### PR TITLE
StateTimeline: Support `NaN` and `null` value mappings

### LINKED ISSUE #92944: StateTimeline: Value mapping for Null + NaN is not working when the query returns Null

### PR DESCRIPTION
**Pull request by fastfrwrd**
**What is this feature?**

`StateTimeline` has controls for mapping NaN, Null, and NaN-or-Null. However, the logic to actually apply these mappings was failing in some cases, so @jesdavpet and I paired as an onboarding task to figure out where the issue was, do a little bit of refactoring to how that's passed between the component and its utils, and clean it up.

🎥 Behaviour for `null` value mappings 🟦 after this bug fix:

https://github.com/user-attachments/assets/fdb3c351-3a7c-447d-82ac-c3c5fbcd1743

> [!NOTE]
> This illustrates correctly that `null` values are not also mapped to `NaN`, that's expected.

To simplify validating these changes, we have added test panels to `gdev` under the dashboard named `StateTimeline - Thresholds & Mappings`.

Screenshot 2025-06-10 at 2 11 02 PM

**Why do we need this feature?**

- Fixes a bug where value mappings for `null` values in data would not render for the `null+nan` option
- Additionally, this applies the same fix for `NaN` values, which was an adjacent problem we discovered

**Who is this feature for?**

Existing and future users of `StateTimeline` who have a null or NaN value and want to map it.

**Which issue(s) does this PR fix?**:

Fixes #92944 

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/core/components/TimelineChart/timeline.ts [hunk 1]
```diff
@@ -209,7 +220,7 @@ export function getConfig(opts: TimelineCoreOptions) {
             for (let ix = 0; ix < dataY.length; ix++) {
               let yVal = dataY[ix];
 
-              if (yVal != null || mappedNull) {
+              if (shouldDrawBox(sidx, yVal)) {
```
Comment (fastfrwrd) [inline public/app/core/components/TimelineChart/timeline.ts]: tldr, the bug was primarily located at the three spots in code we checked `yVal != null || mappedNull`. It didn't account for the `NaN` cases, nor did it account for if `null` was present but NullAndNaN mapping was enabled. we opted to just reorganize things a bit, mostly by accounting for `NaN` and `null` separately.

File: public/app/core/components/TimelineChart/timeline.ts [hunk 2]
```diff
@@ -209,7 +220,7 @@ export function getConfig(opts: TimelineCoreOptions) {
             for (let ix = 0; ix < dataY.length; ix++) {
               let yVal = dataY[ix];
 
-              if (yVal != null || mappedNull) {
+              if (shouldDrawYVal(sidx, yVal)) {
```
Comment (fastfrwrd) [inline public/app/core/components/TimelineChart/timeline.ts:223]: tldr, the bug was primarily located at the three spots in code we checked `yVal != null || mappedNull`. It didn't account for the `NaN` cases, nor did it account for if `null` was present but NullAndNaN mapping was enabled. we opted to just reorganize things a bit, mostly by accounting for `NaN` and `null` separately.

File: public/app/core/components/TimelineChart/timeline.test.ts [hunk 3]
```diff
@@ -0,0 +1,211 @@
...
+              formatValue: () => 'foo',
+            })
+          );
+          const mockUplot = buildMockUplotInstance([[0], [null]]);
+
+          drawClear(mockUplot);
+          drawPaths(mockUplot, 1, 0, 1);
+
+          const { rect } = callOrientCallback(mockUplot);
+          expect(rect).toHaveBeenCalledTimes(2);
```
Comment (fastfrwrd) [inline public/app/core/components/TimelineChart/timeline.test.ts:137]: if we can think of a better proxy for this, I'd be happy to explore it, this number-of-calls check feels brittle.

File: public/app/core/components/TimelineChart/utils.ts [hunk 4]
```diff
@@ -72,6 +73,12 @@ const defaultConfig: PanelFieldConfig = {
   fillOpacity: 80,
 };
 
+/** Checks if a mapped value of the specified type exists for the given field */
+export const hasSpecialMappedValue = (field: Field, match: SpecialValueMatch): boolean =>
+  field.config.mappings?.some(
+    (mapping: ValueMapping): boolean => mapping.type === MappingType.SpecialValue && mapping.options.match === match
+  ) || false;
```
[the remark this answers is not in the document]
Comment (fastfrwrd) [reply public/app/core/components/TimelineChart/utils.ts:80]: I'm all for it - I had a heck of a time getting the other tests working given the need for mocks and invoking callbacks

File: public/app/core/components/TimelineChart/timeline.ts [hunk 5]
```diff
@@ -89,6 +91,17 @@ export function getConfig(opts: TimelineCoreOptions) {
...
+  const shouldDrawYVal = (sidx: number, yVal: number | null): boolean => {
+    if (yVal == null) {
+      return isDiscrete(sidx) && hasMappedNull(sidx);
+    }
+    if (Number.isNaN(yVal)) {
+      return isDiscrete(sidx) && hasMappedNaN(sidx);
+    }
+    return true;
+  };
+
```
Comment (leeoniya) [inline public/app/core/components/TimelineChart/timeline.ts:104]: this one is going to be much more expensive to run.

`isDiscrete(sidx)`, hasMappedNaN(sidx), and `hasMappedNull(sidx)` are invariant for the entire hot loop where this fn is used. there can easily by 2000 values x 30 series rendered at the same time, so this needs to be extremely efficient and not do unnecessary checks for every value. let's restructure to avoid this plz :pray:.

**Review by leeoniya — DISMISSED** [review]

File: public/app/core/components/TimelineChart/timeline.ts (hunk 5 above)
Comment (jesdavpet) [reply public/app/core/components/TimelineChart/timeline.ts:104]: Thanks for this performance related insight @leeoniya. 🚀 Good catch WRT the invariant + hot loop, I'll take a look and see how we can fine tune this a little more.

File: public/app/core/components/TimelineChart/timeline.ts [hunk 6]
```diff
@@ -208,8 +210,10 @@ export function getConfig(opts: TimelineCoreOptions) {
           if (mode === TimelineMode.Changes) {
             for (let ix = 0; ix < dataY.length; ix++) {
               let yVal = dataY[ix];
+              const shouldDrawY =
+                Number.isFinite(yVal) || (yVal == null && mappedNull) || (Number.isNaN(yVal) && mappedNaN);
```
[the remark this answers is not in the document]
Comment (jesdavpet) [reply public/app/core/components/TimelineChart/timeline.ts]: Whoops!  😅 It turns out the `Number.isFinite(...)` condition was overly restrictive FYI and caused a regression:

Screenshot 2025-06-09 at 7 51 44 PM

After reverting this condition to be looser in commit https://github.com/grafana/grafana/pull/105638/commits/36476c4fcba260747d86c98ff047d38701324acc the regression was avoided:

Screenshot 2025-06-09 at 7 51 01 PM

Thanks for pointing this out @leeoniya.

**Comment by jesdavpet** [comment]
👋 😃  Hey @leeoniya + @fastfrwrd, this PR has a few updates and is ready for re-review now!

1. the aforementioned performance improvement was made
2. 2x new test panels have been added to `gdev` under the `StateTimeline - Thresholds & Mappings` dashboard
3. removed the overly restrictive `Number.isFinite(...)` condition, and
4. made sure we allow `0` as well as "truthy" values in the new condition
5. rebased this branch onto latest `main` to freshen it up
6. changelog friendly PR title

Screenshot 2025-06-10 at 2 11 02 PM

**Review by fastfrwrd — COMMENTED** [review]
All of the updates lgtm!

**Review by adela-almasan — APPROVED** [review]
