### PR TITLE
Annotations: Anchor tooltips on click

### LINKED ISSUE #119650: Annotations: Annotation buttons don't have accessible names
**Steps to reproduce**: Open a dashboard with annotations. Look at the buttons for annotations (they are the triangular buttons along the x axis in this screenshot)

Image

**Actual Result**: The annotation buttons should have some kind of name for screenreaders

**Expected Result**: Annotation buttons are missing names. 

**Relevant WCAG Criteria:** https://dequeuniversity.com/rules/axe/4.11/button-name

**Environment**:
- Grafana version: 12.4.0
- Data source type & version: used a Timeseries
- User OS & Browser: Chrome
- Others: n/a

### PR DESCRIPTION
**Pull request by gtk-grafana**
**What is this feature?**
Anchoring annotation tooltips on focus/click.

**Why do we need this feature?**
Tightly clustered annotations are painful to use, and not keyboard accessible.
This PR allows tooltips to stay "pinned" on click or on enter when focused.

**Who is this feature for?**
Users of annotations

**Special notes for your reviewer:**
Clicking on the annotation does not currently toggle the tooltip pin, it only enables, this is due to the setState in ClickOutsideWrapper setting the isPinned state to false immediately before the onClick handler "toggles" the state back to true. While we could move the clickOutsideWrapper to be a parent of the annotation, this would have potential performance impact on panels/dashboards with many annotations, so for now the only way to close a pinned tooltip is to click somewhere else, or to close via the close icon (also added in this PR) within the tooltip.

Ran into a bug with data links: https://github.com/grafana/grafana/issues/119619
Since that is a pre-existing issue I will address in a separate PR. 
Fixes: https://github.com/grafana/grafana/issues/119650

Standalone version of https://github.com/grafana/grafana/pull/111697

**Details**
AnnotationsPlugin2.tsx:
* Adds `pinnedAnnotationId` react state which allows passing in new `isPinned` and `setPinned` props to AnnotationMarker2.

AnnotationMarker2.tsx
* converts the annotation marker `div` to a `button` to allow keyboard navigation
* updates rendering logic to include pinned case
* Prevents hover tooltip while another annotation is pinned

AnnotationEditor2.tsx
* Adds close icon to edit state

AnnotationTooltipHeaderCloseIcon.tsx
* New component to prevent duplication of the close IconButton

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by gtk-grafana** [comment]
@leeoniya wanted to see if we could get around adding the `ClickOutsideWrapper` to close the tooltip when something else is interacted with. I'll try to keep this up to date in case we need to wait for his return from parental leave.

**Comment by gtk-grafana** [comment]
Update, @leeoniya and I want to make sure that this plays nicely with any changes required to the tooltip in the clustering PoC, we want to rule out that the change in state management and use of ClickOutsideWrapper doesn't introduce re-renders that cause flickering like we ran into during the hackathon. Should have an answer in a few days once https://github.com/grafana/grafana/pull/119050 shapes up

File: public/app/plugins/panel/timeseries/plugins/annotations2/AnnotationMarker2.tsx [hunk 1]
```diff
@@ -25,11 +25,13 @@ interface AnnoBoxProps {
   portalRoot: HTMLElement;
   canExecuteActions: boolean;
   replaceVariables: InterpolateFunction;
+  pinAnnotation: (pin: boolean) => void;
```
Comment (leeoniya) [inline public/app/plugins/panel/timeseries/plugins/annotations2/AnnotationMarker2.tsx]: let's rename to `setPinned()`. we already know it's "annotation" :D

Comment (gtk-grafana) [reply public/app/plugins/panel/timeseries/plugins/annotations2/AnnotationMarker2.tsx]: Fixed in https://github.com/grafana/grafana/pull/112134/commits/0b8e34ff831f687cc5fec1f35e0a5ff6de90766a

File: public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin2.tsx [hunk 2]
```diff
@@ -236,9 +233,19 @@ export const AnnotationsPlugin2 = ({
     }
   }, [xAnnos, plot]);
 
+  // Set active annotation tooltip state
+  const setPinnedAnnotationIndex = useCallback((annoIdx: string | undefined) => {
```
Comment (gtk-grafana) [inline public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin2.tsx]: remove callback

Comment (gtk-grafana) [reply public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin2.tsx]: get rid of this method

File: public/app/plugins/panel/timeseries/plugins/annotations2/AnnotationEditor2.tsx [hunk 3]
```diff
@@ -88,6 +99,7 @@ export const AnnotationEditor2 = ({ annoVals, annoIdx, dismiss, timeZone, ...oth
             <>
               <div className={styles.content}>
                 <Field
+                  autoFocus={true}
```
Comment (gtk-grafana) [inline public/app/plugins/panel/timeseries/plugins/annotations2/AnnotationEditor2.tsx]: Doesn't work with wip anno

File: public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin2.test.tsx [hunk 4]
```diff
@@ -0,0 +1,570 @@
...
+    function applyReady() {
+      act(() => {
+        //@ts-ignore
+        hooks.ready(new uPlot());
+      });
+    }
+
+    const annotations = props?.annotations ?? [mockAnnotationFrame];
+    const frames = annotations.map((fr) => createDataFrame(fr));
+    const withOverrides = applyFieldOverrides({
```
Comment (gtk-grafana) [inline public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin2.test.tsx:97]: add todo

File: public/app/plugins/panel/timeseries/plugins/annotations2/AnnotationEditor2.tsx (hunk 3 above)
Comment (gtk-grafana) [reply public/app/plugins/panel/timeseries/plugins/annotations2/AnnotationEditor2.tsx]: fixed in https://github.com/grafana/grafana/pull/112134/commits/8ebd58df8c71a96e14e78175cc83ec0eb8862591

File: public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin2.tsx (hunk 2 above)
Comment (gtk-grafana) [reply public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin2.tsx]: Fixed

File: public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin2.tsx [hunk 5]
```diff
@@ -262,31 +263,43 @@ export const AnnotationsPlugin2 = ({
...
           if (isVisible) {
             style = { left, borderBottomColor: color, top };
-            className = styles.annoMarker;
           }
         }
 
         // @TODO: Reset newRange after annotation is saved
         if (isVisible) {
-          let isWip = frame.meta?.custom?.isWip;
+          const setPinned = (active: boolean) => {
```
Comment (fastfrwrd) [inline public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin2.tsx:278]:
```suggestion
          const annotationKey = getAnnotationKey(frameIdx, i);
          const setPinned = (active: boolean) => {
```

and then use that in the three spots where we called it. string concatenation is not _that_ expensive but better just to avoid multiple calls in the same place.

Comment (gtk-grafana) [reply public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin2.tsx:278]: Fixed in https://github.com/grafana/grafana/pull/112134/commits/f04adfac431dc9b644b30d3ce20a725125e45bd9 (also I introduced a bug in https://github.com/grafana/grafana/pull/112134/commits/8ebd58df8c71a96e14e78175cc83ec0eb8862591 but the tests caught it!)

**Review by fastfrwrd — APPROVED** [review]
Played with this locally and it works well. I ran a11y audits and nothing added in here causes any problems, although I discovered a couple of other simple issues we should address (https://github.com/grafana/grafana/issues/119650, https://github.com/grafana/grafana/issues/119651)

Thanks for all the tests and for running the team through the code!

File: public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin2.tsx (hunk 5 above)
Comment (fastfrwrd) [reply public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin2.tsx:278]: thank uuu

**Comment by fastfrwrd** [comment]
(One more accessibility follow-up I filed: https://github.com/grafana/grafana/issues/119654)

**Comment by gtk-grafana** [comment]
@fastfrwrd I just pushed a [commit](https://github.com/grafana/grafana/pull/112134/commits/cf445e5296d63609fbd124787369871850cb019d) with a fix for https://github.com/grafana/grafana/issues/119650 since that is very arguably in scope of this PR as buttons were not keyboard/screen reader accessible before this PR.

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/22732949497)
- Version: 13.0.0-22732949497
