### PR TITLE
Explore: Show all dataFrames in data tab in Inspector

### LINKED ISSUE #31504: Inspect Data: Only the first data frame is downloadable for LogsPanel
**What happened**:
Observed in https://github.com/grafana/grafana/issues/31247 that is mentioning other LogsPanel-related issue.  
When we receive multiple DataFrames in LogsPanel, it is possible to Download in CSV format only the first DataFrame. 

**What you expected to happen**:
To be able to either download all DataFrames, or to have an option to select which DataFrames to download. 

**How to reproduce it (as minimally and precisely as possible)**:
https://user-images.githubusercontent.com/30407135/109287891-7874ac00-7824-11eb-9d2c-60e21a990063.mov

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.3
- Grafana plugins: LogsPanel

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
In Explore's Inspector and when using Panel Inspect with Logs panel, we weren't able to see/download all dataFrames, just the first one. See this on current master:
image

This PR fixes it and makes sure, that when we have multiple dataFrames, we will get the Show data frame option in Explore and LogsPanel. See this branch: 
image

**Which issue(s) this PR fixes**:

Related to https://github.com/grafana/grafana/issues/28752
Fixes https://github.com/grafana/grafana/issues/31504

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/inspector/InspectDataTab.tsx [hunk 1]
```diff
@@ -227,7 +223,7 @@ export class InspectDataTab extends PureComponent<Props, State> {
                 >
                   <Switch
                     value={!!options.withTransforms}
-                    onChange={() => onOptionsChange({ ...options, withTransforms: !options.withTransforms })}
+                    onChange={() => onOptionsChange!({ ...options, withTransforms: !options.withTransforms })}
```
Comment (ivanahuckova) [inline public/app/features/inspector/InspectDataTab.tsx:226]: Not sure why, but event though we check if **showPanelTransformationsOption** is truthy - `{showPanelTransformationsOption && (` and in **showPanelTransformationsOption** we are checking that we have **onOptionsChange** `const showPanelTransformationsOption = onOptionsChange &&`, typescript was still throwing warning.

File: public/app/features/inspector/InspectDataTab.test.tsx [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+      expect(screen.getByLabelText(/Panel inspector Data content/i)).toBeInTheDocument();
+    });
+    it('should render Data Option row', () => {
+      render(<InspectDataTab {...createProps()} />);
+      expect(screen.getByText(/Data options/i)).toBeInTheDocument();
+    });
+    it('should show available options', () => {
+      render(<InspectDataTab {...createProps()} />);
+      const dataOptions = screen.getByText(/Data options/i);
+      fireEvent.click(dataOptions);
```
Comment (hugohaggmark) [inline public/app/features/inspector/InspectDataTab.test.tsx:51]: If you want to simulate a user clicking on something you should use userEvent.click instead.
https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-testing-libraryuser-event

File: public/app/features/inspector/InspectDataTab.tsx [hunk 3]
```diff
@@ -167,18 +167,17 @@ export class InspectDataTab extends PureComponent<Props, State> {
...
-    const panelTransformations = panel.getTransformations();
+    const panelTransformations = panel?.getTransformations();
     const showPanelTransformationsOption =
-      panelTransformations && panelTransformations.length > 0 && (transformId as any) !== 'join by time';
-    const showFieldConfigsOption = !panel.plugin?.fieldConfigRegistry.isEmpty();
-    const showDataOptions = showPanelTransformationsOption || showFieldConfigsOption;
+      onOptionsChange &&
+      panelTransformations &&
+      panelTransformations.length > 0 &&
+      (transformId as any) !== 'join by time';
```
Comment (hugohaggmark) [inline public/app/features/inspector/InspectDataTab.tsx:179]: nit: I think this can be simplified into:
```suggestion
      onOptionsChange &&
      Boolean(panelTransformations?.length) &&
      (transformId as any) !== 'join by time';
```

File: public/app/features/inspector/InspectDataTab.tsx (hunk 1 above)
Comment (hugohaggmark) [reply public/app/features/inspector/InspectDataTab.tsx:226]: I don't think Typescript knows if onOptionsChange is defined here. Previously the code returned null when onOptionsChange wasn't defined.

Comment (hugohaggmark) [reply public/app/features/inspector/InspectDataTab.tsx:226]: Not sure this is part of the scope for this PR but I think the `renderDataOptions` deserves its own React component(s). The `InspectDataTab` class is just getting bigger if we don't refactor it soon.

Comment (hugohaggmark) [inline public/app/features/inspector/InspectDataTab.tsx:226]: nit: I think we should try to avoid arrow function where possible

**Review by hugohaggmark — APPROVED** [review]
Looks good and works as expected 🎉  I left some comments for consideration.

File: public/app/features/inspector/InspectDataTab.tsx (hunk 1 above)
Comment (ivanahuckova) [reply public/app/features/inspector/InspectDataTab.tsx]: Yeah, not scope of this PR, but I totally agree.

File: public/app/features/inspector/InspectDataTab.test.tsx (hunk 2 above)
Comment (ivanahuckova) [reply public/app/features/inspector/InspectDataTab.test.tsx]: Thanks for sharing!
