### PR TITLE
Postgres: Fix the handling of a null return value in query results

### LINKED ISSUE #36538: Postgres query returning null values works in v7 but fails in v8
A Postgres query that returns null in some columns for some rows fails in both the Graph and Time Series panels on Grafana v 8.0.4.:

Screen Shot 2021-07-07 at 6 02 13 PM

pgAdmin showing that the same query works fine there:
Screen Shot 2021-07-07 at 6 03 38 PM

Null values in some columns for some rows:
Screen Shot 2021-07-07 at 6 04 03 PM

Screen Shot 2021-07-07 at 6 04 50 PM

- Grafana 8.0.4 installed on macOS 11.3 via Homebrew running in Safari
- Postgres 13.3 (but set as v12 in the data source options since there is no option for v13)

The same query and panel works in fine in v 7.5.7.

### PR DESCRIPTION
**Pull request by idafurjes**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #36538

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/tsdb/postgres/postgres_test.go [hunk 1]
```diff
@@ -143,7 +143,7 @@ func TestGenerateConnectionString(t *testing.T) {
 }
 
 // To run this test, set runPostgresTests=true
-// Or from the commandline: GRAFANA_TEST_DB=postgres go test -v ./pkg/tsdb/postgres
+// Or from the commandline: GRAFANA_TEST_DB=postgres go test -tags=integration -v ./pkg/tsdb/postgres
```
Comment (ying-jeanne) [inline pkg/tsdb/postgres/postgres_test.go:146]: nice!

File: pkg/tsdb/postgres/postgres_test.go [hunk 2]
```diff
@@ -222,7 +222,7 @@ func TestPostgres(t *testing.T) {
 
 		sql = `
 			INSERT INTO postgres_types VALUES(
-				1,2,3,
+				null,2,3,
```
Comment (ying-jeanne) [inline pkg/tsdb/postgres/postgres_test.go:225]: maybe we can have both, nullable and no nullable both tested. insert one more value instead of replacing the current one with null.

**Review by ying-jeanne — COMMENTED** [review]
LGTM, just one thing on the test.

File: pkg/tsdb/postgres/postgres_test.go (hunk 2 above)
Comment (idafurjes) [reply pkg/tsdb/postgres/postgres_test.go]: I added a new column

**Review by ying-jeanne — APPROVED** [review]
