### PR TITLE
table panel: assume string dates to be on UTC

### LINKED ISSUE #44708: Table Panel: String dates should be parsed assuming utc instead of local time
**What happened**:
When using the Table panel, date strings without timzone information are assumed to be in users' local timezone, unlike numeric dates which are always assumed to be UTC.

This cause issues when different people from different timezones are looking at the same dashboards as with the same data they'll see different results.

There's already an open PR to fix this behavior in the logs panel at https://github.com/grafana/grafana/pull/44664 with steps to reproduce the issue, and the thing happens in the table panel.

**What you expected to happen**:
String and numeric dates should be assumed to be UTC regardless of their type if no timezone is explicitly set.

**How to reproduce it (as minimally and precisely as possible)**:

Using `elasticsearch77`, create an index and insert a document having a date without timezone info:

```
curl -XPUT http://localhost:13200/without-tz -H "Content-Type: application/json" -d '{"mappings": {"properties": {"@timestamp": {"type": "date", "format": "yyyy-MM-dd HH:mm:ss"}}}}'

curl -XPUT http://localhost:13200/without-tz/_doc/example -H "Content-Type: application/json" -d '{ "@timestamp": "2022-01-31 13:30:00", "foo": "bar" }'
```

then configure the datasource to use that index (without-tx) and create a dashboard with 2 panels:

  -  count group by date histogram (timeseries panel)
  - logs or raw data (table panel).

now, depending on the timezone you live in (if you are in a UTC-like timezone then go in another country. changing your computer timezone manually works as well) you'll see that the logs panel time is not aligned with the one from the timeseries panel.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: N/A
- OS Grafana is installed on: 
- User OS & Browser: MacOs / FF 89
- Grafana plugins: N/A
- Others:

### PR DESCRIPTION
**Pull request by kirederik**
fixes #44708

### CODE REVIEW

File: packages/grafana-data/src/field/displayProcessor.ts [hunk 1]
```diff
@@ -77,7 +77,7 @@ export function getDisplayProcessor(options?: DisplayProcessorOptions): DisplayP
     const isStringUnit = unit === 'string';
 
     if (hasDateUnit && typeof value === 'string') {
-      value = dateTime(value).valueOf();
+      value = toUtc(value).valueOf();
```
Comment (dprokop) [inline packages/grafana-data/src/field/displayProcessor.ts:80]: Think we should default to UTC only if the display processor is not configured with a timezone (it can be passed via display processor's options).

**Review by oscarkilhed — APPROVED** [review]
Looks good! I created a [PR to this branch](https://github.com/grafana/grafana/pull/47259) with some tests I used to figure out what was going on. You can merge it to this branch if you want to.

**Review by mdvictor — APPROVED** [review]

File: packages/grafana-data/src/field/displayProcessor.ts (hunk 1 above)
Comment (dprokop) [reply packages/grafana-data/src/field/displayProcessor.ts:80]: ah wait, ignore the comment above. We are talking date strings here. Thanks @oscarkilhed for the tests, this made it slightly clearer.

**Comment by kirederik** [comment]
Awesome, thanks @oscarkilhed. Merged the tests in!

**Review by Elfo404 — APPROVED** [review]
great stuff!
