### PR TITLE
Server: Fix failure to start with "bind: address already in use" when using socket as protocol

### LINKED ISSUE #20672: Grafana fails to start with "bind: address already in use" in `protocol = socket` mode
**What happened**: After upgrade from 6.4.2 to 6.5.0, my Grafana instance fails to start with 
```
failed to open listener on address 0.0.0.0:3000: listen tcp 0.0.0.0:3000: bind: address already in use
```

The port 3000 is indeed used on this machine, but this should not be a problem since my configuration also specifies

```
protocol = socket
socket = /run/grafana/grafana.sock
```

Setting `http_port` to some random (valid, unbound) value allows Grafana to start. After starting, it will duly listen on the provided socket and `netstat -antp  | grep LISTEN | grep 14482` returns nothing. This command duly returns `grafana-server` when setting `protocol` to `http`.

**What you expected to happen**: the server should start normally, independently of the bound state of port 3000

**How to reproduce it (as minimally and precisely as possible)**: make any program listen on port 3000, and configure grafana with
```
protocol = socket
```

then try to start `grafana-server`.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: N/A
- OS Grafana is installed on:  Debian buster, ARM platform
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others:

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Clean up the Grafana server startup logic and error checking within, _plus_ don't fail if in Unix socket mode and the TCP port is taken.

Differently from the old logic, it carries out all setup and opening of the listener before it spawns a goroutine to shut down the server when the context is done (so the second goroutine won't spawn until we're clear of errors and ready to serve). I think this is a much cleaner and robust approach in case errors should happen. It also waits for the shutdown goroutine to finish, as this is recommended by the official [documentation](https://golang.org/pkg/net/http/#Server.Shutdown).

**Which issue(s) this PR fixes**:
Fixes #20672

### CODE REVIEW

File: pkg/api/http_server.go [hunk 1]
```diff
@@ -84,84 +83,97 @@ func (hs *HTTPServer) Init() error {
...
 
-	return err
+	wg.Wait()
+
+	return nil
 }
 
-func (hs *HTTPServer) listenAndServeTLS(listener net.Listener, certfile, keyfile string) error {
-	if certfile == "" {
+func (hs *HTTPServer) configureHttps() error {
```
Comment (xlson) [inline pkg/api/http_server.go]: might want to go for hs.cfg here as to not depend on the global settings object if we dont have to. But we probably dont have that option

**Review by xlson — APPROVED** [review]
Great work!

**Review by papagian — APPROVED** [review]
LGTM
Nice work!

File: pkg/api/http_server.go [hunk 2]
```diff
@@ -84,84 +83,97 @@ func (hs *HTTPServer) Init() error {
...
+	default:
+		hs.log.Error("Invalid protocol", "protocol", setting.Protocol)
+		return fmt.Errorf("invalid protocol %q", setting.Protocol)
+	}
 
-		err = hs.httpSrv.Serve(ln)
-		if err != nil {
-			hs.log.Debug("server was shutdown gracefully", "err", err)
-			return nil
+	hs.log.Info("HTTP Server Listen", "address", listener.Addr().String(), "protocol",
```
Comment (marefr) [inline pkg/api/http_server.go]: Would move this one up to line 108 (`case setting.HTTP, setting.HTTPS, setting.HTTP2:`) and possible add an info log for the `case setting.SOCKET:` as well.

File: pkg/api/http_server.go [hunk 3]
```diff
@@ -84,84 +83,97 @@ func (hs *HTTPServer) Init() error {
...
+	var wg sync.WaitGroup
+	wg.Add(1)
+
+	// handle http shutdown on server context done
+	go func() {
+		<-ctx.Done()
+		if err := hs.httpSrv.Shutdown(context.Background()); err != nil {
+			hs.log.Error("Failed to shutdown server", "error", err)
+		}
+		wg.Done()
```
Comment (marefr) [inline pkg/api/http_server.go]: `defer wg.Done()` before `<-ctx.Done()`?

File: pkg/api/http_server.go [hunk 4]
```diff
@@ -84,84 +83,97 @@ func (hs *HTTPServer) Init() error {
...
+			if err == http.ErrServerClosed {
+				hs.log.Debug("server was shutdown gracefully")
+				return nil
+			}
+			return err
 		}
 	default:
-		hs.log.Error("Invalid protocol", "protocol", setting.Protocol)
-		err = errors.New("Invalid Protocol")
+		panic(fmt.Sprintf("Unhandled protocol %q", setting.Protocol))
```
Comment (marefr) [inline pkg/api/http_server.go]: Here you panic but on line 127 you're logging and returning an error?

**Review by marefr — CHANGES_REQUESTED** [review]
Some minor changes I would like to see. In general feels a bit weird with 3 different switch cases of protocol - is it possible to fix or at least break out in functions?

Idea (maybe bigger refactoring):
- new interface `HttpServer`
- `NewHttpServer(context, settings)` - factory method for returning HttpServer of certain type and configure it (configure https or http2) etc
- `func (h *HttpServer) ListenAndServe() error` - new method encapsulating the logic for creating listener, adding shut down on server context done and then serving the protocol specific `Serve` or `ServeTLS` of http.HttpServer.
- maybe want to move certain global settings (setting package) to `setting.Cfg` struct.

File: pkg/api/http_server.go (hunk 4 above)
Comment (aknuds1) [reply pkg/api/http_server.go]: The reason for the panic here is that an unhandled protocol at this stage is a programming error, not an error by the caller.

File: pkg/api/http_server.go (hunk 3 above)
Comment (aknuds1) [reply pkg/api/http_server.go]: I can make the change, but is there any practical difference between the two here?

File: pkg/api/http_server.go (hunk 2 above)
Comment (aknuds1) [reply pkg/api/http_server.go]: @marefr It doesn't make sense to move this log message as-is to the HTTP/HTTPS/HTTP2 case at least, since it is general to all cases (for example, the "protocol" tag describes the protocol in use, and the "socket" tag will describe the Unix socket if that is configured).

File: pkg/api/http_server.go (hunk 3 above)
Comment (marefr) [reply pkg/api/http_server.go]: In case the Shutdown panics for some reason

**Comment by aknuds1** [comment]
> Some minor changes I would like to see. In general feels a bit weird with 3 different switch cases of protocol - is it possible to fix or at least break out in functions?
> 
> Idea (maybe bigger refactoring):
> 
> * new interface `HttpServer`
> * `NewHttpServer(context, settings)` - factory method for returning HttpServer of certain type and configure it (configure https or http2) etc
> * `func (h *HttpServer) ListenAndServe() error` - new method encapsulating the logic for creating listener, adding shut down on server context done and then serving the protocol specific `Serve` or `ServeTLS` of http.HttpServer.
> * maybe want to move certain global settings (setting package) to `setting.Cfg` struct.

@marefr Not sure about how to refactor yet, but I've also thought that global settings should be passed via a local parameter. The old code was using locals and globals inconsistently though, so it was better to make it consistent.

File: pkg/api/http_server.go (hunk 2 above)
Comment (marefr) [reply pkg/api/http_server.go]: Yeah so I mean keep the old log message which was for http/https/http2 so you'll get specific log message for http* and specific log message for socket..

File: pkg/api/http_server.go (hunk 3 above)
Comment (aknuds1) [reply pkg/api/http_server.go]: @marefr OK I'll make a PR.
