### PR TITLE
Explore: Fix jumpy live tailing

### LINKED ISSUE #30634: Live tailing also scroll the main view
**What happened**:

Trying to read the bottom of my page but I'm fighting with the auto scroll of loki live-tailing

**What you expected to happen**:

I can freely scroll my main page while loki data is refreshing.

**How to reproduce it (as minimally and precisely as possible)**:

Just tail some logs with multiple queries editor.

https://user-images.githubusercontent.com/1053421/105837387-a3a57a80-5f9c-11eb-8a03-e8213e1b658e.mov

**Environment**:
- Grafana version: Grafana v7.5.0-10872pre (10aabe8ce3)
- Data source type & version: Loki
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
I have simplified the way how we scroll the view and removed jumpy screen. 

Current master:
Kapture 2021-01-26 at 17 40 01

Fixed:
Kapture 2021-01-26 at 17 37 33

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/30634

### CODE REVIEW

File: public/app/features/explore/LiveLogs.tsx [hunk 1]
```diff
@@ -73,25 +72,6 @@ class LiveLogs extends PureComponent<Props, State> {
     };
   }
 
-  componentDidUpdate(prevProps: Props) {
```
Comment (aocenas) [inline public/app/features/explore/LiveLogs.tsx:76]: So what this did was to allow user to pause the live view by just scrolling the view up. Rationale was if you want to focus on some line then you don't wont that line to jump up all the time and you have to chase it. Because we were also scrolling the view to the bottom line every time when not paused, this was needed to figure out if user scrolled up, or if new lines appeared and that is why the view scroll position is not at the bottom.

Comment (aocenas) [reply public/app/features/explore/LiveLogs.tsx:76]: I have a feeling the issue is I did not though there would be 2 scroll views. I though when live tailing the page would have fixed 100% height and only the internal log view would be scrolling

Comment (ivanahuckova) [reply public/app/features/explore/LiveLogs.tsx:76]: Yeah, when I was playing with live tailing that was always the case as I did just 1 query that was 1 line-long. However, if you have more queries/long queries, you get the second scroll area. And we can't remove it, cause if you hae multiple queries + small display, you would end up with very narrow live tailing window.

But anyway, I have tested my solution and it still works in a way where if you scroll, it pause the live tailing.

Comment (aocenas) [reply public/app/features/explore/LiveLogs.tsx:76]: Hmm you are right. Don't like thinking that this elaborate code actually did not do anything substantial but seems to be the case :D

**Review by aocenas — APPROVED** [review]
