### PR TITLE
CloudWatch: Fix query editor does not render in Explore

### LINKED ISSUE #20805: CloudWatch: Query editor does not render in Explore mode

### PR DESCRIPTION
**Pull request by davkal**
- the datasource plugin module API was changed recently so that it no longer falls back on the panel editor in Explore, now it needs to be explicitly set
- this PR sets the cloudwatch explore query field to be the same as the query editor
- needed to change editor types to satisfy explore query field interface

Fixes: #20805

### CODE REVIEW

**Review by sunker — APPROVED** [review]
Great! Tested and it works fine.

**Comment by sunker** [comment]
@davkal added this to 6.5.2 milestone

File: public/app/plugins/datasource/cloudwatch/components/QueryEditor.tsx [hunk 1]
```diff
@@ -1,12 +1,12 @@
...
-import { SelectableValue, QueryEditorProps } from '@grafana/data';
+import { SelectableValue, ExploreQueryFieldProps } from '@grafana/data';
 import { Input, Segment, SegmentAsync, ValidationEvents, EventsWithValidation, Switch } from '@grafana/ui';
 import { CloudWatchQuery } from '../types';
 import CloudWatchDatasource from '../datasource';
 import { SelectableStrings } from '../types';
 import { Stats, Dimensions, QueryInlineField, QueryField, Alias } from './';
 
-export type Props = QueryEditorProps<CloudWatchDatasource, CloudWatchQuery>;
+export type Props = ExploreQueryFieldProps<CloudWatchDatasource, CloudWatchQuery>;
```
Comment (torkelo) [inline public/app/plugins/datasource/cloudwatch/components/QueryEditor.tsx]: Ok for a quick fix, but really wish we could unify these interfaces, I see very recently that ExploreQueryFieldProps has now a NEW prop in master (compared to 6.5) (absoluteRange?: ) the plan was to get rid of the differences not expand them. Can't find the PR where this was added, do you know?  

history could be handled easily internally by each editor, and onBlur could be added to main interface. not sure what this absoluteRange is used for. PanelData has a timeRange property already.

**Review by torkelo — APPROVED** [review]

File: public/app/plugins/datasource/cloudwatch/components/QueryEditor.tsx (hunk 1 above)
Comment (torkelo) [reply public/app/plugins/datasource/cloudwatch/components/QueryEditor.tsx]: or query history could potentially be made into a more universal feature that we can shared between dashboard / explore.
