### PR TITLE
Prometheus: Add info that using Loki as Prometheus data source is no longer supported and might stop working

### LINKED ISSUE #33657: Prometheus: When Loki data source connected, querying doesn't work
**What happened**:
Using Loki as Prometheus data source doesn't work: 
image

It used to work in the past.

**What you expected to happen**:
Possibility to query Loki with Prometheus data source type.

**How to reproduce it (as minimally and precisely as possible)**:
1. Set up Loki as Prometheus data source

image

2. Try to run the query - it throws error

**Environment**:
- Grafana version: 7.5.4
- Data source type & version: Prometheus

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
In Grafana 8, we are introducing metrics browser for Prometheus and changing default http method to POST. These changes will affect our users who use Loki as Prometheus data source as Loki doesn't support POST at couple of endpoints and metric browser is not usable as well.

At this point, Loki supports alerting and therefore we have decided that we will not longer support Loki as Prometheus data source. In this PR, we are adding hint/info for users to use Loki data source for their Loki instance. 

However, it is still usable - I have fixed error due to no received metrics from Loki, but it is informing users that it can break anytime and they should change the data source to Loki. 

image

Lastly, it slightly refactors the hinting logic. In the past, we always showed hints only after data were received. However, some of the hints (for example disabling of lookup) are helpful before we send the query. In the same way, this is helpful for this new Loki-related hint. Therefore now, we are showing initial hints (non-query related) even before we write a query. 

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/33657

### CODE REVIEW

**Comment by ivanahuckova** [comment]
@achatterjee-grafana Could you please check this copy: 
```
Using Loki as Prometheus data source is no longer supported and might stop working. Please use Loki data source for your Loki instance.
```

Basically in the past we were fully supporting using Loki with Prometheus data source because Loki didn't support alerting. But now it does and we decided to not to support it anymore. Nothing really breaks in 8.0 - they can still use it, but we want to inform users that they should switch to Loki data source as it might break in the future.

**Comment by achatterjee-grafana** [comment]
> ```
> Using Loki as Prometheus data source is no longer supported and might stop working. Please use Loki data source for your Loki instance.
> ```

@ivanahuckova, how about:

Using Loki as a Prometheus data source is no longer supported. You must use the Loki data source for your Loki instance.

File: public/app/plugins/datasource/prometheus/query_hints.ts [hunk 1]
```diff
@@ -127,3 +127,28 @@ export function getQueryHints(query: string, series?: any[], datasource?: Promet
...
+export function getInitHints(datasource?: PrometheusDatasource): QueryHint[] {
+  const hints = [];
+  if (!datasource) {
+    return [];
+  }
+
+  // Hint if using Loki as Prometheus data source
+  if (datasource.directUrl.includes('/loki') && !datasource.languageProvider.metrics.length) {
+    hints.push({
+      label: `Using Loki as Prometheus data source is no longer supported and might stop working. Please use Loki data source for your Loki instance.`,
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/prometheus/query_hints.ts:140]:
```suggestion
      label: `Using Loki as a Prometheus data source is no longer supported. You must use the Loki data source for your Loki instance.`,
```

**Review by achatterjee-grafana — APPROVED** [review]
LGTM

File: public/app/plugins/datasource/prometheus/datasource.ts [hunk 2]
```diff
@@ -734,6 +734,10 @@ export class PrometheusDatasource extends DataSourceApi<PromQuery, PromOptions>
     return getQueryHints(query.expr ?? '', result, this);
   }
 
+  getInitHints() {
+    return getInitHints(this);
```
Comment (aocenas) [inline public/app/plugins/datasource/prometheus/datasource.ts:738]: This seems a bit weird. Like why isn't it `this.getInitHints()`? We don't reuse it anywhere.

File: public/app/plugins/datasource/prometheus/query_hints.ts [hunk 3]
```diff
@@ -127,3 +127,28 @@ export function getQueryHints(query: string, series?: any[], datasource?: Promet
 
   return hints;
 }
+
+export function getInitHints(datasource?: PrometheusDatasource): QueryHint[] {
```
Comment (aocenas) [inline public/app/plugins/datasource/prometheus/query_hints.ts:131]: As we use it in single place, from data source so it is always present the optionality of datasource argument looks bit off.

**Comment by aocenas** [comment]
Another nitpick, the hint seems to have some clickable styling, dimming a bit on hover but hasn't any action.

**Review by aocenas — APPROVED** [review]

File: public/app/plugins/datasource/prometheus/query_hints.ts (hunk 3 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/prometheus/query_hints.ts]: Yeah, good point. I made this argument non-optional.

File: public/app/plugins/datasource/prometheus/datasource.ts (hunk 2 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/prometheus/datasource.ts:738]: We are importing this function from `./query_hints` where it is with `getQueryHints`. I think the point was to have `datasource.ts` smaller and not have all the different hints in separate file. I honestly like them together there rather than having 1 hinting function in `datasource.ts` and other in `query_hints.ts`.
