### PR TITLE
Multi-LDAP: Do not fail-fast on invalid credentials

### LINKED ISSUE #19066: Grafana 6.3.5 doesn't fall through to next LDAP server when Bind fails with ErrInvalidCredentials
**What happened**:

Grafana doesn't attempt successive LDAP servers configured in `ldap.toml` when the first authenticated bind fails due to an `ErrInvalidCredentials` error.

**What you expected to happen**:

Grafana falls through to the next LDAP service configured. Like the behaviour in Grafana 6.3.4 for example.

**How to reproduce it (as minimally and precisely as possible)**:

Set up two LDAP servers in `ldap.toml` where the first authenticated bind will fail. Observe that a bind to the the second isn't attempted

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.5
- Data source type & version:
- OS Grafana is installed on: Alpine as per official Grafana docker image.
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others:

**Potential Patch**:

```
diff --git a/pkg/services/multildap/multildap.go b/pkg/services/multildap/multildap.go
index 07c19b19f..23a3c1e00 100644
--- a/pkg/services/multildap/multildap.go
+++ b/pkg/services/multildap/multildap.go
@@ -78,8 +78,8 @@ func (multiples *MultiLDAP) Login(query *models.LoginUserQuery) (
                        return user, nil
                }
 
-               // Continue if we couldn't find the user
-               if err == ErrCouldNotFindUser {
+               // Continue if we couldn't find the user or the credentials are invalid
+               if err == ErrCouldNotFindUser || err == ErrInvalidCredentials {
                        continue
                }
 
diff --git a/pkg/services/multildap/multildap_test.go b/pkg/services/multildap/multildap_test.go
index 03951122e..803a0214a 100644
--- a/pkg/services/multildap/multildap_test.go
+++ b/pkg/services/multildap/multildap_test.go
@@ -101,6 +101,25 @@ func TestMultiLDAP(t *testing.T) {
                                teardown()
                        })
 
+                       Convey("Should still call a second error for invalid credentials error", func() {
+                               mock := setup()
+
+                               mock.loginErrReturn = ErrInvalidCredentials
+
+                               multi := New([]*ldap.ServerConfig{
+                                       {}, {},
+                               })
+                               _, err := multi.Login(&models.LoginUserQuery{})
+
+                               So(mock.dialCalledTimes, ShouldEqual, 2)
+                               So(mock.loginCalledTimes, ShouldEqual, 2)
+                               So(mock.closeCalledTimes, ShouldEqual, 2)
+
+                               So(err, ShouldEqual, ErrInvalidCredentials)
+
+                               teardown()
+                       })
+
                        Convey("Should return unknown error", func() {
                                mock := setup()

```


**Discussion**

From what I can make out of `pkg/services/ldap/ldap.go`; the `ErrCouldNotFindUser` error will only be hit if the authenticated bind succeeds but the `search_filter` yields zero results in the `Login()` function.

https://github.com/grafana/grafana/pull/18588 fixes the fall through for the `ErrCouldNotFindUser` case but breaks it for the invalid credentials case.
I.e.

```
diff --git a/pkg/services/multildap/multildap.go b/pkg/services/multildap/multildap.go                                                                                
index d2560d07e..07c19b19f 100644                                                         
--- a/pkg/services/multildap/multildap.go                                                                                                                         
+++ b/pkg/services/multildap/multildap.go                                               
@@ -19,6 +19,9 @@ var newLDAP = ldap.New                                             
 // ErrInvalidCredentials is returned if username and password do not match                                                                                                                                                                                                                                                                                                                                                           
 var ErrInvalidCredentials = ldap.ErrInvalidCredentials              
                                                                                                                                                                                  
+// ErrCouldNotFindUser is returned when username hasn't been found (not username+password)                                             
+var ErrCouldNotFindUser = ldap.ErrCouldNotFindUser                                                                                                                                
+                                                                         
 // ErrNoLDAPServers is returned when there is no LDAP servers specified                                                      
 var ErrNoLDAPServers = errors.New("No LDAP servers are configured")
                                                                                                              
@@ -76,7 +79,7 @@ func (multiples *MultiLDAP) Login(query *models.LoginUserQuery) (
                }

                // Continue if we couldn't find the user
-               if err == ErrInvalidCredentials {
+               if err == ErrCouldNotFindUser {
                        continue
                }
```

This doesn't work for our use-case, as we expect to fall through to successive configured LDAP servers when the authentication fails. Suggest grandfathering the old behaviour by continuing on either.

### PR DESCRIPTION
**Pull request by gotjosh**
**What this PR does / why we need it**:

When configuring LDAP authentication, it is very common to have multiple
servers configured. When using user bind (authenticating with LDAP using
the same credentials as the user authenticating to Grafana) we don't
expect all the users to be on all LDAP servers.

Because of this use-case, we should not fail-fast when authenticating on
a multiple LDAP server configuration. Instead, we should continue to try
the credentials with the next LDAP server configured.

Fixes #19066

### CODE REVIEW

File: pkg/services/multildap/multildap_test.go [hunk 1]
```diff
@@ -152,6 +152,25 @@ func TestMultiLDAP(t *testing.T) {
 				teardown()
 			})
 
+			Convey("Should still call a second error for invalid credentials error", func() {
```
Comment (xlson) [inline pkg/services/multildap/multildap_test.go]:
```suggestion
			Convey("Should still try to auth with the second server after receiving an invalid credentials error from the first", func() {
```

**Review by xlson — APPROVED** [review]
Looks good.

I will create two new issues based on our discussion previously.

1. If Dial fails but there are at least one more server left, the next server should be tried
2. When authentication with an admin user failure to auth with ldap should result in an error log
