### PR TITLE
Tooltip: Make active series more noticeable

### LINKED ISSUE #35397: Active series in the tooltip is not highlighted enough in 8.0.0
**What happened**:
I upgraded from 7.5.7 to 8.0.0, and the tooltip no longer highlights the series name the mouse cursor points to.

One old instance that hasn't been upgraded still works like before so this should not be that my browser has been upgraded.

**What you expected to happen**:
Nothing broken.

**How to reproduce it (as minimally and precisely as possible)**:
Just add more than one series into a graph and set "Tooltip mode" to "All". Move the mouse cursor to the data points.

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: graphite 1.1.3
- OS Grafana is installed on: Arch Linux
- User OS & Browser: Arch Linux, Firefox 91.0a1
- Grafana plugins: none.
- Others:

### PR DESCRIPTION
**Pull request by nikki-kiga**
Fixes #35397

### It was previously harder to see the difference between the active series and the other series. 

_The following screenshots are taken on Firefox on macOS._

Before the tooltip looked like this:
before

Currently in this PR the color is set to the maxContrast color but it also could be changed to warning or info text, whichever is preferred.

**MaxContrast Color**
colors-text-maxContrast

**Warning Text Color**
colors-warning-text
colors-warning-text2

**Info Text Color**
colors-info-text
colors-info-text2

### CODE REVIEW

**Comment by ryantxu** [comment]
+1 for MaxContrast -- adding colors conflicts with series colors

File: packages/grafana-ui/src/components/VizTooltip/SeriesTable.tsx [hunk 1]
```diff
@@ -14,10 +14,10 @@ export interface SeriesTableRowProps {
   isActive?: boolean;
 }
 
-const getSeriesTableRowStyles = (theme: GrafanaTheme) => {
+const getSeriesTableRowStyles = (theme: GrafanaTheme2) => {
   return {
     icon: css`
-      margin-right: ${theme.spacing.xs};
+      margin-right: ${theme.v1.spacing.xs};
```
Comment (dprokop) [inline packages/grafana-ui/src/components/VizTooltip/SeriesTable.tsx:20]: Instead of using v1 reference, you can use `theme.spacing(factor)` to get the desired value :)

You can read a bit more about the GrafanaTheme2 in this document: https://github.com/grafana/grafana/blob/main/contribute/style-guides/themes.md#paddings-and-margins

File: packages/grafana-ui/src/components/VizTooltip/SeriesTable.tsx [hunk 2]
```diff
@@ -34,13 +34,14 @@ const getSeriesTableRowStyles = (theme: GrafanaTheme) => {
       word-break: break-all;
     `,
     value: css`
-      padding-left: ${theme.spacing.md};
+      padding-left: ${theme.v1.spacing.md};
     `,
     activeSeries: css`
-      font-weight: ${theme.typography.weight.bold};
+      font-weight: ${theme.typography.fontWeightBold};
+      color: ${theme.colors.text.maxContrast};
```
Comment (dprokop) [inline packages/grafana-ui/src/components/VizTooltip/SeriesTable.tsx:41]: I think maxContrast is great, it's so much better now

**Review by dprokop — APPROVED** [review]
This looks really good now @nikki-kiga! Left one nit about theme spacing, other than that it's great 👌
