### PR TITLE
Alerting: Fix saving of screenshots uploaded with a signed url

### LINKED ISSUE #53566: Failed to save screenshots uploaded with a signed url
**What happened**:

An error occurs while saving the metadata of unified alerts screenshots uploaded to an external image storage.

Logs:

```
grafana logger=ngalert t=2022-08-11T05:23:02.217652653Z level=warn msg="failed to generate a screenshot for an alert instance" alert_rule=1odSl7m4k dashboard=G9jnlni4k panel=2 err="failed to save image: failed to insert screenshot: Error 1406: Data too long for column 'url' at row 1"
```

**What you expected to happen**:

The metadata is saved successfully.
 
**How to reproduce it (as minimally and precisely as possible)**:

- Enable Grafana unified alerting screenshot capture and upload to a external storage with signed urls, in our case we are using "gcs".

Our config:

```
- name: GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE
   value: "true"
- name: GF_UNIFIED_ALERTING_SCREENSHOTS_UPLOAD_EXTERNAL_IMAGE_STORAGE
   value: "true"
- name: GF_EXTERNAL_IMAGE_STORAGE_PROVIDER
   value: "gcs"
- name: GF_EXTERNAL_IMAGE_STORAGE_GCS_ENABLE_SIGNED_URLS
   value: "true"
```

**Anything else we need to know?**:

If I understand the code correctly, the url column is currently having a limit of 190 chars, signed url returned from gcs can be 800+ chars: https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/migrations/ualert/tables.go#L391

**Environment**:
- Grafana version: V9.0.6
- Data source type & version: Prometheus and others
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: N/A
- Others: Google Cloud MySQL 5.7

### PR DESCRIPTION
**Pull request by VDVsx**
**What this PR does / why we need it**:

The URL of screenshots uploaded to external image storages can be optionally signed,
resulting in a long string (800+ chars).

Add a migration to support URLs with a max length of 2048 chars in alert_image table.

**Which issue(s) this PR fixes**:

Fixes #53566

**Special notes for your reviewer**:

In theory URL max length should be 2048 chars, this field should not be directly settable by the users so the risk of blowing up in size is minimal, but if there are concerns we can add a length check before saving to DB.

### CODE REVIEW

File: pkg/services/ngalert/store/image_test.go [hunk 1]
```diff
@@ -90,8 +90,11 @@ func TestIntegrationGetImages(t *testing.T) {
 	assert.Len(t, mismatched, 0)
 	assert.Equal(t, []models.Image{image1}, images)
 
-	// create an image with a URL
-	image2 := models.Image{Path: "https://example.com/example.png"}
```
Comment (VDVsx) [inline pkg/services/ngalert/store/image_test.go:94]: This test was not creating an image with a URL as the comment said, so changed it to use an URL and made it a long one.

**Review by JohnnyQQQQ — DISMISSED** [review]
I would discourage the use of any `text` type for MySQL as they are in separated files on disk and can introduce performance bottlenecks.

The common thing to do in MySQL for URLs is to use `VARCHAR(2083)` as this is the common denominator for the maximal URL length in browsers.

But I let @grobinson-grafana do the call here.

**Comment by VDVsx** [comment]
Good point,thanks. Text types are use in several places already for MySQL, but I do agree that there's no need in this case, changed.

File: pkg/services/sqlstore/migrations/ualert/tables.go [hunk 2]
```diff
@@ -396,6 +396,11 @@ func AddAlertImageMigrations(mg *migrator.Migrator) {
 			{Cols: []string{"token"}, Type: migrator.UniqueIndex},
 		},
 	}
+
 	mg.AddMigration("create alert_image table", migrator.NewAddTableMigration(imageTable))
 	mg.AddMigration("add unique index on token to alert_image table", migrator.NewAddIndexMigration(imageTable, imageTable.Indices[0]))
+
+	mg.AddMigration("alter alert_image.url to mediumtext in mysql and text in postgres", migrator.NewRawSQLMigration("").
```
Comment (grobinson-grafana) [inline pkg/services/sqlstore/migrations/ualert/tables.go]:
```suggestion
	mg.AddMigration("support longer URLs in alert_image table", migrator.NewRawSQLMigration("").
		Default("ALTER TABLE alert_image ALTER COLUMN url TYPE VARCHAR(2048);").
		Mysql("ALTER TABLE alert_image MODIFY url VARCHAR(2048) NOT NULL;"))
```

File: pkg/services/ngalert/store/image_test.go [hunk 3]
```diff
@@ -90,8 +90,11 @@ func TestIntegrationGetImages(t *testing.T) {
...
+	// create an image with a long URL (e.g signed URL)
+	image2 := models.Image{URL: "https://example.com/example.png?Signature=3r4r4r34r34r34r34dfeergef3t343t34erg443" +
```
Comment (grobinson-grafana) [inline pkg/services/ngalert/store/image_test.go:94]: Is the signature here just a random string?

Comment (VDVsx) [reply pkg/services/ngalert/store/image_test.go:94]: Yes, c&p 🐱 typing, I can change to something that looks more like a signature if that's preferable for aesthetics

File: pkg/services/sqlstore/migrations/ualert/tables.go (hunk 2 above)
Comment (VDVsx) [reply pkg/services/sqlstore/migrations/ualert/tables.go]: Thanks, good catch the nullable would have been dropped for MySQL :)

Comment (VDVsx) [reply pkg/services/sqlstore/migrations/ualert/tables.go]: I didn't use the `Default(...)` as suggested since SQLite does not support `ALTER COLUMN`, we would need to introduce more migration steps and since the column in SQLite already support long text it seems unnecessary. Let me know what you think.

File: pkg/services/ngalert/store/image_test.go (hunk 3 above)
Comment (VDVsx) [reply pkg/services/ngalert/store/image_test.go]: Ok, made it a little longer, over 1000 chars, this size is already longer than common signed URLs from the 3 major cloud providers.

File: pkg/services/sqlstore/migrations/ualert/tables.go [hunk 4]
```diff
@@ -396,6 +396,11 @@ func AddAlertImageMigrations(mg *migrator.Migrator) {
 			{Cols: []string{"token"}, Type: migrator.UniqueIndex},
 		},
 	}
+
 	mg.AddMigration("create alert_image table", migrator.NewAddTableMigration(imageTable))
 	mg.AddMigration("add unique index on token to alert_image table", migrator.NewAddIndexMigration(imageTable, imageTable.Indices[0]))
+
+	mg.AddMigration("support longer URLs in alert_image table", migrator.NewRawSQLMigration("").
+		Postgres("ALTER TABLE alert_image ALTER COLUMN url TYPE VARCHAR(2048);").
+		Mysql("ALTER TABLE alert_image MODIFY url VARCHAR(2048);"))
```
Comment (grobinson-grafana) [inline pkg/services/sqlstore/migrations/ualert/tables.go:405]:
```suggestion
		Mysql("ALTER TABLE alert_image MODIFY url VARCHAR(2048) NOT NULL;"))
```

**Review by grobinson-grafana — CHANGES_REQUESTED** [review]
This migration needs `NOT NULL` to prevent the column being nullable.

**Review by grobinson-grafana — APPROVED** [review]

**Comment by grobinson-grafana** [comment]
Looks good to me!

```
MariaDB [grafana]> EXPLAIN alert_image;
+------------+---------------+------+-----+---------+----------------+
| Field      | Type          | Null | Key | Default | Extra          |
+------------+---------------+------+-----+---------+----------------+
| id         | bigint(20)    | NO   | PRI | NULL    | auto_increment |
| token      | varchar(190)  | NO   | UNI | NULL    |                |
| path       | varchar(190)  | NO   |     | NULL    |                |
| url        | varchar(2048) | NO   |     | NULL    |                |
| created_at | datetime      | NO   |     | NULL    |                |
| expires_at | datetime      | NO   |     | NULL    |                |
+------------+---------------+------+-----+---------+----------------+
6 rows in set (0.000 sec)
```

```
postgres=# \d alert_image
                                        Table "public.alert_image"
   Column   |            Type             | Collation | Nullable |                 D
efault
------------+-----------------------------+-----------+----------+------------------
-----------------------
 id         | integer                     |           | not null | nextval('alert_im
age_id_seq'::regclass)
 token      | character varying(190)      |           | not null |
 path       | character varying(190)      |           | not null |
 url        | character varying(2048)     |           | not null |
 created_at | timestamp without time zone |           | not null |
 expires_at | timestamp without time zone |           | not null |
Indexes:
    "alert_image_pkey" PRIMARY KEY, btree (id)
    "UQE_alert_image_token" UNIQUE, btree (token)
```

```
sqlite> .schema alert_image
CREATE TABLE `alert_image` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
, `token` TEXT NOT NULL
, `path` TEXT NOT NULL
, `url` TEXT NOT NULL
, `created_at` DATETIME NOT NULL
, `expires_at` DATETIME NOT NULL
);
CREATE UNIQUE INDEX `UQE_alert_image_token` ON `alert_image` (`token`);
```
