### PR TITLE
DataLinks: Fix double dollar-sign bug in data-links editor

### LINKED ISSUE #47184: Graph panel: Data Link editor automcomplete gives double $
**What happened**:
When I press `$` I get a pop-up, but after I select an item I have two `$$`, which causes an error when the link is used.

https://user-images.githubusercontent.com/8125524/161244703-54e82042-928d-4116-961a-6cc6d7c41b3f.mp4

**What you expected to happen**:

Just one `$`

**How to reproduce it (as minimally and precisely as possible)**:
In Graph panel, click on Data Link, edit, position cursor in the middle of existing text.

**Environment**:
- Grafana version: 8.5.0-a2463818pre
- User OS & Browser: MacOS 11.6.1; Chrome Version 99.0.4844.74 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by zuchka**
**Which issue(s) does this PR fix?**:

Fixes #47184 and another related bug

**Special notes for your reviewer**:

the pr addresses ~~two similar bugs with~~ duplicate `$` characters. ~~each is described below. Not sure how to resolve the second scenario (which is described in #47184) while preserving the `includeDollarSign` logic.~~ 
- ~~**But I'm curious**: is that logic still needed here?~~ 
- ~~Looks like that line hasn't changed since v7. And now, if you have to type a `$` character to make the variable suggestions appear, then won't a `$` always be present?~~ 
- ~~Is there a scenario where you can trigger the variables suggestions inside the data-link editor without adding the `$` character?~~ 

~~simplifying the function resolves the two bugs mentioned above. But I can't see what it would break...is there some gotcha I can't see? any help?~~

scenario 1: if you add a template variable using the data-link editor, it produces a double `$$`

CleanShot 2022-11-02 at 11 16 28

~~scenario 2: this is the bug described by OP in #47184. to reproduce: Try to insert a new data-link var **into the middle of a URL**. This also produces a double `$$`~~

CleanShot 2022-11-02 at 11 17 58

### CODE REVIEW

**Comment by zuchka** [comment]
ugh I just realized this doesn't really fix #47184 . Not sure how to make that work while preserving the `includeDollarSign` logic. I'm curious: why is that logic needed here? If you have to type a `$` character to make the variable suggestions appear, then won't a `$` always be present? Is there a scenario where you can trigger variables suggestions without adding the `$` character?

File: packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx [hunk 1]
```diff
@@ -137,11 +137,10 @@ export const DataLinkInput: React.FC<DataLinkInputProps> = memo(
     }, []);
 
     const onVariableSelect = (item: VariableSuggestion, editor = editorRef.current!) => {
-      const includeDollarSign = Plain.serialize(editor.value).slice(-1) !== '$';
       if (item.origin !== VariableOrigin.Template || item.value === DataLinkBuiltInVars.includeVars) {
-        editor.insertText(`${includeDollarSign ? '$' : ''}\{${item.value}}`);
```
Comment (polibb) [inline packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx:142]: This does seem alright to me as well, I cannot seem to find an answer to your question "Is there a scenario where you can trigger the variables suggestions inside the data-link editor without adding the $ character?"

The only thing related is [this in the docs](https://grafana.com/docs/grafana/latest/panels-visualizations/configure-data-links/#add-a-data-link) which says we can use Cmd+Space or Ctrl+Space to trigger the list of suggestions, but it doesn't work like that for me. I cannot find where this combination of keys is programatically caught and overwritten, if anywhere.

If the only way to open suggestions is through typing `$`, then this PR fixes the bugs 🙏😊.

Comment (zuchka) [reply packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx:142]: @polibb thanks so much for this review! so, weirdly, `ctrl` + `space` is triggering the suggestions menu on my mac + chrome (106.0.5249.119 (Official Build) (arm64))

also, as written this PR would totally mess up that functionality. I am thinking it might be better for me if I narrow the scope of this PR to just the template variable + double-dollarsign issue. I can re-use the `includeDollarSign` logic for the else statement that handles the template variables, then it will behave the same way as everything else without breaking anything existing.

would love to keep digging into this other, larger issue as well!

Comment (polibb) [reply packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx:142]: It's curious this shortcut does nothing for me. Anyway, I'm glad it works for you.

Indeed, this is a good trade-off for now 😊. Thank you for tackling it! And for changing the description of the PR for easy view of what's happening.
> would love to keep digging into this other issue as well!

me too - we should probably be able to catch the last character behind the current cursor (?).

**Review by polibb — APPROVED** [review]
Thank you for this, @zuchka!
I just wanted to understand the change before approving, I'm sorry if it took too long.
