### PR TITLE
Cloudwatch: Add expression field to interpolate variables in Metrics Code Builder

### LINKED ISSUE #64176: Cloudwatch: Variables not being interpolated in expression when Expression query is active
**What happened**:
The variables in code editor  are not being interpolated when expression query is added.  It works when using the builder mode of the query editor - the issue is only with the editor in code mode.
The reason for this is [a recent change in code](https://github.com/grafana/grafana/pull/57921/) whereby the expression field is no longer replaced from the ExpressionDatasource.
We need to add the "expression" field [here](https://github.com/grafana/grafana/blob/254577ba568d8010dcc96446e788866d618c96c8/public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts#L99) in order to get it working again. 
Also, `sqlExpression` should probably not be checked for multi, and this function should look more like [this one](https://github.com/grafana/grafana/blob/254577ba568d8010dcc96446e788866d618c96c8/public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts#L178)

**What you expected to happen**:

Variables in the query should be replaced with values. 

**How to reproduce it (as minimally and precisely as possible)**:

1. create a Cloudwatch query using a template variable with the query editor in code mode
2. add an expression and run the query
3. observe that the variable is not being replaced in the request anymore

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.1
- Data source type & version: 9.4.1
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by idastambuk**
**What is this feature?**

Adds the expression field in the interpolateVariable that is being called from [ExpressionDatasource.ts](https://github.com/grafana/grafana/blob/91221bc4362e50b9cca6dbff3a8342b2991900d2/public/app/features/expressions/ExpressionDatasource.ts#L46) and makes the function more similar to [replaceMetricQueryVars](https://github.com/grafana/grafana/blob/da4c12b0d6021f3669dd482f9be0ef0584241918/public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts#L181)

These two should probably be combined in a [refactor](https://github.com/grafana/oss-plugin-partnerships/issues/149), but there are mismatching fields and it would require some testing to figure out the source of truth. 

**Why do we need this feature?**
[Original issue](https://github.com/grafana/grafana/issues/64176) reported in support escalations

**Which issue(s) does this PR fix?**:

Fixes #64176

### CODE REVIEW

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts [hunk 1]
```diff
@@ -99,13 +99,17 @@ export class CloudWatchMetricsQueryRunner extends CloudWatchRequest {
...
+    'alias' | 'metricName' | 'namespace' | 'period' | 'dimensions' | 'sqlExpression' | 'expression'
+  > {
     return {
       alias: this.replaceVariableAndDisplayWarningIfMulti(query.alias, scopedVars),
       metricName: this.replaceVariableAndDisplayWarningIfMulti(query.metricName, scopedVars),
       namespace: this.replaceVariableAndDisplayWarningIfMulti(query.namespace, scopedVars),
       period: this.replaceVariableAndDisplayWarningIfMulti(query.period, scopedVars),
-      sqlExpression: this.replaceVariableAndDisplayWarningIfMulti(query.sqlExpression, scopedVars),
+      expression: this.templateSrv.replace(query.expression, scopedVars),
+      sqlExpression: this.templateSrv.replace(query.sqlExpression, scopedVars, 'raw'),
```
Comment (idastambuk) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts:112]: Not sure about removing multi warning for sql?

Comment (iwysiu) [reply public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts:112]: It should be fine? It's a query string field if I'm not wrong, so I think there are legitimate reasons to use a multi variable

**Review by iwysiu — APPROVED** [review]

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.test.ts [hunk 2]
```diff
@@ -715,6 +716,32 @@ describe('CloudWatchMetricsQueryRunner', () => {
         period: '',
         sqlExpression: '',
         dimensions: { InstanceId: ['foo'] },
+        expression: '',
+      });
+    });
+    it('interpolates values correctly', () => {
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.test.ts:722]: so we have 2 tests for "interpolateMetricsQueryVariables":
- it interpolates dimensions correctly
- and it interpolates values correctly (which also seems to be testing dimensions interpolations)

I might recommend either combining these into one or creating a test for each value field you hope to be able to interpolate you know?

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts (hunk 1 above)
Comment (sarahzinger) [reply public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts:112]: Is that necessary for the bug fix, I thought we only needed to add expression? Also what does adding "raw" as a third argument do?

Comment (idastambuk) [reply public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts:112]: It's not necessary, I wanted to make it more similar to [this one](https://github.com/grafana/grafana/blob/da4c12b0d6021f3669dd482f9be0ef0584241918/public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts#L181), but I guess it can be done as part of [this](https://github.com/grafana/oss-plugin-partnerships/issues/149)
