### PR TITLE
CloudWatch: Make deeplinks work for us-gov and china regions

### LINKED ISSUE #57473: Cloudwatch plugin does not support linking to AWS Gov Cloud partition.
**What happened**:
When adding links via the CloudWatch plugin, the partition of the AWS account is not considered.
When the region is govcloud the partition needs to be updated from aws.amazon.com to amazonaws-us-gov.com.
Currently it gives a dead URL if you are in a gov-cloud region.

**What you expected to happen**:
Code would change the partition within the URL to match gov cloud when a gov cloud region is provided.
**How to reproduce it (as minimally and precisely as possible)**:
Set region to gov cloud on datasource. Create CW panel, add link. Receive incorrect URL.
**Anything else we need to know?**:
https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloudwatch/aws_url.ts#L15
Here is the line of code that needs to be updated.

**Environment**:
- Grafana version: [v9.2.1](https://github.com/grafana/grafana/releases/tag/v9.2.1)
- Data source type & version: CloudWatch latest
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Mac/Firefox
- Grafana plugins: Cloudwatch
- Others:

### PR DESCRIPTION
**Pull request by iwysiu**
**What is this feature?**

Adds checks for the us-gov and china regions and uses the correct urls in the links for them.
us-gov link found at: https://docs.aws.amazon.com/general/latest/gr/mgmt-console.html
china link found at: https://docs.amazonaws.cn/en_us/aws/latest/userguide/endpoints-Ningxia.html (search for Management Console)

**Which issue(s) does this PR fix?**:

Fixes #57473

**Special notes for your reviewer**:
While AWS has an [endpoints api](https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints), from what I can tell, it doesn't support the management console endpoints, so I handled them myself.

Also, while I confirmed that the aws partition links still work, I don't have the access to test the us-gov and china links.

### CODE REVIEW

File: pkg/tsdb/cloudwatch/models/cloudwatch_query.go [hunk 1]
```diff
@@ -485,3 +490,14 @@ func sortDimensions(dimensions map[string][]string) map[string][]string {
 	}
 	return sortedDimensions
 }
+
+func getEndpoint(region string) string {
+	url := defaultConsoleURL
+	if strings.HasPrefix(region, "us-gov-") {
```
Comment (sarahzinger) [inline pkg/tsdb/cloudwatch/models/cloudwatch_query.go:496]: rather than pass this a region as an argument, is it possible to pass a partition and to use the aws constants that are exported by the endpoints package? https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/#pkg-constants

Comment (iwysiu) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go]: done

File: public/app/plugins/datasource/cloudwatch/aws_url.ts [hunk 2]
```diff
@@ -11,8 +11,23 @@ export interface AwsUrl {
   source: string[];
 }
 
+const defaultURL = 'console.aws.amazon.com';
+const usGovURL = 'console.amazonaws-us-gov.com';
+const chinaURL = 'console.amazonaws.cn';
+
+export function getLogsEndpoint(region: string): string {
+  let url = defaultURL;
+  if (region.startsWith('us-gov-')) {
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/aws_url.ts:20]: it feels like a similar thing should exist in https://github.com/aws/aws-sdk-js so we wouldn't have to have hard coded strings here but Idk I did a quick look and didn't see it so idk maybe it doesn't! The closest I found was [this](https://github.com/aws/aws-sdk-js/blob/94e4ab32e4d1faac725968bbeff9329f68a9bc20/lib/region_config_data.json) but I'm not sure how that would be used. 

Anyway probably not worth it!

**Review by sarahzinger — APPROVED** [review]
thanks for looking at this!
