### PR TITLE
Variables: Prevent adhoc filters from crashing when they are not loaded properly

### LINKED ISSUE #28120: TypeError: e is undefined
**What happened**:
`TypeError` errors pop up in console, sometimes making a Dashboard crash.

No error spawned by the server run with a `debug` log level: definitely seems like a frontend error bug.

<details>
  <summary>Error displayed when a Dashboard crashes</summary>

```
An unexpected error happened
TypeError: e is undefined

    in t
    in P
    in div
    in t
    in t
    in t
    in t
    in t
    in f
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in x
    in div
    in o
    in DraggableCore
    in t
    in div
    in ReactGridLayout
    in Unknown
    in SizeMeReferenceWrapper
    in SizeMeRenderer(Component)
    in SizeMe(Component)
    in t
    in div
    in div
    in div
    in t
    in t
    in div
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l
```
</details>

<details>
  <summary>Examples of console error on Dashboard crash</summary>

<details>
  <summary>Crash 1</summary>

```
TypeError: e is undefined
    $r urlParser.ts:24
    getValueForUrl urlParser.ts:8
    getValueForUrl urlParser.ts:6
    getValueForUrl adapter.ts:35
    fillVariableValuesForUrl template_srv.ts:314
    Lodash 2
        ut
        ua
    fillVariableValuesForUrl template_srv.ts:304
    getDataLinkUIModel link_srv.ts:324
    getLinks linkSuppliers.ts:144
    getLinks linkSuppliers.ts:143
    getInfoContent PanelHeaderCorner.tsx:50
    value Popover.tsx:82
    render Popper.js:159
    React 17
        Xa
        Ya
        Su
        yc
        hc
        ic
        Xo
        unstable_runWithPriority
        Wo
        Xo
        Yo
        se
        Ar
        Tr
        kr
        unstable_runWithPriority
        _r
react-dom.production.min.js:196:194
```
</details>
<details>
  <summary>Crash 2</summary>

```
TypeError: e is undefined
    $r urlParser.ts:24
    getValueForUrl urlParser.ts:8
    getValueForUrl urlParser.ts:6
    getValueForUrl adapter.ts:35
    fillVariableValuesForUrl template_srv.ts:314
    Lodash 2
        ut
        ua
    fillVariableValuesForUrl template_srv.ts:304
    getDataLinkUIModel link_srv.ts:324
    getLinks linkSuppliers.ts:144
    getLinks linkSuppliers.ts:143
    getInfoContent PanelHeaderCorner.tsx:50
    value Popover.tsx:82
    render Popper.js:159
    React 17
        Xa
        Ya
        Su
        yc
        hc
        ic
        Xo
        unstable_runWithPriority
        Wo
        Xo
        Yo
        se
        Ar
        Tr
        kr
        unstable_runWithPriority
        _r
react-dom.production.min.js:196:194
    React 20
        fu
        callback
        Oi
        mi
        mc
        unstable_runWithPriority
        Wo
        gc
        ic
        Xo
        unstable_runWithPriority
        Wo
        Xo
        Yo
        se
        Ar
        Tr
        kr
        unstable_runWithPriority
        _r
```
</details>
</details>

<details>
  <summary>Example of console error while Dashboard did _not_ crash</summary>

```
Uncaught (in promise) TypeError: e is undefined
    $r urlParser.ts:24
    getValueForUrl urlParser.ts:8
    getValueForUrl urlParser.ts:6
    getValueForUrl adapter.ts:35
    Y actions.ts:540
    X actions.ts:453
urlParser.ts:24:2
    ne http://127.0.0.1:3000/public/build/app.9f3acd666ba6dad3e060.js:2
    c http://127.0.0.1:3000/public/build/app.9f3acd666ba6dad3e060.js:2
```
</details>

**What you expected to happen**:
No error, no crash

**How to reproduce it (as minimally and precisely as possible)**:
Fiddling with template variables in order to make a Dashboard refresh, sometimes not doing anything other than hovering over Panels.

**Anything else we need to know?**:
***Other potentially related issues***
- #22199 Error looks very much alike
- #24125 Video shows an error happening in a suspiciously similar way

***v6.6.1***
Error already encountered with v6.6.1
<details>
  <summary>Console error v6.6.1</summary>

```
TypeError: e is undefined
    escapeDelimiter plugin_page_ctrl.ts:23
    getValueForUrl plugin_page_ctrl.ts:18
    getValueForUrl plugin_page_ctrl.ts:18
    getValueForUrl plugin_page_ctrl.ts:17
    fillVariableValuesForUrl template_srv.ts:364
    Lodash 2
        Ye
        qa
    fillVariableValuesForUrl template_srv.ts:354
    getDataLinkUIModel link_srv.ts:278
    getLinks linkSuppliers.ts:149
    getLinks linkSuppliers.ts:149
    getInfoContent PanelHeaderCorner.tsx:52
    render useLokiLabels.ts:31
    render Popper.js:159
    React 7
        Za
        $a
        Tu
        Ts
        Os
        ms
        i
    unstable_runWithPriority scheduler.production.min.js:18
    React 7
        Gi
        $i
        Ki
        st
        Cn
        An
        Tn
    unstable_runWithPriority scheduler.production.min.js:18
    r React
react-dom.production.min.js:196:186
    React 5
        pu
        callback
        _o
        wo
        Ps
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        Gi
        Ps
        ms
        i
    unstable_runWithPriority scheduler.production.min.js:18
    React 7
        Gi
        $i
        Ki
        st
        Cn
        An
        Tn
    unstable_runWithPriority scheduler.production.min.js:18
    r React
```
</details>

**Environment**:
- Grafana version: v7.2.0 (error already encountered with v6.6.1)
- Data source type & version: Prometheus
- OS Grafana is installed on: Debian Buster equivalent
- User OS & Browser: Debian Buster equivalent & Mozilla Firefox 78.3.0esr

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
When having AdHoc filter variabels that isn't loaded properly or are empty the UI will crash. This PR resolves that issue by making sure we can handle empty values but also so we will display a better message to the end user when we fail to load the variable list.

**Which issue(s) this PR fixes**:
Fixes #28120

### CODE REVIEW

File: public/app/features/variables/adhoc/urlParser.ts [hunk 1]
```diff
@@ -20,12 +20,12 @@ export const toFilters = (value: UrlQueryValue): AdHocVariableFilter[] => {
...
-function escapeDelimiter(value: string) {
-  return value.replace(/\|/g, '__gfp__');
+function escapeDelimiter(value: string | undefined): string {
+  return value?.replace(/\|/g, '__gfp__') ?? '';
 }
 
-function unescapeDelimiter(value: string) {
-  return value.replace(/__gfp__/g, '|');
+function unescapeDelimiter(value: string | undefined): string {
+  return value?.replace(/__gfp__/g, '|') ?? '';
```
Comment (hugohaggmark) [inline public/app/features/variables/adhoc/urlParser.ts:28]: nit: maybe we should add some test cases for this?

**Review by hugohaggmark — APPROVED** [review]
Outstanding work and works as expected 🌟

File: public/app/features/variables/adhoc/urlParser.ts (hunk 1 above)
Comment (mckn) [reply public/app/features/variables/adhoc/urlParser.ts:28]: Yes, agree! Will add it.
