### PR TITLE
Dashboard: Fixes random scrolling on time range change

### LINKED ISSUE #49037: Screen jumps to last edited panel on zoom
**What happened**:
If you have entered the edit mode of a panel, then the dashboard will jump back to that panel on zoom (or variable value change). In the attached gif, it shows the expected behaviour at first, followed by the unexpected behaviour after editing a panel. The very last zoom shows the dashboard jumping down to the last edited by itself (NOT the user scrolling).
Kapture 2022-05-16 at 16 10 47

**What you expected to happen**:
The dashboard should not jump around. It makes data exploration difficult on dashboards with lots of panels when it jumps around every time you change the zoom level.

**How to reproduce it (as minimally and precisely as possible)**:

1. load a dashboard with enough panels that you need to scroll off the screen to see some. Do not open any panels in edit mode.
2. test zooming in and out. On time changes, the screen will no jump around (expected)
3. go in to edit a panel (i.e. the very bottom one on the page) and return back to the dashboard. 
4. Scroll back up to the top of the page
5. zoom in or out. The dashboard will jump back down to the panel you were previously editing. 

**Anything else we need to know?**:
Reproduced on [play.grafana.org ](https://play.grafana.org/d/000000012) v8.5.2
Also reproduces when a variable value is changed. 

**Environment**:
- Grafana version: v8.5.2
- Data source type & version: 
- OS Grafana is installed on: play.grafana.org
- User OS & Browser: tested on Chrome, Firefox, Edge
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #49037

After editing a panel any subsequent time range change would cause the scrollbar
to jump the last edited panel.

### CODE REVIEW

File: packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx [hunk 1]
```diff
@@ -46,28 +46,28 @@ export const CustomScrollbar: FC<Props> = ({
...
   }, [ref, scrollRefCallback]);
-  const styles = useStyles2(getStyles);
 
-  const updateScroll = () => {
-    if (ref.current && !isNil(scrollTop)) {
+  useEffect(() => {
+    if (ref.current && scrollTop != null) {
+      if (ref.current.view.scrollTop === scrollTop) {
+        console.log('CustomScrollbar: update but  the same');
+      }
```
Comment (dprokop) [inline packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx:60]:
```suggestion
```

File: packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx [hunk 2]
```diff
@@ -46,28 +46,28 @@ export const CustomScrollbar: FC<Props> = ({
...
+
       ref.current.scrollTop(scrollTop);
     }
-  };
-
-  useEffect(() => {
-    updateScroll();
-  });
+  }, [scrollTop]);
```
Comment (torkelo) [inline packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx:65]: The change makes sure we only update scroll position when scrollTop changes (from outside), before the PR there was not real check that that scrollTop has actually changed (since it was not in the useEffect dependency list)

**Review by dprokop — APPROVED** [review]
Works as expected 👍

File: packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx (hunk 1 above)
Comment (torkelo) [reply packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx:60]: ah, forgot to remove that
