### PR TITLE
pkg/api/pluginproxy: Access token provider should handle access tokens without ExpiresOn field

### LINKED ISSUE #19730: DataProxy: Support access tokens without expire_on field
**What happened**:
I'm trying to implement a datasource plugin for Grafana, the api used requires oauth2 client credentials authentication, which is implement as written in the [oauth-guide](https://grafana.com/docs/plugins/developing/auth-for-datasources/#how-token-authentication-works).  Grafana does not reuse the token, and will request a new token for each request. 

The Access Token Response from auth0 is as follows:
```json
{
  "access_token":"eyJz93a...k4laUWw",
  "refresh_token":"GEbRxBN...edjnXbL",
  "id_token":"eyJ0XAi...4faeEoQ",
  "token_type":"Bearer",
  "expires_in":86400
}
```

Which causes issues with the current implementation of Grafana. 

**What you expected to happen**:
Grafana will reuse the token already fetched by the proxy-provider, and not fetch the already cached token. 

**How to reproduce it (as minimally and precisely as possible)**:
Configure a datasource as written in the guide, with auth0 as oauth2-provider. It should not reuse the token. 

**Anything else we need to know?**:
[rfc6749](https://tools.ietf.org/html/rfc6749#section-4.2.2) defines the fields in the Access Token Response, where _expire_on_ is not defined, which is used by Grafana to set the expire time of the token. 

A more universal implementation would use the expire_in field instead or as a fallback.. A note on this is that authentication providers have different types for the _expire_in_ field, for example  [Microsoft](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code) uses a string, and the RFC defines it as a number [RFC6749](https://tools.ietf.org/html/rfc6749#section-4.3.3) [oauth.com](https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/). So the implemenation needs to handle both strings and number in the _expire_in_ field of the Access Token Response.

**Environment**:
- Grafana version:  v6.5.0-pre (commit: d6eb4e8459) and  Grafana v6.4.2 (commit: 443a0ba)
- Data source type & version: custom with oauth2 authentication 
- OS Grafana is installed on: Official Docker image and Debian 
- User OS & Browser: na
- Grafana plugins: na
- Others: na

### PR DESCRIPTION
**Pull request by mmikalsen**
**What this PR does / why we need it**:
While making a datasource provider which requires Auth0 authentication we discovered a large amount of request for tokens. After going through the source-code we discovered that Grafana only handles Accesstoken with a expires-on field. This is something that Auth0 does not provide, instead they provide expire-in field. see issue #19730. Since both expire-on and expire-in fields can be in string or int format this also needs to be considered. 

**Which issue(s) this PR fixes**:
#19730

Fixes #19730

### CODE REVIEW

File: pkg/api/pluginproxy/access_token_provider.go [hunk 1]
```diff
@@ -44,9 +45,10 @@ type accessTokenProvider struct {
 }
 
 type jwtToken struct {
-	ExpiresOn       time.Time `json:"-"`
-	ExpiresOnString string    `json:"expires_on"`
-	AccessToken     string    `json:"access_token"`
+	ExpiresOn      time.Time   `json:"-"`
+	ExpiresOnValue interface{} `json:"expires_on"`
+	ExpiresIn      interface{} `json:"expires_in"`
+	AccessToken    string      `json:"access_token"`
```
Comment (torkelo) [inline pkg/api/pluginproxy/access_token_provider.go]: this looks like a messy way to handle an optional field.   Maybe add a function on the struct instead for getExpiresOnOrIn() or something?

File: pkg/api/pluginproxy/access_token_provider.go [hunk 2]
```diff
@@ -97,7 +99,34 @@ func (provider *accessTokenProvider) getAccessToken(data templateData) (string,
...
+		case string:
+			expiresIn, err = strconv.ParseInt(token.ExpiresIn.(string), 10, 64)
+			if err != nil {
+				return "", err
+			}
+		default:
+			logger.Warn("expires_in with type: %v not supported", reflect.TypeOf(t))
+		}
+		expiresOnEpoch = time.Now().Unix() + (expiresIn)
+	}
```
Comment (torkelo) [inline pkg/api/pluginproxy/access_token_provider.go]: Would like to try to simplify this code, not sure how adding suport for another field added 28 lines of new code.  

Maybe try to break it out into a separate function, and explore ways to simplify the logic

**Review by torkelo — DISMISSED** [review]

File: pkg/api/pluginproxy/access_token_provider.go [hunk 3]
```diff
@@ -57,7 +89,7 @@ func newAccessTokenProvider(ds *models.DataSource, pluginRoute *plugins.AppPlugi
 	}
 }
 
-func (provider *accessTokenProvider) getAccessToken(data templateData) (string, error) {
```
Comment (papagian) [inline pkg/api/pluginproxy/access_token_provider.go]: I think that `ctx` parameter is redundant; it's not used inside the function.

File: pkg/api/pluginproxy/ds_auth_provider.go [hunk 4]
```diff
@@ -46,7 +46,7 @@ func ApplyRoute(ctx context.Context, req *http.Request, proxyPath string, route
 	tokenProvider := newAccessTokenProvider(ds, route)
 
 	if route.TokenAuth != nil {
-		if token, err := tokenProvider.getAccessToken(data); err != nil {
```
Comment (papagian) [inline pkg/api/pluginproxy/ds_auth_provider.go]: Following my previous comment, `ctx` does not serve anything so it should be removed.

**Review by papagian — CHANGES_REQUESTED** [review]
Thank you for the changes you have made and sorry for taking so long to come back.
I have some additional changes to suggest, please check my comments.

File: pkg/api/pluginproxy/access_token_provider.go [hunk 5]
```diff
@@ -57,7 +89,7 @@ func newAccessTokenProvider(ds *models.DataSource, pluginRoute *plugins.AppPlugi
...
+func (provider *accessTokenProvider) getAccessToken(ctx context.Context, data templateData) (string, error) {
```
Comment (papagian) [inline pkg/api/pluginproxy/access_token_provider.go]: I think that `ctx` parameter is redundant; it's not used inside the function.

File: pkg/api/pluginproxy/ds_auth_provider.go [hunk 6]
```diff
@@ -46,7 +46,7 @@ func ApplyRoute(ctx context.Context, req *http.Request, proxyPath string, route
...
+		if token, err := tokenProvider.getAccessToken(ctx, data); err != nil {
```
Comment (papagian) [inline pkg/api/pluginproxy/ds_auth_provider.go]: Following my previous comment, `ctx` does not serve anything so it should be removed.

File: pkg/api/pluginproxy/access_token_provider_test.go [hunk 7]
```diff
@@ -91,4 +95,192 @@ func TestAccessToken(t *testing.T) {
...
+				So(err, ShouldBeNil)
+				So(accessToken, ShouldEqual, token["access_token"])
+
+				accessToken, err = provider.getAccessToken(context.Background(), templateData)
+				So(err, ShouldBeNil)
+				So(accessToken, ShouldEqual, token["access_token"])
+
+				for _, v := range tokenCache.cache {
+					So(v.ExpiresOn.Unix(), ShouldAlmostEqual, t.Unix()+3600)
+				}
```
Comment (papagian) [inline pkg/api/pluginproxy/access_token_provider_test.go]: Instead of looping over all cached tokens, you would better look for the specific token using the provided key.

File: pkg/api/pluginproxy/access_token_provider_test.go [hunk 8]
```diff
@@ -91,4 +95,192 @@ func TestAccessToken(t *testing.T) {
...
+				for _, v := range tokenCache.cache {
+					So(v.ExpiresOn.Unix(), ShouldNotAlmostEqual, t.Unix()+int64(expiresIn))
+					So(v.ExpiresOn.Unix(), ShouldEqual, expiresOn)
+				}
+			})
+
+			Reset(func() {
+				tokenCache.cache = map[string]*jwtToken{}
+				token = map[string]interface{}{}
+			})
```
Comment (papagian) [inline pkg/api/pluginproxy/access_token_provider_test.go]: Access to `tokenCache` should be mutually excluded therefore it should be surrounded by a call to `Lock` and `Unlock` similarly to [this](https://github.com/grafana/grafana/blob/f781cb58594ef989569c2726fb997fd1087b8e9c/pkg/models/datasource_cache_test.go#L235) example code.

In addition to this, in the future we want to [migrate away](https://github.com/grafana/grafana/tree/master/pkg#reduce-the-use-of-goconvey) from Convey therefore instead of using the Convey specific method `Reset`, I would suggest to declare a `clearTokenCache` function and call this at the beginning of it's test.

File: pkg/api/pluginproxy/access_token_provider_test.go [hunk 9]
```diff
@@ -91,4 +99,217 @@ func TestAccessToken(t *testing.T) {
...
+				"audience":  "www.example.com",
+			},
+			SecureJsonData: map[string]string{
+				"client_secret": "my_secret",
+			},
+		}
+
+		ds := &models.DataSource{Id: 1, Version: 2}
+
+		var i int
```
Comment (aknuds1) [inline pkg/api/pluginproxy/access_token_provider_test.go]: Can we delete this one?

File: pkg/api/pluginproxy/access_token_provider.go [hunk 10]
```diff
@@ -44,9 +44,41 @@ type accessTokenProvider struct {
...
+		if err != nil {
+			return err
+		}
+		token.ExpiresOn = time.Unix(expiresOn, 0)
+	case len(t.ExpiresIn) != 0:
+		expiresIn, err := t.ExpiresIn.Int64()
+		if err != nil {
+			return err
+		}
+		token.ExpiresOn = time.Unix(time.Now().Unix()+(expiresIn), 0)
```
Comment (papagian) [inline pkg/api/pluginproxy/access_token_provider.go]: You could rewrite this line so as to be more readable like:
`token.ExpiresOn = time.Now().Add(time.Duration(expiresIn) * time.Second)`

File: pkg/api/pluginproxy/access_token_provider_test.go (hunk 9 above)
Comment (mmikalsen) [reply pkg/api/pluginproxy/access_token_provider_test.go]: used for the creation of the AccessTokenProvider, but we could create a empty DataSource instead.

File: pkg/api/pluginproxy/access_token_provider_test.go [hunk 11]
```diff
@@ -91,4 +99,217 @@ func TestAccessToken(t *testing.T) {
...
+		apiHandler.HandleFunc("/oauth/token", func(w http.ResponseWriter, req *http.Request) {
+			json.NewEncoder(w).Encode(token)
+			i++
+		})
+
+		Convey("Should cache token", func() {
+			Convey("Should parse and cache access token with expires_in string field", func() {
```
Comment (papagian) [inline pkg/api/pluginproxy/access_token_provider_test.go]: It's a bit difficult to understand what are the different test cases and there is too much repeated code. I would suggest to define an array of structs which describe each test like:
```
struct {
				desc              string
				expiresIn         interface{}
				expiresOn         interface{}
				expectedExpiresOn int64
}
```
and loop over this.

**Review by papagian — CHANGES_REQUESTED** [review]
Thank you for your modifications! I have requested some additional changes; please check my inline comments and ask me if you have any questions.

File: pkg/api/pluginproxy/access_token_provider.go [hunk 12]
```diff
@@ -44,9 +44,41 @@ type accessTokenProvider struct {
...
+		token.ExpiresOn = time.Unix(expiresOn, 0)
+	case len(t.ExpiresIn) != 0:
+		expiresIn, err := t.ExpiresIn.Int64()
+		if err != nil {
+			return err
+		}
+		token.ExpiresOn = time.Now().Add(time.Duration(expiresIn) * time.Second)
+	default:
+		token.ExpiresOn = time.Now()
+	}
```
[the remark this answers is not in the document]
Comment (mmikalsen) [reply pkg/api/pluginproxy/access_token_provider.go]: Can drop the `switch` and change it for a `if/if else` clause, set the `expiresOn` to timeNow, and change it if the `accesstoken` has one of the fields.

File: pkg/api/pluginproxy/access_token_provider_test.go (hunk 9 above)
Comment (mmikalsen) [reply pkg/api/pluginproxy/access_token_provider_test.go]: `&models.DataSource{}` can be used as a argument for  `newAccessTokenProvider`

File: pkg/api/pluginproxy/access_token_provider.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (papagian) [reply pkg/api/pluginproxy/access_token_provider.go]: That would work too

File: pkg/api/pluginproxy/access_token_provider_test.go (hunk 9 above)
Comment (papagian) [reply pkg/api/pluginproxy/access_token_provider_test.go]: but the variable `i` is not used.

Comment (mmikalsen) [reply pkg/api/pluginproxy/access_token_provider_test.go]: Oh, i thought it was `ds`. Anyways, It will be used in the next push.

File: pkg/api/pluginproxy/access_token_provider_test.go [hunk 13]
```diff
@@ -91,4 +98,172 @@ func TestAccessToken(t *testing.T) {
...
+			testCases := []tokenTestDescription{
+				{
+					desc:              "token with expires_in in string format",
+					expiresIn:         "3600",
+					expiresOn:         nil,
+					expectedExpiresOn: timeNow().Unix() + 3600,
+				},
+				{
+					desc:              "token with expires_in in int format",
+					expiresIn:         5200,
```
Comment (papagian) [inline pkg/api/pluginproxy/access_token_provider_test.go]: I would suggest to use `3600` as a value here so as to be clearer the difference with the above case.

File: pkg/api/pluginproxy/access_token_provider_test.go [hunk 14]
```diff
@@ -91,4 +98,172 @@ func TestAccessToken(t *testing.T) {
...
+					expiresOn:         nil,
+					expectedExpiresOn: timeNow().Unix() + 5200,
+				},
+				{
+					desc:              "token with expires_on in string format",
+					expiresOn:         timeNow().Add(86 * time.Minute).Unix(),
```
Comment (papagian) [inline pkg/api/pluginproxy/access_token_provider_test.go]: `expireOn` is not string as the description suggests

File: pkg/api/pluginproxy/access_token_provider_test.go [hunk 15]
```diff
@@ -91,4 +98,172 @@ func TestAccessToken(t *testing.T) {
...
+					expiresIn:         nil,
+					expectedExpiresOn: timeNow().Add(86 * time.Minute).Unix(),
+				},
+				{
+					desc:              "token with expires_on in int format",
+					expiresOn:         timeNow().Add(156 * time.Minute).Unix(),
```
Comment (papagian) [inline pkg/api/pluginproxy/access_token_provider_test.go]: I would suggest to use `86` as a value here so as to be clearer the difference with the above case.

File: pkg/api/pluginproxy/access_token_provider_test.go [hunk 16]
```diff
@@ -91,4 +98,172 @@ func TestAccessToken(t *testing.T) {
...
+			for _, testCase := range testCases {
+				clearTokenCache()
+				// reset the httphandler counter
+				authCalls = 0
+
+				token = map[string]interface{}{
+					"access_token":  "2YotnFZFEjr1zCsicMWpAA",
+					"token_type":    "example",
+					"expires_in":    testCase.expiresIn,
+					"expires_on":    testCase.expiresOn,
```
Comment (papagian) [inline pkg/api/pluginproxy/access_token_provider_test.go]: I would prefer to include `expires_in` and `expires_on` only if `testCase.expiresIn` and `testCase.expiresOn` are not `nil` in order to demonstrate the case that either of two can be missing.

File: pkg/api/pluginproxy/access_token_provider_test.go [hunk 17]
```diff
@@ -91,4 +98,172 @@ func TestAccessToken(t *testing.T) {
...
+				So(accessToken, ShouldEqual, token["access_token"])
+				So(authCalls, ShouldEqual, 1)
+
+				tokenCache.Lock()
+				v, ok := tokenCache.cache[provider.getAccessTokenCacheKey()]
+				tokenCache.Unlock()
+
+				So(ok, ShouldBeTrue)
+				So(v.ExpiresOn.Unix(), ShouldEqual, testCase.expectedExpiresOn)
+				So(v.AccessToken, ShouldEqual, token["access_token"])
```
Comment (papagian) [inline pkg/api/pluginproxy/access_token_provider_test.go]: I would enclose this in a Convey() block like:

```
Convey(testCase.desc, func() {
}
```

I that way you can keep better track of each test case failures.

File: pkg/api/pluginproxy/access_token_provider_test.go [hunk 18]
```diff
@@ -91,4 +98,172 @@ func TestAccessToken(t *testing.T) {
...
+
+				// linter fix
+				_ = testCase.desc
```
Comment (papagian) [inline pkg/api/pluginproxy/access_token_provider_test.go]: I assume that this was only needed because `testCase.desc` was never used. But I guess that this will be no more an issue after fixing the above.

**Review by papagian — CHANGES_REQUESTED** [review]
Great! Thank you for your changes!
I have requested some additional before merging!

**Comment by mmikalsen** [comment]
Hope everything is ok now

**Comment by papagian** [comment]
@mmikalsen 
I don't see the last modifications I have requested. Did you push the correct branch?

**Comment by mmikalsen** [comment]
Should be there now, thanks for noticing.

**Review by papagian — APPROVED** [review]
LGTM, thank you for contributing and sorry for taking me so long to reply!

@sunker would you like to have a final look before merging!

**Review by sunker — CHANGES_REQUESTED** [review]
The code looks good to me. 

I tested this with Stackdriver and auth seems to work fine. However I'm seeing some other issue related to the spinner in the panel. Don't think it has to do with your changes @mmikalsen. Can you please merge/rebase latest master to you branch so that I can test again? 
Don't think it's related to you changes @mmikalsen, but I'm getting some ui

**Comment by mmikalsen** [comment]
@sunker rebased on master.

**Review by sunker — APPROVED** [review]
LGTM!

**Review by aknuds1 — APPROVED** [review]
LGTM!

**Comment by aknuds1** [comment]
Thanks a lot for contributing to Grafana, great work!
