### PR TITLE
Flux: Ensure connections to InfluxDB are closed

### LINKED ISSUE #26731: Flux: Connections to the InfluxDB Flux datasource are never closed
**What happened**:

When using the InfluxDB datasource with Flux, anytime I refresh dashboard  page with uses this datasource, or move between dashboards, a handful of new TCP connections are opened between Grafana and InfluxDB, the stay in ESTABLISHED state and never close unless either InfluxDB or Grafana are restarted.  Over time this can lead to an exhaustion of file handles.

**What you expected to happen**:

I would expect either for connections to be reused, or for them to be closed after use.

**How to reproduce it (as minimally and precisely as possible)**:

1) Create a datasource which connects to InfluxDB using Flux.
2) Create a dashboard which queries the datasource.
3) Monitor the number of connections on the InfluxDB server

    netstat -atn | grep ":8086"
    netstat -atn | grep ":8086" | wc -l

4) Refresh the dashboard page, or navigate between 2 dashboards.  The number of ESTABLISHED TCP connections will constantly increase and never decrease

**Anything else we need to know?**:

I compared the code for InfluxQL compared to the Flux and I can see that with InfluxQL the connection is always closed, but there is no Close() method called in the Flux code (except in the test).

Under - /grafana/pkg/tsdb/influxdb
[root@apps3 influxdb]# grep -Rn "Close()" *
flux/executor_test.go:47:	defer server.Close()
influxdb.go:86:	defer resp.Body.Close()

I am not a Go programmer, or familiar with this codebase, but if I add the following to the Query function, it seems to resolve the issue.

defer runner.client.Close()

Happy to submit the pull request if this seems sensible.

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: InfluxDB (build in)
- OS Grafana is installed on: CentOS 7.8
- User OS & Browser: MacOS 10.15
- Grafana plugins: Just the built in plugins
- Others:

### PR DESCRIPTION
**Pull request by paul-sneddon**
What this PR does / why we need it:
Ensures TCP connections created between the Grafana Flux datasource and InFluxDB are closed after they have been used.

Which issue(s) this PR fixes:
Fixes grafana#26731

Special notes for your reviewer:

### CODE REVIEW

File: pkg/tsdb/influxdb/flux/flux.go [hunk 1]
```diff
@@ -41,6 +41,7 @@ func Query(ctx context.Context, dsInfo *models.DataSource, tsdbQuery *tsdb.TsdbQ
 
 		tRes.Results[query.RefId] = backendDataResponseToTSDBResponse(&res, query.RefId)
 	}
+	defer runner.client.Close()
```
Comment (aknuds1) [inline pkg/tsdb/influxdb/flux/flux.go:44]: Please move this to line 32.

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Looks mostly good to me, a minor adjustment is needed though.

**Review by aknuds1 — APPROVED** [review]
Thanks, nice catch!

**Comment by aknuds1** [comment]
Thank you for contributing to Grafana!
