### PR TITLE
Fix renaming columns when displayName or displayNameFromDS are present

### LINKED ISSUE #67731: Datagrid: rename doesn't work for fields with config.displayname
### 
# What went wrong?

**What happened**:

  - https://user-images.githubusercontent.com/13729989/235917424-7735a725-cac0-4073-a725-e8c5894f1b30.mov
  

**What did you expect to happen**:

  - The rename to work on all fields

### 
# How do we reproduce it?

Use the dashboard below.
Rename one of the columns.

### 
# What Grafana version are you using?

Grafana v10.1.0-pre (c0ec1060919)

### 
### Is the bug inside a Dashboard Panel?

| Key | Value |
|--|--|
| Panel | datagrid @ 10.0.0-pre |
| Grafana | 10.1.0-pre (c0ec1060919) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "selectedSeries": 0
      },
      "pluginVersion": "10.0.0-pre",
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "typeVersion": [
                    0,
                    0
                  ],
                  "custom": {
                    "hit": false,
                    "range": "",
                    "spreadsheetId": "1399MxrYphRgkJCd_Qh9KfljIBjjjBFodhRz0gHc2MCw",
                    "warnings": []
                  }
                },
                "name": "A",
                "fields": [
                  {
                    "name": "Time",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64",
                      "nullable": true
                    },
                    "config": {
                      "displayName": "Time"
                    }
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64",
                      "nullable": true
                    },
                    "config": {
                      "displayName": "Value"
                    }
                  },
                  {
                    "name": "Percentages",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64",
                      "nullable": true
                    },
                    "config": {
                      "displayName": "Percentages",
                      "unit": "percent"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1679069340000,
                    1679079340000,
                    1679089340000,
                    1679099340000,
                    1679109340000
                  ],
                  [
                    1,
                    2,
                    2,
                    2,
                    2
                  ],
                  [
                    1,
                    0.5,
                    0.2,
                    0.1,
                    0.32
                  ]
                ]
              }
            }
          ]
        }
      ],
      "title": "Reproduced with embedded data",
      "type": "datagrid"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >datagrid @ 10.0.0-pre</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[grafana-googlesheets-datasource]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 1 frames, 3 fields, 5 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>10.1.0-pre (c0ec1060919) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"datasource\": {\n    \"type\": \"grafana-googlesheets-datasource\",\n    \"uid\": \"PB0CCE99F8730D01D\"\n  },\n  \"gridPos\": {\n    \"h\": 8,\n    \"w\": 12,\n    \"x\": 0,\n    \"y\": 0\n  },\n  \"id\": 1,\n  \"options\": {\n    \"selectedSeries\": 0\n  },\n  \"pluginVersion\": \"10.0.0-pre\",\n  \"targets\": [\n    {\n      \"cacheDurationSeconds\": 300,\n      \"datasource\": {\n        \"type\": \"grafana-googlesheets-datasource\",\n        \"uid\": \"PB0CCE99F8730D01D\"\n      },\n      \"key\": \"Q-b5f4b02e-64c9-4475-b3b1-5992b051641a-0\",\n      \"refId\": \"A\",\n      \"spreadsheet\": \"1399MxrYphRgkJCd_Qh9KfljIBjjjBFodhRz0gHc2MCw\"\n    }\n  ],\n  \"title\": \"New Panel\",\n  \"type\": \"datagrid\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: New Panel // 2023-05-03 15:35:05",
  "tags": [
    "debug",
    "debug-datagrid"
  ],
  "time": {
    "from": "2023-05-03T07:35:05.384Z",
    "to": "2023-05-03T13:35:05.384Z"
  }
}
```
</details>

### Grafana Platform?

Other

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

No

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by mdvictor**
**What is this feature?**

Make datagrid work with `displayName` and `displayNameFromDS` when renaming

**Why do we need this feature?**

Fixes a bug where we cannot rename columns if the field name is set in one of the above properties.

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #67731

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/panel/datagrid/DataGridPanel.tsx [hunk 1]
```diff
@@ -210,7 +210,14 @@ export function DataGridPanel({ options, data, id, fieldConfig, width, height }:
 
   const onRenameInputBlur = (columnName: string, columnIdx: number) => {
     const fields = frame.fields.map((f) => f);
-    fields[columnIdx].name = columnName;
+
+    if (fields[columnIdx].config.displayName) {
```
Comment (ryantxu) [inline public/app/plugins/panel/datagrid/DataGridPanel.tsx:214]: rather than have this... does it make more sense to remove the configs?  (and perhaps try to remove any field overrides setting the name/display name?

I don't think things are going to land well if we try to reverse engineer the results that come out of:
```
      const name = getFieldDisplayName(field, frame, data);
```

**Review by zoltanbedi — APPROVED** [review]
lgtm

File: public/app/plugins/panel/datagrid/state.ts [hunk 2]
```diff
@@ -219,14 +219,12 @@ export const datagridReducer = (state: DatagridState, action: DatagridAction): D
...
-          const displayName = getFieldDisplayName(field, updateColumnsPayload.frame);
-
           // find column by field name and update width in new set. We cannot use index because
           // if a column gets deleted we don't know the correct index anymore
-          const width = state.columns.find((column) => column.title === displayName)?.width;
+          const width = state.columns.find((column) => column.title === field.name)?.width;
 
           return {
-            title: displayName,
+            title: field.name,
```
Comment (ryantxu) [inline public/app/plugins/panel/datagrid/state.ts:227]: IIUC, this now ignores displayName/displayNameFromDS -- that seems wrong.  I assume we want to have the same names we show elsewhere.

Can we get the name from getFieldDisplayName(), and only clear the configs when we change the name?

Comment (mdvictor) [reply public/app/plugins/panel/datagrid/state.ts]: You're right, I pushed a fix

**Review by baldm0mma — APPROVED** [review]
Worked for me. Nice!
