### PR TITLE
Alerting: Include a list of ref_Id and aggregated datasource UIDs to alerts when state reason is NoData

### LINKED ISSUE #88184: Alerting: Include a list of ref_Id and datasource UID to alerts when state reason is NoData
In Grafana Alerting a rule evaluation can have basically 3 outcomes:
- normal evaluations with results
- no-data 
- error

For the last two outcomes, which are considered as exceptional, Grafana offers options to gracefully handle the result. Such options are: 
- Assume "normal" state for all known states from previous evaluations, e.g. if there are 3 dimensions with current state Alerting and 3 with Normal, all 6 states will be transitioned to Normal, and active alerts are resolved.
- Assume "alerting" state, e.g. the same situation, all normal states will be transitioned to "Alerting" respecting pending interval.
- assume the same state as the current state (aka "Keep Last State"), e.g. all states will be maintained, if pending interval is exceeded alert instance in "Pending" state gets promoted to "Alerting".

The fourth option is "do nothing". In that case, a new alert instance is created in the state "Alerting", which creates special kind of alerts with names DatasourceNoData and DatasourceError. The alerts contain information about data source UID and comma-separated refIDs of queries that returned no data (or error). 

The proposal is to add that information to the first 3 options. The only place that makes sense is to add them to annotations, which will keep the same alert and will be sent to the recipient after a "repeat interval".

### PR DESCRIPTION
**Pull request by wasim-nihal**
**What is this feature?**

include a list of ref_Id and aggregated datasource UIDs to alerts when state reason is NoData and is executed as either OK, Alerting or KeepLast. 

**Why do we need this feature?**

see: https://github.com/grafana/grafana/issues/88184

**Who is this feature for?**

grafana users using alerting feature

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/88184

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by wasim-nihal** [comment]
@yuri-tceretian , could you please review and let me know if any changes are needed?

File: pkg/services/ngalert/state/manager_private_test.go [hunk 1]
```diff
@@ -754,9 +754,9 @@ func TestProcessEvalResults_StateTransitions(t *testing.T) {
 	t.Run("no-data", func(t *testing.T) {
 		rules := map[ngmodels.NoDataState]*ngmodels.AlertRule{
 			ngmodels.NoData:   baseRuleWith(ngmodels.RuleMuts.WithNoDataExecAs(ngmodels.NoData)),
-			ngmodels.Alerting: baseRuleWith(ngmodels.RuleMuts.WithNoDataExecAs(ngmodels.Alerting)),
-			ngmodels.OK:       baseRuleWith(ngmodels.RuleMuts.WithNoDataExecAs(ngmodels.OK)),
-			ngmodels.KeepLast: baseRuleWith(ngmodels.RuleMuts.WithNoDataExecAs(ngmodels.KeepLast)),
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/state/manager_private_test.go:759]: this makes tests pass but this is a hack, which just make all test cases treat these annotations as rule-defined. The real tests that assert handling of NoData result, happen to pass because they create matching annotations. 
We should fix all the test cases instead.

**Review by yuri-tceretian — CHANGES_REQUESTED** [review]
Thanks for contribution! The change looks good however tests need to be fixed correctly. I understand that's hard task. So, I went ahead and patched the tests. Unfortunately, I cannot commit to your repositroy. Please apply this patch 
https://gist.github.com/yuri-tceretian/fddb785c5b80f9d0f30a602e5b7d7be6

**Comment by yuri-tceretian** [comment]
@wasim-nihal can you please merge the Grafana's main branch into your feature branch. The build fails.

**Comment by wasim-nihal** [comment]
> @wasim-nihal can you please merge the Grafana's main branch into your feature branch? The build fails.

Done. @yuri-tceretian could you please retrigger?

**Review by yuri-tceretian — APPROVED** [review]
LGTM. Thanks for contributing
