### PR TITLE
CloudWatch Logs: Fix log query display name when used with expressions

### LINKED ISSUE #69002: CloudWatch Logs: Expressions/Alerts have doubled legend name
### 
# What went wrong?

**What happened**:
When using a CloudWatch logs query that returns multiple time series and an expression, the legend label lists it the grouping field repeated:
Screenshot 2023-05-24 at 11 19 26 AM

**What did you expect to happen**:
I expect it to use the grouping field and the metric, like it does without the expression:
Screenshot 2023-05-24 at 11 19 56 AM

### 
# How do we reproduce it?

It can be reproduced with our external-dev source and the following query:
Screenshot 2023-05-24 at 11 19 39 AM

### 
# What Grafana version are you using?

main

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

I suspect that it may be related to https://github.com/grafana/grafana/pull/66039 for ElasticSearch, where they had to stop setting the frame name, which we set in CloudWatch [here](https://github.com/grafana/grafana/blob/f91c1b9897148011a4dcb1a536020e11c3529052/pkg/tsdb/cloudwatch/log_query.go#L203).

### PR DESCRIPTION
**Pull request by iwysiu**
**What is this feature?**

Fixes issue where CloudWatch Logs queries with expressions would label it as the name twice:
image

now only shows the name once:
Screenshot 2023-09-06 at 6 05 33 PM

**Which issue(s) does this PR fix?**:

Fixes #69002

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/tsdb/cloudwatch/log_query.go [hunk 1]
```diff
@@ -202,8 +202,20 @@ func groupResults(results *data.Frame, groupingFieldNames []string, removeNonTim
 			newFrame := results.EmptyCopy()
 			newFrame.Name = groupKey
 			newFrame.Meta = results.Meta
-			// remove grouping indices
-			newFrame.Fields = removeFieldsByIndex(newFrame.Fields, removeFieldIndices)
+			if fromSyncQuery {
```
Comment (fridgepoet) [inline pkg/tsdb/cloudwatch/log_query.go:205]: how come it has to only be on sync queries?

**Review by fridgepoet — APPROVED** [review]

File: pkg/tsdb/cloudwatch/log_query.go (hunk 1 above)
Comment (iwysiu) [reply pkg/tsdb/cloudwatch/log_query.go:205]: I could do it on both, but it gets a bit weird if I do it on non-sync queries. When I fixed the parsing to remove the naming fields, I only did it in the case of sync queries (which was maybe a mistake) so if I set the display name for non-sync queries it ends up sort of doubling those names.
CloudWatch logs query without expression
without DisplayNameFromDS:
Screenshot 2023-09-08 at 10 50 19 AM

with DisplayNameFromDS:
Screenshot 2023-09-08 at 10 49 01 AM
