### PR TITLE
Snapshots: Fix V2 Snapshot data coupling

### LINKED ISSUE #113622: Snapshots: Dynamic dashboards issue
After enabling this FF in a customer instance, they complained that snapshots are broken
[Related escalation](https://github.com/grafana/support-escalations/issues/19336)

### PR DESCRIPTION
**Pull request by CollinFingar**
**What is this feature?**
This fixes an issue with saving V2 snapshots with an `All` value in a query template variable

**Why do we need this feature?**
To correctly render panel data

**Who is this feature for?**
V2 snapshots users

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/113622

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by nmarrs** [comment]
It would be great to include a repro case for testing this out locally to confirm fix (without needing to dig into underlying escalation). Also we should consider adding some test coverage for this so we can be more confident about functionality in the future 👍

File: public/app/features/dashboard-scene/serialization/transformSceneToSaveModelSchemaV2.ts [hunk 1]
```diff
@@ -290,9 +293,51 @@ function getPanelLinks(panel: VizPanel): DataLink[] {
...
+
+    const snapshotQuery: DataQueryKind = {
+      kind: 'DataQuery',
+      version: defaultDataQueryKind().version,
+      group: 'grafana',
+      datasource: {
+        name: 'grafana',
+      },
+      spec: {
+        queryType: GrafanaQueryType.Snapshot,
```
Comment (harisrozajac) [inline public/app/features/dashboard-scene/serialization/transformSceneToSaveModelSchemaV2.ts:323]: I see this logic was in V1, and it looks like we missed it in V2. Looks good!

**Review by harisrozajac — APPROVED** [review]
Nice work! 🙌

**Comment by CollinFingar** [comment]
To reproduce the bug locally:
- Checkout main / comment out the code introduced by this branch
- Turn on V2 locally with `dashboardNewLayouts` feature flag
- Go to a dashboard with a query template variable configured and set to an `All` option
- Create a snapshot for the dashboard and navigate to it
- You should see that all the panels are missing data

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/20376114489)
- Version: 12.4.0-20376114489
