### PR TITLE
Geomap: Fix geohash editor settings

### LINKED ISSUE #45814: Geomap Panel - Geohash Doesn't Work
**What happened**:

When I select geohash, I get no result. 

image

This is the raw data:

image

**What you expected to happen**:

I expect to see markers on the map.

**Anything else we need to know?**:

POSTGIS Version:

```
POSTGIS="3.1.2 cbe925d" [EXTENSION] PGSQL="130" GEOS="3.7.1-CAPI-1.11.1 27a5e771" PROJ="Rel. 5.2.0, September 15th, 2018" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.3.1" WAGYU="0.5.0 (Internal)"
```

Data Type of the column: ```geography(Point, 4326)```

**Environment**:
- Grafana version: 8.4.1
- OS Grafana is installed on: official docker image, grafana/grafana:latest
- Grafana plugins: GEOMAP

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes #45814

This updates the query editor to save field mappings to the proper path.  Previously it was saving:

### Before
```{
 "location: {
    "": {
       "geohash": "field name"
    },
    "mode": "geohash"
  }
}
```

### After
```{
 "location: {
    "geohash": "field name"
    "mode": "geohash"
  }
}
```

We can add an e2e test in a PR that is not backported to 8x

### CODE REVIEW

File: public/app/features/geo/editor/locationEditor.ts [hunk 1]
```diff
@@ -51,7 +51,7 @@ export function addLocationFields<TOptions>(
 
     case FrameGeometrySourceMode.Geohash:
       builder.addFieldNamePicker({
-        path: `${prefix}.geohash`,
+        path: `${prefix}geohash`,
```
Comment (ryantxu) [inline public/app/features/geo/editor/locationEditor.ts:54]: 🤦

**Comment by ryantxu** [comment]
@nmarrs -- I removed the TODOs from this one... since I think we should add them, but not backport to 8.5.  I think this one letter fix is ready to go

**Review by nmarrs — APPROVED** [review]
verified fix works locally ✨
