### PR TITLE
Dashboard: Alerts user to incorrect tag format for JSON import

### LINKED ISSUE #54285: Malformed tags cause hidden title and settings page crash
**What happened**:
In the browse tab Grafana dashboards were shown without a title and with empty/no tags.
image
Clicking on them is possible and they have a page, but their settings page is broken.
grafana settings

**What you expected to happen**:
Grafana dashboards show their title and tags correctly and the settings page doesn't crash.

To prevent this there should be a warning or an auto conversion into valid tags when importing/uploading dashboards.

**How to reproduce it (as minimally and precisely as possible)**:
Import a basic dashboard where the tags are not a simple list
(if an error occurs after importing this minimalistic example, go back to the Browse tab and look into the folder.)

```
{
  "schemaVersion": 36,
  "tags": "tag",
  "title": "Not a list"
}
```
```
{
  "schemaVersion": 36,
  "tags": ["tag", ["nested tag"]],
  "title": "Nested lists"
}
```

**Environment**:
- Grafana version: v9.0.3-0dc0087e
- Data source type & version: Prometheus
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Windows / Firefox
- Grafana plugins: Grafana Cloud defaults
- Others:

**Anything else we need to know?**:
<details>
  <summary>Settings page error log</summary>

```
TypeError: n.map is not a function

ya@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/3372.c2c078d20bd717e87443.js:2478:475
div
div
h@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/3372.c2c078d20bd717e87443.js:458:178
div
div
29483/Yt<@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/3372.c2c078d20bd717e87443.js:7025:3892
g@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/4902.331bf177ac0b86d7f476.js:2:1096373
div
div
div
div
div
t@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/4902.331bf177ac0b86d7f476.js:2:777260
c@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/3372.c2c078d20bd717e87443.js:314:410
div
h@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/4902.331bf177ac0b86d7f476.js:2:146043
Sn@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/3372.c2c078d20bd717e87443.js:7028:5638
div
ri@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/DashboardPage.2f4418b7a6b67910c0e8.js:532:7263
DashboardPage
g@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/4902.331bf177ac0b86d7f476.js:2:1096373
n@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/4902.331bf177ac0b86d7f476.js:2:1042704
rt@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/3372.c2c078d20bd717e87443.js:5384:23611
t@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/4902.331bf177ac0b86d7f476.js:2:1111691
t@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/4902.331bf177ac0b86d7f476.js:2:1113712
main
t@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/4902.331bf177ac0b86d7f476.js:2:1108309
div
ds@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/3372.c2c078d20bd717e87443.js:2569:1029
87686/t.KBarProvider@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/4902.331bf177ac0b86d7f476.js:2:358763
11622/c<@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/3372.c2c078d20bd717e87443.js:6003:27783
El@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/3372.c2c078d20bd717e87443.js:3111:467
Vl@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/3372.c2c078d20bd717e87443.js:3111:1023
y@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/4902.331bf177ac0b86d7f476.js:2:141235
nt@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/3372.c2c078d20bd717e87443.js:5384:23144
l@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/4902.331bf177ac0b86d7f476.js:2:1094416
Rt@https://grafana-assets.grafana.net/grafana-pro/9.0.3-0dc0087e/public/build/3372.c2c078d20bd717e87443.js:5397:167
```

</details>

### PR DESCRIPTION
**Pull request by iamelDuderino**
**What this PR does / why we need it**:

Fixes #54285: Malformed tags cause hidden title and settings page crash

**Which issue(s) this PR fixes**:
Fixes #54285

**Special notes for your reviewer**:

image

image

### CODE REVIEW

File: public/app/features/manage-dashboards/utils/validation.ts [hunk 1]
```diff
@@ -4,8 +4,29 @@ import { validationSrv } from '../services/ValidationSrv';
...
+      // If dashboard.tags && not Array
+    } else if (dashboard.tags && !Array.isArray(dashboard.tags)) {
+      return 'error: tags expected Array';
+      // Else generic JSON test passes and no Tags provided, then import dashboard
+    } else {
+      return true;
+    }
   } catch (error) {
     return 'Not valid JSON';
   }
```
Comment (polibb) [inline public/app/features/manage-dashboards/utils/validation.ts:32]:
```suggestion
  }
  if (dashboard.tags) {
    if (Array.isArray(dashboard.tags)) {
      const hasInvalidTag = dashboard.tags.some((tag: string) => typeof tag !== 'string');
      if (hasInvalidTag) {
        return 'error: tags expected Array of Strings';
      }
    } else {
      return 'error: tags expected Array';
    }
  }
      
```

File: public/app/features/manage-dashboards/utils/validation.ts [hunk 2]
```diff
@@ -4,8 +4,29 @@ import { validationSrv } from '../services/ValidationSrv';
...
+      } else {
+        return 'error: tags expected Array of Strings';
+      }
+      // If dashboard.tags && not Array
+    } else if (dashboard.tags && !Array.isArray(dashboard.tags)) {
+      return 'error: tags expected Array';
+      // Else generic JSON test passes and no Tags provided, then import dashboard
+    } else {
+      return true;
+    }
```
Comment (polibb) [inline public/app/features/manage-dashboards/utils/validation.ts:29]:
```suggestion
    let dashboard = JSON.parse(json);
```

File: public/app/features/manage-dashboards/utils/validation.ts [hunk 3]
```diff
@@ -4,8 +4,29 @@ import { validationSrv } from '../services/ValidationSrv';
 
 export const validateDashboardJson = (json: string) => {
   try {
-    JSON.parse(json);
-    return true;
+    let dashboard = JSON.parse(json);
+    // If dashboard.tags provided && is Array
```
Comment (polibb) [inline public/app/features/manage-dashboards/utils/validation.ts:8]: The comments don't add any new information and the code is easy to read, so what do you think about having no comments? It seems to just create twice as many lines

File: public/app/features/manage-dashboards/utils/validation.ts (hunk 2 above)
Comment (polibb) [reply public/app/features/manage-dashboards/utils/validation.ts:29]: It seems that there's no need of this code block to be in a `try {} catch {}`. We can just leave the `JSON.parse` then and not return true until all validation has passed?

File: public/app/features/manage-dashboards/utils/validation.ts (hunk 1 above)
Comment (polibb) [reply public/app/features/manage-dashboards/utils/validation.ts:32]: Having less `if else`s and variables makes it easier to read IMO. What do you think of those suggestions?

**Review by polibb — CHANGES_REQUESTED** [review]
Thank you for including this validation and tests for it! 
I haven't seen snake case anywhere in the tests, why did you choose it over camel case here?

File: public/app/features/manage-dashboards/utils/validation.ts (hunk 2 above)
Comment (ivanortegaalba) [reply public/app/features/manage-dashboards/utils/validation.ts:29]: If I'm not wrong, the try/catch is part of the validation. An invalid JSON can be introduced in the input, and this function will be called with it. If we don't have the try/catch the function will throw an uncontrolled error.

Comment (polibb) [reply public/app/features/manage-dashboards/utils/validation.ts:29]: When an invalid JSON is introduced in the input, the try/catch will catch the error and return `return 'Not valid JSON';`. But the rest of the validation in this method has no need of a try/catch since it's not going to throw unexpected errors from anywhere.

File: public/app/features/manage-dashboards/utils/validation.ts [hunk 4]
```diff
@@ -4,11 +4,44 @@ import { validationSrv } from '../services/ValidationSrv';
 
 export const validateDashboardJson = (json: string) => {
   try {
```
Comment (polibb) [inline public/app/features/manage-dashboards/utils/validation.ts:6]:
```suggestion
  let dashboard;
  
  try {
```

File: public/app/features/manage-dashboards/utils/validation.ts [hunk 5]
```diff
@@ -4,11 +4,44 @@ import { validationSrv } from '../services/ValidationSrv';
...
+      // Continue to import dashboard if Tags in correct format
+      if (cont) {
+        return true;
+      } else {
+        return 'error: tags expected Array of Strings';
+      }
+      // If dashboard.tags && not Array
+    } else if (dashboard.tags && !Array.isArray(dashboard.tags)) {
+      return 'error: tags expected Array';
+      // Else generic JSON test passes and no Tags provided, then import dashboard
```
Comment (polibb) [inline public/app/features/manage-dashboards/utils/validation.ts:26]:
```suggestion
```

File: public/app/features/manage-dashboards/utils/validation.ts [hunk 6]
```diff
@@ -4,11 +4,44 @@ import { validationSrv } from '../services/ValidationSrv';
...
+    } else {
+      return true;
+    }
   } catch (error) {
     return 'Not valid JSON';
   }
+  if (dashboard.tags) {
```
Comment (polibb) [inline public/app/features/manage-dashboards/utils/validation.ts:33]:
```suggestion
  if (dashboard && dashboard.tags) {
```

**Comment by polibb** [comment]
Note for the future:
There is a great new way of generating models for the frontend and backend, a _schematisation_ of sorts. This is still behind feature flags (e.g. `validateDashboardsOnSave`) at the moment and is not known when we will have it done _not_ in alpha/beta state 😊. When it is done the model of the dashboard itself will correctly check for the contents of the JSON and this validation will probably be able to be removed. Right now it is much needed, nevertheless.

File: public/app/features/manage-dashboards/utils/validation.ts [hunk 7]
```diff
@@ -3,12 +3,18 @@ import { getBackendSrv } from '@grafana/runtime';
 import { validationSrv } from '../services/ValidationSrv';
 
 export const validateDashboardJson = (json: string) => {
-  try {
-    JSON.parse(json);
-    return true;
-  } catch (error) {
-    return 'Not valid JSON';
+  let dashboard = JSON.parse(json);
```
Comment (polibb) [inline public/app/features/manage-dashboards/utils/validation.ts:6]: hi @iamelDuderino ✨. We need to pass the `JSON.parse(json)` through a `try {} catch {}` because if it fails the `validateDashboardJson` will throw an unexpected that's never handled and the page will fail to load.

Comment (iamelDuderino) [reply public/app/features/manage-dashboards/utils/validation.ts]: Hey @polibb Oops! You are correct in that the page just simply does nothing if the json is invalid. I have re-added the `try {} catch {}` and included a test for it, as well as reworded my initial errors to better align with the existing format from the catch statement. Please let me know if there is anything further, thanks!

**Review by polibb — COMMENTED** [review]
Hello @iamelDuderino 😊. The solution looks good! 
It seems like the build is failing, would you try merging your branch with `grafana:main` to be up to date and to re-run the build, so we see if it's some flaky tests or something we have to look into and fix here? This is also probably going to fix the failing Enterprise build.

**Review by polibb — APPROVED** [review]
Great choice for a first task and impressive execution and implementation, @iamelDuderino!
