### PR TITLE
fix app support and add an alpha example

### LINKED ISSUE #16433: Migrate app pages to react
The existing angular pages let you build a set of pages and a config page.  The config page shows up at:
http://localhost:3000/plugins/ryantxu-firebase-app/edit

The app can include pages using somethign like:
```
  "includes": [
    {
      "type": "page",
      "name": "Debug",
      "component": "DebugPageCtrl",
      "role": "Viewer",
      "addToNav": true,
      "defaultNav": true
    },
```
That page then shows up under:
http://localhost:3000/plugins/ryantxu-firebase-app/page/debug

When we move to react, could the plugin expose a single component that handles all paths?  Essentially a root page with `<Router>`  This would expose everything under:
 *  http://localhost:3000/plugins/ryantxu-firebase-app/app/*
Or:
 *  http://localhost:3000/a/ryantxu-firebase-app/*
 *  http://localhost:3000/app/ryantxu-firebase-app/*

The `plugin.json` would be the same, but each Page would not need to map to a component.

This would allow apps to build much more rich UIs that support parameters.  

I think the react page should be in charge of the tabs/header, not the container.  See #11824  We can have a simple react component to match the standard header format

### LINKED ISSUE #16584: App pages don't work in master
The appPlugin in master only registers `ConfigCtrl` this breaks any app plugin using pages.

I think this change happened at #16364

### PR DESCRIPTION
**Pull request by ryantxu**
fixes #16584, and #16585

* cleans up the pluginModel, adding type and jsonData
* uses a single react friendly `getPluginSettings` cache 
* holds the angular plugin pages in AppPlugin
* adds an alpha example app -- it does not do anything

### CODE REVIEW

**Comment by ryantxu** [comment]
@torkelo -- this is ready to look at, the open question is if we should have an alpha app installed.  It would be nice if it did *something* but I think it is important to have something in the code that exercises this core feature :)

File: public/app/features/plugins/plugin_component.ts [hunk 1]
```diff
@@ -155,26 +155,26 @@ function pluginDirectiveLoader($compile, datasourceSrv, $rootScope, $q, $http, $
...
-            Component: appPlugin.components.ConfigCtrl,
+            Component: appPlugin.angular.ConfigCtrl,
           };
         });
       }
       // App Page
       case 'app-page': {
         const appModel = scope.ctrl.appModel;
-        return importAppPlugin(appModel.module).then(appPlugin => {
+        return importAppPlugin(appModel).then(appPlugin => {
```
Comment (torkelo) [inline public/app/features/plugins/plugin_component.ts]: this looks strange, only passing the module and not the app plugin model?

File: packages/grafana-ui/src/types/plugin.ts [hunk 2]
```diff
@@ -76,16 +83,38 @@ export interface PluginMetaInfo {
...
     ConfigCtrl?: any;
+    pages: { [component: string]: any };
   };
 
-  pages: { [str: string]: any };
-
-  constructor(ConfigCtrl: any) {
-    this.components = {
-      ConfigCtrl: ConfigCtrl,
+  constructor(meta: PluginMeta, pluginExports: any) {
```
Comment (torkelo) [inline packages/grafana-ui/src/types/plugin.ts]: problem with this is that we want the constructor to be (eventually when apps start using this) used by the plugin code (module.ts) so sending in meta wont work then, has to be done later by the app via some setter. 

I was thinking something like:
```
export cont plugin = new AppPlugin()
  .setAngularConfig(ConfigCtrl)
  .setAngularPage(MyPageController);
```

Something we can refactor to after this PR, just wondering if you had other plans

File: public/app/features/plugins/plugin_component.ts (hunk 1 above)
Comment (torkelo) [reply public/app/features/plugins/plugin_component.ts]: ah, I see importAppPlugin is a bit different

**Review by torkelo — APPROVED** [review]
Looks good, just a few things with the AppPlugin model that looks temporary (meta in constructor, etc)

File: packages/grafana-ui/src/types/plugin.ts (hunk 2 above)
Comment (ryantxu) [reply packages/grafana-ui/src/types/plugin.ts]: +1 for using the same form as panel plugins.

This is a bit more weird because the meta defines what needs to be imported.  My goal was to get the apps working again with this PR, and then improve it in #16586
