### PR TITLE
Geomap: Fix route layer zoom behavior

### LINKED ISSUE #63323: Geomap: Zoom behavior
Unusual behavior observed with current (main branch) version of OpenLayers and the latest version. Mostly seeing some vector layers disappearing in certain zoom ranges.

### PR DESCRIPTION
**Pull request by drew08t**
What this PR does / why we need it:
Currently route layer has unusual rendering behavior when zooming. This occurs when segments are small enough to share a pixel and are not rendered.

Before:
Feb-17-2023 16-17-49

After (1000 point route layer):
Feb-17-2023 16-19-53

Closes #63323

### CODE REVIEW

File: public/app/plugins/panel/geomap/layers/data/routeLayer.tsx [hunk 1]
```diff
@@ -147,9 +145,38 @@ export const routeLayer: MapLayerRegistryItem<RouteConfig> = {
...
+              //TODO: let's try to find a less intensive check
+              const pixel1 = map.getPixelFromCoordinate(coordinates[j]);
+              const pixel2 = map.getPixelFromCoordinate(coordinates[i + 1]);
+              const deltaX = Math.abs(pixel1[0] - pixel2[0]);
+              const deltaY = Math.abs(pixel1[1] - pixel2[1]);
+              // Only render segment if change in pixel coordinates is significant enough
+              if (deltaX > 2 || deltaY > 2) {
+                flowStyle.setGeometry(LS);
+                styles.push(flowStyle);
+                j = i + 1;
```
Comment (nmarrs) [inline public/app/plugins/panel/geomap/layers/data/routeLayer.tsx:158]: This logic is a little hard for me to follow / understand, what index is `j` tracking? Are we basically determining at what resolution it is necessary to draw a line vs a single point or?

This logic may be clearer if we broke it out into a util func with a few unit tests for good measure 😃

Comment (drew08t) [reply public/app/plugins/panel/geomap/layers/data/routeLayer.tsx:158]: Great suggestion, will pull it out and try to simplify!

File: public/app/plugins/panel/geomap/utils/utils.ts [hunk 2]
```diff
@@ -117,6 +117,25 @@ export const getNextLayerName = (panel: GeomapPanel) => {
   return `Layer ${Date.now()}`;
 };
 
+export function isSegmentVisible(
```
Comment (nmarrs) [inline public/app/plugins/panel/geomap/utils/utils.ts:120]: Great job on this refactor! I think just adding a few unit tests for this util function would be good 👍

Comment (drew08t) [reply public/app/plugins/panel/geomap/utils/utils.ts:120]: I created two follow-up issues to address this. Unfortunately, because testing needs to occur postrender with canvas, Jest has limitations.

https://github.com/grafana/grafana/issues/64182
https://github.com/grafana/grafana/issues/64183

**Review by nmarrs — APPROVED** [review]
Zoom zoom
