### PR TITLE
Alerting: Disallow invalid rule namespace UIDs in provisioning API

### LINKED ISSUE #53151: Alerting: Provisioning rule API should validate rule namespace
**What happened**:

The provisioning rule API allows any string as the NamespaceUID - it doesn't check to see whether the folder actually exists before creation. The result is that a rule is created outside of any folder. There are periodic warnings in the logs: `failed to fetch alert rule namespace`.

**What you expected to happen**:

I expected the API to validate the `NamespaceUID` field against the created folders.

**How to reproduce it (as minimally and precisely as possible)**:

1. Issue a POST request to `/api/v1/provisioning/rules` with an invalid `NamespaceUID`.
2. The request succeeds.

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by rwwiv**
**What is this feature?**

This PR changes the provisioning API to reject requests that create rules which reference a nonexistent folder or do not have a folderUID set.

**Why do we need this feature?**

This removes two sources of orphaned rules:
1. API provisioned rules not belonging to a folder
2. API provisioned rules that reference a nonexistent folder

**Who is this feature for?**

Users of the alerting provisioning API.

**Which issue(s) does this PR fix?**:

Resolves #53151

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/services/ngalert/provisioning/alert_rules.go [hunk 1]
```diff
@@ -639,3 +663,37 @@ func (service *AlertRuleService) checkGroupLimits(group models.AlertRuleGroup) e
...
+		// if namespace UID is set, check that it exists
+		_, err := service.folderService.Get(ctx, &folder.GetFolderQuery{
+			OrgID: rule.OrgID,
+			UID:   &rule.NamespaceUID,
+			// use bg user to avoid access control checks
+			SignedInUser: accesscontrol.BackgroundUser(
+				"ngalert_provisioning",
+				rule.OrgID,
+				org.RoleAdmin,
+				[]accesscontrol.Permission{{Action: dashboards.ActionFoldersRead, Scope: dashboards.ScopeFoldersAll}},
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/provisioning/alert_rules.go:684]: Why do you need this fake user here?

Comment (rwwiv) [reply pkg/services/ngalert/provisioning/alert_rules.go:684]: Discussed this privately. TL;DR is that this was to prevent breaking changes for custom roles, however we decided that was worth avoiding creating a background/service account.

File: pkg/services/provisioning/alerting/rules_provisioner.go [hunk 2]
```diff
@@ -85,9 +85,9 @@ func (prov *defaultAlertRuleProvisioner) provisionRule(
 		return err
 	} else if err != nil {
 		prov.logger.Debug("creating rule", "uid", rule.UID, "org", rule.OrgID)
-		// 0 is passed as userID as then the quota logic will only check for
-		// the organization quota, as we don't have any user scope here.
-		_, err = prov.ruleService.CreateAlertRule(ctx, rule, alert_models.ProvenanceFile, 0)
+		// a nil user is passed in as then the quota logic will only check for
+		// the organization quota since we don't have any user scope here.
+		_, err = prov.ruleService.CreateAlertRule(ctx, nil, rule, alert_models.ProvenanceFile)
```
Comment (yuri-tceretian) [inline pkg/services/provisioning/alerting/rules_provisioner.go:90]: let's create a background user with all the permissions needed: folders, data sources alert rules etc.

File: pkg/services/ngalert/tests/fakes/rules.go [hunk 3]
```diff
@@ -342,3 +342,37 @@ func (f *RuleStore) IncreaseVersionForAllRulesInNamespace(_ context.Context, org
 func (f *RuleStore) CountInFolders(ctx context.Context, orgID int64, folderUIDs []string, u identity.Requester) (int64, error) {
 	return 0, nil
 }
+
+func (f *RuleStore) GetOrCreateDefaultAlertingNamespace(ctx context.Context, orgID int64) (*folder.Folder, error) {
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/tests/fakes/rules.go:346]: once file provisioning user is created, we can make this method accept the user and we will not have to create fake user here. Also, this will protect us from possible future problems in provisioning API (e.g. due to a bug user will be able to create folders via rules API)

File: pkg/services/ngalert/provisioning/alert_rules.go [hunk 4]
```diff
@@ -145,6 +150,13 @@ func (service *AlertRuleService) CreateAlertRule(ctx context.Context, rule model
 	if err != nil {
 		return models.AlertRule{}, err
 	}
+	defaultNamespace, err := service.ruleStore.GetOrCreateDefaultAlertingNamespace(ctx, rule.OrgID)
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/provisioning/alert_rules.go:153]: I think we should propagate the user here as well

File: pkg/services/provisioning/alerting/rules_provisioner.go (hunk 2 above)
Comment (rwwiv) [reply pkg/services/provisioning/alerting/rules_provisioner.go:90]: Right now we have no way to ensure the UserID of a background user is `0`, so if that changes this would break. I want to keep the semantics of this as close to before as possible in this PR, probably worth looking at how to solve that in a follow up though.

**Review by yuri-tceretian — APPROVED** [review]
LGTM.

File: pkg/services/ngalert/provisioning/alert_rules.go [hunk 5]
```diff
@@ -639,3 +652,30 @@ func (service *AlertRuleService) checkGroupLimits(group models.AlertRuleGroup) e
...
+// ensureRuleNamespace ensures that the rule has a valid namespace UID.
+// If the rule does not have a namespace UID or the namespace (folder) does not exist it will return an error.
+func (service *AlertRuleService) ensureRuleNamespace(ctx context.Context, user identity.Requester, rule models.AlertRule) error {
+	if user == nil {
+		return nil // noop if no user
+	}
+
+	if rule.NamespaceUID == "" {
+		return fmt.Errorf("%w: folderUID must be set", models.ErrAlertRuleFailedValidation)
+	}
```
[the remark this answers is not in the document]
Comment (rwwiv) [reply pkg/services/ngalert/provisioning/alert_rules.go:665]: I was worried about introducing error states to file provisioning, but the alternative is orphaned rules so that does seem like the better option.
