### PR TITLE
LDAP test: Fix page crash

### LINKED ISSUE #100030: LDAP: Test user mapping results in stack trace
### What happened?

I am trying to use "Test user mapping" in `grafana.ourdomain.dev/admin/authentication/ldap`, but when I enter a username and click the "Run" button, I get this stack trace:

```
TypeError: Cannot use 'in' operator to search for 'aria-label' in undefined

    at https://grafana.ourdomain.dev/public/build/7836.125f6c2757ee541f83cc.js:1:179100
    at On (https://grafana.ourdomain.dev/public/build/3196.0d4b1a0bf9502490c781.js:176:10380)
    at o
    at cell (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:1560:33850)
    at td
    at tr
    at tbody
    at table
    at div
    at P (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:31:22007)
    at bn (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:1560:33623)
    at div
    at https://grafana.ourdomain.dev/public/build/7836.125f6c2757ee541f83cc.js:1:145004
    at xs (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:1560:35932)
    at section
    at div
    at https://grafana.ourdomain.dev/public/build/7836.125f6c2757ee541f83cc.js:1:145004
    at u (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:159:93406)
    at div
    at div
    at n (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:159:47129)
    at div
    at O (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:159:97344)
    at Es (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:1560:36448)
    at Fr (https://grafana.ourdomain.dev/public/build/3196.0d4b1a0bf9502490c781.js:176:44470)
    at Suspense
    at p (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:12:145768)
    at Qu (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:1560:82037)
    at ku (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:1560:82688)
    at x (https://grafana.ourdomain.dev/public/build/9890.2f086d4a8fdbd47b8d24.js:284:4572)
    at Ot (https://grafana.ourdomain.dev/public/build/9890.2f086d4a8fdbd47b8d24.js:284:12203)
    at div
    at https://grafana.ourdomain.dev/public/build/7836.125f6c2757ee541f83cc.js:1:145004
    at main
    at div
    at div
    at div
    at tf (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:1560:111970)
    at uf (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:1560:116902)
    at u (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:288:201930)
    at x (https://grafana.ourdomain.dev/public/build/9890.2f086d4a8fdbd47b8d24.js:284:4572)
    at Ot (https://grafana.ourdomain.dev/public/build/9890.2f086d4a8fdbd47b8d24.js:284:12203)
    at ht (https://grafana.ourdomain.dev/public/build/9890.2f086d4a8fdbd47b8d24.js:284:11536)
    at Wt (https://grafana.ourdomain.dev/public/build/9890.2f086d4a8fdbd47b8d24.js:275:18349)
    at P (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:5:194373)
    at nt (https://grafana.ourdomain.dev/public/build/9890.2f086d4a8fdbd47b8d24.js:284:28185)
    at Cc (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:1560:118347)
    at div
    at wl (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:1560:62510)
    at S (https://grafana.ourdomain.dev/public/build/9890.2f086d4a8fdbd47b8d24.js:171:9114)
    at h (https://grafana.ourdomain.dev/public/build/9890.2f086d4a8fdbd47b8d24.js:423:139697)
    at b (https://grafana.ourdomain.dev/public/build/3196.0d4b1a0bf9502490c781.js:176:35829)
    at f (https://grafana.ourdomain.dev/public/build/7836.125f6c2757ee541f83cc.js:24:12176)
    at p (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:12:145768)
    at s (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:12:146277)
    at et (https://grafana.ourdomain.dev/public/build/3196.0d4b1a0bf9502490c781.js:180:515)
    at mf (https://grafana.ourdomain.dev/public/build/355.fc64999f01dbe09dc17a.js:1560:120153)
```

### What did you expect to happen?

The user mapping would be tested

### Did this work before?

Yes

### How do we reproduce it?

1. Go to /admin/authentication/ldap
2. Enter a username
3. Click on Run

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.5
OS: Windows 11
Browser: Edge

### Grafana platform?

Kubernetes

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- adjusts the translations so they don't cause a page crash
- for some reason, when using a `<Tooltip />` inside a `<Trans>` tag, the children passed to `Tooltip` are now wrapped in an array... i guess `<Trans>` does some magic? 🤔 
- this causes [this line](https://github.com/grafana/grafana/blob/ash/support-15278/packages/grafana-ui/src/components/Tooltip/Tooltip.tsx#L99) to blow up since `Tooltip` only ever expects a single child
- this feels like an easy problem for someone else to trip over - suggestions for how to prevent this?
  - maybe a lint rule preventing `<Tooltip>` inside `<Trans>` and documenting what to do instead? 🤔 

**Why do we need this feature?**

- so the LDAP test function doesn't crash the page

**Who is this feature for?**

- everyone using LDAP

**Which issue(s) does this PR fix?**:

For https://github.com/grafana/support-escalations/issues/15278
Fixes https://github.com/grafana/grafana/issues/100030

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/admin/ldap/LdapUserGroups.tsx [hunk 1]
```diff
@@ -29,11 +29,17 @@ export const LdapUserGroups = ({ groups }: Props) => {
...
+                  InfoTooltip: (
+                    <Tooltip content="No matching organizations found">
+                      <Icon name="info-circle" />
+                    </Tooltip>
+                  ),
+                }}
+              >
+                No match {'<InfoTooltip />'}
               </Trans>
             </>
```
Comment (joshhunt) [inline public/app/features/admin/ldap/LdapUserGroups.tsx:44]: I think this should be more like:

```jsx
(
  <>
    <Trans ...>No match</Trans>
    <Tooltip ...><Icon name="info-circle /></Tooltip>
  </>
)
```

**Comment by eledobleefe** [comment]
> this feels like an easy problem for someone else to trip over - suggestions for how to prevent this?
>     maybe a lint rule preventing <Tooltip> inside <Trans> and documenting what to do instead? 🤔

Does this happen when `Trans` wraps another component, or is it just when using `Tooltip`? 🤔

**Comment by ashharrison90** [comment]
> > this feels like an easy problem for someone else to trip over - suggestions for how to prevent this?
> > maybe a lint rule preventing  inside  and documenting what to do instead? 🤔
> 
> Does this happen when `Trans` wraps another component, or is it just when using `Tooltip`? 🤔

it'll happen with any component that expects a single element, so these:
image

**Comment by eledobleefe** [comment]
> > > this feels like an easy problem for someone else to trip over - suggestions for how to prevent this?
> > > maybe a lint rule preventing  inside  and documenting what to do instead? 🤔
> > 
> > 
> > Does this happen when `Trans` wraps another component, or is it just when using `Tooltip`? 🤔
> 
> it'll happen with any component that expects a single element, so these: image

Could we check that? I mean, does the component that wraps `Trans` expect just one child, and if so, does it trigger an error?

**Review by eledobleefe — APPROVED** [review]

**Review by volcanonoodle — APPROVED** [review]
Thank you for fixing this! 🙏

**Review by kalleep — COMMENTED** [review]
Great, this would fix https://github.com/grafana/grafana/issues/100030 right?

**Comment by ashharrison90** [comment]
> #100030

yes - i'll mark it as fixing the issue 👍

**Review by kalleep — APPROVED** [review]
