### PR TITLE
Alerting: Make the folder field read-only on the eval group modal

### LINKED ISSUE #59658: Error changing alert rule folder
**What happened**:

Trying to move some alert rules to a different folder before deleting old folder. Got error.

**What you expected to happen**:

Rules moved to the specified folder.

**How to reproduce it (as minimally and precisely as possible)**:

* Dashboards -> Add new folder: create 2 folders "Foo" and "Bar"
* Alerts -> Alerting: Create new "Rule1" in folder "Foo"
* Alerts -> Alerting: Create new "Rule2" in folder "Foo"
* Alerts -> Alerting: Click edit rule group icon for "Foo > Rule1",  Change folder name to "Bar", click save. Works OK!
* Alerts -> Alerting: Click edit rule group icon for "Foo > Rule2",  Change folder name to "Bar", click save. Fails with error:
`Failed to update namespace / group: Namespace "Bar" already exists.` 
or `Failed to update namespace / group: folder not found` if not pre-created folder.

**Anything else we need to know?**:

Just found a workaround, well, better way of doing it, is to edit the actual rule and change the folder in the dropdown, rather than edit the rule group.

**Environment**:
- Grafana version: 9.3.0 and 9.4-pre
- Data source type & version: Graphite
- OS Grafana is installed on: Docker
- User OS & Browser: Linux, FF
- Grafana plugins: Default
- Others:

### PR DESCRIPTION
**Pull request by konrad147**
**What is this feature?**
This PR makes the folder input read-only and adds a `Go to folder` button on the Eval group modal

**Why do we need this feature?**
We want to alleviate confusion about what you can edit on the Eval group modal

Fixes #59658 

**DEMO**
image

### CODE REVIEW

File: public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx [hunk 1]
```diff
@@ -315,44 +287,55 @@ export function EditCloudGroupModal(props: ModalProps): React.ReactElement {
...
+                  id="namespaceName"
+                  readOnly={intervalEditOnly || isGrafanaManagedGroup}
+                  {...register('namespaceName', {
+                    required: 'Namespace name is required.',
+                  })}
+                  className={styles.formInput}
+                />
+                {isGrafanaManagedGroup && (
+                  <LinkButton
+                    href={props.folderUrl}
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx:331]: Should we render this component if `folderUrl` is falsey? I think it doesn't make a whole lot of sense to show this button if clicking it doesn't take you anywhere :)

File: public/app/features/alerting/unified/components/rules/RulesGroup.tsx [hunk 2]
```diff
@@ -238,10 +238,10 @@ export const RulesGroup: FC<Props> = React.memo(({ group, namespace, expandAll,
       )}
       {isEditingGroup && (
         <EditCloudGroupModal
-          groupInterval={group.interval ?? ''}
-          nameSpaceAndGroup={{ group: group, namespace: namespace }}
-          sourceName={getRulesSourceName(namespace.rulesSource)}
+          namespace={namespace}
+          group={group}
           onClose={() => closeEditModal()}
+          folderUrl={folder?.canEdit ? makeFolderSettingsLink(folder) : undefined}
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rules/RulesGroup.tsx:244]: blocking: When testing this it seems like the `folderUrl` is empty when editing an evaluation group from the alert creation flow – is there anything more we need to do to have the correct folder URL?

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 3]
```diff
@@ -163,30 +155,36 @@ function FolderGroupAndEvaluationInterval({
...
+      {folderName && isEditingGroup && (
         <EditCloudGroupModal
-          groupInterval={evaluateEvery}
-          nameSpaceAndGroup={{ namespace: folder?.title ?? '', group: group }}
-          sourceName={GRAFANA_RULES_SOURCE_NAME}
+          namespace={existingNamespace ?? emptyNamespace}
+          group={existingGroup ?? emptyGroup}
           onClose={() => closeEditGroupModal()}
-          folderAndGroupReadOnly
+          intervalEditOnly
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:175]: nit: not a big fan of this but it makes sense for now – perhaps if we start adding more disabled fields we can introduce an array of field names that should be disabled

File: public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx [hunk 4]
```diff
@@ -275,9 +249,7 @@ export function EditCloudGroupModal(props: ModalProps): React.ReactElement {
     ? 'Folder name can be updated in folder view'
     : 'Name space can be updated folder view';
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx:250]: nit: This sentence is weird, should it be

`namespace can be updated on the folder view` and what exactly is the folder view?

**Review by gillesdemey — CHANGES_REQUESTED** [review]

File: public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx (hunk 1 above)
Comment (konrad147) [reply public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx:331]: We shouldn't! Good catch

File: public/app/features/alerting/unified/components/rules/RulesGroup.tsx (hunk 2 above)
Comment (konrad147) [reply public/app/features/alerting/unified/components/rules/RulesGroup.tsx:244]: The folder link should only be available when you edit a group from the alert list view.
Evaluation group editing on the alert creation flow should only allow editing the interval, so the missing folder link is a deliberate thing there (we left eval group editing in this place as fallback compatibility. I think we need to think about eval group experience in the revamped alert creation flow)

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx (hunk 3 above)
Comment (konrad147) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:175]: I'm not a fan either :) This is due to using the same modal in two places. Perhaps the new rule creation flow won't use this modal so it would be used only once on the alert list view

File: public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx (hunk 4 above)
Comment (konrad147) [reply public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx:250]: I'll remove this. The folder input has a link where you can edit, and the namespace has a description below the label, which should be enough

**Review by gillesdemey — APPROVED** [review]
LGTM 🚀
