### PR TITLE
Transformer: Config from Query: set threshold colours

### LINKED ISSUE #45803: Transforms: Config from query results, add support for more thresholds
**Overview**
Hi, I am using SiteWise as a data source in AWS Managed Grafana, but it should apply to any other data source or Grafana version. 

I am trying to set visible thresholds on a gauge and graph based on a query, meaning that Grafana reads a specific measurement from AWS SiteWise, as it would read a value from Influx for example, and I would like to set thresholds based on this value. As it came to my attention, you cannot reference a variable in the thresholds menu. Then I came across the "Config from query result" transformation that let me set one threshold, but then I was not able to select another one, because it was unavailable.

My questions are:
Is this a bug that you cannot select more than one threshold from a query, or is it just supposed to be one? 
If it is just supposed to be one, is there another way how to show thresholds based on a query?

**What happened**:
I was unable to make another "Config from query result" transformation to achieve having multiple thresholds based on queries.

**What you expected to happen**:
Being able to have multiple thresholds by using this transformation method.

**How to reproduce it (as minimally and precisely as possible)**:
Have three different measurements, where two out of the three are the upper and lower thresholds and the third one is the Actual value. Attempt to set thresholds based on the two queries.

**Environment**:
- Grafana version: 8.2.5
- Data source type & version: AWS IoT SiteWise
- OS Grafana is installed on: AWS Managed Grafana
- User OS & Browser: Windows 11, Brave (Chrome)
- Grafana plugins: None, only ones included with AWS Managed Grafana
- Others: 

**Screenshot**
image

### LINKED ISSUE #56425: Barchart: Can't change dynamic threshold colors with 'config from query results'
**What happened**:
I set the dynamic threshold with 'Config from query results' transformation and it's working fine until this part, but I can't change the bar colors with this configuration. Already tried many ways with no success...

image

**What you expected to happen**:
Could be able to change/reverse colors in bar charts and other visualizations. This could be very useful in many occasions.

**How to reproduce it (as minimally and precisely as possible)**:
Just set a dynamic threshold coming from a query result with a simple dataset.

**Environment**:
- Grafana version: 9.1.6
- Data source type & version: PostgreSQL
- OS Grafana is installed on: Windows
- User OS & Browser: Edge

### PR DESCRIPTION
**Pull request by LarsStegman**
**What is this feature?**

Add possibility to set the color for each threshold when using the `ConfigFromQuery` transformer.

**Why do we need this feature?**

Right now, if multiple thresholds are added, they are all colored red.

**Who is this feature for?**

Anyone who wants to set thresholds from a query

**Which issue(s) does this PR fix?**:

Fixes #56425 

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

image

Dashboard to test with: https://gist.github.com/LarsStegman/f35402e5b215bb597d8bf6e043c04e61

### CODE REVIEW

**Comment by LarsStegman** [comment]
@baldm0mma I am not sure if I can do something about the failing checks, do you know:?

**Comment by baldm0mma** [comment]
> @baldm0mma I am not sure if I can do something about the failing checks, do you know:?

Lemme take a look!

**Comment by torkelo** [comment]
The color picker is missing a field label land some spacing

**Review by torkelo — COMMENTED** [review]
let me review this next week

**Comment by LarsStegman** [comment]
> The color picker is missing a field label land some spacing

@torkelo good point, is this better? I reused the threshold editor input concept.

image

**Review by torkelo — COMMENTED** [review]
Missing some unit tests, but otherwise I think this looks close

**Comment by LarsStegman** [comment]
@torkelo Added some unit tests. I don't know how to create a test to select a color which will trigger the on change. Any idea? Is it worth it to test?

**Comment by LarsStegman** [comment]
@torkelo are these unit tests enough?

**Comment by LarsStegman** [comment]
@torkelo @baldm0mma do you need more information or work from me to get this PR approved?

**Comment by baldm0mma** [comment]
@LarsStegman this looks great! I'm going to approve, but would love to hear @torkelo thoughts before merging.

**Review by baldm0mma — DISMISSED** [review]

**Comment by baldm0mma** [comment]
> @LarsStegman this looks great! ~~I'm going to approve,~~ but would love to hear @torkelo thoughts before merging. I don't love that the "Additional settings" heading will always show, but I really like the enhancement!

After doing more thorough testing, I do think having the "additional settings" appear the way it does is pretty problematic.

Screenshot 2024-03-18 at 5 23 35 PM

**Comment by codeincarnate** [comment]
I'd like to take a look at this one too 😄. I'll go through this one tomorrow

**Comment by LarsStegman** [comment]
> After doing more thorough testing, I do think having the "additional settings" appear the way it does is pretty problematic.

Yeah, I didn't really like that either, but I couldn't figure out a nice way to make it disappear and make the code nice. I'll spend some more time on fixing that.

**Comment by LarsStegman** [comment]
I think this should solve it. I don't like the double source of truth for whether a certain handler creates an interface element, but I couldn't find another way.

File: public/app/features/transformers/fieldToConfigMapping/FieldToConfigMappingEditor.tsx [hunk 1]
```diff
@@ -60,13 +70,26 @@ export function FieldToConfigMappingEditor({ frame, mappings, onChange, withRedu
     }
   };
 
+  const onChangeHandlerArguments = (row: FieldToConfigRowViewModel, handlerArguments: HandlerArguments) => {
+    const existingIdx = mappings.findIndex((x) => x.fieldName === row.fieldName);
```
Comment (codeincarnate) [inline public/app/features/transformers/fieldToConfigMapping/FieldToConfigMappingEditor.tsx:74]: Since it's not reused this could can be placed directly in the _if_ statement below.

**Review by codeincarnate — APPROVED** [review]
Looks pretty good overall! It's an interesting take on tackling this. We may want to re-evaluate at some point. I can definitely see a case where it would make sense to map thresholds not from multiple fields but from multiple values of a single field.

As we like to say though, don't let perfection get in the way of progress! I'll let @baldm0mma comment on the additional settings stuff but otherwise I think it's solid 😄

**Comment by LarsStegman** [comment]
@baldm0mma I made the change you requested.

**Comment by baldm0mma** [comment]
> @baldm0mma I made the change you requested.

Great! I'll take another look. Can you also share the dashboard JSON you're using to test this in the description at the top for others to test it also?

**Comment by baldm0mma** [comment]
@LarsStegman Also looks like this is breaking a test in the `public/app/features/transformers/fieldToConfigMapping/FieldToConfigMappingEditor.test.tsx` suite. You can see it [here](https://drone.grafana.net/grafana/grafana/167377/1/6) on line 1460.

Also, in case you cannot view the drone build, here's the error:
```
Summary of all failing tests
FAIL public/app/features/transformers/fieldToConfigMapping/FieldToConfigMappingEditor.test.tsx
  ● FieldToConfigMappingEditor › Shows additional settings

    Expected test not to call console.error().

    If the error is expected, test for it explicitly by mocking it out using jest.spyOn(console, 'error').mockImplementation() and test that the warning occurs.

    Warning: validateDOMNesting(...): <div> cannot appear as a child of <tr>.
        at div

      33 |
      34 | export const Input = React.forwardRef<HTMLInputElement, Props>((props, ref) => {
    > 35 |   const { className, addonAfter, addonBefore, prefix, suffix, invalid, loading, width = 0, ...restProps } = props;
         |           ^
      36 |   /**
      37 |    * Prefix & suffix are positioned absolutely within inputWrapper. We use client rects below to apply correct padding to the input
      38 |    * when prefix/suffix is larger than default (28px = 16px(icon) + 12px(left/right paddings)).

      at packages/grafana-ui/src/components/Input/Input.tsx:35:11
      at FieldConfigMappingHandlerArgumentsEditor (public/app/features/transformers/fieldToConfigMapping/FieldConfigMappingHandlerArgumentsEditor.tsx:22:60)
          at tr
          at tbody
          at table
      at FieldToConfigMappingEditor (public/app/features/transformers/fieldToConfigMapping/FieldToConfigMappingEditor.tsx:30:46)
          at console.captureMessage [as error]...
```

**Comment by LarsStegman** [comment]
> @LarsStegman Also looks like this is breaking a test in the `public/app/features/transformers/fieldToConfigMapping/FieldToConfigMappingEditor.test.tsx` suite. You can see it [here](https://drone.grafana.net/grafana/grafana/167377/1/6) on line 1460.

@baldm0mma Took me a while to figure what was happening. I'd forgotten to put the content in a `td` tag, so the warning was correct 😅

**Comment by LarsStegman** [comment]
> > @baldm0mma I made the change you requested.
> Can you also share the dashboard JSON you're using to test this in the description at the top for others to test it also?

**Review by baldm0mma — APPROVED** [review]
LGTM! Thanks for the contribution!

**Comment by leeoniya** [comment]
i would say this should be in a changelog, since it's a long-requested feature / papercut.

**Comment by baldm0mma** [comment]
@leeoniya good point! I'll get something in the What's New!

**Comment by ganeshvrao** [comment]
@baldm0mma in which version of grafana we will see this feature available? Also, when will it be released?
