### PR TITLE
Geomap: Fix runtime errors in StyleEditor

### LINKED ISSUE #42219: 8.3.0-beta1 geomap edit error
**What happened**: After update to 8.3.0-beta1 geomap still shows data, one problem is that color of dots changed to green from previous set color, bigger problem is that edit is not possible anymore, it shows below error when going to edit mode

image

**What you expected to happen**: /

**How to reproduce it (as minimally and precisely as possible)**: /

**Anything else we need to know?**: /

**Environment**:
- Grafana version: 8.3.0-beta1
- Data source type & version: /
- OS Grafana is installed on: Debian 9
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: /
- Others: /

### PR DESCRIPTION
**Pull request by nikki-kiga**
**What this PR does / why we need it**:
- add nullish checks to prevent runtime errors

**Which issue(s) this PR fixes**:
Fixes #42219 introduced during StyleEditor refactor work in #41842 #41846 #41926 and #41992

**Special notes for your reviewer**:
@nmarrs feel free to incorporate if any of this overlaps with the layer editor refactor work for canvas/geomap

### CODE REVIEW

File: public/app/plugins/panel/geomap/layers/data/StyleEditor.tsx [hunk 1]
```diff
@@ -108,7 +108,7 @@ export const StyleEditor: FC<StandardEditorProps<StyleConfig, StyleEditorOptions
             <InlineFieldRow>
               <InlineField label={'Symbol'}>
                 <ResourceDimensionEditor
-                  value={value.symbol ?? defaultStyleConfig.symbol}
+                  value={value?.symbol ?? defaultStyleConfig.symbol}
```
Comment (nmarrs) [inline public/app/plugins/panel/geomap/layers/data/StyleEditor.tsx:111]: It's a little strange to me that `value` prop would ever be undefined, not a big deal for getting these fixes in but I will investigate this as part of my refactor changes

**Review by nmarrs — APPROVED** [review]
Looks like this should address current reported runtime errors!

File: public/app/plugins/panel/geomap/layers/data/StyleEditor.tsx (hunk 1 above)
Comment (nikki-kiga) [reply public/app/plugins/panel/geomap/layers/data/StyleEditor.tsx:111]: Yeah it's showing up in older panels so I think it's something to do with the shape of the config changing and/or when the value sets text, size, symbol etc.

We could also probably address this by handling with a migration case in the geomap migrations but it seemed like we were trying to minimize the number of migration cases were checking for.
