### PR TITLE
Prometheus: Fix applying of ad-hoc variables after backend migration

### LINKED ISSUE #41280: Prometheus: AdHoc variable filter does not seem to be applied
There was maybe related issue that was fixed here https://github.com/grafana/grafana/pull/41232 but seems like prometheus case was broken even before the DatasourceRef change.

Basically if you create an AdHoc variable for prometheus and the set some filters they should be added to the query in dashboards if they use the same data source. The filter though is not added to the query at all.

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
During Prometheus backend migration I have forgotten to add adding of ad-hoc variables. I incorrectly thought that they were added in applyTemplateVariable step, but they weren't added. This PR fixes this and adds test. 

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/41280

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/datasource.ts [hunk 1]
```diff
@@ -909,6 +901,20 @@ export class PrometheusDatasource extends DataSourceWithBackend<PromQuery, PromO
     return getOriginalMetricName(labelData);
   }
 
+  enhanceExprWithAdHocFilters(expr: string) {
```
Comment (gabor) [inline public/app/plugins/datasource/prometheus/datasource.ts:904]: nitpick: i think this function could be simplified to be like this:
```javascript
  enhanceExprWithAdHocFilters(expr: string) {
    const adhocFilters = this.templateSrv.getAdhocFilters(this.name);
    return adhocFilters.reduce(...
     ...
     ...
    }, expr);
  }
```

**Review by gabor — APPROVED** [review]
LGTM!

i left a nitpick comment, but it's not that important.

File: public/app/plugins/datasource/prometheus/datasource.ts (hunk 1 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/prometheus/datasource.ts:904]: 👍 I merged this, we can always clean this up if we want to.
