### PR TITLE
Loki: Support for template variable queries

### LINKED ISSUE #19826: Loki template variable query not working
**What happened**:

When using a Loki datasource for a template variable query I'm getting an error. 

eg: `label_names()` or `label_values(level)`.

**What you expected to happen**:

Loki support label names and values queries so we should be able to support Loki datasource for template variable query.

see :
- https://github.com/grafana/loki/blob/master/docs/api.md#get-lokiapiv1label
- https://github.com/grafana/loki/blob/master/docs/api.md#get-lokiapiv1labelnamevalues

**How to reproduce it (as minimally and precisely as possible)**:
image

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.5.0-pre (14cf2a3)
- Data source type & version: Loki

/cc @aocenas @davkal

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
`metricFindQuery` is optional method that was not implemented for Loki. This PR implements `metricFindQuery` method for Loki. Loki datasource is now supporting `label names` and `label values` template variable queries for Loki versions v0 and v1. Tests coverage for implemented functionality added as well. 

image

image

**Which issue(s) this PR fixes**:
Fixes #19826

### CODE REVIEW

File: public/app/plugins/datasource/loki/metric_find_query.ts [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+    return this.datasource.metadataRequest(url).then((result: any) => {
+      return map(result.data.data, value => {
+        return { text: value };
+      });
+    });
+  }
+
+  labelValuesQuery(label: string) {
+    let url: string;
+    url = '/loki/api/v1/label/' + label + '/values';
```
Comment (kaydelaney) [inline public/app/plugins/datasource/loki/metric_find_query.ts]: Nit: Could use template strings
```suggestion
    url = `/loki/api/v1/label/${label}/values`;
```

**Comment by kaydelaney** [comment]
Committed some small style and readability changes but otherwise looks good! Might want to check if this PR works with older versions of loki as well (there are several docker images in devenv)

File: public/app/plugins/datasource/loki/datasource.test.ts [hunk 2]
```diff
@@ -357,6 +357,43 @@ describe('LokiDatasource', () => {
...
+      expect(res.length).toBe(2);
+      expect(res[0].text).toEqual('value1');
+      expect(res[1].text).toEqual('value2');
+    });
+
+    it('should return label values', async () => {
+      const query = 'label_values(name)';
+      const res = await ds.metricFindQuery(query);
+      expect(res.length).toBe(2);
+      expect(res[0].text).toEqual('value1');
```
Comment (aocenas) [inline public/app/plugins/datasource/loki/datasource.test.ts]: Having the same values independent of the query looks a bit weird and does not tell you if you got the correct behaviour as it could actually call the wrong endpoint. We could mock `datasource.metadataRequest` and return different values depending on the url. There is actually already a mock for that in `/loki/mocks.ts`.

File: public/app/plugins/datasource/loki/datasource.ts [hunk 3]
```diff
@@ -396,6 +397,15 @@ export class LokiDatasource extends DataSourceApi<LokiQuery, LokiOptions> {
     };
   }
 
+  metricFindQuery(query: string) {
+    if (!query) {
+      return Promise.resolve([]);
+    }
+    const interpolated = this.templateSrv.replace(query, {}, this.interpolateQueryExpr);
+    const metricFindQuery = new LokiMetricFindQuery(this, interpolated);
+    return metricFindQuery.process();
```
Comment (aocenas) [inline public/app/plugins/datasource/loki/datasource.ts]: Why is the `LokiMetricFindQuery` done as class? The statefulness does not seem to be useful  here. Seems like we could just have `processMetricFindQuery(this, interpolated)` and make it a simple function.

**Review by hugohaggmark — COMMENTED** [review]
Looks good but I agree with @aocenas comments

File: public/app/plugins/datasource/loki/metric_find_query.test.ts [hunk 4]
```diff
@@ -0,0 +1,45 @@
+import { processMetricFindQuery } from './metric_find_query';
+import { makeMockLokiDatasource } from './mocks';
+import LokiDatasource from './datasource';
+
+const mocks = makeMocks();
+
+describe('processMetricFindQuery', () => {
+  mocks.forEach((mock, index) => {
```
Comment (hugohaggmark) [inline public/app/plugins/datasource/loki/metric_find_query.test.ts]: Nitpick: there is an `it.each` that I think you could use here. Just learned about it last week.

File: public/app/plugins/datasource/loki/metric_find_query.ts [hunk 5]
```diff
@@ -0,0 +1,35 @@
+import { LokiDatasource, LOKI_ENDPOINT, LEGACY_LOKI_ENDPOINT } from './datasource';
+
+export async function processMetricFindQuery(datasource: LokiDatasource, query: string) {
```
Comment (hugohaggmark) [inline public/app/plugins/datasource/loki/metric_find_query.ts]: Just out of curiosity why is this not in the datasource? Why does it need to be in a separate file?

File: public/app/plugins/datasource/loki/mocks.ts [hunk 6]
```diff
@@ -1,17 +1,23 @@
...
 import { LokiOptions } from './types';
 import { createDatasourceSettings } from '../../../features/datasources/mocks';
 
 export function makeMockLokiDatasource(labelsAndValues: { [label: string]: string[] }): LokiDatasource {
+  const legacyLokiLabelsAndValuesEndpointRegex = /^\/api\/prom\/label\/(\w*)\/values/;
+  const lokiLabelsAndValuesEndpointRegex = /^\/loki\/api\/v1\/label\/(\w*)\/values/;
+
+  const legacyLokiLabelsEndpoint = `${LEGACY_LOKI_ENDPOINT}/label`;
+  const lokiLabelsEndpoint = `${LOKI_ENDPOINT}/label`;
+
```
Comment (hugohaggmark) [inline public/app/plugins/datasource/loki/mocks.ts]: Nitpick: this is "just" testcode but it starting to get a bit complex maybe we should start thinking about refactoring makeMockLokiDatasource in future PRs.

**Review by hugohaggmark — APPROVED** [review]
Looks good, and I left some small comments for you to consider. Haven't tested it locally though.

File: public/app/plugins/datasource/loki/metric_find_query.test.ts (hunk 4 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/metric_find_query.test.ts]: Thanks Hugo, I'll check it out!

File: public/app/plugins/datasource/loki/metric_find_query.ts (hunk 5 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/metric_find_query.ts]: Good question. I was following Prometheus file structure, where it was implemented in its own file. However, in Prometheus we are creating class, which is not a case with Loki. So after thinking more about this, and after looking at more examples how different datasources implement `metricFindQuery`, I have decided to move it directly to datasource, as is doesn't have valid reason to be outside the datasource. I have also moved tests to `datasource.test.ts`.

**Comment by davkal** [comment]
This should be documented @ivanahuckova
