### PR TITLE
RBAC: Check forceLogin inside CanAdminPlugins

### LINKED ISSUE #88837: Plugin Management Pages: Forced login does not work when anonymous access is enabled
### What happened?

When anonymous access is enabled:

```
[auth.anonymous]
enabled = 1
org_role = Admin
```

any of the pages behind `CanAdminPlugins` [middleware](https://github.com/grafana/grafana/blob/main/pkg/middleware/auth.go#L94) ignore the `?forcedLogin=1` flag and do not redirect to the login page and the user stays on the same page.

### What did you expect to happen?

Being redirected to the login page as it is the case on other pages

### Did this work before?

Yeah probably before https://github.com/grafana/grafana/pull/76321

### How do we reproduce it?

1. Do not login / or if logged in -> logout.

2. Enable anonymous access:
```
[auth.anonymous]
enabled = 1
org_role = Admin
```

3. Visit your instance plugin management pages - for example this one `YOUR-INSTANCE/plugins/grafana-azure-data-explorer-datasource` and click on the Login link at the top.

SCR-20240606-mlws

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: latest
OS:
Browser:

### Grafana platform?

Other

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by s4kh**
**What is this feature?**

Redirect to login page when `forceLogin=true` is in the param for endpoints wrapped `CanAdminPlugins` middleware.

**Why do we need this feature?**

Bug fix.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/88837

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] `CanAdminPlugins` redirect to Home page when user does not satisfy the roles and permissions.

### CODE REVIEW

File: pkg/middleware/auth_test.go [hunk 1]
```diff
@@ -353,3 +356,87 @@ func TestRemoveForceLoginparams(t *testing.T) {
...
+	type testCase struct {
+		desc       string
+		url        string
+		isSignedIn bool
+		orgRole    org.RoleType
+		expCode    int
+		expReached bool
+	}
+
+	ac := &actest.FakeAccessControl{}
```
Comment (s4kh) [inline pkg/middleware/auth_test.go:370]: Is there a way we can use the actual implementation?
tried `acimpl.ProvideAccessControlTest()` but cyclic import is not allowed in test.

File: pkg/middleware/auth.go [hunk 2]
```diff
@@ -98,6 +98,10 @@ func CanAdminPlugins(cfg *setting.Cfg, accessControl ac.AccessControl) func(c *c
 			accessForbidden(c)
 			return
 		}
+		if c.AllowAnonymous && !c.IsSignedIn && shouldForceLogin(c) {
```
Comment (andresmgot) [inline pkg/middleware/auth.go:101]: nit: you can omit `c.AllowAnonymous`, if the user is not logged in and anonymous login is not enabled this code won't be reached and it will be redirected before.

File: pkg/middleware/auth_test.go (hunk 1 above)
Comment (andresmgot) [reply pkg/middleware/auth_test.go:370]: you may try to change this file package name to `middleware_test`, not sure if you won't get a cyclic dependency that way but in any case, I think you are good with the fake implementation.

**Review by andresmgot — APPROVED** [review]
LGTM, just one minor comment
