### PR TITLE
AzureAD OAuth: Add optional strict parsing of role_attribute_path

### LINKED ISSUE #22741: Azure AD OAuth2 authentication shouldn't default to Viewer and should throw Unauthorized error instead
**What happened**:
Following this https://grafana.com/docs/grafana/latest/auth/azuread/#enable-azure-ad-oauth-in-grafana and according to https://github.com/grafana/grafana/issues/21366#issuecomment-577026143 , if the users aren't assigned any app roles, they shouldn't be allowed to login.

However, in Azure AD, if the user has no app role, `Default Access` role will be assigned to them, and a token will be returned, instead of no token.

And on Grafana side `pkg\login\social\azuread_oauth.go`,  `extractRole()` default to return `Viewer` role.

**What you expected to happen**:
Because, Azure AD token has a group limit of 200, app role is suggested as a consistent way to authorize to certain groups of users. So if users have no assigned app role, `Unauthorized` error should be thrown instead

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:  v6.7.0-274a4322pre (5ad8a9722e)
- Data source type & version:
- OS Grafana is installed on: Windows
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by sivamu**
**What this PR does / why we need it**:
Using Azure AD, it is not possible to deny users access to Grafana outside of setting `allowed_groups` and `groupMembershipClaims`. 

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/22741
References https://github.com/grafana/grafana/issues/40186

**Special notes for your reviewer**:
There has been a lot of discussion in restricting access for users in https://github.com/grafana/grafana/issues/23218 but the problem is that the solution was not implemented for Azure AD. There are several issues filed, as I tagged in the PR fixes section above, that needs this solution implemented for the Azure AD scenario as well. 

This PR is also based on the changes made in https://github.com/grafana/grafana/pull/28021

### CODE REVIEW

**Comment by kyschouv** [comment]
@kminehart @ying-jeanne could this get a review so it can make it into an upcoming build? We're still blocked on #22741 for some of our work.

**Comment by kminehart** [comment]
Apologies, I was away for all of December and didn't see this land in my inbox until your recent ping.

Could you please resolve the conflicts and I'll get this reviewed right away?

In the meantime I'll see if there are any issues that stand out.

File: pkg/login/social/azuread_oauth.go [hunk 1]
```diff
@@ -115,7 +119,7 @@ func extractRole(claims azureClaims, autoAssignRole string) models.RoleType {
 		}
 	}
 
-	return models.ROLE_VIEWER
+	return models.RoleType("")
```
Comment (kminehart) [inline pkg/login/social/azuread_oauth.go:122]: This change feels a little fishy to me but I'm not super familiar with this area of the codebase.

If I previously had a setup where users were automatically being assigned the viewer role and I was fine with that, will that continue to work here?

I see an old test that is still passing,

```
{
			name: "Email in email claim",
			claims: &azureClaims{
				Email:             "me@example.com",
				PreferredUsername: "",
				Roles:             []string{},
				Name:              "My Name",
				ID:                "1234",
			},
			fields: fields{
				autoAssignOrgRole: "Viewer",
			},
			want: &BasicUserInfo{
				Id:      "1234",
				Name:    "My Name",
				Email:   "me@example.com",
				Login:   "me@example.com",
				Company: "",
				Role:    "Viewer",
				Groups:  []string{},
			},
		},
```

Would this have previously passed even without the `autoAssignOrgRole: "Viewer"` setting, and will that behavior change?

Comment (sivamu) [reply pkg/login/social/azuread_oauth.go:142]: No it wouldn't work. That's the main reason behind this PR, is that I was hoping to address the situation in #22741 where a user with no role assigned in AAD shouldn't be authorized to access Grafana, instead of being granted the viewer role automatically. 

To answer the second question, yes the behavior would change. It would have passed without the setting but with the proposed change in the PR, it wouldn't.

Comment (kminehart) [reply pkg/login/social/azuread_oauth.go:142]: > where a user with no role assigned in AAD shouldn't be authorized to access Grafana, instead of being granted the viewer role automatically

This should only be true when the new strict mode flag is enabled though, correct? If it is not enabled then I believe the previous behavior should stay the same. I agree with your assessment, it should not be that way, but we also should not break existing behavior.

I'll defer to @vtorosyan on this, but I think that we would be prefer a warning log if they reach this point where the user is being assigned the default role of VIEWER and strict mode is disabled

Comment (sivamu) [reply pkg/login/social/azuread_oauth.go:142]: Now that I think about it, the strict mode flag doesn't really do anything in the azure_oauth code. In the [extractRole](https://github.com/grafana/grafana/blob/main/pkg/login/social/azuread_oauth.go#L126-L136) method, we only return roles that match admin, viewer or editor. The strict mode check pretty much does the same thing. The code I based this off in `okta_oauth.go` needed the strict mode since its [`extractRole` method](https://github.com/grafana/grafana/blob/main/pkg/login/social/okta_oauth.go#L123-L133) grabs any role from the claims token.

That said, the PR change will just be changing the default role from Viewer to nothing. Let's wait on their response to determine the final direction.

Comment (alexanderzobnin) [reply pkg/login/social/azuread_oauth.go:142]: Yes, `extractRole()` function returns Viewer role by defaut, so it's always valid. I think code that checks strict option should be in that function. Also, pay attention to the `auto_assign_org_role` (`autoAssignRole` inside `extractRole()`) config that allows to return another role by default.

**Review by alexanderzobnin — DISMISSED** [review]

File: pkg/login/social/azuread_oauth.go (hunk 1 above)
Comment (sivamu) [reply pkg/login/social/azuread_oauth.go:142]: I'm not really sure what to do here. If we want the `extractRole` to be always valid, I don't see a way to deny a user with no role assigned in AAD, regardless of strict mode. The [only workaround](https://github.com/grafana/grafana/issues/22741#issuecomment-598233882) for this issue doesn't work in [all cases ](https://github.com/grafana/grafana/issues/22741#issuecomment-598751235). Any suggestions on how to handle this situation, without modifying the return of default role?

**Comment by kyschouv** [comment]
This seems to have stalled again. What's the current status? We're eagerly awaiting this so we don't have our entire tenant assigned Viewer permissions.

**Comment by sivamu** [comment]
@kyschouv I've asked for a follow up in my [most recent comment](https://github.com/grafana/grafana/pull/42157#discussion_r792321222). @alexanderzobnin thoughts on how to approach this problem going forward?

**Comment by kyschouv** [comment]
@alexanderzobnin any chance we could figure this out? Or maybe @kminehart?

File: pkg/login/social/azuread_oauth.go (hunk 1 above)
Comment (sakjur) [reply pkg/login/social/azuread_oauth.go:142]:
```
func extractRole(claims azureClaims, autoAssignRole string, strictMode bool) models.RoleType {
	if len(claims.Roles) == 0 {
		return models.RoleType(autoAssignRole)
	}
	roleOrder := []models.RoleType{
		models.ROLE_ADMIN,
		models.ROLE_EDITOR,
		models.ROLE_VIEWER,
	}
	for _, role := range roleOrder {
		if found := hasRole(claims.Roles, role); found {
			return role
 		}
 	}

 	if strictMode {
 	 return models.RoleType("")
 	}
 	return models.ROLE_VIEWER
}
```

(or better yet, return an `error` rather than relying on `""` being an invalid role)?

We're _very_ unlikely to merge a change to the default behavior, that would be a breaking change ("Click Manifest, then define the required Application Role values for Grafana: Viewer, Editor, or Admin. If not defined, all users will have the Viewer role." from the docs implies that we _at least_ would need to add an exception for `""->Viewer`).

**Comment by sakjur** [comment]
I have never used AzureAD, so my understanding might be at fault here, but afaict, merging this as-is would risk breaking things for users depending on (and happy with) the current behavior.

I'd suggest passing the configuration of strict mode down into extract role and fail there iff strict mode is defined and the role isn't a permitted organizational role. It might not be ideal, but the risk of randomly breaking existing configurations is low and you get the behavior you want (though not by default— we'd need a major authN refactoring to be able to make improvements like that without breaking backwards compatibility 😢).

**Comment by sakjur** [comment]
This (or an accompanying) PR will also need to update [docs/sources/auth/azuread.md](https://github.com/grafana/grafana/blob/main/docs/sources/auth/azuread.md), [conf/sample.ini](https://github.com/grafana/grafana/blob/main/conf/sample.ini), and [conf/defaults.ini](https://github.com/grafana/grafana/blob/main/conf/defaults.ini) (assuming that a new configuration option is introduced).

File: pkg/login/social/azuread_oauth.go (hunk 1 above)
Comment (kyschouv) [reply pkg/login/social/azuread_oauth.go:142]: @sivamu Is this (and the below feedback) enough to get this working and merged?

**Comment by sivamu** [comment]
Thanks for the suggestion @sakjur, I've made some updates to the PR that doesn't change the default behavior.

**Comment by kyschouv** [comment]
@alexanderzobnin do these changes work? Or maybe @kminehart? It would be nice to get this merged and into the next release =).

**Comment by kminehart** [comment]
I think it looks good but I would really like to get an approval from one of the other team members since they'll likely be more active in this part of the repository.

File: pkg/login/social/azuread_oauth.go [hunk 2]
```diff
@@ -69,7 +70,7 @@ func (s *SocialAzureAD) UserInfo(client *http.Client, token *oauth2.Token) (*Bas
 		return nil, errors.New("error getting user info: no email found in access token")
 	}
 
-	role := extractRole(claims, s.autoAssignOrgRole)
+	role := extractRole(claims, s.autoAssignOrgRole, s.roleAttributeStrict)
```
Comment (sakjur) [inline pkg/login/social/azuread_oauth.go:73]: You should either check if the role is empty and return an error here or return an error from the `extractRole` function and elevate that up if it's not nil.

**Review by sakjur — COMMENTED** [review]
I compared this to generic OAuth and Okta, both of those return an error early if the role isn't valid for strict parsing, we should follow that behavior here.

File: pkg/login/social/azuread_oauth.go (hunk 2 above)
Comment (kyschouv) [reply pkg/login/social/azuread_oauth.go:73]: @sivamu Will this be an easy change?

@sakjur / @kminehart is there someone in particular who should also review this?

Comment (sivamu) [reply pkg/login/social/azuread_oauth.go:73]: Added the change, apologies for the delay

Comment (sakjur) [reply pkg/login/social/azuread_oauth.go:73]: 🙏 Thank you, I'll take another look

**Review by sakjur — APPROVED** [review]
:+1: LGTM, can you merge in latest main? The linter/tests are complaining.

**Comment by sivamu** [comment]
Can't resolve the last two checks, about the milestone and backport. Could someone please help with that?
