### PR TITLE
Prometheus: Add `virtualized` prop to improve memory usage listing Metrics

### LINKED ISSUE #52171: Grafana Query Builder hangs loading K6 metrics from Prometheus
**What happened**:
I set up a Grafana Cloud stack. As part of this stack there were a Prometheus instance and and a Grafana instance.
I followed[ K6's guide](https://k6.io/docs/results-visualization/grafana-cloud/#set-up-grafana-cloud-prometheus) for setting up Grafana Cloud's Prometheus for receiving metrics from `k6`.  Please notice this is not about using [k6 Cloud App](https://grafana.com/grafana/plugins/grafana-k6-app/)  but about sending `k6` metrics to prometheus.

I then used Grafana explorer using the Prometheus instance as a data source but the query builder hung when retrieving the metrics:
Screenshot from 2022-07-11 16-29-22

However, when I then checked in the Cardinality Management it showed the metrics from k6:

Screenshot from 2022-07-07 12-51-56

Interestingly, the Metrics explorer did work and could successfully retrieve the metrics, as shown bellow. 
Screenshot from 2022-07-11 15-26-32

Therefore, it seams the setup for `k6` is correct and it is working, the problem seam related only with the query builder.

**What you expected to happen**:
I expected the explored to allow me to create a query from te

**How to reproduce it (as minimally and precisely as possible)**:

Following the [Set up Grafana Cloud Prometheus ](https://k6.io/docs/results-visualization/grafana-cloud/#set-up-grafana-cloud-prometheus )guide (you will need a `k6` test script. This bellow  should work:
```
#test.js

import http from "k6/http";
import { sleep } from 'k6';

export default function() {
  const res = http.get('https://test-api.k6.io/public/crocodiles/');
  sleep(1)
};

export let options = {
  stages: [
    { duration: '10m', target: 10 }
  ],
  thresholds: {
    "http_req_duration": ["p(95)<200"],
    "http_req_failed": ["rate<0.01"],
  }
};
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana Cloud
- Data source type & version: Prometheus from the Grafana Cloud
- OS Grafana is installed on: N/A
- User OS & Browser: Ubuntu 22.04 / Chrome Version 103.0.5060.53 (Official Build) (64-bit)
- Grafana plugins: N/A
- Others:

### PR DESCRIPTION
**Pull request by obetomuniz**
**What this PR does / why we need it**:

This PR adds the `virtualized` property to the Select Metric field to reduce memory usage overhead while listing Metrics.

**Which issue(s) this PR fixes**:

Fixes #52171
Escalation https://github.com/grafana/support-escalations/issues/4008
Escalation https://github.com/grafana/support-escalations/issues/4053

**Special notes for your reviewer**:

You need to have several metrics to start to figure out the performance issue. Here's a demo:

- Before add `virtualized` prop:

https://user-images.githubusercontent.com/1680157/194077440-a5ead6cf-ae66-45c9-96cb-94e8156931dc.mov

- After add `virtualized` prop:

https://user-images.githubusercontent.com/1680157/194077733-c007482a-25e4-4fde-87c0-783cba36d55b.mov

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/querybuilder/components/MetricSelect.tsx [hunk 1]
```diff
@@ -64,6 +64,7 @@ export function MetricSelect({ query, onChange, onGetMetrics }: Props) {
           className={styles.select}
           value={query.metric ? toOption(query.metric) : undefined}
           placeholder="Select metric"
+          virtualized
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/querybuilder/components/MetricSelect.tsx:67]: beautiful

**Review by gtk-grafana — APPROVED** [review]

**Comment by BruceMa29** [comment]
@obetomuniz Hi，when the number of metrics reaches over 200,000, the API response becomes slow, resulting in a poor user experience.

**Comment by gtk-grafana** [comment]
@BruceMa29 Something similar to what you're describing was added in https://github.com/grafana/grafana/pull/60711.  It's currently behind a feature flag `prometheusResourceBrowserCache`, and can be turned on in 9.5 and up.
