### PR TITLE
Show SAML login button if SAML is enabled

### LINKED ISSUE #19572: SAML: Login button not shown
**What happened**:

SAML login button is not shown despite having SAML enabled and being on Enterprise version.

**What you expected to happen**:

SAML button to be shown.

**How to reproduce it (as minimally and precisely as possible)**:

Use Grafana enterprise and enable SAML as login provider in the configuration. 

**Anything else we need to know?**:

The problem lies on [LoginPage](https://github.com/grafana/grafana/blob/master/public/app/core/components/Login/LoginPage.tsx#L44) where it assumes you need to have OAuth enabled to display the different Login buttons but SAML is not an OAuth provider whilst still being a Login Service for Grafana. 

**Environment**:
- Grafana version: 6.4
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS & Chrome

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
SAML login was not shown despite having SAML enabled and being on Enterprise version.
Move wrapping elements inside LoginServiceButtons as suggested [here](https://github.com/grafana/grafana/pull/19580#discussion_r330675700).

**Which issue(s) this PR fixes**:

Fixes #19572

**Special notes for your reviewer**:

- This is alternative fix for #19580

- If the login form is disabled and at least a login service is enabled the divider line is still shown. I guess that is not something we do not want. So, I tried to removed it but then the button text was not wrapped correctly and I didn't know how to fix it.

### CODE REVIEW

**Review by gotjosh — APPROVED** [review]
Tested it and works as intended. LGTM!

File: public/app/core/components/Login/LoginServiceButtons.tsx [hunk 1]
```diff
@@ -46,6 +46,29 @@ export interface LoginServices {
   [key: string]: LoginService;
 }
 
+const LoginDivider = (keyNames: string[]) => {
+  const serviceElementsEnabled = keyNames.filter(key => {
+    const service: LoginService = loginServices()[key];
+    return service.enabled;
+  });
+  return serviceElementsEnabled.length > 0 ? (
```
Comment (torkelo) [inline public/app/core/components/Login/LoginServiceButtons.tsx]: I would have moved this check into the main component function so that it does not render an empty login-oauth div (check if no services are enabled and return null at start of function)

**Review by torkelo — APPROVED** [review]
Great job! Just one minor nitpick :)

**Comment by torkelo** [comment]
looks great! great job!
