### PR TITLE
News Panel: Improve error message

### LINKED ISSUE #68906: News Visualization: RSS Feed
### 
# What went wrong?

**What happened**:

  - I tried to add two different atom feeds to the source data of the news visualizer and ended up with an exception:
    - https://github.com/junit-team/junit5/releases.atom
    - https://github.com/karatelabs/karate/releases.atom

**What did you expect to happen**:

  - The feeds would be visible on the dashboard

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana, create a new dashboard

**Step 2**:

- Set the visualization for "News" 

**Step 3**:

- Add `https://github.com/junit-team/junit5/releases.atom` as the URL input 

**Step 4**:

image

### 
# What Grafana version are you using?

Grafana v9.5.2 (cfcea75916)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

MacOS

### User's Browser?

Version 113.0.5672.92 (Official Build) (x86_64)

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by tskarhed**
**What is this feature?**
image

Improved error message for the RSS feed

**Why do we need this feature?**

There are a lot of questions about feed errors, which are CORS related. We can reduce support load by linking to the documentation and mentioning this issue

**Who is this feature for?**

People who need external RSS/Atom feeds

**Which issue(s) does this PR fix?**:

Closes #68906

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/panel/news/NewsPanel.tsx [hunk 1]
```diff
@@ -32,7 +32,17 @@ export function NewsPanel(props: NewsPanelProps) {
   }, [getNews]);
 
   if (state.error) {
-    return <div>Error loading RSS feed.</div>;
+    return (
+      <Alert title="Error loading RSS feed">
+        Make sure that the feed URL is correct and that CORS is configured correctly on the server. See{' '}
+        <a
+          style={{ textDecoration: 'underline' }}
+          href="https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/news/"
```
Comment (tskarhed) [inline public/app/plugins/panel/news/NewsPanel.tsx:40]: Do we have any standard link styles? Also, is this the way we should link to documentation?

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍 re: linking to docs, i think this is the only way to do it. does make me worry slightly that it's just going to get out of date at some point tho 🤔
