### PR TITLE
Canvas: Fix duplicated option editors functionality

### LINKED ISSUE #52951: Canvas: Selected element background/border connected to the Layer background/border
https://user-images.githubusercontent.com/88068998/181576039-3ca51978-48b9-40e0-98e4-6306f674056c.mov

Actions made in Selected element background/border sections seem to trigger a scroll to Layer's background/border section.

### PR DESCRIPTION
**Pull request by adela-almasan**
[Uploading Screen Recording 2022-08-02 at 3.57.06 PM.mov…](https://user-images.githubusercontent.com/88068998/182476419-b1e1c962-3e2b-41c2-9619-dd486dd19a2c.mov
)

Fixes #52951

### CODE REVIEW

File: public/app/plugins/panel/canvas/editor/options.ts [hunk 1]
```diff
@@ -1,19 +1,31 @@
...
+
+  return [str];
+};
+
+const uid = Math.floor(Math.random() * 21);
+
 export const optionBuilder: OptionSuppliers = {
   addBackground: (builder, context) => {
-    const category = ['Background'];
+    const category = getCategoryName('Background', context.options?.type);
```
Comment (nmarrs) [inline public/app/plugins/panel/canvas/editor/options.ts:24]: Is this necessary change? I think we can keep the category the same and rely on context instead (for what the options apply to)

**Review by nmarrs — COMMENTED** [review]
Working well for me locally, border also seems to be working semi-reliably too 🤔

File: public/app/plugins/panel/canvas/editor/options.ts (hunk 1 above)
Comment (nmarrs) [reply public/app/plugins/panel/canvas/editor/options.ts:20]: It looks like as long as category is unique the functionality works as expected

With that in mind I removed the uid approach, though we should probably have another person test this locally to confirm these findings (before merge) - I'm going to approve this though as is 👍

**Review by nmarrs — APPROVED** [review]
