### PR TITLE
Elasticsearch: Fixes logs panel error and mapping of level field based on config

### LINKED ISSUE #22023: Log panel error "cannot read property 'toLowerCase' from null"
We've updated our pre-production grafana instance to 6.6.1 from 6.5.3 and our Log panels have stopped working.
The log panels are fed by an elastic data source and since the update they show the error

`Cannot read property 'toLowerCase' from null`

From what I can tell via the query inspector, the query to the elastic data source works fine.
Any ideas how to debug this?

### PR DESCRIPTION
**Pull request by aocenas**
Fixes: https://github.com/grafana/grafana/issues/22023
but also fixes a general issue that the level field was not actually mapped based on what was in the datasource config.

### CODE REVIEW

File: public/app/core/logs_model.ts [hunk 1]
```diff
@@ -312,7 +312,7 @@ export function logSeriesToLogsModel(logSeries: DataFrame[]): LogsModel | undefi
       const searchWords = series.meta && series.meta.searchWords ? series.meta.searchWords : [];
 
       let logLevel = LogLevel.unknown;
-      if (logLevelField) {
+      if (logLevelField && logLevelField.values.get(j)) {
```
Comment (aocenas) [inline public/app/core/logs_model.ts]: This blowed up in same cases because we weren't actually mapping the field properly, but feels like this should be here anyway because we cannot be sure what we get from `values.get(j)` on a Field.

File: public/app/plugins/datasource/elasticsearch/elastic_response.ts [hunk 2]
```diff
@@ -416,86 +416,25 @@ export class ElasticResponse {
...
-          };
-        }
+        const series = createEmptyDataFrame(propNames, this.targets[0].timeField, logMessageField, logLevelField);
 
         // Add a row for each document
         for (const doc of docs) {
+          if (logLevelField) {
+            // Remap level field based on the datasource config. This field is then used in explore to figure out the
+            // log level. We may rewrite some actual data in the level field if they are different.
+            doc['level'] = doc[logLevelField];
```
Comment (aocenas) [inline public/app/plugins/datasource/elasticsearch/elastic_response.ts]: Main fix with the actual mapping of the field here.

File: public/app/plugins/datasource/elasticsearch/elastic_response.ts [hunk 3]
```diff
@@ -522,3 +461,110 @@ export class ElasticResponse {
...
+  _source?: any;
+};
+
+/**
+ * Flatten the docs from response mainly the _source part which can be nested. This flattens it so that it is one level
+ * deep and the keys are: `level1Name.level2Name...`. Also returns list of all properties from all the docs (not all
+ * docs have to have the same keys).
+ * @param hits
+ */
+const flattenHits = (hits: Doc[]): { docs: Record<string, any>[]; propNames: string[] } => {
```
Comment (aocenas) [inline public/app/plugins/datasource/elasticsearch/elastic_response.ts]: This and the later functions were just moved out of the main function for a bit more clarity.

File: public/app/core/logs_model.ts (hunk 1 above)
Comment (kaydelaney) [reply public/app/core/logs_model.ts]: Could simplify a bit with
```suggestion
      if (logLevelField?.values.get(j)) {
```

**Review by kaydelaney — APPROVED** [review]
LGTM
