### PR TITLE
Dashboard: Formatting Currency - add new custom 'financial' currency format without abbreviations

### LINKED ISSUE #37838: Formatting Currency without abbreviation
**What happened**:
Wanted to output a currency value as the full value, without abbreviation, a currency symbol and thousand commas for readability. 

**What you expected to happen**:
To get something like $53,456.75 instead of $53.46K or $53456.75 or 53,456.75

**How to reproduce it (as minimally and precisely as possible)**:
Set a values units in the following ways:

* Currency / Dollar ($) - this gives you the abbreviated version which is no good for reporting.
* prefix:$ - this gives you an unabbreviated version but without the commas, making large numbers hard to read.
* Misc / Locale Format - this gives you the unabbreviated version with the commas but no currency sign.

None of these get the formatting required.

**Anything else we need to know?**:
I would suggest there are couple of options to fix this, either:

* Add "prefix" as a separate option for a value so it can have both a "prefix" and a unit type attached to it. In this way we could prefix it with $ and set the unit to "Misc / Locale Format".

OR 

* Add an extra option to the "Currency" unit option to allow for the abbreviation to be turned off.

I think the first of these offers the most flexibility but the second is more intuitive.

Forum post: https://community.grafana.com/t/formatting-currency-without-abbreviation/50287

**Environment**:
- Grafana version: 8.0.5
- Data source type & version: MySQL 8.0.19
- OS Grafana is installed on: Docker
- User OS & Browser: Mac / Chrome
- Grafana plugins: None

### PR DESCRIPTION
**Pull request by axelavargas**
This PR is based on work implemented in https://github.com/grafana/grafana/pull/54691 (PR by some members of the community who didn't signing the CLA)

**What is this feature?**

Add custom 'financial' currency format without abbreviations

This means: a value such as: `1235667` 
  - `currency:financial:$` formats $1,235,667 instead of $1.24M
  - `currency:financial:€:suffix` formats 1,234.56€ with symbol positioning

Also in this PR:
- Applied performance suggestions from the old PR comment
- Added unit tests
- Updated documentation

EveryPennyCounts

**Who is this feature for?**
Anyone who don't want abbreviations when formatting currency

Fixes #37838

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-data/src/valueFormats/valueFormats.ts [hunk 1]
```diff
@@ -257,8 +257,23 @@ export function getValueFormat(id?: string | null): ValueFormatter {
...
       if (key === 'currency') {
-        return currency(sub);
+        const keySplit = sub.split(':');
+
+        if (keySplit[0] === 'financial' && keySplit.length >= 2) {
+          const symbol = keySplit[1];
+          if (!symbol) {
+            return toFixedUnit(''); // fallback for empty symbol
+          }
+          const asSuffix = keySplit[2] === 'suffix' || keySplit[2] === 'true';
```
Comment (kaydelaney) [inline packages/grafana-data/src/valueFormats/valueFormats.ts]: Not sure I get the `keySplit[2] === 'true'` part? Like if the string is `currency:financial:$:true` we want that to behave the same as `currency:financial:$:suffix`?

**Review by kaydelaney — APPROVED** [review]
Looks good! Just had a small question about one part

File: packages/grafana-data/src/valueFormats/valueFormats.ts (hunk 1 above)
Comment (axelavargas) [reply packages/grafana-data/src/valueFormats/valueFormats.ts]: exactly! Imo it doesn't hurt to have redundancy here

Comment (kaydelaney) [reply packages/grafana-data/src/valueFormats/valueFormats.ts]: Should it be added to the docs? 🤔

Comment (axelavargas) [reply packages/grafana-data/src/valueFormats/valueFormats.ts]: a very good point, I think it should, however, I don't think we follow this pattern anywhere 🤔 

Let me research, if is not a pattern I will remove this, I don't want to make it more confusing for users

**Comment by Niek** [comment]
Awesome work 👏🏻

File: packages/grafana-data/src/valueFormats/valueFormats.ts (hunk 1 above)
Comment (axelavargas) [reply packages/grafana-data/src/valueFormats/valueFormats.ts]: removed [`35165fb` (#106604)](https://github.com/grafana/grafana/pull/106604/commits/35165fbfa685548ff7d99f23774480eb5674e729) , thanks @kaydelaney that was a good catch 🙌🏾

**Review by academo — APPROVED** [review]

**Review by jesdavpet — APPROVED** [review]
🤑 💸

**Comment by marybaldwin** [comment]
Hiiiii @axelavargas - could you create a what's new post for this? https://admin.grafana.com/whats-new/ - we're trying to get them all by EOD tomorrow. Thank you!
