### PR TITLE
Dashboard: Redirect between `v1alpha1` and `v2alpha1` depending on stored version

### LINKED ISSUE #101036: Use v1 or v2 endpoints depending of the format that they were stored
## Problem  

Currently, dashboards stored with schema version `v0` can be in **any** `SchemaVersion`. To ensure they conform to the latest schema, they must go through a series of migrations handled by `DashboardMigrator.ts`.  

We've started migrating these transformations to the backend, allowing them to run automatically for the `v1` endpoint. This ensures that querying any dashboard returns data in the **latest `SchemaVersion` format**.  

However, this introduces several challenges:  

1. Querying `v2` requires multiple transformations:  
- **v0 → v1**: Runs all necessary migrations to upgrade to the latest schema version.  
- **v1 → v2**: Converts the v1 format to v2.  
2. If a dashboard was stored as `v2`, querying it from `v1` leads to complications—should it be downgraded, or should querying return an error?  
3. This level of complexity is **unnecessary while `v2` is still in alpha**.  

---

## Solution  

Each endpoint will be **canonical**, meaning it will not run full migrations beyond its intended scope:  

- **`v0` Endpoint:** Returns the JSON **as it was stored**, without any migrations.  
- **`v1` Endpoint:**  
- If the dashboard’s `schemaVersion` is **greater than the minimum supported version** (currently `v36`), it will be migrated to the latest schema version.  
- If the dashboard was stored as `v2`, the request will **fail** with an error message instructing the user to query the `v2` endpoint.  
- **`v2` Endpoint:**  
- Returns the JSON in **schema v2 format**.  
- If the dashboard was stored in `v1`, the request will **fail** with an error indicating that the user should query the `v1` endpoint instead.  

This approach keeps the migration logic clean while ensuring **predictable behavior** across endpoints.

### PR DESCRIPTION
**Pull request by ivanortegaalba**
This change ensures smooth operation across different dashboard versions without forcing transformations while maintaining backward compatibility and preparing for future layout features.

## Background
Grafana dashboards can be stored using different API versions:
- Legacy API (`api/dashboard`) - stored as `v0alpha1` in K8s app platform
- Kubernetes app platform versions: `v0alpha1`, `v1alpha1`, and `v2alpha1`

## Problem
When querying a dashboard through an API version different from its stored version, and no conversion is implemented between these versions, the K8s API returns a conversion error:

```json
"status": {
    "conversion": {
      "failed": true,
      "storedVersion": "v1alpha1",
      "error": "backend conversion not yet implemented"
    }
}
```

This breaks the user experience as the dashboard becomes inaccessible, even though it exists and is accessible through the correct API version endpoint.

## Solution
We've implemented an intelligent redirection system. 

```mermaid
sequenceDiagram
    participant F as Components
    participant U as UnifiedDashboardAPI
    participant V1 as v1alpha1 Endpoint
    participant V2 as v2alpha1 Endpoint

    F->>U: Request Dashboard
    U->>V1: Try v1alpha1 first
    alt No Conversion Error
        V1-->>U: Return Dashboard
        U-->>F: Return Response
    else Conversion Error
        V1-->>U: Error with storedVersion
        Note over U: storedVersion === v2
        U->>V2: Retry with v2alpha1
        V2-->>U: Return Dashboard
        U-->>F: Return Response
    end
```

With two main components:

### 1. UnifiedDashboardScenePageStateManager
A proxy manager that selects the appropriate state manager based on API version and response format:
- Uses `v1alpha1` as default endpoint
- Handles version redirections:
  - If `v1alpha1` query returns conversion error and stored version is `v2alpha1` → refetch using `v2alpha1`
  - If `v2alpha1` query fails for `v1alpha1`/`v0alpha1` dashboard → switch back to v1
- Save operations use the appropriate version based on dashboard format
- Forces `v2` manager when `newDashboardLayout` feature flag is enabled

### 2. UnifiedDashboardAPI
A proxy service that:
- Handles conversion error redirections outside dashboard pages
- Provides consistent CRUD operations through `getDashboardAPI()`
- Returns different clients based on context:
  - Scenes disabled: Returns v1 or legacy based on K8s Dashboards flag
  - Scenes enabled: Same logic, with option to force version via `getDashboardAPI('v1' | 'v2')`

### API Client Behavior
`getDashboardAPI()` now returns different clients based on context, requiring handlers to support both response formats.

### Dashboard Diffing
- Added warning when dashboard loaded as v1 will be saved as v2 (due to new layout features)
- Implemented v1 to v2 transformation for comparing current values of time options, variables, and refresh settings

### E2E Testing
- Removed forced v2 format testing
- Deprecated `useV2Dashboard` feature toggle
- Refactored test suite to use `kubernetesDashboard` flag

## Follow-up Tasks
- Add E2E tests for v1↔v2 redirections
- Review and improve UX for version change warnings during save operations
- Avoid applying migrations in the backend if the schemaVersion < min migration implemented in the backend

Fixes #101036

### CODE REVIEW

File: public/app/features/dashboard-scene/serialization/DashboardSceneSerializer.ts [hunk 1]
```diff
@@ -19,11 +19,16 @@ import { DashboardScene } from '../scene/DashboardScene';
 import { transformSceneToSaveModel } from './transformSceneToSaveModel';
 import { transformSceneToSaveModelSchemaV2 } from './transformSceneToSaveModelSchemaV2';
 
-export interface DashboardSceneSerializerLike<T, M> {
+/**
+ * T is the type of the save model
+ * M is the type of the metadata
+ * I is the type of the initial save model. By default it's the same as T.
```
Comment (harisrozajac) [inline public/app/features/dashboard-scene/serialization/DashboardSceneSerializer.ts:25]: Why would the `initialSave` model and `save` model have different types? Is this because sometimes we might want to save a V1 dashboard as V2?

File: public/app/features/dashboard-scene/pages/DashboardScenePageStateManager.ts [hunk 2]
```diff
@@ -569,32 +571,117 @@ export class DashboardScenePageStateManagerV2 extends DashboardScenePageStateMan
...
-export function getDashboardScenePageStateManager(
-  v: 'v2'
-): DashboardScenePageStateManagerLike<DashboardWithAccessInfo<DashboardV2Spec>>;
-export function getDashboardScenePageStateManager(): DashboardScenePageStateManagerLike<DashboardDTO>;
+export function getDashboardScenePageStateManager(): UnifiedDashboardScenePageStateManager;
+export function getDashboardScenePageStateManager(v: 'v1'): DashboardScenePageStateManager;
+export function getDashboardScenePageStateManager(v: 'v2'): DashboardScenePageStateManagerV2;
+/**
+ * Get a manager for the given version. By default, it returns the unified manager that would handle both v1 and v2.
+ * V1 would be used by default if no version is provided.
```
Comment (harisrozajac) [inline public/app/features/dashboard-scene/pages/DashboardScenePageStateManager.ts:663]: Does the second line of the comment need to be deleted? Unified manager is used by default right? And  I imagine DashboardScenePage we would update this to just be `const stateManager =  getDashboardScenePageStateManager();` https://github.com/grafana/grafana/blob/7edcde63650b3070b2b050c738cb1fb509731780/public/app/features/dashboard-scene/pages/DashboardScenePage.tsx#L28.

File: public/app/features/dashboard/api/UnifiedDashboardAPI.ts [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+import { DashboardDTO } from 'app/types';
+
+import { SaveDashboardCommand } from '../components/SaveDashboard/types';
+
+import { DashboardAPI, DashboardVersionError, DashboardWithAccessInfo } from './types';
+import { isV1DashboardCommand, isV2DashboardCommand } from './utils';
+import { K8sDashboardAPI } from './v1';
+import { K8sDashboardV2API } from './v2';
+
+export class UnifiedDashboardAPI
```
Comment (harisrozajac) [inline public/app/features/dashboard/api/UnifiedDashboardAPI.ts:13]: ❤️

**Review by harisrozajac — COMMENTED** [review]
This approach looks great to me! I left some questions just to clarify some points but overall great work on this!

File: public/app/features/dashboard-scene/serialization/DashboardSceneSerializer.ts (hunk 1 above)
Comment (ivanortegaalba) [reply public/app/features/dashboard-scene/serialization/DashboardSceneSerializer.ts:25]: Great question! 

In dynamic dashboards, the initial state could be v1, but when editing the dashboard, it will become V2 since dynamic dashboard is only supported in that format. This is why we might have the initial state as v1 for SerializerV2.

**Review by axelavargas — COMMENTED** [review]
This approach looks great!  I tested the redirection when deailing with v2 resources and works as expected.

I also fixed a minor issue with snapshots and TS errors, I think we just need to fix the unit test and it will be ready to go! 🥳

**Comment by harisrozajac** [comment]
This looks great 🎖️  I've tested the redirection too, and everything works as expected. I get the expected status with error in when trying to get V2 dash through V1 endpoint

File: public/app/features/apiserver/types.ts [hunk 4]
```diff
@@ -42,6 +42,7 @@ export const AnnoKeyFolderId = 'grafana.app/folderId';
 export const AnnoKeyFolderUrl = 'grafana.app/folderUrl';
 export const AnnoKeyMessage = 'grafana.app/message';
 export const AnnoKeySlug = 'grafana.app/slug';
+export const AnnoKeyConversion = 'CONVERSION-0';
```
Comment (ryantxu) [inline public/app/features/apiserver/types.ts:45]: ^^^ does not exist and should not exit

(was early development stuff)

Comment (ivanortegaalba) [reply public/app/features/apiserver/types.ts]: Done! It was during testing, we added it, but now it uses status field 💯

**Comment by harisrozajac** [comment]
@ivanortegaalba I've fixed all remaining tests :slightly_smiling_face: Just to give you a bit more context about the changes I've made: I've implemented caching functions in unified state manager which overwrite those in base class, so when we run them we can update the underlying active state managers. There could maybe be a better way to do this and handle state sync between unified manager and the active managers it runs. I didn't use withVersionHandler inside of them because that function is async and all caching functions are synchronous. 

Feel free to refactor that, as long as we keep state in sync we should be good. Not sure if we should maybe update UnifiedManager's state with activeManager's because then things like `getDashboardScenePageStateManager.getCache()` will work. Currently when doing this we only get UnifiedManager's state because we are inheriting this function from base class, when we really need to access the activeManager state. 

Also, there's unrelated failing backend tests which is flaky and not related to this PR.

File: public/app/features/dashboard-scene/saving/SaveDashboardForm.tsx [hunk 5]
```diff
@@ -128,6 +128,15 @@ export function SaveDashboardForm({ dashboard, drawer, changeInfo }: Props) {
   return (
     <Stack gap={2} direction="column">
       <SaveDashboardFormCommonOptions drawer={drawer} changeInfo={changeInfo} />
+      {hasMigratedToV2 && (
+        <Alert title="Dashboard drastically changed" severity="warning">
```
Comment (ryantxu) [inline public/app/features/dashboard-scene/saving/SaveDashboardForm.tsx:132]: drastic!!!

File: public/app/core/components/Select/DashboardPicker.tsx [hunk 6]
```diff
@@ -57,34 +57,28 @@ export const DashboardPicker = ({
...
+      if (isDashboardV2Resource(dto)) {
         setCurrent({
           value: {
-            uid: resWithSchemaV2.metadata.name,
-            title: resWithSchemaV2.spec.title,
-            folderTitle: resWithSchemaV2.metadata.annotations?.[AnnoKeyFolderTitle],
-            folderUid: resWithSchemaV2.metadata.annotations?.[AnnoKeyFolder],
+            uid: dto.metadata.name,
+            title: dto.spec.title,
+            folderTitle: dto.metadata.annotations?.[AnnoKeyFolderTitle],
```
Comment (ryantxu) [inline public/app/core/components/Select/DashboardPicker.tsx:67]: ^^^ `AnnoKeyFolderTitle` sus... but lets resolve that lager

**Review by ryantxu — APPROVED** [review]
basic testing all worked 🎉 

(not this PR... do we need/want to save things in v2 if we are not using any v2 features?  eg, do we only need v2 if a layout is set?)

File: public/app/features/dashboard-scene/saving/SaveDashboardForm.tsx (hunk 5 above)
Comment (ivanortegaalba) [reply public/app/features/dashboard-scene/saving/SaveDashboardForm.tsx:132]: I could say ‘significantly,’ but my Spaniard accent tends to be more dramatic 😆

**Comment by ivanortegaalba** [comment]
> basic testing all worked 🎉

🙌 

> (not this PR... do we need/want to save things in v2 if we are not using any v2 features? eg, do we only need v2 if a layout is set?)

The current logic is to save everything in V1 unless the dashboard has already been saved in V2 or if the dynamic dashboard is enabled. I believe that when V2 is stable and we have migrations, we can set it as the default while still keeping the redirection to V1, of course. In the meantime, we would need to enable save in v2 based on features.

I think this is the safest way to go. WDYT?

File: public/app/features/dashboard/api/types.ts [hunk 7]
```diff
@@ -14,8 +14,30 @@ export interface DashboardAPI<G, T> {
...
+   *   }
+   * }
+   */
+  conversion?: {
+    error: string;
+    failed: boolean;
+    storedVersion: DashboardStoredVersion;
+  };
+}
+
```
Comment (radiohead) [inline public/app/features/dashboard/api/types.ts:38]: Can we use the auto-generated types from https://github.com/grafana/grafana/blob/main/packages/grafana-schema/src/schema/dashboard/v2alpha1/types.status.gen.ts#L1-L29 instead?

**Review by radiohead — COMMENTED** [review]
Nice work!

**Review by axelavargas — COMMENTED** [review]
I gave it a quick test with `dashboardNewLayouts` feature toggle and got this error,  probably not related with this PR, but will investigate

`TypeError: Cannot read properties of null (reading 'scrollTop')`

The error happens when I tried to save a v2 dashboard, after changing the panel title from the panel edit page 



https://github.com/user-attachments/assets/f1925064-047a-412c-8e49-f283be9c6c59

**Comment by harisrozajac** [comment]
> TypeError: Cannot read properties of null (reading 'scrollTop')

@axelavargas yeah not related to this PR because I can reproduce this one in main, and the way it occurs for me sometimes is when I change the dashboard title in settings

File: public/app/features/dashboard/api/types.ts (hunk 7 above)
Comment (ivanortegaalba) [reply public/app/features/dashboard/api/types.ts:38]: Let me add it to the issue related to [SDK usage](https://github.com/grafana/grafana/issues/101956). I'd love that! Thanks for bringing this! 💯

**Comment by ivanortegaalba** [comment]
> I gave it a quick test with `dashboardNewLayouts` feature toggle and got this error, probably not related with this PR, but will investigate
> 
> `TypeError: Cannot read properties of null (reading 'scrollTop')`
> 
> The error happens when I tried to save a v2 dashboard, after changing the panel title from the panel edit page
> 
>  SavingPanelTitleFromPanelEditFails.mp4

If it is new layouts bug, feel free to pass it to dynamic dashboard squad to note this for the coming bug bash :D

**Review by harisrozajac — APPROVED** [review]
looks great! 🚀

**Review by axelavargas — APPROVED** [review]
🏅 awesome work
