### PR TITLE
Row-repeats: Fix disappearing panel when viewed panel is refreshed

### LINKED ISSUE #57159: Graph disappears on clicking on the "Refresh dashboard" inside the non-first repeating row
When you click on "Refresh dashboard", or change time window, the graph expanded in full screen ("view" mode) disappears if it is located in a repeating row, and if it is not in the first row.
The problem is reproduced only if the variable, on the basis of which rows is repeated, has the "Refresh" option specified to "On time range change". If you change it to "On dashboard load", the problem goes away.

Recorded a screencast: https://youtu.be/qa5ISR-h1_4

**Environment**:
- Grafana version: 9.1.6 and 9.2.0
- Data source type & version: Prometheus, we using VictoriaMetrics
- OS Grafana is installed on: Docker image, based on Alpine
- User OS & Browser: macOS Monterey, Firefox 105.0.3 (64-bit), Chromium 107.0.5253.0, Safari 16.0
- Grafana plugins: btplc-alarm-box-panel,vertamedia-clickhouse-datasource,vonage-status-panel,grafana-clock-panel,grafana-piechart-panel,grafana-worldmap-panel,jdbranham-diagram-panel,praj-ams-datasource,yesoreyeram-boomtable-panel

### PR DESCRIPTION
**Pull request by kaydelaney**
Fixes an issue where refreshing a panel being viewed that's part of a repeated row caused the panel to disappear.
The problem was that when the dashboard/panel was refreshed, the repeated rows (and its contained panels) are destroyed and then recreated, but the recreated panel didn't have its `isViewing` property set, and the dashboard's `panelInView` property referred to the "old" panel.

**Which issue(s) does this PR fix?**:
Close #57159

### CODE REVIEW

File: public/app/features/dashboard/state/DashboardModel.ts [hunk 1]
```diff
@@ -547,6 +547,9 @@ export class DashboardModel implements TimeModel {
       return;
     }
 
+    // If we're viewing a panel contained in a repeated row, we need to set it
+    // as isViewing after it's re-created
+    const viewedPanelId = this.panels.findIndex((p) => p.isViewing);
```
Comment (polibb) [inline public/app/features/dashboard/state/DashboardModel.ts:552]:
```suggestion
    const viewedPanelIndex = this.panels.findIndex((p) => p.isViewing);
```

File: public/app/features/dashboard/containers/DashboardPage.tsx [hunk 2]
```diff
@@ -273,7 +273,7 @@ export class UnthemedDashboardPage extends PureComponent<Props, State> {
     else if (state.viewPanel && !urlViewPanelId) {
       // This mutable state feels wrong to have in getDerivedStateFromProps
       // Should move this state out of dashboard in the future
-      dashboard.exitViewPanel(state.viewPanel);
+      dashboard.exitViewPanel(dashboard.panelInView ?? state.viewPanel);
```
Comment (polibb) [inline public/app/features/dashboard/containers/DashboardPage.tsx:276]: I really don't understand how this is fixing the issue of the panel staying huge after leaving the View Panel mode if you have refreshed it at least once.. since the `dashboard.panelInView` is the first one to become `undefined`, so it shouldn't tip the scales of what's happening here. 

But it does, somehow 😅. I love this, @kaydelaney, I would like it if you explain to me why it works.

**Comment by wf1nder** [comment]
Is there a chance that this fix will appear in the next release?

**Review by torkelo — COMMENTED** [review]
Would it not be easier to skip processing repeats when in view mode ?

**Comment by torkelo** [comment]
Easier maybe the wrong word , but less complex :)

**Comment by kaydelaney** [comment]
Finally got back around to this 😓 Simplified the logic as per @torkelo's suggestion

**Review by torkelo — APPROVED** [review]

**Comment by zerok** [comment]
@kaydelaney Shouldn't this also be backported to 9.5.x? This was merged after the v9.5.x branch was cut :)
