### PR TITLE
Alerting: Add subpath to the folder edit and permission url

### LINKED ISSUE #51830: "Edit Folder" and "Edit Permission" in AlertRulesGroup ignores Grafana being hosted under relative subpath
**What happened**:
Links to "Edit Folder" and "Edit Permission" in Alert rules list are using an absolute baseurl ("/dashboards/...)
**What you expected to happen**:
If Grafana is hosted using a subpath (e.g.  /grafana/ ) links should lead to "/grafana/dashboards/..."

**How to reproduce it (as minimally and precisely as possible)**:
Setup grafana with environment variables:

GF_SERVER_ROOT_URL=http://localhost/grafana/
GF_SERVER_SERVE_FROM_SUB_PATH=true

Create a dashboard in a folder, configure an alert in the dashboard. 

Open http://localhost/grafana/alerting/list
Click on Edit or Lock Icon in folder group.
-> links to http://localhost/dashboards/f/***folder_uid***/settings
should be 
-> http://localhost/dashboards/grafana/dashboards/f/***folder_uid***/settings

**Anything else we need to know?**:
in https://github.com/grafana/grafana/blob/3dfafbadef3f17ff4aefe64381caaf1fda03510f/public/app/features/alerting/unified/components/rules/RulesGroup.tsx#L72

the baseurl is set using an absolute link to "/dashboards/...", it should be used with a relative path or include the hosted subpath.

**Environment**:
- Grafana version: 9.02
- OS Grafana is installed on: docker container

### PR DESCRIPTION
**Pull request by konrad147**
**What this PR does / why we need it**:
When Grafana is served under the subpath the Edit Folder and Edit Permission URLs do not take the subpath into consideration, thus users get 404 errors.

**Which issue(s) this PR fixes**:
Fixes #51830

**Special notes for your reviewer**:
The URL will be still an absolute URL as required by https://github.com/grafana/grafana/pull/33782

`config.appSubUrl` starts with `/`

### CODE REVIEW

File: public/app/features/alerting/unified/components/rules/RulesGroup.tsx [hunk 1]
```diff
@@ -70,7 +71,7 @@ export const RulesGroup: FC<Props> = React.memo(({ group, namespace, expandAll }
     );
   } else if (rulesSource === GRAFANA_RULES_SOURCE_NAME) {
     if (folderUID) {
-      const baseUrl = `/dashboards/f/${folderUID}/${kbn.slugifyForUrl(namespace.name)}`;
+      const baseUrl = `${config.appSubUrl}/dashboards/f/${folderUID}/${kbn.slugifyForUrl(namespace.name)}`;
```
Comment (jtheory) [inline public/app/features/alerting/unified/components/rules/RulesGroup.tsx:74]: This does look like the safest approach. :)

2 questions (non blockers):
* are we sure config.appSubUrl always has a leading / and no trailing / (e.g. "/suburl") or could that vary?
* is there any way to test this? I guess the better question is "is there a test that would have caught this bug?

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rules/RulesGroup.tsx:74]: I have a similar question, is it possible to have undefined in `config.appSubrl` ???, because in this case we will have `undefined/dashboards'` as a result

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rules/RulesGroup.tsx:74]: ok, no it's not possible , it's initialised with ''. So, 👍

**Review by soniaAguilarPeiron — APPROVED** [review]
I agree with @jtheory that maybe we can think about adding a test for that

**Review by soniaAguilarPeiron — APPROVED** [review]

File: public/app/features/alerting/unified/components/rules/RulesGroup.tsx (hunk 1 above)
Comment (konrad147) [reply public/app/features/alerting/unified/components/rules/RulesGroup.tsx:74]: I'm not really sure if there is an easy way to test this. A one improvement that comes to my mind is to create a function that we always use when we create urls, then we could test that function and we would have unified way of building URLs

**Comment by konrad147** [comment]
> I have a similar question, is it possible to have undefined in config.appSubrl ???, because in this case we will have undefined/dashboards' as a result
@soniaAguilarPeiron If there is no subpath configured then the `config.appSubUrl` is an empty string, so we are fine :)

File: public/app/features/alerting/unified/components/rules/RulesGroup.tsx (hunk 1 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rules/RulesGroup.tsx:74]: this make sense @konrad147
