### PR TITLE
Azure: Fix duplicated trace links

### LINKED ISSUE #102676: Dashboards: Duplicate "Explore Trace Logs" links in Azure Monitor Traces Visualization
### What happened?

Twelve "Explore Trace Logs" links are displayed in Azure Monitor traces visualization as follows:

Image

### What did you expect to happen?

Only one "Explore Trace Logs" is displayed:

Image

### Did this work before?

Maybe no (I'm new to Grafana)

### How do we reproduce it?

1. Create Azure resources
    - Refer to a Terraform file described later
2. Run Grafana locally
3. Add Azure Monitor data source using the service principle (application registration) created by the step 1
    - You can get the application ID and client secret by running `terraform output -json`
4. Run the Go program described later
5. Go to http://localhost:3000/explore
6. Select the following:
    - Service: Trace
    - Resource: azure-trace-demo (Application Insights)
    - Format as: Trace
7. Click the link icon

<details>
<summary>Terraform file</summary>

```terraform
variable "subscription_id" {}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}

resource "azurerm_resource_group" "this" {
  name     = "azure-tracing-demo"
  location = "eastus"
}

resource "azurerm_log_analytics_workspace" "this" {
  name                = "azure-tracing-demo"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name

  sku = "PerGB2018"

  internet_ingestion_enabled = false
}

resource "azurerm_application_insights" "this" {
  name                = "azure-tracing-demo"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  application_type    = "other"
  workspace_id        = azurerm_log_analytics_workspace.this.id
}

resource "azuread_application" "this" {
  display_name = "azure-tracing-demo"
}

resource "azuread_service_principal" "this" {
  client_id = azuread_application.this.client_id
}

resource "azuread_application_password" "this" {
  application_id = azuread_application.this.id
}

resource "azurerm_role_assignment" "this" {
  principal_id         = azuread_service_principal.this.object_id
  role_definition_name = "Monitoring Reader"
  scope                = "/subscriptions/${var.subscription_id}"

  skip_service_principal_aad_check = true
}

output "instrumentation_key" {
  value     = azurerm_application_insights.this.instrumentation_key
  sensitive = true
}

output "application_id" {
  value = azuread_application.this.client_id
}

output "client_secret" {
  value     = azuread_application_password.this.value
  sensitive = true
}
```

</details>

<details>
<summary>Go program</summary>

```go
package main

import (
	"os"
	"time"

	"github.com/microsoft/ApplicationInsights-Go/appinsights"
	"github.com/microsoft/ApplicationInsights-Go/appinsights/contracts"
)

var instrumentationKey string

func init() {
	instrumentationKey = os.Getenv("INSTRUMENTATION_KEY")
	if instrumentationKey == "" {
		panic("INSTRUMENTATION_KEY is required. You can get the value by running `terraform output -json instrumentation_key`")
	}
}

func main() {
	client := appinsights.NewTelemetryClient(instrumentationKey)

	dependency := appinsights.NewRemoteDependencyTelemetry("operationName", "Redis", "", true)
	dependency.Duration = time.Millisecond
	dependency.Tags = map[string]string{contracts.CloudRole: "serviceName"}
	client.Track(dependency)

	<-client.Channel().Close(5 * time.Second)
}
```

</details>

### Is the bug inside a dashboard panel?

| Key | Value |
|--|--|
| Panel | traces @ 9.2.0 |
| Grafana | Grafana v9.2.0 (NA) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "id": 2,
      "type": "traces",
      "title": "Reproduced with embedded data",
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "fieldConfig": {
        "defaults": {},
        "overrides": []
      },
      "pluginVersion": "9.2.0",
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "typeVersion": [
                    0,
                    0
                  ],
                  "custom": {
                    "azureColumnTypes": [
                      "datetime",
                      "string",
                      "string",
                      "real",
                      "string",
                      "string",
                      "string",
                      "string",
                      "dynamic",
                      "dynamic",
                      "string",
                      "string"
                    ]
                  },
                  "preferredVisualisationType": "trace"
                },
                "fields": [
                  {
                    "name": "startTime",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time",
                      "nullable": true
                    },
                    "config": {
                      "links": [
                        {
                          "title": "Explore Trace Logs",
                          "internal": {
                            "query": {
                              "refId": "",
                              "queryType": "Azure Log Analytics",
                              "azureLogAnalytics": {
                                "query": "union availabilityResults,\ncustomEvents,\ndependencies,\nexceptions,\npageViews,\nrequests,\ntraces\n| where operation_Id == \"${__data.fields.traceID}\"",
                                "resources": [
                                  "/subscriptions/<subscription-id>/resourceGroups/azure-tracing-demo/providers/Microsoft.Insights/components/azure-tracing-demo"
                                ]
                              }
                            },
                            "datasourceUid": "fegls9d2ka48wb",
                            "datasourceName": "grafana-azure-monitor-datasource"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "name": "itemType",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {
                      "links": [
                        {
                          "title": "Explore Trace Logs",
                          "internal": {
                            "query": {
                              "refId": "",
                              "queryType": "Azure Log Analytics",
                              "azureLogAnalytics": {
                                "query": "union availabilityResults,\ncustomEvents,\ndependencies,\nexceptions,\npageViews,\nrequests,\ntraces\n| where operation_Id == \"${__data.fields.traceID}\"",
                                "resources": [
                                  "/subscriptions/<subscription-id>/resourceGroups/azure-tracing-demo/providers/Microsoft.Insights/components/azure-tracing-demo"
                                ]
                              }
                            },
                            "datasourceUid": "fegls9d2ka48wb",
                            "datasourceName": "grafana-azure-monitor-datasource"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "name": "serviceName",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {
                      "links": [
                        {
                          "title": "Explore Trace Logs",
                          "internal": {
                            "query": {
                              "refId": "",
                              "queryType": "Azure Log Analytics",
                              "azureLogAnalytics": {
                                "query": "union availabilityResults,\ncustomEvents,\ndependencies,\nexceptions,\npageViews,\nrequests,\ntraces\n| where operation_Id == \"${__data.fields.traceID}\"",
                                "resources": [
                                  "/subscriptions/<subscription-id>/resourceGroups/azure-tracing-demo/providers/Microsoft.Insights/components/azure-tracing-demo"
                                ]
                              }
                            },
                            "datasourceUid": "fegls9d2ka48wb",
                            "datasourceName": "grafana-azure-monitor-datasource"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "name": "duration",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64",
                      "nullable": true
                    },
                    "config": {
                      "links": [
                        {
                          "title": "Explore Trace Logs",
                          "internal": {
                            "query": {
                              "refId": "",
                              "queryType": "Azure Log Analytics",
                              "azureLogAnalytics": {
                                "query": "union availabilityResults,\ncustomEvents,\ndependencies,\nexceptions,\npageViews,\nrequests,\ntraces\n| where operation_Id == \"${__data.fields.traceID}\"",
                                "resources": [
                                  "/subscriptions/<subscription-id>/resourceGroups/azure-tracing-demo/providers/Microsoft.Insights/components/azure-tracing-demo"
                                ]
                              }
                            },
                            "datasourceUid": "fegls9d2ka48wb",
                            "datasourceName": "grafana-azure-monitor-datasource"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "name": "traceID",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {
                      "links": [
                        {
                          "title": "Explore Trace Logs",
                          "internal": {
                            "query": {
                              "refId": "",
                              "queryType": "Azure Log Analytics",
                              "azureLogAnalytics": {
                                "query": "union availabilityResults,\ncustomEvents,\ndependencies,\nexceptions,\npageViews,\nrequests,\ntraces\n| where operation_Id == \"${__data.fields.traceID}\"",
                                "resources": [
                                  "/subscriptions/<subscription-id>/resourceGroups/azure-tracing-demo/providers/Microsoft.Insights/components/azure-tracing-demo"
                                ]
                              }
                            },
                            "datasourceUid": "fegls9d2ka48wb",
                            "datasourceName": "grafana-azure-monitor-datasource"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "name": "spanID",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {
                      "links": [
                        {
                          "title": "Explore Trace Logs",
                          "internal": {
                            "query": {
                              "refId": "",
                              "queryType": "Azure Log Analytics",
                              "azureLogAnalytics": {
                                "query": "union availabilityResults,\ncustomEvents,\ndependencies,\nexceptions,\npageViews,\nrequests,\ntraces\n| where operation_Id == \"${__data.fields.traceID}\"",
                                "resources": [
                                  "/subscriptions/<subscription-id>/resourceGroups/azure-tracing-demo/providers/Microsoft.Insights/components/azure-tracing-demo"
                                ]
                              }
                            },
                            "datasourceUid": "fegls9d2ka48wb",
                            "datasourceName": "grafana-azure-monitor-datasource"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "name": "parentSpanID",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {
                      "links": [
                        {
                          "title": "Explore Trace Logs",
                          "internal": {
                            "query": {
                              "refId": "",
                              "queryType": "Azure Log Analytics",
                              "azureLogAnalytics": {
                                "query": "union availabilityResults,\ncustomEvents,\ndependencies,\nexceptions,\npageViews,\nrequests,\ntraces\n| where operation_Id == \"${__data.fields.traceID}\"",
                                "resources": [
                                  "/subscriptions/<subscription-id>/resourceGroups/azure-tracing-demo/providers/Microsoft.Insights/components/azure-tracing-demo"
                                ]
                              }
                            },
                            "datasourceUid": "fegls9d2ka48wb",
                            "datasourceName": "grafana-azure-monitor-datasource"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "name": "operationName",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {
                      "links": [
                        {
                          "title": "Explore Trace Logs",
                          "internal": {
                            "query": {
                              "refId": "",
                              "queryType": "Azure Log Analytics",
                              "azureLogAnalytics": {
                                "query": "union availabilityResults,\ncustomEvents,\ndependencies,\nexceptions,\npageViews,\nrequests,\ntraces\n| where operation_Id == \"${__data.fields.traceID}\"",
                                "resources": [
                                  "/subscriptions/<subscription-id>/resourceGroups/azure-tracing-demo/providers/Microsoft.Insights/components/azure-tracing-demo"
                                ]
                              }
                            },
                            "datasourceUid": "fegls9d2ka48wb",
                            "datasourceName": "grafana-azure-monitor-datasource"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "name": "serviceTags",
                    "type": "other",
                    "typeInfo": {
                      "frame": "json.RawMessage",
                      "nullable": true
                    },
                    "config": {
                      "links": [
                        {
                          "title": "Explore Trace Logs",
                          "internal": {
                            "query": {
                              "refId": "",
                              "queryType": "Azure Log Analytics",
                              "azureLogAnalytics": {
                                "query": "union availabilityResults,\ncustomEvents,\ndependencies,\nexceptions,\npageViews,\nrequests,\ntraces\n| where operation_Id == \"${__data.fields.traceID}\"",
                                "resources": [
                                  "/subscriptions/<subscription-id>/resourceGroups/azure-tracing-demo/providers/Microsoft.Insights/components/azure-tracing-demo"
                                ]
                              }
                            },
                            "datasourceUid": "fegls9d2ka48wb",
                            "datasourceName": "grafana-azure-monitor-datasource"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "name": "tags",
                    "type": "other",
                    "typeInfo": {
                      "frame": "json.RawMessage",
                      "nullable": true
                    },
                    "config": {
                      "links": [
                        {
                          "title": "Explore Trace Logs",
                          "internal": {
                            "query": {
                              "refId": "",
                              "queryType": "Azure Log Analytics",
                              "azureLogAnalytics": {
                                "query": "union availabilityResults,\ncustomEvents,\ndependencies,\nexceptions,\npageViews,\nrequests,\ntraces\n| where operation_Id == \"${__data.fields.traceID}\"",
                                "resources": [
                                  "/subscriptions/<subscription-id>/resourceGroups/azure-tracing-demo/providers/Microsoft.Insights/components/azure-tracing-demo"
                                ]
                              }
                            },
                            "datasourceUid": "fegls9d2ka48wb",
                            "datasourceName": "grafana-azure-monitor-datasource"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "name": "itemId",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {
                      "links": [
                        {
                          "title": "Explore Trace Logs",
                          "internal": {
                            "query": {
                              "refId": "",
                              "queryType": "Azure Log Analytics",
                              "azureLogAnalytics": {
                                "query": "union availabilityResults,\ncustomEvents,\ndependencies,\nexceptions,\npageViews,\nrequests,\ntraces\n| where operation_Id == \"${__data.fields.traceID}\"",
                                "resources": [
                                  "/subscriptions/<subscription-id>/resourceGroups/azure-tracing-demo/providers/Microsoft.Insights/components/azure-tracing-demo"
                                ]
                              }
                            },
                            "datasourceUid": "fegls9d2ka48wb",
                            "datasourceName": "grafana-azure-monitor-datasource"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "name": "resource",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {
                      "links": [
                        {
                          "title": "Explore Trace Logs",
                          "internal": {
                            "query": {
                              "refId": "",
                              "queryType": "Azure Log Analytics",
                              "azureLogAnalytics": {
                                "query": "union availabilityResults,\ncustomEvents,\ndependencies,\nexceptions,\npageViews,\nrequests,\ntraces\n| where operation_Id == \"${__data.fields.traceID}\"",
                                "resources": [
                                  "/subscriptions/<subscription-id>/resourceGroups/azure-tracing-demo/providers/Microsoft.Insights/components/azure-tracing-demo"
                                ]
                              }
                            },
                            "datasourceUid": "fegls9d2ka48wb",
                            "datasourceName": "grafana-azure-monitor-datasource"
                          }
                        }
                      ]
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1742746724446
                  ],
                  [
                    "dependency"
                  ],
                  [
                    "serviceName"
                  ],
                  [
                    1
                  ],
                  [
                    "4ef53649-416a-4949-b8f7-885892a32cdb"
                  ],
                  [
                    "983b3c66-fdf7-451e-b57c-0cac818d796e"
                  ],
                  [
                    "4ef53649-416a-4949-b8f7-885892a32cdb"
                  ],
                  [
                    "operationName"
                  ],
                  [
                    [
                      {
                        "value": "MBA",
                        "key": "cloud_RoleInstance"
                      },
                      {
                        "value": "serviceName",
                        "key": "cloud_RoleName"
                      }
                    ]
                  ],
                  [
                    [
                      {
                        "value": "99e51199-3e12-49e2-92f9-5c8daba8a3c3",
                        "key": "appId"
                      },
                      {
                        "value": "/subscriptions/<subscription-id>/resourcegroups/azure-tracing-demo/providers/microsoft.insights/components/azure-tracing-demo",
                        "key": "appName"
                      },
                      {
                        "value": "Go-http-client 2.0",
                        "key": "client_Browser"
                      },
                      {
                        "value": "Minato-Ku (Tokyo)",
                        "key": "client_City"
                      },
                      {
                        "value": "Japan",
                        "key": "client_CountryOrRegion"
                      },
                      {
                        "value": "0.0.0.0",
                        "key": "client_IP"
                      },
                      {
                        "value": "Other",
                        "key": "client_Model"
                      },
                      {
                        "value": "darwin",
                        "key": "client_OS"
                      },
                      {
                        "value": "Tokyo",
                        "key": "client_StateOrProvince"
                      },
                      {
                        "value": "PC",
                        "key": "client_Type"
                      },
                      {
                        "value": 1,
                        "key": "duration"
                      },
                      {
                        "value": false,
                        "key": "error"
                      },
                      {
                        "value": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                        "key": "iKey"
                      },
                      {
                        "value": 1,
                        "key": "itemCount"
                      },
                      {
                        "value": "8a52c1d5-0802-11f0-9aea-002248321622",
                        "key": "itemId"
                      },
                      {
                        "value": "dependency",
                        "key": "itemType"
                      },
                      {
                        "value": "operationName",
                        "key": "name"
                      },
                      {
                        "value": "4ef53649-416a-4949-b8f7-885892a32cdb",
                        "key": "operation_Id"
                      },
                      {
                        "value": "4ef53649-416a-4949-b8f7-885892a32cdb",
                        "key": "operation_ParentId"
                      },
                      {
                        "value": "<250ms",
                        "key": "performanceBucket"
                      },
                      {
                        "value": "go:0.4.4",
                        "key": "sdkVersion"
                      },
                      {
                        "value": "True",
                        "key": "success"
                      },
                      {
                        "value": "operationName",
                        "key": "target"
                      },
                      {
                        "value": "2025-03-23T16:18:44.4466690Z",
                        "key": "timestamp"
                      },
                      {
                        "value": "Redis",
                        "key": "type"
                      }
                    ]
                  ],
                  [
                    "8a52c1d5-0802-11f0-9aea-002248321622"
                  ],
                  [
                    "/subscriptions/<subscription-id>/resourcegroups/azure-tracing-demo/providers/microsoft.insights/components/azure-tracing-demo"
                  ]
                ],
                "nanos": [
                  [
                    669000
                  ],
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null
                ]
              }
            }
          ]
        }
      ],
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "options": {
        "spanFilters": {
          "matchesOnly": false,
          "criticalPathOnly": false,
          "serviceNameOperator": "=",
          "spanNameOperator": "="
        }
      }
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >traces @ 9.2.0</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[grafana-azure-monitor-datasource]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 1 frames, 12 fields, 1 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>Grafana v9.2.0 (NA) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"id\": 1,\n  \"type\": \"traces\",\n  \"title\": \"New Panel\",\n  \"gridPos\": {\n    \"x\": 0,\n    \"y\": 0,\n    \"h\": 8,\n    \"w\": 12\n  },\n  \"fieldConfig\": {\n    \"defaults\": {},\n    \"overrides\": []\n  },\n  \"pluginVersion\": \"9.2.0\",\n  \"targets\": [\n    {\n      \"refId\": \"A\",\n      \"datasource\": {\n        \"type\": \"grafana-azure-monitor-datasource\",\n        \"uid\": \"fegls9d2ka48wb\"\n      },\n      \"queryType\": \"Azure Traces\",\n      \"azureTraces\": {\n        \"resultFormat\": \"trace\",\n        \"traceTypes\": [\n          \"availabilityResults\",\n          \"dependencies\",\n          \"customEvents\",\n          \"exceptions\",\n          \"pageViews\",\n          \"requests\",\n          \"traces\"\n        ],\n        \"resources\": [\n          \"/subscriptions/<subscription-id>/resourceGroups/azure-tracing-demo/providers/Microsoft.Insights/components/azure-tracing-demo\"\n        ]\n      }\n    }\n  ],\n  \"datasource\": {\n    \"type\": \"grafana-azure-monitor-datasource\",\n    \"uid\": \"fegls9d2ka48wb\"\n  },\n  \"options\": {\n    \"spanFilters\": {\n      \"matchesOnly\": false,\n      \"criticalPathOnly\": false,\n      \"serviceNameOperator\": \"=\",\n      \"spanNameOperator\": \"=\"\n    }\n  }\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: New Panel // 2025-03-24 01:55:10",
  "tags": [
    "debug",
    "debug-traces"
  ],
  "time": {
    "from": "2025-03-23T15:54:46.166Z",
    "to": "2025-03-23T16:54:46.166Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana: v11.5.2 (git commit: 73436e3d55f384a85417ab47a8af56510b710d8e)
OS: macOS 14.7.2
Browser: Google Chrome 134.0.6998.118

### Grafana platform?

Other

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by aangelisc**
Modifies the logic for adding links to fields when the trace visualization is used. Previously, the link would be added to every field in the frame but this led to duplicated links.

This logic now adds the link to the first field and breaks out of the loop early to avoid duplicating links.

Fixes #102676

### CODE REVIEW

File: pkg/tsdb/azuremonitor/loganalytics/utils.go [hunk 1]
```diff
@@ -39,7 +44,7 @@ func AddConfigLinks(frame data.Frame, dl string, title *string) data.Frame {
 		URL:         dl,
 	}
 
-	frame = AddCustomDataLink(frame, deepLink)
+	frame = AddCustomDataLink(frame, deepLink, false)
```
Comment (beejeebus) [inline pkg/tsdb/azuremonitor/loganalytics/utils.go]: not a blocking issue, but it would read easier at the callsites if there were some named variables like:
```
const SingleField bool = true
const MultipleField bool = false
```

**Review by beejeebus — APPROVED** [review]
