### PR TITLE
Stat Panel: Fix issue with clipping text values

### LINKED ISSUE #59766: Stat panel incorrectly measures text causing it to clip
**What happened**:
Auto-Fontsize doesn't work properly. The text is cut off.
image

**What you expected to happen**:
Text resize proberly

**How to reproduce it (as minimally and precisely as possible)**:
Here is the JSON from my Stat-Panel.
Here I just went for a "Select 'blabla'" request to SQL for demo-purpose.
```
{
      "datasource": {
        "type": "mssql",
        "uid": "6IyHxWQ7z"
      },
      "description": "",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 2,
        "w": 4,
        "x": 0,
        "y": 9
      },
      "id": 103,
      "options": {
        "colorMode": "background",
        "graphMode": "none",
        "justifyMode": "auto",
        "orientation": "horizontal",
        "reduceOptions": {
          "calcs": [
            "last"
          ],
          "fields": "/^Value$/",
          "values": true
        },
        "text": {},
        "textMode": "value"
      },
      "pluginVersion": "9.2.7",
      "targets": [
        {
          "datasource": {
            "type": "mssql",
            "uid": "6IyHxWQ7z"
          },
          "editorMode": "code",
          "format": "table",
          "rawQuery": true,
          "rawSql": "SELECT 'Ausreichend Batterie'",
          "refId": "A",
          "sql": {
            "columns": [
              {
                "parameters": [],
                "type": "function"
              }
            ],
            "groupBy": [
              {
                "property": {
                  "type": "string"
                },
                "type": "groupBy"
              }
            ],
            "limit": 50
          }
        }
      ],
      "transformations": [],
      "type": "stat"
    },
```
You may need to play with the size of the resolution (2582px*800px in my case)

**Anything else we need to know?**:
When I disable the "Font-Weight" in the css-settings on the "elements"-tab in the "resizing" is working the intended way.
image
image

**Environment**:
- Grafana version: v 9.2.7
- Data source type & version: irrelevant
- OS Grafana is installed on: Linux
- User OS & Browser: All (Opera, Chrome, Edge, ...)
- Grafana plugins: irrelevant
- Others: -

### PR DESCRIPTION
**Pull request by JoaoSilvaGrafana**
**What is this feature?**

Currently the Stat Panel does not always calculate the right font size for a value, it can sometimes clip the text:
Screenshot 2023-03-07 at 11 35 41

This is because the calculation for the font size was not taking into consideration that the font weight for that text was different (500 in this case), so we added an extra optional argument to the `measureText` function to pass in a different `fontWeight`, which solves the issue:
Screenshot 2023-03-07 at 11 36 52

**Why do we need this feature?**

So text values in Stat Panel are always visible.

**Who is this feature for?**

Anyone using Stat Panel

**Which issue(s) does this PR fix?**:

Fixes #59766

**Special notes for your reviewer**:

We also checked other places that used `measureText` and `calculateFontSize` but those all had 400 as a font-weight.

### CODE REVIEW

**Review by ashharrison90 — APPROVED** [review]
good mob 🔱

File: packages/grafana-ui/src/components/BigValue/BigValueLayout.tsx [hunk 1]
```diff
@@ -398,7 +405,9 @@ export class StackedWithNoChartLayout extends BigValueLayout {
         this.valueToAlignTo,
         this.maxTextWidth,
         this.maxTextHeight - titleHeight,
-        LINE_HEIGHT
+        LINE_HEIGHT,
+        undefined,
```
Comment (tskarhed) [inline packages/grafana-ui/src/components/BigValue/BigValueLayout.tsx:409]: Is `maxSize` commonly used? I assume that we don't want to change the order of the parameters

Comment (JoaoSilvaGrafana) [reply packages/grafana-ui/src/components/BigValue/BigValueLayout.tsx:409]: I think they're used the exact same amount of times, so probably leave it like this? 🤷
