### PR TITLE
Tempo: TraceQL syntax highlighting improvements

### LINKED ISSUE #61951: [Tempo] Float constants in TraceQL not correctly highlighted
**What happened**:
Float values are not correctly highlighted when typing TraceQL queries. Everything after the dot is black. Presumably this should be the same shade as the integer part of the number?

image

**What you expected to happen**:

Consistent syntax highlighting for all parts of float value.

**How to reproduce it (as minimally and precisely as possible)**:

Type a float value in a TraceQL editor.

**Environment**:
- Grafana version: v9.4.0-49942pre
- Data source type & version: Tempo
- OS Grafana is installed on: Linux/K8s
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by adrapereira**
**What is this feature?**

This PR improves the TraceQL syntax highlighting by adding rules to highlight tags on the right had side of an operator to colour them in the same way as the tags on the left hand side, and to highlight durations in the same way as numbers (1.2s, 100ms, etc.). 

Additionally, it updates the number rules to accurately highlight floating point values, like 123.4.

image

**Which issue(s) does this PR fix?**:

Fixes #61951

### CODE REVIEW

File: public/app/plugins/datasource/tempo/traceql/traceql.ts [hunk 1]
```diff
@@ -92,14 +94,13 @@ export const language = {
...
-      [/\d*\d+[eE]([\-+]?\d+)?(@floatsuffix)/, 'number.float'],
-      [/\d*\.\d+([eE][\-+]?\d+)?(@floatsuffix)/, 'number.float'],
-      [/0[xX][0-9a-fA-F']*[0-9a-fA-F](@integersuffix)/, 'number.hex'],
-      [/0[0-7']*[0-7](@integersuffix)/, 'number.octal'],
-      [/0[bB][0-1']*[0-1](@integersuffix)/, 'number.binary'],
-      [/\d[\d']*\d(@integersuffix)/, 'number'],
-      [/\d(@integersuffix)/, 'number'],
+      [/(@digits)[eE]([\-+]?(@digits))?[fFdD]?/, 'number.float'],
+      [/(@digits)\.(@digits)([eE][\-+]?(@digits))?[fFdD]?/, 'number.float'],
+      [/0[xX](@hexdigits)[Ll]?/, 'number.hex'],
```
Comment (joey-grafana) [inline public/app/plugins/datasource/tempo/traceql/traceql.ts:99]: I don't think this is highlighting hex numbers properly or if we even need it?

**Review by joey-grafana — APPROVED** [review]
