### PR TITLE
Fix anonymous usage stats for authentication types

### LINKED ISSUE #13240: Anonymous usage stats for authentication types
We would like to extend the anonymous usage stats to gather what kind of authentication types is enabled or not.

Suggested stats:
* Anonymous auth enabled
* Basic auth enabled
* LDAP auth enabled
* Auth proxy enabled 
* OAuth Generic enabled
* OAuth Github enabled
* OAuth Gitlab enabled
* OAuth Google enabled

### PR DESCRIPTION
**Pull request by marefr**
Fixes #13240 

Unsure how to send these metrics. My suggestion is to send them as boolean properties. 

For counting auth usage you'll filter in Elasticsearch on certain auth type and do a document count. No idea if we need to do anything specific to with ES index mapping? What happens with Graphite stats?

Feedback appreciated

### CODE REVIEW

**Comment by torkelo** [comment]
This looks great

File: pkg/metrics/metrics.go [hunk 1]
```diff
@@ -450,6 +452,15 @@ func sendUsageStats() {
 		metrics["stats.alert_notifiers."+stats.Type+".count"] = stats.Count
 	}
 
+	auth["anonymous_enabled"] = setting.AnonymousEnabled
```
Comment (bergquist) [inline pkg/metrics/metrics.go]: I'm not sure how ES store bool values. But I think it would be better to store these values as numbers since it makes it easier to aggregate it with `Sum`.

**Comment by marefr** [comment]
Changed to only send metrics `stats.auth_enabled.anonymous.count`. @torkelo is this enough for now?

**Comment by torkelo** [comment]
Yes, this should work great
