### PR TITLE
Alerting: Fix the silence url's matcher parameters

### LINKED ISSUE #43581: Unified Alerting: UI crashes when user silence an alert with comma in the name
**What happened**:
Grafana UI crashes when a user tries to create a silence for an alert rule by clicking on "Silence" button (see screenshot)

which results in the following error 
<details><summary>Error</summary>

NOTE: stack trace is from devenv

```
An unexpected error happened
Error: Invalid matcher: with comma

SilencesEditor@http://localhost:3000/public/build/AlertSilences.js:1341:24
Route@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:429345:29
Switch@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:429547:29
div
PageContents@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:163218:22
div
div
div
Scrollbars@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:641384:24
CustomScrollbar@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:119255:25
div
Page@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:163158:7
AlertingPageWrapper@http://localhost:3000/public/build/AlertSilences.js:203:29
Silences@http://localhost:3000/public/build/AlertSilences.js:99:154
ErrorBoundary@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:125571:1
ErrorBoundaryAlert@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:125612:1
WithErrorBoundary
LoadableComponent@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:426346:22
GrafanaRoute@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:172546:1
Route@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:429345:29
Switch@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:429547:29
main
Router@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:428976:30
div
ModalsProvider@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:135796:5
ThemeProvider@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:177053:23
ErrorBoundary@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:125571:1
ErrorBoundaryAlert@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:125612:1
Provider@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:426766:15
AppWrapper@http://localhost:3000/public/build/app.js?dd6672dd74dc26ceafd1:156561:5
```
</details>

The UI seems to treat everything after the comma as another matching expression.

Manually creating a silence with the silence works well.

**What you expected to happen**:

Grafana does not crash

**How to reproduce it (as minimally and precisely as possible)**:
- create an alert rule with a name that contains a comma.
- go to "Alert rules" page, find the rule and click on the button "Silence".
- 💥 
**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: Windows, Firefox 95.0.2
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by konrad147**
**What this PR does / why we need it**:
This PR fixes the Silence URL matcher parameters. Previously, a comma was used to separate each matcher rule, but this caused problems in alert rules which contain a comma in their names. This PR changes that and use a separate `matcher` parameter for each matcher rule
image

**Which issue(s) this PR fixes**:
Fixes #43581 

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/alerting/unified/components/silences/SilencesEditor.tsx [hunk 1]
```diff
@@ -89,14 +87,16 @@ const getDefaultFormValues = (queryParams: UrlQueryMap, silence?: Silence): Sile
...
+      ...defaultsFromQuery(searchParams),
     };
   }
 };
 
 export const SilencesEditor: FC<Props> = ({ silence, alertManagerSourceName }) => {
-  const [queryParams] = useQueryParams();
-  const defaultValues = useMemo(() => getDefaultFormValues(queryParams, silence), [silence, queryParams]);
+  const [urlSearchParams] = useURLSearchParams();
+  console.log(urlSearchParams);
```
Comment (peterholmberg) [inline public/app/features/alerting/unified/components/silences/SilencesEditor.tsx:97]: ops :)

**Review by peterholmberg — APPROVED** [review]
Looks good, just found a small nit ;)

File: public/app/features/alerting/unified/components/silences/SilencesEditor.tsx (hunk 1 above)
Comment (konrad147) [reply public/app/features/alerting/unified/components/silences/SilencesEditor.tsx]: Fixed. Shouldn't Eslint catch it on pre-commit or pre-push actions?

Comment (gillesdemey) [reply public/app/features/alerting/unified/components/silences/SilencesEditor.tsx]: It looks like those are allowed by default https://github.com/grafana/eslint-config-grafana/blob/master/index.js#L35

A quick code grep shows quite a few existing uses of `console.<fn>` spread throughout the `public/` folder.

File: public/app/features/alerting/unified/utils/matchers.ts [hunk 2]
```diff
@@ -2,21 +2,29 @@ import { Matcher } from 'app/plugins/datasource/alertmanager/types';
...
-    .filter((x) => !!x.trim())
-    .map((x) => parseMatcher(x.trim()));
+// Parses a list of entries like like "['foo=bar', 'baz=~bad*']" into SilenceMatcher[]
+export function parseQueryParamMatchers(matcherPairs: string[]): Matcher[] {
+  const parsedMatchers = matcherPairs.filter((x) => !!x.trim()).map((x) => parseMatcher(x.trim()));
+
+  // Due to migration, old alert rules might have a duplicated alertname label
+  // To handle that case want to filter out duplicates and make sure there are only unique labels
+  const uniqueMatchersMap = new Map<string, Matcher>();
+  parsedMatchers.forEach(
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/utils/matchers.ts:12]: nit: I'm a personal fan of `lodash` to improve code readability and cut down on boilerplate code.

Something like `return uniqBy(parsedMatchers, (matcher) => matcher.name);` should produce the same output.

File: public/app/features/alerting/unified/utils/matchers.ts [hunk 3]
```diff
@@ -2,21 +2,29 @@ import { Matcher } from 'app/plugins/datasource/alertmanager/types';
...
-      })
-      .join(',')
-  )}`;
+  const validMatcherLabels = Object.entries(labels).filter(
+    ([labelKey]) => !(labelKey.startsWith('__') && labelKey.endsWith('__'))
+  );
+
+  const matcherUrlParams = new URLSearchParams();
+  validMatcherLabels.forEach(([labelKey, labelValue]) =>
+    matcherUrlParams.append('matchers', `${labelKey}=${labelValue}`)
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/utils/matchers.ts:26]: nit: this should probably be the singular `matcher` instead of using the plural `matchers`

**Review by gillesdemey — APPROVED** [review]
Great work! Just a few small nits that are not blockers for merging this.
