### PR TITLE
PublicDashboards: Dont support exemplars

### LINKED ISSUE #54035: Public dashboards add "exemplar" metric to panels
**What happened**: I made an dashboard public accessible, but in the public version there are metrics ("exemplar") displayed which are not in the non-public one.

Public
image
Non-Public
image

**What you expected to happen**: No new metrics to show up.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard
2. Make it public
3. Compare displayed metrics between public and non-public version

**Environment**:
- Grafana version: 9.1.0
- Data source type & version: victoriametrics ~~1.78.0~~ 1.80.0 acting as prometheus ds
- OS Grafana is installed on: Archlinux (repo package)
- User OS & Browser: Firefox 103.0.2 on (Arch-)Linux
- Grafana plugins: Grafana Image Renderer

### PR DESCRIPTION
**Pull request by owensmallwood**
**Problem**
Exemplars are handled within the Prometheus datasource on the frontend. There's a lot of code that handles those transformations, and currently, it's low priority to add exemplar support for our `PublicDashboardDatasource`.

**Solution**
When gathering queries on the backend for public dashboards, we remove the exemplar property if it exists.

**Notes**
I moved the dashboard_queries into the publicdashboards service because they're only used for public dashboards.

fixes https://github.com/grafana/grafana/issues/54035

### CODE REVIEW

File: pkg/services/publicdashboards/models/dashboard_queries.go [hunk 1]
```diff
@@ -1,4 +1,4 @@
-package query
+package models
```
Comment (evictorero) [inline pkg/services/publicdashboards/models/dashboard_queries.go:1]: It has a lot of logic and functions. Wouldn't be better to put in `service` package instead of `models`?

File: pkg/services/query/query.go [hunk 2]
```diff
@@ -16,7 +16,7 @@ import (
 	"github.com/grafana/grafana/pkg/plugins/adapters"
 	"github.com/grafana/grafana/pkg/services/datasources"
 	"github.com/grafana/grafana/pkg/services/oauthtoken"
-	queryModels "github.com/grafana/grafana/pkg/services/query/models"
+	publicDashboards "github.com/grafana/grafana/pkg/services/publicdashboards/models"
```
Comment (evictorero) [inline pkg/services/query/query.go:19]: This alias is different from the package name, should be similar. This could be because the actual `models` name is not a good fit for this package?

File: public/app/plugins/datasource/prometheus/result_transformer.ts [hunk 3]
```diff
@@ -65,7 +65,7 @@ const isHeatmapResult = (dataFrame: DataFrame, options: DataQueryRequest<PromQue
   return target?.format === 'heatmap';
 };
 
-// V2 result trasnformer used to transform query results from queries that were run trough prometheus backend
+// V2 result transformer used to transform query results from queries that were run through prometheus backend
```
Comment (evictorero) [inline public/app/plugins/datasource/prometheus/result_transformer.ts:68]: Good catch 😎

File: pkg/services/publicdashboards/models/dashboard_queries.go (hunk 1 above)
Comment (owensmallwood) [reply pkg/services/publicdashboards/models/dashboard_queries.go:1]: What kind of things should we store in the models folder? Just struct types?

File: pkg/services/query/query.go (hunk 2 above)
Comment (owensmallwood) [reply pkg/services/query/query.go:19]: Naming is hard, lol. They're functions that work with dashboard queries within the public dashboards domain. What about `PublicDashboardQueries`?

File: pkg/services/publicdashboards/models/dashboard_queries.go (hunk 1 above)
Comment (evictorero) [reply pkg/services/publicdashboards/models/dashboard_queries.go:1]: I would say structs, interfaces, some getters/setters or small functions related to those structs. These functions seems more related to the service than the models

File: pkg/services/query/query.go (hunk 2 above)
Comment (evictorero) [reply pkg/services/query/query.go:19]: It is! I think it depends on whether we are keeping these in the models package or not. Did you consider adding them to the service instead of models?

**Comment by evictorero** [comment]
nit related to the title: The area should be one word in camel case and the description should start with capital letter.
`PublicDashboards: Dont support exemplars`

File: pkg/services/publicdashboards/models/dashboard_queries.go (hunk 1 above)
Comment (owensmallwood) [reply pkg/services/publicdashboards/models/dashboard_queries.go:1]: Sounds good. Wasn't sure what our standard was. I'll move these into the service package

File: pkg/services/query/query.go (hunk 2 above)
Comment (owensmallwood) [reply pkg/services/query/query.go:19]: Yeah, I'm going to move them into the service package. I'll update the name to reflect that better

**Review by evictorero — APPROVED** [review]
LGTM!

**Review by evictorero — APPROVED** [review]
LGTM!
