### PR TITLE
Suggestions: Fix no data scenario error

### LINKED ISSUE #118728: Suggestions: Error for no-data scenario
Repro step:
- with `newVizSuggestions` flag turned off
- from a new or existing panel, change the scenario to "No Data Points"
- From the Suggestions tab, click on suggestions

What should happen:
Clicking on a suggestion should apply the suggestion and redirect to panel options

What happens:

- We're not being redirected to panel options
- The page is crashing

https://github.com/user-attachments/assets/39317b06-3cc9-4e66-8c4d-01ac910b267c

### PR DESCRIPTION
**Pull request by drew08t**
When `newVizSuggestions` is set to `false`, for no data scenario, selecting a suggestion was not opening the options. This was leading to a crash upon switching panel types.

Before:
Feb-26-2026 00-04-28

After:
Feb-26-2026 00-02-45

Fixes https://github.com/grafana/grafana/issues/118728

### CODE REVIEW

File: public/app/features/panel/components/VizTypePicker/VisualizationSuggestions.tsx [hunk 1]
```diff
@@ -299,7 +299,7 @@ export function VisualizationSuggestions({ onChange, data, panel, searchQuery, i
                   suggestion={suggestion}
                   width={width}
                   tabIndex={index}
-                  onClick={() => applySuggestion(suggestion, index)}
+                  onClick={() => applySuggestion(suggestion, index, false, true)}
```
Comment (drew08t) [inline public/app/features/panel/components/VizTypePicker/VisualizationSuggestions.tsx:302]: This update ensures that when `isNewVizSuggestionsEnabled` is false, `shouldCloseVizPicker` passes as true when applying the suggestion.

**Review by adela-almasan — APPROVED** [review]

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/22451663093)
- Version: 13.0.0-22451663093
