### PR TITLE
CI: Allow overwriting of existing GitHub release assets

### LINKED ISSUE #63698: CI: publish-github-* pipeline should be idempotent
**What happened**:

The pipeline creating a GitHub release and uploading relevant artifacts fails if an artifact with the same name is already present.

**What you expected to happen**:

The artifact should be replaced.

**How to reproduce it (as minimally and precisely as possible)**:

Promote the same release version multiple times.

**Anything else we need to know?**:

The whole pipeline should act idempotently and not only supported working with existing GitHub releases (which it already does) but also with existing artifacts in those releases (which it currently does not). This is relevant for situations where we need to restart a pipeline due to subsequent failures.

### PR DESCRIPTION
**Pull request by zerok**
Fixes #63698

### CODE REVIEW

File: pkg/build/cmd/publishgithub.go [hunk 1]
```diff
@@ -41,9 +43,10 @@ var (
 	errReleaseNotFound = errors.New(`release not found, use "--create" to create the release`)
 )
 
-func PublishGithub(ctx *cli.Context) error {
+func PublishGithub(cctx *cli.Context) error {
```
Comment (guicaulada) [inline pkg/build/cmd/publishgithub.go:46]: It looks good to me, the only nit I have is that this cctx variable is a little too similar to ctx could make it difficult to understand the code later, maybe it would be better to change it to `cliCtx` ?

Comment (kminehart) [reply pkg/build/cmd/publishgithub.go:46]: I usually prefer `c` for this variable.

Comment (zerok) [reply pkg/build/cmd/publishgithub.go]: Personally I'd prefer going with cliCtx but since we already have `c` in various other places, let's move that discussion somewhere else 🙂 I'll look into how we can implement a linter around these conventions so that they are picked up automatically.

**Review by ricky-undeadcoders — APPROVED** [review]
