### PR TITLE
Azure Monitor: Add select all subscription option for ARG queries

### LINKED ISSUE #71034: AzureMonitor: Add `All` option for subscriptions in ARG queries
### 
# What went wrong?

Before #66890 was merged users could create an ARG query with the subscription field empty that would lead to querying all subscriptions. However, this led to some unexpected UI side-effects that the original PR fixed. However, it is clear users would like the ability to query all subscriptions in both Explore and Alerting which do not support template variables. An `All` option should be added to allow this functionality.

### 
# How do we reproduce it?

Attempt to query all subscriptions in an ARG query.

### 
# What Grafana version are you using?

Latest

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by alyssajoyner**
In order to select all subscriptions, users would have to manually select all the subscriptions. Now, there is a select all option that allow for easy querying of all subscriptions. It also updates all corresponding testing.

Closes #71034

### CODE REVIEW

**Review by bossinc — APPROVED** [review]
Nice!

File: public/app/plugins/datasource/azuremonitor/components/ArgQueryEditor/ArgQueryEditor.tsx [hunk 1]
```diff
@@ -57,8 +57,11 @@ const ArgQueryEditor = ({
     datasource
       .getSubscriptions()
       .then((results) => {
+        const selectAllSubscriptionOption = [
+          { label: 'Select all subscriptions', value: 'Select all subscriptions', description: 'Select all' },
```
Comment (aangelisc) [inline public/app/plugins/datasource/azuremonitor/components/ArgQueryEditor/ArgQueryEditor.tsx:61]: I _think_ ARG may select all subscriptions if the value in the query is `'*'`. Might be worth double checking this

Comment (MaxMelcher) [reply public/app/plugins/datasource/azuremonitor/components/ArgQueryEditor/ArgQueryEditor.tsx:61]: If that is a REST query under the hood, then leaving out the subscription parameter in the request will give you all subscriptions:
https://learn.microsoft.com/en-us/rest/api/azureresourcegraph/resourcegraph/resources/resources?view=rest-azureresourcegraph-resourcegraph-2022-10-01&tabs=HTTP

@alyssabull could you please also add the 'managementGroups' parameter?

Comment (aangelisc) [reply public/app/plugins/datasource/azuremonitor/components/ArgQueryEditor/ArgQueryEditor.tsx:61]: @MaxMelcher we do not currently support management groups. If the parameter were to be specified it'd be empty which I assume is the equivalent of not specifying.

Comment (alyssabull) [reply public/app/plugins/datasource/azuremonitor/components/ArgQueryEditor/ArgQueryEditor.tsx:61]: @aangelisc - I didn't get that to work and I'm not sure if it will since the query is expecting an array of subscription Ids. Let me know if I missed something
