### PR TITLE
DataLinks: Sanitize data/panel link URLs

### LINKED ISSUE #20974: XSS Javascript can run in Panel link URL
**What happened**: Javascript can be used within the link parameter of panel links (with malicious intentions). 

**What you expected to happen**: Only URL redirection is allowed (Sanitize input before saving (?)).

**How to reproduce it (as minimally and precisely as possible)**: 

1. Edit a panel. 
2. Go to the config tab.
3. Add a panel link.
4. Write javascript in the URL (i.e.: URL=> `alert(document.domain)`). 
5. Save.
6. Click the link from the panel.

**Anything else we need to know?**: The malicious user has to be able to edit a panel.

**Environment**:
- Grafana version: 6.3.5 (Did not check any new version, but I did not see any issue related to this)
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: N/A
- Grafana plugins: N/A (Default)
- Others: N/A

### PR DESCRIPTION
**Pull request by dprokop**
Fixes #20974

Changes introduced:
1. Both panel and data link urls are now sanitized using [@braintree/sanitize-url](https://github.com/braintree/sanitize-url). ~~Unfortunately the xss package we use can't do it on a string that is not a html~~. xss package that we use exposes `safeAttrValue` which could be used, but it also performs html escaping, which we want to delegate to components that actually render the html.
2. Added `sanitize-url.d.ts` file for the package type safety
3. Introduced possibility to mock app config in the tests

### CODE REVIEW

File: public/app/core/config.ts [hunk 1]
```diff
@@ -1,5 +1,18 @@
...
+let configMock: Partial<GrafanaBootConfig> | null = null;
+
 export default config;
+
+export const getConfig = () => {
+  return configMock || config;
+};
+
+export const mockConfig = (mock: Partial<GrafanaBootConfig>) => {
+  configMock = mock as GrafanaBootConfig;
```
Comment (dprokop) [inline public/app/core/config.ts]:
```suggestion
  configMock = mock;
```

File: public/app/features/panel/panel_ctrl.ts [hunk 2]
```diff
@@ -297,7 +297,7 @@ export class PanelCtrl {
 
     html += '</div>';
 
-    return html;
+    return config.disableSanitizeHtml ? html : sanitize(html);
```
Comment (dprokop) [inline public/app/features/panel/panel_ctrl.ts]: This sanitizes Angluar panel's links

File: public/app/core/config.ts [hunk 3]
```diff
@@ -1,5 +1,18 @@
...
+
+export const getConfig = () => {
+  return configMock || config;
+};
+
+export const mockConfig = (mock: Partial<GrafanaBootConfig>) => {
+  configMock = mock;
+  return () => {
+    configMock = null;
+  };
```
Comment (torkelo) [inline public/app/core/config.ts]: do we need the configMock object? Can't we have a setConfig function instead that set's the config variable?

File: public/app/features/panel/panellinks/specs/link_srv.test.ts [hunk 4]
```diff
@@ -137,4 +138,38 @@ describe('linkSrv', () => {
...
+              value: { time: dataPointMock.datapoint[0] },
+              text: 'Value',
+            },
+          },
+          {}
+        ).href;
+
+        // console.log(link);
+        expect(link).toBe(expected);
+        restoreConfig();
```
Comment (torkelo) [inline public/app/features/panel/panellinks/specs/link_srv.test.ts]: are not all jest test run in some form of isolation? do we need to the restoreConfig here?

**Review by torkelo — APPROVED** [review]
Looks good, the config mocking & reset feels a bit off , wonder if there is a simper way

**Review by hugohaggmark — APPROVED** [review]
LGTM!

File: public/app/core/config.ts (hunk 3 above)
Comment (dprokop) [reply public/app/core/config.ts]: @torkelo mind the type. This allows partial config mocking, only what you need for your test. That's why I opted for "mock" naming

File: public/app/features/panel/panellinks/specs/link_srv.test.ts (hunk 4 above)
Comment (dprokop) [reply public/app/features/panel/panellinks/specs/link_srv.test.ts]: Good point. In this case it is not necessary. But if other parts of `link_srv` were dependant on `config` and some other property than `disableSanitizeHtml` than not restoring the partial config might have caused the tests to fail. So I consider this more of a good practice rather than necessity. WDYT?

Comment (torkelo) [reply public/app/features/panel/panellinks/specs/link_srv.test.ts]: having to restore state after asserts looks to me like a smell / bad test design, I would add a common setup that set's the expected state. or have a common setup / scenario function that let you pass in expected config.

File: public/app/core/config.ts (hunk 3 above)
Comment (torkelo) [reply public/app/core/config.ts]: can't it be just
```
export function updateConfig(updates: Partial<GrafanaBootConfig>) {
   Object.assign(config, mock);
}
```

Comment (dprokop) [reply public/app/core/config.ts]: I like this!

Comment (torkelo) [reply public/app/core/config.ts]: This function: 

```ts
export const getConfig = () => {
  return configMock || config;
};
```

feels wrong to have in prod code.

**Comment by DanCech** [comment]
The function used by the sanitize library is https://github.com/leizongmin/js-xss/blob/master/lib/default.js#L147 which would avoid the additional import.

**Comment by dprokop** [comment]
@DanCech Thank you for this suggestion, I have removed the new dependency and used the xss one. 

@torkelo also updated with your suggestion about `updateConfig`

File: public/app/features/panel/panellinks/link_srv.ts [hunk 5]
```diff
@@ -209,7 +211,7 @@ export class LinkSrv implements LinkService {
         value: variablesQuery,
       },
     });
-
+    info.href = getConfig().disableSanitizeHtml ? info.href : sanitizeUrl(info.href);
```
Comment (DanCech) [inline public/app/features/panel/panellinks/link_srv.ts]: The only problem I have with this approach is that `info.href` will not only be sanitized against XSS-type urls, but it will also be html-escaped.  The problem with that is that when we now put that value into html, we have to be aware that it is already escaped, and not escape it again (It will contain `&lt;` in place of `<` and if we escape that again we'd end up with `&amp;lt;`).

Comment (dprokop) [reply public/app/features/panel/panellinks/link_srv.ts]: I think we can make this assumption as consumers of this data links model should not care about any escaping IMO. One problematic place could be the panel links corner where we actually do the escaping. I'm gonna take a look at that. 

But I'd rather have both sanitisation and escaping here  than scattering this logic across all of the components that use this model.

Comment (DanCech) [reply public/app/features/panel/panellinks/link_srv.ts]: I agree, the best solution would be for the service to handle sanitization so it gives a "trusted" url, but let the html-escaping happen when actually building the html so that it's clear what's going on and so that we don't have issues eg with react escaping the values when embedded in jsx

File: public/app/core/config.ts (hunk 3 above)
Comment (dprokop) [reply public/app/core/config.ts]: @torkelo it's no longer there

**Review by torkelo — APPROVED** [review]
Looks good!
