### PR TITLE
Elasticsearch: Fix passing of limit and datalinks to logs data frame

### LINKED ISSUE #68427: Explorer log panel with elasticsearch datasource: limit metadata is not displayed
### 
# What went wrong?

**What happened**:

When enabling the feature `enableElasticsearchBackendQuerying`, the metadata displayed at the top of the log panel of the explore is not present any more.

Here is an example of the text displayed: `Line limit:
500 reached, received logs cover 62.05% (2694h 38min 33sec) of your selected time range (4343h)`

**What did you expect to happen**:

 If the feature `enableElasticsearchBackendQuerying` is not enabled, the metadata is correctly displayed.

**Grafana version**

I'm using `10.1.0-116348pre-ubuntu`.

**Explanation**:

This is due to the fact that the backend code is not adding the metadata `limit` while the frontend code is adding it in the function `enhanceDataFrame`, see [ref](https://github.com/grafana/grafana/blob/ea0bf989cbeba06ebf1a2b71d4fa2cb67a029e26/public/app/plugins/datasource/elasticsearch/datasource.ts#L1035-L1040).

### 
# How do we reproduce it?

**Step 1**:

- Start Grafana with the feature `enableElasticsearchBackendQuerying` enabled.

**Step 2**:

- Open explore view, select an elasticsearch datasource, select the `logs` query type
- The query must match more documents than defined limit (default to 500).

**Step 3**:

- Go to the logs panel, no metadata text is displayed (expected text is like "500 reached, received logs cover...").

### 
# What Grafana version are you using?

10.1.0-116348pre-ubuntu

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

macOS Monterey

### User's Browser?

Google Chrome Version 112.0.5615.137 (Official Build) (arm64)

### Is this a Regression?

Yes

### Are Datasources involved?

Elasticsearch

### Anything else to add?

That's a small regression but... being able to get the total number of hits is really nice when you fire a query. Ideally, I would prefer to get directly the total number of hits but that's another issue :)

### PR DESCRIPTION
**Pull request by ivanahuckova**
In this PR we are fixing processing of log response on backend by adding `limit` to `meta` and also by enhancing `dataFrame` with data links. 

Similarly as with [searchWords](https://github.com/grafana/grafana/pull/63924/files), the dataFrames processed on backend have `searchWords` and `limit` in `meta.custom`. Therefore in `logsModel`, we need to make sure that we read at both places.

Fixes https://github.com/grafana/grafana/issues/68427

How to test:

- Run logs query with `enableElasticsearchBackendQuerying` enabled and make sure that in Explore, you see limit displayed in meta. 

image

### CODE REVIEW

File: public/app/core/logsModel.ts [hunk 1]
```diff
@@ -474,10 +474,11 @@ export function logSeriesToLogsModel(logSeries: DataFrame[], queries: DataQuery[
       kind: LogsMetaKind.LabelsMap,
     });
   }
-
-  const limits = logSeries.filter((series) => series.meta && series.meta.limit);
+  // Data sources that set up searchWords on backend use meta.custom.limit
+  // Data sources that set up searchWords trough frontend can use meta.limit
```
Comment (fmassot) [inline public/app/core/logsModel.ts:478]: Nitpick (=you can ignore):

```suggestion
  // Data sources that set up searchWords on backend use meta.custom.limit.
  // Data sources that set up searchWords through frontend can use meta.limit.
```

**Review by gabor — APPROVED** [review]
LGTM 👍 


there's one thing though.. 

i wonder if it's a good idea to read `frame.meta.custom` in `logsModel.ts`. we are kind of making certain `custom` values not-custom.
(i understand that we have been doing it before with the custom-frame-type and also with searchWords).

maybe we could just make sure the javascript-dataframe-meta is in sync with go-dataframe-meta instead.
and in the meantime, while we are waiting for that to be done,
we could have a small function in elastic/datasource.ts that transforms a "backend dataframe" to "frontend dataframe" by adjusting the location of `searchWords` and `limit`.

not sure.
wdyt?

**Comment by gabor** [comment]
> @gabor based on [this](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/data.ts#L91) I would expect it being the other way around. So after this PR is merged elasticsearch does it correctly and we should make sure that other data sources use `custom`.
> 
> image

oh, interesting, i did not see that comment there 👍
