### PR TITLE
CloudWatch Logs: Fix running logs queries with expressions

### LINKED ISSUE #63735: CloudWatch Logs: applying Reduce expression results in an error
**What happened**:
Originally reported [here](https://github.com/grafana/grafana/issues/63388):
>I have not been able to apply panel expressions (like Reduce) to CloudWatch Logs queries either: I always get an error.

**How to reproduce it (as minimally and precisely as possible)**:
1. Set up a CloudWatch Logs query
2. Add an expression and apply Reduce
Something like this:
Screenshot 2023-02-24 at 15 54 37

Result:
An error in the plugin has occurred

**Anything else we need to know?**:
Debugging has shown:
We observe that the expression causes it to go through a time series query [here](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/cloudwatch.go#L182)
and the error that it hits is [this one](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/models/cloudwatch_query.go#L295)

**Environment**:
- Grafana version: ~9.4.0
- Data source type & version: CloudWatch Logs

### PR DESCRIPTION
**Pull request by iwysiu**
Adds a header for expression queries (in the frontend this time!) Which gets passed back to cloudwatch to indicate that it should run the cloudwatch logs queries synchronously. If it gets run asynchronously, the expressions attempt to use the result of the first async response to build the results, and that response doesn't contain data.

This had to be redone because where the header was added in the old pr was buggy, but in this pr the header now gets added at the same time as all the other ones.
**Which issue(s) does this PR fix?**:

Fixes #63735

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.
- [ ] There are no known compatibility issues with older supported versions of Grafana, or plugins.
- [ ] It passes the [Hosted Grafana feature readiness review](https://docs.google.com/document/d/1QL9Ly8KnXzpb6ISbg49pTODRO5mhA5tkkfIZVX6pqQU/edit) for observability, scalability, performance, and security.

### CODE REVIEW

**Review by idastambuk — APPROVED** [review]

File: packages/grafana-runtime/src/utils/DataSourceWithBackend.ts [hunk 1]
```diff
@@ -197,14 +198,16 @@ class DataSourceWithBackend<
...
     }
 
+    const headers: Record<string, string> = {};
+    headers[PluginRequestHeaders.PluginID] = Array.from(pluginIDs).join(', ');
+    headers[PluginRequestHeaders.DatasourceUID] = Array.from(dsUIDs).join(', ');
+
     let url = '/api/ds/query';
     if (hasExpr) {
+      headers[PluginRequestHeaders.FromExpression] = 'true';
       url += '?expression=true';
```
Comment (andresmgot) [inline packages/grafana-runtime/src/utils/DataSourceWithBackend.ts:208]: if this is set now as a header, I don't think we need to use both the query param and the header. The only place I see that is using this is here:

https://github.com/grafana/grafana/blob/main/pkg/services/query/models.go#L59

So we could modify that to use the header. Am I missing some other usage @marefr ?

Comment (marefr) [reply packages/grafana-runtime/src/utils/DataSourceWithBackend.ts:208]: @ryantxu given #58082. Doesn't look like the query string is is use, but maybe there's still some magic use case of it in a "future multi-tenant world"?

**Review by sarahzinger — APPROVED** [review]
Looks good to me!

File: packages/grafana-runtime/src/utils/DataSourceWithBackend.ts (hunk 1 above)
Comment (iwysiu) [reply packages/grafana-runtime/src/utils/DataSourceWithBackend.ts:208]: I'm merging this, so a reminder to create a separate issue for this conversation
