### PR TITLE
Navigation: show breadcrumbs correctly when on the home page

### LINKED ISSUE #55553: Navigation: Breadcrumbs for Home dashboard are incorrect
default home page shows incorrect breadcrumbs:
image

this should probably just show `Home`

we also need to account for a different home dashboard being set via either the user or org preferences, or via config with
```
[dashboards]
default_home_dashboard_path = "devenv/dev-dashboards/panel-graph/graph_tests.json"
```

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- removes `Meta.IsHome` property
- constructs a Home `NavModelItem` in the backend
- sets the home item as the parent item for the root navTree elements when constructing the navTree instead of hardcoding it in the breadcrumbs
- refactors `buildBreadcrumbs` to build in reverse (starting with children) and stops as soon as the url matches the home item url (without query params).

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/55553

**Special notes for your reviewer**:

### CODE REVIEW

**Review by eledobleefe — COMMENTED** [review]
I run this branch in local and found this behaviour: when loading a different page the `breadcrumbs` show `Grafana` instead of the current page path. It doesn't happen every time. I don't know if this is strictly related to these changes but I wanted to let you know.


https://user-images.githubusercontent.com/65417731/192485792-3a764188-cf58-4e57-a439-cb9efbc15aff.mov

**Comment by ashharrison90** [comment]
@eledobleefe it's like that in main as well, it's just _slightly_ more noticeable here because i've removed the hardcoded `Home` breadcrumb. in main, the second breadcrumb flickers to `Grafana` as opposed to the first one on this branch. it's due to the default `sectionNav` set [here](https://github.com/grafana/grafana/blob/main/public/app/core/components/AppChrome/AppChromeService.tsx#L24)

File: public/app/core/selectors/navModel.ts [hunk 1]
```diff
@@ -35,7 +37,7 @@ export const getNavModel = (navIndex: NavIndex, id: string, fallback?: NavModel,
 };
 
 function getSectionRoot(node: NavModelItem): NavModelItem {
-  return node.parentItem ? getSectionRoot(node.parentItem) : node;
+  return node.parentItem && node.parentItem !== HOME_NAV ? getSectionRoot(node.parentItem) : node;
```
Comment (lpskdl) [inline public/app/core/selectors/navModel.ts:40]: will it be overkill or useless to use deep equality comparing `node.parentItem` and `HOME_NAV`?

Comment (ashharrison90) [reply public/app/core/selectors/navModel.ts:40]: hmmm, is there any time where it's not going to be the same object by reference? 🤔 otherwise it's just slower

Comment (lpskdl) [reply public/app/core/selectors/navModel.ts:40]: yeah . I'm not sure really if this is gonna be mutated somewhere :) or if we do allow node to be mutated somewhere which might cause unexpected result. Just asking as I am not sure it is mutated somewhere :)

Comment (ashharrison90) [reply public/app/core/selectors/navModel.ts:40]: could switch it to look at the id instead? e.g. `node.parentItem.id !== HOME_NAV.id`? 🤔

**Comment by eledobleefe** [comment]
> @eledobleefe it's like that in main as well, it's just _slightly_ more noticeable here because i've removed the hardcoded `Home` breadcrumb. in main, the second breadcrumb flickers to `Grafana` as opposed to the first one on this branch. it's due to the default `sectionNav` set [here](https://github.com/grafana/grafana/blob/main/public/app/core/components/AppChrome/AppChromeService.tsx#L24)

Thanks @ashharrison90. Apart from this and regarding the frontend files, it looks good! 🎉

File: public/app/core/selectors/navModel.ts (hunk 1 above)
Comment (lpskdl) [reply public/app/core/selectors/navModel.ts:40]: that should work :) thanks Ash

**Review by lpskdl — APPROVED** [review]
LGTM 🚀

**Review by eledobleefe — APPROVED** [review]
Looks good!!! 👍 
Although I think you also want some feedback from @grafana/backend-platform since you modified backend files. Can any of you take a look at this? Thanks!

File: pkg/api/dashboard.go [hunk 2]
```diff
@@ -152,7 +152,15 @@ func (hs *HTTPServer) GetDashboard(c *models.ReqContext) response.Response {
 		hs.getAnnotationPermissionsByScope(c, &annotationPermissions.Organization, accesscontrol.ScopeAnnotationsTypeOrganization)
 	}
 
+	prefsQuery := pref.GetPreferenceWithDefaultsQuery{OrgID: c.OrgID, UserID: c.SignedInUser.UserID, Teams: c.Teams}
+	preference, err := hs.preferenceService.GetWithDefaults(c.Req.Context(), &prefsQuery)
+	if err != nil {
+		preference.HomeDashboardID = 0
```
Comment (papagian) [inline pkg/api/dashboard.go:158]: I don't think we need this given that we return immediately in the next line without referencing `preference` anywhere.

File: pkg/api/dashboard.go [hunk 3]
```diff
@@ -152,7 +152,14 @@ func (hs *HTTPServer) GetDashboard(c *models.ReqContext) response.Response {
...
 	}
 
+	prefsQuery := pref.GetPreferenceWithDefaultsQuery{OrgID: c.OrgID, UserID: c.SignedInUser.UserID, Teams: c.Teams}
+	preference, err := hs.preferenceService.GetWithDefaults(c.Req.Context(), &prefsQuery)
+	if err != nil {
+		return response.Error(500, "Failed to get preferences", err)
+	}
+
 	meta := dtos.DashboardMeta{
+		IsHome:                 dash.Id == preference.HomeDashboardID,
```
Comment (torkelo) [inline pkg/api/dashboard.go:162]: not sure we should have this here, think the concept of a home dashboard maybe should be seen more as the "default" dashboard (since we redirect to it).

**Comment by ashharrison90** [comment]
@torkelo @marefr ok done a bunch of refactoring. now it builds a backend home object and puts it in the `navTree`. frontend then builds the `navIndex` and sets that home object as the parent for everything else. i've also adjusted the `buildBreadcrumbs` util to build in reverse (building children first) until it either hits the top or hits a `NavModelItem` with a url matching the home object. this way i think we should also be able to handle home pages set via the `home_page` config option (e.g. cloud home pages 😱 )

look forward to your thoughts on monday! 🥳

File: public/app/core/reducers/navModel.ts [hunk 4]
```diff
@@ -4,10 +4,19 @@ import { cloneDeep } from 'lodash';
...
   const rootNodes = cloneDeep(config.bootData.navTree as NavModelItem[]);
-  buildNavIndex(navIndex, rootNodes);
+  if (config.featureToggles.topnav) {
+    const homeNavIndex = rootNodes.findIndex((node) => node.id === HOME_NAV_ID);
+    const homeNav = rootNodes.splice(homeNavIndex, 1)[0];
+    buildNavIndex(navIndex, [homeNav]);
+    buildNavIndex(navIndex, rootNodes, homeNav);
+  } else {
+    buildNavIndex(navIndex, rootNodes);
+  }
```
Comment (torkelo) [inline public/app/core/reducers/navModel.ts:19]: not sure I understand this change

**Review by torkelo — COMMENTED** [review]
Looks great, just found one issue with dashboard breadcrumb when going back sub view 

and one question

File: public/app/features/dashboard/containers/DashboardPage.tsx [hunk 5]
```diff
@@ -424,11 +424,7 @@ function updateStatePageNavFromProps(props: Props, state: State): State {
   if (!pageNav || dashboard.title !== pageNav.text) {
     pageNav = {
       text: dashboard.title,
-      url: locationUtil.getUrlForPartial(props.history.location, {
-        editview: null,
-        editPanel: null,
-        viewPanel: null,
-      }),
+      url: props.history.location.pathname,
```
[the remark this answers is not in the document]
Comment (ashharrison90) [reply public/app/features/dashboard/containers/DashboardPage.tsx]: ah thank you, couldn't figure out why it was using `getUrlForPartial` - obvious in hindsight 🤦 have restored it and updated `buildBreadcrumbs` to ignore query params when matching instead 👍

File: public/app/core/reducers/navModel.ts (hunk 4 above)
Comment (ashharrison90) [reply public/app/core/reducers/navModel.ts:19]: @torkelo `buildNavIndex` takes an optional 3rd parameter which is the `parentItem` for the nodes you pass in the second parameter. 

when `topnav` is off, it's the same as it always was.

when `topnav` is on, we filter out the home node from the other nodes. we build the navIndex for the home node first, then build the navIndex for all the other nodes in the `navTree` setting the home node as the parent for each of them.

File: public/app/core/components/AppChrome/NavToolbar.tsx [hunk 6]
```diff
@@ -29,8 +31,9 @@ export function NavToolbar({
   onToggleSearchBar,
   onToggleKioskMode,
 }: Props) {
+  const homeNav = useSelector((state) => state.navIndex)[HOME_NAV_ID];
   const styles = useStyles2(getStyles);
-  const breadcrumbs = buildBreadcrumbs(sectionNav, pageNav);
+  const breadcrumbs = buildBreadcrumbs(homeNav, sectionNav, pageNav);
```
Comment (torkelo) [inline public/app/core/components/AppChrome/NavToolbar.tsx:36]: can we get home nav node from sectionNav.main.parentItem ?

**Review by torkelo — APPROVED** [review]
Feels like we navTree we give to frontend via config.bootData.navTree should not be an array and start with home node (and the root items should be children of this root node). Would simplify the logic a bit which feels a bit complex now with home node existing on the same level as root sections. 

But I think we can merge this and hopefully refactor that later

File: public/app/core/reducers/navModel.ts [hunk 7]
```diff
@@ -4,10 +4,19 @@ import { cloneDeep } from 'lodash';
...
 
+export const HOME_NAV_ID = 'home';
+
 export function buildInitialState(): NavIndex {
   const navIndex: NavIndex = {};
   const rootNodes = cloneDeep(config.bootData.navTree as NavModelItem[]);
-  buildNavIndex(navIndex, rootNodes);
+  if (config.featureToggles.topnav) {
+    const homeNavIndex = rootNodes.findIndex((node) => node.id === HOME_NAV_ID);
+    const homeNav = rootNodes.splice(homeNavIndex, 1)[0];
```
[the remark this answers is not in the document]
Comment (ashharrison90) [reply public/app/core/reducers/navModel.ts]: yes. i'll add a comment to make that clear 👍

File: public/app/core/components/AppChrome/NavToolbar.tsx (hunk 6 above)
Comment (ashharrison90) [reply public/app/core/components/AppChrome/NavToolbar.tsx:36]: @torkelo yes, but only if `sectionNav.main` is always an object directly below home. i guess that's what it _should_ be, but right now sometimes it's not. 

will leave this for a further refactor.

File: public/app/core/reducers/navModel.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (torkelo) [reply public/app/core/reducers/navModel.ts]: you could also I think skip removing it and just set homeNav.parentItem = null
