### PR TITLE
LogsTable: Inspect button fix

### LINKED ISSUE #115909: Explore: Logs table inspector shows empty modal
### What happened?

Empty modal: 

Image

### What did you expect to happen?

Inspect should show the log line even if it's not a currently visualized field

### Did this work before?

I think so

### How do we reproduce it?

1. View the table in a logs query (https://play.grafana.org/goto/bf9dx9aebquiof?orgId=1)
2. Remove the log line
3. Click inspect

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by gtk-grafana**
**What is this fix?**
Logs table fix for empty inspect button

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/grafana/issues/115909

**Special notes for your reviewer:**
Cleaned up the hover styles and some minor performance optimization (no longer calling getLineValue for each rendered cell on every render).

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/explore/Logs/LogsTableActionButtons.tsx [hunk 1]
```diff
@@ -35,19 +35,15 @@ export function LogsTableActionButtons(props: Props) {
   const [isInspecting, setIsInspecting] = useState(false);
   // Get logId from the table frame (frame), not the original logsFrame, because
   // the table frame is sorted/transformed and rowIndex refers to the table frame
-  const idFieldName = logsFrame?.idField?.name ?? 'id';
-  const idField = frame.fields.find((field) => field.name === idFieldName || field.name === 'id');
+  const idFieldName = logsFrame?.idField?.name ?? DATAPLANE_ID_NAME;
+  const idField = frame.fields.find((field) => field.name === idFieldName || field.name === DATAPLANE_ID_NAME);
   const logId = idField?.values[rowIndex];
+
   const getLineValue = () => {
```
Comment (matyax) [inline public/app/features/explore/Logs/LogsTableActionButtons.tsx:41]: It would be nice to memoize the component and these callbacks, since the table re-renders a lot, and this is one of the components re-rendered during those cycles.

**Review by matyax — APPROVED** [review]
✅

File: public/app/features/explore/Logs/LogsTableActionButtons.tsx (hunk 1 above)
Comment (gtk-grafana) [reply public/app/features/explore/Logs/LogsTableActionButtons.tsx:41]: Good catch yeah this component is constantly getting re-rendered, fixed in https://github.com/grafana/grafana/pull/115912/commits/0a72e7948c4c0658a4b95aab66cd066223d6f73a,

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/20784863274)
- Version: 12.4.0-20784863274
