### PR TITLE
Status history/State timeline: Support datalinks

### LINKED ISSUE #51667: Datalinks not working with status history and state timeline
**What happened**: Datalinks can be added to fields in status history and state timeline, but they are not displayed in the UI.

**What you expected to happen**: Datalinks should be displayed and usable in these dashboard as they can be defined.

**How to reproduce it (as minimally and precisely as possible)**:
Create a status history panel, add a datalink. When hovering the panel, only value is displayed, no datalinks

**Anything else we need to know?**:
The problem exists for some time and has been discussed [here](https://community.grafana.com/t/datalinks-not-showing-up-on-status-history-or-state-timeline/60193/3) and [here](https://community.grafana.com/t/data-links-on-status-history-not-working-8-1-1/51887). I already did a PR [here](https://github.com/grafana/grafana/pull/50226) and creating this issue to link it to a real issue.

**Environment**:
- Grafana version: at least since 8.1.1
- Data source type & version: Any
- OS Grafana is installed on: Any
- User OS & Browser: Any
- Grafana plugins: none
- Others:

### PR DESCRIPTION
**Pull request by jloupdef**
**What this PR does / why we need it**:
As discussed [here](https://community.grafana.com/t/datalinks-not-showing-up-on-status-history-or-state-timeline/60193/3) and [here](https://community.grafana.com/t/data-links-on-status-history-not-working-8-1-1/51887), there currently is a problem with datalinks not working on status history and state timeline (timeline/uplot based panel).

**Which issue(s) this PR fixes**:
Fixes #51667 

**Special notes for your reviewer**:
There is no current issue opened on the subject, the problem comes from the fact that the new status history and state timeline use uplot chart library, which itself use canvas in place of html elements. Because of this, the datalinks have not been added (as they usually rely on an html link) even if they can be defined when building the panel.

### CODE REVIEW

**Review by dprokop — CHANGES_REQUESTED** [review]
@jloupdef Thank you for your contribution! So glad someone picked this work up:)

There are a few things we need to change in order to proceed with this. I suggest following a similar approach to the one taken in i.e. Bar Chart panel that shows the data links within a tooltip. When one clicks on the visualization the tooltip becomes fixed making it possible to interact with the links. With that in place, we will be also able to provide multiple data links and not rely only on the first one defined in the options. Moreover, we will be able to use the native `a` element with `href` and `onClick` handlers rather than `window.open` handler that can be easily blocked by any ad blockers. 

For reference, this is how the bar chart handles data links:

https://user-images.githubusercontent.com/2376619/172153119-2c396ece-4b3f-4835-a2e4-571596ae224f.mov

And also looping in @leeoniya and @ryantxu who's been working on tooltips in Barchart, Geomap and Heatmap panels recently.

**Comment by jloupdef** [comment]
Thank you @dprokop for your feedback. Using tooltip will need much more work but I agree it would be a better solution. I will give it a try, it should not be too difficult as it is already been done on Heatmap as you said which rely on the same technology.

I am putting this PR as WIP (in the title) and will come back once work is done.

**Comment by jloupdef** [comment]
I changed everything using code from the other panels implementations. Let me know if it is good to you all.

**Comment by jloupdef** [comment]
The PR seems stale or blocked, what can I do to go further ? I think I did everything on my side, solution should be what was expected.
Thanks in advance.

**Comment by TheSkorm** [comment]
image
Not sure if I'm doing something wrong here but using this with series names in the link or title generates results for not just the field hovered over.

**Comment by jloupdef** [comment]
Thank you for your feedback @TheSkorm !
I took the code from other panel and just check with one serie, i revised my changes, fixed that and tested a little more thoroughly.
Everything should be good now !

**Comment by TheSkorm** [comment]
Thank you! Looks exactly like the change I did on my branch!

**Comment by jloupdef** [comment]
Don't know ever about this feature, but would not be surprised if it already exists. Ever way it is not directly linked to this PR. Let's hope some grafana dev check it and validate it soon 😁

**Comment by dprokop** [comment]
@jloupdef sorry for the delay. I'm looking into the PR as we speak and I'll get back with some feedback tomorrow.

**Review by dprokop — CHANGES_REQUESTED** [review]
@jloupdef Thanks again for the contribution. I've made some minor changes to the way the tooltip work and I've also synced with the latest changes on main that added possibility to create annotations in the state timeline panel (https://github.com/grafana/grafana/pull/47887).

I think this PR looks good, but I see two things that would be good to fix before landing this on main:
1. Navigating to edit mode with the tooltip open doesn't close the tooltip
2. Navigating back from edit mode to dashboard makes it impossible to click and open the tooltip anymore.

Both issues are shown in the video below:

https://user-images.githubusercontent.com/2376619/177514816-3af68c7e-d15a-4f9c-9895-5876d446ec07.mov

File: public/app/plugins/panel/state-timeline/StateTimelinePanel.tsx [hunk 1]
```diff
@@ -1,19 +1,22 @@
...
+import React, { useCallback, useMemo, useRef, useState } from 'react';
 
-import { DataFrame, FieldType, PanelProps } from '@grafana/data';
-import { TooltipPlugin, useTheme2, ZoomPlugin, usePanelContext } from '@grafana/ui';
+import { CartesianCoords2D, DataFrame, FieldType, PanelProps } from '@grafana/data';
+import { Portal, UPlotConfigBuilder, usePanelContext, useTheme2, VizTooltipContainer, ZoomPlugin } from '@grafana/ui';
+import { CloseButton } from 'app/core/components/CloseButton/CloseButton';
 import { getLastStreamingDataFramePacket } from 'app/features/live/data/StreamingDataFrame';
 
+import { HoverEvent, setupConfig } from '../barchart/config';
```
Comment (mdvictor) [inline public/app/plugins/panel/state-timeline/StateTimelinePanel.tsx:8]: I think the shared components will need to be moved somewhere else since they are used across multiple panels. My guess would be in `@grafana/data` and imported in all modified panels.

**Review by mdvictor — CHANGES_REQUESTED** [review]
Hey @jloupdef! This is some awesome work. Thank you for your contribution, this is a great addition to the codebase! I've mentioned a couple of things that would be nice if improved, but mainly the most important thing is related to what @dprokop also mentioned!

File: packages/grafana-ui/src/components/uPlot/config/setupUPlotConfig.ts [hunk 2]
```diff
@@ -16,14 +18,14 @@ type SetupConfigParams = {
...
-  setCoords: Dispatch<SetStateAction<CartesianCoords2D | null>>;
+  setCoords: Dispatch<SetStateAction<{ viewport: CartesianCoords2D; canvas: CartesianCoords2D } | null>>;
   setHover: Dispatch<SetStateAction<HoverEvent | undefined>>;
   isToolTipOpen: MutableRefObject<boolean>;
 };
 
 // This applies config hooks to setup tooltip listener. Ideally this could happen in the same `prepConfig` function
 // however the GraphNG structures do not allow access to the `setHover` callback
-export const setupConfig = ({
+export const setupUPlotConfig = ({
```
Comment (dprokop) [inline packages/grafana-ui/src/components/uPlot/config/setupUPlotConfig.ts:28]: Since this function is only about enabling the tooltip interaction I suggest renaming it to `addTooltipSupport` - and this should result in the file name change too.

**Review by dprokop — DISMISSED** [review]
All looks good now, I've added one minor comment to fix, and we should be good to merge this. Great contribution @jloupdef !

File: packages/grafana-ui/src/components/uPlot/config/setupUPlotConfig.ts (hunk 2 above)
Comment (jloupdef) [reply packages/grafana-ui/src/components/uPlot/config/setupUPlotConfig.ts]: I renamed it as suggested

**Comment by jloupdef** [comment]
@dprokop @mdvictor , everything should be good now.

**Review by mdvictor — APPROVED** [review]

**Comment by mdvictor** [comment]
Thank you for your awesome contribution @jloupdef. Merged in main!

**Comment by gfranco-replica** [comment]
Hello, is possible this fix introduced a regression?
The date/time on the tooltip was very useful to know the time for specific status about a process.

Screen Shot 2022-09-27 at 3 13 48 PM

After we upgraded last night I don't see anymore the date/time on the tooltip and we have to "guess" for what time it is, specially when the charts spawn several days with many data points

Screen Shot 2022-09-27 at 3 11 05 PM

**Comment by mdvictor** [comment]
Hey @gfranco-replica . This definitely seems like a bug, the date/time should still be there. Can you please help me with further details, either here on in a new issue? Can you tell me what version you're running Grafana and if you have any steps to reproduce this bug? Maybe your dashboard json model and some sample data from the panel to test against (from Query Inspector -> Data)? 

Thank you!

**Comment by gfranco-replica** [comment]
> Hey @gfranco-replica . This definitely seems like a bug, the date/time should still be there. Can you please help me with further details, either here or in a new issue? Can you tell me what version you're running Grafana and if you have any steps to reproduce this bug? Maybe your dashboard json model and some sample data from the panel to test against (from Query Inspector -> Data)?
> 
> Thank you!

Sure, I can provide several details, I'm working on a Dashboard and we had 9.0.1 two nights ago.

Screen Shot 2022-09-27 at 10 23 46 PM

I needed the datalinks but they were not working on the "Status History" panel, I found this PR and that the fix was already merged so I requested operations to upgrade to the latest version of Grafana, then this morning when I refreshed my browser to load to the latest version to verify the datalinks, they were working but I found out the date/time were gone from the tooltip, (now datalinks works properly)

Screen Shot 2022-09-27 at 10 24 06 PM

The funny thing is that on another tab I have the older version still loaded where it shows the tooltip, I can see both behaviors side by side.

24hs data.
[Trends readiness history-data-2022-09-27 22_34_34.csv](https://github.com/grafana/grafana/files/9661776/Trends.readiness.history-data-2022-09-27.22_34_34.csv)

Json model
[json_model.txt](https://github.com/grafana/grafana/files/9661842/json_model.txt)

**Comment by mdvictor** [comment]
Hey @gfranco-replica. This is very weird. I just looked over it on the same version you are on and could not reproduce using the data and json you shared with me.

Can you help me with more data please?

* What browser are you on?
* Can you try recreating the panel and leave me steps on how you reproduced the issue in this new panel?
* Are there any errors in the console on the panel with the bad tooltip?

On my end it looks fine with the data I received:
Screenshot 2022-09-28 at 10 13 16

**Comment by gfranco-replica** [comment]
@mdvictor, I created a brand new dashboard and panel, left everything as default, just selected "status history" visualization and hardcoded a basic query, same result.

Screen Shot 2022-09-28 at 10 57 36 AM

Browser is Chrome on a mac M1.
Screen Shot 2022-09-28 at 11 00 52 AM

**Comment by gfranco-replica** [comment]
This is what I get from the console.

Screen Shot 2022-09-28 at 11 04 32 AM

**Comment by gfranco-replica** [comment]
Tried on Windows (Chrome and Edge) same behavior with the simplest dashboard shown above
Screen Shot 2022-09-28 at 4 02 07 PM
Screen Shot 2022-09-28 at 4 01 35 PM

**Comment by mdvictor** [comment]
Hey @gfranco-replica,

Thanks for taking the time and helping me with this. I managed to reproduce it on v9.1.6. For some reason it's not reproducible in main, which might mean that it got fixed and will be released in the next 9.1 patch.

Either way, I have created this [issue](https://github.com/grafana/grafana/issues/55975) to keep track of it and will look into it to make sure it goes on the next patch.

**Comment by gfranco-replica** [comment]
@mdvictor great news, thank you very much for the quick response and eager to wait for the next patch.
Is there a link to roadmap releases? I'm fairly new to Grafana

**Comment by mdvictor** [comment]
@gfranco-replica Welcome to the community!

Releases happen rather fast for patches. I would expect this fix to be out in at most 2 weeks. I am not aware of any roadmap release link, other than [this](https://github.com/grafana/grafana/blob/main/ROADMAP.md).

**Comment by gfranco-replica** [comment]
> @gfranco-replica Welcome to the community!
> 
> Releases happen rather fast for patches. I would expect this fix to be out in at most 2 weeks. I am not aware of any roadmap release link, other than [this](https://github.com/grafana/grafana/blob/main/ROADMAP.md).

We just updated to 9.2.0 and I can confirm the date/time is back on the tooltips !!!
Thanks.
