### PR TITLE
Prometheus: Use configured HTTP method for /series and /labels endpoints

### LINKED ISSUE #17342: Use configured HTTP Method for meta data requests
**What happened**:
None of the panels loaded the requested data

**What you expected to happen**:
All panels should have loaded the data

**How to reproduce it (as minimally and precisely as possible)**:
1. Set up a prometheus datasource
2. Define a variable with a large cardinality (I'm using 380 pod names)
3. Use automatic ALL value on the variable
4. Build a query which embeds the variable in it
5. Panels do not load data

seems to be exactly as https://github.com/grafana/grafana/issues/8109 but for prometheus rather than influxDB

**Anything else we need to know?**:
image

**Environment**:
- Grafana version: 6.1.3
- Data source type & version: Prometheus 2.8
- OS Grafana is installed on: Ubuntu
- User OS & Browser: MacOSx Mojave
- Grafana plugins: None
- Others:

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
This PR updated Prometheus metadata requests to use configured  http method for endpoints that supports that - `'api/v1/query', 'api/v1/query_range', 'api/v1/series', 'api/v1/labels'`. As the support for POST was added in version 2.10+, we decided to use configured method first, and if we gets **Bad Method** error when trying POST method, then retry with GET.
**Request to `/series` with HTTP method set to POST and Prometheus (v2.7.2) NOT supporting POST to that endpoint:**
https://user-images.githubusercontent.com/30407135/108738397-db6bf780-7533-11eb-99a0-128f134afe0d.mov

**Request to `/series` with HTTP method set to POST and Prometheus (:latest) supporting POST to that endpoint:**
https://user-images.githubusercontent.com/30407135/108738413-deff7e80-7533-11eb-812c-fcb0ad7feba1.mov

**Endpoints supporting POST and GET:**
image
image
image
image

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/17342

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/datasource.ts [hunk 1]
```diff
@@ -136,15 +137,29 @@ export class PrometheusDatasource extends DataSourceApi<PromQuery, PromOptions>
...
+  async metadataRequest<T = any>(url: string) {
     const data: any = {};
     for (const [key, value] of this.customQueryParameters) {
       if (data[key] == null) {
         data[key] = value;
       }
     }
 
-    return this._request<T>(url, data, { method: 'GET', hideFromInspector: true }).toPromise(); // toPromise until we change getTagValues, getTagKeys to Observable
+    // If URL includes endpoint that supports POST method, try to use configures method
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/prometheus/datasource.ts:148]:
```suggestion
    // If URL includes endpoint that might support POST and GET method, try to use configured method. This might fail as POST is supported only in v2.10+ .
```

File: public/app/plugins/datasource/prometheus/datasource.ts [hunk 2]
```diff
@@ -136,15 +137,29 @@ export class PrometheusDatasource extends DataSourceApi<PromQuery, PromOptions>
...
     const data: any = {};
     for (const [key, value] of this.customQueryParameters) {
       if (data[key] == null) {
         data[key] = value;
       }
     }
 
-    return this._request<T>(url, data, { method: 'GET', hideFromInspector: true }).toPromise(); // toPromise until we change getTagValues, getTagKeys to Observable
+    // If URL includes endpoint that supports POST and GET method, try to use configured method. This might fail as POST is supported only in v2.10+.
+    if (GET_AND_POST_MEDATADATA_ENDPOINTS.some((endpoint) => url.includes(endpoint))) {
```
Comment (aocenas) [inline public/app/plugins/datasource/prometheus/datasource.ts:149]: how often do we do these? I think this can make some autocomplete features slower if you configure POST on older versions (which I assume is totally valid because you want POST for queries) and we have to do 2 requests for every metadata query. If we have to run this often maybe we still can cache the result so we then do only one correct request, would that make sense?

**Review by aocenas — APPROVED** [review]

File: public/app/plugins/datasource/prometheus/datasource.ts (hunk 2 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/prometheus/datasource.ts:149]: This would be run in:
-  template variables (label_names() and label_values()) which are not cached, but they are either run just once, run when dashboard is initialised or when time picker changes. So not that often that it should slow down anything. 
- In autocomplete we are caching here labels and values, so shouldn't be problem as well.
