### PR TITLE
Prometheus: Improve prometheus query variable editor

### LINKED ISSUE #59559: Template Variables: Query-based. Newlines in query cause silent failure
**What happened**:

See this Loom video:
https://www.loom.com/share/c57c4cfbf6ea40ccbd11b01f727c3037

I'm naturally trying to bend Grafana to my will, so I have a template-var which is query-based, and has a query of reasonable length/complexity, as follows:

```
query_result(
  scalar(
    (sum(grafanacloud_instance_active_series)
    /
    sum(grafanacloud_instance_memory_series)
  )
)
```

Given the complexity I've introduced newlines in order to make it easier to work with.

**BUT** apparently the newlines lead to the query **never actually getting issued/executed.** This is doubly confusing because I **DO** see a "Preview of values" value present, but apparently it's still there and left over from a previous execution, from before I added the newlines 🤯 .

I can tell the query isn't executed, because when I take out all the newlines (and spaces) I get an error message due to a syntax error:

```
query_result(scalar((sum(grafanacloud_instance_active_series)/sum(grafanacloud_instance_memory_series)))
```
> invalid parameter "query": 1:91: parse error: unclosed left parenthesis

Even then, I still see the "Preview of values" populated 🤯🤯. It seems to me we should clear out this "Preview of values" as soon as the query starts failing and stops executing. While it remains it's lying to me, and implying that I will see that value on the dashboard itself for this dash-variable, when in practice I won't see it at all 💔 

Also the Input is exceeding the visual boundaries of the div that it sits inside, which is ugly:
input wider than parent div

**What you expected to happen**:

- Even with newlines, if I have a syntax error in my query code, I should be told that I have a syntax error and asked to fix it
- As soon as the query stops executing (due to syntax error or otherwise) the "Preview of values" should be cleared out.
- The input should not exceed the boundaries set by the parent/ancestor div.

**How to reproduce it (as minimally and precisely as possible)**:
- Use a GrafanaCloud account, which has the `grafanacloud-usage` datasource present
- Create a new dash-var with type "query" and datasource "grafanacloud-usage"
- Paste in the PromQL above, and see the behaviour I'm describing.

**Anything else we should know**:
This is closely related to https://github.com/grafana/grafana/issues/59495 but it is **NOT** a duplicate. This ticket describes separate and additional problems to my previous bug report (and super frustrating ones).

**Environment**:
- Grafana version: [v9.2.7-0f96ed148c (0f96ed148c)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- OS Grafana is installed on: GrafanaCloud
- User OS & Browser: macOS 12.6.1 (21G217), Chrome Version 107.0.5304.110 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by bohandley**
This is the updated PR for the improved Prom Query Variable Editor that was [reverted](https://github.com/grafana/grafana/pull/63278)
The first was reverted because it did not migrate a variable created for a kubernetes-mixin using libsonnet. This is now handled and there are unit tests for this scenario.

Fixes https://github.com/grafana/grafana/issues/59559 (allow newlines in Prom query result variable query editor)
Fixes https://github.com/grafana/observability-metrics-squad/issues/48

**What is this feature?**
This changes the prometheus query variable editor to a group of selects and inputs to better explain the functions, arguments, and endpoint calls used in the prometheus variable queries.

Previous single input:
Screen Shot 2022-11-05 at 12 16 57 PM

New function select and variable inputs:
Screen Shot 2022-11-05 at 12 17 30 PM

Full proposal [here](https://docs.google.com/document/d/1VsMFjiuug-sbSm5XaQffISsUcyxQ5CeHFAjT-POcIqo/edit).

**Why do we need this feature?**
This is in line with the Grafana 10 goal of "Getting Started." More clarity around creating variables in Prometheus will help onboard new customers.

**Who is this feature for?**
This feature is for anyone using the Prometheus datasource plugin who wants to create template variables.
This is for all users of prometheus datasource plugin, from expert to beginner.

**Special notes for your reviewer**:
1. Please create a prometheus variable in the main branch, for example, `label_names()`
2. Switch to the new branch and open the variable editor to see that the function has been correctly passed to the inputs.
3. Check that the variables are returned.
4. Look for confusing language and readability. Are the tooltips helpful?

### CODE REVIEW

**Review by itsmylife — APPROVED** [review]

**Comment by samjewell** [comment]
Exciting! Thanks for this 🙏

File: public/app/plugins/datasource/prometheus/types.ts [hunk 1]
```diff
@@ -165,3 +166,26 @@ export enum LegendFormatMode {
...
+  LabelValues,
+  MetricNames,
+  VarQueryResult,
+  SeriesQuery,
+}
+
+export interface PromVariableQuery extends DataQuery {
+  query?: string;
+  expr?: string;
+  qryType?: PromVariableQueryType;
```
Comment (torkelo) [inline public/app/plugins/datasource/prometheus/types.ts:181]: @bohandley missspelled? This now in the persisted model, and we have this cryptic enum now numeric values in the persisted model (PromVariableQueryType)

Comment (bohandley) [reply public/app/plugins/datasource/prometheus/types.ts:181]: @torkelo I meant to spell `qryType` that way but I can change it if that is not correct or not clear. When a user selects the query type of label names, label values, etc, this is the `PromVariableQueryType`. We use this to identify which should be selected in the new variable editor. This could use some refactoring to make that more clear. 

All of this could be refactored though, as I originally built it to migrate to the new editor and then migrate back to the string to preserve the definitions in the variables list. I believe we are moving away from that so all of this could be much clearer with less code.

Comment (torkelo) [reply public/app/plugins/datasource/prometheus/types.ts:181]: @bohandley well this is far from clear and is now in millions of dashboard json files as this part of the saved model, so really hurts the as code story (where dashboards are defined using the save model). Not only is "qryType" a very ugly thing to have as a property type in code but also in the save model, AND it just just very cryptic numbers (0, 1, 2, 3) that have no meaning, enums must always have string values so we can make sense of them when looking at the save model.

Comment (torkelo) [reply public/app/plugins/datasource/prometheus/types.ts:181]: and why do do we have query property and expr property??  some code comments on what these properties are would also help :)

Comment (torkelo) [reply public/app/plugins/datasource/prometheus/types.ts:181]: If anyone would change the order of that enum type without a migration many dashboards would now break

Comment (torkelo) [reply public/app/plugins/datasource/prometheus/types.ts:181]: btw, think the PR as whole is awesome, just need to make sure the save model is clear and not fragile and inscrutable :)

File: public/app/plugins/datasource/prometheus/variables.ts [hunk 2]
```diff
@@ -48,11 +45,4 @@ export class PrometheusVariableSupport extends StandardVariableSupport<Prometheu
 
     return metricFindStream.pipe(map((results) => ({ data: results })));
   }
-
-  toDataQuery(query: StandardVariableQuery): PromQuery {
-    return {
-      refId: 'PrometheusDatasource-VariableQuery',
-      expr: query.query,
-    };
-  }
```
Comment (torkelo) [inline public/app/plugins/datasource/prometheus/variables.ts:57]: @bohandley 
Without this I am unsure how this works with old dashboards? I can only see the migration being done for the variable query editor not when queries are executed. But maybe I am missing it

Comment (torkelo) [reply public/app/plugins/datasource/prometheus/variables.ts:57]: I think I know why it works still now, so don't worry about the comment above

File: public/app/plugins/datasource/prometheus/types.ts (hunk 1 above)
Comment (bohandley) [reply public/app/plugins/datasource/prometheus/types.ts:181]: > @bohandley well this is far from clear and is now in millions of dashboard json files as this part of the saved model, so really hurts the as code story (where dashboards are defined using the save model). Not only is "qryType" a very ugly thing to have as a property name in code but also in the save model, AND it just very cryptic numbers (0, 1, 2, 3) that have no meaning, enums must always have string values so we can make sense of them when looking at the save model.

@torkelo thank you! This is true, I had not considered the code story as it relates to dashboards, my apologies. This makes total sense. To see `qryType: 1` in the dashboard json is both ugly and unclear as it relates to the code story. I will make sure any enums have string values moving forward. 

> and why do do we have query property and expr property?? some code comments on what these properties are would also help :)

Yes! I can add the code comments to the appropriate spot. I have some in the editor but I can see that this doesn't help when developers are reading the types to understand building a dashboard as code. The `query` and `expr` property are both there because I also had to migrate from standard variable support (which uses `expr`) and custom variable support (which uses `query`). So both fields would be present. I can add code comments for that!

https://github.com/grafana/grafana/blob/5aacdd9f49a96f4663aeb2900d4ef76ac850b98b/public/app/plugins/datasource/prometheus/components/VariableQueryEditor.tsx#L71-L73

I am sure there is a cleaner way to write all of this now, and I will create an issue to clean up some some of this. I will also add a reference point to make sure that any changes in the save model are as you say "clear, not fragile and inscrutable" 💯 Thank you for the feedback @torkelo!

Comment (torkelo) [reply public/app/plugins/datasource/prometheus/types.ts:181]: @bohandley great!  :+1:

Comment (bohandley) [reply public/app/plugins/datasource/prometheus/types.ts:181]: For the issues: https://github.com/grafana/grafana/issues/75175
