### PR TITLE
Explore: calculate intervals when building data source request

### LINKED ISSUE #19086: Explore: When zooming in the logs graph, the table has entries but graph doesn't
**What happened**:
When zooming in the logs graph in Explore, the table has entries but graph doesn't. 
image

**What you expected to happen**:
See entries that are in the table in graph.

**How to reproduce it (as minimally and precisely as possible)**:
- Go to Explore and choose Loki as a data source
- Run query e.g. `{job="varlogs"}`
- Zoom in to graph where graph bar is not displayed

You will see logs in the table, but not in graph

**Anything else we need to know?**:
Probably related to interval variable which I think does not change when zooming and is something like 15s by default. In dashboard this is computed automatically from graph width so maybe that part is missing in explore.

### PR DESCRIPTION
**Pull request by torkelo**
Somewhere during 6.4 development, the re-calc of intervals was lost :) 

Since the introduction of PanelData in explore state we can remove queryIntervals from redux state as this interval is already stored on the PanelData.request. 

added back getIntervals (found in git history) and made this part of buildTransaction. 
 
Fixes #19086

Sorry for hijacking a fix you where working on @ivanahuckova but think this was pretty tricky to fix as this code had gotten lost and there were relics of old solutions that were actually no longer need (storing/updating queryIntervals in redux state for example). So wanted to help out here so you did not spend too much time trying to figure out how this ever worked as the current state was very messy due to recent changes & missing pieces.

### CODE REVIEW

File: public/app/core/utils/explore.ts [hunk 1]
```diff
@@ -103,17 +98,16 @@ export function buildQueryTransaction(
...
 ): QueryTransaction {
-  const { interval, intervalMs } = queryIntervals;
-
   const configuredQueries = queries.map(query => ({ ...query, ...queryOptions }));
   const key = queries.reduce((combinedKey, query) => {
     combinedKey += query.key;
     return combinedKey;
   }, '');
 
+  const { interval, intervalMs } = getIntervals(range, queryOptions.minInterval, queryOptions.maxDataPoints);
```
Comment (hugohaggmark) [inline public/app/core/utils/explore.ts]: Maybe we should add a test for this so it doesn't get lost again

**Review by hugohaggmark — COMMENTED** [review]
Great work getting this back, I think we're maybe missing a test so it doesn't get removed again.

**Review by ivanahuckova — COMMENTED** [review]
No worries and thank you for doing it @torkel! 🚀🙂

I reviewed a code and I have 2 questions (both might not be related directly to this PR, but maybe/maybe not for separate issue) :
1. Is this (see below) the default behaviour that we want to see if there are no logs for selected interval? Wouldn't be better to have graph there, just without bars as there are no logs? @davkal what do you think?
image

EDIT: ISSUE FOR BUG BELLOW CREATED (https://github.com/grafana/grafana/issues/19114) 
2. When I zoom in to graph in Explore and then use browser's *go back* I get following error (that is currently present in the master as well). Should I create a new issue for this?
`Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`
image

Otherwise, everything works perfectly!

File: public/app/core/utils/explore.ts (hunk 1 above)
Comment (torkelo) [reply public/app/core/utils/explore.ts]: added unit tests in https://github.com/grafana/grafana/pull/19107/commits/b6cc4d0d562b9bcb0a62dead92dd3f0ec546b684

**Comment by torkelo** [comment]
added unit tests!

**Review by hugohaggmark — APPROVED** [review]
LGTM!
