### PR TITLE
Prometheus: Disabled inputs when settings are read-only

### LINKED ISSUE #57328: Prometheus datasource's Test doesn't take into account URL changes.
**What happened**

I went to a datasource's settings page, changed the URL to one that doesn't work, clicked on Test, and it still reported to be OK.

https://user-images.githubusercontent.com/1511481/196892267-4faeb6d0-a47e-4874-80b2-6a3a1bd83440.mp4

**What you expected to happen**:

I expected it to fail.

**How to reproduce it (as minimally and precisely as possible)**:

- Go to a working Prometheus datasource settings
- Change the URL to something that you know doesn't work
- Click on Test

**Anything else we need to know?**:

I tried the same on a non-working datasource that had wrong credentials, changing the URL that would accept those credentials, and it kept failing (although I expected it to succeed). It seems to just ignore the endpoint changes.

**Environment**:
- Grafana version: 9.1.5 (df015...)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome on Linux
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by LudoVio**
**What is this feature?**

In the Prometheus data source settings page, disabled inputs when settings are read-only (imported conf)

**Why do we need this feature?**

User reported the UI to be confusing, as it looks like we cant edit and test the new settings but this is not the case.

**Who is this feature for?**

Every user who deal with data source setting imported by provisioning

**Which issue(s) does this PR fix?**:

Fixes #57328

### CODE REVIEW

File: packages/grafana-ui/src/components/Input/Input.tsx [hunk 1]
```diff
@@ -59,6 +73,7 @@ export const Input = React.forwardRef<HTMLInputElement, Props>((props, ref) => {
           ref={ref}
           className={styles.input}
           {...restProps}
+          disabled={readOnly}
```
Comment (jackw) [inline packages/grafana-ui/src/components/Input/Input.tsx:76]: This component looks to be spreading `restProps` which should mean we can already pass `disabled` to this input component.

File: packages/grafana-ui/src/components/Switch/Switch.tsx [hunk 2]
```diff
@@ -14,7 +14,7 @@ export interface Props extends Omit<HTMLProps<HTMLInputElement>, 'value'> {
 }
 
 export const Switch = React.forwardRef<HTMLInputElement, Props>(
-  ({ value, checked, disabled, onChange, id, label, ...inputProps }, ref) => {
+  ({ value, checked, onChange, id, label, disabled, readOnly, ...inputProps }, ref) => {
```
Comment (codeincarnate) [inline packages/grafana-ui/src/components/Switch/Switch.tsx:17]: Seems redundant to add both `disabled` and `readOnly` props here. Is this for styling purposes (i.e. a disabled field could potentially be re-enabled whereas read only might not be?)

File: packages/grafana-runtime/src/components/DataSourcePicker.tsx [hunk 3]
```diff
@@ -184,7 +186,7 @@ export class DataSourcePicker extends PureComponent<DataSourcePickerProps, DataS
       <div aria-label={selectors.components.DataSourcePicker.container}>
         <Select
           isLoading={isLoading}
-          disabled={disabled}
+          disabled={disabled || readOnly}
```
Comment (jackw) [inline packages/grafana-runtime/src/components/DataSourcePicker.tsx:189]: I think this will make the component API confusing. Rather than introduce another prop that disables the `Select` I would expect the call site to do `<DataSourcePicker disabled={readOnly} />` or similar.

File: packages/grafana-ui/src/components/FormField/FormField.tsx [hunk 4]
```diff
@@ -41,7 +41,12 @@ export const FormField: FunctionComponent<Props> = ({
         {label}
       </InlineFormLabel>
       {inputEl || (
-        <input type="text" className={`gf-form-input ${inputWidth ? `width-${inputWidth}` : ''}`} {...inputProps} />
+        <input
+          type="text"
+          className={`gf-form-input ${inputWidth ? `width-${inputWidth}` : ''}`}
+          {...inputProps}
+          disabled={inputProps.disabled || inputProps.readOnly}
```
Comment (jackw) [inline packages/grafana-ui/src/components/FormField/FormField.tsx:48]: As previous comment can't we continue to use `disabled` here?

File: packages/grafana-ui/src/components/SecretFormField/SecretFormField.tsx [hunk 5]
```diff
@@ -77,6 +77,7 @@ export const SecretFormField: FunctionComponent<Props> = ({
             className={`gf-form-input width-${inputWidth}`}
             placeholder={placeholder}
             {...inputProps}
+            disabled={inputProps.disabled || inputProps.readOnly}
```
Comment (jackw) [inline packages/grafana-ui/src/components/SecretFormField/SecretFormField.tsx:80]: As previous comment can't we continue to use `disabled` here?

File: packages/grafana-ui/src/components/Switch/Switch.tsx [hunk 6]
```diff
@@ -27,10 +27,10 @@ export const Switch = React.forwardRef<HTMLInputElement, Props>(
       <div className={cx(styles.switch)}>
         <input
           type="checkbox"
-          disabled={disabled}
+          disabled={disabled || readOnly}
```
Comment (jackw) [inline packages/grafana-ui/src/components/Switch/Switch.tsx:30]: As previous comment can't we continue to use `disabled` here?

File: packages/grafana-ui/src/components/TagsInput/TagsInput.tsx [hunk 7]
```diff
@@ -73,6 +73,7 @@ export const TagsInput = ({
       <Input
         id={id}
         disabled={disabled}
+        readOnly={disabled}
```
Comment (jackw) [inline packages/grafana-ui/src/components/TagsInput/TagsInput.tsx:76]: As previous comment can't we continue to use `disabled` here?

File: packages/grafana-ui/src/components/Input/Input.tsx (hunk 1 above)
Comment (LudoVio) [reply packages/grafana-ui/src/components/Input/Input.tsx:76]: It should yes, but the "disabled" props is always `undefined` no matter what the value is.
I suspect the forwardRef to interact here

File: packages/grafana-ui/src/components/Switch/Switch.tsx (hunk 2 above)
Comment (LudoVio) [reply packages/grafana-ui/src/components/Switch/Switch.tsx:17]: `disabled` is sometime not working as intended

File: packages/grafana-runtime/src/components/DataSourcePicker.tsx (hunk 3 above)
Comment (LudoVio) [reply packages/grafana-runtime/src/components/DataSourcePicker.tsx:189]: I thought maybe the `disabled` props is currently in use, but on some page it doesn't work

File: packages/grafana-ui/src/components/FormField/FormField.tsx (hunk 4 above)
Comment (LudoVio) [reply packages/grafana-ui/src/components/FormField/FormField.tsx:48]: it doesn't always work

**Comment by itsmylife** [comment]
I agree with @codeincarnate and @jackw `disabled` prop should be sufficient.

File: packages/grafana-ui/src/components/Switch/Switch.tsx (hunk 2 above)
Comment (LudoVio) [reply packages/grafana-ui/src/components/Switch/Switch.tsx]: fixed

File: packages/grafana-ui/src/components/Input/Input.tsx (hunk 1 above)
Comment (LudoVio) [reply packages/grafana-ui/src/components/Input/Input.tsx]: fixed

File: packages/grafana-runtime/src/components/DataSourcePicker.tsx (hunk 3 above)
Comment (LudoVio) [reply packages/grafana-runtime/src/components/DataSourcePicker.tsx]: fixed

File: packages/grafana-ui/src/components/FormField/FormField.tsx (hunk 4 above)
Comment (LudoVio) [reply packages/grafana-ui/src/components/FormField/FormField.tsx]: fixed

File: packages/grafana-ui/src/components/SecretFormField/SecretFormField.tsx (hunk 5 above)
Comment (LudoVio) [reply packages/grafana-ui/src/components/SecretFormField/SecretFormField.tsx]: fixed

File: packages/grafana-ui/src/components/Switch/Switch.tsx (hunk 6 above)
Comment (LudoVio) [reply packages/grafana-ui/src/components/Switch/Switch.tsx]: fixed

File: packages/grafana-ui/src/components/TagsInput/TagsInput.tsx (hunk 7 above)
Comment (LudoVio) [reply packages/grafana-ui/src/components/TagsInput/TagsInput.tsx]: fixed

**Review by itsmylife — APPROVED** [review]
