### PR TITLE
Prometheus: Explore expand raw results in split panel bug fix

### LINKED ISSUE #73863: Prometheus: In explore with split panel, expanding raw results bug
Bug: When using Prometheus ds in Explore tab with a split panel, clicking "expand" for raw results in a second panel expands the results in the first panel.

https://user-images.githubusercontent.com/25674746/263389074-0caf09d4-9d2e-4020-8b38-d0323b713667.mov

### PR DESCRIPTION
**Pull request by bohandley**
**What is this feature?**
Bug fix for when a user is in Explore view with Prometheus ds, click "split pane." Then choose to expand the raw Prometheus results. The bug is that the switches for both panels have the same id so clicking either one expands the first results

See the following issue https://github.com/grafana/grafana/issues/73863

This is without the fix

https://github.com/grafana/grafana/assets/25674746/c774ad83-75e7-4c00-ad6f-c34c345e4736

This is with the fix

https://github.com/grafana/grafana/assets/25674746/0a84137a-0bc9-4c05-a63d-6b145768066f

**Who is this feature for?**
Explore users, Prometheus users, people who want to expand raw results

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/73863

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by itsmylife — APPROVED** [review]

File: public/app/features/explore/PrometheusListView/RawListContainer.tsx [hunk 1]
```diff
@@ -61,7 +62,7 @@ const numberOfColumnsBeforeExpandedViewIsDefault = 2;
  * @constructor
  */
 const RawListContainer = (props: RawListContainerProps) => {
-  const { tableResult } = props;
+  const { tableResult, exploreId } = props;
```
Comment (Elfo404) [inline public/app/features/explore/PrometheusListView/RawListContainer.tsx:65]: `useId` from react may be a better fit for generating ids for such use cases
