### PR TITLE
Alerting: improve error on failure to remove query referenced by legacy alerting

### LINKED ISSUE #39075: Can't delete disabled query
**What happened**:
After upgrading Grafana from 7.5.7 to 8.1.2 I can't delete disabled queries, previously used for alerting.
Getting an error when saving dashboard:
```
Validation failed
alert validation error: Alert on PanelId: 189 refers to query(B) that cannot be found
```
image

Console log

```
fetch.js:45 POST http://hostname:3000/api/dashboards/db/ 422 (Unprocessable Entity)
(anonymous) @ fetch.js:45
e._trySubscribe @ Observable.js:43
e.subscribe @ Observable.js:29
e.call @ mergeMap.js:27
e.subscribe @ Observable.js:24
t.connect @ ConnectableObservable.js:34
e.call @ refCount.js:19
e.subscribe @ Observable.js:24
e.call @ filter.js:15
e.subscribe @ Observable.js:24
e.call @ tap.js:18
e.subscribe @ Observable.js:24
c @ innerSubscribe.js:89
t._innerSub @ mergeMap.js:72
t._tryNext @ mergeMap.js:66
t._next @ mergeMap.js:49
t.next @ Subscriber.js:53
(anonymous) @ subscribeToArray.js:5
e._trySubscribe @ Observable.js:43
e.subscribe @ Observable.js:29
e.call @ mergeMap.js:27
e.subscribe @ Observable.js:24
e.call @ catchError.js:16
e.subscribe @ Observable.js:24
e.call @ takeUntil.js:16
e.subscribe @ Observable.js:24
e.call @ throwIfEmpty.js:18
e.subscribe @ Observable.js:24
(anonymous) @ backend_srv.ts:87
t.__tryOrUnsub @ Subscriber.js:192
t.next @ Subscriber.js:130
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t.next @ Subject.js:47
(anonymous) @ ResponseQueue.ts:30
t.__tryOrUnsub @ Subscriber.js:192
t.next @ Subscriber.js:130
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
(anonymous) @ ResponseQueue.ts:35
(anonymous) @ FetchQueueWorker.ts:54
t.__tryOrUnsub @ Subscriber.js:192
t.next @ Subscriber.js:130
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
(anonymous) @ subscribeToArray.js:5
c @ innerSubscribe.js:91
t._innerSub @ mergeMap.js:72
t._tryNext @ mergeMap.js:66
t._next @ mergeMap.js:49
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t.next @ Subject.js:47
(anonymous) @ FetchQueue.ts:76
(anonymous) @ FetchQueue.ts:55
t.__tryOrUnsub @ Subscriber.js:192
t.next @ Subscriber.js:130
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
(anonymous) @ FetchQueue.ts:59
(anonymous) @ backend_srv.ts:92
e._trySubscribe @ Observable.js:43
e.subscribe @ Observable.js:29
e.call @ map.js:18
e.subscribe @ Observable.js:24
(anonymous) @ Observable.js:98
e.toPromise @ Observable.js:96
request @ backend_srv.ts:67
post @ backend_srv.ts:385
O @ actions.ts:205
(anonymous) @ useDashboardSave.tsx:17
(anonymous) @ useDashboardSave.tsx:23
(anonymous) @ useAsyncFn.js:20
onSubmit @ SaveDashboardModal.tsx:44
onSubmit @ SaveDashboardForm.tsx:25
(anonymous) @ useForm.ts:1059
async function (async)
(anonymous) @ useForm.ts:1046
Ue @ react-dom.production.min.js:52
$e @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Or @ react-dom.production.min.js:100
Er @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Ne @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
jr @ react-dom.production.min.js:105
Zt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uo @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Kt @ react-dom.production.min.js:73
```

**What you expected to happen**:
Saved dashboard without unused queries

**How to reproduce it (as minimally and precisely as possible)**:

1. Create query at Grafana 7.5.7, disable it and use for alert
2. Upgrade Grafana up to 8.1.2
3. Enable option ngalert
4. Edit panel and remove disabled query
5. Press Save button and get error

### PR DESCRIPTION
**Pull request by davidmparrott**
**What this PR does / why we need it**:
Improves the error returned when a user attempts to remove a query that is referenced by a legacy alerting condition for a panel. Upon save, we now check if ngalerting is enabled and, if so, pass back a more informative error for display

**Which issue(s) this PR fixes**:
Fixes #39075

**Special notes for your reviewer**:
Couldn't see an obvious way to get the config for UA other than passing it in the context. Feel free to suggest alternatives if you have something you like better

### CODE REVIEW

File: pkg/api/dashboard.go [hunk 1]
```diff
@@ -332,7 +332,7 @@ func (hs *HTTPServer) PostDashboard(c *models.ReqContext, cmd models.SaveDashboa
 	}
 
 	dashSvc := dashboards.NewService(hs.SQLStore)
```
Comment (gotjosh) [inline pkg/api/dashboard.go:334]: nit: You could do something like `	ctx = context.WithValue(ctx, "unified_alerting_enabled", hs.Cfg.UnifiedAlerting.Enabled)` and avoid passing down the whole struct. The string can be a type or a cost just like you've done with `// CtxCfg is used as a key to get configuration from the context
type CtxCfg struct{}`

File: pkg/services/alerting/extractor.go [hunk 2]
```diff
@@ -170,7 +174,13 @@ func (e *DashAlertExtractor) getAlertFromPanels(ctx context.Context, jsonWithPan
 			panelQuery := findPanelQueryByRefID(panel, queryRefID)
 
 			if panelQuery == nil {
-				reason := fmt.Sprintf("Alert on PanelId: %v refers to query(%s) that cannot be found", alert.PanelId, queryRefID)
+				config := ctx.Value(CtxCfg{}).(*setting.Cfg)
```
Comment (gotjosh) [inline pkg/services/alerting/extractor.go:177]:
```suggestion
				config := ctx.Value(CtxCfg{}).(*setting.Cfg)
			    if !ok {
					return nil, fmt.Errorf("unable to determine if unified alerting is enabled: %v", err)
				}

```

File: pkg/services/alerting/extractor.go [hunk 3]
```diff
@@ -170,7 +174,13 @@ func (e *DashAlertExtractor) getAlertFromPanels(ctx context.Context, jsonWithPan
...
+				var reason string
+				if config.UnifiedAlerting.Enabled {
+					reason = fmt.Sprintf("Alert on PanelId: %v refers to query(%s) that cannot be found. Legacy alerting queries are not able to be removed at this time in order to preserve the ability to rollback to previous versions of Grafana", alert.PanelId, queryRefID)
```
Comment (gotjosh) [inline pkg/services/alerting/extractor.go:180]:
```suggestion
					reason = fmt.Sprintf("alertId '%v' on PanelId: '%v' refers to query(%s) that cannot be found. Legacy alerting conditions are not able to be removed at this time in order to preserve the ability to rollback to previous versions of Grafana", alert.Id, alert.PanelId, queryRefID)
```

**Review by gotjosh — APPROVED** [review]
LGTM - my comments are nits.

File: pkg/services/alerting/extractor.go (hunk 3 above)
Comment (davidmparrott) [reply pkg/services/alerting/extractor.go:180]: Here, the error is specifically on removing the query so I think we should not reference condition

Comment (gotjosh) [reply pkg/services/alerting/extractor.go:180]: 🤦 - you're right.

File: pkg/api/dashboard.go (hunk 1 above)
Comment (davidmparrott) [reply pkg/api/dashboard.go:334]: I had actually done it that way originally but it doesn't pass the linter:

```
[lint-backend:2] pkg/api/dashboard.go:335:65: SA1029: should not use built-in type string as key for value; define your own type to avoid collisions (staticcheck)
[lint-backend:3] 	dashboard, err := dashSvc.SaveDashboard(context.WithValue(ctx, "unified_alerting_enabled", hs.Cfg.UnifiedAlerting.Enabled), dashItem, allowUiUpdate)
```

Comment (gotjosh) [reply pkg/api/dashboard.go:334]: Ah, that makes sense - now I get the reasoning behind the type.

Comment (davidmparrott) [reply pkg/api/dashboard.go:334]: But I bet I could set a bool in the CtxCfg struct and only pass that so that we're not copying the entire config. Thanks!

**Review by santihernandezc — COMMENTED** [review]
I think the decision to put values inside the `context` is ok as far as those values are created and destroyed within the lifetime of the request, so that LGTM.

That being said, I think we should use an unexported key to access the values inside the `context`, and we should also use getters and setters for type safety when using `context.WithValue()` and `ctx.Value()`. For more info, there's a neat [comment](https://github.com/golang/net/blob/236b8f043b920452504e263bc21d354427127473/context/context.go#L100-L104) in the standard library about this.

Also, nice catch @gotjosh about that unsafe type assertion. That could be a source of panics in the future.

**Review by santihernandezc — APPROVED** [review]
LGTM 👍
