### PR TITLE
Time series panel: Hide axis when series is hidden from the visualization

### LINKED ISSUE #46290: Series hidden from `viz` still displays its axis when Scale is Linear
**What happened**:

I have initially hidden series from `Viz`. But while it is hidden, its axis is visible and shows astronomic values.

Switching the axis scale to Logarithmic makes the axis disappear.

**What you expected to happen**:

The axis is not visible as well as there are no series visibile for it

**How to reproduce it (as minimally and precisely as possible)**:

<details>
<summary>Panel Json</summary>

```json
{
  "id": 540,
  "gridPos": {
    "h": 8,
    "w": 18,
    "x": 0,
    "y": 28
  },
  "type": "timeseries",
  "title": "Multiple Y-Axes (more than 2!)",
  "datasource": {
    "uid": "000000051",
    "type": "testdata"
  },
  "pluginVersion": "7.4.0-beta1",
  "maxDataPoints": 50,
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "linear",
        "barAlignment": 0,
        "lineWidth": 2,
        "fillOpacity": 0,
        "gradientMode": "opacity",
        "spanNulls": true,
        "showPoints": "never",
        "pointSize": 6,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false,
          "graph": false
        },
        "thresholdsStyle": {
          "mode": "off"
        },
        "axisSoftMax": 60,
        "axisSoftMin": 0
      },
      "color": {
        "mode": "palette-classic"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "unit": "short"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "Temperature"
        },
        "properties": [
          {
            "id": "unit",
            "value": "celsius"
          },
          {
            "id": "custom.axisPlacement",
            "value": "auto"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Energy"
        },
        "properties": [
          {
            "id": "unit",
            "value": "percentunit"
          },
          {
            "id": "custom.axisPlacement",
            "value": "auto"
          },
          {
            "id": "custom.hideFrom",
            "value": {
              "tooltip": false,
              "viz": false,
              "legend": false
            }
          },
          {
            "id": "custom.scaleDistribution",
            "value": {
              "type": "linear"
            }
          }
        ]
      }
    ]
  },
  "options": {
    "tooltip": {
      "mode": "multi",
      "sort": "none"
    },
    "legend": {
      "displayMode": "table",
      "placement": "right",
      "calcs": [
        "last",
        "min",
        "max"
      ]
    }
  },
  "targets": [
    {
      "alias": "Temperature",
      "csvWave": {
        "timeStep": 60,
        "valuesCSV": "0,0,2,2,1,1"
      },
      "lines": 10,
      "points": [],
      "pulseWave": {
        "offCount": 3,
        "offValue": 1,
        "onCount": 3,
        "onValue": 2,
        "timeStep": 60
      },
      "refId": "A",
      "scenarioId": "csv_metric_values",
      "stream": {
        "bands": 1,
        "noise": 2.2,
        "speed": 250,
        "spread": 3.5,
        "type": "signal"
      },
      "stringInput": "20,25,30,18,35,20,30,25",
      "datasource": {
        "type": "testdata",
        "uid": "000000051"
      }
    },
    {
      "scenarioId": "random_walk",
      "refId": "C",
      "alias": "Energy",
      "csvWave": {
        "timeStep": 60,
        "valuesCSV": "0,0,2,2,1,1"
      },
      "hide": false,
      "lines": 10,
      "max": 1,
      "min": 0.1,
      "noise": 0.1,
      "points": [],
      "pulseWave": {
        "offCount": 3,
        "offValue": 1,
        "onCount": 3,
        "onValue": 2,
        "timeStep": 60
      },
      "spread": 0.5,
      "startValue": 0,
      "stream": {
        "bands": 1,
        "noise": 2.2,
        "speed": 250,
        "spread": 3.5,
        "type": "signal"
      },
      "stringInput": "",
      "datasource": {
        "type": "testdata",
        "uid": "000000051"
      }
    }
  ]
}
```
</details>

### PR DESCRIPTION
**Pull request by dprokop**
Fixes https://github.com/grafana/grafana/issues/46290

### CODE REVIEW

File: packages/grafana-ui/src/components/TimeSeries/utils.ts [hunk 1]
```diff
@@ -201,6 +201,7 @@ export const preparePlotConfigBuilder: UPlotConfigPrepFn<{
             formatValue: (v) => formattedValueToString(fmt(v)),
             theme,
             grid: { show: customConfig.axisGridShow },
+            show: customConfig.hideFrom?.viz === false,
```
Comment (scottlepp) [inline packages/grafana-ui/src/components/TimeSeries/utils.ts:204]:
```suggestion
            show: !customConfig.hideFrom?.viz,
```

**Review by scottlepp — APPROVED** [review]
LGTM - one small suggestion
