### PR TITLE
A11y: Fix canvas setting button accessibility

### LINKED ISSUE #70973: A11y: Fix keyboard accessibility in `public/app/features/canvas/runtime/ables.tsx`
# How to make progress on this issue

- 🔍 open the file and search for `TODO: fix keyboard a11y`
- ❌ remove the `eslint-disable` comment
- 🔧 fix the lint error(s) that should now be showing
  - this will be heavily dependant on context
  - should you be able to interact with this element via the keyboard or is there another element that already handles the same behaviour via the keyboard?
  - in some cases, the best fix is to **use the correct semantic element** for the job. if something behaves like a button but we want it to look different, we can still use the `<button type="button">` element and style it appropriately. this will handle all our keyboard accessibility needs for us. there's even a handy [`clearButtonStyles`](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Button/Button.tsx#L306) util to undo the basic button styling.
  - if using a `<button>` or other similar interactive element is not appropriate, refer to the documentation [here](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/click-events-have-key-events.md) and [here](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-static-element-interactions.md). this will likely involve setting a `role` and implementing a custom `onKeyPress`
- 🧪 test it!
  - can you interact with this element using the keyboard now?
- 🥳 celebrate for making grafana a better product!

### PR DESCRIPTION
**Pull request by Develer**
**What is this feature?**

This update assigns a role to non-button element to fix accessibility issue.

Fixes #70973 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/canvas/runtime/ables.tsx [hunk 1]
```diff
@@ -38,6 +36,16 @@ export const settingsViewable = (scene: Scene) => ({
           const evt = new PointerEvent('contextmenu', { clientX: event.clientX, clientY: event.clientY });
           container.dispatchEvent(evt);
         }}
+        onKeyDown={(event) => {
+          if (event.key === 'Enter') {
+            const container = moveable.getContainer();
+            const rect = event.currentTarget.getBoundingClientRect();
+            const evt = new PointerEvent('contextmenu', { clientX: rect.x, clientY: rect.y });
+            container.dispatchEvent(evt);
```
Comment (nmarrs) [inline public/app/features/canvas/runtime/ables.tsx:44]: These changes look great! It might make sense though to avoid duplicating the onClick logic and breaking it out into a separate `onSettingsClick` function that we can reference for both the `onClick` and `onKeyDown` props 👍

Comment (Develer) [reply public/app/features/canvas/runtime/ables.tsx:44]: I also thought about it but they have a bit different body function and I decided to keep it separated. Do you have any idea how to optimize it?

Comment (Develer) [reply public/app/features/canvas/runtime/ables.tsx:44]: Yeah, I think we can put it in a separate function, just to do different calculations depending on the event type.

Comment (nmarrs) [reply public/app/features/canvas/runtime/ables.tsx:44]: I was thinking of just consolidating the shared logic more along the lines of
```
const openSettings = () => {
    const container = moveable.getContainer();
    const evt = new PointerEvent('contextmenu', { clientX: event.clientX, clientY: event.clientY });
    container.dispatchEvent(evt);
}
```
where
`onClick={openSettings}` 
and
`onKeyDown={() => { key check {openSettings()}}`

Comment (nmarrs) [reply public/app/features/canvas/runtime/ables.tsx:44]: ah just noticed the difference - yeah should be able to just pass even in and do that logic in the separate function 👍

Comment (Develer) [reply public/app/features/canvas/runtime/ables.tsx:44]: There is a trick with this function, I can't just set two types for event e.g. `event: PointerEvent | KeyboardEvent` or `SyntheticEvent`.

```
const onSettingsClick = (event: any) => {
      let clientX = 0;
      let clientY = 0;

      if (event.type === 'click') {
        clientX = event.clientX;
        clientY = event.clientY;
      } else if (event.type === 'keydown' && event.key === 'Enter') {
        const rect = event.currentTarget.getBoundingClientRect();
        clientX = rect.x;
        clientY = rect.y;
      }

      const container = moveable.getContainer();
      const evt = new PointerEvent('contextmenu', { clientX, clientY });
      container.dispatchEvent(evt);
    };
```

any suggestions here?

Comment (nmarrs) [reply public/app/features/canvas/runtime/ables.tsx:44]: hm what if we just broke this out with 3 functions:

```
const onClick = (event) => {
  openSettings(event.clientX, event.clientY); 
}

const onKeyPress = (event) => {
  const rect = event.currentTarget.getBoundingClientRect();
  openSettings(rect.x, rect.y);
}

const openSettings = (clientX: number, clientY: number) => {
      const container = moveable.getContainer();
      const evt = new PointerEvent('contextmenu', { clientX, clientY });
      container.dispatchEvent(evt);
    };
```

Comment (Develer) [reply public/app/features/canvas/runtime/ables.tsx:44]: Oh, cool, even better! Thanks!

**Review by nmarrs — APPROVED** [review]
🚀
