### PR TITLE
Dashboards: Fix 'Make Editable' button not working in Dashboard Settings

### LINKED ISSUE #60305: Dashboards: 'Make Editable' in uneditable Dashboards Settings doesn't do anything
**What happened**:

When trying to change settings in dashboards with `editable: false`, clicking the "Make Editable" button doesn't do anything.

**What you expected to happen**:

The dashboard becomes editable and I can change settings

**How to reproduce it (as minimally and precisely as possible)**:

1. Have a dashboard with `editable: false` in it.
2. Go to Dashboard Settings
3. Click 'Make Editable'
4. Observe nothing happens.

### PR DESCRIPTION
**Pull request by joshhunt**
**What is this feature?**

PR https://github.com/grafana/grafana/pull/52682 [introduced a regression](https://github.com/grafana/grafana/pull/52682/files#diff-d77b6c1b027bdc1db035aadf8b5ab885f55d0fd1315170dc9c992a9c193d93b0R200-R207) where the "Make Editable" button in Dashboard Settings for uneditable dashboards doesn't do anything.

This fixes that.

**Why do we need this feature?**

So people can edit their dashboards.

**Who is this feature for?**

Admins and editors of Grafana

**Which issue(s) does this PR fix?**:

Fixes #60305

### CODE REVIEW

File: public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx [hunk 1]
```diff
@@ -205,18 +211,10 @@ function getSectionNav(
 }
 
 function MakeEditable({ dashboard }: SettingsPageProps) {
-  const onMakeEditable = () => {
-    dashboard.editable = true;
-    dashboard.meta.canMakeEditable = false;
-    dashboard.meta.canEdit = true;
-    dashboard.meta.canSave = true;
-    // TODO add some kind of reload
```
Comment (joshhunt) [inline public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx:213]: Having a TODO here was so handy to know where to fix it! 😉

File: public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx [hunk 2]
```diff
@@ -205,18 +213,10 @@ function getSectionNav(
...
-  };
-
   return (
     <div>
       <div className="dashboard-settings__header">Dashboard not editable</div>
-      <Button type="submit" onClick={onMakeEditable}>
+      <Button type="submit" onClick={() => dashboard.makeEditable}>
```
Comment (torkelo) [inline public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx:219]: this does not look right :)

Comment (torkelo) [inline public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx:219]:
```suggestion
      <Button type="submit" onClick={() => dashboard.makeEditable()}>
```

**Review by torkelo — APPROVED** [review]
was missing function call in the onClick callback, but otherwise looks good

**Comment by Hipska** [comment]
Actually, it worked. As in you could go back and the dashboard was editable. There was only no visible user feedback indicating clicking the button actually worked..
