### PR TITLE
Loki: Fix label filter expression treating int as string

### LINKED ISSUE #62480: Loki Query Builder -> label filter expression treats int as string resulting in invalid logQL
See image for the actual issue. Expected the query builder to not quote values when it should be a numeric value comparison. So instead of `status_code <= "200"` it should be `status_code <= 200`

string_should_be_int

### PR DESCRIPTION
**Pull request by itsgareth**
**What is this feature?**
fixes a bug where label filters in the query builder treat numbers as strings.

**Why do we need this feature?**
...

**Who is this feature for?**
...

**Which issue(s) does this PR fix?**:
Fixes #62480

**Special notes for your reviewer**:
...

### CODE REVIEW

File: public/app/plugins/datasource/loki/querybuilder/operationUtils.ts [hunk 1]
```diff
@@ -148,7 +148,7 @@ function operationWithRangeVectorRenderer(
 }
 
 export function labelFilterRenderer(model: QueryBuilderOperation, def: QueryBuilderOperationDef, innerExpr: string) {
-  if (model.params[1] === '<' || model.params[1] === '>') {
+  if (model.params[1] === '<' || model.params[1] === '>' || /\d/.test(model.params[2] as string)) {
```
Comment (matyax) [inline public/app/plugins/datasource/loki/querybuilder/operationUtils.ts:151]: First question here (specially by looking at the source of this bug): what about `>=` and `<=`?

Comment (gwdawson) [reply public/app/plugins/datasource/loki/querybuilder/operationUtils.ts:151]: looking at this now, they should all be caught by `/\d/.test`.
so `model.params[1] === '<' || model.params[1] === '>'` shouldn't even be necessary now. 👀

Comment (matyax) [inline public/app/plugins/datasource/loki/querybuilder/operationUtils.ts:151]: Then, I would discourage you from using 1) regexes and 2) type assertions:

```suggestion
  if (model.params[1] === '<' || model.params[1] === '>' || Number.isNaN(Number(model.params[2])) === false) {
```

**Review by matyax — COMMENTED** [review]
Finally, we need a couple of tests cases for `labelFilterRenderer()` to assert, beyond looking at the code, that it's doing what it's supposed to do.

File: public/app/plugins/datasource/loki/querybuilder/operationUtils.ts (hunk 1 above)
Comment (matyax) [reply public/app/plugins/datasource/loki/querybuilder/operationUtils.ts:151]: I would defer that to @ivanahuckova , who may have more context on why are we checking for operators here.

My suspicion was that `>, <, <=, and >=` only support numbers, while the rest threat the argument as string, but I can't back that up.

Comment (matyax) [reply public/app/plugins/datasource/loki/querybuilder/operationUtils.ts:151]: BTW, the `.isNaN()` is necessary because `NaN` is not false, or null, or undefined, it's just NaN.

File: public/app/plugins/datasource/loki/querybuilder/operationUtils.ts [hunk 2]
```diff
@@ -148,7 +148,7 @@ function operationWithRangeVectorRenderer(
 }
 
 export function labelFilterRenderer(model: QueryBuilderOperation, def: QueryBuilderOperationDef, innerExpr: string) {
-  if (model.params[1] === '<' || model.params[1] === '>') {
+  if (!Number.isNaN(Number(model.params[2]))) {
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/loki/querybuilder/operationUtils.ts:151]: We want to decide about this based on `operator`, not based on value. So we just want to check for following operators: `<`, `<=`, `>=` `>`. 

This is because for all other operators, such as `=`, `=~`, ... the query should include string, not number.

**Review by ivanahuckova — CHANGES_REQUESTED** [review]

File: public/app/plugins/datasource/loki/querybuilder/operationUtils.ts (hunk 2 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/querybuilder/operationUtils.ts:151]: @svennergr tried it in here https://grafana.com/docs/loki/latest/logql/analyzer/?query=%7C+logfmt+%7C+duration+%3E+9s&line%5B%5D=level%3Dinfo+ts%3D2022-03-23T11%3A55%3A29.846163306Z+caller%3Dmain.go%3A112+msg%3D%22Starting+Grafana+Enterprise+Logs%22+duration%3D10s and comparing durations (and probably bytes as well) works.

File: public/app/plugins/datasource/loki/querybuilder/operationUtils.test.ts [hunk 3]
```diff
@@ -167,13 +167,43 @@ describe('labelFilterRenderer', () => {
...
-    expect(labelFilterRenderer(MOCK_MODEL, MOCK_DEF, MOCK_INNER_EXPR)).toBe('{job="grafana"} | test = `one`');
+  it('should wrap the label value in `` when operator is "="', () => {
+    MOCK_MODEL.params = ['label', '=', 'value'];
+    expect(labelFilterRenderer(MOCK_MODEL, MOCK_DEF, MOCK_INNER_EXPR)).toBe('{job="grafana"} | label = `value`');
   });
 
-  it('should not backticks if the value is a number', () => {
-    MOCK_MODEL.params = ['test', '=', '3'];
-    expect(labelFilterRenderer(MOCK_MODEL, MOCK_DEF, MOCK_INNER_EXPR)).toBe('{job="grafana"} | test = 3');
+  it('should wrap the label value in `` when operator is "!="', () => {
```
Comment (matyax) [inline public/app/plugins/datasource/loki/querybuilder/operationUtils.test.ts:175]: Before you wrap up the changes in this PR, I'd recommend you to use `it.each` and group the test cases for extra clarity.  https://jestjs.io/es-ES/docs/api#testeachtablename-fn-timeout

Comment (matyax) [reply public/app/plugins/datasource/loki/querybuilder/operationUtils.test.ts:175]: That is, `it.each(['<', '<=', '>', '>='])()`, and another for the other. There are also other examples in our repo.

Comment (gwdawson) [reply public/app/plugins/datasource/loki/querybuilder/operationUtils.test.ts:175]: ooo i didn't know this existed, thanks.

**Review by ivanahuckova — APPROVED** [review]
Nice job! LGTM. Great idea to use `it.each` tests for this!

**Review by matyax — APPROVED** [review]
👌
