### PR TITLE
Instrumentation: Check embedded errors in query data response for plugin metrics/logs status label

### LINKED ISSUE #76769: Instrumentation: Plugin metrics/logs status label doesn't take embedded errors in query data response into consideration
The status label for plugin metrics and logs currently only looks at the returned error from a backend plugin request and sets it to one of _ok_, _error_, _cancelled_, see code below
https://github.com/grafana/grafana/blob/756df61a8820d66e6bfa0d9c8cd69ec88070ee82/pkg/services/pluginsintegration/clientmiddleware/metrics_middleware.go#L119-L128
https://github.com/grafana/grafana/blob/5cc3a3f1edded3797ffa4bf9e806905c48644f31/pkg/services/pluginsintegration/clientmiddleware/logger_middleware.go#L41-L51

If no error is returned the status is set to _ok_. However, if query data request there can be errors embedded within the data responses of the query data response together with proper data responses, e.g.
```json
"response": {
  "a": {
    "frames": ...
  },
  "b": {
    "error": "something went wrong"
  }
}
```

Given https://github.com/grafana/grafana/issues/76140 and https://github.com/grafana/grafana/pull/76236, we should probably take embedded errors in query data response into account for setting the status. 

Question is if the status_source from data response should be used to decide whether status is _ok_ or _error_?

### PR DESCRIPTION
**Pull request by marefr**
**What is this feature?**

Check embedded errors in query data response for plugin metrics/logs status label.

_Plugin Request Completed_ log messages are now logged with info level if status=ok, otherwise error level.

Before the changes (see status in bold):
ERROR[11-03|12:30:09] Partial data response error              logger=plugin.instrumentation endpoint=queryData pluginId=prometheus dsName="Prometheus 2.x" dsUID=000000028 uname=admin traceID=2edeba66a8fedcbfd4630304653e64b1 refID=B error="Post \"http://localhost:9090/api/v1/query_range\": dial tcp 127.0.0.1:9090: connect: connection refused"
ERROR[11-03|12:30:09] Partial data response error              logger=plugin.instrumentation endpoint=queryData pluginId=prometheus dsName="Prometheus 2.x" dsUID=000000028 uname=admin traceID=2edeba66a8fedcbfd4630304653e64b1 refID=A error="Post \"http://localhost:9090/api/v1/query_range\": dial tcp 127.0.0.1:9090: connect: connection refused"
INFO [11-03|12:30:09] Plugin Request Completed                 logger=plugin.instrumentation endpoint=queryData pluginId=prometheus dsName="Prometheus 2.x" dsUID=000000028 uname=admin traceID=2edeba66a8fedcbfd4630304653e64b1 **status=ok** duration=1.041192ms eventName=grafana-data-egress time_before_plugin_request=1.298129ms

After the changes (see status in bold):
ERROR[11-10|13:33:35] Partial data response error              logger=plugin.instrumentation endpoint=queryData pluginId=promet
heus dsName="Prometheus 2.x" dsUID=000000028 uname=admin traceID=8256f0e068a57be409ed0d60f1d9d49b refID=A error="Post \"http://
localhost:9090/api/v1/query_range\": dial tcp 127.0.0.1:9090: connect: connection refused"                                     
ERROR[11-10|13:33:35] Partial data response error              logger=plugin.instrumentation endpoint=queryData pluginId=promet
heus dsName="Prometheus 2.x" dsUID=000000028 uname=admin traceID=8256f0e068a57be409ed0d60f1d9d49b refID=B error="Post \"http://
localhost:9090/api/v1/query_range\": dial tcp 127.0.0.1:9090: connect: connection refused"                                     
**ERROR**[11-10|13:33:35] Plugin Request Completed                 logger=plugin.instrumentation endpoint=queryData pluginId=promet
heus dsName="Prometheus 2.x" dsUID=000000028 uname=admin traceID=8256f0e068a57be409ed0d60f1d9d49b **status=error** duration=1.07578
8ms eventName=grafana-data-egress time_before_plugin_request=1.034101ms status_source=plugin 

**Why do we need this feature?**

To see in logs/metrics that there was a problem with plugin request even though it returned a response.

**Who is this feature for?**

Grafana and plugin operators

**Which issue(s) does this PR fix?**:
Fixes #76769 

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/services/pluginsintegration/clientmiddleware/logger_middleware.go [hunk 1]
```diff
@@ -37,25 +36,18 @@ type LoggerMiddleware struct {
...
-	}
+	status, err := fn(ctx)
 	logParams := []any{
 		"status", status,
 		"duration", time.Since(start),
 		"eventName", "grafana-data-egress",
 		"time_before_plugin_request", timeBeforePluginRequest,
 	}
-	if status == statusError {
+	if err != nil {
```
Comment (marefr) [inline pkg/services/pluginsintegration/clientmiddleware/logger_middleware.go:50]: Just noticed we're using info as log level below for any message - maybe we should use error level when status=error?

File: pkg/services/pluginsintegration/clientmiddleware/utils.go [hunk 2]
```diff
@@ -23,3 +39,36 @@ type callResourceResponseSenderFunc func(res *backend.CallResourceResponse) erro
...
+
+	status := requestStatusOK
+
+	if res != nil {
+		for _, dr := range res.Responses {
+			if dr.Error != nil {
+				s, _ := requestStatusFromError(dr.Error)
+				if s > status {
+					status = s
+				}
```
Comment (andresmgot) [inline pkg/services/pluginsintegration/clientmiddleware/utils.go:68]: does it make sense to keep iterating if one error is found?

**Review by andresmgot — COMMENTED** [review]
Some minor comments here

File: pkg/services/pluginsintegration/clientmiddleware/utils.go [hunk 3]
```diff
@@ -23,3 +39,36 @@ type callResourceResponseSenderFunc func(res *backend.CallResourceResponse) erro
 func (fn callResourceResponseSenderFunc) Send(res *backend.CallResourceResponse) error {
 	return fn(res)
 }
+
+func requestStatusFromError(err error) (requestStatus, error) {
```
Comment (xnyo) [inline pkg/services/pluginsintegration/clientmiddleware/utils.go:43]: Any reason why this returns an `error`, but it's always equal to the provided `err` (at least for now)?

File: pkg/services/pluginsintegration/clientmiddleware/metrics_middleware.go [hunk 4]
```diff
@@ -109,27 +108,20 @@ func (m *MetricsMiddleware) instrumentPluginRequestSize(ctx context.Context, plu
...
-			status = statusCancelled
-		}
-	}
+	status, err := fn(ctx)
 	elapsed := time.Since(start)
 
 	pluginRequestDurationLabels := []string{pluginCtx.PluginID, endpoint, target}
-	pluginRequestCounterLabels := []string{pluginCtx.PluginID, endpoint, status, target}
-	pluginRequestDurationSecondsLabels := []string{"grafana-backend", pluginCtx.PluginID, endpoint, status, target}
+	pluginRequestCounterLabels := []string{pluginCtx.PluginID, endpoint, status.String(), target}
```
[the remark this answers is not in the document]
Comment (xnyo) [reply pkg/services/pluginsintegration/clientmiddleware/metrics_middleware.go:123]: `status` is a `requestStatus` which is `type requestStatus int`. Its zero-value is `0` rather than `nil`, so no panic :smiley:

File: pkg/services/pluginsintegration/clientmiddleware/logger_middleware.go (hunk 1 above)
Comment (xnyo) [reply pkg/services/pluginsintegration/clientmiddleware/logger_middleware.go:50]: sounds good to me as well!

**Review by xnyo — APPROVED** [review]
LGTM! Awesome work :rocket: Just left a few minor comments:

File: pkg/services/pluginsintegration/clientmiddleware/utils.go (hunk 2 above)
Comment (marefr) [reply pkg/services/pluginsintegration/clientmiddleware/utils.go:68]: Good question. In general we should probably stop, but then we need yet another check. I'll consider it

File: pkg/services/pluginsintegration/clientmiddleware/utils.go (hunk 3 above)
Comment (marefr) [reply pkg/services/pluginsintegration/clientmiddleware/utils.go:43]: I think it was for convenience to use the return values from the function directly. I'll look into it

File: pkg/services/pluginsintegration/clientmiddleware/utils.go (hunk 2 above)
Comment (marefr) [reply pkg/services/pluginsintegration/clientmiddleware/utils.go:68]: Fixed

Comment (marefr) [reply pkg/services/pluginsintegration/clientmiddleware/utils.go:68]: Made error highest priority instead of cancelled. Should make more sense I think

**Review by xnyo — APPROVED** [review]
LGTM! :partying_face:

**Review by andresmgot — APPROVED** [review]
