### PR TITLE
Color: fix alpha calculation < 16/255 and State-timeline threshold alpha

### LINKED ISSUE #35606: State timeline does not respect transparency
**What happened**:
I changed the color on a state timeline panel to one with some amount of transparency. The alpha component of the color was ignored and the color was displayed without any transparency (100% alpha).

**What you expected to happen**:
The alpha component of the color to be respected and the color to appear transparent.

This does seems to work correctly on all other panels I tested, so I think the issue is limited to the state timeline panel.

See the following screen recording for a demonstration: [screen_recording.zip](https://github.com/grafana/grafana/files/6645820/screen_recording.zip)

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a state timeline panel.
2. Change the color to one with some amount of transparency (using any one of the multiple methods to select a color) .

**Environment**:
- Grafana version: v8.0.1
- Data source type & version: InfluxDB 1.8.6
- OS Grafana is installed on: The official Docker image (https://hub.docker.com/r/grafana/grafana) in Docker version 20.10.6 build 370c289 on Ubuntu 20.04.2 LTS
- User OS & Browser: MacOS 10.15.7 & Chrome
- Grafana plugins: None

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/grafana/issues/35606

unfortunately, this has to reparse any non-hex colors prior to `field.display()` caching. ideally the threshold color picker would operate in pure #rgb or #rgba mode, or the thresholds would store the color in that uniform format :(

this also fixes the alpha() function to properly 0-pad alpha values < 16/255.

### CODE REVIEW

File: packages/grafana-data/src/field/fieldOverrides.ts [hunk 1]
```diff
@@ -216,15 +217,28 @@ function cachingDisplayProcessor(disp: DisplayProcessor, maxCacheSize = 2500): D
...
+
+      // re-parse into hex string :(
+      if (v.color && v.color[0] !== '#') {
+        let color = tinycolor(v.color);
+
+        v = {
+          ...v,
+          color: color.getAlpha() < 1 ? color.toHex8String() : color.toHexString(),
+        };
+      }
```
Comment (torkelo) [inline packages/grafana-data/src/field/fieldOverrides.ts:237]: This feels a bit fragile, or somehow in the wrong place (cached display processor), is there anywhere else this could go? can we move this to the alpha function instead?

Comment (leeoniya) [reply packages/grafana-data/src/field/fieldOverrides.ts:237]: the problem is that this op is expensive. ideally threshold.color strings are all in #rgb or #rgba strings so this whole thing can go away, but right now they're either #rgb when chosen from the palette or rgba() when chosen from the Custom tab in the picker.

can we make this uniform?

Comment (torkelo) [reply packages/grafana-data/src/field/fieldOverrides.ts:237]: Maybe but would require translating it back to rgba in color picker as that is much easier to edit manually for users (input field in color spectrum picker)

Comment (leeoniya) [reply packages/grafana-data/src/field/fieldOverrides.ts:237]: agreed, but that's much cheaper to do there than to do it for every datapoint on every update.

if that seems easy/doable, feel free to push the changes to this PR and drop the section above. (it's a hack for sure).

Comment (ryantxu) [reply packages/grafana-data/src/field/fieldOverrides.ts:237]: I'm not sure where/how to think about existing saved colors... but perhaps we should save colors in a prefered format here:
https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/ColorPicker/ColorInput.tsx#L56

Comment (leeoniya) [reply packages/grafana-data/src/field/fieldOverrides.ts:237]: i changed it to this, but it never reaches this code (this might be a legacy picker?)

```js
    if (newColor.isValid()) {
      let hexColor = newColor.toString(newColor.getAlpha() === 1 ? 'hex6' : 'hex8');
      this.updateColor(hexColor);
    }
```

Comment (torkelo) [reply packages/grafana-data/src/field/fieldOverrides.ts:237]: This is used and it reaches this point for me. But this is just the text input at the bottom of the spectrum picker

Comment (torkelo) [reply packages/grafana-data/src/field/fieldOverrides.ts:237]: If you are looking for a single place to update stored color it would be: https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/ColorPicker/ColorPickerPopover.tsx#L56 

My main problem with this would be we would have to translate back to rgba as that is what the user will see and type in the input

Comment (leeoniya) [reply packages/grafana-data/src/field/fieldOverrides.ts:237]: > My main problem with this would be we would have to translate back to rgba as that is what the user will see and type in the input

doing this conversion in the picker when necessary during config time seems more sensible to me than having to potentially parse `rgb()` strings to determine opacity for each of potentially tens of thousands of data points?

Comment (torkelo) [reply packages/grafana-data/src/field/fieldOverrides.ts:237]: Agree fully, just we have to convert back so user can edit in a more friendly format

File: packages/grafana-data/src/field/fieldOverrides.ts [hunk 2]
```diff
@@ -216,15 +217,28 @@ function cachingDisplayProcessor(disp: DisplayProcessor, maxCacheSize = 2500): D
...
         cache.clear();
       }
 
       v = disp(value);
+
+      // re-parse into hex string :(
+      if (v.color && v.color[0] !== '#') {
+        let color = tinycolor(v.color);
+
+        v = {
```
Comment (ryantxu) [inline packages/grafana-data/src/field/fieldOverrides.ts:233]: lets just mutate color here -- it is not yet passed out of context

File: packages/grafana-data/src/field/fieldOverrides.ts (hunk 1 above)
Comment (leeoniya) [reply packages/grafana-data/src/field/fieldOverrides.ts]: there is ongiong work in https://github.com/grafana/grafana/pull/37173 to improve this, but let's merge this for the fix and improve in a followup. eventually this whole cache should probably be moved into StreamingDataFrame, now that https://github.com/grafana/grafana/pull/35465 is merged and we have more info on how to be smarter about evictions.

**Review by ryantxu — APPROVED** [review]
This seems good -- with @nikki-kiga's change in https://github.com/grafana/grafana/pull/37173 we should hit the condition less frequently, and can potentially get rid of the cache entirely if we know things are in hex

**Comment by leeoniya** [comment]
this did not make it into `8.1.0-beta3` due to the above backport initially failing due to unrelated issues, and other color-related backports were merged ahead of it. i was sleeping when the release team pinged me about it.

i just un-frankensteined the backport and it should land in 8.1.0 final.
