### PR TITLE
Short URL: Include orgId in generated short URLs

### LINKED ISSUE #33813: Shorten  URL doesn't take orgId into account
**What happened**: Using _Shorten URL_ doesn't include the `orgId`. If somebody tries to open the link whilst in a different org., they get a 404.

**What you expected to happen**: The shortened URL also contains the `orgId`, so that people opening the link are automatically switched to the correct org.

**How to reproduce it (as minimally and precisely as possible)**:
 * Create 2 organisations in your Grafana (for example: "Main Org." with orgId=1 and "Test Org." with orgId=2)
 * Create a dashboard in Main Org. (URL in address bar contains `&orgId=1`)
 * Click _Share_ button and use _Shorten URL_, click _Copy_ to copy the shortened URL to your clipboard
 * Switch to Test Org. (URL in address bar now has `&orgId=2`)
 * Try to open the shortened URL
 * Result: 404 "Page not found"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.3

### PR DESCRIPTION
**Pull request by farodin91**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #33813

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by marefr** [comment]
Thanks. Given the recent discussions https://github.com/grafana/grafana/issues/33813 we suggest a different approach. Please have a look

**Comment by farodin91** [comment]
@marefr I updated the commit. Now i don't have any idea to test it.

**Review by marefr — COMMENTED** [review]
See comment. 

Regarding testing this. Dashboard -> Share -> link and generate short url -> copy should include org id

**Comment by farodin91** [comment]
> See comment.
> 
> Regarding testing this. Dashboard -> Share -> link and generate short url -> copy should include org id

I would like to add ci test.

**Comment by farodin91** [comment]
I tested the implementation on local build docker image. Works great.

**Review by ying-jeanne — APPROVED** [review]

**Review by ying-jeanne — DISMISSED** [review]
@farodin91 just one thing, could you update the doc about API response here: https://github.com/grafana/grafana/blob/main/docs/sources/http_api/short_url.md

**Comment by marefr** [comment]
> > See comment.
> 
> > 
> 
> > Regarding testing this. Dashboard -> Share -> link and generate short url -> copy should include org id
> 
> 
> 
> I would like to add ci test.

@farodin91 then you would have to do something like this https://github.com/grafana/grafana/blob/7646246d8cd9ebfc8695318c217552986f99c6cc/pkg/api/folder_test.go#L31 and mock the short url service. If that's to involved you might extract the part that generates the returned URL to a separate function and add tests for that one.

File: pkg/api/short_url.go [hunk 1]
```diff
@@ -15,12 +15,12 @@ import (
 
 // createShortURL handles requests to create short URLs.
 func (hs *HTTPServer) createShortURL(c *models.ReqContext, cmd dtos.CreateShortURLCmd) response.Response {
-	hs.log.Debug("Received request to create short URL", "path", cmd.Path)
+	c.Logger.Debug("Received request to create short URL", "path", cmd.Path)
```
Comment (marefr) [inline pkg/api/short_url.go:18]:
```suggestion
	hs.log.Debug("Received request to create short URL", "path", cmd.Path)
```

File: pkg/api/short_url.go [hunk 2]
```diff
@@ -15,12 +15,12 @@ import (
...
 
 	cmd.Path = strings.TrimSpace(cmd.Path)
 
 	if path.IsAbs(cmd.Path) {
-		hs.log.Error("Invalid short URL path", "path", cmd.Path)
+		c.Logger.Error("Invalid short URL path", "path", cmd.Path)
```
Comment (marefr) [inline pkg/api/short_url.go:23]:
```suggestion
		hs.log.Error("Invalid short URL path", "path", cmd.Path)
```

**Review by marefr — APPROVED** [review]
LGTM added some suggestions since CI is stalled for whatever reason and I couldn't push to your branch.

File: pkg/api/short_url.go (hunk 1 above)
Comment (farodin91) [reply pkg/api/short_url.go]: I had replaced hs.log with c.logger. Otherwise I would have to set log which is private value.

File: pkg/api/short_url_test.go [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+func createShortURLScenario(t *testing.T, desc string, url string, routePattern string, cmd dtos.CreateShortURLCmd, fn scenarioFunc) {
+	t.Run(fmt.Sprintf("%s %s", desc, url), func(t *testing.T) {
+		defer bus.ClearBusHandlers()
+
+		sqlStore := sqlstore.InitTestDB(t)
+		hs := HTTPServer{
+			Cfg: setting.NewCfg(),
+			ShortURLService: &shorturls.ShortURLService{
+				SQLStore: sqlStore,
+			},
```
Comment (marefr) [inline pkg/api/short_url_test.go:52]:
```suggestion
			},
		log: log.New("test"),
```

File: pkg/api/short_url_test.go [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+	"github.com/grafana/grafana/pkg/api/routing"
+	"github.com/grafana/grafana/pkg/bus"
+	"github.com/grafana/grafana/pkg/models"
+	"github.com/grafana/grafana/pkg/services/shorturls"
+	"github.com/grafana/grafana/pkg/services/sqlstore"
+	"github.com/grafana/grafana/pkg/setting"
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+	"regexp"
+	"testing"
```
Comment (marefr) [inline pkg/api/short_url_test.go:17]:
```suggestion
	"encoding/json"
	"fmt"
	"regexp"
	"testing"

	"github.com/grafana/grafana/pkg/api/dtos"
	"github.com/grafana/grafana/pkg/api/response"
	"github.com/grafana/grafana/pkg/api/routing"
	"github.com/grafana/grafana/pkg/bus"
	"github.com/grafana/grafana/pkg/infra/log"
	"github.com/grafana/grafana/pkg/models"
	"github.com/grafana/grafana/pkg/services/shorturls"
	"github.com/grafana/grafana/pkg/services/sqlstore"
	"github.com/grafana/grafana/pkg/setting"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
```

**Review by marefr — COMMENTED** [review]
Suggestions

File: pkg/api/short_url_test.go [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+
+		createShortURLScenario(t, "When calling POST on", "/api/short-urls", "/api/short-urls", cmd,
+			func(sc *scenarioContext) {
+				callCreateShortURL(sc)
+
+				shortUrl := dtos.ShortURL{}
+				err := json.NewDecoder(sc.resp.Body).Decode(&shortUrl)
+				require.NoError(t, err)
+				assert.Equal(t, 200, sc.resp.Code)
+				assert.Regexp(t, regexp.MustCompile("/goto/(.+)\\?orgId=(.+)"), shortUrl.URL)
```
Comment (marefr) [inline pkg/api/short_url_test.go:36]:
```suggestion
				require.Equal(t, 200, sc.resp.Code)
				require.Regexp(t, "/goto/(.+)\\?orgId=(.+)", shortUrl.URL)
```

File: pkg/api/short_url_test.go [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+	"github.com/grafana/grafana/pkg/api/dtos"
+	"github.com/grafana/grafana/pkg/api/response"
+	"github.com/grafana/grafana/pkg/api/routing"
+	"github.com/grafana/grafana/pkg/bus"
+	"github.com/grafana/grafana/pkg/infra/log"
+	"github.com/grafana/grafana/pkg/models"
+	"github.com/grafana/grafana/pkg/services/shorturls"
+	"github.com/grafana/grafana/pkg/services/sqlstore"
+	"github.com/grafana/grafana/pkg/setting"
+	"github.com/stretchr/testify/assert"
```
Comment (marefr) [inline pkg/api/short_url_test.go:18]:
```suggestion
```

File: pkg/api/short_url_test.go [hunk 7]
```diff
@@ -0,0 +1,69 @@
+package api
+
+import (
+	"encoding/json"
+	"fmt"
+	"regexp"
```
Comment (marefr) [inline pkg/api/short_url_test.go:6]:
```suggestion
```

File: pkg/api/short_url_test.go [hunk 8]
```diff
@@ -0,0 +1,68 @@
...
+	t.Run(fmt.Sprintf("%s %s", desc, url), func(t *testing.T) {
+		defer bus.ClearBusHandlers()
+
+		sqlStore := sqlstore.InitTestDB(t)
+		hs := HTTPServer{
+			Cfg: setting.NewCfg(),
+			ShortURLService: &shorturls.ShortURLService{
+				SQLStore: sqlStore,
+			},
+		log: log.New("test"),
```
Comment (marefr) [inline pkg/api/short_url_test.go:53]:
```suggestion
			log: log.New("test"),
```

**Comment by farodin91** [comment]
@marefr Should i squash everything?

**Comment by marefr** [comment]
@farodin91 Thank you for contributing to Grafana! We squash and merge so there's never any need of squashing/force-pushing in PR's.

**Comment by ivanahuckova** [comment]
Thank you for your awesome contribution @farodin91! 🔥
