### PR TITLE
Prometheus: Fix recording rules expansion

### LINKED ISSUE #19196: Prometheus: Recording rule expansion fails with multiple selectors
0. Explore with Prometheus that also has recording rules defined
1. Run a query that uses a recording rule, e.g., `instance:node_load1_per_cpu:ratio{job="default/node-exporter", instance="abc"}` from the node mixin
2. Click on "Expand rules".

Result: The selector is outside the braces, which looks right, but is not a valid query.
```
(node_load1{job="default/node-exporter"} / instance:node_num_cpu:sum{job="default/node-exporter"}){job="default/node-exporter", instance="abc"}
```

Expected:
```
(node_load1{job="default/node-exporter", instance="abc"} / instance:node_num_cpu:sum{job="default/node-exporter", instance="abc"})
```

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
This PR fixes expansion of recording rules with multiple selectors and with labels. The main logic uses `addLabelToQuery` function. I have also added test coverage for more possible recording rules.

I have added recording rules to `devenv/prometheus2`, so the testing of this PR is easier and in the future, it is faster to work on issues related to recording rules.

Kapture 2020-05-21 at 12 18 35

**Which issue(s) this PR fixes**:

Fixes #19196

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/language_utils.ts [hunk 1]
```diff
@@ -111,7 +112,55 @@ export function parseSelector(query: string, cursorOffset = 1): { labelKeys: any
...
+  const indexOfRegexMatch = expr.match(regex).index;
+  const exprBeforeRegexMatch = expr.substr(0, indexOfRegexMatch + 1);
+  const exprAfterRegexMatch = expr.substr(indexOfRegexMatch + 1);
+
+  // Retrieve labels (as a string). Our exprAfterRegexMatch starts with "{" and we need to find closest matching bracket.
+  // We want to leave out the brackets and keep just string in labelsInString.
+  const stringOfLabels = exprAfterRegexMatch.substr(1, exprAfterRegexMatch.indexOf('}') - 1);
+
+  // Create array with labels
+  const arrayOfLabels = stringOfLabels.split(',');
```
Comment (davkal) [inline public/app/plugins/datasource/prometheus/language_utils.ts:144]: Do we need to be careful about label values with commas? This would break currently:
```
    expect(
      expandRecordingRules('metricA{label1="value1",label2="value,2"}', {
        metricA: 'rate(fooA[])',
      })
    ).toBe('rate(fooA{label1="value1",label2="value,2"}[])');
```

Comment (davkal) [reply public/app/plugins/datasource/prometheus/language_utils.ts:144]: Line 82 in that file already does some sort of label parsing, perhaps you can use something similar.

File: public/app/plugins/datasource/prometheus/language_utils.ts [hunk 2]
```diff
@@ -111,7 +112,55 @@ export function parseSelector(query: string, cursorOffset = 1): { labelKeys: any
...
+
+  // Transform strings into object with specified key, operator and value
+  // Uses the same regex and similar logic as function addLabelToSelector in add_label_to_query
+  const arrayOfLabelObjects = arrayOfLabels.map(string => {
+    const labelRegexp = /(\w+)\s*(=|!=|=~|!~)\s*("[^"]*")/g;
```
Comment (davkal) [inline public/app/plugins/datasource/prometheus/language_utils.ts:149]: There is already a similar regexp defined in line 47. Can we use that one, or fix it, or put a comment on why this needs a different one?

**Review by davkal — COMMENTED** [review]
Works great in the given cases. Still need to think about edge cases a bit. I'm actually unsure if commas are supported in label values (probably they are).

**Comment by ivanahuckova** [comment]
@davkal great catch. I have checked and interestingly there are [no restrictions on label values in prometheus](https://github.com/prometheus/client_java/issues/28). I have fixed the implementation and included the test with comma in the label value. 🙂

**Review by davkal — APPROVED** [review]
LGTM

**Comment by valdemarpavesi** [comment]
Hello,

on Grafana 7.4.0 expand rules is not working:

image

https://community.grafana.com/t/query-contains-recording-rules-expand-rules-cut-in-the-middle/42628


regards
Valdemar

**Comment by ivanahuckova** [comment]
Hello @valdemarpavesi, I have checked and it was still working for me. Would you mind creating a [new issue](https://github.com/grafana/grafana/issues/new?assignees=&labels=type%3A+bug&template=1-bug_report.md) and providing more details on how to recreate the issue. Thank you very much! 🙏
