### PR TITLE
fix: return id from api when creating new annotation, fixes #9798

### LINKED ISSUE #9798: POSTing an annotation does not return its ID
When we POST an annotation with the http api

It would be great to get the ID of the new annotation in the response

### PR DESCRIPTION
**Pull request by marefr**
Return id from api when creating new annotation/graphite annotation

When creating a region annotation the response will include both
id (region start id) and endId (region end id), if not only id.

closes https://github.com/grafana/grafana/issues/9798

### CODE REVIEW

File: pkg/api/annotations.go [hunk 1]
```diff
@@ -48,12 +49,13 @@ func (e *CreateAnnotationError) Error() string {
 	return e.message
 }
 
-func PostAnnotation(c *middleware.Context, cmd dtos.PostAnnotationsCmd) Response {
+func PostAnnotation(c *middleware.Context, cmd dtos.PostAnnotationsCmd) {
```
Comment (bergquist) [inline pkg/api/annotations.go]: Its currently kinda mixed between using `Response` or not. 

Last time I and @torkelo talked about this we agreed on using Response since its easy to forget to return after using `c.JsonApiErr`. So using Response is preferred. 

This is the way to do custom return types using `Response` https://github.com/grafana/grafana/blob/master/pkg/api/datasources.go#L149

**Review by bergquist — CHANGES_REQUESTED** [review]

File: pkg/api/annotations.go (hunk 1 above)
Comment (marefr) [reply pkg/api/annotations.go]: Fixed

**Review by bergquist — APPROVED** [review]
