### PR TITLE
Search: Preserves search filters when navigating to another page

### LINKED ISSUE #65710: Search: Navigating to a dashboard from search should not clear the filters
**What happened**:

When you are searching for a dashboard, if you get a long list of results you might click one, but then if it is not the correct one and you navigate back to search you have lost your previous search term (and any other filters):

https://user-images.githubusercontent.com/100691367/229136349-4634ea97-177c-4a2a-9907-25d1940e1b67.mov

**What you expected to happen**:

I expect to be able to go back to search and still get the same list of results.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to search https://play.grafana.org/dashboards
2. Search for a term and click one of the results
3. Using the breadcrumbs click on "Dashboards" to go to search again

**Anything else we need to know?**:

If you search for a term and then navigate to a different page, like "Playlists" and then back to "Dashboards" it will maintain your search term, it is only if you select a dashboard that it clears the filters.

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by khushijain21**
**Which issue(s) does this PR fix?**:

This PR fixes #65710

**Who is this feature for?**

Navigating to dashboard from search should not clear the filters

### CODE REVIEW

File: public/app/features/search/state/SearchStateManager.ts [hunk 1]
```diff
@@ -252,9 +252,9 @@ export class SearchStateManager extends StateManagerBase<SearchState> {
    */
   onSearchItemClicked = (e: React.MouseEvent<HTMLElement>) => {
     // Clear some filters only if we're not opening a search item in a new tab
-    if (!e.altKey && !e.ctrlKey && !e.metaKey) {
-      this.setState({ tag: [], starred: false, sort: undefined, query: '', folderUid: undefined });
-    }
+    // if (!e.altKey && !e.ctrlKey && !e.metaKey) {
+    //   this.setState({ tag: [], starred: false, sort: undefined, query: '', folderUid: undefined });
+    // }
```
Comment (JoaoSilvaGrafana) [inline public/app/features/search/state/SearchStateManager.ts:257]: Should just remove all these comments, otherwise it works as expected 👍

**Comment by JoaoSilvaGrafana** [comment]
@khushijain21 could you merge grafana:main back to your branch? This might solve the issue with failing tests

**Review by JoaoSilvaGrafana — APPROVED** [review]
Nice 👏
