### PR TITLE
Search: Fix empty folder details for nested folder items

### LINKED ISSUE #74433: Nested folders: Empty folder details from search handler response for folder items
Even though the search query returns inherited items when the nested folders feature toggle is enabled, the folder related columns  in the returned rows are empty.
Considering the following example query, the dashboards/folders with user permissions are returned by the inner query `ids` while the folder details come from the `LEFT OUTER JOIN dashboard AS folder` which does not consider the nested structure.

<details><summary>Example search query</summary>
<p>

```
WITH RECURSIVE RecQry0 AS (
                        SELECT uid, parent_uid, org_id FROM folder WHERE uid IN (SELECT substr(scope, 13) FROM permission WHERE scope LIKE 'folders:uid:%'  AND role_id IN(SELECT id FROM role INNER JOIN (
                        SELECT ur.role_id
                        FROM user_role AS ur
                        WHERE ur.user_id = 1
                        AND (ur.org_id = 1 OR ur.org_id = 0)
                UNION
                        SELECT br.role_id FROM builtin_role AS br
                        WHERE br.role IN ("Viewer")
                        AND (br.org_id = 1 OR br.org_id = 0)
                ) as all_role ON role.id = all_role.role_id)  AND action = "dashboards:read")
                        UNION ALL SELECT f.uid, f.parent_uid, f.org_id FROM folder f INNER JOIN RecQry0 r ON f.parent_uid = r.uid and f.org_id = r.org_id
                ),RecQry1 AS (
                        SELECT uid, parent_uid, org_id FROM folder WHERE uid IN (SELECT substr(scope, 13) FROM permission WHERE scope LIKE 'folders:uid:%' AND role_id IN(SELECT id FROM role INNER JOIN (
                        SELECT ur.role_id
                        FROM user_role AS ur
                        WHERE ur.user_id = 1
                        AND (ur.org_id = 1 OR ur.org_id = 0)
                UNION
                        SELECT br.role_id FROM builtin_role AS br
                        WHERE br.role IN ("Viewer")
                        AND (br.org_id = 1 OR br.org_id = 0)
                ) as all_role ON role.id = all_role.role_id)  AND action = "folders:read")
                        UNION ALL SELECT f.uid, f.parent_uid, f.org_id FROM folder f INNER JOIN RecQry1 r ON f.parent_uid = r.uid and f.org_id = r.org_id
                )SELECT
                        dashboard.id,
                        dashboard.uid,
                        dashboard.title,
                        dashboard.slug,
                        dashboard_tag.term,
                        dashboard.is_folder,
                        dashboard.folder_id,
                        folder.uid AS folder_uid,
                        folder.slug AS folder_slug,
                        folder.title AS folder_title  FROM ( SELECT dashboard.id FROM dashboard WHERE ((dashboard.uid IN (SELECT substr(scope, 16) FROM permission WHERE scope LIKE 'dashboards:uid:%' AND role_id IN(SELECT id FROM role INNER JOIN (
                        SELECT ur.role_id
                        FROM user_role AS ur
                        WHERE ur.user_id = 1
                        AND (ur.org_id = 1 OR ur.org_id = 0)
                UNION
                        SELECT br.role_id FROM builtin_role AS br
                        WHERE br.role IN ("Viewer")
                        AND (br.org_id = 1 OR br.org_id = 0)
                ) as all_role ON role.id = all_role.role_id)  AND action = "dashboards:read") AND NOT dashboard.is_folder) OR (dashboard.folder_id IN (SELECT d.id FROM dashboard as d WHERE d.uid IN (SELECT uid FROM RecQry0)) AND NOT dashboard.is_folder) OR (dashboard.uid IN (SELECT uid FROM RecQry1) AND dashboard.is_folder)) AND dashboard.org_id=1 ORDER BY dashboard.title ASC LIMIT 1000 OFFSET 0) AS ids
                INNER JOIN dashboard ON ids.id = dashboard.id
LEFT OUTER JOIN dashboard AS folder ON folder.id = dashboard.folder_id
                LEFT OUTER JOIN dashboard_tag ON dashboard.id = dashboard_tag.dashboard_id
 ORDER BY dashboard.title ASC
```

</p>
</details>

### PR DESCRIPTION
**Pull request by papagian**
**What is this feature?**
For nested folders we have to refer to the `folder` table for getting the parent folder details instead of the `dashboard` table
that knows only of flat folders. However, in the search query we used to join with the latter on `folder_id` column. As a result parent folder details were missing for a subfolder.

The sequential IDs for a folder differ in `folder` and `dashboard` table: but their `UID`s are the same.

This fix:
- Introduces a schema migration for adding a `folder_uid` column in `dashboard` table
- Introduces a data migration for setting `folder_uid` into the existing dashboard and folder rows in the `dashboard` table. (this can take **several minutes** for large setups > 1M dashboards)
- Stores `folder_uid` when saving a dashboard or folder
- Modifies the search query to refer to the folder table if the nested folders are enabled
- Adds tests for searching by folder and title with nested folders on/off

**Why do we need this feature?**

This is introduced for fixing search results for the nested folders feature but we need it in general because in the future we want to exclusively use the `folder` table for storing folders and without this migration this is not possible.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #74433

**Special notes for your reviewer:**
To reproduce the issue:
- enable nested folders in `main`
- create a folder hierarchy like:
Screenshot 2023-10-18 at 8 33 06 AM

- the folder details are missing from `api/search?query=New` response
- the folder details are missing from `api/search?query=child` response
- switch to this branch and try the above request: make sure that [the folder details are not missing](https://ephemeral1511182176504papagia.grafana-dev.net/api/search?query=child)

Try also moving a subfolder under another folder and to the root and make sure that search response is correct.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/services/folder/folderimpl/folder.go [hunk 1]
```diff
@@ -106,6 +109,38 @@ func (s *Service) DBMigration(db db.DB) {
...
+		}
+		folderRowsAffected, folderRowsAffectedErr := r.RowsAffected()
+		if folderRowsAffectedErr != nil {
+			s.log.Error("Failed to get folder rows affected", "error", folderRowsAffectedErr)
+		}
+
+		s.log.Debug("Migrating dashboard data", "dashboards rows", dashboardRowsAffected, "folder rows", folderRowsAffected)
+		return nil
+	}); err != nil {
+		s.log.Error("Failed to run folder_uid migration", "error", err)
```
Comment (papagian) [inline pkg/services/folder/folderimpl/folder.go:142]: if there is an error then we just log it for now (without failing): the migration should be registered as unsuccessful therefore it will be a new attempt running it on next startup.

**Review by zserge — DISMISSED** [review]

**Review by zserge — APPROVED** [review]
