### PR TITLE
Search: Fixes search limits and adds a page parameter

### LINKED ISSUE #16049: Grafana Search API
**What happened**:
I have around 7500 dashboards in an grafana org, but when I use the /search api to get the list of all dashboards, it is responding with only 3400 dashboards. I've also tried by increasing the LIMIT parameter to 50000, but still it doesn't work.

**What you expected to happen**:
It should have returned all the 7500 dashboards available

**How to reproduce it (as minimally and precisely as possible)**:
Create 7500+ dashboards in an org and try listing out dashboards using /search api

**Anything else we need to know?**:

**Environment**:
- Grafana version: v5.4.0
- Data source type & version:
- OS Grafana is installed on: Linux
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by torkelo**
This adds a page parameter to search api without adding
any major breaking change.

It does add an API validation error when trying to use a limit beyond 5000. This is a breaking change. We could remove this and have it only in the docs and describe that this is a limit that Grafana will apply silently. 

This is a bit quick and dirty so feedback is welcomed. But I feel we need to fix this asap so large users can have a way to list all dashboards in the API. But I do not want to just remove the limits and leave a potential future DOS attack vector open. 

The big limitation in this partial paging implementation is the lack of page count in the result but to add that we need to do a substantial breaking API change as the current api just returns items without a container object. Opened an issue for a bigger search api update  https://github.com/grafana/grafana/issues/16457

Fixes #16049

### CODE REVIEW

**Comment by aocenas** [comment]
> The big limitation in this partial paging implementation is the lack of page count in the result but to add that we need to do a substantial breaking API change as the current api just returns items without a container object.

We could also use some header for that. Or something similar to [Github API](https://developer.github.com/v3/#pagination) using Link header.

File: pkg/services/sqlstore/search_builder.go [hunk 1]
```diff
@@ -92,8 +94,17 @@ func (sb *SearchBuilder) ToSql() (string, []interface{}) {
...
 
-	sb.sql.WriteString(" ORDER BY dashboard.title ASC" + dialect.Limit(5000))
+	// Default to page 1
+	if sb.page < 1 {
+		sb.page = 1
+	}
+
+	// do not allow limits beyond 5000
+	if sb.limit > 5000 {
+		sb.limit = 5000
```
Comment (aocenas) [inline pkg/services/sqlstore/search_builder.go]: Do you think it would it make sense to have an error also returned here? Seems like this is kinda silent failure and could lead to issues if somebody does not notice it.

**Comment by marefr** [comment]
@torkelo can you fix the build errors?

File: pkg/api/search.go [hunk 2]
```diff
@@ -9,18 +9,23 @@ import (
...
+	page := c.QueryInt64("page")
 	dashboardType := c.Query("type")
 	permission := m.PERMISSION_VIEW
 
 	if limit == 0 {
 		limit = 1000
 	}
 
+	if limit > 5000 {
+		return Error(422, "Limit is above maxium allowed (5000), use page parameter to access hits beyond 5000", nil)
```
Comment (DanCech) [inline pkg/api/search.go]:
```suggestion
		return Error(422, "Limit is above maximum allowed (5000), use page parameter to access hits beyond 5000", nil)
```

File: pkg/services/sqlstore/search_builder.go (hunk 1 above)
Comment (torkelo) [reply pkg/services/sqlstore/search_builder.go]: I was thinking the same when I wrote this, but there is no error return for this function. There is an error for this condition in the api layer so maybe this check can be removed.

File: pkg/services/sqlstore/search_builder.go [hunk 3]
```diff
@@ -92,8 +94,17 @@ func (sb *SearchBuilder) ToSql() (string, []interface{}) {
...
+	}
 
+	sb.sql.WriteString(" ORDER BY dashboard.title ASC " + dialect.LimitOffset(sb.limit, (sb.page-1)*sb.limit))
```
Comment (marefr) [inline pkg/services/sqlstore/search_builder.go]: Think we should use `ORDER BY dashboard.title ASC, dashboard.id ASC` in case there are dashboards with the same title in the breakpoint between pages.

File: pkg/services/sqlstore/search_builder.go [hunk 4]
```diff
@@ -135,7 +146,7 @@ func (sb *SearchBuilder) buildTagQuery() {
 	// this ends the inner select (tag filtered part)
 	sb.sql.WriteString(`
 		GROUP BY dashboard.id HAVING COUNT(dashboard.id) >= ?
-		ORDER BY dashboard.id` + dialect.Limit(int64(sb.limit)) + `) as ids
+		ORDER BY dashboard.id as ids
```
Comment (marefr) [inline pkg/services/sqlstore/search_builder.go]: Hmm wonder why we had limit in the inner select statement before?

File: pkg/services/sqlstore/search_builder.go [hunk 5]
```diff
@@ -152,7 +163,7 @@ func (sb *SearchBuilder) buildMainQuery() {
 	sb.sql.WriteString(` WHERE `)
 	sb.buildSearchWhereClause()
 
-	sb.sql.WriteString(` ORDER BY dashboard.title` + dialect.Limit(int64(sb.limit)) + `) as ids INNER JOIN dashboard on ids.id = dashboard.id `)
+	sb.sql.WriteString(` ORDER BY dashboard.title) as ids INNER JOIN dashboard on ids.id = dashboard.id `)
```
Comment (marefr) [inline pkg/services/sqlstore/search_builder.go]: Should this be `ORDER BY dashboard.id` as in tagQuery?

File: pkg/services/sqlstore/dashboard_test.go [hunk 6]
```diff
@@ -259,6 +259,35 @@ func TestDashboardDataAccess(t *testing.T) {
...
+					Limit:        1,
+					Page:         2,
+					SignedInUser: &m.SignedInUser{OrgId: 1, OrgRole: m.ROLE_EDITOR},
+				}
+
+				err := SearchDashboards(&query)
+				So(err, ShouldBeNil)
+
+				So(len(query.Result), ShouldEqual, 1)
+				So(query.Result[0].Title, ShouldEqual, "1 test dash folder")
```
Comment (marefr) [inline pkg/services/sqlstore/dashboard_test.go]: Shouldn't this be a dashboard? Or is folder always included in search result if there are a dashboard? Think we need a few more tests in that case to cover the case when both folder and dashboard are expected to be returned.

**Review by marefr — CHANGES_REQUESTED** [review]
This looks good, but have a few comments.

File: pkg/services/sqlstore/search_builder.go (hunk 4 above)
Comment (torkelo) [reply pkg/services/sqlstore/search_builder.go]: yea, did not understand it either, and I wrote it

Comment (torkelo) [reply pkg/services/sqlstore/search_builder.go]: think for performance reasons

File: pkg/services/sqlstore/dashboard_test.go (hunk 6 above)
Comment (torkelo) [reply pkg/services/sqlstore/dashboard_test.go]: Search returns both folders & dashboards, no?

Comment (marefr) [reply pkg/services/sqlstore/dashboard_test.go]: Sorry for not being clear. 

The test "Should be able to limit search" are using page=1 and limit=1 and you verify that you get "1 test dash folder" in response. However in the test highlighted above "Should be able to search beyond limit using paging" you also verify that you get "1 test dash folder" in response where I think that should be something else since you're asking for page 2 with a limit of 1.

Comment (torkelo) [reply pkg/services/sqlstore/dashboard_test.go]: ok, that is strange. Investigated this revealed the limit is not working, should not be on the outer query but the inner. As the outer is joining with tags.

Comment (marefr) [reply pkg/services/sqlstore/dashboard_test.go]: Great :+1: Awaiting a fix then

**Comment by torkelo** [comment]
Ok, moved the limit to the inner query where it should be.

File: pkg/services/sqlstore/search_builder.go [hunk 7]
```diff
@@ -133,12 +148,7 @@ func (sb *SearchBuilder) buildTagQuery() {
 	sb.buildSearchWhereClause()
 
 	// this ends the inner select (tag filtered part)
-	sb.sql.WriteString(`
-		GROUP BY dashboard.id HAVING COUNT(dashboard.id) >= ?
-		ORDER BY dashboard.id` + dialect.Limit(int64(sb.limit)) + `) as ids
-		INNER JOIN dashboard on ids.id = dashboard.id
-	`)
-
+	sb.sql.WriteString(`GROUP BY dashboard.id HAVING COUNT(dashboard.id) >= ? `)
```
Comment (marefr) [inline pkg/services/sqlstore/search_builder.go]: Maybe I'm just tired but can't for my life understand why the `GROUP BY dashboard.id HAVING COUNT(dashboard.id) >= ?` is needed? Maybe the comment can be updated to explain this?

**Review by marefr — CHANGES_REQUESTED** [review]
Good catch with the outer vs inner limit! Still have a few questions/comments.

File: pkg/services/sqlstore/search_builder.go [hunk 8]
```diff
@@ -88,15 +90,28 @@ func (sb *SearchBuilder) ToSql() (string, []interface{}) {
...
+	sb.sql.WriteString(`
+		ORDER BY dashboard.id ` + sb.getLimitExpression() + `) as ids
+		INNER JOIN dashboard on ids.id = dashboard.id
+	`)
+
 	sb.sql.WriteString(`
 		LEFT OUTER JOIN dashboard folder on folder.id = dashboard.folder_id
 		LEFT OUTER JOIN dashboard_tag on dashboard.id = dashboard_tag.dashboard_id`)
 
-	sb.sql.WriteString(" ORDER BY dashboard.title ASC" + dialect.Limit(5000))
```
[the remark this answers is not in the document]
Comment (torkelo) [reply pkg/services/sqlstore/search_builder.go]: yes, this is a small breaking change, calls with a limit > 5000 will now return an error when before they did not as this limit was kind of silent. 

It's actually a bit complicated now that I think about it. The limit the user could specify had no upper bound, but we had this outer hardcoded limit (5000) on the outer query that is actually on the wrong query. The outer query does a outer join with tags, so depending on how many tags the dashboards have this 5000 limit will act very differently. Technically if you have 10 tags on each dashboard it would limit to only 500 dashboards. That is why this limit is now removed.

File: pkg/services/sqlstore/search_builder.go (hunk 7 above)
Comment (torkelo) [reply pkg/services/sqlstore/search_builder.go]: This is the crucial part of this part of the query, this part of the query does filtering based on tags. 

So we join on the tags (created a cartesian product), then filter based on the tags. then we want to filter all all dashboards that have same number of rows as there are tag filters. This is apperently one of the better ways to do filtering on tags in SQL (a many-to-many relationship) .

File: pkg/services/sqlstore/search_builder.go [hunk 9]
```diff
@@ -88,15 +90,28 @@ func (sb *SearchBuilder) ToSql() (string, []interface{}) {
...
-
+	sb.sql.WriteString(" ORDER BY dashboard.title ASC")
 	return sb.sql.String(), sb.params
 }
 
+func (sb *SearchBuilder) getLimitExpression() string {
+	// Default to page 1
+	if sb.page < 1 {
```
[the remark this answers is not in the document]
Comment (torkelo) [reply pkg/services/sqlstore/search_builder.go]: fixed

File: pkg/services/sqlstore/search_builder.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (torkelo) [reply pkg/services/sqlstore/search_builder.go]: yea, this was the strange outer limit that should not be here as it depends on number of tags

File: pkg/services/sqlstore/search_builder.go (hunk 7 above)
Comment (marefr) [reply pkg/services/sqlstore/search_builder.go]: Gotcha :+1:

**Review by marefr — APPROVED** [review]
Looks good :+1:
