### PR TITLE
Geomap: Fix tooltip display option

### LINKED ISSUE #55125: Geomap: Tool tip toggle not working in 9.1.5

### PR DESCRIPTION
**Pull request by drew08t**
What this PR does / why we need it:
When collapsing or expanding panel editor category menus, tooltip control becomes disabled. This is caused by cleanup routine in navigation (https://github.com/grafana/grafana/blob/main/public/app/core/navigation/GrafanaRoute.tsx#L78-L86) removing elements of id 'tooltip'.

Before:
Sep-28-2022 08-59-16

After:
Sep-28-2022 13-01-24

Fixes #55125

### CODE REVIEW

File: public/app/core/components/OptionsUI/registry.tsx [hunk 1]
```diff
@@ -81,7 +81,8 @@ export const getAllOptionEditors = () => {
     name: 'Boolean',
     description: 'Allows boolean values input',
     editor(props) {
-      return <Switch {...props} onChange={(e) => props.onChange(e.currentTarget.checked)} />;
+      const { id, ...rest } = props; // Remove id from properties passed into switch
```
Comment (nmarrs) [inline public/app/core/components/OptionsUI/registry.tsx:84]: Not sure on this approach given whether or not we are sure that the `id` prop is not necessary / being used (both now / in future) for testing purposes etc. for the switches in the editor

**Review by nmarrs — COMMENTED** [review]
Confirmed this works for me locally! Not entirely sure on this approach either given impacts all switches in editor and not just geomap specifically 🤷🏻‍♂️ but maybe it's fine to leave out `id` prop

File: public/app/core/components/OptionsUI/registry.tsx (hunk 1 above)
Comment (drew08t) [reply public/app/core/components/OptionsUI/registry.tsx:84]: Yeah, feel the same way. Another possible approach would be to update this code to exclude tagName of "INPUT":
https://github.com/grafana/grafana/blob/main/public/app/core/navigation/GrafanaRoute.tsx#L78-L86

Comment (nmarrs) [reply public/app/core/components/OptionsUI/registry.tsx:84]: Talked to Ryan a bit about it, given in testing we shouldn't rely on `id` anyways (and use `aria-label` or data-testid if necessary) this change is probably ok

**Review by nmarrs — APPROVED** [review]
