### PR TITLE
Dashboard Scene: Fix unnecessary diffing

### LINKED ISSUE #100104: Navigating away after saving a new dashboard warns about pending changes
With the following settings, after saving a new  dashboard the prompt about unsaved changes is triggered. The change detection indicates changes in such a dashboard - notice that the Save button turns blue right after successful save.

```
app_mode = development

[feature_toggles]
provisioning = true
kubernetesFoldersServiceV2 = true
kubernetesDashboards = true
grafanaAPIServerWithExperimentalAPIs = true
unifiedStorageSearch = true
unifiedStorageSearchUI = true
kubernetesCliDashboards = true
dashboardRestore = true ; SOFT delete in SQL api

# If you want easy kubectl setup development mode
grafanaAPIServerEnsureKubectlAccess = true

[unified_storage.dashboards.dashboard.grafana.app]
dualWriterMode = 2

[unified_storage.folders.folder.grafana.app]
dualWriterMode = 2
```
Image

### PR DESCRIPTION
**Pull request by harisrozajac**
During the last bug bash for k8s dashboards, we found that after saving a new dashboard user gets notified that there are additional changes, which is confusing for the users. This PR fixes those issues:
-  **legacy API and k8s v0**: dashboard `description` is being removed from the JSON, which produces a positive diff
- **k8s v0:**  `id: null` was sent in the request when creating a dashboard, and this property is then removed from JSON when `transformSceneToSaveModel` runs, which produces a positive diff. k8s dashboards don't use id property so it will always be null if sent when initially saving a new dashboard. I've left a [comment](url) in the part that implements the fix for some additional findings and my confusion at why this property even appears in the save request 

For more details about this bug check the issue below:
Fixes #100104

For reviewers, please test with:

- [ ] Legacy API 
- [ ] k8s API - this is the config you'll need to run it with k8s API:

```
app_mode = development

[feature_toggles]
provisioning = true
kubernetesFoldersServiceV2 = true
kubernetesDashboards = true
grafanaAPIServerWithExperimentalAPIs = true
unifiedStorageSearch = true
unifiedStorageSearchUI = true
kubernetesCliDashboards = true
dashboardRestore = true ; SOFT delete in SQL api

# If you want easy kubectl setup development mode
grafanaAPIServerEnsureKubectlAccess = true

[unified_storage.dashboards.dashboard.grafana.app]
dualWriterMode = 2

[unified_storage.folders.folder.grafana.app]
dualWriterMode = 2
```

### CODE REVIEW

File: public/app/features/dashboard-scene/serialization/transformSceneToSaveModel.ts [hunk 1]
```diff
@@ -114,7 +114,7 @@ export function transformSceneToSaveModel(scene: DashboardScene, isSnapshot = fa
   const dashboard: Dashboard = {
     ...defaultDashboard,
     title: state.title,
-    description: state.description || undefined,
+    description: state.description ?? undefined,
```
Comment (harisrozajac) [inline public/app/features/dashboard-scene/serialization/transformSceneToSaveModel.ts:117]: This fixes the diffing but still persists the description if it's an empty string. If we don't want to persist it if it's an empty string we could remove it in legacy and v0 API calls when saving. I can't think of any other way of not persisting these as empty string while not triggering diffing for all the current dashboards

File: public/app/features/dashboard/api/v0.ts [hunk 2]
```diff
@@ -32,6 +32,8 @@ export class K8sDashboardAPI implements DashboardAPI<DashboardDTO, Dashboard> {
 
   saveDashboard(options: SaveDashboardCommand<Dashboard>): Promise<SaveDashboardResponseDTO> {
     const dashboard = options.dashboard as DashboardDataDTO; // type for the uid property
+    // k8s apis server doesn't use dashboard.id
+    delete dashboard.id;
```
Comment (harisrozajac) [inline public/app/features/dashboard/api/v0.ts:36]: I have no idea why here we are getting `id: null`, Looking in here https://github.com/grafana/grafana/blob/8f3fd8f91d7dd286def6f1711c89ad84bcc6b8a6/public/app/features/dashboard-scene/saving/useSaveDashboard.ts#L32 we are getting a saveModel which is clean of any props with null values, and we then pass that saveModel to `saveDashboardRtkQuery` and as soon as we pass it logging the `cmd.dashboard` shows a dashboard object with `id: null` 😵 I thought it's maybe because Dashboard type for this command had id defined like this: https://github.com/grafana/grafana/blob/eb2f8182c0b102bd24c07ea471ef7520e75190cc/packages/grafana-schema/src/raw/dashboard/x/dashboard_types.gen.ts#L1069
but this doesn't seem to be case because when I remove null from type definition I still get null when sending the request

So for now deleting the id field here seems like the most straightforward solution

File: public/app/features/dashboard-scene/serialization/transformSceneToSaveModel.ts (hunk 1 above)
Comment (axelavargas) [reply public/app/features/dashboard-scene/serialization/transformSceneToSaveModel.ts:117]: I think we could remove the default value  in the `DashboardSceneSerializer`

https://github.com/grafana/grafana/blob/main/public/app/features/dashboard-scene/serialization/DashboardSceneSerializer.ts#L67

instead of:

`     description: options.description || '',
`

something like:
`      description: options.description || undefined,
`

File: public/app/features/dashboard/api/v0.ts (hunk 2 above)
Comment (axelavargas) [reply public/app/features/dashboard/api/v0.ts:36]: I am not sure about this change. What was the positive diff that was causing? I tested locally and removing this change did not affect my dashboard. Is there something that I am missing? 😅

**Review by axelavargas — COMMENTED** [review]
Nice work, Haris, left some comments and suggestion 😄

File: public/app/features/dashboard/api/v0.ts (hunk 2 above)
Comment (harisrozajac) [reply public/app/features/dashboard/api/v0.ts:36]: @axelavargas this is when I have `kubernetesDashboards` enabled. The `id: null` is saved to db on initial save, so everytime I load a dashboard JSON differ is showing that this `id: null` is being removed

**Review by axelavargas — APPROVED** [review]
I am approving this PR, after our conversation about the dashboard.id, I think we have a different way to fix it 😄

File: public/app/features/apiserver/types.ts [hunk 3]
```diff
@@ -90,7 +90,7 @@ type GrafanaClientAnnotations = {
 
 // Labels
 type GrafanaLabels = {
-  [DeprecatedInternalId]?: number;
+  [DeprecatedInternalId]?: string;
```
Comment (harisrozajac) [inline public/app/features/apiserver/types.ts:93]: I updated this because we get a string from the backend https://github.com/grafana/grafana/blob/a037c6f34472ec8e16ab1020121a1be30b0e4186/pkg/apimachinery/utils/meta.go#L321
