### PR TITLE
CloudWatch Logs: Disable query path using websockets (Live) feature

### LINKED ISSUE #39196: Cloudwatch Logs: queries don't return when Grafana is in HA mode
**What happened**:
When using the Cloudwatch plugin in Grafana 8.1.2 in HA mode, queries of any kind start hanging after the first query returns correctly. The hanging Cloudwatch queries never time out and there are no errors in the logs.

**What you expected to happen**:
I expect all the Cloudwatch queries to complete in a time frame consistent with the query size.

**How to reproduce it (as minimally and precisely as possible)**:
To reproduce, go to the dev se-demo kit (internal to Grafana Labs)
go to the explore tab
choose AWS-Cloudwatch as the data source
For Query Mode, choose "cloudwatch logs"
for region, choose us-east-2, and for log group - choose promtail-lambda-forwarder
for the query, enter stats count(*)
hit run.

OR

Run Grafana in K8s with 3x replicas (HA mode)
Create a Cloudwatch datasource
Go to Explore mode
Select the Cloudwatch datasource
For Query Mode, choose "cloudwatch logs"
Choose any log group that has logs in it
for the query, enter stats count(*)
hit run
keep hitting run. After the first query it won't work anymore

**Anything else we need to know?**:
Based on an internal Slack thread I think this is a bug with Grafana Live. If you set 
[live]
max_connections = 0

Then the problem goes away.

**Environment**:
- Grafana version: 8.1.2 Enterprise
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Official Grafana docker image
- User OS & Browser: Ubuntu, Firefox
- Grafana plugins: Cloudwatch
- Others: 3x Grafana Pods

### PR DESCRIPTION
**Pull request by aocenas**
Fixes: https://github.com/grafana/grafana/issues/39196

Cloud Watch is using websocket communication with the front end to deliver results from a logs query. This is because logs query is started with one API request and then we have to poll the results with API, which can deliver partial results as the query is scanning logs.

The websocket solution has few problems. First it does not scale in HA setup because it needs to keep track of mapping the running queries to open channels. This state is not shared between Grafana instances so clients can start the query on one instance but then try to subscribe to websocket channel on different one.

Other problem is there seems to be deadlock or slowdown situation for some users. With server handling the state for all the clients there is some synchronisation going on and there is also an internal queue that prevents running more queries than AWS internal limits.

Also from the websocket path we do not propagate errors properly so for some errors clients were kept in loading state indefinitely.

We still have the old path which don't seem to have that much disadvantages. Instead of polling from the server and pushing the data through websocket it polls the results from client (still via backend data source implementation). This is simpler and does not need any shared state on the server while still showing partial results to the user as soon as possible.

Some TODOs to follow this up:
- [ ] Implement retries on concurent query limits
In case of getting throttled on query creation we should retry few times with some reasonable backoff. In websocket path this mitigated a bit with the internal queue but as that wasn't shared we could still get throttled so retrying makes more sense anyway. With this PR this may temporarily be a problem but at least we get proper error message for it now.

- [ ] Clean up the websocket path from the code

### CODE REVIEW

File: public/app/plugins/datasource/cloudwatch/datasource.ts [hunk 1]
```diff
@@ -161,116 +151,17 @@ export class CloudWatchDatasource extends DataSourceWithBackend<CloudWatchQuery,
...
-
-  /**
-   * Handle log query using grafana live feature. This means the backend will return a websocket channel name and it
-   * will listen on it for partial responses until it's terminated. This should give quicker partial data to the user
-   * as the log query can be long running. This requires that config.liveEnabled === true as that controls whether
-   * websocket connections can be made.
-   * @param logQueries
-   * @param options
-   */
-  private handleLiveLogQueries = (
```
Comment (aocenas) [inline public/app/plugins/datasource/cloudwatch/datasource.ts:196]: removed

File: public/app/plugins/datasource/cloudwatch/datasource.ts [hunk 2]
```diff
@@ -161,116 +151,17 @@ export class CloudWatchDatasource extends DataSourceWithBackend<CloudWatchQuery,
       return of({ data: [], state: LoadingState.Done });
     }
 
-    const response = config.liveEnabled
```
Comment (aocenas) [inline public/app/plugins/datasource/cloudwatch/datasource.ts:164]: refactored as having handleLegacyLogQueries did not make sense anymore

**Review by FZambia — APPROVED** [review]
Checked out this branch and can confirm that in Explore mode and HA setup query not hanging anymore.

**Comment by bergquist** [comment]
Would it be possible to backport this to 8.1.x?
