### PR TITLE
LibraryPanelSearch: Refactor and fix hyphen issue 

### LINKED ISSUE #55312: LibraryPanelsSearch: Searching Library Panels with hyphens does not return results
**What happened**:
Searching for a library panel containing a hyphen does not return results, whether or not there are actually any panels containing hyphens.

**What you expected to happen**:
I would expect the results to include any library panels matching the search query.

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Adds a new prop to `FilterInput` to disable regex escaping/unescaping for cases where it isn't needed, fixing an issue where search queries including special characters wouldn't return library panels that include those same characters.

**Which issue(s) this PR fixes**:
Closes #55312

**Special notes for your reviewer**:
Hopefully some of the refactoring I did on `LibraryPanelsSearch` is uncontroversial. I changed how state was handled from using `useReducer` to managing the state inline as I didn't really feel like there was an advantage compared to just using `useState`, but I'm more than happy to undo that change if someone can make a good argument for it.

I did a bit more work than is seen here in this PR refactoring some of the related components, but I'll probably make a separate PR with those changes to avoid overloading this one.

### CODE REVIEW

File: public/app/core/components/FolderFilter/FolderFilter.tsx [hunk 1]
```diff
@@ -57,28 +44,35 @@ export function FolderFilter({ onChange: propsOnChange, maxMenuHeight }: FolderF
...
     query: searchString,
-    type: 'dash-folder',
+    type: DashboardSearchItemType.DashFolder,
     permission: PermissionLevelString.View,
   };
 
   // FIXME: stop using id from search and use UID instead
-  // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
-  const searchHits = (await getBackendSrv().search(params)) as DashboardSearchHit[];
+  const searchHits: DashboardSearchHit[] = await getBackendSrv().search(params);
```
Comment (ivanortegaalba) [inline public/app/core/components/FolderFilter/FolderFilter.tsx:75]: Thanks! 😄

File: public/app/features/library-panels/components/LibraryPanelsSearch/LibraryPanelsSearch.tsx [hunk 2]
```diff
@@ -133,34 +98,118 @@ export const LibraryPanelsSearch = ({
...
+      [onPanelFilterChange]
+    );
+    const folderFilterChanged = useCallback(
+      (folders: FolderInfo[]) => onFolderFilterChange(folders.map((f) => String(f.id))),
+      [onFolderFilterChange]
+    );
+
+    return (
+      <div className={styles.container}>
+        {showSort && <SortPicker value={sortDirection} onChange={onSortChange} filter={['alpha-asc', 'alpha-desc']} />}
```
Comment (ivanortegaalba) [inline public/app/features/library-panels/components/LibraryPanelsSearch/LibraryPanelsSearch.tsx:164]: Should we extract the filter strings to an enum here? WDYT?

**Review by ivanortegaalba — COMMENTED** [review]
Thank you so much for the refactor @kaydelaney, it looks great!

While reproducing the issue, I cannot do it I cannot reproduce it in play. Am I doing something wrong? I tried also adding a panel and I got the same result.

File: public/app/features/library-panels/components/LibraryPanelsSearch/LibraryPanelsSearch.tsx [hunk 3]
```diff
@@ -133,34 +98,118 @@ export const LibraryPanelsSearch = ({
...
+          <div className={styles.filterContainer}>
+            {showFolderFilter && <FolderFilter onChange={folderFilterChanged} />}
+            {showPanelFilter && <PanelTypeFilter onChange={panelFilterChanged} />}
+          </div>
+        )}
+      </div>
+    );
+  }
+);
+SearchControls.displayName = 'SearchRow';
```
[the remark this answers is not in the document]
Comment (kaydelaney) [reply public/app/features/library-panels/components/LibraryPanelsSearch/LibraryPanelsSearch.tsx:175]: Nope, just something I forgot to update :P. Will change

**Comment by polibb** [comment]
> Thank you so much for the refactor @kaydelaney, it looks great!
> 
> While reproducing the issue, I cannot do it I cannot reproduce it in play. Am I doing something wrong? I tried also adding a panel and I got the same result.
> 

@ivanortegaalba Me neither, but I do reproduce it locally and it is fixed on this PR. I also don't know why it's okay in Play 👾.

File: public/app/features/library-panels/components/LibraryPanelsSearch/LibraryPanelsSearch.tsx (hunk 2 above)
Comment (polibb) [reply public/app/features/library-panels/components/LibraryPanelsSearch/LibraryPanelsSearch.tsx:164]: It is indeed not otherwise obvious that those two are part of [the options `SortPicker` has](https://github.com/grafana/grafana/blob/8af587e7bae589820da0a7e459ace1274af3619c/public/app/core/components/Select/SortPicker.tsx#L28) after receiving its response from the api `/api/search/sorting`.

File: packages/grafana-ui/src/components/FilterInput/FilterInput.tsx [hunk 4]
```diff
@@ -9,10 +9,11 @@ export interface Props extends Omit<HTMLProps<HTMLInputElement>, 'onChange'> {
   value: string | undefined;
   width?: number;
   onChange: (value: string) => void;
+  escapeRegex?: boolean;
 }
 
 export const FilterInput = React.forwardRef<HTMLInputElement, Props>(
-  ({ value, width, onChange, ...restProps }, ref) => {
+  ({ value, width, onChange, escapeRegex = true, ...restProps }, ref) => {
```
Comment (polibb) [inline packages/grafana-ui/src/components/FilterInput/FilterInput.tsx:16]: Because `FilterInput` is in `grafana-ui` should we make the naming of the prop more clear about its purpose in general, like `escapeSpecialChars`? 
`escapeRegex` makes me wonder which regex, what is the regex if not the one inside `FilterInput` and what does escaping it mean if it is?

**Review by polibb — APPROVED** [review]
Very neat refactoring 🙏

**Review by ivanortegaalba — APPROVED** [review]
Tested locally, and it works perfectly fine! I can now use special characters as part of the search. The original issue was only in main but not in play, for the records ;P 

Thanks, @kaydelaney for the cool refactor!
