### PR TITLE
Alerting: Fix provisioned templates being ignored by alertmanager

### LINKED ISSUE #69486: Alerting: Provisioned Notification templates no longer work in Grafana 10
**What**

Provisioned Notification templates no longer work in Grafana 10 because Grafana 10 reads a field called `templates` from the configuration that is not updated when using the Provisioning API. Managing notification templates via the UI is unaffected.

**How**

Grafana uses `template_files` and `templates` to define and register notification templates in Grafana. However, in versions of Grafana 9.5 and earlier, `templates` was not used when loading templates into the Grafana Alertmanager.

```
{
  "template_files": {
    "test": "{{ define \"test\" }}\n  test\n{{ end }}"
  },
  "templates": ["test"],
}
```

This was changed in Grafana 10 when adding support for template testing, and since Grafana 10 it reads both `template_files` and `templates`.

However, it turns out that when provisioning notification templates using the Provisioning API, the Provisioning API would set `template_files` but not `templates`. This is different from the UI which sets both, but was not an issue in Grafana 9.5 and earlier because as mentioned, in versions of Grafana 9.5 and earlier, `templates` was not used when loading templates into the Grafana Alertmanager.

### PR DESCRIPTION
**Pull request by JacobsonMT**
Template provisioning sets the template in cfg.TemplateFiles while a recent change made it so that alertmanager reads cfg.AlertmanagerConfig.Templates instead.

This change fixes the issue on both ends, by having provisioning set boths fields and reverts the change on the alertmanager side so that it uses cfg.TemplateFiles.

Fixes: https://github.com/grafana/grafana/issues/69486

### CODE REVIEW

File: pkg/services/ngalert/provisioning/templates.go [hunk 1]
```diff
@@ -53,6 +53,7 @@ func (t *TemplateService) SetTemplate(ctx context.Context, orgID int64, tmpl def
 		revision.cfg.TemplateFiles = map[string]string{}
 	}
 	revision.cfg.TemplateFiles[tmpl.Name] = tmpl.Template
+	revision.cfg.AlertmanagerConfig.Templates = append(revision.cfg.AlertmanagerConfig.Templates, tmpl.Name)
```
Comment (grobinson-grafana) [inline pkg/services/ngalert/provisioning/templates.go:56]: This will also append each time a provisioned template is updated:

```
curl -H "Content-Type: application/json" -u admin:admin http://127.0.0.1:3000/api/v1/provisioning/templates/test -X PUT -d '{"name":"test","template":"hello1"}'
curl -H "Content-Type: application/json" -u admin:admin http://127.0.0.1:3000/api/v1/provisioning/templates/test -X PUT -d '{"name":"test","template":"hello2"}'
```
```
"templates": [
  "test",
  "test"
],
```

Comment (JacobsonMT) [reply pkg/services/ngalert/provisioning/templates.go:56]: I guess we might as well overwrite `cfg.AlertmanagerConfig.Templates` here with the current state of `TemplateFiles` since we'll do it during `applyConfig` anyways, WDYT?

Comment (grobinson-grafana) [reply pkg/services/ngalert/provisioning/templates.go:56]: Yes I think so! I've noticed that sometimes deleted templates are removed from `template_files` and not `templates`, so it should fix both!

Comment (grobinson-grafana) [reply pkg/services/ngalert/provisioning/templates.go:56]: What's the relationship between this and `cfg.AlertmanagerConfig.Templates = paths` on Line 269 of `pkg/services/ngalert/notifier/alertmanager.go`.

Comment (JacobsonMT) [reply pkg/services/ngalert/provisioning/templates.go]: This change is not technically required since we now do the same thing in `pkg/services/ngalert/notifier/alertmanager.go`, figured we might preempt future issues by just making this do both anyways. I can remove it if that's the preference.

**Review by alexweav — APPROVED** [review]
LGTM

**Review by grobinson-grafana — APPROVED** [review]
I tested this in:

- Grafana 9.5.2 ✅ 
- This branch with broken AM configuration (provisioned template missing from `templates`) ✅ 
- This branch with fixed AM configuration (provisioned template now present in `templates`) ✅
