### PR TITLE
RBAC: Fix delete team permissions on team delete

### LINKED ISSUE #74900: Teams: Cannot add team to dashboard/folder permission after deleting and recreating it with the same ID
### What happened?

It appears that the team's re-addition with the same ID after deletion is not successfully granted as a permission to dashboards/folders, despite receiving a success message.

### What did you expect to happen?

A team that once got deleted from Grafana and recreated with the same team id can be assigned as a permission to dashboards/folders.

### Did this work before?

No

### How do we reproduce it?

1. create/sync a team
2. add team as permission in dashboard/folder
3. delete team
4. re-add team with same id
5. add team to any dashboard
6. success message will appear but team will not get added

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 9.5.4 / 10.2.0
OS: Windows/Linux
Browser: N/A

### Grafana platform?

Other

### Datasource(s)?

N/A

### PR DESCRIPTION
**Pull request by gamab**
**What is this feature?**

On team deletion, we need to delete the associated RBAC assignments, role and permissions.

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/74900

**Special notes for your reviewer:**

### CODE REVIEW

File: pkg/services/accesscontrol/database/database.go [hunk 1]
```diff
@@ -241,3 +241,58 @@ func (s *AccessControlStore) DeleteUserPermissions(ctx context.Context, orgID, u
 	})
 	return err
 }
+
+func (s *AccessControlStore) DeleteTeamPermissions(ctx context.Context, orgID, teamID int64) error {
```
Comment (gamab) [inline pkg/services/accesscontrol/database/database.go:245]: Note that the orgID is not really mandatory, but it provides some consistency with `DeleteUserPermissions`

**Review by Jguer — APPROVED** [review]
