### PR TITLE
Loki: Fix a bug where adding adhoc filters was not possible

### LINKED ISSUE #54448: Loki: Ad-Hoc filters are added to the wrong place in query
**What happened**:
Since the update of @lezer-common in https://github.com/grafana/grafana/pull/50866 the LogQL parser will result in wrong positions for empty stream selectors. Even though this was noticed in https://github.com/grafana/grafana/pull/50866, we oversaw implications of that. One implication is that ad-hoc filters are added at the wrong place in the query.
I.e.: [https://play.grafana.org/d/-lPcmrp7z/loki-nginx-service-mesh-pattern-version?orgId=1&[…]var-adhoc=filename%7C%3D%7C%2Fvar%2Flog%2Fnginx%2Faccess.log](https://play.grafana.org/d/-lPcmrp7z/loki-nginx-service-mesh-pattern-version?orgId=1&var-datasource=Loki&var-adhoc=filename%7C%3D%7C%2Fvar%2Flog%2Fnginx%2Faccess.log)

This will result in the query `sum by(host) (count_over_time({$__interval]\"\", filename=\"/var/log/nginx/access.log\"}))`.

**What you expected to happen**:

Expected the query: `sum by(host) (count_over_time({filename=\"/var/log/nginx/access.log\"}[$__interval]))`

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup a dashboard with Loki as DS
2. Setup an adhoc variable.
3. Observe queries being built wrong.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.x since https://github.com/grafana/grafana/pull/50866

### PR DESCRIPTION
**Pull request by svennergr**
**What this PR does / why we need it**:
Adding adhoc filters to metric queries with empty selectors and variables (like `$__interval`) was erroring. This fix replaces the variables before adding the adhoc filters.

**Which issue(s) this PR fixes**:

Fixes #54448

**Special notes for your reviewer**:
If you want to test ad-hoc filters:
1. Setup a dashboard.
2. Setup a dashboard-adhoc-variable from Loki.
3. Setup a panel with this query: `sum by(host) (count_over_time({}[$__interval]))`
4. Open the dashboard with the adhoc variable set. Something like this in the URL: `var-VARNAME=place%7C%3D%7Cmoon`
5. Before the fix: look at the Network tab in devtools and see that the query is in a wrong format.
6. With the fix: the query is formatted correctly.

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/querybuilder/shared/parsingUtils.ts [hunk 1]
```diff
@@ -65,7 +65,7 @@ const varTypeFunc = [
  * Get back the text with variables in their original format.
  * @param expr
  */
-function returnVariables(expr: string) {
+export function returnVariables(expr: string) {
```
Comment (obetomuniz) [inline public/app/plugins/datasource/prometheus/querybuilder/shared/parsingUtils.ts:68]: Out of curiosity, does it makes sense to stay with this utility function here? We can have a top-level shared folder with such things and reuse them as needed in low-level system pieces. Or even ignore DRY, replicate the code on each Query Builder, and let it grow independently of the query builder. Why do we share parts of these Loki/Prom query builders, like in this case? 

Sorry for the loads of questions 😄 Just looking to understand this solution design decision between Loki/Prom Query Builders :)

**Review by obetomuniz — APPROVED** [review]
LGTM. I just left questions about the current codebase design.

**Review by matyax — APPROVED** [review]
Looks good.

File: public/app/plugins/datasource/prometheus/querybuilder/shared/parsingUtils.ts (hunk 1 above)
Comment (svennergr) [reply public/app/plugins/datasource/prometheus/querybuilder/shared/parsingUtils.ts:68]: I don't have deep insights in the architectural decisions, but I would assume it's hard to pick a spot outside of both `datasources` directories where such code would live. I see your point, that Loki and Prometheus datasources are now coupled quite strongly together, but on the other hand they both are core datasources and deselecting some of those when building Grafana is also not possible.

I don't know if @ivanahuckova and @aocenas might have better answers to those questions ;)

Comment (ivanahuckova) [reply public/app/plugins/datasource/prometheus/querybuilder/shared/parsingUtils.ts:68]: @obetomuniz great question! For now, this is actually a place for shared code between `loki` and `prometheus` query builder. Everything in `shared` could be in the future moved somewhere else. The idea is, that in the future, when we add new query builders (e.g. for `flux`) we would figure out where to move all shared logic (either `grafana/ui`, `grafana/data`, new package - `grafana/builder`). But for now, we use prometheus `shared` sub-folder for this.
