### PR TITLE
Alerting: Fix incorrect timing meta information for policy

### LINKED ISSUE #73573: Nested notification policies display wrong wait information’s when using Override general timings
### What happened?

I tried to create various nested notification policies with Override general timings and the displayed values are wrong in the main windows

### What did you expect to happen?

Correct values in the main windows

### Did this work before?

No

### How do we reproduce it?

1. Notification policies > Create a new nested policy with Override general timings `Group wait` = 1m, `Group interval` = 2m, `Repeat interval` = 3m
2. Notification policies > Create a second nested policy under the first one with Override general timings `Group wait` = 10m, `Group interval` = 20m, `Repeat interval` = 30m
3. Notification policies > Create a second nested policy under the first one with Override general timings, `Repeat interval` = 999m

The result if the following:
image

Issues:
On all the policy the `Repeat interval` is missing from the description
On the third one even though only the `Repeat interval` have been overridden it display incorrect values for `Group wait` and `Group interval`

The good news is that even if the displayed values are wrong, the configuration files is ok, so the it’s working correctly

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: v10.2.0
OS: Grafana Cloud
Browser: Edge / Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by gillesdemey**
**What is this feature?**

This PR does two things

1. Moves the `computeInheritedTree` function to utils and adds a few tests
2. Updates the `Policy` component to no longer show the default timing options if we're also inheriting from the parent.

**Which issue(s) does this PR fix?**:

Fixes #73573

The inheritance algorithm was working as intended, but the component showed both the default timing options and inherited properties, which it shouldn't (with the exception of the default policy, which cannot inherit from a parent).

**Special notes for your reviewer:**

I didn't write a regression test for this in `Policy.test.tsx` but might be a good addition to this PR :)

### CODE REVIEW

File: public/app/features/alerting/unified/components/notification-policies/Filters.tsx [hunk 1]
```diff
@@ -129,23 +128,6 @@ export function findRoutesMatchingPredicate(routeTree: RouteWithID, predicateFn:
   return matches;
 }
 
-/**
- * This function will compute the full tree with inherited properties – this is mostly used for search and filtering
- */
-export function computeInheritedTree<T extends Route>(parent: T): T {
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/notification-policies/Filters.tsx:135]: This is just moved to `utils/notification-policies.ts`

File: public/app/features/alerting/unified/components/notification-policies/Policy.tsx [hunk 2]
```diff
@@ -279,8 +279,11 @@ const Policy: FC<PolicyComponentProps> = ({
                     <MuteTimings timings={muteTimings} alertManagerSourceName={alertManagerSourceName} />
                   </MetaText>
                 )}
-                {timingOptions && Object.values(timingOptions).some(Boolean) && (
-                  <TimingOptionsMeta timingOptions={timingOptions} />
+                {timingOptions && (
+                  // for the default policy we will also merge the default timings, that way a user can observe what the timing options would be
+                  <TimingOptionsMeta
+                    timingOptions={isDefaultPolicy ? { ...timingOptions, ...TIMING_OPTIONS_DEFAULTS } : timingOptions}
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/notification-policies/Policy.tsx:285]: I'm creating a new object inline here because I wanted to avoid `timingOptions` with applied defaults being accidentally passed in to a component that might make mutations to the policy. 

That's not happening in this file but I also want to prevent future regressions of this sort.

File: public/app/features/alerting/unified/components/notification-policies/Policy.tsx [hunk 3]
```diff
@@ -441,28 +444,38 @@ const MuteTimings: FC<{ timings: string[]; alertManagerSourceName: string }> = (
...
 
 const TimingOptionsMeta: FC<{ timingOptions: TimingOptions }> = ({ timingOptions }) => {
-  const groupWait = timingOptions.group_wait ?? TIMING_OPTIONS_DEFAULTS.group_wait;
-  const groupInterval = timingOptions.group_interval ?? TIMING_OPTIONS_DEFAULTS.group_interval;
+  const groupWait = timingOptions.group_wait;
+  const groupInterval = timingOptions.group_interval;
+
+  // we don't have any timing options to show – we're inheriting everything from the parent
+  // and those show up in a separate "inherited properties" component
+  if (!groupWait && !groupInterval) {
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/notification-policies/Policy.tsx:452]: Move this logic inside the timing options meta component so we don't have to put the onus on the caller to conditionally render.

File: public/app/features/alerting/unified/components/notification-policies/Policy.tsx [hunk 4]
```diff
@@ -441,28 +444,38 @@ const MuteTimings: FC<{ timings: string[]; alertManagerSourceName: string }> = (
...
-      </Tooltip>
-      <Tooltip
-        placement="top"
-        content="How long to wait before sending a notification about new alerts that are added to a group of alerts for which an initial notification has already been sent."
-      >
-        <span>
-          <Strong>{groupInterval}</Strong> <span>before sending updates</span>
-        </span>
-      </Tooltip>
+      {groupWait && (
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/notification-policies/Policy.tsx:459]: Since either `group_wait` or `group_interval` can be empty now we have to account for that

**Review by VikaCep — APPROVED** [review]
💯  💯  
Tested it locally and it works great!
