### PR TITLE
Nav: Fix main a11y issues

### LINKED ISSUE #80020: Nav: Fix basic a11y issues
There are a couple of issues with our MegaMenu when it comes to a11y. Check them and adjust if necessary.

- [x] Is a nav element, but it's not announced as such
- [x] Between hamburger menu button and the actual nav there are two other elements
- [x] When entering the MegaMenu the number of items in the main unordered list is not announced
- [x] Announce nav item level
- [x] If there are no _Starred_ items the section gets expanded but no further action is possible => _Your starred dashboards will appear here_ should be announced => item is reachable though

**Findings that were dropped after consulting with Chris Bedwell:**
- Headlines for sub-sections are not announced as headlines but only as links
- Number of list items in level 1 is announced wrongly sometimes

### PR DESCRIPTION
**Pull request by L-M-K-B**
**What is this feature?**

Add an announcement for screenreader when users navigate to the MegaMenu

**Why do we need this feature?**

According to [recommendations for a11y](https://www.w3.org/WAI/tutorials/menus/structure/) the main navigation should be announced as a navigation. This wasn't the case yet.

**Who is this feature for?**

Users of screenreaders

**Which issue(s) does this PR fix?**:

Fixes #80020
(I checked the other bullet points in the ticket and they work sufficiently)

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by L-M-K-B** [comment]
@eledobleefe 

> it's also counting the 'Docked icon' as a navigation list item

Good catch! I didn't notice this yet. I'm going to try to remove it.

There is also something else that came to mind on Friday which I'm going to implement.

**Comment by eledobleefe** [comment]
> @eledobleefe I checked the screenreader announcements for the first level of nav items in the MegaMenu and the number of list items were announced correctly. Could you please have a look at it again or elaborate more about when the wrong number of nav items is announced? Screenshot 2024-01-15 at 14 54 39

Hi @L-M-K-B,
As you can see in this screenshot, the menu list is comprised of 8 elements:
1. Home
2. Starred
3. Dashboards
4. Explore
5. Alerting
6. Testing & synthetics
7. Connections
8. Administration

 but the screen reader says '9 items on the list' so I suppose the 9th is the 'Undocked icon'.

fix-main-issues-with-nav

File: public/app/core/components/AppChrome/DockedMegaMenu/MegaMenu.tsx [hunk 1]
```diff
@@ -60,7 +60,7 @@ export const MegaMenu = React.memo(
         </div>
         <nav className={styles.content}>
           <CustomScrollbar showScrollIndicators hideHorizontalTrack>
-            <ul className={styles.itemList}>
+            <ul className={styles.itemList} aria-label="navigation">
```
Comment (ashharrison90) [inline public/app/core/components/AppChrome/DockedMegaMenu/MegaMenu.tsx:63]: this should be translated

File: public/app/core/components/AppChrome/DockedMegaMenu/MegaMenuItem.tsx [hunk 2]
```diff
@@ -121,7 +121,9 @@ export function MegaMenuItem({ link, activeItem, level = 0, onClick }: Props) {
                 />
               ))
           ) : (
-            <div className={styles.emptyMessage}>{link.emptyMessage}</div>
+            <div className={styles.emptyMessage} aria-live="polite">
```
Comment (ashharrison90) [inline public/app/core/components/AppChrome/DockedMegaMenu/MegaMenuItem.tsx:124]: idk if i'm doing something wrong, but this doesn't announce for me with voiceover? 🤔

Comment (L-M-K-B) [reply public/app/core/components/AppChrome/DockedMegaMenu/MegaMenuItem.tsx:124]: It should only announce when the expand/collapse button of the Starred section is clicked.

Comment (ashharrison90) [reply public/app/core/components/AppChrome/DockedMegaMenu/MegaMenuItem.tsx:124]: ah nm, ignore me, got it working 🙌

File: public/app/core/components/AppChrome/DockedMegaMenu/MegaMenuItem.tsx [hunk 3]
```diff
@@ -121,7 +122,9 @@ export function MegaMenuItem({ link, activeItem, level = 0, onClick }: Props) {
...
+              {t('navigation.megamenu.starredEmptyMessage', 'Your starred dashboards will appear here')}
```
Comment (ashharrison90) [inline public/app/core/components/AppChrome/DockedMegaMenu/MegaMenuItem.tsx:126]: hate to be the bearer of bad news, but this is already translated earlier in the process [here](https://github.com/grafana/grafana/blob/main/public/app/core/utils/navBarItem-translations.ts#L28) 😅

Comment (L-M-K-B) [reply public/app/core/components/AppChrome/DockedMegaMenu/MegaMenuItem.tsx:126]: Oh, interesting. I didn't know this file yet. 😅
I'll remove the second translation.

**Review by ashharrison90 — COMMENTED** [review]
minor naming nit, otherwise lgtm 👍

File: public/app/core/components/AppChrome/DockedMegaMenu/MegaMenu.tsx [hunk 4]
```diff
@@ -60,7 +60,7 @@ export const MegaMenu = React.memo(
         </div>
         <nav className={styles.content}>
           <CustomScrollbar showScrollIndicators hideHorizontalTrack>
-            <ul className={styles.itemList}>
+            <ul className={styles.itemList} aria-label={t('navigation.megamenu.listLevel1', 'navigation')}>
```
Comment (ashharrison90) [inline public/app/core/components/AppChrome/DockedMegaMenu/MegaMenu.tsx:63]: maybe `list-label` instead of `listLevel1`? also think `Navigation` should be capitalised

**Review by ashharrison90 — APPROVED** [review]
lgtm 🙌
