### PR TITLE
Auth: Add managed identity token refresh support for Azure AD OAuth

### LINKED ISSUE #122678: Auth: Azure AD OAuth token refresh fails with AADSTS7000218 when using managed identity authentication
### What happened?

When `client_authentication` is set to `managed_identity` for Azure AD OAuth, the initial login/token exchange works correctly using `managedIdentityCallback()` to obtain a client assertion. However, when the access token expires (~60 minutes) and needs to be refreshed via the refresh token, `TokenSource()` falls through to the default `oauth2.Config.TokenSource()`, which doesn't include a `client_assertion` parameter. Azure AD rejects the request with:

```
AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
```

This causes all users to be silently logged out after their access token expires. We observed this consistently across multiple users in production.

### What did you expect to happen?

Token refresh should succeed transparently, the same way it works for `client_authentication = workload_identity` (which has its own dedicated `azureADTokenSource`). The user session should continue without interruption.

### Did this work before?

The managed identity authentication mode (`client_authentication = managed_identity`) was introduced relatively recently. The initial token exchange has always worked, but the refresh token path has never worked for this mode — there was no dedicated token source handling for it (unlike workload identity, which already had `azureADTokenSource`).

### How do we reproduce it?

1. Configure Azure AD OAuth with:
   ```ini
   [auth.azuread]
   enabled = true
   client_authentication = managed_identity
   managed_identity_client_id = <user-assigned MI client ID>
   federated_credential_audience = api://AzureADTokenExchange
   use_refresh_token = true
   scopes = openid profile email offline_access
   ```
2. Deploy Grafana on Azure App Service (or any environment with managed identity)
3. Log in via Azure AD
4. Wait for the access token to expire (~60 minutes)
5. Observe AADSTS7000218 errors in the logs and user session termination

**Before the fix** — production logs showing the error on every token refresh:
```
logger=oauthtoken level=error msg="Failed to retrieve oauth access token"
  provider=oauth_azuread
  error="oauth2: \"invalid_client\" \"AADSTS7000218: The request body must contain the following parameter:
  'client_assertion' or 'client_secret'.\""
```

This happened consistently for every user whose access token expired — all were logged out.

### Environment

- **Grafana**: latest `main` (also affects current releases)
- **OS**: Azure App Service (Linux)
- **Grafana platform**: Docker

### Additional context

A fix is available in #119134, which adds a dedicated `azureADManagedIdentityTokenSource` following the exact same pattern as the existing workload identity token source. The fix has been verified in production — zero AADSTS7000218 errors after deployment, sessions continue without interruption.

### PR DESCRIPTION
**Pull request by PawOrmstrupMadsen**
**What is this feature?**

Adds a dedicated `azureADManagedIdentityTokenSource` for Azure AD OAuth token refresh when `client_authentication = managed_identity` is configured. This follows the same pattern already used by the existing `azureADTokenSource` for workload identity.

**Why do we need this feature?**

When using managed identity authentication, the initial token exchange works correctly, but token *refresh* fails with `AADSTS7000218` because `TokenSource()` falls through to the default `oauth2.Config.TokenSource()` which doesn't include a `client_assertion`. This silently logs out all users after their access token expires (~60 min), causing repeated authentication disruptions in production.

**Who is this feature for?**

Organizations running Grafana on Azure (App Service, AKS, VMs) that use User-Assigned Managed Identity for Azure AD OAuth authentication with refresh tokens enabled.

**Which issue(s) does this PR fix?**

Fixes #122678

**Special notes for your reviewer:**

- The fix mirrors the existing `azureADTokenSource` (workload identity) pattern — same struct shape, same `fetchToken` helper, same token endpoint call — just sourcing the client assertion from a managed identity credential instead of a token file
- Production-verified: deployed to Azure App Service with `token_rotation_interval_minutes = 2`, confirmed zero AADSTS7000218 errors after the fix (previously occurred on every refresh attempt)
- Changed `TokenSource()` from if/else to a switch statement for clarity across the three authentication modes

**Production verification (before/after logs)**

Before the fix — AADSTS7000218 on every token refresh:
```
2026-02-26T12:13:08Z logger=oauthtoken level=error msg="Failed to retrieve oauth access token"
  provider=oauth_azuread
  error="oauth2: \"invalid_client\" \"AADSTS7000218: The request body must contain the following parameter:
  'client_assertion' or 'client_secret'.\""
```

After the fix — successful managed identity token refresh:
```
2026-02-26T17:30:31Z logger=oauth.azuread level=debug msg="Fetching Token with AzureAD Token Source and Managed Identity"
2026-02-26T17:30:32Z logger=oauth.azuread level=debug msg="AzureADManagedIdentityToken fetchToken completed" expiry=2026-02-26T18:44:26Z
```

Zero AADSTS7000218 errors after deploying the fix. Previously they occurred on every token refresh attempt.

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by PawOrmstrupMadsen** [comment]
Production Verification
Deployed a build with this fix to an Azure App Service running with client_authentication = managed_identity and confirmed the token refresh now works.

Configuration (sanitized)

```
[auth]
token_rotation_interval_minutes = 2
login_maximum_inactive_lifetime_duration = 2h
login_maximum_lifetime_duration = 2h

[auth.azuread]
enabled = true
client_authentication = managed_identity
managed_identity_client_id = <user-assigned MI client ID>
federated_credential_audience = api://AzureADTokenExchange
use_refresh_token = true
use_pkce = true
scopes = openid profile email offline_access

[log]
filters = auth:debug oauth.azuread:debug
```


Before the fix — AADSTS7000218 on every token refresh
When the OAuth access token expired (~60 min after login), TokenSource() fell through to the default [oauth2.Config.TokenSource()](vscode-file://vscode-app/c:/Users/pawor/AppData/Local/Programs/Microsoft%20VS%20Code/072586267e/resources/app/out/vs/code/electron-browser/workbench/workbench.html) which sends no client assertion. Azure AD rejected it:

```
2026-02-26T12:13:08Z logger=oauthtoken        level=error msg="Failed to retrieve oauth access token" 
  provider=oauth_azuread 
  error="oauth2: \"invalid_client\" \"AADSTS7000218: The request body must contain the following parameter: 
  'client_assertion' or 'client_secret'.\""

2026-02-26T12:13:08Z logger=oauth_token.sync   level=error msg="Failed to refresh OAuth access token"

2026-02-26T12:13:08Z logger=authn.service      level=info  msg="Failed to run post auth hook" 
  error="[oauth.expired-token] OAuth access token could not be refreshed: oauth2: \"invalid_client\" \"AADSTS7000218...\""
```
  
  
  This happened consistently for every user whose access token expired (userIDs 14, 17, 20, 33, 37 at 11:42, 12:13, 12:34, 12:40, 12:45, 12:58, 14:16). All were logged out.

After the fix — successful managed identity token refresh
After deploying the build with this PR, the new azureADManagedIdentityTokenSource kicked in when the access token expired (~67 min after login):

```
2026-02-26T17:30:31Z logger=oauth.azuread  level=debug msg="Fetching Token with AzureAD Token Source and Managed Identity"
2026-02-26T17:30:32Z logger=oauth.azuread  level=debug msg="AzureADManagedIdentityToken fetchToken completed" expiry=2026-02-26T18:44:26Z
```


The session continued without interruption — no 401, no AADSTS7000218, no user logout. Session rotation kept running normally every ~2 minutes throughout.

Zero AADSTS7000218 errors after deploying the fix. Previously they occurred on every token refresh attempt.

**Comment by PawOrmstrupMadsen** [comment]
Hi @grafana/identity-squad 👋

Friendly ping on this one. It's been a couple of weeks and I wanted to make sure it didn't slip through the cracks.

Quick summary: when client_authentication = managed_identity is used with Azure AD OAuth, token refresh silently fails because TokenSource() falls through to the default path that doesn't include a client_assertion. This causes AADSTS7000218 errors and logs users out after ~60 minutes.

The fix follows the same pattern already used for workload identity — just extended to managed identity. I've included production before/after logs and tests.

Happy to address any feedback or adjust the approach. Thanks!

File: pkg/login/social/connectors/azuread_oauth.go [hunk 1]
```diff
@@ -271,6 +292,92 @@ func (s *azureADTokenSource) Token() (*oauth2.Token, error) {
...
+	v.Set("client_id", s.clientId)
+	v.Set("grant_type", "refresh_token")
+	v.Set("refresh_token", s.token.RefreshToken)
+	v.Set("client_assertion_type", "urn:ietf:params:oauth:client-assertion-type:jwt-bearer")
+	v.Set("client_assertion", tk.Token)
+
+	return s.fetchToken(v)
+}
+
+func (s *azureADManagedIdentityTokenSource) fetchToken(params url.Values) (*oauth2.Token, error) {
```
Comment (mgyongyosi) [inline pkg/login/social/connectors/azuread_oauth.go]: This is exactly the same as the `fetchToken` of `azureADTokenSource`, could you please extract it to a shared helper function, e.g.: `func fetchAzureADToken(ctx context.Context, log log.Logger, tokenURL string, params url.Values) (*oauth2.Token, error) { ... }` and use this function from both `Token()` function?

File: pkg/login/social/connectors/azuread_oauth.go [hunk 2]
```diff
@@ -271,6 +292,92 @@ func (s *azureADTokenSource) Token() (*oauth2.Token, error) {
...
+		}
+	}()
+
+	body, err := io.ReadAll(resp.Body)
+	if err != nil {
+		return nil, fmt.Errorf("oauth2: cannot fetch token: %v", err)
+	}
+
+	if resp.StatusCode < 200 || resp.StatusCode > 299 {
+		s.log.Debug("oauth2: cannot fetch token", "status", resp.Status, "body", body)
```
Comment (mgyongyosi) [inline pkg/login/social/connectors/azuread_oauth.go]: Could you please change this to Error level? Thanks!
```suggestion
		s.log.Error("oauth2: cannot fetch token", "status", resp.Status, "body", body)
```

**Review by mgyongyosi — COMMENTED** [review]
Hi @PawOrmstrupMadsen, 

Thanks for the contribution! This is a great addition to the project. I have left two minor suggestions, but they’re purely cosmetic.

File: pkg/login/social/connectors/azuread_oauth.go (hunk 2 above)
Comment (PawOrmstrupMadsen) [reply pkg/login/social/connectors/azuread_oauth.go]: yes of cause :)

File: pkg/login/social/connectors/azuread_oauth.go (hunk 1 above)
Comment (PawOrmstrupMadsen) [reply pkg/login/social/connectors/azuread_oauth.go]: sounds like a better structure :)

**Comment by PawOrmstrupMadsen** [comment]
> Hi @PawOrmstrupMadsen,
> 
> Thanks for the contribution! This is a great addition to the project. I have left two minor suggestions, but they’re purely cosmetic.

Changes should be ready for your eyes now :)

**Review by mgyongyosi — APPROVED** [review]

**Comment by mgyongyosi** [comment]
Thank you for your contribution, @PawOrmstrupMadsen. Your pull request has been successfully merged into the project.
