### PR TITLE
CloudWatch: Fix custom metrics

### LINKED ISSUE #28075: Cloudwatch custom metric results in server error when query metricFindQuery
**What happened**:

Querying aws cloudwatch custom metrics results in a 500er server error when try to get the list of available metric names.

grafanabug

Server log 

```
/grafana.....de ecs/grafana/f05454fc888745d99c4f82f261266df8 t=2020-10-07T09:30:21+0000 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=markuman method=POST path=/api/tsdb/query status=500 remote_addr=10.103.11.8 time_ms=27 size=34 referer="https://grafana......de/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22AWS%20CloudWatch%22,%7B%22namespace%22:%22fluentd_metrics%22,%22metricName%22:%22%22,%22expression%22:%22%22,%22dimensions%22:%7B%7D,%22region%22:%22default%22,%22id%22:%22%22,%22alias%22:%22%22,%22statistics%22:%5B%22Average%22%5D,%22period%22:%22%22,%22matchExact%22:true%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D"

```

Browser Payload

```json
{"from":"1602059279729","to":"1602062879731","queries":[{"refId":"metricFindQuery","intervalMs":1,"maxDataPoints":1,"datasourceId":2,"type":"metricFindQuery","subtype":"metrics","region":"eu-central-1","namespace":"fluentd_metrics"}]}
```

Browser response 

```json
{"message":"Metric request error"}
```

**What you expected to happen**:

Autocomplete existings metric names and its dimensions.  
When a dimension is set, the autocomplete works again for its value.

**How to reproduce it (as minimally and precisely as possible)**:

Try to access aws cloudwatch custom metric.

**Anything else we need to know?**:

It works in the past.  But I cannot say for sure in which version it failed.  
Out past used versions. I believe 7.0.x it works fine.  
```
7.0.0
7.0.3
7.0.6
7.1.3
```

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: CloudWatch
- OS Grafana is installed on: Official Docker Container
- User OS & Browser: Firefox 81

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Fix querying of CloudWatch custom metrics. I've tested the change, and it works (I can query custom metrics).

**Which issue(s) this PR fixes**:

Fixes #28075.

### CODE REVIEW

File: pkg/tsdb/cloudwatch/metric_find_query.go [hunk 1]
```diff
@@ -39,8 +39,8 @@ type customMetricsCache struct {
 	Cache  []string
 }
 
-var customMetricsMetricsMap = make(map[string]map[string]map[string]*customMetricsCache)
-var customMetricsDimensionsMap = make(map[string]map[string]map[string]*customMetricsCache)
+var customMetricsMetricsMap = make(map[string]*customMetricsCache)
```
Comment (papagian) [inline pkg/tsdb/cloudwatch/metric_find_query.go:42]: Since this is a hot fix and, as we agreed we want to keep it simple, I suggest to not introduce this change here; it's not necessary for fixing the custom metrics.

**Review by marefr — CHANGES_REQUESTED** [review]
Please do refactoring/code simplification in a separate PR. I have a hard time see what changes are actually related to the bug fix

**Comment by papagian** [comment]
> Please do refactoring/code simplification in a separate PR. I have a hard time see what changes are actually related to the bug fix

For reference the original problem (in master) was [here](https://github.com/grafana/grafana/blob/0e17a15fbd2cabe65087207b347d5a21f95206bd/pkg/tsdb/cloudwatch/metric_find_query.go#L713); the `dsInfo.Namespace` is empty; `getDSInfo()` [does not](https://github.com/grafana/grafana/blob/0e17a15fbd2cabe65087207b347d5a21f95206bd/pkg/tsdb/cloudwatch/cloudwatch.go#L430) set it.

**Review by papagian — APPROVED** [review]
LGTM

**Review by marefr — COMMENTED** [review]
Changes looks good to me. @papagian you have more context so relying on you. 

To me it looks like the Namespace field of `datasourceInfo` now can be removed since no code is using it any longer - is that correct? If so, I would suggest removing it since the reason it was added in first place is no longer there.

**Comment by aknuds1** [comment]
> Changes looks good to me. @papagian you have more context so relying on you.
> 
> To me it looks like the Namespace field of `datasourceInfo` now can be removed since no code is using it any longer - is that correct? If so, I would suggest removing it since the reason it was added in first place is no longer there.

@marefr I was also wondering if it could be removed. Haven't checked though, can try cleaning it in another PR.

**Comment by papagian** [comment]
> > Changes looks good to me. @papagian you have more context so relying on you.
> > To me it looks like the Namespace field of `datasourceInfo` now can be removed since no code is using it any longer - is that correct? If so, I would suggest removing it since the reason it was added in first place is no longer there.
> 
> @marefr I was also wondering if it could be removed. Haven't checked though, can try cleaning it in another PR. There's lots of potential for code scrubbing in CW.

I think that it's safe to remove it and it's good suggestion but also agree that there is a lot of room for improvements so let's remove it in the forthcoming refactoring.

**Review by marefr — APPROVED** [review]
Sounds good :+1:
