### PR TITLE
frontend for trim/apply defaults and some bug fixing

### LINKED ISSUE #31044: A new endpoint for returning trimed dashboard json
A new endpoint similar to GET /api/dashboards/uid/:uid to get the trimmed dashboard json by using cue schema

### PR DESCRIPTION
**Pull request by ying-jeanne**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #31044

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ying-jeanne** [comment]
since cue library is not allowed to insert element into list now, the element of list is stored in string, and combined in the end in order to create a list object directly from compile. the trim default API entirely worked with dashboard JSON 600 lines -> 100 lines.

File: pkg/schema/load/generic.go [hunk 1]
```diff
@@ -155,21 +156,22 @@ func (gvs *genericVersionedSchema) TrimDefaults(r schema.Resource) (schema.Resou
 	return schema.Resource{Value: re}, nil
 }
 
-func removeDefaultHelper(inputdef cue.Value, input cue.Value) (cue.Value, bool, error) {
+func removeDefaultHelper(inputdef cue.Value, input cue.Value) (cue.Value, bool, bool, error) {
```
Comment (marefr) [inline pkg/schema/load/generic.go:159]: Nit. It's a bit hard to understand what the different return values is/mean `cue.Value, bool, bool, error`. Maybe returning `struct, error` instead could make things easier to reason about/understand?

File: pkg/schema/load/generic.go [hunk 2]
```diff
@@ -144,7 +145,7 @@ func (gvs *genericVersionedSchema) TrimDefaults(r schema.Resource) (schema.Resou
 	if err != nil {
 		return r, err
 	}
-	rv, _, err := removeDefaultHelper(gvs.CUE(), rvInstance.Value())
+	rv, _, _, err := removeDefaultHelper(gvs.CUE(), rvInstance.Value())
```
Comment (marefr) [inline pkg/schema/load/generic.go:148]: Nit. Following my other comment on return values. Why are the two booleans returned not important here.

**Review by marefr — APPROVED** [review]
LGTM, but see nits

File: public/app/features/dashboard/components/ShareModal/ShareExport.tsx [hunk 3]
```diff
@@ -86,13 +129,17 @@ export class ShareExport extends PureComponent<Props, State> {
...
     const { shareExternally } = this.state;
+    const { trimDefaults } = this.state;
 
     return (
       <>
         <p className="share-modal-info-text">Export this dashboard.</p>
         <Field label="Export for sharing externally">
           <Switch value={shareExternally} onChange={this.onShareExternallyChange} />
         </Field>
+        <Field label="Export with trimed dashboard json">
```
Comment (marefr) [inline public/app/features/dashboard/components/ShareModal/ShareExport.tsx:140]: With a feature toggle check for this field we should be able to merge this.

File: pkg/schema/load/generic.go (hunk 1 above)
Comment (ying-jeanne) [reply pkg/schema/load/generic.go]: i decided not to remove the empty object, since after it would be difficult to know list[{}, {}] had 2 objects if i removed all empty object.

**Comment by marefr** [comment]
Great :+1:
