### PR TITLE
Loki: Fix uncaught errors if `labelKey` contains special characters

### LINKED ISSUE #49122: Explore Loki query editor crash
**What happened**:

Adding a couple of backslashes on a specific query causes the query editor to crash with a "An unexpected error happened" error message.

Step 1, pasting the query.
Screenshot 2022-05-17 17-32-34 step 1

Step 2, adding the first backslash to escape the double-quote. Nothing happens.
Screenshot 2022-05-17 17-32-47 step 2

Step 3, right after adding a backslash on the second double-quote, the query editor crashes.
Screenshot 2022-05-17 17-33-02 step 3

**What you expected to happen**:

Not a crash :)

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to Grafana Explore.
2. Select any Loki data source.
3. Paste this query:
   ```
   {environment="prod", service="something"}
   |= `"abc_to": "+11111111111"`
   ```
4. Change it to this (add backslashes):
   ```
   {environment="prod", service="something"}
   |= `\"abc_to\": "+11111111111"`
   ```

**Anything else we need to know?**:

I simplified the customer's query until there were no more identifiable information but the problem would still be reproducible.

Full error message:

```
SyntaxError: \ at end of pattern

l@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:990664
li
W@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:3703:29
children@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:3703:3433
div
div
t@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:1309549
ul
Z@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:3703:3799
G@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:3703:879
t@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:127340
div
div
Ss@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:2575:884
WithTheme(undefined)
div
div
o@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:4587:7058
k@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/1828.20c89cb88e65f4bf594e.js:56:3814
./public/app/plugins/datasource/loki/module.ts/qr<@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/lokiPlugin.20c89cb88e65f4bf594e.js:9:2701
Tr@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/lokiPlugin.20c89cb88e65f4bf594e.js:9:3402
Po@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:3111:467
Fo@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:3111:1023
div
div
div
./.yarn/__virtual__/react-beautiful-dnd-virtual-27e4b658e7/3/opt/drone/yarncache/react-beautiful-dnd-npm-13.1.0-fcf5568b1c-12b7e9fbe8.zip/node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js/ko<@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:696911
g@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:1112460
Eo@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:698226
So@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:698335
d@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:4710:1116
div
C@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:7466:181
div
./.yarn/__virtual__/react-beautiful-dnd-virtual-27e4b658e7/3/opt/drone/yarncache/react-beautiful-dnd-npm-13.1.0-fcf5568b1c-12b7e9fbe8.zip/node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js/Ao<@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:700585
g@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:1112460
c@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:1109977
Fr@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:683932
t@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:617363
Ur@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:687475
d@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/1602.20c89cb88e65f4bf594e.js:67:806
Vt@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/explore.20c89cb88e65f4bf594e.js:282:1239
div
div
div
div
t@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:771450
u@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:314:3427
nn@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/explore.20c89cb88e65f4bf594e.js:509:13203
WithTheme(undefined)
g@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:1112460
div
cn@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/explore.20c89cb88e65f4bf594e.js:524:2771
g@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:1112460
Po@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:3111:467
Fo@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:3111:1023
div
div
vn@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/explore.20c89cb88e65f4bf594e.js:524:4454
g@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:1112460
n@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:1055472
St@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:4518:23161
t@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:1130458
t@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:1132479
main
t@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:1127076
div
Ls@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:2585:1012
./public/app/core/utils/ConfigProvider.tsx/d<@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:5098:30514
Po@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:3111:467
Fo@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:3111:1023
y@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:142485
yt@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:4518:22547
c@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/7809.20c89cb88e65f4bf594e.js:2:1109977
Bt@http://gem-lab-01.alexware.deverteuil.net:3000/public/build/3317.20c89cb88e65f4bf594e.js:4531:164
```

**Environment**:
- Grafana version: v8.5.2
- Data source type & version: Loki
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Firefox 100.0
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by svennergr**
**What this PR does / why we need it**:

#49122 describes an edge case, where adding quotes in a string with backticks would lead to a request to get labels. The `labelKey` in that case would contain special character (`\`) which will be interpolated as a pathseparator in the `fetchLabelValues` method. This is why I added URL encoding using `encodeURIComponent` to that part.

However, the querybuilder would still erroneously how the autocomplete for labels:

I fixed that by checking if the given `labelKey` in `getLabelCompletionItems` contains special characters. After the fix, `getLabelCompletionItems` handles `labelKey`s with special characters as if there was no `labelKey` given.

**Which issue(s) this PR fixes**:

Fixes #49122

**Special notes for your reviewer**:

Testing as from #49122:
1. Go to Grafana Explore.
2. Select any Loki data source.
3. Paste this query:
```
{environment="prod", service="something"}
|= `"abc_to": "+11111111111"`
```
4. Change it to this (add backslash):
```
{environment="prod", service="something"}
|= `\"abc_to": "+11111111111"`
```
5. Change it to this (add backslash at the end) - without the fix a error would appear:
```
{environment="prod", service="something"}
|= `\"abc_to\": "+11111111111"`
```

#### Video without the fix:

https://user-images.githubusercontent.com/8092184/171153360-7354d05d-462e-4ae1-8cf4-da105bb37299.mov

#### Video with the fix:

https://user-images.githubusercontent.com/8092184/171153509-8dc09b5e-0ffa-4f6d-9842-ceaebc9b6ea9.mov

### CODE REVIEW

File: public/app/plugins/datasource/loki/language_provider.ts [hunk 1]
```diff
@@ -439,7 +441,8 @@ export default class LokiLanguageProvider extends LanguageProvider {
   }
 
   async fetchLabelValues(key: string): Promise<string[]> {
-    const interpolatedKey = this.datasource.interpolateString(key);
+    const interpolatedKey = encodeURIComponent(this.datasource.interpolateString(key));
```
Comment (gabor) [inline public/app/plugins/datasource/loki/language_provider.ts:444]: hmm.. i agree this fixes the problem, but i'm not sure if this is the way to go.

i think valid Loki label names are the same as valid Prometheus label names and those are

> Label names may contain ASCII letters, numbers, as well as underscores. They must match the regex [a-zA-Z_][a-zA-Z0-9_]*.

so there is nothing there that needs escaping.

or, in other words: if it is not a valid label-name, it does not exist in Loki. so there will be no label-values for it.

so i think we can check that label-name if it is valid, and if it is not, we can just return an empty-array. 

what do you think?

or, in a

Comment (svennergr) [reply public/app/plugins/datasource/loki/language_provider.ts:444]: Yep, adding encoding here will not fix the root cause. Even more, by just applying the fix here, the "autocomplete" view is still showing containing some false labels.
That's why I also added those lines: https://github.com/grafana/grafana/pull/49887/files#diff-0d43c145c3bca230cf6677772375619afc5f3ae4581ff294dfc9582e5c5970c4L279-R282

I think the fix in `getLabelCompletionItems` is in the right place, because now, `labelKeys` with specialcharacters won't even passed to the `fetchLabelValues` function. And only `labelKeys` conforming will be passed to `fetchLabelValues`. You are right, that if they conform, we do not need encoding. On the other hand it does not really hurt adding encoding here, or does it?

**Review by gabor — APPROVED** [review]
nice work!
