### PR TITLE
Cloudwatch : Fixed reseting metric name when changing namespace in Metric Query

### LINKED ISSUE #44290: CloudWatch: Metric Query - Selected MetricName does not reset after changing Namespace
**What happened**:
In a CW panel, Metric Query, when you select a namespace, a metricName and then another namespace, the metricName is kept, even if it is not available for new namespace

https://user-images.githubusercontent.com/42030685/150410455-da5b5ff6-04cf-4c0b-a0f1-5344d4ade784.mov

**What you expected to happen**:
Ideally we would check: if the metricName exists for new namespace, we keep it, otherwise we reset it

**How to reproduce it (as minimally and precisely as possible)**:
Create a CW panel, select `Metric Query` and follow the steps in screenshot

**Anything else we need to know?**:

Similar issue for Metric Search fixed by : https://github.com/grafana/grafana/pull/44165
_This is a follow up_

### PR DESCRIPTION
**Pull request by yaelleC**
## What this PR does / why we need it: 
In the Cloudwatch Metric Query editor, there is a MetricName select component whose values are dependent on a Namespace select component's value.
Currently, if we select a namespace, a metric name for it and then change namespace, the metric value will not be reset even though it does not exist in the dropdown.

This PR fixes this bug, resetting the metricName if it does not exist in new dropdown. 
N.B. If a metricName is shared between old and new namespace, it will not be reset.

### Screenshots
*Before* 

https://user-images.githubusercontent.com/42030685/151616998-8111760e-c7ca-46b3-9efd-8704ddcf69d7.mov

*After*

https://user-images.githubusercontent.com/42030685/151617016-1c25c4be-6307-4143-8958-0188a44c7ef3.mov

## Which issue(s) this PR fixes: 
Fixes #44290 

### Test coverage
Output from 
```
yarn test public/app/plugins/datasource/cloudwatch/components/SQLBuilderEditor/ --coverage --collectCoverageFrom="public/app/plugins/datasource/cloudwatch/components/SQLBuilderEditor/*.{ts,tsx}"
```

```
-------------------------|---------|----------|---------|---------|-----------------------------------------------------------------------------
File                     | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                           
-------------------------|---------|----------|---------|---------|-----------------------------------------------------------------------------
All files                |   68.42 |    43.13 |   56.57 |   68.23 |                                                                             
 SQLBuilderSelectRow.tsx |   88.46 |     75.6 |   73.33 |   90.24 | 91-130                                                                      
 utils.ts                |   58.33 |    49.16 |   57.14 |   59.13 | 55-73,83-92,116,133,151,170-188,195-215,219-224,251,260-277,295,312,331,346 
-------------------------|---------|----------|---------|---------|-----------------------------------------------------------------------------
```
_The uncovered lines are not part of this PR - all modified/added lines are covered_ 

## Special notes for your reviewer:
Similar issue for Metric Search fixed by #44165 

Tests use new Select testing lib discussed in: https://github.com/grafana/grafana/pull/36398 (as I had an issue with the `menuShouldPortal` property on the Select)

### CODE REVIEW

File: public/app/plugins/datasource/cloudwatch/components/SQLBuilderEditor/SQLBuilderSelectRow.tsx [hunk 1]
```diff
@@ -52,16 +53,32 @@ const SQLBuilderSelectRow: React.FC<SQLBuilderSelectRowProps> = ({ datasource, q
...
       <EditorFieldGroup>
         <EditorField label="Namespace" width={16}>
           <Select
+            aria-label="Namespace"
             value={namespace ? toOption(namespace) : null}
             inputId={`${query.refId}-cloudwatch-sql-namespace`}
             options={namespaceOptions}
             allowCustomValue
-            onChange={({ value }) => value && onQueryChange(setNamespace(query, value))}
+            onChange={({ value }) => value && onNamespaceChange(setNamespace(query, value))}
```
Comment (yaelleC) [inline public/app/plugins/datasource/cloudwatch/components/SQLBuilderEditor/SQLBuilderSelectRow.tsx:81]: new handler that validates the metric name (and resets it if not available in new namespace)

File: public/app/plugins/datasource/cloudwatch/components/SQLBuilderEditor/utils.ts [hunk 2]
```diff
@@ -146,6 +146,8 @@ export function setSql(query: CloudWatchMetricsQuery, sql: SQLExpression): Cloud
 
 export function setNamespace(query: CloudWatchMetricsQuery, namespace: string | undefined): CloudWatchMetricsQuery {
   const sql = query.sql ?? {};
+  //updating `namespace` props for CloudWatchMetricsQuery
+  query.namespace = namespace ? namespace : '';
```
Comment (yaelleC) [inline public/app/plugins/datasource/cloudwatch/components/SQLBuilderEditor/utils.ts:150]: _Note :_ I added namespace here compared to existing code as it seems they could be out of sync if we only changed the namespace from the sql query (i.e. we could have a CloudWatchMetricsQuery with namespace: 'ec2' and sql.select.from.property.name : 'athena').

It was not breaking anything as the SQLBuilderEditor code gets its namespace from the sql query only but it seemed bad practice to leave the old namespace somewhere?

Any thoughts?

File: public/app/plugins/datasource/cloudwatch/components/SQLBuilderEditor/utils.ts [hunk 3]
```diff
@@ -230,6 +232,13 @@ export function setMetricName(query: CloudWatchMetricsQuery, metricName: string)
   });
 }
 
+export function removeMetricName(query: CloudWatchMetricsQuery): CloudWatchMetricsQuery {
+  const queryWithNoParams = { ...query };
+  delete queryWithNoParams.sql?.select?.parameters;
+
+  return queryWithNoParams;
+}
+
```
Comment (yaelleC) [inline public/app/plugins/datasource/cloudwatch/components/SQLBuilderEditor/utils.ts:241]: This code is only tested via the SQLBuilderSelectRow tests.
Could add an explicit unit test if preferred?

**Review by sunker — APPROVED** [review]
I think it looks great!

I don't think we follow a convention for this in this repo, but I like to name my tests the following way: `it('should not use...`. Up to you if you want to change this.

File: public/app/plugins/datasource/cloudwatch/components/SQLBuilderEditor/SQLBuilderSelectRow.test.tsx [hunk 4]
```diff
@@ -0,0 +1,139 @@
...
+      from: {
+        type: QueryEditorExpressionType.Property,
+        property: {
+          type: QueryEditorPropertyType.String,
+          name: 'n2',
+        },
+      },
+    });
+    expect(onQueryChange).toHaveBeenCalledTimes(1);
+    expect(onQueryChange.mock.calls).toEqual([[{ ...expectedQuery, namespace: 'n2' }]]);
```
[the remark this answers is not in the document]
Comment (yaelleC) [reply public/app/plugins/datasource/cloudwatch/components/SQLBuilderEditor/SQLBuilderSelectRow.test.tsx:100]: I like the `toEqual` that way I make sure it's only be called once 😉 
But happy to use `toHaveBeenCalledWith` along with `toHaveBeenCalledTimes(1)` if more readable?

[the remark this answers is not in the document]
Comment (sunker) [reply public/app/plugins/datasource/cloudwatch/components/SQLBuilderEditor/SQLBuilderSelectRow.test.tsx:100]: Yes you'll need to use it along with `toHaveBeenCalledTimes(1)` 👍
