### PR TITLE
Nav: Fix alerting links/special cases not selecting the right MegaMenu item

### LINKED ISSUE #83507: Fix mega menu navigation
Alerting pages struggle to manage the active menu entry
image

When the user edit or addd new alert rules the menu entry stops being active
The same happens for contact points and silences
image

### PR DESCRIPTION
**Pull request by tomratcliffe**
**What is this feature?**
Fixes to rendering of the current active item in the MegaMenu

**Why do we need this feature?**
When rendering some URLs, the correct MegaMenu item wasn't being selected. 

For example, `/alerting/silence/new` was highlighting the `Alerting` nav item, rather than `Silences`. This is because not all URLs follow a predictable structure, so until we have a consistent hierarchy of routing, we can't rely on matching the start of URLs. For that specific case, the parent URL is `/alerting/silences` (plural), so the `startsWith` doesn't match up.

It would be a fairly substantial overhaul of existing URLs to fix this and make them all structured consistently, so the cleanest solution right now seems to be providing a way of overriding the exact nav item that should be highlighted - any other suggestions are welcomed though!

**Which issue(s) does this PR fix?**:

Fixes #83507 but also fixes `Administration -> Organizations -> New` not selecting the correct item (it was highlighting `Default preferences`)

### CODE REVIEW

File: public/app/core/components/AppChrome/MegaMenu/MegaMenuItemText.tsx [hunk 1]
```diff
@@ -38,6 +38,7 @@ export function MegaMenuItemText({ children, isActive, onClick, target, url }: P
       href={url}
       target={target}
       onClick={onClick}
+      {...(isActive && { 'aria-current': 'page' })}
```
Comment (tomratcliffe) [inline public/app/core/components/AppChrome/MegaMenu/MegaMenuItemText.tsx:41]: This might be _slightly_ inaccurate, as the href of the active item doesn't exactly match the current page (e.g. it's selecting a link that refers to `/dashboards`, but we might be on `/d/someuid/name`). 
Does this seem right? Or just `aria-current=true`?

File: public/app/core/components/AppChrome/MegaMenu/utils.test.ts [hunk 2]
```diff
@@ -160,14 +162,6 @@ describe('getActiveItem', () => {
     });
   });
 
-  it('returns the alerting link if the pathname is an alert notification', () => {
-    const mockPathName = '/alerting/notification/foo';
-    expect(getActiveItem(mockNavTree, mockPathName)).toEqual({
-      text: 'Alerting item',
-      url: '/alerting/list',
-    });
-  });
```
Comment (tomratcliffe) [inline public/app/core/components/AppChrome/MegaMenu/utils.test.ts:169]: (I believe) When legacy alerting was removed, we also removed the need for this special case as the route doesn't exist anymore

Comment (gillesdemey) [reply public/app/core/components/AppChrome/MegaMenu/utils.test.ts:169]: Yep, this was a legacy route so good riddance :)

**Review by ashharrison90 — COMMENTED** [review]
i _think_ we can do even better now. looking at the url was always temporary and prone to failures. **but** in `MegaMenu` we have access to `state.sectionNav.node`. ignore the name, it's the active page. pretty sure we use it to construct the breadcrumbs

i think we can rewrite `getActiveItem` as something like:
```tsx
export const getActiveItem = (
  navTree: NavModelItem[],
  node: NavModelItem,
): NavModelItem | undefined => {
  if (!node || node.id === 'profile') {
    return undefined;
  }

  for (const link of navTree) {
    if (node.text === link.text && node.url === link.url) {
      return link;
    } else if (link.children) {
      const activeChild = getActiveItem(link.children, node);
      if (activeChild) {
        return activeChild;
      }
    }
  }
  
  if (node.parentItem) {
    return getActiveItem(navTree, node.parentItem);
  }

  return undefined;
};
```

and call it in `MegaMenu` with:
```tsx
    const activeItem = getActiveItem(navItems, state.sectionNav.node);
```

think that will then ✨ _just work_ ✨ for everything except the home page which we'll probably have to special case somehow.

that should also let us delete the `stripQueryParams`, `isBetterMatch` and `isMatchOrChildMatch` functions 🤞

**Comment by tomratcliffe** [comment]
Perfect, thanks @ashharrison90! I had tried to do something similar but I didn't realise that I could get the current page reliably through that 😃 Will have a look and a refactor to fix it. I think the starred dashboards will also need handling differently :+1:

File: public/app/core/components/AppChrome/MegaMenu/utils.ts [hunk 3]
```diff
@@ -62,57 +58,64 @@ export const hasChildMatch = (itemToCheck: NavModelItem, searchItem?: NavModelIt
   );
 };
 
-const stripQueryParams = (url?: string) => {
-  return url?.split('?')[0] ?? '';
-};
+/**
```
Comment (tomratcliffe) [inline public/app/core/components/AppChrome/MegaMenu/utils.ts:61]: I still had to do some special-casing here. I looked at the dashboard page code a little bit to see if I could easily set the nav item to be a "starred" one, but I didn't fancy making changes in somewhere so critical in _this_ PR - unless someone is able to point me in a direction to quickly fix that?

I was getting a dashboard page as only ever having a nav item with ID of `dashboards/browse`

**Review by ashharrison90 — COMMENTED** [review]
ok this is real close, nice job 🙌

i see 2 problems here, but i think we can fix them both 🤞:
- dashboards being special cased
  - let's modify the logic for the dashboard navModel
    - search for a nav item matching the starred dashboard id
    - fall back to `dashboards/browse` otherwise
- visiting `Profile`/`Notification history`/`Change password` shows `Home` as highlighted
  - let's just add a special case for profile:
  ```tsx
    if (currentPage.id === 'profile') {
      return undefined;
    }
  ```
  
i've raised a PR into this branch with those changes [here](https://github.com/grafana/grafana/pull/86623)

i think with those we're good to go 👍

**Review by gillesdemey — APPROVED** [review]
Much cleaner 🙌

**Comment by tomratcliffe** [comment]
I just checked through the ephemeral instance, all seems to be working except for one edge case that I don't think is necessarily worth fixing in here:
When you initially star a dashboard, it won't highlight as expected in the MegaMenu until the page is refreshed, as I assume it's using the original navTree elements from page load. On refresh it works as expected

**Comment by ashharrison90** [comment]
> I just checked through the ephemeral instance, all seems to be working except for one edge case that I don't think is necessarily worth fixing in here: When you initially star a dashboard, it won't highlight as expected in the MegaMenu until the page is refreshed, as I assume it's using the original navTree elements from page load. On refresh it works as expected

ah i remember there being some special logic for this somewhere... lemme see if i can find it 🤔

**Comment by ashharrison90** [comment]
@tomratcliffe have pushed a change for dashboard settings that should fix the remaining e2e tests - don't let anyone ever tell you they don't catch things! 😅 

i'm still looking into whether there's a nice way to handle starred items. i agree it's not really a big deal, and if i can't find a nice solution by tomorrow i'll just stick an approve on this anyway 👍

**Comment by ashharrison90** [comment]
@tomratcliffe have pushed a change to handle starring/unstarring correctly. it's not particularly nice as it means we have to update 2 different slices of the state, but at least it's not regressing behaviour. 

the long term solution would be to move consolidate everything in one slice and move everything to rtk query then it can invalidate the cache and refetch when mutations like starring/unstarring occur

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍

**Comment by tomratcliffe** [comment]
Thanks for all your help on this one Ash! 🙌
