### PR TITLE
TimeSeries: Ignore invalid, user-defined log-y-axis min/max limits

### LINKED ISSUE #59699: Log scale for TimeSeries panel broken - no series or y-axis rendered
**What happened**:

See this loom video:
https://www.loom.com/share/140b8d0f4c684c76ac10bc679c0027ff

Choosing "Logarithmic" scale for a TimeSeries panel breaks the rendering. Both:
- Y-axis, and
- Series themselves
Won't render

Additionally I can't search through the panel options for "Loga" - it gives no results. See this described in the video

**What you expected to happen**:

The panel to render properly with a log scale

**How to reproduce it (as minimally and precisely as possible)**:

Take the "Panel help" data shared below.

**Anything else we need to know?**:

This is stopping us from making the Billing/Usage dashboard a better experience for our customers - it's stopping them from understanding their bills more easily.

**Environment**:

From "Panel Help"

| Key | Value |
|--|--|
| Panel | timeseries @ 9.4.0-42921pre |
| Grafana | 9.4.0-42921pre (d5274dfdda) // Enterprise |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "id": 2,
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "title": "Reproduced with embedded data",
      "libraryPanel": {
        "id": 5,
        "orgId": 1,
        "folderId": 108,
        "folderUid": "XDpUogo7z",
        "uid": "gwg03FK4k",
        "name": "Total Billable Logs Usage",
        "kind": 1,
        "type": "timeseries",
        "description": "",
        "model": {
          "id": 10,
          "gridPos": {
            "h": 8,
            "w": 18,
            "x": 6,
            "y": 15
          },
          "type": "timeseries",
          "title": "Total Billable Logs Usage",
          "datasource": {
            "type": "prometheus",
            "uid": "grafanacloud-usage"
          },
          "pluginVersion": "9.4.0-42921pre",
          "links": [],
          "libraryPanel": {
            "name": "Total Billable Logs Usage",
            "uid": ""
          },
          "description": "",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 10,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "never",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "min": 0,
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "gbytes"
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byRegexp",
                  "options": "/Additional Usage Amount/"
                },
                "properties": [
                  {
                    "id": "unit",
                    "value": "currencyUSD"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "Included Usage"
                },
                "properties": [
                  {
                    "id": "custom.fillOpacity",
                    "value": 0
                  },
                  {
                    "id": "custom.lineWidth",
                    "value": 2
                  },
                  {
                    "id": "custom.lineStyle",
                    "value": {
                      "dash": [
                        10,
                        10
                      ],
                      "fill": "dash"
                    }
                  }
                ]
              }
            ]
          },
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "mode": "multi",
              "sort": "none"
            }
          },
          "repeat": null,
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "grafanacloud-usage"
              },
              "expr": "grafanacloud_org_logs_usage",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "Billable Usage",
              "refId": "A"
            },
            {
              "datasource": {
                "type": "prometheus",
                "uid": "grafanacloud-usage"
              },
              "expr": "grafanacloud_org_logs_overage",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "Additional Usage Amount",
              "refId": "B"
            },
            {
              "datasource": {
                "type": "prometheus",
                "uid": "grafanacloud-usage"
              },
              "expr": "grafanacloud_org_logs_included_usage",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "Included Usage",
              "refId": "C"
            },
            {
              "datasource": {
                "type": "prometheus",
                "uid": "grafanacloud-usage"
              },
              "expr": "max(grafanacloud_logs_instance_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_logs_overage * on (id) group_left(name) grafanacloud_logs_instance_info",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "Additional Usage Amount - {{ name }}",
              "refId": "D"
            }
          ],
          "timeFrom": null,
          "timeShift": null
        },
        "version": 1,
        "meta": {
          "folderName": "GrafanaCloud",
          "folderUid": "XDpUogo7z",
          "connectedDashboards": 1,
          "created": "2022-12-02T10:31:11Z",
          "updated": "2022-12-02T10:31:11Z",
          "createdBy": {
            "id": 2,
            "name": "samjewell",
            "avatarUrl": "/avatar/b8e4a07a837d709871263b8ada7268eb"
          },
          "updatedBy": {
            "id": 2,
            "name": "samjewell",
            "avatarUrl": "/avatar/b8e4a07a837d709871263b8ada7268eb"
          }
        }
      },
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "type": "timeseries-many",
                  "custom": {
                    "resultType": "matrix"
                  },
                  "executedQueryString": "Expr: grafanacloud_org_logs_usage\nStep: 30s",
                  "preferredVisualisationType": "graph"
                },
                "name": "Billable Usage",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 30000
                    }
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {
                      "__name__": "cadfkjeutpqn_eme_wlab_nqexj",
                      "cluster": "tvlp-ym-vsbnnpb-0",
                      "org_id": "466935"
                    },
                    "config": {
                      "displayNameFromDS": "Billable Usage"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1669977150000,
                    1669977180000,
                    1669977210000,
                    1669977240000,
                    1669977270000,
                    1669977300000,
                    1669977330000,
                    1669977360000,
                    1669977390000,
                    1669977420000,
                    1669977450000
                  ],
                  [
                    0.5863264443577,
                    0.5863264443577,
                    0.5863264443577,
                    0.5863264443577,
                    0.5863264443577,
                    0.5863264443577,
                    0.5863264443577,
                    0.5863264443577,
                    0.5863264443577,
                    0.5863264443577,
                    0.5863264443577
                  ]
                ]
              }
            },
            {
              "schema": {
                "refId": "B",
                "meta": {
                  "type": "timeseries-many",
                  "custom": {
                    "resultType": "matrix"
                  },
                  "executedQueryString": "Expr: grafanacloud_org_logs_overage\nStep: 30s",
                  "preferredVisualisationType": "graph"
                },
                "name": "Additional Usage Amount",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 30000
                    }
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {
                      "__name__": "zurnozdhstes_qjw_lkeu_dblepex",
                      "cluster": "tvlp-ym-vsbnnpb-0",
                      "org_id": "466935"
                    },
                    "config": {
                      "displayNameFromDS": "Additional Usage Amount"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1669977150000,
                    1669977180000,
                    1669977210000,
                    1669977240000,
                    1669977270000,
                    1669977300000,
                    1669977330000,
                    1669977360000,
                    1669977390000,
                    1669977420000,
                    1669977450000
                  ],
                  [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                  ]
                ]
              }
            },
            {
              "schema": {
                "refId": "C",
                "meta": {
                  "type": "timeseries-many",
                  "custom": {
                    "resultType": "matrix"
                  },
                  "executedQueryString": "Expr: grafanacloud_org_logs_included_usage\nStep: 30s",
                  "preferredVisualisationType": "graph"
                },
                "name": "Included Usage",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 30000
                    }
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {
                      "__name__": "uaihnslpqzoj_ghx_hpfq_kvnjaqee_xmvgl",
                      "cluster": "tvlp-ym-vsbnnpb-0",
                      "org_id": "466935"
                    },
                    "config": {
                      "displayNameFromDS": "Included Usage"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1669977150000,
                    1669977180000,
                    1669977210000,
                    1669977240000,
                    1669977270000,
                    1669977300000,
                    1669977330000,
                    1669977360000,
                    1669977390000,
                    1669977420000,
                    1669977450000
                  ],
                  [
                    400,
                    400,
                    400,
                    400,
                    400,
                    400,
                    400,
                    400,
                    400,
                    400,
                    400
                  ]
                ]
              }
            },
            {
              "schema": {
                "refId": "D",
                "meta": {
                  "type": "timeseries-many",
                  "custom": {
                    "resultType": "matrix"
                  },
                  "executedQueryString": "Expr: max(grafanacloud_logs_instance_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_logs_overage * on (id) group_left(name) grafanacloud_logs_instance_info\nStep: 30s",
                  "preferredVisualisationType": "graph"
                },
                "name": "Additional Usage Amount - samjewell17sept-logs",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 30000
                    }
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {
                      "id": "102631",
                      "name": "caubrdtmt17nzxe-prjv"
                    },
                    "config": {
                      "displayNameFromDS": "Additional Usage Amount - samjewell17sept-logs"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1669977150000,
                    1669977180000,
                    1669977210000,
                    1669977240000,
                    1669977270000,
                    1669977300000,
                    1669977330000,
                    1669977360000,
                    1669977390000,
                    1669977420000,
                    1669977450000
                  ],
                  [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                  ]
                ]
              }
            },
            {
              "schema": {
                "refId": "D",
                "meta": {
                  "type": "timeseries-many",
                  "custom": {
                    "resultType": "matrix"
                  },
                  "executedQueryString": "Expr: max(grafanacloud_logs_instance_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_logs_overage * on (id) group_left(name) grafanacloud_logs_instance_info\nStep: 30s",
                  "preferredVisualisationType": "graph"
                },
                "name": "Additional Usage Amount - samjewell19oct-logs",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 30000
                    }
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {
                      "id": "114281",
                      "name": "xqwnfebdx19kad-rrrb"
                    },
                    "config": {
                      "displayNameFromDS": "Additional Usage Amount - samjewell19oct-logs"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1669977150000,
                    1669977180000,
                    1669977210000,
                    1669977240000,
                    1669977270000,
                    1669977300000,
                    1669977330000,
                    1669977360000,
                    1669977390000,
                    1669977420000,
                    1669977450000
                  ],
                  [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                  ]
                ]
              }
            },
            {
              "schema": {
                "refId": "D",
                "meta": {
                  "type": "timeseries-many",
                  "custom": {
                    "resultType": "matrix"
                  },
                  "executedQueryString": "Expr: max(grafanacloud_logs_instance_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_logs_overage * on (id) group_left(name) grafanacloud_logs_instance_info\nStep: 30s",
                  "preferredVisualisationType": "graph"
                },
                "name": "Additional Usage Amount - samjewell-logs",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 30000
                    }
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {
                      "id": "22920",
                      "name": "pvffnwxmo-kths"
                    },
                    "config": {
                      "displayNameFromDS": "Additional Usage Amount - samjewell-logs"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1669977150000,
                    1669977180000,
                    1669977210000,
                    1669977240000,
                    1669977270000,
                    1669977300000,
                    1669977330000,
                    1669977360000,
                    1669977390000,
                    1669977420000,
                    1669977450000
                  ],
                  [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                  ]
                ]
              }
            },
            {
              "schema": {
                "refId": "D",
                "meta": {
                  "type": "timeseries-many",
                  "custom": {
                    "resultType": "matrix"
                  },
                  "executedQueryString": "Expr: max(grafanacloud_logs_instance_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_logs_overage * on (id) group_left(name) grafanacloud_logs_instance_info\nStep: 30s",
                  "preferredVisualisationType": "graph"
                },
                "name": "Additional Usage Amount - samjewell10aug22-logs",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 30000
                    }
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {
                      "id": "264324",
                      "name": "ejlmihsho10alz22-crjs"
                    },
                    "config": {
                      "displayNameFromDS": "Additional Usage Amount - samjewell10aug22-logs"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1669977150000,
                    1669977180000,
                    1669977210000,
                    1669977240000,
                    1669977270000,
                    1669977300000,
                    1669977330000,
                    1669977360000,
                    1669977390000,
                    1669977420000,
                    1669977450000
                  ],
                  [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                  ]
                ]
              }
            }
          ]
        }
      ],
      "options": {
        "tooltip": {
          "mode": "multi",
          "sort": "none"
        },
        "legend": {
          "showLegend": true,
          "displayMode": "list",
          "placement": "bottom",
          "calcs": []
        }
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "drawStyle": "line",
            "lineInterpolation": "linear",
            "barAlignment": 0,
            "lineWidth": 1,
            "fillOpacity": 10,
            "gradientMode": "none",
            "spanNulls": false,
            "showPoints": "never",
            "pointSize": 5,
            "stacking": {
              "mode": "none",
              "group": "A"
            },
            "axisPlacement": "auto",
            "axisLabel": "",
            "axisColorMode": "text",
            "scaleDistribution": {
              "type": "linear"
            },
            "axisCenteredZero": false,
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "color": {
            "mode": "palette-classic"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "min": 0,
          "unit": "gbytes"
        },
        "overrides": [
          {
            "matcher": {
              "id": "byRegexp",
              "options": "/Additional Usage Amount/"
            },
            "properties": [
              {
                "id": "unit",
                "value": "currencyUSD"
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "Included Usage"
            },
            "properties": [
              {
                "id": "custom.fillOpacity",
                "value": 0
              },
              {
                "id": "custom.lineWidth",
                "value": 2
              },
              {
                "id": "custom.lineStyle",
                "value": {
                  "dash": [
                    10,
                    10
                  ],
                  "fill": "dash"
                }
              }
            ]
          }
        ]
      },
      "type": "timeseries",
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "pluginVersion": "9.4.0-42921pre",
      "links": [],
      "description": "",
      "repeat": null,
      "timeFrom": null,
      "timeShift": null
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >timeseries @ 9.4.0-42921pre</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[prometheus], B[prometheus], C[prometheus], D[prometheus]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 7 frames, 14 fields, 77 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>9.4.0-42921pre (d5274dfdda) // Enterprise</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"id\": 2,\n  \"gridPos\": {\n    \"h\": 13,\n    \"w\": 17,\n    \"x\": 0,\n    \"y\": 0\n  },\n  \"title\": \"Total Billable Logs Usage\",\n  \"libraryPanel\": {\n    \"id\": 5,\n    \"orgId\": 1,\n    \"folderId\": 108,\n    \"folderUid\": \"XDpUogo7z\",\n    \"uid\": \"gwg03FK4k\",\n    \"name\": \"Total Billable Logs Usage\",\n    \"kind\": 1,\n    \"type\": \"timeseries\",\n    \"description\": \"\",\n    \"model\": {\n      \"id\": 10,\n      \"gridPos\": {\n        \"h\": 8,\n        \"w\": 18,\n        \"x\": 6,\n        \"y\": 15\n      },\n      \"type\": \"timeseries\",\n      \"title\": \"Total Billable Logs Usage\",\n      \"datasource\": {\n        \"type\": \"prometheus\",\n        \"uid\": \"grafanacloud-usage\"\n      },\n      \"pluginVersion\": \"9.4.0-42921pre\",\n      \"links\": [],\n      \"libraryPanel\": {\n        \"name\": \"Total Billable Logs Usage\",\n        \"uid\": \"\"\n      },\n      \"description\": \"\",\n      \"fieldConfig\": {\n        \"defaults\": {\n          \"color\": {\n            \"mode\": \"palette-classic\"\n          },\n          \"custom\": {\n            \"axisCenteredZero\": false,\n            \"axisColorMode\": \"text\",\n            \"axisLabel\": \"\",\n            \"axisPlacement\": \"auto\",\n            \"barAlignment\": 0,\n            \"drawStyle\": \"line\",\n            \"fillOpacity\": 10,\n            \"gradientMode\": \"none\",\n            \"hideFrom\": {\n              \"legend\": false,\n              \"tooltip\": false,\n              \"viz\": false\n            },\n            \"lineInterpolation\": \"linear\",\n            \"lineWidth\": 1,\n            \"pointSize\": 5,\n            \"scaleDistribution\": {\n              \"type\": \"linear\"\n            },\n            \"showPoints\": \"never\",\n            \"spanNulls\": false,\n            \"stacking\": {\n              \"group\": \"A\",\n              \"mode\": \"none\"\n            },\n            \"thresholdsStyle\": {\n              \"mode\": \"off\"\n            }\n          },\n          \"mappings\": [],\n          \"min\": 0,\n          \"thresholds\": {\n            \"mode\": \"absolute\",\n            \"steps\": [\n              {\n                \"color\": \"green\",\n                \"value\": null\n              },\n              {\n                \"color\": \"red\",\n                \"value\": 80\n              }\n            ]\n          },\n          \"unit\": \"gbytes\"\n        },\n        \"overrides\": [\n          {\n            \"matcher\": {\n              \"id\": \"byRegexp\",\n              \"options\": \"/Additional Usage Amount/\"\n            },\n            \"properties\": [\n              {\n                \"id\": \"unit\",\n                \"value\": \"currencyUSD\"\n              }\n            ]\n          },\n          {\n            \"matcher\": {\n              \"id\": \"byName\",\n              \"options\": \"Included Usage\"\n            },\n            \"properties\": [\n              {\n                \"id\": \"custom.fillOpacity\",\n                \"value\": 0\n              },\n              {\n                \"id\": \"custom.lineWidth\",\n                \"value\": 2\n              },\n              {\n                \"id\": \"custom.lineStyle\",\n                \"value\": {\n                  \"dash\": [\n                    10,\n                    10\n                  ],\n                  \"fill\": \"dash\"\n                }\n              }\n            ]\n          }\n        ]\n      },\n      \"options\": {\n        \"legend\": {\n          \"calcs\": [],\n          \"displayMode\": \"list\",\n          \"placement\": \"bottom\",\n          \"showLegend\": true\n        },\n        \"tooltip\": {\n          \"mode\": \"multi\",\n          \"sort\": \"none\"\n        }\n      },\n      \"repeat\": null,\n      \"targets\": [\n        {\n          \"datasource\": {\n            \"type\": \"prometheus\",\n            \"uid\": \"grafanacloud-usage\"\n          },\n          \"expr\": \"grafanacloud_org_logs_usage\",\n          \"format\": \"time_series\",\n          \"intervalFactor\": 2,\n          \"legendFormat\": \"Billable Usage\",\n          \"refId\": \"A\"\n        },\n        {\n          \"datasource\": {\n            \"type\": \"prometheus\",\n            \"uid\": \"grafanacloud-usage\"\n          },\n          \"expr\": \"grafanacloud_org_logs_overage\",\n          \"format\": \"time_series\",\n          \"intervalFactor\": 2,\n          \"legendFormat\": \"Additional Usage Amount\",\n          \"refId\": \"B\"\n        },\n        {\n          \"datasource\": {\n            \"type\": \"prometheus\",\n            \"uid\": \"grafanacloud-usage\"\n          },\n          \"expr\": \"grafanacloud_org_logs_included_usage\",\n          \"format\": \"time_series\",\n          \"intervalFactor\": 2,\n          \"legendFormat\": \"Included Usage\",\n          \"refId\": \"C\"\n        },\n        {\n          \"datasource\": {\n            \"type\": \"prometheus\",\n            \"uid\": \"grafanacloud-usage\"\n          },\n          \"expr\": \"max(grafanacloud_logs_instance_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_logs_overage * on (id) group_left(name) grafanacloud_logs_instance_info\",\n          \"format\": \"time_series\",\n          \"intervalFactor\": 2,\n          \"legendFormat\": \"Additional Usage Amount - {{ name }}\",\n          \"refId\": \"D\"\n        }\n      ],\n      \"timeFrom\": null,\n      \"timeShift\": null\n    },\n    \"version\": 1,\n    \"meta\": {\n      \"folderName\": \"GrafanaCloud\",\n      \"folderUid\": \"XDpUogo7z\",\n      \"connectedDashboards\": 1,\n      \"created\": \"2022-12-02T10:31:11Z\",\n      \"updated\": \"2022-12-02T10:31:11Z\",\n      \"createdBy\": {\n        \"id\": 2,\n        \"name\": \"samjewell\",\n        \"avatarUrl\": \"/avatar/b8e4a07a837d709871263b8ada7268eb\"\n      },\n      \"updatedBy\": {\n        \"id\": 2,\n        \"name\": \"samjewell\",\n        \"avatarUrl\": \"/avatar/b8e4a07a837d709871263b8ada7268eb\"\n      }\n    }\n  },\n  \"targets\": [\n    {\n      \"datasource\": {\n        \"type\": \"prometheus\",\n        \"uid\": \"grafanacloud-usage\"\n      },\n      \"expr\": \"grafanacloud_org_logs_usage\",\n      \"format\": \"time_series\",\n      \"intervalFactor\": 2,\n      \"legendFormat\": \"Billable Usage\",\n      \"refId\": \"A\"\n    },\n    {\n      \"datasource\": {\n        \"type\": \"prometheus\",\n        \"uid\": \"grafanacloud-usage\"\n      },\n      \"expr\": \"grafanacloud_org_logs_overage\",\n      \"format\": \"time_series\",\n      \"intervalFactor\": 2,\n      \"legendFormat\": \"Additional Usage Amount\",\n      \"refId\": \"B\"\n    },\n    {\n      \"datasource\": {\n        \"type\": \"prometheus\",\n        \"uid\": \"grafanacloud-usage\"\n      },\n      \"expr\": \"grafanacloud_org_logs_included_usage\",\n      \"format\": \"time_series\",\n      \"intervalFactor\": 2,\n      \"legendFormat\": \"Included Usage\",\n      \"refId\": \"C\"\n    },\n    {\n      \"datasource\": {\n        \"type\": \"prometheus\",\n        \"uid\": \"grafanacloud-usage\"\n      },\n      \"expr\": \"max(grafanacloud_logs_instance_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_logs_overage * on (id) group_left(name) grafanacloud_logs_instance_info\",\n      \"format\": \"time_series\",\n      \"intervalFactor\": 2,\n      \"legendFormat\": \"Additional Usage Amount - {{ name }}\",\n      \"refId\": \"D\"\n    }\n  ],\n  \"options\": {\n    \"tooltip\": {\n      \"mode\": \"multi\",\n      \"sort\": \"none\"\n    },\n    \"legend\": {\n      \"showLegend\": true,\n      \"displayMode\": \"list\",\n      \"placement\": \"bottom\",\n      \"calcs\": []\n    }\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"drawStyle\": \"line\",\n        \"lineInterpolation\": \"linear\",\n        \"barAlignment\": 0,\n        \"lineWidth\": 1,\n        \"fillOpacity\": 10,\n        \"gradientMode\": \"none\",\n        \"spanNulls\": false,\n        \"showPoints\": \"never\",\n        \"pointSize\": 5,\n        \"stacking\": {\n          \"mode\": \"none\",\n          \"group\": \"A\"\n        },\n        \"axisPlacement\": \"auto\",\n        \"axisLabel\": \"\",\n        \"axisColorMode\": \"text\",\n        \"scaleDistribution\": {\n          \"type\": \"linear\"\n        },\n        \"axisCenteredZero\": false,\n        \"hideFrom\": {\n          \"tooltip\": false,\n          \"viz\": false,\n          \"legend\": false\n        },\n        \"thresholdsStyle\": {\n          \"mode\": \"off\"\n        }\n      },\n      \"color\": {\n        \"mode\": \"palette-classic\"\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"color\": \"green\",\n            \"value\": null\n          },\n          {\n            \"color\": \"red\",\n            \"value\": 80\n          }\n        ]\n      },\n      \"min\": 0,\n      \"unit\": \"gbytes\"\n    },\n    \"overrides\": [\n      {\n        \"matcher\": {\n          \"id\": \"byRegexp\",\n          \"options\": \"/Additional Usage Amount/\"\n        },\n        \"properties\": [\n          {\n            \"id\": \"unit\",\n            \"value\": \"currencyUSD\"\n          }\n        ]\n      },\n      {\n        \"matcher\": {\n          \"id\": \"byName\",\n          \"options\": \"Included Usage\"\n        },\n        \"properties\": [\n          {\n            \"id\": \"custom.fillOpacity\",\n            \"value\": 0\n          },\n          {\n            \"id\": \"custom.lineWidth\",\n            \"value\": 2\n          },\n          {\n            \"id\": \"custom.lineStyle\",\n            \"value\": {\n              \"dash\": [\n                10,\n                10\n              ],\n              \"fill\": \"dash\"\n            }\n          }\n        ]\n      }\n    ]\n  },\n  \"type\": \"timeseries\",\n  \"datasource\": {\n    \"type\": \"prometheus\",\n    \"uid\": \"grafanacloud-usage\"\n  },\n  \"pluginVersion\": \"9.4.0-42921pre\",\n  \"links\": [],\n  \"description\": \"\",\n  \"repeat\": null,\n  \"timeFrom\": null,\n  \"timeShift\": null\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: Total Billable Logs Usage // 2022-12-02 10:37:46",
  "tags": [
    "debug",
    "debug-timeseries"
  ],
  "time": {
    "from": "2022-12-02T10:32:46.557Z",
    "to": "2022-12-02T10:37:46.557Z"
  }
}
```
</details>

### LINKED ISSUE #63256: [Timeseries] Infinite loop with logarithmic axis
**What happened**:

Timeseries panel with logarithmic axis and this dataset

```csv
"Time","DEN"
2023-02-10 13:55:00,
2023-02-10 14:00:00,134 ms
2023-02-10 14:05:00,132 ms
2023-02-10 14:10:00,133 ms
2023-02-10 14:15:00,138 ms
2023-02-10 14:20:00,138 ms
2023-02-10 14:25:00,133 ms
2023-02-10 14:30:00,138 ms
2023-02-10 14:35:00,129 ms
2023-02-10 14:40:00,126 ms
2023-02-10 14:45:00,137 ms
2023-02-10 14:50:00,127 ms
```

crashes on

```
es.array.push.js:34 Uncaught RangeError: Invalid array length
    at Array.push (es.array.push.js:34:1)
    at Object.logAxisSplits [as splits] (uPlot.esm.js:1358:1)
    at uPlot.esm.js:4085:1
    at Array.forEach (<anonymous>)
    at axesCalc (uPlot.esm.js:4050:1)
    at convergeSize (uPlot.esm.js:3129:1)
    at _commit (uPlot.esm.js:4340:1)
```

This is the commit that caused it, without it, it does not happen

https://github.com/grafana/grafana/pull/60768

It infinitely loops through this do statement 

https://github.com/leeoniya/uPlot/blob/1e4ea5427100f81750a93c1ab9f5b78d3c0bf116/dist/uPlot.esm.js#L1357-L1367

**Environment**:
- Grafana version: 0bd326d846bba158be115cb2de8992d9e037409c

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes #59699
Fixes #63256

test dashboard:

<details><summary>log-scale-ignore-limits.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 541,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "log": 2,
              "type": "log"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "max": 150,
          "min": 0,
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "1,20,90.5,30,5,0"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "refresh": "",
  "revision": 1,
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "log-scale-ignore-limits",
  "uid": "lB9DdpKVk",
  "version": 1,
  "weekStart": ""
}
```
</details>

### CODE REVIEW

File: packages/grafana-ui/src/components/uPlot/config/UPlotScaleBuilder.ts [hunk 1]
```diff
@@ -156,11 +156,19 @@ export class UPlotScaleBuilder extends PlotConfigBuilder<ScaleProps, Scale> {
 
       // if all we got were hard limits, treat them as static min/max
       if (hardMinOnly) {
-        minMax[0] = hardMin!;
+        if (scale.distr === 3 && hardMin! <= 0) {
+          // guard log scales from <= 0 user-defined limits
```
Comment (zoltanbedi) [inline packages/grafana-ui/src/components/uPlot/config/UPlotScaleBuilder.ts:160]: Did you want to do anything here? or should the condition reversed?

**Comment by zoltanbedi** [comment]
Anything else you want to do in this pr? Do you need help with this?

File: packages/grafana-ui/src/components/uPlot/config/UPlotScaleBuilder.ts (hunk 1 above)
Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/config/UPlotScaleBuilder.ts:160]: i can reverse it, but it doesnt read as easily, imo:

```js
if (scale.distr !== 3 || hardMin! > 0) {
  minMax[0] = hardMin!;
}
```

i think JS minifiers will handle inverting it anyways.

**Comment by leeoniya** [comment]
> Anything else you want to do in this pr?

i should have mentioned it here as well [1], but this requires a new uPlot release, too. i'll do that later this week.

[1] https://github.com/grafana/support-escalations/issues/4707#issuecomment-1365643043

**Review by ryantxu — COMMENTED** [review]
LGTM 
image

Are the required uplot changes already in 9.4?  or was that added after the branch?

**Review by ryantxu — APPROVED** [review]
