### PR TITLE
Dashboard: Template variables are now correctly persisted when clicking breadcrumb links

### LINKED ISSUE #46659: Dashboard variable selections don't persist after clicking the breadcrumb for search
**What happened**:
When viewing a dashboard and setting some variable drop down selections, clicking the the breadcrumb at the top left and then cancelling (ESC) will revert the selections to some default state. Clicking on the magnifying glass (Search Dashboards) does not revert the state.

**What you expected to happen**:
Cancelling out of search dashboards should retain whatever values you selected in the variables before.

**How to reproduce it (as minimally and precisely as possible)**:
- open a dashboard with variable dropdowns created
- select some variables 
- click on the breadcrumb (on any folder)
- hit the ESC key or the X to close it

**Anything else we need to know?**:
No

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: prometheus v2.18.0
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: MacOS 12.2.1 Safari
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- Converts `DashNav` to a functional component
- introduces a new `getUrlForPartial` method passing the location from `useLocation`
- deprecates `updateSearchParams` since it was confusingly named and wouldn't work with the way we define template variables containing multiple values... 😬 

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/46659

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/dashboard/components/DashNav/DashNav.tsx [hunk 1]
```diff
@@ -252,42 +251,41 @@ class DashNav extends PureComponent<Props> {
...
-        {this.renderRightActionsButton()}
-      </PageToolbar>
-    );
-  }
-}
+  const { isFullscreen, title, folderTitle } = props;
+  // this ensures the component rerenders when the location changes
+  useLocation();
+  const titleHref = locationUtil.updateSearchParams(window.location.href, '?search=open');
+  const parentHref = locationUtil.updateSearchParams(window.location.href, '?search=open&folder=current');
```
Comment (torkelo) [inline public/app/features/dashboard/components/DashNav/DashNav.tsx:273]: This looks strange / bad, updating url in render path? The function name for this util is really confusing :)  And it does something that is also pretty bad. 

This should be more like
```ts
const titleRef = locationSrv.getUrlForPartial({search: 'option'});
```

Comment (ashharrison90) [reply public/app/features/dashboard/components/DashNav/DashNav.tsx:273]: @torkelo yeah i agree the naming of this function is bad since it doesn't update the actual url.
what it actually does is: given a url string and some search params you want to update, return a new url string.

as we're exposing this from `@grafana/data`, we're a little hamstrung by semver... could copy the method and rename it to `getUrlForPartial` and deprecate the old method until grafana 9? wdyt? 🤔

Comment (torkelo) [reply public/app/features/dashboard/components/DashNav/DashNav.tsx:273]: yea, we could add a method, getUrlForPartial that takes in the location returned by useLocation? and does something similar to: https://github.com/grafana/grafana/blob/main/packages/grafana-runtime/src/services/LocationService.ts#L59  except just returns the new url

**Review by joshhunt — APPROVED** [review]
