### PR TITLE
Alerting: Use configured headers for external alertmanager

### LINKED ISSUE #60807: Grafana managed alerts are not delivered to Mimir Alertmanager in multi-tenant mode
**What happened**: 
Grafana Managed alerts are not delivered to Mimir Alertmanager. We have enabled Grafana Unified alerting and configured a Grafana managed alert.
The admin page of the Grafana managed is configured to send alerts to external Alertmanager, in our case it is Mimir Alertmanager and multi-tenancy is enabled.
Alertmanager data source implementation is selected as Mimir, the health check of the data source is fine, we are able to configure  contact points and notifications policy and it’s getting uploaded to the respective tenants.

Upon checking the Grafana logs we see Grafana is trying to do a POST request to Mimir Alertmanager on /api/v2/alerts and resulting in HTTP 404. 
We further analysed and found the Mimir Alertmanager exposes the V2 api endpoints on /alertmanager/api/v2/alerts. So we need Grafana to include the /alertmanager to the URI when it’s trying to post the request to Mimir alertmanager.

We tried to include /alertmanager to the alertmanager url in the datasource configuration and upon saving changes we are getting warning stating “It looks like you have chosen a Mimir or Cortex implementation , but detected a Prometheus endpoint.Please update the implementation and try again”.

The change helps to include the /alertmanager to the URI but results in HTTP 401 as we suppose http header is excluded in the POST request sent to Mimir alertmanager.

**What you expected to happen**:

Grafana managed alerts gets delivered to Mimir alertmanager on the correct endpoint.

**How to reproduce it (as minimally and precisely as possible)**:

Configure Mimir alertmanager as alertmanager datasource in Grafana with implementation selected to Mimir.
Enable the Receive Grafana alerts options in the datasource.
Configure X-scope-orgid header
Define contact points and notification policy using Grafana UI.
Navigate to admin page of alert rules and set the “Send alerts to” under External alertmanagers to Only External or Both.
Configure a Grafana alert and verify the logs of Grafana once the alert is moved to Firing state.

**Anything else we need to know?**:

We went one step further and removed the tenancy and post which we see alerts are getting delivered to Alertmanager but it’s not following our tenant specific contact points and notification policies instead using the mimir fallback alertmanager configuration which is kind of expected.

The removal of tenancy also results in contact points and notification policies getting a JSON response instead of YAML configuration.

We had a discussion in Grafana Slack Mimir channel and the link to the discussion is as below https://grafana.slack.com/archives/C039863E8P7/p1671787647315839

I’m unable to add screenshots please refer to support ticket 74646.

**Environment**: 
- Grafana version:  9.3.1 (Enterprise)
- Data source type & version: Alertmanager (Mimir) & 2.5.0
- OS Grafana is installed on: RedHat Linux 8 (UBI 8 image)
- User OS & Browser: Chrome
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by JohnnyQQQQ**
**What is this feature?**

We pass the configured headers from the alertmanager datasource to the external alertmanager call if any are configured.

**Why do we need this feature?**

Customers who are using an external alertmanager that need some headers, i.e. a multi tenant alertmanager from mimir or cortex.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**: 

Fixes #60807

**Special notes for your reviewer**:

All changes were tested manually by me.

We did copy `notifier.go` from upstream and should try to upstream those changes afterward as they might be useful to a broader audience.

### CODE REVIEW

**Review by yuri-tceretian — DISMISSED** [review]
I do not think copying whole client is a good idea. We have our fork of prometheus alertmanager and I think it would make more sense to update it and then use it in sender.

**Comment by JohnnyQQQQ** [comment]
> I do not think copying whole client is a good idea. We have our fork of prometheus alertmanager and I think it would make more sense to update it and then use it in sender.

This code is from `prometheus/prometheus` and not from the `prometheus/alertmanager`. 

Josh and me did an offline code review and agreed to move forward with this but try not to copy the `config.go` file. So I will submit some changes in the near future.

**Comment by yuri-tceretian** [comment]
Then I would appreciate more information about why the decision was to vendor file from upstream instead of updating our fork and then seek for an opportunity to upstream it.

File: pkg/services/ngalert/sender/notifier_ext.go [hunk 1]
```diff
@@ -0,0 +1,198 @@
+// This extension file contains all changed function that would normally be
+// in notifier.go. This helps us to keep track with the changes compared
+// to upstream.
```
Comment (gotjosh) [inline pkg/services/ngalert/sender/notifier_ext.go:3]:
```suggestion
// This extension file contains all changed functions that would normally be
// in notifier.go. This helps us to keep track of the changes compared
// to upstream.
// Changes are denoted explicitly by a comment with the prefix "Extension:"
```

File: pkg/services/ngalert/sender/router.go [hunk 2]
```diff
@@ -230,7 +258,40 @@ func (d *AlertsRouter) alertmanagersFromDatasources(orgID int64) ([]string, erro
 				"error", err)
 			continue
 		}
-		alertmanagers = append(alertmanagers, amURL)
+		m, err := ds.JsonData.Map()
+		if err != nil {
+			return nil, fmt.Errorf("failed to fetch headers for datasource: %w", err)
+		}
+
+		const headerName = "httpHeaderName"
```
Comment (gotjosh) [inline pkg/services/ngalert/sender/router.go:266]: It's kind of a bonkers that such a sensitive thing is not export as a constant directly from the datasource package - I'd add these for both `httpHeaderValue` and `httpHeaderName ` - and replace the string usage with constants.

Comment (gotjosh) [inline pkg/services/ngalert/sender/router.go:266]: It's kind of a bonkers that such a sensitive thing is not export as a constant directly from the datasource package - I'd add these for both `httpHeaderValue` and `httpHeaderName ` - and replace the string usage with constants.

File: pkg/services/ngalert/sender/router.go [hunk 3]
```diff
@@ -128,8 +129,12 @@ func (d *AlertsRouter) SyncAndApplyConfigFromDatabase() error {
 		redactedAMs := buildRedactedAMs(d.logger, alertmanagers, cfg.OrgID)
 		d.logger.Debug("Alertmanagers found in the configuration", "alertmanagers", redactedAMs)
 
+		var urls []string
+		for _, cfg := range alertmanagers {
+			urls = append(urls, cfg.amURL)
+		}
 		// We have a running sender, check if we need to apply a new config.
-		amHash := asSHA256(alertmanagers)
+		amHash := asSHA256(append(urls, headersString(alertmanagers)))
```
Comment (gotjosh) [inline pkg/services/ngalert/sender/router.go:137]: I found this very confusing initially because I couldn't understand why we were combining a header string with the URLs found. Then I realise that we have changed the signature of `alertmanagersFromDatasources` and everything made more sense.

However, `asSHA256` is only used here so it feels unnecessary complexity that we need to extract URLs and then have a separate function (in `headersString`) to combine both things that belong to a separate struct. 

I suggest you go the route of:

```golang
type externalAMcfg struct {
	amURL   string
	headers map[string]string
}

func (cfg *externalAMcfg) SHA256() string {
// loop through and re-use the implementation of `AsSHA256`
}
```

File: pkg/services/ngalert/sender/router.go (hunk 2 above)
Comment (gotjosh) [reply pkg/services/ngalert/sender/router.go:266]: Actually, I changed my mind - Can we scope out this function into a separate pull request and make it a public method that's part of `DataSource`.

It just feels wrong that alerting is now the owner of this extract header logic - it is very likely to get out of the sync with the speed at which Grafana moves.

**Review by gotjosh — COMMENTED** [review]
Wow! Impressive job 👏👏👏👏👏👏👏

Very clean on the copy/paste from Prometheus - I hope we can upstream some of this work by making a good case around it.

Some parts of the `router` implementation can do with a bit of a cleanup; please see my comments.

File: pkg/services/ngalert/sender/router.go (hunk 2 above)
Comment (JohnnyQQQQ) [reply pkg/services/ngalert/sender/router.go]: Done 👍

File: pkg/services/ngalert/sender/router.go (hunk 3 above)
Comment (JohnnyQQQQ) [reply pkg/services/ngalert/sender/router.go]: I changed how this works, the hashes are generated based on the config and then just joined. This is way less confusing.

**Review by gotjosh — APPROVED** [review]
LGTM

Beautiful 👏
