### PR TITLE
Influxdb: Fix missing columns with raw query

### LINKED ISSUE #63842: Grafana 9.4.1 is breaking dashboard
**What happened**:
After upgrading from 9.3.6 to 9.4.1 a Syslog dashboard is broken.
A rollback will fix this issue immediately.

**What you expected to happen**:
Query should work as expected

**How to reproduce it (as minimally and precisely as possible)**:
Reproducible with my uploaded dashboard on 9.4.1

**Environment**:
- Grafana version: 9.4.1
- Data source type & version: InfuxDB 1.8.x
- OS Grafana is installed on: Ubuntu Focal
- User OS & Browser: Safari / Chrome

Grafana 9.3.6:
SCR-20230228-jssi

Grafana 9.4.1:
SCR-20230228-jsxw

Query:
`SELECT "severity_code", "message" FROM "syslog" WHERE ("hostname" =~ /^$hostname$/ AND "appname" =~ /^$appname$/ AND "severity" =~ /^$severity$/ AND "message" =~ /$Query/) AND $timeFilter GROUP BY "hostname", "appname"`

Dashboard export:

```
{
  "__inputs": [
    {
      "name": "DS_SYSLOG-DB",
      "label": "SYSLOG-DB",
      "description": "",
      "type": "datasource",
      "pluginId": "influxdb",
      "pluginName": "InfluxDB"
    }
  ],
  "__elements": {},
  "__requires": [
    {
      "type": "panel",
      "id": "bargauge",
      "name": "Bar gauge",
      "version": ""
    },
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "9.3.6"
    },
    {
      "type": "datasource",
      "id": "influxdb",
      "name": "InfluxDB",
      "version": "1.0.0"
    },
    {
      "type": "panel",
      "id": "piechart",
      "name": "Pie chart",
      "version": ""
    },
    {
      "type": "panel",
      "id": "table",
      "name": "Table",
      "version": ""
    },
    {
      "type": "panel",
      "id": "timeseries",
      "name": "Time series",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "datasource",
          "uid": "grafana"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "description": "Telegraf / InfluxDB / Grafana as syslog receiver",
  "editable": true,
  "fiscalYearStartMonth": 0,
  "gnetId": 12433,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "collapsed": false,
      "datasource": {
        "type": "datasource",
        "uid": "grafana"
      },
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 26,
      "panels": [],
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "grafana"
          },
          "refId": "A"
        }
      ],
      "title": "SYSLOG DATA",
      "type": "row"
    },
    {
      "datasource": {
        "type": "influxdb",
        "uid": "${DS_SYSLOG-DB}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisGridShow": true,
            "axisLabel": "MESSAGES / MIN",
            "axisPlacement": "right",
            "barAlignment": 0,
            "drawStyle": "bars",
            "fillOpacity": 100,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "never",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "decimals": 0,
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "none"
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "Info"
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "rgb(80, 80, 80)",
                  "mode": "fixed"
                }
              },
              {
                "id": "custom.stacking",
                "value": {
                  "group": "A",
                  "mode": "normal"
                }
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "Notice"
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "rgb(182, 182, 182)",
                  "mode": "fixed"
                }
              },
              {
                "id": "custom.stacking",
                "value": {
                  "group": "A",
                  "mode": "normal"
                }
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "Warning"
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "#E0B400",
                  "mode": "fixed"
                }
              },
              {
                "id": "custom.stacking",
                "value": {
                  "group": "A",
                  "mode": "normal"
                }
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "Error"
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "#FF780A",
                  "mode": "fixed"
                }
              },
              {
                "id": "custom.stacking",
                "value": {
                  "group": "A",
                  "mode": "normal"
                }
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "Critical"
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "#E02F44",
                  "mode": "fixed"
                }
              },
              {
                "id": "custom.stacking",
                "value": {
                  "group": "A",
                  "mode": "normal"
                }
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "Alert"
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "#8F3BB8",
                  "mode": "fixed"
                }
              },
              {
                "id": "custom.stacking",
                "value": {
                  "group": "A",
                  "mode": "normal"
                }
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "Emergency"
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "#8F3BB8",
                  "mode": "fixed"
                }
              },
              {
                "id": "custom.stacking",
                "value": {
                  "group": "A",
                  "mode": "normal"
                }
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 7,
        "w": 24,
        "x": 0,
        "y": 1
      },
      "id": 10,
      "interval": "",
      "links": [],
      "options": {
        "legend": {
          "calcs": [
            "last",
            "max",
            "sum"
          ],
          "displayMode": "table",
          "placement": "right",
          "showLegend": true
        },
        "tooltip": {
          "mode": "multi",
          "sort": "none"
        }
      },
      "pluginVersion": "8.0.3",
      "targets": [
        {
          "alias": "Info",
          "datasource": {
            "type": "influxdb",
            "uid": "${DS_SYSLOG-DB}"
          },
          "groupBy": [
            {
              "params": [
                "1m"
              ],
              "type": "time"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "measurement": "syslog",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "A",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "severity_code"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "count"
              }
            ]
          ],
          "tags": [
            {
              "key": "severity",
              "operator": "=",
              "value": "info"
            },
            {
              "condition": "AND",
              "key": "hostname",
              "operator": "=~",
              "value": "/^$hostname$/"
            },
            {
              "condition": "AND",
              "key": "severity",
              "operator": "=~",
              "value": "/^$severity$/"
            },
            {
              "condition": "AND",
              "key": "appname",
              "operator": "=~",
              "value": "/^$appname$/"
            },
            {
              "condition": "AND",
              "key": "message",
              "operator": "=~",
              "value": "/$Query/"
            }
          ]
        },
        {
          "alias": "Notice",
          "datasource": {
            "type": "influxdb",
            "uid": "${DS_SYSLOG-DB}"
          },
          "groupBy": [
            {
              "params": [
                "1m"
              ],
              "type": "time"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "measurement": "syslog",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "B",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "severity_code"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "count"
              }
            ]
          ],
          "tags": [
            {
              "key": "severity",
              "operator": "=",
              "value": "notice"
            },
            {
              "condition": "AND",
              "key": "hostname",
              "operator": "=~",
              "value": "/^$hostname$/"
            },
            {
              "condition": "AND",
              "key": "severity",
              "operator": "=~",
              "value": "/^$severity$/"
            },
            {
              "condition": "AND",
              "key": "appname",
              "operator": "=~",
              "value": "/^$appname$/"
            },
            {
              "condition": "AND",
              "key": "message",
              "operator": "=~",
              "value": "/$Query/"
            }
          ]
        },
        {
          "alias": "Warning",
          "datasource": {
            "type": "influxdb",
            "uid": "${DS_SYSLOG-DB}"
          },
          "groupBy": [
            {
              "params": [
                "1m"
              ],
              "type": "time"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "measurement": "syslog",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "D",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "severity_code"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "count"
              }
            ]
          ],
          "tags": [
            {
              "key": "severity",
              "operator": "=",
              "value": "warning"
            },
            {
              "condition": "AND",
              "key": "hostname",
              "operator": "=~",
              "value": "/^$hostname$/"
            },
            {
              "condition": "AND",
              "key": "severity",
              "operator": "=~",
              "value": "/^$severity$/"
            },
            {
              "condition": "AND",
              "key": "appname",
              "operator": "=~",
              "value": "/^$appname$/"
            },
            {
              "condition": "AND",
              "key": "message",
              "operator": "=~",
              "value": "/$Query/"
            }
          ]
        },
        {
          "alias": "Error",
          "datasource": {
            "type": "influxdb",
            "uid": "${DS_SYSLOG-DB}"
          },
          "groupBy": [
            {
              "params": [
                "1m"
              ],
              "type": "time"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "measurement": "syslog",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "C",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "severity_code"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "count"
              }
            ]
          ],
          "tags": [
            {
              "key": "severity",
              "operator": "=",
              "value": "err"
            },
            {
              "condition": "AND",
              "key": "hostname",
              "operator": "=~",
              "value": "/^$hostname$/"
            },
            {
              "condition": "AND",
              "key": "severity",
              "operator": "=~",
              "value": "/^$severity$/"
            },
            {
              "condition": "AND",
              "key": "appname",
              "operator": "=~",
              "value": "/^$appname$/"
            },
            {
              "condition": "AND",
              "key": "message",
              "operator": "=~",
              "value": "/$Query/"
            }
          ]
        },
        {
          "alias": "Critical",
          "datasource": {
            "type": "influxdb",
            "uid": "${DS_SYSLOG-DB}"
          },
          "groupBy": [
            {
              "params": [
                "1m"
              ],
              "type": "time"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "measurement": "syslog",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "E",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "severity_code"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "count"
              }
            ]
          ],
          "tags": [
            {
              "key": "severity",
              "operator": "=",
              "value": "crit"
            },
            {
              "condition": "AND",
              "key": "hostname",
              "operator": "=~",
              "value": "/^$hostname$/"
            },
            {
              "condition": "AND",
              "key": "severity",
              "operator": "=~",
              "value": "/^$severity$/"
            },
            {
              "condition": "AND",
              "key": "appname",
              "operator": "=~",
              "value": "/^$appname$/"
            },
            {
              "condition": "AND",
              "key": "message",
              "operator": "=~",
              "value": "/$Query/"
            }
          ]
        },
        {
          "alias": "Alert",
          "datasource": {
            "type": "influxdb",
            "uid": "${DS_SYSLOG-DB}"
          },
          "groupBy": [
            {
              "params": [
                "1m"
              ],
              "type": "time"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "measurement": "syslog",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "F",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "severity_code"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "count"
              }
            ]
          ],
          "tags": [
            {
              "key": "severity",
              "operator": "=",
              "value": "alert"
            },
            {
              "condition": "AND",
              "key": "hostname",
              "operator": "=~",
              "value": "/^$hostname$/"
            },
            {
              "condition": "AND",
              "key": "severity",
              "operator": "=~",
              "value": "/^$severity$/"
            },
            {
              "condition": "AND",
              "key": "appname",
              "operator": "=~",
              "value": "/^$appname$/"
            },
            {
              "condition": "AND",
              "key": "message",
              "operator": "=~",
              "value": "/$Query/"
            }
          ]
        },
        {
          "alias": "Emergency",
          "datasource": {
            "type": "influxdb",
            "uid": "${DS_SYSLOG-DB}"
          },
          "groupBy": [
            {
              "params": [
                "1m"
              ],
              "type": "time"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "measurement": "syslog",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "G",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "severity_code"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "count"
              }
            ]
          ],
          "tags": [
            {
              "key": "severity",
              "operator": "=",
              "value": "emerg"
            },
            {
              "condition": "AND",
              "key": "hostname",
              "operator": "=~",
              "value": "/^$hostname$/"
            },
            {
              "condition": "AND",
              "key": "severity",
              "operator": "=~",
              "value": "/^$severity$/"
            },
            {
              "condition": "AND",
              "key": "appname",
              "operator": "=~",
              "value": "/^$appname$/"
            },
            {
              "condition": "AND",
              "key": "message",
              "operator": "=~",
              "value": "/$Query/"
            }
          ]
        }
      ],
      "title": "SYSLOG COUNT",
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "influxdb",
        "uid": "${DS_SYSLOG-DB}"
      },
      "description": "",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "align": "left",
            "displayMode": "auto",
            "filterable": false,
            "inspect": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "dark-purple",
                "value": null
              },
              {
                "color": "dark-red",
                "value": 2
              },
              {
                "color": "dark-orange",
                "value": 3
              },
              {
                "color": "dark-yellow",
                "value": 4
              },
              {
                "color": "rgb(150, 150, 150)",
                "value": 5
              },
              {
                "color": "rgb(51, 51, 51)",
                "value": 6
              },
              {
                "color": "rgb(5, 5, 5)",
                "value": 7
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "severity_code"
            },
            "properties": [
              {
                "id": "mappings",
                "value": [
                  {
                    "options": {
                      "0": {
                        "text": "Emergency"
                      },
                      "1": {
                        "text": "Alert"
                      },
                      "2": {
                        "text": "Critical"
                      },
                      "3": {
                        "text": "Error"
                      },
                      "4": {
                        "text": "Warning"
                      },
                      "5": {
                        "text": "Notice"
                      },
                      "6": {
                        "text": "Info"
                      },
                      "7": {
                        "text": "Debug"
                      }
                    },
                    "type": "value"
                  }
                ]
              },
              {
                "id": "custom.displayMode",
                "value": "color-background"
              },
              {
                "id": "custom.width",
                "value": 119
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "Time"
            },
            "properties": [
              {
                "id": "custom.width",
                "value": 163
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "appname"
            },
            "properties": [
              {
                "id": "custom.width",
                "value": 264
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "hostname"
            },
            "properties": [
              {
                "id": "custom.width",
                "value": 194
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "message"
            },
            "properties": [
              {
                "id": "custom.width",
                "value": 1800
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 17,
        "w": 24,
        "x": 0,
        "y": 8
      },
      "id": 12,
      "options": {
        "footer": {
          "fields": "",
          "reducer": [
            "sum"
          ],
          "show": false
        },
        "showHeader": true,
        "sortBy": [
          {
            "desc": true,
            "displayName": "Time"
          }
        ]
      },
      "pluginVersion": "9.3.6",
      "targets": [
        {
          "datasource": {
            "type": "influxdb",
            "uid": "${DS_SYSLOG-DB}"
          },
          "groupBy": [
            {
              "params": [
                "hostname"
              ],
              "type": "tag"
            },
            {
              "params": [
                "appname"
              ],
              "type": "tag"
            }
          ],
          "measurement": "syslog",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "A",
          "resultFormat": "table",
          "select": [
            [
              {
                "params": [
                  "severity_code"
                ],
                "type": "field"
              }
            ],
            [
              {
                "params": [
                  "message"
                ],
                "type": "field"
              }
            ]
          ],
          "tags": [
            {
              "key": "hostname",
              "operator": "=~",
              "value": "/^$hostname$/"
            },
            {
              "condition": "AND",
              "key": "appname",
              "operator": "=~",
              "value": "/^$appname$/"
            },
            {
              "condition": "AND",
              "key": "severity",
              "operator": "=~",
              "value": "/^$severity$/"
            },
            {
              "condition": "AND",
              "key": "message",
              "operator": "=~",
              "value": "/$Query/"
            }
          ]
        }
      ],
      "title": "SYSLOG MESSAGES",
      "type": "table"
    },
    {
      "collapsed": false,
      "datasource": {
        "type": "datasource",
        "uid": "grafana"
      },
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 25
      },
      "id": 24,
      "panels": [],
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "grafana"
          },
          "refId": "A"
        }
      ],
      "title": "SYSLOG STATS",
      "type": "row"
    },
    {
      "datasource": {
        "type": "influxdb",
        "uid": "${DS_SYSLOG-DB}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            }
          },
          "decimals": 0,
          "mappings": [],
          "unit": "short"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 26
      },
      "id": 18,
      "links": [],
      "maxDataPoints": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "table",
          "placement": "right",
          "showLegend": true,
          "values": [
            "value"
          ]
        },
        "pieType": "pie",
        "reduceOptions": {
          "calcs": [
            "last"
          ],
          "fields": "",
          "values": false
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "7.0.6",
      "targets": [
        {
          "alias": "",
          "datasource": {
            "type": "influxdb",
            "uid": "${DS_SYSLOG-DB}"
          },
          "groupBy": [
            {
              "params": [
                "24h"
              ],
              "type": "time"
            },
            {
              "params": [
                "hostname"
              ],
              "type": "tag"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "measurement": "syslog",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "A",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "message"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "count"
              }
            ]
          ],
          "tags": []
        }
      ],
      "timeFrom": "24h",
      "title": "INGRESS COUNT BY SYSTEM IN 24h",
      "type": "piechart"
    },
    {
      "datasource": {
        "type": "influxdb",
        "uid": "${DS_SYSLOG-DB}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            }
          },
          "decimals": 0,
          "mappings": [],
          "unit": "short"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 12,
        "y": 26
      },
      "id": 20,
      "links": [],
      "maxDataPoints": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "table",
          "placement": "right",
          "showLegend": true,
          "values": [
            "value"
          ]
        },
        "pieType": "pie",
        "reduceOptions": {
          "calcs": [
            "last"
          ],
          "fields": "",
          "values": false
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "7.0.6",
      "targets": [
        {
          "alias": "",
          "datasource": {
            "type": "influxdb",
            "uid": "${DS_SYSLOG-DB}"
          },
          "groupBy": [
            {
              "params": [
                "24h"
              ],
              "type": "time"
            },
            {
              "params": [
                "appname"
              ],
              "type": "tag"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "measurement": "syslog",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "A",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "message"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "count"
              }
            ]
          ],
          "tags": []
        }
      ],
      "timeFrom": "24h",
      "title": "INGRESS COUNT BY APP IN 24h",
      "type": "piechart"
    },
    {
      "datasource": {
        "type": "influxdb",
        "uid": "${DS_SYSLOG-DB}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "continuous-BlPu"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "light-blue"
              }
            ]
          },
          "unit": "Messages"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 34
      },
      "id": 14,
      "links": [],
      "maxDataPoints": 1,
      "options": {
        "displayMode": "basic",
        "minVizHeight": 10,
        "minVizWidth": 0,
        "orientation": "horizontal",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "showUnfilled": true,
        "text": {}
      },
      "pluginVersion": "9.0.2",
      "targets": [
        {
          "alias": "",
          "datasource": {
            "type": "influxdb",
            "uid": "${DS_SYSLOG-DB}"
          },
          "groupBy": [
            {
              "params": [
                "24h"
              ],
              "type": "time"
            },
            {
              "params": [
                "severity"
              ],
              "type": "tag"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "measurement": "syslog",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "A",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "message"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "count"
              }
            ]
          ],
          "tags": []
        }
      ],
      "timeFrom": "24h",
      "title": "INGRESS COUNT BY SEVERITY IN 24h",
      "type": "bargauge"
    },
    {
      "datasource": {
        "type": "influxdb",
        "uid": "${DS_SYSLOG-DB}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "continuous-BlPu"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "light-blue"
              }
            ]
          },
          "unit": "Messages"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 12,
        "y": 34
      },
      "id": 16,
      "links": [],
      "maxDataPoints": 1,
      "options": {
        "displayMode": "basic",
        "minVizHeight": 10,
        "minVizWidth": 0,
        "orientation": "horizontal",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "showUnfilled": true,
        "text": {}
      },
      "pluginVersion": "9.0.2",
      "targets": [
        {
          "alias": "",
          "datasource": {
            "type": "influxdb",
            "uid": "${DS_SYSLOG-DB}"
          },
          "groupBy": [
            {
              "params": [
                "24h"
              ],
              "type": "time"
            },
            {
              "params": [
                "facility"
              ],
              "type": "tag"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "measurement": "syslog",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "A",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "message"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "count"
              }
            ]
          ],
          "tags": []
        }
      ],
      "timeFrom": "24h",
      "title": "INGRESS COUNT BY FACILITY IN 24h",
      "type": "bargauge"
    },
    {
      "alert": {
        "alertRuleTags": {},
        "conditions": [
          {
            "evaluator": {
              "params": [
                2500
              ],
              "type": "gt"
            },
            "operator": {
              "type": "and"
            },
            "query": {
              "params": [
                "A",
                "1m",
                "now"
              ]
            },
            "reducer": {
              "params": [],
              "type": "sum"
            },
            "type": "query"
          }
        ],
        "executionErrorState": "keep_state",
        "for": "10m",
        "frequency": "1m",
        "handler": 1,
        "message": "SYSLOG - INGRESS RATE hits 2500 entries/min for the last 10min!\nSYSLOG Storm, review syslog devices!",
        "name": "SYSLOG - INGRESS RATE",
        "noDataState": "keep_state",
        "notifications": [
          {
            "uid": "34VVPFYGz"
          }
        ]
      },
      "datasource": {
        "type": "influxdb",
        "uid": "${DS_SYSLOG-DB}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "continuous-BlPu",
            "seriesBy": "last"
          },
          "custom": {
            "axisGridShow": true,
            "axisLabel": "INGRESS COUNT",
            "axisPlacement": "right",
            "axisSoftMin": 0,
            "barAlignment": 0,
            "drawStyle": "bars",
            "fillOpacity": 50,
            "gradientMode": "scheme",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "never",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "displayName": "LOG ENTRIES",
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green"
              }
            ]
          },
          "unit": "none"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 24,
        "x": 0,
        "y": 42
      },
      "hideTimeOverride": false,
      "id": 22,
      "options": {
        "legend": {
          "calcs": [
            "lastNotNull",
            "max",
            "sum"
          ],
          "displayMode": "table",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "influxdb",
            "uid": "${DS_SYSLOG-DB}"
          },
          "groupBy": [
            {
              "params": [
                "1m"
              ],
              "type": "time"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "measurement": "syslog",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "A",
          "resultFormat": "table",
          "select": [
            [
              {
                "params": [
                  "message"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "count"
              }
            ]
          ],
          "tags": []
        }
      ],
      "thresholds": [
        {
          "colorMode": "critical",
          "op": "gt",
          "value": 2500,
          "visible": true
        }
      ],
      "timeFrom": "3h",
      "title": "SYSLOG INGRESS RATE",
      "type": "timeseries"
    }
  ],
  "refresh": "5s",
  "schemaVersion": 37,
  "style": "dark",
  "tags": [
    "HOMENET"
  ],
  "templating": {
    "list": [
      {
        "allValue": "",
        "current": {},
        "datasource": {
          "type": "influxdb",
          "uid": "${DS_SYSLOG-DB}"
        },
        "definition": "SHOW TAG VALUES FROM syslog WITH KEY=appname",
        "hide": 0,
        "includeAll": true,
        "label": "Appname",
        "multi": true,
        "name": "appname",
        "options": [],
        "query": "SHOW TAG VALUES FROM syslog WITH KEY=appname",
        "refresh": 2,
        "regex": "",
        "skipUrlSync": false,
        "sort": 5,
        "tagValuesQuery": "",
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      },
      {
        "allValue": "",
        "current": {},
        "datasource": {
          "type": "influxdb",
          "uid": "${DS_SYSLOG-DB}"
        },
        "definition": "SHOW TAG VALUES FROM syslog WITH KEY=hostname",
        "hide": 0,
        "includeAll": true,
        "label": "Hostname",
        "multi": true,
        "name": "hostname",
        "options": [],
        "query": "SHOW TAG VALUES FROM syslog WITH KEY=hostname",
        "refresh": 2,
        "regex": "",
        "skipUrlSync": false,
        "sort": 5,
        "tagValuesQuery": "",
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      },
      {
        "allValue": "",
        "current": {},
        "datasource": {
          "type": "influxdb",
          "uid": "${DS_SYSLOG-DB}"
        },
        "definition": "SHOW TAG VALUES FROM syslog WITH KEY=severity",
        "hide": 0,
        "includeAll": true,
        "label": "Severity",
        "multi": true,
        "name": "severity",
        "options": [],
        "query": "SHOW TAG VALUES FROM syslog WITH KEY=severity",
        "refresh": 2,
        "regex": "",
        "skipUrlSync": false,
        "sort": 5,
        "tagValuesQuery": "",
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      },
      {
        "current": {
          "selected": false,
          "text": "",
          "value": ""
        },
        "description": "Querystring",
        "hide": 0,
        "label": "MessageQuery",
        "name": "Query",
        "options": [
          {
            "selected": true,
            "text": "",
            "value": ""
          }
        ],
        "query": "",
        "skipUrlSync": false,
        "type": "textbox"
      }
    ]
  },
  "time": {
    "from": "now-3h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      " 10s",
      " 30s",
      " 1m",
      " 5m"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "",
  "title": "SYSLOG MONITORING",
  "uid": "TIReHqRgZ",
  "version": 61,
  "weekStart": ""
}
```

### LINKED ISSUE #63923: Previously exsisting custum InfluxDB queries don't show selected columns after upgrade 9.3.8 -> 9.4.1
**What happened**:

When upgrading from 9.3.8 to 9.4.1 previously exsisting custum InfluxDB queries don't show selected columns (mean, last, ..).
When switching to query editor mode and back to raw query mode, then the table shows the column.

If creating new query the issue is not present (because we go through query editor mode first).

P.S. Once the column is shown, it shows "mean" (because it was selected in query editor) even tho the data is actually "last" as written in custom query.

Panel: Table
Format as: Table

Additional info: this issue was not present when upgrading previous versions, for instance upgrading 9.3.6 -> 9.3.8.

GIF:
Grafana

### PR DESCRIPTION
**Pull request by bohandley**
Fixes: https://github.com/grafana/support-escalations/issues/5134
Fixes: https://github.com/grafana/grafana/issues/63842
Fixes: https://github.com/grafana/grafana/issues/63923
Fixes: https://github.com/grafana/support-escalations/issues/5242

What is this fix?
This adds selected fields as column names in the table response for Influxdb.

Why?
Say we have a query:
`SELECT "usage_guest_nice", "usage_idle" FROM "cpu" WHERE $timeFilter`
When the selected object is not part of the query model, which happens when a user performs a rawQuery, the selected columns are not added to the table response. In this example, `usage_guest_nice` and `usage_idle` would not be added as columns to the table response and any values wouldn't be shown either. 

Without columns in table response
Screen Shot 2023-03-02 at 12 36 40 PM

With columns in table response
Screen Shot 2023-03-02 at 12 36 19 PM

So, this fix checks that the columns returned from the query are in the original rawQuery, then adds the field names as column names.

### CODE REVIEW

File: public/app/plugins/datasource/influxdb/response_parser.ts [hunk 1]
```diff
@@ -248,3 +262,30 @@ function incrementName(name: string, nameIncremenet: string, params: string[], i
 function addUnique(s: Set<string>, value: string | number) {
   s.add(value.toString());
 }
+
+function rawQuerySelectedFieldsInDataframe(query: string | undefined, dfs: DataFrame[]) {
+  const names: Array<string | undefined> = dfs.map((df: DataFrame) => df.name);
+
+  const colsInRawQuery: boolean = names.every((name: string | undefined) => {
```
Comment (itsmylife) [inline public/app/plugins/datasource/influxdb/response_parser.ts:269]:
```suggestion
  const colsInRawQuery = names.every((name: string | undefined) => {
```

File: public/app/plugins/datasource/influxdb/response_parser.ts [hunk 2]
```diff
@@ -248,3 +262,30 @@ function incrementName(name: string, nameIncremenet: string, params: string[], i
...
+      // table name and field, i.e. cpu.usage_guest_nice becomes ['cpu', 'usage_guest_nice']
+      const nameParts: string[] = name.split('.');
+
+      return nameParts.every((np) => query.toLowerCase().includes(np.toLowerCase()));
+    }
+
+    return false;
+  });
+
+  const queryChecks: string[] = ['*', 'SHOW'];
```
Comment (itsmylife) [inline public/app/plugins/datasource/influxdb/response_parser.ts:280]:
```suggestion
  const queryChecks = ['*', 'SHOW'];
```

File: public/app/plugins/datasource/influxdb/response_parser.ts [hunk 3]
```diff
@@ -248,3 +262,30 @@ function incrementName(name: string, nameIncremenet: string, params: string[], i
...
   s.add(value.toString());
 }
+
+function rawQuerySelectedFieldsInDataframe(query: string | undefined, dfs: DataFrame[]) {
+  const names: Array<string | undefined> = dfs.map((df: DataFrame) => df.name);
+
+  const colsInRawQuery: boolean = names.every((name: string | undefined) => {
+    if (name && query) {
+      // table name and field, i.e. cpu.usage_guest_nice becomes ['cpu', 'usage_guest_nice']
+      const nameParts: string[] = name.split('.');
```
Comment (itsmylife) [inline public/app/plugins/datasource/influxdb/response_parser.ts:272]:
```suggestion
      const nameParts = name.split('.');
```

**Comment by bohandley** [comment]
@pokerazor could you give us the context for writing the queries? What version of Influx are you on? Could you give us an example of a `SHOW` query you are doing? What do you expect the response to look like? I believe this will handle your case but I just want to be sure. Thank you!

**Review by itsmylife — APPROVED** [review]
LGTM 
I left some small suggestions

**Comment by pokerazor** [comment]
@bohandley we're currently still on InfluxDB 1.8.10-1 Ubuntu 18.04.6 LTS and there's actually a lot of panels and queries using the "raw" mode. Often times using, as said before, the `*`, some explorative dashboards also `SHOW DATABASES`, `SHOW MEASUREMENTS ON "$database"`, `SHOW TAG KEYS ON "$database" FROM "$measurement", `SHOW TAG VALUES ON "$database" FROM "$measurement" WITH KEY = "$tag_key"`, `SHOW FIELD KEYS ON "$database" FROM "$measurement"`, `SHOW SERIES ON $database`, `SHOW RETENTION POLICIES ON $database`, all of those showing either no column or only a `mean` column that wasn't there before. 

`SHOW QUERIES` though shows `InfluxDB Error: Internal server error.`

And `/var/log/grafana/grafana.log` at that time gives 
`level=error msg="Request error" error="interface conversion: interface {} is json.Number, not string" stack="/usr/local/go/src/runtime/iface.go:262 (0x414e29)\n/drone/src/pkg/tsdb/influxdb/response_parser.go:77 (0x346fea4)\n/drone/src/pkg/tsdb/influxdb/response_parser.go:40 (0x346f4be)\n/drone/src/pkg/tsdb/influxdb/influxdb.go:145 (0x3469648)\n/drone/src/pkg/plugins/backendplugin/coreplugin/core_plugin.go:85 (0x3511190)\n/drone/src/pkg/plugins/plugins.go:285 (0x12114f4)\n/drone/src/pkg/plugins/manager/client/client.go:48 (0x3535f11)\n/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:42 (0x353491e)\n/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:103 (0x35358b5)\n/drone/src/pkg/plugins/manager/client/client.go:44 (0x3535890)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/httpclient_middleware.go:71 (0x353ae3e)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/cookies_middleware.go:90 (0x353a07b)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/oauthtoken_middleware.go:100 (0x353b9fc)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/clear_auth_headers_middleware.go:48 (0x353960a)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/tracing_header_middleware.go:53 (0x353c1ca)\n/drone/src/pkg/plugins/manager/client/decorator.go:35 (0x35373a8)\n/drone/src/pkg/services/query/query.go:236 (0x1f8ca41)\n/drone/src/pkg/services/query/query.go:84 (0x1f8add1)\n/drone/src/pkg/api/metrics.go:55 (0x2da6a0b)\n/drone/src/pkg/api/routing/routing.go:17 (0x190ca21)\n/drone/src/pkg/api/response/web_hack.go:40 (0x11da175)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:134 (0x11ced54)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/services/contexthandler/contexthandler.go:221 (0x18f9f39)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/render.go:44 (0x11cf915)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/macaron.go:140 (0x11cedfb)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/middleware/csrf/csrf.go:64 (0x20a87a5)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/middleware/recovery.go:171 (0x19073a1)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/middleware/logger.go:42 (0x1904b01)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/middleware/request_metrics.go:59 (0x19081c9)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/middleware/request_tracing.go:88 (0x190991a)\n/usr/local/go/src/net/http/server.go:2109 (0x7ae40e)\n/drone/src/pkg/web/context.go:49 (0x11cd6bd)\n/drone/src/pkg/web/router.go:155 (0x11d0e8d)\n/drone/src/pkg/web/router.go:211 (0x11d1af5)\n/drone/src/pkg/web/macaron.go:166 (0x11cf270)\n/usr/local/go/src/net/http/server.go:2947 (0x7b180b)\n/usr/local/go/src/net/http/server.go:1991 (0x7acee6)\n/usr/local/go/src/runtime/asm_amd64.s:1594 (0x4783c0)\n` (which seems to maybe be a additional problem…?)

I currently can't roll back easily to 9.3.8 where they all worked fine to show an "expected" response.

**Comment by pokerazor** [comment]
@bohandley when is this going to get released, and will it also cover the error posted above?

For the time being, I now downgraded back to 9.3.8 via `sudo apt install grafana=9.3.8 --only-upgrade --ignore-hold` and the dashboards work again.
Also looking at https://github.com/grafana/grafana/issues/63842#issuecomment-1454329146 there still seem to be problems?

**Comment by bohandley** [comment]
@pokerazor This will be released in v9.4.4, thank you for the details. It will handle parsing the dataframe response for any raw query includes the `SHOW` queries you mentioned. I think v9.4.4 should be released next week but let me confirm that.

**Comment by zekena2** [comment]
It didn't fix it for us, We build a custom image from branch v9.4.x and deployed it and dashboards are still not showing and some dashboards are erroring with an internal error, checking logs of grafana we saw this


"error": "interface conversion: interface {} is nil, not string"
 "stack": "/usr/local/go/src/runtime/iface.go:262 (0x414149)\n/tmp/grafana/pkg/tsdb/influxdb/response_parser.go:103 (0x349ec84)\n/tmp/grafana/pkg/tsdb/influxdb/response_parser.go:40 (0x349cdde)\n/tmp/grafana/pkg/tsdb/influxdb/influxdb.go:145 (0x349741a)\n/tmp/grafana/pkg/plugins/backendplugin/coreplugin/core_plugin.go:85 (0x3538910)\n/tmp/grafana/pkg/plugins/plugins.go:285 (0x120d974)\n/tmp/grafana/pkg/plugins/manager/client/client.go:48 (0x355cd71)\n/tmp/grafana/pkg/plugins/backendplugin/instrumentation/instrumentation.go:42 (0x355b79e)\n/tmp/grafana/pkg/plugins/backendplugin/instrumentation/instrumentation.go:103 (0x355c715)\n/tmp/grafana/pkg/plugins/manager/client/client.go:44 (0x355c6f0)\n/tmp/grafana/pkg/services/pluginsintegration/clientmiddleware/httpclient_middleware.go:71 (0x3561bde)\n/tmp/grafana/pkg/services/pluginsintegration/clientmiddleware/cookies_middleware.go:90 (0x3560e1b)\n/tmp/grafana/pkg/services/pluginsintegration/clientmiddleware/oauthtoken_middleware.go:100 (0x356279c)\n/tmp/grafana/pkg/services/pluginsintegration/clientmiddleware/clear_auth_headers_middleware.go:48 (0x35603aa)\n/tmp/grafana/pkg/services/pluginsintegration/clientmiddleware/tracing_header_middleware.go:53 (0x3562f6a)\n/tmp/grafana/pkg/plugins/manager/client/decorator.go:35 (0x355e1a8)\n/tmp/grafana/pkg/services/query/query.go:236 (0x1f726b5)\n/tmp/grafana/pkg/services/query/query.go:84 (0x1f70a31)\n/tmp/grafana/pkg/api/metrics.go:55 (0x2dfca2b)\n/tmp/grafana/pkg/api/routing/routing.go:17 (0x19089a1)\n/tmp/grafana/pkg/api/response/web_hack.go:40 (0x11d8075)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:134 (0x11cbf74)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/services/contexthandler/contexthandler.go:224 (0x18f5c36)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/render.go:44 (0x11ccb55)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/macaron.go:140 (0x11cc01b)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/middleware/csrf/csrf.go:64 (0x208d825)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/middleware/recovery.go:171 (0x1902d81)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/middleware/gziper.go:75 (0x1906352)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/middleware/logger.go:42 (0x19004d0)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/middleware/request_metrics.go:59 (0x1903b89)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/middleware/request_tracing.go:88 (0x19054ba)\n/usr/local/go/src/net/http/server.go:2122 (0x7be74e)\n/tmp/grafana/pkg/web/context.go:49 (0x11ca8bd)\n/tmp/grafana/pkg/web/router.go:155 (0x11ce109)\n/tmp/grafana/pkg/web/router.go:211 (0x11cec75)\n/tmp/grafana/pkg/web/macaron.go:166 (0x11cc490)\n/usr/local/go/src/net/http/server.go:2936 (0x7c1895)\n/usr/local/go/src/net/http/server.go:1995 (0x7bd271)\n/usr/local/go/src/runtime/asm_amd64.s:1598 (0x478b80)\n",

**Comment by zekena2** [comment]
It's two problems actually one is the crash with error above but another was supposed to be fixed by this PR but it didn't work fully.

Adding a group by to this query breaks the dashboard which is why my dashboards didn't get fixed.

`SELECT "usage_guest_nice", "usage_idle" FROM "cpu" WHERE $timeFilter GROUP BY "host"`

**Comment by bohandley** [comment]
Hi @zekena2, thank you for the note! I was able to successfully group by host with this fix. This should be rolled out in v9.4.5, and it is currently in main. Are you still experiencing issues?
Screenshot 2023-03-15 at 11 14 22 AM

**Comment by zekena2** [comment]
The image you uploaded shows the bug, I should get usage_nice as well in the same table but it doesn't show that it only shows the host. 

It shows like this in grafana 9.3.2 which is what I'd expect it.
image

**Comment by bohandley** [comment]
@zekena2 you are correct! I found the bug. We are not displaying tables with labels correctly. I will look further into this for a fix. Thank you!
