### PR TITLE
A11y: Add announcements for toggle buttons

### LINKED ISSUE #117827: A11y: Toggle buttons (Bookmark, Favorite Star) do not announce pressed/unpressed state
## Description

The "Bookmark" button and similar toggle buttons do not announce their pressed or unpressed state to screen readers when toggled. Screen reader users cannot determine whether the button is currently active or inactive.

**Affected areas:**
- "Bookmark" button in the navigation dialog
- "Favorite Star" button
- Toggle buttons below graphs (e.g., switching between `cpu_steal_pct` and `cpu_wait_pct`)

## Steps to reproduce

1. Open Grafana in Chrome on Windows
2. Enable JAWS screen reader
3. Navigate to the navigation dialog containing the "Bookmark" button
4. Use Tab to reach the "Bookmark" button
5. Listen to the screen reader announcement — note it does not announce the current state
6. Press Enter or Space to toggle the button's state
7. Observe that the screen reader does not announce the updated state

## Actual behavior

The "Bookmark" button does not provide any announcement for its state (pressed or unpressed) when focused or toggled.

## Expected behavior

The button should dynamically announce its state (e.g., "pressed" or "not pressed") to screen readers whenever the state changes.

## Suggested fix

Add the `aria-pressed` attribute to toggle buttons and dynamically update its value to `true` or `false` based on the button's current state.

```html
<button aria-label="Add to Bookmarks" aria-pressed="false" ...>
```

## WCAG criteria

- **4.1.2 Name, Role, Value** (Level A)

## Possible duplicates in grafana/grafana

- [#87801](https://github.com/grafana/grafana/issues/87801) — Incorrect name & role is defined for 'Formatted data' & 'Download for excel' toggle buttons (closed; same pattern of toggle buttons missing proper state/role)

## Issue reference

Reference issue 03

### PR DESCRIPTION
**Pull request by L-M-K-B**
**What is this feature?**
Adding aria props to different toggle buttons:
- `Star button` in toolbar: aria-pressed to announce whether a dashboard is starred
- `ExtensionToolbarItemButton`: aria-label to announce whether an extension for instance Assistant is open
- `Bookmark button` in MegaMenu: aria-pressed to announce whether a page is book marked, tooltip to provide button purpose
- `VizLegendListItem button` under a graph: aria-label to announce whether selected graph or all graphs are displayed
- `VizLegendSeriesIcon button` under a graph: aria-label to announce whether the colour picker is open

**Why do we need this feature? / Who is this feature for?**
Improve UX for screenreader users

**Which issue(s) does this PR fix?**:
Fixes #117827

**Special notes for your reviewer:**
For checking the changes in this PR feel free to use the ephemeral instance created below ⬇️

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/core/components/AppChrome/MegaMenu/MegaMenuItemText.tsx [hunk 1]
```diff
@@ -53,10 +53,16 @@ export function MegaMenuItemText({ children, isActive, onClick, target, url, onP
...
             isPinned
-              ? t('navigation.item.remove-bookmark', 'Remove {{itemName}} from Bookmarks', { itemName })
-              : t('navigation.item.add-bookmark', 'Add {{itemName}} to Bookmarks', { itemName })
+              ? t('navigation.item.remove-bookmark.aria', 'Remove {{itemName}} from Bookmarks', { itemName })
+              : t('navigation.item.add-bookmark.aria', 'Add {{itemName}} to Bookmarks', { itemName })
+          }
+          tooltip={
+            isPinned
+              ? t('navigation.item.remove-bookmark.tooltip', 'Remove from Bookmarks')
+              : t('navigation.item.add-bookmark.tooltip', 'Add to Bookmarks')
```
Comment (ywzheng1) [inline public/app/core/components/AppChrome/MegaMenu/MegaMenuItemText.tsx]: in `IconButton` we overridden `aria-label` if tooltip is provided ([code here](https://github.com/grafana/grafana/blob/63c5d8cb8f1c5432c7ed35569785f669d5b3bda8/packages/grafana-ui/src/components/IconButton/IconButton.tsx#L73-L80)), so the item specific label may not be what screen readers get?

File: public/app/core/components/AppChrome/MegaMenu/MegaMenuItemText.tsx [hunk 2]
```diff
@@ -53,10 +53,16 @@ export function MegaMenuItemText({ children, isActive, onClick, target, url, onP
           className={'pin-icon'}
           iconType={isPinned ? 'solid' : 'default'}
           onClick={() => onPin(url)}
+          aria-pressed={isPinned}
           aria-label={
             isPinned
-              ? t('navigation.item.remove-bookmark', 'Remove {{itemName}} from Bookmarks', { itemName })
-              : t('navigation.item.add-bookmark', 'Add {{itemName}} to Bookmarks', { itemName })
+              ? t('navigation.item.remove-bookmark.aria', 'Remove {{itemName}} from Bookmarks', { itemName })
+              : t('navigation.item.add-bookmark.aria', 'Add {{itemName}} to Bookmarks', { itemName })
```
Comment (ywzheng1) [inline public/app/core/components/AppChrome/MegaMenu/MegaMenuItemText.tsx]: Nice improvement adding aria-pressed for toggle state. 

One small a11y nuance: per the WAI-ARIA APG [Button pattern](https://www.w3.org/WAI/ARIA/apg/patterns/button/), toggle buttons should keep a stable accessible name when state changes.

Could we keep the label constant (e.g., Bookmark {{itemName}}) and rely on aria-pressed (true/false) to announce pressed/not pressed, instead of switching between add/remove labels?

File: packages/grafana-ui/src/components/VizLegend/VizLegendSeriesIcon.tsx [hunk 3]
```diff
@@ -41,6 +42,11 @@ export const VizLegendSeriesIcon = memo(({ seriesName, color, gradient, readonly
             <SeriesIcon
               tabIndex={0}
               role="button"
+              aria-label={
+                isOpen
+                  ? t('grafana-ui.viz-legend.color-picker-open', 'Color picker open')
+                  : t('grafana-ui.viz-legend.color-picker-closed', 'Color picker closed')
+              }
```
Comment (ywzheng1) [inline packages/grafana-ui/src/components/VizLegend/VizLegendSeriesIcon.tsx]: Similar a11y nuance here: could we keep aria-label stable (e.g. “Edit color for {{seriesName}}”) and expose open/closed via aria-expanded (and possibly aria-haspopup) instead of changing the label text? This follows APG guidance to avoid stateful accessible names where ARIA state is available.

File: public/app/core/components/AppChrome/MegaMenu/MegaMenuItemText.tsx (hunk 1 above)
Comment (L-M-K-B) [reply public/app/core/components/AppChrome/MegaMenu/MegaMenuItemText.tsx]: True, I didn't think of this 🤦‍♀️. Removed the aria-label and changed the tooltip.

File: public/app/core/components/AppChrome/MegaMenu/MegaMenuItemText.tsx (hunk 2 above)
Comment (L-M-K-B) [reply public/app/core/components/AppChrome/MegaMenu/MegaMenuItemText.tsx]: As I removed the aria-label (see above) I changed it in the tooltip.

**Review by ywzheng1 — COMMENTED** [review]
LGTM, just failing tests

File: packages/grafana-ui/src/components/VizLegend/VizLegendList.tsx [hunk 4]
```diff
@@ -29,6 +29,9 @@ export const VizLegendList = <T extends unknown>({
 }: Props<T>) => {
   const styles = useStyles2(getStyles);
 
+  const selectedCount = useMemo(() => items.filter((item) => !item.disabled).length, [items]);
+  const allItemsSelected = items.length === selectedCount;
```
Comment (fastfrwrd) [inline packages/grafana-ui/src/components/VizLegend/VizLegendList.tsx]: could this be


```suggestion
  const allItemsSelected = useMemo(() => !items.some((item) => item.disabled);
```

The legend can potentially have a ton of items (10,000s in the worst cases), so we need to be conscious of how we loop over all the items. `Array.prototype.some` would stop looping when it found anything disabled, and it also doesn't create a copy of the array that we throw away like `Array.prototype.filter`.

Comment (L-M-K-B) [reply packages/grafana-ui/src/components/VizLegend/VizLegendList.tsx]: Absolutely, just changed it.

**Review by Clarity-89 — APPROVED** [review]

**Review by fastfrwrd — APPROVED** [review]

**Review by ywzheng1 — APPROVED** [review]
