### PR TITLE
NodeGraph: Fix error when clicking link in a context menu

### LINKED ISSUE #34815: NodeGraph: Links from context menu do not work
https://user-images.githubusercontent.com/13729989/117646423-06a5d080-b18c-11eb-87f4-7593122215f5.mp4

In x-ray version 1.3.3 and Grafana v7.5.0-pre (bdc0d9e862)

### PR DESCRIPTION
**Pull request by aocenas**
Fixes: https://github.com/grafana/grafana/issues/34815

There we 2 issues with the links:
1. At some point interpolation code for links requires field of a dataFrame to have .display property. This is added with applyFieldOverrides which isn't called in Explore cause in general this isn't needed. This adds a call for it with empty overrides which just adds the display property.
2. The links in context menu were not wrapped in code that checked whether onClick exists and preventDefault in that case. This also created some weird interactions with `interceptLinkClicks` handler.

### CODE REVIEW

File: packages/grafana-ui/src/components/Menu/MenuItem.tsx [hunk 1]
```diff
@@ -43,7 +43,16 @@ export const MenuItem: React.FC<MenuItemProps> = React.memo(
           href={url ? url : undefined}
           target={target}
           className={styles.link}
-          onClick={onClick}
+          onClick={
+            onClick
+              ? (event) => {
+                  if (!(event.ctrlKey || event.metaKey || event.shiftKey) && onClick) {
```
Comment (aocenas) [inline packages/grafana-ui/src/components/Menu/MenuItem.tsx:49]: @dprokop I wonder if it would make sense to have a `<Link>` component or something for this? I think this is 3rd time I am adding this somewhere.

**Review by zoltanbedi — APPROVED** [review]
LGTM 🍤
