### PR TITLE
OptionsPicker: Use fuzzy search and improve ranking of matches

### LINKED ISSUE #70629: Dashboard variable search should show exact match above alphabetical/numerical matches
**Steps to reproduce**:
Create dashboard with many dashboard variables. One simple set would be (A, AA, AB, AC, BC, C, CD)
Go to and dashboard and type C into variable search.

**Actual Result**:
The results show up in alphabetical order: AC, BC, C, CD. Pressing enter selects AC.

**Expected Result**
C should be shown first, then AC, BC, CD. Pressing enter should select C. This is not a big problem for smaller sample sets, but in a sample set with many entries, it becomes very difficult to find C buried within the huge list of partial matches.

**Relevant WCAG Criteria:**
Not sure which one would fit, but this would help grafana keyboard navigation.

**Environment**:
- Grafana version: 9 (but probably all)
- Data source type & version: Any
- User OS & Browser: Any

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes #70629

this improves the filtering experience of template variables by allowing single-char typos and ranking exact and prefix matches higher than other substring matches. the previous strategy simply returned filtered results in original order, which is not great, especially with large filtered result lists where the exact "C" match below could be result 100 and not visible without a lot of scrolling.

<details><summary>ufuzzy-tpl-vars.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 893,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "grafana-testdata-datasource",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "grafana-testdata-datasource",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "random_walk",
          "seriesCount": 1
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "refresh": "",
  "schemaVersion": 39,
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": false,
          "text": "A",
          "value": "A"
        },
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "query0",
        "options": [
          {
            "selected": true,
            "text": "A",
            "value": "A"
          },
          {
            "selected": false,
            "text": "AA",
            "value": "AA"
          },
          {
            "selected": false,
            "text": "AB",
            "value": "AB"
          },
          {
            "selected": false,
            "text": "AC",
            "value": "AC"
          },
          {
            "selected": false,
            "text": "BC",
            "value": "BC"
          },
          {
            "selected": false,
            "text": "C",
            "value": "C"
          },
          {
            "selected": false,
            "text": "CD",
            "value": "CD"
          }
        ],
        "query": "A, AA, AB, AC, BC, C, CD",
        "skipUrlSync": false,
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "ufuzzy-tpl-vars",
  "uid": "bfaf9476-1a11-48cb-b63e-81aa49a28dfe",
  "version": 2,
  "weekStart": ""
}
```
</details>

before:

https://github.com/grafana/grafana/assets/43234/a86d73d2-57ea-45d9-850e-78524dc82be8

after:

https://github.com/grafana/grafana/assets/43234/20029db1-1c9d-4b03-8bea-9b2d3276b47b

---

**NOTE:** this does _not_ currently modify the behavior of [adhoc variables picker](https://github.com/grafana/grafana/tree/main/public/app/features/variables/adhoc/picker), which has much different internals and UI:

image

### CODE REVIEW

File: public/app/features/variables/pickers/OptionsPicker/reducer.ts [hunk 1]
```diff
@@ -237,14 +246,28 @@ const optionsPickerSlice = createSlice({
       return state;
     },
     updateOptionsAndFilter: (state, action: PayloadAction<VariableOption[]>): OptionsPickerState => {
-      const searchQuery = trimStart((state.queryValue ?? '').toLowerCase());
+      const needle = state.queryValue;
+
+      // with current API, not seeing a way to cache this on state using action.payload's uniqueness
+      // since it's recreated and includes selected state on each item :(
+      const haystack = action.payload.map(({ text }) => (Array.isArray(text) ? text.toString() : text));
```
Comment (leeoniya) [inline public/app/features/variables/pickers/OptionsPicker/reducer.ts:253]: any ideas where we can cache this?

File: public/app/features/variables/pickers/OptionsPicker/reducer.test.ts [hunk 2]
```diff
@@ -761,12 +761,19 @@ describe('optionsPickerReducer', () => {
         queryValue: searchQuery,
       });
 
+      const expectedFuzzy = [
+        11256, 10256, 11056, 11156, 11206, 11216, 11226, 11236, 11246, 1125, 11250, 11251, 11252, 11253, 11254, 11255,
+        11257, 11258, 11259, 1126, 11260, 11261, 11262, 11263, 11264, 11265, 11266, 11267, 11268, 11269, 11276, 11286,
+        11296, 11356, 11456, 11526, 11556, 1156, 11560, 11561, 11562, 11563, 11564, 11565, 11566, 11567, 11568, 11569,
+        11656, 11756, 11856, 11956, 12156, 12256, 1256, 11125, 11126,
+      ].map((index) => ({ text: `option:${index}`, value: `option:${index}`, selected: false }));
+
```
Comment (leeoniya) [inline public/app/features/variables/pickers/OptionsPicker/reducer.test.ts:770]: i'm improving this upstream in https://github.com/leeoniya/uFuzzy/issues/50, will update this PR with a version bump once ready.

File: public/app/features/explore/Logs/utils/uFuzzy.ts [hunk 3]
```diff
@@ -10,7 +10,7 @@ const uf = new uFuzzy({
 });
 
 export function fuzzySearch(haystack: string[], query: string, dispatcher: (data: string[][]) => void) {
-  const [idxs, info, order] = uf.search(haystack, query, false, 1e5);
+  const [idxs, info, order] = uf.search(haystack, query, 0, 1e5);
```
Comment (leeoniya) [inline public/app/features/explore/Logs/utils/uFuzzy.ts:13]: @gtk-grafana do you actually need the 1e5 ranking limit here? the default is 1e3 and it's probably not a good idea to go higher than 1e4. there's not a huge amount of value to ranking, sorting, and highlighting 100k or even 10k results, but it _is_ slower.

File: public/app/plugins/datasource/prometheus/querybuilder/components/metrics-modal/uFuzzy.ts [hunk 4]
```diff
@@ -10,7 +10,7 @@ const uf = new uFuzzy({
 });
 
 export function fuzzySearch(haystack: string[], query: string, dispatcher: (data: string[][]) => void) {
-  const [idxs, info, order] = uf.search(haystack, query, false, 1e5);
+  const [idxs, info, order] = uf.search(haystack, query, 0, 1e5);
```
Comment (leeoniya) [inline public/app/plugins/datasource/prometheus/querybuilder/components/metrics-modal/uFuzzy.ts:13]: @bohandley same question about 1e5 here as above.

**Review by axelavargas — COMMENTED** [review]
This is a great improvement, @leeoniya 😍 ,  I gave it a good test (values with spaces and other cases we tend to have and they worked as expected). The code also looks great to me 🥇  

However, there is one bit we need to keep in mind, we are currently migrating Dashboards to Scenes. I believe that modifications like this will need to be implemented in Scenes as well (I took a quick look and we will need to add the package and implement something similar to what you've done here - I don't have the full context to know which file we'll need to modify).

cc @torkelo @dprokop

**Comment by leeoniya** [comment]
> However, there is one bit we need to keep in mind, we are currently migrating Dashboards to Scenes. I believe that modifications like this will need to be implemented in Scenes as well

if Scenes uses `OptionsPicker` then it should get these improvements automatically, otherwise it can be added in a new PR, same as the Adhoc filter and probably a bunch of other places we do frontend search. i imagine this isn't a blocker for landing this though?

File: public/app/features/explore/Logs/utils/uFuzzy.ts (hunk 3 above)
Comment (gtk-grafana) [reply public/app/features/explore/Logs/utils/uFuzzy.ts:13]: No, I do not. These settings confused me so I used the same option I knew was already in use in the metrics explorer. I'll remove

**Comment by dprokop** [comment]
@leeoniya @axelavargas - Scenes do not filter values themselves, it's handled by the Select component internals. 

Looking at the changes in this PR it's not gonna affect Scenes. But landing this means we need to figure out how to in handle fuzzy search in Select.

**Comment by leeoniya** [comment]
> But landing this means we need to figure out how to handle fuzzy search in Select directly.

should i work on this as part of this pr? or prior to merging this pr?

**Comment by axelavargas** [comment]
Thanks for the clarification @dprokop 🙌🏾 

> > But landing this means we need to figure out how to handle fuzzy search in Select directly.
> 
> should i work on this as part of this pr? or prior to merging this pr?

@leeoniya  , you can do it after merging this pr 😄 ,  from our side we just want to make sure that the behavior is consistent in both places, we will be testing our migration work the first days of January [Milestone 1 😄 - Rendering a Dashboard using scenes for viewer roles](https://github.com/grafana/grafana/issues/73993)

**Review by axelavargas — APPROVED** [review]
🥳 🥇
