### PR TITLE
Variables: Do not reset description on variable type change

### LINKED ISSUE #31917: Dashboard Variable Description Text is deleted when changing Type
**What happened**:

I added a new dashboard templating variable, and set `Name`, `Label` und `Description`.

Then I changed its `Type` from `Query` (Default) to `Custom`,
-> The description text has been deleted ❌ 

The description text will be discarded on any type change (See gif)

**What you expected to happen**:

The description text should be preserved when changing the variable `Type`, since all Types support the description

**How to reproduce it (as minimally and precisely as possible)**:

Reproducible here: https://play.grafana.org/d/000000010/annotations?editview=templating 

gGVA7sk8XO

**Environment**:
- Grafana version: `Grafana v7.4.3 (010f20c1c8)` and `Grafana v7.5.0-beta1 (6b83895315)`
- Data source type & version: -
- OS Grafana is installed on: https://play.grafana.org
- User OS & Browser: Windows 10, Firefox 86.0

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
Fixes the issue where variable description was reset on variable type change, when creating/editing a variable.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/31917

### CODE REVIEW

File: public/test/core/redux/reducerTester.ts [hunk 1]
```diff
@@ -18,6 +18,7 @@ export interface When<State> {
 export interface Then<State> {
   thenStateShouldEqual: (state: State) => When<State>;
   thenStatePredicateShouldEqual: (predicate: (resultingState: State) => boolean) => When<State>;
+  whenActionIsDispatched: (action: PayloadAction<any> | Action<any>) => Then<State>;
```
Comment (Clarity-89) [inline public/test/core/redux/reducerTester.ts:21]: Added this to this type so it's possible to chain multiple actions.

Comment (hugohaggmark) [reply public/test/core/redux/reducerTester.ts:21]: Excellent addition, but you're not using it, right? In that case I would leave it as is.

**Review by hugohaggmark — APPROVED** [review]
Looks great and works as expected 🎉 !

File: public/test/core/redux/reducerTester.ts (hunk 1 above)
Comment (Clarity-89) [reply public/test/core/redux/reducerTester.ts:21]: It's used in the test. `whenActionIsDispatched` returns `Then`, which doesnt have `whenActionIsDispatched` method, so if I want to call a few `whenActionIsDispatched` one on top another, I'll get a type error.

**Review by mckn — APPROVED** [review]
LGTM!

File: public/test/core/redux/reducerTester.ts (hunk 1 above)
Comment (hugohaggmark) [reply public/test/core/redux/reducerTester.ts:21]: Of course 🙈 , my bad
