### PR TITLE
Alerting: Fix silences preview

### LINKED ISSUE #52676: Alerting: Create silence preview wrongly evaluates some conditions
I found two issues with _Create silence form_:

1. When I go to _Create silence_ screen and click on _Add matcher_ the preview of matching alert instances disappears, making it difficult to change them because I need to remember exactly what I wanted to input (UX issue).

2. When _Label_ contains label name that doesn't exist within current alert instances, _Condition_ is set to "!=", and _Value is set, all alerts disappear from preview even though this condition is valid - silence is saved successfully and alert is silenced (bug)

My alert:
obraz

Valid condition, preview is hiden even though matchers should match my alarm instance:
obraz

After saving silence is properly applied:
obraz

Grafana 9.0.4

### PR DESCRIPTION
**Pull request by konrad147**
This PR changes the source of alert instances we use to display silences preview.

**What is this feature?**
Previously we used Prometheus API to fetch alert instances, which is not correct because we cannot be sure that alerts from a Prometheus data source will be delivered to a particular Alertmanager

The PR introduces a change to fetch alert instances from the Alertmanager `api/v2/alerts` endpoint, which returns all alerts currently being processed by Alertmanager. 
Silences are part of Alertmanager configuration, so fetching alert instances from AM endpoint makes the preview 100% accurate

**Why do we need this feature?**
To fix the inaccurate preview of affected alerts on the silences page

**Which issue(s) does this PR fix?**:
Fixes #52676 

**Special notes for your reviewer:**
The code uses the `filter` parameter of `api/v2/alerts` to filter alert instances by label matchers, so the filtering is done by BE contrary to the previous FE implementation

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/alerting/unified/utils/matchers.ts [hunk 1]
```diff
@@ -37,6 +37,7 @@ interface MatchedInstance {
   };
 }
 
+// TODO We can probably remove this as filtering is done in the backend
```
Comment (konrad147) [inline public/app/features/alerting/unified/utils/matchers.ts:40]: Should we remove it?

File: public/app/features/alerting/unified/components/silences/MatchedSilencedRules.tsx [hunk 2]
```diff
@@ -1,110 +1,81 @@
...
         {matchers.every((matcher) => !matcher.value && !matcher.name) ? (
           <span>Add a valid matcher to see affected alerts</span>
         ) : (
-          <DynamicTable
-            items={matchedAlertRules}
-            isExpandable={false}
-            cols={columns}
-            pagination={{ itemsPerPage: 5 }}
-          />
+          <DynamicTable items={tableItemAlerts} isExpandable={false} cols={columns} pagination={{ itemsPerPage: 10 }} />
```
Comment (VikaCep) [inline public/app/features/alerting/unified/components/silences/MatchedSilencedRules.tsx]: Why was it changed from `5` to `10`?

File: public/app/features/alerting/unified/components/silences/MatchedSilencedRules.tsx [hunk 3]
```diff
@@ -1,110 +1,81 @@
...
-      renderCell: function renderSummary({ data: { matchedInstance } }) {
-        return (
-          <>
-            {matchedInstance.activeAt.startsWith('0001')
-              ? '-'
-              : dateTime(matchedInstance.activeAt).format('YYYY-MM-DD HH:mm:ss')}
-          </>
-        );
+      renderCell: function renderSummary({ data }) {
+        return <>{data.startsAt.startsWith('0001') ? '-' : dateTime(data.startsAt).format('YYYY-MM-DD HH:mm:ss')}</>;
```
Comment (VikaCep) [inline public/app/features/alerting/unified/components/silences/MatchedSilencedRules.tsx]: There's the function `isNullDate` in `time.ts` to check for this in case that you'd like to use it here instead.

File: public/app/features/alerting/unified/api/alertmanagerApi.ts [hunk 4]
```diff
@@ -12,8 +16,34 @@ export interface AlertmanagersChoiceResponse {
...
+    >({
+      query: ({ amSourceName, filter }) => {
+        // TODO Add support for active, silenced, inhibited, unprocessed filters
+        const filterMatchers = filter?.matchers
+          ?.filter((matcher) => matcher.name && matcher.value)
+          .map((matcher) => `${matcher.name}${matcherToOperator(matcher)}${matcher.value}`);
+
+        return {
+          url: `/api/alertmanager/${getDatasourceAPIUid(amSourceName)}/api/v2/alerts`,
+          params: { filter: filterMatchers },
```
Comment (VikaCep) [inline public/app/features/alerting/unified/api/alertmanagerApi.ts:45]: Does the filter work for all alertmanagers or just for grafana?

**Review by VikaCep — APPROVED** [review]
LGTM! non-blocking questions/comments.

File: public/app/features/alerting/unified/components/silences/MatchedSilencedRules.tsx (hunk 2 above)
Comment (konrad147) [reply public/app/features/alerting/unified/components/silences/MatchedSilencedRules.tsx]: Based on my own observation that 5 is too low and uncomfortable when you have more alerts 😄

File: public/app/features/alerting/unified/components/silences/MatchedSilencedRules.tsx (hunk 3 above)
Comment (konrad147) [reply public/app/features/alerting/unified/components/silences/MatchedSilencedRules.tsx]: Thanks! I'll use it

**Review by soniaAguilarPeiron — APPROVED** [review]
LGTM! Nice one!

File: public/app/features/alerting/unified/utils/matchers.ts (hunk 1 above)
Comment (konrad147) [reply public/app/features/alerting/unified/utils/matchers.ts:40]: I mean the whole function below this line

Comment (gillesdemey) [reply public/app/features/alerting/unified/utils/matchers.ts:40]: Yep, let's remove if it's not referrenced

**Review by gillesdemey — APPROVED** [review]
Tested and reviewed; LGTM! 🚀
