### PR TITLE
Azure Monitor: Fix resource picker selection for subresources

### LINKED ISSUE #56113: Azure Monitor: Wrong selection for resources including a /
**What happened**:

When a resource includes a subresource (e.g. `foo/bar`), only the main resource is used to do the matching for the selection in the UI. Selecting the wrong resource. In the "Advanced" section, you can see that the correct resource is selected so it's just a visual bug:

[Screencast from 30-09-22 16:35:30.webm](https://user-images.githubusercontent.com/4025665/193295017-74ae7ae3-7236-4170-9b45-cc3c01b7f78b.webm)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by andresmgot**
**What this PR does / why we need it**:

When matching a row in the resource picker, the subresource was ignored. This is because elements under `microsoft.storage/storageaccounts` namespace are not included. For example, for the resource `namespace: microsoft.storage/storageaccounts/tableServices, name: table/default` it should match the element: `microsoft.storage/storageaccounts/table`.

This is not the case for the rest of resources (with subresources), which should match exactly since all of them are listed (AFAIK).

**Which issue(s) this PR fixes**:

Fixes #56113

**Special notes for your reviewer**:

### CODE REVIEW

**Review by asimpson — APPROVED** [review]
:+1: nice work digging into this!

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/ResourcePicker/utils.ts [hunk 1]
```diff
@@ -62,18 +62,35 @@ export function isGUIDish(input: string) {
...
+  rowNamespace?: string,
+  rowName?: string,
+  resourceNamespace?: string,
+  resourceName?: string
+) {
+  // StorageAccounts subresources are not listed independently
+  if (resourceNamespace?.startsWith('microsoft.storage/storageaccounts')) {
+    resourceNamespace = 'microsoft.storage/storageaccounts';
+    if (resourceName?.endsWith('/default')) {
+      resourceName = resourceName.slice(0, -'/default'.length);
```
Comment (aangelisc) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/ResourcePicker/utils.ts:75]: A very nice way of doing this! Learn something new everyday 😜

**Review by aangelisc — APPROVED** [review]

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/ResourcePicker/utils.test.ts [hunk 2]
```diff
@@ -6,27 +6,27 @@ import { findRow, parseResourceURI, setResource } from './utils';
 describe('AzureMonitor ResourcePicker utils', () => {
   describe('parseResourceURI', () => {
     it('should parse subscription URIs', () => {
-      expect(parseResourceURI('/subscriptions/44693801-6ee6-49de-9b2d-9106972f9572')).toEqual({
-        subscription: '44693801-6ee6-49de-9b2d-9106972f9572',
+      expect(parseResourceURI('/subscriptions/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee')).toEqual({
```
Comment (aangelisc) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/ResourcePicker/utils.test.ts:9]: 👍
