### PR TITLE
 Dashboards: Fix edit button visibility to respect editable flag in new layouts

### LINKED ISSUE #115371: Dashboards in read only mode show "Edit" button
### What happened?

Dashboards with `editable: false` still showing `edit` button

### What did you expect to happen?

It should now give ability to edit read only dashboards

### PR DESCRIPTION
**Pull request by kristinademeshchik**
**What is this feature?**

This PR fixes the dashboard edit/make editable button visibility in the new dashboard layouts (v2) to properly respect the editable flag. Previously, the `EditDashboardSwitch` was always shown regardless of whether the dashboard was marked as read-only.

**Which issue(s) does this PR fix?**:

Fixes #115371

### CODE REVIEW

File: public/app/features/dashboard-scene/scene/new-toolbar/actions/MakeDashboardEditableButton.tsx [hunk 1]
```diff
@@ -17,7 +17,6 @@ export const MakeDashboardEditableButton = ({ dashboard }: ToolbarActionProps) =
       }}
       tooltip={t('dashboard.toolbar.new.enter-edit-mode.tooltip', 'This dashboard was marked as read only')}
       variant="secondary"
-      size="sm"
```
Comment (kristinademeshchik) [inline public/app/features/dashboard-scene/scene/new-toolbar/actions/MakeDashboardEditableButton.tsx:20]: this is not used in v2
this button is used instead - https://github.com/grafana/grafana/blob/main/public/app/features/dashboard-scene/scene/NavToolbarActions.tsx#L346-L366

**Review by oscarkilhed — APPROVED** [review]
🎉

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/20244762969)
- Version: 12.4.0-20244762969
