### PR TITLE
Misc styling fixes to explore

### LINKED ISSUE #13375: Explore mode slate editor theme
Not sure how easy this is to change. The current ACE editor theme we have created is a lot more vibrant and easier to read than the current dark theme for slate used in explore:

image

image

Is it possible to align these? 

The dark theme is defined here: 
https://github.com/grafana/grafana/blob/master/public/app/core/components/code_editor/theme-grafana-dark.js

### PR DESCRIPTION
**Pull request by torkelo**
* Fixed start page as it looked very ugly in dark theme
* Aligned slate colors with brace colors, now a lot more legible in dark theme 
* Aligned typeahead word highlight colors with the rest of Grafana (yellow) 

fixes https://github.com/grafana/grafana/issues/13375

### CODE REVIEW

**Review by davkal — CHANGES_REQUESTED** [review]
Good step towards consistency. 

- Blocker: LoggingStart pages are still in old layout.
- Minor: missing max-width reduced readibility of start page content
- Minor: punctuation styles make query selectors look messy
- Personal: slight preference for blue over orange, I would probably have adapted Brace styling instead

File: public/app/plugins/datasource/prometheus/components/PromStart.tsx [hunk 1]
```diff
@@ -1,59 +1,12 @@
...
-                  })}
-                </ul>
-              </nav>
-            </div>
-          </div>
-        </div>
-        <div className="page-container page-body">
-          {active === 'start' && <PromCheatSheet onClickExample={this.props.onClickExample} />}
-        </div>
+      <div className="grafana-info-box">
```
[the remark this answers is not in the document]
Comment (torkelo) [reply public/app/plugins/datasource/prometheus/components/PromStart.tsx]: agree in general, but since the whole page is full width, I think mixing full width and centered looked very ugly. So I prefer it like this, Especially the text being left aligned with the rest of the page.

**Comment by torkelo** [comment]
Updated promql and logging syntax to be more consitent with { and ) so they are always counted as punctuation. 

image

File: public/sass/components/_slate_editor.scss [hunk 2]
```diff
@@ -95,45 +95,45 @@
     color: $text-color-weak;
   }
 
-  .token.punctuation {
-    color: $text-color-weak;
+  .token.variable,
+  .token.entity {
+    color: $text-color;
```
Comment (davkal) [inline public/sass/components/_slate_editor.scss]: Metric names are tokenized as `variable`. With this change you can no longer tell if a metric name exists on the platform, because now it's just the text color. Before, it was a different color.

Comment (torkelo) [reply public/sass/components/_slate_editor.scss]: ah, did not realize that it validated the metric name exists, and it then gets a different color. thought it was only based on the syntax parser. 

Tried to find a good color, but found the readability best with a white text for this part. If everything has colors it just becomes too much. But think a red color could work for this, or maybe invert it so it's red if it's not found, so default to that.
