### PR TITLE
LibraryPanels: No save modal when user is on same dashboard

### LINKED ISSUE #31305: Library Panels continued
Continuation of Epic issue for the Library Panels feature. #29610

It does not show tasks in priority order :)
Please use avatar avatar to show which task you're working on:

**Backend**
- [x] Sync Panel Title and Name (#31311) 
- [x] Version column to support optimistic concurrency (#31590)
- [x] Permissions (#31572)
- [x] Improve Library Panel get all API
- [x] Add Type and Description to LibararyPanel table for better filtering possibilities and UX (#32258) 

**Frontend**
- [x] ~~Templating (pause until v8 Panel Edit UX is more polished)~~
   - [x] ~~Create a utility that can identify which variables are used in a library panel (#32206)~~
   - [x] ~~Create a generic utility that can import variables from a dashboard (should be able to reuse this for ordinary Dashboard page as well) (#32206)~~
   - [x] ~~Import Variables dialog (2 steps, chose dashboard first, then chose which variables) (#32206)~~
- [x] Edit Libray Panel in v8 Panel Edit UX branch 
   - [x] Add back search in AddPanelWidget
   - [ ] ~~Add filtering component for Types that can be reused between AddPanelWidget and PanelEdit~~ Moved to issue #32975
- [x] Improve the delete library panel flow with confirmation Modal (#32277)
- [x] Improve Library Panel get all API 
- [x] Add Library Panels to the global Dashboard section (#32876)
- [x] Add back library panel section to side pane (#32923)
- [x] Show Modal warning when changing library panels (#32892)
- [x] Add `Current Panel to Library Panel` to Share Modal as a Tab for normal Panels (#32953)
- [x] Add `Current Panel to Library Panel` to PanelMenu -> More for normal Panels  (#32908)
- [x] Add `Reset to normal Panel` to PanelMenu -> More for Library Panels (#32908)

- [ ] Make switching library panel more robust, currently, the plugin & model is changed in two steps which cause flickering and sometimes crashes as the model is in an inconsistent state . 

**Metrics**
- [ ] ~~Collect usage metrics for Cloud customers~~ Moved to issue #32976
   - How many panels on average are users creating
   - <identify more metrics>

**On hold**
- [ ] Tags (On hold)
- [ ] Starring (Do not think we will ever need this)
- [ ] General Search (on Hold)

**Bugs/Questions**
- [x] Save Panel directly after adding a panel to panel library, shouldn't show all dashboards
image
- [x] Changing visualization removes libarary panel options for a panel
bug
- [ ] Solution for discarding changes for Library Panels when user navigates back, ESC etc
- [x] Save Panel that's only used on the same dashboard, shouldn't show update all instances modal? (#31606)
image
- [x] Should the Library Panel being edited show up in the list of available Library Panels? (https://github.com/grafana/grafana/pull/31472)
image
- [x] Clicking on `Use instead of current panel` button shiftes the panel plugin but doesn't switch the actual visualization. The video shows switching from Table to Bar Gauge and only after saving the dashboard and refreshing the whole page does the Bar Gauge show up. (https://github.com/grafana/grafana/pull/31643)
bug

Root issue #1803

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This fixes a small issue when we showed the Update dashboard modal even if the library panel was just connected to the same dashboard as the user is saving the library panel from. I did a lot of refactoring of types and utils too.

I discovered that the recent version addition #31590 only worked for existing panels, so updating all newly added library panels won't work until this PR is merged.

**Which issue(s) this PR fixes**:
Relates #31305

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/dashboard/components/AddPanelWidget/AddPanelWidget.tsx [hunk 1]
```diff
@@ -119,7 +120,7 @@ export const AddPanelWidgetUnconnected: React.FC<Props> = ({ panel, dashboard, u
     const newPanel: PanelModel = {
       ...panelInfo.model,
       gridPos,
-      libraryPanel: _.pick(panelInfo, 'name', 'uid', 'meta'),
+      libraryPanel: toPanelModelLibraryPanel(panelInfo),
```
Comment (hugohaggmark) [inline public/app/features/dashboard/components/AddPanelWidget/AddPanelWidget.tsx:123]: I missed this in #31590 so any new library panels aren't updated correctly without this fix.

File: public/app/features/library-panels/components/PanelLibraryOptionsGroup/PanelLibraryOptionsGroup.tsx [hunk 2]
```diff
@@ -23,7 +25,7 @@ export const PanelLibraryOptionsGroup: React.FC<Props> = ({ panel, dashboard })
     panel.restoreModel({
       ...panelInfo.model,
       ...pick(panel, 'gridPos', 'id'),
-      libraryPanel: pick(panelInfo, 'uid', 'name', 'meta'),
+      libraryPanel: toPanelModelLibraryPanel(panelInfo),
```
Comment (hugohaggmark) [inline public/app/features/library-panels/components/PanelLibraryOptionsGroup/PanelLibraryOptionsGroup.tsx:28]: I missed this in #31590 so any new library panels aren't updated correctly without this fix.

File: public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx [hunk 3]
```diff
@@ -129,13 +138,28 @@ export class PanelEditorUnconnected extends PureComponent<Props> {
...
       // New library panel, no need to display modal
       return;
     }
 
+    if (this.props.panel.libraryPanel.meta.connectedDashboards === 0) {
+      return;
+    }
+
+    const connectedDashboards = await getLibraryPanelConnectedDashboards(this.props.panel.libraryPanel.uid);
+    if (connectedDashboards.length === 1 && connectedDashboards.indexOf(this.props.dashboard.id) !== -1) {
```
Comment (kaydelaney) [inline public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:152]: Small nit:
```suggestion
    if (connectedDashboards.length === 1 && connectedDashboards.includes(this.props.dashboard.id)) {
```

**Review by kaydelaney — APPROVED** [review]
Looks good!

**Comment by torkelo** [comment]
Nice!
