### PR TITLE
Panel: Disable legends when showLegend is false prior to schema v37

### LINKED ISSUE #54472: Timeseries panel switches showLegend to true
**What happened**:

Dashboard is generated as JSON with `showLegend: false` [here](https://github.com/grafana/mimir/blob/cacd7593458475964391ce27acf2f3059d290a6c/operations/mimir-mixin-compiled/dashboards/mimir-writes.json#L655-L679)

When I load it into Grafana the legend is visible.  If I go into Settings / JSON Model it flips to `true`:

```
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
```

**What you expected to happen**:

Legend should stay not-shown.

**How to reproduce it (as minimally and precisely as possible)**:

Use the above JSON.

**Anything else we need to know?**:

If you have the permissions at Grafana Labs you can load this via [URL](https://admin-ops-us-east-0.grafana.net/grafana/d/8280707b8f16e7b87b840fc1cc92d4c5/mimir-writes?from=now-1h&to=now&var-datasource=ops-cortex&var-cluster=prod-eu-west-0&var-namespace=cortex-dedicated-12&orgId=1&refresh=10s&editview=dashboard_json).

**Environment**:
- Grafana version: v9.2.0-7a340f48pre (7a340f486b)
- Data source type & version: Prometheus / please include instructions how to get the version.
- OS Grafana is installed on: Linux I guess.  How would I know, it's hosted by a different team.
- User OS & Browser:  Windows 10 Version 21H2 (Build 19044.1889), Google Chrome 104.0.5112.102 (Official Build) (64-bit)
- Grafana plugins: dozens of them, please include instructions here how to get a list if you want this. 
- Others: what.

### PR DESCRIPTION
**Pull request by ivanortegaalba**
**What this PR does / why we need it**:
Because of the migration logic, if any schema older than v37 includes `showLegend: false` that value is ignored and fallen back to `true` since the accepted value is `displayMode === 'hidden'` for those versions. [This Mimir dashboard](https://github.com/grafana/mimir/blob/cacd7593458475964391ce27acf2f3059d290a6c/operations/mimir-mixin-compiled/dashboards/mimir-writes.json#L655-L679) is generated with that option which breaks the experience. To solve this, we will allow older versions of the schema to be able to use `showLegend` which is the actual way of toggling it.

**Which issue(s) this PR fixes**:

Fixes #54472

### CODE REVIEW

File: public/app/features/dashboard/state/DashboardMigrator.ts [hunk 1]
```diff
@@ -793,7 +793,10 @@ export class DashboardMigrator {
 
     if (oldVersion < 37) {
       panelUpgrades.push((panel: PanelModel) => {
-        if (panel.options?.legend && panel.options.legend.displayMode === 'hidden') {
+        if (
+          panel.options?.legend &&
+          (panel.options.legend.displayMode === 'hidden' || panel.options.legend.showLegend === false)
```
Comment (polibb) [inline public/app/features/dashboard/state/DashboardMigrator.ts:798]: Yeah, looks okay! Should we add a comment above the if statement explaining the supported/not supported situation? Your PR description is good enough, but just to have it in here since `if (showLegend === false) showLegend = false` is definitely confusing

**Review by polibb — APPROVED** [review]

File: public/app/features/dashboard/state/DashboardMigrator.ts (hunk 1 above)
Comment (ivanortegaalba) [reply public/app/features/dashboard/state/DashboardMigrator.ts:798]: I totally agree! Done! Thanks for the suggestion!
