### PR TITLE
Table: Fix regression with Filter popup expression selection

### LINKED ISSUE #111688: Table: Column filters disappear when switching filter mode
### What happened?

I'm trying to filter a column, in the table panel, from `Contains` to any other type of filter (e.g. `>` or `=`). I click the column filter icon, then select the filter I want, and the filter selection disappears. Meaning I can't select or use the filter I want. 

https://github.com/user-attachments/assets/2273f812-f65c-4938-95e3-1372c5882a94

### What did you expect to happen?

I expected to be able to filter.

### Did this work before?

I don't know - sorry!

### How do we reproduce it?

1. Navigate to this sample dashboard: https://ops.grafana-ops.net/d/af3f9bb6-426e-4a52-9b32-b55a4850b32b/zach-days-dashboard?orgId=1&from=2025-08-27T16:11:14.317Z&to=2025-09-26T16:11:14.317Z&timezone=utc
2. Try to filter any of the columns
3. See that it won't work once you've selected the filter you want (e.g. `>`)

### Is the bug inside a dashboard panel?

| Key | Value |
|--|--|
| Panel | table @ 12.3.0-17940193463.patch1 |
| Grafana | Grafana Cloud (fast) // Enterprise |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "id": 2,
      "type": "table",
      "title": "Reproduced with embedded data",
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": "auto",
            "footer": {
              "reducers": []
            },
            "cellOptions": {
              "type": "auto"
            },
            "inspect": false,
            "filterable": true
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "value": null,
                "color": "green"
              },
              {
                "value": 80,
                "color": "red"
              }
            ]
          },
          "color": {
            "mode": "thresholds"
          }
        },
        "overrides": []
      },
      "pluginVersion": "12.3.0-17940193463.patch1",
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "notices": [
                    {
                      "severity": "info",
                      "text": "Cached response"
                    }
                  ],
                  "isCachedResponse": true
                },
                "name": "flight_info_by_state.csv",
                "fields": [
                  {
                    "name": "State",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "Lat",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "Lng",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "DestLocation",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "Count",
                    "type": "number",
                    "typeInfo": {
                      "frame": "int64",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "Price",
                    "type": "number",
                    "typeInfo": {
                      "frame": "int64",
                      "nullable": true
                    },
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    "Alaska",
                    "Alabama",
                    "Arizona",
                    "California",
                    "Colorado",
                    "Florida",
                    "Iowa",
                    "Illinois",
                    "Indiana",
                    "Kentucky",
                    "Massachusetts",
                    "Michigan",
                    "North Carolina",
                    "New Jersey",
                    "New Mexico",
                    "Ohio",
                    "Oregon"
                  ],
                  [
                    61.385,
                    32.799,
                    33.7712,
                    36.17,
                    39.0646,
                    27.8333,
                    42.0046,
                    40.3363,
                    39.8647,
                    37.669,
                    42.2373,
                    43.3504,
                    35.6411,
                    40.314,
                    34.8375,
                    40.3736,
                    44.5672
                  ],
                  [
                    -152.2683,
                    -86.8073,
                    -111.3877,
                    -119.7462,
                    -105.3272,
                    -81.717,
                    -93.214,
                    -89.0022,
                    -86.2604,
                    -84.6514,
                    -71.5314,
                    -84.5603,
                    -79.8431,
                    -74.5089,
                    -106.2371,
                    -82.7755,
                    -122.1269
                  ],
                  [
                    "bdg",
                    "djf",
                    "9w0",
                    "9q6",
                    "9wv",
                    "dhv",
                    "9zm",
                    "dp0",
                    "dp4",
                    "dne",
                    "drt",
                    "dpe",
                    "dnr",
                    "dr5",
                    "9wh",
                    "dpj",
                    "9rc"
                  ],
                  [
                    5,
                    3,
                    10,
                    12,
                    1,
                    5,
                    7,
                    1,
                    5,
                    6,
                    11,
                    2,
                    5,
                    12,
                    15,
                    9,
                    3
                  ],
                  [
                    500,
                    300,
                    150,
                    250,
                    600,
                    500,
                    700,
                    400,
                    540,
                    630,
                    460,
                    250,
                    500,
                    400,
                    800,
                    930,
                    360
                  ]
                ]
              }
            }
          ]
        }
      ],
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "options": {
        "showHeader": true,
        "cellHeight": "sm"
      }
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >table @ 12.3.0-17940193463.patch1</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[grafana-testdata-datasource]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 1 frames, 6 fields, 17 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>Grafana Cloud (fast) // Enterprise</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"id\": 1,\n  \"type\": \"table\",\n  \"title\": \"New panel\",\n  \"gridPos\": {\n    \"x\": 0,\n    \"y\": 0,\n    \"h\": 9,\n    \"w\": 24\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"align\": \"auto\",\n        \"footer\": {\n          \"reducers\": []\n        },\n        \"cellOptions\": {\n          \"type\": \"auto\"\n        },\n        \"inspect\": false,\n        \"filterable\": true\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"value\": null,\n            \"color\": \"green\"\n          },\n          {\n            \"value\": 80,\n            \"color\": \"red\"\n          }\n        ]\n      },\n      \"color\": {\n        \"mode\": \"thresholds\"\n      }\n    },\n    \"overrides\": []\n  },\n  \"pluginVersion\": \"12.3.0-17940193463.patch1\",\n  \"targets\": [\n    {\n      \"scenarioId\": \"csv_file\",\n      \"refId\": \"A\",\n      \"datasource\": {\n        \"type\": \"grafana-testdata-datasource\",\n        \"uid\": \"000000036\"\n      },\n      \"csvFileName\": \"flight_info_by_state.csv\"\n    }\n  ],\n  \"datasource\": {\n    \"uid\": \"000000036\",\n    \"type\": \"grafana-testdata-datasource\"\n  },\n  \"options\": {\n    \"showHeader\": true,\n    \"cellHeight\": \"sm\"\n  }\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: New panel // 2025-09-26 17:11:45",
  "tags": [
    "debug",
    "debug-table"
  ],
  "time": {
    "from": "2025-08-27T16:11:14.317Z",
    "to": "2025-09-26T16:11:14.317Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by fastfrwrd**
Fixes #111688 

_This regression was introduced last week, and was not backported, so it is not in 12.2.x and this fix will not be backported._

### Technical explanation

In https://github.com/grafana/grafana/pull/111431, ButtonSelect was wrapped with `Dropdown`, which is causing a situation where components already inside a Dropdown which render a ButtonSelect inside of them (such as the FilterPopup in TableNG) were not able to properly handle the onClick event on the MenuItems of the ButtonSelect. By allowing those to set a `root` for the Dropdown (e.g. the underlying Portal), we can avoid the issue.

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/TableNG/Filter/FilterPopup.tsx [hunk 1]
```diff
@@ -36,9 +36,9 @@ const OPERATORS = Object.values(operatorSelectableValues);
 
 interface Props {
   name: string;
-  rows: any[];
-  filterValue: any;
-  setFilter: (value: any) => void;
+  rows: TableRow[];
+  filterValue?: Array<SelectableValue<unknown>>;
+  setFilter: React.Dispatch<React.SetStateAction<FilterType>>;
```
Comment (fastfrwrd) [inline packages/grafana-ui/src/components/Table/TableNG/Filter/FilterPopup.tsx:41]: I also took the liberty of fixing some lingering TypeScript issues in the Filter area which had been ignored for a bit.

**Review by torkelo — APPROVED** [review]

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/18118403699)
- Version: 12.3.0-18118403699
