### PR TITLE
CLI: Fix encrypt-datasource-passwords fails with sql error

### LINKED ISSUE #17948: grafana-cli encrypt-datasource-passwords fails with sql error
Tried to encrypt datasource passwords with grafana-cli. It didnt work.

```
/usr/sbin/grafana-cli --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini admin data-migration encrypt-datasource-passwords cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana
t=2019-07-04T21:22:48+0000 lvl=warn msg="[Removed] Session setting was removed in v6.2, use remote_cache option instead" logger=settings
t=2019-07-04T21:22:48+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=mysql
t=2019-07-04T21:22:48+0000 lvl=info msg="Starting DB migration" logger=migrator

Error: failed to select column: basic_auth_password: sql: Scan error on column index 2, name "secure_json_data": unsupported Scan, storing driver.Value type <nil> into type *string

NAME:
   Grafana cli admin data-migration encrypt-datasource-passwords - Migrates passwords from unsecured fields to secure_json_data field. Return ok unless there is an error. Safe to execute multiple times.

USAGE:
   Grafana cli admin data-migration encrypt-datasource-passwords [arguments...]
```

I believe that this error is happening as some data_sources in the DB have 'secure_json_data' currently set to NULL.  The mysql schema as the column default set to NULL so this should be allowed.  But looks like the code is expecting the column to contain '{}' instead.

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Now handles secure_json_data stored as null in database when
running the encrypt-datasource-passwords migration.

**Which issue(s) this PR fixes**:
Fixes #17948 

**Special notes for your reviewer**:
It isn't pretty, but it works :smile: Kind of tired now, so please verify that I haven't done anything crazy.

### CODE REVIEW

File: pkg/cmd/grafana-cli/commands/datamigrations/encrypt_datasource_passwords.go [hunk 1]
```diff
@@ -62,7 +62,7 @@ func EncryptDatasourcePaswords(c utils.CommandLine, sqlStore *sqlstore.SqlStore)
 }
 
 func migrateColumn(session *sqlstore.DBSession, column string) (int, error) {
-	var rows []map[string]string
+	var rows []map[string][]byte
```
Comment (marefr) [inline pkg/cmd/grafana-cli/commands/datamigrations/encrypt_datasource_passwords.go]: This was the first fix, scanning a row containing a row with `secure_json_data=null` to a string throwed error. Tried to create a struct for this, but tricky since it's operating on dynamic password columns so skipped that and using byte arrays instead of string.

File: pkg/cmd/grafana-cli/commands/datamigrations/encrypt_datasource_passwords.go [hunk 2]
```diff
@@ -108,16 +108,20 @@ func updateRows(session *sqlstore.DBSession, rows []map[string]string, passwordF
...
 	var secureJSONData map[string]interface{}
 
-	if err := json.Unmarshal([]byte(row["secure_json_data"]), &secureJSONData); err != nil {
-		return nil, err
+	if len(row["secure_json_data"]) > 0 {
+		if err := json.Unmarshal(row["secure_json_data"], &secureJSONData); err != nil {
+			return nil, err
+		}
+	} else {
+		secureJSONData = map[string]interface{}{}
```
Comment (aocenas) [inline pkg/cmd/grafana-cli/commands/datamigrations/encrypt_datasource_passwords.go]: This will change `NULL` -> `{}` right?

File: pkg/cmd/grafana-cli/commands/datamigrations/encrypt_datasource_passwords_test.go [hunk 3]
```diff
@@ -20,19 +20,30 @@ func TestPasswordMigrationCommand(t *testing.T) {
...
+		} else {
+			ds.SecureJsonData = securejsondata.GetEncryptedJsonData(map[string]string{})
+		}
 	}
 
 	_, err := session.Insert(&datasources)
 	assert.Nil(t, err)
 
+	// force secure_json_data to be null to verify that migration can handle that
+	_, err = session.Exec("update data_source set secure_json_data = null where name = 'influxdb'")
```
Comment (aocenas) [inline pkg/cmd/grafana-cli/commands/datamigrations/encrypt_datasource_passwords_test.go]: Could this be moved into the insert part and just not set the `ds.SecureJsonData` for influx (adding `if` next to `if ds.Name == "elasticsearch" {`) or is there some caveat why is this done in extra sql?

**Review by aocenas — APPROVED** [review]
Looks good

File: pkg/cmd/grafana-cli/commands/datamigrations/encrypt_datasource_passwords.go (hunk 2 above)
Comment (marefr) [reply pkg/cmd/grafana-cli/commands/datamigrations/encrypt_datasource_passwords.go]: Yes, that's correct.

File: pkg/cmd/grafana-cli/commands/datamigrations/encrypt_datasource_passwords_test.go (hunk 3 above)
Comment (marefr) [reply pkg/cmd/grafana-cli/commands/datamigrations/encrypt_datasource_passwords_test.go]: I tried to use the insert, but couldn't get it to insert null for secure_json_data, it was always set to empty string. Don't understand how certain Grafana instances could have null in the first place for secure_json_data though. Could also be related to historic xorm upgrades maybe handling 
null values differently?

Going to try and use the api and create a datasource and see if I can force a null that way.

Comment (aocenas) [reply pkg/cmd/grafana-cli/commands/datamigrations/encrypt_datasource_passwords_test.go]: Right with xorm you have to set something like `session.MustCols("secure_json_data")` to mark that if it is zero value in the insert it will be null. I assume something like this could have changed between some versions.

Comment (marefr) [reply pkg/cmd/grafana-cli/commands/datamigrations/encrypt_datasource_passwords_test.go]: Looked into using `session.MustCols("secure_json_data")`and it seemed to work at first, but behaved very weird. 

In the current state of this pr when updating a datasource secure_json_data with an explicit null value and inspecting the mysql database directly after the update have been written the secure_json_data column has a value of `NULL`. This is an actual NULL value in the database.

Using `session.MustCols("secure_json_data")` and inspecting the mysql database directly after the inserts I can see that secure_json_data column has a value of `null`. This is not an actual NULL value in the database, instead it's a string with the value `null`.

Because of this me and @aocenas decided that we'll merge these changes for the 6.3-beta1 and let users report if there should be any problem or some scenario left to handle.
