### PR TITLE
TableNG: JSON cell implementation + hover fixes

### LINKED ISSUE #94770: TableNG: Cell Type - JSON View
Table cell type for rendering JSON content.

Also support:
- Cell value inspect toggle

### PR DESCRIPTION
**Pull request by alexjonspencer1**
### What does this PR do? 📓 

This PR adds support for JSON cell type. It also makes a few adjustments to hover behavior (please let me know your thoughts on this).

**JSON Cell Notes:** 

- Still need to implement data links and actions. 
- The inspect behavior for JSON cell type previously was handled within the JSON cell. Since that logic has been hoisted into TableCellNG, it leads to a nice and clean JSON cell implementation. Thanks, Ihor!
- I made some changes to our `ContextMenu` state to support a dynamic mode for the Table Inspector. When a user opens the inspector for JSON, it needs to be in code mode, not text mode. 

**Auto Cell Notes:** 

- I think it makes sense to hoist the hover logic outside of `<AutoCell />`, because it's not just auto cell types that support overflow hover, right?

**Other notes:** 

- I added a `height` property to the hover div so it matches at a minimum the cell height. I think this looks more tidy.

#### JSON in TableNG w/hover

image

#### Quick snap of how the new hover behavior works + height, etc.

https://github.com/user-attachments/assets/5f4c3dc4-aba0-49fe-ad86-62644eeee88e

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/TableNG/types.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ export interface CellNGProps {
   field: Field;
   theme: GrafanaTheme2;
   height?: number;
-  justifyContent: Property.JustifyContent;
+  justifyContent?: Property.JustifyContent;
```
Comment (Develer) [inline packages/grafana-ui/src/components/Table/TableNG/types.ts:10]: The JSONCell also includes a Column Alignment option, similar to most table cells, so it makes sense for it to be non-optional. 🙂

Could you please add justify-content to JSONCell as well?

https://github.com/user-attachments/assets/fff3d562-27c8-4f8c-a5f1-2f3c33dc625d

**Review by Develer — APPROVED** [review]
LGTM 🚀

**Review by drew08t — APPROVED** [review]
