### PR TITLE
Alerting/fix folder creation dropdown

### LINKED ISSUE #34796: Unified alerting: Fix folder creation dropdown on alert rule page
On alert rule creation - Grafana managed alerts, folder dropdown should display "+ Add new folder" as we do for Namespaces and Groups for Prometheus alerts. It's confusing for the user to think they have no way of creating a new folder, just typing the name is not that obvious. 

Screenshot 2021-05-27 at 12 02 55
Screenshot 2021-05-27 at 12 04 22
rea

### PR DESCRIPTION
**Pull request by soniaAguilarPeiron**
**Why do we need it?**
This PR fixes the problem we have when no folders are found and makes the folder drop down behaves in the same way as the name space drop down. See #34796

BEFORE: 

https://user-images.githubusercontent.com/33540275/188839664-9f0a0d50-363d-48c7-aa72-cadcf0365e96.mp4

AFTER:

https://user-images.githubusercontent.com/33540275/188839860-be94d7ac-32c3-4d3b-be52-ee6e1853bef0.mp4

**What this PR does**
This PR improves the creation of new folder. It follows the same behaviour as we have in name spaces in the same view.
Includes a refactor for the `Folderpicker` component to be a functional component.

**Which issue(s) this PR fixes**:

Fixes #34796 

**Special notes for your reviewer**:

Added an optional property `customAdd` to be able to maintain the same behaviour we have in the rest of the places where this component is being used.

RESULT OF THIS PR:

https://user-images.githubusercontent.com/33540275/188857774-2b256257-8881-410b-85b6-9943957e9b4d.mp4

### CODE REVIEW

File: public/app/features/alerting/unified/components/rule-editor/FolderPickerWithAdd.tsx [hunk 1]
```diff
@@ -0,0 +1,279 @@
...
+    [createNewFolder, folder, rootName, setFolderLabel]
+  );
+
+  const onNewFolderChange = (e: FormEvent<HTMLInputElement>) => {
+    const value = e.currentTarget.value;
+    const withoutSlashes = value.split('/').join('');
+    setFolder({ id: -1, title: withoutSlashes });
+  };
+
+  if (isCustom) {
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rule-editor/FolderPickerWithAdd.tsx:243]: `react-select` supports `AsyncCreatable`. Maybe we could use that instead of handling it on our own?
Take a look at https://github.com/grafana/grafana/blob/55b1d11aceb1081d62fc01e20f38f0013866fa43/packages/grafana-ui/src/components/Select/SelectBase.tsx#L260-L267

**Review by konrad147 — COMMENTED** [review]
I'm a bit concerned about the amount of code copied from `FolderPicker`. I wonder if there is any easy way to extend the original `FolderPicker` so it could support adding folders or would be capable of handling more props which would allow us to add the desired behaviour.

File: public/app/features/alerting/unified/components/rule-editor/FolderPickerWithAdd.tsx [hunk 2]
```diff
@@ -0,0 +1,279 @@
...
+import { contextSrv } from 'app/core/services/context_srv';
+import { createFolder, getFolderById, searchFolders } from 'app/features/manage-dashboards/state/actions';
+import { DashboardSearchHit } from 'app/features/search/types';
+import { AccessControlAction, PermissionLevelString } from 'app/types';
+
+import { initialFolderLabel } from './DetailsStep';
+
+export type FolderPickerFilter = (hits: DashboardSearchHit[]) => DashboardSearchHit[];
+
+export interface Props {
```
[the remark this answers is not in the document]
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/FolderPickerWithAdd.tsx:20]: sure! good point

File: public/app/features/alerting/unified/components/rule-editor/FolderPickerWithAdd.tsx (hunk 1 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/FolderPickerWithAdd.tsx:243]: So far, we are using Asynccreatable : 
```
 if (allowCustomValue) {
      SelectComponent = Creatable;
      creatableOptions.formatCreateLabel = formatCreateLabel ?? ((input: string) => input);
    }
```
that comes from : `import Creatable from 'react-select/creatable';`

And it's what we don't want to use as the behaviour is not aligned with namespaces.

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/FolderPickerWithAdd.tsx:243]: thank you @konrad147 ! I will take a look!

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/FolderPickerWithAdd.tsx:243]: I was handling it by my own to be consistent with name spaces behaviour. Let's see how it looks using this `AsyncCreatable` 🤞

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/FolderPickerWithAdd.tsx:243]: Now I remember I'm not using `AsyncCreatable`, we need to keep the consistency between Folder, Namespace and Group dropdowns. And so far, in name spaces we have this:
Screenshot 2022-09-06 at 16 43 03

So if we want to have the same behaviour/UI we need to handle it in the same way.

File: public/app/features/alerting/unified/components/rule-editor/FolderPickerWithAdd.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/FolderPickerWithAdd.tsx]: I've just moved all the implementation to the FolderPicker => no more duplicated code

File: public/app/core/components/Select/FolderPicker.tsx [hunk 3]
```diff
@@ -19,7 +20,7 @@ export interface Props {
   enableCreateNew?: boolean;
   rootName?: string;
   enableReset?: boolean;
-  dashboardId?: any;
+  dashboardId?: number | string;
```
Comment (konrad147) [inline public/app/core/components/Select/FolderPicker.tsx:23]: ❤️

**Comment by soniaAguilarPeiron** [comment]
> I'm a bit concerned about the amount of code copied from `FolderPicker`. I wonder if there is any easy way to extend the original `FolderPicker` so it could support adding folders or would be capable of handling more props which would allow us to add the desired behaviour.

All implementation has been moved to the FolderPicker component, so there is no duplicated code any more

File: public/app/core/components/Select/FolderPicker.tsx [hunk 4]
```diff
@@ -195,25 +143,120 @@ export class FolderPicker extends PureComponent<Props, State> {
...
+    },
+    [createNewFolder, folder, rootName]
+  );
+
+  const onNewFolderChange = (e: FormEvent<HTMLInputElement>) => {
+    const value = e.currentTarget.value;
+    setFolder({ id: -1, title: value });
+  };
+
+  if (isCreatingNew) {
```
Comment (konrad147) [inline public/app/core/components/Select/FolderPicker.tsx:244]: No need to check if `customAdd` is set to true?

Comment (soniaAguilarPeiron) [reply public/app/core/components/Select/FolderPicker.tsx:244]: Not necessary, because `isCreatingnew` is going to be true only if we have `VALUE_FOR_ADD` in the options (that only happens if we have `customAdd` set to true
 ```
useEffect(() => {
    if (folder && folder.id === VALUE_FOR_ADD) {
      setIsCreatingNew(true);
    }
  }, [folder]); useEffect(() => {
    if (folder && folder.id === VALUE_FOR_ADD) {
      setIsCreatingNew(true);
    }
  }, [folder]);
```

File: public/app/core/components/Select/FolderPicker.tsx [hunk 5]
```diff
@@ -38,139 +42,83 @@ export interface Props {
...
-  private searchFolders = async (query: string) => {
-    const {
-      rootName,
+      if (
+        enableReset &&
+        query === '' &&
+        initialTitle !== '' &&
+        !options.find((option) => option.label === initialTitle)
+      ) {
+        options.unshift({ label: initialTitle, value: initialFolderId });
```
Comment (gillesdemey) [inline public/app/core/components/Select/FolderPicker.tsx:91]: I'm not entirely sure about this piece of code, it seems to be prepending a blank option to the list (can also be seen in the video recording).

Can you elaborate on what it's checking for here that warrants a mutation to the options list?

**Comment by gillesdemey** [comment]
After having played around with it for a bit I think that:

1. We should add an `onBlur` handler to the input when we are creating a new option, I think that makes sense when you want to cancel (took me a while to figure out I had to use "escape" and I hadn't read the source yet :)
2. Somehow when I type the name of a folder and click "add new" it doesn't populate the input with the entire name 🤔 

https://user-images.githubusercontent.com/868844/189673723-6aa9c08f-33f8-46d1-b169-4752a38e77d2.mp4

**Comment by soniaAguilarPeiron** [comment]
> After having played around with it for a bit I think that:
> 
> 1. We should add an `onBlur` handler to the input when we are creating a new option, I think that makes sense when you want to cancel (took me a while to figure out I had to use "escape" and I hadn't read the source yet :)
> 2. Somehow when I type the name of a folder and click "add new" it doesn't populate the input with the entire name 🤔
> 
>  Kapture.2022-09-12.at.16.00.11.mp4

ok! I will take a look! thank you @gillesdemey

**Comment by soniaAguilarPeiron** [comment]
> After having played around with it for a bit I think that:
> 
> 1. We should add an `onBlur` handler to the input when we are creating a new option, I think that makes sense when you want to cancel (took me a while to figure out I had to use "escape" and I hadn't read the source yet :)
> 2. Somehow when I type the name of a folder and click "add new" it doesn't populate the input with the entire name 🤔
> 
>  Kapture.2022-09-12.at.16.00.11.mp4


I've just pushed a fix for that problem @gillesdemey 

https://user-images.githubusercontent.com/33540275/189879318-89e46995-396c-4727-8265-44daa12679a2.mp4

File: public/app/core/components/Select/FolderPicker.tsx (hunk 5 above)
Comment (soniaAguilarPeiron) [reply public/app/core/components/Select/FolderPicker.tsx]: You were right @gillesdemey that causes a wrong empty row in the drop-down. I've just fixed:


https://user-images.githubusercontent.com/33540275/189921679-337d2203-9631-419a-af49-f5299557f76f.mp4

File: public/app/core/components/Select/FolderPicker.tsx [hunk 6]
```diff
@@ -38,139 +42,84 @@ export interface Props {
   /** The id of the search input. Use this to set a matching label with htmlFor */
   inputId?: string;
 }
+export type SelectedFolder = SelectableValue<number>;
+const VALUE_FOR_ADD = -10;
+
+export function FolderPicker(props: Props) {
```
Comment (VikaCep) [inline public/app/core/components/Select/FolderPicker.tsx:48]: Nice refactor into a functional component! 👏

**Review by gillesdemey — APPROVED** [review]
New changes LGTM! 🙌

**Comment by effendid** [comment]
hi, 
just to check. is it fixed in latest release?

**Comment by soniaAguilarPeiron** [comment]
Hi @effendid, fix has been merged so it will be available on next release 😊

**Comment by effendid** [comment]
Cool, thanks 👍
