### PR TITLE
Azure monitor: ensure that time column has a name

### LINKED ISSUE #35999: Table view crash using Azure datasource
**What happened**:

Creating any Azure metric and switching the dashboard to "Table view" crashes Grafana. I have tested creating the metric first then switching the button and switching to table first and then creating the metric. Both ways the screen crashes as soon as the data is fetched.

**What you expected to happen**:

To show me the metrics in a table view.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a new dashboard
- Choose an Azure datasource
- Create any metric and plot the chart
- Switch the "Table view" button on the top menu

**Anything else we need to know?**:

The logs printed on screen:

```
An unexpected error happened
DetailsTypeError: Cannot read property 'numeric' of undefined

    at wt (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3115:1756)
    at wn (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3285:18)
    at div
    at https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3285:2656
    at div
    at div
    at t (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:1875650)
    at div
    at div
    at div
    at t (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:706836)
    at h (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:5437:31539)
    at div
    at https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3285:921
    at Vr (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:2357:38225)
    at f (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:1961:2262)
    at div
    at div
    at Da (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3376:133)
    at lr (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:354:715)
    at div
    at t (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:1897376)
    at div
    at div
    at div
    at t (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:327:1554)
    at div
    at t (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:327:3507)
    at div
    at t (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:327:1554)
    at div
    at t (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:327:3507)
    at Vn (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:327:9018)
    at div
    at div
    at pr (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:354:2075)
    at k (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:70367)
    at div
    at W (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:405:667)
    at DashboardPage
    at k (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:70367)
    at n (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:462197)
    at dr (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:5612:3196)
    at t (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:1206671)
    at t (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:1208716)
    at div
    at t (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:1203276)
    at div
    at at (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3076:1106)
    at h (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:5435:19792)
    at Di (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3726:564)
    at Ei (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3726:848)
    at l (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:68275)
    at Nr (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:5625:300)
```

**Environment**:
Grafana version: 8.0.3
Data source type & version: Azure
OS Grafana is installed on: running on docker over Linux (centos 8.3.2011)
User OS & Browser: Fedora 33 & Google Chrome 91

### PR DESCRIPTION
**Pull request by sarahzinger**
**What this PR does / why we need it**:
Right now if you try to make a Metrics query with Azure Monitor and switch to the Table view you'll hit an error. This is because our Time fields seem to be missing a name property which are [required for parsing deep links](https://github.com/grafana/grafana/blob/8fe58fc2e3b62b06af87b0c4b2252b32d7008f3f/packages/grafana-data/src/field/fieldOverrides.ts#L354). 

**Which issue(s) this PR fixes**:

Fixes #35999

**Special notes for your reviewer**:
This seems to fix the problem, but doesn't feel like the most robust solution to me. I wonder if it is safe to assume the first field is always the time field here?

### CODE REVIEW

File: pkg/tsdb/azuremonitor/azuremonitor-datasource.go [hunk 1]
```diff
@@ -248,6 +248,8 @@ func (e *AzureMonitorDatasource) parseResponse(amr AzureMonitorResponse, query *
 
 		frame := data.NewFrameOfFieldTypes("", len(series.Data), data.FieldTypeTime, data.FieldTypeNullableFloat64)
```
Comment (andresmgot) [inline pkg/tsdb/azuremonitor/azuremonitor-datasource.go:249]: > I wonder if it is safe to assume the first field is always the time field here?

It is safe because in this line we are setting the first field type as `data.FieldTypeTime`. For me it's a bit weird that there is no way to set the field name when creating the frame and we have to do it manually afterwards but that's what the sdk exposes. It may be worth an issue for that repo but this should be fine.

**Review by andresmgot — APPROVED** [review]
LGTM. Good catch! We'd need to include this in the next release. For that, you need to add the label `backport/v8.0.x` and add it to the next `8.0.x` milestone.
