### PR TITLE
BarChart: Skip formatting null-valued ticks

### LINKED ISSUE #94616: Bar charts: x axis ticks display Null value
### What happened?

If I have Null mapping for data turned on and choose X-axis labels minimum spacing to any value except None, spaces between X-axis ticks are filled with Null value.

Image

### What did you expect to happen?

There should be empty space between X-axis ticks.

### Did this work before?

Don't think so, I was able to reproduce it on different Grafana versions.

### How do we reproduce it?

1. Have a bar chart
2. Set mapping for Special Null value
3. Set X-axis labels minimum spacing to any except None

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: 10x & 11x
OS: macos
Browser: firefox

### Grafana platform?

Other

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/grafana/issues/94616
Closes https://github.com/grafana/grafana/pull/94797

<details><summary>barchart-nan.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 376,
  "links": [],
  "panels": [
    {
      "datasource": {
        "default": true,
        "type": "grafana-testdata-datasource",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "fillOpacity": 80,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1,
            "scaleDistribution": {
              "type": "linear"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [
            {
              "options": {
                "match": "null",
                "result": {
                  "index": 0,
                  "text": "Null"
                }
              },
              "type": "special"
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 14,
        "w": 18,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "barRadius": 0,
        "barWidth": 0.97,
        "fullHighlight": false,
        "groupWidth": 0.7,
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "orientation": "horizontal",
        "showValue": "auto",
        "stacking": "none",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "xTickLabelRotation": 0,
        "xTickLabelSpacing": 100
      },
      "targets": [
        {
          "csvContent": "name,value\nfoo,0.5\nbar,50",
          "datasource": {
            "type": "grafana-testdata-datasource",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "type": "barchart"
    }
  ],
  "refresh": "",
  "schemaVersion": 40,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "browser",
  "title": "barchart-nan",
  "uid": "be174sgkm0bggb",
  "version": 3,
  "weekStart": ""
}
```
</details>

before:

image

after:

image

### CODE REVIEW

File: packages/grafana-ui/src/components/uPlot/config/UPlotAxisBuilder.ts [hunk 1]
```diff
@@ -168,7 +168,7 @@ export class UPlotAxisBuilder extends PlotConfigBuilder<AxisProps, Axis> {
     } else if (formatValue) {
       config.values = (u: uPlot, splits, axisIdx, tickSpace, tickIncr) => {
         let decimals = guessDecimals(roundDecimals(tickIncr, 6));
-        return splits.map((v) => formatValue!(v, decimals > 0 ? decimals : undefined));
+        return splits.map((v) => (v == null ? null : formatValue!(v, decimals > 0 ? decimals : undefined)));
```
Comment (Develer) [inline packages/grafana-ui/src/components/uPlot/config/UPlotAxisBuilder.ts:171]:
```suggestion
        return splits.map((v) => {
            if (v == null) {
                return null;
            } else {
                return formatValue!(v, decimals > 0 ? decimals : undefined);
            }
        });
```

@leeoniya I know you like short versions better, but maybe for the sake of readability 😁

**Review by Develer — APPROVED** [review]
LGTM 🚀
