### PR TITLE
Prometheus: Fix interpolation of $__rate_interval variable

### LINKED ISSUE #43720: $__rate_interval is not $__interval + scrape_interval
**What happened**:
We have a counter that increases by 1 every 10 minutes. Prometheus `scrape_interval: 30s` and that same thing is set in the Prometheus data source which you can see from the image:
image

If the Prometheus range query `step` aligns with the counter increase Grafana returns an empty result. Here is a video displaying how it happens:

https://user-images.githubusercontent.com/1949229/148238016-d159adec-cc10-4066-87bc-e1f6680b5f4e.mp4

As you can see from the video, setting `Min step` to `2m`, `5m`, or `10m` returns an empty result. My guess is that the start of each step is perfectly aligned between the two scrapes when the counter increases by one and because in all situations when `step>=2m`, `$__rate_interval` will be equal to the `step + scrape_interval`.

I don't know how could this happen when `$__rate_interval` from the [code](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/datasource.ts#L539) should be bigger for one scrape interval:
```
const rateInterval = Math.max(interval + scrapeInterval, 4 * scrapeInterval);
```
But from my tests it's like `$__rate_interval` is the same as the step because when I set the step to 600s and set the PromQL query interval to 630s all works fine which you can see from the video.

I don't know how to see the value of `$__rate_interval`. When I open Query inspect it's still displayed as a variable.

Does anyone have an idea what's the problem here?

**How to reproduce it (as minimally and precisely as possible)**:
See the video. The data needs to be aligned to reproduce it (I guess)

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Prometheus 5.0.0
- OS Grafana is installed on: CentOS 7
- User OS & Browser: ArchLinux/Firefox

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:

This PR tackles 3 things:
1. It fixes https://github.com/grafana/grafana/issues/43720 that was happening due to using `intervalv2.FormatDuration` that rounds the duration. So if the duration was `5m30s` it became `5m`.
2. This is probably an edge case, but it fixes the calculation of  `$__rate_interval` when  `$__rate_interval` is used both. in `interval` and in `expr`. If it is used in both, we need to just use the `$__rate_interval` and not calculate it again.
3. Fixes using of `$__rate_interval` in interval.

I have decided to create helper functions and move different logics into different functions to make it more clear what is happening.
**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/43720

**How to test/reproduce:**
To reproduce/test first issue, you can set min interval 5m and then the rate interval should be 5m + scrape interval (in my case I have 30 sec scrape interval). Therefore correct interpolated rate interval should be 5m30s, while in. the past it would be evaluated to 5m:

https://user-images.githubusercontent.com/30407135/149511333-8d3391ec-a403-456b-b822-373e8c3ea0ba.mov

2. When you use rate interval in interval, it should be interpolated to 4x scrape interval (in my case 30 sec) => 2 min

https://user-images.githubusercontent.com/30407135/149512008-406a366e-555a-4e7a-a345-d86a714afddc.mov

### CODE REVIEW

File: pkg/tsdb/prometheus/time_series_query.go [hunk 1]
```diff
@@ -274,24 +272,32 @@ func calculateRateInterval(interval time.Duration, scrapeInterval string, interv
...
+	var rateInterval time.Duration
+	if model.Interval == varRateInterval || model.Interval == varRateIntervalAlt {
+		rateInterval = interval
+	} else {
+		rateInterval = calculateRateInterval(interval, timeInterval, intervalCalculator)
+	}
+
 	expr = strings.ReplaceAll(expr, varIntervalMs, strconv.FormatInt(int64(interval/time.Millisecond), 10))
 	expr = strings.ReplaceAll(expr, varInterval, intervalv2.FormatDuration(interval))
 	expr = strings.ReplaceAll(expr, varRangeMs, strconv.FormatInt(rangeMs, 10))
```
Comment (gabor) [inline pkg/tsdb/prometheus/time_series_query.go:289]: i see that two uses of `intervalv2.FormatDuration` remain in this file. are those ok?

**Review by gabor — APPROVED** [review]
LGTM!

(i left a comment-question above. but that can be handled separately)

**Comment by DasSkelett** [comment]
This might have caused a big regression: https://github.com/grafana/grafana/issues/44198
