### PR TITLE
Plugins Catalog: Fix styling of hyperlinks

### LINKED ISSUE #48078: Plugins Catalog: Hyperlinks Do Not Appear As Hyperlinks
In both the header and the body of pages on the Plugins Catalog, hyperlinks do not appear to be hyperlinks. They function as hyperlinks, you can click on them and they work. Visually, they have no distinguishing features that make it clear they are a hyperlink. (IE: being a different text color). 

This is very confusing for users, as additional information is frequently linked from these pages, but the users do not see them as links.

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Adds some styling (default hyperlink color and underline on hover) to plugin readme hyperlinks.

Header:
image
image

Body:
image
image

**Which issue(s) this PR fixes**:
Fixes #48078 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by jackw — APPROVED** [review]
Great work on this @marefr  🚀 

> In both the header and the body of pages on the Plugins Catalog,

Do we also need to style the header links with underline on hover before we can close that issue? 🤔

**Comment by marefr** [comment]
> Great work on this @marefr 🚀
> 
> > In both the header and the body of pages on the Plugins Catalog,
> 
> Do we also need to style the header links with underline on hover before we can close that issue? 🤔

Hmm what are the header links?

**Comment by jackw** [comment]
> Hmm what are the header links?

I believe they are the **Github**, **Docs**, and **License** links under the plugin name at top of details page.

**Comment by marefr** [comment]
@jackw Pushed an update for the header. Not sure it looks great, but now at least you see there are links :smile:

File: public/app/features/plugins/admin/components/PluginDetailsHeader.tsx [hunk 1]
```diff
@@ -135,13 +135,23 @@ export const getStyles = (theme: GrafanaTheme2) => {
...
         }
         &:last-child::after {
           content: '';
           padding-right: 0;
         }
       }
       font-size: ${theme.typography.h4.fontSize};
+
+      a {
+        color: ${theme.colors.text.link};
```
Comment (jackw) [inline public/app/features/plugins/admin/components/PluginDetailsHeader.tsx:148]: Hmm... looking at the screenshots in the description I think this would look neater without the link color definitions and just the underline. WDYT?

Comment (marefr) [reply public/app/features/plugins/admin/components/PluginDetailsHeader.tsx:148]: That make more sense. Thanks

Comment (marefr) [reply public/app/features/plugins/admin/components/PluginDetailsHeader.tsx]: Changed so it only shows underline on hover, no color changes. Updated screenshots in the description

Comment (jackw) [reply public/app/features/plugins/admin/components/PluginDetailsHeader.tsx]: Nice. I say we go with this. 👍
