### PR TITLE
Time picker: Fixed so you can enter a relative range in the time picker without being converted to absolute range

### LINKED ISSUE #24498: Support for future relative time ranges
**What would you like to be added**:
The ability to configure a relative time range that extends into the future.

**Why is this needed**:
Over the weekend, I put together a Grafana data source using the [building a data source plugin tutorial](https://grafana.com/tutorials/build-a-data-source-plugin) (which is great by the way!). The [data source](https://github.com/departureboard-io/departureboard-io-datasource) uses the https://api.departureboard.io JSON API to draw a table of train schedule boards in Grafana. I was hoping to use the Grafana time picker to control how far into the future to request data (something like now -> now+1h) and use the auto-refresh functionality.

Though I haven't yet tested it, I believe I can use absolute time ranges for queries into the future but since they are absolute, they do not auto-refresh.

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
Making sure that we can enter a relative time range in the time picker form without it being converted to an absolute time range. This is important for scenarios where we use the auto-refresh functionality.

**Which issue(s) this PR fixes**:
Fixes #24498

**Special notes for your reviewer**:
Will try to add some e2e tests to verify this to prevent future errors from happening.

### CODE REVIEW

**Review by tskarhed — APPROVED** [review]
Looks good to me! :trophy:

File: packages/grafana-data/src/datetime/rangeutil.ts [hunk 1]
```diff
@@ -63,10 +63,33 @@ const rangeOptions = [
...
+  { from: 'now', to: 'now+24h', display: 'Next 24 hours', section: 3 },
+  { from: 'now', to: 'now+2d', display: 'Next 2 days', section: 0 },
+  { from: 'now', to: 'now+7d', display: 'Next 7 days', section: 0 },
+  { from: 'now', to: 'now+30d', display: 'Next 30 days', section: 0 },
+  { from: 'now', to: 'now+90d', display: 'Next 90 days', section: 0 },
+  { from: 'now', to: 'now+6M', display: 'Next 6 months', section: 0 },
+  { from: 'now', to: 'now+1y', display: 'Next year', section: 0 },
+  { from: 'now', to: 'now+2y', display: 'Next 2 years', section: 0 },
+  { from: 'now', to: 'now+5y', display: 'Next 5 years', section: 0 },
+];
```
Comment (sakjur) [inline packages/grafana-data/src/datetime/rangeutil.ts:84]: :tada: This is a really nice detail! 🙏 Thank you for adding these @mckn
