### PR TITLE
Plugins: Fix Managed By Grafana version display for grafana cloud

### LINKED ISSUE #98110: Plugins: Managed by Grafana version is not supported with new plugin details panel
### What happened?

We have a logic to not show version of some plugins managed by Grafana, but it was broken by new logic of Plugin details panel

### What did you expect to happen?

When you open Grafana plugin details, you should see Managed by Grafana instead of version

### Did this work before?

It works when the toggle is disabled

### How do we reproduce it?

1. Open any plugin managed by grafana
2. You can see the version, but should see Managed by Grafana

### PR DESCRIPTION
**Pull request by Ukochka**
With introducing Plugin details panel we changed the behaviour to display versions. Now we show Installed version and Latest version. But for some plugins managed by Grafana we do not want to show version. In this case we need to check if plugin isManaged. The logic was written in the usePluginInfo. I changed the logic to incliude 2 different versions and handle isManaged flag. To be able just show all the data from info in the plugin details panel

**Why do we need this feature?**
It is a fix for not showing Managed by Grafana version in cloud

Fixes #98110

### CODE REVIEW

File: public/app/features/plugins/admin/hooks/usePluginInfo.tsx [hunk 1]
```diff
@@ -16,25 +16,38 @@ export const usePluginInfo = (plugin?: CatalogPlugin): PageInfoItem[] => {
   if (!plugin) {
     return info;
   }
+  console.log('plugin POPOPOPO', plugin);
```
Comment (joshhunt) [inline public/app/features/plugins/admin/hooks/usePluginInfo.tsx:19]: hehehe

**Review by wbrowne — APPROVED** [review]
Tested and LGTM!
