### PR TITLE
Chore: fixes throwing errors on 200 response with influxdb datasource

### LINKED ISSUE #21647: Show influxdb error messages from HTTP 200 responses
**What would you like to be added**:

InfluxDB api has some cases where the query call returns HTTP 200 without series, but it includes error messages in the results blocks.
These error messages should be shown as warning/error in the Grafana GUI.

E.g. due to query execution restrictions you can get the following results:
- Query timeout:  
```
{"results":[{"statement_id":0,"error":"query-timeout limit exceeded"}]}
```

- No result due to abort on query limits: e.g.   
```
{"results":[{"statement_id":0,"error":"max-select-buckets limit exceeded: (1081/200)"}]}
```

**Why is this needed**:

On these results the user needs to know, why the data is missing.
Currently this can only be seen in the query inspector via the response object.

Currently only errors with HTTP 400 from Influx are shown in the Grafana Gui.
Here the response message looks different. e.g. 
```
{"error":"error parsing query: found wh, expected ; at line 1, char 59"}
```
But HTTP 400 is only returned on syntax errors.

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Fixes throwing errors on a response with status code 200, that contains errors in the results blocks.

**Which issue(s) this PR fixes**:

Fixes #21647

### CODE REVIEW

**Comment by aocenas** [comment]
The issue you linked seems to be closed by other PR, can you comment here why this is still needed?

File: public/app/plugins/datasource/influxdb/datasource.ts [hunk 1]
```diff
@@ -322,6 +322,15 @@ export default class InfluxDatasource extends DataSourceApi<InfluxQuery, InfluxO
       .datasourceRequest(req)
       .then(
         (result: any) => {
+          if (result.data && result.data.results) {
+            const errors = result.data.results.filter((elem: any) => elem.error);
+            if (errors.length > 0) {
+              throw {
+                message: 'Error: ' + errors[0].error,
```
Comment (aocenas) [inline public/app/plugins/datasource/influxdb/datasource.ts:329]: Can there be more than 1 error? If so should they be included?
Also we prefix it with `InfluxDB Error` few lines down so I think it would make sense to have the same thing here.

**Comment by Estrax** [comment]
@aocenas Sure. Influx have two implementations - one for backend that's used by alerting and one for frontend that's being used in Explore and Dashboards. The PR that closed the referenced issue covered only the backend part, and this PR adds the frontend part of that.

File: public/app/plugins/datasource/influxdb/datasource.ts [hunk 2]
```diff
@@ -322,6 +322,15 @@ export default class InfluxDatasource extends DataSourceApi<InfluxQuery, InfluxO
       .datasourceRequest(req)
       .then(
         (result: any) => {
+          if (result.data && result.data.results) {
```
Comment (aocenas) [inline public/app/plugins/datasource/influxdb/datasource.ts:325]: Do we have some influx db doc link we could add here as a comment so it's easy to find out what kind of errors are these?

File: public/app/plugins/datasource/influxdb/datasource.ts (hunk 1 above)
Comment (Estrax) [reply public/app/plugins/datasource/influxdb/datasource.ts:329]: Right, changed the prefix. As for the errors, at least in theory there can be many results with different errors - though pretty much everywhere in the app we display only the very first one.

File: public/app/plugins/datasource/influxdb/datasource.ts (hunk 2 above)
Comment (Estrax) [reply public/app/plugins/datasource/influxdb/datasource.ts:325]: Unfortunately, not a lot of info has been published there: https://docs.influxdata.com/influxdb/v1.8/tools/api/ - though the most common errors I noticed are about the database or measurement not found, then limits exceeded.

Comment (aocenas) [reply public/app/plugins/datasource/influxdb/datasource.ts:325]: Seems like there is a bit more in v2 https://v2.docs.influxdata.com/v2.0/api/#operation/PostQuery so I wonder if we actually support v2 or not.

In any case there is a TS official client https://github.com/influxdata/influxdb-client-js so maybe you can check how do they handle the errors or check if they have response types we could borrow.

Comment (Estrax) [reply public/app/plugins/datasource/influxdb/datasource.ts:325]: Yes, there are three types of errors in their client:
1. the generic Error having only `code` and `message` fields,
2. LineProtocolError that extends it with additional `op`, `err` stack and `line` number,
3. LineProtocolLengthError that extends the generic error with `maxLength` property.
But pretty much everything is still being returned in an error message anyway.

Comment (Estrax) [reply public/app/plugins/datasource/influxdb/datasource.ts:325]: Yes, there are three types of errors in their client:
1. the generic Error having only `code` and `message` fields,
2. LineProtocolError that extends it with additional `op`, `err` stack and `line` number,
3. LineProtocolLengthError that extends the generic error with `maxLength` property.

But pretty much everything is still being returned in an error message anyway.

**Review by aocenas — APPROVED** [review]
