### PR TITLE
ShortURL: Fix wrong creation timestamp conversion

### LINKED ISSUE #107465: ShortURL: Migrate to app platform

### PR DESCRIPTION
**Pull request by evictorero**
**What is this feature?**

The `convertToK8sResource` was wrongly converting `CreationTimestamp` and returning the epoch time. Because of this, the cleanup process was cleaning all resources because they were being created with an expired date.

Fixes https://github.com/grafana/grafana/issues/107465

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by nmarrs — APPROVED** [review]
💯

File: pkg/tests/apis/shorturl/shorturl_test.go [hunk 1]
```diff
@@ -211,6 +211,7 @@ func doDualWriteTests(t *testing.T, helper *apis.K8sTestHelper, mode grafanarest
 		found, err := client.Resource.Get(context.Background(), uid, metav1.GetOptions{})
 		require.NoError(t, err)
 		assert.Equal(t, uid, found.GetName())
+		assert.LessOrEqual(t, time.Since(found.GetCreationTimestamp().Time).Seconds(), 30.0, "creation timestamp should be within last 30 seconds")
```
Comment (evictorero) [inline pkg/tests/apis/shorturl/shorturl_test.go:214]: This line would have caught the issue. The 30-second value is just long enough to avoid adding a flaky test. The important thing is to check that creationTimestamp has a reasonable value.
