### PR TITLE
Loki: Fix adding of adhoc filters to stream selector when query with empty stream selector

### LINKED ISSUE #57195: Loki: Adhoc filters are adding to the wrong place when using parser and empty stream selector

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:

This PR fixes adding of adhoc filters to stream selector when we have query with empty stream selector. Moreover, it refactors the tests to matrix testing as they were hard to read. 

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/57195

**Special notes for your reviewer**:

I recommend to look at individual commits:
1. https://github.com/grafana/grafana/commit/d3087c587dfed3ebf327fb01084a33b2d6b00490 just refactors the tests without changing any functionality. I have removed 1 test (`count({job!="foo"} < (5*1024*1024*1024) or vector(0)) - 1', 'bar', '=', 'baz')` that isn't valid logql and it was probably just copy-pasted from prometheus tests. 
2. https://github.com/grafana/grafana/commit/dd10d0ec3cf7ebc947381550dc3ce470c3ab8d82 adds tests for new functionality
3. https://github.com/grafana/grafana/commit/f3be984fcbe2529e0c7f1fa00fe6d4afffb77d98 implements the functionality

To test the PR:
1. Run loki data source `make devenv sources=loki`
2. Create new dashboard
3. Create adhoc template variables for `gdev-loki` data source. Choose variable (e.g. `place=luna`)
4. Create new logs panel and choose `gdev-loki` data source
5. Run different queries (example bellow) to and use Panel inspector if adhoc filter were correctly added
  Example of queries: 
- `{}` => `{place="luna"}` 
- `{} | logfmt` => `{place="luna"} | logfmt`
- `{} |  logfmt | label="val1"` => `{place="luna"} | logfmt | label="val1"`
- `{place="luna"}` =>  `{place="luna"}`
-  `{source="data"}` => `{source="data", place="luna"}`
- `{source="data"} | logfmt` => {source="data"} | logfmt | place=`luna`
image

 
 `

### CODE REVIEW

File: public/app/plugins/datasource/loki/modifyQuery.ts [hunk 1]
```diff
@@ -397,3 +413,19 @@ function labelExists(labels: QueryBuilderLabelFilter[], filter: QueryBuilderLabe
 function findLastPosition(positions: Position[]): Position {
   return positions.reduce((prev, current) => (prev.to > current.to ? prev : current));
 }
+
+function getAllPositionsInNodeByType(query: string, node: SyntaxNode, type: number): Position[] {
+  if (node.type.id === Matcher) {
```
Comment (svennergr) [inline public/app/plugins/datasource/loki/modifyQuery.ts:418]: I am curious, why do we need this exact `if` statement?

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/modifyQuery.ts:418]: Nice catch! This is supposed to be `if (node.type.id === type)` to catch cases where you look for  for example `Matcher` and your node is `Matcher`.  I'll add fix.

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/modifyQuery.ts]: Fixed in https://github.com/grafana/grafana/pull/57280/commits/29369bdd8d2a6a8af1418dfc690b7812ee56605e

File: public/app/plugins/datasource/loki/modifyQuery.ts [hunk 2]
```diff
@@ -40,15 +42,16 @@ export function addLabelToQuery(query: string, key: string, operator: string, va
   }
 
   const streamSelectorPositions = getStreamSelectorPositions(query);
+  const hasStreamSelectorMatchers = getMatcherInStreamPositions(query).length > 0;
```
Comment (svennergr) [inline public/app/plugins/datasource/loki/modifyQuery.ts:45]: I am wondering if we should compare the length of matchers with the length of `streamSelectorPositions`. Something like this:

```suggestion
  const hasStreamSelectorMatchers = getMatcherInStreamPositions(query).length >= streamSelectorPositions.length ;
```

The reason might be a super edge case, but I think in binary operations with two queries, e.g. 

```
sum(rate({place="luna"} [$__interval])) + sum(rate({} | json | __error__=`` [$__interval]))
```

we would potentially add the new label to the wrong place. What do you think?

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/modifyQuery.ts:45]: I don't think this would solve it because you can have 3 matchers in first stream selector and 0 in next one. But good catch, I am going to look into it.  Just to confirm if we are on the same page, in this case (when you have 1 query with empty selector + parser and 1 with non-empty) we would add adhoc filter to selector at both places, right?

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/modifyQuery.ts:45]: I'll try to see how complex it and let you know, if we should do it in separate issue or this one.

**Review by svennergr — APPROVED** [review]
Approving, if you want to merge this as it is. 
Great job on getting a fix for this so quickly 🚀

File: public/app/plugins/datasource/loki/modifyQuery.ts (hunk 2 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/modifyQuery.ts:45]: I'll create a new issue for this, because I wrote some test scenarios where it becomes more complex and I am not sure on how to solve it in those cases. 

We agreed on this `sum(rate({x="y"} [5m])) + sum(rate({} | __error__=`` [5m]))` => `sum(rate({x="y", bar="baz"} [5m])) + sum(rate({bar="baz"}| __error__=`` [5m]))`

But what about `sum(rate({x="y"} [5m])) + sum(rate({x="y"} | __error__=`` [5m]))`? Should we check if each subquery has parser/label filters as well? 

I'll create an issue and we can discuss there what the behaviour should be when you are using adhoc filters for metrics query that has different log queries.
