### PR TITLE
CloudWatch: Fix template variable intepolation for metrics queries

### LINKED ISSUE #116181: Cross-Account Cloudwatch Datasources - Account variable not interpolated when math expressions used
### What happened?

When using cloudwatch with cross-account observability enabled, and setting the account field to a variable - this variable is no longer interpolated after adding a math expression to the panel.  The raw $var_name is sent to cloudwatch causing the query to fail.  Removing the math expression restores proper functionality.

Image

### What did you expect to happen?

The account variable should be interpolated regardless of the presence of a math expression.

Image

### Did this work before?

This was only tested in 12.3.1

### How do we reproduce it?

1.  Create a cloudwatch datasource with cross-account observability enabled
2.  Create a variable to use for the AWS account ID
3.  Use this variable in the account field on a panel.  (This will work correctly at this point)
4.  Create a math expression in the panel. (This will cause the query to fail, the inspector will show the variable is no longer being interpolated)

Variables in fields other than the Account field seem to continue working correctly.

Image

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: docker-latest (12.3.1)
OS: Alpine
Browser:  Firefox (146.0.1)

### Grafana platform?

Docker

### Datasource(s)?

Cloudwatch built-in

### PR DESCRIPTION
**Pull request by kevinwcyu**
**What is this feature?**

When using CloudWatch with cross-account observability, the accountId template variable was not being interpolated when math expressions were added to a panel.

Reason for is is because we had two separate code paths for template variable interpolation:

1. Normal query execution used replaceMetricQueryVars() which included accountId
2. Expression-based queries used interpolateMetricsQueryVariables() which was missing accountId

When expressions are present, the expression datasource calls interpolateVariablesInQueries() → applyTemplateVariables() → interpolateMetricsQueryVariables(), and since accountId wasn't in that method, it was never interpolated.

This PR consolidates the two interpolation methods into a single interpolateMetricsQueryVariables() method that so metric queries only have one interpolation path. This is similar to what was done for [CloudWatch Logs queries](https://github.com/grafana/grafana/pull/104041).

Note that in `datasource.ts` we now only have `applyTemplateVariables`. I removed `interpolateVariablesInQueries` from `datasource.ts` because there's already a default implementation from [DataSourceWithBackend.ts](https://github.com/grafana/grafana/blob/d2de4f95dc8cab2d95f629f26f7fd5f4b038733a/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L282) that is called when generating a link to link.

There was also a type error from the `targetContainsTemplate` using `any` so I fixed that up too.

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #116181

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts [hunk 1]
```diff
@@ -85,21 +85,20 @@ export class CloudWatchMetricsQueryRunner extends CloudWatchRequest {
...
-  > {
+  interpolateMetricsQueryVariables(query: CloudWatchMetricsQuery, scopedVars: ScopedVars): CloudWatchMetricsQuery {
     return {
-      alias: this.replaceVariableAndDisplayWarningIfMulti(query.alias, scopedVars),
-      metricName: this.replaceVariableAndDisplayWarningIfMulti(query.metricName, scopedVars),
-      namespace: this.replaceVariableAndDisplayWarningIfMulti(query.namespace, scopedVars),
-      period: this.replaceVariableAndDisplayWarningIfMulti(query.period, scopedVars),
+      ...query,
+      region: this.templateSrv.replace(this.getActualRegion(query.region), scopedVars),
+      alias: this.templateSrv.replace(query.alias, scopedVars),
```
Comment (iwysiu) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts:92]: Is there a reason this one got swapped from `replaceVariableAndDisplayWarningIfMulti`?

**Review by iwysiu — APPROVED** [review]

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts (hunk 1 above)
Comment (kevinwcyu) [reply public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts:92]: `replaceVariableAndDisplayWarningIfMulti` only really does anything if you pass in `true` in the third argument. otherwise it's essentially just running `this.templateSrv.replace(...)` https://github.com/grafana/grafana/blob/a5174185e358d650e26e8ed59a4c4bd9aca5e6bc/public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchRequest.ts#L117-L131

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/21493983211)
- Version: 12.4.0-21493983211
