### PR TITLE
Elasticsearch: Support rendering in logs panel

### LINKED ISSUE #19789: LogsPanel: Elastic query does not work in dashbaords
Logs panel seems to expect special kind of response which for Elastic is implemented as explicit switch with `isLogsQuery` in request https://github.com/grafana/grafana/blob/90b095362052a3d2b1c92767f99a07769cfe77d0/public/app/plugins/datasource/elasticsearch/datasource.ts#L340. In dashboards though there is no way to set it (as far as I know) as `queryRunner.run` is called independent of the visualisation.

What I see as possible solutions:
- Do not do special queries. Not sure if feasible but maybe we could just say, that for this particular visualisation you need a specific query and parse single response in each visualisation.
- Allow visualisation to affect the request in some way. Something like `visualisation.modifyRequest()` that would be called before the request is run so visualisation can alter the query in some way.
- Have a preferred query editor per visualisation. The `isLogsQuery` is set in LogsQueryEditor which is one used in Explore when querying logs.

The preferred query editor solution seems to me like the best one. It is in a sense in sync with how Explore works right now, seems less invasive and keeps better separation. In the future we could allow special editor for more usecases (logs/metrics/single value/raw) selecting the best for current usecase.

### PR DESCRIPTION
**Pull request by davkal**
- add "Logs" metric query type so panels can inform the datasource that
the query is a logs query
- datasource modifies target when metric query type `logs` is detected
- then existing log result processing paths are followed

Fixes #19789

**Special notes for your reviewer**:

Select "Logs" in "Metric" field.

If there is time, I'll add some tests and number of docs display as done for Raw Docs.

### CODE REVIEW

File: public/app/plugins/datasource/elasticsearch/datasource.ts [hunk 1]
```diff
@@ -332,9 +332,11 @@ export class ElasticDatasource extends DataSourceApi<ElasticsearchQuery, Elastic
       }
 
       let queryObj;
-      if (target.isLogsQuery) {
+      if (target.isLogsQuery || queryDef.hasMetricOfType(target, 'logs')) {
```
Comment (torkelo) [inline public/app/plugins/datasource/elasticsearch/datasource.ts]: wonder if the explore logs query field can use the same query metric instead of isLogsQuery to simplify this logic.

**Review by torkelo — APPROVED** [review]
Like this approach! good until we fix the table panel to support data frames.

**Comment by davkal** [comment]
I could not easily get the limit field to work, mostly because of the field update being a second entry point into the query running. I think this needs refactoring for `logs` to simply take similar code paths to "Raw document".

**Comment by aocenas** [comment]
@davkal This works in general for 5v -7v just wondering if the group by section should do something. I assume not as we do not want to actually group anything for logs.
