### PR TITLE
Elastic: prevents datasource from throwing unexpected errors for invalid JSON

### LINKED ISSUE #24843: Invalid JSON: Unexpected token { in JSON at position 171
Running elastic query in explore on v7.0.0 (aee1438ff2), got the following error:

> Invalid JSON: Unexpected token { in JSON at position 171

Looks like the query sent to elastic was invalid perhaps?

### LINKED ISSUE #24857: Datasources: add support for non-JSON messages while parsing query responses.
Certain datasources on various edge cases (e.g. when a datasource goes down while processing the request) return responses that are not valid JSON objects (either just text or an empty response) and at the vast majority of cases Grafana throws a parsing error. For all core datasources we should add an ability to process non-JSON responses.

Should we treat all those non-JSON responses as errors? Or do we know of any cases where a non-JSON response is still a correct one? @davkal @aocenas @torkelo 

ref #24843

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Adds additional error handling to GET requests in Elasticsearch datasource. Adds response parsability checks throwing errors when the response coming back is not parsable (e.g. being a plain text or HTML - when the datasource goes down while processing the request).

**Which issue(s) this PR fixes**:

Fixes #24843 and fixes #24857

### CODE REVIEW

File: public/app/plugins/datasource/elasticsearch/datasource.ts [hunk 1]
```diff
@@ -216,8 +226,18 @@ export class ElasticDatasource extends DataSourceApi<ElasticsearchQuery, Elastic
     const payload = angular.toJson(header) + '\n' + angular.toJson(data) + '\n';
 
     return this.post('_msearch', payload).then((res: any) => {
+      let parsedRes = undefined;
+      if (typeof res !== 'object') {
```
Comment (aocenas) [inline public/app/plugins/datasource/elasticsearch/datasource.ts:230]: I am not exactly sure what are we doing here. From the issue I thought that the problem was that elastic response wasn't json but we tried to parse it resulting in parsing error. Now we seem to actually add the parsing and then just again throw the parsing error. Not sure what is a purpose of that.

File: public/app/plugins/datasource/elasticsearch/datasource.ts [hunk 2]
```diff
@@ -216,8 +226,18 @@ export class ElasticDatasource extends DataSourceApi<ElasticsearchQuery, Elastic
...
+        try {
+          parsedRes = JSON.parse(res);
+        } catch (err) {
+          throw err;
```
Comment (aocenas) [inline public/app/plugins/datasource/elasticsearch/datasource.ts:234]: Is there a reason for catching and immediately throwing the error? Seems like we could just not have a try catch here.

File: public/app/plugins/datasource/elasticsearch/datasource.test.ts [hunk 3]
```diff
@@ -274,6 +274,85 @@ describe('ElasticDatasource', function(this: any) {
...
+          alias: '$varAlias',
+          bucketAggs: [{ type: 'date_histogram', field: '@timestamp', id: '1' }],
+          metrics: [{ type: 'count', id: '1' }],
+          query: 'escape\\:test',
+        },
+      ],
+    };
+
+    createDatasource({
+      url: 'http://es.com',
```
Comment (s-h-a-d-o-w) [inline public/app/plugins/datasource/elasticsearch/datasource.test.ts:294]: As we just spoke about, this should probably be changed, since `es.com` doesn't have anything to do with elasticsearch.
I also wonder whether it should look like a real URL at all. Because when looking at these tests, it might be good to convey to whoever is reading them that this `url` doesn't actually mean anything, since we mock the responses anyway.

Comment (Estrax) [reply public/app/plugins/datasource/elasticsearch/datasource.test.ts]: Replaced with `http://elasticsearch.local`.

**Review by s-h-a-d-o-w — APPROVED** [review]
