### PR TITLE
Templating: Fix recursive loop of template variable queries when changing ad-hoc-variable 

### LINKED ISSUE #26101: When viewing template variables, Grafana can easily get caught in a rapid, endless loop of trying to refresh every panel on the dashboard
This is 100% reproduceable on the live demo site/any dashboard with template variables. For example: https://play.grafana.org/d/000000002/influxdb-templated

**What happened**: When trying to edit template variables, Grafana started spamming out thousands of queries in an attempt to refresh every panel many times over (despite none of them being visible at the time).

**What you expected to happen**: For no refresh call to be sent out when in the dashboard edit view, the panels to register as not visible, and (failing all of that) for each panel to only try to refresh once.

**How to reproduce it (as minimally and precisely as possible)**: After changing a template variable value and seeing the URL update to reflect that change, go into the dashboard options page, which defaults you to "general", and then switch over to view "Variables". At this point the page will appear to hang, Dev Tools will reveal hundreds, or even thousands of requests being made to your datasource in rapid succession.

**Anything else we need to know?**: This is very easy to reproduce and seems very, very bad. Not only does it hang the browser, it hammers your datasources.

**Environment**:
- Grafana version: 7.0.5
- Data source type & version: Seen with ES and InfluxDB
- OS Grafana is installed on: Windows and whatever the Live demo site runs on

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #26101

### CODE REVIEW

File: packages/grafana-ui/src/components/Segment/SegmentAsync.tsx [hunk 1]
```diff
@@ -29,8 +29,10 @@ export function SegmentAsync<T>({
     return (
       <Label
         onClick={async () => {
+          console.log('loading');
```
Comment (dprokop) [inline packages/grafana-ui/src/components/Segment/SegmentAsync.tsx:32]:
```suggestion
```

File: packages/grafana-ui/src/components/Segment/SegmentAsync.tsx [hunk 2]
```diff
@@ -31,6 +31,7 @@ export function SegmentAsync<T>({
         onClick={async () => {
           setSelectPlaceholder('Loading options...');
           const opts = await loadOptions();
+          console.log('loading', opts);
```
Comment (dprokop) [inline packages/grafana-ui/src/components/Segment/SegmentAsync.tsx:34]:
```suggestion
```
