### PR TITLE
Correlations: Add better handling to correlation type and update documentation

### LINKED ISSUE #106520: Correlations: Ability to add `external` correlations via provisioning
## **Why is this needed**:

Currently, external correlations can only be added via the Grafana UI.

According to the [correlation docs](https://grafana.com/docs/grafana/latest/administration/correlations/create-a-new-correlation/#create-a-correlation-with-provisioning):
> config.type
> Correlation type. “query” is the only supported type at the moment

Attempting add `config.type: external` results in the following error.
```
Error: ✗ Datasource provisioning error: invalid correlation config type: "external"
```

## **What would you like to be added**:

The ability specify `config.type: external` with a `config.target.url` that functions the same as if the correlation was created in the UI. 

## **Who is this feature for?**

Grafana users that manage datasources via provisioning

### PR DESCRIPTION
**Pull request by gelicia**
**What is this feature?**

When we added the external correlation type, we moved the type out of the "config" block and to the root of the correlation. The typing of this when creating a new correlation was not enumerating correctly, and the JSON would interpret a missing value as an empty string and would throw an error inappropriately. Both of these are corrected.

Additionally, this updates the example correlation provisioning yaml to have the config value in the correct place and adds an explicit example for an external correlation.

**Why do we need this feature?**

External correlations need the ability to be added via provisioning

**Which issue(s) does this PR fix?**:

Fixes #106520

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: pkg/services/provisioning/datasources/datasources.go [hunk 1]
```diff
@@ -194,9 +194,12 @@ func (dc *DatasourceProvisioner) applyChanges(ctx context.Context, configPath st
 func makeCreateCorrelationCommand(correlation map[string]any, SourceUID string, OrgId int64) (correlations.CreateCorrelationCommand, error) {
 	// we look for a correlation type at the root if it is defined, if not use default
 	// we ignore the legacy config.type value - the only valid value at that version was "query"
-	var corrType = correlation["type"]
-	if corrType == nil || corrType == "" {
-		corrType = correlations.CorrelationType("query")
+	var corrTypeStr = correlation["type"]
```
Comment (gelicia) [inline pkg/services/provisioning/datasources/datasources.go:197]: Is there a better way in go to handle string to an enumerated string?

File: pkg/services/provisioning/datasources/datasources.go [hunk 2]
```diff
@@ -230,7 +233,7 @@ func makeCreateCorrelationCommand(correlation map[string]any, SourceUID string,
 		}
 
 		// config.type is a deprecated place for this value. We will default it to "query" for legacy purposes but non-query correlations should have type outside of config
-		if config.Type != correlations.CorrelationType("query") {
+		if config.Type != "" && config.Type != correlations.CorrelationType("query") {
 			return correlations.CreateCorrelationCommand{}, correlations.ErrInvalidConfigType
```
Comment (ifrost) [inline pkg/services/provisioning/datasources/datasources.go]: Would it make sense to change the error message in that error?

A the moment it's 

```
	ErrInvalidConfigType             = errors.New("correlation contains non default value in config.type")
```

Maybe it could say config.type is deprecated?

Comment (gelicia) [reply pkg/services/provisioning/datasources/datasources.go]: Okay, I changed the error and added better instructions around how to fix it

**Review by ifrost — APPROVED** [review]
