### PR TITLE
Dashboard: Fixed issue changing a panel from transparent back to normal in panel editor

### LINKED ISSUE #24391: PanelEdit: Unable to save transparent state
1) Create panel, toggle transparent mode in panel settings (under title & description in side pane)
2) Go back to dashboard, save dashboard
3) Go into panel edit, untoggle transparent option
4) Go back via apply or arrow button,  panel still transparent

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #24391

Also fixes issues with maxDataPoints & min interval (interval in the model) was not preserved when switching panel type. And an issue with max data points not being parsed as a number in the model & input.

### CODE REVIEW

File: public/app/features/dashboard/state/PanelModel.ts [hunk 1]
```diff
@@ -146,33 +149,22 @@ export class PanelModel implements DataConfigSource {
...
 
   /** Given a persistened PanelModel restores property values */
   restoreModel(model: any) {
     // Start with clean-up
-    for (const property of Object.keys(this)) {
-      if (notPersistedProperties[property]) {
-        continue;
-      }
-
-      if (mustKeepProps[property]) {
```
Comment (hugohaggmark) [inline public/app/features/dashboard/state/PanelModel.ts:164]: Why does the check for mustKeepProps[property] not apply any longer?

**Review by hugohaggmark — APPROVED** [review]
LGTM! Not sure I follow why `onFieldConfigsChange` has been removed and Ieft another comment that you might consider.

File: public/app/features/dashboard/state/PanelModel.ts (hunk 1 above)
Comment (torkelo) [reply public/app/features/dashboard/state/PanelModel.ts:164]: This clause here was wrong, the mustKeepProps is only what properties should be preserved when switching between panel types. Here what we want to do is basically remove ALL delete all non peristed properties and then re-add properties from the passed in model
