### PR TITLE
Azure Monitor: Include datasource ref when interpolating variables

### LINKED ISSUE #48877: AzureMonitor: Store reference to datasource UID in queries
**What happened**:

Recorded queries (enterprise feature) require a reference to the data source UID in the request for it to work. At the moment, only the data source ID is stored for Azure Monitor queries. See more info in this [link](https://github.com/grafana/grafana-enterprise/pull/3266).

For reference, the DataSource ref is [already part of the DataQuery contract](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/query.ts#L53), but it's optional to set. 

**What you expected to happen**:

Recorded queries to work.

**How to reproduce it (as minimally and precisely as possible)**:

See the referenced PR.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by kevinwcyu**
**What this PR does / why we need it**:
When recorded queries are created, it calls the `interpolateVariablesInQueries` function of the datasource. It expects a datasource ref to be included in the query.

This PR adds the datasource ref to the query when variables are interpolated.

**Which issue(s) this PR fixes**:

Fixes #48877

**Special notes for your reviewer**:

### CODE REVIEW

**Review by iwysiu — APPROVED** [review]
lgtm!

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/datasource.ts [hunk 1]
```diff
@@ -203,7 +203,10 @@ export default class Datasource extends DataSourceApi<AzureMonitorQuery, AzureDa
       }
 
       const ds = this.pseudoDatasource[query.queryType];
-      return ds?.applyTemplateVariables(query, scopedVars) ?? query;
+      return {
+        datasource: ds?.getRef(),
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/datasource.ts:207]: I think that a better place for doing this is in the `query` method (that we know for sure it will be executed in all the cases). In the loop that starts at line 71 we are already doing some modifications to the query targets, we can se the datasource ref there.

Also, this file has no coverage, it's a good moment to start adding some tests and create the necessary mocks and test structures :)

Comment (kevinwcyu) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/datasource.ts:207]: `query` doesn't get executed for recorded queries.

`DataSourceWithBackend`'s `query` already sets the datasource ref https://github.com/grafana/grafana/blob/1d7d8bbf960a77c9784dccf664f844f8d9d7bf80/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L144

Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/datasource.ts:207]: This relates to my PR (#49642), in that PR I've spread all original properties of the query. I wonder if that change should be made here instead, thoughts?

Comment (kevinwcyu) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/datasource.ts:207]: Looking at the description from https://github.com/grafana/grafana/issues/49641

> Azure monitor queries that are referenced in an expression query fail as the datasource is not set (the same would also be true for a log query or resource graph query).

It sounds like this PR would fix that as well. Is that correct, or do you need the other properties of the query as well?

Comment (andresmgot) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/datasource.ts:207]: Right, I can confirm that this also fixes #49641

Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/datasource.ts:207]: It would, my question is more are there any other query properties that should be here? Or should we be spreading the whole original query and only overriding the properties as needed. So it'd be something like:
```
return {
   ...query,
   ...(ds?.applyTemplateVariables(query, scopedVars) ?? query),
}

Comment (andresmgot) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/datasource.ts:207]: > `query` doesn't get executed for recorded queries.

That's surprising :thinking: 

> It would, my question is more are there any other query properties that should be here? Or should we be spreading the whole original query and only overriding the properties as needed. So it'd be something like:
> 
> ```
> return {
>    ...query,
>    ...(ds?.applyTemplateVariables(query, scopedVars) ?? query),
> }
> ```

Yeah, the problem is that `applyTemplateVariables` is removing some properties from `query` which is shouldn't IMO. You fixed that in your PR so I would merge both, even though just this one is enough to fix the issue.

**Review by andresmgot — APPROVED** [review]
LGTM!
