### PR TITLE
Docker: Build and use musl-based binaries in alpine images to resolve glibc incompatibility issues

### LINKED ISSUE #19585: Docker: ARM images doesn't work since v6.4.x
**What happened**:
Grafana 6.4.X ARM in Docker does not work on Raspbian Buster.
Error message when trying to run the container:
/run.sh: line 80: /usr/share/grafana/bin/grafana-server: No such file or directory

**What you expected to happen**:
Obvious: Grafana runs without error.

**How to reproduce it (as minimally and precisely as possible)**:
docker run grafana/grafana

**Anything else we need to know?**:
Error is caused by a lib-c mismatch: Grafana is build with ld-linux-armhf.so, but Alpine base image contains only ld-musl-armv7.so.

**Environment**:
- Grafana version: 6.4.X
- Data source type & version: InfluxDB
- OS Grafana is installed on: Raspbian Buster with Docker
- User OS & Browser: Windows / Firefox
- Grafana plugins: None
- Others: None

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
In order to solve #19585, this PR changes the build pipeline to make also [musl](https://www.musl-libc.org) Linux binaries, and to use those binaries in Docker image builds.

**Which issue(s) this PR fixes**:

Fixes #19585.

### CODE REVIEW

**Comment by marefr** [comment]
Seems like a great start :+1: Let us know whenever you want to discuss it or need help.

**Comment by aknuds1** [comment]
> Seems like a great start 👍 Let us know whenever you want to discuss it or need help.

Thanks @marefr. I'm having some trouble figuring out a broken step in the build pipeline now, where `grunt package` doesn't copy the server binaries where it should. I'll let you know when I could use some input.

**Comment by aknuds1** [comment]
@marefr I think this branch successfully builds musl binaries now, although I could use some extra pairs of eyes to inspect my changes. The next step should be to copy musl binaries into Docker image builds.

File: scripts/build/build.sh [hunk 1]
```diff
@@ -1,4 +1,7 @@
 #!/bin/bash
+
+# shellcheck disable=SC2086
```
Comment (aknuds1) [inline scripts/build/build.sh]: I had to disable enforcing double quotes around variable expansion, since it resulted in a bug of several flags being passed as one to build.go. build-all.sh already does this, I can't understand how build.sh ever worked with the aforementioned bug.

File: scripts/build/build.sh [hunk 2]
```diff
@@ -69,17 +75,20 @@ function build_backend_linux_amd64() {
   if [ ! -d "dist" ]; then
     mkdir dist
   fi
-  CC=${CCX64} go run build.go "${OPT}" build
+  CC=${CCX64} go run build.go ${OPT} build
```
Comment (aknuds1) [inline scripts/build/build.sh]: I'm here removing the quotes around `${OPT}` to prevent multiple flags (in `$OPT`) from being passed as a single argument.

**Comment by marefr** [comment]
This looks promising. Great work :+1: Gonna take it for a spin and build a dev-image

File: packaging/docker/Dockerfile [hunk 3]
```diff
@@ -14,46 +14,46 @@ ARG GF_UID="472"
...
+  rm -rf /tmp/* && \
+  apk del --no-cache phantomjs-utils; \
+  fi
 
 COPY --from=0 /tmp/grafana "$GF_PATHS_HOME"
 
 RUN mkdir -p "$GF_PATHS_HOME/.aws" && \
-    addgroup -S -g $GF_GID grafana && \
-    adduser -S -u $GF_UID -G grafana grafana && \
-    mkdir -p "$GF_PATHS_PROVISIONING/datasources" \
```
Comment (xlson) [inline packaging/docker/Dockerfile]: I think the removal of custom indentation for the mkdir paths makes these lines a bit harder to read. Not sure if this is intentional or just the result of a reformat of this file, but I would consider keeping some of the custom formattings for readability.

File: scripts/build/build.sh (hunk 1 above)
Comment (xlson) [reply scripts/build/build.sh]: That's worrying. Good find.

**Review by xlson — COMMENTED** [review]
Great work. I couldn't find anything major, some formatting that might be nice to keep.

Regarding the failing build, the reason is that the musl packaging hasn't been added to the `    package_linux_amd64` method of `build.sh`, which is the only thing that will run with --fast --package-only

**Comment by marefr** [comment]
It's successfully building now https://circleci.com/workflow-run/c5fc2cdf-3140-4540-a7f6-17ad418b3fda

Downloaded the artifact grafana-latest.linux-x64-musl.tar.gz and built a docker image and started it successfully. However, the frontend isn't fully built so I get an error of "html/template: "index" is undefined" when trying to browse Grafana in browser.

File: packaging/docker/Dockerfile (hunk 3 above)
Comment (aknuds1) [reply packaging/docker/Dockerfile]: @xlson, possibly this was done automatically by VS Code, I can't seem to turn this "feature" off for Dockerfiles 😔

**Comment by aknuds1** [comment]
> It's successfully building now https://circleci.com/workflow-run/c5fc2cdf-3140-4540-a7f6-17ad418b3fda
> 
> Downloaded the artifact grafana-latest.linux-x64-musl.tar.gz and built a docker image and started it successfully. However, the frontend isn't fully built so I get an error of "html/template: "index" is undefined" when trying to browse Grafana in browser.

@marefr Is the front-end error simply because it's a fast build? It's not particular to this PR?

**Comment by marefr** [comment]
> Is the front-end error simply because it's a fast build? It's not particular to this PR?

@aknuds1 yeah probably. Will run manually/locally tomorrow and verify everything works as expected.

**Comment by marefr** [comment]
Successfully built Grafana and Grafana Enterprise binaries using updated build container:

<details><summary>Details</summary>

```
-rw-rw-r-- 1 marcus 32439557 okt 16 15:52 grafana-6.5.0-pre.aarch64.rpm
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-6.5.0-pre.aarch64.rpm.sha256
-rw-rw-r-- 1 marcus 60385392 okt 16 15:43 grafana_6.5.0-pre_amd64.deb
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana_6.5.0-pre_amd64.deb.sha256
-rw-rw-r-- 1 marcus 32632516 okt 16 15:45 grafana_6.5.0-pre_arm64.deb
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana_6.5.0-pre_arm64.deb.sha256
-rw-rw-r-- 1 marcus 32513700 okt 16 15:44 grafana_6.5.0-pre_armhf.deb
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana_6.5.0-pre_armhf.deb.sha256
-rw-rw-r-- 1 marcus 32329759 okt 16 15:52 grafana-6.5.0-pre.armhfp.rpm
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-6.5.0-pre.armhfp.rpm.sha256
-rw-rw-r-- 1 marcus 49145652 okt 16 15:45 grafana-6.5.0-pre.darwin-amd64.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-6.5.0-pre.darwin-amd64.tar.gz.sha256
-rw-rw-r-- 1 marcus 60911850 okt 16 15:44 grafana-6.5.0-pre.linux-amd64-musl.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-6.5.0-pre.linux-amd64-musl.tar.gz.sha256
-rw-rw-r-- 1 marcus 60175505 okt 16 15:43 grafana-6.5.0-pre.linux-amd64.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-6.5.0-pre.linux-amd64.tar.gz.sha256
-rw-rw-r-- 1 marcus 33273396 okt 16 15:45 grafana-6.5.0-pre.linux-arm64-musl.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-6.5.0-pre.linux-arm64-musl.tar.gz.sha256
-rw-rw-r-- 1 marcus 32471052 okt 16 15:45 grafana-6.5.0-pre.linux-arm64.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-6.5.0-pre.linux-arm64.tar.gz.sha256
-rw-rw-r-- 1 marcus 32382036 okt 16 15:44 grafana-6.5.0-pre.linux-armv6.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-6.5.0-pre.linux-armv6.tar.gz.sha256
-rw-rw-r-- 1 marcus 33119260 okt 16 15:45 grafana-6.5.0-pre.linux-armv7-musl.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-6.5.0-pre.linux-armv7-musl.tar.gz.sha256
-rw-rw-r-- 1 marcus 32368801 okt 16 15:44 grafana-6.5.0-pre.linux-armv7.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-6.5.0-pre.linux-armv7.tar.gz.sha256
-rw-rw-r-- 1 marcus 55746881 okt 16 15:46 grafana-6.5.0-pre.windows-amd64.zip
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-6.5.0-pre.windows-amd64.zip.sha256
-rw-rw-r-- 1 marcus 59970519 okt 16 15:52 grafana-6.5.0-pre.x86_64.rpm
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-6.5.0-pre.x86_64.rpm.sha256
-rw-rw-r-- 1 marcus 59970519 okt 16 15:52 grafana-latest-1.x86_64.rpm
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-latest-1.x86_64.rpm.sha256
-rw-rw-r-- 1 marcus 60385392 okt 16 15:46 grafana_latest_amd64.deb
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana_latest_amd64.deb.sha256
-rw-rw-r-- 1 marcus 33273396 okt 16 15:46 grafana-latest.linux-arm64-musl.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-latest.linux-arm64-musl.tar.gz.sha256
-rw-rw-r-- 1 marcus 32471052 okt 16 15:46 grafana-latest.linux-arm64.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-latest.linux-arm64.tar.gz.sha256
-rw-rw-r-- 1 marcus 32382036 okt 16 15:46 grafana-latest.linux-armv6.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-latest.linux-armv6.tar.gz.sha256
-rw-rw-r-- 1 marcus 33119260 okt 16 15:46 grafana-latest.linux-armv7-musl.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-latest.linux-armv7-musl.tar.gz.sha256
-rw-rw-r-- 1 marcus 32368801 okt 16 15:46 grafana-latest.linux-armv7.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-latest.linux-armv7.tar.gz.sha256
-rw-rw-r-- 1 marcus 60911850 okt 16 15:46 grafana-latest.linux-x64-musl.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-latest.linux-x64-musl.tar.gz.sha256
-rw-rw-r-- 1 marcus 60175505 okt 16 15:46 grafana-latest.linux-x64.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-latest.linux-x64.tar.gz.sha256
-rw-rw-r-- 1 marcus 32525934 okt 16 15:44 grafana-rpi_6.5.0-pre_armhf.deb
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana-rpi_6.5.0-pre_armhf.deb.sha256
-rw-r--r-- 1 marcus        9 okt 16 15:43 grafana.version
-rw-r--r-- 1 marcus       65 okt 16 15:52 grafana.version.sha256

Enterprise:
-rw-rw-r-- 1 marcus 79256158 okt 16 16:15 grafana-enterprise_6.5.0-pre_amd64.deb
-rw-r--r-- 1 marcus       65 okt 16 16:52 grafana-enterprise_6.5.0-pre_amd64.deb.sha256
-rw-rw-r-- 1 marcus 79766280 okt 16 16:16 grafana-enterprise-6.5.0-pre.linux-amd64-musl.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 16:52 grafana-enterprise-6.5.0-pre.linux-amd64-musl.tar.gz.sha256
-rw-rw-r-- 1 marcus 79037838 okt 16 16:15 grafana-enterprise-6.5.0-pre.linux-amd64.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 16:52 grafana-enterprise-6.5.0-pre.linux-amd64.tar.gz.sha256
-rw-rw-r-- 1 marcus 56583050 okt 16 16:16 grafana-enterprise-6.5.0-pre.windows-amd64.zip
-rw-r--r-- 1 marcus       65 okt 16 16:52 grafana-enterprise-6.5.0-pre.windows-amd64.zip.sha256
-rw-rw-r-- 1 marcus 78827455 okt 16 16:51 grafana-enterprise-6.5.0-pre.x86_64.rpm
-rw-r--r-- 1 marcus       65 okt 16 16:52 grafana-enterprise-6.5.0-pre.x86_64.rpm.sha256
-rw-rw-r-- 1 marcus 78827455 okt 16 16:52 grafana-latest-1.x86_64.rpm
-rw-r--r-- 1 marcus       65 okt 16 16:52 grafana-latest-1.x86_64.rpm.sha256
-rw-rw-r-- 1 marcus 79256158 okt 16 16:16 grafana_latest_amd64.deb
-rw-r--r-- 1 marcus       65 okt 16 16:52 grafana_latest_amd64.deb.sha256
-rw-rw-r-- 1 marcus 79766280 okt 16 16:16 grafana-latest.linux-x64-musl.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 16:52 grafana-latest.linux-x64-musl.tar.gz.sha256
-rw-rw-r-- 1 marcus 79037838 okt 16 16:16 grafana-latest.linux-x64.tar.gz
-rw-r--r-- 1 marcus       65 okt 16 16:52 grafana-latest.linux-x64.tar.gz.sha256
-rw-r--r-- 1 marcus        9 okt 16 16:14 grafana.version
-rw-r--r-- 1 marcus       65 okt 16 16:52 grafana.version.sha256
```
</details>

Now on to building docker images and verify everything works as expected.

**Comment by aknuds1** [comment]
@marefr Yay, well done!

**Comment by marefr** [comment]
Think I've managed to build and test docker images for grafana (amd64, arm32v7, arm64v8) and Grafana Enterprise (amd64) using a virtual Ubuntu 18.04 machine. Used the scripts in packaging/docker and followed CircleCI config to follow the same steps as in CI. Verified that they work as expected:
- Image rendering using phantomjs on amd64 (not arm and only works if I use the host network which is same as on my local machine lately for some dns/alpine reason)
- grafana-cli change admin password and download plugins
- Checking dynamic linking

**grafana grafana/grafana:6.5.0-pre:**
```bash
bash-5.0$ uname -a
Linux a4ff90c0f467 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 
bash-5.0$ ldd bin/grafana-cli
        /lib/ld-musl-x86_64.so.1 (0x7f3a1c4da000)
        libc.so => /lib/ld-musl-x86_64.so.1 (0x7f3a1c4da000)
bash-5.0$ ldd bin/grafana-server
        /lib/ld-musl-x86_64.so.1 (0x7f2fc096c000)
        libc.so => /lib/ld-musl-x86_64.so.1 (0x7f2fc096c000)
```

**grafana/grafana-arm32v7-linux:6.5.0-pre:**
```bash
bash-5.0$ uname -a
Linux 4c1713ea2d3d 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 armv7l 
bash-5.0$ ldd bin/grafana-cli
        /lib/ld-musl-armhf.so.1 (0xf6f78000)
        libc.so => /lib/ld-musl-armhf.so.1 (0xf6f78000)
bash-5.0$ ldd bin/grafana-server
        /lib/ld-musl-armhf.so.1 (0xf6f78000)
        libc.so => /lib/ld-musl-armhf.so.1 (0xf6f78000)
```

**grafana/grafana-arm64v8-linux:6.5.0-pre:**
```bash
bash-5.0$ uname -a
Linux 713856f25cf3 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 aarch64 
bash-5.0$ ldd bin/grafana-cli
        /lib/ld-musl-aarch64.so.1 (0x4000000000)
        libc.so => /lib/ld-musl-aarch64.so.1 (0x4000000000)
bash-5.0$ ldd bin/grafana-server
        /lib/ld-musl-aarch64.so.1 (0x4000000000)
        libc.so => /lib/ld-musl-aarch64.so.1 (0x4000000000)
```

**grafana grafana/grafana-enterprise:6.5.0-pre:**
```bash
bash-5.0$ uname -a
Linux efra 4.4.0-165-generic #193-Ubuntu SMP Tue Sep 17 17:42:52 UTC 2019 x86_64 Linux
bash-5.0$ ldd bin/grafana-cli
        /lib/ld-musl-x86_64.so.1 (0x7f1cf99ea000)
        libc.so => /lib/ld-musl-x86_64.so.1 (0x7f1cf99ea000)
bash-5.0$ ldd bin/grafana-server
        /lib/ld-musl-x86_64.so.1 (0x7f8a988b1000)
        libc.so => /lib/ld-musl-x86_64.so.1 (0x7f8a988b1000)
```

@xlson @aknuds1 anything I may possibly have missed to test/verify?

**Comment by aknuds1** [comment]
@marefr I can't think of too many ways to tests, but have you compared image sizes, out of curiosity?

**Comment by xlson** [comment]
@marefr great work. One thing we could do is to push the images to docker hub with custom tags and ask the community to test them. I would feel a lot more confident if we had these images tested on actual raspberry pies.

**Comment by marefr** [comment]
@aknuds1 

image sizes on virtual machine:
```
grafana/grafana-arm64v8-linux   6.5.0-pre           99cbe3d185af        17 hours ago        117MB
grafana/grafana-arm32v7-linux   6.5.0-pre           7d9d15c6b249        17 hours ago        106MB
grafana/grafana                 6.5.0-pre           c9d6001ea74e        17 hours ago        207MB
```

v6.4.3 images on local machine:
```
grafana/grafana-arm64v8-linux   latest              bd1a44189fda        5 days ago          122MB
grafana/grafana-arm32v7-linux   latest              1dfc3422b689        5 days ago          109MB
grafana/grafana     latest              a532fe3b344a        5 days ago          206MB
```

**Comment by marefr** [comment]
@xlson good idea :+1: I guess we should do the manifest thing as well - is there anything to look out for there or to take into consideration before pushing?

**Comment by xlson** [comment]
Not that I can think of.

**Comment by KamilLenica** [comment]
I can do test on RasPi 4 if You share a tag and test scope

**Comment by marefr** [comment]
Pushed a tag named `dev-musl` to grafana docker hub repositories. No manifest have been pushed to grafana/grafana so if you want to try arm or arm64 you have to manually specify correct repository, see below.

[linux/amd64](https://hub.docker.com/r/grafana/grafana/tags?page=1):
`docker run <args> grafana/grafana:dev-musl`

[linux/arm64](https://hub.docker.com/r/grafana/grafana-arm64v8-linux/tags):
`docker run <args> grafana/grafana-arm64v8-linux:dev-musl`

[linux/arm](https://hub.docker.com/r/grafana/grafana-arm32v7-linux/tags):
`docker run <args> grafana/grafana-arm32v7-linux:dev-musl`

@KamilLenica guess you should use linux/arm64 for Raspberry Pi 4. Please note that these images are based on current developer branch (master/Grafana v6.5.0-pre) of Grafana so if you want to test with an existing Grafana installation please remember to [backup your existing data](https://grafana.com/docs/installation/upgrading/).

**Test scope:**
- Verify that container can successfully run and using `docker logs <image name>` shouldn't output anything unexpected like errors.
- If possible, try to add/connect to a datasource and render a dashboard/panel
- Optional: Verify that you can download plugins
- Provide feedback in issue or this PR by making a comment

Will cross-post this in the issue and ask for more users to help out test. Let me know if you need any help. Appreciate the help.

**Comment by KamilLenica** [comment]
Raspberry Pi has 64bit CPU indeed, but kernel is still 32bit so i used that

` docker run -d  --name="grafana-test" --restart unless-stopped -p 3000:3000 -v grafana-storage:/var/lib/grafana grafana/grafana-arm32v7-linux:dev-musl
`
Downloading plugins works
`bash-5.0$ grafana-cli plugins install raintank-worldping-app
installing raintank-worldping-app @ 1.2.6
from: https://grafana.com/api/plugins/raintank-worldping-app/versions/1.2.6/download
into: /var/lib/grafana/plugins

✔ Installed raintank-worldping-app successfully

Restart grafana after installing plugins . <service grafana-server restart>`

Initial configuration and creation of dashboard with InfluxDB as source works, nothing unexpected in container logs.
`t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Add column tags to annotation table"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Create annotation_tag table v2"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Add unique index annotation_tag.annotation_id_tag_id"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Update alert annotations and set TEXT to empty"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Add created time to annotation table"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Add updated time to annotation table"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for created in annotation table"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for updated in annotation table"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Convert existing annotations from seconds to milliseconds"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Add epoch_end column"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for epoch_end"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Make epoch_end the same as epoch"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Move region to single row"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="create test_data table"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard_version table v1"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="add index dashboard_version.dashboard_id"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index dashboard_version.dashboard_id and dashboard_version.version"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Set dashboard version to 1 where 0"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="save existing dashboard data in dashboard_version table v1"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="alter dashboard_version.data to mediumtext v1"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="create team table"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="add index team.org_id"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index team_org_id_name"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="create team member table"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="add index team_member.org_id"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index team_member_org_id_team_id_user_id"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Add column email to team table"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Add column external to team_member table"


t=2019-10-22T15:24:49+0000 lvl=info msg="Executing migration" logger=migrator id="Add column permission to team_member table"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard acl table"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="add index dashboard_acl_dashboard_id"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index dashboard_acl_dashboard_id_user_id"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index dashboard_acl_dashboard_id_team_id"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="save default acl rules in dashboard_acl table"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="create tag table"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="add index tag.key_value"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="create login attempt table"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="add index login_attempt.username"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="drop index IDX_login_attempt_username - v1"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table login_attempt to login_attempt_tmp_qwerty - v1"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="create login_attempt v2"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_login_attempt_username - v2"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="copy login_attempt v1 to v2"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="drop login_attempt_tmp_qwerty"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="create user auth table"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_user_auth_auth_module_auth_id - v1"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="alter user_auth.auth_id to length 190"


t=2019-10-22T15:24:50+0000 lvl=info msg="Executing migration" logger=migrator id="Add OAuth access token to user_auth"


t=2019-10-22T15:24:51+0000 lvl=info msg="Executing migration" logger=migrator id="Add OAuth refresh token to user_auth"


t=2019-10-22T15:24:51+0000 lvl=info msg="Executing migration" logger=migrator id="Add OAuth token type to user_auth"


t=2019-10-22T15:24:51+0000 lvl=info msg="Executing migration" logger=migrator id="Add OAuth expiry to user_auth"


t=2019-10-22T15:24:51+0000 lvl=info msg="Executing migration" logger=migrator id="Add index to user_id column in user_auth"


t=2019-10-22T15:24:51+0000 lvl=info msg="Executing migration" logger=migrator id="create server_lock table"


t=2019-10-22T15:24:51+0000 lvl=info msg="Executing migration" logger=migrator id="add index server_lock.operation_uid"


t=2019-10-22T15:24:51+0000 lvl=info msg="Executing migration" logger=migrator id="create user auth token table"


t=2019-10-22T15:24:51+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index user_auth_token.auth_token"


t=2019-10-22T15:24:51+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index user_auth_token.prev_auth_token"


t=2019-10-22T15:24:51+0000 lvl=info msg="Executing migration" logger=migrator id="create cache_data table"


t=2019-10-22T15:24:51+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index cache_data.cache_key"


t=2019-10-22T15:24:51+0000 lvl=info msg="Created default admin" logger=sqlstore user=admin


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing HTTPServer" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing InternalMetricsService" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing RemoteCache" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing QuotaService" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing ServerLockService" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing UserAuthTokenService" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing PluginManager" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Starting plugin search" logger=plugins


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing RenderingService" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing AlertEngine" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing DatasourceCacheService" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing HooksService" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing LoginService" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing SearchService" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing TracingService" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing UsageStatsService" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing CleanUpService" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing NotificationService" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing provisioningServiceImpl" logger=server


t=2019-10-22T15:24:51+0000 lvl=info msg="Backend rendering via phantomJS" logger=rendering


t=2019-10-22T15:24:51+0000 lvl=warn msg="phantomJS is deprecated and will be removed in a future release. You should consider migrating from phantomJS to grafana-image-renderer plugin." logger=rendering


t=2019-10-22T15:24:51+0000 lvl=info msg="Initializing Stream Manager"


t=2019-10-22T15:24:51+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=


t=2019-10-22T15:26:04+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.5.222.144 time_ms=0 size=29 referer=


t=2019-10-22T15:26:08+0000 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"


t=2019-10-22T15:26:08+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=401 remote_addr=10.5.222.144 time_ms=709 size=42 referer=http://10.9.124.215:3000/login


t=2019-10-22T15:26:29+0000 lvl=info msg="Successful Login" logger=http.server User=admin@localhost


t=2019-10-22T15:35:03+0000 lvl=eror msg="Failed to look up user based on cookie" logger=context error="database is locked"


t=2019-10-22T15:35:03+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/search status=401 remote_addr=10.5.222.144 time_ms=5005 size=26 referer="http://10.9.124.215:3000/dashboard/new?orgId=1&gettingstarted&from=now%2Fy&to=now"


t=2019-10-22T15:35:03+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status=401 remote_addr=10.5.222.144 time_ms=0 size=26 referer="http://10.9.124.215:3000/dashboard/new?orgId=1&gettingstarted&from=now%2Fy&to=now"


t=2019-10-22T15:35:05+0000 lvl=eror msg="Failed to look up user based on cookie" logger=context error="database is locked"


t=2019-10-22T15:35:05+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/dashboards/db/ status=401 remote_addr=10.5.222.144 time_ms=5006 size=26 referer="http://10.9.124.215:3000/dashboard/new?orgId=1&gettingstarted&from=now%2Fy&to=now"


t=2019-10-22T15:35:06+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status=401 remote_addr=10.5.222.144 time_ms=0 size=26 referer="http://10.9.124.215:3000/dashboard/new?orgId=1&gettingstarted&from=now%2Fy&to=now"


t=2019-10-22T15:35:07+0000 lvl=eror msg="Could not load alerts" logger=alerting.ruleReader error="database is locked"


t=2019-10-22T15:35:12+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/dashboards/home status=401 remote_addr=10.5.222.144 time_ms=0 size=26 referer=http://10.9.124.215:3000/


t=2019-10-22T15:35:12+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status=401 remote_addr=10.5.222.144 time_ms=0 size=26 referer=http://10.9.124.215:3000/


t=2019-10-22T15:35:12+0000 lvl=info msg="Successful Logout" logger=http.server User=


t=2019-10-22T15:35:12+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/logout status=302 remote_addr=10.5.222.144 time_ms=1 size=29 referer=http://10.9.124.215:3000/


t=2019-10-22T15:35:18+0000 lvl=info msg="Successful Login" logger=http.server User=admin@localhost


t=2019-10-22T15:35:19+0000 lvl=warn msg="Error adding avatar to cache: Item 46d229b033af06a191ff2267bca9ae56 already exists"`

Great work!

**Comment by JasonSwindle** [comment]
Howdy,

If I directly use `grafana/grafana-arm64v8-linux:dev-musl` it will work correctly, but if I use `grafana/grafana:dev-musl` I will get the error:

```
standard_init_linux.go:211: exec user process caused "exec format error"
```

My system is:

__SBC__: _RockPro64_
__CPU__: _Topology: 6-Core (2-Die) model: N/A variant-1: cortex-a72 variant-2: cortex-a53 bits: 64_
__OS__: _DietPi_ (Debian GNU/Linux 9)
__Docker__: _19.03.4_

**Comment by marefr** [comment]
Thanks a lot for the quick responses and help. Very appreciated.

**Comment by aknuds1** [comment]
Yep, thanks for helping test!

**Review by marefr — APPROVED** [review]
LGTM
