### PR TITLE
Handle onPaste because of bug in this Slate version

### LINKED ISSUE #15223: Explore cut & paste adds newline before and after selection.
When cutting and pasting queries in the explore, newlines seem to be added before and after:

l2hfqicazx

Not sure if this happens on cut or paste.

### PR DESCRIPTION
**Pull request by hugohaggmark**
Fixes #15223 by handling onPaste event because of bug in Slate

### CODE REVIEW

File: public/app/features/explore/QueryField.tsx [hunk 1]
```diff
@@ -468,6 +468,14 @@ export class QueryField extends React.PureComponent<QueryFieldProps, QueryFieldS
     );
   };
 
+  handlePaste = (event: ClipboardEvent, change: Editor) => {
```
Comment (jschill) [inline public/app/features/explore/QueryField.tsx]: Nice catch!

Do we know if this bug is confirmed by slate?

Comment (hugohaggmark) [reply public/app/features/explore/QueryField.tsx]: Later versions of Slate handles this automagically but introduce other errors/breaking changes.
