### PR TITLE
ChannelOptions: Fix showWhen failure

### LINKED ISSUE #55881: Alert channels showWhen failure
**What happened**:

the form does not display properly after setting showWhen

**What you expected to happen**:

The form is displayed normally

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by aimuz**
Signed-off-by: aimuz <mr.imuz@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/55881

Solved the problem that the form does not display properly when showWhen is set

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx [hunk 1]
```diff
@@ -29,14 +29,15 @@ export function ChannelOptions<R extends ChannelValues>({
   readOnly = false,
 }: Props<R>): JSX.Element {
   const { watch } = useFormContext<ReceiverFormValues<R>>();
-  const currentFormValues = watch() as Record<string, any>; // react hook form types ARE LYING!
+  const currentFormValues = watch(); // react hook form types ARE LYING!
```
Comment (joshhunt) [inline public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx:32]: 🤔 Can Alerting team explain why we think the react hook types are wrong? Would like to help sort this out if we can 😌

File: public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx [hunk 2]
```diff
@@ -29,14 +29,15 @@ export function ChannelOptions<R extends ChannelValues>({
...
   return (
     <>
       {selectedChannelOptions.map((option: NotificationChannelOption, index: number) => {
         const key = `${option.label}-${index}`;
         // Some options can be dependent on other options, this determines what is selected in the dependency options
         // I think this needs more thought.
-        const selectedOptionValue = currentFormValues[`${pathPrefix}settings.${option.showWhen.field}`];
+        const path = `${pathPrefix}settings.${option.showWhen.field}`.split('.');
+        const selectedOptionValue = path.reduce((o, n) => o[n], currentFormValues) as string;
```
Comment (joshhunt) [inline public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx:40]: This is generating a type error at the moment (see https://drone.grafana.net/grafana/grafana/79196/1/6) , and because you didn't run the precommit hook it also fails our linter (https://drone.grafana.net/grafana/grafana/79196/1/7) which would have preventing you from committing this in the first place.

**Review by joshhunt — COMMENTED** [review]
I'll let the Alerting team review this properly, but we don't accept `as` type assertions (or `any`) in new code written.

File: public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx (hunk 2 above)
Comment (aimuz) [reply public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx:40]: i resubmitted

File: public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx (hunk 1 above)
Comment (Clarity-89) [reply public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx:32]: From my experience `watch` doesn't work well with recursive/nested types. Upgrading to the latest version of `react-hook-form` could fix those, but it's quite a big upgrade.

**Comment by aimuz** [comment]
Hi guys, when will this get merged?

File: public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx (hunk 1 above)
Comment (aimuz) [reply public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx:32]: Will this PR be merged? I want to add a new alert channel that depends on this PR?

Comment (joeblubaugh) [reply public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx:32]: @aimuz can you please file an issue (or link to it if one exists) discussing adding another alerting channel? We need to discuss whether it makes sense to take on maintenance responsibilities for such a channel.

Comment (aimuz) [reply public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx:32]: @joeblubaugh  I created a question https://github.com/grafana/grafana/issues/55881

Comment (joeblubaugh) [reply public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx:32]: Sorry, maybe I wasn't clear. You want to add a new type of notifier in `pkg/services/ngalert/notifier/channels`, right? Please update that issue to explain what the notifier would be. Is it another messaging service like Telegram or LINE? SMS? The maintainers need to understand what we would be responsible for after such a change was merged.

Comment (aimuz) [reply public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx:32]: Please take a look https://github.com/grafana/grafana/discussions/55883
 
 Also will the current PR not be merged? Or are you trying to fix this in some other way?

Comment (joeblubaugh) [reply public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx:32]: Thanks for the update - I didn't want you to do a lot of work that wouldn't necessarily be accepted. I'll comment on that issue regarding WeCom-specific information.

I don't know about the current PR. I'll pull someone in. @gillesdemey PTAL

Comment (gillesdemey) [reply public/app/features/alerting/unified/components/receivers/form/ChannelOptions.tsx:32]: These changes look 🆗 – we don't use the `showWhen` property for any receiver currently but I've verified that these changes do make it work as intended.

As for the types, like @Clarity-89 mentioned I believe this is because `react-hook-form` doesn't do well with nested forms and gets confused about the typings.

**Review by gillesdemey — APPROVED** [review]

**Comment by gillesdemey** [comment]
Changes LGTM
