### PR TITLE
Sandbox: Fix react class components stale state

### LINKED ISSUE #70360: Investigate react class components rendering with stale state in specific situations
Related to frontend sandboxing.

### PR DESCRIPTION
**Pull request by academo**
**What is this feature?**

Fixes an issue in [plugin frontend sandbox](https://github.com/grafana/grafana/pull/68889) where react class components will always render with a stale state.

**Why do we need this feature?**

To make plugins using react class components work correctly when running inside the sandbox

**Who is this feature for?**

All grafana frontend plugin developers

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/70360

**Special notes for your reviewer:**

Please check that:

- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/plugins/sandbox/utils.ts [hunk 1]
```diff
@@ -7,3 +9,10 @@ export function isSandboxedPluginObject(value: unknown): value is SandboxedPlugi
 export function assertNever(x: never): never {
   throw new Error(`Unexpected object: ${x}. This should never happen.`);
 }
+
+export function isReactClassComponent(obj: unknown): obj is React.Component {
+  if (obj instanceof React.Component) {
+    return true;
+  }
+  return false;
```
Comment (oshirohugo) [inline public/app/features/plugins/sandbox/utils.ts:17]: maybe here you could return the result of instance of directly:
```ts
  return obj instanceof React.Component
```
since it's a boolean

Comment (academo) [reply public/app/features/plugins/sandbox/utils.ts:17]: Indeed. I was initially doing more checks here and ended up in this simplified logic. Thanks for the suggestions.

**Review by jackw — APPROVED** [review]
Took it for a spin and clock panel is working as expected. 👍
