### PR TITLE
Config: Fixes bug where timeouts for alerting was not parsed correctly

### LINKED ISSUE #16663: Image Rendering Timeout too low (2secs) ?
**What happened**:
Setting up Telegram alerts. The panel i'm alerting from can take some time to render after failing to receive the image on the alert message found errors on grafana log stating that image rendering failed, Log timestamps seem to imply that the timeout was set to 2 seconds

**What you expected to happen**:
Rendering timeout should be configurable
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
These are the relevant log entries:
`t=2019-04-17T22:46:01-0300 lvl=info msg=Rendering logger=rendering path="d-solo/ZQHR1QgZz/alerting?orgId=1&panelId=2"
t=2019-04-17T22:46:03-0300 lvl=info msg="Rendering timed out" logger=rendering
t=2019-04-17T22:46:03-0300 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2019-04-17T22:46:03-0300 lvl=eror msg="Could not close Telegram inline image." logger=alerting.notifier.telegram err="invalid argument"
t=2019-04-17T22:46:03-0300 lvl=eror msg="Could not generate Telegram message with inline image." logger=alerting.notifier.telegram err="open : no such file or directory"
`

**Environment**:
- Grafana version: 6.2.0 Nighty 4/17/19
- Data source type & version: Prometheus 2.1
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows / Chrome x86_64
- Grafana plugins:None
- Others:

### PR DESCRIPTION
**Pull request by aocenas**
Closes: #16663

Fixes how the config is parsed and also how a timeout value is computed in notifier.

### CODE REVIEW

File: pkg/services/alerting/notifier.go [hunk 1]
```diff
@@ -127,7 +127,7 @@ func (n *notificationService) uploadImage(context *EvalContext) (err error) {
 	renderOpts := rendering.Opts{
 		Width:           1000,
 		Height:          500,
-		Timeout:         time.Duration(setting.AlertingEvaluationTimeout.Seconds() * 0.9),
+		Timeout:         time.Duration(setting.AlertingEvaluationTimeout.Seconds()*0.9) * time.Second,
```
Comment (bergquist) [inline pkg/services/alerting/notifier.go]: If `setting.AlertingEvaluationTimeout` is a `time.Duration` I think 
`setting.AlertingEvaluationTimeout * 0.9` will be enough

Comment (aocenas) [reply pkg/services/alerting/notifier.go]: Hmm right even lint is complaining about that.

Comment (aocenas) [reply pkg/services/alerting/notifier.go]: Hmm ok the lint was not about this one. I am not sure if this can be simplified. `setting.AlertingEvaluationTimeout * 0.9` complains that `0.9` cannot be converted to int64 which makes sense I assume.

Comment (aocenas) [reply pkg/services/alerting/notifier.go]: Same complaint with `setting.AlertingEvaluationTimeout.Seconds() * 0.9 * time.Second`

Comment (marefr) [reply pkg/services/alerting/notifier.go]: Hmm question is if need the 0.9 there at all now when we have one configuration each for evaluation and notification. Or do we still have an overall timeout which is the sum of both? @bergquist maybe can shed some light on this.

Comment (bergquist) [reply pkg/services/alerting/notifier.go]: Your right. We can get rid of it

Comment (bergquist) [reply pkg/services/alerting/notifier.go]:
```suggestion
		Timeout:         setting.AlertingEvaluationTimeout,
```

Comment (bergquist) [reply pkg/services/alerting/notifier.go]: Once this is done this is ready to be merged.

**Review by bergquist — APPROVED** [review]
