### PR TITLE
Loki: Re-introduce running of instant queries

### LINKED ISSUE #27162: Loki: We are not running instant metrics queries
**What happened**:
When running metrics queries in Explore, we stopped running instant queries which should be showed in table under the graph with range queries results. 

**What you expected to happen**:
See table with instant queries results.

**How to reproduce it (as minimally and precisely as possible)**:
Run loki metrics query - you see graph but not table. 

**Anything else we need to know?**:
Probably introduced while logs-metrics unification in https://github.com/grafana/grafana/commit/64bc85963b2b2afe86ad3c61510b9b1e41e9fb7a

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
Re-introduces running of instant queries for Loki:

- In case of metrics queries, we visualise the result in table
- In case of log queries, then we know that we are dealing with a logs query, and drop the result from the instant query and only pass on the result from the range query

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/27162

### CODE REVIEW

File: public/app/plugins/datasource/loki/datasource.ts [hunk 1]
```diff
@@ -133,7 +138,8 @@ export class LokiDatasource extends DataSourceApi<LokiQuery, LokiOptions> {
           data: [lokiResultsToTableModel(response.data.data.result, responseListLength, target.refId, meta, true)],
           key: `${target.refId}_instant`,
         };
-      })
+      }),
+      catchError((err: any) => this.throwUnless(err, err.status === 404, target))
```
Comment (davkal) [inline public/app/plugins/datasource/loki/datasource.ts:142]: Why is this needed? Is this for legacy loki instances that don't have the query endpoint?

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/datasource.ts:142]: It in not necessary, but in [throwUnless](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/loki/datasource.ts#L505-L520) we have a function that enriches the error message to give users a better guidance on errors (specifically escaping error).

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/datasource.ts:142]: So instead of having this error message: 
image

We get this - more guiding - error message:
image

**Review by zoltanbedi — APPROVED** [review]
This looks good to me ✨

**Review by davkal — APPROVED** [review]
LGTM
