### PR TITLE
Loki: Fix producing correct log volume query for query with comments

### LINKED ISSUE #53001: Loki/Log-volume-histogram: Shows error if LogQL contains comments at the end.
**What happened**:
When doing LogQL with comments at the **end**, Log volume histogram panel show error.

**What you expected to happen**:
LogVolume histogram panel should ignoring the comments.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open Grafana
2. Choose Loki datasource
3. Run any LogQL with comments at the end. for example
```
{cluster="ops-us-east-0", namespace="loki-ops-003"}
#something-useful-comment
```

ideally, I would expect histogram panel to ignore the comment. But it doesn't. It throws error `parse error at line 2, col 32: syntax error: unexpected $end`

Attached a screenshot for more details
Screenshot 2022-07-29 at 17 16 36

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v 9.1.0
- Data source type & version: Loki
- OS Grafana is installed on:
- User OS & Browser: Linux & Brave browser
- Grafana plugins: NO
- Others: NO

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
When using Loki in Explore, we are creating log volume (metrics) query based on user-typed log query. As mentioned in https://github.com/grafana/grafana/issues/53001, if the log query includes **comments**, the resulting query is incorrect.

In this PR, before creating metrics query, we are removing comments from log query and after that create log volume query. To remove comments, we use `lezer-logql` parser, find all occurrences of `LineComment` and then just remove it from query.

As a part of this PR I have renamed `addToQuery` file to `modifyQuery` as we are both adding and removing now. 

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/53001

**Special notes for your reviewer**:
To test this:
1. Run loki datasource `make devenv sources=loki`
2. In Explore, run any log query (e.g. `{source="data"}` or get inspired by queries in test) with or without comment (comments start with `#`)
3. Every log query with comments should produce log query without comment (you can always check it out in network tab and/or in panel inspector)

Fixed:

https://user-images.githubusercontent.com/30407135/182643376-537f9262-f597-4798-9b49-d80a6f4a3dc1.mov

Previously (current behavior on main):

https://user-images.githubusercontent.com/30407135/182643299-f5a1e75d-1493-4a66-9097-2a9cc803ce5d.mov

### CODE REVIEW

File: public/app/plugins/datasource/loki/modifyQuery.ts [hunk 1]
```diff
@@ -90,6 +90,33 @@ export function addLabelFormatToQuery(query: string, labelFormat: { originalLabe
   return addLabelFormat(query, logQueryPositions, labelFormat);
 }
 
+/**
+ * Removes all comments from query.
+ * It uses  LogQL parser to find all LineComments and removes them.
+ *
+ * @param query
```
Comment (matyax) [inline public/app/plugins/datasource/loki/modifyQuery.ts:97]: Is it required to specify \@params in dockblocks when using TypeScript? Asking because it can be considered redundant.

File: public/app/plugins/datasource/loki/modifyQuery.ts [hunk 2]
```diff
@@ -90,6 +90,33 @@ export function addLabelFormatToQuery(query: string, labelFormat: { originalLabe
...
+  const lineCommentPositions = getLineCommentPositions(query);
+
+  if (!lineCommentPositions.length) {
+    return query;
+  }
+
+  let newQuery = '';
+  let prev = 0;
+
+  for (let i = 0; i < lineCommentPositions.length; i++) {
```
Comment (matyax) [inline public/app/plugins/datasource/loki/modifyQuery.ts:109]: How about:

```suggestion
  for (let match of lineCommentPositions) {
```

File: public/app/plugins/datasource/loki/modifyQuery.test.ts [hunk 3]
```diff
@@ -233,3 +239,39 @@ describe('addLabelFormatToQuery', () => {
     );
   });
 });
+
+describe('removeCommentsFromQuery', () => {
+  it('strips comments in log queries', () => {
```
Comment (matyax) [inline public/app/plugins/datasource/loki/modifyQuery.test.ts:244]: Have you considered using `it.each()` for some of these test scenarios?

**Review by matyax — APPROVED** [review]
Looks good! Left some comments for your consideration.

File: public/app/plugins/datasource/loki/modifyQuery.ts (hunk 1 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/modifyQuery.ts]: Yeah, you are right that in this case it is absolutely redundant. I'll remove it. However in some cases it can be quite useful and in that case you are encouraged to add it there. The documentation on code comments can be find here: https://github.com/grafana/grafana/blob/main/contribute/style-guides/code-comments.md

Updated in: https://github.com/grafana/grafana/pull/53254/commits/cdf0c839e3e48fa18afb1b0cd7a04a852bfeaab4

File: public/app/plugins/datasource/loki/modifyQuery.ts (hunk 2 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/modifyQuery.ts]: Yeah, also great suggestion. I have changed it to `lineCommentPosition of lineCommentPositions`  inhttps://github.com/grafana/grafana/commit/cdf0c839e3e48fa18afb1b0cd7a04a852bfeaab4

File: public/app/plugins/datasource/loki/modifyQuery.test.ts (hunk 3 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/modifyQuery.test.ts]: You are right and `it.each` would be better for future debugging and identifying what actually failed. 

Updated in: https://github.com/grafana/grafana/pull/53254/commits/69e461b8f9b858915086fc577923305b2eb26737

**Review by matyax — APPROVED** [review]
👏 👏
