### PR TITLE
RefreshPicker: make widget accessible

### LINKED ISSUE #39838: AutoRefresh menu not accessible via keyboard
As mentioned on a different thread, I'm aware that there are various accessibility issues currently being worked on. I can't find an issue for this and wanted to bring attention to it, but sorry if I've missed something!

**Steps to reproduce**:
Press tab until keyboard focus reaches the _down arrow_ icon located next to the 'refresh dashboard' icon. Using this, try to change the auto refresh time / turn auto refresh off using the keyboard.

**Actual Result**:
https://user-images.githubusercontent.com/63413067/135409097-8607e56d-3c5e-4f6b-b6df-9ab5c1f0cb8c.mp4

As you can see from the video this is very difficult (/impossible) to do. At first I was pressing enter causing the menu to only appear for a very brief moment. Next I pressed space to get the menu to open on a more permanent basis, however I was unable to get keyboard focus into the menu to select a new option.

**Expected Result**:
I should be able to at least turn off auto refresh using only the keyboard, this can be a very useful tool when using Grafana.

**Relevant WCAG Criteria:** [2.2.1 timing-adjustable](https://www.w3.org/TR/WCAG21/#timing-adjustable) / [2.2.2 pause-stop-hide](https://www.w3.org/TR/WCAG21/#pause-stop-hide)

**Environment**:
- Grafana version: 8.2.0-beta1
- Data source type & version: Default data used at [play.grafana.org](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1)
- User OS & Browser: Windows & Chrome
- Others:

### PR DESCRIPTION
**Pull request by thisisobate**
**What this PR does / why we need it**:
This PR makes the refresh picker to be keyboard navigable and screen reader accessible
**Which issue(s) this PR fixes**:

Relates to #35613
Fixes #39838

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by thisisobate** [comment]
noticed some weird behaviour when you expand the refreshPicker dropdown- requires one has to tab into the list before arrow navigation is enabled.

Already looking into fixing that as well

**Review by natellium — COMMENTED** [review]
It works for this specific case, but I left a couple of comments :) Tests also seem to need some fixing

**Review by ashharrison90 — CHANGES_REQUESTED** [review]
just this function that looks icky 🤮

**Review by hugohaggmark — COMMENTED** [review]
Good work, I took it for a spin and it works as expected and my screen reader sounds great!  But I also agree with @ashharrison90 comment.

**Review by kaydelaney — COMMENTED** [review]
Nice work on this! Agree with what others have said about the `sanitizedIntervalsLabels` function, but otherwise looks good. 👍

File: packages/grafana-data/src/datetime/durationutil.ts [hunk 1]
```diff
@@ -46,7 +46,8 @@ export function parseDuration(duration: string): Duration {
       return acc;
     }
 
-    const key = Object.entries(durationMap).find(([_, abbreviations]) => abbreviations?.includes(match[2]))?.[0];
+    const durationMapKey = Object.entries(durationMap).find(([_, abbreviations]) => abbreviations?.includes(match[2]));
+    const key = Number(match[1]) !== 1 ? durationMapKey?.[1][3] : durationMapKey?.[1][2];
```
Comment (thisisobate) [inline packages/grafana-data/src/datetime/durationutil.ts:50]: I'm afraid this might cause some breaking changes in the codebase. I think it would make more sense if we format the output instead in the refreshPicker

Comment (ashharrison90) [reply packages/grafana-data/src/datetime/durationutil.ts:50]: @thisisobate I wouldn't bother changing it tbh. 1 days is good enough for now. We'll need to think about pluralisation properly when we do the i18n work so this would have to change anyway.

Comment (thisisobate) [reply packages/grafana-data/src/datetime/durationutil.ts]: oh...just saw your comment now. Already pushed some changes that formats the units. Please take a look and see if we need to go ahead with that approach or not

**Comment by thisisobate** [comment]
> It would be better to introduce runButtonV2 and intervalButtonV2 and deprecate the older ones.

Won't this break plugins that would be tested on older versions of the e2e selector package? Doesn't it make sense to leave the older ones and still introduce runButtonV2 and intervalButtonV2? @hugohaggmark 

```tsx
RefreshPicker: {
    runButton: '',
    intervalButton: '',
    runButtonV2: '',
    intervalButtonV2: '',
  },
```

File: packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx [hunk 2]
```diff
@@ -56,17 +57,20 @@ const ButtonSelectComponent = <T,>(props: Props<T>) => {
...
-                  onClick={() => onChangeInternal(item)}
-                  active={item.value === value?.value}
-                />
-              ))}
-            </Menu>
+          <ClickOutsideWrapper onClick={onCloseMenu} parent={document} includeButtonPress={false}>
+            <FocusScope contain restoreFocus autoFocus>
+              <Menu onClose={onCloseMenu}>
+                {options.map((item) => (
+                  <MenuItem
```
Comment (kaydelaney) [inline packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx:64]: Hmm, for the RefreshPicker, I think `menuitemradio` is probably the more appropriate role, since an option is selected and persisted rather than just executing an action. I think that also means adding `aria-checked="true"` to the select option. Maybe we could add a `role` prop to `MenuItem`?

File: packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx [hunk 3]
```diff
@@ -56,17 +57,20 @@ const ButtonSelectComponent = <T,>(props: Props<T>) => {
...
-                <MenuItem
-                  key={`${item.value}`}
-                  label={(item.label || item.value) as string}
-                  onClick={() => onChangeInternal(item)}
-                  active={item.value === value?.value}
-                />
-              ))}
-            </Menu>
+          <ClickOutsideWrapper onClick={onCloseMenu} parent={document} includeButtonPress={false}>
+            <FocusScope contain restoreFocus autoFocus>
```
Comment (kaydelaney) [inline packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx:61]: Not sure we want `contain` here. Looking at the [WAI-ARIA authoring practices](https://www.w3.org/TR/wai-aria-practices-1.1/#menu), it says:
> Tab: Moves focus to the next element in the tab sequence, and if the item that had focus is not in a menubar, closes its menu and all open parent menu containers.
This will probably involve a change to how `Menu` handles focus/blur.

Another thing I noticed from the authoring practices guide is that the menu should open when pressing the down arrow.

**Review by kaydelaney — COMMENTED** [review]
Looks good! 👍  Left some comments, let me know if you need me to clarify any of them.

File: packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx (hunk 2 above)
Comment (thisisobate) [reply packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx:64]: Does changing the menuItem role to `menuitemradio` have any a11y impact?

Comment (kaydelaney) [reply packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx:64]: It depends on the screen reader software and settings used (for example I think this is the case for NVDA), but some will announce the role when focused on the menu item. "Menu item radio" lets users know that they are making a choice from a list of options that will be persisted in some way, which is the case here.

Comment (thisisobate) [reply packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx:64]: Hmm..good point.
But isn't that similar to what I solved with the refresh Picker aria labels here? [run this branch to see how it works]

File: packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx [hunk 4]
```diff
@@ -93,7 +99,17 @@ export function intervalsToOptions({ intervals = defaultIntervals }: { intervals
   SelectableValue<string>
 > {
   const intervalsOrDefault = intervals || defaultIntervals;
-  const options = intervalsOrDefault.map((interval) => ({ label: interval, value: interval }));
+  const options = intervalsOrDefault.map((interval) => {
+    const label: { [key: string]: string | number } = parseDuration(interval);
+    const unit = Object.keys(label);
```
Comment (ashharrison90) [inline packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx:104]: this typing feels a little funky. looking at the `Duration` type in `date-fns`, the RHS of the object is only ever a `number`, not `string | number`. maybe something like:
```suggestion
    const duration = parseDuration(interval);
    const unit = Object.keys(duration) as (keyof Duration)[];
```
would be better. that also suggests that `duration` _could_ be an empty object (`{}`) and therefore `unit` (and `amount`) would be `undefined` and we need to handle that case 🤔 

pinging @joshhunt to check my typescript

**Review by ashharrison90 — COMMENTED** [review]
lgtm 🙌 

just a minor nit on the typings

File: packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx (hunk 2 above)
Comment (kaydelaney) [reply packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx:64]: Sure, it's similar, but I think in general it's better to go with established conventions as a user is more likely to expect and be familiar with those approaches. As well, if the choice is between an aria property with a clearer and more specific purpose vs. using, say, aria-label to fulfill a similar role, it's probably better to go with the first option, since it provides more information to screen readers.

File: packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx (hunk 3 above)
Comment (thisisobate) [reply packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx:61]: > Another thing I noticed from the authoring practices guide is that the menu should open when pressing the down arrow.

I think this is optional though.

> (Optional) Down Arrow: opens the menu and moves focus to the first menu item.

Comment (thisisobate) [reply packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx:61]: > Not sure we want contain here

I think we do. This prevents us from moving focus to the next element in the tab sequence. So, at very point in time, refresh picker menu would always be closed when moving focus to the next tabable element.

File: packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx (hunk 2 above)
Comment (thisisobate) [reply packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx:64]: Good point.
I think in the case of refreshPicker, it makes sense to use both aria labels and aria role `menuitemradio`.

Comment (thisisobate) [reply packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx:64]: would push some updates soon

File: packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx (hunk 4 above)
Comment (thisisobate) [reply packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx:104]: Good Point @ashharrison90 
The downside with this approach is that typescript won't identify `slice` as a valid string property when used on an array item which belongs to an array of strings(`unit` in this case)

e.g `unit[0]`

File: packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx (hunk 3 above)
Comment (kaydelaney) [reply packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx]: > I think we do. This prevents us from moving focus to the next element in the tab sequence. So, at every point in time, refresh picker menu would always be closed when moving focus to the next tabable element.

I think this is desired behaviour though?
From WAI-ARIA authoring practices:

> "Tab: Moves focus to the next element in the tab sequence, and if the item that had focus is not in a menubar, closes its menu and all open parent menu containers."

File: packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx (hunk 4 above)
Comment (ashharrison90) [reply packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx:104]: @thisisobate don't quite follow. `.slice` seems to work fine, the only TS error is about `amount` potentially being undefined:

image

Comment (thisisobate) [reply packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx]: It seems like it's an issue with my VScode instance...would fix it up. Thanks!

**Review by ashharrison90 — APPROVED** [review]
typings lgtm now 👍

File: packages/grafana-e2e-selectors/src/selectors/components.ts [hunk 5]
```diff
@@ -137,8 +137,16 @@ export const Components = {
     active: () => '[class*="-activeTabStyle"]',
   },
   RefreshPicker: {
+    /**
+     * @deprecated use runButtonV2 instead
+     */
     runButton: 'RefreshPicker run button',
+    /**
+     * @deprecated use intervalButtonV2 instead
+     */
```
Comment (joshhunt) [inline packages/grafana-e2e-selectors/src/selectors/components.ts:146]: Seeing as these are for the purpose of versioning, maybe change the message to be like "use intervalButtonV2 from Grafana 8.3 instead", or something like that? @hugohaggmark 

And/or maybe the _new_ keys could include the _Grafana_ version instead? dunno. Just a random musing.

Comment (thisisobate) [reply packages/grafana-e2e-selectors/src/selectors/components.ts:146]: > use intervalButtonV2 from Grafana 8.3 instead

I love this 😍

File: packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx (hunk 3 above)
Comment (thisisobate) [reply packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx]: Oh...I think I get your point now @kaydelaney 
Would look into this

File: packages/grafana-e2e-selectors/src/selectors/components.ts (hunk 5 above)
Comment (hugohaggmark) [reply packages/grafana-e2e-selectors/src/selectors/components.ts:146]: Sounds good!

File: packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx [hunk 6]
```diff
@@ -93,7 +100,23 @@ export function intervalsToOptions({ intervals = defaultIntervals }: { intervals
...
+  const options = intervalsOrDefault.map((interval) => {
+    const duration = parseDuration(interval);
+    const unit = Object.keys(duration) as Array<keyof Duration>;
+    const amount = duration[unit[0]];
+    let describedIntervalLabel = interval;
+
+    if (amount !== undefined) {
+      const formattedUnit = amount > 1 ? unit : unit[0].slice(0, -1);
+      describedIntervalLabel = amount + ' ' + formattedUnit;
+    }
```
Comment (joshhunt) [inline packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx:112]: Instead, are we able to use `formatDuration` from date-fns? formatDuration

This could be simplified down to 

```typescript
const ariaLabel = formatDuration(parseDuration(interval))
```

File: public/app/features/dashboard/components/DashNav/DashNavTimeControls.test.tsx [hunk 7]
```diff
@@ -51,7 +51,7 @@ describe('DashNavTimeControls', () => {
     const container = render(
       <DashNavTimeControls dashboard={dashboardModel} onChangeTimeZone={jest.fn()} key="time-controls" />
     );
-    expect(container.queryByLabelText(/RefreshPicker interval button/i)).not.toBeInTheDocument();
+    expect(container.queryByLabelText(/Choose refresh time interval/i)).not.toBeInTheDocument();
```
Comment (joshhunt) [inline public/app/features/dashboard/components/DashNav/DashNavTimeControls.test.tsx:54]: These assertions are 10x better!!! 😍

File: packages/grafana-ui/src/components/Menu/MenuItem.tsx [hunk 8]
```diff
@@ -30,7 +34,22 @@ export interface MenuItemProps<T = any> {
...
+        label,
+        ariaLabel,
+        ariaChecked,
+        target,
+        onClick,
+        className,
+        active,
+        role = 'menuitem',
+        tabIndex = -1,
+      },
```
Comment (joshhunt) [inline packages/grafana-ui/src/components/Menu/MenuItem.tsx:50]: This has gotten a bit out of hand and tricky to read - maybe lets just get this variable out the single `props` object, and then unpack it down in the body of the function?


```ts
(props, ref) => {
  const { url, icon, etc ... } props;
  const styles = useStyles2(getStyles);
```

**Review by joshhunt — COMMENTED** [review]
Nice work 👍🏻 👍🏻 👍🏻

File: packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx (hunk 3 above)
Comment (thisisobate) [reply packages/grafana-ui/src/components/Dropdown/ButtonSelect.tsx]: Pushed some changes already...feel free to take a look @kaydelaney

File: packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx (hunk 6 above)
Comment (ashharrison90) [reply packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx:112]: ooooft I didn't even realise there was a `formatDuration`. that feels like the one, and avoids any manual manipulation of the string.

nice find @joshhunt 🙌

File: packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx (hunk 4 above)
Comment (joshhunt) [reply packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx]: We've got an alternate implementation to skip this problem entirely, but imho I think the type was fine before.

If we want to treat the `label`/`duration` as a bag of string: number (as opposed to an object with specific keys), then `Record<string, number>` is the right type for that.

As an absolute last resort, if we must, you could do the cast with `Object.keys(duration) as Array<keyof valueof duration>` so at least there's a higher chance of the cast being correct as the code is changed around. But IMHO `as` type assertions should be avoided at all costs.

File: packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx (hunk 6 above)
Comment (thisisobate) [reply packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx:112]: @joshhunt it seems `formatDuration` expects duration values to be of type number instead. Had to convert the values to numbers before passing it in to`formatDuration`. Would push my solution right away

File: packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx (hunk 4 above)
Comment (thisisobate) [reply packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx]: Then I think it makes sense for us to revert back to the type we were using before. Would push some changes right away

Comment (joshhunt) [reply packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx]: If you're using `formatDuration` from date-fns you shouldn't need this type any more.

**Review by joshhunt — APPROVED** [review]
Great stuff!

I’m going to make an issue to refactor the parseDuration function because it’s a bit gnarly and it shouldn’t be returning strings, but it’s not fair for you to have to handle that all in this PR :)
