### PR TITLE
Table: Makes tooltip scrollable for long JSON values

### LINKED ISSUE #30727: Table: JSON Tooltip closes when too long
**What happened**: Expanding a sub-json in the tooltip causing it to exceed the window size instantly closes the tooltip  
HMMxqaGpPJ

**What you expected to happen**: Uhm, a scrollbar I guess? 

**How to reproduce it (as minimally and precisely as possible)**: Get a really really long json, and try to display it in table view. [Here's the one I used](https://pastebin.com/2ZAQHgd7)

**Anything else we need to know?**: I'm out of my element, but maybe `CustomScrollbar` can be added in [JSONViewCell.tsx](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Table/JSONViewCell.tsx) like in [Table.tsx](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Table/Table.tsx)? 

Also, the positioning of the tooltip is way off to the right, probably because of the length as well, should I open another issue for that? 

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: postgresql 12
- OS Grafana is installed on: Ubuntu 20.04 LTS
- User OS & Browser: Windows 10 19042.746 / Chrome 87.0.4280.141
- Grafana plugins: The defaults
- Others:

### LINKED ISSUE #30761: Table: JSON Tooltip positioned issues
**What happened**: The json tooltip is positioned off to the right, it cannot be accessed (unless you flick your cursor over quick enough)
image

**What you expected to happen**: Tooltip edge to be near the cursor, or maybe on the cell's edge

**How to reproduce it (as minimally and precisely as possible)**: Get a really really long json, and try to display it in table view. [Here's the one I used](https://pastebin.com/2ZAQHgd7)

**Anything else we need to know?**: 

**Environment**:
Grafana version: 7.3.7
Data source type & version: postgresql 12
OS Grafana is installed on: Ubuntu 20.04 LTS
User OS & Browser: Windows 10 19042.746 / Chrome 87.0.4280.141
Grafana plugins: The defaults
Others:

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR limits the height of the JSON tooltip and makes the content scrollable for long JSON structures. I also set the placement of the tooltip to `auto-start`.

https://user-images.githubusercontent.com/562238/118264836-9adba480-b4b8-11eb-8cfb-2a6967f8a947.mp4

**Which issue(s) this PR fixes**:
Fixes #30761
Fixes #30727

**Special notes for your reviewer**:

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/JSONViewCell.tsx [hunk 1]
```diff
@@ -1,13 +1,13 @@
-import React, { FC } from 'react';
+import React from 'react';
 import { css, cx } from '@emotion/css';
 import { isString } from 'lodash';
 import { Tooltip } from '../Tooltip/Tooltip';
 import { JSONFormatter } from '../JSONFormatter/JSONFormatter';
-import { useStyles } from '../../themes';
+import { useStyles2 } from '../../themes';
```
Comment (jackw) [inline packages/grafana-ui/src/components/Table/JSONViewCell.tsx:6]: 👏

File: packages/grafana-ui/src/components/Table/JSONViewCell.tsx [hunk 2]
```diff
@@ -29,32 +29,38 @@ export const JSONViewCell: FC<TableCellProps> = (props) => {
...
-};
+}
+
+function getStyles(theme: GrafanaTheme2) {
+  return {
+    container: css`
+      padding: ${theme.spacing(0.5)};
+    `,
+    json: css`
+      max-width: fit-content;
```
Comment (jackw) [inline packages/grafana-ui/src/components/Table/JSONViewCell.tsx:61]: 🧙

**Review by jackw — APPROVED** [review]
Tested locally and works as expected! 👍

File: packages/grafana-ui/src/components/Table/JSONViewCell.tsx (hunk 2 above)
Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Table/JSONViewCell.tsx:61]: Huh, what does that emoji mean?

Comment (jackw) [reply packages/grafana-ui/src/components/Table/JSONViewCell.tsx:61]: It means that you're a wizard Hugo! ⚡
