### PR TITLE
API: Readonly datasources should not be created via the API

### LINKED ISSUE #17347: ReadOnly datasource property returned incorrectly when querying by datasource name via API
**What happened**:
It appears that _readOnly_ property of an already created datasource is returned incorrectly when the one datasource is queried by it's name using HTTP API. At the same time, when a list of all datasources is requested via HTTP API, the property is displayed correctly.

grafana_datasource_querying

**What you expected to happen**:
_readOnly_ property value should be consistent regardless of how the datasources config is retrieved.

**How to reproduce it**:
1. Run Grafana in Docker:
```
docker run -d -p 3000:3000 --name=grafana -e "GF_INSTALL_PLUGINS=grafana-azure-monitor-datasource" grafana/grafana
```` 
3. Create a datasource by posting a JSON:
```
curl -X POST -H "Content-Type: application/json" -H "Accept: application/json"  http://admin:admin@localhost:3000/api/datasources -d @./grafana_env/g
rafana_datasources/test.json
```
Content of the sample config file:
```
{
  "orgId": 1,
  "name": "ai-devops-tst",
  "type": "grafana-azure-monitor-datasource",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "/api/datasources/proxy/4",
  "password": "",
  "user": "",
  "database": "",
  "basicAuth": false,
  "basicAuthUser": "",
  "basicAuthPassword": "",
  "withCredentials": false,
  "isDefault": false,
  "jsonData": {
    "appInsightsAppId": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx",
    "azureLogAnalyticsSameAs": true,
    "clientId": "xxxxxxxx-xxx-xxx-xxxxx-xxxxxxxxxx",
    "cloudName": "azuremonitor",
    "subscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx",
    "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx"
  },
  "secureJsonFields": {
    "appInsightsApiKey": "111111111",
    "clientSecret": "11111111111111111111111"
  },
  "readOnly": false
}
```

4. Observe discrepancy between results of readOnly property as displayed on the screenshot above

**Environment**: Docker Grafana 
- Grafana version: v6.1.6 (cf9cb45)
- Data source type & version: Azure Monitor  0.3.0 
- OS Grafana is installed on: Host: Windows 10; Docker:Debian GNU/Linux 9
- User OS & Browser: NA
- Grafana plugins:  Azure Monitor  0.3.0 
- Others:

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
One should not be able to create a readonly data source via the API (as it can only be removed via provisioning).
With this fix:
- the `readOnly` field is ignored when setting up or updating the datasource via JSON
- fixes `GetDataSourceByName` call which used to return always `true` for the `ReadOnly` field.

**Which issue(s) this PR fixes**:

Fixes #17347

**Special notes for your reviewer**:
Maybe this modification should also be documented [here](https://grafana.com/docs/http_api/data_source/). However now there is no reference to the `ReadOnly` field.

### CODE REVIEW

File: pkg/models/datasource.go [hunk 1]
```diff
@@ -144,9 +144,9 @@ type AddDataSourceCommand struct {
 	IsDefault         bool              `json:"isDefault"`
 	JsonData          *simplejson.Json  `json:"jsonData"`
 	SecureJsonData    map[string]string `json:"secureJsonData"`
-	ReadOnly          bool              `json:"readOnly"`
 
-	OrgId int64 `json:"-"`
+	OrgId    int64 `json:"-"`
+	ReadOnly bool  `json:"-"`
```
Comment (marcusolsson) [inline pkg/models/datasource.go]: Why do we keep the `ReadOnly` field for `AddDataSourceCommand` and `UpdateDataSourceCommand`? I assume these structs define the inputs for those command, so a ReadOnly field wouldn't be used (same goes for OrgId)?

Comment (papagian) [reply pkg/models/datasource.go]: The reason for keeping `ReadOnly` is that we only want `ReadOnly` to be ignored when the datasource is created/updated via the API but not for example via provisioning.

**Review by marefr — APPROVED** [review]
LGTM
