### PR TITLE
Timeseries: Fix null pointer when matching fill below to field

### LINKED ISSUE #57977: Regression in 9.2.3 in TimeSeries breaks with fill below option
**What happened**:
Timeseries graph crashes with this error:

```
TypeError: Cannot read properties of undefined (reading 'state')
    at r (fieldState.ts:40:31)
    at utils.ts:404:35
    at Object.prepConfig (TimeSeries.tsx:25:12)
    at b.prepState (GraphNG.tsx:133:24)
    at new b (GraphNG.tsx:104:22)
    at gi (react-dom.production.min.js:135:172)
    at qa (react-dom.production.min.js:181:146)
    at Zs (react-dom.production.min.js:269:427)
    at Ou (react-dom.production.min.js:250:347)
    at ku (react-dom.production.min.js:250:278)
```

Looking at the diff between 9.2.2 and 9.2.3, I would guess https://github.com/grafana/grafana/pull/57728 triggered the regression.

**What you expected to happen**:
Timeseries graph renders normally

**How to reproduce it (as minimally and precisely as possible)**:
This is the graph that crashes

<details>

```
{
  "id": 4,
  "gridPos": {
    "h": 8,
    "w": 23,
    "x": 0,
    "y": 14
  },
  "type": "timeseries",
  "title": "Load",
  "datasource": {
    "uid": "i3od78gRz",
    "type": "prometheus"
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "smooth",
        "barAlignment": 0,
        "lineWidth": 2,
        "fillOpacity": 0,
        "gradientMode": "none",
        "spanNulls": false,
        "showPoints": "auto",
        "pointSize": 5,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "axisColorMode": "text",
        "scaleDistribution": {
          "type": "linear"
        },
        "axisCenteredZero": false,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        },
        "axisSoftMin": 0
      },
      "color": {
        "mode": "palette-classic"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          }
        ]
      },
      "min": 0,
      "unit": "none"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byFrameRefID",
          "options": "B"
        },
        "properties": [
          {
            "id": "custom.lineWidth",
            "value": 0
          },
          {
            "id": "custom.hideFrom",
            "value": {
              "legend": true,
              "tooltip": false,
              "viz": false
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Detail dodecaphonism"
        },
        "properties": [
          {
            "id": "custom.fillBelowTo",
            "value": "dodecaphonism"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "light-green",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Detail most"
        },
        "properties": [
          {
            "id": "custom.fillBelowTo",
            "value": "most"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "light-yellow",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Detail polyphony"
        },
        "properties": [
          {
            "id": "custom.fillBelowTo",
            "value": "polyphony"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "light-blue",
              "mode": "fixed"
            }
          }
        ]
      }
    ]
  },
  "options": {
    "tooltip": {
      "mode": "single",
      "sort": "none"
    },
    "legend": {
      "showLegend": true,
      "displayMode": "list",
      "placement": "bottom",
      "calcs": [
        "lastNotNull"
      ]
    }
  },
  "targets": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "i3od78gRz"
      },
      "editorMode": "code",
      "expr": "rate(node_load15[$__rate_interval])",
      "interval": "5m",
      "legendFormat": "{{instance}}",
      "range": true,
      "refId": "A"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "i3od78gRz"
      },
      "editorMode": "code",
      "expr": "rate(node_load1[$__rate_interval])",
      "hide": false,
      "legendFormat": "Detail {{instance}}",
      "range": true,
      "refId": "B"
    }
  ]
}
```

</details>

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.3
- Data source type & version: prometheus 2.27.0
- OS Grafana is installed on: Debian Linux
- User OS & Browser: Chrome 106.0.5249.119

### PR DESCRIPTION
**Pull request by mdvictor**
**What is this feature?**
Error check when getting display name of the field selected as fill below to value

**Why do we need this feature?**
There's a error in the console.

**Who is this feature for?**
Timeseries panel users

**Which issue(s) does this PR fix?**:

Fixes #57977

### CODE REVIEW

File: packages/grafana-ui/src/components/TimeSeries/utils.ts [hunk 1]
```diff
@@ -401,7 +401,9 @@ export const preparePlotConfigBuilder: UPlotConfigPrepFn<{
 
       if (customConfig.fillBelowTo) {
         const fillBelowToField = frame.fields.find((f) => f.name === customConfig.fillBelowTo);
```
Comment (leeoniya) [inline packages/grafana-ui/src/components/TimeSeries/utils.ts:403]: ok, i'm a bit confused here.

the values we save in the config are the _display_ name, shouldn't this logic also use that?

https://github.com/grafana/grafana/blob/6e6863f10a78014f757d4565330d67039449a447/public/app/plugins/panel/timeseries/FillBelowToEditor.tsx#L13

Comment (mdvictor) [reply packages/grafana-ui/src/components/TimeSeries/utils.ts:403]: The values we save in the config are the name values returned from the datasource since the field overrides have not yet run at that point. This is why in `utils.ts` we should check the `fillBelowTo` property against the original name and not against the display name.

File: packages/grafana-ui/src/components/TimeSeries/utils.ts [hunk 2]
```diff
@@ -400,8 +400,14 @@ export const preparePlotConfigBuilder: UPlotConfigPrepFn<{
       }
 
       if (customConfig.fillBelowTo) {
-        const fillBelowToField = frame.fields.find((f) => f.name === customConfig.fillBelowTo);
-        const fillBelowDispName = getFieldDisplayName(fillBelowToField!, frame, allFrames);
+        const fillBelowToField = frame.fields.find((field) =>
+          [field.name, field.config?.displayName, field.config?.displayNameFromDS, field.state?.displayName].includes(
```
Comment (ryantxu) [inline packages/grafana-ui/src/components/TimeSeries/utils.ts:404]: rather than try to enumerate them... maybe just use the function?  (it will most likely grab from cached state anyway)

somethign like
```
let fillBelowDispName = customConfig.fillBelowTo;
const fillBelowToField = frame.fields.find((f) => {
  return (fillBelowDispName === f.name || fillBelowDispName === getFieldDisplayName(f, frame, allFrames));
})
```

Comment (mdvictor) [reply packages/grafana-ui/src/components/TimeSeries/utils.ts]: The reason I enumerated was because I needed to find a field name possibly without overrides. The options in the `fillBelowTo` are without field overrides (e.g: display name). Searching for fields with the result of `getFieldDisplayName` would result in post override names, which wouldn't match the `fill bellow to` option, in some scenarios. 

E.g: I have a display name override for a field that is also set as a `fill bellow to` field. So my `customConfig.fillBelowTo` value is the name of the field before the display name override, and that's the one I need to find. Sometimes `field.name` will do, other times it might be `field.config.displayNameFromDS`. But `getFieldDisplayName` func will always return the name of the field with the display name override applied, which doesn't help.

Comment (mdvictor) [reply packages/grafana-ui/src/components/TimeSeries/utils.ts]: I changed the code to use the function if other checks fail

**Review by ryantxu — APPROVED** [review]
I think this is fine -- i don't think `f.config?.displayNameFromDS` is necessary, but it won't hurt

**Comment by mdvictor** [comment]
> I think this is fine -- i don't think `f.config?.displayNameFromDS` is necessary, but it won't hurt

@ryantxu The reason why `displayNameFromDS` is needed is for cases in which a field used as `fillBelowTo` has its display name overriden and the frames have a 2-field-structure(`Time` and `Value`). When the fill below editor creates the options the overrides are not applied, the `field.name` is set to `Value` and the `field.state.displayName` is set to `field.config.displayNameFromDS`.  When `getFieldDisplayName` is called in the editor it will simply return `field.state.displayName`. 

But when the timeseries panel tries to set the `fill bellow to` band, the overrides are applied, so `field.state.displayName` will be equal to whatever the user set it in overrides. In this case `field.name` will be `Value` (which is irrelevant) and `state.displayName` will also be different than the `fillBelowTo` option, thus not showing the bands. This is why we also check for the DS display name.
