### PR TITLE
OptionsUI: use NumberInput for number options

### LINKED ISSUE #40872: Histograms: negative sized buckets crash UI
**What happened**: Grafana UI allows user to set bucket size to -1.  If a user accidentally does this, the grafana UI crashes.

https://www.loom.com/share/3dcd721c09834cfeaaa336f15414f91a

**What you expected to happen**: I expected the UI not to let me enter a negative number so easily

**How to reproduce it (as minimally and precisely as possible)**: Make a histogram -> Pannel -> hist

**Environment**:
- Grafana version: ??? (cloud version)
- Data source type & version: clickhouse
- OS Grafana is installed on: NA
- User OS & Browser: chrome / mac
- Grafana plugins: clickhouse

### PR DESCRIPTION
**Pull request by adela-almasan**
**What this PR does / why we need it:**

Added NumberInput to grafana-ui and replaced the existing usage. The number inputs were using different components and the behavior was not consistent.

Fixes #40872

### CODE REVIEW

File: packages/grafana-ui/src/components/OptionsUI/number.tsx [hunk 1]
```diff
@@ -13,56 +8,65 @@ export const NumberValueEditor: React.FC<FieldConfigEditorProps<number, NumberFi
...
+      }
+    },
+    [onChange, inputValue]
+  );
+
+  const onLocalChange = useCallback(
+    (e: React.SyntheticEvent<HTMLInputElement>) => {
+      let num = e.currentTarget.valueAsNumber;
+
+      if (isNaN(num)) {
```
Comment (leeoniya) [inline packages/grafana-ui/src/components/OptionsUI/number.tsx:37]: `Number.isNaN()` is more robust (does not try to coerce the value)

File: public/app/features/transformers/editors/HistogramTransformerEditor.tsx [hunk 2]
```diff
@@ -51,7 +51,13 @@ export const HistogramTransformerEditor: React.FC<TransformerUIProps<HistogramTr
...
           tooltip={histogramFieldInfo.bucketSize.description}
         >
-          <Input type="number" value={options.bucketSize} placeholder="auto" onChange={onBucketSizeChanged} min={0} />
+          <Input
+            type="number"
+            value={options.bucketSize ?? ''}
+            placeholder="auto"
+            onChange={onBucketSizeChanged}
+            min={0}
+          />
```
Comment (nmarrs) [inline public/app/features/transformers/editors/HistogramTransformerEditor.tsx:60]: When user is trying to enter in fractional bucket size (i.e. 0.5) the `0` doesn't appear which may be a confusing to end user. User can enter in `.5` just fine, but for some reason entering in `0` never appears. User can type all of `0.5` to achieve desired bucket size, but UX of this is less than ideal

File: public/app/features/transformers/editors/HistogramTransformerEditor.tsx [hunk 3]
```diff
@@ -15,22 +14,20 @@ export const HistogramTransformerEditor: React.FC<TransformerUIProps<HistogramTr
   const labelWidth = 18;
 
   const onBucketSizeChanged = useCallback(
-    (evt: FormEvent<HTMLInputElement>) => {
-      const val = evt.currentTarget.valueAsNumber;
+    (val?: number) => {
       onChange({
         ...options,
-        bucketSize: isNaN(val) ? undefined : val,
+        bucketSize: Number.isNaN(val) ? undefined : val,
```
Comment (ryantxu) [inline public/app/features/transformers/editors/HistogramTransformerEditor.tsx:20]:
```suggestion
        bucketSize: val,
```
not needed because the input is already checked

File: packages/grafana-data/src/transformations/transformers/histogram.ts [hunk 4]
```diff
@@ -152,7 +152,7 @@ export function buildHistogram(frames: DataFrame[], options?: HistogramTransform
   let bucketOffset = options?.bucketOffset ?? 0;
 
   // if bucket size is auto, try to calc from all numeric fields
-  if (!bucketSize) {
+  if (!bucketSize || bucketSize < 0) {
```
Comment (ryantxu) [inline packages/grafana-data/src/transformations/transformers/histogram.ts:155]: weirdly.... I think this (and the changes in public/app/plugins/panel/histogram/module.tsx) should be in their own PR.

Otherwise everything else is around making the numer input behave rationally (nothing to do with histogram)

**Comment by ryantxu** [comment]
With the changes for histogram pulled out to: 
https://github.com/grafana/grafana/pull/46218#pullrequestreview-899892060

The name/description of this PR should focus on the changes to `@grafana/ui` for NumberInput (nothing about histogram is left)

**Review by mckn — COMMENTED** [review]
I think the code looks good but I would love to get a bit better understanding why we want to introduce a new `NumberInput` component?

Would it be possible to fix the issue with the current one? Or should we deprecate the `number` type on the previous input?

**Comment by adela-almasan** [comment]
Hi! While working on a fix for #40872 I noticed an issue with the current number input in histogram - it wasn't taking into account the set min/max values so it would allow negative values with a min of 0. I noticed inconsistencies in the way other number inputs were behaving. That's how I came across `NumberInput` - which was being used in a few places and it was working as expected (also has input validation message). Basically for a number input we're using `NumberInput`, `number` and `Input`.

I talked to @ryantxu  and decided the best way would be to just use `NumberInput` in `number` and that would cover the functionality. I think `NumberInput` fixes the issues in `number` - it would be duplicated code to fix `number` and also keep `NumberInput`, so using one consistently would be great. I feel like it's not my decision to deprecate or not a widely used component - but they way it was behaving was not covering the needed functionality.

**Comment by mckn** [comment]
> Hi! While working on a fix for #40872 I noticed an issue with the current number input in histogram - it wasn't taking into account the set min/max values so it would allow negative values with a min of 0. I noticed inconsistencies in the way other number inputs were behaving. That's how I came across `NumberInput` - which was being used in a few places and it was working as expected (also has input validation message). Basically for a number input we're using `NumberInput`, `number` and `Input`.

This is great! I guess that there was different behavior depending on what browser you tested in? Regardless it is great that this is fixed. Are there any other changes in how the component behave?

> I talked to @ryantxu and decided the best way would be to just use `NumberInput` in `number` and that would cover the functionality. I think `NumberInput` fixes the issues in `number` - it would be duplicated code to fix `number` and also keep `NumberInput`, so using one consistently would be great. I feel like it's not my decision to deprecate or not a widely used component - but they way it was behaving was not covering the needed functionality.

Since we are exposing a new component from the `grafana/ui` (which is used by external projects) in this PR, I would say that we also should make a decision on how to do with the `<Input type="number" ..>` component. It will be really confusing for developers consuming `grafana/ui` to understand what component they should use if we don't give them clear instructions on this.

Could `NumberInput` be an internal component in `grafana/ui`? So we basically render that component if you try to render an `<Input type="number" ...>` to keep backward compatability?

**Comment by adela-almasan** [comment]
>  I guess that there was different behavior depending on what browser you tested in? Regardless it is great that this is fixed. Are there any other changes in how the component behave?

Not really, I tested on Chrome, FF and Safari - the app was crashing on all of them, the inputs had the same behavior. There shouldn't be any changes on how `number` works, not from my testing.

> Could NumberInput be an internal component in grafana/ui? So we basically render that component if you try to render an <Input type="number" ...> to keep backward compatability?

Talked to @ryantxu about this and he suggested to just avoid exporting the component for now. I'll hold on pushing the changes until we come to an agreement on what's the best solution for this.

File: public/app/features/transformers/editors/HistogramTransformerEditor.tsx [hunk 5]
```diff
@@ -1,11 +1,11 @@
...
+import React, { useCallback } from 'react';
 import { DataTransformerID, standardTransformers, TransformerRegistryItem, TransformerUIProps } from '@grafana/data';
-
 import {
   HistogramTransformerOptions,
   histogramFieldInfo,
 } from '@grafana/data/src/transformations/transformers/histogram';
-import { InlineField, InlineFieldRow, InlineSwitch, Input } from '@grafana/ui';
+import { InlineField, InlineFieldRow, InlineSwitch } from '@grafana/ui';
+import { NumberInput } from '../../dimensions/editors/NumberInput';
```
Comment (ryantxu) [inline public/app/features/transformers/editors/HistogramTransformerEditor.tsx:8]: bettter would be something like:
```suggestion
import { NumberInput } from '../grafana-ui/src/components/NumberInput/NumberInput.tsx';
```

**Review by ryantxu — APPROVED** [review]
Looks good

**Comment by leventebalogh** [comment]
I agree with @mckn's points, and we also had a quick chat with @adela-almasan end of last week to explain our reasoning.

Personally I think it would be a great addition and could simplify the logic of the "call site" if it doesn't need to deal with how to handle numeric inputs that are out of the range. We are also happy to help out and pair up on this if you would have any questions!

**Why I think it shouldn't be merged in it's current form:**
- **Package integrity** - our main goal with the `@grafana/ui` package is to make it standalone, so it can be consumed on its own and used even outside of Grafana (not depending on its context). Like this we could use the package from core the same way as we do with any other package (not depending on its source). This would enable us to only be concerned about the "public API" of it and would make it easier to simplify the build tooling for both the packages and Grafana core. Introducing code that is only available for Grafana core, and which is not going to be part of the main package bundle unfortunately does not take us into this direction and is introducing "technical debt" that will need to be moved around in the future.
- **Developer experience** - to make these packages easier to use (both for us and plugin developers) we aim to provide only a single "solution" for a problem. This new component introduces another way of creating a numeric input, and it's not that easy to understand when to use which, or to grasp what are the main differences.
- **Testing** - we are also aiming for introducing new functionality to the package only if it has meaningful automated tests, so we can both make sure that maintaining it is going to be easier and that we provide a more solid experience. Although I don't think we should necessarily test "internal" knowledge, this component is currently public for Grafana core and if we leave it as it is, it's most probably going to be used in more and more places.

**Suggestion**
In case we think this is a recurring problem for us with numeric inputs that we would like to solve, then (just like @mckn suggested) I think we should return this `<NumberInput />` component whenever someone specifies to create a `<input type="number" ...>` component, and add automated tests for the different scenarios (this is important, as we need to make sure it behaves exactly the same way as it did before for core and plugins). This way we would still provide a "single way" of creating a numeric input, and it would also be easier to update the logic under hood, in case browsers start supporting the same behaviour natively.

**Comment by ryantxu** [comment]
@leventebalogh/@mckn -- I pretty much agree with what you say, but still trying to figure out how to get from where we are to what we need.  

The crux of the problem is that the [OptionsUI](https://github.com/grafana/grafana/tree/main/packages/grafana-ui/src/components/OptionsUI) components live in `@grafana/ui` so any changes need to live in grafana/ui even though the internal components do not necessarily need to be public components.  We got into this mess because the 
 The root problem is that the number format in https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/histogram/module.tsx#L37 does not behave as expected

This PR (as is) moves the internal number implementation into grafana/ui --- BUT does not expose it in the API.  Only `addNumberInput` will use it.  This seems like a reasonable first step towards adding sanity and at least one fewer way do define a number field.

Changing the behavior of every `<Input type=number .../>` seems like a BIG change (all controlled?) and for sure needs to be done carefully.

Maybe a better option is to move more things from [OptionsUI](https://github.com/grafana/grafana/tree/main/packages/grafana-ui/src/components/OptionsUI) folder into core.  Some items like threshold and value mappings editor are now in [editors](https://github.com/grafana/grafana/blob/main/public/app/core/components/editors/registry.tsx#L44).

**Comment by ryantxu** [comment]
Reading through the comments again... I think the biggest miscommunication is here:
> Since we are exposing a new component from the grafana/ui

This PR does *NOT* expose a new component.  It moves an internal grafana component to grafana/ui, and uses it in the the options builder UI.  For plugins that define options with:
```
.addNumberInput({
        path: 'bucketSize',
        name: histogramFieldInfo.bucketSize.name,
        description: histogramFieldInfo.bucketSize.description,
        settings: {
          placeholder: 'Auto',
          min: 0,
        },
        defaultValue: defaultPanelOptions.bucketSize,
        showIf: (opts, data) => !originalDataHasHistogram(data),
      })
      .addNumberInput({
        path: 'bucketOffset',
        name: histogramFieldInfo.bucketOffset.name,
        description: histogramFieldInfo.bucketOffset.description,
        settings: {
          placeholder: '0',
          min: 0,
        },
        defaultValue: defaultPanelOptions.bucketOffset,
        showIf: (opts, data) => !originalDataHasHistogram(data),
      })
  ```
The number input will display:
image

The behavior change is that:
1. onChange is called:  onBlur + enger
2. min/max are respected all the time (not just after onBlur)

I think our path forward here is either:
1. merge this PR more or less as is
2. move all options UI editors into core so their behavior is not tied to exposed `@grafana/ui`
3. both 1 & 2 :)

----

@leventebalogh -- I like your suggestion for `<input type="number" ...>` but it is a BIG task and not one I am comfortable taking on.  I struggle looking at any of this and wondering why we ever do something different than antd... ie [InputNumber](https://ant.design/components/input-number/)
