### PR TITLE
Dashboard: Keyboard and mouse panel shortcuts improvement

### LINKED ISSUE #47005: Inconsistent keyboard behaviour when interacting with panel
Grafana has recently added the ability to navigate through panels in a dashboard using the keyboard, which is amazing! However, I have noticed that this behaviour can be somewhat inconsistent.

I'm aware that this is a relatively new feature, and is a part of https://github.com/grafana/grafana/issues/36776. I'm not sure if this is covered in that card.

**Steps to reproduce**:
Use the keyboard to navigate to panels in your Grafana dashboard. Attempt to edit or view the panels currently selected by keyboard focus by pressing the 'e' or 'v' keys.

**Actual Result**:
The result I'm seeing is varying a lot. Sometimes nothing happens, other times it loads a panel that I don't currently have keyboard access to.

In the video below, you can see me using my keyboard (by pressing 'tab') to navigate to the panels, with keyboard focus on each panel I am pressing both 'e' and 'v', with nothing happening. Around the 20 second mark, I use my mouse pointer to click on the `status history with time series` panel, which then allows me to use 'e' and 'v' for that panel. However, if I change my keyboard focus to one of the other panels, I am still redirected to the `status history with time series` panel, regardless of where my keyboard focus is.

https://user-images.githubusercontent.com/63413067/160582407-2ab89360-4fda-479a-9d70-a7e28abe2a54.mp4

**Expected Result**:
By pressing 'e' or 'v' I'd be able to edit or view the panel which my keyboard is currently focussed on.

**Relevant WCAG Criteria**:
 [2.1.1 keyboard](https://www.w3.org/TR/WCAG21/#keyboard)

**Environment**:
I am using https://play.grafana.org/ (on 29/03/2022)
- Grafana version: 8.4.4 (fcfb01fae)
- User OS & Browser: Windows 11 + Microsoft Edge

### PR DESCRIPTION
**Pull request by tskarhed**
**What is this feature?**

Gives focus to whichever happened last:
- Mouse move over panel
- Keyboard interaction on panel
 
**Why do we need this feature?**

To support keyboard shortcuts for both mouse and keyboard users 

**Who is this feature for?**

People who use shortcuts.

**Which issue(s) does this PR fix?**:

Fixes #47005
Closes #87213, as this overrides it

https://github.com/grafana/scenes/pull/716 needs to be merged for it to work properly in Scenes dashboards
**Special notes for your reviewer:**

This currently doesn't cover the Scenes use case, as the imports need to be properly available.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard/dashgrid/DashboardGrid.tsx [hunk 1]
```diff
@@ -402,13 +406,24 @@ const GrafanaGridItem = React.forwardRef<HTMLDivElement, GrafanaGridItemProps>((
 
   // props.children[0] is our main children. RGL adds the drag handle at props.children[1]
   return (
-    <div {...divProps} style={{ ...divProps.style }} ref={ref}>
+    <div
+      {...divProps}
+      style={{ ...divProps.style }}
+      onFocus={() => panelAttentionService.setPanelWithAttention(getRefCurrent(ref))}
+      onMouseMove={() => panelAttentionService.setPanelWithAttention(getRefCurrent(ref))}
```
Comment (tskarhed) [inline public/app/features/dashboard/dashgrid/DashboardGrid.tsx:413]: This will cause a lot of function calls. I had previously prevented it by using `hasAttention`, but the service isn't reactive, so it may require more work. Maybe debouncing would help a little? This function call only sets a property on the service.

File: packages/grafana-runtime/src/services/panelAttentionSrv.ts [hunk 2]
```diff
@@ -0,0 +1,31 @@
+export type PanelWithAttention = number | null;
+
+export interface PanelAttentionSrv<T = any> {
```
Comment (tskarhed) [inline packages/grafana-runtime/src/services/panelAttentionSrv.ts:3]: A generic is used here because I cannot access `VizPanel` in runtime. There are issues with setters and getters when using `unknown`, not to speak of the typecasting required in that case.

File: public/app/core/services/panelAttentionSrv.ts [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+
+export class PanelAttentionService implements PanelAttentionSrv<VizPanel> {
+  private panelId: PanelWithAttention = null;
+  private vizPanelWithAttention: VizPanel | null = null;
+
+  getPanelWithAttention(): PanelWithAttention | VizPanel {
+    return this.panelId || this.vizPanelWithAttention;
+  }
+
+  setPanelWithAttention(panelElement: PanelWithAttention | VizPanel): void {
```
Comment (tskarhed) [inline public/app/core/services/panelAttentionSrv.ts:12]: Consider also using ref.current for the scene use case, to simplify typing in runtime.

File: e2e/dashboards-suite/dashboard-panel-attention.spec.ts [hunk 4]
```diff
@@ -0,0 +1,28 @@
+import { e2e } from '../utils';
+
+describe('Dashboard Panel Attention', () => {
```
Comment (tskarhed) [inline e2e/dashboards-suite/dashboard-panel-attention.spec.ts:3]: Is this also needed in the scenes folder?

File: public/app/core/components/AppChrome/AppChrome.tsx [hunk 5]
```diff
@@ -23,7 +24,10 @@ import { TOP_BAR_LEVEL_HEIGHT } from './types';
 export interface Props extends PropsWithChildren<{}> {}
 
 export function AppChrome({ children }: Props) {
-  const { chrome } = useGrafana();
+  const { chrome, keybindings } = useGrafana();
+  const panelAttentionSubscription = appEvents.getStream(SetPanelAttentionEvent).subscribe((event) => {
+    keybindings.setPanelAttention(event.payload.panelId);
+  });
```
Comment (tskarhed) [inline public/app/core/components/AppChrome/AppChrome.tsx:30]: Should this subscription be defined in keybindingSrv instead of having a setter for panel attention? Then there is no risk of someone settings it from elsewhere. The subscription would be initiated and deconstructed in AppChrome

Comment (torkelo) [reply public/app/core/components/AppChrome/AppChrome.tsx:29]: @tskarhed yea, I would move it to the KeybindingSrv constructor 

> The subscription would be initiated and deconstructed in AppChrome

Don't think you need that as KeybingSrv is a singleton @

File: public/app/features/dashboard-scene/scene/keyboardShortcuts.ts [hunk 6]
```diff
@@ -12,6 +14,23 @@ import { onRemovePanel, toggleVizPanelLegend } from './PanelMenuBehavior';
 
 export function setupKeyboardShortcuts(scene: DashboardScene) {
   const keybindings = new KeybindingSet();
+  let vizPanelKey: string | null = null;
+
+  const panelAttentionSubscription = appEvents.getStream(SetPanelAttentionEvent).subscribe((event) => {
```
Comment (torkelo) [inline public/app/features/dashboard-scene/scene/keyboardShortcuts.ts:19]: there is a simpler version where you can just call subscribe directly on appEvents:
`appEvent.subscribe(SetPanelAttentionEvent,  (event) => { ...`

File: public/app/features/dashboard-scene/scene/keyboardShortcuts.ts [hunk 7]
```diff
@@ -12,6 +14,23 @@ import { onRemovePanel, toggleVizPanelLegend } from './PanelMenuBehavior';
...
+
+  function withFocusedPanel(scene: DashboardScene, fn: (vizPanel: VizPanel) => void) {
+    return () => {
+      const vizPanel = sceneGraph.findObject(scene, (o) => o.state.key === vizPanelKey);
+      if (vizPanel && vizPanel instanceof VizPanel) {
+        fn(vizPanel);
+        return;
+      }
+    };
+  }
```
Comment (tskarhed) [inline public/app/features/dashboard-scene/scene/keyboardShortcuts.ts:33]: I consider removing this, as the imports in the PRs are not working correctly until Scenes is pointing to the correct version of grafana-data and grafana-ui.

**Comment by tskarhed** [comment]
I removed the Scenes use case for now, as the imports don't work properly at the moment. I am not sure when the Scenes package.json is updated, but the updates from this PR are needed.

File: packages/grafana-ui/src/components/PanelChrome/PanelChrome.tsx [hunk 8]
```diff
@@ -240,7 +250,9 @@ export function PanelChrome({
       className={cx(styles.container, { [styles.transparentContainer]: isPanelTransparent })}
       style={containerStyles}
       data-testid={testid}
-      tabIndex={0} //eslint-disable-line jsx-a11y/no-noninteractive-tabindex
+      tabIndex={0} // eslint-disable-line jsx-a11y/no-noninteractive-tabindex
+      onFocus={() => onFocus?.()}
+      onMouseMove={() => onMouseMove?.()}
```
Comment (torkelo) [inline packages/grafana-ui/src/components/PanelChrome/PanelChrome.tsx:255]: onFocus={onFocus}
onMouseMove ={onMouseMove}

**Review by torkelo — APPROVED** [review]

**Comment by tskarhed** [comment]
@torkelo When will these changes be available in Scenes?

**Comment by torkelo** [comment]
@tskarhed ? when https://github.com/grafana/scenes/pull/716 is merged (with a release label), that will trigger a new scenes version, then we need to update scenes lib in core

**Comment by tskarhed** [comment]
@torkelo Okay, but with the import issues from grafana/ui there, doesn't it need to update the grafana/ui version in order to actually try the new props on PanelChrome in Scenes?

**Comment by torkelo** [comment]
@tskarhed not really, when core uses scenes both will use @grafana/ui version that is in core (latest)

**Comment by tskarhed** [comment]
@torkelo Okay, then I have idea why I can't get `onFocus` or `onMouseMove` to work in https://github.com/grafana/scenes/pull/716
