### PR TITLE
Database: Initialize xorm with an empty schema for postgres

### LINKED ISSUE #16720: bug with upgrade from 6.0.2 to 6.1.3 or 6.1.4 : column account_id does not exist
after updating grafana from 6.0.2 to 6.1.3 or 6.1.4 with yum, I get the following errors :

t=2019-04-10T16:33:25+0200 lvl=eror msg=“Executing migration failed” logger=migrator id=“copy data_source v1 to v2” error=“pq: column “account_id” does not exist”
t=2019-04-10T16:33:25+0200 lvl=eror msg=“Exec failed” logger=migrator error=“pq: column “account_id” does not exist” sql="INSERT INTO “user” (“id”\n, “version”\n, “login”\n, “name”\n, “org_id”\n, “is_admin”\n, “created”\n, “email”\n, “password”\n, “salt”\n, “rands”\n, “company”\n, “updated”) SELECT “id”\n, “version”\n, “login”\n, “name”\n, “account_id”\n, “is_admin”\n, “created”\n, “email”\n, “password”\n, “salt”\n, “rands”\n, “company”\n, “updated” FROM “user_v1"”
t=2019-04-10T16:33:25+0200 lvl=eror msg=“Server shutdown” logger=server reason=“Service init failed: Migration failed err: pq: column “account_id” does not exist”

t=2019-04-10T16:33:25+0200 lvl=info msg=“Executing migration” logger=migrator id=“Rename table user to user_v1 - v1”
t=2019-04-10T16:33:25+0200 lvl=eror msg=“Executing migration failed” logger=migrator id=“Rename table user to user_v1 - v1” error=“pq: relation “user_v1” already exists”
t=2019-04-10T16:33:25+0200 lvl=eror msg=“Exec failed” logger=migrator error=“pq: relation “user_v1” already exists” sql="ALTER TABLE “user” RENAME TO “user_v1"”
t=2019-04-10T16:33:25+0200 lvl=eror msg=“Server shutdown” logger=server reason=“Service init failed: Migration failed err: pq: relation “user_v1” already exists”

**Environment**:
- Grafana version: 6.0.2 upgrade to 6.1.3 or 6.1.4
- OS Grafana is installed on:CentOS Linux release 7.5.1804
- BDD : PostgreSQL 9.4.10

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
xorm introduced some changes in
https://github.com/go-xorm/xorm/pull/824 and
https://github.com/go-xorm/xorm/pull/876 which by default will use
public as the postgres schema and this was a breaking change compared
to before. Grafana has implemented a custom postgres dialect so above
changes wasn't a problem here. However, Grafana's custom database
migration was using xorm dialect to check if the migration table exists
or not.
For those using a custom search_path (schema) in postgres configured on
server, database or user level the migration table check would not find
the migration table since it was looking in public schema due to xorm
changes above. This had the consequence that Grafana's database
migration failed the second time since migration had already run
migrations in another schema.
This change will make xorm use an empty default schema for postgres and
by that mimic the functionality of how it was functioning before
xorm's changes above.

**Which issue(s) this PR fixes**:
Fixes #16720 

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/sqlstore/sqlstore.go [hunk 1]
```diff
@@ -37,6 +37,8 @@ var (
 const ContextSessionName = "db-session"
 
 func init() {
+	xorm.DefaultPostgresSchema = ""
```
Comment (bergquist) [inline pkg/services/sqlstore/sqlstore.go]: I think this deserves a comment explaining why.

Comment (marefr) [reply pkg/services/sqlstore/sqlstore.go]: Git commit?

Comment (bergquist) [reply pkg/services/sqlstore/sqlstore.go]:
```suggestion
	// This change will make xorm use an empty default schema for postgres and
	// by that mimic the functionality of how it was functioning before
	// xorm's changes above.
	xorm.DefaultPostgresSchema = ""
```

**Review by bergquist — APPROVED** [review]
LGTM!
