### PR TITLE
Loki/Prometheus: Fix wrong queries executed in split view

### LINKED ISSUE #60059: Explore: After split screen, Shift-Enter in left pane triggers query evaluation in right pane!
**What happened**:
See this video:
https://www.loom.com/share/3e2f31bdd4b448e2a8678b47b610ab60

Note I reported the other error encountered in that video in #60060 

It's certainly reproduced in the video, very quickly and simply. I think I:
- Wrote a PromQL query
- Ran it (I think)
- Split the screen
- Edited the query in the left-hand pane of the split screen
- hit Shift->Enter to execute from the keyboard shortcut
- Right hand pane (not focused) query got executed, but left hand pane (focused) did not execute

**What you expected to happen**:
Shift-Enter in left pane should **always** refresh query on that side

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:
nope

**Environment**:

I used "Explore to Dashboard" and then "Panel Help" to quickly get the environment data - here it is:

| Key | Value |
|--|--|
| Panel | timeseries @ 9.4.0-45061pre (29d2f86955) |
| Grafana | 9.4.0-45061pre (29d2f86955) // Enterprise |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "id": 2,
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "type": "timeseries",
      "title": "Reproduced with embedded data",
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "type": "timeseries-multi",
                  "custom": {
                    "resultType": "vector"
                  },
                  "executedQueryString": "Expr: count(grafanacloud_instance_active_series)\nStep: 15s",
                  "preferredVisualisationType": "graph"
                },
                "name": "count(grafanacloud_instance_active_series)",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 15000
                    }
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {},
                    "config": {
                      "displayNameFromDS": "count(grafanacloud_instance_active_series)"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1670535180000
                  ],
                  [
                    3
                  ]
                ]
              }
            },
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "type": "timeseries-multi",
                  "custom": {
                    "resultType": "matrix"
                  },
                  "executedQueryString": "Expr: count(grafanacloud_instance_active_series)\nStep: 15s",
                  "preferredVisualisationType": "graph"
                },
                "name": "count(grafanacloud_instance_active_series)",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 15000
                    }
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {},
                    "config": {
                      "displayNameFromDS": "count(grafanacloud_instance_active_series)"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1670534880000,
                    1670534895000,
                    1670534910000,
                    1670534925000,
                    1670534940000,
                    1670534955000,
                    1670534970000,
                    1670534985000,
                    1670535000000,
                    1670535015000,
                    1670535030000,
                    1670535045000,
                    1670535060000,
                    1670535075000,
                    1670535090000,
                    1670535105000,
                    1670535120000,
                    1670535135000,
                    1670535150000,
                    1670535165000,
                    1670535180000
                  ],
                  [
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3
                  ]
                ]
              }
            }
          ]
        }
      ],
      "options": {
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "legend": {
          "showLegend": true,
          "displayMode": "list",
          "placement": "bottom",
          "calcs": []
        }
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "drawStyle": "line",
            "lineInterpolation": "linear",
            "barAlignment": 0,
            "lineWidth": 1,
            "fillOpacity": 0,
            "gradientMode": "none",
            "spanNulls": false,
            "showPoints": "auto",
            "pointSize": 5,
            "stacking": {
              "mode": "none",
              "group": "A"
            },
            "axisPlacement": "auto",
            "axisLabel": "",
            "axisColorMode": "text",
            "scaleDistribution": {
              "type": "linear"
            },
            "axisCenteredZero": false,
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "color": {
            "mode": "palette-classic"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "value": null,
                "color": "green"
              },
              {
                "value": 80,
                "color": "red"
              }
            ]
          }
        },
        "overrides": []
      }
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >timeseries @ 9.4.0-45061pre (29d2f86955)</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[prometheus]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 2 frames, 4 fields, 22 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>9.4.0-45061pre (29d2f86955) // Enterprise</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"id\": 1,\n  \"gridPos\": {\n    \"x\": 0,\n    \"y\": 0,\n    \"w\": 12,\n    \"h\": 8\n  },\n  \"type\": \"timeseries\",\n  \"title\": \"New Panel\",\n  \"datasource\": {\n    \"type\": \"prometheus\",\n    \"uid\": \"grafanacloud-usage\"\n  },\n  \"targets\": [\n    {\n      \"refId\": \"A\",\n      \"datasource\": {\n        \"type\": \"prometheus\",\n        \"uid\": \"grafanacloud-usage\"\n      },\n      \"editorMode\": \"code\",\n      \"expr\": \"count(grafanacloud_instance_active_series)\",\n      \"legendFormat\": \"__auto\",\n      \"range\": true,\n      \"instant\": true,\n      \"key\": \"Q-a66e5c10-92a0-44ce-bb68-c8e740703c9a-0\"\n    }\n  ],\n  \"options\": {\n    \"tooltip\": {\n      \"mode\": \"single\",\n      \"sort\": \"none\"\n    },\n    \"legend\": {\n      \"showLegend\": true,\n      \"displayMode\": \"list\",\n      \"placement\": \"bottom\",\n      \"calcs\": []\n    }\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"drawStyle\": \"line\",\n        \"lineInterpolation\": \"linear\",\n        \"barAlignment\": 0,\n        \"lineWidth\": 1,\n        \"fillOpacity\": 0,\n        \"gradientMode\": \"none\",\n        \"spanNulls\": false,\n        \"showPoints\": \"auto\",\n        \"pointSize\": 5,\n        \"stacking\": {\n          \"mode\": \"none\",\n          \"group\": \"A\"\n        },\n        \"axisPlacement\": \"auto\",\n        \"axisLabel\": \"\",\n        \"axisColorMode\": \"text\",\n        \"scaleDistribution\": {\n          \"type\": \"linear\"\n        },\n        \"axisCenteredZero\": false,\n        \"hideFrom\": {\n          \"tooltip\": false,\n          \"viz\": false,\n          \"legend\": false\n        },\n        \"thresholdsStyle\": {\n          \"mode\": \"off\"\n        }\n      },\n      \"color\": {\n        \"mode\": \"palette-classic\"\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"value\": null,\n            \"color\": \"green\"\n          },\n          {\n            \"value\": 80,\n            \"color\": \"red\"\n          }\n        ]\n      }\n    },\n    \"overrides\": []\n  }\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: New Panel // 2022-12-08 21:33:12",
  "tags": [
    "debug",
    "debug-timeseries"
  ],
  "time": {
    "from": "2022-12-08T21:28:12.323Z",
    "to": "2022-12-08T21:33:12.324Z"
  }
}
```
</details>

### PR DESCRIPTION
**Pull request by svennergr**
**What is this feature?**

Currently the wrong query is executed when multiple Monaco editors are present. This PR adds a `context` value, which has to be true, to the relevant `editor.addCommand` call.

**Which issue(s) does this PR fix?**:

Fixes #60059

### CODE REVIEW

**Comment by svennergr** [comment]
@grafana/observability-metrics / @matyax before adding tests to this, how do we feel about fixing it like this? I haven't figured out a better way.

File: public/app/plugins/datasource/prometheus/components/monaco-query-field/MonacoQueryField.tsx [hunk 1]
```diff
@@ -87,11 +88,13 @@ const getStyles = (theme: GrafanaTheme2, placeholder: string) => {
 };
 
 const MonacoQueryField = (props: Props) => {
-  // we need only one instance of `overrideServices` during the lifetime of the react component
+  // we need only one instance of `overrideSerices` during the lifetime of the react component
```
Comment (matyax) [inline public/app/plugins/datasource/prometheus/components/monaco-query-field/MonacoQueryField.tsx]:
```suggestion
  // we need only one instance of `overrideServices` during the lifetime of the react component
```

**Comment by matyax** [comment]
> how do we feel about fixing it like this?

At first glance, I don't like this approach, which seems to resolve the issue in a hacky way. Since I can't see right now the root cause of the bug, that's all the feedback I have.

File: public/app/plugins/datasource/prometheus/components/monaco-query-field/MonacoQueryField.tsx (hunk 1 above)
Comment (svennergr) [reply public/app/plugins/datasource/prometheus/components/monaco-query-field/MonacoQueryField.tsx]: Should have been fixed in https://github.com/grafana/grafana/pull/60172/commits/73e283a17f7a4e0610b9ba212a136cfdcf189da5 already 😁

**Comment by matyax** [comment]
BTW, unfortunately you would not be able to add a regression test for this bug because the editor doesn't render in React tests.

**Comment by svennergr** [comment]
> > how do we feel about fixing it like this?
> 
> At first glance, I don't like this approach, which seems to resolve the issue in a hacky way. Since I can't see right now the root cause of the bug, that's all the feedback I have.

Btw, I was able to reproduce this with 2 editors in the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html).

**Comment by matyax** [comment]
I was just looking there 👀

**Comment by matyax** [comment]
If this solves the issue, let's go with this. Nice work 🤝

**Review by matyax — APPROVED** [review]
🥇

**Comment by matyax** [comment]
Locally verified.

**Review by gtk-grafana — APPROVED** [review]
LGTM, the fix is working locally for me. Thanks for digging into this!
