### PR TITLE
Geomap: Fix tooltip field name regression

### LINKED ISSUE #73976: Geomap: unwanted "1" in tooltip in v10.1.0 after migration from v9.5.1
### What happened?

In v9.5.1 the tooltip of GeoJSON layer was correct.
изображение

In v10.1.0 the tooltip has unwanted "1" next to properties fields.
изображение

### What did you expect to happen?

The fields in tooltip box should not contain unwanted symbols "1"

### Did this work before?

There is no issue in v9.5.1

### How do we reproduce it?

Just go to play.grafana.org -> [Panel Tests - Geomap](https://play.grafana.org/d/panel-geomap/panel-tests-geomap).

You can also create the simple CSV content

foo,bar,lat,lon,data
hello,world,35.687,-105.938,"TEST"

изображение

### PR DESCRIPTION
**Pull request by nmarrs**
Address regression introduced by https://github.com/grafana/grafana/pull/67872 that caused tooltip field name to have "1" appended to them

Before

https://github.com/grafana/grafana/assets/22381771/fe4834fa-475f-48ac-97d8-b29d497116c2

After

https://github.com/grafana/grafana/assets/22381771/5b96d2a9-a632-4651-8ab0-4c5d1262ff78

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/73976

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/visualization/data-hover/DataHoverView.tsx [hunk 1]
```diff
@@ -72,8 +72,13 @@ export const DataHoverView = ({ data, rowIndex, columnIndex, sortOrder, mode, he
       });
     }
 
+    // Sanitize field by removing hovered property to fix unique display name issue
+    const sanitizedField = { ...field };
+    // Not the cleanest approach - but necessary to avoid TS error when trying to delete a required property
+    delete (sanitizedField as { hovered?: boolean }).hovered;
+
```
Comment (ashharrison90) [inline public/app/features/visualization/data-hover/DataHoverView.tsx:79]: instead of this, could we do something like:
```typescript
    const { hovered, ...sanitizedField } = field;

    displayValues.push({
      name: getFieldDisplayName(sanitizedField, data),
      value,
      valueString: formattedValueToString(fieldDisplay),
      highlight: hovered,
    });
```
?

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍 

(side note: have you got the precommit hooks installed? if you run `make lefthook-install` it should then handle all the betterer stuff for you)

**Comment by nmarrs** [comment]
Based on the breaking tests it seems like this approach isn't viable breaking previous functionality - will need to rethink this
