### PR TITLE
Previews: create crawler auth setup service

### LINKED ISSUE #46968: Previews: removing the `fixed:datasources:reader` fixed role assignment breaks authorization model of the crawler process
To reproduce:

1. Create a dashboard using at least one non-grafana data source. 
2. Remove the `fixed:datasources:reader` fixed role assignment
   - Example provisioning file:
```
# config file version
apiVersion: 1

# list of default built-in role assignments that should be removed
removeDefaultAssignments:
  - builtInRole: "Admin"
    fixedRole: "fixed:datasources:reader"
```

3. Run the crawler 
4. Previews of dashboards with non-grafana data sources will be blank

### PR DESCRIPTION
**Pull request by ArturWierzbicki**
**What this PR does / why we need it**:

1. extracted crawler auth setup from the main service so that we can stub it out in the enterprise version
2. created `RetrieveServiceAccountIdByName` method in `ServiceAccount` service required for the enterprise setup to work

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/46968

**Special notes for your reviewer**:

More context can be found in this slack thread: https://raintank-corp.slack.com/archives/C01LU2Y5527/p1648732275362749

### CODE REVIEW

File: pkg/services/serviceaccounts/database/database.go [hunk 1]
```diff
@@ -231,6 +231,47 @@ func (s *ServiceAccountsStoreImpl) RetrieveServiceAccount(ctx context.Context, o
 	return serviceAccount, nil
 }
 
+func (s *ServiceAccountsStoreImpl) RetrieveServiceAccountIdByName(ctx context.Context, orgID int64, name string) (int64, error) {
```
Comment (eleijonmarck) [inline pkg/services/serviceaccounts/database/database.go:234]: This makes sense to implement

**Comment by eleijonmarck** [comment]
crawler loooks amaze!

crawler

**Review by eleijonmarck — APPROVED** [review]

**Comment by ArturWierzbicki** [comment]
🚀
