### PR TITLE
Azuremonitor: Multi resource fix

### LINKED ISSUE #67178: Azure Monitor resource picker doesn't select multiple resources when using a multi-value variable
## What happened:
When using a multi-select variable with Azure Monitor resource picker's Advanced option, the resulting Log Analytics query always fails because the picker doesn't parse the comma-separated list of resource ids.

## What you expected to happen:
Log Analytics queries successfully execute against multiple resources selected in the multi-select variable.

## How to reproduce it (as minimally and precisely as possible):
Here is a screenshot that shows the issue:
image

Please note that I am not using actual resource ids in the variable in order to protect PII.

## Environment:
- Grafana version: 9.4.8
- Data source type & version: Azure Monitor data source
- OS Grafana is installed on: Linux
- User OS & Browser: Windows & Edge
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by bossinc**
Before when you had a template variable with multiple resources, it would not correctly format multiple resources. Now it lists each resource in an array.

### CODE REVIEW

File: public/app/plugins/datasource/azuremonitor/azure_log_analytics/azure_log_analytics_datasource.ts [hunk 1]
```diff
@@ -174,6 +175,21 @@ export default class AzureLogAnalyticsDatasource extends DataSourceWithBackend<
     return target;
   }
 
+  private expandResourcesForMultipleVariables(resources: string[] | undefined, scopedVars: ScopedVars, templateSrv: TemplateSrv): string[] | undefined {
```
Comment (aangelisc) [inline public/app/plugins/datasource/azuremonitor/azure_log_analytics/azure_log_analytics_datasource.ts:178]: What's the thinking for making this private? I wonder if we make this a util function and update other areas of the codebase to make sure this works elsewhere, wdyt?

**Review by aangelisc — APPROVED** [review]
Just a suggestion but this can be carried out in a separate PR.
