### PR TITLE
Fix: Install plugins when they have no plugin archive info(catalog en…

### LINKED ISSUE #109023: Plugin: GF_INSTALL_PLUGINS Upgrading custom plugins does not work
### What happened?

Hello,

we have several plugins developed in-house, but since updating to Grafana 12, we can no longer automatically update them using the `GF_INSTALL_PLUGINS` environment variable in our Helm Chart by increasing the version number.

This bug was introduced in https://github.com/grafana/grafana/pull/105145 by @s4kh 

We can use the GF_INSTALL_PLUGINS_FORCE env var to force the old way of course. The official helm chart should be updated to support the new `GF_PLUGIN_PREINSTALL(_SYNC)` env var. I created an issue for this https://github.com/grafana/helm-charts/issues/3831

### What did you expect to happen?

During boot Grafana installs the newer version of our plugin.

### Did this work before?

Yes

### How do we reproduce it?

1. Specify the plugin to install
```yaml
env:
  GF_INSTALL_PLUGINS: "https://s3.our.domain/grafana-plugins/our-plugin-datasource-1.2.0+linux.zip;our-plugin-datasource
```
2. Increase the version number in the URL
```yaml
env:
  GF_INSTALL_PLUGINS: "https://s3.our.domain/grafana-plugins/our-plugin-datasource-1.2.1+linux.zip;our-plugin-datasource
```
3. Restart Grafana
4. The logs say the plugin is installed, and it is, but the version has not increased.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 12.1.0
OS: Windows
Browser: Edge

### Grafana platform?

Kubernetes

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by s4kh**
**What is this feature?**

Updates given plugin in `GF_INSTALL_PLUGINS`.

**Why do we need this feature?**

Private plugins will return `ErrResponse4xx` for  [archive info](https://github.com/grafana/grafana/blob/main/pkg/services/pluginsintegration/plugininstaller/service.go#L105) thus won't update when using preinstall feature. But needs to be updated. 

**Who is this feature for?**

GF_INSTALL_PLUGINS, plugin preinstall feature user.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/109023

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: pkg/services/pluginsintegration/plugininstaller/service.go [hunk 1]
```diff
@@ -108,6 +108,10 @@ func (s *Service) shouldUpdate(ctx context.Context, pluginID, currentVersion str
 		return false
 	}
 
+	// Private plugins won't have entry in our catalog
+	if info == nil || info.Version == "" {
```
Comment (wbrowne) [inline pkg/services/pluginsintegration/plugininstaller/service.go]: This doesn't feel like the right place to capture this scenario. IIUC we're dealing with plugins who have a URL associated with them, no? Could we just capture that in `installPlugins` by checking if URL is set?

Comment (s4kh) [inline pkg/services/pluginsintegration/plugininstaller/service.go]: `GetPluginArchiveInfo` -> calls the gcom `/api/plugins/:pluginId/versions` that will throw `ErrResponse4xx` for private plugins since it does not exist.

Comment (s4kh) [reply pkg/services/pluginsintegration/plugininstaller/service.go]: Yeah, I am thinking about what happens for our plugins that do not specify version as well.

File: pkg/services/pluginsintegration/plugininstaller/service.go [hunk 2]
```diff
@@ -101,7 +101,10 @@ func (s *Service) installPluginsWithTimeout(pluginsToInstall []setting.InstallPl
 	}
 }
 
-func (s *Service) shouldUpdate(ctx context.Context, pluginID, currentVersion string) bool {
+func (s *Service) shouldUpdate(ctx context.Context, pluginID, currentVersion string, pluginURL string) bool {
+	if pluginURL != "" {
```
Comment (s4kh) [inline pkg/services/pluginsintegration/plugininstaller/service.go:107]: @andresmgot @wbrowne With this change(URL set and no version specified) we are allowing downgrade.

File: pkg/setting/setting_plugins_test.go [hunk 3]
```diff
@@ -394,6 +394,17 @@ func Test_migrateInstallPluginsToPreinstallPluginsSync(t *testing.T) {
 				},
 			},
 		},
+		{name: "parse private plugin",
+			installPluginsVal: "https://s3.our.domain/grafana-plugins/our-plugin-datasource-1.2.0+linux.zip;our-plugin-datasource",
```
Comment (andresmgot) [inline pkg/setting/setting_plugins_test.go]:
```suggestion
		{
			name: "parse private plugin",
			installPluginsVal: "https://s3.our.domain/grafana-plugins/our-plugin-datasource-1.2.0+linux.zip;our-plugin-datasource",
```

I'd also add a test for the case `https://s3.our.domain/grafana-plugins/our-plugin-datasource-1.2.0+linux.zip;our-plugin-datasource 1.2.0`, to verify it parsers everything.

**Review by andresmgot — APPROVED** [review]
LGTM

File: pkg/services/pluginsintegration/plugininstaller/service.go (hunk 2 above)
Comment (wbrowne) [reply pkg/services/pluginsintegration/plugininstaller/service.go:107]: Can we add a comment here? Something like:
```suggestion
	// If the plugin is installed from a URL, we cannot check for updates as we do not have the version information
	// from the repository. Therefore, we assume that the plugin should be updated if the URL is provided.
	if pluginURL != "" {
```
