### PR TITLE
Fixed url of back button in datasource edit page, when root_url configured

### LINKED ISSUE #15679: root_url path is ignored in Grafana 6.0 datasource page 'Back' button
Please include this information:
### What Grafana version are you using?
6.0
### What datasource are you using?
InfluxDB, true for other data sources also. 
### What OS are you running grafana on?
darwin
### What did you do?
upgraded to Grafana 6.0. On any datasource page, clicked on Back button to see the list of configured datasources.
### What was the expected result?
It should come to datasource list page.
### What happened instead?
It did not consider root_url path and took the page to the root domain.

### PR DESCRIPTION
**Pull request by dprokop**
Fixes #15679

### CODE REVIEW

File: public/app/features/datasources/settings/ButtonRow.tsx [hunk 1]
```diff
@@ -23,7 +24,7 @@ const ButtonRow: FC<Props> = ({ isReadOnly, onDelete, onSubmit, onTest }) => {
       <button type="submit" className="btn btn-danger" disabled={isReadOnly} onClick={onDelete}>
         Delete
       </button>
-      <a className="btn btn-inverse" href="/datasources">
+      <a className="btn btn-inverse" href={datasourcesPageHref}>
```
Comment (torkelo) [inline public/app/features/datasources/settings/ButtonRow.tsx]: Think the simple solution is just to remove first forward slash. Then it will be relative to base href which is updated if you have appSubUrl

Comment (marefr) [reply public/app/features/datasources/settings/ButtonRow.tsx]: Wouldn't it be relative to base href + the current directory you're on? We're using appSubUrl everywhere else, why not here?

Comment (torkelo) [reply public/app/features/datasources/settings/ButtonRow.tsx]: No it’s always relative to baseHref I think (when you use base href). Was not aware we use appSubUrl in hrefs j. Frontend thought only in backend

Comment (dprokop) [reply public/app/features/datasources/settings/ButtonRow.tsx]: I'm not a big fan of urls without leading slash @torkelo, especially that the behaviour of with/without leading slash isn't that obvious (i.e. see Marcus's comment).

In this case I have introduced the prop, to avoid config import in this dummy component. I think we should perform this navigation in callback prop (`onBackButtonClick`) if we had a location service or something alike.

Comment (torkelo) [reply public/app/features/datasources/settings/ButtonRow.tsx]: Yes, maybe it’s best. Can’t remember what the advantage was for using relative to base href was

Comment (marefr) [reply public/app/features/datasources/settings/ButtonRow.tsx]: Maybe something related to how angular route/location service works?

Comment (torkelo) [reply public/app/features/datasources/settings/ButtonRow.tsx]: Think I might be have mixed it up with something else, I know we have had issues with using absolute urls (as that require an accurate root_url so limit that to only when it's needed).

So I think think this is fine, but do not think we need a prop for this, there is no reason not to use config directly in ButtonRow.

Comment (dprokop) [reply public/app/features/datasources/settings/ButtonRow.tsx]: Yes, you are right Torkel. I was thinking about making ButtonRow as dummy as possible, but since it's not grafana/ui component we can use app config there.

**Comment by torkelo** [comment]
Think someone missed adding a cherry pick label to this as this was not cherry picked to v6.0.1 .

Moving to 6.0.2 milestone and adding cherry pick label so it gets added to next patch release.
