### PR TITLE
Templating: Update variables on location changed

### LINKED ISSUE #9259: Table panel: Update current dashboard template variable via cell links
- Grafana v4.6.0

To reproduce:

1. Set a table-column to `Render value as link`

1. Create a link that points to the current dashboard but with changed variables (e.g. `https://example.com/dashboard/db/overview?var-server=$__cell`)

1. Try to click the link. The address bar changes but the page does not reload.

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes #9259, #8249

The template_srv is not exposed to react plugins... and I don't think there is a quick/easy way to do that.  As a workaround we can set variables by changing the URL -- either though constructing an regular link, or by calling:
```
      getLocationSrv().update({
        partial: true,
        query: {
          'var-test':'something',
         },
      });
```
This should update the variables and refresh the dashboard.

### CODE REVIEW

File: public/app/plugins/panel/text2/TextPanel.tsx [hunk 1]
```diff
@@ -1,5 +1,5 @@
 // Libraries
-import React, { PureComponent } from 'react';
+import React, { PureComponent, ChangeEvent } from 'react';
```
Comment (ryantxu) [inline public/app/plugins/panel/text2/TextPanel.tsx]: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

The changes to this file are so we have a button somewhere in a panel that does the same thing.... none should actually get merged.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

File: public/app/features/templating/variable_srv.ts [hunk 2]
```diff
@@ -303,6 +311,42 @@ export class VariableSrv {
...
+      this.originalUrl = this.$location.url();
+      const queryParams = state.location.query; //this.$location.search();
+      if (!Object.keys(queryParams).some(k => k.indexOf('var-') === 0)) {
+        return this.$q.when({});
+      }
+      console.log('VAR Changed', queryParams);
+      return this.$q
+        .all(
+          this.variables.map(variable => {
+            return this.processVariable(variable, queryParams);
```
Comment (torkelo) [inline public/app/features/templating/variable_srv.ts]: we can't really use this function as is, it is only for dashboard init flows (it checks variable refresh options and will update variables (trigger the variable query) even if it has not changed).

File: public/app/features/templating/variable_srv.ts [hunk 3]
```diff
@@ -303,6 +311,42 @@ export class VariableSrv {
...
+          })
+        )
+        .then(() => {
+          this.templateSrv.updateIndex();
+          this.dashboard.templateVariableValueUpdated();
+          this.dashboard.startRefresh();
```
Comment (torkelo) [inline public/app/features/templating/variable_srv.ts]: We can't do this on every location update. Not sure why index needs updating, and we cant issue a full dashboard refresh on every location change without identifying if a variable value was actually changed.

File: public/app/core/reducers/location.ts [hunk 4]
```diff
@@ -29,6 +30,24 @@ export const locationReducer = (state: LocationState = initialState, action: Act
 
     if (payload.partial) {
       query = _.defaults(query, state.query);
+    }
```
Comment (ryantxu) [inline public/app/core/reducers/location.ts]: @hugohaggmark -- I'm sure this breaks all kinds of redux rules... is there a better place for this to live?

File: public/app/features/templating/variable_srv.ts (hunk 2 above)
Comment (ryantxu) [reply public/app/features/templating/variable_srv.ts]: This was all a copy from #16128 -- I have updated things so that the location change id detected from redux and that broadcasts an event for the variableSrv

**Comment by ryantxu** [comment]
@torkelo / @hugohaggmark -- I reworked this so it is using BridgeSrv now.  Can you take another look?

**Review by hugohaggmark — APPROVED** [review]
I think this looks much better, great work! Would be nice to add some tests for this as well.

File: public/app/features/templating/variable_srv.ts [hunk 5]
```diff
@@ -286,6 +291,22 @@ export class VariableSrv {
     return this.variableUpdated(variable);
   }
 
+  templateVarsChangedInUrl(vars: UrlQueryMap) {
+    const update: Array<Promise<any>> = [];
+    this.variables.forEach(v => {
+      const key = `var-${v.name}`;
+      if (vars.hasOwnProperty(key)) {
+        update.push(v.setValueFromUrl(vars[key]));
```
Comment (ryantxu) [inline public/app/features/templating/variable_srv.ts]: @torkelo -- is there any way to know if this actually makes a change?

This function should only be called when the URL parameters change... but depending on how it is triggered I think that can happen twice.

File: public/app/features/templating/variable_srv.ts [hunk 6]
```diff
@@ -286,6 +291,22 @@ export class VariableSrv {
     return this.variableUpdated(variable);
   }
 
+  templateVarsChangedInUrl(vars: UrlQueryMap) {
+    const update: Array<Promise<any>> = [];
+    this.variables.forEach(v => {
```
Comment (torkelo) [inline public/app/features/templating/variable_srv.ts]: => for of :)

File: public/app/core/services/bridge_srv.ts [hunk 7]
```diff
@@ -62,6 +65,18 @@ export class BridgeSrv {
         });
         console.log('store updating angular $location.url', url);
       }
+
+      // Check for template variable changes
+      if (this.lastQuery) {
```
Comment (torkelo) [inline public/app/core/services/bridge_srv.ts]: think we also need to check if we are still on the same dashboard. This location change could changing dashboard  (to another dashboard with variables in the url)

File: public/app/core/services/bridge_srv.ts [hunk 8]
```diff
@@ -62,6 +65,18 @@ export class BridgeSrv {
...
+        const changes = findTemplateVarChanges(state.location.query, this.lastQuery);
+        if (changes) {
+          const dash = getDashboardSrv().getCurrent();
+          if (dash) {
+            dash.events.emit(CoreEvents.templateVarsChangedInUrl, changes);
```
Comment (torkelo) [inline public/app/core/services/bridge_srv.ts]: technically bridgeSrv could just inject variableSrv and call templateVarsChangedInUrl as both are angular services, but this is fine as well

File: public/app/features/templating/variable_srv.ts (hunk 5 above)
Comment (torkelo) [reply public/app/features/templating/variable_srv.ts]: > @torkelo -- is there any way to know if this actually makes a change?
> This function should only be called when the URL parameters change... but depending on how it is triggered I think that can happen twice.

not sure what you mean

**Review by torkelo — APPROVED** [review]
I like this approach, but think we need to check if only vars has changed (and not path as well)
