### PR TITLE
Graphite Plugin: fix annotation migration regression with ref-ids

### LINKED ISSUE #53275: "Query error: -1 Request was aborted" regression with 9.1.0-beta1; graphite datasource
Hello

It seems the grafana:latest docker image updated to 9.1.0-beta1 recently (I'm not 100% sure this is intended, but it's how we saw this).

Some of our panels have started breaking with "Query error: -1 Request was aborted".  I'm not sure how useful it is, but in the web developer console we get an error:

```
runRequest.catchError {"type":"cancelled","cancelled":true,"data":null,"status":-1,"statusText":"Request was aborted","config":{"method":"POST","url":"https://graphite.opendev.org/render","data":"target=scale(divideSeries(stats.gauges.afs.afs02_dfw_openstack_org.part.vicepa.used%2C%20stats.gauges.afs.afs02_dfw_openstack_org.part.vicepa.total)%2C%20100)&from=1659552968&until=1659574570&format=json&maxDataPoints=100","headers":{"Content-Type":"application/x-www-form-urlencoded"},"requestId":"OpenStack.panelId.4","inspect":{"type":"graphite"},"retry":0,"hideFromInspector":false}} react_devtools_backend.js:4026:25
    overrideMethod react_devtools_backend.js:4026
    S runRequest.ts:151
    RxJS 29
    internalFetch backend_srv.ts:127
    H ResponseQueue.ts:32
    RxJS 6
    H ResponseQueue.ts:37
    _ FetchQueueWorker.ts:56
    RxJS 21
    B FetchQueue.ts:76
    B FetchQueue.ts:55
    RxJS 6
    B FetchQueue.ts:59
    fetch backend_srv.ts:112
    RxJS 69
    pipeToSubject PanelQueryRunner.ts:290
    run PanelQueryRunner.ts:271
    runAllPanelQueries PanelModel.ts:333
    se PanelChrome.tsx:321
    RxJS 3
    n EventBus.ts:37
    emit index.js:181
    publish EventBus.ts:27
    refresh PanelModel.ts:352
    panelInitialized DashboardModel.ts:375
    componentDidMount PanelChrome.tsx:180
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    Redux 6
    d actions.ts:37
    Redux 2
    ue DashboardPanel.tsx:68
    c LazyLoader.tsx:24
    observer LazyLoader.tsx:58
    (Async: IntersectionCallback)
    26346 LazyLoader.tsx:55
    Webpack 14
```

Screenshot from 2022-08-04 10-58-21

I have not been able to establish exactly causes this, but it does seem to be related to graphs that are using ref-id's.  This graph above shows disk usage, so it has one target that gets the total space, and then the other divides the current used space using it's refId ```A```, e.g.

```json
"targets": [
    {
      "hide": true,
      "refId": "A",
      "target": "stats.gauges.afs.afs02_dfw_openstack_org.part.vicepa.total",
      "datasource": {
        "uid": "d9c17c45a8",
        "type": "graphite"
      }
    },
    {
      "hide": false,
      "refId": "B",
      "target": "scale(divideSeries(stats.gauges.afs.afs02_dfw_openstack_org.part.vicepa.used, #A), 100)",
      "datasource": {
        "uid": "d9c17c45a8",
        "type": "graphite"
      }
    }
  ],
```

I have put some of our CI that uses this on hold so it can be inspected at https://23.253.56.172/ (note need to accept self signed certificate as it is a test system).

The panel above is https://23.253.56.172/d/9871b26303/afs?orgId=1&viewPanel=4 which exhibits the problem

https://23.253.56.172/d/9871b26303/afs?orgId=1 is the overall graph that shows some of the panels working, and others showing this error.

Everything the same works with the 9.0.6 image, so it does seem to be something introduced between then and now.

### PR DESCRIPTION
**Pull request by bohandley**
Fixes https://github.com/grafana/grafana/issues/53275#issuecomment-1207260024

This is a fix for graphite queries that reference other queries by ref-id. There was a regression in the migration from angular to react for annotations. 

To test this fix:

1. write a query using a graphite datasource
      For example, query A
      `carbon.agents.a7c8a3109768-a.cache.bulk_queries1`
3. add a second query
4. reference query add in the second query
    scale(A#, 100)

### CODE REVIEW

**Comment by ianw** [comment]
This LGTM; I applied this change ontop of the 9.0.1-beta1 tag and imported our graphs, and they all look OK now.  Thank you

File: public/app/plugins/datasource/graphite/datasource.ts [hunk 1]
```diff
@@ -189,62 +189,61 @@ export class GraphiteDatasource
...
-        }
-
-        if (this.isMetricTank) {
-          params.push('meta=true');
+    if (options.targets.some((target: GraphiteQuery) => target.fromAnnotations)) {
+      const streams: Array<Observable<DataQueryResponse>> = [];
+
+      for (const target of options.targets) {
+        // hiding target is handled in buildGraphiteParams
+        if (target.fromAnnotations) {
```
Comment (itsmylife) [inline public/app/plugins/datasource/graphite/datasource.ts:197]: I think we do not need this condition anymore since we are already filtering these on line 193

**Review by itsmylife — APPROVED** [review]
Just one comment and the rest is LGTM

**Review by obetomuniz — APPROVED** [review]
I do agree with @itsmylife observation. Overall, LGTM 👏

File: public/app/plugins/datasource/graphite/datasource.ts (hunk 1 above)
Comment (bohandley) [reply public/app/plugins/datasource/graphite/datasource.ts]: Done, removed the duplicate condition. Thank you!
