### PR TITLE
Trendline: Add higher polynomial degrees

### LINKED ISSUE #103369: Regression Transformation | Polynomial | Add higher degrees of power like sextic, septic, etc
**Why is this needed**:

Our users need higher degrees of power for the polynomial Regression Transformation to visualize the data better.

**What would you like to be added**:

Higher degrees of power like sextic (6), septic (7), etc available on the dropdown. Or maybe the ability to enter custom equations?

**Who is this feature for?**

Users that use the polynomial Regression Transformation feature

Thank you!

### PR DESCRIPTION
**Pull request by alexjonspencer1**
### What does this PR do? 📓 

Fixes #103369

A user is requesting higher polynomial degrees in the trendline transformation. We currently only offer up to quintic, but there _are_ use cases for higher polynomial degrees. A mathematician I am **not**, so reached out to folks on the ML and data and analytics teams. The suggestion was to allow higher polynomial degrees, but to add a warning so that users understand the risks.

I also took the time to update a deprecated component: `<Select />` to `<Combobox />`

>[!WARNING]
> I was looking at the `regressionEditor.tsx` file and noticed a few items I have questions about
> 1. There's a `useEffect` that doesn't have any dependency array so it runs on every single re-render. This is generally an anti-pattern in React. I wonder if we should do some investigation to see if this is an issue, especially because of the `onChange` in the effect.
> 2. Within this `useEffect`, there are three different nested loops, which I think is **O(3n²) complexity** (only if they all run, which probably doesn't happen). Granted, there is defensive programming in the form of `if` blocks, so I don't think we ever loop through all three, but it looks like on load two of the nested loops are run (**O(frames × fields)**). I wonder if we should try to optimize this or if this would ever be an issue.
>
> Any thoughts @gelicia? 😄 

#### Demo 💻 

https://github.com/user-attachments/assets/00a13fed-8f64-429a-84ae-57b72082d204

### CODE REVIEW

**Review by gelicia — APPROVED** [review]
This code looks great - thanks for moving from Select to Combobox as part of your changes.

With your questions on useEffect, I can absolutely see the usefulness of optimizing it. We haven't, as far as I know, gotten any feedback about slowness with this transformation but it's proven to be a fairly popular feature. Any improvements you want to make on it will be appreciated by our users :)

File: public/app/features/transformers/regression/regressionEditor.tsx [hunk 1]
```diff
@@ -1,128 +1,95 @@
-import { useEffect } from 'react';
+import { ReactElement, useEffect, useMemo } from 'react';
```
Comment (alexjonspencer1) [inline public/app/features/transformers/regression/regressionEditor.tsx:1]: I refactored this file pretty heavily. I was having a hard time understanding the code inside the `useEffect`. So I did the following:
- Added a code comment explaining what is happening
- Extracted duplicated logic into a helper function (DRY principles)
- Performance improvements: added dependency array to the `useEffect` and memoized a few calculated constants. 
- Created a `RegressionField` form field wrapper. This might step into _too much abstraction_ territory, but I personally found it easier on the eyes 😅

File: public/app/features/transformers/regression/utils.ts [hunk 2]
```diff
@@ -0,0 +1,15 @@
+import { DataFrame, Field } from '@grafana/data';
```
Comment (alexjonspencer1) [inline public/app/features/transformers/regression/utils.ts:1]: Extracted functionality previously in `regressionEditor.tsx` in the `useEffect` into it's own function. Added to a new `utils` file 😄

File: public/app/features/transformers/regression/constants.ts [hunk 3]
```diff
@@ -0,0 +1,31 @@
+import { FieldMatcherID, fieldMatchers } from '@grafana/data';
```
Comment (alexjonspencer1) [inline public/app/features/transformers/regression/constants.ts:1]: I felt like we were heading into a `constants.ts` file territory. Helps with separation of concerns particularly after my refactor 😸

**Comment by alexjonspencer1** [comment]
@gelicia I refactored the code a bit. Would you mind taking a look? I added some comments for context, but let me know if you have any questions! 😃

File: public/app/features/transformers/regression/utils.ts [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+
+export const findFieldByMatcher = (
```
Comment (gelicia) [inline public/app/features/transformers/regression/utils.ts]: I'd make it explicit that you're only finding the first field by matcher

File: public/app/features/transformers/regression/constants.ts [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+  editor: FieldNamePicker,
+  id: '',
+  name: '',
+  settings: { width: 24, isClearable: false },
+} as const;
+
+export const LABEL_WIDTH = 20;
+
+export const FIELD_MATCHERS = {
+  timeMatcher: fieldMatchers.get(FieldMatcherID.firstTimeField).get({}),
```
Comment (gelicia) [inline public/app/features/transformers/regression/constants.ts]: If this is going to be kept in a different file, please keep the key matching the matcher ID. So `firstTimeMatcher` or something like that

**Review by gelicia — APPROVED** [review]
I really like the moving the field lookup to another file so it can be reused. A couple non blocking comments just to clarify things since the logic is kept in different places now. 

Not part of this PR but could you make a task for us to add tests for this? Would have been nice for there to be tests before this so we could be sure the refactor didnt change anything, but we can do that at some point for any future work.
