### PR TITLE
TableNG: Markdown cell, plus auto row height

### LINKED ISSUE #24482: Add Grafana 7 cell style to show sanitized HTML
**What happened**:
When adding new tables to Grafana 7, many options are missing. "Column Styles" is missing from the panel options. Dashboards migrated from Grafana 6 still include all the options.

**What you expected to happen**:
All options should be available (such as column type, sanitize html, etc) somewhere. Particularly looking for sanitize html.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new table in Grafana 7

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0-beta3
- Data source type & version: MySQL
- OS Grafana is installed on: RedHat 7.8
- User OS & Browser: Chrome 81.0.4044.129
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by fastfrwrd**
**What is this feature?**

- Adds a new cell type called "Markdown + HTML" to TableNG.
  - within Markdown Cell, adds the option to toggle "Dynamic height." when enabled, rowHeight is set to `auto` for the table, and virtualization is forced off.

https://github.com/user-attachments/assets/8dbcdf13-c07f-4478-8fcd-16ceadb44e99

**Why do we need this feature?**

Customer request. Some users would like to pre-format the contents of a table cell within their data sources (including `span`s with colorized text, etc.) and render them alongside other data.

**Which issue(s) does this PR fix?**:

Relates to https://github.com/grafana/hyperion-planning/issues/220
Fixes #24482

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by fastfrwrd** [comment]
I've hooked up the `disable_sanitize_html` config option to TableNG for MarkdownCell. You could add non-compliant HTML as a user if you wanted to by disabling sanitization as you would across the rest of the product.

https://github.com/user-attachments/assets/7025cf80-6915-4e8e-b6ce-fb0e04d32867

**Comment by fastfrwrd** [comment]
Paging up and down is now supported, thanks to a bit of math in our react-data-grid fork.

**Comment by fastfrwrd** [comment]
- [x] going to add a gdev dashboard for MarkdownCell specifically
- [x] will add e2e tests which at least load the MarkdownCell dashboard for now

**Comment by fastfrwrd** [comment]
Fixes #108819 24482

**Comment by fastfrwrd** [comment]
If you opt to not use Auto height, you can have Markdown cells with a virtualized table. this is useful for situations where you have predictable single-line outputs, or if you are cool with just hovering to reveal the content. I found it a lot less jarring for this cell type in particular to align it `flex-start` instead of `center` because of this.

https://github.com/user-attachments/assets/6f147baa-12c4-4056-94bc-a67d6f391caf

File: public/app/plugins/panel/table/table-new/PaginationEditor.tsx [hunk 1]
```diff
@@ -6,8 +6,8 @@ import { Switch } from '@grafana/ui';
 
 export function PaginationEditor({ onChange, value, context }: StandardEditorProps<boolean>) {
   const changeValue = (event: React.FormEvent<HTMLInputElement> | undefined) => {
-    if (event?.currentTarget.checked) {
-      context.options.footer.show = false;
```
Comment (fastfrwrd) [inline public/app/plugins/panel/table/table-new/PaginationEditor.tsx:10]: this had been carried over from TableRT and needed to be removed anyway, so I just swapped it out for this. In TableRT, I guess it wasn't possible to have pagination and footer on at the same time, but now it is. The idea is the same: if we turn pagination off, we always want to turn `disableVirtualization` to false as well.

**Comment by fastfrwrd** [comment]
The `TableCellHeight.Auto` we're removing here was incorrectly added in a previous commit. This would have been the first commit to allow users to add it and actually use it, but we realized today as we neared merging that it was not the right way to enable this behavior for users, so we've scrapped it.

File: packages/grafana-ui/src/components/Table/TableNG/Cells/MarkdownCell.tsx [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+import { MaybeWrapWithLink } from '../MaybeWrapWithLink';
+import { MarkdownCellProps } from '../types';
+
+export function MarkdownCell({ field, rowIdx, disableSanitizeHtml }: MarkdownCellProps) {
+  const value = field.values[rowIdx];
+
+  const markdownContent =
+    typeof value === 'string'
+      ? renderMarkdown(value, { noSanitize: disableSanitizeHtml })
+      : formattedValueToString(field.display!(value));
```
[the remark this answers is not in the document]
Comment (fastfrwrd) [reply packages/grafana-ui/src/components/Table/TableNG/Cells/MarkdownCell.tsx]: silence, robot

File: public/app/plugins/panel/table/table-new/PaginationEditor.tsx (hunk 1 above)
Comment (fastfrwrd) [reply public/app/plugins/panel/table/table-new/PaginationEditor.tsx:10]: now that we got rid of disableVirtualization, I've just gotten rid of it altogether.

**Review by leeoniya — APPROVED** [review]
noice
