### PR TITLE
datasources: querier: add user to query

### LINKED ISSUE #109916: datasources: querier: we do not handle the special `--grafana--` datasource
when you create a new dashboard panel in grafana, often the by-default selected datasource will be a weird datasource named `--Grafana--`, like here:

Image

this data source has the uid `grafana`, and it does not really exist. the grafana codebase simply has an `IF` in request-processing, and creates the necessary structures here: https://github.com/grafana/grafana/blob/af1b6dd1718ff361bb4cc286002d712043da2ca3/pkg/services/query/query.go#L442 .

when we run in query service mode, both in single-tenant mode and multi-tenant mode, we arrive at this line:https://github.com/grafana/grafana/blob/af1b6dd1718ff361bb4cc286002d712043da2ca3/pkg/services/query/query.go#L443

which calls `user.GetOrgID()`, but in the query-service case, `user` is `nil`. so this panics. (we do recover from the panic).

(note: we already handled this in the past in https://github.com/grafana/grafana/pull/103980 , but things changed since then and we are not handling it currently)

if you want to reproduce it locally without running the grafana user interface, just `curl` this `json` to `/apis/query.grafana.app/...`:
```json
{
  "queries": [
    {
      "datasource": {
        "uid": "grafana"
      },
      "refId": "A",
      "queryType": "randomWalk"
    }
  ],
  "from": "1731656670000",
  "to": "1731656680000"
}
```

### PR DESCRIPTION
**Pull request by gabor**
(fixes https://github.com/grafana/grafana/issues/109916)

currently, when we go through the query-service flow (single-tenant or multi-tenant) we set `user` to `nil`. unfortunately we hit a code-path that calls `user.GetOrgId()`, which panics, because `user` is `nil`. (for details see the linked issue).

we extract the user from the context, and use it.

### CODE REVIEW

File: pkg/services/query/query.go [hunk 1]
```diff
@@ -234,7 +234,13 @@ func QueryData(ctx context.Context, log log.Logger, dscache datasources.CacheSer
 		headers:                    headers,
 		concurrentQueryLimit:       16, // TODO: make it configurable
 	}
-	return s.QueryDataNew(ctx, nil, false, reqDTO)
+
+	user, err := identity.GetRequester(ctx)
```
Comment (asimpson) [inline pkg/services/query/query.go:238]: Do we want to only do this if `user` is `nil`?

**Review by asimpson — COMMENTED** [review]
I wonder how if context has the right context for mt path?

**Review by sarahzinger — COMMENTED** [review]
pulled it down and took a look and I think this works! I find this whole thing a bit confusing... like why would we only need user in the `--grafana--` ds? Also the `--grafana--` ds is confusing to me in general because I know we can store annotations in it but it seems the querying experience for it is completely different lol. 

I don't think this really works in the non-ui path but I also don't think it would ever come up? 

~I like adam's suggestion of only doing this when the user is nil just in case we are accidentally overwriting something we shouldn't in the non-querier usecase~ nevermind, I was misreading this to be overwriting an existing user variable

**Review by sarahzinger — APPROVED** [review]
thanks for the clarifying slack comments! Sounds good to me

**Review by asimpson — APPROVED** [review]
🚀
