### PR TITLE
Alerting: Fix alert instances filtering for prom rules

### LINKED ISSUE #49782: Alerting: Allow filtering prometheus-type alert instances by "Firing" state
**What happened**:
I opened a prometheus alert in the Grafana alerting page and clicked "Alerting" on the state filter for the instances list. All of the instances disappeared and I wasn't able to make them reappear.

**What you expected to happen**:
It should have filtered to the instances that are "Firing", or there should be a "Firing" state filter available for the instances list.

cc @torkelo

### PR DESCRIPTION
**Pull request by konrad147**
**What this PR does / why we need it**:
This PR fixes the filtering of alert instances for Prometheus-based alert rules.

**Which issue(s) this PR fixes**:
Fixes #49782 

**Special notes for your reviewer**:
For Prometheus-based alert rules, there are only two available states of alert instances: `Firing` and `Pending`.

**Preview of Prom-based alert instances**
**Before**
image

**After**
image

### CODE REVIEW

File: public/app/features/alerting/unified/components/rules/AlertInstanceStateFilter.tsx [hunk 1]
```diff
@@ -1,22 +1,34 @@
...
+
+export type InstanceStateFilter = GrafanaAlertState | PromAlertingRuleState.Pending | PromAlertingRuleState.Firing;
 
 interface Props {
   className?: string;
-  stateFilter?: GrafanaAlertState;
-  onStateFilterChange: (value: GrafanaAlertState | undefined) => void;
+  filterType: 'grafana' | 'prometheus';
+  stateFilter?: InstanceStateFilter;
+  onStateFilterChange: (value: InstanceStateFilter | undefined) => void;
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rules/AlertInstanceStateFilter.tsx:13]: nit: This is existing code but I think in most places we just mark the input param as optional.

File: public/app/features/alerting/unified/components/rules/AlertInstanceStateFilter.tsx [hunk 2]
```diff
@@ -1,22 +1,34 @@
...
-  const stateOptions = Object.values(GrafanaAlertState).map((value) => ({
-    label: value,
-    value,
-  }));
+const grafanaOptions = Object.values(GrafanaAlertState).map((value) => ({
+  label: value,
+  value,
+}));
+
+const promOptionValues = [PromAlertingRuleState.Firing, PromAlertingRuleState.Pending] as const;
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rules/AlertInstanceStateFilter.tsx:21]: Interesting, TIL about `as const`! But why do we need it here, it seems like if we remove it the compiler complains 🤔

**Review by gillesdemey — APPROVED** [review]
LGTM, just a few nits

File: public/app/features/alerting/unified/components/rules/AlertInstanceStateFilter.tsx (hunk 2 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/components/rules/AlertInstanceStateFilter.tsx:21]: Ah I think I get it, the compiler infers `PromAlertingRuleState[]` but that's incompatible with `InstanceStateFilter` since that's a union of _specific_ `PromAlertingRuleState` states (`Pending | Firing`)

Comment (konrad147) [reply public/app/features/alerting/unified/components/rules/AlertInstanceStateFilter.tsx:21]: Without `as const` the type of `promOptionValues` would be `Array<PromAlertingRuleState>`. Adding `as const` cause that the type is a tuple `[PromAlertingRuleState.Firing, PromAlertingRuleState.Pending]` so the `PromAlertingRuleState.Inactive` in not allowed

File: public/app/features/alerting/unified/components/rules/RuleDetailsMatchingInstances.test.tsx [hunk 3]
```diff
@@ -0,0 +1,128 @@
...
+        await userEvent.click(ui.cloudStateButton[state].get());
+
+        expect(ui.instanceRow.getAll()).toHaveLength(1);
+        expect(ui.instanceRow.get()).toHaveTextContent(alertStateToReadable(state));
+      }
+    );
+  });
+});
+
+function mockPromNamespace(): CombinedRuleNamespace {
```
Comment (peterholmberg) [inline public/app/features/alerting/unified/components/rules/RuleDetailsMatchingInstances.test.tsx:122]: can we use https://github.com/grafana/grafana/blob/5d65d4ce03f18b99891d6fa3e8e58267d4d8ac15/public/app/features/alerting/unified/mocks.ts#L172 instead?

**Review by peterholmberg — COMMENTED** [review]
Some comments

File: public/app/features/alerting/unified/components/rules/RuleDetailsMatchingInstances.tsx [hunk 4]
```diff
@@ -4,34 +4,42 @@ import React, { useMemo, useState } from 'react';
...
 
+import { isGrafanaRulesSource } from '../../utils/datasource';
 import { isAlertingRule } from '../../utils/rules';
 import { DetailsField } from '../DetailsField';
 
 import { AlertInstancesTable } from './AlertInstancesTable';
 
 type Props = {
-  promRule?: Rule;
+  rule: CombinedRule;
```
[the remark this answers is not in the document]
Comment (konrad147) [reply public/app/features/alerting/unified/components/rules/RuleDetailsMatchingInstances.tsx:24]: I use it in the line 41 to check if it's a Grafana or Prom rule

**Review by peterholmberg — APPROVED** [review]
Looks good!
