### PR TITLE
Plugins: Fix better UX for disabled Angular plugins

### LINKED ISSUE #101040: Improve error messaging or handling for plugins that were installed but can not start anymore
**Why?**
It is mostly prevalent in angular upgrades but this applies to also cases where plugin could not start for some other reasons (license mismatch for example)

**How to reproduce (locally, based off an example of polystat panel - but same applies to other plugins)?**
1. In `main` enable angular and run grafana

```
[security]
angular_support_enabled = true
```
2. Make sure there is no previous polystat version installed
3. Install the version that contains angular `bin/grafana cli plugins install grafana-polystat-panel 1.2.11` 
4. restart the server
5. See that you have update available here http://localhost:3000/plugins/grafana-polystat-panel?page=version-history
6. Now dot not upgrade, just turn the angular support off (set `true` to `false` above)
7. Visit the same page and see that you can not upgrade even though theoretically the new version is using react and would work.
8. Your only way to fix this as a user is either delete the plugins files on grafana server's disk OR use the cli above to update - e.g. `bin/grafana cli plugins install grafana-polystat-panel 2.1.14` or `bin/grafana cli plugins install grafana-polystat-panel` to try to get the latest compatible version without specifying it.

Notice for loading reasons (probably) errors differ between angular disabled and angular removed ([this PR](https://github.com/grafana/grafana/pull/99760)).

Angular disabled screenshot:
Image

Angular removed screenshot:
Image

**What are the possible solutions?**
### 1. The documentation way:

Explain on how to handle the situation or link out to docs (that probably need to be created..) on how to handle it. 
Depending on how much we can detect the reason behind it we could:

**Instead of:**
> Plugin disabled
> We failed to run this plugin due to an unknown reason and have therefore disabled it. We commend you to reinstall the plugin to make sure you are running a working version of this plugin. 
> Please contact your server administrator to get this resolved.
> 
> Read more about managing plugins

**Do something like this for cases when we know it's angular related:**
> Plugin disabled
> The reason this plugin was disabled is that Grafana does not support angular anymore. You can try updating the plugin version to the latest using the `grafana cli plugins install <plugin-id>` to see if the latest version is working and has migrated away from angular. 
> 
> Read more about managing plugins
> Read more about angular deprecation (https://grafana.com/docs/grafana/latest/developers/angular_deprecation/)

### 2. The "better-for-users" way
Make it possible to update from the `Version History` view or `Update` button - this will not solve the cases where update is also not starting (e.g. from angular version to angular version) but at least help in cases where the new version is working (react).

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What is this feature?**
This feature makes the user experience slightly better for disabled Angular plugins in the Plugins Catalog when the `angular_support_enabled = false` is set. 

**BEFORE**
image

**AFTER**
image

- This PR also adds tests for `public/app/features/plugins/admin/components/PluginActions.tsx`
- This PR also marks texts for translations in `public/app/features/plugins/admin/components/PluginDetailsDisabledError.tsx`

**Why do we need this feature?**
When we remove Angular in G12 this feature will make it clearer for the end user what they should do.

**Who is this feature for?**
Plugin catalog users.

**Which issue(s) does this PR fix?**:

Fixes #101040

**Special notes for your reviewer:**
The issue https://github.com/grafana/grafana/issues/101040 explains the necessary steps needed to test this locally

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/plugins/admin/components/PluginDetailsDisabledError.tsx [hunk 1]
```diff
@@ -16,66 +18,119 @@ export function PluginDetailsDisabledError({ className, plugin }: Props): ReactE
...
+      );
     case PluginErrorCode.angular:
-      // Error message already rendered by AngularDeprecationPluginNotice
-      return <></>;
+      if (isLatestCompatibleNotAngular) {
+        return (
+          <p>
+            <Trans i18nKey="plugins.details.disabled-error.angular-error-text">
+              The reason this plugin was disabled is that Grafana does not support angular anymore. You can try updating
+              the plugin version to the latest to see if the latest version is working.
```
Comment (jackw) [inline public/app/features/plugins/admin/components/PluginDetailsDisabledError.tsx:111]: nit:
```suggestion
              This plugin has been disabled as Grafana no longer supports Angular based plugins. You can try updating
              the plugin to the latest version to resolve this issue. You should then test to confirm it works as expected.
```

File: public/app/features/plugins/admin/components/PluginDetailsDisabledError.tsx [hunk 2]
```diff
@@ -16,66 +18,119 @@ export function PluginDetailsDisabledError({ className, plugin }: Props): ReactE
...
+          </p>
+        );
+      }
+
+      return (
+        <p>
+          <Trans i18nKey="plugins.details.disabled-error.angular-error-text-no-non-angular-version">
+            The reason this plugin was disabled is that Grafana does not support angular anymore. Unfortunately, the
+            latest version of this plugin is still using angular so you need to wait for the plugin author to migrate
+            away from angular to use this plugin.
```
Comment (jackw) [inline public/app/features/plugins/admin/components/PluginDetailsDisabledError.tsx:122]: nit:
```suggestion
            This plugin has been disabled as Grafana no longer supports Angular based plugins. Unfortunately, the
            latest version of this plugin still uses Angular so you need to wait for the plugin author to migrate
            to continue using this plugin.
```

File: public/app/features/plugins/admin/components/PluginActions.test.tsx [hunk 3]
```diff
@@ -0,0 +1,277 @@
+import { render, screen } from 'test/test-utils';
```
Comment (jackw) [inline public/app/features/plugins/admin/components/PluginActions.test.tsx:1]: 👏👏👏👏

**Review by jackw — APPROVED** [review]
Awesome work @hugohaggmark! 🚀 

Especially nice to see the translations being handled and all those new tests. 🥇

File: public/app/features/plugins/admin/components/PluginDetailsDisabledError.tsx (hunk 2 above)
Comment (jackw) [reply public/app/features/plugins/admin/components/PluginDetailsDisabledError.tsx:122]: @sympatheticmoose is it worth pointing users to the [angular deprecation docs](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/angular-plugins/#angularjs-based-plugins) and the table of suggestions regarding angular plugins?

Comment (hugohaggmark) [reply public/app/features/plugins/admin/components/PluginDetailsDisabledError.tsx:122]: @jackw thanks for the review 🙌 , I've added a new link `Read more about angular deprecation` (it's not highlighted in the picture but it's below the "Read more about managing plugins link")

**Comment by hugohaggmark** [comment]
> @hugohaggmark - awesome, great to see the work on this and I really appreciate the picture in the summary 🙌
👍 

> Some quick questions, you mention
> 
> > when the angular_support_enabled = false is set.
> 
> My (possibly flawed) understanding is that with G12 we remove that flag as part of removing Angular. I assume there is no actual dependence on this setting that would then break?

👍 it sort of has this dependency now but indirectly. In the frontend we check for disabled Angular plugins with a specific error but I'm going to merge this into the Remove Angular POC 12 too and adapt it accordingly (if needed)
 
> Why is uninstall not possible when the plugin is disabled? (for my own understanding). Given this, are we able to provide appropriate hover over text for the disabled uninstall button?

I did some debugging and the backend doesn't load the plugin into their store/registry so when I try to uninstall it I get an 404 error that the plugin doesn't exist. I could add a tooltip explaining that you can only uninstall it from the cli? WDYT @sympatheticmoose  
 
> I agree we probably don't need the comment on contacting your server administrator.

I'll remove it then

**Comment by sympatheticmoose** [comment]
Gotcha - thanks!

> I could add a tooltip explaining that you can only uninstall it from the cli? 

Grafana.com would probably be the easiest for Cloud users. If we're able to change the message based on how Grafana is running, that's ideal, if not we should mention both methods

**Review by leventebalogh — APPROVED** [review]
Really nice changes, also great to see those new tests 👏

File: apps/dashboard/pkg/apis/dashboard_manifest.go [hunk 4]
```diff
@@ -11,8 +11,6 @@ import (
 	"github.com/grafana/grafana-app-sdk/app"
 )
 
-var ()
-
```
Comment (hugohaggmark) [inline apps/dashboard/pkg/apis/dashboard_manifest.go:15]: This is not something I've done but its probably done by the go linter commit hook, can you verify @onprem . Thank you 🙏

**Comment by hugohaggmark** [comment]
New tooltip
image
