### PR TITLE
Navigation: Enable new navigation by default

### LINKED ISSUE #48268: Navigation: Turn `newNavigation` toggle on by default
First step to enabling this for everyone. Turn the toggle on by default so it appears in environments such as ops.grafana.net

### LINKED ISSUE #48538: Navigation: New nav fails pa11y
New navigation fails pa11y due to some invalid HTML. Two issues appear to be:

 - [ ] NavBarNext contains `div`s inside the `ul`
 - [ ] NavBarItems are `li`s that aren't inside a `ul`

Main offender could possibly be the scroller introduced which put a bunch of divs in the middle of the navigation.

Raw errors:
```
Error: <ul> and <ol> must only directly contain <li>, <script> or <template> elements 
<ul class="css-1iemvmp"><div class="css-1s8pg06"><a cla...</ul> (select with "#reactRoot > div:nth-child(1) > div > nav > ul")


Error: <li> elements must be contained in a <ul> or <ol>
<li class="css-1inbft0"><div class="css-ho888y dropdown...</li> (select with "#reactRoot > div:nth-child(1) > div > nav > ul > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > li:nth-child(2)")


Error: <li> elements must be contained in a <ul> or <ol>
<li class="css-1b4r4c9"><div class="css-ho888y dropdown...</li> (select with "#reactRoot > div:nth-child(1) > div > nav > ul > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > li:nth-child(3)")


Error: <li> elements must be contained in a <ul> or <ol>
<li class="css-1b4r4c9"><div class="css-ho888y dropdown...</li> (select with "#reactRoot > div:nth-child(1) > div > nav > ul > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > li:nth-child(4)")


Error: <li> elements must be contained in a <ul> or <ol>
<li class="css-1b4r4c9"><div class="css-ho888y dropdown...</li> (select with "#reactRoot > div:nth-child(1) > div > nav > ul > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > li:nth-child(5)")
```

### PR DESCRIPTION
**Pull request by joshhunt**
Fixes #48268
Fixes #48538

### CODE REVIEW

**Review by JoaoSilvaGrafana — APPROVED** [review]

**Review by axelavargas — APPROVED** [review]
🥳

File: packages/grafana-e2e-selectors/src/selectors/pages.ts [hunk 1]
```diff
@@ -183,7 +183,7 @@ export const Pages = {
       container: 'data-testid Explore',
       graph: 'Explore Graph',
       table: 'Explore Table',
-      scrollBar: () => '.scrollbar-view',
+      scrollView: 'data-testid explorer scroll view',
```
Comment (jackw) [inline packages/grafana-e2e-selectors/src/selectors/pages.ts:186]: Not 100% sure what's going on here. Does the new nav introduce a custom scrollbar and now we need to grab a specific scroll view for the test?

I'm guessing the likelihood of `e2e.pages.Explore.General.scrollBar()` being used outside of core is unlikely as explore doesn't make use of plugins, right? It's worth noting that changing these selector keys can be problematic when running plugin integration tests across multiple versions of Grafana. Perhaps we keep the key as is and only change the value? 🤔

**Review by jackw — APPROVED** [review]
LGTM! 🚀 

Left a question related to the e2e-selectors breaking change.

**Review by gelicia — APPROVED** [review]
Adding a test ID shouldn't affect anything - 👍 for the change to explore

**Review by ashharrison90 — APPROVED** [review]
looks great! 🙌

File: packages/grafana-e2e-selectors/src/selectors/pages.ts (hunk 1 above)
Comment (joshhunt) [reply packages/grafana-e2e-selectors/src/selectors/pages.ts:186]: The actual Explore page did not use this selector, and it was only returning a class name that was used internally within the `react-custom-scrollbars-2` component. No where did we actually pass this class name into the component, and there was no guarantee this selector was actually correct (apart from tests failing, which is fair)

This selector matched _all_ scroll views on the page, not just the Explore one. This PR adds a second scroll view onto the page, and broke this test because it was not correctly selector the Explore page scroller.
