### PR TITLE
A11y: Make Annotations and Template Variables list and edit pages responsive 

### LINKED ISSUE #66487: ID 257467: [Supporting Platform - Simon - Annotations>Edit]: Horizontal scroll bar appears on the 'Annotations>Edit' screen after setting the pixels at 320*256 view port.
### **User Experience:** 
Low vision users will not be able to navigate through all the controls properly and might face challenges while navigating on the controls present on the page as the user would need to scroll a lot due to two-dimensional scrolling.
_Note: User credentials should not be included in the bug._

### **Pre-Requisite:** 
Achieve viewport 320 X 256 by adjusting the browser. (Open the developer's tool, resize, and zoom the browser to achieve viewport 320 X 256). 

### **Repro Steps:** 

1. Open #URL: [play.grafana.org](https://play.grafana.org/).  Sign in with valid credentials. "Home" page appears.  
2. Navigate the Feature Showcase pane heading and select it. 
3. Navigate the expanded Dropdown and select the "Edit" menu item. 
4. Navigate the page "Edit Panel" page which appears. 
5. Navigate to "Settings" button and select it. 
6. Navigate the "Annotations" tab item and select it.  
7. Navigate the "Annotations>Edit" screen. Verify the issue.

**Actual Result:** 
A horizontal scroll bar appears after setting the pixels at 320*256 view port on the 'Annotations>Edit' screen.

**Expected Result:** 
Horizontal scroll bar should not appear on the 'Annotations>Edit' screen after setting the pixels to 320*256 viewport. There should only be Vertical scroll bar on the page.
_Note: The same issue exists with "Variable" and "variable>New" screens. (Home>feature showcases>edit>setting>Variable). The same issue exists with "Alerting'" screen. e.g.  "Silences" tab (Home page>Alerting>Silences tab)_

### Severity:
`SEV2`

### **Area:**
?

### PR DESCRIPTION
**Pull request by juanicabanas**
**What is this feature?**

It makes annotations, template variables and edit template variables configuration pages responsive.

**Which issue(s) does this PR fix?**:

Fixes [#66487](https://github.com/grafana/grafana/issues/66487)

**Special notes for your reviewer:**
Since there are tables inside these pages, it's not possible to avoid the horizontal scrolling behavior.
I fixed the responsive design.

**Annotations config page**

https://github.com/grafana/grafana/assets/11707172/235a2fcf-89ed-487d-bbf2-16f04280b5f5

**Template variables config page**

https://github.com/grafana/grafana/assets/11707172/7a795b08-7f5b-447d-b8a7-06748eecd623

**Template variables edit page**

https://github.com/grafana/grafana/assets/11707172/c92b76db-234e-48f0-8d5f-98b6923d3266

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/variables/query/QueryVariableRefreshSelect.tsx [hunk 1]
```diff
@@ -14,14 +15,15 @@ const REFRESH_OPTIONS = [
...
+  const { width } = useWindowSize();
   const value = useMemo(
     () => REFRESH_OPTIONS.find((o) => o.value === refresh)?.value ?? REFRESH_OPTIONS[0].value,
     [refresh]
   );
 
   return (
     <Field label="Refresh" description="When to update the values of this variable">
-      <RadioButtonGroup options={REFRESH_OPTIONS} onChange={onChange} value={value} />
+      <RadioButtonGroup options={REFRESH_OPTIONS} onChange={onChange} value={value} size={width < 375 ? 'sm' : 'md'} />
```
Comment (torkelo) [inline public/app/features/variables/query/QueryVariableRefreshSelect.tsx:26]: I don't think this is a good solution (not worth it, and just makes code messy, and not a pattern we use anywhere else )

Comment (torkelo) [reply public/app/features/variables/query/QueryVariableRefreshSelect.tsx:26]: beside the radio button fits on small screens. I would change the wording instead "on time range change" to just "On time change" 
Screenshot 2023-07-24 at 20 54 23

Comment (juanicabanas) [reply public/app/features/variables/query/QueryVariableRefreshSelect.tsx:26]: what do you suggest to make it fit a mobile screen?

**Comment by torkelo** [comment]
Not sure how scrolling just the table is better than scrolling the page? is not scrolling the page a bit more discoverable?

File: public/app/features/variables/query/QueryVariableRefreshSelect.tsx [hunk 2]
```diff
@@ -14,14 +15,15 @@ const REFRESH_OPTIONS = [
 ];
 
 export function QueryVariableRefreshSelect({ onChange, refresh }: PropsWithChildren<Props>) {
+  const { width } = useWindowSize();
```
Comment (ivanortegaalba) [inline public/app/features/variables/query/QueryVariableRefreshSelect.tsx:18]: Should we use [`useMediaQueryChange`](https://github.com/grafana/grafana/blob/43f7309272d623e2a3367d29780c68041e81c09a/public/app/core/hooks/useMediaQueryChange.ts#L4) hook? This will only trigger a re-render when the media query changes, not when the window size changes.

File: public/app/features/variables/query/QueryVariableRefreshSelect.tsx (hunk 1 above)
Comment (ivanortegaalba) [inline public/app/features/variables/query/QueryVariableRefreshSelect.tsx:26]: Out of curiosity, why don't we set a width and the labels are automatically truncated? I love this improvement anyways, I like it to get smaller when the screen is too small.

**Review by ivanortegaalba — APPROVED** [review]
I left small comments, but the changes look great. Thanks @juanicabanas to take care of this!

File: public/app/features/variables/query/QueryVariableRefreshSelect.tsx (hunk 1 above)
Comment (juanicabanas) [reply public/app/features/variables/query/QueryVariableRefreshSelect.tsx:26]: I'm also wondering how responsive we should be since a 320px mobile device is not a common one anymore. 
Changing the wording keeps generating some problems, since there's a minimal horizontal scrolling and no padding. Shouldn't we decrease the padding a little bit more, in this case? 
image

File: public/app/features/variables/editor/VariableEditorList.tsx [hunk 3]
```diff
@@ -51,40 +51,42 @@ export function VariableEditorList({
...
-                          onEdit={onEdit}
-                        />
-                      ))}
-                      {provided.placeholder}
-                    </tbody>
-                  )}
-                </Droppable>
-              </DragDropContext>
-            </table>
+            <div style={{ overflow: 'scroll', width: '100%' }}>
```
[the remark this answers is not in the document]
Comment (juanicabanas) [reply public/app/features/variables/editor/VariableEditorList.tsx:54]: yes! I didn't catch it

File: public/app/features/variables/query/QueryVariableRefreshSelect.tsx (hunk 1 above)
Comment (juanicabanas) [reply public/app/features/variables/query/QueryVariableRefreshSelect.tsx:26]: I just tried it and it seems it's not possible with the RadioButtonGroup we currently have. I should make some modifications to that core component

File: public/app/features/variables/query/QueryVariableRefreshSelect.tsx (hunk 2 above)
Comment (juanicabanas) [reply public/app/features/variables/query/QueryVariableRefreshSelect.tsx:18]: loved it. didn't know it

**Comment by juanicabanas** [comment]
> Not sure how scrolling just the table is better than scrolling the page? is not scrolling the page a bit more discoverable?

@torkelo I think it's better since otherwise, the whole page would look as broken

**Comment by torkelo** [comment]
@juanicabanas yea, your right. just feels like this just hides the problem but maybe with more rows in the table it's easier to notice

**Review by ivanortegaalba — APPROVED** [review]
Thanks for applying the feedback, LGTM!
