### PR TITLE
Tracing: Differentiate collector and agent better

### LINKED ISSUE #71205: Tracing Opentelemetry Jaeger no longer working in Grafana 10.0.1
### 
# What went wrong?

**What happened**:

  - Upgrading from Grafana 9.5.5 to 10.0.1 seems to have broken `tracing.opentelemetry.jaeger`

**What did you expect to happen**:

  - I expected tracing to continue to work

### 
# How do we reproduce it?

**Step 1**:

- Set `GF_TRACING_OPENTELEMETRY_JAEGER_ADDRESS = "https://tempo-distributor-jaeger-thrift-http.${domain}/api/traces"`

**Step 2**:

- start Grafana with v10.0.1
- no other config changes were made other than upgrading from 9.5.5 -> 10.0.1

**Step 3**:

- view logs to see

```bash
logger=tracing t=2023-07-07T12:48:26.545113124Z level=error msg="OpenTelemetry handler returned an error" err="UDP connection not yet initialized, an address has not been resolved"
```

### 
# What Grafana version are you using?

10.0.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by zserge**
This PR uses Jaeger collector for HTTP/HTTPS URLs and Agent for `host:port` notation (without a HTTP/HTTPS schema). It makes sense because Jaeger collector is only available for HTTP/HTTPS protocols and Agent uses UDP `host:port` only.

Previous code worked because usually people run Collector on a custom port, so `SplitHostPort` failed with an error. Now this HTTP/UDP check is more explicit with some logging added.

Fixes https://github.com/grafana/grafana/issues/71205

### CODE REVIEW

File: pkg/infra/tracing/tracing.go [hunk 1]
```diff
@@ -267,10 +267,14 @@ func splitCustomAttribs(s string) ([]attribute.KeyValue, error) {
 func (ots *Opentelemetry) initJaegerTracerProvider() (*tracesdk.TracerProvider, error) {
 	var ep jaeger.EndpointOption
 	// Create the Jaeger exporter: address can be either agent address (host:port) or collector URL
-	if host, port, err := net.SplitHostPort(ots.Address); err == nil {
-		ep = jaeger.WithAgentEndpoint(jaeger.WithAgentHost(host), jaeger.WithAgentPort(port), jaeger.WithMaxPacketSize(64000))
-	} else {
+	if strings.HasPrefix(ots.Address, "http://") || strings.HasPrefix(ots.Address, "https://") {
```
Comment (papagian) [inline pkg/infra/tracing/tracing.go:270]: nit; wouldn't it be better to use url.Parse?

File: pkg/infra/tracing/tracing.go [hunk 2]
```diff
@@ -267,10 +267,14 @@ func splitCustomAttribs(s string) ([]attribute.KeyValue, error) {
...
+		ots.log.Debug("using jaeger collector", "address", ots.Address)
 		ep = jaeger.WithCollectorEndpoint(jaeger.WithEndpoint(ots.Address))
+	} else if host, port, err := net.SplitHostPort(ots.Address); err == nil {
+		ots.log.Debug("using jaeger agent", "host", host, "port", port)
+		ep = jaeger.WithAgentEndpoint(jaeger.WithAgentHost(host), jaeger.WithAgentPort(port))
```
Comment (papagian) [inline pkg/infra/tracing/tracing.go:275]:
```suggestion
		ep = jaeger.WithAgentEndpoint(jaeger.WithAgentHost(host), jaeger.WithAgentPort(port), jaeger.WithMaxPacketSize(64000))
```

**Review by mildwonkey — APPROVED** [review]

File: pkg/infra/tracing/tracing.go (hunk 1 above)
Comment (zserge) [reply pkg/infra/tracing/tracing.go:270]: It might be tempting to use proper parsing functions from the `net` package, however:
* Historically, we have two valid forms of syntax: `host:port` for UDP and `https://example.com/` for collector URL.
* Using `url.Parse` would succeed on both, returning `host` as a schema and `port` as host in the first case.
* Similarly, `net.SplitHostPort` would succeed on both, returning `https` as a host and `//example.com/` as a very weird port syntax.

Which is why the only relatively simple way to tell one from the other is to use string prefixes, knowing that the only valid schema for URLs is http(s).

**Review by papagian — APPROVED** [review]
