### PR TITLE
Alerting: Reduce cyclomatic complexity of PrepareRuleGroupStatuses

### LINKED ISSUE #88670: Reduce cyclomatic complexity of PrepareRuleGroupStatuses
CI is failing for the function `PrepareRuleGroupStatuses` found at https://github.com/grafana/grafana/blob/783aa1c0b4b386cd02af3c0ff561afac0248c204/pkg/services/ngalert/api/api_prometheus.go#L238 due to 
```
pkg/services/ngalert/api/api_prometheus.go:238:1: cyclomatic complexity 36 of func `PrepareRuleGroupStatuses` is high (> 30) (gocyclo)
```
It has currently been excluded from lint with `//nolint:gocyclo` but the function should ideally be refactored.

### PR DESCRIPTION
**Pull request by wasim-nihal**
**What is this feature?**

Reduce cyclomatic complexity of PrepareRuleGroupStatuses

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/88670

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by wasim-nihal** [comment]
@fayzal-g , I have made changes to reduce complexity to around 24. Could you please check and let me know if any further changes are needed.

File: pkg/services/ngalert/api/api_prometheus.go [hunk 1]
```diff
@@ -334,24 +331,8 @@ func PrepareRuleGroupStatuses(log log.Logger, manager state.AlertInstanceManager
...
-		ruleGroup = append(ruleGroup, rule)
-		groupedRules[groupKey] = ruleGroup
-	}
-	// Sort the rules in each rule group by index. We do this at the end instead of
-	// after each append to avoid having to sort each group multiple times.
-	for _, groupRules := range groupedRules {
-		ngmodels.AlertRulesBy(ngmodels.AlertRulesByIndex).Sort(groupRules)
-	}
 
+	processGroupRules(groupedRules, ruleList, ruleNamesSet)
```
Comment (stevesg) [inline pkg/services/ngalert/api/api_prometheus.go:335]: This would read nicer if it returned the slice, and the function created the slice, e.g.

```suggestion
	groupedRules := getGroupedRules(ruleList, ruleNamesSet)
```

File: pkg/services/ngalert/api/api_prometheus.go [hunk 2]
```diff
@@ -334,24 +331,8 @@ func PrepareRuleGroupStatuses(log log.Logger, manager state.AlertInstanceManager
 	// but in this API all rules belong to the same organization. Also filter by rule name if
 	// it was provided as a query param.
 	groupedRules := make(map[ngmodels.AlertRuleGroupKey][]*ngmodels.AlertRule)
```
Comment (stevesg) [inline pkg/services/ngalert/api/api_prometheus.go:333]:
```suggestion
```

File: pkg/services/ngalert/api/api_prometheus.go [hunk 3]
```diff
@@ -418,6 +379,49 @@ func PrepareRuleGroupStatuses(log log.Logger, manager state.AlertInstanceManager
 	return ruleResponse
 }
 
+func processGroupRules(groupedRules map[ngmodels.AlertRuleGroupKey][]*ngmodels.AlertRule, ruleList ngmodels.RulesGroup, ruleNamesSet map[string]struct{}) {
```
Comment (stevesg) [inline pkg/services/ngalert/api/api_prometheus.go:382]:
```suggestion
func processGroupRules(ruleList ngmodels.RulesGroup, ruleNamesSet map[string]struct{}) {
	groupedRules := make(map[ngmodels.AlertRuleGroupKey][]*ngmodels.AlertRule)
```

File: pkg/services/ngalert/api/api_prometheus.go [hunk 4]
```diff
@@ -418,6 +379,49 @@ func PrepareRuleGroupStatuses(log log.Logger, manager state.AlertInstanceManager
...
+		ruleGroup := groupedRules[groupKey]
+		ruleGroup = append(ruleGroup, rule)
+		groupedRules[groupKey] = ruleGroup
+	}
+	// Sort the rules in each rule group by index. We do this at the end instead of
+	// after each append to avoid having to sort each group multiple times.
+	for _, groupRules := range groupedRules {
+		ngmodels.AlertRulesBy(ngmodels.AlertRulesByIndex).Sort(groupRules)
+	}
+}
```
Comment (stevesg) [inline pkg/services/ngalert/api/api_prometheus.go:399]:
```suggestion
	return groupedRules
}
```

**Review by stevesg — COMMENTED** [review]
Thank you for working on this! I left a minor suggestion for groupedRules.

**Comment by wasim-nihal** [comment]
Thanks @stevesg for taking a look. I have addressed the comments. Could you please check?

**Review by stevesg — APPROVED** [review]
