### PR TITLE
Alerting: Fixed an issue where the edit page crashes if you tried to preview an alert without a condition set.

### LINKED ISSUE #39193: Alerting: UI crashes when generating preview for undefined alert
**What happened**:
When a user creates a new grafana hosted alert, the default template generates a query (A) and an expression (B) with alert configured to use B as the source of alerts. When user deletes B and clicks on button "Preview Alerts" the UI crashes.

<details><summary>show</summary>

FFYLeJE1UF

</details>
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
- Go to "Alert Rules" page
- Click on "New Alert Rule" button
- Step 1. In field "rule type" choose "Grafana managed alert"
- Scroll to step 2 and delete expression "B"
- Scroll to step 3 and click "Preview Experession"
- Get the error
<details><summary>error</summary>

```
An unexpected error happened
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bstatus%2C%20statusText%2C%20data%2C%20config%2C%20message%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

div
Me@https://admin-ops-us-east-0.grafana.net/grafana/public/build/AlertingRuleForm.0f06ed3b876fd4f2030e.js:121:2703
div
Ve@https://admin-ops-us-east-0.grafana.net/grafana/public/build/AlertingRuleForm.0f06ed3b876fd4f2030e.js:129:116
fieldset
kd@https://admin-ops-us-east-0.grafana.net/grafana/public/build/6463.0f06ed3b876fd4f2030e.js:3106:863
div
div
p@https://admin-ops-us-east-0.grafana.net/grafana/public/build/AlertingRuleForm.0f06ed3b876fd4f2030e.js:1:1358
ht@https://admin-ops-us-east-0.grafana.net/grafana/public/build/AlertingRuleForm.0f06ed3b876fd4f2030e.js:140:2984
div
div
div
t@https://admin-ops-us-east-0.grafana.net/grafana/public/build/1286.0f06ed3b876fd4f2030e.js:2:1910680
u@https://admin-ops-us-east-0.grafana.net/grafana/public/build/6463.0f06ed3b876fd4f2030e.js:281:484
div
form
P@https://admin-ops-us-east-0.grafana.net/grafana/public/build/1286.0f06ed3b876fd4f2030e.js:2:2111589
wt@https://admin-ops-us-east-0.grafana.net/grafana/public/build/AlertingRuleForm.0f06ed3b876fd4f2030e.js:149:32
./public/app/features/alerting/unified/RuleEditor.tsx/Ft<@https://admin-ops-us-east-0.grafana.net/grafana/public/build/AlertingRuleForm.0f06ed3b876fd4f2030e.js:172:35
nl@https://admin-ops-us-east-0.grafana.net/grafana/public/build/6463.0f06ed3b876fd4f2030e.js:2797:458
il@https://admin-ops-us-east-0.grafana.net/grafana/public/build/6463.0f06ed3b876fd4f2030e.js:2797:745
WithErrorBoundary
n@https://admin-ops-us-east-0.grafana.net/grafana/public/build/1286.0f06ed3b876fd4f2030e.js:2:2170666
K@https://admin-ops-us-east-0.grafana.net/grafana/public/build/6463.0f06ed3b876fd4f2030e.js:4160:121
t@https://admin-ops-us-east-0.grafana.net/grafana/public/build/1286.0f06ed3b876fd4f2030e.js:2:2218017
t@https://admin-ops-us-east-0.grafana.net/grafana/public/build/1286.0f06ed3b876fd4f2030e.js:2:2220004
main
t@https://admin-ops-us-east-0.grafana.net/grafana/public/build/1286.0f06ed3b876fd4f2030e.js:2:2214683
div
Ta@https://admin-ops-us-east-0.grafana.net/grafana/public/build/6463.0f06ed3b876fd4f2030e.js:2105:1022
./public/app/core/utils/ConfigProvider.tsx/u<@https://admin-ops-us-east-0.grafana.net/grafana/public/build/6463.0f06ed3b876fd4f2030e.js:4459:25571
nl@https://admin-ops-us-east-0.grafana.net/grafana/public/build/6463.0f06ed3b876fd4f2030e.js:2797:458
il@https://admin-ops-us-east-0.grafana.net/grafana/public/build/6463.0f06ed3b876fd4f2030e.js:2797:745
c@https://admin-ops-us-east-0.grafana.net/grafana/public/build/1286.0f06ed3b876fd4f2030e.js:2:2196130
xe@https://admin-ops-us-east-0.grafana.net/grafana/public/build/6463.0f06ed3b876fd4f2030e.js:4173:237
```

</details>

**Environment**:
- Grafana version: v8.2.0-33767pre (1c892a2fc4)
- Data source type & version: N\A
- OS Grafana is installed on: N\A
- User OS & Browser: Windows, Firefox 92
- Grafana plugins: N\A
- Others: N\A

### PR DESCRIPTION
**Pull request by peterholmberg**
**What this PR does / why we need it**:
Fixes an issue where the edit page would crash if you tried previewing an alert without a condition set.

**Which issue(s) this PR fixes**:
Fixes #39193

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/alerting/unified/components/rule-editor/PreviewRule.tsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ export function PreviewRule(): React.ReactElement | null {
   const styles = useStyles2(getStyles);
   const [preview, onPreview] = usePreview();
   const { getValues } = useFormContext();
-  const [type] = getValues(fields);
+  const { type, condition } = getValues();
```
Comment (domasx2) [inline public/app/features/alerting/unified/components/rule-editor/PreviewRule.tsx:19]: You should normally use `watch` instead of `getValues` in a FC to not re-render this particular value did not change

**Review by domasx2 — COMMENTED** [review]
Maybe you could also fix https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/components/rule-editor/PreviewRuleResult.tsx#L33 while you're at it :)
It throws because `data.error` is not a valid `React.Element`. Could use https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/utils/redux.ts#L140 to get a string error msg out of it

File: public/app/features/alerting/unified/components/rule-editor/PreviewRule.tsx [hunk 2]
```diff
@@ -15,7 +15,7 @@ const fields: string[] = ['type', 'dataSourceName', 'condition', 'queries', 'exp
 export function PreviewRule(): React.ReactElement | null {
   const styles = useStyles2(getStyles);
   const [preview, onPreview] = usePreview();
-  const { getValues } = useFormContext();
+  const { getValues, watch } = useFormContext();
   const [type] = getValues(fields);
```
Comment (domasx2) [inline public/app/features/alerting/unified/components/rule-editor/PreviewRule.tsx:19]:
```suggestion
  const type = watch('type');
```

**Review by domasx2 — APPROVED** [review]
