### PR TITLE
Graphite: Handle unknown Graphite functions without breaking the visual editor

### LINKED ISSUE #26174: Query panel disappear after switching from one graphite datasource to another
**What happened**:
Query panel disappear after switching from one graphite datasource to another

Please, take a look on the attached screenshots. 
Before 
Screenshot_20200708_194947
and after
Screenshot_20200708_183703
 switching datasources. 
Panel have disappeared.

Browser debug console shows

```
    XHR POST https://grafana.xxx.xxx/api/datasources/proxy/14/render
    [HTTP/1.1 200 OK 219ms]

error parsing target: Method not found reduceSeries graphite_query.ts:57:14
```

Switching back to previous datasource does not fix problem. Browser debug console shows up next error

```
    Uncaught (in promise) TypeError: t is undefined
        r promiseToDigest.ts:3
        value query_ctrl.ts:64
        t query_ctrl.ts:41
```

**What you expected to happen**:
I expect normal switch to new datasource
**How to reproduce it (as minimally and precisely as possible)**:
* Setup dashboard with reduceSeries function in query. 
* Switch to graphite datasource with carbonapi>=0.12.6 as backend

**Anything else we need to know?**:
Switching graphite api version in datasource settings from 1.1.x to 1.0.x fix the problem

**Environment**:
- Grafana version: 6.7.2, 6.7.3, 6.7.4
- Data source type & version: graphite datasource native plugin
- OS Grafana is installed on: ubuntu 14.04
- User OS & Browser: Firefox 78.0.1
- Graphite backend - carbonapi 0.12.6/0.13.0

### PR DESCRIPTION
**Pull request by ifrost**
**What this PR does / why we need it**:

Graphite parser creates a list of function names entered by the user in the query. If any function does not exist on the list of defined functions it throws an error. The list of defined functions is hardcoded for versions 0.9 and 1.0 and received from graphite-web API in 1.1.

The error caused by an unknown function locks the editor in raw mode. This PR adds handling unknown functions to keep the visual editor available with clearer indication which function has not been recognised (a warning icon). This may happen when switching between different datasources (with different set of supported functions) or when mistyping a function name in the raw editor:

unknown-functions

**Which issue(s) this PR fixes**:

Fixes #26174

**Special notes for your reviewer**: -

### CODE REVIEW

File: public/app/plugins/datasource/graphite/FunctionEditor.tsx [hunk 1]
```diff
@@ -68,6 +68,11 @@ class FunctionEditor extends React.PureComponent<FunctionEditorProps, FunctionEd
                   onClick={popperProps.show ? hidePopper : showPopper}
                   style={{ cursor: 'pointer' }}
                 >
+                  {this.props.func.def.unknown && (
```
Comment (Elfo404) [inline public/app/plugins/datasource/graphite/FunctionEditor.tsx:71]: NIT: I like the idea of showing a warning to the user in this case, but wouldn't this clutter the interface a bit too much?

what about something like (pseudocode): 

```tsx
<span 
    ref={this.triggerRef}
    onClick={popperProps.show ? hidePopper : showPopper}
    style={{ cursor: 'pointer' }}
    className={cx(this.props.func.def.unknown && 'a_slighlty_different_color_that_indicates_a_warning'}
>
  {this.props.func.def.unknown ? (
    <Tooltip content="This function is not on the list of supported functions." placement="bottom">
      {this.props.func.def.name}
    </Tooltip>) : this.props.func.def.name }
</span>
```

**Review by Elfo404 — CHANGES_REQUESTED** [review]
that's nice! 🚀 

aside from the enzyme thing it looks great!

File: public/app/plugins/datasource/graphite/FunctionEditor.test.tsx [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+    },
+  };
+}
+
+describe('FunctionEditor', () => {
+  it('should display a defined function with name and no icon', () => {
+    const component = mount(
+      <FunctionEditor
+        func={mockFunctionDescriptor('foo')}
+        onMoveLeft={jest.fn()}
```
[the remark this answers is not in the document]
Comment (ifrost) [reply public/app/plugins/datasource/graphite/FunctionEditor.test.tsx:26]: It's a required prop, but can be an empty function as well. I'll change it 👍

File: public/app/plugins/datasource/graphite/FunctionEditor.tsx (hunk 1 above)
Comment (ifrost) [reply public/app/plugins/datasource/graphite/FunctionEditor.tsx:71]: Because I'm color-blind and I need something else 😭 I was thinking about wavy underline but wasn't sure. I'll run it by UX.

File: public/app/plugins/datasource/graphite/FunctionEditor.test.tsx [hunk 3]
```diff
@@ -0,0 +1,53 @@
+import React from 'react';
+import { mount } from 'enzyme';
```
[the remark this answers is not in the document]
Comment (ifrost) [reply public/app/plugins/datasource/graphite/FunctionEditor.test.tsx:2]: Will do!

- [ ] convert to testing-library

File: public/app/plugins/datasource/graphite/FunctionEditor.tsx (hunk 1 above)
Comment (Elfo404) [reply public/app/plugins/datasource/graphite/FunctionEditor.tsx:71]: Good point!

btw, i'm not even sure it's needed since if the function is not defined you get an error anyway. but better loop UX in 👍

Comment (ifrost) [reply public/app/plugins/datasource/graphite/FunctionEditor.tsx:71]: I've added some changes suggested by UX:
- red border around the label
- padding between the icon and the label
- more descriptive tooltip content

> (...) btw, i'm not even sure it's needed since if the function is not defined you get an error anyway (...)

This is still useful in cases where there are multiple queries/functions. The error message contains only one unsupported function even if there are many:

Screenshot 2021-04-06 at 16 11 22

File: public/app/plugins/datasource/graphite/FunctionEditor.tsx [hunk 4]
```diff
@@ -68,6 +68,16 @@ class FunctionEditor extends React.PureComponent<FunctionEditorProps, FunctionEd
...
+                    <Tooltip content={<TooltipContent />} placement="bottom">
+                      <Icon
+                        data-testid="warning-icon"
+                        name="exclamation-triangle"
+                        size="xs"
+                        style={{ marginRight: '2px' }}
```
Comment (Elfo404) [inline public/app/plugins/datasource/graphite/FunctionEditor.tsx:77]: NIT: you might want to use `spacing.xss` from grafana theme

something like:
```
const theme = useTheme();
// ..
<Icon
  className={css`margin-right: ${theme.spacing.xss}`}
/>

Comment (Elfo404) [reply public/app/plugins/datasource/graphite/FunctionEditor.tsx:77]: i also wonder if we could use `aria-role="alert"` to make it more a11y-friendly, but I don't know how nicely it plays with the tooltip

File: public/app/plugins/datasource/graphite/FunctionEditor.test.tsx [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+      <FunctionEditor
+        func={mockFunctionDescriptor('foo')}
+        onMoveLeft={() => {}}
+        onMoveRight={() => {}}
+        onRemove={() => {}}
+      />
+    );
+
+    expect(screen.queryByText('foo')).toBeTruthy();
+    expect(screen.queryByTestId('warning-icon')).toBeNull();
```
Comment (Elfo404) [inline public/app/plugins/datasource/graphite/FunctionEditor.test.tsx:33]:
```suggestion
    expect(screen.getByText('alert')).toBeInTheDocument()
    expect(screen.queryByTestId('warning-icon')).not.toBeInTheDocument();
```

**Review by Elfo404 — CHANGES_REQUESTED** [review]
Looks great! 
We had some discussion a couple of weeks ago about using the custom matches for this kind of situation: https://github.com/grafana/grafana/pull/32212

I kinda don't like using `*ByTestId`, but as commented there I suspect there's not much we can do as I don't think `aria-role="alert"` really plays nice with the tooltip, so I think it's ok

And it looks great! I really like it! 🔥

File: public/app/plugins/datasource/graphite/FunctionEditor.tsx (hunk 4 above)
Comment (ifrost) [reply public/app/plugins/datasource/graphite/FunctionEditor.tsx]: > NIT: you might want to use spacing.xss from grafana theme

I like it! And sorry but I ended up making the component functional :P 

> i also wonder if we could use aria-role="alert" to make it more a11y-friendly, but I don't know how nicely it plays with the tooltip

I was thinking about it but according to [docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role) it might be too verbose:

> (...) Because of its intrusive nature, the alert role must be used sparingly and only in situations where the user's immediate attention is required.  (...)

**Review by Elfo404 — APPROVED** [review]
looks sick! 🚀

**Comment by Elfo404** [comment]
Maybe we want this added to the changelog as well? if so remember to add `add to changelog` label :)
