### PR TITLE
StateTimeline: Fix use of hidden fields in data links

### LINKED ISSUE #93616: StateTimeline: Hidden fields cannot be used for data links
we currently remove `hideFrom: viz` fields from the data, which makes them unusable in data macros. instead, we should take the same approach as in BarChart [1] and make dedicated frames for viz data and use original frames to be used in links.

<details><summary>hidden-field-links-state-timeline.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 364,
  "links": [],
  "panels": [
    {
      "datasource": {
        "default": true,
        "type": "grafana-testdata-datasource",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "fillOpacity": 70,
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineWidth": 0,
            "spanNulls": false
          },
          "links": [
            {
              "title": "${__data.fields.region}",
              "url": "${__data.fields.region}"
            }
          ],
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "region"
            },
            "properties": [
              {
                "id": "custom.hideFrom",
                "value": {
                  "legend": false,
                  "tooltip": false,
                  "viz": true
                }
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "maxDataPoints": 10,
      "options": {
        "alignValue": "left",
        "legend": {
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "mergeValues": true,
        "rowHeight": 0.9,
        "showValue": "auto",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "grafana-testdata-datasource",
            "uid": "PD8C576611E62080A"
          },
          "rawFrameContent": "[\n  {\n    \"schema\": {\n      \"refId\": \"A\",\n      \"fields\": [\n        {\n          \"name\": \"time\",\n          \"type\": \"time\",\n          \"config\": {\n            \"interval\": 1800000\n          }\n        },\n        {\n          \"name\": \"A-series\",\n          \"type\": \"number\",\n          \"labels\": {},\n          \"config\": {}\n        },\n        {\n          \"name\": \"region\",\n          \"type\": \"string\",\n          \"labels\": {},\n          \"config\": {}\n        }\n      ]\n    },\n    \"data\": {\n      \"values\": [\n        [\n          1727083433579,\n          1727085233579,\n          1727087033579,\n          1727088833579,\n          1727090633579,\n          1727092433579,\n          1727094233579,\n          1727096033579,\n          1727097833579,\n          1727099633579,\n          1727101433579,\n          1727103233579\n        ],\n        [\n          5.60999280425672,\n          -1.0149102853872263,\n          -19.984928537967168,\n          -52.67782221471374,\n          -82.71383588147009,\n          -88.02484468320455,\n          -92.65414104354055,\n          -139.99558226037362,\n          -153.98060212057743,\n          -190.21589425770395,\n          -170.8839524374352,\n          -172.97583600019817\n        ],\n        [\n          \"a\",\n          \"a\",\n          \"a\",\n          \"a\",\n          \"a\",\n          \"a\",\n          \"a\",\n          \"a\",\n          \"a\",\n          \"a\",\n          \"a\",\n          \"a\"\n        ]\n      ]\n    }\n  }\n]",
          "refId": "A",
          "scenarioId": "raw_frame"
        }
      ],
      "title": "Panel Title",
      "type": "state-timeline"
    }
  ],
  "refresh": "",
  "schemaVersion": 39,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "2024-09-23T09:16:28.166Z",
    "to": "2024-09-23T15:30:40.310Z"
  },
  "timepicker": {},
  "timezone": "browser",
  "title": "hidden-field-links-state-timeline",
  "uid": "bdys1gyi4bym8b",
  "version": 2,
  "weekStart": ""
}
```
</details>

Image

https://github.com/grafana/grafana/blob/d630e9bcb35e889dff57f993fa184ffacfb9bb10/public/app/plugins/panel/barchart/BarChartPanel.tsx#L84-L91

### PR DESCRIPTION
**Pull request by gelicia**
**What is this feature?**

There is a feature in grafana, available via field overrides, that lets you hide series from the visualization but not other elements. For instance, someone might want to not see data as part of a visualization but would want it in a data link. The hide options were enabled for state timeline but it filtering fields completely rather than saving them for use outside of the visualization but hiding it from the visual elements. This removes that filter and adds it in closer to where the visualization is generated.

NOTE: this feature works correctly when consecutive state merging is disabled. otherwise it may not work correctly when merged states dont have coinciding start timestamps.

image

**Why do we need this feature?**

To create data links with hidden series data.

**Which issue(s) does this PR fix?**:

Related: #93616
Relates to https://github.com/grafana/support-escalations/issues/12271

**Special notes for your reviewer:**

<details><summary>Sample dashboard</summary>

```json

{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 217,
  "links": [],
  "panels": [
    {
      "datasource": {
        "type": "grafana-testdata-datasource",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "fillOpacity": 70,
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineWidth": 0,
            "spanNulls": false
          },
          "links": [
            {
              "title": "",
              "url": "http://google.com/search?q=${__data.fields.stat2}"
            }
          ],
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 3
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "stat2"
            },
            "properties": [
              {
                "id": "custom.hideFrom",
                "value": {
                  "legend": false,
                  "tooltip": false,
                  "viz": true
                }
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "alignValue": "center",
        "legend": {
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "mergeValues": false,
        "rowHeight": 0.9,
        "showValue": "always",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "11.4.0-pre",
      "targets": [
        {
          "csvContent": "date,stat1,stat2,stat3\n1729537261000,1,2,3\n1729537251000,1,2,3\n1729537241000,1,2,3\n1729537231000,1,2,3\n1729537221000,1,2,3",
          "refId": "A",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "transformations": [
        {
          "id": "convertFieldType",
          "options": {
            "conversions": [
              {
                "destinationType": "time",
                "targetField": "date"
              }
            ],
            "fields": {}
          }
        }
      ],
      "type": "state-timeline"
    }
  ],
  "preload": false,
  "schemaVersion": 40,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "browser",
  "title": "95095",
  "uid": "be1l8jn4j3o5cb",
  "version": 2,
  "weekStart": ""
}
```
</details>

<details><summary>state-timeline-hideFrom.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 377,
  "links": [],
  "panels": [
    {
      "datasource": {
        "default": true,
        "type": "grafana-testdata-datasource",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "fillOpacity": 70,
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineWidth": 0,
            "spanNulls": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "A-series2"
            },
            "properties": [
              {
                "id": "custom.hideFrom",
                "value": {
                  "legend": false,
                  "tooltip": false,
                  "viz": true
                }
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 19,
        "w": 16,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "maxDataPoints": 20,
      "options": {
        "alignValue": "left",
        "legend": {
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "mergeValues": true,
        "rowHeight": 0.9,
        "showValue": "auto",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "grafana-testdata-datasource",
            "uid": "PD8C576611E62080A"
          },
          "rawFrameContent": "[\n  {\n    \"schema\": {\n      \"refId\": \"A\",\n      \"meta\": {\n        \"typeVersion\": [\n          0,\n          0\n        ],\n        \"custom\": {\n          \"customStat\": 10\n        }\n      },\n      \"fields\": [\n        {\n          \"name\": \"time\",\n          \"type\": \"time\",\n          \"typeInfo\": {\n            \"frame\": \"time.Time\",\n            \"nullable\": true\n          },\n          \"config\": {\n            \"interval\": 21600000\n          }\n        },\n        {\n          \"name\": \"A-series\",\n          \"type\": \"number\",\n          \"typeInfo\": {\n            \"frame\": \"float64\",\n            \"nullable\": true\n          },\n          \"labels\": {},\n          \"config\": {}\n        }\n      ]\n    },\n    \"data\": {\n      \"values\": [\n        [\n          1729372268262,\n          1729393868262,\n          1729415468262,\n          1729437068262,\n          1729458668262,\n          1729480268262,\n          1729501868262,\n          1729523468262,\n          1729545068262,\n          1729566668262,\n          1729588268262,\n          1729609868262,\n          1729631468262,\n          1729653068262,\n          1729674668262,\n          1729696268262\n        ],\n        [\n          61.772564578934606,\n          175.02260003434006,\n          -242.40606457832416,\n          -64.69574475981159,\n          171.75628164368072,\n          412.32553290918037,\n          193.74811801612805,\n          269.42988341696827,\n          329.7644040168287,\n          674.5280378200961,\n          639.701072111102,\n          252.8893708798898,\n          560.308245426107,\n          327.59037294534403,\n          826.8504049399908,\n          1273.2813178174051\n        ]\n      ]\n    }\n  },\n  {\n    \"schema\": {\n      \"refId\": \"A\",\n      \"meta\": {\n        \"typeVersion\": [\n          0,\n          0\n        ],\n        \"custom\": {\n          \"customStat\": 10\n        }\n      },\n      \"fields\": [\n        {\n          \"name\": \"time\",\n          \"type\": \"time\",\n          \"typeInfo\": {\n            \"frame\": \"time.Time\",\n            \"nullable\": true\n          },\n          \"config\": {\n            \"interval\": 21600000\n          }\n        },\n        {\n          \"name\": \"A-series1\",\n          \"type\": \"number\",\n          \"typeInfo\": {\n            \"frame\": \"float64\",\n            \"nullable\": true\n          },\n          \"labels\": {},\n          \"config\": {}\n        }\n      ]\n    },\n    \"data\": {\n      \"values\": [\n        [\n          1729372268262,\n          1729393868262,\n          1729415468262,\n          1729437068262,\n          1729458668262,\n          1729480268262,\n          1729501868262,\n          1729523468262,\n          1729545068262,\n          1729566668262,\n          1729588268262,\n          1729609868262,\n          1729631468262,\n          1729653068262,\n          1729674668262,\n          1729696268262\n        ],\n        [\n          48.56104274436573,\n          471.62437757501,\n          617.9193102169953,\n          581.3291295805906,\n          320.98757901852196,\n          535.7611302549631,\n          147.59474196533947,\n          629.6247631505431,\n          508.38578957835773,\n          851.4841217901278,\n          563.7037322535721,\n          772.2416686378049,\n          662.2090769979106,\n          1176.661819090698,\n          1235.938814161856,\n          1720.931201009116\n        ]\n      ]\n    }\n  },\n  {\n    \"schema\": {\n      \"refId\": \"A\",\n      \"meta\": {\n        \"typeVersion\": [\n          0,\n          0\n        ],\n        \"custom\": {\n          \"customStat\": 10\n        }\n      },\n      \"fields\": [\n        {\n          \"name\": \"time\",\n          \"type\": \"time\",\n          \"typeInfo\": {\n            \"frame\": \"time.Time\",\n            \"nullable\": true\n          },\n          \"config\": {\n            \"interval\": 21600000\n          }\n        },\n        {\n          \"name\": \"A-series2\",\n          \"type\": \"string\",\n          \"labels\": {},\n          \"config\": {}\n        }\n      ]\n    },\n    \"data\": {\n      \"values\": [\n        [\n          1729372268262,\n          1729393868262,\n          1729415468262,\n          1729437068262,\n          1729458668262,\n          1729480268262,\n          1729501868262,\n          1729523468262,\n          1729545068262,\n          1729566668262,\n          1729588268262,\n          1729609868262,\n          1729631468262,\n          1729653068262,\n          1729674668262,\n          1729696268262\n        ],\n        [\n          \"a\",\n          \"b\",\n          \"c\",\n          \"d\",\n          \"e\",\n          \"f\",\n          \"g\",\n          \"h\",\n          \"i\",\n          \"j\",\n          \"k\",\n          \"l\",\n          \"m\",\n          \"n\",\n          \"o\",\n          \"p\"\n        ]\n      ]\n    }\n  }\n]",
          "refId": "A",
          "scenarioId": "raw_frame"
        }
      ],
      "title": "Panel Title",
      "type": "state-timeline"
    }
  ],
  "schemaVersion": 40,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "2024-10-19T21:11:08.262Z",
    "to": "2024-10-23T21:11:08.262Z"
  },
  "timepicker": {},
  "timezone": "browser",
  "title": "state-timeline-hideFrom",
  "uid": "fe1l8q3327togc",
  "version": 4,
  "weekStart": ""
}
```
</details>

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-data/src/field/fieldState.ts [hunk 1]
```diff
@@ -101,7 +101,16 @@ export function decoupleHideFromState(frames: DataFrame[], fieldConfig: FieldCon
       };
 
       // original with perm overrides
-      field.config.custom.hideFrom = hideFrom;
+      if (field.config.custom !== undefined) {
```
Comment (gelicia) [inline packages/grafana-data/src/field/fieldState.ts:104]: I only added this because the tests were hitting it, if youd rather have me leave it and change the test, I can do that!

File: public/app/core/components/GraphNG/GraphNG.tsx [hunk 2]
```diff
@@ -167,7 +167,9 @@ export class GraphNG extends Component<GraphNGProps, GraphNGState> {
         // filter join field and fields.y
         alignedFrameFinal = {
           ...alignedFrame,
-          fields: alignedFrame.fields.filter((field, i) => i === 0 || fields.y(field, alignedFrame, [alignedFrame])),
+          fields: alignedFrame.fields
+            .filter((field, i) => i === 0 || fields.y(field, alignedFrame, [alignedFrame]))
+            .filter((field) => field.config.custom?.hideFrom?.viz !== true),
```
Comment (gelicia) [inline public/app/core/components/GraphNG/GraphNG.tsx:172]: combine

**Review by Develer — DISMISSED** [review]

**Comment by leeoniya** [comment]
unfortunately, this approach breaks TimeSeries panel when toggling legend. we'll have to approach this differently.

<details><summary>graph-ng-hideFrom-links.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 405,
  "links": [],
  "panels": [
    {
      "datasource": {
        "default": true,
        "type": "grafana-testdata-datasource",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "align": "auto",
            "cellOptions": {
              "type": "auto"
            },
            "inspect": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 10,
        "w": 5,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "maxDataPoints": 10,
      "options": {
        "cellHeight": "sm",
        "footer": {
          "countRows": false,
          "fields": "",
          "reducer": [
            "sum"
          ],
          "show": false
        },
        "frameIndex": 0,
        "showHeader": true
      },
      "pluginVersion": "11.4.0-pre",
      "targets": [
        {
          "datasource": {
            "type": "grafana-testdata-datasource",
            "uid": "PD8C576611E62080A"
          },
          "rawFrameContent": "[\n  {\n    \"schema\": {\n      \"refId\": \"A\",\n      \"meta\": {\n        \"typeVersion\": [\n          0,\n          0\n        ],\n        \"custom\": {\n          \"customStat\": 10\n        }\n      },\n      \"fields\": [\n        {\n          \"name\": \"time\",\n          \"type\": \"time\",\n          \"typeInfo\": {\n            \"frame\": \"time.Time\",\n            \"nullable\": true\n          },\n          \"config\": {\n            \"interval\": 1800000\n          }\n        },\n        {\n          \"name\": \"A-series\",\n          \"type\": \"number\",\n          \"typeInfo\": {\n            \"frame\": \"float64\",\n            \"nullable\": true\n          },\n          \"labels\": {},\n          \"config\": {}\n        },\n        {\n          \"name\": \"A-series1\",\n          \"type\": \"number\",\n          \"typeInfo\": {\n            \"frame\": \"float64\",\n            \"nullable\": true\n          },\n          \"labels\": {},\n          \"config\": {}\n        }\n      ]\n    },\n    \"data\": {\n      \"values\": [\n        [\n          1732322243069,\n          1732324043069,\n          1732325843069,\n          1732327643069,\n          1732329443069,\n          1732331243069,\n          1732333043069,\n          1732334843069,\n          1732336643069,\n          1732338443069,\n          1732340243069,\n          1732342043069\n        ],\n        [\n          31.780036033415037,\n          37.279932599336675,\n          22.589709282048084,\n          -5.746401029619978,\n          -41.20664708580816,\n          -67.56729325521567,\n          -84.78414441497958,\n          -51.074482946673875,\n          -54.14054786538971,\n          -44.972820650884216,\n          -46.747527043148374,\n          -11.131738336590558\n        ],\n        [\n          31.780036033415037,\n          15.417945098024827,\n          50.30681192279489,\n          11.794890920763713,\n          -30.009132893248598,\n          -69.0809130514628,\n          -113.44271486846236,\n          -95.36072106125508,\n          -140.7164796267919,\n          -113.00771928074624,\n          -160.85636741074,\n          -186.042981738422\n        ]\n      ]\n    }\n  },\n  {\n    \"schema\": {\n      \"refId\": \"B\",\n      \"meta\": {\n        \"typeVersion\": [\n          0,\n          0\n        ],\n        \"custom\": {\n          \"customStat\": 10\n        }\n      },\n      \"fields\": [\n        {\n          \"name\": \"time\",\n          \"type\": \"time\",\n          \"typeInfo\": {\n            \"frame\": \"time.Time\",\n            \"nullable\": true\n          },\n          \"config\": {\n            \"interval\": 1800000\n          }\n        },\n        {\n          \"name\": \"B-series\",\n          \"type\": \"number\",\n          \"typeInfo\": {\n            \"frame\": \"float64\",\n            \"nullable\": true\n          },\n          \"labels\": {},\n          \"config\": {}\n        },\n        {\n          \"name\": \"B-series1\",\n          \"type\": \"number\",\n          \"typeInfo\": {\n            \"frame\": \"float64\",\n            \"nullable\": true\n          },\n          \"labels\": {},\n          \"config\": {}\n        },\n        {\n          \"name\": \"B-series2\",\n          \"type\": \"number\",\n          \"typeInfo\": {\n            \"frame\": \"float64\",\n            \"nullable\": true\n          },\n          \"labels\": {},\n          \"config\": {}\n        }\n      ]\n    },\n    \"data\": {\n      \"values\": [\n        [\n          1732322243069,\n          1732324043069,\n          1732325843069,\n          1732327643069,\n          1732329443069,\n          1732331243069,\n          1732333043069,\n          1732334843069,\n          1732336643069,\n          1732338443069,\n          1732340243069,\n          1732342043069\n        ],\n        [\n          22.82852829258531,\n          -14.12546670005699,\n          -48.29960919062656,\n          -26.998458819700282,\n          -62.537605160316275,\n          -22.583263862665333,\n          -46.53824503113624,\n          -36.39494012376462,\n          -15.463866299173493,\n          -40.23043019027155,\n          -76.24588161519044,\n          -37.256020130745355\n        ],\n        [\n          22.82852829258531,\n          49.756703986213786,\n          51.867343208552235,\n          53.06701877646672,\n          36.69955279928066,\n          16.707127678385852,\n          46.15196333366451,\n          21.40377272384856,\n          26.23793055282944,\n          13.976436427475518,\n          23.9680303961498,\n          25.567327366692464\n        ],\n        [\n          22.82852829258531,\n          27.897385259465153,\n          62.24319862052406,\n          51.765411763154034,\n          79.7338232660895,\n          66.08819185534006,\n          98.21181395243417,\n          73.44008746542926,\n          122.05100472432039,\n          113.09102870033527,\n          69.97898231137873,\n          83.132712951098\n        ]\n      ]\n    }\n  }\n]",
          "refId": "A",
          "scenarioId": "raw_frame"
        }
      ],
      "title": "Table",
      "type": "table"
    },
    {
      "datasource": {
        "default": false,
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "barWidthFactor": 0.6,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 10,
        "w": 5,
        "x": 5,
        "y": 0
      },
      "id": 2,
      "maxDataPoints": 10,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "11.4.0-pre",
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 1,
          "refId": "A"
        }
      ],
      "title": "TimeSeries",
      "type": "timeseries"
    },
    {
      "datasource": {
        "default": false,
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "barWidthFactor": 0.6,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 10,
        "w": 5,
        "x": 10,
        "y": 0
      },
      "id": 3,
      "maxDataPoints": 10,
      "options": {
        "candleStyle": "candles",
        "colorStrategy": "open-close",
        "colors": {
          "down": "red",
          "up": "green"
        },
        "includeAllFields": false,
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "mode": "candles+volume",
        "tooltip": {
          "mode": "multi",
          "sort": "none"
        }
      },
      "pluginVersion": "11.4.0-pre",
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 1,
          "refId": "A"
        }
      ],
      "title": "Candlestick",
      "type": "candlestick"
    },
    {
      "datasource": {
        "default": false,
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "fillOpacity": 70,
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineWidth": 0,
            "spanNulls": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "orange",
                "value": 50
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 5,
        "x": 5,
        "y": 10
      },
      "id": 4,
      "maxDataPoints": 10,
      "options": {
        "alignValue": "left",
        "legend": {
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "mergeValues": true,
        "rowHeight": 0.9,
        "showValue": "auto",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "11.4.0-pre",
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 1,
          "refId": "A"
        }
      ],
      "title": "StateTimeline",
      "type": "state-timeline"
    },
    {
      "datasource": {
        "default": false,
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "fillOpacity": 70,
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "orange",
                "value": 50
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 5,
        "x": 10,
        "y": 10
      },
      "id": 5,
      "maxDataPoints": 10,
      "options": {
        "colWidth": 0.9,
        "legend": {
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "rowHeight": 0.9,
        "showValue": "auto",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "11.4.0-pre",
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 1,
          "refId": "A"
        }
      ],
      "title": "StatusHistory",
      "type": "status-history"
    }
  ],
  "schemaVersion": 40,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "2024-11-23T00:23:34.758Z",
    "to": "2024-11-23T06:23:32.705Z"
  },
  "timepicker": {},
  "timezone": "browser",
  "title": "graph-ng-hideFrom-links",
  "uid": "ae4sdf44tiw3kd",
  "version": 8,
  "weekStart": ""
}
```
</details>

File: packages/grafana-data/src/field/fieldState.ts [hunk 3]
```diff
@@ -62,11 +62,32 @@ export function cacheFieldDisplayNames(frames: DataFrame[]) {
...
+        config: {
+          ...field.config,
+          custom: {
+            ...field.config.custom,
+            hideFrom: {
+              ...field.config.custom?.hideFrom,
+            },
+          },
+        },
+      };
```
Comment (leeoniya) [inline packages/grafana-data/src/field/fieldState.ts:89]: this removes the mutation, allowing the before/after config diff to invalidate and re-init uPlot

File: public/app/core/components/TimeSeries/utils.ts [hunk 4]
```diff
@@ -497,7 +497,7 @@ export const preparePlotConfigBuilder: UPlotConfigPrepFn = ({
       barMaxWidth: customConfig.barMaxWidth,
       pointSize: customConfig.pointSize,
       spanNulls: customConfig.spanNulls || false,
-      show: !customConfig.hideFrom?.viz,
+      show: !customConfig.hideFrom?.viz && !field.state?.hideFrom?.viz,
```
Comment (leeoniya) [inline public/app/core/components/TimeSeries/utils.ts:500]: this `show` property is a hack that're really only needed for PlotLegend (i think).

we should actually never have a `show: false` uPlot series and omit adding any series that is not visible, instead of always adding a series with different `show` values.

File: public/app/core/components/TimeSeries/TimeSeries.tsx [hunk 5]
```diff
@@ -31,14 +31,14 @@ export class UnthemedTimeSeries extends Component<TimeSeriesProps> {
...
-  renderLegend = (config: UPlotConfigBuilder) => {
+  renderLegend = (config: UPlotConfigBuilder, alignedFrame: DataFrame) => {
     const { legend, frames } = this.props;
 
     if (!config || (legend && !legend.showLegend) || !hasVisibleLegendSeries(config, frames)) {
       return null;
     }
 
-    return <PlotLegend data={frames} config={config} {...legend} />;
+    return <PlotLegend data={[alignedFrame]} config={config} {...legend} />;
```
Comment (leeoniya) [inline public/app/core/components/TimeSeries/TimeSeries.tsx:41]: this array-wrap probably breaks PlotLegend's `React.memo`. need to fix/cache.

**Review by leeoniya — APPROVED** [review]

File: public/app/core/components/GraphNG/GraphNG.tsx [hunk 6]
```diff
@@ -52,6 +52,12 @@ export interface GraphNGProps extends Themeable2 {
   dataLinkPostProcessor?: DataLinkPostProcessor;
   cursorSync?: DashboardCursorSync;
 
+  // this is a temporary hack that only works when:
+  // 1. renderLegend (above) does not render <PlotLegend>
+  // 2. does not have legend series toggle
+  // 3. passes through all fields required for link/action gen (including those with hideFrom.viz)
+  omitHideFromViz?: boolean;
```
Comment (leeoniya) [inline public/app/core/components/GraphNG/GraphNG.tsx:59]: not great, but will work for now, until this GraphNG abstraction layer disappears.
