### PR TITLE
Histogram: ensure y axis is unit-less

### LINKED ISSUE #54654: Units also show on Y axis Histogram Panel
**What happened**:
The Unit is replicated on both axis on **Histogram panel**. which ideally should only be on the X axis and Y axis should show the count/density.

image

**What you expected to happen**:
The Y axis should just show the count of occurrences and not inherit the unit on Y axis or if possible show the density.

**How to reproduce it (as minimally and precisely as possible)**:
Setting the Unit to any existing histogram panel
**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.2 (3c13120cde) Enterprise (Free & unlicensed)
- Data source type & version: MySQL
- OS Grafana is installed on: Docker Container
- User OS & Browser: Safari/Chrome
- Grafana plugins: NA
- Others:

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes #54654

### CODE REVIEW

File: packages/grafana-data/src/transformations/transformers/histogram.ts [hunk 1]
```diff
@@ -220,7 +220,7 @@ export function buildHistogram(frames: DataFrame[], options?: HistogramTransform
           ...field,
           config: {
             ...field.config,
-            unit: undefined,
+            unit: field.config.unit === 'short' ? 'short' : undefined,
```
Comment (leeoniya) [inline packages/grafana-data/src/transformations/transformers/histogram.ts:223]: this adds an allowance for `short`, which is still unitless, but could be useful for large Y counts

**Review by ryantxu — APPROVED** [review]

**Comment by sirianni** [comment]
This doesn't seem to be fixed
image
