### PR TITLE
AzureMonitor: Fixes metric definition for Azure Storage queue/file/blob/table resources.

### LINKED ISSUE #48794: Can't get metrics for Azure Storage Queue (Queue Message Count, for example)
**What happened**:

Can't get metrics data for Azure Storage **Queue** (Message Count, for example)

**What you expected to happen**:

Be able to get the metrics.

**How to reproduce it (as minimally and precisely as possible)**:

Try to add a metrics query:

image

**Anything else we need to know?**:

Other metrics works like, like `Storage Account`, `App Service` ... but not the queue, blob, table, etc.
image

**Environment**:
- Grafana version: v8.4.5 (4cafe613e)
- Data source type & version: Azure Monitor (hosted, where to get the version?)
- OS Grafana is installed on: Azure Hosted.
- User OS & Browser: Windows 11, Chrome.
- Grafana plugins: Azure Monitor
- Others:

### PR DESCRIPTION
**Pull request by aangelisc**
- Nested storage account resources (queues/blobs/tables/files) require metric definition of Microsoft.Storage/storageAccounts
- Update tests accordingly

**What this PR does / why we need it**:

Azure Storage Accounts can contain queue/table/file/blob sub-resources. Currently, we use the metric namespace as the filter for identifying resources. However, the correct metric definition for these resources is `Microsoft.Storage/storageAccounts`. This change appropriately sets the metric definition.

**Which issue(s) this PR fixes**:

Fixes #48794 

**Special notes for your reviewer**:

Tested using a storage account with a queue created and ensuring the correct metrics are displayed.

### CODE REVIEW

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts [hunk 1]
```diff
@@ -207,9 +207,12 @@ export default class AzureMonitorDatasource extends DataSourceWithBackend<AzureM
   }
 
   getResourceNames(subscriptionId: string, resourceGroup: string, metricDefinition: string, skipToken?: string) {
+    const validMetricDefinition = startsWith(metricDefinition, 'Microsoft.Storage/storageAccounts/')
+      ? 'Microsoft.Storage/storageAccounts'
+      : metricDefinition;
     let url =
       `${this.resourcePath}/subscriptions/${subscriptionId}/resourceGroups/${resourceGroup}/resources?` +
-      `$filter=resourceType eq '${metricDefinition}'&` +
+      `$filter=resourceType eq '${validMetricDefinition}'&` +
```
Comment (sarahzinger) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts:215]: cool stuff, is it possible to write a test for this?

**Review by sarahzinger — APPROVED** [review]
Cool stuff thanks for fixing!

Random mostly unrelated things I have noticed here, that might be worth opening in their own issue or might be easy to fix here I'm not sure:
Screen Shot 2022-05-18 at 5 09 13 PM
- it's kind of odd here ^ the way we have this duplicated with different casing, do you know what's happening here?
- also I noticed when I tried to make a request for these metrics, I kept getting an error using the 'auto' time grain I'm not sure if that's a new issue or an old one, I'm guessing it's an old issue.

Edit to add: it feels worth adding to changelog to me, it'll show up under bug fixes if you add [Fix to the title](https://github.com/grafana/grafana/blob/7e332d6f97a88562b4016aa3d0cfc2ed177423d2/contribute/merge-pull-request.md) and add the label. This way if there's some kind of funky breaking change here we don't understand, people might be able to find the pr more easily to help us debug.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.test.ts [hunk 2]
```diff
@@ -447,28 +447,28 @@ describe('AzureMonitorDatasource', () => {
...
-
-        it('should return list of Resource Names', () => {
-          metricDefinition = 'Microsoft.Storage/storageAccounts/blobServices';
           return ctx.ds
             .getResourceNames(subscription, resourceGroup, metricDefinition)
             .then((results: Array<{ text: string; value: string }>) => {
               expect(results.length).toEqual(1);
               expect(results[0].text).toEqual('storagetest/default');
               expect(results[0].value).toEqual('storagetest/default');
+              expect(ctx.ds.azureMonitorDatasource.getResource).toHaveBeenCalledWith(
```
Comment (aangelisc) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.test.ts:469]: @sarahzinger I think this should be sufficient as a test, lmk what you think 😊

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/setQueryValue.ts [hunk 3]
```diff
@@ -109,6 +109,20 @@ export function setMetricNamespace(query: AzureMonitorQuery, metricNamespace: st
...
+    const baseUri = splitUri.slice(0, accountNameIndex + 1).join('/');
+    if (metricNamespace === 'Microsoft.Storage/storageAccounts') {
+      resourceUri = baseUri;
+    } else {
+      const subNamespace = metricNamespace.split('/')[2];
+      resourceUri = `${baseUri}/${subNamespace}/default`;
+    }
+  }
+
   return {
```
Comment (kevinwcyu) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/setQueryValue.ts:126]: I was just reading this https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview#types-of-storage-accounts and https://docs.microsoft.com/en-us/azure/storage/common/storage-account-create?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=azure-portal#create-a-storage-account-1 after reading this part of the code and the way I understand it is that the storage account is the resource, which is identified by the resource uri, and the different storage services (queue, blob, etc.) have different metrics which is the metric namespace. So I'm assuming we don't need to modify the resourceUri here.

I think it should still work without this. I also checked the Azure Portal and copied the link to the dashboard where I'm checking the storage account for a queue capacity metric and the resourceUri it uses doesn't include the sub namespace (storage service) part.

I clicked the copy link and used `decodeURIComponent` to see the resource uri (it's under the property resourceMetadata.id) in the decoded string.

Screen Shot 2022-05-19 at 11 30 09 AM

Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/setQueryValue.ts:126]: I don't think it can, if you take a look at the network requests made when selecting one of the other services besides default you'll see the relative URL will look something like this: 

`"/subscriptions/subId/resourcegroups/rgName/providers/Microsoft.Storage/storageAccounts/acctName/queueServices/default/providers/microsoft.Insights/metrics?timespan=2022-05-19T09:30:00.000Z/2022-05-20T09:30:00.000Z&interval=FULL&metricnames=QueueCapacity&aggregation=average&metricNamespace=microsoft.storage%2Fstorageaccounts%2Fqueueservices&validatedimensions=false&api-version=2019-07-01"`

Similarly, if you take a look at https://docs.microsoft.com/en-us/azure/storage/queues/monitor-queue-storage-reference#resource-logs the `resourceId` field implies that the resource URI needs the service and `default` paths appended. I did test this locally and I couldn't get it working without modifying the resource URI (which is annoying as it also then modifies the display name of the picked resource).

Comment (kevinwcyu) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/setQueryValue.ts:126]: Thanks for the explanation. I think it would be worth it to add a comment here to explain why the resourceUri needs to be modified just when it's a storage account.

**Review by kevinwcyu — APPROVED** [review]

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/setQueryValue.ts (hunk 3 above)
Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/setQueryValue.ts]: Have done this, thanks @kevinwcyu!
