### PR TITLE
Nested folders: Allow creating folders with duplicate names in different locations

### LINKED ISSUE #63082: Nested Folders: Strict constrain on nested folder titles
**What happened**:

Previously there was no a dedicated table for folders: they were stored in the `dashboard` table (with a `is_folder` flag set).
As part of the work in the nested folders: we introduced a table dedicated for folders (`folder`).
The `folder` table requires [folder titles to be unique under a folder](https://github.com/grafana/grafana/blob/f46f8bdd3acef271b77af9a98ceb2edf3bba3c9a/pkg/services/sqlstore/migrations/folder_mig.go#L25-L28).  The `dashboard` table also requires [the folder titles to be unique under a folder](https://github.com/grafana/grafana/blob/33277fccde146e49e2eb4f3f8afdf8c091ff7076/pkg/services/sqlstore/migrations/dashboard_mig.go#L176).
When creating a nested folder, for keeping [backward compatibility](https://docs.google.com/document/d/1trRt3KDJxBXa8khgmQgZB0n7KtVXE1UGX4v11FDBUv8/edit#heading=h.qdidspdfg89) we create an entry both in the `dashboard` table and in the new `folder` table.
However,  during folder creation when we insert the entry in the `dashboard` store we don't set the `folder_id` for folders. In fact, there is a check that prevents us:
https://github.com/grafana/grafana/blob/5f5f51b3bfba1d3b6f04847f15f81d6b78b97ce4/pkg/services/folder/folderimpl/folder.go#L605-L607

Hence, it's impossible to have the following folder structure:
- parent folder
	- subfolder
		- subfolder
		
Besides a frontend check prevents also this:
Screenshot 2023-02-08 at 12 52 26 PM

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/pull/72602
- [ ] https://github.com/grafana/grafana/issues/58184
- [ ] https://github.com/grafana/grafana/pull/74725
- [ ] https://github.com/grafana/grafana/pull/75817
- [ ] https://github.com/grafana/grafana/issues/74671
- [x] add schema migration for dashboard table to add `folder_uid` column
- [x] add data migration at the dashboard service startup to populater the `folder_uid` column
- [x] update dashboard service to store `folder_uid`
- [x] drop unique index on dashboard table using `folder_id`
- [x] introduce unique index on dashboard table using `folder_uid`
```

### LINKED ISSUE #71417: Allow creating folders with duplicate names in different locations
Can I create a folder with a duplicate name, if one in that location already exists? No
Can I create a folder with a duplicate name, if the duplicate is in a different location? Yes
Can I move a folder with a duplicate name to another folder where a duplicate exists? No

### PR DESCRIPTION
**Pull request by papagian**
**What is this feature?**

- removes old unique constrain on `dashboard` table and adds a new on `org_id`, `folder_uid`, `title`, `is_folder`
- updates all functions fetching a folder so that they fetch a root folder by default (current behavior) and fetch a subfolder only if the parent UID is provided

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #63082
Fixes #71417

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/services/dashboards/accesscontrol.go [hunk 1]
```diff
@@ -49,7 +49,9 @@ func NewFolderNameScopeResolver(folderDB folder.FolderStore, folderSvc folder.Se
 		if len(nsName) == 0 {
 			return nil, ac.ErrInvalidScope
 		}
-		folder, err := folderDB.GetFolderByTitle(ctx, orgID, nsName)
+		// this will fetch only root folders
+		// this is legacy code so most probably it is not used
+		folder, err := folderDB.GetFolderByTitle(ctx, orgID, nsName, nil)
```
Comment (papagian) [inline pkg/services/dashboards/accesscontrol.go:54]: @grafana/identity-access-team is this resolver used for newly created folders?

File: pkg/services/folder/folderimpl/folder.go [hunk 2]
```diff
@@ -418,8 +418,8 @@ func (s *Service) getFolderByUID(ctx context.Context, orgID int64, uid string) (
 	return s.dashboardFolderStore.GetFolderByUID(ctx, orgID, uid)
 }
 
-func (s *Service) getFolderByTitle(ctx context.Context, orgID int64, title string) (*folder.Folder, error) {
-	return s.dashboardFolderStore.GetFolderByTitle(ctx, orgID, title)
+func (s *Service) getFolderByTitle(ctx context.Context, orgID int64, title string, folderUID *string) (*folder.Folder, error) {
```
Comment (IevaVasiljeva) [inline pkg/services/folder/folderimpl/folder.go:421]: nit: would it be clearer if the variable was called `parentUID` not `folderUID`?

File: pkg/services/folder/service.go [hunk 3]
```diff
@@ -33,7 +35,10 @@ type Service interface {
 //go:generate mockery --name FolderStore --structname FakeFolderStore --outpkg foldertest --output foldertest --filename folder_store_mock.go
 type FolderStore interface {
 	// GetFolderByTitle retrieves a folder by its title
-	GetFolderByTitle(ctx context.Context, orgID int64, title string) (*Folder, error)
+	// It expects a folderUID as last argument.
+	// If folderUID is empty then the folder will be fetched from the root level
+	// otherwise it will be fetched from the subfolder under the folder with the given UID.
+	GetFolderByTitle(ctx context.Context, orgID int64, title string, folderUID *string) (*Folder, error)
```
Comment (IevaVasiljeva) [inline pkg/services/folder/service.go:41]: nit: same here, I think it would be easier to read if `folderUID` was called `parentUID` instead.

**Review by IevaVasiljeva — APPROVED** [review]
Great job! I tested this on the ephemeral instance, and it seems to be working as expected 👌 

Two comments (don't have to be addressed in this PR):
* the error that comes up when you attempt to create a folder with the same name as a folder that already exists in that level mentions the general folder (`a folder or dashboard in the general folder with the same name already exists`). I wonder how much effort it would be to customise it to the name of the folder that your in, or maybe just remove the "general folder" bit and say "a folder with the same name already exists in the current location".
* folder listing is a bit confusing if you can't see the full path to them, eg, here's a screenshot from the folder list when creating a new alert rule:
Screenshot 2024-01-23 at 18 19 54

**Comment by papagian** [comment]
> Great job! I tested this on the ephemeral instance, and it seems to be working as expected 👌
> 
> Two comments (don't have to be addressed in this PR):
> 
> * the error that comes up when you attempt to create a folder with the same name as a folder that already exists in that level mentions the general folder (`a folder or dashboard in the general folder with the same name already exists`). I wonder how much effort it would be to customise it to the name of the folder that your in, or maybe just remove the "general folder" bit and say "a folder with the same name already exists in the current location".

I did the latter for now

> * folder listing is a bit confusing if you can't see the full path to them, eg, here's a screenshot from the folder list when creating a new alert rule:
> 
> Screenshot 2024-01-23 at 18 19 54

I have also noticed: I think that alerting is already aware of that

File: pkg/services/dashboards/accesscontrol.go (hunk 1 above)
Comment (IevaVasiljeva) [reply pkg/services/dashboards/accesscontrol.go:54]: Do we then need to update the checks [here](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/api/authorization.go#L22-L30) to use a UID based scope instead of a name based scope?

So have 
```
eval = ac.EvalPermission(ac.ActionAlertingRuleDelete, dashboards.ScopeFoldersProvider.GetResourceScopeUID(ac.Parameter(":Namespace")))
```
instead of
```
eval = ac.EvalPermission(ac.ActionAlertingRuleDelete, dashboards.ScopeFoldersProvider.GetResourceScopeName(ac.Parameter(":Namespace")))
```

Comment (papagian) [reply pkg/services/dashboards/accesscontrol.go:54]: good catch!

File: pkg/services/dashboards/database/database.go [hunk 4]
```diff
@@ -346,9 +346,15 @@ func getExistingDashboardByIDOrUIDForUpdate(sess *db.Session, dash *dashboards.D
...
 	var existing dashboards.Dashboard
-	// nolint:staticcheck
-	exists, err := sess.Where("org_id=? AND title=? AND (is_folder=? OR folder_id=?)", dash.OrgID, dash.Title,
-		dialect.BooleanStr(true), dash.FolderID).Get(&existing)
+	condition := "org_id=? AND title=?"
+	args := []any{dash.OrgID, dash.Title}
+	if dash.FolderUID != "" {
+		condition += " AND folder_uid=?"
+		args = append(args, dash.FolderUID)
+	} else {
```
Comment (idafurjes) [inline pkg/services/dashboards/database/database.go:354]: is this else clause for a root folder?

Comment (papagian) [reply pkg/services/dashboards/database/database.go:354]: yes

**Review by idafurjes — APPROVED** [review]
LGTM
