### PR TITLE
Alerting: Fixed logic on how to render alert tab

### LINKED ISSUE #42998: Alerting UI visible in panel configurations when Alerting has been disabled
**What happened**:
Configurations for both classic alerting and new unified alerting have been disabled, but Alert tab persists on dashboard panel edit mode.
Screen Shot 2021-12-10 at 11 04 58 AM
Screen Shot 2021-12-10 at 11 04 20 AM

Example configuration:
```
# Legacy Grafana alerting
export GF_ALERTING_ENABLED=false
# Grafana v8 unified alerting
export GF_UNIFIED_ALERTING_ENABLED=false
```

**What you expected to happen**:
Alert tab should not be visible when all alerting configurations are disabled.

**How to reproduce it (as minimally and precisely as possible)**:
- Disable alerting for both legacy and unified alerting. 
- Create/edit a dashboard panel
- An Alert tab will be present and actionable

**Anything else we need to know?**:
This looks to have been addressed previously in https://github.com/grafana/grafana/issues/25143, but I believe that was before v8 and possibly doesn't account for Unified alerts (just guessing).

**Environment**:
- Grafana version: Grafana v8.2.5
- Data source type & version: Graphite 1.1, Prometheus 5.0.0, CloudWatch 5.0.0, etc.
- OS Grafana is installed on: Alpine 3.14.3
- User OS & Browser: MacOS 11.6.1, Firefox Developer Edition 96.0b3
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by peterholmberg**
**What this PR does / why we need it**:
Fix an issue where the alert tab in panel edit was visible even though both legacy and unified alerting was disabled.
**Which issue(s) this PR fixes**:

Fixes #42998

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx [hunk 1]
```diff
@@ -36,33 +36,40 @@ export const PanelEditorTabs: FC<PanelEditorTabsProps> = React.memo(({ panel, da
     return null;
   }
 
+  console.log(config.unifiedAlertingEnabled);
+  console.log(config.alertingEnabled);
```
Comment (ashharrison90) [inline public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx:40]: can probably remove these now 😄

**Review by ashharrison90 — APPROVED** [review]
lgtm 🙌
