### PR TITLE
Explore: Fix selection/copy of log lines

### LINKED ISSUE #17072: Explore: Selecting loki log results to copy is tricky
**What happened**:

Tried to select text across a set of lines, after releasing the mouse button the selection was shortened.

**What you expected to happen**:

The selection should keep the text selected that I selected.

**How to reproduce it (as minimally and precisely as possible)**:

0. Explore with Loki
1. Query a log stream that produces results in a parsable format, e.g., prometheus, loki itself, or a JSON stream
2. Select some text across a couple of lines
3. Release the mouse button

Notice how the selection becomes shorter.

**Anything else we need to know?**:

Likely to do with the parsing of text and the resulting row being re-rendered. Perhaps worth not parsing a row for as long text is being selected (e.g., tracking mouse down/up events).

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
This adds some logic to identify/guess if the user is possibly selecting text and if so disables parsing of log messages on hover. 

**Which issue(s) this PR fixes**:
Fixes #17072 

**Special notes for your reviewer**:
Not sure at all if this is a viable solution? 
- Would a change of `parsingEnabled` prop re-render all log rows, if so is the solution to add some logic to `componentDidUpdate`?

### CODE REVIEW

**Comment by hugohaggmark** [comment]
> Use shouldComponentUpdate() to let React know if a component’s output is not affected by the current change in state or props. The default behavior is to re-render on every state change, and in the vast majority of cases you should rely on the default behavior.

You could try to add shouldComponentUpdate to LogRow otherwise you're correct every row will rerender.

File: public/app/features/explore/LogRow.tsx [hunk 1]
```diff
@@ -89,6 +90,10 @@ export class LogRow extends PureComponent<Props, State> {
   };
 
   onMouseOverMessage = () => {
+    const { parsingEnabled } = this.props;
+    if (!parsingEnabled) {
+      return;
```
Comment (davkal) [inline public/app/features/explore/LogRow.tsx]: Have you tried exiting early here if `window.getSelection().anchorNode` is not null? If that worked, you could remove the mouse logic.

Comment (marefr) [reply public/app/features/explore/LogRow.tsx]: Interesting. I have not. Will try it out :+1:

Comment (marefr) [reply public/app/features/explore/LogRow.tsx]: @davkal Your suggestion doesn't feel as reliable, see screenshot below:
* Start with clicking on the page so nothing has focus
* Then I hover a row and I get null as anchorNode (row 1)
* Then I select text and I get multiple non-null as anchorNode (row 2 to 8)
* Then I click on a row to remove the text selection
* Then I hover log messages and I still get non-null as anchorNode (row 9 to 10)

image

Maybe looking at the [isCollapsed](https://developer.mozilla.org/en-US/docs/Web/API/Selection/isCollapsed) would be a viable solution, but not sure since the [selection object](https://developer.mozilla.org/en-US/docs/Web/API/Selection) is marked as experiemental technology.

Comment (marefr) [reply public/app/features/explore/LogRow.tsx]: Seems like using the `isCollapsed` works at least in chrome and firefox. Have pushed changes which uses selection api.

**Review by hugohaggmark — APPROVED** [review]
LGTM!
