### PR TITLE
Prometheus: Disable exemplar queries for alerting

### LINKED ISSUE #40683: Prometheus: Exemplars break alerting
**What happened**:

Recently my alerts on Grafana Cloud have regressed and firing incorrectly due to "NoData". I think this is because of the recent addition of exemplars for Prometheus for existing queries which add an extra data frame to the results, which confuses alerting.

My queries seemed to have gotten exemplars at the same time my instance got Unified Alerting, so I'm not 100% sure of the issue, but I think it's due to exemplars being turned on for existing queries.

**What you expected to happen**:

My alerts don't break!

**How to reproduce it (as minimally and precisely as possible)**:

 - In Grafana 8.1 set up an alert with prometheus + time series panel.
    - query: `up{job="destiny_stats"}`
    - alert condition: when last() of A is below 1
  - Observe that the alert works and does not have "NoData"
  - Upgrade to latest main and enable AlertsNG
  - Observe that the alert now has an additional data frame, and the alert has the state of "NoData" and no longer fires when `up` reports < 1

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.3.0-38205pre (6ec2c54c5)
- Data source type & version: Prometheus
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Windows 11, Chrome

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
We don't want to run exemplar queries for alerting. This PR removes running of queries on backend and frontend. Ob backend:
- Check if query is coming from alerting and if so, sets exemplarQuery to false
- Removes exemplar button in prom editor in unified alerting and sets exemplar to false

**Which issue(s) this PR fixes**:
Fixes: https://github.com/grafana/grafana/issues/40683

### CODE REVIEW

**Comment by gerobinson** [comment]
Looks great, could we get a test to show that the `FromAlert` header will disable exemplars when it contains `"true"`?

**Review by papagian — APPROVED** [review]
LGTM

File: public/app/plugins/datasource/prometheus/components/PromQueryEditor.tsx [hunk 1]
```diff
@@ -111,6 +112,8 @@ export class PromQueryEditor extends PureComponent<PromQueryEditorProps, State>
   render() {
     const { datasource, query, range, data } = this.props;
     const { formatOption, instant, interval, intervalFactorOption, legendFormat } = this.state;
+    //We want to hide exemplar field for unified alerting as exemplars in alerting don't make sense and are source of confusion
+    const showExemplarField = this.props.app !== CoreApp.UnifiedAlerting;
```
Comment (joshhunt) [inline public/app/plugins/datasource/prometheus/components/PromQueryEditor.tsx:116]: TIL about the `app` type.

**Review by grobinson-grafana — APPROVED** [review]

File: public/app/plugins/datasource/prometheus/components/PromQueryEditor.test.tsx [hunk 2]
```diff
@@ -36,18 +50,24 @@ const setup = (propOverrides?: object) => {
...
+  it('should render exemplar editor for dashboard', () => {
+    setup({ app: CoreApp.Dashboard });
+    expect(screen.getByTestId(testIds.editor)).toBeInTheDocument();
+    expect(screen.getByTestId(testIds.exemplar)).toBeInTheDocument();
+  });
+
+  it('should not render exemplar editor for unified alerting', () => {
+    setup({ app: CoreApp.UnifiedAlerting });
+    expect(screen.getByTestId(testIds.editor)).toBeInTheDocument();
+    expect(screen.queryByTestId(testIds.exemplar)).not.toBeInTheDocument();
```
Comment (joshhunt) [inline public/app/plugins/datasource/prometheus/components/PromQueryEditor.test.tsx:71]: For user-centric react testing library tests, ideally this would read something like `expect(screen.queryByLabelText("Exemplars")).not.toBeInTheDocument()` rather than using the [test-id escape hatch](https://testing-library.com/docs/queries/bytestid).

But that might require changes larger than this (like using a Toggle for the button instead, because that's what it is 😅 ) which is fair to be out of scope. ✌🏻

**Review by joshhunt — APPROVED** [review]
Something to think about later on, but this seems like a neat fix for this. Thanks for teaching me about the `app` prop on query editors!

File: public/app/plugins/datasource/prometheus/components/PromQueryEditor.test.tsx (hunk 2 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/prometheus/components/PromQueryEditor.test.tsx:71]: Yeah, I think that toggle would be better, and I vaguely remember that it was toggle at the beginning, but then it was change to icon button for some reasons (maybe tooltips?). But good points!
