### PR TITLE
Alerting: Display query from grafana-managed alert rules on `/api/v1/rules`

### LINKED ISSUE #45882: Unexpected `query` field value in `/api/prometheus/grafana/api/v1/rules`
**What happened**:

*This is for Prometheus alert-generator compliance, read more [here](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md). Using Grafana managed alert on a Prometheus datasource.*

To get Prometheus compliant behaviour out of Grafana Alerting, user would have a single query specified in the alerting rule like this:

Screenshot from 2022-02-25 13-32-35

The `query` field for rules in `/api/prometheus/grafana/api/v1/rules` would expect only the query that was specified in the alerting rule when there is only one condition specified. Instead it has this which is not compliant:
```
"query": "[{\"refId\":\"A\",\"queryType\":\"\",\"relativeTimeRange\":{\"from\":300,\"to\":0},\"datasourceUid\":\"0ReGYlBnk\",\"model\":{\"exemplar\":false,\"expr\":\"test_rule_1 \\u003e 0\",\"hide\":false,\"instant\":true,\"interval\":\"\",\"intervalMs\":1000,\"legendFormat\":\"\",\"maxDataPoints\":43200,\"refId\":\"A\"}}]"
```

**What you expected to happen**:

For `/api/prometheus/grafana/api/v1/rules`, when the rule has only one query, the API to only have that query in the `query` field.

For the example above, it would be `"query": "test_rule_1 > 0"`

**Anything else we need to know?**:

This is mainly for how the API outputs the data. The internals of the alerting engine might not require any changes for this.

**Environment**:
- Grafana version: 8.4.2

### PR DESCRIPTION
**Pull request by gotjosh**
Fixes https://github.com/grafana/grafana/issues/45882

On `api/v1/rules` which is one of the prometheus-compatible routes, we want to be able to visualize the query.  However, Grafana's multi-query model makes this a bit tricky.

For Prometheus compliance reasons, we must display _just_ the query. In the case of for example - most Prometheus expressions this is very valid as grafana managed alerts would only have 1 query.

My proposal as part of this pull request is that:

- ~~For single query expressions (`len(rule.Data) == 1`) attempt to extract the query and use that.~~ Doesn't work, even single query expressions have two queries.
- For multi query expressions (`len(rule.Data) > 1`) attempt to extract _all_ the queries and concatenate them using `|` for example: `"count(up) | sum by (job) (up) | vector(4)"`
- If the above fails for any reason (e.g. because the query was not stored in `expr` within the model  - because this is datasource dependant) fallback to rendering the whole of `rule.Data` as `JSON` and use that - which is the behaviour before this pull request.

TODO

- [x] check API specs
- [x] tests
- [x] documentation that might need updating

### CODE REVIEW

**Comment by codesome** [comment]
I have tested it and can confirm that it is working as expected for the use case.

PS: not sure what behaviour you would want with more than 1 expression specified in the rule, that is is not something Prometheus rules would contain so I leave that up to you.

File: pkg/services/ngalert/models/alert_query_test.go [hunk 1]
```diff
@@ -110,7 +111,7 @@ func TestAlertQuery(t *testing.T) {
 				Model: json.RawMessage(`{
 					"queryType": "metricQuery",
 					"intervalMs": "invalid",
-					"extraParam": "some text"	
+					"extraParam": "some text"
```
Comment (gotjosh) [inline pkg/services/ngalert/models/alert_query_test.go:114]: gofmt

File: pkg/services/ngalert/api/api_prometheus.go [hunk 2]
```diff
@@ -149,17 +147,10 @@ func (srv PrometheusSrv) RouteGetRuleStatuses(c *models.ReqContext) response.Res
...
-		if err != nil {
-			queryStr = err.Error()
-		} else {
-			queryStr = string(encodedQuery)
-		}
 		alertingRule := apimodels.AlertingRule{
 			State:       "inactive",
 			Name:        rule.Title,
-			Query:       queryStr,
+			Query:       ruleToQuery(srv.log, rule),
```
Comment (gotjosh) [inline pkg/services/ngalert/api/api_prometheus.go:153]: This is the _actual_ change of the PR - the rest of the lines are just tests and fixtures.

**Review by alexweav — APPROVED** [review]
LGTM - single comment was really more of a question

File: pkg/services/ngalert/api/api_prometheus.go [hunk 3]
```diff
@@ -220,3 +212,45 @@ func (srv PrometheusSrv) RouteGetRuleStatuses(c *models.ReqContext) response.Res
...
+			queryErr = err
+			break
+		}
+
+		queries = append(queries, q)
+	}
+
+	// If we were able to extract at least one query without failure use it.
+	if queryErr == nil && len(queries) > 0 {
+		return strings.Join(queries, " | ")
```
[the remark this answers is not in the document]
Comment (gotjosh) [reply pkg/services/ngalert/api/api_prometheus.go:242]: Great question! It is not, `|` is not part of of promQL syntax and would produce an error.

Screenshot 2022-03-11 at 16 21 01

**Review by yuri-tceretian — APPROVED** [review]
LGTM
