### PR TITLE
PublicDashboards: Configuration link from item list fixed

### LINKED ISSUE #74348: Bug: config button in public dashboard list not redirecting properly
When navigating to `/dashboard/public`, every item list has a configuration button that redirects the user to the dashboard, with the Share modal opened and the Public dashboard tab selected (thanks to `shareView=public-dashboard` query param).

That's not working and the modal is opened with the first tab selected, the link one.

### PR DESCRIPTION
**Pull request by juanicabanas**
**What is this feature?**

It fixes the redirect to the public dashboard configuration

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/74348

**Special notes for your reviewer:**

The bug was introduced in [this PR](https://github.com/grafana/grafana/pull/72613)

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard/components/ShareModal/SharePublicDashboard/SharePublicDashboardUtils.ts [hunk 1]
```diff
@@ -77,7 +77,7 @@ export const generatePublicDashboardUrl = (accessToken: string): string => {
 };
 
 export const generatePublicDashboardConfigUrl = (dashboardUid: string): string => {
-  return `/d/${dashboardUid}?shareView=public-dashboard`;
+  return `/d/${dashboardUid}?shareView=public_dashboard`;
```
Comment (evictorero) [inline public/app/features/dashboard/components/ShareModal/SharePublicDashboard/SharePublicDashboardUtils.ts:80]: Can we use the new enum instead of a hardcoded string to avoid this happening again?

Comment (juanicabanas) [reply public/app/features/dashboard/components/ShareModal/SharePublicDashboard/SharePublicDashboardUtils.ts:80]: yes, you're right.

**Review by evictorero — APPROVED** [review]
