### PR TITLE
Explore: Close drawer when the dashboard search modal is open

### LINKED ISSUE #47820: Explore : The inspector is not closed when navigating away from the explore view
**What happened**:

In Explore, when you open the inspector and then navigate away from it (go to dashboards for example) the inspector is still open.

Screenshot:

https://user-images.githubusercontent.com/42030685/163569475-74c4982a-283a-4936-b20b-ae27b64b7e8d.mov

**What you expected to happen**:
Close the inspector when exiting the explore view?

**How to reproduce it (as minimally and precisely as possible)**:
See screenshot

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.0.0-057ff5bcpre (`ops`)
- Data source type & version: tried with Cloudwatch data source, but I suppose it's not DS related
- User OS & Browser: mac / chrome

### PR DESCRIPTION
**Pull request by gelicia**
**What this PR does / why we need it**:
Update: After feedback on the PR, the update only changes the z-index so the dashboard search is over the explore drawer. The dashboard search's z-index is navbarFixed+1 (https://github.com/grafana/grafana/blob/main/public/app/features/search/components/DashboardSearch.tsx#L80) so setting the explore drawer to navbarFixed seems to be the right move. The navbarFixed variable only seems to be used in places that will not interfere with the explore drawer.

---

~The search dashboards screen is a full screen modal, and not a route change. Because of this, anything that happens inside explore does not get erased when the search dashboard button is pressed. This means when you have the explore drawer open for query history or inspector, and then click "Search Dashboards", the drawer still stays open over the search dashboards screen.~

~The search dashboard screen appends a query param into the url, which we can use to tell if it is open or not. We set the drawer to undefined if this query param is appended.~

**Which issue(s) this PR fixes**:
Fixes #47820

### CODE REVIEW

File: public/app/features/explore/Wrapper.tsx [hunk 1]
```diff
@@ -88,19 +88,29 @@ class WrapperUnconnected extends PureComponent<Props> {
   }
 
   render() {
-    const { left, right } = this.props.queryParams;
+    const { left, right, search } = this.props.queryParams;
```
Comment (ifrost) [inline public/app/features/explore/Wrapper.tsx:91]: This is too hacky because it relies on NavBar component behavior which may change (e.g. `search` is renamed or removed) and Explore should not depend on it.

It looks more like a problem with z-indexing of DashboadSearch vs ExploreDrawer. `DashboardSearch` has z-index of 1001 while ExploreDrawer is 1060. What is more we will not have the `DashboardSearch` once `topnav` is enabled.

**Review by ifrost — CHANGES_REQUESTED** [review]

File: public/app/features/explore/ExploreDrawer.tsx [hunk 2]
```diff
@@ -28,7 +28,7 @@ const getStyles = stylesFactory((theme: GrafanaTheme2) => {
       border-top: 1px solid ${theme.colors.border.weak};
       margin: ${theme.spacing(0, -2, 0, -2)};
       box-shadow: ${theme.shadows.z3};
-      z-index: ${theme.zIndex.sidemenu};
+      z-index: ${theme.zIndex.navbarFixed};
```
Comment (gelicia) [inline public/app/features/explore/ExploreDrawer.tsx:31]: Dashboard search is navbarFixed + 1, so this should work fine https://github.com/grafana/grafana/blob/main/public/app/features/search/components/DashboardSearch.tsx#L80

File: public/app/features/explore/Wrapper.tsx (hunk 1 above)
Comment (gelicia) [reply public/app/features/explore/Wrapper.tsx]: I realize it was a hacky solution, I thought it may be okay because topnav will make this no longer an issue, but I have changed the solution to use z-index.

**Review by ifrost — APPROVED** [review]
