### PR TITLE
Frontend Logging: Integrate grafana javascript agent

### LINKED ISSUE #50790: Integrate Grafana Javascript Agent to track frontend errors
**Why?**
We would like to be able to battle-test [grafana javascript agent](https://github.com/grafana/grafana-javascript-agent) in some Grafana Cloud Instances. In order to do that we need to integrate it and make it possible to activate / deactivate via configuration settings.

**Which transport target should we support?**
Logging the captured exceptions into the standard log stream is sufficient. Use a new logger name to make it easier to differentiate between log sources.

### PR DESCRIPTION
**Pull request by tolzhabayev**
**What this PR does / why we need it**:
Adding [Grafana Javascript Agent](https://github.com/grafana/grafana-javascript-agent) Integration to battle-test it on Hosted Grafana. The logs will be parsed by Loki on the HG side. 

**Which issue(s) this PR fixes**:

Fixes #50790

**Special notes for your reviewer**:

This is how you can enable it locally, just add following into your `conf/custom.ini`
```
[log.frontend]
enabled = true
provider = grafana
custom_endpoint = /log-grafana-javascript-agent
instrumentations_errors_enabled = true
instrumentations_console_enabled = true
instrumentations_webvitals_enabled = false
apiKey = testingCustomApiKey
```
**To test sourcemaps**:
Change your `webpack.dev.js` from ```devtool: 'inline-source-map',``` to ```devtool: 'source-map',```
do NOT commit this change.

**Outstanding ToDo's**
- [x] Figure out why exceptions are being captured twice
- [x] Add sourcemap parsing and resolution
- [x] Refactor Golang code to make responsibilities clearer and catch error cases
- [x] Write Go tests
- [x] Extend TypeScript tests
- [x] Remove test error https://github.com/grafana/grafana/pull/50801/files#diff-c6f7d4a0489af7cb40b1b9865771b395c6484dd0c68a28f8e185fb8b5c873f11R121
- [x] Add Api Key support
- Support for inline sourcemaps parsing and resolution - `won't fix` as we have ```devtool`: 'source-map'``` in our production webpack config.

### CODE REVIEW

File: public/app/features/api-keys/ApiKeysPage.tsx [hunk 1]
```diff
@@ -116,6 +116,11 @@ export class ApiKeysPageUnconnected extends PureComponent<Props, State> {
     }
   };
 
+  //@TODO Remove this, it's only for dev testing
+  produceErrorr = () => {
+    throw new Error('This is a test error');
```
Comment (tolzhabayev) [inline public/app/features/api-keys/ApiKeysPage.tsx:121]: This obviously has to go before merge, left it here to enable local testing for whoever is reviewing.

Comment (tolzhabayev) [reply public/app/features/api-keys/ApiKeysPage.tsx:121]: The failing a11y tests will be green again after we remove this

File: scripts/webpack/webpack.common.js [hunk 2]
```diff
@@ -68,6 +68,13 @@ module.exports = {
   ],
   module: {
     rules: [
+      {
```
[the remark this answers is not in the document]
Comment (domasx2) [reply scripts/webpack/webpack.common.js:71]: coming very soon (tm), update in review

File: public/app/core/services/echo/backends/grafana-javascript-agent/GrafanaJavascriptAgentBackend.ts [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+      instrumentations.push(new WebVitalsInstrumentation());
+    }
+
+    // initialize GrafanaJavascriptAgent so it can set up it's hooks and start collecting errors
+    const grafanaJavaScriptAgentOptions: BrowserConfig = {
+      app: {
+        version: options.buildInfo.version,
+        environment: options.buildInfo.env,
+      },
+      url: options.customEndpoint || '/log',
```
Comment (domasx2) [inline public/app/core/services/echo/backends/grafana-javascript-agent/GrafanaJavascriptAgentBackend.ts:47]: When adding the original sentry integration here, theer was an ask from platform team to route all events through Grafana's EchoSrv.

So what Sentry integration does and I believe Grafana js agent should do as well is configure a `EchoSrvTransport` that dispatches captured items to `EchoSrv`, then intecepts these items back from echsrv via `addEvent` and send them to backend using a sepratately instantiated `FetchTransport`. Does that make sense?

The goal is that it would be possible to get at these events by subscribing to `EchoSrv` in grafana, though I don't know that it has ever actually been useful..

**Comment by tolzhabayev** [comment]
Found why the error is being logged twice - it's because of the react's `rethrowCaughtError` [function](https://github.com/facebook/react/blob/a724a3b578dce77d427bef313102a4d0e978d9b4/packages/shared/ReactErrorUtils.js#L95-L106), so I think we can ignore it

File: public/app/core/services/echo/backends/grafana-javascript-agent/GrafanaJavascriptAgentBackend.ts (hunk 3 above)
Comment (tolzhabayev) [reply public/app/core/services/echo/backends/grafana-javascript-agent/GrafanaJavascriptAgentBackend.ts:47]: Gotcha, will look into that - I saw the Sentry Integration doing it and it was a bit confusing but I'll see if I can do it this way.

File: pkg/api/frontend_logging.go [hunk 4]
```diff
@@ -46,3 +47,35 @@ func NewFrontendLogMessageHandler(store *frontendlogging.SourceMapStore) fronten
...
+func GrafanaJavascriptAgentLogMessageHandler() frontendLogMessageHandler {
+	return func(c *models.ReqContext) response.Response {
+		event := frontendlogging.FrontendGrafanaJavascriptAgentEvent{}
+		if err := web.Bind(c.Req, &event); err != nil {
+			return response.Error(http.StatusBadRequest, "bad request data", err)
+		}
+		var ctx = frontendlogging.CtxVector{}
+		ctx = event.AddMetaToContext(ctx)
+
+		if event.Logs != nil && len(event.Logs) > 0 {
```
Comment (domasx2) [inline pkg/api/frontend_logging.go:60]: would be better to iterate over the slice rather than pick first item. on account that we start batching logs at some point :)

File: scripts/webpack/webpack.common.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (tolzhabayev) [reply scripts/webpack/webpack.common.js]: this one is resolved after upgrading to `v0.3.0`. I removed the webpack rule as not needed anymore https://github.com/grafana/grafana/pull/50801/commits/d309cd2620778b42418c5dffa1f6fe208b5ef74d

File: pkg/api/frontend_logging.go (hunk 4 above)
Comment (tolzhabayev) [reply pkg/api/frontend_logging.go:62]: good point, iterating now

File: pkg/api/frontend_logging.go [hunk 5]
```diff
@@ -46,3 +47,49 @@ func NewFrontendLogMessageHandler(store *frontendlogging.SourceMapStore) fronten
...
+			return response.Error(http.StatusBadRequest, "bad request data", err)
+		}
+		var ctx = frontendlogging.CtxVector{}
+
+		// Meta object is standard across event types, adding it globally.
+		ctx = event.AddMetaToContext(ctx)
+
+		if event.Logs != nil && len(event.Logs) > 0 {
+			for _, logEntry := range event.Logs {
+				ctx = append(ctx, "original_timestamp", logEntry.Timestamp)
```
Comment (domasx2) [inline pkg/api/frontend_logging.go:64]:
```suggestion
				ctx = append(ctx, "kind", "log", "original_timestamp", logEntry.Timestamp)
```

**Review by domasx2 — CHANGES_REQUESTED** [review]
Looks good! Some suggestions, mostly about aligning logged attributes with the agent receiver, so we can reuse the kowalski dashboards/queries

Also https://github.com/grafana/grafana/blob/main/packages/grafana-runtime/src/utils/logging.ts needs to be updated I think, to use grafana agent if it's configured

File: pkg/api/frontend_logging.go [hunk 6]
```diff
@@ -46,3 +47,49 @@ func NewFrontendLogMessageHandler(store *frontendlogging.SourceMapStore) fronten
...
+					ctx = append(ctx, "original_timestamp", measurementEntry.Timestamp)
+					grafanaJavascriptAgentLogger.Info("Measurement: "+measurementEntry.Type, ctx...)
+				}
+			}
+		}
+		if event.Exceptions != nil && len(event.Exceptions) > 0 {
+			for _, exception := range event.Exceptions {
+				exception := exception
+				transformedException := frontendlogging.TransformException(&exception, store)
+				ctx = append(ctx, "exception", transformedException.String())
```
[the remark this answers is not in the document]
Comment (tolzhabayev) [reply pkg/api/frontend_logging.go]: Changed here: https://github.com/grafana/grafana/pull/50801/commits/86ee8a87e40bd91e954f24733758f0d051947e4e

File: pkg/api/frontend_logging.go [hunk 7]
```diff
@@ -46,3 +47,49 @@ func NewFrontendLogMessageHandler(store *frontendlogging.SourceMapStore) fronten
...
+				ctx = append(ctx, "original_timestamp", exception.Timestamp)
+				grafanaJavascriptAgentLogger.Info(exception.Message(), ctx...)
```
[the remark this answers is not in the document]
Comment (tolzhabayev) [reply pkg/api/frontend_logging.go]: Changed here: https://github.com/grafana/grafana/pull/50801/commits/86ee8a87e40bd91e954f24733758f0d051947e4e

File: pkg/api/api.go [hunk 8]
```diff
@@ -620,4 +620,6 @@ func (hs *HTTPServer) registerRoutes() {
 	sourceMapStore := frontendlogging.NewSourceMapStore(hs.Cfg, hs.pluginStaticRouteResolver, frontendlogging.ReadSourceMapFromFS)
 	r.Post("/log", middleware.RateLimit(hs.Cfg.Sentry.EndpointRPS, hs.Cfg.Sentry.EndpointBurst, time.Now),
 		routing.Wrap(NewFrontendLogMessageHandler(sourceMapStore)))
+	r.Post("/log-grafana-javascript-agent", middleware.RateLimit(hs.Cfg.GrafanaJavascriptAgent.EndpointRPS, hs.Cfg.GrafanaJavascriptAgent.EndpointBurst, time.Now),
```
[the remark this answers is not in the document]
Comment (tolzhabayev) [reply pkg/api/api.go:623]: Setting it automatically now based on provider https://github.com/grafana/grafana/pull/50801/commits/08dbccb0c9990ef923d929ba965d128d79e7a17d

File: pkg/api/frontend_logging.go [hunk 9]
```diff
@@ -46,3 +47,49 @@ func NewFrontendLogMessageHandler(store *frontendlogging.SourceMapStore) fronten
...
 	}
 }
+
+func GrafanaJavascriptAgentLogMessageHandler(store *frontendlogging.SourceMapStore) frontendLogMessageHandler {
+	return func(c *models.ReqContext) response.Response {
+		event := frontendlogging.FrontendGrafanaJavascriptAgentEvent{}
+		if err := web.Bind(c.Req, &event); err != nil {
+			return response.Error(http.StatusBadRequest, "bad request data", err)
+		}
+		var ctx = frontendlogging.CtxVector{}
```
[the remark this answers is not in the document]
Comment (tolzhabayev) [reply pkg/api/frontend_logging.go]: Good catch, changed https://github.com/grafana/grafana/pull/50801/commits/0bc97ea66167c3c8262a4d3ac519e6ec1a8bf7a6

File: pkg/api/frontend_logging.go [hunk 10]
```diff
@@ -46,3 +47,49 @@ func NewFrontendLogMessageHandler(store *frontendlogging.SourceMapStore) fronten
...
+		if event.Logs != nil && len(event.Logs) > 0 {
+			for _, logEntry := range event.Logs {
+				ctx = append(ctx, "original_timestamp", logEntry.Timestamp)
+				if logEntry.LogLevel != "" {
+					ctx = append(ctx, "original_log_level", logEntry.LogLevel)
+				}
+				for k, v := range frontendlogging.KeyValToInterfaceMap(logEntry.KeyValContext()) {
+					ctx = append(ctx, k, v)
+				}
+				grafanaJavascriptAgentLogger.Info(logEntry.Message, ctx...)
```
[the remark this answers is not in the document]
Comment (tolzhabayev) [reply pkg/api/frontend_logging.go]: done https://github.com/grafana/grafana/pull/50801/commits/25d6d7ebf8ee4926cf4ddc2c2899807cb182e02f

**Comment by tolzhabayev** [comment]
@domasx2 thanks for the review, I have addressed all of the requested changes and also added it into logging.ts (even though it's used almost nowhere atm): https://github.com/grafana/grafana/pull/50801/commits/a99cae48d6c2419cfebdddb890d14b6f59c0f47c

File: pkg/setting/setting_grafana_javascript_agent.go [hunk 11]
```diff
@@ -0,0 +1,29 @@
...
+	if provider == "grafana" {
+		cfg.GrafanaJavascriptAgent = GrafanaJavascriptAgent{
+			Enabled:                             raw.Key("enabled").MustBool(true),
+			CustomEndpoint:                      raw.Key("custom_endpoint").MustString("/log-grafana-javascript-agent"),
+			EndpointRPS:                         raw.Key("log_endpoint_requests_per_second_limit").MustInt(),
+			EndpointBurst:                       raw.Key("log_endpoint_burst_limit").MustInt(),
+			ErrorInstrumentalizationEnabled:     raw.Key("instrumentations_errors_enabled").MustBool(true),
+			ConsoleInstrumentalizationEnabled:   raw.Key("instrumentations_console_enabled").MustBool(true),
+			WebVitalsInstrumentalizationEnabled: raw.Key("instrumentations_webvitals_enabled").MustBool(true),
+			ApiKey:                              raw.Key("api_key").String(),
```
Comment (papagian) [inline pkg/setting/setting_grafana_javascript_agent.go:26]: Is there an `api_key` setting defined under `log.frontend` section?

File: pkg/setting/setting_grafana_javascript_agent.go [hunk 12]
```diff
@@ -0,0 +1,29 @@
...
+
+func (cfg *Cfg) readGrafanaJavascriptAgentConfig() {
+	raw := cfg.Raw.Section("log.frontend")
+	provider := raw.Key("provider").MustString("sentry")
+	if provider == "grafana" {
+		cfg.GrafanaJavascriptAgent = GrafanaJavascriptAgent{
+			Enabled:                             raw.Key("enabled").MustBool(true),
+			CustomEndpoint:                      raw.Key("custom_endpoint").MustString("/log-grafana-javascript-agent"),
+			EndpointRPS:                         raw.Key("log_endpoint_requests_per_second_limit").MustInt(),
+			EndpointBurst:                       raw.Key("log_endpoint_burst_limit").MustInt(),
```
Comment (papagian) [inline pkg/setting/setting_grafana_javascript_agent.go:22]: Shouldn't we fallback to the default values?
```suggestion
			EndpointRPS:                         raw.Key("log_endpoint_requests_per_second_limit").MustInt(3),
			EndpointBurst:                       raw.Key("log_endpoint_burst_limit").MustInt(15),
```

File: pkg/setting/setting_sentry.go [hunk 13]
```diff
@@ -11,12 +11,15 @@ type Sentry struct {
...
+	provider := raw.Key("provider").MustString("sentry")
+	if provider == "sentry" || provider != "grafana" {
+		cfg.Sentry = Sentry{
+			Enabled:        raw.Key("enabled").MustBool(true),
+			DSN:            raw.Key("sentry_dsn").String(),
+			CustomEndpoint: raw.Key("custom_endpoint").MustString("/log"),
+			SampleRate:     raw.Key("sample_rate").MustFloat64(),
+			EndpointRPS:    raw.Key("log_endpoint_requests_per_second_limit").MustInt(),
+			EndpointBurst:  raw.Key("log_endpoint_burst_limit").MustInt(),
+		}
```
Comment (papagian) [inline pkg/setting/setting_sentry.go:23]: Same question as above: wouldn't it be better to fallback to the default values?

**Review by papagian — COMMENTED** [review]
Backend wise LGTM; I left some minor comments.
Should [the configuration docs](https://grafana.com/docs/grafana/next/setup-grafana/configure-grafana/#logfrontend) get updated with the new settings?
Also should the new endpoint get documented?
Finally, I wonder how much harder/efficient would be not to introduce the additional dependency for the ordered map.

File: pkg/setting/setting_sentry.go (hunk 13 above)
Comment (tolzhabayev) [reply pkg/setting/setting_sentry.go]: Very good catch, added https://github.com/grafana/grafana/pull/50801/commits/514c9dff0baa711644990441a78c9f99d2ba4396

File: pkg/setting/setting_grafana_javascript_agent.go (hunk 12 above)
Comment (tolzhabayev) [reply pkg/setting/setting_grafana_javascript_agent.go]: Good catch, added https://github.com/grafana/grafana/pull/50801/commits/514c9dff0baa711644990441a78c9f99d2ba4396

File: pkg/setting/setting_grafana_javascript_agent.go (hunk 11 above)
Comment (tolzhabayev) [reply pkg/setting/setting_grafana_javascript_agent.go:26]: There is now :) https://github.com/grafana/grafana/pull/50801/commits/514c9dff0baa711644990441a78c9f99d2ba4396

**Comment by tolzhabayev** [comment]
> Backend wise LGTM; I left some minor comments. Should [the configuration docs](https://grafana.com/docs/grafana/next/setup-grafana/configure-grafana/#logfrontend) get updated with the new settings? Also should the new endpoint get documented? Finally, I wonder how much harder/efficient would be not to introduce the additional dependency for the ordered map.

Thanks for the review! 

- I have added the docs update: https://github.com/grafana/grafana/pull/50801/commits/514c9dff0baa711644990441a78c9f99d2ba4396
- Not sure about the endpoint documentation, it's mostly internal usage (hosted grafana) now (the sentry one is also undocumented)
- Regarding the ordered map dependency: ideally we should be able to remove a lot of code (and direct dependency on `ordered-map`) from https://github.com/grafana/grafana/blob/2fd84e6622b3c066fedcf94ca375c9b6b2db7a8b/pkg/api/frontendlogging/grafana_javascript_agent_payload.go in favour of using this dependency https://pkg.go.dev/github.com/grafana/agent@v0.25.1/pkg/integrations/v2/agent But unfortunately there are too many dependency conflicts at the moment so that I had to duplicate some code from there.

**Review by papagian — APPROVED** [review]
LGTM

File: pkg/api/frontend_logging.go [hunk 14]
```diff
@@ -54,40 +53,63 @@ func GrafanaJavascriptAgentLogMessageHandler(store *frontendlogging.SourceMapSto
...
-					ctx = append(ctx, "original_log_level", logEntry.LogLevel)
-				}
+				ctx = append(ctx, "kind", "log", "original_timestamp", logEntry.Timestamp)
+
 				for k, v := range frontendlogging.KeyValToInterfaceMap(logEntry.KeyValContext()) {
 					ctx = append(ctx, k, v)
 				}
-				grafanaJavascriptAgentLogger.Info(logEntry.Message, ctx...)
+				switch logEntry.LogLevel {
+				case frontendlogging.LogLevelDebug:
```
Comment (domasx2) [inline pkg/api/frontend_logging.go:69]: `trace` level is missing; given that it can't be mapped directly, it should probably fall under `Debug` rather than `Info`

**Comment by domasx2** [comment]
> (even though it's used almost nowhere atm)

It's in runtime package, might be used by some plugins afaik :thinking:

**Review by domasx2 — APPROVED** [review]
Found a few more nits, but approving, great work :+1:

File: pkg/api/frontend_logging.go (hunk 14 above)
Comment (tolzhabayev) [reply pkg/api/frontend_logging.go]: https://github.com/grafana/grafana/pull/50801/commits/66f0908cbba8dc42fbe5d47f4425195ed2e6e199

File: packages/grafana-runtime/src/utils/logging.ts [hunk 15]
```diff
@@ -10,10 +14,25 @@ type Contexts = Record<string, Record<string, number | string | Record<string, s
  * @public
  */
 export function logInfo(message: string, contexts?: Contexts) {
-  captureMessage(message, {
-    level: LogLevel.Info,
-    contexts,
-  });
+  if (config.grafanaJavascriptAgent.enabled) {
+    getEchoSrv().addEvent({
```
[the remark this answers is not in the document]
Comment (tolzhabayev) [reply packages/grafana-runtime/src/utils/logging.ts]: https://github.com/grafana/grafana/pull/50801/commits/66f0908cbba8dc42fbe5d47f4425195ed2e6e199

File: pkg/api/frontend_logging.go (hunk 4 above)
Comment (tolzhabayev) [reply pkg/api/frontend_logging.go:59]: https://github.com/grafana/grafana/pull/50801/commits/ce40cfdc5e992e107e60e8453ff365b8ac8d9ea8
