### PR TITLE
fix dashboard version cleanup on large datasets

### LINKED ISSUE #11278: version cleanup fails on old databases with many entries
### What Grafana version are you using?
5.0.1
### What datasource are you using?
Aurora5.6 on r4.larges
### What OS are you running grafana on?
Amazon Linux
### What did you do?
Upgraded
### What was the expected result?
Version trim works
### What happened instead?
t=2018-03-16T15:44:34+0000 lvl=eror msg="Failed to delete expired dashboard versions" logger=cleanup error="Error 1390: Prepared statement contains too many placeholders"

 
A couple of notes:
As a user of grafana for a long time we had a pre-existing system which was not turned off when the "versioning" was enabled. This system continually updated dashboards and our versions kept increasing. The version table is 30GB so this may be an extreme case but other users may also see this bug if they have implemented the same thing.

### PR DESCRIPTION
**Pull request by alexanderzobnin**
This PR fixes #11278 
I found a bit different solution - deleting by the one query. Not sure it's a better way, so, please, review this.

### CODE REVIEW

**Comment by DanCech** [comment]
This doesn't solve the core problem of trying to delete too many rows at once, you just need to limit the number of candidates for deletion that are selected to a reasonable number (say 100) and do only that many each time the cleanup job is run.  As long as there are less than 100 new dashboard versions created per cleanup interval it will clean them up eventually without creating huge transactions that try to delete thousands of rows at once.

**Comment by alexanderzobnin** [comment]
I thought a problem is `Error 1390: Prepared statement contains too many placeholders`. It means we have a statement with too many params inside `IN(...)` clause. No?

**Comment by alexanderzobnin** [comment]
You could test it by increasing `versionsToWrite` param in tests https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/dashboard_version_test.go#L110

**Comment by alexanderzobnin** [comment]
Anyway, we can set a limit in the subquery and run in in the loop until `cmd.DeletedRows` is `0`.

**Comment by DanCech** [comment]
Don't do that either, there is absolutely no need to hammer the database deleting a huge number of rows, just let it delete a reasonable batch each time it runs and everything will be fine.

File: pkg/services/sqlstore/dashboard_version.go [hunk 1]
```diff
@@ -69,68 +70,47 @@ func GetDashboardVersions(query *m.GetDashboardVersionsQuery) error {
...
-			GROUP BY dashboard_id HAVING COUNT(dashboard_version.id) > ?
-		)`, versionsToKeep).
-			Desc("dashboard_version.dashboard_id", "dashboard_version.version").
-			Find(&versions)
-
+		// Idea of this query is finding version IDs to delete based on formula:
+		// min_version_to_keep = min_version + (versions_count - versions_to_keep)
+		// where version stats is processed for each dashboard. This guarantees that we keep at least versions_to_keep
+		// versions, but in some cases (when versions are sparse) this number may be more.
+		versionIdsToDeleteSybqueryTemplate := `SELECT id
```
Comment (DanCech) [inline pkg/services/sqlstore/dashboard_version.go]: this is misspelled

File: pkg/services/sqlstore/dashboard_version.go [hunk 2]
```diff
@@ -69,68 +70,47 @@ func GetDashboardVersions(query *m.GetDashboardVersionsQuery) error {
...
+			FROM dashboard_version, (
+				SELECT dashboard_id, count(version) as count, min(version) as min
+				FROM dashboard_version
+				GROUP BY dashboard_id
+				) AS vtd
+				WHERE dashboard_version.dashboard_id=vtd.dashboard_id
+				AND version < vtd.min + vtd.count - %v`
+
```
Comment (DanCech) [inline pkg/services/sqlstore/dashboard_version.go]: Can we use a `LIMIT` clause here rather than loading everything only to discard it?

File: pkg/services/sqlstore/dashboard_version.go [hunk 3]
```diff
@@ -69,68 +70,47 @@ func GetDashboardVersions(query *m.GetDashboardVersionsQuery) error {
...
+		versionIdsToDeleteSubquery := fmt.Sprintf(versionIdsToDeleteSybqueryTemplate, versionsToKeep)
```
Comment (DanCech) [inline pkg/services/sqlstore/dashboard_version.go]: In general this is an anti-pattern and passing parameters down to the db layer is the right way to do this, see how it was done in the old code.

**Review by DanCech — CHANGES_REQUESTED** [review]

File: pkg/services/sqlstore/dashboard_version.go (hunk 2 above)
Comment (alexanderzobnin) [reply pkg/services/sqlstore/dashboard_version.go]: I wanted to do that, but `LIMIT` is not a cross-platform syntax. MSSQL doesn't support it, for example. Using go-xorm `Limit()` is not possible, because it doesn't work with `SQL(expr)` function and I cannot split query into xorm functions.

File: pkg/services/sqlstore/dashboard_version.go [hunk 4]
```diff
@@ -69,28 +69,39 @@ func GetDashboardVersions(query *m.GetDashboardVersionsQuery) error {
...
 
-		// Keep last versionsToKeep versions and delete other
-		versionIdsToDelete := getVersionIDsToDelete(versions, versionsToKeep)
+		// Don't delete more than MAX_VERSIONS_TO_DELETE version per time
+		limit := MAX_VERSIONS_TO_DELETE
+		if len(versionIdsToDelete) < MAX_VERSIONS_TO_DELETE {
+			limit = len(versionIdsToDelete)
+		}
+		versionIdsToDelete = versionIdsToDelete[:limit]
+
```
Comment (DanCech) [inline pkg/services/sqlstore/dashboard_version.go]: Would this be clearer here?
```
if len(versionIdsToDelete) > MAX_VERSIONS_TO_DELETE {
	versionIdsToDelete = versionIdsToDelete[:MAX_VERSIONS_TO_DELETE]
}
```

**Review by DanCech — APPROVED** [review]

**Review by bergquist — APPROVED** [review]

**Comment by bergquist** [comment]
I think this is good enough. Lets avoid over-engineering :)
