### PR TITLE
Bug Fix: Only display latest version if a plugin is not installed

### LINKED ISSUE #77993: Wrong version displayed for decoupled plugin
When running a core plugin in "coupled" mode, it should display no version on its plugin page, since this one is empty on its plugin JSON. Can be seen here in the `settings` request:

Screenshot from 2023-11-10 13-43-17

It seems it's displaying the info coming from the `gnet` request instead:

Screenshot from 2023-11-10 13-43-57

### PR DESCRIPTION
**Pull request by andresmgot**
**What is this feature?**

Core plugins don't define a version when running in "core" mode. This caused the latest version published to be shown in the catalog view even if that version is not the one installed.

This PR ensures that if the plugin is installed, it will show the plugin details or nothing if that info is missing.

image

**Which issue(s) does this PR fix?**:

Fixes #77993

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by jackw — APPROVED** [review]
LGTM! 🚀

File: public/app/features/plugins/admin/hooks/usePluginInfo.tsx [hunk 1]
```diff
@@ -19,7 +19,8 @@ export const usePluginInfo = (plugin?: CatalogPlugin): PageInfoItem[] => {
 
   // Populate info
   const latestCompatibleVersion = getLatestCompatibleVersion(plugin.details?.versions);
-  const version = plugin.installedVersion || latestCompatibleVersion?.version;
+  const useLatestCompatibleInfo = !plugin.isInstalled;
+  const version = plugin.installedVersion || (useLatestCompatibleInfo && latestCompatibleVersion?.version);
```
Comment (academo) [inline public/app/features/plugins/admin/hooks/usePluginInfo.tsx:23]: Could you replace this for a ternary condition?  `(useLatestCompatibleInfo && latestCompatibleVersion?.version);`

What is the value of `version` if `useLatestCompatibleInfo` is false and `plugin.installedVersion` is falsy?

Comment (andresmgot) [reply public/app/features/plugins/admin/hooks/usePluginInfo.tsx:23]: I am not sure what you are picturing with a ternary condition but I can replace this with an `if` to make it more readable.

Comment (academo) [reply public/app/features/plugins/admin/hooks/usePluginInfo.tsx]: @andresmgot that works better! the current code makes it hard to know what are the outputs to the possible conditions.

**Review by leventebalogh — APPROVED** [review]

**Review by academo — APPROVED** [review]
