### PR TITLE
Explore: Avoid changing queries twice when importing a query in mixed mode

### LINKED ISSUE #63780: Mixed data source: New Elastic query is collapsed
**Steps to reproduce**:

1. Open Explore
2. Select Loki data source and run any query
3. Switch to Mixed data source
4. Add a new query row (it will add an empty Loki query)
5. Change added query data source to Elastic
6. Elastic query row is collapsed

**Expected result**:

Elastic query editor / row is not collapsed.

https://user-images.githubusercontent.com/745532/221433945-7ad29855-7a29-4272-9951-89b7f720af0b.mov

### PR DESCRIPTION
**Pull request by Elfo404**
**What is this feature?**

When using mixed mode in Explore, changing datasource for a query that can be imported into the selected datasource cause the query to change twice - once as a regular change and once as a result of the import process. This resulted in the result of the import being overridden by the "normal" change. in the mentioned issue, the query row is not collpased, but subsequent query changes form the DS were discarded, and given the import produced an empty query, ES query editor rendered an empty UI.

Additionally the wrong DS was used as the import source, which resulted i queries not being imported at all in mixed mode.

**Which issue(s) does this PR fix?**:

Fixes #63780

### CODE REVIEW

File: public/app/features/explore/QueryRows.tsx [hunk 1]
```diff
@@ -51,18 +51,24 @@ export const QueryRows = ({ exploreId }: Props) => {
...
   const onChange = useCallback(
     async (newQueries: DataQuery[]) => {
-      dispatch(changeQueriesAction({ queries: newQueries, exploreId }));
+      let queriesImported = false;
 
       for (const newQuery of newQueries) {
         for (const oldQuery of queries) {
           if (newQuery.refId === oldQuery.refId && newQuery.datasource?.type !== oldQuery.datasource?.type) {
-            const queryDatasource = await getDataSourceSrv().get(newQuery.datasource);
+            const queryDatasource = await getDataSourceSrv().get(oldQuery.datasource);
```
Comment (ifrost) [inline public/app/features/explore/QueryRows.tsx:59]: Nice catch! How come it works in `main`? It looks like use incorrect source data source? Or is it broken in `main`? 🤔 Could you add a test for it? Also at first sight it looks like the whole callback could be a redux action.

**Review by ifrost — APPROVED** [review]

File: public/app/features/explore/QueryRows.tsx (hunk 1 above)
Comment (Elfo404) [reply public/app/features/explore/QueryRows.tsx]: it doesn't work in main :)

the reason it seems to work is because you are probably switching between prom and loki, and because of the description above, the `expr` property is kept when switching between them. 

if you modify `public/app/plugins/datasource/prometheus/language_utils.ts` to return `'something'` on line 283, you should see that `{something}` as the result of the import. in main you won't see that happening.

as per adding tests, as mentioning during the standup i tried to implement one but there are a lot of moving parts and i was having an hard time doing it. i also just moved the logic into a dedicated thunk, which should possibly make testing (and isolating) this easier, but again there are a lot of moving bits (especially around mocking datasourceSrv and datasources with query import and export support). i will spend more time on this later

**Review by gelicia — APPROVED** [review]
Thank you for all the work on this. Adding tests was a lot but it will hopefully keep further regressions from happening.
