### PR TITLE
@grafana/toolkit: Use process.cwd() instead of PWD to get directory

### LINKED ISSUE #24582: Error running yarn dev command
**What happened**:
While trying to follow the tutorial do develop a data source plugin, after using the grafana toolkit cli, and running yarn install successfully, when I tried to run yarn dev to build the project I just created I get the following error: 
```
PS E:\Work\my-plugin> yarn dev
yarn run v1.22.4
$ grafana-toolkit plugin:dev
internal/validators.js:117
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined       
    at validateString (internal/validators.js:117:11)
    at Object.basename (path.js:671:5)
    at isLinkedMode (E:\Work\my-plugin\node_modules\@grafana\toolkit\bin\grafana-toolkit.js:13:12)     
    at entrypoint (E:\Work\my-plugin\node_modules\@grafana\toolkit\bin\grafana-toolkit.js:29:7)        
    at Object.<anonymous> (E:\Work\my-plugin\node_modules\@grafana\toolkit\bin\grafana-toolkit.js:51:9)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**What you expected to happen**:
I expected that yarn dev created a dist folder that with the plugin successfully built.

**How to reproduce it (as minimally and precisely as possible)**:
On Windows command line or Powershell run:
```
npx "@grafana/toolkit"@next plugin:create my-plugin
```
Select datasource plugin as the plugin type
```
cd my-plugin
yarn install
yarn dev
```

**Anything else we need to know?**:
Running yarn dev in git bash successfully builds the project.

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: N/A
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10, Google Chrome
- Grafana plugins: 
- Others: node v12.16.3; yarn 1.22.4

### PR DESCRIPTION
**Pull request by zoltanbedi**
**What this PR does / why we need it**:

In windows system env.PWD is not present but we can get the current dictionary with the cwd method.

**Which issue(s) this PR fixes**:

Fixes #24582 - Error running yarn dev command

### CODE REVIEW

File: packages/grafana-toolkit/bin/grafana-toolkit.js [hunk 1]
```diff
@@ -8,7 +8,7 @@ let includeInternalScripts = false;
 const isLinkedMode = () => {
   // In circleci we are in linked mode. Detect by using the circle working directory,
   // rather than the present working directory.
-  const pwd = process.env.CIRCLE_WORKING_DIRECTORY || process.env.PWD;
+  const pwd = process.env.CIRCLE_WORKING_DIRECTORY || process.cwd();
```
Comment (dprokop) [inline packages/grafana-toolkit/bin/grafana-toolkit.js:11]: Think it should be process.env.CIRCLE_WORKING_DIRECTORY || process.env.PWD || process.cwd();

**Review by dprokop — APPROVED** [review]

File: packages/grafana-toolkit/bin/grafana-toolkit.js (hunk 1 above)
Comment (zoltanbedi) [reply packages/grafana-toolkit/bin/grafana-toolkit.js]: I might argue that process.cwd will be enough, but it will not hurt, so added back PWD :)
