### PR TITLE
Loki: Fix datasource config page test run

### LINKED ISSUE #20970: Loki: Testing datasource returns no labels
Adding a loki datasource is currently not working well, since the testing of the datasource falsely reports no labels found. This happens because in the API change not only the URL, but also the response format changed, and the testing function had its own code path which was not adapted.

Broken since #20158

### PR DESCRIPTION
**Pull request by davkal**
- since the API update, the URL fallback was working, but the response
format also needed adapting: `data` (v1) vs `values` (pre-v1)
- this change looks for either data or values in the response for test
and metadata requests

Fixes #20970

### CODE REVIEW

**Comment by aknuds1** [comment]
I'll give this a spin and see if it helps.

File: public/app/plugins/datasource/loki/datasource.ts [hunk 1]
```diff
@@ -559,21 +559,24 @@ export class LokiDatasource extends DataSourceApi<LokiQuery, LokiOptions> {
           throw err;
         }),
         switchMap((response: { data: { values: string[] }; status: number }) =>
-          iif<DataQueryResponse, DataQueryResponse>(
+          iif<DataQueryResponse, any>(
```
Comment (davkal) [inline public/app/plugins/datasource/loki/datasource.ts]: Had to change this because the object was a real browser response object, as opposed to a `DataQueryResponse`.

File: public/app/plugins/datasource/loki/datasource.test.ts [hunk 2]
```diff
@@ -261,7 +261,7 @@ describe('LokiDatasource', () => {
             return Promise.resolve({
               status: 200,
               data: {
-                values: ['avalue'],
+                data: ['avalue'],
```
Comment (davkal) [inline public/app/plugins/datasource/loki/datasource.test.ts]: Adapted to new API.

**Review by aknuds1 — APPROVED** [review]
Tested and LGTM! 🎉
