### PR TITLE
Elasticsearch: omit query_string filter when no lucene query is provided

### LINKED ISSUE #35866: The performance of Elasticsearch queries generated by grafana are not optimal
**What happened**:

When using elasticsearch panels, queries with empty "lucene query" takes too long to complete. 

In the query inspector, I can see the queries generated is not optimal: 

``` json
{
  "search_type": "query_then_fetch",
  "ignore_unavailable": true,
  "index": "<index_name>"
}
{
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "@timestamp": {
              "gte": <start_time>,
              "lte": <end_time>,
              "format": "epoch_millis"
            }
          }
        },
        {
          "query_string": {
            "analyze_wildcard": true,
            "query": "*"
          }
        }
      ]
    }
  },
  "aggs": {
 // omitted
```

By running the same query in the Kibana console and profiling it, I can figure out that it is the following filter item that leads to the problem, especially there are large amount of fields in the documents in the index:

``` json
        {
          "query_string": {
            "analyze_wildcard": true,
            "query": "*"
          }
        }
```

By removing the `query_string` filter, the speed of the query can be improved significantly. Furthermore, The following patch, by removing `query_string` filters with `*` in its `query` field, can significantly increase the loading speed of the entire dashboard.

``` patch
diff --git a/public/app/plugins/datasource/elasticsearch/query_builder.ts b/public/app/plugins/datasource/elasticsearch/query_builder.ts
index 5f5eb9f842..9a2205cb2c 100644
--- a/public/app/plugins/datasource/elasticsearch/query_builder.ts
+++ b/public/app/plugins/datasource/elasticsearch/query_builder.ts
@@ -228,6 +228,10 @@ export class ElasticQueryBuilder {
       },
     };
 
+    if (queryString === '*') {
+      query.query.bool.filter.pop();
+    }
+
     this.addAdhocFilters(query, adhocFilters);
 
     // If target doesn't have bucketAggs and type is not raw_document, it is invalid query.
```

**What you expected to happen**:

There should be no `query_string` filters with `*` in its `query` field in the generated elasticsearch query.

**How to reproduce it (as minimally and precisely as possible)**:

In any elasticsearch panel, with a query whose ``Lucene Query" is empty, such pattern of generated elasticsearch query can be spotted.

**Anything else we need to know?**:

The patch above is a proof of the cause of this issue, but I guess this patch may not be adequate to get applied.

**Environment**:
- Grafana version: Grafana v8.0.0 (41f0542c1e)
- Data source type & version: Elasticsearch 7.13.2
- OS Grafana is installed on: Debian Buster
- User OS & Browser: Safari 14.1.1 on macOS Catalina 
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by Elfo404**
**What this PR does / why we need it**:
As described in https://github.com/grafana/grafana/issues/35866, the FE implementation of the query builder in ES is not optimal as it create a `query_string` filter when none is required.
This PR fixes this so that a `query_string`filter is added only when a lucene query is present, and prevents it from being added otherwise for log queries, metric queries and annotation queries. 
This is consistent with the current backend implementation.

**Which issue(s) this PR fixes**:

Fixes #35866

**Special notes for your reviewer**:

the usage of `interpolateLuceneQuery` seems a bit off, i'd like to review it further but I also want to keep the changes here scoped to this issue only.

**How to test this:**
using gdev dashboards we should be able to get the same results from this branch as we get from main.

### CODE REVIEW

File: public/app/plugins/datasource/elasticsearch/query_builder.ts [hunk 1]
```diff
@@ -213,31 +213,35 @@ export class ElasticQueryBuilder {
     }
   }
 
-  build(target: ElasticsearchQuery, adhocFilters?: any, queryString?: string) {
+  build(target: ElasticsearchQuery, adhocFilters?: any) {
```
Comment (Elfo404) [inline public/app/plugins/datasource/elasticsearch/query_builder.ts:216]: the last param is removed as it was always being set from `target`

File: public/app/plugins/datasource/elasticsearch/query_builder.ts [hunk 2]
```diff
@@ -493,7 +497,7 @@ export class ElasticQueryBuilder {
     return query;
   }
 
-  getLogsQuery(target: ElasticsearchQuery, limit: number, adhocFilters?: any, querystring?: string) {
+  getLogsQuery(target: ElasticsearchQuery, limit: number, adhocFilters?: any) {
```
Comment (Elfo404) [inline public/app/plugins/datasource/elasticsearch/query_builder.ts:500]: like for the `build` method, the last param is removed as it was always being set from `target`

File: public/app/plugins/datasource/elasticsearch/specs/query_builder.test.ts [hunk 3]
```diff
@@ -65,8 +65,7 @@ describe('ElasticQueryBuilder', () => {
             metrics: [{ type: 'avg', field: '@value', id: '1' }],
             bucketAggs: [{ type: 'date_histogram', field: '@timestamp', id: '2' }],
           },
-          100,
```
Comment (Elfo404) [inline public/app/plugins/datasource/elasticsearch/specs/query_builder.test.ts:68]: all of these changes are related to the removal of the last parameter in the `build` method

File: public/app/plugins/datasource/elasticsearch/datasource.test.ts [hunk 4]
```diff
@@ -895,7 +895,6 @@ describe('ElasticDatasource', function (this: any) {
 
     const interpolatedQuery = ds.interpolateVariablesInQueries([query], {})[0];
 
-    expect(interpolatedQuery.query).toBe('*');
```
Comment (Elfo404) [inline public/app/plugins/datasource/elasticsearch/datasource.test.ts:898]: this was removed in favor of a dedicated test in https://github.com/grafana/grafana/pull/42060/files#diff-4c45fed23a4567bef120a187afc98ade9787d19c61fdef3e9cde0382017ea024R741

**Review by ifrost — APPROVED** [review]
LGTM 👍

File: public/app/plugins/datasource/elasticsearch/specs/query_builder.test.ts [hunk 5]
```diff
@@ -751,18 +737,22 @@ describe('ElasticQueryBuilder', () => {
...
-            bool: {
-              filter: [
-                { range: { '@timestamp': { gte: '$timeFrom', lte: '$timeTo', format: 'epoch_millis' } } },
-                { query_string: { analyze_wildcard: true, query: 'foo' } },
-              ],
-            },
-          };
-          expect(query.query).toEqual(expectedQuery);
+            expect(
+              query.query.bool.filter.find((filter: any) => Object.keys(filter).includes('query_string'))
```
[the remark this answers is not in the document]
Comment (Elfo404) [reply public/app/plugins/datasource/elasticsearch/specs/query_builder.test.ts]: fixed it in 4aac8f8beb
also introduced more strict types for terms queries
