### PR TITLE
DashboardV2: Fix value mapping v1 to v2

### LINKED ISSUE #115230: SchemaV2: Field overrides and value mappings are missing
In this [dashboard](https://ops.grafana-ops.net/d/grafana-fs-versions/frontend-service-versions?orgId=1&from=now-7d&to=now&timezone=utc&var-prom_datasource=grafanacloud-prom&var-loki_datasource=grafanacloud-logs&var-slug=a000m000a&var-slug_cluster=prod-us-central-3&editPanel=10) the state timeline panel has missing overrides and value mappings that have probably been lost due to migration to dynamic dashboards.

Missing value mappings reported in [this thread](https://raintank-corp.slack.com/archives/C07QVGH37D4/p1765554040020329) ([example panel 1](https://ops.grafana-ops.net/d/ddfh1a06g9vk0b/mimir-versions?orgId=1&from=now-3h&to=now&timezone=utc&var-datasource=000000134&var-wave=$__all&var-day=$__all&var-current_version=$__all&var-cluster=$__all&refresh=1m&var-Filters=&viewPanel=panel-28), [example panel 2](https://ops.grafana-ops.net/d/bdyyfnlod1on4a/mimir-limits-operator?orgId=1&from=now-3h&to=now&timezone=utc&var-datasource=000000134&var-logs_datasource=c-R8UWvVk&var-namespace=mimir-dedicated-29&var-cluster=prod-eu-west-3&refresh=5m&viewPanel=panel-15))

### PR DESCRIPTION
**Pull request by ivanortegaalba**
Fix value mapping conversion from v1beta1 to v2alpha1

**Problem**

The backend dashboard conversion from v1beta1 to v2alpha1 was losing information:
- Regex value mappings were not being converted correctly. The \`buildRegexMap\` function expected \`options\` to be an array and looked for a \`regex\` key, but the actual v1beta1 format has \`options\` as an object with a \`pattern\` key.
- Empty \`refId\` strings in queries were not being defaulted to \"A\" to match frontend behavior.

**Solution**

- Fixed `buildRegexMap` in `v1beta1_to_v2alpha1.go` to correctly parse the `options` field as a map and extract the `pattern` key. It was using `regex` as key, but it was incorrect. We used v1 CUE to verify v1 types returned by `transformSceneToSaveModel()`.
- Added explicit check in `transformSingleQuery` to default empty `refId` strings to "A".
- Add an input test file that covers all value mapping types (value, range, regex, special), and all override matcher types (byName, byRegexp, byType, byFrameRefID, byValue).

**How to test**

1. Run backend conversion tests:
```
go test ./apps/dashboard/pkg/migration/conversion/... -v
```

2. Run frontend parity tests:
```
yarn test public/app/features/dashboard-scene/serialization/transformSaveModelV1ToV2.test.ts --no-watch
```

Fixes #115230

### CODE REVIEW

File: apps/dashboard/pkg/migration/conversion/v1beta1_to_v2alpha1.go [hunk 1]
```diff
@@ -2022,6 +2022,10 @@ func transformPanelQueries(ctx context.Context, panelMap map[string]interface{},
 
 func transformSingleQuery(ctx context.Context, targetMap map[string]interface{}, panelDatasource *dashv2alpha1.DashboardDataSourceRef, dsIndexProvider schemaversion.DataSourceIndexProvider) dashv2alpha1.DashboardPanelQueryKind {
 	refId := schemaversion.GetStringValue(targetMap, "refId", "A")
+	// Treat empty refId as missing and default to "A" to match frontend behavior
```
Comment (dprokop) [inline apps/dashboard/pkg/migration/conversion/v1beta1_to_v2alpha1.go]: pointless comment :)
```suggestion
```

File: apps/dashboard/pkg/migration/conversion/v1beta1_to_v2alpha1.go [hunk 2]
```diff
@@ -2518,22 +2522,15 @@ func buildRegexMap(mappingMap map[string]interface{}) *dashv2alpha1.DashboardReg
...
-
-	optMap, ok := opts[0].(map[string]interface{})
+	optMap, ok := mappingMap["options"].(map[string]interface{})
 	if !ok {
 		return nil
 	}
 
 	r := dashv2alpha1.DashboardV2alpha1RegexMapOptions{}
-	if pattern, ok := optMap["regex"].(string); ok {
+	if pattern, ok := optMap["pattern"].(string); ok {
```
Comment (dprokop) [inline apps/dashboard/pkg/migration/conversion/v1beta1_to_v2alpha1.go:2530]: eh, a stupid mistake :(

**Review by dprokop — APPROVED** [review]
LGTM

File: apps/dashboard/pkg/migration/conversion/v1beta1_to_v2alpha1.go (hunk 2 above)
Comment (ivanortegaalba) [reply apps/dashboard/pkg/migration/conversion/v1beta1_to_v2alpha1.go:2530]: TIL to use the old CUE schema (in the end is what we use to generate the type that is used as transformer output) 😄 

I reviewed all the rest of the overrides and mappings and all is good!

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/20232784144)
- Version: 12.4.0-20232784144
