### PR TITLE
Fix: Log close (ie flush) was done too early, before final shutdown log

### LINKED ISSUE #12438: 5.2 no longer reports errors before crashing
### What Grafana version are you using?
5.2.0 official RPM
### What datasource are you using?
None
### What OS are you running grafana on?
Latest CentOS 7 version.
### What did you do?
Made a mistake in the datasource provisioning configuration
### What was the expected result?
Errors in the logs and grafana shutting down
### What happened instead?
Grafana just shut down without any mention of an issue.

### More info
Downgrading to the 5.1.4 RPM restores the logging as I expect it to happen.

### PR DESCRIPTION
**Pull request by torkelo**
fixes #12438

### CODE REVIEW

**Review by bergquist — DISMISSED** [review]

File: pkg/cmd/grafana-server/server.go [hunk 1]
```diff
@@ -185,6 +185,8 @@ func (g *GrafanaServerImpl) Exit(reason error) {
 	}
 
 	g.log.Error("Server shutdown", "reason", reason)
+
+	log.Close()
 	os.Exit(code)
```
Comment (bergquist) [inline pkg/cmd/grafana-server/server.go]: I don't like that fact that we call `os.Exit()` outside `main.go`

**Review by bergquist — COMMENTED** [review]
I don't like that fact that we call os.Exit() outside `main.go`

I think the correct solution here is to close the logger in `main.go` after server.Exit(err)
