### PR TITLE
Tooltip: Set tooltip of active panel to front of zIndex

### LINKED ISSUE #58855: Tooltip: Active tooltip displayed behind that of other panels
**What happened**:
When you have a lot of series in a panel, the tooltips can end up overlapping. They appear to be rendered from the top of the page to the bottom, which means panels higher up the page will be beneath those lower down. 

Kapture 2022-11-16 at 10 25 41

**What you expected to happen**:

1. **most important** I expect that the tooltip for the active panel (i.e. the one the mouse is actually hovering over) to **always** be rendered on top.
2. Tooltips should be layered from top panel to bottom panel. Typically the most important panels are higher up the page, so their tooltips are also more important and should be displayed on top of those further down the screen. 
3. I would expect the tooltip to be rendered at the same x and y coordinate percentage for each panel. i.e. if the mouse cursor is near the bottom of the panel on one panel, then the tooltip should be near the bottom on other panels. Currently, this behaviour exists in the x direction, but in the y direction it is inconsistent. This would help space out the tooltips better to avoid overlapping in the first place (I know its not possible or reasonable to prevent all tooltip overlap).

**How to reproduce it (as minimally and precisely as possible)**:

1. dashboard settings --> panel options --> shared tooltip
3. edit panel --> tooltip mode --> All
4. Create multiple panels with a lot of series (5-10). 
5. Change panel sizes and window size until issue is observed. 
 
**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: Any (demo uses influxdb)
- OS Grafana is installed on: play.grafana.org
- User OS & Browser: macos/chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by sjd210**
**What is this feature?**

With multiple panels, the tooltip for the active panel (the one the mouse is hovering over) is now rendered on top of any other tooltips.

Before

https://github.com/grafana/grafana/assets/22381771/5e9bfaff-ee8f-4d46-87c3-6cc84a492bf8

After

https://github.com/grafana/grafana/assets/22381771/9573f3a6-6e5e-4aa4-86e8-f15e36e3fa72

**Why do we need this feature?**

Previously, tooltips would always render from top to bottom of page, meaning higher up panels would always have tooltips beneath those lower down. This is a particular issue for higher up panels with particularly long tooltips.

**Who is this feature for?**

Users with many series in a single panel (such that it has a long tooltip in "All" tooltip mode).

**Which issue(s) does this PR fix?**:

Fixes #58855

**Special notes for your reviewer:**

This addresses the main expected behaviour in the issue, but not supplementary points 2 and 3 (on layering from top to bottom panel, and rendering at the same x and y coordinate percentage for each panel).

<details><summary>Repro dashboard</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 2,
  "id": 512,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 7,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 3,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "multi",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "random_walk",
          "seriesCount": 15
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 7,
        "w": 24,
        "x": 0,
        "y": 7
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "multi",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "random_walk",
          "seriesCount": 5
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-12h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Overlapping tooltips",
  "uid": "WoCFPUKVk",
  "version": 6,
  "weekStart": ""
}
```
</details>

### CODE REVIEW

**Review by nmarrs — APPROVED** [review]
great work on this! tested it out locally and it works well :) 

Just a note, in the future it can be very helpful to include before / after images / videos as part of the PR description. We can also provide a repro dashboard as part of the description to make it easier for reviewers to test locally. I've updated the PR description with before / after vids and a repro dashboard as a reference - please let me know if you have any questions!

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx [hunk 1]
```diff
@@ -264,7 +264,7 @@ export const TooltipPlugin = ({
   }
 
   return (
-    <Portal>
+    <Portal zIndexOffset={isActive ? 1 : 0}>
```
Comment (nmarrs) [inline packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx:267]: I think this change may be impacting other places that we use `Portal` including on the `Dashboards` page.


https://github.com/grafana/grafana/assets/22381771/3d9aa1d1-b7fd-4714-82fc-fcb34ab48baa

We will probably want to do an audit of where we use this component and ensure that we aren't introducing regressions given the `Portal` component has a large surface area in the codebase

**Review by nmarrs — CHANGES_REQUESTED** [review]
After playing around with branch locally found a potential regression so we probably should test this PR more thoroughly to avoid introducing unintended regressions

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx (hunk 1 above)
Comment (baldm0mma) [reply packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx:267]: Good catch, @nmarrs

**Review by nmarrs — COMMENTED** [review]
removing `Request changes` status to avoid blocking this PR given upcoming time off 😬

**Review by nmarrs — DISMISSED** [review]
Looks like only way to remove the request changes is to approve haha

**Review by mdvictor — CHANGES_REQUESTED** [review]
Great job on this! I think you're on the right track here!

Good catch, @nmarrs, with that bug. It seems that the problem stems from the fact that zIndexOffset is optional and does not have a default value. Since `Portal` is used in various places across Grafana, having it `undefined` in other places will break the addition later on in `node.current.style.zIndex`. 

I see a couple possible solutions here: 
- we either set `zIndexOffset` as default 0 in `Portal` and keep this functionality. If it defaults to 0 when `undefined` then functionality should be the same as before in other places. Having this visible extra prop might be beneficial for other scenarios where a similar situation might happen where we want to change the default theme defined z-index.
- we isolate this functionality in `TooltipPlugin` by setting the portal a `className` where we specify the desired z-index and leave the `Portal` untouched.

Personally, I'm thinking a bit, but am not entirely sure, about the second option so that we leave `Portal` as is, with it's default `theme.zIndex.portal` value and if overrides are necessary for special cases (as is this `TooltipPlugin` one), they can be applied through a class. 

What do you folks think?

**Comment by leeoniya** [comment]
btw, we have some future plans to portal tooltips into the panels rather than into a global overlay to resolve some positioning glitches that happen with dashboard scrolling, and to improve performance by relying on an offset from the panel coords rather than having to manually track where the panel is in the viewport during all scroll and resize events.

**Comment by mdvictor** [comment]
Based on this information I would then start leaning more towards setting the z-index in a class that's sent to the `Portal` and leaving that component untouched. We can then refactor `TooltipPlugin` when the portals are moved in the viz dom.

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx [hunk 2]
```diff
@@ -263,8 +264,12 @@ export const TooltipPlugin = ({
     tooltip = renderTooltip(otherProps.data, focusedSeriesIdx, focusedPointIdx);
   }
 
+  const activeTooltipClass = css`
+    z-index: ${theme.zIndex.portal + 1} !important;
+  `;
+
```
Comment (leeoniya) [inline packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx:270]: you can probably avoid re-generating this static class on every tooltip movement and extract it out of this re-rendering component by using the getStyles/useStyles2 pattern. see what we're doing here:

https://github.com/grafana/grafana/pull/70872/files#diff-8b78102d87c552bbe06c1e3887b7bb6c1bf2742c92d94431433daf9e3aaa5899

**Review by leeoniya — APPROVED** [review]
small perf nit, but works as advertised, thanks! :+1:

**Review by mdvictor — APPROVED** [review]
LGTM!

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx [hunk 3]
```diff
@@ -312,3 +316,9 @@ export function positionTooltip(u: uPlot, bbox: DOMRect) {
 
   return { x, y };
 }
+
+const getStyles = (theme: GrafanaTheme2) => ({
+  tooltipWrapper: css`
+    z-index: ${theme.zIndex.portal + 1} !important;
```
Comment (baldm0mma) [inline packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx:322]: Is `!important` needed here? IIFC best practices around using the `!important` declaration is that it should generally be avoided as much as possible, since it can lead to specificity and maintenance issues in our stylesheets.

Comment (mdvictor) [reply packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx:322]: Yes, there already is a zIndex prop set on the inline style of the wrapper element itself. We need to overwrite it for tooltips since that wrapper is used across grafana and only the tooltip one needs the modification. Using `important` is generally frowned upon but I think it works for this scenario especially since tooltips will be refactors to not be global but panel based rather soon as @leeoniya mentioned earlier
