### PR TITLE
TableNG: Fix column width override

### LINKED ISSUE #99085: TableNG: Column width override adjustment
The global minimum table column width is currently set to 50. However, column width overrides allow reducing it to as low as 20. We need to implement this capability to ensure feature parity for table column width adjustments.

UPD. Looks like we don't need to go lower than 50, in the current table 50 is a minimum value, even if we go lower, it doesn't affect column width.

### PR DESCRIPTION
**Pull request by Develer**
**What is this feature?**

This PR fixes column width override.

**Which issue(s) does this PR fix?**:

Fixes #99085 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/TableNG/utils.ts [hunk 1]
```diff
@@ -187,14 +187,35 @@ export function shouldTextOverflow(
...
+
+  const overrideWidth = override?.value ?? (override ? 'auto' : undefined);
 
   return overrideWidth ?? field.config?.custom?.width ?? fieldConfig?.defaults?.custom?.width ?? 'auto';
 }
 
+export function getColumnMinWidth(field: Field, fieldConfig: TableNGProps['fieldConfig'], key: string): number {
+  // The 'minWidth' is applied only when:
+  // - The field's 'width' is overridden or set to 'auto' by default.
+  // Otherwise, the current or overridden 'width' is used.
```
Comment (drew08t) [inline packages/grafana-ui/src/components/Table/TableNG/utils.ts:203]: Great summary!

**Review by drew08t — APPROVED** [review]
This works as expected for width override, but let's make sure to update the `packages/grafana-ui/src/components/Table/TableNG/utils.test.ts` to cover this (it is also failing currently).

**Review by adela-almasan — APPROVED** [review]

File: public/app/features/search/page/components/SearchResultsTable.test.tsx [hunk 2]
```diff
@@ -150,7 +150,7 @@ describe('SearchResultsTable', () => {
           width={1000}
         />
       );
-      const noData = await screen.findByText('No data');
+      const noData = await screen.findByText('No values');
```
Comment (drew08t) [inline public/app/features/search/page/components/SearchResultsTable.test.tsx:153]: Forgot to mention this earlier, but why are we updating this?

Comment (Develer) [reply public/app/features/search/page/components/SearchResultsTable.test.tsx:153]: There was i18n error in tests
