### PR TITLE
Logs: Added copy-to-clipboard fallback support and visual feedback after copying

### LINKED ISSUE #67819: Logs: row message copy button does not work
### 
# What went wrong?

**What happened**:

  - clicking the copy button does not copy the text and throws console error "Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')"

**What did you expect to happen**:

  - clicking the copy button in logs row should copy the text

### 
# How do we reproduce it?

image

**Step 1**:

- Click copy button button on logs row tooltip button

**Step 2**:

- Try to paste the text - it seems like it's not copied to clipboard properly.

### 
# What Grafana version are you using?

9.5.1

### Grafana Platform?

Docker

### User's OS?

OSX

### User's Browser?

Chromium

### Is this a Regression?

None

### Are Datasources involved?

Loki

### Anything else to add?

It seems like there is already a proper copy button component which has fallback for http and older browsers that don't support `window.navigator.clipboard` - `ClipboardButton` in `@grafana/ui`.
I would suggest using it in `LogRowMessage` component, like so:

`LogRowMessage.tsx:7`
```
import { IconButton, Tooltip, ClipboardButton } from '@grafana/ui';
```

`LogRowMessage.tsx:105`
```
              <ClipboardButton 
                title="Copy value to clipboard"
                fill="text"
                icon="copy"
                variant="secondary"
                size="md"
                getText={() => restructuredEntry}
              />
```

### PR DESCRIPTION
**Pull request by matyax**
This PR changes the copy log button to use the `ClipboardButton` component, which has a fallback for old navigators or Grafana instances being loaded via HTTP, which disables the clipboard API.

imagen

As a byproduct of this change, the user now gets a visual confirmation when the log row has been copied.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/67819

**Special notes for your reviewer:**

The underlying functionality should remain unchanged.

### CODE REVIEW

File: public/app/features/logs/components/LogRowMessage.tsx [hunk 1]
```diff
@@ -94,16 +104,23 @@ export class LogRowMessage extends PureComponent<Props> {
...
             )}
-            <Tooltip placement="top" content={'Copy'}>
-              <IconButton size="md" name="copy" onClick={() => navigator.clipboard.writeText(restructuredEntry)} />
-            </Tooltip>
+            <ClipboardButton
+              className={styles.copyLogButton}
+              icon="copy"
+              variant="secondary"
+              fill="text"
+              size="sm"
```
Comment (ivanahuckova) [inline public/app/features/logs/components/LogRowMessage.tsx:119]:
```suggestion
              size="md"
```

To keep the size of `showContext` and `Copy` the same

File: public/app/features/logs/components/LogRowMessage.tsx [hunk 2]
```diff
@@ -94,16 +104,23 @@ export class LogRowMessage extends PureComponent<Props> {
...
+              getText={this.getLogText}
```
Comment (ivanahuckova) [inline public/app/features/logs/components/LogRowMessage.tsx:120]: As we already have `restructuredEntry` we can just do `() => restructuredEntry`, so we don't have to restructure it again.

**Review by ivanahuckova — COMMENTED** [review]
This is great change! I love that you used CopyButton instead of duplicating logic. Left couple of comments bellow.

File: public/app/features/logs/components/LogRowMessage.tsx (hunk 2 above)
Comment (matyax) [reply public/app/features/logs/components/LogRowMessage.tsx:120]: Since it's the log row message component, I did this change as a small performance improvement, to prevent creating new arrow functions which cause unnecessary re-renders. Both `onLogRowClick` and `getLogText` would be created once per log line only once.
In any case, it's a simple change so I don't mind reverting it.

Comment (ivanahuckova) [reply public/app/features/logs/components/LogRowMessage.tsx:120]: 👍

**Review by ivanahuckova — APPROVED** [review]
LGTM
