### PR TITLE
Influxdb: Fix issues with request creation and parsing

### LINKED ISSUE #21741: Influxdb: Querying throws error and measurement picker does not load
**What happened**:

Screenshot 2020-01-25 at 14 37 15
Screenshot 2020-01-25 at 14 37 53

**What you expected to happen**:
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: master
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by aocenas**
Closes: https://github.com/grafana/grafana/issues/21741

### CODE REVIEW

File: public/app/core/services/backend_srv.ts [hunk 1]
```diff
@@ -461,25 +461,9 @@ export class BackendSrv implements BackendService {
     return options;
   };
 
-  private parseUrlFromOptions = (options: BackendSrvRequest): string => {
```
Comment (aocenas) [inline public/app/core/services/backend_srv.ts]: Moved outside of the class as they do not need to be methods here.

File: public/app/core/services/backend_srv.ts [hunk 2]
```diff
@@ -525,3 +509,19 @@ coreModule.factory('backendSrv', () => backendSrv);
...
+};
+
+export const parseInitFromOptions = (options: BackendSrvRequest): RequestInit => ({
+  method: options.method,
+  headers: {
+    'Content-Type': 'application/json',
+    Accept: 'application/json, text/plain, */*',
+    ...options.headers,
+  },
+  body: options.data ? (typeof options.data === 'string' ? options.data : JSON.stringify(options.data)) : undefined,
```
Comment (aocenas) [inline public/app/core/services/backend_srv.ts]: Checks data first, so that null is not serialized as `null`. Probably ok for 0, false or empty string too.

File: public/app/core/specs/backend_srv.test.ts [hunk 3]
```diff
@@ -135,41 +124,6 @@ describe('backendSrv', () => {
     );
   });
 
-  describe('parseUrlFromOptions', () => {
```
Comment (aocenas) [inline public/app/core/specs/backend_srv.test.ts]: Just moved outside.

File: public/app/plugins/datasource/influxdb/datasource.ts [hunk 4]
```diff
@@ -204,7 +204,9 @@ export default class InfluxDatasource extends DataSourceApi<InfluxQuery, InfluxO
   metricFindQuery(query: string, options?: any) {
     const interpolated = this.templateSrv.replace(query, null, 'regex');
 
-    return this._seriesQuery(interpolated, options).then(() => this.responseParser.parse(query));
+    return this._seriesQuery(interpolated, options).then(resp => {
+      return this.responseParser.parse(query, resp);
```
Comment (aocenas) [inline public/app/plugins/datasource/influxdb/datasource.ts]: `resp` was not passed to the parse function.

File: public/app/plugins/datasource/influxdb/datasource.ts [hunk 5]
```diff
@@ -337,6 +339,8 @@ export default class InfluxDatasource extends DataSourceApi<InfluxQuery, InfluxO
                 config: err.config,
               };
             }
+          } else {
+            throw err;
```
Comment (aocenas) [inline public/app/plugins/datasource/influxdb/datasource.ts]: Throw error if it is not from influx.

**Review by Estrax — APPROVED** [review]
LGTM

**Review by kaydelaney — APPROVED** [review]
