### PR TITLE
Gauge: Improve font size auto sizing

### LINKED ISSUE #28759: Gauge panel values scaled wrongly
**What happened**:
After update from 7.2.2 to 7.3.1, the gauge panel values are being scaled incorrectly. Longer values are too small and shorter values are too big.
This is how it looks on 7.3.1:

**What you expected to happen**:
This is how it looked on 7.2.2:

**How to reproduce it (as minimally and precisely as possible)**:
Create gauge panel with long and short value

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.1
- Data source type & version: Influxdb 1.8.2
- OS Grafana is installed on: Debian 4.9
- User OS & Browser: Windows 10 Opera Gx
- Grafana plugins: -
- Others: -

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #28759

### CODE REVIEW

File: packages/grafana-ui/src/components/Gauge/Gauge.tsx [hunk 1]
```diff
@@ -112,7 +103,17 @@ export class Gauge extends PureComponent<Props> {
...
     const thresholdMarkersWidth = gaugeWidth / 5;
     const text = formattedValueToString(value);
-    const fontSize = calculateFontSize(text, dimension - gaugeWidth * 3, dimension, 1, 48);
+    // This not 100% accurate as I am unsure of flot's calculations here
+    const valueWidthBase = Math.min(width, dimension * 1.3) * 0.9;
+    const fontSize = calculateFontSize(
+      text,
+      // remove gauge & marker width (on left and right side)
+      // and 10px is some padding that flot adds to the outer canvas
+      valueWidthBase - ((gaugeWidth + (showThresholdMarkers ? thresholdMarkersWidth : 0)) * 2 + 10),
```
Comment (mckn) [inline packages/grafana-ui/src/components/Gauge/Gauge.tsx:112]: nit: I would have moved this to its own variable just to make it a bit more readable.

**Review by mckn — APPROVED** [review]
LGTM - works as expected!

**Review by mckn — APPROVED** [review]
LGTM!
