### PR TITLE
Alerting: Attempt to preserve UID from migrated legacy channel

### LINKED ISSUE #57638: Alerting: Migration should attempt to preserve contact point UIDs
**What happened**:

The legacy version of contact points, `notifications`, has a UID field which works pretty much exactly the same as the UID in UA's contact point objects.

When migrating a contact point from legacy to unified, we don't preserve that UID at all - we just re-roll a new one. As a courtesy for users who are creating notifications via an external system, we could just re-use the existing UID. This helps them see what got migrated and correlate objects easier. It also doesn't introduce consistency issues - contact points are 1:1 with legacy notifications, and the notifications table is not used at all by UA.

**What you expected to happen**:

I expected the migrated contact points to have the same UID as the original.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create legacy contact points.
2. Write down their UIDs.
3. Migrate.
4. Same contact points exists in UA, but the UIDs are all different.

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by alexweav**
**What is this feature?**

This PR makes migrated contact points re-use the same UID from the notification channel that it came from.

We only attempt to re-use the UID. If there is a conflict or if the original channel had an empty UID for some reason, we log it and roll a new one.

**Why do we need this feature?**

Contact points are migrated from legacy Notification Channels on a 1:1 basis. However, we don't preserve UIDs between them, making it difficult for users to correlate the result of the migration. It'd be nice to preserve the value, especially for users who have external systems provisioning the notifiers.

**Who is this feature for?**

Users who are provisioning legacy notifications. This helps them update their tooling with less headache.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/57638

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/sqlstore/migrations/ualert/channel.go [hunk 1]
```diff
@@ -177,9 +177,22 @@ func (m *migration) getNotificationChannelMap() (channelsPerOrg, defaultChannels
 
 // Create a notifier (PostableGrafanaReceiver) from a legacy notification channel
 func (m *migration) createNotifier(c *notificationChannel) (*PostableGrafanaReceiver, error) {
-	uid, err := m.generateChannelUID()
-	if err != nil {
-		return nil, err
+	uid := c.Uid
+	if uid == "" {
```
Comment (gotjosh) [inline pkg/services/sqlstore/migrations/ualert/channel.go:181]: sorry if this is a dumb question, but under which circumstances would this happen? We always generate new contact points based on existing ones IIRC, so there's no need for the code below.

**Review by gotjosh — COMMENTED** [review]
LGTM on the nature of the change but please see my question.

File: pkg/services/sqlstore/migrations/ualert/channel.go (hunk 1 above)
Comment (JacobsonMT) [reply pkg/services/sqlstore/migrations/ualert/channel.go:181]: This idea of checking to make sure the uid isn't empty and potentially using the ID as a backup has been around since the [original migration code](https://github.com/grafana/grafana/commit/e52f718a87f9f26813bfe45cd30d823e7a1d42f7#diff-3d6f33c060b6bf9fcfcb6c64e52c81198f5793d5ee389dd81395633cd8ea50f8R54-R59) and as far as I know the reason has been lost to to time.

I kept it around "just in case" when I refactored the migration code a while back. IMO it makes some sense to also make sure we're not copying an empty uid here if we still have this [code elsewhere](https://github.com/grafana/grafana/blob/0db339d82f905a7f4c0db11717bcb22b7fd9f111/pkg/services/sqlstore/migrations/ualert/channel.go#L231-L237).

Comment (alexweav) [reply pkg/services/sqlstore/migrations/ualert/channel.go:181]: Thanks, @JacobsonMT! Indeed, it was mostly just to guard against weird edge cases. I actually didn't know we had similar checks elsewhere, that's a great point. Sure enough, it seems like empty string UIDs are a very valid concern.

I also have no idea how strict Legacy alerting's object validation is. A lot of resources in Grafana let you control the UID, and we've seen more than one case where empty string was allowed, usually unintentionally. Maybe a handful of users out there have an empty string as a UID already? Now, we'll ensure that all the UIDs make sense.

**Comment by callmehyde** [comment]
👋 Hi y'all - I just wanted to double check, is this still on track to be part of `9.2.3`?

**Comment by alexweav** [comment]
@callmehyde Still waiting on an approval from @grafana/alerting-squad-backend. It's not urgent enough to hold a release on, though. If it misses and ends up being part of 9.2.4, it's not a big deal.

**Review by gotjosh — APPROVED** [review]
LGTM

File: pkg/services/sqlstore/migrations/ualert/channel.go (hunk 1 above)
Comment (gotjosh) [reply pkg/services/sqlstore/migrations/ualert/channel.go:181]: Makes sense, thanks for the answers!
