### PR TITLE
Dashboards: Small improvements to the Switch Variable UI

### LINKED ISSUE #115081: Dashboards: Switch variable sidebar layout
### What happened?

When a switch variable is edited in the sidebar, the layout is a bit broken, and certain headers are duplicated.

Image

### What did you expect to happen?

To have a clean and responsive layout, that adopts the sidebar.

### Did this work before?

No.

### How do we reproduce it?

1. Go to a dashboard that has the new layouts enabled
2. Enter edit mode
3. Click on "Add variable"
4. Select the Switch variable type

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by mckn**
**What is this feature?**

I have made a couple small adjustments to the Switch Variable UI. 
The following things has been fixed:

Before this PR:
Screenshot 2025-12-17 at 15 51 50

After this PR:
Screenshot 2025-12-19 at 16 22 47

Before this PR:
Screenshot 2025-12-17 at 15 52 30

After this PR:
Screenshot 2025-12-19 at 16 23 09

**Why do we need this feature?**

To make the UI look more consistent and aligned.

**Who is this feature for?**

Grafana dashboard users

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/115081

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard-scene/settings/variables/components/SwitchVariableForm.tsx [hunk 1]
```diff
@@ -87,11 +89,15 @@ export function SwitchVariableForm({
     }
   };
 
+  const fieldWidth = inline ? undefined : 30;
```
Comment (mckn) [inline public/app/features/dashboard-scene/settings/variables/components/SwitchVariableForm.tsx:92]: I did this instead of adding the `width` to the stack since that caused the field labels to line break too early compared to other variable editor forms.

**Review by dprokop — APPROVED** [review]

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/21133944505)
- Version: 12.4.0-21133944505
