### PR TITLE
Alerting: Fix recording rules being shown in the rules table on edit group modal

### LINKED ISSUE #62057: Cannot update evaluation interval on recording rules
Recording rules do not have the `for` value, hence they should not be validated against that property
image

### PR DESCRIPTION
**Pull request by soniaAguilarPeiron**
**What is this feature?**

This PR fix recording rules being shown in the alert table on editing group modal. Fixes users not being able to edit interval for recording rules.

Recording rules don't have `For` value, and for this reason they should not appear in the alert table on the group modal and they should not have any validation when editing the value regarding this inexistent `For` value.

But, if a recording rule shares the same group as other non recording rules, then this table should should show these alerts (only the non recording alert rules) in the table and interval should be validated taking in account the `For` values used in this alerts that are in the same group.

**Why do we need this feature?**

Users need to be able to update the interval for a recording rule.

**Who is this feature for?**

All users.

**Which issue(s) does this PR fix?**:

Fixes #62057

**Special notes for your reviewer**:

https://user-images.githubusercontent.com/33540275/214834058-afb4d9d3-aa88-4b15-b6e8-4f735bd6e35d.mp4

### CODE REVIEW

File: public/app/features/alerting/unified/mocks.ts [hunk 1]
```diff
@@ -438,6 +451,37 @@ export const someRulerRules: RulerRulesConfigDTO = {
   namespace2: [mockRulerRuleGroup({ name: 'group3', rules: [mockRulerAlertingRule({ alert: 'alert3' })] })],
 };
 
+export const someCloudRulerRules: RulerRulesConfigDTO = {
```
Comment (konrad147) [inline public/app/features/alerting/unified/mocks.ts:454]: nit: These two methods seem to be highly coupled to the `EditRuleGroupModal` test. I'd keep them in the test file

File: public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx [hunk 2]
```diff
@@ -328,6 +318,11 @@ export function EditCloudGroupModal(props: ModalProps): React.ReactElement {
   const rulerRuleRequests = useUnifiedAlertingSelector((state) => state.rulerRules);
   const groupfoldersForSource = rulerRuleRequests[sourceName];
 
+  const groupWithRules = getGroupFromRuler(groupfoldersForSource?.result, groupName, nameSpaceName);
+  const rulesWithoutRecordingRules: RulerRuleDTO[] =
+    groupWithRules?.rules.filter((rule: RulerRuleDTO) => !isRecordingRulerRule(rule)) ?? [];
+  const hasSomeNoRecordingRules = rulesWithoutRecordingRules.length > 0;
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx:324]: nit: `hasSomeRecordingRules` -> `hasAlertingRules`

File: public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx [hunk 3]
```diff
@@ -328,6 +318,11 @@ export function EditCloudGroupModal(props: ModalProps): React.ReactElement {
   const rulerRuleRequests = useUnifiedAlertingSelector((state) => state.rulerRules);
   const groupfoldersForSource = rulerRuleRequests[sourceName];
 
+  const groupWithRules = getGroupFromRuler(groupfoldersForSource?.result, groupName, nameSpaceName);
+  const rulesWithoutRecordingRules: RulerRuleDTO[] =
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx:322]: Could we reverse the names a bit? Maybe instead of saying `withoutRecording` we could use `alertingRules`? 
`const alertingRules` and then instead of `!isRecordingRulerRule` we could check `isAlertingRulerRule`

File: public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx [hunk 4]
```diff
@@ -122,24 +122,14 @@ export const safeParseDurationstr = (duration: string): number => {
...
   const styles = useStyles2(getStyles);
-  const group = getGroupFromRuler(rulerRules, groupName, folderName);
-  const rules: RulerRuleDTO[] = group?.rules ?? [];
 
   const { watch } = useFormContext<FormValues>();
   const currentInterval = watch('groupInterval');
   const unknownCurrentInterval = !Boolean(currentInterval);
 
-  const rows: AlertsWithForTableProps[] = rules
+  const rows: AlertsWithForTableProps[] = rulesWithoutRecordingRules
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx:132]: nit: how about `rulesWithourRecordingRules` -> `alertingRules`?

**Review by konrad147 — APPROVED** [review]
LGTM! I left a few non-blocking nits

File: public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx (hunk 2 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx:324]: you mean `hasSomeNoRecordingRules` -> `hasAlertingRules `, right?

File: public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx (hunk 3 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx:322]: it makes sense, I was confused with this `AlertingRules` name.

File: public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx (hunk 4 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rules/EditRuleGroupModal.tsx:132]: actually, we cannot do this change. 
`non-recording-rules !== alerting rules` , because they can be `alerting rules` and `grafana rules`
