### PR TITLE
Alerting: Allow configuration of non-ready alertmanagers

### LINKED ISSUE #40901: Alerting: unable to change contact point when Alertmanager is not ready
**What happened**:
When internal Alertmanager fails to start due to invalid configuration, Grafana does not let it change the configuration because Alertmanager is not ready. On UI side this affects pages "Contact Points", "Notification Policies", "Admin" as they use the same API and model. The user is not able to change anything on these pages.

**What you expected to happen**:
Grafana should let users change configuration no matter what's the state of Alertmanager is. 

**How to reproduce it (as minimally and precisely as possible)**:
- Disable feature flag `ngalert`
- Create a notification channel that will not be accepted by Alertmanager (for example Slack https://github.com/grafana/grafana/issues/40709)
- Change the feature flag and restart Grafana
- Go to "Contact Points", remove or fix the bad configuration. Click the Save button. The request will fail with the message "Alertmanager is not ready".
 

**Environment**:
- Grafana version: 8.3.0-e117b80
- Data source type & version: MySql 
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by alexweav**
**What this PR does / why we need it**:

Currently, if a user has invalid alertmanager config (such as a bad notifier or other invalid setting), new configs cannot be applied. This is because alertmanager config changes currently require the existing alertmanager to be ready, which won't be the case if the config is invalid.

This results in a nasty cycle where a user cannot fix their issue without interacting directly with the database. If they try to correct the invalid config using the UI, the request to apply the new config is rejected because the old config is invalid.

Repro steps:
1. Set invalid alertmanager config. I did this by directly editing the config in the database.
  a. There are several ways a config can be invalid, in my testing I made an email contact point with a missing `addresses` field. Other options include invalid JSON or [bad notifier config](https://github.com/grafana/grafana/issues/40901) (the Slack plugin still rejects whitespace recipients!
2. Launch Grafana
3. Attempt to correct the bad config in the UI
4. When saving the new config, the request is rejected.

**Which issue(s) this PR fixes**:

Fixes #40901 

**Special notes for your reviewer**:

I originally wrote an integration test for this, but it was unstable because the alertmanager tracking logic has in-memory state. The test would not behave as expected when the database and in-memory state were out of sync. So, I went for unit tests instead.

### CODE REVIEW

File: pkg/services/ngalert/api/api.go [hunk 1]
```diff
@@ -49,6 +50,27 @@ type Alertmanager interface {
 	TestReceivers(ctx context.Context, c apimodels.TestReceiversConfigBodyParams) (*notifier.TestReceiversResult, error)
 }
 
+type MultiOrgAlertmanager interface {
```
Comment (alexweav) [inline pkg/services/ngalert/api/api.go:53]: The API layer logic previously depended directly on the concrete `Alertmanager` and `MultiOrgAlertmanager` classes. I refactored this to depend on an abstraction of functionality instead. This decouples the code, makes the API handlers unit-testable, and provides slightly better demarcation between the layers.

File: pkg/services/ngalert/api/api.go [hunk 2]
```diff
@@ -49,6 +50,27 @@ type Alertmanager interface {
...
+	AlertmanagerFor(orgID int64) (Alertmanager, error)
+}
+
+type AlertmanagerProvider struct {
```
Comment (alexweav) [inline pkg/services/ngalert/api/api.go:57]: This was necessary because `notifier.MultiOrgAlertmanager.AlertmanagerFor` returned a concrete `notifier.Alertmanager` which made it no longer conform to the interface above. This is because Go forces signatures to match exactly when applying interfaces. It's essentially this problem: https://stackoverflow.com/questions/34190170/go-interface-method-returning-interface-doesnt-match-method-returning-concrete

I worked around this by introducing this type, which adapts the concrete class's signature `AlertmanagerFor(orgID int64) (notifier.Alertmanager, error)` to return the interface instead, `AlertmanagerFor(orgID int64 (Alertmanager, error)`. Please let me know if there is a better way to do this.

Also [this](https://github.com/grafana/grafana/blob/6ae8f23f326193b907e7d4116447ecdfd5a8eef0/pkg/services/ngalert/api/api_alertmanager.go#L513) function already exists which does something similar. Another possibility would be to move `AlertmanagerProvider` to that file, use that as the adapter method instead.

File: pkg/services/ngalert/api/api_alertmanager_test.go [hunk 3]
```diff
@@ -138,3 +140,107 @@ func TestStatusForTestReceivers(t *testing.T) {
...
+			},
+		}
+		request := apimodels.PostableUserConfig{}
+
+		response := sut.RoutePostAlertingConfig(&rc, request)
+
+		require.Equal(t, 202, response.Status())
+	})
+
+	t.Run("assert 202 when alertmanager to configure is not ready", func(t *testing.T) {
```
Comment (alexweav) [inline pkg/services/ngalert/api/api_alertmanager_test.go:191]: This is the test that actually exercises the bug in question. The others were auxiliary, and helped me build out the test infrastructure.

File: pkg/services/ngalert/api/testing.go [hunk 4]
```diff
@@ -0,0 +1,109 @@
...
+
+func (f FakeSecretService) Encrypt(ctx context.Context, payload []byte, opt secrets.EncryptionOptions) ([]byte, error) {
+	return payload, nil
+}
+
+func (f FakeSecretService) Decrypt(ctx context.Context, payload []byte) ([]byte, error) {
+	return payload, nil
+}
+
+type FakeAlertmanager struct{}
```
Comment (alexweav) [inline pkg/services/ngalert/api/testing.go:70]: This one was a large interface. Mocks rather than handwritten fakes would have simplified this file a lot. I stayed with handwritten fakes for consistency, all the existing code uses fakes, but it seems like mocks would be preferable as we add more unit tests.

File: pkg/services/ngalert/api/api.go (hunk 2 above)
Comment (JohnnyQQQQ) [reply pkg/services/ngalert/api/api.go:57]: I think I would opt-in for the second option, reusing the existing function.

**Review by JohnnyQQQQ — COMMENTED** [review]
Nice work 👍 

Is there a way we can test that `AlertmanagerFor` in the multi-org-alertmanager will return a non-nil alertmanager if we are in a state that is unready? I think this should be tested as otherwise, we could end up with the same behavior again.

File: pkg/services/ngalert/api/testing.go [hunk 5]
```diff
@@ -0,0 +1,109 @@
...
+}
+
+func (f FakeAlertingStore) GetLatestAlertmanagerConfiguration(query *models.GetLatestAlertmanagerConfigurationQuery) error {
+	if _, ok := f.orgsWithConfig[query.OrgID]; ok {
+		return nil
+	}
+	return store.ErrNoAlertmanagerConfiguration
+}
+
+type FakeSecretService struct{}
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/api/testing.go:60]: This is not necessary. https://github.com/grafana/grafana/blob/e81d434edff6a7a44a1ad9ad5d74be37429fe0ec/pkg/services/secrets/fakes/fake_service.go

File: pkg/services/ngalert/api/api.go (hunk 2 above)
Comment (yuri-tceretian) [reply pkg/services/ngalert/api/api.go:57]: I do not think I like adding more entities just for the sake of working around some language limitations. Perhaps we can figure out a better way, like a return interface instead of a concrete type. @gotjosh wdyt?

**Review by yuri-tceretian — COMMENTED** [review]
Although I think that the direction with interfaces is the right one, the workaround does not seem to be a good choice. I would suggest moving the refactoring part to another PR.

File: pkg/services/ngalert/api/testing.go (hunk 5 above)
Comment (alexweav) [reply pkg/services/ngalert/api/testing.go:60]: Thanks, this is perfect.

File: pkg/services/ngalert/api/api.go (hunk 2 above)
Comment (alexweav) [reply pkg/services/ngalert/api/api.go:57]: @yuri-tceretian We could do this by pushing the interface down into the `notifier` package rather than keeping all the interfaces in the `api` package. This type can disappear entirely if `MultiOrgAlertmanager.AlertmanagerFor` returned an interface directly.

This was an approach I considered at first I avoided it originally because it felt more idiomatic in Go to keep the interface bound to the consuming layer. But, perhaps I followed this to a fault here - it definitely seems simpler to go with what you suggested.

File: pkg/services/ngalert/notifier/multiorg_alertmanager.go [hunk 6]
```diff
@@ -311,7 +311,7 @@ func (moa *MultiOrgAlertmanager) AlertmanagerFor(orgID int64) (*Alertmanager, er
 	}
 
 	if !orgAM.Ready() {
-		return nil, ErrAlertmanagerNotReady
+		return orgAM, ErrAlertmanagerNotReady
```
Comment (alexweav) [inline pkg/services/ngalert/notifier/multiorg_alertmanager.go:314]: @JohnnyQQQQ Pointing out the area where we're adding multiple error behaviors. Since `AlertmanagerFor` is used in many places, we discussed adding a separate method (say, `GetAlertmanager`) which doesn't check for readiness, and having `AlertmanagerFor` call our new method.

After experimenting with this, I ran into a couple issues of concern:

- `AlertmanagerFor` performs locking. If we push the lock acquisition and map access into our new method, we introduce an insidious potential bug where the AM readiness check no longer happens within the lock. Instead, it happens after the lock is released, allowing concurrent requests to interfere with state.
- To ensure both entry points are properly locked, we'd need them both to call a third private method which performs the lookup without any at all. Then, both entry points would independently handle their own locking. I didn't feel great about introducing a non-thread-safe private method, as it's easy for future developers to call this method without realizing it, introducing more concurrency problems.

The second error state here is not ideal, but IMO it is a "lesser of two evils." I really like the idea of having a single thread-safe lookup method so that callers don't have to think about which lookup method they're calling and whether it's safe or not.

Do you have any thoughts on this? I'm still happy to change this if we disagree with the reasoning above.

**Comment by yuri-tceretian** [comment]
I was thinking a little bit more. What do you think about changing the way it works and let MultiOrgAM handle that rather than pulling AM and updating it directly?

File: pkg/services/ngalert/api/api.go (hunk 2 above)
Comment (alexweav) [reply pkg/services/ngalert/api/api.go]: I ended up re-using the test infra in `notifier/multiorg_alertmanager_test.go` which let me re-use existing fakes for the persistence layer. This let me use a concrete alertmanager in the test, working around this problem.

IMO, this results in a less isolated/reproducible unit test, since it hits lots of unrelated functionality. But, as @JohnnyQQQQ mentioned offline, we'll be refactoring this early next year anyway.

File: pkg/services/ngalert/api/testing.go (hunk 4 above)
Comment (alexweav) [reply pkg/services/ngalert/api/testing.go]: Not needed anymore.

**Comment by alexweav** [comment]
By expanding the scope of the test, I got the tests working properly by faking at the store level rather than the AM<->API level. As @JohnnyQQQQ mentioned we'll be refactoring this area soon anyways, so this ended up being a bit less invasive and could re-use existing infra.

File: pkg/services/ngalert/api/api.go [hunk 7]
```diff
@@ -49,6 +50,10 @@ type Alertmanager interface {
 	TestReceivers(ctx context.Context, c apimodels.TestReceiversConfigBodyParams) (*notifier.TestReceiversResult, error)
 }
 
+type AlertingStore interface {
```
Comment (alexweav) [inline pkg/services/ngalert/api/api.go:53]: Note: All the other interfaces are now gone. This one remains though - we can't do without this one because the API layer talks directly to the store layer. This one is a bit less problematic though, and is consistent with how the MultiOrgAlertmanager tests already work by faking the store.

**Review by yuri-tceretian — APPROVED** [review]
LGTM
