### PR TITLE
Prometheus: Browser resource caching

### LINKED ISSUE #60420: Prometheus: Cache resource calls in browser
**What**:
This provides the option to set more aggressive prometheus editor cache settings to improve editor UX and to reduce the number of queries sent to the datasource.

Right now we're providing a cache for select API calls in the prometheus editor, which will prevent some API calls from being made if they were within the same minute of a prior query. This proposal is to externalize that cache from the react application and instead leverage the native browser cache via the Cache Control HTTP header.

What does this look like in Grafana?
I'm proposing that we add an additional setting to the prometheus [JSON data](https://grafana.com/docs/grafana/latest/administration/provisioning/#json-data), which by default would provide the current settings (cache queries for 1 minute).

We should provide at least 3 settings, low (current), medium, high.

Low caching mode:
* Cache matching queries within 1 minute
* Debounce user event driven network requests for 300ms

Medium cacheing mode:
* Cache matching queries within 10 minutes
* Debounce user event driven network requests for 600ms

Hard cacheing mode:
* Cache queries for up to an hour
* Debounce user event driven network requests for 1200ms

**Why**:

Editor UX can be poor for high cardinality instances, for some instances it can take minutes to get the entire list of metric names, which means waiting minutes every time you open a promql editor. While this PR doesn't help with the initial request, it should allow users to hang onto those initial requests longer, meaning fewer waits for the backend, and spend more writing/debugging.

If people want more fine grained control over these settings, please reach out, I'm just adding a dropdown for now so we don't add a bunch more complexity to the configuration UI. 

**How**:
* New JSON data select field.
* Default value will be "low" which will provide the current settings so as to prevent regression.
* New functionality will be feature flagged

**Anything else we need to know?**:
This will not impact prometheus queries, only editor API calls like /labels, and /metadata etc.

### PR DESCRIPTION
**Pull request by gtk-grafana**
**What is this feature?**
* Adding time range snapping and enabling client cache for resource API calls via "Cache-Control" HTTP header.
* Deprecating react LRU cache in favor of native browser cache. 
* Feature flag should allow users to revert back to LRU cache implementation in case of unexpected regression.

In order to prevent the number of API calls made, I'm proposing that we cache the editor API resource calls in the browser. 

In order to cache editor API calls, we need the client to return non-unique parameters each request. Currently we are already range snapping to the closest minute in our LRU cache storage, this is just providing the option for users to configure higher snapping values, and expose this snapping in the request (which could potentially open up server caching), instead of handling the snapping within in the react application.

This should only impact the following endpoints:
* `/api/v1/label/${name}/values`
* `/api/v1/series`
* `/api/v1/labels`
* `/api/v1/metadata` 

Metadata doesn't contain any time parameters, so it gets special caching rules. Also this call can be **hefty**, so we wanted to give users the option to cache it for an extended duration (1 day, 7 days, or 30 days).
All other endpoints cache for 1m, 10m, and 1h for low, medium, and high data source config values respectively.

The "None" option will prevent any range snapping or cache headers, except for metadata which still gets cached for 1 day.

Debounce intervals for interactive resource calls (e.g. autocomplete) are also impacted by this input, 350ms, 600ms, 1200 ms for Low, Medium, and High respecitvely. None gets the same value as low: 350ms.

**UI changes**
New Prometheus configuration dropdown field.
image
The potential values are: Low, Medium, High, and None.
The value of this new field is stored in the `cacheLevel` in the Prometheus `DataSourceJsonData`.

**Why do we need this feature?**
Provide better performance when writing queries in prometheus
Reduce number of queries to prometheus backend
Expose caching mechanism in frontend
Expose ability for data sources to define own Cache-Control headers

**Caveats**
Most browsers don't cache POST requests, so if you're configured to use POST, you might not be able to cache all the 
resource queries. But some resource api calls only support GET (like metadata), so there is still benefit.

**How to use**
Controlled by `prometheusResourceBrowserCache` feature flag. Add to feature toggles section in custom.ini
```
[feature_toggles]
enable = prometheusResourceBrowserCache
```

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/grafana/issues/60420

**Special notes for your reviewer**:
Design doc: https://docs.google.com/document/d/19RnKIDbR-WZ_0AUvT4txrcAFg-OORujGr8g6q6L5-V4

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/language_provider.ts [hunk 1]
```diff
@@ -109,6 +110,10 @@ export default class PromQlLanguageProvider extends LanguageProvider {
     this.timeRange = { start: 0, end: 0 };
     this.metrics = [];
 
+    this.keysCache = new LRU<string, string[]>({ max: this.datasource.getCacheLength() });
+    this.labelsCache = new LRU<string, Record<string, string[]>>({ max: this.datasource.getCacheLength() });
+    this.labelValuesCache = new LRU<string, string[]>({ max: this.datasource.getCacheLength() });
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/language_provider.ts:115]: There is also a maxSize which limits the total "length" of all of the values stored, but this incurs some additional work in calculating the length of everything in the cache instead of just throwing it in there.

Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/language_provider.ts:115]: I opted not to use it for now, and just set relatively small number of elements to store in this LRU data structure.

File: public/app/plugins/datasource/prometheus/language_provider.ts [hunk 2]
```diff
@@ -525,17 +560,17 @@ export default class PromQlLanguageProvider extends LanguageProvider {
...
     const interpolatedName = name ? this.datasource.interpolateString(name) : null;
-    const range = this.datasource.getTimeRangeParams();
+    const range = this.datasource.getQuantizedTimeRangeParams();
     const urlParams = {
       ...range,
       ...(match && { 'match[]': match }),
     };
 
     const cacheParams = new URLSearchParams({
-      'match[]': interpolatedName ?? '',
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/language_provider.ts:535]: so I think the current values are not correct, we're not cacheing on the match string so this could potentially be  a bug on main

File: public/app/plugins/datasource/prometheus/language_provider.ts [hunk 3]
```diff
@@ -140,11 +145,11 @@ export default class PromQlLanguageProvider extends LanguageProvider {
...
 
     // TODO #33976: make those requests parallel
-    await this.fetchLabels();
+    // await this.fetchLabels();
     this.metrics = (await this.fetchLabelValues('__name__')) || [];
-    await this.loadMetricsMetadata();
+    // await this.loadMetricsMetadata();
     this.histogramMetrics = processHistogramMetrics(this.metrics).sort();
-    return [];
+    return Promise.all([this.loadMetricsMetadata(), this.fetchLabels()]);
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/language_provider.ts:152]: This seems so obvious but I'm sure I'll regret this later

File: public/app/plugins/datasource/prometheus/configuration/PromSettings.tsx [hunk 4]
```diff
@@ -304,6 +312,24 @@ export const PromSettings = (props: Props) => {
             />
           </div>
         </div>
+        <div className="gf-form-inline">
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/configuration/PromSettings.tsx:315]: this is still very rough

**Comment by gtk-grafana** [comment]
After thinking about this further, I think the LRU cache in the react application is unhelpful, and we should remove it entirely to replace with setting expiry headers on the backend and let the browser manage cacheing requests. We'll still need the quantized time-intervals to sync with the cache durations so we're generating non-unique timestamps, so I still think we'll need some level of data source cache configuration so the client app and backend can set similar durations?

**Comment by gtk-grafana** [comment]
Also I want to state explicitly that quantizing the time intervals beyond a minute will potentially allow users to craft queries that do not return results for the current time interval selected in the UI. This will be most obvious when the time interval is shorter than the cache duration, and for users who are adding metrics, or have metrics that do not omit during the same intervals (maybe prometheus went down or something).

This is acceptable in some environments, and not others, and users could perceive this behavior as a bug. For this reason, I would suggest that by default the cache duration should not be longer than 1 minute, and we provide documentation about any side-effects of cacheing longer then 1 minute.

File: public/app/plugins/datasource/prometheus/configuration/PromSettings.tsx (hunk 4 above)
Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/configuration/PromSettings.tsx:346]: Once this gets out of the proof of concept stage I'll review the proposed UI changes with UX

File: public/app/plugins/datasource/prometheus/datasource.tsx [hunk 5]
```diff
@@ -1171,6 +1180,76 @@ export class PrometheusDatasource
...
+      return { start: startTimeQuantizedSeconds.toString(), end: endTimePlusOneStep.toString() };
+    }
+
+    const start = startTimeQuantizedSeconds.toString();
+    const end = endTimeQuantizedSeconds.toString();
+
+    return { start, end };
+  }
+
+  /**
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/datasource.tsx:1212]: Delete this commented out code please

File: public/app/plugins/datasource/prometheus/language_provider.ts [hunk 6]
```diff
@@ -139,17 +138,25 @@ export default class PromQlLanguageProvider extends LanguageProvider {
...
     this.metricsMetadata = fixSummariesMetadata(
-      await this.request('/api/v1/metadata', {}, {}, { showErrorAlert: false })
+      await this.request(
+        '/api/v1/metadata',
+        {},
+        {},
+        {
+          showErrorAlert: false,
+          headers: {
+            'Cache-Control': `private, max-age=${this.datasource.getDaysToCacheMetadata() * 86400}`,
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/language_provider.ts:155]: helper function please

**Review by gtk-grafana — COMMENTED** [review]
Please add unit tests for `calculateQuantizedTimeRange` specifically

**Review by gtk-grafana — COMMENTED** [review]
Also pull out as much cache code out of the datasource as you can

File: public/app/plugins/datasource/prometheus/types.ts [hunk 7]
```diff
@@ -34,6 +35,7 @@ export interface PromOptions extends DataSourceJsonData {
   exemplarTraceIdDestinations?: ExemplarTraceIdDestination[];
   prometheusType?: PromApplication;
   prometheusVersion?: string;
+  cacheLevel?: PrometheusCacheLevel;
```
Comment (itsmylife) [inline public/app/plugins/datasource/prometheus/types.ts:38]: Can we make this required? Or better I must ask is there a reason behind we make this `optional`?

File: public/app/plugins/datasource/prometheus/datasource.tsx [hunk 8]
```diff
@@ -72,6 +75,13 @@ const GET_AND_POST_METADATA_ENDPOINTS = ['api/v1/query', 'api/v1/query_range', '
 
 export const InstantQueryRefIdIndex = '-Instant';
 
+export enum PrometheusCacheLevel {
+  low = 'low',
+  medium = 'medium',
+  high = 'high',
+  none = 'none',
+}
+
```
[the remark this answers is not in the document]
Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/datasource.tsx]: Good catch, fixed!

File: public/app/plugins/datasource/prometheus/language_provider.ts [hunk 9]
```diff
@@ -43,6 +41,15 @@ const setFunctionKind = (suggestion: CompletionItem): CompletionItem => {
   return suggestion;
 };
 
+const buildCacheHeaders = (durationInSeconds: number) => {
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/language_provider.ts:44]: move to language_utils

File: public/app/plugins/datasource/prometheus/language_provider.ts [hunk 10]
```diff
@@ -153,17 +159,25 @@ export default class PromQlLanguageProvider extends LanguageProvider {
...
     this.metrics = (await this.fetchLabelValues('__name__')) || [];
-    await this.loadMetricsMetadata();
     this.histogramMetrics = processHistogramMetrics(this.metrics).sort();
-    return [];
+    return Promise.all([this.loadMetricsMetadata(), this.fetchLabels()]);
   };
 
   async loadMetricsMetadata() {
+    const headers = config.featureToggles.prometheusResourceBrowserCache
+      ? buildCacheHeaders(this.datasource.getDaysToCacheMetadata() * 86400)
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/language_provider.ts:169]: Remove numeric const

File: public/app/plugins/datasource/prometheus/language_provider.ts [hunk 11]
```diff
@@ -153,17 +161,25 @@ export default class PromQlLanguageProvider extends LanguageProvider {
       return [];
     }
 
-    // TODO #33976: make those requests parallel
-    await this.fetchLabels();
     this.metrics = (await this.fetchLabelValues('__name__')) || [];
-    await this.loadMetricsMetadata();
     this.histogramMetrics = processHistogramMetrics(this.metrics).sort();
-    return [];
+    return Promise.all([this.loadMetricsMetadata(), this.fetchLabels()]);
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/language_provider.ts:166]: Add unit test, check when rejected

File: public/app/plugins/datasource/prometheus/language_provider.ts [hunk 12]
```diff
@@ -153,17 +161,25 @@ export default class PromQlLanguageProvider extends LanguageProvider {
...
   };
 
   async loadMetricsMetadata() {
+    const headers = config.featureToggles.prometheusResourceBrowserCache
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/language_provider.ts:170]: Add comment for each usage of `prometheusResourceBrowserCache` flag

File: docs/sources/administration/provisioning/index.md [hunk 13]
```diff
@@ -218,6 +218,7 @@ Common settings in the [built-in core data sources]({{< relref "../../datasource
...
 | prometheusType             | string  | Prometheus                                                       | The type of the Prometheus data sources. such as `Prometheus`, `Cortex`, `Thanos`, `Mimir`                                                                                                                                                                                                                          |
+| cacheLevel                 | string  | Prometheus                                                       | The setting that determines how aggressive the browser cache is, valid values are: `Low`, `Medium`, `High`, or `None`. This field is only configurable when the prometheusResourceBrowserCache feature flag is enabled.                                                                                             |
```
Comment (chri2547) [inline docs/sources/administration/provisioning/index.md:221]:
```suggestion
| cacheLevel                 | string  | Prometheus                                                       | This determines how aggressive the browser cache is. Valid values include: `Low`, `Medium`, `High`, and `None`. This field is configurable when you enable the `prometheusResourceBrowserCache` feature flag.                                                                                             |
```

Comment (chri2547) [inline docs/sources/administration/provisioning/index.md:221]: What do you mean by 'aggressive'?

**Review by chri2547 — COMMENTED** [review]
A suggestion and a question. Thank you. Please ping me for a re-review.

File: docs/sources/administration/provisioning/index.md (hunk 13 above)
Comment (gtk-grafana) [reply docs/sources/administration/provisioning/index.md]: I removed the word "aggressive", basically this feature does a host of cache related things, including increasing debounce intervals, setting the cache duration for metadata, and setting the cache duration for other resource calls.

Comment (gtk-grafana) [reply docs/sources/administration/provisioning/index.md]: Should we document what each of the settings do? Aka a setting of Low will give a debounce interval of 350ms, cache metadata for 1 day, and cache all other resource calls made within the same minute. Medium will me 600ms debounce, metadata for 1 week, and all resource queries made within 10 minutes...

Comment (gtk-grafana) [reply docs/sources/administration/provisioning/index.md]: The only concern I have with adding that is that the code will change and folks won't change the docs, should we link to the code? Or is that too low level and we want some additional high level description?

Comment (chri2547) [reply docs/sources/administration/provisioning/index.md]: I'm unfamiliar with linking the docs to the code. Do you mean auto-populating the docs based on the code? And looking into this further, we want to update the product docs to account for this change given its importance. Will this be the default experience at some point? I'm not sure exactly which topic to update, perhaps this one? https://grafana.com/docs/grafana/v9.4/datasources/prometheus/query-editor/

I do feel like we should describe the benefits and promote its use. Thoughts?

Comment (gtk-grafana) [reply docs/sources/administration/provisioning/index.md]: This will potentially be the default experience in the future, but for now we're launching behind a feature flag so we can get this out to a few customers to help test this, so maybe we can worry about the more public announcement documentation (it's also been suggested that we write a blog post about this) when we're ready to remove this feature flag and make this the default behavior?

Comment (chri2547) [reply docs/sources/administration/provisioning/index.md]: That works for me, thank you!

**Review by chri2547 — APPROVED** [review]
LGTM! Thanks for the contribution!

File: pkg/tsdb/prometheus/resource/resource.go [hunk 14]
```diff
@@ -29,10 +29,12 @@ func New(
 		return nil, err
 	}
 	httpMethod, _ := maputil.GetStringOptional(jsonData, "httpMethod")
+	cacheLevel, _ := maputil.GetStringOptional(jsonData, "cacheLevel")
 
 	return &Resource{
 		log:        plog,
 		promClient: client.NewClient(httpClient, httpMethod, settings.URL),
+		cacheLevel: cacheLevel,
```
Comment (itsmylife) [inline pkg/tsdb/prometheus/resource/resource.go:37]: Why do we need `cacheLevel` here? It seems we don't use it.

File: public/app/plugins/datasource/prometheus/language_utils.ts [hunk 15]
```diff
@@ -344,3 +360,59 @@ export function extractLabelMatchers(tokens: Array<string | Token>): AbstractLab
...
+ */
+export function getRangeSnapInterval(
+  cacheLevel: PrometheusCacheLevel,
+  range: TimeRange
+): { start: string; end: string } {
+  // Don't round the range if we're not caching
+  if (cacheLevel === PrometheusCacheLevel.None) {
+    return {
+      start: getPrometheusTime(range.from, false).toString(),
+      end: getPrometheusTime(range.to, true).toString(),
```
Comment (itsmylife) [inline public/app/plugins/datasource/prometheus/language_utils.ts:377]: Is rounding up intentional here?

File: public/app/plugins/datasource/prometheus/querybuilder/components/MetricEncyclopediaModal.tsx [hunk 16]
```diff
@@ -327,7 +327,7 @@ export const MetricEncyclopediaModal = (props: Props) => {
         setMetrics(metrics);
         setFilteredMetricCount(metrics.length);
         setIsLoading(false);
-      }, 300),
+      }, datasource.getDebounceTimeInMilliseconds() ?? 350),
```
Comment (itsmylife) [inline public/app/plugins/datasource/prometheus/querybuilder/components/MetricEncyclopediaModal.tsx:330]: It looks like getDebounceTimeInMilliseconds is returning 350 by default. Do we need `??` here?

File: public/app/plugins/datasource/prometheus/datasource.tsx [hunk 17]
```diff
@@ -1239,6 +1260,32 @@ export class PrometheusDatasource
   interpolateString(string: string) {
     return this.templateSrv.replace(string, undefined, this.interpolateQueryExpr);
   }
+
+  getDebounceTimeInMilliseconds(): number {
```
Comment (itsmylife) [inline public/app/plugins/datasource/prometheus/datasource.tsx:1264]: This might accept an optional parameter named `fallback`. If that is present it returns it in `default` case, otherwise, it returns 350. WDYT?

File: public/app/plugins/datasource/prometheus/language_provider.ts [hunk 18]
```diff
@@ -153,17 +172,26 @@ export default class PromQlLanguageProvider extends LanguageProvider {
       return [];
     }
 
-    // TODO #33976: make those requests parallel
-    await this.fetchLabels();
     this.metrics = (await this.fetchLabelValues('__name__')) || [];
-    await this.loadMetricsMetadata();
     this.histogramMetrics = processHistogramMetrics(this.metrics).sort();
-    return [];
+    return Promise.all([this.loadMetricsMetadata(), this.fetchLabels()]);
```
Comment (itsmylife) [inline public/app/plugins/datasource/prometheus/language_provider.ts:177]: I cannot see any direct reason to return an array here. Maybe I am missing something. Do we really return something here? Can't the return type be just `Promise<void>`>?

**Review by itsmylife — APPROVED** [review]
🚀 LGTM
I just put some nitpicks. Great job!

File: public/app/plugins/datasource/prometheus/language_utils.ts (hunk 15 above)
Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/language_utils.ts:377]: Yup, should be the same behavior as current

File: public/app/plugins/datasource/prometheus/querybuilder/components/MetricEncyclopediaModal.tsx (hunk 16 above)
Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/querybuilder/components/MetricEncyclopediaModal.tsx:330]: DOUBLE TAP. Yeah I'll fix

File: pkg/tsdb/prometheus/resource/resource.go (hunk 14 above)
Comment (gtk-grafana) [reply pkg/tsdb/prometheus/resource/resource.go:37]: Sorry about that, this was my initial implementation and I guess I forgot to remove it all

File: public/app/plugins/datasource/prometheus/language_provider.ts (hunk 18 above)
Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/language_provider.ts:177]: I'm not sure if I understand? the `start` function in the parent `LanguageProvider` class defines start as a function that returns a promise of array of promises

File: public/app/plugins/datasource/prometheus/datasource.tsx (hunk 17 above)
Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/datasource.tsx:1264]: I'm not sure that's necessary, I just removed all the null coalesce that would never get called anyway because this function will always return 350 by default if no cache rules are set.

File: public/app/plugins/datasource/prometheus/language_provider.ts (hunk 18 above)
Comment (itsmylife) [reply public/app/plugins/datasource/prometheus/language_provider.ts:177]: Yes, you are right.

Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/language_provider.ts:177]: This should get us a performance improvement on its own also because we won't be waiting for the labels response to make the metadata request. For high cardinality/slow prometheus instances this should make the initial render a teensy bit faster, and then every subsequent load these should be cached for a bit too (at least metadata).
