### PR TITLE
Accessibility: Ensure dashboard edit panel inputs have accessible labels

### LINKED ISSUE #106227: WCAG Name, Role, Value - Ensure Panel Options form element has a label
**Steps to reproduce**:
"[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier."

1. Create a new dashboard
2. Add a panel
3. click Edit Panel to pop out the Panel Options side-bar
4. Run the Accessibility Insights for Web tool with the FastPass option
5. Notice the accessibility issues automatically identified by the tool.

**Actual Result**:
Image

**Expected Result**

No failures from Accessibility Insights for Web FastPass test run

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html

**Environment**:
- Grafana version: 12.0.2
- Data source type & version: n/a
- User OS & Browser:
    Chromium Edge: Version 137.0.3269.1 (Official build) dev (64-bit)
    Edition Windows 11 Pro
    Version 24H2
    OS build 26100.3476
- Others:

### PR DESCRIPTION
**Pull request by samsch**
**What is this feature?**

Make sure all input have accessible labels in panel editors

Covered in this PR: When creating a new dashboard panel or editing an existing one, the visible sidebar elements for every visualization type do not have any missing accessible label errors shown by [the Accessibility Insights browser extension](https://accessibilityinsights.io/), and spot checked inputs also function correctly.

Areas not covered that still need fixed
- [`public/app/plugins/panel/timeseries/LineStyleEditor.tsx`](https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/timeseries/LineStyleEditor.tsx#L95) and [`public/app/features/dimensions/editors/ScalarDimensionEditor.tsx`](https://github.com/grafana/grafana/blob/main/public/app/features/dimensions/editors/ScalarDimensionEditor.tsx#L108-L113) have `Select` components which don't have accessible labels. https://github.com/grafana/grafana/issues/109757
- [Add link](https://github.com/grafana/grafana/issues/109755) and [Add action](https://github.com/grafana/grafana/issues/109756) modals each have some inputs which still need correct labeling
- Radio button groups aren't correctly linked to their label

**Why do we need this feature?**

To be accessible to our users (WCAG A level)

**Who is this feature for?**

All users

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/106227

**Special notes for your reviewer:**

Reviewing will be easiest commit by commit, as changes are grouped with other like changes

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by ashharrison90** [comment]
@samsch have pushed a couple of commits to fix the unit/e2e tests 👍 

i think it would be good to list out in the PR description what input types are fixed and what's still left to do. once we've got that written down, we could probably just deliver this and tackle the others in followup PRs

File: public/app/features/dashboard-scene/conditional-rendering/ConditionalRenderingEditor.tsx [hunk 1]
```diff
@@ -1,3 +1,5 @@
+import { v4 as uuidv4 } from 'uuid';
```
Comment (joshhunt) [inline public/app/features/dashboard-scene/conditional-rendering/ConditionalRenderingEditor.tsx:1]: using uuid like this felt a bit.... off to me, but im not sure why. 

I went digging to see if we could use something better... but did not find anything

https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/utils/src/useId.ts#L13

Comment (samsch) [reply public/app/features/dashboard-scene/conditional-rendering/ConditionalRenderingEditor.tsx:1]: The other reasonable option is nanoid with a custom alphabet, but there's not going to be a lot of difference

File: public/app/features/dashboard/components/PanelEditor/getPanelFrameOptions.tsx [hunk 2]
```diff
@@ -102,12 +107,12 @@ export function getPanelFrameCategory(props: OptionPaneRenderProps): OptionsPane
     .addCategory(
       new OptionsPaneCategoryDescriptor({
         title: t('dashboard.get-panel-frame-category.title.panel-links', 'Panel links'),
-        id: 'Panel links',
```
Comment (samsch) [inline public/app/features/dashboard/components/PanelEditor/getPanelFrameOptions.tsx]: Mistaken change, reverting

File: public/app/plugins/panel/geomap/editor/StyleEditor.tsx [hunk 3]
```diff
@@ -50,6 +50,22 @@ export interface StyleEditorOptions {
...
+   */
+  return function getId(name: string) {
+    if (used.has(name)) {
+      throw new Error(`"${name}" has already been used!`);
+    }
+    used.add(name);
+    return `${name}${base}`;
+  };
+}
+
```
Comment (ashharrison90) [inline public/app/plugins/panel/geomap/editor/StyleEditor.tsx]: i... don't understand this bit. what am i missing? 😅 

can we not just use `useId` a bunch of times? e.g. 
```tsx
const resourceDimensionId = useId();
const scalarDimensionId = useId();
const colorPickerId = useId();
const sliderValueId = useId();
...etc
```

**Review by ashharrison90 — APPROVED** [review]
lgtm 🙌 

one question about the custom id function

i've also noted that radio button groups aren't correctly linked to their label as well. i think we should merge this, and tackle the other problems in separate PRs 👍

File: public/app/plugins/panel/geomap/editor/StyleEditor.tsx (hunk 3 above)
Comment (samsch) [reply public/app/plugins/panel/geomap/editor/StyleEditor.tsx]: no reason we can't, and that it drew confusion is a good enough reason to change it to that!

main reason for the abstraction is safety handling around dynamic IDs, but this isn't a case where that's actually needed, i just wanted to.
