### PR TITLE
LoginAttempts: Reset attempts on successfull password reset

### LINKED ISSUE #30161: Reset Password Functionality does not reset "Too many Attempts" Flag
Hi,

On Login Grafana 7.3.6 may well refuse login because of too many login attempts, instead of wrong password,  unlike many other systems which clearly specify what account was temporary locked.

Even worse, following reset-admin-password process as described here:

https://grafana.com/docs/grafana/latest/administration/cli/

while resets password, does NOT seems to clean the banned flag,  at least login attempt is NOT possible even with new password one needs to reset for recovery.

Jan 09 12:50:31 ivanworkbox grafana-server[14670]: t=2021-01-09T12:50:31+0000 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Too many consecutive incorrect login attempts for user. Login for user temporarily blocked" remote_addr=99.69.XX.XX

This is very poor usability because  first  user may think they forgot the password, where the problem is someone else abuses their account with login attempt and second  even changing password fails.

### PR DESCRIPTION
**Pull request by kalleep**
**What is this feature?**
When trying to sign in into grafana there is not a clear message on what went wrong, we always display "Invalid username or password".  Login attempts are recorded for every unsuccessful login and have a 5 minute window.

If the user gets blocked by to many login attempts it is not clear what is going wrong and could trigger users to reset their password

When resetting the password we should also reset the login attempts for that user so they can authenticate after a successful reset

**Which issue(s) does this PR fix?**:

Fixes #30161

**Special notes for your reviewer**:
* Simplify the DeleteOldLoginAttempts query

### CODE REVIEW

File: pkg/services/loginattempt/loginattemptimpl/store.go [hunk 1]
```diff
@@ -41,26 +41,7 @@ func (xs *xormStore) CreateLoginAttempt(ctx context.Context, cmd CreateLoginAtte
...
-		maxId = toInt64(result[0]["id"])
-
-		if maxId == 0 {
-			return nil
-		}
-
-		sql = "DELETE FROM login_attempt WHERE id <= ?"
-
-		deleteResult, err := sess.Exec(sql, maxId)
+		deleteResult, err := sess.Exec("DELETE FROM login_attempt WHERE created < ?", cmd.OlderThan.Unix())
```
Comment (IevaVasiljeva) [inline pkg/services/loginattempt/loginattemptimpl/store.go:44]: Nice! This is way simpler!

**Review by IevaVasiljeva — APPROVED** [review]
LGTM! Would be nice to have some tests for the new methods.
