### PR TITLE
Thresholds: Fix undefined color in "Add threshold"

### LINKED ISSUE #38822: Can't set color to threshold when added more than 55 thresholds
**What happened**:
Can't set color to threshold when last threshold is a special color, the color control of new threshold disappeared.

color

**How to reproduce it (as minimally and precisely as possible)**:
1. Click Add threshold button 55 times, you'll see threshold 0, 10, 20, 30....540
2. The color of threshold `540` would be rgb(222, 218, 247)
3. Click Add threshold button again.
4. Color control of threshold `550` disappeared.
5. Remove threshold `550`.
6. Click color control of threshold `540`, click `Custom`, click textbox(`rgb(222, 218, 247)`), press Enter key.
7. Click Add threshold button.
8. Color control of threshold `550` appeared normally.
9. Click Add threshold button.
10. Color control of threshold `560` disappeared.

**Environment**:
- Grafana version: Grafana v8.1.2 (103f8fa094)
- User OS & Browser: Edge Chromium 93.0.961.33 beta

### PR DESCRIPTION
**Pull request by glintik**
**What this PR does / why we need it**:

1) Shows default color(#CCCCCC) in color picker when all colors are used in "Thresholds" section.
2) For any undefined color value shows color picker with default black color.

If you want another default color - fixed or from pallette, let me know, I'll adjust the code accordingly.

**Which issue(s) this PR fixes**:

Fixes #38822

**Special notes for your reviewer**:

### CODE REVIEW

File: packages/grafana-ui/src/components/ThresholdsEditorNew/ThresholdsEditor.tsx [hunk 1]
```diff
@@ -59,7 +59,11 @@ export class ThresholdsEditor extends PureComponent<Props, State> {
       nextValue = steps[steps.length - 1].value + 10;
     }
 
-    const color = colors.filter((c) => !steps.some((t) => t.color === c))[1];
+    let color = colors.filter((c) => !steps.some((t) => t.color === c))[1];
+    if (!color) {
+      // Default color when all colors are used
+      color = '#CCCCCC';
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/ThresholdsEditorNew/ThresholdsEditor.tsx:65]: Maybe we should use the primary text color from the theme but that would mean you need to extend the component with theme and that might not be worth the while for this small change.

**Review by hugohaggmark — APPROVED** [review]
Thank you for contributing to Grafana, looks good and works as expected 🎉
