### PR TITLE
Explore: Be sure time range key bindings are mounted after clear

### LINKED ISSUE #56175: Explore: timerange keyboard bindings behave weirdly
**What happened**:
There are a few weird behaviours related to using time range keyboard bindings in Explore:

<details><summary>1. (fixed by https://github.com/grafana/grafana/pull/61892) Navigating away from explore and then back to it causes keybindings to be ignored (no error in console):</summary>

https://user-images.githubusercontent.com/1170767/193575390-d9c998f4-1be3-45ce-a48b-721210ae4e08.mov
</details>

<details><summary>2. In split view, only right pane's time range is updated:</summary>

https://user-images.githubusercontent.com/1170767/193575696-79b43e5c-07f4-4065-8a02-90041d98a8fd.mov
</details>

<details><summary>3. (not reproducible in 10.0) after closing split view it errors:</summary>

https://user-images.githubusercontent.com/1170767/193575904-6a138aac-fd0e-47e1-ae0c-94cad97cf1a1.mov

(opening the split view again is then similar to point 2)

**What you expected to happen**:

1. When navigating back to explore, it should work as normal
2. both pane should be affected (debatable)
3. no error should happen, it should work as normal.

</details>

**How to reproduce it (as minimally and precisely as possible)**:

se screen recordings

**Anything else we need to know?**:

**Environment**:
- Grafana version: `main`

### PR DESCRIPTION
**Pull request by gelicia**
**What is this feature?**

This was a bug caused by a couple different ways keybindings get added and removed. 

On mounting the explore page, the time range keybindings are added here. The hook looks for changes in `keybindings` which does not hold any kind of state within itself so this only fires once. https://github.com/grafana/grafana/blob/main/public/app/features/explore/ExplorePage.tsx#L56

In Grafana Route, it will clear and re-init global key bindings on every route change https://github.com/grafana/grafana/blob/main/public/app/core/navigation/GrafanaRoute.tsx#L22 

When navigating away from Explore, the time picker key bindings get wiped. When re-entering, they get re-added but before the clear and init function runs. Clear and init then wipes the re-added time range bindings.

Thanks to @ifrost for the fix! This moves the clear and reinit to the `useLayoutEffect` hook, which fires before individual components do, meaning the global keybindings are cleared and re-initialized, and then the explore page adds in the time range ones specific to explore.

**Which issue(s) does this PR fix?**:

Related to #56175

**Special notes for your reviewer**:

Replication Steps:
1. Go to Explore and run a query. Type `t z` to trigger a time range key binding. You will notice the time picker will change from a relative time to an exact time.
2. Go to home, or another non-explore page
3. Go back to explore. Attempt to type `t z` again. Notice that nothing happens. With the fix, the time range keybindings work as expected.

### CODE REVIEW

File: public/app/features/explore/ExplorePage.tsx [hunk 1]
```diff
@@ -54,7 +54,7 @@ export function ExplorePage(props: GrafanaRouteComponentProps<{}, ExploreQueryPa
 
   useEffect(() => {
     keybindings.setupTimeRangeBindings(false);
-  }, [keybindings]);
+  }, [keybindings, keybindings.bindings]);
```
Comment (ifrost) [inline public/app/features/explore/ExplorePage.tsx:57]: It's a bit obscure because to correctly implement binding someone writing the code needs to know to add `keybindings.bindings`. This is part of internal implementation of KeybindingSrv. It also makes it less abstract.

I'd prefer to just clean bindings before the render, e.g. move it to:

```typescript
  useLayoutEffect(() => {
    keybindings.clearAndInitGlobalBindings();
  }, []);
```

If that's not an option and there's no other way I'd suggest at least adding a custom hook `useKeybinding` that would encapsulate this logic.

**Review by ifrost — COMMENTED** [review]
Works as expected!

I left a comment to consider a different approach.

A few more questions: 
* Do we need to apply this fix to other places, e.g. Dashboards?
* Can it be backported?

> Partially fixes https://github.com/grafana/grafana/issues/56175

I don't think GitHub understands "partially" and will close the issue. Could you change it to "Related to #56175"?

File: public/app/features/explore/ExplorePage.tsx (hunk 1 above)
Comment (gelicia) [reply public/app/features/explore/ExplorePage.tsx]: This is a much better solution - I reverted my changes and added this one. Thank you!

**Comment by gelicia** [comment]
> Do we need to apply this fix to other places, e.g. Dashboards?

I wasn't able to replicate it outside of explore.

> Can it be backported?

It can - I changed it to backport it to 9.3 - but since this is a bug and as far as I know, has not been noticed widely, I would like to limit the backporting. I can change this if you disagree.

> I don't think GitHub understands "partially" and will close the issue. Could you change it to "Related to https://github.com/grafana/grafana/issues/56175"?

Done!

**Review by ifrost — APPROVED** [review]
