### PR TITLE
fix: create temp user no longer sets ID to 0 for all users

### LINKED ISSUE #63995: Unable to invite new user after adding 1
**What happened**:
After a clean and fresh setup of an Grafana instance I'am just able to add and invite 1 user. For each next 'Invite user' attempt it will fail with an error message 'Failed to save into database'.

image

I've found already a similar reported issue in an older version (v7.3.1): https://github.com/grafana/grafana/issues/28871

**What you expected to happen**:
That I can continously add new users.

**How to reproduce it (as minimally and precisely as possible)**:
- Setup an instance of Grafana v9.4.1
- Login as admin
- Start adding users
- --> it will fail after adding the first new user

**Anything else we need to know?**:
I followed the recommendations of the previos posted link and removed the database entry in the table 'temp_user' (see figure below). After that I was able to add one new user. Just one because the entry in the table was created again for the new one and it seems this occurence (after the user accepted his invite) blocks the ability to add additional users.

image

**Environment**:
- Grafana version: v9.4.1
- Data source type & version: -
- OS Grafana is installed on: Windows Server 2019 Datacenter
- User OS & Browser: Chrome, Edge, Firefox
- Grafana plugins: -
- Others: -

### PR DESCRIPTION
**Pull request by mildwonkey**
The xorm tag added to the tempuser ID field caused xorm to create all temp users with ID 0. Removing that tag allows xorm to set the ID based on the database result instead. I also added a test which was failing before this.

Fixes #63995

### CODE REVIEW

File: pkg/services/temp_user/model.go [hunk 1]
```diff
@@ -24,7 +24,7 @@ const (
 
 // TempUser holds data for org invites and unconfirmed sign ups
 type TempUser struct {
-	ID              int64 `xorm:"id"`
+	ID              int64
```
Comment (papagian) [inline pkg/services/temp_user/model.go:27]: in other tables we use these tags: `xorm:"pk autoincr 'id'"`
otherwise I think that xorm assumes for `i_d` column

Comment (sakjur) [inline pkg/services/temp_user/model.go:27]: I think this will become `i_d` if it's ever used, I would guess it should be something like this, no?

```suggestion
	ID              int64 `xorm:"pk autoincr 'id'"`
```

Comment (sakjur) [reply pkg/services/temp_user/model.go:27]: Sofia got there before me 🎉 🙈

**Comment by mildwonkey** [comment]
@papagian @sakjur fixed thank you! 😀

**Review by sakjur — APPROVED** [review]

**Comment by MamadR7** [comment]
Hello, I have the same problem how we can apply the fix stp. THANKS

**Comment by sakjur** [comment]
@MamadR7 The most recent Grafana version is 9.4.3, when a later version is released it should include this fix and you shouldn't have to do anything beyond upgrading to apply the fix.
