### PR TITLE
Fix notification routes editing when filters are applied

### LINKED ISSUE #45378: Alerting: Invalid notification route being edited when filters applied
When filters are applied to the notifications routes table, an invalid route may be edited

### PR DESCRIPTION
**Pull request by konrad147**
**What this PR does / why we need it**:
This PR fixes notification routes editing when there are any filters applied

**Which issue(s) this PR fixes**:
Fixes #45378

**Special notes for your reviewer**:

### CODE REVIEW

**Review by peterholmberg — APPROVED** [review]
Nice, just a minor typo :)

File: public/app/features/alerting/unified/components/amroutes/AmRoutesTable.tsx [hunk 1]
```diff
@@ -180,10 +180,14 @@ export const AmRoutesTable: FC<AmRoutesTableProps> = ({
             onSave={(data) => {
               const newRoutes = [...routes];
 
-              newRoutes[index] = {
-                ...newRoutes[index],
-                ...data,
-              };
+              const editIndex = newRoutes.findIndex((route) => route.id === data.id);
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/amroutes/AmRoutesTable.tsx:183]: Can we extract this in to a separate function and write a test for it?

**Review by gillesdemey — APPROVED** [review]
LGTM 🚀
