### PR TITLE
[Scuemeta] Fix cue schema load on windows

### LINKED ISSUE #34863: Cue crashes Grafana on startup when running on Windows
**What happened**:

After change #34488 on **main** branch, Grafana crashes on startup with:

```
t=2021-05-27T19:19:29-0700 lvl=info msg="Telemetry Gateway initialization" logger=live.push_http
service init failed: failed to load dashboard cue schema from path {{%!q(*[]embed.file=&[{cue/  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} {cue/data/  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} {cue/scuemata/  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} {cue/ui/  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} {cue/data/gen.cue package grafanaschema

...

 [86 75 157 152 122 207 49 23 165 202 142 228 90 151 147 249]}])} %!q(*fs.subFS=&{{0x3333160} public/app/plugins}) <nil>}: must provide absolute path prefix when generating cue overlay, got "/"

Process finished with the exit code 1
```

Can reproduce when running Grafana on Windows built from **main**.
It doesn't reproduce on Linux.

Can reproduce it with empty configuration (no config, no data).

**How to reproduce it (as minimally and precisely as possible)**:

Grafana works fine:
```
git checkout dbef103fb980c3365cb545dfed1c15e5feacb3d6
go run -buildmode=exe github.com/grafana/grafana/pkg/cmd/grafana-server
```

Grafana fails on startup:
```
git checkout c59a2e1bcf1225493bd9e60fa6cd2560beaf6a33
go run -buildmode=exe github.com/grafana/grafana/pkg/cmd/grafana-server
```

**Environment**:
- Grafana version: main
- OS Grafana is installed on: Windows

### PR DESCRIPTION
**Pull request by ying-jeanne**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #34863

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/schema/load/dashboard.go [hunk 1]
```diff
@@ -21,10 +23,16 @@ var panelSubpath = cue.MakePath(cue.Def("#Panel"))
 
 func defaultOverlay(p BaseLoadPaths) (map[string]load.Source, error) {
 	overlay := make(map[string]load.Source)
-	if err := toOverlay("/", p.BaseCueFS, overlay); err != nil {
+	currentDir, err := os.Getwd()
+	if err != nil {
+		fmt.Println(err)
+	}
+
+	if err := toOverlay(currentDir, p.BaseCueFS, overlay); err != nil {
```
Comment (ying-jeanne) [inline pkg/schema/load/dashboard.go:31]: in the toOverlay, according to the comments, cue overlay should be absolute path, that is why instead of changing it to toOverlay(os.pathseperator, p.BaseCueFS, overlay), i am putting currentDir instead. probably we can use environement variable to put it at home instead? not sure

File: pkg/schema/load/dashboard.go [hunk 2]
```diff
@@ -21,10 +23,16 @@ var panelSubpath = cue.MakePath(cue.Def("#Panel"))
...
 		return nil, err
 	}
-	if err := toOverlay("/", p.DistPluginCueFS, overlay); err != nil {
+	// spew.Dump(p.DistPluginCueFS)
```
Comment (zserge) [inline pkg/schema/load/dashboard.go:34]: 🚧

File: pkg/schema/load/dashboard.go [hunk 3]
```diff
@@ -43,9 +51,13 @@ func BaseDashboardFamily(p BaseLoadPaths) (schema.VersionedCueSchema, error) {
 	if err != nil {
 		return nil, err
 	}
-
+	currentDir, err := os.Getwd()
+	if err != nil {
+		fmt.Println(err)
```
Comment (zserge) [inline pkg/schema/load/dashboard.go:56]: Shouldn't we return an error here instead?

**Review by marefr — APPROVED** [review]
LGTM

**Review by sdboyer — APPROVED** [review]
