### PR TITLE
Fix data source picker width issue

### LINKED ISSUE #33111: Tracing: Trace to logs data source field in edit view is too small
**What happened**:
On current master:
image

In 7.5.3:
image

**Environment**:
- Grafana version: master 0af90795c6)
- Data source type & version: Tempo, Zipkin, Jaeger

### PR DESCRIPTION
**Pull request by zoltanbedi**
**What this PR does / why we need it**:

Fixes the issue with data source picker component being too small in data source config page.

Screenshot 2021-05-04 at 22 42 52

**Which issue(s) this PR fixes**:

Fixes #33111

### CODE REVIEW

File: packages/grafana-ui/src/components/TagsInput/TagsInput.tsx [hunk 1]
```diff
@@ -39,27 +40,26 @@ export const TagsInput: FC<Props> = ({ placeholder = 'New tag (enter key to add)
   };
 
   return (
-    <div className={styles.wrapper}>
-      <div className={styles.tags}>
+    <div className={cx(styles.wrapper, width ? css({ width: `${8 * width}px` }) : '')}>
```
Comment (torkelo) [inline packages/grafana-ui/src/components/TagsInput/TagsInput.tsx:43]: theme.spacing(width) should work here as well (does gridSize * width and return px string)

**Review by torkelo — APPROVED** [review]
LGTM

File: packages/grafana-ui/src/components/TagsInput/TagsInput.tsx (hunk 1 above)
Comment (zoltanbedi) [reply packages/grafana-ui/src/components/TagsInput/TagsInput.tsx:43]: Nice! Didn't know about that.
