### PR TITLE
Azure Monitor: Improved error messages for variable queries

### LINKED ISSUE #43197: Azure Monitor: App crashes when using invalid template variable queries
This issue was originally reported as an HG escalation. 

**What happened**:
Frontend crashes when using an invalid variable query. 

azurevariable

**What you expected to happen**:

We should handle the exception (currently we don't in the Azure Monitor plugin) and return a human readable error message.

**How to reproduce it (as minimally and precisely as possible)**:
Use a  bad template variable query, e.g `ResourceGroups(abc)`

**Anything else we need to know?**:

Azure Monitor should indeed handle exceptions, but I also think the variable query runner should handle exceptions and prevent the app from crashing. Also it looks like the query is triggered on a really short debounce time. Has this been changed recently? I believe previously, variable queries were only triggered onblur. Thoughts @hugohaggmark? 

**Environment**: 
- Grafana version: main branch
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by sunker**
**What this PR does / why we need it**:

This PR adds error handling for our interim query type - [GrafanaTemplateVariableFn](https://github.com/grafana/grafana/blob/azure-monitor/handle-variable-errors/public/app/plugins/datasource/grafana-azure-monitor-datasource/types/query.ts#L10) - in the Azure Monitor custom variable support. It also removes the debounce effect for triggering variable queries to run, and instead triggers them to run onblur. 

See [this](https://github.com/grafana/grafana/issues/43197) issue for details.

@sarahzinger should this be considered a bug and therefore backported? I'm not sure. Keeping this PR in draft state until we not what milestone to aim for. 

**Which issue(s) this PR fixes**:
Fixes #43197

### CODE REVIEW

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/variables.ts [hunk 1]
```diff
@@ -26,10 +27,15 @@ export class VariableSupport extends CustomVariableSupport<DataSource, AzureMoni
       const queryObj = await migrateStringQueriesToObjectQueries(request.targets[0], { datasource: this.datasource });
 
       if (queryObj.queryType === AzureQueryType.GrafanaTemplateVariableFn && queryObj.grafanaTemplateVariableFn) {
-        const templateVariablesResults = await this.callGrafanaTemplateVariableFn(queryObj.grafanaTemplateVariableFn);
-        return {
-          data: templateVariablesResults ? [toDataFrame(templateVariablesResults)] : [],
-        };
+        try {
+          console.log('heeej');
```
Comment (sarahzinger) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/variables.ts:31]: 👋

**Review by sarahzinger — APPROVED** [review]
Yeah seems like a bug fix good for 8.3.4 I think

**Review by sarahzinger — APPROVED** [review]
