### PR TITLE
Fix dashboard drop down links

### LINKED ISSUE #12315: Dashboard link doesn't work when "As dropdown" option is checked
### What Grafana version are you using?

v5.2.0-beta1 (commit: faa5e69)

### What OS are you running grafana on?

Amazon Linux AMI 2017.09.1.20180307 x86_64 HVM GP2

### What did you do?

I create dashboard link as dropdown. And I click it.

dashboardlink

### What was the expected result?

When I click the dashboard link, I expect related dashboards are listed in dropdown menu.

### What happened instead?

Navigate to root url.

If as dropdown option is not checked, it seems that dashboard link works well.

### PR DESCRIPTION
**Pull request by marefr**
Fixes #12315

### CODE REVIEW

**Comment by torkelo** [comment]
I think a better fix would be to not sanitize the whole link but just the text. 

looking at https://github.com/grafana/grafana/pull/11813/files I am not sure why the whole link is sanitized, we control that. it's only the link title & tooltip that are user inputs.

**Comment by alexanderzobnin** [comment]
@torkelo @marefr I also suggested an option to use `ng-href` instead of `href` and then compile template with `$compile` service. In this case angular sanitizes links automatically.

```diff
diff --git a/public/app/features/dashlinks/module.ts b/public/app/features/dashlinks/module.ts
index 148d32f..b4a353e 100644
--- a/public/app/features/dashlinks/module.ts
+++ b/public/app/features/dashlinks/module.ts
@@ -31,7 +31,7 @@ function dashLink($compile, $sanitize, linkSrv) {
         template +=
           '<ul class="dropdown-menu" role="menu">' +
           '<li ng-repeat="dash in link.searchHits">' +
-          '<a href="{{dash.url}}" target="{{dash.target}}">{{dash.title}}</a>' +
+          '<a ng-href="{{dash.url}}" target="{{dash.target}}">{{dash.title}}</a>' +
           '</li>' +
           '</ul>';
       }
@@ -39,7 +39,6 @@ function dashLink($compile, $sanitize, linkSrv) {
       template += '</div>';
 
       elem.html(template);
-      $compile(elem.contents())(scope);
 
       var anchor = elem.find('a');
       var icon = elem.find('i');
@@ -48,8 +47,7 @@ function dashLink($compile, $sanitize, linkSrv) {
       function update() {
         var linkInfo = linkSrv.getAnchorInfo(link);
         span.text(linkInfo.title);
-        anchor.attr('href', linkInfo.href);
-        sanitizeAnchor();
+        anchor.attr('ng-href', linkInfo.href);
 
         // tooltip
         elem.find('a').tooltip({
@@ -57,11 +55,8 @@ function dashLink($compile, $sanitize, linkSrv) {
           html: true,
           container: 'body',
         });
-      }
 
-      function sanitizeAnchor() {
-        const anchorSanitized = $sanitize(anchor.parent().html());
-        anchor.parent().html(anchorSanitized);
+        $compile(elem.contents())(scope);
       }
 
       icon.attr('class', 'fa fa-fw ' + scope.link.icon);
```

**Comment by marefr** [comment]
> it's only the link title & tooltip that are user inputs

That's not true. For an absolute link the href is user input as well. I tried the ng-href solution, but angular prefixes a href of `javascript: alert('XSS')` with `unsafe:` and in my case resulted in chrome trying to open a new page/navigate away.

File: public/app/features/dashlinks/module.ts [hunk 1]
```diff
@@ -49,8 +49,10 @@ function dashLink($compile, $sanitize, linkSrv) {
         var linkInfo = linkSrv.getAnchorInfo(link);
         span.text(linkInfo.title);
         anchor.attr('href', linkInfo.href);
```
Comment (alexanderzobnin) [inline public/app/features/dashlinks/module.ts]: I think it makes sense to add `href` only if dropdown is not used to prevent unnecessary link on button:
```js
span.text(linkInfo.title);
if (!link.asDropdown) {
  anchor.attr('href', linkInfo.href);
  sanitizeAnchor();
}
```

**Review by alexanderzobnin — CHANGES_REQUESTED** [review]
Since `$sanitize` only strips data attribute in this case, I think this fix makes sense. What do you think about my note about `href` for dropdown menu?

**Comment by torkelo** [comment]
sorry, it seems more complicated than I thought :) if ng-href can't be used then I this should be an ok solution.

File: public/app/features/dashlinks/module.ts (hunk 1 above)
Comment (marefr) [reply public/app/features/dashlinks/module.ts]: Yeah sounds like a good idea. Will push a fix

**Review by alexanderzobnin — APPROVED** [review]
