### PR TITLE
Panel: Show multiple errors info in the inspector

### LINKED ISSUE #54665: Support display/visualization of multiple data response errors in the UI
The `error` property on the `DataQueryResponse` interface can only hold one data response error currently:
https://github.com/grafana/grafana/blob/8e4fa4046bcf373ca52a0bd382ed00664fd4bb81/packages/grafana-data/src/types/datasource.ts#L427-L444

The `toDataQueryResponse` function, used by the [DataSourceWithBackend class](https://github.com/grafana/grafana/blob/8e4fa4046bcf373ca52a0bd382ed00664fd4bb81/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L183) that all backend plugin datasources extends, are populating the `DataQueryResponse.error` with the first data response coming back from /api/ds/query than contains an error: https://github.com/grafana/grafana/blob/8e4fa4046bcf373ca52a0bd382ed00664fd4bb81/packages/grafana-runtime/src/utils/queryResponse.ts#L82-L91

We want/need to support `DataQueryResponse` holding multiple data response errors in case they are different to provide end users with the full details of what went wrong. 

Open questions:
- How to display/visualize multiple errors to end users in dashboards, Explore and potentially the Alerting rule editor

### LINKED ISSUE #58637: Support display/visualization of data response status in the UI
With https://github.com/grafana/grafana-plugin-sdk-go/pull/544 merged it results in query data responses having a `status` property rendered in the JSON response being returned from the /api/ds/query endpoint. This `status` property can have an HTTP status value, e.g. 200 Ok, 500 Internal server error etc.

By default, when data response doesn't include an error, the status 200 (Ok) is set:
image

By default, when data response include an error, the status 500 (Internal server error) is set:
image

A plugin author could implement support in backend plugin for setting the status and by that circumvent the default behavior referenced above.

We want/need to support data response status code being displayed/visualized when there's an error to give end users more context of why an error happened. 

Open questions:
- How to display/visualize status code from a UX perspective? 
  - Is the existing query inspector enough perhaps?
  - Do we want to combine it somehow with the existing error message already being shown for panel errors, e.g. 
image
  - Do we want to combine it somehow with the existing error message already shown for Explore query/panel query editing, e.g. 
image
image

### PR DESCRIPTION
**Pull request by andresmgot**
**What is this feature?**

The goal of this PR is to show the details of the errors in case a query with multiple targets fails more than once. Before, only the first error was shown in the panel title error and in the inspector. Now, in case there are multiple errors, only that is stated in the title error. Clicking on it displays the query inspector, in the Error tab which shows information about all the errors.

This also includes information about the status code in the error message (which was missing before):

[Screencast from 07-03-23 16:51:56.webm](https://user-images.githubusercontent.com/4025665/223487840-b69f6e3a-9173-42ce-b186-2af34db46da8.webm)

Since the error could have different formats (e.g. including a json). This is how it looks for the different formats:

Screenshot from 2023-03-07 16-52-49

**Why do we need this feature?**

To display all the information available to the user about an error.

**Who is this feature for?**

Grafana users.

**Which issue(s) does this PR fix?**:

Fixes #54665
Fixes #58637

**Special notes for your reviewer**:

This supersedes https://github.com/grafana/grafana/pull/64022

### CODE REVIEW

File: public/app/features/inspector/InspectErrorTab.tsx [hunk 1]
```diff
@@ -35,15 +32,39 @@ export const InspectErrorTab = ({ error }: InspectErrorTabProps) => {
...
   }
   return <JSONFormatter json={error} open={2} />;
+}
+
+export const InspectErrorTab = ({ errors }: InspectErrorTabProps) => {
+  if (!errors?.length) {
+    return null;
+  }
+  if (errors.length === 1) {
+    return renderError(errors[0]);
```
Comment (leventebalogh) [inline public/app/features/inspector/InspectErrorTab.tsx:59]: What's the reason behind rendering a single error slightly differently (not wrapping it with an `<Alert>`)?

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx [hunk 2]
```diff
@@ -43,6 +53,7 @@ export function PanelHeader({ panel, error, isViewing, isEditing, data, alertSta
         scopedVars={panel.scopedVars}
         links={getPanelLinksSupplier(panel)}
         error={error}
+        multipleErrors={multipleErrors}
```
Comment (leventebalogh) [inline public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx:56]: Nit: maybe a name like `hasMultipleErrors` would communicate better that this is a boolean prop

**Review by leventebalogh — APPROVED** [review]
LGTM, but would be good to also wait for someone from user essentials to have a look.

File: public/app/features/dashboard/dashgrid/PanelStateWrapper.tsx [hunk 3]
```diff
@@ -717,6 +719,7 @@ export class PanelStateWrapper extends PureComponent<Props, State> {
             isViewing={isViewing}
             alertState={alertState}
             data={data}
+            multipleErrors={this.state.multipleErrors}
```
Comment (axelavargas) [inline public/app/features/dashboard/dashgrid/PanelStateWrapper.tsx:722]: `multipleErrors`  it is being implemented only in the old panel header, are there plans to make the same adjustments in the new PanelHeader?  

ps, The new panel header is being developed under `newPanelChromeUI` :)

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderCorner.tsx [hunk 4]
```diff
@@ -95,15 +96,16 @@ export class PanelHeaderCorner extends Component<Props> {
...
 
     if (!infoMode) {
       return null;
     }
 
-    if (infoMode === InfoMode.Error && error) {
-      return this.renderCornerType(infoMode, error, this.onClickError);
+    if (infoMode === InfoMode.Error && (error || multipleErrors)) {
+      const errorMsg = multipleErrors ? 'Multiple errors found. Click for more details' : error || '';
+      return this.renderCornerType(infoMode, errorMsg, this.onClickError);
```
[the remark this answers is not in the document]
Comment (andresmgot) [reply public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderCorner.tsx:108]: this is tricky because this is rendered as  `Tooltip` content and that has a delay of 150ms. Not even the `Tooltip` tests cover this but I can give it a try.

File: public/app/features/dashboard/dashgrid/PanelStateWrapper.tsx (hunk 3 above)
Comment (andresmgot) [reply public/app/features/dashboard/dashgrid/PanelStateWrapper.tsx:722]: good shout :+1: I missed that

File: public/app/features/inspector/InspectErrorTab.tsx (hunk 1 above)
Comment (andresmgot) [reply public/app/features/inspector/InspectErrorTab.tsx:59]: I didn't want to affect the current style since for one error it's clear that it's a single thing. For multiple errors, the best way I found to encasulate them separately was to show different Alerts. Happy to suggestions if there is something else I could try!

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx (hunk 2 above)
Comment (andresmgot) [reply public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx]: I removed this property at the end, it's enough to have the `error`

**Comment by andresmgot** [comment]
Also covered now the new panel header:

Screenshot from 2023-03-08 13-12-12

**Review by axelavargas — APPROVED** [review]
Great work @andresmgot 🥳
