### PR TITLE
UI/ClipboardButton: Remove ClipboardJS in favor of native Clipboard API

### LINKED ISSUE #42365: ClipboardButton to share Panel link does not work on Chrome
**What happened**:

Once I click on the `<ClipboardButton>` present on the `Link` tab of the `Share Panel` (while trying to share the link to a specific panel present on a dashboard), it displays the success alert but the text (the link, shortened or not) is not actually copied.

**What you expected to happen**:

The text (the link, shortened or not) to be actually copied.

**How to reproduce it (as minimally and precisely as possible)**:

1. Click on the dropdown present along the name of any dashboard panel.
2. Click on "Share".
3. Click on the blue "Copy" button along the panel link.
(Then the link is not actually copied)

**Anything else we need to know?**:

- Did some debugging and looks like the text is being sent to the `clipboard.js` library.
- Tried to update latest patch release of `clipboard.js` library and still not working.
- Tested on Safari and it worked, so looks like something specific to Google Chrome and maybe other browsers.
- Haven't seen any clear issue or insight from `clipboard.js`'s repository, but may worth looking further.

**Environment**: 
- Grafana version: Tested on `main` and `v8.4.0-43362pre`
- Data source type & version: -
- OS Grafana is installed on: MacOS & GCloud
- User OS & Browser: Mac OS Monterrey - `Google Chrome v96.0.4664.55 (Build oficial) (x86_64)`
- Grafana plugins: -
- Others: -

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Removes ClipboardJS, which uses the deprecated [execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) feature in favor of the native [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText).

**Which issue(s) this PR fixes**:
Closes #42365

### CODE REVIEW

**Comment by ryantxu** [comment]
IIUC, this is a breaking change for people using `<ClipboardButton  .../>` in plugin development, it does not change any grafana end user behavior.

@pkolyvas - do we have a strategy for better identifying that?

File: packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.tsx [hunk 1]
```diff
@@ -1,51 +1,26 @@
...
-import Clipboard from 'clipboard';
+import React, { useCallback } from 'react';
 import { Button, ButtonProps } from '../Button';
 
 export interface Props extends ButtonProps {
   /** A function that returns text to be copied */
   getText(): string;
   /** Callback when the text has been successfully copied */
-  onClipboardCopy?(e: Clipboard.Event): void;
+  onClipboardCopy?(): void;
```
Comment (mckn) [inline packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.tsx:8]: Would it be possible to keep backward compatibility by introducing our own ClipboardEvent type that looks the same as the `Clipboard.Event`? Or is that a complex type to manage?

Comment (kaydelaney) [reply packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.tsx:8]: I'll look into it

**Review by mckn — COMMENTED** [review]
Great work on this!

I guess it is breaking backwards compatibility in two ways.

- The ClipboardButton props changes.
- The removal of the angular directive.

Are we breaking it in more ways? Feels like it is kind of easy to keep backward compatibility until Grafana 9 but deprecate it now. Or what is the plan going forward?

File: packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.tsx (hunk 1 above)
Comment (kaydelaney) [reply packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.tsx:8]: So the interface is like this:
```ts
    interface Event {
        action: string;
        text: string;
        trigger: Element;
        clearSelection(): void;
    }
```

The trouble is some of these don't really make sense (e.g. `clearSelection`) now that the Clipboard API is being used, so I'm not sure what the best move is.

Comment (mckn) [reply packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.tsx:8]: Ok ok, I will see if I can find any stats on how widely this is used.

Comment (joshhunt) [reply packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.tsx:8]: From my looks within grafana, no one uses it. Can't comment for _outside_ of grafana.,

I would consider providing a "dummy" event object, at least to prevent any `cannot read property action of undefined` exceptions.

Comment (kaydelaney) [reply packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.tsx:8]: Not the most scientific test, but I downloaded every plugin supported by the current version of Grafana and grepped for `ClipboardButton` with no results, which makes me think it's not used by anyone. But then again, a breaking change is a breaking change

Comment (mckn) [reply packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.tsx:8]: I think you can carry on with this change. I have checked our collected data and can't find anyone using this. However, I have only checked the react code. So there might be usages of the angular directive.

**Comment by kaydelaney** [comment]
Added a copy of the old `ClipboardEvent` interface for backwards compatibility and an angular wrapped version of the new component in case any plugins use that. I'll try and remember to remove all that when 9.0 comes around.

**Review by mckn — APPROVED** [review]
LGTM! Really great work with this @kaydelaney 🙌🏻
