### PR TITLE
Fix canvas connection point z-indexing bug

### LINKED ISSUE #106028: Canvas: Connection anchor z-index
Connection anchor placed behind the element, when it should be on top of it.

Incorrect position:
Image

Correct position:
Image

### PR DESCRIPTION
**Pull request by jesdavpet**
This is meant to fix the bug we discovered in z-indexing for Canvas element connection points: https://github.com/grafana/grafana/issues/106028

🐞 🔍 :shipit: _It seems that this bug was caused by nesting the connection points in a parent component that resulted in a DOM hierarchy where their z-index was constrained by that of the parent element._

Screenshot 2025-06-25 at 7 54 29 PM

### CODE REVIEW

File: public/app/features/canvas/runtime/root.tsx [hunk 1]
```diff
@@ -54,6 +54,7 @@ export class RootElement extends FrameState {
         {this.elements.map((v) => (
           <Fragment key={v.UID}>{v.render()}</Fragment>
         ))}
+        {this.scene.connections.render()}
```
Comment (jesdavpet) [inline public/app/features/canvas/runtime/root.tsx:57]: **note:** 📓 I was striving for the _minimum_ viable change to fix the bug, that's how I landed on this approach.

However, I'm also super open to other approaches if there are any concerns around hoisting the connection points higher in the DOM ordering at the root level.

**Review by Develer — COMMENTED** [review]
LGTM!
As long as root element is one and the only element (unique element) we safe (let's double check).

Also, back to our discussion, let's check the option to just swap connections and root render to see if we can do something this way.

**Comment by Develer** [comment]
Hey Jesse,
Thanks for the clean and elegant solution - really nice work!
I didn’t get a chance to review the PR before it was merged, but I noticed one small issue: it seems I can’t select elements by clicking on them 🤔
