### PR TITLE
Plugins: Disable plugin uninstall while plugin is installing

### LINKED ISSUE #95050: Disable plugin installation control button during installation
Right now it's possible to uninstall a plugin while it was not fully installed, leading to a situation where we try to uninstall a plugin that is not installed and we see the following error:

https://github.com/user-attachments/assets/1640bd9f-359f-4503-895e-7ea38cb49f13

We should disable the plugin uninstall while the plugin isn't fully installed.

### PR DESCRIPTION
**Pull request by oshirohugo**
**What is this feature?**

Disable plugin uninstall while the plugin is not fully installed in cloud.

**Why do we need this feature?**

This is a bug fix to avoid that a user uninstall a plugin in cloud that was not fully installed.

**Who is this feature for?**

Plugin catalog users.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/95050

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/plugins/admin/components/InstallControls/InstallControlsButton.tsx [hunk 1]
```diff
@@ -119,7 +119,7 @@ export function InstallControlsButton({
 
   let disableUninstall =
     config.pluginAdminExternalManageEnabled && configCore.featureToggles.managedPluginsInstall
-      ? plugin.isUninstallingFromInstance
+      ? plugin.isUninstallingFromInstance || !plugin.isFullyInstalled || plugin.isUpdatingFromInstance
```
Comment (s4kh) [inline public/app/features/plugins/admin/components/InstallControls/InstallControlsButton.tsx:122]: Is it possible to create a function and name it with logic behind `plugin.isUninstallingFromInstance || !plugin.isFullyInstalled || plugin.isUpdatingFromInstance` check? Encapsulate Predicate refactor.

**Review by leventebalogh — COMMENTED** [review]
Let's extend / update [the tests](https://github.com/grafana/grafana/blob/44290ddf3285ca5d40095ab3b56d0bbea88448ee/public/app/features/plugins/admin/components/InstallControls/InstallControlsButton.test.tsx#L0-L1) as well to cover this scenario (and then we can also more easily refactor the underlying logic in the future)!

**Review by s4kh — APPROVED** [review]

**Review by leventebalogh — APPROVED** [review]
LGTM 👍
