### PR TITLE
Dashboard: SchemaV2 - Fix stateless variable query with default datasource

### LINKED ISSUE #106825: Dashboard: Schema V2 - Default Datasource in variables conflict with stateless query variables
When we have a V1 Dashboards with query variables using the default datasource in v1 implementation we resolve the DS in runtime to be the default ds configured in the instance.

In V2 implementation we follow the "bestGuess" datasource logic that takes the first available ds from the datasource type

```
"variables": [
    {
      "kind": "QueryVariable",
      "spec": {
        ....
        "query": { //THERE IS NO DS defined
          "kind": "prometheus",
          "spec": {
            "qryType": 1,
            "query": "label_values(<SUPER QUERY>)",
            "refId": "PrometheusVariableQueryEditor-VariableQuery"
          }
        },
       ...
      }
    }
  ]
```

This is related to the stateless datasource logic we implementend:
https://github.com/grafana/grafana/blob/main/public/app/features/dashboard-scene/serialization/layoutSerializers/utils.ts#L227

### PR DESCRIPTION
**Pull request by axelavargas**
### Current Problem: 

Reported internally [slack](https://raintank-corp.slack.com/archives/C07QVGH37D4/p1748628706450199) 

In V1 dashboards with query variables using no explicit datasource would resolve to the instance's default datasource. In V2, the "bestGuess" logic picks the first available datasource of the required type.

### Approach to resolve this issue:

Refactor `getDataSourceForQuery()` to:
  1. First check if the default datasource matches the query type from the variable query - use it if it does
  2. Fall back to existing "bestGuess" logic (first available of that type) if default doesn't match
  3. Keep final fallback to default datasource regardless of type

Fixes: https://github.com/grafana/grafana/issues/106825

Tasks:
- [x]  Test with similar dashboard provided in the issue 
- [x] Fix logic
- [x] Add test

https://github.com/user-attachments/assets/795445d1-ef9c-401a-b120-3abbb2baeaac

### CODE REVIEW

File: public/app/features/dashboard-scene/serialization/layoutSerializers/utils.ts [hunk 1]
```diff
@@ -224,12 +224,23 @@ function getDataSourceForQuery(
...
+    };
+  }
+
+  // Look up by query type/kind from all available datasources
   const bestGuess = dsList && Object.values(dsList).find((ds) => ds.meta.id === queryKind);
 
   if (bestGuess) {
     return { uid: bestGuess.uid, type: bestGuess.meta.id };
   } else if (dsList && dsList[defaultDatasource]) {
+    // Fallback to default datasource even if type doesn't match
```
Comment (dprokop) [inline public/app/features/dashboard-scene/serialization/layoutSerializers/utils.ts:243]: @axelavargas - can we add a console.warn about this case? Would make things easier to debug if we see any issues regarding resolving the data source.

Comment (axelavargas) [reply public/app/features/dashboard-scene/serialization/layoutSerializers/utils.ts:243]: Yes! good idea

Comment (axelavargas) [reply public/app/features/dashboard-scene/serialization/layoutSerializers/utils.ts:243]: ✅ here [`bdae902` (#106850)](https://github.com/grafana/grafana/pull/106850/commits/bdae902633fc11b5f0cb3bcad8ef3a6128b08889)

**Review by dprokop — APPROVED** [review]

**Review by ivanortegaalba — APPROVED** [review]
