### PR TITLE
Explore: Align time filters properly to day boundaries in query history

### LINKED ISSUE #81044: Query History: Incorrect time filtering
### Steps to reproduce

Prerequisite: You need some items in your query history that were added more than 24 hours ago

1. Open Explore
2. Open Query History
3. Scroll down and click "load more" to make sure all items for yesterday are loaded
4. Check number of queries saved yesterday, e.g. (22 January => 64 queries)

Image

5. Change the filter (top slider) from "today" to "yesterday"

Expected behavior: The same number of queries is shown for the same date as in step 3

Current: Fewer queries are shown, e.g. (22 January => 15 queries)

Image

### Technical details

* The filtering is relative to the current time. Selecting “yesterday” uses “now-1d” as a filter
* We could use `now-1d/d` instead of `now-1d` to make it absolute

### PR DESCRIPTION
**Pull request by aocenas**
Fixes: https://github.com/grafana/grafana/issues/81044

Even though the query history filters operate on days we sent `now - nDays` as a relative timestamp which means it wasn't aligned on the day boundary making the results seem none non-deterministic.

This reuses some utility function to align to the start or end of the day and also adds a timezone param to do that properly if user changes their timezone. At the same time it shifts where this happens. Before the transform was done inside the history service code which make it having to know about users time zone and also sort of leaks the UI decisions into it. This now transforms the filters before calling the service so that the service operates on standard from - to UNIX timestamps while the front end stores it states as days from now which is aligned with the UI.

### CODE REVIEW

File: public/app/core/history/RichHistoryRemoteStorage.ts [hunk 1]
```diff
@@ -132,11 +134,11 @@ function buildQueryParams(filters: RichHistorySearchFilters): string {
     params = params + `&sort=${filters.sortOrder === SortOrder.Ascending ? 'time-asc' : 'time-desc'}`;
   }
   if (!filters.starred) {
-    const relativeFrom = filters.from === 0 ? 'now' : `now-${filters.from}d`;
-    const relativeTo = filters.to === 0 ? 'now' : `now-${filters.to}d`;
     // TODO: Unify: remote storage from/to params are swapped comparing to frontend and local storage filters
-    params = params + `&to=${relativeFrom}`;
-    params = params + `&from=${relativeTo}`;
+    const from = createRetentionPeriodBoundary(filters.to ?? 14, { isLastTs: true, tz: contextSrv.user?.timezone });
```
Comment (aocenas) [inline public/app/core/history/RichHistoryRemoteStorage.ts:138]: There is also a timezone in the Explore redux state but we still also keep it updated in the contextSrv so I thought that should be treated as the main source of truth here (also it's easier to access here)

File: public/app/core/history/richHistoryLocalStorageUtils.ts [hunk 2]
```diff
@@ -25,22 +28,27 @@ export function filterAndSortQueries(
   return sortQueries(filteredQueriesToBeSorted, sortOrder);
 }
 
-export const createRetentionPeriodBoundary = (days: number, isLastTs: boolean) => {
-  const today = new Date();
-  const date = new Date(today.setDate(today.getDate() - days));
+export const createRetentionPeriodBoundary = (
```
Comment (aocenas) [inline public/app/core/history/richHistoryLocalStorageUtils.ts:31]: Mayne this should be moved somewhere near the front end? Not sure so opted for keeping it here for now.

File: public/app/core/history/RichHistoryStorage.ts [hunk 3]
```diff
@@ -1,4 +1,5 @@
-import { RichHistorySearchFilters, RichHistorySettings } from 'app/core/utils/richHistory';
+import { RichHistorySearchBackendFilters, RichHistorySettings } from 'app/core/utils/richHistoryTypes';
+import {} from '@grafana/runtime';
```
Comment (ifrost) [inline public/app/core/history/RichHistoryStorage.ts:2]:
```suggestion
```

🤔

File: public/app/core/history/RichHistoryLocalStorage.ts [hunk 4]
```diff
@@ -173,7 +173,8 @@ function updateRichHistory(
  */
 function cleanUp(richHistory: RichHistoryLocalStorageDTO[]): RichHistoryLocalStorageDTO[] {
   const retentionPeriod: number = store.getObject(RICH_HISTORY_SETTING_KEYS.retentionPeriod, 7);
-  const retentionPeriodLastTs = createRetentionPeriodBoundary(retentionPeriod, false);
+  // We don't care about timezones that much here.
```
[the remark this answers is not in the document]
Comment (aocenas) [reply public/app/core/history/RichHistoryLocalStorage.ts:176]: Hmm not sure right now. Like we are cleaning up old things every time we add a new item. It probably does not make sense to clean it up differently based on the currently set timezone, like if you change for querying but it now deletes some additional history items it would be a bit weird. Like it probably should not be aligned to end of date at all and just do now - (14 x 24h) always. At the same time like does not seem like a big deal, not sure we even still use local history or not.

[the remark this answers is not in the document]
Comment (aocenas) [reply public/app/core/history/RichHistoryLocalStorage.ts]: Updated the comment though I hope that makes ti more clear.

**Review by ifrost — APPROVED** [review]
LGTM 🎉
