### PR TITLE
Provisioning: Fix unmarshaling nested jsonData values

### LINKED ISSUE #11537: datasource provisioning not working if datasource has nested jsonData options
### What Grafana version are you using?
5.0.4

### What datasource are you using?
[grafana-prometheus-alertmanager-datasource](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource) but other datasources might be effected if they use nested configuration

### What OS are you running grafana on?
Ubuntu 16.04 (Linux vagrant 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)
Docker version 17.12.0-ce, build c97c6d6

### What did you do?

* Installed Grafana as Docker Container
* Installed Alertmanager Datasource Plugin version 0.0.4 (https://grafana.com/plugins/camptocamp-prometheus-alertmanager-datasource/installation)
* provisioned the datasource via config file:

```
apiVersion: 1
deleteDatasources:
datasources:
- name: alertmanager
type: camptocamp-prometheus-alertmanager-datasource
access: proxy
url: https://192.168.77.30
version: 1
editable: false
jsonData:
tlsSkipVerify: true
severity:
critical: 3
warning: 2
info: 1
```

### What was the expected result?
That the datasource is added and the plugin is configured as set up.

### What happened instead?
Datasource is added but configuration from jsonData is not applied. Also verified via api:

```
# request to https://192.168.77.20/api/datasources
[
        {
"id": 21,
"orgId": 1,
"name": "alertmanager",
"type": "camptocamp-prometheus-alertmanager-datasource",
"typeLogoUrl": "public/img/icn-datasource.svg",
"access": "proxy",
"url": "https://192.168.77.30",
"password": "",
"user": "",
"database": "",
"basicAuth": false,
"isDefault": false,
"readOnly": true
        },
....
```

jsonData is missing

Setting up via grafana web gui works as expected. The problem seams to be that the nested structure is not properly handled while reading the config. The problem might be somewhere around here: https://github.com/grafana/grafana/blob/v5.0.4/pkg/services/provisioning/datasources/types.go#L222
I tried to find an issue but there is nothing that is obvious to me.

I also tried different variants of configuration formatting (documentation suggests json blob), so I tried things like this without success:
`jsonData: {"tlsSkipVerify":true, "severity": {"critical":page,"warning":critical,"info":warning}}`
`jsonData: '{"tlsSkipVerify":true, "severity": {"critical":page,"warning":critical,"info":warning}}'`
`jsonData: '{"tlsSkipVerify":true, "severity": {"critical":"page","warning":"critical","info":"warning"}}'`

```
jsonData:
tlsSkipVerify":true
severity: {"critical":page,"warning":critical,"info":warning}}

# produces in the api but does not work in the datasource configuration
"jsonData": {
"severity": "{\"critical\":page,\"warning\":critical,\"info\":warning}}",
"tlsSkipVerify": true
},
```

@bergquist Since you might be familiar with the code of the provisioning it would be very kind if you could take a look at this, thanks in advance.

### PR DESCRIPTION
**Pull request by aocenas**
Fixes: https://github.com/grafana/grafana/issues/11537
Problem was that yaml un-marshal returned nested maps as `map[interface{}]interface{}` which are then not marshal-able to json because of that `interface{}` key type. This adds explicit casting of the keys in the yaml value types to string which then makes the values marshal-able to JSON in DB.

### CODE REVIEW

File: pkg/services/provisioning/values/values.go [hunk 1]
```diff
@@ -151,14 +154,15 @@ func (val *StringMapValue) Value() map[string]string {
...
 }
 
-// tranformInterface tries to transform any interface type into proper value with env expansion. It travers maps and
+// transformInterface tries to transform any interface type into proper value with env expansion. It travers maps and
 // slices and the actual interpolation is done on all simple string values in the structure. It returns a copy of any
-// map or slice value instead of modifying them in place.
-func tranformInterface(i interface{}) interface{} {
+// map or slice value instead of modifying them in place and also return value without interpolation but with converted
+// type as a second value.
+func transformInterface(i interface{}) (interface{}, interface{}) {
```
Comment (aocenas) [inline pkg/services/provisioning/values/values.go]: Returning 2 values so that both raw value and value which was interpolated has the same types and there is no discrepancy. Also non string keys will be dropped (should not happen but yaml technically allows non string keys afaik) which would also create a difference in raw vs interpolated value.

**Comment by aocenas** [comment]
@marefr Although the bug itself is old, I added this to current beta because with the derived fields feature in Loki we need a nested jsonData to make that provision-able.

**Comment by wardbekker** [comment]
With a docker image that contains this fix, I had issues with template variables in the url field of this YAML below. 

The docker image SHA used is: sha256:37e71eaf4076d43a30e44c3c7b9a048c7a8086675f1c2d5b53962a97613b38b3

````yaml
apiVersion: 1
datasources:
- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  basicAuth: false
  jsonData: 
    maxLines: 1000
    derivedFields: 
    - matcherRegex: ".*trace_id=(.*?)\\s.*"
      name: "TraceId"
      url: "http://localhost:16686/trace/${__value.raw}"    
````

**Comment by marefr** [comment]
@wardbekker solution is here: https://grafana.com/docs/administration/provisioning/#using-environment-variables

So you want to use `$$` instead of `$`:
````yaml
apiVersion: 1
datasources:
- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  basicAuth: false
  jsonData: 
    maxLines: 1000
    derivedFields: 
    - matcherRegex: ".*trace_id=(.*?)\\s.*"
      name: "TraceId"
      url: "http://localhost:16686/trace/$${__value.raw}"    
````

**Review by marefr — APPROVED** [review]
Great :+1: LGTM
