### PR TITLE
GrafanaUI: InputGroup: Fix invalid children borders

### LINKED ISSUE #56006: InputGroup removes left side of invalid red border in select or input
**What happened**:

In `InputGroup`, because there we are removing left border from every child (starting with second child). This is correctly looking when you have normal selects or inputs. However, when select/input is invalid, this results in invalid state (red boarder) being only visible on 3 sides as the right side is overridden in InputGroup. 

I encountered this while working at https://github.com/grafana/grafana/pull/55751#discussion_r983426283. 

**What you expected to happen**:

If any children in InputGroup are invalid, all borders have invalid styling.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: main 9.3.0-pre

### PR DESCRIPTION
**Pull request by joshhunt**
**What this PR does / why we need it**:

This updates the experimental InputGroup component to support children with "invalid" borders.

This is a bit of a tricky one - to collapse adjacent borders inside an input group, children have a negative left margin to overlap the borders, and then we raise the z-index when hovering so all of the hovered element's borders are visible.

The tricky part is how to raise the z-index of invalid children. I initially tried with putting a `data-invalid` attribute on individual components when they're invalid, and targeting that in InputGroups's CSS, but I couldn't get the attribute to on the Select component.

Instead, I went with inspecting children's props to look for `invalid` and use `cloneElement` to apply an extra className to the child if it's invalid. I'm not totally enthusiastic about this, but so far it's the only approach I've really found. Really open to other ideas here. This does create requirements on "invalid" children though - they must have an `invalid` prop, and accept a `className`,
 
image

image

image

image

**Which issue(s) this PR fixes**:

Fixes #56006

**Special notes for your reviewer**:

### CODE REVIEW

File: packages/grafana-ui/src/components/QueryEditor/InputGroup.tsx [hunk 1]
```diff
@@ -1,16 +1,38 @@
...
+export const InputGroup = ({ children }: InputGroupProps) => {
   const styles = useStyles2(getStyles);
 
-  return <div className={styles.root}>{children}</div>;
+  // Find children with an invalid prop, and set a class name to raise their z-index so all
+  // of the invalid border is visible
+  const modifiedChildren = Children.map(children, (child) => {
+    if (isValidElement(child) && child.props.invalid) {
+      return cloneElement(child, { className: cx(child.props.className, styles.invalidChild) });
+    }
```
Comment (joshhunt) [inline packages/grafana-ui/src/components/QueryEditor/InputGroup.tsx:19]: hmmm i think this needs more testing to make sure that `cloneElement()` doesn't do funky things to form controls when they change from valid -> invalid

**Comment by joshhunt** [comment]
Other options: InputGroup could take an `invalidIndex` prop, and we use that with some `nth-child(invalidIndex)` css to raise the z-index. I don't really like this because it breaks the invalid logic up for the consumer. Having to write

```jsx
<InputGroup invalidIndex={2}>
  <Input placeholder="One" />
  <Input placeholder="Two" invalid />
</InputGroup>
```

is weird.

Another option could be to use a `<Invalid>` component (that's just a simple pass-through component) to identify the index of the invalid child, and use similar css to the above suggestion.

```jsx
<InputGroup>
  <Input placeholder="One" />
  <Invalid>
    <Input placeholder="Two" invalid />
  </Invalid>
</InputGroup>
```

still, it's weird, and makes you have to do two things to mark an input as invalid.

Perhaps there's another approach to take for the collapsing borders that could work?

**Review by dprokop — APPROVED** [review]
@joshhunt thanks for exploring all the different alternatives. This is tricky, i would hope for the data attribute to work, but looking into [react-select implementation](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Select.tsx), it's only aria props that are passed down to the component. 

All in all, I think the implemented proposal should work as expected. IIRC cloneElement does shallow clone, so the referential equality, if required by any outer element, should be preserved.
