### PR TITLE
Permissions: Fix inherited folder permissions can prevent new permissions being added to a dashboard

### LINKED ISSUE #33296: Inherited folder permissions can prevent new permissions being added to a dashboard
**What happened**:
Dashboard permissions can end up with duplicate entries by inheriting a permission from their parent folder that is also defined in the dashboard.  This prevents new entries from being added, and resulting in a confusing error message.

**What you expected to happen**:
Either the duplicate permission not to matter, or for a clear error message directing the user what to do.

**How to reproduce it (as minimally and precisely as possible)**:
- create a test folder FOLDER , and a test dashbaord BOARD within the folder
- GIve the test BOARD permissions "Editor can edit".
- go back to the parent FOLDER, and give the folder permissions "editor can edit"
- go back to the test dashboard BOARD, edit the permissions, and try to add a permission for a specific user to have any permissions.
- 
You get the error "you can only override a permission to be higher" (image to follow)

image (7)

**Anything else we need to know?**:
If the BOARD's permission "Editor can edit" is removed, the new permission can be saved. 

**Environment**:
- Grafana version: 7.4.5
- Data source type & version: n/a 
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: n/a
- Grafana plugins:  n/a 
- Others: n/a

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
In the case permissions has been added on dashboard(s). Later permissions for the parent folder of the dashboard is edited in such a way that dashboard in that folder has a permission that is a duplicate of an inherited one. This PR changes so that duplicate permissions are now filtered out from `/api/dashboards/id/<dashboard id>/permissions`.

Duplicate permission are not filtered out if the permission on dashboard is higher than on the inherited folder.

**Which issue(s) this PR fixes**:
Fixes #33296 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Looks good!

File: pkg/services/guardian/guardian.go [hunk 1]
```diff
@@ -22,7 +22,14 @@ type DashboardGuardian interface {
...
 	HasPermission(permission models.PermissionType) (bool, error)
 	CheckPermissionBeforeUpdate(permission models.PermissionType, updatePermissions []*models.DashboardAcl) (bool, error)
+
+	// GetAcl returns ACL.
 	GetAcl() ([]*models.DashboardAclInfoDTO, error)
+
+	// GetAclWithoutDuplicates returns ACL and strips any permission
+	// that already has an inherited permission with higher or equal
+	// permission.
+	GetAclWithoutDuplicates() ([]*models.DashboardAclInfoDTO, error)
```
Comment (aknuds1) [inline pkg/services/guardian/guardian.go:32]: Nit, but initialisms should be in consistent case in Go:
```suggestion
	// GetACLWithoutDuplicates returns ACL and strips any permission
	// that already has an inherited permission with higher or equal
	// permission.
	GetACLWithoutDuplicates() ([]*models.DashboardAclInfoDTO, error)
```

File: pkg/services/guardian/guardian.go [hunk 2]
```diff
@@ -202,6 +209,42 @@ func (g *dashboardGuardianImpl) GetAcl() ([]*models.DashboardAclInfoDTO, error)
 	return g.acl, nil
 }
 
+func (g *dashboardGuardianImpl) GetAclWithoutDuplicates() ([]*models.DashboardAclInfoDTO, error) {
```
Comment (aknuds1) [inline pkg/services/guardian/guardian.go:212]:
```suggestion
func (g *dashboardGuardianImpl) GetACLWithoutDuplicates() ([]*models.DashboardAclInfoDTO, error) {
```

File: pkg/services/guardian/guardian_test.go [hunk 3]
```diff
@@ -726,3 +726,45 @@ func TestGuardianGetHiddenACL(t *testing.T) {
 		})
 	})
 }
+
+func TestGuardianGetAclWithoutDuplicates(t *testing.T) {
+	Convey("Get hidden ACL tests", t, func() {
```
Comment (aknuds1) [inline pkg/services/guardian/guardian_test.go:731]: Since you're adding a new test, can it be done without go-convey?

**Review by aknuds1 — APPROVED** [review]
LGTM, but see nits

File: pkg/api/dashboard_permission.go [hunk 4]
```diff
@@ -24,7 +24,7 @@ func (hs *HTTPServer) GetDashboardPermissionList(c *models.ReqContext) response.
 		return dashboardGuardianResponse(err)
 	}
 
-	acl, err := g.GetAcl()
+	acl, err := g.GetAclWithoutDuplicates()
```
Comment (marefr) [inline pkg/api/dashboard_permission.go:27]:
```suggestion
	acl, err := g.GetACLWithoutDuplicates()
```

File: pkg/services/guardian/guardian.go [hunk 5]
```diff
@@ -290,6 +333,10 @@ func (g *FakeDashboardGuardian) GetAcl() ([]*models.DashboardAclInfoDTO, error)
 	return g.GetAclValue, nil
 }
 
+func (g *FakeDashboardGuardian) GetAclWithoutDuplicates() ([]*models.DashboardAclInfoDTO, error) {
```
Comment (marefr) [inline pkg/services/guardian/guardian.go:336]:
```suggestion
func (g *FakeDashboardGuardian) GetACLWithoutDuplicates() ([]*models.DashboardAclInfoDTO, error) {
```

File: pkg/services/guardian/guardian_test.go (hunk 3 above)
Comment (marefr) [reply pkg/services/guardian/guardian_test.go]: Good catch. Fixed

**Review by aknuds1 — APPROVED** [review]
