### PR TITLE
fix: Explore -Tables missing vertical spacing

### LINKED ISSUE #78059: Explore: Tables are missing vertical spacing
In Explore, each visualization is displayed with some gap (8px wit the current theme) set by a common flex container. 
The table Viz however - being wrapped in another element - does not respect this when rendering multiple tables:

image

**How to reproduce:**
create 2 queries using `testdata`, `CSV Content` scenario and make sure that each table has different columns, ie:

Query A
```
A,B
A,B
```

Query V
```
C,D
C,D
```

### PR DESCRIPTION
**Pull request by aditipatelpro**
**What is this feature?**

It fixes missing vertical space between tables in the `Explore` component.

Screenshot 2023-11-15 at 3 18 28 PM

**Why do we need this feature?**

To fix the UI by adding back the space needed.

**Who is this feature for?**

All

**Which issue(s) does this PR fix?**:

Fixes #78059 

**Special notes for your reviewer:**

@Elfo404, could you please provide your feedback on this PR? 

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/explore/Table/TableContainer.tsx [hunk 1]
```diff
@@ -93,27 +93,29 @@ export class TableContainer extends PureComponent<Props> {
...
-                  data={data}
-                  width={innerWidth}
-                  height={innerHeight}
-                  onCellFilterAdded={onCellFilterAdded}
-                />
-              )}
-            </PanelChrome>
-          ))}
+        {frames && frames.length > 0 && (
+          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
```
Comment (Elfo404) [inline public/app/features/explore/Table/TableContainer.tsx:97]: this is grea! 

can we use the theme for this?
you can do that by using th `withTheme2` HOC:

```
export default withTheme2(connector(YourComponent));
```

then you'll have access to a `theme` prop, so here you can do something like 


```
<div className={css({ display: 'flex', flexDirection: 'column', gap: theme.spacing(1) })}>
```

you can have a look at `public/app/features/explore/Logs/LiveLogs.tsx` for a. more concrete example, or search for `withTheme2(` in the codebase, you should get quite a few results :)

lmk if that doesn't work

Comment (aditipatelpro) [reply public/app/features/explore/Table/TableContainer.tsx]: @Elfo404, Thanks for the feedback. I have used `withTheme2` and also updated the test.

**Review by Elfo404 — APPROVED** [review]
Thank you so much for this! 🚀
