### PR TITLE
Accessibility: Colorblind-safe line style fill patterns

### LINKED ISSUE #21120: Legal Requirement: Denotative colour coding for Colourblind Users
Those who have any difficulties distinguishing colour currently find Grafana difficult to use; when all colours look the same, there is no way to distinguish different series. Grafana should be designed for those who have [Monochromacy](https://en.wikipedia.org/wiki/Monochromacy), so that it is accessible to everyone.

**Steps to reproduce**:
All graphs use colour alone to distinguish information.

**Actual Result**:
All graphs use colour alone to distinguish information.

**Expected Result**
Color should not be used as the only visual means of conveying information. Graphs should include patterns _and_ colours to better enable all users to distinguish information.

This example is taken from [Trello](https://trello.com/). While Trello is an entirely separate entity, Trello cards can be categorised using patterns _and_ colours.
image

**Relevant WCAG Criteria:**

- [Use of Color](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#use-of-color): "_Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element._"
- [Colourblind Awareness in Business](http://www.colourblindawareness.org/business/)
- Many countries have legal accessibility requirements. The [UK Health and Safety
Executive](https://www.hse.gov.uk/pubns/web03.pdf), for example, requires that Connotative colour coding is redesigned to Denotative colour coding.

Grafana currently contravenes these.

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: mysql Ver 14.14
- User OS & Browser: Ubuntu & FireFox, Windows & Chrome

**Relates to:**
This issue is related to the following, though they do not go far enough for full colourblind accessibility.
- [13014](https://github.com/grafana/grafana/issues/13014)
- [18041](https://github.com/grafana/grafana/issues/18041)

### PR DESCRIPTION
**Pull request by vijaygovindaraja**
## What

Behind `enableColorblindSafePanelOptions` feature toggle

When the colorblind-safe color palette is active, each series automatically gets a distinct line pattern (solid, dash, dot, long-dash, dash-dot, etc.) on top of its unique color. This provides a second visual channel so series remain distinguishable even for users who cannot perceive color differences at all.

## Why

Color alone is not sufficient for accessibility (WCAG 1.4.1 — Use of Color). The colorblind palette (#121385) handles the color side, but users with severe color vision deficiency still benefit from shape/pattern differentiation. This is standard practice in scientific publishing (Wong 2011, Nature Methods).

## How it works

- 8 distinct line patterns cycle per series: solid, dash, dot, long-dash, dash-dot, wide-dot, short-gap, short-dash
- Only activates when the "Colorblind safe" color scheme is selected — no change for other palettes
- If a user manually sets a lineStyle override on a field, the override takes precedence
- Patterns show in both the chart lines and the legend

## Files changed

| File | Change |
|------|--------|
| `public/app/core/components/TimeSeries/utils.ts` | Auto-assign line pattern per series when colorblind palette is active |
| `public/app/core/components/TimeSeries/utils.test.ts` | 4 new tests for auto-pattern assignment, cycling, override behavior |

Depends on #121385

Fixes #21120

### CODE REVIEW

File: packages/grafana-ui/src/components/InteractiveTable/InteractiveTable.tsx [hunk 1]
```diff
@@ -278,13 +278,28 @@ export function InteractiveTable<TableData extends object>({
 
                   const headerTooltip = headerTooltips?.[column.id];
 
+                  const columnStyle: React.CSSProperties = {};
```
Comment (gtk-grafana) [inline packages/grafana-ui/src/components/InteractiveTable/InteractiveTable.tsx]: Interactive table changes are back

File: packages/grafana-data/src/themes/createVisualizationColors.ts [hunk 2]
```diff
@@ -344,6 +344,33 @@ function getClassicPalette() {
   ];
 }
 
+/**
+ * Colorblind-safe palette based on Wong (2011) "Points of view: Color blindness"
+ * Nature Methods 8:441. Extended with Okabe-Ito colors for additional series.
+ * These colors are distinguishable by people with all common forms of color
+ * vision deficiency (protanopia, deuteranopia, tritanopia).
+ */
+export function getColorblindPalette(): string[] {
```
Comment (gtk-grafana) [inline packages/grafana-data/src/themes/createVisualizationColors.ts]: let's pull the changes from https://github.com/grafana/grafana/pull/121385 out of this branch now that they are no longer dependent

File: public/app/core/components/TimeSeries/utils.ts [hunk 3]
```diff
@@ -30,6 +31,34 @@ import {
...
+/**
+ * Resolves the "colorblind" fill type into a concrete dash pattern per series.
+ * Non-colorblind line styles pass through unchanged.
+ */
+function resolveLineStyle(lineStyle: LineStyle | undefined, seriesIndex: number): LineStyle | undefined {
+  if (!lineStyle || lineStyle.fill !== 'colorblind') {
+    return lineStyle;
+  }
+  const pattern = COLORBLIND_LINE_PATTERNS[seriesIndex % COLORBLIND_LINE_PATTERNS.length];
+  return pattern.length === 0 ? { fill: 'solid' } : { fill: 'dash', dash: pattern };
```
Comment (gtk-grafana) [inline public/app/core/components/TimeSeries/utils.ts]: this is much harder to read then the previous implementation, let's define `COLORBLIND_LINE_PATTERNS` as an array of objects without any exception for fill by index

File: public/app/plugins/panel/timeseries/LineStyleEditor.tsx
Comment (gtk-grafana) [inline public/app/plugins/panel/timeseries/LineStyleEditor.tsx]: The current copy doesn't fit in the panel options sidebar, and this feature doesn't necessarily relate to colorblindness anymore, so we might want some different copy here, or we'll need to change the layout of this toggle.

Image

We'll need docs added for this change too, maybe @imatwawana has other some ideas on what we can call this that will fit in the current toggle

Comment (gtk-grafana) [inline public/app/plugins/panel/timeseries/LineStyleEditor.tsx]: "Auto" is a much better name for this option, as a nit it would be good to update the `LineFill` option to `auto` in the code as well

**Review by imatwawana — COMMENTED** [review]
The updates look good, but the graph-styles-options.md file is used in both the time series and trend visualizations and it looks like this change only applies to time series? Is that correct? Can it be extended to trend?

File: packages/grafana-ui/src/components/InteractiveTable/InteractiveTable.tsx (hunk 1 above)
Comment (vijaygovindaraja) [reply packages/grafana-ui/src/components/InteractiveTable/InteractiveTable.tsx]: Removed — branch is clean now, only the 6 line-pattern files remain.

File: packages/grafana-data/src/themes/createVisualizationColors.ts (hunk 2 above)
Comment (vijaygovindaraja) [reply packages/grafana-data/src/themes/createVisualizationColors.ts]: Done, palette changes are only in #121385 now.

File: public/app/core/components/TimeSeries/utils.ts (hunk 3 above)
Comment (vijaygovindaraja) [reply public/app/core/components/TimeSeries/utils.ts]: Refactored to a typed LineStyle[] array with no special index handling.

File: public/app/plugins/panel/timeseries/LineStyleEditor.tsx
Comment (vijaygovindaraja) [reply public/app/plugins/panel/timeseries/LineStyleEditor.tsx]: Renamed to Auto and added docs. Also confirmed this applies to trend panels too since they share getGraphFieldConfig.

**Comment by vijaygovindaraja** [comment]
Rebased on main, removed leaked files, and replied to all review threads. Ready for re-review.

File: docs/sources/shared/visualizations/graph-styles-options.md [hunk 4]
```diff
@@ -13,7 +13,7 @@ comments: |
 | Line width                                  | Set the thickness of the series lines or the outline for bars using the **Line width** slider. |
 | Fill opacity                                | Set the series area fill color using the **Fill opacity** slider. |
 | [Gradient mode](#gradient-mode)             | Choose a gradient mode to control the gradient fill, which is based on the series color. |
-| [Line style](#line-style)                   | Choose a solid, dashed, or dotted line style. |
+| [Line style](#line-style)                   | Choose a solid, dashed, dotted, or auto-patterned line style. |
```
Comment (gtk-grafana) [inline docs/sources/shared/visualizations/graph-styles-options.md]: revert all docs changes, we'll add them back after public preview

File: public/app/plugins/panel/timeseries/LineStyleEditor.tsx [hunk 5]
```diff
@@ -54,6 +55,14 @@ export const LineStyleEditor = ({ value, onChange }: Props) => {
       label: t('timeseries.line-style-editor.line-fill-options.label-dots', 'Dots'),
       value: 'dot',
     },
+    ...(config.featureToggles.enableColorblindSafePanelOptions
+      ? [
+          {
+            label: t('timeseries.line-style-editor.line-fill-options.label-auto', 'Auto'),
+            value: 'auto' as LineFill,
```
Comment (gtk-grafana) [inline public/app/plugins/panel/timeseries/LineStyleEditor.tsx]: don't add type assertions outside of tests, try something like this instead:


```
suggestion
  const lineFillOptions: Array<SelectableValue<LineFill>> = [
    {
      label: t('timeseries.line-style-editor.line-fill-options.label-solid', 'Solid'),
      value: 'solid',
    },
    {
      label: t('timeseries.line-style-editor.line-fill-options.label-dash', 'Dash'),
      value: 'dash',
    },
    {
      label: t('timeseries.line-style-editor.line-fill-options.label-dots', 'Dots'),
      value: 'dot',
    },
  ];
  if(config.featureToggles.enableColorblindSafePanelOptions){
    lineFillOptions.push({
      label: t('timeseries.line-style-editor.line-fill-options.label-auto', 'Auto'),
      value: 'auto',
    })
  }
```
```

File: public/app/plugins/panel/timeseries/LineStyleEditor.tsx [hunk 6]
```diff
@@ -55,6 +56,13 @@ export const LineStyleEditor = ({ value, onChange }: Props) => {
       value: 'dot',
     },
   ];
+
+  if (config.featureToggles.enableColorblindSafePanelOptions) {
+    lineFillOptions.push({
+      label: t('timeseries.line-style-editor.line-fill-options.label-auto', 'Auto'),
```
Comment (fastfrwrd) [inline public/app/plugins/panel/timeseries/LineStyleEditor.tsx]: we were commenting that "Auto" has a pretty specific meaning in Grafana, that pretty much always relates to a default value, so I really don't think we can call this "Auto" unless it becomes the default eventually. It's fine for now but expect that we'll change it, probably.

Comment (fastfrwrd) [reply public/app/plugins/panel/timeseries/LineStyleEditor.tsx]: tbf, if it became the default, then that would mean that anyone who had "solid" set will not have their panels change underneath them and would have to opt-in, which is... probably a good thing? hopefully?

File: packages/grafana-schema/src/common/mudball.cue [hunk 7]
```diff
@@ -38,7 +38,7 @@ ScaleDirection: 1 | 1 | -1 | -1 @cuetsy(kind="enum",memberNames="Up|Right|Down|L
 
 // TODO docs
 LineStyle: {
-	fill?: "solid" | "dash" | "dot" | "square"
+	fill?: "solid" | "dash" | "dot" | "square" | "auto"
```
Comment (fastfrwrd) [inline packages/grafana-schema/src/common/mudball.cue]: **This is the hold up for 13.0 for this PR, unfortunately.**

We spent some time spitballing what the ramifications of adding this now if we change our mind on the naming, behavior, etc. Ultimately, one of my key responsibilities is making sure my team's code is stable and reliable, and that we don't introduce changes that are going to need migrations later if they can be avoided. The fact is, we're about to do the release, so it's a bad idea to merge this at the 11th hour because it's adding to this enum is something of a one-way decision.

We discussed alternatives that didn't involve changing the model, or that used a temporary name of the option like `experimental-alternating`, but the fact still remains that if a release is out there in the world where a new value can be set on this field (even if it's behind a flag), and we still will have users who use the flag that we'll need to maintain a level of support for, so we want to be more confident in what we're doing before we go ahead.

We have time scheduled with our designer next week to look through this and the new palette and consider what the best path forward is for this and how we get it all to GA in an upcoming release, but we need to wait until 13.1 at least for this particular change.

**Review by fastfrwrd — CHANGES_REQUESTED** [review]
marking as request changes to put the PR on a "hold" until after 13.0; **I'm not actually requesting anything change other than the passage of time and getting past the 13.0 release cut.**

File: packages/grafana-schema/src/common/mudball.cue (hunk 7 above)
Comment (vijaygovindaraja) [reply packages/grafana-schema/src/common/mudball.cue]: makes sense, happy to wait for 13.1. let me know after the design review if anything needs to change on my end.

Comment (gtk-grafana) [reply packages/grafana-schema/src/common/mudball.cue]: @vijaygovindaraja 
Yeah @fastfrwrd is 100% correct to exercise caution here, any schema changes show up as options for folks using provisioning tools and we don't really have a good way to feature flag changes to existing panel options. 

Let's hold off on making more changes to this branch for now, we've got some time scheduled with UX to review these changes and I'll circle back once we have more alignment. This way we can make sure we get this implemented in a way that dataviz feels comfortable supporting and expanding without introducing costly/frustrating migrations to the public panel options API.

Sorry if I got your hopes up that this would land in 13.0, I believe that this is an extremely valuable feature and would love to continue working with you to continue making Grafana better for everyone!

Comment (vijaygovindaraja) [reply packages/grafana-schema/src/common/mudball.cue]: @gtk-grafana no worries at all, totally understand. i'll hold off until you circle back after the ux review.

Comment (gtk-grafana) [inline packages/grafana-schema/src/common/mudball.cue]:
```suggestion
	fill?: "solid" | "dash" | "dot" | "square" | "accessible"
```

And then run `make gen-cue` to update the generated files

File: public/app/plugins/panel/timeseries/LineStyleEditor.tsx (hunk 6 above)
Comment (gtk-grafana) [inline public/app/plugins/panel/timeseries/LineStyleEditor.tsx]:
```suggestion
      label: t('timeseries.line-style-editor.line-fill-options.label-accessible', 'Accessible'),
```

And then run `yarn i18n-extract`

File: public/app/core/components/TimeSeries/utils.test.ts [hunk 8]
```diff
@@ -398,3 +405,132 @@ describe('calculateAnnotationLaneSizes', () => {
...
+      getTimeRange: jest.fn(),
+      eventBus,
+      sync: jest.fn(),
+      allFrames: [frame],
+      renderers: [],
+    });
+  }
+
+  it('should assign different patterns per series when colorblind line style is selected', () => {
+    const builder = buildWithLineStyle({ fill: 'auto' }, 3);
```
Comment (gtk-grafana) [inline public/app/core/components/TimeSeries/utils.test.ts]: looks like these tests didn't get updated

File: public/app/core/components/TimeSeries/utils.ts [hunk 9]
```diff
@@ -30,6 +31,33 @@ import {
   type ScaleDistributionConfig,
 } from '@grafana/schema';
 
+/**
+ * Distinct line styles cycled per series when the "auto" line style is selected.
```
Comment (gtk-grafana) [inline public/app/core/components/TimeSeries/utils.ts]: looks like this file is missing some updates as well

File: public/app/plugins/panel/timeseries/LineStyleEditor.test.tsx [hunk 10]
```diff
@@ -0,0 +1,50 @@
...
+  beforeEach(() => {
+    originalEnableColorblindSafePanelOptions = config.featureToggles.enableColorblindSafePanelOptions;
+  });
+
+  afterEach(() => {
+    config.featureToggles.enableColorblindSafePanelOptions = originalEnableColorblindSafePanelOptions;
+  });
+
+  it.each([false, undefined])(
+    'does not show the Auto line fill option when enableColorblindSafePanelOptions is %s',
```
Comment (gtk-grafana) [inline public/app/plugins/panel/timeseries/LineStyleEditor.test.tsx]: more tests missed in auto -> accessible relabeling

**Comment by vijaygovindaraja** [comment]
@gtk-grafana Fixed the remaining auto -> accessible references in utils.ts, utils.test.ts. LineStyleEditor.test.tsx was already updated. Should be all clean now.

**Review by fastfrwrd — APPROVED** [review]

**Comment by fastfrwrd** [comment]
Thank you again @vijaygovindaraja 🎉
