### PR TITLE
Loki: Fix showing of unusable labels field in detected fields

### LINKED ISSUE #52455: Logs: Logs view in explore have unusable labels field.
Grafana version : 9.0.3
Datasource: loki

Lookout the detected fields section of the below screenshot. This is reproducible at [here](https://play.grafana.org/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bapp%3D%5C%22productpage%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221658230470884%22,%22to%22:%221658231441720%22%7D%7D). As the labels are already parsed, the redundant labels field can be removed from the detected fields section.

image

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
Based on multiple reports, seeing `labels` field in detected fields is confusing for users. This change came from https://github.com/grafana/grafana/pull/47153 and with @gabor we actually discussed if we should hide it or not, and we both decided against it. However, seeing how confusing it is for users, we should hide it.

To fix this, I have added it to the list of fields that should be hidden from detected fields. In the future, we should re-evaluate what should be shown in labels and what in detected fields, but this should work for now. 

I have also refactored how we determine if field should be hidden as it was becoming messy and added tests to test each scenario. 

**Which issue(s) this PR fixes**:

Fixes [#52455](https://github.com/grafana/grafana/issues/52455)

**Special notes for your reviewer**:

To test this:
1. Run loki data source `make devenv sources=loki` in Explore. 
2. After you run any query (e.g. `source="data"}`), open log details view by clicking on log row.
3. `labels      [Object object]` should not be in detected fields.

After: 
image

Before: 
image

### CODE REVIEW

File: packages/grafana-ui/src/components/Logs/logParser.ts [hunk 1]
```diff
@@ -99,3 +86,28 @@ function sortFieldsLinkFirst(fieldA: FieldDef, fieldB: FieldDef) {
   }
   return fieldA.key > fieldB.key ? 1 : fieldA.key < fieldB.key ? -1 : 0;
 }
+
+function shouldRemoveField(field: Field, index: number, row: LogRowModel) {
```
Comment (ivanahuckova) [inline packages/grafana-ui/src/components/Logs/logParser.ts:90]: This is a refactor of this logic + adding extra condition `field.name === 'labels' && field.type === FieldType.other`

```
filter(
          (field, index) => !('id' === field.name || row.entryFieldIndex === index || field.config.custom?.hidden)
        )
        // Filter out fields without values. For example in elastic the fields are parsed from the document which can
        // have different structure per row and so the dataframe is pretty sparse.
        .filter((field) => {
          const value = field.values.get(row.rowIndex);
          // Not sure exactly what will be the empty value here. And we want to keep 0 as some values can be non
          // string.
          return value !== null && value !== undefined;
        })
```

File: packages/grafana-ui/src/components/Logs/logParser.ts [hunk 2]
```diff
@@ -99,3 +86,28 @@ function sortFieldsLinkFirst(fieldA: FieldDef, fieldB: FieldDef) {
...
+  // entry field which we are showing as the log message
+  if (row.entryFieldIndex === index) {
+    return true;
+  }
+  // hidden field
+  if (field.config.custom?.hidden) {
+    return true;
+  }
+  // field that has empty value (we want to keep 0 or empty string)
+  if (field.values.get(row.rowIndex) == null) {
```
Comment (matyax) [inline packages/grafana-ui/src/components/Logs/logParser.ts:109]:
```suggestion
  if (field.values.get(row.rowIndex) === null || field.values.get(row.rowIndex) === undefined) {
```

I'm surprised no linter complained about using strict equality (===). Do we not consider it a bad practice in Grafana?

File: packages/grafana-ui/src/components/Logs/logParser.test.ts [hunk 3]
```diff
@@ -0,0 +1,170 @@
...
+};
+
+const testFieldWithNullValue = {
+  name: 'test_field_null',
+  type: FieldType.string,
+  config: {},
+  values: new ArrayVector([null]),
+};
+
+const createLogRow = (overrides?: Partial<LogRowModel>): LogRowModel => {
```
Comment (matyax) [inline packages/grafana-ui/src/components/Logs/logParser.test.ts:150]: Would it make sense to move this to a common module? Just checking, because it seems like it could be used in a couple of places.

**Review by matyax — COMMENTED** [review]
Looks great! Left a couple of comments.

File: packages/grafana-ui/src/components/Logs/logParser.test.ts (hunk 3 above)
Comment (ivanahuckova) [reply packages/grafana-ui/src/components/Logs/logParser.test.ts]: Updated in https://github.com/grafana/grafana/pull/53319/commits/553b72ba2cc08312caf7c9a29352ff3dfc2f2768. I have created mock and used it for all of the tests in  Logs folder.

**Comment by ivanahuckova** [comment]
> Curious if you considered keeping the labels field

Yes we talked about it, but it wouldn't be preferred option as we already display labels in `Labels` field above.
image

We want to improve/re-think detected fields as we are currently mixing there 2 sources - dataframe fields and key-value pairs from log line. In the future, we want to have here only key-value pairs from log line, but this requires more work. You can check out more about this in https://docs.google.com/document/d/1sEiXv35UK5uEtG2ycofRrdTm5YCXs2V4ExB7bEyh7Ng/edit and search for "detected fields".

File: packages/grafana-ui/src/components/Logs/logParser.ts (hunk 2 above)
Comment (matyax) [reply packages/grafana-ui/src/components/Logs/logParser.ts:109]: Gotcha, thanks for clarifying!

**Review by matyax — APPROVED** [review]
Great work!
