### PR TITLE
Alerting: Support filtering of alerts by state and labels

### LINKED ISSUE #65582: Add server-side filtering to the alert rules endpoint
### Filtering

In order to support limits on alert instances in the alert list panel, the following server-side filters should be implemented:

#### Alert and instance state

Support for following state filter values

```
firing: boolean;
pending: boolean;
inactive?: boolean; // backwards compatability, alias for normal
noData: boolean;
normal: boolean;
error: boolean;
```

`firing`, `pending` and `normal / inactive` are first applied to the state of the alert rule. The other states are ignored.

Then apply filtering to the alert instances for the filtered set of alert rules. All of the state filters above should be supported.

The default state filters are 

```
Alerting / Firing
Pending
Error
```

#### Alert instance label filters

Apply instance label filters to all instance in alerts. Supported syntax is the same as prometheus label matchers (support for all matchers `=`, `!=`, `=~`, `!~`).

#### A combination of the above

Always filter out alert rules with 0 instances matching the filters above.

If a combination of state filter and instance label filter are combined, it is possible that alert rules with 0 matching instances are returned. 

We omit these from the alert list panel because they might show as false positives.

See [this PR](https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/components/rules/RuleState.tsx#L25-L52) for an example / valid use-case.

If there are additional instances in an alert rule that don't match the state or instance label filter, we show "x hidden by filters".

### Sorting

The following sorting should be supported on the backend because they use alert instances for sorting:

1. `Time (asc)`
2. `Time (desc)`

This can be done by updating the alert rule property `activeAt` or something similar.

### Additional

To compute the "Firing for x time" we traverse the list of instances and figure it out from the earliest firing alert.

See [this piece of code](https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/components/rules/RuleState.tsx#L25-L52).

_Originally posted by @gillesdemey in https://github.com/grafana/grafana/issues/65071#issuecomment-1485462015_

### PR DESCRIPTION
**Pull request by grobinson-grafana**
**What is this feature?**

This pull request adds support for filtering alerts by state and labels (#65582).

Alerts can be filtered by state with the `state` query string. An example of an HTTP request asking for just firing alerts might be `/api/prometheus/grafana/api/v1/rules?state=alerting`. A request can filter by two or more states by adding additional `state` query strings to the URL. For example `?state=alerting&state=normal`.

Like the alert list panel, the `firing`, `pending` and `normal` state are first compared against the state of each alert rule. All other states are ignored. If the alert rule matches then its alert instances are filtered against states once more.

Alerts can also be filtered by labels using the `matcher` query string. Like `state`, multiple matchers can be provided by adding additional `matcher` query strings to the URL.

The match expression should be parsed using existing regular expression and sent to the API as URL-encoded JSON in the format:

```
{
    "name": "test",
    "value": "value1",
    "isRegex": false,
    "isEqual": true
}
```

An example of how this would look is `/api/prometheus/grafana/api/v1/rules?matcher=%7B%22name%22:%20%22test%22%2C%22value%22:%22value1%22%2C%22isRegex%22:false%2C%22isEqual%22:true%7D%0A` for the matcher `test=value1`.

The `isRegex` and `isEqual` options work as follows:

| IsEqual | IsRegex  | Operator |
| ------- | -------- | -------- |
| true    | false    |    =     |
| true    | true     |    =~    |
| false   | true     |    !~    |
| false   | false    |    !=    |

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #65582

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/services/ngalert/api/api_prometheus.go [hunk 1]
```diff
@@ -190,14 +240,39 @@ func (srv PrometheusSrv) RouteGetRuleStatuses(c *contextmodel.ReqContext) respon
...
+				if state != nil {
+					if _, ok := withStatesFast[*state]; ok {
+						filteredRules = append(filteredRules, rule)
+					}
+				}
+			}
+			ruleGroup.Rules = filteredRules
+		}
+
+		if limitRulesPerGroup > -1 && int64(len(rules)) > limitRulesPerGroup {
```
Comment (JacobsonMT) [inline pkg/services/ngalert/api/api_prometheus.go:272]: I think this should read:
```suggestion
		if limitRulesPerGroup > -1 && int64(len(ruleGroup.Rules)) > limitRulesPerGroup {
```

Otherwise, you'll extend the slice passed its length with zeroed structs when `len(rules)` > `limitRulesPerGroup` > `len(filteredRules)`

image

File: pkg/services/ngalert/api/api_prometheus.go [hunk 2]
```diff
@@ -291,6 +366,20 @@ func (srv PrometheusSrv) toRuleGroup(groupKey ngmodels.AlertRuleGroupKey, folder
 				newRule.Health = "error"
 			}
 
+			if len(withStates) > 0 {
+				if _, ok := withStates[alertState.State]; !ok {
+					continue
+				}
+			}
+
+			lbs := make(model.LabelSet)
```
Comment (JacobsonMT) [inline pkg/services/ngalert/api/api_prometheus.go:375]: NIT: Surrounding in an empty check can save some unnecessary `LabelSet` creation if there are no `matchers`

**Review by JacobsonMT — APPROVED** [review]
Overall, I think I have a slight preference for extracting the new limit/filtering/counting code to a separate function(s) to be done at the end of `RouteGetRuleStatuses`. Yes, it will be less efficient but it seems like these methods have a lot of concerns all being done at once. It might benefit from simplification in this respect.

That being said, this LGTM as is (with a couple NITs mentioned below)

File: pkg/services/ngalert/api/api_prometheus.go [hunk 3]
```diff
@@ -190,14 +240,39 @@ func (srv PrometheusSrv) RouteGetRuleStatuses(c *contextmodel.ReqContext) respon
...
-		}
+		ruleGroup, totals := srv.toRuleGroup(groupKey, folder, rules, limitAlertsPerRule, withStatesFast, matchers, labelOptions)
 		ruleGroup.Totals = totals
 		for k, v := range totals {
 			rulesTotals[k] += v
 		}
+
+		if len(withStates) > 0 {
+			// Filtering is weird but firing, pending, and normal filters also need to be
+			// applied to the rule. Others such as nodata and error should have no effect.
```
[the remark this answers is not in the document]
Comment (grobinson-grafana) [reply pkg/services/ngalert/api/api_prometheus.go:251]: Done! 🙂

File: pkg/services/ngalert/api/api_prometheus.go (hunk 2 above)
Comment (grobinson-grafana) [reply pkg/services/ngalert/api/api_prometheus.go]: Done! 🙂

File: pkg/services/ngalert/api/api_prometheus.go [hunk 4]
```diff
@@ -291,6 +367,22 @@ func (srv PrometheusSrv) toRuleGroup(groupKey ngmodels.AlertRuleGroupKey, folder
...
+			}
+
+			if len(matchers) > 0 {
+				lbs := make(model.LabelSet)
+				for k, v := range alertState.Labels {
+					lbs[model.LabelName(k)] = model.LabelValue(v)
+				}
+				if !matchers.Matches(lbs) {
+					continue
+				}
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/api/api_prometheus.go:383]: Method `labels.Matchers.Matches` is very simple 
```
// Matches checks whether all matchers are fulfilled against the given label set.
func (ms Matchers) Matches(lset model.LabelSet) bool {
	for _, m := range ms {
		if !m.Matches(string(lset[model.LabelName(m.Name)])) {
			return false
		}
	}
	return true
}
```
and uses a string. So, if we implement our own `Matchers` that accepts `data.Labels` then we can avoid copying maps.

**Comment by VikaCep** [comment]
Hey @grobinson-grafana has anything changed regarding filtering by matchers where the label value contains white spaces? For some reason this isn't returning results:

`&matcher=grafana_folder%3Dgdev%20dashboards`
image

when I have instances with that label
image

**Comment by grobinson-grafana** [comment]
> Hey @grobinson-grafana has anything changed regarding filtering by matchers where the label value contains white spaces? For some reason this isn't returning results:
> 
> `&matcher=grafana_folder%3Dgdev%20dashboards` image
> 
> when I have instances with that label image

We are using Alertmanager for label matching, but it sounds like it's too limited as it doesn't support spaces 🙁 . I was hoping we wouldn't need to build our own, but it now seems like we will.

File: pkg/services/ngalert/api/api_prometheus.go [hunk 5]
```diff
@@ -105,6 +108,41 @@ func getPanelIDFromRequest(r *http.Request) (int64, error) {
 	return 0, nil
 }
 
+func getMatchersFromRequest(r *http.Request) (labels.Matchers, error) {
+	var matchers labels.Matchers
+	for _, s := range r.URL.Query()["matcher"] {
+		m, err := labels.ParseMatcher(s)
```
[the remark this answers is not in the document]
Comment (grobinson-grafana) [reply pkg/services/ngalert/api/api_prometheus.go:114]: Thanks Yuri! It looks like this doesn't work in the UI either, so I'm inclined to merge this PR as-is and come back and fix this later.

File: pkg/services/ngalert/api/api_prometheus.go (hunk 4 above)
Comment (grobinson-grafana) [reply pkg/services/ngalert/api/api_prometheus.go:383]: OK, will do! 🙂
