### PR TITLE
Alerting: Fix evaluation interval validation

### LINKED ISSUE #55357: UI Bug, Alert Creation: "Evaluate every:" with non number input blocks the whole page
**What happened**:

When I enter anything in the field that does start with a number, the UI immediately displays an error and I can do nothing but reload the page or navigate away otherwise.

CleanShot 2022-09-19 at 09 32 33

**What you expected to happen**:

The UI might only mark the field as invalid instead of blocking the whole page.

**How to reproduce it (as minimally and precisely as possible)**:

Tab or click into the <kbd>Evaluate every </kbd>-input widget and delete the `1` that's there by default, or enter anything that does not start with a number.

**Environment**:
- Grafana version: 9.1.5
- Data source type & version: Prometheus 
- OS Grafana is installed on: Ubuntu, Running in a docker container
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

### PR DESCRIPTION
**Pull request by konrad147**
**What this PR does / why we need it**:
This PR fixes evaluation interval validation

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/55357, https://github.com/grafana/grafana/issues/55649

**Special notes for your reviewer**:
~WIP: Prometheus validation regex doesn't play well in JS~

### CODE REVIEW

**Comment by gillesdemey** [comment]
I had some time to play around with a parser that I think could work to parse this type of duration

https://gist.github.com/gillesdemey/6c251dc4f810d8e60ec2958eb9aa7225

**Comment by gillesdemey** [comment]
I've appended some changes that should correctly validate:

* If `interval` and `for` are valid "prometheus duration" strings (such as `1d30m10s`)
* Compare `interval` and `for` with eachother
* Compare `interval` with the global `min_interval`

**Review by gillesdemey — APPROVED** [review]
LGTM but my review is slightly biased :)

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 1]
```diff
@@ -25,38 +21,52 @@ const forValidationOptions = (evaluateEvery: string): RegisterOptions => ({
...
     message: 'Required.',
   },
-  pattern: positiveDurationValidationPattern,
   validate: (value: string) => {
-    const duration = parseDuration(value);
-    if (Object.keys(duration).length) {
-      const diff = durationToMilliseconds(duration);
-      if (diff < MIN_TIME_RANGE_STEP_S * 1000) {
+    try {
+      const duration = parsePrometheusDuration(value);
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:56]: I would name this const  with`millisEvery` or `millisEvaluateEvery` to be consistent with the  `For`, and I think it would be more clear

File: public/app/features/alerting/unified/utils/time.ts [hunk 2]
```diff
@@ -21,22 +28,78 @@ export const timeOptions = Object.entries(TimeOptions).map(([key, value]) => ({
...
-export const positiveDurationValidationPattern = {
-  value: new RegExp(`^\\d+(${Object.values(TimeOptions).join('|')})$`),
-  message: `Must be of format "(number)(unit)" , for example "1m". Available units: ${Object.values(TimeOptions).join(
-    ', '
-  )}`,
+export function parseDurationToMilliseconds(duration: string) {
+  return durationToMilliseconds(parseDuration(duration));
+}
+
+export function isValidPrometheusDuration(duration: string): boolean {
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/utils/time.ts:35]: 👏

File: public/app/features/alerting/unified/components/rules/RuleConfigStatus.tsx [hunk 3]
```diff
@@ -15,7 +15,10 @@ interface RuleConfigStatusProps {
 export function RuleConfigStatus({ rule }: RuleConfigStatusProps) {
   const styles = useStyles2(getStyles);
 
-  const { exceedsLimit } = checkEvaluationIntervalGlobalLimit(rule.group.interval);
+  const { exceedsLimit } = useMemo(
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/components/rules/RuleConfigStatus.tsx:18]: 💡

**Review by soniaAguilarPeiron — APPROVED** [review]
LGTM! 🎉
I added a non-blocking comment 👀

File: public/app/features/alerting/unified/utils/config.ts [hunk 4]
```diff
@@ -8,19 +8,19 @@ export function getAllDataSources(): Array<DataSourceInstanceSettings<DataSource
 }
 
 export function checkEvaluationIntervalGlobalLimit(alertGroupEvaluateEvery?: string) {
-  // There is a discrepancy between the duration format for evaluateEvery and unifiedAlerting.minInterval
-  // "evaluateEvery" is a Prometheus duration and supports d, w, y – "minInterval" is
-  // a strict golang time.ParseDuration compatible format
-  if (!alertGroupEvaluateEvery || !isValidPrometheusDuration(alertGroupEvaluateEvery)) {
+  // config.unifiedAlerting.minInterval should be Prometheus-compatible duration
+  // However, Go's gtime library has issues with parsing y,w,d
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/utils/config.ts:12]: Technically it's our own `grafana-sdk-go`'s `gtime` package :D

**Review by gillesdemey — APPROVED** [review]

File: public/app/features/alerting/unified/utils/config.ts (hunk 4 above)
Comment (konrad147) [reply public/app/features/alerting/unified/utils/config.ts:12]: Hmm, so why can't we fix it? 😄

Comment (gillesdemey) [reply public/app/features/alerting/unified/utils/config.ts:12]: I think that might introduce some unwanted side-effects :D
