### PR TITLE
Fix: DataLinks from data sources override user defined data link

### LINKED ISSUE #26762: DataLinks from data sources override user defined data link
**What happened**: Updated from 7.0.6 to 7.1.1 and DataLinks from Stat Panels on our dashboard using Log Analytics queries all reverted to "View in Azure Portal" ignoring the existing Datalink

**What you expected to happen**: It should render the Datalink correctly and open the correct link in a new tab

**How to reproduce it (as minimally and precisely as possible)**: Create a Panel that uses an Azure Log Analytics query and try set and follow the Datalink

**Anything else we need to know?**: Panel Links still work fine

**Environment**:
- Grafana version: v7.1.1 (3039f9c3bd)
- Data source type & version: Azure Log Analytics
- OS Grafana is installed on: Ubuntu 16.04.6 LTS
- User OS & Browser: Edge Chromium/FireFox 
- Grafana plugins: Azure Monitor 0.3.0

Example
datalinks

Actual link
datalinks2

- Others:

### PR DESCRIPTION
**Pull request by axelavargas**
**What is this feature?**

Merge data links when they come from datasource config and panel config

https://user-images.githubusercontent.com/239999/230040963-833fbb1d-2ee4-48ab-9c3a-6f88080f339b.mp4

**How to test this bug?**

Follow the instructions from the escalation https://github.com/grafana/support-escalations/issues/5036 

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #26762

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: packages/grafana-data/src/field/fieldOverrides.ts [hunk 1]
```diff
@@ -290,10 +290,42 @@ export function setDynamicConfigValue(config: FieldConfig, value: DynamicConfigV
   }
 }
 
+/**
+ * Merge the links from the ds config and the panel config
```
Comment (dprokop) [inline packages/grafana-data/src/field/fieldOverrides.ts:294]:
```suggestion
 * Merge the links from the data source config and the panel config
```

File: packages/grafana-data/src/field/fieldOverrides.ts [hunk 2]
```diff
@@ -290,10 +290,42 @@ export function setDynamicConfigValue(config: FieldConfig, value: DynamicConfigV
...
+ * @param configLinks coming from the datasource
+ * @param defaultLinks coming from the panel config
+ * @returns unique merged links
+ */
+
+function mergeLinks(configLinks: DataLink[], defaultLinks: DataLink[]) {
```
Comment (dprokop) [inline packages/grafana-data/src/field/fieldOverrides.ts:300]:
```suggestion
function mergeLinks(dataSourceLinks: DataLink[], defaultLinks: DataLink[]) {
```

Comment (dprokop) [reply packages/grafana-data/src/field/fieldOverrides.ts:300]: Please apply this feedback to all places where data source provided links are named `config links`

File: packages/grafana-data/src/field/fieldOverrides.ts [hunk 3]
```diff
@@ -290,10 +290,42 @@ export function setDynamicConfigValue(config: FieldConfig, value: DynamicConfigV
...
+}
+
 // config -> from DS
 // defaults -> from Panel config
 export function setFieldConfigDefaults(config: FieldConfig, defaults: FieldConfig, context: FieldOverrideEnv) {
   for (const fieldConfigProperty of context.fieldConfigRegistry.list()) {
+    // For cases where we have links on the datasource config and the panel config, we need to merge them
+    if (config.links && defaults.links) {
+      config.links = mergeLinks(config.links, defaults.links);
+    }
```
Comment (dprokop) [inline packages/grafana-data/src/field/fieldOverrides.ts:327]: Why is this done within the loop? It's something that doesn't seem like fieldConfigProperty dependant.

Comment (dprokop) [reply packages/grafana-data/src/field/fieldOverrides.ts:327]: It looks like this might be the reason you need to deduplicate the links in merge. `setFieldConfigDefaults` is called once per each field, so I don't see any other reason why links would be duplicated there.

Comment (ivanortegaalba) [reply packages/grafana-data/src/field/fieldOverrides.ts:327]: I was checking this also. I see also the function `applyFieldConfigDefaults`, which I think is meant to do the merging between the passed config and the default one (correct me if I'm wrong).

So, maybe that's the place to do this operation. WDYT?

Comment (dprokop) [reply packages/grafana-data/src/field/fieldOverrides.ts:327]: No, I don't think so. That function is building the field configuration _of the panel_. What we are looking for here is the _actual application of that field config on Fields_. Panel's field config is considered a source that is later on applied to particular fields. So there are two sources of the field config - it's Panel and the raw data directly returned from the data source. And these are not known to each other until `PQR.getData`.

Comment (axelavargas) [reply packages/grafana-data/src/field/fieldOverrides.ts:327]: @dprokop good catch! I missed completely the loop 🙈

File: packages/grafana-data/src/field/fieldOverrides.ts [hunk 4]
```diff
@@ -290,9 +290,25 @@ export function setDynamicConfigValue(config: FieldConfig, value: DynamicConfigV
...
+ * @param dataSourceLinks coming from the datasource
+ * @param defaultLinks coming from the panel config
+ * @returns merged links
+ */
+
+function mergeLinks(dataSourceLinks: DataLink[], defaultLinks: DataLink[]) {
+  // Combine the config links and the default links
+  return [...dataSourceLinks, ...defaultLinks];
+}
+
```
Comment (dprokop) [inline packages/grafana-data/src/field/fieldOverrides.ts:304]: This function does not make much sense to be defined. Let's just add the spreads inline, shall we? With an appropriate comment.

**Review by dprokop — APPROVED** [review]
Tested with the attached dashboard[1] and it works as expected!

<details>
<summary>[1] dashboard.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 2093,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "gdev-testdata"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "links": [
            {
              "title": "Test",
              "url": "sjdhajsd"
            }
          ],
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 12,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "gdev-testdata"
          },
          "rawFrameContent": "[\n  {\n    \"schema\": {\n      \"refId\": \"A\",\n      \"fields\": [\n        {\n          \"name\": \"time\",\n          \"type\": \"time\",\n          \"typeInfo\": {\n            \"frame\": \"time.Time\",\n            \"nullable\": true\n          },\n          \"config\": {\n            \"interval\": 10000\n          }\n        },\n        {\n          \"name\": \"A-series\",\n          \"type\": \"number\",\n          \"typeInfo\": {\n            \"frame\": \"float64\",\n            \"nullable\": true\n          },\n          \"labels\": {},\n          \"config\": {\n              \"links\": [\n              {\n                \"title\": \"Google link\",\n                \"url\": \"https://google.com\"\n              },\n              {\n                \"title\": \"Grafana\",\n                \"url\": \"https://grafana.com\"\n              }\n            ]\n          }\n        }\n      ]\n    },\n    \"data\": {\n      \"values\": [\n        [\n          1680672489402,\n          1680672499402,\n          1680672509402,\n          1680672519402,\n          1680672529402\n        ],\n        [\n          63.570662968338965,\n          63.41326491635544,\n          63.007634586960044,\n          62.54583246060652,\n          62.60740530516958\n        ]\n      ]\n    }\n  }\n]",
          "refId": "A",
          "scenarioId": "raw_frame"
        }
      ],
      "title": "No override",
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "testdata",
        "uid": "gdev-testdata"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "links": [
            {
              "title": "Test",
              "url": "sjdhajsd"
            }
          ],
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "A-series"
            },
            "properties": [
              {
                "id": "links",
                "value": [
                  {
                    "title": "Link from overrides",
                    "url": "asdasdasdasda"
                  }
                ]
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 12,
        "w": 24,
        "x": 0,
        "y": 12
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "gdev-testdata"
          },
          "rawFrameContent": "[\n  {\n    \"schema\": {\n      \"refId\": \"A\",\n      \"fields\": [\n        {\n          \"name\": \"time\",\n          \"type\": \"time\",\n          \"typeInfo\": {\n            \"frame\": \"time.Time\",\n            \"nullable\": true\n          },\n          \"config\": {\n            \"interval\": 10000\n          }\n        },\n        {\n          \"name\": \"A-series\",\n          \"type\": \"number\",\n          \"typeInfo\": {\n            \"frame\": \"float64\",\n            \"nullable\": true\n          },\n          \"labels\": {},\n          \"config\": {\n              \"links\": [\n              {\n                \"title\": \"Google link\",\n                \"url\": \"https://google.com\"\n              },\n              {\n                \"title\": \"Grafana\",\n                \"url\": \"https://grafana.com\"\n              }\n            ]\n          }\n        }\n      ]\n    },\n    \"data\": {\n      \"values\": [\n        [\n          1680672489402,\n          1680672499402,\n          1680672509402,\n          1680672519402,\n          1680672529402\n        ],\n        [\n          63.570662968338965,\n          63.41326491635544,\n          63.007634586960044,\n          62.54583246060652,\n          62.60740530516958\n        ]\n      ]\n    }\n  }\n]",
          "refId": "A",
          "scenarioId": "raw_frame"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "refresh": "",
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "2023-04-05T05:27:25.678Z",
    "to": "2023-04-05T05:29:26.999Z"
  },
  "timepicker": {},
  "timezone": "",
  "title": "DS links",
  "uid": "f2f0f196-2224-4fe8-9fee-e9d2c4f46cad",
  "version": 6,
  "weekStart": ""
}
```
</details>

**Review by aangelisc — APPROVED** [review]
Great stuff @axelavargas, thank you for solving this 😊
