### PR TITLE
TableNG: Fix sparkline sorting + column key config

### LINKED ISSUE #104013: TableNG: Fix sparkline sorting
Sorting is broken for Sparklines

### LINKED ISSUE #104014: TableNG: Support duplicate column names
Two column names can be the same, right now we don't support that. We need to change the way we're implementing column keys.

### PR DESCRIPTION
**Pull request by alexjonspencer1**
## What does this PR do?

I've separated each fix into its own commit for ease of review!

1. Fixes sparkline sorting. Sparkline has a different cell value data structure than other cells. It appears to be some form of DataFrame, and we need to sort on `a.value` and `b.value` instead of just `a` and `b`. Open to suggestions on how to improve this.

Test with: [Table Sparklines and more-1744662488285.json](https://github.com/user-attachments/files/19742936/Table.Sparklines.and.more-1744662488285.json)

2. Our column key definitions are not sufficiently unique. We are currently use key `field.name`, but there are cases where column names can be the same, or at least we don't prevent the user from naming columns the same thing. So default to `field.state.displayName ?? field.name`. 

Test with: [Two columns same name-1744662480983.json](https://github.com/user-attachments/files/19742948/Two.columns.same.name-1744662480983.json)

Fixes: #104013
Fixes: #104014

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/TableNG/Cells/HeaderCell.tsx [hunk 1]
```diff
@@ -52,10 +52,10 @@ const HeaderCell: React.FC<HeaderCellProps> = ({
     isColumnFilterable = field.config.custom?.filterable || false;
   }
   // we have to remove/reset the filter if the column is not filterable
-  if (!isColumnFilterable && filter[field.name]) {
+  if (!isColumnFilterable && filter[field.state?.displayName ?? field.name]) {
```
Comment (adela-almasan) [inline packages/grafana-ui/src/components/Table/TableNG/Cells/HeaderCell.tsx:55]: not a big deal but can we extract the field name in utils or somewhere else? this seems very repetitive - `field.state?.displayName ?? field.name`

**Review by adela-almasan — APPROVED** [review]
left a comment but otherwise looks good!

File: packages/grafana-ui/src/components/Table/TableNG/Cells/HeaderCell.tsx (hunk 1 above)
Comment (alexjonspencer1) [reply packages/grafana-ui/src/components/Table/TableNG/Cells/HeaderCell.tsx]: Good idea! Updated.
