### PR TITLE
Accessibility: Improve landmark markup

### LINKED ISSUE #79521: [accessibility issue] Landmarks are missing and incorrectly marked up
**Steps to reproduce**:
Go to a Grafana instance (e.g. play.grafana.com). Activate your screenreader or open your dev tools and inspect the accessibility tree. Notice:

- a `header` element is not defined even though we clearly have a header
- the `main` element is marked up incorrectly (I would expect it to be on the `id="pageContent"` as that is where the skip to content link moves focus to
- on the welcome page there is an empty `section` labelled `Dashboard submenu` (if empty it should not render)
- the blog posts widget are articles with no `aria-describedby` pointing to the blog post titles.

**Expected Result**
- Should have a `header` element.
- Correctly define `main` (if you use it to anchor it is effectively the same as going to navigation so is pointless as it stands)
- Remove empty sections
- Add labels to repeated landmarks

A screenshot of the VoiceOver rotor on the landmarks menu demonstrating the errors listed above.

UHG Audit ID: 1.31131

### PR DESCRIPTION
**Pull request by tskarhed**
**What is this feature?**

Changes faulty landmarks and adds some where it is needed.

- Adds a global `header`
- Correctly marks up `main`
- Only renders Submenu if it is supposed to be visible
- Fixes issue where article doesn't get a label from the `h3`

**Why do we need this feature?**

WCAG compliance

**Who is this feature for?**

Screen reader users

**Which issue(s) does this PR fix?**:

Fixes #79521

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard/components/SubMenu/SubMenu.tsx [hunk 1]
```diff
@@ -51,10 +51,6 @@ class SubMenuUnConnected extends PureComponent<Props> {
 
     const styles = getStyles(theme);
 
-    if (!dashboard.isSubMenuVisible()) {
-      return null;
-    }
-
```
Comment (tskarhed) [inline public/app/features/dashboard/components/SubMenu/SubMenu.tsx:57]: Since it is only used in DashboardPage, I'd figured moving the logic there instead made more sense.

File: public/app/features/dashboard/containers/DashboardPage.test.tsx [hunk 2]
```diff
@@ -322,7 +322,6 @@ describe('DashboardPage', () => {
     it('should render dashboard page toolbar and submenu', async () => {
       setup({ dashboard: getTestDashboard() });
       expect(await screen.findAllByTestId(selectors.pages.Dashboard.DashNav.navV2)).toHaveLength(1);
-      expect(screen.getAllByLabelText(selectors.pages.Dashboard.SubMenu.submenu)).toHaveLength(1);
```
Comment (tskarhed) [inline public/app/features/dashboard/containers/DashboardPage.test.tsx:325]: Please correct me on this, but in this case the dashboard doesn't have anything that is supposed to be displayed in the submenu? Should I add some of that data to the dashboard setup instead?

**Review by ckbedwell — APPROVED** [review]
LGTM! 💪 

So satisfying being able to navigate around using the landmarks correctly now :D

File: public/app/features/dashboard/containers/DashboardPage.test.tsx (hunk 2 above)
Comment (axelavargas) [reply public/app/features/dashboard/containers/DashboardPage.test.tsx:325]: Hey @tskarhed 👋🏾 , that's an interesting finding.

I wonder if the `dashboard setup` somehow configures something?

I know that the submenu is rendered if we have links, annotations or variables. Is it maybe the built-in annotation that is being configured?

Comment (tskarhed) [reply public/app/features/dashboard/containers/DashboardPage.test.tsx:325]: Yeah, the test failed, which means that the SubMenu component returned `null` previously, just having the `section` element empty. Which means that this assertion would always pass as true, unless you were in edit mode or kiosk mode, regardless of the content of the submenu.

Comment (tskarhed) [reply public/app/features/dashboard/containers/DashboardPage.test.tsx:325]: But based on the test, I should probably add something to the setup that makes the submenu display.

Comment (axelavargas) [reply public/app/features/dashboard/containers/DashboardPage.test.tsx:325]: Yes, maybe a quick change will be to add links. 🙃

**Comment by tskarhed** [comment]
@axelavargas I changed the test to make sure that submenu is not shown. There is no testing in regards to template variables or annotations in this specific suite, so I figured it is out of scope for this PR.

**Review by axelavargas — APPROVED** [review]
