### PR TITLE
Units: Format currency with negative before the symbol

### LINKED ISSUE #65123: Stat Panel: Single value formatting for prefix/suffix inconsistent with "accepted/common/traditional" ways of formatting values, specifically currency
**What happened**:

A BI user noticed that our Stat Panel, when a standard currency unit is chosen, formats values in a way that is "non-traditional". Instead of `-$372k` (traditional numerical formatting), it formats to `$-372k`.

**What you expected to happen**:

`-$372k` instead of `$-372k`.

**How to reproduce it (as minimally and precisely as possible)**:

Open any dashboard that includes a stat panel ->  click "edit" in the top panel dropdown -> navigate to "standard options" section -> click "unit" dropdown -> click "Currency" -> add a currency unit. Any negative value should show the above issue.

**Anything else we need to know?**:
image

NOTE: this was not mentioned as high priority, just something the user wanted to bring to our attention. I have spent some time with formatting in the stat panel, and this issue is a complex one to fix. When the value gets formatted, prefixes/suffixes get prepended/appended to the core `text` value without consideration of edge-case "standard practices"; in this case, the `text` value is `-372_000`, which I *believe* the formatter automatically formats to `-372k`. Then, the `prefix` value of `$` is simply prepended. This is how all unit values in the standard options work. Writing a function that takes into account how to *actually* insert the unit in the case above would, I believe, be a lot of work a not much return.

### PR DESCRIPTION
**Pull request by ryantxu**
**What is this feature?**

We currently format  negative monies as `$-100` and it should be `-$100`

**Why do we need this feature?**

to be more normal

image

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #65123

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.
- [ ] There are no known compatibility issues with older supported versions of Grafana, or plugins.
- [ ] It passes the [Hosted Grafana feature readiness review](https://docs.google.com/document/d/1QL9Ly8KnXzpb6ISbg49pTODRO5mhA5tkkfIZVX6pqQU/edit) for observability, scalability, performance, and security.

### CODE REVIEW

File: packages/grafana-data/src/valueFormats/symbolFormatters.ts [hunk 1]
```diff
@@ -5,16 +5,23 @@ import { scaledUnits, ValueFormatter } from './valueFormats';
...
   const units = ['', 'K', 'M', 'B', 'T'];
   const scaler = scaledUnits(1000, units);
-  return (size: number, decimals?: DecimalCount, scaledDecimals?: DecimalCount) => {
-    if (size === null) {
+  return (value: number, decimals?: DecimalCount, scaledDecimals?: DecimalCount) => {
+    if (value == null) {
       return { text: '' };
     }
-    const scaled = scaler(size, decimals, scaledDecimals);
+    const neg = value < 0;
```
Comment (leventebalogh) [inline packages/grafana-data/src/valueFormats/symbolFormatters.ts:12]: **Nit:** something like `isNegative` would make the core easier to scan
```suggestion
    const isNegative = value < 0;
```

**Review by leventebalogh — APPROVED** [review]
Nice! 👏

**Review by baldm0mma — APPROVED** [review]
Fast and elegant solution! Played around with it, and works great. LGTM!

File: packages/grafana-data/src/valueFormats/symbolFormatters.ts [hunk 2]
```diff
@@ -5,16 +5,23 @@ import { scaledUnits, ValueFormatter } from './valueFormats';
 export function currency(symbol: string, asSuffix?: boolean): ValueFormatter {
   const units = ['', 'K', 'M', 'B', 'T'];
   const scaler = scaledUnits(1000, units);
-  return (size: number, decimals?: DecimalCount, scaledDecimals?: DecimalCount) => {
-    if (size === null) {
+  return (value: number, decimals?: DecimalCount, scaledDecimals?: DecimalCount) => {
```
Comment (baldm0mma) [inline packages/grafana-data/src/valueFormats/symbolFormatters.ts:8]: Good change here, value makes way more sense.
