### PR TITLE
Geomap: Display legend

### LINKED ISSUE #45813: Geomap Legend Doesnt Work
**What happened**: I couldn't manage to get a lenged for geomap panel.

**What you expected to happen**: I expect too see a legend.

**How to reproduce it (as minimally and precisely as possible)**: 
- Create a geomap with latitudes and longitudes / markers.
- enable "Show Legend" under Data Layer section.
- you'll get no legend.

**Environment**:
- Grafana version: 8.4.1
- Data source type & version: Postgres
- OS Grafana is installed on: official docker image, grafana/grafana:latest
- Grafana plugins: GEOMAP

### LINKED ISSUE #46895: Geomap: hide tootip option for base layers
The geomap will show an option to check tooltips in the baselayer... but this should be hidden:

image

### PR DESCRIPTION
**Pull request by adela-almasan**
**What this PR does / why we need it**:
Bugfix to display the legend on the bottom left side of the map. As it was a small change, this also covers hiding the tooltip for base layer.

https://user-images.githubusercontent.com/88068998/160655154-b3f1c578-9820-4397-a62b-6ba63fb5d0a5.mov

Fixes #45813 
Fixes #46895

### CODE REVIEW

File: public/app/plugins/panel/geomap/GeomapPanel.tsx [hunk 1]
```diff
@@ -124,7 +125,7 @@ export class GeomapPanel extends Component<Props, State> {
       layers: layers.slice(1).map((v) => v.options),
     });
 
-    // Notify the the panel editor
+    // Notify the panel editor
```
Comment (nmarrs) [inline public/app/plugins/panel/geomap/GeomapPanel.tsx:128]: Great job on fixing up grammar / spelling! 👍

File: public/app/plugins/panel/geomap/editor/layerEditor.tsx [hunk 2]
```diff
@@ -93,12 +93,14 @@ export function getLayerEditor(opts: LayerEditorOptions): NestedPanelOptions<Map
...
-        defaultValue: true,
-      });
+      if (opts.category === ['Data layer']) {
+        builder.addBooleanSwitch({
+          path: 'tooltip',
+          name: 'Display tooltip',
+          description: 'Show the tooltip for layer',
+          defaultValue: true,
+        });
+      }
```
Comment (nmarrs) [inline public/app/plugins/panel/geomap/editor/layerEditor.tsx:103]: I'm not seeing this option appearing for inside settings of individual data layers.

I'm not sure having a toggle on a layer by layer basis for tooltips makes a lot of sense vs. a single global enable / disable tooltip setting (maybe as part of `Panel options` or potentially even `Map controls`?) @ryantxu thoughts on this?
Screen Shot 2022-03-29 at 12 50 03 PM

Comment (adela-almasan) [reply public/app/plugins/panel/geomap/editor/layerEditor.tsx:103]: Yes, that's not right, the tooltip should've been there for data layer. Looking into it.

Comment (nmarrs) [reply public/app/plugins/panel/geomap/editor/layerEditor.tsx:103]: Your latest change works great! On re-review, having tooltip disable / enable on a layer by layer basis makes sense to me now, though I still think it might make sense to have a global option as well. We can revisit this another time though

**Review by nmarrs — APPROVED** [review]
LGTM!
