### PR TITLE
FolderPicker: Fixes not being able to create new folder

### LINKED ISSUE #27067: FolderPicker: unable to create new folder
**What happened**:
Tried to create a new folder from folder picker in the dashboard settings. The same issue appeared in the save new dashboard model.

**What you expected to happen**:
Folder to be created

**How to reproduce it (as minimally and precisely as possible)**:
1. Create new dashboard
2. When saving, create a new folder to save to
3. New folder is not created and the dashboard is saved in the default folder

**Anything else we need to know?**:
Recording:
Kapture 2020-08-19 at 11 54 31

Stack trace:
```
FolderPicker.tsx:90 Uncaught (in promise) TypeError: Object(...)(...).createFolder is not a function
    at _callee3$ (FolderPicker.tsx:90)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (QueryOperationRow.tsx:118)
    at _next (QueryOperationRow.tsx:118)
    at QueryOperationRow.tsx:118
    at new Promise (<anonymous>)
    at QueryOperationRow.tsx:118
    at FolderPicker.tsx:29
_callee3$ @ FolderPicker.tsx:90
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
asyncGeneratorStep @ QueryOperationRow.tsx:118
_next @ QueryOperationRow.tsx:118
(anonymous) @ QueryOperationRow.tsx:118
(anonymous) @ QueryOperationRow.tsx:118
(anonymous) @ FolderPicker.tsx:29
Creatable._this.onChange @ react-select.browser.esm.js:83
Select._this.onChange @ Select-0919c909.browser.esm.js:1079
Select._this.setValue @ Select-0919c909.browser.esm.js:1106
Select._this.selectOption @ Select-0919c909.browser.esm.js:1155
onSelect @ Select-0919c909.browser.esm.js:2205
callCallback @ react-dom.development.js:336
invokeGuardedCallbackDev @ react-dom.development.js:385
invokeGuardedCallback @ react-dom.development.js:440
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:454
executeDispatch @ react-dom.development.js:584
executeDispatchesInOrder @ react-dom.development.js:609
executeDispatchesAndRelease @ react-dom.development.js:713
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:722
forEachAccumulated @ react-dom.development.js:694
runEventsInBatch @ react-dom.development.js:739
runExtractedPluginEventsInBatch @ react-dom.development.js:880
handleTopLevel @ react-dom.development.js:5803
batchedEventUpdates$1 @ react-dom.development.js:24401
batchedEventUpdates @ react-dom.development.js:1415
dispatchEventForPluginEventSystem @ react-dom.development.js:5894
attemptToDispatchEvent @ react-dom.development.js:6010
dispatchEvent @ react-dom.development.js:5914
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
discreteUpdates$1 @ react-dom.development.js:24417
discreteUpdates @ react-dom.development.js:1438
dispatchDiscreteEvent @ react-dom.development.js:5881
Show 6 more frames
```
**Environment**:
- Grafana version: master (689ca1be876df3a5fcc4edff50613879b925e350)
- Data source type & version: -
- OS Grafana is installed on: MacOs Catalina
- User OS & Browser: Chrome
- Grafana plugins: - 
- Others:-

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
Fixes what is beautifully described in #27067

**Which issue(s) this PR fixes**:
Fixes #27067

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/core/components/Select/FolderPicker.tsx [hunk 1]
```diff
@@ -4,9 +4,11 @@ import { AsyncSelect } from '@grafana/ui';
 import { AppEvents, SelectableValue } from '@grafana/data';
 import { getBackendSrv } from '@grafana/runtime';
 import { selectors } from '@grafana/e2e-selectors';
+
 import appEvents from '../../app_events';
 import { contextSrv } from 'app/core/services/context_srv';
 import { DashboardSearchHit } from 'app/features/search/types';
+import { createFolder } from '../../../features/manage-dashboards/state/actions';
```
Comment (dprokop) [inline public/app/core/components/Select/FolderPicker.tsx:11]:
```suggestion
import { createFolder } from 'app/features/manage-dashboards/state/actions';
```

**Review by dprokop — APPROVED** [review]
Cool cool my friend!
