### PR TITLE
Annotations: fixes variable values not displaying in annotations.

### LINKED ISSUE #37962: Identify root cause and fix https://github.com/grafana/support-escalations/issues/726

### PR DESCRIPTION
**Pull request by thisisobate**
**What this PR does / why we need it**:
This PR fixes wrong annotation when opening dashboard with URL encoded variable
**Which issue(s) this PR fixes**:

Fixes: #37962

### CODE REVIEW

File: public/app/features/dashboard/state/initDashboard.ts [hunk 1]
```diff
@@ -166,6 +164,9 @@ export function initDashboard(args: InitDashboardArgs): ThunkResult<void> {
     // template values service needs to initialize completely before the rest of the dashboard can load
     await dispatch(initVariablesTransaction(args.urlUid!, dashboard));
 
+    const runner = createDashboardQueryRunner({ dashboard, timeSrv });
+    runner.run({ dashboard, range: timeSrv.timeRange() });
+
```
Comment (hugohaggmark) [inline public/app/features/dashboard/state/initDashboard.ts:169]: Maybe we should add a comment
```suggestion
    // DashboardQueryRunner needs to run after all variables have been resolved so that any annotation query including a variable
    // will be correctly resolved
    const runner = createDashboardQueryRunner({ dashboard, timeSrv });
    runner.run({ dashboard, range: timeSrv.timeRange() });
```

**Review by hugohaggmark — APPROVED** [review]
LGTM! 🎉

File: public/app/features/dashboard/state/initDashboard.ts (hunk 1 above)
Comment (thisisobate) [reply public/app/features/dashboard/state/initDashboard.ts:169]: oh yes, will do! Thanks Hugo! 🥳

**Review by ashharrison90 — APPROVED** [review]
lgtm too! 🙌
