### PR TITLE
Snapshots: Fix breadcrumb when not logged in

### LINKED ISSUE #96988: Snapshots: "Page not found" in breadcrumbs when not logged in
### What happened?

Image

### What did you expect to happen?

For it to not show "Page not found"

### Did this work before?

🤷  probably before the new breadcrumbs

### How do we reproduce it?

1. Create snapshot
2. Log out
3. Go to snapshot

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by juanicabanas**
**What is this feature?**

This fixes `Page not found` breadcrumb when the user is not signed in.
Now, it shows `Home`.
As mentioned [here](https://github.com/grafana/grafana/issues/96988#issuecomment-3127392630), I prefer displaying `Home` breadcrumb instead of `Snapshots`, because if redirects you to the login page if you click on it

| Signed in | Not signed in (before) | Not signed in (now) |
|--------|--------|--------|
| image | image | image |

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/96988

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard-scene/scene/DashboardSceneRenderer.tsx [hunk 1]
```diff
@@ -32,7 +32,15 @@ export function DashboardSceneRenderer({ model }: SceneComponentProps<DashboardS
...
-  const navModel = getNavModel(navIndex, `dashboards/${type === 'snapshot' ? 'snapshots' : 'browse'}`);
+  const navModel =
+    type === 'snapshot'
+      ? getNavModel(
+          navIndex,
+          'dashboards/snapshots',
+          // fallback navModel to prevent showing `Page not found` in snapshots
+          getNavModel(navIndex, 'home')
+        )
+      : getNavModel(navIndex, 'dashboards/browse');
```
Comment (nmarrs) [inline public/app/features/dashboard-scene/scene/DashboardSceneRenderer.tsx:43]: can we add a small unit test confirming this fix / functionality?

**Review by nmarrs — APPROVED** [review]
LGTM 🫡
