### PR TITLE
Dashboards: Fix adhoc filter click when panel has no panel-level datasource

### LINKED ISSUE #115307: V2: Clicking a value in a Viz panel to populate an AdHoc filter no longer works
Reported [here](https://raintank-corp.slack.com/archives/C081AF3S814/p1765782900990709?thread_ts=1765538735.085799&cid=C081AF3S814)

Clicking a value in a Viz panel to populate an AdHoc filter no longer works at all.

### PR DESCRIPTION
**Pull request by ivanortegaalba**
*Problem*

When clicking on a series value to add an adhoc filter, if the panel has no panel-level datasource set (because all queries use the same datasource), the filter was not applied to the existing adhoc filter variable. Instead, a new adhoc variable was created.

This happened because `queryRunner.state.datasource` is undefined when all queries share the same datasource (non-mixed mode), causing the adhoc filter lookup to fail.

In v1, the panel ds was the ds from the queries when the queries were the same. In v2 we delegated the ds to the queries, so that ds is undefined unless the queries ds are different between them...

*Solution*

Add a helper function `getDatasourceFromQueryRunner` that extracts the datasource from the query runner. When no panel-level datasource is set, it falls back to the first query's datasource since all queries share the same one.

Updated the following consumers to use this helper:
- `setDashboardPanelContext.ts` - adhoc filter and group by variable lookup
- `urlBuilders.ts` - Explore URL building
- `drilldownUtils.ts` - drilldown applicability checks

*How to test*

1. Create a dashboard with a panel that has queries using the same datasource
2. Add an adhoc filter variable for that datasource
3. Click on a series value in the panel to filter
4. Verify the filter is added to the existing adhoc variable (not a new one)

**Question to be answered**
- Should we set the query runner ds at the scene creation time instead? 
- Is this showing an architecture limitation that should be resolved in any other way?

### CODE REVIEW

File: public/app/features/dashboard-scene/utils/utils.ts [hunk 1]
```diff
@@ -237,6 +237,26 @@ export function getQueryRunnerFor(sceneObject: SceneObject | undefined): SceneQu
...
+  // Panel-level datasource is set for mixed datasource panels
+  if (queryRunner.state.datasource) {
+    return queryRunner.state.datasource;
+  }
+
+  // No panel-level datasource means all queries share the same datasource
+  const firstQuery = queryRunner.state.queries?.[0];
+  if (firstQuery?.datasource) {
+    return firstQuery.datasource;
+  }
```
Comment (dprokop) [inline public/app/features/dashboard-scene/utils/utils.ts:255]: @ivanortegaalba  - I can't remember from the top of my head, but are these actual resolved ds refs that we pass when transforming v2 -> scene, or do we delegate ds resolving to SQR? Because if they are not (i.e. query had only ds group defined in v2), then this may still fail.

Comment (harisrozajac) [reply public/app/features/dashboard-scene/utils/utils.ts:255]: @dprokop these are not actual resolved ds refs, but they are delegated to SQR which then resolves it through ds service, and you are right that this would fail when ds only has a group because `state.queries[0].datasource` will just have type and not uid. I added a fix here https://github.com/grafana/grafana/pull/115576/commits/d5fec70ae8d790d32609ac1366752791feffe87e. Not sure if there's a better way to do this, but we are doing someting similar in [PanelDataQueriesTab](https://github.com/grafana/grafana/blob/cfc5d96c34c08b66b5c381dc6de6820a8a82d7be/public/app/features/dashboard-scene/panel-edit/PanelDataPane/PanelDataQueriesTab.tsx#L124)

As to why a new ad hoc variable get's created 😃 , it's because of this, when there's no match we just create a new variable (not sure why):
https://github.com/grafana/grafana/blob/d5fec70ae8d790d32609ac1366752791feffe87e/public/app/features/dashboard-scene/scene/setDashboardPanelContext.ts#L251-L269

**Review by harisrozajac — APPROVED** [review]
Tested this and added a small change to fix the issue when panel only has group defined
