### PR TITLE
Don't truncate IPv6 addresses

### LINKED ISSUE #18924: IPv6 Truncation
Bug: 

Grafana truncates one doctet from IPv6 addresses in the Profile -> Sessions view.

What do you expect: 

I expect to see the full IPv6 address, not just the first seven doctets.

How to reproduce the bug:

1. Login to Grafana as a normal user using an IPv6 address.
2. View https://your.grafana.url:3000/profile to see the missing doctet.

Pictures of the bug:

ipv6
ipv6-2

Misc:

- Grafana version: Grafana v6.3.5 (commit: 67bad72)
- Data source type & version: N/A
- OS Grafana is installed on: Debian Linux 9
- User OS & Browser: Ubuntu/Debian FireFox and Chrome
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
This PR fixes the parsing of network addresses to not truncate the final part of IPv6 addresses.

**Which issue(s) this PR fixes**:

Fixes #18924.

### CODE REVIEW

File: pkg/util/ip_address.go [hunk 1]
```diff
@@ -24,28 +28,37 @@ func ParseIPAddress(input string) string {
...
+		input = fmt.Sprintf("%s:%s", input, defaultPort)
 	}
 
-	s = strings.Replace(s, "[", "", -1)
-	s = strings.Replace(s, "]", "", -1)
-	port = strings.Replace(port, "[", "", -1)
-	port = strings.Replace(port, "]", "", -1)
+	host, port, err := net.SplitHostPort(input)
+	if err != nil {
+		panic(fmt.Sprintf("net.SplitHostPort failed for '%s': %v", input, err))
```
Comment (kylebrandt) [inline pkg/util/ip_address.go]: Why a call to panic?

Comment (aknuds1) [reply pkg/util/ip_address.go]: @kylebrandt Is there any sensible way for us to recover from this error? Ideally I would change `SplitHostPortDefault` to return an error, so we can propagate it.

Comment (kylebrandt) [reply pkg/util/ip_address.go]: I think the implication in `SplitHostPortDefault` is that the defaults will be used in the case of a parse error - "no match".

Comment (kylebrandt) [reply pkg/util/ip_address.go]: We might want @marefr to weigh in

Comment (aknuds1) [reply pkg/util/ip_address.go]: > I think the implication in `SplitHostPortDefault` is that the defaults will be used in the case of a parse error - "no match".

OK, not sure what the original intention is.

Comment (marefr) [reply pkg/util/ip_address.go]: > I think the implication in SplitHostPortDefault is that the defaults will be used in the case of a parse error - "no match".

Yes, that's the idea. For the `UserAuthTokenService` we don't want to fail a user to login/rotate auth token because the ip address couldn't be determined. But introducing return of errors is maybe a way forward and let the caller decide what to do?

Comment (aknuds1) [reply pkg/util/ip_address.go]: @marefr I think returning an error and letting caller decide does sound better 👍

File: pkg/util/ip_address.go [hunk 2]
```diff
@@ -10,12 +11,15 @@ func ParseIPAddress(input string) string {
 	host, _ := SplitHostPort(input)
 
 	ip := net.ParseIP(host)
-
 	if ip == nil {
 		return host
 	}
 
 	if ip.IsLoopback() {
+		if strings.Contains(host, ":") {
```
Comment (marefr) [inline pkg/util/ip_address.go]: This change makes the session view look like this. The earlier loopback check and returning 127.0.0.1 was when signing in locally, not sure though what makes the best user experience here?

Top: With your changes, bottom: Current master
image

Comment (marefr) [reply pkg/util/ip_address.go]: Maybe that's more of a UX issue though and shouldn't matter how we store the IP address

Comment (aknuds1) [reply pkg/util/ip_address.go]: @marefr I thought this change should only cause `ParseIPAddress` to return "::1" for IPv6 loopback addresses? Is your local address IPv6? I don't see why your network IP address would contain colons if not IPv6.

**Comment by aknuds1** [comment]
@kylebrandt @marefr I pushed a change now to make the involved functions (ParseIPAddress, SplitHostPort*) return errors. Please let me know if there are outstanding issues.

We'll also have to decide on what to do about IPv6 loopback addresses :)

File: pkg/services/auth/auth_token.go [hunk 3]
```diff
@@ -55,7 +55,14 @@ func (s *UserAuthTokenService) ActiveTokenCount(ctx context.Context) (int64, err
 }
 
 func (s *UserAuthTokenService) CreateToken(ctx context.Context, userId int64, clientIP, userAgent string) (*models.UserToken, error) {
-	clientIP = util.ParseIPAddress(clientIP)
+	s.log.Debug("Creating user auth token", "clientIp", clientIP)
+	clientIP, err := util.ParseIPAddress(clientIP)
+	if err != nil {
+		s.log.Debug("Failed to parse client IP address", "clientIp", clientIP, "err", err)
+		clientIP = ""
```
Comment (aknuds1) [inline pkg/services/auth/auth_token.go]: Assuming that we want to be tolerant here and just go with an empty client IP address.

File: pkg/services/auth/auth_token.go [hunk 4]
```diff
@@ -214,7 +221,14 @@ func (s *UserAuthTokenService) TryRotateToken(ctx context.Context, token *models
 
 	s.log.Debug("token needs rotation", "tokenId", model.Id, "authTokenSeen", model.AuthTokenSeen, "rotatedAt", rotatedAt)
 
-	clientIP = util.ParseIPAddress(clientIP)
+	clientIP, err := util.ParseIPAddress(clientIP)
+	if err != nil {
+		s.log.Debug("Failed to parse client IP address", "clientIp", clientIP, "err", err)
+		clientIP = ""
```
Comment (aknuds1) [inline pkg/services/auth/auth_token.go]: Assuming that we want to be tolerant here and just go with an empty client IP address.

File: pkg/services/auth/auth_token.go (hunk 3 above)
Comment (marefr) [reply pkg/services/auth/auth_token.go]: Makes sense :+1: Just remove the debug log messages - I guess you used them for manual tests?

File: pkg/services/auth/auth_token.go (hunk 4 above)
Comment (marefr) [reply pkg/services/auth/auth_token.go]: Same comment as earlier

File: pkg/services/sqlstore/sqlstore.go [hunk 5]
```diff
@@ -185,7 +186,11 @@ func (ss *SqlStore) buildConnectionString() (string, error) {
 
 		cnnstr += ss.buildExtraConnectionString('&')
 	case migrator.POSTGRES:
-		host, port := util.SplitHostPortDefault(ss.dbCfg.Host, "127.0.0.1", "5432")
+		host, port, err := util.SplitHostPortDefault(ss.dbCfg.Host, "127.0.0.1", "5432")
+		if err != nil {
+			return "", xerrors.Errorf("Invalid host specifier '%s': %w", ss.dbCfg.Host, err)
```
Comment (marefr) [inline pkg/services/sqlstore/sqlstore.go]: We have some utils for working with xerrors that I would suggest to use. See https://github.com/grafana/grafana/blob/master/pkg/util/errutil/errors.go#L23

File: pkg/tsdb/mssql/mssql.go [hunk 6]
```diff
@@ -46,7 +47,10 @@ func newMssqlQueryEndpoint(datasource *models.DataSource) (tsdb.TsdbQueryEndpoin
 }
 
 func generateConnectionString(datasource *models.DataSource) (string, error) {
-	server, port := util.SplitHostPortDefault(datasource.Url, "localhost", "1433")
+	server, port, err := util.SplitHostPortDefault(datasource.Url, "localhost", "1433")
+	if err != nil {
+		return "", xerrors.Errorf("Invalid data source URL '%s': %w", datasource.Url, err)
```
Comment (marefr) [inline pkg/tsdb/mssql/mssql.go]: Same as earlier comment regarding xerrors util

File: pkg/util/ip_address.go [hunk 7]
```diff
@@ -1,54 +1,77 @@
...
+	"golang.org/x/xerrors"
 )
 
 // ParseIPAddress parses an IP address and removes port and/or IPV6 format
-func ParseIPAddress(input string) string {
-	host, _ := SplitHostPort(input)
+func ParseIPAddress(input string) (string, error) {
+	host, _, err := SplitHostPort(input)
+	if err != nil {
+		return "", xerrors.Errorf("Failed to split network address '%s' by host and port: %w",
```
Comment (marefr) [inline pkg/util/ip_address.go]: Same as earlier comment regarding xerrors util

File: pkg/util/ip_address.go [hunk 8]
```diff
@@ -1,54 +1,77 @@
...
-	if lastIndex != -1 {
-		if lastIndex > 0 && input[lastIndex-1:lastIndex] != ":" {
-			s = input[:lastIndex]
-			port = input[lastIndex+1:]
-		} else if lastIndex == 0 {
-			s = defaultHost
-			port = input[lastIndex+1:]
+func SplitHostPortDefault(input, defaultHost, defaultPort string) (host string, port string, err error) {
+	if len(input) == 0 {
+		return "", "", xerrors.Errorf("Input is empty")
```
Comment (marefr) [inline pkg/util/ip_address.go]: Don't need to use xerrors here

File: pkg/util/ip_address.go [hunk 9]
```diff
@@ -1,54 +1,77 @@
...
+	}
+
+	start := 0
+	// Determine if IPv6 address, in which case IP address will be enclosed in square brackets
+	if strings.Index(input, "[") == 0 {
+		addrEnd := strings.LastIndex(input, "]")
+		if addrEnd < 0 {
+			// Malformed address
+			return "", "", xerrors.Errorf("Malformed IPv6 address: '%s'", input)
```
Comment (marefr) [inline pkg/util/ip_address.go]: `fmt.Errorf` can be used here?

File: pkg/util/ip_address.go [hunk 10]
```diff
@@ -1,54 +1,77 @@
...
+	if strings.LastIndex(input[start:], ":") < 0 {
+		// There's no port section of the input
+		// It's still useful to call net.SplitHostPort though, since it removes IPv6
+		// square brackets from the address
+		input = fmt.Sprintf("%s:%s", input, defaultPort)
+	}
+
+	host, port, err = net.SplitHostPort(input)
+	if err != nil {
+		return "", "", xerrors.Errorf("net.SplitHostPort failed for '%s': %w", input, err)
```
Comment (marefr) [inline pkg/util/ip_address.go]: Same as earlier comment regarding xerrors util

File: pkg/util/ip_address.go [hunk 11]
```diff
@@ -1,54 +1,77 @@
...
-	lastIndex := strings.LastIndex(input, ":")
-
-	if lastIndex != -1 {
-		if lastIndex > 0 && input[lastIndex-1:lastIndex] != ":" {
-			s = input[:lastIndex]
-			port = input[lastIndex+1:]
-		} else if lastIndex == 0 {
-			s = defaultHost
-			port = input[lastIndex+1:]
+func SplitHostPortDefault(input, defaultHost, defaultPort string) (host string, port string, err error) {
```
Comment (marefr) [inline pkg/util/ip_address.go]: Instead of returning 3 result types maybe consider putting host and port into a struct and use that as result type? Reason is we don't normally have more than 2 return types. But I'm open to discuss it.

**Review by marefr — CHANGES_REQUESTED** [review]
Great. This is an improvement. Have added some minor requests for changes and a general comment/thought.

File: pkg/services/auth/auth_token.go (hunk 3 above)
Comment (aknuds1) [reply pkg/services/auth/auth_token.go]: @marefr I thought the debug messages might be useful to keep around. You think they add to much noise?

File: pkg/util/ip_address.go (hunk 11 above)
Comment (aknuds1) [reply pkg/util/ip_address.go]: @marefr OK I changed to using a struct `NetworkAddress` - please have a look.

File: pkg/services/auth/auth_token.go (hunk 3 above)
Comment (marefr) [reply pkg/services/auth/auth_token.go]: Yeah given that we already have debug message on [line 99 below](https://github.com/grafana/grafana/pull/19573/files#diff-df4f6a94ac93c2556bf59f514f4c847eR99). 

At least if there's no problem parsing the IP address we don't need to debug log (line 63-65 below).

If there are problem parsing the IP address we can keep the debug log, but since `clientIP` are or may be overwritten when calling `clientIP, err := util.ParseIPAddress(clientIP)` I'm not sure if the debug log message will include the source IP address or an empty string?

File: pkg/util/ip_address.go (hunk 11 above)
Comment (marefr) [reply pkg/util/ip_address.go]: Looks great :+1:

File: pkg/services/auth/auth_token.go (hunk 3 above)
Comment (aknuds1) [reply pkg/services/auth/auth_token.go]: @marefr You're right, the logging of `clientIP` didn't make sense since it was already reassigned. I renamed the parameter to `clientAddr` since I think this makes more sense anyway, as it may contain a port section. Also removed the offending logs.

Comment (marefr) [reply pkg/services/auth/auth_token.go]: Great :+1:

File: pkg/services/auth/auth_token.go [hunk 12]
```diff
@@ -214,7 +218,14 @@ func (s *UserAuthTokenService) TryRotateToken(ctx context.Context, token *models
...
+	} else {
+		s.log.Debug("Parsed client IP address", "clientIp", clientIP)
```
Comment (marefr) [inline pkg/services/auth/auth_token.go]: Same problem here as fixed for CreateToken.

**Review by marefr — CHANGES_REQUESTED** [review]
`CreateToken` looks good now, but needs to fix `TryRotateToken` as well.

File: pkg/services/auth/auth_token.go (hunk 4 above)
Comment (aknuds1) [reply pkg/services/auth/auth_token.go]: Thanks, fixed.

**Comment by aknuds1** [comment]
@marefr Please have another look.

**Review by marefr — APPROVED** [review]
Great :+1:
