### PR TITLE
Prometheus: Fix adding metric name to matcher

### LINKED ISSUE #107189: Prometheus: adhoc filter request returns error if `vector(0)` is present in panel query
### What happened?

Click on adhoc variable generates malformed request to Prometheus datasource if panel on the dashboard contains `... or vector(0)` expression.

### What did you expect to happen?

No errors for adhoc variable.

### Did this work before?

It is working fine if I remove `or vector(0)` part of expression.

### How do we reproduce it?

1. Create a TimeSeries panel with Prometheus datasource type. My expression is the following:
```
sum(increase(prometheus_http_requests_total[$__rate_interval])) or vector(0)
```
2. Create `adhoc` variable type.
3. Save and reload dashboard (**important**)
4. Click on adhoc variable
5. Get malformed request sent to Prometheus backend:

Image

Request data:
```
start=1750835100&end=1750856760&match%5B%5D=prometheus_http_requests_total&match%5B%5D=
```
Response from backend:
```
{
    "status": "error",
    "errorType": "bad_data",
    "error": "unknown position: parse error: unexpected end of input"
}
```

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: grafana/grafana:12.0.2
OS: macOS 15.5
Browser: Chrome Version 137.0.7151.119 (Official Build) (arm64)

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

When having a query which has a binary operation we weren't checking whether the metric is an empty string or not. This PR addresses that by adding a simple empty string check. 

Fixes https://github.com/grafana/grafana/issues/107189

**Special notes for your reviewer:**
- For a reproduction please follow the steps defiend in the issue 

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-prometheus/src/datasource.ts [hunk 1]
```diff
@@ -557,38 +557,14 @@ export class PrometheusDatasource
...
-    const labelFilters: QueryBuilderLabelFilter[] = adhocFilters.map((f) => ({
-      label: f.key,
-      value: f.value,
-      op: f.operator,
-    }));
-    // Extract label filters from the filters we have already
-    const labelsMatch = renderLabelsWithoutBrackets(labelFilters);
-    // Create a matcher using metric names and label filters
-    return `{${[metricMatch, ...labelsMatch].join(',')}}`;
-  }
```
Comment (itsmylife) [inline packages/grafana-prometheus/src/datasource.ts:590]: Moved outside of the datasource class since we don't need it in datasource.

File: packages/grafana-prometheus/src/language_provider.ts [hunk 2]
```diff
@@ -810,7 +810,9 @@ export const populateMatchParamsFromQueries = (queries?: PromQuery[]): string =>
     }
     if (visualQuery.query.binaryQueries) {
       visualQuery.query.binaryQueries.forEach((bq) => {
-        params.push(bq.query.metric);
+        if (bq.query.metric !== '') {
+          params.push(bq.query.metric);
+        }
```
Comment (itsmylife) [inline packages/grafana-prometheus/src/language_provider.ts:815]: Real fix is here.

**Review by itsgareth — APPROVED** [review]
LGTM
