### PR TITLE
Provisioning: Ensure path to file exists in Files endpoints

### LINKED ISSUE #103295: Dashboard provisioning: Parent folder does not get created during repository generation
### What happened?

I've added folder validation during dashboard creation and [this test](https://github.com/grafana/grafana/blob/47ec51fda729aea453845ab60cb45db2afaed8ce/pkg/tests/apis/provisioning/provisioning_test.go#L210) has revealed that we are not actually creating a folder as part of repository creation based on files.

This leads to dashboard provisioning failing as this process is assuming the folder to already exist. There is a FIXME regarding this topic in the code:
https://github.com/grafana/grafana/blob/47ec51fda729aea453845ab60cb45db2afaed8ce/pkg/registry/apis/provisioning/resources/dualwriter.go#L197

### What did you expect to happen?

Folders to be created when a repository is created.

### Did this work before?

No

### How do we reproduce it?

1. Created a repository like in the test: `helper.Repositories.Resource.Create(ctx, localTmp, metav1.CreateOptions{})` 
2. Observe that no folder has been created

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

_No response_

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by MissingRoberto**
**What is this feature?**

Ensure path to file exists in `/files` APIs. Also fixed a bug in which the folder name in sync and files API.

**Why do we need this feature?**

`/files` API can accept a file path within the repository that points to files located in nested directories (e.g., `/files/dir1/dir2/file.txt`). Currently, this API will only work for files that are located in the root directory of the repository.

**Who is this feature for?**

Users of Provisioning / Git Sync.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/103295

**Special notes for your reviewer:**

Please check that:

- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

## Example payload

```bash
curl -X 'POST' \
  'http://localhost:3000/apis/provisioning.grafana.app/v0alpha1/namespaces/default/repositories/github-demo-2/files/dir1%2Fdir2%2Fdir3%2Fdeepinside.json' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "apiVersion": "dashboard.grafana.app/v1alpha1",
  "kind": "Dashboard",
  "spec": {
    "annotations": {
      "list": [
        {
          "builtIn": 1,
          "datasource": {
            "type": "grafana",
            "uid": "-- Grafana --"
          },
          "enable": true,
          "hide": true,
          "iconColor": "rgba(0, 211, 255, 1)",
          "name": "Annotations & Alerts",
          "type": "dashboard"
        }
      ]
    },
    "editable": true,
    "fiscalYearStartMonth": 0,
    "graphTooltip": 0,
    "links": [],
    "panels": [],
    "preload": false,
    "schemaVersion": 41,
    "tags": [],
    "templating": {
      "list": []
    },
    "time": {
      "from": "now-6h",
      "to": "now"
    },
    "timepicker": {},
    "timezone": "browser",
    "title": "deepinside"
  }
}'

```

Response: 

```json

{
  "kind": "ResourceWrapper",
  "apiVersion": "provisioning.grafana.app/v0alpha1",
  "path": "dir1/dir2/dir3/deepinside.json",
  "repository": {
    "type": "github",
    "title": "Github UI Sync Demo",
    "namespace": "default",
    "name": "github-demo-2"
  },
  "urls": {
    "sourceURL": "https://github.com/grafana/git-ui-sync-demo/blob/robertoonboarding/dir1/dir2/dir3/deepinside.json",
    "repositoryURL": "https://github.com/grafana/git-ui-sync-demo"
  },
  "resource": {
    "type": {
      "group": "dashboard.grafana.app",
      "version": "v1alpha1",
      "kind": "Dashboard",
      "resource": "dashboards"
    },
    "file": {
      "apiVersion": "dashboard.grafana.app/v1alpha1",
      "kind": "Dashboard",
      "metadata": {
        "annotations": {
          "grafana.app/folder": "dir3-vunp88u2ssnrp6pibssvjh2nd9jpe9g22ve",
          "grafana.app/managedBy": "repo",
          "grafana.app/managerId": "github-demo-2",
          "grafana.app/sourcePath": "dir1/dir2/dir3/deepinside.json"
        },
        "name": "deepinside-ahlfsmqqixfsztpni2nys-md0w4ro",
        "namespace": "default"
      },
      "spec": {
        "annotations": {
          "list": [
            {
              "builtIn": 1,
              "datasource": {
                "type": "grafana",
                "uid": "-- Grafana --"
              },
              "enable": true,
              "hide": true,
              "iconColor": "rgba(0, 211, 255, 1)",
              "name": "Annotations & Alerts",
              "type": "dashboard"
            }
          ]
        },
        "editable": true,
        "fiscalYearStartMonth": 0,
        "graphTooltip": 0,
        "links": [],
        "panels": [],
        "preload": false,
        "schemaVersion": 41,
        "tags": [],
        "templating": {
          "list": []
        },
        "time": {
          "from": "now-6h",
          "to": "now"
        },
        "timepicker": {},
        "timezone": "browser",
        "title": "deepinside"
      }
    },
    "existing": null,
    "action": "create",
    "dryRun": null,
    "upsert": {
      "apiVersion": "dashboard.grafana.app/v1alpha1",
      "kind": "Dashboard",
      "metadata": {
        "annotations": {
          "grafana.app/createdBy": "user:dehhdv7fkc45cf",
          "grafana.app/folder": "dir3-vunp88u2ssnrp6pibssvjh2nd9jpe9g22ve",
          "grafana.app/managedBy": "repo",
          "grafana.app/managerId": "github-demo-2",
          "grafana.app/sourcePath": "dir1/dir2/dir3/deepinside.json"
        },
        "creationTimestamp": "2025-04-03T11:11:48Z",
        "generation": 1,
        "labels": {
          "grafana.app/deprecatedInternalID": "2730251385135104"
        },
        "managedFields": [
          {
            "apiVersion": "dashboard.grafana.app/v1alpha1",
            "fieldsType": "FieldsV1",
            "fieldsV1": {
              "f:metadata": {
                "f:annotations": {
                  ".": {},
                  "f:grafana.app/folder": {},
                  "f:grafana.app/managedBy": {},
                  "f:grafana.app/managerId": {},
                  "f:grafana.app/sourcePath": {}
                }
              },
              "f:spec": {
                "f:annotations": {
                  ".": {},
                  "f:list": {}
                },
                "f:editable": {},
                "f:fiscalYearStartMonth": {},
                "f:graphTooltip": {},
                "f:links": {},
                "f:panels": {},
                "f:preload": {},
                "f:schemaVersion": {},
                "f:tags": {},
                "f:templating": {
                  ".": {},
                  "f:list": {}
                },
                "f:time": {
                  ".": {},
                  "f:from": {},
                  "f:to": {}
                },
                "f:timepicker": {},
                "f:timezone": {},
                "f:title": {}
              }
            },
            "manager": "grafana",
            "operation": "Update",
            "time": "2025-04-03T11:11:48Z"
          }
        ],
        "name": "deepinside-ahlfsmqqixfsztpni2nys-md0w4ro",
        "namespace": "default",
        "resourceVersion": "1743678708865007",
        "uid": "9eb55d15-2a7e-4ce6-ada5-1dc182568551"
      },
      "spec": {
        "annotations": {
          "list": [
            {
              "builtIn": 1,
              "datasource": {
                "type": "grafana",
                "uid": "-- Grafana --"
              },
              "enable": true,
              "hide": true,
              "iconColor": "rgba(0, 211, 255, 1)",
              "name": "Annotations & Alerts",
              "type": "dashboard"
            }
          ]
        },
        "editable": true,
        "fiscalYearStartMonth": 0,
        "graphTooltip": 0,
        "links": [],
        "panels": [],
        "preload": false,
        "schemaVersion": 41,
        "tags": [],
        "templating": {
          "list": []
        },
        "time": {
          "from": "now-6h",
          "to": "now"
        },
        "timepicker": {},
        "timezone": "browser",
        "title": "deepinside"
      },
      "status": {}
    }
  }
}
```
Result: 

image

### CODE REVIEW

File: pkg/registry/apis/provisioning/resources/id.go [hunk 1]
```diff
@@ -92,12 +92,12 @@ func appendHashSuffix(hashKey, repositoryName string) func(string) string {
 }
 
 // Will pick a name based on the hashed repository and path
-func NamesFromHashedRepoPath(repo string, fpath string) (string, string) {
+func FileNameFromHashedRepoPath(repo string, fpath string) string {
```
Comment (MissingRoberto) [inline pkg/registry/apis/provisioning/resources/id.go:95]: Let's use single purpose functions when possible.

File: pkg/registry/apis/provisioning/resources/id.go [hunk 2]
```diff
@@ -92,12 +92,12 @@ func appendHashSuffix(hashKey, repositoryName string) func(string) string {
...
 	// Remove the extension: we don't want the extension to impact the ID. This lets the user change between all supported formats.
 	fpath = safepath.RemoveExt(fpath)
 	hasher := appendHashSuffix(fpath, repo)
 
-	return hasher(safepath.Base(fpath)), hasher(strings.Trim(safepath.Dir(fpath), "/"))
+	return hasher(safepath.Base(fpath))
```
Comment (MissingRoberto) [inline pkg/registry/apis/provisioning/resources/id.go:100]: This was the bug for the directory name. For sync the name will be the dir name and when using `/files` api a trimmed version of entire dir path. 

I opted for simple the dir name only for clarity and scalability. 


image

File: pkg/registry/apis/provisioning/resources/id_test.go [hunk 3]
```diff
@@ -67,18 +67,11 @@ func TestAppendHashSuffix(t *testing.T) {
...
 
-func TestNamesFromHashedRepoPath(t *testing.T) {
-	dashName, folderName := NamesFromHashedRepoPath("xyz", "path/to/folder/dashboard.json")
+func TestFileNameFromHashedRepoPath(t *testing.T) {
+	dashName := FileNameFromHashedRepoPath("xyz", "path/to/folder/dashboard.json")
 	assert.Equal(t, "dashboard-fy2kflbmskvt6u-9uecoahd1ekwbb7", dashName, "dashboard name of dashboard.json")
-	assert.Equal(t, "path-to-folder-3ehfurpmbvs4yxfp7a0r2uskr", folderName, "folder name of dashboard.json")
 	// We only want 40 characters because UIDs support no more. When we get rid of legacy storage, we can extend the support to 253 character long strings.
 	assert.LessOrEqual(t, len(dashName), 40, "dashName after hashing needs to be <=40 chars long")
-	assert.LessOrEqual(t, len(folderName), 40, "folderName after hashing needs to be <=40 chars long")
```
Comment (marcoabreu) [inline pkg/registry/apis/provisioning/resources/id_test.go:76]: How come you've removed this check?

File: pkg/registry/apis/provisioning/resources/parser.go [hunk 4]
```diff
@@ -169,11 +170,15 @@ func (r *Parser) Parse(ctx context.Context, info *repository.FileInfo, validate
 
 	// Calculate name+folder from the file path
 	if info.Path != "" {
-		objName, folderName := NamesFromHashedRepoPath(r.repo.Name, info.Path)
-		parsed.Meta.SetFolder(folderName)
+		objName := FileNameFromHashedRepoPath(r.repo.Name, info.Path)
```
Comment (ryantxu) [inline pkg/registry/apis/provisioning/resources/parser.go:173]: in https://github.com/grafana/grafana/pull/103309 I think we should remove this option entirely for now

we have too many untested options where things may or may not have the name in the resource

File: pkg/registry/apis/provisioning/resources/id.go (hunk 2 above)
Comment (ryantxu) [reply pkg/registry/apis/provisioning/resources/id.go:100]: I think we can even shorten the hash part -- it is kinda ugly :)

File: pkg/registry/apis/provisioning/resources/dualwriter.go [hunk 5]
```diff
@@ -257,21 +251,36 @@ func (r *DualReadWriter) UpdateResource(ctx context.Context, path string, ref st
...
+			parsed.Errors = append(parsed.Errors, err)
 		}
 	}
 
 	return parsed, err
 }
+
+// writeParsed write parsed resource to the repository and grafana database
+func (r *DualReadWriter) writeParsed(ctx context.Context, path string, parsed *ParsedResource) error {
+	if _, err := r.folders.EnsureFolderPathExist(ctx, path); err != nil {
```
[the remark this answers is not in the document]
Comment (MissingRoberto) [reply pkg/registry/apis/provisioning/resources/dualwriter.go:267]: I think we need to really rethink the dryrun strategy. 

In your PR you are creating an actual folders which doesn't sound to me like a dryrun to me.

 In the case of an actual sync, we shouldn't even have to do a dry run  because we apply it. 

For the sake of making things work and not ending up with too big of a PR. Let's get this one in and then I look at the dry separately (right after)

File: pkg/registry/apis/provisioning/resources/id_test.go (hunk 3 above)
Comment (ryantxu) [reply pkg/registry/apis/provisioning/resources/id_test.go:76]: because the updated function only produces a single hash -- rather than two :)

**Review by ryantxu — APPROVED** [review]

File: pkg/registry/apis/provisioning/resources/parser.go (hunk 4 above)
Comment (MissingRoberto) [reply pkg/registry/apis/provisioning/resources/parser.go:173]: I challenged that part in that PR for the POST /files

File: pkg/registry/apis/provisioning/resources/id_test.go (hunk 3 above)
Comment (MissingRoberto) [reply pkg/registry/apis/provisioning/resources/id_test.go:76]: It will be re-added in a different spot soon :) 

In that file it doesn't make much sense as we know it's consistent hashing (by not having flaky / failing unit tests). So same input, same output. 

I will add tests for this case and many others in follow-up PRs.

File: pkg/registry/apis/provisioning/resources/id.go (hunk 2 above)
Comment (MissingRoberto) [reply pkg/registry/apis/provisioning/resources/id.go:100]: sure, I will shorten it when I add more tests in a follow-up.

File: pkg/registry/apis/provisioning/resources/dualwriter.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (marcoabreu) [reply pkg/registry/apis/provisioning/resources/dualwriter.go:267]: Yeah I fully agree.

**Review by marcoabreu — APPROVED** [review]
