### PR TITLE
Accessibility: Ensure dashboard edit panel inputs have accessible labels (again)

### LINKED ISSUE #106227: WCAG Name, Role, Value - Ensure Panel Options form element has a label
**Steps to reproduce**:
"[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier."

1. Create a new dashboard
2. Add a panel
3. click Edit Panel to pop out the Panel Options side-bar
4. Run the Accessibility Insights for Web tool with the FastPass option
5. Notice the accessibility issues automatically identified by the tool.

**Actual Result**:
Image

**Expected Result**

No failures from Accessibility Insights for Web FastPass test run

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html

**Environment**:
- Grafana version: 12.0.2
- Data source type & version: n/a
- User OS & Browser:
    Chromium Edge: Version 137.0.3269.1 (Official build) dev (64-bit)
    Edition Windows 11 Pro
    Version 24H2
    OS build 26100.3476
- Others:

### PR DESCRIPTION
**Pull request by joshhunt**
This reintroduces the changes from https://github.com/grafana/grafana/pull/109546.

Instead of generating random ids, which doesn't work when the classes are constructed in a render loop (which is often!), we:

 - use the `useId()` hook if being called directly in a react component
 - derive an ID based on available properties (such as when rendering panel edit options)
 - hard code id when it's the only instance
 
 fixes https://github.com/grafana/grafana/issues/106227

### CODE REVIEW

File: public/app/features/dashboard-scene/conditional-rendering/ConditionalRenderingEditor.tsx [hunk 1]
```diff
@@ -54,6 +54,7 @@ export function useConditionalRenderingEditor(
   }).addItem(
     new OptionsPaneItemDescriptor({
       title,
+      id: 'conditional-rendering-options-item',
```
Comment (samsch) [inline public/app/features/dashboard-scene/conditional-rendering/ConditionalRenderingEditor.tsx:57]: this one seems like it should be a useId

**Review by fastfrwrd — COMMENTED** [review]
I've tested this out locally and this is working much better than the previous attempt. Thanks for the second pass!

**Comment by fastfrwrd** [comment]
I'll see if I can adjust my crappy table selectors which are now failing given the improved ids in this PR, actually.

File: public/app/features/dashboard-scene/panel-edit/getPanelFrameOptions.tsx
Comment (samsch) [inline public/app/features/dashboard-scene/panel-edit/getPanelFrameOptions.tsx:1]: the fixed IDs here are safe enough because right now `getPanelFrameOptions` is only used in one place. but thoughts on changing the call location and here so that this file exports a hook that handles the useMemo, and can then use useId?

File: public/app/features/dashboard-scene/scene/layout-tabs/TabItemEditor.tsx
Comment (samsch) [inline public/app/features/dashboard-scene/scene/layout-tabs/TabItemEditor.tsx:1]: This one looks like it can be useIds

**Comment by fastfrwrd** [comment]
The e2e failures in the table tests are now due to actual thrown errors introduced by the changes (see attached, from a screenshot from Playwright UI.) I'm presuming it's something to do with a `useId` somehwere it shouldn't be.

Screenshot 2025-08-26 at 1 34 49 PM

**Review by samsch — APPROVED** [review]

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍

File: public/app/features/dashboard/components/PanelEditor/getVisualizationOptions.tsx [hunk 2]
```diff
@@ -130,9 +130,11 @@ export function getVisualizationOptions(props: OptionPaneRenderProps): OptionsPa
       category.props.itemsCount = fieldOption.getItemsCount(value);
     }
 
+    const htmlId = `${plugin.meta.id}-${fieldOption.path}`;
```
Comment (torkelo) [inline public/app/features/dashboard/components/PanelEditor/getVisualizationOptions.tsx:133]: @joshhunt 

Trying to understand why we are adding the plugin id here, we never mix options from different plugins, so what is the purpose of adding the plugin id to the option id here?

Comment (joshhunt) [reply public/app/features/dashboard/components/PanelEditor/getVisualizationOptions.tsx:133]: Sorry @torkelo, I can't remember. I don't think there was a particularly strong reason to, but I was either following a similar pattern from elsewhere, or just being _extra_ sure the field will be unique.

Comment (torkelo) [reply public/app/features/dashboard/components/PanelEditor/getVisualizationOptions.tsx:133]: @joshhunt ok, no worries. I think I will remove the plugin.meta.id bit here as it makes it hard to use the id property (to filter on specific properties)
