### PR TITLE
Loki: Retry web socket connection when connection is closed abnormally

### LINKED ISSUE #29348: Loki: Loki Explore live tail view crashes after some time
**What happened**:

While piping live view of a quite active log stream through a filter, such as `|= "MARK"`  or `|= "foo count"`, after between 5 and 10 mins the live view will crash with the following. 

error: 
An unexpected error happened
TypeError: r is null

    in t
    in WithTheme(undefined)
    in s
    in div
    in div
    in Collapse
    in t
    in t
    in h
    in t
    in x
    in t
    in t
    in main
    in div
    in t
    in div
    in div
    in t
    in WithTheme(undefined)
    in x
    in t
    in t
    in div
    in div
    in div
    in t
    in t
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l

**What you expected to happen**:
Not to crash :-) 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.3 
- Data source type & version: Loki from hosted logs. 
- OS Grafana is installed on: hosted
- User OS & Browser: firefox and chorme. 
- Grafana plugins: n/a
- Others:
image

### PR DESCRIPTION
**Pull request by ivanahuckova**
**How to reproduce the issue**:

See https://github.com/grafana/grafana/issues/29348. 

**What this PR does / why we need it**:
This PR fixes 2 issues:
- When live tailing throws error and the received data/logs are `null`, we use empty `[]` as our data and this way `rowsToRender.slice(100)` [won't throw error.](https://github.com/grafana/grafana/blob/master/public/app/features/explore/LiveLogs.tsx#L132) Before this, we passed `null` and null.slice() threw error as well. 

- When we receive **[1006](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent) error code** which means that connection was closed abnormally (that is, with no close frame being sent). For this specifically, we retry connection. 
**Which issue(s) this PR fixes**:

**Fixed - going over 1h:** 
image

**Broken:**
image

image

**Fixes:**
Fixes https://github.com/grafana/grafana/issues/29348

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/datasource/loki/live_streams.ts [hunk 1]
```diff
@@ -42,9 +42,19 @@ export class LiveStreams {
...
-      catchError(err => {
-        return throwError(`error: ${err.reason}`);
-      }),
+      retryWhen((attempts: Observable<any>) =>
+        attempts.pipe(
+          mergeMap(error => {
+            // Code 1006 is used to indicate that a connection was closed abnormally.
+            // If connection was closed abnormally, we wish to retry, otherwise throw error.
+            if (error.code === 1006) {
+              console.log('Reconnecting websocket...');
```
Comment (hugohaggmark) [inline public/app/plugins/datasource/loki/live_streams.ts:51]: nit: maybe remove console output?

File: public/app/plugins/datasource/loki/live_streams.ts [hunk 2]
```diff
@@ -42,9 +42,19 @@ export class LiveStreams {
...
+              return timer(1000);
+            }
+            return throwError(`error: ${error.reason}`);
+          })
+        )
+      ),
```
Comment (hugohaggmark) [inline public/app/plugins/datasource/loki/live_streams.ts:57]: Skilled work on the RxJs code. The code now will retry into infinity with 1s delay between attempts? Maybe we should limit the retries to x number of retries?

File: public/app/plugins/datasource/loki/live_streams.ts [hunk 3]
```diff
@@ -42,9 +42,19 @@ export class LiveStreams {
         appendResponseToBufferedData(response, data);
         return [data];
       }),
-      catchError(err => {
-        return throwError(`error: ${err.reason}`);
-      }),
+      retryWhen((attempts: Observable<any>) =>
```
Comment (hugohaggmark) [inline public/app/plugins/datasource/loki/live_streams.ts:45]: This is an excellent candidate for testing using `expect(getStream()).toEmitValuesWith()`. Maybe you could pass webSocket as an argument to the function so you can pass your own Observable when testing?.

**Review by hugohaggmark — COMMENTED** [review]
Looks great ⭐ , I added some comments that you might want to consider.

**Comment by davkal** [comment]
If retries are cheap, we can keep retrying every 5-ish seconds, and keep trying. If it keeps failing, then show a message to the user but keep retrying and tell the user that something is disrupted but that it keeps retrying.

File: public/app/plugins/datasource/loki/live_streams.ts (hunk 2 above)
Comment (aocenas) [reply public/app/plugins/datasource/loki/live_streams.ts:57]: Not sure if I read this right and did not find good explanation in the docs but shouldn't it return `timer(1000).take(1)` or something like that? I mean what we want is to wait for error and then wait 1s and retry and then wait for another error and repeat right? But having a timer that will fire every 1s forever after the first error does not seem correct but maybe there is some internal implementation that prevents that which isn't documented?

feels like this section from the [docs](https://www.learnrxjs.io/learn-rxjs/operators/transformation/mergemap) applies here:
> Be aware that because mergeMap maintains multiple active inner subscriptions at once it's possible to create a memory leak through long-lived inner subscriptions. A basic example would be if you were mapping to an observable with an inner timer, or a stream of dom events. In these cases, if you still wish to utilize mergeMap you may want to take advantage of another operator to manage the completion of the inner subscription, think take or takeUntil. You can also limit the number of active inner subscriptions at a time with the concurrent parameter, seen in example 5.

Comment (aocenas) [reply public/app/plugins/datasource/loki/live_streams.ts:57]: Ah ok now I read that `timer(1000)` won't emit indefinitely if the second arg for period is not specified so disregard my previous comment.

Comment (hugohaggmark) [reply public/app/plugins/datasource/loki/live_streams.ts:57]: I still think we should consider adding a max number of attempts counter, but that is just me being super cautious.

File: public/app/plugins/datasource/loki/live_streams.ts (hunk 1 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/live_streams.ts]: Removed :)

File: public/app/plugins/datasource/loki/live_streams.ts (hunk 2 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/live_streams.ts]: I have added emitting of warning message `Websocket connection is being disrupted. We keep reconnecting but consider starting new live tailing again.` after we reconnect 10 times and every reconnection after that. So live tailing will be still working, but it is going to be super obvious that something is wrong. Also we have changed the timer from 1s to 5s.

**Comment by ivanahuckova** [comment]
@aocenas @hugohaggmark @davkal I have added test and implemented functionality as we discussed. Thanks Hugo so much for your help writing the test. 🙏

File: public/app/plugins/datasource/loki/live_streams.test.ts [hunk 4]
```diff
@@ -105,6 +106,39 @@ describe('Live Stream Tests', () => {
...
+        // When re-subsribed after abnormal error, return just logStream
+        return logStream;
+      })
+    ) as any;
+    const liveStreams = new LiveStreams();
+    await expect(liveStreams.getStream(makeTarget('url_to_match'), 100)).toEmitValuesWith(received => {
+      const dataBefore = received[0];
+      const dataAfter = received[1];
+      expect(dataBefore).not.toBe(undefined);
+      expect(dataAfter).not.toBe(undefined);
```
Comment (hugohaggmark) [inline public/app/plugins/datasource/loki/live_streams.test.ts:138]: In order to test that our retry logic works as expected, maybe we should check for specific log rows instead of just toBeDefined?

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/live_streams.test.ts]: Yes, makes sense! Done in https://github.com/grafana/grafana/pull/29438/commits/e5968b923eb1c957d26800357991e0d6ea02ef8f

Comment (hugohaggmark) [reply public/app/plugins/datasource/loki/live_streams.test.ts]: Beautiful ⭐

File: public/app/plugins/datasource/loki/live_streams.ts [hunk 5]
```diff
@@ -42,9 +43,26 @@ export class LiveStreams {
...
+          mergeMap((error, i) => {
+            // Code 1006 is used to indicate that a connection was closed abnormally.
+            // If connection was closed abnormally, we wish to retry, otherwise throw error.
+            const retryAttempt = i + 1;
+            if (error.code === 1006) {
+              if (retryAttempt > 10) {
+                // If more than 10 times retried, show user warning, but keep reconnecting
+                appEvents.emit(AppEvents.alertWarning, [
+                  'Websocket connection is being disrupted. We keep reconnecting but consider starting new live tailing again.',
+                ]);
```
Comment (hugohaggmark) [inline public/app/plugins/datasource/loki/live_streams.ts:57]: nit: Not sure you're supposed to use appEvents outside of the main app.

**Review by hugohaggmark — APPROVED** [review]
This looks great to me ⭐

File: public/app/plugins/datasource/loki/live_streams.ts (hunk 5 above)
Comment (torkelo) [reply public/app/plugins/datasource/loki/live_streams.ts:57]: Yea better to return a data error here and let Grafana show that

Comment (hugohaggmark) [reply public/app/plugins/datasource/loki/live_streams.ts:57]: That would work if we didn't need to retry, in this case we only want to show information to the user but not stop the retries.

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/live_streams.ts]: @hugohaggmark as mentioned on our call I have added console.warn and created an issue for informing user in better way https://github.com/grafana/grafana/issues/29609. As we can't inform the user about issues with their connection, if you think it makes sense to add max retries (e.g. 30?), I can do that.

Comment (hugohaggmark) [reply public/app/plugins/datasource/loki/live_streams.ts]: Yeah, I think that is a good idea
