### PR TITLE
Canvas: Fix setting icon from field data

### LINKED ISSUE #58492: Canvas: Unable to set icon via field data
A user found an issue where they could not set an icon based using field data. See comment [here](https://github.com/grafana/grafana/discussions/56835?sort=new#discussioncomment-4071835)

When setting an icon source to field, only the fallback question mark icon appears even if the field data is a valid path

### PR DESCRIPTION
**Pull request by nmarrs**
Fix bug where user was unable to set icon source through field data. See [community comment here](https://github.com/grafana/grafana/discussions/56835?sort=new#discussioncomment-4071835).

https://user-images.githubusercontent.com/22381771/200746767-e737fa73-d1d5-40f2-8e17-860525f23efb.mov

**Which issue(s) does this PR fix?**:

Fixes #58492

### CODE REVIEW

File: public/app/features/dimensions/resource.ts [hunk 1]
```diff
@@ -40,17 +40,18 @@ export function getResourceDimension(
...
     };
   }
 
-  const getIcon = (value: any): string => {
-    const disp = field.display!;
-    return getPublicOrAbsoluteUrl(disp(value).icon ?? '');
+  // mode === ResourceDimensionMode.Field case
+  const getIcon = (value: string): string => {
+    const display = field.display!;
+    return getPublicOrAbsoluteUrl(display(value).icon ?? value ?? '');
```
Comment (nmarrs) [inline public/app/features/dimensions/resource.ts:54]: The additional fallback here ` ?? value ` is what fixed the issue. This solution does have an issue though when the path is invalid / url doesn't allow CORS (displays empty instead falling back to `?` icon)

**Review by ryantxu — APPROVED** [review]
