### PR TITLE
Email: Mark HTML comments as "safe" in email templates

### LINKED ISSUE #63996: Alerting: Email template appears broken in Outlook's desktop client
**What happened**:
I upgraded from Grafana 9.2.0 to 9.4.1

**What you expected to happen**:
Email alerts would continue to look clear and functional

**How to reproduce it (as minimally and precisely as possible)**:
1. Create email contact point
2. Send a test alert to this contact point using the "Test" button

**Anything else we need to know?**:
After upgrading to 9.4.1, my alert emails now look like this:
image

While they used to look like this:
image

Is this expected behavior? The new email template looks stretched out and have a _lot_ of whitespace. Real alerts also show the buttons stacked on top of each other, while I'd expect them to be next to each other:
image

At first I thought I might've had a broken template installed, but the email templates in my installation all appear stock: 
image

**Environment**:
- Grafana version: 9.4.1
- Data source type & version: N/A
- OS Grafana is installed on: Windows Server 2016 v1607
- User OS & Browser: Windows 11 21H2, Outlook version 2301 (Build 16026.20200)
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by gillesdemey**
**What is this feature?**

This change adds an additional "safeHTML" function to the email templates to allow comment blocks to be preserved after compiling the template with Go's html/template package.

**Why do we need this feature?**

MJML outputs comments that are specific for MS Outlook and if those are not preserved the email is rendered incorrectly.

**Which issue(s) does this PR fix?**:

Fixes #63996

**Special notes for your reviewer**:

There's a security implication here in case the author of the email templates is untrusted.

I still have to figure out how to port this to `grafana-enterprise`

I've tested this with an Outlook for Desktop client I had access to from a friend of a friend and they said it looked correct 😆

### CODE REVIEW

File: emails/grunt/replace.js [hunk 1]
```diff
@@ -1,16 +1,45 @@
...
+/**
+ * Replace all instances of HTML comments with {{ safeHTML "<!-- my comment -->" }}.
+ *
+ * MJML will output <!--[if !mso]><!--> comments which are specific to MS Outlook.
+ *
+ * Go's template/html package will strip all HTML comments and we need them to be preserved
+ * to work with MS Outlook on the Desktop.
+ */
+const HTML_SAFE_FUNC = 'safeHTML';
+const commentBlock = /(\<\!\-\-(?:.|\n|\r)*?-->)/g;
```
Comment (KristianGrafana) [inline emails/grunt/replace.js:34]: This regex might be a bit too naive as it will try to match `<!-- foo -->` but comments might still be rendered when there's some other character in the closing HTML comment. One possible character might be `!`, so `<!-- foo --!>` might still be a valid comment, but I'm uncertain if that's an issue in this case.

**Comment by jmatosgrafana** [comment]
@gillesdemey Following our security assessment with @KristianGrafana, it's OK to ignore the `gosec` warning for `safeHTML`: changing an email template requires write access to the filesystem of the Grafana server and Grafana admins are trusted (if you have access to html files of Grafana server you could just edit them to include malicious payloads).

Yet to avoid in the future dangerous usage of `safeHTML` where the input would be coming from an untrusted user and not a trusted admin, could we rename it to something that makes explicit the risks of calling this method ?

**Comment by gillesdemey** [comment]
Changes made to this PR after meeting with @jmatosgrafana and @KristianGrafana

- [x] Renamed `safeHTML` to `__dangerouslyInjectHTML` to make anyone who uses this function think really hard about using it
- [x] Silenced with `nolint:gosec` since the attack vector requires write access to the emails directory and this requires admin privileges

File: emails/grunt/aliases.yaml [hunk 2]
```diff
@@ -1,5 +1,4 @@
 default:
-  - 'clean'
```
Comment (gillesdemey) [inline emails/grunt/aliases.yaml:2]: This is now handled by `make clean` since we need to clean the folder before grunt is even invoked

File: emails/Makefile [hunk 3]
```diff
@@ -1,14 +1,18 @@
...
+	mkdir dist/
+
+build-mjml:
 	npx mjml \
 		--config.beautify true \
 		--config.minify false \
 		--config.validationLevel=strict \
 		--config.keepComments=false \
-		./templates/*.mjml --output ../public/emails/
+		./templates/*.mjml --output ./dist/
```
Comment (gillesdemey) [inline emails/Makefile:13]: Moving the templates here first since we'll need to do some additional processing before we move them to `../public/emails`

**Review by yuri-tceretian — APPROVED** [review]

**Comment by yuri-tceretian** [comment]
I tested the PR in windows. The change LGTM.
