### PR TITLE
loki: query splitting: labels-based frame matching

### LINKED ISSUE #66661: loki: the combination of `lokiQuerySplitting` with `lokiMetricDataplane` does not work
in `lokiQuerySplitting`, to find the dataframes we should join, we look at `frame.name`. this is not happening anymore with `lokiMetricDataplane`.

### PR DESCRIPTION
**Pull request by gabor**
(fixes https://github.com/grafana/grafana/issues/66661)

in the loki query splitting code, we need to join the "correct" dataframes. right now it is done by looking at their `frame.name` field.

but, as we are trying to make Loki's metric output compatible with grafana's timeseries-data-specification ( https://github.com/grafana/grafana-plugin-sdk-go/blob/main/data/contract_docs/timeseries.md#properties-shared-by-all-time-series-based-formats ), we will stop setting the `frame.name` attribute.

so we cannot use it to decide if two frames are "joinable".

this PR changes the logic so that it looks at the dataframe's number-field's labels. if they have the same labels they are joinable.

for this to work, we need handle separately the metric-data coming from Loki and logs-data coming from Loki

(btw. logs-dataframes can always be joined)

how to test:
1. run split-query metric and logs queries, make sure it works
    - make sure you run a metric query that produces multiple series, for example something like:
       - `sum(count_over_time({place="luna"}|logfmt[1d])) by(level)` . you should see multiple lines in the graph.
3. enable the `lokiMetricDataplane`, and repeat the test from [1]. again, make sure you see multiple lines in the graph.

### CODE REVIEW

File: public/app/plugins/datasource/loki/responseUtils.ts [hunk 1]
```diff
@@ -123,7 +125,38 @@ function shouldCombine(frame1: DataFrame, frame2: DataFrame): boolean {
...
+    // we do not join things that have a different type
+    return false;
+  }
+
+  // metric range query data
+  if (frameType1 === DataFrameType.TimeSeriesMulti) {
+    const field1 = frame1.fields.find((f) => f.type === FieldType.number);
+    const field2 = frame2.fields.find((f) => f.type === FieldType.number);
+    if (field1 === undefined || field2 === undefined) {
+      // should never happen
```
Comment (gabor) [inline public/app/plugins/datasource/loki/responseUtils.ts:141]: for now we just return " do not join", but i wonder if we should throw na error here.. WDYT?

File: public/app/plugins/datasource/loki/responseUtils.ts [hunk 2]
```diff
@@ -123,7 +125,38 @@ function shouldCombine(frame1: DataFrame, frame2: DataFrame): boolean {
...
+      return false;
+    }
+
+    return shallowCompare(field1.labels ?? {}, field2.labels ?? {});
```
Comment (svennergr) [inline public/app/plugins/datasource/loki/responseUtils.ts:145]: Is this really enough to determine if two frames "belong to each other"?

In a test I did both fields were an empty object:
image

But even if they would be filled with the labels, how would two queries with the same labels we handled?

E.g. 
image
I would assume they have the same labels?

Comment (svennergr) [reply public/app/plugins/datasource/loki/responseUtils.ts:145]: Thanks @gabor. Sounds good to me. Regarding the missing labels on the Loki metric responses: are they missing because we haven't implemented them yet?

File: public/app/plugins/datasource/loki/responseUtils.ts [hunk 3]
```diff
@@ -123,7 +125,38 @@ function shouldCombine(frame1: DataFrame, frame2: DataFrame): boolean {
...
+  // logs use a special attribute in the dataframe's "custom" section
+  // because we do not have a good "frametype" value for them yet.
+  const customType1 = frame1.meta?.custom?.frameType;
+  const customType2 = frame2.meta?.custom?.frameType;
+
+  if (customType1 === 'LabeledTimeValues' && customType2 === 'LabeledTimeValues') {
+    return true;
+  }
+
+  // should never reach here
```
[the remark this answers is not in the document]
Comment (svennergr) [reply public/app/plugins/datasource/loki/responseUtils.ts:158]: I don't know what kind of error we would throw. I think it's fine returning nothing.

File: public/app/plugins/datasource/loki/responseUtils.ts (hunk 2 above)
Comment (svennergr) [reply public/app/plugins/datasource/loki/responseUtils.ts:145]: Still doesn't produce any labels, but the feature itself is working.

**Review by svennergr — APPROVED** [review]
LGTM, despite I don't get any labels for metric queries.

File: public/app/plugins/datasource/loki/responseUtils.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (gabor) [reply public/app/plugins/datasource/loki/responseUtils.ts:158]: 👍  (my usual one is `throw new Error('this should never happen')` 😄 )

**Review by matyax — APPROVED** [review]
👌
