### PR TITLE
Sparkline: Prevent infinite loop when rendering a sparkline with a single value

### LINKED ISSUE #113875: Suggestions: "Datapoints outside range" leads to infinite loop
To reproduce:

- use the gdev datasource locally
- select the "Datapoints outside range" scenario
- open suggestions

the infinite loop is in uPlot.

we need to identify which uPlot viz(s?) is/are having this issue, and decide whether we should update the `previewModifier` for these or just remove them from suggestions in this situation. We may want to update PanelDataSummary to easily detect this.

### PR DESCRIPTION
**Pull request by fastfrwrd**
Fixes #113875, relates to #112977

- fixed an issue where attempting to render a panel which contained a sparkline (Gauge, Stat, etc.) where only one value was present in the `values` array meant that the range calculation inside uPlot could get in an infinite loop. There was other code which assumed there were at least two datapoints, so I just return null from sparklines if there is only data point now.
- **I ripped the bandaid and converted the Sparkline component to a functional component.**
  - one of the things that has made Sparkline a pain to work with has honestly been that it's a class-based component still, and that it uses `state` where we would instead just use memoized calculations in a functional component, which means awkward state transitions. 
  - because the problem we were running into in this bug was primarily one that we solve elsewhere by early-returning before getting into the meat of configuring uPlot, it made sense to just go for it and turn this into a functional component.
  - this aligns with our goals across the repo anyway, so this is worth doing at some point.
- while I was in there, I laid the groundwork for enabling `highlightIndex` in Sparkline (which we would like to add for the new gauge in particular, #112977), but I am not going to turn any of that on just yet in this change. We probably need to cautiously roll that change out, in case it causes layout issues or there are cases where we want to leave it off altogether.

To test the fix:
- locally, go to create a new dashboard
- select gdev-testdata and pick the "Datapoints outside timerange" scenario
- open suggestions, and also render Gauge and Stat panels with this scenario

Confirm that no sparklines have broken:
- test a guage panel
- test a stat panel
- open the Table - Sparkline gdev dashboard

### CODE REVIEW

File: packages/grafana-data/src/field/fieldDisplay.ts [hunk 1]
```diff
@@ -190,10 +190,62 @@ export const getFieldDisplayValues = (options: GetFieldDisplayValuesOptions): Fi
...
+                //       prevMax = v;
+                //       maxIdx = k;
+                //     }
+                //   }
+                //   return maxIdx >= 0 ? maxIdx : undefined;
+                // }
+                default:
+                  return;
+              }
+            })();
```
Comment (fastfrwrd) [inline packages/grafana-data/src/field/fieldDisplay.ts:245]: we'll extract this to be a util that we can test separately.

**Comment by gelicia** [comment]
Can you clarify the testing steps? Based on the title, I would expect an infinite loop on `main` when performing those three actions, but I see a chart as expected. What am I missing?

**Comment by fastfrwrd** [comment]
We spoke about this in our daily stand up today, but the best way to consistently trigger this failure is to set the `newGauge` flag on when following the steps I outlined.

**Review by adela-almasan — APPROVED** [review]
