### PR TITLE
GlobalStyle: Add focus style for links

### LINKED ISSUE #36474: Links: Lack global focus styles
There is a lack of global link styles, which is an accessibility issue.
___
(Old part of the issue)

**Steps to reproduce**:
1. Try to tab through the home dashboard

**Actual Result**:

Screenshot from 2021-07-06 14-28-57

**Expected Result**

To have focus styles present around the link elements. This could possible be a wider Grafana issue than just this panel.

### PR DESCRIPTION
**Pull request by tharun208**
**What this PR does / why we need it**: Previously there is no focus style for links throughout grafana and this PR introduces the focus style for links

**Which issue(s) this PR fixes**: #36474

Fixes #36474

**Special notes for your reviewer**: As mentioned in the issue, instead of fixing the issue on the welcome screen, I added the relevant styles in the global style component to have an effect throughout the app.

### CODE REVIEW

File: packages/grafana-ui/src/themes/GlobalStyles/elements.ts [hunk 1]
```diff
@@ -120,8 +120,17 @@ export function getElementStyles(theme: GrafanaTheme2) {
       color: ${theme.colors.text.primary};
       text-decoration: none;
 
-      &:focus {
+      &:focus,
+      &:focus-visible {
+        outline: 2px dotted transparent;
```
Comment (tskarhed) [inline packages/grafana-ui/src/themes/GlobalStyles/elements.ts:125]: You should use `getFocusStyles` here, otherwise we just have duplicated code

File: packages/grafana-ui/src/themes/GlobalStyles/elements.ts [hunk 2]
```diff
@@ -120,8 +120,17 @@ export function getElementStyles(theme: GrafanaTheme2) {
...
+        outline-offset: 2px;
+        box-shadow: 0 0 0 2px ${theme.colors.background.canvas}, 0 0 0px 4px ${theme.colors.primary.main};
+        transition: all 0.2s cubic-bezier(0.19, 1, 0.22, 1);
+      }
+
+      &:focus:not(:focus-visible) {
         outline: none;
+        box-shadow: none;
```
Comment (tskarhed) [inline packages/grafana-ui/src/themes/GlobalStyles/elements.ts:133]: What's the reasoning for this?

**Review by tskarhed — CHANGES_REQUESTED** [review]

File: packages/grafana-ui/src/themes/GlobalStyles/elements.ts (hunk 2 above)
Comment (tharun208) [reply packages/grafana-ui/src/themes/GlobalStyles/elements.ts:133]: I just added this from other focus styles. do we need to add styles for `focus:not(:focus-visible)` ?

**Review by tskarhed — CHANGES_REQUESTED** [review]
It turns out it needs `display: inline-block` to work properly.

Otherwise it looks like this in several places:
Screenshot from 2021-07-14 10-00-06

I am not quite sure of the implications of putting that on a global level, let me talk to some people about it.

**Comment by tskarhed** [comment]
There is also the question of whether we want the global styles on `:focus` or `:focus-visible`. With `:focus` the focus styles appear when you click a link, which might no the desirable, whereas `:focus-visible` pretty much covers the tab navigation use case.

I'll talk to the team about it.

**Comment by torkelo** [comment]
> With :focus the focus styles appear when you click a link, which might no the desirable 

Yes! we do not want focus styles on mouse click only when using the keyboard.

**Comment by torkelo** [comment]
This is causing double focus stops / focusable thing in Cards (first one with rounded border, then one with square borders)

**Comment by tskarhed** [comment]
I guess we need to to a bit more widespread testing of this PR.

@tharun208 It looks like we're going to fix the inline-blocks wherever they appear, so we'll go with the current approach. I'd change it so that the focus styles appear on `:focus-visible` instead of `:focus` too.

**Comment by tskarhed** [comment]
> This is causing double focus stops / focusable thing in Cards (first one with rounded border, then one with square borders)

Should the fixes be done in this PR, or should we do follow-ups for that?

**Comment by tskarhed** [comment]
@tharun208 Could you try merging main again?

**Comment by axelavargas** [comment]
> > This is causing double focus stops / focusable thing in Cards (first one with rounded border, then one with square borders)
> 
> Should the fixes be done in this PR, or should we do follow-ups for that?

I have created a separate issue where we can report and follow up on the issues we encounter here :) https://github.com/grafana/grafana/issues/36908.

**Review by tskarhed — APPROVED** [review]
Okay, we're going with this! This will have a huge impact on keyboard navigation! Thank you so much!
