### PR TITLE
PieChart: Fix right-oriented legends

### LINKED ISSUE #83015: Support long metric names in Graph legend in table mode
### Discussed in https://github.com/grafana/grafana/discussions/38365

<div type='discussions-op-text'>

<sup>Originally posted by **nkondratyk** February 18, 2020</sup>
**What happened**:
For some reason I can`t see full output of the metric with Prom labels
image

**What you expected to happen**:
I would like to see full output as we can see without legend table. But without table I can`t group by max, min, avg etc..

image

**How to reproduce it (as minimally and precisely as possible)**:
Create Prom Graph with a lot of labels inside and inside visualization settings use option - "As table"
image

**Anything else we need to know?**:
No

**Environment**:
- Grafana version: 6.5.3
- Data source type & version: Prometheus 2.16.0
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Google Chrome Version 79.0.3945.130
- Grafana plugins:
- Others:
</div>

### PR DESCRIPTION
**Pull request by jesdavpet**
**What is this feature?**

Tweaks minimum widths so that right-oriented legends in table mode don't get squished in Piechart etc.

### ❌ Before ...

Screenshot 2026-01-09 at 14 01 37

Screenshot 2026-01-09 at 14 21 18

### ✅ After!

https://github.com/user-attachments/assets/b979726a-3baf-4a90-ae1f-6c95b02aec3b

Screenshot 2026-01-09 at 14 22 04

### ♻️  Regression check

Here's the panel we used to verify the original fix that caused this regression, also looks fine.

Screenshot 2026-01-09 at 14 09 00

**Why do we need this feature?**

Fixes a CSS layout bug that was introduced by https://github.com/grafana/grafana/pull/115647.

**Who is this feature for?**

All users of Grafana who have a right-oriented, table view, legend on a Piechart panel in Grafana v12.4

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/83015 https://github.com/grafana/grafana/issues/115277

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- `N/A` ~If this is a pre-GA feature, it is behind a feature toggle.~
- `N/A` ~The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.~

### CODE REVIEW

File: packages/grafana-ui/src/components/VizLegend/VizLegendTableItem.tsx [hunk 1]
```diff
@@ -134,6 +134,7 @@ const getStyles = (theme: GrafanaTheme2) => {
       label: 'LegendLabelCell',
       maxWidth: 0,
       width: '100%',
+      minWidth: theme.spacing(16),
```
Comment (jesdavpet) [inline packages/grafana-ui/src/components/VizLegend/VizLegendTableItem.tsx:137]: **note:** This `minWidth` is arbitrary and translates to around `135px`-ish. I chose it through experimentation, it looked good generally, and didn't break down until a _ridiculously small_ viewport width for me locally.

**Review by gelicia — APPROVED** [review]

File: packages/grafana-ui/src/components/VizLegend/VizLegendTableItem.tsx (hunk 1 above)
Comment (drew08t) [reply packages/grafana-ui/src/components/VizLegend/VizLegendTableItem.tsx:137]: I may be oversimplifying my understanding of things, but can we base this number on legend width?

Comment (fastfrwrd) [reply packages/grafana-ui/src/components/VizLegend/VizLegendTableItem.tsx:137]: maybe a comment to this effect just in case we need to tweak it later

**Review by fastfrwrd — APPROVED** [review]
tested it out on pie chart and bar chart, looking good.

File: packages/grafana-ui/src/components/VizLegend/VizLegendTableItem.tsx (hunk 1 above)
Comment (jesdavpet) [reply packages/grafana-ui/src/components/VizLegend/VizLegendTableItem.tsx:137]: > _"... can we base this number on legend width? ..."_

How would you propose to do so?
