### PR TITLE
Elasticsearch: Fix processing of raw_data with not-recognized time format

### LINKED ISSUE #77114: 10.2.0 - No Elasticsearch Logs / Empty @timestamp
### What happened?

Upon upgrading to 10.2.0 from 10.1.x my logs are not visible. Upon switching enableElasticsearchBackendQuerying to false, logs appear again.
This previously happened before during an upgrade from 9.4.7 to 9.5.1 https://github.com/grafana/grafana/issues/67391 however this time, the logs don't appear at all unless I view the logs in Raw Data, where I can see my logs have no timestamps associated with them (The field is empty).
As stated in the previous bug report, I am using date_nanos field time for my timestamp field.

### What did you expect to happen?

My logs are visible.

### Did this work before?

Yes however, this broke in a previous version

### How do we reproduce it?

1. Have some indexes with the timestamp field set to the date_nano field type.
2. Set up data source to the index
3. Query logs in explore or via dashboard

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.2.0
OS: Windows 11
Browser: Edge Chromium

### Grafana platform?

Kubernetes

### Datasource(s)?

Elasticsearch 7.10.2

### PR DESCRIPTION
**Pull request by ivanahuckova**
This is pretty much the same as https://github.com/grafana/grafana/pull/67767 where we fixed processing of `logs` queries with not-recognized time format. At that time, I did not realized that this is going to be an issue for `raw_data` queries as well. Therefore in this PR, we are fixing processing of unrecognized time formats for `raw_data` queries. For `raw_document` queries this is not needed as we are not parsing time field. 

**More detailed information:**
This is a bug fix for processing time field in ES on backend, when time field uses format that golang does not recognize (e.g. MM/DD/YYY, unix timestamp with nanoseconds decimal point, ...). To fix this for `raw_data` queries, we are using `fields` to get time field in `strict_date_optional_time_nanos` format that is recognizable by golang and also supports nanosecond precision.

**To test this:**

1. Run `make devenv sources=elastic`
2. Make sure that `enableElasticsearchBackendQuerying` is set to `true`
3. Create a new elastic data source pointing to `https://localhost:9200` and for time field add `@timestamp_custom`. 
4. Run `raw_data` query - you should not see `null` values in time column 
5. You can also switch to `@timestamp`, `@timestamp_unix`, `@timestamp_nanos` to ensure all formats work as expected.

Fixed: 

image

Current main (broken):

image

Fixes: https://github.com/grafana/grafana/issues/77114

### CODE REVIEW

File: pkg/tsdb/elasticsearch/data_query.go [hunk 1]
```diff
@@ -384,11 +386,16 @@ func processLogsQuery(q *Query, b *es.SearchRequestBuilder, from, to int64, defa
 	_ = addDateHistogramAgg(aggBuilder, bucketAgg, from, to, defaultTimeField)
 }
 
-func processDocumentQuery(q *Query, b *es.SearchRequestBuilder, from, to int64, defaultTimeField string) {
+func processDocumentQuery(q *Query, b *es.SearchRequestBuilder, from, to int64, defaultTimeField string, shouldAddStandardizedTimeField bool) {
 	metric := q.Metrics[0]
 	b.Sort(es.SortOrderDesc, defaultTimeField, "boolean")
 	b.Sort(es.SortOrderDesc, "_doc", "")
 	b.AddDocValueField(defaultTimeField)
+	if shouldAddStandardizedTimeField {
```
Comment (matyax) [inline pkg/tsdb/elasticsearch/data_query.go:394]: Since I don't see other calls to `processDocumentQuery`, what do you think on leaving line 100 as it was, and add here:

```suggestion
	if isRawDataQuery(q) {
```

Or

```suggestion
    shouldAddStandardizedTimeField := isRawDataQuery(q)
	if shouldAddStandardizedTimeField {
```

Comment (ivanahuckova) [reply pkg/tsdb/elasticsearch/data_query.go]: Good catch! I also like that now `processDocumentQuery` is handling all logic and `processQuery` doesn't need to care about `standardizedTimeField` 🤩

**Review by matyax — APPROVED** [review]
✨
