### PR TITLE
Users: Improve conflict error handling

### LINKED ISSUE #26934: Adding a new user with an already-existing name returns 500 instead of 409
**What happened**:
I sent an api request to create a new user whose name already exists. Grafana replied with a 500 error code.

**What you expected to happen**:
Grafana send a 409 HTTP code, like it does for new teams for example.

**How to reproduce it (as minimally and precisely as possible)**:
Create a user. Try creating a user with the same name again.

**Anything else we need to know?**:
There may be other api endpoints with the same issue. Those endpoints should send a meaningful http status code instead of a 500.

**Environment**:
- Grafana version: 7.1.3

### PR DESCRIPTION
**Pull request by joanlopez**
**What this PR does / why we need it**:

Currently, when an admin tries to create a new user with an already existing email / login, it returns a `500 Internal Server Error` with the ORM error text. So, the idea of this PR is to handle these situations properly and return a meaningful error.

**Which issue(s) this PR fixes**:

Fixes #26934

**Special notes for your reviewer**:
- Even though the issue's author requested to return a `409 Conflict`, I preferred to return the `412 Precondition Failed` because we're already returning that HTTP status code for very similar cases (i.e. trying to invite a user with an already existing email / login), so IMHO I'd try to keep the coherency among all of these cases.
- Both cases (already existing email / login) are handled as the same error because IMHO it does not worth it to have them divided (I prefer to keep it as simple as possible).

### CODE REVIEW

File: pkg/api/admin_users.go [hunk 1]
```diff
@@ -33,6 +35,10 @@ func AdminCreateUser(c *models.ReqContext, form dtos.AdminCreateUserForm) Respon
 			return Error(400, models.ErrOrgNotFound.Error(), nil)
 		}
 
+		if err == models.ErrUserAlreadyExists {
+			return Error(412, fmt.Sprintf("User with email %s and/or login %s already exists", form.Email, form.Login), err)
```
Comment (sakjur) [inline pkg/api/admin_users.go:39]: We call the login param username in the form. I also changed `and/or` to just `or`, since there's nothing that implies that the or is exclusive and it's a slightly more natural sentence (:joy: not sure any sentence with an email in the middle is natural).

And consider adding quotes around the email and username if the user uses whitespace in them to make the error clearer (not sure we allow that, but in case)

```suggestion
			return Error(412, fmt.Sprintf("User with email '%s' or username '%s' already exists", form.Email, form.Login), err)
```

**Review by sakjur — COMMENTED** [review]
:+1: This looks really good to me. I have some minor feedback on the user facing error message, but other than that this is a really good patch.

I like that this logic is kept to a few lines, like we discussed earlier the additional benefits of having a longer logic to be able to tell the admin that it was the email in particular or the username specifically that didn't match.

I also appreciate how well these tests integrates with the rest, I'm working on converting these tests to testify in another PR, but it's more work than I'd anticipated so it's taking some time.

You don't have to mention the bug you're fixing in the title, when we squash-merge this that'll be confusing as you'll have a commit message of `API: Improve error handling (#26934) (#26958)` 🙂

File: pkg/api/admin_users.go (hunk 1 above)
Comment (joanlopez) [reply pkg/api/admin_users.go]: Thanks for the suggestion! Indeed, your sentence really looks more natural 👌

**Review by sakjur — APPROVED** [review]
LGTM. Let's see if someone from the backend team has some feedback before merging 🙂

File: pkg/services/sqlstore/user_test.go [hunk 2]
```diff
@@ -541,6 +541,28 @@ func TestUserDataAccess(t *testing.T) {
 					}
 				})
 			})
+
+			Convey("When creating a new user with an already existing email returns error", func() {
+				createUserCmd := &models.CreateUserCommand{
+					Email:        "user2@test.com",
```
Comment (aknuds1) [inline pkg/services/sqlstore/user_test.go:547]: Where is user2@test.com already inserted into the database here? Couldn't find it.

File: pkg/services/sqlstore/user_test.go [hunk 3]
```diff
@@ -541,6 +541,28 @@ func TestUserDataAccess(t *testing.T) {
...
+					SkipOrgSetup: true,
+				}
+				err := CreateUser(context.Background(), createUserCmd)
+				So(err, ShouldEqual, models.ErrUserAlreadyExists)
+			})
+
+			Convey("When creating a new user with an already existing login returns error", func() {
+				createUserCmd := &models.CreateUserCommand{
+					Email:        "user-2@test.com",
+					Name:         "user2",
```
Comment (aknuds1) [inline pkg/services/sqlstore/user_test.go:559]: Where is user2 already inserted into the database here? Couldn't find it.

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Generally looks good, but left some suggestions for improvement.

**Comment by aknuds1** [comment]
> LGTM. Let's see if someone from the backend team has some feedback before merging

Thank you @sakjur, just finished my review :)

File: pkg/services/sqlstore/user_test.go [hunk 4]
```diff
@@ -541,6 +541,28 @@ func TestUserDataAccess(t *testing.T) {
 					}
 				})
 			})
+
+			Convey("When creating a new user with an already existing email returns error", func() {
```
[the remark this answers is not in the document]
Comment (joanlopez) [reply pkg/services/sqlstore/user_test.go]: Thanks for the suggestion, I already applied the suggested changes 👌

File: pkg/services/sqlstore/user_test.go (hunk 2 above)
Comment (joanlopez) [reply pkg/services/sqlstore/user_test.go]: Sorry, on the previous version I included these tests under the `Given 5 users` group, which, in fact, is not really clear. That's the reason it wasn't clear there's a user with `Email` equals to `user", i, "@test.com` where `i` is `0...4` and the same for the `Login` attribute equals to `"loginuser", i`.

Now, I refactored the code to create an specific Convey section for these two tests.

File: pkg/services/sqlstore/user_test.go (hunk 3 above)
Comment (joanlopez) [reply pkg/services/sqlstore/user_test.go]: Ditto 👉 https://github.com/grafana/grafana/pull/26958#discussion_r469511437

**Comment by joanlopez** [comment]
> > LGTM. Let's see if someone from the backend team has some feedback before merging
> 
> Thank you @sakjur, just finished my review :)

Feedback applied! Can you @aknuds1  PTAL? Thanks! 🙏

File: pkg/services/sqlstore/user_test.go [hunk 5]
```diff
@@ -590,6 +568,39 @@ func TestUserDataAccess(t *testing.T) {
...
+
+		Convey("Given one user", func() {
+			var err error
+			createUserCmd := &models.CreateUserCommand{
+				Email: fmt.Sprint("user", "@test.com"),
+				Name:  "user",
+				Login: "user",
+			}
+			err = CreateUser(context.Background(), createUserCmd)
+			So(err, ShouldBeNil)
```
Comment (aknuds1) [inline pkg/services/sqlstore/user_test.go:580]:
```suggestion
			createUserCmd := &models.CreateUserCommand{
				Email: "user@test.com",
				Name:  "user",
				Login: "user",
			}
			err := CreateUser(context.Background(), createUserCmd)
			So(err, ShouldBeNil)
```

File: pkg/services/sqlstore/user_test.go [hunk 6]
```diff
@@ -590,6 +568,39 @@ func TestUserDataAccess(t *testing.T) {
...
+
+			Convey("When trying to create a new user with the same email, an error is returned", func() {
+				createUserCmd := &models.CreateUserCommand{
+					Email:        fmt.Sprint("user", "@test.com"),
+					Name:         "user2",
+					Login:        "user2",
+					SkipOrgSetup: true,
+				}
```
Comment (aknuds1) [inline pkg/services/sqlstore/user_test.go:588]:
```suggestion
				createUserCmd := &models.CreateUserCommand{
					Email:        "user@test.com",
					Name:         "user2",
					Login:        "user2",
					SkipOrgSetup: true,
				}
```

File: pkg/services/sqlstore/user_test.go [hunk 7]
```diff
@@ -590,6 +568,39 @@ func TestUserDataAccess(t *testing.T) {
...
+				So(err, ShouldEqual, models.ErrUserAlreadyExists)
+			})
+
+			Convey("When trying to create a new user with the same login, an error is returned", func() {
+				createUserCmd := &models.CreateUserCommand{
+					Email:        fmt.Sprint("user2", "@test.com"),
+					Name:         "user2",
+					Login:        "user",
+					SkipOrgSetup: true,
+				}
```
Comment (aknuds1) [inline pkg/services/sqlstore/user_test.go:599]:
```suggestion
				createUserCmd := &models.CreateUserCommand{
					Email:        "user2@test.com",
					Name:         "user2",
					Login:        "user",
					SkipOrgSetup: true,
				}
```

**Review by aknuds1 — CHANGES_REQUESTED** [review]

File: pkg/api/admin_users.go [hunk 8]
```diff
@@ -29,10 +32,14 @@ func AdminCreateUser(c *models.ReqContext, form dtos.AdminCreateUserForm) Respon
 	}
 
 	if err := bus.Dispatch(&cmd); err != nil {
-		if err == models.ErrOrgNotFound {
+		if errors.Is(err, models.ErrOrgNotFound) {
 			return Error(400, models.ErrOrgNotFound.Error(), nil)
```
Comment (aknuds1) [inline pkg/api/admin_users.go:36]: Do you mind updating this as well? I don't see any point in fixating the error message, when we can get it from `err`:
```suggestion
			return Error(400, err.Error(), nil)
```

File: pkg/api/admin_users_test.go [hunk 9]
```diff
@@ -259,6 +259,26 @@ func TestAdminApiEndpoint(t *testing.T) {
 			})
 		})
 	})
+
+	Convey("When a server admin attempts to create a user with an already existing email / login", t, func() {
```
Comment (aknuds1) [inline pkg/api/admin_users_test.go:263]:
```suggestion
	Convey("When a server admin attempts to create a user with an already existing email/login", t, func() {
```

File: pkg/services/sqlstore/user_test.go [hunk 10]
```diff
@@ -568,6 +568,38 @@ func TestUserDataAccess(t *testing.T) {
 				So(query.Result.IsAdmin, ShouldEqual, true)
 			})
 		})
+
+		Convey("Given one user", func() {
+			createUserCmd := &models.CreateUserCommand{
+				Email: "user@test.com",
+				Name:  "user",
+				Login: "user",
+			}
```
Comment (aknuds1) [inline pkg/services/sqlstore/user_test.go:577]:
```suggestion
			const email = "user@test.com"
			const username = "user"
			createUserCmd := &models.CreateUserCommand{
				Email: email,
				Name:  "user",
				Login: username,
			}
```

File: pkg/services/sqlstore/user_test.go [hunk 11]
```diff
@@ -568,6 +568,38 @@ func TestUserDataAccess(t *testing.T) {
...
+			err := CreateUser(context.Background(), createUserCmd)
+			So(err, ShouldBeNil)
+
+			Convey("When trying to create a new user with the same email, an error is returned", func() {
+				createUserCmd := &models.CreateUserCommand{
+					Email:        "user@test.com",
+					Name:         "user2",
+					Login:        "user2",
+					SkipOrgSetup: true,
+				}
```
Comment (aknuds1) [inline pkg/services/sqlstore/user_test.go:587]:
```suggestion
				createUserCmd := &models.CreateUserCommand{
					Email:        email,
					Name:         "user2",
					Login:        "user2",
					SkipOrgSetup: true,
				}
```

File: pkg/services/sqlstore/user_test.go [hunk 12]
```diff
@@ -568,6 +568,38 @@ func TestUserDataAccess(t *testing.T) {
...
+				err := CreateUser(context.Background(), createUserCmd)
+				So(err, ShouldEqual, models.ErrUserAlreadyExists)
+			})
+
+			Convey("When trying to create a new user with the same login, an error is returned", func() {
+				createUserCmd := &models.CreateUserCommand{
+					Email:        "user2@test.com",
+					Name:         "user2",
+					Login:        "user",
```
Comment (aknuds1) [inline pkg/services/sqlstore/user_test.go:596]:
```suggestion
					Login:        username,
```

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Almost there, but I left suggestions for a couple of adjustments I'd like to see.

File: pkg/api/admin_users.go (hunk 8 above)
Comment (joanlopez) [reply pkg/api/admin_users.go:36]: Well, I'd say it depends. With the current implementation, it's true that both statements are equivalent. However, the usage of `errors.Is` is more recommended than the equality comparator precisely to get it working despite of eventual error wraps. So, with the same reasoning, I'm not sure if returning the message present on given error is what we really want.

Comment (aknuds1) [reply pkg/api/admin_users.go:36]: Personally I think it makes sense to return any wrapping error message, since it should wrap the error for a reason. The wrapped error message should also include `models.ErrOrgNotFound.Error()`. @sakjur @papagian WDYT?

**Review by aknuds1 — APPROVED** [review]
Looks good now, thanks! Still wondering about my remaining comment though, if that's a change we ought to make.

**Comment by joanlopez** [comment]
> Looks good now, thanks! Still wondering about my remaining comment though, if that's a change we ought to make.

Sure, let's wait for the comments. I'm completely open to apply what we decide on consensus, I raised the question in order to clarify it all of us together.

Thanks for you feedback & suggestions!! 😇 🙏

File: pkg/api/admin_users.go (hunk 8 above)
Comment (sakjur) [reply pkg/api/admin_users.go:36]: I'm pro changing to `err.Error()`.

The only reason I can see why we wouldn't want to use `err.Error()` is to prevent exposure of secrets or over-technical error messages, and since this is an operation only available to admins I don't think that should be a concern.

Alternatively info log `err.Error()` and then return `models.ErrOrgNotFound.Error()`, that way we're not throwing away possibly useful debug information (Does the org not exist? Did the database crash during querying? Timeout while looking?)

Comment (papagian) [reply pkg/api/admin_users.go:36]: I agree with @aknuds1; I think we don't want to loose this information.

Comment (aknuds1) [reply pkg/api/admin_users.go:36]: @sakjur I guess that is also my one uncertainty, divulging secrets. My current thinking is that an error wrapping ErrOrgNotFound shouldn't divulge secrets, since it's meant for translating into an API error. That's my thinking around API error design at least, to have certain error types which are meant to be passed on via the API. I'm open to opposing points of view, though. I'm not super used to Go wrapped errors yet, coming from an exception background.

Comment (joanlopez) [reply pkg/api/admin_users.go:36]: Okay, I will change it to `err.Error()`.

Thanks for your point of view!

Comment (sakjur) [reply pkg/api/admin_users.go]: @aknuds1 I agree! If we want to send sensitive/debugging information with the error we should probably extend the error type to have something else than `.Error()` to access that information.

Comment (aknuds1) [reply pkg/api/admin_users.go]: That's a good point @sakjur! It's definitely worth thinking about.

**Comment by papagian** [comment]
I think this should change too:
https://github.com/grafana/grafana/blob/3798ac903d04a903b1cf09656af56d24864bbe5f/pkg/api/org_invite.go#L184

Also, this query has become redundant; it can be treated by the [subsequent](https://github.com/grafana/grafana/blob/3798ac903d04a903b1cf09656af56d24864bbe5f/pkg/api/signup.go#L88
) `CreateUserCommand` query
https://github.com/grafana/grafana/blob/3798ac903d04a903b1cf09656af56d24864bbe5f/pkg/api/signup.go#L82

**Comment by papagian** [comment]
I have also noticed some inconsistency with the return status codes in similar cases:
https://github.com/grafana/grafana/blob/3798ac903d04a903b1cf09656af56d24864bbe5f/pkg/api/signup.go#L29
https://github.com/grafana/grafana/blob/3798ac903d04a903b1cf09656af56d24864bbe5f/pkg/api/signup.go#L84

I'm a bit reluctant change them but I think that we can decide if we want actually `412` to be returned for the cases where currently `500` is returned.
@aknuds1 @sakjur any thoughts?

**Comment by sakjur** [comment]
@papagian Let's keep the scope down by just changing 500->412 for now?

For the end-user registration forms I think ideally we wouldn't tell the user if a user with that email address is already signed up, but that's a wider discussion 🙂

**Comment by aknuds1** [comment]
@papagian Well, [422](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422) sounds like the wrong status code at least. [401 unauthorized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) I'm unsure about.

**Comment by aknuds1** [comment]
But I guess I agree with @sakjur about keeping the scope down.

**Comment by joanlopez** [comment]
Is there already any doc about HTTP status codes conventions?

IMHO, these incoherences (up to 4-5 different status codes for -almost- the same) are common when dealing with HTTP APIs, so I guess the best to deal with it is at least formalize some conventions. Otherwise, we are at the risk of having new incoherences on the future.

**Comment by aknuds1** [comment]
@joanlopez I'm not aware of any doc, but it sounds like we might need to ensure some consistency. Good news is that we are working on improving the API specifications, including functional tests :)

**Comment by joanlopez** [comment]
So, to avoid converting this PR in an endless task, what do you think about focusing on:

1. Adding the `models.ErrUserAlreadyExists` -> `412` error handling at:
https://github.com/grafana/grafana/blob/3798ac903d04a903b1cf09656af56d24864bbe5f/pkg/api/org_invite.go#L184

2. Removing the pre-check query and handling errors properly (without modifying the current returned HTTP status codes) at:
https://github.com/grafana/grafana/blob/3798ac903d04a903b1cf09656af56d24864bbe5f/pkg/api/signup.go#L84

@aknuds1 @papagian @sakjur

**Comment by papagian** [comment]
> So, to avoid converting this PR in an endless task, what do you think about focusing on:
> 
> 1. Adding the `models.ErrUserAlreadyExists` -> `412` error handling at:
>    https://github.com/grafana/grafana/blob/3798ac903d04a903b1cf09656af56d24864bbe5f/pkg/api/org_invite.go#L184
> 2. Removing the pre-check query and handling errors properly (without modifying the current returned HTTP status codes) at:
>    https://github.com/grafana/grafana/blob/3798ac903d04a903b1cf09656af56d24864bbe5f/pkg/api/signup.go#L84
> 
> @aknuds1 @papagian @sakjur

sounds. good to me!

**Review by sakjur — APPROVED** [review]

**Review by papagian — APPROVED** [review]
LGTM!

**Review by aknuds1 — APPROVED** [review]
