### PR TITLE
Cloudwatch: Fix template variables in variable queries

### LINKED ISSUE #48136: CloudWatch: Variable editor should replace template variables
When I replaced the variable editor, I ended up removing code that did template variable replacement in filters. This code should be put back for ec2InstanceAttributes and resourceARNs.

### PR DESCRIPTION
**Pull request by iwysiu**
**What this PR does / why we need it**:
When I [implemented the new variable editor](https://github.com/grafana/grafana/pull/46943), I removed two calls to templateSrv that were never put back, and getEC2InstanceAttribute and getResourceARNs were not replacing template variables.

**Which issue(s) this PR fixes**:

Fixes #48136

**Special notes for your reviewer**:

### CODE REVIEW

**Review by andresmgot — APPROVED** [review]
LGTM

File: public/app/plugins/datasource/cloudwatch/datasource.ts [hunk 1]
```diff
@@ -125,7 +125,7 @@ export class CloudWatchDatasource
     this.logsTimeout = instanceSettings.jsonData.logsTimeout || '15m';
     this.sqlCompletionItemProvider = new SQLCompletionItemProvider(this, this.templateSrv);
     this.metricMathCompletionItemProvider = new MetricMathCompletionItemProvider(this, this.templateSrv);
-    this.variables = new CloudWatchVariableSupport(this);
+    this.variables = new CloudWatchVariableSupport(this, this.templateSrv);
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/datasource.ts:128]: It feels like because you already pass it `this` that templateSrv should already be passed in as an argument to CloudWatchVariableSupport, am I misunderstanding?

**Review by sarahzinger — APPROVED** [review]
seems cool, one quick suggestion!

File: public/app/plugins/datasource/cloudwatch/datasource.ts (hunk 1 above)
Comment (iwysiu) [reply public/app/plugins/datasource/cloudwatch/datasource.ts:128]: Since `templateSrv` is a private variable, it can't be accessed by `CloudWatchVariableSupport` unless it's passed separately. It was already being passed separately on lines 126 and 127,  so I assumed that it was private for a reason.
