### PR TITLE
Alerting: Fix template query validation logic

### LINKED ISSUE #20821: Template check in alert tab is incorrect
**What happened**:

in a panel, i have two query A and B.
A is a template query, and B is a normal query
when i add an alert with two condition, one is about query A, and another one is about query B
it's should warning alert do not support template variables, but not

**What you expected to happen**:

warning warning alert do not support template variables

**How to reproduce it (as minimally and precisely as possible)**:

add a panel with query A, B. A is template query and B is normal query.
add alert for panel with condition 1 about query A, and condition 2 about query B.
warning will appear when have only condition 1, after add condtion 2, warning disappeared

**Anything else we need to know?**:

it's seem like in `public/app/features/alerting/AlertTabCtrl.ts` loop condition check logic is incorrect

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: prometheus
- OS Grafana is installed on: linux
- User OS & Browser: chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by okhowang**
**What this PR does / why we need it**:

validateModel in AlertTabCtrl has bug when there were many conditions.

foundTarget is a outer variable which was same for each datasource closure

and in each closure error may be overrided when any condition is valid

**Which issue(s) this PR fixes**:

Fixes #20821

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by marefr** [comment]
Please open a bug report explaining what kind of problem you have and reference that issue in the PR description `Fixes #<issue nr>`. We wont review this until that is fixed.

File: public/app/features/alerting/AlertTabCtrl.ts [hunk 1]
```diff
@@ -272,20 +273,46 @@ export class AlertTabCtrl {
...
+            })(foundTarget)
+          )
+          .then(
+            err =>
+              new Promise((resolve, reject) => {
+                if (err) {
+                  reject(err);
+                } else {
+                  resolve();
+                }
```
Comment (torkelo) [inline public/app/features/alerting/AlertTabCtrl.ts]: this looks pretty pointless, why not just throw error in the callback above?

**Review by torkelo — CHANGES_REQUESTED** [review]
Code could be simplified a bit (maybe move out to separate smaller functions , and by using async & await

File: public/app/features/alerting/AlertTabCtrl.ts (hunk 1 above)
Comment (okhowang) [reply public/app/features/alerting/AlertTabCtrl.ts]: i rewrite it by $q

**Review by torkelo — APPROVED** [review]

File: public/app/features/alerting/AlertTabCtrl.ts [hunk 2]
```diff
@@ -318,6 +334,7 @@ export class AlertTabCtrl {
         return this.$q.when(result);
       }
     }
+    return undefined;
```
Comment (torkelo) [inline public/app/features/alerting/AlertTabCtrl.ts]: why did you add these?

File: public/app/features/alerting/AlertTabCtrl.ts [hunk 3]
```diff
@@ -272,20 +274,34 @@ export class AlertTabCtrl {
...
+    this.$q.all(promises).then(
+      () => {
+        this.error = '';
+        this.$scope.$apply();
+      },
+      e => {
+        this.error = e;
+        this.$scope.$apply();
+      }
+    );
```
Comment (torkelo) [inline public/app/features/alerting/AlertTabCtrl.ts]: think this could be improved (refactored) further by extract function, and using async await, try catch. But this is fine for now.

File: public/app/features/alerting/AlertTabCtrl.ts (hunk 2 above)
Comment (okhowang) [reply public/app/features/alerting/AlertTabCtrl.ts]: i add type for $q: IQService
and here will get ts error: for not all branch return value

File: public/app/features/alerting/AlertTabCtrl.ts (hunk 3 above)
Comment (okhowang) [reply public/app/features/alerting/AlertTabCtrl.ts]: I think for loop with await is not a good practice

**Comment by okhowang** [comment]
can we merge it?

**Comment by aknuds1** [comment]
@torkelo This ready to merge?

**Review by torkelo — APPROVED** [review]
