### PR TITLE
Explore: Fix showing of results of queries in table

### LINKED ISSUE #23657: Explore table view doesn't show data
Running a prometheus query, the instance query in explore table view says "returned 0 rows" when it did in fact return rows:

Screenshot 2020-04-17 at 17 35 55

Version: Grafana v7.0.0-254070a2pre (43fc6c3a17)

### PR DESCRIPTION
**Pull request by ivanahuckova**
*What this PR does / why we need it**:
**Context:**
In [ResultProcessor](https://github.com/grafana/grafana/blob/master/public/app/features/explore/utils/ResultProcessor.ts#L53) when we are creating table results, we filter out all frames that are single-value time series -> we are checking if it the data frame has exactly 2 fields and if the first one is time. So in case of https://github.com/grafana/grafana/issues/23657, if Prometheus instant query doesn't have any metrics (*metric name is erased when you do aggregation in Prometheus*),  its data frame has only 2 fields and the first one is time. Therefore, as single-value time series, it is not shown in the Explore table. 

And checking if data frame has exactly 2 fields and the first one is time, filters out a lot of results of queries of other datasources (elastic, influxdb,...).

**Solution:**
After the discussion, we have agreed that solution should meet following criteria:

- In Explore table we want to show all time series results
- EXCEPTION 1: For Prometheus, we want to show in table results of instant queries
- EXCEPTION 2: For Elastic, if we do logs query, we want to show aggregation only in graph and logs fields in table

I have created a DataFrame meta property _preferredVisualisationType_ (more generic and usable across the whole Grafana than _hideInExploreTable_ ). In ResultProcessor, I have added `shouldShowInTable` function that determines if DataFrame should be shown Explore table. It checks if DataFrame has PreferredVisualisationType meta property, and if it has, it should equal to table - otherwise it shouldn't be shown. If it doesn't have PreferredVisualisationType meta property, then it should be shown in table .

When processing results of EXCEPTION 1 and 2, I have set the meta property PreferredVisualisationType to 'graph', therefore they are not going to be shown in Explore table.  

**hideInExploreTable vs preferredVisualisationType:**
After the discussion, I have decided to use preferredVisualisationType instead of hideInExploreTable as we would like to eliminate Explore-specific-exceptions as much as possible. PreferredVisualisationType meta property is more generic and therefore it can be used in the future across whole Grafana. 
Possible other use-cases - showing users the recommended visualisation types. 

**Tested with following datasources:**
✅Prometheus
✅Loki
✅Graphite
✅Influx
✅Elastic7
✅Elastic6 (found and created an [issue with showing of results in table](https://github.com/grafana/grafana/issues/24077) that is not connected to this PR and reproducible in play)

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/23657

### CODE REVIEW

File: public/app/features/explore/utils/ResultProcessor.ts [hunk 1]
```diff
@@ -128,8 +127,25 @@ export function isTimeSeries(frame: DataFrame, datasource?: string): boolean {
   return false;
 }
 
+/* In Explore table, we don't want to show time-series.
```
Comment (torkelo) [inline public/app/features/explore/utils/ResultProcessor.ts:130]: This is not true , we want to show time series in table!!!  But we can’t because then it would show that instead of the instant results for Prometheus . But for ALL other datasources we want to show the table data for no matter what

File: public/app/features/explore/utils/ResultProcessor.ts [hunk 2]
```diff
@@ -128,8 +127,25 @@ export function isTimeSeries(frame: DataFrame, datasource?: string): boolean {
...
+function shouldShowInTable(frame: DataFrame, datasource?: string) {
+  // DataFrames with exactly 2 fields, when first field.type === time are time-series.
+  if (frame.fields.length === 2 && frame.fields[0].type === FieldType.time) {
+    // Hack: Prometheus instant vectors's value has always length === 1.
+    // https://prometheus.io/docs/prometheus/latest/querying/api/#instant-vectors
+    if (datasource && datasource === 'prometheus' && frame.length === 1) {
+      return true;
+    }
+    return false;
+  }
```
Comment (torkelo) [inline public/app/features/explore/utils/ResultProcessor.ts:142]: I would in the prometheus data source  set a meta field on the time series results that should be hidden in explore. Then we can always show any data in the table (that does not have a hideExploreTable property on them)

File: public/app/features/explore/utils/ResultProcessor.ts (hunk 1 above)
Comment (ivanahuckova) [reply public/app/features/explore/utils/ResultProcessor.ts:130]: Yeah, my comment wasn't clear. I meant  **In Explore table, we don't want to show single-value time series (series with exactly 2 fields - time and value)**. But based on your comment, that is not true as well.

Currently (on master), we show in table only time series with 3+ fields. So as you can see [here](https://play.grafana.org/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22InfluxDB%22,%7B%22datasource%22:%22InfluxDB%22,%22policy%22:%22default%22,%22resultFormat%22:%22time_series%22,%22orderByTime%22:%22ASC%22,%22tags%22:%5B%5D,%22groupBy%22:%5B%7B%22type%22:%22time%22,%22params%22:%5B%22$__interval%22%5D%7D,%7B%22type%22:%22fill%22,%22params%22:%5B%22null%22%5D%7D%5D,%22select%22:%5B%5B%7B%22type%22:%22field%22,%22params%22:%5B%22value%22%5D%7D,%7B%22type%22:%22mean%22,%22params%22:%5B%5D%7D%5D%5D,%22measurement%22:%22logins.count%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D), Explore table doesn't have any series in table. But we would like to see something like this, right?:

image

So maybe the staring point should be clarifying what we want/do't want to show. Based on my observation and your feedback:
- Prometheus - in table, we want to show only results of instant queries.
- Elastic - in table, if we have data frames with time series with 3+ fields, show that in table. If we don't, should we show single-value time series (which we use for graph)?
- Influx and rest of the data sources - in table, we want to show all time series.

**Review by torkelo — CHANGES_REQUESTED** [review]
The fundamental problem is that we want to show data in explore table if the table is expanded in explore, no matter form the data response is in (how many fields). But can't as it would break showing only instant query results for prometheus. 

I think it's time we fixed this bug/limitation in explore where the table does not work 95% of data sources. The way think we should fix this is to set a DataFrame meta property like "hideInExploreTable" on the time series results for prometheus. Then we can filter those out and show everything else.

**Comment by ivanahuckova** [comment]
@torkelo Can you please review again. I have explained all context and decisions in [here](https://github.com/grafana/grafana/pull/24018#issue-410294489).

File: packages/grafana-data/src/types/data.ts [hunk 3]
```diff
@@ -28,6 +30,9 @@ export interface QueryResultMeta {
   /** Used to track transformation ids that where part of the processing */
   transformations?: string[];
 
+  /** Currently used to show results in Explore only in preferred visualisation option */
+  preferredVisualisationType?: PreferredVisualisationType;
```
Comment (torkelo) [inline packages/grafana-data/src/types/data.ts:34]: @ryantxu just a heads up we are adding this to query meta. It's nice solution for data sources that return different results sets (data frames) for the same query to direct explore to visualize them in the correct display (time series to graph and the instant query to table). And similar case for elasticsearch logs where one query returns time series and logs result in two different data frames. 

This now finally makes explore show time series in the table as well for other data sources that only return time series (removing the filter from the explore table only made it show non-time series).

**Review by torkelo — APPROVED** [review]
Looks good!
