### PR TITLE
Alerting: Remove dependency on alerting package in definitions

### LINKED ISSUE #63582: Alerting: API code generation tooling produces invalid server stubs
**What happened**:

The tooling that generates OpenAPI and server stubs is broken. It appears to be picking up and merging data from an OpenAPI yaml file from upstream: https://github.com/prometheus/alertmanager/blob/main/api/v2/openapi.yaml

Running the tooling now replaces the doc's description with the one from upstream. You get:
```
"description": "API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)\nSchemes:\nhttp",
```

It also tries to add multiple new endpoints to Grafana that don't exist from the root - ones like `/api/v2/alerts` that come from prometheus. Right now, we are blocked from adding new endpoints or modifying the swagger docs for existing endpoints.

**How to reproduce it (as minimally and precisely as possible)**:

On main:
1. go to `pkg/services/ngalert/api/tooling`
2. `make clean`
3. `make`
4. look at post.json

**Anything else we need to know?**:

**Environment**:
- Grafana version: main

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What is this feature?**
This is the last part major of refactoring to clean up the dependency graph of the `definitions` package because changes in packages affect the swagger generation and can lead to an unexpected outcome. 
In this PR I 
1. move methods of EmbeddedContactPoint to provisioning package.
- method `Valid` converted to a function `ValidateContactPoint`
- method `SecretKeys` converted to a function `GetSecretKeysForContactPointType` and updated to require only contact point type.
- method `ExtractSecrets` converted to a function `RemoveSecretsForContactPoint` to better reflect that the function mutates the structure.

2. Move models for resource exporting `AlertingFileExport` from provisioning to definitions to make sure the correct direction of the import.

Fixes https://github.com/grafana/grafana/issues/63582

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.
- [x] There are no known compatibility issues with older supported versions of Grafana, or plugins.
- [x] It passes the [Hosted Grafana feature readiness review](https://docs.google.com/document/d/1QL9Ly8KnXzpb6ISbg49pTODRO5mhA5tkkfIZVX6pqQU/edit) for observability, scalability, performance, and security.

### CODE REVIEW

File: pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go [hunk 1]
```diff
@@ -217,4 +215,41 @@ type AlertRuleGroup struct {
...
+	Rules    []AlertRuleExport `json:"rules" yaml:"rules"`
+}
+
+// AlertRuleExport is the provisioned file export of models.AlertRule.
+type AlertRuleExport struct {
+	UID          string              `json:"uid" yaml:"uid"`
+	Title        string              `json:"title" yaml:"title"`
+	Condition    string              `json:"condition" yaml:"condition"`
+	Data         []AlertQueryExport  `json:"data" yaml:"data"`
+	DashboardUID string              `json:"dasboardUid,omitempty" yaml:"dashboardUid,omitempty"`
```
Comment (alexweav) [inline pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go:238]: might cause merge conflicts with @JacobsonMT https://github.com/grafana/grafana/pull/65143 just to note

File: pkg/services/provisioning/alerting/file/rules_types.go [hunk 2]
```diff
@@ -176,88 +177,45 @@ func (queryV1 *QueryV1) mapToModel() (models.AlertQuery, error) {
...
-	QueryType         string                   `json:"queryType,omitempty" yaml:"queryType,omitempty"`
-	RelativeTimeRange models.RelativeTimeRange `json:"relativeTimeRange,omitempty" yaml:"relativeTimeRange,omitempty"`
-	DatasourceUID     string                   `json:"datasourceUid" yaml:"datasourceUid"`
-	Model             map[string]interface{}   `json:"model" yaml:"model"`
-}
-
 // NewAlertingFileExport creates an AlertingFileExport DTO from []AlertRuleGroupWithFolderTitle.
-func NewAlertingFileExport(groups []AlertRuleGroupWithFolderTitle) (AlertingFileExport, error) {
-	f := AlertingFileExport{APIVersion: 1}
+func NewAlertingFileExport(groups []AlertRuleGroupWithFolderTitle) (definitions.AlertingFileExport, error) {
```
Comment (alexweav) [inline pkg/services/provisioning/alerting/file/rules_types.go:181]: I think this converter and its helpers should also move to `ngalert/api/compat.go`, or perhaps a new file in that package, to correspond with the structs moving to `definitions`. The only caller of this is in `api/api_provisioning.go`, so this function isn't really any different to `ApiAlertRuleGroupFromAlertRuleGroup` in terms of purpose and dependencies

Comment (JacobsonMT) [reply pkg/services/provisioning/alerting/file/rules_types.go:181]: I think one of the main reasons for this package to exist was to keep `AlertRuleGroupV1` and the various `Alert...Export` struct definitions close to eachother.

Since we're now separating them I think we can probably get rid of this package now, if we wanted to. Any other dependency reasons that necessitated its creation no longer exist from what I can see. It should be as simple as moving `AlertRuleGroupWithFolderTitle` to `services/ngalert/models` and then putting `services/provisioning/alerting/file/rules_types.go` + test file back into `services/provisioning/alerting`.

File: pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go [hunk 3]
```diff
@@ -217,4 +215,41 @@ type AlertRuleGroup struct {
...
+	PanelID      int64               `json:"panelId,omitempty" yaml:"panelId,omitempty"`
+	NoDataState  NoDataState         `json:"noDataState" yaml:"noDataState"`
+	ExecErrState ExecutionErrorState `json:"execErrState" yaml:"execErrState"`
+	For          Duration            `json:"for" yaml:"for"`
```
Comment (JacobsonMT) [inline pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go:242]: This was changed from upstream `model.Duration` to our own version, the semantics are not the same. It's the reason some tests are failing.

**Review by JacobsonMT — CHANGES_REQUESTED** [review]
Main issue is the change from upstream `model.Duration` to our own version in `AlertRuleExport`, the comment about removing `pkg/services/provisioning/alerting/file` is optional and at your discretion.

File: pkg/services/provisioning/alerting/file/rules_types.go (hunk 2 above)
Comment (yuri-tceretian) [reply pkg/services/provisioning/alerting/file/rules_types.go]: moved AlertRuleGroupWithFolderTitle to ngalert/models and adapters to compat in ngalert/api

File: pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go (hunk 3 above)
Comment (yuri-tceretian) [reply pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go]: fixed!

File: pkg/services/provisioning/alerting/file/rules_types.go (hunk 2 above)
Comment (yuri-tceretian) [reply pkg/services/provisioning/alerting/file/rules_types.go]: moved files back to package where they used to be before https://github.com/grafana/grafana/pull/58623

**Review by JacobsonMT — APPROVED** [review]
LGTM :rocket:

**Review by alexweav — APPROVED** [review]
LGTM!
