### PR TITLE
Gauge: Fixes issue with all null values cause min & max to be null

### LINKED ISSUE #25279: Gauge: Panel throws error when all values are null
**What happened**:
When the query returns no data, the Gauge visualization throws the error "Cannot read Property 'toFixed' of undefined instead of showing 'No Data'. 
image
image

These  2 panels have the same query, and everything works well when there is data
image

**What you expected to happen**:
'No Data' message displayed, like it is in other panels.

**How to reproduce it (as minimally and precisely as possible)**:
Use Gauge visalization on a query returning no data.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #25279

* [x] Adds e2e test for gauge, checks for rendered gauges & no errors 

The bug was caused by all null series causing min & max to be null. I do not like this fix (in Gauge.tsx). Would prefer to either use:
* [getFieldConfigWithMinMax](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/field/scale.ts) But this is not possible as Gauge does not have access to the full source field only FieldConfig. 
* or some how modify [getFieldDisplayValues](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/field/fieldDisplay.ts#L133) to ensure a default min & max.

### CODE REVIEW

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderCorner.tsx [hunk 1]
```diff
@@ -78,9 +79,12 @@ export class PanelHeaderCorner extends Component<Props> {
 
   renderCornerType(infoMode: InfoMode, content: PopoverContent, onClick?: () => void) {
     const theme = infoMode === InfoMode.Error ? 'error' : 'info';
+    const className = `panel-info-corner panel-info-corner--${infoMode.toLowerCase()}`;
+    const ariaLabel = selectors.components.Panels.Panel.headerCornerInfo(infoMode.toLowerCase());
```
Comment (hugohaggmark) [inline public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderCorner.tsx:83]: Nice!

**Review by hugohaggmark — APPROVED** [review]
This looks good 🎉 , not very familiar with Gauge but maybe we should add a test cases for the when min & max are `null`?

File: e2e/suite1/specs/gauge.spec.ts [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+  scenario: () => {
+    // open Panel Tests - Gauge
+    e2e.flows.openDashboard({ uid: '_5rDmaQiz' });
+
+    cy.wait(1000);
+
+    // check that gauges are rendered
+    e2e()
+      .get('body')
+      .find(`.flot-base`)
```
Comment (dprokop) [inline e2e/suite1/specs/gauge.spec.ts:18]: Wonder if we maybe could introduce label selector for Gauge viz rather than relying on this confusing class name? WDYT?

**Review by dprokop — APPROVED** [review]
Left one nit to consider :)

File: e2e/suite1/specs/gauge.spec.ts (hunk 2 above)
Comment (torkelo) [reply e2e/suite1/specs/gauge.spec.ts:18]: not sure how without modifying the flot code, want to validate that the flot canvas exists
