### PR TITLE
Alerting: Append org ID to alert notification URLs

### LINKED ISSUE #47424: DashboardURL in alerts results in "Dashboard not found" when using multiple Grafana orgs
**What happened**:
When working with more than one org in Grafana, the dashboard link in the new Grafana unified alerts does not work when it points to a dashboard in a different org than the one I've been currently using. The `DashboardURL` in the [alert template data](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/message-templating/template-data/) does not contain the orgId in the query string. As a result, if I've been previously viewing org "A" but I receive an alert with a link to a dashboard in org "B", I get a "Dashboard not found" error when I click on the link. Screenshot below:

image

However, I if switch to org "B" and then click on the link to the dashboard again, the dashboard opens correctly.

**What you expected to happen**:
I expect the dashboard link to always take me to the dashboard if I have the appropriate permissions for viewing it. The link should open up the correct org in Grafana and display the dashboard regardless of which org I have been viewing previously.

The `DashboardURL` should likely contain the `orgId` in the query string.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create two Grafana orgs: A and B
2. Create an alert linked to a dashboard in org A and ensure the alert triggers shortly
3. Switch to viewing org B
4. Once you receive the alert for the dashboard in org A, click on the link to view the dashboard
5. You will get a "Dashboard not found" error

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: not relevant
- OS Grafana is installed on: not relevant
- User OS & Browser: Ubuntu 20, Chrome Version 100.0
- Grafana plugins: not relevant

### PR DESCRIPTION
**Pull request by neel1996**
- The orgId field has been appended as query param to the dashboard and panel URL that are sent as part of an alert notification
- Resolves #47424

**What this PR does / why we need it**:

The PR addresses #47424. The dashboard and the panel source URLs that are included in an alert notification currently does not include the orgId reference. If an user is on a different org and tries to land on the dashboard URL included in the alert, then the user will receive an error from UI, as the target dashboard is not within the current org account

image

**Which issue(s) this PR fixes**:

The above issue has been addressed by including the `orgId` as a query param in both the dashboard and the panel URLs that are sent as part of an alert notification.

**After fix**

Below is a sample Discord alert with the updated URLs

image

Switched to an org that does not have the source of the alert

image

Landing on the dashboard using the URL from the alert

image

Fixes #47424

### CODE REVIEW

**Comment by neel1996** [comment]
Hi @alexweav,

This is the PR to address issue #47424.

**Summary of the change:** The `orgId` field has been appended as query param to the URLs sent in the alert notifications which are scoped based on organisations (dashboard, panel & alert source)

File: pkg/services/ngalert/notifier/channels/template_data.go [hunk 1]
```diff
@@ -89,6 +89,34 @@ func extendAlert(alert template.Alert, externalURL string, logger log.Logger) *E
...
+		if dErr != nil {
+			logger.Debug("failed to parse dashboard URL while extending template data", "url", extended.DashboardURL, "err", dErr.Error())
+			return extended
+		}
+
+		orgId := alert.Annotations[ngmodels.OrgIDAnnotation]
+		if len(orgId) > 0 {
+			orgIdParam := "orgId=" + orgId
+
+			dashboardUrl.RawQuery = orgIdParam
```
Comment (joeblubaugh) [inline pkg/services/ngalert/notifier/channels/template_data.go:109]: Why use RawQuery here and Query.Add three lines down? Let's be consistent.

File: pkg/services/ngalert/notifier/channels/template_data.go [hunk 2]
```diff
@@ -89,6 +89,34 @@ func extendAlert(alert template.Alert, externalURL string, logger log.Logger) *E
 			u.RawQuery = "viewPanel=" + panelId
 			extended.PanelURL = u.String()
 		}
+
+		generatorUrl, gErr := url.Parse(extended.GeneratorURL)
```
Comment (joeblubaugh) [inline pkg/services/ngalert/notifier/channels/template_data.go:93]: Can you please add a test that validates the orgID is appended when these are set, but the url is otherwise the same?

Comment (neel1996) [reply pkg/services/ngalert/notifier/channels/template_data.go:93]: Hi,

Currently there are two tests covering these scenarios

[// Firing with dashboard and panel ID](https://github.com/grafana/grafana/blob/8911d64574bda76a24b5345d18cb2ba69a483abe/pkg/services/ngalert/notifier/channels/default_template_test.go#L19) - This has the orgId in the annotations and expects the query param to be appended to the generator URL

[// Firing without dashboard and panel ID](https://github.com/grafana/grafana/blob/8911d64574bda76a24b5345d18cb2ba69a483abe/pkg/services/ngalert/notifier/channels/default_template_test.go#L29) - This expects the generated URL without the orgId

Should the above mentioned tests sufice?

File: pkg/services/ngalert/notifier/channels/template_data.go (hunk 1 above)
Comment (neel1996) [reply pkg/services/ngalert/notifier/channels/template_data.go]: Have extracted the logic of appending the query param to a private function to keep the logic consistent.

**Comment by neel1996** [comment]
Hi @joeblubaugh 

I have pushed the changes based on the review discussions. Please have a look and share your thoughts

File: pkg/services/ngalert/notifier/channels/template_data.go [hunk 3]
```diff
@@ -89,6 +89,25 @@ func extendAlert(alert template.Alert, externalURL string, logger log.Logger) *E
...
```
Comment (grobinson-grafana) [inline pkg/services/ngalert/notifier/channels/template_data.go:93]: You can just use `err` here, it's OK to re-use it

```suggestion
		generatorUrl, err := url.Parse(extended.GeneratorURL)
```

File: pkg/services/ngalert/notifier/channels/template_data.go [hunk 4]
```diff
@@ -89,6 +89,25 @@ func extendAlert(alert template.Alert, externalURL string, logger log.Logger) *E
...
+		if gErr != nil {
+			logger.Debug("failed to parse generator URL while extending template data", "url", extended.GeneratorURL, "err", gErr.Error())
+			return extended
+		}
+
+		dashboardUrl, dErr := url.Parse(extended.DashboardURL)
```
Comment (grobinson-grafana) [inline pkg/services/ngalert/notifier/channels/template_data.go:99]:
```suggestion
		dashboardUrl, err := url.Parse(extended.DashboardURL)
```

File: pkg/services/ngalert/notifier/channels/template_data.go (hunk 3 above)
Comment (neel1996) [reply pkg/services/ngalert/notifier/channels/template_data.go]: Hi, The suggested change has been made to re-use the same `err` variable

**Review by grobinson-grafana — APPROVED** [review]
Looks good to me!
