### PR TITLE
Image uploader: Fix uploading of images to GCS

### LINKED ISSUE #26194: GCS external image upload error response status code 404
**What happened**:
I am using GCS for external image storage solution. I already mount required key_file json. No file is uploaded when alert is triggered, and log states that GCS response is 404
```
t=2020-07-09T07:30:45+0000 lvl=dbug msg="Rendered alert panel image" logger=alerting.notifier ruleId=6 path=/var/lib/grafana/png/PaICSdwfoqdYUnOa6DkM.png took=4.289621693s
t=2020-07-09T07:30:45+0000 lvl=dbug msg="Uploading alert panel image to external image store" logger=alerting.notifier ruleId=6 path=/var/lib/grafana/png/PaICSdwfoqdYUnOa6DkM.png
t=2020-07-09T07:30:45+0000 lvl=dbug msg="Opening key file " logger=gcsuploader /etc/secrets/<REDACTED>.json=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
t=2020-07-09T07:30:45+0000 lvl=dbug msg="Creating JWT conf" logger=gcsuploader
t=2020-07-09T07:30:45+0000 lvl=dbug msg="Creating HTTP client" logger=gcsuploader
t=2020-07-09T07:30:45+0000 lvl=dbug msg="Opening image file " logger=gcsuploader /var/lib/grafana/png/PaICSdwfoqdYUnOa6DkM.png=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
t=2020-07-09T07:30:45+0000 lvl=dbug msg="Request URL: " logger=gcsuploader https://www.googleapis.com/upload/storage/v1/b/<REDACTED>/o?uploadType=media&name=uJ0fW2e0UqOZ5Q51hp3C.png&predefinedAcl=publicRead=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
t=2020-07-09T07:30:45+0000 lvl=dbug msg="Sending POST request to GCS" logger=gcsuploader
t=2020-07-09T07:30:45+0000 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=6 error="GCS response status code 404"
```
**What you expected to happen**:
Image is uploaded to GCS every time alert triggers.

**How to reproduce it (as minimally and precisely as possible)**:
- Create k8s Secret for the GCP SA key
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-name
stringData:
  your-key-file.json: |-
    {
        "type": "service_account",
        ...
    }
```
- Deploy [Grafana Helm Chart](https://github.com/helm/charts/tree/master/stable/grafana) with this values
```
image:
  repository: grafana/grafana
  tag: 7.0.3
extraSecretMounts:
- name: secret-files
  mountPath: /etc/secrets
  secretName: secret-name
  readOnly: true
  subPath: ""
grafana.ini:
  external_image_storage:
    provider: gcs
  external_image_storage.gcs:
    key_file: /etc/secrets/your-key-file.json
    bucket: your-gcs-bucket
```
- Try to config and trigger an alarm that will upload image file to GCS

**Anything else we need to know?**:
[Official GCP Documentation](https://cloud.google.com/storage/docs/uploading-objects#upload-object-json) states this is the API for uploading file to GCS.
```
curl -X POST --data-binary @[OBJECT_LOCATION] \
-H "Authorization: Bearer [OAUTH2_TOKEN]" \
-H "Content-Type: [OBJECT_CONTENT_TYPE]" \
"https://storage.googleapis.com/upload/storage/v1/b/[BUCKET_NAME]/o?uploadType=media&name=[OBJECT_NAME]"
```
Apparently there is [changes in the endpoint](https://github.com/googleapis/google-cloud-cpp/issues/2634#issuecomment-533304420) at some time

This is the line that defines the URL
https://github.com/grafana/grafana/blob/45cfb3451b122a601d3b7ac9aff019fc419e5332/pkg/components/imguploader/gcsuploader.go#L18

**Environment**:
- Grafana version: Grafana v7.0.3 (00ee734baf)
- Others: Helm Stable Grafana Deployed on GKE Cluster

### PR DESCRIPTION
**Pull request by gastonqiu**
**What this PR does / why we need it**:
Upload image to GCS with SDK to simplify the code. And make it easier to maintain.

**Which issue(s) this PR fixes**:
The GCS upload URL expires because the user can't upload the image file to GCS.

Fixes #26194

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/components/imguploader/gcsuploader.go [hunk 1]
```diff
@@ -43,40 +40,46 @@ func (u *GCSUploader) Upload(ctx context.Context, imageDiskPath string) (string,
...
 	if u.keyFile != "" {
 		u.log.Debug("Opening key file ", u.keyFile)
 		data, err := ioutil.ReadFile(u.keyFile)
 		if err != nil {
 			return "", err
 		}
 
-		u.log.Debug("Creating JWT conf")
-		conf, err := google.JWTConfigFromJSON(data, tokenUrl)
+		u.log.Debug("Creating google Credentials from json")
```
Comment (aknuds1) [inline pkg/components/imguploader/gcsuploader.go:51]:
```suggestion
		u.log.Debug("Creating Google credentials from JSON")
```

File: pkg/components/imguploader/gcsuploader.go [hunk 2]
```diff
@@ -43,40 +40,46 @@ func (u *GCSUploader) Upload(ctx context.Context, imageDiskPath string) (string,
...
+		cred, err := google.CredentialsFromJSON(ctx, data)
```
Comment (aknuds1) [inline pkg/components/imguploader/gcsuploader.go:52]:
```suggestion
		creds, err := google.CredentialsFromJSON(ctx, data)
```

File: pkg/components/imguploader/gcsuploader.go [hunk 3]
```diff
@@ -43,40 +40,46 @@ func (u *GCSUploader) Upload(ctx context.Context, imageDiskPath string) (string,
...
 		if err != nil {
 			return "", err
 		}
 
-		u.log.Debug("Creating HTTP client")
-		client = conf.Client(ctx)
+		u.log.Debug("Creating gcs client")
```
Comment (aknuds1) [inline pkg/components/imguploader/gcsuploader.go:57]:
```suggestion
		u.log.Debug("Creating GCS client")
```

File: pkg/components/imguploader/gcsuploader.go [hunk 4]
```diff
@@ -43,40 +40,46 @@ func (u *GCSUploader) Upload(ctx context.Context, imageDiskPath string) (string,
...
+		client, err = storage.NewClient(ctx, option.WithCredentials(cred))
+		if err != nil {
+			return "", err
+		}
 	} else {
-		u.log.Debug("Key file is empty, trying to use application default credentials")
-		client, err = google.DefaultClient(ctx)
+		u.log.Debug("Creating gcs client with no credentials")
```
Comment (aknuds1) [inline pkg/components/imguploader/gcsuploader.go:63]:
```suggestion
		u.log.Debug("Creating GCS client without credentials")
```

File: pkg/components/imguploader/gcsuploader.go [hunk 5]
```diff
@@ -85,26 +88,14 @@ func (u *GCSUploader) uploadFile(client *http.Client, imageDiskPath, key string)
 	}
 	defer fileReader.Close()
 
-	reqUrl := fmt.Sprintf(uploadUrl, u.bucket, key)
-	u.log.Debug("Request URL: ", reqUrl)
-
-	req, err := http.NewRequest("POST", reqUrl, fileReader)
-	if err != nil {
+	u.log.Debug("Sending to gcs bucket using SDK")
```
Comment (aknuds1) [inline pkg/components/imguploader/gcsuploader.go:91]:
```suggestion
	u.log.Debug("Sending to GCS bucket using SDK")
```

**Review by aknuds1 — COMMENTED** [review]
I will have to test your PR before I can conclude on anything, but left some suggestions for improvements.

**Comment by aknuds1** [comment]
Sorry, quite busy now, still have it on my agenda to test/review this.

**Comment by gastonqiu** [comment]
It's OK. Take your time.

**Comment by gastonqiu** [comment]
@aknuds1 This has been marked as stale. Can you help to remove the tag? Also does it help if I test this by myself and post the result here?

**Comment by aknuds1** [comment]
The stale bot applies the label automatically. I haven't forgot about the PR, but I'm very busy with a number of different PRs plus own tasks to take care of.

File: pkg/components/imguploader/gcsuploader.go [hunk 6]
```diff
@@ -65,76 +56,46 @@ func (u *GCSUploader) Upload(ctx context.Context, imageDiskPath string) (string,
...
-		Expires:        time.Now().Add(u.signedUrlExpiration),
-	}
-	signedUrl, err := storage.SignedURL(u.bucket, key, opts)
+
+	err = u.uploadFile(ctx, client, imageDiskPath, key)
 	if err != nil {
-		return "", fmt.Errorf("storage.SignedURL: %v", err)
+		return "", err
 	}
-	return signedUrl, nil
```
Comment (aknuds1) [inline pkg/components/imguploader/gcsuploader.go:134]: Can you please tell me why this section, i.e. support for signed URLs, is removed?

**Review by aknuds1 — CHANGES_REQUESTED** [review]

File: pkg/components/imguploader/gcsuploader.go (hunk 6 above)
Comment (gastonqiu) [reply pkg/components/imguploader/gcsuploader.go:134]: You're right. It should not be removed since this is the new feature after I modify it. I don't notice when I rebase. I will add this back.

File: pkg/components/imguploader/gcsuploader.go [hunk 7]
```diff
@@ -65,35 +57,34 @@ func (u *GCSUploader) Upload(ctx context.Context, imageDiskPath string) (string,
...
 		if err != nil {
 			return "", err
 		}
 	}
 
-	err = u.uploadFile(client, imageDiskPath, key)
-	if err != nil {
-		return "", err
-	}
+	err = u.uploadFile(ctx, client, imageDiskPath, key)
```
Comment (aknuds1) [inline pkg/components/imguploader/gcsuploader.go:87]: You need to keep the error check.
```suggestion
	err = u.uploadFile(ctx, client, imageDiskPath, key)
	if err != nil {
		return "", err
	}
```

**Review by aknuds1 — CHANGES_REQUESTED** [review]

**Comment by aknuds1** [comment]
Sorry for the long wait, but I'm testing the PR now.

**Review by aknuds1 — APPROVED** [review]
LGTM! Tested and works well both with and without signed URLs.

Please note that I had to rewrite a bit to make it function.

**Review by kylebrandt — APPROVED** [review]

**Comment by aknuds1** [comment]
Thanks for contributing!
