### PR TITLE
DataLinks: Improve Data-Links AutoComplete Logic

### LINKED ISSUE #47184: Graph panel: Data Link editor automcomplete gives double $
**What happened**:
When I press `$` I get a pop-up, but after I select an item I have two `$$`, which causes an error when the link is used.

https://user-images.githubusercontent.com/8125524/161244703-54e82042-928d-4116-961a-6cc6d7c41b3f.mp4

**What you expected to happen**:

Just one `$`

**How to reproduce it (as minimally and precisely as possible)**:
In Graph panel, click on Data Link, edit, position cursor in the middle of existing text.

**Environment**:
- Grafana version: 8.5.0-a2463818pre
- User OS & Browser: MacOS 11.6.1; Chrome Version 99.0.4844.74 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by zuchka**
Fixes #47184

**Special notes for your reviewer**:

This resolves a pretty narrow edge case so a quick explanation feels useful:

The data-links editor includes a "variable suggestions" dropdown. Users can trigger this dropdown three different ways: by pressing the `$` key, the `=` key, or the `CTRL + SPACE` keys. 

Currently, there are no problems when inserting a variable from the dropdown list IF you triggered the dropdown using `=` or `CTRL + SPACE`. 

But if you use `$` to trigger the dropdown, it only works properly when you are inserting  a var at the very end of the URL string. If you try the `$`-based workflow in the middle of a string, it results in a double `$$`. This is what the OP is describing in the linked issue:  

CleanShot 2022-11-17 at 19 07 07

This is because the existing logic, `includeDollarSign`, only checked the end of the URL string for an existing `$` (the _most likely_ cursor location). It did not consider the cursor's _actual_ location because it was assumed that users would only insert variables at the very end.

This new logic ([thanks, StackOverflow](https://stackoverflow.com/questions/15157435/get-last-character-before-caret-position-in-javascript) 😄 ❤️  ) grabs the cursor's location and then traps the character directly before it. This new method can both replace the old `includeDollarSign` and has the added benefit of working anywhere in the link's string:

CleanShot 2022-11-17 at 19 16 24

### CODE REVIEW

File: packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx [hunk 1]
```diff
@@ -151,10 +153,27 @@ export const DataLinkInput: React.FC<DataLinkInputProps> = memo(
...
+    const getCharactersAroundCaret = () => {
+      const input: HTMLSpanElement | null = document.getElementById('data-link-input')!;
+      let precedingChar = '',
+        sel: Selection | null,
+        range: Range;
+      if (window.getSelection) {
+        sel = window.getSelection();
+        if (sel && sel.rangeCount > 0) {
+          range = sel.getRangeAt(0).cloneRange();
+          range.collapse(true);
```
Comment (polibb) [inline packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx:165]: I would add
```suggestion
          // If the content is focused and editable, the caret will blink there.
          range.collapse(true);
```
because it's a bit out of the blue and not too widely used imo.

**Review by polibb — APPROVED** [review]
Awesome detail management @zuchka! Thank you 🙌

I've added a small suggestion for a comment before the less easy to read code.

File: packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx (hunk 1 above)
Comment (zuchka) [reply packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx:165]: good call. thanks!

**Comment by zuchka** [comment]
> Awesome detail management @zuchka! Thank you 🙌
> 
> I've added a small suggestion for a comment before the less easy to read code.

thanks, Poli! 🚀
