### PR TITLE
Image Rendering: Make it work using serve_from_sub_path configured

### LINKED ISSUE #21925: Image rendering: Doesn't work when using serve_from_sub_path
**What happened**:

The image sent by e-mail is not the graphic that is alerted. Example:

grafana-01

**What you expected to happen**:

The image sent should be from the graphic with alert.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Occurs after update, as follows:

```
Start-Date: 2020-02-03  09:03:40
Commandline: apt install grafana
Upgrade: grafana:amd64 (6.5.2, 6.6.0)
End-Date: 2020-02-03  09:03:44
```

In the email notification channel, you are selected to include the image. A log summary:

```
t=2020-02-04T15:48:01-0300 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=5 newState=pending prev state=ok
t=2020-02-04T15:50:07-0300 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=5 newState=alerting prev state=pending
t=2020-02-04T15:50:07-0300 lvl=info msg=Rendering logger=rendering renderer=phantomJS path="d-solo/n41K9ndZk/xxxxx-application-server?orgId=1&panelId=10"
t=2020-02-04T15:50:13-0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/datasources/proxy/8/_msearch status=502 remote_addr=127.0.0.1 time_ms=128 size=0 referer="http://127.0.0.1:3000/grafana/d/eY2it3vZk/centro-de-inicio?orgId=1&refresh=5s"
t=2020-02-04T15:50:13-0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/datasources/proxy/8/_msearch status=502 remote_addr=127.0.0.1 time_ms=129 size=0 referer="http://127.0.0.1:3000/grafana/d/eY2it3vZk/centro-de-inicio?orgId=1&refresh=5s"
t=2020-02-04T15:50:13-0300 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses="[xxxx@xxxx.com.br yyyy@yyyy.com.br]" singleEmail=true

```
Could this Request 502 be the reason?

**EDIT:**

I looked that [PhantomJS is depreciated](https://grafana.com/docs/grafana/latest/administration/image_rendering/#phantomjs), I will test [Grafana Image Renderer](https://grafana.com/grafana/plugins/grafana-image-renderer) to see if the problem continues.

**Environment**:
- Grafana version:  v6.6.0 (5c11bbdfb4)
- Data source type & version: Elasticsearch v7.3.1 (4749ba6)
- OS Grafana is installed on: Debian GNU/Linux 10 (buster)

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Make rendering work when using serve_from_sub_path and not have `rendering.renderer_url` configured.

**Which issue(s) this PR fixes**:
Fixes #21925

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/rendering/rendering_test.go [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+		Cfg: setting.NewCfg(),
+	}
+
+	t.Run("When renderer url configured", func(t *testing.T) {
+		rs.Cfg.RendererUrl = "http://localhost:8081/render"
+
+		t.Run("Should return path", func(t *testing.T) {
+			url := rs.getURL(path)
+			require.Equal(t, path+"&render=1", url)
+		})
```
Comment (aknuds1) [inline pkg/services/rendering/rendering_test.go:22]: Basically, this case differs from the other one by not setting rs.Cfg.RendererCallbackUrl. Is this really a valid case? I'm not familiar with the semantics of the GetURL method, but I'm wondering why it should return a basically invalid URL (just starting with the path) if rs.Cfg.RendererCallbackUrl hasn't been set?

Comment (marefr) [reply pkg/services/rendering/rendering_test.go:22]: Good catch. It's actually some logic in setting package setting callback URL:
https://github.com/grafana/grafana/blob/c26bfe9e03b92011bd402e0e64bb386817bca237/pkg/setting/setting.go#L926-L940

Will update the test

**Review by aknuds1 — APPROVED** [review]
LGTM
