### PR TITLE
Table: fix data links tooltip overflow with viewport-constrained scrolling

### LINKED ISSUE #115608: Unable to scroll data links that does not fit on the screen
### What happened?

Impossible to see all data links if they are not fit to a browser window

### What did you expect to happen?

Scrolling for a list of data links

### Did this work before?

No

### How do we reproduce it?

1. Create a table with many data links
2. Click to a row inside this table to see data links
3. Decrease window size of a browser if needed

Result: cannot use links outside of the screen. It's not even clear that the list shown is not complete.

Image

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: v12.3.1 (0d1a5b4420)
OS: Windows 11
Browser: Google Chrome 143.0.7499.41

### Grafana platform?

Docker

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by lokeshkaki**
**What is this feature?**
Adds viewport-constrained scrolling to the data links tooltip in Table panels so links that extend beyond the screen edge are scrollable instead of clipped.

**Why do we need this feature?**
When a Table panel has many data links configured, the tooltip silently overflows the viewport, users can't reach links rendered off-screen with no indication the list is incomplete.

**Who is this feature for?**
Grafana users who configure multiple data links on Table panel columns.

**Which issue(s) does this PR fix?**
Fixes #115608 (Table panel path only, ContextMenu path is a separate PR)

**Special notes for your reviewer:**
- Scroll constraints moved into `getStyles()` / `tooltipWrapper` using Grafana's `useStyles2` + Emotion `css()` pattern, no inline style overrides
- `DataLinksActionsTooltip.test.tsx` updated to verify overflow styles on the floating container
- No new dependencies added
- 142 test suites pass

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated.

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.tsx [hunk 1]
```diff
@@ -83,7 +83,12 @@ export const DataLinksActionsTooltip = ({ links, actions, value, coords, onToolt
           ref={refCallback}
           {...getReferenceProps()}
           {...getFloatingProps()}
-          style={floatingStyles}
+          style={{
+            ...floatingStyles,
```
Comment (gtk-grafana) [inline packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.tsx]: instead of overwriting the inline floating styles these should be added to the css in `tooltipWrapper`

File: packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.test.tsx [hunk 2]
```diff
@@ -25,6 +27,11 @@ describe('DataLinksActionsTooltip', () => {
 
   beforeEach(() => {
     jest.clearAllMocks();
+    logSpy = jest.spyOn(console, 'log').mockImplementation(() => {});
```
Comment (gtk-grafana) [inline packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.test.tsx]: Please remove the console log mocking

**Review by gtk-grafana — DISMISSED** [review]
A few nits but that table changes look good, thanks for taking a look at this. Only request is to split the table and context menu changes into separate PRs, since these components are owned by different teams it will make review much easier.

File: packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.tsx (hunk 1 above)
Comment (lokeshkaki) [reply packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.tsx]: done

File: packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.test.tsx (hunk 2 above)
Comment (lokeshkaki) [reply packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.test.tsx]: done. good catch!

**Comment by lokeshkaki** [comment]
> A few nits but that table changes look good, thanks for taking a look at this. Only request is to split the table and context menu changes into separate PRs, since these components are owned by different teams it will make review much easier.

@gtk-grafana Done. Moved scroll styles into `getStyles()` / `tooltipWrapper`, removed the console.log mock, and split the ContextMenu changes into a separate PR (#119884). Also rebased the branch. Thanks!

File: packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.tsx [hunk 3]
```diff
@@ -119,6 +119,9 @@ const getStyles = (theme: GrafanaTheme2) => {
       background: theme.colors.background.primary,
       border: `1px solid ${theme.colors.border.weak}`,
       boxShadow: theme.shadows.z3,
+      maxHeight: 'calc(100vh - 32px)',
+      overflowY: 'auto',
```
Comment (gtk-grafana) [inline packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.tsx]:
```suggestion
```

I don't think we need the overflowY here, just remember to remove it from your test as well.

File: packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.tsx [hunk 4]
```diff
@@ -119,6 +119,9 @@ const getStyles = (theme: GrafanaTheme2) => {
       background: theme.colors.background.primary,
       border: `1px solid ${theme.colors.border.weak}`,
       boxShadow: theme.shadows.z3,
+      maxHeight: 'calc(100vh - 32px)',
```
Comment (fastfrwrd) [inline packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.tsx]:
```suggestion
      maxHeight: `calc(100vh - ${theme.spacing(4)})`,
```

**Review by fastfrwrd — COMMENTED** [review]
Works well! One other note to tie the 32px into theme.

File: packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.tsx (hunk 4 above)
Comment (lokeshkaki) [reply packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.tsx]: Done.

File: packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.tsx (hunk 3 above)
Comment (lokeshkaki) [reply packages/grafana-ui/src/components/Table/DataLinksActionsTooltip.tsx]: Done.

**Review by gtk-grafana — APPROVED** [review]
Looks good, works well. Thanks for taking the time to get this fixed!

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/22973136712)
- Version: 13.0.0-22973136712
