### PR TITLE
OpenTSDB: Fix data frame construction

### LINKED ISSUE #38729: Alerting with OpenTSDB, graph data not sorted by time
**What happened**:
Data from query on the Create Alert Rule page is not displayed properly. It looks like the data is not sorted and the graph looks terrible.

**What you expected to happen**:
I expected the graph displayed on the Create alert rule page to look exactly like the panel for which I'm trying to create the alert.

**How to reproduce it (as minimally and precisely as possible)**:
Try to create an alert on a OpenTSDB graph panel. Click "Run queries" and look at the data in Time series format and also table format.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: OpenTSDB 2.4
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Ubuntu / Firefox
- Grafana plugins:
- Others:

not_sorted
not_sorted2

### LINKED ISSUE #82027: Alerts: Graph does not display
### What happened?

User created a new dashboard, Attempted to create a new alert for the dashboard. When the query was executed data was returned but the UI only shows a table view with the first data point value from the JSON data section. 

### What did you expect to happen?

User should have seen a graph of the resulting data. 

### Did this work before?

Yes prior to Grafana version 10.3.1

### How do we reproduce it?

See what happened section

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 10.3.1
OS: Linux Centos 7
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?
TSDB

### PR DESCRIPTION
**Pull request by aangelisc**
OpenTSDB typically sends data responses as key-value pairs. This means that data can be appended to the data frame out of order. This previously did not cause any problems as the `toDataFrame` method did not validate if data in the time field was in order. 

This changed in #77841 leading to OpenTSDB time-series being incorrectly handled as non-time-series data.

I've updated the OpenTSDB queries to use the `arrays=true` query parameter which will return the data in an ordered array allowing us to guarantee the ordering of the data in the frame without having to sort it ourselves. I've also updated the frame construction to be more up-to-date.

Fixes #82027
Fixes #38729

### CODE REVIEW

**Comment by ChengChung** [comment]
why set `dataField.Name = val.Metric` rather than `dataField.Name = data.TimeSeriesValueFieldName`

**Comment by aangelisc** [comment]
Hi @ChengChung, the reason we're using the `Metric` value is because it's guaranteed to be filled. I can't find a reference to `TimeSeriesValueFieldName` in the OpenTSDB docs.

**Comment by ChengChung** [comment]
Is it the Data Plane Contract introduced in Grafana 10 that requires us to set `val.Metric` as the value of `dataField.Name` instead of the string literal `"value"` (a.k.a `data.TimeSeriesValueFieldName`)? I don't think this is related to the OpenTSDB documentation, as it seems `pkg/tsdb/opentsdb` is only used in alerting.

File: pkg/tsdb/opentsdb/types.go [hunk 1]
```diff
@@ -7,7 +7,7 @@ type OpenTsdbQuery struct {
 }
 
 type OpenTsdbResponse struct {
-	Metric     string             `json:"metric"`
-	Tags       map[string]string  `json:"tags"`
-	DataPoints map[string]float64 `json:"dps"`
+	Metric     string            `json:"metric"`
+	Tags       map[string]string `json:"tags"`
+	DataPoints [][]float64       `json:"dps"`
```
Comment (bossinc) [inline pkg/tsdb/opentsdb/types.go:12]: I'm not why this was changed to a double array instead of using a map

Comment (aangelisc) [reply pkg/tsdb/opentsdb/types.go:12]: That's the new data structure that's returned from OpenTSDB now

**Comment by aangelisc** [comment]
> Is it the Data Plane Contract introduced in Grafana 10 that requires us to set `val.Metric` as the value of `dataField.Name` instead of the string literal `"value"` (a.k.a `data.TimeSeriesValueFieldName`)? I don't think this is related to the OpenTSDB documentation, as it seems `pkg/tsdb/opentsdb` is only used in alerting.

We could continue to use `value` instead to be consistent with the previous implementation, I'll update that!

**Review by bossinc — APPROVED** [review]

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. This is a friendly reminder that the Steady [11.2.x Release Branch](https://github.com/grafana/grafana/tree/v11.2.x) was cut this week, and that it includes the changes committed up to https://github.com/grafana/grafana/commit/b4126d3bce3627e9460e2db0e870c8d984be8e84. This PR was merged after it, so we wanted to let you know that you can add the `backport v11.2.x` label to to backport it and make it part of the next 11.2.x Patch Release, just in case you may have missed the news.

Thank you!

**Comment by yuri-tceretian** [comment]
Greetings from Release Guild. This PR has been successfully included in the Grafana 11.2 release branch. A backport PR was also created to ensure the v11.2.x branch is correctly synchronized with the release.

File: pkg/tsdb/opentsdb/types.go (hunk 1 above)
Comment (Helene) [reply pkg/tsdb/opentsdb/types.go:12]: > That's the new data structure that's returned from OpenTSDB now

@aangelisc could you please provide me a reference of the OpenTSDB response dps changed format. I'm wondering to which OpenTSDB API version this changes have been applied?
According the official OpenTSDB API 2.x documentation for /api/query endpoint nothing has changed in the result format
https://opentsdb.net/docs/build/html/api_http/query/index.html

Comment (aangelisc) [reply pkg/tsdb/opentsdb/types.go:12]: Hi @Helene,

As we're now using `arrays=true` [this](https://opentsdb.net/docs/build/html/api_http/serializers/json.html) documentation applies which changes the response to an array of arrays instead of a map.

Comment (Helene) [reply pkg/tsdb/opentsdb/types.go:12]: > Hi @Helene,
> 
> As we're now using `arrays=true` [this](https://opentsdb.net/docs/build/html/api_http/serializers/json.html) documentation applies which changes the response to an array of arrays instead of a map.

hi @aangelisc,
first of all many thanks for your quick answer. The documentation you are referencing is OpenTSDB API **2.4**  According the official Grafana documentation, supported OpenTSDB version are 2.1, 2.2, 2.3.

We are using in our product OpenTSDB API format 2.3 and with this fix our dashboards have issue reported by https://github.com/grafana/grafana/issues/94150

image

Comment (aangelisc) [reply pkg/tsdb/opentsdb/types.go:12]: Apologies! That's my bad and I will investigate a fix for this!.

Comment (Helene) [reply pkg/tsdb/opentsdb/types.go:12]: @aangelisc no problem, the things do happen.
It is important for us to know when (from which version) Grafana will support OpenTSDB 2.4. Will OpenTSDB 2.3 continue to be supported or will it be discontinued (if discontinued, from which version).
And the proper documentation of the /api/query?arrays=true endpoint is also required.

I tried to put all this in the new issue
https://github.com/grafana/grafana/issues/100359

let me know if you have any questions

Comment (aangelisc) [reply pkg/tsdb/opentsdb/types.go:12]: Hi @Helene,

I have a PR (#100673) open that should fix both #94150 and #100359. PTAL and we can continue the conversation in that PR 😊
