### PR TITLE
Browse dashboards: Fix delete modal affected counts

### LINKED ISSUE #122481: [REOPEN] Dashboard deletion modal incorrect plural grammar
**Steps to reproduce:**

1. Login
2. Navigate to Dashboards
3. Select a folder with multiple items in it
4. Click "Delete"

**Expected:** Delete modal shows "items" (plural form) if there is more than 1 item in the folder.

**Actual:** Delete modal always shows "item" (singular form). Ex: "12 item" instead of "12 items".

**Timestamp:** 0:00

**Video:** 

[https://www.loom.com/share/6742a5a17eb4422cbf07b1240418d767](https://www.loom.com/share/6742a5a17eb4422cbf07b1240418d767)

[View bug report on QA Wolf](https://app.qawolf.com/grafana/bug-reports/82db0ca2-90fd-413a-bbbc-8cb0514a8c7a)

**Affected flows:**
- [Add Dashboard panel to Library and use Library to apply panel to other Dashboards](https://app.qawolf.com/grafana/environments/vob7zzuvffresv8j38m0ieakoenv/flows/hj0p1z7rtdli2xdcdqd835olowor/code)

_If you are aware of this bug, you can set the priority to low or medium to make it non-blocking._

### LINKED ISSUE #122499: Deleting Dashboard modal > Deleting Folders with Nested Dashboard > "NaN item" text instead of # items
**Steps to reproduce:**

1. Log into account.
2. Navigate to the Dashboards page.
3. Search for a folder that has nested dashboards.
4. Click on the checkbox for the folder.
5. Click "Delete".
6. Wait for the modal to confirm deletion.

**Expected:** Expect the delete confirmation modal to confirm the # of nested dashboards and # of folders that are being deleted (e.g  2 items: 1 folder, 1 dashboard)

**Actual:** The delete confirmation modal indicates:

"This action will delete the folder "qaw-folder-test-2" and the following content:

NaN item"

**Timestamp:** 0:00

**Video:** 

[https://www.loom.com/share/824279ac38a84ad2b9929fd6267ceffc](https://www.loom.com/share/824279ac38a84ad2b9929fd6267ceffc)

[View bug report on QA Wolf](https://app.qawolf.com/grafana/bug-reports/297c09a2-f7cc-4980-9dcf-c588aa6852c2)

**Affected flows:**
- [Create, Update, Move and Delete Folder with Multiple Dashboards](https://app.qawolf.com/grafana/environments/vob7zzuvffresv8j38m0ieakoenv/flows/srdxm9m8v5va0xxby1jupbyyowor/code)

_If you are aware of this bug, you can set the priority to low or medium to make it non-blocking._

### PR DESCRIPTION
**Pull request by aocenas**
Fixes https://github.com/grafana/grafana/issues/122499
Will fix https://github.com/grafana/grafana/issues/122481 (with the caveat that there is separate issue with pluralization as a whole see https://raintank-corp.slack.com/archives/C025WTVRBSN/p1776318484686039?thread_ts=1776279599.434699&cid=C025WTVRBSN)

Seems like the `/api/folders/${folderUID}/counts` endpoint returns different shape depending on whether unified storage is used or not.

### CODE REVIEW

File: public/app/features/browse-dashboards/api/browseDashboardsAPI.ts [hunk 1]
```diff
@@ -79,6 +79,26 @@ interface RestoreDashboardArgs {
   dashboard: Resource<Dashboard | DashboardV2Spec>;
 }
 
+// We need to do this as the API will return different responses depending on the type of storage used, even though we
+// are using the old api/ endpoint.
+const normalizeDescendantCounts = (folderCounts: DescendantCountDTO): DescendantCount => {
+  if ('folders' in folderCounts) {
```
Comment (Clarity-89) [inline public/app/features/browse-dashboards/api/browseDashboardsAPI.ts]: This breaks for partial responses, for example when the count doesn't contain `folders`, but has `dashboards`, which could be also why the tests are failing. Should each case be handled individually?

Comment (aocenas) [reply public/app/features/browse-dashboards/api/browseDashboardsAPI.ts]: Hmm yeah I thought this always filled in and that there is some specific structure on the backend, because it does return zero values for keys, but it seems like it is still just `{[string]: number}` without guarantee about the keys. So yeah will revert to the previous type which was probably better in that case.

**Review by Clarity-89 — APPROVED** [review]
