### PR TITLE
Sandbox: Fix panel custom editors not working inside the sandbox

### LINKED ISSUE #74587: Investigate button panel plugin options not working as expected
The `speakyourcode-button-panel` plugin is not working correctly when inside the sandbox. The buttons text and queries can't be edited.

### PR DESCRIPTION
**Pull request by academo**
**What is this feature?**

This PR addresses plugin panels with custom editors that malfunction within the sandbox.

The sandbox implements a DOM access protection to restrict plugins from accessing beyond their own render scope. However, this implementation overlooked the fact that panel plugins can declare custom components in their options, which are often forms.

When a plugin panel attempts to access its own rendered form fields in the panel options, the DOM access protection intervenes, returning a mocked element and causing the form to malfunction.

This fix ensures that panels with custom editors operate properly within the sandbox. This is achieved by adding a custom data attribute to an existing div element in the panel options editor and validating it in the DOM access protection logic.

**Why do we need this feature?**

To make grafana panel plugins with custom editor options work correctly inside the sandbox

**Who is this feature for?**

Grafana panel plugins running inside the sandbox

**Which issue(s) does this PR fix?**:

Closes https://github.com/grafana/grafana/issues/74587

Fixes #

**Special notes for your reviewer:**

Please check that:

- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard/components/PanelEditor/OptionsPaneCategory.tsx [hunk 1]
```diff
@@ -112,6 +112,7 @@ export const OptionsPaneCategory = React.memo(
       <div
         className={boxStyles}
         data-testid="options-category"
+        data-plugin-sandbox={'panel-options'}
```
Comment (academo) [inline public/app/features/dashboard/components/PanelEditor/OptionsPaneCategory.tsx:115]: This data-attribute won't affect at all plugins not running inside the sandbox. It'll be just another data-attribute.

Comment (mckn) [reply public/app/features/dashboard/components/PanelEditor/OptionsPaneCategory.tsx:115]: Will this wrap editors both added by the panel and by Grafana core with `data-plugin-sandbox`? Will that then allow plugins to tamper with any children of that dom element?

Would it work if we apply the `data-plugin-sandbox=${pluginId}` only for the elements added by the plugin instead? I think we could add a data attribute to those elements during panel configuration. 

So when the plugin developer calls `useFieldConfig` we could detect if any custom editors are added and then, under the hood, add a property that will be used while rendering that config editor.

**Review by mckn — COMMENTED** [review]
LGTM! Have a question and potentially a suggestion on how we could improve this code a bit. But it depends on the answer to my question. Might not be worth it :)

File: public/app/features/dashboard/components/PanelEditor/OptionsPaneCategory.tsx (hunk 1 above)
Comment (academo) [reply public/app/features/dashboard/components/PanelEditor/OptionsPaneCategory.tsx:115]: The plugin could potentially access elements in the panel options editor that were not directly render by itself but only and only panel editor options. Considering there's only one panel editor open at the time and it'll be the panel editor options of the plugin itself it sounds reasonable. Also it will definitely won't go any further up the dom than the panel options because it can't escape this attribute.

Having the pluginId as you suggest would be the best solution. I did want to put the $pluginId here instead of just "panel-options" but I the pluginId was not available in this component and it seems to be used in too many different places that also don't have the context of the plugin id and thus I went for a simpler solution using `panel-options` as the sandbox attribute value.

Comment (mckn) [reply public/app/features/dashboard/components/PanelEditor/OptionsPaneCategory.tsx:115]: Ah, ok ok! Let me have a quick look. I think we have access to the plugin in when calling the `useFieldConfig`. So I will see if we can define something like additional props during registration time. Will time box this and get back to you if my proposed solution will work.

Comment (mckn) [reply public/app/features/dashboard/components/PanelEditor/OptionsPaneCategory.tsx:115]: So I have two suggestions depending on which solution you prefer.

We add a "sandboxId" (or similar) to the OptionsEditorItem assign the pluginId to that id in createFieldConfigRegistry and then use it for the data attribute when rendering the editor in OptionsPaneItemDescriptor.
The other alternative is that we wrap the whole options pane section with the id. Then you can just use it from the PanelModel which is available when rendering the options pane.

**Review by mckn — APPROVED** [review]
LGTM! Great work on this ⭐

File: public/app/features/dashboard/components/PanelEditor/OptionsPaneCategory.tsx (hunk 1 above)
Comment (academo) [reply public/app/features/dashboard/components/PanelEditor/OptionsPaneCategory.tsx]: I followed your idea and ended up modifying the `OptionsPaneCategoryDescriptor` to accept a sandboxID. It'll be only passed and rendered with the plugin visualization options which are the ones provided by the plugin which are the ones we want to sandbox.
