### PR TITLE
Anonymous: Fix anonymous cache ignoring device limit evaluation

### LINKED ISSUE #93755: auth.anonymous.device_limit does not actually limit the amount of devices that can access
### What happened?

After setting device_limit=1, multiple different devices (different browsers, different machines, different ips, etc) could still access the anonymous org.
The only thing that it seems to be actually limiting is the Anonymous devices view in /admin/users

On the second access you do get an unauthorized popup.
Sometimes you are redirected to a blank grafana page, then you could just click the side panel to go to Dashboards and open it.
Sometimes you just click the unauthorized popup and everything just works fine

This was tested on the grafana/grafana:11.2.0 docker image

### What did you expect to happen?

Other anonymous devices to be fully denied access to grafana once device_limit is reached

### Did this work before?

no idea

### How do we reproduce it?

1. make an anonymous org and create a dashboard
2. open the dash in an anonymous browser window on multiple devices
3.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 11.2
OS: linux
Browser: brave, chrome, firefox

### Grafana platform?

Docker

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by Jguer**
**What is this feature?**

- Fix issue with anonymous cache ignoring device limit evaluation (Fixes https://github.com/grafana/grafana/issues/93755)
- Add 2 types of end user warnings for device limit reached

Screenshot_20241003_163329
Screenshot_20241003_163210

### CODE REVIEW

File: pkg/services/anonymous/anonimpl/impl_test.go [hunk 1]
```diff
@@ -271,3 +282,88 @@ func TestIntegrationDeviceService_SearchDevice(t *testing.T) {
...
+		},
+	}
+
+	// Run test cases
+	for _, tc := range testCases {
+		t.Run(tc.name, func(t *testing.T) {
+			err := anonService.TagDevice(context.Background(), tc.httpReq, anonymous.AnonDeviceUI)
+			if tc.expectedErr != nil {
+				require.Error(t, err)
+				assert.Equal(t, tc.expectedErr, err)
```
Comment (aarongodin) [inline pkg/services/anonymous/anonimpl/impl_test.go:363]: There's also `assert.ErrorIs(..)` but maybe you prefer checking exactly that they are the same. However `Equal(..)` might fail if an error had a variadic message? Not sure.

**Review by aarongodin — APPROVED** [review]
LGTM
