### PR TITLE
Prometheus: Handle the response with different field key order

### LINKED ISSUE #64693: Response to a Prometheus query have to have keys in a certain order.
**What happened**:
Responding to a query with `{"status": "success", "data": {"resultType": "vector", "result": []}}` returns `unknown result type:`

**What you expected to happen**:
Return empty response `[]`

**How to reproduce it (as minimally and precisely as possible)**:
Respond to a query with `{"data": {"result": [], "resultType": "vector"}, "status": "success"}` returns the expected response
Respond to a query with  `{"status": "success", "data": {"resultType": "vector", "result": []}}` returns `unknown result type:`

**Anything else we need to know?**:
I'm not sure if this is a bug or expected behavior. I couldn't find documentation related to it.
I think this is where the behavior comes from https://github.com/grafana/grafana/blame/main/pkg/util/converter/prom.go#L109

**Environment**:
- Grafana version: v9.4.3
- Data source type & version: Prometheus
- OS Grafana is installed on: ubuntu
- User OS & Browser: Windows, Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

For some edge cases prometheus response is returning with out of order field keys. We must read the `resultType` before the `result` while parsing the data. 
See the example http response here https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries
Since that is an edge case this PR is covering by re-iterating the result after reading the `resultType`

**Why do we need this feature?**

To be able to cover out of order field key responses.

**Who is this feature for?**

Potentially all prometheus data source users

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/64693

**Special notes for your reviewer:**

#### How to test
- You can modify the prometheus response as it will return the `resultType` after `result` field
- Or you can just run the unit tests I provided in the `main` branch and this branch.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/util/converter/prom.go [hunk 1]
```diff
@@ -165,35 +167,20 @@ l1Fields:
...
-				rsp = backend.DataResponse{
-					Error: fmt.Errorf("unknown result type: %s", resultType),
-				}
+			// for some rare cases resultType is coming after the result.
+			// when that happens we save the bytes and parse them after reading resultType
+			// see: https://github.com/grafana/grafana/issues/64693
+			if resultType != "" {
+				rsp = readResult(resultType, rsp, iter, opt)
+			} else {
+				resultBytes = iter.SkipAndReturnBytes()
```
Comment (DanCech) [inline pkg/util/converter/prom.go:183]: There does appear to be a couple of unlikely edge cases we are not handling here, if resultType is not set at all or set to an empty string then we'll populate resultBytes but never call readResult (because we never reach line 166 due to missing resultType, or because we find an empty resultType before we find result, so we don't hit line 174 or line 181).  If we have an empty resultType *after* (a non-empty) result, then we'll go through into readResult as expected on line 174 and return the unknown result type error.

Comment (itsmylife) [reply pkg/util/converter/prom.go:183]: That's absolutely true. Those are extremely edge but valid cases. I will cover those too. Thanks for pointing them.

Comment (itsmylife) [reply pkg/util/converter/prom.go:186]: @DanCech Please see the latest state of the PR

**Review by DanCech — COMMENTED** [review]
LGTM, there are still pre-existing edge cases like what happens if there is no result element but that's outside the scope of this PR imho. I'll defer to @kylebrandt for final approval.

File: pkg/tsdb/prometheus/querydata/response_test.go [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+
+	"github.com/grafana/grafana/pkg/tsdb/prometheus/models"
+	"github.com/grafana/grafana/pkg/tsdb/prometheus/querydata/exemplar"
+)
+
+func TestQueryData_parseResponse(t *testing.T) {
+	qd := QueryData{exemplarSampler: exemplar.NewStandardDeviationSampler}
+
+	t.Run("resultType is before result the field must parsed normally", func(t *testing.T) {
+		resBody := "{\"data\":{\"resultType\":\"vector\", \"result\":[{\"metric\":{\"__name__\":\"some_name\",\"environment\":\"some_env\",\"id\":\"some_id\",\"instance\":\"some_instance:1234\",\"job\":\"some_job\",\"name\":\"another_name\",\"region\":\"some_region\"},\"value\":[1.1,\"2\"]}]},\"status\":\"success\"}"
```
Comment (kylebrandt) [inline pkg/tsdb/prometheus/querydata/response_test.go:20]: Fore these, you can replace the outer double quotes `"` with a backtick (backquote) , and then all the escaping isn't needed.

Comment (itsmylife) [reply pkg/tsdb/prometheus/querydata/response_test.go:20]: I did that and all tests failed. Let me try that once more. Maybe I did something wrong.

Comment (itsmylife) [reply pkg/tsdb/prometheus/querydata/response_test.go]: I made a mistake earlier. Now they are with backticks.

**Review by kylebrandt — APPROVED** [review]
