### PR TITLE
Alerting: Fix send resolved notifications

### LINKED ISSUE #54766: Resolved alerts are not sent to the Alertmanager
**What happened**:

Resolved alerts are not sent to the Alertmanager. This means that annotations from the resolved alert, such as the latest image token, are not present in the resolved notification.

**What you expected to happen**:

The `NeedsSending` function should return true if the state has just transitioned from `Alerting` to `Normal`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by grobinson-grafana**
**What this PR does / why we need it**:

This pull request fixes a bug where we did not send resolved alerts to Alertmanager for resolved alert instances. This meant that resolved notifications did not have the annotations from the resolved state, and a result did not also have the resolved screenshot.

**Which issue(s) this PR fixes**:

Fixes #54766

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/ngalert/state/state_test.go [hunk 1]
```diff
@@ -71,25 +71,14 @@ func TestNeedsSending(t *testing.T) {
...
 			expected:    true,
 			testState: &State{
 				State:              eval.Normal,
 				Resolved:           true,
 				LastEvaluationTime: evaluationTime,
-				LastSentAt:         evaluationTime.Add(-1 * time.Minute),
-			},
-		},
-		{
-			name:        "state: normal + resolved does _not_ send after 30 seconds (before one minute)",
```
Comment (grobinson-grafana) [inline pkg/services/ngalert/state/state_test.go:85]: Before this change `eval.Normal` states that were resolved would have to wait the interval provided to `NeedsSending`. However, because a resolved state has `Resolved` set as true for the first evaluation, and false for all subsequent evaluations, this meant that resolved states were never sent to the Alertmanager. Instead, what I think we should do is send the resolved state to the Alertmanager as soon as it is resolved, rather than attempt to wait the interval.

Comment (joeblubaugh) [reply pkg/services/ngalert/state/state_test.go:85]: What's the downside of waiting for the interval? Does it make the code too complicated?

File: pkg/services/ngalert/state/state.go [hunk 2]
```diff
@@ -174,12 +174,17 @@ func (a *State) resultNoData(alertRule *models.AlertRule, result eval.Result) {
 }
 
 func (a *State) NeedsSending(resendDelay time.Duration) bool {
-	if a.State == eval.Pending || a.State == eval.Normal && !a.Resolved {
+	if a.State == eval.Pending {
```
Comment (joeblubaugh) [inline pkg/services/ngalert/state/state.go:177]: Style nit: what about seeting a boolean result and returning it at the end of the conditional instead of doing a return in each branch?

File: pkg/services/ngalert/state/state_test.go (hunk 1 above)
Comment (joeblubaugh) [reply pkg/services/ngalert/state/state_test.go:85]: Should we instead have the `Resolved` value persist over time?

File: pkg/services/ngalert/state/state.go (hunk 2 above)
Comment (grobinson-grafana) [reply pkg/services/ngalert/state/state.go:177]: Could you give an example?

File: pkg/services/ngalert/state/state_test.go (hunk 1 above)
Comment (grobinson-grafana) [reply pkg/services/ngalert/state/state_test.go:85]: If we want to wait for the interval we need to make `Resolved` persist over time. However, since state **N** does not know about state **N-1**, we don't know if this `Resolved` resolved is the first resolved state, or the **N+1**<sup>th</sup> resolved state.

File: pkg/services/ngalert/state/state.go [hunk 3]
```diff
@@ -174,12 +174,17 @@ func (a *State) resultNoData(alertRule *models.AlertRule, result eval.Result) {
...
+		// We do not send notifications for pending states
 		return false
+	} else if a.State == eval.Normal {
+		// We should send a notification if the state is Normal because it was resolved
+		return a.Resolved
+	} else {
+		// We should send, and re-send notifications, each time LastSentAt is <= LastEvaluationTime + resendDelay
+		nextSent := a.LastSentAt.Add(resendDelay)
+		return nextSent.Before(a.LastEvaluationTime) || nextSent.Equal(a.LastEvaluationTime)
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/state/state.go:186]:
```suggestion
    switch a.State {
	case eval.Pending:
	    // We do not send notifications for pending states
		return false
	case eval.Normal:
	    // We should send a notification if the state is Normal because it was resolved
		return a.Resolved
	default:
		// We should send, and re-send notifications, each time LastSentAt is <= LastEvaluationTime + resendDelay
		nextSent := a.LastSentAt.Add(resendDelay)
		return nextSent.Before(a.LastEvaluationTime) || nextSent.Equal(a.LastEvaluationTime)
    }
```

Comment (grobinson-grafana) [reply pkg/services/ngalert/state/state.go:186]: I have written `NeedsSending` below with both an if statement and switch statement, what do we think?

Screenshot 2022-09-14 at 11 53 15

Screenshot 2022-09-14 at 11 53 51

Comment (grobinson-grafana) [reply pkg/services/ngalert/state/state.go:186]: I have written `needsSending` below with both an if statement and a switch statement, what do we think?

```
func (a *State) NeedsSending(resendDelay time.Duration) bool {
	if a.State == eval.Pending {
		// We do not send notifications for pending states
		return false
	} else if a.State == eval.Normal {
		// We should send a notification if the state is Normal because it was resolved
		return a.Resolved
	} else {
		// We should send, and re-send notifications, each time LastSentAt is <= LastEvaluationTime + resendDelay
		nextSent := a.LastSentAt.Add(resendDelay)
		return nextSent.Before(a.LastEvaluationTime) || nextSent.Equal(a.LastEvaluationTime)
	}
}
```

```
func (a *State) NeedsSending(resendDelay time.Duration) bool {
	switch a.State {
	case eval.Pending:
		// We do not send notifications for pending states
		return false
	case eval.Normal:
		// We should send a notification if the state is Normal because it was resolved
		return a.Resolved
	default:
		// We should send, and re-send notifications, each time LastSentAt is <= LastEvaluationTime + resendDelay
		nextSent := a.LastSentAt.Add(resendDelay)
		return nextSent.Before(a.LastEvaluationTime) || nextSent.Equal(a.LastEvaluationTime)
	}
}
```

Comment (yuri-tceretian) [reply pkg/services/ngalert/state/state.go:186]: I am more in favor of switch

Comment (joeblubaugh) [reply pkg/services/ngalert/state/state.go:186]: I agree with Yuri. With three cases and always comparing `a.State` the switch is easier for me to read.

File: pkg/services/ngalert/state/state.go (hunk 2 above)
Comment (joeblubaugh) [reply pkg/services/ngalert/state/state.go:177]: Even saying you go with a switch, the general pattern I'm thinking of is:

```go
outcome := defaultValue
switch cond {
case "A":
  outcome = foo()
case "B":
  outcome = bar()
}
return outcome
```

Now, some tools get made about the missing `default:`, in which case:
```go
var outcome typ
switch cond {
case "A":
  outcome = foo()
case "B":
  outcome = bar()
default:
  outcome = defaultValue
}
return outcome
```

The thing I like is that you never forget to return. I suppose the downside is that you can forget to correctly assign `outcome` and compiler won't complain because of missing returns.

Like I said, total nit, do what feels best to you.

**Review by joeblubaugh — APPROVED** [review]
I think you should do NeedsSending as a switch like Yuri recommends, so strongly consider that. But this logic is correct, the tests look good.
