### PR TITLE
Search: fix PostgreSQL query

### LINKED ISSUE #28546: Dashboard Links: Search by tag causes SQL error
**What happened:**
Search failed popups into dashboard  with tags links 

**What you expected to happen:**
Functional tags links

**How to reproduce it (as minimally and precisely as possible):**

Create tags links  with postgreSQL, but works with SQlite

**Anything else we need to know?:**

grafana-server with postgrSQL backend :  error log from postgreSQL

2020-10-26 02:35:36.746 CET [79584] ERROR:  column "dashboard.title" must appear in the GROUP BY clause or be used in an aggregate function at character 1520

2020-10-26 02:35:36.746 CET [79584] STATEMENT:  SELECT
                                dashboard.id,
                                dashboard.uid,
                                dashboard.title,
                                dashboard.slug,
                                dashboard_tag.term,
                                dashboard.is_folder,
                                dashboard.folder_id,
                                folder.uid AS folder_uid,
                                folder.slug AS folder_slug,
                                folder.title AS folder_title
                        FROM ( SELECT dashboard.id FROM dashboard LEFT OUTER JOIN dashboard_tag ON dashboard_tag.dashboard_id = dashboard.id  WHERE (
                        dashboard.id IN (
                                SELECT distinct DashboardId from (
                                        SELECT d.id AS DashboardId
                                                FROM dashboard AS d
                                                LEFT JOIN dashboard AS folder on folder.id = d.folder_id
                                                LEFT JOIN dashboard_acl AS da ON
                                                        da.dashboard_id = d.id OR
                                                        da.dashboard_id = d.folder_id
                                                LEFT JOIN team_member as ugm on ugm.team_id = da.team_id
                                                WHERE
                                                        d.org_id = $1 AND
                                                        da.permission >= $2 AND
                                                        (
                                                                da.user_id = $3 OR
                                                                ugm.user_id = $4 OR
                                                                da.role IN ($5)
                                                        )
                                        UNION
                                        SELECT d.id AS DashboardId
                                                FROM dashboard AS d
                                                LEFT JOIN dashboard AS folder on folder.id = d.folder_id
                                                LEFT JOIN dashboard_acl AS da ON
                                                        (
                                                                -- include default permissions -->
                                                                da.org_id = -1 AND (
                                                                  (folder.id IS NOT NULL AND folder.has_acl = false) OR
                                                                  (folder.id IS NULL AND d.has_acl = false)
                                                                )
                                     SELECT
                                dashboard.id,
                                dashboard.uid,
                                dashboard.title,
                                dashboard.slug,
                                dashboard_tag.term,
                                dashboard.is_folder,
                                dashboard.folder_id,
                                folder.uid AS folder_uid,
                                folder.slug AS folder_slug,
                                folder.title AS folder_title
                        FROM ( SELECT dashboard.id FROM dashboard LEFT OUTER JOIN dashboard_tag ON dashboard_tag.dashboard_id = dashboard.id  WHERE (
                        dashboard.id IN (
                                SELECT distinct DashboardId from (
                                        SELECT d.id AS DashboardId
                                                FROM dashboard AS d
                                                LEFT JOIN dashboard AS folder on folder.id = d.folder_id
                                                LEFT JOIN dashboard_acl AS da ON
                                                        da.dashboard_id = d.id OR
                                                        da.dashboard_id = d.folder_id
                                                LEFT JOIN team_member as ugm on ugm.team_id = da.team_id
                                                WHERE
                                                        d.org_id = $1 AND
                                                        da.permission >= $2 AND
                                                        (
                                                                da:q
.user_id = $3 OR
                                                                ugm.user_id = $4 OR
                                                                da.role IN ($5)
                                                        )
                                        UNION
                                        SELECT d.id AS DashboardId
                                                FROM dashboard AS d
                                                LEFT JOIN dashboard AS folder on folder.id = d.folder_id
                                                LEFT JOIN dashboard_acl AS da ON
                                                        (
                                                                -- include default permissions -->
                                                                da.org_id = -1 AND (
                                                                  (folder.id IS NOT NULL AND folder.has_acl = false) OR
                                                                  (folder.id IS NULL AND d.has_acl = false)
                                                                )
                                                        )
                                                WHERE
                                                        d.org_id = $6 AND
                                                        da.permission >= $7 AND
                                                        (
                                                                da.user_id = $8 OR
                                                                da.role IN ($9)
                                                        )
                                ) AS a
                        )
                )
                 AND dashboard.org_id=$10 AND dashboard_tag.term IN ($11) GROUP BY dashboard.id HAVING COUNT(dashboard.id) >= $12 ORDER BY dashboard.title ASC LIMIT 100 OFFSET 0) AS ids
                        INNER JOIN dashboard ON ids.id = dashboard.id
        LEFT OUTER JOIN dashboard AS folder ON folder.id = dashboard.folder_id
                        LEFT OUTER JOIN dashboard_tag ON dashboard.id = dashboard_tag.dashboard_id
                   )
                                                WHERE
                                                        d.org_id = $6 AND
                                                        da.permission >= $7 AND
                                                        (
                                                                da.user_id = $8 OR
                                                                da.role IN ($9)
                                                        )
                                ) AS a
                        )
                )
                 AND dashboard.org_id=$10 AND dashboard_tag.term IN ($11) GROUP BY dashboard.id HAVING COUNT(dashboard.id) >= $12 ORDER BY dashboard.title ASC LIMIT 100 OFFSET 0) AS ids
                        INNER JOIN dashboard ON ids.id = dashboard.id
        LEFT OUTER JOIN dashboard AS folder ON folder.id = dashboard.folder_id
                        LEFT OUTER JOIN dashboard_tag ON dashboard.id = dashboard_tag.dashboard_id
         ORDER BY dashboard.title ASC

**Environment:**

Grafana version: 7.2.2
Data source type & version: PostgreSQL10
OS Grafana is installed on: Redhat7.7 RHEL
User OS & Browser: windows 10  with Firefox 81.0.1  & Chrome
Grafana plugins:
Others:

Thank you.

With kind regards

Nat

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
It fixes a customer issue when searching by tags using PostgreSQL 13.3 used to fail with:
`ERROR: column "dashboard.title" must appear in the GROUP BY clause or be used in an aggregate function at character 1520`
This is was also reported in #28546 but we were unable to reproduce it. I wasn't able to reproduce the failure myself using PostgreSQL 13.3 but I believe that the fix does not harm.

<details>
<summary>search by tag: before the fix
</summary>

```
 SELECT
                        dashboard.id,
                        dashboard.uid,
                        dashboard.title,
                        dashboard.slug,
                        dashboard_tag.term,
                        dashboard.is_folder,
                        dashboard.folder_id,
                        folder.uid AS folder_uid,
                        folder.slug AS folder_slug,
                        folder.title AS folder_title  FROM ( SELECT dashboard.id FROM dashboard LEFT OUTER JOIN dashboard_tag ON dashboard_tag.dashboard_id = dashboard.id  WHERE dashboard.org_id=1 AND dashboard_tag.term IN ('panel-tests') AND dashboard.title ILIKE 'Can%' GROUP BY dashboard.id HAVING COUNT(dashboard.id) >= 1 ORDER BY dashboard.title ASC LIMIT 1000 OFFSET 0) AS ids
                INNER JOIN dashboard ON ids.id = dashboard.id
LEFT OUTER JOIN dashboard AS folder ON folder.id = dashboard.folder_id
                LEFT OUTER JOIN dashboard_tag ON dashboard.id = dashboard_tag.dashboard_id
 ORDER BY dashboard.title ASC
```
</details>

<details>
<summary>search by tag: with the fix
</summary>

```

 SELECT
                        dashboard.id,
                        dashboard.uid,
                        dashboard.title,
                        dashboard.slug,
                        dashboard_tag.term,
                        dashboard.is_folder,
                        dashboard.folder_id,
                        folder.uid AS folder_uid,
                        folder.slug AS folder_slug,
                        folder.title AS folder_title  FROM ( SELECT dashboard.id FROM dashboard LEFT OUTER JOIN dashboard_tag ON dashboard_tag.dashboard_id = dashboard.id  WHERE dashboard.org_id=1 AND dashboard_tag.term IN ('panel-tests') AND dashboard.title ILIKE 'Can%' GROUP BY dashboard.title, dashboard.id HAVING COUNT(dashboard.id) >= 1 ORDER BY dashboard.title ASC LIMIT 1000 OFFSET 0) AS ids
                INNER JOIN dashboard ON ids.id = dashboard.id
LEFT OUTER JOIN dashboard AS folder ON folder.id = dashboard.folder_id
                LEFT OUTER JOIN dashboard_tag ON dashboard.id = dashboard_tag.dashboard_id
 ORDER BY dashboard.title ASC
```
</details>

<details>
<summary>search by tag inside folder: before the fix</summary>

```
SELECT
                        dashboard.id,
                        dashboard.uid,
                        dashboard.title,
                        dashboard.slug,
                        dashboard_tag.term,
                        dashboard.is_folder,
                        dashboard.folder_id,
                        folder.uid AS folder_uid,
                        folder.slug AS folder_slug,
                        folder.title AS folder_title  FROM ( SELECT dashboard.id FROM dashboard LEFT OUTER JOIN dashboard_tag ON dashboard_tag.dashboard_id = dashboard.id  WHERE dashboard.org_id=1 AND dashboard_tag.term IN ('panel-tests') AND dashboard.title ILIKE 'Can%' AND dashboard.is_folder = false AND dashboard.folder_id IN (1) GROUP BY dashboard.id HAVING COUNT(dashboard.id) >= 1 ORDER BY dashboard.title ASC LIMIT 1000 OFFSET 0) AS ids
                INNER JOIN dashboard ON ids.id = dashboard.id
LEFT OUTER JOIN dashboard AS folder ON folder.id = dashboard.folder_id
                LEFT OUTER JOIN dashboard_tag ON dashboard.id = dashboard_tag.dashboard_id
 ORDER BY dashboard.title ASC
```
</details>

<details>
<summary>search by tag inside folder: with the fix</summary>

```
SELECT
                        dashboard.id,
                        dashboard.uid,
                        dashboard.title,
                        dashboard.slug,
                        dashboard_tag.term,
                        dashboard.is_folder,
                        dashboard.folder_id,
                        folder.uid AS folder_uid,
                        folder.slug AS folder_slug,
                        folder.title AS folder_title  FROM ( SELECT dashboard.id FROM dashboard LEFT OUTER JOIN dashboard_tag ON dashboard_tag.dashboard_id = dashboard.id  WHERE dashboard.org_id=1 AND dashboard_tag.term IN ('panel-tests') AND dashboard.title ILIKE 'Can%' AND dashboard.is_folder = false AND dashboard.folder_id IN (1) GROUP BY dashboard.title, dashboard.id HAVING COUNT(dashboard.id) >= 1 ORDER BY dashboard.title ASC LIMIT 1000 OFFSET 0) AS ids
                INNER JOIN dashboard ON ids.id = dashboard.id
LEFT OUTER JOIN dashboard AS folder ON folder.id = dashboard.folder_id
                LEFT OUTER JOIN dashboard_tag ON dashboard.id = dashboard_tag.dashboard_id
 ORDER BY dashboard.title ASC
```
</details>

**Which issue(s) this PR fixes**:

Fixes #28546

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/sqlstore/searchstore/builder.go [hunk 1]
```diff
@@ -115,15 +115,22 @@ func (b *Builder) applyFilters() (ordering string) {
...
 	}
 
+	if len(groups) > 0 {
+		cols := make([]string, 0, len(orders)+len(groups))
+		for _, o := range orders {
+			o := strings.TrimSuffix(o, " DESC")
+			o = strings.TrimSuffix(o, " ASC")
+			cols = append(cols, o)
+		}
+		cols = append(cols, groups...)
```
Comment (wbrowne) [inline pkg/services/sqlstore/searchstore/builder.go:129]: Could it be that an ordered column is already in `groups`?

Comment (papagian) [reply pkg/services/sqlstore/searchstore/builder.go:129]: good point! I believe that this wouldn't affect the query result but it may have performance implications, therefore better to filter them out, thanks!

**Review by sakjur — APPROVED** [review]
Would we get away with not having `GROUP BY dashboard.title` if there is no other `GROUP BY`? I think the answer is yes and if so this looks good :+1: Added a comment about adding a comment to make sure it's clear why this was added.

**Comment by srclosson** [comment]
Merging this one in preparation for the 8.4.2 release
