### PR TITLE
Dashboard: Propagate unhandled errors when saving dashboard

### LINKED ISSUE #24015: Save dashboard failure from server doesn't propagate to UI
**What happened**:
Saved dashboard, but didn't receive any feedback that dashboard saved.

**What you expected to happen**:
Success info message saying dashboard saved.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create new dashboard
2. Add graph panel
3. Alert tab -> Create alert and exit edit panel mode
4. Save dashboard

**Anything else we need to know?**:
Inspecting network response from save dashboard I notice a 422 status code with payload:
```json
{"message":"Alert validation error: error in condition 0: Evaluator 'IS ABOVE' is missing the threshold parameter PanelId: 2"}
```

Would have expected that error to show in alert message.

**Environment**:
- Grafana version: 7.0.0-beta1
- User OS & Browser: Chrome 81

### PR DESCRIPTION
**Pull request by peterholmberg**
**What this PR does / why we need it**:
Fix an issue where unhandled errors would not get propagated to the frontend.

**Which issue(s) this PR fixes**:
Fixes #24015

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/dashboard/components/SaveDashboard/SaveDashboardErrorProxy.tsx [hunk 1]
```diff
@@ -25,7 +25,7 @@ export const SaveDashboardErrorProxy: React.FC<SaveDashboardErrorProxyProps> = (
   const { onDashboardSave } = useDashboardSave(dashboard);
 
   useEffect(() => {
-    if (error.data) {
+    if (error.data && (error.data.status === 'version-mismatch' || error.data.status === 'name-exists')) {
```
Comment (torkelo) [inline public/app/features/dashboard/components/SaveDashboard/SaveDashboardErrorProxy.tsx:28]: missing 'plugin-dashboard'

**Review by torkelo — APPROVED** [review]
