### PR TITLE
InfluxDB: Use grafana timeout value for flux queries

### LINKED ISSUE #29457: Queries failing after 60s despite changing dataproxy.timeout to > 60s(changed from 30/default but 180 is not reflecting) for Influx datasource
What happened:
Long running queries from Influx Datasource failed to fetch for larger data within 60s but dataproxy.timeout is changed to 180s (which is not reflecting)

What you expected to happen:
We expect that queries should not appear to time out in less time than has been configured in the dataproxy.timeout setting.

**Environment**:
- Grafana version: 7.X.X
- Data source type & version: InfluxDB
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

Use grafana timeout configuration for flux query calls

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/29457

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/tsdb/influxdb/influxdb.go [hunk 1]
```diff
@@ -23,12 +24,14 @@ import (
 var logger log.Logger = log.New("tsdb.influxdb")
 
 type Service struct {
+	Cfg      *setting.Cfg
 	im       instancemgmt.InstanceManager
 	features featuremgmt.FeatureToggles
 }
 
-func ProvideService(httpClient httpclient.Provider, features featuremgmt.FeatureToggles) *Service {
+func ProvideService(cfg *setting.Cfg, httpClient httpclient.Provider, features featuremgmt.FeatureToggles) *Service {
```
Comment (marefr) [inline pkg/tsdb/influxdb/influxdb.go:32]: You shouldn't use this as a dependency. Rather I think you should read the timeout value from HTTP options retrieved in newInstanceSettings?

**Review by marefr — CHANGES_REQUESTED** [review]

**Review by marefr — APPROVED** [review]
LGTM

**Comment by lars20070** [comment]
Thanks for the fix! :+1:
