### PR TITLE
TextPanel: Fixes so panel title is updated when variables change

### LINKED ISSUE #30729: TextPanel: Panel title with variable doesn't update when changing variable value
**What happened**:
When a TextPanel has a panel title that contains a variable the title isn't updated when changing variable value.

**What you expected to happen**:
Panel title with variable values should always interpolate to the correct variable values. 

**How to reproduce it (as minimally and precisely as possible)**:
Try it out here:
https://play.grafana.org/d/c9ouF7LMk/key-value-variable-in-title?orgId=1&var-server=20

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.0-beta1
- Data source type & version: NA
- OS Grafana is installed on: Grafana Play
- User OS & Browser: Mac OSX, chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
I originally was going after a fix for this #30729 which is almost a one-liner, but then I got caught up in refactoring the PanelHeader. 
I might have gone a bit overboard with the refactoring, but I couldn't help myself because it felt so much better to have all the concerns split out into smaller components.

**Which issue(s) this PR fixes**:
Fixes #30729

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/dashboard/dashgrid/PanelChrome.tsx [hunk 1]
```diff
@@ -347,7 +345,7 @@ export class PanelChrome extends Component<Props, State> {
           isEditing={isEditing}
           isViewing={isViewing}
           data={data}
-          updateLocation={updateLocation}
+          renderCounter={renderCounter}
```
Comment (hugohaggmark) [inline public/app/features/dashboard/dashgrid/PanelChrome.tsx:348]: This is actually the fix for the issue I fixed.

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx [hunk 2]
```diff
@@ -1,175 +1,50 @@
...
-    });
-  };
-
-  closeMenu = () => {
-    this.setState({
-      panelMenuOpen: false,
-    });
-  };
-
+export class PanelHeader extends PureComponent<Props> {
```
Comment (dprokop) [inline public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx:31]: Would it make sense to just make it function component?

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx [hunk 3]
```diff
@@ -1,175 +1,50 @@
...
-    );
-  };
-
   render() {
-    const { panel, error, isViewing, isEditing, data, alertState } = this.props;
-    const { menuItems } = this.state;
+    const { panel, error, isViewing, isEditing, data, alertState, dashboard } = this.props;
     const title = panel.replaceVariables(panel.title, {}, 'text');
 
     const panelHeaderClass = classNames({
```
Comment (dprokop) [inline public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx:40]: Since we are here, maybe let's get rid of `classNames` in favour of `cx`?

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx [hunk 4]
```diff
@@ -179,56 +54,38 @@ export class PanelHeader extends PureComponent<Props, State> {
...
+                  />
+                  {data.request && data.request.timeInfo && (
+                    <span className="panel-time-info">
+                      <Icon name="clock-nine" size="sm" /> {data.request.timeInfo}
+                    </span>
+                  )}
+                </div>
+              );
+            }}
+          </PanelHeaderMenuTrigger>
```
Comment (dprokop) [inline public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx:86]: neat!

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderMenuProvider.tsx [hunk 5]
```diff
@@ -0,0 +1,29 @@
+import { FC, ReactElement, useEffect, useState } from 'react';
+import { useSelector } from 'react-redux';
+import { PanelMenuItem } from '@grafana/data';
+
+import { DashboardModel, PanelModel } from '../../state';
+import { StoreState } from '../../../../types';
+import { getPanelMenu } from '../../utils/getPanelMenu';
+
+interface Api {
```
Comment (dprokop) [inline public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderMenuProvider.tsx:9]:
```suggestion
interface PanelHeaderMenuProviderApi {
```

to keep this consistent with the other naming you have in PanelHeaderMenuTrigger

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderMenuTrigger.tsx [hunk 6]
```diff
@@ -0,0 +1,55 @@
+import React, { FC, HTMLAttributes, MouseEvent, ReactElement, useCallback, useState } from 'react';
+
+interface ClickCoordinates {
+  x: number;
+  y: number;
+}
```
Comment (dprokop) [inline public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderMenuTrigger.tsx:6]: We already have the same interface https://github.com/grafana/grafana/blob/1d689888b0fc2de2dbed6e606eee19561a3ef006/packages/grafana-ui/src/components/uPlot/plugins/ClickPlugin.tsx#L29 that's not exported from grafana ui. Maybe we can have this type in grafana/data like `CartesianCoords2D` so we can reuse it rather than recreating here and there? I bet we have more intarfaces like this.

**Review by dprokop — COMMENTED** [review]
Did a quick review (no testing yet) and left few comments. Looks good!

**Review by torkelo — COMMENTED** [review]
Nice refactorings! :heart: 

fixing bugs and doing some leaving the code in a better shape :)

**Review by dprokop — APPROVED** [review]
@hugohaggmark tested it and it works great. One thing I've noticed is the lack of the alerting icons in the header but maybe it's related to this branch being not synced with master? I think @torkelo fixed the issue already in https://github.com/grafana/grafana/pull/30840

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx (hunk 3 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx:40]: Sure thing!

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx (hunk 2 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx:31]: That makes a lot of sense.

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderMenuProvider.tsx (hunk 5 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderMenuProvider.tsx:9]: Will fix

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderMenuTrigger.tsx (hunk 6 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderMenuTrigger.tsx:6]: Yes, good suggestion!

**Comment by hugohaggmark** [comment]
@dprokop I merged with master so the alerting icons should work now too, other than that please have another look when you have time. Thank you!

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx (hunk 2 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx]: Fixed.

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx (hunk 3 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx]: Fixed!

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderMenuProvider.tsx (hunk 5 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderMenuProvider.tsx]: Fixed!

File: public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderMenuTrigger.tsx (hunk 6 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderMenuTrigger.tsx]: Fixed and changed ClickPlugin accordingly.

**Review by dprokop — APPROVED** [review]
Awesome @hugohaggmark!
