### PR TITLE
Datasource: Fixes storing of secureJSONData when creating/updating datasource

### LINKED ISSUE #45273: Datasource: Securejsondata stripped away while creating/updating data source
**What happened**:
Securejsondata stripped away while creating/updating data source

**How to reproduce it (as minimally and precisely as possible)**:
Create a new data source that uses secure json data - CloudWatch or Azure Monitor for example. 

**Environment**:
- Grafana version: 8.4-pre (main)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

securejsondata

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Fixes an issue introduced by #44987 where bus dispatch was replaced by calling sqlstore directly. This should have been changed to call the datasource service since that is responsible for encrypting secrets. 

**Which issue(s) this PR fixes**:
Fixes #45273

**Special notes for your reviewer**:
To be able to mock the datasource service I had to introduce a quite big refactoring adding an interface for the datasource service.

### CODE REVIEW

File: pkg/services/datasources/service/cache_service.go [hunk 1]
```diff
@@ -1,27 +1,27 @@
...
 	"fmt"
 	"time"
 
 	"github.com/grafana/grafana/pkg/infra/localcache"
+	"github.com/grafana/grafana/pkg/infra/log"
 	"github.com/grafana/grafana/pkg/models"
 	"github.com/grafana/grafana/pkg/services/sqlstore"
 )
 
+var (
```
Comment (ying-jeanne) [inline pkg/services/datasources/service/cache_service.go:14]: how about remove the global logger also in the PR. I know it is not related to this :D

**Review by sunker — APPROVED** [review]
Tested and it's working as expected.

**Review by ying-jeanne — APPROVED** [review]
LGTM, left some comments, but it could be done later, not strictly related to the fix.

**Review by zserge — APPROVED** [review]
I like the new structure much more! Thanks
