### PR TITLE
LogRow: Fix placement of icon

### LINKED ISSUE #50842: 9.0 log panels, line spacing increased a lot
After upgrading from Grafana 8.5 to 9.0 the line spacing between log entries in Loki log panels and explore window is a lot bigger.
Previously a small browser window that could fit 43 lines now only fits 33, this makes reading logs more difficult.

Left side: 9.0, Right side:8.5
image

Using Firefox, zoom level 150% on both sides. Issue can be observed at 100% also but less prominent.

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
https://github.com/grafana/grafana/pull/48759 caused issue with placement of icon in log row. This PR fixes it for LogRow. 

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/50842

Before: 
image
image

Now: 
image
image

### CODE REVIEW

File: packages/grafana-ui/src/components/Logs/LogRow.tsx [hunk 1]
```diff
@@ -67,8 +67,7 @@ const getStyles = (theme: GrafanaTheme2) => {
   return {
     topVerticalAlign: css`
       label: topVerticalAlign;
-      vertical-align: top;
-      margin-top: -${theme.spacing(0.5)};
+      margin-top: -${theme.spacing(0.9)};
```
Comment (ivanahuckova) [inline packages/grafana-ui/src/components/Logs/LogRow.tsx:70]: I tried here `-${theme.spacing(1)};`, but `-${theme.spacing(0.9)};` looked better and more aligned.

**Review by gabor — APPROVED** [review]
nice, LGTM!
