### PR TITLE
BarChart: fix top y tick clipping when x labels are rotated

### LINKED ISSUE #52914: barchart: when labels are rotated 90 degrees the top of the y-axis is truncated
**What happened**:

Change the label orientation to 90 degrees, the top of the y-axis is truncated. The length of the label doesn't matter also tried to adjust the maximum label length. 

**How to reproduce it (as minimally and precisely as possible)**:

Create a bar chart
Use the TestDB Datasource and select CSV Content
Add this CSV content: 

```
label,value
"kdjfdkjal",3000
"fjakjd",45000
"kdjfdkjal",3
```
Before rotation:

Screen Shot 2022-07-27 at 6 15 34 PM

after rotation: 
Screen Shot 2022-07-27 at 6 15 20 PM

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.05
- Data source type & version: TestDataDB
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes #52914

avoids setting top chart padding to 0.

image

### CODE REVIEW

File: public/app/plugins/panel/barchart/utils.ts [hunk 1]
```diff
@@ -302,7 +302,7 @@ function getRotationPadding(frame: DataFrame, rotateLabel: number, valueMaxLengt
   // Add padding to the bottom to avoid clipping the rotated labels.
   const paddingBottom = Math.sin(((rotateLabel >= 0 ? rotateLabel : rotateLabel * -1) * Math.PI) / 180) * maxLength;
 
-  return [0, paddingRight, paddingBottom, paddingLeft];
+  return [Math.round(UPLOT_AXIS_FONT_SIZE * uPlot.pxRatio), paddingRight, paddingBottom, paddingLeft];
```
Comment (leeoniya) [inline public/app/plugins/panel/barchart/utils.ts:305]: `uPlot.pxRatio` is a cached `window.devicePixelRatio`, because that's expensive to read directly, for some reason. :shrug:

Comment (codeincarnate) [reply public/app/plugins/panel/barchart/utils.ts:305]: That makes sense, I'm guessing the browser might actually query for it when read but not 100% sure. Unrelated but this _might_ be the source of a strange font rendering error I've seen. Will follow up with you 😄

**Review by codeincarnate — APPROVED** [review]
LGTM
