### PR TITLE
AppChrome/MegaMenu: Fixes issue with default state being initialised to undocked 

### LINKED ISSUE #103495: AppChrome: Mega menu starts undocked on xl viewport
Clear local storage. 

Set viewport to 1280 (somewhere between xl = 1200 and xxl = 1440 breakpoint) 

Notice the missing mega menu. 

Expand viewport a bit (beyond xxl = 1440), See mega menu appear. Now go back down below 1440, it remains (Which it should). 

Caused by the initial state of megaMenuDocked is set incorrectly:
https://github.com/grafana/grafana/blob/main/public/app/core/components/AppChrome/AppChromeService.tsx#L45 

Using xxl breakpoint, while the responsive logic to dynamically update it is using xl breakpoint. 

Fixing this bug also requires a rethink of the navigation e2e tests. 

https://github.com/grafana/grafana/blob/main/e2e/various-suite/navigation.spec.ts#L6 

As they are built assuming the initial state of the menu is always undocked given screen size 1280px.

### PR DESCRIPTION
**Pull request by torkelo**
Extracted from https://github.com/grafana/grafana/pull/103488 to help make that easier to review 

Fixes https://github.com/grafana/grafana/issues/103495

* Fixes bug in explore with docked nav not undocking when screen size is reduced, related to buggy useMediaQueryChange hook
* Fixes buggy / poorly designed useMediaQueryChange hook (onChange was never memorized so always triggered the useEffect, and having multiple useMediaQueryChange with the same breakpoint caused conflicts)
* Adds new useMediaQueryMinWidth hook

Because this fixes the default state of the mega menu I had to
* Correct the e2e tests that where written assuming this bug exists 
* Fix new a11y errors that showed up in mega menu now that it's correctly open by default (The new errors where mostly due to using a div inside the ul  (Stack wrapping MegaMenuItem)). 

Explore bug 

[explore_bug.webm](https://github.com/user-attachments/assets/618d82b1-bd3a-4466-9703-8fed38c1cb81)

### CODE REVIEW

File: public/app/core/components/AppChrome/MegaMenu/MegaMenu.tsx [hunk 1]
```diff
@@ -116,15 +116,14 @@ export const MegaMenu = memo(
           <ScrollContainer height="100%" overflowX="hidden" showScrollIndicators>
             <ul className={styles.itemList} aria-label={t('navigation.megamenu.list-label', 'Navigation')}>
               {navItems.map((link, index) => (
-                <Stack key={link.text} direction={index === 0 ? 'row-reverse' : 'row'} alignItems="start">
```
Comment (torkelo) [inline public/app/core/components/AppChrome/MegaMenu/MegaMenu.tsx:119]: this Stack caused a11y errors (no divs allowed inside uls). And seems unnnessary as MegaMenuItem is always a single item (li) so this logic of reverse-row never has any effect.

File: .pa11yci-pr.conf.js [hunk 2]
```diff
@@ -139,13 +139,13 @@ var config = {
...
       rootElement: '.main-view',
-      threshold: 2,
+      threshold: 4,
     },
     {
       url: '${HOST}/dashboards',
       wait: 500,
       rootElement: '.main-view',
-      threshold: 0,
+      threshold: 2,
```
Comment (torkelo) [inline .pa11yci-pr.conf.js:148]: these are due to mega menu now being visible, and complaining about contrast of text links in mega menu. 

think we need a tweak to dark theme primary and secondary text colors maybe, will talk to ed

File: public/app/core/hooks/useMediaQueryChange.ts [hunk 3]
```diff
@@ -1,17 +0,0 @@
...
-  onChange: (e: MediaQueryListEvent) => void;
-}) {
-  useEffect(() => {
-    const mediaQuery = window.matchMedia(`(min-width: ${breakpoint}px)`);
-    const onMediaQueryChange = (e: MediaQueryListEvent) => onChange(e);
-    mediaQuery.addEventListener('change', onMediaQueryChange);
-
-    return () => mediaQuery.removeEventListener('change', onMediaQueryChange);
-  }, [breakpoint, onChange]);
-}
```
Comment (torkelo) [inline public/app/core/hooks/useMediaQueryChange.ts:17]: because onChange was never memoized by any user of this hook this useEffect was always firing / cleanup on ever re-render. This caused (at least in explore which triggers a lot of AppChromeService state updates) bugs to appear when you resize.

I think this hook was a bit poorly designed, better to return a "isMatch" state instead and have the change effect handled by the caller rather than passing in a on change handler.

File: public/app/core/components/AppChrome/MegaMenu/MegaMenu.tsx (hunk 1 above)
Comment (ashharrison90) [reply public/app/core/components/AppChrome/MegaMenu/MegaMenu.tsx:119]: ah yeah, this is a hang over from the old docked implementation where the dock button lived in the first row alongside `Home`. nice job ripping it out 👍

File: public/app/core/components/AppChrome/AppChromeService.tsx [hunk 4]
```diff
@@ -42,7 +42,7 @@ export class AppChromeService {
 
   private megaMenuDocked = Boolean(
     window.innerWidth >= config.theme2.breakpoints.values.xl &&
-      store.getBool(DOCKED_LOCAL_STORAGE_KEY, Boolean(window.innerWidth >= config.theme2.breakpoints.values.xxl))
+      store.getBool(DOCKED_LOCAL_STORAGE_KEY, Boolean(window.innerWidth >= config.theme2.breakpoints.values.xl))
```
Comment (ashharrison90) [inline public/app/core/components/AppChrome/AppChromeService.tsx:45]: so this was as intended. we decided to have different breakpoints for the _initial_ docking vs once you're already docked

having said that, i don't think we get much benefit from those separate breakpoints... so i think you're right, this is better 👍 makes things simpler

File: public/app/core/components/AppChrome/MegaMenu/MegaMenuItem.tsx [hunk 5]
```diff
@@ -162,6 +162,7 @@ const getStyles = (theme: GrafanaTheme2) => ({
   listItem: css({
     flex: 1,
     maxWidth: '100%',
+    alignItems: 'start',
```
Comment (ashharrison90) [inline public/app/core/components/AppChrome/MegaMenu/MegaMenuItem.tsx:165]: curious - what do we need this for? 🤔

File: .pa11yci-pr.conf.js (hunk 2 above)
Comment (ashharrison90) [reply .pa11yci-pr.conf.js:148]: i think i know what's going on here 💡 

think it's due to the scroll indicators (gradient at the scroll boundary) on the megamenu causing the contrast to be lower than it should be. also explains why it's always the same 2 links. 

one thing we could do is give the scroll indicators a `data-` attribute and hide them in the pa11y tests via the `hideElements` option [here](https://github.com/grafana/grafana/blob/main/.pa11yci.conf.js#L49) and [here](https://github.com/grafana/grafana/blob/main/.pa11yci-pr.conf.js#L59)

or maybe even better would be to give them a `role="presentation"` and hide all `role="presentation"` elements? that's what they do in [their docs](https://github.com/pa11y/pa11y?tab=readme-ov-file#hideelements-string). but i'm not sure if there would be any side effects of that 😬

**Review by ashharrison90 — COMMENTED** [review]
think we should try to sort the pa11y thing, otherwise lgtm 👍

File: public/app/core/hooks/useMediaQueryChange.ts (hunk 3 above)
Comment (ashharrison90) [reply public/app/core/hooks/useMediaQueryChange.ts:17]: yeah agreed, nice catch 🙌

File: public/app/core/components/AppChrome/MegaMenu/MegaMenuItem.tsx (hunk 5 above)
Comment (torkelo) [reply public/app/core/components/AppChrome/MegaMenu/MegaMenuItem.tsx:165]: @ashharrison90 no idea, you added it to the wrapping Stack that I removed

File: .pa11yci-pr.conf.js (hunk 2 above)
Comment (torkelo) [reply .pa11yci-pr.conf.js]: @ashharrison90 pushed update to add role="presentation" to the scroll indicators and updated the pa11y config

File: public/app/core/components/AppChrome/MegaMenu/MegaMenuItem.tsx (hunk 5 above)
Comment (torkelo) [reply public/app/core/components/AppChrome/MegaMenu/MegaMenuItem.tsx]: removed it

File: public/app/core/components/AppChrome/AppChromeService.tsx (hunk 4 above)
Comment (torkelo) [reply public/app/core/components/AppChrome/AppChromeService.tsx:45]: yea, having different initial logic makes the automatic logic when screen changes a lot more complex, so think it makes sense for both to use the same breakpoint

File: .pa11yci-pr.conf.js [hunk 6]
```diff
@@ -56,7 +56,8 @@ var config = {
     },
     // see https://github.com/grafana/grafana/pull/41693#issuecomment-979921463 for context
     // on why we're ignoring singleValue/react-select-*-placeholder elements
-    hideElements: '#updateVersion, [class*="-singleValue"], [id^="react-select-"][id$="-placeholder"]',
+    hideElements:
+      '#updateVersion, [class*="-singleValue"], [id^="react-select-"][id$="-placeholder"], div[aria-role=presentation]',
```
Comment (ashharrison90) [inline .pa11yci-pr.conf.js:60]: think this just needs to be `div[role="presentation"]`

File: .pa11yci.conf.js [hunk 7]
```diff
@@ -46,7 +46,8 @@ var config = {
     },
     // see https://github.com/grafana/grafana/pull/41693#issuecomment-979921463 for context
     // on why we're ignoring singleValue/react-select-*-placeholder elements
-    hideElements: '#updateVersion, [class*="-singleValue"], [id^="react-select-"][id$="-placeholder"]',
+    hideElements:
+      '#updateVersion, [class*="-singleValue"], [id^="react-select-"][id$="-placeholder"], div[aria-role=presentation]',
```
Comment (ashharrison90) [inline .pa11yci.conf.js:50]: same here

Comment (torkelo) [reply .pa11yci.conf.js]: fixed

Comment (torkelo) [reply .pa11yci.conf.js]: in their example docs they don't quotes it 🤷

**Comment by ashharrison90** [comment]
@torkelo same as you, couldn't get it working. in the interests of speed i'll just up the thresholds and investigate it in another PR 👍

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍

**Comment by torkelo** [comment]
@ashharrison90 thanks ash!

**Review by eledobleefe — APPROVED** [review]
LGTM 👌
