### PR TITLE
Provisioning: Validate that datasource access field equals to direct or proxy

### LINKED ISSUE #25866: Data source provisioning access value error not caught by validator
**What happened**:
Using a data source provisioning yaml with a certain incorrect value for the "access" key will still add the data source. The data source however, is not usable.

Example to incorrect data source provisioning yaml:
```
    apiVersion: 1
    datasources:
        - access: proxy,
          editable: true
          name: prometheus
          isDefault: true
          orgId: 1
          type: prometheus
          url: localhost:9090
          version: 1
```

Note the error on the "access" key property: "proxy," (a comma at the end). Grafana will parse this data source and add it without any warnings or errors. When trying to create a dashboard using data from the data source a hard-to-parse UI error will occur: "Failed to fetch"

**What you expected to happen**:
Receive an error of incorrect value on key "access".

**How to reproduce it (as minimally and precisely as possible)**:

- Create a data source provisioning file using the example given above, eg: /etc/grafana/provisioning/datasources/prom.yaml
- Start Grafana (note no error message of incorrect syntax)
- Try to add a panel in a new dashboard with any data from the data source (eg; PromQL: prometheus_build_info)
- Note the exclamation point in the corner of the panel, hovering over the exclamation point shows the error: "Failed to fetch"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.4
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Ubuntu 18.04
- Grafana plugins: None
- Others: N/A

### PR DESCRIPTION
**Pull request by nabokihms**
**What this PR does / why we need it**:
This PR adds validation of datasource configuration that `access` field should equal to proxy or direct. If it's not, we will change the value to 'proxy' (default value) and will warn about it into the console log. 

**Which issue(s) this PR fixes**:
Fixes #25866

**Special notes for your reviewer**:
Nothing special. There was a difficult choice between error and warning. I chose the second because returning an error will break Grafana startup for users with invalid value in access filed (which makes this change a breaking change).

### CODE REVIEW

File: pkg/services/provisioning/datasources/config_reader_test.go [hunk 1]
```diff
@@ -149,6 +150,12 @@ func TestDatasourceAsConfig(t *testing.T) {
 			So(err, ShouldNotBeNil)
 		})
 
+		Convey("invalid access should warn about invalid value and return 'proxy'", func() {
+			reader := &configReader{log: logger}
+			configs, _ := reader.readConfig(invalidAccess)
```
Comment (aknuds1) [inline pkg/services/provisioning/datasources/config_reader_test.go:155]: Why do you ignore the error here, instead of verifying it's nil?

Comment (nabokihms) [reply pkg/services/provisioning/datasources/config_reader_test.go:155]: My bad. I will fix it.

**Review by papagian — APPROVED** [review]
LGTM; thank you for contributing to grafana and fixing this!

**Review by aknuds1 — APPROVED** [review]

**Comment by aknuds1** [comment]
Thank you for contributing to Grafana!
