### PR TITLE
Fix search item links

### LINKED ISSUE #23209: Search: Clicking search items cause full page reload & they are no longer links
* Clicking a search item should not cause page reload
* They should be regular anchor links so CMD/CTRL click works to open in new tab

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
Use `a` inside result item.

**Which issue(s) this PR fixes**:

Fixes #23209 

Also fix folder icon alignment.
**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/search/components/SearchItem.tsx [hunk 1]
```diff
@@ -48,15 +44,16 @@ export const SearchItem: FC<Props> = ({ item, editable, onToggleSelection, onTag
...
-        <span className={styles.folderTitle}>{item.folderTitle}</span>
-      </div>
-      <TagList tags={item.tags} onClick={tagSelected} className={styles.tags} />
+      <a href={item.url} className={styles.link}>
+        <Icon className={styles.icon} name="th-large" />
+        <div className={styles.body} onClick={onItemClick}>
+          <span>{item.title}</span>
+          <span className={styles.folderTitle}>{item.folderTitle}</span>
+        </div>
+        <TagList tags={item.tags} onClick={tagSelected} className={styles.tags} />
```
Comment (torkelo) [inline public/app/features/search/components/SearchItem.tsx]: Clicking on tags no longer works, they need a e.stopPropagation() or e.preventDefault to stop the event from bubbling to the anchor

Comment (Clarity-89) [reply public/app/features/search/components/SearchItem.tsx]: It's there in the `tagSelected`, but it doesn't work. Neither does `preventDefault` nor their `event.nativeEvent` alternatives. Could be something to do with angular routing and how it attaches listeners to anchor tags. 

The only solution I was able to come up with is to attach an event listener to the tags' `ref` and prevent default there. Can't think of any better alternatives.

**Review by torkelo — APPROVED** [review]
