### PR TITLE
Dashboard: Slider overlapping with right input field

### LINKED ISSUE #71220: Dashboard: slider component range number overlapping with input field
### 
# What went wrong?

There is a slider component on the field config right-side component. The slider's top range number is overlapping with the right-standing input field.

Current view:
Screenshot 2023-07-07 at 17 10 33

Possible solution (align number by the right edge of slider):
Screenshot 2023-07-07 at 17 13 24

Also would be great to have more space between the slider and the input field.

### 
# How do we reproduce it?

See screenshots above.

### 
# What Grafana version are you using?

v10.1.0-pre

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by Develer**
**What is this feature?**

There is a slider component on the field config right-side component. The slider's top range number is overlapping with the right-standing input field.

Current view:
Screenshot 2023-07-07 at 17 10 33

Possible solution (align number by the right edge of slider):
Screenshot 2023-07-07 at 17 13 24

I decided to go a bit different way and just added left-margin based on [Grafana Labs Storybook](https://developers.grafana.com/ui/latest/index.html?path=/story/forms-slider--with-marks). Works fine for me. I think in most case scenarios max value is 100 so it shouldn't be any overlapping.

**Which issue(s) does this PR fix?**:

Fixes #71220 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/core/components/OptionsUI/slider.tsx [hunk 1]
```diff
@@ -131,7 +131,7 @@ function getTextWidth(text: string, font: string): number | null {
 const getStylesSlider = (theme: GrafanaTheme2, width: number) => {
   return {
     numberInputWrapper: css`
-      margin-left: 10px;
+      margin-left: 24px;
```
Comment (JoaoSilvaGrafana) [inline public/app/core/components/OptionsUI/slider.tsx:134]:
```suggestion
      margin-left: ${theme.spacing(3)};
```

Better to use the theme directly here for the spacing!

Comment (Develer) [reply public/app/core/components/OptionsUI/slider.tsx:134]: Thanks for the suggestion, let me quickly check!

**Review by JoaoSilvaGrafana — APPROVED** [review]
Nice 👍
