### PR TITLE
Dashboards: Resolve display names by identity in version history

### LINKED ISSUE #119219: Dashboard version history shows incorrect "Updated By" user names
### What happened?

The "Updated By" column in dashboard version history (Settings > Versions) displays incorrect user names. When multiple users have edited a dashboard, the names appear swapped or shuffled across versions.

For example, if User A created versions 1-12 and User B saves version 13, the UI shows User B's name on versions 1-12 and User A's name on version 13.

The underlying data is correct -- the `grafana.app/updatedBy` annotations on each version have the right identity keys. The bug is in the frontend display name resolution.

### What did you expect to happen?

Each version should display the name of the user who actually saved that version.

### How do we reproduce it?

1. As User A, create a dashboard and save a few versions
2. As User B (a different user with a higher database ID), save a new version
3. Open Settings > Versions
4. Observe that the "Updated By" names are swapped between versions

This also reproduces when using a service account token to update a dashboard via the API.

### Root cause

`VersionsEditView.tsx` resolves user identity keys to display names via the IAM display API (`GET /display`). The response contains:

- `keys`: user identity keys in **request order**
- `display`: resolved display items ordered by **database ID ascending** (`ORDER BY u.id asc`)

The code assumes these arrays are aligned by index, but they are not. The Go type definition documents this:

```go
// Matching items (the caller may need to remap from keys to results)
Items []Display `json:"display"`
```

### Grafana version

Affects any version using the dashboard-scene version history with the IAM display API for user name resolution.

### Datasource

_No response_

### OS / Environment

_No response_

### PR DESCRIPTION
**Pull request by ivanortegaalba**
Fixes #119219

*Problem*

The "Updated By" column in the dashboard version history page shows wrong user names when multiple users have edited a dashboard. The names appear swapped or shuffled across versions. This affects both UI-saved and API-saved dashboards.

The frontend resolves user identity keys to display names via the IAM display API (`/display`). The response contains `keys` (in request order) and `display` (ordered by `u.id ASC` in the database). The code used an index-based lookup between these two misaligned arrays, mapping the wrong display name to the wrong user key.

*Solution*

Replace the index-based array lookup with an identity-based `Map` using each display item's `identity` field (`type:name`). Also add an `internalId` fallback for legacy numeric keys.

*How to test*

1. Create a dashboard and save a few versions as User A
2. Log in as User B (with a different/higher DB ID) and save a new version
3. Open Settings > Versions -- each version should show the correct user name

### CODE REVIEW

File: public/app/features/dashboard-scene/settings/VersionsEditView.tsx [hunk 1]
```diff
@@ -197,14 +197,19 @@ function VersionsEditorSettingsListView({ model }: SceneComponentProps<VersionsE
...
+    for (const item of displayData.display) {
+      displayMap.set(`${item.identity.type}:${item.identity.name}`, item.displayName);
+      if (item.internalId) {
+        displayMap.set(String(item.internalId), item.displayName);
+      }
+    }
     return model.versions.map((version) => {
-      const idx = version.createdBy ? displayData.keys.indexOf(version.createdBy) : -1;
-      const displayName = idx >= 0 ? displayData.display[idx]?.displayName : undefined;
+      const displayName = version.createdBy ? displayMap.get(version.createdBy) : undefined;
```
Comment (dprokop) [inline public/app/features/dashboard-scene/settings/VersionsEditView.tsx:218]: how does `displayMap.get(version.createdBy) ` relate to `displayMap.set(`${item.identity.type}:${item.identity.name}`, item.displayName);` ?

Comment (ivanortegaalba) [reply public/app/features/dashboard-scene/settings/VersionsEditView.tsx:218]: the annotation stores the identity as a single string "user:fdjvnb8elz1mob", and the display item from the IAM API returns it split into { type: "user", name: "fdjvnb8elz1mob" }. We join them back with : to create a matching key.

**Comment by bfmatei** [comment]
There's a problem: the initial version of the dashboard doesn't have an "updated by".

**Comment by ivanortegaalba** [comment]
> There's a problem: the initial version of the dashboard doesn't have an "updated by".

Oh! Let me check! I was testing with an existing dashboard

File: public/app/features/dashboard-scene/settings/VersionsEditView.tsx [hunk 2]
```diff
@@ -127,7 +133,7 @@ export class VersionsEditView extends SceneObjectBase<VersionsEditViewState> imp
           item.metadata.annotations?.[AnnoKeyUpdatedTimestamp] ??
           item.metadata.creationTimestamp ??
           new Date().toISOString(),
-        createdBy: item.metadata.annotations?.[AnnoKeyUpdatedBy] ?? '',
+        createdBy: item.metadata.annotations?.[AnnoKeyUpdatedBy] ?? item.metadata.annotations?.[AnnoKeyCreatedBy] ?? '',
```
Comment (ivanortegaalba) [inline public/app/features/dashboard-scene/settings/VersionsEditView.tsx:136]: @bfmatei good catch! This solved the issue! Sorry, I forced push

**Review by dprokop — APPROVED** [review]
Looks good

File: public/app/features/dashboard-scene/settings/VersionsEditView.tsx (hunk 2 above)
Comment (ivanortegaalba) [reply public/app/features/dashboard-scene/settings/VersionsEditView.tsx:136]: I'm adding a test case for this too :)

**Comment by ghost** [comment]
The backport to `release-12.3.5` failed:

```
error cherry-picking: error running git cherry-pick: error running command 'git cherry-pick -x 1e2b2c0eb5f64c06d6c5a7f19d79bee937442585'
error: exit status 1
stdout: Auto-merging public/app/features/dashboard-scene/settings/VersionsEditView.test.tsx
CONFLICT (content): Merge conflict in public/app/features/dashboard-scene/settings/VersionsEditView.test.tsx
Auto-merging public/app/features/dashboard-scene/settings/VersionsEditView.tsx
CONFLICT (content): Merge conflict in public/app/features/dashboard-scene/settings/VersionsEditView.tsx

stderr: error: could not apply 1e2b2c0eb5f... Dashboards: Resolve display names by identity in version history (#119220)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"

```

To backport manually, run these commands in your terminal:

```bash
git fetch
git switch --create backport-119220-to-release-12.3.5 origin/release-12.3.5
git cherry-pick -x 1e2b2c0eb5f64c06d6c5a7f19d79bee937442585
```

Resolve the conflicts, then add the changes and run `git cherry-pick --continue`:

```bash
git add . && git cherry-pick --continue
```

If you have the [GitHub CLI](https://cli.github.com/) installed:

```bash
git push --set-upstream origin backport-119220-to-release-12.3.5
PR_BODY=$(gh pr view 119220 --json body --template 'Backport 1e2b2c0eb5f64c06d6c5a7f19d79bee937442585 from #119220{{ "\n\n---\n\n" }}{{ index . "body" }}')
echo "${PR_BODY}" | gh pr create --title '[release-12.3.5] Dashboards: Resolve display names by identity in version history' --body-file - --label 'backport' --label '' --label 'area/frontend' --label 'add to changelog' --base release-12.3.5 --web
```

Or, if you don't have the GitHub CLI installed ([we recommend you install it!](https://github.com/cli/cli#installation)):

```bash
git push --set-upstream origin backport-119220-to-release-12.3.5
```

And open a pull request where the `base` branch is `release-12.3.5` and the `compare`/`head` branch is `backport-119220-to-release-12.3.5`
