### PR TITLE
Dashboard: Fix restore erroring  with API version mismatch

### LINKED ISSUE #122532: Restore dashboards: fails with API version mismatch on upgraded instances
Restoring a deleted dashboard from "Recently deleted" fails with:

> the API version in the data (dashboard.grafana.app/v1beta1) does not match the expected API version (dashboard.grafana.app/v1)

Affects instances upgraded through v1beta1 -> v1 (13.0.0+).

### Root cause

`restoreDashboard()` in `v1.ts` and `v2.ts` posts the resource body without updating the `apiVersion` field. Trashed resources retain their original stored `apiVersion` (e.g. `v1beta1`), but `ScopedResourceClient` sends the request to the resolved `/v1/` endpoint. The K8s API server rejects the mismatch with 400.

Additionally, `unified.ts` hardcodes `'v1beta1'` for the deleted dashboards search URL (currently dead code, but wrong).

### PR DESCRIPTION
**Pull request by kristinademeshchik**
**What is this feature?**

Fixes the `restoreDashboard` method in both v1 and v2 dashboard api clients to construct a clean create payload with only `metadata` and `spec`, letting the API server infer `apiVersion` and `kind` 

Fixes https://github.com/grafana/grafana/issues/122532

### CODE REVIEW

File: public/app/features/dashboard/api/v2.ts [hunk 1]
```diff
@@ -254,11 +254,16 @@ export class K8sDashboardV2API
...
+    return this.client.create({
+      metadata: {
+        ...dashboard.metadata,
+        resourceVersion: '',
+        annotations: {
+          ...dashboard.metadata.annotations,
+          [AnnoKeyGrantPermissions]: 'default',
+        },
+      },
+      spec: dashboard.spec,
```
Comment (Clarity-89) [inline public/app/features/dashboard/api/v2.ts]: Maybe extract this logic into a function to be reused for both api versions? If new fields are added, the changes will be in one place.

**Review by Clarity-89 — APPROVED** [review]
