### PR TITLE
Graphite: Fix date mutation

### LINKED ISSUE #107413: Graphite mutating date objects
Graphite is mutating the date object provided to it via queries. This is invalid and can lead to various issues.

### PR DESCRIPTION
**Pull request by aangelisc**
Data sources should not mutate the date object. If modifications need to be made when requesting data from the underlying data source, the date object should be cloned.

Fixes #107413

### CODE REVIEW

File: public/app/plugins/datasource/graphite/datasource.ts [hunk 1]
```diff
@@ -510,24 +514,33 @@ export class GraphiteDatasource
         date = date.replace('M', 'mon');
         return date;
       }
-      date = dateMath.parse(date, roundUp, timezone);
+      const parsedDate = dateMath.toDateTime(date, { roundUp, timezone });
+
+      // If the date is invalid return the original string
+      if (!parsedDate) {
```
Comment (adamyeats) [inline public/app/plugins/datasource/graphite/datasource.ts]: What scenarios lead to `parsedDate` being invalid? Could the comment here clarify this further?

File: public/app/plugins/datasource/graphite/datasource.ts [hunk 2]
```diff
@@ -500,7 +502,9 @@ export class GraphiteDatasource
     return this.templateSrv.containsTemplate(target.target ?? '');
   }
 
-  translateTime(date: any, roundUp?: boolean, timezone?: TimeZone) {
+  translateTime(date: DateTime | string, roundUp?: boolean, timezone?: TimeZone) {
+    let dateCopy: Moment;
```
Comment (adamyeats) [inline public/app/plugins/datasource/graphite/datasource.ts]: Mutation of `let`. IMO, it would be preferable to have a function that returned `Moment` with this logic encapsulated inside of it.

**Review by adamyeats — COMMENTED** [review]
LGTM, couple of nits 👍

File: public/app/plugins/datasource/graphite/datasource.ts (hunk 2 above)
Comment (aangelisc) [reply public/app/plugins/datasource/graphite/datasource.ts]: Fixed

File: public/app/plugins/datasource/graphite/datasource.ts (hunk 1 above)
Comment (aangelisc) [reply public/app/plugins/datasource/graphite/datasource.ts]: Added a test and clarified the comment

File: public/app/plugins/datasource/graphite/datasource.ts [hunk 3]
```diff
@@ -500,34 +502,52 @@ export class GraphiteDatasource
...
+  translateTime(date: DateTime | string, roundUp?: boolean, timezone?: TimeZone) {
+    const parseDate = () => {
+      if (isString(date)) {
+        if (date === 'now') {
+          return 'now';
+        } else if (date.indexOf('now-') >= 0 && date.indexOf('/') === -1) {
+          date = date.substring(3);
+          date = date.replace('m', 'min');
+          date = date.replace('M', 'mon');
+          return date;
```
Comment (adamyeats) [inline public/app/plugins/datasource/graphite/datasource.ts]:
```suggestion
          return date.substring(3).replace('m', 'min').replace('M', 'mon');
```

Can be shortened to this, and avoids mutating the `date` argument.

**Review by adamyeats — APPROVED** [review]

File: public/app/plugins/datasource/graphite/datasource.ts (hunk 3 above)
Comment (aangelisc) [reply public/app/plugins/datasource/graphite/datasource.ts]: Have updated and added a test for this case. Thankfully this never would've caught us out as strings are immutable in JS 😄

Comment (adamyeats) [reply public/app/plugins/datasource/graphite/datasource.ts]: It's true that strings are immutable in JavaScript, but reassigning a function argument like this can still make the code a bit harder to follow. This change was mostly about making the intent clearer, not addressing a technical issue.
