### PR TITLE
TimeSeries: always enforceSort

### LINKED ISSUE #47795: Tooltips don't display for most datapoints on graph and timeseries visualization
**What happened**:

Tooltips don't display for most datapoints on graph and timeseries visualization. I've also seen a related issue where the plot doesn't display at all. See gifs below for both issues.

GrafanaTooltips

GrafanaPlot

**What you expected to happen**:

Tooltip would show for every datapoints and plot would show.

**How to reproduce it (as minimally and precisely as possible)**:

Apply timeseries data to either of the above-mentioned visualizations and attempt to hover datapoints.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.5 ([Fork](https://github.com/ni/grafana))
- Data source type & version: [Custom datasource](https://github.com/ni/systemlink-notebook-datasource)
- OS Grafana is installed on: [Alpine 3.15](https://github.com/ni/grafana/blob/main/Dockerfile#L1)
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins: Above-mentioned datasource
- Others: N/A

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/grafana/issues/47795

most data is already sorted and the check is cheap, so Just Do It (tm)

### CODE REVIEW

File: public/app/plugins/panel/barchart/utils.ts [hunk 1]
```diff
@@ -301,7 +301,7 @@ export function prepareBarChartDisplayValues(
   }
 
   // Bar chart requires a single frame
-  const frame = series.length === 1 ? series[0] : outerJoinDataFrames({ frames: series, enforceSort: false });
```
Comment (leeoniya) [inline public/app/plugins/panel/barchart/utils.ts:304]: this is now handled automagically by skipping sorting of string fields. (we still want to sort BarCharts by time x)

Comment (ryantxu) [reply public/app/plugins/panel/barchart/utils.ts:304]: barchart... I don't think so.  candlestick maybe

**Review by ryantxu — APPROVED** [review]
LGTM
