### PR TITLE
Dashboard: Fix so default data source is selected when data source can't be found in panel editor

### LINKED ISSUE #24336: PanelEditor: all options will be empty when datasource can't be found.
**Why do we need this:**
After importing a dashboard from play.grafana.com and the datasource isn't available locally you will get stuck in the following scenario in the new panel edit.

Skärmavbild 2020-05-06 kl  14 14 10

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
If you, for example is importing or inserting a dashboard and the datasource in the target dashboard doesn't exist locally. You can now change this one in the panel edit mode.

**Which issue(s) this PR fixes**:
Fixes #24336

**Special notes for your reviewer**:
Not super happy that we are doing the fallback handling in both the QueryRow and the QueryTab. Would be nice to do some refactorings to prevent this.

### CODE REVIEW

File: public/app/features/dashboard/panel_editor/QueriesTab.tsx [hunk 1]
```diff
@@ -74,8 +75,14 @@ export class QueriesTab extends PureComponent<Props, State> {
       next: (data: PanelData) => this.onPanelDataUpdate(data),
     });
 
-    const ds = await getDataSourceSrv().get(panel.datasource);
-    this.setState({ dataSource: ds });
+    try {
+      const ds = await getDataSourceSrv().get(panel.datasource);
+      this.setState({ dataSource: ds });
```
Comment (tskarhed) [inline public/app/features/dashboard/panel_editor/QueriesTab.tsx:80]: Is a dataSourceItem already set for the default case?

**Review by tskarhed — APPROVED** [review]
Failing gracefully! :tada: 
Screenshot from 2020-05-11 16-45-15

File: public/app/features/dashboard/panel_editor/QueriesTab.tsx (hunk 1 above)
Comment (mckn) [reply public/app/features/dashboard/panel_editor/QueriesTab.tsx:80]: yes, it is set in the initial state. Great question!

**Review by torkelo — APPROVED** [review]
Looks great! Awesome job!
