### PR TITLE
Proxy: Improve header handling for reverse proxy

### LINKED ISSUE #64486: Dashboard import responses HSTS header even when disabled in configuration
**What happened**:

The configuration `security.strict_transport_security` is disabled, most of the responses do not provide `Strict-Transport-Security` header.

normal without hsts

But when we import a dashboard through id, the response replies with a HSTS header

- Request: `https://my-grafana-server:3000/api/gnet/dashboards/1`
- Response Header: `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`

with hsts

> Server name `my-grafana-server` and dashboard id `2` are placeholders

**What you expected to happen**:

When HSTS is disabled in configuration, no responses should provide HSTS header, since it is a one way configuration and you will have to wait until it expired, or remove it manually in `chrome://net-internals/#hsts`

**How to reproduce it (as minimally and precisely as possible)**:

On Grafana with configuration `security.strict_transport_security` unset or set to false, import a dashboard through id

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.4.3
- Data source type & version: Prometheus v2.42.0
- OS Grafana is installed on: Docker CE 23.0.1 on Ubuntu 22.04 LTS
- User OS & Browser: Microsoft Windows 10 22H2, Chrome 110.0.5481.180

### PR DESCRIPTION
**Pull request by sakjur**
**What is this feature?**

Remove more headers from the reverse proxy that risks confusing a client.

**Who is this feature for?**

Users of Grafana as a proxy (most users).

**Which issue(s) does this PR fix?**:

Fixes #64486

**Special notes for your reviewer:**

I'm unsure about backporting this to v9.5 or holding it off until v10.0. Let me know what you think.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/util/proxyutil/reverse_proxy.go [hunk 1]
```diff
@@ -79,11 +79,37 @@ func wrapDirector(d func(*http.Request)) func(req *http.Request) {
...
 }
 
+// deletedHeaders lists a number of headers that we don't want to
+// pass-through from the upstream when using a reverse proxy.
+//
+// These are related to the connection between Grafana and the proxy
+// or instructions that would alter how a browser will interact with
+// future requests to Grafana (such as enabling Strict Transport
+// Security)
+var deletedHeaders = []string{
```
Comment (marefr) [inline pkg/util/proxyutil/reverse_proxy.go:89]: Some of these already deleted by `httputil.ReverseProxy`, see https://github.com/golang/go/blob/ada0eec8277449ecd6383c86bc2e5fe7e7058fc7/src/net/http/httputil/reverseproxy.go#L294-L304

We've basically copied this for the call resource handling since it behaves like an HTTP proxy as well: 
https://github.com/grafana/grafana/blob/9599e8003b3476dbc6629d43b60e5c9eeee45b85/pkg/plugins/manager/client/client.go#L276-L294

Comment (sakjur) [reply pkg/util/proxyutil/reverse_proxy.go:89]: Ah, I can remove the duplicates then :+1: It's really the STS that's been reported as a problem, but I noticed we copied over Server as well and added the ones that seemed reasonable and safe to me, good to know some of them are already handled.

Comment (andresmgot) [reply pkg/util/proxyutil/reverse_proxy.go:89]: Q: Should we have just one list of headers and use it in the different places? Is there a case in which we should forward some header for a request but not for other?

Comment (marefr) [reply pkg/util/proxyutil/reverse_proxy.go:89]: Probably yes, but maybe not now. Me and @wbrowne have discussed unifying plugin/datasource proxy and call resource handling by refactoring/moving plugin/datasource proxy into plugin management. Then having a common handling of all this logic make more sense. Probably needs some more discussions/thoughts though.

Comment (sakjur) [reply pkg/util/proxyutil/reverse_proxy.go:89]: Updated to remove the extraneous headers in 37e5bac.

**Review by marefr — APPROVED** [review]
LGTM with a comment

File: pkg/util/proxyutil/proxyutil.go [hunk 2]
```diff
@@ -75,6 +77,16 @@ func SetProxyResponseHeaders(header http.Header) {
 	header.Set("Content-Security-Policy", "sandbox")
 }
 
+// SetViaHeader adds Grafana's reverse proxy to the proxy chain.
+// Defined in RFC 9110 7.6.3 https://datatracker.ietf.org/doc/html/rfc9110#name-via
+func SetViaHeader(header http.Header, major, minor int) {
+	via := fmt.Sprintf("%d.%d %s grafana", major, minor, setting.InstanceName)
```
[the remark this answers is not in the document]
Comment (sakjur) [reply pkg/util/proxyutil/proxyutil.go:83]: Looking at this again, I think it's safer to just set grafana for now and maybe in the future extend this with an optional hostname value :+1:

I'll change this!
