### PR TITLE
Cloudwatch: Fix parsing for ec2 resource attributes

### LINKED ISSUE #96489: CloudWatch: Resource handler for ec2 instance attributes doesn't parse correctly
Currently, the ec2 instance attribute resource handler only supports parsing string and time fields and fails if any of the instances do not have the field in question. Some of [the fields](https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/template-variables/#use-ec2_instance_attribute) return bool and int values, and we should parse those correctly.

Reported in https://github.com/grafana/support-escalations/issues/13459

### PR DESCRIPTION
**Pull request by iwysiu**
**What is this feature?**
Fixes parsing for ec2 instance attribute resource requests for nil, bool, and int values. Now we handle all the fields listed in the [docs](https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/template-variables/#use-ec2_instance_attribute), with the exception of `IamInstanceProfile` where they will need to query `IamInstanceProfile.Arn` or `IamInstanceProfile.Name` depending on which part they want.
This is a quicker fix because its a support escalation. In the long term I think we could refactor this- as the user points out, we could do a dropdown with known attribute fields and let users set custom fields for the other values. Also we don't need to be doing reflection for the known fields of `ec2.Instance`- we already know what types they are. Though we should cross reference this with the v2 sdk to make sure we're not doing work that will immediately be obselete

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #96489

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: pkg/tsdb/cloudwatch/metric_find_query.go [hunk 1]
```diff
@@ -111,6 +112,9 @@ func (e *cloudWatchExecutor) handleGetEc2InstanceAttribute(ctx context.Context,
 				v := reflect.ValueOf(instance)
 				for _, key := range attributePath {
 					if v.Kind() == reflect.Ptr {
+						if v.IsNil() {
+							continue instanceLoop
+						}
```
Comment (njvrzm) [inline pkg/tsdb/cloudwatch/metric_find_query.go:117]: Purely optional, but _if_ you wanted to avoid the outer loop (they always feel a bit dirty to me despite being perfectly legitimate) you could extract the contents of this `else` block into a function looking something like

```go
func getInstanceAttributeValue(attributeName string, instance *ec2.Instance) (value string, found bool, err error) {
...
}
```

But like I said, not necessary by any means.

**Review by njvrzm — APPROVED** [review]
Looks good! One purely optional comment.
