### PR TITLE
Plugins: Remove uninstall plugin step from cli plugins update-all

### LINKED ISSUE #101493: grafana cli: loosing plugins on update
### What happened?

When running `grafana cli plugins update-all` etc. grafana removes the related plugin before it has downloaded the new version successfully. So if e.g. a firewall blocks access to the related repo, one will loose the plugin!

E.g.:
```
> grafana  cli plugins ls
installed plugins:
briangann-gauge-panel @ 0.0.8

> grafana cli plugins update-all
Updating briangann-gauge-panel 
Removing plugin: briangann-gauge-panel
Error: ✗ failed to download plugin archive: Get "https://storage.googleapis.com/plugins-community/briangann-gauge-panel/release/2.0.1/briangann-gauge-panel-2.0.1.zip": dial tcp 172.217.16.91:443: connect: connection refused
> grafana cli  plugins ls
no installed plugins found
```

### What did you expect to happen?

On update grafana should download the new plugin first, and only on success it should remove the old and install the new one.

NOTE: Since storage.googleapis.com changes its IP every 5 min to 4 random IPs out of a set of several hundreds, it is very likely, that plugin updates will fail.

### Did this work before?

unknown

### How do we reproduce it?

1. allow outgoing connections to `grafana.com`, only.
2. run `grafana cli plugins update-all`

### Is the bug inside a dashboard panel?

discovered in CLI, but might be there, too.

### Environment (with versions)?

Grafana: 9.5.21
OS: Ubuntu 20.04.6 LTS
Browser: dna

### Grafana platform?

A downloaded binary

### Datasource(s)?

no

### PR DESCRIPTION
**Pull request by oshirohugo**
**What is this feature?**

This PR removes uninstall plugin step from `cli plugins update-all` command. The removal is already done if the installation itself, therefore uninstalling the plugin before the installation is unnecessary and can cause issues.

**Why do we need this feature?**

Before this feature, we could loose a plugin if the installation of a new version failed, since the plugin removal was happening before the new version installation.

**Who is this feature for?**

Grafana cli users.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/101493

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by andresmgot — COMMENTED** [review]
I wonder if we need to uninstall at all, if I am correct, when upgrading a plugin through the API or with `preinstall`, we call `pluginInstaller.Add`, which [doesn't uninstall the plugin, it simply overwrites the new one on top of the existing one](https://github.com/grafana/grafana/blob/main/pkg/plugins/manager/installer.go#L54).

It seems that we have some inconsistency in behavior here between the CLI and the service so thoughts?

**Comment by oshirohugo** [comment]
@andresmgot you are right. Before making this solution, I tested removing the uninstall step and everything worked just fine. I thought that the uninstall was there just to guarantee a "clean install" and avoid issues.

**Comment by andresmgot** [comment]
@wbrowne may have an opinion here, I am not sure how safe is to just overwrite plugins. 

> I thought that the uninstall was there just to guarantee a "clean install" and avoid issues.

I guess it may cause inconsistencies when a plugin changes other plugin dependencies or have different files but we haven't had issues with that so far.

**Comment by wbrowne** [comment]
I actually have found issues before with just overwriting plugins as new files can be introduced as you say Andres, thus breaking the signing. We do purge the pre-existing folder already, but [further down than you expect](https://github.com/grafana/grafana/blob/main/pkg/plugins/storage/fs.go#L74). This would still be problematic in case the plugin folder name happens to be different, but we haven't hit that yet 😅

**Comment by andresmgot** [comment]
> We do purge the pre-existing folder already, but [further down than you expect](https://github.com/grafana/grafana/blob/main/pkg/plugins/storage/fs.go#L74)

Oh, so `extractFiles` does more than just extracting 💀.  So the good thing is that you can just remove the call to `uninstallPlugin` here @oshirohugo since it will be uninstalled anyway when extracting the new archive. That will also fix https://github.com/grafana/grafana/issues/101493 since it won't be uninstalled if the download fails.

**Comment by wbrowne** [comment]
Yeah it's a bit of a mess - it might be a good idea to relook at how we do this in the future. But yeah I think removing that call to uninstall may be all that's needed here.

File: pkg/plugins/ifaces.go [hunk 1]
```diff
@@ -77,7 +77,6 @@ type FS interface {
 type FSRemover interface {
 	Remove() error
 }
-
```
Comment (andresmgot) [inline pkg/plugins/ifaces.go:80]: missing a new line here now :)

**Review by andresmgot — APPROVED** [review]
LGTM
