### PR TITLE
CloudWatch: Fix high CPU load

### LINKED ISSUE #20578: CloudWatch: High CPU load
**What happened**:
Grafana gets unresponsive from time and time and sort of hangs, requests times out and takes really long time. 

**What you expected to happen**:
Grafana should always be responsive. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure a CloudWatch datasource with Auth Provider=Access & secret key.
2. Make a lot of requests and possibly using queries which expands to multiple queries

**Anything else we need to know?**
pprof profiling showed that most av the CPU time was spent in `SecureJsonData.Decrypt` and CloudWatch responsible for calling it a lot :
```
(pprof) top -cum
Showing nodes accounting for 3.11s, 7.86% of 39.59s total
Dropped 720 nodes (cum <= 0.20s)
Showing top 10 nodes out of 162
      flat  flat%   sum%        cum   cum%
         0     0%     0%     30.22s 76.33%  github.com/grafana/grafana/pkg/util.Decrypt
     1.19s  3.01%  3.01%     30.17s 76.21%  github.com/grafana/grafana/pkg/util.PBKDF2
         0     0%  3.01%     30.17s 76.21%  github.com/grafana/grafana/pkg/util.encryptionKeyToBytes
         0     0%  3.01%     28.44s 71.84%  github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1
     1.92s  4.85%  7.86%     26.85s 67.82%  crypto/sha256.(*digest).Write
         0     0%  7.86%     25.56s 64.56%  github.com/grafana/grafana/pkg/tsdb/cloudwatch.(*CloudWatchExecutor).executeQuery
         0     0%  7.86%     25.56s 64.56%  github.com/grafana/grafana/pkg/tsdb/cloudwatch.(*CloudWatchExecutor).executeTimeSeriesQuery.func1
         0     0%  7.86%     25.15s 63.53%  github.com/grafana/grafana/pkg/tsdb/cloudwatch.(*CloudWatchExecutor).getClient
         0     0%  7.86%     25.04s 63.25%  github.com/grafana/grafana/pkg/components/securejsondata.SecureJsonData.Decrypt
         0     0%  7.86%     25.04s 63.25%  github.com/grafana/grafana/pkg/tsdb/cloudwatch.(*CloudWatchExecutor).getDsInfo
```

Digging in to this identified the following code calling `SecureJsonData.Decrypt`:a lot:
https://github.com/grafana/grafana/blob/ede3adc7d469c23fd923905dff869822aaebcd36/pkg/tsdb/cloudwatch/credentials.go#L152-L159

**Environment**:
- Grafana version: 6.3.5
- Data source type & version: CloudWatch
- OS Grafana is installed on: Docker

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
At first, did some investigations and started with comparing if there may be any difference in looping over decryped map vs picking one specific key in the map. Wrote a benchmark to verify:

<details><summary>securejsondata_test.go</summary>

```go
package securejsondata

import (
	"testing"
)

func BenchmarkDecrypt(b *testing.B) {
	b.Run("Key by key", func(b *testing.B) {
		for n := 0; n < b.N; n++ {
			sd := SecureJsonData{
				"accessKey": []byte("dTBzSXNKU0u950cXPsFoR4Ch1pMr2vAxYRFdR2u6kL1+DRb5zydBUXi21M8="),
				"secretKey": []byte("TUg5eXJPZHba++7W1fzpuFmyYqkFUSgMYq/fCArndW4edXS/Tvt4rbudXRjDvUBS+ThfpSUhNXMKUhClZzM0Aw=="),
			}
			DecryptValuesBy(sd)
		}
	})

	b.Run("In loop", func(b *testing.B) {
		for n := 0; n < b.N; n++ {
			sd := SecureJsonData{
				"accessKey": []byte("dTBzSXNKU0u950cXPsFoR4Ch1pMr2vAxYRFdR2u6kL1+DRb5zydBUXi21M8="),
				"secretKey": []byte("TUg5eXJPZHba++7W1fzpuFmyYqkFUSgMYq/fCArndW4edXS/Tvt4rbudXRjDvUBS+ThfpSUhNXMKUhClZzM0Aw=="),
			}
			DecryptValuesInLoop(sd)
		}
	})
}

func DecryptValuesInLoop(sd SecureJsonData) (string, string) {
	accessKey := ""
	secretKey := ""
	for key, value := range sd.Decrypt() {
		if key == "accessKey" {
			accessKey = value
		}
		if key == "secretKey" {
			secretKey = value
		}
	}

	return accessKey, secretKey
}

func DecryptValuesBy(sd SecureJsonData) (string, string) {
	accessKey, _ := sd.DecryptedValue("accessKey")
	secretKey, _ := sd.DecryptedValue("secretKey")

	return accessKey, secretKey
}
```
</details>

Ran it for 60s, but didn't show any difference:
```
> go test ./pkg/components/securejsondata/... -bench=BenchmarkDecrypt -benchtime=60s -benchmem                                                                                                
goos: linux                                                                                                                                                                                   
goarch: amd64                                                                                                                                                                                 
pkg: github.com/grafana/grafana/pkg/components/securejsondata                                                                                                                                 
BenchmarkDecrypt/Key_by_key-4               4005          18787486 ns/op            2880 B/op         38 allocs/op                                                                            
BenchmarkDecrypt/In_loop-4                  3520          18789649 ns/op            3216 B/op         40 allocs/op
PASS
ok      github.com/grafana/grafana/pkg/components/securejsondata        145.271s
```

Based on above benchmark I reasoned that we probably need to cache the decrypted values so that's what the current changes are doing.  

This could be a problem for other data sources than CloudWatch as well. 

**Which issue(s) this PR fixes**:
Fixes #20578

### CODE REVIEW

File: pkg/models/datasource_cache.go [hunk 1]
```diff
@@ -162,3 +162,43 @@ func (ds *DataSource) getCustomHeaders() map[string]string {
...
+var dsDecryptionCache = secureJSONDecryptionCache{
+	cache: make(map[int64]cachedDecryptedJSON),
+}
+
+// DecryptedValues returns cached decrypted values from secureJsonData.
+//
+// Caches decrypted values.
+func (ds *DataSource) DecryptedValues() map[string]string {
+	ptc.Lock()
+	defer ptc.Unlock()
```
Comment (marefr) [inline pkg/models/datasource_cache.go]: this should be using `dsDecryptionCache` instead of `ptc` :man_facepalming:

File: pkg/tsdb/cloudwatch/credentials.go [hunk 2]
```diff
@@ -149,16 +149,8 @@ func (e *CloudWatchExecutor) getDsInfo(region string) *DatasourceInfo {
...
-	secretKey := ""
-	for key, value := range e.DataSource.SecureJsonData.Decrypt() {
-		if key == "accessKey" {
-			accessKey = value
-		}
-		if key == "secretKey" {
-			secretKey = value
-		}
-	}
+	accessKey, _ := e.DataSource.DecryptedValue("accessKey")
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/credentials.go]: I think it would be more efficient to get the decrypted map just once.

**Review by aknuds1 — CHANGES_REQUESTED** [review]
There's a change I think we should make.

File: pkg/api/pluginproxy/ds_proxy_test.go [hunk 3]
```diff
@@ -527,6 +527,72 @@ func TestDSRouteRule(t *testing.T) {
 					"important_cookie=important_value")
 			})
 		})
+
+		Convey("When datasource hasn't been updated, encrypted JSON should be fetched from cache", func() {
```
Comment (marefr) [inline pkg/api/pluginproxy/ds_proxy_test.go]: Not sure it makes sense to test the caching of decrypted data here. Should have tests in datasource_cache_test.go

**Review by marefr — COMMENTED** [review]
Cannot request changes since I opened the PR, but see comment.

File: pkg/tsdb/cloudwatch/credentials.go (hunk 2 above)
Comment (marefr) [reply pkg/tsdb/cloudwatch/credentials.go]: Yeah it's probably a good idea to avoid unnecessary locking :+1:

**Review by aknuds1 — APPROVED** [review]
LGTM

File: pkg/models/datasource_cache_test.go [hunk 4]
```diff
@@ -236,7 +237,62 @@ func TestDataSourceCache(t *testing.T) {
 	})
 }
 
-func clearCache() {
+func TestDataSourceDecryptionCache(t *testing.T) {
+	Convey("When datasource hasn't been updated, encrypted JSON should be fetched from cache", t, func() {
+		ClearDSDecryptionCache()
+
+		ds := DataSource{
+			Type:     DS_INFLUXDB_08,
```
Comment (marefr) [inline pkg/models/datasource_cache_test.go]: Specify an id

File: pkg/models/datasource_cache_test.go [hunk 5]
```diff
@@ -236,7 +237,62 @@ func TestDataSourceCache(t *testing.T) {
...
+
+		password, ok = ds.DecryptedValue("password")
+		So(password, ShouldEqual, "password")
+		So(ok, ShouldBeTrue)
+	})
+
+	Convey("When datasource is updated, encrypted JSON should not be fetched from cache", t, func() {
+		ClearDSDecryptionCache()
+
+		ds := DataSource{
```
Comment (marefr) [inline pkg/models/datasource_cache_test.go]: Specify an id

**Review by marefr — COMMENTED** [review]
Looks good, Some minor fixes left.

File: pkg/tsdb/cloudwatch/credentials.go [hunk 6]
```diff
@@ -149,16 +149,9 @@ func (e *CloudWatchExecutor) getDsInfo(region string) *DatasourceInfo {
...
-		if key == "accessKey" {
-			accessKey = value
-		}
-		if key == "secretKey" {
-			secretKey = value
-		}
-	}
+	decrypted := e.DataSource.DecryptedValues()
+	accessKey := decrypted["accessKey"]
+	secretKey := decrypted["secretKey"]
```
Comment (DanCech) [inline pkg/tsdb/cloudwatch/credentials.go]: This should have a fallback in case they keys aren't present shouldn't it? Might make sense for DecryptedValue to just replace decryptedValue and match its signature.

Comment (marefr) [reply pkg/tsdb/cloudwatch/credentials.go]: @DanCech no they shouldn't have a fallback - didn't have that before. Or what am I missing here?

Comment (DanCech) [reply pkg/tsdb/cloudwatch/credentials.go]: What happens if those keys aren't present?

Comment (marefr) [reply pkg/tsdb/cloudwatch/credentials.go]: Okay, guess it makes sense. @aknuds1 can you change this to something like this (as before)
```go 
accessKey := ""
secretKey := ""
if value, exists := decrypted["accessKey"]; exists {
  accessKey = value
}
if value, exists := decrypted["secretKey"]; exists {
  secretKey = value
}
```

Comment (DanCech) [reply pkg/tsdb/cloudwatch/credentials.go]: @marefr this is an api we'll use in every datasource, why not just make decryptedValue public and use those semantics instead of this mess?

Comment (aknuds1) [reply pkg/tsdb/cloudwatch/credentials.go]: As discussed in Slack, making the following change doesn't have any practical effect, since the default when looking up a string in a map is the empty string:

```
accessKey := ""
secretKey := ""
if value, exists := decrypted["accessKey"]; exists {
  accessKey = value
}
if value, exists := decrypted["secretKey"]; exists {
  secretKey = value
}
```

Comment (marefr) [reply pkg/tsdb/cloudwatch/credentials.go]: @DanCech have a look at the comment here https://github.com/grafana/grafana/pull/20579#discussion_r349529035 we now uses `DecryptedValues()` to optimize for not have to lock the cache 2 times and instead 1 time.

Comment (DanCech) [reply pkg/tsdb/cloudwatch/credentials.go]: I'd forgotten about the map semantics, haven't written enough go lately :(  Let's get this out the door!
