### PR TITLE
Metrics: fix `grafana_database_conn_*` metrics, and add new `go_sql_stats_*` metrics as eventual replacement

### LINKED ISSUE #54242: metrics: Some grafana_database_conn_* metrics are incorrect
**What happened**:

The `grafana_database_conn_max_idle_closed_total` metric, for example, is intended to expose the value of [`DBStats.MaxIdleClosed`](https://pkg.go.dev/database/sql#DBStats). `DBStats.MaxIdleClosed` is a counter that only increments, from the lifetime of the `*sql.DB`.

However, when collecting metrics, Grafana adds that value to the metric (itself also a counter):
 
https://github.com/grafana/grafana/blob/82b63688d236a4c5788043822e8a22d003bb8a8c/pkg/services/sqlstore/sqlstore.go#L546

The effect is that the metric is exponentially increasing, rather than exposing the correct value from `DBStats`.

This bug appears to exist for all of the counter metrics that are exposed:

- `grafana_database_conn_max_idle_closed_seconds`
- `grafana_database_conn_max_idle_closed_total`
- `grafana_database_conn_max_lifetime_closed_total`
- `grafana_database_conn_wait_count_total`
- `grafana_database_conn_wait_duration_seconds`

**What you expected to happen**:

I expect the `grafana_database_conn_*` metrics to correctly expose the `DBStats` values.

**How to reproduce it (as minimally and precisely as possible)**:

n/a

**Anything else we need to know?**:

The name `grafana_database_conn_max_idle_closed_seconds` is also not ideal - suffixes like `_seconds` imply that the value's unit is time, but in this case it's not - it's exposing `DBStats. MaxIdleTimeClosed`, which is the number of connections closed due to `MaxIdleTime` being reached.

**Environment**:
- Grafana version: 9.1.0
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:

### PR DESCRIPTION
**Pull request by hairyhenderson**
**What this PR does / why we need it**:

Fixes incorrect `grafana_database_conn_*` metrics, and also introduces optionally using the [`dmiddlecote/sqlstats`](https://github.com/dlmiddlecote/sqlstats) package instead (when the `database_metrics` feature toggle is enabled.

**Which issue(s) this PR fixes**:

Fixes #54242

**Special notes for your reviewer**:

It might be better to simply remove the `grafana_database_conn_*` metrics entirely, and instead replace with the `dmiddlecote/sqlstats` package. That would _technically_ be a breaking change, though, so perhaps it's ideal to defer that removal until 9.2.x or 10.x?

It's worth noting that these metrics are relatively new, only added in 9.1.0-beta1 - in https://github.com/grafana/grafana/pull/52797. Given how broken they are it may be best to just remove them?

**Update:** the `grafana_database_conn_*` metrics have been removed entirely, making this a breaking change

Signed-off-by: Dave Henderson <dave.henderson@grafana.com>

# Deprecation notice

The `grafana_database_conn_*` metrics are deprecated, and will be removed in a future version of Grafana. Use the `go_sql_stats_*` metrics instead.

### CODE REVIEW

File: pkg/services/sqlstore/sqlstore.go [hunk 1]
```diff
@@ -89,9 +79,18 @@ func ProvideService(cfg *setting.Cfg, cacheService *localcache.CacheService, mig
...
-	s.initMetrics()
+	// initialize and register metrics wrapper around the *sql.DB
+	db := s.engine.DB().DB
+
+	var metrics prometheus.Collector
+	if cfg.IsFeatureToggleEnabled(featuremgmt.FlagDatabaseMetrics) {
+		metrics = sqlstats.NewStatsCollector("grafana", db)
+	} else {
+		// TODO: deprecate/remove these metrics
+		metrics = newSQLStoreMetrics(db)
```
Comment (marefr) [inline pkg/services/sqlstore/sqlstore.go:90]: I vote for removing it now. Probably only grafana cloud using it and maybe a couple more

Comment (hairyhenderson) [reply pkg/services/sqlstore/sqlstore.go:90]: ok - I know @bergquist is also in favour of removing it now...

In that case, should I put the new metric names under the `database_metrics` feature toggle, or expose them by default?

Comment (bergquist) [reply pkg/services/sqlstore/sqlstore.go:90]: > expose them by default?

expose them by default. `database_metrics` is behind a feature flag cause we only tested it with mysql enough to make me comfortable.

Comment (bergquist) [reply pkg/services/sqlstore/sqlstore.go:90]: I guess `database_metrics` could be turned into a setting instead. In another PR

Comment (marefr) [reply pkg/services/sqlstore/sqlstore.go]: > expose them by default. `database_metrics` is behind a feature flag cause we only tested it with mysql enough to make me comfortable.

Didn't we have a serious bug enabling the feature toggle on non-mysql drivers? With migrations

**Comment by sakjur** [comment]
I don't think we should ever backport breaking changes to released versions.
If this is all behind a feature toggle, I don't think it is a breaking change, since things behind feature toggles aren't released yet (generally speaking).

**Comment by hairyhenderson** [comment]
Thanks @sakjur - TBH that feels more consistent as a matter of practice anyway.

I can go either way, just need to rip out 8c56a78 - @bergquist, @marefr, can we get some consensus?

I would've liked to have gotten this in for 9.1.2 but it seems a bit late for that... 😞

File: pkg/services/sqlstore/sqlstore.go (hunk 1 above)
Comment (marefr) [reply pkg/services/sqlstore/sqlstore.go]: Sorry, disregard my earlier comment, I mixed this up with https://github.com/grafana/grafana/blob/fc348e62796db7d748f032c3ef079656e3fb379d/pkg/services/sqlstore/sqlstore.go#L354-L356

**Comment by hairyhenderson** [comment]
Ok, I've dropped 8c56a78cc4922108f3663941bc2fff4607607d9a so now there are no breaking changes. 

I'll also remove the `sqlstats` metrics from being being `database_metrics`, as per https://github.com/grafana/grafana/pull/54405#discussion_r957673161. That's safe since the names don't clash at all.

**Review by bergquist — APPROVED** [review]
LGTM

**Comment by bergquist** [comment]
@hairyhenderson Please add the 'add to changelog' label and update the title. The title is used to generate the changelog so it should be descriptive :)

**Comment by hairyhenderson** [comment]
I've added a deprecation notice to the end of the PR description (thanks for the hint @marefr!) - LMK if that looks good

**Comment by bergquist** [comment]
@hairyhenderson you might want to rebase this. there might be a fix in `grafana/grafana` for the enterprise build failures :)

**Comment by hairyhenderson** [comment]
I've rebased this just now...

**Review by marefr — APPROVED** [review]
LGTM, but please update the PR title since same information is in the deprecation notice

**Comment by hairyhenderson** [comment]
Backport is at https://github.com/grafana/grafana/pull/54540
