### PR TITLE
Import: Library panel missing DS when imported in v1 and classic 

### LINKED ISSUE #119494: Dashboards: Unable to import dashboards with libraries as classic or V1 resource
### What happened?

_See also https://community.grafana.com/t/12-4-0-cannot-import-dashboards-with-library-panels-anymore/161940_

Trying to import a dashboard that references library panels like this one: [EVCC: Today | Grafana Labs](https://grafana.com/grafana/dashboards/22028-evcc-today/)

Tried the following methods:

- Import dashboard through Grafana.com using the dashboard ID '22028'.
- Upload dashboard from file system from classic JSON exported under 12.3.1: https://github.com/ha-puzzles/evcc-grafana-dashboards/blob/main/dashboards/dashboards/EVCC_%20Today.json
- Export dashboard from a migrated 12.4.0 system, where the dashboards were imported before the upgrade to 12.4.0 and tried the import to another fresh 12.4.0 installation using either 
  - Classic JSON or 
  - V1 JSON resources.

Neither of these methods works. After import all library panels are broken:

Image

Besides the broken library panels, see the broken variable name on the top of the dashboard:

Image

The only workaround that worked was:

Export as V2 resource under 12.4.0 and import to other 12.4.0 instance - this however eliminates all library panels and I ended up with the message “The Dynamic Dashboard feature is temporarily disabled”. See [New warning about dynamic dashboards being unavailable](https://community.grafana.com/t/new-warning-about-dynamic-dashboards-being-unavailable/161936)

Image

### What did you expect to happen?

Successful import including library panels from classic JSON file as it was possible with previous Grafana versions.

### Did this work before?

Up to Grafana 12.3.2 this works without any problem. 

Downgrade to 12.3.2. and import the dashboard above and it will work.

### How do we reproduce it?

1. Create an influx data source. It does not need the correct data (which would be data from [EVCC](https://evcc.io/))
1. Import this dashboard: https://grafana.com/grafana/dashboards/22028-evcc-today/
2. See the errors on all library panels
3. Examine the list of Library panels. You see several panels starting with the name "EVCC:", which got imported as part of the dashboard.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 12.4.0
OS: Linux, ARM64 (Raspian)
Browser: Brave, Chrome

### Grafana platform?

None

### Datasource(s)?

Influx 1.8, filled through EVCC.io

### PR DESCRIPTION
**Pull request by ivanortegaalba**
## Summary

Fixes #119494

When importing a classic/V1 dashboard with library panels through the K8s import path, library panels appear broken due to two issues:

**1. UID mismatch**: `addLibraryPanel` calls `POST /api/library-elements` without the original `uid`. The backend generates a new random UID, but dashboard panels still reference the original UIDs from `__elements`.

**2. Unresolved datasource placeholders**: Library panel models from `__elements` contain `${DS_...}` placeholders. The legacy backend path ran a full recursive interpolation via `DashTemplateEvaluator` before creating library elements. The K8s frontend path only interpolated panels/annotations/variables via `applyV1Inputs` but never touched the `__elements` models — so library panels were created with broken datasource references.

### Changes

| File | What |
|---|---|
| `api.ts` | `addLibraryPanel` accepts optional `uid` parameter, passes it to the API |
| `inputs.ts` | New `interpolateLibraryPanelDatasources` replaces `${DS_...}` in library panel models |
| `ImportOverviewV1.tsx` | Passes original uid and interpolates models before creating library panels |
| `api.test.ts` | Tests that uid is passed/omitted correctly |
| `inputs.test.ts` | Tests for datasource placeholder interpolation in library panel models |

## Test plan

- [ ] Import the [EVCC dashboard](https://grafana.com/grafana/dashboards/22028-evcc-today/) (ID 22028) from Grafana.com — verify library panels render correctly with resolved datasources
- [ ] Import a classic JSON with `__elements` containing `${DS_...}` references — verify library panels are created with the correct UIDs and datasource UIDs
- [ ] Create a new library panel normally (not via import) — verify no regressions

### CODE REVIEW

File: public/app/features/manage-dashboards/import/utils/inputs.ts [hunk 1]
```diff
@@ -551,6 +551,42 @@ function replaceElementDatasources(
...
+    result.targets = result.targets.map((target: Record<string, unknown>) => {
+      const ds = target.datasource;
+      if (isRecord(ds) && typeof ds.uid === 'string' && ds.uid.startsWith('$')) {
+        const userInput = checkUserInputMatch(ds.uid, inputs.dataSources, form.dataSources);
+        if (userInput) {
+          return { ...target, datasource: { ...ds, uid: userInput.uid } };
+        }
+      }
+      return target;
+    });
```
Comment (axelavargas) [inline public/app/features/manage-dashboards/import/utils/inputs.ts:571]: Can we extract this logic outside, I see the same in `processPanel`

File: public/app/features/manage-dashboards/import/utils/inputs.ts [hunk 2]
```diff
@@ -551,6 +551,42 @@ function replaceElementDatasources(
...
+export function interpolateLibraryPanelDatasources(
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
+  model: any,
+  inputs: { dataSources: DataSourceInput[] },
+  form: ImportDashboardDTO
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
+): any {
+  const result = { ...model };
+
+  if (result.datasource?.uid && typeof result.datasource.uid === 'string' && result.datasource.uid.startsWith('$')) {
```
Comment (axelavargas) [inline public/app/features/manage-dashboards/import/utils/inputs.ts]: In community dashboards, we could get very old dashboards with the legacy datasource string.

`datasource: "${DS_PROMETHEUS}"`

Can we include that edge case here and apply the same fix in `processDashboards` function (that would solve https://github.com/grafana/grafana/issues/117859). I suggest we extract the check adding that edgecase.

`result.datasource?.uid && typeof result.datasource.uid === 'string' && result.datasource.uid.startsWith('$')
`

**Comment by axelavargas** [comment]
@ivanortegaalba btw I found another issue related to collapsed rows, added a small fix here https://github.com/grafana/grafana/pull/120044. We want to use the frontend logic in suggested dashboards and avoid calling `/interpolate` endpoint https://github.com/grafana/grafana/issues/120045 😄

**Review by axelavargas — APPROVED** [review]
Great work, Ivan 🙌🏾. I found we were missing the same fix for variables. I added the commit https://github.com/grafana/grafana/pull/119980/changes/bf9f8084dfbfb5eed95ac53eabd7222346d52149 🙈
