### PR TITLE
Plugins: Refactor Grafana and Plugin version update checkers

### LINKED ISSUE #44590: Plugins: Plugin update checking is not working
**What happened**:
Plugin updates no longer appear in the UI (plugins list page)

IE no longer appears
Screenshot 2022-01-27 at 15 13 51

**What you expected to happen**:
The above image to appear, and to subsequently be able to see the `Update` button via the plugin details page

**How to reproduce it (as minimally and precisely as possible)**:
Install an older version of a plugin where there is a newer version that is compatible with your system (OS, Grafana version, etc.)

### PR DESCRIPTION
**Pull request by wbrowne**
**What this PR does / why we need it**:
This moves plugin version checking outside of the plugin manager, in an effort to make plugin management leaner

This also fixes a bug where plugin update checking stopped working as of `8.3.0-beta1` (https://github.com/grafana/grafana/pull/41340)

**Which issue(s) this PR fixes**:

Fixes #44590

### CODE REVIEW

File: pkg/plugins/manager/update_checker.go [hunk 1]
```diff
@@ -1,84 +0,0 @@
...
-	for _, localP := range m.Plugins(ctx) {
-		for _, gcomP := range gcomPlugins {
-			if gcomP.Slug == localP.ID {
-				localP.GrafanaComVersion = gcomP.Version
-
-				plugVersion, err1 := version.NewVersion(localP.Info.Version)
-				gplugVersion, err2 := version.NewVersion(gcomP.Version)
-
-				if err1 != nil || err2 != nil {
-					localP.GrafanaComHasUpdate = localP.Info.Version != localP.GrafanaComVersion
```
Comment (wbrowne) [inline pkg/plugins/manager/update_checker.go:64]: **NOTE**: I have removed this logic which previously stated that if we had a plugin version (either the version found on grafana com or the one installed in Grafana) that couldn't be properly validated, we just check if they're not the same - and if they're not, we consider that a potential upgrade

**Review by mckn — COMMENTED** [review]
LGTM! Plugins with updates available seems to be updatable 🎉

**Comment by tolzhabayev** [comment]
Some security scans fail https://github.com/grafana/grafana/pull/44529/checks?check_run_id=4980351734

File: pkg/services/updatechecker/plugins.go [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+		s.log.Debug("Failed to unmarshal plugin repo, reading response from grafana.com", "error", err.Error())
+		return
+	}
+
+	for _, gcomP := range gcomPlugins {
+		if localP, exists := localPlugins[gcomP.Slug]; exists {
+			delete(s.availableUpdates, localP.ID)
+
+			if canUpgrade(localP.Info.Version, gcomP.Version) {
+				s.availableUpdates[localP.ID] = gcomP.Version
```
Comment (marefr) [inline pkg/services/updatechecker/plugins.go:123]: Think you need some locking/mutex around this since reading from it in `HasUpdate`. Maybe can use a local map during processing and then lock/unlock for updating the whole map? 

My suggestion would probably also resolve an issue I spotted where availableUpdates are not reset on each run, not sure how big of an issue that is though.

**Review by marefr — CHANGES_REQUESTED** [review]
Great. Left a comment though regarding need of locking.

File: pkg/services/updatechecker/plugins.go (hunk 2 above)
Comment (wbrowne) [reply pkg/services/updatechecker/plugins.go:132]: I just added a mutex control to wrap how things are currently - if you think it could be improved further LMK

File: pkg/services/updatechecker/plugins.go [hunk 3]
```diff
@@ -0,0 +1,171 @@
...
+		// can ignore update as the update data is stale
+		if !canUpgrade(plugin.Info.Version, update) {
+			s.mutex.Lock()
+			delete(s.availableUpdates, pluginID)
+			s.mutex.Unlock()
+
+			return "", false
+		}
+
+		return update, true
```
Comment (marefr) [inline pkg/services/updatechecker/plugins.go:87]: Wouldn't just return canUpgrade be enough here, not sure I understand the use case. But with my suggestion would create less lock contention and comparing versions over and over again doesn't feel like it will impact performance.

**Review by marefr — COMMENTED** [review]
Added some suggestions/comments

File: pkg/services/updatechecker/plugins.go (hunk 3 above)
Comment (wbrowne) [reply pkg/services/updatechecker/plugins.go]: Yeah I think that should be enough actually. Original thought was that if we know here that we can't upgrade, we should just remove the (now stale) update we found in the map

**Review by marefr — APPROVED** [review]
LGTM
