### PR TITLE
CloudMonitor: Correctly encode default project response

### LINKED ISSUE #48907: Minified react error #31 when editing dashboard panel with Google Cloud Monitoring data source
**What happened**:

When I edit a panel in a dashboard where the data source is [Google Cloud Monitoring](https://grafana.com/docs/grafana/latest/datasources/google-cloud-monitoring/). I get the following error:

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

**What you expected to happen**:

I expect to be able to use the [query editor](https://grafana.com/docs/grafana/latest/datasources/google-cloud-monitoring/#using-the-query-editor) to create a query. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure a data source using Google Cloud Monitoring using `GCE Default Service Account` authentication (see image)
2. `Save & test` and ensure you get the green check mark
3. Create new dashboard and select `Add a new panel`.
4. Select the `Google Cloud Monitoring` data source. This may work the first time. If it does, select another data source and then re-select `Google Cloud Monitoring`

image

**Anything else we need to know?**:

* [Issue #47872](https://github.com/grafana/grafana/issues/47872) seemed related but upgrading to 8.5.0 did not resolve the issue.
* The plugin does work when I import the dashboards that come with the data source (i.e. the dashboards show data). I am able to reproduce the issue with those dashboards by editing a panel, switching the data source to something that's not Google Cloud Monitoring and then switching back.

**Environment**:
- Grafana version: 8.5.2 (also tested on 8.5.0, 8.4.6, 8.4.4)
- Data source type & version: [Google Cloud Monitoring](https://grafana.com/docs/grafana/latest/datasources/google-cloud-monitoring/) 1.0.0
- OS Grafana is installed on: [grafana/grafana:8.5.2](https://hub.docker.com/layers/grafana/grafana/grafana/8.5.2/images/sha256-60666139f672e0ff3d71395102a813e7ff85e8afd7cc5c2d4676abcb00a357a4?context=explore) docker image running in GKE
- User OS & Browser: MacOS, Firefox 100.0 (also tested on Safari 15.4, Brave 1.38.111)
- Grafana plugins: -
- Others: -

### PR DESCRIPTION
**Pull request by aangelisc**
**What this PR does / why we need it**:

Correctly encodes the response of `getGCEDefaultProject` to prevent invalid JSON being returned which then gets parsed as an empty object. 
 
**Which issue(s) this PR fixes**:

Fixes #48907 

**Special notes for your reviewer**:

Tested in GCP by creating an instance and installing Grafana locally. The Cloud Monitoring datasource was then setup to use the `GCE Default Service Account` authentication method (which was the affected method). The fix was also tested as above.

### CODE REVIEW

File: pkg/tsdb/cloudmonitoring/resource_handler.go [hunk 1]
```diff
@@ -41,7 +41,8 @@ func getGCEDefaultProject(rw http.ResponseWriter, req *http.Request) {
 		writeResponse(rw, http.StatusBadRequest, fmt.Sprintf("unexpected error %v", err))
 		return
 	}
-	writeResponse(rw, http.StatusOK, project)
+	encoded, _ := json.Marshal(project)
```
Comment (andresmgot) [inline pkg/tsdb/cloudmonitoring/resource_handler.go:44]: we should handle the possible error here

Comment (andresmgot) [inline pkg/tsdb/cloudmonitoring/resource_handler.go:44]: Also, if you make this function a `s *Service` function, you can use `s.gceDefaultProjectGetter` to retrieve the default project. That way you can "easily" add tests for this.

**Review by andresmgot — COMMENTED** [review]
Good catch! Can you add some test to express what's the expected result here? (from the API perspective)

File: pkg/tsdb/cloudmonitoring/resource_handler.go [hunk 2]
```diff
@@ -27,21 +26,29 @@ type processResponse func(body []byte) ([]json.RawMessage, string, error)
...
 	return mux
 }
 
-func getGCEDefaultProject(rw http.ResponseWriter, req *http.Request) {
-	project, err := utils.GCEDefaultProject(req.Context())
-	if err != nil {
-		writeResponse(rw, http.StatusBadRequest, fmt.Sprintf("unexpected error %v", err))
-		return
+func (s *Service) getGCEDefaultProject() func(rw http.ResponseWriter, req *http.Request) {
+	return func(rw http.ResponseWriter, req *http.Request) {
```
Comment (andresmgot) [inline pkg/tsdb/cloudmonitoring/resource_handler.go:38]: you don't have any parameters so you don't need the extra wrapper. You can just define:

```
func (s *Service) getGCEDefaultProject(rw http.ResponseWriter, req *http.Request) {
```

File: pkg/tsdb/cloudmonitoring/resource_handler_test.go [hunk 3]
```diff
@@ -285,3 +287,23 @@ func Test_processData_functions(t *testing.T) {
...
+				},
+			},
+		},
+		gceDefaultProjectGetter: func(ctx context.Context) (string, error) {
+			return project, nil
+		},
+	}
+
+	assert.HTTPSuccess(t, s.getGCEDefaultProject(), "GET", "/gceDefaultProject", nil)
+	assert.HTTPBodyContains(t, s.getGCEDefaultProject(), "GET", "/gceDefaultProject", nil, project)
```
Comment (andresmgot) [inline pkg/tsdb/cloudmonitoring/resource_handler_test.go:308]: I believe this test would have successed without your change. I am not sure if the fix is that since now you are returning a JSON, there is a header `Content-Type: "application/json"` or that we are now returning `"project-name"` vs `project-name`. Can you clarify that?

**Review by andresmgot — COMMENTED** [review]
thanks for the test! some more suggestions

File: pkg/tsdb/cloudmonitoring/resource_handler_test.go (hunk 3 above)
Comment (aangelisc) [reply pkg/tsdb/cloudmonitoring/resource_handler_test.go:308]: Previously the return value would've been `project-name` which is invalid JSON vs `"project-name"`. You're correct the test would've succeeded before the change, I'm updating this now 😊

**Review by andresmgot — APPROVED** [review]
LGTM!
