### PR TITLE
BarChart: Only apply radius to topmost bar segment when stacking

### LINKED ISSUE #61833: [Bar Chart] Bug when using Bar Radius with staking for multiple series.
**What happened**:

Bar chart rounded corners do not behave right when overlapping

**What you expected to happen**:

Bars with rounded corners to overlap without visible corners at the bottom.

**How to reproduce it (as minimally and precisely as possible)**:

- using BarChart with 2 or more series
- set  stacking to Normal or 100%
- set the Bar Radius to a value higher than 0

The result is:

image

**Anything else we need to know?**:

**Environment**: All  (OSS and  Grafana Cloud)
- Grafana version: 9.3.2
- Data source type & version:  used the TestDB to replicate the behaviour
- OS Grafana is installed on: Tested with Ubuntu 20.04 for OSS, in cloud you can use [this panel in Grafana Play](https://play.grafana.org/d/timeseries-stacking2/timeseries-and-barchart-stacking?orgId=1&editPanel=18) to replicate the problem.
- User OS & Browser: MacOS Ventura 13.1 and Google Chrome 109.0.5414.87 (Official Build) (arm64)
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/grafana/issues/61833

(it's not a perfect fix, see above issue for caveats, but kicks the can down the road somewhat, and fixes obvious badness)

test with:

<details><summary>stacked-barchart-radius.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 610,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "fillOpacity": 80,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1,
            "scaleDistribution": {
              "type": "linear"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 28,
        "w": 7,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "barRadius": 0.1,
        "barWidth": 0.7,
        "fullHighlight": false,
        "groupWidth": 0.7,
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "orientation": "vertical",
        "showValue": "auto",
        "stacking": "normal",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "xTickLabelRotation": 0,
        "xTickLabelSpacing": 0
      },
      "targets": [
        {
          "csvContent": "Name,Stat1,Stat2,Stat3,Stat4,Stat5,Stat6,Stat7,Stat8,Stat9,Stat10\nA, 10, 15,8,3,4,12,14,1,5,10\nB, 19, 5,8,3,4,12,14,6,7,2\nC, 15, 5,8,3,4,10,4,6,7,2\n",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "type": "barchart"
    }
  ],
  "refresh": "",
  "revision": 1,
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "stacked-barchart-radius",
  "uid": "be66b644-03ab-4883-8cae-589ab656f75a",
  "version": 5,
  "weekStart": ""
}
```
</details>

before/after:

https://user-images.githubusercontent.com/43234/222008258-ff5827a8-01d1-4619-b1b5-f57067b3e14c.mp4

### CODE REVIEW

File: public/app/plugins/panel/barchart/bars.ts [hunk 1]
```diff
@@ -286,7 +286,14 @@ export function getConfig(opts: BarsOptions, theme: GrafanaTheme2) {
...
   let barsBuilder = uPlot.paths.bars!({
-    radius: barRadius,
+    radius: pctStacked
+      ? 0
+      : !isStacked
+      ? barRadius
+      : (u: uPlot, seriesIdx: number) => {
+          let isTopmostSeries = seriesIdx === u.data.length - 1;
+          return isTopmostSeries ? [barRadius, 0] : [0, 0];
+        },
```
Comment (nmarrs) [inline public/app/plugins/panel/barchart/bars.ts:296]: This isn't the most readable logic 🤔 could we maybe break this out as an util func or even setting a value for `radius` above line 288 using if branches? (not as concise but maybe more readable option?)

**Review by nmarrs — APPROVED** [review]
💯

File: public/app/plugins/panel/barchart/bars.ts (hunk 1 above)
Comment (leeoniya) [reply public/app/plugins/panel/barchart/bars.ts:296]: i guess it's in the eye of the beholder? i find this to be much more difficult to read with a soup of braces and packed if/else one-liners:

```ts
let finalBarRadius: uPlot.Series.BarsPathBuilderRadius;

if (pctStacked) {
  finalBarRadius = 0;
} else if (!isStacked) {
  finalBarRadius = barRadius;
} else {
  finalBarRadius = (u: uPlot, seriesIdx: number) => {
     let isTopmostSeries = seriesIdx === u.data.length - 1;
     return isTopmostSeries ? [barRadius, 0] : [0, 0];
  };
}
```

that being said, i'm not a huge fan of what Prettier forces upon my original formatting :cry: :

```ts
  let barsBuilder = uPlot.paths.bars!({
    radius: (
      pctStacked ? 0 :
      !isStacked ? barRadius :
      (u: uPlot, seriesIdx: number) => {
          let isTopmostSeries = seriesIdx === u.data.length - 1;
          return isTopmostSeries ? [barRadius, 0] : [0, 0];
        }
    ),
```

Comment (nmarrs) [reply public/app/plugins/panel/barchart/bars.ts:296]: Yeah either way isn't super ideal, to me the if else just reads a bit more clearly but I don't feel strongly either way 🤷🏻‍♂️ maybe a helpful comment explaining basic logic flow could be useful, otherwise :shipit:

Comment (leeoniya) [reply public/app/plugins/panel/barchart/bars.ts:296]: :see_no_evil:

**Comment by masterwishx** [comment]
Using lasted version and got : 
can we get override parameter for other field ?

image
