### PR TITLE
SQLStore: Prevent concurrent migrations

### LINKED ISSUE #41834: Grafana migration can fail when two replicas start up near the same time
**What happened**:

We're seeing occasional crashes when multiple Grafana replicas connected to the same database start up at close to the same time. These are caused by migration failures, but migrations generally succeed after a restart (or a few restarts).

(See also [internal Slack conversation](https://raintank-corp.slack.com/archives/CMSUYD6H3/p1636665199127300))

**What you expected to happen**:

Migrations should succeed and Grafana should not crash on startup.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

This is specifically an issue with MySQL, which cannot guarantee transactional integrity for schema changes.

The solution should likely involve locking the database at migration time, with a reasonable lock timeout (10-30s) to avoid risks from Grafana crashing and not releasing the lock. The https://github.com/golang-migrate/migrate project uses this approach.

**Environment**:
- Grafana version: 8.2.4 or recent main builds (Grafana Cloud)
- Data source type & version: n/a
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
It extends Dialect interface by introducing two additional functions for locking and unlocking the database (implemented for MySQL and Postgres).
It modifies the migrator so that it locks the database before running the migrations and unlocks it on completion.
The implementation is similar to locking in https://github.com/golang-migrate/migrate
This feature is disabled by default and for enabling users need to set the `migrationLocking` feature toggle.

**Which issue(s) this PR fixes**:

Fixes #41834

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/sqlstore/migrator/migrator.go [hunk 1]
```diff
@@ -5,21 +5,29 @@ import (
 	"time"
 
 	_ "github.com/go-sql-driver/mysql"
+	"github.com/golang-migrate/migrate/v4/database"
```
Comment (papagian) [inline pkg/services/sqlstore/migrator/migrator.go:8]: I have added it as dependency since I use some utility functions. Alternative I could have implemented inside grafana. Not sure which we prefer better.

File: pkg/services/sqlstore/migrator/mysql_dialect.go [hunk 2]
```diff
@@ -225,3 +225,71 @@ func (db *MySQLDialect) UpsertSQL(tableName string, keyCols, updateCols []string
...
+	}
+
+	// trying to obtain the lock with the specific name
+	// the lock is exclusive per session and is released explicitly by executing RELEASE_LOCK() or implicitly when the session terminates
+	// it returns 1 if the lock was obtained successfully,
+	// 0 if the attempt timed out (for example, because another client has previously locked the name),
+	// or NULL if an error occurred
+	// starting from MySQL 5.7 it is even possible for a given session to acquire multiple locks for the same name
+	// however other sessions cannot acquire a lock with that name until the acquiring session releases all its locks for the name.
+	_, err = sess.SQL(query, lockName, 0).Get(&success)
```
Comment (papagian) [inline pkg/services/sqlstore/migrator/mysql_dialect.go:248]: I have set timeout to 0 so it fail fast and it won't wait at all if the database is already locked.

File: pkg/services/sqlstore/migrator/mysql_dialect.go [hunk 3]
```diff
@@ -225,3 +225,71 @@ func (db *MySQLDialect) UpsertSQL(tableName string, keyCols, updateCols []string
...
+func (db *MySQLDialect) getLockName() (string, error) {
+	cfg, err := mysql.ParseDSN(db.engine.DataSourceName())
+	if err != nil {
+		return "", err
+	}
+
+	s := strings.Join([]string{cfg.Addr, cfg.DBName}, "/")
+
+	// MySQL 5.7 and later enforces a maximum length on lock names of 64 characters.
+	// TODO check lock name length
```
Comment (papagian) [inline pkg/services/sqlstore/migrator/mysql_dialect.go:293]: This will be an issue if the datasource name is longer. Not sure which lock name is better to pick in this case.

File: pkg/services/sqlstore/migrations/migrations_test.go [hunk 4]
```diff
@@ -53,6 +57,126 @@ func TestMigrations(t *testing.T) {
 	checkStepsAndDatabaseMatch(t, mg, expectedMigrations)
 }
 
+func TestMigrationLock(t *testing.T) {
```
Comment (papagian) [inline pkg/services/sqlstore/migrations/migrations_test.go:60]: Note that the tests in this file are not marked as integration tests so won't run during CI against MySQL and Postgres. I'm not sure if we want to force then run during CI checks.

for running them locally:
```
make devenv sources=mysql_tests,postgres_tests mysql_version=5.7
GRAFANA_TEST_DB=mysql go test -v -count 1 --race ./pkg/services/sqlstore/migrations/...
GRAFANA_TEST_DB=postgres go test -v -count 1 --race ./pkg/services/sqlstore/migrations/...
```

File: pkg/services/sqlstore/migrator/mysql_dialect.go (hunk 2 above)
Comment (marefr) [reply pkg/services/sqlstore/migrator/mysql_dialect.go:252]: This means that the Grafana instance not acquiring the lock will continue to init and start Grafana, right? Have you considered this a problem?

Comment (papagian) [reply pkg/services/sqlstore/migrator/mysql_dialect.go:252]: no, AFAIU if it's not able to acquire the lock returns an error and falls in [this](https://github.com/grafana/grafana/blob/53fbb825f162b6044d51a408b7ea7edd236ef1d4/pkg/services/sqlstore/migrator/migrator.go#L102) case, so the server will fail to start.

Comment (marefr) [reply pkg/services/sqlstore/migrator/mysql_dialect.go:252]: Great, that feels like a viable solution :+1: In Kubernetes this would mean that new pods will be started until migrations are complete and the `ReplicaSet` is fulfilled with number of running/health pods.

File: pkg/services/sqlstore/migrations/migrations_test.go (hunk 4 above)
Comment (marefr) [reply pkg/services/sqlstore/migrations/migrations_test.go:60]: You think/know it will lock the database under test and affect other tests? Think each integration test runs per package synchronously so should be fine I think. Would be good to run this in CI if possible.

Comment (marefr) [reply pkg/services/sqlstore/migrations/migrations_test.go:60]: Or alternatively, implementing an integration test [here](https://github.com/grafana/grafana/blob/main/pkg/tests/README.md) that starts two instances at the same time perhaps? Not sure how easy that would be. We're not running them with integration build tag today, but we probably want that and you could definitely do that for this test I believe.

File: pkg/services/sqlstore/migrator/mysql_dialect.go [hunk 5]
```diff
@@ -225,3 +229,76 @@ func (db *MySQLDialect) UpsertSQL(tableName string, keyCols, updateCols []string
...
+		return "", err
+	}
+
+	s, err := database.GenerateAdvisoryLockId(cfg.DBName)
+	if err != nil {
+		return "", fmt.Errorf("failed to generate advisory lock key: %w", err)
+	}
+
+	if len(s) > max_allowed_lockname_length {
+		// what if there several databases with same prefix of 64 length or more?
```
Comment (marefr) [inline pkg/services/sqlstore/migrator/mysql_dialect.go:300]: We need to document this as a potential breaking change at least. Random thought, might be able to use https://grafana.com/docs/grafana/latest/administration/configuration/#instance_name as fallback, but not sure since it can be empty.

**Review by marefr — COMMENTED** [review]
I think this looks great :+1: Would like to take it for a spin as well. An integration test would be nice as discussed in comments.

File: pkg/services/sqlstore/migrations/migrations_test.go (hunk 4 above)
Comment (papagian) [reply pkg/services/sqlstore/migrations/migrations_test.go:60]: > You think/know it will lock the database under test and affect other tests? Think each integration test runs per package synchronously so should be fine I think. Would be good to run this in CI if possible.

good question! I unlock the database during test cleanups and also locking should not last long in the tests (don't do anything meaningful) but I believe it is still possible if tests run concurrently. I agree that I would like to include them in the CI.

> Or alternatively, implementing an integration test here that starts two instances at the same time perhaps? Not sure how easy that would be. We're not running them with integration build tag today, but we probably want that and you could definitely do that for this test I believe.

I tried to make an integration test but since `testinfra.StartGrafana` performs also other tasks it was difficult to synchronise them so that the migrations occur at the same time.

Comment (marefr) [reply pkg/services/sqlstore/migrations/migrations_test.go:60]: > I tried to make an integration test but since `testinfra.StartGrafana` performs also other tasks it was difficult to synchronise them so that the migrations occur at the same time.

Okay. So maybe easier with a database integration test then and run two go routines somehow syncing them to race/compete for the database lock.

File: pkg/services/sqlstore/migrator/mysql_dialect.go [hunk 6]
```diff
@@ -225,3 +229,76 @@ func (db *MySQLDialect) UpsertSQL(tableName string, keyCols, updateCols []string
 	)
 	return s
 }
+
+func (db *MySQLDialect) Lock() error {
+	sess := db.engine.NewSession()
+	defer sess.Close()
```
Comment (radiohead) [inline pkg/services/sqlstore/migrator/mysql_dialect.go:235]: I'm not very familiar with `xorm` and what their concept of a `Session` is so I'm just doing a sanity check.

If session = connection, then opening and closing a session to obtain a lock does not provide proper locking guarantees, since the lock will be automatically released after `Lock` returns, i.e.:

```go
var db *MySQLDialect

db.Lock() // Lock is created and immediately released
db.Migrate() // Is not protected by the lock
db.Unlock() // no-op
```

Please correct me if I'm wrong.

Comment (papagian) [reply pkg/services/sqlstore/migrator/mysql_dialect.go:235]: you are totally right! I would swear I had made a change to pass the session and not closing it but I must have missed it in the way.

File: pkg/services/sqlstore/migrations/migrations_test.go (hunk 4 above)
Comment (papagian) [reply pkg/services/sqlstore/migrations/migrations_test.go:62]: I've added [TestDatabaseLocking](https://github.com/grafana/grafana/blob/d422f312cda0ca480fe4433e037a9dd3bc458eeb/pkg/services/sqlstore/migrations/migrations_test.go#L185) where I create two migrators (for the same database) and run the migrations concurrency and check that the 2nd one fails with the error returned by `Lock()`.
I enclose the test output:
<details>
<summary></summary>

```
GRAFANA_TEST_DB=mysql go test -v -count 1 --race ./pkg/services/sqlstore/migrations/... -run TestDatabaseLocking 
=== RUN   TestDatabaseLocking
=== RUN   TestDatabaseLocking/when_concurrent_migrations_occur_for_different_migrators_occur,_the_second_one_should_fail
=== RUN   TestDatabaseLocking/when_concurrent_migrations_occur_for_different_migrators_occur,_the_second_one_should_fail/run_migration_0
=== PAUSE TestDatabaseLocking/when_concurrent_migrations_occur_for_different_migrators_occur,_the_second_one_should_fail/run_migration_0
=== RUN   TestDatabaseLocking/when_concurrent_migrations_occur_for_different_migrators_occur,_the_second_one_should_fail/run_migration_1
=== PAUSE TestDatabaseLocking/when_concurrent_migrations_occur_for_different_migrators_occur,_the_second_one_should_fail/run_migration_1
=== CONT  TestDatabaseLocking/when_concurrent_migrations_occur_for_different_migrators_occur,_the_second_one_should_fail/run_migration_1
=== CONT  TestDatabaseLocking/when_concurrent_migrations_occur_for_different_migrators_occur,_the_second_one_should_fail/run_migration_0
logger=migrator t=2022-01-31T18:11:43.63+0200 lvl=info msg="Locking database"
logger=migrator t=2022-01-31T18:11:43.63+0200 lvl=info msg="Starting DB migrations"
logger=migrator t=2022-01-31T18:11:43.63+0200 lvl=info msg="Locking database"
logger=migrator t=2022-01-31T18:11:43.64+0200 lvl=eror msg="Failed to lock database" error="failed to obtain lock"
logger=migrator t=2022-01-31T18:11:43.64+0200 lvl=info msg="Executing migration" id="create migration_log table"
[...]
logger=migrator t=2022-01-31T18:11:47.86+0200 lvl=info msg="Unlocking database"
--- PASS: TestDatabaseLocking (4.96s)
    --- PASS: TestDatabaseLocking/when_concurrent_migrations_occur_for_different_migrators_occur,_the_second_one_should_fail (0.00s)
        --- PASS: TestDatabaseLocking/when_concurrent_migrations_occur_for_different_migrators_occur,_the_second_one_should_fail/run_migration_0 (0.01s)
        --- PASS: TestDatabaseLocking/when_concurrent_migrations_occur_for_different_migrators_occur,_the_second_one_should_fail/run_migration_1 (4.24s)
PASS
```
</details>

File: pkg/services/sqlstore/migrator/mysql_dialect.go (hunk 5 above)
Comment (papagian) [reply pkg/services/sqlstore/migrator/mysql_dialect.go:295]: > We need to document this as a potential breaking change at least.
do you mean not allowing having databases with longer names?

> Random thought, might be able to use https://grafana.com/docs/grafana/latest/administration/configuration/#instance_name as fallback, but not sure since it can be empty.
but still there is not any limit on the  length of `instance_name`, right?

File: pkg/services/sqlstore/migrator/mysql_dialect.go (hunk 6 above)
Comment (papagian) [reply pkg/services/sqlstore/migrator/mysql_dialect.go]: @radiohead I have pushed the changes, if you want to check again!

File: pkg/services/sqlstore/migrator/mysql_dialect.go (hunk 5 above)
Comment (marefr) [reply pkg/services/sqlstore/migrator/mysql_dialect.go:295]: > do you mean not allowing having databases with longer names?

Yes. Just in case someone hits this we should have it covered under breaking changes in release notes at least. Question is what to suggest if this happens, rename the database? Might not be possible/hard. Do we need a config to fallback on perhaps? I really like to keep the number of configuration parameters as low as possible so see this as a last resort so lets wait with this and see if someone hits this problem.

> but still there is not any limit on the length of instance_name, right?

True. Forgot my suggestion since instance_name is supposed to be/is probably unique :smile:

File: pkg/services/sqlstore/migrator/migrator.go [hunk 7]
```diff
@@ -96,20 +95,28 @@ func (mg *Migrator) GetMigrationLog() (map[string]MigrationLog, error) {
...
 		}
-	}()
 
+		defer func() {
+			mg.Logger.Info("Unlocking database")
+			unlockErr := casRestoreOnErr(&mg.isLocked, true, false, ErrMigratorIsUnlocked, mg.Dialect.Unlock, sess)
+			if unlockErr != nil {
+				mg.Logger.Error("Failed to unlock database", "error", unlockErr)
+			}
+			sess.Close()
```
Comment (radiohead) [inline pkg/services/sqlstore/migrator/migrator.go:111]: Just making a sanity check here - do we need to close `sess` manually here, or will `mg.InTransaction` take care of this?

If we need to always close it manually, then we need to do the same on line 101, in the error handling of `casRestoreOnErr` or maybe just put `defer sess.Close()` at the top of the `InTransaction` callback.

Comment (papagian) [reply pkg/services/sqlstore/migrator/migrator.go:111]: sorry, my mistake `InTransaction()` takes care of it; I just forgot to remove it when I copied.

Comment (radiohead) [reply pkg/services/sqlstore/migrator/migrator.go:111]: Okay, thanks for the clarification!

File: pkg/services/sqlstore/migrator/migrator.go [hunk 8]
```diff
@@ -87,7 +94,29 @@ func (mg *Migrator) GetMigrationLog() (map[string]MigrationLog, error) {
...
+		}
+
+		defer func() {
+			mg.Logger.Info("Unlocking database")
+			unlockErr := casRestoreOnErr(&mg.isLocked, true, false, ErrMigratorIsUnlocked, mg.Dialect.Unlock, sess)
+			if unlockErr != nil {
+				mg.Logger.Error("Failed to unlock database", "error", unlockErr)
+			}
+			sess.Close()
+		}()
```
Comment (radiohead) [inline pkg/services/sqlstore/migrator/migrator.go:112]: Since we use `InTransaction`, we don't need to call `sess.Close()` manually here.
```suggestion
		defer func() {
			mg.Logger.Info("Unlocking database")
			unlockErr := casRestoreOnErr(&mg.isLocked, true, false, ErrMigratorIsUnlocked, mg.Dialect.Unlock, sess)
			if unlockErr != nil {
				mg.Logger.Error("Failed to unlock database", "error", unlockErr)
			}
		}()
```

**Review by radiohead — APPROVED** [review]
Looks great, thanks! 🎉

File: pkg/services/sqlstore/migrator/mysql_dialect.go (hunk 5 above)
Comment (papagian) [reply pkg/services/sqlstore/migrator/mysql_dialect.go:295]: checking again: this is [crc32](https://github.com/golang-migrate/migrate/blob/3e43c429ee00336a1e8e3bc1f9a855d55b3b4414/database/util.go#L17) so it's length it's should be fixed.
I tend to believe that this redundant.

Comment (marefr) [reply pkg/services/sqlstore/migrator/mysql_dialect.go:295]: You mean `if len(s) > max_allowed_lockname_length {` is redundant?

File: pkg/services/sqlstore/migrator/mysql_dialect.go (hunk 2 above)
Comment (bergquist) [reply pkg/services/sqlstore/migrator/mysql_dialect.go:250]: I think we want to make the timeout configurable and allow the Grafana instance to retry the migrations after a certain time. This will work in K8S but we also alert on pod restarting too many times to catch configuration errors and other unexpected behaviors. 

In the on-prem scenario I think retries and configurable timeout would be very appropriated since on-prem tooling might not solve the instance life cycle as good as K8s


Making the timeout configurable should be good enough to get this merged and retries could be solve in a follow up PR.

File: pkg/services/sqlstore/migrator/migrator.go [hunk 9]
```diff
@@ -87,7 +94,28 @@ func (mg *Migrator) GetMigrationLog() (map[string]MigrationLog, error) {
 	return logMap, nil
 }
 
-func (mg *Migrator) Start() error {
+func (mg *Migrator) Start() (err error) {
```
[the remark this answers is not in the document]
Comment (dafydd-t) [reply pkg/services/sqlstore/migrator/migrator.go:97]: +1

File: pkg/services/sqlstore/migrator/mysql_dialect.go (hunk 5 above)
Comment (dafydd-t) [reply pkg/services/sqlstore/migrator/mysql_dialect.go:295]: I also think this is redundant. IIUC: CRC checksum is 32 bits, with a theoretical max value of 2147483647. 2147483647 * (the salt) 1486364155 = 3191942716349473285, which as a string has length 19.

File: pkg/services/sqlstore/migrator/mysql_dialect.go (hunk 2 above)
Comment (dafydd-t) [reply pkg/services/sqlstore/migrator/mysql_dialect.go:250]: I agree, it would be nice to be able to set this timeout in HG. I think it would be preferrable for a 2nd instance to wait a few seconds to get a lock, then perform a noop on migration (as they're already completed, say), compared to crashLoop until the lock becomes available.

File: docs/sources/administration/configuration.md [hunk 10]
```diff
@@ -314,6 +314,10 @@ The maximum number of open connections to the database.
 
 Sets the maximum amount of time a connection may be reused. The default is 14400 (which means 14400 seconds or 4 hours). For MySQL, this setting should be shorter than the [`wait_timeout`](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout) variable.
 
+### locking_attempt_timeout_sec
+
+For "mysql" only if `lockingMigration` feature toggle is set. How many seconds to wait before failing to lock the database for the migrations, default is 0.
```
Comment (achatterjee-grafana) [inline docs/sources/administration/configuration.md:319]:
```suggestion
For "mysql", if `lockingMigration` feature toggle is set, specify the time (in seconds) to wait before failing to lock the database for the migrations. Default is 0.
```
```suggestion
For "mysql" only if `lockingMigration` feature toggle is set. How many seconds to wait before failing to lock the database for the migrations, default is 0.
```

**Review by achatterjee-grafana — COMMENTED** [review]
Added doc review.

File: pkg/services/sqlstore/migrator/migrator.go [hunk 11]
```diff
@@ -87,7 +94,32 @@ func (mg *Migrator) GetMigrationLog() (map[string]MigrationLog, error) {
...
+
+		defer func() {
+			mg.Logger.Info("Unlocking database")
+			unlockErr := casRestoreOnErr(&mg.isLocked, true, false, ErrMigratorIsUnlocked, mg.Dialect.Unlock, LockCfg{Session: sess})
+			if unlockErr != nil {
+				mg.Logger.Error("Failed to unlock database", "error", unlockErr)
+			}
+		}()
+
+		// migration will run inside a nested transaction
```
Comment (bergquist) [inline pkg/services/sqlstore/migrator/migrator.go:117]: I don't think all the migrations will run in the same transaction https://github.com/grafana/grafana/pull/44101/files#diff-cc26a898455f75d00301a5d13594c160a6558b4152fcd5c47b502375a03d3675R224

But they don't have to either since the whole database is locked :)

**Review by bergquist — APPROVED** [review]
LGTM

A comment but not a blocker.

**Comment by bergquist** [comment]
@papagian how do you feel about merging this before 8.4.0? It's behind a feature toggle after all :)

File: pkg/services/sqlstore/migrator/migrator.go (hunk 11 above)
Comment (papagian) [reply pkg/services/sqlstore/migrator/migrator.go:117]: I'm not sure I understand why they won't run in the same transaction: we start a new transaction inside [migrator.run()](https://github.com/grafana/grafana/blob/cc5f372e2d50d486d4c372a2f2762e6a93e915d7/pkg/services/sqlstore/migrator/migrator.go#L150)

**Comment by AgnesToulet** [comment]
@papagian This is breaking Enterprise because of a dependency cycle (see https://drone.grafana.net/grafana/grafana-enterprise/15483/1/9). I wouldn't backport this if a fix is not ready for Enterprise as it will block the 8.4 release.

**Comment by marefr** [comment]
Did some tests using Grafana High Availability (HA) test setup and seems to work as expected :+1: 

The setting `restart: "on-failure"` for grafana docker-compose service was used and started ha test using 3 Grafana instances; `docker-compose up --scale grafana=3 -d `.

<details><summary>MySQL log output</summary>

```bash
grafana_3          | logger=sqlstore t=2022-02-15T23:29:08.85+0000 lvl=info msg="Connecting to DB" dbtype=mysqlWithHooks
grafana_3          | logger=migrator t=2022-02-15T23:29:08.85+0000 lvl=info msg="Locking database"
grafana_3          | logger=migrator t=2022-02-15T23:29:08.85+0000 lvl=info msg="Starting DB migrations"

grafana_1          | logger=sqlstore t=2022-02-15T23:29:08.91+0000 lvl=info msg="Connecting to DB" dbtype=mysqlWithHooks
grafana_1          | logger=migrator t=2022-02-15T23:29:08.92+0000 lvl=info msg="Locking database"
grafana_1          | logger=migrator t=2022-02-15T23:29:08.92+0000 lvl=eror msg="Failed to lock database" error="failed to obtain lock"
grafana_1          | Failed to start grafana. error: failed to obtain lock
grafana_1          | failed to obtain lock

grafana_2          | logger=sqlstore t=2022-02-15T23:29:08.91+0000 lvl=info msg="Connecting to DB" dbtype=mysqlWithHooks
grafana_2          | logger=migrator t=2022-02-15T23:29:08.92+0000 lvl=info msg="Locking database"
grafana_2          | logger=migrator t=2022-02-15T23:29:08.92+0000 lvl=eror msg="Failed to lock database" error="failed to obtain lock"
grafana_2          | Failed to start grafana. error: failed to obtain lock
grafana_2          | failed to obtain lock

grafana_1          | logger=sqlstore t=2022-02-15T23:29:09.97+0000 lvl=info msg="Connecting to DB" dbtype=mysqlWithHooks
grafana_1          | logger=migrator t=2022-02-15T23:29:09.99+0000 lvl=info msg="Locking database"
grafana_1          | logger=migrator t=2022-02-15T23:29:09.99+0000 lvl=eror msg="Failed to lock database" error="failed to obtain lock"
grafana_1          | Failed to start grafana. error: failed to obtain lock
grafana_1          | failed to obtain lock

grafana_2          | logger=sqlstore t=2022-02-15T23:29:09.97+0000 lvl=info msg="Connecting to DB" dbtype=mysqlWithHooks
grafana_2          | logger=migrator t=2022-02-15T23:29:09.98+0000 lvl=info msg="Locking database"
grafana_2          | logger=migrator t=2022-02-15T23:29:09.98+0000 lvl=eror msg="Failed to lock database" error="failed to obtain lock"
grafana_2          | Failed to start grafana. error: failed to obtain lock
grafana_2          | failed to obtain lock

grafana_1          | logger=sqlstore t=2022-02-15T23:29:10.82+0000 lvl=info msg="Connecting to DB" dbtype=mysqlWithHooks
grafana_1          | logger=migrator t=2022-02-15T23:29:10.84+0000 lvl=info msg="Locking database"
grafana_1          | logger=migrator t=2022-02-15T23:29:10.84+0000 lvl=eror msg="Failed to lock database" error="failed to obtain lock"
grafana_1          | Failed to start grafana. error: failed to obtain lock
grafana_1          | failed to obtain lock

grafana_2          | logger=sqlstore t=2022-02-15T23:29:10.82+0000 lvl=info msg="Connecting to DB" dbtype=mysqlWithHooks
grafana_2          | logger=migrator t=2022-02-15T23:29:10.84+0000 lvl=info msg="Locking database"
grafana_2          | logger=migrator t=2022-02-15T23:29:10.84+0000 lvl=eror msg="Failed to lock database" error="failed to obtain lock"
grafana_2          | Failed to start grafana. error: failed to obtain lock
grafana_2          | failed to obtain lock

grafana_3          | logger=migrator t=2022-02-15T23:29:11.68+0000 lvl=info msg="migrations completed" performed=387 skipped=0 duration=2.828375959s
grafana_3          | logger=migrator t=2022-02-15T23:29:11.68+0000 lvl=info msg="Unlocking database"

grafana_1          | logger=sqlstore t=2022-02-15T23:29:11.78+0000 lvl=info msg="Connecting to DB" dbtype=mysqlWithHooks
grafana_1          | logger=migrator t=2022-02-15T23:29:11.8+0000 lvl=info msg="Locking database"
grafana_1          | logger=migrator t=2022-02-15T23:29:11.81+0000 lvl=eror msg="Failed to lock database" error="failed to obtain lock"
grafana_1          | Failed to start grafana. error: failed to obtain lock
grafana_1          | failed to obtain lock

grafana_2          | logger=sqlstore t=2022-02-15T23:29:11.77+0000 lvl=info msg="Connecting to DB" dbtype=mysqlWithHooks
grafana_2          | logger=migrator t=2022-02-15T23:29:11.8+0000 lvl=info msg="Locking database"
grafana_2          | logger=migrator t=2022-02-15T23:29:11.8+0000 lvl=info msg="Starting DB migrations"
grafana_2          | logger=migrator t=2022-02-15T23:29:11.81+0000 lvl=info msg="migrations completed" performed=0 skipped=383 duration=571.073µs
grafana_2          | logger=migrator t=2022-02-15T23:29:11.81+0000 lvl=info msg="Unlocking database"
grafana_2          | Failed to start grafana. error: Datasource provisioning error: trying to update old version of datasource                                 
grafana_2          | Datasource provisioning error: trying to update old version of datasource                                                                 
grafana_2          | logger=provisioning t=2022-02-15T23:29:11.9+0000 lvl=eror msg="Failed to provision data sources" error="Datasource provisioning error: try
ing to update old version of datasource"                                                                                                                       

grafana_1          | logger=sqlstore t=2022-02-15T23:29:13.13+0000 lvl=info msg="Connecting to DB" dbtype=mysqlWithHooks 
grafana_1          | logger=migrator t=2022-02-15T23:29:13.14+0000 lvl=info msg="Locking database"
grafana_1          | logger=migrator t=2022-02-15T23:29:13.14+0000 lvl=info msg="Starting DB migrations"
grafana_1          | logger=migrator t=2022-02-15T23:29:13.15+0000 lvl=info msg="migrations completed" performed=0 skipped=383 duration=397.253µs
grafana_1          | logger=migrator t=2022-02-15T23:29:13.15+0000 lvl=info msg="Unlocking database"

grafana_2          | logger=sqlstore t=2022-02-15T23:29:15.34+0000 lvl=info msg="Connecting to DB" dbtype=mysqlWithHooks
grafana_2          | logger=migrator t=2022-02-15T23:29:15.35+0000 lvl=info msg="Locking database"
grafana_2          | logger=migrator t=2022-02-15T23:29:15.35+0000 lvl=info msg="Starting DB migrations"
grafana_2          | logger=migrator t=2022-02-15T23:29:15.36+0000 lvl=info msg="migrations completed" performed=0 skipped=383 duration=430.478µs
grafana_2          | logger=migrator t=2022-02-15T23:29:15.36+0000 lvl=info msg="Unlocking database"
```
</details>

<details><summary>Postgres log output</summary>

```bash
grafana_2      | logger=sqlstore t=2022-02-15T23:17:22.62+0000 lvl=info msg="Connecting to DB" dbtype=postgresWithHooks
grafana_2      | logger=migrator t=2022-02-15T23:17:22.63+0000 lvl=info msg="Locking database"
grafana_2      | logger=migrator t=2022-02-15T23:17:22.64+0000 lvl=info msg="Starting DB migrations"

grafana_1      | logger=sqlstore t=2022-02-15T23:17:22.65+0000 lvl=info msg="Connecting to DB" dbtype=postgresWithHooks
grafana_1      | logger=migrator t=2022-02-15T23:17:22.66+0000 lvl=info msg="Locking database"
grafana_1      | logger=migrator t=2022-02-15T23:17:22.66+0000 lvl=eror msg="Failed to lock database" error="failed to obtain lock"
grafana_1      | Failed to start grafana. error: failed to obtain lock
grafana_1      | failed to obtain lock

grafana_3      | logger=sqlstore t=2022-02-15T23:17:22.68+0000 lvl=info msg="Connecting to DB" dbtype=postgresWithHooks
grafana_3      | logger=migrator t=2022-02-15T23:17:22.68+0000 lvl=info msg="Locking database"
grafana_3      | logger=migrator t=2022-02-15T23:17:22.68+0000 lvl=eror msg="Failed to lock database" error="failed to obtain lock"
grafana_3      | Failed to start grafana. error: failed to obtain lock
grafana_3      | failed to obtain lock

grafana_1      | logger=sqlstore t=2022-02-15T23:17:23.5+0000 lvl=info msg="Connecting to DB" dbtype=postgresWithHooks
grafana_1      | logger=migrator t=2022-02-15T23:17:23.52+0000 lvl=info msg="Locking database"
grafana_1      | logger=migrator t=2022-02-15T23:17:23.52+0000 lvl=eror msg="Failed to lock database" error="failed to obtain lock"
grafana_1      | Failed to start grafana. error: failed to obtain lock
grafana_1      | failed to obtain lock

grafana_3      | logger=sqlstore t=2022-02-15T23:17:23.5+0000 lvl=info msg="Connecting to DB" dbtype=postgresWithHooks
grafana_3      | logger=migrator t=2022-02-15T23:17:23.53+0000 lvl=info msg="Locking database"
grafana_3      | logger=migrator t=2022-02-15T23:17:23.53+0000 lvl=eror msg="Failed to lock database" error="failed to obtain lock"
grafana_3      | Failed to start grafana. error: failed to obtain lock
grafana_3      | failed to obtain lock

grafana_2      | logger=migrator t=2022-02-15T23:17:23.82+0000 lvl=info msg="migrations completed" performed=387 skipped=0 duration=1.175171317s
grafana_2      | logger=migrator t=2022-02-15T23:17:23.82+0000 lvl=info msg="Unlocking database"

grafana_1      | logger=sqlstore t=2022-02-15T23:17:24.5+0000 lvl=info msg="Connecting to DB" dbtype=postgresWithHooks
grafana_1      | logger=migrator t=2022-02-15T23:17:24.52+0000 lvl=info msg="Locking database"
grafana_1      | logger=migrator t=2022-02-15T23:17:24.52+0000 lvl=info msg="Starting DB migrations"
grafana_1      | logger=migrator t=2022-02-15T23:17:24.53+0000 lvl=info msg="migrations completed" performed=0 skipped=383 duration=639.313µs
grafana_1      | logger=migrator t=2022-02-15T23:17:24.53+0000 lvl=info msg="Unlocking database"

grafana_3      | logger=sqlstore t=2022-02-15T23:17:24.5+0000 lvl=info msg="Connecting to DB" dbtype=postgresWithHooks
grafana_3      | logger=migrator t=2022-02-15T23:17:24.52+0000 lvl=info msg="Locking database"
grafana_3      | logger=migrator t=2022-02-15T23:17:24.52+0000 lvl=eror msg="Failed to lock database" error="failed to obtain lock"
grafana_3      | Failed to start grafana. error: failed to obtain lock
grafana_3      | failed to obtain lock

grafana_3      | logger=sqlstore t=2022-02-15T23:17:25.33+0000 lvl=info msg="Connecting to DB" dbtype=postgresWithHooks
grafana_3      | logger=migrator t=2022-02-15T23:17:25.35+0000 lvl=info msg="Locking database"
grafana_3      | logger=migrator t=2022-02-15T23:17:25.35+0000 lvl=info msg="Starting DB migrations"
grafana_3      | logger=migrator t=2022-02-15T23:17:25.36+0000 lvl=info msg="migrations completed" performed=0 skipped=383 duration=496.051µs
grafana_3      | logger=migrator t=2022-02-15T23:17:25.36+0000 lvl=info msg="Unlocking database"
```
</details>
