### PR TITLE
Dashboards: Fix so that empty folders can be deleted from the manage dashboards/folders page

### LINKED ISSUE #42486: Unable to delete empty folders on Grafana dashboards
@darrenjaneczek and I found what we think is a bug. 

Scenario: we are trying to delete an empty folder _Dashboards > Manage_. 

1. Select checkbox for empty folder
2. Observe: _Delete_ and _Move_ buttons do not appear. 

Please see attached video for more details. 

https://user-images.githubusercontent.com/86840333/143937050-0f98df6b-7f38-44b2-bd88-9e31c93141cd.mp4

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- there is no way to currently delete an empty folder. this is because `canDelete` is currently based on `canMove`, and `canMove` is only true if a dashboard is selected.
- change the logic so `canDelete` is enabled if **anything** is selected. this allows us to select empty folders, and also allows us to delete folders before they've been expanded.
- add a new unit test to make sure we can delete empty folders

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/42486

**Special notes for your reviewer**:

- we should probably hold off on merging this until the release is complete 😱

### CODE REVIEW

**Review by Clarity-89 — APPROVED** [review]
Nice catch, works as expected 🎉   Could we also update the text copy for delete warning as it doesn't seem to account for singular folder case properly?
Screenshot 2021-12-01 at 10 46 20

File: public/app/features/search/hooks/useManageDashboards.ts [hunk 1]
```diff
@@ -42,14 +42,13 @@ export const useManageDashboards = (
     dispatch({ type: MOVE_ITEMS, payload: { dashboards: selectedDashboards, folder } });
   };
 
-  const canMove = useMemo(() => results.some((result) => result.items && result.items.some((item) => item.checked)), [
-    results,
-  ]);
+  const canMove = useMemo(() => results.some((result) => result.items.some((item) => item.checked)), [results]);
 
   const canDelete = useMemo(() => {
+    const somethingChecked = results.some((result) => result.checked || result.items.some((item) => item.checked));
```
Comment (hugohaggmark) [inline public/app/features/search/hooks/useManageDashboards.ts:48]: nit: I wonder if it would be worth to flatten everything and check for checked because using `.some` in another `.some` isn't super readable. I know I've been part of adding to this complexity in the past 🙈   I guess as long we have good tests for these cases its not super important. 🤔

**Review by hugohaggmark — APPROVED** [review]
Looks good but I haven't had the chance to test it out (yet)

File: public/app/features/search/hooks/useManageDashboards.ts (hunk 1 above)
Comment (ashharrison90) [reply public/app/features/search/hooks/useManageDashboards.ts]: @hugohaggmark yeah agreed it's not super readable, but also didn't wanna flatten as that means we definitely have to go through the entire array. when using list view that means looping an array containing every dashboard that exists in your instance 😬  whereas with the `.some` it shortcircuits that loop as soon as it finds one. 

have moved the logic into a separate mini function instead. wdyt? 🤔

Comment (hugohaggmark) [reply public/app/features/search/hooks/useManageDashboards.ts]: You're right! Looks better as a separate function.

**Comment by ashharrison90** [comment]
> Nice catch, works as expected 🎉 Could we also update the text copy for delete warning as it doesn't seem to account for singular folder case properly? Screenshot 2021-12-01 at 10 46 20

@Clarity-89 i don't think this is easily possible as there's currently no real way to distinguish between an empty folder (`items: []`), and a folder that just hasn't been expanded yet to fetch the inner dashboards (`items: []`). we could maybe make a call to the backend on deletion of a single folder to check if it's really empty or not, but i'm erring on the side of the more generic error message for simplicity. wdyt? 🤔

**Comment by Clarity-89** [comment]
> > Nice catch, works as expected 🎉 Could we also update the text copy for delete warning as it doesn't seem to account for singular folder case properly? Screenshot 2021-12-01 at 10 46 20
> 
> @Clarity-89 i don't think this is easily possible as there's currently no real way to distinguish between an empty folder (`items: []`), and a folder that just hasn't been expanded yet to fetch the inner dashboards (`items: []`). we could maybe make a call to the backend on deletion of a single folder to check if it's really empty or not, but i'm erring on the side of the more generic error message for simplicity. wdyt? 🤔

Just to clarify, if only one folder is selected, the message should say `Do you want to delete the selected folder and all its dashboards and alerts?` instead of `Do you want to delete the selected folder and all their dashboards and alerts?`. The logic to detect if multiple dashboards are selected is already there, it just needs to be applied to this string.

**Comment by ashharrison90** [comment]
> 

@Clarity-89 ahhhhh gotcha, that we can probably do. 👍  i thought you were referring to the `dashboards and alerts` bit 🤦
