### PR TITLE
API: Fix redirect issues

### LINKED ISSUE #22227: Redirect loop following login after visiting /grafana, but not for /grafana/
**What happened**:
I ended up in a redirect loop. The loop occur between `https://example.local/grafana` and `https://example.local/grafana/login`, and occur after an initial visit to `/grafana` and the initial login to `/grafana/login`.

**What you expected to happen**:
To continue from a successful login at `/grafana` or `/grafana/` that renders to the Grafana home screen.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy Grafana using [the charts/stable Grafana Helm chart](https://github.com/helm/charts/tree/master/stable/grafana).

2. Configure the Helm chart like this, but with a valid domain name
```yaml
adminUser: admin
adminPassword: tmp-password

image:
  # This contains a recent fix not yet released from PR #21652 regarding use of sub paths
  repository: grafana/grafana-dev
  tag: master-0e2d874ecf9277dcc17d562e05271917efc8b595

grafana.ini:
  server:
    domain: example.local
    root_url: 'http://%(domain)s/grafana'
    # also tried: 'http://%(domain)s/grafana/'
    serve_from_sub_path: true
    enforce_domain: false
    enable_gzip: true
    router_logging: true
```

3. Visit http://example.local/grafana, then login after redirect to `/grafana/login` and login.

**Anything else we need to know?**:
My investigation and thoughts:
- The `redirect_to` cookie is set to `/grafana` (`%2Fgrafana`) or `/grafana/` (`%2Fgrafana%2F`) on a visit to `http://example.local/grafana` (no trailing `/`) or `http://example.local/grafana/` (with trailing `/`). This is probably fine as it is.
- The real issue and where to fix it as I see it, is that for a logged in user, it should not matter if I visit `/grafana` or `/grafana/`, both requests should be treated by the Webservers home screen handler for the authenticated user.
- I used Okta authentication (OpenID Connect / OAuth2) when I logged in, and I had HTTPS instead of HTTP, with TLS termination managed by a nginx-ingress-controller in kubernetes, but I don't think this matters.

**Environment**:
- Grafana version: unreleased, pre 6.6.2
- OS Grafana is installed on: an official docker image of grafana/grafana-dev
- User OS & Browser: chrome
- Grafana plugins: none
- Others:

### LINKED ISSUE #22461: Nginx not redirecting to Dashboards even Auth Proxy is enabled
**What happened**:
I'm running Grafana behind Nginx reverse-proxy and enabled Auth Proxy and created a dashboard in it and trying to iframe the dashboard and added custom validation to validate the user using the token.
Token validation is happening and request is going to grafana through the Auth Proxy but the dashboard is not showing instead it is redirected to Home dashboard.
even after login is successful, when the request hit to grafana dashboard it will be redirected to grafana home dashboard. 
**What you expected to happen**:
Grafana Dashboard should show instead of a Home dashboard.
**How to reproduce it (as minimally and precisely as possible)**:
following is my Nginx configuration:
worker_processes 1;

events { worker_connections 20000; }

http {
log_format compression '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $upstream_addr '
        '"$http_referer" "$http_user_agent" "$gzip_ratio"';
resolver       8.8.8.8 8.8.4.4 ;
server {
    listen 80;
    large_client_header_buffers 4 64k;

    location  /graph/org/ {
        add_header X_REQUEST_TOKEN $token;
        auth_request      /validatetoken;
        set $uid $arg_uid;
        set $dashboard $arg_dashboard;
        set $orgid $arg_orgid;
        set $from $arg_from;
        set $to $arg_to;

        if ($arg_solo = "true"){
                rewrite "^/graph/org(.*)?$" "/grafana/d-solo/$uid/$dashboard?orgId=1&var-orgid=$orgid&theme=light&kiosk&from=$from&to=$to" last;
        }

        if ($arg_solo = "false"){
                rewrite "^/graph/org(.*)$" "/grafana/d/$uid/$dashboard?orgId=1&var-orgid=$orgid&theme=light&kiosk&from=$from&to=$to" last;
        }

    }

    location = /validatetoken {
        internal;
        set $token '';
        if ($request_uri ~* "([^/]*$)" ) {
          set  $token  $1;
        }
        proxy_pass        http://backenapp.test.com/validatetoken?token=$token;
        proxy_pass_request_body off;
        proxy_set_header X-Original-URI $request_uri;
    }

    location  /grafana {
        set $grafana_user "raman";
        proxy_pass         http://grafana.test.com/;
        proxy_set_header X-WEBAUTH-USER $grafana_user;
        proxy_set_header Authorization "";
     }
  }
}

and below is Auth Proxy configuration:
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = false
# Deprecated, use sync_ttl instead
ldap_sync_ttl = 60
sync_ttl = 60
whitelist =
headers =
enable_login_token = true

I'm hitting following URL:
http://reverseproxy.test.com/graph/org/MTU4Mjc3NDY1MToxNWZmYTI3YmM4MjI3MDQzNjVmOTkxZjI5MDU3OWQ4Mg==?uid=QfbI3XUZk&dashboard=sample-dashboard&orgid=00776ca5-2ef8-4e8d-8d1d&from=now-7d&to=now&solo=false

can anyone please help me understand why this is happening or what I did wrong?

as if I directly try to open the rewritten URL then I can see the dashboard. 
i.e. http://reverseproxy.test.com/grafana/d/QfbI3XUZk/sample-dashboard?orgId=1&var-orgid=00776ca5-2ef8-4e8d-8d1d&theme=light&kiosk&from=now-7d&to=now

**Anything else we need to know?**:

**Environment**:
- Grafana version: Latest Grafana Docker Image
- Data source type & version:
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:

The 6.6.1 has the following issues:
- In [this](https://github.com/grafana/grafana/pull/21057) modification I had made the wrong assumption that the appSubUrl does not include the leading slash. As a result the redirect validation is not correct. In addition to this, validation should not consider correct paths like `/<appSubUrl>blahblah`.
- Frontend prepends the subpath to redirects in addition to the backend (`/grafana` ends up to `/grafana/grafana`)

[This](https://github.com/grafana/grafana/pull/21652) fix addresses the above issues by [removing](https://github.com/grafana/grafana/pull/21652/files#diff-c6731ee8c1631796c076df9ae9e4d2c7R50) the subpath from redirects in the backend.
However it does not work optimally when redirects occur in the backend before reaching the frontend ([like in the OAuth flow](https://github.com/grafana/grafana/issues/22227)) because the session cookie path is set to `appSubUrl/` and requests without the appSubUrl can not read it.

[This](https://github.com/grafana/grafana/pull/22265/) fixes the above issue by removing the trailing slash from the cookie path.

The reason for this is that addresses the causes of the problem instead of the symptoms.

This PR:
- [X] Reverts [this](https://github.com/grafana/grafana/pull/22265/) (#22671)
- [X] Fixes redirect validation and tests (#22675)
- [X] Modifies the backend and the frontend to prepend the appSubUrl only if it’s missing from the redirect URL (#22676)
- [X] Validates the redirect URL in OAuth login (#22677)
- [X] Fixes login view if `redirect_to` value is invalid but the user is authenticated so as the user is navigated to the home page instead of rendering login page with error. (#22678)

**Which issue(s) this PR fixes**:

Fixes #22227
Fixes #22461

**Special notes for your reviewer**:

I have tested it with  the following scenarios:
- with subpath `/grafana`:
    - base auth:
        - [X] Dashboard URL (http://localhost:3000/grafana/d/dFcV-J4Zz/16707?orgId=1)
        - [X] http://localhost:3000/grafana/
        - [X] http://localhost:3000/grafana
        - [X] http://localhost:3000/grafanagrafana
    - oauth:
        - [X] Dashboard URL (http://localhost:3000/grafana/d/dFcV-J4Zz/16707?orgId=1)
        - [X] http://localhost:3000/grafana/
        - [X] http://localhost:3000/grafana
        - [X] http://localhost:3000/grafanagrafana

- without subpath:
    - base auth:
        - [X]  Dashboard URL (http://localhost:3000/d/dFcV-J4Zz/16707?orgId=1)
        - [X] http://localhost:3000/
        - [X] http://localhost:3000
        - [X] http://localhost:3000/grafanagrafana
    - oauth:
        - [X]  Dashboard URL (http://localhost:3000/d/dFcV-J4Zz/16707?orgId=1)
        - [X] http://localhost:3000/
        - [X] http://localhost:3000
        - [X] http://localhost:3000/grafanagrafana

### CODE REVIEW

File: pkg/api/login.go [hunk 1]
```diff
@@ -35,9 +35,7 @@ func (hs *HTTPServer) validateRedirectTo(redirectTo string) error {
 	if to.IsAbs() {
 		return login.ErrAbsoluteRedirectTo
 	}
-	// when using a subUrl, the redirect_to should have a relative or absolute path that includes the subUrl, otherwise the redirect
-	// will send the user to the wrong location
-	if hs.Cfg.AppSubUrl != "" && !strings.HasPrefix(to.Path, hs.Cfg.AppSubUrl) && !strings.HasPrefix(to.Path, "/"+hs.Cfg.AppSubUrl) {
+	if hs.Cfg.AppSubUrl != "" && !strings.HasPrefix(to.Path, hs.Cfg.AppSubUrl+"/") {
```
Comment (kylebrandt) [inline pkg/api/login.go]: Add comment explaining logic here.

File: pkg/api/login_oauth.go [hunk 2]
```diff
@@ -217,9 +217,12 @@ func (hs *HTTPServer) OAuthLogin(ctx *m.ReqContext) {
 	metrics.MApiLoginOAuth.Inc()
 
 	if redirectTo, _ := url.QueryUnescape(ctx.GetCookie("redirect_to")); len(redirectTo) > 0 {
-		middleware.DeleteCookie(ctx.Resp, "redirect_to", hs.cookieOptionsFromCfg)
-		ctx.Redirect(redirectTo)
-		return
+		if err := hs.validateRedirectTo(redirectTo); err == nil {
+			middleware.DeleteCookie(ctx.Resp, "redirect_to", hs.cookieOptionsFromCfg)
```
Comment (kylebrandt) [inline pkg/api/login_oauth.go]: happen to understand this enough to add a comment explaining why the cookie is deleted?

**Comment by kylebrandt** [comment]
Don't understand this enough to approve it, but an exemplar pull request message :-)

File: pkg/api/login.go (hunk 1 above)
Comment (briangann) [reply pkg/api/login.go]: looks like comment was removed...

File: pkg/api/login_oauth.go (hunk 2 above)
Comment (briangann) [reply pkg/api/login_oauth.go]: the cookie is no longer needed since it held the redirect_to location.  this code path is going to send the browser to the new location, and should not retain the redirect_to cookie (could end up in a redirect loop, but mainly it is no longer needed).

**Review by briangann — DISMISSED** [review]
looks great!

File: pkg/api/login_oauth.go (hunk 2 above)
Comment (papagian) [reply pkg/api/login_oauth.go]: exactly; the cookie is deleted because it's has fulfilled its purpose.

File: pkg/api/login.go (hunk 1 above)
Comment (papagian) [reply pkg/api/login.go]: I have put back the comment

**Comment by consideRatio** [comment]
I have not fully understood the details here, but I think it makes sense to use the logic from #22265 alongside this PR that allows cookies to be passed along to `/grafana/` and `/grafana` paths and not only the former. My example for why I think so is the following.

- Assume I have a grafana_session cookie already, but without #22265's logic, it's path value remains at `/grafana/` as I understand it, because I don't think this PR influence the `grafana_session` cookie's path value.
- Assume I visit `mydomain.org/grafana`, then my `grafana_session` cookie isn't passed along because I didn't include a trailing `/` in my host header, so I get redirected to /login instead of directly visiting Grafana's root path even though I'm already logged in.

Thanks for working on this!

**Comment by papagian** [comment]
> I have not fully understood the details here, but I think it makes sense to use the logic from #22265 alongside this PR that allows cookies to be passed along to `/grafana/` and `/grafana` paths and not only the former. My example for why I think so is the following.
> 
> * Assume I have a grafana_session cookie already, but without #22265's logic, it's path value remains at `/grafana/` as I understand it, because I don't think this PR influence the `grafana_session` cookie's path value.

In that case, [this](https://github.com/grafana/grafana/blob/ab3d7fe56e49f856dd999e1b279ad94f2a5ce35f/pkg/api/login.go#L92) validation returns error and the redirect_to cookie is ignored and delete it and the logged in user is navigated to the home page.

> * Assume I visit `mydomain.org/grafana`, then my `grafana_session` cookie isn't passed along because I didn't include a trailing `/` in my host header, so I get redirected to /login instead of directly visiting Grafana's root path even though I'm already logged in.
> 

This is true.

> Thanks for working on this!

@consideRatio 
Your concerns are fair and I want also to test your modifications on top of these. I'm only a bit reluctant changing the cookie path from what is used to be until today because we had faced a number of issues related to cookie handling and there can be some cases we can't think of right now.

It's also a bit concerning that two different people have difficulty understanding the modifications in this PR therefore I would love some feedback from anybody with better insight than me.

**Comment by papagian** [comment]
> > * Assume I visit `mydomain.org/grafana`, then my `grafana_session` cookie isn't passed along because I didn't include a trailing `/` in my host header, so I get redirected to /login instead of directly visiting Grafana's root path even though I'm already logged in.
> 
> This is true.

I have pushed a modification for fixing this.

**Comment by consideRatio** [comment]
> > > * Assume I visit `mydomain.org/grafana`, then my `grafana_session` cookie isn't passed along because I didn't include a trailing `/` in my host header, so I get redirected to /login instead of directly visiting Grafana's root path even though I'm already logged in.
> > 
> > 
> > This is true.
> 
> I have pushed a modification for fixing this.

The fix will still make `/grafana?and=query-params` redirect to `/grafana/login`, but from `/grafana/login`, it will realize that the redirect_to cookie specifies that it should go to `/grafana` instead of `/grafana/`, so it will say "no! this is invalid" and then assume the user wants to go to `/grafana/` where the authentication cookie is actually passed along.

It makes a visit to `/grafana` a bit less invalid, but it still disrupts the user by bounces that truncates potential query parameters.

> Your concerns are fair and I want also to test your modifications on top of these. I'm only a bit reluctant changing the cookie path from what is used to be until today because we had faced a number of issues related to cookie handling and there can be some cases we can't think of right now.

This is the key discussion in my mind. Cookie handling is indeed a delicate and complicated matter. I have never really felt confident about them, but after the references you found I've started to feel that I understand them somewhat. That makes me want to tackle the question if the change suggested in #22265 going to cause issues head on. If it isn't going to cause issues, it would actually solve the issue I described above with the workaround in 4e52076 and remove the need to bounce the user to `/home/login` once just to get redirected a place where the cookie is passed.

File: public/app/core/components/Login/LoginCtrl.tsx [hunk 3]
```diff
@@ -104,9 +104,17 @@ export class LoginCtrl extends PureComponent<Props, State> {
     const params = this.props.routeParams;
     // Use window.location.href to force page reload
     if (params.redirect && params.redirect[0] === '/') {
-      window.location.href = config.appSubUrl + params.redirect;
+      if (config.appSubUrl !== '' && !params.redirect.startsWith(config.appSubUrl)) {
```
Comment (marefr) [inline public/app/core/components/Login/LoginCtrl.tsx]: Do we need frontend logic at all for redirect, couldn't the backend make sure to always return the correct url? Wait why are we using redirect query param here - thought we always had redirect in cookie?

**Review by marefr — COMMENTED** [review]
Sorry being late to the party. I probably lack a lot of context, but added some comments/questions.

File: pkg/middleware/auth.go [hunk 4]
```diff
@@ -47,7 +47,11 @@ func notAuthorized(c *m.ReqContext) {
 		return
 	}
 
-	WriteCookie(c.Resp, "redirect_to", url.QueryEscape(c.Req.RequestURI), 0, newCookieOptions)
+	redirectTo := c.Req.RequestURI
+	if setting.AppSubUrl != "" && !strings.HasPrefix(redirectTo, setting.AppSubUrl) {
```
[the remark this answers is not in the document]
Comment (papagian) [reply pkg/middleware/auth.go]: > Why doesn't c.Req.RequestURI include AppSubUrl?

As far as I understand, the user can request whatever URL.
For instance, the user can request `http://localhost:3000` even though the subpath is `/grafana`.

In addition to this, we always prepended the subpath before [this](https://github.com/grafana/grafana/commit/a7f96ea98e34da8253f7bb071ae6e2bf7435e7b0#diff-c6731ee8c1631796c076df9ae9e4d2c7) change which was introduced for fixing [this](https://github.com/grafana/grafana/pull/21652#issuecomment-582601735) problematic situation.

Probably now that we have validation for the redirects (and if it's working correctly) we no more need to prepend it
because [invalid redirect paths are ignored](4e52076b9dc8c312b2b9323621274a6b0de45601).
But I think it's safer to keep it here, since it appends it only if it's missing.

**Review by marefr — APPROVED** [review]
A: Logout scenario with anonymous auth disabled:
1. Login 
2. Browse dashboard X
3. Clear cookies
4. Refresh browser. Should be redirected to login page
5. Login 
6. Should be redirected to dashboard X

B: Anonymous scenario:
1. Browse dashboard X
2. Click on login in sidemenu and redirect to login page
3. Login 
4. Should be redirected to dashboard X

Root url default without sub path using Grafana auth:
A: Works as expected
B: Works as expected

Root url default without sub path using OAuth:
A: Works as expected
**B: No, redirected to home page**

Root url http://localhost:3000/grafana with serve_from_sub_path using Grafana auth:
A: Works as expected
B: Works as expected

Root url http://localhost:3000/grafana with serve_from_sub_path using OAuth:
A: Works as expected
**B: No, redirected to home page**

Root url http://grafana.myproxy.com:10080/grafana without serve_from_sub_path using nginx and Grafana auth:
A: Works as expected
B: Works as expected

Root url http://grafana.myproxy.com:10080/grafana without serve_from_sub_path using nginx and OAuth:
A: Works as expected
**B: No, redirected to home page**

Also confirmed this resolves #22227

@papagian Not sure if B scenario using OAuth is a new or existing regression? We could create a new issue if there's no existing one and fix that for 6.7 stable maybe?

**Comment by papagian** [comment]
> @papagian Not sure if B scenario using OAuth is a new or existing regression? We could create a new issue if there's no existing one and fix that for 6.7 stable maybe?

I was able to reproduce it in 6.5.2 and 6.6.2 and therefore I have filed a new [issue](https://github.com/grafana/grafana/issues/22709)
