### PR TITLE
NodeGraph: Fix overlaps preventing opening an edge context menu when nodes were too close

### LINKED ISSUE #59733: Node Graph edge ContextMenu will not open if source and target nodes are positioned too closed by
**What happened**: On a Node Graph, when two nodes are too close toghether, trying to open the edge ContextMenu is impossible because it always open one of the nodes ContextMenu

Near nodes (bug):
image

Far nodes (works as expected)
image

**What you expected to happen**: When clicking on an edge (and maybe more precisely the edge main stat box), I expect it to always open the edge ContextMenu, not the node ContextMenu.

**How to reproduce it (as minimally and precisely as possible)**: Create NodeGraph panel, pull Test Data DB with Node Graph scenario data type response. Then try opening edge ContextMenu for edge between the yellow and green nodes on the left 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.0
- Data source type & version: Test Data DB
- OS Grafana is installed on: Debian 1
- User OS & Browser: Ubuntu 20.04 Chrome 107.0.5304.121
- Grafana plugins: Test Data DB datasource
- Others:

### PR DESCRIPTION
**Pull request by aocenas**
Fixes https://github.com/grafana/grafana/issues/59733

Problem was the hover and click events were registered on the whole node group svg element and on hover we make the labels bigger (to show full labels on hover in case they are longer than the node width). This meant the clicks on edges could get obscured by the larger label rectangles (which may not be actually visible):

Screenshot 2023-05-16 at 17 29 18

The white rectangles are the large label boxes, the red rectangles are areas that will react on click and hover after this PR.

### CODE REVIEW

File: public/app/plugins/panel/nodeGraph/Node.tsx [hunk 1]
```diff
@@ -108,6 +95,27 @@ export const Node = memo(function Node(props: {
...
+        onMouseLeave={() => {
+          onMouseLeave(node.id);
+        }}
+        onClick={(event) => {
+          onClick(event, node);
+        }}
+        style={{
+          fill: 'none',
+          stroke: 'none',
+          pointerEvents: 'fill',
```
Comment (joey-grafana) [inline public/app/plugins/panel/nodeGraph/Node.tsx:112]: nit: these could be moved into getStyles.

**Review by joey-grafana — APPROVED** [review]
LGTM 👍 

Note: The milestone should be set to `10.1.x` and then in the PR that is created for the backport the milestone should be `10.0.x`
