### PR TITLE
A11y: Make tabs in query history + inspector accessible in Explore

### LINKED ISSUE #46477: A11y : Cannot reach tabs inside Inspector / Query History via keyboard
**Steps to reproduce**:

Tabs inside Inspector / Query History are not reachable by keyboard

**Actual Result**:

Basic functionality is lost for users who rely on keyboard navigation

**Expected Result**

Tabs should be accessible via keyboard navigation

**Relevant WCAG Criteria:**

[2.1.1 Keyboard - Level A](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=335%2C332#keyboard)

**Environment**:
- Grafana version: 8.4.3
- Data source type & version:
- User OS & Browser:
- Others:

### PR DESCRIPTION
**Pull request by L-M-K-B**
Fixes #46477 

**ToDo:**
- [x]  make tabs accessible
- [ ]  make slider for time range accessible (query history tab)
- [x]  make tab content accessible

Open task will be solved separately. See issue #53776

### CODE REVIEW

File: packages/grafana-ui/src/components/Slider/RangeSlider.tsx [hunk 1]
```diff
@@ -47,6 +47,7 @@ export const RangeSlider: FunctionComponent<RangeSliderProps> = ({
         onAfterChange={onAfterChange}
         vertical={!isHorizontal}
         reverse={reverse}
+        tabIndex={[0, 1]}
```
Comment (Elfo404) [inline packages/grafana-ui/src/components/Slider/RangeSlider.tsx:50]: what does this solve?

AFAIK this sets the tabIndex of the second handler to 1, which means users, after focusing the first handler, would have to tab all the way through the end of the page (or all the way through elements that have a tabindex != 0) to focus the second one.

if the slider ha some weird behavior, i'd fix it separtely in https://github.com/grafana/grafana/issues/53776 and focus on the tab component on this PR

**Review by Elfo404 — CHANGES_REQUESTED** [review]

File: packages/grafana-ui/src/components/Slider/RangeSlider.tsx (hunk 1 above)
Comment (L-M-K-B) [reply packages/grafana-ui/src/components/Slider/RangeSlider.tsx:50]: I am aware that this can only be a temporary solution but for now it's making the rest of the tab content accessible. Otherwise the search bar as well as the list of queries would continue not to be accessible by keyboard until I found a solution for the slider.

Comment (Elfo404) [reply packages/grafana-ui/src/components/Slider/RangeSlider.tsx:50]: then do you mind adding a  TODO/FIXME comment in the code specifying it's a temporary workaround and why?

**Comment by Elfo404** [comment]
Please either change the milestone if you don't want to backport this, or if you want this to be in the next patch release add the related backport label (`backport 9.1.x`)

File: packages/grafana-ui/src/components/Slider/RangeSlider.tsx (hunk 1 above)
Comment (L-M-K-B) [reply packages/grafana-ui/src/components/Slider/RangeSlider.tsx:51]: No, I don't mind. Done.

**Review by Elfo404 — APPROVED** [review]
🔥
