### PR TITLE
SQL Datasources: Use health check for config test

### LINKED ISSUE #52521: MySQL: Return meaningful error message based on SQLState
There are situations when the error comes back as error 9999. We can't figure out what goes wrong. When this PR gets released we might give more meaningful error message based on the SQLState. https://github.com/go-sql-driver/mysql/pull/1321

See the issue described here https://community.grafana.com/t/unable-to-connect-to-azure-mysql-database-as-data-source/22084

### PR DESCRIPTION
**Pull request by zoltanbedi**
**What is this feature?**

This PR changes the way we test the connection in the datasource config page for the SQL datasources by calling the health endpoint instead of manually creating a query. ~With this change we can return all the error messages instead of showing a general one. This PR also bumps the mysql go driver to https://github.com/go-sql-driver/mysql/releases/tag/v1.7.0 so now it returns the sql state as part of the error.~

### TODO:

- [x] Remove the bump for the go-mysql-driver. Do that in a separate pr.
- [x] Figure out if we can return error messages or if we shouldn't expose them publicly.

### CODE REVIEW

File: pkg/tsdb/sqleng/sql_engine.go [hunk 1]
```diff
@@ -849,7 +853,7 @@ func convertSQLTimeColumnToEpochMS(frame *data.Frame, timeIndex int) error {
 
 	origin := frame.Fields[timeIndex]
 	valueType := origin.Type()
-	if valueType == data.FieldTypeTime || valueType == data.FieldTypeNullableTime {
+	if valueType == data.FieldTypeTime || valueType == data.FieldTypeNullableTime || valueType == data.FieldTypeNullableString {
```
Comment (mdvictor) [inline pkg/tsdb/sqleng/sql_engine.go:856]: Why do we need this here? Is it for scenarios where a 'time' column is represented as a string date? If so, should we also add `data.FieldTypeString` there?

**Review by mdvictor — CHANGES_REQUESTED** [review]
LGTM. Tested all 3 SQL datasources successfully! 

I am only curious to better understand the `convertSQLTimeColumnToEpochMS` function valueType situation

File: pkg/tsdb/sqleng/sql_engine.go (hunk 1 above)
Comment (zoltanbedi) [reply pkg/tsdb/sqleng/sql_engine.go:856]: I should have commented on this. This was needed because of the bump of go-sql-driver/mysql. They changed how the unsigned types returns.

**Review by mdvictor — APPROVED** [review]

**Comment by zoltanbedi** [comment]
@marefr what do you think about this? Does it make sense to expose the error message for the config pages?

**Comment by marefr** [comment]
Going to ask @xnyo to review this since he started looking into #60244

File: pkg/tsdb/mssql/mssql.go [hunk 2]
```diff
@@ -193,6 +193,23 @@ func (t *mssqlQueryResultTransformer) TransformQueryError(logger log.Logger, err
...
+	dsHandler, err := s.getDataSourceHandler(req.PluginContext)
+	if err != nil {
+		return nil, err
+	}
+
+	err = dsHandler.Ping()
+
+	if err != nil {
+		logger.Error("Check health failed", "error", err)
+		return &backend.CheckHealthResult{Status: backend.HealthStatusError, Message: err.Error()}, nil
```
Comment (marefr) [inline pkg/tsdb/mssql/mssql.go:207]: For security reasons you should probably call TransformQueryError. Applicable to all sql datasources

File: pkg/tsdb/mysql/mysql.go [hunk 3]
```diff
@@ -134,6 +134,24 @@ func (s *Service) getDataSourceHandler(pluginCtx backend.PluginContext) (*sqleng
...
+		return nil, err
+	}
+
+	err = dsHandler.Ping()
+
+	var driverErr *mysql.MySQLError
+	if errors.As(err, &driverErr) {
+		logger.Error("Check health failed", "error", err)
+		return &backend.CheckHealthResult{Status: backend.HealthStatusError, Message: driverErr.Message}, nil
+	}
```
Comment (xnyo) [inline pkg/tsdb/mysql/mysql.go:150]: You should also handle `err != nil` when it's not `As mysql.MySQLError`:

```suggestion
	if err != nil {
		logger.Error("Check health failed", "error", err)
		var driverErr *mysql.MySQLError
		if errors.As(err, &driverErr) {
			return &backend.CheckHealthResult{Status: backend.HealthStatusError, Message: driverErr.Message}, nil
		}
		return &backend.CheckHealthResult{Status: backend.HealthStatusError, Message: err.Error()}, nil
	}
```

:point_up:  Here in my suggestion also consider `TransformQueryError` instead of `err.Error()` as suggested by @marefr

**Review by xnyo — CHANGES_REQUESTED** [review]
Awesome! :clap::clap::clap:
Just one thing to change regarding error handling  in mysql and probably the other suggestion by Marcus:

**Comment by zoltanbedi** [comment]
> also consider TransformQueryError instead of err.Error() as suggested

My initial problem that I wanted to solve with this is to give back error messages to the users who set up their datasources so they don't have to look for the log files. I understand that it might expose information about the db that can be used by an attacker. 
My thinking was that if I separate the query call from the test datasource call by using the health check I can show errors to admins who set up datasources but not for users who queries them. 
Thinking about it now the checkhealth call can probably be called from anywhere so this way we would cause security threat again.

Would that maybe make sense if we would limit that the health check call can be only called from the datasource settings page? @marefr @xnyo

**Comment by zoltanbedi** [comment]
I think I'm also going to remove the bump for the mysql-go-driver and just focus on the healthcheck call with this pr.

**Comment by marefr** [comment]
> Would that maybe make sense if we would limit that the health check call can be only called from the datasource settings page?

@zoltanbedi no I'm afraid not it doesn't matter. In Grafana Cloud we cannot trust administrators - they can use this as a way to port/host scan the network.

**Comment by zoltanbedi** [comment]
Thanks for your input @marefr I'll change the code then.

File: pkg/tsdb/mssql/mssql.go [hunk 4]
```diff
@@ -209,8 +209,8 @@ func (s *Service) CheckHealth(ctx context.Context, req *backend.CheckHealthReque
 	err = dsHandler.Ping()
 
 	if err != nil {
-		logger.Error("Check health failed", "error", err)
-		return &backend.CheckHealthResult{Status: backend.HealthStatusError, Message: err.Error()}, nil
+		transformer := mssqlQueryResultTransformer{}
```
Comment (xnyo) [inline pkg/tsdb/mssql/mssql.go:212]: Rather than instantiating the transformer here, I would export `DataSourceHandler.transformQueryError` and use that one instead, like this:

https://github.com/grafana/grafana/blob/ab25ce18f46d5ad89f08899a26cb52721e2f570e/pkg/tsdb/sqleng/sql_engine.go#L110

:point_down: 

```go
func (e *DataSourceHandler) TransformQueryError(logger log.Logger, err error) error {
```

And the commented line becomes:

```go
transformer := dsHandler.TransformQueryError()
```

Because the correct query result transformer is already passed to `NewQueryDataHandler`:

https://github.com/grafana/grafana/blob/ab25ce18f46d5ad89f08899a26cb52721e2f570e/pkg/tsdb/sqleng/sql_engine.go#L124

e.g.: 

https://github.com/grafana/grafana/blob/ab25ce18f46d5ad89f08899a26cb52721e2f570e/pkg/tsdb/mssql/mssql.go#L101-L103

Also, `DataSourceHandler.transformQueryError` hides `net.Op` errors as well, which is neat.

(The same also would apply for mysql and postgres)

What do you think?

**Review by xnyo — CHANGES_REQUESTED** [review]
Thanks for addressing that! :smile:  I have left a suggestion:

File: pkg/tsdb/mssql/mssql.go (hunk 4 above)
Comment (zoltanbedi) [reply pkg/tsdb/mssql/mssql.go]: Thanks for your review @xnyo, I addressed the changes you asked for.

**Review by xnyo — APPROVED** [review]
Thanks for addressing! LGTM :+1: :tada:
