### PR TITLE
Annotations: Change indices and rewrites annotation find query to improve database query performance

### LINKED ISSUE #21902: Queries against Large Numbers of Annotations can overload/lock MySQL
**What happened**:

MySQL database locks up on Annotation query when there are a large (millions) of annotation rows. Grafana-Server subsequently fails as it loses access to its database.

**What you expected to happen**:

Queries that don't have to scan the entire table, and lock up the db.

**How to reproduce it (as minimally and precisely as possible)**:

Unhappy Query:

```sql
MySQL [hg_redacted]> select id,text from annotation where org_id=1 and epoch<=unix_timestamp(now())*1000 and epoch_end>=unix_timestamp(now())*1000-60*10
^CCtrl-C -- query killed. Continuing normally.
ERROR 1317 (70100): Query execution was interrupted
MySQL [hg_redacted]> explain select id,text from annotation where org_id=1 and epoch<=unix_timestamp(now())*1000 and epoch_end>=unix_timestamp(now())*10
+----+-------------+------------+------------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------+---------+-------+---------+--
| id | select_type | table      | partitions | type | possible_keys                                                                                                                                                                                 | key                            | key_len | ref   | rows    | f
+----+-------------+------------+------------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------+---------+-------+---------+--
|  1 | SIMPLE      | annotation | NULL       | ref  | IDX_annotation_org_id_alert_id,IDX_annotation_org_id_type,IDX_annotation_org_id_dashboard_id_panel_itation_org_id_created,IDX_annotation_org_id_updated,IDX_annotation_org_id_epoch_epoch_end | IDX_annotation_org_id_alert_id | 8       | const | 2102754 |
+----+-------------+------------+------------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------+---------+-------+---------+--
1 row in set, 1 warning (0.037 sec)

MySQL [hg_redacted]> explain select id,text from annotation where org_id=1 and epoch<=unix_timestamp(now())*1000 and epoch_end>=unix_timestamp(now())*10
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: annotation
   partitions: NULL
         type: ref
possible_keys: IDX_annotation_org_id_alert_id,IDX_annotation_org_id_type,IDX_annotation_org_id_dashboard_id_panel_id_epoch,IDX_annotation_org_id_epoch,IDX
          key: IDX_annotation_org_id_alert_id
      key_len: 8
          ref: const
         rows: 2102754
     filtered: 11.11
        Extra: Using where
1 row in set, 1 warning (0.002 sec)

MySQL [hg_redacted]> show create table annotation;
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| Table      | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| annotation | CREATE TABLE `annotation` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `org_id` bigint(20) NOT NULL,
  `alert_id` bigint(20) DEFAULT NULL,
  `user_id` bigint(20) DEFAULT NULL,
  `dashboard_id` bigint(20) DEFAULT NULL,
  `panel_id` bigint(20) DEFAULT NULL,
  `category_id` bigint(20) DEFAULT NULL,
  `type` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `text` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `metric` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `prev_state` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
  `new_state` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
  `data` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `epoch` bigint(20) NOT NULL,
  `region_id` bigint(20) DEFAULT '0',
  `tags` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created` bigint(20) DEFAULT '0',
  `updated` bigint(20) DEFAULT '0',
  `epoch_end` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `IDX_annotation_org_id_alert_id` (`org_id`,`alert_id`),
  KEY `IDX_annotation_org_id_type` (`org_id`,`type`),
  KEY `IDX_annotation_org_id_dashboard_id_panel_id_epoch` (`org_id`,`dashboard_id`,`panel_id`,`epoch`),
  KEY `IDX_annotation_org_id_epoch` (`org_id`,`epoch`),
  KEY `IDX_annotation_org_id_created` (`org_id`,`created`),
  KEY `IDX_annotation_org_id_updated` (`org_id`,`updated`),
  KEY `IDX_annotation_org_id_epoch_epoch_end` (`org_id`,`epoch`,`epoch_end`)
) ENGINE=InnoDB AUTO_INCREMENT=12444472 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci |
```

**Environment**:

Introduced I think in 6.4.x by #17673 

**TODO**:

 - [ ] Figure out index and/or query options that fix this above query to a reasonable about of rows
 - [ ] Come up with some other queries likely to come out of https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/annotation.go#L122 , and make sure that they also have acceptable performance plans.
- [ ] Implement necessary migrations for the above.

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
Drop indices and create new ones and rewrites annotation find query 
to address performance issues when querying annotation table and 
there is a large amount of rows.

The query is used in the following cases:
- [Panel alert tab](https://github.com/grafana/grafana/blob/master/public/app/features/alerting/AlertTabCtrl.ts#L96)
- [Alert state history](https://github.com/grafana/grafana/blob/master/public/app/features/alerting/StateHistory.tsx#L27)
- [Dashboard](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/grafana/datasource.ts#L83)
- [Alert list](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/alertlist/module.ts#L126)
- [Annotations list panel](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/annolist/AnnoListPanel.tsx#L101) **We haven't optimised the indices for this one since its an alpha plugin.**

**Which issue(s) this PR fixes**:
Fixes #21902

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/sqlstore/migrations/annotation_mig.go [hunk 1]
```diff
@@ -123,7 +123,21 @@ func addAnnotationMig(mg *Migrator) {
...
+		Cols: []string{"org_id", "dashboard_id", "panel_id", "epoch"}, Type: IndexType,
+	}))
+
+	mg.AddMigration("Add index for org_id_dashboard_id_epoch_epoch_end on annotation table", NewAddIndexMigration(table, &Index{
+		Cols: []string{"org_id", "dashboard_id", "epoch", "epoch_end"}, Type: IndexType,
+	}))
+
+	mg.AddMigration("Add index for org_id_dashboard_id_panel_id on annotation table", NewAddIndexMigration(table, &Index{
+		Cols: []string{"org_id", "dashboard_id", "panel_id"}, Type: IndexType,
+	}))
```
Comment (DanCech) [inline pkg/services/sqlstore/migrations/annotation_mig.go]: Why do we need this index?  It would only ever be used when querying annotations for a specific panel with no time range, as soon as you have a time range the index above is preferable.

File: pkg/services/sqlstore/migrations/annotation_mig.go [hunk 2]
```diff
@@ -123,7 +123,21 @@ func addAnnotationMig(mg *Migrator) {
...
+		Cols: []string{"org_id", "epoch"}, Type: IndexType,
+	}))
+
+	mg.AddMigration("Remove index org_id_dashboard_id_panel_id_epoch on annotation table", NewDropIndexMigration(table, &Index{
+		Cols: []string{"org_id", "dashboard_id", "panel_id", "epoch"}, Type: IndexType,
+	}))
+
+	mg.AddMigration("Add index for org_id_dashboard_id_epoch_epoch_end on annotation table", NewAddIndexMigration(table, &Index{
+		Cols: []string{"org_id", "dashboard_id", "epoch", "epoch_end"}, Type: IndexType,
+	}))
```
Comment (DanCech) [inline pkg/services/sqlstore/migrations/annotation_mig.go]: Have you tested this against an index with epoch_end before epoch?

File: pkg/services/sqlstore/migrations/annotation_mig.go (hunk 1 above)
Comment (marefr) [reply pkg/services/sqlstore/migrations/annotation_mig.go]: This use case is for [alert state history](https://github.com/grafana/grafana/blob/master/public/app/features/alerting/StateHistory.tsx#L27) filtering on org id, dashboard and panel id.

File: pkg/services/sqlstore/migrations/annotation_mig.go (hunk 2 above)
Comment (marefr) [reply pkg/services/sqlstore/migrations/annotation_mig.go]: We're working on it why this is a WIP. Do you mean having the epoch_end before epoch in the index?

Comment (DanCech) [reply pkg/services/sqlstore/migrations/annotation_mig.go]: Yes, maybe I wasn't clear in the issue.  The query looks for rows with `epoch_end > From` and `epoch < To`, in most cases there will be far fewer rows with `epoch_end > From` than `epoch < To` so the index will be more efficient if `epoch_end` is before `epoch`.

File: pkg/services/sqlstore/migrations/annotation_mig.go (hunk 1 above)
Comment (DanCech) [reply pkg/services/sqlstore/migrations/annotation_mig.go]: Ok

**Comment by papagian** [comment]
> * [Panel alert tab](https://github.com/grafana/grafana/blob/master/public/app/features/alerting/AlertTabCtrl.ts#L96)
> * [Alert state history](https://github.com/grafana/grafana/blob/master/public/app/features/alerting/StateHistory.tsx#L27)

The generated query for the above two cases is:

```
SELECT \
    annotation.id, \
    annotation.epoch as time, \
    annotation.epoch_end as time_end, \
    annotation.dashboard_id, \
    annotation.panel_id, \
    annotation.new_state, \
    annotation.prev_state, \
    annotation.alert_id, \
    annotation.text, \
    annotation.tags, \
    annotation.data, \
    annotation.created, \
    annotation.updated, \
    usr.email, \
    usr.login, \
    alert.name as alert_name \
FROM annotation \
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id \
LEFT OUTER JOIN alert on alert.id = annotation.alert_id \
WHERE annotation.org_id = <org_id> \
AND annotation.dashboard_id = <dashboard_id> \
AND annotation.panel_id = <panel_id> \
AND annotation.alert_id > 0
```

**Comment by papagian** [comment]
> * [Dashboard](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/grafana/datasource.ts#L83)

The generated queries for this one can be:

```
SELECT \
    annotation.id, \
    annotation.epoch as time, \
    annotation.epoch_end as time_end, \
    annotation.dashboard_id, \
    annotation.panel_id, \
    annotation.new_state, \
    annotation.prev_state, \
    annotation.alert_id, \
    annotation.text, \
    annotation.tags, \
    annotation.data, \
    annotation.created, \
    annotation.updated, \
    usr.email, \
    usr.login, \
    alert.name as alert_name \
FROM annotation \
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id \
LEFT OUTER JOIN alert on alert.id = annotation.alert_id \
WHERE annotation.org_id = 1 \
AND annotation.epoch <= <timestamp> AND annotation.epoch_end >= <timestamp> \
AND annotation.dashboard_id = <dashboard_id>;
```

or 
```
SELECT \
    annotation.id, \
    annotation.epoch as time, \
    annotation.epoch_end as time_end, \
    annotation.dashboard_id, \
    annotation.panel_id, \
    annotation.new_state, \
    annotation.prev_state, \
    annotation.alert_id, \
    annotation.text, \
    annotation.tags, \
    annotation.data, \
    annotation.created, \
    annotation.updated, \
    usr.email, \
    usr.login, \
    alert.name as alert_name \
FROM annotation \
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id \
LEFT OUTER JOIN alert on alert.id = annotation.alert_id \
WHERE annotation.org_id = 1 \
AND annotation.epoch <= <timestamp> AND annotation.epoch_end >= <timestamp> \
AND (
    SELECT SUM(1) FROM annotation_tag at
        INNER JOIN tag on tag.id = at.tag_id
        WHERE at.annotation_id = annotation.id
        AND (
            tag.key = <tag_key> OR tag.value = <tag_value>
        )
) > 0;
```
or
```
SELECT \
    annotation.id, \
    annotation.epoch as time, \
    annotation.epoch_end as time_end, \
    annotation.dashboard_id, \
    annotation.panel_id, \
    annotation.new_state, \
    annotation.prev_state, \
    annotation.alert_id, \
    annotation.text, \
    annotation.tags, \
    annotation.data, \
    annotation.created, \
    annotation.updated, \
    usr.email, \
    usr.login, \
    alert.name as alert_name \
FROM annotation \
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id \
LEFT OUTER JOIN alert on alert.id = annotation.alert_id \
WHERE annotation.org_id = 1 \
AND annotation.epoch <= <timestamp> AND annotation.epoch_end >= <timestamp> \
AND (
    SELECT SUM(1) FROM annotation_tag at
        INNER JOIN tag on tag.id = at.tag_id
        WHERE at.annotation_id = annotation.id
        AND (
            tag.key = <tag_key> OR tag.value = <tag_value>
        )
) = <tag_length>;
```

**Comment by papagian** [comment]
> * Alert list

**Comment by papagian** [comment]
> * [](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/grafana/datasource.ts#L83)
> * [Alert list](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/alertlist/module.ts#L126)

The generated queries for this one can be:

```
SELECT \
    annotation.id, \
    annotation.epoch as time, \
    annotation.epoch_end as time_end, \
    annotation.dashboard_id, \
    annotation.panel_id, \
    annotation.new_state, \
    annotation.prev_state, \
    annotation.alert_id, \
    annotation.text, \
    annotation.tags, \
    annotation.data, \
    annotation.created, \
    annotation.updated, \
    usr.email, \
    usr.login, \
    alert.name as alert_name \
FROM annotation \
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id \
LEFT OUTER JOIN alert on alert.id = annotation.alert_id \
WHERE annotation.org_id = 1 \
AND annotation.epoch <= <timestamp> AND annotation.epoch_end >= <timestamp> \
AND annotation.alert_id > 0 \
ORDER BY epoch DESC LIMIT <limit>;
```
or

```
SELECT \
    annotation.id, \
    annotation.epoch as time, \
    annotation.epoch_end as time_end, \
    annotation.dashboard_id, \
    annotation.panel_id, \
    annotation.new_state, \
    annotation.prev_state, \
    annotation.alert_id, \
    annotation.text, \
    annotation.tags, \
    annotation.data, \
    annotation.created, \
    annotation.updated, \
    usr.email, \
    usr.login, \
    alert.name as alert_name \
FROM annotation \
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id \
LEFT OUTER JOIN alert on alert.id = annotation.alert_id \
WHERE annotation.org_id = 1 \
AND annotation.epoch <= <timestamp> AND annotation.epoch_end >= <timestamp> \
AND annotation.alert_id = 0 \
ORDER BY epoch DESC LIMIT <limit>;
```
or

```
SELECT \
    annotation.id, \
    annotation.epoch as time, \
    annotation.epoch_end as time_end, \
    annotation.dashboard_id, \
    annotation.panel_id, \
    annotation.new_state, \
    annotation.prev_state, \
    annotation.alert_id, \
    annotation.text, \
    annotation.tags, \
    annotation.data, \
    annotation.created, \
    annotation.updated, \
    usr.email, \
    usr.login, \
    alert.name as alert_name \
FROM annotation \
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id \
LEFT OUTER JOIN alert on alert.id = annotation.alert_id \
WHERE annotation.org_id = 1 \
AND annotation.epoch <= <timestamp> AND annotation.epoch_end >= <timestamp> \
AND annotation.alert_id > 0 \
AND annotation.dashboard_id = <dashboard_id> \
ORDER BY epoch DESC LIMIT <limit>;

```
or

```
SELECT \
    annotation.id, \
    annotation.epoch as time, \
    annotation.epoch_end as time_end, \
    annotation.dashboard_id, \
    annotation.panel_id, \
    annotation.new_state, \
    annotation.prev_state, \
    annotation.alert_id, \
    annotation.text, \
    annotation.tags, \
    annotation.data, \
    annotation.created, \
    annotation.updated, \
    usr.email, \
    usr.login, \
    alert.name as alert_name \
FROM annotation \
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id \
LEFT OUTER JOIN alert on alert.id = annotation.alert_id \
WHERE annotation.org_id = 1 \
AND annotation.epoch <= <timestamp> AND annotation.epoch_end >= <timestamp> \
AND annotation.alert_id = 0 \
AND annotation.dashboard_id = <dashboard_id> \
ORDER BY epoch DESC LIMIT <limit>;
```

**Review by DanCech — APPROVED** [review]

File: pkg/services/sqlstore/annotation.go [hunk 3]
```diff
@@ -223,7 +225,7 @@ func (r *SqlAnnotationRepo) Find(query *annotations.ItemQuery) ([]*annotations.I
 		query.Limit = 100
 	}
 
-	sql.WriteString(" ORDER BY epoch DESC" + dialect.Limit(query.Limit))
+	sql.WriteString(" ORDER BY a.org_id, a.epoch_end DESC, a.epoch DESC" + dialect.Limit(query.Limit) + " ) dt on dt.id = annotation.id")
```
Comment (kylebrandt) [inline pkg/services/sqlstore/annotation.go]:
```suggestion
	// order of ORDER BY arguments match the order of a sql index for performance 
	sql.WriteString(" ORDER BY a.org_id, a.epoch_end DESC, a.epoch DESC" + dialect.Limit(query.Limit) + " ) dt on dt.id = annotation.id")
```

**Comment by marefr** [comment]
>  * [Panel alert tab](https://github.com/grafana/grafana/blob/master/public/app/features/alerting/AlertTabCtrl.ts#L96)
>  * [Alert state history](https://github.com/grafana/grafana/blob/master/public/app/features/alerting/StateHistory.tsx#L27)

The generated query (using updated query) for the above two cases is:

```sql
SELECT
  annotation.id,
  annotation.epoch as time,
  annotation.epoch_end as time_end,
  annotation.dashboard_id,
  annotation.panel_id,
  annotation.new_state,
  annotation.prev_state,
  annotation.alert_id,
  annotation.text,
  annotation.tags,
  annotation.data,
  annotation.created,
  annotation.updated,
  usr.email,
  usr.login,
  alert.name as alert_name
FROM annotation
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id
LEFT OUTER JOIN alert on alert.id = annotation.alert_id
INNER JOIN (
  SELECT a.id from annotation a
    WHERE a.org_id = <org_id>
    AND a.dashboard_id = <dashboard_id>
    AND a.panel_id = <panel_id>
    AND a.alert_id > 0
    ORDER BY a.org_id, a.epoch_end DESC a.epoch DESC LIMIT <limit>
) dt 
ON dt.id = annotation.id
```

> * [Dashboard](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/grafana/datasource.ts#L83)

The generated queries (using updated query) for this one can be:

```sql
SELECT
  annotation.id,
  annotation.epoch as time,
  annotation.epoch_end as time_end,
  annotation.dashboard_id,
  annotation.panel_id,
  annotation.new_state,
  annotation.prev_state,
  annotation.alert_id,
  annotation.text,
  annotation.tags,
  annotation.data,
  annotation.created,
  annotation.updated,
  usr.email,
  usr.login,
  alert.name as alert_name
FROM annotation
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id
LEFT OUTER JOIN alert on alert.id = annotation.alert_id
INNER JOIN (
  SELECT a.id from annotation a
    WHERE a.org_id = <org_id>
    AND a.epoch <= <timestamp> AND a.epoch_end >= <timestamp>
    AND a.dashboard_id = <dashboard_id>
  ORDER BY a.org_id, a.epoch_end DESC a.epoch DESC LIMIT <limit>
) dt 
ON dt.id = annotation.id
```

or 
```sql
SELECT
    annotation.id,
    annotation.epoch as time,
    annotation.epoch_end as time_end,
    annotation.dashboard_id,
    annotation.panel_id,
    annotation.new_state,
    annotation.prev_state,
    annotation.alert_id,
    annotation.text,
    annotation.tags,
    annotation.data,
    annotation.created,
    annotation.updated,
    usr.email,
    usr.login,
    alert.name as alert_name
FROM annotation
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id
LEFT OUTER JOIN alert on alert.id = annotation.alert_id
INNER JOIN (
  SELECT a.id from annotation a
  WHERE a.org_id = <org_id>
  AND a.epoch <= <timestamp> AND a.epoch_end >= <timestamp>
  AND (
    SELECT SUM(1) FROM annotation_tag at
      INNER JOIN tag on tag.id = at.tag_id
    WHERE at.annotation_id = a.id
    AND (
      tag.key = "<tag_key>" OR tag.value = "<tag_value>"
    )
  ) > 0 
  ORDER BY a.org_id, a.epoch_end DESC a.epoch DESC LIMIT <limit>
) dt 
ON dt.id = annotation.id
```
or
```sql
SELECT
  annotation.id,
  annotation.epoch as time,
  annotation.epoch_end as time_end,
  annotation.dashboard_id,
  annotation.panel_id,
  annotation.new_state,
  annotation.prev_state,
  annotation.alert_id,
  annotation.text,
  annotation.tags,
  annotation.data,
  annotation.created,
  annotation.updated,
  usr.email,
  usr.login,
  alert.name as alert_name
FROM annotation
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id
LEFT OUTER JOIN alert on alert.id = annotation.alert_id
INNER JOIN (
  SELECT a.id from annotation a
  WHERE a.org_id = <org_id>
  AND a.epoch <= <timestamp> AND a.epoch_end >= <timestamp>
  AND (
    SELECT SUM(1) FROM annotation_tag at
      INNER JOIN tag on tag.id = at.tag_id
    WHERE at.annotation_id = annotation.id
      AND (
        tag.key = "<tag_key>" OR tag.value = "<tag_value>"
      )
  ) = <tag_length> 
  ORDER BY a.org_id, a.epoch_end DESC a.epoch DESC LIMIT <limit>
) dt 
ON dt.id = annotation.id
```

> * [](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/grafana/datasource.ts#L83)
> * [Alert list](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/alertlist/module.ts#L126)

The generated queries (using update query) for this one can be:

```sql
SELECT
  annotation.id,
  annotation.epoch as time,
  annotation.epoch_end as time_end,
  annotation.dashboard_id,
  annotation.panel_id,
  annotation.new_state,
  annotation.prev_state,
  annotation.alert_id,
  annotation.text,
  annotation.tags,
  annotation.data,
  annotation.created,
  annotation.updated,
  usr.email,
  usr.login,
  alert.name as alert_name
FROM annotation
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id
LEFT OUTER JOIN alert on alert.id = annotation.alert_id
INNER JOIN (
  SELECT a.id from annotation a
  WHERE a.org_id = <org_id>
  AND a.epoch <= <timestamp> AND a.epoch_end >= <timestamp>
  AND a.alert_id > 0
  ORDER BY a.org_id, a.epoch_end DESC a.epoch DESC LIMIT <limit>
) dt 
ON dt.id = annotation.id
```
or

```sql
SELECT
  annotation.id,
  annotation.epoch as time,
  annotation.epoch_end as time_end,
  annotation.dashboard_id,
  annotation.panel_id,
  annotation.new_state,
  annotation.prev_state,
  annotation.alert_id,
  annotation.text,
  annotation.tags,
  annotation.data,
  annotation.created,
  annotation.updated,
  usr.email,
  usr.login,
  alert.name as alert_name
FROM annotation
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id
LEFT OUTER JOIN alert on alert.id = annotation.alert_id
INNER JOIN (
  SELECT a.id from annotation a
  WHERE a.org_id = <org_id>
  AND a.epoch <= <timestamp> AND a.epoch_end >= <timestamp>
  AND a.alert_id = 0
  ORDER BY a.org_id, a.epoch_end DESC a.epoch DESC LIMIT <limit>
) dt 
ON dt.id = annotation.id
```
or

```sql
SELECT
  annotation.id,
  annotation.epoch as time,
  annotation.epoch_end as time_end,
  annotation.dashboard_id,
  annotation.panel_id,
  annotation.new_state,
  annotation.prev_state,
  annotation.alert_id,
  annotation.text,
  annotation.tags,
  annotation.data,
  annotation.created,
  annotation.updated,
  usr.email,
  usr.login,
  alert.name as alert_name
FROM annotation
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id
LEFT OUTER JOIN alert on alert.id = annotation.alert_id
INNER JOIN (
  SELECT a.id from annotation a
  WHERE a.org_id = <org_id>
  AND a.epoch <= <timestamp> AND a.epoch_end >= <timestamp>
  AND a.alert_id > 0
  AND a.dashboard_id = <dashboard_id>
  ORDER BY a.org_id, a.epoch_end DESC a.epoch DESC LIMIT <limit>
) dt 
ON dt.id = annotation.id

```
or

```sql
SELECT
  annotation.id,
  annotation.epoch as time,
  annotation.epoch_end as time_end,
  annotation.dashboard_id,
  annotation.panel_id,
  annotation.new_state,
  annotation.prev_state,
  annotation.alert_id,
  annotation.text,
  annotation.tags,
  annotation.data,
  annotation.created,
  annotation.updated,
  usr.email,
  usr.login,
  alert.name as alert_name
FROM annotation
LEFT OUTER JOIN user as usr on usr.id = annotation.user_id
LEFT OUTER JOIN alert on alert.id = annotation.alert_id
INNER JOIN (
  SELECT a.id from annotation a
  WHERE a.org_id = <org_id>
  AND a.epoch <= <timestamp> AND a.epoch_end >= <timestamp>
  AND a.alert_id = 0
  AND a.dashboard_id = <dashboard_id>
  ORDER BY a.org_id, a.epoch_end DESC a.epoch DESC LIMIT <limit>
) dt 
ON dt.id = annotation.id
```

File: pkg/services/sqlstore/annotation.go (hunk 3 above)
Comment (papagian) [reply pkg/services/sqlstore/annotation.go]: @marefr what is the performance for other queries where another index is picked instead of `IDX_annotation_org_id_epoch_end_epoch`
maybe we need to change the ordering by according to the index (the where condition)

Comment (marefr) [reply pkg/services/sqlstore/annotation.go]: Using `IDX_annotation_org_id_dashboard_id_epoch_end_epoch`

```
PANEL ALERT TAB:
SELECT   annotation.id,   annotation.epoch as time,   annotation.epoch_end as time_end,   annotation.dashboard_id,   annotation.panel_id,   annotation.new_state,   annotation.prev_state,   annotation.alert_id,   annotation.text,   annotation.tags,   annotation.data,   annotation.created,   annotation.updated,   usr.email,   usr.login,   alert.name as alert_name FROM annotation LEFT OUTER JOIN user as usr on usr.id = annotation.user_id LEFT OUTER JOIN alert on alert.id = annotation.alert_id INNER JOIN (   SELECT a.id from annotation a     WHERE a.org_id = 1     AND a.dashboard_id = 78 and a.panel_id=2     AND a.alert_id > 0     ORDER BY a.org_id, a.epoch_end DESC, a.epoch DESC LIMIT 50 ) dt  ON dt.id = annotation.id;
50 rows in set (0.00 sec)

explain SELECT   annotation.id,   annotation.epoch as time,   annotation.epoch_end as time_end,   annotation.dashboard_id,   annotation.panel_id,   annotation.new_state,   annotation.prev_state,   annotation.alert_id,   annotation.text,   annotation.tags,   annotation.data,   annotation.created,   annotation.updated,   usr.email,   usr.login,   alert.name as alert_name FROM annotation LEFT OUTER JOIN user as usr on usr.id = annotation.user_id LEFT OUTER JOIN alert on alert.id = annotation.alert_id INNE
+----+-------------+------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------+-----------------------------+-------+----------------------------------------------------+
| id | select_type | table      | type   | possible_keys                                                                                                                                                                                                  | key                                                | key_len | ref                         | rows  | Extra                                              |
+----+-------------+------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------+-----------------------------+-------+----------------------------------------------------+
|  1 | PRIMARY     | <derived2> | ALL    | NULL                                                                                                                                                                                                           | NULL                                               | NULL    | NULL                        |    50 | NULL                                               |
|  1 | PRIMARY     | annotation | eq_ref | PRIMARY                                                                                                                                                                                                        | PRIMARY                                            | 8       | dt.id                       |     1 | NULL                                               |
|  1 | PRIMARY     | usr        | ALL    | PRIMARY                                                                                                                                                                                                        | NULL                                               | NULL    | NULL                        |     1 | Using where; Using join buffer (Block Nested Loop) |
|  1 | PRIMARY     | alert      | eq_ref | PRIMARY                                                                                                                                                                                                        | PRIMARY                                            | 8       | grafana.annotation.alert_id |     1 | NULL                                               |
|  2 | DERIVED     | a          | ref    | IDX_annotation_org_id_alert_id,IDX_annotation_org_id_type,IDX_annotation_org_id_created,IDX_annotation_org_id_updated,IDX_annotation_org_id_dashboard_id_epoch_end_epoch,IDX_annotation_org_id_epoch_end_epoch | IDX_annotation_org_id_dashboard_id_epoch_end_epoch | 17      | const,const                 | 29068 | Using where                                        |
+----+-------------+------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------+-----------------------------+-------+----------------------------------------------------+
```

**Comment by marefr** [comment]
## Load test results

### Setup

- Used the [ha_test](https://github.com/grafana/grafana/tree/master/devenv/docker/ha_test)
- Used and added the number generator from https://stackoverflow.com/a/9751493.
- [Provisioned 100 alert rules/dashboards](https://github.com/grafana/grafana/tree/master/devenv/docker/ha_test#provision-alert-dashboards-with-alert-rules) using `./alerts.sh provision -a 100 -c 20` which creates 200 annotations, 100 pending, 100 alerting
- Changed alert condition `./alerts.sh provision -a 100 -c 100` to make alerts transition to OK which creates 100 annotations
- Based on these 300 annotations I generated 1,5 million annotations with 10 minutes difference each step going backward:
  - v6.6.0 and this branch: `insert into annotation (org_id, alert_id, user_id, dashboard_id, panel_id, category_id, type, title, text, metric, prev_state, new_state, data, epoch, region_id, tags, created, updated, epoch_end) 
select at.org_id, at.alert_id, at.user_id, at.dashboard_id, at.panel_id, at.category_id, at.type, at.title, at.text, at.metric, at.prev_state, at.new_state, at.data, at.epoch -(n*600000), at.region_id, at.tags, at.created, at.updated, at.epoch_end - (n*600000) from annotation at cross join generator_64k WHERE n > 0 AND n <= 5000\g` 
  - v6.3.7: `insert into annotation (org_id, alert_id, user_id, dashboard_id, panel_id, category_id, type, title, text, metric, prev_state, new_state, data, epoch, region_id, tags, created, updated)  select at.org_id, at.alert_id, at.user_id, at.dashboard_id, at.panel_id, at.category_id, at.type, at.title, at.text, at.metric, at.prev_state, at.new_state, at.data, at.epoch -(n*600000), at.region_id, at.tags, at.created, at.updated from annotation at cross join generator_64k WHERE n > 0 AND n <= 5000;`
- Then running annotation_by_tag_test load test for 5 minutes and using 200 concurrent users

### v6.3.7
<details><summary>Details</summary>

```bash
> ./run.sh -d 5m -v 200 -c annotations_by_tag_test -u http://grafana.loc

          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     output: -
     script: src/annotations_by_tag_test.js

    duration: 5m0s, iterations: -
         vus: 200,  max: 200

    done [==========================================================] 5m0s / 5m0s

    █ annotation by tag test

      █ user authenticates thru ui with username and password

        ✓ response status is 200
        ✓ response has cookie 'grafana_session' with 32 characters

      █ batch tsdb requests with annotations by tag

        ✗ response status is 200
         ↳  99% — ✓ 39999 / ✗ 1

    checks.....................: 99.99% ✓ 40399 ✗ 1
    data_received..............: 546 MB 1.8 MB/s
    data_sent..................: 14 MB  48 kB/s
    group_duration.............: avg=21.78s   min=134.87ms med=23.35s   max=46.48s   p(90)=29.45s  p(95)=31.4s
    http_req_blocked...........: avg=569.08µs min=1.34µs   med=4.49µs   max=222.78ms p(90)=10.17µs p(95)=32.75µs
    http_req_connecting........: avg=541.68µs min=0s       med=0s       max=222.68ms p(90)=0s      p(95)=0s
    http_req_duration..........: avg=2.05s    min=2.83ms   med=629.55ms max=46.29s   p(90)=3.32s   p(95)=7.59s
    http_req_receiving.........: avg=4.38ms   min=24.6µs   med=904.97µs max=251.85ms p(90)=8.55ms  p(95)=16.71ms
    http_req_sending...........: avg=187.92µs min=7.3µs    med=26.12µs  max=350.09ms p(90)=50.85µs p(95)=100.47µs
    http_req_tls_handshaking...: avg=0s       min=0s       med=0s       max=0s       p(90)=0s      p(95)=0s
    http_req_waiting...........: avg=2.05s    min=2.46ms   med=623.86ms max=46.29s   p(90)=3.31s   p(95)=7.58s
    http_reqs..................: 44344  147.8133/s
    iteration_duration.........: avg=26.7s    min=5.18µs   med=28.28s   max=51.48s   p(90)=34.54s  p(95)=36.53s
    iterations.................: 2135   7.116665/s
    vus........................: 200    min=200 max=200
    vus_max....................: 200    min=200 max=200
```
image
image
image
image

</details>

### v6.6.0
<details><summary>Details</summary>

```bash
> ./run.sh -d 5m -v 200 -c annotations_by_tag_test -u http://grafana.loc

          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     output: -
     script: src/annotations_by_tag_test.js

    duration: 15m0s, iterations: -
         vus: 200,   max: 200

    done [==========================================================] 5m0.3s / 15m0s

    █ annotation by tag test

      █ user authenticates thru ui with username and password

        ✓ response has cookie 'grafana_session' with 32 characters
        ✓ response status is 200

      █ batch tsdb requests with annotations by tag

        ✗ response status is 200
         ↳  86% — ✓ 3608 / ✗ 552

    checks.....................: 87.89% ✓ 4008  ✗ 552
    data_received..............: 49 MB  165 kB/s
    data_sent..................: 2.6 MB 8.6 kB/s
    group_duration.............: avg=47.51s   min=622.61ms med=1m0s     max=3m48s   p(90)=1m51s    p(95)=1m59s
    http_req_blocked...........: avg=26.89ms  min=1.43µs   med=4.37µs   max=2.55s   p(90)=2.89ms   p(95)=16.96ms
    http_req_connecting........: avg=26.36ms  min=0s       med=0s       max=2.55s   p(90)=2.45ms   p(95)=15.89ms
    http_req_duration..........: avg=35.07s   min=13.79ms  med=38.14s   max=1m2s    p(90)=1m0s     p(95)=1m0s
    http_req_receiving.........: avg=801.75µs min=18.01µs  med=149.15µs max=69.79ms p(90)=1.45ms   p(95)=3.14ms
    http_req_sending...........: avg=17.06ms  min=6.78µs   med=24.79µs  max=2.51s   p(90)=138.96µs p(95)=606.14µs
    http_req_tls_handshaking...: avg=0s       min=0s       med=0s       max=0s      p(90)=0s       p(95)=0s
    http_req_waiting...........: avg=35.05s   min=13.59ms  med=38.13s   max=1m2s    p(90)=1m0s     p(95)=1m0s
    http_reqs..................: 7786   25.924376/s
    iteration_duration.........: avg=50.77s   min=2.62s    med=1m5s     max=3m47s   p(90)=1m55s    p(95)=2m3s
    iterations.................: 404    1.345164/s
    vus........................: 200    min=200 max=200
    vus_max....................: 200    min=200 max=200
```
image
image
image

</details>

### Changes in this branch
<details><summary>Details</summary>

```bash
> ./run.sh -d 5m -v 200 -c annotations_by_tag_test -u http://grafana.loc

          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     output: -
     script: src/annotations_by_tag_test.js

    duration: 5m0s, iterations: -
         vus: 200,  max: 200

    done [==========================================================] 5m0s / 5m0s

    █ annotation by tag test

      █ user authenticates thru ui with username and password

        ✓ response status is 200
        ✓ response has cookie 'grafana_session' with 32 characters

      █ batch tsdb requests with annotations by tag

        ✗ response status is 200
         ↳  96% — ✓ 73768 / ✗ 3012

    checks.....................: 96.09% ✓ 74168 ✗ 3012
    data_received..............: 1.1 GB 3.8 MB/s
    data_sent..................: 27 MB  90 kB/s
    group_duration.............: avg=9.81s    min=10.13ms  med=10.42s  max=19.57s   p(90)=16.42s   p(95)=17.06s
    http_req_blocked...........: avg=129.94µs min=1.2µs    med=4.43µs  max=206.99ms p(90)=11.81µs  p(95)=21.55µs
    http_req_connecting........: avg=84.54µs  min=0s       med=0s      max=58.06ms  p(90)=0s       p(95)=0s
    http_req_duration..........: avg=2.56s    min=617.49µs med=1.92s   max=18.28s   p(90)=5.69s    p(95)=7.41s
    http_req_receiving.........: avg=140.72ms min=16.47µs  med=4.79ms  max=2.71s    p(90)=427.76ms p(95)=799.37ms
    http_req_sending...........: avg=132.09µs min=6.31µs   med=26.01µs max=323.71ms p(90)=65.82µs  p(95)=127.22µs
    http_req_tls_handshaking...: avg=0s       min=0s       med=0s      max=0s       p(90)=0s       p(95)=0s
    http_req_waiting...........: avg=2.42s    min=567.58µs med=1.8s    max=18.28s   p(90)=5.44s    p(95)=7.05s
    http_reqs..................: 80925  269.749846/s
    iteration_duration.........: avg=14.89s   min=2.11µs   med=15.5s   max=24.58s   p(90)=21.48s   p(95)=22.12s
    iterations.................: 3893   12.976659/s
    vus........................: 200    min=200 max=200
    vus_max....................: 200    min=200 max=200
```
image
image
image

</details>

### Summary 
Version | HTTP requests total | HTTP requests/s
--- | --- | ---
v6.3.7 | 44344  |  ~148
v6.6.0 | 7786  | ~26
**This branch** | **80925** | **~270**

It's worth mentioning that 
- the Grafana instance using version v6.6.0 was extremely unresponsive during the load test and basically timed out and didn't serve requests. 
- the v6.3.7 did respond quickly and behaved really snappy during the load test. 
- the current branch did respond okay even though with latency serving requests. Given that this load test served twice as much requests than v6.3.7 and put on twice the load my conclusion is that the additional amount of requests did put too much load on my machine/mysql.

**Comment by kylebrandt** [comment]
Using my dataset (830k) annotations, generated via api calls against 6.3.7 (which doubles the count in that version before migration). Lines up with Marcus' results:

https://gist.github.com/kylebrandt/7ec4409aa008d791494368f1fd8c8c7a

### Summary 
Version | HTTP requests total | HTTP requests/s
--- | --- | ---
v6.3.7 | 9480  |  ~31
v6.6.0 | 19465  | ~64
**This branch** | **92374** | **~307**

**Review by kylebrandt — APPROVED** [review]

**Review by marefr — APPROVED** [review]

**Review by DanCech — APPROVED** [review]
