### PR TITLE
TablePanel/StatPanel: Fix values not being visible when background transparent

### LINKED ISSUE #39781: Light Theme - Issue with text color with Cell Display Mode set to Color Background
**What happened**:
We were migrating Grafana from 7.4.3 to 8.1.5
After migration, the color scheme in some of the tables changed in such a way that when using Light Theme, the numbers were not visible.

grafana_color_issue

**How to reproduce it (as minimally and precisely as possible)**:
Create a table in 8.1.5 with defined thresholds and change the background color of the cells based on said threshold. 

**Environment**:
- Grafana version: 8.1.5
- Data source type & version: Azure Data Explorer Datasource 3.3.2
- OS Grafana is installed on: Linux
- User OS & Browser: Windows & Chrome
- Grafana plugins: None
- Others: None

### PR DESCRIPTION
**Pull request by mdvictor**
**What this PR does / why we need it**:
Fixes issue where alpha value of a color was not taken into consideration and caused Table cells and Stat panels to show text colored as the background rendereding it invisible. This happened when the background color was set to transparent and the text color was dark, which triggered the text color to be white. If the Grafana theme was also set to light then both the background and the text would be white and thus invisible.

**Which issue(s) this PR fixes**:

Fixes #39781

### CODE REVIEW

File: packages/grafana-ui/src/utils/colors.ts [hunk 1]
```diff
@@ -112,8 +112,15 @@ function hslToHex(color: tinycolor.ColorFormats.HSLA) {
...
 
-export function getTextColorForBackground(color: string) {
-  const b = tinycolor(color).getBrightness();
+export function getTextColorForBackground(color: string, themeIsDark: boolean) {
+  const tcolor = tinycolor(color);
+  const b = tcolor.getBrightness();
+  const a = tcolor.getAlpha();
+
+  if (a < 0.3) {
+    return themeIsDark ? 'rgb(247, 248, 250)' : 'rgb(32, 34, 38)';
```
Comment (mckn) [inline packages/grafana-ui/src/utils/colors.ts:121]: Isn't the `b > 180` basically the same thing as `themeIsDark`? I'm asking because this is a breaking change of the `getTextColorForBackground` function since the `themeIsDark` is required.

Comment (mdvictor) [reply packages/grafana-ui/src/utils/colors.ts:121]: As far as I understandd, the `b` component is strictly related to the background color hex code and does not take into account what the theme settings are. I understand that this is a breaking change. In this case I guess the cleanest solution is to create a new function that takes the transparency component into account and use that internally.

**Review by mckn — APPROVED** [review]
LGTM!
