### PR TITLE
Tracing: Fix view bounds after trace change

### LINKED ISSUE #23988: Tracing: Spans lines not showing when selecting trace with trace selector
When selecting trace from the dropdown the lines don't get rendered. They are rendered when you refresh the page.

Screenshot from 2020-04-28 11-41-02

### PR DESCRIPTION
**Pull request by aocenas**
Fixes https://github.com/grafana/grafana/issues/23988

After trace was changed the view bounds were kept the same so each span was positioned outside of the current view.

### CODE REVIEW

**Review by Estrax — APPROVED** [review]
LGTM

File: packages/jaeger-ui-components/src/TraceTimelineViewer/VirtualizedTraceView.tsx [hunk 1]
```diff
@@ -202,12 +202,13 @@ export class UnthemedVirtualizedTraceView extends React.Component<VirtualizedTra
     if (trace !== nextTrace || childrenHiddenIDs !== nextHiddenIDs || detailStates !== nextDetailStates) {
       this.rowStates = nextTrace ? generateRowStates(nextTrace.spans, nextHiddenIDs, nextDetailStates) : [];
     }
-    if (currentViewRangeTime !== nextViewRangeTime) {
+    if (currentViewRangeTime !== nextViewRangeTime || trace !== nextTrace) {
+      console.log('update createViewedBoundsFunc');
```
Comment (Estrax) [inline packages/jaeger-ui-components/src/TraceTimelineViewer/VirtualizedTraceView.tsx:206]: Do we really want to log it there, or was it only for debugging?

Comment (aocenas) [reply packages/jaeger-ui-components/src/TraceTimelineViewer/VirtualizedTraceView.tsx:206]: No I forget to delete it
