### PR TITLE
Dashboard: Fix Variable Dropdown to Enforce Minimum One Selection when 'All' Option is Configured

### LINKED ISSUE #64887: Buggy variable dropdown behavior
**What happened**:
When `Selected(n)` is clicked  to deselect all, it sometimes defaults back to all, and sometimes displays an empty field.

**What you expected to happen**:
Revert back to `All` when `Selected(n)` is clicked.

**How to reproduce it (as minimally and precisely as possible)**:
1. Click on variable field with default All
2. Click on Selected to deselect All
3. Click outside of the variable selector to close it out
4. Blank value is displayed, but if you select on the variable field again, All is selected

https://user-images.githubusercontent.com/45561153/225590713-b71e2309-ff9c-475b-8c6a-01151814f37b.mov

### PR DESCRIPTION
**Pull request by axelavargas**
**What is this feature?**

When 'Selected(n)' is clicked to deselect all, the behavior is inconsistent; sometimes it defaults back to 'All', and at other times, it leaves an empty field.  

I've modified the logic to use the 'Selected(n)' to toggle between standard options and the 'All' option. 

### Important: 

**I retained the existing UI and enforced the selection of at least one option, which can be either a standard option or the 'All' option.** 
**The enforcing part is only applied when the "All" option is configured, these changes don't address the enforcement otherwise.** 

<table>
<tr>
<td>
Before: The user was not forced to select an option
<td>
<td>
After - Enforced the selection of at least one option, which can be either a standard option or the 'All' option. 
<td>
<tr>
<td>

https://github.com/grafana/grafana/assets/239999/3a22191d-59b2-4a4e-9d6c-c0a877996154

<td>
<td>

https://github.com/grafana/grafana/assets/239999/b952f56b-cd42-4123-b9b0-b965a7978814

<td>

</table>

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #64887

**Special notes for your reviewer:**

I modified the UI slightly and added a border-bottom, this in my opinion brings more clarity to the users about the special "All" option we allow to configure. 

<table>
<tr>
 <td>
Before
 <td>
 <td>
After
 <td>
<tr>
 <td>

image

 <td>
<td>

image

<td>
</table>

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/variables/pickers/OptionsPicker/reducer.ts [hunk 1]
```diff
@@ -178,20 +187,39 @@ const optionsPickerSlice = createSlice({
...
     toggleAllOptions: (state, action: PayloadAction): OptionsPickerState => {
-      if (state.selectedValues.length > 0) {
+      // Check if 'All' option is configured and if it's selected
+      const isAllSelected = state.selectedValues.find((option) => option.value === ALL_VARIABLE_VALUE);
+      const isAllConfigured = state.options.find((option) => option.value === ALL_VARIABLE_VALUE);
+
+      // If 'All' option is not selected but some options are, clear all options and select 'All'
+      if (state.selectedValues.length > 0 && isAllConfigured && !isAllSelected) {
         state.selectedValues = [];
+        const allOptionState = state.options.find((option) => option.value === ALL_VARIABLE_VALUE);
```
Comment (juanicabanas) [inline public/app/features/variables/pickers/OptionsPicker/reducer.ts:197]: you already have this object in `isAllConfigured`. I would reuse it, instead of iterating again over the list (maybe with the name of `allOptionState`)

File: public/app/features/variables/pickers/OptionsPicker/reducer.ts [hunk 2]
```diff
@@ -178,20 +187,39 @@ const optionsPickerSlice = createSlice({
...
+        state.selectedValues.push({
+          text: allOptionState?.text ?? 'All',
+          value: allOptionState?.value ?? ALL_VARIABLE_VALUE,
+          selected: true,
+        });
```
Comment (juanicabanas) [inline public/app/features/variables/pickers/OptionsPicker/reducer.ts:202]: If you already found the All option based on option.value === ALL_VARIABLE_VALUE, that means the value is not null and that is ALL_VARIABLE_VALUE. (using the `isAllConfigured` that is checked in the if)

```suggestion
        state.selectedValues.push({
          text: isAllConfigured.text ?? 'All',
          value: isAllConfigured.value,
          selected: true,
        });
```

File: public/app/features/variables/pickers/OptionsPicker/reducer.ts [hunk 3]
```diff
@@ -178,20 +187,39 @@ const optionsPickerSlice = createSlice({
...
 
+      // If some options are selected but 'All' is not configured, clear the selection
+      if (state.selectedValues.length > 0 && !isAllConfigured) {
+        state.selectedValues = [];
+        return applyStateChanges(state, updateOptions);
+      }
+
+      // If no options are selected and 'All' is not selected, select all options
+      state.selectedValues = selectAllOptions(state.options);
       return applyStateChanges(state, updateOptions);
```
Comment (juanicabanas) [inline public/app/features/variables/pickers/OptionsPicker/reducer.ts:220]: what about adding this code into another IF to make it more clear and not based on the comments and neither based on the previous IFs "followed logic"? I mean, this is the "default" behavior if it doesn't get into any if but I would be more declarative, since I have to follow all the IFs.

  ```suggestion
  if (!state.selectedValues.length && !isAllSelected) {
      state.selectedValues = selectAllOptions(state.options);
      return applyStateChanges(state, updateOptions);
      }
```

File: public/app/features/variables/pickers/OptionsPicker/reducer.ts (hunk 2 above)
Comment (juanicabanas) [reply public/app/features/variables/pickers/OptionsPicker/reducer.ts:202]: I put `isAllConfigured` but it would be `allOptionState` name. However, that const is from the .find before the if.

```
const allOptionState = state.options.find((option) => option.value === ALL_VARIABLE_VALUE);
if (state.selectedValues.length > 0 && isAllConfigured && !isAllSelected) {
  // the code mentioned
}
```

File: public/app/features/variables/pickers/OptionsPicker/reducer.ts (hunk 1 above)
Comment (juanicabanas) [reply public/app/features/variables/pickers/OptionsPicker/reducer.ts:197]: and I would change the if as 
if (state.selectedValues.length > 0 && !!allOptionState && !isAllSelected)

(the name of the object and the !! to make it a boolean value)

**Comment by ivanortegaalba** [comment]
About the behavior, what I understand is:
1. We have never supported "0 selected" as a real value. It was using All behind the scenes although the UI was not reflecting that.
2. Now, we're making explicit the use of "All" when no values are selected
3. There is no use case for "0 selected" that we're breaking. We have never allowed this.

If the 3 points are correct, this is a good behavior to me 💯

**Comment by axelavargas** [comment]
Thanks for the review @juanicabanas and @ivanortegaalba  🙌🏾 . I have applied  PR suggestions and added more comments for the future.

Whenever you have time to give another review it will be awesome ❤️  
P.S I still need to fix some unit test

**Review by juanicabanas — APPROVED** [review]
LGTM

**Review by ivanortegaalba — APPROVED** [review]
