### PR TITLE
Profile: Add tooltip to revoke session button

### LINKED ISSUE #91836: A11y: Buttons in profile/sessions do not provide tooltips
**Steps to reproduce**:
home - user - profile, scroll down to sessions
hover pink buttons withe the mouse or bring the keyboard focus on it

**Actual Result**:
no tooltip appears - neither when hovering with the mouse nor when receiving the keyboard focus, see attached picture.

**Expected Result**
All non-text content that is presented to the user has a text alternative (e.g. tooltip) that serves the equivalent purpose.

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)
https://www.w3.org/TR/WCAG22/#non-text-content

**Environment**:
- Grafana version: Grafana v11.0.0 (83b9528bce)
- Data source type & version:
- User OS & Browser: Windows 11, Google Chrome Version 127.0.6533.100
- Others:

### PR DESCRIPTION
**Pull request by AbdessamadEnabih**
What is this feature?
This feature adds a tooltip to a specific button in the sessions section of the application. The tooltip provides additional context for the button, enhancing its accessibility and usability.

Why do we need this feature?
Improving accessibility (A11y) is a priority for our application. By adding a tooltip to this button, we make the function of the button clearer, especially for users relying on assistive technologies, contributing to a more inclusive user experience.

Which issue(s) does this PR fix?
This PR addresses the lack of a tooltip on one specific button in the sessions section, ensuring that its purpose is easily understood by all users.

Fixes [#91836](https://github.com/grafana/grafana/issues/91836)

### CODE REVIEW

File: public/app/features/profile/UserSessions.tsx [hunk 1]
```diff
@@ -60,6 +60,7 @@ class UserSessions extends PureComponent<Props> {
                       <Button
                         size="sm"
                         variant="destructive"
+                        tooltip={'Revoke user session'}
```
Comment (tskarhed) [inline public/app/features/profile/UserSessions.tsx:63]:
```suggestion
                        tooltip={t('user-session.revoke', 'Revoke user session')}
```
You could use the same approach as for the aria-label. This enables translations for the string.

**Review by tskarhed — COMMENTED** [review]
Great! Thank you! Just fix the comment I left and we're good to go! :)

**Comment by AbdessamadEnabih** [comment]
Thank you for the review,  I fixed it.

**Review by tskarhed — APPROVED** [review]

**Review by ashharrison90 — DISMISSED** [review]
~hey @AbdessamadEnabih 👋~

~2 suggestions:~
- ~let's name the key something like `profile.user-session.revoke-tooltip`~
- ~once you've done that, you'll need to run `make i18n-extract` to extract the translations and commit those changes (you should see changes to `en/grafana.json` and `pseudo-LOCALE/grafana.json`~

~then we're good to go 🥳~

ignore this, didn't realise this was reusing a previous key!

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍
