### PR TITLE
Suggestions: Add intermediate state to avoid unexpected saved states

### LINKED ISSUE #115600: Suggestions: Avoid issues when suggestion hasn't been applied yet
Currently, there's an awkward state where a suggestion has been applied (either automatically or intentionally) to a panel which is already configured, and then getting back to the panel state before Suggestions was opened is kind of painful.

This leads to a number of problems:

- when you save the dashboard in this state, it overwrites the dashboard state.
- when you go back from panel edit while in this state, the panel retains the suggestion state.
- given that there's no back button in suggestions, there's no good way to revert in the UI without just reloading the page, which means you can lose work if you hadn't saved the dashboard before getting into this state.

### PR DESCRIPTION
**Pull request by fastfrwrd**
Fixes #115600

Before doing this, a variety of operations would result in overriding the dashboard state with an "unapplied" suggestion, including:

- previewing a suggestion and then navigating back to the dashboard
- previewing a suggestion and then saving the dashboard
- previewing a suggestion and then closing the viz picker instead of applying

this updates the panel editor to have suggestion previews applied to an intermediary temp vizpanel, and only applying the suggestion to the real panel when the user clicks "apply this suggestion."

TODO: need to write e2es for these cases and add/update unit tests.

https://github.com/user-attachments/assets/3ce77bd1-e3ef-4fb5-bac6-768a1eeea3db

### CODE REVIEW

File: public/app/features/dashboard-scene/panel-edit/PanelVizTypePicker.tsx [hunk 1]
```diff
@@ -97,49 +98,55 @@ export function PanelVizTypePicker({ panel, data, onChange, onClose, showBackBut
...
+                    fill="text"
+                    variant="secondary"
+                    icon="arrow-left"
+                    data-testid={selectors.components.PanelEditor.toggleVizPicker}
+                    onClick={onClose}
+                  >
+                    <Trans i18nKey="dashboard-scene.panel-viz-type-picker.button.close">Back</Trans>
+                  </Button>
+                )}
+                <FilterInput
```
Comment (fastfrwrd) [inline public/app/features/dashboard-scene/panel-edit/PanelVizTypePicker.tsx:122]: for now, the filter input is back in the Suggestions view for the new one just to have somewhere to put the back button for now. I think that we'll probably have a design idea from @jotasolano on how to have a back button in the Suggestions view in a way that is not funky.

**Review by jesdavpet — APPROVED** [review]

File: public/app/features/dashboard-scene/panel-edit/PanelEditor.tsx [hunk 2]
```diff
@@ -251,16 +255,39 @@ export class PanelEditor extends SceneObjectBase<PanelEditorState> {
...
+
+      this._subs.add(
+        optionsPane.subscribeToState((newState, oldState) => {
+          if (newState.isVizPickerOpen !== oldState.isVizPickerOpen) {
+            const panel = this.state.panelRef.resolve();
+            let editPreview: VizPanel | undefined;
+            if (newState.isVizPickerOpen) {
+              const editPreviewBuilder = PanelBuilders.timeseries()
+                .setTitle(panel.state.title)
+                .setDescription(panel.state.description);
```
Comment (jesdavpet) [inline public/app/features/dashboard-scene/panel-edit/PanelEditor.tsx:281]: **question(non-blocking):** 🤔 💭  Is this limited to timeseries only @fastfrwrd, if so is that just temporary? What about for non-timeseries panels, would this benefit from being more flexible?

_(I'm not very close to this project, so pardon if I misunderstood due to lack of context.)_

Comment (fastfrwrd) [reply public/app/features/dashboard-scene/panel-edit/PanelEditor.tsx:281]: This is kind of a funky thing, I originally had a comment in here but I guess I deleted it. tl;dr is that `PanelBuilders` doesn't have `PanelBuilders.unconfigured()` and we should add it, but there's no harm in doing this for now because the panel type is immediately overwritten by other logic.

Longer version: this PR changes how suggestions renders the main viz. Before, Suggestions wrote changes to the panel to the main Panel model, which is connected to the Dashboard, so hitting save or back would result in persisted changes from Suggestions. Now, there's this new panel (which is coming from `PanelBuilders.timeseries()`), and it is unhooked from the main dashboard. As the user clicks suggestions but doesn't yet apply them, this updates that model and renders it in the main VizPanel. This helps us avoid changing the underlying Dashboard JSON until the user hits "Use this suggestion."

The PanelBuilders give us a convenient way to construct a panel with defaults that make sense, but they are all initialized with a panel type, because until dynamic dashboards, I believe it wasn't even possible to initialize a panel without one? Like how you create a panel from a dashboard and it's automatically a timeseries panel. PanelBuilders doesn't expose that case (it's referred to as "unconfigured") and it wouldn't even work depending on the state of the dynamic dashboards flag at the moment, so we just need to pick one of the builders and then immediately override the panel with the appropriate panel type (whenever `onChange` is called in the Suggestions code).

File: public/app/features/dashboard-scene/panel-edit/PanelEditor.tsx [hunk 3]
```diff
@@ -251,16 +255,39 @@ export class PanelEditor extends SceneObjectBase<PanelEditorState> {
...
         isInitializing: false,
       });
+
+      this._subs.add(
+        optionsPane.subscribeToState((newState, oldState) => {
+          if (newState.isVizPickerOpen !== oldState.isVizPickerOpen) {
+            const panel = this.state.panelRef.resolve();
+            let editPreview: VizPanel | undefined;
+            if (newState.isVizPickerOpen) {
+              const editPreviewBuilder = PanelBuilders.timeseries()
```
Comment (fastfrwrd) [inline public/app/features/dashboard-scene/panel-edit/PanelEditor.tsx:279]:
```suggestion
              // we just "pick" timeseries, viz type will likely be overridden by Suggestions.
              const editPreviewBuilder = PanelBuilders.timeseries()
```

File: public/app/features/dashboard-scene/panel-edit/PanelEditor.tsx (hunk 2 above)
Comment (jesdavpet) [reply public/app/features/dashboard-scene/panel-edit/PanelEditor.tsx:281]: TIL, thanks for the detailed explanation. Makes sense!
