### PR TITLE
Cloudwatch: Add support for template variables in new log group picker

### LINKED ISSUE #48806: CloudWatch Logs: "multi template variables are not supported for queryString"
**What happened**:
Using multi template variable inside CloudWatch Logs query shows popup error, even if the query works well.

**What you expected to happen**:
The popup error is not shown.

**How to reproduce it (as minimally and precisely as possible)**:
Create multi-value variable, eg:
image

Use multi template variable inside CloudWatch Logs query, eg: `filter pod_name in [ ${pod:doublequote} ]`

**Anything else we need to know?**:
image

**Environment**:
- Grafana version: 8.5.0
- Data source type & version: CloudWatch
- OS Grafana is installed on: Linux
- User OS & Browser: Windows, Chrome 100

### LINKED ISSUE #61447: CloudWatch: Merge describe log groups route and describe all log groups route

### PR DESCRIPTION
**Pull request by sunker**
**What is this feature?**

This PR adds support for template variables in the new log group picker. There's a few different things going here:
* removing `all-log-groups` resource request, and use an additional parameter in the existing `describe-log-groups` resource handler to achieve the same thing
* add a new template variable field selector at the bottom of the log group picker. In the previous log group selector, it was possible to select "normal" log group names + a template variable, so this needed to be possible in the new log group picker too.
* changing the log groups template variable query so that it returns both log group name and log group arn.
* cleaning up in the CloudWatchLogsQueryRunner and removing unused types related to logs. hopefully this makes it easier to understand when and how template variables are being interpolated in the logs execution flow.  

Fixes #61447
Fixes #48806
Related to #48806
This is related to a bunch of open issues. Will add links shortly. 

**Special notes for your reviewer**:
Added a few comments in the code.

### CODE REVIEW

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import { set } from 'lodash';
+import { set, uniq } from 'lodash';
```
Comment (sunker) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts:1]: Some context for the changes in this file. Before we started the work to move resource requests to the new layered architecture, CloudWatch logs did not use the CallResource api. All requests - `StartQuery`, `GetQueryResult`, `StopQuery`, `DescribeLogGroups`, `DescribeAllLogGroups`,  `GetLogGroupFields`, `GetLogEvents` - went through the DataQuery api. Using the DataQuery api for discovery data is bad practice and it also made it hard to structure code both in backend and in the frontend. After this pr, the only discovery data request that still goes through the DataQuery  api is the GetLogEvents request, but hopefully that can be removed too soon. 

Previously, all the requests went through the `makeLogActionRequest` method. The calling method was passing the `makeReplacement` boolean arg, and if it was set to true, some(?) of the props passed would be replaced as template variables. This was very un-intuitive, so main goal here is to interpolate variables where the query is actually created so that it becomes easier to test and read the code.

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts [hunk 2]
```diff
@@ -295,58 +280,16 @@ export class CloudWatchLogsQueryRunner extends CloudWatchRequest {
...
-    }
-
     const resultsToDataFrames = (
       val:
         | { data: BackendDataSourceResponse | undefined }
         | FetchResponse<BackendDataSourceResponse | undefined>
         | DataQueryError
     ): DataFrame[] => toDataQueryResponse(val).data || [];
     let headers = {};
-    if (options.skipCache) {
```
Comment (sunker) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts:345]: Now none of the calling methods wants to skip cache, so I removed this argument.

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts [hunk 3]
```diff
@@ -295,58 +280,16 @@ export class CloudWatchLogsQueryRunner extends CloudWatchRequest {
       })),
     };
 
-    if (options.makeReplacements) {
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts:298]: what did this do before?

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts (hunk 2 above)
Comment (sarahzinger) [reply public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts:345]: Why did they want to skip the cache before and why do they not now?

File: public/app/plugins/datasource/cloudwatch/types.ts [hunk 4]
```diff
@@ -144,46 +137,7 @@ export interface CloudWatchSecureJsonData extends AwsAuthDataSourceSecureJsonDat
...
-}
-
-export type QueryStatus = 'Scheduled' | 'Running' | 'Complete' | 'Failed' | 'Cancelled' | string;
-
-export type CloudWatchLogsRequest =
-  | GetLogEventsRequest
-  | StartQueryRequest
-  | DescribeLogGroupsRequest
-  | GetLogGroupFieldsRequest;
+export type CloudWatchLogsRequest = GetLogEventsRequest | StartQueryRequest | QueryParam;
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/types.ts:140]: I guess this is old but what's "GetLogEventsRequest"?

File: pkg/tsdb/cloudwatch/services/log_groups.go [hunk 5]
```diff
@@ -33,20 +34,29 @@ func (s *LogGroupsService) GetLogGroups(req resources.LogGroupsRequest) ([]resou
...
+			result = append(result, resources.ResourceResponse[resources.LogGroup]{
+				Value: resources.LogGroup{
+					Arn:  *logGroup.Arn,
+					Name: *logGroup.LogGroupName,
+				},
+				AccountId: utils.Pointer(getAccountId(*logGroup.Arn)),
+			})
+		}
+
+		if !req.ListAllLogGroups || response.NextToken == nil {
```
Comment (sarahzinger) [inline pkg/tsdb/cloudwatch/services/log_groups.go:56]: Why do we have both req.ListAllLogGroups and a req.Limit?

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts [hunk 6]
```diff
@@ -83,18 +82,27 @@ export class CloudWatchLogsQueryRunner extends CloudWatchRequest {
...
+        target.logGroupNames || this.instanceSettings.jsonData.defaultLogGroups || [],
+        'text'
+      );
+
+      return {
+        refId: target.refId,
+        region: this.templateSrv.replace(this.getActualRegion(target.region)),
+        queryString: this.templateSrv.replace(target.expression || ''),
+        logGroups: uniq(logGroupArns).map((arn) => ({ arn, name: arn })),
+        logGroupNames: uniq(logGroupNames),
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts:103]: are these uniqs necessary?

**Review by sarahzinger — COMMENTED** [review]
Looking good, have some questions/suggestions, maybe we could go over some of this in mob?

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.test.ts [hunk 7]
```diff
@@ -185,4 +192,67 @@ describe('CloudWatchLogsQueryRunner', () => {
...
+          ...CloudWatchSettings,
+          jsonData: {
+            ...CloudWatchSettings.jsonData,
+            logsTimeout: '500ms',
+          },
+        },
+      });
+      const spy = jest.spyOn(runner, 'makeLogActionRequest');
+      await lastValueFrom(runner.handleLogQueries([legacyLogGroupNamesQuery, logGroupNamesQuery], LogsRequestMock));
+      const startQueryRequests: StartQueryRequest[] = [
```
[the remark this answers is not in the document]
Comment (iwysiu) [reply public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.test.ts:233]: Yeah, cloudwatch logs does a weird thing where it handles the async stuff on the frontend, but it makes calls to the backend to start the query and such.

File: public/app/plugins/datasource/cloudwatch/components/LogGroups/LogGroupsSelector.tsx [hunk 8]
```diff
@@ -178,8 +193,25 @@ export const LogGroupsSelector = ({
...
+                newValues.push({ name: option.label, arn: option.label });
+              }
+              setSelectedLogGroups(newValues);
+            }}
+          />
+        </EditorField>
+        <Space layout="block" v={2} />
         <Label className={styles.logGroupCountLabel}>
-          {selectedLogGroups.length} log group{selectedLogGroups.length !== 1 && 's'} selected
+          {selectedLogGroupsCounter} log group{selectedLogGroupsCounter !== 1 && 's'} selected
```
Comment (iwysiu) [inline public/app/plugins/datasource/cloudwatch/components/LogGroups/LogGroupsSelector.tsx:214]: I do sort of understand why the variables don't count toward this, but also I feel like it may be confusing from a user perspective if their variable maps to a log group and isn't counted?

**Review by iwysiu — COMMENTED** [review]
Added a few questions, but would also be in favor of going over this in mob

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts (hunk 1 above)
Comment (sunker) [reply public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts:1]: Yes good idea!

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts (hunk 2 above)
Comment (sunker) [reply public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts:345]: Similar to the long running query feature in Athena and Redshift, CW logs polls the grafana backend (and the logs apis) to check if there are results to fetch. Unlike the Athena and Redshift apis, the logs api can also return partial responses. This is neat because even though the query may need to scan petabytes of data which can take minutes, you may be able to see some result on the logs panel after only a few seconds. However, if we cache a partial response, it will mess up query caching pretty badly. For that reason, none of query data requests (StartQuery, GetQueryResult, StopQuery) should be cached. Some of the requests that have now been moved to the resource request flow (through api.ts) used to set the `skipCache` parameter to false, but now that they're not using the `makeLogActionRequest` anymore, we can safely remove the argument from this function since all the calling methods always wants the cache to be bypassed. 

Let's talk more about this in the mob session!

File: pkg/tsdb/cloudwatch/resource_handler.go [hunk 9]
```diff
@@ -19,7 +19,6 @@ func (e *cloudWatchExecutor) newResourceMux() *http.ServeMux {
 	mux.HandleFunc("/ec2-instance-attribute", handleResourceReq(e.handleGetEc2InstanceAttribute))
 	mux.HandleFunc("/resource-arns", handleResourceReq(e.handleGetResourceArns))
 	mux.HandleFunc("/describe-log-groups", routes.ResourceRequestMiddleware(routes.LogGroupsHandler, logger, e.getRequestContext))
```
[the remark this answers is not in the document]
Comment (sunker) [reply pkg/tsdb/cloudwatch/resource_handler.go:21]: I agree! Should be changed now.

File: public/app/plugins/datasource/cloudwatch/api.ts [hunk 10]
```diff
@@ -69,6 +69,7 @@ export class CloudWatchAPI extends CloudWatchRequest {
       ...params,
       region: this.templateSrv.replace(this.getActualRegion(params.region)),
       accountId: this.templateSrv.replace(params.accountId),
+      listAllLogGroups: params.listAllLogGroups ? 'true' : 'false',
```
[the remark this answers is not in the document]
Comment (sunker) [reply public/app/plugins/datasource/cloudwatch/api.ts:72]: These are url parameters, so we can only send strings.

File: public/app/plugins/datasource/cloudwatch/components/LogGroups/LogGroupsField.test.tsx [hunk 11]
```diff
@@ -45,6 +45,20 @@ describe('LogGroupSelection', () => {
     expect(defaultProps.onChange).toHaveBeenCalledWith([{ arn: 'arn', name: 'loggroupname' }]);
   });
 
+  it('should remove any variables before calling describeCrossAccountLogGroups', async () => {
```
[the remark this answers is not in the document]
Comment (sunker) [reply public/app/plugins/datasource/cloudwatch/components/LogGroups/LogGroupsField.test.tsx:48]: Oh yes this was confusing! I've updated the scenario name and also added a comment in the component. Hopefully that makes things clearer. 

If a template variable is defined in the legacy logs query like this:
``` typescript
const logsQuery: CloudWatchLogsQuery = {
    ...,
    logGroupNames: ['logGroup1', '$logGroupVariable'],
  }

```

Then there's no need to call the `getLogGroups` api to substitute the variable value for a log group arn - this will be taken of in the log query execution flow instead. So we just need to make sure any variables are being moved to the new log group array. So for the above query, expected output would be:
``` typescript
const logsQuery: CloudWatchLogsQuery = {
    ...,
    logGroupNames: undefined,
    logGroups: [{ arn: 'arn', name: 'loggroupname' }, { arn: '$logGroupVariable', name: '$logGroupVariable' }],
  }
```

**Comment by idastambuk** [comment]
I pulled the branch and played around with it a bit, and I came across an error that seems like a bug: 
ezgif-2-810236dfc7 
Tried it with main without an error. 

Also, when I select a logGroup from the variable dropdown, the selected log group doesn't seem to be selected in the logGroup selector modal - is this intended behaviour? 

We can go over these in a call if this isn't clear or Im doing something wrong :)

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts (hunk 3 above)
Comment (sunker) [reply public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts:298]: That's a good question, and also the main driver behind this refactoring! 
As said before, all different query subTypes called this method. Some of these sub types wanted their query props to be replaced as variablas. If so, they set the `makeReplacements` arg to true. 

If you look below, what happens is pretty nasty with a deeply nested if statements. The idea here is that variables are supposed to be interpolated before the backend query is issued. For the logs query, it's in the `handleLogQueries` method above. And all the resource requests that used to be in this file are now moved to api.ts ts and that's also where the variables are being interpoalted.

File: public/app/plugins/datasource/cloudwatch/types.ts (hunk 4 above)
Comment (sunker) [reply public/app/plugins/datasource/cloudwatch/types.ts:140]: The CloudWatch datasource file implement the [DataSourceWithLogsContextSupport](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/logs.ts#L154) interface. That means the platform (probably logs query runner or logs panel) will call the [getLogRowContext](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloudwatch/datasource.ts#L137) method in the data source file. I'm not familiar with this method and I don't know when it's being triggered, but it seems like what CloudWatch logs does is that it will fetch log event from the `GetLogEvents` api, tweak the response to the format that DataSourceWithLogsContextSupport expects. 

Since this is not a data query, it should be using the call resource api instead. It's the last subType request that should be moved to the resource api instead. See [this epic](https://github.com/grafana/grafana/issues/57146) or more details.

File: pkg/tsdb/cloudwatch/services/log_groups.go (hunk 5 above)
Comment (sunker) [reply pkg/tsdb/cloudwatch/services/log_groups.go:56]: Limit is the maximum items per page, and if ListAllLogGroups is true we'll iterate over all pages. If false, only the first page.

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts (hunk 6 above)
Comment (sunker) [reply public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts]: Yes. Let's say for example this is the logGroupNames array:
```typescript 
['logGroup1', '$logGroupVariable']
```
If $logGroupVariable is a multi-valued variable, and one of it's value is the same as `logGroup1` which is already in the logGroupNames array, the array will include dupes:
```typescript 
// expanded
['logGroup1', 'logGroup1', 'logGroup2']
```
When logGroupNames includes dupes, the  `StartLogQuery` api will return an error. Weirdly, it returns a permission error (?). However, removing dupes with the uniq func solves the problem.

File: pkg/tsdb/cloudwatch/services/log_groups.go [hunk 12]
```diff
@@ -18,6 +18,7 @@ func NewLogGroupsService(logsClient models.CloudWatchLogsAPIProvider, isCrossAcc
 }
 
 func (s *LogGroupsService) GetLogGroups(req resources.LogGroupsRequest) ([]resources.ResourceResponse[resources.LogGroup], error) {
+	var nextToken *string
```
[the remark this answers is not in the document]
Comment (sunker) [reply pkg/tsdb/cloudwatch/services/log_groups.go:21]: Nice!

File: pkg/tsdb/cloudwatch/services/log_groups_test.go [hunk 13]
```diff
@@ -86,6 +87,81 @@ func TestGetLogGroups(t *testing.T) {
...
+			LogGroupNamePrefix: utils.Pointer("test"),
+			ListAllLogGroups:   false,
+		}
+
+		mockLogsAPI.On("DescribeLogGroups", &cloudwatchlogs.DescribeLogGroupsInput{
+			Limit:              aws.Int64(req.Limit),
+			LogGroupNamePrefix: req.LogGroupNamePrefix,
+		}).Return(&cloudwatchlogs.DescribeLogGroupsOutput{
+			LogGroups: []*cloudwatchlogs.LogGroup{
+				{Arn: utils.Pointer("arn:aws:logs:us-east-1:111:log-group:group_a"), LogGroupName: utils.Pointer("group_a")},
```
[the remark this answers is not in the document]
Comment (sunker) [reply pkg/tsdb/cloudwatch/services/log_groups_test.go:104]: Good catch!

File: public/app/plugins/datasource/cloudwatch/components/LogGroups/LogGroupsSelector.tsx (hunk 8 above)
Comment (sunker) [reply public/app/plugins/datasource/cloudwatch/components/LogGroups/LogGroupsSelector.tsx:214]: Catherine wanted variables to be excluded from this counter. But I remember now that she also me to move this counter so that it's placed above the template variable field. That way it's a bit more obvious that the counter is only for non-variable selections.

**Comment by sunker** [comment]
> I pulled the branch and played around with it a bit, and I came across an error that seems like a bug: ezgif-2-810236dfc7 [ ezgif-2-810236dfc7 ](https://user-images.githubusercontent.com/16140639/212046275-b2dc1987-0e5f-4434-bdd8-5960b531e909.gif) [ ](https://user-images.githubusercontent.com/16140639/212046275-b2dc1987-0e5f-4434-bdd8-5960b531e909.gif) Tried it with main without an error.
> 
> Also, when I select a logGroup from the variable dropdown, the selected log group doesn't seem to be selected in the logGroup selector modal - is this intended behaviour?
> 
> We can go over these in a call if this isn't clear or Im doing something wrong :)


Oh, thanks for finding this @idastambuk! Pushed a fix and added a test. 

Note that it _should_ not return any data for the `aws` prefix - you need to add a leading `/` for it to return log groups. However, it should return an empty array instead of null when no results are found, so this was definitely a bug.

**Review by sarahzinger — APPROVED** [review]

**Review by iwysiu — APPROVED** [review]
