### PR TITLE
Analytics: Respect appsuburl in tracking url

### LINKED ISSUE #27319: serve_from_sub_path not reflected in google analytics reports
**What happened**:

I currently serve grafana from a subpath. The config looks like this:

```
[server]
root_url = https://mydomain/grafana
serve_from_sub_path = true
[analytics]
google_analytics_ua_id = my-google-analytics-id
```

**What you expected to happen**:
I expect visits to the grafana pages to be reported to google analytics under the /grafana path, e.g., `/grafana/d/HSr2fnSGk/global-usage`

Instead, google analytics paths are reported as `/d/HSr2fnSGk/global-usage`

**How to reproduce it (as minimally and precisely as possible)**:

see above

**Anything else we need to know?**:

nope, thanks for building a great product! :hugs: 

**Environment**:
- Grafana version: 7.1.1

### PR DESCRIPTION
**Pull request by peterholmberg**
**What this PR does / why we need it**:
Fixes an issue where the appsuburl was not added to the tracking url

**Which issue(s) this PR fixes**:
Fixes #27319

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/core/services/analytics.ts [hunk 1]
```diff
@@ -26,8 +26,9 @@ export class Analytics {
   }
 
   init() {
+    console.log('analytics init');
```
Comment (hugohaggmark) [inline public/app/core/services/analytics.ts:29]: please remove :)

**Review by hugohaggmark — APPROVED** [review]
Looks good to me and works as expected when testing 🌟  Left a small nit for you to consider :)

File: public/app/core/services/analytics.ts (hunk 1 above)
Comment (peterholmberg) [reply public/app/core/services/analytics.ts:29]: Bah, missed that one
