### PR TITLE
SQL Expressions: Exclude CTEs from required Tables

### LINKED ISSUE #105030: SQL Expressions: CTEs failing to execute
Introducing a CTE into a SQL Expression leads to a failure:

```
[sse.dependencyError] did not execute expression [<Ref-id>] due to a failure of the dependent expression or query [<CTE-table-name>]
```

eg:
```
[sse.dependencyError] did not execute expression [A] due to a failure of the dependent expression or query [CTE]
```

This is easy to reproduce:

1. Add a Datasource query to the TestData DS, with Query-name (RefID): "A", and using `CSV Content` and the following content:
    ```
    Month
    "2025-04"
    ```
2. Add a SQL Expression which introduces a CTE. Something like:
    ```sql
    WITH CTE AS (
      SELECT
        Month
      FROM metrics
    )

    SELECT * FROM CTE
    ```

You'll see the error.

I'm seeing this on GrafanaCloud Fast channel on Tuesday 6th of May. But it wasn't an issue on the same Fast channel on Thursday last week (the 1st of May)

## EDIT

Adding `&__feature.queryServiceFromUI=false` to the URL fixes the issue

### PR DESCRIPTION
**Pull request by kylebrandt**
**What is this feature?**

Clean up detection of CTEs in SQL expressions by excluding them in the TableList command.

**Why do we need this feature?**

See issue.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #105030

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by kylebrandt** [comment]
Todo: Clean up other places in SSE Graph / and the query service graph that was doing or trying to do this before.

File: pkg/expr/sql/parser.go [hunk 1]
```diff
@@ -19,10 +21,18 @@ func TablesList(rawSQL string) ([]string, error) {
...
 
 	tables := make(map[string]struct{})
+	cteNames := make(map[string]struct{})
 
 	walkSubtree := func(node sqlparser.SQLNode) error {
 		err = sqlparser.Walk(func(node sqlparser.SQLNode) (kontinue bool, err error) {
 			switch v := node.(type) {
+			case *sqlparser.CommonTableExpr:
+				// Track CTE name from the As field
+				cteName := v.As.String()
```
Comment (samjewell) [inline pkg/expr/sql/parser.go:31]: This is neat 👏 
I think I tried something like this once before, and was trying to get an LLM to fix it for me. I think the LLM couldn't find this step (and nor did I).

File: pkg/expr/sql/parser.go [hunk 2]
```diff
@@ -49,9 +59,15 @@ func TablesList(rawSQL string) ([]string, error) {
 		// Remove 'dual' table if it exists
 		// This is a special table in MySQL that always returns a single row with a single column
 		// See: https://dev.mysql.com/doc/refman/5.7/en/select.html#:~:text=You%20are%20permitted%20to%20specify%20DUAL%20as%20a%20dummy%20table%20name%20in%20situations%20where%20no%20tables%20are%20referenced
-		if table != "dual" {
-			result = append(result, table)
+		if table == "dual" {
+			continue
+		}
+
+		// Skip tables that are part of CTEs
```
Comment (samjewell) [inline pkg/expr/sql/parser.go]: I found this comment a little confusing. How about
```suggestion
		// Skip CTEs
```
or
```suggestion
		// Skip the table-names that are CTEs
```

**Review by asimpson — APPROVED** [review]
This cleans thing up nicely :trophy: Thanks!
