### PR TITLE
[dashboard api] manage error when data in dashboard table is not valid json

### LINKED ISSUE #26910: API: Add validation for dashboard JSON
**What happened**:
If the dashboard JSON is for some reason corrupted in the database (migration from other database)
the dashboard is not loaded properly (missing title etc.) but there is no other error message informing the user.

**What you expected to happen**:
There should be at least an error informing the user about the failure to load the dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
Modify the `data` column in `datasource` table and store an invalid JSON.

**Anything else we need to know?**:

**Environment**:
- Grafana version: master

### PR DESCRIPTION
**Pull request by ying-jeanne**
**What this PR does / why we need it**: now when data from the dashboard table is not valid JSON, the response is HTTP 200 and with empty content, which is confusing for the customer.

The fix is done on GetDashboard of API level, it is because the GetDashboardQuery is used not only by retrieve dashboard API, but also by folder service and file reader, etc.

Error code is 500 in this case.
 
**Which issue(s) this PR fixes**:

Fixes #26910 

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/api/dashboard_test.go [hunk 1]
```diff
@@ -1009,7 +1009,8 @@ func TestDashboardAPIEndpoint(t *testing.T) {
 				return nil
 			})
 			bus.AddHandler("test", func(query *models.GetDashboardQuery) error {
-				query.Result = &models.Dashboard{Id: 1, Data: &simplejson.Json{}}
+				dataValue, _ := simplejson.NewJson([]byte(`{"id": 1, "editable": true, "style": "dark"}`))
```
Comment (aknuds1) [inline pkg/api/dashboard_test.go:1012]: We should make sure the JSON parsing went OK:
```suggestion
				dataValue, err := simplejson.NewJson([]byte(`{"id": 1, "editable": true, "style": "dark"}`))
				require.NoError(t, err)
```

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Generally looks good, but see suggested change please.

File: pkg/api/dashboard_test.go (hunk 1 above)
Comment (aknuds1) [reply pkg/api/dashboard_test.go:1012]: Also, can we add a test for the error case?

File: pkg/api/dashboard.go [hunk 2]
```diff
@@ -50,10 +50,25 @@ func (hs *HTTPServer) GetDashboard(c *models.ReqContext) Response {
 	slug := c.Params(":slug")
 	uid := c.Params(":uid")
 	dash, rsp := getDashboardHelper(c.OrgId, slug, 0, uid)
+
```
Comment (aknuds1) [inline pkg/api/dashboard.go:53]: Why add this blank line? I think it makes sense as-is:

```suggestion
```

**Review by aknuds1 — APPROVED** [review]
LGTM, except I'm wondering if we could add a test case for invalid dashboard data.

**Review by aknuds1 — APPROVED** [review]
