### PR TITLE
Fix empty value for expiry date

### LINKED ISSUE #64889: Cannot set a expiry date for Service Accounts if config is empty
**What happened**:

A user can no longer set a custom expiry date for Service Account Tokens (SAT) when the configuration is empty or `0`.

**What you expected to happen**:

If the configuration for `service_accounts.token_expiration_day_limit` is empty, I should be able to create a SAT with a custom expiry date.

**How to reproduce it (as minimally and precisely as possible)**:

- Set `service_accounts.token_expiration_day_limit` to empty
- click on `Add service account token`
- click on `Set expiration date`
- Calendar modal won't let me set a custom date

### PR DESCRIPTION
**Pull request by linoman**
**What is this feature?**

This will change the Service accounts tokens' expiry date to the maximum possible as a default, allowing them to use any date if there is no configuration set as a limit.

**Why do we need this feature?**

Upon using an empty value for Service accounts tokens' expiry date, the user couldn't choose any value they might want.

**Which issue(s) does this PR fix?**:

Fixes #64889

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/serviceaccounts/components/CreateTokenModal.tsx [hunk 1]
```diff
@@ -38,8 +38,11 @@ export const CreateTokenModal = ({ isOpen, token, serviceAccountLogin, onCreateT
   tomorrow.setDate(tomorrow.getDate() + 1);
 
   const maxExpirationDate = new Date();
-  if (config.tokenExpirationDayLimit !== undefined) {
+  if (config.tokenExpirationDayLimit !== undefined && config.tokenExpirationDayLimit > -1) {
+    console.error(`there is a defined date`, config.tokenExpirationDayLimit);
```
Comment (IevaVasiljeva) [inline public/app/features/serviceaccounts/components/CreateTokenModal.tsx:42]: You probably want to remove this debug log :)

Comment (linoman) [reply public/app/features/serviceaccounts/components/CreateTokenModal.tsx]: What debug log? 😬

jk! removed!

**Review by IevaVasiljeva — APPROVED** [review]
Nice, I tested it and it works!

One thing that I noticed is that there's no easy way to go from setting expiration date for a token to setting no expiration date for it. Here's a little video to show what I mean:

https://user-images.githubusercontent.com/9482349/225879651-20fad860-d20e-49dc-9432-d90fe4d0537e.mov

It's out of the scope for this PR, but a potential UX improvement for the future.

**Comment by linoman** [comment]
> there's no easy way to go from setting expiration date for a token to setting no expiration date for it

@vesnadean can you help me with a suggestion to address this `I change my mind, I don't want an expiration date anymore`?

**Comment by vesnadean** [comment]
Here's a screenshot from the design file. It shows that when you select "Set expiration date", the date input field doesn't replace the select component, instead it appears underneath so users can always toggle between setting an expiration date or not. 
Screenshot 2023-03-20 at 14 14 13

[Figma design file](https://www.figma.com/file/59QdzyoapeCLLDBuetcUuo/%F0%9F%9F%A2-Service-accounts?node-id=41%3A1565&t=ZR8qjWYoW5loYe42-1)

**Comment by linoman** [comment]
@IevaVasiljeva I created issue #65085 to address this.

@vesnadean Thank you for pointing out the reference.
