### PR TITLE
Naming: Fix wrong reactive power (kVAr)

### LINKED ISSUE #31961: Wrong case on electric units, var kvar for reactive power
Units in energy for reactive power is incorrect with regards to case.

var for reactive power should be VAr and kvar should be kVAr

### PR DESCRIPTION
**Pull request by ldhnam**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #31961

### CODE REVIEW

File: packages/grafana-data/src/valueFormats/categories.ts [hunk 1]
```diff
@@ -210,7 +210,7 @@ export const getCategories = (): ValueFormatCategory[] => [
       { name: 'Volt-ampere (VA)', id: 'voltamp', fn: SIPrefix('VA') },
       { name: 'Kilovolt-ampere (kVA)', id: 'kvoltamp', fn: SIPrefix('VA', 1) },
       { name: 'Volt-ampere reactive (var)', id: 'voltampreact', fn: SIPrefix('var') },
-      { name: 'Kilovolt-ampere reactive (kvar)', id: 'kvoltampreact', fn: SIPrefix('var', 1) },
+      { name: 'Kilovolt-ampere reactive (kVAr)', id: 'kvoltampreact', fn: SIPrefix('var', 1) },
```
Comment (torkelo) [inline packages/grafana-data/src/valueFormats/categories.ts:213]:
```suggestion
      { name: 'Kilovolt-ampere reactive (kVAr)', id: 'kvoltampreact', fn: SIPrefix('VAr', 1) },
```

**Comment by ldhnam** [comment]
@torkelo I updated code, can you review MR again ?

**Review by torkelo — APPROVED** [review]
