### PR TITLE
Footer: Add release notes url to version label

### LINKED ISSUE #52773: Footer: Grafana Version / Commit is an empty link
**What happened**:
Wherever Grafana generates a footer, it adds the Grafana version and commit to the list of links:

https://github.com/grafana/grafana/blob/238d761450738cdef822589f321500879fa49b32/public/app/core/components/Footer/Footer.tsx#L48

The link is empty, which I've always found a little disappointing. I was thinking we could reference the commit like this:

```
links.push({ text: `v${buildInfo.version} (${buildInfo.commit})`, url: `https://github.com/grafana/grafana/search?q=${buildInfo.commit}&type=commits` });
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by kianelbo**
**What this PR does / why we need it**:
Currently the version/commit part of the footer has no urls. This PR adds a link to the release notes page.

**Which issue(s) this PR fixes**:
Fixes #52773

### CODE REVIEW

**Review by zuchka — COMMENTED** [review]
I really like this idea, but it breaks on certain builds:

https://grafana.com/docs/grafana/latest/release-notes/release-notes-9.1.0-pre/

**Comment by kianelbo** [comment]
> but it breaks on certain builds

Well we can consider the version up to the minor segment (for example 9.1.0-pre -> 9.1).

File: public/app/core/components/Footer/Footer.tsx [hunk 1]
```diff
@@ -45,7 +45,10 @@ export let getVersionLinks = (): FooterLink[] => {
     return links;
   }
 
-  links.push({ text: `v${buildInfo.version} (${buildInfo.commit})` });
+  links.push({
+    text: `v${buildInfo.version} (${buildInfo.commit})`,
+    url: `https://grafana.com/docs/grafana/latest/release-notes/release-notes-${buildInfo.version}/`
```
Comment (joshhunt) [inline public/app/core/components/Footer/Footer.tsx:50]: At a minimum, this would need the periods replaced with hyphens for the URL to be valid.

I'm taking a look to see what we should handle pre-release versions. I'm thinking prereleases just shouldn't link to anything.

Comment (joshhunt) [reply public/app/core/components/Footer/Footer.tsx:50]:
```ts
const isPrerelease = buildInfo.version.includes('-');
links.push({
  text: `v${buildInfo.version} (${buildInfo.commit})`,
  url: isPrerelease ? `https://grafana.com/docs/grafana/latest/release-notes/release-notes-${buildInfo.version.replace(".", "-")}/` ? undefined
})
```

Comment (kianelbo) [reply public/app/core/components/Footer/Footer.tsx:50]: Good suggestion! However, this filters beta versions as well (like [v9.0.0-beta3](https://grafana.com/docs/grafana/latest/release-notes/release-notes-9-0-0-beta3/)), doesn't it?

**Comment by joshhunt** [comment]
Merged in main, and pushed up a few changes:

 - fixed the version slug (it was only replacing the first dot with hyphen
 - link to /next/ docs for beta versions
 - Don't use `<a />` if there's not a link - this is a longstanding issue with the footer :(
 - Added a hover underline to the links to make it slightly easier to tell they're links.

File: public/app/core/components/Footer/Footer.tsx [hunk 2]
```diff
@@ -89,3 +106,19 @@ export const Footer: FC = React.memo(() => {
 });
 
 Footer.displayName = 'Footer';
+
+function FooterItem({ item }: { item: FooterLink }) {
+  const content = item.url ? (
+    <a href={item.url} target={item.target} rel="noopener" id={item.id}>
```
Comment (Clarity-89) [inline public/app/core/components/Footer/Footer.tsx:112]:
```suggestion
    <a href={item.url} target={'_blank'} rel="noopener" id={item.id}>
```
Should we just hardcode `target` as `_blank`? Can't really think of a case where it'd be beneficial to have it configurable.

**Review by Clarity-89 — APPROVED** [review]

**Comment by JoaoSilvaGrafana** [comment]
> * link to /next/ docs for beta versions

@joshhunt What is the difference between `/next` and `/latest` release notes then? 🤔 Just wondering because `/latest` actually doesn't have release notes for `9.0.7` or `8.5.10` while `/next` does...

File: public/app/core/components/Footer/Footer.tsx (hunk 2 above)
Comment (joshhunt) [reply public/app/core/components/Footer/Footer.tsx]: good shout. did this!

**Review by zuchka — APPROVED** [review]
tested and looks awesome. super cool to see the solution to this
