### PR TITLE
RBAC: Add permission to get usage report preview

### LINKED ISSUE #2733: Nightly build titles panel seem to be broken
Interested in trying out a few of the new features in 2.5 so i pulled down the nightly build, but i noticing all the panel titles have gone astray 

image

image

Also see this error when looking in the chrome dev tools
```
Error: [$injector:unpr] Unknown provider: aProvider <- a <- interpolateTemplateVarsFilter
http://errors.angularjs.org/1.4.3/$injector/unpr?p0=aProvider%20%3C-%20a%20%3C-NaNnterpolateTemplateVarsFilter
    at http://grafana-hk.tibra.com/app/app.415e973a.js:9:5834
    at http://grafana-hk.tibra.com/app/app.415e973a.js:9:25174
    at Object.d [as get] (http://grafana-hk.tibra.com/app/app.415e973a.js:9:24344)
    at http://grafana-hk.tibra.com/app/app.415e973a.js:9:25271
    at d (http://grafana-hk.tibra.com/app/app.415e973a.js:9:24344)
    at Object.e [as invoke] (http://grafana-hk.tibra.com/app/app.415e973a.js:9:24681)
    at Object.$get (http://grafana-hk.tibra.com/app/app.415e973a.js:9:23151)
    at Object.e [as invoke] (http://grafana-hk.tibra.com/app/app.415e973a.js:9:24714)
    at http://grafana-hk.tibra.com/app/app.415e973a.js:9:25291
    at Object.d [as get] (http://grafana-hk.tibra.com/app/app.415e973a.js:9:24344)
```
Using  Version: 2.5.0-pre1, Commit: v2.1.2+321-g8174b9f, Build date: 2015-09-11 16:58:45 +1000 AEST

### PR DESCRIPTION
**Pull request by alexanderzobnin**
**What is this feature?**
This PR adds access control to `/api/admin//usage-report-preview` endpoint.
New action is created for accessing this endpoint.

**Why do we need this feature?**
Endpoint should be covered by access control.

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/infra/usagestats/service/accesscontrol.go [hunk 1]
```diff
@@ -0,0 +1,30 @@
+package service
+
+import (
+	"github.com/grafana/grafana/pkg/services/accesscontrol"
+)
+
+const (
+	ActionRead = "server.stats.report:read"
```
Comment (alexanderzobnin) [inline pkg/infra/usagestats/service/accesscontrol.go:8]: Not sure what's a good and clear name for this action. Is it `server.stats` or `server.usagestats`?

Comment (Jguer) [reply pkg/infra/usagestats/service/accesscontrol.go:8]: `usagestats` would be most correct as there's already server stats which is a different endpoint

**Review by Jguer — APPROVED** [review]
Should be good after the action name change
