### PR TITLE
Alerting: Prevent uid collision in migration when db is case-insensitive

### LINKED ISSUE #54680: Error 1062: Duplicate entry '114-xxxxxxxx' for key 'UQE_alert_rule_org_id_uid'
What happened:
I want to update grafana from v7.3.5 to v8.4.6, so I copied history data from our live environment, and then start grafana.
I upgraded grafana from version 8.4.2 to 9.1.0 without unified alerting. DB was cloned before upgrade. Now while trying to enable unified alerting I am getting below error:

level=error msg="Executing migration failed" id="move dashboard alerts to unified alerting" error="Error 1062: Duplicate entry '114-rMBR2ZGVz' for  │
│ logger=migrator t=2022-09-03T03:19:21.502720885Z level=error msg="Exec failed" error="Error 1062: Duplicate entry '114-rMBR2ZGVz' for key 'UQE_alert_rule_org_id_uid'" sql="code migration"        │
│ Failed to start grafana. error: migration failed (id = move dashboard alerts to unified alerting): Error 1062: Duplicate entry '114-rMBR2ZGVz' for key 'UQE_alert_rule_org_id_uid'                 │
│ migration failed (id = move dashboard alerts to unified alerting): Error 1062: Duplicate entry '114-rMBR2ZGVz' for key 'UQE_alert_rule_org_id_uid'

What you expected to happen:
Migration is done successfully with other environment having less data.

How to reproduce it (as minimally and precisely as possible):
GF_UNIFIED_ALERTING_ENABLED: false
  alerting:
    enabled: true  
  unified_alerting:
    enabled: false  
add these values in grafana.ini

Anything else we need to know?:
Production there are 25000 alerts to be migrated across 150 organisations and it is failing for multiple org_ids. DB size is 50 GB.

Environment:

Grafana version: v9.1.0
Data source type & version:
OS Grafana is installed on: linux
User OS & Browser:
Grafana plugins:
plugins:
  - instana-datasource
  - farski-blendstat-panel
  - yesoreyeram-boomtable-panel
  - jdbranham-diagram-panel
  - natel-discrete-panel
  - agenty-flowcharting-panel
  - pierosavi-imageit-panel
  - simpod-json-datasource
  - marcusolsson-json-datasource
  - grafana-piechart-panel
  - natel-plotly-panel 
  - vonage-status-panel
  - grafana-worldmap-panel
  - https://github.com/GoshPosh/grafana-meta-queries/archive/refs/tags/0.0.9.zip;goshposh-metaqueries-datasource
  - flant-statusmap-panel
  - grafana-athena-datasource
  - grafana-timestream-datasource
Others:

### PR DESCRIPTION
**Pull request by JacobsonMT**
**What is this feature?**

This improves our duplicate uid detection during legacy migration to include checking for case-insensitive duplicates.

**Why do we need this feature?**

Two factors come into play that cause sporadic uid conflicts during legacy alert migration:
- MySQL and MySQL-compatible backends use case-insensitive collation.
- Our short uid generator is not a uniform RNG and generates uids in such a way that generations in quick succession have a higher probability of creating similar uids.

Normally we would be guaranteed unique short uid generation, however if the source alphabet contains duplicate characters (for example, if we use case-insensitive comparison) this guarantee is void.

Generating even ~1000 uids in quick succession is nearly guaranteed to create a case-insensitive duplicate.

**Which issue(s) does this PR fix?**:

Fixes #54680

### CODE REVIEW

**Review by yuri-tceretian — COMMENTED** [review]
LGTM

**Review by yuri-tceretian — APPROVED** [review]

File: pkg/services/sqlstore/migrations/ualert/ualert_test.go [hunk 1]
```diff
@@ -172,3 +173,24 @@ func Test_getAlertFolderNameFromDashboard(t *testing.T) {
 		require.Contains(t, folder, dash.Uid)
 	})
 }
+
+func Test_shortUIDCaseInsensitiveConflicts(t *testing.T) {
+	// Note: Because of the nature of this test, if it's flaky it could be because of an issue in uid generation not necessarily a faulty test.
```
Comment (armandgrillet) [inline pkg/services/sqlstore/migrations/ualert/ualert_test.go:178]: That worries me due to Grafana policy around flaky tests. Is it going to be flaky?

Comment (JacobsonMT) [reply pkg/services/sqlstore/migrations/ualert/ualert_test.go:178]: I think this note is misleading, I'll remove it. It could be flaky, but if it is it will be in the opposite sense to how we generally mean it: the test might pass even if `generateUid` is broken if somehow no duplicates are generated in the 10000 UIDs.
