### PR TITLE
Scenes/LibraryPanels: Fix issue where library panels plugin type was not set correctly

### LINKED ISSUE #82907: Library panels that are table or gauge does not work in scenes.
image

Library panels that are tables or gauges does not work in scenes.

### PR DESCRIPTION
**Pull request by kaydelaney**
Fixes an issue where the plugin type wasn't being set after library panel models were fetched.

Closes #82907

### CODE REVIEW

File: public/app/features/dashboard-scene/scene/LibraryVizPanel.tsx [hunk 1]
```diff
@@ -41,16 +41,17 @@ export class LibraryVizPanel extends SceneObjectBase<LibraryVizPanelState> {
   };
 
   private async loadLibraryPanelFromPanelModel() {
-    const vizPanel = this.state.panel;
+    let vizPanel = this.state.panel;
     try {
       const libPanel = await getLibraryPanel(this.state.uid, true);
       const libPanelModel = new PanelModel(libPanel.model);
-      vizPanel.setState({
+      vizPanel = vizPanel.clone({
```
Comment (oscarkilhed) [inline public/app/features/dashboard-scene/scene/LibraryVizPanel.tsx:48]: This is interesting. I tried setting the pluginId as well, but did not do this clone. I don't quite understand why it's needed.

**Review by oscarkilhed — APPROVED** [review]
Thank you @kaydelaney!

File: public/app/features/dashboard-scene/scene/LibraryVizPanel.tsx (hunk 1 above)
Comment (oscarkilhed) [reply public/app/features/dashboard-scene/scene/LibraryVizPanel.tsx:48]: Thank you for the explanation!
