### PR TITLE
Floating UI: Update to use the `.main-view` as a boundary

### LINKED ISSUE #98366: Tooltip: Incorrect positioning when page is scrolled
### What happened?

Refresh interval picker slides sideways

Reproduction video: https://youtu.be/Q5jAh8c3uEA

### What did you expect to happen?

The picker to be opened from the arrow to going downwards, or anyhow with no overlap with existing UI.

### Did this work before?

Not sure, I think it did

### How do we reproduce it?

1. Open dashboard
2. Scroll to the bottom (Might have something to do with rows)
3. Observe picker no longer being open at the expected place

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: `https://youtu.be/Q5jAh8c3uEA`
OS: Windows 11 23H2
Browser: Chrome Version 131.0.6778.205 (Official Build) (64-bit)

### Grafana platform?

A downloaded binary

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by leventebalogh**
Fixes https://github.com/grafana/grafana/issues/98366

### What changed?

There was an issue related to using the `Dropdown` component in the dashboard toolbars: it was flickering during scrolling (flipping) - however there were no view changes that would have justified it. Also updated [the currently suggested way by floating-ui for using together `flip()` and `shift()`.](https://floating-ui.com/docs/flip#combining-with-shift)

As far as I understood this was because the `body` is set to `height: 100%`, but then it's scrolled out of the screen as the user scrolls, and it causes flipping for drop-down menus.
Screenshot 2025-09-15 at 13 28 18

This PR is changing the `boundary` for the `Dropdowns` to point to the `.main-view` - however maybe a more appropriate solution would be to adjust the styling around the body, so it's not scrolled out of the view?

**Before**

https://github.com/user-attachments/assets/d8f31823-9506-43d9-bab7-e53f844a89e7

**After**

https://github.com/user-attachments/assets/d45a3ba8-8d2a-4a2c-9498-3e930ea76f05

### CODE REVIEW

**Comment by dprokop** [comment]
@grafana/grafana-frontend-platform - can we get some help from you reviewing this? Thank you!

File: public/app/core/components/AppChrome/AppChrome.tsx [hunk 1]
```diff
@@ -87,6 +87,7 @@ export function AppChrome({ children }: Props) {
   // doesn't get re-mounted when chromeless goes from true to false.
   return (
     <div
+      id={floatingUtils.BOUNDARY_ELEMENT_ID}
```
Comment (joshhunt) [inline public/app/core/components/AppChrome/AppChrome.tsx:90]: nice

**Review by joshhunt — APPROVED** [review]
Excellent work both!!! 👏 

@leventebalogh Thanks for FINALLY fixing this very old bug!!

File: packages/grafana-ui/src/components/DateTimePickers/DatePickerWithInput/DatePickerWithInput.tsx [hunk 2]
```diff
@@ -31,21 +32,15 @@ export const DatePickerWithInput = forwardRef<HTMLInputElement, DatePickerWithIn
...
     // see https://floating-ui.com/docs/arrow#order
-    const middleware = [
-      flip({
-        // see https://floating-ui.com/docs/flip#combining-with-shift
-        crossAxis: false,
-        boundary: document.body,
-      }),
-      shift(),
-    ];
+    const middleware = [...getPositioningMiddleware(placement)];
```
Comment (samsch) [inline packages/grafana-ui/src/components/DateTimePickers/DatePickerWithInput/DatePickerWithInput.tsx]: in the places where `getPositioningMiddleware(placement)` is the only middleware, i don't think we need to spread it into a new array since it returns a new array anyway.

Comment (ashharrison90) [reply packages/grafana-ui/src/components/DateTimePickers/DatePickerWithInput/DatePickerWithInput.tsx]: yeah i left it spread to make it easier to extend later, but you're right 👍

**Review by samsch — APPROVED** [review]

**Review by leventebalogh — COMMENTED** [review]
Really nice work @ashharrison90 🚀
