### PR TITLE
Prometheus: Fix numeric values in raw prometheus view which are being formatted as text

### LINKED ISSUE #69660: Prometheus: inconsistent quantile (le) format
### 
# What went wrong?

**What happened**:

Quantile formats are inconsistent between legend format and the new prometheus raw view. E.g. the chart legend shows `le="24.999999999999996"` but the list view has `le="25.0"`.
image.

Additionally larger values will display in exponential notation while the raw view does not
image

We should also check other numeric label values as well.

  - 

**What did you expect to happen**:
Formats should be consistent.
  - 

Thanks to @bboreham for the heads up

### 
# How do we reproduce it?

View series that has quantile (le) label in explorer, note differences between panel legend and raw view.

### 
# What Grafana version are you using?

v10

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by gtk-grafana**
**What is this feature?**
Fixes bug formatting label values in prometheus raw instant view in explore.

**Why do we need this feature?**
Raw prometheus view should always output valid queries, so whatever values we get from prometheus we need to display in the frontend.

**Who is this feature for?**
Prometheus users in Explore UI.

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/grafana/issues/69660

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by gtk-grafana** [comment]
@leeoniya I saw you made some changes in the `getRawPrometheusListItemsFromDataFrame` recently, wanna help with the review? :P
I think this approach should work, we just check if the `DisplayValue` `numeric` prop is NaN before running the formattedValueToString which always returns the `text` prop.

File: public/app/features/explore/PrometheusListView/RawListItem.tsx [hunk 1]
```diff
@@ -115,10 +115,12 @@ const RawListItem = ({ listItemData, listKey, totalNumberOfValues, valueLabels,
   };
 
   // Convert the object back into a string
-  const stringRep = `${__name__}{${attributeValues.map((value) => {
-    // For histograms the string representation currently in this object is not directly queryable in all situations, leading to broken copied queries. Omitting the attribute from the copied result gives a query which returns all le values, which I assume to be a more common use case.
-    return value.key !== 'le' ? `${value.key}="${transformCopyValue(value.value)}"` : '';
-  })}}`;
+  const stringRep = `${__name__}{${attributeValues
+    .filter((value) => value.key !== 'le')
```
Comment (gtk-grafana) [inline public/app/features/explore/PrometheusListView/RawListItem.tsx:119]: So I actually fixed another bug here, if you copied a series with an "le" it would leave in the extra comma. But I can't remember why we're excluding the "le", maybe just on the assumption that the user would want the whole histogram? Maybe we just kill this filter now, I bet the problem was introduced by outputting the text representation which wouldn't work in a prom query.

**Review by gelicia — APPROVED** [review]

File: public/app/features/explore/PrometheusListView/RawListItem.tsx (hunk 1 above)
Comment (gtk-grafana) [reply public/app/features/explore/PrometheusListView/RawListItem.tsx:119]: I implemented the above change, but you can't see it because github is having issues

**Review by bohandley — APPROVED** [review]
LGTM!
