### PR TITLE
Explore: Only update pane's instance of Inspector

### LINKED ISSUE #38917: Explore: Query inspector in split view is not split
**What happened**:
Inspected two Loki queries, in a split view in Explore.
The Query Inspector's _Query_ tab's contents is updated in both splits when refreshing.

**What you expected to happen**:
The Query Inspector's _Query_ tab should only update for the split view which is being refreshed.

**How to reproduce it (as minimally and precisely as possible)**:
- inspect two Loki queries side-by-side in Explore
- click _Inspector_ on both views
- hit _Refresh_ from the _Query_ tab
- see both split views updating

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.2 (103f8fa094)
- Data source type & version: Loki
- OS Grafana is installed on: Linux
- User OS & Browser: Linux/Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by gelicia**
**What is this feature?**

The query inspector was built assuming there would be only one instance of it available on the screen at a time. In Explore, there is a split view that allows for the inspector to be there twice. As a result of the internal subscription logic, refreshing the data refreshes both instances with the same data, so they are always in sync. 

This will check the request ID the query response has, and if the query URL also has a requestID appended onto it, it will check that one starts with the other. Grafana will append an index number to request IDs, so it won't be an exact match.

**Why do we need this feature?**

Both query inspectors always showing the same data twice is a bug.

**Which issue(s) does this PR fix?**:

Fixes #38917

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/inspector/QueryInspector.tsx [hunk 1]
```diff
@@ -19,6 +20,7 @@ interface ExecutedQueryInfo {
 }
 
 interface Props {
+  instanceId?: string; // Must match the prefix of the requestId of the query being inspected. For updating only one instance of the inspector in case of multiple instances, ie Explore split view
```
Comment (gelicia) [inline public/app/features/inspector/QueryInspector.tsx:23]: I was really torn with the name on this. Ideally it should include `requestId` but opted for something more indicating it's use, since most places won't use it. Let me know if you disagree

**Comment by ifrost** [comment]
When mixed data source is selected I see no results in the inspector. Seems to be caused by MixedDataSource overriding the requestId [here](https://github.com/grafana/grafana/blob/f8faacd54a3ac1ac7ae523014c72f0830f562609/public/app/plugins/datasource/mixed/MixedDataSource.ts#L73).

Screenshot 2024-01-09 at 13 58 55

**Comment by gelicia** [comment]
> When mixed data source is selected I see no results in the inspector. Seems to be caused by MixedDataSource overriding the requestId [here]

@ifrost The template for generating the mixed datasource request ID was duplicated a little, so I moved it to something exportable, then use that in Explore to generate the prefix when appropriate. Let me know what you think!

File: public/app/features/explore/ExploreQueryInspector.tsx [hunk 2]
```diff
@@ -71,7 +74,11 @@ export function ExploreQueryInspector(props: Props) {
     value: 'query',
     icon: 'info-circle',
     content: (
-      <QueryInspector data={queryResponse} onRefreshQuery={() => props.runQueries({ exploreId: props.exploreId })} />
+      <QueryInspector
+        instanceId={isMixed ? mixedRequestId(0, requestIdGenerator(exploreId)) : requestIdGenerator(exploreId)}
```
Comment (ifrost) [inline public/app/features/explore/ExploreQueryInspector.tsx:78]: I think that ideally `ExploreQueryInspector` should not depend on the implementation details of the data source (and check if it's mixed or not). What is more, it seems that any data source can override the request ID, not only mixed so we cannot guarantee it'd work in every case.

Would it be possible to instead of passing the generated `requestId`, keep track of the returned, latest response's `requestId` after the query is run and pass only the requestId to `ExploreQueryInspector`?

Comment (gelicia) [reply public/app/features/explore/ExploreQueryInspector.tsx]: 🤦 the query inspector has the response and thus the requestId already. cleaned this up quite a bit

**Comment by Elfo404** [comment]
i'm still experiencing some weird behavior (althogh a bit different from before) where the second inspector gets updated with the queries from the second one:

https://github.com/grafana/grafana/assets/1170767/e853d514-6b62-4b59-bcb7-6e156508d80f


also it still doesn't seem to work with mixed datasource 😿

File: public/app/features/explore/ExploreQueryInspector.tsx (hunk 2 above)
Comment (gelicia) [reply public/app/features/explore/ExploreQueryInspector.tsx:86]: @ifrost actually, we can't do this. The mixed datasource takes whatever the incoming request ID is and adds a prefix to it. So whatever requestID explore makes and sends to the query and the query inspector gets changed by the datasource. Thus, the response request ID is not the same - it always is the requestID post that change.

Everything has a requestID and I can ensure the logic the mixed datasource uses and what gets passed around is the same, but I can't rely on requestId alone for this. Let me know if you have any other ideas - I know ideally the ExploreQueryInspector shouldn't know/care if the datasource is mixed but Id rather have this logic kept within Explore.

Comment (ifrost) [reply public/app/features/explore/ExploreQueryInspector.tsx:86]: > The mixed datasource takes whatever the incoming request ID is and adds a prefix to it.

I meant changing the logic so instead of passing `requestId` to the inspector that "should match" the one that was used: make a request and take the `requestId` but from the response object after the request is made (maybe [this](https://github.com/grafana/grafana/blob/6ee2bd4d29413882164db55833034985ad30b4e6/packages/grafana-data/src/types/panel.ts#L54)?) and store in redux store. 

This, however, assumes we can get the same response object with the same `requestId` in 2 places:
- as result of`runRequest`,
- and in the inspector stream. 

But if I understand correctly, you're saying there's no way to match responses like this.

I think QueryInspector should not parse `response.config.url`, and rather that information should be attached to the response. We should be able to get the same information attached to responses we handle in Explore. In other words I think to solve this problem we need to have a clear way to have an `id` (like `requestId`) attached to the response to can clearly identify it in various places. This way Explore would know what was the latest loaded `id` in a pane (by storing it in the state) and pass the same id to the inspector. But it seems that would require a lot of refactoring out of the scope.

File: public/app/features/inspector/QueryInspector.tsx [hunk 3]
```diff
@@ -47,9 +49,21 @@ export class QueryInspector extends PureComponent<Props, State> {
   }
 
   componentDidMount() {
+    const { instanceId } = this.props;
     this.subs.add(
       backendSrv.getInspectorStream().subscribe({
-        next: (response) => this.onDataSourceResponse(response),
+        next: (response) => {
+          let update = true;
+          if (instanceId && response?.config?.url) {
```
Comment (Elfo404) [inline public/app/features/inspector/QueryInspector.tsx:57]: this "should" make this work even is the `instanceId` prop changes
```suggestion
          if (this.props.instanceId && response?.config?.url) {
```

**Comment by gelicia** [comment]
@grafana/dashboards-squad : can someone take a look at the changes to the inspector here?

**Comment by ifrost** [comment]
Explore changes LGTM 👍

**Review by ifrost — APPROVED** [review]

**Review by harisrozajac — APPROVED** [review]
Works great, and looks good on @grafana/dashboards-squad side!
