### PR TITLE
Library Panel: Fix issue where library panels did not display panel links.

### LINKED ISSUE #98483: Dashboards & Libary Panels: "Panel Links" not working/visible on "Libarý Panels", Normal Panels are OK
### What happened?

"Panel Links" not working/visible on "Libarý Panels", Normal Panels are OK

I created panels with "Panel links" so far so good.  Everthing is working fine. 
After converting them into "Libary-Panels" the "Panel Links" are not visible anymore. 

If i checked the "Libary Panel" in "Panel-JSON view" the "link" Area is present.
It worked in a earlier Version, after an Update the behavior changed. 

I tested it with "Table" and "Bar Chart" same result ob both types

### What did you expect to happen?

It should work in "libary panels" the same way as in "normal panels"

### Did this work before?

yes, it worked in an earlier Version but i don't know the number

### How do we reproduce it?

1. created panels with "Panel links"
2. converting them into "Libary-Panels" 
3. after refresh the screen the "Panel Link" is no longer visible

### Is the bug inside a dashboard panel?

yes

### Environment (with versions)?

Grafana: v11.4.0
OS: Debian
Browser: EDGE

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

table, bar chart

### PR DESCRIPTION
**Pull request by yincongcyincong**
Fixes #98483

### CODE REVIEW

File: public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts [hunk 1]
```diff
@@ -333,7 +333,7 @@ export function buildGridItemForPanel(panel: PanelModel): DashboardGridItem {
 
   if (panel.libraryPanel) {
     vizPanelState.$behaviors!.push(
-      new LibraryPanelBehavior({ uid: panel.libraryPanel.uid, name: panel.libraryPanel.name })
+      new LibraryPanelBehavior({ uid: panel.libraryPanel.uid, name: panel.libraryPanel.name, titleItems: titleItems })
```
Comment (torkelo) [inline public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts:336]: not sure we need this part

File: public/app/features/dashboard-scene/scene/LibraryPanelBehavior.tsx [hunk 2]
```diff
@@ -48,6 +50,14 @@ export class LibraryPanelBehavior extends SceneObjectBase<LibraryPanelBehaviorSt
 
     const libPanelModel = new PanelModel(libPanel.model);
 
+    if (libPanelModel.links) {
+      this.state.titleItems?.forEach(titleItem => {
+        if (titleItem instanceof VizPanelLinks) {
+          titleItem.setState({rawLinks: libPanelModel.links ?? []})
+        }
+      })
```
Comment (torkelo) [inline public/app/features/dashboard-scene/scene/LibraryPanelBehavior.tsx:58]: this seems wrong, we should set the titleItems on the vizPanelState

Comment (yincongcyincong) [reply public/app/features/dashboard-scene/scene/LibraryPanelBehavior.tsx]: thanks for your review. i think you are right. we should add titleItem at [LibraryPanelBehavior.tsx]. i modified it. please take a look.

**Review by oscarkilhed — APPROVED** [review]
Tested this and it works as expected. I added a test that should be been there before this PR to avoid this issue :)

**Comment by oscarkilhed** [comment]
Thank you @yincongcyincong for your contribution!
