### PR TITLE
AnnoListPanel: Fix 'Within Time Range' option

### LINKED ISSUE #28172: Annotations List Panel aka annolist (alpha) - all annotations are shown disregard "Within Time Range" setting
**What happened**:
All annotations are shown disregard "Within Time Range" setting

**What you expected to happen**:
Only annotations within current timerange should be shown

**How to reproduce it (as minimally and precisely as possible)**:
1. Create some annotation
2. Observe it in annolist panel
2. Change current timerange several days ago, for example - to yesterday
3. The annotation still shown!!!

**Anything else we need to know?**:
On below image:
1. Within Time Range is ON
2. Current Time Range  is 2020-10-07 00:00:00 to 2020-10-07 23:59:59 (Oct 7)
3. All annotations are created Oct-8 and Oct-11, but still shown!!!

image

**Environment**:
- Grafana version:  6.1.3
- Data source type & version: Grafana
- OS Grafana is installed on: Linux
- User OS & Browser: Mac/Chrome
- Grafana plugins: Annotations List (alpha)
- Others:

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Fixes the 'Within Time Range' option of the `AnnoListPanel` so the current time range is respected.

**Which issue(s) this PR fixes**:
Closes #28172

### CODE REVIEW

File: public/app/plugins/panel/annolist/AnnoListPanel.tsx [hunk 1]
```diff
@@ -74,7 +75,7 @@ export class AnnoListPanel extends PureComponent<Props, State> {
 
     let timeInfo = '';
     if (options.onlyInTimeRange) {
-      const { timeRange } = this.props;
+      const timeRange = getTimeSrv().timeRange();
```
Comment (torkelo) [inline public/app/plugins/panel/annolist/AnnoListPanel.tsx:78]: Time range is passed via props, it should be up to date, if not we need to fix it in PanelChrome

Comment (kaydelaney) [reply public/app/plugins/panel/annolist/AnnoListPanel.tsx:78]: So, not sure my understanding of this is correct, but what's happening as far as I can tell is this:
In the `renderPanel` method of `PanelChrome`, we pass the following as the `timeRange` prop to `PanelComponent`:
```ts
const timeRange = data.timeRange || this.timeSrv.timeRange();
```
The problem seems to be that `data` is only updated when a query is run (via `onDataUpdate`) which doesn't happen with the AnnoListPanel since it's not for visualizing datasource query results. Instead, `data.timeRange` is always just what it is initialized to, `getDefaultTimeRange()`.
I think if we instead initialized it to `undefined` that would fix the underlying problem, but let me know if I've made a mistake in my reasoning.

Comment (torkelo) [reply public/app/plugins/panel/annolist/AnnoListPanel.tsx:78]: Yes, the fix needs to be done in PanelChrome so this is fixed for non data panels

Comment (kaydelaney) [reply public/app/plugins/panel/annolist/AnnoListPanel.tsx:78]: Some thoughts:
Typically, with plugins that make queries, the `timeRange` is included as part of the resulting `PanelData`, and this new `timeRange` is passed to the `PanelComponent` when `PanelChrome` renders the panel.
For other plugins, like the `AnnoList` panel, what is currently happening is `timeRange` just stays as the initialized value (`getDefaultTimeRange()`), or if you change the panel to a querying plugin and modify the time range then switch back to the `AnnoList`, it will now have that `timeRange`. That latter point highlights a problem with just initializing `timeRange` to undefined, besides typing considerations, as we just end up stuck with the previous plugin’s time range if we switch from it to `AnnoList`.
The only solution I can think of (that's not potentially a breaking change) besides what's already been committed to this PR is for the plugin to make a "dummy" query but I imagine this would be very hacky and not ideal.

Comment (torkelo) [reply public/app/plugins/panel/annolist/AnnoListPanel.tsx:78]: So onRefresh when we do not execute the query: https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashgrid/PanelChrome.tsx#L212 

We should update the time range (from timeSrv) before rendering the panel

**Comment by kaydelaney** [comment]
The commit I just pushed fixes the issue while you're in edit mode, but annoyingly when you return to the dashboard the time range resets to whatever it was before you entered edit mode.

File: public/app/features/dashboard/dashgrid/PanelChrome.tsx [hunk 2]
```diff
@@ -209,7 +209,12 @@ export class PanelChrome extends Component<Props, State> {
       });
     } else {
       // The panel should render on refresh as well if it doesn't have a query, like clock panel
-      this.onRender();
+      this.setState(
+        (prevState) => ({
+          data: { ...prevState.data, timeRange: this.timeSrv.timeRange() },
+        }),
+        this.onRender
```
Comment (torkelo) [inline public/app/features/dashboard/dashgrid/PanelChrome.tsx:216]: think we can skip this onRender as the above will trigger a  state update same as onRender

**Review by torkelo — APPROVED** [review]
Looks good!
