### PR TITLE
Dashboards: SchemaV2 - Fix stateless queries for mixed ds

### LINKED ISSUE #102969: V2 stateless queries: Panel with mixed queries does not work
Given the attached v2 json, data sources for panel with mixed data source queries are not resolved. No queries are executed.

<details>
<summary>dashboard.json</summary>

```json
{
    "annotations": [],
    "cursorSync": "Off",
    "description": "",
    "editable": true,
    "elements": {
      "panel-1": {
        "kind": "Panel",
        "spec": {
          "data": {
            "kind": "QueryGroup",
            "spec": {
              "queries": [
                {
                  "kind": "PanelQuery",
                  "spec": {
                    "hidden": false,
                    "query": {
                      "kind": "grafana-testdata-datasource",
                      "spec": {}
                    },
                    "refId": "A"
                  }
                },
                {
                  "kind": "PanelQuery",
                  "spec": {
                    "hidden": false,
                    "query": {
                      "kind": "prometheus",
                      "spec": {
                        "disableTextWrap": false,
                        "editorMode": "builder",
                        "expr": "rate(promhttp_metric_handler_requests_total[$__rate_interval])",
                        "fullMetaSearch": false,
                        "includeNullMetadata": false,
                        "legendFormat": "__auto",
                        "range": true,
                        "useBackend": false
                      }
                    },
                    "refId": "B"
                  }
                }
              ],
              "queryOptions": {},
              "transformations": []
            }
          },
          "description": "",
          "id": 1,
          "links": [],
          "title": "New panel",
          "vizConfig": {
            "kind": "timeseries",
            "spec": {
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisBorderShow": false,
                    "axisCenteredZero": false,
                    "axisColorMode": "text",
                    "axisLabel": "",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "barWidthFactor": 0.6,
                    "drawStyle": "line",
                    "fillOpacity": 0,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "insertNulls": false,
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "auto",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "none"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green"
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  }
                },
                "overrides": []
              },
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom",
                  "showLegend": true
                },
                "tooltip": {
                  "hideZeros": false,
                  "mode": "single",
                  "sort": "none"
                }
              },
              "pluginVersion": "12.0.0-pre"
            }
          }
        }
      }
    },
    "layout": {
      "kind": "GridLayout",
      "spec": {
        "items": [
          {
            "kind": "GridLayoutItem",
            "spec": {
              "element": {
                "kind": "ElementReference",
                "name": "panel-1"
              },
              "height": 8,
              "width": 12,
              "x": 0,
              "y": 0
            }
          }
        ]
      }
    },
    "links": [],
    "liveNow": false,
    "preload": false,
    "tags": [],
    "timeSettings": {
      "autoRefresh": "",
      "autoRefreshIntervals": [
        "5s",
        "10s",
        "30s",
        "1m",
        "5m",
        "15m",
        "30m",
        "1h",
        "2h",
        "1d"
      ],
      "fiscalYearStartMonth": 0,
      "from": "now-6h",
      "hideTimepicker": false,
      "timezone": "browser",
      "to": "now"
    },
    "title": "Dashboard with mixed ds",
    "variables": []
  }

```
</details>

### PR DESCRIPTION
**Pull request by axelavargas**
When dealing with stateless queries and mixed datasources, queries were not resolved.

#### Approach
When rendering a panel in scenes, we use createPanelDataProvider which resolves the datasource for the panel query runner using:
`const datasource = getPanelDataSource(panelKind); -- had the best guess logic`

However, when resolving queries, we omitted the logic for best datasource guess:

```
dataProvider = new SceneQueryRunner({
  datasource,
  queries: targets.map(panelQueryKindToSceneQuery), // Missing the best guess
```

- [x] Fix issue
- [x] Add unit test

Fixes: #102969

### CODE REVIEW

File: public/app/features/dashboard-scene/serialization/layoutSerializers/utils.ts [hunk 1]
```diff
@@ -219,10 +215,25 @@ export function getRuntimeVariableDataSource(variable: QueryVariableKind): DataS
...
+    const defaultDatasource = config.bootData.settings.defaultDatasource;
+    const dsList = config.bootData.settings.datasources;
+    // this is look up by type
+    const bestGuess = Object.values(dsList).find((ds) => ds.meta.id === query.spec.query.kind);
+    datasource = bestGuess ? { uid: bestGuess.uid, type: bestGuess.meta.id } : dsList[defaultDatasource];
+  } else {
+    datasource = query.spec.datasource;
+  }
+  return datasource;
+}
```
Comment (dprokop) [inline public/app/features/dashboard-scene/serialization/layoutSerializers/utils.ts:231]: A similar code is used in two more place. can we unify?

**Review by ivanortegaalba — COMMENTED** [review]
After these changes, this unit test started failing 🤔 

https://github.com/grafana/grafana/actions/runs/14403881218/job/40395562855?pr=103885

**Comment by axelavargas** [comment]
> After these changes, this unit test started failing 🤔
> 
> [grafana/grafana/actions/runs/14403881218/job/40395562855?pr=103885](https://github.com/grafana/grafana/actions/runs/14403881218/job/40395562855?pr=103885)
I am missing mocking the `bootDataConfig`

File: public/app/features/dashboard-scene/serialization/layoutSerializers/utils.ts (hunk 1 above)
Comment (axelavargas) [reply public/app/features/dashboard-scene/serialization/layoutSerializers/utils.ts]: @dprokop I did the refactor here [`c127dad` (#103885)](https://github.com/grafana/grafana/pull/103885/commits/c127dad0845fc2ccc394ba80a33456637ad14633)

**Review by dprokop — APPROVED** [review]
@axelavargas - tested the case described in the bug report and it now works. Thanks for applying my feedback!

**Review by harisrozajac — APPROVED** [review]
nice work! 🚀
