### PR TITLE
Security: Use same cookie settings for all cookies

### LINKED ISSUE #19744: 'cookie_secure' has no impact on 'redirect_to' cookie
**What happened**: After a security scan we noticed the cookies were not secure. We enabled it through `cookie_secure` and all Grafana cookies are secure now. 

However one cookie `redirect_to` is still not secure.

**What you expected to happen**: After enabling `cookie_secure` the `redirect_to` cookie should be secure as well.

**How to reproduce it (as minimally and precisely as possible)**:
- Enable HTTPS
- Configure SSL certificate and key
- set `cookie_secure` on `true`
- Perform a cURL to the Grafana server:
```
$ curl -I https://GRAFANA-URL/
HTTP/1.1 302 Found
Location: /login
Set-Cookie: grafana_sess=XXXXXXXXX; Path=/; HttpOnly; Secure
Set-Cookie: redirect_to=%252F; Path=/; HttpOnly
Date: Thu, 10 Oct 2019 12:11:32 GMT
Content-Type: text/plain; charset=utf-8
```

**Anything else we need to know?**: The `redirect_to` cookie should be secure as well if `cookie_secure` is enabled.

**Environment**:
- Grafana version: production 5.0.4, tested it on 6.4.2 as well
- Data source type & version: Influx
- OS Grafana is installed on: Debian 9
- User OS & Browser: Mac OS X / Chrome
- Grafana plugins: PieChart
- Others: n/a

### PR DESCRIPTION
**Pull request by jeffdesc**
**What this PR does / why we need it**: For security reasons the `Secure` flag in the `redirect_to` cookie should be enforced together when the `cookie_secure` is enabled.

**Which issue(s) this PR fixes**: #19744 

Fixes #19744

### CODE REVIEW

File: pkg/api/login_oauth.go [hunk 1]
```diff
@@ -214,7 +214,15 @@ func (hs *HTTPServer) OAuthLogin(ctx *m.ReqContext) {
 	metrics.MApiLoginOAuth.Inc()
 
 	if redirectTo, _ := url.QueryUnescape(ctx.GetCookie("redirect_to")); len(redirectTo) > 0 {
-		ctx.SetCookie("redirect_to", "", -1, setting.AppSubUrl+"/")
+		ctx.Resp.Header().Del("Set-Cookie")
```
Comment (marefr) [inline pkg/api/login_oauth.go]: You cannot delete the "Set-Cookie" header since `hs.loginUserWithUser` above sets the auth cookie using `http.SetCookie`-.

File: pkg/api/login.go [hunk 2]
```diff
@@ -135,7 +144,16 @@ func (hs *HTTPServer) LoginPost(c *models.ReqContext, cmd dtos.LoginCommand) Res
 
 	if redirectTo, _ := url.QueryUnescape(c.GetCookie("redirect_to")); len(redirectTo) > 0 {
 		result["redirectUrl"] = redirectTo
-		c.SetCookie("redirect_to", "", -1, setting.AppSubUrl+"/")
+		c.Resp.Header().Del("Set-Cookie")
```
Comment (marefr) [inline pkg/api/login.go]: You cannot delete the "Set-Cookie" header since `hs.loginUserWithUser` above sets the auth cookie using `http.SetCookie`. If you delete the "Set-Cookie" header here you basically logging out the user.

File: pkg/api/login_oauth.go (hunk 1 above)
Comment (marefr) [inline pkg/api/login_oauth.go]: You cannot delete the "Set-Cookie" header since `hs.loginUserWithUser` above sets the auth cookie using `http.SetCookie`. If you delete the "Set-Cookie" header here you basically logging out the user.

**Review by marefr — CHANGES_REQUESTED** [review]
Reasonable changes, but please see comments.

File: pkg/api/login.go (hunk 2 above)
Comment (jeffdesc) [reply pkg/api/login.go]: Make sense, I've deleted the 'Set-Cookie' delete in the code. Thanks for noticing.

File: pkg/api/login_oauth.go (hunk 1 above)
Comment (jeffdesc) [reply pkg/api/login_oauth.go]: Make sense, I've deleted the 'Set-Cookie' delete in the code. Thanks for noticing.

File: pkg/api/login.go [hunk 3]
```diff
@@ -63,7 +63,15 @@ func (hs *HTTPServer) LoginView(c *models.ReqContext) {
 	}
 
 	if redirectTo, _ := url.QueryUnescape(c.GetCookie("redirect_to")); len(redirectTo) > 0 {
-		c.SetCookie("redirect_to", "", -1, setting.AppSubUrl+"/")
+		cookie := http.Cookie{
```
Comment (marefr) [inline pkg/api/login.go]: `HttpOnly: true,` missing

File: pkg/api/login_oauth.go [hunk 4]
```diff
@@ -214,7 +214,14 @@ func (hs *HTTPServer) OAuthLogin(ctx *m.ReqContext) {
 	metrics.MApiLoginOAuth.Inc()
 
 	if redirectTo, _ := url.QueryUnescape(ctx.GetCookie("redirect_to")); len(redirectTo) > 0 {
-		ctx.SetCookie("redirect_to", "", -1, setting.AppSubUrl+"/")
+		cookie := http.Cookie{
```
Comment (marefr) [inline pkg/api/login_oauth.go]: `HttpOnly: true,` missing

**Review by marefr — CHANGES_REQUESTED** [review]
Thanks. Looks good. Some minor request for changes, see comments.

File: pkg/api/login.go (hunk 3 above)
Comment (jeffdesc) [reply pkg/api/login.go]: I converted the line as it was before, I assume it was not needed. But I've added it.

File: pkg/api/login_oauth.go (hunk 4 above)
Comment (jeffdesc) [reply pkg/api/login_oauth.go]: I converted the line as it was before, I assume it was not needed. But I've added it.

File: pkg/api/login.go [hunk 5]
```diff
@@ -135,7 +144,15 @@ func (hs *HTTPServer) LoginPost(c *models.ReqContext, cmd dtos.LoginCommand) Res
...
+			Name:     "redirect_to",
+			Value:    "",
+			HttpOnly: true,
+			Path:     setting.AppSubUrl + "/",
+			Secure:   setting.CookieSecure,
+			MaxAge:   -1,
+		}
+		http.SetCookie(c.Resp, &cookie)
```
Comment (torkelo) [inline pkg/api/login.go]: Looks like this code is duplicated in two places, can we extract this to a function named getEmptyRedirectCookie()

Comment (torkelo) [reply pkg/api/login.go]: or just getRedirectCookie(value string)

**Comment by marefr** [comment]
@jeffdesc are you planning to continue working with the last changes requested in https://github.com/grafana/grafana/pull/19787#pullrequestreview-305039266?

**Review by aknuds1 — APPROVED** [review]
LGTM

File: pkg/middleware/auth.go [hunk 6]
```diff
@@ -47,7 +48,16 @@ func notAuthorized(c *m.ReqContext) {
...
+	c.Resp.Header().Del("Set-Cookie")
+	cookie := http.Cookie{
+		Name:     "redirect_to",
+		Value:    url.QueryEscape(setting.AppSubUrl + c.Req.RequestURI),
+		HttpOnly: true,
+		Path:     setting.AppSubUrl + "/",
+		Secure:   setting.CookieSecure,
+		MaxAge:   0,
+	}
+	http.SetCookie(c.Resp, &cookie)
```
Comment (marefr) [inline pkg/middleware/auth.go]: This part seems like we have in other places. This is also not setting the same_site attribute.

We have https://github.com/grafana/grafana/blob/master/pkg/middleware/middleware.go#L243-L270  which is doing similar things but specific to session cookie - this should be able to use shared code for creating and writing the actual cookie. 

We also have https://github.com/grafana/grafana/blob/fd2131c1e32e7d47aad5d35ad0babdb396d6f3c4/pkg/api/login_oauth.go#L228-L245 which does similar things.

Possible to extract the part that at least creates the cookie, maybe to util package or something?

File: pkg/api/login.go [hunk 7]
```diff
@@ -82,10 +82,10 @@ func (hs *HTTPServer) LoginView(c *models.ReqContext) {
 			if err := validateRedirectTo(redirectTo); err != nil {
 				viewData.Settings["loginError"] = err.Error()
 				c.HTML(200, getViewIndex(), viewData)
-				c.SetCookie("redirect_to", "", -1, setting.AppSubUrl+"/")
+				hs.deleteCookie(c.Resp, "redirect_to", http.SameSiteDefaultMode)
```
Comment (marefr) [inline pkg/api/login.go]: All of the `hs.deleteCookie` in this file are providing the wrong same sate attribute, should be taken from Grafana settings.

**Review by marefr — CHANGES_REQUESTED** [review]
Some minor things. See comments.

File: pkg/middleware/middleware.go [hunk 8]
```diff
@@ -254,19 +253,7 @@ func WriteSessionCookie(ctx *models.ReqContext, value string, maxLifetimeDays in
...
-		Path:     setting.AppSubUrl + "/",
-		Secure:   setting.CookieSecure,
-		MaxAge:   maxAge,
-	}
-	if setting.CookieSameSite != http.SameSiteDefaultMode {
-		cookie.SameSite = setting.CookieSameSite
-	}
-
-	http.SetCookie(ctx.Resp, &cookie)
+	WriteCookie(ctx.Resp, setting.LoginCookieName, url.QueryEscape(value), maxAge, nil)
```
Comment (marefr) [inline pkg/middleware/middleware.go]: This must include proper config as last argument. Know it's tricky since you only have `setting.Cfg` available in some handlers and some not. Maybe you can add override functions in middleware/cookie.go to either use `setting.Cfg` or global `setting` that we eventually want to move away from.

File: pkg/middleware/auth.go [hunk 9]
```diff
@@ -47,7 +47,8 @@ func notAuthorized(c *m.ReqContext) {
 		return
 	}
 
-	c.SetCookie("redirect_to", url.QueryEscape(setting.AppSubUrl+c.Req.RequestURI), 0, setting.AppSubUrl+"/", nil, false, true)
+	c.Resp.Header().Del("Set-Cookie")
+	WriteCookie(c.Resp, "redirect_to", url.QueryEscape(setting.AppSubUrl+c.Req.RequestURI), 0, nil)
```
Comment (marefr) [inline pkg/middleware/auth.go]: This must include proper config as last argument. Know it's tricky since you only have `setting.Cfg` available in some handlers and some not. Maybe you can add override functions in middleware/cookie.go to either use `setting.Cfg` or global `setting` that we eventually want to move away from.

File: pkg/middleware/auth.go [hunk 10]
```diff
@@ -47,7 +47,8 @@ func notAuthorized(c *m.ReqContext) {
 		return
 	}
 
-	c.SetCookie("redirect_to", url.QueryEscape(setting.AppSubUrl+c.Req.RequestURI), 0, setting.AppSubUrl+"/", nil, false, true)
+	c.Resp.Header().Del("Set-Cookie")
```
Comment (marefr) [inline pkg/middleware/auth.go]: Why wasn't this needed before, or was it?

**Review by marefr — CHANGES_REQUESTED** [review]
Great. Much better :+1: Some minor things left to address, see comments.

File: pkg/middleware/auth.go (hunk 10 above)
Comment (papagian) [reply pkg/middleware/auth.go]: I think it is not needed.
It was introduced by this [commit](https://github.com/grafana/grafana/pull/19787/commits/f80d23e83617e3607b9a4961e676c6b337f282ba) and I hesitated to delete it because I was not sure.

**Review by marefr — CHANGES_REQUESTED** [review]
LGTM. Great work! :+1: 

Left a comment though about one problem.

File: pkg/api/login_oauth.go [hunk 11]
```diff
@@ -82,7 +83,7 @@ func (hs *HTTPServer) OAuthLogin(ctx *m.ReqContext) {
 
 	// delete cookie
 	ctx.Resp.Header().Del("Set-Cookie")
-	hs.deleteCookie(ctx.Resp, OauthStateCookieName, hs.Cfg.CookieSameSite)
+	middleware.DeleteCookie(ctx.Resp, OauthStateCookieName, hs.cookieOptionsFromCfg)
```
[the remark this answers is not in the document]
Comment (papagian) [reply pkg/api/login_oauth.go]: I will have a look.

[the remark this answers is not in the document]
Comment (papagian) [reply pkg/api/login_oauth.go]: @marefr 
I have tested also in the master and the cookie is not deleted.

[the remark this answers is not in the document]
Comment (marefr) [reply pkg/api/login_oauth.go]: Okay. I still think it should be deleted

[the remark this answers is not in the document]
Comment (papagian) [reply pkg/api/login_oauth.go]: Ok, should I delete also [this](https://github.com/grafana/grafana/blob/99986eb1c612fa05204205babaf1c163a7ffaf75/pkg/middleware/middleware.go#L255) one then?

[the remark this answers is not in the document]
Comment (marefr) [reply pkg/api/login_oauth.go]: Yeah

**Review by marefr — APPROVED** [review]
LGTM
