### PR TITLE
Fix: when reloading page make sure that time picker history is converted to dateTime.

### LINKED ISSUE #22289: New updated time picker loads recently used absolute ranges in wrong timezone
**What happened**: Recently used absolute time ranges are wrong when loaded from browser local storage.

**What you expected to happen**: Recently used absolute time ranges should remain consistent.

**How to reproduce it (as minimally and precisely as possible)**:
1. Access Grafana 6.6.1 from a machine set to a non-UTC timezone (tested with offset +11).
1. View any dashboard.
1. Open time picker, choose any `Absolute time range`, then `Apply time range`.
1. Open time picker again, observe the correct time range under `Recently used absolute ranges`.
1. Refresh the page (`cmd-R`) to force recently used ranges to be loaded from local storage.
1. Open time picker again, observe times on the recently used range have had UTC offset subtracted. In my case the times went backwards by 11 hours.

The last two steps can be repeated indefinitely, resulting in the times getting further and further away from the original range.

**Anything else we need to know?**:

As an example, I selected the absolute time range `2020-02-18 12:00:00 to 2020-02-18 13:00:00` using the picker. After reloading the page, the most recently used absolute time range had changed to `2020-02-18 01:00:00 to 2020-02-18 02:00:00`.

Checking the `grafana.dashboard.timepicker.history` key in my browser's local storage shows recent time ranges are stored in UTC time: 

image

The problem seems to be these saved times are not converted to my local timezone after being loaded from local storage.

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Prometheus 2.13.1
- OS Grafana is installed on: Docker (official `grafana/grafana` image)
- User OS & Browser: macOS 10.14.6, Chrome 80.0.3987.106
- Grafana plugins: grafana-clock-panel, bessler-pictureit-panel
- Others:

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
When you filter the dashboard by absolute time range via the TimePicker. Those values are stored in the TimePicker history. Everything works as planned until you refresh the page. Then we read the new values from local storage without converting those values to the DateTime (moment) type. 

So later when displaying the value to the user the timeZone isn't respected. This should be fixed by making sure that we always sends DateTime (moment) values to the TimePicker. Regardless if we do a page reload or adding new values.

**Which issue(s) this PR fixes**:
Fixes #22289

**Special notes for your reviewer**:
Maybe not super good that we need to iterate the history list on each `TimePickerWithHistory` rendering but it is only 4 items so I don't this this should be to much of an performance hit.

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
LGTM

File: public/app/core/components/TimePicker/TimePickerWithHistory.tsx [hunk 1]
```diff
@@ -25,6 +25,21 @@ export const TimePickerWithHistory: React.FC<Props> = props => {
...
+    }
+
+    return {
+      from: dateTime(time.from),
+      to: dateTime(time.to),
+      raw: time.raw,
+    };
+  });
+}
+
```
Comment (hugohaggmark) [inline public/app/core/components/TimePicker/TimePickerWithHistory.tsx]: Nit: maybe add some tests for this?

**Review by hugohaggmark — APPROVED** [review]
LGTM! Left a small nit that you might want to consider
