### PR TITLE
TimeSeries: Fix fill below for dataframes with name

### LINKED ISSUE #34916: Time series panel: fillBelowTo fails whan data frame contains name property
This is  a followup to https://github.com/grafana/grafana/pull/34901

fillBelowTo config uses getDisplayName calculated based on the aligned data frame (https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/TimeSeries/utils.ts#L266). The details of this issue are described in #34901 but the gist is that the display names used in the panel options (calculated on the original frames) are different from the ones used by UPlotConfig to configure the fillBelowTo bands when there is a `name` property provided on the data frame from the datasource.

For that to be fixed we need to use the original data frame and fields to create the names map and configure the bands. In general, we should use original data frame in every possible case outside of the GraphNG context.

Screenshot of the failing band:
image

Dashboard for reproduction:
```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 456,
  "links": [],
  "panels": [
    {
      "datasource": "Google Sheets",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "always",
            "spanNulls": true,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "B Temp"
            },
            "properties": [
              {
                "id": "custom.fillBelowTo",
                "value": "A RH"
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltip": {
          "mode": "single"
        }
      },
      "targets": [
        {
          "cacheDurationSeconds": 300,
          "refId": "A",
          "spreadsheet": "1iNs5qpI2kYzNKCXH9NP6bsbJPn_rJsJaGbbJkTdlevs"
        },
        {
          "cacheDurationSeconds": 300,
          "hide": false,
          "refId": "B",
          "spreadsheet": "1jF_XiWZnuQm3zw8Olg9LJu4KgL0Zaum5xaDM75xZSGo"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "refresh": false,
  "schemaVersion": 30,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "2021-05-16T21:59:59.477Z",
    "to": "2021-05-16T22:00:08.348Z"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Fill below to sheets",
  "uid": "grGqh9qMz",
  "version": 3
}
```

### PR DESCRIPTION
**Pull request by oscarkilhed**
**What this PR does / why we need it**:
The fill below to config does not work when there are named fields in the aligned dataframe.
This PR makes the config prep use the non cached way to calculate the field names for the aligned frames, because running the cached version over the aligned frames messes up the cache. It then adds a reference to the original name of the field from the original dataframes so that we can find what field to fill to from the config.

**Which issue(s) this PR fixes**:
Fixes #34916

### CODE REVIEW

File: packages/grafana-ui/src/components/uPlot/config/UPlotConfigBuilder.ts [hunk 1]
```diff
@@ -227,6 +227,7 @@ type UPlotConfigPrepOpts<T extends Record<string, any> = {}> = {
   timeZone: TimeZone;
   getTimeRange: () => TimeRange;
   eventBus: EventBus;
+  allFrames?: DataFrame[];
```
Comment (dprokop) [inline packages/grafana-ui/src/components/uPlot/config/UPlotConfigBuilder.ts:230]: Would make this a non-optional field I think

File: packages/grafana-ui/src/components/TimeSeries/utils.ts [hunk 2]
```diff
@@ -152,10 +153,11 @@ export const preparePlotConfigBuilder: UPlotConfigPrepFn<{ sync: DashboardCursor
 
     if (customConfig.fillBelowTo) {
       if (!indexByName) {
-        indexByName = getNamesToFieldIndex(frame);
+        indexByName = getNamesToFieldIndex(frame, allFrames);
       }
-      const t = indexByName.get(getFieldDisplayName(field, frame));
-      const b = indexByName.get(customConfig.fillBelowTo);
+
+      const t = indexByName.alignedNames.get(calculateFieldDisplayName(field, frame));
```
Comment (dprokop) [inline packages/grafana-ui/src/components/TimeSeries/utils.ts:159]: seems like the `alignedNames` ain't used anywhere apart from the check below. Think we should get rid of it.

File: packages/grafana-ui/src/components/TimeSeries/utils.ts [hunk 3]
```diff
@@ -259,10 +261,25 @@ export const preparePlotConfigBuilder: UPlotConfigPrepFn<{ sync: DashboardCursor
...
+  allFrames?: DataFrame[]
+): { alignedNames: Map<string, number>; originNames: Map<string, number> } {
+  const alignedNames = new Map<string, number>();
+  const originNames = new Map<string, number>();
   for (let i = 0; i < frame.fields.length; i++) {
-    names.set(getFieldDisplayName(frame.fields[i], frame), i);
+    const origin = frame.fields[i].state?.origin;
+    if (allFrames && origin) {
+      originNames.set(
+        calculateFieldDisplayName(
```
Comment (dprokop) [inline packages/grafana-ui/src/components/TimeSeries/utils.ts:274]: In this case, since we know `frame` exists, this means that `allFrames` exist too. I think there's no need for using the `calculateFieldDisplayName` but just getFieldDisplayName and utilize the cache if it was calculated for allFrames field already. This would save us exposing the `calculateFieldDisplayName` function.

**Review by dprokop — COMMENTED** [review]
Works as expected, good stuff @oscarkilhed. Left few comments you may want to consider :)

File: packages/grafana-ui/src/components/TimeSeries/utils.ts (hunk 3 above)
Comment (oscarkilhed) [reply packages/grafana-ui/src/components/TimeSeries/utils.ts:274]: We can't run the getFieldDisplayName over the dataframe as it will change the state that is by reference. Before this PR when you add the fillBelowTo config property `A RH` changes to `RH A` and `B Temp` changes to `Temp B` everywhere in the graph. I previously had a way to disable the updating of the cache, but all it really did was make getFieldDisplayName into calculateFieldDisplayName.

File: packages/grafana-ui/src/components/GraphNG/GraphNG.tsx [hunk 4]
```diff
@@ -38,7 +38,7 @@ export interface GraphNGProps extends Themeable2 {
   fields?: XYFieldMatchers; // default will assume timeseries data
   onLegendClick?: (event: GraphNGLegendEvent) => void;
   children?: (builder: UPlotConfigBuilder, alignedFrame: DataFrame) => React.ReactNode;
-  prepConfig: (alignedFrame: DataFrame, getTimeRange: () => TimeRange) => UPlotConfigBuilder;
+  prepConfig: (alignedFrame: DataFrame, getTimeRange: () => TimeRange, allFrames?: DataFrame[]) => UPlotConfigBuilder;
```
[the remark this answers is not in the document]
Comment (oscarkilhed) [reply packages/grafana-ui/src/components/GraphNG/GraphNG.tsx:41]: I was just worried adding required parameters would break stuff.

File: packages/grafana-ui/src/components/TimeSeries/utils.ts (hunk 3 above)
Comment (dprokop) [reply packages/grafana-ui/src/components/TimeSeries/utils.ts:274]: The issue with changing from A RH to RH A was caused by calling the getDisplayName on a field (with the already cached state) against aligned data frame. But since the aligned data frame has indexes to both frame and field within the original data frame, this should no longer be an issue if you call getFieldDisplayName on **original** field and **original** frame.

File: packages/grafana-ui/src/components/GraphNG/GraphNG.tsx [hunk 5]
```diff
@@ -38,7 +38,7 @@ export interface GraphNGProps extends Themeable2 {
   fields?: XYFieldMatchers; // default will assume timeseries data
   onLegendClick?: (event: GraphNGLegendEvent) => void;
   children?: (builder: UPlotConfigBuilder, alignedFrame: DataFrame) => React.ReactNode;
-  prepConfig: (alignedFrame: DataFrame, getTimeRange: () => TimeRange) => UPlotConfigBuilder;
+  prepConfig: (alignedFrame: DataFrame, getTimeRange: () => TimeRange, allFrames: DataFrame[]) => UPlotConfigBuilder;
```
Comment (dprokop) [inline packages/grafana-ui/src/components/GraphNG/GraphNG.tsx:41]: Nit: can you move allFrames to be 2nd argument?

File: packages/grafana-ui/src/components/TimeSeries/utils.ts [hunk 6]
```diff
@@ -259,10 +264,20 @@ export const preparePlotConfigBuilder: UPlotConfigPrepFn<{ sync: DashboardCursor
...
+  const originNames = new Map<string, number>();
   for (let i = 0; i < frame.fields.length; i++) {
-    names.set(getFieldDisplayName(frame.fields[i], frame), i);
+    const origin = frame.fields[i].state?.origin;
+    if (origin) {
+      originNames.set(
+        getFieldDisplayName(
+          allFrames[origin.frameIndex].fields[origin.fieldIndex],
+          allFrames[origin.frameIndex],
+          allFrames
```
Comment (dprokop) [inline packages/grafana-ui/src/components/TimeSeries/utils.ts:276]: Exactly, thanks!

**Review by dprokop — APPROVED** [review]
Awesome, thanks @oscarkilhed !
