### PR TITLE
Dashboards: Prevent row selection when clicking canvas add actions

### LINKED ISSUE #115349: DD : Wrong display of Row config in Edit pane instead of panel config
Reported [here](https://raintank-corp.slack.com/archives/C03KVDHTWAH/p1765806314385269)

Two wrongly displayed:

* When adding a panel to a row (not the first panel, but could replicate with a second) 
* When clicking the arrow next to configure button

https://github.com/user-attachments/assets/d2ead017-eab1-4383-a4e5-340f4ace3ec3

### PR DESCRIPTION
**Pull request by kristinademeshchik**
**What is this feature?**

Stops event propagation on canvas grid add actions to prevent row selection when clicking action buttons.

before:

https://github.com/user-attachments/assets/8bf415ba-ee81-4464-a7fd-51b05452db24

after:

https://github.com/user-attachments/assets/7ddf003e-4b86-4967-a7b5-86d6b37c8eb3

**Why do we need this feature?**

Clicking "Add panel" or "Group panels" buttons inside a row was unintentionally selecting the row.

**Which issue(s) does this PR fix?**:

Fixes #115349

### CODE REVIEW

File: public/app/features/dashboard-scene/scene/layouts-shared/CanvasGridAddActions.tsx [hunk 1]
```diff
@@ -189,7 +194,6 @@ const getStyles = (theme: GrafanaTheme2) => ({
     height: theme.spacing(5),
     bottom: 0,
     left: 0,
-    right: 0,
```
Comment (kristinademeshchik) [inline public/app/features/dashboard-scene/scene/layouts-shared/CanvasGridAddActions.tsx:192]: since we don’t want the events to propagate, we now need to eliminate the dead area

File: public/app/features/dashboard-scene/scene/layouts-shared/CanvasGridAddActions.tsx [hunk 2]
```diff
@@ -59,7 +59,12 @@ export function CanvasGridAddActions({ layoutManager }: Props) {
   }, [layoutManager]);
 
   return (
-    <div className={cx(styles.addAction, 'dashboard-canvas-add-button')}>
+    <div
+      className={cx(styles.addAction, 'dashboard-canvas-add-button')}
+      onPointerDown={(evt) => {
```
Comment (grafakus) [inline public/app/features/dashboard-scene/scene/layouts-shared/CanvasGridAddActions.tsx]: For clarity, what do you think about capturing both `onPointerDown` and `onPointerUp`, to prevent both `RowItemRenderer` handlers to be executed? Currently it works because the pointer distance check in `RowItemRenderer` returns true.

Comment (kristinademeshchik) [reply public/app/features/dashboard-scene/scene/layouts-shared/CanvasGridAddActions.tsx]: oh that's actually a really good point, let me update that

Comment (kristinademeshchik) [reply public/app/features/dashboard-scene/scene/layouts-shared/CanvasGridAddActions.tsx]: updated ✅

File: packages/grafana-ui/src/components/PanelChrome/PanelChrome.tsx [hunk 3]
```diff
@@ -248,15 +248,17 @@ export function PanelChrome({
 
   const onContentPointerDown = React.useCallback(
     (evt: React.PointerEvent) => {
-      // Ignore clicks inside buttons, links, canvas and svg elments
+      // When selected, ignore clicks inside buttons, links, canvas and svg elments
       // This does prevent a clicks inside a graphs from selecting panel as there is normal div above the canvas element that intercepts the click
-      if (evt.target instanceof Element && evt.target.closest('button,a,canvas,svg')) {
+      if (isSelected && evt.target instanceof Element && evt.target.closest('button,a,canvas,svg')) {
```
Comment (grafakus) [inline packages/grafana-ui/src/components/PanelChrome/PanelChrome.tsx:253]: It makes sense to me but I'm not sure if it was intentional in the first place (being able to interact with the panel series/buttons without selecting it).

**Review by grafakus — APPROVED** [review]
LGTM! Just left a couple of minor comments.

File: packages/grafana-ui/src/components/PanelChrome/PanelChrome.tsx (hunk 3 above)
Comment (kristinademeshchik) [reply packages/grafana-ui/src/components/PanelChrome/PanelChrome.tsx:253]: The button in the header still acts the same - triggers context menu without selecting the panel 
I can keep this pr open for a few more days to hear other folks feedback on this change 

also, I believe this now mimics row item behaviour:

https://github.com/grafana/grafana/blob/main/public/app/features/dashboard-scene/scene/layout-rows/RowItemRenderer.tsx#L106-L110

**Review by harisrozajac — APPROVED** [review]

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/20604268434)
- Version: 12.4.0-20604268434
