### PR TITLE
Generic OAuth: Prevent adding duplicated users

### LINKED ISSUE #23077: Generic OAuth: Creating multiple user auth rows for the same user and provider
**What happened**:
Noticed in the `user_auth` database table that there were multiple rows for my user with `auth_module=oauth_generic_oauth`. On top of that, each time I login all the rows for my user and auth_models is updated which seems strange. 

| id | user_id | auth_module         | auth_id             | created        | o_auth_access_token | o_auth_refresh_token | o_auth_token_type   | o_auth_expiry | 
|----|---------|---------------------|---------------------|----------------|---------------------|----------------------|---------------------|---------------| 
| 20 | 24     | oauth_generic_oauth | | 2020-03-25 15:41:03 | `<access token>` | `<refresh token>`     | `<token type>`          | 2020-03-26 15:41:03 |               | 
| 21 | 24      | oauth_generic_oauth | | 2020-03-25 15:41:03 | `<access token>` | `<refresh token>`     | `<token type>`          | 2020-03-26 15:41:03 |               | 
| 22 | 24      | oauth_generic_oauth | | 2020-03-25 15:41:03 | `<access token>` | `<refresh token>`     | `<token type>`         | 2020-03-26 15:41:03 |               | 

**What you expected to happen**:
Only one row for the combination of `user_id`, `auth_module` and `auth_id`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Login with a Generic OAuth provider. 
1. Logout
1. Login with same Generic OAuth provider in step 1.
1. Inspect `user_auth` database table. 

**Anything else we need to know?**:
This resolves to `false` in Generic OAuth use case: https://github.com/grafana/grafana/blob/4c2b191a8332aa66a671944908bd5d12947cf44a/pkg/services/sqlstore/user_auth.go#L31

Further down below this happens which at the end insert a new row in `user_auth` table:
https://github.com/grafana/grafana/blob/4c2b191a8332aa66a671944908bd5d12947cf44a/pkg/services/sqlstore/user_auth.go#L72-L113

Then later, all user_auth rows for that user and `auth_module` are updated if auth provider returned an OAuth token:  
https://github.com/grafana/grafana/blob/4c2b191a8332aa66a671944908bd5d12947cf44a/pkg/services/login/login.go#L85-L90

All in all, I find this very weird and wonder why [this](https://github.com/grafana/grafana/blob/4c2b191a8332aa66a671944908bd5d12947cf44a/pkg/services/sqlstore/user_auth.go#L31) logic exists. The only thing I can think of is supporting multiple Generic OAuth provider, but that's not something we do anyway. This is something we should fix.

In addition, we also need to think about if or how we need a migration to remove all duplicate rows. Had a customer reporting having 35000 rows for a single Generic OAuth user!

On another note, the `user_auth` table is in need of some refactoring/love. Only have a created column, no updated column. The created column is updated when a row is updated as explained above. This table also holds OAuth tokens and is related to another feature/problem #20515

Also related to #12131

**Environment**:
- Grafana version: master (bdb5659)

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

The purpose of this PR is to prevent adding duplicated users in `user_auth` column, when logging in. 
Essentially, since we'll have to deal with many duplicated entries already, we add a check where:

image

Notes:

1. Check for `auth_id` is now removed, since no auth_id exists when using Generic OAuth. This was the main cause of the problem, since every time a new user with Generic OAuth login existed was re-added on the database.
2. The new _DELETE_ operation, can be potentially removed in the future. 

**Which issue(s) this PR fixes**:

Fixes #23077

**Special notes for your reviewer**:

Steps to reproduce:

* Make sure you have a Generic OAuth provider config ready. (The most easy and straight-forward one should be to add a Bitbucket config)
* Set up the `[auth.generic_oauth]` config in your `custom.ini` file inside grafana repo.
* Make sure you are on master, then try to login and logout 3-4 times.
* Then go to `grafana.db`, browse `user_auth` table, and you'll see something like:

| id | user_id | auth_module         | auth_id             | created        | o_auth_access_token | o_auth_refresh_token | o_auth_token_type   | o_auth_expiry | 
|----|---------|---------------------|---------------------|----------------|---------------------|----------------------|---------------------|---------------| 
| 33 | 4 | oauth_generic_oauth | | 2021-03-24 12:02:25 | <o_auth_access_token> | <o_auth_refresh_token> | <o_auth_token_type> | 2021-03-24 14:02:11 | |
| 33 | 4 | oauth_generic_oauth | | 2021-03-24 12:02:25 | <o_auth_access_token> | <o_auth_refresh_token> | <o_auth_token_type> | 2021-03-24 14:02:11 |  |
| 33 | 4 | oauth_generic_oauth | | 2021-03-24 12:02:25 | <o_auth_access_token> | <o_auth_refresh_token> | <o_auth_token_type> | 2021-03-24 14:02:11 |  |

* Checkout branch and run against it.
* Try to login again.
* You'll see:

| id | user_id | auth_module         | auth_id             | created        | o_auth_access_token | o_auth_refresh_token | o_auth_token_type   | o_auth_expiry | 
|----|---------|---------------------|---------------------|----------------|---------------------|----------------------|---------------------|---------------| 
| 33 | 4 | oauth_generic_oauth | | 2021-03-24 12:22:25 | <o_auth_access_token> | <o_auth_refresh_token> | <o_auth_token_type> | 2021-03-24 14:22:11 | |

### CODE REVIEW

File: pkg/services/sqlstore/user_auth.go [hunk 1]
```diff
@@ -151,6 +151,13 @@ func GetAuthInfo(query *models.GetAuthInfoQuery) error {
 	if err != nil {
 		return err
 	}
+	if has {
+		_, err := x.Desc("created").Exec("DELETE FROM user_auth WHERE o_auth_access_token = ? AND rowid NOT IN (SELECT MIN(rowid) FROM user_auth GROUP BY o_auth_access_token)", userAuth.OAuthAccessToken)
```
Comment (marefr) [inline pkg/services/sqlstore/user_auth.go:155]: Is `rowid` something supported in sqlite? Never seen this. Does it work with mysql and postgres as well?

Comment (dsotirakis) [reply pkg/services/sqlstore/user_auth.go:155]: Oh, I think it's not supported on Postgres (but supported in the other two) :/ 
Let me try and fix that.

Comment (marefr) [reply pkg/services/sqlstore/user_auth.go:155]: Have been thinking about the deleting of old duplicate rows and whether that's needed given we have workarounds in the issue for cleaning that up. If we just start with making sure to fix that no more duplicates are created we have fixed the biggest problem. We can decide on the delete later maybe?

Comment (dsotirakis) [reply pkg/services/sqlstore/user_auth.go:155]: Maybe... Also can think about adding an update column by then. Try and run it again without this part then, only with this added --> https://github.com/grafana/grafana/pull/32286/files#diff-7f4243c0fd4c4d7435e078fb10c3743fb2350bb4b6091de5cfafdc3679416558R32

File: pkg/services/sqlstore/user_auth.go [hunk 2]
```diff
@@ -29,7 +29,7 @@ func GetUserByAuthInfo(query *models.GetUserByAuthInfoQuery) error {
 	authQuery := &models.GetAuthInfoQuery{}
 
 	// Try to find the user by auth module and id first
-	if query.AuthModule != "" && query.AuthId != "" {
+	if query.AuthModule != "" {
```
Comment (marefr) [inline pkg/services/sqlstore/user_auth.go:32]: Changing this would mean that `authQuery` will contain only a filter for auth module. Why? We're using xorm and on line 150 the resulting sql statement would be `select * from user_auth where auth_module = 'generic_oauth'`. Given you have 10 different users in this table using generic oauth it could delete rows on line 44. Feels like a generic_oauth user potentially could get the wrong row returned. There are tests in place but none of them seems to test this use case.

Maybe it would make sense to have a special handling `else if AuthModule=generic oauth` making sure to filter on auth module and user id?

I might be wrong and haven't tested it yet.

Comment (dsotirakis) [reply pkg/services/sqlstore/user_auth.go:32]: Hm, on line 43 though, there's 
```
if query.UserId != 0 && query.UserId != authQuery.Result.UserId { ... }
```
which will be only accessed if there's an error getting auth info.

This will be false, since query.UserId **==** authQuery.Result.UserId if the user is found, no?

Comment (dsotirakis) [reply pkg/services/sqlstore/user_auth.go:32]: Created `user_auth` entries from both Github and Bitbucket OAuth on the same session. Github adds an `auth_id`, and it seems to work without problems as well.

Comment (marefr) [reply pkg/services/sqlstore/user_auth.go:32]: I temporarily disabled the deletion. Also added a print of the executed SQL:
```diff
diff --git a/pkg/services/sqlstore/user_auth.go b/pkg/services/sqlstore/user_auth.go
index cfd466bf05..60492c1104 100644
--- a/pkg/services/sqlstore/user_auth.go
+++ b/pkg/services/sqlstore/user_auth.go
@@ -3,6 +3,7 @@ package sqlstore
 import (
        "encoding/base64"
        "errors"
+       "fmt"
        "time"
 
        "github.com/grafana/grafana/pkg/bus"
@@ -147,16 +148,19 @@ func GetAuthInfo(query *models.GetAuthInfoQuery) error {
                AuthModule: query.AuthModule,
                AuthId:     query.AuthId,
        }
-       has, err := x.Desc("created").Get(userAuth)
+       sess := x.NewSession()
+       has, err := sess.Desc("created").Get(userAuth)
        if err != nil {
                return err
        }
-       if has {
-               _, err := x.Desc("created").Exec("DELETE FROM user_auth WHERE o_auth_access_token = ? AND rowid NOT IN (SELECT MIN(rowid) FROM user_auth GROUP BY o_auth_access_token)", userAuth.OAuthAccessToken)
-               if err != nil {
-                       sqlog.Error("Error removing duplicated user_auth entries", "error", err)
-               }
-       }
+       sql, args := sess.LastSQL()
+       fmt.Println("GetAuthInfo", "sql", sql, "args", args)
+       // if has {
+       //      _, err := x.Desc("created").Exec("DELETE FROM user_auth WHERE o_auth_access_token = ? AND rowid NOT IN (SELECT MIN(rowid) FROM user_auth GROUP BY o_auth_access_token)", userAuth.OAuthAccessToken)
+       //      if err != nil {
+       //              sqlog.Error("Error removing duplicated user_auth entries", "error", err)
+       //      }
+       // }
 
        if !has {
                return models.ErrUserNotFound
```

Then I signed in with my generic oauth provider and you can clearly see that it only filters by auth_module column like I was afraid of above:
```
GetAuthInfo sql SELECT `id`, `user_id`, `auth_module`, `auth_id`, `created`, `o_auth_access_token`, `o_auth_refresh_token`, `o_auth_token_type`, `o_auth_expiry` FROM `user_auth` WHERE `auth_module`=? ORDER BY `created` DESC LIMIT 1 args [oauth_generic_oauth]
```

In addition, I received an error and wasn't logged in to Grafana:
`EROR[03-26|16:48:20] UNIQUE constraint failed: user.email     logger=context userId=0 orgId=0 uname=`

The error I think is due to the fact I have rows in user_auth table for two different users using generic_oauth and I think "potentially could get the wrong row returned" as I wrote above was exactly what happened here. But not really sure.

I still think that "have a special handling else if AuthModule=generic oauth making sure to filter on auth module and user id?" is the proper solution. However, the user id is available first after the following has been run https://github.com/grafana/grafana/blob/5ce9fa360dbc1a934fe8f74db8203fe635324a36/pkg/services/sqlstore/user_auth.go#L73-L102

So having a generic oauth check after this to lookup the existing auth_user row would make the most sense I think. WDYT?

Comment (dsotirakis) [reply pkg/services/sqlstore/user_auth.go:32]: Hm yes, I see what you mean. Let me try and do the same and get back with a fix. Thanks! 🙏

File: pkg/services/sqlstore/user_auth.go [hunk 3]
```diff
@@ -101,8 +101,21 @@ func GetUserByAuthInfo(query *models.GetUserByAuthInfoQuery) error {
 		return models.ErrUserNotFound
 	}
 
+	// Special case for generic oauth duplicates
+	if query.AuthModule == "oauth_generic_oauth" && user.Id != 0 {
```
Comment (dsotirakis) [inline pkg/services/sqlstore/user_auth.go:105]: @marefr I think this fixes it - tested and seems to not add a new entry.

However, my concern is, what happens when you have same email and login name from two different oauth sources? In that case, a different entry is added (as it should be and we would expect) but they share a `user_id`, which I think is wrong? Shouldn't they have different `user_id` since they use different oauth providers?

File: pkg/services/sqlstore/user_auth.go [hunk 4]
```diff
@@ -101,8 +101,24 @@ func GetUserByAuthInfo(query *models.GetUserByAuthInfoQuery) error {
...
+				UserId:     user.Id,
+				AuthModule: query.AuthModule,
+				AuthId:     query.AuthId,
+			}
+			if err := UpdateAuthInfo(cmd2); err != nil {
+				return err
+			}
+		}
+		// create authInfo record to link accounts
+	} else if authQuery.Result == nil && query.AuthModule != "" {
```
Comment (dsotirakis) [inline pkg/services/sqlstore/user_auth.go:121]: Trying to make this less ugly.

File: pkg/services/sqlstore/user_auth.go (hunk 3 above)
Comment (marefr) [reply pkg/services/sqlstore/user_auth.go:106]: > Shouldn't they have different user_id since they use different oauth providers?

It depends. But the user_auth table was added from the beginning to keep external auth providers in sync with Grafana users.

Two different oauth sources will create 2 rows in the auth user_auth table because login with non-generic oauth will add an `auth_id` value which is the unique identifier from third-party auth provider. For generic oauth providing the unique identifier from third-party auth provider is not supported why this empty in user_auth table. Does this make sense?

File: pkg/services/sqlstore/user_auth.go (hunk 2 above)
Comment (marefr) [reply pkg/services/sqlstore/user_auth.go:32]: I still believe this change should be reverted

File: pkg/services/sqlstore/user_auth.go [hunk 5]
```diff
@@ -101,8 +101,24 @@ func GetUserByAuthInfo(query *models.GetUserByAuthInfoQuery) error {
 		return models.ErrUserNotFound
 	}
 
-	// create authInfo record to link accounts
-	if authQuery.Result == nil && query.AuthModule != "" {
+	// Special case for generic oauth duplicates
+	oauthModule := false
+	if query.AuthModule == "oauth_generic_oauth" && user.Id != 0 {
+		oauthModule = true
+		_, err = x.Id(user.Id).Get(user)
```
Comment (marefr) [inline pkg/services/sqlstore/user_auth.go:108]: Think you want to use `GetAuthInfo(authQuery)` and filter by auth module and user id to make sure there exist a row in user_auth for auth_module and user_id.

File: pkg/services/sqlstore/user_auth.go (hunk 2 above)
Comment (dsotirakis) [reply pkg/services/sqlstore/user_auth.go:32]: Ah yes, forgot to remove. Didn't make any difference when I was testing so I left it there

File: pkg/services/sqlstore/user_auth.go (hunk 5 above)
Comment (marefr) [reply pkg/services/sqlstore/user_auth.go:108]: This existing code is a bit confusing. So I looked at how the `GetUserByAuthInfo` is used and it's used here:
https://github.com/grafana/grafana/blob/636be0ed22335c8725412f5832a5bb20fa1c3eab/pkg/services/login/loginservice/loginservice.go#L46-L101

Given that no error is returned and there exist an oauthtoken `updateUserAuth` will be called from there.

So I think that this special case when generic oauth is true we need to `GetAuthInfo` based on auth module and user id which will populate `authQuery.Result`. The `UpdateAuthInfoCommand` shouldn't be needed then. On line 121 if `authQuery.Result` is nil it will insert, otherwise just return the result and eventually the `updateUserAuth` will be called by loginservice.go (if needed)

Let me know if all of this is super confusing :smile:

**Review by marefr — CHANGES_REQUESTED** [review]
Great work with the conversion of tests :tada: 

I added some additional comments. Let me know if you don't understand and we can discuss it.

File: pkg/services/sqlstore/user_auth.go (hunk 5 above)
Comment (dsotirakis) [reply pkg/services/sqlstore/user_auth.go]: A bit complicated, but feel free to have a look again.

File: pkg/services/sqlstore/user_auth.go [hunk 6]
```diff
@@ -29,18 +29,33 @@ func GetUserByAuthInfo(query *models.GetUserByAuthInfoQuery) error {
...
 	// Try to find the user by auth module and id first
-	if query.AuthModule != "" && query.AuthId != "" {
-		authQuery.AuthModule = query.AuthModule
-		authQuery.AuthId = query.AuthId
+	authQuery.AuthModule = query.AuthModule
+	authQuery.AuthId = query.AuthId
 
-		err = GetAuthInfo(authQuery)
-		if !errors.Is(err, models.ErrUserNotFound) {
+	err = GetAuthInfo(authQuery)
```
Comment (marefr) [inline pkg/services/sqlstore/user_auth.go:35]: This could produce `select * from user_auth where auth_module = 'generic_oauth` - same problem as we earlier discussed. Or am I missing something that has changed? I still believe `if query.AuthModule != "" && query.AuthId != "" {` is needed for the non-generic oauth use case.

**Review by marefr — CHANGES_REQUESTED** [review]
See comment and let me know if I misunderstood

File: pkg/services/sqlstore/user_auth.go (hunk 6 above)
Comment (dsotirakis) [reply pkg/services/sqlstore/user_auth.go:35]: * I think the first time `GetAuthInfo` is called, should not search for the `user_id` since it doesn't yet exist, no?
* Yeah, I guess you are right, since otherwise if they are both empty, it will go and select any row from the table.

File: pkg/services/sqlstore/user_auth.go [hunk 7]
```diff
@@ -101,7 +101,12 @@ func GetUserByAuthInfo(query *models.GetUserByAuthInfoQuery) error {
 		return models.ErrUserNotFound
 	}
 
-	// create authInfo record to link accounts
+	// Special case for generic oauth duplicates
+	if query.AuthModule == "oauth_generic_oauth" && user.Id != 0 {
+		authQuery.UserId = user.Id
+		authQuery.AuthModule = query.AuthModule
+		_ = GetAuthInfo(authQuery)
```
Comment (marefr) [inline pkg/services/sqlstore/user_auth.go:108]: Need to handle the possible error condition here.

**Review by marefr — CHANGES_REQUESTED** [review]
Great. Now I think it should work according to my idea. Not sure I'm correct though and that it works :) I will test it manually as well. Added a comment regarding a missing error check.

Would be great to add a test for generic_oauth in sqlstore/user_auth_test.go as well to validate the changes works as expected.

File: pkg/services/sqlstore/user_test.go [hunk 8]
```diff
@@ -8,599 +8,680 @@ import (
...
+	})
 
-				query := models.GetUserByIdQuery{Id: user.Id}
-				getUserError := GetUserById(&query)
-				So(getUserError, ShouldBeNil)
+	ss = InitTestDB(t)
 
-				So(query.Result.IsAdmin, ShouldEqual, true)
-			})
+	t.Run("Testing DB - users with generic oauth tokens", func(t *testing.T) {
```
Comment (marefr) [inline pkg/services/sqlstore/user_test.go:483]: Think this test should be in user_auth.go instead.

**Review by marefr — CHANGES_REQUESTED** [review]
Works as expected :+1: 

Verified no new rows in user_auth is created when signing in with existing generic_oauth user that exists in user_auth and that a new row is created for generic_oauth user when there are no rows in the user_auth table.

One thing left, I added a comment. Otherwise this should be good to merge I think since it prevents adding duplicate rows in the user_auth table. Great work

File: pkg/services/sqlstore/user_auth_test.go [hunk 9]
```diff
@@ -216,8 +218,31 @@ func TestUserAuth(t *testing.T) {
 
 			err = GetAuthInfo(getAuthQuery)
 
-			So(err, ShouldBeNil)
-			So(getAuthQuery.Result.AuthModule, ShouldEqual, "test1")
+			require.Nil(t, err)
+			require.Equal(t, getAuthQuery.Result.AuthModule, "test1")
+		})
+
+		t.Run("Testing DB - users with generic oauth tokens", func(t *testing.T) {
```
Comment (marefr) [inline pkg/services/sqlstore/user_auth_test.go:225]:
```suggestion
		t.Run("Can set & locate by generic oauth auth module and user id", func(t *testing.T) {
```

**Review by marefr — APPROVED** [review]
LGTM left a couple comments/suggestions. 

After this been merged need to think about what's left in regard to duplicate rows

File: pkg/services/sqlstore/user_auth_test.go [hunk 10]
```diff
@@ -216,8 +218,31 @@ func TestUserAuth(t *testing.T) {
...
+			// Find a user to set tokens on
+			login := "loginuser0"
+
+			// Expect to pass since there's a matching login user
+			getTime = func() time.Time { return time.Now().AddDate(0, 0, -2) }
+			query := &models.GetUserByAuthInfoQuery{Login: login, AuthModule: "oauth_generic_oauth", AuthId: ""}
```
[the remark this answers is not in the document]
Comment (dsotirakis) [reply pkg/services/sqlstore/user_auth_test.go:231]: It's used with different `Login` field so we shall create a method / func for that - think it's not necessary?

[the remark this answers is not in the document]
Comment (marefr) [reply pkg/services/sqlstore/user_auth_test.go:231]: Was referring to the magic string `oauth_generic_oauth`. Sorry for being unclear
