### PR TITLE
Dashboard: Add failsafe for slug generation

### LINKED ISSUE #22618: Emoji-named dashboards trigger redirect loop 🐴
**What happened**:

I made a wonderful dashboard, named it 🐴 and saved.

Then ended in a redirect loop, presumably because Grafana tries to redirect me to the proper name, but is confused by my horsing around.

**What you expected to happen**:

Horses! Lots of horses! (Seriously)

Also: to be able to see the dashboard without a redirect loop.

**How to reproduce it (as minimally and precisely as possible)**:

Make a dashboard named 🐴. I assume other emojis have similar problems, but it's fine by me if you exclusively fix this for horse-emojis.

**Anything else we need to know?**:

🐴

**Environment**:
- Grafana version: v6.6.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Chromium on Debian
- Grafana plugins:
- Others:🐴

### PR DESCRIPTION
**Pull request by sakjur**
**What this PR does / why we need it**:

When a dashboard title contains only characters which cannot be converted by the slug library into a URL friendly name we store an empty slug. This is a problem because when trying to open a dashboard with an empty slug the router will throw the client into an infinite loop. This PR adds a failsafe which sets the slug to a base64 variant of the title meaning than any non-empty title will be valid as a dashboard name.

This allows dashboard titles to be part of less-commonly used alphabets (I tried it with cuneiform) or emojis.

Another way to do this would be to escape the unicode to the URL escaped version. I chose not to do that because 1. it triggers a funny bug in search 2. the rendering in the browsers URL bar can be a little bit funny when having zero-width spaces and things like that. Let me know if there's a reason why we'd want to do that instead.

**Which issue(s) this PR fixes**:

Fixes #22618 (general solution, not only for the 🐴 emoji)

**Special notes for your reviewer**:
I used 𒆠 and 🙃 to test the functionality. I also tried with the first Kanji characters appearing on Google when googling Kanji: 漢字, but that seems to already work.

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Nice :+1:

File: pkg/models/dashboards.go [hunk 1]
```diff
@@ -189,7 +190,18 @@ func (dash *Dashboard) UpdateSlug() {
 }
 
 func SlugifyTitle(title string) string {
```
Comment (bergquist) [inline pkg/models/dashboards.go:192]: Tests? :)
