### PR TITLE
Alerting: Update silences creation to support `__alert_rule_uid__` and move into drawer

### LINKED ISSUE #86981: Alerting: Silence preview only updates when you add additional label matchers
### To reproduce:
* Go to create a new silence
* Fill in a label & value for the matching labels fields that are present on the page from first load
* Un-focus the label/value field(s)

### Expected behaviour:
Silenced alert instances are shown as a preview at the bottom of the form

### Actual behaviour:
No preview is shown, and is only fetched when an additional matcher is added

### PR DESCRIPTION
**Pull request by tomratcliffe**
**What is this feature?**

Moves alert rule silence creation into a drawer that pops out when selecting to create a silence from the list view.

**Why do we need this feature?**

We need the ability to create more targeted alert rule silences. The most sensible way to allow this is by tying a silence to an alert rule's UID.

This means it makes more sense to show the silence creation without taking a user away from the list view
image
image

**Which issue(s) does this PR fix?**:

Fixes #86981

### CODE REVIEW

File: public/app/features/alerting/unified/mocks/plugins.ts [hunk 1]
```diff
@@ -1,12 +1,28 @@
...
 import { plugins } from 'app/features/alerting/unified/testSetup/plugins';
 
-export const pluginsHandler = (pluginsArray: PluginMeta[] = plugins) =>
-  http.get<{ pluginId: string }>(`/api/plugins/:pluginId/settings`, ({ params: { pluginId } }) => {
+/**
+ * Returns a handler that maps from plugin ID to PluginMeta, and additionally sets up necessary
+ * config side effects that are expected to come along with this API behaviour
+ */
+export const pluginsHandler = (pluginsArray: PluginMeta[] = plugins) => {
+  plugins.forEach(({ id, baseUrl, info, angular }) => {
```
Comment (tomratcliffe) [inline public/app/features/alerting/unified/mocks/plugins.ts:12]: Interested to hear thoughts on this. It ties the plugin handler setup along with the configuration of the `config` module, but the two kind of _should_ go hand in hand?

File: public/app/features/alerting/unified/mocks/server/configure.ts [hunk 2]
```diff
@@ -13,3 +16,10 @@ export const setAlertmanagerChoices = (alertmanagersChoice: AlertmanagerChoice,
   };
   server.use(alertmanagerChoiceHandler(response));
 };
+
+/**
+ * Makes the mock server respond with different folder access control settings
+ */
+export const setFolderAccessControl = (accessControl: FolderDTO['accessControl']) => {
+  server.use(folderHandler(mockFolder({ hasAcl: true, accessControl })));
+};
```
Comment (tomratcliffe) [inline public/app/features/alerting/unified/mocks/server/configure.ts:25]: I haven't fully decided/worked out how best to configure overriding the behaviour for _one specific_ folder's response. I won't try and solve it here as it's not strictly necessary for the tests we're currently doing.

File: public/app/features/alerting/unified/api/alertRuleApi.ts [hunk 3]
```diff
@@ -206,6 +207,10 @@ export const alertRuleApi = alertingApi.injectEndpoints({
       providesTags: ['CombinedAlertRule'],
     }),
 
+    getGrafanaAlertRule: build.query<RulerGrafanaRuleDTO, { uid: string; ruler?: string }>({
+      query: ({ uid, ruler = GRAFANA_RULES_SOURCE_NAME }) => ({ url: `/api/ruler/${ruler}/api/v1/rule/${uid}` }),
```
Comment (konrad147) [inline public/app/features/alerting/unified/api/alertRuleApi.ts:211]: Finally 🚀

File: public/app/features/alerting/unified/api/alertSilencesApi.ts [hunk 4]
```diff
@@ -47,6 +51,14 @@ export const alertSilencesApi = alertingApi.injectEndpoints({
         data: payload,
       }),
       invalidatesTags: ['AlertmanagerSilences', 'AlertmanagerAlerts'],
+      onQueryStarted: async (arg, { queryFulfilled }) => {
+        try {
+          await queryFulfilled;
+          appEvents.emit(AppEvents.alertSuccess, ['Silence created']);
+        } catch (error) {
+          appEvents.emit(AppEvents.alertError, ['Could not create silence']);
```
Comment (konrad147) [inline public/app/features/alerting/unified/api/alertSilencesApi.ts:59]: Should we track these errors in faro?

File: public/app/features/alerting/unified/components/rules/RuleActionsButtons.tsx [hunk 5]
```diff
@@ -131,6 +136,11 @@ export const RuleActionsButtons = ({ compact, showViewButton, showCopyLinkButton
         }}
       />
       {deleteModal}
+      {isGrafanaRulerRule(rule.rulerRule) && showSilenceDrawer && (
```
[the remark this answers is not in the document]
Comment (konrad147) [reply public/app/features/alerting/unified/components/rules/RuleActionsButtons.tsx:139]: I believe the In-rule silence drawer should be only available for GMA. Mimir/Loki data sources doesn't support that fine-grained permissions and rule-level silences not to mention issues with linking rules generators to alertmanagers
Having said that, I do wonder if we should display the Alertmanager selector in the drawer at all
Technically GMA alerts can be sent to external AMs but then the userflow gets weirs -> The user should silence for each alertmanager separately
wdyt @gillesdemey @soniaAguilarPeiron

File: public/app/features/alerting/unified/components/silences/SilencesDrawer.tsx [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+    <Drawer
+      title="Silence alert rule"
+      subtitle="Configure silences to stop notifications from a particular alert rule."
+      onClose={onClose}
+      size="md"
+    >
+      <Stack gap={2} direction={'column'}>
+        <GrafanaAlertmanagerDeliveryWarning currentAlertmanager={selectedAlertmanager!} />
+
+        <AlertManagerPicker />
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/silences/SilencesDrawer.tsx:36]: As commented above I do wonder if we need the picker or maybe we should only use Grafana built-in AM in that case

File: public/app/features/alerting/unified/components/silences/SilencesEditor.tsx [hunk 7]
```diff
@@ -22,145 +21,142 @@ import {
...
   const [createSilence, { isLoading }] = alertSilencesApi.endpoints.createSilence.useMutation();
-  const [urlSearchParams] = useURLSearchParams();
+  const [getAlertByUid, { data: alertRule }] = alertRuleApi.endpoints.getGrafanaAlertRule.useLazyQuery();
+  const formAPI = useForm({ defaultValues: formValues });
+  const styles = useStyles2(getStyles);
+
+  const { register, handleSubmit, formState, watch, setValue, clearErrors } = formAPI;
+  const duration = watch('duration');
+  const startsAt = watch('startsAt');
+  const endsAt = watch('endsAt');
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/silences/SilencesEditor.tsx:116]: Could be simplified to
```suggestion
  const [duration, startsAt, endsAt] = watch(['duration', 'startsAt', 'endsAt']);
```

File: public/app/features/alerting/unified/components/silences/SilencesEditor.tsx [hunk 8]
```diff
@@ -186,37 +182,19 @@ export const SilencesEditor = ({ silenceId, alertManagerSourceName }: Props) =>
...
   return (
     <FormProvider {...formAPI}>
       <form onSubmit={handleSubmit(onSubmit)}>
-        <FieldSet>
-          <div className={cx(styles.flexRow, styles.silencePeriod)}>
+        <FieldSet className={styles.formContainer}>
+          {alertRule && (
+            <Field label="Alert rule">
+              <div>{alertRule.grafana_alert.title}</div>
+            </Field>
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/silences/SilencesEditor.tsx:194]: I think this component could be more prominent that a regular form field. I find it difficult to spot the rule name. Maybe Deyan could help

File: public/app/features/alerting/unified/api/alertRuleApi.ts (hunk 3 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/api/alertRuleApi.ts:211]: one nit; can we choose a more generic name here? It's _currently_ only for Grafana managed rules but no reason why we couldn't add this in to Mimir either.

File: public/app/features/alerting/unified/hooks/useSilenceNavData.ts [hunk 9]
```diff
@@ -9,20 +9,22 @@ const defaultPageNav: Partial<NavModelItem> = {
...
-  const [pageNav, setPageNav] = useState<Pick<NavModelItem, 'id' | 'text' | 'icon'> | undefined>();
+  const [pageNav, setPageNav] = useState<NavModelItem | undefined>();
 
   useEffect(() => {
     if (path === '/alerting/silence/new') {
       setPageNav({
         ...defaultPageNav,
         id: 'silence-new',
-        text: 'Add silence',
+        text: 'Silence alert rule',
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/hooks/useSilenceNavData.ts:19]: Unrelated to the changes in this PR but silences are actually applied to a list of "labels" and have no relationship with rules at all – should we make those changes in this PR?

/cc @brendamuir

File: public/app/features/alerting/unified/mocks/plugins.ts (hunk 1 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/mocks/plugins.ts:12]: I think it's fine – I've done similar things where the handler also spies on / mocks  the runtime config :)

File: public/app/features/alerting/unified/components/silences/SilencesEditor.tsx (hunk 8 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/components/silences/SilencesEditor.tsx:194]: Dito, came to report the same thing but it looks like Konrad also noticed (or... not noticed 😆)

File: public/app/features/alerting/unified/components/silences/SilencesEditor.tsx [hunk 10]
```diff
@@ -22,145 +21,142 @@ import {
...
+  const ruleUid = silence?.matchers?.find((m) => m.name === MATCHER_ALERT_RULE_UID)?.value;
 
-  const formMatchers = parseQueryParamMatchers(matchers);
-  if (formMatchers.length) {
-    defaults.matchers = formMatchers.map(matcherToMatcherField);
+  const defaultValues = useMemo(() => {
+    if (!silence) {
+      return;
+    }
+    const filteredMatchers = (silence.matchers || []).filter((m) => m.name !== MATCHER_ALERT_RULE_UID);
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/silences/SilencesEditor.tsx:69]: Probably nothing you edited but can this not be an optional chain instead?

File: public/app/features/alerting/unified/components/rules/RuleActionsButtons.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (konrad147) [reply public/app/features/alerting/unified/components/rules/RuleActionsButtons.tsx:139]: RBAC - I almost forgot about it 😄 
RBAC makes it even more tricky - The idea is that the drawer allows to only create so called rule-level silences which are silences tied to a specific rule and cannot impact alerts from other rules
However these rule-level silences are only supported by Grafana Alertmanager so it might be odd to display the drawer for external alertmanagers 🤔

File: public/app/features/alerting/unified/api/alertRuleApi.ts (hunk 3 above)
Comment (tomratcliffe) [reply public/app/features/alerting/unified/api/alertRuleApi.ts:211]: Are you okay with `getAlertRule`? To keep it simple - the parameters will give the rest of the context of what we're fetching, and at it's core we're getting an alert rule

Comment (konrad147) [reply public/app/features/alerting/unified/api/alertRuleApi.ts:211]: > no reason why we couldn't add this in to Mimir either

I think the main reason is the lack of unique identifiers in Mimir

File: public/app/features/alerting/unified/api/alertSilencesApi.ts [hunk 11]
```diff
@@ -47,6 +51,14 @@ export const alertSilencesApi = alertingApi.injectEndpoints({
         data: payload,
       }),
       invalidatesTags: ['AlertmanagerSilences', 'AlertmanagerAlerts'],
+      onQueryStarted: async (arg, { queryFulfilled }) => {
```
[the remark this answers is not in the document]
Comment (tomratcliffe) [reply public/app/features/alerting/unified/api/alertSilencesApi.ts:54]: I've split this out into a separate small PR here: https://github.com/grafana/grafana/pull/87435

File: public/app/features/alerting/unified/hooks/useSilenceNavData.ts (hunk 9 above)
Comment (tomratcliffe) [reply public/app/features/alerting/unified/hooks/useSilenceNavData.ts:19]: (I guess though that the _intent_ here is to silence an alert rule, so it is accurate to label it that way)

File: public/app/features/alerting/unified/components/rules/RuleActionsButtons.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rules/RuleActionsButtons.tsx:139]: I believe we should limit the display of the 'silence alert rule' drawer to scenarios where it's specifically used for silencing a Grafana-managed alert rule (by alert rule UID). There is no alert rule uid for cloud alerts.
However, I see the value in the drawer as an enhancement for creating silences, whether they are from Grafana Alertmanager or not. Therefore, it might be beneficial to expand the drawer's availability to include cloud scenarios as well. In this case, we would adjust the title to 'Create a Silence' and exclude the alert UID matcher functionality.

File: public/app/features/alerting/unified/components/rules/RuleActionsButtons.tsx [hunk 12]
```diff
@@ -131,6 +136,11 @@ export const RuleActionsButtons = ({ compact, showViewButton, showCopyLinkButton
...
+        <AlertmanagerProvider accessType="instance">
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rules/RuleActionsButtons.tsx:140]: I guess the `accessType=instance` might be no longer valid here. It assumes you need the `instance` permission which is not true in this context
I think it should be silence for GMA and instance for external AMs 🤔

File: public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx [hunk 13]
```diff
@@ -14,25 +18,43 @@ import { AmAlertStateTag } from './AmAlertStateTag';
...
 interface Props {
   amSourceName: string;
-  matchers: Matcher[];
+  matchers: MatcherFieldValue[];
+  ruleUid?: string;
 }
 
-export const SilencedInstancesPreview = ({ amSourceName, matchers }: Props) => {
-  const { useGetAlertmanagerAlertsQuery } = alertmanagerApi;
+const useDebouncedDeepCompare = (cb: () => void, debounceMs: number, dependencies: unknown[]) => {
```
[the remark this answers is not in the document]
Comment (konrad147) [reply public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx:25]: Could you add a comment in code why this is needed?

File: public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx [hunk 14]
```diff
@@ -14,25 +18,43 @@ import { AmAlertStateTag } from './AmAlertStateTag';
...
-  } = useGetAlertmanagerAlertsQuery(
-    { amSourceName, filter: { matchers } },
-    { skip: !hasValidMatchers, refetchOnMountOrArgChange: true }
+  const hasValidMatchers = ruleUid || inputMatchers.some((matcher) => matcher.value && matcher.name);
+
+  const [getAlertmanagerAlerts, { currentData: alerts = [], isFetching, isError }] = useLazyQuery();
+
+  useDebouncedDeepCompare(
+    () => {
+      if (hasValidMatchers || ruleUid) {
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx:52]: Isnt' `hasValidMatchers` enough?

File: public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx [hunk 15]
```diff
@@ -14,25 +18,43 @@ import { AmAlertStateTag } from './AmAlertStateTag';
...
+
+  useDebounce(cb, debounceMs, [state]);
+
+  useDeepCompareEffect(() => {
+    setState(dependencies);
+  }, [dependencies]);
+};
+
+export const SilencedInstancesPreview = ({ amSourceName, matchers: inputMatchers, ruleUid }: Props) => {
+  const matchers: Matcher[] = [
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx:36]: This code creates a new instance of `matchers` array every time so maybe the deep compare later or is not needed?

File: public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx [hunk 16]
```diff
@@ -43,18 +65,18 @@ export const SilencedInstancesPreview = ({ amSourceName, matchers }: Props) => {
   return (
     <div>
       <h4 className={styles.title}>
-        Silenced alert instances
+        Affected alert rule instances
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx:68]: Doesn't the text imply that we only display instances of a single rule?
Maybe we should display a slightly different text depending on the presence of the `ruleUid` prop?

File: public/app/features/alerting/unified/components/silences/SilencesDrawer.tsx [hunk 17]
```diff
@@ -0,0 +1,50 @@
...
+type Props = {
+  rule: CombinedRule;
+  onClose: () => void;
+};
+
+/**
+ * For a given rule, renders a drawer containing silences editor and Alertmanager selection
+ */
+const SilencesDrawer = ({ rule, onClose }: Props) => {
+  const ruleUid = isGrafanaRulerRule(rule.rulerRule) ? rule.rulerRule?.grafana_alert.uid : '';
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/silences/SilencesDrawer.tsx:21]: What if instead of having `rule: CombinedRule` in props we would have `rule: RulerGrafanaRuleDTO`?
Is there a reason why we would like to show the drawer for non-Grafana rules? I feel it could be misleading because for Mimir/Loki rules the same UI (drawer) would result in a different behavior (creating a global silence instead of rule-level one)

File: public/app/features/alerting/unified/components/silences/SilencesDrawer.tsx [hunk 18]
```diff
@@ -0,0 +1,50 @@
...
+
+type Props = {
+  rule: CombinedRule;
+  onClose: () => void;
+};
+
+/**
+ * For a given rule, renders a drawer containing silences editor and Alertmanager selection
+ */
+const SilencesDrawer = ({ rule, onClose }: Props) => {
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/silences/SilencesDrawer.tsx:20]: How about `SilenceRuleDrawer` to emphasise the component creates rule-bounded silences?

File: public/app/features/alerting/unified/components/silences/SilencesEditor.tsx [hunk 19]
```diff
@@ -22,145 +21,140 @@ import {
...
 }
 
-const defaultsFromQuery = (searchParams: URLSearchParams): Partial<SilenceFormFields> => {
-  const defaults: Partial<SilenceFormFields> = {};
+/**
+ * Silences editor for editing an existing silence.
+ *
+ * Fetches silence details from API, based on `silenceId`
+ */
+export const ConnectedSilencesEditor = ({ silenceId, alertManagerSourceName }: ConnectedSilenceEditorProps) => {
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/silences/SilencesEditor.tsx:53]: How about renaming to `ExistingSilenceEditor`?
`Connected` remind me redux connected components which is not true in this case 😄

File: public/app/features/alerting/unified/components/silences/utils.ts
Comment (konrad147) [inline public/app/features/alerting/unified/components/silences/utils.ts:1]: 👍

File: public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx (hunk 14 above)
Comment (tomratcliffe) [reply public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx:52]: Ah yes - because I added `ruleUid` to the `hasValidMatchers` definition further up. That one _is_ needed, because the form defaults to a rule UID but no additional matchers

File: public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx (hunk 16 above)
Comment (tomratcliffe) [reply public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx:68]: To me that reads as "instances across one or many alert rules" - or is that not accurate in all scenarios?

File: public/app/features/alerting/unified/components/silences/SilencesDrawer.tsx (hunk 17 above)
Comment (tomratcliffe) [reply public/app/features/alerting/unified/components/silences/SilencesDrawer.tsx:21]: Yes definitely - I much prefer that. It makes it clearer that we only expect this drawer to be shown for GMA (for now, at least)

File: public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx (hunk 15 above)
Comment (tomratcliffe) [reply public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx:36]: We need the deep compare as we're checking the values - if we don't do that, we end up thinking that they change all the time and we call the API too frequently. I couldn't get it working without this approach, but happy if you're able to get it working

File: public/app/features/alerting/unified/components/AlertManagerPicker.tsx [hunk 20]
```diff
@@ -9,25 +9,34 @@ import { AlertManagerDataSource, GRAFANA_RULES_SOURCE_NAME } from '../utils/data
 
 interface Props {
   disabled?: boolean;
+  /**
+   * If true, only show alertmanagers that are receiving alerts from Grafana
+   */
+  showOnlyReceving?: boolean;
```
[the remark this answers is not in the document]
Comment (tomratcliffe) [reply public/app/features/alerting/unified/components/AlertManagerPicker.tsx]: I went for `showOnlyReceivingGrafanaAlerts`, as it more closely matches the property `isReceivingGrafanaAlerts`

File: public/app/features/alerting/unified/components/rules/RuleActionsButtons.tsx (hunk 12 above)
Comment (tomratcliffe) [reply public/app/features/alerting/unified/components/rules/RuleActionsButtons.tsx:140]: (As per Slack, will address this in the RBAC portion)

File: public/app/features/alerting/unified/api/alertSilencesApi.ts (hunk 4 above)
Comment (tomratcliffe) [reply public/app/features/alerting/unified/api/alertSilencesApi.ts:59]: As per Slack - are you ok if we don't track this? As this is just the same as the error at the API level, rather than a UI problem/bug that we've encountered

File: public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx (hunk 13 above)
[the remark this answers is not in the document]
Comment (tomratcliffe) [reply public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx:28]: Added a comment to explain this method, and then why we're using it below

File: public/app/features/alerting/unified/api/alertRuleApi.ts (hunk 3 above)
Comment (konrad147) [reply public/app/features/alerting/unified/api/alertRuleApi.ts:211]: Should we remove the `ruler` parameter? The endpoint doesn't exists for any other than Grafana ruler

File: public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx (hunk 16 above)
Comment (konrad147) [reply public/app/features/alerting/unified/components/silences/SilencedInstancesPreview.tsx:74]: Then it's okay :)

**Review by konrad147 — APPROVED** [review]
LGTM!

**Review by gillesdemey — APPROVED** [review]
LGTM :shipit:
