### PR TITLE
Explore: Fix Browser title not updated on Navigation to Explore

### LINKED ISSUE #32898: Explore: browser title not updated on navigation to Explore
**How to reproduce it (as minimally and precisely as possible)**: Navigate to any other Grafana section (configuration, dashboards...) then click onto Explore

Screenshot 2021-04-12 at 16 26 05

**What you expected to happen**: the title to update

**Anything else we need to know?**: pretty minor issue, just could be made a bit nicer - I often have a variety of Grafana tabs open. I usually open an Explore tab for ad-hoc stuff and I may then navigate to another tab (email, Jira, whatever) to write up something based on the query I ran, then when navigating back to the Explore tab I find myself having to click though the Grafana tabs to find which one is actually the explore. Additionally, sometimes I'll navigate to an Explore tab based on the title (which is the name of a dashboard after navigating from Dashboard page) rather than the actual tab where I have the dashboard open

**Environment**:
- Grafana version: 7.5.2 // ca413c612f
- User OS & Browser: MacOS, Chrome

### PR DESCRIPTION
**Pull request by axelavargas**
**What this PR does / why we need it**:
When navigating to Explore page the document.title was not being updated, this was caused because Explore page is not using `Page` component that takes care of this functionality.

##Notes about the Approach
I decided to add the functionality on Explore page by duplicating the same logic we applied on `Page` component. That component is being used on other pages (Configuration, Alerting, etc...) but for the explore page will cause some unwanted styling issues and refactoring.

ExploreDocumentTitle

**Which issue(s) this PR fixes**:

Fixes #32898

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/explore/Wrapper.tsx [hunk 1]
```diff
@@ -6,13 +6,32 @@ import { lastSavedUrl, resetExploreAction, richHistoryUpdatedAction } from './st
...
 import { GrafanaRouteComponentProps } from 'app/core/navigation/types';
+import { NavModel } from '@grafana/data';
+import { Branding } from '../../core/components/Branding/Branding';
 
-interface WrapperProps extends GrafanaRouteComponentProps<{}, ExploreQueryParams> {
+// Libraries
+import { getNavModel, getTitleFromNavModel } from '../../core/selectors/navModel';
+
+// Types
+import { StoreState } from 'app/types';
```
Comment (hugohaggmark) [inline public/app/features/explore/Wrapper.tsx:16]: Please don't add import comments, that's something we're trying to remove. Thank you.

File: public/app/features/explore/Wrapper.tsx [hunk 2]
```diff
@@ -46,9 +66,15 @@ export class Wrapper extends Component<WrapperProps> {
...
+  };
+}
+
 const mapDispatchToProps = {
   resetExploreAction,
   richHistoryUpdatedAction,
 };
 
-export default connect(null, mapDispatchToProps)(Wrapper);
+export default connect(mapStateToProps, mapDispatchToProps)(Wrapper);
```
Comment (hugohaggmark) [inline public/app/features/explore/Wrapper.tsx:80]: This is an old way of setting up Redux connections refer to [this for the preferred way](https://github.com/grafana/grafana/blob/main/contribute/style-guides/redux.md#typing-of-connected-props).

**Review by hugohaggmark — COMMENTED** [review]
Code looks great, but I'm not sure about the title part. I think `Explore - Grafana` should be enough. `Explore: Explore - Grafana` looks weird to me.

File: public/app/features/explore/Wrapper.tsx (hunk 2 above)
Comment (axelavargas) [reply public/app/features/explore/Wrapper.tsx:80]: Thank you @hugohaggmark 🙌🏾  I will take a look :)

File: public/app/features/explore/Wrapper.tsx (hunk 1 above)
Comment (axelavargas) [reply public/app/features/explore/Wrapper.tsx]: Fixed :) https://github.com/grafana/grafana/pull/34651/commits/0e6990946b6134881f68061c97c19d295ff8976d#diff-06aad0593d46c656f9c92b1a6e517f30e9758c1f1eff827194d81389ee5c74f6R12

File: public/app/features/explore/Wrapper.tsx (hunk 2 above)
Comment (axelavargas) [reply public/app/features/explore/Wrapper.tsx]: I did the changes here as well https://github.com/grafana/grafana/pull/34651/commits/0e6990946b6134881f68061c97c19d295ff8976d#diff-06aad0593d46c656f9c92b1a6e517f30e9758c1f1eff827194d81389ee5c74f6R15

**Comment by axelavargas** [comment]
> Code looks great, but I'm not sure about the title part. I think `Explore - Grafana` should be enough. `Explore: Explore - Grafana` looks weird to me.

Thanks, @hugohaggmark for the review, indeed it looks weird, I did the changes here https://github.com/grafana/grafana/pull/34651/commits/0e6990946b6134881f68061c97c19d295ff8976d#diff-06aad0593d46c656f9c92b1a6e517f30e9758c1f1eff827194d81389ee5c74f6R35, I had to use directly the value from `${navModel.main.text}`, my old approach was using `getTitleFromNavModel(navModel);` but unfortunately this doesn't work in `Explore` page because the `main.text` and the `node.text` are the same text, and this is something generated in the backend.

**Comment by hugohaggmark** [comment]
> > Code looks great, but I'm not sure about the title part. I think `Explore - Grafana` should be enough. `Explore: Explore - Grafana` looks weird to me.
> 
> Thanks, @hugohaggmark for the review, indeed it looks weird, I did the changes here [0e69909#diff-06aad0593d46c656f9c92b1a6e517f30e9758c1f1eff827194d81389ee5c74f6R35](https://github.com/grafana/grafana/commit/0e6990946b6134881f68061c97c19d295ff8976d#diff-06aad0593d46c656f9c92b1a6e517f30e9758c1f1eff827194d81389ee5c74f6R35), I had to use directly the value from `${navModel.main.text}`, my old approach was using `getTitleFromNavModel(navModel);` but unfortunately this doesn't work in `Explore` page because the `main.text` and the `node.text` are the same text, and this is something generated in the backend.
> 
> _ps. I updated the gif in this PR with the new title_

Outstanding, will do another pass now.

File: public/app/features/explore/Wrapper.tsx [hunk 3]
```diff
@@ -1,18 +1,43 @@
-import React, { Component } from 'react';
-import { connect } from 'react-redux';
+import React, { PureComponent } from 'react';
```
Comment (hugohaggmark) [inline public/app/features/explore/Wrapper.tsx:1]: The change from Component to PureComponent should be fine AFAIK but maybe @ivanahuckova or @aocenas can confirm this too?

**Review by hugohaggmark — APPROVED** [review]
Looks outstanding! 🎉  

The change from Component to PureComponent should be fine AFAIK but there might be some edge case that I'm unaware of.

File: public/app/features/explore/Wrapper.tsx (hunk 3 above)
Comment (ivanahuckova) [reply public/app/features/explore/Wrapper.tsx:1]: As far as I know, the change should be okay. 🙂

Comment (aocenas) [reply public/app/features/explore/Wrapper.tsx:1]: I don't think it should break anything but I have a feeling:
```
navModel: getNavModel(state.navIndex, 'explore'),
```
will break any benefit as it seems to create a new object every time.

Comment (axelavargas) [reply public/app/features/explore/Wrapper.tsx:1]: great 🙌🏾, thank you @ivanahuckova for taking a look, I will proceed to merge :)

**Review by ivanahuckova — APPROVED** [review]
Thank you for working on this @axelavargas! 🧡 It has been in the backlog for quite some time and I am very happy that Explore has finally title.✨ LGTM!

File: public/app/features/explore/Wrapper.tsx (hunk 3 above)
Comment (axelavargas) [reply public/app/features/explore/Wrapper.tsx:1]: > I don't think it should break anything but I have a feeling:
> 
> ```
> navModel: getNavModel(state.navIndex, 'explore'),
> ```
> 
> will break any benefit as it seems to create a new object every time.

Hey, @aocenas thanks for checking out this PR 😄 , I was looking into `getNavModel` function, even though it generates a new object every time, the values are always the same if the parameters don't change, and because PureComponent only does a shallow comparison on the `ComponentShouldUpdate` I think will keep the benefits. I also verified the children's `Wrapper` component to confirm they are also PureComponents only to make sure are not breaking anything.

let me know if I am mistaken(I still lacking context in the project 😅 ) , I will merge the PR but ofc, if we find later on this, don't add any benefits we can put it back as before :)
