### PR TITLE
Explore: Support display of multiple tables

### LINKED ISSUE #70813: Explore: Cannot render multiple tables
### 
# What went wrong?

**What happened**:

  - When returning multiple data frames (from multiple queries) with a `preferredVisualizationType` of `table`, only one table gets rendered in explore. 

Screenshot 2023-06-28 at 10 39 32

**What did you expect to happen**:

  - Render a table for each query that returns table data frames.

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and go to explore 

**Step 2**:

- Select the test data source

**Step 3**:

- Select CSV file and choose a file for the first query

**Step 4**:

- Add a query and select table static as the scenario

**Step 5**:

- Run the query and see that only one table is being visualized

### 
# What Grafana version are you using?

Grafana v10.1.0-pre (c9c357f)

### PR DESCRIPTION
**Pull request by gelicia**
**What is this feature?**

A future new feature in Explore needs to display multiple tables at once. This was not possible given limitations in implementation.

**Why do we need this feature?**

To allow for features to display multiple tables in Explore at once.

**Who is this feature for?**

Developers who would like to display multiple tables in Explore at once and users who would like to see multiple tables in Explore at once.

**Which issue(s) does this PR fix?**:

Fixes [#70813](https://github.com/grafana/grafana/issues/70813)

**Special notes for your reviewer:**
Replication steps
1. Go to Explore. Select the test datasource
2. Choose the CSV File scenario and pick any file
3. Click Add query 
4. Choose the CSV File scenario and pick another file

Both tables will render.

**An important note regarding subtables**
In the Table implementation, you can supply `data` which is the content of the table, and `subData` which is a table that will display under a dropdown for individual table rows. The Table component only needs to know which `subData` frames go with what `data` rows, so there is a property, `meta.custom.parentRowIndex`, that would store this. 

Prior to this PR, query result data to `TableContainer`, Explore's wrapper of the Table component, only needed to supply that data as well, because, you guessed it, you could not see multiple tables in Explore at once. With the removal of that limitation, we need another property to match up not just the parent rows, but the parent table as well. I introduced the `meta.custom.tableKey` property for this. 

Looking at usages for this, I am fairly sure Tempo is the only one taking advantage of this feature as of now. Other usages include
- The table component itself, which is not relevant
- The `RawPrometheusContainer` which does not use `TableContainer`
- The `TablePanel` which only shows one Table at a time and is not relevant

I believe changing the Tempo code is all we need to do for this, but let me know if I'm missing something.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by gelicia** [comment]
@joey-grafana - I tried getting this to work with 2 queries from Tempo (I still have the feature flag turned on) and it would only display one of them - but it looks like the data is the same no matter what I select. I'm guessing this is a result of the feature being a WIP. Let me know if you think it's something up with the table container.

File: public/app/features/explore/Table/TableContainer.tsx [hunk 1]
```diff
@@ -85,33 +82,58 @@ export class TableContainer extends PureComponent<Props> {
...
+    if (mainFrames?.length === 1) {
+      tableData.push({
+        main: mainFrames[0],
+        sub: dataFrames?.filter((df) => df.meta?.custom?.parentRowIndex !== undefined),
+      });
+    } else if (mainFrames.length > 1) {
+      mainFrames?.forEach((frame) => {
+        let subFrames: DataFrame[] = [];
+        if (frame.meta?.custom?.tableKey !== undefined) {
+          subFrames = dataFrames?.filter((df) => df.meta?.custom?.tableKey === frame.meta?.custom?.tableKey) || [];
```
Comment (Elfo404) [inline public/app/features/explore/Table/TableContainer.tsx:104]: can't we just use the refId to match mainFrames with subFrames?

**Comment by ifrost** [comment]
Could we reuse `TablePanel` instead? It would give the dropdown selector for the frame and will give more consistent behavior between Explore / Dashboards.

**Comment by joey-grafana** [comment]
> @joey-grafana - I tried getting this to work with 2 queries from Tempo (I still have the feature flag turned on) and it would only display one of them - but it looks like the data is the same no matter what I select. I'm guessing this is a result of the feature being a WIP. Let me know if you think it's something up with the table container.

I checked out this branch and applied the changes we previously discussed to this branch. I can see in [Explore.tsx](https://github.com/grafana/grafana/blob/main/public/app/features/explore/Explore.tsx#L444) that the tableFrames from the query response does not always contain the correct frames. The observable is returning the responses from the two separate table queries at different times and they are being rendered in explore separately. I do not see any `queryResponse.tableFrames` that contains the results from both queries - so we don't render two tables as we don't have the frames from two tables. Whichever response is received last in Explore is the response that is used to render the table. Not sure why this is happening.

I pushed my [changes to a new branch](https://github.com/grafana/grafana/commit/0a5606e6e2f21d7ae33ff6d93cbe03d8ae3ed8ed) that tracks this one.


https://github.com/grafana/grafana/assets/90795735/9326a320-5336-4761-acaa-105b1f6287fc

**Comment by Elfo404** [comment]
FWIW Explore merges table results when possible (`decorateWithTableResult` in `public/app/features/explore/utils/decorators.ts`) by using the merge transformation when receiving results:

https://github.com/grafana/grafana/assets/1170767/3d92beee-459d-4371-ac06-db28e5707373

at that stage, from `Explore.tsx` POV there's only one table. If results cannot be merged, then this PR behaves as expected and creates 2 different tables (or, in dashboard, would make the dropdown at the bottom of the table appear).

that behavior i think makes sense most of the times when querying tabular data, so that users are only presented with a single table. (ie. displaying multiple timeseries data ,or as per the example) but may not for other cases, such this one. maybe the dataframe itself should be able to control the dafault behavior via a visualization option? (i.e. by setting `dataframe.custom.explore.merge = false` or something better)

**Comment by ifrost** [comment]
> I believe changing the Tempo code is all we need to do for this, but let me know if I'm missing something.

> Regarding the sub-tables functionality, as far as I know only the Tempo datasource uses it and the feature was originally added to the Table component because of Tempo. 

> The Tempo data source will be moving away soon from using the Table component to show nested data in favour of a dedicated traces list component, so there will no longer be any users of the sub-tables feature

I think putting Tempo-only features in Explore does not work well in the long-term. It adds complexity to Explore with features serving only one data source, and at the same time, for you, it takes more time to build features that Tempo users need. Maybe you should consider writing a custom Tempo App Plugin. With https://github.com/grafana/grafana/pull/65524 it will be easier to move from Explore to an App Plugin. I can imagine a user starting in Explore for basic investigation and switching to a dedicated app for a more rich experience. This way you will have more freedom in implementing new features, and Explore will be easier to maintain and scale with fewer single-use features.

One more note regarding multiple tables specifically. I don't know the exact requirements for Tempo but bear in mind that it may not be feasible to stretch Explore to every use case. What if you need to render tables in a specific order, or with custom titles, custom size, or maybe collapse them in the future? We would like to avoid putting features that serve only one data source to cover one specific use case.

The other solution could be to have a more rich visualization plugin, like Logs Panel / Container. Logs Container contains multiple visualizations put in a single view:  Logs panel +  Logs Volume + Logs Sample.

**Comment by gelicia** [comment]
> Could we reuse `TablePanel` instead? It would give the dropdown selector for the frame and will give more consistent behavior between Explore / Dashboards.

I do not want to refactor Explore to go from TableContainer to TablePanel at this time

**Comment by gelicia** [comment]
Okay, for one, I changed it up so we use refID and not the request ID. However, with Tempo's use case, the refID is still the same since both subqueries come from one query, so we have to append on to the refID to keep the tables unique. 

I pushed the core explore change to this branch but the other changes to tempo only were kept on that branch since there's a lot going on with that work. The final result is the following.

https://github.com/grafana/grafana/commit/79283a603242b1e39f3079d9eb6ab727ed729d11

screencapture-localhost-3000-explore-2023-07-05-13_20_22

**Comment by gelicia** [comment]
Add to dashboard works well. Query history has two queries per run, neither work. Hiding the query doesn't work, but the other query interactions work. The inspector functionality doesn't seem to work well, but I would need to double check with someone with what we want our expectations are there.

File: public/app/features/explore/Table/TableContainer.tsx [hunk 2]
```diff
@@ -85,33 +83,45 @@ export class TableContainer extends PureComponent<Props> {
       }
     }
 
-    const mainFrame = this.getMainFrame(dataFrames);
-    const subFrames = dataFrames?.filter((df) => df.meta?.custom?.parentRowIndex !== undefined);
+    const tableData: Array<{ main: DataFrame; sub?: DataFrame[] }> = [];
+    const mainFrames = this.getMainFrames(dataFrames).filter(
+      (frame: DataFrame | undefined): frame is DataFrame => !!frame && frame.length !== 0
```
Comment (gelicia) [inline public/app/features/explore/Table/TableContainer.tsx:88]: checking for main frame length along with it existing is to be consistent with prior logic for when to display the '0 series returned' text

File: public/app/features/explore/Table/TableContainer.tsx [hunk 3]
```diff
@@ -85,33 +83,45 @@ export class TableContainer extends PureComponent<Props> {
...
+    );
+
+    mainFrames?.forEach((frame) => {
+      const subFrames =
+        dataFrames?.filter((df) => frame.refId === df.refId && df.meta?.custom?.parentRowIndex !== undefined) ||
+        undefined;
+      tableData.push({ main: frame, sub: subFrames });
+    });
+
+    const isNoData = tableData.length === 0;
```
Comment (gelicia) [inline public/app/features/explore/Table/TableContainer.tsx:98]: This does mean we will not show individual empty tables if queries are empty, only if all queries return 0 results. Not sure if that's correct or not.

Comment (joey-grafana) [reply public/app/features/explore/Table/TableContainer.tsx:98]: Hmm yeah I don't really mind anyway, either way it makes sense. I'd have a slight preference for combining any empty results into some kind of a warning for the user. Not in this PR though, but more of a longer term goal.

**Comment by joey-grafana** [comment]
This is looking good so far but if you need anything else from me to get this merged, please lmk.

File: public/app/features/explore/Table/TableContainer.tsx [hunk 4]
```diff
@@ -85,33 +83,45 @@ export class TableContainer extends PureComponent<Props> {
...
+    const mainFrames = this.getMainFrames(dataFrames).filter(
+      (frame: DataFrame | undefined): frame is DataFrame => !!frame && frame.length !== 0
+    );
+
+    mainFrames?.forEach((frame) => {
+      const subFrames =
+        dataFrames?.filter((df) => frame.refId === df.refId && df.meta?.custom?.parentRowIndex !== undefined) ||
+        undefined;
+      tableData.push({ main: frame, sub: subFrames });
+    });
```
Comment (Elfo404) [inline public/app/features/explore/Table/TableContainer.tsx:96]: tbh i find this logic is becoming a bit confusing and starting to become a bit too spread over this component.
wdyt about this:

```ts
    const tableData = dataFrames?.filter(isMainFrame).map((mainFrame) => ({
      main: mainFrame,
      sub: dataFrames?.filter(isChildOf(mainFrame)),
    }));
```

where `isMainFrame` and `isChildOf` are defined as (outside of the component):

```ts
function isMainFrame(frame: DataFrame) {
  return frame.meta?.custom?.parentRowIndex === undefined;
}

function isChildOf(parentFrame: DataFrame) {
  return (maybeChild: DataFrame) => {
    return parentFrame.refId === maybeChild.refId && maybeChild.meta?.custom?.parentRowIndex !== undefined;
  };
}
```

**Review by Elfo404 — COMMENTED** [review]
Overall looks good and seem to work great, the only real blocker imho  is the MetaInforText not being rendered inside PanelChrome which looks weird

File: public/app/features/explore/Table/TableContainer.tsx (hunk 3 above)
Comment (ifrost) [reply public/app/features/explore/Table/TableContainer.tsx:98]: I think it should be good for now 👍  

It seems to be a recurring theme of how we handle errors and empty results in Explore, we will need to look at this more holistically.

File: public/app/features/explore/Table/TableContainer.tsx (hunk 4 above)
Comment (ifrost) [reply public/app/features/explore/Table/TableContainer.tsx:96]: The whole splitting logic could be encapsulated in a single function. Maybe not in this PR, but do you think it would make sense to make it part of the decorator logic?

Comment (Elfo404) [reply public/app/features/explore/Table/TableContainer.tsx:96]: i don't see why not, it would actually make more sense there than here, especially given the recent progression over custom viz which may benefit from it as well

File: public/app/features/explore/Table/TableContainer.tsx [hunk 5]
```diff
@@ -34,25 +34,23 @@ const connector = connect(mapStateToProps, {});
 type Props = TableContainerProps & ConnectedProps<typeof connector>;
 
 export class TableContainer extends PureComponent<Props> {
-  getMainFrame(frames: DataFrame[] | null) {
-    return frames?.find((df) => df.meta?.custom?.parentRowIndex === undefined) || frames?.[0];
+  getMainFrames(frames: DataFrame[] | null) {
+    return (
+      frames?.filter((df) => df.meta === undefined || df.meta?.custom?.parentRowIndex === undefined) || [frames?.[0]]
+    );
```
[the remark this answers is not in the document]
Comment (gelicia) [reply public/app/features/explore/Table/TableContainer.tsx]: nope! thanks!

File: public/app/features/explore/Table/TableContainer.tsx [hunk 6]
```diff
@@ -85,33 +83,45 @@ export class TableContainer extends PureComponent<Props> {
...
+                  data={data.main}
+                  subData={data.sub}
+                  width={innerWidth}
+                  height={innerHeight}
+                  onCellFilterAdded={onCellFilterAdded}
+                />
+              )}
+            </PanelChrome>
+          ))}
+      </>
```
[the remark this answers is not in the document]
Comment (gelicia) [reply public/app/features/explore/Table/TableContainer.tsx]: Looks good!

**Review by ifrost — APPROVED** [review]

**Review by Elfo404 — APPROVED** [review]
