### PR TITLE
Fix: make sure that we the gauge panel can handle scenario with no data.

### LINKED ISSUE #24897: "Cannot read property 'toFixed' of undefined" on Gauge panel with no data
**What happened**:
The error `Cannot read property 'toFixed' of undefined` appears in the top-left corner of a Gauge panel when the panel's queries return no data.

**What you expected to happen**:
The Gauge renders with the text "No data".

**How to reproduce it (as minimally and precisely as possible)**:
Do one of the following:
- Visit https://play.grafana.org/d/000000012/grafana-play-home?editPanel=7&orgId=1 and change Panel->Visualization to "Gauge", "Bar gauge", or "Table".
- Add a panel to a dashboard. Click the "Add a new panel" button. Leaving everything else at defaults, set Panel->Visualization to "Gauge", "Bar gauge", or "Table". 

Observe a red "!" appear in the top left corner of where the panel is supposed to be, with a hover tooltip of your browser's flavour of `Cannot read property 'toFixed' of undefined`.

**Anything else we need to know?**:
I have also replicated the error on play.grafana.org and on a Docker instance of Grafana 7.0.0, on both Chrome and Safari.

It appears to be necessary to set the following options on the panel's "Field" tab to trigger the bug:
- Min, Max: unset (auto)
- Thresholds mode: Absolute

The choice of data source seems to be irrelevant so long as there are either no queries defined or the queries return no data for the time period.

**Environment**:
- Grafana version: 7.0.0 (Docker image `sha256:4c8a5fede0b0982d4588a77a80aeeb5bc572e333a557615f0753aaed7e6fb901`)
- Data source type & version: N/A
- OS Grafana is installed on: Linux
- User OS & Browser: macOS 10.15.4, Chrome 81.0.4044.138 and Safari 13.1 (15609.1.20.111.8)
- Grafana plugins: N/A
- Others:

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
If you try to feed the gauge panel with a query that returns no data it will throw an error. Added some guarding and will return default values in that scenario.

**Which issue(s) this PR fixes**:
Fixes #24897

### CODE REVIEW

File: packages/grafana-ui/src/components/Gauge/Gauge.tsx [hunk 1]
```diff
@@ -57,8 +58,13 @@ export class Gauge extends PureComponent<Props> {
     const thresholds = field.thresholds ?? Gauge.defaultProps.field?.thresholds!;
     const isPercent = thresholds.mode === ThresholdsMode.Percentage;
     const steps = thresholds.steps;
-    let min = field.min!;
-    let max = field.max!;
+    let min = field.min;
+    let max = field.max;
+
+    if (!isNumber(min) || !isNumber(max)) {
```
Comment (mckn) [inline packages/grafana-ui/src/components/Gauge/Gauge.tsx:64]: @torkelo do you know if we can end up in a scenario where we have a value for `min` but not `max` and the other way around? Thinking if I should change this one to `&&` and use a default value for `min` or `max` in that scenario.

Comment (torkelo) [reply packages/grafana-ui/src/components/Gauge/Gauge.tsx:64]: yes, I think technically it is possible. wonder if apply field overrides always should set some numeric defaults for min & max so that logic like this isn't needed in every visualization. 

thoughts @ryantxu ?

Comment (dprokop) [reply packages/grafana-ui/src/components/Gauge/Gauge.tsx:64]: @torkelo maybe the autoMinMax should be true by default in the `ApplyFieldOverrideOptions`? then min/max would be guaranteed.

File: packages/grafana-ui/src/components/Gauge/Gauge.tsx [hunk 2]
```diff
@@ -130,9 +137,12 @@ export class Gauge extends PureComponent<Props> {
     }
 
     const decimals = field.decimals === undefined ? 2 : field.decimals!;
+
     if (showThresholdMarkers) {
-      min = +min.toFixed(decimals);
-      max = +max.toFixed(decimals);
+      if (isNumber(min) && isNumber(max)) {
+        min = +min.toFixed(decimals);
+        max = +max.toFixed(decimals);
```
Comment (dprokop) [inline packages/grafana-ui/src/components/Gauge/Gauge.tsx:144]: Never seen this syntax before. Is it ensuring the value to be positive?

File: packages/grafana-ui/src/components/Gauge/Gauge.tsx (hunk 1 above)
Comment (torkelo) [reply packages/grafana-ui/src/components/Gauge/Gauge.tsx:64]: yes, it is always true now in PanelQueryRunner

File: packages/grafana-ui/src/components/Gauge/Gauge.tsx (hunk 2 above)
Comment (mckn) [reply packages/grafana-ui/src/components/Gauge/Gauge.tsx:144]: It ensures that the value is a numeric value to make sure that the `.toFixed` is available (I guess).

File: packages/grafana-ui/src/components/Gauge/Gauge.tsx (hunk 1 above)
Comment (mckn) [reply packages/grafana-ui/src/components/Gauge/Gauge.tsx:64]: OK ok, so what do you think I should default to in case one of them is a numeric value but not the other?

Comment (torkelo) [reply packages/grafana-ui/src/components/Gauge/Gauge.tsx:64]: Think the fix should not be here but in maybe here? https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/field/fieldDisplay.ts#L260 

The bug is that min & max are not numeric when there is no data right? think that the no data field config options are defined there

Comment (mckn) [reply packages/grafana-ui/src/components/Gauge/Gauge.tsx:64]: ah, I will have a look at it. Thanks for the feedback!

**Review by dprokop — APPROVED** [review]

**Review by torkelo — APPROVED** [review]
Looks good!

**Review by dprokop — APPROVED** [review]
LGTM, last changes are legit :)
