### PR TITLE
FieldOverrides: Added support to change display name in an override field and have it be matched by a later rule

### LINKED ISSUE #31364: Overrides: Filtering / Selecting on timeseries is not possible when an override with displayName exists
**What happened**:
Given is an influx-query which is displayed with the new timeseriespanel. If added override to a field on "Display Name" (for better readability) it is not possible to select the field/series as in graphpanel. (See screenshot)

**What you expected to happen**:
I'd like to view only the graph for the selected field/series like it was/is when using the old graphpanel

**How to reproduce it (as minimally and precisely as possible)**:
See screenshot. Simply create the same graph (with timeseries) and then try to select the series "AAA" at the panel. Everything is deselected then.
Bildschirmfoto 2021-02-20 um 07 55 31

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.2
- Data source type & version: influxdb 1.8.4
- OS Grafana is installed on: debian buster
- User OS & Browser: macos/chrome
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #31364

So this is tricky stuff. But the basic premise is not that complicated. 

* [x] Always add the hide in rule last 
* [x] To support updating display name in override and have it impact later a custom override processor that clears displayName from state was added. 

But the above did not help, as in field override we mix a lot of calls with new and old field and frame so field equality checks where not working in getFieldDisplayName as the frame that was passed had the old copy of the field, and the field being passed was the new field being processed for overrides. So to make equality checks consistent I had to move the field copy out of the field override inner loop and first copy the frame & fields and then process the overrides. This way a call to `getFieldDisplayName(field, frame)`, will always find that field in the frame (using reference identity check).

### CODE REVIEW

File: packages/grafana-data/src/field/overrides/processors.ts [hunk 1]
```diff
@@ -24,6 +24,16 @@ export const numberOverrideProcessor = (
   return parseFloat(value);
 };
 
+export const displayNameOverrideProcessor = (
+  value: any,
+  context: FieldOverrideContext,
+  settings?: StringFieldConfigSettings
+) => {
+  // clear the cached display name
+  delete context.field?.state?.displayName;
```
Comment (ryantxu) [inline packages/grafana-data/src/field/overrides/processors.ts:33]: Ahhh -- the magic!

Comment (torkelo) [reply packages/grafana-data/src/field/overrides/processors.ts:33]: yea, well this was done outside in the field overrides code, but after all everything was processed. Now only done if the display name is changed

File: packages/grafana-data/src/field/fieldOverrides.ts [hunk 2]
```diff
@@ -97,33 +97,38 @@ export function applyFieldOverrides(options: ApplyFieldOverrideOptions): DataFra
...
-  return options.data.map((frame, index) => {
+  return options.data.map((originalFrame, index) => {
     // Need to define this new frame here as it's passed to the getLinkSupplier function inside the fields loop
-    const newFrame: DataFrame = { ...frame };
+    const newFrame: DataFrame = { ...originalFrame };
+    // Copy fields
+    newFrame.fields = newFrame.fields.map((field) => {
+      return {
+        ...field,
+        config: cloneDeep(field.config),
```
Comment (ryantxu) [inline packages/grafana-data/src/field/fieldOverrides.ts:107]: Assuming this runs on everything.... perhaps we should clone the whole DataFrame before PanelQueryRunner starts applying changes, and then everything in the pipeline can safely mutate.  With the current model, we have a few deep clones scattered about adding a bit of complexity.

cc @leeoniya

Comment (torkelo) [reply packages/grafana-data/src/field/fieldOverrides.ts:107]: yea this deepClone was new to me, was added recently. But we do not want to deep clone the values! so I think being more deliberate about what is shallow and what is deep like above I think is ok

Comment (leeoniya) [reply packages/grafana-data/src/field/fieldOverrides.ts:107]: if it's an array of plain values then a "deep" clone on it is a cheap `values.slice()` call that i assume has copy-on-write semantics in V8. the trick is not to iterate those arrays and do a `push` loop, which may need custom handling to avoid in cloneDeep(). i think cloning the rest of the structures will be much more expensive.

**Review by hugohaggmark — APPROVED** [review]
Amazing work! I took this for a test drive and it works as expected 💥

File: packages/grafana-data/src/field/fieldOverrides.ts (hunk 2 above)
Comment (torkelo) [reply packages/grafana-data/src/field/fieldOverrides.ts:107]: Been looking at this, I would like to cleanup the code in PanelQueryRunner.getData (that handles copy field config from last result, etc), there is a lot of copying the data frame there and then again in applyFieldOverrides. The only problem is applyFieldOverrides is also used elsewhere. So making applyFieldOverrides fully mutable could have other effects there.

**Comment by torkelo** [comment]
@ryantxu @leeoniya merging this but not backporting it to v8.0, feels too risky.
