### PR TITLE
LogsPanel: Fix scrollbar

### LINKED ISSUE #24569: Dashboards: cannot move scrollbar in logs panel using Chrome
**What happened**:

When running logs query in dashboards I can't move the scrollbar in the logs panel in Chromium-powered browsers. Works properly in Firefox.

**What you expected to happen**:

Logs panel working properly with an ability to move scrollbars.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open Grafana
2. Create new dashboard
3. Add new panel
4. Set the panel visualization to Logs
5. Use a logs datasource (Loki, Elasticsearch logs)
6. Write a query to display data with long log messages (for Loki under linux, usually `{job="varlogs"}` should do the job)
7. Try to move the scrollbar.

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
Fixes inactive scrollbar in Logs Panel. As explained in comments, we are passing logsPanel props (boolean) and add styling to container based on if we are in LogsPanel or in Explore.  In Explore, for scrolling we can't use CustomScrollbar as it causes the problem with logs context - it is not visible for top log rows. Therefore we use CustomScrollbar only in LogsPanel and for Explore, we use custom css styling.

Fixes #24569

### CODE REVIEW

**Comment by Estrax** [comment]
@ivanahuckova Can you check whether it works properly in dashboards, by clicking on the scrollbar and moving it (not via the mouse wheel/scroll event on the container itself)?

**Comment by ivanahuckova** [comment]
It works for me, doesn't it fix the problem for you?

**Comment by Estrax** [comment]
@ivanahuckova Nope, still seems not to be working properly on my end with webkit-powered browsers on both Windows and Linux.

**Comment by ivanahuckova** [comment]
Hmmm, @torkelo [mentioned that it worked for him](https://github.com/grafana/grafana/issues/24569#issuecomment-630265473). So I am not sure now, as I can't replicate it (as all scrollbars work for me). @Estrax is there a problem with all of the scrollbars in other parts of Grafana as well? Because after this update, we are just simply using CustomScrollbar component that is used at a lot of other places. 🤔

**Comment by Estrax** [comment]
Weird. Works now after you removed `autoHide`. All good.

**Comment by ivanahuckova** [comment]
Thanks for thorough testing Lukas! Super appreciated! 🙂

**Comment by aocenas** [comment]
Can't we just pass a prop from logsPanel that would disable the horizontal scroll? That way we can leave the horizontal scroll in explore so the wrapping works but disable it in logs panel as it uses the custom scrolling wrapper.

**Comment by ivanahuckova** [comment]
But still we would have problem in Explore with context when wrap line is disabled.

**Comment by aocenas** [comment]
> But still we would have problem in Explore with context when wrap line is disabled.

Well yes that will stay broken in the same way but at least we will fix the scroll in panel without breaking anything else right?

**Comment by ivanahuckova** [comment]
@Estrax could you just check if removing autoHide from https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/logs/LogsPanel.tsx#L28. on master doesn't fix the issue?

**Comment by ivanahuckova** [comment]
Followed @aocenas advice. This fixes the scrolling without any regression. I have also added comments that explains why we do the things the way we do.

File: packages/grafana-ui/src/components/Logs/LogRows.tsx [hunk 1]
```diff
@@ -98,7 +102,10 @@ class UnThemedLogRows extends PureComponent<Props, State> {
       ? dedupedRows.reduce((sum, row) => (row.duplicates ? sum + row.duplicates : sum), 0)
       : 0;
     const showDuplicates = dedupStrategy !== LogsDedupStrategy.none && dedupCount > 0;
-    const horizontalScrollWindow = wrapLogMessage ? '' : logsRowsHorizontalScroll;
+
+    // For horizontal scrolling we can't use CustomScrollbar as it causes the problem with logs context - it is not visible
+    // for top log rows. Therefore we use CustomScrollbar only in LogsPanel and for Explore, we use custom css styling.
+    const horizontalScrollWindow = wrapLogMessage && !logsPanel ? '' : logsRowsHorizontalScroll;
```
Comment (aocenas) [inline packages/grafana-ui/src/components/Logs/LogRows.tsx:108]: So what will happen if we are in logsPanel and somebody selects `wrapLogMessges=true`? Does this basically disable that option in Logs Panel?

Comment (ivanahuckova) [reply packages/grafana-ui/src/components/Logs/LogRows.tsx:108]: No, it still works, because we are using CustomScrollbar in LogsPanel that can handle horizontal and vertical scrolling.
Kapture 2020-05-19 at 17 27 25

Comment (ivanahuckova) [reply packages/grafana-ui/src/components/Logs/LogRows.tsx:108]: But this brought be to another question - should we do autoHide for CustomScrollbar in Logs Panel? Maybe without autoHide it is going to be more clear that you can scroll both. directions?

Comment (aocenas) [reply packages/grafana-ui/src/components/Logs/LogRows.tsx:108]: Cool in that case though I would rename the prop. `logsPanel` does not say what the prop means, it says that parent is logsPanel which is something the component should not care/know. Something like `disableHorizontalScroll` or something like that would make more sense.

> should we do autoHide for CustomScrollbar in Logs Panel

Looking at the usages it seems to be mixed. Personally hate autoHide for scrolling and is the first thing I disable in mac :D. So I would vote to remove it. is that white background of the scroll bar something you did extra? Cause there is no background on my machine.

Comment (ivanahuckova) [reply packages/grafana-ui/src/components/Logs/LogRows.tsx:108]: > cool in that case though I would rename the prop. 

Yeah, good point. 

> I would vote to remove it.  

I don't have strong preference. Maybe we can keep it the way it is and disable/leave it enabled when/if we have strategy for that. 

>is that white background of the scroll bar something you did extra?

No that is my Chrome's default scrollbar's background. It looks normal and nice but changes to that ugly one when I'm over it. It is the same on every website. 
Screenshot 2020-05-19 at 17 47 21
Screenshot 2020-05-19 at 17 47 21 (2)

image

**Review by Estrax — APPROVED** [review]
Seems to be working properly on Linux and Windows with webkit-powered browsers, though in comparison to Firefox for example, not only those scrollbars look completely different, but in Chrome they are also hard to click and move.

This is how it looks like in Firefox:
Screenshot from 2020-05-20 05-45-34

And this is how it looks in Chrome:
Screenshot from 2020-05-20 05-35-09

Also, not sure if we should do anything with those white boxes in the corner (`::-webkit-scrollbar-corner`).

**Comment by ivanahuckova** [comment]
Yeah, maybe there should be a general discussion about scrollbars. But it is really weird how drastically different they look. 
For example this is my Firefox:
image
And Chrome:
Screenshot 2020-05-20 at 10 46 08

They look absolutely the other way around than yours 🙈.

**Comment by aocenas** [comment]
So lets skip the scroll bar styling for now. I think we did not introduce any new styling here so if the scrollbars look differently on each browser I guess that is a problem across grafana. Especially as it seem we use 2 different ones depending on whether we use html overflow or the <CustomScrollbar> component. So I think this is fine to merge and we can create an issue (or look if there isn't already) for the scroll bar styling and whether it can be improved.

**Review by aocenas — APPROVED** [review]
