### PR TITLE
TooltipPlugin: Fix behavior of Shared Crosshair when Tooltip is set to All

### LINKED ISSUE #35552: Time series: Shared crosshair does not work when tooltip mode set to all
**What happened**:
Some time ago I have reported that shared crosshair does not work for time series graphs (#33093).
Shared tooltip for time series was added in 8.0.0, but it does not work properly.

When I switch tooltip mode to all in graph's settings,
image
And then select shared crosshair in dashboard's settings
image
It still shares the whole tooltip instead of just the crosshair (the mouse was over the top graph).
image

**What you expected to happen**:
The other graph should have displayed only the crosshair.

**Environment**:
- Grafana version: 8.0.1
- Data source type & version: Influxdb 2.0.7
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Opera Gx
- Grafana plugins: -
- Others: -

### PR DESCRIPTION
**Pull request by nikki-kiga**
**What this PR does / why we need it**:
Addresses the panel "All" behavior when Dashboard is set to Shared Crosshair instead of Shared Tooltip

**Which issue(s) this PR fixes**:
Fixes #35552

**Special notes for your reviewer**:
After PR:
Dashboard with Panel Tooltip set to "Shared crosshair" and Panel Tooltips set to "All"
https://user-images.githubusercontent.com/42276368/127526358-b3b682dc-d8a6-4aab-96e3-0a55d3a18f9f.mov

### CODE REVIEW

**Comment by oscarkilhed** [comment]
Looks good!

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx [hunk 1]
```diff
@@ -55,21 +59,33 @@ export const TooltipPlugin: React.FC<TooltipPluginProps> = ({
...
 
     return () => {
       setCoords(null);
       if (plotCtx && plotCtx.plot) {
         plotCtx.plot.over.removeEventListener('mouseleave', plotMouseLeave);
+        plotCtx.plot.over.removeEventListener('mouseenter', plotMouseEnter);
       }
     };
-  }, [plotCtx.plot?.root, setCoords]);
+  }, [plotCtx.plot?.root, setCoords, setIsActive]);
```
Comment (leeoniya) [inline packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx:88]: is it a typical pattern for this array to contain the setter functions rather than the actual states?

functionally it makes no difference, but `coords, isActive` feels a bit better to me.

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx [hunk 2]
```diff
@@ -205,6 +221,12 @@ export const TooltipPlugin: React.FC<TooltipPluginProps> = ({
   );
 };
 
+function handleMouseEvent(e: MouseEvent) {
+  if (e.target) {
+    (e.target as HTMLDivElement).classList.toggle('plot-active');
+  }
+}
+
```
Comment (leeoniya) [inline packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx:229]: it'd probably get rid of this and do something like this above (more explicit than toggle and doesnt need to get target from event, since we know it's bound to `.over` already):

```js
    const plotMouseLeave = (e: MouseEvent) => {
      setCoords(null);
      setIsActive(false);
      plotCtx.plot.over.classList.remove('plot-active');
    };
```

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx (hunk 1 above)
Comment (nikki-kiga) [reply packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx]: Good point - I just looked into this some more.

I don't think we want to change it to `coords, isActive` since each time those change, they would trigger the useEffect.

[After researching this](https://github.com/facebook/react/issues/19125), it looks like it is a good practice to include functions that could change in the dependency array, but setState doesn't need to be.

**Review by leeoniya — APPROVED** [review]

**Comment by benrubson** [comment]
Any reason not to backport this into 8.1.x ?
Many thanks 👍
