### PR TITLE
Combobox: Handle error if async fails

### LINKED ISSUE #95385: New Select: Handle async errors in a nice way
We need a way to handle errors that are non-stale. I am not quite sure how to approach this.

https://github.com/grafana/grafana/blob/69f888e296394bbbd4c363de05d120345b00719d/packages/grafana-ui/src/components/Combobox/Combobox.tsx#L185

### PR DESCRIPTION
**Pull request by JoaoSilvaGrafana**
**What is this feature?**

In an async combobox, there is a chance that the `loadOptions` function fails and if so we need to show an error.
Screenshot 2024-11-01 at 17 12 54

**Why do we need this feature?**

So users know an error has occurred.

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #95385

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/Combobox/Combobox.tsx [hunk 1]
```diff
@@ -341,6 +345,11 @@ export const Combobox = <T extends string | number>({
             })}
           </ul>
         )}
+        {asyncError && (
+          <Stack justifyContent="center" alignItems="center" height={8}>
+            <Text color="secondary">{t('combobox.async.error', 'An error occurred while loading options.')}</Text>
```
Comment (tskarhed) [inline packages/grafana-ui/src/components/Combobox/Combobox.tsx:350]: Could you maybe add a warning triangle icon here? Either next to the text or above.

**Review by tskarhed — APPROVED** [review]
This looks good! It would be nice with an added error icon, but I won't block the PR because of it.

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍
