### PR TITLE
Profile: Fixes profile preferences page being available when anonymous access was enabled

### LINKED ISSUE #31507: Anonymous access to profile page changes organization preferences
**What happened**:
Anonymous users can access `<root_url>/grafana/profile`, e.g. by calling the URL directly or shortcut keys `g` `p`. 

Changes done on this page then **affect the whole organization**, as if done by an admin on `<root_url>/grafana/org`. These settings don't seem to be critical, but it's annoying when curious users change them.

For reference, this screen is shown:
image

**What you expected to happen**:
Depends on whether it's possible to store these settings as cookie and thus apply them for the current browser (session) only.
If this is supported, the "Save" actions should update those instead of the org. preferences. That would be a feature and could be promoted by making the preferences page appear in the menu for anonymous users.

Otherwise, the profile/preferences page shouldn't be accessible at all for anonymous users, even when the URL is known. 

**How to reproduce it (as minimally and precisely as possible)**:
Configure [anonymous authentication](https://grafana.com/docs/grafana/latest/auth/grafana/#anonymous-authentication). Open `<root_url>/grafana/profile` in incognito mode, change the theme. Verify with another user (or a new incognito session) that the theme has changed.

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: n/a
- OS Grafana is installed on: Linux (SLES 15.1)
- User OS & Browser: Windows 10 / Chrome 88.0.4324.190
- Grafana plugins: n/a
- Others: n/a

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #31507

Explore different ways to fix, this one felt cleanest.

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]
Looks good AFAICT.

File: pkg/middleware/auth.go [hunk 1]
```diff
@@ -16,6 +16,7 @@ import (
 type AuthOptions struct {
 	ReqGrafanaAdmin bool
 	ReqSignedIn     bool
+	NoAnonynmous    bool
```
Comment (wbrowne) [inline pkg/middleware/auth.go:19]: Nit: For consistency and helps make it clearer. Or alternatively `ReqAnonymous` and then flip the logic.
```suggestion
	ReqNotAnonynmous    bool
```

Comment (torkelo) [reply pkg/middleware/auth.go:19]: ah, good suggestion!
