### PR TITLE
TimePicker: Improve screen reader support

### LINKED ISSUE #86649: Change time settings: No state property is defined for the 'Change time settings' button.
### What happened?

The narrator does not announce the 'collapsed/expanded' state for the 'Change time settings' button. 
The narrator announces it here as 'Change time settings, button' etc. 

https://github.com/grafana/grafana/assets/93735775/ec67c63b-2541-4ad1-b887-f3856808dc6a

-a69d-44f7-b82f-f66cc6ddba6a">

### What did you expect to happen?

The screen reader should announce the collapsed and expanded state for the button as there are controls defined inside it. It should announce as 'Change time settings, button, collapsed'.

### Did this work before?

No

### How do we reproduce it?

1. Open the URL [Grafana Play Home - Dashboards - Grafana](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1) in edge Dev browser.
2. ‘Grafana Play Home’ page will open. 
3. Navigate to ‘Time range’ button & expand it. 
4. Navigate to ‘Change time settings’ button via tab key and activate it using Enter key. 
5. Observe the issue. 

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: v11.1.0-69372 (51da96d94e)
OS: 23H2 OS build: 22631.3520
Browser: Edge version 124.0.2478.51 (Official build) (64-bit)

### Grafana platform?

None

### Datasource(s)?

_No response_

### LINKED ISSUE #86658: Time Range button: Incorrect role as 'radio button' is defined instead of tab items for 'Fiscal year' and 'Time zone' control time range pop-up.
### What happened?

Incorrect role as 'radio button' is defined instead of tab items for 'Fiscal year' control time range pop-up. 
The narrator announces it here as 'Time zone, radio button 1 of 2 selected' etc. 

https://github.com/grafana/grafana/assets/93735775/4ac176de-d6e7-4ab9-9f2d-737e0f8c2eab

### What did you expect to happen?

The correct role as tab items be defined for all these two controls Narrator should announce as 'Time zone, 1 of 2, selected' etc. 

### Did this work before?

No

### How do we reproduce it?

1. Open the URL [Grafana Play Home - Dashboards - Grafana](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1) in edge Dev browser.
2. ‘Grafana Play Home’ page will open. 
3. Navigate to ‘Time range’ button & activate it. 
4. Navigate to ‘Change time settings’ button & activate it. 
5. Navigate to the 'Fiscal year' and 'Time zone' controls & observe the screen reader narration. 

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: v11.1.0-69372 (51da96d94e)
OS: 24H2 (OS Build 26100.1) 
Browser: Edge version 125.0.2506.0 (Official build) dev (64-bit)

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by tskarhed**
**What is this feature?**

These could've been two separate PRs, but I got into the groove.

- Adds aria controls and expanded to time settings button
- Changes radio buttons to tabs
image

**Why do we need this feature?**

More accessibility, better screen reader support

**Who is this feature for?**

Screen reader users and everyone else

**Which issue(s) does this PR fix?**:

Fixes #86649
Fixes [#86658](https://github.com/grafana/grafana/issues/86658)

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerFooter.tsx [hunk 1]
```diff
@@ -78,62 +78,81 @@ export const TimePickerFooter = (props: Props) => {
...
+          aria-controls="time-settings-section"
+          icon={isEditing ? 'angle-up' : 'angle-down'}
         >
           <Trans i18nKey="time-picker.footer.change-settings-button">Change time settings</Trans>
         </Button>
       </section>
       {isEditing ? (
-        <div className={style.editContainer}>
+        <div className={style.editContainer} id="time-settings-section">
           <div>
```
Comment (ashharrison90) [inline packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerFooter.tsx:90]: think this `<div>` is redundant - can we remove it?

File: packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerFooter.tsx [hunk 2]
```diff
@@ -78,62 +78,81 @@ export const TimePickerFooter = (props: Props) => {
...
+          aria-expanded={isEditing}
+          aria-controls="time-settings-section"
+          icon={isEditing ? 'angle-up' : 'angle-down'}
         >
           <Trans i18nKey="time-picker.footer.change-settings-button">Change time settings</Trans>
         </Button>
       </section>
       {isEditing ? (
-        <div className={style.editContainer}>
+        <div className={style.editContainer} id="time-settings-section">
```
Comment (ashharrison90) [inline packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerFooter.tsx:89]: can we remove the top padding on `editContainer`? the tabs already have quite a bit of top padding

**Review by ashharrison90 — APPROVED** [review]
great job! 👏 

couple of nits

File: packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerFooter.tsx (hunk 1 above)
Comment (tskarhed) [reply packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerFooter.tsx:90]: It is used for the `aria-controls` id. I could put it directly on the tabs maybe? 🤔

File: packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerFooter.tsx [hunk 3]
```diff
@@ -78,62 +78,81 @@ export const TimePickerFooter = (props: Props) => {
           variant="secondary"
           onClick={onToggleChangeTimeSettings}
           size="sm"
+          aria-expanded={isEditing}
+          aria-controls="time-settings-section"
```
Comment (ashharrison90) [inline packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerFooter.tsx:82]: also just thought, couldn't we just use `useId` here? e.g.

```tsx
const timeSettingsId = useId();

// ...

<Button
  aria-controls={timeSettingsId}
>

// ...

<div className={style.editContainer} id={timeSettingsId}>
```

Comment (tskarhed) [reply packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerFooter.tsx:82]: I've run into som issues with useId, where pa11y fails because it doesn't think `:` should be in a valid id. I guess we could write a wrapper around it.

**Review by eledobleefe — APPROVED** [review]
Tested on local and looks good 👌

File: packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerFooter.tsx (hunk 3 above)
Comment (ashharrison90) [reply packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerFooter.tsx]: ah i see, basically hitting https://github.com/facebook/react/issues/26839

good to know 👍

**Review by ashharrison90 — APPROVED** [review]
looks great! 🥳
