### PR TITLE
Loki: Fix autocomplete when re-editing Loki label values

### LINKED ISSUE #31705: loki intellisense/autocomplete for explore doesn't work when re-editing values
**What happened**:
The intellisense works great when typing the value out for the first time:
image

But when you do a search and go back and edit it to select a different app the intellisense suggests labels instead of label values:
image

**What you expected to happen**:
Label values to be suggested

**How to reproduce it (as minimally and precisely as possible)**:
1. Type in `{app="your_app_name_here"}`
2. highlight your_app_name_here
3. backspace
4. start typing "your_app_name_here". 

Expected results: label value suggested
Actual results: nothing happens or label is suggested

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.5
- Data source type & version: loki, version unknown
- OS Grafana is installed on: whatever OS the grafana helm charts uses
- User OS & Browser: Ubuntu, Chrome Version 88.0.4324.182 (Official Build) (64-bit)
- Grafana plugins: None
- Others:

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
Re-editing of Loki label values was problem if user had just 1 log stream selector. In that case, this part of code `if (!labelKey && !isValueStart && selector === EMPTY_SELECTOR) {` resulted in wrong/non-functional autocomplete, because selector was at that time empty and we weren't at the labelValueStart. As soon as we had 2 log stream selectors this wasn't an issue because `if (!labelKey && !isValueStart && selector === EMPTY_SELECTOR) {` would be falsy (we would have non-empty selector) and there this would be skipped and autocomplete would work as expected.

This PR fixed the autocomplete when re-editing Loki label values by making sure, that we check if we have a labelKey. If we do, we naturally want to skip this part of code as we don't need to list all labelKeys. If we don't have it, then we want to list all labelKeys. 

Fixed:
https://user-images.githubusercontent.com/30407135/110500759-d42f1700-80f9-11eb-848b-5b5d0282d25c.mov

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/31705

### CODE REVIEW

File: public/app/plugins/datasource/loki/language_provider.ts [hunk 1]
```diff
@@ -269,7 +269,7 @@ export default class LokiLanguageProvider extends LanguageProvider {
       selector = EMPTY_SELECTOR;
     }
 
-    if (!isValueStart && selector === EMPTY_SELECTOR) {
+    if (!labelKey && !isValueStart && selector === EMPTY_SELECTOR) {
```
Comment (ifrost) [inline public/app/plugins/datasource/loki/language_provider.ts:272]: Could it be simplified to: `!labelKey && selector === EMPTY_SELECTOR`?

 It seems to be covering the case when the very first label is being typed. It can only happen when the selector is empty and no label is fully defined yet. Once the label is defined the value of `isValueStart` won't matter  so it could be removed from the condition.

Comment (ivanahuckova) [inline public/app/plugins/datasource/loki/language_provider.ts:272]:
```suggestion
    if (!labelKey && selector === EMPTY_SELECTOR) {
```

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/language_provider.ts]: Yes, you are correct. Nice catch.

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/language_provider.ts]: Changed in 3e204e2

**Review by ifrost — APPROVED** [review]
