### PR TITLE
[As code] correct trim/apply defaults when import/export dashboards

### LINKED ISSUE #38724: Schema: Fix default trimming behavior
Currently, default trimming (as encapsulated in [this function](https://github.com/grafana/grafana/blob/79e79fe24489d57a56db64d9b8839ddc598e16ae/pkg/schema/schema.go#L312)) fails to produce useful results on essentially any dashboard JSON, as our currently logic fails to correctly handle [the disjunctions we dynamically create](https://gist.github.com/sdboyer/a8a5eacb9ceac45aca5c77cb7a34661b#file-dashboard-cue-L62-L409) to integrate plugin-defined schema into the definition of panels. The result is that all default-stripped dashboards we create end up just removing everything: `panels: []`.

Default stripping needs to be rewritten so that it works correctly over disjunctions. (Note: doing this properly/selecting the right disjunction branch may involve doing anti-unification, which i understand to be a generally known algorithm in the CS/theoretical world, but has not yet been implemented in CUE.)

### PR DESCRIPTION
**Pull request by ying-jeanne**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #38724

**Special notes for your reviewer**:
With the current change, we can choose the right branch of panel definition and trim/apply defaults on the schema. need massive testing with different panel type with import/export to make sure that we cover all the corner cases.

### CODE REVIEW

**Comment by sdboyer** [comment]
For one part of our testing strategy, at least initially, i'd recommend we rely on devenv again:

1. As in [`TestDevenvDashboardValidity`](https://github.com/grafana/grafana/blob/fcbcfd232b59228b086d7d0b5a9e36d119523485/pkg/schema/load/load_test.go#L56), load up all the devenv dashboards with at least schema version 30
2. Run trim defaults. Not sure what to check for here apart from non-errors, but maybe we can think of some useful, fully general checks to make
3. Unify with the schema again, render to JSON, and check that the result is the same as the original input

This all would have the effect of ensuring symmetry of these operations, which is a crucial premise of what we're doing.

Beyond that, testing should probably be more unit test-ish - write some more txtars that explore some significantly different cases of schema containing disjunctions.

File: pkg/schema/schema.go [hunk 1]
```diff
@@ -381,34 +456,44 @@ func removeDefaultHelper(inputdef cue.Value, input cue.Value) (cue.Value, bool,
...
+				re, isEqual, err := removeDefaultHelper(ref, iter.Value())
+				if err == nil && !isEqual {
+					reString, err := convertCUEValueToString(re)
+					if err != nil {
+						return rv, true, nil
+					}
+					iterlist = append(iterlist, reString)
+				}
 			}
+			iterlistContent := fmt.Sprintf("[%s]", strings.Join(iterlist, ","))
```
[the remark this answers is not in the document]
Comment (ying-jeanne) [reply pkg/schema/schema.go:487]: I am not sure now the list fill path index is working, it was not working at all, that is why i have to generate the string and build the entire list again to fill the list instead of list element.

File: pkg/schema/schema.go [hunk 2]
```diff
@@ -417,6 +502,40 @@ func removeDefaultHelper(inputdef cue.Value, input cue.Value) (cue.Value, bool,
...
+				return def, nil
+			}
+		}
+		// no matching branches? wtf
+		return def, errors.New("no branch is found for list")
+	}
+	return def, nil
+}
+
+func PrintCUE(v cue.Value) string {
```
[the remark this answers is not in the document]
Comment (ying-jeanne) [reply pkg/schema/schema.go:520]: I didn't want to put it in the schema, just keep for now in case of debugging, what do you think i just remove it when the PR is ready?

File: pkg/schema/schema.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (sdboyer) [reply pkg/schema/schema.go:487]: i have also found lists quite frustrating to work with 😢

File: pkg/schema/schema.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (sdboyer) [reply pkg/schema/schema.go:520]: works for me, we'll remove before merging

File: pkg/schema/schema.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (sdboyer) [reply pkg/schema/schema.go:487]: This func may help https://pkg.go.dev/cuelang.org/go@v0.4.0/cue#Context.NewList

File: devenv/dev-dashboards/datasource-elasticsearch/elasticsearch_compare.json [hunk 3]
```diff
@@ -10530,14 +10526,21 @@
...
           "calcs": [],
           "displayMode": "list",
+          "isVisible": false,
           "placement": "bottom"
         },
         "tooltip": {
           "mode": "single"
         }
       },
+      "panelSchema": [
```
Comment (ying-jeanne) [inline devenv/dev-dashboards/datasource-elasticsearch/elasticsearch_compare.json:10539]: this probably is not correct since it is optional with [number, number], we should ignore it.

File: devenv/dev-dashboards/datasource-elasticsearch/elasticsearch_compare.json [hunk 4]
```diff
@@ -10596,6 +10599,8 @@
         }
       ],
       "title": "Old & new script format",
+      "transformations": [],
```
Comment (ying-jeanne) [inline devenv/dev-dashboards/datasource-elasticsearch/elasticsearch_compare.json:10602]: this is a fake default for list, need to be removed.

File: devenv/dev-dashboards/home.json [hunk 5]
```diff
@@ -40,12 +46,25 @@
...
       "pluginVersion": "8.1.0-pre",
+      "repeatDirection": "h",
       "tags": [],
       "title": "Starred",
+      "transformations": [],
+      "transparent": false,
       "type": "dashlist"
     },
     {
+      "fieldConfig": {
```
Comment (ying-jeanne) [inline devenv/dev-dashboards/home.json:62]: need to check here whether it should be present

File: pkg/schema/schema.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (ying-jeanne) [reply pkg/schema/schema.go:532]: going to fix it in the pr of update 0.4.0

[the remark this answers is not in the document]
Comment (sdboyer) [reply pkg/schema/schema.go:526]: good, we need that PR for multiple reasons now, anyway

File: pkg/schema/rtinstance/rtinstance.go [hunk 6]
```diff
@@ -0,0 +1,7 @@
+package rtinstance
```
Comment (sdboyer) [inline pkg/schema/rtinstance/rtinstance.go:1]: Let's put this whole package under an `internal` dir. (so, `pkg/schema/internal/rt`.) We need to be doing a lot more of this in general, and this feels an especially good place to start.

File: pkg/schema/rtinstance/rtinstance.go [hunk 7]
```diff
@@ -0,0 +1,7 @@
...
+
+import (
+	"cuelang.org/go/cue"
+)
+
+var Rt = &cue.Runtime{}
```
Comment (sdboyer) [inline pkg/schema/rtinstance/rtinstance.go:7]: `rt` was an acceptable name when the variable was unexported, but exporting it - even from `internal` - means it should be a real word.
```suggestion
var Runtime = &cue.Runtime{}
```

(of course, it should change to `CueContext` after the v0.4.0 update)

**Review by sdboyer — COMMENTED** [review]
initial round of notes, not a complete review yet

File: pkg/schema/internal/rt.go [hunk 8]
```diff
@@ -0,0 +1,7 @@
+package internal
```
Comment (sdboyer) [inline pkg/schema/internal/rt.go:1]: ah, `pkg/schema/internal/rt`, not `pkg/schema/internal`

**Review by sdboyer — CHANGES_REQUESTED** [review]

File: pkg/schema/load/load_test.go [hunk 9]
```diff
@@ -175,3 +175,83 @@ func TestCueErrorWrapper(t *testing.T) {
...
+					// store the trimmed result into testdata for easy debug
+
+					out, err := schema.ApplyDefaults(schema.Resource{Value: trimmed.Value.(string)}, dsSchema.CUE())
+					require.NoError(t, err)
+
+					file, _ := os.Create(filepath.Join("testdata", filepath.Base(path)))
+					defer file.Close()
+					var jsonMap map[string]interface{}
+					json.Unmarshal([]byte(out.Value.(string)), &jsonMap)
+					jdata, err := json.MarshalIndent(jsonMap, "", "  ")
```
[the remark this answers is not in the document]
Comment (sdboyer) [reply pkg/schema/load/load_test.go]: ok if it's just a helper, nbd

File: pkg/schema/internal/rt.go (hunk 8 above)
Comment (ying-jeanne) [reply pkg/schema/internal/rt.go:1]: :D ooooooops

Comment (sdboyer) [reply pkg/schema/internal/rt.go:1]: no worries :)

Comment (ying-jeanne) [reply pkg/schema/internal/rt.go:1]: that means internal is in the package schema? i would have a cyclic import i think again.

Comment (ying-jeanne) [reply pkg/schema/internal/rt.go:1]: oh you mean pkg/schema/internal/internal.go?

**Review by sdboyer — CHANGES_REQUESTED** [review]
The trimming logic generally looks good! i haven't reviewed in detail, but that test is really promising :)

i think we need to change testing approach a little, here - we're not ready to require that the contents of devenv have the defaults fully applied yet, because that would require devs to change their workflows for updating devenv further, and we're not yet ready to support that.

To deal with things in the interim, i think we can have this test work just slightly differently. For each dashboard in devenv:

1. First, apply defaults to it, then write the result to somewhere under `testdata`
2. Then, trim defaults, and write that to somewhere under `testdata`
3. Then, re-apply defaults to the trimmed defaults, and ensure it matches the original applied version.

The proper approach here involves some kind of [golden files](https://ieftimov.com/post/testing-in-go-golden-files/) pattern, though we can work on getting that exactly right later.

**Comment by sdboyer** [comment]
Also, let's move away from `test1`, `test2`, etc., and towards at least somewhat-descriptive names for the files

**Comment by ying-jeanne** [comment]
> The trimming logic generally looks good! i haven't reviewed in detail, but that test is really promising :)
> 
> i think we need to change testing approach a little, here - we're not ready to require that the contents of devenv have the defaults fully applied yet, because that would require devs to change their workflows for updating devenv further, and we're not yet ready to support that.
> 
> To deal with things in the interim, i think we can have this test work just slightly differently. For each dashboard in devenv:
> 
>     1. First, apply defaults to it, then write the result to somewhere under `testdata`
> 
>     2. Then, trim defaults, and write that to somewhere under `testdata`
> 
>     3. Then, re-apply defaults to the trimmed defaults, and ensure it matches the original applied version.
> 
> 
> The proper approach here involves some kind of [golden files](https://ieftimov.com/post/testing-in-go-golden-files/) pattern, though we can work on getting that exactly right later.

amazing idea :), didn't think about it.

**Comment by ying-jeanne** [comment]
when running the validation against demo_kit repository, we have several dashboard json fails:

```
--- FAIL: TestDevenvDashboardValidity (2.85s)
        --- FAIL: TestDevenvDashboardValidity/dist/nr-dd-prom-snow-mysql-sheets-etc.json (0.19s)
        --- FAIL: TestDevenvDashboardValidity/dist/grafana-internal-metrics.json (0.18s)
        --- FAIL: TestDevenvDashboardValidity/dist/grafana-labs-ref-archs.json (0.12s)
        --- FAIL: TestDevenvDashboardValidity/dist/grafana-ml.json (0.10s)
        --- FAIL: TestDevenvDashboardValidity/dist/oracle-datasource-explainer.json (0.26s)
        --- FAIL: TestDevenvDashboardValidity/dist/oracle-main.json (0.14s)
        --- FAIL: TestDevenvDashboardValidity/dist/salesforce.json (0.09s)
```
We might need to correct those dashboard json or schema first before.

File: pkg/schema/internal/rt/rtinstance.go [hunk 10]
```diff
@@ -0,0 +1,5 @@
+package internal
```
Comment (sdboyer) [inline pkg/schema/internal/rt/rtinstance.go:1]: See if we can remove this entirely, now that we have `v0.4.0`

**Review by sdboyer — CHANGES_REQUESTED** [review]
Almost there!

**Review by sdboyer — APPROVED** [review]
Just some little nits, but looks good, merge away!
