### PR TITLE
Dashboard: handle the case where `refresh_intervals` could be null

### LINKED ISSUE #32707: broken dashboard if timepicker.refresh_intervals === null
**What happened**:

broken dashboard if in dashboard settings JSON model add:
```
timepicker: { refresh_intervals: null }
```
image

This happed because in `TimeSrv.ts` line 155 
`      refreshIntervals: this.dashboard?.timepicker?.refresh_intervals` refreshIntervals = null and in `getRefreshFromUrl` is default parameter `refreshIntervals = defaultIntervals` that is skipped..

UPD: to correct reproduce this you need query parameter `refresh=<value>`

**What you expected to happen**:

valid dashboard

**How to reproduce it (as minimally and precisely as possible)**:

set in JSON model `timepicker.refresh_intervals = null`

**Environment**:
- Grafana version: 7.5.2
- Data source type & version: any
- OS Grafana is installed on: official docker image
- User OS & Browser: any
- Grafana plugins: any
- Others:

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- if `refresh_intervals` is set to null, the dashboard fails to load because the default value in `getRefreshIntervals` does not apply, and it tries to do `null.find`
- pass `undefined` instead of `null`, which allows the default value to be applied
- add a unit test to prevent regression

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/32707

**Special notes for your reviewer**:

- realised `_dashboard` was being shared between all tests, so i moved it into the `beforeEach` so it starts from a clean state each time, else setting `timepicker` could affect other tests.

### CODE REVIEW

File: public/app/features/dashboard/services/TimeSrv.ts [hunk 1]
```diff
@@ -156,7 +156,9 @@ export class TimeSrv {
     this.refresh = getRefreshFromUrl({
       params: paramsJSON,
       currentRefresh: this.refresh,
-      refreshIntervals: this.dashboard?.timepicker?.refresh_intervals,
+      refreshIntervals: Array.isArray(this.dashboard?.timepicker?.refresh_intervals)
+        ? this.dashboard?.timepicker?.refresh_intervals
+        : undefined,
```
Comment (tskarhed) [inline public/app/features/dashboard/services/TimeSrv.ts:161]: It's a good idea to be explicit about which value you want to default to as soon as you use `?`, right?

**Review by tskarhed — APPROVED** [review]
LGTM! :partying_face:

File: public/app/features/dashboard/services/TimeSrv.ts (hunk 1 above)
Comment (ashharrison90) [reply public/app/features/dashboard/services/TimeSrv.ts:161]: @tskarhed do you mean like removing the optional chaining from the first option? 🤔 

e.g.
```javascript
      refreshIntervals: Array.isArray(this.dashboard?.timepicker?.refresh_intervals)
        ? this.dashboard.timepicker.refresh_intervals
        : undefined,
```
