### PR TITLE
Alerting: Resend alerts for states that are missing in the eval results

### LINKED ISSUE #105571: Alerting: Resolved notifications incorrectly sent for firing alert with missing series
## Context
A single edge server, with fieldbus connection to 100's of embedded devices, pushing metrics to a local otelcol instance, which forwards metrics to a self-hosed otelcol in AWS, and finally to a self-hosted Prometheus instance in AWS. Alerting and dashboards are driven from a self-hosted Grafana instance alongside Prometheus.

## Problem
I have an alert triggered off a simple gauge metric (“devices_offline”), which reflects the number of embedded devices that the edge server failed to communicate with (usually because they’re powered off or have some fault).

When the edge server loses connectivity, it of course can’t push metrics to the cloud Prometheus instance. I have the alert rule set up to execute every 5m, with ‘Alert state if no data or all values are null’ set to ‘Keep Last State’. I have also set Missing series evaluations to resolve to a high value (2016, which is 7 days at 5 minute evaluation periods).

In the alert state history, everything looks right - through transient connectivity drops (lasting for 10m to an hour), the alert just stays in the firing state. However, we’re receiving Resolved notifications when the data drops out and new Firing notifications when it comes back, even though the alert state history itself showed no changes.

### What did you expect to happen?

I expected to receive no Resolved notification

### Did this work before?

This is the first alert I've configured in our shiny new Grafana deployment :)

### How do we reproduce it?

1. Configure an alert with *Alert state if no data or all values are null* set to `Keep Last State` and *Missing series evaluations to resolve* set to a number higher than 4
2. Stop submitting data for the timeseries that the alert queries
3. Observe *Resolved* notification getting sent after 4 evaluation periods of missing data

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 12.0.0 arm64
OS: Debian 12.10
Browser: Firefox

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Prometheus 3.3.0

### PR DESCRIPTION
**Pull request by alexander-akhmetov**
**What is this feature?**

This PR fixes the `MissingSeriesEvalsToResolve` behavior when it's set to more than 4 evaluation intervals.

**Why do we need this feature?**

The `MissingSeriesEvalsToResolve` setting was not working correctly due to alerts being auto-resolved by Alertmanager after 4 evaluation intervals (via the `endsAt` field).

Before we had `deleteStaleStatesFromCache` method that was returning only stale states that had to be resolved. Non-stale states for which the current evaluation does not have a series never had `endsAt` updated and were never resend to the Alertmanager, so they were automatically resolved after 4 evaluations regardless of the setting.

The new `processMissingSeriesStates` returns state for each missing series on every evaluation, and resolves the stale ones. This guarantees that alerts without series still alert for the configured number of evaluations.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/105571

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: pkg/services/ngalert/state/manager.go [hunk 1]
```diff
@@ -516,30 +516,50 @@ func translateInstanceState(state ngModels.InstanceStateType) eval.State {
...
+	for _, tr := range evalTransitions {
+		present[tr.CacheID] = struct{}{}
+	}
+
+	missingTransitions := []StateTransition{}
+	staleCount := 0
 
-	for _, s := range staleStates {
-		logger.Info("Detected stale state entry", "cacheID", s.CacheID, "state", s.State, "reason", s.StateReason)
+	for _, s := range st.cache.getStatesForRuleUID(alertRule.OrgID, alertRule.UID) {
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/state/manager.go:536]: this method creates a copy of the state. I wonder if it would be better to just iterate over state within mutex. Something like
```
st.cache.forRuleState(alertRule.OrgID, alertRule.UID, func(rs *ruleState) { ... })

Comment (alexander-akhmetov) [reply pkg/services/ngalert/state/manager.go]: Good point, changed

File: pkg/services/ngalert/state/manager.go [hunk 2]
```diff
@@ -517,30 +517,49 @@ func translateInstanceState(state ngModels.InstanceStateType) eval.State {
...
+// for series that are no longer present in the current evaluation.
+// For each missing state, we check if it is stale, and if so, we resolve it.
+// At the end we return the missing states so that later they can be sent
+// to the alertmanager if needed.
+func (st *Manager) processMissingSeriesStates(logger log.Logger, evaluatedAt time.Time, alertRule *ngModels.AlertRule, evalTransitions []StateTransition, takeImageFn takeImageFn) ([]StateTransition, int) {
+	// Build a set of states for series we saw in this evaluation
+	present := make(map[data.Fingerprint]struct{}, len(evalTransitions))
+	for _, tr := range evalTransitions {
+		present[tr.CacheID] = struct{}{}
+	}
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/state/manager.go:532]: I am not sure we need this map here. I think any state that has LastEvaluationTime < evaluatedAt can be considered "stale candidate".
We iterate through all states anyway, so this won't save us anything.

File: pkg/services/ngalert/state/state.go [hunk 3]
```diff
@@ -581,7 +581,7 @@ func resultKeepLast(state *State, rule *models.AlertRule, result eval.Result, lo
 // - The state has been resolved since the last notification.
 // - The state is firing and the last notification was sent at least resendDelay ago.
 // - The state was resolved within the resolvedRetention period, and the last notification was sent at least resendDelay ago.
-func (a *State) NeedsSending(resendDelay time.Duration, resolvedRetention time.Duration) bool {
+func (a *State) NeedsSending(evaluatedAt time.Time, resendDelay time.Duration, resolvedRetention time.Duration) bool {
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/state/state.go:584]: I think `evaluatedAt` can be called "now", which would make it clearer.

File: pkg/services/ngalert/state/cache.go [hunk 4]
```diff
@@ -253,6 +249,25 @@ func (c *cache) getStatesForRuleUID(orgID int64, alertRuleUID string) []*State {
...
+		return
+	}
+
+	rs, ok := orgRules[alertRuleUID]
+	if !ok {
+		return
+	}
+
+	for _, state := range rs.states {
+		fn(state)
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/state/cache.go:267]: Perhaps it makes sense to encapsulate deletion of stale state here? This would be more atomic operation.

**Review by yuri-tceretian — APPROVED** [review]
LGTM
