### PR TITLE
Alerting: Fix TestIntegration_GetAlertRulesForScheduling to make sure rules are created in different org

### LINKED ISSUE #68996: Alerting: Flake TestIntegration_GetAlertRulesForScheduling integration test
**What**

It looks like `TestIntegration_GetAlertRulesForScheduling` is a flake integration test [(example)](https://drone.grafana.net/grafana/grafana/117986/6/15):

```
--- FAIL: TestIntegration_GetAlertRulesForScheduling (0.24s)
    --- FAIL: TestIntegration_GetAlertRulesForScheduling/with_a_filter_on_orgs,_it_returns_rules_that_do_not_belong_to_that_org (0.00s)
        alert_rule_test.go:154: 
            	Error Trace:	/drone/src/pkg/services/ngalert/store/alert_rule_test.go:154
            	Error:      	"[]" should have 1 item(s), but has 0
            	Test:       	TestIntegration_GetAlertRulesForScheduling/with_a_filter_on_orgs,_it_returns_rules_that_do_not_belong_to_that_org
    --- FAIL: TestIntegration_GetAlertRulesForScheduling/with_populate_folders_enabled_and_a_filter_on_orgs,_it_only_returns_selected_information (0.00s)
        alert_rule_test.go:154: 
            	Error Trace:	/drone/src/pkg/services/ngalert/store/alert_rule_test.go:154
            	Error:      	"[]" should have 1 item(s), but has 0
            	Test:       	
```

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What is this feature?**
This PR fixes an integration test `TestIntegration_GetAlertRulesForScheduling` by making sure that key fields the test relies upon like ID and OrgID of two rules are created unique.

**Why do we need this feature?**
Fix a flaky integration test.

**Who is this feature for?**
For developers who have to re-run CI after a failed test.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/68996

**Special notes for your reviewer:**

### CODE REVIEW

File: pkg/services/ngalert/store/alert_rule_test.go [hunk 1]
```diff
@@ -88,15 +88,14 @@ func TestIntegration_GetAlertRulesForScheduling(t *testing.T) {
...
+		SQLStore:      sqlStore,
+		Cfg:           cfg.UnifiedAlerting,
 		FolderService: setupFolderService(t, sqlStore, cfg),
 	}
 
-	rule1 := createRule(t, store)
-	rule2 := createRule(t, store)
+	generator := models.AlertRuleGen(withIntervalMatching(store.Cfg.BaseInterval), models.WithUniqueID(), models.WithUniqueOrgID())
+	rule1 := createRule(t, store, generator)
+	rule2 := createRule(t, store, generator)
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/store/alert_rule_test.go:98]: this is the fix

**Review by grobinson-grafana — APPROVED** [review]

File: pkg/services/ngalert/models/testing.go [hunk 2]
```diff
@@ -140,6 +140,21 @@ func WithOrgID(orgId int64) AlertRuleMutator {
 	}
 }
 
+func WithUniqueOrgID() AlertRuleMutator {
```
Comment (grobinson-grafana) [inline pkg/services/ngalert/models/testing.go:143]: In the past I've used `sync/atomic` to keep incrementing a uint64, avoids the need to keep a map of orgIDs.

**Review by grobinson-grafana — APPROVED** [review]

File: pkg/services/ngalert/models/testing.go (hunk 2 above)
Comment (yuri-tceretian) [reply pkg/services/ngalert/models/testing.go:143]: I chose this approach because of two reasons:
1. there is a similar function WithUniqueID that implements the same approach
2. it lets us use randomization instead of monotonic increments, which expands the test to all possible values of the field type.

**Review by JacobsonMT — APPROVED** [review]
