### PR TITLE
AppChromeService: Improve `useChromeHeaderHeight` to only react to necessary state changes

### LINKED ISSUE #93219: Grafana/Runtime: using useChromeHeaderHeight results in infinite rendering cycle
`useChromeHeaderHeight` should just return a height of the header based on a visual mode grafana is in like `kiosk` or `chromeless`. This information though is all inside `AppChromeService` state and so the hook is dependant on the whole `AppChromeService.state` for this.
https://github.com/grafana/grafana/blob/334657e1cb46bc30699dfcafef14e1b42e86dbd8/public/app/core/context/GrafanaContext.ts#L49

It seems that because of this in some case the hook can create a cycle, if the render path also changes something in the `AppChromeService.state` most likely `sectionNav`.

### Repro scenario
To test this behavior, minimal report seems to be to add these lines:
```
const height = useChromeHeaderHeight();
console.log(height);
```
here
https://github.com/grafana/grafana/blob/47f87171496f675bc44ddf839effaed1846bfa4e/public/app/features/explore/ExploreToolbar.tsx#L71

which should result in
```
An unexpected error happened
Details
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

------------------

This may not be a clear bug on the side of `useChromeHeaderHeight` hook. This happens in Explore probably because of updating the `AppChromeService.state` like here https://github.com/grafana/grafana/blob/40157111336615a85440f990dd584c93c42600b6/public/app/features/explore/ExplorePage.tsx#L70

I think though that such dependant behavior is very surprising in this case and I think we should find a way to make the `useChromeHeaderHeight` not force rerender on changes of `AppChromeService.state` that aren't relevant to it, in a similar way that you can select only parts of Redux state that are relevant to render using selectors.

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- creates a new `headerHeightObservable` in `AppChromeService`
  - subscribers are only notified when the value changes, instead of when any of the state changes
- updates `useChromeHeaderHeight` to subscribe to this new observable 

**Why do we need this feature?**

- so `useChromeHeaderHeight` only updates when necessary
- prevent render loop when using `useChromeHeaderHeight` and `AppChromeUpdate` in the same component

**Who is this feature for?**

- grafana devs

**Which issue(s) does this PR fix?**:

Fixes #93219 

**Special notes for your reviewer:**

my rxjs isn't the best so there might be a better way to do this 🙏 

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/core/components/AppChrome/AppChromeService.tsx [hunk 1]
```diff
@@ -56,6 +57,31 @@ export class AppChromeService {
     returnToPrevious: this.returnToPreviousData,
   });
 
+  public headerHeightObservable = this.state
```
Comment (joshhunt) [inline public/app/core/components/AppChrome/AppChromeService.tsx:60]: this `headerHeightObservable` is like a... sub-observable? It's not a new piece of state, but it's connected to the one 'global' state and only emits changes when it's portion changes?

**Review by joshhunt — APPROVED** [review]

File: public/app/core/components/AppChrome/AppChromeService.tsx (hunk 1 above)
Comment (ashharrison90) [reply public/app/core/components/AppChrome/AppChromeService.tsx:60]: yep exactly. it will only emit changes if the actual value changes. my rxjs knowledge isn't amazing, so if there's a better pattern i can change this 🙇
