### PR TITLE
Alerting: Allow space in label and annotation names

### LINKED ISSUE #36094: Notifications not getting sent when details contain spaces
**What happened**: Notifications do not get sent when you add a new details for alert with space in it. 

**What you expected to happen**: Notifications to get sent 

**How to reproduce it (as minimally and precisely as possible)**: 
Add custom detail with space in it.  See picture below!

**Anything else we need to know?:** 
image

**Environment:**
Grafana version: 8.0.3
Data source type & version: Prometheus / Thanos
OS Grafana is installed on: Azure AKS, official Grafana
User OS & Browser: not relevant
Grafana plugins: clean install
Others:

### PR DESCRIPTION
**Pull request by codesome**
**What this PR does / why we need it**:

Implements custom validation of alerts in the notifier to allow spaces in label and annotation names. 

**Which issue(s) this PR fixes**:

Fixes #36094

**Special notes for your reviewer**:

All validation is a copy paste from upstream Prometheus with `isValidLabelName` modified to support a space. Here are some references for the copy paste:

https://github.com/prometheus/common/blob/a1b6ede20323252d2b99a0f57178a4b7d364d0ca/model/alert.go#L84-L102

https://github.com/prometheus/common/blob/a1b6ede20323252d2b99a0f57178a4b7d364d0ca/model/labelset.go#L30-L42

https://github.com/prometheus/common/blob/a1b6ede20323252d2b99a0f57178a4b7d364d0ca/model/labels.go#L91-L113

### CODE REVIEW

File: pkg/services/ngalert/notifier/alertmanager.go [hunk 1]
```diff
@@ -528,6 +528,59 @@ func (am *Alertmanager) PutAlerts(postableAlerts apimodels.PostableAlerts) error
...
+// while we will follow ^[a-zA-Z_][a-zA-Z0-9_ ]*$
+func isValidLabelName(ln model.LabelName) bool {
+	if len(ln) == 0 {
+		return false
+	}
+	for i, b := range ln {
+		if !((b >= 'a' && b <= 'z') ||
+			(b >= 'A' && b <= 'Z') ||
+			b == '_' ||
+			(i > 0 && (b == ' ' || (b >= '0' && b <= '9')))) {
```
Comment (papagian) [inline pkg/services/ngalert/notifier/alertmanager.go:577]: I wonder whether we need to support any other special characters like `&` that can possibly appear in labels?

**Review by papagian — APPROVED** [review]
AFAICT LGTM
I would suggest adding a warning in the logs [when an alert fails to validate.](https://github.com/grafana/grafana/blob/cc38613ba4c7ef49e52f4206b4284ac94e320315/pkg/services/ngalert/notifier/alertmanager.go#L514)

File: pkg/services/ngalert/notifier/alertmanager.go (hunk 1 above)
Comment (codesome) [reply pkg/services/ngalert/notifier/alertmanager.go:577]: At the moment I would prevent supporting any more characters until we get any requests.

**Comment by codesome** [comment]
> I would suggest adding a warning in the logs

These will actually be logged as error a few level above with "failed to put alerts in the notifier" in the scheduler. So I guess we can skip additional logs here?

**Comment by codesome** [comment]
Added this to 8.0.6 milestone with backport label since this could be a potential blocker for migration to ngalert and should be fixed in 8.0.x.

**Comment by papagian** [comment]
> I would suggest adding a warning in the logs when an alert fails to validate.

I see that there will be actually a log error [here](https://github.com/grafana/grafana/blob/a86ad1190c0b1da546c5b52fdbddec2860ceaec4/pkg/services/ngalert/schedule/schedule.go#L221) so no need for extra logging
