### PR TITLE
Variables: Fixes so queries work for numbers values too

### LINKED ISSUE #30595: Some queries don't work in Query variables (7.4.0 beta 1)
**What happened**:
After the last update queries with functions like **count, cast** throw an error
Screenshot_5

**Environment**:
- Grafana version: 7.4.0 beta 1
- Data source type & version: postgeSQL 12 + timescaleDB 2.0-rc1
- OS Grafana is installed on: ubuntu 20.04
- User OS & Browser: windows 10, chrome
- Grafana plugins:
- Others:

**Log:**
[log.log](https://github.com/grafana/grafana/files/5866110/log.log)

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
When we check if the data from the data source is a metric find value or not I made a silly mistake and only allowed return values of string type. This PR opens up so other types are valid for metric find values.

**Which issue(s) this PR fixes**:
Fixes #30595

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/variables/query/operators.ts [hunk 1]
```diff
@@ -183,5 +181,26 @@ export function areMetricFindValues(data: any[]): data is MetricFindValue[] {
...
+  if (isDataFrame(firstValue)) {
+    return false;
+  }
+
+  for (const firstValueKey in firstValue) {
+    if (
+      !firstValue.hasOwnProperty(firstValueKey) ||
+      typeof firstValue[firstValueKey] === 'object' ||
+      typeof firstValue[firstValueKey] === 'function' ||
+      typeof firstValue[firstValueKey] === 'symbol'
```
Comment (hugohaggmark) [inline public/app/features/variables/query/operators.ts:193]: What is an allowed return type?

Comment (torkelo) [reply public/app/features/variables/query/operators.ts:193]: not nested sub objects & functions. If it's an object that has a value prop that is string or number, and a text prop that is a string )

Comment (hugohaggmark) [reply public/app/features/variables/query/operators.ts]: Thank you, I've changed it to string or number. Regarding text and value, I've seen results with only the text property so I'm just checking if anyone of them exists.

**Review by dprokop — APPROVED** [review]
LGTM!
