### PR TITLE
Dynamic dashboards: Fix empty space under time controls when dashboard has many variables

### LINKED ISSUE #103516: A lot of empty space when using a large adhoc filter
**Steps to reproduce**:
1. Add an ad hoc filter on the dashboard
2. On the dashboard, add a link to all desktops
3. Add a lot of adhock filters

**Actual Result**:

Image

**Expected Result**
Is it possible to return the location that it was before in 8.5.16

Image
The link to the desktop is located in the lower right corner and the location under the time selection is used.

**Environment**:
- Grafana version: 11.6.0
- Data source type & version: elasticsearch
- User OS & Browser: windows / google chrome
- Others:

### PR DESCRIPTION
**Pull request by oscarkilhed**
Fixes excessive empty space under time controls when dashboards have many variables or large adhoc filters. Variables now wrap underneath the time controls instead of creating empty space.

image

Implemented float-based layout for time controls: Switched from flexbox to CSS floats. Time controls use `float: 'right'` so variables flow around them and wrap underneath when needed, eliminating the empty space.

This should keep the existing visual appearance while fixing the layout issue.

Fixes #103516

### CODE REVIEW

**Review by mdvictor — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/19336291009)
- Version: 12.4.0-19336291009

File: public/app/features/dashboard-scene/scene/DashboardControls.tsx [hunk 1]
```diff
@@ -240,6 +234,8 @@ function getStyles(theme: GrafanaTheme2) {
       display: 'flex',
       justifyContent: 'flex-end',
       gap: theme.spacing(1),
+      marginBottom: theme.spacing(1),
+      float: 'right',
```
Comment (torkelo) [inline public/app/features/dashboard-scene/scene/DashboardControls.tsx:238]: @oscarkilhed this float is making the controls not take up the height the it needs, so if you only have time controls (no variables), the spacing between time picker and the dashboard panels is wrong
