### PR TITLE
Cloudwatch Logs: Set Alerting timeout to datasource config's logsTimeout (#72611)

### LINKED ISSUE #63305: CloudWatch Logs: Make alertMaxAttempts configurable
**What happened**:
Hi,
We have the Grafana alert based on AWS Cloudwatch Logs query. 
Sometimes the alert fails with the errors, and the error messages are below:
`logger=ngalert.scheduler rule_uid=oEDtfR2Vk org_id=1 version=13 attempt=0 now=2023-02-13T02:09:00Z t=2023-02-13T02:09:12.596886776Z level=error msg="Failed to evaluate rule" error="[plugin.downstreamError] failed to query data: fetching of query results exceeded the max number of attempts" duration=0s`

As per alert state histories, Sometimes all are good and data is returned and the alert works fine.
Screenshot 2023-02-13 at 3 02 57 PM

Does anybody have an idea?

**What you expected to happen**:
Alert shouldn't happen freqently.

**How to reproduce it (as minimally and precisely as possible)**:
Use the query from AWS CloudWatch log.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: CloudWatch
- OS Grafana is installed on: Amazon Linux
- User OS & Browser:
- Grafana plugins: CloudWatch
- Others:

### PR DESCRIPTION
**Pull request by idastambuk**
**What is this feature?**

When getting results for CW Logs queries, the client needs to get the ID of the query first, then periodically poll the results with GetQueryResults. The Status of the query we get from AWS is "Running". Once the request resolves with Status "Done", it will contain complete results. More info [here](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_GetQueryResults.html)

In CloudwatchLogsQueryRunner for dashboards and explore, there is a timeout set in the ConfigEditor (default: 30 minutes) to retry query results for Cloudwatch Logs queries with GetQueryResults. 

After [some users](https://github.com/grafana/grafana/issues/63305#issuecomment-1553881446) noticed they were getting `"failed to query data: fetching of query results exceeded max number of attempts"` errors in their alerts, we decided to make this option configurable (only for alerts). However, in the process we discovered that the 30 minute configuration wasn't being used on the BE for alert queries. Instead, CW datasource plugin polled the results for 8 seconds maximum, which might be too short for some queries. 

So instead of making this configurable, we decided to first use this setting from ConfigEditor and make it 30 minutes. 
**Note that this means that some queries will timeout with the alerting runner's error "context cancelled", since the default value when running queries in this context is 30s (https://github.com/grafana/grafana/blob/main/conf/defaults.ini#L1207) but this can be increased per instance and doesn't need any change in the code**

The next step in improving this flow will be to not poll the results every second, but to instead do something like in [async-query-data](https://github.com/grafana/grafana-async-query-data-js/blob/main/src/requestLooper.ts), which will increase wait time with every request that returns still "Running".
After this, we could implement a query option input that will give the user more control over how often the results are polled per-query, but it might not be necessary after ☝🏻

Some additional things in this PR: 

1. Made the tooltip in ConfigEditor more clear that this is not a retry after error, but a retry after "not yet done" response. 
2. Defined the default 30 minute timeout in executor struct, in order to be able to pass a shorter timeout for tests (otherwise the test with default value would run for 30 min 👀)
3. Moved the comment about logs queries closer to where the requests for GetQueryResults were happening (from datasource.go to log_sync_query.go, since I felt it was easy to miss where it was. Lmk if there's a better place.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/63305

**Special notes for your reviewer:**
When this is merged, I will comment [here](https://github.com/grafana/grafana/issues/63305) and [here](https://github.com/grafana/support-escalations/issues/6135) to inform the user and customer support about the change.
TODO: Add to what's new

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/tsdb/cloudwatch/cloudwatch.go [hunk 1]
```diff
@@ -80,6 +85,11 @@ func newExecutor(im instancemgmt.InstanceManager, cfg *setting.Cfg, sessions Ses
 	}
 
 	e.resourceHandler = httpadapter.New(e.newResourceMux())
+
+	if len(logsTimeout) == 1 && logsTimeout[0] != 0 {
+		e.logsTimeoutDefault = logsTimeout[0]
```
Comment (idastambuk) [inline pkg/tsdb/cloudwatch/cloudwatch.go:90]: I should probably return an error here if len > 1?

File: pkg/tsdb/cloudwatch/models/settings.go [hunk 2]
```diff
@@ -12,6 +12,7 @@ type CloudWatchSettings struct {
 	awsds.AWSDatasourceSettings
 	Namespace               string `json:"customMetricsNamespaces"`
 	SecureSocksProxyEnabled bool   `json:"enableSecureSocksProxy"` // this can be removed when https://github.com/grafana/grafana/issues/39089 is implemented
+	LogsTimeout             string `json:"logsTimeout"`
```
Comment (fridgepoet) [inline pkg/tsdb/cloudwatch/models/settings.go:15]: Right here I think the type of LogsTimeout can already be time.Duration. I think I would move the validation of the json and the initialization to default logsTimeout here too.

this bit:
```golang
    logsTimeoutDuration := e.logsTimeoutDefault

	if logsTimeout != "" {
		logsTimeoutDuration, err = time.ParseDuration(logsTimeout)
	}

	if err != nil {
		return nil, err
	}
```

File: pkg/tsdb/cloudwatch/cloudwatch.go [hunk 3]
```diff
@@ -71,7 +76,7 @@ type SessionCache interface {
 	GetSession(c awsds.SessionConfig) (*session.Session, error)
 }
 
-func newExecutor(im instancemgmt.InstanceManager, cfg *setting.Cfg, sessions SessionCache, features featuremgmt.FeatureToggles) *cloudWatchExecutor {
+func newExecutor(im instancemgmt.InstanceManager, cfg *setting.Cfg, sessions SessionCache, features featuremgmt.FeatureToggles, logsTimeout ...time.Duration) *cloudWatchExecutor {
```
Comment (fridgepoet) [inline pkg/tsdb/cloudwatch/cloudwatch.go:79]: After looking over the whole work, I think you don't need to add the logsTimeout to the executor. Instead you can inject it in your tests through the instance settings.

What you can do is (see my other comment) validate the time duration string and initialize it in `LoadCloudWatchSettings`. (I would add a test for that in settings_test.go)

File: pkg/tsdb/cloudwatch/log_sync_query.go [hunk 4]
```diff
@@ -82,7 +80,7 @@ var executeSyncLogQuery = func(ctx context.Context, e *cloudWatchExecutor, req *
 }
 
 func (e *cloudWatchExecutor) syncQuery(ctx context.Context, logsClient cloudwatchlogsiface.CloudWatchLogsAPI,
-	queryContext backend.DataQuery, logsQuery models.LogsQuery) (*cloudwatchlogs.GetQueryResultsOutput, error) {
+	queryContext backend.DataQuery, logsQuery models.LogsQuery, logsTimeout string) (*cloudwatchlogs.GetQueryResultsOutput, error) {
```
Comment (fridgepoet) [inline pkg/tsdb/cloudwatch/log_sync_query.go:83]: (see other comment, I believe you can set logsTimeout type can be time.Duration)

File: pkg/tsdb/cloudwatch/log_sync_query_test.go [hunk 5]
```diff
@@ -307,4 +307,62 @@ func Test_executeSyncLogQuery_handles_RefId_from_input_queries(t *testing.T) {
...
 	})
+
+	t.Run("when logsTimeout setting isn't defined, the polling period will be set to default value defined in cloudwatch executor", func(t *testing.T) {
+		cli = &mockLogsSyncClient{}
+		cli.On("StartQueryWithContext", mock.Anything, mock.Anything, mock.Anything).Return(&cloudwatchlogs.StartQueryOutput{
+			QueryId: aws.String("abcd-efgh-ijkl-mnop"),
+		}, nil)
+		cli.On("GetQueryResultsWithContext", mock.Anything, mock.Anything, mock.Anything).Return(&cloudwatchlogs.GetQueryResultsOutput{Status: aws.String("Running")}, nil)
+		im := datasource.NewInstanceManager(func(s backend.DataSourceInstanceSettings) (instancemgmt.Instance, error) {
+			return DataSource{Settings: models.CloudWatchSettings{}}, nil
```
Comment (fridgepoet) [inline pkg/tsdb/cloudwatch/log_sync_query_test.go:318]: right here you should be able to overwrite the timeout for the tests in `Settings: models.CloudWatchSettings{}` I believe

**Review by fridgepoet — COMMENTED** [review]
Great work, Ida!

I am fairly certain executor does not need to have the timeout. You ought to be able to inject your custom timeout for tests through the `Settings` instead. This will simplify the code a little. Let me know if I have missed something, though!

File: pkg/tsdb/cloudwatch/cloudwatch.go (hunk 1 above)
Comment (fridgepoet) [reply pkg/tsdb/cloudwatch/cloudwatch.go:90]: (If all goes as I thought, we won't need this anymore, but I think logsTimeout didn't need to be a slice. Then you wouldn't have to do this check. Let me know if I missed something!)

File: pkg/tsdb/cloudwatch/log_sync_query.go [hunk 6]
```diff
@@ -107,8 +113,8 @@ func (e *cloudWatchExecutor) syncQuery(ctx context.Context, logsClient cloudwatc
 		if isTerminated(*res.Status) {
 			return res, err
 		}
-		if attemptCount >= alertMaxAttempts {
-			return res, fmt.Errorf("fetching of query results exceeded max number of attempts")
+		if (time.Duration(attemptCount) * time.Second) >= time.Duration(logsTimeout) {
```
Comment (fridgepoet) [inline pkg/tsdb/cloudwatch/log_sync_query.go:116]: What is this part? `(time.Duration(attemptCount) * time.Second)`
what do you want to compare? I think this might be a typo

File: pkg/tsdb/cloudwatch/cloudwatch.go (hunk 3 above)
Comment (fridgepoet) [reply pkg/tsdb/cloudwatch/cloudwatch.go]: I think you have a great solution!

I originally thought of using the "DTO" solution which is to have one struct type to deserialize the JSON and another struct type to actually use everywhere else in the code, but I like the custom Unmarshaller you have created more.


I have a couple of thoughts:
1. After reading [this stackoverflow](https://stackoverflow.com/questions/48050945/how-to-unmarshal-json-into-durations), I think I slightly prefer using a struct containing time.Duration because of the comment "One thing I noticed when implementing this solution but with a type alias was that you lose some of the access to existing methods on the time.Duration type. So one example was that when implementing MarshalJSON the String method no longer existed." What do you think of that?

2. I am a little undecided if we should now set the defaults in the Unmarshal method on Duration and in the initialization in the CloudWatchSettings struct. Let me know what you think. Something like:

```golang
// logs timeout default is 30 minutes, the same as timeout in frontend logs query
// note: for alerting queries, the context will be cancelled before that unless evaluation_timeout_seconds in defaults.ini is increased (default: 30s)
const defaultLogsTimeout = 30 * time.Minute

type Duration struct {
	time.Duration
}

type CloudWatchSettings struct {
	awsds.AWSDatasourceSettings
	Namespace               string   `json:"customMetricsNamespaces"`
	SecureSocksProxyEnabled bool     `json:"enableSecureSocksProxy"` // this can be removed when https://github.com/grafana/grafana/issues/39089 is implemented
	LogsTimeout             Duration `json:"logsTimeout"`
}

func LoadCloudWatchSettings(config backend.DataSourceInstanceSettings) (CloudWatchSettings, error) {
	instance := CloudWatchSettings{LogsTimeout: Duration{defaultLogsTimeout}}
	if config.JSONData != nil && len(config.JSONData) > 1 {
		if err := json.Unmarshal(config.JSONData, &instance); err != nil {
			return CloudWatchSettings{}, fmt.Errorf("could not unmarshal DatasourceSettings json: %w", err)
		}
	}

	if instance.Region == "default" || instance.Region == "" {
		instance.Region = instance.DefaultRegion
	}

	if instance.Profile == "" {
		instance.Profile = config.Database
	}

	instance.AccessKey = config.DecryptedSecureJSONData["accessKey"]
	instance.SecretKey = config.DecryptedSecureJSONData["secretKey"]

	return instance, nil
}

func (d *Duration) UnmarshalJSON(b []byte) error {
	var logsTimeout interface{}
	if err := json.Unmarshal(b, &logsTimeout); err != nil {
		return err
	}

	switch value := logsTimeout.(type) {
	case float64:
		d.Duration = time.Duration(value)
	case string:
		var err error
		d.Duration, err = time.ParseDuration(value)
		if err != nil {
			d.Duration = defaultLogsTimeout
		}
	default:
		d.Duration = defaultLogsTimeout
	}

	return nil
}
```

File: pkg/tsdb/cloudwatch/models/settings_test.go [hunk 7]
```diff
@@ -71,4 +72,39 @@ func Test_Settings_LoadCloudWatchSettings(t *testing.T) {
...
+			DecryptedSecureJSONData: map[string]string{
+				"accessKey": "AKIAIOSFODNN7EXAMPLE",
+				"secretKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
+			},
+		}
+
+		s, err := LoadCloudWatchSettings(settings)
+		require.NoError(t, err)
+		assert.Equal(t, Duration(time.Minute * 10), s.LogsTimeout)
+	})
```
Comment (fridgepoet) [inline pkg/tsdb/cloudwatch/models/settings_test.go:109]: I would add all the possible test cases here to document our behavior and to enter all possible paths.
(Here's what I was using to test out my other comment to you setting the default in error cases if this is a good starting point)
```golang
func Test_LoadCloudWatchSettings_logsTimeout(t *testing.T) {
	t.Run("Should set logsTimeout to default duration if it is not defined", func(t *testing.T) {
		settings := backend.DataSourceInstanceSettings{
			ID: 33,
			JSONData: []byte(`{
			"authType": "arn",
			"assumeRoleArn": "arn:aws:iam::123456789012:role/grafana"
		  }`),
			DecryptedSecureJSONData: map[string]string{
				"accessKey": "AKIAIOSFODNN7EXAMPLE",
				"secretKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
			},
		}

		s, err := LoadCloudWatchSettings(settings)
		require.NoError(t, err)
		assert.Equal(t, 30*time.Minute, s.LogsTimeout.Duration)
	})
	t.Run("Should parse valid logsTimeout json field duration string", func(t *testing.T) {
		settings := backend.DataSourceInstanceSettings{
			ID: 33,
			JSONData: []byte(`{
			"authType": "arn",
			"assumeRoleArn": "arn:aws:iam::123456789012:role/grafana",
			"logsTimeout": "10m"
		  }`),
			DecryptedSecureJSONData: map[string]string{
				"accessKey": "AKIAIOSFODNN7EXAMPLE",
				"secretKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
			},
		}

		s, err := LoadCloudWatchSettings(settings)
		require.NoError(t, err)
		assert.Equal(t, 10*time.Minute, s.LogsTimeout.Duration)
	})

	t.Run("Should return default timeout for an invalid duration string", func(t *testing.T) {
		settings := backend.DataSourceInstanceSettings{
			ID: 33,
			JSONData: []byte(`{
			"authType": "arn",
			"assumeRoleArn": "arn:aws:iam::123456789012:role/grafana",
			"logsTimeout": "bad value"
		  }`),
			DecryptedSecureJSONData: map[string]string{
				"accessKey": "AKIAIOSFODNN7EXAMPLE",
				"secretKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
			},
		}

		s, err := LoadCloudWatchSettings(settings)
		require.NoError(t, err)
		assert.Equal(t, 30*time.Minute, s.LogsTimeout.Duration)
	})

	t.Run("Should return default timeout for logsTimeout json field of unexpected type", func(t *testing.T) {
		settings := backend.DataSourceInstanceSettings{
			ID: 33,
			JSONData: []byte(`{
			"authType": "arn",
			"assumeRoleArn": "arn:aws:iam::123456789012:role/grafana",
			"logsTimeout": true
		  }`),
			DecryptedSecureJSONData: map[string]string{
				"accessKey": "AKIAIOSFODNN7EXAMPLE",
				"secretKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
			},
		}

		s, err := LoadCloudWatchSettings(settings)
		require.NoError(t, err)
		assert.Equal(t, 30*time.Minute, s.LogsTimeout.Duration)
	})

	t.Run("Should correctly parse logsTimeout json field duration in nanoseconds", func(t *testing.T) {
		settings := backend.DataSourceInstanceSettings{
			ID: 33,
			JSONData: []byte(`{
			"authType": "arn",
			"assumeRoleArn": "arn:aws:iam::123456789012:role/grafana",
			"logsTimeout": 300000000
		  }`),
			DecryptedSecureJSONData: map[string]string{
				"accessKey": "AKIAIOSFODNN7EXAMPLE",
				"secretKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
			},
		}

		s, err := LoadCloudWatchSettings(settings)
		require.NoError(t, err)
		assert.Equal(t, 300*time.Millisecond, s.LogsTimeout.Duration)
	})
}
```
(I don't think we can actually reach the json unmarshal error case in our custom Unmarshaller... I don't think we can't write a test for it. This happens sometimes, but it's sort of like trying to test the `json` module in the standard library and I think there is no need since that is expected to be quite reliable already.)

File: pkg/tsdb/cloudwatch/models/settings_test.go [hunk 8]
```diff
@@ -71,4 +72,39 @@ func Test_Settings_LoadCloudWatchSettings(t *testing.T) {
 		assert.Equal(t, "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY", s.SecretKey)
 		assert.Equal(t, "AKIAIOSFODNN7EXAMPLE", s.AccessKey)
 	})
+	t.Run("Should set logsTimeout to default duration if it is not defined", func(t *testing.T) {
```
Comment (fridgepoet) [inline pkg/tsdb/cloudwatch/models/settings_test.go:75]: Not related to your changes, but the original tests could use a test covering the unmarshal json error case

```golang
t.Run("Should return error for invalid json", func(t *testing.T) {
		settings := backend.DataSourceInstanceSettings{
			ID: 33,
			JSONData: []byte(`{
			"authType": "arn",
			"assumeRoleArn": "arn:aws:iam::123456789012:role/grafana",
			"logsTimeout": fluffles
		  }`),
			DecryptedSecureJSONData: map[string]string{
				"accessKey": "AKIAIOSFODNN7EXAMPLE",
				"secretKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
			},
		}

		_, err := LoadCloudWatchSettings(settings)

		assert.Error(t, err)
	})
```

File: public/app/plugins/datasource/cloudwatch/components/ConfigEditor.tsx [hunk 9]
```diff
@@ -74,9 +74,9 @@ export const ConfigEditor = (props: Props) => {
       <h3 className="page-heading">CloudWatch Logs</h3>
       <div className="gf-form-group">
         <InlineField
-          label="Retry Timeout"
+          label="Query Result Timeout"
           labelWidth={28}
-          tooltip='Cloudwatch Logs allows for a maximum of 30 concurrent queries. If Grafana hits a concurrent max query error from Cloudwatch Logs it will auto-retry requesting a query for up to 30min. This retry timeout strategy is configurable. Must be a valid duration string, such as "15m" "30s" "2000ms" etc.'
+          tooltip='Grafana will poll for Cloudwatch Logs query results every second until Done status is returned from AWS or timeout is exceeded, in which case Grafana will return an error. The default period is 30 minutes. Note: For Alerting, the timeout defined in the config file will take precedence. Must be a valid duration string, such as "15m" "30s" "2000ms" etc.'
```
Comment (fridgepoet) [inline public/app/plugins/datasource/cloudwatch/components/ConfigEditor.tsx:79]: I guess it can be nanoseconds, too, since we support numbers but maybe we should not include that in the official recommendation in order to align with other similar fields in Grafana. What do you think?

File: pkg/tsdb/cloudwatch/log_sync_query.go [hunk 10]
```diff
@@ -82,7 +80,7 @@ var executeSyncLogQuery = func(ctx context.Context, e *cloudWatchExecutor, req *
 }
 
 func (e *cloudWatchExecutor) syncQuery(ctx context.Context, logsClient cloudwatchlogsiface.CloudWatchLogsAPI,
-	queryContext backend.DataQuery, logsQuery models.LogsQuery) (*cloudwatchlogs.GetQueryResultsOutput, error) {
+	queryContext backend.DataQuery, logsQuery models.LogsQuery, logsTimeout models.Duration) (*cloudwatchlogs.GetQueryResultsOutput, error) {
```
Comment (fridgepoet) [inline pkg/tsdb/cloudwatch/log_sync_query.go:83]: (Not a blocker at all: I think still I would use the `time.Duration` type here directly and convert time.Duration(instance.Settings.LogsTimeout) or use the time.Duration type of a models.Duration struct in order to avoid this models import.)

**Comment by fridgepoet** [comment]
Great Go code, these are purely functional questions/suggestions and not a remark on the Go code!

File: pkg/tsdb/cloudwatch/cloudwatch.go (hunk 3 above)
Comment (idastambuk) [reply pkg/tsdb/cloudwatch/cloudwatch.go]: I didn't know about 1! I will change it to struct to keep the methods in case we need them for later :) 

I'm not sure about 2. either. I put it where the other "defaults" for settings are, and maaaaybe I'd rather keep it there cause I feel like it's more visible there🤔

File: pkg/tsdb/cloudwatch/log_sync_query.go (hunk 6 above)
Comment (idastambuk) [reply pkg/tsdb/cloudwatch/log_sync_query.go:116]: Since the attempts happen every second, Im just converting attemptCount to time.Duration so I can multiply it with second. I guess I dont need the parentheses so `time.Duration(attemptCount) * time.Second >= time.Duration(logsTimeout)` is better

File: public/app/plugins/datasource/cloudwatch/components/ConfigEditor.tsx (hunk 9 above)
Comment (idastambuk) [reply public/app/plugins/datasource/cloudwatch/components/ConfigEditor.tsx:79]: Im ok keeping it like this too, I doubt nanosecond will be used anyway

File: pkg/tsdb/cloudwatch/cloudwatch.go (hunk 3 above)
Comment (fridgepoet) [reply pkg/tsdb/cloudwatch/cloudwatch.go]: Sounds good!

File: pkg/tsdb/cloudwatch/log_sync_query.go (hunk 6 above)
Comment (fridgepoet) [reply pkg/tsdb/cloudwatch/log_sync_query.go:116]: discussed with Ida, thanks for sharing this common gotcha with me https://stackoverflow.com/questions/17573190/how-to-multiply-duration-by-integer

**Review by fridgepoet — APPROVED** [review]
