### PR TITLE
Transformations: Fix bug in convert fields boolean to number

### LINKED ISSUE #60072: TablePanel/Transforms: Convert Field Type Transform Boolean=>Numeric breaks table panel
**What happened**:

Some (not all) Table Panels appear empty (doesnt show 'No Data')

**What you expected to happen**:

not empty?

**How to reproduce it (as minimally and precisely as possible)**:

Query results

**Anything else we need to know?**:

Worked in 9.2.1 and after upgrading to 9.3.1, some tables are empty. There is data when inspecting the table.

Error in Browser inspection:
Screenshot 2022-12-09 083013

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows Server 2019
- User OS & Browser: Chrome, Windows 11
- Grafana plugins: Table Panel
- Others:

### PR DESCRIPTION
**Pull request by bohandley**
Fixes https://github.com/grafana/grafana/issues/60072

A bug was introduced into the Convert Fields transformation recently. Booleans were not being converted to numbers. A request had been made to convert strings with commas to numbers, which used a replace regex function, removing commas before coercing the string, and that broke the conversion of booleans to numbers. To fix this, we now only remove commas from strings, everything else we coerce.

### CODE REVIEW

**Review by mckn — APPROVED** [review]
LGTM!

File: packages/grafana-data/src/transformations/transformers/convertFieldType.ts [hunk 1]
```diff
@@ -142,9 +142,16 @@ function fieldToNumberField(field: Field): Field {
   const numValues = field.values.toArray().slice();
 
   for (let n = 0; n < numValues.length; n++) {
-    // some numbers returned from datasources have commas
-    // strip the commas, coerce the string to a number
-    const number = +numValues[n].replace(/,/g, '');
+    let toBeConverted = numValues[n];
+
+    if (typeof toBeConverted === 'string') {
+      // some numbers returned from datasources have commas
```
Comment (leeoniya) [inline packages/grafana-data/src/transformations/transformers/convertFieldType.ts:148]: feels like this can be outside this hot loop. isnt this uniform/known for the whole array?

Comment (bohandley) [reply packages/grafana-data/src/transformations/transformers/convertFieldType.ts:148]: Good point! As far as I know, the array should be consistent. I can do the check on the array

Comment (bohandley) [reply packages/grafana-data/src/transformations/transformers/convertFieldType.ts:148]: I can check `field.type === 'string'` or I can check `field.some(v => typeof v === 'string')`

Is there somewhere in the code that all dataframe fields are checked for a type? Is this consistent across all datasources? I'm leaning towards the `some` check.

Comment (leeoniya) [reply packages/grafana-data/src/transformations/transformers/convertFieldType.ts:150]: :+1:
