### PR TITLE
A11y: Fix screen reader announcements for checkboxes in notification history page

### LINKED ISSUE #117838: A11y: Notification History checkbox does not expose name, role, or state to screen readers
## Description

The checkbox on the Notification History page does not announce its name, role, or state (checked/unchecked) when focused. The checkbox uses `tabindex="-1"`, which removes it from the tab order, and its `<label>` wrapper does not provide an accessible name. Screen reader users cannot identify the control or interact with it meaningfully.

## Steps to reproduce

1. Open Grafana in Chrome on Windows
2. Enable JAWS screen reader
3. Navigate to the Notification History page
4. Use Tab to navigate to the checkbox before an error entry
5. Listen to the screen reader announcement

## Actual behavior

The screen reader does not announce the name, role (checkbox), or state (checked/unchecked) of the control.

## Expected behavior

The checkbox should announce its name (e.g., "Select Error"), role ("checkbox"), and state ("checked" or "unchecked") to screen readers.

## Suggested fix

Remove `tabindex="-1"` so the checkbox is focusable, and provide an accessible name via `aria-label` or a visible `<label>` with associated text:

```html
<label>
  <input type="checkbox" aria-label="Select notification" />
  <span class="css-11ty15i"></span>
</label>
```

Reference: [WAI Tutorials: Form Labels](https://www.w3.org/WAI/tutorials/forms/labels/)

## WCAG criteria

- **4.1.2 Name, Role, Value** (Level A)

## Possible duplicates in grafana/grafana

No exact duplicates found. The Notification History checkbox issue appears to be unique.

## Issue reference

Reference issue 15

### PR DESCRIPTION
**Pull request by L-M-K-B**
**What is this feature?**

Fixes screen reader accessibility for the notification history page (`/profile/notifications`). Adds aria-labels to checkboxes and removes the duplicate interactive element that caused each notification to be announced twice.

**Who is this feature for?**

Users who rely on screen readers or other assistive technologies.

**Which issue(s) does this PR fix?**:

Fixes #117838

**Special notes for your reviewer:**
Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/core/components/AppNotifications/StoredNotificationItem.tsx [hunk 1]
```diff
@@ -32,11 +33,15 @@ export const StoredNotificationItem = ({
   const styles = getStyles(theme);
 
   return (
-    <Card noMargin className={className} onClick={onClick}>
```
Comment (ywzheng1) [inline public/app/core/components/AppNotifications/StoredNotificationItem.tsx:35]: The original `<Card onClick={onClick}>` meant users could click anywhere on the card to select it. Removing it leaves only the checkbox clickable, is this intentional?

Comment (L-M-K-B) [reply public/app/core/components/AppNotifications/StoredNotificationItem.tsx:35]: Yes, it is intentional to clean up for keyboard navigation and screenreader use. 
Before there was the checkbox and the title + description together were a button. When navigating with a keyboard users had to navigate to the button (title + description) first and then to the checkbox which is the wrong order and confusing. Additionally every item in the list got announced twice by the screenreader. First as a button then as a checkbox. When clicking users were toggling the same checkbox with both elements.

**Review by ywzheng1 — APPROVED** [review]
