### PR TITLE
Accessibility: Colorblind safe color palette for visualizations

### LINKED ISSUE #21120: Legal Requirement: Denotative colour coding for Colourblind Users
Those who have any difficulties distinguishing colour currently find Grafana difficult to use; when all colours look the same, there is no way to distinguish different series. Grafana should be designed for those who have [Monochromacy](https://en.wikipedia.org/wiki/Monochromacy), so that it is accessible to everyone.

**Steps to reproduce**:
All graphs use colour alone to distinguish information.

**Actual Result**:
All graphs use colour alone to distinguish information.

**Expected Result**
Color should not be used as the only visual means of conveying information. Graphs should include patterns _and_ colours to better enable all users to distinguish information.

This example is taken from [Trello](https://trello.com/). While Trello is an entirely separate entity, Trello cards can be categorised using patterns _and_ colours.
image

**Relevant WCAG Criteria:**

- [Use of Color](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#use-of-color): "_Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element._"
- [Colourblind Awareness in Business](http://www.colourblindawareness.org/business/)
- Many countries have legal accessibility requirements. The [UK Health and Safety
Executive](https://www.hse.gov.uk/pubns/web03.pdf), for example, requires that Connotative colour coding is redesigned to Denotative colour coding.

Grafana currently contravenes these.

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: mysql Ver 14.14
- User OS & Browser: Ubuntu & FireFox, Windows & Chrome

**Relates to:**
This issue is related to the following, though they do not go far enough for full colourblind accessibility.
- [13014](https://github.com/grafana/grafana/issues/13014)
- [18041](https://github.com/grafana/grafana/issues/18041)

### PR DESCRIPTION
**Pull request by vijaygovindaraja**
## What

Add a discrete colorblind-safe color palette as a new color scheme option, allowing users with color vision deficiency to distinguish series in charts.

## Why

Grafana currently relies on color alone to differentiate series in visualizations. For users with color blindness (~8% of males, ~0.5% of females), many series become indistinguishable. This is both an accessibility barrier and a legal requirement in many jurisdictions (WCAG 1.4.1, Section 508). This issue has been open for 6+ years with 14 comments.

## Implementation

Based on Wong (2011) "Points of view: Color blindness" (Nature Methods 8:441), extended with Tol qualitative colors. The 16 colors are validated to be distinguishable under protanopia, deuteranopia, and tritanopia.

### Color palette
| Color | Hex | Source |
|-------|-----|--------|
| Blue | `#0072B2` | Wong |
| Orange | `#E69F00` | Wong |
| Bluish green | `#009E73` | Wong |
| Reddish purple | `#CC79A7` | Wong |
| Sky blue | `#56B4E9` | Wong |
| Vermilion | `#D55E00` | Wong |
| Yellow | `#F0E442` | Wong |
| Black | `#000000` | Wong |
| + 8 extended | various | Tol qualitative |

### Files changed
| File | Change |
|------|--------|
| `types/fieldColor.ts` | Add `PaletteColorblind` enum value |
| `themes/createVisualizationColors.ts` | Add `getColorblindPalette()` function |
| `field/fieldColor.ts` | Register in `fieldColorModeRegistry` under "Accessible" group |

### Usage
Panel field config → Color scheme → Accessible → **"Colorblind safe"**

This sits alongside existing accessible continuous schemes (Viridis, Cividis, etc.) but is the first **discrete** accessible palette — suitable for categorical data and multi-series time series.

Fixes #21120

### CODE REVIEW

**Comment by jamesgeddes** [comment]
@vijaygovindaraja this sounds like a fantastic change. Are you able to include a screenshot too, please? 

Also, does this add patterns to further distinguish series?

File: packages/grafana-data/src/field/fieldColor.ts [hunk 1]
```diff
@@ -88,6 +89,16 @@ export const fieldColorModeRegistry = new Registry<FieldColorMode>(() => {
...
       },
     }),
+    new FieldColorSchemeMode({
+      id: FieldColorModeId.PaletteColorblind,
+      name: 'Colorblind safe',
+      isContinuous: false,
+      isByValue: false,
+      getColors: () => {
+        return getColorblindPalette();
+      },
```
Comment (gtk-grafana) [inline packages/grafana-data/src/field/fieldColor.ts]: Since these colors are not currently aware of their background from the theme, let's filter out the ones that do not have enough contrast

```suggestion
 getColors: (theme: GrafanaTheme2) => {
        return getColorblindPalette().filter(
          (color) =>
            getContrastRatio(theme.visualization.getColorByName(color), theme.colors.background.primary) >=
            theme.colors.contrastThreshold
        );
      },
```

File: packages/grafana-data/src/themes/createVisualizationColors.ts [hunk 2]
```diff
@@ -344,6 +344,33 @@ function getClassicPalette() {
...
+export function getColorblindPalette(): string[] {
+  return [
+    '#0072B2', // blue
+    '#E69F00', // orange
+    '#009E73', // bluish green
+    '#CC79A7', // reddish purple
+    '#56B4E9', // sky blue
+    '#D55E00', // vermilion
+    '#F0E442', // yellow
+    '#000000', // black
```
Comment (gtk-grafana) [inline packages/grafana-data/src/themes/createVisualizationColors.ts]: After filtering out low contrast colors in `packages/grafana-data/src/field/fieldColor.ts`, we probably want to add white which should be visually distinct from the other colors, but can still be used in themes with dark backgrounds. 

```suggestion
    '#000000', // black
    '#FFFFFF', // white
```

Comment (gtk-grafana) [reply packages/grafana-data/src/themes/createVisualizationColors.ts]: Image

Image

File: docs/sources/visualizations/panels-visualizations/configure-standard-options/index.md [hunk 3]
```diff
@@ -266,6 +266,7 @@
...
 | Classic palette (by series name)      | Grafana automatically assigns colors based on the name of the series. Useful when the series names to be visualized can change based on the available data.                                                                                                                                                                                                                                                 |
+| Colorblind safe                       | A discrete palette of 17 colors based on Wong (2011) and Tol qualitative research, validated to be distinguishable under protanopia, deuteranopia, and tritanopia. Colors with insufficient contrast against the current theme background are automatically filtered out. Located in the **Accessible** group in the color scheme selector.                                                                  |
```
[the remark this answers is not in the document]
Comment (gtk-grafana) [reply docs/sources/visualizations/panels-visualizations/configure-standard-options/index.md]: A touch verbose for the context, but otherwise really good, can we shorten this up a bit to something like: 

```suggestion
| Colorblind safe                       | A palette validated to be distinguishable by users with protanopia, deuteranopia, and tritanopia. Located in the **Accessible** group in the color scheme selector.                                                                  |
```

File: docs/sources/visualizations/panels-visualizations/configure-standard-options/index.md [hunk 4]
```diff
@@ -266,6 +266,7 @@ Select one of the following schemes:
...
 | Classic palette                       | Grafana automatically assigns a color for each field or series based on its order. If the order of a field changes in your query, the color also changes. Useful for graphs, pie charts, and other categorical data visualizations.                                                                                                                                                                         |
 | Classic palette (by series name)      | Grafana automatically assigns colors based on the name of the series. Useful when the series names to be visualized can change based on the available data.                                                                                                                                                                                                                                                 |
+| Colorblind safe                       | A palette validated to be distinguishable by users with protanopia, deuteranopia, and tritanopia. Located in the **Accessible** group in the color scheme selector.                                                                  |
```
Comment (imatwawana) [inline docs/sources/visualizations/panels-visualizations/configure-standard-options/index.md]:
```suggestion
| Color blind safe                       | A palette validated to be distinguishable by users with protanopia, deuteranopia, and tritanopia. Located in the **Accessible** group in the color scheme selector.                                                                  |
| Multiple accessible continuous colors (by value) | Grafana automatically assigns colors based on the percentage of a value relative to the min and the max of the field or series. For some visualizations, you also need to choose if the color is set by the **Last**, **Min**, or **Max** value of the field or series. Select from: **Viridis**, **Magma**, **Plasma**, **Inferno**, **Cividis**, and **Yellow-Blue**. Located in the **Accessible** group in the color scheme selector. |
```

File: packages/grafana-data/src/field/fieldColor.ts [hunk 5]
```diff
@@ -22,6 +22,31 @@ import { Registry, type RegistryItem } from '../utils/Registry';
 import { getScaleCalculator, type ColorScaleValue } from './scale';
 import { fallBackThreshold } from './thresholds';
 
+/**
+ * Colorblind-safe palette based on Wong (2011) "Points of view: Color blindness"
```
Comment (imatwawana) [inline packages/grafana-data/src/field/fieldColor.ts]:
```suggestion
 * Color blind-safe palette based on Wong (2011) "Points of view: Color blindness"
```

File: packages/grafana-data/src/themes/createVisualizationColors.ts [hunk 6]
```diff
@@ -344,6 +344,34 @@ function getClassicPalette() {
   ];
 }
 
+/**
+ * Colorblind-safe palette based on Wong (2011) "Points of view: Color blindness"
```
Comment (imatwawana) [inline packages/grafana-data/src/themes/createVisualizationColors.ts]:
```suggestion
 * Color blind-safe palette based on Wong (2011) "Points of view: Color blindness"
```

File: packages/grafana-data/src/field/fieldColor.ts [hunk 7]
```diff
@@ -88,6 +113,20 @@ export const fieldColorModeRegistry = new Registry<FieldColorMode>(() => {
         );
       },
     }),
+    new FieldColorSchemeMode({
+      id: FieldColorModeId.PaletteColorblind,
+      name: 'Colorblind safe',
```
Comment (imatwawana) [inline packages/grafana-data/src/field/fieldColor.ts]: I'm not sure which file/s this needs to be updated in, but "Colour blind" should be two words in the UI.
```suggestion
      name: 'Color blind safe',
```

**Review by imatwawana — COMMENTED** [review]
Made changes to include the other schemes included in this change and fix spelling of "color blind".

**Comment by gtk-grafana** [comment]
Yeah make that change and I'll discuss with dataviz. It's looking like this might have to wait until 13.1 but I'll try to let you know before EOD.

Also there's a few linting errors in CI you might want to clean up while you're at it

**Comment by vijaygovindaraja** [comment]
@gtk-grafana trimmed to wong-only (removed all tol colors) and gated behind enableColorblindSafePanelOptions. rebased on main with the feature toggle.

File: docs/sources/visualizations/panels-visualizations/configure-standard-options/index.md [hunk 8]
```diff
@@ -259,15 +259,17 @@ The color options and their effect on a visualization depend on the visualizatio
...
-| Single continuous color (by value)    | Grafana automatically assigns shades of one color based on the percentage of a value relative to the min and the max of the field or series. For some visualizations, you also need to choose if the color is set by the **Last**, **Min**, or **Max** value of the field or series. Select from: **Blues**, **Reds**, **Greens**, and **Purples**.                                                         |
+| Color scheme                                     | Description                                                                                                                                                                                                                                                                                                                                                                                                                               |
```
Comment (gtk-grafana) [inline docs/sources/visualizations/panels-visualizations/configure-standard-options/index.md]: revert all docs changes, we'll add them back after public preview

File: public/app/core/components/OptionsUI/fieldColor.tsx [hunk 9]
```diff
@@ -29,7 +30,9 @@ export const FieldColorEditor = ({ value, onChange, item, id }: Props) => {
     ? fieldColorModeRegistry.list()
     : fieldColorModeRegistry.list().filter((m) => !m.isByValue);
 
-  const filteredOptions = availableOptions.filter((option) => !option.excludeFromPicker);
+  const filteredOptions = availableOptions
+    .filter((option) => !option.excludeFromPicker)
```
Comment (gtk-grafana) [inline public/app/core/components/OptionsUI/fieldColor.tsx]: let's combine these filters so we don't iterate through the options twice

Comment (vijaygovindaraja) [reply public/app/core/components/OptionsUI/fieldColor.tsx]: done, combined into a single filter.

File: docs/sources/visualizations/panels-visualizations/configure-standard-options/index.md (hunk 8 above)
Comment (vijaygovindaraja) [reply docs/sources/visualizations/panels-visualizations/configure-standard-options/index.md]: reverted, will add docs back after public preview.

File: packages/grafana-data/src/field/fieldColor.ts [hunk 10]
```diff
@@ -22,6 +22,24 @@ import { Registry, type RegistryItem } from '../utils/Registry';
...
+  '#0072B2',
+  '#E69F00',
+  '#009E73',
+  '#CC79A7',
+  '#56B4E9',
+  '#D55E00',
+  '#F0E442',
+  '#000000',
+  '#FFFFFF',
+];
```
Comment (fastfrwrd) [inline packages/grafana-data/src/field/fieldColor.ts:41]: note: I think this isn't necessarily the spot for this array, but we can move it around after merging.

File: packages/grafana-data/src/types/fieldColor.ts [hunk 11]
```diff
@@ -6,6 +6,7 @@ export enum FieldColorModeId {
   PaletteClassic = 'palette-classic',
   PaletteClassicByName = 'palette-classic-by-name',
   PaletteSaturated = 'palette-saturated',
+  PaletteColorblind = 'palette-colorblind',
```
Comment (fastfrwrd) [inline packages/grafana-data/src/types/fieldColor.ts:13]: this is the one change that _can't_ be flagged that eventually could cause us problems, the addition of the type that we would consider breaking in the future if we were to remove it/rename it. _(we would only remove it as part of moving towards some other solution for color blind support in the coming months)_. the simplest thing to do here is mark as alpha and add a note that we may change or remove this.

 
```suggestion
  /**
   * @alpha - the color blind safe palette is experimental and may be removed or changed 
   * as we work towards a GA of improved color blind support.
   */
  PaletteColorblind = 'palette-colorblind',
```

**Review by fastfrwrd — APPROVED** [review]
Moving forward with this and getting the flag enabled in our test environments is the first step to getting feedback and moving us in a better direction w/r/t how we build a product that works for color blind Grafana users. It may change a lot before it GAs, but: progress over perfection, let's get it moving forward!

**Review by gtk-grafana — APPROVED** [review]
@vijaygovindaraja Looks great to me, works well locally.
Thanks again for all of your hard work on this!
