### PR TITLE
Panel: Apply option defaults on panel init and on save model retrieval

### LINKED ISSUE #17154: Bar gauge min,max input is overly "helpful"
**What happened**:

When trying to input min, max values in a Bar Gauge the UI tries to be helpful. Unfortunately it makes it a nightmare to input certain things like negative numbers or change the leading number of tens, hundreds, thousands etc.

**What you expected to happen**:

The UI shouldn't be overly prescriptive or clever about how I input numbers.

**How to reproduce it (as minimally and precisely as possible)**:

* Try inputting a negative number. You can't, unless you put in a number greater than 0 first and then prepend the `-` sign. Numbers can be negative, for example temperature. The only other way to input negative numbers is to use the arrow down key to go below zero
* Input 100 first, change your mind, should be 200. Remove the 1 to replace it with a 2 and poof it's 0 now 0 if you tried this in the min field or 100 if you tried it in the max field
* Try backspacing into the `max` field with it's default of 100. I want to enter 30 instead. So backspace backspace backspace to wipe 100 and poof it's 100 again. I can't enter the number 30 without selecting the contents of the field with the mouse and overriding it b/c the UI won't tolerate the entry being empty for a millisecond

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.0-beta2
- Data source type & version: Prometheus 2.9.2
- OS Grafana is installed on: Ubuntu 18.04 (Docker)
- User OS & Browser: Arch Linux, Firefox 68.0a1
- Grafana plugins: Cloudflare, World map, Alertmanager data source
- Others:

### PR DESCRIPTION
**Pull request by dprokop**
Fixes #17154

This PR changes the way panel option defaults are applied. Until now the defaults were applied in `PanelModel.getOptions` method. This was performed using `defaultsDeep` Lodash function, which applies defaults for options that are `undefined`. In our case, where options model is updated on key down, it ended up in situation, where user couldn't erase the input field.

TODO: 
- [x] Update tests
- [x] Don't remove leading zeros when editing numeric options

### CODE REVIEW

**Comment by ryantxu** [comment]
Looks good -- thanks

File: public/app/features/dashboard/state/PanelModel.ts [hunk 1]
```diff
@@ -247,8 +250,20 @@ export class PanelModel {
...
   pluginLoaded(plugin: PanelPlugin) {
     this.plugin = plugin;
+    const hasPersistedOptions = !!this.options;
+    const defaultOptions = plugin.defaults;
+
+    if (hasPersistedOptions) {
+      this.applyPluginOptionDefaults(this.plugin);
+    } else {
+      this.options = _.defaultsDeep({}, defaultOptions);
+    }
```
Comment (torkelo) [inline public/app/features/dashboard/state/PanelModel.ts]: not sure I understand this if statement, cant it be replaced with 
this.options =  _.defaultsDeep({}, this.options || {}, plugin.defaults);

And I think this needs a if (!this.plugin.angularPanelCtrl) or some check so that it only happens on react panels

**Review by torkelo — APPROVED** [review]
Look good!
