### PR TITLE
Folders: Removes the possibility to delete the General folder

### LINKED ISSUE #29880: Deleting "General" folder causing empty grafana state
**What happened**:
Moved all dashboards into custom folder and deleted "General" folder. 
After refresh I see empty list: 
image

**What you expected to happen**:
In case General is default and mandatory folder:
- I expect to see disabled delete button 
- or notification about my deletion aborted
- or popup to define new default folder.   
In case General is ordinary folder: 
- Correct deletion and remained folders with all created dashboards. 

**How to reproduce it (as minimally and precisely as possible)**:
general_deleted

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.3.5 (11f305f88a) and  v7.0.3 (00ee734baf)
- Data source type & version:  
- OS Grafana is installed on: Mint 20.10 (with docker container) and CentOS (with docker container)
- User OS & Browser: Firefox 83.0 (64-bit)
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR prevents the Delete button to appear when checking only the `General` folder for deletion, because that leads to a confusing state as described in #29880.

We could also make it so whenever you select folders for deletion, including the `General` folder, the Delete button will not be available. Not sure this is a good user experience, though. Please let me know if I should include this as well.

Enjoy the review 🎉 

**Which issue(s) this PR fixes**:
Fixes #29880

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/search/hooks/useManageDashboards.ts [hunk 1]
```diff
@@ -6,6 +6,8 @@ import { DELETE_ITEMS, MOVE_ITEMS, TOGGLE_ALL_CHECKED, TOGGLE_CHECKED } from '..
 import { manageDashboardsReducer, manageDashboardsState, ManageDashboardsState } from '../reducers/manageDashboards';
 import { useSearch } from './useSearch';
 
+export const GENERAL_FOLDER_ID = 0;
```
Comment (Clarity-89) [inline public/app/features/search/hooks/useManageDashboards.ts:9]: There's also `constants` file in the search folder where this could be stored.

**Review by Clarity-89 — APPROVED** [review]
Looks good to me! Also great job with adding tests for the hook 🎉

File: public/app/features/search/hooks/useManageDashboards.ts (hunk 1 above)
Comment (hugohaggmark) [reply public/app/features/search/hooks/useManageDashboards.ts:9]: Brilliant suggestion, will move it there right away!
