### PR TITLE
Explore: Expand table height to show sub-tables

### LINKED ISSUE #59839: TraceQL: Low number of results gets cut off when expanding
**What happened**:
When executing a TraceQL query that returns a low number of results the table does not resize properly when expanding a result. 

**What you expected to happen**:
The results table should increase its height to contain all results.

**How to reproduce it (as minimally and precisely as possible)**:
- Execute a TraceQL query and set the limit to 1. This will artificially constrain the results to a low number which will help repro the issue:
image
- Click the > symbol on the left to drop down a trace result. This should show the returned spans from Tempo:
image
- Note that the table does not increase in height and the results are cut off.

**Environment**:
- Grafana version: Grafana v9.4.0-44473pre (7deaeb0f9e)
- Data source type & version: Tempo
- OS Grafana is installed on: Linux/Docker
- User OS & Browser: Chrome

### PR DESCRIPTION
**Pull request by adrapereira**
**What is this feature?**

We use the number of rows in a dataframe to define the height of the table. In cases where the table contains sub-tables this can be an issue when the user expands a sub-table and there isn't enough room to reasonably show its content. 

This PR looks at the expanded rows and checks if there's enough height to reasonably show most of the sub-tables content, increasing the height if there isn't space. To prevent the table from growing forever it also adds a new optional prop to set the `maxHeight` of the table. 

Before this change:

https://user-images.githubusercontent.com/4313971/207715023-14380e10-a29a-453c-aa2a-b1c5a1bf77ed.mov

With this PR:

https://user-images.githubusercontent.com/4313971/207713993-6f24e80d-d7ce-4089-954b-ae1bef4677f7.mov

Please confirm whether it makes sense to have the table's height be dynamic, if not, I would be interested in discussing alternatives that would fix the issue linked in this PR.

**Which issue(s) does this PR fix?**:

Fixes #59839

### CODE REVIEW

**Comment by Elfo404** [comment]
@radiorental can you have a look at this?

**Comment by radiorental** [comment]
Looks good, I would be curious to see the behaviour when the expanded section is taller than the viewport.  I.e. what's the scrollbar interaction, do you keep the table header stickied so the user has context and easy access to the collapse action?

**Comment by Elfo404** [comment]
on the explore side looks good, letting @grafana/grafana-bi-squad approve it as they own the table panel

File: public/app/features/explore/TableContainer.tsx [hunk 1]
```diff
@@ -99,6 +99,7 @@ export class TableContainer extends PureComponent<Props> {
             subData={subFrames}
             width={tableWidth}
             height={height}
+            maxHeight={600}
```
Comment (aocenas) [inline public/app/features/explore/TableContainer.tsx:102]: Feels weird to have both height and maxHeight here. What is the interaction between those two?

Comment (aocenas) [reply public/app/features/explore/TableContainer.tsx:102]: I mean I am not sure how these should be used. Like if I set height = 500 does it mean it will be 500 unexpanded but if some row expands it will grow without limit? And if maxHeight = 600 it will grow only to 600? What if height > maxHeight? So one thing, I assume we don't really need the maxHeight for explore. The other thing is I wonder if there is a better way to express this cause to me it's a bit confusing.

Like here I would sort off expect something more automatic that `if height <= 3 * headerHeight && subRows === true then heigh += 200` or something like that, basically having a minHeight instead of maxHeight I guess.

Because I feel like there are 2 general cases:
1. you have some container and you need to fit into it like a dashboard panel so you don't want to expand on subRows anyway.
2. you don't have the container and you can expand (like explore) but I don't think in that case you care much about maxHeight (assuming whole page will just scroll)

So maybe even just having `expandable: boolean` property would make sense to me for this.

Comment (aocenas) [reply public/app/features/explore/TableContainer.tsx:102]: I think the main reason for having set height is the case when you have footer in the table. Then you cannot leave the scroll on the container and you have to set the height of the table to be equal to container otherwise you would not see the footer unless you scroll all the way down. Which I assume we don't want?

I would assume somebody from @grafana/grafana-bi-squad should also chime in on this.

**Comment by codeincarnate** [comment]
@adrapereira I should be able to take a look today 😄

**Comment by codeincarnate** [comment]
Before I forget did want to note that this will probably need to be taken into account for #60787

File: packages/grafana-ui/src/components/Table/Table.tsx [hunk 2]
```diff
@@ -189,6 +190,18 @@ export const Table = memo((props: Props) => {
 
   const pageSize = Math.round(listHeight / tableStyles.rowHeight) - 1;
 
+  // Make sure we have room to show the sub-table
+  const expandedIndices = Object.keys(extendedState.expanded);
+  if (expandedIndices.length) {
+    const subTablesHeight = expandedIndices.reduce((sum, index) => {
+      const subLength = subData?.find((frame) => frame.meta?.custom?.parentRowIndex === parseInt(index, 10))?.length;
```
Comment (codeincarnate) [inline packages/grafana-ui/src/components/Table/Table.tsx:197]: I'm a bit surprised this isn't an integer comparison. Am I missing something?

File: public/app/features/explore/TableContainer.tsx (hunk 1 above)
Comment (codeincarnate) [reply public/app/features/explore/TableContainer.tsx:102]: Including `maxHeight` for footer display makes sense to me. I'm not sure if in every scenario we would be able to rely on container sizing to constrain the table. I think as long as it's kept limited it's not a bad idea.

I'm not sure about the `expandable` flag as it seems like having sub-rows implies the ability to expand the table as well. The same could be accomplished by setting the `maxHeight` to whatever the initial height is.

**Review by codeincarnate — APPROVED** [review]
Looks good to me overall. Would appreciate input on the comments though. And per other reviews we'll probably need to work out a strategy for viewport overflows.

File: packages/grafana-ui/src/components/Table/Table.tsx (hunk 2 above)
Comment (codeincarnate) [reply packages/grafana-ui/src/components/Table/Table.tsx:197]: Hey Andre, yes that's correct. Didn't realize the internal react table state used a string index so no worries there!
