### PR TITLE
Transformations: Fix Timeseries to table transformation trend reduction when result is 0

### LINKED ISSUE #78025: SparklineCell: No value shown when calculated trend value is 0
### What happened?

I am using Timeseries to table transformation along sparkline cell to show timeseries in a table. When the trend value for a timeseries has a value of 0, no trend value is shown in sparkline cell. 

### What did you expect to happen?

- When a trend timeseries ends with 0 and i choose "Last" or "Last *" aggregation, I expect the panel to show a 0 at the left of the timeseries in the sparkline cell.
- When a trend timeseries has all 0s, I expect "Last", "Last *" or "Mean" aggregation to show a 0 at the left of the timeseries in the sparkline cell.

### Did this work before?

No

### How do we reproduce it?

1. Generate 3 queries with test data:
1 query

2. Change visualization to Table and apply the Timeseries to table transform:
- For the ends_zero, using "Last *" reduction:
2 ends_zero
- For the ends_nonzero, using "Last *" reduction:
3 ends_nonzero
- For the all_zero, using "Mean" reduction (same result using "Last *" reduction):
3 all_zero

- For the ends_zero, a 0 should be displayed (as it is the last value), but no value is shown.
- For the ends_nonzero, a 6 should be displayed in the sparkline cell, and indeed, a 6 is shown.
- For the all_zero, a 0 should be displayed (as it is the mean), but no value is shown.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 10.3.0-pre commit=e9e7e0b628 branch=main
OS: Fedora 38
Browser: Google Chrome 117.0.5938.132

### Grafana platform?

Other

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by oserde**
When reduceField function returns 0, the reduced value is set to null. I think we can remove this "|| null" statement, as:
- There is a check a few lines above to make sure the field type is a number. This might be a reasonable guarantee that the calculation we are doing will make sense and there will be no need to set to null.
- Sparkline cell type already has an option to hide value if we believe the calculation does not make sense.

Fixes #78025

### CODE REVIEW

File: public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.ts [hunk 1]
```diff
@@ -172,7 +172,7 @@ export function timeSeriesToTableTransform(options: TimeSeriesTableTransformerOp
         // and push the frame with reduction
         // into the the appropriate field
         const reducerId = options[refId]?.stat ?? ReducerID.lastNotNull;
-        const value = reduceField({ field, reducers: [reducerId] })[reducerId] || null;
```
Comment (oscarkilhed) [inline public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.ts:175]: You're correct in that this check should not be `|| null`. But looking at the implementation of `reduceField` it seems to return undefined if the field has no values and [`reducer.emptyInputResult`](https://github.com/grafana/grafana/blob/b607a4e0a2ee2a9b368c6ebcf4021249768b347e/packages/grafana-data/src/transformations/fieldReducer.ts#L90C19-L90C19) is undefined. It could be that the check in reduceField is wrong, and it should really check if emptyInputResult is undefined.

In any case, I think the change here should be to check if the FieldCalc here is `undefined`. Adding a test with a field that has no values would also be a good idea.

**Review by oscarkilhed — CHANGES_REQUESTED** [review]
Thank you for your submission!

**Review by oscarkilhed — APPROVED** [review]

**Comment by oscarkilhed** [comment]
Went ahead and updated the PR with my suggested changes.

**Review by baldm0mma — APPROVED** [review]
lgtm!

**Review by mdvictor — APPROVED** [review]
