### PR TITLE
Dashboard: Library Panels - Add ability to search by folder name

### LINKED ISSUE #62865: Can't filter library panels by folder name when adding to dash
**What happened**:

- Create a folder in a Grafana instance (whose name is my name)
- Save a library panel into that new folder (in an instance where other library-panels have also been saved)
- Now create a new dashboard, click **add panel** then **add panel from the panel library**
- Try to filter to the panel I just saved by filtering just on the folder-name alone. This doesn't work. In order to find my panel in the big list I either have to scroll through a huge list, or go to `/library-panels`, filter to my folder there, and remind myself of the panel name, in order to use that to filter

**What you expected to happen**:
- Be able to filter library-panels by folder when adding them to dashboards

**How to reproduce it (as minimally and precisely as possible)**:
As above

**Anything else we need to know?**:
image (7)

**Environment**:
- Grafana version: Grafana | 9.4.0-52188pre (3c01ae2c9e) // Enterprise
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: MacOS, Chrome, in Feb 2023

### PR DESCRIPTION
**Pull request by axelavargas**
**What is this feature?**

Enables searching library panels by folder name besides panel name and description. Users can now type a folder name to find all panels contained within that folder.

**Why do we need this feature?**

Currently, users can only search library panels by panel name or description. When users remember which folder contains the panel they need but not the specific panel name, they have to manually browse through folders to find it. 

This is not very user friendly, especially with orgs having a lot of library panels

**Who is this feature for?**

Everyone that uses the library panels search widget

For Admins

https://github.com/user-attachments/assets/36e60eb4-3d98-46e2-8fd9-39d67cd4fa5d

For Viewers with limited access to folders

https://github.com/user-attachments/assets/b8ab7755-7e7d-4d87-9679-d04c6ce6ce47

**Which issue(s) does this PR fix?**:

Fixes #62865

**Special notes for your reviewer:**

My Go coding skills are rough 😬. I did my best to consider security aspects, such as preventing users from accessing folders they shouldn't have access to, and implemented the logic by following patterns similar to those I saw in the library panels code.

Please check that:
- [x] It works as expected from a user's perspective.
- [x] It follows Grafana go patterns
- [x] It's secure

Tasks:
- [x] Implement logic that adds that support
- [x] Add unit tests

### CODE REVIEW

File: pkg/services/libraryelements/database.go [hunk 1]
```diff
@@ -441,15 +441,29 @@ func (l *LibraryElementService) getAllLibraryElements(c context.Context, signedI
 	if folderFilter.parseError != nil {
 		return model.LibraryElementSearchResult{}, folderFilter.parseError
 	}
+
+	// Get accessible folder UIDs for secure folder name search
+	fs, err := l.folderService.GetFolders(c, folder.GetFoldersQuery{OrgID: signedInUser.GetOrgID(), SignedInUser: signedInUser})
```
Comment (evictorero) [inline pkg/services/libraryelements/database.go]: Instead of using the `folderService.GetFolders` service and filtering later by title using a JOIN we could use a different service and search directly by title and permissions. Did you take a look at the `folderService.SearchFolders` ?

File: pkg/services/libraryelements/database.go [hunk 2]
```diff
@@ -441,15 +441,29 @@ func (l *LibraryElementService) getAllLibraryElements(c context.Context, signedI
...
+		accessibleFolderUIDs = append(accessibleFolderUIDs, f.UID)
+	}
+
 	err = l.SQLStore.WithDbSession(c, func(session *db.Session) error {
 		builder := db.NewSqlBuilder(l.Cfg, l.features, l.SQLStore.GetDialect(), recursiveQueriesAreSupported)
 		if folderFilter.includeGeneralFolder {
 			builder.Write(selectLibraryElementDTOWithMeta)
 			builder.Write(", '' as folder_uid ")
 			builder.Write(getFromLibraryElementDTOWithMeta(l.SQLStore.GetDialect()))
+			builder.Write(" LEFT JOIN folder f ON le.folder_uid = f.uid AND le.org_id = f.org_id")
```
Comment (evictorero) [inline pkg/services/libraryelements/database.go]: I don't think we should use a JOIN while migrating to unified storage. We recently removed all queries that join the dashboards table and it is the same case for folders.

**Review by evictorero — COMMENTED** [review]
I left some comments about the approach.
The search works as expected. I found an unexpected case.
When selecting the general folder in the old dashboard filter, it lists children folders. But when I type in a child folder name it disappears.

https://github.com/user-attachments/assets/ea3a0433-f284-42f4-8d05-cbba409924e5

File: pkg/services/libraryelements/database.go (hunk 1 above)
Comment (axelavargas) [reply pkg/services/libraryelements/database.go]: No, I didn't look at that service. Thanks, Eze. I'll check it out.

File: pkg/services/libraryelements/database.go (hunk 2 above)
Comment (axelavargas) [reply pkg/services/libraryelements/database.go]: I will research a different way, btw if you have any examples, let me know

Comment (evictorero) [reply pkg/services/libraryelements/database.go]: This JOIN is only needed to filter by f.title but if `folderService.SearchFolders` already returns folders filtered by permissions and title then you can use the folder uids directly in this query and remove the JOIN.

Comment (axelavargas) [reply pkg/services/libraryelements/database.go]: I made changes using the the `folderService.SearchFolders`, it works as expected! I had to implement some fallback mechanism because that service is behind `KubernetesClientDashboardsFolders`

File: pkg/services/libraryelements/database.go [hunk 3]
```diff
@@ -459,9 +495,10 @@ func (l *LibraryElementService) getAllLibraryElements(c context.Context, signedI
 		builder.Write(selectLibraryElementDTOWithMeta)
 		builder.Write(", le.folder_uid as folder_uid ")
 		builder.Write(getFromLibraryElementDTOWithMeta(l.SQLStore.GetDialect()))
+		builder.Write(" LEFT JOIN folder f ON le.folder_uid = f.uid AND le.org_id = f.org_id")
```
Comment (evictorero) [inline pkg/services/libraryelements/database.go]: This is not needed anymore, we can filter directly by `folder_uid` and `org_id` in the `library_element` table

File: pkg/services/libraryelements/database.go [hunk 4]
```diff
@@ -441,6 +441,42 @@ func (l *LibraryElementService) getAllLibraryElements(c context.Context, signedI
...
+	if len(strings.TrimSpace(query.SearchString)) > 0 {
+		searchQuery := folder.SearchFoldersQuery{
+			OrgID:        signedInUser.GetOrgID(),
+			Title:        query.SearchString,
+			SignedInUser: signedInUser,
+		}
+
+		folderHits, err := l.folderService.SearchFolders(c, searchQuery)
+		if err != nil {
+			if strings.Contains(err.Error(), "cannot be called on the legacy folder service") {
```
Comment (evictorero) [inline pkg/services/libraryelements/database.go]: If we know in advance `folderService.SearchFolders` only works with `FlagKubernetesClientDashboardsFolders` we could maybe ask about it instead of using a string contains to match with an error string.

File: pkg/services/libraryelements/database.go [hunk 5]
```diff
@@ -441,6 +441,42 @@ func (l *LibraryElementService) getAllLibraryElements(c context.Context, signedI
...
+				}
+				foldersWithMatchingTitles = make([]string, 0, len(fs))
+				for _, f := range fs {
+					if strings.Contains(strings.ToLower(f.Title), strings.ToLower(query.SearchString)) {
+						foldersWithMatchingTitles = append(foldersWithMatchingTitles, f.UID)
+					}
+				}
+			} else {
+				return model.LibraryElementSearchResult{}, err
+			}
```
Comment (evictorero) [inline pkg/services/libraryelements/database.go]:
```suggestion
		if err != nil && !strings.Contains(err.Error(), "cannot be called on the legacy folder service") {
		   return model.LibraryElementSearchResult{}, err
		}
		fs, err := l.folderService.GetFolders(c, folder.GetFoldersQuery{
			OrgID:        signedInUser.GetOrgID(),
			SignedInUser: signedInUser,
		})
		if err != nil {
			return model.LibraryElementSearchResult{}, err
		}
		foldersWithMatchingTitles = make([]string, 0, len(fs))
		for _, f := range fs {
			if strings.Contains(strings.ToLower(f.Title), strings.ToLower(query.SearchString)) {
				foldersWithMatchingTitles = append(foldersWithMatchingTitles, f.UID)
			}
		}
```

nit: About Go, we try to return early if there is an error. In this case, I would add the nested condition and return the errro when needed, and then, the happy path without nesting if/else.

File: pkg/services/libraryelements/database.go [hunk 6]
```diff
@@ -441,6 +441,42 @@ func (l *LibraryElementService) getAllLibraryElements(c context.Context, signedI
 	if folderFilter.parseError != nil {
 		return model.LibraryElementSearchResult{}, folderFilter.parseError
 	}
+
+	var foldersWithMatchingTitles []string
```
Comment (evictorero) [inline pkg/services/libraryelements/database.go]: We could extract all the following code to a function that returns these `foldersWithMatchingTitles` and keep the main function cleaner for better readability.

File: pkg/services/libraryelements/database.go [hunk 7]
```diff
@@ -426,6 +426,12 @@ func (l *LibraryElementService) getAllLibraryElements(c context.Context, signedI
...
+	foldersWithMatchingTitles, err = getFoldersWithMatchingTitles(c, l, signedInUser, query)
```
Comment (evictorero) [inline pkg/services/libraryelements/database.go]:
```suggestion
foldersWithMatchingTitles, err := getFoldersWithMatchingTitles(c, l, signedInUser, query)
```
nit: more idiomatic in Go

File: pkg/services/libraryelements/writers.go [hunk 8]
```diff
@@ -58,13 +58,28 @@ func writeTypeFilterSQL(typeFilter []string, builder *db.SQLBuilder) {
...
 		sql, param := sqlStore.GetDialect().LikeOperator("le.name", true, query.SearchString, true)
 		builder.Write(" AND ("+sql, param)
 
+		// Search element descriptions across all accessible folders
 		sql, param = sqlStore.GetDialect().LikeOperator("le.description", true, query.SearchString, true)
-		builder.Write(" OR "+sql+")", param)
+		builder.Write(" OR "+sql, param)
+
+		// Include ALL elements from folders whose titles match the search string
+		hasFolderFilter := len(strings.TrimSpace(query.FolderFilterUIDs)) > 0
```
Comment (evictorero) [inline pkg/services/libraryelements/writers.go:72]: Why do we have this condition `!hasFolderFilter` ? In my mind, if the folder filter has `FolderA, FolderB, FolderC` selected and I type in the search folder `FolderA`, I would expect only to see `FolderA`.

File: pkg/services/libraryelements/database.go [hunk 9]
```diff
@@ -882,3 +888,43 @@ func contains(slice []string, element string) bool {
 	}
 	return false
 }
+
+func getFoldersWithMatchingTitles(c context.Context, l *LibraryElementService, signedInUser identity.Requester, query model.SearchLibraryElementsQuery) ([]string, error) {
+	var foldersWithMatchingTitles []string
+	if len(strings.TrimSpace(query.SearchString)) > 0 {
```
Comment (evictorero) [inline pkg/services/libraryelements/database.go]: nit: In Go we try to keep the code aligned to the left. To do so, we prefer to have more than one return statement and return as soon as possible. In this case, for example, it would be better this approach to remove the nested if/else condition.
```suggestion
	if len(strings.TrimSpace(query.SearchString)) <= 0 {
		return nil, nil
	}
```

File: pkg/services/libraryelements/database.go [hunk 10]
```diff
@@ -882,3 +888,43 @@ func contains(slice []string, element string) bool {
...
+			folderHits, err := l.folderService.SearchFolders(c, searchQuery)
+
+			if err != nil {
+				return nil, err
+			}
+			foldersWithMatchingTitles = make([]string, 0, len(folderHits))
+			for _, hit := range folderHits {
+				foldersWithMatchingTitles = append(foldersWithMatchingTitles, hit.UID)
+			}
+		} else {
```
Comment (evictorero) [inline pkg/services/libraryelements/database.go]: Instead of an else we could return above and put al the else code aligned to the left below.

File: pkg/services/libraryelements/database.go [hunk 11]
```diff
@@ -882,3 +888,43 @@ func contains(slice []string, element string) bool {
...
+			SignedInUser: signedInUser,
+		}
+
+		if l.features.IsEnabled(c, featuremgmt.FlagKubernetesClientDashboardsFolders) {
+			folderHits, err := l.folderService.SearchFolders(c, searchQuery)
+
+			if err != nil {
+				return nil, err
+			}
+			foldersWithMatchingTitles = make([]string, 0, len(folderHits))
```
Comment (evictorero) [inline pkg/services/libraryelements/database.go]: nit: We can declare this var before using it instead of declaring it at the beginning.
```suggestion
			foldersWithMatchingTitles := make([]string, 0, len(folderHits))
```

File: pkg/services/libraryelements/writers.go (hunk 8 above)
Comment (axelavargas) [reply pkg/services/libraryelements/writers.go:72]: the condition is here to narrow the search to filter by "name" and "description" only if the user set the folder filter.

Think in this use case:
->Folder: Alexa 
---> library panels title: "alexa lib panel", "eze lib panel"

->Folder: Alexa2 
---> library panels title: "alexa 2 lib panel", "eze 2 lib panel"

->Dashboards (this is the fake general folder)
---> library panels title: "alexa 3 lib panel", "eze 2 lib panel"

If a user search by "alexa" and set the folder filter to "alexa"
The output should be: `alexa lib panel`

If a user search by "alexa" and doesn't use any folder filter
The output should be: 
- `alexa lib panel`
 - `eze lib panel`
 - `alexa 2 lib panel`
 - `eze 2 lib panel`
 - `alexa 3 lib panel`

This is returning all the library panels from the folder matching "alexa" and the library panels title that match as well

https://github.com/user-attachments/assets/1ac32800-6f0d-45d5-bb66-3660d6ef30b9

**Review by evictorero — APPROVED** [review]
LGTM!!
