### PR TITLE
Alerting: Fix screenshot is not taken for stale series

### LINKED ISSUE #57954: Alerting: Screenshots are not taken when firing alert is resolved due to stale series
**What happened**:

Screenshots are not taken when a firing alert is resolved because the series is stale (i.e there is no more data for the series).  This happens because alerts for stale series are resolved in `staleResultsHandler` which does not call `maybeTakeScreenshot`.

**What you expected to happen**:

Screenshots should be taken for series that either fall below the alert threshold or are stale.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by grobinson-grafana**
**Which issue(s) does this PR fix?**:

Fixes #57954

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/ngalert/state/manager.go [hunk 1]
```diff
@@ -418,6 +392,20 @@ func (st *Manager) staleResultsHandler(ctx context.Context, evaluatedAt time.Tim
...
 				}
+
+				// If there is no resolved image for this rule then take one
+				if resolvedImage == nil {
+					image, err := takeImage(ctx, st.imageService, alertRule)
+					if err != nil {
+						logger.Warn("Failed to take an image",
+							"dashboard", alertRule.DashboardUID,
+							"panel", alertRule.PanelID,
+							"err", err)
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/state/manager.go:403]: according to the new [guidelines ](https://github.com/grafana/grafana/blob/main/contribute/engineering/backend/instrumentation.md) we should use label `error` for errors

File: pkg/services/ngalert/state/manager.go [hunk 2]
```diff
@@ -389,6 +359,10 @@ func (i InstanceStateAndReason) String() string {
 }
 
 func (st *Manager) staleResultsHandler(ctx context.Context, evaluatedAt time.Time, alertRule *ngModels.AlertRule, states map[string]*State, logger log.Logger) []*State {
+	// If we are removing two or more stale series it makes sense to share the resolved image as the alert rule is the same.
+	// TODO: We will need to change this when we support images without screenshots as each series will have a different image
+	var resolvedImage *ngModels.Image
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/state/manager.go:364]: I wonder if the image should be passed as an argument because during this cycle manager could process normal states and already take a screenshot. Another idea is to do this on the screenshot service side (i.e. caching rule + eval timestamp)

Comment (yuri-tceretian) [reply pkg/services/ngalert/state/manager.go:364]: Another alternative: this method accepts a map of states which may already have the image taken. Probably reuse it?

**Review by yuri-tceretian — APPROVED** [review]
Changes LGTM. Please see my comments

File: pkg/services/ngalert/state/manager.go (hunk 2 above)
Comment (grobinson-grafana) [reply pkg/services/ngalert/state/manager.go:364]: I would not be against passing it as an argument, but there are two issues in doing so that I would need to figure out:

1. Does `ProcessEvalResults` then take the screenshot? We want a screenshot of the graph from around the time the alert was resolved, rather than the original screenshot from when it fired
2. In future when we replace screenshots with server-side images we will need to create an image per state as each state will have different historical time series

Comment (yuri-tceretian) [reply pkg/services/ngalert/state/manager.go:364]: 1 Isn't the image we create in `setNextState` the same as we create in the stale results handler? I think that currently, we can make it once per `ProcessEvalResults` and then share it between all states. Is that correct?
2. Agree but we can refactor when we are there, right?

Comment (grobinson-grafana) [reply pkg/services/ngalert/state/manager.go:364]: I think it would be an issue when the alert rule is deleted because there would be no next state, however the results handler would still need to resolve all existing alerts.
