### PR TITLE
Fix: Redirect to correct url after creating a folder

### LINKED ISSUE #26108: Creating new folder redirects to 404 error page
**What happened**:

Whenever I create a new folder, the folder gets created (good) and I get redirected to a 404 error page (bad). I can simply navigate back but it is a bug, nevertheless.

**What you expected to happen**:

No redirection to 404 page.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new folder

**Anything else we need to know?**:

**Environment**:

- Grafana version: v7.0.5 (efbcbb838b)
- OS Grafana is installed on: Vanilla Grafana Docker image
- User OS & Browser: Windows, Chrome
- Grafana plugins: No
- behind reverse proxy Nginx

See this comment for more details: https://github.com/grafana/grafana/issues/26108#issuecomment-654944818

gif

### PR DESCRIPTION
**Pull request by peterholmberg**
**What this PR does / why we need it**:
Fixes an issue where the redirect after creating a new folder would end up on a 404 page.

**Which issue(s) this PR fixes**:
Fixes #26108

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/folders/state/actions.ts [hunk 1]
```diff
@@ -122,9 +121,8 @@ export function addFolderPermission(newItem: NewDashboardAclItem): ThunkResult<v
 
 export function createNewFolder(folderName: string): ThunkResult<void> {
   return async dispatch => {
-    // @ts-ignore
-    const newFolder = await getBackendSrv().createFolder({ title: folderName });
+    const newFolder = await getBackendSrv().post('/api/folders', { title: folderName });
     appEvents.emit(AppEvents.alertSuccess, ['Folder Created', 'OK']);
-    dispatch(updateLocation({ path: newFolder.url }));
+    dispatch(updateLocation({ path: locationUtil.stripBaseFromUrl(newFolder.url) }));
```
Comment (dprokop) [inline public/app/features/folders/state/actions.ts:126]: ah, so the API call returns URL with the base url applied?

**Review by dprokop — APPROVED** [review]

File: public/app/features/folders/state/actions.ts (hunk 1 above)
Comment (peterholmberg) [reply public/app/features/folders/state/actions.ts:126]: correct!
