### PR TITLE
Table: Make last cell value visible when right aligned

### LINKED ISSUE #24872: 7.0 Table scrollbar obscures last column
**What happened**:
A table panel with too many values generates a scrollbar, which obscures the last column

**What you expected to happen**:

Scrollbar should render next to the table, not over it.

**How to reproduce it (as minimally and precisely as possible)**:

Generate a large table with a final column that is right-aligned.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0
- Data source type & version: Postgresql
- OS Grafana is installed on: Debian 10
- User OS & Browser: Debian 10, Firefox 68.7.0
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by peterholmberg**
**What this PR does / why we need it**:
In Firefox, the last cell of a row is partially hidden when the scroll bar is visible. This PR adds some padding to accommodate the scroll bar.

table_scrollbar_clip

table_scrollbar_clip_fix

**Which issue(s) this PR fixes**:
Fixes #24872

**Special notes for your reviewer**:

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/styles.ts [hunk 1]
```diff
@@ -82,6 +82,7 @@ export const getTableStyles = stylesFactory(
 
         &:last-child {
           border-right: none;
+          padding-right: 5px;
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/Table/styles.ts:85]: nit: shouldn't use spacing from the theme instead of hardcoding values? Or maybe that is hard to use in this context?

**Review by hugohaggmark — APPROVED** [review]
LGTM!

File: packages/grafana-ui/src/components/Table/styles.ts (hunk 1 above)
Comment (peterholmberg) [reply packages/grafana-ui/src/components/Table/styles.ts:85]: Yeah, we can. Just tried with 8px and it looks ok.

**Review by dprokop — CHANGES_REQUESTED** [review]
We need to think about different solution, as it breaks the UI in other scenarios:

image

**Review by torkelo — APPROVED** [review]

**Review by torkelo — APPROVED** [review]
Updated code a bit, moved padding into the inner div (so that it's not outside the colored area, and made the padding dependant on the actual scrollbar width.

**Review by dprokop — APPROVED** [review]
