### PR TITLE
CommandPalette: Fix long dashboard names freezing the browser

### LINKED ISSUE #61093: Bug: Long dashboard names cause the command palette to crash

### PR DESCRIPTION
**Pull request by joshhunt**
**What is this feature?**

Uses a custom `useMatches` hook with a different search (@leeoniya's uFuzzy) that doesn't crash the browser on long dashboard names.
 
**Why do we need this feature?**

So Command Palette wows and amazes users instead of disapointing them!

**Who is this feature for?**

Everyone! 🙌

**Which issue(s) does this PR fix?**:

Fixes #61093

**Special notes for your reviewer**:

This is somewhat of an interim solution until the problem is fixed within kbar directly.

I think we should have this fix _as well as_ https://github.com/grafana/grafana/pull/61271

We need to test and evaluate this properly as uFuzzy is less 'fuzzy' than the command-score that was used before, so in most cases this will return less results than before.

For example, previously "datasources" would match "Data sources", but with this change it will no longer match that.

| Before | After |
| --- | --- |
| image | image |

I think the higher level of fuzziness is preferred - similar to VS Code's command palette where it might be common start a search with a prefix, and narrow it down with a phrase occuring at the end (skipping a bunch of words/characters in the middle).

I think there's a few solutions to this, but worth keeping in mind.

### CODE REVIEW

**Review by ashharrison90 — COMMENTED** [review]
performance is definitely much better than the default `command-score` implementation in `kbar` 🙌 

still crashes on super long dashboard names but the search term has to be much longer now. 

i think between this and https://github.com/grafana/grafana/pull/61271 we're in a pretty good spot performance-wise

with regards to fuzziness, the backend dashboard search is less fuzzy anyway (doesn't handle typos for example) so i don't think it's a big problem

**Comment by joshhunt** [comment]
> with regards to fuzziness, the backend dashboard search is less fuzzy anyway (doesn't handle typos for example) so i don't think it's a big problem

@ashharrison90  But nav tree isn't searched on the backend, so less nav tree results will return now (try searching for 'datasources' settings page, for example)

**Comment by ashharrison90** [comment]
@joshhunt yep agreed, but it's a smaller subset than all of the dashboards as well 😄

**Comment by leeoniya** [comment]
> uFuzzy is less 'fuzzy' than the command-score
> For example, previously "datasources" would match "Data sources", but with this change it will no longer match that.

setting `intraChars: '.'` will make it fuzzier by also allowing insertion of punctuation and whitespace in between term chars, instead of only alphanum, which is the default setting (`[a-z\d]`).

**Comment by ashharrison90** [comment]
@leeoniya it's in uFuzzy, but it's approaching an edge case tbh (requires a fairly long search string)

you can see it in your demo page. go to https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&outOfOrder&search=spac%20ca and type `Memory that is completely free and eligible to be returned to the underlying system, but has not been`... at some point it'll crash. for me, it's around `eligible`.

**Comment by joshhunt** [comment]
@leeoniya I see [in the search service](https://github.com/grafana/grafana/blob/bbcd7d0899d0c4966c06d71e7213f592c7f634da/public/app/features/search/service/frontend.ts/#L122-L123) you do multiple searches with different orders of search words(?), and then concat the results. Do you think doing something similar here would be useful?

**Comment by leeoniya** [comment]
oof, i dont think there's much i can do about combinatorial explosion in a sentance-long regex. we'll just have to "avoid holding it that way" 😅. it would be more worrisome if it was crashing due to some property of our haystack. limiting the needle seems much more palatable. fwiw, i've never needed to type more than 3 partial terms to filter down a 200k list to less than a dozen items.

we could consider removing stop words from the needle, which would shorten your example somewhat.

`Memory that is completely free and eligible to be returned to the underlying system, but has not been`

becomes something like

`Memory completely free eligible returned underlying system not been`

**Comment by leeoniya** [comment]
> @leeoniya I see [in the search service](https://github.com/grafana/grafana/blob/bbcd7d0899d0c4966c06d71e7213f592c7f634da/public/app/features/search/service/frontend.ts/#L122-L123) you do multiple searches with different orders of search words(?), and then concat the results. Do you think doing something similar here would be useful?

yes, i think we should do it. you can prolly copy/paste https://github.com/grafana/grafana/blob/main/public/app/features/search/service/frontend.ts#L120

**Comment by ashharrison90** [comment]
@leeoniya naw i agree i think it's fine as-is, that's why i was saying it's approaching an edge case tbh 👍

**Comment by joshhunt** [comment]
@ashharrison90 @leeoniya Edge case that can be easily triggered by user typing stuff in. I think Grafana should try to not crash the browser 😅 

What do we think about if the search term is over a limit, we just do a simple substring match using `str.includes()`?

```js
const MAX_SEARCH_LIMIT = 25;

if (query.length > MAX_SEARCH_LIMIT ) {
  return haystack.filter(hay => hay.contains(query))
} else {
  return searchUsingUfuzzy(...)
}
```

The demo page starts to get too slow for me (firefox, whatever PC this is I have) at about 25 characters - is that a reasonable limit?

**Comment by leeoniya** [comment]
i might be missing a bit of context here, and maybe im a bit confused becaise im unfamiliar with the command palette and the discussion here is about dashboard search.

is the command pallete both a search and a command autocomplete? where can i test it? what types of needles are typical? what haystacks are typical? (feel free to ping me with this info on slack).

intraMode:1 and outOfOrder is great for search but for sure much slower than the default settings, and less appropriate for command typeahead/autocomplete.

if the command palette serves both cases, and we can identify which is being used, we can use two different uFuzzy instances to provide better/faster results in each case.

**Comment by leeoniya** [comment]
> The demo page starts to get too slow for me (firefox, whatever PC this is I have) at about 25 characters

the demo has 162k entries, and our largest users have ~100k dashboards, with some users > 10k, and the vast majority of users < 1k. so this limit could likely be quite a bit higher, but 25 sounds fine initially as a substring fallback threshold. with outOfOrder enabled, things can get out of hand rather quickly :)

what could help a lot is some kind of hint below the entry field when the search string is empty. something like:

**HINT**: For faster results, search `prom rem stor` instead of `prometheus remote storage`

**Comment by leeoniya** [comment]
@joshhunt feel free to bump the uFuzzy dep to [0.9.1](https://github.com/leeoniya/uFuzzy/releases/tag/0.9.1) as part of this.

File: public/app/features/commandPalette/useMatches.ts [hunk 1]
```diff
@@ -0,0 +1,256 @@
...
+      intraMode: 1,
+      intraIns: 1,
+      intraSub: 1,
+      intraTrn: 1,
+      intraDel: 1,
+    });
+  }
+
+  return ref.current;
+}
```
Comment (joshhunt) [inline public/app/features/commandPalette/useMatches.ts:256]: This section is basically the only part that I've written/changed. Everything else is copy-pasta

File: public/app/features/commandPalette/useMatches.ts [hunk 2]
```diff
@@ -0,0 +1,256 @@
...
+        if (substringPosition > -1) {
+          const score = haystack.length - substringPosition;
+          const action = throttledFiltered[haystackIndex];
+          results.push({ score, action });
+        }
+      }
+    } else {
+      const allMatchedIndexes = new Set<number>();
+
+      const queryWords = ufuzzy.split(throttledSearch);
```
Comment (leeoniya) [inline public/app/features/commandPalette/useMatches.ts:215]: you may want to add a guard here for or 4 or 5 terms before falling back to substring match. permutations are factorial, so it can explode for stuff like `a b c d e f g h i` before our 25 char limit.

Comment (joshhunt) [reply public/app/features/commandPalette/useMatches.ts:215]: maybe only do `permutations` if <= 5 words or something?

Comment (leeoniya) [reply public/app/features/commandPalette/useMatches.ts:215]: that works too

**Review by ashharrison90 — APPROVED** [review]
lgtm! 🙌
