### PR TITLE
AnnotationList: Fix link for annotation with no panel or dashboard

### LINKED ISSUE #86774: Annotations in Annotation List doesn't change timeline
### What happened?

Hello Team,

We noticed that if we create Annotations using the API, without linking them to any Dashboard or Panel, and we visualize them in a Panel using the Annotations List visualization, the Link behavior defaults to 10m before/after. I don't know if it's possible, but for annotations without panel nor dashboard assigned, could we just make it change the time range of the $current_dashboard without trying to link anywhere?

Recording is attached below.
https://github.com/grafana/grafana/assets/135922203/b7b827ab-c84f-400b-be80-68b8d42c91ee

Customer use case would be the following:

> Would be nice to have a place to surface "all" annotations in Grafana cloud, we still have option to filter for "This Dashboard" if we only want to show annotations associated to a specific dashboard.
> Clickable part is a nice to have, my use case here is I would like to view how my panels looked like during this "global" annotation, just serves as a quick way to investigate correlation between events(annotations) and impact(graphs).
> My use case, I have hooked our deployment system to send annotations to Grafana cloud, I want these annotations to be available now and in the future to anyone who would like to use them in their dashboards, so having a "global view" in the Annotation list visualization would be cool, later service owners can click on such annotations to take them to the time range of the annotation in an arbitrary dashboard.
> I realize this might not be a common use case, but I think the current implementation has most of the functionality.

### What did you expect to happen?

 They want these annotations to be available now and in the future to anyone who would like to use them in their dashboards, so having a "global view" in the Annotation list visualization would be cool, later service owners can click on such annotations to take them to the time range of the annotation in an arbitrary dashboard.

### Did this work before?

No

### How do we reproduce it?

1. Create an Annotation via the API without linking it to any Dashboard or Panel
2. Visualize it using the Annotations List panel
3. Click on the Annotation from the list as showcased in the recording attached

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 11.1.0-69372

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by tskarhed**
**What is this feature?**

Only updates the timerange of the current dashboard, if the annotation has no associated panel or dashboard (previously error messages would be shown)

**Why do we need this feature?**

The panel and dashboards field are marked as optional in the HTTP API, hence we need to support it as a valid use case.

**Who is this feature for?**

Mainly users who create annotations via the HTTP API

**Which issue(s) does this PR fix?**:

Fixes [#86774](https://github.com/grafana/grafana/issues/86774)

**Special notes for your reviewer:**

[Use Swagger](http://localhost:3000/swagger) to create an annotation, and remove fields for panel and dashboard.

Pro tip: Create it before checking out this branch, and verify that the bug appears.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/panel/annolist/AnnoListPanel.tsx [hunk 1]
```diff
@@ -146,10 +146,10 @@ export class AnnoListPanel extends PureComponent<Props, State> {
     const params = {
       from: this._timeOffset(anno.time, options.navigateBefore, true),
       to: this._timeOffset(anno.timeEnd ?? anno.time, options.navigateAfter, false),
-      viewPanel: options.navigateToPanel ? anno.panelId : undefined,
+      viewPanel: options.navigateToPanel && anno.panelId ? anno.panelId : undefined,
```
Comment (tskarhed) [inline public/app/plugins/panel/annolist/AnnoListPanel.tsx:149]: Without this, the URL would update with viewPanel=null, which would then display an error message.

**Review by joshhunt — APPROVED** [review]
