### PR TITLE
LDAP: Fix for IPA v4.6.4 which does not allow empty attributes in search requests

### LINKED ISSUE #14432: Grafana LDAP authentication against IPA fails
### What Grafana version are you using?
grafana-5.3.0

### What datasource are you using?
Irrelevant

### What OS are you running grafana on?
Red Hat Enterprise Linux Server release 7.5 (Maipo)

### What did you do?
Update IPA from 4.5.4 -> 4.6.4

### What was the expected result?
LDAP authentication would proceed as normal

### What happened instead?
Trying to authenticate via LDAP:

```lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="LDAP Result Code 2 \"Protocol Error\": "```

Search request seen from IPA:

```
[05/Dec/2018:10:50:10.160459643 +0200] conn=84119 fd=338 slot=338 SSL connection from XXX.XX.X.XXX to XXX.XX.X.XXX
[05/Dec/2018:10:50:10.165958341 +0200] conn=84119 TLS1.2 256-bit AES-GCM
[05/Dec/2018:10:50:10.167109254 +0200] conn=84119 op=0 BIND dn="uid=readgroup,cn=users,cn=accounts,dc=asd,dc=asd,dc=asd" method=128 version=3
[05/Dec/2018:10:50:10.167750466 +0200] conn=84119 op=0 RESULT err=0 tag=97 nentries=0 etime=0.0007013470 dn="uid=readgroup,cn=users,cn=accounts,dc=asd,dc=asd,dc=asd"
[05/Dec/2018:10:50:10.168907397 +0200] conn=84119 op=1 SRCH base="(null)" scope=2 asdlter="(uid=asdf)", invalid attribute request
[05/Dec/2018:10:50:10.168943337 +0200] conn=84119 op=1 RESULT err=2 tag=101 nentries=0 etime=0.0000119809
[05/Dec/2018:10:50:10.170213905 +0200] conn=84119 op=-1 fd=338 closed - B1
```

As you can see SRCH base is null. Debuggin tcpdump and testing ldap authentication. Bind works fine but search gives out null

grafana:

```
30 76 02 01 02 63 71 04
```

go-ldap (5.3.0 source code) / perl(Net::LDAP) / python(ldap), these are working:

```
30 78 02 01 02 63 73 04
```

As you can see 2nd and 7th bytes from hexa differ from other requests. Maybe grafana LDAP implementation is adding/modifying something to the request?

From go-ldap it seems this block is responsible for the search requests, which seems to be failing in grafana:

```
searchRequest := NewSearchRequest(
"dc=example,dc=com", // The base dn to search
ScopeWholeSubtree, NeverDerefAliases, 0, 0, false,
"(&(objectClass=organizationalPerson))", // The filter to apply
[]string{"dn", "cn"}, // A list attributes to retrieve
nil,
)
```

Grafana:

```
func (a *ldapAuther) searchForUser(username string) (*LdapUserInfo, error) {
var searchResult *ldap.SearchResult
var err error

for _, searchBase := range a.server.SearchBaseDNs {
searchReq := ldap.SearchRequest{
BaseDN: searchBase,
Scope: ldap.ScopeWholeSubtree,
DerefAliases: ldap.NeverDerefAliases,
Attributes: []string{
a.server.Attr.Username,
a.server.Attr.Surname,
a.server.Attr.Email,
a.server.Attr.Name,
a.server.Attr.MemberOf,
},
Filter: strings.Replace(a.server.SearchFilter, "%s", ldap.EscapeFilter(username), -1),
}
```

From LDAP error codes:

==============================
‣2 
‣ LDAP_PROTOCOL_ERROR 
‣ Indicates that the server has received an invalid or malformed request from the client.
\==============================

ldap.toml:

```
verbose_logging = true

[[servers]]
host = "foobar.asd.asd.asd"
port = 389
use_ssl = false
ssl_skip_verify = true

# Search user bind dn
bind_dn = "uid=readgroup,cn=users,cn=accounts,dc=asd,dc=asd,dc=asd"
bind_password = 'asd'

search_filter = "(uid=%s)"
search_base_dns = ["cn=users,cn=accounts,dc=asd,dc=asd,dc=asd"]

[servers.attributes]
name = "displayName"
username = "uid"
member_of = "memberOf"

[[servers.group_mappings]]
group_dn = "cn=sw_perfdb_grafana_admins_asd,cn=groups,cn=accounts,dc=asd,dc=asd,dc=asd"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"
```

### PR DESCRIPTION
**Pull request by daniellee**
Fixes #14432 

A security patch for IPA/FreeIPA v4.6.4 had the side effect of not allowing LDAP searches with empty attributes in the search request. This fix only adds attributes to the search request if they are mapped in the ldap toml file and does not send empty attributes as it currently does.

This PR also includes a simple docker block for FreeIPA so that we can test LDAP issues in the future. An alternative to using the docker-compose block is to use the following docker run command:

```bash
docker run --name freeipa -ti \
--sysctl net.ipv6.conf.all.disable_ipv6=0 \
--tmpfs /run --tmpfs /tmp -v /dev/urandom:/dev/random:ro \
-v /sys/fs/cgroup:/sys/fs/cgroup:ro \
-h ipa.example.test \
-p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 \
-p 88:88/udp -p 464:464/udp -p 123:123/udp -p 7389:7389 \
-p 9443:9443 -p 9444:9444 -p 9445:9445 \
-e PASSWORD=Secret123 -e DEBUG_NO_EXIT=1 \
freeipa/freeipa-server:fedora-29 -r EXAMPLE.TEST \
-U --admin-password=Secret123 --ds-password=Secret123
```

To test this PR, you will need to run the above command and then create a user (per default only an admin user is created). To create a user, follow the instructions in the notes.md file included in this PR.

### CODE REVIEW

File: pkg/login/ldap.go [hunk 1]
```diff
@@ -278,18 +278,27 @@ func (a *ldapAuther) searchForUser(username string) (*LdapUserInfo, error) {
 	var err error
 
 	for _, searchBase := range a.server.SearchBaseDNs {
+		attributes := make([]string, 0)
+
+		appendIfNotEmpty := func(slice []string, attr string) []string {
```
Comment (torkelo) [inline pkg/login/ldap.go]: maybe we can move this to a package func or out of the loop (just looks a bit strang to define this util function in the loop :)

Comment (bergquist) [reply pkg/login/ldap.go]: Could be a func with an `...string` argument.
ex https://play.golang.org/p/deln_a2skzU

**Comment by xlson** [comment]
I fixed the comments but ran into some problems when trying to test with freeipa. Round 2 on monday.
