### PR TITLE
Alerting: Attempt to send email notifications to all given email addresses

### LINKED ISSUE #16651: E-mail alerts: if one address fails, all other addresses after it also fail
**What happened**:
When an e-mail notification channel uses multiple destination e-mail addresses, a failure in one address causes all the addresses after it to be skipped also.

**What you expected to happen**:
If an alert is configured to go to multiple addresses, and one fails, all the others should still be attempted, regardless of what order they have been entered into the notification channel configuration.

**How to reproduce it (as minimally and precisely as possible)**:
Create a test e-mail Notification channel.

Add three e-mail addresses, for example:
  good.mail@myserver.com
  bogus.fake.mail@myserver.com
  a.different.good.mail@myserver.com

Click "Save" and click "Send Test"

The test mail will be delivered to the first good address, but will not be delivered to the second good address

**Anything else we need to know?**:

The grafana server log file says something like:

t=2019-04-17T11:32:50-0400 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="gomail: could not send email 1: 550 5.1.1 <jamespzzzz@[domain redacted]>: Recipient address rejected: User unknown in local recipient table"

**Environment**:
- Grafana version:
Grafana v6.1.0 (03346b6)

- Data source type & version:
N/A

- OS Grafana is installed on:
CentOS 7

- User OS & Browser:
Windows 10  and Chrome

- Grafana plugins:
N/A

- Others:

### PR DESCRIPTION
**Pull request by zhulongcheng**
**What this PR does / why we need it**:
Attempt to send notifications to all given email addresses and log failed addresses.

**Which issue(s) this PR fixes**:

Fixes #16651

### CODE REVIEW

File: pkg/services/notifications/mailer.go [hunk 1]
```diff
@@ -23,6 +24,8 @@ func (ns *NotificationService) send(msg *Message) (int, error) {
 		return 0, err
 	}
 
+	var num int
+	var werr error
```
Comment (bergquist) [inline pkg/services/notifications/mailer.go]: error variables should be named `err`. You can just avoid declaring this variable and overwrite `err` instead.

File: pkg/services/notifications/mailer.go [hunk 2]
```diff
@@ -35,11 +38,14 @@ func (ns *NotificationService) send(msg *Message) (int, error) {
 		m.SetBody("text/html", msg.Body)
 
 		if err := dialer.DialAndSend(m); err != nil {
```
Comment (bergquist) [inline pkg/services/notifications/mailer.go]:
```suggestion
		err = dialer.DialAndSend(m) {
		if err != nil {
```

File: pkg/services/notifications/mailer.go [hunk 3]
```diff
@@ -35,11 +38,14 @@ func (ns *NotificationService) send(msg *Message) (int, error) {
...
-			return 0, err
+			werr = errors.Wrapf(err, "Failed to send notification to email address: %s", address)
+			continue
 		}
+
+		num += 1
 	}
 
-	return len(msg.To), nil
+	return num, werr
```
Comment (bergquist) [inline pkg/services/notifications/mailer.go]: since the loop never is exicted `num` will always be the same as `len(msg.To)` So unless there is somhing I havent consiered you can just go back to using `len(msg.To)`

**Comment by bergquist** [comment]
Thank you for taking the time to contribute to Grafana! I've made some minor comments that I would like to see fixed before we merge this.

File: pkg/services/notifications/mailer.go (hunk 1 above)
Comment (zhulongcheng) [reply pkg/services/notifications/mailer.go]: ok

File: pkg/services/notifications/mailer.go (hunk 3 above)
Comment (zhulongcheng) [reply pkg/services/notifications/mailer.go]: https://github.com/grafana/grafana/blob/0c1530c7a89ba3321a24567a28a511cd13a6c407/pkg/services/notifications/notifications.go#L85-L96

the `num` should be the number of addresses sent successfully.

If some addresses failed, `num` will less than `len(msg.To)`.

Comment (bergquist) [reply pkg/services/notifications/mailer.go]: Your right. Silly me :)

**Comment by bergquist** [comment]
Thank you for contributing to Grafana!
