### PR TITLE
Cloudmonitor: Refactor query builder

### LINKED ISSUE #58325: Google Cloud Monitoring: Refresh selector values when re-running a query
**What happened**:

There are several issues when editing values in the builder, each of these items can be treated as an independent issue:

 - When selecting a new Service, all filters and other fields (e.g. Group by) should be cleaned up.
 - When selecting a new Metric name, filters can be kept the same but the rest of inputs (e.g. Group by) should be cleaned up.
 - Fields that are automatically populated with options (e.g. Group by) should be refreshed everytime the query gets executed (e.g. when the time range changes). At the moment, is only re-calculated when the service or metric name changes.

**What you expected to happen**:

The builder to behave consistently after changes.

**How to reproduce it (as minimally and precisely as possible)**:

For the 3rd item: Select a small window (e.g. 1h), then select “Bigquery > Query Execution times”. Check that the "Group by" labels are empty. Increase time (1 week), the query gets executed and you should get some values back but the group-by selector still shows nothing.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.3
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by aangelisc**
This PR contains multiple fixes to ensure that builder values are refreshed according to the relevant property changes.

- All fields are refreshed when the `Service` is changed.
- All fields except `Filters` are refreshed when the `Metric name` is changed.
- The metric labels are refreshed when the panel time period is changed.
- Refactored `VisualMetricsQueryEditor` component and removed `Metrics` component.
- Updated `datasource` to expose `timeSrv`.

Fixes #58325

### CODE REVIEW

File: public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx [hunk 1]
```diff
@@ -38,12 +40,24 @@ function Editor({
   const [labels, setLabels] = useState<{ [k: string]: any }>({});
   const { projectName, groupBys, crossSeriesReducer } = query;
   const metricType = getMetricType(query);
+  const [timeState, setTime] = useState<{ from: string; to: string } | null>(null);
```
Comment (andresmgot) [inline public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx:43]: I think you can use `TimeOption` from `@grafana/data` here as the type.

File: public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx [hunk 2]
```diff
@@ -38,12 +40,24 @@ function Editor({
...
+  const timeSrv = getTimeSrv();
+
+  const useTime = (time: { from: string; to: string }) => {
+    if (timeState !== null && (timeState.from !== time.from || timeState.to !== time.to)) {
+      setTime({ ...timeSrv.time });
+    } else if (!timeState) {
+      setTime({ ...timeSrv.time });
+    }
```
Comment (andresmgot) [inline public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx:51]: what if rather than this `else` you do in the initialization:

```
  const timeSrv = getTimeSrv();
  const [timeState, setTime] = useState<TimeOption>(timeSrv.time);
```
?

File: public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx [hunk 3]
```diff
@@ -38,12 +40,24 @@ function Editor({
...
+  };
+
+  useTime(timeSrv.time);
 
   useEffect(() => {
     if (projectName && metricType) {
       datasource.getLabels(metricType, refId, projectName).then((labels) => setLabels(labels));
     }
-  }, [datasource, groupBys, metricType, projectName, refId, crossSeriesReducer]);
+  }, [datasource, groupBys, metricType, projectName, refId, crossSeriesReducer, timeState]);
```
Comment (andresmgot) [inline public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx:60]: this is a bit brittle, if you remove `timeState` here, nothing will tell you that you are breaking this. I see that `getLabels` is using `this.timeSrv.timeRange()`. Why don't you store the `TimeRange` in the state instead and pass it as an argument? That way you are sure that you are calling `getLabels` with the right range.

**Review by andresmgot — COMMENTED** [review]
Noice :) I have some suggestions you may have already considered, let me know if you know more!

File: public/app/plugins/datasource/cloud-monitoring/components/Metrics.tsx [hunk 4]
```diff
@@ -109,6 +110,8 @@ export function Metrics(props: Props) {
         label: m.displayName,
         description: m.description,
       }));
+    // On service change reset all query values except the project name
+    Object.assign(query, { ...defaultTimeSeriesList(datasource), projectName: query.projectName });
```
[the remark this answers is not in the document]
Comment (aangelisc) [reply public/app/plugins/datasource/cloud-monitoring/components/Metrics.tsx:114]: Updating the service value triggers `onChange` as it causes the `onMetricTypeChange` function to be called 😊

[the remark this answers is not in the document]
Comment (andresmgot) [reply public/app/plugins/datasource/cloud-monitoring/components/Metrics.tsx:114]: mmh, that would be relying on an indirect reference. `onMetricTypeChange` is getting the `query` object from `VisualMetricQueryEditor`, not from this component so it's a miracle if that works :sweat_smile:

I would move the definition of `onMetricTypeChange` to this component (since it's only used here) and explicitly build a full `query` object here that is used for the main `onChange` so it's explicit.

File: public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx (hunk 3 above)
Comment (andresmgot) [reply public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx:60]: not using `groupBys` and `crossSeriesReducer` already sounds like a bug and I don't know if that's on purpose :sweat_smile: 

> There isn't a need to pass TimeRange as an arg as the value used within the function would be the correct one

yes, but it feels more natural to calculate it here since this component is the one in charge of re-calling the function in case the TimeRange here. You are calculating the `time` here just to detect changes and recalculate the `range`. Isn't it simpler to just calculate the range and store that?

Comment (aangelisc) [reply public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx:60]: Also a good point. I'm now considering doing a bigger refactor of the `VisualMetricQueryEditor` because I'm not entirely sure why this component is separate to the `Metrics` component when there isn't much in that component specifically, wdyt?

Comment (andresmgot) [reply public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx:60]: yep, makes sense!

File: .betterer.results [hunk 5]
```diff
@@ -5063,9 +5063,6 @@ exports[`better eslint`] = {
     "public/app/plugins/datasource/cloud-monitoring/components/MQLQueryEditor.tsx:5381": [
       [0, 0, 0, "Unexpected any. Specify a different type.", "0"]
     ],
-    "public/app/plugins/datasource/cloud-monitoring/components/Metrics.tsx:5381": [
-      [0, 0, 0, "Unexpected any. Specify a different type.", "0"]
-    ],
```
Comment (joshhunt) [inline .betterer.results:5068]: 🥳

File: public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.test.tsx [hunk 6]
```diff
@@ -69,30 +221,66 @@ describe('VisualMetricQueryEditor', () => {
...
     );
     expect(query).toEqual(defaultQuery);
     expect(document.body).toHaveTextContent('metric.test_label');
-    expect(await screen.queryByText('Delta')).toBe(null);
-    expect(await screen.queryByText('metric.test_groupby')).toBe(null);
+    expect(await screen.queryByText('Delta')).not.toBeInTheDocument();
+    expect(await screen.queryByText('metric.test_groupby')).not.toBeInTheDocument();
+  });
+
+  it('updates labels on time range change', async () => {
```
Comment (andresmgot) [inline public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.test.tsx:240]: :oof: tricky test :sweat_smile:

File: public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.test.tsx [hunk 7]
```diff
@@ -69,30 +221,66 @@ describe('VisualMetricQueryEditor', () => {
...
+      timeSrv,
+    });
+
+    const { rerender } = render(
+      <VisualMetricQueryEditor {...defaultProps} onChange={onChange} datasource={datasource} query={query} />
+    );
+
+    const service = await screen.findByLabelText('Service');
+    await openMenu(service);
+    await act(async () => {
```
Comment (andresmgot) [inline public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.test.tsx:261]: I find that usually `act` is not needed, for example if you wait for the text 'Srv' to be there it should work the same way

File: public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx [hunk 8]
```diff
@@ -13,125 +16,263 @@ import { Alignment } from './Alignment';
...
-      setTime({ ...timeSrv.time });
-    } else if (!timeState) {
-      setTime({ ...timeSrv.time });
+  const [metricDescriptors, setMetricDescriptors] = useState<MetricDescriptor[]>([]);
+  const [metricDescriptor, setMetricDescriptor] = useState<MetricDescriptor>();
+  const [metrics, setMetrics] = useState<Array<SelectableValue<string>>>([]);
+  const [services, setServices] = useState<Array<SelectableValue<string>>>([]);
+  const [service, setService] = useState<string>('');
+  const [timeSrv, _setTimeSrv] = useState<TimeSrv>(datasource.timeSrv);
+  const [timeRange, setTimeRange] = useState<TimeRange>({ ...timeSrv.timeRange() });
```
Comment (andresmgot) [inline public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx:50]: why not
```suggestion
  const [timeRange, setTimeRange] = useState<TimeRange>({ ...datasource.timeSrv.timeRange() });
```
?

File: public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx [hunk 9]
```diff
@@ -13,125 +16,263 @@ import { Alignment } from './Alignment';
...
+    const metrics = metricDescriptors
+      .filter((m: MetricDescriptor) => m.service === templateSrv.replace(service))
+      .map((m: MetricDescriptor) => ({
+        service: m.service,
+        value: m.type,
+        label: m.displayName,
+        description: m.description,
+      }));
+    // On service change reset all query values except the project name
+    Object.assign(query, { ...defaultTimeSeriesList(datasource), projectName: query.projectName });
```
Comment (andresmgot) [inline public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx:139]: I don't think you need this assign, in  `if` condition below, `onMetricTypeChange` is doing the same, and in the `else` the query is not being updated anyway :shrug:

**Review by andresmgot — APPROVED** [review]
Thanks for the refactor :+1:

File: public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.test.tsx (hunk 6 above)
Comment (aangelisc) [reply public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.test.tsx:240]: 🤣  I finally got it working and I'm very happy about this

File: public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.test.tsx (hunk 7 above)
Comment (aangelisc) [reply public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.test.tsx:261]: Without the `act` I have the error related to causing the state to be updated outside of `act` so I think it's safer to keep them in?

File: public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx (hunk 8 above)
Comment (aangelisc) [reply public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx:50]: Good shout!

File: public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx (hunk 9 above)
Comment (aangelisc) [reply public/app/plugins/datasource/cloud-monitoring/components/VisualMetricQueryEditor.tsx:139]: This is partially true, I can change this to just set the `filters` value to `[]` as the assign in `onMetricTypeChange` conserves the value.
