### PR TITLE
AzureMonitor: Fix queries with Microsoft.NetApp/../../volumes resources

### LINKED ISSUE #28350: Azure: Problem with Microsoft.NetApp/../../volumes
When trying to create a panel for Azure metric 'Microsoft.NetApp/netAppAccounts/capacityPools/volume' the below error message is displayed:

**The Resource 'Microsoft.NetApp/netAppAccounts/capacityPools' under resource group 'my.rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix**

Seems like the API call is missing '/volumes'.

Creating panels for Azure metric 'Microsoft.NetApp/netAppAccounts/capacityPools' works as expected.

### PR DESCRIPTION
**Pull request by pckls**
This PR fixes #28350 

This is my first time contributing to the Grafana repo and I'm not particularly flash at TypeScript so apologies in advance for any obvious issues!

Here is a rough overview of my approach:
- Added additional tests for `buildAzureMonitorGetMetricNamespacesUrl` that I knew would pass, as there wasn't any coverage
- After this I added a test for both `buildAzureMonitorGetMetricNamespacesUrl` and `buildAzureMonitorGetMetricNamesUrl` that replicated #28350
- Made changes to both `buildAzureMonitorGetMetricNamespacesUrl` and `buildAzureMonitorGetMetricNamesUrl` and confirmed tests were passing

Things I considered improving but decided not to for initial PR:
- Refactoring two methods? into one as I think it could be consolidated (but likely would need updates elsewhere)
- Not using a for loop, it feels wrong and I'm sure there is a better way
- Could probably add some input validation; should there be a min/max for the length of `metricDefintion` or `resourceName`?

### CODE REVIEW

**Comment by pckls** [comment]
I have only just been able to test this by actually configuring my local Grafana instance, and while it does definitely fix the reported issue and allow metric names to be selected, it does also expose another issue as the actual getting of the metrics returns a 404. I'm still trying to figure out how that works, but I suspect it should be raised as a separate issue (will do once I figure it out) and a separate PR?

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts [hunk 1]
```diff
@@ -7,20 +7,16 @@ export default class UrlBuilder {
...
-      const md = metricDefinition.substring(0, metricDefinition.lastIndexOf('/'));
-      return (
-        `${baseUrl}/${subscriptionId}/resourceGroups/${resourceGroup}/providers/${md}/${rn[0]}/${service}/${rn[1]}` +
-        `/providers/microsoft.insights/metricNamespaces?api-version=${apiVersion}`
-      );
+    var metricDefinitionArray = metricDefinition.split('/');
+    const resourceNameArray = resourceName.split('/');
+    const provider = metricDefinitionArray.shift();
+    var urlArray = [baseUrl, subscriptionId, 'resourceGroups', resourceGroup, 'providers', provider];
+    for (var i in metricDefinitionArray) {
```
Comment (joshhunt) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts:14]: these three `var` should be `const`

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts [hunk 2]
```diff
@@ -32,23 +28,18 @@ export default class UrlBuilder {
...
-        `${baseUrl}/${subscriptionId}/resourceGroups/${resourceGroup}/providers/${md}/${rn[0]}/${service}/${rn[1]}` +
-        `/providers/microsoft.insights/metricdefinitions?api-version=${apiVersion}&metricnamespace=${encodeURIComponent(
-          metricNamespace
-        )}`
-      );
+    var metricDefinitionArray = metricDefinition.split('/');
+    const resourceNameArray = resourceName.split('/');
+    const provider = metricDefinitionArray.shift();
+    var urlArray = [baseUrl, subscriptionId, 'resourceGroups', resourceGroup, 'providers', provider];
+    for (var i in metricDefinitionArray) {
```
Comment (joshhunt) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts:35]: `var` -> `const`

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts [hunk 3]
```diff
@@ -7,20 +7,16 @@ export default class UrlBuilder {
...
-        `${baseUrl}/${subscriptionId}/resourceGroups/${resourceGroup}/providers/${md}/${rn[0]}/${service}/${rn[1]}` +
-        `/providers/microsoft.insights/metricNamespaces?api-version=${apiVersion}`
-      );
+    var metricDefinitionArray = metricDefinition.split('/');
+    const resourceNameArray = resourceName.split('/');
+    const provider = metricDefinitionArray.shift();
+    var urlArray = [baseUrl, subscriptionId, 'resourceGroups', resourceGroup, 'providers', provider];
+    for (var i in metricDefinitionArray) {
+      urlArray.push(metricDefinitionArray[i]);
+      urlArray.push(resourceNameArray[i]);
```
Comment (joshhunt) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts:16]: On first glance this seems like an opportunuty for bugs - this relies on the resource name and metric namespace having the same number of 'levels', otherwise either we'll get undefined in the URL or miss out on segments. 

in practice this might be fine though - not sure what to do about this...

**Review by joshhunt — COMMENTED** [review]
Thanks for contributing, and a thorough one at that!

First just some style nits to get some early feedback before I take more of a look at this.

> it does also expose another issue as the actual getting of the metrics returns a 404.

I suspect this might be basically the same issue (url not supporting the additional 'levels' in the resource type), but for the actual metrics query url. Azure Monitor is a "backend datasource", so I believe that's built in https://github.com/grafana/grafana/blob/master/pkg/tsdb/azuremonitor/url-builder.go, but I havent looked much into this yet.

If this is all basically the same issue, I think it makes most sense to fix it all in the same PR 😃

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts (hunk 1 above)
Comment (pckls) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts:14]: https://www.typescriptlang.org/docs/handbook/variable-declarations.html#const-declarations
>This should not be confused with the idea that the values they refer to are immutable.

Aha, that's exactly the misunderstanding I had, thanks!

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts (hunk 3 above)
Comment (pckls) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts:16]: Yep, 100% agree and was sort of included in my comment about input validation. I think this same issue applies with the current code though, not that it's an excuse but I was just not sure how far to go with this :)

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts (hunk 1 above)
Comment (pckls) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts]: I have now fixed the datasource url builder as well :)

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts (hunk 3 above)
Comment (pckls) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts:16]: This is the only thing outstanding, I guess I would just check for equality of size and throw an error if they don't match? I guess we would want to assert that the size should be at least 1, not sure if an upper bound matters.

**Comment by joshhunt** [comment]
Hey @pckls - Sorry for dropping the ball on this PR.

If you can rebase this with main and push it up, we can take a look at getting this in for the 8.0 release.

Cheers!

**Comment by pckls** [comment]
> Hey @pckls - Sorry for dropping the ball on this PR.
> 
> If you can rebase this with main and push it up, we can take a look at getting this in for the 8.0 release.
> 
> Cheers!

Sorry @joshhunt I also dropped the ball, saw the email about Grafana 8.0 and realised I forgot all about this!

**Comment by pckls** [comment]
@joshhunt I think this is good to go now :)

**Review by joshhunt — APPROVED** [review]
I don't have access to NetApp resources in our test account, so I'm not able to test this super thoroughly that it solves the problem, but everything else looks good

**Comment by seanluce** [comment]
I've just tested Grafana version 8.0.3 and this issue with Azure NetApp Files volumes still persists. @pckls, I have an Azure Sub with Azure NetApp Files. Could we take a look at this some time?

**Comment by seanluce** [comment]
@joshhunt If you can share your Azure SubID, I can have Azure NetApp Files enabled for you if that would help with testing. Please email me: b-sluce@microsoft.com and I can take care of that for you.

**Comment by joshhunt** [comment]
@seanluce Unfortunately it looks like this wasn't backported so I don't think this actually went out in a patch release - I'll have to double check.

I'll check about getting NetApp Files enabled 👍🏻

**Comment by pckls** [comment]
The milestone is set for 8.1.0, is that why it wasn't in 8.0.3 or 8.0.4?

**Comment by smijithps** [comment]
Checked on 8.0.6 and its still not fixed.

**Comment by joshhunt** [comment]
Apologises for the confusion on this.

This should be included in the 8.1 release, in beta 1/2 which just went out.
