### PR TITLE
Elasticsearch: Fix query initialization logic & query transformation from Prometheus/Loki

### LINKED ISSUE #31300: Elasticsearch: Transform prometheus query to elasticsearch query does not work
**What happened**:
https://github.com/grafana/grafana/pull/23670 added transform prometheus query to elastic search query functionality. However, I have tested it today (7.4.2) and it seems that it is not working.  Secondly, I don't think we have documentation or examples for this feature.

**What you expected to happen**:
When switching from prometheus to elastic, queries should be imported. 

**How to reproduce it (as minimally and precisely as possible)**:

https://user-images.githubusercontent.com/30407135/108267970-2ec4fb00-716c-11eb-9c20-af8f928a4d79.mov

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.2

### PR DESCRIPTION
**Pull request by Elfo404**
**What this PR does / why we need it**:
Before the react refactoring, when switching from a prometheus or loki datasource to Elasticsearch in explore, we were generating  logs query. While this was still happening, the new query initialization logic was overwriting those changes.

Additionally, everytime we were switching from *ANY* datasource to elasticsearch we were creating a log query, which is what most users probably want when switching from prometheus/loki, but not from other datasources.

**Which issue(s) this PR fixes**:

Fixes #31300

**Special notes for your reviewer**:
I changed a bit the initialization logic, this should be 100% compatible with what we had before, but it needs a bit of testing to be sure.

I'll also create an issue and a follow-up PR to add documentation for the "transform prometheus/loki query to elastic search query functionality"

### CODE REVIEW

File: public/app/plugins/datasource/elasticsearch/language_provider.ts [hunk 1]
```diff
@@ -104,22 +105,32 @@ export default class ElasticsearchLanguageProvider extends LanguageProvider {
...
+   * For every other datasource we just copy the refId and let the query editor initialize a default query.
+   * */
   importQueries(queries: DataQuery[], datasourceType: string): ElasticsearchQuery[] {
     if (datasourceType === 'prometheus' || datasourceType === 'loki') {
       return queries.map((query) => {
-        let prometheusQuery: PromQuery = query as PromQuery;
+        let prometheusQuery = query as PromQuery;
         const expr = getElasticsearchQuery(extractPrometheusLabels(prometheusQuery.expr));
         return {
           isLogsQuery: true,
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/elasticsearch/language_provider.ts:119]: Do we still need `isLogsQuery: true` if we are adding ` type: 'logs'`?

**Review by ivanahuckova — APPROVED** [review]
LGTM!  I have tested Prom -> Elastic and Loki -> Elastic data source switch and it gave me correct query based on previous data source in both cases. I have also looked at older Elastic dashboards to see if there aren't any unexpected results, but all looked good. 👍 for adding and updating tests. 

Good job. :)

File: public/app/plugins/datasource/elasticsearch/language_provider.ts (hunk 1 above)
Comment (Elfo404) [reply public/app/plugins/datasource/elasticsearch/language_provider.ts:119]: I'm not completely sure about it, i'm keeping it to avoid breaking anything, but for sure I'm gonna revisit it now with the BE refactoring. Thanks for pointing that out!
