### PR TITLE
SearchV2 - Fix starred dashboards for new organizations error

### LINKED ISSUE #49613: SearchV2 - Starred Dashboards for new organizations give error on Search Page V2
**What happened**:
- Enable `panelTitleSearch` in your local instance
- Create a new organization
- Go to `http://localhost:3000/org/users?search=open&query=`
- Error` Failed to get dashboard`

I noticed we got an Error:500 when hitting this endpoint 
`http://localhost:3000/api/user/stars`

https://user-images.githubusercontent.com/239999/170271363-0bde3d91-a5e0-4f6b-9021-8d0812622b90.mp4

### PR DESCRIPTION
**Pull request by axelavargas**
**What this PR does / why we need it**:

On the new search page, we were getting an error on the `api/user/stars` endpoint when switching organizations

After this PR

https://user-images.githubusercontent.com/239999/170338502-9d291fea-94e2-4391-9e6e-0f7e00885c3d.mp4

**Which issue(s) this PR fixes**:

Fixes #49613

**Special notes for your reviewer**:
I am not a backender feel free to remove this solution if it doesn't work 🙈

### CODE REVIEW

File: pkg/api/stars.go [hunk 1]
```diff
@@ -27,10 +27,11 @@ func (hs *HTTPServer) GetStars(c *models.ReqContext) response.Response {
 			OrgId: c.OrgId,
 		}
 		err := hs.dashboardService.GetDashboard(c.Req.Context(), query)
-		if err != nil {
-			return response.Error(500, "Failed to get dashboard", err)
+
+		// sometimes we don't find the dashboard because it belongs to a different OrgId that the user is in
```
Comment (ryantxu) [inline pkg/api/stars.go:31]:
```suggestion
		// Grafana admin users may have starred dashboards in multiple orgs.  This will avoid returning errors when the dashboard is in another org
```

**Review by ryantxu — APPROVED** [review]
that is a weird one.  Nice catch.
