### PR TITLE
Prometheus Datasource: Improve Prom query variable editor

### LINKED ISSUE #59559: Template Variables: Query-based. Newlines in query cause silent failure
**What happened**:

See this Loom video:
https://www.loom.com/share/c57c4cfbf6ea40ccbd11b01f727c3037

I'm naturally trying to bend Grafana to my will, so I have a template-var which is query-based, and has a query of reasonable length/complexity, as follows:

```
query_result(
  scalar(
    (sum(grafanacloud_instance_active_series)
    /
    sum(grafanacloud_instance_memory_series)
  )
)
```

Given the complexity I've introduced newlines in order to make it easier to work with.

**BUT** apparently the newlines lead to the query **never actually getting issued/executed.** This is doubly confusing because I **DO** see a "Preview of values" value present, but apparently it's still there and left over from a previous execution, from before I added the newlines 🤯 .

I can tell the query isn't executed, because when I take out all the newlines (and spaces) I get an error message due to a syntax error:

```
query_result(scalar((sum(grafanacloud_instance_active_series)/sum(grafanacloud_instance_memory_series)))
```
> invalid parameter "query": 1:91: parse error: unclosed left parenthesis

Even then, I still see the "Preview of values" populated 🤯🤯. It seems to me we should clear out this "Preview of values" as soon as the query starts failing and stops executing. While it remains it's lying to me, and implying that I will see that value on the dashboard itself for this dash-variable, when in practice I won't see it at all 💔 

Also the Input is exceeding the visual boundaries of the div that it sits inside, which is ugly:
input wider than parent div

**What you expected to happen**:

- Even with newlines, if I have a syntax error in my query code, I should be told that I have a syntax error and asked to fix it
- As soon as the query stops executing (due to syntax error or otherwise) the "Preview of values" should be cleared out.
- The input should not exceed the boundaries set by the parent/ancestor div.

**How to reproduce it (as minimally and precisely as possible)**:
- Use a GrafanaCloud account, which has the `grafanacloud-usage` datasource present
- Create a new dash-var with type "query" and datasource "grafanacloud-usage"
- Paste in the PromQL above, and see the behaviour I'm describing.

**Anything else we should know**:
This is closely related to https://github.com/grafana/grafana/issues/59495 but it is **NOT** a duplicate. This ticket describes separate and additional problems to my previous bug report (and super frustrating ones).

**Environment**:
- Grafana version: [v9.2.7-0f96ed148c (0f96ed148c)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- OS Grafana is installed on: GrafanaCloud
- User OS & Browser: macOS 12.6.1 (21G217), Chrome Version 107.0.5304.110 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by bohandley**
Fixes https://github.com/grafana/grafana/issues/59559 (allow newlines in Prom query result variable query editor)
Fixes https://github.com/grafana/observability-metrics-squad/issues/48

**What is this feature?**
This changes the prometheus query variable editor to a group of selects and inputs to better explain the functions, arguments, and endpoint calls used in the prometheus variable queries.

Previous single input:
Screen Shot 2022-11-05 at 12 16 57 PM

New function select and variable inputs:
Screen Shot 2022-11-05 at 12 17 30 PM

Full proposal [here](https://docs.google.com/document/d/1VsMFjiuug-sbSm5XaQffISsUcyxQ5CeHFAjT-POcIqo/edit).

**Why do we need this feature?**
This is in line with the Grafana 10 goal of "Getting Started." More clarity around creating variables in Prometheus will help onboard new customers.

**Who is this feature for?**
This feature is for anyone using the Prometheus datasource plugin who wants to create template variables.
This is for all users of prometheus datasource plugin, from expert to beginner.

**Special notes for your reviewer**:
1. Please create a prometheus variable in the main branch, for example, `label_names()`
2. Switch to the new branch and open the variable editor to see that the function has been correctly passed to the inputs.
3. Check that the variables are returned.
4. Look for confusing language and readability. Are the tooltips helpful?

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/metric_find_query.ts [hunk 1]
```diff
@@ -47,25 +47,30 @@ export default class PrometheusMetricFindQuery {
...
-        return { text: value };
-      });
-    });
-  }
+  //   return this.datasource.metadataRequest(url, params).then((result: any) => {
+  //     return _map(result.data.data, (value) => {
+  //       return { text: value };
+  //     });
+  //   });
+  // }
```
Comment (itsmylife) [inline public/app/plugins/datasource/prometheus/metric_find_query.ts:73]: Can we remove them totally?

File: public/app/plugins/datasource/prometheus/migrations/variableMigration.ts [hunk 2]
```diff
@@ -0,0 +1,96 @@
+import { PromVariableQuery, PromVariableQueryType as QueryType } from '../types';
+
+const labelNamesRegex = /^label_names\(\)\s*$/;
+const labelValuesRegex = /^label_values\((?:(.+),\s*)?([a-zA-Z_][a-zA-Z0-9_]*)\)\s*$/;
+const metricNamesRegex = /^metrics\((.+)\)\s*$/;
+const queryResultRegex = /^query_result\((.+)\)\s*$/;
```
Comment (itsmylife) [inline public/app/plugins/datasource/prometheus/migrations/variableMigration.ts:6]: Are those all the options that we can use? I remember we can use `scalar()` too.

**Review by itsmylife — COMMENTED** [review]
After I check this locally I will approve it.

File: public/app/plugins/datasource/prometheus/metric_find_query.ts (hunk 1 above)
Comment (itsmylife) [reply public/app/plugins/datasource/prometheus/metric_find_query.ts:73]: I mean the comment lines.

File: public/app/plugins/datasource/prometheus/migrations/variableMigration.ts (hunk 2 above)
Comment (bohandley) [reply public/app/plugins/datasource/prometheus/migrations/variableMigration.ts:6]: While scalar() is a function provided by Prometheus, these are function created by Grafana to list variables. The scalar() function can be used in the query_result() function like so, `query_result(scalar(<some prom query>))`

**Comment by itsmylife** [comment]
This is from one of my existing dashboards. It doesn't seem to handle existing variables properly.
image

**Comment by bohandley** [comment]
> For instance for the "label values" we had this before: image
> 
> After this change we have this: image
> 
> There is no way to get explicitly label values of one metric. Or am I missing something?

Oh! This could cause a problem. I brought Galen's check for the label values endpoint into this work, so if a prometheus datasource doesn't have flavor and version defined in the configuration page, and the flavor and version specified don't have this end point, a user cannot query with this. I think I might have to remove this because it assumes people have configured their datasource page, but they don't have to do that.
Screen Shot 2022-11-29 at 6 15 53 PM
Screen Shot 2022-11-29 at 6 17 32 PM

**Comment by bohandley** [comment]
@itsmylife I think I will have to remove the flavor and version check for that function label_values!

File: public/app/plugins/datasource/prometheus/components/VariableQueryEditor.tsx [hunk 3]
```diff
@@ -0,0 +1,254 @@
...
+
+  useEffect(() => {
+    if (!query) {
+      return;
+    }
+    // Changing from standard to custom variable editor changes the string attr from expr to query
+    const variableQuery = query.query ? migrateVariableQueryToEditor(query.query) : query;
+
+    setExprType(variableQuery.exprType);
+    setLabel(variableQuery.label || '');
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/components/VariableQueryEditor.tsx:55]: probably want to use null coalescing operator instead of boolean OR here?

File: public/app/plugins/datasource/prometheus/migrations/variableMigration.ts [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+    };
+  }
+
+  return queryBase;
+}
+
+// migrate it back to a string with the correct varialbes in place
+export function migrateVariableEditorBackToVariableSupport(QueryVariable: PromVariableQuery): string {
+  switch (QueryVariable.exprType) {
+    case 0: // LabelNames
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/migrations/variableMigration.ts:78]: I think we can use the enum instead of numeric values in this case statement to make things a bit more legible

**Comment by itsmylife** [comment]
@bohandley Thanks for the updates. I have some weird behavior. I select label_values and select a label from the second select component. Then I want to change it but it only shows me the option I choose. Others are gone. Similarly when I type a custom option and then want to change it, it just shows only the option I typed:
image

File: public/app/plugins/datasource/prometheus/components/VariableQueryEditor.tsx [hunk 5]
```diff
@@ -0,0 +1,249 @@
...
+    if (exprType !== QueryType.LabelValues) {
+      return;
+    }
+
+    labelNamesVarQuery(datasource).then((labelNames: Array<{ text: string }>) => {
+      setLabelOptions(labelNames.map(({ text }) => ({ label: text, value: text })));
+    });
+  }, [datasource, exprType]);
+
+  const onChangeWithVariableString = (exprType: number) => {
```
Comment (itsmylife) [inline public/app/plugins/datasource/prometheus/components/VariableQueryEditor.tsx:74]:
```suggestion
  const onChangeWithVariableString = (exprType: QueryType) => {
```

File: public/app/plugins/datasource/prometheus/types.ts [hunk 6]
```diff
@@ -165,3 +166,21 @@ export enum LegendFormatMode {
...
+}
+
+export interface PromVariableQuery extends DataQuery {
+  query?: string;
+  expr?: string;
+  exprType?: PromVariableQueryType;
+  label?: string;
+  metric?: string;
+  varQuery?: string;
+  seriesQuery?: string;
```
Comment (itsmylife) [inline public/app/plugins/datasource/prometheus/types.ts:185]: Should all of those be optional? For instance, I think we always need the `exprType`.

**Review by itsmylife — APPROVED** [review]
LGTM 🚀 
Good work 🎉 
Some nitpicks only.

File: public/app/plugins/datasource/prometheus/migrations/variableMigration.ts [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+  if (labelNames) {
+    return {
+      ...queryBase,
+      exprType: QueryType.LabelNames,
+    };
+  }
+
+  const labelValues = rawQuery.match(labelValuesRegex);
+  if (labelValues) {
+    if (labelValues[2]) {
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/migrations/variableMigration.ts:29]: Maybe assign some variables to the result of the rawQueryMatch like `const [totalMatch,label,metric] = rawQuery.match(labelValuesRegex);` for readability instead of using raw index values

File: public/app/plugins/datasource/prometheus/components/VariableQueryEditor.tsx [hunk 8]
```diff
@@ -0,0 +1,249 @@
...
+              options={labelOptions}
+              width={25}
+              allowCustomValue
+            />
+          </InlineField>
+          <InlineField
+            label="Metric"
+            labelWidth={20}
+            tooltip={
+              <div>
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/components/VariableQueryEditor.tsx:163]: I see this calling label values unless I'm using an old prom version (but both API endpoints appear to work correctly), so I'm not sure this is accurate, additionally I'm not sure the tooltips are an appropriate context for API level documentation, that should be available in the change notes, or the code, but this information presented to users should be oriented towards helping them understand and use this field.

**Review by gtk-grafana — CHANGES_REQUESTED** [review]
I think the tooltips could use a bit more love before I'd be comfortable merging, but otherwise this is looking really good, all of my local dashboards are able to switch between this branch and main without issue.
I'm still wary we're missing bugs, but I see that you picked a release far in the future, which is will give our internal folks a chance to test this out on ops and hopefully catch any remaining bugs before a public release is cut.

Really great work on this, the variable editing in prom was a personal pet peeve of mine, really happy to see this cleaned up!!

File: public/app/plugins/datasource/prometheus/types.ts (hunk 6 above)
Comment (bohandley) [reply public/app/plugins/datasource/prometheus/types.ts:185]: That's true, exprType is required. The other fields are only necessary based on the exprType chosen

File: public/app/plugins/datasource/prometheus/metric_find_query.ts [hunk 9]
```diff
@@ -185,3 +173,21 @@ export default class PrometheusMetricFindQuery {
     });
   }
 }
+
+export function labelNamesVarQuery(datasource: PrometheusDatasource) {
```
[the remark this answers is not in the document]
Comment (bohandley) [reply public/app/plugins/datasource/prometheus/metric_find_query.ts:177]: Nice find! Yes, getTagKeys() isn't very descriptive when we are not calling them tags in the frontend. It is used in Tempo though to get some specific label names, so we'll get a review from them if I change it https://github.com/grafana/grafana/blob/bc93f45e9deb7d6772da2245f4a2dc1fdca8da66/public/app/plugins/datasource/tempo/QueryEditor/ServiceGraphSection.tsx#L32

It totally works for metric_find_query though!

File: public/app/plugins/datasource/prometheus/migrations/variableMigration.ts (hunk 7 above)
Comment (bohandley) [reply public/app/plugins/datasource/prometheus/migrations/variableMigration.ts:29]: This is good, although I can't assign them all inline because totalMatch could be null and I'm getting this error 
```
Type 'RegExpMatchArray | null' must have a '[Symbol.iterator]()' method that returns an iterator.
```
I can assign the label and the metric a variable to make this more readable. Will do!

File: public/app/plugins/datasource/prometheus/components/VariableQueryEditor.tsx (hunk 8 above)
Comment (bohandley) [reply public/app/plugins/datasource/prometheus/components/VariableQueryEditor.tsx:163]: Got it! I'll remove the reference to the api.

**Comment by bohandley** [comment]
> I think the tooltips could use a bit more love before I'd be comfortable merging, but otherwise this is looking really good, all of my local dashboards are able to switch between this branch and main without issue. I'm still wary we're missing bugs, but I see that you picked a release far in the future, which is will give our internal folks a chance to test this out on ops and hopefully catch any remaining bugs before a public release is cut.
> 
> Really great work on this, the variable editing in prom was a personal pet peeve of mine, really happy to see this cleaned up!!

Thank you! I agree the tooltips need need some more love, I am just copying directly form the documentation, which was missing the series functionality. I haven't made the changes to the docs yet, but if we can describe the tooltips for each function more clearly, we can use this for the docs too. https://grafana.com/docs/grafana/latest/datasources/prometheus/template-variables/

Want to meet for tooltip a brainstorming session before next week or during GKO?

File: public/app/plugins/datasource/prometheus/metric_find_query.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (bohandley) [reply public/app/plugins/datasource/prometheus/metric_find_query.ts]: Hi @grafana/observability-traces-and-profiling! I renamed Prometheus function getTagKeys() to getLabelNames(). I can change it back if you like, let me know what you think.

File: public/app/plugins/datasource/prometheus/components/VariableQueryEditor.tsx [hunk 10]
```diff
@@ -0,0 +1,257 @@
...
+              value={label}
+              options={labelOptions}
+              width={25}
+              allowCustomValue
+            />
+          </InlineField>
+          <InlineField
+            label="Metric"
+            labelWidth={20}
+            tooltip={<div>*Optional: returns a list of label values for the label name in the specified metric.</div>}
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/components/VariableQueryEditor.tsx:172]:
```suggestion
            tooltip={<div>Optional: returns a list of label values for the label name in the specified metric.</div>}
```

**Review by gtk-grafana — APPROVED** [review]
Looks awesome to me! I had an insignificant nit-pick, but this is a huge improvement, thanks again for all your hard work on this!

File: public/app/plugins/datasource/prometheus/components/VariableQueryEditor.tsx (hunk 10 above)
Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/components/VariableQueryEditor.tsx:172]: Just that we're using the asterisk to denote required fields, the asterisk in this context is kinda confusing
