### PR TITLE
Trace View: Disallow a span colour that is the same or looks similar to previous colour

### LINKED ISSUE #55431: Trace visualiser can pick the same colour for different services within a trace
**What happened**:
Trace diagrams for two different services (denoted as two different names in the `service.name` resources for the spans) used the same colour for all spans. See attached screenshot.

image

**What you expected to happen**:
Each different service identified by the `service.name` span resource should show spans in a different colour.

**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately, this is not easily reproducable, as other traces with different services did show unique colours for spans from those different services.

Ideally the trace visualising code should ensure that colours picked are sufficiently different as to be independently distinguishable.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Cloud - v9.1.5-0100a6a (0100a6aa96)
- Data source type & version: Grafana Cloud Traces/Tempo
- OS Grafana is installed on: N/A
- User OS & Browser: MacOS, https://www.whatsmybrowser.org/b/YHLEX
- Grafana plugins: Standard GC plugins
- Others:

### PR DESCRIPTION
**Pull request by joey-grafana**
**What is this feature?**

Does not allow a span colour that is the exact same to the previous span colour in the trace view. Also does not allow a span colour that looks very similar to a previous span colour.

**Why do we need this feature?**

Ensures that when the trace view is rendered, span colours will be clearly distinguishable from their siblings.

**Who is this feature for?**

Grafana users with Tempo/Jaeger/Zipkin plugin.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/55431 & https://github.com/grafana/grafana/issues/57198

**Special notes for your reviewer**:

- blue's readability >3 for light and dark mode
Screenshot 2022-11-03 at 13 17 44
Screenshot 2022-11-03 at 13 17 36

- green's readability is great for dark mode but poor for light mode (so purple is the next available colour with readability >3 for light mode)
Screenshot 2022-11-03 at 13 19 31
Screenshot 2022-11-03 at 13 19 24

- for light mode, red is the third colour used as purple was used directly before it

 - for reference
Screenshot 2022-11-03 at 13 10 22
Screenshot 2022-11-03 at 13 09 38

### CODE REVIEW

**Review by adrapereira — APPROVED** [review]
LGTM

File: packages/jaeger-ui-components/src/utils/color-generator.tsx [hunk 1]
```diff
@@ -45,13 +45,40 @@ class ColorGenerator {
...
+      }
+
       this.cache.set(key, i);
     }
     return i;
   }
 
+  getNextIndex(i: number) {
+    // get next index or go back to 0
+    return (i = i + 1 < this.colorsHex.length ? i + 1 : 0);
```
Comment (aocenas) [inline packages/jaeger-ui-components/src/utils/color-generator.tsx:79]: Is the assignment needed here?
