### PR TITLE
Various Panels: Add ability to toggle legend with keyboard shortcut

### LINKED ISSUE #49005: TimeSeries: allow toggling of Legends like w/ Graph (old)
**What happened**:

On the old Graph panel we used to be able to toggle panel legends on or off using the panel popup menu ("More..." → "Toggle legend") or using keyboard shortcuts `pl` for panel legend and `dl` for all dashboards.

We used to use this quite often. Our legends are complicated and they clutter the dashboard so we keep them off.  But sometimes the legend is useful and so it can be toggled on-demand.

**What you expected to happen**:

After migrating to the "Time series" panel, the legend toggle shortcuts listed in the help overlay should continue working.

**How to reproduce it (as minimally and precisely as possible)**:

Compare Graph and Time series panel, when hovering press `p l`, `d l`, or look in the panel menu.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.2

### PR DESCRIPTION
**Pull request by alyssajoyner**
**What this PR does / why we need it**: This PR allows for the toggling of a graph's legend both in the configuration panel, menu dropdown and with keyboard shortcut (`p l` when hovering over the panel). 

Screen Shot 2022-07-25 at 10 00 32 AM

Screen Shot 2022-07-14 at 3 48 19 PM

Fixes #49005 

**Special notes for your reviewer**: The designs for this PR are in review by the UX team.

### CODE REVIEW

**Comment by codeincarnate** [comment]
Just a note so it's not forgotten, assuming you stick with configuration change route going to need to make sure this has a migration for that.

File: public/app/core/services/keybindingSrv.ts [hunk 1]
```diff
@@ -283,14 +297,14 @@ export class KeybindingSrv {
...
-      }
-    });
+    // this.bindWithPanelId('p l', (panelId) => {
+    //   const panelInfo = dashboard.getPanelInfoById(panelId)!;
+
+    //   if (panelInfo.panel.legend) {
+    //     panelInfo.panel.legend.show = !panelInfo.panel.legend.show;
+    //     panelInfo.panel.render();
+    //   }
+    // });
```
Comment (dprokop) [inline public/app/core/services/keybindingSrv.ts:307]:
```suggestion
```

File: packages/grafana-schema/src/schema/mudball.cue [hunk 2]
```diff
@@ -128,7 +128,11 @@ GraphThresholdsStyleConfig: {
 LegendPlacement: "bottom" | "right" @cuetsy(kind="type")
 
 // TODO docs
-LegendDisplayMode: "list" | "table" | "hidden" @cuetsy(kind="enum")
+LegendDisplayMode: "list" | "table" @cuetsy(kind="enum")
+
+// TODO docs
+
+LegendVisibility: "visible" | "hidden" @cuetsy(kind="enum")
```
Comment (dprokop) [inline packages/grafana-schema/src/schema/mudball.cue:135]: Not sure I understand why we need this new enum. Can't we rely on the `LegendDisplayMode`? Think it would be better given that this change implicates a need for migration.

File: public/app/features/dashboard/components/PanelEditor/OptionsPaneCategoryDescriptor.tsx [hunk 3]
```diff
@@ -28,6 +28,7 @@ export class OptionsPaneCategoryDescriptor {
   addItem(item: OptionsPaneItemDescriptor) {
     item.parent = this;
     this.items.push(item);
+    // console.log(this.items)
```
Comment (dprokop) [inline public/app/features/dashboard/components/PanelEditor/OptionsPaneCategoryDescriptor.tsx:31]:
```suggestion
```

File: packages/grafana-schema/src/schema/mudball.cue (hunk 2 above)
Comment (dprokop) [reply packages/grafana-schema/src/schema/mudball.cue:135]: Damn, I get it - it's probably to make sure that the given legend type(list/table) stays the same when one toggles it back on.

File: packages/grafana-ui/src/options/builder/legend.tsx [hunk 4]
```diff
@@ -11,21 +11,33 @@ export function addLegendOptions<T extends OptionsWithLegend>(
...
+    .addRadio({
+      path: 'legend.showLegend',
+      name: 'Visibility',
+      category: ['Legend'],
+      description: '',
+      defaultValue: LegendVisibility.Visible,
+      settings: {
+        options: [
+          { value: LegendVisibility.Visible, label: 'Visible' },
+          { value: LegendVisibility.Hidden, label: 'Hidden' },
```
Comment (dprokop) [inline packages/grafana-ui/src/options/builder/legend.tsx:34]: I suggest using `addBooleanSwitch` instead and placing it above the Legend Mode option.

**Review by dprokop — COMMENTED** [review]
Left some comments - but forgot to mention that I've tested it and it works as expected, well done!

**Review by codeincarnate — COMMENTED** [review]
This looks really good. I believe it is missing a migration for the legend display mode setting

File: packages/grafana-ui/src/options/builder/legend.tsx [hunk 5]
```diff
@@ -11,21 +11,33 @@ export function addLegendOptions<T extends OptionsWithLegend>(
...
+      name: 'Mode',
       category: ['Legend'],
       description: '',
       defaultValue: LegendDisplayMode.List,
       settings: {
         options: [
           { value: LegendDisplayMode.List, label: 'List' },
           { value: LegendDisplayMode.Table, label: 'Table' },
-          { value: LegendDisplayMode.Hidden, label: 'Hidden' },
+        ],
```
[the remark this answers is not in the document]
Comment (dprokop) [reply packages/grafana-ui/src/options/builder/legend.tsx:22]: +1

File: public/app/features/dashboard/state/DashboardMigrator.ts [hunk 6]
```diff
@@ -777,6 +777,13 @@ export class DashboardMigrator {
       }
     }
 
+    if (oldVersion < 37) {
+      panelUpgrades.push((panel: PanelModel) => {
+        panel.options.legend.showLegend = 'visible';
+        return panel;
+      });
```
Comment (dprokop) [inline public/app/features/dashboard/state/DashboardMigrator.ts:784]: I think we also need a migration for `options.legend.displayMode === LegendDisplayMode.Hidden`. With the migration you've added, all legends will become visible regardless of the `displayMode` settings.

Comment (dprokop) [reply public/app/features/dashboard/state/DashboardMigrator.ts:784]: Actually, it's even weirder. In scenario where legend was previously hidden, the migration is setting the value to `visible` and the display mode is not set at all:

You can reproduce this using the following dashboard:

<details>
<summary>dashboard.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 1175,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "hidden",
          "placement": "bottom",
          "showLegend": "visible"
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "schemaVersion": 36,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Hidden legend migration",
  "uid": "uWgkIagVk",
  "version": 1,
  "weekStart": ""
}
```

</details>

File: public/app/features/dashboard/state/DashboardMigrator.ts [hunk 7]
```diff
@@ -777,6 +777,13 @@ export class DashboardMigrator {
       }
     }
 
+    if (oldVersion < 37) {
+      panelUpgrades.push((panel: PanelModel) => {
+        panel.options.legend.showLegend = 'visible';
```
Comment (dprokop) [inline public/app/features/dashboard/state/DashboardMigrator.ts:782]:
```suggestion
        panel.options.legend.showLegend = LegendVisibility.Visible;
```

File: packages/grafana-ui/src/options/builder/legend.tsx [hunk 8]
```diff
@@ -11,21 +11,33 @@ export function addLegendOptions<T extends OptionsWithLegend>(
...
+      },
+    })
+    .addRadio({
```
Comment (dprokop) [inline packages/grafana-ui/src/options/builder/legend.tsx:25]: Please use a boolean switch instead of radio button. Similar to how we handle boolean options in other panels. Here's Table panel for reference:

image

File: public/app/features/dashboard/state/DashboardMigrator.ts (hunk 6 above)
Comment (dprokop) [reply public/app/features/dashboard/state/DashboardMigrator.ts:784]: Ah, and please add a test for this migration :)

File: packages/grafana-ui/src/options/builder/legend.tsx (hunk 8 above)
Comment (alyssabull) [reply packages/grafana-ui/src/options/builder/legend.tsx:32]: done!

File: public/app/features/dashboard/state/DashboardMigrator.ts [hunk 9]
```diff
@@ -777,6 +777,18 @@ export class DashboardMigrator {
...
+      panelUpgrades.push((panel: PanelModel) => {
+        if (panel.options?.legend && panel.options.legend.displayMode === 'hidden') {
+          panel.options.legend.displayMode! = 'list';
+          panel.options.legend.showLegend! = false;
+        } else {
+          panel.options.legend.showLegend! = true;
+        }
+        return panel;
+      });
+    }
```
Comment (dprokop) [inline public/app/features/dashboard/state/DashboardMigrator.ts:790]: This migration is fine, but I think you haven't bumped the dashboard schema version on line 79 - hence the migration is not kicking in.

Please also add a test for this new migration.

**Review by dprokop — COMMENTED** [review]
@alyssabull I gave it another try and it's super close :) I think when my last comments are resolved we should be good to go! Nice one:)

File: .drone.yml [hunk 10]
```diff
@@ -434,6 +434,22 @@ steps:
   image: grafana/docker-puppeteer:1.0.0
   name: test-a11y-frontend
 - commands:
+<<<<<<< HEAD
```
Comment (codeincarnate) [inline .drone.yml:437]: Uh oh! this probably shouldn't be here 😢

File: public/app/features/dashboard/utils/getPanelMenu.ts [hunk 11]
```diff
@@ -46,6 +47,12 @@ export function getPanelMenu(
     sharePanel(dashboard, panel);
   };
 
+  const onToggleLegend = (event: React.MouseEvent<any>) => {
+    console.log(panel.options.legend)
```
Comment (codeincarnate) [inline public/app/features/dashboard/utils/getPanelMenu.ts:51]: Remove this

File: scripts/drone/steps/lib.star [hunk 12]
```diff
@@ -1,7 +1,22 @@
 load('scripts/drone/vault.star', 'from_secret', 'github_token', 'pull_secret', 'drone_token', 'prerelease_bucket')
 
+<<<<<<< HEAD
```
Comment (codeincarnate) [inline scripts/drone/steps/lib.star:3]: This one too 😢

File: scripts/drone/steps/lib.star [hunk 13]
```diff
@@ -2,6 +2,18 @@ load('scripts/drone/vault.star', 'from_secret', 'github_token', 'pull_secret', '
 
 grabpl_version = 'v2.9.54'
 build_image = 'grafana/build-container:1.5.8'
+=======
```
Comment (codeincarnate) [inline scripts/drone/steps/lib.star:5]: Uh oh! I'm thinking this file shouldn't have any changes

File: .drone.yml [hunk 14]
```diff
@@ -433,6 +433,13 @@ steps:
   failure: always
   image: grafana/docker-puppeteer:1.0.0
   name: test-a11y-frontend
+- commands:
```
Comment (codeincarnate) [inline .drone.yml:436]: I'm pretty sure this shouldn't have any changes relative to main. Looks like something happened here? 🤔

File: pkg/services/secrets/kvstore/plugin_mig.go [hunk 15]
```diff
@@ -76,7 +76,6 @@ func (s *PluginSecretMigrationService) Migrate(ctx context.Context) error {
 				return err
 			}
 		}
-		s.logger.Debug("migrated unified secrets to plugin", "number of secrets", len(allSec))
```
Comment (codeincarnate) [inline pkg/services/secrets/kvstore/plugin_mig.go:79]: Also looks like this shouldn't be modified

**Review by codeincarnate — APPROVED** [review]
LGTM 🥳

**Comment by towolf** [comment]
Thank you very much @alyssabull! Awesome work!
