### PR TITLE
BrowseDashboards: Only remember the most recent expanded folder

### LINKED ISSUE #59543: Search: Folder view can be really slow if there are too many expanded folders
**What happened**:

The Folder view for search does one query for each expanded folder to get the dashboards in that folder. This becomes very slow for someone with a lot of expanded folders (for example https://github.com/grafana/support-escalations/issues/4546 ).

**What you expected to happen**:

Folder view to be more scalable. If there are thousands of expanded folders we shouldn't slow down Grafana to do one query for each. Or give people the ability to collapse all of their folders.

**How to reproduce it (as minimally and precisely as possible)**:

Go to https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&search=open&layout=folders and open the network tab, see that each expanded folder has its equivalent request.

**Anything else we need to know?**:

Happens on new search as well.

**Environment**:
- Grafana version: 9.3.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by joshhunt**
**What is this feature?**

The old Browse Dashboards UI remembers opened folders and automatically loads their children when Browse or Search is opened. If the user has opened many folders, this can saturate the requests the frontend makes and prevents new requests (such as one for the user's search) from completing quickly.

This PR changers the old Browse Dashboards UI to only remember the last folder opened.

**Why do we need this feature?**

So the old Browse Dashboards UI performance does not get worse the more someone uses it.

**Who is this feature for?**

Everyone who isn't using new Browse Dashboards UI

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/59543

**Special notes for your reviewer:**

Becuase this is in the old UI which we no longer dog food, we must manually test this throughly.

This is intended to be backported.

### CODE REVIEW

**Review by ashharrison90 — APPROVED** [review]
couple of nits, otherwise lgtm 👍

**Review by JoaoSilvaGrafana — APPROVED** [review]
Lgtm when I tested it around! Great job!

There was one small thing I noticed that probably doesn't need fixed but just to keep in mind:
1. If you expand a folder "A" -> local storage = "A"
2. Expand folder "B" -> local storage = "B"
3. Collapse "A" -> local storage = null

I think because this is for an older version it doesn't matter so much, but just when we word it as "remember the most recent expanded folder" it is not necessarily true.

**Comment by joshhunt** [comment]
@ashharrison90 @JoaoSilvaGrafana Pushed a change:
 - no longer use the useLocalStorage hook because we only really use the initial value on mount, and we can just call the native browser apis for get/set
 - will only 'forget' the opened folder if it was the most recently opened, to fix the case @JoaoSilvaGrafana reported

**Comment by eledobleefe** [comment]
Hi @joshhunt,
I've found this glitch when opening a folder:
https://github.com/grafana/grafana/assets/65417731/255b6278-35f8-417d-b2f8-3b5525404896

And is the ephemeral updated with the latest change? I can still see what @JoaoSilvaGrafana mentioned 🤔 
https://github.com/grafana/grafana/assets/65417731/fffd39cb-a024-427a-9f69-5e81746c7d66

**Comment by joshhunt** [comment]
Thanks for the test @eledobleefe. My guess is that's not a regression caused by this change, and was just existing funkiness? Thoughts? Either way, I'm not sure we'll block this PR with it...

File: public/app/features/search/page/components/FolderSection.tsx [hunk 1]
```diff
@@ -1,16 +1,15 @@
 import { css } from '@emotion/css';
-import React, { useCallback, useId } from 'react';
+import React, { useCallback, useId, useState } from 'react';
 import { useAsync, useLocalStorage } from 'react-use';
```
Comment (JoaoSilvaGrafana) [inline public/app/features/search/page/components/FolderSection.tsx:3]: Can remove `useLocalStorage` import now

File: public/app/features/search/page/components/FolderSection.tsx [hunk 2]
```diff
@@ -72,6 +76,16 @@ export const FolderSection = ({
...
+
+    if (sectionExpanded) {
+      if (lastExpandedFolder === uid) {
+        window.localStorage.removeItem(SEARCH_EXPANDED_FOLDER_STORAGE_KEY);
+      }
+    } else {
+      window.localStorage.setItem(SEARCH_EXPANDED_FOLDER_STORAGE_KEY, uid);
+    }
+
     setSectionExpanded(!sectionExpanded);
```
Comment (JoaoSilvaGrafana) [inline public/app/features/search/page/components/FolderSection.tsx:89]: Nit: I find it a bit harder to follow code when it uses a prop that's about to change, like here where if the section WAS expanded and is about to no longer be, we remove the item from localStorage.
Could we create a variable before the if `const newSectionExpanded = !sectionExpanded` and just use that in the if and to set it on line 89?
Also the `lastExpandedFolder` variable can just be created inside the first `if` since it's only used there.

**Review by JoaoSilvaGrafana — COMMENTED** [review]
Issue I found seems resolved 👍

**Comment by eledobleefe** [comment]
> Thanks for the test @eledobleefe. My guess is that's not a regression caused by this change, and was just existing funkiness? Thoughts? Either way, I'm not sure we'll block this PR with it...

I've tested again and now I can see the fixed behaviour. Good job! 🎉 
Regarding the 'glitch' thing, I do not think this is a reason to block this PR, although we may need to create an issue that reminds us we should fix it, no?

**Comment by joshhunt** [comment]
@eledobleefe To be honest, we're about to GA the new browse dashboards UI in 9.2, so people won't experience that any more, and I don't think the issue is big enough to warrant a fix + backports.

**Review by JoaoSilvaGrafana — APPROVED** [review]
Lgtm 👍
