### PR TITLE
Fix: cli error message when installing plugin doesn't include helpful…

### LINKED ISSUE #28732: Plugins: Error message when installing plugin doesn't include helpful information
**What happened**:
Installed plugins before Grafana starts and received the following error `Error: ✗ Failed to find requested plugin, check if the plugin_id is correct: 404 not found error`. 

**What you expected to happen**:
Error message to include at least the plugin id, but if possible the version would also be helpful.

**How to reproduce it (as minimally and precisely as possible)**:
1. Use Grafana 6.6.2
2. Install _jdbranham-diagram-panel_ v1.7.1 (which is only supported on Grafana v7.x)

### PR DESCRIPTION
**Pull request by ying-jeanne**
… info

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #28732

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/cmd/grafana-cli/services/api_client.go [hunk 1]
```diff
@@ -28,7 +28,8 @@ func (client *GrafanaComClient) GetPlugin(pluginId, repoUrl string) (models.Plug
 	body, err := sendRequestGetBytes(HttpClient, repoUrl, "repo", pluginId)
 	if err != nil {
 		if errors.Is(err, ErrNotFoundError) {
-			return models.Plugin{}, errutil.Wrap("Failed to find requested plugin, check if the plugin_id is correct", err)
+			return models.Plugin{}, errutil.Wrap(
+				fmt.Sprintf("Failed to find requested plugin, check if the plugin_id: %s is correct", pluginId), err)
```
Comment (aknuds1) [inline pkg/cmd/grafana-cli/services/api_client.go:32]: The colon makes the sentence difficult to understand. I think the following makes for better language. WDYT?
```suggestion
				fmt.Sprintf("Failed to find requested plugin, check if the plugin_id (%s) is correct", pluginId), err)
```

**Comment by ying-jeanne** [comment]
image

**Comment by ying-jeanne** [comment]
bug fixed with test below.
image

**Review by aknuds1 — APPROVED** [review]
