### PR TITLE
Graphite: Use target as name for aliased queries

### LINKED ISSUE #116281: Graphite: Aliased queries not working with math expressions
Graphite's backend mode modifies how Graphite series titles are generated.

Historically, FE mode would set the series title to the target (query). The logic has since been updated to use the tag `name` as the series title (except for when queries originated from alerts).

However, for multi-dimensional aliased queries used in expressions, this is not suitable, as the queries may be indistinguishable from one another. This is actually why alerts use the target instead.

Graphite should be updated to catch aliased queries and ensure the target is used.

### PR DESCRIPTION
**Pull request by aangelisc**
#115588 broke the fix that was introduced in #94563.

To ensure that queries that make use of aliases are still distinguishable and function as expected with math expressions and alerts, when a query is aliased, the aliased target will be used as the series name. This is the same behaviour as for alerts.

For all other queries, the value of the `name` tag will be used as the series name.

Current behaviour reproduction (example [here](https://datasourcedev.grafana-dev.net/d/anvclhk/20228?orgId=1&from=now-6h&to=now&timezone=browser&editPanel=1)):

- Ensure `graphiteBackendMode` feature toggle is enabled.
- Create a dashboard panel with multiple Graphite queries that use aliases (but are different to each other). e.g. `aliasByTags(seriesByTag('name=cpu.usage.beyla.afr0.host1'), 'cpu')` and `aliasByTags(seriesByTag('name=cpu.utilisation.beyla.afr0.host1'), 'cpu')`.
- Add a math expression that operates on the above queries e.g. `$A/$B`.
- Hide the queries and see that `No data` is displayed.

If you run Grafana from this branch and follow the above steps you will see the relevant data.

Fixes #116281

### CODE REVIEW

File: pkg/tsdb/graphite/query.go [hunk 1]
```diff
@@ -200,8 +200,11 @@ func (s *Service) toDataFrames(response *http.Response, refId string, fromAlert
 		return nil, err
 	}
 
+	aliasRegex := regexp.MustCompile(`(alias\(|aliasByMetric|aliasByNode|aliasByTags|aliasQuery|aliasSub)`)
```
Comment (bossinc) [inline pkg/tsdb/graphite/query.go]: Why does `alias(` have a `(` but the other functions do not?

Comment (aangelisc) [reply pkg/tsdb/graphite/query.go]: I wanted to capture the `alias` function individually and the easiest way I could think of without capturing the word itself was to use `alias(`. If you can think of a better regex please lmk because I'm not that great with regex's!

Comment (bossinc) [reply pkg/tsdb/graphite/query.go]: Ohh that makes sense. Would it be reasonable to just have `alias`?
```
aliasRegex := regexp.MustCompile(`(alias)`)
```

Comment (aangelisc) [reply pkg/tsdb/graphite/query.go]: Nah because that will capture if a user has a metric called `alias`

Comment (bossinc) [reply pkg/tsdb/graphite/query.go]: thats a great point. should we then add `(` to all the alias functions here?

Comment (aangelisc) [reply pkg/tsdb/graphite/query.go]: Updated 😊

File: pkg/tsdb/graphite/query.go [hunk 2]
```diff
@@ -24,15 +24,16 @@ import (
 func (s *Service) RunQuery(ctx context.Context, req *backend.QueryDataRequest, dsInfo *datasourceInfo) (*backend.QueryDataResponse, error) {
 	emptyQueries := []string{}
 	graphiteQueries := map[string]struct {
-		req      *http.Request
-		formData url.Values
+		req       *http.Request
```
Comment (adamyeats) [inline pkg/tsdb/graphite/query.go]: As we define this inline twice in the same file, it should probably be it's own `interface` at the top of the file.

Comment (aangelisc) [reply pkg/tsdb/graphite/query.go]: Done

**Review by adamyeats — APPROVED** [review]

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/21213129841)
- Version: 12.4.0-21213129841
