### PR TITLE
Live: Rely on app url for origin check

### LINKED ISSUE #34537: no live updates; /api/live/ws always returns 403
**What happened**:
Logs like this and the live updates never get started:

```
[grafana] t=2021-05-20T16:02:11-0700 lvl=info msg="Request Completed" 
     logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=403 
     remote_addr=10.42.0.253 time_ms=0 size=10 referer=
```

**What you expected to happen**:
Probably a status=101 on that request, but definitely for live updating to work.

**How to reproduce it (as minimally and precisely as possible)**:
grafana-8.0.0-beta2 from `https://packages.grafana.com/oss/deb beta`
with grafana.ini like this:

```
[paths]
data = /opt/grafana
plugins = /opt/plugins

provisioning = /opt/grafana/provisioning

[server]

http_port = 9067

root_url = https://bigasterisk.com/grafana/

router_logging = true

enable_gzip = false

[database]
type = sqlite3
path = /opt/grafana/grafana.db

[session]

[analytics]
reporting_enabled = true

check_for_updates = false

[security]

disable_gravatar = true

allow_embedding = true

[snapshots]
external_enabled = false

[users]
allow_sign_up = false

allow_org_create = false

[auth]
disable_login_form = true

[auth.anonymous]
enabled = true

org_role = Admin

[auth.basic]
enabled = false

[log]
mode = console

level = debug

filters = live:debug

[event_publisher]

[alerting]
execute_alerts = false

[metrics]
enabled           = true

[grafana_net]

[external_image_storage]

[external_image_storage.s3]

[external_image_storage.webdav]
```

My ingress setup deals with logins before we get to grafana. There may be some x-* headers set, but I think no other auth headers make it down.

Startup looks like this:
```

[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="Starting Grafana" logger=server version=8.0.0-beta2 commit=9d4c719205 branch=HEAD compiled=2021-05-20T02:51:41-0700
[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="Path Data" logger=settings path=/opt/grafana
[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="Path Logs" logger=settings path=/usr/share/grafana/data/log
[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="Path Plugins" logger=settings path=/opt/plugins
[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="Path Provisioning" logger=settings path=/opt/grafana/provisioning
[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="App mode production" logger=settings
[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
[grafana] t=2021-05-20T16:09:12-0700 lvl=warn msg="SQLite database file has broader permissions than it should" logger=sqlstore path=/opt/grafana/grafana.db mode=-rw-r--r-- expected=-rw-r-----
[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="Starting DB migrations" logger=migrator
...
[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="migrations completed" logger=migrator performed=0 skipped=327 duration=5.083708ms
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="Ensuring main org and admin user exist" logger=sqlstore
[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="Starting plugin search" logger=plugins
...
[grafana] t=2021-05-20T16:09:12-0700 lvl=warn msg="Some plugin scanning errors were found" logger=plugins errors="plugin 'petrslavotinek-carpetplot-panel' is unsigned, plugin 'natel-discrete-panel' is unsigned"
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="Registering backend plugin" logger=plugins.backend pluginId=testdata
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="Backend plugin registered" logger=plugins.backend pluginId=testdata
[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="Telemetry Gateway initialization" logger=live.push_http
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="Looking for plugin provisioning files" logger=provisioning.plugins path=/opt/grafana/provisioning/plugins
[grafana] t=2021-05-20T16:09:12-0700 lvl=eror msg="Failed to read plugin provisioning files from directory" logger=provisioning.plugins path=/opt/grafana/provisioning/plugins error="open /opt/grafana/provisioning/plugins: no such file or directory"
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="Looking for alert notification provisioning files" logger=provisioning.notifiers path=/opt/grafana/provisioning/notifiers
[grafana] t=2021-05-20T16:09:12-0700 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/opt/grafana/provisioning/notifiers error="open /opt/grafana/provisioning/notifiers: no such file or directory"
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="GrafanaLive initialization" logger=live
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg=initing logger=tsdb.cloudwatch
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="Registering backend plugin" logger=plugins.backend pluginId=cloudwatch
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="Backend plugin registered" logger=plugins.backend pluginId=cloudwatch
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="NOTIFY_SOCKET environment variable empty or unset, can't send systemd notification" logger=server
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="Waiting on services..." logger=server
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="Looking for app dashboard updates" logger=plugindashboards
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="No image renderer found/installed. For image rendering support please install the grafana-image-renderer plugin. Read more at https://grafana.com/docs/grafana/latest/administration/image_rendering/" logger=rendering
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="Stopped PluginDashboardService" logger=server reason=nil
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="Found old rendered file to delete" logger=cleanup folder=/opt/grafana/png deleted=0 kept=0
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="Found old rendered file to delete" logger=cleanup folder=/opt/grafana/csv deleted=0 kept=0
[grafana] t=2021-05-20T16:09:12-0700 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:9067 protocol=http subUrl=/grafana socket=
[grafana] t=2021-05-20T16:09:12-0700 lvl=dbug msg="Start walking disk" logger=provisioning.dashboard type=file name=default path=/opt/grafana/dashboards
[grafana] t=2021-05-20T16:09:17-0700 lvl=dbug msg="Start walking disk" logger=provisioning.dashboard type=file name=default path=/opt/grafana/dashboards
[grafana] t=2021-05-20T16:09:19-0700 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=403 remote_addr=10.42.0.253 time_ms=1 size=10 referer=

```

### PR DESCRIPTION
**Pull request by FZambia**
**What this PR does / why we need it**:

At this moment we follow same origin strategy for WS connections, in current implementation this requires request Host to be properly set. Unfortunately this means that HTTP Host header should be properly passed on load balancer level (keeping port part, for example using `$http_host` Nginx variable). Here we change the check function to look at AppURL (`root_url` in configuration) for origin check - thus all requests from browsers using public URL should be authorized by Live.

**Which issue(s) this PR fixes**:

Fixes #34537

### CODE REVIEW

**Review by wbrowne — APPROVED** [review]
LGTM!

Was just thinking would it be simpler to pass the `AppURL` as part of the `WebsocketConfig` instead?  But maybe that's mixing concerns - don't have enough context to fully judge

**Comment by FZambia** [comment]
> Was just thinking would it be simpler to pass the AppURL as part of the WebsocketConfig instead?

One of 2 WebsocketConfig is part of Centrifuge lib - it accepts `CheckOrigin` func only, so passing  AppURL is not possible for it.

File: pkg/services/live/live.go [hunk 1]
```diff
@@ -277,6 +290,23 @@ func (g *GrafanaLive) Init() error {
 	return nil
 }
 
+func checkOrigin(r *http.Request, appURL *url.URL) bool {
```
Comment (ryantxu) [inline pkg/services/live/live.go:293]: My only concern is when appURL = "localhost:3000"

This usually means that the appURL was not actually configured.  In the frontend, we decided to just use the browser URL rather than having an error that everyone needs to fix.  Can we do the same here?  essentially skip verification if it is not specified?

Comment (FZambia) [reply pkg/services/live/live.go:293]: `localhost:3000` will work since if `root_url` not configured then appURL is `http://localhost:3000/`.

Approach in this pr won't work if `root_url` set to sth like `https://mygrafana.example.com` but user tries to open `http://localhost:3000/` which is an actual upstream behind `https://mygrafana.example.com`.

In theory we can skip check if Origin starts with `http://localhost:` - in this case I can only imagine a case where a user can hijack WS connection for it's own account only. But this won't help a lot with cases where Grafana instance is accessed over ip: like `127.0.0.1:3000` or `10.0.0.1:3000` etc.

**Review by ryantxu — APPROVED** [review]

**Comment by marefr** [comment]
@FZambia this and the backport PR lacks a milestone which is important to keep track of which changes went into which release, Please assign milestone.
