### PR TITLE
Elasticsearch: Prevent pipeline aggregations to show up in terms order by options

### LINKED ISSUE #37849: Elasticsearch: Bucket script in term order by is not showing any results in grafana 8.0.6
**What happened**:  Bucket script in term order by is not showing any results in grafana 8.0.6 with elasticsearch data source

**What you expected to happen**: Order by Bucket script should show the results based on bucket script in the stats panel

**How to reproduce it (as minimally and precisely as possible)**:

1.Prepare Bucket script based on fields calculations in the series description
2.Use group by {field_name} and order by {Bucket Script}
3.Check query inspector error and error message on the stats panel
 
For more details check on community: https://community.grafana.com/t/elasticsearch-should-not-be-possible-to-use-bucket-script-in-term-order-by-in-grafana-8-0-6/51588?u=anghanbhoomika

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: Elasticsearch and 7.10.0
- OS Grafana is installed on: Red Hat Enterprise Linux 8.2 (Ootpa)
- User OS & Browser: Windows 10 and google chrome

### PR DESCRIPTION
**Pull request by Elfo404**
**What this PR does / why we need it**:
as per https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-order Pipeline aggregations can't be used for sorting. this PR filters out any pipeline aggregation from the order by select in the terms aggregations.

**Which issue(s) this PR fixes**:
Fixes #37849

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/datasource/elasticsearch/components/QueryEditor/BucketAggregationsEditor/utils.ts [hunk 1]
```diff
@@ -123,6 +124,8 @@ const INCOMPATIBLE_ORDER_BY_AGGS = ['top_metrics'];
 export const createOrderByOptionsFromMetrics = (metrics: MetricAggregation[] = []): OrderByOption[] => {
   const metricOptions = metrics
     .filter((metric) => !INCOMPATIBLE_ORDER_BY_AGGS.includes(metric.type))
+    // pipeline aggregations can't be used for sorting: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-order
```
Comment (ifrost) [inline public/app/plugins/datasource/elasticsearch/components/QueryEditor/BucketAggregationsEditor/utils.ts:127]: nitpick: It seems like both filters do similar thing (removing incompatible metrics), it could read a bit better if it was a single `.filter()` callback.

**Review by ifrost — APPROVED** [review]

**Comment by ifrost** [comment]
testing-cat

File: public/app/plugins/datasource/elasticsearch/components/QueryEditor/BucketAggregationsEditor/utils.ts (hunk 1 above)
Comment (Elfo404) [reply public/app/plugins/datasource/elasticsearch/components/QueryEditor/BucketAggregationsEditor/utils.ts:127]: i actually used a different filter because I thought it read better 🤔 

btw, i should add some tests, i wanted to create a draft PR but clicked on open without thinking :D

File: public/app/plugins/datasource/elasticsearch/components/QueryEditor/BucketAggregationsEditor/utils.ts [hunk 2]
```diff
@@ -70,67 +66,3 @@ export const sizeOptions = [
   { label: '15', value: '15' },
   { label: '20', value: '20' },
 ];
-
```
Comment (Elfo404) [inline public/app/plugins/datasource/elasticsearch/components/QueryEditor/BucketAggregationsEditor/utils.ts:73]: moved the following in the only file they were actually being used

File: public/app/plugins/datasource/elasticsearch/components/QueryEditor/BucketAggregationsEditor/SettingsEditor/TermsSettingsEditor.test.tsx [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+import React from 'react';
+import { renderWithESProvider } from '../../../../test-helpers/render';
+import { Average, Derivative, TopMetrics } from '../../MetricAggregationsEditor/aggregations';
+import { Terms } from '../aggregations';
+import { TermsSettingsEditor } from './TermsSettingsEditor';
+import selectEvent from 'react-select-event';
+import { describeMetric } from 'app/plugins/datasource/elasticsearch/utils';
+
+describe('Terms Settings Editor', () => {
+  it('Pipeline aggregations should not bein  order by options', () => {
```
Comment (ifrost) [inline public/app/plugins/datasource/elasticsearch/components/QueryEditor/BucketAggregationsEditor/SettingsEditor/TermsSettingsEditor.test.tsx:12]:
```suggestion
  it('Pipeline aggregations should not be in "order by" options', () => {
```

**Review by ifrost — APPROVED** [review]
