### PR TITLE
Transformations: Allow Timeseries to table transformation to handle multiple time series

### LINKED ISSUE #76291: Transformations: TimeseriesToTable Transformation Error with Multiple Timeseries
### What happened?

The TimeSeriesToTable transformation does not work as expected with more than one series being returned. This has been tested with multiple other combinations of metrics, namespaces, etc. When a query is returning one time series, the transformation will work as expected and show a sparkline for the series when the cell type is auto or sparkline. When a query returns greater than one series, the transformation does not work correctly, and shows "no data" in the table format, or other broken displays.
No transformation applied, one series returned:
image
Transformation applied, one series returned:
image
No transformation applied, multiple series returned:
image
Transformation applied, multiple series returned. No timeseries to table conversion occurs and no sparklines are shown, with corrupted data as well:
image

### What did you expect to happen?

The expected behavior is to see sparkline data in a table format for all of the timeseries returned from a query, much like how the data for a singular returned series is currently displayed.

### Did this work before?

Unsure, this is our first time testing this ability

### How do we reproduce it?

1. Create any query that returns one series and apply the timeseries to table transformation, with a cell type of sparkline. Note the table shows as expected
2.  Alter the query so that multiple series are returned. Note that displays such as "no data" for series which clearly have data in a normal time series will appear, and no sparklines will be shown

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: v10.0.2
OS: Windows 11
Browser: Edge

### Grafana platform?

Docker

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by codeincarnate**
**What is this feature?**

This PR extends the capabilities of the _Timeseries to table transformation_ to support multiple time series, even if those time series are embedded within a single data series. That is, it will be able to use a time field in combination with number fields and labeled data to breakdown time series data into distinct table rows.

Additionally, this also handles the case in which multiple series are present. Currently it doesn't modify multiple series which is actually a departure in behavior from how this transform worked previously in which multiple series would be mapped to a single one (i.e. even with multiple series the series selector for the table wouldn't appear). 

I'm currently planning on adding an option (and making it the default) in order to preserve this behavior. However, it feels like we should update this in the future as currently multiple data series in the table panel will show a series selector. The default behavior of this transformation breaks that underlying structure

Beyond that, it currently assumes that the first time field found is the one that should be used to determine the time series. This isn't necessarily correct, and it's quite possible multiple time series could be present in the incoming data (e.g. created times vs update times for records is a straightforward example). I'll be adding an option for that.

**Why do we need this feature?**

This significantly enhances the capabilities of the Timeseries to table transformation to handle multiple data scenarios. In particular it should allow for this transformation to work across time series datasources, as well as other data sources with time data (e.g. SQL, App Analytics, etc.). This will allow multiple time series datums to be displayed together in a straightforward manner.

**Who is this feature for?**

Users that have multiple time series frames being returned from a single datasource.

**Which issue(s) does this PR fix?**:

Fixes #76291

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by codeincarnate** [comment]
Have this mostly working at this point. Working on one bug in which merging off all series from multiple queries isn't working right. Think I know how to solve that one.

**Comment by codeincarnate** [comment]
Did some cleanups and fixes and also fixed the test as the overall output has changed. Taking this out of draft so feedback can be incorporated. As far as I know the main thing missing at this point is a migration for the transformation settings.

File: public/app/features/transformers/timeSeriesTable/TimeSeriesTableTransformEditor.tsx [hunk 1]
```diff
@@ -1,56 +1,102 @@
...
-                />
-              </InlineField>
-            </InlineFieldRow>
-          </div>
-        );
-      })}
-    </>
+  const onMergeSeriesToggle = useCallback(
+    (refId: string) => {
+      console.log(options);
```
Comment (baldm0mma) [inline public/app/features/transformers/timeSeriesTable/TimeSeriesTableTransformEditor.tsx:56]: console.log

File: public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.ts [hunk 2]
```diff
@@ -11,18 +10,72 @@ import {
   isTimeSeriesFrame,
   ReducerID,
   reduceField,
+  TransformationApplicabilityLevels,
 } from '@grafana/data';
 
+const MERGE_DEFAULT = true;
+
+/**
```
Comment (baldm0mma) [inline public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.ts:18]: Love these docs!

**Review by baldm0mma — APPROVED** [review]
Looks great!

File: public/app/features/transformers/timeSeriesTable/TimeSeriesTableTransformEditor.tsx [hunk 3]
```diff
@@ -1,56 +1,115 @@
...
+    [onChange, options]
   );
+
+  let configRows = [];
+  for (const refId of Object.keys(refIdMap)) {
+    configRows.push(
+      <InlineFieldRow key={refId}>
+        <InlineField
+          label="Time Field"
+          tooltip="The the time field that will be used for the time series. If not selected the first found will be used."
```
Comment (mdvictor) [inline public/app/features/transformers/timeSeriesTable/TimeSeriesTableTransformEditor.tsx:84]: small typo here

**Comment by mdvictor** [comment]
I'm not sure, but it looks like there's some weird behaviour with the merge switch. I think the selected stat should not change, and the switch also looks like it's auto enabling on stat change.

https://github.com/grafana/grafana/assets/36818606/6dca6e91-59eb-41dd-bbe8-bf62499c5422

**Review by mdvictor — CHANGES_REQUESTED** [review]
Works well! Left a few comments regarding the UI and I think I don't understand the merging well and need a bit of help figuring that out, please. :D

**Comment by codeincarnate** [comment]
That's a weird one with the merge switching back it shouldn't 😢

File: public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.ts [hunk 4]
```diff
@@ -37,101 +90,179 @@ export const timeSeriesTableTransformer: DataTransformerInfo<TimeSeriesTableTran
...
-    if (!frameField) {
-      frameField = {
-        name: 'Trend' + (refId && Object.keys(refId2LabelFields).length > 1 ? ` #${refId}` : ''),
-        type: FieldType.frame,
-        config: {},
-        values: [],
-      };
-      refId2frameField[refId] = frameField;
+    // Get the frames with the current refId
+    const framesForRef = data.filter((frame) => frame.refId === refId);
```
[the remark this answers is not in the document]
Comment (codeincarnate) [reply public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.ts:123]: It should show two distinct rows, that's correct! If you don't merge them you should get a series selector for the table with one row in each series.

refId is unique to the query not the frame, as a single query can return multiple frames. This will get all the frames for a single query and proceed from there

Currently, merging is only done per query and not for all frames but it might not be a bad idea to have a "merge all" option 😄

[the remark this answers is not in the document]
Comment (mdvictor) [reply public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.ts:123]: right! thanks, got it working now. I was definitely doing something wrong the first time around.

**Comment by codeincarnate** [comment]
I found the problem, the options for other frames were being copied but not the options for the frame being modified 😭. That being said this should be fixed now 😄

**Review by mdvictor — APPROVED** [review]
Tested out the changes and LGTM!

**Comment by codeincarnate** [comment]
Currently looking into the GenAI tests failures so I don't blow up something important there. Otherwise though I _think_ this is mostly ready to go.

**Comment by torkelo** [comment]
@codeincarnate would have been good if @domasx2 had reviewed this it looks to be a breaking change For app11y app that uses this

File: public/app/features/dashboard/state/DashboardMigrator.ts [hunk 5]
```diff
@@ -849,6 +862,46 @@ export class DashboardMigrator {
       });
     }
 
+    // Update the configuration of the Timeseries to table transformation
+    // to support multiple options per query
+    if (oldVersion < 39) {
+      panelUpgrades.push((panel: PanelModel) => {
```
Comment (torkelo) [inline public/app/features/dashboard/state/DashboardMigrator.ts:868]: We cannot rely on this type of migration now, transforms are used from app plugins. Need to figure out how to have these migrations be part of the transformation runner

**Comment by torkelo** [comment]
Ah, see we have https://github.com/grafana/grafana/pull/77415 already :+1:

File: public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.test.ts [hunk 6]
```diff
@@ -51,15 +52,23 @@ describe('timeSeriesTableTransformer', () => {
...
     expect(results[0].refId).toBe('A');
     expect(results[0].fields).toHaveLength(3);
-    expect(results[0].fields[0].values).toEqual(['A', 'A', 'A']);
-    expect(results[0].fields[1].values).toEqual(['B', 'C', 'D']);
-    assertDataFrameField(results[0].fields[2], series.slice(0, 3));
+    expect(results[0].fields[0].values).toEqual([
+      'Value : instance=A : pod=B',
+      'Value : instance=A : pod=C',
+      'Value : instance=A : pod=D',
+    ]);
```
Comment (torkelo) [inline public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.test.ts:59]: @codeincarnate this looks like a very strange and big breaking change, the transform created separate fields, and now it's just some value inside a string?

File: public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.test.ts [hunk 7]
```diff
@@ -33,8 +36,6 @@ describe('timeSeriesTableTransformer', () => {
     expect(results[0]).toEqual(series[0]);
     expect(results[1].refId).toBe('A');
     expect(results[1].fields).toHaveLength(3);
-    expect(results[1].fields[0].values).toEqual(['A', 'A']);
-    expect(results[1].fields[1].values).toEqual(['B', 'C']);
```
Comment (torkelo) [inline public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.test.ts:37]: ?

**Review by torkelo — COMMENTED** [review]
@codeincarnate I could not find any new tests that cover the new behavior, only modified tests that show a very big change in behavior from before, so hard to understand what the goal was here.

File: public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.ts [hunk 8]
```diff
@@ -11,18 +10,72 @@ import {
...
+ * For each refId we allow the following to
+ * be configured:
+ *
+ *  - stat: A stat to calculate for the refId
+ *  - mergeSeries: Whether separate series should be merged into one
+ *  - timeField: The time field that should be used for the time series
+ */
+export interface RefIdTransformerOptions {
+  stat?: ReducerID;
+  mergeSeries?: boolean;
```
Comment (torkelo) [inline public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.ts:59]: not sure this option makes sense

**Comment by codeincarnate** [comment]
Definitely a miss on this on my part, there were some parts of the original behavior I misunderstood. Working with @domasx2 on this now.

File: public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.ts (hunk 8 above)
Comment (codeincarnate) [reply public/app/features/transformers/timeSeriesTable/timeSeriesTableTransformer.ts:59]: This was removed 😄
