### PR TITLE
Thresholds: fix line rendering with multiple y axes

### LINKED ISSUE #56459: Filled threshold regions cause individual series selection to fail
**What happened**:
When using the _Time Series_ visualisation with thresholds, individual series selection fails when the _filled regions_ option is selected. 

**What you expected to happen**:
Individual series should display when clicked.

**How to reproduce it (as minimally and precisely as possible)**:
See screen recording:
filled-regions

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.3.0-36287pre (b396f16fe1)
- Data source type & version: Prometheus
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/grafana/issues/56459

this looks like something i missed in the original refactor. without this PR, threshold lines were always drawn using the first/left y axis, but filled areas were drawn correctly :grimacing: 

<details><summary>thresholds-no-axis.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 452,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "line+area"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "B-series"
            },
            "properties": [
              {
                "id": "unit",
                "value": "short"
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 13,
        "w": 11,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "1,20,90,30,5,0"
        },
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "B",
          "scenarioId": "csv_metric_values",
          "stringInput": "25,100,200,700,100,0"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "thresholds-no-axis",
  "uid": "pPJeowVVz",
  "version": 2,
  "weekStart": ""
}
```
</details>

### CODE REVIEW

File: packages/grafana-ui/src/components/uPlot/config/UPlotThresholds.ts [hunk 1]
```diff
@@ -75,12 +75,12 @@ export function getThresholdsDrawHook(options: UPlotThresholdOptions) {
     }
   }
 
-  function addAreas(u: uPlot, steps: Threshold[], theme: GrafanaTheme2) {
+  function addAreas(u: uPlot, yScaleKey: string, steps: Threshold[], theme: GrafanaTheme2) {
     let ctx = u.ctx;
 
     let grd = scaleGradient(
       u,
-      u.series[1].scale!,
```
Comment (leeoniya) [inline packages/grafana-ui/src/components/uPlot/config/UPlotThresholds.ts:83]: this was the actual bug. the rest of the changeset is just cleanup.

**Review by codeincarnate — APPROVED** [review]
Tested out and looks good!

**Comment by leeoniya** [comment]
thanks! 🙏
