### PR TITLE
Azure: Fix logs editor rendering

### LINKED ISSUE #109613: Azure: Logs query editor crashing
The Logs query editor is crashing when a schema with no tables is loaded.

### PR DESCRIPTION
**Pull request by aangelisc**
The Logs query editor has a re-rendering issue when the schema provided has no tables.

This PR rectifies the problem and prevents the infinite re-render. Also, I've added a test for the schema loading. An additional test has been added to the time management component for a schema without tables.

This can be tested by building and running Grafana and connecting to Azure Monitor. Choosing the resource `azmonlogstest` with this branch will succeed. Testing without this branch will lead to the editor crashing.

Fixes #109613

### CODE REVIEW

**Review by bossinc — APPROVED** [review]

File: public/app/plugins/datasource/azuremonitor/components/LogsQueryEditor/TimeManagement.tsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ export function TimeManagement({ query, onQueryChange: onChange, schema }: Azure
       const timeColumnsSet: Set<string> = new Set();
       const defaultColumnsMap: Map<string, SelectableValue> = new Map();
       const db = schema.database;
-      if (db) {
+      if (db && db.tables && db.tables.length > 0) {
```
Comment (adamyeats) [inline public/app/plugins/datasource/azuremonitor/components/LogsQueryEditor/TimeManagement.tsx]:
```suggestion
      if (db?.tables?.length > 0) {
```

**Review by adamyeats — APPROVED** [review]
Small nit, otherwise LGTM 👍
