### PR TITLE
Middleware: Fix IPv6 host parsing in CSRF check

### LINKED ISSUE #45115: New CSRF check broken with raw IPv6 Host
**Summary**:  
The [CSRF fix](https://github.com/grafana/grafana/commit/405654b33f205b903caf04ff9d8ba13e6db7ee39) breaks with IPv6 addresses. This line:
https://github.com/grafana/grafana/blob/a53fcac7b1b7ebda8c0cb18f7ce92788af92fa32/pkg/middleware/csrf.go#L30
splits a host like `[2001:db8::1]` or `[2001:db8::1]:3000` to `[2001`.  
Thus the comparison always fails, and you get "403 origin not allowed" for all datasource proxy routes.

I do not think this is a security vulnerability, as this shouldn't be exploitable. However it does break Grafana when accessed with a raw IPv6 address as host.

As the port in the Host header is optional, `net.SplitHostPort()` wouldn't work either. `url.Parse()` doesn't seem to work without scheme. Instead, maybe checking for `string.HasSuffix("]")`, and if true, don't split at all, if false, split at _last_ colon.  
Then surrounding square brackets need to be stripped as well for the comparison, because `(*URL).Hostname()` [removes them](https://pkg.go.dev/net/url#URL.Hostname).

Also the accompanying code comment is a bit weird, it talks about comparing the origins while the actual check ignores the port (different port->different origin), it's more of a stricter same-site check (disallowing different subdomains, allowing different ports):
https://github.com/grafana/grafana/blob/a53fcac7b1b7ebda8c0cb18f7ce92788af92fa32/pkg/middleware/csrf.go#L29
Maybe `Otherwise - verify that the hostname of the Origin header matches the hostname of the Host header` would fit better?

**What happened**:  
After the upgrade to v8.3.5, all requests to the datasource proxy endpoints (e.g. `/api/datasources/proxy/1/api/v1/series` for Prometheus or `/api/ds/query`) return 403 with `origin not allowed`.  
Thus the dashboard panels stay empty, no nice graphs.

**What you expected to happen**:  
Requests succeed, no 403, dashboards work; like in v8.3.4.

**How to reproduce it (as minimally and precisely as possible)**:  
- Setup Grafana, listening on IPv6.
- Access Grafana using the raw IPv6 address in the browser
- Try to load a dashboard, or e.g. add a new Prometheus datasource and click "Save & Test"

**Anything else we need to know?**:  
In my particular case I didn't access Grafana with the IPv6 address, but through a nginx reverse proxy in front, which then proxies to the raw address llike `proxy_pass http://[::1]:3000;`. Adding `proxy_set_header Host $http_host;` to the nginx config worked around the issue in my case, because it replaces the raw IPv6 Host header with a domain name.

However without this directive, or when accessing Grafana without domain name but a raw IPv6 address, this is still a problem.

**Environment**:
- Grafana version: _v8.3.5_
- Data source type & version: _Prometheus 2.32.1_
- OS Grafana is installed on: _Fedora Linux 35 (Container Image)_
- User OS & Browser: _Kubuntu 21.10, Firefox 96.0_
- Others: _Most of my setup is IPv6-only_

### PR DESCRIPTION
**Pull request by ying-jeanne**
**What this PR does / why we need it**:
Fixes the CSRF middleware to work with IPv6.

**Which issue(s) this PR fixes**:

Fixes #45115

**Special notes for your reviewer**:

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Would definitely need some tests for this to validate it does work as intended/expected. Could we perhaps use the existing [util.SplitHostPortDefault](https://github.com/grafana/grafana/blob/a68a570e921258de735cb60feb863c2087efb23d/pkg/util/ip_address.go#L17)? Think it should work for both IPv4 and IPv6 - something to test/evaluate.

**Comment by kylebrandt** [comment]
FWIW, It does seem to work for me locally, on main I see the console errors about live and "disconnected from server" when using `http://[::1]:3000/?orgId=1`, but okay on this branch.

File: pkg/middleware/csrf.go [hunk 1]
```diff
@@ -27,12 +27,17 @@ func CSRF(loginCookieName string) func(http.Handler) http.Handler {
 				}
 			}
 			// Otherwise - verify that Origin matches the server origin
-			host := strings.Split(r.Host, ":")[0]
+			host, _, err := net.SplitHostPort(r.Host)
```
Comment (kylebrandt) [inline pkg/middleware/csrf.go:30]: Actually this requires a port or will error, so I probably do need the "withdefaults" I guess, and need the cfg to know the port I imagine...

File: pkg/middleware/csrf.go [hunk 2]
```diff
@@ -27,12 +28,21 @@ func CSRF(loginCookieName string) func(http.Handler) http.Handler {
 				}
 			}
 			// Otherwise - verify that Origin matches the server origin
-			host := strings.Split(r.Host, ":")[0]
+			netAddr, err := util.SplitHostPortDefault(r.Host, "", defaultPort)
+			if err != nil {
+				http.Error(w, err.Error(), http.StatusBadRequest)
```
Comment (marefr) [inline pkg/middleware/csrf.go:33]:
```suggestion
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
```

File: pkg/middleware/csrf.go [hunk 3]
```diff
@@ -4,10 +4,11 @@ import (
 	"errors"
 	"net/http"
 	"net/url"
-	"strings"
+
+	"github.com/grafana/grafana/pkg/util"
 )
 
-func CSRF(loginCookieName string) func(http.Handler) http.Handler {
+func CSRF(loginCookieName, defaultPort string) func(http.Handler) http.Handler {
```
Comment (marefr) [inline pkg/middleware/csrf.go:11]: Not sure the `defaultPort` needs to be passed since only used for setting the default and can be hardcoded inside the `CSRF` function maybe?

File: pkg/middleware/csrf.go [hunk 4]
```diff
@@ -27,12 +28,21 @@ func CSRF(loginCookieName string) func(http.Handler) http.Handler {
...
+				http.Error(w, err.Error(), http.StatusBadRequest)
+			}
+
 			origin, err := url.Parse(r.Header.Get("Origin"))
-			if err != nil || (origin.String() != "" && origin.Hostname() != host) {
+			// Possible TODO: If Origin, but malformed, error?
+			// Per url.Parse: The url may be relative (a path, without a host) or absolute (starting with
+			// a scheme). Trying to parse a hostname and path without a scheme is invalid but may not
+			//  necessarily return an error, due to parsing ambiguities.
+			if err != nil || netAddr.Host == "" || (origin.String() != "" && origin.Hostname() != netAddr.Host) {
```
Comment (marefr) [inline pkg/middleware/csrf.go:41]: if `err` not is nil we probably want to log that.

File: pkg/middleware/csrf_test.go [hunk 5]
```diff
@@ -0,0 +1,114 @@
...
+			code:        http.StatusOK,
+		},
+		{
+			name:        "mismatched origin and host is NOT forbidden without a cookie",
+			cookieName:  "",
+			method:      "GET",
+			origin:      "http://notLocalhost",
+			host:        "localhost",
+			defaultPort: "80",
+			code:        http.StatusOK,
```
Comment (marefr) [inline pkg/middleware/csrf_test.go:46]: I'm probably stupid right now, but don't understand how this could be OK when origin and host is different?

File: pkg/middleware/csrf_test.go [hunk 6]
```diff
@@ -0,0 +1,114 @@
...
+		},
+		{
+			name:        "IPv6 host should get default port",
+			cookieName:  "foo",
+			method:      "GET",
+			host:        "[::1]",
+			origin:      "http://[::1]",
+			defaultPort: "3000",
+			code:        http.StatusOK,
+		},
```
Comment (marefr) [inline pkg/middleware/csrf_test.go:81]: Would be nice to add the example IPv6 addresses/port from the [issue](https://github.com/grafana/grafana/issues/45115#issue-1127873033) originally reported to make sure it works for those as well.

File: pkg/middleware/csrf_test.go (hunk 5 above)
Comment (marefr) [reply pkg/middleware/csrf_test.go:46]: A missed the `name` spanning multiple rows :facepalm:

**Review by marefr — CHANGES_REQUESTED** [review]
Some minor things, but looks good in general.

File: pkg/middleware/csrf.go (hunk 3 above)
Comment (kylebrandt) [reply pkg/middleware/csrf.go]: I see for the check we don't use the Port property, so in that sense it makes sense (passing and do nothing could be misleading).

But I'm not clear on all the cases here, for example is sending `Host: "locatlhost:80", and `Origin: "http://localhost" valid if it is on port is 80 (other the other way with schema on origin still)?

If we do want to ignore the port entirely, then can add a comment and some tests that demonstrate a port mismatch is allowed.

File: pkg/middleware/csrf.go [hunk 7]
```diff
@@ -4,10 +4,12 @@ import (
...
 	"net/http"
 	"net/url"
-	"strings"
+
+	"github.com/grafana/grafana/pkg/infra/log"
+	"github.com/grafana/grafana/pkg/util"
 )
 
-func CSRF(loginCookieName string) func(http.Handler) http.Handler {
+func CSRF(loginCookieName, defaultPort string, logger log.Logger) func(http.Handler) http.Handler {
```
Comment (DanCech) [inline pkg/middleware/csrf.go:12]: we don't care about the port and never access netAddr.Port so we should be fine to skip all this and pass defaultPort=0 when calling SplitHostPortDefault

File: pkg/middleware/csrf.go (hunk 3 above)
Comment (marefr) [reply pkg/middleware/csrf.go]: As I understood it we don't care about the port. See also @DanCech comment below.

File: pkg/middleware/csrf.go [hunk 8]
```diff
@@ -27,12 +29,24 @@ func CSRF(loginCookieName string) func(http.Handler) http.Handler {
...
+			}
+
 			origin, err := url.Parse(r.Header.Get("Origin"))
-			if err != nil || (origin.String() != "" && origin.Hostname() != host) {
+			// Possible TODO: If Origin, but malformed, error?
+			// Per url.Parse: The url may be relative (a path, without a host) or absolute (starting with
+			// a scheme). Trying to parse a hostname and path without a scheme is invalid but may not
+			//  necessarily return an error, due to parsing ambiguities.
+			if err != nil {
+				logger.Error("error parsing Origin header", "err", err)
```
Comment (marefr) [inline pkg/middleware/csrf.go:40]: Might want to keep this if as separate from the else and make the else an if so that `StatusForbidden` still is returned if parsing the origin fails. Otherwise this could potentially be exploited to circumvent the CSRF check.

**Review by marefr — APPROVED** [review]
LGTM, but see comment since need to be fixed. We probably would like to resolve the port discussion before merging as well. I have to run now so in case you would like to merge later you can do that :smile:

**Review by DanCech — APPROVED** [review]

File: pkg/middleware/csrf_test.go [hunk 9]
```diff
@@ -0,0 +1,124 @@
...
+func csrfScenario(t *testing.T, cookieName, method, origin, host string) *httptest.ResponseRecorder {
+	req, err := http.NewRequest(method, "/", nil)
+	if err != nil {
+		t.Fatal(err)
+	}
+	req.AddCookie(&http.Cookie{
+		Name: cookieName,
+	})
+
+	// Note: Not sure where host header populates req.Host, or how that works.
```
Comment (kylebrandt) [inline pkg/middleware/csrf_test.go:110]: Anyone know which is right here? 
I use r.Host in the actual CRSF Func, should I get the header instead? Or does it not matter outside of testing?

Comment (zserge) [reply pkg/middleware/csrf_test.go:110]: `go doc` gives some clues:
```
    // For server requests, Host specifies the host on which the
	// URL is sought. For HTTP/1 (per [RFC 7230, section 5.4](https://rfc-editor.org/rfc/rfc7230.html#section-5.4)), this
	// is either the value of the "Host" header or the host name
	// given in the URL itself. For HTTP/2, it is the value of the
	// ":authority" pseudo-header field.
	// It may be of the form "host:port". For international domain
	// names, Host may be in Punycode or Unicode form. Use
	// golang.org/x/net/idna to convert it to either format if
	// needed.
	// To prevent DNS rebinding attacks, server Handlers should
	// validate that the Host header has a value for which the
	// Handler considers itself authoritative. The included
	// ServeMux supports patterns registered to particular host
	// names and thus protects its registered Handlers.
	//
	// For client requests, Host optionally overrides the Host
	// header to send. If empty, the Request.Write method uses
	// the value of URL.Host. Host may contain an international
	// domain name.
```
I would keep it as it is now

Comment (kylebrandt) [reply pkg/middleware/csrf_test.go:110]: I did read that but still wasn't sure :-)

Comment (DanCech) [reply pkg/middleware/csrf_test.go:110]: http supports sending host either in the host header or in the request url itself (in which case the host header is ignored), req.Host will be from one or the other depending.  This is fine the way it is imho.
