### PR TITLE
LibraryPanels: Fixes error when importing plugin dashboard

### LINKED ISSUE #34490: LibraryPanels: Import fails for Datasource Dashboards
1. Navigate to http://localhost:3000/datasources
2. Open gdev-prometheus
3. Click on Dashboards tab
image
4. Try importing any of the listed dashboards
5. Fails [Not OK]
image
6. Navigate to imported dashboard
7. Dashboard opens [OK]

This is caused by https://github.com/grafana/grafana/blob/23939eab107443e0dc985195309a7fc732590cce/pkg/api/plugins.go#L229 because when I implemented this I assumed we always had a valid dashboard json passed in the command. Seems like in this case only a path is provided so we need to refactor this.

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
I've tried to figure out the best approach to solve the import for plugin dashboards and this PR tries to solve this. Feels like a better approach than #34556.
This approach that involves changing the interface for plugin manager and I don't know how this affects other parts of the code and any public contributors. 

I tried a third approach where the libraryPanels service was a dependency to PluginManager so we could call `ConnectLibararyPanels` within `PluginManager` but that meant that we needed to pass the RequestContext as param all the way and that seemed troublesome. Any other ideas?

**Which issue(s) this PR fixes**:
Fixes #34490

**Special notes for your reviewer**:

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]
I think this approach looks preferable to the other one, since you're re-using the dashboard object already acquired by `PluginManager.ImportDashboard`. It makes for less complexity, and one less SQL query, both wins in my book.

**Comment by hugohaggmark** [comment]
@marefr @torkelo any implications changing the Plugin Manager api as suggested in this PR?

**Review by marefr — APPROVED** [review]
LGTM

File: pkg/services/librarypanels/librarypanels.go [hunk 1]
```diff
@@ -18,7 +18,6 @@ type Service interface {
 	LoadLibraryPanelsForDashboard(c *models.ReqContext, dash *models.Dashboard) error
 	CleanLibraryPanelsForDashboard(dash *models.Dashboard) error
 	ConnectLibraryPanelsForDashboard(c *models.ReqContext, dash *models.Dashboard) error
-	ImportDashboard(c *models.ReqContext, dashboard *simplejson.Json, importedID int64) error
```
Comment (torkelo) [inline pkg/services/librarypanels/librarypanels.go:21]: ah, this is nice, because I thought when this was added that it feels wrong, that this service needed a special case for this scenario.

**Review by torkelo — APPROVED** [review]
Agree, this feels like the better approach. and getting rid of the ImportDashboard from library  panel service feels like a very good thing

**Comment by hugohaggmark** [comment]
Thanks for all the reviews and feedback!
