### PR TITLE
Datasource/Loki: Fixes issue where cached log values weren't merged when labels were refreshed

### LINKED ISSUE #24087: Explore - Loki labels not properly populated
**What happened**:

The "Log labels" drop-down menu in Explore is not properly populated for Loki data source and values become empty after a short timeout.

The only way to restore is to reload the page (changing pages without refresh does not work)

**What you expected to happen**:

The "Log labels" drop-down menu to be always properly populated.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open the Explore pane: `https://grafana/explore`
2. Select a Loki data source
3. Open the "Log labels" drop-down menu
4. Verify that the labels and their values have been properly populated
5. Click outside of the drop-down menu to close it
6. Wait for 10 seconds
7. Open the "Log labels" drop-down menu again
8. Verify that the labels are still there but now no values have been populated (empty)
9. Only way to restore is to reload the page (changing pages without refresh does not work)

**Anything else we need to know?**:

In my setup, I have two labels `app` and `job`. Here is the sequence of API calls from Grafana.

When you open "Log labels" for the first time:
```
/api/datasources/proxy/6/api/prom/label?start=1588241711386000000&end=1588241721386000000
/api/datasources/proxy/6/api/prom/label/job/values?start=1588241711386000000&end=1588241721386000000
/api/datasources/proxy/6/api/prom/label/app/values?start=1588241711445000000&end=1588241721445000000
/api/datasources/proxy/6/api/prom/label/__name__/values?start=1588241711445000000&end=1588241721445000000
```

After `end - start` time passes (from the first `label` API call), which is 10 seconds:
```
/api/datasources/proxy/6/api/prom/label?start=1588241711445000000&end=1588241721445000000
-- no more calls to obtain values again --
```

**Screenshots**:

*Note: some values had to be anonymised as per my company's policies.*

"Log labels" drop-down menu properly populated when opening Explore for the first time:

image

*Log labels* drop-down menu does not have any values for labels anymore after a short timeout psases (10 seconds):

image

Only way to see the labels again is to reload/refresh the page (F5). Changing pages without reloading does not help.

**Environment**:
- Grafana version: `6.7.3`
- Data source type & version: Loki, Official Loki Docker Container (`latest`)
- OS Grafana is installed on: Official Grafana Docker Container (`6.7.3`)
- User OS & Browser: Linux Container, Chrome 81
- Grafana plugins: n/a
- Others: n/a

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Fixes an issue where cached log values weren't merged with log labels upon being refreshed.

**Which issue(s) this PR fixes**:
Closes #24087

### CODE REVIEW

File: public/app/plugins/datasource/loki/language_provider.ts [hunk 1]
```diff
@@ -460,18 +473,13 @@ export default class LokiLanguageProvider extends LanguageProvider {
...
-            };
-          }
-          return keyOption;
-        });
+        this.logLabelOptions = addLabelValuesToOptions(values);
       } catch (e) {
         console.error(e);
       }
+    } else {
+      // Add to label options
```
Comment (davkal) [inline public/app/plugins/datasource/loki/language_provider.ts:481]: This comment is repeating the code. Perhaps either clarify what "option" means here, or clarify what value is being added here, e.g., the cached vs the uncached one.

**Review by davkal — APPROVED** [review]
Bug fixes could use a test
Otherwise LGTM
