### PR TITLE
Card: Defend against conditional action buttons

### LINKED ISSUE #35164: playlist is broken
**What happened**:
We can not open or create playlist in recent version.

图片

**What you expected to happen**:

Component `Playlists` act as normal.

**How to reproduce it (as minimally and precisely as possible)**:
Just open https://play.grafana.org/playlists

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9d4c71920555f3ee76b1d8ed6f1b1a5d2885af
- User OS & Browser: Edge && Firefox

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
The `PlaylistPage` currently fails to render if visited by a viewer due to a conditional render occurring inside `<Card.Actions>` but the component always expects elements. This PR addresses that by asserting the element exists before calling `cloneElement`. 

It also removes the disabled prop from the Edit button in the PlaylistPage so editors and admins can edit playlists.

There shouldn't be a need to check if the children prop is an array as [React.children.map](https://reactjs.org/docs/react-api.html#reactchildrenmap) already handles this.

**Which issue(s) this PR fixes**:

Fixes #35164

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/playlist/PlaylistPage.tsx [hunk 1]
```diff
@@ -56,7 +56,6 @@ export const PlaylistPage: FC<Props> = ({ navModel }) => {
                   variant="secondary"
                   href={`/playlists/edit/${playlist.id}`}
                   icon="cog"
-                  disabled
                   title="Feature temporarily disabled"
```
Comment (Clarity-89) [inline public/app/features/playlist/PlaylistPage.tsx:59]: Should this tittle be removed as well?

**Review by Clarity-89 — APPROVED** [review]
Great job with fixing this! 🎉

**Review by torkelo — APPROVED** [review]
