### PR TITLE
PanelInspect: Update UI for Data display options

### LINKED ISSUE #24531: Query options overflowing on small screen
**What happened**:
Screenshot from 2020-05-11 16-51-01

**What you expected to happen**:
Not that.

**How to reproduce it (as minimally and precisely as possible)**:
Edit panel and resize window accordingly.

**Anything else we need to know?**:
A little bit of thinking might be needed to handle this

### LINKED ISSUE #25268: Update UI for Panel Inspect data display options and transformations
## Current state
In 7.0 we have introduced field configuration and transformations control when inspecting panel with Panel Inspect. The UI for this feature looks like this currently:

1. When no transformations applied in the panel:
image

2. When transformations applied in the panel:
image

3. When multiple series available in the panel:
image
---

We have discussed with @torkelo @jessover9000 and @sarlinska that the UI for transforming data, applying overrides, and transformations in the Panel Inspect is not optimal and confusing. 

As a result, @sarlinska came up with this [design proposal](https://www.figma.com/file/afM4ojoMBRfSmlb0LA0pYQ/Inspect-Drawer?node-id=506%3A0):
image

## UI updates to be implemented
This [proposed UI](https://www.figma.com/file/afM4ojoMBRfSmlb0LA0pYQ/Inspect-Drawer?node-id=506%3A0) organizes the Inspect data options in a simpler way. The most significant changes are:

1. The current Transform select (None/Join By Time) and Data frame select are gone and integrated into a single select that allows Data frame selection and Join By Time transformation:
image
2. All data options should be organized into single expandable section **Table data options**:
image
3. The **Table data options** expandable section should show a summary of the data options applied:
image

**Figma design**: https://www.figma.com/file/afM4ojoMBRfSmlb0LA0pYQ/Inspect-Drawer?node-id=506%3A0

### PR DESCRIPTION
**Pull request by tskarhed**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Closes #25268

Accidentally fixes #24531 too.

**Special notes for your reviewer**:
- Make sure min-height and line-height for QueryOptionsRow does not have any unintended consequences.

### CODE REVIEW

**Comment by torkelo** [comment]
Lots of margin/padding issues :)

Screenshot from 2020-06-10 10-19-35

Screenshot from 2020-06-10 10-19-51

Screenshot from 2020-06-10 10-21-06

**Review by dprokop — CHANGES_REQUESTED** [review]
Think this works OK!

Some design inaccuracy that I see compared to the sketch. In the Figma file the field config and the transformations switches are put in the horizontal layout:
image

while in the implementation they are stacked:
image

File: public/app/features/dashboard/components/Inspector/CollapsedText.tsx [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+import { css } from 'emotion';
+
+const getStyles = (theme: GrafanaTheme) => css`
+  margin: 0;
+  margin-left: ${theme.spacing.md};
+  font-size: ${theme.typography.size.sm};
+  color: ${theme.colors.textWeak};
+`;
+
+export const CollapsedText: FC = ({ children }) => {
```
Comment (dprokop) [inline public/app/features/dashboard/components/Inspector/CollapsedText.tsx:13]:
```suggestion
export const DetailText: FC = ({ children }) => {
```

File: public/app/features/dashboard/components/Inspector/PanelInspector.tsx [hunk 2]
```diff
@@ -191,6 +191,8 @@ export class PanelInspectorUnconnected extends PureComponent<Props, State> {
 
   renderDataTab() {
     const { last, isLoading, withFieldConfig, withTransforms } = this.state;
+    console.log(withTransforms);
+    console.log(last.series);
```
Comment (dprokop) [inline public/app/features/dashboard/components/Inspector/PanelInspector.tsx:195]:
```suggestion
```

File: public/app/features/dashboard/components/Inspector/styles.ts [hunk 3]
```diff
@@ -59,9 +59,14 @@ export const getPanelInspectorStyles = stylesFactory(() => {
...
       flex-grow: 1;
+
+      max-width: 85%;
+      @media (max-width: 1345px) {
+        max-width: 75%;
+      }
     `,
     options: css`
-      margin-top: 19px;
+      padding-top: 10px;
```
Comment (dprokop) [inline public/app/features/dashboard/components/Inspector/styles.ts:69]: maybe use theme consts?:)

**Comment by dprokop** [comment]
@tskarhed I will gently ping @sarlinska to review these changes to from the UX pov.

**Comment by tskarhed** [comment]
@sarlinksa The grey background isn't a thing in other places where this component is used, should it be? It's a bit complicated to implement otherwise.

**Comment by tskarhed** [comment]
I also tried to make the radio buttons horizontal, but it caused the Download CSV button to wrap to below unless it was on a very wide screen. This could be prevented, I just need a little bit more work on it.

**Comment by dprokop** [comment]
@tskarhed should this be still considered a Draft?

**Comment by dprokop** [comment]
With the horizontally aligned switches it works way better!

I found one issue tho, quite weird:
Kapture 2020-06-26 at 10 59 54

To reproduce:
1. Create table panel with **two** queries, Random Walk Table
2. Add **Outer join** transformation by Time column
3. Open inspect
4. Click on **Apply panel transformations**. 
5. The data frame select is gone (which is OK, as there are no multiple data frames anymore), but the Switch is off

File: public/app/features/dashboard/components/Inspector/DetailText.tsx [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+
+const getStyles = (theme: GrafanaTheme) => css`
+  margin: 0;
+  margin-left: ${theme.spacing.md};
+  font-size: ${theme.typography.size.sm};
+  color: ${theme.colors.textWeak};
+`;
+
+export const DetailText: FC = ({ children }) => {
+  const collapsedTextStyles = useStyles(getStyles);
```
Comment (dprokop) [inline public/app/features/dashboard/components/Inspector/DetailText.tsx:14]: @tskarhed can you bring the `useStyles` to upcoming front end weekly? :)

Comment (tskarhed) [reply public/app/features/dashboard/components/Inspector/DetailText.tsx:14]: Oh, right! Yeah, I created it a couple of months ago because people constantly used the same pattern.

**Comment by tskarhed** [comment]
It was the same issue as in #25826

**Review by dprokop — APPROVED** [review]
