### PR TITLE
Grafana/UI: Add disable prop to Segment

### LINKED ISSUE #29573: Grafana/ui: SegmentAsync component cannot be disabled
**What happened**:

I have defined a SegmentAsync component (in a datasource panel) and I have added disabled={true} to disable it.

Example : 
```
<SegmentAsync
         disabled={true}
          loadOptions={() => this.props.datasource.getall()}
          onChange={this.handleChangeProperty}
          allowCustomValue={true}
          value={this.state.property}
          placeholder="Select an Property"
/>
```

**What you expected to happen**:

The component should be disabled and clicking on the component should not open the menu.

**How to reproduce it (as minimally and precisely as possible)**:

Just define it

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.4
- Data source type & version: custom
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome
- Grafana plugins: custom
- Others:

### PR DESCRIPTION
**Pull request by oscarkilhed**
SegmentSync, SegmentAsync and SegmentInput had the disable prop inherited from HTMLProp but it did not disable the component. The disable prop should now disable the component.

**Which issue(s) this PR fixes**:

Fixes #29573

### CODE REVIEW

File: packages/grafana-ui/src/components/Segment/SegmentInput.tsx [hunk 1]
```diff
@@ -34,9 +36,18 @@ export function SegmentInput<T>({
...
         Component={
           Component || (
-            <a className={cx('gf-form-label', 'query-part', !value && placeholder && 'query-placeholder', className)}>
+            <a
+              className={cx(
+                'gf-form-label',
+                'query-part',
+                !value && placeholder && 'query-placeholder',
+                getStyles<T>({ disabled: disabled }).link,
+                className
```
Comment (torkelo) [inline packages/grafana-ui/src/components/Segment/SegmentInput.tsx:48]: fees like it would be better to use conditional classnames here: https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Button/ToolbarButton.tsx#L42 
Then you can move the getStyles call to the top (dont pass any props), just return a style with a "disabled"   style on it. then compose all the classses using cx like

```typescript
cx(
 'gf-form-label',
  'query-part', {
     ['query-placeholder']: !value && placeholder,
     [styles.disabled]: disabled
  },
className);
```

Comment (oscarkilhed) [reply packages/grafana-ui/src/components/Segment/SegmentInput.tsx:48]: Thanks, I wasn't quite happy with how the styles were applied. This looks cleaner, I'll get on it.

Comment (dprokop) [reply packages/grafana-ui/src/components/Segment/SegmentInput.tsx]: Good point @torkelo

File: packages/grafana-ui/src/components/Segment/SegmentAsync.tsx [hunk 2]
```diff
@@ -28,12 +30,25 @@ export function SegmentAsync<T>({
...
+    const styles = getStyles();
+
     return (
       <Label
         onClick={fetchOptions}
+        disabled={disabled}
         Component={
           Component || (
-            <a className={cx('gf-form-label', 'query-part', !value && placeholder && 'query-placeholder', className)}>
+            <a
```
Comment (Clarity-89) [inline packages/grafana-ui/src/components/Segment/SegmentAsync.tsx:41]: Using `a` without href is a bad accessibility practice, plus it seems like we're not using it as a link here at all, so can just change it to `span` and apply existing styles.

**Review by Clarity-89 — APPROVED** [review]
Looks good! 🎉  Left a few suggestions. Also I think it'd be a good idea to enable the controls for the components story in the storybook so it's easier to test props visually.

File: packages/grafana-ui/src/components/Segment/styles.ts [hunk 3]
```diff
@@ -0,0 +1,15 @@
+import { css } from 'emotion';
+import { stylesFactory } from '../../themes';
+
+export const getStyles = stylesFactory(() => {
```
[the remark this answers is not in the document]
Comment (oscarkilhed) [reply packages/grafana-ui/src/components/Segment/styles.ts:4]: Absolutely!

File: packages/grafana-ui/src/components/Segment/Segment.tsx [hunk 4]
```diff
@@ -18,19 +19,34 @@ export function Segment<T>({
...
+                'gf-form-label',
+                'query-part',
+                styles.clickable,
+                {
+                  ['query-placeholder']: placeholder !== undefined && !value,
+                  [styles.disabled]: disabled,
+                },
+                className
+              )}
+            >
```
[the remark this answers is not in the document]
Comment (oscarkilhed) [reply packages/grafana-ui/src/components/Segment/Segment.tsx:47]: Sounds like a good idea.

File: packages/grafana-ui/src/components/Segment/Segment.tsx [hunk 5]
```diff
@@ -18,19 +21,33 @@ export function Segment<T>({
...
   placeholder,
+  disabled,
   ...rest
 }: React.PropsWithChildren<SegmentSyncProps<T>>) {
   const [Label, width, expanded, setExpanded] = useExpandableLabel(false);
 
   if (!expanded) {
     const label = _.isObject(value) ? value.label : value;
+    const theme = useTheme();
+    const styles = getSegmentStyles(theme);
```
Comment (Clarity-89) [inline packages/grafana-ui/src/components/Segment/Segment.tsx:32]:
```suggestion
    const styles = useStyles(getSegmentStyles);
```
If get styles function has only theme param, we can use `useStyles` hook: https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/themes/ThemeContext.tsx#L51, which would provide the theme and memoize `getStyles` calls.

**Review by Clarity-89 — APPROVED** [review]
Good job! One minor suggestion and I think this is good to go.

File: packages/grafana-ui/src/components/Segment/Segment.tsx (hunk 5 above)
Comment (oscarkilhed) [reply packages/grafana-ui/src/components/Segment/Segment.tsx]: Ah, thanks!

**Review by torkelo — APPROVED** [review]
Merge it!
