### PR TITLE
Variables: Fix crash when changing query variable datasource

### LINKED ISSUE #43803: Changing variable datasource away from Azure Monitor crashes the page
I think this issue is not specific to Azure Monitor, but it's where I noticed it and triggers it in a very reliable way.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new variable "Query" on a dashboard 
2. Select the Azure Monitor datasource. You do not need to fill out a query, just select Azure Monitor as the datasource.
3. Change the datasource to Prometheus
4. The page crashes with "An unexpected error happened" and a "TypeError: datasource.getVariables is not a function" exception.

**Anything else we need to know?**:

While the exception happens from within the Azure Monitor datasource, it appears the problem is higher up in the stack in core Grafana as it looks like the Azure Monitor datasource is being incorrectly passed the Prometheus datasource when switching. Eek!

**Environment**:
- Grafana version: latest main - 36e4a871f2

### PR DESCRIPTION
**Pull request by joshhunt**
**What this PR does / why we need it**:

Builds on the work in https://github.com/grafana/grafana/pull/44749 to dispatch whole and typed actions to modify variable editor "extended" state.

 - Dispatching "whole" state means we prevent out-of-sync issues caused by dispatching one property at a time
 - Typing the action makes sure we're actually dispatching the correct thing.

**Which issue(s) this PR fixes**:

Fixes #43803

### CODE REVIEW

File: public/app/features/variables/adhoc/actions.ts [hunk 1]
```diff
@@ -85,27 +85,16 @@ export const changeVariableDatasource = (datasource?: DataSourceRef): ThunkResul
...
-          propValue: 'This data source does not support ad hoc filters yet.',
-        })
-      );
-    }
+    // TS TODO: ds is not typed to be optional - is this check unnecessary or is the type incorrect?
+    const message = ds?.getTagKeys
+      ? 'Ad hoc filters are applied automatically to all queries that target this data source'
+      : 'This data source does not support ad hoc filters yet.';
+
+    dispatch(changeVariableEditorExtended({ infoText: message }));
```
Comment (joshhunt) [inline public/app/features/variables/adhoc/actions.ts:97]: I've changed the behavior of the action here to no longer dispatch the "Ad hoc filters are applied automatically..." message while the datasource is loading because a) i don't think that's actually a loading messages, and b) I think it only shows _very_ briefly for unsupported data sources anyway?

File: public/app/features/variables/query/actions.test.ts [hunk 2]
```diff
@@ -312,43 +298,16 @@ describe('query actions', () => {
...
-        .whenActionIsDispatched(variablesInitTransaction({ uid: 'a uid' }))
-        .whenAsyncActionIsDispatched(initQueryVariableEditor(toVariablePayload(variable)), true);
-
-      tester.thenDispatchedActionsPredicateShouldEqual((actions) => {
-        const [setDatasource] = actions;
-        const expectedNumberOfActions = 1;
-
-        expect(setDatasource).toEqual(changeVariableEditorExtended({ propName: 'dataSource', propValue: undefined }));
-        return actions.length === expectedNumberOfActions;
-      });
```
Comment (joshhunt) [inline public/app/features/variables/query/actions.test.ts:344]: This test currently throws a "cannot read property variables of undefined" exception in main because  the action (and functions it call) does not actually handle if the datasource is undefined.

https://github.com/grafana/grafana/blob/4b4afc7b2caf641de0d350552a74c7ee25f1abbf/public/app/features/variables/guard.ts#L143-L149

From what I can tell, none of the `getVariableQueryEditor` or `hasCustomVariableSupport` tests have a case for the datasource being undefined.

Also, `await getDataSourceSrv().get(name ?? '')` says it cannot return undefined, and it will _always_ return a datasource, so I think this test does not test an actual scenario?

Comment (joshhunt) [reply public/app/features/variables/query/actions.test.ts:344]: _If_ `getDataSourceSrv().get()` _can_ return undefined, we should update it's type and fix everything that breaks.

File: public/app/features/variables/datasource/actions.ts [hunk 3]
```diff
@@ -49,8 +49,7 @@ export const initDataSourceVariableEditor =
 
     dispatch(
       changeVariableEditorExtended({
-        propName: 'dataSourceTypes',
-        propValue: dataSourceTypes,
+        dataSourceTypes: dataSourceTypes,
```
Comment (hugohaggmark) [inline public/app/features/variables/datasource/actions.ts:52]: super small nit:
```suggestion
        dataSourceTypes,
```

File: public/app/features/variables/editor/reducer.ts [hunk 4]
```diff
@@ -78,14 +78,10 @@ const variableEditorReducerSlice = createSlice({
...
-    changeVariableEditorExtended: (
-      state: VariableEditorState,
-      action: PayloadAction<{ propName: string; propValue: any }>
-    ) => {
-      // @ts-ignore - temp ignoring the errors now the state type is more strict
+    changeVariableEditorExtended: (state: VariableEditorState, action: PayloadAction<VariableEditorExtension>) => {
       state.extended = {
         ...state.extended,
-        [action.payload.propName]: action.payload.propValue,
+        ...action.payload,
```
Comment (hugohaggmark) [inline public/app/features/variables/editor/reducer.ts:84]: nit/future fear: Maybe this works now but in the future this can start to store some unknowns into state.

**Review by hugohaggmark — APPROVED** [review]
Looks good but I haven't tested it yet. Waiting for #https://github.com/grafana/grafana/pull/44749 to merge first.

File: public/app/features/variables/editor/reducer.ts (hunk 4 above)
Comment (joshhunt) [reply public/app/features/variables/editor/reducer.ts:84]: Hmmm... I'm not sure if I follow?

I did originally have this as `state.extended = action.payload;`, but changed it to what it is now in the PR to more closely match the current behavior of extending what's already there.

I think spreading existing state in keeps behavior/semantics the same as before, but I also don't think there should be problems caused by just overriding it with the action payload.

Happy to defer to you on what the best thing to do here is.

Comment (hugohaggmark) [reply public/app/features/variables/editor/reducer.ts:84]: No worries

**Review by ashharrison90 — APPROVED** [review]
lgtm 🙌
