### PR TITLE
Alerting: Return errors when expanding templates

### LINKED ISSUE #64231: Alerting: Custom annotations aren't expanded after every rule evaluation
**What happened**:

In Prometheus, annotations for an alert are expanded after each evaluation. This is in contrast from Grafana where annotations are expanded once when an alert fires. Grafana should be updated to match the same semantics as in Prometheus.

**What you expected to happen**:

For example, annotations that contain `$value` should be updated over time.

**How to reproduce it (as minimally and precisely as possible)**:

Create an alert rule in Prometheus that uses `$value` in an annotation and make HTTP requests to `api/v1/rules` to see the value of the query changes over time. Then create the same alert rule in Grafana and see how the annotations never change.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by grobinson-grafana**
**What is this feature?**

This commit changes the state package so that errors encountered while expanding templates for custom labels and annotations are returned from the function. This is not used at present, but will be used in the future as we look at how to offer better feedback to users who don't have access to logs, for example our customers who use Hosted Grafana.

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

This pull request will also help fix #64231 as we need to expand both annotations and labels separately from one another so we can update annotations over the lifetime of an alert.

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/ngalert/state/cache.go [hunk 1]
```diff
@@ -6,8 +6,10 @@ import (
 	"net/url"
 	"strings"
 	"sync"
+	"time"
 
 	"github.com/grafana/grafana-plugin-sdk-go/data"
+	"github.com/hashicorp/go-multierror"
```
Comment (gotjosh) [inline pkg/services/ngalert/state/cache.go:12]: What's your plan for this for the future? 

- I see we use `go-multierror` in many other places.
- dskit also has a multierror
- Go 1.20 has native support for this, but we're still at 1.19

At least with this approach is consistent I guess? Do you think it warrants a comment or an issue to follow up on it eventually?

File: pkg/services/ngalert/state/template/error.go [hunk 2]
```diff
@@ -0,0 +1,16 @@
+package template
+
+import (
```
Comment (gotjosh) [inline pkg/services/ngalert/state/template/error.go:3]: nit: I'd inline this error. I don't see a need for a new file - more indirection more files to look at.

File: pkg/services/ngalert/state/template/error_test.go [hunk 3]
```diff
@@ -0,0 +1,13 @@
+package template
```
Comment (gotjosh) [inline pkg/services/ngalert/state/template/error_test.go:1]: nit: I'm not sure I see the value of this test - you already test this incidentally on other functions.

File: pkg/services/ngalert/state/cache.go [hunk 4]
```diff
@@ -49,7 +51,12 @@ func (c *cache) getOrCreate(ctx context.Context, log log.Logger, alertRule *ngMo
 }
 
 func (rs *ruleStates) getOrCreate(ctx context.Context, log log.Logger, alertRule *ngModels.AlertRule, result eval.Result, extraLabels data.Labels, externalURL *url.URL) *State {
-	ruleLabels, annotations := rs.expandRuleLabelsAndAnnotations(ctx, log, alertRule, result, extraLabels, externalURL)
+	templateLabels := mergeLabels(extraLabels, result.Instance)
+	templateData := template.NewData(templateLabels, result)
+
+	// do nothing with the errors right now, these are logged in expand
```
Comment (gotjosh) [inline pkg/services/ngalert/state/cache.go:57]: nit: 
```suggestion
	// For now, we'll do nothing with these errors - they are already logged in `expand`.
```

**Review by gotjosh — APPROVED** [review]
LGTM - very nice, love this change!

File: pkg/services/ngalert/state/cache.go (hunk 1 above)
Comment (grobinson-grafana) [reply pkg/services/ngalert/state/cache.go:12]: Once we're on Go 1.20 I want to use the native support for multiple errors, until then I kept with `go-multierror` for the exact reasons you've listed here!

Comment (grobinson-grafana) [reply pkg/services/ngalert/state/cache.go:12]: I'll open a GitHub issue for us to move all use of `go-multierror` in Alerting once we update to Go 1.20.

Comment (grobinson-grafana) [reply pkg/services/ngalert/state/cache.go:12]: https://github.com/grafana/grafana/issues/63686

File: pkg/services/ngalert/state/template/error.go (hunk 2 above)
Comment (grobinson-grafana) [reply pkg/services/ngalert/state/template/error.go:3]: Inlined! 🙂

File: pkg/services/ngalert/state/template/error_test.go (hunk 3 above)
Comment (grobinson-grafana) [reply pkg/services/ngalert/state/template/error_test.go:1]: Those tests are in another package though which is the issue. If that package changes its behaviour then the implicit tests for `ExpandError` might no longer exist and then the code is untested.

File: pkg/services/ngalert/state/cache.go [hunk 5]
```diff
@@ -60,12 +69,12 @@ func (rs *ruleStates) getOrCreate(ctx context.Context, log log.Logger, alertRule
 		}
 	}
 
-	lbs := make(data.Labels, len(extraLabels)+len(ruleLabels)+len(result.Instance))
+	lbs := make(data.Labels, len(extraLabels)+len(labels)+len(result.Instance))
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/state/cache.go:72]: I think ruleLabels were more specific than "random" labels

Comment (grobinson-grafana) [reply pkg/services/ngalert/state/cache.go:72]: Should I do the same for annotations and call them `ruleAnnotations`?

Comment (grobinson-grafana) [reply pkg/services/ngalert/state/cache.go:72]: I was hoping there wasn't a need to be that specific here as there will be no other local variables called labels in this function. However, if I we want to keep using `ruleLabels` then I think I have to the same for annotations and call them `ruleAnnotations`, as otherwise it looks like the annotations don't belong to the rule according to the naming scheme.

Comment (yuri-tceretian) [reply pkg/services/ngalert/state/cache.go:72]: I think this is a good idea, and it's consistent.

Comment (grobinson-grafana) [reply pkg/services/ngalert/state/cache.go:72]: Perhaps we use `expandedLabels` and `expandedAnnotations` instead, as these variables are not really the original labels or annotations as they have been expanded?

**Comment by grobinson-grafana** [comment]
I just rebased `main`.

**Comment by grobinson-grafana** [comment]
I just did some manual testing of custom labels and annotations to complement the new and existing tests and show that this still works as expected.

Screenshot 2023-03-07 at 22 24 06

Screenshot 2023-03-07 at 22 25 04

**Comment by grobinson-grafana** [comment]
Here are the results of manual testing invalid templates.

Screenshot 2023-03-07 at 22 26 20

Screenshot 2023-03-07 at 22 27 22
