### PR TITLE
PanelEdit: Prevent the preview pane to be resized further than window height

### LINKED ISSUE #27990: PanelEdit: Protect against resizing query region beyond viewport
**What happened**:
DIVs at the bottom in EDIT are not scrollable when the graph itself takes much of the screen's real estate. Additionally, when you accidentally resized the graph to be very large, you lose the resize handle so you can't resize it back.

grafana_scroll_bug

**What you expected to happen**:
Scrolls. Set max height of the graphs/panels in Edit view

**How to reproduce it (as minimally and precisely as possible)**:
Edit any panel, make the widget large.

**Anything else we need to know?**:
Reproducible on all browsers, even on https://play.grafana.org/d/000000012/grafana-play-home?editPanel=2&orgId=1

### PR DESCRIPTION
**Pull request by peterholmberg**
**What this PR does / why we need it**:
Sets a maxSize on the SplitPane which prevents the topPane from being resized beyond the window height. Also store the value as a percent so if you resize the window the topPane will adjust after the new window size (needs refresh though). 
**Which issue(s) this PR fixes**:

Fixes #27990

**Special notes for your reviewer**:
The needs refresh part doesn't feel super, but not sure how to solve this without a rerender loop?

### CODE REVIEW

**Comment by dprokop** [comment]
> The needs refresh part doesn't feel super, but not sure how to solve this without a rerender loop?

@peterholmberg I think there are two ways.
1. Debouncing - but won't be bulletproof
2. Faking post-window resize event. Quick sketch of how this could look:

```ts
const rafToken = useRef<number>();

window.addEventListener('resize', () => {
  if(rafToken.current !== undefined) {
    window.cancelAnimationFrame(rafToke.current);
  }
  window.requestAnimationFrame(() => {
    // do the resize thing
  });
});
```

**Review by dprokop — COMMENTED** [review]
@peterholmberg this seems to work as expected, nice!

Since you are on it, maybe you could also fix the issue with the side pane? You can end up in a situation when the side pane cannot be resized if you make it full width, see the video:

Kapture 2020-10-20 at 10 20 19

File: public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx [hunk 1]
```diff
@@ -131,11 +131,16 @@ export class PanelEditorUnconnected extends PureComponent<Props> {
...
-    updatePanelEditorUIState({
-      [targetPane]: size,
-    });
+    if (pane === Pane.Top) {
+      updatePanelEditorUIState({
+        topPaneSize: `${(size / window.innerHeight) * 100}%`,
+      });
+    } else {
+      updatePanelEditorUIState({
+        rightPaneSize: size,
```
Comment (dprokop) [inline public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:141]: Would be awesome to have percentages here as well to be aligned with top pane sizing.

**Review by jackw — APPROVED** [review]
LGTM! 🚀

File: public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx [hunk 2]
```diff
@@ -58,19 +58,48 @@ interface DispatchProps {
...
+    window.removeEventListener('resize', this.updateSplitPaneSize);
   }
 
+  updateSplitPaneSize = () => {
+    if (this.rafToken.current !== undefined) {
+      window.cancelAnimationFrame(this.rafToken.current!);
+    }
+    window.requestAnimationFrame(() => {
+      this.setState({ rightPanelSize: this.props.uiState.rightPaneSize });
+      this.setState({ topPanelSize: this.props.uiState.topPaneSize });
```
Comment (dprokop) [inline public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:99]: Can we do in a single pass?
```suggestion
      this.setState({ 
        rightPanelSize: this.props.uiState.rightPaneSize,
        topPanelSize: this.props.uiState.topPaneSize
      });
```

Comment (peterholmberg) [reply public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:99]: Gah, yes! No idea what happened there :smile:

**Review by dprokop — COMMENTED** [review]
Seems to work as expected! I have noticed few things we need to followup on but in the context of this PR this one is relevant:

When resizing the side pane's min width(300px) is not being respected and the pane is being resized below that limit:
Kapture 2020-10-21 at 09 50 41


I think we could maybe collapse the side pane when there is no space available to show it? @torkelo @peterholmberg  WDYT?

Additional problems I've noticed and will open separate issues:
1. There's a lot of stuttering when resizing the panel editor window
2. Bottom pane's tabs are rendered incorrectly when size of the window is small:
image

File: public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx [hunk 3]
```diff
@@ -62,15 +66,28 @@ type Props = OwnProps & ConnectedProps & DispatchProps;
...
 
   componentWillUnmount() {
     this.props.panelEditorCleanUp();
+    window.removeEventListener('resize', this.updateSplitPaneSize);
   }
 
+  updateSplitPaneSize = () => {
+    if (this.rafToken.current !== undefined) {
+      window.cancelAnimationFrame(this.rafToken.current!);
+    }
```
Comment (dprokop) [inline public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:85]: This is never executed as you are never setting the rafToken. You need to assign it with rAF result for this to work.

File: public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx [hunk 4]
```diff
@@ -62,15 +66,28 @@ type Props = OwnProps & ConnectedProps & DispatchProps;
 
 export class PanelEditorUnconnected extends PureComponent<Props> {
   querySubscription: Unsubscribable;
+  rafToken = createRef<number>();
 
   componentDidMount() {
     this.props.initPanelEditor(this.props.sourcePanel, this.props.dashboard);
+
+    window.addEventListener('resize', debounce(this.updateSplitPaneSize, 100));
```
Comment (dprokop) [inline public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:74]: I think the debounce is not necessary here. We should use **either** debounce or rAF

File: public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx [hunk 5]
```diff
@@ -131,11 +148,16 @@ export class PanelEditorUnconnected extends PureComponent<Props> {
...
     }
 
-    const targetPane = pane === Pane.Top ? 'topPaneSize' : 'rightPaneSize';
     const { updatePanelEditorUIState } = this.props;
-    updatePanelEditorUIState({
-      [targetPane]: size,
-    });
+    if (pane === Pane.Top) {
+      updatePanelEditorUIState({
+        topPaneSize: `${(size / window.innerHeight) * 100}%`,
```
Comment (dprokop) [inline public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:154]: I suggest keeping numbers in the state rather than strings. Can't see any benefit in having percentage strings persisted. What is interesting from the component rendering POV is the ratio between the pane size vs window size. This way we can easily switch between % and px if we decide to.

File: public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx [hunk 6]
```diff
@@ -313,10 +344,21 @@ export class PanelEditorUnconnected extends PureComponent<Props> {
...
     const { uiState } = this.props;
 
+    // Limit options pane width to 90% of screen.
+    const maxWidth = window.innerWidth * 0.9;
+
+    // Need to handle when width is relative. ie a percentage of the viewport
+    const width =
+      typeof uiState.rightPaneSize === 'string'
+        ? (parseFloat(uiState.rightPaneSize) / 100) * window.innerWidth
+        : uiState.rightPaneSize;
```
Comment (dprokop) [inline public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:354]: With my comment above you can just assume the persisted state is stored as numbers and change this condition to check whether the number is <1 (storing ration) or >1 (storing actual width)

File: public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx (hunk 1 above)
Comment (dprokop) [reply public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx]: I wasn't precise enough - instead of percentages I have meant pane size/ window size ratio

**Review by dprokop — APPROVED** [review]
