### PR TITLE
Dashboard: Prevent crash when expanding a row containing panels with …

### LINKED ISSUE #42579: Investigate browser crashing when expanding a repeated row
see https://github.com/grafana/support-escalations/issues/1412 for context

### PR DESCRIPTION
**Pull request by ashharrison90**
…no yPos defined

**What this PR does / why we need it**:

- grafonnet can generate panels inside rows with no x or y gridPos (see https://github.com/grafana/grafonnet-lib/blob/master/grafonnet-7.0/DOCS.md#setgridpos-2)
- when expanding the row, this causes the browser to crash in an infinite loop
- default to the row yPos if no panel yPos is set (the y gridPos is the only one we strictly need)
- add a unit test to make sure this doesn't regress

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/42579

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/dashboard/state/DashboardModel.ts [hunk 1]
```diff
@@ -942,8 +942,8 @@ export class DashboardModel {
 
       if (row.panels.length > 0) {
         // Use first panel to figure out if it was moved or pushed
-        const firstPanel = row.panels[0];
-        const yDiff = firstPanel.gridPos.y - (row.gridPos.y + row.gridPos.h);
+        const firstPanelYPos = row.panels[0].gridPos.y ?? row.gridPos.y;
+        const yDiff = firstPanelYPos - (row.gridPos.y + row.gridPos.h);
```
Comment (joshhunt) [inline public/app/features/dashboard/state/DashboardModel.ts:946]: maybe just add a brief comment explaining why this is so defensive?

**Review by joshhunt — APPROVED** [review]
👍🏻
