### PR TITLE
Logs: Show LogRowMenu also for long logs and wrap-lines turned off

### LINKED ISSUE #55951: Logs: LogRow menu is not visible when wrap-lines is turned off
**What happened**:

@ivanahuckova noticed that the menu with the copy and show-context button is not visible with long lines and wrap-lines turned off. The menu should be always visible.

**What you expected to happen**:
Visible menu with long logrows and wrap-lines turned off.

**How to reproduce it (as minimally and precisely as possible)**:
Turn wrap-lines off and display log lines which are longer than your screen width.

**Anything else we need to know?**:

**Environment**:
- Grafana version: main

### PR DESCRIPTION
**Pull request by svennergr**
**What this PR does / why we need it**:
As mentioned in https://github.com/grafana/grafana/issues/55951 the menu in a LogRow containing the copy button and show-context button is not visible if there are long LogRows and wrap-lines toggled off.

This PR fixes this issue by moving the menu into a new table cell.

**Which issue(s) this PR fixes**:

Fixes #55951

**Special notes for your reviewer**:
1. You need long log entries to reproduce this. Best is to change the https://github.com/grafana/grafana/blob/d0fa81fe91aa334354aeabf240e77dc7663645f7/devenv/docker/blocks/loki/data/data.js#L73 file to ingest long lines into loki.
2. Toggle wrap-lines off.
3. Without this PR you won't see the LogRowMenu.

### CODE REVIEW

File: public/app/features/logs/components/LogRowMessage.tsx [hunk 1]
```diff
@@ -72,6 +71,11 @@ const getStyles = (theme: GrafanaTheme2, showContextButton: boolean, isInDashboa
       visibility: hidden;
       width: ${showContextButton ? '80px' : '40px'};
     `,
+    logRowMenuCell: css`
+      position: absolute;
+      right: ${isInDashboard ? '40px' : '163px'};
```
Comment (svennergr) [inline public/app/features/logs/components/LogRowMessage.tsx:76]: Unfortunately I can not really justify those numbers. That's just what I figured out.

Comment (ivanahuckova) [reply public/app/features/logs/components/LogRowMessage.tsx:76]: I am slightly worried if this is not going to break if users have different default font sizes/different browser. You see how I have it in the ~middle of log line. 

What about having menu at the beginning of the line instead of end? This way it would be at the same position for all cases - wrap/not wrapped. 

image

image

Comment (svennergr) [reply public/app/features/logs/components/LogRowMessage.tsx:76]: I just noticed another issue with this, where the timestamp row got a wrong width. I moved this issue back to draft to figure out a better solution for this.

Comment (svennergr) [reply public/app/features/logs/components/LogRowMessage.tsx:76]: Oh, regarding the issue you are seeing, that is indeed only if there's just the "one" button menu. I think the positions are correct if you add a line filter to also see the show context button.

File: public/app/features/logs/components/LogRowMessage.tsx [hunk 2]
```diff
@@ -72,6 +71,11 @@ const getStyles = (theme: GrafanaTheme2, showContextButton: boolean, isInDashboa
       visibility: hidden;
       width: ${showContextButton ? '80px' : '40px'};
     `,
+    logRowMenuCell: css`
+      position: absolute;
+      right: ${isInDashboard ? '40px' : `calc(75px + ${theme.spacing()} + ${showContextButton ? '80px' : '40px'})`};
```
Comment (svennergr) [inline public/app/features/logs/components/LogRowMessage.tsx:76]: `75px` is coming from the `LogsNavigation` to the right of the table being 75px width. I agree it's not ideal, but it should work in most cases. Additionally I think this is always better that having the menu kinda "hidden" on long lines. 
I think this solves the issue for now, but we could dedicate some time bringing the context into a more stable shape in Q4.
WDYT?

File: public/app/features/logs/components/LogRowMessage.tsx (hunk 1 above)
Comment (matyax) [reply public/app/features/logs/components/LogRowMessage.tsx]: > I am slightly worried if this is not going to break if users have different default font sizes/different browser

That's a good argument for using `em` or `rem` instead of `px`. https://blog.logrocket.com/using-em-vs-rem-css/#what-em-rem-why-use

Comment (svennergr) [reply public/app/features/logs/components/LogRowMessage.tsx]: I think "custom" font-sizes are currently not supported in Grafana? I changed the font-size in Chrome and it did not apply to Grafana.

File: public/app/features/logs/components/LogRowMessage.tsx (hunk 2 above)
Comment (ivanahuckova) [reply public/app/features/logs/components/LogRowMessage.tsx:76]: 1 more question, is this space that is created by `theme.spacing()` wanted on purpose?
image

I am asking because without it, it ends at the same place as log line hover style. So I was just curious, if that is wanted.  
image

**Review by ivanahuckova — APPROVED** [review]
LGTM (1 left 1 question below, but it is non-blocking) for bug fix, but I agree that if we decide to dedicate more time to show context improvements and menu, this could be refactored to make it more stable.
