### PR TITLE
Navigation: Use correct component for custom branding

### LINKED ISSUE #48093: New Navigation: Fix customisation (whitelabelling) in new navbar
Custom branding feature (whitelabelling) doesn’t work for the new navigation, i.e. the grafana logo on the top left is not customisable.

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- uses the `Branding.MenuLogo` component as the home icon which allows for custom branding

**Which issue(s) this PR fixes**:

Fixes #48093 

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/core/components/NavBar/Next/NavBarMenu.tsx [hunk 1]
```diff
@@ -267,9 +268,21 @@ function NavItem({
...
+                  {link.img && (
+                    <img
+                      src={link.img}
+                      alt={`${link.text} logo`}
+                      height="24"
+                      width="24"
+                      style={{ borderRadius: '50%' }}
+                    />
+                  )}
+                </>
```
Comment (joshhunt) [inline public/app/core/components/NavBar/Next/NavBarMenu.tsx:285]: I wonder maybe if we can just scoot this out to a separate component that's just an if-statement to make this a bit easier to follow?

```tsx
const NavBarMenuLogo = ({link}) => {

if (link.id == "home") {
..
} else if (link.icon)  {
..
} etc
```

just a random thought.

**Review by joshhunt — APPROVED** [review]

File: public/app/core/components/NavBar/Next/NavBarMenu.tsx (hunk 1 above)
Comment (ashharrison90) [reply public/app/core/components/NavBar/Next/NavBarMenu.tsx]: yep, have made that change. we can also extract and reuse it further in a later refactor 🤓
