### PR TITLE
AzureMonitor: Correctly update subscriptions value in ARG editor

### LINKED ISSUE #55190: Azure Monitor: ARG variable sub picker not allowing for change
**What happened**:  Both locally and on Grafana cloud instance, the sub picker for ARG template variables showed odd behavior.
1. Clicking on the `x` by the subscription name, takes me back to the Variable main menu
2. Clicking on the `x` by the edge of the sub editor does nothhing
3. Clicking on the dropdown and trying to select a different sub, does nothing

argVarBroken

**What you expected to happen**:
For the subscription picker on the ARG template variable to allow for either removal of subscriptions pre selected, or adding/changing the subscription selected

**How to reproduce it (as minimally and precisely as possible)**:
1. Ensure there is an Azure Monitor datasource
2. create a new dashboard
3. create a new variable
4. select Resource Graph for the `query type`
5. try changing or removing the sub

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.3
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Na
- User OS & Browser: Windows, Edge
- Grafana plugins: NA
- Others: NA

### PR DESCRIPTION
**Pull request by aangelisc**
**What this PR does / why we need it**:

Correctly sets the `subscriptions` property in an Azure Monitor query to allow for multi-select in the variable editor. Query properties cannot be edited directly as they're read-only, a new query must be constructed and updated.

**Which issue(s) this PR fixes**:

Fixes #55190 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by asimpson — APPROVED** [review]
LGTM 🏆 

I like how this follows the same pattern of instantiating `newQuery` like `handleChange` does before it.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/SubscriptionField.tsx [hunk 1]
```diff
@@ -56,9 +56,12 @@ const SubscriptionField: React.FC<SubscriptionFieldProps> = ({
         return;
       }
 
-      query.subscriptions = change.map((c) => c.value ?? '');
+      let newQuery: AzureMonitorQuery = {
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/SubscriptionField.tsx:59]: nit: you can either set this to a `const` or simply doing the replacement in `onQueryChange`:

```
      onQueryChange({
        ...query,
        subscriptions: change.map((c) => c.value ?? ''),
      });
```

**Review by andresmgot — APPROVED** [review]
Nice catch! Wondering why this works in the normal query editor but not in the template variable editor... I guess `query` is defined as immutable there.

**Comment by andresmgot** [comment]
BTW, add this to the changelog since it's a bug fix :)
