### PR TITLE
PostgreSQL: Fix error source in PGX

### LINKED ISSUE #110751: PostgreSQL: PGX changed error source from downstream to plugin
We need to change back the error source from plugin to downstream where it is needed.

### PR DESCRIPTION
**Pull request by zoltanbedi**
Fixes https://github.com/grafana/grafana/issues/110751

### CODE REVIEW

File: pkg/tsdb/grafana-postgresql-datasource/sqleng/sql_engine.go [hunk 1]
```diff
@@ -108,7 +108,6 @@ func (e *DataSourceHandler) TransformQueryError(logger log.Logger, err error) er
 	// for security purposes.
 	var opErr *net.OpError
 	if errors.As(err, &opErr) {
-		logger.Error("Query error", "err", err)
```
Comment (zoltanbedi) [inline pkg/tsdb/grafana-postgresql-datasource/sqleng/sql_engine.go:111]: Removed this error logging as it is duplicate. We are going to log the error anyway.

**Review by dgiagio — APPROVED** [review]
