### PR TITLE
@grafana/runtime: Avoid calling applyTemplateVariables for the wrong datasource

### LINKED ISSUE #503: Math expressions don't work in dashboard panels
**What happened**:

Any math expressions result in error "e.replace is not a function"

**How to reproduce it (as minimally and precisely as possible)**:

1. Add two queries A and B which successfully return data
2. Add an expression, "Math", "$A + $B"
3. See the error "e.replace is not a function"

**Screenshots**

Screenshot_20221021_053527

**Anything else we need to know?**:

**Environment**:

- Grafana version: 9.1.x
- Plugin version: main

### LINKED ISSUE #57663: Backend - Incorrect datasource ref used for applyTemplateVariables
**What happened**:

Related to grafana/azure-data-explorer-datasource#503. The incorrect datasource reference is used when applying template variables [here](https://github.com/grafana/grafana/blob/92531c559612dd077f30b186873e23002c5c5ac5/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L145). 

When a query containing an ADX target and an expression target is run the `applyTemplateVariables` function is called with the `ExpressionDatasource` instance for both queries rather than just the expression query.

**What you expected to happen**:

The `applyTemplateVariables` function should be called with the correct datasource instance for the respective query.

**How to reproduce it (as minimally and precisely as possible)**:

- Create an ADX query
- Create an Expression query referencing the ADX query
- Make use of a breakpoint on the above referenced line to see the `applyTemplateVariables` function called with the wrong instance.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by andresmgot**
**What is this feature?**

We found (thanks to @aangelisc) an interesting bug [here](https://github.com/grafana/grafana/issues/57663). When a data source has a field `expression` on its query (for example ADX) and is used along a Grafana expression, it doesn't work. What we noticed is that the code is trying to execute `applyTemplateVariables` defined in the `ExpressionDatasource` not the one for `AdxDatasource`.

This is actually the case for all data sources, the code modified in this PR executes the method `applyTemplateVariables` of the  `ExpressionDatasource` if there is an expresion, for the query of the plugin data source. This is usually a noop since most of the data sources does not have an `expression` field, because `ExpressionDatasource` calls `.templateSrv().replace` on that field.

See inline comment for more details.

**Which issue(s) does this PR fix?**:

Fixes #57663 
Fixes https://github.com/grafana/azure-data-explorer-datasource/issues/503

**Special notes for your reviewer**:

Who is the owner of Expressions?

### CODE REVIEW

File: packages/grafana-runtime/src/utils/DataSourceWithBackend.ts [hunk 1]
```diff
@@ -137,12 +139,19 @@ class DataSourceWithBackend<
           throw new Error(`Unknown Datasource: ${JSON.stringify(q.datasource)}`);
         }
 
-        datasource = ds.rawRef ?? getDataSourceRef(ds);
-        datasourceId = ds.id;
+        const dsRef = ds.rawRef ?? getDataSourceRef(ds);
+        const dsId = ds.id;
+        if (!eq(dsRef, datasource) || datasourceId !== dsId) {
```
Comment (andresmgot) [inline packages/grafana-runtime/src/utils/DataSourceWithBackend.ts:144]: Interestenly enough, I only found that this condition is true (so `this` and `q.datasource` are different) when there is an `Expression` in the list of targets.

In the case of a `-- Mixed --` query, `this` is pointing to the right data source instance (as long as there is not an `Expression` query) on each iteration of the loop.

This issue would also be fixed if we modify the reason why `this` is pointing to the `ExpressionDatasource` rather than the actual data source but not sure if this condition is also true for other type of query.

**Review by aangelisc — CHANGES_REQUESTED** [review]
A nice fix! This would benefit from a test I think (at least to ensure that this case can potentially be caught in the future). 👍

**Review by aangelisc — APPROVED** [review]

**Review by mckn — APPROVED** [review]
LGTM! This is a scary change but I can't find any place where it break.
