### PR TITLE
Fix queries being imported incorrectly on datasource change 

### LINKED ISSUE #15086: Inifinite loop when Scan for older logs clicked

### PR DESCRIPTION
**Pull request by dprokop**
Queries import is now separated from 'loadDatasource` action. 

fixes #15086

### CODE REVIEW

File: public/app/features/explore/state/actionTypes.ts [hunk 1]
```diff
@@ -43,6 +43,7 @@ export enum ActionTypes {
   ToggleTable = 'explore/TOGGLE_TABLE',
   UpdateDatasourceInstance = 'explore/UPDATE_DATASOURCE_INSTANCE',
   ResetExplore = 'explore/RESET_EXPLORE',
+  SetInitialQueries = 'explore/SET_INITIAL_QUERIES',
```
Comment (davkal) [inline public/app/features/explore/state/actionTypes.ts]: Any chance to avoid setter actions?

File: public/app/features/explore/state/actions.ts [hunk 2]
```diff
@@ -69,10 +70,15 @@ export function addQueryRow(exploreId: ExploreId, index: number): AddQueryRowAct
  * Loads a new datasource identified by the given name.
  */
 export function changeDatasource(exploreId: ExploreId, datasource: string): ThunkResult<void> {
-  return async dispatch => {
-    const instance = await getDatasourceSrv().get(datasource);
-    dispatch(updateDatasourceInstance(exploreId, instance));
-    dispatch(loadDatasource(exploreId, instance));
+  return async (dispatch, getState) => {
+    const newDataSourceInstance = await getDatasourceSrv().get(datasource);
```
Comment (davkal) [inline public/app/features/explore/state/actions.ts]: Since this is async and the next lines get state later, you might end up importing different queries from a different DB.

File: public/app/features/explore/state/actions.ts [hunk 3]
```diff
@@ -319,34 +361,13 @@ export function loadDatasource(exploreId: ExploreId, instance: DataSourceApi): T
     }
 
     // Check if queries can be imported from previously selected datasource
-    const queries = getState().explore[exploreId].modifiedQueries;
```
Comment (davkal) [inline public/app/features/explore/state/actions.ts]: Importing came after `instance.init();`. Have you checked if that makes a difference?

**Review by davkal — COMMENTED** [review]
Some subtleties that should be verified, or at least commented on.

File: public/app/plugins/datasource/loki/language_provider.ts [hunk 4]
```diff
@@ -177,6 +177,7 @@ export default class LokiLanguageProvider extends LanguageProvider {
     return queries.map(query => ({
```
Comment (hugohaggmark) [inline public/app/plugins/datasource/loki/language_provider.ts]: This is my fault, we shouldn't introduce Grafanaish concepts like refId and key here, right @davkal? That's why in the original code (https://github.com/grafana/grafana/blob/a21f6777c16bca7f8c15ef7568f6095ff31a45e9/public/app/features/explore/state/actions.ts#L346) used ...generateEmptyQuery(i). So refId and key should be removed and tests updated.

File: public/app/features/explore/state/actions.ts (hunk 2 above)
Comment (dprokop) [reply public/app/features/explore/state/actions.ts]: I think you can not. Instance instate is updated later on (L80)

File: public/app/features/explore/state/actions.ts [hunk 5]
```diff
@@ -319,34 +361,13 @@ export function loadDatasource(exploreId: ExploreId, instance: DataSourceApi): T
...
-      }
-    }
 
     if (datasourceName !== getState().explore[exploreId].requestedDatasourceName) {
       // User already changed datasource again, discard results
       return;
     }
 
-    // Reset edit state with new queries
-    const nextQueries = importedQueries.map((q, i) => ({
```
[the remark this answers is not in the document]
Comment (dprokop) [reply public/app/features/explore/state/actions.ts]: Good catch! Removed unnecessarily.

File: public/app/features/explore/state/actions.ts (hunk 3 above)
Comment (dprokop) [reply public/app/features/explore/state/actions.ts]: Haven't noticed. Was there any particular reason to have queries imported after `init`?

File: public/app/features/explore/state/actionTypes.ts (hunk 1 above)
Comment (dprokop) [reply public/app/features/explore/state/actionTypes.ts]: I'm assuming you are referring to naming convention here? I'll update the name to make it not bound to performed state change, but queries import is a de facto setter.

File: public/app/features/explore/state/actions.ts (hunk 3 above)
Comment (davkal) [reply public/app/features/explore/state/actions.ts]: It's currently not relevant. Only Prometheus uses `init()`, but perhaps we should make that contract a bit clearer.

**Comment by davkal** [comment]
Works if the datasources are ok. If the target DS is not working, the import attempt is useless. I'm wondering if it makes sense to have the query import before the datasource loading in the first place.
Otherwise looks good.

**Comment by dprokop** [comment]
Tru dat @davkal, that was my biggest concern about this change. The DS loading you are refering to consists of two steps: DS test and init. I think the test itself should be performed as a first step, to fail ASAP. This means we could introduce test DS action to make the flow more verbose. 

There is an issue for improving the flow and UX of datasource loding (https://github.com/grafana/grafana/issues/15096) and we should focus on the order of things optimisation when working on that as well.

File: public/app/features/explore/state/actions.ts (hunk 3 above)
Comment (torkelo) [reply public/app/features/explore/state/actions.ts]: what does init do? can it be moved to DatasourceSrv..get ?

Comment (dprokop) [reply public/app/features/explore/state/actions.ts]: In case of Prometheus it loads rules. DatasourceSrv.get could perform the whole DS setup, init included after the DS is loaded. That would make sense to have DatasourceSrv return fully usable DS instance.
