### PR TITLE
BarChart: Fix value mappings

### LINKED ISSUE #59776: Cannot read properties of undefined (reading 'color')  on Bar Chart
Hola Folks,

Here a small i encounter since the last release

**What happened**:
One of my bar chart is "broken" since the last release. If the bar chart have a value mapping set to something that doesn't exist, it will crash
image
`TypeError: Cannot read properties of undefined (reading 'color')
    at 2352.d7c14cbd3dbda648a17f.js:7413:18202
    at Array.some (<anonymous>)
    at 2352.d7c14cbd3dbda648a17f.js:7413:18170
    at Array.some (<anonymous>)
    at G.c.useFieldConfig.standardOptions.settings.byValueSupport (2352.d7c14cbd3dbda648a17f.js:7413:17941)
    at ra (2754.c9252327f51106ea3a6d.js:2:801944)
    at Ws (2754.c9252327f51106ea3a6d.js:2:854025)
    at Ou (2754.c9252327f51106ea3a6d.js:2:841298)
    at ku (2754.c9252327f51106ea3a6d.js:2:841226)
    at Eu (2754.c9252327f51106ea3a6d.js:2:841089)`

**What you expected to happen**:
Not be broken and render it anyways

**How to reproduce it (as minimally and precisely as possible)**:
- Create a bar chart panel
- Make a basic query
- Add a Value Mapping to a value with text that doesn't exist  in query 
- The bar chart doesn't render anymore

**Anything else we need to know?**:
- If i remove the unuse mapping it work fine
- I've tried on other panel type, it work fine with unuse mapping value

**Environment**:
- Grafana version: [v9.3.1 (89b365f8b1)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- Data source type & version: SQL Query
- OS Grafana is installed on: Unix/Kubernetes
- User OS & Browser: Chrome/Mozilla/Opera
- Grafana plugins: N/A
- Others:

### LINKED ISSUE #60002: Bar Chart error with MySQL queries
Hi, 
Since the last update, Bar Chars does not work anymore with our MySQL queries.
We have this error: 
image
But if we switch to the Table view it works: 
image

And the SQL query works with other visualizations.

Grafana Version: 9.3.1 on Debian 11

If you have an idea, that's would be helpful :)

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/grafana/issues/59776
Fixes https://github.com/grafana/grafana/issues/60002

i broke this over a month ago in https://github.com/grafana/grafana/pull/58285

you can test this by adding any Value type mapping in any BarChart panel.

apparently my mental model of value mappings having the same structure was incorrect. they're all the same _except_ the most common `ValueToText` one :facepalm:

image

### CODE REVIEW

File: public/app/plugins/panel/barchart/BarChartPanel.tsx [hunk 1]
```diff
@@ -242,7 +242,17 @@ export const BarChartPanel: React.FunctionComponent<Props> = ({
         f.config.custom?.gradientMode === GraphGradientMode.Scheme &&
         f.config.color?.mode === FieldColorModeId.Thresholds;
 
-      return fromThresholds || f.config.mappings?.some((m) => m.options.result.color != null);
+      return (
+        fromThresholds ||
+        f.config.mappings?.some((m) => {
+          // ValueToText mappings have a different format, where all of them are grouped into an object keyed by value
+          if (m.type === 'value') {
+            // === MappingType.ValueToText
```
Comment (leeoniya) [inline public/app/plugins/panel/barchart/BarChartPanel.tsx:250]: this was on the previous line, until Prettier "fixed" it :roll_eyes: 

this is here because we currently have an issue with the schema generation which exports enums only as types, so the values cannot be used as RHS. @sdboyer is on it, but we can probably just land it like this, since that can take more time and we'll want this fix to land in the next patch release.

image

**Review by ryantxu — APPROVED** [review]

File: public/app/plugins/panel/barchart/BarChartPanel.tsx (hunk 1 above)
Comment (sdboyer) [reply public/app/plugins/panel/barchart/BarChartPanel.tsx:250]: fyi, this is already fixed in #55769 - i'm just loathe to pull it out and inevitably create a merge conflict there when it's already so close

i'll do it if that PR doesn't land by next week though
