### PR TITLE
Explore: Prevent direct access to explore if disabled via feature toggle

### LINKED ISSUE #46430: Explore: feature toggle does not prevent direct access
**What happened**:

When you set the `explore` configuration `enabled = false` and navigate directly to `/explore` the explore page loads.

**What you expected to happen**:

User would encounter "Page not found" FeatureTogglePage (similar to the experience when alerting is disabled).

**How to reproduce it (as minimally and precisely as possible)**:

1. Set `explore` configuration `enabled = false`
2. Navigate to `/explore` route

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.6
- Data source type & version: N/A
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by Elfo404**
**What this PR does / why we need it**:

setting
```ini
[explore]
enabled = false
```
prevents the Explore nav item to be added to the navbar but does not prevent direct access ( by typing `/explore` in the URL).

this PR changes that by avoid registering the route altogether if explore is disabled.

**Which issue(s) this PR fixes**:

Fixes #46430

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/routes/routes.tsx [hunk 1]
```diff
@@ -153,7 +154,7 @@ export function getAppRoutes(): RouteDescriptor[] {
         () => import(/* webpackChunkName: "DashboardListPage"*/ 'app/features/search/components/DashboardListPage')
       ),
     },
-    {
+    config.exploreEnabled && {
```
Comment (ifrost) [inline public/app/routes/routes.tsx:157]: Just realized we do it differently for alerting and profile. Maybe we could do something similar, by creating a `FeatureTogglePage.tsx`:

```typescript
    {
      path: '/explore',
      pageClass: 'page-explore',
      roles: () =>
        contextSrv.evaluatePermission(
          () => (config.viewersCanEdit ? [] : ['Editor', 'Admin']),
          [AccessControlAction.DataSourcesExplore]
        ),
      component: config.exploreEnabled
        ? SafeDynamicImport(() => import(/* webpackChunkName: "explore" */ 'app/features/explore/Wrapper'))
        : SafeDynamicImport(
            () => import(/* webpackChunkName: "Explore feature toggle page"*/ 'app/features/explore/FeatureTogglePage')
          ),
    }
```

This way we could get a nice info page (something like below) instead of regular 404 (and avoid filtering at the bottom):

Screen Shot 2022-04-13 at 19 03 44

**Review by ifrost — APPROVED** [review]

File: public/app/routes/routes.tsx (hunk 1 above)
Comment (Elfo404) [reply public/app/routes/routes.tsx]: good point, modified to look like this:
Screenshot 2022-04-14 at 11 33 37

**Review by gelicia — APPROVED** [review]
