### PR TITLE
InfluxDB: Fix table parsing with backend mode

### LINKED ISSUE #76897: InfluxDB: Table rendering with transformation is broken when switching to backend mode
When you raw query with table format you get the response but UI is not able to show a table.

Image

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

This PR is addressing a couple of issues altogether. 
- We were using custom table parsing logic for backend mode. That's not needed anymore
- Also we were adding rowName to the field names. For instance when you query something `select qqq, eee from somewhere` we return the names as `somewhere.qqq and somewhere.eee`. This is not compatible with what we have with the frontend mode. 
- Panels with influxdb frontend mode if have transformations (i.e. `join by field`) is failing since backend is sending field names with rows
- Table parsing logic relies on query model but with raw queries we don't have it. So it is not working.

**Who is this feature for?**

InfluxDB influxql users with backend mode enabled.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/76897

**Special notes for your reviewer:**

### How to test
- Set feature toggle `influxdbBackendMigration=false`
- Create a panel that uses InfluxDB InfluxQL raw code editor in frontend mode
- Use query `SELECT usage_idle, usage_iowait FROM "cpu" WHERE $timeFilter`
- Select "Table" format
- Apply transformation "Join by Field"
- Apply field override to `usage_idle` and `usage_iowait`
- Run the query and observe you got `Time`, `usage_idle`, `usage_iowait` columns back
- enable feature toggle `influxdbBackendMigration=true`
- Refresh and see the table is not same or potentially broken
- Switch to this branch and run the same query on same panel
- Observe you have the same result and transformation, field overrides are working

# Release notice breaking change

For the existing backend mode users who have table visualization might see some inconsistencies on their panels. We have updated the table column naming. This will potentially affect field transformations and/or field overrides.  To resolve this either:
- Update transformation 
- Update field override

### CODE REVIEW

File: pkg/tsdb/influxdb/influxql/response_parser.go [hunk 1]
```diff
@@ -247,9 +254,11 @@ func formatFrameName(row models.Row, column string, query models.Query, frameNam
...
 }
 
-func buildFrameNameFromQuery(row models.Row, column string, frameName []byte) []byte {
-	frameName = append(frameName, row.Name...)
-	frameName = append(frameName, '.')
+func buildFrameNameFromQuery(row models.Row, column string, frameName []byte, resultFormat string) []byte {
+	if resultFormat != "table" {
+		frameName = append(frameName, row.Name...)
+		frameName = append(frameName, '.')
+	}
```
Comment (itsmylife) [inline pkg/tsdb/influxdb/influxql/response_parser.go:261]: Don't want to add the row name in table responses for frontend compatibility

**Review by bohandley — APPROVED** [review]
LGTM!
