### PR TITLE
PublicDashboards: Data discrepancy fix. Use real datasource plugin when it is a public dashboard. 

### LINKED ISSUE #67556: Bug: Query options for prometheus DS get ignored
This issue is an attempt to collect all the data that we have and organize this task.
TLDR:
Public dashboard is ignoring query options like `format` or `type` and because of that, the panels are not rendering properly or differ from the original dashboard.
image

We have several issues opened caused by the same cause.
https://github.com/grafana/grafana/issues/60802 -> confirmed this can be fixed with the implementation suggested
https://github.com/grafana/grafana/issues/61984 -> confirmed this can be fixed with the implementation suggested
https://github.com/grafana/grafana/issues/72740

Escalations (some of them triggered a new issue)
https://github.com/grafana/support-escalations/issues/5739 -> confirmed this can be fixed with the implementation suggested
https://github.com/grafana/support-escalations/issues/5456
https://github.com/grafana/grafana/issues/71018 -> not confirmed
https://github.com/grafana/support-escalations/issues/6892 -> confirmed this can be fixed with the implementation suggested
https://github.com/grafana/support-escalations/issues/7002 -> confirmed this can be fixed with the implementation suggested

analysis by @juanicabanas
[This is the code line](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/datasource.tsx#L469) which changes the response between a dashboard and a public dashboard.
Basically, after the api request, the response is being transformed in the PrometheusDataSource class, while the PublicDashboardDataSource class doesn't do it.

There are many possible complex solutions:

We should make that transformation in the backend (I think that's the best solution)
We should add a method in DataSourceApi class like transformResponse, which will return the original response but can be overriden in the subclasses that want it. Therefore, after calling query https://github.com/grafana/grafana/blob/main/public/app/features/query/state/runRequest.ts#L201, call that method as well.
Should we start creating one PublicDashboardDataSource per every datasource, such as PrometheusPublicDashboardDataSource?
Should we change the way we call query inside PrometheusDataSource class and, instead of calling it from super.query(), make a state design pattern, where a method from a property is the one that is called and, based on wether it is PublicDashboard or Dashboard itself, initialize PrometheusDataSource class with one or another class, which has query method?

### PR DESCRIPTION
**Pull request by juanicabanas**
**What is this feature?**

It changes the way a public dashboard panel executes a query.
Instead of instantiating a fake datasource plugin to execute the query, now the real ds plugin is instantiated, which executes the query method.
DataSourceWithBackend query method is modified to execute public dashboard logic but, after this, keeps running real ds plugin code.

**Why do we need this feature?**

Data discrepancy between a dashboard and the public one.
See https://docs.google.com/document/d/1gUjIofbXEwQKCBSkzv0YlWQOCvqa6Ifz-9wV0VE1NmI/edit#heading=h.5sybau7waq2q

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/67556

**Special notes for your reviewer:**

Cherry pick from https://github.com/grafana/grafana/pull/73476

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/query/state/runRequest.ts [hunk 1]
```diff
@@ -194,7 +194,7 @@ export function callQueryMethod(
   );
 
   // If its a public datasource, just return the result. Expressions will be handled on the backend.
-  if (datasource.type === 'public-ds') {
+  if (!!config.publicDashboardAccessToken) {
```
Comment (ryantxu) [inline public/app/features/query/state/runRequest.ts:197]:
```suggestion
  if (config.publicDashboardAccessToken != null) {
```
maye 🤷🏻 -- supports both null and undefined

**Review by ryantxu — APPROVED** [review]
This looks much better!

File: public/app/features/query/state/DashboardQueryRunner/AnnotationsWorker.ts [hunk 2]
```diff
@@ -50,7 +50,7 @@ export class AnnotationsWorker implements DashboardQueryRunnerWorker {
       let datasourceObservable;
 
       if (config.publicDashboardAccessToken) {
-        const pubdashDatasource = new PublicDashboardDataSource(PUBLIC_DATASOURCE);
+        const pubdashDatasource = new PublicAnnotationsDataSource();
```
Comment (ryantxu) [inline public/app/features/query/state/DashboardQueryRunner/AnnotationsWorker.ts:53]: Is this still necessary?  won't the normal path work ok?  (and if not, would be an error anyway)

Comment (juanicabanas) [reply public/app/features/query/state/DashboardQueryRunner/AnnotationsWorker.ts:53]: So, we still need to have a class that inherits from DataSourceApi and has a query method implemented for the annotations flow.
That's because the normal flow takes a specific datasource (Grafana datasource) and executes the query method to get the annotations.

We could try getting the Grafana datasource and add an `if` in the query method to call the public dashboard endpoint or continue with the normal flow, but I don't want to add too many modifications to this PR.
Thoughts? @torkelo

Comment (torkelo) [reply public/app/features/query/state/DashboardQueryRunner/AnnotationsWorker.ts:53]: yea, we can look at that in a separate PR if it makes sense.

File: public/app/features/query/state/runRequest.ts (hunk 1 above)
Comment (torkelo) [reply public/app/features/query/state/runRequest.ts:197]:
```suggestion
  if (config.publicDashboardAccessToken) {
```

Why does this not work? And empty string is false

Comment (juanicabanas) [reply public/app/features/query/state/runRequest.ts:197]: I put !! in order to make it a boolean value, but it's the same when it's inside an if. I can change it

**Review by torkelo — APPROVED** [review]
