### PR TITLE
Tempo: Show error if transformTrace() is passed bad data to parse to JSON

### LINKED ISSUE #42131: Tempo: Show some error message when we could not transform response
In this issue https://github.com/grafana/grafana/issues/41646 the Tempo datasource just silently failed to transform the trace data and didn't show any error or message to the user, just didn't display any data.

We should propagate the error to the user.

### PR DESCRIPTION
**Pull request by CatPerry**
**What this PR does / why we need it**:
- This PR fixes the issue where, the function `parseJsonData` is passed bad data and fails silently. We need to surface an error so that the frontend notifies the user.
- This PR also adds a test for the a function written by @connorlindsey in the same file `transformFromOTLP()` that also surfaces an error if it receives bad data. I was just testing my own and was doing so by adding a test to his, so just thought I'd leave that test. LMK if it's wrong!

**Which issue(s) this PR fixes**:
Closes [Tempo: Show some error message when we could not transform response](https://github.com/grafana/grafana/issues/42131) 

**Special notes for your reviewer**:
I did not put bad data into the UI to trigger this, instead, by @connorlindsey suggestion, I used TDD. So attached you'll see the tests returning the correct `console.error`. Then I mocked those console errors, so that you dont actually see them when running the test suite. 

***Test of bad data, returns a console error and surfaces the error to Grafana global alerting `JSON is not valid OpenTelemetry format`***

Screen Shot 2022-01-31 at 3 31 55 PM

Screen Shot 2022-01-31 at 3 32 06 PM

***With mocking of console.error and passing tests***
Screen Shot 2022-01-31 at 3 32 21 PM

### CODE REVIEW

File: public/app/plugins/datasource/tempo/resultTransformer.ts [hunk 1]
```diff
@@ -488,7 +488,12 @@ export function transformTrace(response: DataQueryResponse, nodeGraph = false):
     return emptyDataQueryResponse;
   }
 
-  parseJsonFields(frame);
+  try {
+    parseJsonFields(frame);
+  } catch (error) {
+    console.error(error);
+    return { error: { message: 'JSON is not valid OpenTelemetry format: ' + error }, data: [] };
```
Comment (connorlindsey) [inline public/app/plugins/datasource/tempo/resultTransformer.ts:495]: Because the trace isn't being uploaded via JSON, we should update the error message to something like `Unable to parse trace response` or `Invalid trace data`

File: public/app/plugins/datasource/tempo/resultTransformer.test.ts [hunk 2]
```diff
@@ -54,3 +54,70 @@ describe('transformFromOTLP()', () => {
     expect(res.data[0]).toMatchObject(otlpDataFrameFromResponse);
   });
 });
+
+describe('transformFromOTLP()', () => {
+  // Mock the console error so that running the test suite doesnt throw the error
+  const origError = console.error;
```
Comment (connorlindsey) [inline public/app/plugins/datasource/tempo/resultTransformer.test.ts:60]: This is really nice and cleans up the logs when running tests, great addition!

File: public/app/plugins/datasource/tempo/resultTransformer.test.ts [hunk 3]
```diff
@@ -54,3 +54,70 @@ describe('transformFromOTLP()', () => {
...
+  beforeEach(() => (console.error = consoleErrorMock));
+
+  test('if passed bad data, will surface an error', () => {
+    const res = transformFromOTLP(
+      (badOTLPResponse.batches as unknown) as collectorTypes.opentelemetryProto.trace.v1.ResourceSpans[],
+      false
+    );
+
+    expect(res.data[0]).toBeFalsy();
+    expect(res?.error?.message).toContain('JSON is not valid OpenTelemetry format');
```
Comment (connorlindsey) [inline public/app/plugins/datasource/tempo/resultTransformer.test.ts:72]: First conditional is unnecessary as res is defined

Comment (connorlindsey) [reply public/app/plugins/datasource/tempo/resultTransformer.test.ts:72]: Also would consider switching toContain(string) to expect the message to be truthy

File: public/app/plugins/datasource/tempo/resultTransformer.test.ts [hunk 4]
```diff
@@ -54,3 +54,70 @@ describe('transformFromOTLP()', () => {
...
+    // if it does have resources, no error will be thrown
```
Comment (connorlindsey) [inline public/app/plugins/datasource/tempo/resultTransformer.test.ts:73]: Not sure what this next part is testing. I think it can be removed

**Review by connorlindsey — CHANGES_REQUESTED** [review]
Looks great! Just a few small changes: need to update the error message and a few small changes in the tests

File: public/app/plugins/datasource/tempo/resultTransformer.test.ts (hunk 4 above)
Comment (connorlindsey) [reply public/app/plugins/datasource/tempo/resultTransformer.test.ts:73]: I think we should just remove it as it doesn't test any new behavior or new data. Given a falsy value (res.data[0]) and a truthy value (the resources object you pass in), of course it's going to be truthy

**Review by connorlindsey — APPROVED** [review]
