### PR TITLE
Cloud Monitoring: Adds metric type to Metric drop down options

### LINKED ISSUE #42931: Datasource Google Cloud Monitoring incorrectly deduplicates metrics names
Google Cloud Monitoring have a lot of duplicated metric names under the same Service and the UI incorrectly deduplicates these which can make it impossible to choose the exact one you want. 

Example:
```json
{
      "valueType": "DOUBLE",
      "metricKind": "CUMULATIVE",
      "type": "kubernetes.io/anthos/container/cpu/core_usage_time",
      "unit": "s{CPU}",
      "service": "kubernetes.io",
      "serviceShortName": "kubernetes",
      "displayName": "CPU usage time",
      "description": "Cumulative CPU usage on all cores used by the container in seconds."
}, {
      "valueType": "DOUBLE",
      "metricKind": "CUMULATIVE",
      "type": "kubernetes.io/container/cpu/core_usage_time",
      "unit": "s{CPU}",
      "service": "kubernetes.io",
      "serviceShortName": "kubernetes",
      "displayName": "CPU usage time",
      "description": "Cumulative CPU usage on all cores used by the container in seconds."
},
```

These two metrics are completely different but one of them is randomly removed from the UI, which I think is caused by google cloud monitoring metrics descriptors api call doesn't return data sorted. This causes further confusion as you might have data on one of the metrics but not the others and when you use the explore data can just disappear.

I did a quick hack in https://github.com/grafana/grafana/blob/2655be61b6dbf548282f3370c74339152cec2e29/pkg/tsdb/cloudmonitoring/resource_handler.go#L94-L95

```go
		typeParts := strings.SplitN(resp.Descriptors[i].Type, "/", 3)
		resp.Descriptors[i].Service = typeParts[0] + "/" + typeParts[1]
		resp.Descriptors[i].ServiceShortName = strings.SplitN(resp.Descriptors[i].Service, ".", 2)[0] + " (" + typeParts[1] + ")"
```
to verify the issue and a possible fix

### PR DESCRIPTION
**Pull request by tw1nk**
**What this PR does / why we need it**:
This pull request fixes an issue in the UI for google cloud monitoring where it was impossible to select certain metric types

**Which issue(s) this PR fixes**:
#42931

Fixes #42931

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/datasource/cloud-monitoring/components/Metrics.tsx [hunk 1]
```diff
@@ -39,6 +40,21 @@ export function Metrics(props: Props) {
     projectName: null,
   });
 
+  const theme = useTheme2();
+  const styles = getSelectStyles(theme);
+  const getStyle = stylesFactory((theme: GrafanaTheme2) => {
```
Comment (sunker) [inline public/app/plugins/datasource/cloud-monitoring/components/Metrics.tsx:45]: stylesFactory is deprecated. Can you use the `useStyles` hook instead? Also, please break this out into a separate `getStyles` function so that we follow the same pattern as in other components.

**Review by sunker — COMMENTED** [review]
Looks great! Thanks for creating this PR. Just added a nit comment. 

Adding the new custom option component is slowing down the render function a bit. It's fine in most cases, but for services such as the `kubernetes` one that has a lot of metrics it becomes pretty obvious. So I still think we should split up the services in smaller chunks, like you suggested in [this](https://github.com/grafana/grafana/issues/42931) issue. However, that would introduce a breaking change so let's save it for the next major release.

**Review by sunker — APPROVED** [review]
LGTM
