### PR TITLE
Datasource API: #32556 resolve readonly datasources can be modified

### LINKED ISSUE #32556: Config: Readonly datasources can be modifed
**What would you like to be added**:

Provisioned datasources are marked as readonly but it seems that it's still possible to edit them with the API and make them editable. Could it / should it be prevented in the backend? 

In theory it shouldn't be possible to do it directly from the UI, but recently we fixed [a bug ](https://github.com/grafana/grafana/pull/31823#issuecomment-795715620) where a button in the configuration panel accidentally submitted the form sending a PUT request with a new config. For non-provisioned datasources it simply saved the configuration, but for provisioned/readonly datasources it actually managed to modify the config in the database.

Would it be possible to reject all modifications to provisioned datasources?

**Steps to reproduce**

1. Open the configuration editor of a provisioned datasource and copy it's JSON config from the network tab:

Screenshot 2021-03-31 at 15 55 53

2. Copy the request as cURL:

Screenshot 2021-03-31 at 15 57 13

3. Paste the copied cURL and modify it:

* add `-x 'PUT'`
* add `-H 'content-type: application/json'`
* add `--data-raw 'JSON config'` (use the JSON config copied from the network tab)
* modify JSON config, e.g. change the name (for consecutive updates change the `version` as well)

example:

```diff
 curl 'http://localhost:3000/api/datasources/20' \
+  -X 'PUT' \
+  -H 'content-type: application/json' \
+ --data-raw '{"id":20,"uid":"8vZgeQyGk","orgId":1,"name":"gdev-mysql-changed","type":"mysql","typeLogoUrl":"","access":"proxy","url":"localhost:3306","password":"","user":"grafana","database":"grafana","basicAuth":false,"basicAuthUser":"","basicAuthPassword":"","withCredentials":false,"isDefault":false,"jsonData":{},"secureJsonFields":{"password":true},"version":1,"readOnly":true}' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'x-grafana-org-id: 1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: ...' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:3000/datasources/edit/20' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Cookie: grafana_user=admin;  ... ' \
  --compressed
```

4. Run the command in the terminal.

Current result: the request is submitted and provisioned datasource becomes editable.
Expected result: the request should be rejected

**Why is this needed**:

As I mentioned in theory it shouldn't be possible to do it directly from the UI, but it may happen because of bugs. Also - are there are any valid cases where overriding a provisioned data source would be needed?

### PR DESCRIPTION
**Pull request by jalevin**
**What this PR does / why we need it**:
Currently, read only datasources can be modified through the api. This PR fixes this hole and adds tests for it.

**Which issue(s) this PR fixes**:
#32556 

Fixes #32556 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by pianohacker — APPROVED** [review]

File: pkg/api/datasources.go [hunk 1]
```diff
@@ -309,6 +314,15 @@ func (hs *HTTPServer) UpdateDataSource(c *models.ReqContext) response.Response {
 		return resp
 	}
 
+	ds, err := getRawDataSourceById(c.Req.Context(), cmd.Id, cmd.OrgId)
+	if err != nil {
+		return response.Error(409, "Datasource has already been updated by someone else. Please reload and try again", err)
```
Comment (marefr) [inline pkg/api/datasources.go:319]: Same handling as delete datasource? The 409/conflict is handled further down after trying to update the datasource - do we need to have it when getting a datasource as well??

```suggestion
		if errors.Is(err, models.ErrDataSourceNotFound) {
			return response.Error(404, "Data source not found", nil)
		}
		return response.Error(500, "Failed to update datasource", err)```

File: pkg/api/datasources.go [hunk 2]
```diff
@@ -309,6 +314,15 @@ func (hs *HTTPServer) UpdateDataSource(c *models.ReqContext) response.Response {
...
+	}
+
+	if ds.ReadOnly {
+		return response.Error(400, "Cannot update datasource", models.ErrDatasourceIsReadOnly)
```
Comment (marefr) [inline pkg/api/datasources.go:323]: Same handling as delete datasource?

```suggestion
		return response.Error(403, "Cannot update read-only data source", nil)```

**Review by marefr — CHANGES_REQUESTED** [review]
See comments/suggestions.

File: pkg/api/datasources.go (hunk 1 above)
Comment (jalevin) [reply pkg/api/datasources.go:319]: We left this behavior in place in the event that the frontend was relying on getting a 409 somewhere. 

The thinking with the 400 vs a 404 is that this is an improper request due to the datasource being read only, rather than not found.

Happy to make that change, I'll defer to you.

Comment (marefr) [reply pkg/api/datasources.go:319]: > You would also get a 409 when updating a datasource that did not exist.

True, but by returning a 404 should make things more consistent so I think we should take the opportunity to fix that. The difference in Grafana UI is that there will be a different error message.

> Happy to make that change, I'll defer to you.

Given above I think my suggestions makes more sense

**Review by marefr — APPROVED** [review]
Great LGTM

**Comment by marefr** [comment]
Think you have to sync with latest main changes to be able to build properly
