### PR TITLE
TablePanel: Fix JSON tooltip positioning

### LINKED ISSUE #24322: TablePanel: JSON view tooltip position is off
Replicate use Elasticsearch in Logs or Raw document mode 

Screenshot from 2020-05-06 09-38-02

### PR DESCRIPTION
**Pull request by tskarhed**
It needed a positioned block element, that's why it didn't work properly
Closes #24322
Check by using Elastic data source in logs mode and cell display mode JSON view.

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/JSONViewCell.tsx [hunk 1]
```diff
@@ -21,7 +21,14 @@ export const JSONViewCell: FC<TableCellProps> = props => {
   return (
     <div className={cx(txt, tableStyles.tableCell)}>
       <Tooltip placement="auto" content={content} theme={'info'}>
-        <span>{displayValue}</span>
+        <div
+          className={css`
+            overflow: hidden;
+            text-overflow: ellipsis;
+          `}
+        >
```
Comment (torkelo) [inline packages/grafana-ui/src/components/Table/JSONViewCell.tsx:29]: can we add this to table style file

**Review by torkelo — APPROVED** [review]
