### PR TITLE
Cloudwatch: Fix missing defaultRegion

### LINKED ISSUE #35369: MissingRegion error for Cloudwatch alerts since upgrade to 8.0.0
**What happened**:
I have upgraded Grafana to 8.0.0
Although the dashboards work as expected (including data coming from Cloudwatch) the alerts fired immediately with the following error:

```
Execution Error: request handler response error {MissingRegion: could not find region configuration A <nil> [] [] 0xc000b620f0}
```

**What you expected to happen**:
No errors from alerts

**How to reproduce it (as minimally and precisely as possible)**:
Create a Cloudwatch data source in v7 with a default region selected, create an alert but use the "default" region. Upgrade to v8, the alert fails.

**Anything else we need to know?**:
In the panel config, when changing the "default" region to a specific version, the alert works again, so it must be something with the default region from the data source config not taken into account.

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Docker (grafana/grafana image)
- User OS & Browser: N/A
- Grafana plugins: Core only
- Others: -

### PR DESCRIPTION
**Pull request by andresmgot**
**What this PR does / why we need it**:

Fixes a typo in the data source definition of Cloudwatch. This caused that the default region was not automatically detected.

**Which issue(s) this PR fixes**:

Fixes #35369

**Special notes for your reviewer**:

Added some basic test for the function.

### CODE REVIEW

File: pkg/tsdb/cloudwatch/cloudwatch.go [hunk 1]
```diff
@@ -102,7 +102,7 @@ func NewInstanceSettings() datasource.InstanceFactoryFunc {
 	return func(settings backend.DataSourceInstanceSettings) (instancemgmt.Instance, error) {
 		jsonData := struct {
 			Profile       string `json:"profile"`
-			Region        string `json:"defaulRegion"`
+			Region        string `json:"defaultRegion"`
```
Comment (joshhunt) [inline pkg/tsdb/cloudwatch/cloudwatch.go:105]: 😱

**Review by joshhunt — APPROVED** [review]

**Comment by joshhunt** [comment]
I meant to say - i love the addition of tests!

**Review by sunker — APPROVED** [review]
Tested and it works as expected.
