### PR TITLE
Make value mappings correctly interpret numeric-like strings

### LINKED ISSUE #29949: ValueMappings: Support string value mappings when value can be parsed as a number (For example IP Address)
**What happened**:
Matfching rules for Value=>Text mappings are not working for strings in a table. It appears that it's interpreting the IP addresses as numbers and ignoring everything beginning with the second `.` character. I have tried both setting the table's default Units to String, as well as using field overrides to do it. That made no difference.

**What you expected to happen**:

I expect to be able to put an IP address in the Value field and a replacement string in the Text field to see my replacement string in the table instead of the IP address.

**How to reproduce it (as minimally and precisely as possible)**:

This table is constructed of Prometheus metrics with the labels shown as columns. All 3 columns in my screenshot are the same underlying data, but I created this to show the difference in behavior. The first column has no overrides. The second one is matching against "169.254.antyhing" to show that it matches every value that begins with `169.254`. The third column shows that `169.253` is not a match.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.3.6 (ea06633c34)
- Data source type & version: Prometheus 2.18.1
- OS Grafana is installed on: Ubuntu Bionic
- User OS & Browser: Debian Buster, Firefox 78.6.0esr (64-bit)
- Grafana plugins: Core, Grafana Image Renderer, Pie Chart, Status Map, worldPing
- Others:

image

### LINKED ISSUE #30764: Grafana v7.4.0-beta1: value mappings in override applying to all columns
Hello together,
I wanted to report an Bug.

The value overrides all values in the table, see pictures below

Grafana  Version: Grafana v7.4.0-beta1
In version 7.3.7 everything works

Image1s
Image2

### PR DESCRIPTION
**Pull request by dprokop**
**What this PR does / why we need it**:
Value mappings were incorrectly applied when mapping was applied to numeric-like strings.
For example a value 20/1 and 20/2 would be mapped to the same text if the mapping was set to 20/1 -> 'Some text'. That's because we were parsing (parseFloat) the incomming value and the result of it would for both values and the mapping be 20.

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/30764
Fixes https://github.com/grafana/grafana/issues/29949

### CODE REVIEW

File: packages/grafana-data/src/utils/valueMappings.ts [hunk 1]
```diff
@@ -93,3 +95,9 @@ const isNullValueMap = (mapping: ValueMap): boolean => {
   }
   return mapping.value.toLowerCase() === 'null';
 };
+
+// Ref
```
Comment (dprokop) [inline packages/grafana-data/src/utils/valueMappings.ts:99]:
```suggestion
// Ref https://stackoverflow.com/a/42356340
```

File: packages/grafana-data/src/utils/valueMappings.ts [hunk 2]
```diff
@@ -93,3 +95,9 @@ const isNullValueMap = (mapping: ValueMap): boolean => {
   }
   return mapping.value.toLowerCase() === 'null';
 };
+
+// Ref https://stackoverflow.com/a/42356340
+export function isNumeric(num: any) {
+  num = '' + num;
+  return !isNaN(num as number) && !isNaN(parseFloat(num));
+}
```
Comment (hugohaggmark) [inline packages/grafana-data/src/utils/valueMappings.ts:103]: Could almost be written as `return Boolean(Number(num));` but it fails for boolean values :(

**Review by hugohaggmark — APPROVED** [review]
Skilled work, love the tests 🎉

File: packages/grafana-data/src/utils/valueMappings.ts (hunk 2 above)
Comment (hugohaggmark) [inline packages/grafana-data/src/utils/valueMappings.ts:103]: I guess this would work, at least all the tests are passing 😉 
```suggestion
export function isNumeric(num: any) {
  if (num === true) {
    return false;
  }

  return Boolean(Number(num));
}
```

**Comment by dprokop** [comment]
Ah not, some tests are red!

**Comment by hugohaggmark** [comment]
> Ah not, some tests are red!

My bad I just ran the tests in `packages/grafana-data/src/utils/valueMappings.test.ts`

**Comment by dprokop** [comment]
> My bad, I just checked the tests in packages/grafana-data/src/utils/valueMappings.test.ts
@hugohaggmark not your falt. Singlestat tests surfaced a legitimate issue with the code, fixing it.
