### PR TITLE
Dashboard: Fix issue where unsaved changes warning would appear even after save, and not being able to change library panels.

### LINKED ISSUE #54443: Dashboard: Unsaved changes prompt is displayed with no changes when editing a panel
**What happened**:

When we save a dashboard from Panel Edit, if we move away from the dashboard the "Unsaved changes prompt" is displayed with no changes. 

https://user-images.githubusercontent.com/239999/187440895-5468461f-9b42-4237-a823-d3908c20656d.mp4

**What you expected to happen**:

It should not be displayed with zero changes 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: V9.1.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #54443 Unsaved changes warning after saving change from panel edit 
Fixes #52855 Changing Libray panels are not taking effect when you leave panel edit  (Alt fix that issue) 

After we switched to dirty tracking instead of full json diff it's been a bumpy road of many unsaved changes issues

It's get's very complicated with panel edit where we have to apply the change to the dashboard when leaving panel edit (if a change has been made AND if it's been saved) but if it has been saved that should not be seen as a dity change in the dashboard (which it is currently in main).  

There is also a bug with libray panels where after saving them configRev was set to 0 so when leaving panel edit the editor actions exitPanelEditor did not recognize any panel edit change.

Tried to solve this but just could not figure out any simple change. it get's complicated that we really have to increase configRev for at least one refresh cycle when going back to the dashboard so that the panel change is registered properly. 

This PR adds a new property to panel hasSavedPanelEdit change to remember that there is a change made but it has been saved.

### CODE REVIEW

File: public/app/features/dashboard/state/DashboardModel.ts [hunk 1]
```diff
@@ -494,6 +494,11 @@ export class DashboardModel implements TimeModel {
     for (const panel of this.panels) {
       panel.configRev = 0;
     }
+
+    if (this.panelInEdit) {
+      this.panelInEdit.hasSavedPanelEditChange = this.panelInEdit.configRev > 0;
```
Comment (dprokop) [inline public/app/features/dashboard/state/DashboardModel.ts:499]: Trying to understand this - the `configRev` changes with any change provided via panel editor. But it doesn't mean the model was changed. So now, when we go back to dashboard, we reset the `configRev` so that we perceive a panel as **not changed** ?

**Review by dprokop — APPROVED** [review]
I think I understand what's going on here, and the fix actually works.

File: public/app/features/dashboard/state/DashboardModel.ts (hunk 1 above)
Comment (torkelo) [reply public/app/features/dashboard/state/DashboardModel.ts:499]: @dprokop 
if configRev is > 0 that means there has been a config change. Since we are clearing here (as this is called from save dashboard), we need to remember that we saved a change, and hence configRev is 0 but there is a change there that is still not reflected in the panel in the dashboard (only in panelInEdit)

[the remark this answers is not in the document]
Comment (torkelo) [reply public/app/features/dashboard/state/DashboardModel.ts:499]: yea, a comment would be good

Comment (dprokop) [reply public/app/features/dashboard/state/DashboardModel.ts:499]: Ah, this now makes sense, thanks!

**Review by kaydelaney — APPROVED** [review]

**Comment by michaelkebe** [comment]
Updated to 9.1.5 and still have the problem of unsaved changes on a provisioned dashboard.
