### PR TITLE
CloudWatch Logs: Adds template variable support to log groups

### LINKED ISSUE #25099: CloudWatch Logs: Variables in log group name don't get interpolated
**What happened**:

Using variables in log group names seems to be not possible like:

`/aws/ecs/containerinsights/$cluster/performance`

**What you expected to happen**:

Variables values are  rendered.

**How to reproduce it (as minimally and precisely as possible)**:

Cloudwatch Log Insights Query Syntax with Log Group Name like: `/aws/ecs/containerinsights/$cluster/performance`

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Linux
- User OS & Browser: Mac / Safari
- Grafana plugins:
- Others:

### LINKED ISSUE #25185: CloudWatch Logs: Log Group not saved in panel settings when saving dashboard
**What happened**:
- Editing a log type panel with a CloudWatch Logs data source
- Set a log group
- Save the dashboard
- Close the dashboard
- Come back to the dashboard, edit the panel
- The "log group" field in the panel settings is empty and has to be filled out again
- This does not seem to affect fetching results, only the edit mode, so the log group is saved somewhere, just not displayed

**What you expected to happen**:
Display the log group that's been saved with the panel when editing the panel

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:
-
**Environment**:
Grafana version: Grafana v7.0.1 (ef5b586)
Data source type & version: CloudWatch
OS Grafana is installed on: CentOS 7
User OS & Browser: Mac OS 10.15.4, Chrome 83.0.4103.61
Grafana plugins: NA
Others: NA

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Lets a user enter custom values into the log groups selector, which are then interpolated with any template variable values.

**Which issue(s) this PR fixes**:
Closes #25099 
Closes https://github.com/grafana/grafana/issues/25185

### CODE REVIEW

File: public/app/plugins/datasource/cloudwatch/components/LogsQueryEditor.tsx [hunk 1]
```diff
@@ -12,15 +12,15 @@ import { CloudWatchLanguageProvider } from '../language_provider';
 import CloudWatchLink from './CloudWatchLink';
 import { css } from 'emotion';
 
-type Props = QueryEditorProps<CloudWatchDatasource, CloudWatchQuery>;
+type Props = QueryEditorProps<CloudWatchDatasource, CloudWatchQuery> & { allowCustomValue?: boolean };
```
Comment (aocenas) [inline public/app/plugins/datasource/cloudwatch/components/LogsQueryEditor.tsx:15]: Nitpick: we probably do not need this as a prop if we never set it to false.

File: public/app/plugins/datasource/cloudwatch/components/LogsQueryField.tsx [hunk 2]
```diff
@@ -130,6 +131,12 @@ export class CloudWatchLogsQueryField extends React.PureComponent<CloudWatchLogs
       return Promise.resolve();
     }
 
+    // No need to fetch matching log groups if the search term isn't valid
+    // This is also useful for preventing searches when a user is typing out a log group with template vars
+    if (!/^[\.\-_/#A-Za-z0-9]+$/.test(searchTerm)) {
```
Comment (aocenas) [inline public/app/plugins/datasource/cloudwatch/components/LogsQueryField.tsx:136]: Can we add some link to cloudwatch docs where the allowed chars are mentioned for future reference?

**Review by aocenas — COMMENTED** [review]
Seems like there is some weird behavior.
1. insert custom group
2. it does not run a query and just return LogGroup is required error. 
3. Add another group from the dropdown
4. Now it sends the query and returns error that the custom log group does not exists which is correct.
5. Remove existing log group, keeping only the custom one
6. This now works ok, runs the query and returns log group does not exist

Probably connected if I save panel with just custom log group it is not preserved when I reload. If I have custom + existing log group the values are persisted.

Also can we add some tests for the new functionality?

**Review by marefr — COMMENTED** [review]
Don't really have anything to say about the code. Let me know if you want me to test it eventually. 

Reading [here](https://grafana.com/docs/grafana/latest/features/datasources/cloudwatch/#query-variable), but nothing special about log groups. Wondering if it's already possible to define a variable query that populates with log groups or not? If not, maybe something to consider?

File: public/app/plugins/datasource/cloudwatch/components/LogsQueryEditor.tsx (hunk 1 above)
Comment (kaydelaney) [reply public/app/plugins/datasource/cloudwatch/components/LogsQueryEditor.tsx:15]: Should probably make it more explicit but it's false by omission in Explore, since template variables aren't supported there

File: public/app/plugins/datasource/cloudwatch/components/LogsQueryField.tsx (hunk 2 above)
Comment (kaydelaney) [reply public/app/plugins/datasource/cloudwatch/components/LogsQueryField.tsx:136]: Sure

**Comment by kaydelaney** [comment]
@aocenas Re: weird behavior, can you give slightly more explicit instructions to reproduce? Having difficulty getting the behavior you're describing.

**Comment by aocenas** [comment]
Cool was trying to repro and seem to be working fine now.

Can we also add tests for this if possible?

**Comment by kaydelaney** [comment]
@aocenas Yes, writing some tests now.

**Review by aocenas — APPROVED** [review]
Nice work
