### PR TITLE
Tempo: Provide tag value completion items while typing value

### LINKED ISSUE #43715: Tempo search autocomplete not handling values correctly
**What happened**:
After typing a tag name I am correctly presented with a list of possible values:

image

But when I begin typing a value it does not correctly filter down the list. Instead it appears to be showing tag values.

image
 
**What you expected to happen**:

Filter down the list of tag values based on the typed text after `=`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Type a tag name.
2. Type = and observe the list of possible values.
3. Begin typing a value and notice that it filters down to tag names instead of values.

**Anything else we need to know?**:
This possibly impacts Jaeger search as well. Untested.

**Environment**:
- Grafana version: v8.4.0-46847pre
- Data source type & version: Tempo
- OS Grafana is installed on: Linux container?
- User OS & Browser: Ubuntu 18.04/Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by connorlindsey**
**What this PR does / why we need it**:
Originally, tempo search provided tag values only after entering an '=', so when the user kept typing the value, it would revert to showing tag options for the autocomplete. Now, it more accurately checks whether the user it typing a value (after an =, before another space). 

**Which issue(s) this PR fixes**:
Fixes #43715

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/datasource/tempo/language_provider.ts [hunk 1]
```diff
@@ -37,7 +37,10 @@ export default class TempoLanguageProvider extends LanguageProvider {
     if (!value) {
       return emptyResult;
     }
-    if (text === '=') {
+
+    const query = value.endText.getText();
+    const isValue = query[query.indexOf(text) - 1] === '=';
```
Comment (connorlindsey) [inline public/app/plugins/datasource/tempo/language_provider.ts:42]: Text is a tag value if it's preceded by an '='

**Review by aocenas — APPROVED** [review]
