### PR TITLE
QueryEditor: Alerts view

### LINKED ISSUE #118053: Alert editor
Render alert editor in the editor section

### LINKED ISSUE #118055: Alert content header
Render the header, which is basically nothing for alerts. I think the designs are incorrect for this.

### PR DESCRIPTION
**Pull request by alexjonspencer1**
## Description

Resolves https://github.com/grafana/grafana/issues/118053
Resolves https://github.com/grafana/grafana/issues/118054
Resolves https://github.com/grafana/grafana/issues/118055

This PR wires up the alert view in the new query editor!

## Changes

* Create new alert-specific components: 
   * `AlertCard`
   * `AlertEditorRenderer`
* Update sidebar card border color logic - extracted to a compute function so we can accommodate alert state.
* Updates to `NewAlertRuleButton.tsx` api to ensure styles are better handled in the new header content paradigm.
* Add `variant` to sidebar card to handle "ghost state". This is pretty hacky right now as we don't have solidified designs for this. I want something to render for the demo, it's the only place in the app right now we really would show the sidebar without any cards, and it looks pretty bad without anything there 😄 
* I've left various comments in the code as well, which I hope are helpful for explaining other decisions and behaviour.

## Risks

* Not a tremendous amount of risk right now. The alerts view needs some hardening down the road (e.g. ghost card state)

#### Saved panel with alerts!

https://github.com/user-attachments/assets/7fbccba7-d209-4b06-9031-a87637a34842

#### Saved panel with no alerts, empty state + ghost card

https://github.com/user-attachments/assets/163a24b8-92b4-4da6-944f-332d52f8f755

#### Unsaved panel - not allowed to add alerts until panel is saved

image

## Testing Instructions

* Please pull this branch down and test with new panels (no alerts), existing panels with alerts, and adding alerts to panels!

## Reviewer Checklist

- [ ] Tests are added where applicable
- [ ] Issue is linked to PR
- [ ] Code pulled and tested
- [ ] Code is meaningfully improved if applicable

### CODE REVIEW

File: public/app/features/dashboard-scene/panel-edit/PanelEditNext/Actions.tsx [hunk 1]
```diff
@@ -10,15 +10,17 @@ export interface ActionItem {
...
 
 interface ActionsProps {
   contentHeader?: boolean;
   handleResetFocus?: () => void;
   item: ActionItem;
-  onDelete: () => void;
+  onDelete?: () => void;
   onDuplicate?: () => void;
-  onToggleHide: () => void;
+  onToggleHide?: () => void;
```
Comment (alexjonspencer1) [inline public/app/features/dashboard-scene/panel-edit/PanelEditNext/Actions.tsx:23]: Making all three optional as alert cards don't have any hover actions... yet at least.

File: public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/QueryEditorContext.tsx [hunk 2]
```diff
@@ -36,6 +36,7 @@ export interface QueryRunnerState {
 export interface AlertingState {
   alertRules: AlertRule[];
   loading: boolean;
+  isDashboardSaved: boolean;
```
Comment (alexjonspencer1) [inline public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/QueryEditorContext.tsx:43]: Controls empty state messaging in the alerts editor. Used in legacy implementation, so matching 1:1 for now.

File: public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/Sidebar/SidebarCard.tsx [hunk 3]
```diff
@@ -1,30 +1,30 @@
...
-  onToggleHide: () => void;
+  onDelete?: () => void;
+  onToggleHide?: () => void;
   showAddButton: boolean;
   item: ActionItem;
+  variant?: 'default' | 'ghost';
 }
 
 export const SidebarCard = ({
-  config,
```
Comment (alexjonspencer1) [inline public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/Sidebar/SidebarCard.tsx:26]: `config` is no longer needed in this component. It was being used for the left card border, but now that value is computed by `getEditorBorderColor`, using state already available in this component.

File: public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/Sidebar/QueryEditorSidebar.tsx [hunk 4]
```diff
@@ -56,27 +63,15 @@ export const QueryEditorSidebar = memo(function QueryEditorSidebar({
...
-              onDragEnd={onQueryDragEnd}
+          {isAlertView ? (
+            <AlertsView alertRules={alertRules} />
+          ) : (
+            <QueriesAndTransformationsView
+              queries={queries}
+              transformations={transformations}
+              onQueryDragEnd={onQueryDragEnd}
+              onTransformationDragEnd={onTransformationDragEnd}
             />
```
Comment (alexjonspencer1) [inline public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/Sidebar/QueryEditorSidebar.tsx:77]: Extracted to new components to keep this component clean! 🧹

File: public/app/features/dashboard-scene/panel-edit/PanelDataPane/NewAlertRuleButton.tsx [hunk 5]
```diff
@@ -1,33 +1,54 @@
+import { css } from '@emotion/css';
```
Comment (alexjonspencer1) [inline public/app/features/dashboard-scene/panel-edit/PanelDataPane/NewAlertRuleButton.tsx:1]: I had to make some updates to this component, which we technically own now as it's in panel-edit. Just to take some extra props for it to style nicely in the new header paradigm.

File: public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/Sidebar/SidebarCard.tsx [hunk 6]
```diff
@@ -220,5 +264,25 @@ function getStyles(
     hidden: css({
       opacity: 0.7,
     }),
+    ghostCardIcon: css({
```
Comment (sgriff96) [inline public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/Sidebar/SidebarCard.tsx:265]: Tiny nit: can we just put the css classes for the ghost card all next to each other?

File: public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/Sidebar/AlertsView.tsx [hunk 7]
```diff
@@ -0,0 +1,86 @@
...
+  name: 'New alert rule',
+  type: QueryEditorType.Alert,
+  isHidden: false,
+  alertState: null,
+};
+
+export function AlertsView({ alertRules }: AlertsViewProps) {
+  const { panel } = usePanelContext();
+
+  const theme = useStyles2((theme) => theme);
```
Comment (sgriff96) [inline public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/Sidebar/AlertsView.tsx]: I think you can do this instead
```
const theme = useTheme2();
```

File: public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/Sidebar/AlertsView.tsx [hunk 8]
```diff
@@ -0,0 +1,86 @@
...
+  const styles = useStyles2(getStyles);
+
+  if (alertRules.length === 0) {
+    return (
+      <div className={styles.container}>
+        <SidebarCard
+          id="ghost-alert"
+          isSelected={false}
+          item={GHOST_ALERT_ITEM}
+          onClick={() => {}} // Noop for the ghost alert
```
Comment (sgriff96) [inline public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/Sidebar/AlertsView.tsx:39]: This feels like an accessibility problem, maybe we should hide this from screen readers?

File: public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/Sidebar/AlertsView.tsx [hunk 9]
```diff
@@ -0,0 +1,86 @@
...
+      </div>
+    );
+  }
+
+  return (
+    <div className={styles.container}>
+      {alertRules.map((alert) => (
+        <AlertCard key={alert.alertId} alert={alert} />
+      ))}
+      {alertRules.length > 0 && (
```
Comment (sgriff96) [inline public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/Sidebar/AlertsView.tsx]: Think this can be removed since you already check for this in line 32

**Review by sgriff96 — CHANGES_REQUESTED** [review]
Left some comments but this is looking good overall

**Review by sgriff96 — APPROVED** [review]
This looks good to me now, but we definitely should prioritize adding tests to this soon
