### PR TITLE
Alerting: update rule versions on folder move

### LINKED ISSUE #88361: Alerting: when a folder is moved, the alert rules within the folder are not updated
### What happened?

When a folder with alerts is moved to another folder, the alerts within the folder are not updated and still have the old full path in the instance labels, notifications, etc.

### What did you expect to happen?

When a folder with alerts is moved, all alert rules within it should be updated with the new full folder path. The path should also be correct in the notifications.

It works correctly when I rename the folder: the new alert instances are created with the correct new path in the labels, and the alert notifications also contain the correct paths.

### Did this work before?

I don't know.

### How do we reproduce it?

I could reproduce this locally on `main` branch. In the Grafana Cloud it appears to be working correctly. 

How to reproduce:

1. Create an alert in a nested folder `folder / nested folder / alert rule`:

```
Dashboards
 - folder
   - nested folder
      * alert rule
```

3. After the alert is evaluated, move the `nested folder` out of the `folder`. For example, one level up:
```
Dashboards
 - folder
 - nested folder
    * alert rule
```
4. Make the alert fire
  a. When a new alert instance in the Pending state is created, it still has the old folder path in the labels.
  b. When the alert starts firing, the Firing alert instance also has the old folder path in the labels.
  c. The alert notification also has the old full path to the alert.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

_No response_

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by alexander-akhmetov**
**What is this feature?**

Changes `FolderTitleUpdated` event to `FolderFullPathUpdated` and emits the event not only when the folder is renamed but also when it's moved to another folder. Alerting is subscribed to it and when a folder is moved, all alert rules in it are updated now.

**Why do we need this feature?**

Currently when a folder with alerts is moved, the alerts within the folder are not updated and still have the old full path in the instance labels, notifications, etc. With this change the behavior is the same as if when the folder is renamed.

**Which issue(s) does this PR fix?**:

Fixes #88361

### CODE REVIEW

**Review by yuri-tceretian — COMMENTED** [review]
This fixes only one edge case of a more general, bigger problem. 
I like the name of the new event. However, it is not sent in all cases when folder's full path changes. For example, when title of a parent is changed, or when a parent folder is moved.

I think we should:
1. handle title changes.
2. send events for every children folder of the one that was updated. Alternative - provide them in the event info so listeners could do that by themselves.

@papagian do you have an idea how we can fix it in more general case?

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. Just letting you know I'm updating your PR's milestone to [11.2.x](https://github.com/grafana/grafana/milestone/529). If you need to see your changes in a previous version, please consider adding a backport label.

Thank you!

File: pkg/services/folder/folderimpl/folder.go [hunk 1]
```diff
@@ -685,14 +685,13 @@ func (s *Service) Update(ctx context.Context, cmd *folder.UpdateFolderCommand) (
...
-			if err := s.bus.Publish(ctx, &events.FolderTitleUpdated{
+			if err := s.bus.Publish(ctx, &events.FolderFullPathUpdated{
 				Timestamp: foldr.Updated,
-				Title:     foldr.Title,
 				ID:        dashFolder.ID, // nolint:staticcheck
 				UID:       dashFolder.UID,
 				OrgID:     cmd.OrgID,
 			}); err != nil {
-				s.log.ErrorContext(ctx, "failed to publish FolderTitleUpdated event", "folder", foldr.Title, "user", id, "namespace", namespace, "error", err)
+				s.log.ErrorContext(ctx, "Failed to publish FolderTitleUpdated event", "folderUid", foldr.UID, "user", id, "namespace", namespace, "error", err)
```
Comment (yuri-tceretian) [inline pkg/services/folder/folderimpl/folder.go:694]: message mentions old type of the event

**Review by yuri-tceretian — APPROVED** [review]
LGTM for this particular change. However, I still think we should address it in more general case cc @papagian

**Comment by alexander-akhmetov** [comment]
We could use [GetDescendants](https://github.com/grafana/grafana/blob/b6de9e9d3c406987cb45d40daafc1670e30abe56/pkg/services/folder/folderimpl/sqlstore.go#L536) to add UIDs of the folder and all nested folders to the event when the folder is moved or its title is changed. This would solve the issue, but I’m unsure if it's fine to call `GetDescendants` every time this happens. If not, I can probably come up with a workaround on the alerting side.

@papagian Would it be ok to call `GetDescendants` in the `Move` and `Update` (when the title is changed) or maybe there is a better way?

**Comment by yuri-tceretian** [comment]
I think we can call GetDescendants on the listener side. And then update the `IncreaseVersionForAllRulesInNamespace` to accept list of the folder UIDs.

**Comment by alexander-akhmetov** [comment]
The folder service does not expose `GetDescendants`, only `GetDescendantCounts`. :( So I implemented this on the folder service side (https://github.com/grafana/grafana/pull/88376/commits/8bcd728515ef92963f1532d4ebad715f9f8bdd82). The `FolderFullPathUpdated` event now includes a list of UIDs, which triggers a version update for all rules in the affected folders. Please let me know if any changes are needed.

**Comment by yuri-tceretian** [comment]
> The folder service does not expose GetDescendants, only GetDescendantCounts.

I think we could just expose it. However, I think the current implementation does make sense.

File: pkg/services/ngalert/ngalert.go [hunk 2]
```diff
@@ -487,13 +487,13 @@ func (ng *AlertNG) init() error {
...
 func subscribeToFolderChanges(logger log.Logger, bus bus.Bus, dbStore api.RuleStore) {
-	// if folder title is changed, we update all alert rules in that folder to make sure that all peers (in HA mode) will update folder title and
+	// if full path to the folder is changed, we update all alert rules in that folder to make sure that all peers (in HA mode) will update folder title and
 	// clean up the current state
-	bus.AddEventListener(func(ctx context.Context, evt *events.FolderTitleUpdated) error {
-		logger.Info("Got folder title updated event. updating rules in the folder", "folderUID", evt.UID)
-		_, err := dbStore.IncreaseVersionForAllRulesInNamespace(ctx, evt.OrgID, evt.UID)
+	bus.AddEventListener(func(ctx context.Context, evt *events.FolderFullPathUpdated) error {
+		logger.Info("Got folder full path updated event. updating rules in the folders", "folderUIDs", evt.UIDs)
+		_, err := dbStore.IncreaseVersionForAllRulesInNamespaces(ctx, evt.OrgID, evt.UIDs)
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/ngalert.go:494]: I wonder if we want to log keys of updated rules here.

**Review by yuri-tceretian — APPROVED** [review]
LGTM. Below are just nits

File: pkg/services/folder/folderimpl/folder.go [hunk 3]
```diff
@@ -947,13 +942,41 @@ func (s *Service) Move(ctx context.Context, cmd *folder.MoveFolderCommand) (*fol
...
+
 		return nil
 	}); err != nil {
 		return nil, err
 	}
 	return f, nil
 }
 
+func (s *Service) publishFolderFullPathUpdatedEvent(ctx context.Context, timestamp time.Time, orgID int64, folderUID string) error {
+	descFolders, err := s.store.GetDescendants(ctx, orgID, folderUID)
```
Comment (papagian) [inline pkg/services/folder/folderimpl/folder.go:957]: not blocking for this but it would be nice to have some [tracing](https://github.com/grafana/grafana/blob/main/contribute/backend/instrumentation.md#traces0

**Review by papagian — APPROVED** [review]
LGTM
regarding the general case, I'm not sure if there are other cases that would cause the fullpath to change except from renaming or moving
but both they use [store.Update()](https://github.com/grafana/grafana/blob/5e638b4af0d25dd40da53ca5ebd0f6ebf3f58d23/pkg/services/folder/folderimpl/store.go#L33) so we could wrap it together with the event publishing but performance-wise it makes no difference.
It would be nice to add some tracing to monitor the GetDescendants impact.

File: pkg/services/ngalert/ngalert.go (hunk 2 above)
Comment (alexander-akhmetov) [reply pkg/services/ngalert/ngalert.go:494]: I was thinking that we could completely remove fetching the keys in `IncreaseVersionForAllRulesInNamespaces` since we are not using them. Plus, it doesn't return updated IDs but makes another query to fetch UIDs, which is potentially inconsistent. What do you think?

Comment (yuri-tceretian) [reply pkg/services/ngalert/ngalert.go:494]: It would be great if we can log the UID of changed rules so we have a full picture of what happened.

File: pkg/services/folder/folderimpl/folder.go (hunk 3 above)
Comment (alexander-akhmetov) [reply pkg/services/folder/folderimpl/folder.go:972]: Added tracing: https://github.com/grafana/grafana/pull/88376/commits/dc0da4178c18e8ca7eb2b4673bcaa00eef6429c8

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. This is a friendly reminder that the Steady [11.2.x Release Branch](https://github.com/grafana/grafana/tree/v11.2.x) was cut this week, and that it includes the changes committed up to https://github.com/grafana/grafana/commit/b4126d3bce3627e9460e2db0e870c8d984be8e84. This PR was merged after it, so we wanted to let you know that you can add the `backport v11.2.x` label to to backport it and make it part of the next 11.2.x Patch Release, just in case you may have missed the news.

Thank you!
