### PR TITLE
Chore: Fix Random Walk scenario for Grafana DS

### LINKED ISSUE #73563: Default data source: Random Walk returns zeroes
### What happened?

When using default `-- Grafana --` data source with Random Walk query, it returns list of zeroes. The issue does not appear in TestData data source, which uses the same function to generate random data. The reason is that in the `-- Grafana --` data source values not initialized properly and everything is zero:
https://github.com/grafana/grafana/blob/4c37ba494e416a85397ca051355f7322390f022b/pkg/tsdb/grafanads/grafana.go#L168-L169

Maybe it's related to this PR #71332

### What did you expect to happen?

Random values should be returned

### Did this work before?

Random values was returned

### How do we reproduce it?

1. Create new panel
2. Select `-- Grafana --` data source
3. Select `Random Walk`

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: latest main branch
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

Grafana

### PR DESCRIPTION
**Pull request by andresmgot**
**What is this feature?**

The Random Walk scenario was initiating empty values when generating data.

**Which issue(s) does this PR fix?**:

Fixes #73563

**Special notes for your reviewer:**

Please check that:
- [X] It works as expected from a user's perspective.
- [X] If this is a pre-GA feature, it is behind a feature toggle.
- [X] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by xnyo — APPROVED** [review]
LGTM! Works great :smile:

File: pkg/tsdb/grafanads/grafana.go [hunk 1]
```diff
@@ -165,7 +165,11 @@ func (s *Service) doReadQuery(ctx context.Context, query backend.DataQuery) back
 func (s *Service) doRandomWalk(query backend.DataQuery) backend.DataResponse {
 	response := backend.DataResponse{}
 
-	model := testdatasource.JSONModel{}
+	model, err := testdatasource.GetJSONModel(nil)
```
Comment (wbrowne) [inline pkg/tsdb/grafanads/grafana.go:168]: Nit: Would prefer here:
```suggestion
	model, err := testdatasource.GetJSONModel(json.RawMessage{})
```

Alternatively, keep as is and add a comment to `GetJSONModel` just in case someone in the future doesn't catch this

**Review by wbrowne — APPROVED** [review]
LGTM!
