### PR TITLE
TimePickerWithHistory: Improve type handling when reading history from localStorage

### LINKED ISSUE #103775: TimePicker: Improve type handling when reading history from localStorage
### What happened?

```
Error: console.error: Cannot read properties of null (reading 'toISOString')
  at ? ([webpack://grafana/./public/app/core/components/TimePicker/TimePickerWithHistory.tsx:58:76](webpack://grafana/public/app/core/components/TimePicker/TimePickerWithHistory.tsx:58:76))
```
The app crashes displaying this error. Related to https://github.com/grafana/support-escalations/issues/15619#issuecomment-2789971191

### What did you expect to happen?

For it to fail gracefully. Use type `unknown`, when accessing objects from localStorage.

Update the type here:

```
function migrateHistory(values: LSTimePickerHistoryItem[]): TimePickerHistoryItem[] {
  return values.map((item) => {
    const fromValue = typeof item.from === 'string' ? item.from : item.from.toISOString();
    const toValue = typeof item.to === 'string' ? item.to : item.to.toISOString();

    return {
      from: fromValue,
      to: toValue,
    };
  });
}
```

### Did this work before?

Not that I am aware of.

We can use the currently available helper for this https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/utils/store.ts

### How do we reproduce it?

1. Add incorrectly formatted data to the timerangepicker history localstorage field
2. Voíla

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by ywzheng1**
**What is this feature?**

TimePickerWithHistory: Improve type handling when reading history from localStorage, from now on we only support `TimePickerHistoryItem` type range history for display. 
- Remove `migrateHistory` function 
- Remove `LSTimePickerHistoryItem `, only support `TimePickerHistoryItem` and anything doesn't match it will be remove from range history display
- Add MAX_HISTORY_ITEMS constant for better maintainability

**Before:**  invalid time range history will cause page broken and refresh can't fix the issue. 

https://github.com/user-attachments/assets/8941d72c-5127-479a-8588-e419aff2c38e

**After:** invalid time range history will be filter out from display. 

https://github.com/user-attachments/assets/a00dccee-6814-417d-b31e-371605fd8654

**Why do we need this feature?**

This change ensures that invalid time picker history items are properly filtered out before processing, preventing potential runtime errors and improving type safety throughout the component.

**Who is this feature for?**

All users

**Which issue(s) does this PR fix?**:

Fixes #103775 

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by joshhunt — COMMENTED** [review]
Nice stuff, and lovely tests!

Looking at this more in depth now, I think we can clean up the migration stuff further by just removing it. Thoughts?

File: public/app/core/components/TimePicker/TimePickerWithHistory.tsx [hunk 1]
```diff
@@ -55,16 +55,23 @@ function deserializeHistory(values: TimePickerHistoryItem[]): TimeRange[] {
...
+    .filter(isValidTimePickerValue) // Filter out invalid values
+    .map((item) => {
+      const fromValue = typeof item.from === 'string' ? item.from : item.from.toISOString();
+      const toValue = typeof item.to === 'string' ? item.to : item.to.toISOString();
+
+      return {
+        from: fromValue,
+        to: toValue,
+      };
+    });
```
[the remark this answers is not in the document]
Comment (ywzheng1) [reply public/app/core/components/TimePicker/TimePickerWithHistory.tsx]: Thanks for pointing this out! Totally agree, it makes sense to support just `TimePickerHistoryItem` to keep things clean. I’ve updated my changes so anything that doesn’t match `TimePickerHistoryItem` will be dropped from the history display.

File: public/app/core/components/TimePicker/TimePickerWithHistory.test.tsx [hunk 2]
```diff
@@ -52,15 +52,37 @@ describe('TimePickerWithHistory', () => {
...
+    const BAD_LOCAL_STORAGE = [
+      { from: '2022-12-03T00:00:00.000Z', to: '2022-12-03T23:59:59.000Z' },
+      {
+        from: '2022-12-01T00:00:00.000Z',
+        to: '2022-12-01T23:59:59.000Z',
+        raw: { from: '2022-12-03T00:00:00.000Z', to: '022-12-03T23:59:59.000Z' },
+      },
+      {},
+      { from: null, to: null },
+    ];
```
Comment (joshhunt) [inline public/app/core/components/TimePicker/TimePickerWithHistory.test.tsx:77]: small nit - i think these could do with a tiny comment on each option explaining why it's good/bad.

File: public/app/core/components/TimePicker/TimePickerWithHistory.test.tsx [hunk 3]
```diff
@@ -52,15 +52,37 @@ describe('TimePickerWithHistory', () => {
     expect(screen.getByText(/It looks like you haven't used this time picker before/i)).toBeInTheDocument();
   });
 
-  it('Should load with old TimeRange history', async () => {
+  it('Should not load with old TimeRange history', async () => {
```
Comment (joshhunt) [inline public/app/core/components/TimePicker/TimePickerWithHistory.test.tsx:55]: I don't think we need this test anymore. Now, i think this test is basically the same as the next test you've added ''Should load with valid time picker history only'. We just want to make sure it doesn't blow up if unexpected data is in local storage!

**Review by joshhunt — COMMENTED** [review]
Looks great! just two small nits with the test, and I think this is good to go!

File: public/app/core/components/TimePicker/TimePickerWithHistory.test.tsx (hunk 2 above)
Comment (ywzheng1) [reply public/app/core/components/TimePicker/TimePickerWithHistory.test.tsx]: removed 👍🏻

File: public/app/core/components/TimePicker/TimePickerWithHistory.test.tsx (hunk 3 above)
Comment (ywzheng1) [reply public/app/core/components/TimePicker/TimePickerWithHistory.test.tsx]: removed 👍🏻

**Review by joshhunt — APPROVED** [review]
