### PR TITLE
Annotations: Fix `min step` parameter interpolation in Prometheus annotations query

### LINKED ISSUE #63687: Prometheus annotation query ranges break apart when viewing more than a ~2h time range
**What happened**: With Prometheus-based annotation queries enabled on a dashboard, zooming out too far causes the annotation range to be processed instead as individual annotations, specifically when the annotation query time interval is greater than 60s.

Screenshot of an affected graph at a 3h time range:
Screenshot_20230223_142251

**What you expected to happen**: Prometheus-based annotations should respect the time interval returned from the query, rather than assuming it's 60s or less.

Screenshot of the same graph, but at a 2h time range:
Screenshot_20230223_142312

**How to reproduce it (as minimally and precisely as possible)**: Create a dashboard with a graph panel (any size), add a Prometheus-based annotation query to the dashboard, view a range where the annotation query is active, leave the "min step" field unset, and zoom out to a 3h range or greater.

**Anything else we need to know?**: This line appears to be the culprit. It assumes that the annotation's "min step" setting is the interval that the data source will also return data at, which causes problems when data is returned more sparsely: [plugins/datasource/prometheus/datasource.tsx:827](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/datasource.tsx#L827). I'm not familiar enough with the Grafana codebase to know exactly what the fix is though.

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: Prometheus 2.39.1
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Firefox 111
- Grafana plugins: defaults for Grafana Cloud
- Others:

### PR DESCRIPTION
**Pull request by konstantin-kornienko**
**Additional work:** This is a bug fix for Prometheus annotations, where when the range is extended, annotations displayed in a range (not individual) were broken apart. This fixes it by using the calculated step in the algorithm used to decide whether to show annotations over a range or as individual.

Fixes #63687

Historical info:

**What is this feature?**

Looks like the step is interpolated in annotationQuery, but not interpolated in processAnnotationResponse. Fixing that.

It doesn't fix the 'Annotation query ranges break apart when zooming' issue completely, but at least it makes possible using variables in the `min step` field.

**Why do we need this feature?**

Fixes errors in console when using variables (f.e. $__interval) in the `min step` field:

```
Error: Invalid interval string, has to be either unit-less or end with one of the following units: "y, M, w, d, h, m, s, ms"
```

Also, with some tweaking in variables/annotations query it can be almost usable on some zoom ranges. 

**Who is this feature for?**

Everyone who tries to visualize alerts from the prometheus data source on Grafana dashboards.

**Which issue(s) does this PR fix?**:

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by bohandley** [comment]
Hi @konstantin-kornienko  and thank you for your submission. 

I don't think this is the correct way to handle the interpolation of range and interval variables used in the annotation editor. 

First, we interpolate the macro interval variables on the backend for Prometheus. This is because we need to calculate the step correctly for the width of the panel. This sometimes means that the step you put in is not the step that is calculated. The step is then returned in the dataframe in the executed query string. If you were to create a regex to get this, you could avoid the error when using variables in the 'min step' field.

```
{
    ...
    "meta": {
        ...
        "executedQueryString": "Expr: up\nStep: 15m0s"
    },
    ...
}
```

Second, your solution interpolates the range which is not necessary, this would not be used in the step. 

I think the best way to solve the problem of the errors when using variables is to get the step directly from the data frame response.

File: packages/grafana-prometheus/src/datasource.ts [hunk 1]
```diff
@@ -537,7 +537,15 @@ export class PrometheusDatasource
...
-    const step = rangeUtil.intervalToSeconds(annotation.step || ANNOTATION_QUERY_STEP_DEFAULT) * 1000;
+    const scopedVars = {
+      ...this.getIntervalVars(),
+      ...this.getRangeScopedVars(options?.range ?? getDefaultTimeRange()),
+    };
+
+    const step = rangeUtil.intervalToSeconds(
+      this.interpolateString(annotation.step || ANNOTATION_QUERY_STEP_DEFAULT, scopedVars)
+    ) * 1000;
+
```
Comment (bohandley) [inline packages/grafana-prometheus/src/datasource.ts:548]:
```suggestion
    const input = frames[0].meta?.executedQueryString || '';
    const regex = /Step:\s*([\d\w]+)/;
    const match = input.match(regex);
    const stepValue = match ? match[1] : null;
    const step = rangeUtil.intervalToSeconds(
      this.interpolateString(stepValue || ANNOTATION_QUERY_STEP_DEFAULT, scopedVars)
    ) * 1000;
```

Comment (bohandley) [reply packages/grafana-prometheus/src/datasource.ts:548]: I do not want to get too excited about this suggestion, but it handled the annotation breaking apart on larger query ranges. Would you mind testing it out?

**Comment by konstantin-kornienko** [comment]
@bohandley , I've tested your fix. Now it's ideal (at least on my point of view).

The result:
Top row - before the fix - last 1h, 3h, 6h, 1d "zoom".
Bottom row - after the fix - last 1h, 3h, 6h, 1d "zoom".

result

Thanks a lot for your help!
Should I maybe add some tests to the PR?

**Comment by bohandley** [comment]
Awesome! @konstantin-kornienko yes please, add some tests and we can continue to move forward with this.

**Comment by konstantin-kornienko** [comment]
@bohandley , added one, could you please take a look? Thanks in advance.

File: packages/grafana-prometheus/src/datasource.test.ts [hunk 2]
```diff
@@ -1093,6 +1097,18 @@ describe('PrometheusDatasource2', () => {
         const results = await runAnnotationQuery([[2 * 60000], [1]]);
         expect(results.map((result) => [result.time, result.timeEnd])).toEqual([[120000, 120000]]);
       });
+
+      it('should handle non-default step in executedQuery', async () => {
```
Comment (bohandley) [inline packages/grafana-prometheus/src/datasource.test.ts:1101]: This is looking good. Can you make this test show that two different steps produce different results? One result with the standard step will show individual annotation and one result with a greater step with group the annoations.

Then update the test description to say something like "should group annotations over wider range when the step grows larger"

```
Smaller range
1m0s => [
          [120000, 120000],
          [240000, 240000],
          [600000, 600000],
          [720000, 720000],
        ]

2m0s => [
          [120000, 240000],
          [600000, 720000],
        ]

**Comment by bohandley** [comment]
Also, please use the lefthooks to lint the code
https://github.com/grafana/grafana/blob/HEAD/contribute/developer-guide.md#configure-precommit-hooks

File: packages/grafana-prometheus/src/datasource.test.ts (hunk 2 above)
Comment (konstantin-kornienko) [reply packages/grafana-prometheus/src/datasource.test.ts]: Good idea! Have tried to fix that.

**Comment by konstantin-kornienko** [comment]
> Also, please use the lefthooks to lint the code https://github.com/grafana/grafana/blob/HEAD/contribute/developer-guide.md#configure-precommit-hooks

Looks like it's working.

  EXECUTE > frontend-lint
  EXECUTE > frontend-betterer

SUMMARY: (done in 7.96 seconds)
✔️  frontend-lint
✔️  frontend-betterer

**Comment by bohandley** [comment]
Sorry, the left hook didn't fix the prettier issues, you will have to run Prettier with --write to fix

**Review by bohandley — APPROVED** [review]
LGTM! Thank you for your contribution!
