### PR TITLE
Scenes: Remove normal and library panels from layout or rows

### LINKED ISSUE #83477: Cannot remove panels if they are in a row
Removing a panel from the panel menu does not work if the panel is part of a row.

### LINKED ISSUE #83891: Be able to remove a library panel with the panel menu
Should be possible to remove a library panel from a dashboard using the panel menu.

Also make sure this works for library panels in rows.

### PR DESCRIPTION
**Pull request by mdvictor**
Allows panels and library panels to be removed through the panel menu. Also works for panels and library panels within rows.

Closes https://github.com/grafana/grafana/issues/83891
Closes https://github.com/grafana/grafana/issues/83477

### CODE REVIEW

File: public/app/features/dashboard-scene/scene/DashboardScene.tsx [hunk 1]
```diff
@@ -533,6 +534,58 @@ export class DashboardScene extends SceneObjectBase<DashboardSceneState> {
...
+      const layout = this.state.body;
+
+      if (layout instanceof SceneGridLayout || layout instanceof SceneFlexLayout) {
+        const children: SceneObject[] = layout.state.children;
+        const index = children.findIndex((child) => child.state.key === row?.state.key);
+
+        children.splice(index, 1, row);
+
+        layout.setState({ children });
+      }
```
Comment (mdvictor) [inline public/app/features/dashboard-scene/scene/DashboardScene.tsx:571]: I'm not sure if this is the best way to do it. I would've expected setting the row state to refresh the dashboard and show that the panel was removed since the layout is updated but it doesn't. I looked into `forceRenderChildren` as well but it doesn't work with the layout body, it rerenders only if I send it the entire scene as a param which seems like a lot of unnecessary computation.

Comment (dprokop) [reply public/app/features/dashboard-scene/scene/DashboardScene.tsx:597]: @mdvictor i think the issue you are facing is related to the fact that the SceneGridRow is actually not rendering it's children, so changing the state of that object will not result in a row re-render

Comment (torkelo) [reply public/app/features/dashboard-scene/scene/DashboardScene.tsx:597]: think layout.forceRender() should work here instead

Comment (mdvictor) [reply public/app/features/dashboard-scene/scene/DashboardScene.tsx]: Thank you folks, much cleaner. That worked!

**Review by dprokop — APPROVED** [review]
