### PR TITLE
Alerting: Improve default form values handling

### LINKED ISSUE #95937: Alerting: changing evaluation group for alert rule is broken (v11.1+) - groups modified instead of rules
### What happened?

Hi guys!
I'm reanimating #93337 - sadly, could solidly reproduce only after issue being closed :(

So, the setup:
- you have an Alert Rule with evaluation group "5m", interval "5m"
- you have another group, say "1m", interval "1m"
- you want to assign a rule a new group, 1m instead of 5m

**The problem**:
When you pick the "1m" group and hit Save rule, "1m" group changes its interval to 5m.

**Repro notes**:
- go to alert rule edit page, by pasting direct link in browser address bar
- OR navigate from alert rule link in messenger (slack, telegram etc)
- OR navigate from "Alert Rules" Grafana page and make sure to refresh the page
In those conditions issue reproduces.

When you navigate from Alert Rules page without refreshing, all works as expected.

@tonypowa @tomratcliffe sorry for mentioning directly, please look into this 🙏 
Consider this a critical one, since my users almost always come to rules from alerts in messengers and face this problem.

### What did you expect to happen?

Choosing a new group in Alert rule & Save rule:

- SHOULD change this particular Alert rule's evaluation group
- SHOULD NOT modify chosen evaluation group (or any other group)

### Did this work before?

I reckon it was broken in 11.1+

### How do we reproduce it?

See repro notes above

### Is the bug inside a dashboard panel?

NO

### Environment (with versions)?

Grafana: 11.1+
OS: Any
Browser: Any

### Grafana platform?

I don't know

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by konrad147**
This PR refactors default form values handling.
It tires to collect form values logic in one place

`formDefaults` - collects functions related to populating default form values from various sources
`formProcessing` collects functions related to necessary form processing

Files structure has been reorganizes a bit, to put `RuleEdtior` related file close to it - to organize the code by a `feature` instead of `file type`

Fixes https://github.com/grafana/grafana/issues/95937

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/alerting/unified/rule-editor/formProcessing.ts [hunk 1]
```diff
@@ -0,0 +1,150 @@
...
+  query: AlertQuery<AlertDataQuery | ExpressionQuery>
+): query is AlertQuery<AlertDataQuery> {
+  return !isExpressionQuery(query.model);
+}
+
+// the backend will always execute "hidden" queries, so we have no choice but to remove the property in the front-end
+// to avoid confusion. The query editor shows them as "disabled" and that's a different semantic meaning.
+// furthermore the "AlertingQueryRunner" calls `filterQuery` on each data source and those will skip running queries that are "hidden"."
+// It seems like we have no choice but to act like "hidden" queries don't exist in alerting.
+export const revealHiddenQueries = (ruleDefinition: RuleFormValues): RuleFormValues => {
```
Comment (konrad147) [inline public/app/features/alerting/unified/rule-editor/formProcessing.ts:126]: I changed the name from `ignoreHiddenQueries` because if I understand correctly, we don't remove any queries, we only remove the `hidden` query parameter

File: public/app/features/alerting/unified/components/rule-editor/alert-rule-form/AlertRuleForm.tsx [hunk 2]
```diff
@@ -109,19 +98,10 @@ export const AlertRuleForm = ({ existing, prefill }: Props) => {
       return formValuesFromPrefill(prefill);
     }
 
-    if (queryParams.has('defaults')) {
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rule-editor/alert-rule-form/AlertRuleForm.tsx:112]: `AlertRuleForm` is no longer responsible for parsing data from query string. Instead, other components will pass the default as `prefill`

File: public/app/features/alerting/unified/rule-editor/formDefaults.ts [hunk 3]
```diff
@@ -0,0 +1,157 @@
...
+    };
+  }
+
+  return setQueryEditorSettings(
+    setInstantOrRange(
+      revealHiddenQueries({
+        ...getDefaultFormValues(),
+        ...ruleFromQueryParams,
+        annotations: normalizeDefaultAnnotations(ruleFromQueryParams.annotations ?? []),
+        queries: ruleFromQueryParams.queries ?? getDefaultQueries(),
```
Comment (konrad147) [inline public/app/features/alerting/unified/rule-editor/formDefaults.ts:116]: I think all invocations of `getDefaultQueries` should take the parameter (like in line 139) but the `type` parameter can't be trusted in its current form

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 4]
```diff
@@ -204,11 +210,30 @@ export function GrafanaEvaluationBehaviorStep({
 
   const isNewGroup = useIsNewGroup(folderUid ?? '', group);
 
+  const handleFieldsDependecies: WatchObserver<RuleFormValues> = useCallback(
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:213]: Excercies: I do wonder if having one function handling dependencies could be easier to read/write than multiple watches and effects

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 5]
```diff
@@ -192,9 +196,11 @@ export function GrafanaEvaluationBehaviorStep({
 
   const isGrafanaAlertingRule = isGrafanaAlertingRuleByType(type);
   const isGrafanaRecordingRule = isGrafanaRecordingRuleByType(type);
-  const { groupOptions, loading } = useFolderGroupOptions(folder?.uid ?? '', enableProvisionedGroups);
+  const { groupOptions, intervalsByGroup, loading } = useFolderGroupOptions(folder?.uid ?? '', enableProvisionedGroups);
   const [isEditingGroup, setIsEditingGroup] = useState(false);
 
+  // TODO This is way suboptimal, but it requires more changes to make it right, especiall in EditRuleGroupModal
+  // dispatch(fetchPromAndRulerRulesAction({ rulesSourceName: GRAFANA_RULES_SOURCE_NAME }));
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:203]: @gillesdemey PR https://github.com/grafana/grafana/pull/97490 might improve this one

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 6]
```diff
@@ -192,9 +196,11 @@ export function GrafanaEvaluationBehaviorStep({
 
   const isGrafanaAlertingRule = isGrafanaAlertingRuleByType(type);
   const isGrafanaRecordingRule = isGrafanaRecordingRuleByType(type);
-  const { groupOptions, loading } = useFolderGroupOptions(folder?.uid ?? '', enableProvisionedGroups);
+  const { groupOptions, intervalsByGroup, loading } = useFolderGroupOptions(folder?.uid ?? '', enableProvisionedGroups);
   const [isEditingGroup, setIsEditingGroup] = useState(false);
 
+  // TODO This is way suboptimal, but it requires more changes to make it right, especiall in EditRuleGroupModal
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:202]: I'm not sure if I understand this TODO 🤔

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx (hunk 4 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:213]: Personally, i believe it would be easier to understand/maintain in a single place, also i can avoid duplication of useEffects observing the same fields..

File: public/app/features/alerting/unified/rule-editor/formDefaults.ts [hunk 7]
```diff
@@ -0,0 +1,157 @@
...
+
+import {
+  normalizeDefaultAnnotations,
+  revealHiddenQueries,
+  setInstantOrRange,
+  setQueryEditorSettings,
+} from './formProcessing';
+
+// even if the min interval is < 1m we should default to 1m, but allow arbitrary values for minInterval > 1m
+const GROUP_EVALUATION_MIN_INTERVAL_MS = safeParsePrometheusDuration(config.unifiedAlerting?.minInterval ?? '10s');
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/rule-editor/formDefaults.ts:29]: this '10s', shouldn't be the `GROUP_EVALUATION_INTERVAL_LOWER_BOUND` ?

File: public/app/features/alerting/unified/rule-editor/formProcessing.ts (hunk 1 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/rule-editor/formProcessing.ts:126]: 💯

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 8]
```diff
@@ -181,51 +153,42 @@ export function GrafanaEvaluationBehaviorStep({
...
 
-  const isNewGroup = useIsNewGroup(folderUid ?? '', group);
+  const isNewGroup = !existingGroup && !loadingGroups;
 
+  // synchronize the evaluation interval with the group name when it's an existing group
   useEffect(() => {
-    if (!isNewGroup && existingGroup?.interval) {
-      setEvaluateEvery(existingGroup.interval);
+    if (existingGroup) {
+      setValue('evaluateEvery', existingGroup.interval ?? DEFAULT_GROUP_EVALUATION_INTERVAL);
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:184]: is this necessary?

Comment (gillesdemey) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:184]: Yes, when we select a different group from the dropdown we need to update the interval of the form to make sure the form values are kept in sync with what the user has selected.

Ideally we'd store a "evaluation group" which contains both the name and the interval but that seemed like a much larger refactor.

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:184]: But I think this is for the existing group, not the selected one? (dependencies are on the `existingGroup`)

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 9]
```diff
@@ -53,48 +49,42 @@ import { RuleEditorSection } from './RuleEditorSection';
...
-  }, [rulerNamespace, enableProvisionedGroups]);
-
-  return { groupOptions, loading: isLoadingRulerNamespace };
+const namespaceToGroupOptions = (rulerNamespace: RulerRulesConfigDTO, enableProvisionedGroups: boolean) => {
+  if (!rulerNamespace) {
+    // still waiting for namespace information to be fetched
+    return [];
+  }
+
+  const folderGroups = Object.values(rulerNamespace).flat() ?? [];
```
Comment (tomratcliffe) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:72]: (based on the types) The `if` would always be falsy, as rulerNamespace is required. And then also the `??` operator isn't required as the first part will always be truthy

File: .betterer.results [hunk 10]
```diff
@@ -2670,6 +2652,25 @@ exports[`better eslint`] = {
       [0, 0, 0, "Unexpected any. Specify a different type.", "7"],
       [0, 0, 0, "Do not use any type assertions.", "8"]
     ],
+    "public/app/features/alerting/unified/rule-editor/CloneRuleEditor.tsx:5381": [
```
Comment (tomratcliffe) [inline .betterer.results:2655]: (Files were renamed, these aren't necessarily new)

File: public/app/features/alerting/unified/components/rule-editor/alert-rule-form/ModifyExportRuleForm.tsx [hunk 11]
```diff
@@ -63,9 +59,7 @@ export function ModifyExportRuleForm({ ruleForm, alertUid }: ModifyExportRuleFor
   const { returnTo } = useReturnTo('/alerting/list');
 
   const [exportData, setExportData] = useState<RuleFormValues | undefined>(undefined);
-
   const [conditionErrorMsg, setConditionErrorMsg] = useState('');
-  const [evaluateEvery, setEvaluateEvery] = useState(ruleForm?.evaluateEvery ?? DEFAULT_GROUP_EVALUATION_INTERVAL);
```
Comment (tomratcliffe) [inline public/app/features/alerting/unified/components/rule-editor/alert-rule-form/ModifyExportRuleForm.tsx:68]: ❤️

File: public/app/features/alerting/unified/components/rules/EditRuleGroupModal.test.tsx [hunk 12]
```diff
@@ -49,7 +61,8 @@ describe('EditGroupModal', () => {
 });
 
 describe('EditGroupModal component on cloud alert rules', () => {
-  const promDsSettings = mockDataSource({ name: 'Prometheus-1', uid: 'Prometheus-1' });
+  const { dataSource, rulerConfig } = mimirDataSource();
+  setupDataSources(dataSource);
```
Comment (tomratcliffe) [inline public/app/features/alerting/unified/components/rules/EditRuleGroupModal.test.tsx:65]: Nit, but it could cause confusion: It looks like `mimirDataSource` calls `setupDataSources` itself. So we don't technically need to call this here, but perhaps it makes it clearer anyway

File: public/app/features/alerting/unified/components/rules/EditRuleGroupModal.test.tsx [hunk 13]
```diff
@@ -29,18 +32,27 @@ const ui = {
...
-    const group = namespace.groups[0];
+  const { dataSource, rulerConfig } = mimirDataSource();
+  setupDataSources(dataSource);
 
-    render(<EditRuleGroupModal namespace={namespace} group={group} intervalEditOnly onClose={noop} />);
+  it('Should disable all inputs but interval when intervalEditOnly is set', async () => {
+    const rulerGroupIdentifier: RuleGroupIdentifier = {
+      dataSourceName: dataSource.name,
+      groupName: 'default-group',
+      namespaceName: 'my-namespace',
```
Comment (tomratcliffe) [inline public/app/features/alerting/unified/components/rules/EditRuleGroupModal.test.tsx:45]: (I think Gilles is fixing these tests, but this should change to `namespace-1` to match what's in the default mimir handlers)

Comment (gillesdemey) [reply public/app/features/alerting/unified/components/rules/EditRuleGroupModal.test.tsx:45]: Yep! I'm refactoring this test suite to use those :)

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rules/EditRuleGroupModal.test.tsx:45]: maybe we should expose a constant to figure out which values we can use in tests? @tomratcliffe

Comment (tomratcliffe) [reply public/app/features/alerting/unified/components/rules/EditRuleGroupModal.test.tsx:45]: There is a constant for `namespace-1` already, exposed somewhere else :) we need an ongoing effort to use constants/fixtures across our tests, IMO

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx (hunk 4 above)
Comment (konrad147) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx]: Yeah, this is the idea to remove `useEffects`

**Comment by gillesdemey** [comment]
Fixed merge conflicts, I'll give this another run to see if it resolves the original issue this was tackling.

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx (hunk 9 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:72]: Good catch!

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx (hunk 8 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:179]: the `existingGroup` will also update if the `group` from the `watch()` function is updated (in other words, when we either select a different group in an existing rule or select a group in a new rule form)

File: public/app/features/alerting/unified/components/rules/EditRuleGroupModal.test.tsx [hunk 14]
```diff
@@ -1,18 +1,18 @@
...
+import { RuleGroupIdentifier } from 'app/types/unified-alerting';
+
+import { GRAFANA_RULER_CONFIG } from '../../api/featureDiscoveryApi';
+import server, { setupMswServer } from '../../mockApi';
+import { mimirDataSource } from '../../mocks/server/configure';
+import { alertingFactory } from '../../mocks/server/db';
+import { rulerRuleGroupHandler as grafanaRulerRuleGroupHandler } from '../../mocks/server/handlers/grafanaRuler';
+import { rulerRuleGroupHandler } from '../../mocks/server/handlers/mimirRuler';
 import { GRAFANA_RULES_SOURCE_NAME } from '../../utils/datasource';
+import { grantPermissionsHelper } from '../rule-viewer/RuleViewer.test';
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rules/EditRuleGroupModal.test.tsx:15]: nit: we should move this to a test util file

File: public/app/features/alerting/unified/components/rules/RulesTable.tsx
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rules/RulesTable.tsx:1]: These changes are a side-effect of refactoring the `EditRuleGroupModal`

File: public/app/features/alerting/unified/rule-editor/formDefaults.ts (hunk 7 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/rule-editor/formDefaults.ts:29]: There's definitely something confusing going on here, I'll see if I can reason about this

**Review by gillesdemey — APPROVED** [review]
Code changes LGTM; also tested the issue this is trying to resolve and that works as intended ✅

**Comment by wanzirong** [comment]
Thank you for fixing this issue! I see that this PR has been merged into the main branch, but when checking the released versions, I found that the latest v11.5.0-v11.5.2 versions don't seem to include this fix (confirmed by searching for PR #97564 and through testing).

Could you please let me know in which version this fix is expected to be officially released? This information is quite important for our work planning.

Thank you!
