### PR TITLE
ImageRendering: Fixed incorrect increments/decrements of the rendering inflight counter.

### LINKED ISSUE #30860: Getting "Concurrent server side render limit reached" while rendering dashboard, with no real render requests
**What happened**:
Grafana with no concurrent render requests (config limit - concurrent_render_limit = 128) after some time (usually 2-3 weeks uptime) starts to generate "render limit reached" images. I tried to kill rendering plugin process - plugin-linux-x64-glibc, but only restart of the grafana server is helping.

**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately, have no idea.
I found no relevant logs (level = debug) at the time of rendering.

**Environment**:
- Grafana version: 7.3.5
- Data source type & version: -
- OS Grafana is installed on: Ubuntu 14.04
- User OS & Browser: curl
- Grafana plugins: rendering with grafana-image-renderer=2.0.0 (https://github.com/grafana/grafana-image-renderer)

### PR DESCRIPTION
**Pull request by knuzhdin**
**What this PR does / why we need it**:
Fixes arbitrary change of the rendering inflight counter (inProgressCount) due to race when incrementing or decrementing it

**Which issue(s) this PR fixes**:

Fixes #30860

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by knuzhdin** [comment]
Somehow swapping `"sync/atomic"` and `"time"` imports in `pkg/services/rendering/rendering.go` made `golangci-lint` (`lint-backend` test) happy

File: pkg/services/rendering/rendering.go [hunk 1]
```diff
@@ -154,7 +155,7 @@ func (rs *RenderingService) Render(ctx context.Context, opts Opts) (*RenderResul
 }
 
 func (rs *RenderingService) render(ctx context.Context, opts Opts) (*RenderResult, error) {
-	if rs.inProgressCount > opts.ConcurrentLimit {
+	if int(atomic.LoadInt32(&rs.inProgressCount)) > opts.ConcurrentLimit {
```
Comment (ying-jeanne) [inline pkg/services/rendering/rendering.go:158]: @marefr i am thinking could we just put concurrent_render_limit setting type to int64 or int32(if it is backward compatible) instead of cast forward/back int32/int.

**Review by ying-jeanne — COMMENTED** [review]
A nice pr, regarding what happened, we probably want some tests around it.

**Comment by knuzhdin** [comment]
> A nice pr, regarding what happened, we probably want some tests around it.

Thanks, I have not looked into tests infrastructure yet, and I do not know how to reproduce this issue reliably. But it looks like this race is much more probable when jobs are finishing (the counter was very rarely leaking to the negative values)

File: pkg/services/rendering/rendering.go (hunk 1 above)
Comment (marefr) [reply pkg/services/rendering/rendering.go:158]: Yes I believe so

**Comment by knuzhdin** [comment]
@marefr @AgnesToulet 
Is there anything I can do to push this request forward?

**Comment by knuzhdin** [comment]
@marefr @AgnesToulet
I do not know how its done here, but ping?

**Comment by marefr** [comment]
@knuzhdin sorry for slow response. Been crazy busy lately with the Grafana 8 release. We've asked for a test, but understand that is tricky. Think it would be enough with one test of the Render method called by two goroutines and then run the test with race detector enabled (`go test -race ...`). Let us know if you need help with that.

**Review by marefr — COMMENTED** [review]
After consideration think it's tricky/very hard to write proper tests for this given the current code. I've asked @AgnesToulet to review this since I'm busy with other things. Think the changes overall looks good though, but need to test it by putting some load on it with multiple users.

**Review by AgnesToulet — APPROVED** [review]
Thanks for you contribution! I was able to reproduce the issue by running some load tests in parallel and this PR fixes it.
