### PR TITLE
grafana/ui: Refactor Checkbox to fix alignment issues

### LINKED ISSUE #36063: ManageDashboards: Clicking the empty space between a checkbox and the folder icon selects the folder, but checkbox isn't checked
**What happened**:

If you click the empty space between a checkbox and the folder icon, the UI will update to indicate that _a_ folder has been selected, but the checkbox will not show that it is checked. 

https://user-images.githubusercontent.com/46142/123085699-76111000-d41a-11eb-9353-af9451cd8a83.mp4

I presume this is because the Checkbox uses an onClick handler rather than onChange to toggle the checked state, and the checkbox is takes up more space than is visible.

https://github.com/grafana/grafana/blob/83860bdcc3dc93574d8a1a962b01afaaea52a61b/public/app/features/search/components/SectionHeader.tsx#L49

SearchItem also uses onClick rather than onChange

https://github.com/grafana/grafana/blob/83860bdcc3dc93574d8a1a962b01afaaea52a61b/public/app/features/search/components/SearchItem.tsx#L57

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by joshhunt**
**What this PR does / why we need it**:

It's tricky to use `<Checkbox />` in your UI outside of traditional forms-with-labels (what I'm sure it was designed for), mainly because the actual visual checkbox itself does not occupy space in the DOM as it is absolutely positioned within some padding.

You can see the impacts of this when consumers write janky CSS to go into the internals and change the properties to get it to work as they want

https://github.com/grafana/grafana/blob/58bbe17d8434a28eefa25b1af0675a748d4d108a/public/app/features/search/components/SearchCheckbox.tsx#L21-L32

This PR is a slight refactor of checkbox to make the actual Checkbox take up space in the DOM and remove the padding/margin/space around it.

Of course, this regresses Checkbox in the Manage Dashboards page, so I've made an attempt to try and fix it, but I'm now I'm getting funny behaviour with it just there that I don't understand too much 😅

**Which issue(s) this PR fixes**:

Fixes #36063   
Related to #35649 

**Special notes for your reviewer**:

Still a draft until i fix the Manage Dashboards behaviour :)

### CODE REVIEW

File: public/app/features/search/components/DashboardListPage.tsx [hunk 1]
```diff
@@ -39,9 +40,15 @@ export const DashboardListPage: FC<Props> = memo(({ navModel, match, location })
     });
   }, [match.params.uid]);
 
+  const [testState, setTestState] = useState(false);
```
Comment (joshhunt) [inline public/app/features/search/components/DashboardListPage.tsx:43]: Need to remove this - it's here to test my sanity that checkboxes actually work 😅

File: packages/grafana-ui/src/components/Forms/Checkbox.tsx [hunk 2]
```diff
@@ -44,34 +44,20 @@ export const Checkbox = React.forwardRef<HTMLInputElement, CheckboxProps>(
...
-    ),
     wrapper: css`
       position: relative;
-      padding-left: ${checkboxSize};
       vertical-align: middle;
-      min-height: ${theme.spacing(3)};
+      font-size: 0;
     `,
     input: css`
       position: absolute;
```
Comment (Clarity-89) [inline packages/grafana-ui/src/components/Forms/Checkbox.tsx:57]:
```suggestion
      position: relative;
```
This seems to fix the issue on manage dashboards page, but breaks the layout on storybook. Can't figure out why it doesn't set the checked state with absolute position on that page. Maybe we'd just keep the custom styles for manage dashboards page 🤔

Comment (joshhunt) [reply packages/grafana-ui/src/components/Forms/Checkbox.tsx:57]: I _think_ the problem maybe is related to `onClick` being used rather than `onChange` - the div wrapping the checkbox registers a click and toggles state in ManageDashboards, but the checkbox itself doesn't receive the click so it doesn't switch to checked. 

I had a brief play to try and switch it over to use `onChange` (which is better for a few reasons) and i think I observed the same problem, but it's definitely possible I didn't dig far enough though. Thinking about it now, perhaps i left in a preventDefault to stopPropagation or something?

Comment (Clarity-89) [reply packages/grafana-ui/src/components/Forms/Checkbox.tsx:57]: It does get the checked value though (I also tied `checked` instead of `value`, same effect). plus I don't see how an event handler would influence the styling this way.

Comment (joshhunt) [reply packages/grafana-ui/src/components/Forms/Checkbox.tsx:57]: Yeah, that was also my other confusion - if checked is still going through, why doesn't it switch to the right visual style? 

I might take another stab later this week at understanding this...

Comment (joshhunt) [reply packages/grafana-ui/src/components/Forms/Checkbox.tsx:57]: Is it possible that there's some state changes happening outside of react? Like an angular digest that's not happening? Feel like I'm grasping at straws :P

Comment (Clarity-89) [reply packages/grafana-ui/src/components/Forms/Checkbox.tsx:57]: Don't think that'd make any difference with either absolutely or relatively positioned element.

Comment (joshhunt) [reply packages/grafana-ui/src/components/Forms/Checkbox.tsx:57]: I fixed this!

I don't totally understand exactly what was going on, but calling `.preventDefault()` on the event that would check the checkbox would... prevent the checkbox from becoming checked, even though we set state to check it. Here's an extremely minimal reproduction https://codesandbox.io/s/checkbox-repro-o8kos?file=/src/App.js

File: packages/grafana-ui/src/components/Forms/Checkbox.tsx [hunk 3]
```diff
@@ -125,21 +111,33 @@ export const getCheckboxStyles = stylesFactory((theme: GrafanaTheme2) => {
...
+      width: ${theme.spacing(checkboxSize)};
+      height: ${theme.spacing(checkboxSize)};
       border-radius: ${theme.shape.borderRadius()};
-      margin-right: ${theme.spacing(1)};
       background: ${theme.components.input.background};
       border: 1px solid ${theme.components.input.borderColor};
-      position: absolute;
-      top: 2px;
-      left: 0;
+      pointer-events: none;
```
Comment (Clarity-89) [inline packages/grafana-ui/src/components/Forms/Checkbox.tsx:119]: Wonder why is it needed? can't see any difference with or without pointer-events enabled here.

File: packages/grafana-ui/src/components/Forms/Checkbox.tsx [hunk 4]
```diff
@@ -44,34 +44,20 @@ export const Checkbox = React.forwardRef<HTMLInputElement, CheckboxProps>(
...
+      font-size: 0;
     `,
     input: css`
       position: absolute;
       top: 0;
       left: 0;
-      width: 100%;
+      width: 100% !important; // global styles unset this
       height: 100%;
       opacity: 0;
```
Comment (Clarity-89) [inline packages/grafana-ui/src/components/Forms/Checkbox.tsx:62]:
```suggestion
      opacity: 0;
      cursor: pointer;
```
I think we need to add pointer cursor to the input directly, otherwise it shows the default cursor on hover.

File: packages/grafana-ui/src/components/Forms/Checkbox.tsx [hunk 5]
```diff
@@ -28,7 +28,7 @@ export const Checkbox = React.forwardRef<HTMLInputElement, CheckboxProps>(
         <input
           type="checkbox"
           className={styles.input}
-          checked={value}
+          checked={value ?? false}
```
Comment (Clarity-89) [inline packages/grafana-ui/src/components/Forms/Checkbox.tsx:31]: This will break uncontrolled checkboxes (which we use quite a lot inside forms) since the checkbox will always have a value and passing `defaultChecked` to it won't work anymore (an example can be seen in the storybook in uncontrolled story).

**Review by Clarity-89 — COMMENTED** [review]
Great job with figuring out the issue here! 🎉 
Left a few comments. Also I think the label alignment needs to be tweaked a bit, otherwise the text is a bit too low compared to the checkbox:
Screenshot 2021-07-07 at 9 23 58

File: packages/grafana-ui/src/components/Forms/Checkbox.tsx (hunk 4 above)
Comment (joshhunt) [reply packages/grafana-ui/src/components/Forms/Checkbox.tsx:62]: Checkboxes do not normally have the pointer cursor, but it looks like they did in Grafana previously. We want to keep that I presume?

Comment (Clarity-89) [reply packages/grafana-ui/src/components/Forms/Checkbox.tsx:62]: I think it'd be nice to keep them, this also enables cursor pointer when hovering on label, which clearly indicates that it's clickable.

File: packages/grafana-ui/src/components/Forms/Checkbox.tsx (hunk 3 above)
Comment (joshhunt) [reply packages/grafana-ui/src/components/Forms/Checkbox.tsx]: The actual white check itself was above the checkbox, and would prevent the hover from happening properly.

I've re-organised the layering of them all and its no longer required.

File: packages/grafana-ui/src/components/Forms/Checkbox.tsx (hunk 4 above)
Comment (joshhunt) [reply packages/grafana-ui/src/components/Forms/Checkbox.tsx:63]: Resolved this in one way or another

Comment (Clarity-89) [reply packages/grafana-ui/src/components/Forms/Checkbox.tsx:63]: hmm, but now the label doesn't have `cursor: pointer` even though it's clickable.

**Review by Clarity-89 — COMMENTED** [review]
Two very minor issues and then it's good to go 🎉 

- The top position could be changed to -3px, which looks better aligned. 
- Add pointer cursor to the checkbox label to signal the user that it's clickable.

**Review by Clarity-89 — APPROVED** [review]
🎉
