### PR TITLE
GrafanaUI: Fix color of links in error Tooltips in light theme

### LINKED ISSUE #49169: Tooltip: Links in form validation tooltip in Light theme are barely visible
Not sure if it's me and my colour blindness, but I find links in tooltips in Light theme to be not-so-much-accessible:

image

At first sight, I thought that the Tooltip itself has a semi-transparent background, and the "Click..." link is a glitch from the layer below.

### PR DESCRIPTION
**Pull request by joshhunt**
**What this PR does / why we need it**:

Fixes the link color in error tooltip, and in the input validation error tooltip (they're two different implementations), so they're consistent and readable.

Problem with fixing this is we haven't really defined what color links should be on `error` background - the theme/tokens don't cover this. So, I fixed this in the two component implementations. Links in the form validation error, and tooltips, will use the same text color, but will have the underline. When hovered, the link will disappear, similar to [mozilla protocol's link](https://protocol.mozilla.org/patterns/atoms/links.html).

| Before | After |
| --- | ---- |
| Before| After|

**Which issue(s) this PR fixes**:

Fixes #49169

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by joshhunt** [comment]
I'm wondering if the link color is a bit too faded with not enough contrast. Instead, here's only 10% darker, and with link underline 
image

File: packages/grafana-ui/src/components/Forms/FieldValidationMessage.tsx [hunk 1]
```diff
@@ -22,6 +24,14 @@ export const getFieldValidationMessageStyles = stylesFactory((theme: GrafanaThem
...
       position: relative;
       display: inline-block;
+
+      a {
+        color: ${linkColor};
+      }
+
+      a:hover {
+        text-decoration: underline;
+      }
```
Comment (torkelo) [inline packages/grafana-ui/src/components/Forms/FieldValidationMessage.tsx:34]: as per conv on slack, think using contrastText + underline, and then remove underline on hover is a good solution here

**Review by torkelo — APPROVED** [review]

**Comment by staton-hyse11** [comment]
I'll start the Figma adjustments to reflect this in the design files and will include this in the WIP documentation for tooltips as well 👍

**Review by staton-hyse11 — APPROVED** [review]
