### PR TITLE
Search: Fix report search usage from throwing in console

### LINKED ISSUE #60377: Console throwing a "Cannot read properties of undefined (reading 'eventTrackingNamespace')" error
**What happened**:

Bitnami developer here, I'm working on the release of our Grafana 9.3.0 Chart and the console is throwing the following error:

```
SearchStateManager.ts:243 Uncaught TypeError: Cannot read properties of undefined (reading 'eventTrackingNamespace')
    at Object.onReportSearchUsage [as current] (SearchStateManager.ts:243:42)
    at useTimeoutFn.js:13:22
```
**What you expected to happen**:

Everything seems to work fine but the error is picked up by our Cypress tests. I will catch the error in the test I just want to report the issue. In case there is anything we can do about it on our side - changing a configuration option or anything - please let me know.

**How to reproduce it (as minimally and precisely as possible)**:

1) Install the Grafana chart for 9.3.0:
```
git clone https://github.com/bitnami/charts.git
cd charts
git pull automated/grafana-8.2.21
helm install grafana bitnami/grafana
```

2) Visit page
3) Try to upload a JSON

**Anything else we need to know?**:

**Environment**:
- Grafana version:9.3.0
- Data source type & version:
- OS Grafana is installed on: Debian 11
- User OS & Browser: Chromium 100
- Grafana plugins: Core Plugins
- Others:

### PR DESCRIPTION
**Pull request by joshhunt**
Fixes #60377

Class method being passed into useDebounced is called with wrong/missing `this`, so `this.state` was not availabe inside it.

### CODE REVIEW

File: public/app/features/search/page/components/SearchView.tsx [hunk 1]
```diff
@@ -42,7 +42,7 @@ export const SearchView = ({ showManage, folderDTO, hidePseudoFolders, keyboardE
   const [listKey, setListKey] = useState(Date.now());
 
   // Search usage reporting
-  useDebounce(stateManager.onReportSearchUsage, 1000, []);
+  useDebounce(() => stateManager.onReportSearchUsage(), 1000, []);
```
Comment (torkelo) [inline public/app/features/search/page/components/SearchView.tsx:45]: since it's named onXX I would expect it to be a instance property with arrow function, so an alternative fix would be to fix that name it an instance function with arrow

**Review by torkelo — APPROVED** [review]

File: public/app/features/search/page/components/SearchView.tsx (hunk 1 above)
Comment (joshhunt) [reply public/app/features/search/page/components/SearchView.tsx:45]: Hmm, im not sure i follow/understand that reasoning, but I guess i come to the same conclusion. Looking at SearchStateManager, this `onReportSearchUsage` is the only function there that _isnt_ an arrow function.
