### PR TITLE
AzureMonitor: Fix custom namespaces

### LINKED ISSUE #54757: Azure Monitor: Custom Metric Namespaces not working (Grafana 9.1.3)
After the Grafana 9.0.0 and these changes https://github.com/grafana/grafana/pull/49029. It is not possible to find/chose custom Metric Namespaces.
We have a namespaces named "Yggdrasil ServiceBus Metrics", which we could find and chose before, but now it's not possible - not even when typing it in manually.

image

Not able to find or query it:
image

With Grafana < 9.0.0 it worked perfectly fine and we could chose it from the picker.

### PR DESCRIPTION
**Pull request by asimpson**
**What this PR does / why we need it**:
The request for listing metric namespaces can return three types of namespaces as documented [here]. We previously only handled the platform namespace `microsoft.insights/components`.

[here]: https://docs.microsoft.com/en-us/rest/api/monitor/metric-namespaces/list?tabs=HTTP#metricnamespacecollection

Related to #54826

**Which issue(s) this PR fixes**:
Fixes #54757
Fixes https://github.com/grafana/support-escalations/issues/3761

**Special notes for your reviewer**:
If you have access to Grafana's Azure dev account you can use the `AppInsightsTest` resource to test.
image

### CODE REVIEW

File: pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource.go [hunk 1]
```diff
@@ -113,8 +113,13 @@ func (e *AzureMonitorDatasource) buildQueries(queries []backend.DataQuery, dsInf
...
 		params.Add("interval", timeGrain)
 		params.Add("aggregation", azJSONModel.Aggregation)
-		params.Add("metricnames", azJSONModel.MetricName) // MetricName or MetricNames ?
-		params.Add("metricnamespace", azJSONModel.MetricNamespace)
+		params.Add("metricnames", azJSONModel.MetricName)
+
+		if azJSONModel.CustomNamespace != "" {
+			params.Add("metricnamespace", azJSONModel.CustomNamespace)
+		} else {
+			params.Add("metricnamespace", azJSONModel.MetricNamespace) // MetricName or MetricNames ?
```
Comment (andresmgot) [inline pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource.go:121]: the comment is now in the wrong  line but we likely don't need that comment at all

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/MetricNamespaceField.tsx [hunk 2]
```diff
@@ -43,7 +43,7 @@ const MetricNamespaceField: React.FC<MetricNamespaceFieldProps> = ({
     <Field label="Metric namespace">
       <Select
         inputId="azure-monitor-metrics-metric-namespace-field"
-        value={query.azureMonitor?.metricNamespace || null}
+        value={query.azureMonitor?.customNamespace || query.azureMonitor?.metricNamespace || null}
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/MetricNamespaceField.tsx:46]:
```suggestion
        value={value || null}
```
?

**Review by andresmgot — COMMENTED** [review]
Thanks for this tricky fix! I have some minor comments.

Food for thought but a good UX improvement would be to not render the namespace selector if there are no "custom" namespaces (this is, namespaces apart from the one of the resource). In most of the cases we could skip that input. Not necessary to do that in this PR though.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/types/query.ts [hunk 3]
```diff
@@ -47,6 +47,7 @@ export interface AzureMetricQuery {
   resourceName?: string;
   /** Resource type */
   metricNamespace?: string;
+  customNamespace?: string;
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/types/query.ts:50]: since we are differing from the naming in Azure Monitor API, it would be good to add some comment here explaining the difference between `metricNamespace` and `customNamespace` for future reference

**Review by andresmgot — APPROVED** [review]
LGTM! Thanks

**Comment by andresmgot** [comment]
let me merge this. It seems that 9.1.5 release is on its way now just in case we miss that train :)

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/types/query.ts (hunk 3 above)
Comment (asimpson) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/types/query.ts:50]: Yeah, I can PR that this am.
