### PR TITLE
Alerting: Fix setting datasource uid, when datasource is string in old version

### LINKED ISSUE #96040: Alerting: crashes on old alerts
### What happened?

After upgrading to grafana 11.3.0 I can't open alert definition in grafana and I only get "An unexpected error happened" error message.
Since https://github.com/grafana/grafana/pull/93057 was merged, frontend code overrides uid field on datasource. But sometimes, with older alerts (successfully created via API in grafana 11.2.0), datasource is a string. So calling `datasource.uid` on a string raises an exception:
```
2react-dom.production.min.js:189 TypeError: Cannot create property 'uid' on string '<datasource name>'
    at M (QueryWrapper.tsx:101:34)
    at el (react-dom.production.min.js:167:137)
    at Rf (react-dom.production.min.js:290:337)
    at Cf (react-dom.production.min.js:280:389)
    at Qf (react-dom.production.min.js:280:320)
    at Cl (react-dom.production.min.js:280:180)
    at bc (react-dom.production.min.js:271:88)
    at Ef (react-dom.production.min.js:273:300)
    at Ls (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
```
I believe the correct code in QueryWrapper.tsx should be like this:
```
queryWithDefaults.datasource = {}
queryWithDefaults.datasource.uid = query.datasourceUid;
```

### What did you expect to happen?

Editor view presented with all details.

### Did this work before?

Yes, in 11.2.0

### How do we reproduce it?

1.
2.
3.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by soniaAguilarPeiron**
**What is this feature?**

This PR fixes a rare bug that happens on old rules created before uids where introduced in datasources.

In particular when trying to set datasource uid, and the datasource hapens to be an string instead of an object.

It seems a regression after this [PR](https://github.com/grafana/grafana/pull/93057) was merged (that was actually fixing another edge usecase)

**Why do we need this feature?**

It's a bug.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/96040 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/alerting/unified/components/rule-editor/QueryWrapper.tsx [hunk 1]
```diff
@@ -98,7 +98,18 @@ export const QueryWrapper = ({
...
+    // see: https://github.com/grafana/grafana/issues/96040 for more context
+    if (typeof queryWithDefaults.datasource === 'object' && Boolean(queryWithDefaults.datasource)) {
+      queryWithDefaults.datasource.uid = query.datasourceUid;
+    } else {
+      // if the datasource is a string, we need to convert it to an object, and populate the fields from the query model
+      queryWithDefaults.datasource = {};
+      queryWithDefaults.datasource.uid = query.datasourceUid;
+      queryWithDefaults.datasource.type = query.model.datasource?.type;
+      queryWithDefaults.datasource.apiVersion = query.model.datasource?.apiVersion;
+    }
```
Comment (tomratcliffe) [inline public/app/features/alerting/unified/components/rule-editor/QueryWrapper.tsx:112]: Two thoughts from me:

Should we switch this/explicitly special case the scenario of "datasource is a string"? So:
```tsx
if(typeof queryWithDefaults.datasource === 'string') { 
  // do special things
}
```

And could we simplify the special case logic to just be like this?:
```tsx
queryWithDefaults.datasource = {
  uid: query.datasourceUid,
  type: query.model.datasource?.type,
  apiVersion: query.model.datasource?.apiVersion,
};
```

**Comment by tomratcliffe** [comment]
(I was going to suggest adding some tests as well, but it's very fiddly to do, I left a comment on the previous PR, pointing to https://github.com/grafana/grafana/pull/90363. We should probably invest in these kinds of tests separately)

File: public/app/features/alerting/unified/components/rule-editor/QueryWrapper.tsx (hunk 1 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/QueryWrapper.tsx:112]: > Should we switch this/explicitly special case the scenario of "datasource is a string"? 

I believe it’s safer to check for the opposite condition, as this approach covers all types that are not objects.

**Review by tomratcliffe — APPROVED** [review]
