### PR TITLE
Auth: Add sub claim check to JWT Auth pre-checks

### LINKED ISSUE #59023: Post 9.2 Using API & JWT auth - if email claim fails auth does not fall through to use basic auth
**What happened**:

After upgrading from Grafana 9.1.4 to Grafana 9.2.1, authenticating with Basic auth with a non-user-account JWT present in the auth.jwt header_name header does not fallback to using Basic Auth, but instead instantly fails with the following error

`{"error":null,"level":"warn","logger":"context","msg":"Got a JWT without the mandatory 'sub' claim","t":"2022-11-21T10:27:54.299454803Z"}`

**What you expected to happen**:

A failed JWT login should fallback to Basic Auth (or another type of login)

**How to reproduce it (as minimally and precisely as possible)**:

(We are using Cloudflare access)
Configure a Cloudflare access tunnel to Grafana. In the grafana settings, configure `auth.jwt` to use the Cf-Access-Jwt-Assertion header, and set username and email claims to use `email`

Create a Cloudflare Service token with permissions to use the app.
Make an API call with the CF access headers, and basic auth headers for a local grafana user. In 9.1.4 this works successfully, but in 9.2.1 you get the above warning, and authentication fails

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.1

### PR DESCRIPTION
**Pull request by mgyongyosi**
**What is this feature?**
This PR adds a pre-check to the JWT Auth which checks whether the provided JWT token has a non-empty `sub` claim, if it has it attempts to authenticate, otherwise it does pass the control to the next handler(s).

**Why do we need this feature?**

When both JWT auth and Basic auth is configured it can happen that the user would like to use the Basic auth however the a JWT token is also included in the request (but it does not contain a valid a `sub` claim which is the case for #59023) and because JWT comes first in the authentication handlers list, it handles the request and then (after a failed login attempt) returns 401 Unauthorized. 

**Which issue(s) does this PR fix?**:

Fixes #59023 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Jguer — APPROVED** [review]
looks great :+1:

File: pkg/services/authn/clients/jwt.go [hunk 1]
```diff
@@ -143,21 +144,14 @@ func (s *JWT) Test(ctx context.Context, r *authn.Request) bool {
 		return false
 	}
 
-	// The header is Authorization and the token does not look like a JWT,
-	// this is likely an API key. Pass it on.
-	if s.cfg.JWTAuthHeaderName == "Authorization" && !looksLikeJWT(jwtToken) {
+	// If the "sub" claim is missing or empty then pass the control to the next handler
+	if !authJWT.HasSubClaim(jwtToken) {
```
Comment (linoman) [inline pkg/services/authn/clients/jwt.go:148]: opinionated nit: I'd merge the last 2 conditional statements into a single return value. Something similar to this.
```
func (s *JWT) Test(ctx context.Context, r *authn.Request) bool {
	if !s.cfg.JWTAuthEnabled || s.cfg.JWTAuthHeaderName == "" {
		return false
	}

	jwtToken := s.retrieveToken(r.HTTPRequest)

    // If the "sub" claim is missing or empty then pass the control to the next handler
    return jwtToken != "" || authJWT.HasSubClaim(jwtToken);
}
```

**Review by linoman — APPROVED** [review]
I left a minor comment. I trust @mgyongyosi whether to include it or not.

File: pkg/services/authn/clients/jwt.go (hunk 1 above)
Comment (mgyongyosi) [reply pkg/services/authn/clients/jwt.go:148]: Thanks for the suggestion! I checked the cognitive complexity and the cyclomatic complexity of the current implementation and your suggestion and those are the same, so I wouldn't change this part, because it is easier and quicker (at least for me) to understand the pre-checks for this auth client.
