### PR TITLE
Tempo: Fix the inconsistency between the query limit values in the options component

### LINKED ISSUE #56551: Tempo: TraceQL `Limit` field value is not always consistent with the collapsed value
**What happened**:
When changing the value of the `Limit` field to `X`, if you click on another query type and go back to the `TraceQL` tab, the value of the `Limit` field goes back to 20, however the value shown when the `Options` component is collapsed is still `X`, making the two values inconsistent with each other.

https://user-images.githubusercontent.com/48166845/194554513-ca7a25aa-bb9d-4976-aac5-068056eb6eef.mov

**What you expected to happen**:
The same value shown when the component is collapsed and expanded.

**How to reproduce it (as minimally and precisely as possible)**:
- Click on the TraceQL tab and change the value of the `Limit` field.
- Switch to a different query type, then switch back to the TraceQL tab.
- Look at the `Options` component and note the value, now expand this component and you will see that the value in the `Limit` field is different.

**Environment**:
- macOS 12.6
- Grafana v9.1.7
- https://www.whatsmybrowser.org/b/TCJ6W

### PR DESCRIPTION
**Pull request by CrypticSignal**
Fixes #56551

### CODE REVIEW

**Review by joey-grafana — APPROVED** [review]

File: public/app/plugins/datasource/tempo/traceql/TempoQueryBuilderOptions.tsx [hunk 1]
```diff
@@ -26,7 +26,7 @@ export const TempoQueryBuilderOptions = React.memo<Props>(({ onChange, query })
               placeholder="auto"
               type="number"
               min={1}
-              defaultValue={DEFAULT_LIMIT}
+              defaultValue={query.limit || DEFAULT_LIMIT}
```
Comment (aocenas) [inline public/app/plugins/datasource/tempo/traceql/TempoQueryBuilderOptions.tsx:29]: @joey-grafana @CrypticSignal I don't think this is the right fix here. The `defaultValue` I would assume should not be shown if `query.limit` is set. If it is set there should be no need to override the defaultValue prop. If it isn't set this should not have any effect. Seems like there is some other root cause why this does not work as expected.

So either we are using defaultValue wrong here, it does not work as expected and there is a bug in the Input or there is something else going on.

Comment (aocenas) [reply public/app/plugins/datasource/tempo/traceql/TempoQueryBuilderOptions.tsx:29]: Also if query.limit === 0 this will show DEFAULT_LIMIT. Not sure if that is expected or not.

Comment (CrypticSignal) [reply public/app/plugins/datasource/tempo/traceql/TempoQueryBuilderOptions.tsx:29]: Are you saying that we shouldn't have the `defaultValue` prop at all? If it think about it, I don't think we need it because if we have `value={DEFAULT_LIMIT}`, that is essentially setting a default value, so I'm not entirely sure of the purpose of the `defaultValue` prop.

I will do some testing to check whether query limiting works as intended. If not, I will make the necessary changes in a new PR.
