### PR TITLE
Admin: Fix infinite loading edit on the profile page

### LINKED ISSUE #34382: Profile: Cannot load profile page when coming from a dashboard
* To replicate to to dashboard 
* Click on profile via sidemenu 
* Profile page loads but spinner keeps spinning 

Cause during dashboard cleanup we cancel all network requests (to cancel variable queries), this clean up process is async and as a side effect of the react router migration happens faster now so the cancelling of network requests as part of dashboard close happens to cancel the loading of the user profile (This is my theory).

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
The fix for #34382 was to change `UNSAFE_componentWillMount` into `componentDidMount` here 
https://github.com/grafana/grafana/blob/d666defaea5786aca9672cff8b497b31d6ee1254/public/app/core/utils/UserProvider.tsx#L76

But then I started looking deeper into this and I thought that this entire part of Grafana could use a refactor as it should use Redux or `useReducer` for the state handling. As there was already a shared state for the user profile I stored everything in Redux. Please let me know if I should use `useReducer` instead. I also added RTL tests for the page.

Not sure if this affects Enterprise so I'm adding Alex as a reviewer.

**Which issue(s) this PR fixes**:
Fixes #34382

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/profile/UserProfileEditPage.tsx [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+  teams,
+  isUpdating,
+  user,
+  revokeUserSession,
+  changeUserOrg,
+  updateUserProfile,
+}: Props) {
+  useAsync(async () => {
+    await initUserProfilePage();
+  }, []);
```
Comment (Clarity-89) [inline public/app/features/profile/UserProfileEditPage.tsx:66]:
```suggestion
  useAsync(async () => initUserProfilePage(), []);
```

File: public/app/features/profile/UserProfileEditPage.tsx [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+
+  return (
+    <Page navModel={navModel}>
+      <Page.Contents isLoading={!Boolean(user)}>
```
Comment (Clarity-89) [inline public/app/features/profile/UserProfileEditPage.tsx:70]:
```suggestion
      <Page.Contents isLoading={!user}>
```
`Boolean` is redundant here since `!` will convert the value to boolean.

File: public/app/features/profile/api.ts [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+async function changePassword(payload: ChangePasswordFields): Promise<void> {
+  try {
+    await getBackendSrv().put('/api/user/password', payload);
+  } catch (err) {
+    console.error(err);
+  }
+}
+
+async function loadUser(): Promise<UserDTO> {
+  return await getBackendSrv().get('/api/user');
```
Comment (Clarity-89) [inline public/app/features/profile/api.ts:15]:
```suggestion
  return getBackendSrv().get('/api/user');
```
Is there a reason we use `await` together with `return` in these functions? The only reason I see if we'd use them inside of `try/catch` clauses, but I even then we can just add `await` to the function itself.

**Review by Clarity-89 — COMMENTED** [review]
Not 100% sure `useAsync` hook is meant to work with Redux as it seems like the `loadUser` action is not cancelled on the change password page. To reproduce:
- Navigate to user profile edit page
- Refresh the page
- Switch to the Change Password tab and then switch back to the Preferences tab
- A warning `Can't perform a React state update on an unmounted component.` appears in console.

**Comment by hugohaggmark** [comment]
> Not 100% sure `useAsync` hook is meant to work with Redux as it seems like the `loadUser` action is not cancelled on the change password page. To reproduce:
> 
> * Navigate to user profile edit page
> * Refresh the page
> * Switch to the Change Password tab and then switch back to the Preferences tab
> * A warning `Can't perform a React state update on an unmounted component.` appears in console.

@Clarity-89 thanks for the feedback, will have a look about the state `Can't perform a React state update on an unmounted component.` warning.

File: public/app/features/profile/UserProfileEditPage.tsx (hunk 2 above)
Comment (hugohaggmark) [reply public/app/features/profile/UserProfileEditPage.tsx:70]: Good catch!

File: public/app/features/profile/api.ts (hunk 3 above)
Comment (hugohaggmark) [reply public/app/features/profile/api.ts:15]: Hmm, I think I might have copied paste with little thought.

File: public/app/features/profile/UserProfileEditPage.tsx (hunk 2 above)
Comment (hugohaggmark) [reply public/app/features/profile/UserProfileEditPage.tsx]: Fixed!

File: public/app/features/profile/api.ts (hunk 3 above)
Comment (hugohaggmark) [reply public/app/features/profile/api.ts]: Fixed!

File: public/app/features/profile/ChangePasswordPage.tsx [hunk 4]
```diff
@@ -1,51 +1,54 @@
...
+};
+
+const connector = connect(mapStateToProps, mapDispatchToProps);
+
+type Props = OwnProps & ConnectedProps<typeof connector>;
+
+export function ChangePasswordPage({ navModel, loadUser, isUpdating, user, changePassword }: Props) {
+  useAsync(async () => {
+    await loadUser();
+  }, []);
```
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply public/app/features/profile/ChangePasswordPage.tsx]: Fixed!

File: public/app/features/profile/UserProfileEditPage.tsx (hunk 1 above)
Comment (hugohaggmark) [reply public/app/features/profile/UserProfileEditPage.tsx]: Fixed!

**Review by dprokop — APPROVED** [review]
Solid work @hugohaggmark as always!

**Comment by hugohaggmark** [comment]
> Not 100% sure `useAsync` hook is meant to work with Redux as it seems like the `loadUser` action is not cancelled on the change password page. To reproduce:
> 
> * Navigate to user profile edit page
> * Refresh the page
> * Switch to the Change Password tab and then switch back to the Preferences tab
> * A warning `Can't perform a React state update on an unmounted component.` appears in console.

I've looked deeper into this warning and this is caused by `SharedPreferences` being unmounted/mounted. Trying to find a solution to it.

**Review by Clarity-89 — APPROVED** [review]
Looks good, great work! 🎉
