### PR TITLE
POC: Disable `ConfirmButton`

### LINKED ISSUE #74666: BrowseDashboards: When invalid delete warning is shown, delete button is not disabled
When attempting to delete a folder containing alerts, we show this warning to say the folder cannot be deleted

image

However, the confirmation text box and button is not disabled, so the user can still attempt to delete the folder (which the API will fail)

Not biggest issue, but should fix.

Grafana: 10.2.3

### PR DESCRIPTION
**Pull request by eledobleefe**
**What is this feature?**
This is a POC triggered by this issue: #74666

**Why do we need this feature?**
When a **Folder** contains a **Library Panel** or **Alerts**, the `DeleteModal` shows a warning, but the user can click on the `DeleteButton` after writing the confirm text. The deletion will. not be completed, and a toast with an error message will appear.
We want to avoid this by disabling the `DeleteButton` in the `Modal` if the **Folder**  contains **Library Panels** or **Alerts**. The user won't be able to click on it and must follow the alert indication (delete them before deleting the folder).

Proposal:
Creating an `isConfirmButtonDisabled` prop. This prop should be used when there is a second check, apart from the one looking for the confirm text to be written. In this case, we check if the folder contains alerts or library panels. If this is true the `isConfirmButtonDisabled` will be true and therefore the `DeleteButton` will be disabled.
This is already applied outside Grafana, for example, in the `Modal` of [Bootstrap Vue](https://bootstrap-vue.org/docs/components/modal#disabling-built-in-footer-buttons).

Cons:
It's not ideal the fact that we have to pass the prop from `DeleteModal` to `ConfirmModal` and then to `ConfirmContent`.

**Who is this feature for?**
All who need to disable the `ConfirmButton` if a condition must be met, apart from writing the confirm text.

**Which issue(s) does this PR fix?**:
Fixes #74666

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/ConfirmModal/ConfirmModal.tsx [hunk 1]
```diff
@@ -44,6 +44,8 @@ export interface ConfirmModalProps {
   onDismiss(): void;
   /** Alternative action callback */
   onAlternative?(): void;
+  /** Disable the confirm button if needed */
+  isConfirmButtonDissabled?: boolean;
```
Comment (joshhunt) [inline packages/grafana-ui/src/components/ConfirmModal/ConfirmModal.tsx:48]: What if we just add a `disabled` prop that disables both the text entry and confirm button?

I _think_ we can keep the cancel button enabled? I think that's understable for consumers?

File: packages/grafana-ui/src/components/ConfirmModal/ConfirmModal.tsx [hunk 2]
```diff
@@ -52,7 +54,6 @@ export const ConfirmModal = ({
   body,
   description,
   confirmText,
-  confirmVariant = 'destructive',
```
Comment (eledobleefe) [inline packages/grafana-ui/src/components/ConfirmModal/ConfirmModal.tsx:55]: I removed it because I thought it was a duplicate of `confirmButtonVariant`, but it may need a review as I'm not 100% sure 🤷

Comment (L-M-K-B) [reply packages/grafana-ui/src/components/ConfirmModal/ConfirmModal.tsx:55]: I can't find any reason to keep this but if you remove it in line 55 you also want to remove it from ConfirmModalProps (line 24).

**Review by L-M-K-B — COMMENTED** [review]
Just a nit but besides this looks awesome!

File: packages/grafana-ui/src/components/ConfirmModal/ConfirmModal.tsx (hunk 2 above)
Comment (eledobleefe) [reply packages/grafana-ui/src/components/ConfirmModal/ConfirmModal.tsx:55]: I investigated a bit more and discovered we are using this prop in some places. So, I'm going to undo this change in this PR and create a new one if I confirm this is not needed / duplicated.

**Review by L-M-K-B — APPROVED** [review]
I think you are good to go with this. Great job!
