### PR TITLE
DashboardExport: Correctly templetatize datasource prop now that is's a ref obj

### LINKED ISSUE #42240: 8.3.0-beta1: Import dashboard exported for sharing externally doesn't render correct data source when editing panel
**What happened**:
Imported a dashboard that's been exported for sharing externally, but when editing panel in imported dashboard the test datasource was selected. 

**What you expected to happen**:
Clickhouse datasource to be selected in data source drop down together with its query editor. In addition, when switching the selected datasource to clickhouse manually the query editor doesn't remember the old clickhouse query.

**How to reproduce it (as minimally and precisely as possible)**:
Can probably use any data source besides the test data source to reproduce this, but below a video showing my experience:
https://user-images.githubusercontent.com/1668778/143265008-da0495b0-7ce4-4e87-a402-3b27e879b5c8.mp4

Exported dashboard:
```json
{
  "__inputs": [
    {
      "name": "DS_CLICKHOUSE",
      "label": "ClickHouse",
      "description": "",
      "type": "datasource",
      "pluginId": "vertamedia-clickhouse-datasource",
      "pluginName": "ClickHouse"
    }
  ],
  "__elements": [],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "8.4.0-pre"
    },
    {
      "type": "panel",
      "id": "timeseries",
      "name": "Time series",
      "version": ""
    },
    {
      "type": "datasource",
      "id": "vertamedia-clickhouse-datasource",
      "name": "ClickHouse",
      "version": "2.3.1"
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": "${DS_CLICKHOUSE}",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "bars",
            "fillOpacity": 100,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "never",
            "spanNulls": true,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "short"
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "count()"
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "green",
                  "mode": "fixed"
                }
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 13,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltip": {
          "mode": "single"
        }
      },
      "pluginVersion": "8.1.0-pre",
      "targets": [
        {
          "database": "default",
          "dateColDataType": "",
          "dateLoading": false,
          "dateTimeColDataType": "closed_at",
          "dateTimeType": "DATETIME",
          "datetimeLoading": false,
          "extrapolate": true,
          "format": "time_series",
          "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
          "intervalFactor": 1,
          "query": "SELECT\n    Time as DateTime,\n    count()\nFROM github_events\n\nWHERE\n    (repo_name = 'grafana/grafana')\n    AND(event_type = 'PullRequestEvent')\n    AND(Time >= toDate('2021-01-01'))\nGROUP BY toStartOfDay(created_at) AS Time\n\nORDER BY Time ASC\n",
          "rawQuery": true,
          "refId": "A",
          "round": "0s",
          "skip_comments": true,
          "table": "github_events",
          "tableLoading": false
        }
      ],
      "title": "Panel Title",
      "transformations": [
        {
          "id": "filterFieldsByName",
          "options": {
            "include": {
              "names": [
                "count()",
                "Time"
              ]
            }
          }
        }
      ],
      "type": "timeseries"
    }
  ],
  "schemaVersion": 33,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "2020-12-29T07:08:37.066Z",
    "to": "2021-04-21T15:24:27.112Z"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Clickhouse",
  "uid": "vjf0ny6Mz",
  "version": 6,
  "weekStart": ""
}
```

**Anything else we need to know?**:
Feels related to datasource ref changes.

**Environment**:
- Grafana version: Grafana v8.3.0-beta1
- Data source type & version: Clickhouse v2.3.1

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #42240

### CODE REVIEW

**Review by kaydelaney — APPROVED** [review]

File: public/app/features/dashboard/components/DashExportModal/DashboardExporter.ts [hunk 1]
```diff
@@ -116,7 +116,11 @@ export class DashboardExporter {
               pluginName: ds.meta?.name,
             };
 
-            obj.datasource = '${' + refName + '}';
+            if (obj.datasource === null || typeof obj.datasource === 'string') {
+              obj.datasource = '${' + refName + '}';
```
Comment (torkelo) [inline public/app/features/dashboard/components/DashExportModal/DashboardExporter.ts:120]: annotation queries are not using a DataSourceRef object yet

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍
