### PR TITLE
TimeRange: Avoid x-axis pan jump caused by data loading latency

### LINKED ISSUE #114483: TimeRange: X-axis jump during data loading latency after panning
When you release the mouse at the end of a time range pan interaction, the x-axis jumps a bit.

#### Steps to Reproduce:
1. Go to a dashboard with a timeseries panel _(preferably one with a larger dataset, slower to load)_
2. Click and drag the x-axis to pan time the time range in any direction

#### Expected Behavior:
Upon release, the x-axis in the location it was dragged to while the data is loaded.

#### Actual Behavior:
Upon release, the x-axis jumps back to the original location before panning while the data is loaded, then jumps back to the location it was dragged to after the data loads.

#### Additional Notes:
The time range pan is still accurate, the jump just doesn’t look very polished, it’s a bit janky.

### PR DESCRIPTION
**Pull request by jesdavpet**
**What is this feature?**

This changes the behaviour of time range panning in the panel where the x-axis was dragged, to avoid the x-axis jumping back and forth while waiting for slower data (or large datasets) to load.

### Before 

❌ The x-axis jumps back and forth with slow loading data:

https://github.com/user-attachments/assets/af110ef5-d495-431d-b9e1-abab054bdb38

### After

✅ The x-axis stays where you drag it to in the panel, while show data is loaded:

https://github.com/user-attachments/assets/7ae24211-996d-4154-af2b-bdb634da8e6b

**Why do we need this feature?**

To make the new experimental x-axis panning feature work more intuitively with large/slow datasets.

**Who is this feature for?**

Anyone with the experimental `timeRangePan` feature flag turned on for now, eventually all Grafana users.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/114483

**Special notes for your reviewer:**

- 🎏 Make sure you have the `timeRangePan` flag toggled on to try it out.
- I had to artificially throttle my connection in browser dev tools to make the original bug obvious.

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
-  `N/A` ~The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.~

### CODE REVIEW

File: packages/grafana-ui/src/components/uPlot/config/UPlotConfigBuilder.ts [hunk 1]
```diff
@@ -29,7 +29,7 @@ const cursorDefaults: Cursor = {
 type PrepData = (frames: DataFrame[]) => AlignedData | FacetedData;
 type PreDataStacked = (frames: DataFrame[], stackingGroups: StackingGroup[]) => AlignedData | FacetedData;
 
-type PlotState = { isPanning: false } | { isPanning: true; min: number; max: number };
+type PlotState = { isPanning: false } | { isPanning: true; min: number; max: number; waitingForSync?: boolean };
```
Comment (fastfrwrd) [inline packages/grafana-ui/src/components/uPlot/config/UPlotConfigBuilder.ts]: **non-blocking:** my only quibble with this PR is the name of this attribute. I thought "sync" was referring to sync/async, and expected to see something related to RAF or promise handling or something here. Some ideas for naming could be  `waitingForTimeRangeMatch` to be super duper literal, or `waitForUpdate`

**Review by fastfrwrd — APPROVED** [review]
Looks great, nice improvement.

File: packages/grafana-ui/src/components/uPlot/config/UPlotConfigBuilder.ts (hunk 1 above)
Comment (jesdavpet) [reply packages/grafana-ui/src/components/uPlot/config/UPlotConfigBuilder.ts]: Ah, that's a good point "sync" is a little bit ambiguous -- I'll come up with something better. 🤔 💭

Comment (jesdavpet) [reply packages/grafana-ui/src/components/uPlot/config/UPlotConfigBuilder.ts]: Refactored to `isTimeRangePending` etc. as of commit: 0ef192b68f19f5bacfcaa8d91f95a52c5ab0e13f

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/19716873335)
- Version: 12.4.0-19716873335
