### PR TITLE
Card: Improve header semantics

### LINKED ISSUE #118779: [A11ySev2] [Programmatic access -Dashboards with Grafana - Select data source dialog]: Unnecessary h2 heading defined for list items in Select data source dialog.
## Steps to reproduce

Repro Steps: 
  
 
1. Open 'Azure Monitor dashboards with Grafana' in Azure Portal
2. "Monitor | Dashboards with Grafana | Gallery" screen appears with already Dashboards with Grafana tab selected.
3. Navigate to the all the controls available on Dashboards with Grafana blade like tool bar , controls under All Dashboards tab.
4. Navigate New menu present in the tool bar and select New Dashboard.
5. Navigate to "Add visualization" button and hit ENTER key. "Select data source" popup will appear.
6. Navigate to  all the control present in the Select data source dialog.
7. Observe that screen reader announcement for second radio button under the refresh combo box. 

**Actual Result:**
Each data source list item is announced as a level 2 heading. 
Screen readers announce repeated “Heading level 2” for every item in the list. 

**Expected Result:**
List items in the Select data source dialog should not be marked as headings. 
Appropriate semantic elements (e.g., li, button, or role="option") should be used instead. 
Screen readers should announce each item as a selectable option without heading level information, providing a clear and efficient navigation experience.

**Relevant WCAG Criteria:** [1.3.1 Info and Relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html) (Level A)

## Environment

- **Grafana version:** 12.2.0
- **Data source type & version:**
- **User OS & Browser:** Version 25H2 (OS Build 26200.7093) / Chrome Version 142.0.7444.177 (Official Build) (64-bit)
- **Others:**

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- removes the `h2` element on the card heading

**Why do we need this feature?**

- because `Card` is a very generic component, it's extremely hard to use this in a way that doesn't cause a11y issues. e.g. accidentally nesting this `h2` under a `h3`

**Who is this feature for?**

- everyone

**Which issue(s) does this PR fix?**:

Fixes #118779 
For https://github.com/grafana/grafana/issues/117836

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/Card/Card.tsx [hunk 1]
```diff
@@ -124,7 +124,7 @@ const Heading = ({ children, className, 'aria-label': ariaLabel }: ChildProps &
   const optionLabel = t('grafana-ui.card.option', 'option');
 
   return (
-    <h2 className={cx(styles.heading, className)}>
+    <div className={cx(styles.heading, className)}>
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/Card/Card.tsx]: do we want to stick a data-testId here so we can use that in the tests?

**Review by hugohaggmark — APPROVED** [review]

File: packages/grafana-ui/src/components/Card/Card.tsx (hunk 1 above)
Comment (ashharrison90) [reply packages/grafana-ui/src/components/Card/Card.tsx]: i wasn't gonna bother given we can query by text 🤔 wdyt? happy to do either, second opinion would help 👍

Comment (tomratcliffe) [reply packages/grafana-ui/src/components/Card/Card.tsx]: I was going to suggest adding `role=heading`, but then you apparently need to add `aria-level`, and then you're back to the original problem 😁 

Personally I'd prefer just querying by text in that case

Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Card/Card.tsx]: query by text is very weak imho, but I don't feel that strongly about this

Comment (ashharrison90) [reply packages/grafana-ui/src/components/Card/Card.tsx]: have added an e2e selector and updated it in some tests where it makes more sense 👍

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/22898798261)
- Version: 13.0.0-22898798261
