### PR TITLE
FIX: RBAC prevents deleting empty snapshots

### LINKED ISSUE #51189: Snapshot: cannot delete incorrect snapshot created through HTTP API
**What happened**:
Cannot delete an incorrect snapshot created with the Snapshot API
From API:
```
{
  "message": "Error while checking permissions for snapshot",
  "traceID": "00000000000000000000000000000000"
}
```
Logs:
```
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=grafana-admin t=2022-06-21T18:37:39.585177279+02:00 level=error msg="Error while checking permissions for snapshot" error="Unique identifier needed to be able to get a dashboard" remote_addr=10.3.3.10 traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=grafana-admin t=2022-06-21T18:37:39.585217193+02:00 level=error msg="Request Completed" method=DELETE path=/api/snapshots/l2OeOHc6uqaWQmRXK0mz6SfbF6ePpqxS status=500 remote_addr=10.3.3.10 time_ms=23 duration=23.613911ms size=104 referer= traceID=00000000000000000000000000000000
```
From GUI:

Screenshot from 2022-06-21 18-36-16

**What you expected to happen**:
Either of the following:

- being able to delete the snapshot with http api
- being able to delete the snapshot from the GUI

**How to reproduce it (as minimally and precisely as possible)**:
On a fresh grafana instance, call the api with the following payload:
```
{
      "dashboard": {},
      "expires": 3600
}
```

**Anything else we need to know?**:
Can be delete from the db:
```
delete from dashboard_snapshot ;
```

**Environment**:
- Grafana version: 9.0.0 b5c56f6371 (docker)
- Data source type & version: /
- OS Grafana is installed on: (Docker)
- User OS & Browser: Debian 11, Chrome
- Grafana plugins: /
- Others: /

### PR DESCRIPTION
**Pull request by gamab**
**What this PR does / why we need it**:
As reported by @gjed, and analysed by @dprokop in #51189 deleting an "empty" snapshot is prevented by RBAC (no permission targetting `dashboard ID = 0`).

This PR intends to skip the access-control check should that be the case, **but also** prevent creation of a local snapshot targeting no dashboard.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/51189

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/api/dashboard_snapshot.go [hunk 1]
```diff
@@ -325,22 +330,26 @@ func (hs *HTTPServer) DeleteDashboardSnapshot(c *models.ReqContext) response.Res
...
+			if err != nil && !errors.Is(err, dashboards.ErrDashboardNotFound) {
+				return response.Error(http.StatusInternalServerError, "Error while checking permissions for snapshot", err)
+			}
 
-		if !canEdit && query.Result.UserId != c.SignedInUser.UserID && !errors.Is(err, dashboards.ErrDashboardNotFound) {
-			return response.Error(403, "Access denied to this snapshot", nil)
+			if !canEdit && query.Result.UserId != c.SignedInUser.UserID && !errors.Is(err, dashboards.ErrDashboardNotFound) {
+				return response.Error(http.StatusForbidden, "Access denied to this snapshot", nil)
+			}
 		}
```
Comment (sakjur) [inline pkg/api/dashboard_snapshot.go:346]: If the comment above doesn't lie, you should be able to remove the `else` that is surrounding this code for the same effect, since an external dashboard is also going to return ID 0.

**Review by kalleep — CHANGES_REQUESTED** [review]
LGTM

**Review by kalleep — APPROVED** [review]
LGTM

**Comment by k24dizzle** [comment]
So to clarify, you need to provide an `id` in the `dashboard` field in the HTTP POST request in order for it to work?
The docs don't seem to specify this requirement:
https://grafana.com/docs/grafana/v9.0/developers/http_api/snapshot/#create-new-snapshot

Is this `id` used any where other than providing the ability to delete a snapshot? If so can I just choose any arbitrary value for the `id` here?

**Comment by jnadler** [comment]
We've been using `-1` for a dashboard ID to workaround this problem @k24dizzle .   It doesn't make sense of course, but... keeps us in business.

**Comment by jnadler** [comment]
@gamab is this behavior expected / should we file an issue here?

**Comment by gamab** [comment]
@k24dizzle @jnadler my apologies for the inconvenience, I did not expect snapshots to be created without a dashboard ID. #58669 should revert that specific change.

Out of curiosity, how do you get the dashboard JSON without the dashboard ID?

**Comment by jnadler** [comment]
Hi Gabriel!  The dashboard definition is in our Github, and is posted to `/api/snapshots`.

For example one of our tools posts a snapshot as an automatic PR comment that shows how the service is performing in a test env.  Te snapshot URL is built using the `url` from the create response.   

Thanks for fixing this @gamab !!!
