### PR TITLE
Barchart docs and styling fix

### LINKED ISSUE #41552: BarChart: Slider with tickmarks does not have correct height
The slider field option does not fully work with the step marks, they extend beyond it's height making the spacing to the next option to small and different to the rest of the options. 

Screenshot from 2021-11-10 16-00-46

### PR DESCRIPTION
**Pull request by oscarkilhed**
**What this PR does / why we need it**:
Adds documentation for rotating barchart bar labels and bar label max length.
Also fixes the names and some small styling.

Closes https://github.com/grafana/grafana/issues/41552

### CODE REVIEW

**Review by dprokop — APPROVED** [review]

File: public/app/plugins/panel/barchart/module.tsx [hunk 1]
```diff
@@ -78,7 +78,7 @@ export const plugin = new PanelPlugin<BarChartOptions, BarChartFieldConfig>(BarC
       })
       .addSliderInput({
         path: 'valueRotation',
```
Comment (ryantxu) [inline public/app/plugins/panel/barchart/module.tsx:80]: should we also change the real property value?  `labelRotation`?

Comment (dprokop) [reply public/app/plugins/panel/barchart/module.tsx:80]: Yeah, think this should be changed

File: packages/grafana-ui/src/components/Slider/styles.ts [hunk 2]
```diff
@@ -14,7 +14,8 @@ export const getStyles = stylesFactory((theme: GrafanaTheme2, isHorizontal: bool
   return {
     container: css`
       width: 100%;
-      margin: ${isHorizontal ? 'none' : `${spacing(1, 3, 1, 1)}`};
+      margin: ${isHorizontal ? 'inherit' : `${spacing(1, 3, 1, 1)}`};
+      padding-bottom: ${isHorizontal ? theme.spacing(1) : 'inherit'};
```
Comment (torkelo) [inline packages/grafana-ui/src/components/Slider/styles.ts:18]: This creates too much bottom padding for normal sliders 
Screenshot from 2021-11-10 16-11-10

Comment (oscarkilhed) [reply packages/grafana-ui/src/components/Slider/styles.ts]: Changed it so that the padding is only added when marks have been defined.

File: public/app/plugins/panel/barchart/module.tsx (hunk 1 above)
Comment (oscarkilhed) [reply public/app/plugins/panel/barchart/module.tsx]: changed to xTickLabels[Rotation/MaxLength]

**Review by dprokop — APPROVED** [review]
Works good with the padding added!
