### PR TITLE
SQL: Remove double quotes for multi-value variables

### LINKED ISSUE #63295: Postgresql query editor adds extra quotes for multi variables
Seems that multi-value variables are handled differently than single-value variables in the postgres query editor (builder and code editor).

Reproduction steps:

Create a variable var_nonmulti, type custom, values a, b, c , don't check "Multi-value"
Create a variable var_multi, type custom, values a, b, c , DO check "Multi-value"
Create a postgres data source
Create a panel with postgres datasource. 
In code editor, add SQL:
select * from mytable where device_id='${var_nonmulti}' or device_id='${var_multi}'
Execute SQL.

In Postgresql log, I see:
2023-02-11 08:17:54.065 UTC [761] ERROR:  syntax error at or near "a" at character 58
2023-02-11 08:17:54.065 UTC [761] STATEMENT:  select * from devices where device_id='a' or device_id=''a''

I expect to not have double quoutes around the var_multi value.

**Environment**:
- Grafana version: docker.io/grafana/grafana:9.3.6
- Data source type & version: docker.io/timescale/timescaledb:latest-pg14
- OS Grafana is installed on: Windows 10, Rancher Desktop
- User OS & Browser: Windows 10, Microsoft Edge 109.0.1518.78
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by sjd210**
**What is this feature?**

Fix for SQL WHERE...IN... clauses such that multi-value variables are correctly queried as a list of strings e.g. ('Africa', 'America', 'Asia') rather than a quoted list of strings e.g. (''Africa', 'America', 'Asia'').

**Variable Set-Up**

image

image

**Query Inspector Before**

image

**Query Inspector After**

image

**Why do we need this feature?**

Previously, multi-value variables could not be queried using PostgreSQL, MySQL or MSSQL datasources.

**Who is this feature for?**

Users with SQL datasources using custom variables

**Which issue(s) does this PR fix?**:

Fixes #63295

**Special notes for your reviewer:**

We're fairly convinced that using a type assertion is the only reasonable way to do this - please don't crucify me for it :)

### CODE REVIEW

File: public/app/features/plugins/sql/components/visual-query-builder/SQLWhereRow.tsx [hunk 1]
```diff
@@ -31,6 +32,18 @@ export function SQLWhereRow({ query, fields, onQueryChange, db }: WhereRowProps)
       config={{ fields: state.value || {} }}
       sql={query.sql!}
       onSqlChange={(val: SQLExpression) => {
+        const templateSrv = getTemplateSrv();
+        const templateVars = templateSrv.getVariables() as VariableWithMultiSupport[];
```
Comment (baldm0mma) [inline public/app/features/plugins/sql/components/visual-query-builder/SQLWhereRow.tsx:36]: It's odd that this is passing the drone build, I thought we disallowed all type assertions in new code? Or am I crazy @mdvictor ?

File: public/app/features/plugins/sql/components/visual-query-builder/SQLWhereRow.tsx [hunk 2]
```diff
@@ -31,6 +32,18 @@ export function SQLWhereRow({ query, fields, onQueryChange, db }: WhereRowProps)
...
+
+        if (
+          templateVars.some((tv) => {
```
Comment (baldm0mma) [inline public/app/features/plugins/sql/components/visual-query-builder/SQLWhereRow.tsx:39]: More of a personal nit: maybe we can break this condition out into it's own function? Having 3 lines for a single condition is tough to read, in my view.

File: public/app/features/plugins/sql/components/visual-query-builder/SQLWhereRow.tsx (hunk 1 above)
Comment (sjd210) [reply public/app/features/plugins/sql/components/visual-query-builder/SQLWhereRow.tsx:36]: Type assertions _do_ normally make the build fail Betterer tests - which I was concerned about too. Victor and I looked it over together and decided this was the only reasonable solution, so we updated the Betterer file to add this to the list of accepted failures, so it now passed.

**Review by mckn — COMMENTED** [review]
I think this looks good! However since this is a central piece of code it would like to see some tests.

File: public/app/features/plugins/sql/components/visual-query-builder/SQLWhereRow.tsx [hunk 3]
```diff
@@ -49,3 +53,14 @@ function mapFieldsToTypes(columns: SQLSelectableValue[]) {
   }
   return fields;
 }
+
+export function removeQuotesForMultiVariables(val: SQLExpression, templateVars: VariableWithMultiSupport[]) {
+  if (
+    templateVars.some((tv) => {
```
Comment (baldm0mma) [inline public/app/features/plugins/sql/components/visual-query-builder/SQLWhereRow.tsx:59]: Since the return value from this arrow function is acting as a condition for the `if` statement, I would consider either moving the logic it to it's own function which you could call here - for readability - or defining a variable above the if statement encompassing said logic. I find when working with conditional statements, the less code in the condition, the easier it is to reason.

**Review by baldm0mma — CHANGES_REQUESTED** [review]
Love the tests! Just a small nit.

File: public/app/features/plugins/sql/components/visual-query-builder/SQLWhereRow.tsx (hunk 3 above)
Comment (mckn) [reply public/app/features/plugins/sql/components/visual-query-builder/SQLWhereRow.tsx:59]: +1 on this

**Review by mckn — APPROVED** [review]
LGTM! Agree with @baldm0mma regarding the if statement

File: public/app/features/plugins/sql/components/visual-query-builder/SQLWhereRow.tsx (hunk 3 above)
Comment (sjd210) [reply public/app/features/plugins/sql/components/visual-query-builder/SQLWhereRow.tsx:59]: Makes sense to me! I'll push through that change quickly now.

**Review by baldm0mma — APPROVED** [review]
Awesome! LGTM.
