### PR TITLE
prom: add support for default step param in backend

### LINKED ISSUE #9777: "tsdb.HandleRequest() error invalid value type"
I test the Alert but throw out error:
    "tsdb.HandleRequest() error invalid value type"
I use version 4.6.1
But I test same operating in version 4.5.2, no error thrown out, and working properly
image

### PR DESCRIPTION
**Pull request by bergquist**
closes #9777

### CODE REVIEW

File: pkg/tsdb/interval.go [hunk 1]
```diff
@@ -6,25 +6,52 @@ import (
...
+	from := timerange.MustGetFrom().UnixNano()
+	interval := time.Duration((to - from) / defaultRes)
 
-	if interval < minInterval {
-		return Interval{Text: formatDuration(minInterval), Value: interval}
+	if interval < ic.minInterval {
+		return Interval{Text: formatDuration(ic.minInterval), Value: ic.minInterval}
 	}
 
-	return Interval{Text: formatDuration(roundInterval(interval)), Value: interval}
```
Comment (bergquist) [inline pkg/tsdb/interval.go]: Not sure why we interval directly before. Can't think of any reason where text and value shouldn't align?

Comment (torkelo) [reply pkg/tsdb/interval.go]: what do you mean interval directly? the Text version is for example "10s" and the value I think is the raw duration value (in go duration type). The text can be used in query languages that support it I think, the the raw value can be used otherwise. 

For example InfluxDB uses the Text version: 
https://github.com/grafana/grafana/blob/master/pkg/tsdb/influxdb/query.go#L38

File: pkg/tsdb/prometheus/prometheus.go [hunk 2]
```diff
@@ -163,9 +158,25 @@ func parseQuery(queries []*tsdb.Query, queryContext *tsdb.TsdbQuery) (*Prometheu
 		return nil, err
 	}
 
+	intervalFactor := queryModel.Model.Get("intervalFactor").MustInt64(1)
+
+	var step time.Duration
+	stepSeconds, err := queryModel.Model.Get("step").Int64()
```
Comment (torkelo) [inline pkg/tsdb/prometheus/prometheus.go]: dont think we ever should look at the step model property, it was a bug to use this in the first place and the way it was stored using the last time range you saved the dashboard with makes this pretty random if this is what you actually want.

File: pkg/tsdb/prometheus/prometheus.go [hunk 3]
```diff
@@ -163,9 +158,25 @@ func parseQuery(queries []*tsdb.Query, queryContext *tsdb.TsdbQuery) (*Prometheu
...
+	if err != nil {
+		if err.Error() == "invalid value type" {
+			calculator := tsdb.NewIntervalCalculator(&tsdb.IntervalOptions{MinInterval: time.Second * 1})
```
Comment (torkelo) [inline pkg/tsdb/prometheus/prometheus.go]: should this not look at the queryModel.Model.Get("interval")  (it contains the min interval value).

File: pkg/tsdb/prometheus/prometheus.go [hunk 4]
```diff
@@ -163,9 +158,25 @@ func parseQuery(queries []*tsdb.Query, queryContext *tsdb.TsdbQuery) (*Prometheu
...
+			interval := calculator.Calculate(queryContext.TimeRange)
+			step = interval.Value / time.Duration(intervalFactor)
```
Comment (torkelo) [inline pkg/tsdb/prometheus/prometheus.go]: Should this not be a multiplication? The intervalFactor is 1,2,3,4,5 or 10. And if understand the frontend code it is factor that "lowers the resultion" by that amount, ie increasing the step by that amount: 

also intervalFactor is not a duration. 

https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/datasource.ts#L162

**Review by torkelo — CHANGES_REQUESTED** [review]

File: pkg/tsdb/prometheus/prometheus.go (hunk 3 above)
Comment (bergquist) [reply pkg/tsdb/prometheus/prometheus.go]: We don't support that in the Prometheus data source. But it would be a good thing to align the min interval with Prometheus scrape interval. But that might be out of scope for this issue. 

The reason I introduced this option was to set a different lowest possible interval for Influxdb and Prometheus.

File: pkg/tsdb/prometheus/prometheus.go (hunk 4 above)
Comment (bergquist) [reply pkg/tsdb/prometheus/prometheus.go]: Yes! Brain fart....

I cast it to duration to make it possible to divide (soon multiply) it with interval (time.Duration). Casting interval to int64 and then back to time.Duration felt noisy.

File: pkg/tsdb/prometheus/prometheus.go (hunk 2 above)
Comment (bergquist) [reply pkg/tsdb/prometheus/prometheus.go]: Right, I totally forgot that discussion we had.

Taking a step back I wonder if it makes sense to set step to anything else then the scrape interval for alerting queries. If we scrape every 10s and set step to 1, Prometheus will return the same value every second for 10s. 

Most current reducers wont be affected by this. `count()` and `count_non_null()` would be kinda weird.

File: pkg/tsdb/prometheus/prometheus.go (hunk 3 above)
Comment (torkelo) [reply pkg/tsdb/prometheus/prometheus.go]: We do support it an interval option (min step parameter in query editor)

File: pkg/tsdb/interval.go [hunk 5]
```diff
@@ -6,25 +6,56 @@ import (
...
 
 var (
-	defaultRes  int64         = 1500
-	minInterval time.Duration = 1 * time.Millisecond
-	year        time.Duration = time.Hour * 24 * 365
-	day         time.Duration = time.Hour * 24 * 365
+	defaultRes         int64         = 1500
+	defaultMinInterval time.Duration = 1 * time.Millisecond
+	year               time.Duration = time.Hour * 24 * 365
+	day                time.Duration = time.Hour * 24 * 365
```
Comment (aidjek) [inline pkg/tsdb/interval.go]: Why `day` definition has same value as and `year`? Is it not typo ?

Comment (bergquist) [reply pkg/tsdb/interval.go]: Good catch! :)

Fixed in my last commit. Good thing it was only used for formatting.

File: pkg/tsdb/interval.go (hunk 1 above)
Comment (bergquist) [reply pkg/tsdb/interval.go]: We only used the rounded value for the `Text` property. I think both `Text` and `Value` should be rounded.
