### PR TITLE
Prometheus: Fix creation of invalid dataframes with exemplars

### LINKED ISSUE #73654: Exemplars: Grafana panics if any time series has >1 unique label name
### What happened?

When Grafana calls /query_exemplars API to retrieve exemplars and visualize in a panel, Grafana panics if two or more exemplars within the same timeseries have different exemplars label names. This can happen if a client changes how they instrument their exemplars in code, and then call /query_exemplars with time range spanning the time that they changed their instrumentation. Here is an example /query_exemplars response that would cause Grafana to panic because both "trace_id" and "mytraceid" are returned as exemplars labels within the same timeseries:

```
{
    "status": "success",
    "data": [
        {
            "seriesLabels": {
                "__name__": "exemplar_my_histogram_bucket",
                "cluster": "vishwa-e-3",
                "dim1": "E",
                "dim2": "F",
                "instance": "exemplars.kube-system.svc.cluster.local:80",
                "job": "custom-metrics-vishwa",
                "le": "2.000000000000002",
                "service.instance.id": "exemplars.kube-system.svc.cluster.local:80",
                "service.name": "custom-metrics-vishwa"
            },
            "exemplars": [
                {
                    "labels": {
                        "trace_id": "fa128244a04e3167"
                    },
                    "value": "1.957157657274828",
                    "timestamp": 1692560698.655
                },
                {
                    "labels": {
                        "mytraceid": "fa128244a04e3167"
                    },
                    "value": "1.957157657274828",
                    "timestamp": 1692560698.655
                }
         ]
     ]
}
```

Here is what Grafana shows in case the above is returned:
image

When I check the error message in Grafana logs, I see:
`
logger=context userId=1 orgId=1 uname=admin t=2023-08-22T13:57:58.0230053-07:00 level=error msg="Request error" error="runtime error: index out of range [230] with length 230" stack="/usr/local/go/src/runtime/panic.go:113 (0x4ae1e)\n/opt/drone/gomodcache/github.com/grafana/grafana-plugin-sdk-go@v0.160.0/data/vector.gen.go:771 (0x7475b2)\n/opt/drone/gomodcache/github.com/grafana/grafana-plugin-sdk-go@v0.160.0/data/field.go:213 (0x2ed7b46)\n/drone/src/pkg/tsdb/prometheus/querydata/exemplar/framer.go:72 (0x2ed7b35)\n/drone/src/pkg/tsdb/prometheus/querydata/response.go:97 (0x2edc01e)\n/drone/src/pkg/tsdb/prometheus/querydata/response.go:49 (0x2edb7b4)\n/drone/src/pkg/tsdb/prometheus/querydata/request.go:213 (0x2edacd8)\n/drone/src/pkg/tsdb/prometheus/querydata/request.go:144 (0x2eda1a4)\n/drone/src/pkg/tsdb/prometheus/querydata/request.go:102 (0x2ed98a9)\n/drone/src/pkg/tsdb/prometheus/prometheus.go:89 (0x2edf51b)\n/drone/src/pkg/plugins/backendplugin/coreplugin/core_plugin.go:86 (0x2ee5050)\n/drone/src/pkg/plugins/plugins.go:259 (0xeca6d4)\n/drone/src/pkg/plugins/manager/client/client.go:60 (0x30316b1)\n/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:70 (0x302f541)\n/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:145 (0x30304f1)\n/drone/src/pkg/plugins/manager/client/client.go:56 (0x3031196)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/httpclient_middleware.go:71 (0x303653e)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/resource_response_middleware.go:26 (0x303768a)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/cookies_middleware.go:90 (0x303577b)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/oauthtoken_middleware.go:100 (0x30370fc)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/clear_auth_headers_middleware.go:48 (0x3034d0a)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/tracing_header_middleware.go:54 (0x3037eea)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/tracing_middleware.go:85 (0x30390db)\n/drone/src/pkg/plugins/manager/client/decorator.go:35 (0x3032ea8)\n/drone/src/pkg/services/query/query.go:250 (0x21fac75)\n/drone/src/pkg/services/query/query.go:95 (0x21f8ff1)\n/drone/src/pkg/api/metrics.go:55 (0x24942c2)\n/drone/src/pkg/api/routing/routing.go:17 (0x16ba521)\n/drone/src/pkg/api/response/web_hack.go:40 (0xe9c8f5)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:134 (0xe90194)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/extensions/ratelimiting/ratelimiting.go:54 (0x2eeb79a)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/services/contexthandler/contexthandler.go:242 (0x16a7a17)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/render.go:44 (0xe90d75)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/macaron.go:140 (0xe9023b)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/middleware/csrf/csrf.go:66 (0x1ca5ba5)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/middleware/recovery.go:171 (0x16b45c1)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/middleware/loggermw/logger.go:71 (0x1ca6c97)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/middleware/request_metrics.go:59 (0x16b53c9)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/middleware/request_tracing.go:88 (0x16b6cfa)\n/usr/local/go/src/net/http/server.go:2122 (0x3ee6ee)\n/drone/src/pkg/web/context.go:52 (0xe8e97d)\n/drone/src/pkg/web/router.go:155 (0xe92329)\n/drone/src/pkg/web/router.go:211 (0xe92e95)\n/drone/src/pkg/web/macaron.go:166 (0xe906b0)\n/usr/local/go/src/net/http/server.go:2936 (0x3f1835)\n/usr/local/go/src/net/http/server.go:1995 (0x3ed211)\n/usr/local/go/src/runtime/asm_amd64.s:1598 (0x82520)\n"
`

### What did you expect to happen?

I expected both exemplars to be plotted successfully with both label names.

### Did this work before?

No, this never worked. I tried with a few Grafana versions including the latest.

### How do we reproduce it?

1. Mock a /query_exemplars response that has this property -- at least two exemplars have different label names within the same time series.
2. Try to plot in a panel.
3. You should see this "internal server error" and when you go to logs, see that Grafana is panicking.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 10.0.3
OS: Windows
Browser: Edge

### Grafana platform?

A downloaded binary

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by kylebrandt**
With different labels for examplars, the prom response parser would create invalid frames (different field lengths). The prom datasource would then panic processing these frames.

This adds a test case for it and addresses the issue.

**Which issue(s) does this PR fix?**:

Fixes #73654

**Special notes for your reviewer:**

It was creating something like the following:

```
(*data.Frame)(0xc000b3f7c0)({
 Name: (string) "",
 Fields: ([]*data.Field) (len=4 cap=4) {
  (*data.Field)(0xc000aadaa0)({
   Name: (string) (len=4) "Time",
   Labels: (data.Labels) ,
   Config: (*data.FieldConfig)(<nil>),
   vector: (*data.timeTimeVector)(0xc0002018d8)((len=2 cap=2) {
    (time.Time) 2022-06-01 12:28:36.81 +0000 UTC,
    (time.Time) 2031-12-03 17:48:36.81 +0000 UTC
   })
  }),
  (*data.Field)(0xc000aadad0)({
   Name: (string) (len=5) "Value",
   Labels: (data.Labels) (len=9) __name__=traces_spanmetrics_duration_seconds_bucket, group=mythical, instance=f1c32fe505c3, le=0.256, service=mythical-requester, source=tempo, span_kind=SPAN_KIND_CLIENT, span_name=requester, span_status=STATUS_CODE_OK,
   Config: (*data.FieldConfig)(<nil>),
   vector: (*data.float64Vector)(0xc0002018f0)((len=2 cap=2) {
    (float64) 1.134971,
    (float64) 1.134971
   })
  }),
  (*data.Field)(0xc000aadb30)({
   Name: (string) (len=7) "traceID",
   Labels: (data.Labels) ,
   Config: (*data.FieldConfig)(<nil>),
   vector: (*data.stringVector)(0xc000201908)((len=1 cap=1) {
    (string) (len=32) "46e15ae41852149068aeb26c64643c29"
   })
  }),
  (*data.Field)(0xc000aadb60)({
   Name: (string) (len=8) "ztraceID",
   Labels: (data.Labels) ,
   Config: (*data.FieldConfig)(<nil>),
   vector: (*data.stringVector)(0xc000201950)((len=1 cap=1) {
    (string) (len=32) "46e15ae41852149068aeb26c64643c29"
   })
  })
 },
```

Which wouldn't marshal to JSON, so if we had the test case the existing tests would have failed.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/util/converter/prom.go [hunk 1]
```diff
@@ -417,7 +418,6 @@ l1Fields:
 						timeField.Append(ts)
 
 					case "labels":
-						max := 0
 						pairs, err := readLabelsAsPairs(iter)
```
Comment (toddtreece) [inline pkg/util/converter/prom.go:421]: not really related to this PR, but one thing i just noticed while reviewing this locally is that we don't seem to handle an exemplar without labels.

**Review by toddtreece — APPROVED** [review]

**Review by itsmylife — APPROVED** [review]
