### PR TITLE
Queries: Move explore state out of query targets

### LINKED ISSUE #26202: CloudWatch: Various internal variables leaked with query requests
**What happened**:
Certain variables that should be internal to grafana/explore such as `liveStreaming` and `showingGraph` are sent along as part of the query request.
image

**What you expected to happen**:
For only the data relevant to the query request to be sent.

**How to reproduce it (as minimally and precisely as possible)**:
- Navigate to Explore
- Select a CloudWatch Datasource
- Make a CloudWatch metrics query
- Investigate the query request in your browser's devtools

**Anything else we need to know?**:
The unwanted variables in question are attached to the queries as part of `buildQueryTransaction` (in public/app/core/utils/explore.ts). This isn't a problem in and of itself but when the actual query is sent we should use lodash pick or similar to send only the relevant parameters.

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Before being provided to a data source's query method, query targets are populated with various pieces of explore state
in `buildQueryTransaction`. Since this data isn't query-specific, it makes more sense to move it out of the targets and up a level as part of the `DataQueryRequest` object

**Which issue(s) this PR fixes**:
Closes #26202

### CODE REVIEW

File: public/app/plugins/datasource/cloudwatch/datasource.ts [hunk 1]
```diff
@@ -199,12 +218,14 @@ export class CloudWatchDatasource extends DataSourceApi<CloudWatchQuery, CloudWa
             throw { message: 'Invalid extended statistics' };
           }
 
+          const reducedItem = _.pick(item, metricsParams);
```
Comment (papagian) [inline public/app/plugins/datasource/cloudwatch/datasource.ts:221]: I have a small concern how we can be sure that the above list is complete therefore I would prefer to filter out the internal to explorer variables instead if this is feasible.

File: public/app/plugins/datasource/loki/datasource.ts [hunk 2]
```diff
@@ -44,7 +44,10 @@ import LanguageProvider from './language_provider';
 import { serializeParams } from '../../../core/utils/fetch';
 import { RowContextOptions } from '@grafana/ui/src/components/Logs/LogRowContextProvider';
 
-export type RangeQueryOptions = Pick<DataQueryRequest<LokiQuery>, 'range' | 'intervalMs' | 'maxDataPoints' | 'reverse'>;
+export type RangeQueryOptions = Pick<
+  DataQueryRequest<LokiQuery>,
+  'range' | 'intervalMs' | 'maxDataPoints' | 'reverse' | 'liveStreaming' | 'showingGraph' | 'showingTable'
```
Comment (torkelo) [inline public/app/plugins/datasource/loki/datasource.ts:49]: This RangeQueryOptions type feels very mess, is there an easier way to define it?

Comment (kaydelaney) [reply public/app/plugins/datasource/loki/datasource.ts:49]: You're right. I'll take a look and see if I can improve it

**Review by aocenas — APPROVED** [review]
