### PR TITLE
Explore: Load default data source in Explore when the provided source does not exist

### LINKED ISSUE #32782: Explore: Blank page when datasource in localStorage is missing
**What happened**:
When opening Explore, the pre-default datasource is set to the last one used. It might happen that a datasource gets removed or renamed, in that case Explore only shows a blank page.

In this example I'm manually editing localstorage, but the result it's equivalent to deleting/renaming a datasource. 

https://user-images.githubusercontent.com/1170767/114010040-9ee22a00-985b-11eb-8cba-c231db8ed721.mov

**What you expected to happen**:
In such condition I'd expect the default datasource to be selected instead and the explore page to be usable.

**How to reproduce it (as minimally and precisely as possible)**:

- Open Explore
- Manually edit `grafana.explore.datasource.1` entry in localstorage to something non-existent (this imitates deleting a datasource, or renaming one)
- Navigate somewhere else and then back to `/explore`

**NOTE**: Only refreshing the explore page doesn't trigger the problem, as the datasource specified in the URL takes precedence over the one in localstorage

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.3

### PR DESCRIPTION
**Pull request by ifrost**
**What this PR does / why we need it**:

**Problem**: When the data source that was recently used in Explore is removed or renamed the Explore panel goes blank when it's opened. 

**Root cause**: Explores attempts to load recently used data source based on its name saved in the local storage but it doesn't handle the scenario when the data source is not found.

**Fixes**:
1. Add a fallback to default data source when the provided one is not found
2. Save uid instead of the name of the data source to load the correct data source when it gets renamed

**Which issue(s) this PR fixes**:

Fixes #32782 

**Special notes for your reviewer**:

[Data source can be loaded by uid or name already](https://github.com/grafana/grafana/blob/master/public/app/features/plugins/datasource_srv.ts#L83) so switching name to uid will be backwards compatible.

### CODE REVIEW

File: public/app/features/explore/state/utils.ts [hunk 1]
```diff
@@ -63,7 +63,17 @@ export async function loadAndInitDatasource(
...
+  let instance;
+  try {
+    instance = await getDatasourceSrv().get(datasourceName);
+  } catch (error) {
+    // Falling back to the default data source in case the provided data source was not found.
+    // It may happen if last used data source or the data source provided in the URL has been
+    // removed or it is not provisioned anymore.
+    console.error(error);
+    instance = await getDatasourceSrv().get();
+    console.info('Default datasource loaded.');
```
Comment (Elfo404) [inline public/app/features/explore/state/utils.ts:75]: do we really need to print to console?

Comment (ifrost) [reply public/app/features/explore/state/utils.ts:75]: Nope and hmmm... actually in this case might be even misleading as both lines may not appear next to each other. I'll remove `console.info`. I think it may be worth keeping `console.error` as there is no UI warning displayed in this case.

Comment (Elfo404) [reply public/app/features/explore/state/utils.ts:75]: but what's the point of showing an error in the console in the first place?

if this was an actual runtime error we probably should have surfaced it in the UI, but we actually expect the datasource to not be there, and we just fallback to the default one in case the one you last visited is not present anymore.

Also,

Comment (ifrost) [reply public/app/features/explore/state/utils.ts:75]: True that! I'll ditch both.

File: public/app/features/explore/state/utils.ts [hunk 2]
```diff
@@ -77,7 +85,7 @@ export async function loadAndInitDatasource(
   const history = store.getObject(historyKey, []);
   // Save last-used datasource
 
-  store.set(lastUsedDatasourceKeyForOrgId(orgId), instance.name);
+  store.set(lastUsedDatasourceKeyForOrgId(orgId), instance.uid);
```
Comment (Elfo404) [inline public/app/features/explore/state/utils.ts:88]: 👍

**Review by Elfo404 — APPROVED** [review]
LGTM! 🚀
