### PR TITLE
DataSource: Fix secure json data reset on datasource update

### LINKED ISSUE #48525: Data source config's [save&test] button removes basic-auth password when pressed 2 times
when a datasource is configured, the user can enable basic-auth authentication. when the details are filled in, and the datsource saved, everything is ok. but if you press Save one more time, it removes the basic auth password.

how to reproduce:

- go to the config page of a datasource
- enable “basic auth”
- fill in a username & password (they don’t have to be valid)
- press [save&test]
- see that the password changed to `configured` and a [reset] button appeared next to it. this is good.
- now press [save&test] again.
- the basic-auth-password field was cleared
- if you reload the page, it stays cleared
- (with loki i verified also that the password is really removed from grafana, Loki does not receive the basic-auth-password from this point on. i assume this is the same for other datasources too)

this is happening since this PR was merged: https://github.com/grafana/grafana/pull/45804

### PR DESCRIPTION
**Pull request by guicaulada**
**What this PR does / why we need it**:

This PR fixes an issue introduced by #45804 that happens when clicking Save to update a Data Source without changing any secure json data information.

**Which issue(s) this PR fixes**:

Fixes #48525

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/datasources/service/datasource_service.go [hunk 1]
```diff
@@ -218,7 +214,18 @@ func (s *Service) UpdateDataSource(ctx context.Context, cmd *models.UpdateDataSo
 		}
 	}
 
-	return s.SecretsStore.Set(ctx, cmd.OrgId, cmd.Name, secretType, string(secret))
+	if len(cmd.SecureJsonData) > 0 {
```
Comment (marefr) [inline pkg/services/datasources/service/datasource_service.go:217]: I think you need to mimic the old behavior, see https://github.com/grafana/grafana/blob/0af09cd0815bfe16e9ea9ce3c2e1ce40775a4455/pkg/api/datasources.go#L342-L367

The old behavior basically merged updated secure JSON data keys with the existing stored secure JSON data.

**Review by marefr — CHANGES_REQUESTED** [review]
Might need some additional changes, see comment.

File: pkg/services/datasources/service/datasource_service.go (hunk 1 above)
Comment (marefr) [reply pkg/services/datasources/service/datasource_service.go]: > Since the keys are not merged when `len(cmd.SecureJsonData) == 0` I think we still need a check for `len(cmd.SecureJsonData) != 0` before updating the secrets. 

Don't really see any difference between `if len(cmd.SecureJsonData) > 0 {` and `if len(cmd.SecureJsonData) != 0 {` in datasource_service.go so don't understand that change - it can't be negative length, right?

> I did update `fillWithSecureJSONData` to use the `DecryptedValues` function on [d921f59](https://github.com/grafana/grafana/commit/d921f59e52056134f40f49a6fb033ae1bafe3f69).
> Do you think it would be best to keep the check for `!= 0` or remove the one that doesn't merge the keys when `len(..) == 0` ?

It's probably because it historically took for granted secureJsonData will not be updated in the database if it's empty/nil - An XORM thing. Not sure what's best, maybe safer to skip the `if len(cmd.SecureJsonData) == 0` check and always merge.

When looking at it now, maybe the fillSecureJsonData logic should be located in the datasource_service.go instead to support modifying datasources from multiple places rather than living in the API layer, but not sure. Maybe an improvement for later. WDYT?

Sorry if I provided confusing answers but was a bit unsure what code you referred to in some cases :smile: You did reference the actual code/commit above and that is great :+1:, removes any confusion.

Comment (guicaulada) [reply pkg/services/datasources/service/datasource_service.go]: It does makes sense to have that code on datasource_service.go instead.

Comment (guicaulada) [reply pkg/services/datasources/service/datasource_service.go]: Done on f800dd2

Comment (marefr) [reply pkg/services/datasources/service/datasource_service.go]: Looks good :+1:

File: pkg/services/datasources/service/datasource_service.go [hunk 2]
```diff
@@ -559,3 +565,18 @@ func awsServiceNamespace(dsType string) string {
...
 }
+
+func (s *Service) fillWithSecureJSONData(ctx context.Context, cmd *models.UpdateDataSourceCommand, ds *models.DataSource) error {
+	decrypted, err := s.DecryptedValues(ctx, ds)
+	if err != nil {
+		return err
+	}
+
+	for k, v := range decrypted {
+		if _, ok := cmd.SecureJsonData[k]; !ok {
```
Comment (marefr) [inline pkg/services/datasources/service/datasource_service.go:576]: Can `cmd.SecureJsonData` be nil/not initialized?

**Review by marefr — APPROVED** [review]
LGTM, added a comment.

File: pkg/services/datasources/service/datasource_service.go (hunk 2 above)
Comment (guicaulada) [reply pkg/services/datasources/service/datasource_service.go:580]: Sanity check added on ffad198
