### PR TITLE
Fixed Gauge being cropped when resizing panel

### LINKED ISSUE #14815: Gauge is getting cropped when resizing the panel
The broken state is persistent across reloads.

Reporoduced on:
- Chrome
- Safari
- Firefox

### PR DESCRIPTION
**Pull request by dprokop**
fix #14815 

@jschill  @peterholmberg  @hugohaggmark  FYI: Enabled import of SASS variables into TS. You can now use sass variables in TS files by importing from `sass/_variables.scss`. Note, that when exporting variables you need to update corresponding `_variables.scss.d.ts` files, otherwise TS will complain.

### CODE REVIEW

File: public/app/plugins/panel/gauge/GaugePanel.tsx [hunk 1]
```diff
@@ -15,6 +16,13 @@ export class GaugePanel extends PureComponent<Props> {
       nullValueMode: NullValueMode.Ignore,
     });
 
-    return <Gauge timeSeries={vmSeries} {...this.props.options} width={width} height={height} />;
+    return (
+      <Gauge
+        timeSeries={vmSeries}
+        {...this.props.options}
+        width={width - 2 * variables.panelHorizontalPadding}
+        height={height - variables.panelVerticalPadding}
```
Comment (torkelo) [inline public/app/plugins/panel/gauge/GaugePanel.tsx]: I wonder if we should do this in PanelChrome instead, then panel plugins do not need to bother:
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashgrid/PanelChrome.tsx#L126

Comment (dprokop) [reply public/app/plugins/panel/gauge/GaugePanel.tsx]: Well, you are right @torkelo. No matter what viz we render, the size passed shouldn't be wider than panel's content area.

File: public/sass/_variables.scss [hunk 2]
```diff
@@ -202,3 +204,8 @@ $external-services: (
     oauth: (bgColor: #262628, borderColor: #393939, icon: '')
   )
   !default;
+
+:export {
+  panelHorizontalPadding: $panel-horizontal-padding;
+  panelVerticalPadding: $panel-vertical-padding;
+}
```
Comment (jschill) [inline public/sass/_variables.scss]: Interesting! I've never seen this approach before.
