### PR TITLE
Organize transformer: Use display name in field order comparer

### LINKED ISSUE #24974: Transforms & Table Panel: Organize fields does not reorder Reduced fields
**What happened**:

image

**What you expected to happen**:

Reorganized fields

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows OS
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by dprokop**
Fixes https://github.com/grafana/grafana/issues/24974

The organize fields transformer was using `field.name` when comparing the sort order of the fields. This was wrong, as in the sort index map field display name is used. This PR is a remedy for this issue :)

### CODE REVIEW

File: packages/grafana-data/src/field/fieldState.ts [hunk 1]
```diff
@@ -47,9 +47,9 @@ export function getFieldDisplayName(field: Field, frame?: DataFrame, allFrames?:
 }
 
 /**
- * Get an appropriate display name. If the 'title' is set, use that
+ * Get an appropriate display name. If the 'displayName' field config is set, use that
  */
-function calculateFieldDisplayName(field: Field, frame?: DataFrame, allFrames?: DataFrame[]): string {
+export function calculateFieldDisplayName(field: Field, frame?: DataFrame, allFrames?: DataFrame[]): string {
```
Comment (torkelo) [inline packages/grafana-data/src/field/fieldState.ts:52]: why export this and not use getFieldDisplayName (the exported function), this is an internal function

File: packages/grafana-data/src/transformations/transformers/order.ts [hunk 2]
```diff
@@ -39,15 +39,21 @@ export const createOrderFieldsComparer = (indexByName: Record<string, number>) =
...
   if (!Array.isArray(fields) || fields.length === 0) {
     return fields;
   }
   if (!indexByName || Object.keys(indexByName).length === 0) {
     return fields;
   }
   const comparer = createOrderFieldsComparer(indexByName);
-  return fields.sort((a, b) => comparer(a.name, b.name));
+  return fields.sort((a, b) =>
+    comparer(calculateFieldDisplayName(a, frame, data), calculateFieldDisplayName(b, frame, data))
```
Comment (torkelo) [inline packages/grafana-data/src/transformations/transformers/order.ts:55]: was there a problem using getFieldDisplayName?

Comment (dprokop) [reply packages/grafana-data/src/transformations/transformers/order.ts:55]: no, just the `calculateFieldDisplayName` is a leaner one. This function stays private to grafana-data, but we can use the `getDisplayName` too and revert this change.

Comment (torkelo) [reply packages/grafana-data/src/transformations/transformers/order.ts:55]: getFieldDisplayName is the leaner one (it includes caching), and should be used always, afraid if calculateFieldDisplayName get's exported it might see some usage as well

File: packages/grafana-data/src/field/fieldState.ts (hunk 1 above)
Comment (mckn) [reply packages/grafana-data/src/field/fieldState.ts:52]: Change to `getFieldDisplayName` to get the benefit of using the cached field name.

Comment (dprokop) [reply packages/grafana-data/src/field/fieldState.ts]: fixed in 655357e
