### PR TITLE
Alerting: Add retry mechanism

### LINKED ISSUE #5855: Alert query retry
Failing queries should retry at least x times before its considered firing.

### PR DESCRIPTION
**Pull request by Thib17**
Fix #5855 

cc @bergquist , @iksaif

### CODE REVIEW

File: pkg/services/alerting/engine.go [hunk 1]
```diff
@@ -86,32 +87,79 @@ func (e *Engine) runJobDispatcher(grafanaCtx context.Context) error {
...
-			dispatcherGroup.Go(func() error { return e.processJob(alertCtx, job) })
+			dispatcherGroup.Go(func() error { return e.processJobWithRetry(alertCtx, job) })
 		}
 	}
 }
 
 var (
 	unfinishedWorkTimeout time.Duration = time.Second * 5
 	alertTimeout          time.Duration = time.Second * 30
+	alertMaxAttempts      int           = 2
```
Comment (iksaif) [inline pkg/services/alerting/engine.go]: 3 ? (plus add TODO to make that configurable in the config file)

File: pkg/services/alerting/engine.go [hunk 2]
```diff
@@ -86,32 +87,79 @@ func (e *Engine) runJobDispatcher(grafanaCtx context.Context) error {
...
+	cancelChan := make(chan context.CancelFunc, alertMaxAttempts)
+	attemptChan := make(chan int, 1)
+
+	// Initialize with first attemptID=1
+	attemptChan <- 1
+	job.Running = true
+
+	for {
+		select {
+		case <-grafanaCtx.Done():
```
Comment (iksaif) [inline pkg/services/alerting/engine.go]: can you add comments to explain the cases

File: pkg/services/alerting/engine.go [hunk 3]
```diff
@@ -86,32 +87,79 @@ func (e *Engine) runJobDispatcher(grafanaCtx context.Context) error {
...
+			unfinishedWorkTimer := time.NewTimer(unfinishedWorkTimeout)
+			for {
```
Comment (iksaif) [inline pkg/services/alerting/engine.go]: I think it should be possible to have only one for { select { } } instead of two, and that would make the code more readable

File: pkg/services/alerting/engine.go [hunk 4]
```diff
@@ -122,43 +170,36 @@ func (e *Engine) processJob(grafanaCtx context.Context, job *Job) error {
...
-
-	var err error = nil
-	select {
-	case <-grafanaCtx.Done():
-		select {
-		case <-time.After(unfinishedWorkTimeout):
-			cancelFn()
-			err = grafanaCtx.Err()
-		case <-done:
+		if (evalContext.Rule.State == models.AlertStateAlerting) && (attemptID < alertMaxAttempts) {
```
Comment (iksaif) [inline pkg/services/alerting/engine.go]: I think we want to retry on timeout and execution errors, not each time the alert is alerting

**Review by iksaif — CHANGES_REQUESTED** [review]

File: pkg/services/alerting/engine.go (hunk 1 above)
Comment (Thib17) [reply pkg/services/alerting/engine.go]: Done

File: pkg/services/alerting/engine.go (hunk 2 above)
Comment (Thib17) [reply pkg/services/alerting/engine.go]: Done

File: pkg/services/alerting/engine.go (hunk 4 above)
Comment (Thib17) [reply pkg/services/alerting/engine.go]: Fixed

File: pkg/services/alerting/engine.go (hunk 3 above)
Comment (Thib17) [reply pkg/services/alerting/engine.go]: I looks like it's not possible. I mean, it would be possible to have something that works but not as expected.
It would looks like 
```
	for {
		select {
		case <-grafanaCtx.Done():
			time.AfterFunc(unfinishedWorkTimeout, func() {
				endChan <- grafanaCtx.Err()
			})
		case err := <-endChan:
			return e.endJob(err, cancelChan, job)
		case attemptID, more := <-attemptChan:
			if !more {
				return e.endJob(nil, cancelChan, job)
			}
			go e.processJob(attemptID, attemptChan, cancelChan, job)
		}
	}
```

In golang `select` chooses one at random if multiple cases are ready.
In addition, we do need to wait for `<-grafanaCtx.Done()` to be ready, to catch grafana server context cancellation. And `<-grafanaCtx.Done()` will remain a valid case, even after executing that case.
Therefore it will loop on execution of `<-grafanaCtx.Done()` case a lot of time between grafana server context cancellation and the end of job processing; plus a random times when multiple cases are ready.
That's not the behavior that we would like.

The core issue, is that AFAIK **there is no way in golang to prioritize a case in a `select` statement**. The common workarroud (as already used here before my change) seems to have a `select` inside a `select`. And because we can now wait for several attempts, it's `for + select` inside `for + select`

File: pkg/services/alerting/engine.go [hunk 5]
```diff
@@ -86,32 +86,82 @@ func (e *Engine) runJobDispatcher(grafanaCtx context.Context) error {
...
 var (
 	unfinishedWorkTimeout time.Duration = time.Second * 5
-	alertTimeout          time.Duration = time.Second * 30
+	// TODO: Make alertTimeout and alertMaxAttempts configurable in the config file.
+	alertTimeout     time.Duration = time.Second * 30
+	alertMaxAttempts int           = 3
 )
 
-func (e *Engine) processJob(grafanaCtx context.Context, job *Job) error {
+func (e *Engine) processJobWithRetry(grafanaCtx context.Context, job *Job) error {
```
Comment (bergquist) [inline pkg/services/alerting/engine.go]: I think we need a few tests for this function. To many moving pieces right now. Creating an interface for the EvalHandler should make it fairly easy.

**Review by bergquist — CHANGES_REQUESTED** [review]
Looks good but I would love to see some tests for this. I know we currently lack tests on this part but that's something we have to improve.

File: pkg/services/alerting/engine.go (hunk 3 above)
Comment (iksaif) [reply pkg/services/alerting/engine.go]: Maybe it would be worth it putting the inner for in a separate method/function then.

While I understand that you want to let the job finish, why do we allow new attempts when `grafanaCtx.Done()` ? (What is `grafanaCtx.Done()` exactly ?)

Comment (bergquist) [reply pkg/services/alerting/engine.go]: `grafanaCtx.Done()` gets a signal when Grafana wants to shut down. Which gives alerting some time to save its current state to the database first. 

It's slight abusive way of using Context. But back when I wrote it I didn't find any other solution that I liked.

Comment (iksaif) [reply pkg/services/alerting/engine.go]: Ok, so in this case clearly we don't want to attempt new retries on grafanaCtx.Done() :)

Comment (Thib17) [reply pkg/services/alerting/engine.go]: Fixed

File: pkg/services/alerting/engine.go (hunk 5 above)
Comment (Thib17) [reply pkg/services/alerting/engine.go]: Done

**Comment by bergquist** [comment]
This is not working as expected. 

If I start Grafana with one alert rule in `ok` state but without a running datasource I expected that alert rule to change to `alerting` but it doesn't. The reason for this is that evalHandler updates state to alerting on the first attempt so when we stop sending new attempts and handle the result both states are in alerting. 

Not sure how to solve this in a good way. Right now I see two solutions
* pass a bool telling evalHandler if there could be retries.. ex `hasMoreAttempts` 
* move `getNewState` in eval handler to `EvalContext` and update the state in the engine before passing `EvalContext` to the result handler. 

Do you have any other suggestions?

**Comment by Thib17** [comment]
Oh you're right. Sorry, I didn't saw that.
From the two solutions you suggested, I like the second one: _move getNewState in eval handler to EvalContext_. (And there already is a comment to do it)

File: pkg/services/alerting/engine.go [hunk 6]
```diff
@@ -86,32 +86,77 @@ func (e *Engine) runJobDispatcher(grafanaCtx context.Context) error {
...
+	cancelChan <- cancelFn
 	span := opentracing.StartSpan("alert execution")
 	alertCtx = opentracing.ContextWithSpan(alertCtx, span)
 
-	job.Running = true
 	evalContext := NewEvalContext(alertCtx, job.Rule)
 	evalContext.Ctx = alertCtx
 
-	done := make(chan struct{})
 	go func() {
```
Comment (bergquist) [inline pkg/services/alerting/engine.go]: I'm not sure we need this anonymous function anymore since we call processJob with `go` at 131

Looks good overall. I just want to see if we can improve maintainability before I merge it.

**Review by bergquist — APPROVED** [review]

**Comment by bergquist** [comment]
@iksaif Anything else you want to add before I merge this?

File: pkg/services/alerting/engine.go (hunk 6 above)
Comment (bergquist) [reply pkg/services/alerting/engine.go]: Nevermind. I can fix this later

**Comment by iksaif** [comment]
:+1:  LGTM

**Comment by bergquist** [comment]
Great work! :) Thank you for contributing

**Comment by dudusakharovich** [comment]
@bergquist - Hey,
Is this feature already exists in Beta 5.1.0, because I've installed it on a test machine and I can't find the option to retry.

**Comment by bergquist** [comment]
@dudusakharovich its not an option. Grafana will always retry 3 times
