### PR TITLE
Dashboard: Make legend colors and link rows keyboard accessible

### LINKED ISSUE #116513: [SEV1] Keyboard focus does not move to controls under the Visualizations section.
**Steps to reproduce**:
1. Create a new dashboard
2. Navigate to "Add visualization" button and hit ENTER key. "Select data source" popup will appear.
3. Navigate to the TestData list item select it. 
4. Navigate to all controls under  right side pane like  visualization, Panel options , Tooltip section ,Legend Sections .
5. Attempt to interact with the controls using keyboard navigation.
6. Observe that keyboard focus skips the controls entirely, and no visible focus indicator is present.

**Actual Result**:
Keyboard focus skips the controls under the Visualizations section entirely, leaving them inaccessible to keyboard users.
Observation:
The controls under the Visualizations section are not focusable via keyboard navigation (Tab or down arrow key). Additionally, there is no visible focus indicator for these controls, preventing users from identifying which element is currently focused.
Issue1: Same issue repro for the color button under the new panel section. 
Navigation: Select “ Add visualization” button > Select testdata list item> Select last 7 hours option in the combo box next to table view toggle button > Observe that the color button under the new panel section below the graph is not keyboard accessible.  
Issue 2: Same issue repro for the interactive rows under the link tab in the settings. 
Navigation: Select “ Add visualization” button > Select testdata list item> Select back to dasboard > Select settings button in the toolbar > Go to links tab in the setting > add New link button > Select back to dashboard > Again select links > Observe that the interactive rows are not keyboard accessible. 

**Expected Result**
The controls under the Visualizations section should be accessible via keyboard navigation, allowing users to move focus to them using Tab or ALT down arrow key. Each control should have a visible focus indicator to clearly show which element is currently focused, ensuring users can identify the active element. Additionally, the focus order should follow a logical sequence that preserves the intended meaning and operability of the interface, enabling seamless interaction for keyboard users.

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)
WCAG: [2.1.1 Keyboard](https://www.w3.org/WAI/WCAG21/Understanding/keyboard.html)
Section 508: [E207.2 WCAG Conformance](https://www.access-board.gov/ict/#E207.2), [E205.4 Accessibility Standard](https://www.access-board.gov/ict/#E205.4) and [E205.4.1 Word Substitution when Applying WCAG to Non-Web Documents](https://www.access-board.gov/ict/#E205.4.1), and [E207.2.1 Word Substitution when Applying WCAG to Non-Web Software](https://www.access-board.gov/ict/#e207-2-1-word-substitution-when-applying-wcag-to-non-web-softwar).
EN 301 549: [PDF of EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf), which applies WCAG principles for Keyboard to 9.2.1.1 web, 10.2.1.1 non-web documents, and 11.2.1.1.1 software.

**Environment**:
- Grafana version: 12.2.0
- Data source type & version: n/a
- User OS & Browser: n/a
- Others:

### PR DESCRIPTION
**Pull request by DivyamUp14**
**Which issue(s) does this PR fix?**:

Fixes #116513

### Scope Clarification
This PR addresses **Issue 1** and **Issue 2** from the linked issue:
- **Issue 1**: Legend color button not keyboard accessible
- **Issue 2**: Dashboard link rows not keyboard accessible
**Note**: The main flow (steps 1-6) appears to be working correctly in my testing - I was able to navigate through panel sections, visualization controls, and legend settings using keyboard. If this is still an issue, additional reproduction details would be helpful.

### CODE REVIEW

File: packages/grafana-ui/src/components/VizLegend/SeriesIcon.tsx [hunk 1]
```diff
@@ -12,6 +12,7 @@ export interface Props extends React.HTMLAttributes<HTMLDivElement> {
   gradient?: string;
   lineStyle?: LineStyle;
   noMargin?: boolean;
+  tabIndex?: number;
```
Comment (ashharrison90) [inline packages/grafana-ui/src/components/VizLegend/SeriesIcon.tsx]: this isn't needed. the props already extend the base htmlattributes, so `tabIndex` is already defined

File: packages/grafana-ui/src/components/VizLegend/VizLegendSeriesIcon.tsx [hunk 2]
```diff
@@ -30,16 +30,26 @@ export const VizLegendSeriesIcon = memo(({ seriesName, color, gradient, readonly
...
+        {({ ref, showColorPicker, hideColorPicker }) => {
+          function handleKeyDown(e: React.KeyboardEvent<HTMLSpanElement>) {
+            if (e.key === ' ' || e.key === 'Enter') {
+              e.preventDefault();
+              showColorPicker();
+            }
+          }
+          return (
+            <SeriesIcon
+              tabIndex={0}
```
Comment (ashharrison90) [inline packages/grafana-ui/src/components/VizLegend/VizLegendSeriesIcon.tsx:42]: think we should add `role="button"` here as well

**Review by ashharrison90 — COMMENTED** [review]
couple of nits, otherwise lgtm, thanks! 👍 

you'll also need to merge/rebase with main i think to get all the CI checks to pass

**Comment by DivyamUp14** [comment]
> couple of nits, otherwise lgtm, thanks! 👍
> 
> you'll also need to merge/rebase with main i think to get all the CI checks to pass

Thank you for feedback @ashharrison90 addressed them and rebased with the main

**Review by ashharrison90 — APPROVED** [review]
lgtm! thanks for the contribution 🙌

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/22095247098)
- Version: 12.4.0-22095247098

**Comment by DivyamUp14** [comment]
Thanks for the review! Really appreciate it 🙌
