### PR TITLE
Scenes: Fix issue where "get help" drawer was empty in panel edit mode

### LINKED ISSUE #89095: Dashboard scenes: The get help screen feature does not properly populate when accessed through panel edit.
When using scenes dashboards. Clicking the get help menu option on a panel from the dashboard view properly populates the debug dashboard, but if the menu item is clicked from inside the edit panel view the debug dashboard is not populated with data.

Context: https://raintank-corp.slack.com/archives/C03KVDHTWAH/p1718135082061829

### PR DESCRIPTION
**Pull request by kaydelaney**
Fixes an issue where the debug dashboard was not correctly populated with panel data when the "get help" option is chosen while in panel edit mode.

Closes #89095

### CODE REVIEW

**Comment by dprokop** [comment]
@kaydelaney there's a problem(not present in the old arch) with the get help view when rendomization options are enabled/disabled, see the attached video:


https://github.com/grafana/grafana/assets/2376619/0035e259-b8d1-454e-84f0-91dfdbc325ba

**Comment by kaydelaney** [comment]
@dprokop Good catch, will investigate

File: public/app/features/dashboard-scene/inspect/HelpWizard/utils.ts [hunk 1]
```diff
@@ -62,15 +63,31 @@ export function getGithubMarkdown(panel: VizPanel, snapshot: string): string {
...
   if (isLibraryPanel) {
     saveModel = {
       ...gridItemToPanel(gridItem),
       ...vizPanelToPanel(panel),
     };
+  } else if (scene.state.editPanel) {
+    // If panel edit mode is open when the user chooses the "get help" panel menu option
+    // we want the debug dashboard to include the panel with any changes that were made while
+    // in panel edit mode.
+    const gridItems = (scene.state.body as SceneGridLayout).state.children as DashboardGridItem[];
```
Comment (mdvictor) [inline public/app/features/dashboard-scene/inspect/HelpWizard/utils.ts:80]: I think we need to pull gridItems from rows as well. Otherwise the issue will still exist for panels in rows when clicking "get help" in panel edit.

**Review by mdvictor — COMMENTED** [review]
Tested this out and works well overall, except for panels that are in a row.

File: public/app/features/dashboard-scene/inspect/HelpWizard/utils.ts (hunk 1 above)
Comment (dprokop) [reply public/app/features/dashboard-scene/inspect/HelpWizard/utils.ts:80]: Victor is right. The get help view is empty when inspecting a panel that is within a repeated row.

**Comment by dprokop** [comment]
> @dprokop Good catch, will investigate

@kaydelaney  - the issue i found is now fixed, I can confirm. Thanks!

File: public/app/features/dashboard-scene/inspect/HelpWizard/utils.ts [hunk 2]
```diff
@@ -62,15 +63,29 @@ export function getGithubMarkdown(panel: VizPanel, snapshot: string): string {
...
     saveModel = {
       ...gridItemToPanel(gridItem),
       ...vizPanelToPanel(panel),
     };
+  } else if (scene.state.editPanel) {
+    // If panel edit mode is open when the user chooses the "get help" panel menu option
+    // we want the debug dashboard to include the panel with any changes that were made while
+    // in panel edit mode.
+    const sourcePanel = scene.state.editPanel.state.vizManager.state.sourcePanel.resolve();
+    const parentItem = sourcePanel.parent as DashboardGridItem | LibraryVizPanel;
```
Comment (mdvictor) [inline public/app/features/dashboard-scene/inspect/HelpWizard/utils.ts:81]: Nit: I think we can skip this type assertion to reduce betterer results, and just do:
`const dashGridItem = sourcePanel.parent instanceof LibraryVizPanel ? sourcePanel.parent.parent : sourcePanel.parent;`
But it's up to you.

**Review by mdvictor — APPROVED** [review]
Tested and LGTM!
