### PR TITLE
TrendPanel: Add new trend panel (Alpha)

### LINKED ISSUE #7158: [Feat]: Graph Panel + support for non time series data
Graph panel should support json doc and table data formats.

### LINKED ISSUE #64275: All option of XY chart's tooltip does not work
**What happened**: Tool tip option of ALL does not work for XY chart.

**What you expected to happen**: When the all option is enabled the tool tip most show values of all the series at that point of hover.

**How to reproduce it (as minimally and precisely as possible)**: Create XY chart panel, define 2-3 series with respective dummy values, and y axis values is in the range [10,20,30,50,100]

**Anything else we need to know?**: NA

**Environment**: Azure Managed Grafana
- Grafana version: 9.3.6
- Data source type & version: Postgres
- OS Grafana is installed on: NA
- User OS & Browser: Ubuntu and Firefox 
- Grafana plugins:XY chart plugin
- Others:

### LINKED ISSUE #65533: XY Chart: Fill below two graphs
In the `XY Chart` there is currently no possibility to fill between two graphs, as in the `time series` panel.
This would be a nice feature.
Example `time series` panel:
image

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes https://github.com/grafana/grafana/issues/7158
Fixes https://github.com/grafana/support-escalations/issues/5208
Fixes https://github.com/grafana/grafana/issues/64275
Fixes https://github.com/grafana/grafana/issues/65533

Replaces https://github.com/grafana/grafana/pull/65094

<details><summary>trend.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 632,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 5,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "cycle_nr_load_A"
            },
            "properties": [
              {
                "id": "custom.axisLabel",
                "value": "Cycle #"
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 17,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "multi",
          "sort": "none"
        }
      },
      "targets": [
        {
          "csvContent": "cycle_nr_load_A,3_2203-1477_2204-1294,1_6855931-2_6855923-2\n1500,688.445558250502,529.032942915503\n1501,703.808873742938,519.68497248597\n1502,704.048421479454,534.802685321835\n1503,690.439488991208,524.103346049224\n1504,697.598673908778,522.363831150299\n1505,706.996228066005,547.222363375532\n1506,693.478570132414,505.443601681971\n1507,686.103279274132,526.146032914292\n1508,694.605536078078,525.385321251288\n1509,693.810886070643,475.994090571656\n1510,692.37696562393,474.777280832175\n1511,706.24207330026,497.036925110718\n1512,685.720040417448,495.748584313632\n1513,681.421661165352,492.551624866796\n1514,703.053417334587,495.796320545381\n1515,719.950346450326,477.899904258715\n1516,688.358418693051,482.840273984121\n1517,693.47343354069,476.16989094554\n1518,710.275293974103,485.560606612767\n1519,693.335189675182,481.164515402188\n1520,698.542323081453,481.73789389685\n1521,707.326509539632,479.935670700122\n1522,701.471936482184,485.864019548042\n1523,688.293074096284,480.010751341293\n1524,678.594634536418,476.195169878779\n1525,701.56215732558,494.439908006735\n1526,750.186822018402,486.628391663626\n1527,681.561016375283,477.26424231456\n1528,697.136204099949,481.935250195408\n1529,705.403765696711,486.834582468446\n1530,699.196465137045,478.297850511161\n1531,688.491730953118,476.977380137306\n1532,715.738197122885,489.862201414027\n1533,693.935510597784,477.500370295459\n1534,690.192454351818,480.627939173857\n1535,703.71732851132,495.401198296531\n1536,674.73486795073,485.303095527361\n1537,694.657834646836,482.478199802041\n1538,698.214116550102,482.45301702704\n1539,690.381741721938,479.578812037907\n1540,677.496373992441,486.684167830325\n1541,707.327495611991,484.897140487544\n1542,692.723241330041,481.711022230034\n1543,684.988116718584,485.799072096551\n1544,694.163809419681,481.649490252478\n1545,703.820676627391,482.807370570253\n1546,679.333006022278,489.082635226379\n1547,698.757706780729,475.798823313767\n1548,705.358564066876,481.877184318454\n1549,689.118005855724,489.460543912509\n1550,704.006927436177,477.156305535235\n1551,683.035074799534,485.758311631761\n1552,689.256001488139,478.597889506171\n1553,762.597211094547,486.42089434461\n1554,761.207604986839,515.724548722501\n1555,676.315994649691,520.450717361826\n1556,697.964746388478,524.294751311091\n1557,692.964575697607,519.697503657568\n1558,688.629327685166,522.663957348116\n1559,662.570040368992,518.731015406358\n1560,732.087021514372,516.961251298657\n1561,715.775469236983,524.686031147735\n1562,687.053588983474,481.999857001883\n1563,703.589662710951,496.226253932551\n1564,707.86560153305,496.875327778826\n1565,691.800714251491,493.30989320446\n1566,677.721479399159,490.488065959364\n1567,683.965867359869,492.904385694651\n1568,679.439708343455,487.004469687019\n1569,683.146875568999,484.67512936274\n1570,713.486269244429,479.463763811568\n1571,670.713674179749,483.839581708188\n1572,692.923742145367,487.854612567987\n1573,695.124499228518,481.782701053639\n1574,732.223296174804,490.659704817311\n1575,692.378781700208,478.182688826921\n1576,705.851845583214,482.53097049731\n1577,669.33427274792,487.671942973436\n1578,696.181096249871,485.288961134264\n1579,689.133989861071,483.732820623884\n1580,676.189710903743,480.891528614965\n1581,698.837620988993,487.416917963278\n1582,709.672641768483,484.431396888923\n1583,686.075992313177,478.551998073773\n1584,735.203361124723,478.294998968054\n1585,702.391796616733,477.139176731004\n1586,694.857970892726,481.284047644091\n1587,681.744824395232,486.420820342506\n1588,698.583421863174,476.610358092367\n1589,689.719060653664,491.82385647644\n1590,747.728951796717,475.481533235865\n1591,682.980893815009,487.115193341616\n1592,686.350852121788,478.68251034003\n1593,735.843166926751,487.546978402706\n1594,706.360515963843,486.798293870265\n1595,705.299457703205,528.556376263793\n1596,697.425528785382,534.031302072245\n1597,695.145923783801,526.883640518501\n1598,708.35970473126,527.76661018213\n1599,687.902838580769,519.563687761237\n1600,681.897735311676,525.314075199002\n1601,683.919908242489,484.194138472535\n1602,698.190844145733,497.004723176672\n1603,709.872674644509,498.040639624042\n1604,677.148080356449,491.262612701948\n1605,687.112594746583,490.24661039433\n1606,692.657853464782,483.834930145561\n1607,703.313373230111,482.23301770302\n1608,689.916284694559,490.237817967731\n1609,708.932852000409,483.898621886607\n1610,689.025045833116,490.482103746803\n1611,692.80209909,474.837714818519\n1612,699.044484982834,489.925657772358\n1613,689.014908321868,481.262090316112\n1614,683.85068276243,489.393283041303\n1615,701.898399076464,478.118678132818\n1616,700.841272209355,480.058672638729\n1617,696.86252264516,480.525728420354\n1618,684.120006951722,490.958475203808\n1619,711.002083679708,478.358299419007\n1620,713.231345436045,479.275282367422\n1621,688.635152219246,483.526498993107\n1622,747.169886160391,484.103280561831\n1623,690.878754670015,479.4168882526\n1624,700.846380339217,482.238646231144\n1625,686.933117568865,534.485415985288\n1626,689.016618940392,529.301227976156\n1627,700.336855599974,520.260090286044\n1628,753.300504764992,522.90058127947\n1629,688.156881215622,524.651010644173\n1630,676.845284195095,534.07364894669\n1631,684.73167679717,534.265484828537\n1632,702.132340505078,491.334513771914\n1633,701.985704555438,487.955408879679\n1634,690.966826923988,477.846584952464\n1635,682.808161503095,480.572144838907\n1636,678.169385306994,478.776444045424\n1637,706.747592013025,483.693668108785\n1638,712.104492123562,490.502743057297\n1639,678.257432707521,483.881342109826\n1640,692.877028184536,476.322200953768\n1641,684.935155154358,482.086658706006\n1642,675.00704071588,481.392127149715\n1643,727.139165124338,487.847886144755\n1644,678.86405096542,482.590816796349\n1645,750.304087507104,476.03115127401\n1646,695.728900683247,478.087004327575\n1647,689.261235709494,475.399417838155\n1648,684.875530000536,476.971119074062\n1649,693.544077493493,484.594893456226\n1650,673.155307179182,491.552266514739\n1651,742.006272323162,526.035512257644\n1652,704.043745241998,532.364919026291\n1653,708.780669492318,523.703420524228\n1654,692.247724070371,485.490054972457\n1655,681.629763873865,478.306246984326\n1656,684.427924792927,478.797276334879\n1657,704.394993556093,481.829077928235\n1658,686.451639988808,476.265084664489\n1659,685.303377561656,477.912598761946\n1660,670.638340664702,476.171342305871\n1661,694.207048533179,483.353169503685\n1662,693.765299647009,487.059669900156\n1663,687.33038984456,487.904331395101\n1664,694.951424472177,485.576619576073\n1665,697.642427267804,481.030489862796\n1666,697.721586131626,487.9282408\n1667,692.858466461716,475.109669045064\n1668,725.426782873201,483.9012343296\n1669,690.725077894008,476.91129579356\n1670,696.388712607954,485.576646670347\n1671,675.4748568165,485.368366645953\n1672,686.484051119967,509.172604675344\n1673,720.341303751759,515.423290591211\n1674,663.064012722946,482.254295797977\n1675,684.566217341446,493.38796358774\n1676,691.645745382773,496.709858566366\n1677,701.985506202907,492.885176671148\n1678,701.78445679487,479.74464738543\n1679,688.710021891426,477.185753551256\n1680,692.19366673034,482.04032201451\n1681,698.72755862532,479.755476410018\n1682,699.739109812238,479.939969344825\n1683,685.75898928842,475.838748418016\n1684,703.296386912798,480.781972300156\n1685,697.034062019958,477.719541891057\n1686,699.488666673272,476.944045769494\n1687,682.592743810176,480.890270533378\n1688,711.131539054105,476.46207343001\n1689,695.673659330356,484.657519254266\n1690,696.568741330715,491.386944135477\n1691,693.499509630762,516.286091098723\n1692,688.214015275013,520.545380256946\n1693,705.076332976122,541.148677937105\n1694,707.805597113079,526.459728578267\n1695,697.151972358136,493.496529111841\n1696,690.678575157119,485.122412196583\n1697,695.28421744517,478.193465326337\n1698,715.096208185593,491.72231304918\n1699,765.911209367105,484.715644427483\n1700,709.443129653429,476.631756673932\n1701,717.535329018983,480.560429518187\n1702,712.478626578175,477.177216662033\n1703,682.156688463134,484.673115605416\n1704,707.124385615236,478.135121882421\n1705,702.217168884485,484.264798123232\n1706,704.312869484515,485.048993522184\n1707,719.894450409414,475.972764285137\n1708,696.664165564347,528.073595268825\n1709,694.040853994776,519.946173957536\n1710,703.781885069492,521.719702099135\n1711,687.694758815325,525.604674124297\n1712,687.194585665897,520.925830172763\n1713,711.024687309974,494.620720156484\n1714,704.964188720527,484.500457842292\n1715,709.489388809459,478.243836158452\n1716,720.626194282567,487.156869881951\n1717,697.589268744109,484.596900877142\n1718,691.639385424698,481.703516236001\n1719,702.023547659726,490.964543432339\n1720,704.726028891229,476.494539331095\n1721,701.779967286445,477.015615542703\n1722,705.763454871551,487.973895721258\n1723,708.446973407429,482.8170656029\n1724,701.312691038738,488.626882605526\n1725,760.128112878308,522.704305041224\n1726,707.757272703966,527.787163552276\n1727,689.255081891969,526.626130108906\n1728,700.163443760866,518.474745651688\n1729,708.457366871371,521.982746653247\n1730,757.317631170948,533.360753704361\n1731,694.800081533293,492.911512481904\n1732,677.096858087982,483.188364966084\n1733,693.704772188535,484.450929217523\n1734,694.470390984791,476.840874348825\n1735,689.401409958811,486.294458358313\n1736,720.656395603318,481.225256613402\n1737,692.603217134224,477.225084948096\n1738,702.12714694188,475.664847342695\n1739,696.908390437699,486.141442905548\n1740,706.418122199196,482.468074087474\n1741,706.196609652657,476.291064825365\n1742,757.550616584489,484.226977783047\n1743,697.123254132495,479.228564897841\n1744,691.686909334095,514.184231535111\n1745,701.913929098521,515.324075249329\n1746,706.996814404008,522.533518473888\n1747,706.987819251121,526.233001497013\n1748,711.491877519612,507.101868980544\n1749,702.552418953146,491.851483546659\n1750,693.533259992497,478.965094332044\n1751,686.634027026701,479.164976668029\n1752,689.535115278714,477.244105033695\n1753,698.47467201,478.206973356891\n1754,681.605476954745,476.653567647109\n1755,698.900240363544,479.27889114201\n1756,710.939754948575,483.301222576064\n1757,709.062238712113,487.563092120759\n1758,673.899066294757,478.536706478736\n1759,692.970756352109,476.764550440348\n1760,695.113058866751,480.24260164895\n1761,688.176637989417,494.202965645029\n1762,696.830485478265,520.49714654558\n1763,691.697011678163,521.359795563726\n1764,711.947263994621,521.383678471876\n1765,697.512058401616,531.277257126239\n1766,692.195859247398,531.229388840176\n1767,695.815266975364,476.027642115892\n1768,710.259858656922,485.343762064051\n1769,698.053403590426,481.889364769389\n1770,704.833960850929,476.477605912253\n1771,697.658271692288,476.741028621725\n1772,710.930335842426,487.368751719876\n1773,695.867960886015,474.825285226256\n1774,697.980772891536,478.10554709007\n1775,709.638575554472,484.218757974167\n1776,718.43892812628,483.834930145561\n1777,698.8856991183,479.861598220141\n1778,698.312574404608,475.208394689341\n1779,677.224485536724,486.318276909486\n1780,682.749298873706,516.317620402415\n1781,707.862006571373,520.880529752564\n1782,694.806369478296,522.368360927243\n1783,698.043783091773,521.051149289131\n1784,675.411477747817,496.19245189223\n1785,705.887028006768,488.121031622669\n1786,704.016200019976,484.053799579502\n1787,693.803722297212,487.863401843042\n1788,695.961530081783,484.143681676971\n1789,720.293295782373,474.801086359946\n1790,709.915813064746,482.655004172161\n1791,702.237145764237,484.67652731647\n1792,706.165231445227,482.273684288974\n1793,718.290920524532,478.824161920813\n1794,703.830351997116,486.030755419749\n1795,717.086764382236,477.959360424494\n1796,693.449846265368,488.235860418626\n1797,736.60990437663,540.281938942737\n1798,708.319338196267,517.95889618481\n1799,707.524240380725,485.726855488681\n1800,702.442377993286,491.511828732812\n1801,706.593242023557,473.656448813901\n1802,685.022735750805,471.659997537411\n1803,712.204102265582,481.747768193541\n1804,726.889494048312,475.152877424031\n1805,697.318546515116,484.462895731861\n1806,714.309600201108,477.04284728876\n1807,744.32674886873,474.876692093668\n1808,685.34380631299,475.305107469597\n1809,698.886473034989,487.979525844737\n1810,693.596537983513,475.733483613735\n1811,712.258984954576,475.790234394382\n1812,693.85907810141,486.588843038523\n1813,709.907287774915,532.243218833649\n1814,711.279552523073,520.440645294472\n1815,705.631219236215,518.474382871478\n1816,676.085225351891,525.228716234253\n1817,679.34879399073,495.662247029959\n1818,708.324346121168,489.748972800486\n1819,682.427371576745,480.10105324702\n1820,688.80149997985,475.935398680338\n1821,690.923347773575,476.79722105185\n1822,745.352166757955,478.922395876209\n1823,709.311418719966,484.67364407969\n1824,697.599355028989,483.182697391009\n1825,712.219732269505,478.371190237178\n1826,708.768330771857,480.056452981223\n1827,727.956641598152,485.791431989366\n1828,705.614781133364,484.091275525402\n1829,693.459088286892,481.457610884156\n1830,726.987666553781,484.091275525402\n1831,775.486627137006,514.278130701331\n1832,718.047797224201,521.192025144882\n1833,711.659854075303,522.045447319981\n1834,694.152441107507,491.868446548006\n1835,739.368790196184,492.408601205991\n1836,702.73116921139,482.493833409793\n1837,701.168621128861,477.33972551514\n1838,694.668369028142,479.117010291216\n1839,700.283171526837,483.140346125408\n1840,703.787017315336,478.001464011957\n1841,716.904023650618,475.556643346684\n1842,681.337712152283,482.874776209538\n1843,688.411643012872,485.68841655294\n1844,707.036386086281,481.516098387992\n1845,697.7299395763,480.520952149304\n1846,711.999880399052,480.087796435746\n1847,692.295076856726,475.024564121279\n1848,681.459537292491,521.132148899972\n1849,695.142330826325,524.740774372529\n1850,698.61873808471,518.247452354211\n1851,758.308995763239,522.151274547867\n1852,691.031503478203,523.809397892129\n1853,698.640354559392,492.279982617681\n1854,705.584714599856,488.674370500105\n1855,681.145443999681,483.164332732302\n1856,695.787827247829,478.549796660821\n1857,691.625144820515,485.798756008526\n1858,717.827102749805,475.692166877558\n1859,713.642091927267,484.905576386424\n1860,697.431791196187,520.389644467474\n1861,718.574481973169,523.014975152095\n1862,702.743180487631,526.894051354052\n1863,697.516661920558,516.518020760342\n1864,764.715491102667,527.924466241443\n1865,682.515744725832,530.463005809415\n1866,712.470914393515,534.685130600376\n1867,705.822847270612,526.30596968441\n1868,705.878935050698,523.74437943271\n1869,713.770506841495,524.470986288845\n1870,725.116532987108,517.652635065308\n1871,702.354275288194,526.643347905792\n1872,682.940419640105,517.659207880265\n1873,710.30170049936,524.42318401629\n1874,686.021885552947,539.567500302092\n1875,687.793873534041,526.970213969805\n1876,721.001286860172,515.729022237904\n1877,714.375690536246,531.884134350264\n1878,696.392406082034,523.52278970063\n1879,708.870335500161,536.134229543699\n1880,723.125294752696,513.148075641961\n1881,698.866549394062,528.394010299753\n1882,688.334956599199,519.873411230713\n1883,709.147493304407,512.613540289059\n1884,700.76383358931,532.378914340942\n1885,721.301829655188,513.004421738396\n1886,709.02120524677,518.680197767755\n1887,702.797884036144,516.179713112911\n1888,679.701309026904,517.993483613334\n1889,680.210376782036,506.792114992235\n1890,701.980231448765,527.757236012631\n1891,698.508214131212,523.79547378893\n1892,752.02790951154,513.950710717068\n1893,748.602430907514,518.340158687847\n1894,701.461102473788,520.904938392028\n1895,703.188143091641,510.119345933651\n1896,694.084007239904,530.389098721616\n1897,698.562190278109,512.067611968944\n1898,696.349173206196,517.243315414485\n1899,708.018917201828,516.410360508244\n1900,702.204714445004,525.912772092416\n1901,688.852143720169,514.106078953099\n1902,710.54681394799,511.650121668075\n1903,705.52820654462,529.599224653793\n1904,700.866854448094,515.320394785517\n1905,689.436237668719,522.298525096656\n1906,718.198170273395,513.009978436789\n1907,692.335820268724,526.169813390281\n1908,689.196028672563,522.685727108984\n1909,707.915988274848,516.812255613042\n1910,711.986008990352,508.385950850535\n1911,708.162843058505,507.676186968993\n1912,688.83606763626,522.116389226427\n1913,708.302485628371,534.613303898006\n1914,715.514603987453,519.26384122461\n1915,700.699945828235,525.890326000099\n1916,713.778835079156,525.661733253023\n1917,708.540126414217,519.350795181014\n1918,698.98908727615,524.962889988581\n1919,706.74427222263,521.000260333012\n1920,698.780930451307,523.110711724221\n1921,738.509101569928,507.615953516167\n1922,690.282178592842,496.360088984201\n1923,694.296687126528,516.381195811599\n1924,702.585624837298,527.088244304885\n1925,681.800359568439,535.499944617457\n1926,686.305472319087,519.636872204297\n1927,704.961865312671,532.50711939124\n1928,709.217860716564,529.104646013154\n1929,693.179770714245,526.476120169817\n1930,693.69283671137,520.357839291421\n1931,708.770610775336,514.775575175767\n1932,711.382428701014,516.629334847852\n1933,713.496597160833,515.195321838926\n1934,744.886751228396,513.966863516764\n1935,705.081290171432,539.554056202352\n1936,695.472234479261,523.391011811768\n1937,699.251304442903,518.840703039527\n1938,706.597618010112,513.382132803901\n1939,698.714549408456,511.149642578571\n1940,702.404093370986,537.138986499905\n1941,707.602673140076,507.748954969489\n1942,702.920205618776,513.574654166217\n1943,698.819364997907,511.36719227457\n1944,703.709215610929,515.101935655496\n1945,718.347331174615,513.573604095495\n1946,705.04923878465,522.367253852352\n1947,708.193852704161,524.481443340563\n1948,686.428883300231,527.493814447876\n1949,704.783730979424,532.816062206178\n1950,701.74288612213,495.987940880763\n1951,713.278943333708,529.975789026881\n1952,694.742396420192,524.529229222966\n1953,716.749795168061,519.708385735047\n1954,703.129862546942,512.569822229581\n1955,697.683259146257,515.269555068416\n1956,709.746082981359,527.051449998071\n1957,708.844172454752,524.505703907746\n1958,710.229902660963,508.442339314861\n1959,700.241114495743,533.069901630084\n1960,698.869835805213,499.73331806356\n1961,700.925421376579,522.20795051906\n1962,692.904531576162,522.236116739866\n1963,713.035460982839,525.779305904982\n1964,719.34487448161,523.265567435885\n1965,693.188413733634,519.898890522861\n1966,697.958415562441,513.956719770676\n1967,712.021543847275,531.86532029661\n1968,689.7138559424,516.370694292996\n1969,682.270909690202,520.883561242535\n1970,697.078481277169,524.642376264402\n1971,699.705513568666,511.237195864685\n1972,684.749679331764,521.362489330041\n1973,690.03587987114,530.49367452246\n1974,677.162159947415,520.222324038919\n1975,700.333398355749,516.375912012758\n1976,701.903914082175,517.400194017482\n1977,696.624818966223,529.044344839867\n1978,703.528191018495,521.560381936411\n1979,677.492747396147,521.785289101808\n1980,693.503670358263,524.149282892817\n1981,697.493630530702,537.19352938848\n1982,691.170785493737,522.200674789897\n1983,694.957636521191,515.619418178479\n1984,745.945791819692,521.254517826449\n1985,692.641511400841,512.271889231561\n1986,705.782912625454,531.380560455387\n1987,689.153150854735,526.421843746248\n1988,695.781061920727,510.304361042634\n1989,698.511716927709,534.574653775657\n1990,709.035238776051,529.767207393129\n1991,706.180060827735,525.451260417086\n1992,690.377118415571,521.686462395076\n1993,707.78961847303,519.406874488872\n1994,697.903335173193,519.779344042152\n1995,718.233024576032,531.375967020425\n1996,687.494958650336,527.80550308182\n1997,700.320397841069,518.607735361691\n1998,712.386979612198,519.105540676993\n1999,713.264221935715,542.437385086079\n2000,704.550011239287,531.907790207248\n2001,705.003156939108,527.060303842704\n2002,693.593137826089,513.976683337338\n2003,712.295249473562,530.806831871641\n2004,789.209155535657,529.035237289083\n2005,698.701634971785,502.700724549123\n2006,702.116912359719,516.435033731459\n2007,710.067874949069,513.065645079842\n2008,688.904958620524,526.033263285385\n2009,703.227726547311,521.397393409645\n2010,700.682969095924,521.289958931433\n2011,708.850306505577,519.122054833022\n2012,695.413833581274,530.913861911251\n2013,700.076678977894,508.281670074265\n2014,696.67910928443,537.001947608842\n2015,705.457597178566,531.507647600327\n2016,705.554691303876,510.93231651298\n2017,708.019832572529,536.83336244044\n2018,708.640912933345,530.83599427752\n2019,708.064929426703,521.419056283873\n2020,785.239086988648,520.775803886556\n2021,711.162570975565,530.979695325694\n2022,705.238312746853,528.933850095814\n2023,688.741474970869,532.46567095689\n2024,709.17867872732,524.411284071757\n2025,685.998487291637,505.928277810824\n2026,713.160078955378,511.663275957253\n2027,702.721275702864,525.313977108252\n2028,701.567165184559,526.0542345806\n2029,703.10674197677,512.315826286013\n2030,712.629644808725,517.157252786838\n2031,700.614413202974,507.316533276872\n2032,705.884297844262,526.234192010505\n2033,705.242975564475,522.375832979749\n2034,704.316935472028,518.477496496104\n2035,695.171690894122,519.926183688854\n2036,696.945576413003,522.71203804405\n2037,708.937106549416,534.534262393534\n2038,700.111813123895,508.751936053113\n2039,712.366143596049,528.386772216397\n2040,690.480809144257,519.985710160483\n2041,713.927942526539,511.837118434379\n2042,709.579250639596,505.942997497922\n2043,714.215551597993,515.963247094794\n2044,695.508567060096,511.660725901907\n2045,690.508703931141,525.408103557534\n2046,708.483618123922,502.738763383915\n2047,688.50525007308,517.783880383478\n2048,700.67626393348,517.954704555979\n2049,694.70430771516,523.034305815705\n2050,705.486098657579,526.964288856333\n2051,715.133005284304,519.635680922495\n2052,680.602213030391,515.169217593438\n2053,691.154039163412,525.568065190408\n2054,707.378986554132,507.796236563987\n2055,695.291471208574,515.630225928739\n2056,705.520658172326,520.497814932249\n2057,721.026448896963,513.059018310821\n2058,700.858370045866,518.65244785073\n2059,704.452770478683,520.120394042009\n2060,707.703961599043,529.940254406507\n2061,690.021447497288,524.614462687006\n2062,665.822221311834,511.91790716381\n2063,703.497869052735,524.521561355236\n2064,699.810365783986,523.614914972093\n2065,703.043578130639,516.467955916957\n2066,703.54640673,520.557904643444\n2067,722.579566581862,527.563313622995\n2068,695.362539506729,519.848018522908\n2069,700.748159622824,512.490992914703\n2070,695.597317730998,513.297881166947\n2071,,526.458559264867\n2072,718.8204212385,487.213322661079\n2073,703.964158351948,519.549229887319\n2074,711.696491773897,523.855624060722\n2075,731.103801001941,520.7192856102\n2076,715.563246832607,520.931178098255\n2077,693.530252806957,511.28864176124\n2078,704.038532543179,524.478933058245\n2079,710.680602757705,516.391980217002\n2080,709.966271377576,523.894645099329\n2081,697.069870188783,518.660661579463\n2082,699.254892368133,521.839335761678\n2083,697.688184932665,529.558700372819\n2084,724.900490789897,513.068358347718\n2085,693.219748725857,515.205400606609\n2086,692.371903051268,520.384420822282\n2087,705.442465573604,524.352865522754\n2088,692.636623922034,525.605097030268\n2089,673.745342377758,524.010732822948\n2090,702.670127454925,513.96223324995\n2091,685.156742994187,525.641799087182\n2092,695.742430641017,525.249257087887\n2093,687.889927065593,523.732164580886\n2094,711.279543431865,525.989778255274\n2095,705.223891497711,518.149608549051\n2096,681.526545781778,523.547113497631\n2097,703.648010099935,514.715818793872\n2098,686.31000880591,526.045542252483\n2099,710.070449109079,522.606966511577\n2100,702.103238561118,512.413961388419\n2101,687.350620870376,514.052837545883\n2102,711.673766542997,521.253599518983\n2103,730.995973309512,522.472034936047\n2104,701.551905003645,513.105796375241\n2105,707.455586755099,524.292902534685\n2106,690.456111885307,523.097570021375\n2107,699.409551946102,512.891587606264\n2108,703.109215887346,514.095939600403\n2109,707.076968687047,526.055951378899\n2110,691.135931559521,513.044424685772\n2111,705.715381115213,511.51840648873\n2112,696.107575878,515.676761525979\n2113,706.499393049925,538.402485565843\n2114,718.372640000626,525.255572534073\n2115,687.91332864721,520.298320563682\n2116,725.481099111592,512.999481411385\n2117,719.700440912135,522.744614207791\n2118,714.779730684006,526.412013404556\n2119,714.928950838862,520.489486582862\n2120,702.924656895162,513.687338297651\n2121,715.220458609785,514.057095471632\n2122,711.268357637807,524.325816646644\n2123,746.999255265362,508.469117114787\n2124,718.981772649113,522.945449539818\n2125,699.596180544629,523.837755719972\n2126,682.781604640478,520.375159876844\n2127,719.319185972283,530.539818208958\n2128,691.146990328385,522.633997348682\n2129,711.288656355619,520.285315811335\n2130,680.352873246699,520.082052702213\n2131,709.489803709114,518.509239155484\n2132,690.898545870279,528.381348167634\n2133,695.525279654445,521.371500856073\n2134,705.726455144204,526.414252835666\n2135,705.390806139427,517.872837705874\n2136,694.032495664203,515.915423925085\n2137,689.178629924636,523.873115617627\n2138,691.286364403946,512.374471275219\n2139,680.654847143502,523.825542487288\n2140,758.615927358295,507.540320291346\n2141,724.358703492826,523.49194505946\n2142,678.975676717259,511.769828157854\n2143,706.875443619961,518.274221709712\n2144,712.035451998163,513.813679359\n2145,700.852888617733,504.421677809209\n2146,706.365351389458,509.919587343805\n2147,777.227128439447,521.40644950178\n2148,729.654810118074,517.667713624286\n2149,708.717845001373,513.666405316891\n2150,707.812859115454,522.130822804745\n2151,712.088022405521,519.729315344181\n2152,710.876685499831,522.728898111047\n2153,709.76776728147,517.321197728384\n2154,703.984030579008,521.665833503329\n2155,693.048335567345,522.721094894039\n2156,693.705218098572,519.937164558371\n2157,707.808094384081,510.864474892774\n2158,728.383215890772,526.827528994107\n2159,705.734810985109,527.730467200506\n2160,706.294264072712,519.38020339363\n2161,696.293439997053,512.445977066937\n2162,719.105040064925,518.024999424706\n2163,707.775116312642,520.719343121907\n2164,716.506591690851,521.752769000149\n2165,701.716669138017,517.045852556458\n2166,708.836976278627,514.784202015591\n2167,710.511098035427,529.70287407142\n2168,717.117808954786,527.230881488802\n2169,715.359046378473,518.030862086626\n2170,710.484384671556,514.219282246197\n2171,723.591847464814,518.334589459958\n2172,709.025882038423,510.623356593872\n2173,721.299692918993,510.683819629492\n2174,708.43553230087,526.974985812147\n2175,716.832716589187,518.090910236711\n2176,714.708968075585,516.293893421583\n2177,707.310194034862,513.212764991916\n2178,709.775357424308,525.905325755808\n2179,721.233186616097,509.331753591605\n2180,694.849629463402,525.698410091596\n2181,719.999065353072,521.014389692051\n2182,712.611973901487,510.97013929996\n2183,699.043735133906,522.924512532518\n2184,721.697752354886,516.382313647082\n2185,718.885113789629,512.50273921542\n2186,712.436059825055,515.717915528483\n2187,689.251285208658,521.675906628079\n2188,738.781039518853,515.240699791031\n2189,701.812284770606,526.50400655177\n2190,734.291156012014,517.819452454166\n2191,714.854149671118,512.741158820019\n2192,734.022398273061,521.42257024858\n2193,706.968934384818,522.325597629028\n2194,724.681237418054,519.535201687993\n2195,727.582764169933,520.012368565434\n2196,732.582028521195,517.268634590146\n2197,707.758249186057,524.176327613542\n2198,737.594281141544,523.671180650812\n2199,716.89566708988,517.387950739512\n2200,706.094356329698,520.540343152295\n2201,712.596417789237,517.424000445886\n2202,711.323857789128,509.300113583654\n2203,724.109168855423,515.656300057668\n2204,723.036110693302,511.909460671304\n2205,683.026566559844,521.252973130771\n2206,707.541970969429,521.375363861214\n2207,711.358381997492,511.375677399772\n2208,774.528697060742,509.706103677737\n2209,711.481638303836,514.740032390013\n2210,727.420628905223,511.706048436443\n2211,712.263238796772,512.820057600186\n2212,732.826536618969,521.780083808501\n2213,700.285728436896,513.85597459627\n2214,714.661475530404,515.127497436572\n2215,693.499769273058,515.495889144948\n2216,772.170454309073,524.69762407941\n2217,728.008094249584,530.522294994538\n2218,705.908505561687,521.957985226236\n2219,720.866806515162,517.835979442458\n2220,698.76667316982,509.518202065104\n2221,688.198919356435,512.151124177623\n2222,689.39272198163,525.240149009769\n2223,727.081421961012,520.969992819098\n2224,712.141969662726,516.154469661441\n2225,702.021841660124,523.212915765791\n2226,728.460890615622,508.042080266234\n2227,715.178929153453,521.490769130292\n2228,728.30454861866,509.977041627038\n2229,724.993767512607,523.019295617786\n2230,785.309346887547,509.562811484296\n2231,700.719198505184,518.945546109268\n2232,717.670822536931,521.424145683069\n2233,697.623311856612,525.432849451918\n2234,706.703167238719,520.677081132241\n2235,720.414896225918,515.380210110108\n2236,711.112368623353,520.241727256801\n2237,781.24396869873,522.746127838586\n2238,697.335306978262,509.995113895962\n2239,716.929209043773,515.489442274991\n2240,696.454511913854,516.467247024527\n2241,761.071374386129,531.805234285571\n2242,777.085447698229,511.806976416152\n2243,705.292767214965,523.533289067405\n2244,771.264210447505,512.081561750674\n2245,697.855286414528,523.308250641505\n2246,722.683257902487,509.945722119885\n2247,713.592416532956,516.366407175101\n2248,713.056067618633,526.702572604819\n2249,701.876036560501,522.061962032756\n2250,725.094936883669,508.837277719261\n2251,705.385700144404,523.922682838357\n2252,715.59791904604,518.27645930456\n2253,718.466756172856,509.3431482802\n2254,699.072347908251,523.757637608503\n2255,701.275282615113,518.681154022522\n2256,714.773133866477,509.051844082071\n2257,715.47111103199,515.424210717208\n2258,715.840766235116,514.637510023185\n2259,690.300519464507,514.805138641769\n2260,697.939716782632,500.5024332607\n2261,694.187369406418,526.702917109224\n2262,723.549339747611,515.05240879665\n2263,701.42567343192,517.117962004472\n2264,717.209522428177,520.769899821814\n2265,716.139651729321,518.395931780968\n2266,716.047230038464,519.0681615879\n2267,708.595981028721,510.930995906144\n2268,712.427237978743,515.216602846776\n2269,728.893820784962,523.954117578923\n2270,708.906898519558,510.930947029338\n2271,723.185449155101,507.40136302703\n2272,715.624611393612,517.254036710508\n2273,709.893373597434,512.018667565587\n2274,722.932147887843,513.425885813517\n2275,724.844311694953,517.0262692236\n2276,706.551237530178,523.13508137414\n2277,704.25829753019,515.284580288543\n2278,723.09634796532,522.029770416491\n2279,705.943369391305,516.388934826572\n2280,696.16288722777,517.990008449304\n2281,721.464309663224,510.554737219547\n2282,709.675171378656,523.253689064128\n2283,716.23889497035,514.880756268577\n2284,726.212624260071,518.452606277129\n2285,726.273358146802,523.579793045322\n2286,693.983218521104,520.612237558349\n2287,702.49948899745,514.401818600427\n2288,723.62712873447,509.96771320129\n2289,718.588419177604,528.084636275211\n2290,716.929005760853,523.891896855458\n2291,717.313415539466,515.212083882527\n2292,705.424719620652,508.738777967862\n2293,719.891546234672,522.936780868461\n2294,723.806705907408,517.889010162833\n2295,717.032674891258,520.537222814611\n2296,712.707318215546,509.085315476068\n2297,709.233012199633,530.050334226288\n2298,719.241367676758,518.041827935042\n2299,727.571702635507,497.341264712998\n2300,722.672377822785,517.863840909004\n2301,687.917109348204,533.292752961209\n2302,711.403304212909,508.636602709787\n2303,697.378713791494,522.611671858671\n2304,681.250971349154,520.895031174973\n2305,711.84274930442,514.462006834837\n2306,721.727358114332,512.984729082161\n2307,716.769169074939,518.434253234573\n2308,709.114481935486,515.309137871473\n2309,707.614443947882,516.484292903119\n2310,731.19994967586,512.50278804188\n2311,731.355160445793,516.31668013722\n2312,713.10201467229,512.912394581374\n2313,708.640788031444,514.199375488099\n2314,788.990313221802,528.20913166435\n2315,707.669508357874,517.832420894359\n2316,685.201089201643,542.058849752506\n2317,712.147553847678,522.754733386723\n2318,683.807674179373,513.012327635998\n2319,699.008098381057,531.576112277511\n2320,710.561494138993,525.598323404369\n2321,709.508594016734,513.194121890235\n2322,698.831744580155,514.262842192794\n2323,743.194893938681,521.333222167125\n2324,729.740813346165,520.787750694126\n2325,701.53174252116,519.393949529765\n2326,709.419326611599,518.024950648487\n2327,706.149609267441,517.381933760168\n2328,704.423549495487,521.767014339503\n2329,686.400953621635,508.590077806063\n2330,697.854543641088,516.850103778575\n2331,710.106760969388,514.242486320545\n2332,722.471155992933,513.004907098488\n2333,691.533210564659,507.396299878937\n2334,708.224982902006,507.159200599087\n2335,689.559436199539,518.469624384576\n2336,702.814987787765,515.120819243544\n2337,715.681194815712,505.154736357255\n2338,691.179625974585,513.338941588527\n2339,725.668543409572,517.687047290587\n2340,737.3414084289,516.726704927013\n2341,722.080240271751,530.548262555689\n2342,700.340104306403,520.039339484335\n2343,734.900512412873,515.901716838983\n2344,713.750261711075,518.181750027217\n2345,722.38228257373,538.373070307241\n2346,695.709929976715,502.503050552673\n2347,701.294950349627,534.196361387076\n2348,703.823471795809,505.531428360745\n2349,730.573014168703,519.458609951444\n2350,726.217078530548,519.359860689116\n2351,735.257355234674,513.241776515279\n2352,704.713373376585,510.149658113824\n2353,713.457418017281,509.836543811953\n2354,723.045479913567,518.581743932419\n2355,716.926615098462,515.507551713119\n2356,699.551704950512,508.055364173585\n2357,728.349693214148,506.18403860515\n2358,725.536074379282,505.589394368287\n2359,699.572790201013,505.463898431017\n2360,712.602674836894,507.310535767545\n2361,672.697586211871,527.926078269431\n2362,718.669430115052,507.289840851734\n2363,728.220270852067,508.388508137703\n2364,695.599137174304,508.49111016763\n2365,713.560469266017,518.198839627327\n2366,734.067886002001,503.537489678418\n2367,717.250320024166,523.804267813174\n2368,720.277453969291,514.218119432982\n2369,721.264424649854,531.396732884982\n2370,724.958320688419,522.39274748678\n2371,717.928490394233,510.024742033231\n2372,722.60098832314,518.19867642877\n2373,732.194704280874,511.65875349487\n2374,722.046355601304,516.615016375085\n2375,725.807070335203,507.151977365932\n2376,729.896083271205,519.855633629968\n2377,715.770124058883,512.185139175091\n2378,719.550994454265,521.35013770126\n2379,735.106515161742,526.728079060788\n2380,730.504795392099,516.615786134111\n2381,744.024441624978,498.572904113408\n2382,726.912509778364,514.70309007214\n2383,728.734129315873,520.752143945932\n2384,724.695619596766,508.49111016763\n2385,731.339163903826,523.419643152446\n2386,729.89728030382,511.539845717374\n2387,710.638280702819,515.630198638901\n2388,736.961300864589,507.556175567119\n2389,712.574783798862,511.907258913898\n2390,726.45888198996,507.164169815838\n2391,696.077371484061,501.950364527875\n2392,689.935049424425,517.470985556949\n2393,737.145499842787,522.656589000185\n2394,697.282186151477,511.908590114768\n2395,706.452729390815,511.693254445254\n2396,757.891548905235,512.293543270491\n2397,711.51675225828,511.317782726469\n2398,718.357012708194,525.688739693471\n2399,728.698784938513,513.312253686757\n2400,716.283784530201,492.502632631296\n2401,712.809941210258,509.325863505015\n2402,747.464606369163,503.189026077559\n2403,724.163451491586,500.698930609375\n2404,733.378338721112,505.537505937408\n2405,716.514334864887,499.196271533666\n2406,743.997803745013,521.614554328076\n2407,741.54906484051,507.677938416719\n2408,710.671574630233,508.628949111097\n2409,755.250819470585,509.167756917423\n2410,731.646154610115,503.265749310258\n2411,759.547701057291,515.285888616127\n2412,716.542492421245,495.321200460297\n2413,751.112552473163,504.918986707819\n2414,712.03927667744,503.671846837845\n2415,736.475370470615,512.503259206255\n2416,716.839469128119,511.351350103545\n2417,721.066893307847,496.659899638136\n2418,759.340425972614,503.590027138672\n2419,767.628062685939,506.973087087281\n2420,736.064005442404,498.867793152715\n2421,724.236299609631,508.006586536663\n2422,745.090817834564,512.204253653247\n2423,755.948303995951,498.294716436606\n2424,744.896068473982,505.436720550391\n2425,756.626143852004,511.417769989333\n2426,751.136557533491,505.730292214371\n2427,744.715512749887,506.342211582897\n2428,746.417433787205,507.480434766671\n2429,734.687538602602,516.162062274729\n2430,745.338045763996,506.985041456517\n2431,744.044363129129,509.390223010489\n2432,770.649235338458,515.891033658\n2433,760.995668874581,508.045126054135\n2434,752.251825011011,502.870288185436\n2435,758.421835938304,510.924296966438\n2436,729.588613657504,503.677928830425\n2437,756.171348612426,515.573693686734\n2438,741.956233031327,506.900019158243\n2439,754.519813236789,515.09823137049\n2440,770.28322579742,510.013381336167\n2441,769.562359191686,499.375393048314\n2442,746.139414751244,503.124895774806\n2443,738.308290736575,513.186911956935\n2444,748.062083157081,515.006309362369\n2445,724.840040025188,514.746792406219\n2446,738.872232942019,514.621022860927\n2447,711.710670753249,510.389209296391\n2448,735.039719156099,511.97370626271\n2449,729.768149809893,521.813672201523\n2450,725.065266248471,508.151781123916\n2451,716.597973421607,507.141459117574\n2452,741.697192253227,508.463820969006\n2453,783.324626011067,508.609957865801\n2454,730.465878266668,510.432685490155\n2455,729.189132990423,513.252171551528\n2456,701.288518546184,506.381510485914\n2457,705.335564793507,512.784380381811\n2458,723.67829751952,510.54184771679\n2459,688.454167298373,511.465360364\n2460,733.105474859438,501.988511967538\n2461,730.716871264344,511.401239752708\n2462,727.084041184578,515.253275059483\n2463,703.72169291465,511.871157540186\n2464,808.5265443989,503.07765775568\n2465,725.329340353793,531.739234833059\n2466,700.436498391372,507.488459708812\n2467,709.796246241833,510.376061075166\n2468,716.822965802569,499.750825954909\n2469,724.606116476705,518.662966140318\n2470,720.758212650075,514.146945796541\n2471,736.006953422607,502.545376825334\n2472,715.661664591113,499.926604694468\n2473,721.041883854735,508.525412601038\n2474,717.949096455487,504.150294207417\n2475,729.230050922899,502.133025693364\n2476,715.774403106081,516.883011504673\n2477,691.011906642865,509.996512844561\n2478,716.025308964537,514.5738326129\n2479,755.515339387886,517.290565962318\n2480,712.197554610245,14.2171226691302\n2481,722.191131283113,509.180899460766\n2482,693.381641909396,505.040350942098\n2483,715.619240428152,513.377559467843\n2484,748.399199893841,514.498781787645\n2485,706.152807776837,497.039813673086\n2486,710.542050014838,494.841005032206\n2487,721.274098260486,500.518544547417\n2488,717.208454956832,508.465762125458\n2489,721.092267071966,503.254165122318\n2490,718.708342123222,503.749848123372\n2491,714.986649896922,503.35423085728\n2492,729.353981442103,513.346102931277\n2493,744.662758986851,510.67476476159\n2494,727.744844261412,517.862362644149\n2495,711.791597987821,513.984420619682\n2496,794.752091201134,512.415072778214\n2497,731.390230013218,512.193702426596\n2498,755.5632462807,504.510539805577\n2499,709.854702151075,513.569831682288\n2500,703.328733703728,517.074487619799\n2501,716.962409705118,520.550707776602\n2502,733.980754514974,477.811034833856\n2503,742.616293666272,513.606858772649\n2504,717.640629306508,505.989689105563\n2505,714.256639711523,500.66987568729\n2506,714.040905455103,512.634443853109\n2507,751.594111603264,509.40367429723\n2508,730.972386021639,492.818426529073\n2509,794.937501460282,511.604842882228\n2510,787.89169566806,514.601883120247\n2511,765.68596042665,501.231860118403\n2512,725.877253045231,499.523474273283\n2513,701.791027521297,518.280161034872\n2514,713.667859710454,513.59098554352\n2515,712.96666928812,503.105583438162\n2516,709.963050893595,511.529909695176\n2517,795.191866306556,\n2518,705.863513138411,511.687807996626\n2519,729.852629285521,509.917835844218\n2520,716.268538725922,502.545136166855\n2521,713.780364547647,507.456858638965\n2522,721.172610892314,501.317505210883\n2523,735.075190811213,515.597295932432\n2524,717.347209762345,498.865867234383\n2525,702.610895087824,520.976174782041\n2526,730.018315343508,514.698489432745\n2527,696.657095433434,506.086807170698\n2528,711.795572346939,501.835576949493\n2529,765.607967666186,513.282939965086\n2530,705.711289347969,512.310739018131\n2531,712.993469093592,505.685426296664\n2532,732.330440031545,514.862371192457\n2533,732.705097990842,497.766795184823\n2534,706.915319731284,505.80130825517\n2535,724.679688376129,508.145402796393\n2536,707.980133825,501.587071290856\n2537,708.519529360669,509.660609912027\n2538,725.083534939477,507.668338212895\n2539,714.789571484641,514.771161692837\n2540,715.413469521247,507.395085274912\n2541,712.261432358814,512.808416643355\n2542,720.207684238056,524.321967588341\n2543,718.003469469896,512.302205562632\n2544,711.036442001726,506.408052546023\n2545,709.022842780384,512.158309024\n2546,698.325271564946,506.982612091813\n2547,705.731924573589,505.206764959996\n2548,729.94103008645,514.468723772562\n2549,733.464601193565,519.836899386103\n2550,730.846912293312,514.421719048685\n2551,759.132891671461,504.619247545755\n2552,768.412485479488,506.238492598795\n2553,709.562017367307,511.140019977507\n2554,742.55643882386,516.726958835594\n2555,715.745466837981,509.044636517919\n2556,720.811457503462,504.142920480638\n2557,758.38759988902,510.989224905099\n2558,720.267570188603,517.495786620897\n2559,723.031146144086,510.718482655543\n2560,702.535080565597,512.109833890633\n2561,703.881264215399,506.092386342118\n2562,698.349619636871,514.970759424617\n2563,711.30128991577,512.856013659791\n2564,714.378051459484,506.583591695443\n2565,739.5777533731,506.55989454807\n2566,705.200647792156,496.523620658871\n2567,729.414777306155,513.436306560675\n2568,750.632846294004,511.731579335341\n2569,739.817400547439,510.054885254895\n2570,718.9110784237,516.464856284482\n2571,719.479654662659,505.149537604057\n2572,739.707267332963,501.337036544095\n2573,736.66822556415,500.732047718267\n2574,718.020625955659,501.573432784555\n2575,738.566495790281,503.708502786858\n2576,719.896876886291,513.595750653755\n2577,728.615262877521,514.011999052976\n2578,710.968462361781,506.188938451658\n2579,727.94909500328,508.319947289455\n2580,722.706043316224,510.006918437851\n2581,752.9562751484,516.09010640847\n2582,739.163589705746,499.153924515292\n2583,754.939994492301,514.535840107035\n2584,734.694355139667,506.498746342374\n2585,712.611663964878,510.117983089913\n2586,735.007403662779,510.29712593476\n2587,736.424414179715,510.240909991962\n2588,734.221189558071,510.960250961282\n2589,742.874699905608,502.323327047711\n2590,730.901286318497,513.210726914286\n2591,721.63301835794,500.947267855669\n2592,757.645763392591,508.710963807617\n2593,746.047728840629,509.476501616489\n2594,682.24264245468,512.988414686411\n2595,674.831133717259,509.802686458486\n2596,676.287803454194,510.022294136424\n2597,660.312809131119,510.862912590586\n2598,664.349537930064,515.754536542995\n2599,696.13506190596,518.394125050968\n2600,670.71885958415,509.413581657552\n2601,670.066714480675,521.741067854792\n2602,677.61574409946,505.780956749771\n2603,666.773924726631,508.274409142662\n2604,678.788894245497,503.020871332236\n2605,664.834672642382,480.277445803153\n2606,663.856912915817,513.211103771201\n2607,,498.541897979581\n2608,,509.405546480069\n2609,,443.761350149685\n2610,,497.774770900689\n2611,,505.437996277318\n2612,,513.79101920463\n2613,,494.323036182064\n2614,,507.610540543867\n2615,,501.961258404993\n2616,,503.930608186592\n2617,,504.142115738259\n2618,,505.249672562828\n2619,,503.554710230971\n2620,,519.809733721646\n2621,,513.926813023223\n2622,,513.366829196595\n2623,,510.72916366254\n2624,,504.931699883829\n2625,,500.410746252329\n2626,,511.840027867266\n2627,,518.459834460783\n2628,,504.283538726965\n2629,,504.903885800987\n2630,,514.667040899355\n2631,,508.67524898955\n2632,,515.771608667894\n2633,,511.610798019848\n2634,,502.62408052345\n2635,,516.806430919404\n2636,,498.574038028349\n2637,,522.301129208326\n2638,,507.147302493893\n2639,,504.534609901515\n2640,,515.460280754727\n2641,,457.735174171517\n2642,,503.424707956421\n2643,,507.963201665118\n2644,,512.776734252785\n2645,,498.852892044573\n2646,,497.382020305828\n2647,,508.853584775191\n2648,,512.922719598631\n2649,,517.304980910848\n2650,,526.044959127347\n2651,,507.850112282689\n2652,,512.389196268402\n2653,,504.772423849644\n2654,,499.175678310005\n2655,,514.332727565145\n2656,,513.913488983444\n2657,,516.566813294407\n2658,,511.84501954889\n2659,,503.554806789834\n2660,,506.12378723905\n2661,,509.126284475969\n2662,,508.838893799052\n2663,,464.881722386558\n2664,,507.937028292349\n2665,,506.628075836436\n2666,,512.550042328671\n2667,,522.694927024105\n2668,,503.754349165744\n2669,,499.713504646516\n2670,,512.197014276441\n2671,,505.967131336117\n2672,,508.338023927858\n2673,,512.759035357878\n2674,,509.780074002993\n2675,,503.578094687408\n2676,,511.062874549861\n2677,,500.304747746297\n2678,,507.730519037504\n2679,,505.629277395476\n2680,,518.390238326907\n2681,,499.435154603203\n2682,,519.913923779749\n2683,,509.291240190795\n2684,,506.1668386614\n2685,,502.274676978841\n2686,,507.06264001084\n2687,,498.380837309495\n2688,,513.857066581137\n2689,,506.254842518422\n2690,,519.724757923523\n2691,,502.238327560327\n2692,,497.90771025334\n2693,,506.621125991072\n2694,,511.390528396464\n2695,,506.13088951859\n2696,,504.917413670471\n2697,,501.719393294489\n2698,,502.528606318145\n2699,,497.174791588045\n2700,,505.721887116149\n2701,,448.808084302699\n2702,,503.383223200926\n2703,,524.439156500063\n2704,,512.866105987833\n2705,,495.471823724106\n2706,,515.092631619536\n2707,,511.56015902754\n2708,,502.331579499774\n2709,,504.622658245908\n2710,,509.136835656969\n2711,,506.858078785367\n2712,,512.914076186554\n2713,,506.860566302428\n2714,,503.961467850508\n2715,,508.633230558229\n2716,,507.604655705427\n2717,,516.410276718785\n2718,,500.159268606564\n2719,,501.0864164038\n2720,,503.35423085728\n2721,,513.884434778666\n2722,,509.874130891317\n2723,,513.483448793209\n2724,,506.148450852066\n2725,,500.289038822701\n2726,,499.301208200187\n2727,,506.98023653404\n2728,,505.25211847788\n2729,,505.443455288827\n2730,,502.416231607009\n2731,,512.416378532892\n2732,,502.999862171747\n2733,,529.772720745289\n2734,,511.822640698812\n2735,,507.010440944813\n2736,,503.890168446765\n2737,,515.852302066724\n2738,,513.511282905244\n2739,,466.640558702075\n2740,,515.364681820992\n2741,,503.590027138672\n2742,,515.147784044857\n2743,,514.382173181514\n2744,,503.855147864285\n2745,,507.994255734834\n2746,,513.063110415273\n2747,,508.516125694572\n2748,,504.77156046548\n2749,,502.905594713006\n2750,,505.195780751094\n2751,,500.018659727222\n2752,,506.960551848647\n2753,,497.434204165882\n2754,,507.797330838154\n2755,,501.795625260748\n2756,,515.502261935339\n2757,,503.092737050279\n2758,,513.281282004485\n2759,,510.362257737307\n2760,,514.593119320654\n2761,,502.418813508495\n2762,,512.189113872905\n2763,,497.491818394392\n2764,,524.002902309059\n2765,,494.929364986093\n2766,,499.754305907921\n2767,,501.278333977348\n2768,,504.457551505583\n2769,,496.732541338179\n2770,,500.523406986457\n2771,,509.126165051325\n2772,,498.839789246135\n2773,,507.773124625121\n2774,,513.630030825276\n2775,,514.390597385094\n2776,,501.103709846409\n2777,,515.072366768305\n2778,,523.582362007748\n2779,,498.878327190839\n2780,,506.430909073378\n2781,,487.685332570943\n2782,,511.423870048947\n2783,,511.395005810935\n2784,,509.330571719414\n2785,,510.73721764486\n2786,,503.708424391958\n2787,,510.467161412844\n2788,,509.345288740092\n2789,,503.401447763366\n2790,,509.574703144928\n2791,,503.48377821556\n2792,,508.858682855888\n2793,,506.689269750024\n2794,,521.741711537556\n2795,,507.062983372004\n2796,,514.645941084662\n2797,,508.824214486749\n2798,,499.798331452307\n2799,,509.037328774322\n2800,,509.448421811306\n2801,,511.454511530579\n2802,,506.410358102228\n2803,,516.110198039803\n2804,,511.407778135741\n2805,,507.976838876393\n2806,,506.397100833435\n2807,,501.468655050126\n2808,,511.994135381239\n2809,,511.274598607329\n2810,,517.284261002424\n2811,,501.842322302975\n2812,,507.621983841003\n2813,,512.073911896627\n2814,,507.816023937653\n2815,,498.715588112912\n2816,,506.325941375632\n2817,,520.837524373621\n2818,,511.745466676623\n2819,,504.773355046788\n2820,,496.86068595165\n2821,,505.573927073049\n2822,,502.506825240143\n2823,,512.546688899844\n2824,,500.488060930195\n2825,,510.095754941606\n2826,,503.92996745109\n2827,,503.965208229643\n2828,,518.615186047755\n2829,,517.884049520108\n2830,,508.072850427902\n2831,,507.680802639453\n2832,,508.286562190827\n2833,,508.231999630677\n2834,,504.191317030599\n2835,,515.239340141732\n2836,,516.478262922951\n2837,,511.269713469983\n2838,,507.373194374359\n2839,,506.399819624624\n2840,,517.535740736867\n2841,,497.630926102269\n2842,,502.926779770909\n2843,,505.260921024439\n2844,,510.328567144703\n2845,,502.80199365854\n2846,,501.774839136186\n2847,,498.311982380795\n2848,,504.732888887374\n2849,,503.941724589803\n2850,,500.135992656564\n2851,,496.577892422743\n2852,,514.68759190973\n2853,,504.610593487306\n2854,,509.713103486097\n2855,,506.887536216695\n2856,,521.417422046479\n2857,,500.555974061856\n2858,,502.765694245186\n2859,,500.139667137026\n2860,,511.010395176719\n2861,,506.55328442303\n2862,,505.571956893305\n2863,,505.404248811828\n2864,,513.250078846882\n2865,,496.739985475442\n2866,,506.093321814449\n2867,,528.611907222203\n2868,,502.957054603416\n2869,,496.227586271752\n2870,,496.501250533203\n2871,,501.278872744518\n2872,,516.786990109029\n2873,,509.53388787718\n2874,,505.271142567432\n2875,,508.85639662279\n2876,,497.152751458892\n2877,,510.986484040977\n2878,,503.082224620742\n2879,,507.771623987115\n2880,,510.02318510948\n2881,,504.427557701833\n2882,,511.594473350803\n2883,,498.273293530608\n2884,,505.810961313082\n2885,,503.472321500473\n2886,,501.522128141928\n2887,,507.358995679061\n2888,,510.245752525599\n2889,,497.066673692808\n2890,,508.010554948263\n2891,,518.502043394373\n2892,,501.140446919448\n2893,,503.757636616998\n2894,,431.196867982304\n2895,,404.379644624502\n2896,,411.253007125844\n2897,,398.292950504512\n2898,,407.215718696382\n2899,,398.593658305431\n2900,,395.06783675965\n2901,,407.374180647734\n2902,,405.515233584539\n2903,,407.938763124108\n2904,,411.425457159942\n2905,,410.135043410251\n2906,,405.671852024055\n2907,,409.652645790479\n2908,,398.729250545933\n2909,,399.033285341902\n2910,,402.717002335453\n2911,,397.311438572839\n2912,,398.135183724569\n2913,,401.238413887689\n2914,,407.163694310668\n2915,,406.128679125437\n2916,,402.260736644348\n2917,,411.083706721991\n2918,,410.085283232748\n2919,,409.339798024131\n2920,,398.880873990118\n2921,,400.432974545524\n2922,,405.29675320147\n2923,,404.620553685613\n2924,,402.79739788042\n2925,,408.0957358143\n2926,,404.558348895774\n2927,,399.03721858028\n2928,,408.115922647804\n2929,,408.383498073148\n2930,,411.989766397075\n2931,,405.820579436365\n2932,,400.058830026854\n2933,,403.526144356237\n2934,,416.113983394421\n2935,,517.04260704871\n2936,,510.849261624666\n2937,,504.663736323875\n2938,,508.30181893509\n2939,,505.338715610433\n2940,,506.980423612121\n2941,,503.493118239429\n2942,,510.985814440419\n2943,,512.044593565008\n2944,,502.668124877036\n2945,,503.696477598879\n2946,,513.303937023998\n2947,,503.354182479303\n2948,,508.340628087682\n2949,,515.040857855205\n2950,,512.80205557457\n2951,,506.734230037841\n2952,,515.590901271616\n2953,,507.612102578569\n2954,,514.445893935111\n2955,,509.991084360184\n2956,,514.57928258159\n2957,,498.18845661789\n2958,,511.80950054661\n2959,,514.003117932028\n2960,,504.355056082885\n2961,,509.383238613721\n2962,,514.055991696559\n2963,,512.520014830717\n2964,,471.452184400128\n2965,,501.206607759073\n2966,,497.979343685461\n2967,,523.64455859634\n2968,,500.740889270017\n2969,,519.820205869749\n2970,,502.230242636272\n2971,,510.841062006844\n2972,,505.682610651942\n2973,,514.142330559169\n2974,,511.515873635822\n2975,,500.000174183238\n2976,,505.810769120946\n2977,,518.352472786252\n2978,,505.36417607856\n2979,,492.974248605775\n2980,,510.038029968623\n2981,,521.415315144461\n2982,,518.884749844672\n2983,,509.460420463872\n2984,,502.306243912619\n2985,,511.308977104288\n2986,,506.512552818242\n2987,,511.602090280878\n2988,,505.248752790833\n2989,,499.199103354219\n2990,,467.088398014472\n2991,,508.649553762287\n2992,,506.640546176748\n2993,,504.824795909503\n2994,,508.930792336839\n2995,,503.22415911768\n2996,,176.955782424209\n2997,,510.792706001881\n2998,,508.442701990469\n2999,,521.458627621687\n3000,,508.267105111962\n3001,,514.141756617636\n3002,,506.822307784083\n3003,,504.096285243449\n3004,,513.007989019296\n3005,,499.652933728558\n3006,,506.763328666549\n3007,,501.419591248824\n3008,,513.067061050048\n3009,,504.666724550187\n3010,,508.498154256934\n3011,,500.638748707218\n3012,,495.409429689586\n3013,,507.199525754709\n3014,,518.407405197988\n3015,,515.380840728545\n3016,,492.130975676102\n3017,,496.927330529765\n3018,,505.204003657151\n3019,,493.213775594147\n3020,,505.479336757586\n3021,,514.830792573977\n3022,,502.935055350554\n3023,,510.663398134758\n3024,,506.414862250491\n3025,,505.813891845722\n3026,,502.99946605508\n3027,,508.059924396308\n3028,,508.344247786808\n3029,,493.87532032491\n3030,,509.225556208923\n3031,,495.385026310493\n3032,,505.815542407907\n3033,,513.720013853776\n3034,,501.478854927499\n3035,,506.806319356382\n3036,,498.629892525215\n3037,,504.251279957432\n3038,,504.110136756455\n3039,,505.684916659994\n3040,,500.170615361739\n3041,,496.896560185392\n3042,,501.466839471994\n3043,,500.614248663866\n3044,,508.44484749484\n3045,,505.365063610014\n3046,,500.445031458107\n3047,,510.135368127201\n3048,,511.806949995602\n3049,,506.707110713742\n3050,,507.715296502803\n3051,,509.165473152785\n3052,,501.565450529996\n3053,,503.826021705344\n3054,,500.257627661938\n3055,,507.24973622727\n3056,,508.392977358114\n3057,,501.593558932984\n3058,,499.03001532726\n3059,,494.880341874011\n3060,,496.206794794437\n3061,,499.71901427613\n3062,,501.57010214079\n3063,,498.742291616361\n3064,,508.395974605603\n3065,,500.724547098577\n3066,,517.055304045978\n3067,,498.621414690213\n3068,,508.430414482222\n3069,,511.637080915001\n3070,,491.906239463104\n3071,,521.535542127421\n3072,,499.327031456428\n3073,,506.392448970044\n3074,,513.661515195249\n3075,,492.835790691952\n3076,,505.104906263026\n3077,,492.330892539383\n3078,,505.363688024928\n3079,,491.270423145185\n3080,,508.996300341371\n3081,,494.976792410505\n3082,,511.182157654505\n3083,,495.36859275336\n3084,,492.548821639403\n3085,,510.656947776369\n3086,,499.69582467835\n3087,,501.008250141509\n3088,,491.873308990928\n3089,,500.538935540523\n3090,,506.171442106535\n3091,,505.356299031929\n3092,,509.432237601044\n3093,,498.247462351711\n3094,,515.248833143924\n3095,,505.376781310084\n3096,,500.229834576831\n3097,,505.933395849671\n3098,,504.524609372865\n3099,,505.91602937676\n3100,,500.007608439011\n3101,,503.076276012376\n3102,,498.18108749625\n3103,,501.477735051092\n3104,,509.288326772479\n3105,,509.796593868182\n3106,,509.176201396283\n3107,,447.550752524965\n3108,,496.84746848756\n3109,,510.201543337638\n3110,,507.17977695218\n3111,,494.375196454795\n3112,,516.603827091379\n3113,,521.348077489967\n3114,,509.459543737958\n3115,,508.11551195887\n3116,,506.787332736012\n3117,,505.389509206859\n3118,,500.589548687958\n3119,,501.264844004755\n3120,,500.876849513268\n3121,,499.703221016388\n3122,,516.351541499343\n3123,,511.288048979824\n3124,,511.131576185398\n3125,,497.329462511718\n3126,,510.54630168748\n3127,,490.290822336164\n3128,,520.748213981098\n3129,,500.514607168669\n3130,,498.500901682326\n3131,,500.632598543275\n3132,,417.721582250417\n3133,,506.13714422324\n3134,,508.411885773285\n3135,,501.946890826948\n3136,,498.477117908137\n3137,,490.504950547972\n3138,,503.018330323378\n3139,,494.3799648869\n3140,,498.416162623402\n3141,,447.985759693236\n3142,,485.010012548173\n3143,,512.000736684372\n3144,,476.419676832168\n3145,,503.919399986213\n3146,,502.565397280323\n3147,,506.952482774727\n3148,,501.137152194321\n3149,,497.568417785687\n3150,,508.346243386291\n3151,,496.683209061953\n3152,,493.205085064096\n3153,,507.464416687605\n3154,,504.033149938291\n3155,,492.917573550011\n3156,,500.536598437241\n3157,,520.586135571898\n3158,,517.11933034675\n3159,,515.489148935976\n3160,,498.490530353398\n3161,,507.330056157887\n3162,,514.902085541518\n3163,,515.155279722038\n3164,,509.120737970745\n3165,,504.228275777625\n3166,,502.86436604369\n3167,,503.507852774818\n3168,,501.536429631579\n3169,,514.305517818644\n3170,,509.693839233895\n3171,,506.815064802914\n3172,,510.390562604085\n3173,,515.133479829411\n3174,,483.948638457487\n3175,,515.941028089237\n3176,,505.753066141103\n3177,,487.752130538318\n3178,,497.695008423376\n3179,,495.401070336358\n3180,,500.440270191664\n3181,,507.569735408344\n3182,,503.382121649215\n3183,,505.733867998137\n3184,,504.591233327525\n3185,,504.703978136231\n3186,,497.839734711385\n3187,,498.302703204577\n3188,,505.095826064894\n3189,,500.60401567617\n3190,,499.89741891578\n3191,,513.389344634373\n3192,,510.379343106981\n3193,,490.876508870411\n3194,,499.101662018248\n3195,,497.558354344311\n3198,,504.206352053832\n3199,,502.246518450246\n3200,,503.283308742196\n3201,,517.383481568224\n3202,,499.834331279471\n3203,,511.630360798576\n3204,,509.472263449682\n3205,,505.568096388227\n3206,,502.47874758613\n3207,,499.005273276444\n3208,,518.760385016078\n3209,,498.510434597166\n3210,,507.034192816979\n3211,,518.62033518346\n3212,,501.513146286849\n3213,,513.996450649472\n3214,,508.740665753584\n3215,,511.863263713108\n3216,,456.679242120378\n3217,,504.658440846009\n3218,,497.39439088837\n3219,,503.679112684596\n3220,,502.994150929803\n3221,,506.690727700474\n3222,,500.62317112372\n3223,,506.542232706584\n3224,,493.196403667649\n3225,,511.707978911019\n3226,,504.044968256204\n3227,,517.243154096342\n3228,,499.498355523771\n3229,,511.876207502035\n3230,,502.078551967338\n3231,,501.455234664325\n3232,,520.223317901185\n3233,,423.401516454518\n3234,,498.605656583935\n3235,,508.474749245205\n3236,,504.401166263713\n3237,,510.975853318267\n3238,,503.112750400228\n3239,,495.037472283171\n3240,,499.963881639034\n3241,,500.282723390495\n3242,,507.791025129774\n3243,,499.893087447301\n3244,,501.32923657263\n3245,,501.012003275136\n3246,,502.595331004295\n3247,,507.323379273973\n3248,,494.208097933304\n3249,,500.760240302947\n3250,,500.515956425217\n3251,,500.046984354784\n3252,,512.732690385241\n3253,,500.419901598706\n3254,,506.93633580676\n3255,,511.134473229883\n3256,,510.71995578272\n3257,,497.076075000735\n3258,,520.112246254728\n3259,,514.068635364982\n3260,,501.537830465625\n3261,,502.438173300555\n3262,,502.248029683446\n3263,,507.158328449164\n3264,,496.004106445176\n3265,,508.730098854123\n3266,,499.647526727782\n3267,,502.038541902557\n3268,,490.825180269921\n3269,,503.283731367365\n3270,,505.245340003018\n3271,,499.146400399115\n3272,,503.883971260213\n3273,,510.81124324725\n3274,,502.30136019445\n3275,,508.252668343656\n3276,,495.171476369664\n3277,,509.590587564912\n3278,,510.157577461766\n3279,,507.392046578021\n3280,,511.101638210671\n3281,,507.824716946167\n3282,,505.150701703709\n3283,,504.889733359808\n3284,,501.721930479826\n3285,,501.102234853989\n3286,,497.640200886616\n3287,,502.011653114201\n3288,,498.65350395029\n3289,,509.367626656316\n3290,,500.095316643217\n3291,,501.793454319447\n3292,,495.740817500721\n3293,,505.456592627549\n3294,,515.407303097435\n3295,,509.666379074387\n3296,,500.365575672755\n3297,,499.774607519853\n3298,,512.68972112294\n3299,,504.827036322401\n3300,,524.355457970142\n3301,,516.491421116986\n3302,,509.483518347146\n3303,,498.995045318826\n3304,,508.071475427489\n3305,,495.177099674621\n3306,,513.263983897805\n3307,,517.852443400298\n3308,,508.668988817592\n3309,,501.811950964907\n3310,,497.209309510253\n3311,,498.12753111883\n3312,,506.477964376854\n3313,,503.949124438406\n3314,,513.882429492709\n3315,,501.801779722001\n3316,,482.340530679513\n3317,,500.241079968828\n3318,,495.400368909899\n3319,,506.559776369358\n3320,,502.056980478326\n3321,,508.537010729331\n3322,,506.216852561165\n3323,,509.682779771337\n3324,,510.528850439325\n3325,,499.110879250223\n3326,,498.065050864164\n3327,,518.083122917762\n3328,,513.449167515698\n3329,,508.919959574753\n3330,,495.434838825107\n3331,,498.252002820877\n3332,,509.708252268168\n3333,,521.953260160242\n3334,,515.042584336746\n3335,,509.181185939714\n3336,,495.865755334771\n3337,,506.107005792168\n3338,,508.031510482499\n3339,,495.416952837066\n3340,,501.913196040082\n3341,,505.887363540025\n3342,,515.692430527641\n3343,,498.06677940928\n3344,,527.708406493445\n3345,,510.019596360889\n3346,,501.191852976754\n3347,,512.508980079287\n3348,,500.193138057265\n3349,,501.274290982663\n3350,,497.117729015715\n3351,,495.605917217365\n3352,,497.09416894065\n3353,,507.07944241384\n3354,,504.606156160247\n3355,,495.180674794725\n3356,,502.769514474808\n3357,,498.949986300277\n3358,,504.824715745689\n3359,,513.020972300179\n3360,,500.472257978838\n3361,,507.228290921283\n3362,,513.422131933619\n3363,,507.161956491573\n3364,,503.245106072381\n3365,,513.083193688812\n3366,,508.116376798518\n3367,,510.293997033477\n3368,,500.721853439298\n3369,,498.477761552763\n3370,,500.892238963713\n3371,,517.472781738837\n3372,,508.045098994046\n3373,,507.56692184806\n3374,,505.812243123006\n3375,,501.78574739025\n3376,,501.285145605981\n3377,,499.727056333505\n3378,,489.877559825036\n3379,,503.478010622835\n3380,,504.708567275173\n3381,,496.812439365476\n3382,,495.785412313494\n3383,,504.291752687086\n3384,,501.21724185881\n3385,,502.738412731175\n3386,,509.021830975595\n3387,,493.788827960695\n3388,,505.307983039077\n3389,,496.523620658871\n3390,,503.170915290686\n3391,,507.482128741608\n3392,,502.213172796258\n3393,,498.825227219658\n3394,,501.786398156355\n3395,,496.26803252113\n3396,,511.81597306777\n3397,,505.657095139734\n3398,,501.10949251889\n3399,,505.803163847566\n3400,,504.757923529952\n3401,,515.01794126072\n3402,,506.647838868387\n3403,,507.008973293208\n3404,,498.775923250713\n3405,,504.79889229\n3406,,513.094530163408\n3407,,494.832577056022\n3408,,512.876021852326\n3409,,511.016314621032\n3410,,505.035400834973\n3411,,516.209277453718\n3412,,494.74786156233\n3413,,510.930353918665\n3414,,498.330843023277\n3415,,498.519973612938\n3416,,520.508738196255\n3417,,510.905066843174\n3418,,514.249605538543\n3419,,497.204429702268\n3420,,514.349016501065\n3421,,518.88554731719\n3422,,502.045737057315\n3423,,500.315412409512\n3424,,503.585057097198\n3425,,505.946059778565\n3426,,500.856356932285\n3427,,502.184422750268\n3428,,503.573537425042\n3429,,512.297775546407\n3430,,508.647718847715\n3431,,501.778493148136\n3432,,518.080375158866\n3433,,503.668029535329\n3434,,521.301526702826\n3435,,511.02648789832\n3436,,500.055513224898\n3437,,516.182258914573\n3438,,519.994811881969\n3439,,506.843892643837\n3440,,503.732600180036\n3441,,507.746487710918\n3442,,511.198925603278\n3443,,518.88425739329\n3444,,508.849783186505\n3445,,505.962899807333\n3446,,500.368322713763\n3447,,503.927901926759\n3448,,519.190555642491\n3449,,497.21800500595\n3450,,515.371978743232\n3451,,512.020644552012\n3452,,518.46150977314\n3453,,501.548485141028\n3454,,498.51895147987\n3455,,505.612977113705\n3456,,508.684262040118\n3457,,500.778472923835\n3458,,510.961189032603\n3459,,522.414246938273\n3460,,501.329672950792\n3461,,505.68141587021\n3462,,506.416544369766\n3463,,501.791484613581\n3464,,506.773152699979\n3465,,506.674904273496\n3466,,507.839647874272\n3467,,519.282954176179\n3468,,499.900171787966\n3469,,518.821565640775\n3470,,521.168084215831\n3471,,507.992929132311\n3472,,515.301053763648\n3473,,505.348152793924\n3474,,495.804157958238\n3475,,502.475991798303\n3476,,508.62668543706\n3477,,511.176761628467\n3478,,510.933274888833\n3479,,509.28392522024\n3480,,513.305171280216\n3481,,512.688291585315\n3482,,511.354539781416\n3483,,505.151493132954\n3484,,506.49561494235\n3485,,521.702715618617\n3486,,518.264795472185\n3487,,506.016679517677\n3488,,512.407560534884\n3489,,500.346375071043\n3490,,505.973420137059\n3491,,505.368667325932\n3492,,517.162649814325\n3493,,504.72721365913\n3494,,507.021922710768\n3495,,515.119389016679\n3496,,522.412781288915\n3497,,511.20808761991\n3498,,510.52773912621\n3499,,507.151543584499\n3500,,502.219533560304\n",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Trendy",
      "type": "trend"
    }
  ],
  "refresh": "",
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "2023-04-04T09:02:40.080Z",
    "to": "2023-04-04T15:02:40.080Z"
  },
  "timepicker": {},
  "timezone": "",
  "title": "trend",
  "uid": "b8b7d389-d9eb-48ce-a613-6a3fbd564d13",
  "version": 5,
  "weekStart": ""
}
```
</details>

image

Currently the XY chart is the only option when trying to graph x != time, however it is structured to be more generic and unlike the timeseries panel, does not assume increasing values on the X axis.

BUT there are many requests to support the same features available in timeseries, but for x != time.

This PR adds a simple stub for a new "Trend" panel that will work with numeric X axis that has ascending values.

Currently it is an exact copy of timeseries but removing the time specific features

### CODE REVIEW

File: public/app/plugins/panel/trend/TrendPanel.tsx [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+        fieldConfig={fieldConfig}
+        data={data}
+        needsTimeField={true}
+        needsNumberField={true}
+      />
+    );
+  }
+
+  return (
+    <TimeSeries // Name change!
```
Comment (ryantxu) [inline public/app/plugins/panel/trend/TrendPanel.tsx:48]: We can/should likely rename this component --it is shared between Trend+TimeSeries

File: public/app/plugins/panel/trend/TrendPanel.tsx [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+        if (
+          alignedDataFrame.fields.filter((f) => f.config.links !== undefined && f.config.links.length > 0).length > 0
+        ) {
+          alignedDataFrame = regenerateLinksSupplier(alignedDataFrame, frames, replaceVariables, timeZone);
+        }
+
+        return (
+          <>
+            <KeyboardPlugin config={config} />
+            <ZoomPlugin config={config} onZoom={onChangeTimeRange} />
```
Comment (ryantxu) [inline public/app/plugins/panel/trend/TrendPanel.tsx:68]: Zoom will need to be different/disabled 🤷

File: public/app/plugins/panel/trend/TrendPanel.tsx [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+  height,
+  options,
+  fieldConfig,
+  onChangeTimeRange,
+  replaceVariables,
+  id,
+}: PanelProps<PanelOptions>) => {
+  const { sync } = usePanelContext();
+
+  const frames = useMemo(() => prepareGraphableFields(data.series, config.theme2, timeRange), [data, timeRange]);
```
Comment (ryantxu) [inline public/app/plugins/panel/trend/TrendPanel.tsx:33]: ^^ TODO... needs to be number/category specific

File: public/app/plugins/panel/trend/TrendPanel.tsx (hunk 1 above)
Comment (leeoniya) [reply public/app/plugins/panel/trend/TrendPanel.tsx:77]: timeseries data _is_ a trend. the internal component can be renamed to Trend and it will have either x=time or x=number

File: packages/grafana-ui/src/components/GraphNG/GraphNG.tsx [hunk 4]
```diff
@@ -39,6 +39,7 @@ export const FIXED_UNIT = '__fixed';
 export type PropDiffFn<T extends any = any> = (prev: T, next: T) => boolean;
 
 export interface GraphNGProps extends Themeable2 {
+  xField?: string;
```
Comment (ryantxu) [inline packages/grafana-ui/src/components/GraphNG/GraphNG.tsx:42]: do we need this?

File: public/app/plugins/panel/timeseries/utils.ts [hunk 5]
```diff
@@ -15,12 +15,14 @@ import { convertFieldType } from '@grafana/data/src/transformations/transformers
...
 import { applyNullInsertThreshold } from '@grafana/ui/src/components/GraphNG/nullInsertThreshold';
 import { nullToValue } from '@grafana/ui/src/components/GraphNG/nullToValue';
+import { findField } from 'app/features/dimensions';
 
 /**
  * Returns null if there are no graphable fields
  */
 export function prepareGraphableFields(
   series: DataFrame[],
+  xField: string | undefined,
```
Comment (ryantxu) [inline public/app/plugins/panel/timeseries/utils.ts:25]: actually better... change this to a boolean flag (numericX=true?) and fail if series[0] is not number?

File: public/app/plugins/panel/trend/TrendPanel.tsx [hunk 6]
```diff
@@ -0,0 +1,123 @@
...
+          frames: data.series,
+        };
+      }
+
+      xFieldName = f.name;
+    }
+
+    const frames = prepareGraphableFields(data.series, xFieldName, config.theme2);
+
+    return { frames, xFieldName };
```
Comment (ryantxu) [inline public/app/plugins/panel/trend/TrendPanel.tsx:61]: ^^^ rather than needing to find it again, lets just set it as the first field here

File: packages/grafana-ui/src/components/GraphNG/GraphNG.tsx (hunk 4 above)
Comment (leeoniya) [reply packages/grafana-ui/src/components/GraphNG/GraphNG.tsx]: nope

**Review by leeoniya — APPROVED** [review]

File: public/app/plugins/panel/trend/TrendPanel.tsx [hunk 7]
```diff
@@ -0,0 +1,137 @@
...
+      const field = frames[0].fields[xFieldIdx];
+      if (field.type === FieldType.number) {
+        // we may support ordinal soon
+        let last = Number.NEGATIVE_INFINITY;
+        const values = field.values.toArray();
+        for (let i = 0; i < values.length; i++) {
+          const v = values[i];
+          if (last > v) {
+            return {
+              warning: `Values must be in ascending order (index: ${i}, ${last} > ${v})`,
```
Comment (ryantxu) [inline public/app/plugins/panel/trend/TrendPanel.tsx:67]: @leeoniya -- I'm adding this explicit check here... seems better that we block the weird behaviors that almost work from the start.  Then we can avoid the issue with timeseries, where we have to sort implicitly 😬

Comment (leeoniya) [reply public/app/plugins/panel/trend/TrendPanel.tsx:67]: buuuhhhhttt...

https://github.com/grafana/grafana/blob/afc9925dbfa55886cc85a9a2106ed9892d7df239/packages/grafana-data/src/transformations/transformers/joinDataFrames.ts#L355

**Comment by demonkoryu** [comment]
Awesome work! Thanks!
