### PR TITLE
Alerting: Fix stale alertmanager selection issue when switching organizations

### LINKED ISSUE #83320: Alerting UI: Selected Alertmanager not found
### What happened?

Error in the alerting UI pages (Contact Point, etc.) in Grafana:

> **Selected Alertmanager not found.**
> The selected Alertmanager no longer exists or you may not have permission to access it. You can select a different Alertmanager from the dropdown.

image

The dropdown to select an Alertmanager is inactive and can't be used to choose a different Alertmanager.

### What did you expect to happen?

The Alerting UI page loads, and for example listing configured Contact Points.

### Did this work before?

I don't know

### How do we reproduce it?

This requires two _organizations_ in Grafana; `A` and `B`.

Organization `A` must have an **external Alertmanager datasource** configured, while `B` should have none.

1. Go to one of the Alerting UI pages in organization `A`
2. Select the **external Alertmanager** to display it's configuration
3. Switch to organization `B`
4. Go to one of the Alerting UI pages
5. The error should now be displayed

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: v10.3.1
OS: macOS 14.3.1
Browser: Google Chrome 122

### Grafana platform?

Kubernetes

### Datasource(s)?

Alertmanager

### PR DESCRIPTION
**Pull request by rodrigopk**
**Problem**

The Alerting UI stored the selected Alertmanager in a single global localStorage key (alerting-alertmanager) shared across all organizations. When a user switched orgs or renamed the datasource, the stale key referred to an AM that no longer existed in the current context, causing the UI to render an error with a disabled dropdown that offered no way to recover.

*Before the fix*

https://github.com/user-attachments/assets/d073b04e-6e0d-4009-af9a-e057063fb879

**Fix**

Refactored the localStorage key to be scoped per organization (alerting-alertmanager-org-{orgId}), preventing cross-org contamination. Additionally, when the desired AM is unavailable, the context now gracefully falls back to the Grafana built-in Alertmanager (instead of returning undefined) and cleans up the stale key, ensuring users are never left in a broken state.

*After the fix*

https://github.com/user-attachments/assets/f823ccc4-f542-4db4-bd5a-86776a5515e4

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/83320

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/alerting/unified/state/AlertmanagerContext.tsx [hunk 1]
```diff
@@ -59,37 +64,49 @@ const AlertmanagerProvider = ({ children, accessType, alertmanagerSourceName }:
...
+
+  let selectedAlertmanager: string | undefined;
+  if (isDesiredAvailable) {
+    selectedAlertmanager = desiredAlertmanager;
+  } else if (isAlertManagerAvailable(availableAlertManagers, defaultSource)) {
+    selectedAlertmanager = defaultSource;
+  }
+
+  // Clean up stale org-scoped key if the stored value no longer resolves to an available AM
+  React.useEffect(() => {
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/state/AlertmanagerContext.tsx:102]: nit: prefer to directly import `useEffect` :)

edit: I see we already import from `React.` in this file – I wouldn't mind if we didn't either :D

**Comment by gillesdemey** [comment]
On initial switch to another (newly created) org I still get this warning – I can dig a bit deeper to see what we're missing

Screenshot 2026-03-12 at 10 00 51

**Comment by gillesdemey** [comment]
The warning seems to be from the back-end and will resolve itself after a while, seems to be some lazy configuration initialization :)

PR LGTM! ✅

**Review by gillesdemey — APPROVED** [review]

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/22994412055)
- Version: 13.0.0-22994412055
