### PR TITLE
VariableControls: Adjust variable selection in edit mode

### LINKED ISSUE #112566: Fix: Inconsistent Variable UX when in Edit mode
When in edit mode, the variables behaves inconsistently: a click on the check box does not work for modifying the selection, however clicking on the label might 🤷‍♀️

https://github.com/user-attachments/assets/02a07801-4c96-4374-a472-f565e9af1330

The change should be made behind a feature toggle

### PR DESCRIPTION
**Pull request by Sergej-Vlasov**
Multi select option checkbox contained label element so selecting option by clicking on checkbox would trigger variable edit pane selection. Adjusting logic to look only for label elements with specific `data-testid` to avoid false positives.

Fixes https://github.com/grafana/grafana/issues/112566

Before:

https://github.com/user-attachments/assets/5319329e-9fe6-43f0-b662-b75da84369cb

After:

https://github.com/user-attachments/assets/b93a9e55-120f-43dd-bb45-c8eb8bda97c9

### CODE REVIEW

File: public/app/features/dashboard-scene/scene/VariableControls.tsx [hunk 1]
```diff
@@ -60,10 +60,16 @@ export function VariableValueSelectWrapper({ variable, inMenu }: VariableSelectP
...
+    if (evt.target instanceof Element) {
+      // multi variable options contain label element so we need a more specific
+      //  condition to target variable label to prevent edit pane selection on option click
+      const testId = evt.target.closest('label[data-testid]')?.getAttribute('data-testid');
+
+      if (!testId?.startsWith(selectors.pages.Dashboard.SubMenu.submenuItemLabels(''))) {
+        // Prevent clearing selection when clicking inside value
+        evt.stopPropagation();
+        return;
+      }
```
Comment (oscarkilhed) [inline public/app/features/dashboard-scene/scene/VariableControls.tsx:68]: I don't like this use of testId. In my opinion testId should really only be used in testing.

I'm thinking we could remove this check completely and surround the component with an element that stops propagation.

something like this (but not with the inline function)
image

**Review by oscarkilhed — CHANGES_REQUESTED** [review]

File: public/app/features/dashboard-scene/scene/VariableControls.tsx (hunk 1 above)
Comment (Sergej-Vlasov) [reply public/app/features/dashboard-scene/scene/VariableControls.tsx:68]: @oscarkilhed Played around with some options and here is what we got:

1. Wrap `<variable.Component />` and add `onPointerDown` with event propagation stop
    - probably cleanest idea, but we get few issues
    - border rounding issue Screenshot 2025-11-05 at 10 38 51
    - quite a few E2E tests will need adjustment due to additional nesting (lack of test ids force tests to traverse html)
2. Wrap `<VariableLabel />` and move `onPointerDown` to it
    - same E2E issue as above
    - future issue - might be tricky to enable selecting variable edit pane when no label present without encountering the same issue
3. Do not wrap and adjust `onPointerDown`
    - instead of `data-testid` we could utilise `for` attribute 
    
 
2 or 3 sounds most reasonable. If you don't want approach 3 I am happy to implement option 2 and adjust E2Es.

Comment (oscarkilhed) [reply public/app/features/dashboard-scene/scene/VariableControls.tsx:68]: Good catch on the border issue, I didn't pick that up. Let's go with option 3 to keep the E2E tests the same.

**Review by oscarkilhed — APPROVED** [review]
