### PR TITLE
Alerting: Update provisioning API to support regular permissions

### LINKED ISSUE #69073: alerting: export button not seen for Editor user
### 
# What went wrong?

**What happened**:

 Export button is seen only for admin users

**What did you expect to happen**:

 For Editor Grafana users to be able to see the Export button in order to download all alerts

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and do X 

**Step 2**:

- Now click button Y

**Step 3**:

- Wait for the browser to crash. Error message says: "Error..."

### 
# What Grafana version are you using?

9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Other

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What is this feature?**
Update provisioning API to support regular permissions e.g. `alert.rules:read`, `alert.rules:create` etc that require scope folder UID. 

The current permissions `alert.provisioning:read` and `alert.provisioning:write` are still considered. The changes are structured in a way that these permissions bypass the new authorization code.

**Why do we need this feature?**
1. Support fine-grained access control in provisioning API.
2. Reduce the difference between regular and provisioning API to simplify the merge in the future.

**Who is this feature for?**
Users of provisioning API that want to limit access for provisioning user.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/69073

**Special notes for your reviewer:**
- The changes are structured in a way to be able to bypass the new validation logic that makes extra calls to the database. This is done to reduce the impact on file provisioning that operates under the (assumed) admin permissions as well as API provisioning when the user has blanket permissions.

- To have the best review experience, you can review it by commits.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by mdraijer** [comment]
Hi @yuri-tceretian , I see that the build is breaking on:

```
pkg/services/ngalert/api/api_provisioning_test.go:1607:21: cannot use ruleAuthz (variable of type *provisioning.FakeProvisioningRuleAccessControlService) as provisioning.RuleAccessControlService value in struct literal: *provisioning.FakeProvisioningRuleAccessControlService does not implement provisioning.RuleAccessControlService (wrong type for method AuthorizeAccessToRuleGroup)

		have AuthorizeAccessToRuleGroup("context".Context, identity.Requester, "github.com/grafana/grafana/pkg/services/ngalert/models".RulesGroup) bool

		want AuthorizeAccessToRuleGroup("context".Context, identity.Requester, "github.com/grafana/grafana/pkg/services/ngalert/models".RulesGroup) error (typecheck)
```

I am not that proficient in Go, but it seems that AuthorizeAccessToRuleGroup should simply return the error instead of a bool, and maybe a few calls to the method to test on error != nil instead of a boolean.

When do you expect that the PR is ready?

It really is an important feature for alerting that the provisioning API should be available to editors.

**Comment by vanhoutenbos** [comment]
Any progress or planning on this? For people using Grafana OS this is an annoying bug.
An editor can make alerts in the UI but not the API.

How can we get someone on this that can tell us about the planning for this bug?
Is there still work that needs to done on the PR?

**Comment by yuri-tceretian** [comment]
> Any progress or planning on this? For people using Grafana OS this is an annoying bug.
An editor can make alerts in the UI but not the API.

How can we get someone on this that can tell us about the planning for this bug?
Is there still work that needs to done on the PR?

File: pkg/services/ngalert/provisioning/accesscontrol.go [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+var _ ruleAccessControlService = &provisioningRuleAccessControl{}
+
+func (p *provisioningRuleAccessControl) AuthorizeAccessToRuleGroup(ctx context.Context, user identity.Requester, rules models.RulesGroup) error {
+	if can, err := p.CanReadAllRules(ctx, user); can || err != nil {
+		return err
+	}
+	return p.RuleAccessControlService.AuthorizeAccessToRuleGroup(ctx, user, rules)
+}
+
+func (p *provisioningRuleAccessControl) AuthorizeRuleChanges(ctx context.Context, user identity.Requester, change *store.GroupDelta) error {
```
Comment (alexweav) [inline pkg/services/ngalert/provisioning/accesscontrol.go:37]: Massive nit -
These are a pair (they do the same thing for both read and write), can we align the naming closer? i.e. `AuthorizeRuleRead` and `AuthorizeRuleWrite`?

the term `Access` doesn't imply read, it implies write too. i think `CanReadAllRules`/`CanWriteAllRules` does this very well already

File: pkg/services/ngalert/provisioning/alert_rules.go [hunk 2]
```diff
@@ -250,6 +356,38 @@ func (service *AlertRuleService) UpdateRuleGroup(ctx context.Context, user ident
 				New:      newRule,
 			})
 		}
+
+		// check if user has write access to all rules and can bypass the regular checks.
+		// If it cannot, check that the user is authorized to perform all the changes caused by this request
+		if can, err := service.authz.CanWriteAllRules(ctx, user); !can || err != nil {
+			if err != nil {
+				return err
+			}
```
Comment (rwwiv) [inline pkg/services/ngalert/provisioning/alert_rules.go:365]: There are a few places like this where we can avoid checking err twice by moving around the logic.

```suggestion
		can, err := service.authz.CanWriteAllRules(ctx, user)
		if err != nil {
			return err
		}
		if !can {
```

File: pkg/services/ngalert/provisioning/alert_rules.go [hunk 3]
```diff
@@ -285,35 +433,26 @@ func (service *AlertRuleService) ReplaceRuleGroup(ctx context.Context, user iden
...
+		if err := service.authz.AuthorizeRuleChanges(ctx, user, delta); err != nil {
+			return err
 		}
 	}
 
-	// Delete all rules.
-	return service.xact.InTransaction(ctx, func(ctx context.Context) error {
-		return service.deleteRules(ctx, user.GetOrgID(), ruleList...)
-	})
+	return service.persistDelta(ctx, user, delta, provenance)
```
Comment (rwwiv) [inline pkg/services/ngalert/provisioning/alert_rules.go:455]: 🚀

**Review by rwwiv — APPROVED** [review]
Few style nits but LGTM 🚀

**Review by JacobsonMT — APPROVED** [review]
LGTM with one comment

File: pkg/services/ngalert/provisioning/alert_rules.go [hunk 4]
```diff
@@ -486,6 +662,21 @@ func (service *AlertRuleService) DeleteAlertRule(ctx context.Context, user ident
...
+		delta, err := store.CalculateRuleDelete(ctx, service.ruleStore, rule.GetKey())
+		if err != nil {
+			return err
+		}
+		if err = service.authz.AuthorizeRuleGroupWrite(ctx, user, delta); err != nil {
+			return err
+		}
+	}
+
 	return service.xact.InTransaction(ctx, func(ctx context.Context) error {
```
Comment (alexweav) [inline pkg/services/ngalert/provisioning/alert_rules.go:680]:
```suggestion
	// The single delete is idempotent, and doesn't error when deleting a group that already doesn't exist.
	// This is different from deleting groups. We delete the rules directly rather than persisting a delta here to keep the semantics the same.
	// TODO: Either persist a delta here as a breaking change, or deprecate this endpoint in favor of the group endpoint.
	return service.xact.InTransaction(ctx, func(ctx context.Context) error {
```
There's a subtle choice here, I think this PR makes the right choice but now it's clear for readers in a comment. I had to so some significant archaeology to make sure this lined up correctly.

**Review by alexweav — APPROVED** [review]
LGTM

File: pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go [hunk 5]
```diff
@@ -192,7 +192,7 @@ type ProvisionedAlertRule struct {
 
 // swagger:route PUT /v1/provisioning/folder/{FolderUID}/rule-groups/{Group} provisioning stable RoutePutAlertRuleGroup
 //
-// Update the interval of a rule group.
+// Create or update alert rule group.
```
[the remark this answers is not in the document]
Comment (alexweav) [reply pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go:195]: I think we need to regenerate the openAPI docs for this? This text ends up in the openapi doc and is generally misleading, i think it would be nice to get it out of there.

File: pkg/services/ngalert/provisioning/alert_rules.go [hunk 6]
```diff
@@ -346,7 +488,7 @@ func (service *AlertRuleService) calcDelta(ctx context.Context, user identity.Re
 		NamespaceUID: group.FolderUID,
 		RuleGroup:    group.Title,
 	}
-	rules := make([]*models.AlertRuleWithOptionals, len(group.Rules))
+	rules := make([]*models.AlertRuleWithOptionals, 0, len(group.Rules))
```
[the remark this answers is not in the document]
Comment (yuri-tceretian) [reply pkg/services/ngalert/provisioning/alert_rules.go:491]: we filter out nils downstream https://github.com/grafana/grafana/blob/737f2ef637b69ff3e095a97badf80a0ec0504fc9/pkg/services/ngalert/store/deltas.go#L94-L96

**Comment by vanhoutenbos** [comment]
Hi, 

i see that this PR is still stuck in a milestone, when will this be released? We have been waiting for the release for quite a while
