### PR TITLE
TimeSeries: Fix showing datalinks when clicking on a point

### LINKED ISSUE #57565: TimeSeries: disable "Add annotation" on mobile/touch
extracted from https://github.com/grafana/grafana/issues/25580#issuecomment-1249230699

this is not good:

image

people are probably 90% more likely to want to view the tooltip on mobile than to add annotations. i think it makes sense to disable it on touch devices and/or screens below a certain size.

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes a regression in showing datalinks when clicking on a point. (regressed by the css changes in https://github.com/grafana/grafana/pull/75199)

Fixes https://github.com/grafana/grafana/issues/57565
Fixes https://github.com/grafana/support-escalations/issues/7884

also simplifies `ContextMenuPlugin` and prevents it from opening context menus unless clicking on a specific focused point. helps avoid the add annotation popup when double-click unzooming as well as clicking on mobile, where a tooltip should not be occluded by Add annotation popup.

### CODE REVIEW

File: public/app/plugins/panel/timeseries/plugins/ContextMenuPlugin.tsx [hunk 1]
```diff
@@ -39,108 +38,37 @@ export const ContextMenuPlugin = ({
...
-          return;
-        }
-        isClick = true;
-
-        if (e.target instanceof HTMLElement) {
-          if (!e.target.classList.contains('u-cursor-pt')) {
-            pluginLog('ContextMenuPlugin', false, 'canvas click');
-            setPoint({ seriesIdx: null, dataIdx: null });
-          }
+      u.over.addEventListener('click', (e) => {
```
Comment (leeoniya) [inline public/app/plugins/panel/timeseries/plugins/ContextMenuPlugin.tsx:49]: uplot now has some magic that prevents click from firing when it detects a drag (via a capturing listener on `.u-over`)

Comment (leeoniya) [inline public/app/plugins/panel/timeseries/plugins/ContextMenuPlugin.tsx:49]: uplot now has some internal quality-of-life assistance that prevents clicks from firing when it detects drags (via a capturing listener on `.u-over`)

File: public/app/plugins/panel/trend/TrendPanel.tsx [hunk 2]
```diff
@@ -137,15 +136,6 @@ export const TrendPanel = ({
...
             )}
-
-            <ContextMenuPlugin
-              data={alignedDataFrame}
-              frames={info.frames!}
-              config={config}
-              timeZone={timeZone}
-              replaceVariables={replaceVariables}
-              defaultItems={[]}
-            />
```
Comment (leeoniya) [inline public/app/plugins/panel/trend/TrendPanel.tsx:148]: probably does not make sense in this panel, since x != time. (most likely a leftover from TimeSeries copy/paste)

**Review by adela-almasan — APPROVED** [review]

**Review by nmarrs — APPROVED** [review]
code changes look good - was not able to replicate datalink issue locally though so was not able to confirm fix :/ (though functionality of context menu seems unchanged so that's good)

**Review by codeincarnate — APPROVED** [review]
Took a quick look over this and appears to fix the issue

**Review by dprokop — APPROVED** [review]
Works back!

**Comment by leeoniya** [comment]
so. many. reviews.

:heart: :eyes: :eye: :mag: :detective:

**Comment by GrzegorzLyp** [comment]
There is a problem with hints on TimeSeries. As you move cursor from top to bottom of the bar suddenly hint disappears and as you go further down hint from next bar is shown. That's really strange and need a fix. Screen show taken from https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1

image
