### PR TITLE
Explore: Fix issues when loading and both graph/table are collapsed

### LINKED ISSUE #17098: Explore: Impossible to view logs when once collapsed
**What happened**:
1. Run query (Loki)
2. Collapsed logs results
3. Refreshed page
4. Can't see query results anymore or run new query

**What you expected to happen**:
To be able to interact with Explore no matter the previous state

**How to reproduce it (as minimally and precisely as possible)**:
See What happened

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Removes the functionality of being able to collapse/expand the logs container.

**Which issue(s) this PR fixes**:
Fixes #17098 

**Special notes for your reviewer**:
Left the `showingLogs` ui property to not introduce a breaking change of parsing URL. Don't have any good idea how we can support removing of url parameters in a backward compatible way with the current solution.

### CODE REVIEW

**Comment by davkal** [comment]
The original issue is true for Graphs and Tables as well. Can we fix this for those as well as part of this PR (keeping them collapsable)?

File: public/app/features/explore/Panel.tsx [hunk 1]
```diff
@@ -4,18 +4,27 @@ interface Props {
   isOpen: boolean;
   label: string;
   loading?: boolean;
-  onToggle: (isOpen: boolean) => void;
+  isCollapsable?: boolean;
```
Comment (davkal) [inline public/app/features/explore/Panel.tsx]: Spelling issue, also I'd propose `collapsible`, it's shorter. Or is there a benefit with the `is` prefix?

**Review by hugohaggmark — CHANGES_REQUESTED** [review]
1. Change to a Prometheus datasource
2. Collapse both Table and Graph
3. Refresh page
4. Still can't run new queries

File: public/app/features/explore/Panel.tsx (hunk 1 above)
Comment (marefr) [reply public/app/features/explore/Panel.tsx]: Good catch. I went for is since `isOpen` was used. Will change :+1:

**Comment by davkal** [comment]
Even on 56e7ed43ad I still can repro hugo's issue.

**Comment by hugohaggmark** [comment]
Unfortunately I can still repro my issue.

**Comment by marefr** [comment]
Hmm that's really weird. But with my latest commit when having graph and table collapsed and reloading page I swear I could expand graph and/or table and then queries are run. What am I missing?

**Comment by marefr** [comment]
The issue was related to that the start page incorrectly was shown when reloading the page having graph/table collapsed. That should be fixed now together with actually running all reducer tests instead of only one :smile:

**Review by hugohaggmark — APPROVED** [review]

**Comment by hugohaggmark** [comment]
LGTM!
