### PR TITLE
Alerting: Fix display of paused recording rules

### LINKED ISSUE #102342: Alerting: Tweak presentation of paused recording rules
We don't appear to indicate that a Recording Rule is paused, which would be nice. e.g.

In the "View" page, perhaps instead of `Recording`, it says `Paused`.
Image

And in the "List" page, it would be good to have paused indicated somewhere.
Image

### PR DESCRIPTION
**Pull request by tomratcliffe**
**What is this feature?**
Fixes display of paused recording rules on the list view and detail views

**Why do we need this feature?**
(I think, but didn't verify that) A recent refactor in https://github.com/grafana/grafana/pull/101639 caused a small regression. (Tests are to come on this PR as well)

**Who is this feature for?**
Alerting users

Fixes https://github.com/grafana/grafana/issues/102342

### CODE REVIEW

File: public/app/features/alerting/unified/components/rule-viewer/RuleViewer.tsx [hunk 1]
```diff
@@ -73,7 +73,9 @@ const RuleViewer = () => {
 
   const isFederatedRule = isFederatedRuleGroup(rule.group);
   const isProvisioned = rulerRuleType.grafana.rule(rulerRule) && Boolean(rulerRule.grafana_alert.provenance);
-  const isPaused = rulerRuleType.grafana.alertingRule(rulerRule) && isPausedRule(rulerRule);
+  const isPaused =
+    (rulerRuleType.grafana.alertingRule(rulerRule) || rulerRuleType.grafana.recordingRule(rulerRule)) &&
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/components/rule-viewer/RuleViewer.tsx:77]: nit: given the logic is used in several places I think we could extract to a separate function so we can re-use it.

Comment (gillesdemey) [reply public/app/features/alerting/unified/components/rule-viewer/RuleViewer.tsx:77]: There should be one `rulerRule.grafana.rule()`

File: public/app/features/alerting/unified/components/rule-viewer/tabs/Details.tsx [hunk 2]
```diff
@@ -74,7 +74,9 @@ export const Details = ({ rule }: DetailsProps) => {
   const hasEvaluationDuration = Number.isFinite(evaluationDuration);
 
   const updated = rulerRuleType.grafana.rule(rule.rulerRule) ? rule.rulerRule.grafana_alert.updated : undefined;
-  const isPaused = rulerRuleType.grafana.alertingRule(rule.rulerRule) && isPausedRule(rule.rulerRule);
+  const isPaused =
+    (rulerRuleType.grafana.alertingRule(rule.rulerRule) || rulerRuleType.grafana.recordingRule(rule.rulerRule)) &&
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rule-viewer/tabs/Details.tsx:78]:
```suggestion
    (rulerRuleType.grafana.rule(rule.rulerRule) &&
```

File: public/app/features/alerting/unified/components/rules/RulesTable.tsx [hunk 3]
```diff
@@ -353,7 +353,9 @@ function useRuleStatus(rule: CombinedRule) {
 
   const isDeleting = Boolean(hasRuler && rulerRulesLoaded && promRule && !rulerRule);
   const isCreating = Boolean(hasRuler && rulerRulesLoaded && rulerRule && !promRule);
-  const isPaused = rulerRuleType.grafana.alertingRule(rulerRule) && isPausedRule(rulerRule);
+  const isPaused =
+    (rulerRuleType.grafana.alertingRule(rulerRule) || rulerRuleType.grafana.recordingRule(rulerRule)) &&
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rules/RulesTable.tsx:357]: dito `rulerRule.grafana.rule()` :)

**Comment by gillesdemey** [comment]
> (I think, but didn't verify that) A recent refactor in https://github.com/grafana/grafana/pull/101639 caused a small regression.

I checked and it's a regression :)

**Review by gillesdemey — APPROVED** [review]

**Review by soniaAguilarPeiron — APPROVED** [review]
LGTM!
