### PR TITLE
Explore: Improve handling time range keyboard shortcuts inside Explore

### LINKED ISSUE #56175: Explore: timerange keyboard bindings behave weirdly
**What happened**:
There are a few weird behaviours related to using time range keyboard bindings in Explore:

<details><summary>1. (fixed by https://github.com/grafana/grafana/pull/61892) Navigating away from explore and then back to it causes keybindings to be ignored (no error in console):</summary>

https://user-images.githubusercontent.com/1170767/193575390-d9c998f4-1be3-45ce-a48b-721210ae4e08.mov
</details>

<details><summary>2. In split view, only right pane's time range is updated:</summary>

https://user-images.githubusercontent.com/1170767/193575696-79b43e5c-07f4-4065-8a02-90041d98a8fd.mov
</details>

<details><summary>3. (not reproducible in 10.0) after closing split view it errors:</summary>

https://user-images.githubusercontent.com/1170767/193575904-6a138aac-fd0e-47e1-ae0c-94cad97cf1a1.mov

(opening the split view again is then similar to point 2)

**What you expected to happen**:

1. When navigating back to explore, it should work as normal
2. both pane should be affected (debatable)
3. no error should happen, it should work as normal.

</details>

**How to reproduce it (as minimally and precisely as possible)**:

se screen recordings

**Anything else we need to know?**:

**Environment**:
- Grafana version: `main`

### PR DESCRIPTION
**Pull request by ifrost**
Fixes https://github.com/grafana/grafana/issues/56175 (see point 2) by handling time keyboard shortcuts directly from appEvents instead of hooking it with TimeSrv/TimeModel (which are dashboards' internal objects)

Previously:

```mermaid
sequenceDiagram
 participant User
 participant KeybindingSrv
 participant Explore
 participant AppEvents as AppEvents (singleton)
 participant TimeSrv as TimeSrv (singleton)


 participant TimeModel


 TimeSrv->>AppEvents: in constructor(): subscribe(HANDLER)
 Explore->>TimeSrv: init(timeModel with timeRangeUpdated)


 User->>KeybindingSrv: keyboard shortcut
 KeybindingSrv->>AppEvents: AbsoluteTime/ZoomOut/ShiftTime(Event)
 AppEvents->>TimeSrv: HANDLER()
 TimeSrv->>TimeModel: timeRangeUpdated
 TimeModel->>Explore: timeRangeUpdated provided with TimeModel

```

After:

```mermaid
sequenceDiagram
 participant User
 participant KeybindingSrv
 participant Explore
 participant AppEvents as AppEvents (singleton)

 Explore->>AppEvents: on load: subscribe(HANDLER)
 User->>KeybindingSrv: keyboard shortcut
 KeybindingSrv->>AppEvents: AbsoluteTime/ZoomOut/ShiftTime(Event)
 AppEvents->>Explore: HANDLER()

```

Interestigly enough we've already had such handling but just for absolute range in Explore.tsx component. I moved all logic to useKeyboardShortcuts.

I wanted to remove all usage of TimeSrv in Explore but it turned out to involve twice more changes so I'll open a separate PR for it. You can check the branch here https://github.com/grafana/grafana/pull/73559.

### CODE REVIEW

File: public/app/features/explore/ExplorePage.tsx [hunk 1]
```diff
@@ -55,6 +56,8 @@ export default function ExplorePage(props: GrafanaRouteComponentProps<{}, Explor
     keybindings.setupTimeRangeBindings(false);
   }, [keybindings]);
 
+  useKeyboardShortcuts();
```
Comment (Elfo404) [inline public/app/features/explore/ExplorePage.tsx:59]: could we move 

```ts
  useEffect(() => {
    keybindings.setupTimeRangeBindings(false);
  }, [keybindings]);
```
inside `useKeyboardShortcuts` to make all the logic relative to timeranges and keybinings self-contained?

**Comment by Elfo404** [comment]
i would also consider adding this fix to the changelog, it's imho worth a mention as it significantly improves usability

**Review by Elfo404 — APPROVED** [review]
love this <3
