### PR TITLE
Search: uncheck dashboards after moved

### LINKED ISSUE #25158: Dashboards aren't unselected when moving folders
**What happened**:
I selected a bunch of dashboards and moved them into a different folder. I then selected the folder they were in and clicked "delete". After confirming the action, the dashboards I just moved, and were not selected, were deleted.

**What you expected to happen**:
Things that are not visually selected should not be deleted.

**How to reproduce it (as minimally and precisely as possible)**:
* Have dashboards in a folder.
* Select those dashboards and move them to a different folder.
* Select the old folder and click "delete".
* Confirm the action.
* Watch as your dashboards that you had moved out of the folder get deleted.

**Anything else we need to know?**:
It's possible the dashboards may have been selected, but not visible, as the folder they were moved into was not expanded. So I could not see them.

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: N/A
- OS Grafana is installed on: CentOS/8
- User OS & Browser: Linux Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
Uncheck selected dashboards after they have been moved to another folder. 

**Which issue(s) this PR fixes**:
Fixes #25158

### CODE REVIEW

File: public/app/features/search/reducers/manageDashboards.ts [hunk 1]
```diff
@@ -46,13 +46,18 @@ const reducer = (state: ManageDashboardsState, action: SearchAction) => {
         }),
       };
     case MOVE_ITEMS: {
-      const { dashboards, folder } = action.payload;
-      const uids = dashboards.map((d: DashboardSectionItem) => d.uid);
+      const dashboards: DashboardSectionItem[] = action.payload.dashboards;
+      const folder: DashboardSection = action.payload.folder;
```
Comment (hugohaggmark) [inline public/app/features/search/reducers/manageDashboards.ts:50]: You shouldn't need to type these if the action payload is correct type or?
```suggestion
      const dashboards = action.payload.dashboards;
      const folder = action.payload.folder;
```

File: public/app/features/search/reducers/manageDashboards.ts [hunk 2]
```diff
@@ -46,13 +46,18 @@ const reducer = (state: ManageDashboardsState, action: SearchAction) => {
...
       return {
         ...state,
         results: state.results.map(result => {
           if (folder.id === result.id) {
-            return { ...result, items: [...result.items, ...dashboards] };
+            return {
+              ...result,
+              items: [...result.items, ...dashboards.map(db => ({ ...db, checked: false }))],
+              checked: false,
+            };
```
Comment (hugohaggmark) [inline public/app/features/search/reducers/manageDashboards.ts:60]: If possible, try to refactor this reducer to `createSlice` from redux-toolkit instead. That way we can minimize the hierarchy of spread operators and just mutate the state instead as createSlice uses ImmerJs.

**Review by hugohaggmark — APPROVED** [review]
Looks good, but I haven't tested it out. I left a minor and a larger comment for you to consider if you agree.

File: public/app/features/search/reducers/manageDashboards.ts (hunk 2 above)
Comment (Clarity-89) [reply public/app/features/search/reducers/manageDashboards.ts:60]: That's what I'd normally do for Redux reducers but this reducer for for React's `useReducer` hook, no Redux involved, so I don't think `createSlice` would work here.

File: public/app/features/search/reducers/manageDashboards.ts (hunk 1 above)
Comment (Clarity-89) [reply public/app/features/search/reducers/manageDashboards.ts:50]: Probable relevant to the reply below, but there's no action creators here, just plain `dispatch` calls with `type` and `payload`, so no explicit typings on payload.

File: public/app/features/search/reducers/manageDashboards.ts (hunk 2 above)
Comment (hugohaggmark) [reply public/app/features/search/reducers/manageDashboards.ts:60]: Ok I see, it seems like `useReducer` hook comes with some drawbacks like untyped dispatches and deep nested object spreading? 

You can still use Redux from functional components with `useState` hook so I'm not sure I like this pattern that much, but I'm probably not understanding the complete picture here. WDYT @dprokop @torkelo?

Comment (dprokop) [reply public/app/features/search/reducers/manageDashboards.ts:60]: On a fence here TBH. I totally see redux-toolkit is more mature and has a very elegant way to manage state, but moving state to Redux in case of search means quite some refactoring. Taking into consideration the fact that we wanted to move more complex state handling into the Redux store, I think search is a very solid candidate to migrate. Question is- do @Clarity-89 have time to do this now, maybe this could be scheduled for 7.1 enterprise planning?

Comment (hugohaggmark) [reply public/app/features/search/reducers/manageDashboards.ts:60]: I agree, this will take some rework so better migrate this at a later stage.

Comment (Clarity-89) [reply public/app/features/search/reducers/manageDashboards.ts:60]: Didn't know we had a preference to use Redux even for local component state, but I'll keep that in mind in the future. 

Not sure about 7.1, seems like there are already other things planned, but will definitely look into this more later, especially if it starts becoming a bottleneck of some sort.
