### PR TITLE
Remotecache: Avoid race condition in Set causing error on insert. 

### LINKED ISSUE #17079: duplicate key on cache_data
**What happened**:
We've upgraded grafana from 6.1.6 to 6.2.0-beta1 recently due to the need to be able to query ElasticSearch 7 cluster. After the upgrade, sometimes an error pop's up in grafana dashboard for different requests - annotation, msearch result in 500. After a refresh, everything would continue to work. 
The error is: Error 1062: Duplicate entry "auth-proxy-sync-ttl:sysmonk" for key "PRIMARY"
This is a MySQL error. After debugging a bit, it looks to be cause by [this code](https://github.com/grafana/grafana/blob/2fff8f77dcdc90ab9a4890eeed95d8f3dced370b/pkg/infra/remotecache/database_storage.go#L107) which was added in #15457
There's probably a race condition happening, and the insert happens when there's no data yet, but data shows up during the request. 
My best suggestions is to use INSERT ON DUPLICATE KEY UPDATE, so something like this:
```
sql := `INSERT INTO cache_data (cache_key,data,created_at,expires) VALUES(?,?,?,?)`
		_, err = session.Exec(sql, key, data, getTime().Unix(), expiresInSeconds)
```
to:
```
sql := `INSERT INTO cache_data (cache_key,data,created_at,expires) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE data = ?, created_at = ?, expires = ?`
		_, err = session.Exec(sql, key, data, getTime().Unix(), expiresInSeconds, data, getTime().Unix(), expiresInSeconds)
```

I haven't looked at what other databases are supported, but this would work on mysql/mariadb. It's not a default SQL statement, so might not work on other sql databases - in example, sqlite has a [different syntax](https://www.sqlite.org/lang_UPSERT.html) for this.

**What you expected to happen**:
For stuff to just work, without errors :)

**How to reproduce it (as minimally and precisely as possible)**:
Enable sql backend
Enable proxy
Dashboard with more than one view
Doesn't happen straight away, in our case happens a few times per hour only.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.0-beta1
- Data source type & version: influxdb, elasticsearch 7
- OS Grafana is installed on: Debian Linux
- User OS & Browser: OSX 10.14.4 / Chrome 73
- Grafana plugins: 
- Others:

### PR DESCRIPTION
**Pull request by bergquist**
since set called the database twice without transactions another
operation could insert a value before the first operation completed.
which would raise an error on insert since the data have been inserted
by the other request.

closes #17079

### CODE REVIEW

File: pkg/infra/remotecache/database_storage.go [hunk 1]
```diff
@@ -80,44 +84,48 @@ func (dc *databaseCache) Get(key string) (interface{}, error) {
...
 
-	// insert or update depending on if item already exist
-	if has {
-		sql := `UPDATE cache_data SET data=?, created_at=?, expires=? WHERE cache_key=?`
-		_, err = session.Exec(sql, data, getTime().Unix(), expiresInSeconds, key)
-	} else {
-		sql := `INSERT INTO cache_data (cache_key,data,created_at,expires) VALUES(?,?,?,?)`
-		_, err = session.Exec(sql, key, data, getTime().Unix(), expiresInSeconds)
-	}
+		// insert or update depending on if item already exist
```
Comment (aocenas) [inline pkg/infra/remotecache/database_storage.go]: Would be nice to have an upsert for supported DBs. Xorm does not seem to have any but maybe we could write our own at some point. I think I seen this select/update/insert pattern already in the codebase.

**Review by aocenas — APPROVED** [review]
