### PR TITLE
Alerting: Fix renaming queries and rewiring expressions

### LINKED ISSUE #71637: Error after removing or moving queries in the alert rule form
Expressions are not rewired correctly after moving or removing queries.

It seems a regression after fixing the stale state for queries as this is not happening in `v9.4.13`.

https://github.com/grafana/grafana/assets/33540275/d3b06d47-8c78-4693-a08c-211058c70067

### PR DESCRIPTION
**Pull request by gillesdemey**
Still a minor bug when deleting the last data query, the expressions pointing to it will be reset to "A" for some reason but should fix https://github.com/grafana/grafana/issues/71637

### CODE REVIEW

File: public/app/features/alerting/unified/components/expressions/Expression.tsx [hunk 1]
```diff
@@ -225,9 +224,15 @@ export const PreviewSummary: FC<{ firing: number; normal: number; isCondition: b
   seriesCount,
 }) => {
   const { mutedText } = useStyles2(getStyles);
+
+  if (seriesCount === 0) {
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/expressions/Expression.tsx:228]: Unrelated to the fix but might as well

File: public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx [hunk 2]
```diff
@@ -526,9 +529,14 @@ const getStyles = (theme: GrafanaTheme2) => ({
 
 const useSetExpressionAndDataSource = () => {
   const { setValue } = useFormContext<RuleFormValues>();
+
   return (updatedQueries: AlertQuery[]) => {
     // update data source name and expression if it's been changed in the queries from the reducer when prom or loki query
     const query = updatedQueries[0];
+    if (!query) {
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx:536]: This prevents the UI from crashing since we can't assume `updatedQueries[0]` to not be `[]` when the last data query is removed.

File: public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx [hunk 3]
```diff
@@ -161,15 +161,18 @@ export const QueryAndExpressionsStep = ({ editingExistingRule, onDataChange }: P
...
-      });
+
+      // check if we need to rewire expressions (and which ones)
+      const updatedDataQueries = updatedQueries.map((query) => query.refId);
+      const previousDataQueries = queries
+        .filter((query) => !isExpressionQuery(query.model))
+        .map((query) => query.refId);
+
+      // this code assumes not more than 1 query refId has changed per "onChangeQueries"
+      const [oldRefId, newRefId] = xor(previousDataQueries, updatedDataQueries);
```
[the remark this answers is not in the document]
Comment (VikaCep) [reply public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx:172]: That'd be nice :)

**Review by VikaCep — APPROVED** [review]
