### PR TITLE
UX: Fix empty space in select

### LINKED ISSUE #19600: Bug: All select dropdowns have an empty space to the left
My guess is that this PR introduced this: https://github.com/grafana/grafana/pull/19465

Screen Shot 2019-10-03 at 14 39 23

### PR DESCRIPTION
**Pull request by aocenas**
Fixes: https://github.com/grafana/grafana/issues/19600

In case there is no image in the option that should show loading, the spinner will slide in and out instead of crossfading with the image, so the loading state is still usable without image.

### CODE REVIEW

**Review by hugohaggmark — APPROVED** [review]
LGTM! Tested it in various places and works as expected!

File: packages/grafana-ui/src/components/transitions/SlideOutTransition.tsx [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+    exitActive: css`
+      label: exitActive;
+      opacity: 0;
+      ${measurement}: 0;
+      transition: opacity ${duration}ms ease-out, ${measurement} ${duration}ms ease-out;
+    `,
+  };
+});
+
+type Props = {
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/transitions/SlideOutTransition.tsx]: Just of curiosity why a type and not an interface?

**Comment by torkelo** [comment]
Why do we need to add this to the changelog? This bug was never in a release.

File: packages/grafana-ui/src/components/transitions/SlideOutTransition.tsx (hunk 1 above)
Comment (aocenas) [reply packages/grafana-ui/src/components/transitions/SlideOutTransition.tsx]: Kinda unconscious personal preference (easier to type I guess). I rarely need to implement or extend `Props` so `type` seems fine there, not sure if there are any other benefits of using interface instead of type.

**Comment by aocenas** [comment]
@torkelo 
> Why do we need to add this to the changelog? This bug was never in a release.

And why does this need to mentiond in our npm package changelog?

Sorry thought the bug was in the release. Removed the changelog labels.

**Review by torkelo — APPROVED** [review]
Tested and all dropdown look good!
