### PR TITLE
TimeRangePicker: Allow users to navigate quick ranges with arrows instead of Tab

### LINKED ISSUE #56232: A11y: In Time Picker the Tab is used where the arrows Up and Down should be used instead
**What happened**:
In the **quick ranges** moving with arrow up and down is only moving the cursor but not moving through the options. We are using tab to preselect the option. This is not ideal because we need to go through the whole list using the tab to go the options "Absolute time range".

**What you expected to happen**:
Using the arrows for Up and Down on the keyboard should allow the user to go through the list of quick ranges by preselecting each option. The Tab, on the other hand, should allow the user to go to the next section ("Absolute time range" in this case) immediately at any point from the list of quick ranges. 

**How to reproduce it (as minimally and precisely as possible)**:
Open Time Picker in a dashboard. Use the Tab to get to the quick ranges list. Use the arrows Up and Down to see how the cursor moves, but the preselection stays the same.

https://user-images.githubusercontent.com/13227501/193757424-4c577871-1d1a-47f5-9409-663741029f95.mov

**Anything else we need to know?**:

**Relevant WCAG Criteria**:
[2.1.1 Keyboard - Level A](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=335%2C332#keyboard)

**Environment**:
- Grafana version: 9.3.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by JoaoSilvaGrafana**
**What is this feature?**

Currently if you are using the keyboard to navigate the TimeRange picker, you have to tab through all of the "Quick ranges" before you can even get to the next section. This feature makes it so that to navigate through the "Quick ranges" you can use the arrow keys.
This solution is _highly_ inspired by how we do this for the `Menu` [component](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Menu/hooks.ts).

Tabbing through before:

https://github.com/grafana/grafana/assets/100691367/94d9cf8d-db0f-471f-bce6-e1072baf36e4

Tabbing through now:

https://github.com/grafana/grafana/assets/100691367/8aeaac0a-848a-417c-b5e5-211aae32e367

**Why do we need this feature?**

To make the timerange picker easier to use with keyboard only.

**Who is this feature for?**

Keyboard users

**Which issue(s) does this PR fix?**:

Fixes #56232

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts [hunk 1]
```diff
@@ -0,0 +1,78 @@
+import { RefObject, useEffect, useState } from 'react';
+
+import { TimeOption } from '@grafana/data';
+
+const modulo = (a: number, n: number) => ((a % n) + n) % n;
```
Comment (tskarhed) [inline packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts:5]: Can you explain the logic behind this?

File: packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+/** @internal */
+export type UseListFocusReturn = [(event: React.KeyboardEvent) => void];
+
+/** @internal */
+export const useListFocus = ({ localRef, options }: UseListFocusProps): UseListFocusReturn => {
+  const [focusedItem, setFocusedItem] = useState(0);
+
+  useEffect(() => {
+    // Reset focused item when options have changed
+    setFocusedItem(0);
```
Comment (tskarhed) [inline packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts:22]: If an item is selected, that's the one supposed to get the focus if I remember correctly.

File: packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+        newFocusedIndex = modulo(focusedItem + 1, itemsCount);
+        break;
+      case 'Home':
+        event.preventDefault();
+        event.stopPropagation();
+        newFocusedIndex = 0;
+        break;
+      case 'End':
+        event.preventDefault();
+        event.stopPropagation();
```
Comment (tskarhed) [inline packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts:53]: Maybe you could add some generic logic to this? Store the keys in an enum and check if the pressed one is in it?

**Review by tskarhed — COMMENTED** [review]
I've played around with this issue a couple of times, and I must say it is unfortunate that there is no native behaviour for this :(

File: packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts (hunk 1 above)
Comment (JoaoSilvaGrafana) [reply packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts:5]: This was a direct copy of how it is done in the `Menu` [hook](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Menu/hooks.ts#L4). From what I understand this is a calculation for when a number goes "out of bounds" and you want to loop back to the top/bottom of the list, for instance if you are moving from index 7 to index 8, `modulo(8,8)` returns `0` so it will select the first item.

File: packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts (hunk 2 above)
Comment (JoaoSilvaGrafana) [reply packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts:22]: Hmm good point, that means somehow the list will have to have a selected concept or receive it

File: packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts (hunk 3 above)
Comment (JoaoSilvaGrafana) [reply packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts:53]: What do you mean here? 🤔

Comment (tskarhed) [reply packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts:53]: Just so you don't have to repeat 
```
event.preventDefault();
event.stopPropagation();
``` 
in the case for `ArrowUp`, `ArrowDown`, `Home`, `End` and `Enter`

File: packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts (hunk 2 above)
Comment (tskarhed) [reply packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts:22]: You could query the localRef for the `checked` attribute and then see which index it is in the list.

Comment (JoaoSilvaGrafana) [reply packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/hooks.ts]: I have done something like this, but open to ideas on how to rewrite it in a more clear way if there is one 👍

**Review by tskarhed — APPROVED** [review]
LGTM! 🥳 Although we probably need to open an issue about the scrollbar (it seems to be present in Play too, just not as pronounced)
image
