### PR TITLE
Prometheus: Fix link to Prometheus graph in dashboard

### LINKED ISSUE #29444: Link to Prometheus graph in edit mode not always working
**What happened**: Clicking the Prometheus link in edit mode (to get to the PromQL console for the corresponding query) opens the main Grafana page instead.

bild

**What you expected to happen**: The link opens the PromQL console with the right corresponding query.

**How to reproduce it (as minimally and precisely as possible)**:
1. Load a graph in edit mode
2. Without doing anything else, click the Prometheus link

grafana-prometheus-click

**Anything else we need to know?**:

I _think_ this started happening when upgrading from Grafana 6.4.3 to 7.2.1. It's still happening with Grafana 7.3.2.

After clicking around and e.g. editing the query, the link eventually starts working.

**Environment**:
- Grafana version: 7.2.1, 7.3.2
- Data source type & version: Prometheus 2.22.0
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: MacOS and Ubuntu 20.04, Firefox 83.0
- Grafana plugins: -
- Others: -

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
The href was set only in componentDidUpdate. Therefore to have href correct, you've had to interact with editor. This PR fixes it + adds test coverage. 

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/29444

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/components/PromLink.tsx [hunk 1]
```diff
@@ -18,6 +18,14 @@ interface State {
 export default class PromLink extends Component<Props, State> {
```
Comment (zoltanbedi) [inline public/app/plugins/datasource/prometheus/components/PromLink.tsx:18]: Would it be too much to ask to refactor this component to a function component? 😄 

2 things I noticed
- the same logic is used in componentDidMount and componentDidUpdate
- getExternalLink is async because?

Comment (ivanahuckova) [reply public/app/plugins/datasource/prometheus/components/PromLink.tsx:18]: No, not much work at all. And you are totally right ⭐️ - leave the code in better shape than.... So I refactored it to hooks + as I was adding tests, I switched to react-testing-library. 🙂

Comment (ivanahuckova) [reply public/app/plugins/datasource/prometheus/components/PromLink.tsx:18]: Also async was not necessary.

**Review by zoltanbedi — APPROVED** [review]
Thank you! This looks awesome with the refactor. Good job. 🐥
