### PR TITLE
v1 to v2 conversion: Fix issue when Grafana datasource wouldn't be resolved correctly

### LINKED ISSUE #114574: v1 -> v2 conversion: Panels using Grafana data source are incorrectly converted
1. **`type: "datasource"` and  without UID**: Panels using Grafana data source with mutliple queries are not resolved to the Grafana datasource (`uid: "grafana"`). This caused queries to show as "Mixed" data source in the UI instead of "Grafana". See attached dashboard 1).
2. **Empty target datasource inheritance**: Targets with `datasource: {}` are not correctly inheriting the panel datasource during conversion. See attached dashboard 2).

<details>
<summary>dashboard 1</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 284,
  "links": [],
  "panels": [
    {
      "datasource": {
        "type": "datasource"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "barWidthFactor": 0.6,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "showValues": false,
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": 0
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "hideZeros": false,
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "12.4.0-pre",
      "targets": [
        {
          "datasource": {},
          "queryType": "randomWalk",
          "refId": "A"
        },
        {
          "datasource": {},
          "hide": false,
          "queryType": "randomWalk",
          "refId": "B"
        }
      ],
      "title": "New panel",
      "type": "timeseries"
    }
  ],
  "preload": false,
  "schemaVersion": 42,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "browser",
  "title": "Grafana ds inheritance",
  "uid": "ad6t9qb",
  "version": 3
}
```
</details>

<details>
<summary>dashboard 2</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 288,
  "links": [],
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "gdev-testdata"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "barWidthFactor": 0.6,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "showValues": false,
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": 0
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "hideZeros": false,
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "12.4.0-pre",
      "targets": [
        {
          "datasource": {},
          "queryType": "randomWalk",
          "refId": "A"
        }
      ],
      "title": "New panel",
      "type": "timeseries"
    }
  ],
  "preload": false,
  "schemaVersion": 42,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "browser",
  "title": "Panel ds inheritance ",
  "uid": "ad5vfcn",
  "version": 2
}
```
</details>

### PR DESCRIPTION
**Pull request by dprokop**
Closes https://github.com/grafana/grafana/issues/114574

### Problem

Queries without explicit datasource that should inherit from panel datasource were not correctly handled during v1beta1 to v2alpha1 conversion, particularly for `type: "datasource"` without UID.

### Solution

- Resolve `type: "datasource"` to `uid: "grafana"` when UID is missing
- ~Handle `null` panel datasources with empty target datasource objects by defaulting to default datasource~
- Ensure queries properly inherit panel datasource when targets have empty datasource objects

### How to test

Run backend conversion tests:
go test ./apps/dashboard/pkg/migration/conversion/... -v

### CODE REVIEW

File: apps/dashboard/pkg/migration/conversion/v1beta1_to_v2alpha1.go [hunk 1]
```diff
@@ -1796,22 +1810,80 @@ func transformPanelQueries(ctx context.Context, panelMap map[string]interface{},
...
+	if len(targets) > 0 {
+		for _, target := range targets {
+			if targetMap, ok := target.(map[string]interface{}); ok {
+				if ds, ok := targetMap["datasource"].(map[string]interface{}); ok {
+					// Check if it's an empty object {}
+					if len(ds) == 0 {
+						hasEmptyTargetDatasource = true
+						break
+					}
+				}
```
Comment (ivanortegaalba) [inline apps/dashboard/pkg/migration/conversion/v1beta1_to_v2alpha1.go]: What if it is nil?

File: apps/dashboard/pkg/migration/conversion/v1beta1_to_v2alpha1_test.go
Comment (ivanortegaalba) [inline apps/dashboard/pkg/migration/conversion/v1beta1_to_v2alpha1_test.go]: We can remove this one since this has already been tested through snapshot testing in input/output comparison. WDYT?

**Review by ivanortegaalba — APPROVED** [review]
Tested! Even when saved as v2, if I loaded from v1 again, it works as expected. Great work! 💯

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/19867849846)
- Version: 12.4.0-19867849846
