### PR TITLE
Routing NG: Fix time range zoom not working when refresh enabled

### LINKED ISSUE #32010: Cant zoom into time-range
**What happened**:

Can't zoom into the time-range in the latest commit

https://user-images.githubusercontent.com/7354143/111273628-56f12e00-8634-11eb-8e8f-444e4ecf74cb.mp4

**How to reproduce it (as minimally and precisely as possible)**:

Open a dashboard and drag to zoom in.

**Environment**:
- Grafana version: Grafana v7.5.0-14319pre (50e5342379)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome on Linux
- Grafana plugins: None

### PR DESCRIPTION
**Pull request by dprokop**
Fixes https://github.com/grafana/grafana/issues/32010

### CODE REVIEW

File: public/app/features/dashboard/containers/DashboardPage.tsx [hunk 1]
```diff
@@ -138,7 +138,16 @@ export class DashboardPage extends PureComponent<Props, State> {
...
+      const prevUrlParams = new URLSearchParams(prevProps.location.search);
+      const urlParams = new URLSearchParams(this.props.location.search);
+
+      if (urlParams.get('from') !== prevUrlParams.get('from') && urlParams.get('to') !== prevUrlParams.get('to')) {
+        getTimeSrv().updateTimeRangeFromUrl();
+      }
+
+      if (!prevUrlParams.get('refresh') && urlParams.get('refresh')) {
+        getTimeSrv().setAutoRefresh(urlParams.get('refresh'));
+      }
```
Comment (torkelo) [inline public/app/features/dashboard/containers/DashboardPage.tsx:150]: this feels unelegant, can we add from & to and refresh to DashboardPageRouteSearchParams? and thhen do 

if (preProps.queryParams.from !== this.props.queryParams.from ...)

And then I would update updateTimeRangeFromUrl to pass in from & to, so it does not need to ask it from locationService again)

Comment (dprokop) [reply public/app/features/dashboard/containers/DashboardPage.tsx:150]: I have no idea what I've been thinking using the URLSearchParams here 🙈

**Review by torkelo — APPROVED** [review]
LGTM
