### PR TITLE
Logs Panel: Fix setting default details mode

### LINKED ISSUE #111252: New Logs Panel: Details not showing up
Details are not showing up on click if there's no `grafana.explore.logs.detailsMode` key in local storage.

Related PRs:

- [ ] https://github.com/grafana/grafana/pull/107718
- [ ] https://github.com/grafana/grafana/pull/110276
- [ ] https://github.com/grafana/grafana/pull/111163

Probably directly caused by https://github.com/grafana/grafana/pull/111163 (sets detailsMode to undefined on useEffect)

Possible fix: https://github.com/grafana/grafana/pull/111251

### PR DESCRIPTION
**Pull request by ifrost**
fixes: https://github.com/grafana/grafana/issues/111252

I have never set display mode added in https://github.com/grafana/grafana/pull/107718:

Screenshot 2025-09-17 at 15 39 58

I think that's why I also didn't have grafana.explore.logs.detailsMode in local storage ever set. After adding https://github.com/grafana/grafana/pull/110276 and https://github.com/grafana/grafana/pull/111163 it may be now be set to `undefined` in runtime causing no details being showed up on click.

### CODE REVIEW

File: public/app/features/logs/components/panel/LogListContext.tsx [hunk 1]
```diff
@@ -203,7 +203,7 @@ export const LogListContextProvider = ({
   enableLogDetails,
   logOptionsStorageKey,
   detailsMode: detailsModeProp = logOptionsStorageKey
-    ? store.get(`${logOptionsStorageKey}.detailsMode`)
+    ? store.get(`${logOptionsStorageKey}.detailsMode`) || getDefaultDetailsMode(containerElement)
```
Comment (matyax) [inline public/app/features/logs/components/panel/LogListContext.tsx]:
```suggestion
    ? store.get(`${logOptionsStorageKey}.detailsMode`) ?? getDefaultDetailsMode(containerElement)
```

**Review by matyax — APPROVED** [review]
Thank you!
