### PR TITLE
PanelEvents: Refactors and removes unnecessary events, fixes panel editor update issue when panel options change

### LINKED ISSUE #27464: PanelEdit: PanelProps onOptionsChange doesn't immediately update panel settings UI
**What happened**:
When reflecting changes back to a panel's options using `onOptionsChange`, the UI component in the settings side pane for the changed option will not update immediately. If you refresh the dashboard (or presumably any other action that re-renders the UI), the option will then render correctly. 
**What you expected to happen**:
Calling `onOptionsChange` within a panel should immediately refresh the settings UI to reflect the correct state. 

**How to reproduce it (as minimally and precisely as possible)**:
Minimal example using the simple-react-panel template
https://github.com/mure/grafana-options-bug 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.3
- Data source type & version:
- OS Grafana is installed on: macOS
- User OS & Browser: macOS Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #27464

This also removes and unifies some events that were only used to notify DashboardGrid that the panels array changed. A lot of this could be fixed by moving more state to redux or immutable react state. 

Had to add one new event for when panels change options so that the PanelEditor will know. 

Updated some events to the new event model.

### CODE REVIEW

File: public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx [hunk 1]
```diff
@@ -113,8 +129,9 @@ export class PanelEditorUnconnected extends PureComponent<Props> {
   };
 
   onPanelOptionsChanged = (options: any) => {
+    // we do not need to trigger force update here as the function call below
+    // fires PanelOptionsChangedEvent which we subscribe to above
     this.props.panel.updateOptions(options);
```
Comment (dprokop) [inline public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:134]: 👍

File: public/app/features/dashboard/dashgrid/DashboardGrid.tsx [hunk 2]
```diff
@@ -102,26 +102,17 @@ export interface Props {
...
 
   componentDidMount() {
     const { dashboard } = this.props;
-
-    dashboard.on(panelAdded, this.triggerForceUpdate);
-    dashboard.on(panelRemoved, this.triggerForceUpdate);
-    dashboard.on(CoreEvents.repeatsProcessed, this.triggerForceUpdate);
-    dashboard.on(CoreEvents.rowCollapsed, this.triggerForceUpdate);
-    dashboard.on(CoreEvents.rowExpanded, this.triggerForceUpdate);
+    this.eventSubs.add(dashboard.events.subscribe(DashboardPanelsChangedEvent, this.triggerForceUpdate));
```
Comment (dprokop) [inline public/app/features/dashboard/dashgrid/DashboardGrid.tsx:111]: Lovely!

**Review by dprokop — APPROVED** [review]
I think this looks great code-wise. Didn't have a chance to test this yet, adding @ryantxu  as a reviewer to confirm it addresses the issues he has encountered.
