### PR TITLE
Alerting: Don't validate rules on group update if they've only been reordered

### LINKED ISSUE #81840: Can't delete a rule if rules later in the group fails validation
**Bug**

Trying to delete a rule in a group where other rules would fail validation (for instance were querying a now-deleted data source) will fail with a validation error.

**Cause**

There are two parts to this:

1. Because we remove a rule from the group and POST the shortened group to the backend, all rules past the deleted rule have an updated index. When we diff the rules we consider these "updated" and will validate them, even though their relative order remained the same. 
2. The `>` and `<` characters in a math expression are being encoded as UTF-8 escape sequences at some point before being persisted to the database, which means the diff for a rule will always include that expression since the frontend sends the normal ascii characters. 

**Fix**

1. Either check if only the index was updated when deciding whether to validate a rule, or check relative order within the group.
2. Long term we should probably encoding the `>` and `<` characters, in the short term we should decode this string before comparison so the diff will see the same string value.

### PR DESCRIPTION
**Pull request by rwwiv**
**What is this feature?**

This PR ignores the index of a rule for the sake of determining whether to validate the rule on update. 

**Why do we need this feature?**

This lets us delete (or add) rules in the middle of a group by not validating rules that were only re-indexed when the group is updated.

**Who is this feature for?**

All alerting users.

**Which issue(s) does this PR fix?**:

Fixes #81840

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/services/ngalert/api/api_ruler.go [hunk 1]
```diff
@@ -500,6 +503,9 @@ func validateQueries(ctx context.Context, groupChanges *store.GroupDelta, valida
 	}
 	if len(groupChanges.Update) > 0 {
 		for _, upd := range groupChanges.Update {
+			if !shouldValidate(upd) {
+				continue
+			}
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/api/api_ruler.go:508]: Let's do the opposite: validate queries only if `Data` or `Condition` fields changed.

File: pkg/services/ngalert/api/api_ruler.go [hunk 2]
```diff
@@ -509,6 +515,20 @@ func validateQueries(ctx context.Context, groupChanges *store.GroupDelta, valida
...
+	for _, diff := range delta.Diff {
+		diffs[diff.Path] = true
+	}
+	for _, field := range ignoreFieldsForValidate {
+		delete(diffs, field)
+	}
+
+	// TODO: consider also checking if rule will be paused after the update
+	return len(diffs) > 0
+}
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/api/api_ruler.go:530]: As far as I understand, shouldValidate always returns `true` unless all delta.Diff are supposed to be ignored. Therefore, I think this can be simpler and I bit more straightforward

```suggestion
func shouldValidate(delta store.RuleDelta) bool {
	for _, diff := range delta.Diff {
		if !slices.Contains(ignoreFieldsForValidate, diff.Path) {
			return false
		}
	}
	return true
}
```

this will exit as soon as diff path is not ignored.

Comment (yuri-tceretian) [reply pkg/services/ngalert/api/api_ruler.go]: I can't think of any real examples that would be past O(N+1) in the worst case.

**Review by yuri-tceretian — APPROVED** [review]
LGTM

File: pkg/services/ngalert/api/api_ruler.go (hunk 2 above)
Comment (yuri-tceretian) [reply pkg/services/ngalert/api/api_ruler.go]: oh, dumb me... actually, hypothetical complexity is M*N, but in reality it's just O(2).
