### PR TITLE
CLI: Return error and aborts when plugin file extraction fails

### LINKED ISSUE #20841: grafana-cli reports false positive when failing to re-install plugin while running
**What happened**:
When trying to upgrade the installed grafana-image-renderer plugin with `grafana-cli` and a custom pluginUrl (unsure if the latter part is relevant) while running Grafana with a previous version of the same plugin, the installation fails due to file being busy but reports successful installation.

**What you expected to happen**:
Either the plugin is successfully installed in the background and applied on next restart of Grafana or the installation is correctly marked as a failure.

**How to reproduce it (as minimally and precisely as possible)**:
On a fresh installation of Grafana 6.5.1 on Ubuntu 19.10 (installed via the repo as per the instructions on https://grafana.com/docs/installation/debian/ ),  I ran this in the command-line:

1. Install plugin
```
root@grafana-lb-test:~# systemctl start grafana-server
root@grafana-lb-test:~# grafana-cli --pluginUrl https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-linux-x64-glibc.zip plugins install grafana-image-renderer
installing grafana-image-renderer @
from: https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-linux-x64-glibc.zip
into: /var/lib/grafana/plugins

✔ Installed grafana-image-renderer successfully

Restart grafana after installing plugins . <service grafana-server restart>
root@grafana-lb-test:~# systemctl restart grafana-server
```

2. Re-install plugin live (failure + false positive)
```
root@grafana-lb-test:~# grafana-cli --pluginUrl https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-linux-x64-glibc.zip plugins install grafana-image-renderer
installing grafana-image-renderer @
from: https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-linux-x64-glibc.zip
into: /var/lib/grafana/plugins

Failed to extract file: Failed to open file: open /var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64: text file busy
✔ Installed grafana-image-renderer successfully

Restart grafana after installing plugins . <service grafana-server restart>
```

The fourth line to the end indicates a failure, but the third line to the end claims successful installation. Stopping Grafana and then installing seems to fix the problem:

**Workaround**:

3. Re-install plugin while stopped (successful)
```
root@grafana-lb-test:~# systemctl stop grafana-server
root@grafana-lb-test:~# grafana-cli --pluginUrl https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-linux-x64-glibc.zip plugins install grafana-image-renderer
installing grafana-image-renderer @
from: https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-linux-x64-glibc.zip
into: /var/lib/grafana/plugins

✔ Installed grafana-image-renderer successfully

Restart grafana after installing plugins . <service grafana-server restart>
```

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: N/A
- OS Grafana is installed on: Ubuntu 19.10
- User OS & Browser: N/A
- Grafana plugins: grafana-image-renderer
- Others: N/A

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Return error and aborts when plugin file extraction fails. 
If file is in use, a somewhat user-friendly message is returned.

**Which issue(s) this PR fixes**:
Fixes #20841 

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/cmd/grafana-cli/commands/install_command.go [hunk 1]
```diff
@@ -241,11 +241,9 @@ func extractFiles(archiveFile string, pluginName string, filePath string, allowS
 					continue
 				}
 			} else {
-
 				err = extractFile(zf, newFile)
 				if err != nil {
-					logger.Errorf("Failed to extract file: %v \n", err)
-					continue
+					return errutil.Wrap("Failed to extract file", err)
```
Comment (marefr) [inline pkg/cmd/grafana-cli/commands/install_command.go]: @aocenas are you aware of any particular reason we don't want to abort installing plugin when extraction fails? Do you see any risk with adding this?

**Review by sakjur — APPROVED** [review]
LGTM

That was fast!

File: pkg/cmd/grafana-cli/commands/install_command.go (hunk 1 above)
Comment (sakjur) [reply pkg/cmd/grafana-cli/commands/install_command.go]: Maybe if we can be semi-successful? We still probably want to abort, but abort entirely rather than partially.

Comment (ryantxu) [reply pkg/cmd/grafana-cli/commands/install_command.go]: Full failure is much better.  Should we also try to delete anything we did extract?  A halfway extracted plugin will just confuse people

Comment (aocenas) [reply pkg/cmd/grafana-cli/commands/install_command.go]: Don't think I made the initial decision for this code so only thing that I see is that this is per file error so it may be better for debugging to collect all the files that have problems with extraction and then show all the errors afterwards and failing hard if there is more than 0 file errors.

**Review by aocenas — APPROVED** [review]
Small comment regarding the error handling but either way this seems like an improvement.

File: pkg/cmd/grafana-cli/commands/install_command.go (hunk 1 above)
Comment (marefr) [reply pkg/cmd/grafana-cli/commands/install_command.go]: @ryantxu that feels like a new issue/PR. Regarding delete anything we did extract. With current solution we would try to delete the failed extracted plugin and/or an existing installed plugin and that operation will also fail if a backend plugin is in use. . 

One thing we need would be to extract all files to a temporary directory to verify extraction was successful, before trying to overwrite an existing installed plugin. Need to create an issue for this.

Highly related to backend plugins moving forward. Will add this to Backend Plugin API Roadmap.

@aocenas Thanks. Will consider collecting all files/problem in enhancement of this, but will merge this fix for now.
