### PR TITLE
BarChart: Fix threshold lines rendering for horizontal orientation

### LINKED ISSUE #73534: Threshold Line has wrong orientation when Bar Chart is horizontal
### What happened?

When a Bar Chart is set to Orientation=horizontal, the Threshold Line orinettaion stays in vertical

**Bar Chart Orientation=horizontal (Threshold Line orientation WRONG)**
Screenshot 2023-08-21 075852

**Bar Chart Orientation=vertical (Threshold Line orientation correct)**
Screenshot 2023-08-21 075902

### What did you expect to happen?

Orientation of Threshold Line follows Orientation of Bar Chart

### Did this work before?

I just started using Grafana

### How do we reproduce it?

1. create Bar Chart
2. add threshold line
3. change orientation of Bar Chart

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 10.0.3 OSS
OS: Ubuntu
Browser: Chrome (Windows and Android)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by gelicia**
**What is this feature?**

There are two main ways to show thresholds in Grafana - either with a line or a filled region in the background. The logic for areas that handled orientations is in `scaleGradient` but lines didn't have an equivalent. Now it does!

**Why do we need this feature?**

So thresholds will display on horizontal bar charts. 

**Which issue(s) does this PR fix?**:

Fixes #73534

**Special notes for your reviewer:**

Random Walk bar chart is all you need to see this. Set the threshold to a value in the data and set the orientation from horizontal to vertical

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by leeoniya — APPROVED** [review]
(pushed a minor tweak to semantics)

LGTM :shipit:

File: packages/grafana-ui/src/components/uPlot/config/UPlotThresholds.ts [hunk 1]
```diff
@@ -58,13 +58,13 @@ export function getThresholdsDrawHook(options: UPlotThresholdOptions) {
         color.setAlpha(0.7);
       }
 
-      const isVertical = u.scales.x ? u.scales.x.ori !== ScaleOrientation.Vertical : true;
+      const isHorizontal = u.scales.x!.ori === ScaleOrientation.Horizontal;
```
Comment (leeoniya) [inline packages/grafana-ui/src/components/uPlot/config/UPlotThresholds.ts:61]: in uPlot land, the chart orientation always follows the x axis.

for BarChart specifically the orientation we show in the UI/toggle follows the bars orientation. yes, it's inverted from the uPlot view of it. but since this code is for a uPlot wrapper, let's stick with the uPlot frame of reference.
