### PR TITLE
Plugins: Check if the user has permissions to access the plugin custom page

### LINKED ISSUE #42121: Plugins: Navigating to a plugin custom page doesn't respect the role attribute
A plugin developer can make use of the `[includes.role]` property in `plugin.json` to limit access to custom pages however the frontend doesn't seem to respect which can result in broken pages:

image

This PR: https://github.com/grafana/grafana/pull/53520 is preventing access when a route is loaded directly, now we need to do the same on the frontend side. The reason is react router being used directly in the app plugins and so far are not defining any protected routes based on plugin.json config.

### PR DESCRIPTION
**Pull request by Ukochka**
**What is this feature?**
Checks if the user has access to plugin custom page. 

**Why do we need this feature?**
Plugin developer can configure access to plugin or different access to different pages in the plugin at package.json. If the user does not have access our frontend does not show plugin in the navigation, but gives access to the plugin via direct link to decide what can be shown. 

**Who is this feature for?**
Plugin developers who configure different access levels for plugins

**Which issue(s) does this PR fix?**:
Fixes #42121

### CODE REVIEW

File: public/app/features/plugins/components/AppRootPage.tsx [hunk 1]
```diff
@@ -81,16 +82,56 @@ export function AppRootPage({ pluginId, pluginNavSection }: Props) {
...
+      return true;
+    }
+    let rolesMap = new Map();
+    plugin.meta?.includes.map((include) => {
+      rolesMap.set(include.path, include.role);
+    });
+    if (contextSrv.isGrafanaAdmin) {
+      return true;
+    }
+    if (contextSrv.isEditor && rolesMap.get(path) === 'Viewer') {
```
Comment (academo) [inline public/app/features/plugins/components/AppRootPage.tsx:98]: We should not use a hardcoded value such as this for this check.

File: public/app/features/plugins/components/AppRootPage.tsx [hunk 2]
```diff
@@ -81,16 +82,56 @@ export function AppRootPage({ pluginId, pluginNavSection }: Props) {
     />
   );
 
+  // Because of the fallback at plugin routes, we need to check
+  // if the user has permissions to see the plugin page.
+  const userHasPermissionsToPluginPage = (path: string) => {
+    if (!plugin.meta?.includes) {
+      return true;
+    }
+    let rolesMap = new Map();
```
Comment (academo) [inline public/app/features/plugins/components/AppRootPage.tsx:91]: It seems like this logic can work without this map here. Perhaps you can use this same loop to check for what you need?

File: public/app/features/plugins/components/AppRootPage.tsx [hunk 3]
```diff
@@ -81,16 +82,56 @@ export function AppRootPage({ pluginId, pluginNavSection }: Props) {
...
+    if (contextSrv.isEditor && rolesMap.get(path) === 'Viewer') {
+      return true;
+    }
+    return contextSrv.hasRole(rolesMap.get(path));
+  };
+
+  const AccessDenied = () => {
+    return (
+      <Alert severity="warning" title="Access denied">
+        You do not have permission to see this plugin.
```
Comment (academo) [inline public/app/features/plugins/components/AppRootPage.tsx:107]: A better message can be `You do not have permission to see this page.`.

File: public/app/features/plugins/components/AppRootPage.tsx [hunk 4]
```diff
@@ -81,16 +82,56 @@ export function AppRootPage({ pluginId, pluginNavSection }: Props) {
...
+      </Alert>
+    );
+  };
   if (!pluginNav) {
-    return <PluginPageContext.Provider value={context}>{pluginRoot}</PluginPageContext.Provider>;
+    return (
+      <>
```
Comment (academo) [inline public/app/features/plugins/components/AppRootPage.tsx:113]: we might not need this fragment

File: public/app/features/plugins/components/AppRootPage.tsx [hunk 5]
```diff
@@ -81,16 +82,56 @@ export function AppRootPage({ pluginId, pluginNavSection }: Props) {
...
+    if (!plugin.meta?.includes) {
+      return true;
+    }
+    let rolesMap = new Map();
+    plugin.meta?.includes.map((include) => {
+      rolesMap.set(include.path, include.role);
+    });
+    if (contextSrv.isGrafanaAdmin) {
+      return true;
+    }
```
Comment (leventebalogh) [inline public/app/features/plugins/components/AppRootPage.tsx:97]: I think this `isGrafanaAdmin` check could go to the top of the function (if it's an admin we don't need to perform any other logic).

File: public/app/features/plugins/components/AppRootPage.tsx [hunk 6]
```diff
@@ -81,16 +82,56 @@ export function AppRootPage({ pluginId, pluginNavSection }: Props) {
...
-        </Page>
+        <>
+          {userHasPermissionsToPluginPage(pluginRoot.props.path) ? (
+            <Page navModel={navModel} pageNav={pluginNav?.node}>
+              <Page.Contents isLoading={loading}>{pluginRoot}</Page.Contents>
+            </Page>
+          ) : (
+            <AccessDenied />
+          )}
+        </>
```
Comment (leventebalogh) [inline public/app/features/plugins/components/AppRootPage.tsx:134]: I am afraid that this will only block access in case there is no `navModel`, otherwise it will render `<Page>{pluginRoot}</Page>` even if the user has no access. Am I correct?

**Review by leventebalogh — COMMENTED** [review]
Nice work @Ukochka 👏 

I think if we are taking this approach (limiting based on role in the `AppRootPage`), then we should add some tests to the `AppRootPage.test.tsx` that covers this new logic. Let me know if you need any help with it.

File: public/app/features/plugins/components/AppRootPage.test.tsx [hunk 7]
```diff
@@ -72,13 +73,13 @@ function renderUnderRouter() {
...
   } as unknown as RouteDescriptor;
-  locationService.push('/a/my-awesome-plugin');
+  locationService.push(`/a/my-awesome-plugin/${page}`);
 
   render(
     <Router history={locationService.getHistory()}>
       <Provider store={store}>
         <GrafanaContext.Provider value={getGrafanaContextMock()}>
-          <Route path="/a/:pluginId" exact render={(props) => <GrafanaRoute {...props} route={route} />} />
+          <Route path={`/a/:pluginId/${page}`} exact render={(props) => <GrafanaRoute {...props} route={route} />} />
```
Comment (academo) [inline public/app/features/plugins/components/AppRootPage.test.tsx:82]: Is it really necessary to modify an existing test? You are adding a trailing slash here and I wonder if this is somehow changing the way it used to work.

File: public/app/features/plugins/components/AppRootPage.test.tsx [hunk 8]
```diff
@@ -43,7 +44,7 @@ class RootComponent extends Component<AppRootProps> {
   }
 }
 
-function renderUnderRouter() {
+function renderUnderRouter(page: string | undefined) {
```
Comment (academo) [inline public/app/features/plugins/components/AppRootPage.test.tsx:47]: you can mark this parameter as optional `function renderUnderRouter(page?: string) {`

And you won't have to modify the call in line 118 to pass an empty string.

File: public/app/features/plugins/components/AppRootPage.test.tsx [hunk 9]
```diff
@@ -72,13 +73,13 @@ function renderUnderRouter() {
   const route = {
     component: () => <AppRootPage pluginId="my-awesome-plugin" pluginNavSection={appsSection} />,
   } as unknown as RouteDescriptor;
-  locationService.push('/a/my-awesome-plugin');
+  locationService.push(`/a/my-awesome-plugin/${page}`);
```
Comment (academo) [inline public/app/features/plugins/components/AppRootPage.test.tsx:76]: if `$page` is undefined this will print `/a/my-awesome-plugin/undefined`

File: public/app/features/plugins/components/AppRootPage.test.tsx (hunk 7 above)
Comment (Ukochka) [reply public/app/features/plugins/components/AppRootPage.test.tsx:82]: We discussed it with @leventebalogh and this was done to not duplicate the code. About slash seems like it does not. Tests are succesful

File: public/app/features/plugins/components/AppRootPage.test.tsx [hunk 10]
```diff
@@ -95,6 +96,14 @@ describe('AppRootPage', () => {
     id: 'my-awesome-plugin',
     type: PluginType.app,
     enabled: true,
+    includes: [
```
Comment (academo) [inline public/app/features/plugins/components/AppRootPage.test.tsx:99]: could you add additional test cases for `Viewer` and `Admin`?

**Review by academo — COMMENTED** [review]
Great work with the recent changes!

We should add more tests covering different cases that we introduce in the checks:

Viewer trying to access a viewer-only page
Editor trying to access a viewer-only page
Admin trying to access a viewer-only page
[any role] trying to access a page without a defined include
[any role] trying to access a page with  non existing role (user input, maybe the misspelled the role)

File: public/app/features/plugins/components/AppRootPage.test.tsx (hunk 7 above)
Comment (academo) [reply public/app/features/plugins/components/AppRootPage.test.tsx:82]: what about `/a/:pluginId/undefined` ?

File: public/app/features/plugins/components/AppRootPage.test.tsx (hunk 9 above)
Comment (leventebalogh) [reply public/app/features/plugins/components/AppRootPage.test.tsx:76]: This is a good point, we probably should fall back to the default plugin page routes in case page is not defined (and in that case the existing tests would keep testing the entry route without any page).

E.g.:
```typescript
const baseUrl = '/a/my-awesome-plugin';
const url = page ? `${baseUrl}/${page}` : baseUrl;

const baseRoute = '/a/:pluginId';
const route = page ? `${baseRoute}/${page}` : baseRoute;
```

File: public/app/features/plugins/components/AppRootPage.test.tsx (hunk 7 above)
Comment (leventebalogh) [reply public/app/features/plugins/components/AppRootPage.test.tsx:82]: I think Esteban is raising a valid point here, we should probably also cater for the previous scenario, where we are testing if there is no page set ("entry page"). It is a good thing to improve the `renderUnderRouter()` so it can cater for sub-pages, too, but probably in a way where it also serves the previous scenarios.

(Maybe I said something confusing during the pairing, in that case sorry.)

**Comment by Ukochka** [comment]
Additional tests were added, thanks @leventebalogh for help!

File: public/app/features/plugins/components/AppRootPage.test.tsx [hunk 11]
```diff
@@ -106,23 +111,150 @@ describe('AppRootPage', () => {
...
+      getPluginSettingsMock.mockResolvedValue(pluginMetaWithIncludes);
+
+      const plugin = new AppPlugin();
+      plugin.meta = pluginMetaWithIncludes;
+      plugin.root = RootComponent;
+
+      importAppPluginMock.mockResolvedValue(plugin);
+    });
+
+    it('an User with no existing role should be able to see any page', async () => {
```
Comment (academo) [inline public/app/features/plugins/components/AppRootPage.test.tsx:174]: Should this be `an User with no existing role should NOT be able to see any page` ?

**Review by academo — APPROVED** [review]
Excellent work on this @Ukochka.

I left a small question of a test that might have the wrong title.

File: public/app/features/plugins/components/AppRootPage.test.tsx (hunk 11 above)
Comment (Ukochka) [reply public/app/features/plugins/components/AppRootPage.test.tsx]: you are right!

**Review by leventebalogh — APPROVED** [review]
Nice one! 🥇
