### PR TITLE
Prometheus: Query builder label filters dropdown UI overload fix

### LINKED ISSUE #58089: Prometheus: label filters select crashing UI for high cardinality instances
Video:
https://user-images.githubusercontent.com/109082771/199554747-ff7a81c4-d68f-40dc-8c28-4b644729f293.mov

**What happened**:
When trying to shove 100k+ labels into the filter dropdowns the UI crashes.

**What you expected to happen**:
UI doesn't crash, only a subset of the results are returned, and I can use the auto-complete functionality to search for options that aren't initially rendered. 

**How to reproduce it (as minimally and precisely as possible)**:
On high cardinality prometheus instance select __name__ as label filter label. When opening the value dropdown afterwards the UI will freeze as it attempts to populate too many items into the DOM.

**Anything else we need to know?**:

**Environment**:
- Grafana version: main/9.2.3
- Data source type & version: Prometheus 1.18/2.28/latest
- OS Grafana is installed on: OS X/Hosted Grafana
- User OS & Browser: All
- Grafana plugins: N/A
- Others: Requires high cardinality prometheus instance to reproduce

### PR DESCRIPTION
**Pull request by gtk-grafana**
**What is this feature?**

Updates query builder label value select component to use AsyncSelect, and query the prometheus API for autocomplete results.

**Why do we need this feature?**
Stops query builder from crashing the browser for high cardinality prometheus instances.

**Who is this feature for?**
Users with lots of metrics.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/58089

**Special notes for your reviewer**:
If you don't have a prometheus instance with a huge volume of values, don't select a metric, and select `__name__` as the label name, this will dump all your metrics into the label value dropdown this PR updates. I tested this new input with over 1 million records and everything in the UI was functional.
Make sure to test variable interpolation, regex in the label values input, for both new and old prometheus client versions.

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/querybuilder/components/PromQueryBuilder.tsx [hunk 1]
```diff
@@ -83,43 +84,89 @@ export const PromQueryBuilder = React.memo<Props>((props) => {
...
   };
 
+  const getLabelValuesAutocompleteSuggestions = (
+    queryString?: string,
+    labelName?: string
+  ): Promise<SelectableValue[]> => {
+    const forLabel = {
+      label: labelName ?? '__name__',
+      op: '=~',
+      value: regexifyLabelValuesQueryString(`${queryString}`),
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/querybuilder/components/PromQueryBuilder.tsx:94]: Ok, so I've been worried about calling this function for this field (this function removes any whitespace in the queries text and adds a wildcard selector) allows users to enter in their own regex. The argument for keeping it is that whitespace is never valid in a label name or value, so whenever the user enters a whitespace char they won't get back a valid query. But is there any regex query that could be executed that contains whitespace that we don't want broken up? Whitespace is just used to match whitespace, so again my argument is that this should be safe, but I want more confidence.

File: .betterer.results [hunk 2]
```diff
@@ -6668,6 +6668,9 @@ exports[`better eslint`] = {
       [0, 0, 0, "Do not use any type assertions.", "0"],
       [0, 0, 0, "Unexpected any. Specify a different type.", "1"]
     ],
+    "public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.tsx:5381": [
```
Comment (gtk-grafana) [inline .betterer.results:6671]: I would love to find a way around these...

File: public/app/plugins/datasource/prometheus/querybuilder/components/PromQueryBuilder.tsx [hunk 3]
```diff
@@ -83,43 +84,89 @@ export const PromQueryBuilder = React.memo<Props>((props) => {
...
+
+    let response;
+    if (datasource.hasLabelsMatchAPISupport()) {
+      response = getLabelValuesFromLabelValuesAPI(forLabel, expr);
+    } else {
+      response = getLabelValuesFromSeriesAPI(forLabel, expr);
+    }
+
+    return response.then((response: SelectableValue[]) => {
+      if (response.length > PROMETHEUS_QUERY_BUILDER_MAX_RESULTS) {
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/querybuilder/components/PromQueryBuilder.tsx:111]: We're doing this little splice all over the place, do we want a helper function to clean these up?

Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/querybuilder/components/PromQueryBuilder.tsx:111]: Great idea Galen, but maybe we tackle that and the types in a follow up PR?

File: public/app/plugins/datasource/prometheus/querybuilder/shared/parsingUtils.ts [hunk 4]
```diff
@@ -200,3 +200,11 @@ function jsonToText(
 function nodeToString(expr: string, node: SyntaxNode) {
   return node.name + ': ' + getString(expr, node);
 }
+
+/**
+ * There aren't any spaces in the metric names, so let's introduce a wildcard into the regex for each space to better facilitate a fuzzy search
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/querybuilder/shared/parsingUtils.ts:205]: So this is true for metric names, are we **certain** this is the case for label values, which is a field that accepts regex as valid input?

File: public/app/plugins/datasource/prometheus/querybuilder/components/PromQueryBuilder.tsx (hunk 3 above)
Comment (leeoniya) [reply public/app/plugins/datasource/prometheus/querybuilder/components/PromQueryBuilder.tsx:111]: :rofl:

File: public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilterItem.tsx [hunk 5]
```diff
@@ -0,0 +1,162 @@
...
+    return [];
+  };
+
+  const labelValueSearch = debounce((query: string) => getLabelValuesAutofillSuggestions(query, item.label), 350);
+
+  return (
+    <div data-testid="prometheus-dimensions-filter-item">
+      <InputGroup>
+        {/* Label name select, loads all values at once */}
+        <Select
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilterItem.tsx:62]: I tried to figure out how to call the API for label names with regex match and failed. I'll need to look into this more in another PR/issue.

File: public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilterItem.tsx [hunk 6]
```diff
@@ -0,0 +1,162 @@
+import debounce from 'debounce-promise';
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilterItem.tsx:1]: Ok, splitting this component for Loki and Prometheus: I'm ambivalent about this change, I don't like the duplication of the formatting functions, but this seemed like a good way not to break stuff. 
The actual diff from the original file is quite small, this is nearly identical to the [original](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/querybuilder/shared/LabelFilterItem.tsx), but this has a new function prop  (`getLabelValuesAutofillSuggestions`) that takes the current auto-complete string and returns potential matches. 

If the Loki maintainers decide that they also want to facilitate the auto-complete via the backend API, then we could go back to using a shared component?

File: public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.test.tsx [hunk 7]
```diff
@@ -0,0 +1,133 @@
+import { render, screen } from '@testing-library/react';
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.test.tsx:1]: These tests are copy paste as well from the shared. Can we add some test coverage for the new functionality?

File: public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.tsx [hunk 8]
```diff
@@ -0,0 +1,81 @@
+import { isEqual } from 'lodash';
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.tsx:1]: These are identical except for a single property: https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/querybuilder/shared/LabelFilters.tsx. 
😢

File: public/app/plugins/datasource/prometheus/querybuilder/components/PromQueryBuilder.tsx [hunk 9]
```diff
@@ -83,43 +84,95 @@ export const PromQueryBuilder = React.memo<Props>((props) => {
...
+      label: labelName ?? '__name__',
+      op: '=~',
+      value: regexifyLabelValuesQueryString(`${queryString}`),
+    };
+    const labelsToConsider = query.labels.filter((x) => x.label !== forLabel.label);
+    labelsToConsider.push(forLabel);
+    if (query.metric) {
+      labelsToConsider.push({ label: '__name__', op: '=', value: query.metric });
+    }
+    console.log('labelsToConsider', labelsToConsider);
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/querybuilder/components/PromQueryBuilder.tsx:101]: ahem

File: public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.test.tsx (hunk 7 above)
Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.test.tsx:1]: I tried and mocking the autocomplete functionality in these components was not trivial, could we follow up with adding some e2e tests on this behavior?

Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.test.tsx:1]: Uck, I'd like to get some more test coverage on this, how about testing the updated variable interpolation in the PromQueryBuilder.test.tsx?

File: public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilterItem.tsx (hunk 6 above)
Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilterItem.tsx:1]: Created here: https://github.com/grafana/grafana/issues/58375

File: public/app/plugins/datasource/prometheus/querybuilder/components/PromQueryBuilder.tsx (hunk 3 above)
Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/querybuilder/components/PromQueryBuilder.tsx:115]: Added in #58375: https://github.com/grafana/grafana/issues/58375#issuecomment-1306158748

File: .betterer.results (hunk 2 above)
Comment (gtk-grafana) [reply .betterer.results:6671]: TODO in https://github.com/grafana/grafana/issues/58375, unless someone else can find a way that doesn't refactor a bunch of external files.

File: public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.tsx [hunk 10]
```diff
@@ -0,0 +1,81 @@
...
+        label="Label filters"
+        error={MISSING_LABEL_FILTER_ERROR_MESSAGE}
+        invalid={labelFilterRequired && !hasLabelFilter}
+      >
+        <EditorList
+          items={items}
+          onChange={onLabelsChange}
+          renderItem={(item, onChangeItem, onDelete) => (
+            <LabelFilterItem
+              item={item as QueryBuilderLabelFilter}
```
Comment (joshhunt) [inline public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.tsx:66]: As a new item is created, all its properties will initially be empty.

This is a source of bugs here - if you call `item.label.indexOf()` in `<LabelFilterItem />` you'll crash because it didn't expect `item.label` to be undefined.

Comment (joshhunt) [reply public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.tsx:66]: `<LabelFilterItem />` should accept item will all it's properties being nullable (`Partial<>`), or, set defaults in here before passing it in.

File: .betterer.results (hunk 2 above)
Comment (joshhunt) [reply .betterer.results:6671]: use [eslint ignore comments](https://raintank-corp.slack.com/archives/CHKLEJ668/p1667489134866859) instead of a betterer exception so the debt is apparent where it is

**Comment by bohandley** [comment]
LGTM for interpolated variables for old and new versions but I found one difference:

Previous label filters autocomplete for values that contain the regex anywhere in the label value
Screen Shot 2022-11-07 at 4 33 35 PM

while this branch only autocompletes for values that start with the regex.
contains
Screen Shot 2022-11-07 at 4 37 47 PM

starts with: 
Screen Shot 2022-11-07 at 4 41 10 PM

File: public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.tsx (hunk 10 above)
Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.tsx]: Yeah I thought that I was doing it a favor by removing some of those type assertions in the LabelFilterItem, but I agree that sets a bad expectation that all of the values have already been set. I went back to the pattern from the [original component](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/querybuilder/shared/LabelFilterItem.tsx). 

I spent a bit of time the other day trying to clean up all of the types in these "new" components, but it was looking like it would require some refactor of files not in scope for this PR. But I plan on spending some more time with it in a [follow up PR](https://github.com/grafana/grafana/issues/58375).

**Comment by gtk-grafana** [comment]
@bohandley good catch! 🙇  I updated the regex so we're more closely matching the current UX. Thank you!

**Review by bohandley — APPROVED** [review]
LGTM!

File: .betterer.results (hunk 2 above)
Comment (gtk-grafana) [reply .betterer.results]: @joshhunt I added the eslint-ignore coments, but betterer isn't removing these rules when I run the update?
