### PR TITLE
ExportAsCode: Use layout creator when exporting v1 dashboard as v2

### LINKED ISSUE #115436: V2 : Export v2 dashboard from v1 dashboard loses rows because it uses the wrong serializer
Reported [here](https://raintank-corp.slack.com/archives/C07QVGH37D4/p1765906345650979)

I’ve exported [this bi dashboard](https://bi.grafana-ops.net/goto/df7aggacudslca?orgId=stacks-258275) as v2 and tried importing it in ops [here](https://ops.grafana-ops.net/goto/cf7agtzcxnfnka?orgId=stacks-27821) but I only get the first few panels (the ones outside of rows) nothing below that (the rows with actual data and panels)
I’ve tried exporting as v1 [here](https://ops.grafana-ops.net/goto/df7agvg0781dse?orgId=stacks-27821) and this time and this time I see all the panels, but that means I did not get to pick my data sources so of course I do not get data
I initially thought it could be related to https://github.com/grafana/grafana/pull/115290 but testing the same thing in my instance that’s on instant (with fix) I can replicate the same issue.

### PR DESCRIPTION
**Pull request by harisrozajac**
Alternative to #115457

Fixes https://github.com/grafana/grafana/issues/115436

Please check that:
- [ ] It works as expected from a user's perspective.

### CODE REVIEW

File: public/app/features/dashboard-scene/pages/DashboardScenePageStateManager.ts [hunk 1]
```diff
@@ -106,6 +110,33 @@ interface DashboardScenePageStateManagerLike<T> {
...
+ */
+export function getSceneCreationOptions(
+  loadOptions?: LoadDashboardOptions,
+  meta?: { isSnapshot?: boolean }
+): SceneCreationOptions | undefined {
+  const isReport = loadOptions?.route === DashboardRoutes.Report;
+  const isSnapshot = meta?.isSnapshot ?? false;
+
+  // Don't use v2 layout for reports or snapshots
+  if (isReport || isSnapshot) {
```
Comment (ivanortegaalba) [inline public/app/features/dashboard-scene/pages/DashboardScenePageStateManager.ts]: Should `getSceneCreationOptions` handle the `DashboardRoutes.Template` case? Currently, it only checks for Report and isSnapshot, but templates are not compatible with V2 either.

File: public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts [hunk 2]
```diff
@@ -76,11 +76,53 @@ export interface SaveModelToSceneOptions {
...
+  createLayout?: LayoutCreator;
+  /**
+   * Determines how the dashboard scene is serialized.
+   * @default 'v1'
+   */
+  targetVersion?: 'v1' | 'v2';
+}
+
+// Rows as SceneGridRow within the grid.
+export const createDefaultGridLayout: LayoutCreator = (panels, preload) => {
```
Comment (ivanortegaalba) [inline public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts]: I think we don't need to export it since it is not used outside of this file, right?

**Review by dprokop — APPROVED** [review]
LGTM. Mind I'm approving my own commit, so wait for another approval ;)

**Review by ivanortegaalba — APPROVED** [review]

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/20821576757)
- Version: 12.4.0-20821576757
