### PR TITLE
graph: fix legend decimals precision calculation

### LINKED ISSUE #11792: 4.6.2 -> 5.1.0: Graph, axes unit "none" does not show original decimals precision anymore
### What Grafana version are you using?
grafana_5.1.0_amd64.deb
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
ubuntu.xenial64
### What did you do?
Copied grafana.db from our live system to a separate VM, upgraded to Grafana 5.1.0 to check for issues
### What was the expected result?
To see the same data with the same precision. '1.01' must stay '1.01' in the legend and the tooltip.
### What happened instead?
'1.01' becomes '1' in Grafana 5.1.0

Grafana 4.x:
image

Grafana 5.1.0:
image

Both Axes are configured the same:
image

Here is the full JSON of the panel (Grafana 4.6.2):

```json
{
  "aliasColors": {},
  "bars": false,
  "dashLength": 10,
  "dashes": false,
  "datasource": "$datasource",
  "editable": true,
  "error": false,
  "fill": 1,
  "grid": {},
  "id": 65537,
  "interval": "$inter",
  "legend": {
    "alignAsTable": true,
    "avg": true,
    "current": true,
    "hideEmpty": true,
    "hideZero": true,
    "max": true,
    "min": true,
    "rightSide": true,
    "show": true,
    "total": false,
    "values": true,
    "sortDesc": true,
    "sort": "current"
  },
  "lines": true,
  "linewidth": 1,
  "links": [],
  "nullPointMode": "connected",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "spaceLength": 10,
  "span": 10,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "alias": "$tag_host:$tag_port $tag_env - $col",
      "dsType": "influxdb",
      "groupBy": [
        {
          "params": [
            "$interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "measurement": "redis_used_cpu_sys",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"mem_fragmentation_ratio\") as \"frag\" FROM \"$rp\".\"redis\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(none)",
      "rawQuery": true,
      "refId": "C",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeShift": null,
  "title": "Memory Fragmentation",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "cumulative"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "none",
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "none",
      "logBase": 1,
      "max": null,
      "min": null,
      "show": false
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by alexanderzobnin**
This PR fixes #11792
When extracting decimals calculation algorithm from flot.js I missed this part of the code (that really long function and this part is at the bottom of it, that's why short functions are better):
```js
// we might need an extra decimal since forced
// ticks don't necessarily fit naturally
if (!axis.mode && opts.tickDecimals == null) {
    var extraDec = Math.max(0, -Math.floor(Math.log(axis.delta) / Math.LN10) + 1),
        ts = axis.tickGenerator(axis);

    // only proceed if the tick interval rounded
    // with an extra decimal doesn't give us a
    // zero at end
    if (!(ts.length > 1 && /\..*0$/.test((ts[1] - ts[0]).toFixed(extraDec))))
        axis.tickDecimals = extraDec;
}
```
so decimals will be ussually 
```js
var extraDec = Math.max(0, -Math.floor(Math.log(delta) / Math.LN10) + 1);
```

### CODE REVIEW

**Comment by marefr** [comment]
@alexanderzobnin just tried generating a graph panel on master with some series having values of 1.01, 2.02, 3.33, but it shows 2 decimals as expected when I have unit None and auto for decimals. I must have misunderstood something? Do you have a panel to reproduce the problem that you can share?

**Comment by alexanderzobnin** [comment]
The problem is legend and tooltip should have decimal precision higher than Y axis. I use panel like this:
```json
{
  "aliasColors": {},
  "bars": false,
  "dashLength": 10,
  "dashes": false,
  "datasource": "Prometheus",
  "decimals": null,
  "fill": 1,
  "gridPos": {
    "h": 10,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "id": 2,
  "legend": {
    "alignAsTable": true,
    "avg": true,
    "current": true,
    "max": true,
    "min": true,
    "rightSide": false,
    "show": true,
    "total": false,
    "values": true
  },
  "lines": true,
  "linewidth": 1,
  "nullPointMode": "null",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "spaceLength": 10,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "expr": "avg(rate(node_cpu[1m])*10) by(mode)",
      "format": "time_series",
      "intervalFactor": 1,
      "legendFormat": "{{mode}}",
      "refId": "A",
      "target": ""
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeShift": null,
  "title": "Panel Title",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "none",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  }
}
```
It looks now like 

screen shot 2018-06-05 at 10 50 18

But legend should have 2 decimals at least.

File: public/app/core/utils/ticks.ts [hunk 1]
```diff
@@ -121,12 +121,11 @@ export function getFlotRange(panelMin, panelMax, datamin, datamax) {
  * Calculate tick decimals.
  * Implementation from Flot.
  */
-export function getFlotTickDecimals(data, axis) {
-  let { datamin, datamax } = getDataMinMax(data);
-  let { min, max } = getFlotRange(axis.min, axis.max, datamin, datamax);
-  let noTicks = 3;
-  let tickDecimals, maxDec;
-  let delta = (max - min) / noTicks;
+export function getFlotTickDecimals(data, axis, height) {
```
Comment (marefr) [inline public/app/core/utils/ticks.ts]: Would be really handy for some tests of this function. Having hard times understand what it should do.

**Review by marefr — COMMENTED** [review]
I would expect this graph to have decimals in y axis or have I misunderstood something? The panel is the same as you provided.

image

In your included panel I've modified the query to multiply with 100 instead of 10. Shouldn't y axis and legend have decimals?

image

**Comment by alexanderzobnin** [comment]
@marefr Decimals on Y axis depend on graph height. It's generated by flot.js. But values at legend and tooltip should have greater precision. Anyway, tests are required, agree.

**Comment by marefr** [comment]
Oh right so my second screenshot should have decimals in legend and tooltip - that's what I expected.

**Comment by alexanderzobnin** [comment]
Second screenshot is right, because if you set multiplier to 100 all values are integer and decimals should be 0;

**Comment by marefr** [comment]
No, values are float just like in your panel you included. If I enable 3 decimals for legend I get the following:

image

**Comment by alexanderzobnin** [comment]
@marefr Added more tests for different cases, hope now logic is more clear.

**Comment by marefr** [comment]
I can understand that the height is taken into consideration for calculating decimals for the y axis, but I find it a bit weird that the height is taken into consideration when calculating decimals for the legend. In this example I would suspect the legend to the right to also have decimals, but it's only displays with two decimals when I make the panel really really high - this must be a regressions since https://github.com/grafana/grafana/commit/3cdf0dce562692ad93125ee09bbc51fe7530c3bc#diff-d93fe1310378a95c4a7cd8787b5052fd.

image

**Comment by alexanderzobnin** [comment]
Legend decimals depend on Y axis decimals, so algorithm has to take into consideration panel height. Previously, decimals precision was calculated in flot.js (https://github.com/grafana/grafana/blob/master/public/vendor/flot/jquery.flot.js#L1718). But we extracted this part to make legend independent of flot.js.

**Comment by marefr** [comment]
But has legend decimals always depended on flot.js? Even if this is a new feature, don't you agree that it's weird to take the height of the panel into consideration for rendering the legend values?

**Comment by alexanderzobnin** [comment]
Y axis decimals precision depends on graph height. Legend decimals depends on Y axis decimals, so it  depends on height as well. In this case we're trying to save behaviour of the previous version. Not sure, maybe we can save decimals as a property of GraphCtrl to avoid using graph height.

@torkelo any thoughts on this thread?

**Comment by marefr** [comment]
When you put it like "Legend decimals depends on Y axis decimals" it actually makes a lot more sense in my head.

**Comment by marefr** [comment]
From my perspective and what I know this works as expected, but don't have very good knowledge of these parts of the code and the history.

**Comment by marefr** [comment]
@torkelo could you have a look at these changes? Thanks

**Comment by marefr** [comment]
@torkelo we've decided to merge this since it will make it work better than currently and we can hopefully get some feedback in upcoming beta release.
