### PR TITLE
Visualizations: Stack negative-valued series downwards

### LINKED ISSUE #36151: Stacked negative values do not paint fill in New time series graph panel
**What happened**:
A query which returns negative values using new graph panel
Stacking mode set to normal
Fill opacity set to 100.
No fill is painted

**What you expected to happen**:
Series expected to be filled with colors for each metric

**How to reproduce it (as minimally and precisely as possible)**:
Query a DB for multiple negative series split by a metric
Set stacking mode to normal for query override.
Set fill opacity to 100.

**Anything else we need to know?**:
image
The positive series works as expected but the negative series has no fill

**Environment**:
- Grafana version: 8.0.2
- Data source type & version: Postgres
- OS Grafana is installed on: MacOS
- User OS & Browser: MacS and Chrome
- Grafana plugins: Default new graph panel
- Others:

### PR DESCRIPTION
**Pull request by leeoniya**
This fixes multiple stacking bugs and somewhat modifies existing stacking behavior.

**Special notes for your reviewer**:

This PR removes the ability to control stacking order via sorting the legend table. The stacking order now follows series order, and can be controlled via the [Organize fields transform](https://grafana.com/docs/grafana/latest/panels/reference-transformation-functions/#organize-fields), or by reordering the query. We intend to evaluate additional alternatives, such as adding `stacking.order` config alongside the existing `stacking.mode` and `stacking.group` config options.

The docs should be updated here: https://grafana.com/docs/grafana/latest/panels/working-with-panels/configure-legend/#sort-series

> The sort order affects the positions of the bars in the Bar chart panel ~~as well as the order of stacked series in the Time series and Bar chart panels.~~

Fixes #36151
Fixes https://github.com/grafana/support-escalations/issues/1810

(maybe fixes some others, gotta search)

before/after:

Peek 2022-04-07 00-14

<details><summary>stacking-snafu.json</summary>

```json
{
    "annotations": {
      "list": [
        {
          "builtIn": 1,
          "datasource": {
            "type": "datasource",
            "uid": "grafana"
          },
          "enable": true,
          "hide": true,
          "iconColor": "rgba(0, 211, 255, 1)",
          "name": "Annotations & Alerts",
          "target": {
            "limit": 100,
            "matchAny": false,
            "tags": [],
            "type": "dashboard"
          },
          "type": "dashboard"
        }
      ]
    },
    "editable": true,
    "fiscalYearStartMonth": 0,
    "graphTooltip": 0,
    "id": 137,
    "links": [],
    "liveNow": false,
    "panels": [
      {
        "datasource": {
          "type": "testdata",
          "uid": "PD8C576611E62080A"
        },
        "fieldConfig": {
          "defaults": {
            "color": {
              "mode": "palette-classic"
            },
            "custom": {
              "axisLabel": "",
              "axisPlacement": "auto",
              "barAlignment": 0,
              "drawStyle": "line",
              "fillOpacity": 64,
              "gradientMode": "none",
              "hideFrom": {
                "legend": false,
                "tooltip": false,
                "viz": false
              },
              "lineInterpolation": "linear",
              "lineWidth": 1,
              "pointSize": 5,
              "scaleDistribution": {
                "type": "linear"
              },
              "showPoints": "auto",
              "spanNulls": false,
              "stacking": {
                "group": "A",
                "mode": "none"
              },
              "thresholdsStyle": {
                "mode": "off"
              }
            },
            "mappings": [],
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green",
                  "value": null
                },
                {
                  "color": "red",
                  "value": 80
                }
              ]
            }
          },
          "overrides": [
            {
              "matcher": {
                "id": "byName",
                "options": "B1"
              },
              "properties": [
                {
                  "id": "custom.stacking",
                  "value": {
                    "group": "A",
                    "mode": "normal"
                  }
                }
              ]
            },
            {
              "matcher": {
                "id": "byName",
                "options": "B15"
              },
              "properties": [
                {
                  "id": "custom.stacking",
                  "value": {
                    "group": "A",
                    "mode": "normal"
                  }
                }
              ]
            }
          ]
        },
        "gridPos": {
          "h": 12,
          "w": 12,
          "x": 0,
          "y": 0
        },
        "id": 2,
        "options": {
          "legend": {
            "calcs": [],
            "displayMode": "list",
            "placement": "bottom"
          },
          "tooltip": {
            "mode": "single",
            "sort": "none"
          }
        },
        "targets": [
          {
            "datasource": {
              "type": "testdata",
              "uid": "PD8C576611E62080A"
            },
            "refId": "A"
          }
        ],
        "title": "stack fill override",
        "transformations": [
          {
            "id": "calculateField",
            "options": {
              "alias": "B1",
              "binary": {
                "left": "A-series",
                "operator": "*",
                "reducer": "sum",
                "right": "-1"
              },
              "mode": "binary",
              "reduce": {
                "reducer": "sum"
              }
            }
          },
          {
            "id": "calculateField",
            "options": {
              "alias": "B15",
              "binary": {
                "left": "A-series",
                "operator": "*",
                "reducer": "sum",
                "right": "-1.5"
              },
              "mode": "binary",
              "reduce": {
                "reducer": "sum"
              }
            }
          }
        ],
        "type": "timeseries"
      },
      {
        "datasource": {
          "type": "testdata",
          "uid": "PD8C576611E62080A"
        },
        "fieldConfig": {
          "defaults": {
            "color": {
              "mode": "palette-classic"
            },
            "custom": {
              "axisLabel": "",
              "axisPlacement": "auto",
              "barAlignment": -1,
              "drawStyle": "line",
              "fillOpacity": 50,
              "gradientMode": "hue",
              "hideFrom": {
                "legend": false,
                "tooltip": false,
                "viz": false
              },
              "lineInterpolation": "linear",
              "lineWidth": 1,
              "pointSize": 5,
              "scaleDistribution": {
                "type": "linear"
              },
              "showPoints": "auto",
              "spanNulls": false,
              "stacking": {
                "group": "A",
                "mode": "normal"
              },
              "thresholdsStyle": {
                "mode": "off"
              }
            },
            "mappings": [],
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green",
                  "value": null
                },
                {
                  "color": "red",
                  "value": 80
                }
              ]
            }
          },
          "overrides": []
        },
        "gridPos": {
          "h": 12,
          "w": 12,
          "x": 12,
          "y": 0
        },
        "id": 23763571993,
        "options": {
          "legend": {
            "calcs": [],
            "displayMode": "list",
            "placement": "bottom"
          },
          "tooltip": {
            "mode": "single",
            "sort": "none"
          }
        },
        "targets": [
          {
            "refId": "A",
            "scenarioId": "csv_metric_values",
            "stringInput": "100, 200, -100, -200"
          },
          {
            "hide": false,
            "refId": "B",
            "scenarioId": "csv_metric_values",
            "stringInput": "50, 100, -300, -400"
          }
        ],
        "title": "Stacked (will never work as \"fill between\")",
        "type": "timeseries"
      },
      {
        "datasource": {
          "type": "testdata",
          "uid": "PD8C576611E62080A"
        },
        "fieldConfig": {
          "defaults": {
            "color": {
              "mode": "palette-classic"
            },
            "custom": {
              "axisLabel": "",
              "axisPlacement": "auto",
              "barAlignment": 0,
              "drawStyle": "line",
              "fillOpacity": 20,
              "gradientMode": "none",
              "hideFrom": {
                "legend": false,
                "tooltip": false,
                "viz": false
              },
              "lineInterpolation": "linear",
              "lineWidth": 1,
              "pointSize": 5,
              "scaleDistribution": {
                "type": "linear"
              },
              "showPoints": "auto",
              "spanNulls": false,
              "stacking": {
                "group": "A",
                "mode": "none"
              },
              "thresholdsStyle": {
                "mode": "off"
              }
            },
            "mappings": [],
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green",
                  "value": null
                },
                {
                  "color": "red",
                  "value": 80
                }
              ]
            }
          },
          "overrides": []
        },
        "gridPos": {
          "h": 14,
          "w": 12,
          "x": 0,
          "y": 12
        },
        "id": 23763571996,
        "maxDataPoints": 200,
        "options": {
          "legend": {
            "calcs": [],
            "displayMode": "list",
            "placement": "bottom"
          },
          "tooltip": {
            "mode": "single",
            "sort": "none"
          }
        },
        "targets": [
          {
            "datasource": {
              "type": "testdata",
              "uid": "PD8C576611E62080A"
            },
            "refId": "A",
            "scenarioId": "random_walk",
            "seriesCount": 1,
            "spread": 10,
            "startValue": 60
          },
          {
            "datasource": {
              "type": "testdata",
              "uid": "PD8C576611E62080A"
            },
            "hide": false,
            "refId": "B",
            "scenarioId": "random_walk",
            "spread": 10,
            "startValue": 120
          },
          {
            "datasource": {
              "type": "testdata",
              "uid": "PD8C576611E62080A"
            },
            "hide": false,
            "refId": "C",
            "scenarioId": "random_walk",
            "spread": 10,
            "startValue": -60
          },
          {
            "datasource": {
              "type": "testdata",
              "uid": "PD8C576611E62080A"
            },
            "hide": false,
            "refId": "D",
            "scenarioId": "random_walk",
            "spread": 10,
            "startValue": -120
          }
        ],
        "title": "Unstacked",
        "type": "timeseries"
      },
      {
        "datasource": {
          "type": "datasource",
          "uid": "-- Dashboard --"
        },
        "fieldConfig": {
          "defaults": {
            "color": {
              "mode": "palette-classic"
            },
            "custom": {
              "axisLabel": "",
              "axisPlacement": "auto",
              "barAlignment": 0,
              "drawStyle": "line",
              "fillOpacity": 20,
              "gradientMode": "none",
              "hideFrom": {
                "legend": false,
                "tooltip": false,
                "viz": false
              },
              "lineInterpolation": "linear",
              "lineWidth": 1,
              "pointSize": 5,
              "scaleDistribution": {
                "type": "linear"
              },
              "showPoints": "auto",
              "spanNulls": false,
              "stacking": {
                "group": "A",
                "mode": "normal"
              },
              "thresholdsStyle": {
                "mode": "off"
              }
            },
            "mappings": [],
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green",
                  "value": null
                },
                {
                  "color": "red",
                  "value": 80
                }
              ]
            }
          },
          "overrides": []
        },
        "gridPos": {
          "h": 14,
          "w": 12,
          "x": 12,
          "y": 12
        },
        "id": 23763571995,
        "maxDataPoints": 200,
        "options": {
          "legend": {
            "calcs": [],
            "displayMode": "list",
            "placement": "bottom"
          },
          "tooltip": {
            "mode": "single",
            "sort": "none"
          }
        },
        "targets": [
          {
            "datasource": {
              "type": "datasource",
              "uid": "-- Dashboard --"
            },
            "panelId": 23763571996,
            "refId": "A"
          }
        ],
        "title": "Stacked",
        "type": "timeseries"
      }
    ],
    "refresh": "",
    "schemaVersion": 36,
    "style": "dark",
    "tags": [],
    "templating": {
      "list": []
    },
    "time": {
      "from": "now-6h",
      "to": "now"
    },
    "timepicker": {},
    "timezone": "",
    "title": "Stacking SNAFU",
    "uid": "vzGUtaY7z34",
    "version": 10,
    "weekStart": ""
  }
```
</details>

image

TODO:

- [x] Update BarChart, hook up onStackMeta & cumulative sum callback
- [x] Make a bunch of various stacking gdev dashboard tests (negY, constant, stack groups, percent/normal, positive/negative vals
- [x] Verify i haven't gutted anything that used to be there
- [x] Fix crash in panel edit when switching stacking options

# Release notice breaking change

The change in behavior is that negative-valued series are now stacked downwards from 0 (in their own stacks), rather than downwards from the top of the positive stacks. We now automatically group stacks by Draw style, Line interpolation, and Bar alignment, making it impossible to stack bars on top of lines, or smooth lines on top of stepped lines.

### CODE REVIEW

File: packages/grafana-ui/src/components/uPlot/utils.ts [hunk 1]
```diff
@@ -152,6 +149,196 @@ export function collectStackingGroups(f: Field, groups: Map<string, number[]>, s
...
+        dir: -1 * dir,
+      });
+    }
+  });
+
+  return bands;
+}
+
+// expects an AlignedFrame
+export function getStackingGroups(frame: DataFrame) {
```
Comment (torkelo) [inline packages/grafana-ui/src/components/uPlot/utils.ts:180]: is it possible to write tests for this function? Would help

File: packages/grafana-ui/src/components/uPlot/utils.ts [hunk 2]
```diff
@@ -152,6 +149,196 @@ export function collectStackingGroups(f: Field, groups: Map<string, number[]>, s
...
+    group.series.push(i);
+  });
+
+  console.log(...groups.values());
+
+  return [...groups.values()];
+}
+
+/** @internal */
+export function preparePlotData2(
```
Comment (torkelo) [inline packages/grafana-ui/src/components/uPlot/utils.ts:254]: Tests for this would also be good.

**Review by torkelo — COMMENTED** [review]
nice refactor, would help greatly to understand the logic, and for others to fix bugs in this code (without introducing new bugs) if some of this code had tests

**Comment by leeoniya** [comment]
- made barchart work
- added new stacking gdev dashboard
- ported most tests, might add more. 2 are still failing but not 100% sure they were correct, still need to verify

there's theoretically hundreds of combos of data variations, stacking, grouping, transform and style, options so it's really impossible to actually makes panels and tests for them all.

still crashing for me when switching from stacking mode during panel edit, but works fine after reload. will check tomorrow.

File: packages/grafana-ui/src/components/uPlot/utils.ts (hunk 2 above)
Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/utils.ts:151]: ported most of the tests over from `preparePlotData()`. probably can write a few more for this variant since it does auto-grouping by pos/neg and by rendering style (drawStyle + barAlignment + lineInterpolation)

File: packages/grafana-ui/src/components/uPlot/utils.ts (hunk 1 above)
Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/utils.ts:73]: the updated tests for `preparePlotData2()` depend on this to work properly, so it's covered by association:

```js
expect(preparePlotData2(df, getStackingGroups(df)))
```

do you still prefer to make these more unit-y?

**Comment by torkelo** [comment]
love the new devenv test dashboard!

File: packages/grafana-ui/src/components/uPlot/utils.ts [hunk 3]
```diff
@@ -41,115 +40,219 @@ interface StackMeta {
...
+        : vals.some((v) => v > 0)
+        ? 1
+        : -1;
+
+    let drawStyle = custom.drawStyle;
+    let drawStyle2 =
+      drawStyle === GraphDrawStyle.Bars
+        ? custom.barAlignment
+        : drawStyle === GraphDrawStyle.Line
+        ? custom.lineInterpolation
```
Comment (leeoniya) [inline packages/grafana-ui/src/components/uPlot/utils.ts:128]: this will prevent stacking of line series with different interpolations (e.g. linear + smooth + stepped). and will auto-group stacks based on interpolation, in addition to other things like scaleKey, etc.

generally i think this is the right thing to do in 99% of the cases. we can always relax this later if people present compelling use cases.

**Comment by leeoniya** [comment]
https://github.com/grafana/grafana/pull/47373/commits/a3b43077ecee9ed356d9e222d10ac7b04a607c4b fixes the crash when switching stacking modes.

since we determine & cache `stackingGroups` as part of ConfigBuilder prep, and prepData does the actual stacking using that info, we need to ensure that the order of ops is always:

1. join frames into alignedFrame
2. prepConfig(alignedFrame), which determines and caches stacking groups
3. prepData that applies negY and stacks using `config.getStackingGroups()`

before this change we would run alignedFrame -> prepData, but before the config was possibly re-initialized with new stacking groups.

**Review by dprokop — COMMENTED** [review]
Very good refactor @leeoniya. Few nits and some questions in my review, but overall code is looking good.

@torkelo there is this one significant change we discussed over Slack with @leeoniya, that's about the automatic split of negative stacks. Currently, the pos/neg stacks are combined together resulting in negative stacks not being separated:
image

Changes introduced in the PR separate the negative stack:
image

This will potentially bring "re-ahem-ahem-gressions" ;) to some of the existing panels relying on the current stacking behavior, but me and Leon we believe this is the correct way forward to separate neg/pos stacks automatically. I did a quick research on how popular charting libraries do this, and it's a typical default behavior, the one proposed in this PR. 

I was advocating for having the proposed mechanism a default one and introducing an option for stacking to preserve the current behavior. But the more I think about it the more skeptical I become, mostly because it will complicate the code given the stacking groups being overrides etc. From the data viz perspective I also agree with Leon that the proposed behavior is the one that works best for visualizing stacked data.

We would like to hear some more opinions too :)

If we landed on the decision to auto split neg/pos stacks, be need to add a breaking change notice to this PR

**Comment by torkelo** [comment]
yea, think spliting out the negative series and stacking them separately seem like the right thing to do :+1:

File: packages/grafana-ui/src/components/uPlot/utils.ts [hunk 4]
```diff
@@ -41,115 +40,219 @@ interface StackMeta {
...
+export function preparePlotData2(
+  frame: DataFrame,
+  stackingGroups: StackingGroup[],
+  onStackMeta?: (meta: StackMeta) => void
+) {
+  let data = Array(frame.fields.length) as AlignedData;
+
+  let dataLen = frame.length;
+  let zeroArr = Array(dataLen).fill(0);
+  let accums = Array.from({ length: stackingGroups.length }, () => zeroArr.slice());
```
[the remark this answers is not in the document]
Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/utils.ts:160]: don't do it for huge arrays (except in tests), since it does a callback for each element ;)

File: packages/grafana-ui/src/components/uPlot/utils.ts [hunk 5]
```diff
@@ -41,115 +40,219 @@ interface StackMeta {
...
+      let stacked = data[i];
+
+      for (let i = 0; i < dataLen; i++) {
+        let v = stacked[i];
+
+        if (v != null) {
+          // v / accum will always be pos, so properly (re)sign by group stacking dir
+          stacked[i] = group.dir * (v / accum[i]);
+        }
+      }
```
[the remark this answers is not in the document]
Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/utils.ts:251]:
```js
let accum = accums[stackIdx];
```

assumes that we have already summed all series in each stacking group in the previous loop.

File: packages/grafana-ui/src/components/uPlot/utils.ts [hunk 6]
```diff
@@ -41,115 +40,219 @@ interface StackMeta {
...
+  stackingGroups: StackingGroup[],
+  onStackMeta?: (meta: StackMeta) => void
+) {
+  let data = Array(frame.fields.length) as AlignedData;
+
+  let dataLen = frame.length;
+  let zeroArr = Array(dataLen).fill(0);
+  let accums = Array.from({ length: stackingGroups.length }, () => zeroArr.slice());
+
+  frame.fields.forEach((field, i) => {
```
[the remark this answers is not in the document]
Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/utils.ts:162]: the `for` vs `forEach` perf difference only becomes significant for thousands+ of iterations. it would just be noise for anything below 100 and only during setData(), rather than mousemove or resize. if we have 100 fields to deal with, this loop will be the least of our problems. :rofl:

File: packages/grafana-ui/src/components/uPlot/utils.ts [hunk 7]
```diff
@@ -41,115 +40,219 @@ interface StackMeta {
...
+        ? vals[0] > 0
+          ? 1
+          : -1
+        : transform === GraphTransform.NegativeY
+        ? vals.some((v) => v > 0)
+          ? -1
+          : 1
+        : vals.some((v) => v > 0)
+        ? 1
+        : -1;
```
[the remark this answers is not in the document]
Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/utils.ts]: done

File: packages/grafana-ui/src/components/uPlot/utils.ts (hunk 1 above)
Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/utils.ts:80]: added some tests

File: packages/grafana-ui/src/components/uPlot/utils.ts (hunk 2 above)
Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/utils.ts:158]: i think the additional behavior is now quasi-covered by the `getStackingGroups()` tests

**Comment by leeoniya** [comment]
searched open stacking issues...

Maybe fixes:

- #39740

Since this PR removes support for stacking order being dynamically dependent on legend calcs sort order, we should probably close these issues:

- #43537
- #40874

**Comment by ryantxu** [comment]
@sdboyer -- any hints on how to get this to pass cue validation?  The sample dashboard fails with:
```
 Family.lineages.0.0.panels.11: 3 errors in empty disjunction:
                Family.lineages.0.0.panels.11.datasource: conflicting values string and {type:"datasource",uid:"-- Dashboard --"} (mismatched types string and struct):
                    ../../../devenv/dev-dashboards/panel-graph/graph-ng-stacking2.json:1:1
                    ../../../devenv/dev-dashboards/panel-graph/graph-ng-stacking2.json:1127:21
                    /packages/grafana-schema/src/scuemata/dashboard/dashboard.cue:337:34
                Family.lineages.0.0.panels.11.fieldConfig.defaults.thresholds.steps.0.value: conflicting values null and number (mismatched types null and number):
                    ../../../devenv/dev-dashboards/panel-graph/graph-ng-stacking2.json:1159:26
 ```
I am not totally sure how to bring that into sync beyond just faking the scheme version

**Comment by dprokop** [comment]
@leeoniya Think we need to add release notes about this breaking change similar to how it is done in i.e. this PR: https://github.com/grafana/grafana/pull/45438

**Review by dprokop — APPROVED** [review]
What can I say, awesome work on this! 🚀
