### PR TITLE
Folders: Make `listFolders` call correct API and fix tags sorting

### LINKED ISSUE #114036: Migrate `listFolders` method to use app platform
https://github.com/grafana/grafana/blob/7888f19443b6c3c6cc0dd5c5ff16b9f78694b9fa/public/app/features/browse-dashboards/api/services.ts#L14-L43

The `listFolders` method is still hardcoded to use the legacy folders API endpoint. It should be updated to use app platform or legacy, depending on feature toggles

### PR DESCRIPTION
**Pull request by tomratcliffe**
**What is this feature?**
* Fixes the api used for `listFolders` - makes this use `grafanaSearcher`
* ~Removes one additional API call to legacy endpoint when calling for a virtual folder (we don't need to call for this if it's `general` or `sharedwithme`, I think~ - Edit: Removed this to reduce risk, might not be possible depending on write modes so skipping for now
* Sorts the tags on the response so they are in alphabetical order

**Why do we need this feature?**
So we use the correct API (legacy vs app platform) for listing folders
So tags are sorted from the API response

**Who is this feature for?**
Devs! But should be unchanged for users

**Which issue(s) does this PR fix?**:

Fixes #114036

### CODE REVIEW

File: public/app/api/clients/folder/v1beta1/hooks.ts [hunk 1]
```diff
@@ -162,10 +162,11 @@ export function useGetFolderQueryFacade(uid?: string) {
   const isVirtualFolder = uid && [GENERAL_FOLDER_UID, config.sharedWithMeFolderUID].includes(uid);
   const params = !uid ? skipToken : { name: uid };
 
+  const skipLegacyCall = isVirtualFolder && shouldUseAppPlatformAPI;
   // This may look weird that we call the legacy folder anyway all the time, but the issue is we don't have good API
   // for the access control metadata yet, and so we still take it from the old api.
   // see https://github.com/grafana/identity-access-team/issues/1103
-  const legacyFolderResult = useGetFolderQueryLegacy(uid || skipToken);
+  const legacyFolderResult = useGetFolderQueryLegacy(skipLegacyCall ? skipToken : uid || skipToken);
```
Comment (tomratcliffe) [inline public/app/api/clients/folder/v1beta1/hooks.ts]: @aocenas I don't think we need to call the legacy endpoint if app platform APIs are being used, and we're asking about a virtual folder (general or sharedwithme)

I checked it locally and the permissions/access control info seems to be correct, but what do you think?

File: public/app/features/browse-dashboards/api/services.ts [hunk 2]
```diff
@@ -17,22 +16,24 @@ export async function listFolders(
   page = 1,
   pageSize = PAGE_SIZE
 ): Promise<DashboardViewItem[]> {
-  const backendSrv = getBackendSrv();
+  const results = getGrafanaSearcher();
 
-  // TODO: what to do here for unified search?
```
Comment (tomratcliffe) [inline public/app/features/browse-dashboards/api/services.ts:22]: Answer: This PR!

File: public/app/api/clients/folder/v1beta1/hooks.ts (hunk 1 above)
Comment (aocenas) [reply public/app/api/clients/folder/v1beta1/hooks.ts]: Not sure could have changed but it was very dependant on which dual write mode I were using. Like if you are asking `apis/folders` in dual writer mode >3 I don't think they would return the virtual folder at all.

Comment (tomratcliffe) [reply public/app/api/clients/folder/v1beta1/hooks.ts]: Hm I've been running in 
```
[unified_storage.folders.folder.grafana.app]
dualWriterMode = 5
```
and `/api/folders/general` gives me a response, but I think I'll put this change in a separate PR then if you think it's a risk :+1:

**Review by L-M-K-B — APPROVED** [review]
Checked the code and ran it locally. LGTM! 🚀

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/19539410875)
- Version: 12.4.0-19539410875
