### PR TITLE
InfluxDB: Fix Cannot read property 'length' of undefined in when parsing response

### LINKED ISSUE #31584: InfluxDB: TypeError: Cannot read property 'length' of undefined
**What happened**:
From Sentry (112 times): 
`TypeError: Cannot read property 'length' of undefined`
`at length (core|webpack:///./public/app/plugins/datasource/influxdb/response_parser.ts:5:36)`

### PR DESCRIPTION
**Pull request by ivanahuckova**
The `results.results` has type any which means it can also be `null` or `undefined`. If so, we want to return empty array as parsed results. 

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/31584

### CODE REVIEW

File: public/app/plugins/datasource/influxdb/response_parser.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import _ from 'lodash';
 
 export default class ResponseParser {
   parse(query: string, results: { results: any }) {
-    if (!results || results.results.length === 0) {
+    if (!results?.results || results.results.length === 0) {
```
Comment (ifrost) [inline public/app/plugins/datasource/influxdb/response_parser.ts:5]: Nit: Could also be

```suggestion
    if (!results?.results?.length === 0) {
```

**Review by ifrost — APPROVED** [review]

File: public/app/plugins/datasource/influxdb/response_parser.ts (hunk 1 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/influxdb/response_parser.ts]: 🚀🚀🚀

File: public/app/plugins/datasource/influxdb/response_parser.ts [hunk 2]
```diff
@@ -2,7 +2,7 @@ import _ from 'lodash';
 
 export default class ResponseParser {
   parse(query: string, results: { results: any }) {
-    if (!results || results.results.length === 0) {
+    if (!results?.results?.length === 0) {
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/influxdb/response_parser.ts:5]:
```suggestion
    if (!results || results.results.length === 0) {
```

File: public/app/plugins/datasource/influxdb/response_parser.ts (hunk 1 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/influxdb/response_parser.ts:5]: I had to revert this, cause it can't be  `(!results?.results?.length === 0)` as if the `length === 0`, then it is true, but we have `!` so it would become false. And the other way around, if the `length !== 0` then it if false and `!` makes it ture, which we don't want.
