### PR TITLE
URLParams: Stringify true values as key=true always (fixes issues with variables with true value) 

### LINKED ISSUE #97290: Dashboards: Regression with custom variables in Grafana 11.3.0
### What happened?

Since Grafana 11.3.x the custom variable presents a regression where it thinks it has a space or empty value by default. This makes charts that use such variable for queries break as any chart action (like edit) will update the variable to the empty value.
Image

Image

Video of Grafana 11.3.0:

https://github.com/user-attachments/assets/5bfa39e4-4712-4154-abfe-461a96ec29a1

### What did you expect to happen?

I expect the variable/url param to stay to the one that is set between navigation over the dashboard instead of going blank.

Video of Grafana 11.2.0:

https://github.com/user-attachments/assets/90fe314e-04a9-4dc6-aae1-f2d297a4b548

### Did this work before?

Yes, it is working fine on <11.3  and since 8.4 it had kept the same behavior for me.

### How do we reproduce it?

1. Create a dashboard
2. Add Grafana random walk datasource + chart
3. Add a custom variable with custom options `foo : true, bar : false`
5. Save and navigate to your dashboard and then open the chart in edit mode, the variable will be emptied.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Grafana v11.2.0 (2a88694fd3)
OS: Linux
Browser:  
* Chrome Version 109.0.5414.74 (Official Build) (64-bit)
* Firefox 133.0 (64-bit)

### Grafana platform?

Docker

### Datasource(s)?

_No response_

### LINKED ISSUE #106366: Dashboards: Template variables reset to empty during inspection
### What happened?

When selecting a specific value for template variables in a Grafana dashboard, instead of the default All value, and then using the "Inspect" feature on a table panel, the selected variable resets to an empty value. This causes SQL queries that depend on this variable to malfunction, as they receive no value.

### What did you expect to happen?

The selected template variable should retain its value when using the "Inspect" feature, allowing dependent SQL queries to execute without errors.

### Did this work before?

Yes, this worked correctly in Grafana v11.2.2

### How do we reproduce it?

1. Select a specific value (e.g., true) for a template variable in a dashboard.
2. Observe the URL for the GET parameter, confirming it is correctly set (e.g., &var-is_active=true).
3. In the table panel, click on the three dots menu in the upper right corner and choose "Inspect" or hover over the table and press "i".
4. Notice that the value of the template variable changes to empty, and the URL parameter shows &var-is_active.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 12.0.1
OS: macOS
Browser: Chrome v137.0.7151.56

### Grafana platform?

Kubernetes

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by torkelo**
Restore some of the changes from https://github.com/grafana/grafana/pull/97346 (some made no sense), and fix the issues that the changes caused 

Fixes https://github.com/grafana/grafana/issues/97290
Fixes https://github.com/grafana/grafana/issues/106366

### CODE REVIEW

File: public/app/features/panel/panellinks/link_srv.ts [hunk 1]
```diff
@@ -256,18 +256,18 @@ export interface LinkService {
...
     }
 
     if (link.includeVars) {
-      params[`\$${DataLinkBuiltInVars.includeVars}`] = true;
+      url = urlUtil.appendQueryToUrl(url, `\$${DataLinkBuiltInVars.includeVars}`);
     }
 
-    let url = locationUtil.assureBaseUrl(urlUtil.appendQueryToUrl(link.url || '', urlUtil.toUrlParams(params)));
     url = getTemplateSrv().replace(url);
+    url = locationUtil.assureBaseUrl(url);
```
Comment (torkelo) [inline public/app/features/panel/panellinks/link_srv.ts:270]: this is new the new change that was not part of the original PR, that fixes the regression it introduced

**Review by ivanortegaalba — APPROVED** [review]
Good catch! 💯 

Should we backport it @torkelo?

**Review by oscarkilhed — APPROVED** [review]

**Comment by ghost** [comment]
The backport to `release-11.6.7` failed:

```
error cherry-picking: error running git cherry-pick: error running command 'git cherry-pick -x 1564e1bac9b1b7a0c07a9ee7d83988fe0e70998b'
error: exit status 1
stdout: Auto-merging public/app/features/dashboard-scene/sharing/ShareLinkTab.test.tsx
Auto-merging public/app/features/panel/panellinks/link_srv.ts
CONFLICT (content): Merge conflict in public/app/features/panel/panellinks/link_srv.ts

stderr: error: could not apply 1564e1bac9b... URLParams: Stringify true values as key=true always (fixes issues with variables with true value)  (#106440)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"

```

To backport manually, run these commands in your terminal:

```bash
git fetch
git switch --create backport-106440-to-release-11.6.7 origin/release-11.6.7
git cherry-pick -x 1564e1bac9b1b7a0c07a9ee7d83988fe0e70998b
```

Resolve the conflicts, then add the changes and run `git cherry-pick --continue`:

```bash
git add . && git cherry-pick --continue
```

If you have the [GitHub CLI](https://cli.github.com/) installed:

```bash
git push --set-upstream origin backport-106440-to-release-11.6.7
PR_BODY=$(gh pr view 106440 --json body --template 'Backport 1564e1bac9b1b7a0c07a9ee7d83988fe0e70998b from #106440{{ "\n\n---\n\n" }}{{ index . "body" }}')
echo "${PR_BODY}" | gh pr create --title '[release-11.6.7] URLParams: Stringify true values as key=true always (fixes issues with variables with true value) ' --body-file - --label 'backport' --label '' --label 'area/frontend' --label 'add to changelog' --base release-11.6.7 --web
```

Or, if you don't have the GitHub CLI installed ([we recommend you install it!](https://github.com/cli/cli#installation)):

```bash
git push --set-upstream origin backport-106440-to-release-11.6.7
```

And open a pull request where the `base` branch is `release-11.6.7` and the `compare`/`head` branch is `backport-106440-to-release-11.6.7`
