### PR TITLE
BarGauge: Fix so we properly display the "no result" value when query returns empty result

### LINKED ISSUE #21766: Bar Gauge "l is undefined" when no data is returned
**What happened**: If no data is returned, a working bar gauge get's an error "l is undefined":

grafik

If you change the query to something that returns data, the error still persists until the dashboard is reloaded completly.

**What you expected to happen**: It is displayed "No Data" or its value mapping.

**How to reproduce it (as minimally and precisely as possible)**: Select a dashboard with a bar gauge. Show Data in it. Select for example a time interval that does not return any data. See the error. Revert the time interval back to the interval before that error. The error still persists. Reload the dashboard.

**Anything else we need to know?**: No.

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: InfluxDB 1.7.3
- OS Grafana is installed on: Ubuntu 16.04.6 LTS
- User OS & Browser: Windows 10 (1809) & Firefox 72.0.2
- Grafana plugins: Default + TrackMap
- Others: -

### LINKED ISSUE #21911: [BUG][6.6.0] Bar Gauge > ERROR: Cannot read property 'dataFrame' of undefined
**What happened**:
Bar Gauge - error *Cannot read property 'dataFrame' of undefined* 
image

Error not gone out and data not rendered even if SQL Query returns data with another variable or by edit query string

Error  gone out if refresh page by F5

**What you expected to happen**:
Just empty Bar Gauge (no error) and Bar Gauge with data when was selected another variable which returns some data without refresh (F5)

**How to reproduce it (as minimally and precisely as possible)**:
SQL Query with empty data (by edit query or by select variable)

**Anything else we need to know?**:
this errror not gone while refersh page

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: SQL Server
- OS Grafana is installed on: Windows Server 2016
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: Bar Gauge
- Others:

### PR DESCRIPTION
**Pull request by mckn**
Fixes #21766

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]
LGTM -- can we add a test that returns no results?

File: public/app/plugins/panel/bargauge/BarGaugePanel.tsx [hunk 1]
```diff
@@ -88,3 +89,17 @@ export class BarGaugePanel extends PureComponent<PanelProps<BarGaugeOptions>> {
     );
   }
 }
+
+const getDisplay = (view: DataFrameView, colIndex: number): DisplayProcessor => {
```
Comment (ryantxu) [inline public/app/plugins/panel/bargauge/BarGaugePanel.tsx]: actually looking some more....  what do you think about adding:

`getFieldDisplayProcessor(colIndex)` to DataFrameView?

then it could be reused for the other similar cases, and could be called above on line 40 as:
```
display={view?.getFieldDisplayProcessor(colIndex)}
```

Comment (mckn) [reply public/app/plugins/panel/bargauge/BarGaugePanel.tsx]: Yeah, totally agree! Much better! Will do the change.

**Review by torkelo — APPROVED** [review]
LGTM

**Comment by mckn** [comment]
> LGTM

Awesome! Just added a test to verify that this works as expected and to prevent recursion. Please have a look at those as well 🙏

**Review by torkelo — APPROVED** [review]
great!

**Comment by marefr** [comment]
@mckn please change title of PR according to [PR guidelines](https://github.com/grafana/grafana/blob/master/contribute/create-pull-request.md#pull-request-titles) , e.g. `BarGauge: <Description>`. Since this has add to changelog label it will be added to [changelog](https://github.com/grafana/grafana/blob/master/CHANGELOG.md) based on PR title.

**Comment by mckn** [comment]
> @mckn please change title of PR according to [PR guidelines](https://github.com/grafana/grafana/blob/master/contribute/create-pull-request.md#pull-request-titles) , e.g. `BarGauge: <Description>`. Since this has add to changelog label it will be added to [changelog](https://github.com/grafana/grafana/blob/master/CHANGELOG.md) based on PR title.

WDYT? :)

**Comment by marefr** [comment]
Awesome! Thanks
