### PR TITLE
fix for wrong locale and text issues #8840

### LINKED ISSUE #8840: [BUG] text display error in Alertlist plugin
- What Grafana version are you using?
Version 4.2.0 (commit: 349f3eb)

- What datasource are you using?
InfluxDB 1.2.4

- What OS are you running grafana on?
Red Hat Enterprise Linux Server release 6.8

- What did you do?
created Alertlist with 3 Alerts.

- What was the expected result?
Display of configured alerts with times since last state change
example: "OK for 5 hours"

- What happened instead?
On Windows Systems with DE locale browsers (tested with IE 11, Firefox and Chrome) it displays the alerts with time since last state change but part of the text is in german.
example: "OK for vor 5 Stunden"
note the repetition "for" in englisch followed by the german translation "vor"
For some alerts, it displays "OK for in 5 Stunden" which is also wrong.
Everything else in my dashboards is englisch as expected.

### PR DESCRIPTION
**Pull request by wait-io**
fixes https://github.com/grafana/grafana/issues/8840
by setting a default locale. Also uses fromNow(true) to work around the replace.

### CODE REVIEW

File: public/app/plugins/panel/alertlist/module.ts [hunk 1]
```diff
@@ -125,7 +125,7 @@ class AlertListPanel extends PanelCtrl {
       .then(res => {
         this.currentAlerts = this.sortResult(_.map(res, al => {
           al.stateModel = alertDef.getStateDisplayModel(al.state);
-          al.newStateDateAgo = moment(al.newStateDate).fromNow().replace(" ago", "");
+          al.newStateDateAgo = moment(al.newStateDate).locale('en').fromNow(true);
```
Comment (torkelo) [inline public/app/plugins/panel/alertlist/module.ts]: why remove " ago"

Comment (wait-io) [inline public/app/plugins/panel/alertlist/module.ts]: because "fromNow(true)" returns "4 hours" and you don't need to do string replacement.
See https://momentjs.com/docs/#/displaying/fromnow/

Comment (torkelo) [inline public/app/plugins/panel/alertlist/module.ts]: ah , great!
