### PR TITLE
Elasticsearch: Support extended stats and percentiles in terms order by

### LINKED ISSUE #5148: Elasticsearch: Support metric aggregations like Percentiles and extended stats in Order By
**What Grafana version**
3.0.2

**What datasource**
Elasticsearch

**What did you do?**

* Go to http://play.grafana.org/dashboard/db/elasticsearch-metrics?panelId=1&fullscreen&edit
* Edit metric to percentile and set percentiles to 99
* Modify Order By of `@hostname` terms aggregation -> set to `Percentiles @value`
orderbypercentiles

**What was the expected result?**
When only one percentile is entered, the aggregation order path should be set automatically (see error message below). When multiple percentiles are entered, the user should be able to choose one.

**What happenend instead**

```
{
"root_cause": [
{
"type": "aggregation_execution_exception",
"reason": "Invalid terms aggregation order path [1]. When ordering on a multi-value metrics aggregation a metric name must be specified"
}
],
"type": "search_phase_execution_exception",
"reason": "all shards failed",
"phase": "query",
"grouped": true,
"failed_shards": [
{
"shard": 0,
"index": "metrics-2016.05.24",
"node": "Fs1eG42kRquwBzlAS_nB-w",
"reason": {
"type": "aggregation_execution_exception",
"reason": "Invalid terms aggregation order path [1]. When ordering on a multi-value metrics aggregation a metric name must be specified"
}
}
]
}
```

### PR DESCRIPTION
**Pull request by simianhacker**
**What this PR does / why we need it**:

This PR closes #5148 by adding support to the terms aggregation for ordering by percentiles and extended stats. I've added an option to the terms order by dropdown for every extended stats that is enabled AND every percentile percent specified in the settings.   

image

**Which issue(s) this PR fixes**:

Fixes #5148

**Special notes for your reviewer**:

This PR changes the format of the `aggDev.settings.orderBy` from a numeric string that referenced the `target.metrics` index to a numeric string (that references the same index or meric id) but with a bucket path. For example, if the user wants to use a standard deviation from extended stats to order the terms aggregation, the value will be `1[std_deviation]`.  

I've added a helper function `convertOrderByToMetricId(orderBy: string): string | undefined` under `public/app/plugins/elasticsearch/lib` to convert the order by back to the expected index string or metric id.  This helper function is used in two places, `query_builder.ts` for creating the aggregation for sorting and `query_def.ts` for finding the metric and describing the order by.

For accessing `std_deviation_bound.upper` and `std_devation_bound.lower` via bucket paths for the terms `order` key you have to use `std_upper` and `std_lower`. These strings are not documented  on Elastic.co. When the upper and lower bounds were introduced, these keys were created for Kibana and it appears the documentation was overlooked. I'm planning on filing an issue with the Elasticsearch team to get that fixed.

### CODE REVIEW

**Comment by Elfo404** [comment]
ping stale bot, i'm going to pick this up soon :)

**Comment by hhmob** [comment]
Would like to know which version will contain this fix? Thanks!

**Comment by Elfo404** [comment]
@hhmob We commented on a few other PRs but this one slipped through, sorry! We are refactoring the ES datasource now to use React (https://github.com/grafana/grafana/pull/28033), most likely this will be included in 7.4.

**Comment by hhmob** [comment]
> @hhmob We commented on a few other PRs but this one slipped through, sorry! We are refactoring the ES datasource now to use React (#28033), most likely this will be included in 7.4.

Thanks!

**Comment by simianhacker** [comment]
@Elfo404 This has been converted to the new React code base, it's ready for review.

**Comment by hhmob** [comment]
would anyone  make a review?

**Review by Elfo404 — CHANGES_REQUESTED** [review]
on the FE works like a charm and the comments are great! thanks for this!

It doesn't work with alerting tho, the generated query in the go code looks like: 

```json
{"aggs":{"4":{"aggs":{"2":{"aggs":{"3":{"extended_stats":{"field":"@value"}},"5":{"percentiles":{"field":"@value","percents":["25","50","75","95","99"]}}},"date_histogram":{"field":"@timestamp","interval":"200ms","min_doc_count":0,"extended_bounds":{"min":"1608206367998","max":"1608206667998"},"format":"epoch_millis"}}},"terms":{"field":"@hostname","size":1,"order":{"5[99.0]":"desc"}}}},"query":{"bool":{"filter":[{"range":{"@timestamp":{"format":"epoch_millis","gte":"1608206367998","lte":"1608206667998"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"size":0}
```

while the working one generated by the FE query builder looks like:

```json
{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":1608204919321,"lte":1608206719321,"format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"4":{"terms":{"field":"@hostname","size":1,"order":{"5[99.0]":"desc"},"min_doc_count":1},"aggs":{"2":{"date_histogram":{"interval":"10s","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":1608204919321,"max":1608206719321},"format":"epoch_millis"},"aggs":{"3":{"extended_stats":{"field":"@value"}},"5":{"percentiles":{"field":"@value","percents":["25","50","75","95","99"]}}}},"5":{"percentiles":{"field":"@value"}}}}}}
```

seems like the aggregations are being built a bit differently.

**Comment by simianhacker** [comment]
@Elfo404 I believe everything has been address and this is ready for a second review.

**Review by Elfo404 — APPROVED** [review]
LGTM and seems to work as expected, this is great! 🚀

File: pkg/tsdb/elasticsearch/time_series_query.go [hunk 1]
```diff
@@ -242,9 +243,21 @@ func addTermsAgg(aggBuilder es.AggBuilder, bucketAgg *BucketAgg, metrics []*Metr
 		if orderBy, err := bucketAgg.Settings.Get("orderBy").String(); err == nil {
 			a.Order[orderBy] = bucketAgg.Settings.Get("order").MustString("desc")
 
-			if _, err := strconv.Atoi(orderBy); err == nil {
+			/*
+			   The format for extended stats and percentiles is {metricId}[bucket_path]
+			   for everything else it's just {metricId}
+			*/
+			metricIdRegex := regexp.MustCompile(`^(\d+)`)
+			metricIdMatches := metricIdRegex.FindStringSubmatch(orderBy)
```
Comment (wbrowne) [inline pkg/tsdb/elasticsearch/time_series_query.go:251]: Is there any reason why this can't be simplified to `metricId := metricIdRegex.FindString(orderBy)`?

**Review by wbrowne — COMMENTED** [review]
Looking good! Just a small question

File: pkg/tsdb/elasticsearch/time_series_query.go (hunk 1 above)
Comment (simianhacker) [reply pkg/tsdb/elasticsearch/time_series_query.go:251]: Thanks for the suggesting! I will make the change and re-push.

**Comment by marefr** [comment]
We have some devenv dashboards [here](https://github.com/grafana/grafana/tree/master/devenv/dev-dashboards/datasource-elasticsearch) that's convenient to use for validating existing and new features works as expected on different ES versions. Going to try them out and potentially push some updates of the dashboards.

**Review by marefr — CHANGES_REQUESTED** [review]
Only tested frontend changes so far. Pushed an update of devenv elasticsearch comparison dashboard that makes it rather easy to compare/validate different ES versions is supported. Instructions [here](https://github.com/grafana/grafana/tree/master/devenv#developer-dashboards-and-data-sources) for setting up provisioning of data sources and dashboards together with docker compose setups of data sources. For reference:
```
~/go/src/github.com/grafana/grafana on issue-5148-s…-in-order-by                                                                                                                        
❯ make devenv sources=elastic,elastic5,elastic6,elastic7
```

Order by extended stats and percentiles seems to work as expected. Order by `doc count` or `term value` doesn't work (as supported before), see below.

Terms order by Count:
image

Testing on Grafana 7.3.6 (https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1):
Seems to have special handling of `Doc Count` and `Term value` and this needs to be supported to be backward compatible.
image

**Comment by simianhacker** [comment]
@marefr Looks like that is broken in master too.

**Comment by simianhacker** [comment]
Oops... I need to check the Golang code as well.

**Comment by marefr** [comment]
If you could re-request a review from me when this is ready that would be great, thanks

**Review by marefr — APPROVED** [review]
Great. LGTM

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Comment by hhmob** [comment]
Great !!!!
