### PR TITLE
Panels: Use the No value option when showing the no data message

### LINKED ISSUE #47662: The "No Value" box does not override the "No Data" output
**What happened**:
A customer asked me how to override what a panel says when there is no data. Usually it says "No Data" but I found a box in the panel config called "No Value" that sounded like it was for overriding the "No Data" output. I was told that was the correct box but I've never been able to get it to work and the customer was not able to get it to work either. 

It's possible that it's dependent on how you achieve a "No Data" scenario. I tried by changing the name of the metric to one that doesn't exist. That gave me "No Data" immediately but it was never overwritten by the "No Value" field.

Customers words - "I tried editing the “No Value” box with integer, string value and string variable in the panel for Pie Chart Visualization. Also tried with the value mapping options which is next to the “No Value” but still no luck in replacing the no data option."

**What you expected to happen**:
I would expect that whatever I type into "No Value" would show instead of "No Data" in a "No Data" scenario.

**How to reproduce it (as minimally and precisely as possible)**:
1. Choose a Prometheus data source
2. Find a metric that exists and graph it so you know you're in a good state
3. Add "fake" to the end of the metric name so you get a "No Data" output
4. Set the "No Value" field in the panel options section to something other than blank
5. I still see "No Data" instead of whatever I set the "No Value" field to

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.5
- Data source type & version: Prometheus
- OS Grafana is installed on: official Docker image
- User OS & Browser: Chrome on Ubuntu
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #47662

Not 100% this is the right solution / behavior.

But this at least will make the behavior of the other panels behave like Stat/Gauge/BarGauge etc who already use
the No value option like this.

### CODE REVIEW

File: public/app/AppWrapper.tsx [hunk 1]
```diff
@@ -113,6 +113,7 @@ export class AppWrapper extends React.Component<AppWrapperProps, AppWrapperState
                   </div>
                   <LiveConnectionWarning />
                   <ModalRoot />
+                  <PortalContainer />
```
Comment (ryantxu) [inline public/app/AppWrapper.tsx:116]: I think this is an unrelated issue in the same PR?

**Review by ryantxu — APPROVED** [review]
Excluding the "portal" changes, i think this looks good!
