### PR TITLE
Transformations: Fix filterByValue interpolation

### LINKED ISSUE #11207: Locale Format unit Uncaught TypeError
Grafana v4.6.2 (commit: 8db5f08)
CentOS 7.4
InfluxDB 1.4.2

**Steps to reproduce**
1) Create new dashboard with graph panel
2) Apply following changes to panel:
2.1) **Metric:** Input any query (using default InfluxInternal works) using fill(null);
2.2) **Axes:** Use Locale Format for Y axis;
2.3) **Display:** In "Stacking & Null value" select "null" from "Null value" dropdown;
3) Hovering over empty data in graph shows no tooltip and produces `Uncaught TypeError: Cannot read property 'toLocaleString' of null` error on mouse movement.

tested using Chrome

### PR DESCRIPTION
**Pull request by adela-almasan**
Before

filterByValue_before

After

https://github.com/user-attachments/assets/c68c7fdf-f9f5-4d5a-ac0e-12f70ea51b6b

Fixes https://github.com/grafana/support-escalations/issues/11207

**Special notes for your reviewer:**
Relates to https://github.com/grafana/grafana/pull/89418

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: packages/grafana-data/src/transformations/transformers/filterByValue.ts [hunk 1]
```diff
@@ -56,39 +56,40 @@ export const filterByValueTransformer: DataTransformerInfo<FilterByValueTransfor
       interpolatedFilters.push(
         ...filters.map((filter) => {
           if (filter.config.id === ValueMatcherID.between) {
+            let valueFrom = filter.config.options.from;
+            let valueTo = filter.config.options.from;
```
Comment (drew08t) [inline packages/grafana-data/src/transformations/transformers/filterByValue.ts:60]: This supposed to be options.to?

Comment (adela-almasan) [reply packages/grafana-data/src/transformations/transformers/filterByValue.ts:60]: ooops, yes. copy-paste..

**Review by nmarrs — APPROVED** [review]
LGTM ⛳

**Review by baldm0mma — APPROVED** [review]
