### PR TITLE
Alerting: Show disabled provisioned evaluation group

### LINKED ISSUE #69213: error loading alert group in UI when creating new alert via UI
### 
# What went wrong?

**What happened**:

  We have positioned alerts and alert group e.g RWS-DEV

during creating of new alert via ui we wanted to load already existing RWS-DEV alert gourp but it was not loading existing alert groups and if we want to create add new one RWS-DEV it gives following error it can not create RWS-DEV since it is provistioned 

MicrosoftTeams-image (18)

**What did you expect to happen**:

  We expect that already persisted alerts groups are loaded in uI and gave to users as option to be choosen

### 
# How do we reproduce it?

**Step 1**:

Grafana 9.5.2 persist some alerts via file
**Step 2**:

create new alert

**Step 3**:

choose alert group

### 
# What Grafana version are you using?

9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by gillesdemey**
**What is this feature?**

This PR adds provisioned evaluation groups to the dropdown list, disabling them and indicating to the user that those have been provisioned and cannot be selected.

Previously provisioned evaluation groups were hidden from the user and was confusing because there was no visual indication for why they were omitted from the list.

image

**Which issue(s) does this PR fix?**:

Fixes #69213

**Special notes for your reviewer:**

I've found a bug where the `SingleValue` component destructures `isDisabled` and uses that to determine... if it's disabled but we actually pass a `disabled` prop instead of `isDisabled` in `BaseSelect`.

### CODE REVIEW

File: public/app/features/alerting/unified/components/rule-editor/FolderAndGroup.tsx [hunk 1]
```diff
@@ -34,21 +35,29 @@ export const useGetGroupOptionsFromFolder = (folderTitle: string) => {
   const grafanaFolders = useCombinedRuleNamespaces(GRAFANA_RULES_SOURCE_NAME);
   const folderGroups = grafanaFolders.find((f) => f.name === folderTitle)?.groups ?? [];
 
-  const nonProvisionedGroups = folderGroups.filter((g) => {
-    return g.rules.every(
-      (r) => isGrafanaRulerRule(r.rulerRule) && Boolean(r.rulerRule.grafana_alert.provenance) === false
+  // we include provisioned folders, but disable the option to select them
+  const isProvisionedGroup = (group: CombinedRuleGroup) => {
```
Comment (VikaCep) [inline public/app/features/alerting/unified/components/rule-editor/FolderAndGroup.tsx:39]: Should this be wrapped in `useCallback`?

File: packages/grafana-ui/src/components/Select/SelectBase.tsx [hunk 2]
```diff
@@ -357,7 +357,7 @@ export function SelectBase<T>({
             return <DropdownIndicator isOpen={props.selectProps.menuIsOpen} />;
           },
           SingleValue(props: any) {
-            return <SingleValue {...props} disabled={disabled} />;
+            return <SingleValue {...props} isDisabled={disabled} />;
```
Comment (VikaCep) [inline packages/grafana-ui/src/components/Select/SelectBase.tsx:360]: any reason why this was changed?

**Review by VikaCep — APPROVED** [review]
LGTM!

File: packages/grafana-ui/src/components/Select/SelectBase.tsx (hunk 2 above)
Comment (gillesdemey) [reply packages/grafana-ui/src/components/Select/SelectBase.tsx:360]: Yep, `isDisabled` is the prop that is destructured in `SingleValue` to check if the option should be disabled – however we've always been passing `disabled` in to the component instead of `isDisabled`.

The functionality to disable select options seems to have been broken for quite a while.

File: public/app/features/alerting/unified/components/rule-editor/FolderAndGroup.tsx (hunk 1 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/components/rule-editor/FolderAndGroup.tsx:39]: Usually I don't bother unless it's really necessary as a performance optimizations (when the components is re-rendered often).

Good shout-out here though since I believe this function doesn't even need to be in the hook in the first place – I'll move it outside.
