### PR TITLE
Transformations: Fix crash in Config from query results

### LINKED ISSUE #93372: Query Transformation: Crashes when 'Config from query results' -> 'Fields with Values' is selected
### What happened?

I was using a query transformation when reading data from another panel. I selected the 'Config from query results' transformation, selected which query to use, then clicked "Fields with Values" in the dropdown. It immediately crashed and took me to an error page Image

### What did you expect to happen?

I expected to receive further dropdown options

### Did this work before?

I have never tried using this method before

### How do we reproduce it?

1. Make a panel with a datasource query
2. Make another panel, and set the datasource to "Dashboard"
3. Select the  'Config from query results' -> 'Fields with Values' options

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.1.0
OS: MacOS
Browser: Google Chrome

### Grafana platform?

Docker

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by yincongcyincong**
**Which issue(s) does this PR fix?**:

Fixes #93372
when config query is not choosed, choose `apply to` `Fields with Values`. there will be a crash.
 because `options` don't check is undefined or not
image

### CODE REVIEW

**Comment by yincongcyincong** [comment]
@leeoniya could you please look at this pr. thanks

**Comment by yincongcyincong** [comment]
@joshhunt @ashharrison90 could you please look at this pr. thanks

**Comment by yincongcyincong** [comment]
@joshhunt @ashharrison90  could you please look at this pr. thanks

File: packages/grafana-ui/src/components/MatchersUI/FieldValueMatcher.tsx [hunk 1]
```diff
@@ -62,7 +62,7 @@ export const FieldValueMatcherEditor = ({ options, onChange }: Props) => {
   );
 
   const opts = options ?? {};
-  const isBool = isBooleanReducer(options.reducer);
+  const isBool = isBooleanReducer(options?.reducer);
```
Comment (leeoniya) [inline packages/grafana-ui/src/components/MatchersUI/FieldValueMatcher.tsx:65]: the rest of the code uses `opts` from the line above, so let's change this to also use `opts.reducer`?

**Comment by leeoniya** [comment]
@yincongcyincong sorry i missed this (i was out last week). left a comment.

**Comment by yincongcyincong** [comment]
> @yincongcyincong sorry i missed this (i was out last week). left a comment.

thanks for the review. i modified it.

**Review by leeoniya — APPROVED** [review]
