### PR TITLE
FieldReducers: Fix median

### LINKED ISSUE #98140: Dashboard Legend: Median value not populating
### What happened?

After adding Median value to the legend of a Time Series panel and refreshing the dashboard, the Median value is not populating (it's blank). On the other hand, other values in the legend (last, min, mean, max) are populating.

### What did you expect to happen?

Median value should populate, after the dashboard is done refreshing.

### Did this work before?

Not sure, only tried adding Median to the legend starting yesterday

### How do we reproduce it?

1. Create a Time Series visualization
2. Add Median to the legend
3. Apply and refresh the dashboard
4. Observe the blank Median value in the dashboard legend

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: v11.2.2+security-01 (dc86a9eafb)
OS: macOS Sequoia Version 15.1.1
Browser: Chrome

### Grafana platform?

Grafana Enterprise

### Datasource(s)?

This was seen on both Prometheus and Cloudwatch datasources

### PR DESCRIPTION
**Pull request by yincongcyincong**
Fixes #98140
image

### CODE REVIEW

**Comment by yincongcyincong** [comment]
@leeoniya bro, could you please take a look this pr? thanks

**Comment by yincongcyincong** [comment]
@Develer bro, could you please take a look this pr. thanks

**Comment by gelicia** [comment]
I am unable to recreate your issue - can you provide any other replication steps to reliably replicate it, preferably using the [testdata datasource](https://grafana.com/docs/grafana/latest/datasources/testdata/)?

**Review by gelicia — CHANGES_REQUESTED** [review]
Hello, thank you for this PR! After some discussion, we decided we don't want this calculation to be implicitly calculated as part of the standard set, but calculated on demand instead. Could you change the option to follow the pattern used by other non-standard reducers? See something like [distinctCount](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/transformations/fieldReducer.ts#L383) for what that looks like. If youd like, I can take care of it. Thank you!

**Comment by yincongcyincong** [comment]
@gelicia i modified the code. please take a look. thanks.

File: packages/grafana-data/src/transformations/fieldReducer.ts [hunk 1]
```diff
@@ -703,3 +705,32 @@ function calculatePercentile(field: Field, percentile: number, ignoreNulls: bool
   const index = Math.round((sorted.length - 1) * percentile);
   return sorted[index];
 }
+
+function calculateMedian(field: Field, ignoreNulls: boolean, nullAsZero: boolean): FieldCalcs {
+  // add number
+  const data = field.values;
+  let numbers: any[] = [];
```
Comment (gelicia) [inline packages/grafana-data/src/transformations/fieldReducer.ts:712]: I think we should be doing the same type checking as was there previously - avoiding `any` to have this be `number` and then ensuring the value is a number before it's added to the median. Sort will have weird behaviors if this is mixed as strings and numbers. 

Just trying to have it match the go equivalent here https://github.com/grafana/grafana/pull/91119/files#diff-a86ecb852faf2c362cd80fb9ac99614fc92dd6ffe3a1bc870a3618437b176254R103  - I think after we ensure the values are numbers, we're good on that.

**Review by gelicia — CHANGES_REQUESTED** [review]

File: packages/grafana-data/src/transformations/fieldReducer.ts (hunk 1 above)
Comment (yincongcyincong) [reply packages/grafana-data/src/transformations/fieldReducer.ts]: thanks for your review. i modifed the code. please take a look.

**Comment by yincongcyincong** [comment]
@gelicia  i modified the code. please take a look. thanks.

**Review by gelicia — APPROVED** [review]
Took out an explicit type check to rely on typescript instead. Thank you for your contribution!

**Comment by gelicia** [comment]
@yincongcyincong Hello, the code for this is looking good. I'll be doublechecking everything passes and being sure its in a couple unit tests, but then I can merge it :) Thank you for your contribution!
