### PR TITLE
Explore: Fix ANSI dim style being unreadable in dark mode

### LINKED ISSUE #40976: Explore: ANSI dim style almost unreadable in dark mode
**Steps to reproduce**:

Using the Explore page with Loki, find a log line containing the ANSI `dim` style (`ESC[2m`).

To emit such a line in a shell:
```sh
echo "normal \e[2mdimmed\e[22m"
```

**Actual Result**:

In the Dark UI theme, the dim text (`rgba(0, 0, 0, 0.5)`) is nearly identical to the color of the background (`rgba(24, 27, 31, 1)`), making it almost impossible to read (contrast ratio 1.12). I have added a red arrow pointing to a block of dimmed text in the following screenshot.

Screen Shot 2021-10-27 at 18 01 51

**Expected Result**

In the Light UI theme, the dim text is quite readable (contrast ratio 3.97).

image

**Relevant WCAG Criteria:**

[1.4.3 Contrast (Minimum)](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#contrast-minimum)

**Environment**:
- Grafana version: v8.3.0-pre (fadf72d)
- Data source type & version: Loki
- User OS & Browser: Chrome 94 on macOS 10.15 (Catalina)

### PR DESCRIPTION
**Pull request by oliverfrye**
**What this PR does / why we need it**:

The ANSI dim style (`ESC[2m`) is nearly unreadable in dark mode, because the underlying `ansicolor` library returns a dark grey colour, without regard for the background that it is displayed on.

This PR adds a workaround to intercept the dark grey colour that `ansicolor` returns and replaces it with `opacity: 0.5` instead, which works on both light and dark themes. The corrected text is pictured below:

image

**Which issue(s) this PR fixes**:

Fixes #40976

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by oliverfrye** [comment]
Note to reviewers: I'm just awaiting review from my employer's legal team before I can sign the CLA. I will sign it as soon as possible.

File: packages/grafana-ui/src/components/Logs/LogMessageAnsi.tsx [hunk 1]
```diff
@@ -12,6 +12,15 @@ interface ParsedChunk {
...
   return css.split(/;\s*/).reduce((accumulated, line) => {
+    // The ansicolor package returns this color if the chunk has the ANSI dim
+    // style (`\e[2m`), but it is nearly unreadable in the dark theme, so we use
+    // `opacity` instead to style it in a way that works across all themes.
+    if (line === 'color:rgba(0,0,0,0.5)') {
+      // @ts-ignore
+      accumulated['opacity'] = '0.5';
+      return accumulated;
+    }
+
```
Comment (Elfo404) [inline packages/grafana-ui/src/components/Logs/LogMessageAnsi.tsx:23]: just a nit, I see this is already done in the same function so no biggie:

it would be great if instead of `@ts-ignore` which would suppress any error we could do
```suggestion
  return css.split(/;\s*/).reduce<Style>((accumulated, line) => {
    // The ansicolor package returns this color if the chunk has the ANSI dim
    // style (`\e[2m`), but it is nearly unreadable in the dark theme, so we use
    // `opacity` instead to style it in a way that works across all themes.
    if (line === 'color:rgba(0,0,0,0.5)') {
      accumulated['opacity'] = '0.5';
      return accumulated;
    }

```

if then you could also remove the ignore on line 28 that would be great :)

**Comment by Elfo404** [comment]
@oliverfrye thanks for contributing! 

Just left a small nit for now while waiting for the CLA, but I was thinking that instead of hardcoding that substitute color we could instead use some value from `GrafanaTheme2` cc. @gabor does it make sense? any idea on which one we could use?

File: packages/grafana-ui/src/components/Logs/LogMessageAnsi.tsx (hunk 1 above)
Comment (oliverfrye) [reply packages/grafana-ui/src/components/Logs/LogMessageAnsi.tsx]: This is much nicer, thank you 🙏

**Comment by oliverfrye** [comment]
> @oliverfrye thanks for contributing!
> 
> Just left a small nit for now while waiting for the CLA, but I was thinking that instead of hardcoding that substitute color we could instead use some value from `GrafanaTheme2` cc. @gabor does it make sense? any idea on which one we could use?

Thanks @Elfo404. I've managed to secure company approval and to sign the CLA now, so this should be good to go now.

I think one good thing about using `opacity` instead of a specific colour, as I've done in this MR, is that it should look fairly decent in all themes and against all backgrounds, even if the user is using custom styles. Nonetheless, if you or @gabor want to use a specific colour then I can easily change the MR to reflect that.

**Comment by Elfo404** [comment]
I see your point, but this is also the point of using tokens from GrafanaTheme2, plus it makes sure it's consistent with every other component. i think `theme.colors.text.secondary` or `theme.colors.text.disabled` would make good candidates (maybe the former should be preferred).

 I'd wait for some other opinion though before implementing it, otherwise the PR looks good! thanks for contributing!

**Comment by gabor** [comment]
hi @oliverfrye @Elfo404 , sorry, i missed the ping somehow.. 
i see @oliverfrye 's point of this solution being generic, but still, i'd go with the theme-colors based approach, it seems more in sync with how we are tying to do things.

**Comment by oliverfrye** [comment]
@gabor no worries. Could you let me know which colour you'd like me to use? I will make the requested changes as soon as I can.

**Comment by Elfo404** [comment]
@oliverfrye i think `theme.colors.text.secondary` from `GrafanaTheme2` would be appropriate here. thank you!

**Comment by oliverfrye** [comment]
Thanks @Elfo404. I've made those changes as requested.

I'm not sure I've done the right thing in terms of getting the `GrafanaTheme2` object - I tried to mimic code I found near to this component. Does that look OK to you?

**Comment by Elfo404** [comment]
looks great! I'll get back to this asap and test it, but code looks good.

Thanks again!

File: packages/grafana-ui/src/components/Logs/LogMessageAnsi.tsx [hunk 2]
```diff
@@ -1,8 +1,9 @@
-import { findHighlightChunksInText } from '@grafana/data';
+import { findHighlightChunksInText, GrafanaTheme2 } from '@grafana/data';
 import ansicolor from 'ansicolor';
 import React, { PureComponent } from 'react';
 // @ts-ignore
 import Highlighter from 'react-highlight-words';
+import { Themeable2, withTheme2 } from 'src';
```
Comment (Elfo404) [inline packages/grafana-ui/src/components/Logs/LogMessageAnsi.tsx:6]: i think most of frontend test are failing because of this:

```suggestion
import { Themeable2 } from '../../types';
import { withTheme2 } from '../../themes';
```

**Review by Elfo404 — CHANGES_REQUESTED** [review]
i think we also need to update the tests in `packages/grafana-ui/src/components/Logs/LogMessageAnsi.test.tsx`

you can check `packages/grafana-ui/src/components/Logs/LogLabels.test.tsx` for an example on how to test the unthemed component with the correct theme.

Aside from that everything looks great, let me know if you can get back to this otherwise I'll be happy to pick it up.

File: packages/grafana-ui/src/components/Logs/LogMessageAnsi.tsx (hunk 2 above)
Comment (oliverfrye) [reply packages/grafana-ui/src/components/Logs/LogMessageAnsi.tsx]: Apologies for the delay @Elfo404 - I've been out sick all week. I've pushed some changes to (1) fix the existing tests (including this import), and (2) to add a new test to ensure ANSI dim is rendered with the correct theme color.

**Review by Elfo404 — APPROVED** [review]
Great stuff! 🚀 

thanks again for contributing!
