### PR TITLE
Elasticsearch: Fix calculation of trimEdges in alert mode

### LINKED ISSUE #39414: (ElasticSearch) Trim edges not considered by alert rule
**What happened**:
When alert is evaluating it is not taking into account trim edges value, that is used in ElasticSearch query, even though trimmed value is visible in panel
2021-09-20_14h33_27
2021-09-20_14h34_37

**What you expected to happen**:
With trim edges value defined, it should remove that number of points from beginning and the end of the query result
This functionality is working fine Grafana 7.3.6

**How to reproduce it (as minimally and precisely as possible)**:
Create time series panel for ElasticSearch data source, write any query and use Group By: Date Histogram > @timestamp >Trim Edges: 1

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.4
- Data source type & version: ElasticSearch 6.8.3

### PR DESCRIPTION
**Pull request by jorgelbg**
**What this PR does / why we need it**:

This PR fixes the handling of the `trimEdges` option in the Elasticsearch go backend. This option was ignored by the backend which is used by the alerting component.

**Which issue(s) this PR fixes**:

This was reported on #39414, and considering that both we reproduced this with both the legacy and unified alerting.

Fixes #39414 (already closed)

**Special notes for your reviewer**:

When `trimEdges` is set to `n` it should drop `n` datapoints from both the beginning and the end of the frames fields, but it was always ignoring 1 element from the end. When `n=1` it was not dropping any sample from the end.

The second bug happens because within the panel JSON the `trimEdges` is stored as a quoted number (string) rather than an actual number:  https://github.com/grafana/grafana/blob/23956557d8c6a119b7de5be5c42024e29634d002/public/app/plugins/datasource/elasticsearch/components/QueryEditor/BucketAggregationsEditor/aggregations.ts#L20

```json
"bucketAggs": [
  {
    "field": "@timestamp",
    "id": "2",
    "settings": {
      "interval": "1m",
      "trimEdges": "1"
    },
    "type": "date_histogram"
  }
],
```

When this value was read in the backend `simplejson` failed to coerce it into an integer, which silently failed due to the early return of the function. Since `simplejson` is deprecated, a new function (`castToInt`) that handles this case was added, similar to the existing `castToFloat`.

### CODE REVIEW

File: pkg/tsdb/elasticsearch/response_parser.go [hunk 1]
```diff
@@ -527,18 +527,19 @@ func (rp *responseParser) trimDatapoints(queryResult backend.DataResponse, targe
 		return
 	}
 
-	trimEdges, err := histogram.Settings.Get("trimEdges").Int()
-	if err != nil {
```
Comment (gabor) [inline pkg/tsdb/elasticsearch/response_parser.go:531]: `trimEdges` is defined to be a `string` at https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/elasticsearch/components/QueryEditor/BucketAggregationsEditor/aggregations.ts#L20 ,
so i don't think we need to handle any other dataype there.

so i'd recommend to just convert it to string and then do the `atoi` inline, something like 
```go
strconv.Atoi(histogram.Settings.Get("trimEdges").MustString(""))
```

what do you think?

File: pkg/tsdb/elasticsearch/response_parser_test.go [hunk 2]
```diff
@@ -691,17 +691,17 @@ func TestResponseParser(t *testing.T) {
 			frame := dataframes[0]
 			require.Len(t, frame.Fields, 2)
 			require.Equal(t, frame.Fields[0].Name, "time")
-			require.Equal(t, frame.Fields[0].Len(), 2)
```
Comment (gabor) [inline pkg/tsdb/elasticsearch/response_parser_test.go:694]: please also adjust the test-data at https://github.com/jorgelbg/grafana/blob/es-alert-trimedges/pkg/tsdb/elasticsearch/response_parser_test.go#L647 so that the `trimEdges` value is a string.

**Review by gabor — CHANGES_REQUESTED** [review]
thanks for finding the problem! 
to me it does not seem we need to have a very generic take-numbers-and-numbers-in-strings-from-json transform here, because `trimEdges` should always be a string, more details in the comments.

File: pkg/tsdb/elasticsearch/response_parser.go (hunk 1 above)
Comment (jorgelbg) [reply pkg/tsdb/elasticsearch/response_parser.go:531]: Happy to apply the suggestion, I just went the extra round because I noticed that `trimEdges` seems to be used somehow inconsistently in different places. For instance

In this test it is mocked and expected to be a numeric value: https://github.com/grafana/grafana/blob/a58edc9f5e3f8b18772dab48b9396c91109a25c3/pkg/tsdb/elasticsearch/time_series_query_test.go#L1208

Also in this dev dashboard it is exported and stored as an integer:
https://github.com/grafana/grafana/blob/23956557d8c6a119b7de5be5c42024e29634d002/devenv/dev-dashboards/datasource-elasticsearch/elasticsearch_compare.json#L97

I also tested locally by editing the raw JSON of the panel and setting a numeric value directly (instead of using the query editor) an actual number is stored & sent to backend.

Again, happy to simply the code, I was just being extra cautious with the change 😅.

Comment (gabor) [reply pkg/tsdb/elasticsearch/response_parser.go:531]: @jorgelbg  hmm.. yeah, good point. please don't do it yet, let me dig more into the history of this thing, i'll come back to you 👍

**Review by gabor — CHANGES_REQUESTED** [review]
ok, i checked and there might be a chance that old dashboards were saved with "really numbers" in javascript 😢 , so let's go with your approach. i have two comments in that case:

1. please make `castToInt` more go-ish, i described that more in a separate comment
2. please add one more test-case, so that we have two tests, one for value-is-number, and another for value-is-a-string-that-is-a-number 
3. 
thanks!

File: pkg/tsdb/elasticsearch/response_parser.go (hunk 1 above)
Comment (gabor) [reply pkg/tsdb/elasticsearch/response_parser.go:531]: @jorgelbg let's go with supporting both modes (number-in-string and really-number) 👍 . i added some more comments below. thanks for finding this complication!

File: pkg/tsdb/elasticsearch/response_parser_test.go (hunk 2 above)
Comment (gabor) [reply pkg/tsdb/elasticsearch/response_parser_test.go:694]: this is not needed anymore, now we need to have two tests, one for string and one for number.

File: pkg/tsdb/elasticsearch/response_parser.go [hunk 3]
```diff
@@ -674,6 +675,25 @@ func (rp *responseParser) getMetricName(metric string) string {
 	return metric
 }
 
+func castToInt(j *simplejson.Json) *int {
```
[the remark this answers is not in the document]
Comment (jorgelbg) [reply pkg/tsdb/elasticsearch/response_parser.go]: @gabor I refactored `castToInt` to bubble up any error that it gets either from simplejson or from strconv.Atoi().

I also added the new test case, although it is mostly a copy from https://github.com/grafana/grafana/blob/main/pkg/tsdb/elasticsearch/response_parser_test.go#L637 with the updated title and the `trimEdges` property set to the quoted number. Not really easy to make a shorter test in this case and I didn't think that changing the values would provide any additional benefit in this case.

[the remark this answers is not in the document]
Comment (gabor) [reply pkg/tsdb/elasticsearch/response_parser.go]: thanks for your work there! from a quick reading of the diff everything looks fine :+1:, i'll try to do a real review next week.

**Review by gabor — APPROVED** [review]
nice work!

**Comment by gabor** [comment]
@jorgelbg thanks for your work on this! it's merged now.

note, it seems there's still a problem with the trim-values calculation, when `trimEdges` is larger than `1` it does strange things, the reason being, that loop that deletes the items deletes them during the iteration of the array, so the array-length keeps changing during the iteration... anyway, we'll fix that, no problem.

**Comment by jorgelbg** [comment]
@gabor Oh no! Good catch! I assumed that `field.Delete()` (or the underline data structure) would deal with in-place modifications (after checking, it is a normal slice), but on second thought I also kept the `field.Len()` within the loop which gets evaluated in each iteration 🤦.
