### PR TITLE
TimeSeries: Improve tooltip positioning when tooltip overflows

### LINKED ISSUE #31098: GraphNG: Time series panel Tooltip is cut off at the top
**What happened**:

Tested new Time series beta Panel, with "Tooltip mode" = "All". The Tooltip position is different / incorrect, as the mouse cursor is in the bottom left corner, which may result in the Tooltip being cut off at the top (see below).
When having just a few series, tooltip position is the same as with Graph Panel.

Old Graph Panel Tooltip seems to show a maximum of 32 series (see #18425 Support more than 32 series in Graph tooltip )

**What you expected to happen**:

Panel tooltip behavior should not change (or get worse) compared to old Graph Panel.

Even though #18425 is not solved, It's better or more consistent to always show the Position Timestamp at the top of the tooltip and cut off the list after 32 series.
Current behavior of timeseries panel may show much less than the possible 32 series in tooltip depending on panel position in dashboard.

**How to reproduce it (as minimally and precisely as possible)**:

- Use any dashboard, e.g. <https://play.grafana.org/d/000000016>
- Duplicate (for comparision) Graph Panel und change to Timeseries Panel, set Tooltip mode to "All",
(Top is old Graph Panel, below is new Timerseries panel)

with just 4 series, there is no difference ✔️ 

WaLgzZ4o8v

- Get more series (change to prometheus datasource and use `{__name__ =~ "prometheus_tsdb.+"}`) for both panels:
grafik

Now, the timeseries panel tooltip position is different, the tooltip is not fully readable anymore 💥 :

6MmeXKaGiD

It's still ok with 17 series (`{__name__ =~ "prometheus_tsdb_head.+"}`)
O1Gupdc116

----

**Environment**:
- Grafana version: `7.4.0`
- Data source type & version: prometheus
- OS Grafana is installed on: <https://play.grafana.org>
- User OS & Browser: Windows 10, Firefox 85.0.1
- Grafana plugins: Timeseries beta plugin

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

this PR ensures the tooltip makes maximum use of the space it has available, and we prefer a tooltip position of bottom right.

the logic is the same for both axes, but taking the y-axis as an example:
  - if the tooltip would overflow the bottom when placed below and the top when placed above, position it stickily to the end which has the least overflow
  - if the tooltip would overflow the bottom when placed below but not the top when placed above, position it above
  - if the tooltip would not overflow the bottom when placed below, then position it below

see video for example:

https://user-images.githubusercontent.com/20999846/124489937-7067e280-dda9-11eb-98e2-aa4893a62972.mov

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/31098

**Special notes for your reviewer**:

### CODE REVIEW

File: packages/grafana-ui/src/components/VizTooltip/VizTooltipContainer.tsx [hunk 1]
```diff
@@ -64,23 +64,40 @@ export const VizTooltipContainer: React.FC<VizTooltipContainerProps> = ({
...
       }
 
-      if (yOverflow < 0) {
-        yO = tooltipMeasurement.height;
+      if (wouldOverflowBelow && wouldOverflowAbove) {
+        y = overflowBelow > overflowAbove ? offsetY : height - offsetY - tooltipMeasurement.height;
+      } else if (wouldOverflowBelow) {
+        y = positionY - offsetY - tooltipMeasurement.height;
+      } else {
+        y = positionY + offsetY;
```
Comment (dprokop) [inline packages/grafana-ui/src/components/VizTooltip/VizTooltipContainer.tsx:94]: Cool that you have added this @ashharrison90 . Would be great if this could be extracted to a helper function and unit tested.

Another alternative that I think is worth trying instead of this calculation is to use react-popper with virtual reference(https://popper.js.org/react-popper/v2/virtual-elements/). We use it in few places and it was working great so far. Do you mind checking how well it works in this scenario?

**Review by dprokop — COMMENTED** [review]
Cool that you have added this @ashharrison90 . Would be great if this could be extracted to a helper function and unit tested.

Another alternative that I think is worth trying instead of this calculation is to use react-popper with virtual reference(https://popper.js.org/react-popper/v2/virtual-elements/). We use it in few places and it was working great so far. Do you mind checking how well it works in this scenario?

**Comment by ashharrison90** [comment]
@dprokop @mckn think i've addressed everything

switched to use `react-popper`, but still using the calculation as the inbuilt calculation doesn't seem to handle all cases as gracefully 🤔 

added unit tests as well 👍

**Comment by dprokop** [comment]
@ashharrison90 found some time today to peek at this ad managed to use react-popper only: f3250c7a1fa124eb1cb49a19ec7f820956cb7ac5. The position calculation that was a leftover felt redundant. WDYT?

**Review by mckn — COMMENTED** [review]
I really like the code when using popper. It was really clean and neat, however when I tested it it doesn't really work in all scenarios. Have a look at the following scenario:

position2

Also, I found another weird bug when playing around with the panel settings:

not_update2

Should we open another issue on that one?

**Comment by leeoniya** [comment]
> Should we open another issue on that one?

it's this one: https://github.com/grafana/grafana/issues/35266

**Comment by mckn** [comment]
> > Should we open another issue on that one?
> 
> it's this one: #35266

Ah, ok ok - thanks 🙏🏻

**Comment by ashharrison90** [comment]
@dprokop @mckn have updated the PR to address the last little problem of the tooltip overflowing the y-axis and reduced the transition time a bit as 0.5s felt a bit sluggish. thanks for getting popper to work nicely, code is much cleaner now! 🎉

**Review by dprokop — APPROVED** [review]

**Review by mckn — APPROVED** [review]
LGTM!

It is a bit flickering when I hover and move the mouse but this is way better than before! Great work on this Ash!
