### PR TITLE
Loki: Run instant query only in Explore

### LINKED ISSUE #27860: Grafana 7.2 + Loki 1.6.1 + pie-chart: query then query_range
**What happened**:
I just updated Grafana to version 7.2 and I noticed that the Pie-Chart plugin was not working correctly.

**What you expected to happen**:
I was expecting that my dashboard should keep working, but the pie chart panel did not worked as expected.

**How to reproduce it (as minimally and precisely as possible)**:
Just try to use a pie chart panel. The chart does not get rendered.

**Anything else we need to know?**:
During the troubleshooting, I noticed that Grafana is triggering a **query**, then a **query_range** call. The **query** does not return data, but the **query_range** does. Some sample responses:

- **_query_** (URL like(the query would be encoded): **loki/api/v1/query?query=sum(count_over_time({job="services"}[2m])) by (ServiceName)&time=1597874341000000000&limit=1000**):
```JSON
{"status":"success","data":{"resultType":"vector","result":[],"stats":{"summary":{"bytesProcessedPerSecond":0,"linesProcessedPerSecond":0,"totalBytesProcessed":0,"totalLinesProcessed":0,"execTime":0.0020015},"store":{"totalChunksRef":0,"totalChunksDownloaded":0,"chunksDownloadTime":0,"headChunkBytes":0,"headChunkLines":0,"decompressedBytes":0,"decompressedLines":0,"compressedBytes":0,"totalDuplicates":0},"ingester":{"totalReached":1,"totalChunksMatched":0,"totalBatches":0,"totalLinesSent":0,"headChunkBytes":0,"headChunkLines":0,"decompressedBytes":0,"decompressedLines":0,"compressedBytes":0,"totalDuplicates":0}}}}
```

- **_query_range_** (URL like(the query would be encoded): **loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=sum(count_over_time({job="services"}[2m])) by (ServiceName)&start=1597701600000000000&end=1597874341000000000&step=120**):
```JSON
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"ServiceName":"ABC"},"values":[[1597701600,"3"],[1597701840,"3"],[1597702080,"3"],[1597702200,"3"],[1597702440,"3"],[1597702680,"3"],[1597702920,"3"],[1597703160,"3"],[1597703400,"3"],[1597703640,"3"],[1597703880,"3"],[1597704120,"3"],[1597704240,"3"],[1597704480,"3"],[1597704720,"3"],[1597704960,"3"],[1597705200,"3"],[1597705440,"3"],[1597705680,"3"],[1597705920,"3"],[1597706040,"3"],[1597706280,"3"],[1597706520,"3"],[1597706760,"3"],[1597707000,"3"],[1597707240,"3"],[1597707480,"3"],[1597707720,"3"],[1597707960,"3"],[1597708080,"3"],[1597708320,"3"],[1597708560,"3"],[1597708800,"3"],[1597709040,"3"],[1597709280,"3"],[1597709520,"3"],[1597709760,"3"],[1597709880,"3"],[1597710120,"3"],[1597710360,"3"],[1597710600,"3"],[1597710840,"3"],[1597711080,"3"],[1597711320,"3"],[1597711560,"3"],[1597711800,"3"],[1597711920,"3"],[1597712160,"3"],[1597712400,"3"],[1597712640,"3"],[1597712880,"3"],[1597713120,"3"],[1597713360,"3"],[1597713600,"3"],[1597713720,"3"],[1597713960,"3"],[1597714200,"3"],[1597714440,"3"],[1597714680,"3"],[1597714920,"3"],[1597715160,"3"],[1597715400,"3"],[1597715640,"3"],[1597715760,"3"],[1597716000,"3"],[1597716240,"3"],[1597716480,"3"],[1597716720,"3"],[1597716960,"3"],[1597717200,"3"],[1597717440,"3"],[1597717680,"3"],[1597717800,"3"],[1597718040,"3"],[1597718280,"3"],[1597718520,"3"],[1597718760,"3"],[1597719000,"3"],[1597719240,"3"],[1597719480,"3"],[1597719600,"3"],[1597719840,"3"],[1597720080,"3"],[1597720320,"3"],[1597720560,"3"],[1597720800,"3"],[1597721040,"3"],[1597721280,"3"],[1597721520,"3"],[1597721640,"3"],[1597721880,"3"],[1597722120,"3"],[1597722360,"3"],[1597722600,"3"],[1597722840,"3"],[1597723080,"3"],[1597723320,"3"],[1597723440,"3"],[1597723680,"3"],[1597723920,"3"],[1597724160,"3"],[1597724400,"3"],[1597724640,"3"],[1597724880,"3"],[1597725120,"3"],[1597725360,"3"],[1597725480,"3"],[1597725720,"3"],[1597725960,"3"],[1597726200,"3"],[1597726440,"3"],[1597726680,"3"],[1597726920,"3"],[1597727160,"3"],[1597727400,"3"],[1597727520,"3"],[1597727760,"3"],[1597728000,"3"],[1597728240,"3"],[1597728480,"3"],[1597728720,"3"],[1597728960,"3"],[1597729200,"3"],[1597729320,"3"],[1597729560,"3"],[1597729800,"3"],[1597730040,"3"],[1597730280,"3"],[1597730520,"3"],[1597730760,"3"],[1597731000,"3"],[1597731240,"3"],[1597731360,"3"],[1597731600,"3"],[1597731840,"3"],[1597732080,"3"],[1597732320,"3"],[1597732560,"3"],[1597732800,"3"],[1597733040,"3"],[1597733160,"3"],[1597733400,"3"],[1597733640,"3"],[1597733880,"3"],[1597734120,"3"],[1597734360,"3"],[1597734600,"3"],[1597734840,"3"],[1597735080,"3"],[1597735200,"3"],[1597735440,"3"],[1597735680,"3"],[1597735920,"3"],[1597736160,"3"],[1597736400,"3"],[1597736640,"3"],[1597736880,"3"],[1597737120,"3"],[1597737240,"3"],[1597737480,"3"],[1597737720,"3"],[1597737960,"3"],[1597738200,"3"],[1597738440,"3"],[1597738680,"3"],[1597738920,"3"],[1597739040,"3"],[1597739280,"3"],[1597739520,"3"],[1597739760,"3"],[1597740000,"3"],[1597740240,"3"],[1597740480,"3"],[1597740720,"3"],[1597740960,"3"],[1597741080,"3"],[1597741320,"3"],[1597741560,"3"],[1597741800,"3"],[1597742040,"3"],[1597742280,"3"],[1597742520,"3"],[1597742760,"3"],[1597742880,"3"],[1597743120,"3"],[1597743360,"3"],[1597743600,"3"],[1597743840,"3"],[1597744080,"3"],[1597744320,"3"],[1597744560,"3"],[1597744800,"3"],[1597744920,"3"],[1597745160,"3"],[1597745400,"3"],[1597745640,"3"],[1597745880,"3"],[1597746120,"3"],[1597746360,"3"],[1597746600,"3"],[1597746720,"3"],[1597746960,"3"],[1597747200,"3"],[1597747440,"3"],[1597747680,"3"],[1597747920,"3"],[1597748160,"3"],[1597748400,"3"],[1597748640,"3"],[1597748760,"3"],[1597749000,"3"],[1597749240,"3"],[1597749480,"3"],[1597749720,"3"],[1597749960,"3"],[1597750200,"3"],[1597750440,"3"],[1597750680,"3"],[1597750800,"3"],[1597751040,"3"],[1597751280,"3"],[1597751520,"3"],[1597751760,"3"],[1597752000,"3"],[1597752240,"3"],[1597752480,"3"],[1597752600,"3"],[1597752840,"3"],[1597753080,"3"],[1597753320,"3"],[1597753560,"3"],[1597753800,"3"],[1597754040,"3"],[1597754280,"3"],[1597754520,"3"],[1597754640,"3"],[1597754880,"3"],[1597755120,"3"],[1597755360,"3"],[1597755600,"3"],[1597755840,"3"],[1597756080,"3"],[1597756320,"3"],[1597756440,"3"],[1597756680,"3"],[1597756920,"3"],[1597757160,"3"],[1597757400,"3"],[1597757640,"3"],[1597757880,"3"],[1597758120,"3"],[1597758360,"3"],[1597758480,"3"],[1597758720,"3"],[1597758960,"3"],[1597759200,"3"],[1597759440,"3"],[1597759680,"3"],[1597759920,"3"],[1597760160,"3"],[1597760400,"3"],[1597760520,"3"],[1597760760,"3"],[1597761000,"3"],[1597761240,"3"],[1597761480,"3"],[1597761720,"3"],[1597761960,"3"],[1597762200,"3"],[1597762320,"3"],[1597762560,"3"],[1597762800,"3"],[1597763040,"3"],[1597763280,"3"],[1597763520,"3"],[1597763760,"3"],[1597764000,"3"],[1597764240,"3"],[1597764360,"3"],[1597764600,"3"],[1597764840,"3"],[1597765080,"3"],[1597765320,"3"],[1597765560,"3"],[1597765800,"3"],[1597766040,"3"],[1597766160,"3"],[1597766400,"3"],[1597766640,"3"],[1597766880,"3"],[1597767120,"3"],[1597767360,"3"],[1597767600,"3"],[1597767840,"3"],[1597768080,"3"],[1597768200,"3"],[1597768440,"3"],[1597768680,"3"],[1597768920,"3"],[1597769160,"3"],[1597769400,"3"],[1597769640,"3"],[1597769880,"3"],[1597770120,"3"],[1597770240,"3"],[1597770480,"3"],[1597770720,"3"],[1597770960,"3"],[1597771200,"3"],[1597771440,"3"],[1597771680,"3"],[1597771920,"3"],[1597772040,"3"],[1597772280,"3"],[1597772520,"3"],[1597772760,"3"],[1597773000,"3"],[1597773240,"3"],[1597773480,"3"],[1597773720,"3"],[1597773960,"3"],[1597774080,"3"],[1597774320,"3"],[1597774560,"3"],[1597774800,"3"],[1597775040,"3"],[1597775280,"3"],[1597775520,"3"],[1597775760,"3"],[1597775880,"3"],[1597776120,"3"],[1597776360,"3"],[1597776600,"3"],[1597776840,"3"],[1597777080,"3"],[1597777320,"3"],[1597777560,"3"],[1597777800,"3"],[1597777920,"3"],[1597778160,"3"],[1597778400,"3"],[1597778640,"3"],[1597778880,"3"],[1597779120,"3"],[1597779360,"3"],[1597779600,"3"],[1597779840,"3"],[1597779960,"3"],[1597780200,"3"],[1597780440,"3"],[1597780680,"3"],[1597780920,"3"],[1597781160,"3"],[1597781400,"3"],[1597781640,"3"],[1597781760,"3"],[1597782000,"3"],[1597782240,"3"],[1597782480,"3"],[1597782720,"3"],[1597782960,"3"],[1597783200,"3"],[1597783440,"3"],[1597783680,"3"],[1597783800,"3"],[1597784040,"3"],[1597784280,"3"],[1597784520,"3"],[1597784760,"3"],[1597785000,"3"],[1597785240,"3"],[1597785480,"3"],[1597785600,"3"],[1597785840,"3"],[1597786080,"3"],[1597786320,"3"],[1597786560,"3"],[1597786800,"3"],[1597787040,"3"],[1597787280,"3"],[1597787520,"3"],[1597787640,"3"],[1597787880,"3"],[1597788120,"3"],[1597788360,"3"],[1597788600,"3"],[1597788840,"3"],[1597789080,"3"],[1597789320,"3"],[1597789560,"3"],[1597789680,"3"],[1597789920,"3"],[1597790160,"3"],[1597790400,"3"],[1597790640,"3"],[1597790880,"3"],[1597791120,"3"],[1597791360,"3"],[1597791480,"3"],[1597791720,"3"],[1597791960,"3"],[1597792200,"3"],[1597792440,"3"],[1597792680,"3"],[1597792920,"3"],[1597793160,"3"],[1597793400,"3"],[1597793520,"3"],[1597793760,"3"],[1597794000,"3"],[1597794240,"3"],[1597794480,"3"],[1597794720,"3"],[1597794960,"3"],[1597795200,"3"],[1597795320,"3"],[1597795560,"3"],[1597795800,"3"],[1597796040,"3"],[1597796280,"3"],[1597796520,"3"],[1597796760,"3"],[1597797000,"3"],[1597797240,"3"],[1597797360,"3"],[1597797600,"3"],[1597797840,"3"],[1597798080,"3"],[1597798320,"3"],[1597798560,"3"],[1597798800,"3"],[1597799040,"3"],[1597799160,"3"],[1597799400,"3"],[1597799640,"3"],[1597799880,"3"],[1597800120,"3"],[1597800360,"3"],[1597800600,"3"],[1597800840,"3"],[1597801080,"3"],[1597801200,"3"],[1597801440,"3"],[1597801680,"3"],[1597801920,"3"],[1597802160,"3"],[1597802400,"3"],[1597802640,"3"],[1597802880,"3"],[1597803120,"3"],[1597803240,"3"],[1597803480,"3"],[1597803720,"3"],[1597803960,"3"],[1597804200,"3"],[1597804440,"3"],[1597804680,"3"],[1597804920,"3"],[1597805040,"3"],[1597805280,"3"],[1597805520,"3"],[1597805760,"3"],[1597806000,"3"],[1597806240,"3"],[1597806480,"3"],[1597806720,"3"],[1597806960,"3"],[1597807080,"3"],[1597807320,"3"],[1597807560,"3"],[1597807800,"3"],[1597808040,"3"],[1597808280,"3"],[1597808520,"3"],[1597808760,"3"],[1597808880,"3"],[1597809120,"3"],[1597809360,"3"],[1597809600,"3"],[1597809840,"3"],[1597810080,"3"],[1597810320,"3"],[1597810560,"3"],[1597810800,"3"],[1597810920,"3"],[1597811160,"3"],[1597811400,"3"],[1597811640,"3"],[1597811880,"3"],[1597812120,"3"],[1597812360,"3"],[1597812600,"3"],[1597812720,"3"],[1597812960,"3"],[1597813200,"3"],[1597813440,"3"],[1597813680,"3"],[1597813920,"3"],[1597814160,"3"],[1597814400,"3"],[1597814640,"3"],[1597814760,"3"],[1597815000,"3"],[1597815240,"3"],[1597815480,"3"],[1597815720,"3"],[1597815960,"3"],[1597816200,"3"],[1597816440,"3"],[1597816680,"3"],[1597816800,"3"],[1597817040,"3"],[1597817280,"3"],[1597817520,"3"],[1597817760,"3"],[1597818000,"3"],[1597818240,"3"],[1597818480,"3"],[1597818600,"3"],[1597818840,"3"],[1597819080,"3"],[1597819320,"3"],[1597819560,"3"],[1597819800,"3"],[1597820040,"3"],[1597820280,"3"],[1597820520,"3"],[1597820640,"3"],[1597820880,"3"],[1597821120,"3"],[1597821360,"3"],[1597821600,"3"],[1597821840,"3"],[1597822080,"3"],[1597822320,"3"]]},{"metric":{"ServiceName":"DEF"},"values":[[1597701600,"162"],[1597701720,"206"],[1597701840,"153"],[1597701960,"193"],[1597702080,"173"],[1597702200,"152"],[1597702320,"369"],[1597702440,"150"],[1597702560,"191"],[1597702680,"176"],[1597702800,"153"],[1597702920,"199"],[1597703040,"158"],[1597703160,"335"],[1597703280,"178"],[1597703400,"151"],[1597703520,"192"],[1597703640,"162"],[1597703760,"186"],[1597703880,"181"],[1597704000,"146"],[1597704120,"354"],[1597704240,"163"],[1597704360,"192"],[1597704480,"167"],[1597704600,"157"],[1597704720,"205"],[1597704840,"162"],[1597704960,"739"],[1597705080,"178"],[1597705200,"152"],[1597705320,"212"],[1597705440,"150"],[1597705560,"191"],[1597705680,"181"],[1597705800,"151"],[1597705920,"360"],[1597706040,"171"],[1597706160,"181"],[1597706280,"174"],[1597706400,"157"],[1597706520,"200"],[1597706640,"169"],[1597706760,"341"],[1597706880,"161"],[1597707000,"163"],[1597707120,"203"],[1597707240,"166"],[1597707360,"186"],[1597707480,"172"],[1597707600,"153"],[1597707720,"362"],[1597707840,"158"],[1597707960,"185"],[1597708080,"172"],[1597708200,"147"],[1597708320,"194"],[1597708440,"168"],[1597708560,"733"],[1597708680,"164"],[1597708800,"157"],[1597708920,"236"],[1597709040,"155"],[1597709160,"177"],[1597709280,"187"],[1597709400,"151"],[1597709520,"370"],[1597709640,"157"],[1597709760,"208"],[1597709880,"176"],[1597710000,"152"],[1597710120,"208"],[1597710240,"162"],[1597710360,"341"],[1597710480,"169"],[1597710600,"151"],[1597710720,"206"],[1597710840,"164"],[1597710960,"172"],[1597711080,"177"],[1597711200,"154"],[1597711320,"353"],[1597711440,"158"],[1597711560,"201"],[1597711680,"175"],[1597711800,"151"],[1597711920,"194"],[1597712040,"171"],[1597712160,"786"],[1597712280,"171"],[1597712400,"157"],[1597712520,"214"],[1597712640,"152"],[1597712760,"185"],[1597712880,"175"],[1597713000,"153"],[1597713120,"357"],[1597713240,"156"],[1597713360,"194"],[1597713480,"164"],[1597713600,"153"],[1597713720,"212"],[1597713840,"161"],[1597713960,"344"],[1597714080,"175"],[1597714200,"148"],[1597714320,"207"],[1597714440,"153"],[1597714560,"184"],[1597714680,"169"],[1597714800,"163"],[1597714920,"353"],[1597715040,"156"],[1597715160,"186"],[1597715280,"171"],[1597715400,"158"],[1597715520,"201"],[1597715640,"158"],[1597715760,"740"],[1597715880,"168"],[1597716000,"159"],[1597716120,"197"],[1597716240,"163"],[1597716360,"186"],[1597716480,"168"],[1597716600,"154"],[1597716720,"361"],[1597716840,"153"],[1597716960,"192"],[1597717080,"171"],[1597717200,"153"],[1597717320,"196"],[1597717440,"156"],[1597717560,"344"],[1597717680,"172"],[1597717800,"159"],[1597717920,"199"],[1597718040,"156"],[1597718160,"185"],[1597718280,"166"],[1597718400,"163"],[1597718520,"342"],[1597718640,"159"],[1597718760,"194"],[1597718880,"167"],[1597719000,"147"],[1597719120,"194"],[1597719240,"168"],[1597719360,"739"],[1597719480,"170"],[1597719600,"157"],[1597719720,"207"],[1597719840,"158"],[1597719960,"184"],[1597720080,"171"],[1597720200,"153"],[1597720320,"360"],[1597720440,"156"],[1597720560,"184"],[1597720680,"175"],[1597720800,"159"],[1597720920,"195"],[1597721040,"157"],[1597721160,"342"],[1597721280,"163"],[1597721400,"161"],[1597721520,"204"],[1597721640,"156"],[1597721760,"200"],[1597721880,"164"],[1597722000,"157"],[1597722120,"350"],[1597722240,"162"],[1597722360,"186"],[1597722480,"178"],[1597722600,"153"],[1597722720,"208"],[1597722840,"161"],[1597722960,"730"],[1597723080,"164"],[1597723200,"151"],[1597723320,"233"],[1597723440,"163"],[1597723560,"188"],[1597723680,"165"],[1597723800,"162"],[1597723920,"349"],[1597724040,"159"],[1597724160,"194"],[1597724280,"172"],[1597724400,"156"],[1597724520,"204"],[1597724640,"157"],[1597724760,"344"],[1597724880,"170"],[1597725000,"162"],[1597725120,"210"],[1597725240,"153"],[1597725360,"192"],[1597725480,"171"],[1597725600,"152"],[1597725720,"372"],[1597725840,"160"],[1597725960,"189"],[1597726080,"162"],[1597726200,"153"],[1597726320,"196"],[1597726440,"167"],[1597726560,"770"],[1597726680,"175"],[1597726800,"148"],[1597726920,"218"],[1597727040,"156"],[1597727160,"193"],[1597727280,"170"],[1597727400,"152"],[1597727520,"355"],[1597727640,"163"],[1597727760,"192"],[1597727880,"172"],[1597728000,"160"],[1597728120,"205"],[1597728240,"157"],[1597728360,"348"],[1597728480,"174"],[1597728600,"156"],[1597728720,"201"],[1597728840,"154"],[1597728960,"200"],[1597729080,"165"],[1597729200,"159"],[1597729320,"342"],[1597729440,"169"],[1597729560,"188"],[1597729680,"176"],[1597729800,"157"],[1597729920,"195"],[1597730040,"166"],[1597730160,"733"],[1597730280,"172"],[1597730400,"160"],[1597730520,"205"],[1597730640,"165"],[1597730760,"189"],[1597730880,"181"],[1597731000,"151"],[1597731120,"344"],[1597731240,"164"],[1597731360,"188"],[1597731480,"186"],[1597731600,"158"],[1597731720,"202"],[1597731840,"157"],[1597731960,"349"],[1597732080,"175"],[1597732200,"157"],[1597732320,"197"],[1597732440,"161"],[1597732560,"179"],[1597732680,"165"],[1597732800,"171"],[1597732920,"350"],[1597733040,"162"],[1597733160,"188"],[1597733280,"175"],[1597733400,"152"],[1597733520,"195"],[1597733640,"168"],[1597733760,"745"],[1597733880,"170"],[1597734000,"152"],[1597734120,"205"],[1597734240,"157"],[1597734360,"187"],[1597734480,"173"],[1597734600,"152"],[1597734720,"364"],[1597734840,"158"],[1597734960,"183"],[1597735080,"180"],[1597735200,"152"],[1597735320,"201"],[1597735440,"166"],[1597735560,"341"],[1597735680,"170"],[1597735800,"151"],[1597735920,"204"],[1597736040,"162"],[1597736160,"193"],[1597736280,"175"],[1597736400,"146"],[1597736520,"344"],[1597736640,"163"],[1597736760,"209"],[1597736880,"173"],[1597737000,"161"],[1597737120,"200"],[1597737240,"148"],[1597737360,"729"],[1597737480,"174"],[1597737600,"157"],[1597737720,"229"],[1597737840,"163"],[1597737960,"193"],[1597738080,"171"],[1597738200,"153"],[1597738320,"352"],[1597738440,"167"],[1597738560,"187"],[1597738680,"172"],[1597738800,"157"],[1597738920,"198"],[1597739040,"163"],[1597739160,"341"],[1597739280,"166"],[1597739400,"157"],[1597739520,"201"],[1597739640,"162"],[1597739760,"190"],[1597739880,"164"],[1597740000,"157"],[1597740120,"358"],[1597740240,"162"],[1597740360,"191"],[1597740480,"181"],[1597740600,"152"],[1597740720,"198"],[1597740840,"157"],[1597740960,"784"],[1597741080,"170"],[1597741200,"146"],[1597741320,"202"],[1597741440,"171"],[1597741560,"194"],[1597741680,"170"],[1597741800,"152"],[1597741920,"371"],[1597742040,"157"],[1597742160,"195"],[1597742280,"162"],[1597742400,"162"],[1597742520,"203"],[1597742640,"161"],[1597742760,"340"],[1597742880,"179"],[1597743000,"147"],[1597743120,"212"],[1597743240,"149"],[1597743360,"190"],[1597743480,"172"],[1597743600,"155"],[1597743720,"357"],[1597743840,"164"],[1597743960,"197"],[1597744080,"170"],[1597744200,"162"],[1597744320,"207"],[1597744440,"157"],[1597744560,"743"],[1597744680,"172"],[1597744800,"159"],[1597744920,"211"],[1597745040,"162"],[1597745160,"204"],[1597745280,"173"],[1597745400,"150"],[1597745520,"363"],[1597745640,"163"],[1597745760,"184"],[1597745880,"176"],[1597746000,"152"],[1597746120,"201"],[1597746240,"157"],[1597746360,"346"],[1597746480,"178"],[1597746600,"152"],[1597746720,"201"],[1597746840,"155"],[1597746960,"179"],[1597747080,"171"],[1597747200,"148"],[1597747320,"355"],[1597747440,"162"],[1597747560,"172"],[1597747680,"190"],[1597747800,"150"],[1597747920,"199"],[1597748040,"151"],[1597748160,"737"],[1597748280,"169"],[1597748400,"157"],[1597748520,"213"],[1597748640,"164"],[1597748760,"192"],[1597748880,"165"],[1597749000,"164"],[1597749120,"357"],[1597749240,"162"],[1597749360,"190"],[1597749480,"165"],[1597749600,"158"],[1597749720,"189"],[1597749840,"176"],[1597749960,"345"],[1597750080,"177"],[1597750200,"152"],[1597750320,"204"],[1597750440,"160"],[1597750560,"187"],[1597750680,"169"],[1597750800,"157"],[1597750920,"353"],[1597751040,"157"],[1597751160,"186"],[1597751280,"160"],[1597751400,"152"],[1597751520,"197"],[1597751640,"150"],[1597751760,"734"],[1597751880,"155"],[1597752000,"153"],[1597752120,"225"],[1597752240,"158"],[1597752360,"190"],[1597752480,"167"],[1597752600,"147"],[1597752720,"367"],[1597752840,"152"],[1597752960,"185"],[1597753080,"165"],[1597753200,"158"],[1597753320,"205"],[1597753440,"152"],[1597753560,"352"],[1597753680,"161"],[1597753800,"157"],[1597753920,"215"],[1597754040,"163"],[1597754160,"186"],[1597754280,"176"],[1597754400,"153"],[1597754520,"364"],[1597754640,"159"],[1597754760,"196"],[1597754880,"172"],[1597755000,"155"],[1597755120,"205"],[1597755240,"157"],[1597755360,"762"],[1597755480,"171"],[1597755600,"147"],[1597755720,"202"],[1597755840,"158"],[1597755960,"194"],[1597756080,"170"],[1597756200,"148"],[1597756320,"360"],[1597756440,"153"],[1597756560,"174"],[1597756680,"177"],[1597756800,"155"],[1597756920,"202"],[1597757040,"152"],[1597757160,"345"],[1597757280,"167"],[1597757400,"148"],[1597757520,"199"],[1597757640,"162"],[1597757760,"187"],[1597757880,"174"],[1597758000,"148"],[1597758120,"348"],[1597758240,"157"],[1597758360,"185"],[1597758480,"162"],[1597758600,"157"],[1597758720,"194"],[1597758840,"167"],[1597758960,"733"],[1597759080,"166"],[1597759200,"155"],[1597759320,"213"],[1597759440,"153"],[1597759560,"185"],[1597759680,"170"],[1597759800,"157"],[1597759920,"352"],[1597760040,"163"],[1597760160,"183"],[1597760280,"183"],[1597760400,"147"],[1597760520,"194"],[1597760640,"158"],[1597760760,"349"],[1597760880,"167"],[1597761000,"147"],[1597761120,"194"],[1597761240,"151"],[1597761360,"191"],[1597761480,"150"],[1597761600,"157"],[1597761720,"356"],[1597761840,"157"],[1597761960,"190"],[1597762080,"166"],[1597762200,"147"],[1597762320,"207"],[1597762440,"151"],[1597762560,"731"],[1597762680,"160"],[1597762800,"157"],[1597762920,"205"],[1597763040,"151"],[1597763160,"185"],[1597763280,"155"],[1597763400,"153"],[1597763520,"356"],[1597763640,"146"],[1597763760,"196"],[1597763880,"162"],[1597764000,"156"],[1597764120,"190"],[1597764240,"162"],[1597764360,"348"],[1597764480,"176"],[1597764600,"151"],[1597764720,"194"],[1597764840,"166"],[1597764960,"189"],[1597765080,"168"],[1597765200,"152"],[1597765320,"355"],[1597765440,"156"],[1597765560,"184"],[1597765680,"169"],[1597765800,"152"],[1597765920,"196"],[1597766040,"162"],[1597766160,"731"],[1597766280,"160"],[1597766400,"163"],[1597766520,"232"],[1597766640,"162"],[1597766760,"182"],[1597766880,"166"],[1597767000,"158"],[1597767120,"364"],[1597767240,"152"],[1597767360,"187"],[1597767480,"171"],[1597767600,"148"],[1597767720,"203"],[1597767840,"162"],[1597767960,"340"],[1597768080,"185"],[1597768200,"155"],[1597768320,"214"],[1597768440,"158"],[1597768560,"191"],[1597768680,"173"],[1597768800,"157"],[1597768920,"357"],[1597769040,"173"],[1597769160,"190"],[1597769280,"170"],[1597769400,"146"],[1597769520,"194"],[1597769640,"157"],[1597769760,"765"],[1597769880,"172"],[1597770000,"153"],[1597770120,"209"],[1597770240,"156"],[1597770360,"187"],[1597770480,"183"],[1597770600,"152"],[1597770720,"364"],[1597770840,"165"],[1597770960,"191"],[1597771080,"161"],[1597771200,"176"],[1597771320,"210"],[1597771440,"156"],[1597771560,"355"],[1597771680,"171"],[1597771800,"155"],[1597771920,"210"],[1597772040,"157"],[1597772160,"175"],[1597772280,"177"],[1597772400,"157"],[1597772520,"362"],[1597772640,"160"],[1597772760,"191"],[1597772880,"171"],[1597773000,"156"],[1597773120,"204"],[1597773240,"161"],[1597773360,"739"],[1597773480,"175"],[1597773600,"147"],[1597773720,"207"],[1597773840,"157"],[1597773960,"187"],[1597774080,"168"],[1597774200,"158"],[1597774320,"365"],[1597774440,"153"],[1597774560,"185"],[1597774680,"178"],[1597774800,"158"],[1597774920,"199"],[1597775040,"158"],[1597775160,"347"],[1597775280,"174"],[1597775400,"151"],[1597775520,"199"],[1597775640,"168"],[1597775760,"185"],[1597775880,"168"],[1597776000,"151"],[1597776120,"365"],[1597776240,"156"],[1597776360,"184"],[1597776480,"171"],[1597776600,"160"],[1597776720,"206"],[1597776840,"161"],[1597776960,"735"],[1597777080,"178"],[1597777200,"156"],[1597777320,"197"],[1597777440,"157"],[1597777560,"192"],[1597777680,"165"],[1597777800,"157"],[1597777920,"355"],[1597778040,"151"],[1597778160,"184"],[1597778280,"165"],[1597778400,"151"],[1597778520,"188"],[1597778640,"154"],[1597778760,"353"],[1597778880,"166"],[1597779000,"151"],[1597779120,"202"],[1597779240,"160"],[1597779360,"186"],[1597779480,"170"],[1597779600,"152"],[1597779720,"356"],[1597779840,"151"],[1597779960,"190"],[1597780080,"161"],[1597780200,"157"],[1597780320,"197"],[1597780440,"176"],[1597780560,"732"],[1597780680,"170"],[1597780800,"152"],[1597780920,"230"],[1597781040,"167"],[1597781160,"175"],[1597781280,"175"],[1597781400,"153"],[1597781520,"349"],[1597781640,"158"],[1597781760,"192"],[1597781880,"160"],[1597782000,"157"],[1597782120,"198"],[1597782240,"153"],[1597782360,"339"],[1597782480,"172"],[1597782600,"152"],[1597782720,"205"],[1597782840,"157"],[1597782960,"182"],[1597783080,"166"],[1597783200,"157"],[1597783320,"349"],[1597783440,"157"],[1597783560,"189"],[1597783680,"176"],[1597783800,"151"],[1597783920,"199"],[1597784040,"161"],[1597784160,"760"],[1597784280,"179"],[1597784400,"153"],[1597784520,"245"],[1597784640,"160"],[1597784760,"183"],[1597784880,"172"],[1597785000,"156"],[1597785120,"358"],[1597785240,"163"],[1597785360,"184"],[1597785480,"152"],[1597785600,"168"],[1597785720,"203"],[1597785840,"155"],[1597785960,"344"],[1597786080,"172"],[1597786200,"150"],[1597786320,"188"],[1597786440,"153"],[1597786560,"189"],[1597786680,"156"],[1597786800,"147"],[1597786920,"396"],[1597787040,"157"],[1597787160,"206"],[1597787280,"159"],[1597787400,"157"],[1597787520,"301"],[1597787640,"152"],[1597787760,"740"],[1597787880,"181"],[1597788000,"161"],[1597788120,"219"],[1597788240,"148"],[1597788360,"191"],[1597788480,"168"],[1597788600,"160"],[1597788720,"376"],[1597788840,"153"],[1597788960,"197"],[1597789080,"167"],[1597789200,"156"],[1597789320,"205"],[1597789440,"146"],[1597789560,"349"],[1597789680,"163"],[1597789800,"147"],[1597789920,"199"],[1597790040,"151"],[1597790160,"194"],[1597790280,"164"],[1597790400,"148"],[1597790520,"345"],[1597790640,"158"],[1597790760,"197"],[1597790880,"166"],[1597791000,"147"],[1597791120,"195"],[1597791240,"153"],[1597791360,"735"],[1597791480,"157"],[1597791600,"152"],[1597791720,"203"],[1597791840,"147"],[1597791960,"186"],[1597792080,"163"],[1597792200,"146"],[1597792320,"349"],[1597792440,"165"],[1597792560,"184"],[1597792680,"166"],[1597792800,"153"],[1597792920,"208"],[1597793040,"153"],[1597793160,"347"],[1597793280,"167"],[1597793400,"148"],[1597793520,"195"],[1597793640,"158"],[1597793760,"192"],[1597793880,"159"],[1597794000,"147"],[1597794120,"347"],[1597794240,"164"],[1597794360,"182"],[1597794480,"166"],[1597794600,"151"],[1597794720,"197"],[1597794840,"150"],[1597794960,"741"],[1597795080,"166"],[1597795200,"158"],[1597795320,"221"],[1597795440,"156"],[1597795560,"192"],[1597795680,"163"],[1597795800,"148"],[1597795920,"345"],[1597796040,"169"],[1597796160,"198"],[1597796280,"176"],[1597796400,"147"],[1597796520,"209"],[1597796640,"153"],[1597796760,"339"],[1597796880,"172"],[1597797000,"153"],[1597797120,"203"],[1597797240,"153"],[1597797360,"191"],[1597797480,"165"],[1597797600,"158"],[1597797720,"355"],[1597797840,"163"],[1597797960,"180"],[1597798080,"164"],[1597798200,"157"],[1597798320,"191"],[1597798440,"156"],[1597798560,"771"],[1597798680,"163"],[1597798800,"148"],[1597798920,"217"],[1597799040,"152"],[1597799160,"191"],[1597799280,"156"],[1597799400,"147"],[1597799520,"360"],[1597799640,"147"],[1597799760,"194"],[1597799880,"159"],[1597800000,"146"],[1597800120,"194"],[1597800240,"147"],[1597800360,"335"],[1597800480,"162"],[1597800600,"151"],[1597800720,"192"],[1597800840,"157"],[1597800960,"177"],[1597801080,"173"],[1597801200,"153"],[1597801320,"352"],[1597801440,"155"],[1597801560,"171"],[1597801680,"184"],[1597801800,"151"],[1597801920,"204"],[1597802040,"166"],[1597802160,"742"],[1597802280,"171"],[1597802400,"158"],[1597802520,"195"],[1597802640,"161"],[1597802760,"197"],[1597802880,"163"],[1597803000,"152"],[1597803120,"352"],[1597803240,"168"],[1597803360,"183"],[1597803480,"163"],[1597803600,"163"],[1597803720,"205"],[1597803840,"156"],[1597803960,"332"],[1597804080,"171"],[1597804200,"151"],[1597804320,"209"],[1597804440,"166"],[1597804560,"184"],[1597804680,"175"],[1597804800,"152"],[1597804920,"360"],[1597805040,"157"],[1597805160,"184"],[1597805280,"172"],[1597805400,"156"],[1597805520,"205"],[1597805640,"150"],[1597805760,"735"],[1597805880,"163"],[1597806000,"155"],[1597806120,"198"],[1597806240,"157"],[1597806360,"199"],[1597806480,"166"],[1597806600,"153"],[1597806720,"349"],[1597806840,"165"],[1597806960,"204"],[1597807080,"150"],[1597807200,"170"],[1597807320,"202"],[1597807440,"161"],[1597807560,"342"],[1597807680,"185"],[1597807800,"151"],[1597807920,"208"],[1597808040,"161"],[1597808160,"196"],[1597808280,"161"],[1597808400,"162"],[1597808520,"355"],[1597808640,"156"],[1597808760,"196"],[1597808880,"176"],[1597809000,"152"],[1597809120,"213"],[1597809240,"161"],[1597809360,"711"],[1597809480,"168"],[1597809600,"157"],[1597809720,"231"],[1597809840,"163"],[1597809960,"183"],[1597810080,"178"],[1597810200,"153"],[1597810320,"368"],[1597810440,"153"],[1597810560,"185"],[1597810680,"172"],[1597810800,"152"],[1597810920,"199"],[1597811040,"158"],[1597811160,"341"],[1597811280,"176"],[1597811400,"148"],[1597811520,"203"],[1597811640,"162"],[1597811760,"181"],[1597811880,"177"],[1597812000,"160"],[1597812120,"359"],[1597812240,"159"],[1597812360,"191"],[1597812480,"168"],[1597812600,"161"],[1597812720,"205"],[1597812840,"170"],[1597812960,"761"],[1597813080,"168"],[1597813200,"148"],[1597813320,"206"],[1597813440,"161"],[1597813560,"192"],[1597813680,"163"],[1597813800,"156"],[1597813920,"363"],[1597814040,"164"],[1597814160,"189"],[1597814280,"160"],[1597814400,"167"],[1597814520,"207"],[1597814640,"153"],[1597814760,"340"],[1597814880,"168"],[1597815000,"162"],[1597815120,"197"],[1597815240,"152"],[1597815360,"195"],[1597815480,"172"],[1597815600,"152"],[1597815720,"353"],[1597815840,"159"],[1597815960,"192"],[1597816080,"165"],[1597816200,"162"],[1597816320,"197"],[1597816440,"157"],[1597816560,"732"],[1597816680,"161"],[1597816800,"152"],[1597816920,"198"],[1597817040,"158"],[1597817160,"190"],[1597817280,"166"],[1597817400,"152"],[1597817520,"345"],[1597817640,"155"],[1597817760,"181"],[1597817880,"165"],[1597818000,"155"],[1597818120,"199"],[1597818240,"153"],[1597818360,"334"],[1597818480,"175"],[1597818600,"156"],[1597818720,"208"],[1597818840,"156"],[1597818960,"185"],[1597819080,"175"],[1597819200,"149"],[1597819320,"349"],[1597819440,"162"],[1597819560,"176"],[1597819680,"165"],[1597819800,"158"],[1597819920,"198"],[1597820040,"151"],[1597820160,"745"],[1597820280,"170"],[1597820400,"153"],[1597820520,"192"],[1597820640,"167"],[1597820760,"181"],[1597820880,"171"],[1597821000,"149"],[1597821120,"349"],[1597821240,"162"],[1597821360,"182"],[1597821480,"174"],[1597821600,"157"],[1597821720,"199"],[1597821840,"104"],[1597821960,"19"],[1597822920,"6"],[1597823760,"9"]]},{"metric":{"ServiceName":"GHI"},"values":[[1597824240,"5"],[1597824360,"2"],[1597824480,"2"]]},{"metric":{"ServiceName":"JKL"},"values":[[1597701600,"589"],[1597701840,"600"],[1597702080,"589"],[1597702200,"589"],[1597702440,"589"],[1597702680,"589"],[1597702920,"589"],[1597703160,"589"],[1597703400,"589"],[1597703640,"600"],[1597703880,"589"],[1597704120,"589"],[1597704240,"589"],[1597704480,"589"],[1597704720,"589"],[1597704960,"589"],[1597705200,"589"],[1597705440,"600"],[1597705680,"589"],[1597705920,"589"],[1597706040,"544"],[1597706160,"45"],[1597706280,"589"],[1597706520,"589"],[1597706760,"589"],[1597707000,"589"],[1597707240,"600"],[1597707480,"589"],[1597707720,"589"],[1597707960,"589"],[1597708080,"589"],[1597708320,"589"],[1597708560,"589"],[1597708800,"589"],[1597709040,"600"],[1597709280,"589"],[1597709520,"589"],[1597709760,"589"],[1597709880,"589"],[1597710120,"589"],[1597710360,"589"],[1597710600,"589"],[1597710840,"600"],[1597711080,"589"],[1597711320,"589"],[1597711560,"589"],[1597711800,"589"],[1597711920,"589"],[1597712160,"589"],[1597712400,"589"],[1597712640,"600"],[1597712880,"589"],[1597713120,"589"],[1597713360,"589"],[1597713600,"589"],[1597713720,"589"],[1597713960,"589"],[1597714200,"589"],[1597714440,"600"],[1597714680,"589"],[1597714920,"589"],[1597715160,"589"],[1597715400,"589"],[1597715640,"589"],[1597715760,"589"],[1597716000,"589"],[1597716240,"600"],[1597716480,"589"],[1597716720,"589"],[1597716960,"589"],[1597717200,"589"],[1597717440,"589"],[1597717680,"589"],[1597717800,"589"],[1597718040,"600"],[1597718280,"589"],[1597718520,"589"],[1597718760,"589"],[1597719000,"589"],[1597719240,"589"],[1597719480,"589"],[1597719600,"589"],[1597719840,"600"],[1597720080,"589"],[1597720320,"589"],[1597720560,"589"],[1597720800,"589"],[1597721040,"589"],[1597721280,"589"],[1597721520,"589"],[1597721640,"600"],[1597721880,"589"],[1597722120,"589"],[1597722360,"589"],[1597722600,"589"],[1597722840,"589"],[1597723080,"589"],[1597723320,"589"],[1597723440,"600"],[1597723680,"589"],[1597723920,"589"],[1597724160,"589"],[1597724400,"589"],[1597724640,"589"],[1597724880,"589"],[1597725120,"589"],[1597725360,"600"],[1597725480,"589"],[1597725720,"589"],[1597725960,"589"],[1597726200,"589"],[1597726440,"589"],[1597726680,"589"],[1597726920,"589"],[1597727160,"600"],[1597727400,"589"],[1597727520,"589"],[1597727760,"589"],[1597728000,"589"],[1597728240,"589"],[1597728480,"589"],[1597728720,"589"],[1597728960,"600"],[1597729200,"589"],[1597729320,"589"],[1597729560,"589"],[1597729800,"589"],[1597730040,"589"],[1597730280,"589"],[1597730520,"589"],[1597730760,"600"],[1597731000,"589"],[1597731240,"589"],[1597731360,"589"],[1597731600,"589"],[1597731840,"589"],[1597732080,"589"],[1597732320,"589"],[1597732560,"600"],[1597732800,"589"],[1597733040,"589"],[1597733160,"455"],[1597733280,"134"],[1597733400,"589"],[1597733640,"589"],[1597733880,"589"],[1597734120,"589"],[1597734360,"600"],[1597734600,"589"],[1597734840,"589"],[1597735080,"589"],[1597735200,"589"],[1597735440,"589"],[1597735680,"589"],[1597735920,"589"],[1597736160,"600"],[1597736400,"589"],[1597736640,"589"],[1597736880,"589"],[1597737120,"589"],[1597737240,"589"],[1597737480,"589"],[1597737720,"589"],[1597737960,"600"],[1597738200,"589"],[1597738440,"589"],[1597738680,"589"],[1597738920,"589"],[1597739040,"589"],[1597739280,"589"],[1597739520,"589"],[1597739760,"600"],[1597740000,"589"],[1597740240,"589"],[1597740480,"589"],[1597740720,"589"],[1597740960,"589"],[1597741080,"589"],[1597741320,"589"],[1597741560,"600"],[1597741800,"589"],[1597742040,"589"],[1597742280,"589"],[1597742520,"589"],[1597742760,"589"],[1597742880,"589"],[1597743120,"589"],[1597743360,"600"],[1597743600,"589"],[1597743840,"589"],[1597744080,"589"],[1597744320,"589"],[1597744560,"589"],[1597744800,"589"],[1597744920,"589"],[1597745160,"600"],[1597745400,"589"],[1597745640,"589"],[1597745880,"589"],[1597746120,"589"],[1597746360,"589"],[1597746600,"589"],[1597746720,"589"],[1597746960,"600"],[1597747200,"589"],[1597747440,"589"],[1597747680,"589"],[1597747920,"589"],[1597748160,"589"],[1597748400,"589"],[1597748640,"589"],[1597748760,"600"],[1597749000,"589"],[1597749240,"589"],[1597749480,"589"],[1597749720,"589"],[1597749960,"589"],[1597750200,"589"],[1597750440,"589"],[1597750680,"600"],[1597750800,"589"],[1597751040,"589"],[1597751280,"589"],[1597751520,"589"],[1597751760,"589"],[1597752000,"589"],[1597752240,"589"],[1597752480,"600"],[1597752600,"589"],[1597752840,"589"],[1597753080,"589"],[1597753320,"589"],[1597753560,"589"],[1597753800,"589"],[1597754040,"589"],[1597754280,"600"],[1597754520,"589"],[1597754640,"589"],[1597754880,"589"],[1597755120,"589"],[1597755360,"589"],[1597755600,"589"],[1597755840,"589"],[1597756080,"600"],[1597756320,"589"],[1597756440,"589"],[1597756680,"589"],[1597756920,"589"],[1597757160,"589"],[1597757400,"589"],[1597757640,"589"],[1597757880,"600"],[1597758120,"589"],[1597758360,"589"],[1597758480,"589"],[1597758720,"589"],[1597758960,"589"],[1597759200,"589"],[1597759440,"589"],[1597759680,"600"],[1597759920,"589"],[1597760160,"589"],[1597760400,"589"],[1597760520,"589"],[1597760760,"589"],[1597761000,"589"],[1597761240,"589"],[1597761480,"600"],[1597761720,"589"],[1597761960,"589"],[1597762200,"589"],[1597762320,"589"],[1597762560,"589"],[1597762800,"589"],[1597763040,"589"],[1597763280,"600"],[1597763520,"589"],[1597763760,"589"],[1597764000,"589"],[1597764240,"589"],[1597764360,"589"],[1597764600,"589"],[1597764840,"589"],[1597765080,"600"],[1597765320,"589"],[1597765560,"589"],[1597765800,"589"],[1597766040,"589"],[1597766160,"589"],[1597766400,"589"],[1597766640,"589"],[1597766880,"600"],[1597767120,"589"],[1597767360,"589"],[1597767600,"589"],[1597767840,"589"],[1597768080,"589"],[1597768200,"589"],[1597768440,"589"],[1597768680,"600"],[1597768920,"589"],[1597769160,"589"],[1597769400,"589"],[1597769640,"589"],[1597769880,"589"],[1597770120,"589"],[1597770240,"589"],[1597770480,"600"],[1597770720,"589"],[1597770960,"589"],[1597771200,"589"],[1597771440,"589"],[1597771680,"589"],[1597771920,"589"],[1597772040,"589"],[1597772280,"600"],[1597772520,"589"],[1597772760,"589"],[1597773000,"589"],[1597773240,"589"],[1597773480,"589"],[1597773720,"589"],[1597773960,"589"],[1597774080,"600"],[1597774320,"589"],[1597774560,"589"],[1597774800,"589"],[1597775040,"589"],[1597775280,"589"],[1597775520,"589"],[1597775760,"589"],[1597775880,"600"],[1597776120,"589"],[1597776360,"589"],[1597776600,"589"],[1597776840,"589"],[1597777080,"589"],[1597777320,"589"],[1597777560,"589"],[1597777800,"600"],[1597777920,"589"],[1597778160,"589"],[1597778400,"589"],[1597778640,"589"],[1597778880,"589"],[1597779120,"589"],[1597779360,"589"],[1597779600,"600"],[1597779840,"589"],[1597779960,"589"],[1597780200,"589"],[1597780440,"589"],[1597780680,"589"],[1597780920,"589"],[1597781160,"589"],[1597781400,"600"],[1597781640,"589"],[1597781760,"589"],[1597782000,"589"],[1597782240,"589"],[1597782480,"589"],[1597782720,"589"],[1597782960,"589"],[1597783200,"600"],[1597783440,"589"],[1597783680,"589"],[1597783800,"589"],[1597784040,"589"],[1597784280,"589"],[1597784520,"589"],[1597784760,"589"],[1597785000,"600"],[1597785240,"589"],[1597785480,"589"],[1597785600,"589"],[1597785840,"589"],[1597786080,"589"],[1597786320,"589"],[1597786560,"589"],[1597786800,"600"],[1597787040,"589"],[1597787280,"589"],[1597787520,"589"],[1597787640,"589"],[1597787880,"589"],[1597788120,"589"],[1597788360,"589"],[1597788600,"600"],[1597788840,"589"],[1597789080,"589"],[1597789320,"589"],[1597789560,"589"],[1597789680,"589"],[1597789920,"589"],[1597790160,"589"],[1597790400,"600"],[1597790640,"589"],[1597790880,"589"],[1597791120,"589"],[1597791360,"589"],[1597791480,"589"],[1597791720,"589"],[1597791960,"589"],[1597792200,"600"],[1597792440,"589"],[1597792680,"589"],[1597792920,"589"],[1597793160,"589"],[1597793400,"589"],[1597793520,"589"],[1597793760,"589"],[1597794000,"600"],[1597794240,"589"],[1597794480,"589"],[1597794720,"589"],[1597794960,"589"],[1597795200,"589"],[1597795320,"589"],[1597795560,"589"],[1597795800,"600"],[1597796040,"589"],[1597796280,"589"],[1597796520,"589"],[1597796760,"589"],[1597797000,"589"],[1597797240,"589"],[1597797360,"589"],[1597797600,"600"],[1597797840,"589"],[1597798080,"589"],[1597798320,"589"],[1597798560,"589"],[1597798800,"589"],[1597799040,"589"],[1597799160,"589"],[1597799400,"600"],[1597799640,"589"],[1597799880,"589"],[1597800120,"589"],[1597800360,"589"],[1597800600,"589"],[1597800840,"589"],[1597801080,"589"],[1597801200,"600"],[1597801440,"589"],[1597801680,"589"],[1597801920,"589"],[1597802160,"589"],[1597802400,"589"],[1597802640,"589"],[1597802880,"589"],[1597803120,"600"],[1597803240,"589"],[1597803480,"589"],[1597803720,"589"],[1597803960,"589"],[1597804200,"589"],[1597804440,"589"],[1597804680,"589"],[1597804920,"600"],[1597805040,"589"],[1597805280,"589"],[1597805520,"589"],[1597805760,"589"],[1597806000,"589"],[1597806240,"589"],[1597806480,"589"],[1597806720,"600"],[1597806960,"589"],[1597807080,"589"],[1597807320,"589"],[1597807560,"589"],[1597807800,"589"],[1597808040,"589"],[1597808280,"589"],[1597808520,"600"],[1597808760,"589"],[1597808880,"589"],[1597809120,"589"],[1597809360,"589"],[1597809600,"589"],[1597809840,"589"],[1597810080,"589"],[1597810320,"600"],[1597810560,"589"],[1597810800,"589"],[1597810920,"589"],[1597811160,"589"],[1597811400,"589"],[1597811640,"589"],[1597811880,"589"],[1597812120,"600"],[1597812360,"589"],[1597812600,"589"],[1597812720,"589"],[1597812960,"589"],[1597813200,"589"],[1597813440,"589"],[1597813680,"589"],[1597813920,"600"],[1597814160,"589"],[1597814400,"589"],[1597814640,"589"],[1597814760,"589"],[1597815000,"589"],[1597815240,"589"],[1597815480,"589"],[1597815720,"600"],[1597815960,"589"],[1597816200,"589"],[1597816440,"589"],[1597816680,"589"],[1597816800,"589"],[1597817040,"589"],[1597817280,"589"],[1597817520,"600"],[1597817760,"589"],[1597818000,"589"],[1597818240,"589"],[1597818480,"589"],[1597818600,"589"],[1597818840,"589"],[1597819080,"589"],[1597819320,"600"],[1597819560,"589"],[1597819800,"589"],[1597820040,"589"],[1597820280,"589"],[1597820520,"589"],[1597820640,"589"],[1597820880,"589"],[1597821120,"600"],[1597821360,"273"]]},{"metric":{"ServiceName":"MNO"},"values":[[1597701600,"24"],[1597701720,"24"],[1597701840,"24"],[1597701960,"24"],[1597702080,"24"],[1597702200,"24"],[1597702320,"24"],[1597702440,"24"],[1597702560,"24"],[1597702680,"24"],[1597702800,"24"],[1597702920,"24"],[1597703040,"24"],[1597703160,"24"],[1597703280,"24"],[1597703400,"24"],[1597703520,"24"],[1597703640,"24"],[1597703760,"24"],[1597703880,"24"],[1597704000,"23"],[1597704120,"24"],[1597704240,"24"],[1597704360,"24"],[1597704480,"24"],[1597704600,"24"],[1597704720,"24"],[1597704840,"24"],[1597704960,"24"],[1597705080,"24"],[1597705200,"24"],[1597705320,"24"],[1597705440,"24"],[1597705560,"24"],[1597705680,"24"],[1597705800,"24"],[1597705920,"24"],[1597706040,"24"],[1597706160,"24"],[1597706280,"24"],[1597706400,"24"],[1597706520,"24"],[1597706640,"24"],[1597706760,"24"],[1597706880,"24"],[1597707000,"24"],[1597707120,"24"],[1597707240,"24"],[1597707360,"24"],[1597707480,"24"],[1597707600,"24"],[1597707720,"24"],[1597707840,"24"],[1597707960,"24"],[1597708080,"24"],[1597708200,"23"],[1597708320,"24"],[1597708440,"24"],[1597708560,"24"],[1597708680,"24"],[1597708800,"24"],[1597708920,"24"],[1597709040,"24"],[1597709160,"24"],[1597709280,"24"],[1597709400,"24"],[1597709520,"24"],[1597709640,"24"],[1597709760,"24"],[1597709880,"24"],[1597710000,"24"],[1597710120,"24"],[1597710240,"24"],[1597710360,"24"],[1597710480,"24"],[1597710600,"24"],[1597710720,"24"],[1597710840,"24"],[1597710960,"24"],[1597711080,"24"],[1597711200,"24"],[1597711320,"24"],[1597711440,"24"],[1597711560,"24"],[1597711680,"24"],[1597711800,"23"],[1597711920,"24"],[1597712040,"24"],[1597712160,"24"],[1597712280,"24"],[1597712400,"24"],[1597712520,"24"],[1597712640,"24"],[1597712760,"24"],[1597712880,"24"],[1597713000,"24"],[1597713120,"24"],[1597713240,"24"],[1597713360,"24"],[1597713480,"24"],[1597713600,"24"],[1597713720,"24"],[1597713840,"24"],[1597713960,"24"],[1597714080,"24"],[1597714200,"24"],[1597714320,"24"],[1597714440,"24"],[1597714560,"24"],[1597714680,"24"],[1597714800,"24"],[1597714920,"24"],[1597715040,"24"],[1597715160,"24"],[1597715280,"24"],[1597715400,"24"],[1597715520,"24"],[1597715640,"24"],[1597715760,"23"],[1597715880,"24"],[1597716000,"24"],[1597716120,"24"],[1597716240,"24"],[1597716360,"24"],[1597716480,"24"],[1597716600,"24"],[1597716720,"24"],[1597716840,"24"],[1597716960,"24"],[1597717080,"24"],[1597717200,"24"],[1597717320,"24"],[1597717440,"24"],[1597717560,"24"],[1597717680,"24"],[1597717800,"24"],[1597717920,"24"],[1597718040,"24"],[1597718160,"24"],[1597718280,"24"],[1597718400,"24"],[1597718520,"24"],[1597718640,"24"],[1597718760,"24"],[1597718880,"24"],[1597719000,"24"],[1597719120,"24"],[1597719240,"24"],[1597719360,"23"],[1597719480,"24"],[1597719600,"24"],[1597719720,"24"],[1597719840,"24"],[1597719960,"24"],[1597720080,"24"],[1597720200,"24"],[1597720320,"24"],[1597720440,"24"],[1597720560,"24"],[1597720680,"24"],[1597720800,"24"],[1597720920,"24"],[1597721040,"24"],[1597721160,"24"],[1597721280,"24"],[1597721400,"24"],[1597721520,"24"],[1597721640,"24"],[1597721760,"24"],[1597721880,"24"],[1597722000,"24"],[1597722120,"24"],[1597722240,"24"],[1597722360,"24"],[1597722480,"24"],[1597722600,"24"],[1597722720,"24"],[1597722840,"24"],[1597722960,"24"],[1597723080,"23"],[1597723200,"24"],[1597723320,"24"],[1597723440,"24"],[1597723560,"24"],[1597723680,"24"],[1597723800,"24"],[1597723920,"24"],[1597724040,"24"],[1597724160,"24"],[1597724280,"24"],[1597724400,"24"],[1597724520,"24"],[1597724640,"24"],[1597724760,"24"],[1597724880,"24"],[1597725000,"24"],[1597725120,"24"],[1597725240,"24"],[1597725360,"24"],[1597725480,"24"],[1597725600,"24"],[1597725720,"24"],[1597725840,"24"],[1597725960,"24"],[1597726080,"24"],[1597726200,"24"],[1597726320,"24"],[1597726440,"24"],[1597726560,"24"],[1597726680,"24"],[1597726800,"24"],[1597726920,"24"],[1597727040,"24"],[1597727160,"24"],[1597727280,"23"],[1597727400,"24"],[1597727520,"24"],[1597727640,"24"],[1597727760,"24"],[1597727880,"24"],[1597728000,"24"],[1597728120,"24"],[1597728240,"24"],[1597728360,"24"],[1597728480,"24"],[1597728600,"24"],[1597728720,"24"],[1597728840,"24"],[1597728960,"24"],[1597729080,"24"],[1597729200,"24"],[1597729320,"24"],[1597729440,"24"],[1597729560,"24"],[1597729680,"24"],[1597729800,"24"],[1597729920,"24"],[1597730040,"24"],[1597730160,"24"],[1597730280,"24"],[1597730400,"24"],[1597730520,"24"],[1597730640,"24"],[1597730760,"24"],[1597730880,"24"],[1597731000,"24"],[1597731120,"24"],[1597731240,"24"],[1597731360,"24"],[1597731480,"24"],[1597731600,"24"],[1597731720,"24"],[1597731840,"23"],[1597731960,"24"],[1597732080,"24"],[1597732200,"24"],[1597732320,"24"],[1597732440,"24"],[1597732560,"24"],[1597732680,"24"],[1597732800,"24"],[1597732920,"24"],[1597733040,"24"],[1597733160,"24"],[1597733280,"24"],[1597733400,"24"],[1597733520,"24"],[1597733640,"24"],[1597733760,"24"],[1597733880,"24"],[1597734000,"24"],[1597734120,"24"],[1597734240,"24"],[1597734360,"24"],[1597734480,"24"],[1597734600,"24"],[1597734720,"24"],[1597734840,"24"],[1597734960,"24"],[1597735080,"24"],[1597735200,"24"],[1597735320,"24"],[1597735440,"24"],[1597735560,"23"],[1597735680,"24"],[1597735800,"24"],[1597735920,"24"],[1597736040,"24"],[1597736160,"24"],[1597736280,"24"],[1597736400,"24"],[1597736520,"24"],[1597736640,"24"],[1597736760,"24"],[1597736880,"24"],[1597737000,"24"],[1597737120,"24"],[1597737240,"24"],[1597737360,"24"],[1597737480,"24"],[1597737600,"24"],[1597737720,"24"],[1597737840,"24"],[1597737960,"24"],[1597738080,"24"],[1597738200,"24"],[1597738320,"24"],[1597738440,"24"],[1597738560,"24"],[1597738680,"24"],[1597738800,"24"],[1597738920,"24"],[1597739040,"24"],[1597739160,"24"],[1597739280,"24"],[1597739400,"24"],[1597739520,"24"],[1597739640,"23"],[1597739760,"24"],[1597739880,"24"],[1597740000,"24"],[1597740120,"24"],[1597740240,"24"],[1597740360,"24"],[1597740480,"24"],[1597740600,"24"],[1597740720,"24"],[1597740840,"24"],[1597740960,"24"],[1597741080,"24"],[1597741200,"24"],[1597741320,"24"],[1597741440,"24"],[1597741560,"24"],[1597741680,"24"],[1597741800,"24"],[1597741920,"24"],[1597742040,"24"],[1597742160,"24"],[1597742280,"24"],[1597742400,"24"],[1597742520,"24"],[1597742640,"24"],[1597742760,"24"],[1597742880,"24"],[1597743000,"24"],[1597743120,"24"],[1597743240,"24"],[1597743360,"23"],[1597743480,"24"],[1597743600,"24"],[1597743720,"24"],[1597743840,"24"],[1597743960,"24"],[1597744080,"24"],[1597744200,"24"],[1597744320,"24"],[1597744440,"24"],[1597744560,"24"],[1597744680,"24"],[1597744800,"24"],[1597744920,"24"],[1597745040,"24"],[1597745160,"24"],[1597745280,"24"],[1597745400,"24"],[1597745520,"24"],[1597745640,"24"],[1597745760,"24"],[1597745880,"24"],[1597746000,"24"],[1597746120,"24"],[1597746240,"24"],[1597746360,"24"],[1597746480,"24"],[1597746600,"24"],[1597746720,"24"],[1597746840,"24"],[1597746960,"24"],[1597747080,"24"],[1597747200,"24"],[1597747320,"24"],[1597747440,"23"],[1597747560,"24"],[1597747680,"24"],[1597747800,"24"],[1597747920,"24"],[1597748040,"24"],[1597748160,"24"],[1597748280,"24"],[1597748400,"24"],[1597748520,"24"],[1597748640,"24"],[1597748760,"24"],[1597748880,"24"],[1597749000,"24"],[1597749120,"24"],[1597749240,"24"],[1597749360,"24"],[1597749480,"24"],[1597749600,"24"],[1597749720,"24"],[1597749840,"24"],[1597749960,"24"],[1597750080,"24"],[1597750200,"24"],[1597750320,"24"],[1597750440,"24"],[1597750560,"24"],[1597750680,"24"],[1597750800,"24"],[1597750920,"24"],[1597751040,"24"],[1597751160,"24"],[1597751280,"24"],[1597751400,"24"],[1597751520,"23"],[1597751640,"24"],[1597751760,"24"],[1597751880,"24"],[1597752000,"24"],[1597752120,"24"],[1597752240,"24"],[1597752360,"24"],[1597752480,"24"],[1597752600,"24"],[1597752720,"24"],[1597752840,"24"],[1597752960,"24"],[1597753080,"24"],[1597753200,"24"],[1597753320,"24"],[1597753440,"24"],[1597753560,"24"],[1597753680,"24"],[1597753800,"24"],[1597753920,"24"],[1597754040,"24"],[1597754160,"24"],[1597754280,"24"],[1597754400,"24"],[1597754520,"24"],[1597754640,"24"],[1597754760,"24"],[1597754880,"24"],[1597755000,"24"],[1597755120,"24"],[1597755240,"24"],[1597755360,"23"],[1597755480,"24"],[1597755600,"24"],[1597755720,"24"],[1597755840,"24"],[1597755960,"24"],[1597756080,"24"],[1597756200,"24"],[1597756320,"24"],[1597756440,"24"],[1597756560,"24"],[1597756680,"24"],[1597756800,"24"],[1597756920,"24"],[1597757040,"24"],[1597757160,"24"],[1597757280,"24"],[1597757400,"24"],[1597757520,"24"],[1597757640,"24"],[1597757760,"24"],[1597757880,"24"],[1597758000,"24"],[1597758120,"24"],[1597758240,"24"],[1597758360,"24"],[1597758480,"24"],[1597758600,"24"],[1597758720,"24"],[1597758840,"24"],[1597758960,"24"],[1597759080,"24"],[1597759200,"23"],[1597759320,"24"],[1597759440,"24"],[1597759560,"24"],[1597759680,"24"],[1597759800,"24"],[1597759920,"24"],[1597760040,"24"],[1597760160,"24"],[1597760280,"24"],[1597760400,"24"],[1597760520,"24"],[1597760640,"24"],[1597760760,"24"],[1597760880,"24"],[1597761000,"24"],[1597761120,"24"],[1597761240,"24"],[1597761360,"24"],[1597761480,"24"],[1597761600,"24"],[1597761720,"24"],[1597761840,"24"],[1597761960,"24"],[1597762080,"24"],[1597762200,"24"],[1597762320,"24"],[1597762440,"24"],[1597762560,"24"],[1597762680,"24"],[1597762800,"24"],[1597762920,"24"],[1597763040,"24"],[1597763160,"23"],[1597763280,"24"],[1597763400,"24"],[1597763520,"24"],[1597763640,"24"],[1597763760,"24"],[1597763880,"24"],[1597764000,"24"],[1597764120,"24"],[1597764240,"24"],[1597764360,"24"],[1597764480,"24"],[1597764600,"24"],[1597764720,"24"],[1597764840,"24"],[1597764960,"24"],[1597765080,"24"],[1597765200,"24"],[1597765320,"24"],[1597765440,"24"],[1597765560,"24"],[1597765680,"24"],[1597765800,"24"],[1597765920,"24"],[1597766040,"24"],[1597766160,"24"],[1597766280,"24"],[1597766400,"24"],[1597766520,"24"],[1597766640,"24"],[1597766760,"24"],[1597766880,"23"],[1597767000,"24"],[1597767120,"24"],[1597767240,"24"],[1597767360,"24"],[1597767480,"24"],[1597767600,"24"],[1597767720,"24"],[1597767840,"24"],[1597767960,"24"],[1597768080,"24"],[1597768200,"24"],[1597768320,"24"],[1597768440,"24"],[1597768560,"24"],[1597768680,"24"],[1597768800,"24"],[1597768920,"24"],[1597769040,"24"],[1597769160,"24"],[1597769280,"24"],[1597769400,"24"],[1597769520,"24"],[1597769640,"24"],[1597769760,"24"],[1597769880,"24"],[1597770000,"24"],[1597770120,"24"],[1597770240,"24"],[1597770360,"24"],[1597770480,"24"],[1597770600,"24"],[1597770720,"23"],[1597770840,"24"],[1597770960,"24"],[1597771080,"24"],[1597771200,"24"],[1597771320,"24"],[1597771440,"24"],[1597771560,"24"],[1597771680,"24"],[1597771800,"24"],[1597771920,"24"],[1597772040,"24"],[1597772160,"24"],[1597772280,"24"],[1597772400,"24"],[1597772520,"24"],[1597772640,"24"],[1597772760,"24"],[1597772880,"24"],[1597773000,"24"],[1597773120,"24"],[1597773240,"24"],[1597773360,"24"],[1597773480,"24"],[1597773600,"24"],[1597773720,"24"],[1597773840,"24"],[1597773960,"24"],[1597774080,"24"],[1597774200,"23"],[1597774320,"24"],[1597774440,"24"],[1597774560,"24"],[1597774680,"24"],[1597774800,"24"],[1597774920,"24"],[1597775040,"24"],[1597775160,"24"],[1597775280,"24"],[1597775400,"24"],[1597775520,"24"],[1597775640,"24"],[1597775760,"24"],[1597775880,"24"],[1597776000,"24"],[1597776120,"24"],[1597776240,"24"],[1597776360,"24"],[1597776480,"24"],[1597776600,"24"],[1597776720,"24"],[1597776840,"24"],[1597776960,"24"],[1597777080,"24"],[1597777200,"24"],[1597777320,"24"],[1597777440,"24"],[1597777560,"24"],[1597777680,"24"],[1597777800,"24"],[1597777920,"24"],[1597778040,"24"],[1597778160,"23"],[1597778280,"24"],[1597778400,"24"],[1597778520,"24"],[1597778640,"24"],[1597778760,"24"],[1597778880,"24"],[1597779000,"24"],[1597779120,"24"],[1597779240,"24"],[1597779360,"24"],[1597779480,"24"],[1597779600,"24"],[1597779720,"24"],[1597779840,"24"],[1597779960,"24"],[1597780080,"24"],[1597780200,"24"],[1597780320,"24"],[1597780440,"24"],[1597780560,"24"],[1597780680,"24"],[1597780800,"24"],[1597780920,"24"],[1597781040,"24"],[1597781160,"24"],[1597781280,"24"],[1597781400,"24"],[1597781520,"24"],[1597781640,"24"],[1597781760,"24"],[1597781880,"24"],[1597782000,"24"],[1597782120,"24"],[1597782240,"24"],[1597782360,"23"],[1597782480,"24"],[1597782600,"24"],[1597782720,"24"],[1597782840,"24"],[1597782960,"24"],[1597783080,"24"],[1597783200,"24"],[1597783320,"24"],[1597783440,"24"],[1597783560,"24"],[1597783680,"24"],[1597783800,"24"],[1597783920,"24"],[1597784040,"24"],[1597784160,"24"],[1597784280,"24"],[1597784400,"24"],[1597784520,"24"],[1597784640,"24"],[1597784760,"24"],[1597784880,"24"],[1597785000,"24"],[1597785120,"24"],[1597785240,"24"],[1597785360,"24"],[1597785480,"24"],[1597785600,"24"],[1597785720,"24"],[1597785840,"24"],[1597785960,"23"],[1597786080,"25"],[1597786200,"23"],[1597786320,"24"],[1597786440,"24"],[1597786560,"24"],[1597786680,"24"],[1597786800,"24"],[1597786920,"24"],[1597787040,"24"],[1597787160,"24"],[1597787280,"24"],[1597787400,"24"],[1597787520,"24"],[1597787640,"24"],[1597787760,"24"],[1597787880,"24"],[1597788000,"24"],[1597788120,"24"],[1597788240,"24"],[1597788360,"24"],[1597788480,"24"],[1597788600,"24"],[1597788720,"24"],[1597788840,"24"],[1597788960,"24"],[1597789080,"24"],[1597789200,"24"],[1597789320,"24"],[1597789440,"24"],[1597789560,"24"],[1597789680,"24"],[1597789800,"24"],[1597789920,"24"],[1597790040,"23"],[1597790160,"24"],[1597790280,"24"],[1597790400,"24"],[1597790520,"24"],[1597790640,"24"],[1597790760,"24"],[1597790880,"24"],[1597791000,"24"],[1597791120,"24"],[1597791240,"24"],[1597791360,"24"],[1597791480,"24"],[1597791600,"24"],[1597791720,"24"],[1597791840,"24"],[1597791960,"24"],[1597792080,"24"],[1597792200,"24"],[1597792320,"24"],[1597792440,"24"],[1597792560,"24"],[1597792680,"24"],[1597792800,"24"],[1597792920,"24"],[1597793040,"24"],[1597793160,"24"],[1597793280,"24"],[1597793400,"24"],[1597793520,"24"],[1597793640,"24"],[1597793760,"24"],[1597793880,"24"],[1597794000,"24"],[1597794120,"23"],[1597794240,"24"],[1597794360,"24"],[1597794480,"24"],[1597794600,"24"],[1597794720,"24"],[1597794840,"24"],[1597794960,"24"],[1597795080,"24"],[1597795200,"24"],[1597795320,"24"],[1597795440,"24"],[1597795560,"24"],[1597795680,"24"],[1597795800,"24"],[1597795920,"24"],[1597796040,"24"],[1597796160,"24"],[1597796280,"24"],[1597796400,"24"],[1597796520,"24"],[1597796640,"24"],[1597796760,"24"],[1597796880,"24"],[1597797000,"24"],[1597797120,"24"],[1597797240,"24"],[1597797360,"24"],[1597797480,"24"],[1597797600,"24"],[1597797720,"24"],[1597797840,"24"],[1597797960,"24"],[1597798080,"24"],[1597798200,"24"],[1597798320,"24"],[1597798440,"23"],[1597798560,"24"],[1597798680,"24"],[1597798800,"24"],[1597798920,"24"],[1597799040,"24"],[1597799160,"24"],[1597799280,"24"],[1597799400,"24"],[1597799520,"24"],[1597799640,"24"],[1597799760,"24"],[1597799880,"24"],[1597800000,"24"],[1597800120,"24"],[1597800240,"24"],[1597800360,"24"],[1597800480,"24"],[1597800600,"24"],[1597800720,"24"],[1597800840,"24"],[1597800960,"24"],[1597801080,"24"],[1597801200,"24"],[1597801320,"24"],[1597801440,"24"],[1597801560,"24"],[1597801680,"24"],[1597801800,"24"],[1597801920,"24"],[1597802040,"24"],[1597802160,"24"],[1597802280,"24"],[1597802400,"24"],[1597802520,"23"],[1597802640,"24"],[1597802760,"24"],[1597802880,"24"],[1597803000,"24"],[1597803120,"24"],[1597803240,"24"],[1597803360,"24"],[1597803480,"24"],[1597803600,"24"],[1597803720,"24"],[1597803840,"24"],[1597803960,"24"],[1597804080,"24"],[1597804200,"24"],[1597804320,"24"],[1597804440,"24"],[1597804560,"24"],[1597804680,"24"],[1597804800,"24"],[1597804920,"24"],[1597805040,"24"],[1597805160,"24"],[1597805280,"24"],[1597805400,"24"],[1597805520,"24"],[1597805640,"24"],[1597805760,"24"],[1597805880,"24"],[1597806000,"24"],[1597806120,"24"],[1597806240,"24"],[1597806360,"23"],[1597806480,"24"],[1597806600,"24"],[1597806720,"24"],[1597806840,"24"],[1597806960,"24"],[1597807080,"24"],[1597807200,"24"],[1597807320,"24"],[1597807440,"24"],[1597807560,"24"],[1597807680,"24"],[1597807800,"24"],[1597807920,"24"],[1597808040,"24"],[1597808160,"24"],[1597808280,"24"],[1597808400,"24"],[1597808520,"24"],[1597808640,"24"],[1597808760,"24"],[1597808880,"24"],[1597809000,"24"],[1597809120,"24"],[1597809240,"24"],[1597809360,"24"],[1597809480,"24"],[1597809600,"24"],[1597809720,"24"],[1597809840,"24"],[1597809960,"24"],[1597810080,"24"],[1597810200,"23"],[1597810320,"24"],[1597810440,"24"],[1597810560,"24"],[1597810680,"24"],[1597810800,"24"],[1597810920,"24"],[1597811040,"24"],[1597811160,"24"],[1597811280,"24"],[1597811400,"24"],[1597811520,"24"],[1597811640,"24"],[1597811760,"24"],[1597811880,"24"],[1597812000,"24"],[1597812120,"24"],[1597812240,"24"],[1597812360,"24"],[1597812480,"24"],[1597812600,"24"],[1597812720,"24"],[1597812840,"24"],[1597812960,"24"],[1597813080,"24"],[1597813200,"24"],[1597813320,"24"],[1597813440,"24"],[1597813560,"24"],[1597813680,"24"],[1597813800,"23"],[1597813920,"24"],[1597814040,"24"],[1597814160,"24"],[1597814280,"24"],[1597814400,"24"],[1597814520,"24"],[1597814640,"24"],[1597814760,"24"],[1597814880,"24"],[1597815000,"24"],[1597815120,"24"],[1597815240,"24"],[1597815360,"24"],[1597815480,"24"],[1597815600,"24"],[1597815720,"24"],[1597815840,"24"],[1597815960,"24"],[1597816080,"24"],[1597816200,"24"],[1597816320,"24"],[1597816440,"24"],[1597816560,"24"],[1597816680,"24"],[1597816800,"24"],[1597816920,"24"],[1597817040,"24"],[1597817160,"24"],[1597817280,"23"],[1597817400,"24"],[1597817520,"24"],[1597817640,"24"],[1597817760,"24"],[1597817880,"24"],[1597818000,"24"],[1597818120,"24"],[1597818240,"24"],[1597818360,"24"],[1597818480,"24"],[1597818600,"24"],[1597818720,"24"],[1597818840,"24"],[1597818960,"24"],[1597819080,"24"],[1597819200,"24"],[1597819320,"24"],[1597819440,"24"],[1597819560,"24"],[1597819680,"24"],[1597819800,"24"],[1597819920,"24"],[1597820040,"24"],[1597820160,"24"],[1597820280,"24"],[1597820400,"24"],[1597820520,"24"],[1597820640,"24"],[1597820760,"24"],[1597820880,"24"],[1597821000,"23"],[1597821120,"24"],[1597821240,"6"]]},{"metric":{"ServiceName":"PQR"},"values":[[1597704120,"2"],[1597704240,"1"],[1597707840,"3"],[1597711440,"1"],[1597711560,"2"],[1597715160,"3"],[1597718880,"3"],[1597722480,"2"],[1597722600,"1"],[1597726200,"3"],[1597729800,"1"],[1597729920,"2"],[1597733520,"3"],[1597737240,"3"],[1597740840,"2"],[1597740960,"1"],[1597744560,"3"],[1597748160,"1"],[1597748280,"2"],[1597751880,"3"],[1597755600,"3"],[1597759200,"2"],[1597759320,"1"],[1597762920,"3"],[1597766520,"2"],[1597766640,"1"],[1597770240,"3"],[1597773960,"3"],[1597777560,"3"],[1597781280,"3"],[1597784880,"2"],[1597785000,"1"],[1597788600,"3"],[1597792200,"1"],[1597792320,"2"],[1597795920,"3"],[1597799640,"3"],[1597803240,"2"],[1597803360,"1"],[1597806960,"3"],[1597810560,"1"],[1597810680,"2"],[1597814280,"3"],[1597817880,"1"],[1597818000,"2"],[1597821600,"2"],[1597821720,"1"]]},{"metric":{"ServiceName":"STU"},"values":[[1597701600,"20"],[1597701720,"20"],[1597701840,"20"],[1597701960,"20"],[1597702080,"20"],[1597702200,"20"],[1597702320,"20"],[1597702440,"20"],[1597702560,"20"],[1597702680,"20"],[1597702800,"20"],[1597702920,"20"],[1597703040,"20"],[1597703160,"19"],[1597703280,"20"],[1597703400,"20"],[1597703520,"20"],[1597703640,"20"],[1597703760,"20"],[1597703880,"20"],[1597704000,"20"],[1597704120,"20"],[1597704240,"20"],[1597704360,"20"],[1597704480,"20"],[1597704600,"20"],[1597704720,"20"],[1597704840,"20"],[1597704960,"20"],[1597705080,"20"],[1597705200,"20"],[1597705320,"20"],[1597705440,"20"],[1597705560,"19"],[1597705680,"20"],[1597705800,"20"],[1597705920,"20"],[1597706040,"20"],[1597706160,"20"],[1597706280,"20"],[1597706400,"20"],[1597706520,"20"],[1597706640,"20"],[1597706760,"20"],[1597706880,"20"],[1597707000,"20"],[1597707120,"20"],[1597707240,"20"],[1597707360,"20"],[1597707480,"20"],[1597707600,"20"],[1597707720,"20"],[1597707840,"20"],[1597707960,"19"],[1597708080,"20"],[1597708200,"20"],[1597708320,"20"],[1597708440,"20"],[1597708560,"20"],[1597708680,"20"],[1597708800,"20"],[1597708920,"20"],[1597709040,"20"],[1597709160,"20"],[1597709280,"20"],[1597709400,"20"],[1597709520,"20"],[1597709640,"20"],[1597709760,"20"],[1597709880,"20"],[1597710000,"20"],[1597710120,"20"],[1597710240,"20"],[1597710360,"20"],[1597710480,"20"],[1597710600,"19"],[1597710720,"20"],[1597710840,"20"],[1597710960,"20"],[1597711080,"20"],[1597711200,"20"],[1597711320,"20"],[1597711440,"20"],[1597711560,"20"],[1597711680,"20"],[1597711800,"20"],[1597711920,"20"],[1597712040,"20"],[1597712160,"20"],[1597712280,"20"],[1597712400,"20"],[1597712520,"20"],[1597712640,"20"],[1597712760,"20"],[1597712880,"19"],[1597713000,"20"],[1597713120,"20"],[1597713240,"20"],[1597713360,"20"],[1597713480,"20"],[1597713600,"20"],[1597713720,"20"],[1597713840,"20"],[1597713960,"20"],[1597714080,"20"],[1597714200,"20"],[1597714320,"20"],[1597714440,"20"],[1597714560,"20"],[1597714680,"20"],[1597714800,"20"],[1597714920,"20"],[1597715040,"20"],[1597715160,"20"],[1597715280,"20"],[1597715400,"19"],[1597715520,"20"],[1597715640,"20"],[1597715760,"20"],[1597715880,"20"],[1597716000,"20"],[1597716120,"20"],[1597716240,"20"],[1597716360,"20"],[1597716480,"20"],[1597716600,"20"],[1597716720,"20"],[1597716840,"20"],[1597716960,"20"],[1597717080,"20"],[1597717200,"20"],[1597717320,"20"],[1597717440,"20"],[1597717560,"19"],[1597717680,"20"],[1597717800,"20"],[1597717920,"20"],[1597718040,"20"],[1597718160,"20"],[1597718280,"20"],[1597718400,"20"],[1597718520,"20"],[1597718640,"20"],[1597718760,"20"],[1597718880,"20"],[1597719000,"20"],[1597719120,"20"],[1597719240,"20"],[1597719360,"20"],[1597719480,"20"],[1597719600,"20"],[1597719720,"20"],[1597719840,"19"],[1597719960,"20"],[1597720080,"20"],[1597720200,"20"],[1597720320,"20"],[1597720440,"20"],[1597720560,"20"],[1597720680,"20"],[1597720800,"20"],[1597720920,"20"],[1597721040,"20"],[1597721160,"20"],[1597721280,"20"],[1597721400,"20"],[1597721520,"20"],[1597721640,"20"],[1597721760,"20"],[1597721880,"20"],[1597722000,"20"],[1597722120,"20"],[1597722240,"20"],[1597722360,"19"],[1597722480,"20"],[1597722600,"20"],[1597722720,"20"],[1597722840,"20"],[1597722960,"20"],[1597723080,"20"],[1597723200,"20"],[1597723320,"20"],[1597723440,"20"],[1597723560,"20"],[1597723680,"20"],[1597723800,"20"],[1597723920,"20"],[1597724040,"20"],[1597724160,"20"],[1597724280,"20"],[1597724400,"20"],[1597724520,"20"],[1597724640,"20"],[1597724760,"19"],[1597724880,"20"],[1597725000,"20"],[1597725120,"20"],[1597725240,"20"],[1597725360,"20"],[1597725480,"20"],[1597725600,"20"],[1597725720,"20"],[1597725840,"20"],[1597725960,"20"],[1597726080,"20"],[1597726200,"20"],[1597726320,"20"],[1597726440,"20"],[1597726560,"20"],[1597726680,"20"],[1597726800,"20"],[1597726920,"20"],[1597727040,"20"],[1597727160,"20"],[1597727280,"19"],[1597727400,"20"],[1597727520,"20"],[1597727640,"20"],[1597727760,"20"],[1597727880,"20"],[1597728000,"20"],[1597728120,"20"],[1597728240,"20"],[1597728360,"20"],[1597728480,"20"],[1597728600,"20"],[1597728720,"20"],[1597728840,"20"],[1597728960,"20"],[1597729080,"20"],[1597729200,"20"],[1597729320,"20"],[1597729440,"19"],[1597729560,"20"],[1597729680,"20"],[1597729800,"20"],[1597729920,"20"],[1597730040,"20"],[1597730160,"20"],[1597730280,"20"],[1597730400,"20"],[1597730520,"20"],[1597730640,"20"],[1597730760,"20"],[1597730880,"20"],[1597731000,"20"],[1597731120,"20"],[1597731240,"20"],[1597731360,"20"],[1597731480,"20"],[1597731600,"19"],[1597731720,"20"],[1597731840,"20"],[1597731960,"20"],[1597732080,"20"],[1597732200,"20"],[1597732320,"20"],[1597732440,"20"],[1597732560,"20"],[1597732680,"20"],[1597732800,"20"],[1597732920,"20"],[1597733040,"20"],[1597733160,"20"],[1597733280,"20"],[1597733400,"20"],[1597733520,"20"],[1597733640,"20"],[1597733760,"20"],[1597733880,"20"],[1597734000,"19"],[1597734120,"20"],[1597734240,"20"],[1597734360,"20"],[1597734480,"20"],[1597734600,"20"],[1597734720,"20"],[1597734840,"20"],[1597734960,"20"],[1597735080,"20"],[1597735200,"20"],[1597735320,"20"],[1597735440,"20"],[1597735560,"20"],[1597735680,"20"],[1597735800,"20"],[1597735920,"20"],[1597736040,"20"],[1597736160,"20"],[1597736280,"20"],[1597736400,"20"],[1597736520,"19"],[1597736640,"20"],[1597736760,"20"],[1597736880,"20"],[1597737000,"20"],[1597737120,"20"],[1597737240,"20"],[1597737360,"20"],[1597737480,"18"],[1597737600,"22"],[1597737720,"20"],[1597737840,"20"],[1597737960,"20"],[1597738080,"20"],[1597738200,"20"],[1597738320,"20"],[1597738440,"20"],[1597738560,"20"],[1597738680,"20"],[1597738800,"20"],[1597738920,"20"],[1597739040,"19"],[1597739160,"20"],[1597739280,"20"],[1597739400,"20"],[1597739520,"20"],[1597739640,"20"],[1597739760,"20"],[1597739880,"20"],[1597740000,"20"],[1597740120,"20"],[1597740240,"20"],[1597740360,"20"],[1597740480,"20"],[1597740600,"20"],[1597740720,"20"],[1597740840,"20"],[1597740960,"20"],[1597741080,"20"],[1597741200,"20"],[1597741320,"20"],[1597741440,"20"],[1597741560,"19"],[1597741680,"20"],[1597741800,"20"],[1597741920,"20"],[1597742040,"20"],[1597742160,"20"],[1597742280,"20"],[1597742400,"20"],[1597742520,"20"],[1597742640,"20"],[1597742760,"20"],[1597742880,"20"],[1597743000,"20"],[1597743120,"20"],[1597743240,"20"],[1597743360,"20"],[1597743480,"20"],[1597743600,"20"],[1597743720,"20"],[1597743840,"20"],[1597743960,"20"],[1597744080,"19"],[1597744200,"20"],[1597744320,"20"],[1597744440,"20"],[1597744560,"20"],[1597744680,"20"],[1597744800,"20"],[1597744920,"20"],[1597745040,"20"],[1597745160,"20"],[1597745280,"20"],[1597745400,"20"],[1597745520,"20"],[1597745640,"20"],[1597745760,"20"],[1597745880,"20"],[1597746000,"20"],[1597746120,"20"],[1597746240,"20"],[1597746360,"20"],[1597746480,"20"],[1597746600,"19"],[1597746720,"20"],[1597746840,"20"],[1597746960,"20"],[1597747080,"20"],[1597747200,"20"],[1597747320,"20"],[1597747440,"20"],[1597747560,"20"],[1597747680,"20"],[1597747800,"20"],[1597747920,"20"],[1597748040,"20"],[1597748160,"20"],[1597748280,"20"],[1597748400,"20"],[1597748520,"20"],[1597748640,"20"],[1597748760,"20"],[1597748880,"20"],[1597749000,"19"],[1597749120,"20"],[1597749240,"20"],[1597749360,"20"],[1597749480,"20"],[1597749600,"20"],[1597749720,"20"],[1597749840,"20"],[1597749960,"20"],[1597750080,"20"],[1597750200,"20"],[1597750320,"20"],[1597750440,"20"],[1597750560,"20"],[1597750680,"20"],[1597750800,"20"],[1597750920,"20"],[1597751040,"20"],[1597751160,"20"],[1597751280,"20"],[1597751400,"20"],[1597751520,"19"],[1597751640,"20"],[1597751760,"20"],[1597751880,"20"],[1597752000,"20"],[1597752120,"20"],[1597752240,"20"],[1597752360,"20"],[1597752480,"20"],[1597752600,"20"],[1597752720,"20"],[1597752840,"20"],[1597752960,"20"],[1597753080,"20"],[1597753200,"20"],[1597753320,"20"],[1597753440,"20"],[1597753560,"20"],[1597753680,"20"],[1597753800,"20"],[1597753920,"20"],[1597754040,"19"],[1597754160,"20"],[1597754280,"20"],[1597754400,"20"],[1597754520,"20"],[1597754640,"20"],[1597754760,"20"],[1597754880,"20"],[1597755000,"20"],[1597755120,"20"],[1597755240,"20"],[1597755360,"20"],[1597755480,"20"],[1597755600,"20"],[1597755720,"20"],[1597755840,"20"],[1597755960,"20"],[1597756080,"20"],[1597756200,"20"],[1597756320,"19"],[1597756440,"20"],[1597756560,"20"],[1597756680,"20"],[1597756800,"20"],[1597756920,"20"],[1597757040,"20"],[1597757160,"20"],[1597757280,"20"],[1597757400,"20"],[1597757520,"20"],[1597757640,"20"],[1597757760,"20"],[1597757880,"20"],[1597758000,"20"],[1597758120,"20"],[1597758240,"20"],[1597758360,"20"],[1597758480,"20"],[1597758600,"20"],[1597758720,"20"],[1597758840,"19"],[1597758960,"20"],[1597759080,"20"],[1597759200,"20"],[1597759320,"20"],[1597759440,"20"],[1597759560,"20"],[1597759680,"20"],[1597759800,"20"],[1597759920,"20"],[1597760040,"20"],[1597760160,"20"],[1597760280,"20"],[1597760400,"20"],[1597760520,"20"],[1597760640,"20"],[1597760760,"20"],[1597760880,"20"],[1597761000,"20"],[1597761120,"20"],[1597761240,"19"],[1597761360,"20"],[1597761480,"20"],[1597761600,"20"],[1597761720,"20"],[1597761840,"20"],[1597761960,"20"],[1597762080,"20"],[1597762200,"20"],[1597762320,"20"],[1597762440,"20"],[1597762560,"20"],[1597762680,"20"],[1597762800,"20"],[1597762920,"20"],[1597763040,"20"],[1597763160,"20"],[1597763280,"20"],[1597763400,"20"],[1597763520,"20"],[1597763640,"20"],[1597763760,"19"],[1597763880,"20"],[1597764000,"20"],[1597764120,"20"],[1597764240,"20"],[1597764360,"20"],[1597764480,"20"],[1597764600,"20"],[1597764720,"20"],[1597764840,"20"],[1597764960,"20"],[1597765080,"20"],[1597765200,"20"],[1597765320,"20"],[1597765440,"20"],[1597765560,"20"],[1597765680,"20"],[1597765800,"20"],[1597765920,"20"],[1597766040,"20"],[1597766160,"20"],[1597766280,"19"],[1597766400,"20"],[1597766520,"20"],[1597766640,"20"],[1597766760,"20"],[1597766880,"20"],[1597767000,"20"],[1597767120,"20"],[1597767240,"20"],[1597767360,"20"],[1597767480,"20"],[1597767600,"20"],[1597767720,"20"],[1597767840,"20"],[1597767960,"20"],[1597768080,"20"],[1597768200,"20"],[1597768320,"20"],[1597768440,"20"],[1597768560,"20"],[1597768680,"20"],[1597768800,"20"],[1597768920,"19"],[1597769040,"20"],[1597769160,"20"],[1597769280,"20"],[1597769400,"20"],[1597769520,"20"],[1597769640,"20"],[1597769760,"20"],[1597769880,"20"],[1597770000,"20"],[1597770120,"20"],[1597770240,"20"],[1597770360,"20"],[1597770480,"20"],[1597770600,"20"],[1597770720,"20"],[1597770840,"20"],[1597770960,"20"],[1597771080,"20"],[1597771200,"20"],[1597771320,"20"],[1597771440,"19"],[1597771560,"20"],[1597771680,"20"],[1597771800,"20"],[1597771920,"20"],[1597772040,"20"],[1597772160,"20"],[1597772280,"20"],[1597772400,"20"],[1597772520,"20"],[1597772640,"20"],[1597772760,"20"],[1597772880,"20"],[1597773000,"20"],[1597773120,"20"],[1597773240,"20"],[1597773360,"20"],[1597773480,"20"],[1597773600,"20"],[1597773720,"20"],[1597773840,"19"],[1597773960,"20"],[1597774080,"20"],[1597774200,"20"],[1597774320,"20"],[1597774440,"20"],[1597774560,"20"],[1597774680,"20"],[1597774800,"20"],[1597774920,"20"],[1597775040,"20"],[1597775160,"20"],[1597775280,"20"],[1597775400,"20"],[1597775520,"20"],[1597775640,"20"],[1597775760,"20"],[1597775880,"20"],[1597776000,"20"],[1597776120,"20"],[1597776240,"20"],[1597776360,"19"],[1597776480,"20"],[1597776600,"20"],[1597776720,"20"],[1597776840,"20"],[1597776960,"20"],[1597777080,"20"],[1597777200,"20"],[1597777320,"20"],[1597777440,"20"],[1597777560,"20"],[1597777680,"20"],[1597777800,"20"],[1597777920,"20"],[1597778040,"20"],[1597778160,"20"],[1597778280,"20"],[1597778400,"20"],[1597778520,"20"],[1597778640,"19"],[1597778760,"20"],[1597778880,"20"],[1597779000,"20"],[1597779120,"20"],[1597779240,"20"],[1597779360,"20"],[1597779480,"20"],[1597779600,"20"],[1597779720,"20"],[1597779840,"20"],[1597779960,"20"],[1597780080,"20"],[1597780200,"20"],[1597780320,"20"],[1597780440,"20"],[1597780560,"20"],[1597780680,"20"],[1597780800,"20"],[1597780920,"20"],[1597781040,"20"],[1597781160,"20"],[1597781280,"19"],[1597781400,"20"],[1597781520,"20"],[1597781640,"20"],[1597781760,"20"],[1597781880,"20"],[1597782000,"20"],[1597782120,"20"],[1597782240,"20"],[1597782360,"20"],[1597782480,"20"],[1597782600,"20"],[1597782720,"20"],[1597782840,"20"],[1597782960,"20"],[1597783080,"20"],[1597783200,"20"],[1597783320,"20"],[1597783440,"20"],[1597783560,"20"],[1597783680,"19"],[1597783800,"20"],[1597783920,"20"],[1597784040,"20"],[1597784160,"20"],[1597784280,"20"],[1597784400,"20"],[1597784520,"20"],[1597784640,"20"],[1597784760,"20"],[1597784880,"20"],[1597785000,"20"],[1597785120,"20"],[1597785240,"20"],[1597785360,"20"],[1597785480,"20"],[1597785600,"20"],[1597785720,"20"],[1597785840,"20"],[1597785960,"20"],[1597786080,"20"],[1597786200,"19"],[1597786320,"20"],[1597786440,"20"],[1597786560,"20"],[1597786680,"20"],[1597786800,"20"],[1597786920,"20"],[1597787040,"20"],[1597787160,"20"],[1597787280,"20"],[1597787400,"20"],[1597787520,"20"],[1597787640,"20"],[1597787760,"20"],[1597787880,"20"],[1597788000,"20"],[1597788120,"20"],[1597788240,"20"],[1597788360,"20"],[1597788480,"20"],[1597788600,"19"],[1597788720,"20"],[1597788840,"20"],[1597788960,"20"],[1597789080,"20"],[1597789200,"20"],[1597789320,"20"],[1597789440,"20"],[1597789560,"20"],[1597789680,"20"],[1597789800,"20"],[1597789920,"20"],[1597790040,"20"],[1597790160,"20"],[1597790280,"20"],[1597790400,"20"],[1597790520,"20"],[1597790640,"20"],[1597790760,"19"],[1597790880,"20"],[1597791000,"20"],[1597791120,"20"],[1597791240,"20"],[1597791360,"20"],[1597791480,"20"],[1597791600,"20"],[1597791720,"20"],[1597791840,"20"],[1597791960,"20"],[1597792080,"20"],[1597792200,"20"],[1597792320,"20"],[1597792440,"20"],[1597792560,"20"],[1597792680,"20"],[1597792800,"20"],[1597792920,"19"],[1597793040,"20"],[1597793160,"20"],[1597793280,"20"],[1597793400,"20"],[1597793520,"20"],[1597793640,"20"],[1597793760,"20"],[1597793880,"20"],[1597794000,"20"],[1597794120,"20"],[1597794240,"20"],[1597794360,"20"],[1597794480,"20"],[1597794600,"20"],[1597794720,"20"],[1597794840,"20"],[1597794960,"20"],[1597795080,"20"],[1597795200,"20"],[1597795320,"20"],[1597795440,"19"],[1597795560,"20"],[1597795680,"20"],[1597795800,"20"],[1597795920,"20"],[1597796040,"20"],[1597796160,"20"],[1597796280,"20"],[1597796400,"20"],[1597796520,"20"],[1597796640,"20"],[1597796760,"20"],[1597796880,"20"],[1597797000,"20"],[1597797120,"20"],[1597797240,"20"],[1597797360,"20"],[1597797480,"20"],[1597797600,"20"],[1597797720,"20"],[1597797840,"19"],[1597797960,"20"],[1597798080,"20"],[1597798200,"20"],[1597798320,"20"],[1597798440,"20"],[1597798560,"20"],[1597798680,"20"],[1597798800,"20"],[1597798920,"20"],[1597799040,"20"],[1597799160,"20"],[1597799280,"20"],[1597799400,"20"],[1597799520,"20"],[1597799640,"20"],[1597799760,"20"],[1597799880,"20"],[1597800000,"20"],[1597800120,"19"],[1597800240,"20"],[1597800360,"20"],[1597800480,"20"],[1597800600,"20"],[1597800720,"20"],[1597800840,"20"],[1597800960,"20"],[1597801080,"20"],[1597801200,"20"],[1597801320,"20"],[1597801440,"20"],[1597801560,"20"],[1597801680,"20"],[1597801800,"20"],[1597801920,"20"],[1597802040,"20"],[1597802160,"20"],[1597802280,"20"],[1597802400,"20"],[1597802520,"20"],[1597802640,"19"],[1597802760,"20"],[1597802880,"20"],[1597803000,"20"],[1597803120,"20"],[1597803240,"20"],[1597803360,"20"],[1597803480,"20"],[1597803600,"20"],[1597803720,"20"],[1597803840,"20"],[1597803960,"20"],[1597804080,"20"],[1597804200,"20"],[1597804320,"20"],[1597804440,"20"],[1597804560,"20"],[1597804680,"20"],[1597804800,"20"],[1597804920,"20"],[1597805040,"20"],[1597805160,"20"],[1597805280,"19"],[1597805400,"20"],[1597805520,"20"],[1597805640,"20"],[1597805760,"20"],[1597805880,"20"],[1597806000,"20"],[1597806120,"20"],[1597806240,"20"],[1597806360,"20"],[1597806480,"20"],[1597806600,"20"],[1597806720,"20"],[1597806840,"20"],[1597806960,"20"],[1597807080,"20"],[1597807200,"20"],[1597807320,"20"],[1597807440,"20"],[1597807560,"20"],[1597807680,"20"],[1597807800,"20"],[1597807920,"19"],[1597808040,"20"],[1597808160,"20"],[1597808280,"20"],[1597808400,"20"],[1597808520,"20"],[1597808640,"20"],[1597808760,"20"],[1597808880,"20"],[1597809000,"20"],[1597809120,"20"],[1597809240,"20"],[1597809360,"20"],[1597809480,"20"],[1597809600,"20"],[1597809720,"20"],[1597809840,"20"],[1597809960,"20"],[1597810080,"20"],[1597810200,"19"],[1597810320,"20"],[1597810440,"20"],[1597810560,"20"],[1597810680,"20"],[1597810800,"20"],[1597810920,"20"],[1597811040,"20"],[1597811160,"20"],[1597811280,"20"],[1597811400,"20"],[1597811520,"20"],[1597811640,"20"],[1597811760,"20"],[1597811880,"20"],[1597812000,"20"],[1597812120,"20"],[1597812240,"20"],[1597812360,"20"],[1597812480,"19"],[1597812600,"20"],[1597812720,"20"],[1597812840,"20"],[1597812960,"20"],[1597813080,"20"],[1597813200,"20"],[1597813320,"20"],[1597813440,"20"],[1597813560,"20"],[1597813680,"20"],[1597813800,"20"],[1597813920,"20"],[1597814040,"20"],[1597814160,"20"],[1597814280,"20"],[1597814400,"20"],[1597814520,"20"],[1597814640,"20"],[1597814760,"19"],[1597814880,"20"],[1597815000,"20"],[1597815120,"20"],[1597815240,"20"],[1597815360,"20"],[1597815480,"20"],[1597815600,"20"],[1597815720,"20"],[1597815840,"20"],[1597815960,"20"],[1597816080,"20"],[1597816200,"20"],[1597816320,"20"],[1597816440,"20"],[1597816560,"20"],[1597816680,"20"],[1597816800,"20"],[1597816920,"20"],[1597817040,"20"],[1597817160,"19"],[1597817280,"20"],[1597817400,"20"],[1597817520,"20"],[1597817640,"20"],[1597817760,"20"],[1597817880,"20"],[1597818000,"20"],[1597818120,"20"],[1597818240,"20"],[1597818360,"20"],[1597818480,"20"],[1597818600,"20"],[1597818720,"20"],[1597818840,"20"],[1597818960,"20"],[1597819080,"20"],[1597819200,"20"],[1597819320,"20"],[1597819440,"20"],[1597819560,"19"],[1597819680,"20"],[1597819800,"20"],[1597819920,"20"],[1597820040,"20"],[1597820160,"20"],[1597820280,"20"],[1597820400,"20"],[1597820520,"20"],[1597820640,"20"],[1597820760,"20"],[1597820880,"20"],[1597821000,"14"]]},{"metric":{"ServiceName":"VWX"},"values":[[1597704240,"4"],[1597706160,"2"],[1597707840,"2"],[1597710240,"1"],[1597711560,"4"],[1597715280,"2"],[1597716120,"1"],[1597718880,"2"],[1597722120,"1"],[1597722600,"2"],[1597726200,"4"],[1597728240,"1"],[1597729920,"4"],[1597733280,"2"],[1597733640,"2"],[1597734120,"2"],[1597737240,"2"],[1597740120,"2"],[1597740960,"2"],[1597744560,"4"],[1597746120,"2"],[1597748280,"2"],[1597752000,"6"],[1597755600,"3"],[1597758120,"2"],[1597759320,"4"],[1597760400,"2"],[1597762920,"4"],[1597764240,"1"],[1597766640,"2"],[1597770120,"1"],[1597770240,"2"],[1597773960,"2"],[1597776120,"2"],[1597777680,"2"],[1597781280,"4"],[1597782240,"2"],[1597785000,"2"],[1597787520,"2"],[1597787880,"2"],[1597788600,"2"],[1597792320,"2"],[1597794120,"2"],[1597796040,"2"],[1597799640,"2"],[1597800120,"1"],[1597803360,"2"],[1597806120,"2"],[1597806960,"2"],[1597810680,"4"],[1597812120,"2"],[1597814280,"4"],[1597814640,"2"],[1597818000,"2"],[1597818240,"1"],[1597821720,"4"],[1597824240,"7"]]},{"metric":{"ServiceName":"YZ0"},"values":[[1597701600,"60"],[1597701720,"60"],[1597701840,"60"],[1597701960,"60"],[1597702080,"60"],[1597702200,"60"],[1597702320,"60"],[1597702440,"60"],[1597702560,"60"],[1597702680,"60"],[1597702800,"60"],[1597702920,"60"],[1597703040,"60"],[1597703160,"60"],[1597703280,"59"],[1597703400,"60"],[1597703520,"61"],[1597703640,"59"],[1597703760,"60"],[1597703880,"60"],[1597704000,"60"],[1597704120,"60"],[1597704240,"60"],[1597704360,"60"],[1597704480,"60"],[1597704600,"60"],[1597704720,"60"],[1597704840,"60"],[1597704960,"60"],[1597705080,"60"],[1597705200,"60"],[1597705320,"60"],[1597705440,"60"],[1597705560,"60"],[1597705680,"60"],[1597705800,"60"],[1597705920,"60"],[1597706040,"60"],[1597706160,"60"],[1597706280,"60"],[1597706400,"60"],[1597706520,"60"],[1597706640,"60"],[1597706760,"60"],[1597706880,"60"],[1597707000,"60"],[1597707120,"60"],[1597707240,"60"],[1597707360,"59"],[1597707480,"60"],[1597707600,"60"],[1597707720,"60"],[1597707840,"60"],[1597707960,"60"],[1597708080,"60"],[1597708200,"60"],[1597708320,"60"],[1597708440,"60"],[1597708560,"60"],[1597708680,"60"],[1597708800,"60"],[1597708920,"60"],[1597709040,"60"],[1597709160,"60"],[1597709280,"60"],[1597709400,"60"],[1597709520,"60"],[1597709640,"60"],[1597709760,"60"],[1597709880,"60"],[1597710000,"60"],[1597710120,"60"],[1597710240,"60"],[1597710360,"60"],[1597710480,"60"],[1597710600,"60"],[1597710720,"60"],[1597710840,"60"],[1597710960,"60"],[1597711080,"60"],[1597711200,"59"],[1597711320,"60"],[1597711440,"60"],[1597711560,"60"],[1597711680,"60"],[1597711800,"60"],[1597711920,"60"],[1597712040,"60"],[1597712160,"60"],[1597712280,"60"],[1597712400,"60"],[1597712520,"60"],[1597712640,"60"],[1597712760,"60"],[1597712880,"60"],[1597713000,"60"],[1597713120,"60"],[1597713240,"60"],[1597713360,"60"],[1597713480,"60"],[1597713600,"60"],[1597713720,"60"],[1597713840,"60"],[1597713960,"60"],[1597714080,"60"],[1597714200,"60"],[1597714320,"60"],[1597714440,"60"],[1597714560,"60"],[1597714680,"60"],[1597714800,"60"],[1597714920,"60"],[1597715040,"60"],[1597715160,"60"],[1597715280,"60"],[1597715400,"59"],[1597715520,"60"],[1597715640,"60"],[1597715760,"60"],[1597715880,"60"],[1597716000,"60"],[1597716120,"60"],[1597716240,"60"],[1597716360,"60"],[1597716480,"60"],[1597716600,"60"],[1597716720,"60"],[1597716840,"60"],[1597716960,"60"],[1597717080,"60"],[1597717200,"60"],[1597717320,"60"],[1597717440,"60"],[1597717560,"60"],[1597717680,"60"],[1597717800,"60"],[1597717920,"60"],[1597718040,"60"],[1597718160,"60"],[1597718280,"60"],[1597718400,"60"],[1597718520,"60"],[1597718640,"60"],[1597718760,"60"],[1597718880,"60"],[1597719000,"60"],[1597719120,"60"],[1597719240,"59"],[1597719360,"60"],[1597719480,"60"],[1597719600,"60"],[1597719720,"60"],[1597719840,"60"],[1597719960,"60"],[1597720080,"60"],[1597720200,"60"],[1597720320,"60"],[1597720440,"60"],[1597720560,"60"],[1597720680,"60"],[1597720800,"60"],[1597720920,"60"],[1597721040,"60"],[1597721160,"60"],[1597721280,"60"],[1597721400,"60"],[1597721520,"60"],[1597721640,"60"],[1597721760,"60"],[1597721880,"60"],[1597722000,"60"],[1597722120,"60"],[1597722240,"60"],[1597722360,"60"],[1597722480,"60"],[1597722600,"60"],[1597722720,"60"],[1597722840,"60"],[1597722960,"60"],[1597723080,"59"],[1597723200,"60"],[1597723320,"60"],[1597723440,"60"],[1597723560,"60"],[1597723680,"60"],[1597723800,"60"],[1597723920,"60"],[1597724040,"60"],[1597724160,"60"],[1597724280,"60"],[1597724400,"60"],[1597724520,"60"],[1597724640,"60"],[1597724760,"60"],[1597724880,"60"],[1597725000,"60"],[1597725120,"60"],[1597725240,"60"],[1597725360,"60"],[1597725480,"60"],[1597725600,"60"],[1597725720,"60"],[1597725840,"60"],[1597725960,"60"],[1597726080,"60"],[1597726200,"60"],[1597726320,"60"],[1597726440,"60"],[1597726560,"60"],[1597726680,"60"],[1597726800,"60"],[1597726920,"60"],[1597727040,"60"],[1597727160,"60"],[1597727280,"59"],[1597727400,"60"],[1597727520,"61"],[1597727640,"59"],[1597727760,"60"],[1597727880,"60"],[1597728000,"60"],[1597728120,"60"],[1597728240,"60"],[1597728360,"60"],[1597728480,"60"],[1597728600,"60"],[1597728720,"60"],[1597728840,"60"],[1597728960,"60"],[1597729080,"60"],[1597729200,"60"],[1597729320,"60"],[1597729440,"60"],[1597729560,"60"],[1597729680,"60"],[1597729800,"60"],[1597729920,"60"],[1597730040,"60"],[1597730160,"60"],[1597730280,"60"],[1597730400,"60"],[1597730520,"60"],[1597730640,"60"],[1597730760,"60"],[1597730880,"60"],[1597731000,"60"],[1597731120,"60"],[1597731240,"60"],[1597731360,"60"],[1597731480,"59"],[1597731600,"60"],[1597731720,"60"],[1597731840,"60"],[1597731960,"60"],[1597732080,"60"],[1597732200,"60"],[1597732320,"60"],[1597732440,"60"],[1597732560,"60"],[1597732680,"60"],[1597732800,"60"],[1597732920,"60"],[1597733040,"60"],[1597733160,"60"],[1597733280,"60"],[1597733400,"60"],[1597733520,"60"],[1597733640,"60"],[1597733760,"60"],[1597733880,"60"],[1597734000,"60"],[1597734120,"60"],[1597734240,"60"],[1597734360,"60"],[1597734480,"60"],[1597734600,"60"],[1597734720,"60"],[1597734840,"60"],[1597734960,"60"],[1597735080,"60"],[1597735200,"60"],[1597735320,"59"],[1597735440,"60"],[1597735560,"60"],[1597735680,"60"],[1597735800,"60"],[1597735920,"60"],[1597736040,"60"],[1597736160,"60"],[1597736280,"60"],[1597736400,"60"],[1597736520,"60"],[1597736640,"60"],[1597736760,"60"],[1597736880,"60"],[1597737000,"60"],[1597737120,"60"],[1597737240,"60"],[1597737360,"60"],[1597737480,"60"],[1597737600,"60"],[1597737720,"60"],[1597737840,"60"],[1597737960,"60"],[1597738080,"60"],[1597738200,"60"],[1597738320,"60"],[1597738440,"60"],[1597738560,"60"],[1597738680,"60"],[1597738800,"60"],[1597738920,"60"],[1597739040,"59"],[1597739160,"61"],[1597739280,"60"],[1597739400,"59"],[1597739520,"60"],[1597739640,"60"],[1597739760,"60"],[1597739880,"60"],[1597740000,"60"],[1597740120,"60"],[1597740240,"60"],[1597740360,"60"],[1597740480,"60"],[1597740600,"60"],[1597740720,"60"],[1597740840,"60"],[1597740960,"60"],[1597741080,"60"],[1597741200,"60"],[1597741320,"60"],[1597741440,"60"],[1597741560,"60"],[1597741680,"60"],[1597741800,"60"],[1597741920,"60"],[1597742040,"60"],[1597742160,"60"],[1597742280,"60"],[1597742400,"60"],[1597742520,"60"],[1597742640,"60"],[1597742760,"60"],[1597742880,"60"],[1597743000,"60"],[1597743120,"60"],[1597743240,"60"],[1597743360,"59"],[1597743480,"60"],[1597743600,"60"],[1597743720,"60"],[1597743840,"60"],[1597743960,"60"],[1597744080,"60"],[1597744200,"60"],[1597744320,"60"],[1597744440,"60"],[1597744560,"60"],[1597744680,"60"],[1597744800,"60"],[1597744920,"60"],[1597745040,"60"],[1597745160,"60"],[1597745280,"60"],[1597745400,"60"],[1597745520,"60"],[1597745640,"60"],[1597745760,"60"],[1597745880,"60"],[1597746000,"60"],[1597746120,"60"],[1597746240,"60"],[1597746360,"60"],[1597746480,"60"],[1597746600,"60"],[1597746720,"60"],[1597746840,"60"],[1597746960,"60"],[1597747080,"60"],[1597747200,"60"],[1597747320,"59"],[1597747440,"60"],[1597747560,"60"],[1597747680,"60"],[1597747800,"60"],[1597747920,"60"],[1597748040,"60"],[1597748160,"60"],[1597748280,"60"],[1597748400,"60"],[1597748520,"60"],[1597748640,"60"],[1597748760,"60"],[1597748880,"60"],[1597749000,"60"],[1597749120,"60"],[1597749240,"60"],[1597749360,"60"],[1597749480,"60"],[1597749600,"60"],[1597749720,"60"],[1597749840,"60"],[1597749960,"60"],[1597750080,"60"],[1597750200,"60"],[1597750320,"60"],[1597750440,"60"],[1597750560,"60"],[1597750680,"60"],[1597750800,"60"],[1597750920,"60"],[1597751040,"60"],[1597751160,"59"],[1597751280,"61"],[1597751400,"59"],[1597751520,"60"],[1597751640,"60"],[1597751760,"60"],[1597751880,"60"],[1597752000,"60"],[1597752120,"60"],[1597752240,"60"],[1597752360,"60"],[1597752480,"60"],[1597752600,"60"],[1597752720,"60"],[1597752840,"60"],[1597752960,"60"],[1597753080,"60"],[1597753200,"60"],[1597753320,"60"],[1597753440,"60"],[1597753560,"60"],[1597753680,"60"],[1597753800,"60"],[1597753920,"60"],[1597754040,"60"],[1597754160,"60"],[1597754280,"60"],[1597754400,"60"],[1597754520,"60"],[1597754640,"60"],[1597754760,"60"],[1597754880,"60"],[1597755000,"59"],[1597755120,"60"],[1597755240,"61"],[1597755360,"59"],[1597755480,"60"],[1597755600,"60"],[1597755720,"60"],[1597755840,"60"],[1597755960,"60"],[1597756080,"60"],[1597756200,"60"],[1597756320,"60"],[1597756440,"60"],[1597756560,"60"],[1597756680,"60"],[1597756800,"60"],[1597756920,"60"],[1597757040,"60"],[1597757160,"60"],[1597757280,"60"],[1597757400,"60"],[1597757520,"60"],[1597757640,"60"],[1597757760,"60"],[1597757880,"60"],[1597758000,"60"],[1597758120,"60"],[1597758240,"60"],[1597758360,"60"],[1597758480,"60"],[1597758600,"60"],[1597758720,"60"],[1597758840,"60"],[1597758960,"60"],[1597759080,"59"],[1597759200,"60"],[1597759320,"60"],[1597759440,"60"],[1597759560,"60"],[1597759680,"60"],[1597759800,"60"],[1597759920,"60"],[1597760040,"60"],[1597760160,"60"],[1597760280,"60"],[1597760400,"60"],[1597760520,"60"],[1597760640,"60"],[1597760760,"60"],[1597760880,"60"],[1597761000,"60"],[1597761120,"60"],[1597761240,"60"],[1597761360,"60"],[1597761480,"60"],[1597761600,"60"],[1597761720,"60"],[1597761840,"60"],[1597761960,"60"],[1597762080,"60"],[1597762200,"60"],[1597762320,"60"],[1597762440,"60"],[1597762560,"60"],[1597762680,"60"],[1597762800,"60"],[1597762920,"60"],[1597763040,"60"],[1597763160,"60"],[1597763280,"60"],[1597763400,"59"],[1597763520,"60"],[1597763640,"60"],[1597763760,"60"],[1597763880,"60"],[1597764000,"60"],[1597764120,"60"],[1597764240,"60"],[1597764360,"60"],[1597764480,"60"],[1597764600,"60"],[1597764720,"60"],[1597764840,"60"],[1597764960,"60"],[1597765080,"60"],[1597765200,"60"],[1597765320,"60"],[1597765440,"60"],[1597765560,"60"],[1597765680,"60"],[1597765800,"60"],[1597765920,"60"],[1597766040,"60"],[1597766160,"60"],[1597766280,"60"],[1597766400,"60"],[1597766520,"60"],[1597766640,"60"],[1597766760,"60"],[1597766880,"60"],[1597767000,"60"],[1597767120,"60"],[1597767240,"59"],[1597767360,"61"],[1597767480,"59"],[1597767600,"60"],[1597767720,"60"],[1597767840,"60"],[1597767960,"60"],[1597768080,"60"],[1597768200,"60"],[1597768320,"60"],[1597768440,"60"],[1597768560,"60"],[1597768680,"60"],[1597768800,"60"],[1597768920,"60"],[1597769040,"60"],[1597769160,"60"],[1597769280,"60"],[1597769400,"60"],[1597769520,"60"],[1597769640,"60"],[1597769760,"60"],[1597769880,"60"],[1597770000,"60"],[1597770120,"60"],[1597770240,"60"],[1597770360,"60"],[1597770480,"60"],[1597770600,"60"],[1597770720,"60"],[1597770840,"60"],[1597770960,"60"],[1597771080,"60"],[1597771200,"59"],[1597771320,"61"],[1597771440,"60"],[1597771560,"59"],[1597771680,"60"],[1597771800,"60"],[1597771920,"60"],[1597772040,"60"],[1597772160,"60"],[1597772280,"60"],[1597772400,"60"],[1597772520,"60"],[1597772640,"60"],[1597772760,"60"],[1597772880,"60"],[1597773000,"60"],[1597773120,"60"],[1597773240,"60"],[1597773360,"60"],[1597773480,"60"],[1597773600,"60"],[1597773720,"60"],[1597773840,"60"],[1597773960,"60"],[1597774080,"60"],[1597774200,"60"],[1597774320,"60"],[1597774440,"60"],[1597774560,"60"],[1597774680,"60"],[1597774800,"60"],[1597774920,"60"],[1597775040,"60"],[1597775160,"60"],[1597775280,"60"],[1597775400,"59"],[1597775520,"60"],[1597775640,"60"],[1597775760,"60"],[1597775880,"60"],[1597776000,"60"],[1597776120,"60"],[1597776240,"60"],[1597776360,"60"],[1597776480,"60"],[1597776600,"60"],[1597776720,"60"],[1597776840,"60"],[1597776960,"60"],[1597777080,"60"],[1597777200,"60"],[1597777320,"60"],[1597777440,"60"],[1597777560,"60"],[1597777680,"60"],[1597777800,"60"],[1597777920,"60"],[1597778040,"60"],[1597778160,"60"],[1597778280,"60"],[1597778400,"60"],[1597778520,"60"],[1597778640,"60"],[1597778760,"60"],[1597778880,"60"],[1597779000,"60"],[1597779120,"60"],[1597779240,"60"],[1597779360,"60"],[1597779480,"59"],[1597779600,"61"],[1597779720,"59"],[1597779840,"60"],[1597779960,"60"],[1597780080,"60"],[1597780200,"60"],[1597780320,"60"],[1597780440,"60"],[1597780560,"60"],[1597780680,"60"],[1597780800,"60"],[1597780920,"60"],[1597781040,"60"],[1597781160,"60"],[1597781280,"60"],[1597781400,"60"],[1597781520,"60"],[1597781640,"60"],[1597781760,"60"],[1597781880,"60"],[1597782000,"60"],[1597782120,"60"],[1597782240,"60"],[1597782360,"60"],[1597782480,"60"],[1597782600,"60"],[1597782720,"60"],[1597782840,"60"],[1597782960,"60"],[1597783080,"60"],[1597783200,"60"],[1597783320,"60"],[1597783440,"60"],[1597783560,"60"],[1597783680,"60"],[1597783800,"59"],[1597783920,"60"],[1597784040,"60"],[1597784160,"60"],[1597784280,"60"],[1597784400,"60"],[1597784520,"60"],[1597784640,"60"],[1597784760,"60"],[1597784880,"60"],[1597785000,"60"],[1597785120,"60"],[1597785240,"60"],[1597785360,"60"],[1597785480,"60"],[1597785600,"60"],[1597785720,"60"],[1597785840,"60"],[1597785960,"60"],[1597786080,"60"],[1597786200,"60"],[1597786320,"60"],[1597786440,"60"],[1597786560,"60"],[1597786680,"60"],[1597786800,"60"],[1597786920,"60"],[1597787040,"60"],[1597787160,"60"],[1597787280,"60"],[1597787400,"60"],[1597787520,"59"],[1597787640,"60"],[1597787760,"60"],[1597787880,"60"],[1597788000,"60"],[1597788120,"60"],[1597788240,"60"],[1597788360,"60"],[1597788480,"60"],[1597788600,"60"],[1597788720,"60"],[1597788840,"60"],[1597788960,"60"],[1597789080,"60"],[1597789200,"60"],[1597789320,"60"],[1597789440,"60"],[1597789560,"60"],[1597789680,"60"],[1597789800,"60"],[1597789920,"60"],[1597790040,"60"],[1597790160,"60"],[1597790280,"60"],[1597790400,"60"],[1597790520,"60"],[1597790640,"60"],[1597790760,"60"],[1597790880,"60"],[1597791000,"60"],[1597791120,"60"],[1597791240,"59"],[1597791360,"60"],[1597791480,"60"],[1597791600,"60"],[1597791720,"60"],[1597791840,"60"],[1597791960,"60"],[1597792080,"60"],[1597792200,"60"],[1597792320,"60"],[1597792440,"60"],[1597792560,"60"],[1597792680,"60"],[1597792800,"60"],[1597792920,"60"],[1597793040,"60"],[1597793160,"60"],[1597793280,"60"],[1597793400,"60"],[1597793520,"60"],[1597793640,"60"],[1597793760,"60"],[1597793880,"60"],[1597794000,"60"],[1597794120,"60"],[1597794240,"60"],[1597794360,"60"],[1597794480,"60"],[1597794600,"60"],[1597794720,"60"],[1597794840,"60"],[1597794960,"60"],[1597795080,"60"],[1597795200,"59"],[1597795320,"60"],[1597795440,"60"],[1597795560,"60"],[1597795680,"60"],[1597795800,"60"],[1597795920,"60"],[1597796040,"60"],[1597796160,"60"],[1597796280,"60"],[1597796400,"60"],[1597796520,"60"],[1597796640,"60"],[1597796760,"60"],[1597796880,"60"],[1597797000,"60"],[1597797120,"60"],[1597797240,"60"],[1597797360,"60"],[1597797480,"60"],[1597797600,"60"],[1597797720,"60"],[1597797840,"60"],[1597797960,"60"],[1597798080,"60"],[1597798200,"60"],[1597798320,"60"],[1597798440,"60"],[1597798560,"60"],[1597798680,"60"],[1597798800,"60"],[1597798920,"60"],[1597799040,"60"],[1597799160,"60"],[1597799280,"59"],[1597799400,"60"],[1597799520,"60"],[1597799640,"60"],[1597799760,"60"],[1597799880,"60"],[1597800000,"60"],[1597800120,"60"],[1597800240,"60"],[1597800360,"60"],[1597800480,"60"],[1597800600,"60"],[1597800720,"60"],[1597800840,"60"],[1597800960,"60"],[1597801080,"60"],[1597801200,"60"],[1597801320,"60"],[1597801440,"60"],[1597801560,"60"],[1597801680,"60"],[1597801800,"60"],[1597801920,"60"],[1597802040,"60"],[1597802160,"60"],[1597802280,"60"],[1597802400,"60"],[1597802520,"60"],[1597802640,"60"],[1597802760,"60"],[1597802880,"60"],[1597803000,"60"],[1597803120,"60"],[1597803240,"59"],[1597803360,"60"],[1597803480,"60"],[1597803600,"60"],[1597803720,"60"],[1597803840,"60"],[1597803960,"60"],[1597804080,"60"],[1597804200,"60"],[1597804320,"60"],[1597804440,"60"],[1597804560,"60"],[1597804680,"60"],[1597804800,"60"],[1597804920,"60"],[1597805040,"60"],[1597805160,"60"],[1597805280,"60"],[1597805400,"60"],[1597805520,"60"],[1597805640,"60"],[1597805760,"60"],[1597805880,"60"],[1597806000,"60"],[1597806120,"60"],[1597806240,"60"],[1597806360,"60"],[1597806480,"60"],[1597806600,"60"],[1597806720,"60"],[1597806840,"60"],[1597806960,"60"],[1597807080,"60"],[1597807200,"60"],[1597807320,"59"],[1597807440,"60"],[1597807560,"60"],[1597807680,"60"],[1597807800,"60"],[1597807920,"60"],[1597808040,"60"],[1597808160,"60"],[1597808280,"60"],[1597808400,"60"],[1597808520,"60"],[1597808640,"60"],[1597808760,"60"],[1597808880,"60"],[1597809000,"60"],[1597809120,"60"],[1597809240,"60"],[1597809360,"60"],[1597809480,"60"],[1597809600,"60"],[1597809720,"60"],[1597809840,"60"],[1597809960,"60"],[1597810080,"60"],[1597810200,"60"],[1597810320,"60"],[1597810440,"60"],[1597810560,"60"],[1597810680,"60"],[1597810800,"60"],[1597810920,"60"],[1597811040,"59"],[1597811160,"60"],[1597811280,"60"],[1597811400,"60"],[1597811520,"60"],[1597811640,"60"],[1597811760,"60"],[1597811880,"60"],[1597812000,"60"],[1597812120,"60"],[1597812240,"60"],[1597812360,"60"],[1597812480,"60"],[1597812600,"60"],[1597812720,"60"],[1597812840,"60"],[1597812960,"60"],[1597813080,"60"],[1597813200,"60"],[1597813320,"60"],[1597813440,"60"],[1597813560,"60"],[1597813680,"60"],[1597813800,"60"],[1597813920,"60"],[1597814040,"60"],[1597814160,"60"],[1597814280,"60"],[1597814400,"60"],[1597814520,"60"],[1597814640,"60"],[1597814760,"59"],[1597814880,"61"],[1597815000,"60"],[1597815120,"59"],[1597815240,"60"],[1597815360,"60"],[1597815480,"60"],[1597815600,"60"],[1597815720,"60"],[1597815840,"60"],[1597815960,"60"],[1597816080,"60"],[1597816200,"60"],[1597816320,"60"],[1597816440,"60"],[1597816560,"60"],[1597816680,"60"],[1597816800,"60"],[1597816920,"60"],[1597817040,"60"],[1597817160,"60"],[1597817280,"60"],[1597817400,"60"],[1597817520,"60"],[1597817640,"60"],[1597817760,"60"],[1597817880,"60"],[1597818000,"60"],[1597818120,"60"],[1597818240,"60"],[1597818360,"60"],[1597818480,"60"],[1597818600,"60"],[1597818720,"59"],[1597818840,"61"],[1597818960,"59"],[1597819080,"60"],[1597819200,"60"],[1597819320,"60"],[1597819440,"60"],[1597819560,"60"],[1597819680,"60"],[1597819800,"60"],[1597819920,"60"],[1597820040,"60"],[1597820160,"60"],[1597820280,"60"],[1597820400,"60"],[1597820520,"60"],[1597820640,"60"],[1597820760,"60"],[1597820880,"60"],[1597821000,"60"],[1597821120,"60"],[1597821240,"60"],[1597821360,"60"],[1597821480,"60"],[1597821600,"60"],[1597821720,"60"],[1597821840,"60"],[1597821960,"60"],[1597822080,"60"],[1597822200,"60"],[1597822320,"60"],[1597822440,"60"],[1597822560,"13"]]},{"metric":{"ServiceName":"A1B2"},"values":[[1597701600,"172"],[1597701720,"172"],[1597701840,"172"],[1597701960,"165"],[1597702080,"172"],[1597702200,"172"],[1597702320,"172"],[1597702440,"172"],[1597702560,"172"],[1597702680,"172"],[1597702800,"172"],[1597702920,"172"],[1597703040,"172"],[1597703160,"165"],[1597703280,"172"],[1597703400,"172"],[1597703520,"172"],[1597703640,"172"],[1597703760,"172"],[1597703880,"172"],[1597704000,"172"],[1597704120,"172"],[1597704240,"172"],[1597704360,"172"],[1597704480,"165"],[1597704600,"172"],[1597704720,"172"],[1597704840,"172"],[1597704960,"172"],[1597705080,"172"],[1597705200,"172"],[1597705320,"172"],[1597705440,"172"],[1597705560,"172"],[1597705680,"172"],[1597705800,"165"],[1597705920,"172"],[1597706040,"172"],[1597706160,"172"],[1597706280,"172"],[1597706400,"172"],[1597706520,"172"],[1597706640,"172"],[1597706760,"172"],[1597706880,"172"],[1597707000,"165"],[1597707120,"172"],[1597707240,"172"],[1597707360,"172"],[1597707480,"172"],[1597707600,"172"],[1597707720,"172"],[1597707840,"172"],[1597707960,"172"],[1597708080,"172"],[1597708200,"165"],[1597708320,"172"],[1597708440,"172"],[1597708560,"172"],[1597708680,"172"],[1597708800,"172"],[1597708920,"172"],[1597709040,"172"],[1597709160,"172"],[1597709280,"172"],[1597709400,"172"],[1597709520,"165"],[1597709640,"172"],[1597709760,"172"],[1597709880,"172"],[1597710000,"172"],[1597710120,"172"],[1597710240,"172"],[1597710360,"172"],[1597710480,"172"],[1597710600,"172"],[1597710720,"172"],[1597710840,"165"],[1597710960,"172"],[1597711080,"172"],[1597711200,"172"],[1597711320,"172"],[1597711440,"172"],[1597711560,"172"],[1597711680,"172"],[1597711800,"172"],[1597711920,"172"],[1597712040,"165"],[1597712160,"172"],[1597712280,"172"],[1597712400,"172"],[1597712520,"172"],[1597712640,"172"],[1597712760,"172"],[1597712880,"172"],[1597713000,"172"],[1597713120,"172"],[1597713240,"172"],[1597713360,"165"],[1597713480,"172"],[1597713600,"172"],[1597713720,"172"],[1597713840,"172"],[1597713960,"172"],[1597714080,"172"],[1597714200,"172"],[1597714320,"172"],[1597714440,"172"],[1597714560,"165"],[1597714680,"172"],[1597714800,"172"],[1597714920,"172"],[1597715040,"172"],[1597715160,"172"],[1597715280,"172"],[1597715400,"172"],[1597715520,"172"],[1597715640,"172"],[1597715760,"172"],[1597715880,"165"],[1597716000,"172"],[1597716120,"172"],[1597716240,"172"],[1597716360,"172"],[1597716480,"172"],[1597716600,"172"],[1597716720,"172"],[1597716840,"172"],[1597716960,"172"],[1597717080,"165"],[1597717200,"172"],[1597717320,"172"],[1597717440,"172"],[1597717560,"172"],[1597717680,"172"],[1597717800,"172"],[1597717920,"172"],[1597718040,"172"],[1597718160,"172"],[1597718280,"165"],[1597718400,"172"],[1597718520,"172"],[1597718640,"172"],[1597718760,"172"],[1597718880,"172"],[1597719000,"172"],[1597719120,"172"],[1597719240,"172"],[1597719360,"172"],[1597719480,"172"],[1597719600,"165"],[1597719720,"172"],[1597719840,"172"],[1597719960,"172"],[1597720080,"172"],[1597720200,"172"],[1597720320,"172"],[1597720440,"172"],[1597720560,"172"],[1597720680,"172"],[1597720800,"172"],[1597720920,"165"],[1597721040,"172"],[1597721160,"172"],[1597721280,"172"],[1597721400,"172"],[1597721520,"172"],[1597721640,"172"],[1597721760,"172"],[1597721880,"172"],[1597722000,"172"],[1597722120,"172"],[1597722240,"165"],[1597722360,"172"],[1597722480,"172"],[1597722600,"172"],[1597722720,"172"],[1597722840,"172"],[1597722960,"172"],[1597723080,"172"],[1597723200,"172"],[1597723320,"172"],[1597723440,"165"],[1597723560,"172"],[1597723680,"172"],[1597723800,"172"],[1597723920,"172"],[1597724040,"172"],[1597724160,"172"],[1597724280,"172"],[1597724400,"172"],[1597724520,"172"],[1597724640,"172"],[1597724760,"165"],[1597724880,"172"],[1597725000,"172"],[1597725120,"172"],[1597725240,"172"],[1597725360,"172"],[1597725480,"172"],[1597725600,"172"],[1597725720,"172"],[1597725840,"172"],[1597725960,"172"],[1597726080,"165"],[1597726200,"172"],[1597726320,"172"],[1597726440,"172"],[1597726560,"172"],[1597726680,"172"],[1597726800,"172"],[1597726920,"172"],[1597727040,"172"],[1597727160,"172"],[1597727280,"172"],[1597727400,"165"],[1597727520,"172"],[1597727640,"172"],[1597727760,"172"],[1597727880,"172"],[1597728000,"172"],[1597728120,"172"],[1597728240,"172"],[1597728360,"172"],[1597728480,"172"],[1597728600,"165"],[1597728720,"172"],[1597728840,"172"],[1597728960,"172"],[1597729080,"172"],[1597729200,"172"],[1597729320,"172"],[1597729440,"172"],[1597729560,"172"],[1597729680,"172"],[1597729800,"165"],[1597729920,"172"],[1597730040,"172"],[1597730160,"172"],[1597730280,"172"],[1597730400,"172"],[1597730520,"172"],[1597730640,"172"],[1597730760,"172"],[1597730880,"172"],[1597731000,"172"],[1597731120,"165"],[1597731240,"172"],[1597731360,"172"],[1597731480,"172"],[1597731600,"172"],[1597731720,"172"],[1597731840,"172"],[1597731960,"172"],[1597732080,"172"],[1597732200,"172"],[1597732320,"165"],[1597732440,"172"],[1597732560,"172"],[1597732680,"172"],[1597732800,"172"],[1597732920,"172"],[1597733040,"172"],[1597733160,"172"],[1597733280,"172"],[1597733400,"172"],[1597733520,"172"],[1597733640,"165"],[1597733760,"172"],[1597733880,"172"],[1597734000,"172"],[1597734120,"172"],[1597734240,"172"],[1597734360,"172"],[1597734480,"172"],[1597734600,"172"],[1597734720,"172"],[1597734840,"172"],[1597734960,"165"],[1597735080,"172"],[1597735200,"172"],[1597735320,"172"],[1597735440,"172"],[1597735560,"172"],[1597735680,"172"],[1597735800,"172"],[1597735920,"172"],[1597736040,"172"],[1597736160,"172"],[1597736280,"165"],[1597736400,"172"],[1597736520,"172"],[1597736640,"172"],[1597736760,"172"],[1597736880,"172"],[1597737000,"172"],[1597737120,"172"],[1597737240,"172"],[1597737360,"172"],[1597737480,"165"],[1597737600,"172"],[1597737720,"172"],[1597737840,"172"],[1597737960,"172"],[1597738080,"172"],[1597738200,"172"],[1597738320,"172"],[1597738440,"172"],[1597738560,"172"],[1597738680,"172"],[1597738800,"165"],[1597738920,"172"],[1597739040,"172"],[1597739160,"172"],[1597739280,"172"],[1597739400,"172"],[1597739520,"172"],[1597739640,"172"],[1597739760,"172"],[1597739880,"172"],[1597740000,"172"],[1597740120,"165"],[1597740240,"172"],[1597740360,"172"],[1597740480,"172"],[1597740600,"172"],[1597740720,"172"],[1597740840,"172"],[1597740960,"172"],[1597741080,"172"],[1597741200,"172"],[1597741320,"165"],[1597741440,"172"],[1597741560,"172"],[1597741680,"172"],[1597741800,"172"],[1597741920,"172"],[1597742040,"172"],[1597742160,"172"],[1597742280,"172"],[1597742400,"172"],[1597742520,"172"],[1597742640,"165"],[1597742760,"172"],[1597742880,"172"],[1597743000,"172"],[1597743120,"172"],[1597743240,"172"],[1597743360,"172"],[1597743480,"172"],[1597743600,"172"],[1597743720,"172"],[1597743840,"165"],[1597743960,"172"],[1597744080,"172"],[1597744200,"172"],[1597744320,"172"],[1597744440,"172"],[1597744560,"172"],[1597744680,"172"],[1597744800,"172"],[1597744920,"172"],[1597745040,"165"],[1597745160,"172"],[1597745280,"172"],[1597745400,"172"],[1597745520,"172"],[1597745640,"172"],[1597745760,"172"],[1597745880,"172"],[1597746000,"172"],[1597746120,"172"],[1597746240,"165"],[1597746360,"172"],[1597746480,"172"],[1597746600,"172"],[1597746720,"172"],[1597746840,"172"],[1597746960,"172"],[1597747080,"172"],[1597747200,"172"],[1597747320,"172"],[1597747440,"172"],[1597747560,"172"],[1597747680,"165"],[1597747800,"172"],[1597747920,"172"],[1597748040,"172"],[1597748160,"172"],[1597748280,"172"],[1597748400,"172"],[1597748520,"172"],[1597748640,"172"],[1597748760,"172"],[1597748880,"165"],[1597749000,"172"],[1597749120,"172"],[1597749240,"172"],[1597749360,"172"],[1597749480,"172"],[1597749600,"172"],[1597749720,"172"],[1597749840,"172"],[1597749960,"172"],[1597750080,"172"],[1597750200,"165"],[1597750320,"172"],[1597750440,"172"],[1597750560,"172"],[1597750680,"172"],[1597750800,"172"],[1597750920,"172"],[1597751040,"172"],[1597751160,"172"],[1597751280,"172"],[1597751400,"165"],[1597751520,"172"],[1597751640,"172"],[1597751760,"172"],[1597751880,"172"],[1597752000,"172"],[1597752120,"172"],[1597752240,"172"],[1597752360,"172"],[1597752480,"172"],[1597752600,"172"],[1597752720,"172"],[1597752840,"165"],[1597752960,"172"],[1597753080,"172"],[1597753200,"172"],[1597753320,"172"],[1597753440,"172"],[1597753560,"172"],[1597753680,"172"],[1597753800,"172"],[1597753920,"172"],[1597754040,"165"],[1597754160,"172"],[1597754280,"172"],[1597754400,"172"],[1597754520,"172"],[1597754640,"172"],[1597754760,"172"],[1597754880,"172"],[1597755000,"172"],[1597755120,"172"],[1597755240,"172"],[1597755360,"165"],[1597755480,"172"],[1597755600,"172"],[1597755720,"172"],[1597755840,"172"],[1597755960,"172"],[1597756080,"172"],[1597756200,"172"],[1597756320,"172"],[1597756440,"172"],[1597756560,"165"],[1597756680,"172"],[1597756800,"172"],[1597756920,"172"],[1597757040,"172"],[1597757160,"172"],[1597757280,"172"],[1597757400,"172"],[1597757520,"172"],[1597757640,"172"],[1597757760,"172"],[1597757880,"165"],[1597758000,"172"],[1597758120,"172"],[1597758240,"172"],[1597758360,"172"],[1597758480,"172"],[1597758600,"172"],[1597758720,"172"],[1597758840,"172"],[1597758960,"172"],[1597759080,"165"],[1597759200,"172"],[1597759320,"172"],[1597759440,"172"],[1597759560,"172"],[1597759680,"172"],[1597759800,"172"],[1597759920,"172"],[1597760040,"172"],[1597760160,"172"],[1597760280,"172"],[1597760400,"165"],[1597760520,"172"],[1597760640,"172"],[1597760760,"172"],[1597760880,"172"],[1597761000,"172"],[1597761120,"172"],[1597761240,"172"],[1597761360,"172"],[1597761480,"172"],[1597761600,"172"],[1597761720,"165"],[1597761840,"172"],[1597761960,"172"],[1597762080,"172"],[1597762200,"172"],[1597762320,"172"],[1597762440,"172"],[1597762560,"172"],[1597762680,"172"],[1597762800,"172"],[1597762920,"172"],[1597763040,"165"],[1597763160,"172"],[1597763280,"172"],[1597763400,"172"],[1597763520,"172"],[1597763640,"172"],[1597763760,"172"],[1597763880,"172"],[1597764000,"172"],[1597764120,"172"],[1597764240,"165"],[1597764360,"172"],[1597764480,"172"],[1597764600,"172"],[1597764720,"172"],[1597764840,"172"],[1597764960,"172"],[1597765080,"172"],[1597765200,"172"],[1597765320,"172"],[1597765440,"165"],[1597765560,"172"],[1597765680,"172"],[1597765800,"172"],[1597765920,"172"],[1597766040,"172"],[1597766160,"172"],[1597766280,"172"],[1597766400,"172"],[1597766520,"172"],[1597766640,"172"],[1597766760,"165"],[1597766880,"172"],[1597767000,"172"],[1597767120,"172"],[1597767240,"172"],[1597767360,"172"],[1597767480,"172"],[1597767600,"172"],[1597767720,"172"],[1597767840,"172"],[1597767960,"168"],[1597768080,"169"],[1597768200,"172"],[1597768320,"172"],[1597768440,"172"],[1597768560,"172"],[1597768680,"172"],[1597768800,"172"],[1597768920,"172"],[1597769040,"172"],[1597769160,"165"],[1597769280,"172"],[1597769400,"172"],[1597769520,"172"],[1597769640,"172"],[1597769760,"172"],[1597769880,"172"],[1597770000,"172"],[1597770120,"172"],[1597770240,"172"],[1597770360,"172"],[1597770480,"165"],[1597770600,"172"],[1597770720,"172"],[1597770840,"172"],[1597770960,"172"],[1597771080,"172"],[1597771200,"172"],[1597771320,"172"],[1597771440,"172"],[1597771560,"172"],[1597771680,"172"],[1597771800,"165"],[1597771920,"172"],[1597772040,"172"],[1597772160,"172"],[1597772280,"172"],[1597772400,"172"],[1597772520,"172"],[1597772640,"172"],[1597772760,"172"],[1597772880,"172"],[1597773000,"172"],[1597773120,"165"],[1597773240,"172"],[1597773360,"172"],[1597773480,"172"],[1597773600,"172"],[1597773720,"172"],[1597773840,"172"],[1597773960,"172"],[1597774080,"172"],[1597774200,"172"],[1597774320,"165"],[1597774440,"172"],[1597774560,"172"],[1597774680,"172"],[1597774800,"172"],[1597774920,"172"],[1597775040,"172"],[1597775160,"172"],[1597775280,"172"],[1597775400,"172"],[1597775520,"172"],[1597775640,"165"],[1597775760,"172"],[1597775880,"172"],[1597776000,"172"],[1597776120,"172"],[1597776240,"172"],[1597776360,"172"],[1597776480,"172"],[1597776600,"172"],[1597776720,"172"],[1597776840,"165"],[1597776960,"172"],[1597777080,"172"],[1597777200,"172"],[1597777320,"172"],[1597777440,"172"],[1597777560,"172"],[1597777680,"172"],[1597777800,"172"],[1597777920,"172"],[1597778040,"172"],[1597778160,"165"],[1597778280,"172"],[1597778400,"172"],[1597778520,"172"],[1597778640,"172"],[1597778760,"172"],[1597778880,"172"],[1597779000,"172"],[1597779120,"172"],[1597779240,"172"],[1597779360,"165"],[1597779480,"172"],[1597779600,"172"],[1597779720,"172"],[1597779840,"172"],[1597779960,"172"],[1597780080,"172"],[1597780200,"172"],[1597780320,"172"],[1597780440,"172"],[1597780560,"172"],[1597780680,"165"],[1597780800,"172"],[1597780920,"172"],[1597781040,"172"],[1597781160,"172"],[1597781280,"172"],[1597781400,"172"],[1597781520,"172"],[1597781640,"172"],[1597781760,"172"],[1597781880,"165"],[1597782000,"172"],[1597782120,"172"],[1597782240,"172"],[1597782360,"172"],[1597782480,"172"],[1597782600,"172"],[1597782720,"172"],[1597782840,"172"],[1597782960,"172"],[1597783080,"172"],[1597783200,"165"],[1597783320,"172"],[1597783440,"172"],[1597783560,"172"],[1597783680,"172"],[1597783800,"172"],[1597783920,"172"],[1597784040,"172"],[1597784160,"172"],[1597784280,"172"],[1597784400,"172"],[1597784520,"165"],[1597784640,"172"],[1597784760,"172"],[1597784880,"172"],[1597785000,"172"],[1597785120,"172"],[1597785240,"172"],[1597785360,"172"],[1597785480,"172"],[1597785600,"172"],[1597785720,"165"],[1597785840,"172"],[1597785960,"172"],[1597786080,"172"],[1597786200,"172"],[1597786320,"172"],[1597786440,"172"],[1597786560,"172"],[1597786680,"172"],[1597786800,"172"],[1597786920,"172"],[1597787040,"165"],[1597787160,"172"],[1597787280,"172"],[1597787400,"172"],[1597787520,"172"],[1597787640,"172"],[1597787760,"172"],[1597787880,"172"],[1597788000,"172"],[1597788120,"172"],[1597788240,"165"],[1597788360,"172"],[1597788480,"172"],[1597788600,"172"],[1597788720,"172"],[1597788840,"172"],[1597788960,"172"],[1597789080,"172"],[1597789200,"172"],[1597789320,"172"],[1597789440,"172"],[1597789560,"165"],[1597789680,"172"],[1597789800,"172"],[1597789920,"172"],[1597790040,"172"],[1597790160,"172"],[1597790280,"172"],[1597790400,"172"],[1597790520,"172"],[1597790640,"172"],[1597790760,"165"],[1597790880,"172"],[1597791000,"172"],[1597791120,"172"],[1597791240,"172"],[1597791360,"172"],[1597791480,"172"],[1597791600,"172"],[1597791720,"172"],[1597791840,"172"],[1597791960,"172"],[1597792080,"165"],[1597792200,"172"],[1597792320,"172"],[1597792440,"172"],[1597792560,"172"],[1597792680,"172"],[1597792800,"172"],[1597792920,"172"],[1597793040,"172"],[1597793160,"172"],[1597793280,"172"],[1597793400,"165"],[1597793520,"172"],[1597793640,"172"],[1597793760,"172"],[1597793880,"172"],[1597794000,"172"],[1597794120,"172"],[1597794240,"172"],[1597794360,"172"],[1597794480,"172"],[1597794600,"165"],[1597794720,"172"],[1597794840,"172"],[1597794960,"172"],[1597795080,"172"],[1597795200,"172"],[1597795320,"172"],[1597795440,"172"],[1597795560,"172"],[1597795680,"172"],[1597795800,"172"],[1597795920,"165"],[1597796040,"172"],[1597796160,"172"],[1597796280,"172"],[1597796400,"172"],[1597796520,"172"],[1597796640,"172"],[1597796760,"172"],[1597796880,"172"],[1597797000,"172"],[1597797120,"165"],[1597797240,"172"],[1597797360,"172"],[1597797480,"172"],[1597797600,"172"],[1597797720,"172"],[1597797840,"172"],[1597797960,"172"],[1597798080,"172"],[1597798200,"172"],[1597798320,"172"],[1597798440,"165"],[1597798560,"172"],[1597798680,"172"],[1597798800,"172"],[1597798920,"172"],[1597799040,"172"],[1597799160,"172"],[1597799280,"172"],[1597799400,"172"],[1597799520,"172"],[1597799640,"172"],[1597799760,"165"],[1597799880,"172"],[1597800000,"172"],[1597800120,"172"],[1597800240,"172"],[1597800360,"172"],[1597800480,"172"],[1597800600,"172"],[1597800720,"172"],[1597800840,"172"],[1597800960,"165"],[1597801080,"172"],[1597801200,"172"],[1597801320,"172"],[1597801440,"172"],[1597801560,"172"],[1597801680,"172"],[1597801800,"172"],[1597801920,"172"],[1597802040,"172"],[1597802160,"172"],[1597802280,"165"],[1597802400,"172"],[1597802520,"172"],[1597802640,"172"],[1597802760,"172"],[1597802880,"172"],[1597803000,"172"],[1597803120,"172"],[1597803240,"172"],[1597803360,"172"],[1597803480,"172"],[1597803600,"165"],[1597803720,"172"],[1597803840,"172"],[1597803960,"172"],[1597804080,"172"],[1597804200,"172"],[1597804320,"172"],[1597804440,"172"],[1597804560,"172"],[1597804680,"172"],[1597804800,"165"],[1597804920,"172"],[1597805040,"172"],[1597805160,"172"],[1597805280,"172"],[1597805400,"172"],[1597805520,"172"],[1597805640,"172"],[1597805760,"172"],[1597805880,"172"],[1597806000,"165"],[1597806120,"172"],[1597806240,"172"],[1597806360,"172"],[1597806480,"172"],[1597806600,"172"],[1597806720,"172"],[1597806840,"172"],[1597806960,"172"],[1597807080,"172"],[1597807200,"172"],[1597807320,"165"],[1597807440,"172"],[1597807560,"172"],[1597807680,"172"],[1597807800,"172"],[1597807920,"172"],[1597808040,"172"],[1597808160,"172"],[1597808280,"172"],[1597808400,"172"],[1597808520,"172"],[1597808640,"165"],[1597808760,"172"],[1597808880,"172"],[1597809000,"172"],[1597809120,"172"],[1597809240,"172"],[1597809360,"172"],[1597809480,"172"],[1597809600,"172"],[1597809720,"172"],[1597809840,"165"],[1597809960,"172"],[1597810080,"172"],[1597810200,"172"],[1597810320,"172"],[1597810440,"172"],[1597810560,"172"],[1597810680,"172"],[1597810800,"172"],[1597810920,"172"],[1597811040,"166"],[1597811160,"171"],[1597811280,"172"],[1597811400,"172"],[1597811520,"172"],[1597811640,"172"],[1597811760,"172"],[1597811880,"172"],[1597812000,"172"],[1597812120,"172"],[1597812240,"172"],[1597812360,"168"],[1597812480,"169"],[1597812600,"172"],[1597812720,"172"],[1597812840,"172"],[1597812960,"172"],[1597813080,"172"],[1597813200,"172"],[1597813320,"172"],[1597813440,"172"],[1597813560,"172"],[1597813680,"165"],[1597813800,"172"],[1597813920,"172"],[1597814040,"172"],[1597814160,"172"],[1597814280,"172"],[1597814400,"172"],[1597814520,"172"],[1597814640,"172"],[1597814760,"172"],[1597814880,"172"],[1597815000,"165"],[1597815120,"172"],[1597815240,"172"],[1597815360,"172"],[1597815480,"172"],[1597815600,"172"],[1597815720,"172"],[1597815840,"172"],[1597815960,"172"],[1597816080,"172"],[1597816200,"165"],[1597816320,"172"],[1597816440,"172"],[1597816560,"172"],[1597816680,"172"],[1597816800,"172"],[1597816920,"172"],[1597817040,"172"],[1597817160,"172"],[1597817280,"172"],[1597817400,"165"],[1597817520,"172"],[1597817640,"172"],[1597817760,"172"],[1597817880,"172"],[1597818000,"172"],[1597818120,"172"],[1597818240,"172"],[1597818360,"172"],[1597818480,"172"],[1597818600,"172"],[1597818720,"165"],[1597818840,"172"],[1597818960,"172"],[1597819080,"172"],[1597819200,"172"],[1597819320,"172"],[1597819440,"172"],[1597819560,"172"],[1597819680,"172"],[1597819800,"172"],[1597819920,"172"],[1597820040,"165"],[1597820160,"172"],[1597820280,"172"],[1597820400,"172"],[1597820520,"172"],[1597820640,"172"],[1597820760,"172"],[1597820880,"172"],[1597821000,"172"],[1597821120,"172"],[1597821240,"165"],[1597821360,"172"],[1597821480,"172"],[1597821600,"172"],[1597821720,"172"],[1597821840,"172"],[1597821960,"172"],[1597822080,"172"],[1597822200,"172"],[1597822320,"172"],[1597822440,"172"],[1597822560,"165"],[1597822680,"172"],[1597822800,"172"],[1597822920,"172"],[1597823040,"172"],[1597823160,"172"],[1597823280,"172"],[1597823400,"172"],[1597823520,"172"],[1597823640,"165"]]}],"stats":{"summary":{"bytesProcessedPerSecond":260259609,"linesProcessedPerSecond":613085,"totalBytesProcessed":341469665,"totalLinesProcessed":804390,"execTime":1.3120348},"store":{"totalChunksRef":1176,"totalChunksDownloaded":1176,"chunksDownloadTime":0.0798912,"headChunkBytes":0,"headChunkLines":0,"decompressedBytes":341469665,"decompressedLines":804390,"compressedBytes":14971983,"totalDuplicates":0},"ingester":{"totalReached":1,"totalChunksMatched":0,"totalBatches":0,"totalLinesSent":0,"headChunkBytes":0,"headChunkLines":0,"decompressedBytes":0,"decompressedLines":0,"compressedBytes":0,"totalDuplicates":0}}}}
```
I believe that as the first query returns no data, then the plugin gets a bit lost. So is this the behavior from now on? Trigger a Query then a query_range?

**Environment**:
- Grafana version: 7.2 from 23.09.2020, https://github.com/grafana/grafana/releases/tag/v7.2.0
- Loki version: 1.6.1 from 24.08.2020, https://github.com/grafana/loki/releases/tag/v1.6.1
- Pie Chart: 1.6.1 from 14.09.2020, https://grafana.com/grafana/plugins/grafana-piechart-panel
- User OS & Browser: Windows 10 + Chrome or Edge(Chrome based edition)

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
Following up on https://github.com/grafana/grafana/issues/27860 and our discussion, this PR removes running of instant queries in dashboard (regression in 7.2 by https://github.com/grafana/grafana/pull/27213)

Fixes https://github.com/grafana/grafana/issues/27860

### CODE REVIEW

File: public/app/plugins/datasource/loki/datasource.ts [hunk 1]
```diff
@@ -93,12 +94,13 @@ export class LokiDatasource extends DataSourceApi<LokiQuery, LokiOptions> {
         expr: this.templateSrv.replace(target.expr, options.scopedVars, this.interpolateQueryExpr),
       }));
 
-    filteredTargets.forEach(target =>
-      subQueries.push(
-        this.runInstantQuery(target, options, filteredTargets.length),
-        this.runRangeQuery(target, options, filteredTargets.length)
-      )
-    );
+    filteredTargets.forEach(target => {
```
Comment (torkelo) [inline public/app/plugins/datasource/loki/datasource.ts:97]: nit: use for(const target of

**Review by torkelo — APPROVED** [review]
Looks good, only one small nit pick
