### PR TITLE
Chore: Fix plugins magefile for Azure

### LINKED ISSUE #81000: Fix issue in az monitor release standalone
Fix: https://github.com/grafana/grafana/actions/runs/7613430426/job/20733299236

### PR DESCRIPTION
**Pull request by andresmgot**
**What is this feature?**

Similar fixes than https://github.com/grafana/grafana/pull/80528 and https://github.com/grafana/grafana/pull/81065 but for the Magefile used to build plugins.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/81000

### CODE REVIEW

File: pkg/tsdb/Magefile.go [hunk 1]
```diff
@@ -26,8 +26,16 @@ func find(dir string, name string) ([]string, error) {
...
+func fileHasString(path string, s string) bool {
+	f, err := os.ReadFile(path)
+	if err != nil {
+		return false
+	}
+	return strings.Contains(string(f), s)
+}
+
+func findPluginJSONDir(pluginID string) (string, error) {
+	pluginJSONMatches, err := find(filepath.Join("../../public/app/plugins/datasource"), "plugin.json")
```
Comment (wbrowne) [inline pkg/tsdb/Magefile.go:38]: Nit: Maybe something to use eventually here instead https://pkg.go.dev/path/filepath#Glob

**Review by wbrowne — APPROVED** [review]
LGTM

File: pkg/tsdb/Magefile.go (hunk 1 above)
Comment (andresmgot) [reply pkg/tsdb/Magefile.go:38]: right, a pity that Glob doesn't work with `**` in paths
