### PR TITLE
TablePanel: fix footer bug; no footer calculated values after "hidden" column override

### LINKED ISSUE #58896: TablePanel: Footer works incorrectly with 'Hide in table'
**What happened**:
Don't know how to describe. The column set Hide in table to True will cause footer hide incorrectly.
image

**Environment**:
- Grafana version: Grafana v9.2.4 (64017e8ca6)
- User OS & Browser: Windows 11 Edge

### PR DESCRIPTION
**Pull request by baldm0mma**
What is this feature?

Bug fix where footer values aren't rendering properly on hide in table column override. Specifically the footer calculation that is the index directly after an override "hidden" column. See https://github.com/grafana/grafana/issues/58896 issue.

Why do we need this feature?

Bugs are bad, m'cay?

Who is this feature for?

Everyone.

Which issue(s) does this PR fix?:

Fixes https://github.com/grafana/grafana/issues/58896

Special notes for your reviewer:
N/A

Before:
Screenshot 2023-03-06 at 2 54 57 PM (2)

After:
Screenshot 2023-03-06 at 2 59 20 PM (2)

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/utils.ts [hunk 1]
```diff
@@ -477,3 +506,18 @@ export const defaultRowNumberColumnFieldData: Omit<Field, 'values'> = {
     },
   },
 };
+
```
Comment (codeincarnate) [inline packages/grafana-ui/src/components/Table/utils.ts:509]: The comments are great! Let's add a TSDoc comment for the function here as well 😄

**Review by codeincarnate — COMMENTED** [review]
The comments are great! And tested out the fix and appears to work just fine. I think adding the TSDoc comment to the added function would be awesome but otherwise looks good 😄

**Review by codeincarnate — APPROVED** [review]
Looks great! 🚀
