### PR TITLE
Datasource: fix a bug where deleting data source will trigger save an…

### LINKED ISSUE #21282: Deleting datasource will trigger save and test events
**What happened**:
    I want to delete data source, but when I click the delete button, the page prompts "Datasource updated" and "Data source is working". Clicking the delete button triggered the save and test events.
grafana_bug

**What you expected to happen**:
    After clicking the delete button, a delete confirmation box pops up without displaying other prompts.

**How to reproduce it (as minimally and precisely as possible)**:
    1. Add a data source and save it;
    2.click Delete button;

**Anything else we need to know?**:

**Environment**: 
- Grafana version: v6.5.2
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker 
- User OS & Browser: MacOS && chrome 79.0.3945.88
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by lzdw**
…d test events

**What this PR does / why we need it**:
    Fix a bug where deleting data source will trigger save and test events

**Which issue(s) this PR fixes**:

Fixes #21282

**Special notes for your reviewer**:

### CODE REVIEW

**Review by dprokop — CHANGES_REQUESTED** [review]
@lzdw thank's for the fix. Looking into the code the problems lies in the fact that both Save & Test and Delete buttons have type `submit`. Of course your fix is a correct one but it introduces some complexity. My suggestion is to change the code to use `Button` component from grafana/ui instead of plain buttons. grafana/ui button has default type of `button` which means that the submit will not happen and the event prevention will not be necessary.

File: public/app/features/datasources/settings/DataSourceSettingsPage.tsx [hunk 1]
```diff
@@ -209,7 +210,7 @@ export class DataSourceSettingsPage extends PureComponent<Props, State> {
           <div>
             <div className="gf-form-button-row">
               {showDelete && (
-                <button type="submit" className="btn btn-danger" onClick={this.onDelete}>
+                <button type="submit" className="btn btn-danger" onClick={event => this.onDelete(event)}>
```
Comment (torkelo) [inline public/app/features/datasources/settings/DataSourceSettingsPage.tsx]: Why is the delete button a submit button, can’t it be a normal button and this problem would go away?

Comment (lzdw) [reply public/app/features/datasources/settings/DataSourceSettingsPage.tsx]: Yes, it can be a normal button, but I  think it is better to be consistent with the save button.

Comment (lzdw) [reply public/app/features/datasources/settings/DataSourceSettingsPage.tsx]: Yes, of course. But before, I want it to be consistent with the save button.
Now,I have resolved .

**Review by torkelo — APPROVED** [review]
