### PR TITLE
fix ipv6 startup fail #81870

### LINKED ISSUE #81870: cannot derive external address port without listening on a secure port.
### What happened?

```
logger=ticker t=2024-02-05T10:36:28.496462788+01:00 level=info msg=starting first_tick=2024-02-05T10:36:30+01:00
logger=sqlstore t=2024-02-05T10:36:28.339411276+01:00 level=info msg="Connecting to DB" dbtype=postgres
logger=settings t=2024-02-05T10:36:28.338576283+01:00 level=info msg="App mode production"
logger=settings t=2024-02-05T10:36:28.338564591+01:00 level=info msg="Path Provisioning" path=/nix/store/7v9i6mkimy42wf1lhc22aw54vidc7fq4-grafana-provisioning
logger=settings t=2024-02-05T10:36:28.338553821+01:00 level=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2024-02-05T10:36:28.338543252+01:00 level=info msg="Path Logs" path=/var/lib/grafana/data/log
logger=settings t=2024-02-05T10:36:28.338532921+01:00 level=info msg="Path Data" path=/var/lib/grafana/data
logger=settings t=2024-02-05T10:36:28.338516989+01:00 level=info msg="Path Home" path=/var/lib/grafana
logger=settings t=2024-02-05T10:36:28.338500519+01:00 level=info msg=Target target=[all]
logger=settings t=2024-02-05T10:36:28.338487535+01:00 level=info msg="Config loaded from" file=/nix/store/8yrfznz7xd9kch6jpgs3pni9gl8kn1iw-config.ini
logger=settings t=2024-02-05T10:36:28.338450025+01:00 level=info msg="Config loaded from" file=/var/lib/grafana/conf/defaults.ini
logger=settings t=2024-02-05T10:36:28.335772108+01:00 level=info msg="Starting Grafana" version=10.3.1 commit=NA branch=main compiled=2024-02-05T10:36:28+01:00
logger=secrets t=2024-02-05T10:36:28.360905533+01:00 level=info msg="Envelope encryption state" enabled=true currentprovider=secretKey.v1
logger=query_data t=2024-02-05T10:36:28.442449428+01:00 level=info msg="Query Service initialization"
logger=provisioning.datasources t=2024-02-05T10:36:28.466482236+01:00 level=info msg="inserting datasource from configuration" name=Prometheus uid=PBFA97CFB590B2093
logger=provisioning.datasources t=2024-02-05T10:36:28.465923427+01:00 level=info msg="deleted datasource based on configuration" name=Prometheus
logger=provisioning.alerting t=2024-02-05T10:36:28.489262978+01:00 level=info msg="finished to provision alerting"
logger=provisioning.alerting t=2024-02-05T10:36:28.489226316+01:00 level=info msg="starting to provision alerting"
logger=plugin.store t=2024-02-05T10:36:28.439355825+01:00 level=info msg="Plugins loaded" count=55 duration=49.157436ms
logger=plugin.store t=2024-02-05T10:36:28.390199487+01:00 level=info msg="Loading plugins..."
logger=ngalert.state.manager t=2024-02-05T10:36:28.496259754+01:00 level=info msg="State cache has been initialized" states=0 duration=4.832784ms
logger=ngalert.state.manager t=2024-02-05T10:36:28.491420467+01:00 level=info msg="Warming state cache for startup"
logger=ngalert.scheduler t=2024-02-05T10:36:28.496330913+01:00 level=info msg="Starting scheduler" tickInterval=10s
logger=ngalert.multiorg.alertmanager t=2024-02-05T10:36:28.494325352+01:00 level=info msg="Starting MultiOrg Alertmanager"
logger=ngalert.migration t=2024-02-05T10:36:28.449082443+01:00 level=info msg=Starting
logger=ngalert.migration CurrentType=UnifiedAlerting DesiredType=UnifiedAlerting CleanOnDowngrade=false CleanOnUpgrade=false t=2024-02-05T10:36:28.449856001+01:00 level=info msg="Migration already complete"
logger=migrator t=2024-02-05T10:36:28.354841941+01:00 level=info msg="migrations completed" performed=0 skipped=526 duration=956.449µs
logger=migrator t=2024-02-05T10:36:28.341513348+01:00 level=info msg="Starting DB migrations"
logger=local.finder t=2024-02-05T10:36:28.491757721+01:00 level=warn msg="Skipping finding plugins as directory does not exist" path=/var/lib/grafana/plugins
logger=local.finder t=2024-02-05T10:36:28.439264787+01:00 level=warn msg="Skipping finding plugins as directory does not exist" path=/var/lib/grafana/plugins
logger=local.finder t=2024-02-05T10:36:28.439055321+01:00 level=warn msg="Skipping finding plugins as directory does not exist" path=/var/lib/grafana/plugins-bundled
logger=local.finder t=2024-02-05T10:36:28.388120441+01:00 level=warn msg="Skipping finding plugins as directory does not exist" path=/var/lib/grafana/plugins
logger=live.push_http t=2024-02-05T10:36:28.446834+01:00 level=info msg="Live Push Gateway initialization"
logger=infra.usagestats.collector t=2024-02-05T10:36:28.461017013+01:00 level=info msg="registering usage stat providers" usageStatsProvidersLen=2
logger=http.server t=2024-02-05T10:36:28.494887695+01:00 level=info msg="HTTP Server Listen" address=[::1]:8000 protocol=http subUrl= socket=
logger=grafanaStorageLogger t=2024-02-05T10:36:28.494964381+01:00 level=info msg="Storage starting"
logger=grafana-apiserver t=2024-02-05T10:36:28.502640384+01:00 level=info msg="cannot derive external address port without listening on a secure port."
```

### What did you expect to happen?

For it to run normally, the config worked on an older version, my config is like so:

```nix
    settings = {
      analytics.reporting_enabled = false;

      database.host = "/run/postgresql";
      database.type = "postgres";
      database.user = "grafana";

      server.domain    = fqdn;
      server.http_addr = "::";
      server.http_port = 8000;

      users.default_theme = "system";
    };

    settings.security = {
      admin_email    = "metrics@${domain}";
      admin_password = "$__file{${config.age.secrets."cube/password.grafana".path}}";
      admin_user     = "admin";

      cookie_secure    = true;
      disable_gravatar = true;

      disable_initial_admin_creation = true; # Just in case.
    };

    settings.smtp = {
      enabled = true;

      password        = "$__file{${config.age.secrets."cube/password.mail.grafana".path}}";
      startTLS_policy = "MandatoryStartTLS";

      ehlo_identity = "contact@${domain}";
      from_address  = "metrics@${domain}";
      from_name     = "Metrics";
      host          = "${config.mailserver.fqdn}:${toString config.services.postfix.relayPort}";
    };
```

### Did this work before?

Yes, 10.2.3

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 10.3.1
OS: NixOS
Browser: -

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

-

### PR DESCRIPTION
**Pull request by yincongcyincong**
**Which issue(s) does this PR fix?**:
When the ipv6 configuration is not enclosed in square brackets，apiserver printed a fatal log and exited.
https://github.com/kubernetes/apiserver/blob/master/pkg/server/config.go#L686
I solve the issue. When the ip is ipv6, it enclose in square brackets.

image

Fixes #81870 https://github.com/grafana/grafana/issues/81870

### CODE REVIEW

**Comment by RGBCube** [comment]
Does it still work when you provide the IP in [] brackets? Wouldn't want to break peoples setups.

**Comment by yincongcyincong** [comment]
> Does it still work when you provide the IP in [] brackets? Wouldn't want to break peoples setups.

 the IP in [] brackets don't work, the server just listen :3000, don't have a ip

**Comment by RGBCube** [comment]
I think it should be backwards compatible as a few people might already specify ip addresses with brackets.

**Comment by DanCech** [comment]
There are a few different concerns here, firstly with the current code an ipv6 address wrapped in square brackets will fail because net.ParseIP will fail and return nil in that case, so we can at least exclude that possibility.

The first thing we should likely do is to correctly handle an error parsing the provided address, but to fix that we'll need to update the applyGrafanaConfig function so it can return an error. With that change, if net.ParseIP returns nil we can return an error.

Once we have a valid IP, we can use netip.AddrFromSlice to get a valid Addr from our IP (and handle any errors), then pass that to netip.AddrPortFrom (together with the port) and finally use MarshalText on the returned AddrPort to generate the host string with ipv6 addresses properly wrapped in square brackets (again checking that the returned string is not empty and returning an error).

**Comment by yincongcyincong** [comment]
> There are a few different concerns here, firstly with the current code an ipv6 address wrapped in square brackets will fail because net.ParseIP will fail and return nil in that case, so we can at least exclude that possibility.
> 
> The first thing we should likely do is to correctly handle an error parsing the provided address, but to fix that we'll need to update the applyGrafanaConfig function so it can return an error. With that change, if net.ParseIP returns nil we can return an error.
> 
> Once we have a valid IP, we can use netip.AddrFromSlice to get a valid Addr from our IP (and handle any errors), then pass that to netip.AddrPortFrom (together with the port) and finally use MarshalText on the returned AddrPort to generate the host string with ipv6 addresses properly wrapped in square brackets (again checking that the returned string is not empty and returning an error).

i think this suggestion is very helpeful, i will update my code.

**Comment by yincongcyincong** [comment]
> I think it should be backwards compatible as a few people might already specify ip addresses with brackets.

new pr is compatible

**Review by toddtreece — APPROVED** [review]

File: pkg/services/apiserver/config.go [hunk 1]
```diff
@@ -5,15 +5,20 @@ import (
...
 	"github.com/grafana/grafana/pkg/services/apiserver/options"
 	"github.com/grafana/grafana/pkg/services/featuremgmt"
 	"github.com/grafana/grafana/pkg/setting"
 )
 
-func applyGrafanaConfig(cfg *setting.Cfg, features featuremgmt.FeatureToggles, o *options.Options) {
+func applyGrafanaConfig(cfg *setting.Cfg, features featuremgmt.FeatureToggles, o *options.Options) error {
 	defaultLogLevel := 0
-	ip := net.ParseIP(cfg.HTTPAddr)
+	ipStr := strings.TrimSuffix(strings.TrimPrefix(cfg.HTTPAddr, "["), "]")
```
Comment (DanCech) [inline pkg/services/apiserver/config.go:17]: Not sure that we actually need this, since right now ipv6 addresses enclosed in square brackets don't work (afaik) and we're better off being strict about input and requiring a valid ip address

Comment (yincongcyincong) [reply pkg/services/apiserver/config.go:17]: i see, but some people use IP in [] brackets. it will return some error.

**Review by DanCech — APPROVED** [review]
LGTM

**Comment by yincongcyincong** [comment]
> @yincongcyincong it looks like your earlier commits have an email address that doesn't match your github account, which is causing the CLA bot to reject the PR. I think you can fix that by adding your baidu email address to your github profile [here](https://github.com/settings/emails).

thanks, bro. i have added my baidu email.
