### PR TITLE
TableNG: Add bottom border to column headers + fix footer styling

### LINKED ISSUE #100619: TableNG: Fix Table Border Styling
Borders should be correctly placed to achieve feature parity.

Current table:
Image

TableNG:
Image

### LINKED ISSUE #101008: TableNG: Footer summary styles
The summary footer styles need to be updated so they don't clash with data grid row styling. 

https://github.com/user-attachments/assets/96ae7cd7-057c-4d19-aa7a-0d50defefde2

### PR DESCRIPTION
**Pull request by alexjonspencer1**
## What does this PR do? 📓 

This PR solves two issues: 

1. Adds a bottom border to the column headers for parity with TableOG
2. Updates footer styles so they're not busted

Fixes #100619 & #101008

#### **Note regarding number 1**: 

Due to bizarre styling added by the data-grid library, we have to hack a bit for a nicer experience. The `border-inline-end` CSS property used by the data-grid package creates weird border gapping. To fix this, we need to unset that CSS property, and add our own border.

### Table Before:

https://github.com/user-attachments/assets/7d163f7c-5da9-4dee-991e-99aa09fcb8e7

### Table After: 

https://github.com/user-attachments/assets/00f9b13e-aa6f-4566-812f-256b0f068231

### _Weird gap_: 

Screenshot 2025-02-19 at 3 13 23 PM

### _Weird gap, fixed_:

Screenshot 2025-02-19 at 3 12 58 PM

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/TableNG/TableNG.tsx [hunk 1]
```diff
@@ -716,6 +716,30 @@ const getStyles = (theme: GrafanaTheme2, textWrap: boolean) => ({
...
+    // get a small gap where the gridCell borders meet the column header borders.
+    // To avoid this, we can unset borderInlineEnd and set borderRight instead.
+    '.rdg-cell': {
+      borderInlineEnd: 'unset',
+      borderRight: `1px solid ${theme.colors.border.medium}`,
+    },
+
+    '.rdg-summary-row': {
+      backgroundColor: theme.colors.background.primary,
+      '--rdg-summary-border-color': theme.colors.border.medium,
```
Comment (drew08t) [inline packages/grafana-ui/src/components/Table/TableNG/TableNG.tsx:730]: This is redundant with line 709, no? It overrides it, but both can be used to set the summary border color. Unless I'm missing something, let's just use one.

**Review by drew08t — APPROVED** [review]
Other than that minor comment, this LGTM! Good job tightening this styling up!

File: packages/grafana-ui/src/components/Table/TableNG/TableNG.tsx (hunk 1 above)
Comment (alexjonspencer1) [reply packages/grafana-ui/src/components/Table/TableNG/TableNG.tsx:729]: Good catch, I meant to remove this! 🚀
