### PR TITLE
Fix: Reimplement HideFromTabs in Tabs component

### LINKED ISSUE #21851: 'Divider' tab visible in Manage Dashboards view, but can't interact with it
**What happened**:
In the 'Manage Dashboards' view of grafana 6.6.0 I noticed a 'tab' labeled as "Divider" that seems to serve no purpose. Can't click or interact with it, and I couldn't locate any documentation on it. Not sure if it is meant to be an invisible element or if some actual content is missing. I don't remember this being visible in 6.5

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Login to Grafana 6.6.0. Hover mouse over the Dashboards icon on left shortcut panel. Select 'Manage'. Should see the Divider tab as indicated in the attached screenshot.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: n/a
- OS Grafana is installed on: Centos 7
- User OS & Browser: OS X (catalina), Firefox 72.0.2
- Grafana plugins: n/a
- Others: n/a
image

### PR DESCRIPTION
**Pull request by peterholmberg**
**What this PR does / why we need it**:
Missed checking for `hideFromTabs` in the new Tabs component. I thought it made more sense to put this in the component instead of having every other component implementing `<Tab />` to add this logic.

**Which issue(s) this PR fixes**:
Fixes #21851

**Special notes for your reviewer**:

### CODE REVIEW

File: packages/grafana-ui/src/components/Tabs/Tab.tsx [hunk 1]
```diff
@@ -62,10 +63,14 @@ const getTabStyles = stylesFactory((theme: GrafanaTheme) => {
   };
 });
 
-export const Tab: FC<TabProps> = ({ label, active, icon, onChangeTab }) => {
+export const Tab: FC<TabProps> = ({ label, active, icon, onChangeTab, hideFromTabs }) => {
   const theme = useTheme();
   const tabsStyles = getTabStyles(theme);
 
+  if (hideFromTabs) {
```
Comment (dprokop) [inline packages/grafana-ui/src/components/Tabs/Tab.tsx]: Do we really need this? I think we should simply NOT render a tab, if it's not necessary.

In place where you would possibly need it:
```
{ !hideFromTabs && <Tab ... /> }
```

**Review by dprokop — APPROVED** [review]
So much better now!
