### PR TITLE
Manually set query type in Tempo explore on component mount

### LINKED ISSUE #38407: Tempo: TraceID field is missing on initial page load
**What happened**:
Trace id field doesn't appear when first loading Tempo

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.0
- Data source type & version: Tempo
- OS Grafana is installed on:
- User OS & Browser: Chrome, Mac OS
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by connorlindsey**
**What this PR does / why we need it**:
Sets the queryType on QueryField component did mount because it was previously not set, thus no input was rendered.

Also, if native search is not enabled, I put Loki search as the first option and name is Search to keep it as consistent as possible with previous versions. 

**Which issue(s) this PR fixes**:
Fixes #38407

**Special notes for your reviewer**:
This feels a bit hacky. Is there a way to define the default query when defining the datasource? Maybe I need to add a default to the TempoQuery type?

### CODE REVIEW

File: public/app/plugins/datasource/tempo/QueryField.tsx [hunk 1]
```diff
@@ -62,6 +62,12 @@ class TempoQueryFieldComponent extends React.PureComponent<Props, State> {
       serviceMapDatasourceUid: serviceMapDsUid,
       serviceMapDatasource: serviceMapDs as PrometheusDatasource,
     });
+
+    // Set initial query type to ensure traceID field appears
+    this.props.onChange({
+      ...this.props.query,
+      queryType: DEFAULT_QUERY_TYPE,
```
Comment (ifrost) [inline public/app/plugins/datasource/tempo/QueryField.tsx:69]: Would it make sense to check if queryType already exists in `props.query`? Not sure if it's passed when the URL changes. Also do we still need to set DEFAULT_QUERY_TYPE below as a fallback?

Comment (connorlindsey) [reply public/app/plugins/datasource/tempo/QueryField.tsx:69]: From what I've seen, it is not passed in with the URL, but I think it's smart to check if it exists before setting it here. And yeah, in that case I can remove the default fallback below. I'll make those changes.

**Review by ifrost — APPROVED** [review]
