### PR TITLE
Azure Monitor: Fixes error using azure monitor credentials with log analytics and non-default cloud

### LINKED ISSUE #19545: Azure Monitor data source uses wrong authorization uri for Azure China
**What happened**:
When attempting to configure a data source in Grafana for Azure Monitor in the Azure China cloud, Grafana reports back two "unexpected error" messages and a message at the bottom: 

1. Azure Monitor: Cannot connect to Azure Monitor REST API. 2. Azure Log Analytics: Cannot connect to Azure Log Analytics REST API.

Upon inspection in the network tab in Chrome's developer console, I can see that the error appears to be caused by a 401 at http://{OUR GRAFANA HOSTNAME}/api/datasources/proxy/5/sameasloganalyticsazure/bf19f9f8-baac-4275-9a9b-546989f7d439/metadata

The www-authenticate header suggests that Grafana is attempting to obtain authentication from login.microsoftonline.com:

Www-Authenticate: Bearer authorization_uri="https://login.microsoftonline.com/common"

**What you expected to happen**:
I would expect Grafana to instead use the Azure China login gateway:

https://login.chinacloudapi.cn/common

**How to reproduce it (as minimally and precisely as possible)**:

Configure a Azure Monitor for the Azure China cloud (portal.azure.cn) with an Azure AD app registration that has the log analytics reader role to the subscription that contains your log analytics instance and the Data.Read permission for the Log Analytics API. Grant the permissions. Then attempt to configure the Log Analytics instances as a Data source within Grafana with the developer tab open to Network on Chrome (issue occurs in all browsers). 

**Anything else we need to know?**:

Grafana IS able to load the default subscription and workspace lists, but IS NOT able to query the Log Analytics API. Perhaps the way Grafana authenticates to get the subscription and workspace list is different than testing the Log Analytics API?

Confirmed all permissions are correct by calling the Log Analytics API myself with the same credentials via Postman.

**Environment**:
- Grafana version: 6.4.0
- Data source type & version: AzureMonitor 
- OS Grafana is installed on: Docker Image on Kubernetes/OpenShift
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: Only defaults
- Others:

### PR DESCRIPTION
**Pull request by shavonn**
Fixes #19545

Copying the credentials will allow us to get rid of the sameas route with hard-coded default cloud URL.

### CODE REVIEW

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/AnalyticsConfig.tsx [hunk 1]
```diff
@@ -92,6 +124,13 @@ export class AnalyticsConfig extends PureComponent<Props> {
           onChange={this.onAzureLogAnalyticsSameAsChange}
           {...addtlAttrs}
         />
+        {showSameAsHelpMsg && (
```
Comment (daniellee) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/AnalyticsConfig.tsx]: This was very nice UX with the re-enter dialog.

**Review by daniellee — APPROVED** [review]
LGTM - always nice to get rid of one of those extra routes

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/AnalyticsConfig.tsx (hunk 1 above)
Comment (shavonn) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/AnalyticsConfig.tsx]: Thank you :)
