### PR TITLE
Cloudwatch Logs: Fix bug where we did not return errors to user

### LINKED ISSUE #80365: Cloudwatch Logs Errors do not always get surfaced to user and instead show No Data
From https://github.com/grafana/grafana/issues/78819
> If I write a Cloudwatch Query that is invalid and try to run it, my expectation is that the error that AWS returns back to us would surface back to the Grafana user in some way. The only way I see the error is in the network tab of my browser which is not a great experience as a user, as it seems to imply it was a valid query there just was not data associated:

This is the case with Metric Queries and Logs queries. Metric queries are being fixed in https://github.com/grafana/grafana/pull/79911, so opening this for Cloudwatch Logs.

### PR DESCRIPTION
**Pull request by sarahzinger**
**What is this feature?**
Fixes a bug where errors were not being returned to users when using the cloudwatch datasource and querying for logs. I think there are a few other places where we swallow errors as well, but at least this fixes logs. 

Before: 
Screenshot 2024-05-01 at 11 00 57 AM

After: 
Screenshot 2024-05-01 at 1 48 46 PM

**Why do we need this feature?**

So that users can debug their queries

**Who is this feature for?**

Cloudwatch users

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/80365

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts [hunk 1]
```diff
@@ -342,7 +342,12 @@ export class CloudWatchLogsQueryRunner extends CloudWatchRequest {
     };
 
     return queryFn(requestParams).pipe(
-      map((response) => response.data),
+      map((response) => {
+        if (response.errors) {
+          throw new Error(response.errors[0].message);
```
Comment (kevinwcyu) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts:347]: This thrown error is showing up in the console now.

I think it would be better if we could just return `response` here and let the built in error handling show the error message. I think we also may be missing out on being able to associate errors with their respective ref ids by only taking the first error message.

We may need to change the signature of `makeLogActionRequest` to return `Observable<DataQueryResponse>`, but not sure how much work that is to modify all the places that this function is called from.

File: pkg/tsdb/cloudwatch/log_actions_test.go [hunk 2]
```diff
@@ -227,9 +230,9 @@ func TestQuery_StartQuery(t *testing.T) {
 				},
 			},
 		})
-		require.Error(t, err)
+		require.NoError(t, err)
 
-		assert.Contains(t, err.Error(), "invalid time range: start time must be before end time")
+		assert.Equal(t, "failed to execute log action with subtype: StartQuery: invalid time range: start time must be before end time", resp.Responses["A"].Error.Error())
```
Comment (kevinwcyu) [inline pkg/tsdb/cloudwatch/log_actions_test.go:235]: nit:

```suggestion
		assert.Equal(t, "failed to execute log action with subtype: StartQuery: invalid time range: start time must be before end time", resp.Responses[refID].Error.Error())
```

File: pkg/tsdb/cloudwatch/log_actions.go [hunk 3]
```diff
@@ -57,14 +57,10 @@ func (e *cloudWatchExecutor) executeLogActions(ctx context.Context, req *backend
...
-				var AWSError *AWSError
-				if errors.As(err, &AWSError) {
-					resultChan <- backend.Responses{
-						query.RefID: backend.DataResponse{Frames: data.Frames{}, Error: AWSError},
-					}
-					return nil
+				resultChan <- backend.Responses{
+					query.RefID: backend.DataResponse{Frames: data.Frames{}, Error: err},
 				}
-				return err
```
Comment (sarahzinger) [inline pkg/tsdb/cloudwatch/log_actions.go:67]: basically before we returned a raw error unless it was formatted in a certain way, now we always return an response with an error. 

I think this is probably always desirable? It lets us connect the error to the ref id, and ensures we display the error properly. That said it looks like our frontend code at least used to expect raw errors more.

File: public/app/plugins/datasource/cloudwatch/components/QueryEditor/LogsQueryEditor/LogsQueryField.tsx [hunk 4]
```diff
@@ -132,11 +131,6 @@ export const CloudWatchLogsQueryField = (props: CloudWatchLogsQueryFieldProps) =
         </div>
         {ExtraFieldElement}
       </div>
-      {showError ? (
-        <div className="query-row-break">
-          <div className="prom-query-field-info text-error">{data?.error?.message}</div>
-        </div>
-      ) : null}
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/components/QueryEditor/LogsQueryEditor/LogsQueryField.tsx:139]: this is a somewhat unrelated change but I noticed that without removing this, sometimes error messages would show twice. I'm not sure if I'm misunderstanding it's original purpose or if grafana has changed in someway since this was added to always display inline errors when ref ids are present?

File: public/app/plugins/datasource/cloudwatch/datasource.ts [hunk 5]
```diff
@@ -101,7 +105,7 @@ export class CloudWatchDatasource
 
     const dataQueryResponses: Array<Observable<DataQueryResponse>> = [];
     if (logQueries.length) {
-      dataQueryResponses.push(this.logsQueryRunner.handleLogQueries(logQueries, options, super.query.bind(this)));
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/datasource.ts:104]: when looking at the CloudwatchLogsQueryRunner it took a bit of time just to understand what calls what so I wanted to emphasize that this is a public function. It looks a little funny now in comparison to the other runners but hopefully it's helpful?

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts [hunk 6]
```diff
@@ -168,16 +114,17 @@ export class CloudWatchLogsQueryRunner extends CloudWatchRequest {
...
+      (targets) => this.makeLogActionRequest('StartQuery', targets, queryFn, options),
       startQueryRequests,
       timeoutFunc
     ).pipe(
-      mergeMap(({ frames, error }: { frames: DataFrame[]; error?: DataQueryError }) =>
-        this.getQueryResults({ frames, logQueries, timeoutFunc, error, queryFn })
-      ),
+      // once we've started the query, we need to poll for the results
+      mergeMap((startQueryResponse) => {
+        return this.getQueryResults({ logQueries, timeoutFunc, queryFn, startQueryResponse })
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts:125]: the main change here is that we now pass the whole response body from StartQuery, so that if there is an error in the response we'll be able to show it even as we poll for more responses that may not have errored.

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts [hunk 7]
```diff
@@ -197,14 +144,59 @@ export class CloudWatchLogsQueryRunner extends CloudWatchRequest {
...
+    );
+  };
+
+
   /**
    * Checks progress and polls data of a started logs query with some retry logic.
    * @param queryParams
    */
-  logsQuery(
+  pollForLogQueryResults(
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts:195]: again renaming for clarity and passing along the response

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts [hunk 8]
```diff
@@ -215,16 +207,30 @@ export class CloudWatchLogsQueryRunner extends CloudWatchRequest {
...
+    const responses = increasingInterval({ startPeriod: 100, endPeriod: 1000, step: 300 }).pipe(
       concatMap((_) => this.makeLogActionRequest('GetQueryResults', queryParams, queryFn)),
       repeat(),
       share()
     );
 
+    let errorsFromGetQuery: DataQueryError[] = [];
+    const dataFrames: Observable<DataFrame[]> = responses.pipe(
+      map((response) => {
+        // TODO: it's not entirely clear to me why but this map gets called twice, but the responses are the same
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts:219]: I am not sure yet if I'm adding this bug or if I'm just moving it around. If anyone can see what I'm missing feel free to shout it out, it definitely feels wrong/hacky atm

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts [hunk 9]
```diff
@@ -341,27 +349,7 @@ export class CloudWatchLogsQueryRunner extends CloudWatchRequest {
       })),
     };
 
-    return queryFn(requestParams).pipe(
-      map((response) => response.data),
-      catchError((err: FetchError) => {
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts:346]: I'm a little wary removing this, but I actually couldn't see what good it was doing and if it is still being run in the first place. Let me know if you think I'm missing something, but I suspect this is just legacy cruft that doesn't do much at this point

File: public/app/plugins/datasource/cloudwatch/utils/logsRetry.ts [hunk 10]
```diff
@@ -21,16 +21,16 @@ type Result = { frames: DataFrameJSON[]; error?: string };
  * @param options
  */
 export function runWithRetry(
-  queryFun: (targets: StartQueryRequest[]) => Observable<DataFrame[]>,
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/utils/logsRetry.ts:24]: before runWithRetry assumed that any errors would be thrown, not inside a response. This meant we called a query function that returned just the frames, assuming the query would throw otherwise. But now we look at the whole response and do the retry logic if there is a specific error in the response

**Comment by sarahzinger** [comment]
@kevinwcyu this needs a lot of tests but I'm curious if you wouldn't mind taking a look at this at some point. It has turned into a much bigger refactor than I intended but I think there are quite a number of bugs in the existing code (that said if you see a simpler way to fix definitely feel free to suggest, it's easy to get a bit lost in this and miss the forest for the trees!)

I tried to make this thing a bit easier to read, etc as well, and tried to simplify where I could (although I am pretty sure there's more we can do...). If this seems about right, we can go ahead and start writing/rewriting the tests for this, I just wanted to see if I could fix the structure first.

**Review by idastambuk — APPROVED** [review]

File: public/app/plugins/datasource/cloudwatch/utils/logsRetry.ts [hunk 11]
```diff
@@ -39,83 +39,56 @@ export function runWithRetry(
...
-          const errorData = splitErrorData(error);
+        next(response: DataQueryResponse) {
+          if (response.errors) {
+            const { refIdsForRequestsToRetry, errorsNotToRetry } = splitErrorsData(response.errors);
+            if (refIdsForRequestsToRetry.length > 0) {
+              if (!timeoutFunc(retries, startTime.valueOf())) {
+                // store the responses we are not retrying
+                collected.data = [
+                  ...collected.data,
+                  ...response.data,
```
Comment (kevinwcyu) [inline public/app/plugins/datasource/cloudwatch/utils/logsRetry.ts:50]: does `...response.data` include every response? E.g. if a response has an error would that be included here even if it was an error response that would be retried?

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.test.ts [hunk 12]
```diff
@@ -1,332 +1,350 @@
-import { interval, lastValueFrom, of } from 'rxjs';
+// import { interval, lastValueFrom, of } from 'rxjs';
```
[the remark this answers is not in the document]
Comment (sarahzinger) [reply public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.test.ts:1]: no sorry all the tests need to be reenabled/rewritten, just wanted to get clarity on the approach before tackling testing

File: public/app/plugins/datasource/cloudwatch/utils/logsRetry.ts (hunk 11 above)
Comment (sarahzinger) [reply public/app/plugins/datasource/cloudwatch/utils/logsRetry.ts:50]: I think if it had an error it would be in response.errors no? 

When I call this with 2 queries (a and b) and log it out, runWithRetry is called separately for each query, I'm not sure I follow in what circumstances response.data would have more than one entry in but it does come back as an array.

**Comment by sarahzinger** [comment]
hi y'all added some tests and re-requested reviews if you get a min!

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.test.ts [hunk 13]
```diff
@@ -79,254 +62,527 @@ describe('CloudWatchLogsQueryRunner', () => {
...
+
+      const queryFn = jest
+        .fn()
+        .mockReturnValueOnce(of(startQuerySuccessResponseStub))
+        .mockReturnValueOnce(of(getQuerySuccessResponseStub));
+
+      const response = runner.handleLogQueries(
+        rawLogQueriesStub,
+        options,
+        queryFn as (request: DataQueryRequest<CloudWatchQuery>) => Observable<DataQueryResponse>
```
Comment (kevinwcyu) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.test.ts:82]: You can get rid of the type casting of `queryFn` for all of the tests in this file by changing

```ts
      const queryFn = jest
        .fn()
```

to

```ts
      const queryFn = jest
        .fn<Observable<DataQueryResponse>, [DataQueryRequest<CloudWatchQuery>]>()
```

And in the response stubs change the `state` from a string to use the `LoadingState` enum from `@grafana/data`

**Review by kevinwcyu — APPROVED** [review]
🙌  nice work!
