### PR TITLE
AzureMonitor: Add a button to clear Logs credentials

### LINKED ISSUE #35858: AzureMonitor: Show a warning in Log Analytics panel if different credentials are set
**What would you like to be added**:

After https://github.com/grafana/grafana/pull/35121, Log Analytics credentials are no longer used. If the user visits the data source config page, they will see the error banner but if they don't, a panel which were using those credentials can be silently failing. We should show a warning in that scenario so the user gets notified about the change.

We should also provide an upgrade path for the data source so user can remove the banner/error once they have migrated (if necessary) their credentials.

cc/ @kostrse

### PR DESCRIPTION
**Pull request by andresmgot**
**What this PR does / why we need it**:

Allow the user to clear up errors when different credentials were specified.

Screenshot from 2021-06-29 10-48-38

**Which issue(s) this PR fixes**:

Fixes #35858

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kostrse** [comment]
We need to discuss this.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/AnalyticsConfig.tsx [hunk 1]
```diff
@@ -91,6 +91,18 @@ export const AnalyticsConfig: FunctionComponent<Props> = (props: Props) => {
...
 
+  const onClearAzLogsCreds = () => {
+    updateOptions((options) => {
+      return {
+        ...options,
+        jsonData: {
+          ...options.jsonData,
+          azureLogAnalyticsSameAs: true,
+        },
+      };
```
Comment (joshhunt) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/AnalyticsConfig.tsx:102]: Lets clean up the object properly and `delete` the deprecated fields `azureLogAnalyticsSameAs`, `logAnalyticsTenantId`, `logAnalyticsClientId`, and `logAnalyticsSubscriptionId`.

The goal here should be to get their JSON data into a close as "ideal" or "as if configured from scratch" state as possible, as they're doing a manual action.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/AnalyticsConfig.tsx [hunk 2]
```diff
@@ -113,7 +125,9 @@ export const AnalyticsConfig: FunctionComponent<Props> = (props: Props) => {
             }}
             getSubscriptions={getSubscriptions}
             disabled={true}
-          />
+          >
+            <Button onClick={onClearAzLogsCreds}>Clear Azure Monitor Logs Credentials</Button>
```
Comment (joshhunt) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/AnalyticsConfig.tsx:129]: `variant="destructive"`, and I think the "Credentials" should be lowercase.

**Review by joshhunt — APPROVED** [review]
Overall I think this is fine, but I would like to see the cleanup action actually clean up their config a bit more.

**Comment by kostrse** [comment]
LGTM

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/AnalyticsConfig.tsx (hunk 1 above)
Comment (kostrse) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/AnalyticsConfig.tsx:102]: I would move it to `credentials.ts`, I wouldn't do data manipulation in the UI component.

**Comment by kostrse** [comment]
LGTM

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/AnalyticsConfig.tsx (hunk 1 above)
Comment (andresmgot) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/AnalyticsConfig.tsx:102]: my reasoning to not delete those were in case  some emergency recovery is needed but it's probably not the case.
