### PR TITLE
Alerting: Fix Conflicting Alert Rule Response Has Wrong 'rule_uid'

### LINKED ISSUE #89755: Conflicting Alert Rule Response Has Wrong 'rule_uid'
### What happened?

We are using the [Alert Rule HTTP API](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/) and I noticed what appears to be a potential bug. We have a use case that will sometimes try to create an alert that may already exist (side note, it would be really handy make the POST just update if it exists, perhaps configurable via header). When we attempt to get the below error as expected according with the documentation:

```json
{
  "message": "[alerting.alert-rule.conflict] conflicting alert rule found [rule_uid: 'adpx066eftmv4b', title: '<MY_LAG_ALERT_NAME>', namespace_uid: '<MY_LAG_ALERT_FOLDER_UID>']: rule title under the same organisation and folder should be unique",
  "traceID": ""
}
```

Fine right? Well the `rule_uid` value is not correct. When I do a GET on that alert rule UID I get a 404 Not Found. This is further observed by resending the POST more times, I can watch the `rule_uid` change each time despite the title/body being _exactly_ the same each time. 

This is fairly inconvenient as we were hoping to use and store that `rule_uid` for another use case 

Looks like some of the code in[ question might be here ](https://github.com/grafana/grafana/blob/4651506319fa1e1d96487f4b7818ac86a77e553e/pkg/services/ngalert/models/errors.go#L15)

### What did you expect to happen?

I expect the `rule_uid` returned by the POST alert rule API on a conlicting alert to represent the conflicting alert in question

### Did this work before?

Not sure, greenfield project. 

### How do we reproduce it?

1. Create an alert with the HTTP Alert Rule API via POST request
2. Send that same exact POST request again, take note of the `rule_uid` in the response `message` value
3. Do a GET on the `rule_uid` retrieved from the previous step, in my testing I get a 404 Not Found 
4. Repeat, I can see the `rule_uid` changing each iteration of the POST despite the original alert rule still being available from the UI with the original alert rule UID (and no duplicate alerts being present)

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.4.1 (enterprise on-prem)
OS: N/A (using HTTP API)
Browser: N/A (using HTTP API)

### Grafana platform?

Other

### Datasource(s)?

N/A - this is for Alert Rule API (utilizing a Prometheus/Thanos source)

### PR DESCRIPTION
**Pull request by wasim-nihal**
**What is this feature?**

Fix to return the correct UID for the conflicting alert_rule

**Who is this feature for?**

Users of Grafana Alerting Component

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/89755

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by wasim-nihal** [comment]
@JacobsonMT, could you please have a look at this change and share your feedback?

File: pkg/services/ngalert/store/alert_rule.go [hunk 1]
```diff
@@ -172,6 +172,7 @@ func (st DBstore) GetAlertRulesGroupByRuleUID(ctx context.Context, query *ngmode
 // InsertAlertRules is a handler for creating/updating alert rules.
 // Returns the UID and ID of rules that were created in the same order as the input rules.
 func (st DBstore) InsertAlertRules(ctx context.Context, rules []ngmodels.AlertRule) ([]ngmodels.AlertRuleKeyWithId, error) {
+	logger := st.Logger.New()
```
Comment (JacobsonMT) [inline pkg/services/ngalert/store/alert_rule.go:175]: No need to create a new logger, can use `st.Logger`

File: pkg/services/ngalert/store/alert_rule.go [hunk 2]
```diff
@@ -206,6 +207,16 @@ func (st DBstore) InsertAlertRules(ctx context.Context, rules []ngmodels.AlertRu
 			for i := range newRules {
 				if _, err := sess.Insert(&newRules[i]); err != nil {
 					if st.SQLStore.GetDialect().IsUniqueConstraintViolation(err) {
+						// return the uid of conflicting alert_rule
```
Comment (JacobsonMT) [inline pkg/services/ngalert/store/alert_rule.go:210]: This doesn't technically apply to all conflicts that match `IsUniqueConstraintViolation`. If you look into `ruleConstraintViolationToErr` you'll see a (db-agnostic) attempt to determine which constraint was hit and return a clearer error message.

I would propose we move these changes into `ruleConstraintViolationToErr` under the first `if` branch by changing its signature into something like:

```go
func (st DBstore) ruleConstraintViolationToErr(sess *db.Session, rule ngmodels.AlertRule, err error) error
```

This way, the code will benefit rule `Update`s as well.

One thing to keep in mind though is (at least for updates) we should try and keep the `UID` of the new/updated rule somewhere in the error. This is so that you know which rule in a group update caused the conflict. A way to do this could be to wrap the error passed into `st.ruleConstraintViolationToErr` with something like:
```go
err = fmt.Errorf("failed to update rule [%s] %s: %w", r.New.UID, r.New.Title, err)
```

**Review by JacobsonMT — COMMENTED** [review]
Looking good so far, and thanks for the contribution!

Added a few comments but they aren't too drastic so I think we're close to merging.

File: pkg/services/ngalert/store/alert_rule.go (hunk 2 above)
Comment (wasim-nihal) [reply pkg/services/ngalert/store/alert_rule.go]: Thanks for reviewing the change @JacobsonMT ! I have made the suggested changes in the latest commit.  I have one concern with respect to the wrapping of the error to keep the new/updated rule UID (maybe I misunderstood your comment), as the error is currently not getting used in `st.ruleConstraintViolationToErr` except for checking if it contains UQE constraint violation string. Instead predefined error is used `return ngmodels.ErrAlertRuleConflict(rule, ngmodels.ErrAlertRuleUniqueConstraintViolation)`.

Is it better to pass this wrapped error message to `ngmodels.ErrAlertRuleConflict` so that this message is sent back in HTTP response ? I have created a gist implementation for the same. Could you please check https://gist.github.com/wasim-nihal/c62c0df161cfb4d49996255e53716c0f

Comment (JacobsonMT) [reply pkg/services/ngalert/store/alert_rule.go]: Ah, you're right! I didn't take into account that only the info contained in `ErrAlertRuleConflict` will be returned in the HTTP response. It's actually kind of awkward getting this to format well with how the error is currently designed, I was initially trying to avoid this but how about we make the conflict error a bit more explicit by separating the new and existing rule information. Something like:

```go
errAlertRuleConflictMsg  = "alert rule [rule_uid: '{{ .Public.New.RuleUID }}', title: '{{ .Public.New.Title }}', namespace_uid: '{{ .Public.New.NamespaceUID }}'] conflicts with existing [rule_uid: '{{ .Public.Existing.RuleUID }}', title: '{{ .Public.Existing.Title }}', namespace_uid: '{{ .Public.Existing.NamespaceUID }}']: {{ .Public.Error }}"

...

func ErrAlertRuleConflict(existingPartialRule, rule AlertRule, underlying error) error {
	return ErrAlertRuleConflictBase.Build(errutil.TemplateData{Public: map[string]any{
		"New": map[string]any{
			"RuleUID":      rule.UID,
			"Title":        rule.Title,
			"NamespaceUID": rule.NamespaceUID,
		},
		"Existing": map[string]any{
			"RuleUID":      existingPartialRule.UID,
			"Title":        existingPartialRule.Title,
			"NamespaceUID": existingPartialRule.NamespaceUID,
		},
		"Error": underlying.Error(),
	}, Error: underlying})
}
```

Then we can pass in a partial rule from `ruleConstraintViolationToErr` that contains relevant fields depending on the conditional block:

UQE_alert_rule_org_id_namespace_uid_title: `OrgID`, `NamespaceUID`, `Title`, and `UID`
UQE_alert_rule_org_id_uid: `OrgID` and `UID`
Else: Nothing

This should give us a response that is unambiguous (if a bit verbose):
```json
{
  "extra" : {
    "Error" : "rule title under the same organisation and folder should be unique",
    "Existing" : {
      "NamespaceUID" : "folder1",
      "RuleUID" : "de4ci3bjxerk0d",
      "Title" : "AlwaysFiring"
    },
    "New" : {
      "NamespaceUID" : "folder1",
      "RuleUID" : "fe3bgyheuvb40d",
      "Title" : "AlwaysFiring"
    }
  },
  "message" : "alert rule [rule_uid: 'fe3bgyheuvb40d', title: 'AlwaysFiring', namespace_uid: 'folder1'] conflicts with existing [rule_uid: 'de4ci3bjxerk0d', title: 'AlwaysFiring', namespace_uid: 'folder1']: rule title under the same organisation and folder should be unique",
  "messageId" : "alerting.alert-rule.conflict",
  "statusCode" : 409,
  "traceID" : ""
}
```

Comment (wasim-nihal) [reply pkg/services/ngalert/store/alert_rule.go]: Hi @JacobsonMT , thank you for the above suggestions!! I need some clarifications (hope you don’t mind) related below items

> Then we can pass in a partial rule from ruleConstraintViolationToErr that contains relevant fields depending on the conditional block:
> 
> UQE_alert_rule_org_id_namespace_uid_title: NamespaceUID, Title, and UID
> UQE_alert_rule_org_id_uid: UID
> Else: Nothing

For the 'else' condition, currently we do not know the what specific unique constraint is conflicting to fetch the `AlertRule` to be passed as `existingPartialRule`. In this case creating an empty AlertRule{} and passing might result in vague error response. So can we still maintain the existing method `func ErrAlertRuleConflict(rule AlertRule, underlying error) error`  mainly for this else block and have another method named (maybe with a different name) `func ErrAlertRuleConflictDetailed (existingPartialRule, rule AlertRule, underlying error) error` similar to what you have suggested above for `UQE_alert_rule_org_id_namespace_uid_title` and `UQE_alert_rule_org_id_uid`

I'd appreciate hearing your thoughts here?

Comment (JacobsonMT) [reply pkg/services/ngalert/store/alert_rule.go]: That seems like a good solution to me :rocket:

Comment (wasim-nihal) [reply pkg/services/ngalert/store/alert_rule.go]: Thanks! I have pushed the changes. Could you please review it?

File: pkg/services/ngalert/store/alert_rule.go [hunk 3]
```diff
@@ -1033,12 +1034,26 @@ func (st DBstore) RenameTimeIntervalInNotificationSettings(
...
+		}
+		if ok {
+			existingPartialAlertRule = ngmodels.AlertRule{UID: fetched_uid, Title: rule.Title, NamespaceUID: rule.NamespaceUID}
+		}
+		return ngmodels.ErrAlertRuleConflictVerbose(existingPartialAlertRule, rule, ngmodels.ErrAlertRuleUniqueConstraintViolation)
 	} else if strings.Contains(msg, "UQE_alert_rule_org_id_uid") || strings.Contains(msg, "alert_rule.org_id, alert_rule.uid") {
-		return ngmodels.ErrAlertRuleConflict(rule, errors.New("rule UID under the same organisation should be unique"))
+		// return verbose conflicting alert rule error response
+		// see: https://github.com/grafana/grafana/issues/89755
+		existingPartialAlertRule := ngmodels.AlertRule{UID: rule.UID, Title: rule.Title, NamespaceUID: rule.NamespaceUID}
```
Comment (JacobsonMT) [inline pkg/services/ngalert/store/alert_rule.go:1055]: The existing rule is not guaranteed to have the same Title or Namespace, I would just leave it as:
```suggestion
		existingPartialAlertRule := ngmodels.AlertRule{UID: rule.UID}
```

**Comment by JacobsonMT** [comment]
This looks ready to merge as soon as we get the tests passing, approved the drone run. I can help fix any broken tests if you prefer, though I don't think there will be anything too egregiously broken.

**Comment by wasim-nihal** [comment]
> This looks ready to merge as soon as we get the tests passing, approved the drone run. I can help fix any broken tests if you prefer, though I don't think there will be anything too egregiously broken.

@JacobsonMT , could you please help with triggering the Drone CI?

**Review by JacobsonMT — APPROVED** [review]
LGTM, great work :rocket: Thanks for the contribution!
