### PR TITLE
Prometheus: fix incorrect baseline in classic histogram

### LINKED ISSUE #81437: Prometheus classic histogram heatmap de-accumulation produces values < 0
you can see the baseline here is -5, not 0. this is because of imperfect float precision, and we end up with near-zero values that should actually be zero.

we should modify the de-accumulation function [1] to treat any values < 1e-9 as zero. we already hide such values by default in Heatmap panel, since they add a bunch of noise and are almost universally float precision errors.

image

image

[1] https://github.com/grafana/grafana/blob/1a1531ca5e92554d107bb1eb9df2f9fdc604d824/public/app/plugins/datasource/prometheus/result_transformer.ts#L362-L384

### PR DESCRIPTION
**Pull request by NWRichmond**
## What is this feature?

This fix ensures that when producing heatmap-format [histograms](https://grafana.com/docs/grafana/latest/fundamentals/intro-histograms), the baseline is set correctly, without being influenced by floating-point errors described in #81437.

## Who is this feature for?

Prometheus data source users who visualize classic [histograms](https://prometheus.io/docs/concepts/metric_types/#histogram) in their Grafana dashboards.

## Which issue(s) does this PR fix?

Fixes #81437

## Demonstration

Before this fix, very small (<1e-9) values appeared in heatmap-style histogram data, which made the histograms have an erroneous, negative baseline value:

before fix table view

before fix histogram view with erroneous negative baseline

With the fix, these issues are resolved:

after fix table view

after fix histogram view

## Special notes for your reviewer

- This PR makes parallel updates to `public/app/plugins/datasource/prometheus` and `packages/grafana-prometheus` (for context, see #81641).
- Please reach out to me if you'd like to reproduce the issues demonstrated in the screenshots above :)
- This PR adds tests for error handling in the `transformToHistogramOverTime` utility that's called by `transformV2` in `results_transformer.ts`. These tests are unrelated to the fix.

Please check that:
- [x] It works as expected from a user's perspective.

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/result_transformer.ts [hunk 1]
```diff
@@ -377,6 +377,10 @@ function transformToHistogramOverTime(seriesList: DataFrame[]) {
     for (let j = 0; j < topSeries.values.length; j++) {
       const bottomPoint = bottomSeries.values[j] || [0];
       topSeries.values[j] -= bottomPoint;
+
+      if (topSeries.values[j] < 1e-9) {
+        topSeries.values[j] = 0;
+      }
```
Comment (leeoniya) [inline public/app/plugins/datasource/prometheus/result_transformer.ts:383]: think we can move this condition into an additional loop below these nested loops and only run this check & adjustment for the final (lowest) series?

e.g. if we have 1k values and 20 buckets you would be running this check 20k times (and we dont really need it in the middle of the de-accum stack). if you pull this out and only run it over the lowest series, then it will always run 1k times (or however many timestamps you got) no matter how many buckets you have.

Comment (NWRichmond) [reply public/app/plugins/datasource/prometheus/result_transformer.ts:383]: Sure thing! I'll make some updates.

Comment (leeoniya) [reply public/app/plugins/datasource/prometheus/result_transformer.ts:383]: sorry, you're correct. negative buckets in the middle would also cause this, so we have to check all of them.

**Comment by leeoniya** [comment]
i pulled in some real-world response data that hopefully makes the scenario more obvious. also exported the core de-accum function so we can reduce the test noise.

nice work on this :+1:

**Review by leeoniya — APPROVED** [review]
