### PR TITLE
Auth: Duplicate API Key Name Handle With Useful HTTP Code

### LINKED ISSUE #17447: Adding an api key with an already-existing name to organization returns 500 Internal Server Error instead of useful HTTP code
**What happened**:
I sent a request for an api key with an already reserved name and I got an 500 Internal Server Error.

**What you expected to happen**:
The server would respond with another HTTP response code (eg 409 Conflict).

**How to reproduce it (as minimally and precisely as possible)**:
Create an api key and then try to create another one with the same name.

**Environment**:
- Grafana version:
Grafana v6.3.0-pre (commit: 1c3ad7867)

### PR DESCRIPTION
**Pull request by ATTron**
**What this PR does / why we need it**:
adds useful http status code & message when trying to create api key 
with same name as another existing api key
**Which issue(s) this PR fixes**:

Fixes #17447

### CODE REVIEW

**Review by papagian — CHANGES_REQUESTED** [review]
Great, thank you for your contribution!
I have some suggestions before merging it.

[Here](https://github.com/ATTron/grafana/blob/17447-Duplicate-API-Key-Name-Handling/pkg/services/sqlstore/apikey.go#L59) you could make use `dialect.IsUniqueConstraintViolation` and return your error `ErrDuplicateApiKey` just as it happens [here](https://github.com/ATTron/grafana/blob/17447-Duplicate-API-Key-Name-Handling/pkg/services/sqlstore/apikey.go#L46)

File: pkg/api/apikey.go [hunk 1]
```diff
@@ -68,7 +68,10 @@ func (hs *HTTPServer) AddAPIKey(c *models.ReqContext, cmd models.AddApiKeyComman
 		if err == models.ErrInvalidApiKeyExpiration {
 			return Error(400, err.Error(), nil)
 		}
-		return Error(500, "Failed to add API key", err)
+		if err.Error() == models.ErrDuplicateApiKey.Error() {
```
Comment (papagian) [inline pkg/api/apikey.go]: Following my suggestion for using `dialect.IsUniqueConstraintViolation` and returning the actual error this can be changed to:
`if err == models.ErrDuplicateApiKey {`

File: pkg/api/apikey.go [hunk 2]
```diff
@@ -68,7 +68,10 @@ func (hs *HTTPServer) AddAPIKey(c *models.ReqContext, cmd models.AddApiKeyComman
...
+			return Error(409, "API Key Name Must Be Unique", nil)
```
Comment (papagian) [inline pkg/api/apikey.go]: And this can be changed to:
`return Error(409, err.Error(), nil)`
just as it happens for `ErrInvalidApiKeyExpiration` just above

File: pkg/models/apikey.go [hunk 3]
```diff
@@ -7,6 +7,7 @@ import (
 
 var ErrInvalidApiKey = errors.New("Invalid API Key")
 var ErrInvalidApiKeyExpiration = errors.New("Negative value for SecondsToLive")
+var ErrDuplicateApiKey = errors.New("UNIQUE constraint failed: api_key.org_id, api_key.name")
```
Comment (papagian) [inline pkg/models/apikey.go]: Finally, this can become:
`var ErrDuplicateApiKey = errors.New("API Organisation id and Key Name Must Be Unique")`

**Comment by ATTron** [comment]
I've made the changes you've suggested. Let me know if you need anything else from me!

**Comment by papagian** [comment]
Sorry, your implementation is absolutely fine but after reconsidering it a bit I think I would like this to be implemented in a different way because usage of `dialect.IsUniqueConstraintViolation` should be generally avoided and only used in specific scenarios.

So, I would suggest you to revert the last commit and instead of handling the unique constrain error, a check for existing key with the specific organisation id and name is performed before the insert.
In that case if the organisation id and name combination is reserved the error `models.ErrDuplicateApiKey` will be returned (similarly to [this](https://github.com/grafana/grafana/blob/78ca55f3d73019f2e942e8cec2987c32274e3f5f/pkg/services/sqlstore/datasource.go#L93-L98) code).

Also, it's not obligatory but it would be great if you have some more time to invest to write a test similar to these [tests](https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/apikey_test.go#L10) that tries to insert an api key with a reserved organisation and name and gets the expected error.

Sorry again for changing my mind! Please let me know if you are you still interested to make these modifications?

**Comment by ATTron** [comment]
>  Sorry again for changing my mind! Please let me know if you are you still interested to make these modifications?

Not a problem at all! I pushed what you suggested and added testing as well.

File: pkg/api/apikey.go [hunk 4]
```diff
@@ -68,7 +68,10 @@ func (hs *HTTPServer) AddAPIKey(c *models.ReqContext, cmd models.AddApiKeyComman
 		if err == models.ErrInvalidApiKeyExpiration {
 			return Error(400, err.Error(), nil)
 		}
-		return Error(500, "Failed to add API key", err)
+		if err == models.ErrDuplicateApiKey {
+			return Error(409, err.Error(), nil)
+		}
+		return Error(500, "Failed to add API", err)
```
Comment (papagian) [inline pkg/api/apikey.go]: This error message used to "Failed to add API key"

**Review by papagian — CHANGES_REQUESTED** [review]
Great, thanks!
Almost there, just one more small change.

**Comment by ATTron** [comment]
All good to go

**Review by papagian — APPROVED** [review]

**Comment by papagian** [comment]
Thank you for contributing to Grafana!
