### PR TITLE
fix sql query in GetAdminStats.

### LINKED ISSUE #3883: SQL query error in AdminGetStats
When using MySQL.

```
2016/01/29 01:32:23 [admin.go:38 AdminGetStats()] [E] Failed to get admin stats from database: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DISTINCT `dashboard_id` )
        FROM `star`
      ) AS starred_db_count,
     ' at line 31
```

### PR DESCRIPTION
**Pull request by woodsaj**
fixes #3883

### CODE REVIEW

File: pkg/services/sqlstore/stats.go [hunk 1]
```diff
@@ -83,7 +83,7 @@ func GetAdminStats(query *m.GetAdminStatsQuery) error {
         FROM ` + dialect.Quote("playlist") + `
       ) AS playlist_count,
       (
-        SELECT COUNT (DISTINCT ` + dialect.Quote("dashboard_id") + ` )
```
Comment (utkarshcmu) [inline pkg/services/sqlstore/stats.go]: Wow, a space solved the issue. :)
