### PR TITLE
Traces: Fix for multiple $__tags in trace to metrics

### LINKED ISSUE #59618: Traces to metrics $__tags replacement only matches first use in query
**What happened**:
When using the traces to metrics workflow in the Tempo data source, mapping span attributes to metrics labels allows the use of `$__tags` to inject the relevant labels into a given trace query. See screenshot below.

image

However, it appears that only the first occurrence of `$__tags` is actually replaced within the query. This means should you write a query (such as attempting to calculate a percentage of occurrences over two different label values), the query becomes invalid as the tags are not injected. See screenshot below.

image

**What you expected to happen**:
Every occurrence of `$__tags` in a traces to metrics query should be replaced with the relevant labels mapped from span attributes.

**How to reproduce it (as minimally and precisely as possible)**:
An internal demo kit link will be posted in the relevant channel along with this issue for engineers to reproduce.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.0 (and earlier)
- Data source type & version: Tempo, inbuilt.
- OS Grafana is installed on: Kubernetes and local docker installation.
- User OS & Browser: https://www.whatsmybrowser.org/b/5EU7W
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by joey-grafana**
**What is this feature?**

Adds a fix to allow the use of multiple $__tags in trace to metrics queries.

**Why do we need this feature?**

We need to support adding $__tags in multiple places in the query.

**Who is this feature for?**

Users of our tracing datasources.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/59618

**Special notes for your reviewer**:

Screenshot 2022-12-01 at 10 55 30
Screenshot 2022-12-01 at 10 55 38

### CODE REVIEW

File: public/app/features/explore/TraceView/createSpanLink.tsx [hunk 1]
```diff
@@ -455,7 +455,7 @@ function buildMetricsQuery(query: TraceToMetricQuery, tags: Array<KeyValue<strin
     }, [] as string[]);
 
     const labelsQuery = labels?.join(', ');
-    expr = expr.replace('$__tags', labelsQuery);
```
Comment (aocenas) [inline public/app/features/explore/TraceView/createSpanLink.tsx:458]: hmm we should probably use the template service to do the replacement for us mainly so the syntax for variable interpolation is the same across grafana.

**Review by aocenas — APPROVED** [review]
Left a comment but that probably isn't blocking at this moment.
