### PR TITLE
Fixed data source selection in explore

### LINKED ISSUE #14938: Explore: After data source init error it does not recover
* Selecting a data source that returns an error in the test data source phase shows error (as expected).
* After switching to other data sources that do work (if I reload page), they only now show different error messages.

### PR DESCRIPTION
**Pull request by torkelo**
fixes #14938

* The datasourceError was not cleared on data source change success. 
* Also fixed bug where datasourceId was assigned pluginId but used as instance id, switched this to datasourceName which is what we refer to in url & panel models.

### CODE REVIEW

File: public/app/features/explore/state/reducers.ts [hunk 1]
```diff
@@ -217,6 +217,7 @@ const itemReducer = (state, action: Action): ExploreItemState => {
         supportsTable,
         datasourceLoading: false,
         datasourceMissing: false,
+        datasourceError: null,
```
Comment (torkelo) [inline public/app/features/explore/state/reducers.ts]: this is the important fix

**Comment by davkal** [comment]
LGTM
