### PR TITLE
Search: Add substring matcher, to bring back the old dashboard search behavior.

### LINKED ISSUE #54387: search: poor match on dashboard name with multiple words
When searching for dashboard titles, partial matching on multiple words does not find obvious matches. The whole second word has to be typed before the search returns a good match.

**What happened**:

I am searching for a dashboard with multiple words in the dashboard title and I  have to type the whole second word before I get a match.

An example from play.grafana.com. I am looking for the dashboard with the title [Prometheus 2.0 Stats](https://play.grafana.org/d/UDdpyzz7z/prometheus-2-0-stats?orgId=1&refresh=1m&search=open)

1. Type the word `Prometheus`. The result does not contain the dashboard I am looking for. Not that strange - there are lots of dashboards with Prometheus in the title.
image

2. Start typing a second word in the title (either `2.0` or `stats`). No match until the whole word is typed. Here I have typed `2.` and still no match. The top result doesn't even contain the word `prometheus`.
image

Here I have typed `prometheus stat`and no match either:

image

A gif showing the search experience: Search-multiple-words

**What you expected to happen**:

I expect the search to find obvious partial matches. In my example above there is only one other dashboard with the words `prometheus` and `2` in the title, why are they not the top 2 matches when I type `prometheus 2`?

**How to reproduce it (as minimally and precisely as possible)**:

Type `prometheus 2` or `prometheus stat` on the [play.grafana.org ](https://play.grafana.org/) site and see if you can find the dashboard with title `Prometheus 2.0 Stats`. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.x

Can see the same issue on our internal staging Grafana too which is running latest version of the main branch.

### PR DESCRIPTION
**Pull request by ArturWierzbicki**
Replaces all custom matchers with a single substring matcher to bring back the old dashboard search behavior

fixes https://github.com/grafana/grafana/issues/54387
fixes https://github.com/grafana/support-escalations/issues/3757

### CODE REVIEW

File: pkg/services/searchV2/bluge.go [hunk 1]
```diff
@@ -435,22 +435,10 @@ func doSearchQuery(
 			fullQuery.AddShould(bluge.NewMatchAllQuery())
 		}
 	} else {
-		// The actual se
-		bq := bluge.NewBooleanQuery().
-			AddShould(bluge.NewMatchQuery(q.Query).SetField(documentFieldName).SetBoost(6)).
-			AddShould(bluge.NewMatchQuery(q.Query).SetField(documentFieldDescription).SetBoost(3)).
-			AddShould(bluge.NewMatchQuery(q.Query).
```
Comment (ryantxu) [inline pkg/services/searchV2/bluge.go:442]: ugg -- I am torn here.   This is a pretty big change that gets rid of everything nice about bluge :(

Will this behave as expected if we put both the substring and ngram query in should clauses?

Since we are not using `documentFieldDescription` we should probably remove it from the index also

**Comment by torkelo** [comment]
Been reading https://docs.google.com/document/d/1PcdfO7IBnd2nXXsSFUf4CjUROw-SF78uzn8HbCkjRzE/edit#  and not reverting to full wildcard searches is a great idea. Feels like it will make many other scenarios worse? 

The escallation of missing hits on thisisatest when searching for test seem ok me (Same is true for Github issue search). 
https://github.com/grafana/support-escalations/issues/3757

But daniels case of searching for `Prometheus 2.` and not getting a hit on `Prometheus 2.0 Stats` looks different. If I understand correctly "Prometheus 2.0 Stats` is tokenized to `Prometheus` `2` `0` `Stats` ,  so should search query should match two tokens and that dashboards should be ranked highest.

File: pkg/services/searchV2/bluge.go (hunk 1 above)
Comment (ArturWierzbicki) [reply pkg/services/searchV2/bluge.go:442]: Yup :( It will behave correctly, I just removed it all for the (tiny) perf increase and consistency. Brought it back, and removed the description field from the index

**Comment by ArturWierzbicki** [comment]
> But daniels case of searching for Prometheus 2. and not getting a hit on Prometheus 2.0 Stats looks different. If I understand correctly Prometheus 2.0 Stats is tokenized to Prometheus 2 0 Stats , so should search query should match two tokens and that dashboards should be ranked highest.

That case and @ryantxu's nudging is what led me towards writing that doc. The `name` document in the index is analyzed using bluge's [standard analyzer](https://github.com/blugelabs/bluge/blob/f837c36803195492cbb3859d5a8331bbef25195f/analysis/analyzer/standard.go#L23) which tokenizes `prometheus 2.0 stats` into `[prometheus, 2.0, stats]`, which makes sense for prioritizing exact term matches. 

Now, the `Prometheus 2.0 Stats` dashboard shows up in the results on play.grafana.org, but its pretty down there, because we matched it only on the first term (prometheus)

image


the input, `Prometheus 2.` is tokenized into `[prometheus, 2]`, so `2 - Stats` is at the top because of an exact match on `2`, AND some combination of 
- `2`'s rarity ([BM25](https://en.wikipedia.org/wiki/Okapi_BM25)'s IDF), 
- short length of the document overall (BM25's `|D|`),
- fuzzy query match

This can be fixed (my best try is here https://github.com/grafana/grafana/pull/54478/files), but it requires some tradeoffs.  

The "wildcard search" has been with grafana forever, and `panelTitleSearch` takes it away without good comms which _might not_ be the best experience - I know I couldn't live without it in my IDE! 

This isn't supposed to be the end state, its a temporary solution allowing us to broadly enable `panelTitleSearch` without negatively impacting the users. Enabling it has some benefits beyond the basic dashboard name search (gaining ops experience with bluge, panel title search feature itself!, using the search backend component in other services, etc), so I think its worth doing that while [we collect more data on how to tune the search algorithm](https://github.com/grafana/grafana/issues/54659).

Let me know if that makes sense - thats my reasoning, but I dont hold a super strong opinion on this.

**Review by ryantxu — APPROVED** [review]
I think this is a very reasonable next step.
🌮

**Review by torkelo — APPROVED** [review]
Ok makes sense! Was just worried that we took a step backwards because of fear of changing any current behavior. But if you and ryan think this is a good step forward to get more adoption of new search now and something we can tweak going forward sounds good !
