### PR TITLE
Provide correct field scoped vars for data links interpolation

### LINKED ISSUE #25106: 7.0 Stat panel: ${__field.labels.*} not evaluated in data links
I have some dashboards that use data links in Stats panels that go to other dashboards for drill-down. In order to pass the correct variables to the linked dashboards I was using things like ${__field.labels.instance} in the data link URL. This worked fine in 6.7, but in 7.0 these are not being evaluated.

**What happened**:
After upgrading to 7.0 the URL passed to the linked dashboard contains "${__field.labels.instance}".

**What you expected to happen**:
I expected it to contain the value of the "instance" label of the data in the stat panel.

**How to reproduce it (as minimally and precisely as possible)**:
Add a data link to a Stat panel that includes variables set via the above method:
<URL>?orgId=1&var-instance=${__field.labels.instance}&var-ifName=${__field.labels.ifName}

Set up the dashboard in the link to handle the passed variables.

Use the data link and see what is passed to the linked dashboard.

**Anything else we need to know?**:
These ${__field.label.*} variables still show up in the popup for the URL editor (^space) and are correctly syntax hi lighted so this doesn't look intentional.

Also ${__url_time_range} is working as expected in Stat panel data links in 7.0.

**Environment**:
- Grafana version:
7.0
- Data source type & version:
Prometheus 2.x
- OS Grafana is installed on:
Ubuntu 18.04
- User OS & Browser:
macOS 10.15.4
Safari 13..1
- Grafana plugins:
Stat panel
- Others:

### PR DESCRIPTION
**Pull request by dprokop**
Fixes #25106

In https://github.com/grafana/grafana/pull/24024 (https://github.com/grafana/grafana/commit/5dca59f72048f3928d699254763d3dfbe586f12d#diff-d94589eab80f69c7edf5759634cd6aeeR111) `labels` field scoped var was renamed to `label`, while `labels` started to represent formatted labels. I don't know if this was intentional or just by accident, but it broke labels interpolation in data links. But it was definitely a breaking change.

In this PR I'm bringing back the `labels` scoped var to contain a dictionary with field labels. The formated labels scoped var is now named `formattedLabels`. I couldn't find the formatted labels to be used anywhere. @torkelo @ryantxu maybe you recall if this scoped var is used anywhere?

Another approach I have considered was to implement migration for the data links to update `__field.labels` to `__field.label`, but I found this as an unnecessarily complex solution. 

I also feel like the `formattedLabels` scoped var is more verbose than `labels`.

### CODE REVIEW

File: packages/grafana-data/src/field/fieldOverrides.ts [hunk 1]
```diff
@@ -358,7 +358,7 @@ export const getLinksSupplier = (
   }
   const timeRangeUrl = locationUtil.getTimeRangeUrlParams();
   const { timeField } = getTimeField(frame);
-
+  debugger;
```
Comment (dprokop) [inline packages/grafana-data/src/field/fieldOverrides.ts:361]:
```suggestion
```

File: packages/grafana-data/src/field/fieldOverrides.ts [hunk 2]
```diff
@@ -358,7 +358,6 @@ export const getLinksSupplier = (
   }
   const timeRangeUrl = locationUtil.getTimeRangeUrlParams();
   const { timeField } = getTimeField(frame);
```
Comment (dprokop) [inline packages/grafana-data/src/field/fieldOverrides.ts:360]:
```suggestion
  const { timeField } = getTimeField(frame);
  
```

**Review by torkelo — APPROVED** [review]
This looks good! Do not think the labels (formatted) is used anywhere, was added during 7.0 to use in title (displayName) expressions, so I think it’s ok to change to restore labels to what is used to be

**Comment by bergquist** [comment]
I was just pinged about this on public slack as it breaks the setup for people who run master (folks who run master are extremely valuable to us since they give us fast feedback). Please mark this as a breaking change or ideally support both during a transition period. 

cheers 

The cherry-pick label is not needed if this will be released in 7.1 :)
