### PR TITLE
Editor: Fixes issue where only entire lines were being copied

### LINKED ISSUE #18768: Explore: can't copy/paste part of a query
**What happened**:
I copied part of a query:

image

and pasted but it the whole line was copied.

**What you expected to happen**:

 I expected to be able to copy part of query and to be able to paste it.

**How to reproduce it (as minimally and precisely as possible)**:
In latest Chrome or Firefox:

1. Write some text in the query input
2. Select some of it
3. Copy either with a keyboard shortcut or by right-clicking and choosing Copy
4. Paste the text in the clipboard anywhere

**Environment**:
- Grafana version: latest master
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu 16.04 
- User OS & Browser: Ubuntu 16.04 and Chrome/Firefox
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Fixes an issue where only entire lines were being copied, so now copying works as expected.

**Which issue(s) this PR fixes**:
Closes #18768

### CODE REVIEW

File: public/app/features/explore/QueryField.tsx [hunk 1]
```diff
@@ -1,6 +1,7 @@
 import _ from 'lodash';
 import React, { Context } from 'react';
 import ReactDOM from 'react-dom';
+import { List } from 'immutable';
```
Comment (davkal) [inline public/app/features/explore/QueryField.tsx]: Is there a way to do this without anything from `immutable`. I know it's an explicit dependency now (because of slate), but it's not used anywhere else in the project. Not a blocker.

File: public/app/features/explore/QueryField.tsx [hunk 2]
```diff
@@ -622,9 +623,33 @@ export class QueryField extends React.PureComponent<QueryFieldProps, QueryFieldS
 
   handleCopy = (event: ClipboardEvent, change: Editor) => {
     event.preventDefault();
-    const selectedBlocks = change.value.document.getBlocksAtRange(change.value.selection);
-    event.clipboardData.setData('Text', selectedBlocks.map((block: Block) => block.text).join('\n'));
+    const selectedBlocks: List<Block> = change.value.document.getBlocksAtRange(change.value.selection);
```
Comment (davkal) [inline public/app/features/explore/QueryField.tsx]: Can we have a test for the meat of the function, i.e., the part that does not use `event`? Might have to extract that part.

**Review by davkal — COMMENTED** [review]
Works well. 

Minor issues:

- import by otherwise unused lib
- no test for bug fix

File: public/app/features/explore/QueryField.tsx (hunk 2 above)
Comment (kaydelaney) [reply public/app/features/explore/QueryField.tsx]: Sure, no problem

**Review by davkal — APPROVED** [review]
Happy with the tests 🎉
