### PR TITLE
[Influxb] Support for multible measurement results in showtag values

### LINKED ISSUE #4726: [Bug] [regression] grafana2 -> 3 influx 0.9 -> 0.11 templating doesn't show all the values
* What grafana version are you using? 2.6.0 -> 3.0.0-beta2
* What datasource are you using? influxdb 0.9 -> 0.11.1

We are using grafana for dashboarding an hbase and hdfs database, and using templating to make sure we can differentiate between the various instances of the hbase database.

As a distributed system, it's useful to see metrics for the cluster as a whole (rather than individual servers within it), so we template with:

```SHOW TAG VALUES WITH KEY = cluster```

In influx 0.9 in the CLI (and similarly in the JSON), this results in:
```
> SHOW TAG VALUES WITH KEY = cluster
name: clusterTagValues
----------------------
cluster
hadoop-dr
hadoop-live
hbase-dr
hbase-live
live
live-hadoop
live-hbase
live_resources0
live_zk
```

However in Influx 0.11.1 in the CLI (and again similarly in the JSON), this results in a set split by table:
```
> SHOW TAG VALUES WITH KEY = cluster
name: =regionserver
-------------------
key	value
cluster	stage_resources0


name: _stats
------------
key	value
cluster	stage_resources0
[...]
name: net
---------
key	value
cluster	stage_mentions0
cluster	stage_resources0
cluster	zk_test
[...]
```

Grafana's behaviour in this situation is just to take the tags from the first tabular result returned by influx, where, without a specific measurement (table) and because there is no one measurement that covers all the results, in order to see other clusters, I resort to typing them in. Obviously the behaviour I suggest here and that I'd expect (principle of least surprise etc) is the union of these results across all the tables, generating something closer to the list that we had on our old installation.

I did have a look at the code, but trying to dip in when I'm very unclear about how it's structured turned out to not be as trivial as I'd hoped.

AFAICT it's either possible to fix it: https://github.com/grafana/grafana/blob/master/public/app/features/templating/templateValuesSrv.js#L228 or presumably better: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/datasource.ts#L120

I may try and have a go at fixing it on Monday, as it's a work thing, but if this is a trivial-ish fix, then your (probably better) fix would be much appreciated by me. :-)

### PR DESCRIPTION
**Pull request by bergquist**
closes #4726

kinda fugly code but it solves the problem :)

### CODE REVIEW

File: public/app/plugins/datasource/influxdb/response_parser.ts [hunk 1]
```diff
@@ -12,17 +12,27 @@ export default class ResponseParser {
...
-        return { text: value };
-      }
+      });
     });
+
+    return res;
+  }
+}
+
+function addUnique(arr, value) {
```
Comment (torkelo) [inline public/app/plugins/datasource/influxdb/response_parser.ts]: use an javascript hash instead, should be way faster than doing an array check every add,  then after the loop turn hash into array. by hash I mean javascript object

File: public/app/plugins/datasource/influxdb/response_parser.ts [hunk 2]
```diff
@@ -12,17 +12,27 @@ export default class ResponseParser {
...
-    var series = influxResults.series[0];
-    return _.map(series.values, (value) => {
-      if (_.isArray(value)) {
-        if (query.toLowerCase().indexOf('show tag values') >= 0) {
-          return { text: (value[1] || value[0]) };
+    var res = [];
+    _.each(influxResults.series, (serie) => {
+      _.each(serie.values, (value) => {
+        if (_.isArray(value)) {
+          if (query.toLowerCase().indexOf('show tag values') >= 0) {
```
Comment (torkelo) [inline public/app/plugins/datasource/influxdb/response_parser.ts]: Minor performance thing here, try to have this check outside the loop once, instead of on every loop

**Comment by mb-m** [comment]
OK, seeing this, I realise even your "fugly" code is way better than anything else I could have done! :-) Thank you!!!

**Comment by bergquist** [comment]
@torkelo good points! thanks for reviewing :)
