### PR TITLE
Annotation Panel: Fix annotation with end time not being centered

### LINKED ISSUE #38422: Annotation Panel: Annotation not correctly centered when start and and time are different
**What happened**:

When clicking on an annotation in the annotation list panel, sometimes the annotation is not correctly centered and time offset are wrongly applied.

_In fact it is only the case when the annotation is created over a time range and it's time and timeEnd properties are different_

**What you expected to happen**:

The annotation should correctly centered even if it is a time range annotation.
The time offset should apply to the timeEnd property if available. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard with a sample graph and the annotation panel
2. Add one single time annotation and one time range annotation (over 1 hour for exemple)
3. Click on the single annotation: it is centered 
image
4. Click on the time range annotation: it is not correctly displayed (centered on time start but not showing the end)
image
it should be displayed as followed:
image

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: None
- OS Grafana is installed on: Mac OSX
- User OS & Browser: Firefox 90
- Grafana plugins: None
- Others: N.A

### PR DESCRIPTION
**Pull request by Willena**
**What this PR does / why we need it**:

This fixes time range annotation not being correctly centered when clicking the item in the list. 
The time property was always used even if the timeEnd propety was defined to another date. While this is true for annotation on a single time range, it can't be applied to annotation with the timeEnd property. 

The fix uses the time property if the timeEnd property is not defined.

Before:
image

After:

image

**Which issue(s) this PR fixes**:

Fixes #38422

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/panel/annolist/AnnoListPanel.tsx [hunk 1]
```diff
@@ -140,7 +140,7 @@ export class AnnoListPanel extends PureComponent<Props, State> {
 
     const params: any = {
       from: this._timeOffset(anno.time, options.navigateBefore, true),
-      to: this._timeOffset(anno.time, options.navigateAfter, false),
+      to: this._timeOffset(anno.timeEnd ? anno.timeEnd : anno.time, options.navigateAfter, false),
```
Comment (ryantxu) [inline public/app/plugins/panel/annolist/AnnoListPanel.tsx:143]:
```suggestion
      to: this._timeOffset(anno.timeEnd ?? anno.time, options.navigateAfter, false),
```

Looks good!  Thank you

**Review by ashharrison90 — APPROVED** [review]
looks good to me. thanks for your contribution! 🙌
