### PR TITLE
Explore: No logs should show an empty graph

### LINKED ISSUE #19125: Explore: No logs should show an empty graph
**What happened**:
In Explore, if there are no logs for selected time interval, the graph section is blank. Graph layout without data is not displayed. 
image

**What you expected to happen**:
See empty graph. 

**How to reproduce it (as minimally and precisely as possible)**:
 - Go to Explore and choose Loki as a data source
 - Run query e.g. {job="varlogs"}
 - Zoom in to graph until you find a time interval with no logs

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
In Explore, if there are no logs for selected time interval, the section where should be graph layout is empty. Graph layout is not displayed. This PR fixes this issue. So if there are no logs, you see an empty graph with *No data point* message.  
image

**Which issue(s) this PR fixes**:
Fixes #19125

### CODE REVIEW

File: packages/grafana-ui/src/components/Graph/Graph.tsx [hunk 1]
```diff
@@ -79,22 +79,26 @@ export class Graph extends PureComponent<GraphProps> {
...
-          tickDecimals,
-        };
-      }),
-      yAxisConfig => yAxisConfig.index
-    );
+
+    const noDataToBeDisplayed = series.length === 0;
+    const yaxes = noDataToBeDisplayed
+      ? [{ show: true, min: -1, max: 1 }]
+      : uniqBy(
```
Comment (torkelo) [inline packages/grafana-ui/src/components/Graph/Graph.tsx]: to make this more readable would break this out into functions so we can get rid of the multi-line ? expression.

First a function getYAxes(...) 

first in that function we could do
if (series.length === 0) {
return [{ show: true, min: -1, max: 1 }]
}

File: packages/grafana-ui/src/components/Graph/Graph.tsx [hunk 2]
```diff
@@ -157,10 +162,12 @@ export class Graph extends PureComponent<GraphProps> {
   }
 
   render() {
-    const { height } = this.props;
+    const { height, series } = this.props;
+    const noDataToBeDisplayed = series.length === 0;
     return (
       <div className="graph-panel">
         <div className="graph-panel__chart" ref={e => (this.element = e)} style={{ height }} />
+        {noDataToBeDisplayed && <div className="datapoints-warning flot-temp-elem">No data points</div>}
```
Comment (torkelo) [inline packages/grafana-ui/src/components/Graph/Graph.tsx]: the flot-temp-elem class should not be needed (only for elements inside the flot element)

**Review by torkelo — COMMENTED** [review]
Looks good! Some refactoring tips to improve code readability

File: packages/grafana-ui/src/components/Graph/Graph.tsx (hunk 2 above)
Comment (ivanahuckova) [reply packages/grafana-ui/src/components/Graph/Graph.tsx]: fixed 🙂

File: packages/grafana-ui/src/components/Graph/Graph.tsx (hunk 1 above)
Comment (ivanahuckova) [reply packages/grafana-ui/src/components/Graph/Graph.tsx]: Refactored. Thanks for feedback @torkelo! 🔝

**Review by torkelo — APPROVED** [review]
