### PR TITLE
Geomap: Fix tooltip display

### LINKED ISSUE #54094: Geomap Tooltip can't overflow beyond panel
image

**What happened**:
After adding marker to the Geomap Panel and hovering over marker Tooltip near map border is cut off and is blocked from overflowing.

**What you expected to happen**:
In the past the Geomap tooltips was able to overflow panel. 

**How to reproduce it (as minimally and precisely as possible)**:
1. create Geomap panel
2. add marker to the map
3. hover over marker that is close enough to panel border.

**Anything else we need to know?**:
Issue is probably similar for other panels. I have created dropdown navigation in text panel and it also stopped working as expected. It was able to overflow beyond text panel but from version 9.03 up dropdown is stopped at panel border.

**Environment**:
- Grafana version: 9.03-9.1
- Data source type & version: Elasticsearch (and none for text panel)
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10 Brave/Chrome

### PR DESCRIPTION
**Pull request by adela-almasan**
*Before*

https://user-images.githubusercontent.com/88068998/186712792-f5e5467e-737b-434e-a468-dff3e1a2ba7d.mov

*After*

https://user-images.githubusercontent.com/88068998/186712998-75da26e6-5742-4d64-9c5d-ae182d2e1c9b.mov

Fixes #54094

Caused by #52167
Reverts #53274

### CODE REVIEW

File: public/app/plugins/panel/geomap/globalStyles.ts [hunk 1]
```diff
@@ -78,5 +78,8 @@ export function getGlobalStyles(theme: GrafanaTheme2) {
     .ol-attribution:not(.ol-collapsed) {
       background-color: ${theme.colors.background.secondary}; // rgba(255,255,255,0.8);
     }
+    .panel-content {
```
Comment (ryantxu) [inline public/app/plugins/panel/geomap/globalStyles.ts:81]: 🤔 I think this gets applied to ALL panels, not just the geomap one.

Comment (ryantxu) [reply public/app/plugins/panel/geomap/globalStyles.ts:81]: Yes -- it is equivalent to dynamically changing:
https://github.com/grafana/grafana/blob/dashboard-list-panel/public/sass/pages/_dashboard.scss#L45

after the geomap panel loads

Comment (adela-almasan) [reply public/app/plugins/panel/geomap/globalStyles.ts:81]: ugh, I thought it's applied where it's being used.. 👀

Comment (nmarrs) [reply public/app/plugins/panel/geomap/globalStyles.ts:81]: This may or may not be the worst thing given in original issue user also mentions other cases where overflow being disabled causing broken functionality 

See https://github.com/grafana/grafana/issues/54094 
```
Anything else we need to know?:
Issue is probably similar for other panels. 
I have created dropdown navigation in text panel and it also stopped working as expected. 
It was able to overflow beyond text panel but from version 9.03 up dropdown is stopped at panel border.
```

Comment (adela-almasan) [reply public/app/plugins/panel/geomap/globalStyles.ts:81]: Yes, I saw it's being referenced in other issues too, but not sure why it was needed in the first place.. ie - what issues the revert is going to cause

File: public/app/plugins/panel/geomap/GeomapTooltip.tsx [hunk 2]
```diff
@@ -19,14 +19,14 @@ export const GeomapTooltip = ({ ttip, onClose, isOpen }: Props) => {
   const { dialogProps } = useDialog({}, ref);
 
   return (
-    <>
+    <Portal>
```
Comment (ryantxu) [inline public/app/plugins/panel/geomap/GeomapTooltip.tsx:22]: any sense if we should add portal all the time, or only when the tooltip is in use?

If adding it conditionally is not worse, we should do that since it will have less *stuff* in the real DOM unless it is actually used

Comment (adela-almasan) [reply public/app/plugins/panel/geomap/GeomapTooltip.tsx]: You're right, updated!

**Review by nmarrs — APPROVED** [review]
Tested locally and works! 🎉

**Comment by nmarrs** [comment]
Added `Add to changelog` tag here so our bug fixes have better visibility in releases - see [here](https://github.com/grafana/support-escalations/issues/3664) for context
