### PR TITLE
Loki/Prometheus: updates addLabelToQuery method to prevent it from adding labels outside of selector when using Loki datasource

### LINKED ISSUE #25010: Filtering logs using Loki in Explore section fails if there is a text filter with a dash
**What happened**:
While exploring logs from Loki in Grafana's Explore we've noticed that If you have a text filter containing a dash (`-`) it breaks the query when you filter by clicking a value in a log entry.

For example if you perform this query `{namespace="foo",container="bar"} != "foo-bar"` and then go to a log entry and filter by any field it performs this query `{namespace="foo",container="bar",field_name="value"} != "foo{field_name="value"}-bar"` and gives an error.

On the other hand, if the filter doesn't contain a dash (`-`) it works as expected: `{namespace="foo",container="bar"} != "foobar"` -> `{namespace="foo",container="bar",field_name="value"} != "foobar"`

**What you expected to happen**:
I expected Grafana to perform this query `{namespace="foo",container="bar",field_name="value"} != "foo-bar"`

**How to reproduce it (as minimally and precisely as possible)**:
1.- Perform any Loki log search that contains a text filter with a dash (`-`)
  Example: `{field="value"} != "foo-bar"`
2.- Go to any log entry, expand details and click any of its value to filter
3.- It fails

**Anything else we need to know?**:
GrafanaLokiBug-Small

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Loki, built-in version
- OS Grafana is installed on: Official docker image
- User OS & Browser: macOS 10.15 & Google Chrome 83
- Grafana plugins: None
- Others: N/A

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Fixes `addLabelToQuery` method to prevent it from adding labels outside of selector when using Loki datasource.

**Which issue(s) this PR fixes**:

Fixes #25010

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/add_label_to_query.ts [hunk 1]
```diff
@@ -35,7 +40,13 @@ export function addLabelToQuery(query: string, key: string, value: string, opera
     const isColonBounded = word.endsWith(':');
 
     previousWord = word;
-    if (!insideSelector && !isColonBounded && !previousWordIsKeyWord && builtInWords.indexOf(word) === -1) {
+    if (
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/prometheus/add_label_to_query.ts:43]: Could you add comment explaining why is this needed/what is happening here? That would be awesome!

**Review by ivanahuckova — COMMENTED** [review]
Quick check - isn't this going to break some of the Loki metrics queries when we filter for/out labels in table?

File: public/app/plugins/datasource/prometheus/add_label_to_query.ts (hunk 1 above)
Comment (Estrax) [reply public/app/plugins/datasource/prometheus/add_label_to_query.ts:43]: @ivanahuckova sure - it basically prevents from appending the filter for/out label to anything outside of the selector when using Loki datasource.

Right now, when you add a filter for/out a sentence with a dash character inside, e.g. `{selector} |= "foo-bar"`, adding a label from the table is going to add an empty selector to `foo` as well, and then fill it with the label - while it shouldn't.

**Review by ivanahuckova — COMMENTED** [review]
This comment/question didn't make sense 🙈. Loki don't have metrics.

**Comment by Estrax** [comment]
@ivanahuckova metrics queries with Loki should work properly.

File: public/app/plugins/datasource/prometheus/add_label_to_query.ts (hunk 1 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/prometheus/add_label_to_query.ts:47]: What about, instead of using `isLokiDatasource` here, we would use something like `hasNoMetrics` ? As `isLokiDatasource`. Also, it would remove Loki-specific code?

Comment (Estrax) [reply public/app/plugins/datasource/prometheus/add_label_to_query.ts:47]: @ivanahuckova good idea! Renamed it from `isLokiDatasource` to `hasNoMetrics`.

**Review by ivanahuckova — APPROVED** [review]
LGTM! Just a tiny nitpick/personal preference in `public/app/plugins/datasource/loki/datasource.ts` in `expression = addLabelToQuery(expression, action.key, action.value, undefined, true);` instead if `undefined` I would use `=` as it is basically the same, but more clear/readable.
