### PR TITLE
bug: adjust table footer height calculations

### LINKED ISSUE #62410: Transparent footer background when header is toggled off, then footer is toggled on
**What happened**:
In the TablePanel component, when editing the settings, and `Show table header` is enabled and `Show table footer` is disabled, when you toggle `Show table header` to disabled, then toggle `Show table footer` to enabled, the footer data shows up with a transparent footer background.

**What you expected to happen**:
An opaque footer background when the above is done.

**How to reproduce it (as minimally and precisely as possible)**:
- Open a Table panel, populate it with data
- Toggle `Show table header` to disabled
- Toggle `Show table footer` to enabled

**Anything else we need to know?**:
Nada

**Environment**:
- Grafana version: 9.4.0-pre
- Data source type & version: gdev-testdata
- OS Grafana is installed on: macOS
- User OS & Browser: Brave
- Grafana plugins:
- Others:

https://user-images.githubusercontent.com/46619047/215224578-5ed821e8-994b-4a74-bb64-e78ab7b733d0.mov

### PR DESCRIPTION
**Pull request by baldm0mma**
**What is this feature?**

Table height was being incorrectly calculated, and therefore the footer was rendering over table rows. This fixes that.

**Why do we need this feature?**

Bugs are bad, m'kay?

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:
Fixes #62410

**Special notes for your reviewer**:
Screenshot 2023-02-01 at 4 32 30 PM (2)
What it was ^^^

Screenshot 2023-02-01 at 4 31 54 PM (2)
The fix ^^^

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/Table.tsx [hunk 1]
```diff
@@ -63,7 +64,7 @@ export const Table = memo((props: Props) => {
   const [footerItems, setFooterItems] = useState<FooterItem[] | undefined>(footerValues);
 
   const footerHeight = useMemo(() => {
-    const EXTENDED_ROW_HEIGHT = headerHeight;
```
Comment (baldm0mma) [inline packages/grafana-ui/src/components/Table/Table.tsx:66]: This calculation of the footer height was being based on the headerHeight, which is fine, if the headers are being rendered/toggled on. However, if they aren't, then the value of the return of this function will always be 0, and therefore the footer values will render over table row values.

**Review by mdvictor — APPROVED** [review]
lgtm
