### PR TITLE
Dashboard: Fix iteration property change triggering unsaved changes warning 

### LINKED ISSUE #3001: Please reopen #2940
Hi
I have answered to the issue #2940
https://github.com/grafana/grafana/issues/2940

Can you reopen it?

Thanks,

### PR DESCRIPTION
**Pull request by torkelo**
Removes dashboard.iteration property.

This property should not be persisted, but looking at the code I don't think this serves any purpose anymore. 

iteration property was used in the repeating panel/rows code, has very old origins (before react), was still part of the code when we re-did this for the react grid. Think it was used to re-use instances between iterations. But now it looks like we always remove all repeated rows/panels before starting a new repeat iteration so this looks like it has lost all purpose

### CODE REVIEW

File: public/app/features/dashboard/state/DashboardModel.ts [hunk 1]
```diff
@@ -507,13 +506,10 @@ export class DashboardModel implements TimeModel {
       return;
     }
 
-    this.iteration = (this.iteration || new Date().getTime()) + 1;
     // cleanup scopedVars
     deleteScopeVars(this.panels);
 
-    const panelsToRemove = this.panels.filter(
-      (p) => (!p.repeat || p.repeatedByRow) && p.repeatPanelId && p.repeatIteration !== this.iteration
```
Comment (torkelo) [inline public/app/features/dashboard/state/DashboardModel.ts:515]: I don't see any scenario where `p.repeatIteration !== this.iteration` would ever be false, all my testing it's always true

**Review by ryantxu — APPROVED** [review]
I can't find anywhere this is used, and all manual testing seems the same.
