### PR TITLE
Alerting: Apply Custom Headers to datasource queries.

### LINKED ISSUE #44460: Alerting: custom headers not being sent from alert queries
**What happened**:

Custom headers not being sent for queries which invoked from alerts (e.g. **it affects Prometheus datasource**).

**What you expected to happen**:

When user configured custom headers for a datasource which supports it (e.g. Prometheus), the headers should be consistently sent from both dashboard and from alerts.

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure a Prometheus datasource and point it to a RequestBin URL.
2. Configure a custom header.
3. Configure an alert for the datasource.

Observe presence/absence of the configured header depending on whether the request was originated from dashboard or alert.

**Anything else we need to know?**:

Queries from dashboard and alerts have different code paths to call `pluginsClient.QueryData`.

query from a dashboard:
[pkg/services/query/query.go](https://github.com/grafana/grafana/blob/9eb82f9fff6635176ea6816c8c153abbece6b6c6/pkg/services/query/query.go#L157)

query from alerts:
[pkg/tsdb/legacydata/service/service.go](https://github.com/grafana/grafana/blob/baab021fec6b2cab7e54ed574af2a0662752ce5b/pkg/tsdb/legacydata/service/service.go#L96)

Query from dashboard has code that collects custom headers from the datasource JsonData and sets them into query request ([here](https://github.com/grafana/grafana/blob/9eb82f9fff6635176ea6816c8c153abbece6b6c6/pkg/services/query/query.go#L149-L151)):
```go
for k, v := range customHeaders(ds.JsonData, instanceSettings.DecryptedSecureJSONData) {
    req.Headers[k] = v
}
```

Alerting doesn't have such code.
As result custom headers are not being sent from alerts.

**Environment**:
- Grafana version: 8.3, main
- Data source type & version: Prometheus
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by joeblubaugh**
Unlike dashboard queries, alerting queries were not correctly applying
custom headers to datasource queries. This change mimics the dashboard
query code to apply custom headers.

Fixes #44460

Signed-off-by: Joe Blubaugh <joe.blubaugh@grafana.com>

### CODE REVIEW

File: pkg/tsdb/legacydata/service/service.go [hunk 1]
```diff
@@ -35,11 +42,59 @@ func ProvideService(pluginsClient plugins.Client, oAuthTokenService oauthtoken.O
...
+
+	req, err := generateRequest(ctx, ds, decryptedJsonData, query)
+	if err != nil {
+		return legacydata.DataResponse{}, err
+	}
+
+	// Attach Auth information
+	if oAuthIsOAuthPassThruEnabledFunc(h.oAuthTokenService, ds) {
+		if token := h.oAuthTokenService.GetCurrentOAuthToken(ctx, query.User); token != nil {
+			delete(query.Headers, "Authorization")
```
Comment (grobinson-grafana) [inline pkg/tsdb/legacydata/service/service.go:55]: Do we need to delete as the line below sets `Authorization`?

File: pkg/tsdb/legacydata/service/service.go [hunk 2]
```diff
@@ -35,11 +42,59 @@ func ProvideService(pluginsClient plugins.Client, oAuthTokenService oauthtoken.O
...
+
+		for _, f := range r.Frames {
+			if f.RefID == "" {
+				f.RefID = refID
+			}
+		}
+
+		qr.Dataframes = legacydata.NewDecodedDataFrames(r.Frames)
+
+		if r.Error != nil {
```
Comment (grobinson-grafana) [inline pkg/tsdb/legacydata/service/service.go:82]: Is `r.Error` not set until we call `NewDecodedDataFrames`?

File: pkg/tsdb/legacydata/service/service_test.go [hunk 3]
```diff
@@ -57,6 +57,39 @@ func TestHandleRequest(t *testing.T) {
 	})
 }
 
+func Test_generateRequest(t *testing.T) {
+	t.Run("Should attach custom headers to request if present", func(t *testing.T) {
+		jsonData := simplejson.New()
+		jsonData.Set(headerName+"testOne", "x-test-one")
```
Comment (grobinson-grafana) [inline pkg/tsdb/legacydata/service/service_test.go:63]: Would it be better to check that the suffix must be an integer like in ngalert?

File: pkg/tsdb/legacydata/service/service.go [hunk 4]
```diff
@@ -76,10 +124,15 @@ func (h *Service) HandleRequest(ctx context.Context, ds *models.DataSource, quer
 		Headers: query.Headers,
 	}
 
+	// Apply Configured Custom Headers to query request.
+	for k, v := range customHeaders(ds.JsonData, instanceSettings.DecryptedSecureJSONData) {
+		req.Headers[k] = v
```
Comment (grobinson-grafana) [inline pkg/tsdb/legacydata/service/service.go:129]: I added a check to make sure that custom headers cannot change headers that we have set (i.e. `From-Alert` and `X-Cache-Skip` in ngalert).

File: pkg/tsdb/legacydata/service/service.go [hunk 5]
```diff
@@ -93,37 +146,27 @@ func (h *Service) HandleRequest(ctx context.Context, ds *models.DataSource, quer
...
 
-		for _, f := range r.Frames {
-			if f.RefID == "" {
-				f.RefID = refID
+	headers := map[string]string{}
+	for k := range data {
+		if strings.HasPrefix(k, headerName) {
+			if header, ok := data[k].(string); ok {
+				valueKey := strings.ReplaceAll(k, headerName, headerValue)
+				headers[header] = decryptedJsonData[valueKey]
```
Comment (grobinson-grafana) [inline pkg/tsdb/legacydata/service/service.go:164]: Isn't `valueKey` just `fmt.Sprintf("httpHeaderValue%d", i)` where i is the index of the loop, like in ngalert?

Comment (joeblubaugh) [reply pkg/tsdb/legacydata/service/service.go:163]: I can't actually find the code that writes down "httpHeaderValue" to the store anywhere in the go code. Looks like that's handled by the frontend code. I'm rather happy to use the map keys and extract whatever suffix string happens to exist, especially since we don't have any guarantees that the frontend won't change this.

File: pkg/tsdb/legacydata/service/service_test.go (hunk 3 above)
Comment (joeblubaugh) [reply pkg/tsdb/legacydata/service/service_test.go:63]: See the above comment - I don't think we have a guarantee in our API that it will remain an integer.

File: pkg/tsdb/legacydata/service/service.go (hunk 4 above)
Comment (grobinson-grafana) [reply pkg/tsdb/legacydata/service/service.go:131]: There could be some headers we don't want them to change like the Host header, or for Hosted Metrics some kind of tracing headers? I'm not 100% sure.

File: pkg/tsdb/legacydata/service/service.go [hunk 6]
```diff
@@ -98,37 +148,27 @@ func (h *Service) HandleRequest(ctx context.Context, ds *models.DataSource, quer
...
-		}
+	data := jsonData.MustMap()
 
-		for _, f := range r.Frames {
-			if f.RefID == "" {
-				f.RefID = refID
+	headers := map[string]string{}
+	for k := range data {
+		if strings.HasPrefix(k, headerName) {
+			if header, ok := data[k].(string); ok {
```
Comment (grobinson-grafana) [inline pkg/tsdb/legacydata/service/service.go:164]: Should we add log lines for when its not a string?

**Review by grobinson-grafana — APPROVED** [review]

**Comment by grobinson-grafana** [comment]
Approved, but I left some additional comments!

File: pkg/tsdb/legacydata/service/service.go [hunk 7]
```diff
@@ -63,13 +115,6 @@ func (h *Service) HandleRequest(ctx context.Context, ds *models.DataSource, quer
 		query.Headers = make(map[string]string)
 	}
 
-	if oAuthIsOAuthPassThruEnabledFunc(h.oAuthTokenService, ds) {
```
[the remark this answers is not in the document]
Comment (joeblubaugh) [reply pkg/tsdb/legacydata/service/service.go:66]: So I didn't have to pass h.oAuthTokenService into the request, and so I could skip doing this if generateQuery failed.
