### PR TITLE
Cloudwatch: Move deep link creation to the backend

### LINKED ISSUE #30204: CloudWatch: "Show query preview" is broken
The cloudwatch query editor has a feature that allows to show query preview. When clicking on that, a tiny table will be collapsed that will show what expressions were generated in the backend and what periods were being used. The data in this table is passed from backend to frontend in tsdb.QueryResult.Meta, but when the datasource was refactored to use data frames in #27449, the meta data was no longer available to the query editor.

### LINKED ISSUE #30205: CloudWatch: Move deep links code from frontend to backend
At the moment, deep links to the cloudwatch console are created on the frontend. The code that handles this has a dependency tsdb.QueryResult.Meta, which should not be used now that the datasource is converted to use data frames. So instead of creating the link in the frontend, the link should be created in the backend where the data frames are being created.

### PR DESCRIPTION
**Pull request by sunker**
Moving the deep link code from the frontend to the backend also enabled fixing #30204 and that is also done in this PR. 

Fixes #30204
Fixes #30205

### CODE REVIEW

File: pkg/tsdb/cloudwatch/query_transformer.go [hunk 1]
```diff
@@ -104,10 +99,119 @@ func (e *cloudWatchExecutor) transformQueryResponsesToQueryResult(cloudwatchResp
 			queryResult.ErrorString = "Cloudwatch GetMetricData error: Too many datapoints requested - your search has been limited. Please try to reduce the time range"
 		}
 
+		eq, err := json.Marshal(executedQueries)
+		if err != nil {
+			plog.Error("Could not marshal executedString struct", err)
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer.go:104]: Shouldn't you return if it fails here? I don't think you should be using `eq` further down, if the encoding failed.

File: pkg/tsdb/cloudwatch/query_transformer.go [hunk 2]
```diff
@@ -104,10 +99,119 @@ func (e *cloudWatchExecutor) transformQueryResponsesToQueryResult(cloudwatchResp
...
+		}
+
+		link, err := buildDeepLink(refID, requestQueries, executedQueries, startTime, endTime)
+		if err != nil {
+			plog.Error("Could not build deep link", err)
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer.go:109]: Shouldn't you return if this fails?

File: pkg/tsdb/cloudwatch/query_transformer.go [hunk 3]
```diff
@@ -104,10 +99,119 @@ func (e *cloudWatchExecutor) transformQueryResponsesToQueryResult(cloudwatchResp
...
+						Links: []data.DataLink{
+							{
+								Title:       "View in CloudWatch console",
+								TargetBlank: true,
+								URL:         link,
+							},
+						},
+					}
+				}
+			}
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer.go:129]: It's more idiomatic to avoid deep nesting in Go.
```suggestion
			if link != "" {
				continue
			}
			
				for _, field := range frame.Fields {
					field.Config = &data.FieldConfig{
						Links: []data.DataLink{
							{
								Title:       "View in CloudWatch console",
								TargetBlank: true,
								URL:         link,
							},
						},
					}
				}
```

File: pkg/tsdb/cloudwatch/query_transformer.go [hunk 4]
```diff
@@ -104,10 +99,119 @@ func (e *cloudWatchExecutor) transformQueryResponsesToQueryResult(cloudwatchResp
...
+
 		queryResult.Dataframes = tsdb.NewDecodedDataFrames(frames)
-		queryResult.Meta.Set("gmdMeta", queryMeta)
 		results[refID] = queryResult
 	}
 
 	return results
 }
+
+// Generates a deep link from Grafana to the CloudWatch console. The link params are based on metric(s) for a given query row in the Query Editor
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer.go:139]: Even though this isn't exported, it's best to follow the standard doc comment style.
```suggestion
// buildDeepLink generates a deep link from Grafana to the CloudWatch console. The link params are based on metric(s) for a given query row in the Query Editor.
```

File: pkg/tsdb/cloudwatch/query_transformer.go [hunk 5]
```diff
@@ -104,10 +99,119 @@ func (e *cloudWatchExecutor) transformQueryResponsesToQueryResult(cloudwatchResp
...
+				Period: requestQuery.Period,
+			})
+			metricItems = append(metricItems, metricStat)
+		}
+		cloudWatchLinkProps.Metrics = metricItems
+	}
+
+	linkProps, err := json.Marshal(cloudWatchLinkProps)
+	if err != nil {
+		return "", fmt.Errorf("could not marshal link")
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer.go:189]: Shouldn't drop the original error:
```suggestion
		return "", fmt.Errorf("could not marshal link: %w", err)
```

File: pkg/tsdb/cloudwatch/query_transformer.go [hunk 6]
```diff
@@ -104,10 +99,119 @@ func (e *cloudWatchExecutor) transformQueryResponsesToQueryResult(cloudwatchResp
...
+	}
+
+	url, err := url.Parse(fmt.Sprintf(`https://%s.console.aws.amazon.com/cloudwatch/deeplink.js`, requestQuery.Region))
+	if err != nil {
+		return "", fmt.Errorf("unable to parse CloudWatch console deep link")
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer.go:194]:
```suggestion
		return "", fmt.Errorf("unable to parse CloudWatch console deep link: %w", err)
```

File: pkg/tsdb/cloudwatch/query_transformer_test.go [hunk 7]
```diff
@@ -150,4 +152,79 @@ func TestQueryTransformer(t *testing.T) {
...
+			Region:     "us-east-1",
+			Namespace:  "ec2",
+			MetricName: "CPUUtilization",
+			Statistics: aws.StringSlice([]string{"Average", "p46.32"}),
+			Period:     600,
+			Id:         "myId",
+		},
+	}
+
+	t.Run("A deep link that reference two metric stat metrics is created based on a request query with two stats", func(t *testing.T) {
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer_test.go:177]:
```suggestion
	t.Run("A deep link that references two metric stat metrics is created based on a request query with two stats", func(t *testing.T) {
```

File: pkg/tsdb/cloudwatch/query_transformer_test.go [hunk 8]
```diff
@@ -150,4 +152,79 @@ func TestQueryTransformer(t *testing.T) {
...
+		start, _ := time.Parse(time.RFC3339, "2018-03-15T13:00:00Z")
+		end, _ := time.Parse(time.RFC3339, "2018-03-18T13:34:00Z")
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer_test.go:179]:
```suggestion
		start, err := time.Parse(time.RFC3339, "2018-03-15T13:00:00Z")
		require.NoError(t, err)
		end, err := time.Parse(time.RFC3339, "2018-03-18T13:34:00Z")
		require.NoError(t, err)
```

File: pkg/tsdb/cloudwatch/query_transformer_test.go [hunk 9]
```diff
@@ -150,4 +152,79 @@ func TestQueryTransformer(t *testing.T) {
...
+
+		link, err := buildDeepLink("E", requestQueries, []executedQuery{}, start, end)
+		require.NoError(t, err)
+
+		parsedURL, err := url.Parse(link)
+		require.NoError(t, err)
+
+		decodedLink, _ := url.PathUnescape(parsedURL.String())
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer_test.go:187]:
```suggestion
		decodedLink, err := url.PathUnescape(parsedURL.String())
		require.NoError(t, err)
```

File: pkg/tsdb/cloudwatch/query_transformer_test.go [hunk 10]
```diff
@@ -150,4 +152,79 @@ func TestQueryTransformer(t *testing.T) {
...
+		expected := `https://us-east-1.console.aws.amazon.com/cloudwatch/deeplink.js?region=us-east-1#metricsV2:graph={"view":"timeSeries","stacked":false,"title":"E","start":"2018-03-15T13:00:00Z","end":"2018-03-18T13:34:00Z","region":"us-east-1","metrics":[["ec2","CPUUtilization",{"stat":"Average","period":600}],["ec2","CPUUtilization",{"stat":"p46.32","period":600}]]}`
+		assert.Equal(t, expected, decodedLink)
+	})
+
+	t.Run("A deep link that reference an expression based metric is created based on a request query with one stat", func(t *testing.T) {
+		start, _ := time.Parse(time.RFC3339, "2018-03-15T13:00:00Z")
+		end, _ := time.Parse(time.RFC3339, "2018-03-18T13:34:00Z")
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer_test.go:194]:
```suggestion
		start, err := time.Parse(time.RFC3339, "2018-03-15T13:00:00Z")
		require.NoError(t, err)
		end, err := time.Parse(time.RFC3339, "2018-03-18T13:34:00Z")
		require.NoError(t, err)
```

File: pkg/tsdb/cloudwatch/query_transformer_test.go [hunk 11]
```diff
@@ -150,4 +152,79 @@ func TestQueryTransformer(t *testing.T) {
...
+			Period:     600,
+		}}
+
+		link, err := buildDeepLink("E", requestQueries, executedQueries, start, end)
+		require.NoError(t, err)
+
+		parsedURL, err := url.Parse(link)
+		require.NoError(t, err)
+
+		decodedLink, _ := url.PathUnescape(parsedURL.String())
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer_test.go:207]:
```suggestion
		decodedLink, err := url.PathUnescape(parsedURL.String())
		require.NoError(t, err)
```

File: pkg/tsdb/cloudwatch/query_transformer_test.go [hunk 12]
```diff
@@ -150,4 +152,79 @@ func TestQueryTransformer(t *testing.T) {
...
+		expected := `https://us-east-1.console.aws.amazon.com/cloudwatch/deeplink.js?region=us-east-1#metricsV2:graph={"view":"timeSeries","stacked":false,"title":"E","start":"2018-03-15T13:00:00Z","end":"2018-03-18T13:34:00Z","region":"us-east-1","metrics":[{"expression":"REMOVE_EMPTY(SEARCH('Namespace=\"AWS/EC2\"+MetricName=\"CPUUtilization\"',+'Sum',+600))"}]}`
+		assert.Equal(t, expected, decodedLink)
+	})
+
+	t.Run("A deep link is not built in case any of the executedQueries are math expressions", func(t *testing.T) {
+		start, _ := time.Parse(time.RFC3339, "2018-03-15T13:00:00Z")
+		end, _ := time.Parse(time.RFC3339, "2018-03-18T13:34:00Z")
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer_test.go:214]:
```suggestion
		start, err := time.Parse(time.RFC3339, "2018-03-15T13:00:00Z")
		require.NoError(t, err)
		end, err := time.Parse(time.RFC3339, "2018-03-18T13:34:00Z")
		require.NoError(t, err)
```

File: pkg/tsdb/cloudwatch/query_transformer_test.go [hunk 13]
```diff
@@ -150,4 +152,79 @@ func TestQueryTransformer(t *testing.T) {
...
+			Period:     600,
+		}}
+
+		link, err := buildDeepLink("E", requestQueries, executedQueries, start, end)
+		require.NoError(t, err)
+
+		parsedURL, err := url.Parse(link)
+		require.NoError(t, err)
+
+		decodedLink, _ := url.PathUnescape(parsedURL.String())
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer_test.go:227]:
```suggestion
		decodedLink, err := url.PathUnescape(parsedURL.String())
		require.NoError(t, err)
```

**Review by aknuds1 — CHANGES_REQUESTED** [review]
See comments

File: pkg/tsdb/cloudwatch/query_transformer.go (hunk 1 above)
Comment (sunker) [reply pkg/tsdb/cloudwatch/query_transformer.go:104]: This is just meta data, so we don't need to return an error. But we should definitely add key/value pair to plog!

Comment (sunker) [reply pkg/tsdb/cloudwatch/query_transformer.go:104]: Or actually I think you're right. Lets return an error

File: pkg/tsdb/cloudwatch/query_transformer.go (hunk 3 above)
Comment (sunker) [reply pkg/tsdb/cloudwatch/query_transformer.go:129]: Yes, good idea!

File: pkg/tsdb/cloudwatch/query_transformer.go (hunk 1 above)
Comment (aknuds1) [reply pkg/tsdb/cloudwatch/query_transformer.go:104]: I actually didn't mean to return an error, but to return in the first place. This code just continues in case of an error.

File: pkg/tsdb/cloudwatch/query_transformer.go [hunk 14]
```diff
@@ -101,30 +101,32 @@ func (e *cloudWatchExecutor) transformQueryResponsesToQueryResult(cloudwatchResp
 
 		eq, err := json.Marshal(executedQueries)
 		if err != nil {
-			plog.Error("Could not marshal executedString struct", err)
+			return nil, fmt.Errorf("Could not marshal executedString struct: %w", err)
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer.go:104]: Go errors shouldn't be capitalized, also the message looks misleading:
```suggestion
			return nil, fmt.Errorf("could not marshal executed queries %w", err)
```

File: pkg/tsdb/cloudwatch/query_transformer.go [hunk 15]
```diff
@@ -101,30 +101,32 @@ func (e *cloudWatchExecutor) transformQueryResponsesToQueryResult(cloudwatchResp
...
 		}
 
 		link, err := buildDeepLink(refID, requestQueries, executedQueries, startTime, endTime)
 		if err != nil {
-			plog.Error("Could not build deep link", err)
+			return nil, fmt.Errorf("Could not build deep link: %w", err)
```
Comment (aknuds1) [inline pkg/tsdb/cloudwatch/query_transformer.go:109]:
```suggestion
			return nil, fmt.Errorf("could not build deep link: %w", err)
```

**Review by aknuds1 — APPROVED** [review]
Looks good now, but see comments for nits.

File: pkg/tsdb/cloudwatch/query_transformer.go [hunk 16]
```diff
@@ -104,10 +99,124 @@ func (e *cloudWatchExecutor) transformQueryResponsesToQueryResult(cloudwatchResp
...
+		for _, frame := range frames {
+			frame.Meta = &data.FrameMeta{
+				ExecutedQueryString: string(eq),
+			}
+
+			if link == "" {
+				continue
+			}
+
+			for _, field := range frame.Fields {
```
Comment (ying-jeanne) [inline pkg/tsdb/cloudwatch/query_transformer.go:121]: i have tested, we don't need to add config to all field anymore, just Fields[1] would be good.

**Review by papagian — APPROVED** [review]
AFAICT modifications look good and it works as expected.

File: pkg/tsdb/cloudwatch/query_transformer.go (hunk 16 above)
Comment (sunker) [reply pkg/tsdb/cloudwatch/query_transformer.go:121]: that's great news! I'll update accordingly

Comment (sunker) [reply pkg/tsdb/cloudwatch/query_transformer.go:129]: actually that didn't work for me @ying-jeanne
