### PR TITLE
Alerting: hide "silence" button for external AM setups

### LINKED ISSUE #59750: Alerting: Silence button not working with external alertmanager
**What happened**:
Clicking the "silence" button on an alert rule while having an Alertmanager data source with "Receive Grafana Alerts" enabled always creates the silence in the internal Alertmanager data source. This happens even with the setting "Send alerts to = Only External".

**What you expected to happen**:
Silences are created in the external Alertmanager. Or if that's not possible for some reason, the "silence" button should not appear.

**How to reproduce it (as minimally and precisely as possible)**:
* create Alertmanager data source with "Receive Grafana Alerts" enabled 
* set "Send alerts to" to "External Only"
* click "Silence" on any alert rule

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3
- Data source type & version: Alertmanager
- OS Grafana is installed on: Ubuntu
- User OS & Browser: MacOS 12.3, Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by gillesdemey**
**What is this feature?**

Several changes in this PR; but most notably

* Hides the "silence" button for Grafana managed rules if alert instances are only delivered to external Alertmanagers.
* Show a warning in several places when the "Both internal and external" is configured for alert instance delivery.
* Some small UI changes to "matched instances" in the "Create silence" view.

**Why do we need this feature?**

We were previously showing a "create silence" button for Grafana managed alerts even if the admin has configured external Alertmanager(s). This would create the silence in the internal Alertmanager and it wouldn't do anything to silence their alert rule.

**Who is this feature for?**

Anyone who sets up or creates silences for an alert rule.

**Which issue(s) does this PR fix?**:

Fixes #59750

**Special notes for your reviewer**:

I've made some changes to how we fetch the Alertmanager choice, I've moved that to the warning component instead of fetching it on the parent pages.

I'm also including a screenshot of the new warning message so we can get a review of the copy from @brendamuir :)

image

### CODE REVIEW

File: public/app/features/alerting/unified/components/GrafanaAlertmanagerDeliveryWarning.tsx [hunk 1]
```diff
@@ -1,41 +1,60 @@
...
-  if (currentAlertmanager !== GRAFANA_RULES_SOURCE_NAME) {
+  const { useGetAlertmanagerChoiceQuery, useGetExternalAlertmanagersQuery } = alertmanagerApi;
+  const viewingInternalAm = currentAlertmanager === GRAFANA_RULES_SOURCE_NAME;
+
+  const { currentData: alertmanagerChoice } = useGetAlertmanagerChoiceQuery();
+  const { currentData: externalAMs } = useGetExternalAlertmanagersQuery();
+
+  const externalAlertManagers = externalAMs?.activeAlertManagers ?? [];
+
+  if (alertmanagerChoice === AlertmanagerChoice.Internal) {
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/GrafanaAlertmanagerDeliveryWarning.tsx:27]: Unfortunately due to the rules of hooks I can't think of a way to avoid fetching the external AMs if `Internal` is selected.

Though I _think_ we can do so if we import the deferred version of the `GetExternalAlertmanagersQuery` hook and use a `useEffect` to call it only if we have chosen to send to external AMs. 🤔

Comment (gillesdemey) [reply public/app/features/alerting/unified/components/GrafanaAlertmanagerDeliveryWarning.tsx:27]: Well – turns out it's a lot easier to just use `skip` as a config for `useGetExternalAlertmanagersQuery()` 😬

File: public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx [hunk 2]
```diff
@@ -249,6 +254,21 @@ export const RuleDetailsActionButtons: FC<Props> = ({ rule, rulesSource, isViewM
   return null;
 };
 
+function useCanSilence(alertmanagerSourceName?: string) {
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx:257]: Nice 👏

File: public/app/features/alerting/unified/components/GrafanaAlertmanagerDeliveryWarning.tsx [hunk 3]
```diff
@@ -1,41 +1,70 @@
...
+
+  const viewingInternalAM = currentAlertmanager === GRAFANA_RULES_SOURCE_NAME;
+
+  const interactsWithExternalAMs =
+    alertmanagerChoice && [AlertmanagerChoice.External, AlertmanagerChoice.All].includes(alertmanagerChoice);
+
+  const fetchExternalAMs = viewingInternalAM && interactsWithExternalAMs;
+
+  // only fetch external AMs when we have the right admin config
+  const { currentData: externalAMs } = useGetExternalAlertmanagersQuery(undefined, {
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/GrafanaAlertmanagerDeliveryWarning.tsx:30]: There is one caveat there. The `getExternalAlertmanagers` endpoint requires `Admin` permissions, so the component would work only for Admins.
Maybe we could ask to BE folks to add information about the number of active external AMs to the `getAlertmanagerChoice` response. 
The `getExternalAlertmanagers` endpoint reveals AMs URLs, so there is probably no option to loosen its permission.

**Comment by brendamuir** [comment]
@gillesdemey how about something like this: You have additional Alertmanagers to configure

Ensure you make configuration changes in all of your Alertmanagers; both internal and external.  Changing one will not affect the others. 
To change your Alertmanager setup, go to the Alerting Admin page. If you do not have access, contact your Administrator.

File: public/app/features/alerting/unified/components/GrafanaAlertmanagerDeliveryWarning.tsx (hunk 3 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/components/GrafanaAlertmanagerDeliveryWarning.tsx:30]: Ah that's a pity – should we roll back the additional check for multiple external AMs?

File: pkg/services/ngalert/api/api_configuration.go [hunk 4]
```diff
@@ -148,8 +148,17 @@ func (srv ConfigSrv) RouteGetAlertingStatus(c *contextmodel.ReqContext) response
...
+	if err != nil {
+		msg := "failed to fetch configuration from the database"
+		srv.log.Error(msg, "error", err)
+		return ErrResp(http.StatusInternalServerError, err, msg)
+	}
+
 	resp := apimodels.AlertingStatus{
-		AlertmanagersChoice: apimodels.AlertmanagersChoice(sendsAlertsTo.String()),
+		AlertmanagersChoice:   apimodels.AlertmanagersChoice(sendsAlertsTo.String()),
+		ExternalAlertManagers: len(externalAlertManagers),
```
Comment (alexweav) [inline pkg/services/ngalert/api/api_configuration.go:161]: Extremely nitpicky:

Could we make the name for this field something that conveys it's a count, rather than a list, like `NumExternalAlertmanagers`? Just in case we decide to expose more information about this in the future

**Review by alexweav — COMMENTED** [review]
The API parts are looking :+1:! I'll defer on the typescript changes.

File: public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx (hunk 2 above)
Comment (armandgrillet) [reply public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx:261]: The name `useCanSilence` seems strange to me, is it `userCanSilence` or `canSilence`?

File: pkg/services/ngalert/api/api_configuration.go (hunk 4 above)
Comment (gillesdemey) [reply pkg/services/ngalert/api/api_configuration.go:161]: Sounds totally reasonable – will update this!

File: public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx (hunk 2 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx:261]: React Hooks need to have a `use` prefix, and this is enforced by the `eslint(react-hooks/rules-of-hooks)` lint rule.

File: public/app/features/alerting/unified/components/GrafanaAlertmanagerDeliveryWarning.tsx [hunk 5]
```diff
@@ -5,37 +5,58 @@ import { GrafanaTheme2 } from '@grafana/data/src';
...
+
+  if (!interactsWithExternalAMs || !viewingInternalAM) {
     return null;
   }
 
-  if (alertmanagerChoice !== AlertmanagerChoice.External) {
-    return null;
+  const hasActiveExternalAMs = amChoiceStatus.numExternalAlertmanagers > 0;
+
+  if (amChoiceStatus.alertmanagersChoice === AlertmanagerChoice.External && hasActiveExternalAMs) {
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/GrafanaAlertmanagerDeliveryWarning.tsx:33]: If `alertmanagersChoice === External` and `hasActiveExternalAMs === 0` there is still no point in configuring Grafana Alertmanager, isn't it?

File: public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx [hunk 6]
```diff
@@ -263,6 +267,25 @@ export const RuleDetailsActionButtons: FC<Props> = ({ rule, rulesSource, isViewM
...
+ * 1. the user has no permissions to create silences
+ * 2. the admin has configured to only send instances to external AMs
+ */
+function useCanSilence(alertmanagerSourceName?: string) {
+  const hasAlertmanagerSource = Boolean(alertmanagerSourceName);
+
+  const { useGetAlertmanagerChoiceStatusQuery } = alertmanagerApi;
+  const { currentData: amConfigStatus } = useGetAlertmanagerChoiceStatusQuery();
+
+  const hasPermissions = contextSrv.hasAccess(AccessControlAction.AlertingInstanceCreate, contextSrv.isEditor);
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx:281]: This permission is correct only for Grafana AM. 
Please use the `getInstancesPermissions` function to get the necessary permission based on the `alertmanagerSourceName`

File: public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx [hunk 7]
```diff
@@ -263,6 +267,25 @@ export const RuleDetailsActionButtons: FC<Props> = ({ rule, rulesSource, isViewM
   return null;
 };
 
+/**
+ * We don't want to show the silence button if either
+ * 1. the user has no permissions to create silences
+ * 2. the admin has configured to only send instances to external AMs
+ */
+function useCanSilence(alertmanagerSourceName?: string) {
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx:275]: I think we should refactor this a bit. We show the `Silence` button only for Grafana-managed alert rules and the condition in https://github.com/grafana/grafana/pull/62133/files#diff-691394a56baf1c8cb3534abb9530db44e1329d6f0bd8866049404848779bd13cR47-R49 is no longer valid
I think we could get rid of `alertmanagerSourceName` and only check if this is a Grafana-managed rule

File: public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx (hunk 6 above)
Comment (konrad147) [reply public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx:281]: However, this might be correct because we want to display Silence only for Grafana-managed rules

File: public/app/features/alerting/unified/components/GrafanaAlertmanagerDeliveryWarning.tsx (hunk 5 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/components/GrafanaAlertmanagerDeliveryWarning.tsx:33]: Good point, I don't think we need to check how many external AMs are configured 🤔

File: public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx (hunk 6 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx:281]: I've copied this one from the original implementation, I believe it's correct since we only show the silence button for Grafana managed rules anyway.

File: public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx (hunk 7 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx:275]: Yea that makes sense, will update the hook to check the type of the rule instead 👍

**Comment by gillesdemey** [comment]
Failing enterprise CI is unrelated to the changes in this PR

**Review by konrad147 — APPROVED** [review]
LGTM!
