### PR TITLE
DataSource: change status code to 404 if datasource and plugin is not found

### LINKED ISSUE #36418: Datasource proxy returning 5xx for DataSource not found
**What happened**:
Grafana workspace throwing 500 with the error code "data source not found", message "Unable to load datasource meta data" when calling /api/datasources/proxy/4/api/v1/query_range

When [datasources/cache](https://github.com/aws-observability/aws-grafana/blob/fbcc464c7d5197dd6cd134184d990f0bda2893bb/pkg/services/datasources/cache.go#L35) calls the [sqlstore.getDatasrouce](https://github.com/aws-observability/aws-grafana/blob/fbcc464c7d5197dd6cd134184d990f0bda2893bb/pkg/services/datasources/cache.go#L52) the sqlstore is returning a DataSource not found error [link](https://github.com/aws-observability/aws-grafana/blob/fbcc464c7d5197dd6cd134184d990f0bda2893bb/pkg/services/sqlstore/datasource.go#L62), this is being translated by the dataproxy as an Internal Server Error.

**What you expected to happen**:
Grafana returns 4xx status code when a datasource is not found 

**How to reproduce it (as minimally and precisely as possible)**:
* In a Grafana workspace add a Prometheus data source
* Go to Explore, select the Prometheus data source
* Configure simple query (example: `http_requests_total`)
* Open new tab, delete Prometheus datasource
* Go back to Explore tab and run query 

**Anything else we need to know?**:
AWS Managed Grafana reporting issue. 

**Environment**:
- Grafana version: 7.5
- Data source type & version: any datasource relying on datasources/proxy
- OS Grafana is installed on: n/a
- User OS & Browser: n/a

### PR DESCRIPTION
**Pull request by tharun208**
**What this PR does / why we need it**: We are returning the status code as `500` if the data source is not found, this PR changes the status code to `404`.

**Which issue(s) this PR fixes**: #36418

Fixes #36418

**Special notes for your reviewer**: Also, changed the status code to `404` if the plugin associated with the data source is not found.

### CODE REVIEW

File: pkg/services/datasourceproxy/datasourceproxy.go [hunk 1]
```diff
@@ -46,7 +46,7 @@ func (p *DatasourceProxyService) ProxyDatasourceRequestWithID(c *models.ReqConte
 			c.JsonApiErr(http.StatusForbidden, "Access denied to datasource", err)
 			return
 		}
-		c.JsonApiErr(http.StatusInternalServerError, "Unable to load datasource meta data", err)
+		c.JsonApiErr(http.StatusNotFound, "Unable to load datasource meta data", err)
```
Comment (torkelo) [inline pkg/services/datasourceproxy/datasourceproxy.go:49]: do no think this is correct, you not checking if this is the actual error

Comment (tharun208) [reply pkg/services/datasourceproxy/datasourceproxy.go]: addressed

**Review by torkelo — APPROVED** [review]
