### PR TITLE
Thresholds: Fixed issue with thresholds in overrides not working after save and reload

### LINKED ISSUE #27290: Singlestat Panel Defaulting to Base Color After Dashboard Refresh
Hi there, this issue has been bugging me for a few weeks now.

**What happened**:
After the configuration of threshold overrides in the Singlestat Panel, the coloring shows correctly in the panel. However when I save and refresh the page, it defaults back to display the base color. Editing the panel and clicking back onto the threshold override settings the correct color displays again. (I'm using negative values for the threshold settings)

**What you expected to happen**:
On dashboard refresh, the Singlestat panel should still show the correct color based on the threshold override settings.

image
Correctly configured and working

image
After save and refresh it defaults to the Base color. Clicking and unclicking the threshold value reverts it back to the correct color.

**How to reproduce it (as minimally and precisely as possible)**:
1. Read metric from prometheus into Singlestat Panel.
2. Set the Threshold Override in the Overrides tab - not the Field tab.
3. Use negative numbers for the threshold values.
4. Identify that the correct color is showing in the Singlestat panel.
5. Save and refresh.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chrome, Windows 10

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #27290

Currently, the fix of changing the first threshold value from null to -Infinity is done in applyFieldOverride but only after defaults are applied. 

Moved logic of fixing null to -Infinity to plugin load instead, feels like this part does not need to be executed on every field override apply.

### CODE REVIEW

File: public/app/features/dashboard/state/PanelModel.ts [hunk 1]
```diff
@@ -501,6 +489,51 @@ export class PanelModel implements DataConfigSource {
...
+      {},
+      defaults.defaults,
+      fieldConfig ? fieldConfig.defaults : {},
+      (objValue: any, srcValue: any): any => {
+        if (_.isArray(srcValue)) {
+          return srcValue;
+        }
+      }
+    ),
+    overrides: [...defaults.overrides, ...(fieldConfig && fieldConfig.overrides ? fieldConfig.overrides : [])],
```
Comment (hugohaggmark) [inline public/app/features/dashboard/state/PanelModel.ts:504]: I think this code is a mouthful and deserves some tests to explain it :)

Comment (torkelo) [reply public/app/features/dashboard/state/PanelModel.ts:504]: also thought this looked strange (this was just copied from the existing code that I extracted to this new method). 

Can simplify this as we do not actually support setting default overrides

**Review by hugohaggmark — APPROVED** [review]
LGTM!
