### PR TITLE
TablePanel: Add support for Count calculation per column or per entire dataset

### LINKED ISSUE #57799: Table footer shows count value under each column
Maybe as designed but the current table footer shows the count under each column.
When selecting count for the footer i expected the total count either right next to Total (so under the first column) or all the way to the right under the last column.

How it looks:

Image

How i expected it:

Image

Steps to reproduce:
1. create a table with multiple columns
2. enable table footer and select "Count" from the drop down
Expected:
The count is either under the first column, next to total, or under the last column.
Actual: 
The count is under all columns 

Version: 9.2.2

### PR DESCRIPTION
**Pull request by mdvictor**
**What is this feature?**
The Count calculation in the table panel shows values per each column, and they are usually the same number since the count calculation takes in the data length itself. With this change, the calculation counts only non-null values and shows them per column. 
An extra switch has been added in the options ui, available only for the count calculation, which allows the user to set the count calculation for the entire dataset, thus showing the count only on the first column of the table footer. 

**Why do we need this feature?**
The count calculation could do more than it already does and by occupying less space. We don't need to see the same count value (aka the dataset length) across all columns in the table footer. At the same time, we might not want to see the dataset length at all, but only a counter of all valid (non-null) values

**Who is this feature for?**
Table panel users

**Which issue(s) does this PR fix?**:

Fixes #57799

Todo: 
- [x] Write some tests for this
- [x] Add `footerOptions` to schema
- [x] Refactor name and write description
- [x] Docs

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/FooterRow.tsx [hunk 1]
```diff
@@ -71,10 +72,14 @@ function renderFooterCell(column: ColumnInstance, tableStyles: TableStyles, heig
...
 }
 
-export function getFooterValue(index: number, footerValues?: FooterItem[]) {
+export function getFooterValue(index: number, footerValues?: FooterItem[], isCountAllSet?: boolean) {
   if (footerValues === undefined) {
     return EmptyCell;
   }
 
+  if (isCountAllSet) {
+    return FooterCell({ value: [{ Count: footerValues[index] as string }] });
```
Comment (joshhunt) [inline packages/grafana-ui/src/components/Table/FooterRow.tsx:81]: Can we properly narrow the type down, rather than just hoping for the best that the value is a string? 

We want to avoid adding _more_ exceptions to .betterer.results that we only have to go in and clean up later.

Comment (joshhunt) [reply packages/grafana-ui/src/components/Table/FooterRow.tsx:81]: Alternatively, rename this file to `.js` and remove all typescript and be prepared to justify the decision 😅

File: public/app/plugins/panel/table/module.tsx [hunk 2]
```diff
@@ -131,6 +131,13 @@ export const plugin = new PanelPlugin<PanelOptions, TableFieldOptions>(TablePane
         defaultValue: [ReducerID.sum],
         showIf: (cfg) => cfg.footer?.show,
       })
+      .addBooleanSwitch({
```
Comment (codeincarnate) [inline public/app/plugins/panel/table/module.tsx:134]: Looks good! I'm thinking we should add a description here and maybe change the name of this option as well to make it more clear.

Comment (codeincarnate) [reply public/app/plugins/panel/table/module.tsx:134]: And I'd say we might to reverse the language, like "Count Per Field" with a description along the lines of "Count the non-empty results of each field separately"

Comment (mdvictor) [reply public/app/plugins/panel/table/module.tsx:134]: From this I understand we also reverse the functionality. E.g: We show a count for all fields in one column and when the "Count Per Field" switch is active we show a count for each field. This would change all existing table panels for the users. Is this something we'd want?

**Comment by zoltanbedi** [comment]
Found a couple of issue. 
- Count all data seems to be off when field has null values.
- If you tick count all data and then change calculation then it is still enabled

https://user-images.githubusercontent.com/13729989/200818567-14a095f8-e413-4211-bbfd-7761954c39f0.mov

I think adding the `ignoreNulls` check to the count makes sense. But only showing the count to the right, I'm not sure. Based on my panel below that has the error. Which fields count is this showing? This is confusing for me. Alse where can I change the `nullValueMode` option for the table panel? This is also going to affect the timeseries panel when there are calculations there.

I'd also love to see some docs for this.

File: public/app/plugins/panel/table/models.gen.ts [hunk 3]
```diff
@@ -27,6 +27,7 @@ export const defaultPanelOptions: PanelOptions = {
   footer: {
```
Comment (zoltanbedi) [inline public/app/plugins/panel/table/models.gen.ts:27]: This options is not under the schema. We should put it there.

**Comment by mdvictor** [comment]
@zoltanbedi Calculation functionality docs seem to be in a different [page](https://grafana.com/docs/grafana/latest/panels-visualizations/calculation-types/). Since this functionality is only for the table panel, it doesn't make sense to add it there, but since the table doc page doesn't describe calculations at all it kind of feels out of context to describe this feature in there. Not sure how to add this to the docs in a readable way. Any suggestions? 

Tagging @grafana/docs-dev also for help on this, if possible.

**Review by zoltanbedi — COMMENTED** [review]
> Calculation functionality docs seem to be in a different [page](https://grafana.com/docs/grafana/latest/panels-visualizations/calculation-types/). Since this functionality is only for the table panel, it doesn't make sense to add it there, but since the table doc page doesn't describe calculations at all it kind of feels out of context to describe this feature in there. Not sure how to add this to the docs in a readable way. Any suggestions?

Yes this is a good opportunity to improve the doc for the table panel. Add a new section for Table footer options mention the calcs and how it works. Link it to the original article. Explain the feature that you just added.

**Review by zoltanbedi — APPROVED** [review]
lgtm

File: docs/sources/panels-visualizations/visualizations/table/index.md [hunk 4]
```diff
@@ -160,3 +160,15 @@ Columns with filters applied have a blue funnel displayed next to the title.
 {{< figure src="/static/img/docs/tables/filtered-column.png" max-width="500px" caption="Filtered column" class="docs-image--no-shadow" >}}
 
 To remove the filter, click the blue funnel icon and then click **Clear filter**.
+
+## Table footer
+
+You can use the table footer to show [calculations]({{< relref "../../calculation-types/" >}}) on fields.
+
+After enabling the table footer, you can select your **Calculation** and select the **Fields** that should be calculated. Not selecting any field apply the calculation to all numeric fields.
```
Comment (chri2547) [inline docs/sources/panels-visualizations/visualizations/table/index.md:168]: After you enable the table footer:

1. Select the **Calculation**. 
1. Select the **Fields** you want to calculate. 

The system applies the calculation to all numeric fields if you do not select a field.

File: docs/sources/panels-visualizations/visualizations/table/index.md [hunk 5]
```diff
@@ -160,3 +160,15 @@ Columns with filters applied have a blue funnel displayed next to the title.
...
+
+### Count rows
+
+On selecting the **Count** calculation, you will see the **Count rows** switch.
```
Comment (chri2547) [inline docs/sources/panels-visualizations/visualizations/table/index.md:172]: Selecting the **Count** calculation will show the **Count rows** switch.

File: docs/sources/panels-visualizations/visualizations/table/index.md [hunk 6]
```diff
@@ -160,3 +160,15 @@ Columns with filters applied have a blue funnel displayed next to the title.
...
+
+By enabling this option the footer will show the number of rows in the dataset instead of the number of values in the selected fields.
```
Comment (chri2547) [inline docs/sources/panels-visualizations/visualizations/table/index.md:174]: I think you can combine these two statements by saying:

Select the **Count** calculation when you want to show the number of rows in the dataset instead of the number of values in the selected fields.

**Review by chri2547 — COMMENTED** [review]
Docs reviewed post-merge.
