### PR TITLE
Variables: Ensure variables in query params are correctly recognised

### LINKED ISSUE #44304: Chained variables don't refresh
**What (didn't) happened**:

When using the child in a panel of a series of chained variables, the panel doesn't update when the variable does.

**What you expected to happen**:

When changing the variable, the panel using it should update as well.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a [JSON API data source](https://grafana.com/plugins/marcusolsson-json-datasource) (1.3.0).
2. Import the following dashboard.

<details>
<summary>
<strong>DASHBOARD JSON</strong>
</summary>
<pre>
{
  "__inputs": [
    {
      "name": "DS_TV_MAZE",
      "label": "TV Maze",
      "description": "",
      "type": "datasource",
      "pluginId": "marcusolsson-json-datasource",
      "pluginName": "JSON API"
    }
  ],
  "__elements": [],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "8.3.3"
    },
    {
      "type": "datasource",
      "id": "marcusolsson-json-datasource",
      "name": "JSON API",
      "version": "1.3.0"
    },
    {
      "type": "panel",
      "id": "table",
      "name": "Table",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "iteration": 1642754355432,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "marcusolsson-json-datasource",
        "uid": "${DS_TV_MAZE}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "align": "auto",
            "displayMode": "auto"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "footer": {
          "fields": "",
          "reducer": [
            "sum"
          ],
          "show": false
        },
        "showHeader": true
      },
      "pluginVersion": "8.3.3",
      "targets": [
        {
          "cacheDurationSeconds": 300,
          "datasource": {
            "type": "marcusolsson-json-datasource",
            "uid": "${DS_TV_MAZE}"
          },
          "fields": [
            {
              "jsonPath": "$.name"
            },
            {
              "jsonPath": "$.airdate",
              "language": "jsonpath",
              "name": ""
            },
            {
              "jsonPath": "$.runtime",
              "language": "jsonpath",
              "name": ""
            },
            {
              "jsonPath": "$.summary",
              "language": "jsonpath",
              "name": ""
            }
          ],
          "method": "GET",
          "params": [
            [
              "season",
              "${season}"
            ],
            [
              "number",
              "${episode}"
            ]
          ],
          "queryParams": "",
          "refId": "A",
          "urlPath": "/shows/${show}/episodebynumber"
        }
      ],
      "title": "Panel Title",
      "type": "table"
    }
  ],
  "refresh": "",
  "schemaVersion": 34,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": false,
          "text": "216",
          "value": "216"
        },
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "show",
        "options": [
          {
            "selected": true,
            "text": "216",
            "value": "216"
          }
        ],
        "query": "216",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      },
      {
        "current": {},
        "datasource": {
          "type": "marcusolsson-json-datasource",
          "uid": "${DS_TV_MAZE}"
        },
        "definition": "$.[*].number",
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "season",
        "options": [],
        "query": {
          "cacheDurationSeconds": 300,
          "fields": [
            {
              "jsonPath": "$.[*].number"
            }
          ],
          "method": "GET",
          "queryParams": "",
          "urlPath": "/shows/${show}/seasons"
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      },
      {
        "current": {},
        "datasource": {
          "type": "marcusolsson-json-datasource",
          "uid": "${DS_TV_MAZE}"
        },
        "definition": "$.[?(@.season == ${season})].number",
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "episode",
        "options": [],
        "query": {
          "cacheDurationSeconds": 300,
          "fields": [
            {
              "jsonPath": "$.[?(@.season == ${season})].number"
            }
          ],
          "method": "GET",
          "params": [],
          "queryParams": "",
          "urlPath": "/shows/${show}/episodes"
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "TV Shows",
  "uid": "n4o7BRx7k",
  "version": 4,
  "weekStart": ""
}
</pre>
</details>

3. Change the `season` variable and watch the `episode` variable update.
4. Change the `episode` variable. The panel doesn't reflect the new value. Only if you reload the dashboard.

**Anything else we need to know?**:

Works in 8.2.0.

Related issues:

https://github.com/marcusolsson/grafana-json-datasource/issues/95
https://github.com/marcusolsson/grafana-json-datasource/issues/155

**Environment**:

- Grafana version: 8.3.3
- Data source type & version: JSON API 1.3.0
- OS Grafana is installed on: Official Docker image on macOS 12.1
- User OS & Browser: Firefox on macOS 12.1

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- when a variable is used in a query param, the stringified json looks like `{ params: [['param', '$var']] }`
- the regex to match the `[[var:fmt]]` pattern is too generous, causing it to match the whole thing (e.g. `[['param', '$var']]`) instead of matching on the individual variable `$var`
- make the regex to match the `[[var:fmt]]` pattern more specific such that it can only include alphanumeric and `_`

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/44304

**Special notes for your reviewer**:

### CODE REVIEW

**Review by kaydelaney — APPROVED** [review]

File: public/app/features/variables/utils.ts [hunk 1]
```diff
@@ -15,10 +15,10 @@ import { KeyedVariableIdentifier, VariableIdentifier, VariablePayload } from './
 /*
  * This regex matches 3 types of variable reference with an optional format specifier
  * \$(\w+)                          $var1
- * \[\[([\s\S]+?)(?::(\w+))?\]\]    [[var2]] or [[var2:fmt2]]
+ * \[\[(\w+?)(?::(\w+))?\]\]        [[var2]] or [[var2:fmt2]]
  * \${(\w+)(?::(\w+))?}             ${var3} or ${var3:fmt3}
  */
-export const variableRegex = /\$(\w+)|\[\[([\s\S]+?)(?::(\w+))?\]\]|\${(\w+)(?:\.([^:^\}]+))?(?::([^\}]+))?}/g;
```
Comment (ashharrison90) [inline public/app/features/variables/utils.ts:21]: @torkelo would appreciate your thoughts on this change 🤔
