### PR TITLE
Backend Plugins: Discard logged messages from logger named stdio

### LINKED ISSUE #23461: Backend Plugins: Mute logged warning about unknown service plugin.GRPCStdio
**What happened**:
Running Grafana with an old backend plugin logs 
```
WARN[04-09|11:07:23] received EOF, stopping recv loop         logger=plugins.backend pluginId=grafana-test-datasource err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
```

**What you expected to happen**:
Since the error is expected when a plugin doesn't use the latest hashicorp/go-plugin version it shouldn't be logged as a warning.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Introduced by #23388

**Environment**:
- Grafana version: master

Epic: #19667

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Discard logged messages coming from backend plugin logger named stdio since that service is not in use. Currently it logs a warning which doesn't make sense.

**Which issue(s) this PR fixes**:
Fixes #23461

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/plugins/backendplugin/log_wrapper.go [hunk 1]
```diff
@@ -60,7 +76,18 @@ func (lw logWrapper) With(args ...interface{}) hclog.Logger {
...
 }
 func (lw logWrapper) Named(name string) hclog.Logger {
-	return logWrapper{Logger: lw.Logger.New()}
+	discardLogs := false
+	if name == "stdio" {
+		// discard logs from stdio hashicorp/go-plugin gRPC service since
+		// it's not enabled/in use per default.
+		// discard debug log of "waiting for stdio data".
+		// discard warn log of "received EOF, stopping recv loop".
+		discardLogs = true
```
Comment (bergquist) [inline pkg/plugins/backendplugin/log_wrapper.go:85]: Another option would be to return a Noop logger here that doesn't log anything. This is fine as well. If we stick to this solution I think it would be cleaner to invert the if statements to avoid the early return and just wrap the log statement.

Comment (marefr) [reply pkg/plugins/backendplugin/log_wrapper.go:85]: Good idea. Will try it out

**Review by bergquist — APPROVED** [review]
LGTM! :)
