### PR TITLE
CloudWatch: Fix sorting of metrics results

### LINKED ISSUE #25494: Cloudwatch SORT metrics math function is not respected for more than 10 results
**What happened**:
When using [`SORT(SEARCH(...), SUM, DESC)`](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/using-metric-math.html#metric-math-syntax) to sort the results of a SEARCH query with 10+ results, the time series are sorted based on their labels rather than the order returned by Cloudwatch.

Because the rank of the result is affixed to the label, this results in the ordering of the rank 1, 10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9 (assuming the result contains 12 time series). I suspect [this](https://github.com/grafana/grafana/blob/5f923be2bf67deadab90dcd328e84bee8a9b41cf/pkg/tsdb/cloudwatch/response_parser.go#L69) is the line that causes this.

**What you expected to happen**:

I expected Grafana to respect the order returned by Cloudwatch (1, 2, 3, ...), which helps in visualizing multiple time series when stacked.

**How to reproduce it (as minimally and precisely as possible)**:

SEARCH and SORT for metrics that return more than 10 time series and inspect the response array in Grafana.

**Anything else we need to know?**:

N/A

**Environment**:
- Grafana version: 7.0.3

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Fix sorting of CloudWatch metrics query results.

**Which issue(s) this PR fixes**:

Fixes #25494.

**Special notes for your reviewer**:
Not 100% sure if this is correct, since I'm new to this part of the code base, but I think it makes sense.

### CODE REVIEW

**Comment by kylebrandt** [comment]
FYI we do have https://pkg.go.dev/github.com/grafana/grafana-plugin-sdk-go/data?tab=doc#Fields which sorts the fields of a wideframe to be predictable, but that doesn't preserve order. I created it for a case where the order returned from the datasource was not consistent.

**Comment by aknuds1** [comment]
@kylebrandt Is that something we can use here at all, considering we're not switching to data frames as part of this PR?

File: pkg/tsdb/cloudwatch/response_parser.go [hunk 1]
```diff
@@ -23,25 +24,27 @@ func (e *cloudWatchExecutor) parseResponse(metricDataOutputs []*cloudwatch.GetMe
 		}
 
 		for _, r := range mdo.MetricDataResults {
```
Comment (kylebrandt) [inline pkg/tsdb/cloudwatch/response_parser.go:26]: I would insert something like:

```
id := *r.id
lablel := *r.Label
```

as the start of the inside of the loop. That should make it easier to read, and also if you need to do a nil check to make sure you are not dereferencing a nil pointer -  that would be the place to do it.

File: pkg/tsdb/cloudwatch/response_parser.go [hunk 2]
```diff
@@ -13,7 +13,8 @@ import (
 )
 
 func (e *cloudWatchExecutor) parseResponse(metricDataOutputs []*cloudwatch.GetMetricDataOutput, queries map[string]*cloudWatchQuery) ([]*cloudwatchResponse, error) {
-	mdr := make(map[string]map[string]*cloudwatch.MetricDataResult)
+	mdrs := make(map[string]map[string]*cloudwatch.MetricDataResult)
```
Comment (kylebrandt) [inline pkg/tsdb/cloudwatch/response_parser.go:16]: I find helpful to have comment saying what the strings are on map like this, e.g. id -> label -> result.

**Review by kylebrandt — APPROVED** [review]
Looks okay to me, but maybe make a couple assignments to clean up all the `*` to make it more readable, also be good to be safe and make sure things are not nil before referencing them

**Comment by kylebrandt** [comment]
> @kylebrandt Is that something we can use here at all, considering we're not switching to data frames as part of this PR?
> 
> I guess we can do things differently after the switch to data frames, but until then, isn't this an acceptable solution?

Ah I didn't realize that ...

**Comment by aknuds1** [comment]
> Looks okay to me, but maybe make a couple assignments to clean up all the `*` to make it more readable, also be good to be safe and make sure things are not nil before referencing them

OK thanks for the suggestion @kylebrandt, will get right on it.

File: pkg/tsdb/cloudwatch/response_parser.go (hunk 1 above)
Comment (aknuds1) [reply pkg/tsdb/cloudwatch/response_parser.go:26]: Thanks @kylebrandt, does make sense indeed and I'll take care of it.

File: pkg/tsdb/cloudwatch/response_parser_test.go [hunk 3]
```diff
@@ -60,7 +61,7 @@ func TestCloudWatchResponseParser(t *testing.T) {
 				Period: 60,
 				Alias:  "{{LoadBalancer}} Expanded",
 			}
-			series, partialData, err := parseGetMetricDataTimeSeries(resp, query)
+			series, partialData, err := parseGetMetricDataTimeSeries(mdrs, labels, query)
```
Comment (papagian) [inline pkg/tsdb/cloudwatch/response_parser_test.go:64]: It would be nice to test also that `labels` are having the respected order; therefore I would suggest breaking `parseResponse` in two separate functions.
This would be a safeguard in case the code that building labels would change in the future and would break this behaviour but this only a suggestion.

**Review by papagian — APPROVED** [review]
LGTM, I have a small suggestion.

File: pkg/tsdb/cloudwatch/response_parser_test.go (hunk 3 above)
Comment (aknuds1) [reply pkg/tsdb/cloudwatch/response_parser_test.go:64]: That should be covered through the API tests I'm adding, and things will be changed around radically anyway when the conversion to data frames is over anyway.
