### PR TITLE
Alerting: Support customizable timeout for screenshots

### LINKED ISSUE #59527: Add the ability to set a timeout for the Render Plugin request. Unified alerting.
**What happened**:

Our alerts are getting sent without screenshots because rendering takes to long.

Log from Grafana
logger=rendering renderer=http t=2022-11-30T14:58:10.118602652+07:00 level=error msg="Failed to send request to remote rendering service" error="Get \"http://grafana_render:8081/render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=ITdJiq7M7czZ3y15rFUib32T4KBTOauV&timeout=10&timezone=&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2F0K3ZBAv4z%2Flink-down-alerts%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000\": context deadline exceeded"

Log from Render Plugin
{"level":"error","message":"Request failed","stack":"Error: Request aborted\n    at onaborted (/usr/src/app/node_modules/express/lib/response.js:1052:15)\n    at Immediate._onImmediate (/usr/src/app/node_modules/express/lib/response.js:1094:9)\n    at processImmediate (node:internal/timers:466:21)","url":"/render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=HSF5bCeuXGLe7Nm7fso0XBvLuslj0K5H&timeout=10&timezone=&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2F0K3ZBAv4z%2Flink-down-alerts%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000"}

**What you expected to happen**:

A way to configure the rendering timeout. Currently it seems to be hardcoded to 10 seconds:
https://github.com/grafana/grafana/blob/2b5d12310a4eb0f0230f64ed98b1faa138d99b7e/pkg/services/ngalert/image/service.go#L21

We are working on getting the results faster, but I wonder if it were possible to make that configurable.

**How to reproduce it (as minimally and precisely as possible)**:

Create an alert that links a dashboard & panel so the alert message includes an image. The panel in question needs to have a long loading time.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.0 (latest docker image from a day ago)
- Data source type & version: MySQL
- OS Grafana is installed on: Centos7 with docker
- User OS & Browser: Fedora 36 with Firefox 
- Grafana plugins:
- Others:

_Originally posted by @apollo13 in https://github.com/grafana/grafana/discussions/53755_

### PR DESCRIPTION
**Pull request by grobinson-grafana**
**What is this feature?**

This feature adds a customizable timeout for screenshots called `capture_timeout`. The default value is 10 seconds, and the maximum value is 30 seconds. This timeout should be less than the minimum Interval of all Evaluation Groups to avoid back pressure on alert rule evaluation.

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #59527

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/ngalert/image/service_test.go [hunk 1]
```diff
@@ -30,90 +31,116 @@ func TestScreenshotImageService(t *testing.T) {
...
+			PanelID:      1,
+			Timeout:      5 * time.Second,
+		}).Return(nil, context.DeadlineExceeded)
+
+		image, err := s.NewImage(ctx, &models.AlertRule{
+			OrgID:        1,
+			UID:          "qux",
+			DashboardUID: pointer.String("qux"),
+			PanelID:      pointer.Int64(1)})
+		assert.EqualError(t, err, "context deadline exceeded")
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/image/service_test.go:143]: this can be asserted by comparing with `context.DeadlineExceeded`

**Review by yuri-tceretian — APPROVED** [review]
LGTM
