### PR TITLE
Fixed user deletion in Postgres SQL

### LINKED ISSUE #3146: User deletion in postgres fails
This fails with a syntax error.  I have a feeling it is because user is a reserved word in postgres, and would have to be double quoted, but I'm not positive that is the issue.  From the logs I have this:
ERROR:  syntax error at or near "user" at character 13
STATEMENT:  DELETE FROM user WHERE id = $1

http://stackoverflow.com/questions/22256124/cannot-create-a-database-table-named-user-in-postgresql

### PR DESCRIPTION
**Pull request by utkarshcmu**
Fixes #3146

### CODE REVIEW

File: pkg/services/sqlstore/user.go [hunk 1]
```diff
@@ -319,10 +319,15 @@ func SearchUsers(query *m.SearchUsersQuery) error {
 
 func DeleteUser(cmd *m.DeleteUserCommand) error {
 	return inTransaction(func(sess *xorm.Session) error {
-		deletes := []string{
-			"DELETE FROM star WHERE user_id = ?",
-			"DELETE FROM user WHERE id = ?",
-		}
+    var deletes [2]string
+
+    if (sess.Engine.DriverName() == "postgres") {
```
Comment (torkelo) [inline pkg/services/sqlstore/user.go]: this is not required, in other places I use the dialect abstraction to quote strings. 

https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/user.go#L280

**Comment by utkarshcmu** [comment]
Thanks for the code review, I tested this change with all the 3 databases, and the code looks better now too. :)
