### PR TITLE
Alerting: Fixes Alert list panel "ungrouped" regression

### LINKED ISSUE #66814: AlertList: Group by doesn't show items lacking the grouped label
## What happened:

Promethus is sending three alarms:
1. Labels: `{hostname=foo1, alertname=highcpu}`
2. Labels: `{hostname=foo1, alertname=lowdisk}`
3. Labels: `{alertname=othergeneralerror}`

In Grafana:
Add a **Alert list** panel
Configure **Options -> GroupMode=Custom grouping -> Group By=`hostname`**

Now the groupby acts as a filter also, showing only see the alarms which have a hostname. Making me miss one important alarm `#3` !
* hostname=foo1
   * alertname=lowdisk
   * alertname=highcpu
   

## What you expected to happen:
I want to see 2 groups in the list, including those that do not have a hostname:
* hostname=foo1
   * alertname=lowdisk
   * alertname=highcpu
* hostname=UNDEFINED
   * alertname=othergeneralerror

## Environment:
- Grafana version: 9.4.7
- Data source type & version: Prometheus

### PR DESCRIPTION
**Pull request by gillesdemey**
**What is this feature?**

A previous regression had removed the "ungrouped" group when using a "custom grouping" in the alert list panel.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/66814

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.

### CODE REVIEW

File: public/app/plugins/panel/alertlist/unified-alerting/GroupedView.tsx [hunk 1]
```diff
@@ -16,27 +16,36 @@ type Props = {
...
+        const mapKey = hasInstancesMatching ? createMapKey(groupBy, alert.labels) : UNGROUPED_KEY;
+
         const existingAlerts = groupedRules.get(mapKey) ?? [];
         groupedRules.set(mapKey, [...existingAlerts, alert]);
       });
     });
 
+    // move the "UNGROUPED" key to the last item in the Map, items are shown in insertion order
+    const ungrouped = groupedRules.get(UNGROUPED_KEY) ?? [];
+    groupedRules.delete(UNGROUPED_KEY);
```
Comment (soniaAguilarPeiron) [inline public/app/plugins/panel/alertlist/unified-alerting/GroupedView.tsx:46]: why do you need to delete before setting the new value?

**Review by soniaAguilarPeiron — APPROVED** [review]
tested locally and worked perfect!🚀
I added a non blocking comment

File: public/app/plugins/panel/alertlist/unified-alerting/GroupedView.tsx [hunk 2]
```diff
@@ -16,27 +16,36 @@ type Props = {
...
   const styles = useStyles2(getStyles);
-
   const groupBy = options.groupBy;
 
   const groupedRules = useMemo<GroupedRules>(() => {
     const groupedRules = new Map<string, Alert[]>();
 
-    const hasInstancesWithMatchingLabels = (rule: CombinedRuleWithLocation) =>
-      groupBy ? alertHasEveryLabelForCombinedRules(rule, groupBy) : true;
+    const hasInstancesWithMatchingLabels = (rule: CombinedRuleWithLocation) => {
```
[the remark this answers is not in the document]
Comment (gillesdemey) [reply public/app/plugins/panel/alertlist/unified-alerting/GroupedView.tsx:28]: I refactored this for readability; I'm not a big fan of how prettier formatted it previously and had some trouble parsing it – though that is subjective so I'm happy to revert it :)

File: public/app/plugins/panel/alertlist/unified-alerting/GroupedView.tsx (hunk 1 above)
Comment (gillesdemey) [reply public/app/plugins/panel/alertlist/unified-alerting/GroupedView.tsx:46]: If we don't delete the key first it will just overwrite the value but leave the place of the key intact (in other words, the key is already inserted so its order in the map isn't updated).

To achieve what we want here (which is to have the "ungrouped" group show up last) we have to delete the key and insert it again so its position in the map is update.

Comment (soniaAguilarPeiron) [reply public/app/plugins/panel/alertlist/unified-alerting/GroupedView.tsx:45]: got it! thank you for the explanation 👍
