### PR TITLE
Explore: Fixes Legend overflow in splitted view

### LINKED ISSUE #18044: Explore: graph legend overflows container
Screenshot 2019-07-10 at 17 51 16

Grafana v6.4.0-pre (3bbc40a)

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #18044

**Special notes for your reviewer**:

### CODE REVIEW

File: packages/grafana-ui/src/components/Legend/LegendList.tsx [hunk 1]
```diff
@@ -37,6 +37,7 @@ export const LegendList: React.FunctionComponent<LegendComponentProps> = ({
         flex-wrap: wrap;
         justify-content: space-between;
         width: 100%;
+        overflow-x: hidden;
```
Comment (dprokop) [inline packages/grafana-ui/src/components/Legend/LegendList.tsx]: From accessibility POV I think this is not the optimal solution as it's gonna crop part of the legend label. I would suggest enabling label's text wrap for LegendList component.

**Review by dprokop — CHANGES_REQUESTED** [review]

File: packages/grafana-ui/src/components/Legend/LegendList.tsx (hunk 1 above)
Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Legend/LegendList.tsx]: Thanks, thats a very valid POV. Removed it and added `pre-wrap`instead.

**Review by torkelo — APPROVED** [review]

**Review by dprokop — APPROVED** [review]
