### PR TITLE
Elasticsearch: Fix processing of logs with not-recognized time format

### LINKED ISSUE #67391: [9.5.1] [Elasticsearch Backend Data Source] "Invalid date" when viewing Elasticsearch Logs
## What happened:
Upon updating from 9.4.7 to 9.5.1, when viewing logs via our Elasticsearch datasource in Explore, we do not see log entries dated and instead see "invalid date" 

Before:
image
After:
image

If we go to a dashboard displaying logs, we can see dates there. So the problem seems localised to the Explore view.

image

## What you expected to happen:
We wanted to see dates along side our message when viewing logs in Explore

## How to reproduce it (as minimally and precisely as possible):
I downloaded a windows version of 9.4.7 and configured our datasource as approperate, taking note to set the time field name to @timestamp. I confirm it was working as expected.
I then downloaded 9.5.1, copied the data directory from 9.4.7 in to the extracted folder and executed grafana-server. Upon viewing logs, "invalid date" was in place of where we expected to see timestamps.

## Anything else we need to know?:
Our @timestamps are using the date_nano field type. Our timestamps are formatted as epoch_millis. "1682602574704.8618" is how they are stored in the data frame in 9.4.7.

Other logs that are using date field type seems to display as expected.

Kibana renders the timestamp fine.

## Environment:
- Grafana version: 9.5.1
- Data source type & version: Elasticsearch (Running 7.10.2)
- OS Grafana is installed on: Kubernetes (Reproducible on Windows)
- User OS & Browser: Windows Edge
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by ivanahuckova**
This is a bug fix for processing time field in ES on backend, when time field uses format that golang does not recognize (e.g. MM/DD/YYY, unix timestamp with nanoseconds decimal point, ...). To fix this, for log queries, we are using `fields` to get time field in `strict_date_optional_time_nanos` format that is recognizable by golang and also supports nanosecond precision.

This is only affecting logs queries.

I have added and updates tests for this. Moreover I have added `@timestamp_custom`, `@timestamp_unix` and `@timestamp_nanos` to `data.js` for easier testing of this PR, but also for easier testing of time formats in the future.

Fixes https://github.com/grafana/grafana/issues/67391

To test this:

1. Run `make devenv sources=elastic`
2. Make sure that `enableElasticsearchBackendQuerying` is set to `true`
3. Create a new elastic data source pointing to `https://localhost:9200` and for time field add `@timestamp_custom`. 
4. Run log query - you should not see `Invalid date` in time column
5. You can also switch to `@timestamp`, `@timestamp_unix`, `@timestamp_nanos` to ensure all formats work as expected.

Fixed: 

image

Current main (broken):

image

### CODE REVIEW

File: pkg/tsdb/elasticsearch/client/search_request.go [hunk 1]
```diff
@@ -99,6 +99,12 @@ func (b *SearchRequestBuilder) Sort(order SortOrder, field string, unmappedType
 	return b
 }
 
+// AddTimeFieldWithStandardizedFormat adds a field for time field with standardized value
```
Comment (ivanahuckova) [inline pkg/tsdb/elasticsearch/client/search_request.go:102]:
```suggestion
// AddTimeFieldWithStandardizedFormat adds a time field to fields with standardized time format
```

**Review by gabor — APPROVED** [review]
LGTM 👍  nice
