### PR TITLE
Dashboard: avoid and correct invalid date ranges (i.e. to < from)

### LINKED ISSUE #34424: Time ranges: "to" allowed to be less than "from"
**What happened**:

By using the URL params or even manually filing the date range selector, inverted date ranges are allowed, which are then also saved to local storage.

**What you expected to happen**:

"To" should always be equal to or greater than "from".

**How to reproduce it (as minimally and precisely as possible)**:

- for example, use "from=now" and "to=now-1h" as URL params in a dashboard (same applies for absolute times)
- same can be achieved using the input fields

Screenshot 2021-05-19 at 17 03 43

### PR DESCRIPTION
**Pull request by fabio-silva**
**What this PR does / why we need it**:

Avoids invalid date ranges from the picker inputs. Also, automatically inverts date ranges from the URL if needed.

**Which issue(s) this PR fixes**:

Fixes #34424

### CODE REVIEW

File: public/app/features/dashboard/services/TimeSrv.ts [hunk 1]
```diff
@@ -56,6 +56,17 @@ export class TimeSrv {
 
     this.initTimeFromUrl();
     this.parseTime();
+    const range = rangeUtil.convertRawToRange(this.time, this.dashboard ? this.dashboard.getTimezone() : undefined);
```
Comment (atymchuk) [inline public/app/features/dashboard/services/TimeSrv.ts:59]:
```suggestion
    const range = rangeUtil.convertRawToRange(this.time, this.dashboard?.getTimezone());
```

File: public/app/features/dashboard/services/TimeSrv.ts [hunk 2]
```diff
@@ -56,6 +56,17 @@ export class TimeSrv {
...
+
+    if (range.to.isBefore(range.from)) {
```
Comment (atymchuk) [inline public/app/features/dashboard/services/TimeSrv.ts:61]: @fabio-silva Shouldn't this come after line 72, since that one will clone the update time, not the original one?

**Review by ademidoff — CHANGES_REQUESTED** [review]

File: public/app/features/dashboard/services/TimeSrv.ts (hunk 1 above)
Comment (fabio-silva) [reply public/app/features/dashboard/services/TimeSrv.ts]: 👍

File: public/app/features/dashboard/services/TimeSrv.ts (hunk 2 above)
Comment (fabio-silva) [reply public/app/features/dashboard/services/TimeSrv.ts:65]: well spotted, thanks 👍

File: packages/grafana-ui/src/components/TimePicker/TimeRangePicker/TimeRangeForm.tsx [hunk 3]
```diff
@@ -73,6 +73,10 @@ export const TimeRangeForm: React.FC<Props> = (props) => {
       const raw: RawTimeRange = { from: from.value, to: to.value };
       const timeRange = rangeUtil.convertRawToRange(raw, timeZone);
 
+      if (!timeRange.from.isBefore(timeRange.to)) {
+        return;
+      }
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/TimePicker/TimeRangePicker/TimeRangeForm.tsx:78]: This is a great check, but this is not a great user experience. Maybe we should warn the user that they have entered an incorrect order and make the form invalid?

**Review by hugohaggmark — COMMENTED** [review]
Thank you for taking the time to add this contribution. I think it looks good, but I left a comment about the user experience that is worth exploring.

File: packages/grafana-ui/src/components/TimePicker/TimeRangePicker/TimeRangeForm.tsx (hunk 3 above)
Comment (fabio-silva) [reply packages/grafana-ui/src/components/TimePicker/TimeRangePicker/TimeRangeForm.tsx:78]: Seems a great suggestion @hugohaggmark ! 
Where do you think we should put that warning?

Comment (hugohaggmark) [reply packages/grafana-ui/src/components/TimePicker/TimeRangePicker/TimeRangeForm.tsx:78]: Sorry for the late response but I think we would need to refactor this form quite a bit so we can present an error message directly in the form inputs if the data ranges are reversed. Let me know if you need help doing this.

**Comment by hugohaggmark** [comment]
@fabio-silva any progress on this?

**Comment by fabio-silva** [comment]
> @fabio-silva any progress on this?

@hugohaggmark Yes, only now I had the time to start working on this. I'll ping you once I make those changes, of if I need help here. Thanks!

**Comment by fabio-silva** [comment]
@hugohaggmark  First fix tentative 👍

**Comment by fabio-silva** [comment]
(Only using `from.invalid` instead of having to cross validate both fields every time, I think only one error might be sufficient to sinalize users that the range is not valid)

File: packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimeRangeForm.tsx [hunk 4]
```diff
@@ -86,6 +86,28 @@ export const TimeRangeForm: React.FC<Props> = (props) => {
     [timeZone]
   );
 
+  const onFromChange = useCallback(
+    (event: FormEvent<HTMLInputElement>) => {
+      const newState = eventToState(event, false, timeZone);
+      const invalid = isRangeInvalid(newState, to, timeZone);
+
+      newState.invalid = newState.invalid || invalid;
```
Comment (mckn) [inline packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimeRangeForm.tsx:94]: nit: instead of doing this you can change the `eventToState` function directly to include your range check.

**Comment by mckn** [comment]
Awesome work on this! I think you can do some refactoring to clean up the code in the TimeRangeForm a bit to make it easier to follow. It would be good to have the logic for `invalid` gathered in the same place.

Also, if you want to get bonus points you can add some tests for this scenario in the `TimeRangeForm.test.tsx` (optional).

**Review by hugohaggmark — COMMENTED** [review]
Skilled work, on those last changes 🎉  I only have one small nit and that is the message that is shown. It's ok, but it's not super clear what is wrong when `to` is before `from`.
image

**Comment by fabio-silva** [comment]
Thanks for the suggestions!
I added those improvements there now.

**Review by mckn — APPROVED** [review]
Great work on this!! Looks really nice 🙌🏻
