### PR TITLE
StatPanel: Fix problem where string values where always green

### LINKED ISSUE #27516: Stat panel font color always green for non numeric value
**What happened**:
Stat panel allows to change threshold color, and the default for the base is green. But when the result cannot convert to the number table, the result shows always green, even if I show the base color to another one. In the example, I had converted a timestamp to varchar so I could format it to show only hours. So this text cannot have the color changed, causing confusion on the dashboard.

image

**What you expected to happen**:
When I change the base color to black, for example, and having no other threshold, I was expecting the content to be always black and not green.

**How to reproduce it (as minimally and precisely as possible)**:
Add a text field to Stat panel and change the base color to black. It will remain green.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.1.5 (9893b8c53d)
- Data source type & version: PostgreSQL 11 w/ Timescale
- OS Grafana is installed on: Ununtu 18.04
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins: Stat
- Others:

### PR DESCRIPTION
**Pull request by peterholmberg**
**What this PR does / why we need it**:
As the issue describes, thresholds are only applied to numeric values right now (makes sense) but it also means that if you change the base color, string values will be green despite what you set the base color to.

**Which issue(s) this PR fixes**:

Fixes #27516

**Special notes for your reviewer**:
This is a proposed solution and to be honest I'm not sure if we should use thresholds this way? And should we include all FieldTypes?

### CODE REVIEW

File: packages/grafana-ui/src/utils/standardEditors.tsx [hunk 1]
```diff
@@ -146,7 +146,7 @@ export const getStandardFieldConfigs = () => {
         { value: 80, color: 'red' },
       ],
     },
-    shouldApply: field => field.type === FieldType.number,
```
Comment (torkelo) [inline packages/grafana-ui/src/utils/standardEditors.tsx:149]: Might as well return true here always

**Review by torkelo — APPROVED** [review]
Looks good! think it might be best to just always apply thresholds

**Review by ryantxu — APPROVED** [review]
