### PR TITLE
InfluxDB: InfluxQL query editor: fix retention policy handling

### LINKED ISSUE #35966: Grafana 8 InfluxDB retention selection problem
**What happened**:
Problem with InfluxDB retention selection when multiple retention is present on db.
I have a db "test" with 2 retention: autogen and RP1
the combobox concatenates the 2 retention: autogenRP1

**What you expected to happen**:
combobox with retention list:
autogen
RP1

**How to reproduce it (as minimally and precisely as possible)**:
1. create database test (influxdb 1.7.8) 
2. CREATE RETENTION POLICY "RP1"  ON test DURATION 365d REPLICATION 1
> show retention policies on test
```
name    duration  shardGroupDuration replicaN default
----    --------  ------------------ -------- -------
autogen 0s        168h0m0s           1        true
RP1     8760h0m0s 168h0m0s           1        false
```

When I select the retention in the combobox I see a single string with the 2 concatenated retention autogenRP1 (see image)

image

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: influxdb 1.7.8
- OS Grafana is installed on: Ubuntu 16.04.6 LTS
- User OS & Browser: Ubuntu 20.04.2 LTS - Chrome 
- Grafana plugins: ACE.SVG, D3 Gauge and standard plugin
- Others:

### PR DESCRIPTION
**Pull request by gabor**
fixes https://github.com/grafana/grafana/issues/35966

there is a bug in the retention-policy handling code. the code wants to add a new item at the beginning of an array, and misses the spread-operator.

so, it should work like this:
a. if you have a retention-policy called `default` then the list of retention policies is untouched.
b. if you do not have a retention-policy called `default`, then we add the option `default` to the beginning of the list. so, for example you have policies `one` and `two`, the list should become `["default", "one", "two"]`. unfortunately, it became `["default", ["one", "two"]]`.

how to test:
- `make devenv sources=influxdb1` should create the datasource you need
- go to `explore`, choose the `gdev-influxdb1-influxql` datasource
- open the first dropdown next to `FROM` (the one that says `default`)
- you should see 5 options: "default", "autogen", "bar", "1m_avg", "5m_avg" (in the wrong version the options shown were "default" and "autogenbar1m_avg5m_avg")

### CODE REVIEW

File: public/app/plugins/datasource/influxdb/components/VisualInfluxQLEditor/FromSection.tsx [hunk 1]
```diff
@@ -35,7 +35,7 @@ export const FromSection = ({
     // if `default` does not exist in the list of policies, we add it
     const allPoliciesWithDefault = allPolicies.some((p) => p === 'default')
       ? allPolicies
-      : [DEFAULT_POLICY, allPolicies];
+      : [DEFAULT_POLICY, ...allPolicies];
 
     return allPoliciesWithDefault.map(toSelectableValue);
```
Comment (gabor) [inline public/app/plugins/datasource/influxdb/components/VisualInfluxQLEditor/FromSection.tsx:40]: at this point typescript should have catched it, `toSelectableValue` needs a `string`. i will investigate later why it did not catch it.

Comment (gabor) [reply public/app/plugins/datasource/influxdb/components/VisualInfluxQLEditor/FromSection.tsx:40]: nevermind, found the reason. we are not running currently with `strict:true` in the `tsconfig.json` file, so not all checks happen.

**Review by zoltanbedi — APPROVED** [review]
lgtm 🌞
