### PR TITLE
Table: Proper handling of json data with dataframes

### LINKED ISSUE #19531: Raw Document on Elasticsearch Datasource broken in Table
**What happened**: Raw Document Queries don't show the json

**What you expected to happen**: That Raw Document shows the json as in older versions (< 6.4.0)

**How to reproduce it (as minimally and precisely as possible)**: 

1. Add a Table to the Dashboard
2. Select Raw Document as Metric

**Anything else we need to know?**:

Worked in Grafana 6.3.5 and lower. When selecting Json Data in Table Transform it says [null,null] for every entry instead of the json.

**Environment**:
- Grafana version: 6.4.0
- Data source type & version: Elasticsearch 7.3.0
- OS Grafana is installed on: Alpine (Docker)
- User OS & Browser: Windows10, Chrome
- Grafana plugins: Pie Chart, Traffic Light
- Others:

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
When using Raw Document query with Elasticsearch there's a special response from datasource that is used which includes a `type` field with the value `json`. In the table panel there is a transformation for JSON data which up until this fix didn't work at all due to the new data structure we call data frames.

Verified using gdev dashboard/Datasource tests - Elasticsearch v7 and panel "ES Log query"
- renders result in table as before using correct selected columns
- Edit panel the `Table Transform` is `JSON data` and the columns selected in panel model are displayed below. Click the `+` icon gives you a list of all the available fields in the json document.
- Hover a cell in the table allows you to filter for and out using adhoc-filters

**Which issue(s) this PR fixes**:
Fixes #19531

**Special notes for your reviewer**:
Shouldn't be any other datasource using the docs type, at least not in core grafana. Possibly other plugins?

### CODE REVIEW

File: public/app/plugins/panel/table/transformers.ts [hunk 1]
```diff
@@ -209,8 +211,11 @@ transformers['json'] = {
       const tableCol: any = { text: column.text };
 
       // if filterable data then set columns to filterable
-      if (data.length > 0 && data[0].filterable) {
-        tableCol.filterable = true;
+      if (data.length > 0) {
+        const dataFrame = toDataFrame(data[0]);
+        if (dataFrame.meta && dataFrame.fields[0].config.filterable) {
+          tableCol.filterable = true;
+        }
```
Comment (marefr) [inline public/app/plugins/panel/table/transformers.ts]: All of this feels really messy. Suggestion of improvement very welcome.

**Review by hugohaggmark — APPROVED** [review]
LGTM, works as expected! Left a minor comment and couldn't find any small way to refactor JSON transformer. Could probably be good to cover it with tests and then redo it from scratch :)

File: public/app/plugins/panel/table/transformers.ts [hunk 2]
```diff
@@ -209,8 +211,11 @@ transformers['json'] = {
       const tableCol: any = { text: column.text };
 
       // if filterable data then set columns to filterable
-      if (data.length > 0 && data[0].filterable) {
-        tableCol.filterable = true;
+      if (data.length > 0) {
+        const dataFrame = toDataFrame(data[0]);
```
Comment (torkelo) [inline public/app/plugins/panel/table/transformers.ts]: Don't you convert it to DataFrame already in the toLegacy function (convertJSONDocumentDataToDataFrame)

File: public/app/plugins/panel/table/transformers.ts (hunk 1 above)
Comment (ryantxu) [reply public/app/plugins/panel/table/transformers.ts]: kill them all!!!!   I hope we can replace all of this with a new table panel and using 'transformers' rather than the one-off transformers in table panel that are calculated a few ways :(

File: packages/grafana-data/src/dataframe/processDataFrame.ts [hunk 3]
```diff
@@ -217,6 +244,8 @@ export const guessFieldTypes = (series: DataFrame): DataFrame => {
 
 export const isTableData = (data: any): data is DataFrame => data && data.hasOwnProperty('columns');
 
+export const isJSONDocumentData = (data: any): data is DataFrame => data && data.meta && data.meta.json;
```
Comment (ryantxu) [inline packages/grafana-data/src/dataframe/processDataFrame.ts]: do we need this in `@grafana/data`?  can it be isolated to just the table panel?  I don't want to encourage that this gets used anywhere new

File: packages/grafana-data/src/dataframe/processDataFrame.ts [hunk 4]
```diff
@@ -241,6 +270,11 @@ export const toDataFrame = (data: any): DataFrame => {
     return new MutableDataFrame(data as DataFrameDTO);
   }
 
+  // Handle legacy docs/json type
+  if (data.hasOwnProperty('type') && data.type === 'docs') {
+    return convertJSONDocumentDataToDataFrame(data);
+  }
+
```
Comment (ryantxu) [inline packages/grafana-data/src/dataframe/processDataFrame.ts]: Is the only difference between this and `convertTimeSeriesToDataFrame` that it adds:
```
    meta: { json: true },
```
If so, do we need the new function?  or just add a note about deprecated/legacy docs mode?

Comment (marefr) [reply packages/grafana-data/src/dataframe/processDataFrame.ts]: No, `convertTimeSeriesToDataFrame` expects a time and value besides some other differences. See https://github.com/grafana/grafana/pull/19596/files#diff-0600e6a1b61c8024cc2e5cc95d22c54bR130-R156

File: public/app/plugins/panel/table/transformers.ts (hunk 1 above)
Comment (marefr) [reply public/app/plugins/panel/table/transformers.ts]: Yeah, but the point of this PR is to mainly resolve the critical bug. We have to create a separate issue to do bigger enhancement/migrations eventually.

File: packages/grafana-data/src/dataframe/processDataFrame.ts (hunk 3 above)
Comment (marefr) [reply packages/grafana-data/src/dataframe/processDataFrame.ts]: Sure. WIll fix

File: public/app/plugins/panel/table/transformers.ts (hunk 2 above)
Comment (marefr) [reply public/app/plugins/panel/table/transformers.ts]: Can you add some more information, do you want me to enforce the type of `data` argument to be an array of data frames?

Comment (torkelo) [reply public/app/plugins/panel/table/transformers.ts]: Sorry, confused, just not sure why we convert it back to DataFrame here? Seems like we convert it to toDataFrame (in runRequest) -> legacy (in MetricsPanelCtrl), then here back to DataFrame. 

Do we need this conversion?

Comment (marefr) [reply public/app/plugins/panel/table/transformers.ts]: Hopefully fixed now

File: packages/grafana-data/src/dataframe/processDataFrame.ts [hunk 5]
```diff
@@ -288,6 +320,16 @@ export const toLegacyResponseData = (frame: DataFrame): TimeSeries | TableData =
     }
   }
 
+  if (frame.meta && frame.meta.json) {
+    return {
+      alias: fields[0].name || frame.name,
+      target: fields[0].name || frame.name,
+      datapoints: fields[0].values.toArray(),
+      filterable: fields[0].config ? fields[0].config.filterable : undefined,
+      type: 'docs',
```
Comment (marefr) [inline packages/grafana-data/src/dataframe/processDataFrame.ts]: This isn't really a `TimeSeries`, but not sure if this is okay or not?

Comment (torkelo) [reply packages/grafana-data/src/dataframe/processDataFrame.ts]: Think this is ok for now until we make table panel work with DataFrame directly

**Review by torkelo — APPROVED** [review]
Looks good!
