### PR TITLE
Public Dashboards: use intervalMs and maxDataPoints from request

### LINKED ISSUE #53499: Public Dashboard Step size does not match logged in version
**What happened**:
I have minutely metrics which I have on a dashboard. When I go to the public dashboard link, it shows me the metric at a resolution of 5m instead of 1m.

The two prometheus queries on this dashboard don't have any duration and the min step is `auto`:
```
sum(player_count)

lobby_count
```

Logged in dashboard:
image

Navigating to the public dashboard link
image

**What you expected to happen**:
The metrics on the public dashboard should appear identical to the logged in version.

**How to reproduce it (as minimally and precisely as possible)**:
The minimal reproduction is as follows, I believe:
1. Create a new dashboard and add  panel with a prometheus query of `0`
2. Hover over the graph and see that the step size changes in increments of 30s
3. Enable public dashboard and go to the link. When hovering over the chart, the timestamp increments in steps of 5 minutes.

**Anything else we need to know?**:

**Environment**:
- Grafana version: docker image grafana/grafana:9.1.0-beta1 digest: 17bf8bd0e7f0
- Data source type & version: prometheus 2.37.0 on arm64, revision b41e0750abf5cc18d8233161560731de05199330
- OS Grafana is installed on: docker
host:
$ uname -a
`Linux arm1 5.15.0-1013-oracle #17~20.04.1-Ubuntu SMP Mon Jul 4 05:29:46 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`
- User OS & Browser: Windows 10, brave browser
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by evictorero**
**What this PR does / why we need it**:
* Remove unused data sent from the frontend when querying public dashboard panels
* Add `intervalMs` and `maxDataPoints` calculated on the frontend when request public dashboard panel queries

**Which issue(s) this PR fixes**:

Fixes #53499

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/publicdashboards/api/api.go [hunk 1]
```diff
@@ -149,6 +149,11 @@ func (api *Api) QueryPublicDashboard(c *models.ReqContext) response.Response {
 		return response.Error(http.StatusBadRequest, "invalid panel ID", err)
 	}
 
+	reqDTO := &PublicDashboardQueryDTO{}
```
Comment (jalevin) [inline pkg/services/publicdashboards/api/api.go:152]: Is this enough validation of user input? Do we need to sanity check these values? What happens if we get 0, -1, or 999999999 ?

Comment (jalevin) [reply pkg/services/publicdashboards/api/api.go:152]: Also- for the sake of discussion, our original security model relies on not taking user input.

How complicated is it to calculate this on the backend?

File: public/app/features/dashboard/services/PublicDashboardDataSource.ts [hunk 2]
```diff
@@ -57,30 +57,15 @@ export class PublicDashboardDataSource extends DataSourceApi<any> {
    * Ideally final -- any other implementation may not work as expected
    */
   query(request: DataQueryRequest<any>): Observable<DataQueryResponse> {
```
Comment (jalevin) [inline public/app/features/dashboard/services/PublicDashboardDataSource.ts:59]: Clean! Nice refactor

File: pkg/services/publicdashboards/api/api.go (hunk 1 above)
Comment (evictorero) [reply pkg/services/publicdashboards/api/api.go:153]: Added validation for negative values in the request and calculate safe values for interval.

File: pkg/services/publicdashboards/api/api.go [hunk 3]
```diff
@@ -159,11 +169,12 @@ func (api *Api) QueryPublicDashboard(c *models.ReqContext) response.Response {
 		return response.Error(http.StatusInternalServerError, "could not fetch public dashboard", err)
 	}
 
-	reqDTO, err := api.PublicDashboardService.BuildPublicDashboardMetricRequest(
+	builtReqDTO, err := api.PublicDashboardService.BuildPublicDashboardMetricRequest(
```
Comment (owensmallwood) [inline pkg/services/publicdashboards/api/api.go:172]: maybe `metricReqDTO` ?

File: pkg/services/publicdashboards/api/api.go [hunk 4]
```diff
@@ -239,3 +250,15 @@ func toJsonStreamingResponse(features *featuremgmt.FeatureManager, qdr *backend.
 
 	return response.JSONStreaming(statusCode, qdr)
 }
+
+func validateRequest(req *PublicDashboardQueryDTO) error {
```
Comment (owensmallwood) [inline pkg/services/publicdashboards/api/api.go:254]: We already have a file for putting request validation at `pkg/services/publicdashboards/validation/validator.go`. Could we put this in there?

**Review by owensmallwood — APPROVED** [review]
Looks good 👍 Only thing I'd change is moving the request validation out to the services validation folder

File: pkg/services/publicdashboards/api/api.go [hunk 5]
```diff
@@ -149,6 +150,15 @@ func (api *Api) QueryPublicDashboard(c *models.ReqContext) response.Response {
 		return response.Error(http.StatusBadRequest, "invalid panel ID", err)
 	}
```
Comment (jalevin) [inline pkg/services/publicdashboards/api/api.go:152]: Let's get the dashboard first and error if that fails for some reason

File: pkg/services/publicdashboards/api/api.go (hunk 4 above)
Comment (jalevin) [reply pkg/services/publicdashboards/api/api.go:254]: In principle I agree with this, the one caveat is that we're making additional queries even if the request is not valid, however, I think the trade off of having clean separation of logic is worthwhile. I just want to acknowledge we're making that tradeoff here.

File: pkg/services/publicdashboards/service/service.go [hunk 6]
```diff
@@ -167,23 +172,31 @@ func (pd *PublicDashboardServiceImpl) updatePublicDashboardConfig(ctx context.Co
 
 // BuildPublicDashboardMetricRequest merges public dashboard parameters with
 // dashboard and returns a metrics request to be sent to query backend
-func (pd *PublicDashboardServiceImpl) BuildPublicDashboardMetricRequest(ctx context.Context, dashboard *models.Dashboard, publicDashboard *PublicDashboard, panelId int64) (dtos.MetricRequest, error) {
+func (pd *PublicDashboardServiceImpl) BuildPublicDashboardMetricRequest(ctx context.Context, dashboard *models.Dashboard, publicDashboard *PublicDashboard, panelId int64, reqDTO *PublicDashboardQueryDTO) (dtos.MetricRequest, error) {
 	if !publicDashboard.IsEnabled {
```
Comment (jalevin) [inline pkg/services/publicdashboards/service/service.go:176]: This code is only called from the api which calls GetDashboard(accessToken) and returns ErrPublicDashboardNotFound so this code would not actually get hit. I'm wondering if for clarity, it's worth removing the isEnabled check in this method now that we have the additional complexity of the PublicDashboardQueryInterval

File: pkg/services/publicdashboards/api/api.go (hunk 5 above)
Comment (jalevin) [inline pkg/services/publicdashboards/api/api.go:152]: Let's get the dashboard first and error if that fails for some reason

File: pkg/services/publicdashboards/service/service.go [hunk 7]
```diff
@@ -224,3 +237,25 @@ func GenerateAccessToken() (string, error) {
 
 	return fmt.Sprintf("%x", token[:]), nil
 }
+
+func (pd *PublicDashboardServiceImpl) getSafeIntervalAndMaxDataPoints(reqDTO *PublicDashboardQueryDTO, ts *TimeSettings) (int64, int64) {
```
Comment (jalevin) [inline pkg/services/publicdashboards/service/service.go:241]: I think this makes sense. Could we add documentation here that describes what we deem safe to be?

File: pkg/services/publicdashboards/service/service.go [hunk 8]
```diff
@@ -167,23 +172,31 @@ func (pd *PublicDashboardServiceImpl) updatePublicDashboardConfig(ctx context.Co
...
 
 	queriesByPanel := models.GroupQueriesByPanelId(dashboard.Data)
 
-	if _, ok := queriesByPanel[panelId]; !ok {
+	queries, ok := queriesByPanel[panelId]
+	if !ok {
 		return dtos.MetricRequest{}, ErrPublicDashboardPanelNotFound
 	}
 
 	ts := publicDashboard.BuildTimeSettings(dashboard)
```
Comment (jalevin) [inline pkg/services/publicdashboards/service/service.go:187]: nit: slight reorg of blocks in this method and a little documentation

image

File: pkg/services/publicdashboards/api/api.go [hunk 9]
```diff
@@ -239,3 +250,15 @@ func toJsonStreamingResponse(features *featuremgmt.FeatureManager, qdr *backend.
 
 	return response.JSONStreaming(statusCode, qdr)
```
Comment (jalevin) [inline pkg/services/publicdashboards/api/api.go:251]: I think this is the flow I would think of for this method (includes inline comments I left on this review as well). I added here because they're not really organized well.. so hopefully this better articulates what I'm thinking from the top down.

image

**Review by jalevin — COMMENTED** [review]
Great approach and awesome job on the archaeology! Some general naming/organization things and then I think this will be good to go.

File: pkg/services/publicdashboards/api/api.go (hunk 4 above)
Comment (evictorero) [reply pkg/services/publicdashboards/api/api.go:254]: I like this idea, I can't see that caveat. What additional query we will be doing if we move this function?

File: pkg/services/publicdashboards/service/service.go (hunk 6 above)
Comment (evictorero) [reply pkg/services/publicdashboards/service/service.go:176]: Agree, we shouldn't call this method if the pubdash is disabled. Moved this check to the upper layer. I don't think this struct implies we have the public dashboard info because it is a DTO, it only implies we receive a request with data from a client.

File: pkg/services/publicdashboards/api/api.go (hunk 5 above)
Comment (evictorero) [reply pkg/services/publicdashboards/api/api.go:152]: I don't think we should do any query before validating that a path param received is a valid integer

File: pkg/services/publicdashboards/api/api.go (hunk 9 above)
Comment (evictorero) [reply pkg/services/publicdashboards/api/api.go]: I made some changes and answered some comments. Let's talk about this with the new structure in mind.

File: pkg/services/publicdashboards/api/api.go [hunk 10]
```diff
@@ -209,24 +184,8 @@ func handleDashboardErr(defaultCode int, defaultMsg string, err error) response.
...
-	if errors.As(err, &badQuery) {
-		return response.Error(http.StatusBadRequest, util.Capitalize(badQuery.Message), err)
-	}
-
-	if errors.Is(err, backendplugin.ErrPluginNotRegistered) {
-		return response.Error(http.StatusNotFound, "Plugin not found", err)
-	}
-
-	return response.Error(http.StatusInternalServerError, "Query data error", err)
+func handlePublicDashboardErr(err error) response.Response {
```
Comment (jalevin) [inline pkg/services/publicdashboards/api/api.go:187]: Nice! Clever and simple.

File: pkg/services/publicdashboards/api/api.go [hunk 11]
```diff
@@ -157,35 +151,16 @@ func (api *Api) QueryPublicDashboard(c *models.ReqContext) response.Response {
...
-	if err != nil {
-		return handleDashboardErr(http.StatusInternalServerError, "Failed to get queries for public dashboard", err)
+	reqDTO := &PublicDashboardQueryDTO{}
+	if err = web.Bind(c.Req, reqDTO); err != nil {
+		return response.Error(http.StatusBadRequest, "bad request data", err)
 	}
 
-	// Build anonymous user for the request
-	anonymousUser, err := api.PublicDashboardService.BuildAnonymousUser(c.Req.Context(), dashboard)
+	resp, err := api.PublicDashboardService.GetQueryDataResponse(c.Req.Context(), c.SkipCache, reqDTO, panelId, web.Params(c.Req)[":accessToken"])
```
Comment (jalevin) [inline pkg/services/publicdashboards/api/api.go:159]: nit/thought: Now that we're only calling this one method `GetQueryDataResponse` I wonder if there is a better name? `QueryData` or something.

File: pkg/services/publicdashboards/service/service.go [hunk 12]
```diff
@@ -180,25 +189,67 @@ func (pd *PublicDashboardServiceImpl) updatePublicDashboardConfig(ctx context.Co
...
 
-// BuildPublicDashboardMetricRequest merges public dashboard parameters with
-// dashboard and returns a metrics request to be sent to query backend
-func (pd *PublicDashboardServiceImpl) BuildPublicDashboardMetricRequest(ctx context.Context, dashboard *models.Dashboard, publicDashboard *PublicDashboard, panelId int64) (dtos.MetricRequest, error) {
+func (pd *PublicDashboardServiceImpl) GetQueryDataResponse(ctx context.Context, skipCache bool, reqDTO *PublicDashboardQueryDTO, panelId int64, accessToken string) (*backend.QueryDataResponse, error) {
+	if err := validation.ValidateQueryPublicDashboardRequest(reqDTO); err != nil {
+		return nil, ErrPublicDashboardBadRequest
+	}
+
+	publicDashboard, dashboard, err := pd.GetPublicDashboard(ctx, accessToken)
```
Comment (jalevin) [inline pkg/services/publicdashboards/service/service.go:197]: service.GetPublicDashboard checks for IsEnabled. However, I like that it's explicit on this method. I'm a little torn between leaving as is vs switching to call store.GetPublicDashboard and checking for nil/IsEnabled directly in this method.

File: pkg/services/publicdashboards/service/service.go [hunk 13]
```diff
@@ -180,25 +189,67 @@ func (pd *PublicDashboardServiceImpl) updatePublicDashboardConfig(ctx context.Co
...
+		return nil, err
+	}
+
+	anonymousUser, err := pd.BuildAnonymousUser(ctx, dashboard)
+	if err != nil {
+		return nil, err
+	}
 
-	if _, ok := queriesByPanel[panelId]; !ok {
+	resp, err := pd.QueryDataService.QueryDataMultipleSources(ctx, anonymousUser, skipCache, metricReqDTO, true)
```
Comment (jalevin) [inline pkg/services/publicdashboards/service/service.go:222]: We can return this method instead of assigning to vars.

File: pkg/services/publicdashboards/service/service.go [hunk 14]
```diff
@@ -180,25 +189,67 @@ func (pd *PublicDashboardServiceImpl) updatePublicDashboardConfig(ctx context.Co
...
+	if err != nil {
+		return nil, err
+	}
+
+	return resp, nil
+}
+
+// BuildPublicDashboardMetricRequest merges public dashboard parameters with
+// dashboard and returns a metrics request to be sent to query backend
+func (pd *PublicDashboardServiceImpl) buildPublicDashboardMetricRequest(ctx context.Context, dashboard *models.Dashboard, publicDashboard *PublicDashboard, panelId int64, reqDTO *PublicDashboardQueryDTO) (dtos.MetricRequest, error) {
```
Comment (jalevin) [inline pkg/services/publicdashboards/service/service.go:232]: Nice! This feels like a win.

File: pkg/services/publicdashboards/service/service.go [hunk 15]
```diff
@@ -240,6 +291,35 @@ func GenerateAccessToken() (string, error) {
 	return fmt.Sprintf("%x", token[:]), nil
 }
 
+// intervalMS and maxQueryData values are being calculated on the frontend for regular dashboards
```
Comment (jalevin) [inline pkg/services/publicdashboards/service/service.go:294]: Yes! This is a great explanation.

**Review by jalevin — APPROVED** [review]
Great work. A couple very minor things to think through, but for launch!

File: pkg/services/publicdashboards/service/service.go (hunk 12 above)
Comment (evictorero) [reply pkg/services/publicdashboards/service/service.go:197]: I won't put that in the store since it is business logic. We can keep it inside `GetPublicDashbaord` I will remove it from this method.
