### PR TITLE
Panel Header Fix: Implement new Panel Header on Angular Panels 

### LINKED ISSUE #66282: Implement new Panel Header on Angular Panels

### PR DESCRIPTION
**Pull request by axelavargas**
**What is this feature?**

Use the new panel header on angular panels.

- [x]  Research effort required to use `PanelChrome` on `PanelChromeAngular`
- [x]  Implement `PanelChrome` on angular panels
>  Idea from Torkel: refactor out a bit of code from PanelStateWrapper (something like getPanelChromeProps(panel, plugin, data)) so we can share some logic between PanelStateWrapper and PanelChromeAngular
- [x]  Use helper function  `getPanelChromeProps` on `PanelStateWrapper`
- [x] Make sure e2e and unit tests pass
- [ ] Make sure the new flow is not impacting the e2e test from plugin examples https://github.com/grafana/grafana-plugin-examples (If yes, fix it)

**Why do we need this feature?**

Prevent a mix of UI on dashboards that have angular and react panels

**Who is this feature for?**

everyone

**Which issue(s) does this PR fix?**:

Fixes #66282

**Special notes for your reviewer:**
- Should I target this change to milestone `v10`? or `9.5.x`?

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx [hunk 1]
```diff
@@ -179,9 +183,11 @@ export class PanelChromeAngularUnconnected extends PureComponent<Props, State> {
     const { dashboard, panel, isViewing, isEditing, plugin } = this.props;
     const { errorMessage, data } = this.state;
     const { transparent } = panel;
-
     const alertState = data.alertState?.state;
 
+    const panelChromeProps = getPanelChromeProps(panel, dashboard, data);
+    const panelHeaderTitleItemsProps = panelChromeProps.getPanelHeaderTitleItemsProps();
```
Comment (dprokop) [inline public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx:189]: 👍

File: public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx [hunk 2]
```diff
@@ -196,29 +202,69 @@ export class PanelChromeAngularUnconnected extends PureComponent<Props, State> {
...
+          menu={this.props.hideMenu ? undefined : menu}
+          dragClass={dragClass}
+          dragClassCancel="grid-drag-cancel"
+          padding={panelChromeProps.padding}
+          hoverHeaderOffset={hoverHeaderOffset}
+          hoverHeader={panelChromeProps.hasOverlayHeader()}
+          displayMode={transparent ? 'transparent' : 'default'}
+          onCancelQuery={panelChromeProps.onCancelQuery}
+        >
+          {(width, height) => <div ref={(element) => (this.element = element)} className="panel-height-helper" />}
```
Comment (dprokop) [inline public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx:240]:
```suggestion
          {() => <div ref={(element) => (this.element = element)} className="panel-height-helper" />}
```

File: public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx [hunk 3]
```diff
@@ -196,29 +202,69 @@ export class PanelChromeAngularUnconnected extends PureComponent<Props, State> {
...
+        </PanelChrome>
+      );
+    } else {
+      return (
+        <div
+          className={containerClassNames}
+          data-testid={selectors.components.Panels.Panel.title(panel.title)}
+          aria-label={selectors.components.Panels.Panel.containerByTitle(panel.title)}
```
Comment (dprokop) [inline public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx:248]: Wonder if lack of these when using the new PanelChrome wouldn't cause some test to fail?

**Review by dprokop — COMMENTED** [review]
@axelavargas tested this with http://localhost:3000/d/pttable/panel-tests-table?orgId=1 and http://localhost:3000/d/5SdHCadmz/panel-tests-graph?orgId=1 I couldn't find any issues so far.

**Review by torkelo — COMMENTED** [review]
This looks really good but looks like you can move a lot more of the props to getPanelChromeProps

File: public/app/features/dashboard/utils/getPanelChromeProps.ts [hunk 4]
```diff
@@ -0,0 +1,100 @@
+import { LinkModel, PanelData, renderMarkdown } from '@grafana/data';
+import { getTemplateSrv, locationService, reportInteraction } from '@grafana/runtime';
+import { PanelPadding } from '@grafana/ui';
+import { InspectTab } from 'app/features/inspector/types';
+import { getPanelLinksSupplier } from 'app/features/panel/panellinks/linkSuppliers';
+import { plugin } from 'app/plugins/panel/alertGroups/module';
+
+import { DashboardModel, PanelModel } from '../state';
+
+export function getPanelChromeProps(panel: PanelModel, dashboard: DashboardModel, data: PanelData) {
```
[the remark this answers is not in the document]
Comment (torkelo) [reply public/app/features/dashboard/utils/getPanelChromeProps.ts:10]: so it would be 
```ts
    const panelChromeProps = getPanelChromeProps(this.props);
```

**Comment by polibb** [comment]
I can see some issues related to updating the panel when changing its settings: Change of the DS, description, links, transparency, etc. do not change the data or look of the panel until after the dashboard is saved and the page reloaded. 

https://user-images.githubusercontent.com/13227501/233347878-bcfc389d-df99-4097-845b-87123600f9dc.mov

Changing the transparency, for example, is effective "immediately" if you change the panel type to a non-angular one and go back to the angular one:

https://user-images.githubusercontent.com/13227501/233348138-fff9bd2d-3327-402c-9b07-655e114f55fb.mov

**NB!** However, I can also see those problems on _Ops_ right now:

Uploading Screen Recording 2023-04-20 at 13.59.20.mov…

File: public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx (hunk 1 above)
Comment (axelavargas) [reply public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx:189]: I'm not sure if I can directly return PanelHeaderTitleItems from the getPanelChromeProps function because it's only a utility JavaScript function and not a React component.

I also considered the alternative of returning the props directly, but it wasn't possible due to some checks involving "showTitleItems" that we need to determine whether to display the title items or not (in this case, panelHeaderTitleItemsProps is null).

```
const getPanelHeaderTitleItemsProps = () => {
    const alertState = data.alertState?.state;
    const showTitleItems =
      (panel.links && panel.links.length > 0 && onShowPanelLinks) ||
      (data.series.length > 0 && data.series.some((v) => (v.meta?.notices?.length ?? 0) > 0)) ||
      (data.request && data.request.timeInfo) ||
      alertState;

    if (!showTitleItems) {
      return null;
    }
 
    return {
      alertState,
      data,
      panelId: panel.id,
      panelLinks: panel.links,
      onShowPanelLinks: onShowPanelLinks,
    };
  };
```

I might be missing a crucial aspect here and potentially complicating the code 😅. If you have any suggestions on how to improve this code, please let me know."

**Comment by axelavargas** [comment]
> I can see some issues related to updating the panel when changing its settings: Change of the DS, description, links, transparency, etc. do not change the data or look of the panel until after the dashboard is saved and the page reloaded.

Thank you @polibb 🙌🏾, I've tested locally and confirmed that these are indeed bugs. As you mentioned, they also exist in the current implementation (I tested them in ops). For now, I won't address them in this PR since they are out of scope. We can discuss this problem with the team and evaluate whether we should fix these issues, keeping in mind that Angular panels are deprecated.

File: public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx (hunk 3 above)
Comment (axelavargas) [reply public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx:248]: Yes, in the past we got some failed tests when we enabled the `newPanelChromeUI` feature flag by default, not only because of these selectors but also because we changed the flow of opening a menu. Marcus helped us in implementing code to maintain backward compatibility between the old angular panels and new panels [PR](https://github.com/grafana/grafana/pull/66118). But, I think this code is not needed anymore as we will have the same flow for angular panels and react panels.

File: public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx [hunk 5]
```diff
@@ -196,29 +202,69 @@ export class PanelChromeAngularUnconnected extends PureComponent<Props, State> {
...
+
+      return (
+        <PanelChrome
+          width={this.props.width}
+          height={this.props.height}
+          title={title}
+          loadingState={data.state}
+          statusMessage={errorMessage}
+          statusMessageOnClick={panelChromeProps.onOpenErrorInspect}
+          description={!!panel.description ? panelChromeProps.onShowPanelDescription : undefined}
```
[the remark this answers is not in the document]
Comment (axelavargas) [reply public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx:229]: good catch, I think we can return it :)

File: public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx (hunk 1 above)
Comment (torkelo) [reply public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx]: @axelavargas I am not sure what the problem is, returning titleItems worked without any issues

https://github.com/grafana/grafana/compare/axelav/migrate-to-angular-panels...migrate-to-angular-panels-title-items?expand=1

Comment (axelavargas) [reply public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx]: Ah, I think I see what I was doing wrong. I didn't change the file extension, and my editor was giving errors 😅. I'll apply your suggestions.

**Comment by axelavargas** [comment]
@torkelo I applied all the suggestions 😄
✔️ Returned title items directly
✔️ Moved drag class, title, and description to `getPanelChromeProps`
✔️ Extracted common props from `PanelChromeAngular` and `PanelStateWrapper`

File: public/app/features/dashboard/utils/getPanelChromeProps.tsx [hunk 6]
```diff
@@ -0,0 +1,121 @@
+import React from 'react';
+
+import { LinkModel, PanelData, PanelPlugin, renderMarkdown } from '@grafana/data';
+import { getTemplateSrv, locationService, reportInteraction } from '@grafana/runtime';
+import { PanelPadding } from '@grafana/ui';
+import { InspectTab } from 'app/features/inspector/types';
+import { getPanelLinksSupplier } from 'app/features/panel/panellinks/linkSuppliers';
+import { plugin } from 'app/plugins/panel/alertGroups/module';
```
Comment (torkelo) [inline public/app/features/dashboard/utils/getPanelChromeProps.tsx:8]: @axelavargas I discovered a bug, the panel padding is not working / correctly set for panels that have the "noPadding" option set (Stat panel, old angular table panel). 

The problem is that your importing plugin from here instead of accessing it from props :)

Comment (axelavargas) [reply public/app/features/dashboard/utils/getPanelChromeProps.tsx:8]: oh! will fix it :)

**Review by torkelo — APPROVED** [review]

**Review by polibb — APPROVED** [review]
Manually tested with CarpetPlot and d3 - LGTM! Beautiful!

**Comment by gtk-grafana** [comment]
https://ops.grafana-ops.net/d/eef643/mimir-reads?orgId=1&refresh=10s
image
https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/utils/getPanelChromeProps.tsx#L44

I get nearly 100 of these `dashboards_panelheader_description_displayed` rudderstack events just scrolling to the bottom of a big dashboard, and they just keep coming. Do we really need to make this many requests? Can we aggregate and send these events out in batches or something if this data collection is critical?
