### PR TITLE
Expressions: Isolate broken SSE pipeline nodes to enable partial results

### LINKED ISSUE #119939: Disabled, invalid SQL Expressions block ALL query results
TODO

### LINKED ISSUE #120002: Hidden SSE expressions with invalid configs still evaluate, producing errors in the response
## Overview

Hiding an SSE expression (math, reduce, SQL, etc.) does not prevent it from executing. When a hidden expression is also invalid — referencing a missing table, using bad syntax, etc. — it produces an error that appears in the panel response, potentially cascading to dependent visible queries.

## Steps to reproduce

1. Create a panel with:
  - **A**: a working datasource query, visible
  - **B**: a SQL expression referencing A with invalid SQL (e.g. `SELECT * FROM nonexistent`), hidden
  - **C**: a math expression `$A * 2`, visible
2. Observe that C may show a dependency error even though B is hidden, or that unnecessary backend work is performed

## Expected behavior

A hidden expression does not execute. Its hidden status is treated as a signal that it's a work-in-progress and should be entirely skipped — no evaluation, no errors, no datasource calls.

## Actual behavior

The pipeline executes every node regardless of hide status. The hide property is only consulted after execution as a post-processing filter on the response. Errors from hidden nodes can cascade: if **B** errors and **C** depends on **B**, **C** gets a `DependencyError` even though **B** shouldn't have run.

## Root cause

`DataPipeline.execute()` (`pkg/expr/graph.go`) has no hide check. The `hiddenRefIDs()` filtering in `TransformData` (`transform.go`) is a post-execution response filter only. It removes results from the returned response but does not prevent execution.

### PR DESCRIPTION
**Pull request by NWRichmond**
## Motivation

This PR fixes #119939.

## Description

This PR fixes pipeline-build failures where `buildGraphEdges` hard-fails the entire pipeline when an expression node references a nonexistent refID, hiding all other query results. With the `sseExpressionErrorIsolation` feature toggle enabled, broken nodes are pruned before execution and their errors are surfaced per-refID in the response. Valid nodes continue to run and return data normally.

The alerting pipeline path (`BuildPipeline`, used by `ngalert`) is unaffected: it rejects degraded pipelines the same as before, ensuring alerting rules cannot silently evaluate against partial data.

## Changes

- Added a new `sseExpressionErrorIsolation` feature toggle (experimental, default off). I don't envision this being a long-lived feature toggle. But out of caution, especially with respect to Alerting, it feels wise to put these changes behind a feature toggle.
- In **`pkg/expr/graph.go`**, added `collectBrokenNodes` which identifies nodes with missing dependencies, propagates errors to transitive dependents via fixed-point loop, and removes them from the graph before execution. `buildPipeline` returns a `brokenNodes map[string]error` alongside the pipeline; the degraded path is gated on the OpenFeature flag.
- In **`pkg/expr/service.go`**, `BuildPipeline` (public, used by alerting) rejects degraded pipelines by returning the first broken-node error, preserving existing alerting safety semantics. SQL error category metrics are recorded before returning.
- In **`pkg/expr/transform.go`**, `TransformData` calls `buildPipeline` directly, pre-populates per-refID error entries for broken nodes, then executes the remaining valid pipeline. SQL metrics recorded for broken nodes here too.
- **`pkg/expr/sql_schema.go`** is updated for the new 3-value `buildPipeline` return.

## Risks

The `sseExpressionErrorIsolation` toggle is off by default, so no behavioral change ships until it is explicitly enabled. The public `BuildPipeline` API signature is unchanged; alerting callers (`ngalert/eval`) are insulated from the degraded pipeline path entirely. The only changed signature is the private `buildPipeline`, which is contained within `pkg/expr`.

## Demo

Here's a dashboard that demonstrates #119939:

[dashboard-119939-sql-expressions-bug_three-v1.json](https://github.com/user-attachments/files/26230397/dashboard-119939-sql-expressions-bug_three-v1.json)

### Before

Ideally, when there's an issue with a SQL Expression, we should see an informative error alongside any successful query results. We currently see this when a SQL Expressions query references a valid table but references a non-existent column. But for SQL Expressions queries that reference a table that doesn't exist, the entire panel crashes, so we don't see the successful datasource results. Note that the same is true for Math expressions that reference an invalid refId.

https://github.com/user-attachments/assets/dfaf8682-51d4-4bc2-9f9e-fc7af3aebe5e

### After

The parts that worked before still work. Importantly, for the SQL Expressions and Math panels that previously crashed, we now see error messages alongside successful query results.

https://github.com/user-attachments/assets/d6d473e1-7f76-4a17-b5fe-264b91d886b5

## Testing Instructions

- Checkout branch `119939/expressions-error-isolation`
- Enable the toggle in `conf/custom.ini`:
  ```ini
  [feature_toggles]
  sseExpressionErrorIsolation = true
  ```
- Start the backend (`make run`) and frontend (`yarn start`)
- Create a panel with two queries: one valid data source query (e.g. testdata) and one SQL expression referencing a nonexistent table (e.g. `SELECT time, value FROM nonexistent_table`)
- **Expected (toggle ON):** all panels show the valid query's data; the broken expression shows a per-query error in the query inspector
- **Expected (toggle OFF):** panels with invalid refIds in expressions show a full panel error, no data returned (existing behavior)

## Reviewer Checklist

- [ ] Tests are added where applicable
- [x] Issue is linked to PR
- [ ] Code pulled and tested
- [ ] Code is meaningfully improved if applicable

### CODE REVIEW

File: pkg/expr/graph.go [hunk 1]
```diff
@@ -373,12 +399,18 @@ func (s *Service) buildGraphEdges(dp *simple.DirectedGraph, registry map[string]
 		for _, neededVar := range cmdNode.Command.NeedsVars() {
 			neededNode, ok := registry[neededVar]
 			if !ok {
+				if degraded {
+					var nodeErr error
+					if cmdNode.CMDType == TypeSQL {
+						nodeErr = sql.MakeTableNotFoundError(cmdNode.refID, neededVar)
+					} else {
+						nodeErr = fmt.Errorf("unable to find dependent node '%v'", neededVar)
```
Comment (kylebrandt) [inline pkg/expr/graph.go]: Can you make an error for this like in expr/errors.go?

Comment (NWRichmond) [reply pkg/expr/graph.go]: Certainly, done in https://github.com/grafana/grafana/pull/121043/changes/d268eae3a0fdf746ce14f44b8abd377cc1a03162 ✔️

File: pkg/expr/service.go [hunk 2]
```diff
@@ -102,8 +103,26 @@ func (s *Service) isDisabled() bool {
...
 func (s *Service) BuildPipeline(ctx context.Context, req *Request) (DataPipeline, error) {
-	return s.buildPipeline(ctx, req)
+	pipeline, err := s.buildPipeline(ctx, req)
+	if err != nil {
+		return nil, err
+	}
+	for _, node := range pipeline {
+		if nodeErr := node.DisabledErr(); nodeErr != nil {
+			// Record SQL metrics before returning, matching the behavior of
+			// the non-degraded path where instrumentSQLError fires on failure.
```
Comment (beejeebus) [inline pkg/expr/service.go:117]: not sure how much this matters, but it looks like we're changing the behaviour of this counter.

previously, we'd increment per-pipeline, and now, we increment per failed sqlErr.

**Review by beejeebus — APPROVED** [review]
I left a question about changed behaviour of error counters, but I don't see that as a blocker.

File: pkg/expr/service.go (hunk 2 above)
Comment (NWRichmond) [reply pkg/expr/service.go:117]: Thanks for flagging this! But I think the cardinality is actually the same here. The `return nil, nodeErr` inside the loop means we still increment at most once per `BuildPipeline` call, same as before. The only difference is the increment moved from `buildPipeline`'s deferred into this loop.
                                                                                                                                                                 
The per-node behavior you're describing does exist, but in `dp.execute`, where a disabled node fires once, then any downstream SQL dependents fire via the existing cascade logic. That path is `TransformData` only; `BuildPipeline` (alerting) never reaches it.
