### PR TITLE
GoogleCloudMonitoring: Fix query object for panels prior to v7

### LINKED ISSUE #29643: Explore link of stackdriver datasource no longer works after upgrade from v6
**What happened**:

The `Explore` link no longer works after upgraded from v6 (v6.7.4 in my case),
the panel was configured as stackdriver datasource before upgrade:
Screen Shot 2020-12-07 at 16 03 44

and after the upgrade, the link no longer opens `Explore` page, from the console it has errors:
```
datasource.ts:313 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at t.value (datasource.ts:313)
    at t.value (datasource.ts:345)
    at datasource.ts:359
    at Array.map (<anonymous>)
    at t.value (datasource.ts:359)
    at explore.ts:102
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97)
value @ datasource.ts:313
value @ datasource.ts:345
(anonymous) @ datasource.ts:359
value @ datasource.ts:359
(anonymous) @ explore.ts:102
c @ runtime.js:45
...
```
Screen Shot 2020-12-07 at 15 53 51

after some checking, we noticed the dashboard json has extra json contents added after click `Edit` (edit the panel):
```
          "metricQuery": {
            "aliasBy": "{{metric.label.method}} -> {{metric.label.route}}: {{metric.label.code}}",
            "alignOptions": [
              {
                "expanded": true,
                "label": "Alignment options",
                "options": [
                  {
            ...
            "lastQueryError": "",
            "metricKind": "DELTA",
            "metricType": "....",
            "perSeriesAligner": "ALIGN_SUM",
            "service": "",
            "unit": "1",
            "usedAlignmentPeriod": 60,
            "valueType": "INT64"
          },
          "queryType": "metrics",
```

So we think these contents were missing from the upgrade, and the typescripts are looking for these, currently the workaround is edit the panel, save the dashboard (so the extra contents being saved), then the `Explore` link should work again.

**What you expected to happen**:
After clicking on the `Explore` link, it should open `Explore` page with the metric options set from the panel.

**How to reproduce it (as minimally and precisely as possible)**:
1. install grafana v6.7.4
1. configured stackdriver data source and a panel with the datasource
1. upgrade grafana to v7.3.4
1. check the dashboard with the panel (without clicking any `edit` link), click on the `Explore` link, the error should show, and UI did not redirect.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.7.4 -> v7.3.4
- Data source type & version: Stackdriver 
- OS Grafana is installed on: docker grafana/grafana:7.3.4 
- User OS & Browser: macOS Catalina 10.15.7, Chrome Version 87.0.4280.88 (Official Build) (x86_64)
- Grafana plugins: 
- Others:

### PR DESCRIPTION
**Pull request by andresmgot**
**What this PR does / why we need it**:

After some refactoring, panels from <7.x wouldn't work in v7 or v8. The information is still there but not under the query `metricQuery`.

**Which issue(s) this PR fixes**:

Fixes #29643

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/datasource/cloud-monitoring/datasource.ts [hunk 1]
```diff
@@ -103,10 +104,10 @@ export default class CloudMonitoringDatasource extends DataSourceWithBackend<
...
   }
 
-  applyTemplateVariables(
-    { metricQuery, refId, queryType, sloQuery }: CloudMonitoringQuery,
-    scopedVars: ScopedVars
-  ): Record<string, any> {
+  applyTemplateVariables(query: CloudMonitoringQuery, scopedVars: ScopedVars): Record<string, any> {
+    const { refId, queryType, sloQuery } = query;
+    // Query won't have the key metricQuery in v6.x, just the plain object
+    const metricQuery = query.metricQuery ? query.metricQuery : (query as MetricQuery);
```
Comment (sunker) [inline public/app/plugins/datasource/cloud-monitoring/datasource.ts:110]: I think you should be able to call `this.migrateQuery(query)` instead. Then we don't have the migration code at different places.

**Review by sunker — APPROVED** [review]
LGTM
