### PR TITLE
Permissions: Validate against Team/User permission role update

### LINKED ISSUE #29059: Permissions: Inconsistent state inherited for User+Team ACLs after adding Editor/Viewer permissions
**What happened**:
It seems to me the react state isn't being reset correctly in `AddPermission.tsx` for when the type select form field changes - or more concretely, the **role** field is never being set to `undefined` when the form flips back to type `Team` after adding a permission. The backend intercepts the role value as normal (will follow up with this in a separate issue) and eventually ends up creating a weird state for the user (see #28615). 

**What you expected to happen**:
`role` will be set to `null`/`undefined` when creating a Team permission so that the correct state is represented in the database.

**How to reproduce it (as minimally and precisely as possible)**:
Kapture 2020-11-12 at 13 02 20

**Environment**:
- Grafana version: master
- User OS & Browser: MacOS, Chrome v86

### PR DESCRIPTION
**Pull request by wbrowne**
**What this PR does / why we need it**:
It's my understanding that team/user permissions cannot have an associated role as it leads to weird permission leaks (see linked issue). This will fix the bad state in the frontend and also validate against the request on the backend in the case the state ever breaks on the client again.

**Which issue(s) this PR fixes**:

Fixes #29059

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/api/dashboard_permission_test.go [hunk 1]
```diff
@@ -166,6 +166,33 @@ func TestDashboardPermissionAPIEndpoint(t *testing.T) {
...
+					},
+				},
+			}
+
+			for _, cmd := range cmds {
+				updateDashboardPermissionScenario(t, "When calling POST on", "/api/dashboards/id/1/permissions",
+					"/api/dashboards/id/:id/permissions", cmd, func(sc *scenarioContext) {
+						callUpdateDashboardPermissions(sc)
+						assert.Equal(t, 400, sc.resp.Code)
+						respJSON, err := simplejson.NewJson(sc.resp.Body.Bytes())
```
Comment (aknuds1) [inline pkg/api/dashboard_permission_test.go:189]: Can we use the standard json package instead of simplejson? I think we want to move away from the latter.

File: pkg/api/folder_permission_test.go [hunk 2]
```diff
@@ -172,6 +172,33 @@ func TestFolderPermissionAPIEndpoint(t *testing.T) {
...
+				},
+			},
+		}
+
+		for _, cmd := range cmds {
+			updateFolderPermissionScenario(t, "When calling POST on", "/api/folders/uid/permissions",
+				"/api/folders/:uid/permissions", cmd, func(sc *scenarioContext) {
+					callUpdateFolderPermissions(sc)
+					assert.Equal(t, 400, sc.resp.Code)
+					respJSON, err := simplejson.NewJson(sc.resp.Body.Bytes())
```
Comment (aknuds1) [inline pkg/api/folder_permission_test.go:195]: Also wondering if we can use the standard json package here, instead of simplejson.

File: pkg/models/dashboard_acl.go [hunk 3]
```diff
@@ -24,10 +24,11 @@ func (p PermissionType) String() string {
...
 var (
-	ErrDashboardAclInfoMissing           = errors.New("User id and team id cannot both be empty for a dashboard permission")
-	ErrDashboardPermissionDashboardEmpty = errors.New("Dashboard Id must be greater than zero for a dashboard permission")
-	ErrFolderAclInfoMissing              = errors.New("User id and team id cannot both be empty for a folder permission")
-	ErrFolderPermissionFolderEmpty       = errors.New("Folder Id must be greater than zero for a folder permission")
+	ErrDashboardAclInfoMissing           = errors.New("user id and team id cannot both be empty for a dashboard permission")
+	ErrDashboardPermissionDashboardEmpty = errors.New("dashboard id must be greater than zero for a dashboard permission")
+	ErrFolderAclInfoMissing              = errors.New("user id and team id cannot both be empty for a folder permission")
+	ErrFolderPermissionFolderEmpty       = errors.New("folder id must be greater than zero for a folder permission")
+	ErrPermissionsWithRoleNotAllowed     = errors.New("teams and users permissions cannot have an associated role")
```
Comment (aknuds1) [inline pkg/models/dashboard_acl.go:31]: Isn't it more correct to say "team permissions" and "user permissions"?
```suggestion
	ErrPermissionsWithRoleNotAllowed     = errors.New("team and user permissions cannot have an associated role")
```

**Review by aknuds1 — APPROVED** [review]
Not really familiar with the functionality/semantics, but generally LGTM. See comments though.

**Review by marefr — APPROVED** [review]
LGTM

**Review by mckn — APPROVED** [review]
LGTM!

**Review by hugohaggmark — APPROVED** [review]
LGTM!
