### PR TITLE
Alerting: Fix prometheus API to check folder permissions

### LINKED ISSUE #36289: Alerting: Users can see folders they have no permissions for
* Create a folder with only Admin role can Admin permissions 
* Add a new alert rule to this folder 
* Login as a Viewer or Editor user 

The folder is present in the alert rule list but the rule as a spinner and as deleting.... 
Screenshot from 2021-06-30 10-07-48

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
It adds check for folder permissions in `GET /api/prometheus/grafana/api/v1/rules` similar to what happens for [`GET /api/ruler/grafana/api/v1/rules`](https://github.com/grafana/grafana/blob/1490c255f10cdb80ec26caf69f511b427756d2a3/pkg/services/ngalert/api/api_ruler.go#L158-L166)

It also standardises the response to always returns the results ordered by the folder title.

**Which issue(s) this PR fixes**:

Fixes #36289

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/ngalert/api/api_prometheus.go [hunk 1]
```diff
@@ -76,6 +77,13 @@ func (srv PrometheusSrv) RouteGetRuleStatuses(c *models.ReqContext) response.Res
 			continue
 		}
 		groupId, namespaceUID, namespace := r[0], r[1], r[2]
+		if _, err := srv.store.GetNamespaceByUID(namespaceUID, c.SignedInUser.OrgId, c.SignedInUser); err != nil {
```
Comment (torkelo) [inline pkg/services/ngalert/api/api_prometheus.go:80]: If you have a 200 folders won't this result in N+ queries ?

Comment (papagian) [reply pkg/services/ngalert/api/api_prometheus.go:80]: yes, as an improvement we could use some caching but we need to cache also folder permissions and keep the cache updated whenever permissions change.

**Review by torkelo — APPROVED** [review]
