### PR TITLE
Loki: Fix double stringified log-lines when copied via Copy button

### LINKED ISSUE #57093: Explore 'Copy' button copies double-quoted string instead of raw string
**What happened**:

In Grafana Explore, I am viewing some Loki logs. I click on the "Copy" button on the right of a log line. It copies the log line in my clipboard, but as a double-quoted string instead of the raw string.

For example, here is a simple log line copied and pasted from Explore:
```
"2022-10-17T14:30:35.946788314Z stdout F level=debug traceID=159eac248e55b80e msg=\"GET / (200) 4.368281ms\""
```

**What you expected to happen**:

I would expect the raw string being copied:
```
2022-10-17T14:30:35.946788314Z stdout F level=debug traceID=159eac248e55b80e msg="GET / (200) 4.368281ms"
```

**How to reproduce it (as minimally and precisely as possible)**:

This can be reproduced in play.grafana.org.

https://play.grafana.org/explore?orgId=1&left=%7B%22datasource%22:%22zXvfRSSVz%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bjob%3D%5C%22tns%2Ftns-app%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22zXvfRSSVz%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

**Anything else we need to know?**:

The use-cases are described in this GitHub discussion:
https://github.com/grafana/grafana/issues/25517

**Environment**:
- Grafana version: v9.2.0
- Data source type & version: Loki
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Firefox 105.0.1 on Pop_OS 22.04
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by svennergr**
**What this PR does / why we need it**:
This PR fixes a bug, where log-lines where stringified even though there are already strings.

**Which issue(s) this PR fixes**:

Fixes #57093

### CODE REVIEW

File: public/app/features/logs/components/LogRowMessage.tsx [hunk 1]
```diff
@@ -207,11 +207,7 @@ class UnThemedLogRowMessage extends PureComponent<Props> {
                 </Tooltip>
               )}
               <Tooltip placement="top" content={'Copy'}>
-                <IconButton
-                  size="md"
-                  name="copy"
-                  onClick={() => navigator.clipboard.writeText(JSON.stringify(restructuredEntry))}
-                />
+                <IconButton size="md" name="copy" onClick={() => navigator.clipboard.writeText(restructuredEntry)} />
```
Comment (svennergr) [inline public/app/features/logs/components/LogRowMessage.tsx:210]: `restructuredEntry` is already a string, thus I only removed `JSON.stringify`

**Review by ivanahuckova — APPROVED** [review]
👍
