### PR TITLE
Cloudwatch: Clear cached PDC transport when PDC is disabled

### LINKED ISSUE #91356: Cloudwatch: disabling PDC does not work until session expires
### What happened?

If you enable Private Datasource Connect on a cloudwatch datasource, then disable it again, PDC will still be used until the session expires up to 15 minutes later.

### What did you expect to happen?

As soon as the datasource is saved with PDC disabled, it should stop trying to use PDC.

### Did this work before?

Unsure, but certainly not for a while.

### How do we reproduce it?

1. Create a cloudwatch datasource
2. "Save and test" and see it working.
3. Enable PDC with a network that has no connected agents
4. "Save and test" and see an error like
```
CloudWatch metrics query failed: RequestError: send request failed caused by: Post "https://sts.amazonaws.com/":
socks connect tcp localhost:10443->sts.amazonaws.com:443: dial tcp [::1]:10443: connect: connection refused
```
5. Disable PDC by unselecting the network
6. "Save and test" again and see that the error persists.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

cloudwatch

### PR DESCRIPTION
**Pull request by njvrzm**
**What is this feature?**
This fixes an issue where disabling PDC on a Cloudwatch datasource doesn't take effect until the cached session expires.

**Why do we need this feature?**
Fixes #91356

### CODE REVIEW

File: pkg/tsdb/cloudwatch/cloudwatch.go [hunk 1]
```diff
@@ -337,6 +337,10 @@ func (ds *DataSource) newSession(region string) (*session.Session, error) {
 		if err != nil {
 			return nil, fmt.Errorf("error configuring Secure Socks proxy for Transport: %w", err)
 		}
+	} else if sess.Config.HTTPClient != nil {
```
Comment (njvrzm) [inline pkg/tsdb/cloudwatch/cloudwatch.go:340]: Checking this because the tests receive a session with an empty Config.

**Review by iwysiu — APPROVED** [review]
