### PR TITLE
Datasource config: correctly remove single custom http header

### LINKED ISSUE #29096: Removal of HTTP Headers fail
**What happened**:

After removing a custom HTTP header in a Prometheus datasource, clicking save&test, the header was removed. save&test succeeded
When then selecting the datasource again, the header was present again

**What you expected to happen**:

after removing the header, it should be removed permanently, not come back after refresh/reload

**How to reproduce it (as minimally and precisely as possible)**:

- create prometheus datasource (haven't tested with other datasources)
- add custom http header with value
- save & test -> success
- refresh/reload datasources
- open recently created datasource
- remove custom header with bin icon
- save & test -> success
- refresh/reload page
- header is still there

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: Prometheus
- OS Grafana is installed on: based on official docker image
- User OS & Browser: mac + chrome
- Grafana plugins: 
- Others: using Postgres as a database: `postgres:11.2-alpine`

### PR DESCRIPTION
**Pull request by gabor**
Fixes https://github.com/grafana/grafana/issues/29096

When you configure a datasource, you can add custom http-headers. When there are multiple such headers, one can be removed correctly. But, when there is only 1, it cannot be removed. (When you click on the trashcan-icon, visually it will disappear, but it wills stay in the data, and if you do a [save & test] and then a reload-page, it appears again.)

in the code, there is a loop that adds the current items to the data-structure, and there is a cleanup-code that removes items that do not exist anymore from the data-structure. the cleanup happened at every iteration of the for-loop, so when there was no item, no for-loop iteration, no cleanup, no last-item-removed. i moved the cleanup-code outside the for-loop.

i added a test in the unit-tests, this required a minor reorganisation in the unit-test-file.

### CODE REVIEW

File: packages/grafana-ui/src/components/DataSourceSettings/CustomHeadersSettings.tsx [hunk 1]
```diff
@@ -119,15 +119,15 @@ export class CustomHeadersSettings extends PureComponent<Props, State> {
...
-        });
     }
+    Object.keys(jsonData)
+      .filter(
+        (key) =>
+          key.startsWith('httpHeaderName') && parseInt(key.substring('httpHeaderName'.length), 10) > headers.length
+      )
+      .forEach((key) => {
+        delete jsonData[key];
+      });
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/DataSourceSettings/CustomHeadersSettings.tsx:130]: nit: I'm always a bit sceptical when I see deletes in a forEach, seems like we would mutate state. Maybe this is the same?
```suggestion
    const newJsonData: any = Object.keys(jsonData).reduce((acc, key) => {
      if (key.startsWith('httpHeaderName') && parseInt(key.substring('httpHeaderName'.length), 10) > headers.length) {
        return acc;
      }

      acc[key] = jsonData[key];
      return acc;
    }, {} as Record<string, any>);
```

**Review by hugohaggmark — APPROVED** [review]
Looks good and I left some nits for consideration 🎉

File: packages/grafana-ui/src/components/DataSourceSettings/CustomHeadersSettings.tsx (hunk 1 above)
Comment (gabor) [reply packages/grafana-ui/src/components/DataSourceSettings/CustomHeadersSettings.tsx:130]: i'll be honest with you i was trying to do a minimal possible change here :-) you are right of course, i will adjust the code

Comment (gabor) [reply packages/grafana-ui/src/components/DataSourceSettings/CustomHeadersSettings.tsx]: done (i chose a slightly different approach but should be ok)

File: packages/grafana-ui/src/components/DataSourceSettings/CustomHeadersSettings.test.tsx [hunk 2]
```diff
@@ -33,29 +34,29 @@ const setup = (propOverrides?: object) => {
       secureJsonFields: {},
       readOnly: true,
     },
-    onChange: jest.fn(),
+    onChange,
     ...propOverrides,
   };
 
-  return mount(<CustomHeadersSettings {...props} />);
+  return { wrapper: mount(<CustomHeadersSettings {...props} />), onChange };
```
[the remark this answers is not in the document]
Comment (gabor) [reply packages/grafana-ui/src/components/DataSourceSettings/CustomHeadersSettings.test.tsx]: done

**Comment by gabor** [comment]
@hugohaggmark i improved the pull-req, but now it changed a lot, could you check it one more time plz? thanks

File: packages/grafana-ui/src/components/DataSourceSettings/CustomHeadersSettings.tsx [hunk 3]
```diff
@@ -112,27 +118,25 @@ export class CustomHeadersSettings extends PureComponent<Props, State> {
...
+      Object.entries(this.props.dataSourceConfig.jsonData).filter(([key, val]) => !key.startsWith('httpHeaderName'))
+    );
+
+    // then we add the current httpHeader-fields
     for (const [index, header] of headers.entries()) {
-      jsonData[`httpHeaderName${index + 1}`] = header.name;
+      newJsonData[`httpHeaderName${index + 1}`] = header.name;
       if (!header.configured) {
-        secureJsonData[`httpHeaderValue${index + 1}`] = header.value;
+        newSecureJsonData[`httpHeaderValue${index + 1}`] = header.value;
```
Comment (aocenas) [inline packages/grafana-ui/src/components/DataSourceSettings/CustomHeadersSettings.tsx:132]: Took me a while to figure out what this code did before. Another problem that is still there is that we do not remove the value from secureJsonData can we also add that? Cause right now you can configure a header then delete it, configure another header without setting the value and it will inherit the previous orphaned value which isn't great.

Comment (hugohaggmark) [reply packages/grafana-ui/src/components/DataSourceSettings/CustomHeadersSettings.tsx:132]: Good catch!

**Review by hugohaggmark — APPROVED** [review]
Looks a lot better and splendid work with the tests 🎉 ! I agree with @aocenas comment and I found this strange edge case with auto filled values that aren't getting preserved.

bug1

File: packages/grafana-ui/src/components/DataSourceSettings/CustomHeadersSettings.tsx (hunk 3 above)
Comment (gabor) [reply packages/grafana-ui/src/components/DataSourceSettings/CustomHeadersSettings.tsx:138]: done
