### PR TITLE
Instrumentation: Proxy status code correction and various improvements

### LINKED ISSUE #46337: Status code correction for client canceled requests in Grafana backend logs
**What happened**:

Dashboard data query can take longer than the set interval or user manually triggered refresh in UI so that duplicate requests would be created; and then Grafana cancels the ongoing request that has not finished yet (Reference: https://github.com/grafana/grafana/blob/6165377eb21ddf00b65d4d85ae1a8b203aac5439/contribute/architecture/frontend-data-requests.md)

For these kind of client side canceled requests, the Grafana backend will output logs with status code `502 (Bad Gateway)` via `context` logger.

However, these kind of errors are not server errors, so they should not be tagged with a 500+ status code. As a result, these kind of status codes will lead to a higher-than-expected failure rate if server failure monitoring is based on 500+ status code (a common way of server failure rate evaluation), which makes service health monitoring inaccurate.

**What you expected to happen**:

A status code less than 500 (such as `400 Bad Request`) should be used for the backend logs of those kind of client side canceled requests since they are not server failures.

**How to reproduce it (as minimally and precisely as possible)**:
- [enable dataproxy logging (set as `true`)](https://grafana.com/docs/grafana/latest/administration/configuration/#logging) for the Grafana backend
- set up some dashboards using data source like Prometheus
- suppose there are some data queries of some dashboard panels taking long time to finish (5-10s for example), then you can hit the refresh button in the dashboard page to trigger the first refresh for all panels, and then while some panels are still refreshing (as indicated by the spinning ui on the top right corner of the panels) you can hit refresh button again for a second time to generate duplicated requests for the same panel queries. Then you would see some requests canceled in browser network trace.
- for those canceled requests shown in browser, the Grafana backend would output logs of `dataproxy` logger showing error message like `http: proxy error: context canceled` and logs of `context` logger with status code of `502 (Bad Gateway)`.

**Anything else we need to know?**:

Although there is no correlation id (trace id) to connect the `dataproxy` logger logs with the `context` logger logs, you can still recognize those logs in backend log output that corresponds to those client canceled requests.

**Environment**:
- Grafana version: 8.4.1
- Data source type & version: Prometheus (this error is not necessarily tied with Prometheus data source)
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10 with Chrome

### LINKED ISSUE #46338: Status code correction for timed-out dataproxy requests in Grafana backend logs
**What happened**:

Dashboard data query that is sent to external data source by Grafana backend could time out some time. 

For these kind of timed-out data proxy requests, the Grafana backend will output logs with status code `502 (Bad Gateway)` via `context` logger and logs with error `http: proxy error: net/http: timeout awaiting response headers` via `dataproxy` logger (if enabled) like below.
image

**What you expected to happen**:

Status code of [`504 (Gateway Timeout)`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504) should be used rather than status code [`502 (Bad Gateway)`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502) to better reflect the root cause of the failed data query requests.

**How to reproduce it (as minimally and precisely as possible)**:
- [enable dataproxy logging (set as `true`)](https://grafana.com/docs/grafana/latest/administration/configuration/#logging) for the Grafana backend
- set up some dashboards using data source like Prometheus
- suppose there are some data queries of some dashboard panels timed out (longer than 30s [default time out in Grafana Core](https://github.com/grafana/grafana/blob/6165377eb21ddf00b65d4d85ae1a8b203aac5439/pkg/api/pluginproxy/ds_proxy.go#L107)), then the Grafana backend would output logs of `dataproxy` logger showing error message like `http: proxy error: net/http: timeout awaiting response headers` and logs of `context` logger with status code of `502 (Bad Gateway)`.

**Anything else we need to know?**:

Although there is no correlation id (trace id) to connect the `dataproxy` logger logs with the `context` logger logs, you can still recognize those logs in backend log output that corresponds to those timed-out requests.

**Environment**:
- Grafana version: 8.4.1
- Data source type & version: Prometheus (this bahavior is not necessarily tied with Prometheus data source)
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10 with Chrome

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
For a proxied request, e.g. Grafana's datasource or plugin proxy:
- If the request is cancelled, e.g. from the browser, the HTTP status code is now `499 Client closed request` instead of `502 Bad gateway`
- If the request times out, e.g. takes longer time than allowed, the HTTP status code is now `504 Gateway timeout` instead of `502 Bad gateway`.

This also means that request metrics and logs will get their status codes adjusted according to above.

In addition some refactoring has been done:
- Introduces a `proxyutil.NewReverseProxy` function that creates a new `httputil.ReverseProxy` with sane default configuration and includes proper logging and removal of certain HTTP request/response headers. 
- All places in source code that used `httputil.ReverseProxy{}` to create a new reverse proxy now uses `proxyutil.NewReverseProxy`.
- App plugin proxy now includes data proxy logging if enabled in the same way as the datasource proxy works.

**Which issue(s) this PR fixes**:
Fixes #46337
Fixes #46338

**Special notes for your reviewer**:
Noticed a problem with app plugin routes that it probably doesn't work great when installing/uninstalling app plugins during runtime. This will be handled separately. 

Datasource proxy request cancelled by client test:
```
INFO[04-08|18:09:15] Proxying incoming request                logger=data-proxy-log userid=1 orgid=1 username=admin datasource=graphite uri=/api/datasources/proxy/53/render method=POST body="target=averageSeries(aliasByTags(seriesByTag('name%3Drandom-walk.count'%2C%20'app%3Dcollector')%2C%20'dc'%2C%20'dc'%2C%20'server')%2C%20aliasByTags(seriesByTag('name%3Drandom-walk.count'%2C%20'app%3Dlogger')%2C%20'dc'%2C%20'dc'%2C%20'server'))&from=-6h&until=now&format=json&maxDataPoints=404"
DBUG[04-08|18:09:15] Proxy request cancelled by client        logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/53/render remote_addr=[::1] referer="http://localhost:3000/d/gqJ6zPznz/graphite-test?orgId=1"
```

Datasource proxy request timeout test:
```
INFO[04-08|17:59:41] Proxying incoming request                logger=data-proxy-log userid=1 orgid=1 username=admin datasource=graphite uri=/api/datasources/proxy/325/render method=POST body="target=constantLine(100)&from=-1h&until=now&format=json&maxDataPoints=300"
EROR[04-08|17:59:42] Proxy request timed out                  logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/325/render remote_addr=[::1] referer=http://localhost:3000/datasources/edit/jOQJPSU7z err="net/http: timeout awaiting response headers"
EROR[04-08|17:59:42] Request Completed                        logger=context traceID=414b97e27ed571b4 userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/325/render status=504 remote_addr=[::1] time_ms=1005 duration=1.005378738s size=0 referer=http://localhost:3000/datasources/edit/jOQJPSU7z traceID=414b97e27ed571b4
```

Datasource proxy other error test:
```
INFO[04-08|18:21:49] Proxying incoming request                logger=data-proxy-log userid=1 orgid=1 username=admin datasource=graphite uri=/api/datasources/proxy/53/render method=POST body="target=averageSeries(aliasByTags(seriesByTag('name%3Drandom-walk.count'%2C%20'app%3Dcollector')%2C%20'dc'%2C%20'dc'%2C%20'server')%2C%20aliasByTags(seriesByTag('name%3Drandom-walk.count'%2C%20'app%3Dlogger')%2C%20'dc'%2C%20'dc'%2C%20'server'))&from=-6h&until=now&format=json&maxDataPoints=404"
EROR[04-08|18:21:49] Proxy request failed                     logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/53/render remote_addr=[::1] referer="http://localhost:3000/d/gqJ6zPznz/graphite-test?orgId=1" err="dial tcp 127.0.0.1:8180: connect: connection refused"
EROR[04-08|18:21:49] Request Completed                        logger=context traceID=15699d5ef8cbf506 userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/53/render status=502 remote_addr=[::1] time_ms=6 duration=6.697872ms size=0 referer="http://localhost:3000/d/gqJ6zPznz/graphite-test?orgId=1" traceID=15699d5ef8cbf506
```

App plugin proxy request with data proxy logging enabled:
```
INFO[04-08|18:53:57] Proxying incoming request                logger=data-proxy-log userid=1 orgid=1 username=admin app=cloudflare-app uri=/api/plugin-proxy/cloudflare-app/with-token/api/v4/accounts/7f9ffa5475f6a5266cf50a189cfca8f4/dns_firewall method=GET body=
INFO[04-08|18:53:58] Request Completed                        logger=context traceID=4ef2a920a682a7fe userId=1 orgId=1 uname=admin method=GET path=/api/plugin-proxy/cloudflare-app/with-token/api/v4/accounts/7f9ffa5475f6a5266cf50a189cfca8f4/dns_firewall status=200 remote_addr=[::1] time_ms=822 duration=822.944415ms size=111 referer=http://localhost:3000/plugins/cloudflare-app traceID=4ef2a920a682a7fe
```

# Release notice breaking change

For a proxied request, e.g. Grafana's datasource or plugin proxy:
- If the request is cancelled, e.g. from the browser/by the client, the HTTP status code is now `499 Client closed request` instead of `502 Bad gateway`
- If the request times out, e.g. takes longer time than allowed, the HTTP status code is now `504 Gateway timeout` instead of `502 Bad gateway`.

### CODE REVIEW

File: pkg/util/proxyutil/reverse_proxy.go [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+type timeoutError interface {
+	error
+	Timeout() bool
+}
+
+func errorHandler(logger glog.Logger) func(http.ResponseWriter, *http.Request, error) {
+	return func(w http.ResponseWriter, r *http.Request, err error) {
+		if errors.Is(err, context.Canceled) {
+			logger.Debug("Proxy request cancelled")
+			w.WriteHeader(http.StatusBadRequest)
```
Comment (bergquist) [inline pkg/util/proxyutil/reverse_proxy.go:90]: Is this where we change status for cancelled requests? Perhaps some comment about it :)
I think 499 _might_ be more appropriate as well. It's not standard but fairly common for proxies. not sure. 400 could be confused with invalid input which we care more about. 

https://httpstatus.in/499/

File: pkg/api/pluginproxy/pluginproxy.go [hunk 2]
```diff
@@ -80,15 +91,35 @@ func NewApiPluginProxy(ctx *models.ReqContext, proxyPath string, route *plugins.
...
 
-	return nil
+	logger.Info("Proxying incoming request",
+		"userid", c.UserId,
+		"orgid", c.OrgId,
+		"username", c.Login,
+		"app", appID,
+		"uri", c.Req.RequestURI,
+		"method", c.Req.Method,
+		"body", body)
```
Comment (papagian) [inline pkg/api/pluginproxy/pluginproxy.go:124]: I don't know if we used to log the body before but if not, what if it contains sensitive information? Is that possible? In which cases `DataProxyLogging` is enabled? Would debug level be more appropriate?

File: pkg/util/proxyutil/reverse_proxy_test.go [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+		req := httptest.NewRequest(http.MethodGet, upstream.URL, nil)
+		req.Header.Set("X-Forwarded-Host", "forwarded.host.com")
+		req.Header.Set("X-Forwarded-Port", "8080")
+		req.Header.Set("X-Forwarded-Proto", "https")
+		req.Header.Set("Origin", "test.com")
+		req.Header.Set("Referer", "https://test.com/api")
+		req.RemoteAddr = "10.0.0.1"
+
+		rp := NewReverseProxy(log.New("test"), func(req *http.Request) {
+			fmt.Println(req.Header.Get("X-Forwarded-For"))
```
Comment (papagian) [inline pkg/util/proxyutil/reverse_proxy_test.go:35]: do we need this?

**Review by papagian — COMMENTED** [review]
LGTM, nice work; I left some minor comments

File: pkg/api/pluginproxy/pluginproxy.go (hunk 2 above)
Comment (marefr) [reply pkg/api/pluginproxy/pluginproxy.go:124]: We've done that since at least [5 years](https://github.com/grafana/grafana/commit/63d6ab476a9a767ff5bc7d4e093b5ec303c70d5d) so I don't see a problem with it. Just added it to the plugin proxy now as well. It's only the request body posted to Grafana HTTP API.

> Would debug level be more appropriate?

I think no, because you have to actively enable data proxy logging for it to be logged.

File: pkg/util/proxyutil/reverse_proxy_test.go (hunk 3 above)
Comment (marefr) [reply pkg/util/proxyutil/reverse_proxy_test.go:35]: No :smile: Good catch :+1: I'll fix

**Review by papagian — APPROVED** [review]

File: pkg/util/proxyutil/reverse_proxy.go (hunk 1 above)
Comment (marefr) [reply pkg/util/proxyutil/reverse_proxy.go:90]: > Is this where we change status for cancelled requests? 

Yes, that's correct. You don't think `logger.Debug("Proxy request cancelled")` is enough?

> I think 499 _might_ be more appropriate as well. It's not standard but fairly common for proxies. not sure. 400 could be confused with invalid input which we care more about.
> 
> https://httpstatus.in/499/

Yeah I did consider this status, but based on my minor read up sounded like this was only used by nginx. Have you seen this used in other places?

For the client/browser cancelling the request they'll never receive this status code - it's mainly for logs and metrics. Metrics for proxied request will need additional work outside of this, but one thought currently is that we shouldn't track request metrics for our proxies at all. If needed, we should track specific proxy metrics. Thoughts?

Comment (marefr) [reply pkg/util/proxyutil/reverse_proxy.go:90]: I'll push an update with 499.

Also found another good source for 499 https://www.belugacdn.com/499-error-code/

Comment (marefr) [reply pkg/util/proxyutil/reverse_proxy.go]: Done. Need to do some manual test to verify it works as expected

**Review by bergquist — APPROVED** [review]
LGTM <3

**Review by wbrowne — APPROVED** [review]
LGTM. Just noted one thing as a nit

File: pkg/util/proxyutil/reverse_proxy_test.go [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+		require.Empty(t, actualReq.Header.Get("Origin"))
+		require.Empty(t, actualReq.Header.Get("Referer"))
+		require.Equal(t, "value", actualReq.Header.Get("X-KEY"))
+		resp := rec.Result()
+		require.Empty(t, resp.Cookies())
+		require.Equal(t, "sandbox", resp.Header.Get("Content-Security-Policy"))
+		require.NoError(t, resp.Body.Close())
+	})
+
+	t.Run("Error handling should convert status codes depending on what kind of error it is", func(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (marefr) [reply pkg/util/proxyutil/reverse_proxy_test.go:87]: Good point. Pushed some changes

File: pkg/api/pluginproxy/ds_proxy.go [hunk 5]
```diff
@@ -115,45 +88,51 @@ func (proxy *DataSourceProxy) HandleRequest() {
...
 			}
-			return nil
-		},
+			_ = resp.Body.Close()
+
+			proxyErrorLogger.Info("Authentication to data source failed", "body", string(body), "statusCode",
+				resp.StatusCode)
+			msg := "Authentication to data source failed"
+			*resp = http.Response{
+				StatusCode:    400,
```
[the remark this answers is not in the document]
Comment (marefr) [reply pkg/api/pluginproxy/ds_proxy.go:119]: 1. This is not new. The reason to not return 401 is to not trigger a basic authentication challenge in the browser that would popup and require basic auth username and password to be filled in.
2. Would suggest to open a new issue and include details showing Grafana is actually converting 429 to 400 and/or all 4xx to 400 for requests going through the Grafana datasource proxy.

[the remark this answers is not in the document]
Comment (raggupta-ms) [reply pkg/api/pluginproxy/ds_proxy.go:119]: ok, thanks will open a new issue!
