### PR TITLE
Dashboard: Schema V2 - Fix annotations losing queries

### LINKED ISSUE #103308: Dashboards: Schema V2 - Annotations losing `query` from v1 to v2 transformation
When saving a v1 dashboard to v2  (using the `dashboardsNewLayout` feature toggle), annotations are losing queries

[Slack](https://raintank-corp.slack.com/archives/C07QVGH37D4/p1743460179903609)

BugLosingQueries

### Problem:
`targets`  definitions are not consistent across annotation datasources.

*Example: Prometheus and Postgres*

a v1 dashboard, with prometheus datasource annotations will look like:
 ```
    {
        "datasource": {...},
        "enable": true,
        "expr": "{alertname=\"AppCrash\"}", --- THIS IS THE QUERY
        "hide": false,
        "iconColor": "red",
        "name": "prom-annnot",
        "step": "12",  --- THIS IS THE QUERY
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        }
      }
    ]
```
Notice that the "target" or query is outside of the target prop

How does it works? The Prometheus annotation query editor constructs the query using: expr, refId, interval --- [AnnotationQueryEditor.tsx#L21](https://github.com/grafana/grafana/blob/main/packages/grafana-prometheus/src/components/AnnotationQueryEditor.tsx#L21)

Now a Postgres DS will look like (notice here, everything is inside target )
```
{
        "datasource": {...},
        "enable": true,
        "hide": false,
        "iconColor": "red",
        "name": "postgress-ds",
        "target": {
          "editorMode": "builder",
          "format": "table",
          "limit": 100,
          "matchAny": false,
          "rawSql": "SELECT * FROM grafana_metric LIMIT 50 ",
          "refId": "A",
          "sql": {
            "columns": [
              {
                "parameters": [
                  {
                    "name": "*",
                    "type": "functionParameter"
                  }
                ],
                "type": "function"
              }
            ],
            "groupBy": [
              {
                "property": {
                  "type": "string"
                },
                "type": "groupBy"
              }
            ],
            "limit": 50
          },
          "table": "grafana_metric",
          "tags": [],
          "type": "dashboard"
        }
      }
    ]
  },
```

This creates a conflict with our annotation schema definition, because we assumed the target will be contained in query; however, if we do that, we break the Prometheus annotation query editor.  

In this [PR](https://github.com/grafana/grafana/pull/102951/commits/06ab1ab28ab1034ce2667970d923a55d44b43f78) I tried the approach of adding other props that could be outside of the query,but it doesn't work, as we only stored in the db things that are defined in the schema.

```
AnnotationQueryKind: {
	kind: "AnnotationQuery"
	spec: AnnotationQuerySpec
}

AnnotationQuerySpec: {
	datasource?: DataSourceRef
	query?:      DataQueryKind --- NOT ALL DS have the query contained
	enable:      bool
	hide:        bool
	iconColor:   string
	name:        string
	builtIn?:    bool | *false
	filter?:     AnnotationPanelFilter
}
```

Known data sources that will be impacted if we don't use the extra prop options:
Prometheus
Loki
Victoria Metrics ([code](https://github.com/VictoriaMetrics/victoriametrics-datasource/blob/3ab87ed69136dc561cdbe7307b4ecaf8a3d82d08/src/components/Annotations/AnnotationQueryEditor.tsx#L21))

### PR DESCRIPTION
**Pull request by axelavargas**
Fixes annotations losing queries when saving v1 with dynamic dashboard

### Problem
`targets`  definitions are not consistent across annotation datasources.  

### Approach
To fix This PR adds an options field to annotations to store datasource-specific properties. The implementation:

- Adds `options` to v2 annotation schema definitions
- Preserves `options` during annotation edits in v2 dashboards
- Propagates `options` properties to root level for compatibility with datasource editors 
- Automatically collects non-standard properties into `options` when saving v2 dashboards
- Maintains backward compatibility with v1 dashboards

#### Known data sources that will be affected if we don't use the extra prop `options`:

- Prometheus
- Loki
- Victoria Metrics ([code](https://github.com/VictoriaMetrics/victoriametrics-datasource/blob/3ab87ed69136dc561cdbe7307b4ecaf8a3d82d08/src/components/Annotations/AnnotationQueryEditor.tsx#L21))
- elastic search - query editor
- cloudwatch - migration
- azuremonitor - migration

To reproduce this uncomment this line https://github.com/grafana/grafana/blob/a59e7e14b1fe68524010542eae0a8161e7f50b65/packages/grafana-data/src/types/annotations.ts#L22, and then run yarn typecheck

BugLosingQueries

Fixes: #103308

### CODE REVIEW

File: public/app/features/dashboard-scene/serialization/transformSceneToSaveModelSchemaV2.ts [hunk 1]
```diff
@@ -404,11 +404,31 @@ function getAnnotations(state: DashboardSceneState): AnnotationQueryKind[] {
...
+        },
+      };
+    } else if (layer.state.query.target) {
+      // Transform old target structure to new query structure for non-built-in annotations
+      result.spec.query = {
+        kind: getAnnotationQueryKind(layer.state.query),
+        spec: {
+          ...layer.state.query.target,
+          // Include any datasource-specific query properties (like expr for Prometheus)
+          ...(layer.state.query.expr && { expr: layer.state.query.expr }),
```
Comment (dprokop) [inline public/app/features/dashboard-scene/serialization/transformSceneToSaveModelSchemaV2.ts:425]: I think over here we should take _any_ property (not only `expr`) that is not a property of the annotation spec.


Do you know how prometheus ends up adding `expr` to the annotation json, rathen than the target?

File: public/app/features/dashboard-scene/serialization/transformSceneToSaveModelSchemaV2.ts [hunk 2]
```diff
@@ -404,11 +404,31 @@ function getAnnotations(state: DashboardSceneState): AnnotationQueryKind[] {
...
+        },
+      };
+    } else if (layer.state.query.query?.kind) {
+      // Use new query structure if it exists
+      result.spec.query = {
+        kind: layer.state.query.query.kind,
         spec: layer.state.query.query.spec,
```
Comment (dprokop) [inline public/app/features/dashboard-scene/serialization/transformSceneToSaveModelSchemaV2.ts:432]: Don't understand why we need this `else if`.

File: public/app/features/dashboard-scene/serialization/transformSceneToSaveModelSchemaV2.ts [hunk 3]
```diff
@@ -404,11 +404,31 @@ function getAnnotations(state: DashboardSceneState): AnnotationQueryKind[] {
...
 
-    // Check if DataQueryKind exists
-    const queryKind = getAnnotationQueryKind(layer.state.query);
-    if (layer.state.query.query?.kind === queryKind) {
+    // For built-in annotations, always use grafana kind but respect target if it exists
+    if (layer.state.query.builtIn) {
       result.spec.query = {
-        kind: queryKind,
+        kind: 'grafana',
+        spec: layer.state.query.target || {
```
[the remark this answers is not in the document]
Comment (axelavargas) [reply public/app/features/dashboard-scene/serialization/transformSceneToSaveModelSchemaV2.ts:411]: When we filter by tags, we get the `target` 

built-in-ds

File: public/app/features/dashboard-scene/serialization/transformSceneToSaveModelSchemaV2.ts (hunk 2 above)
Comment (axelavargas) [reply public/app/features/dashboard-scene/serialization/transformSceneToSaveModelSchemaV2.ts]: We can have cases where `query.query` is not defined, like grafana annotations with no tags or other prop that could generate a target property

P.S I added a comment to the if to make it clear 😄

**Review by harisrozajac — APPROVED** [review]
Great work on this 🚀 I've tested with prometheus and verified that fields necessary for query editor are persisted in options field, and when a dashboard load annotations are applied correctly and populated in the query editor

**Review by ivanortegaalba — APPROVED** [review]
It works! 💯 

Do you mind creating an issue to follow up on the `options` approach? Thank you Alexa for taking care of this and sorry for the delay

File: public/app/features/dashboard-scene/serialization/transformSaveModelSchemaV2ToScene.ts [hunk 4]
```diff
@@ -88,10 +88,19 @@ export function transformSaveModelSchemaV2ToScene(dto: DashboardWithAccessInfo<D
...
+      AnnoQuerySpec = {
+        ...AnnoQuerySpec,
+        ...AnnoQuerySpec.options,
+      };
+    }
     return new DashboardAnnotationsDataLayer({
       key: uniqueId('annotations-'),
       query: {
-        ...annotation.spec,
+        ...AnnoQuerySpec,
```
[the remark this answers is not in the document]
Comment (axelavargas) [reply public/app/features/dashboard-scene/serialization/transformSaveModelSchemaV2ToScene.ts:103]: no reason, probably a typo in the first letter

**Comment by axelavargas** [comment]
> It works! 💯
> 
> Do you mind creating an issue to follow up on the `options` approach? Thank you Alexa for taking care of this and sorry for the delay

yes! https://github.com/grafana/grafana/issues/103688
