### PR TITLE
Alerting: Fix database unavailable removes rules from scheduler

### LINKED ISSUE #49855: Alerting: Database not available will cause rule evaluation to be stopped
**What happened**:

From @grobinson-grafana:

> We call https://github.com/grafana/grafana/blob/1cc034d9606af3fdc69a0816245f8a712b27ab25/pkg/services/ngalert/schedule/schedule.go#L365
But if err is not nil we return a nil slice https://github.com/grafana/grafana/blob/1c679e814b1e031a351c3d2c066eb85d8633150d/pkg/services/ngalert/schedule/fetcher.go#L20-L23
This is used to set up readyToRun so if the slice is nil there will be no ready to run items https://github.com/grafana/grafana/blob/1cc034d9606af3fdc69a0816245f8a712b27ab25/pkg/services/ngalert/schedule/schedule.go#L380-L381
https://github.com/grafana/grafana/blob/1cc034d9606af3fdc69a0816245f8a712b27ab25/pkg/services/ngalert/schedule/schedule.go#L421-L430

**What you expected to happen**:

Database or query failure should not stop rule evaluation.

**How to reproduce it (as minimally and precisely as possible)**:

Setup an alert rule, make the database fail, and your alert rule will not continue to be evaluated.

### PR DESCRIPTION
**Pull request by grobinson-grafana**
**What this PR does / why we need it**:

This pull request fixes a bug in Grafana where intermittent failure of database, network between Grafana and the database, or error in querying the database would cause all alert rules to be unscheduled in Grafana. This pull request fixes this so alert rules are not changed unless the query is successful.

**Which issue(s) this PR fixes**:

Fixes #49855

**Special notes for your reviewer**:

# Release notice breaking change

This change fixes a bug in Grafana where intermittent failure of database, network between Grafana and the database, or error in querying the database would cause all alert rules to be unscheduled in Grafana. Following this change scheduled alert rules are not updated unless the query is successful.

The `get_alert_rules_duration_seconds` metric has been renamed to `schedule_query_alert_rules_duration_seconds`.

### CODE REVIEW

File: pkg/services/ngalert/schedule/fetcher.go [hunk 1]
```diff
@@ -16,10 +19,21 @@ func (sch *schedule) getAlertRules(ctx context.Context, disabledOrgs []int64) []
...
 		ExcludeOrgIDs: disabledOrgs,
 	}
-	err := sch.ruleStore.GetAlertRulesForScheduling(ctx, &q)
-	if err != nil {
-		sch.log.Error("failed to fetch alert definitions", "err", err)
-		return nil
+
+	// If the database is unavailable or the query returns an error then return
+	// the alert rules from the most recent tick
+	if err := sch.ruleStore.GetAlertRulesForScheduling(ctx, &q); err != nil {
```
Comment (gotjosh) [inline pkg/services/ngalert/schedule/fetcher.go:25]: Good shout on the result ordering - if you add:

```golang
		if err := q.OrderBy("uid desc").Find(&alerts); err != nil {
			return err
		}
```

To `GetAlertRulesForScheduling` you should get a consistent and ordered set of rules.

From there you should be able to consistently compute the correct hash.

File: pkg/services/ngalert/schedule/fetcher.go [hunk 2]
```diff
@@ -16,10 +19,21 @@ func (sch *schedule) getAlertRules(ctx context.Context, disabledOrgs []int64) []
...
+		sch.log.Error("failed to get most recent alert rules", "error", err)
```
Comment (gotjosh) [inline pkg/services/ngalert/schedule/fetcher.go:26]: How do you feel about including the number of alerts we're about to return from the cache?

File: pkg/services/ngalert/metrics/ngalert.go [hunk 3]
```diff
@@ -52,6 +52,7 @@ type Scheduler struct {
 	EvalFailures             *prometheus.CounterVec
 	EvalDuration             *prometheus.SummaryVec
 	GetAlertRulesDuration    prometheus.Histogram
+	GetAlertRulesFailures    prometheus.Counter
```
Comment (gotjosh) [inline pkg/services/ngalert/metrics/ngalert.go:55]: I don't think a counter tells us much - I feel strongly about a gauge with the hash of the current rule set to track changes over time.

Something like `RuleSetHash` for the variable name and its type should be a `prometheus.Gauge`.

For the metric details:

I suggest the name `shedule_ruleset_hash", where its value is the hash -> float64. If you're short on time, feel free to leave it for the next PR.

**Review by gotjosh — COMMENTED** [review]
LGTM, but please see my comments I'm happy to take another look.

**Comment by gotjosh** [comment]
We also need a changelog entry.

File: pkg/services/ngalert/metrics/ngalert.go (hunk 3 above)
Comment (grobinson-grafana) [reply pkg/services/ngalert/metrics/ngalert.go]: I started to work on this but one observation I have is that the values will be so large (64 bit checksum as a float64) that I think it will be difficult to show in Grafana because the Y axis will have to scale between min and max of a 64 bit float?

**Review by yuri-tceretian — CHANGES_REQUESTED** [review]
Scheduler has two methods that provide the ability to update\delete rule (methods DeleteAlertRule and UpdateAlertRule). I think we should update the cache when DeleteAlertRule is called

File: pkg/services/ngalert/schedule/fetcher.go [hunk 4]
```diff
@@ -2,24 +2,56 @@ package schedule
...
-		sch.log.Error("failed to fetch alert definitions", "err", err)
-		return nil
+	if err := sch.ruleStore.GetAlertRulesForScheduling(ctx, &q); err != nil {
+		defer sch.metrics.UpdateSchedulableAlertRulesFailures.Inc()
+		return fmt.Errorf("failed to get alert rules: %w", err)
 	}
-	return q.Result
+	sch.schedulableAlertRules.set(q.Result)
+	sch.metrics.SchedulableAlertRules.Set(float64(len(q.Result)))
+	sch.metrics.SchedulableAlertRulesHash.Set(float64(hashUIDs(q.Result)))
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/schedule/fetcher.go:55]: These metrics are changed only during the eval cycle (i.e. every 10 seconds). However, if a rule is deleted from the registry via the delete method of the scheduler it will not be changed. 
I think that's ok. Just making sure that we are fine with this.

File: pkg/services/ngalert/schedule/registry.go [hunk 5]
```diff
@@ -111,3 +111,52 @@ type evaluation struct {
 	scheduledAt time.Time
 	version     int64
 }
+
+type schedulableAlertRulesRegistry struct {
+	rules map[models.AlertRuleKey]*models.SchedulableAlertRule
+	mu    sync.Mutex
+}
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/schedule/registry.go:118]: I think eventually we should merge these two registries into one so we will make sure of the consistency.

**Review by yuri-tceretian — APPROVED** [review]
LGTM. Great changes! 👍🏻

**Comment by yuri-tceretian** [comment]
This PR opens door for really great improvement in this area. The table alert_rule has field Updated which contains a timestamp of when the rule was updated. We can greatly reduce traffic to database if we request all records since the last update, i.e 
```
SELECT * FROM alert_rule WHERE Update > ?
```
where ? is MAX(update) FROM in_memory_alert_rules.

File: pkg/services/ngalert/metrics/ngalert.go [hunk 6]
```diff
@@ -163,24 +166,47 @@ func newSchedulerMetrics(r prometheus.Registerer) *Scheduler {
...
+				Help:      "The time taken to run the scheduler.",
 				Buckets:   []float64{0.1, 0.25, 0.5, 1, 2, 5, 10},
 			},
 		),
-		SchedulePeriodicDuration: promauto.With(r).NewHistogram(
+		SchedulableAlertRules: promauto.With(r).NewGauge(
+			prometheus.GaugeOpts{
+				Namespace: Namespace,
+				Subsystem: Subsystem,
+				Name:      "schedulable_alert_rules",
```
[the remark this answers is not in the document]
Comment (gotjosh) [reply pkg/services/ngalert/metrics/ngalert.go:182]: When looking at metrics you typically look by the prefix and is strange that metrics that are closely correlated have different (but a similar variation of the word schedule) and appear inconsistent. 

How do you feel about using the word of the component "schedule" as the prefix for all of them?

File: pkg/services/ngalert/metrics/ngalert.go [hunk 7]
```diff
@@ -163,24 +166,47 @@ func newSchedulerMetrics(r prometheus.Registerer) *Scheduler {
...
+				Help:      "The number of alert rules being considered for evaluation each tick.",
+			},
+		),
+		SchedulableAlertRulesHash: promauto.With(r).NewGauge(
+			prometheus.GaugeOpts{
+				Namespace: Namespace,
+				Subsystem: Subsystem,
+				Name:      "schedulable_alert_rules_hash",
```
[the remark this answers is not in the document]
Comment (gotjosh) [reply pkg/services/ngalert/metrics/ngalert.go:190]: Ditto from above.

File: pkg/services/ngalert/metrics/ngalert.go [hunk 8]
```diff
@@ -163,24 +166,47 @@ func newSchedulerMetrics(r prometheus.Registerer) *Scheduler {
...
+				Help:      "A hash of the alert rules over time.",
+			}),
+		UpdateSchedulableAlertRulesDuration: promauto.With(r).NewHistogram(
 			prometheus.HistogramOpts{
 				Namespace: Namespace,
 				Subsystem: Subsystem,
-				Name:      "schedule_periodic_duration_seconds",
-				Help:      "The time taken to run the scheduler.",
+				Name:      "update_schedulable_alert_rules_duration_seconds",
+				Help:      "The time taken to get update alert rules for the scheduler.",
```
[the remark this answers is not in the document]
Comment (gotjosh) [reply pkg/services/ngalert/metrics/ngalert.go:198]: This does not take into account the update time which is done outside of the function where this is measured.

File: pkg/services/ngalert/schedule/fetcher.go (hunk 4 above)
Comment (gotjosh) [reply pkg/services/ngalert/schedule/fetcher.go:55]: I don't think this is OK, metrics at all times should reflect an accurate state of the system.

File: pkg/services/ngalert/schedule/schedule.go [hunk 9]
```diff
@@ -314,9 +321,17 @@ func (sch *schedule) UpdateAlertRule(key models.AlertRuleKey) {
 
 // DeleteAlertRule stops evaluation of the rule, deletes it from active rules, and cleans up state cache.
 func (sch *schedule) DeleteAlertRule(key models.AlertRuleKey) {
+	// It can happen that the scheduler has deleted the alert rule before the
+	// Ruler API has called DeleteAlertRule. This can happen as requests to
+	// the Ruler API do not hold an exclusive lock over all scheduler operations.
+	if _, ok := sch.schedulableAlertRules.del(key); !ok {
+		sch.log.Info("alert rule cannot be removed from the scheduler as it is not scheduled", "uid", key.UID, "org_id", key.OrgID)
```
[the remark this answers is not in the document]
Comment (gotjosh) [reply pkg/services/ngalert/schedule/schedule.go:328]: Isn't this a bug? if you don't return you'll continue to stop the evaluation of the rule even though you couldn't remove it from the registry.

File: pkg/services/ngalert/schedule/schedule.go [hunk 10]
```diff
@@ -314,9 +321,17 @@ func (sch *schedule) UpdateAlertRule(key models.AlertRuleKey) {
...
+	}
+
+	// Delete the rule routine
 	ruleInfo, ok := sch.registry.del(key)
 	if !ok {
-		sch.log.Info("unable to delete alert rule routine information by key", "uid", key.UID, "org_id", key.OrgID)
+		sch.log.Info("alert rule cannot be stopped as it is not running", "uid", key.UID, "org_id", key.OrgID)
 		return
 	}
 	// stop rule evaluation
```
Comment (gotjosh) [inline pkg/services/ngalert/schedule/schedule.go:337]:
```suggestion
	// stop rule evaluation
	sch.metrics.SchedulableAlertRules.Sub(1)
```

I can't comment on the line below but this must go right after the call to stop.

File: pkg/services/ngalert/schedule/schedule.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (gotjosh) [reply pkg/services/ngalert/schedule/schedule.go:328]: On second thought, I think the problem is `schedulableAlertRules.del` - the boolean returned is not to indicate whether the operation was successful or not is to indicate that the key was not found (?) I don't think this is right please see my comment there and with that this log line (which seems to assume the same I did) can be removed.

File: pkg/services/ngalert/schedule/registry.go [hunk 11]
```diff
@@ -111,3 +111,52 @@ type evaluation struct {
...
+
+func (r *schedulableAlertRulesRegistry) del(k models.AlertRuleKey) (*models.SchedulableAlertRule, bool) {
+	r.mu.Lock()
+	defer r.mu.Unlock()
+	rule, ok := r.rules[k]
+	if ok {
+		delete(r.rules, k)
+	}
+	return rule, ok
+}
```
Comment (gotjosh) [inline pkg/services/ngalert/schedule/registry.go:162]:
```suggestion
func (r *schedulableAlertRulesRegistry) del(k models.AlertRuleKey) {
	r.mu.Lock()
	defer r.mu.Unlock()
	rule, ok := r.rules[k]
	if ok {
		delete(r.rules, k)
	}
}
```

Comment (gotjosh) [reply pkg/services/ngalert/schedule/registry.go:162]: I think this implementation needs to be slightly different to the one in `alertRuleInfoRegistry`.

`alertRuleInfoRegistry` uses the delete operation to also stop the rule - we don't have to do that here. (I also think this opens the door to a potential refactor of using `get` and `del` for the stopping operation as opposed to just a `del` but there's another topic for another day and def not part of this PR)

**Review by gotjosh — COMMENTED** [review]
Overall LGTM, but please see my comments.

File: pkg/services/ngalert/metrics/ngalert.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (grobinson-grafana) [reply pkg/services/ngalert/metrics/ngalert.go:182]: Should we use `scheduler` as the prefix?

File: pkg/services/ngalert/schedule/schedule.go [hunk 12]
```diff
@@ -362,7 +377,11 @@ func (sch *schedule) schedulePeriodic(ctx context.Context) error {
 				disabledOrgs = append(disabledOrgs, disabledOrg)
 			}
 
-			alertRules := sch.getAlertRules(ctx, disabledOrgs)
+			if err := sch.updateSchedulableAlertRules(ctx, disabledOrgs); err != nil {
+				sch.log.Error("scheduler failed to update alert rules", "error", err)
```
[the remark this answers is not in the document]
Comment (grobinson-grafana) [reply pkg/services/ngalert/schedule/schedule.go:381]: Should we use `err` rather than `error`? We seem to use both in ngalert and I wasn't sure which one we recommend.

File: pkg/services/ngalert/schedule/registry.go (hunk 11 above)
Comment (grobinson-grafana) [reply pkg/services/ngalert/schedule/registry.go:162]: I like that both registries have similar function signatures. We don't need to remove the return values just because we don't use them?

File: pkg/services/ngalert/metrics/ngalert.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (gotjosh) [reply pkg/services/ngalert/metrics/ngalert.go:182]: I have a slight preference for the word `schedule` instead of the component `scheduler` - the latter is most likely to change than the former. Up to you really.

File: pkg/services/ngalert/schedule/registry.go (hunk 5 above)
Comment (grobinson-grafana) [reply pkg/services/ngalert/schedule/registry.go:118]: It might be easier to merge them sooner rather than later as I am finding it hard to reason about the scheduler when we have separate registries.

File: pkg/services/ngalert/schedule/schedule.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (gotjosh) [reply pkg/services/ngalert/schedule/schedule.go:328]: If we make `del` idempotent as suggested, I don't think the above can happen - am I missing something?

[the remark this answers is not in the document]
Comment (grobinson-grafana) [reply pkg/services/ngalert/schedule/schedule.go:328]: It can't happen either right now, it would only happen if we add a `return` statement when `ok` is false.

File: pkg/services/ngalert/CHANGELOG.md [hunk 13]
```diff
@@ -45,6 +45,7 @@ Scopes must have an order to ensure consistency and ease of search, this helps u
 
 ## Grafana Alerting - main / unreleased
 
+- [ENHANCEMENT] Scheduler: Metric `get_alert_rules_duration_seconds` has been renamed to `schedule_query_alert_rules_duration_seconds`.
```
Comment (gotjosh) [inline pkg/services/ngalert/CHANGELOG.md:48]:
```suggestion
- [ENHANCEMENT] Scheduler: Adds new metrics to track rules that might be scheduled.
  - `grafana_alerting_schedule_alert_rules `
  - `grafana_alerting_schedule_alert_rules_hash `
- [CHANGE] Scheduler: Renaming of metrics to make them consistent with similar metrics exposed by the component.
  - `grafana_alerting_get_alert_rules_duration_seconds` to `grafana_alerting_schedule_periodic_duration_seconds
  - `grafana_alerting_schedule_periodic_duration_seconds` to `grafana_alerting_schedule_query_alert_rules_duration_seconds`
  - 
```

**Review by gotjosh — APPROVED** [review]
LGTM
