### PR TITLE
Build: Fix Redis/Memcached integration tests

### LINKED ISSUE #60587: Build: Redis/Memcached integration tests problems
https://github.com/grafana/grafana-enterprise/pull/3503 removed build tags for redis/memcached in enterprise. OSS still has build tags for redis and memcached and seems like we never run these?
- https://github.com/grafana/grafana/blob/main/pkg/infra/remotecache/redis_storage_integration_test.go
- https://github.com/grafana/grafana/blob/main/pkg/services/live/managedstream/cache_redis_test.go
- https://github.com/grafana/grafana/blob/main/pkg/infra/remotecache/memcached_storage_integration_test.go

Memcached/redis integration tests sets the `GRAFANA_TEST_DB` to mysql in drone config, https://github.com/grafana/grafana/blob/ecf83a6df9db948992df61e369a85447383da2c4/.drone.yml#L3223-L3225, meaning that redis and memcached integration tests are running all integration tests using mysql again plus any redis/memcached integration tests.

Redis/memcached integration tests using mysql which takes 18+ minutes plus redis or memcached which takes ~2min. Optimally redis and memcached integration test steps should take 2min each instead of 20min

**Suggested/discussed solution:**
- Remove usage of `redis` and `memcached` build tags (should only be left in OSS)
- New naming rule for redis/memcached test:
  - all redis integration tests prefixed `TestRedisIntegration` and in Drone run `go list './pkg/...' | xargs -I {} sh -c 'go test -run RedisIntegration -covermode=atomic`
  - all memcached integration tests prefixed `TestMemcachedIntegration` and in Drone run `go list './pkg/...' | xargs -I {} sh -c 'go test -run MemcachedIntegration -covermode=atomic`

### PR DESCRIPTION
**Pull request by papagian**
**What is this feature?**

Cache tests didn't use to run: they were ignored in OSS and in enterprise the integration tests used to re-run instead of them

**Why do we need this feature?**

This fix:
- removes build tags from OSS cache tests
- skips these tests when `-test.short` flag is set and when the expected environmental variables are not set (`REDIS_URL` for the redis and `MEMCACHED_HOSTS` for the memcached ones)
- updates release CI pipeline to run cache  redis/memcached instead of integration tests
- adds redis/memcached tests in the other pipelines (pr, main)

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #60587

**Special notes for your reviewer**:
for testing locally:
```sh
make devenv sources=redis,memcached
make test-go-integration-redis
make test-go-integration-memcached
```

the redis tests used to fail therefore ~I had to make [these changes](https://github.com/grafana/grafana/pull/64298/commits/5350751673367ea0a808538828c50e7118561a2e) but I'm not at ll sure if the cache is supposed to behave this way.~ I have reverted this change and I have modified the tests instead

### CODE REVIEW

**Comment by papagian** [comment]
it seems there is inconsistency on the expected redis URL in [OSS](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#redis) and [enterprise](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/enterprise-configuration/#url-3)
so either the tests should accept both or adopt the same (breaking change)

File: pkg/infra/remotecache/remotecache_test.go [hunk 1]
```diff
@@ -95,7 +95,8 @@ func canPutGetAndDeleteCachedObjects(t *testing.T, client CacheStorage) {
 	assert.Equal(t, err, nil)
 
 	_, err = client.Get(context.Background(), "key1")
-	assert.Equal(t, err, ErrCacheItemNotFound)
+	// redis client returns redis.Nil error when key does not exist.
+	assert.Error(t, err)
```
Comment (papagian) [inline pkg/infra/remotecache/remotecache_test.go:99]: not sure if the redis implementation should change instead and return `ErrCacheItemNotFound` in that case

File: scripts/drone/steps/lib.star [hunk 2]
```diff
@@ -1143,7 +1143,7 @@ def redis_integration_tests_step():
         "commands": [
             "dockerize -wait tcp://redis:6379/0 -timeout 120s",
             "go clean -testcache",
-            "go list './pkg/...' | xargs -I {} sh -c 'go test -run Integration -covermode=atomic -timeout=5m {}'",
+            "go test -run IntegrationRedis -covermode=atomic -timeout=30m ./pkg/...",
```
Comment (zerok) [inline scripts/drone/steps/lib.star:1146]: Do you really need a timeout of 30 minutes here?

File: scripts/drone/services/services.star [hunk 3]
```diff
@@ -36,21 +36,20 @@ def integration_test_services(edition):
...
-                    "environment": {},
-                },
-                {
-                    "name": "memcached",
-                    "image": "memcached:1.6.9-alpine",
-                    "environment": {},
-                },
-            ],
-        )
+    services.extend(
```
Comment (zerok) [inline scripts/drone/services/services.star:39]: Please add them directly to the service list above if this is no longer conditional 🙂

File: scripts/drone/events/release.star [hunk 4]
```diff
@@ -266,7 +266,7 @@ def enterprise_pipelines(ver_mode = ver_mode, trigger = release_trigger):
 
     environment = {"EDITION": "enterprise"}
 
-    services = integration_test_services(edition = "enterprise")
+    services = integration_test_services()
```
Comment (zerok) [inline scripts/drone/events/release.star:269]: Since now *all* services are launched, does it also make sense to run the redis/memcached integration tests for non-enterprise builds (line 338)?

**Review by zerok — CHANGES_REQUESTED** [review]
Thank you so much for working on this ❤️

File: pkg/infra/remotecache/remotecache_test.go (hunk 1 above)
Comment (bergquist) [reply pkg/infra/remotecache/remotecache_test.go:99]: Sounds like a good idea but perhaps in another PR.

File: .drone.yml [hunk 5]
```diff
@@ -797,6 +797,12 @@ services:
   volumes:
   - name: mysql
     path: /var/lib/mysql
+- environment: {}
+  image: redis:6.2.1-alpine
```
Comment (DanCech) [inline .drone.yml:801]: this is a 2 year old version, should we be using 6.2.11 (latest 6.2.x) or 7.0.10 (current stable) instead?

Comment (papagian) [reply .drone.yml:801]: it seems that in cloud we use [another image](https://github.com/grafana/deployment_tools/blob/28f2a0d86338e8150a57814fdfa0e1c53461db8a/ksonnet/lib/hosted-grafana/images.libsonnet#L21)
it would make sense to use the same, @grafana/grafana-delivery WDYT?

**Comment by kminehart** [comment]
> it seems there is inconsistency on the expected redis URL in [OSS](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#redis) and [enterprise](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/enterprise-configuration/#url-3) so either the tests should accept both or adopt the same (breaking change)

You could allow for both in Enterprise and make this a non-breaking change.

In Enterprise, `redis.ParseURL` https://pkg.go.dev/github.com/go-redis/redis#ParseURL is used to parse the URL. I imagine, if that returns an error, then we could attempt to parse the URL the same way as OSS does.

File: scripts/drone/events/release.star (hunk 4 above)
Comment (papagian) [reply scripts/drone/events/release.star:269]: not sure I understand: do you mean since in enterprise builds will run also the OSS ones we don't need to run them for non-enterprise builds?

**Comment by papagian** [comment]
> > it seems there is inconsistency on the expected redis URL in [OSS](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#redis) and [enterprise](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/enterprise-configuration/#url-3) so either the tests should accept both or adopt the same (breaking change)
> 
> You could allow for both in Enterprise and make this a non-breaking change.
> 
> In Enterprise, `redis.ParseURL` https://pkg.go.dev/github.com/go-redis/redis#ParseURL is used to parse the URL. I imagine, if that returns an error, then we could attempt to parse the URL the same way as OSS does.
> 
> I don't know for sure but I have a feeling that `ParseURL` will also handle connection strings. But I'm just guessing

yes, that's exactly what I have ended up [doing](https://github.com/grafana/grafana/pull/64298/files#diff-667c888dc0457bb7078b721c9798117ccc9deadd9b8e462ebc0209bd14774444)

**Comment by kminehart** [comment]
ah I didn't see that! awesome, don't mind me then :joy:

File: scripts/drone/events/release.star (hunk 4 above)
Comment (kminehart) [reply scripts/drone/events/release.star:269]: I think Horst is suggesting that redis/memcached tests might not be running for non-enterprise builds. For context, when I added them, enterprise was the only one that had redis/memcached integration tests.

File: .drone.yml (hunk 5 above)
Comment (kminehart) [reply .drone.yml:801]: i think it makes sense to use the same.

File: scripts/drone/events/release.star (hunk 4 above)
Comment (papagian) [reply scripts/drone/events/release.star:287]: thank for the clarification: I have addeed them also in the OSS builds

File: .drone.yml (hunk 5 above)
Comment (papagian) [reply .drone.yml]: I have ended up using the `redis:6.2.11-alpine` for now because the image used by cloud [requires extra setup for setting a password](https://drone.grafana.net/grafana/grafana/109102/8/4) so it requires extra work for modifying the `REDIS_URL` for test to include it

**Review by kminehart — APPROVED** [review]

**Review by DanCech — APPROVED** [review]
Nice!

**Review by zerok — APPROVED** [review]
