### PR TITLE
Explore/Logs: Improve and add descriptions of Explore's Escape newlines feature

### LINKED ISSUE #45770: Docs: Improve wording for tooltip in "Add escaping feature" in Explore
A ~year ago we have added this [smart feature](https://github.com/grafana/grafana/pull/31352) to Explore that checks if it is possible that logs have incorrectly escaped log content and if so, we add option to try to escape it correctly. 

**What was mentioned in original PR:**

```
❗️What is very important - we should communicate to users that the lines aren't correctly 
escaped and that the first step should be fixing escaping. However, for some logs it is very 
hard/almost impossible to correctly escape them. And for thos cases, we would provide them 
with a feature that would replace incorrectly escapes newlines with actual newlines. Of course, 
it might always produce incorrect results, as we don't know which characters are actual newlines
 and which have just the \n pattern, but I think that if we communicate it clearly, users will 
understand.
```

So we added to tooltip following info: `We suggest to try to fix the escaping of your log lines first. This is an experimental feature, your logs might not be correctly escaped."`

However, we got feedback from users that `This is an experimental feature` makes them feel like we might remove this feature which we don't plan. So we could improve wording to remove `experimental feature` wording.

This is how feature looks:
image

https://user-images.githubusercontent.com/30407135/155304940-738a1f72-3391-4d22-a90b-e66b0f77b8bc.mov

### PR DESCRIPTION
**Pull request by gguillotte-grafana**
**What this PR does / why we need it**:

Per issue #45770, the tooltip describing the "Escape newlines" feature in Explore suggests the feature is experimental, which can be interpreted to mean the feature might be removed. The intent was to communicate to users that the results should be manually confirmed, since the automatic replacement of incorrectly escaped sequences might not always be accurate.

This PR rewrites the tooltip to clarify these points, and adds documentation describing the feature.

**Which issue(s) this PR fixes**:

Fixes #45770 

**Special notes for your reviewer**:

This PR changes a tooltip in code and also adds supporting documentation. Please let me know if these changes should be split into separate PRs for the code change and docs addition.

### CODE REVIEW

**Review by gelicia — APPROVED** [review]

**Comment by ivanahuckova** [comment]
This is awesome! Thanks @gguillotte-grafana for tackling this.

File: public/app/features/explore/LogsMetaRow.tsx [hunk 1]
```diff
@@ -71,7 +71,7 @@ export const LogsMetaRow: React.FC<Props> = React.memo(
         label: 'Your logs might have incorrectly escaped content',
         value: (
           <Tooltip
-            content="We suggest to try to fix the escaping of your log lines first. This is an experimental feature, your logs might not be correctly escaped."
+            content="Attempt to automatically fix incorrectly escaped newline and tab sequences in log lines. Manually review the results to confirm that the replacements are correct."
```
Comment (achatterjee-grafana) [inline public/app/features/explore/LogsMetaRow.tsx:74]:
```suggestion
            content="Fix incorrectly escaped newline and tab sequences in log lines. Manually review the results to confirm that the replacements are correct."
```

File: docs/sources/explore/logs-integration.md [hunk 2]
```diff
@@ -97,6 +97,16 @@ You can change the order of received logs from the default descending order (new
 
 Each log row has an extendable area with its labels and detected fields, for more robust interaction. For all labels we have added the ability to filter for (positive filter) and filter out (negative filter) selected labels. Each field or label also has a stats icon to display ad-hoc statistics in relation to all displayed logs.
 
+### Escaping newlines
+
+> **Note:** Available in Grafana 7.5 and later versions.
+
+Explore can automatically detect and attempt to fix incorrectly escaped sequences in log lines, such as newlines (`\n`, `\r`) or tabs (`\t`). This feature appears only when Explore detects incorrectly escaped sequences.
```
Comment (achatterjee-grafana) [inline docs/sources/explore/logs-integration.md:104]:
```suggestion
Explore can automatically detect and attempt to fix incorrectly escaped sequences in log lines, such as newlines (`\n`, `\r`) or tabs (`\t`). 
```

File: docs/sources/explore/logs-integration.md [hunk 3]
```diff
@@ -97,6 +97,16 @@ You can change the order of received logs from the default descending order (new
...
+
+1. Click the "Escape newlines" button to fix incorrectly escaped sequences.
```
Comment (achatterjee-grafana) [inline docs/sources/explore/logs-integration.md:106]:
```suggestion
1. Click the "Escape newlines" option to fix incorrectly escaped sequences.
```

File: docs/sources/explore/logs-integration.md [hunk 4]
```diff
@@ -97,6 +97,16 @@ You can change the order of received logs from the default descending order (new
...
+2. Manually review the replacements to confirm that the detection and replacement were correct.
```
Comment (achatterjee-grafana) [inline docs/sources/explore/logs-integration.md:107]:
```suggestion
2. Manually review the replacements to confirm that the detection and replacement are correct.
```

File: docs/sources/explore/logs-integration.md [hunk 5]
```diff
@@ -97,6 +97,16 @@ You can change the order of received logs from the default descending order (new
...
+3. To revert the replacements, click "Remove escaping".
```
Comment (achatterjee-grafana) [inline docs/sources/explore/logs-integration.md:108]:
```suggestion
3. If you need to revert the replacements, then click "Remove escaping".
```

**Review by achatterjee-grafana — COMMENTED** [review]
Added doc review.

File: public/app/features/explore/LogsMetaRow.tsx (hunk 1 above)
Comment (gguillotte-grafana) [reply public/app/features/explore/LogsMetaRow.tsx:74]: Thanks! I waffled on whether to be this explicit about the feature's reliability.

File: docs/sources/explore/logs-integration.md (hunk 2 above)
Comment (gguillotte-grafana) [reply docs/sources/explore/logs-integration.md:104]: This feature won't be visible in many circumstances. I'm concerned that omitting the conditional nature (and concerns about reliability that led to calling it "experimental") could confuse users who expect it to be visible. Is there a better way to emphasize this?

Comment (achatterjee-grafana) [reply docs/sources/explore/logs-integration.md:104]: How about "The "Escape newlines" option is available only when Explore detects incorrectly escaped sequences."

Comment (achatterjee-grafana) [reply docs/sources/explore/logs-integration.md:104]: Also, this capability is probably no longer "experimental". Might be worth it to find out more.

File: docs/sources/explore/logs-integration.md (hunk 5 above)
Comment (gguillotte-grafana) [reply docs/sources/explore/logs-integration.md:108]: Reverting should be a separate (if one-step) task, and this should also mention that the option changes, so I'll rewrite.

File: docs/sources/explore/logs-integration.md (hunk 2 above)
Comment (gguillotte-grafana) [reply docs/sources/explore/logs-integration.md:104]: > Also, this capability is probably no longer "experimental". Might be worth it to find out more.

The linked issue has some discussion about this. "Experimental" here referred to the relative reliability of detection and replacement, not the supportability of the feature.

> I would actually remove the note "Available in Grafana 7.5 and later versions".

👍🏻

**Comment by Elfo404** [comment]
@achatterjee-grafana can you take a look please?

File: public/app/features/explore/LogsMetaRow.tsx (hunk 1 above)
Comment (achatterjee-grafana) [reply public/app/features/explore/LogsMetaRow.tsx:74]: "Attempt to automatically fix" does not read well, it can also reduce user confidence in the feature capability.

The preceding label says: "'Your logs might have incorrectly escaped content'. So, perhaps say: "Automatically fix incorrectly ..."

File: docs/sources/explore/logs-integration.md [hunk 6]
```diff
@@ -97,6 +97,17 @@ You can change the order of received logs from the default descending order (new
...
+### Escaping newlines
+
+Explore automatically detects some incorrectly escaped sequences in log lines, such as newlines (`\n`, `\r`) or tabs (`\t`). When it detects such sequences, Explore provides an "Escape newlines" option.
+
+To automatically fix detected incorrectly escaped sequences:
+
+1. Click "Escape newlines" to replace the sequences.
+2. Manually review the replacements to confirm their correctness.
+
+After replacing these sequences, Explore changes the option from "Escape newlines" to "Remove escaping". Clicking this option reverts the replacements.
```
Comment (achatterjee-grafana) [inline docs/sources/explore/logs-integration.md:109]:
```suggestion
If you want to revert the replacements, then click the "Remove escaping" option.
```

**Review by achatterjee-grafana — COMMENTED** [review]
Added doc review.

**Comment by Elfo404** [comment]
@grafana/observability-logs-and-traces do you mind having a second look at this? AFAIK we do not guarantee the correctness of the replacements. everything else looks good on our side, i just want to confirm we are communicating the correct information to users

**Comment by gguillotte-grafana** [comment]
@achatterjee-grafana @grafana/observability-logs-and-traces This PR was meant to solve #45770, which specifically raised concerns about managing user expectations for this feature's reliability, and that the goal is only to remove the confusing usage of "experimental", not to document that the feature is reliable.

My understanding is that we won't guarantee that this feature will correctly fix all escaping issues, and I'm concerned that the suggested changes won't communicate this.

Emphasis mine:

> Of course, it might always produce incorrect results, as we don't know which characters are actual newlines and which have just the \n pattern, but I think that *if we communicate it clearly, users will understand.*

If we don't want to communicate this, perhaps we should close this, discuss in #45770 what it is that we want here instead, and I can rewrite and open a new PR.

**Comment by achatterjee-grafana** [comment]
It is tricky documenting something that may or may not work - I agree with @gguillotte-grafana, we should revisit how we mention this in our docs.

Also, ping @GrafanaWriter, for your opinion.

File: docs/sources/explore/logs-integration.md (hunk 6 above)
Comment (gguillotte-grafana) [reply docs/sources/explore/logs-integration.md:109]: Because this involves a UI element changing, and not two separate UI elements, the "Remove escaping" option won't always be visible. This suggestion would mean the conditions for that UI element's presence won't be documented. Is this intended?

Comment (GrafanaWriter) [inline docs/sources/explore/logs-integration.md:109]:
```suggestion
 Explore replaces these sequences. When it does so, the option will change from "Escape newlines" to "Remove escaping". Evaluate the changes as the parsing may not be accurate based on the input received. You can revert the replacements by clicking "Remove escaping".
```

File: public/app/features/explore/LogsMetaRow.tsx (hunk 1 above)
Comment (GrafanaWriter) [reply public/app/features/explore/LogsMetaRow.tsx:74]: I like @achatterjee-grafana's edit here.

File: docs/sources/explore/logs-integration.md (hunk 6 above)
Comment (GrafanaWriter) [reply docs/sources/explore/logs-integration.md:109]: I've added an edit to see if we can make that more clear.

**Review by GrafanaWriter — APPROVED** [review]
Thank you.

File: docs/sources/explore/logs-integration.md (hunk 6 above)
Comment (gguillotte-grafana) [reply docs/sources/explore/logs-integration.md:109]: Removed an extraneous leading space before committing. Thank you!

**Comment by gguillotte-grafana** [comment]
Thanks @achatterjee-grafana and @grafanawriter! I've committed the changes.

**Review by achatterjee-grafana — APPROVED** [review]

**Comment by gguillotte-grafana** [comment]
Anything else I need to do to move this forward?

**Comment by gguillotte-grafana** [comment]
I don't have merge permissions so I do still need someone to merge this PR.

**Comment by ivanahuckova** [comment]
merged 🙂
