### PR TITLE
Scenes/Dashboard: Fix issue where changes to panel in row weren't detected in panel edit

### LINKED ISSUE #87171: Dashboard Scene: Panel inside a row is not detecting changes in Panel Edit mode
When a panel is inside a row, if changes are made, the detecting changes mechanism does not work. ([dashboard ops](https://ops.grafana-ops.net/d/adke5jppntclca/transformation-changes-are-not-detected?folderUid=eb7c879e-3c2c-412d-8a4d-c81cdfb2fe49))

https://github.com/grafana/grafana/assets/239999/54a7158b-c309-4294-a155-05c269514731

### PR DESCRIPTION
**Pull request by kaydelaney**
Closes #87171

### CODE REVIEW

File: public/app/features/dashboard-scene/serialization/transformSceneToSaveModel.ts [hunk 1]
```diff
@@ -186,21 +176,36 @@ export function gridItemToPanel(gridItem: DashboardGridItem, isSnapshot = false)
     return libraryVizPanelToPanel(gridItem.state.body, { x, y, w, h });
   }
 
-  if (!(gridItem.state.body instanceof VizPanel)) {
+  let gridItem_ = gridItem;
+
+  // If we're saving while the panel editor is open, we need to persist those changes in the panel model
+  if (
+    sceneState &&
```
Comment (ivanortegaalba) [inline public/app/features/dashboard-scene/serialization/transformSceneToSaveModel.ts:183]: Can't we get this state from the gridItem using `getDashboardSceneFor`? With that, we would avoid to pass down the dashboard scene state. WDYT?

**Review by ivanortegaalba — APPROVED** [review]
The fix solves the issue, and I think the approach is correct! 💯  

However, I'd like to avoid passing down the state as a parameter, if we can get it through the util function to get the root.

**Review by axelavargas — APPROVED** [review]
Hey @kaydelaney , great job with figuring out this one 🙌🏾. I gave it a test and it works as expected.

File: public/app/features/dashboard-scene/serialization/transformSceneToSaveModel.ts (hunk 1 above)
Comment (kaydelaney) [reply public/app/features/dashboard-scene/serialization/transformSceneToSaveModel.ts:183]: Yeah, I agree that it's ugly passing the state down through the functions, but I wanted to avoid calling `getDashboardSceneFor` multiple times

Comment (ivanortegaalba) [reply public/app/features/dashboard-scene/serialization/transformSceneToSaveModel.ts:183]: Looking at the function 
https://github.com/grafana/grafana/blob/7d84ae04aac74d77aef0f05d5036c5f1884dec82/public/app/features/dashboard-scene/utils/utils.ts#L185

I don't see any issue with calling it multiple times, it is just getting the root. Am I missing something here?

FYI, we're discussing it with the team, and @Sergej-Vlasov is trying to refactor it to use `getDashboardSceneFor `. We can always move it back to this approach if there is something we're missing.
