### PR TITLE
Azure Monitor: Add current value to editor options

### LINKED ISSUE #53159: Azure Monitor: Editor with empty values when it cannot be resolved
**What happened**:

When a query is based on template variables, if solving those variables fail (or are pointing to the wrong thing), the query editor may not be able to obtain the different fields (like metric names) but even in that scenario, we should render the saved options. For example, this JSON:

Screenshot from 2022-08-02 17-08-07

Is not rendering the different fields:

Screenshot from 2022-08-02 17-17-01

**What you expected to happen**:

All the fields to be pre-filled, even if they cannot be auto-resolved.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by andresmgot**
**What is this feature?**

If the query value is not a part of the options, render it anyway. This behavior was already present for the "Metric Namespace" input so I applied the same behavior to the rest of fields:

Screenshot from 2022-12-23 13-42-42

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/53159

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/utils/common.ts [hunk 1]
```diff
@@ -22,6 +22,21 @@ export const findOptions = (options: AzureMonitorOption[], values: string[] = []
...
 export const toOption = (v: { text: string; value: string }) => ({ value: v.value, label: v.text });
 
+export const addValueToOptions = (
+  values: AzureMonitorOption[],
+  variableOptionGroup: VariableOptionGroup,
+  value?: string
+) => {
+  const options = [...values, variableOptionGroup];
+
+  const optionValues = values.map((m) => m.value.toLowerCase()).concat(variableOptionGroup.options.map((p) => p.value));
```
Comment (aangelisc) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/utils/common.ts:32]: I would do this in one step as:

```
if([...values, variableOptionGroup.options].every((v) => v.value.toLowerCase() !== value.toLowerCase())) {
    options.push({ label: value, value});
}
```

To save on the extra loop the `includes` will add.

**Review by aangelisc — APPROVED** [review]
Great simplifications here, just one suggestion 😊

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/utils/common.ts (hunk 1 above)
Comment (andresmgot) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/utils/common.ts:32]: that doesn't work exactly because options is a because the syntax is not valid:

Screenshot 2022-12-23 at 18 17 54

making that work (e.g. forcing to read `value` and ensuring it's not `undefined` would make the method less readable. Since these are short arrays, you don't win that much avoiding the extra loop.
