### PR TITLE
AzureMonitor: Fix auto-selection of time-grain for metrics.

### LINKED ISSUE #47979: AzureMonitor: Automatic time grain selection is not correctly set in backend
**What happened**:

When selecting a metric using the Azure Monitor datasource, the automatic time grain is correctly inferred on the frontend. However, selecting auto as the time grain causes an API error as the backend does not make use of the defined metrics defined time grains and instead uses hardcoded defaults. This causes the wrong time grain to be selected when the query is executed.

Screen Recording 2022-04-20 at 15 32 24

**What you expected to happen**:

The automatic time grain inferred in the frontend should be used in the backend request.

**How to reproduce it (as minimally and precisely as possible)**:

See screenshot.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by aangelisc**
**What this PR does / why we need it**:

This fixes an issue where the allowed time grains for a metric are not correctly passed to the backend leading to the interval being set to an invalid value.

**Which issue(s) this PR fixes**:

Fixes #47979

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource.go [hunk 1]
```diff
@@ -106,6 +106,7 @@ func (e *AzureMonitorDatasource) buildQueries(queries []backend.DataQuery, dsInf
 
 		timeGrain := azJSONModel.TimeGrain
 		timeGrains := azJSONModel.AllowedTimeGrainsMs
+		fmt.Println("TIME GRAINS ", timeGrains)
```
Comment (kevinwcyu) [inline pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource.go:109]: this can be removed.

**Review by kevinwcyu — APPROVED** [review]
👍 can we add a test for this?

File: pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource.go (hunk 1 above)
Comment (aangelisc) [reply pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource.go]: missed that, will remove this and get a test in 😊
