### PR TITLE
Prometheus: Restore FromAlert header

### LINKED ISSUE #54403: Missing Fromalert and X-Cache-Skip HTTP headers since v9.1.0
**What happened**:

After upgrading to v9.1.1 we noticed that the `Fromalert` header we use to route Prometheus alerting queries was not added to the requests anymore.

Grafana 9.0.7 :
```
POST /prometheus/api/v1/query_range HTTP/1.1
Host: 127.0.0.1:8427
Accept-Encoding: gzip
Content-Length: 62
Content-Type: application/x-www-form-urlencoded
Fromalert: true
User-Agent: Grafana/9.0.7
X-Cache-Skip: true
```

Grafana 9.1.0
```
POST /prometheus/api/v1/query_range HTTP/1.1
Host: 127.0.0.1:8427
Accept-Encoding: gzip
Content-Length: 62
Content-Type: application/x-www-form-urlencoded
User-Agent: Grafana/9.1.0
```

**What you expected to happen**:

Fromalert and X-Cache-Skip Headers are added to alerting queries requests

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade from Grafana 9.0.x to Grafana 9.1.x

**Anything else we need to know?**:

Might be related to this commit : https://github.com/grafana/grafana/commit/3df34fe06452d7a5c5369b27d81514497a57485b

### PR DESCRIPTION
**Pull request by kylebrandt**
**What this PR does / why we need it**:
Restores the FromAlert header to prometheus that comes for Grafana Managed Alert queries.

**Which issue(s) this PR fixes**:

Fixes #54403

**Special notes for your reviewer**:
I think was made a feature by accident, but people are using Load balance / route queries to different higher SLA servers for alerting.

So this doesn't fix that it isn't thought out as feature (e.g. document, support across datasource, less fragile internal code then a header). But it does provide a fix of restoring the header.

This reverts https://github.com/grafana/grafana/pull/51518 , but with the change to only pass through the FromAlert header.

### CODE REVIEW

**Comment by kylebrandt** [comment]
@aocenas Are you able to check this out since it reverts a PR of yours?

File: pkg/tsdb/prometheus/buffered/time_series_query.go [hunk 1]
```diff
@@ -92,6 +94,17 @@ func New(roundTripper http.RoundTripper, tracer tracing.Tracer, settings backend
 }
 
 func (b *Buffered) ExecuteTimeSeriesQuery(ctx context.Context, req *backend.QueryDataRequest) (*backend.QueryDataResponse, error) {
+	// Add headers from the request to context so they are added later on by a context middleware. This is because
+	// prom client does not allow us to do this directly.
+
+	addHeaders := make(map[string]string)
+
+	if req.Headers["FromAlert"] == "true" {
+		addHeaders["FromAlert"] = "true"
```
Comment (aocenas) [inline pkg/tsdb/prometheus/buffered/time_series_query.go:103]: Is this only for the `FromAlert` info? Out of curiosity why is it needed to send to prometheus? Could it be moved to infra code so that it is always sent downstream?

Comment (kylebrandt) [reply pkg/tsdb/prometheus/buffered/time_series_query.go:103]: Only for the header. Since it was being sent, people have used it to load balance on. So they point their datasource at their LB and use the header to route differently.

Not sure I follow with moving to the infra code? This doesn't seem like the right way to fix it to me, but trying to undo the experienced regression for the user.

Comment (aocenas) [reply pkg/tsdb/prometheus/buffered/time_series_query.go:103]: Yep got it, this works so no issue in merging.

> Not sure I follow with moving to the infra code?

We are already handling headers in grafana backend in general by providing a HTTP client to datasource, so it does not have to be handled custom, which is why this code was removed. We may somehow move this to the HTTP client that is provided so that `FromAlert` header would be passed upstream for all datasources automatically if it is valuable in general.

**Review by aocenas — APPROVED** [review]
