### PR TITLE
QueryEditor: Fix focused states

### LINKED ISSUE #122369: Query stack header has extra focusable elements
In the query stack, there are elements that shouldn't have focus but do. Let's fix that, while taking care to preserve keyboard navigation a11y.

## Expandable section container

Image

When this element has focus, we can expand/compact the section with the **Enter** button. We want to preserve this keyboard functionality, but let's have focus on the button (carat) instead.

## Query stack wrapper

There isn't an action associated with this element – I can't think of a good reason why it should have focus.

Image

## Add button container

The add button (`+`) has a container that doesn't need focus.

Image

Let's get rid of that...the button itself is what should have focus for the "add item" interaction:

Image

### PR DESCRIPTION
**Pull request by alexjonspencer1**
## Description

Resolves https://github.com/grafana/grafana/issues/122369

The focused states were not polished with the collapsible section and query cards themselves. 

> [!NOTE]
> The issue mentions focus on the sidebar container itself not being needed. I think it _is needed_, it's the "scrollable" section and is a part of our "ScrollContainer" Grafana element.
> image

## Changes

1. We're asking too much of `CollapsibleSection` from the Grafana design system, it's not meant to handle additional elements alongside it (e.g., an add button like we have). We're just trying to shoe horn it in. Made our own new custom `CollasableSection` component that handles this better for our needs. 
2. Explicitly set `tabIndex={-1}` on our `DraggableList` cards. We still get the DnD package's keyboard navigation, don't worry! (space to select, arrows to move, space to accept) 

#### New collapsable section focused state
image

#### 🎥 

https://github.com/user-attachments/assets/a8e6a6c9-1045-4602-b1aa-880087857e68

## Testing Instructions

* Pull down, test out.

## Reviewer Checklist

- [ ] Tests are added where applicable
- [x] Issue is linked to PR
- [x] Code pulled and tested
- [ ] Code is meaningfully improved if applicable

### CODE REVIEW

**Review by NWRichmond — APPROVED** [review]
It's working beautifully! Nicely done 🙌🏼

File: public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/Sidebar/DraggableList/DraggableList.tsx [hunk 1]
```diff
@@ -63,6 +63,7 @@ export function DraggableList<T>({
                       ref={dragProvided.innerRef}
                       {...dragProvided.draggableProps}
                       {...dragProvided.dragHandleProps}
+                      tabIndex={-1}
```
Comment (Develer) [inline public/app/features/dashboard-scene/panel-edit/PanelEditNext/QueryEditor/Sidebar/DraggableList/DraggableList.tsx:66]: Nice work! I was worried it would affect dnd behaviour, but it works great! 🎉

**Review by Develer — APPROVED** [review]
LGTM 🚀🚀🚀
