### PR TITLE
Teams: Support paginating and filtering more then 1000 teams

### LINKED ISSUE #58736: Only possible to list 1000 teams
**What happened**:

When there are more than 1000 teams in Grafana, on the teams page only first 1000 are visible and there is no pagination is available. It is also not possible to get teams beyond first 1000 via the API.

**What you expected to happen**:
Having more than 1000 teams is not unusual, especially for big companies. We should support pagination in the UI and in the API, so that users will be able to manage their teams fully.

**How to reproduce it (as minimally and precisely as possible)**:
- Create >1000 teams
- Navigate to `/org/teams` page
- You can see only 1000 teams

**Anything else we need to know?**:
This seem to be the case from the very beginning of Grafana.

### PR DESCRIPTION
**Pull request by kalleep**
**What is this feature?**
The team list page always fetch the first 1000 teams and do all pagination and filtering in front-end, making it impossible to view a team that that is not part of that first 1000 in the list.

The API already has support for paginating and filtering (by query) so I just had to update the front-end code to support back-end pagination and filtering.

**Why do we need this feature?**
To be able to view more teams than the first 1000.

**Which issue(s) does this PR fix?**:
Fixes #58736

**Special notes for your reviewer**:
* Extract the code for team row as its own component
* Rework TeamList to be a functional component

### CODE REVIEW

File: public/app/features/teams/TeamList.tsx [hunk 1]
```diff
@@ -35,199 +34,131 @@ export interface State {
...
+}
 
-    return (
-      <Page navId="teams">
-        <Page.Contents isLoading={!hasFetched}>{this.renderList()}</Page.Contents>
-      </Page>
-    );
-  }
+function shouldDisaplyRolePicker(): boolean {
+  return false;
```
Comment (mgyongyosi) [inline public/app/features/teams/TeamList.tsx:146]: I guess you forgot to remove this. ;)

Comment (kalleep) [reply public/app/features/teams/TeamList.tsx:146]: Yeah, will fix that

**Review by mgyongyosi — APPROVED** [review]
