### PR TITLE
Dashboard save: Persist details message when navigating through dashboard save drawer's tabs.

### LINKED ISSUE #53946: Saving dashboards: Details get deleted when I review changes
**What happened**:
I noted my changes when saving my dashboard. When I went to review changes and then back, my comment was gone.

**What you expected to happen**:

For my comment to be left as-is.

**How to reproduce it (as minimally and precisely as possible)**:

Launch vanilla Grafana, create a dashboard, save it. Add a blank panel (optional), save it again, type in a comment, review changes, click back to see the comment. It's not there.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.0
- OS Grafana is installed on: macOS, Ubuntu
- User OS & Browser: macOS, Chrome
- Grafana plugins: none

**Demo**:

grafana_detail_faster

### PR DESCRIPTION
**Pull request by vbeskrovnov**
**What this PR does / why we need it**:
Fix `changes note` textarea to save draft when going to other tabs

https://user-images.githubusercontent.com/9114994/186127851-6c63ae01-ae46-4037-ab88-d61a08241b6e.mov

**Which issue(s) this PR fixes**:

Fixes #53946

### CODE REVIEW

**Review by dprokop — CHANGES_REQUESTED** [review]
Thanks for your contribution @vbeskrovnov.

Instead of extending props interfaces of multiple form components, I suggest using the `options` object to store the transient message. Its interface already contains `message` property, so it's gonna be the least impactful change to the current implementation.

File: public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx [hunk 1]
```diff
@@ -85,7 +89,15 @@ export const SaveDashboardForm = ({
             />
           )}
 
-          <TextArea {...register('message')} placeholder="Add a note to describe your changes." autoFocus rows={5} />
+          <TextArea
+            {...register('message')}
+            aria-label="message"
+            value={message}
+            onChange={onUpdateMessage}
```
Comment (dprokop) [inline public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx:96]: This will override `onChange` handler provided by the `register` function. What you need to do instead is:

```ts
const messageProps = register('message');
...

onChange={(e) => {
  // your update here 
  ...
  // original callback call
  messageProps.onChange(e);
}}
```

Comment (vbeskrovnov) [reply public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx]: I tried to fix it, but it would be much better to update `react-hook-form`(https://github.com/react-hook-form/react-hook-form/releases/tag/v7.16.0) to be able to handle such cases

File: public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx [hunk 2]
```diff
@@ -84,8 +84,21 @@ export const SaveDashboardForm = ({
...
+          <TextArea
+            {...register('message')}
+            aria-label="message"
+            value={options.message}
+            onChange={(e) => {
+              onOptionsChange({
+                ...options,
+                message: e.currentTarget.value,
+              });
+              register('message').onChange(e);
```
Comment (dprokop) [inline public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx:96]: Instead of calling `register` twice, please define it as const within the render prop closure, L60.

**Review by dprokop — CHANGES_REQUESTED** [review]
Looks good, requested one change to make- when it's done we should be good to merge.

Also - I've pushed a minor change that hides the changes tab when there are no edits in the dashboard.

File: public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx (hunk 2 above)
Comment (vbeskrovnov) [reply public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx]: > Instead of calling `register` twice, please define it as const within the render prop closure, L60.

Thank you for your help!
hope I understand you in the right way :)

Comment (dprokop) [reply public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx]: What you did is exactly what I had in mind. Thank you!

**Review by dprokop — APPROVED** [review]
👏

File: public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx (hunk 2 above)
Comment (vbeskrovnov) [reply public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx]: Thank you! Should I do something to merge it?
