### PR TITLE
Fix graph render blocked by annotations issue

### LINKED ISSUE #11806: Loading large number of Graph panels waits for all to load
When loading a dashboard with large number of panels, the dashboard waits for all them to load and just after they all are loaded, they are shown. The data are already in memory so it would be better that loaded panels are displayed just as soon as they receive the data.

I have tried to record the situation http://g.recordit.co/KG5uHKTNOC.gif You can see the loader disappear for panels that are loaded but they show no data yet.

### PR DESCRIPTION
**Pull request by jsferrei**
graphs finish querying

Fixes https://github.com/grafana/grafana/issues/11806

Open to suggestions for a better way to accomplish this.

### CODE REVIEW

**Review by torkelo — CHANGES_REQUESTED** [review]
Not fond of this solution, the caching in annotationSrv is duplicated as it's done in datasourceSrv as well. We will need a different solution I think, not sure what would be the easiest alternative though. One way would be to do annotation queries async and let them complete whenever, if after the metric queries it will trigger another render, if before it will be added to render data.

**Comment by jsferrei** [comment]
@torkelo thank you for the suggestion. This seems to do what I want. Updated.

File: public/app/plugins/panel/graph/module.ts [hunk 1]
```diff
@@ -207,16 +207,19 @@ class GraphCtrl extends MetricsPanelCtrl {
       }
     }
 
+    this.render(this.seriesList);
+    this.loading = true;
```
Comment (jsferrei) [inline public/app/plugins/panel/graph/module.ts]: Not sure about this. On the one hand it can be confusing to see graph data with a loading indicator still, on the other, folks may wonder where their annotations are if there's no indicator the query is still running. @torkelo thoughts?

**Comment by jsferrei** [comment]
@torkelo any more thoughts on this given the changes made?

**Comment by jsferrei** [comment]
Hey @torkelo would love a second round of feedback on this when you get a chance

**Comment by torkelo** [comment]
this results in too many duplicated renders, and also might cause issues with snapshots. Tricky, not sure what the best solution is here.

**Comment by jsferrei** [comment]
Hm not sure what to do then. 

We really need a fix for this issue as our users have been complaining about it. Perhaps some version of the original approach is required then?

**Comment by torkelo** [comment]
I think we need some way reserve 1 request for annotation srv and one for Grafana api. So that metrics requests only use 4 concurrent requests. Most browser have a limit of 6.

Not exactly sure how to accomplish this in backendSrv and what other negative effects that might have.

**Comment by torkelo** [comment]
Worth a try , but reserving a connection for grafana api / annotation arc could be a really great thing as slow queries can today make grafana unresponsive as api requests have to wait for queries to complete

**Comment by jsferrei** [comment]
I pushed new changes that implement the solution I described in my previous comment, which seems to solve this issue.

Reserving a connection for the API and annotations might work, but that connection would need to be accessible by the datasource, so that it can queue its annotation query up front. But then you run into the issue of potentially bad annotation queries blocking other Grafana API requests that need that reserved connection, no?

File: public/app/plugins/panel/graph/module.ts [hunk 2]
```diff
@@ -156,7 +156,10 @@ class GraphCtrl extends MetricsPanelCtrl {
       panel: this.panel,
       range: this.range,
     });
-    return super.issueQueries(datasource);
+
+    return this.annotationsSrv.datasourcePromises.then(r => {
```
Comment (torkelo) [inline public/app/plugins/panel/graph/module.ts]: maybe add a comment here that this allows annotations service a change to fire annotations queries before graph queries (fire not wait for completion).

Comment (jsferrei) [reply public/app/plugins/panel/graph/module.ts]: Commented and added a note about the original issue it fixes.

**Comment by jsferrei** [comment]
Thank you for the input on this
