### PR TITLE
Cloudwatch: Unwrap errors - throw error from upstream

### LINKED ISSUE #32461: Grafana 5xx response should be 4xx
When querying datasources Grafana frequently returns 5xx responses when customer input is invalid. For example, when querying a database that does not exist, or when a CloudWatch logs query is incorrect, CW returns errors such as `mismatched input '<EOF>' expected K_STATS Service:AWSLogs, Status Code: 400` which Grafana than translates as 5xx. 

5xx suggests this is a server side error, that can be retried successfully by the client. 

**What you expected to happen**:
Grafana datasource 4xx responses should not be translated as 5xx. Error messages shown in the Grafana workspace should show the datasource errors, instead of generic Grafana `5xx Server Error`

**Environment**:
- Grafana version: 7.4.5
- Data source type & version: CloudWatch, DataDog, etc.
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

Improve error handling for datasources. To date, Grafana returns `5xx` errors, here:

https://github.com/grafana/grafana/blob/1caaa784d9436776847d4844e4666f9fba12bb7a/pkg/api/metrics.go#L77-L80

Errors need to be unwrapped and checked before a default `500` error is returned.

**Which issue(s) this PR fixes**:

Fixes #32461

**Special notes for your reviewer**:

First commit is only about AWS Cloudwatch. The way I image it is to have a dedicated error struct that can be applied to all datasources across our packages, and fill the struct with the appropriate messages each time (that is, upstream errors, upstream error messages etc.)

### CODE REVIEW

File: pkg/tsdb/cloudwatch/time_series_query.go [hunk 1]
```diff
@@ -98,6 +100,13 @@ func (e *cloudWatchExecutor) executeTimeSeriesQuery(ctx context.Context, req *ba
 	}
 
 	if err := eg.Wait(); err != nil {
+		var awsErr awserr.RequestFailure
```
Comment (marefr) [inline pkg/tsdb/cloudwatch/time_series_query.go:103]: This error is coming from an error happening inside single query goroutine. To me the errors happening inside query goroutine should be put into dataframe, like we do it for sql data sources as an example https://github.com/grafana/grafana/blob/738a3a2d89bfc8474cf941a34d8da409b15a85aa/pkg/tsdb/sqleng/sql_engine.go#L209. This will allow data to be rendered if all queries except one fails and a 400 status will be returned. 

Probably need to check with @grafana/cloud-datasources if my suggestion doesn't work for some reason.

File: pkg/api/metrics.go [hunk 2]
```diff
@@ -76,6 +77,10 @@ func (hs *HTTPServer) QueryMetricsV2(c *models.ReqContext, reqDTO dtos.MetricReq
 
 	resp, err := hs.DataService.HandleRequest(c.Req.Context(), ds, request)
 	if err != nil {
+		var requestError *cloudwatch.RequestError
```
Comment (marefr) [inline pkg/api/metrics.go:80]: This will never work for external backend plugins

**Review by marefr — COMMENTED** [review]
Left some comments

File: pkg/api/metrics.go (hunk 2 above)
Comment (dsotirakis) [reply pkg/api/metrics.go:80]: Yes, as I wrote into the description, it won't be like this, I imagine an errorWrapper that's going to be global and external plugins should wrap their errors in it. Otherwise, it's still going to return `5xx` errors I guess.

File: pkg/tsdb/cloudwatch/time_series_query.go (hunk 1 above)
Comment (andresmgot) [reply pkg/tsdb/cloudwatch/time_series_query.go:103]: +1 to encode the error within a frame if that's the case.

File: pkg/api/metrics.go (hunk 2 above)
Comment (marefr) [reply pkg/api/metrics.go:80]: Regarding my other comment. The idea has always been that an error returned from querying a data source means that it couldn't handle the query data request at all, hence unable to return any data and why we use a 500. If the error is happening for a certain query we can return the error in dataframe for certain refID and it will result in a 400

Comment (andresmgot) [reply pkg/api/metrics.go:80]: I don't think we should forward the status code that the Cloud returns. Imagine that AWS is down (yeah) and it's returning a 500. If we simply return that, it would be interpreted as _our_ internal error (hurting our SLO for example). I think that a neater solution would be to return a 200 if we were able to send and receive a request and encode the result in the body like a JSON:

```
  Status: 200
  Message: {"statusCode": 401, "result": "the user foo doesn't have permissions for bar"}
```

Would we be able to do something like that?

**Review by andresmgot — COMMENTED** [review]
Thanks @dsotirakis! Let me know what you think.

File: pkg/tsdb/cloudwatch/cloudwatch.go [hunk 3]
```diff
@@ -46,6 +46,19 @@ type datasourceInfo struct {
...
+}
+
+func (rE *RequestError) Error() string {
+	return rE.requestError.Error()
+}
+
+func (rE *RequestError) StatusCode() int {
+	return rE.statusCode
+}
+
```
Comment (andresmgot) [inline pkg/tsdb/cloudwatch/cloudwatch.go:61]: this code is no longer used

File: pkg/tsdb/cloudwatch/time_series_query.go [hunk 4]
```diff
@@ -98,6 +100,15 @@ func (e *cloudWatchExecutor) executeTimeSeriesQuery(ctx context.Context, req *ba
...
+		if ok := errors.As(err, &awsErr); ok {
```
Comment (andresmgot) [inline pkg/tsdb/cloudwatch/time_series_query.go:104]: It seems to me that we want to add the error to the dataframe in any case (e.g. a connection error), not only when the request fail. Are you thinking on some case in which we don't want to do that?

**Review by andresmgot — COMMENTED** [review]
Thanks @dsotirakis for getting back to this! I have a question.

File: pkg/tsdb/cloudwatch/time_series_query.go (hunk 4 above)
Comment (dsotirakis) [reply pkg/tsdb/cloudwatch/time_series_query.go]: Nah, I just wanted to unwrap them and I had something else on my mind before (it's been a while), I guess you're right.

**Review by andresmgot — APPROVED** [review]
LGTM!
