### PR TITLE
Provisioning: Fix bug when provision app plugins using Enterprise edition

### LINKED ISSUE #26336: Provisoning plugin enablement/disablement fails with server halting
**What happened**:
When using a provisioning file located in the `provisioning/plugins` directory, Grafana attempts to enable/disable the plugin before the plugins have actually been registered. This causes the Grafana server to halt as the referenced plugin can't be found.

**What you expected to happen**:
The relevant plugin to be enabled/disabled on Grafana startup.

**How to reproduce it (as minimally and precisely as possible)**:
Enable debug output in Grafana via the envvar or config file.

1. Install the relevant plugin into Grafana with `grafana-cli plugins install raintank-worldping-app` or via an environment variable to Grafana
2. Create a new plugin provisioning file, such as the following:
```
apiVersion: 1
apps:
- type: raintank-worldping-app
  org_id: 1
  jsonData:
    apiKey: myKey
```
and save to the `provisioning/plugins` directory (eg. `/etc/grafana/provisioning/plugins/myapp.yaml`)
3. Start up Grafana
4. Grafana will attempt to configure the plugins before the plugins have been registered:
```
t=2020-07-14T19:15:43+0000 lvl=info msg="inserting datasource from configuration " logger=provisioning.datasources name="TestData DB" uid=
t=2020-07-14T19:15:43+0000 lvl=dbug msg="Looking for plugin provisioning files" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins
t=2020-07-14T19:15:43+0000 lvl=dbug msg="Parsing plugin provisioning file" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins file.Name=myapp.yaml
t=2020-07-14T19:15:43+0000 lvl=dbug msg="Validating plugins" logger=provisioning.plugins
t=2020-07-14T19:15:43+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: app provisioning error: app plugin not installed: raintank-worldping-app"
```

That this is out of order with when plugins are registered can be verified by removing the `myapp.yaml` provisioning file from `provisioning/plugins` and restarting Grafana:
```
t=2020-07-14T19:19:22+0000 lvl=info msg="inserting datasource from configuration " logger=provisioning.datasources name="TestData DB" uid=
t=2020-07-14T19:19:22+0000 lvl=dbug msg="Looking for plugin provisioning files" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins
t=2020-07-14T19:19:22+0000 lvl=dbug msg="Parsing plugin provisioning file" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins file.Name=synthetic-monitoring.yaml
t=2020-07-14T19:19:22+0000 lvl=dbug msg="Validating plugins" logger=provisioning.plugins
t=2020-07-14T19:19:22+0000 lvl=dbug msg="Looking for alert notification provisioning files" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers
t=2020-07-14T19:19:22+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: no such file or directory"
t=2020-07-14T19:19:22+0000 lvl=dbug msg="Initializing RemoteCache" logger=server
t=2020-07-14T19:19:22+0000 lvl=dbug msg="Initializing PluginManager" logger=server
t=2020-07-14T19:19:22+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2020-07-14T19:19:22+0000 lvl=dbug msg="Scanning core plugin directory" logger=plugins dir=/usr/share/grafana/public/app/plugins
t=2020-07-14T19:19:22+0000 lvl=dbug msg="Scanning bundled plugins directory" logger=plugins dir=/usr/share/grafana/plugins-bundled
t=2020-07-14T19:19:22+0000 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
t=2020-07-14T19:19:22+0000 lvl=dbug msg="Scanning external plugins directory" logger=plugins dir=/var/lib/grafana/plugins
t=2020-07-14T19:19:22+0000 lvl=info msg="Registering plugin" logger=plugins name=WorldPing
```
Copying the `myapp.yaml` plugin provisioning file back into the `provisioning/plugins` directory and then forcing an update using the plugins provisioning endpoint:
```
curl -u 'admin:admin' -XPOST http://1.2.3.4:3000/api/admin/provisioning/plugins/reload
```
Yields:
```t=2020-07-14T19:23:15+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/admin/provisioning/plugins/reload status=401 remote_addr=172.17.0.1 time_ms=0 size=26 referer=
t=2020-07-14T19:23:22+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2020-07-14T19:23:25+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=1 orgId=1 uname=admin user_id=1
t=2020-07-14T19:23:25+0000 lvl=dbug msg="Looking for plugin provisioning files" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins
t=2020-07-14T19:23:25+0000 lvl=dbug msg="Parsing plugin provisioning file" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins file.Name=myapp.yaml
t=2020-07-14T19:23:25+0000 lvl=dbug msg="Validating plugins" logger=provisioning.plugins
t=2020-07-14T19:23:25+0000 lvl=info msg="Updating app from configuration " logger=provisioning.plugins type=raintank-worldping-app enabled=true
t=2020-07-14T19:23:25+0000 lvl=info msg="Plugin state changed" logger=plugins pluginId=raintank-worldping-app enabled=true
t=2020-07-14T19:23:25+0000 lvl=info msg="Syncing plugin dashboards to DB" logger=plugins pluginId=raintank-worldping-app
t=2020-07-14T19:23:25+0000 lvl=dbug msg="cleaning up directory" logger=metaanalytics.storage dir=/var/lib/grafana/events lifetime=24h0m0s
t=2020-07-14T19:23:32+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
```
Where the plugin is now verified and configured appropriately and enabled in the Dashboard, thus proving the server startup order issue.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.0-beta3
- OS Grafana is installed on: kubernetes cluster
- User OS & Browser: https://www.whatsmybrowser.org/b/N7RZS (macOS 10.15/Firefox)
- Grafana plugins: raintank-worldping-app/1.2.7

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
In OSS provisioning service init after plugin registration, but in
Enterprise it's the opposite order and installed app plugin check
fails. This adjusts service registry init priority to make sure plugins 
are registered before provisioning inits.

**Which issue(s) this PR fixes**:
Fixes #26336 

**Special notes for your reviewer**:
Adjusting the service init priority is very sensitive. I tried to just change using high and low, but couldn't get it to work why I introduced the medium priority and made that the default, instead of low. I also noticed some places used a numeric priority instead of high and low so adjusted those to comply with new default.

Have done quite a lot of testing myself and at first had a lot of weird problem, but finally found and [fixed this bug](https://github.com/grafana/grafana-enterprise/pull/676). Seems to work as expected. Have tested reporting, licensing, rendering (plugin), provisioning of apps (worldping app), loading of backend plugins. But would really need some additional help testing  using both OSS and Enterprise to make sure I haven't introduced any new bugs.

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]

File: pkg/services/search/service.go [hunk 1]
```diff
@@ -11,11 +11,7 @@ import (
 )
 
 func init() {
-	registry.Register(&registry.Descriptor{
-		Name:         "SearchService",
-		Instance:     &SearchService{},
-		InitPriority: 20,
-	})
+	registry.RegisterService(&SearchService{})
```
Comment (marefr) [inline pkg/services/search/service.go:14]: This had priority 20 before and default prio was low so think that using medium should be fine. Found another service having search.SearchService as dependency and that service was registered with priority low.

**Review by aknuds1 — APPROVED** [review]
Probably good, difficult for me to tell.

**Review by papagian — APPROVED** [review]
AFAICT LGTM

I have tested in OSS and Enterprise with the scenario described in the issue and I no more see the error I used to get.

**Review by sakjur — APPROVED** [review]
:+1: LGTM

Started Grafana Enterprise a bunch of times with the steps to reproduce in the bug.

**Review by xlson — APPROVED** [review]
LGTM!
