### PR TITLE
Explore/Loki: Remove regex parsing errors for huge logs

### LINKED ISSUE #19869: Explore: Long log line triggers an error when scrolling down.
**What happened**:
If Loki contains a huge log line, when scrolling down, the whole log panel disappears and shows a red error as below:

image

The message at the end read:`RegExp too big`

**What you expected to happen**:
I should still be able to cro

**How to reproduce it (as minimally and precisely as possible)**:

I've shared a link where this happens.

**Anything else we need to know?**:

It seems to be triggered by the scroll event, if I don't move everything looks fine :)

**Environment**:
- Grafana version: Grafana v6.5.0-pre (55d7fbf)

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
This PR removes parsing for highlighting and creating parsed fields in log details view for log lines with 100,000+ characters. I have tested the regex with 100,000 characters and it was still parsing, so the problem is created only with really really  massive log lines (100,000+ characters). I have also added Info message about this.

image

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/19869

**Special notes for your reviewer**:

### CODE REVIEW

File: packages/grafana-ui/src/components/Logs/LogRowMessage.tsx [hunk 1]
```diff
@@ -110,7 +112,7 @@ class UnThemedLogRowMessage extends PureComponent<Props> {
             />
           )}
           <span className={cx(styles.positionRelative, { [styles.rowWithContext]: contextIsOpen })}>
-            {needsHighlighter ? (
+            {needsHighlighter && entry.length < MAX_CHARACTERS ? (
```
Comment (kaydelaney) [inline packages/grafana-ui/src/components/Logs/LogRowMessage.tsx:115]: `entry.length < MAX_CHARACTERS` could probably just be added to the `needsHighlighter` definition
Though that definition itself could use some simplification, so maybe something like
`const needsHighlighter = !!highlights?.[0]?.length && entry.length < MAX_CHARACTERS;`

**Review by kaydelaney — APPROVED** [review]
One small comment but otherwise LGTM

File: packages/grafana-ui/src/components/Logs/LogRowMessage.tsx (hunk 1 above)
Comment (ivanahuckova) [reply packages/grafana-ui/src/components/Logs/LogRowMessage.tsx]: Yeah, great point!
