### PR TITLE
Elasticsearch: Fix index pattern not working with multiple base sections

### LINKED ISSUE #27485: Index with Weekly-Pattern breaks Alerts
Hi, we encountered the following issue in our environement. This may be releated to this [issue](https://github.com/grafana/grafana/issues/12731).

We have an elastic data source with a weekly index pattern. That works fine for creating visualizations. However it does not work with alerts.

Bildschirmfoto 2020-09-09 um 22 19 14

If you click on the "Test Rule" button in an alert section you can see that the index is complete garbage:

Bildschirmfoto 2020-09-09 um 22 19 08

When we change the index pattern to one without a weekly pattern:

Bildschirmfoto 2020-09-09 um 22 26 15

Everything works fine (the "Test Rule" button works and we receive alerts):

Bildschirmfoto 2020-09-09 um 22 27 29

**Environment**:
- Grafana version: Grafana v7.1.0 (8101355285)
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Some Linux?
- User OS & Browser: Mac OS & Firefox
- Grafana plugins: ?

Thank you for developing and supporting this great open source app.

Appologies if this is a duplicate of an already reported issue, I was'nt able to find an existing bug report.

Greetings

Sebastian

### PR DESCRIPTION
**Pull request by tomdaly**
**What this PR does / why we need it**:

The current logic means that an Elasticsearch index pattern can be similar to `[data-]YYYY` or `MM.DD[-data]`, but breaks if there are multiple `[*]` sections (e.g. `YYYY[-data-]MM.DD[-moredata]`). See issue for more details.

**Which issue(s) this PR fixes**:

Fixes #27485 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by tomdaly** [comment]
Hi @aknuds1 thanks for updating the PR, do you have any idea why the 'Backport PR Creator' builds are failing? (or how to disable notifications for it while it fails, I got 62 emails last night from it)

**Comment by aknuds1** [comment]
> Hi @aknuds1 thanks for updating the PR, do you have any idea why the 'Backport PR Creator' builds are failing? (or how to disable notifications for it while it fails, I got 62 emails last night from it)

@torkelo Do you know why the latest error occurs?

**Comment by aknuds1** [comment]
@tomdaly You can ignore the Backport PR Creator failures, it's just a utility automation, with some kinks that need working out.

**Comment by aknuds1** [comment]
@wbrowne You've worked with Elasticsearch lately? Maybe you could have a look at this?

File: pkg/tsdb/elasticsearch/client/index_pattern.go [hunk 1]
```diff
@@ -247,72 +247,101 @@ var datePatternReplacements = map[string]string{
...
-		formatted = strings.ReplaceAll(formatted, "<stdWeekOfYear>", fmt.Sprintf("%02d", isoWeek))
-
-		formatted = strings.ReplaceAll(formatted, "<stdUnix>", fmt.Sprintf("%d", t.Unix()))
-
-		day := t.Weekday()
-		dayOfWeekIso := int(day)
-		if day == time.Sunday {
-			dayOfWeekIso = 7
+	for i, formatted := range formattedDatePatterns {
+		if strings.Contains(formatted, "<std") {
```
Comment (aknuds1) [inline pkg/tsdb/elasticsearch/client/index_pattern.go:288]: Can you invert this if test as follows? It's more idiomatic Go:

```suggestion
		if !strings.Contains(formatted, "<std") {
			continue
		}
```

File: pkg/tsdb/elasticsearch/client/index_pattern.go [hunk 2]
```diff
@@ -247,72 +247,101 @@ var datePatternReplacements = map[string]string{
...
+			isoYear, isoWeek := t.ISOWeek()
+			isoYearShort := fmt.Sprintf("%d", isoYear)[2:4]
```
Comment (aknuds1) [inline pkg/tsdb/elasticsearch/client/index_pattern.go:290]: These can be moved outside of the loop, right? It's much better if everything that's constant wrt. the loop are moved outside of it.

File: pkg/tsdb/elasticsearch/client/index_pattern.go [hunk 3]
```diff
@@ -247,72 +247,101 @@ var datePatternReplacements = map[string]string{
...
+			formatted = strings.ReplaceAll(formatted, "<stdIsoYearShort>", isoYearShort)
+			formatted = strings.ReplaceAll(formatted, "<stdWeekOfYear>", fmt.Sprintf("%02d", isoWeek))
+
+			formatted = strings.ReplaceAll(formatted, "<stdUnix>", fmt.Sprintf("%d", t.Unix()))
+
+			day := t.Weekday()
+			dayOfWeekIso := int(day)
+			if day == time.Sunday {
+				dayOfWeekIso = 7
+			}
```
Comment (aknuds1) [inline pkg/tsdb/elasticsearch/client/index_pattern.go:301]: Can you move this outside of the loop? It helps in making the code readable.

File: pkg/tsdb/elasticsearch/client/index_pattern.go [hunk 4]
```diff
@@ -247,72 +247,101 @@ var datePatternReplacements = map[string]string{
...
+			quarter := 4
+
+			switch t.Month() {
+			case time.January, time.February, time.March:
+				quarter = 1
+			case time.April, time.May, time.June:
+				quarter = 2
+			case time.July, time.August, time.September:
+				quarter = 3
+			}
```
Comment (aknuds1) [inline pkg/tsdb/elasticsearch/client/index_pattern.go:316]: Can you move this outside of the loop? It would help in keeping the code as readable as possible.

Comment (tomdaly) [reply pkg/tsdb/elasticsearch/client/index_pattern.go]: Thanks for the review - refactored all of your suggested changes into 878a1bc

**Review by wbrowne — APPROVED** [review]
LGTM!

**Comment by wbrowne** [comment]
@tomdaly Thanks a lot for the contribution!

**Comment by morsik** [comment]
I've just upgraded from 7.3.7 to 7.4.3 on my CentOS and whole ElasticSearch data source stopped working. Newer version even fails at week assignment.

I have this pattern: `[myapp-]YYYY.WW`
When I pressed "Save & Test" on 7.3.7 it tried: `myapp-2012.09`.
But on 7.4.3 it tried: `myapp-2012.08` which doesn't exists and whole Data Source is broken. No data on dashboards at all.

I downgraded to 7.3.7 and my Data Source and dashboards are working again.

I suspect this change?

**Comment by Elfo404** [comment]
@morsik the issue is actually in the frontend, it was reported earlier today in https://github.com/grafana/grafana/issues/31634
