### PR TITLE
Accessibility: Add lint rule to prevent text anchor usage

### LINKED ISSUE #73396: [Accessibility issue] Some links and text buttons cannot be easily identified for users with color deficiencies.
**Steps to reproduce**:
Go to [play.grafana.org/alerting](https://play.grafana.org/alerting). Simulate a color deficiency using your browser tools (e.g. Firefox accessibility tab > Simulate; Chrome devtools > More tools > Rendering > Emulate vision deficiencies). Notice how difficult it is to discern what is a link.

**Actual Result**:
Links, text buttons and other interactive controls are often difficult to identify for users with vision deficiencies.

**Expected Result**
Interactive controls should be easily recognisable without color and have some sort of designator they are interactive. e.g. links have underlines, a chevron or another common design pattern to discern them.

image

UHG Audit ID: 1.401

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- adds a new lint rule preventing`<a>` tags containing non-empty text strings. 
  - in these cases, developers should use the `TextLink` component from `@grafana/ui`. it provides the correct behaviour and styling.
  - we need to ignore empty text strings as newlines/whitespace in the JSX counts as empty text strings
- fixes the ~50 existing violations to use `TextLink`
- adjusts the existing alert links to use `inline=true` so they correctly show an underline

**Why do we need this feature?**

- more accessible text links 🥳 

**Who is this feature for?**

- everyone

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/73396

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by Develer — APPROVED** [review]

File: public/app/plugins/datasource/tempo/configuration/StreamingSection.tsx [hunk 1]
```diff
@@ -21,22 +19,14 @@ interface StreamingOptions extends DataSourceJsonData {
...
           <div>Enable streaming for different Tempo features.</div>
-          <a
-            href={'https://grafana.com/docs/tempo/latest/traceql/#stream-query-results'}
-            target={'_blank'}
-            rel="noreferrer"
-            className={styles.a}
-          >
-            Learn more
-          </a>
+          <TextLink href={'https://grafana.com/docs/tempo/latest/traceql/#stream-query-results'}>Learn more</TextLink>
```
Comment (ifrost) [inline public/app/plugins/datasource/tempo/configuration/StreamingSection.tsx]: Should this also be `external`? 🤔

Comment (ashharrison90) [reply public/app/plugins/datasource/tempo/configuration/StreamingSection.tsx]: it absolutely should - thanks for the spot! 🙏

**Review by ifrost — APPROVED** [review]

**Review by joshhunt — APPROVED** [review]
