### PR TITLE
sql tsdb: fix value columns conversion to float when using timeseries query

### LINKED ISSUE #11703: [Bug] Unsupported data types for value column using time series query
### What Grafana version are you using? 

latest master

### What datasource are you using? 

mysql

### What did you do?

Created a table

```SQL
CREATE TABLE tickets (
id int(11) NOT NULL AUTO_INCREMENT,
date_created datetime NOT NULL,
PRIMARY KEY (id),
KEY date_created_idx (date_created)
) ENGINE=InnoDB AUTO_INCREMENT=2748 DEFAULT CHARSET=utf8
```

Inserted some data 

```SQL
INSERT INTO `tickets`(`date_created`) VALUES(NOW());
```

Executed a time series query in Grafana

```SQL
SELECT $__time(date_created), id as value, 'Tickets' as metric FROM tickets
```

### What was the expected result?

Be able to plot the data in a graph panel

### What happened instead?

Error message: `Value column must have numeric datatype, column: value type: *int32 value: 0xc4208b23a0`

Seems like pointer values for value column are not handled correctly.

### PR DESCRIPTION
**Pull request by marefr**
Fixes #11703

Started to fix this for MySql, but realized that MSSQL had similar problems so decided to extract a common function for converting value columns that's now used by all three SQL datasources.

### CODE REVIEW

File: pkg/tsdb/sql_engine.go [hunk 1]
```diff
@@ -185,3 +188,109 @@ func ConvertSqlTimeColumnToEpochMs(values RowValues, timeIndex int) {
 		}
 	}
 }
+
+// ConvertSqlValueColumnToFloat converts timeseries value column to float.
+func ConvertSqlValueColumnToFloat(columnName string, columnValue interface{}) (null.Float, error) {
+	var value null.Float
+
+	switch typedValue := columnValue.(type) {
```
Comment (marefr) [inline pkg/tsdb/sql_engine.go]: Would be nice if there were any other way of doing this

**Review by daniellee — APPROVED** [review]
Great work Marcus - the issue was really well written which made this easy to test and the change looks solid.
