### PR TITLE
grafana-cli: update plugins ls command

### LINKED ISSUE #47835: grafana-cli plugins ls only shows restart grafana message when invoked
**What happened**:
When invoking ```grafana-cli plugins ls``` the only output gotten is ```"Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary."```

**What you expected to happen**:
Get a list of installed plugins

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Plugins directory is set to default in grafana.ini. No overrides

**Environment**:
- Grafana version: 8.4.6
- Data source type & version: Prometheus version 2.15.2+ds (branch: debian/sid, revision: 2.15.2+ds-2)
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows 10 - Chrome
- Grafana plugins: grafana-image-renderer
- Others:

### PR DESCRIPTION
**Pull request by andresmgot**
**What is this feature?**

This PR clarifies some confusion from the execution of  `grafana-cli plugins ls`:

 - Updates the help text to specify that it only list externally installed plugins (not core ones).
 - Shows a new message if there are no installed plugins.
 - Move the info message about restarting grafana to the relevant commands.

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #47835

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/cmd/grafana-cli/commands/commands.go [hunk 1]
```diff
@@ -100,7 +100,7 @@ func runPluginCommand(command func(commandLine utils.CommandLine) error) func(co
 			return err
 		}
 
-		logger.Info(color.GreenString("Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.\n\n"))
+		logger.Info(color.GreenString("If you have recently installed a plugin, please restart Grafana. Refer to Grafana documentation for instructions if necessary.\n\n"))
```
Comment (wbrowne) [inline pkg/cmd/grafana-cli/commands/commands.go:103]: This one has always bugged me. WDYT if we finally moved this to the end of the relevant commands (`install`, `update`, `update-all`, `uninstall`) instead?

**Review by wbrowne — APPROVED** [review]
🚀
