### PR TITLE
remote_cache: Fix redis connstr parsing

### LINKED ISSUE #18199: 6.2.5: remote cache redis is parsing connstr wrong and leaks password plaintext to log
**What happened**:
When `connstr` contains a password with a `=` char (eg password used in Azure Redis PaaS instances) the parsing fails and also leaks the password in plain text to the container logs.
This even happens when the environment variables are used. Trible quotes are also not working.

**What you expected to happen**:
Parsing works and the password is NOT leaked to the log in case of failure.

**How to reproduce it (as minimally and precisely as possible)**:

```
[remote_cache]
type = redis
connstr = addr=127.0.0.1:6370,pool_size=100,password=foobar=
```

**Anything else we need to know?**:

The parsing is just too simple by splitting by `=` char:
https://github.com/grafana/grafana/blob/master/pkg/infra/remotecache/redis_storage.go#L25

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: not needed
- OS Grafana is installed on: Docker container on Kubernetes on Ubuntu
- User OS & Browser: Win 10, latest Chrome
- Grafana plugins: not needed
- Others:

### PR DESCRIPTION
**Pull request by mblaschke**
**What this PR does / why we need it**:
Fixes wrong splitting string after the first `=`, allows usage of base64 passwords like Azure Redis is using.
Instead of split the string into multiple pieces only split it into max of 2 pieces.

**Which issue(s) this PR fixes**:
Fixes #18199

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/infra/remotecache/redis_storage.go [hunk 1]
```diff
@@ -22,9 +22,14 @@ func parseRedisConnStr(connStr string) (*redis.Options, error) {
...
 	options := &redis.Options{Network: "tcp"}
 	for _, rawKeyValue := range keyValueCSV {
-		keyValueTuple := strings.Split(rawKeyValue, "=")
+		keyValueTuple := strings.SplitN(rawKeyValue, "=", 2)
 		if len(keyValueTuple) != 2 {
-			return nil, fmt.Errorf("incorrect redis connection string format detected for '%v', format is key=value,key=value", rawKeyValue)
+			if strings.HasPrefix(rawKeyValue, "password") {
+				// don't log the password
+				return nil, fmt.Errorf("incorrect redis connection string format detected for 'password', format is key=value,key=value")
+			} else {
```
Comment (papagian) [inline pkg/infra/remotecache/redis_storage.go]: As you may have noticed lint fails here with the following error:

> pkg/infra/remotecache/redis_storage.go
>   (30, 11)  https://revive.run/r#indent-error-flow  if block ends with a return statement, so drop this else and outdent its block

you have to remote the `else` and just return the error as proposed.

File: pkg/infra/remotecache/redis_storage.go [hunk 2]
```diff
@@ -22,9 +22,14 @@ func parseRedisConnStr(connStr string) (*redis.Options, error) {
 	keyValueCSV := strings.Split(connStr, ",")
 	options := &redis.Options{Network: "tcp"}
 	for _, rawKeyValue := range keyValueCSV {
-		keyValueTuple := strings.Split(rawKeyValue, "=")
+		keyValueTuple := strings.SplitN(rawKeyValue, "=", 2)
 		if len(keyValueTuple) != 2 {
-			return nil, fmt.Errorf("incorrect redis connection string format detected for '%v', format is key=value,key=value", rawKeyValue)
+			if strings.HasPrefix(rawKeyValue, "password") {
+				// don't log the password
+				return nil, fmt.Errorf("incorrect redis connection string format detected for 'password', format is key=value,key=value")
```
Comment (papagian) [inline pkg/infra/remotecache/redis_storage.go]: Instead of returning a different error I would proposed to censor the `rawKeyValue`.
In that case you could do something like this:

```
	for _, rawKeyValue := range keyValueCSV {
		keyValueTuple := strings.SplitN(rawKeyValue, "=", 2)
        censored := []byte(rawKeyValue)
		if len(keyValueTuple) != 2 {
			if strings.HasPrefix(rawKeyValue, "password") {
                for i := len("password"); i < len(rawKeyValue); i++ {
                    censored[i] = '*'
                }
			}
            return nil, fmt.Errorf("incorrect redis connection string format detected for '%v', format is key=value,key=value", string(censored))
		}
```

**Review by papagian — CHANGES_REQUESTED** [review]
Thank you for finding this and contributing your modifications!
I have proposed some additional changes before merging.

File: pkg/infra/remotecache/redis_storage.go (hunk 2 above)
Comment (mblaschke) [reply pkg/infra/remotecache/redis_storage.go]: Instead of leaking any information (eg. length of the password) what about the current solution? I think nobody is interested in the correct length so the error should be enough.

File: pkg/infra/remotecache/redis_storage.go [hunk 3]
```diff
@@ -22,8 +22,12 @@ func parseRedisConnStr(connStr string) (*redis.Options, error) {
 	keyValueCSV := strings.Split(connStr, ",")
 	options := &redis.Options{Network: "tcp"}
 	for _, rawKeyValue := range keyValueCSV {
-		keyValueTuple := strings.Split(rawKeyValue, "=")
+		keyValueTuple := strings.SplitN(rawKeyValue, "=", 2)
 		if len(keyValueTuple) != 2 {
+			if strings.HasPrefix(rawKeyValue, "password") {
+				// don't log the password
+				rawKeyValue = "password=******"
```
Comment (papagian) [inline pkg/infra/remotecache/redis_storage.go]: That is even better!
But can you remove the `=` symbol? Otherwise the message can be misleading since the actual error case here is the missing `=` symbol.

**Review by papagian — CHANGES_REQUESTED** [review]
That is even better. Just a small improvement.

File: pkg/infra/remotecache/redis_storage.go (hunk 3 above)
Comment (mblaschke) [reply pkg/infra/remotecache/redis_storage.go]: Fixe and thanks :)

**Review by papagian — APPROVED** [review]
