### PR TITLE
NodeGraph: Detect dataframes more accurately based on fields

### LINKED ISSUE #47019: NodeGraph: Make dataframe selection more permissive
**What you expected to happen**:
The Node Graph visualization should be more permissive when selecting dataframes to render. 
1. It should render dataframes with a refId of 'nodes' or 'edges'
2. The field name matching should be case insensitive (e.g. accept 'subTitle', 'subtitle', SUBTITLE')

**How to reproduce it (as minimally and precisely as possible)**:

### PR DESCRIPTION
**Pull request by connorlindsey**
**What this PR does / why we need it**:
Improves the node graph data frame selection to detect node graph frames based on the shape of the dataframe as a fallback in situations where users can't specify the preferredVisualizationType, frame name, or frame refId

**Which issue(s) this PR fixes**:
Fixes #47019

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/panel/nodeGraph/utils.ts [hunk 1]
```diff
@@ -323,11 +323,18 @@ export function getNodeGraphDataFrames(frames: DataFrame[]) {
...
       return true;
     }
-    if (frame.name === 'nodes' || frame.name === 'edges') {
+
+    if (frame.name === 'nodes' || frame.name === 'edges' || frame.refId === 'nodes' || frame.refId === 'edges') {
+      return true;
+    }
+
+    const fieldsCache = new FieldCache(frame);
+    if (fieldsCache.getFieldByName(NodeGraphDataFrameFieldNames.id)) {
```
Comment (connorlindsey) [inline public/app/plugins/panel/nodeGraph/utils.ts:337]: Node frames require the id field. Edge frames require id, source, and target. But since the intersection of those required fields is just id, we can only really check that. It's not a very thorough, but I think should be alright.

**Review by ivanahuckova — COMMENTED** [review]
I have 1 question, I see in the issue that matching should be case insensitive and that also `SUBTITLE` should be matched, which this PR doesn't cover. So I am wondering if it doesn't make sense to "normalize" nodes/edges when we are adding them to FieldsCache to let's say lowercase and then we could always use `NodeGraphDataFrameFieldNames.secondaryStat.toLowerCase()`? 

But maybe this doesn't make sense. Just curious.

**Comment by connorlindsey** [comment]
Good catch, got a lot tunneled on supporting lowercase instead of camelcase. I'll add support for that

File: docs/sources/visualizations/node-graph.md [hunk 2]
```diff
@@ -91,9 +91,9 @@ Optional fields:
...
 | title         | string        | Name of the node visible in just under the node.                                                                                                                                                         |
-| subTitle      | string        | Additional, name, type or other identifier that will be shown right under the title.                                                                                                                     |
-| mainStat      | string/number | First stat shown inside the node itself. Can be either string in which case the value will be shown as it is or it can be a number in which case any unit associated with that field will be also shown. |
-| secondaryStat | string/number | Same as mainStat but shown right under it inside the node.                                                                                                                                               |
+| subtitle      | string        | Additional, name, type or other identifier that will be shown right under the title.                                                                                                                     |
```
Comment (brendamuir) [inline docs/sources/visualizations/node-graph.md:94]:
```suggestion
| subtitle      | string        | Additional, name, type or other identifier shown under the title.                                                                                                                     |
```

File: docs/sources/visualizations/node-graph.md [hunk 3]
```diff
@@ -91,9 +91,9 @@ Optional fields:
...
+| mainstat      | string/number | First stat shown inside the node itself. Can be either string in which case the value will be shown as it is or it can be a number in which case any unit associated with that field will be also shown. |
```
Comment (brendamuir) [inline docs/sources/visualizations/node-graph.md:95]:
```suggestion
| mainstat      | string/number | First stat shown inside the node itself. It can either be a string showing the value as is or a number. If it is a number,  any unit associated with that field is also shown. |
```

File: docs/sources/visualizations/node-graph.md [hunk 4]
```diff
@@ -91,9 +91,9 @@ Optional fields:
...
+| secondarystat | string/number | Same as mainStat but shown right under it inside the node.                                                                                                                                               |
```
Comment (brendamuir) [inline docs/sources/visualizations/node-graph.md:96]:
```suggestion
| secondarystat | string/number | Same as mainStat, but shown under it inside the node.                                                                                                                                               |
```

File: docs/sources/visualizations/node-graph.md [hunk 5]
```diff
@@ -111,6 +111,6 @@ Optional fields:
...
 | ------------- | ------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
-| mainStat      | string/number | First stat shown in the overlay when hovering over the edge. Can be either string in which case the value will be shown as it is or it can be a number in which case any unit associated with that field will be also shown |
-| secondaryStat | string/number | Same as mainStat but shown right under it.                                                                                                                                                                                  |
+| mainstat      | string/number | First stat shown in the overlay when hovering over the edge. Can be either string in which case the value will be shown as it is or it can be a number in which case any unit associated with that field will be also shown |
```
Comment (brendamuir) [inline docs/sources/visualizations/node-graph.md:114]:
```suggestion
| mainstat      | string/number | First stat shown in the overlay when hovering over the edge. It can be a string showing the value as is or it can be a number. If it is a number,  any unit associated with that field is also shown |
```

File: docs/sources/visualizations/node-graph.md [hunk 6]
```diff
@@ -111,6 +111,6 @@ Optional fields:
...
+| secondarystat | string/number | Same as mainStat but shown right under it.                                                                                                                                                                                  |
```
Comment (brendamuir) [inline docs/sources/visualizations/node-graph.md:115]:
```suggestion
| secondarystat | string/number | Same as mainStat, but shown right under it.                                                                                                                                                                                  |
```

**Review by brendamuir — CHANGES_REQUESTED** [review]

**Review by ivanahuckova — APPROVED** [review]
There are still some tests failing related to lower-uppercasing. Other than that, code and tests look good! 🙂

**Comment by connorlindsey** [comment]
Thanks for the docs review @brendamuir, added in those changes :)

**Review by brendamuir — APPROVED** [review]
