### PR TITLE
Alerting: Get alert rules on faults (#61248)

### LINKED ISSUE #61248: Alerting: A single rule with a malformed data field is a single-point-of-failure for Unified Alerting
**What happened**:

I had one rule in my database, with a broken `data` field. Every single Unified Alerting rule was broken, the scheduler loaded no rules.

**What you expected to happen**:

I expected my one bad rule to not be scheduled, but the others to work normally.

**How to reproduce it (as minimally and precisely as possible)**:

1. Edit a rule's `data` field, at the DB level, to be invalid JSON.
2. Nothing works.
3. Check logs, all rules fail to schedule

This is because of how our validation works.

We leverage the ORM to deserialize the JSON in the database into Go structs automatically, as part of querying
https://github.com/grafana/grafana/blob/2a291afbae0cc97543802f4e161c7a6161f6d3c5/pkg/services/ngalert/models/alert_rule.go#L142
https://github.com/grafana/grafana/blob/2a291afbae0cc97543802f4e161c7a6161f6d3c5/pkg/services/ngalert/store/alert_rule.go#L457

And, we perform our validation at deserialization time.

So, if even one rule fails, the ORM returns an error for the batched query and yields nothing.

We should investigate how we can make this more resilient. One option can be: to do the query and deserialization as two separate steps, and if one rule fails to deserialize, we log it but still return the others for scheduling.

**Anything else we need to know?**:

Instead of just taking the alert rule struct, we should persist an alert rule database model.

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by bla2ej**
**What is this feature?**

When there is a corrupted rule in DB that does not deserialize correctly functions do return no alert rules.
This can lead to further problems when all alert rules disappear in the system. 

**Why do we need this feature?**

We should not impact correct alert rules when one is faulty. 

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #61248

**Special notes for your reviewer**:

Instead of using one step deserialization with Find function this change is 
- fetching records from DB to Rows
- loops over Rows and deserializes rows with Scan function

Error is logged if any rule deserialization fails.

### CODE REVIEW

File: pkg/services/ngalert/store/alert_rule.go [hunk 1]
```diff
@@ -275,9 +275,26 @@ func (st DBstore) ListAlertRules(ctx context.Context, query *ngmodels.ListAlertR
...
 
 		alertRules := make([]*ngmodels.AlertRule, 0)
-		if err := q.Find(&alertRules); err != nil {
+		var faultyRules int64 = 0
+		rule := new(ngmodels.AlertRule)
+		rows, err := q.Rows(rule)
+		if err != nil {
 			return err
 		}
+		defer rows.Close()
```
Comment (alexweav) [inline pkg/services/ngalert/store/alert_rule.go:284]: The linter noticed this too, but we can handle the return of close via this pattern instead:
```
defer func() {
    _ = rows.Close()
}()
```
If we really want, we can optionally log the error returned by Close

File: pkg/services/ngalert/store/alert_rule.go [hunk 2]
```diff
@@ -275,9 +275,26 @@ func (st DBstore) ListAlertRules(ctx context.Context, query *ngmodels.ListAlertR
 		q = q.Asc("namespace_uid", "rule_group", "rule_group_idx", "id")
 
 		alertRules := make([]*ngmodels.AlertRule, 0)
-		if err := q.Find(&alertRules); err != nil {
+		var faultyRules int64 = 0
```
Comment (alexweav) [inline pkg/services/ngalert/store/alert_rule.go:278]:
```suggestion
		var faultyRules int64
```
Nitpick:This or `faultyRules := int64(0)` is the style that's more commonly used in the project

File: pkg/services/ngalert/store/alert_rule.go [hunk 3]
```diff
@@ -275,9 +275,26 @@ func (st DBstore) ListAlertRules(ctx context.Context, query *ngmodels.ListAlertR
...
+		rule := new(ngmodels.AlertRule)
+		rows, err := q.Rows(rule)
+		if err != nil {
 			return err
 		}
+		defer rows.Close()
+		for rows.Next() {
```
Comment (alexweav) [inline pkg/services/ngalert/store/alert_rule.go:285]: Could we add a comment explaining why we're doing this by hand over `.Find(&someSliceOfRules)`? Just to prevent someone from refactoring this and undoing it in the future
```suggestion
		// Deserialize each rule separately in case any of them contain invalid JSON.
		for rows.Next() {
```

File: pkg/services/ngalert/store/alert_rule.go [hunk 4]
```diff
@@ -455,9 +472,28 @@ func (st DBstore) GetAlertRulesForScheduling(ctx context.Context, query *ngmodel
...
-		if err := sess.SQL(alertRulesSql, args...).Find(&rules); err != nil {
+		var faultyRules int64 = 0
+		rule := new(ngmodels.AlertRule)
+		rows, err := sess.SQL(alertRulesSql, args...).Rows(rule)
+		if err != nil {
 			return fmt.Errorf("failed to fetch alert rules: %w", err)
 		}
+		defer rows.Close()
+
+		for rows.Next() {
```
Comment (alexweav) [inline pkg/services/ngalert/store/alert_rule.go:483]: WDYT about extracting the iteration + logging into a func to keep things a little more DRY? The caller could look more like:

```
alertRules := make([]*ngmodels.AlertRule, 0)
rows, err := sess.SQL(...).Rows(ngmodels.AlertRule{})
if err != nil {
    ...
}
go func() {
    _ = rows.Close()
}()
h.scanRules(rows, &alertRules)
```
Not a requirement, just a thought.

File: pkg/services/ngalert/store/alert_rule.go [hunk 5]
```diff
@@ -455,9 +472,28 @@ func (st DBstore) GetAlertRulesForScheduling(ctx context.Context, query *ngmodel
...
+			rule := new(ngmodels.AlertRule)
+			err = rows.Scan(rule)
+			if err != nil {
+				faultyRules++
+				continue
+			}
```
Comment (alexweav) [inline pkg/services/ngalert/store/alert_rule.go:489]: A faulty rule is a really exceptional situation, let's emit a separate log for each faulty rule. This lets us capture more debug info like the actual error, this can help when operating Grafana
```suggestion
			if err != nil {
				st.Logger.Error("Faulty rule found in DB store, ignoring it", "func", "GetAlertRulesForScheduling", "error", err)
				continue
			}
```

**Review by alexweav — COMMENTED** [review]
Hey :wave: thanks for this contribution! It's looking good, my comments are just small ones.

File: pkg/services/ngalert/store/alert_rule.go (hunk 2 above)
Comment (grobinson-grafana) [inline pkg/services/ngalert/store/alert_rule.go:278]: I think I would like us to another variable name here. I don't think `faulty` is the right word, and I was thinking we could be more precise that these are invalid definitions. In my opinion, a `faulty` rule means something else, specifically that the rule doesn't behave as intended. For example, it fires when it shouldn't.

**Comment by bla2ej** [comment]
@alexweav 
I tried to update according to your comments. I have not taken out scanning to separate function as I'm not sure if it's worth to do for so simple code.

@grobinson-grafana 
I completely removed this counter but I've updated error message to `invalid` instead of `faulty`

I'm new in this project event if I'm using Grafana daily so please let me know if I can do something in a better way.

**Review by alexweav — APPROVED** [review]
> I have not taken out scanning to separate function as I'm not sure if it's worth to do for so simple code.

Makes sense! I'm okay with it.

> I'm new in this project event if I'm using Grafana daily so please let me know if I can do something in a better way.

We appreciate the contribution very much! It's looking good to me :+1:

**Comment by alexweav** [comment]
Backport is merged, this will be in 9.4.1 @bla2ej

**Comment by bla2ej** [comment]
Thanks, first one merged for Grafana :)
