### PR TITLE
CloudWatch Logs: Add labels to alert and expression queries

### LINKED ISSUE #63388: CloudWatch Logs: queries returning multiple time series cannot be used in alert rules
**What happened**:
CloudWatch Logs returning multiple time series cannot be used in alert rules. I can see this problem was reported in another issue's comment in the past (https://github.com/grafana/grafana/issues/46429#issuecomment-1185375094).

**What you expected to happen**:
Each time series returned in a CloudWatch logs query should be evaluated individually in an alert rule. 

**How to reproduce it (as minimally and precisely as possible)**:
Select the CloudWatch Logs data source and write a query returning multiple time series, like the following (if more than one log group is selected):
```
stats count(*) by bin(1h), @log
```
Each individual time series is shown correctly in a time series panel:

If the query above is used in an alert rule instead, the error `Failed to evaluate queries and expressions: input data must be a wide series but got type long (input refid)` pops up:

The alert rule works if the query returns a single time series:
```
stats count(*) by bin(1h)
```

**Anything else we need to know?**:
I have not been able to apply panel expressions (like `Reduce`) to CloudWatch Logs queries either: I always get an error. Maybe the issue is related?
Also, in case it's useful: I've checked the Query Inspector for the query above. No `labels` are populated, and `@log` is a textual field. 
```
{
  "response": {
    "results": {
      "A": {
        "status": 200,
        "frames": [
          {
            "schema": {
              "name": "/loggroup1",
              "refId": "A",
              "meta": {...}
              "fields": [
                {
                  "name": "bin(1h)",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time",
                    "nullable": true
                  },
                  "labels": {}
                },
                {
                  "name": "@log",
                  "type": "string",
                  "typeInfo": {
                    "frame": "string",
                    "nullable": true
                  },
                  "labels": {}
                },
                {
                  "name": "count(*)",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {}
                }
              ]
            },
...
```

**Environment**:
- Grafana version: tested in 9.3.1, 9.3.2, 9.3.6
- Data source type & version: Cloudwatch 5.0.0
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Ubuntu 20.04, Firefox 109
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by iwysiu**
**What is this feature?**

Labels the grouped fields for sync CloudWatch Logs queries with the fields they were grouped on.

**Why do we need this feature?**

In order for CloudWatch Logs queries returning multiple time series to be useful in alerts, the different time series need to be labeled with their grouping information

**Who is this feature for?**

Users that want to use CloudWatch Logs queries with multiple time series in alerts.

**Which issue(s) does this PR fix?**:

Fixes #63388 

**Special notes for your reviewer:**

Making this a bug because it should work, even if it never has.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/tsdb/cloudwatch/log_query.go [hunk 1]
```diff
@@ -205,14 +205,16 @@ func groupResults(results *data.Frame, groupingFieldNames []string, fromSyncQuer
 			if fromSyncQuery {
 				// remove grouping indices
 				newFrame.Fields = removeFieldsByIndex(newFrame.Fields, removeFieldIndices)
+				groupLabels := generateLabels(groupingFields, i)
 
 				// set the group key as the display name for sync queries
-				for i := 1; i < len(newFrame.Fields); i++ {
-					valueField := newFrame.Fields[i]
+				for j := 1; j < len(newFrame.Fields); j++ {
```
Comment (iwysiu) [inline pkg/tsdb/cloudwatch/log_query.go:211]: changed this to a `j` because I realized it's nested in a for loop using `i`

**Review by kevinwcyu — APPROVED** [review]
nice, tested and labels are showing properly now 🎉
