### PR TITLE
DashboardScene: Fix issues with dashboard empty state

### LINKED ISSUE #84569: Discarding changes to an empty dashboard has no effect - changes are still visible.
- Create and save an empty dashboard.
- Refresh page
- Add a panel (without entering edit mode)
- Go back do dashboard (panel should be added)
- Exit edit mode and discard changes
- Booom: Panel is still visible on that dashboard that should be empty

### LINKED ISSUE #84570: Adding library panel from an empty state doesn't work
Adding a library panel from the empty dashboard state (save and refresh and empty dashboard) does not enable dashboard edit mode, hence one cannot save a newly added lib panel

### LINKED ISSUE #85405: Adding to an empty dashboard is not possible after panel removal
1. Create and save empty dashboard
2. refresh
3. add panel and go back to dashboard
4. exit edit mode.
5. add panel.
6. go back to dasboard - EMPTY STATE is shown

### PR DESCRIPTION
**Pull request by dprokop**
Fixes https://github.com/grafana/grafana/issues/84569
Fixes https://github.com/grafana/grafana/issues/84570
Fixes https://github.com/grafana/grafana/issues/85405

Thanks to a great investigation by @kaydelaney we narrowed the bug to be caused deactivation of `trackIfIsEmpty` behavior and not re-activating it when the grid is rendered back. We could solve it in a more complex way as proposed in https://github.com/grafana/grafana/issues/84569, but I think there's no need for adding this complexity, when we can for now just render the grid even when the dashboard is empty. The grid will render an empty div in such scenario which should be fine.

### CODE REVIEW

**Review by kaydelaney — APPROVED** [review]

File: public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts [hunk 1]
```diff
@@ -285,6 +285,7 @@ export function createDashboardSceneFromDashboardModel(oldModel: DashboardModel)
     body: new SceneGridLayout({
       isLazy: true,
       children: createSceneObjectsForPanels(oldModel.panels),
+      $behaviors: [trackIfEmpty],
```
Comment (dprokop) [inline public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts:288]: @kaydelaney  - I'm also moving the behavior to the grid as i think it belongs here, also makes the behavior simpler.
