### PR TITLE
Prometheus: Send time range params when requesting labels

### LINKED ISSUE #56479: ad-hoc filter is missing 'remove', POST /api/v1/labels fail with code 500, missing body with start and end time
Ad-hoc filter is missing 'remove' and not able to remove the filter

'remove' option shall appear on combox

Grafana is sending POST  [/grafana/api/datasources/218/resources/api/v1/labels]
to get all labels, it will fail with code 500

The POST is missing a body with start and end time

https://prometheus.io/docs/prometheus/latest/querying/api/

start=<rfc3339 | unix_timestamp>: Start timestamp. Optional.
end=<rfc3339 | unix_timestamp>: End timestamp. Optional.
match[]=<series_selector>: Repeated series selector argument that selects the series from which to read the label names. Optional.

There is another way to list all labels from Prometheus by a variable: 
label_names()

It is working fine because it has a POST body with start and end time

it takes 7 seconds to get all labels.

POST ok, with payload
image

POST fail, missing payload:
image

**Environment**:
- Grafana version: 9.1.7
- Data source type & version: Prometheus latest
- OS Grafana is installed on:
- User OS & Browser: K8S
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

We were not sending the time range param when we are requesting `labels` from Prometheus when we are querying ad-hoc filters. It was not the case for other `labels` calls. So I added time range params into ad-hoc filter calls. 

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/56479

**Special notes for your reviewer**:

Set up a Prometheus datasource and dashboard with minimal requirements. Create an ad-hoc filter variable and normal variable with the query `label_names()`. 
Observe the second variable calls the` labels` endpoint with time range params. 
Observe ad-hoc filter will also call `labels` with time range and get the response back successfully.

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/datasource.tsx [hunk 1]
```diff
@@ -895,7 +895,14 @@ export class PrometheusDatasource
...
     } else {
       // Get all tags
-      const result = await this.metadataRequest('/api/v1/labels');
+      const range = this.timeSrv.timeRange();
+      const start = this.getPrometheusTime(range.from, false);
+      const end = this.getPrometheusTime(range.to, true);
+      const params = {
+        start: start.toString(),
+        end: end.toString(),
+      };
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/prometheus/datasource.tsx:904]:
```suggestion
      const params = this.getTimeRangeParams();
```

I think you can just use this

**Review by ivanahuckova — COMMENTED** [review]
LGTM. Btw, I noticed that in `getTagValues` you are also not sending time range params. In Loki we always send time range params for both queries https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/datasource.ts#L380-L391

**Review by ivanahuckova — APPROVED** [review]
✨
