### PR TITLE
GraphNG: Fix exemplars window position

### LINKED ISSUE #32989: Cannot click exemplar if datapoint is in bottom left of graph
**What would you like to be added**:

Something that perhaps moves the "pop out" menus for exemplars based on where they are on screen.

NB this is not just explore, but also on dashboards.

Grafana v7.5.3

**Why is this needed**:

image

### PR DESCRIPTION
**Pull request by zoltanbedi**
**Which issue(s) this PR fixes**:

Fixes #32989

**Special notes for your reviewer**:

This didn't work because the ref's value was always 0 in the useLayoutEffect.

### CODE REVIEW

File: packages/grafana-ui/src/components/VizTooltip/VizTooltipContainer.tsx [hunk 1]
```diff
@@ -25,7 +25,7 @@ export const VizTooltipContainer: React.FC<VizTooltipContainerProps> = ({
   ...otherProps
 }) => {
   const tooltipRef = useRef<HTMLDivElement>(null);
-  const tooltipMeasurementRef = useRef<Dimensions2D>({ width: 0, height: 0 });
+  const [tooltipMeasurement, setTooltipMeasurement] = useState<Dimensions2D>({ width: 0, height: 0 });
```
Comment (dprokop) [inline packages/grafana-ui/src/components/VizTooltip/VizTooltipContainer.tsx:28]: ah, so the ref was 0 because of the layout effect being called before flushing to DOM :(

**Review by dprokop — APPROVED** [review]
Works good. Testes against tooltips and haven't noticed any regression
