### PR TITLE
Accessibility: Default Icon to aria-hidden

### LINKED ISSUE #79513: [accessibility issue] Icons appear in the accessibility tree
**Steps to reproduce**:
Go to a Grafana instance (e.g. play.grafana.com), open your dev tools and inspect the accessibility tree. Notice that all instances of `<Icon />` appear as an image with no description.

A screenshot of a Grafana homepage with Chrome dev tools open on the accessibility tree and with VoiceOver rotor menu for images present. It shows that almost all of the images recognised by the screen rotor are just listed as "image". The image values in the accessibility tree are also blank.

**Expected Result**
Most (all?) of our icons are purely decorative and don't add any extra meaningful information which isn't already provided by the surrounding context (e.g. an IconButton should have an aria-label on it).

I am slightly hesitant to suggest putting `aria-hidden="true"` on by default but I think this is probably a sensible default that developers can choose to opt out of?

An example is the keyboard icon in the command bar could add some useful text to benefit to indicate it is denoting a keyboard shortcut but is that implicit anyway by the accompanying text (cmd + k)?

UHG checkpoint: 1.111

### PR DESCRIPTION
**Pull request by tskarhed**
**What is this feature?**

Defaults the Icon component to `aria-hidden`, and adds documentation encouraging adding an accessible title.

**Why do we need this feature?**

Empty images fill up the a11y tree, often when they lack semantic meaning.

**Who is this feature for?**

Screen reader users.

**Which issue(s) does this PR fix?**:

Fixes #79513 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by eledobleefe — COMMENTED** [review]
As long as I know, the code looks good but you're missing modifying the failing tests according to your changes 🤔

File: public/app/features/alerting/unified/components/rules/RulesFilter.tsx [hunk 1]
```diff
@@ -232,7 +232,7 @@ const RulesFilter = ({ onFilterCleared = () => undefined }: RulesFilerProps) =>
                     <Stack gap={0.5}>
                       <span>Search</span>
                       <HoverCard content={<SearchQueryHelp />}>
-                        <Icon name="info-circle" size="sm" tabIndex={0} />
+                        <Icon name="info-circle" size="sm" tabIndex={0} title="Search help" />
                       </HoverCard>
```
Comment (tskarhed) [inline public/app/features/alerting/unified/components/rules/RulesFilter.tsx:236]: The popup from the `HoverCard` is not keyboard accessible. It should be changed to the `ToggleTip` component.

Comment (eledobleefe) [reply public/app/features/alerting/unified/components/rules/RulesFilter.tsx:241]: Would it not be better to make these changes in a separate PR and just leave this one only to improve the documentation and default the Icon to `aria-hidden`? 🤔

**Review by ckbedwell — APPROVED** [review]
I think this works great. I thought I had some initial comments but I've had a play with it in a few different scenarios and it does everything I'd like it to. Great job 💪

File: packages/grafana-ui/src/components/Icon/Icon.mdx [hunk 2]
```diff
@@ -7,6 +7,14 @@ import { Icon } from './Icon';
 
 Grafana's wrapper component over [Font Awesome](https://fontawesome.com/) and Unicons icons
 
+## Accessibility
+
+`Icon` is aria-hidden by default. If your icon has semantic meaning, please provide a `title` or wrap it in a `Tooltip`.
```
Comment (ckbedwell) [inline packages/grafana-ui/src/components/Icon/Icon.mdx:12]: Actually, I do have one comment, I think we are better off recommending `aria-label` or `aria-labelledby` rather than `title`. In the screenshot below when it has a title the default browser tooltip appears covering some of the information in the Grafana tooltip.

Screenshot of a Grafana tooltip being partially covered by a browser tooltip.

Comment (tskarhed) [reply packages/grafana-ui/src/components/Icon/Icon.mdx:12]: I agree that this should be the case when using it with the `Tooltip`, but I think `title` is a better option when that's not the case, as it can provide information for non-screen readers too.

**Review by eledobleefe — APPROVED** [review]
LGTM 👌
