### PR TITLE
#42174: fix: fill 'field.name' in the auto-added Time field

### LINKED ISSUE #42174: Live: missing time when selecting individual fields from streaming frames
**What happened**:

https://user-images.githubusercontent.com/12394084/143134680-735357e8-3f26-4fd9-bc88-0b37f10818c3.mp4

**What you expected to happen**:
Would expect a single real-time streaming time-series to show up, equivalent to when selecting from the legend itself, as in the beginning of the video.

**How to reproduce it (as minimally and precisely as possible)**:
Select any of the streaming channel from here (within Live measurements under Grafana datasouece):

Screen Shot 2021-11-23 at 1 51 39 PM

And then try to select an individual field from within, as shown in the video.

**Anything else we need to know?**:

NOTE: This is using the `jsonauto` converter from the Live pipeline, and the time stamp is being added onto the frame from the backend.

A possible solution:
Maybe for these situations we should default to including the time field unless the user explicitly deselects it from the UI (in case they want to use their own from the json data being ingested in)

### PR DESCRIPTION
**Pull request by ArturWierzbicki**
**What this PR does / why we need it**:
details in https://github.com/grafana/grafana/issues/42174

`QueryEditor` looks for the time field based on the `field.name` value: https://github.com/grafana/grafana/blob/6bda64cb193771256bab56060da2df067ce6f72a/public/app/plugins/datasource/grafana/components/QueryEditor.tsx#L133

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/42174

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/live/pipeline/json_to_frame.go [hunk 1]
```diff
@@ -108,6 +108,7 @@ func jsonDocToFrame(name string, body []byte, fields map[string]Field, nowTimeFu
 	}
 
 	f := data.NewFieldFromFieldType(data.FieldTypeTime, 1)
+	f.Name = "Time"
```
Comment (ArturWierzbicki) [inline pkg/services/live/pipeline/json_to_frame.go:111]: Fixed it here rather than in frontend as `name` is marked as non-nullable https://github.com/grafana/grafana/blob/c41b5d80a3bdceb658f3815e36671155000eeef3/packages/grafana-data/src/dataframe/DataFrameJSON.ts#L89 so we always expect it to be filled

**Review by FZambia — COMMENTED** [review]
👍

**Review by FZambia — APPROVED** [review]

**Review by atifali — APPROVED** [review]
solves the issue for me - lets merge this

Peek 2021-1278
