### PR TITLE
Logs: Fixed wrapping log lines from detected fields

### LINKED ISSUE #48398: "Show this field" does not honor "Wrap lines" option in Explore
**What happened**:

When using Grafana Explore with structured logs, enabling `Show this field instead of the message` activates line-wrapping, dispite the `Wrap lines` option being off.

**What you expected to happen**:

`Show this field instead of the message` should honor line wrap settings.

**How to reproduce it (as minimally and precisely as possible)**:

- Go to <https://play.grafana.org/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bfilename%3D%5C%22%2Fvar%2Flog%2Fnginx%2Fjson_access.log%5C%22%7D%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D>
or get some structed logs with long properties, the explore loki query is `{filename="/var/log/nginx/json_access.log"}`
- There are structured `json` logs
- Default: "Wrap lines" and "Prettify JSON" is Disabled
- Expand a message and use `Show this field instead of the message` on a long text property, here `http_user_agent` is suitable
- Long lines are now "wrapped", dispite `Wrap lines` being disabled (See screenshots)

grafik

grafik

grafik

firefox_mdLAlhgzKc

**Environment**:
- Grafana version: `v8.5.0`
- Data source type & version: loki

### PR DESCRIPTION
**Pull request by svennergr**
**What this PR does / why we need it**:
Log lines with detected fields are not wrapped if enabled.

**Which issue(s) this PR fixes**:

Fixes #48398

**Special notes for your reviewer**:

https://user-images.githubusercontent.com/8092184/178507519-67546161-0b9b-4186-a8aa-d18273254a51.mov

### CODE REVIEW

File: packages/grafana-ui/src/components/Logs/LogRowMessageDetectedFields.tsx [hunk 1]
```diff
@@ -19,12 +19,11 @@ class UnThemedLogRowMessageDetectedFields extends PureComponent<Props> {
...
     const fields = getAllFields(row, getFieldLinks);
-    const wrapClassName = cx(
-      wrapLogMessage &&
-        css`
-          white-space: pre-wrap;
-        `
-    );
+    const wrapClassName = wrapLogMessage
+      ? ''
+      : cx(css`
```
Comment (ivanahuckova) [inline packages/grafana-ui/src/components/Logs/LogRowMessageDetectedFields.tsx:24]: I think we can remove `cx` from here, as we are not merging more classnames?

Comment (svennergr) [reply packages/grafana-ui/src/components/Logs/LogRowMessageDetectedFields.tsx]: Sure, definitely. Removed it 👍

**Review by ivanahuckova — APPROVED** [review]
LGTM, nice!
