### PR TITLE
CloudMonitoring: Fixes broken variable queries that use group bys

### LINKED ISSUE #43504: Google Cloud Monitoring metadata missing
We just noticed that the metadata appears to be missing for Cloud SQL instances, so my customer can no longer retrieve the list of instance names, see the attached screenshot.

My customer were pulling the label values for all “metadata.system_labels.name”, which previously returned all the Cloud SQL instance names, so they could populate the drop down menu, but now they get ”None” back from this label key.

Do you know if something changed around the metadata/system_labels recently?

We from Google Cloud Side confirmed that based on the internal assessment on this issue, we saw in metric explorer it is being populated correctly. Leading us to believe the issue is not with our API but with the query the stackdriver plugin is using. 

Grafana_Screenshot
GoogleCloud_Screenshot

Based on the information provided we can find nothing wrong from Google Cloud Side, hence raising this at Grafana end.

### PR DESCRIPTION
**Pull request by sunker**
**What this PR does / why we need it**:
After a recent API change, cloud monitoring ignores the group by in case the crossSeriesReducer is set to _REDUCE_NONE_. This caused issues in the CloudMonitoring plugin when loading labels that were used in variables queries and in queries that return labels that would be used in the filter section. This PR ensures a crossSeriesReducer other than _REDUCE_NONE_ is always specified in case a group by was provided. 
**Which issue(s) this PR fixes**:

Fixes #43504

### CODE REVIEW

File: public/app/plugins/datasource/cloud-monitoring/CloudMonitoringMetricFindQuery.ts [hunk 1]
```diff
@@ -100,7 +100,10 @@ export default class CloudMonitoringMetricFindQuery {
       return [];
     }
     const refId = 'handleLabelValuesQuery';
-    const labels = await this.datasource.getLabels(selectedMetricType, refId, projectName, [labelKey]);
+    const labels = await this.datasource.getLabels(selectedMetricType, refId, projectName, {
+      groupBys: [labelKey],
+      crossSeriesReducer: 'REDUCE_MEAN',
```
Comment (andresmgot) [inline public/app/plugins/datasource/cloud-monitoring/CloudMonitoringMetricFindQuery.ts:105]: a comment (or better a test) to explain why this is set would be helpful

**Review by andresmgot — APPROVED** [review]
:+1: one minor comment

**Comment by andresmgot** [comment]
_merging this to be included in 8.3.4_
