### PR TITLE
Time Series: Fix X-axis time format when tick increment is larger than a year

### LINKED ISSUE #36169: [Grafana 8.0.3] Dashboard and panel display bugs
Dashboard display bug
**Environment**:
- Grafana version: 8.0.3
- Data source type & version: mysql (Time series or Table)
- OS Grafana is installed on: windows 10
- User OS & Browser: firefox 89.0.1  x64
- Grafana plugins: Time series

if increase time range or reduce browser windows ，X axis will display error, the same problem appears on the panel

图片

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #36169

### CODE REVIEW

File: packages/grafana-ui/src/components/Modal/Modal.tsx [hunk 1]
```diff
@@ -79,7 +80,9 @@ export function Modal(props: PropsWithChildren<Props>) {
             <IconButton surface="header" name="times" size="xl" onClick={onDismiss} />
           </div>
         </div>
-        <div className={cx(styles.modalContent, contentClassName)}>{children}</div>
+        <div className={cx(styles.modalContent, contentClassName)}>
+          <CustomScrollbar>{children}</CustomScrollbar>
```
Comment (jackw) [inline packages/grafana-ui/src/components/Modal/Modal.tsx:84]: Does this add `overflow-y: hidden` and if so will it reintroduce the `<Select/>` inside `<Modal />` bug that was fixed recently?

Comment (torkelo) [reply packages/grafana-ui/src/components/Modal/Modal.tsx:84]: ah sorry this was me trying to experiment with fixing https://github.com/grafana/grafana/issues/36317 (in a generic way) before starting this fix, will remove

**Review by dprokop — APPROVED** [review]
