### PR TITLE
Fix bug that was breaking aws-sdk ConnectionConfig

### LINKED ISSUE #41211: Cloudwatch Bug: Access and Secret Key input fields broken
**What happened**:
I'm on the main branch and tried to set up a new Cloudwatch datasource and couldn't type anything in the access or secret keys

**What you expected to happen**:
I would expect to be able to type in these fields

**How to reproduce it (as minimally and precisely as possible)**:
Add a new cloudwatch datasource and select access and secret key

### PR DESCRIPTION
**Pull request by sarahzinger**
**What this PR does / why we need it**:
I believe in [one of our typescript fixes](https://github.com/grafana/grafana/pull/40675/files#diff-0b7f2cb8a0cff4dccdfd5b50ce6c6963d3ffa3f476341d6bd79beb7fe2b2611cR85), we accidentally introduced a bug (that was easy to write because of a lack of typing haha). Hopefully use strict will make this sort of thing, a thing of the past.

**Which issue(s) this PR fixes**:

Fixes #41211

**Special notes for your reviewer**:
To reproduce bug/fix:
- try to add a datasource that uses the aws-sdk ConnectionConfig (ex: Cloudwatch)
- select keys/access id
- notice you can't type in the access key.
- I then hacked a local version of our aws-sdk (I did this by making a folder in core grafana and copying over the src files from the aws-sdk and changing the import ConnectionConfig to import from that folder instead, although I'm sure there are much better ways to do this)

Tbh I'm not sure on the difference between secureJsonFields vs secureJsonData, I think we're expecting one but getting the other. This seems like a hacky fix that should work for now tho as I think it's basically what we had before and the problem goes away for me when I do this. 

Edit to add:
Just noting that I'm not adding a milestone because I think the bug was both introduced for 8.3 and then fixed before 8.3 could be released so I don't think it's necessary

### CODE REVIEW

**Comment by ryantxu** [comment]
Editing a value still seems broken -- try clicking the pencil icon after editing:
image

File: packages/grafana-data/src/utils/datasource.ts [hunk 1]
```diff
@@ -118,16 +118,13 @@ export const updateDatasourcePluginSecureJsonDataOption = <J, S extends {} = Key
...
   const config = props.options;
-  if (!config.secureJsonData) {
-    return;
-  }
 
   props.onOptionsChange({
     ...config,
     secureJsonData: {
-      ...config.secureJsonData,
+      ...(config.secureJsonData ? config.secureJsonData : {}),
```
Comment (andresmgot) [inline packages/grafana-data/src/utils/datasource.ts:125]: in theory, using `as ...` was a bit of cheating but I cannot find a better a solution (I don't know if someone has a better suggestion). We can reduce the scope a bit just setting the type of the empty object:

```suggestion
      ...(config.secureJsonData ? config.secureJsonData : {} as S),
```

File: packages/grafana-data/src/utils/datasource.ts [hunk 2]
```diff
@@ -136,16 +133,12 @@ export const updateDatasourcePluginResetOption = <J, S extends {} = KeyValue>(
...
 ) => {
   const config = props.options;
-  if (!config.secureJsonData) {
-    return;
-  }
-
   props.onOptionsChange({
     ...config,
     secureJsonData: {
       ...config.secureJsonData,
```
Comment (andresmgot) [inline packages/grafana-data/src/utils/datasource.ts:139]: we should use the same ternary operator here?

**Review by andresmgot — COMMENTED** [review]
Thanks for fixing this! For me it would be a +1

**Comment by andresmgot** [comment]
> Editing a value still seems broken -- try clicking the pencil icon after editing:

If you mean that the input is emptied that was the behavior before (to protect the secret content).

**Comment by sarahzinger** [comment]
@andresmgot I think @ryantxu here is referring to the fact that before my second commit in this pr the same issue of not editing the input fields was happening, I just hadn't noticed we had the same problem there. 

Anyway should be fixed now if either one of you want to take another look for me and give a ✅  I can merge this

**Review by andresmgot — APPROVED** [review]
it works for me!
