### PR TITLE
Redact sensitive values before logging them

### LINKED ISSUE #33340: GF_AUTH_SAML_PRIVATE_KEY env variable not obfuscated during startup
**What happened**:
We just turned on SAML auth for our grafana install, and unlike other sensitive environment variables like `GF_DATABASE_PASSWORD` or `GF_SECURITY_SECRET_KEY`, the fields `GF_AUTH_SAML_PRIVATE_KEY` and `GF_AUTH_SAML_CERTIFICATE` are not obfuscated in the startup logs, and are instead visible in their entirety. The log lines look like:
```
t=2021-04-23T21:02:40+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_AUTH_SAML_PRIVATE_KEY=<actual private key in plaintext>
```

**What you expected to happen**:
A logline similar to this:
```
t=2021-04-23T21:02:40+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_DATABASE_PASSWORD=*********"
```

**How to reproduce it (as minimally and precisely as possible)**:
Configure SAML auth on 7.3.10

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.10
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by zserge**
There have been different approaches to handle sensitive data in the logs, this PR tries to unify them.

1. Here we expose RedactedPassword string constant, so that at least all masked values would look the same. This should only be used when data is redacted manually.
2. For automated redaction there is a `RedactValue(k, v)` helper, that a) checks if the key is sensitive (password, certificates, keys etc) and if so b) replaces value with RedactedPassword or url.Redact

This PR removes database URL validation from the settings package, however it enables database URL validation in the sqlstore package. As a bonus, the tests there are updated to avoid using goconvey.

Closes #33340.

### CODE REVIEW

File: pkg/services/sqlstore/sqlstore_test.go [hunk 1]
```diff
@@ -66,44 +68,50 @@ var sqlStoreTestCases = []sqlStoreTest{
...
-				sqlstore.Cfg = makeSQLStoreTestConfig(testCase.dbType, testCase.dbHost)
-				sqlstore.readConfig()
+	for _, testCase := range sqlStoreTestCases {
+		t.Run(testCase.name, func(t *testing.T) {
+			sqlstore := &SQLStore{}
+			sqlstore.Cfg = makeSQLStoreTestConfig(t, testCase.dbType, testCase.dbHost, testCase.dbURL)
+			if err := sqlstore.readConfig(); err != nil {
+				require.Equal(t, testCase.err.Error(), err.Error())
+				return
+			}
```
Comment (aknuds1) [inline pkg/services/sqlstore/sqlstore_test.go:86]: Some problems with this approach:

* If `testCase.err` is nil, you get a segfault
* If `testCase.err` is non-nil and `err` is nil, the former gets ignored

File: pkg/services/sqlstore/sqlstore_test.go [hunk 2]
```diff
@@ -66,44 +68,50 @@ var sqlStoreTestCases = []sqlStoreTest{
...
-	})
+			for _, connSubStr := range testCase.connStrValues {
+				require.Contains(t, connStr, connSubStr)
+			}
+		})
+	}
 }
 
-func makeSQLStoreTestConfig(dbType string, host string) *setting.Cfg {
+func makeSQLStoreTestConfig(t *testing.T, dbType, host, dbURL string) *setting.Cfg {
```
Comment (aknuds1) [inline pkg/services/sqlstore/sqlstore_test.go:98]: Nit, but test helpers should be flagged correspondingly (makes a difference when stack gets dumped on test failure):
```suggestion
func makeSQLStoreTestConfig(t *testing.T, dbType, host, dbURL string) *setting.Cfg {
	t.Helper()

```

File: pkg/services/sqlstore/sqlstore_test.go [hunk 3]
```diff
@@ -66,44 +68,50 @@ var sqlStoreTestCases = []sqlStoreTest{
...
 	cfg := setting.NewCfg()
 
 	sec, err := cfg.Raw.NewSection("database")
-	So(err, ShouldBeNil)
+	require.Nil(t, err)
```
Comment (aknuds1) [inline pkg/services/sqlstore/sqlstore_test.go:102]: Nit, but we should use `require.NoError` instead of `require.Nil` to check for absence of errors:

```suggestion
	require.NoError(t, err)
```

**Review by aknuds1 — APPROVED** [review]
Looks good to me, although there're problems with the error checking approach in a test as I've commented.

File: pkg/services/sqlstore/sqlstore_test.go [hunk 4]
```diff
@@ -66,44 +68,53 @@ var sqlStoreTestCases = []sqlStoreTest{
...
 }
 
 func TestSQLConnectionString(t *testing.T) {
-	Convey("Testing SQL Connection Strings", t, func() {
-		t.Helper()
+	for _, testCase := range sqlStoreTestCases {
+		t.Run(testCase.name, func(t *testing.T) {
+			sqlstore := &SQLStore{}
+			sqlstore.Cfg = makeSQLStoreTestConfig(t, testCase.dbType, testCase.dbHost, testCase.dbURL)
+			if err := sqlstore.readConfig(); err != nil {
```
Comment (aknuds1) [inline pkg/services/sqlstore/sqlstore_test.go:83]: There's still the problem that if `testCase.err != nil`, it doesn't get caught when `err == nil`.

**Review by marefr — APPROVED** [review]
LGTM

Great work :+1:
