### PR TITLE
A11y: Fix a11y for toolbar buttons in PanelEditor

### LINKED ISSUE #53844: A11y:  Update toolbar buttons in  PanelEditor to not use HTML Title for tooltip
**Steps to reproduce**:
1. Go here: https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&editPanel=4
2. Hover over "Settings", "Discard", "Save", "Apply" or "Data Source Help" icon button under Query 

**Actual Result**:
Native HTML tooltip is displayed on **hover**, uses HTML title|
No tooltip is displayed on **focus**

**Expected Result**
- Use of ARIA tags to ensure tooltip is accessible and correct styling applied to remain consistent with other tooltip implementations
- Tooltip displays on focus
**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)
https://www.w3.org/WAI/WCAG22/Understanding/content-on-hover-or-focus

**Environment**:
- Grafana version:
- Data source type & version:
- User OS & Browser:
- Others:

### PR DESCRIPTION
**Pull request by vbeskrovnov**
**What this PR does / why we need it**:
Use `tooltip` instead of `title` to fix a11y for toolbar buttons.

Result:
image

**Which issue(s) this PR fixes**:

Fixes #53844

**Special notes for your reviewer**:
There is an issue with `aria-label` for Button component (for "Data Source Help"), I think it is better to fix in the separate PR.

### CODE REVIEW

**Review by axelavargas — APPROVED** [review]
Hey @vbeskrovnov, thanks for helping to make Grafana more accessible 👏🏾 , the code looks great and works as expected.

ps, I think you might need to merge the latest `main` branch to fix some CI errors :)

ps2: I think also you need to fix the `public/app/features/dashboard/containers/DashboardPage.test.tsx`, it was relying on the old behavior :)

File: public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx [hunk 1]
```diff
@@ -338,32 +338,31 @@ export class PanelEditorUnconnected extends PureComponent<Props> {
...
           Save
         </ToolbarButton>
       ),
       <ToolbarButton
         onClick={this.onBack}
         variant="primary"
-        title="Apply changes and go back to dashboard"
+        tooltip="Apply changes and go back to dashboard"
         key="apply"
-        aria-label={selectors.components.PanelEditor.applyButton}
```
Comment (axelavargas) [inline public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:366]: 🤔 I think we are using this selector for our e2e tests, our CI is complaining https://drone.grafana.net/grafana/grafana/75446/2/17

failed [e2e test](https://github.com/grafana/grafana/blob/main/e2e/shared/smokeTestScenario.ts#L27)

Comment (axelavargas) [reply public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:366]: no problem 👍🏾 , and thank you again 🤗

**Comment by vbeskrovnov** [comment]
Not sure how to fix `Error response from daemon: Get "https://registry-1.docker.io/v2/": EOF` error from CI

**Comment by vbeskrovnov** [comment]
> Hey @vbeskrovnov, thanks for helping to make Grafana more accessible 👏🏾 , the code looks great and works as expected.
> 
> ps, I think you might need to merge the latest `main` branch to fix some CI errors :)
> 
> ps2: I think also you need to fix the `public/app/features/dashboard/containers/DashboardPage.test.tsx`, it was relying on the old behavior :)

Hey @axelavargas! :) 
I fixed all tests and failed builds. Still have `Enterprise PR check`, but not sure if I can fix it too. Could you help me with it please?

**Comment by axelavargas** [comment]
> > Hey @vbeskrovnov, thanks for helping to make Grafana more accessible 👏🏾 , the code looks great and works as expected.
> > ps, I think you might need to merge the latest `main` branch to fix some CI errors :)
> > ps2: I think also you need to fix the `public/app/features/dashboard/containers/DashboardPage.test.tsx`, it was relying on the old behavior :)
> 
> Hey @axelavargas! :) I fixed all tests and failed builds. Still have `Enterprise PR check`, but not sure if I can fix it too. Could you help me with it please?

Hey, @vbeskrovnov, great job fixing the tests! and yes, I can help out 🤗 
With External PR's the CI fails and we need to run a manual check (running enterprise locally and verifying everything is working correctly), I would do that today, and if everything works as expected, I will approve and merge the PR 🤞🏾

**Comment by axelavargas** [comment]
Everything works as expected 🚀 🚀 and enterprise tests are also passing, again thanks for contributing to Grafana!

image

**Comment by vbeskrovnov** [comment]
> Everything works as expected 🚀 🚀 and enterprise tests are also passing, again thanks for contributing to Grafana!

Thank you so much, I really appreciate your help! Will try to do more for grafana :)
