### PR TITLE
Alerting: Fix share URL for Prometheus rules on subpath

### LINKED ISSUE #66709: [Alerting] "Copy link to rule" generates incorrect URLs when Grafana root_url contains a subpath.
## What happened: 
I set up Grafana using a `root_url` that contained a subpath, tried to copy a link to an alert rule and noticed the URL is incorrect. It came out like: `https://<host>/grafana//grafana/alerting/GEM-infra/KubeAPIErrorBudgetBurn/find`

Notice the extra `/grafana` and the double slash `//`

Note that even if you correct the URL manually it won't route, you get a 404 page.

## What you expected to happen: 
It should have come out like: `https://<host>/grafana/alerting/GEM-infra/KubeAPIErrorBudgetBurn/find`

## How to reproduce it (as minimally and precisely as possible):
- Set up a Grafana instance with a `root_url` that contains a subpath such as `https://myhost.grafana.net/grafana/`
- Set `serve_from_sub_path: true` also
- Set up an alert (I used Prometheus alerts from a GEM cluster)
- Open a rule and click "Copy link to rule"
- Note the bad URL

- I have this in a Grafana Labs internal environment reproduced and can link it to whoever needs to see.

## Environment:
- Grafana version: 9.4.7
- Data source type & version: Prometheus/GEM
- OS Grafana is installed on: Linux
- User OS & Browser: Ubuntu, Firefox
- Grafana plugins:
- Others:

cc @gotjosh @johnheywardobrien

### PR DESCRIPTION
**Pull request by gillesdemey**
**What is this feature?**

Fixes incorrect shareURL for Prometheus-based rules when Grafana is hosted on a sub path.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/66709

Tested with the following config

```
[server]
root_url = %(protocol)s://%(domain)s:%(http_port)s/foo/
serve_from_sub_path = true
```

### CODE REVIEW

File: public/app/features/alerting/unified/RedirectToRuleViewer.tsx [hunk 1]
```diff
@@ -22,7 +24,7 @@ function useRuleFindParams() {
   // Relevant issue: https://github.com/remix-run/history/issues/505#issuecomment-453175833
   // It was probably fixed in React-Router v6
   const location = useLocation();
-  const segments = location.pathname?.split('/') ?? []; // ["", "alerting", "{sourceName}", "{name}]
+  const segments = location.pathname?.replace(subUrl, '').split('/') ?? []; // ["", "alerting", "{sourceName}", "{name}]
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/RedirectToRuleViewer.tsx:27]: There's some weird stuff going on here – but the gist is that this doesn't work with subpaths since it assumes a certain path structure.

File: public/app/features/alerting/unified/RedirectToRuleViewer.tsx [hunk 2]
```diff
@@ -76,7 +78,8 @@ export function RedirectToRuleViewer(): JSX.Element | null {
 
   if (rules.length === 1) {
     const [rule] = rules;
-    return <Redirect to={createViewLink(rulesSource, rule, '/alerting/list')} />;
+    const to = createViewLink(rulesSource, rule, '/alerting/list').replace(subUrl, '');
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/RedirectToRuleViewer.tsx:81]: Another weird `react-router` quirk – passing `to={"/foo"}` in an URL that already has a path like `http://localhost:3000/foo/alerting` becomes `http://localhost:3000/foo/foo/alerting` 🤷‍♂️

File: public/app/features/alerting/unified/components/rules/RuleActionsButtons.tsx [hunk 3]
```diff
@@ -59,16 +58,7 @@ export const RuleActionsButtons = ({ rule, rulesSource }: Props) => {
     }
   };
 
-  const buildShareUrl = () => {
-    if (isCloudRulesSource(rulesSource)) {
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rules/RuleActionsButtons.tsx:63]: Moved this to `public/app/features/alerting/unified/utils/url.ts`

File: public/app/features/alerting/unified/utils/url.ts [hunk 4]
```diff
@@ -2,5 +2,24 @@ import { config } from '@grafana/runtime';
 
 export function createUrl(path: string, queryParams?: string[][] | Record<string, string> | string | URLSearchParams) {
   const searchParams = new URLSearchParams(queryParams);
-  return `${config.appSubUrl}${path}?${searchParams.toString()}`;
+  const searchParamsString = searchParams.toString();
+
+  return `${config.appSubUrl}${path}${searchParamsString ? `?${searchParamsString}` : ''}`;
+}
+
+export function createAbsoluteUrl(
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/utils/url.ts:10]: This function creates an absolute URL (includes the host) but also prevents double `/` by 

1. Passing the appSubUrl and appUrl to the URL constructor
2. Setting the `pathname` on the URL object will normalize double `/`

**Review by konrad147 — APPROVED** [review]
LGTM!
