### PR TITLE
Loki: Lower min step to 1ms

### LINKED ISSUE #29210: LogQL metric query [Interval] returns no data when it is expected to do so
**Describe the bug**
I am using Loki 1.6.1 and am having an unexpected behavior. We are building some Grafana Dashboards with Loki data, and one of the Dashboard elements is a chart that shows log entries over time , grouped by level.

To achieve that, I have a very simple query:

`sum(count_over_time({ServiceName=~"DataService"}[$__interval])) by(Level)`

The $__interval is calculated by Grafana by dividing the "Max data points" by the "time range".

I defined a Range which certainly has few Long entries, given my criteria.

What I noticed is that depending of the $__interval calculated value, loki does not return data:

- **100ms**: No data is returned
- **1s**: Data is returned

As far as I can understand, when I have a query like this:
`sum(count_over_time({ServiceName=~"DataService"}[100ms])) by(Level)`
I should get a sum of log entries grouped by level, every 100ms, given my Time range.

`sum(count_over_time({ServiceName=~"DataService"}[1s])) by(Level)`
I should get a sum of log entries grouped by level, every 1s, given my Time range.

On Both cases, I am using exactly the same Time Range, but when I have 1s I get data from loki, but on 100ms I get no data.

**Expected behavior**
On Both cases I expect that some data is returned, as I am sure there is data on Loki that matches the criteria.

Could you guys share some light? I believe that I might have some setting wrongly configured?

My Loki settings:
```yaml
auth_enabled: false

server:
  http_listen_port: 22222
  log_level: 'debug'

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h      
    
storage_config:
  boltdb:
    directory: C:\LokiBackup\Loki_Bkp_2020.08.19__10_11_55\index
  filesystem:
    directory: C:\LokiBackup\Loki_Bkp_2020.08.19__10_11_55\chunks

limits_config:
  enforce_metric_name: false
```

Thanks in advance!

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
The lowest for Loki queries is currently set to 1s. This PR changes this to 100ms. See https://github.com/grafana/grafana/issues/29210 for more details. 

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/29210

### CODE REVIEW

File: public/app/plugins/datasource/loki/datasource.ts [hunk 1]
```diff
@@ -543,7 +544,8 @@ export class LokiDatasource extends DataSourceApi<LokiQuery, LokiOptions> {
     if (interval !== 0 && range / interval > 11000) {
       interval = Math.ceil(range / 11000);
     }
-    return Math.max(interval, 1000);
+    // The min interval is set to 100ms
+    return Math.max(interval, 100);
```
Comment (cyriltovena) [inline public/app/plugins/datasource/loki/datasource.ts:548]: What could go wrong if we set the min to 1ms ?

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/datasource.ts:548]: @davkal @torkelo @kaydelaney can you think of any problems that could happen if we set min to 1ms? I can't think of anything.

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/datasource.ts:548]: @cyriltovena I have found  [this issue that Loki used to have problem with floats in the step](https://github.com/grafana/loki/issues/1305). I wasn't able to reproduce it, but I don't see any linked PR that would be fixing this on Loki side. Could it still be a case?
image
image

Comment (cyriltovena) [reply public/app/plugins/datasource/loki/datasource.ts]: The step is not used for log queries may be it won't work for metric queries ?

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/datasource.ts]: 🙈 true! But I have checked and it works for metric queries as well.
image

image

image

Comment (cyriltovena) [reply public/app/plugins/datasource/loki/datasource.ts]: Sounds good to me.

**Review by zoltanbedi — APPROVED** [review]
lgtm 🐏
