### PR TITLE
Table: Fix sorting for number fields

### LINKED ISSUE #33466: TablePanel: Sort seems to be broken after updating to Grafana v7.5.4 (615c153b3a)
After updating to Grafana v7.5.4 (615c153b3a) with the fix for the sorting issue reported in #32435 sorting broke for us in a TablePanel.

We get unexpected behavior when we're sorting on a column, see the screenshots below:

Screenshot 2021-04-28 102921
Screenshot 2021-04-28 102947

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR adds a different number sorting algorithm to the Table panel for all numeric fields. 
I found that upgrading the react-table component would solve this but decided to skip that upgrade right now, might be a good idea to hold of this PR anyways and upgrade to react-table instead after v8. Let's discuss what's the best approach!

See https://github.com/tannerlinsley/react-table/pull/3235
 
**Which issue(s) this PR fixes**:
Fixes #33466

**Special notes for your reviewer**:

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/utils.ts [hunk 1]
```diff
@@ -208,3 +209,16 @@ export function getFilteredOptions(options: SelectableValue[], filterValues?: Se
...
   return String(a.values[id]).localeCompare(String(b.values[id]), undefined, { sensitivity: 'base' });
 }
+
+const replaceNonNumeric = /[^0-9.]/gi;
+export function sortNumber(rowA: Row<any>, rowB: Row<any>, id: string) {
+  const valueA = rowA.values[id];
+  const valueB = rowB.values[id];
+  const a = isInfinity(valueA) ? valueA : Number(String(valueA).replace(replaceNonNumeric, ''));
+  const b = isInfinity(valueB) ? valueB : Number(String(valueB).replace(replaceNonNumeric, ''));
+  return a === b ? 0 : a > b ? 1 : -1;
```
Comment (torkelo) [inline packages/grafana-ui/src/components/Table/utils.ts:219]: this seems very expensive, for sorting 100 000 rows this is called quite a number of times. A numeric value is rendered to string, then replace non numeric, then parsed back to number. 

Is there a reason to render numeric values to strings and then replace the non numeric elements?  or is that scenario mainly for non numeric values, but cannot see any strings in your tests so not sure that can be it.

Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Table/utils.ts:219]: Code was copied from `react-table` (except for the isInfinity check) and there are strings in my tests.  https://github.com/grafana/grafana/blob/d3f45719824e7c9881b5c6fe8200010cea7603ed/packages/grafana-ui/src/components/Table/utils.test.ts#L429

Question, I was under the impression that this was only called for the cells rendered so I didn't bother about performance as we don't usually render 100 000 rows. But if that is the case, then I need to optimize this.

Comment (torkelo) [reply packages/grafana-ui/src/components/Table/utils.ts:219]: Ah I see, but sorting must be applied to all rows surely? Not sure how it can work by only sorting visible rows :)

Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Table/utils.ts:219]: That makes sense, I'll optimize this.

Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Table/utils.ts]: Refactored, tried to use the existing `anyToNumber` function and `toNumber` from lodash but those didn't pass the previously created tests so I created a local `toNumber` function instead.

**Review by torkelo — APPROVED** [review]
