### PR TITLE
Explore: Fix import of queries between SQL data sources

### LINKED ISSUE #36104: [Grafana 8] Explore doesn't toggle datasource instances correctly
**What happened**:

Have multiple Datasources of the same type (MySQL Prod, Dev, Test, ...).
Go to Explore and enter some SQL to create a table view.
Switch to another Datasource of same type. The old datasource is still used.

**What you expected to happen**:

The new Datasource is used.

**How to reproduce it (as minimally and precisely as possible)**:

See steps above.

**Anything else we need to know?**:

The query URL is not changing correctly:
Initial: `.../explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22ProdDB%22,%7B%22datasource%22:%22ProdDB`
After change: `.../explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22DevDB%22,%7B%22datasource%22:%22ProdDB`

In Grafana 7 or on entering the Explore view again the datasource in the URL is changed correctly.

**Environment**:
- Grafana version: 8.0.0 and 8.0.2
- Data source type & version: MySQL - core version
- OS Grafana is installed on: Ubuntu 20.04.2 LTS
- User OS & Browser: Ubuntu 20.04.2 LTS and Chrome 91.0.4472.114
- Grafana plugins: -
- Others: -

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
Some data sources (e.g. graphite & sql data sources) have `datasource` property (which is optional and non-essential) in their queries. When switching between same type of data sources (e.g. postgres->postgres), we imported full query that included old/previous data source instance in the query object and therefore created miss-match between old and new instance. This PR fixes it.
**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/36104

**Special notes for your reviewer**:
1. Run `make devenv sources=postgres`
2. Create postgres1 and postgres2 data sources (Host: `localhost:5432`, User: `grafana`, Password: `password`, TLS/SSL Mode: `disable`)
3. Open Explore and choose `postgres1` data source. Run query and the switch to `postgres2`.

On master, the urls should be (non-matching postgres instances):
`http://localhost:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22postgres1%22,%7B%22datasource%22:%22postgres2%22,%22format...`

On this branch (matching postgres2 instances):
`http://localhost:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22postgres2%22,%7B%22datasource%22:%22postgres2%22,%22format...`

### CODE REVIEW

File: public/app/features/explore/state/datasource.ts [hunk 1]
```diff
@@ -51,9 +51,8 @@ export function changeDatasource(
       })
     );
 
-    const queries = getState().explore[exploreId]!.queries;
```
Comment (ivanahuckova) [inline public/app/features/explore/state/datasource.ts:54]: We use this only in  `if (options?.importQueries) {...` so I moved it below so we don't create queries variable if not needed.

File: public/app/features/explore/state/query.ts [hunk 2]
```diff
@@ -264,8 +264,8 @@ export const importQueries = (
     let importedQueries = queries;
     // Check if queries can be imported from previously selected datasource
     if (sourceDataSource.meta?.id === targetDataSource.meta?.id) {
-      // Keep same queries if same type of datasource
-      importedQueries = [...queries];
+      // Keep same queries if same type of datasource, but delete datasource query property to prevent miss-match of new and old data source instance
```
Comment (Elfo404) [inline public/app/features/explore/state/query.ts:267]:
```suggestion
      // Keep same queries if same type of datasource, but delete datasource query property to prevent mismatch of new and old data source instance
```

File: public/app/features/explore/state/datasource.ts [hunk 3]
```diff
@@ -51,9 +51,8 @@ export function changeDatasource(
...
-
     if (options?.importQueries) {
+      const queries = getState().explore[exploreId]!.queries;
```
Comment (Elfo404) [inline public/app/features/explore/state/datasource.ts:55]: ❤️

**Review by Elfo404 — APPROVED** [review]
Looks great and works as expected! 🔥
