### PR TITLE
Explore: Improve Explore performance by removing unnecessary re-renders

### LINKED ISSUE #25457: Grafana Logs Explore unusable with 100% CPU, slow rendering (Chrome)
**What happened**:

Searching logs in Grafana is unusable.

Here is a Chrome Performance profile recording: [Profile-20200608T171348.json.zip](https://github.com/grafana/grafana/files/4746895/Profile-20200608T171348.json.zip)

**What you expected to happen**:

It to work and perform in a normal manner.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open Grafana Explore
2. Select Logs datasource
3. Select "Logs" button
4. Type a query, I used `{app="xxx-yyyy"}`
5. Logs load up slowly
6. Page is unusable, slow scrolling, can't move cursor in query field, opening and closing individual logs is super slow.

**Anything else we need to know?**:

My other colleagues don't have this problem. I disabled all my extensions. Updated browser. Restarted browser etc.

**Environment**: 
- Grafana version: `Grafana v7.0.1 (ef5b586d7d)`
- Data source type & version: Logs
- OS Grafana is installed on: k8s
- User OS & Browser: MacOS, Chrome `Version 83.0.4103.61 (Official Build) (64-bit)`
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:

Removes redundant re-renders of:
- **Explore** - We are passing `queryKeys` from store. We were creating a new `queryKeys` array on each key stroke, but  `queryKeys` don't change in `changeQueryAction` as they[ are based on the data source name and index](https://github.com/grafana/grafana/blob/master/public/app/core/utils/explore.ts#L343-L350). None of this changes in `changeQueryAction`.

```
const primaryKey = datasourceInstance && datasourceInstance.name ? datasourceInstance.name : query.key;
return newQueryKeys.concat(`${primaryKey}-${index}`);
```

This also removes re-renders of **QueryRows** as we are passing the same `queryKeys`.

 - **ExploreToolbar** - ExploreToolbar was re-rendering on each keystroke as we are passing `queries` from store which are changing on every key stroke. However, we use these queries only in 1 case - when we are coming to Explore from Dashboard panel and we want to return to dashboard panel and apply those changes. This is done very very rarely and we can remove majority of re-renders but extracting `ReturnToDashboardButton` to its own component that is rendered only when we access Explore from Dashboard panel. 

- **LogsContainer** & **LogRows** & **LogRow** - `logsHighlighterExpressions` array was re-created on each key stroke. In this PR we fix it bt always checking if anything in `logsHighlighterExpressions` array changed.  If not, we return the same array. If yes, we return the new one. 

For more details see [this document](https://docs.google.com/document/d/1CL_0EjvTsmgDf176z5H8f542Qf2d6jvhXJsd5mKa6O4/edit#heading=h.1of22r847lh1).

**Before:**
https://github.com/grafana/grafana/issues/25457#issuecomment-724717353

**Fixed:**
Kapture 2020-12-10 at 15 52 43

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/25457

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/explore/ReturnToDashboardButton.tsx [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+  );
+};
+
+function mapStateToProps(state: StoreState, { exploreId }: { exploreId: ExploreId }) {
+  const explore = state.explore;
+  const { datasourceInstance, queries } = explore[exploreId];
+  return {
+    exploreId,
+    datasourceInstance,
+    queries,
```
Comment (aocenas) [inline public/app/features/explore/ReturnToDashboardButton.tsx:100]: nit: we could probably get also the originalPanelId from redux instead of passing it as prop and then just not render anything here if there isn't any value basically moving this condition `originPanelId && Number.isInteger(originPanelId) && !splitted` inside the component.

File: public/app/features/explore/state/explorePane.ts [hunk 2]
```diff
@@ -258,8 +258,13 @@ export const paneReducer = (state: ExploreItemState = makeExplorePaneState(), ac
...
 
   if (highlightLogsExpressionAction.match(action)) {
-    const { expressions } = action.payload;
-    return { ...state, logsHighlighterExpressions: expressions };
+    const { expressions: newExpressions } = action.payload;
+    const { logsHighlighterExpressions: currentExpressions } = state;
+
+    return {
+      ...state,
+      logsHighlighterExpressions: isEqual(newExpressions, currentExpressions) ? currentExpressions : newExpressions,
```
Comment (aocenas) [inline public/app/features/explore/state/explorePane.ts:266]: Would just add a comment here that this is to prevent rerenders and that it comes from datasource so we cannot control if it returns new array or not.

**Review by aocenas — APPROVED** [review]
Nice work, looks good left some small nitpicks

File: public/app/features/explore/state/explorePane.ts (hunk 2 above)
Comment (ivanahuckova) [reply public/app/features/explore/state/explorePane.ts:267]: Added in https://github.com/grafana/grafana/pull/29752/commits/94eea0f47c81608a34af4874d990223ffde13347

File: public/app/features/explore/ReturnToDashboardButton.tsx (hunk 1 above)
Comment (ivanahuckova) [reply public/app/features/explore/ReturnToDashboardButton.tsx:109]: Moved https://github.com/grafana/grafana/pull/29752/commits/94eea0f47c81608a34af4874d990223ffde13347. I have also added a test for the scenario with split mode.

**Comment by yandingkang** [comment]
hello,I'm using Grafana v8.2.1,but the 'unnecessary re-renders' problem still remains. So which version should I use to solve this problem?

**Comment by yandingkang** [comment]
@ivanahuckova @aocenas Hello,I found another problem.After the result was displayed, when I croll my mouse to see more logs,the whole explore page would be rerendered.Can you find ways to solve this problem?

**Comment by ivanahuckova** [comment]
@yandingkang Can you please create a new issue and provide more information/screenshots on when this happens.

**Comment by yandingkang** [comment]
@ivanahuckova I have created a new issue #41849 .If you need more information,please notice me,thanks.

**Comment by ivanahuckova** [comment]
Awesome, thank you!
