### PR TITLE
heatmap: fix empty tooltip in "Time series bucket" mode

### LINKED ISSUE #9332: [Bug] tooltip is empty on heatmap panel with time series bucket
- What Grafana version are you using?
  - 4.5.1
- What datasource are you using?
  - elasticsearch
- What OS are you running grafana on?
  - official docker container
- What did you do?
  - Move cursor to a heatmap card
- What was the expected result?
  - Tooltip is shown with its content
- What happened instead?
  - Tooltip is empty
  - console error: `TypeError: bucket.bounds is undefined`

It seems the change  https://github.com/grafana/grafana/commit/cb8ecb2d5faec9c1ac8b3f4d8dcc466c65da3fa3#diff-3c623908bd3b58da4e0e63acf4e45cbfL168 does not consider time series bucket, which does not have `buckets.bounds`.

### PR DESCRIPTION
**Pull request by alexanderzobnin**
This PR fixes #9332 by adding `bounds: {bottom: y, top: null}` property to buckets in ES histogram mode converter.

### CODE REVIEW

File: public/app/plugins/panel/heatmap/heatmap_tooltip.ts [hunk 1]
```diff
@@ -83,7 +83,7 @@ export class HeatmapTooltip {
     let xData = data.buckets[xBucketIndex];
     // Search in special 'zero' bucket also
     let yData = _.find(xData.buckets, (bucket, bucketIndex) => {
-      return bucket.bounds.bottom === yBucketIndex || bucketIndex === yBucketIndex;
+      return bucket.bounds.bottom === yBucketIndex || bucketIndex === yBucketIndex.toString();
```
Comment (torkelo) [inline public/app/plugins/panel/heatmap/heatmap_tooltip.ts]: why toString ?

Comment (alexanderzobnin) [reply public/app/plugins/panel/heatmap/heatmap_tooltip.ts]: because `bucketIndex` is a string, but `yBucketIndex` is a Number.

Comment (alexanderzobnin) [reply public/app/plugins/panel/heatmap/heatmap_tooltip.ts]: `bucketIndex` is an object key and when we iterate over it with lodash it returns it as string.
