### PR TITLE
Alerting: Improve heading accessibility

### LINKED ISSUE #67040: ID 261597: [Screen reader - Simon – Alert rules]: Heading hierarchy is not sequential in "Alert rules" tab present under "Alerting" screen.
### **User Experience:** 
Visual Impaired users will be unable to understand and face difficulty in relating the content while navigating the page in heading mode of the screen reader as the heading structure/order is not logical. 
_Note: User credentials should NOT be included in the bug._

**Pre-requisite:**
Turn on Narrator.

### **Repro steps:**

1. Open [https://play.grafana.org/](https://play.grafana.org/) Sign in with valid credentials. "Home" page appears. 
2. Navigate to the left navigation bar and to the "Alerting" button, select it.
3. It gets expanded and navigates to the expanded sub menu items.
4. Select the "Alert Rules" menu items. A new page "Alerting" appears.
5. Navigate the tab " Alert Rules". Verify the issue

**Actual Result:** 
 Issue:  Heading hierarchy is not defined sequentially in **"Alert rules"** tab present under **"Alerting"** screen.

**Observation**: 
 "Grafana" heading and the Contents(headings) such as "Data source: AWS IoT Site-Wise" present under it, is defined under `<H5>` and `<H6>` heading level. Which is defined just after `<H1>` heading level.

**Expected Result:** 
Heading hierarchy should be defined sequentially in in "Alert rules" tab present under "Alerting" screen. "Grafana" heading and the Contents(headings) such as "Data source: AWS IoT Site-Wise" present under it, should be defined under `<H2>` and `<H3>` heading level.

_Note: The same issue exists with the "Mimir/Cortex/Loki" heading section under the same "Alert rules" tab present under the "Alerting" screen._

**Screenshot:**
Screenshot 2023-04-21 at 12 25 27

### **Severity:**
`SEV2`

### **Area:**
`Alert Rules` (GrafanaRules Component)

### PR DESCRIPTION
**Pull request by tskarhed**
**What is this feature?**

Makes the alert group headings H2. In the issue the folder titles are seen as h6, which is no longer the case.

**Which issue(s) does this PR fix?**:

Fixes #67040

Related to multiple points in #73693

**Special notes for your reviewer:**

My understanding of notification policies is that matchers can appear on multiple levels. Is there a way to get the appropriate level?

### CODE REVIEW

File: public/app/features/alerting/unified/components/AlertLabels.tsx [hunk 1]
```diff
@@ -28,7 +28,7 @@ export const AlertLabels = ({ labels, commonLabels = {}, size }: Props) => {
   const hasCommonLabels = commonLabelsCount > 0;
 
   return (
-    <div className={styles.wrapper} role="list" aria-label="Labels">
```
Comment (tskarhed) [inline public/app/features/alerting/unified/components/AlertLabels.tsx:31]: I would still like an `aria-label` here, but the problem is that this is what is being announced as `h2`. I guess here are some things to think about:

- How many labels do we expect?
- Does just reading them out loud provide a good `h2` navigation experience?
- Is there a more generic name for a group than a set of labels?

Comment (tskarhed) [reply public/app/features/alerting/unified/components/AlertLabels.tsx:31]: Also, this should have a testid instead.

File: public/app/features/alerting/unified/components/RuleLocation.tsx [hunk 2]
```diff
@@ -9,13 +9,17 @@ interface Props {
...
+      </Text>
+    );
   }
 
   return (
-    <>
-      {namespace} <Icon name="angle-right" /> {group}
-    </>
+    <Text element="h3" variant="body">
+      {namespace} <Icon name="angle-right" aria-label=">" /> {group}
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/RuleLocation.tsx:21]: Wouldn't this read a bit weird for screen readers? What if we labeled it as "with group" or similar?

File: public/app/features/alerting/unified/components/AlertLabels.tsx (hunk 1 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/components/AlertLabels.tsx:31]: Just wanted to point out these are only announced as `h2` in the groups page :)

The number of labels is technically unbounded, and when grouping is disabled it will pick all labels to group by. Sadly we don't have any other definition other than "set of labels".

Comment (tomratcliffe) [reply public/app/features/alerting/unified/components/AlertLabels.tsx:31]: We should probably allow passing an aria-describedby or similar so we can link to an existing element. E.g. in this case, there's "Labels" nearby, but nothing linking them together

image

----

image

----

I would expect that the list of labels is described by the element that contains "Labels", as otherwise we're duplicating the description?

File: public/app/features/alerting/unified/components/alert-groups/AlertGroup.tsx [hunk 3]
```diff
@@ -35,7 +35,10 @@ export const AlertGroup = ({ alertManagerSourceName, group }: Props) => {
           />
           {Object.keys(group.labels).length ? (
             <Stack direction="row" alignItems="center">
-              <AlertLabels labels={group.labels} size="sm" />
+              <Text element="h2" variant="body">
+                <AlertLabels labels={group.labels} size="sm" />
+              </Text>
```
Comment (tomratcliffe) [inline public/app/features/alerting/unified/components/alert-groups/AlertGroup.tsx:40]: This one feels a little strange to me, having a list of elements inside the H2 that define the heading. 
What do you think about the `Grouped by: ....` being that second level heading?

image

**Comment by tomratcliffe** [comment]
I think also a separate improvement would be to instead have the tags link their key & value together to each other and say that one describes the other, rather than us redefining an `aria-label` with a colon joining the two together (not necessarily something for this PR though)

File: public/app/features/alerting/unified/components/RuleLocation.tsx (hunk 2 above)
Comment (tskarhed) [reply public/app/features/alerting/unified/components/RuleLocation.tsx:21]: At the moment  the `>` isn't being read at all, but without it there is no space, weirdly enough. I like the `with group` idea, although I would probably want to make in an i18n string altoghether.

File: public/app/features/alerting/unified/components/AlertLabels.tsx (hunk 1 above)
Comment (tskarhed) [reply public/app/features/alerting/unified/components/AlertLabels.tsx:31]: > Just wanted to point out these are only announced as `h2` in the groups page :)

I think it only makes sense in that use case, although a more "simple" title for a group would probably be prefferable.

I think the idea with using `describedby` is good

File: public/app/features/alerting/unified/components/alert-groups/AlertGroup.tsx (hunk 3 above)
Comment (tskarhed) [reply public/app/features/alerting/unified/components/alert-groups/AlertGroup.tsx:40]: I agree it feels strange, but it is better than nothing. That could be an idea. At the top level, is it possible to have multiple of those groups? Because then I'd really want something for quick screen reader navigation, even if they'd be `h3` instead. Alternatively give the lists good labels.

**Comment by tskarhed** [comment]
I'm leaving the labels issue out of the PR, as it seems to need more discussion

**Comment by gillesdemey** [comment]
CI failures seem unrelated; but LGTM!

**Review by gillesdemey — APPROVED** [review]
