### PR TITLE
Cloud Monitoring: set missing meta data for distribution type metrics

### LINKED ISSUE #45347: Labels for Google Cloud logs-based metrics (Distribution) cannot be fetched in Grafana 8
**What happened**:
We have two logs-based metrics created in Google Cloud. One is Counter type and the other is Distribution type. User-defined metric labels for the Distribution type cannot be fetched in Grafana 8, but it works well in Grafana 7. There is no problem to fetch metric labels for Counter type metric. 

Please see screenshots from Grafana 7 and 8

image
image

**What you expected to happen**:
User-defined metric labels can be successfully fetched and used in Group By configuration.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Distribution type logs-based metric in Google Cloud with some user-defined labels
2. Setup Google Cloud Monitoring data source
3. Use Explorer trying to fetch the metric labels from newly created metric

**Anything else we need to know?**:
We have two Grafana 7.3.4 and 8.3.6 running in same GKE cluster. Both are using same service account key in Google Cloud Monitoring data source

**Environment**:
- Grafana version: 7.4.4 & 8.3.6
- Data source type & version: Google Cloud Monitoring
- OS Grafana is installed on: GKE Container OS
- User OS & Browser: Microsoft Edge

### PR DESCRIPTION
**Pull request by mtanda**
**What this PR does / why we need it**:
Set metadata for distribution type metrics.

**Which issue(s) this PR fixes**:
Fixes #45347

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/tsdb/cloudmonitoring/time_series_filter.go [hunk 1]
```diff
@@ -220,13 +223,24 @@ func (timeSeriesFilter *cloudMonitoringTimeSeriesFilter) parseResponse(queryRes
...
+			if buckets[i].Meta != nil {
+				buckets[i].Meta.Custom = customFrameMeta
+			} else {
+				buckets[i].SetMeta(&data.FrameMeta{Custom: customFrameMeta})
+			}
 			frames = append(frames, buckets[i])
 		}
+		if len(buckets) == 0 {
+			frames = append(frames, frame)
+		}
```
Comment (mtanda) [inline pkg/tsdb/cloudmonitoring/time_series_filter.go:243]: If request is `HEADERS`, the response doesn't contain `series.Points`, buckets length becomes 0.

File: pkg/tsdb/cloudmonitoring/time_series_filter.go [hunk 2]
```diff
@@ -193,6 +193,9 @@ func (timeSeriesFilter *cloudMonitoringTimeSeriesFilter) parseResponse(queryRes
 							valueField,
 						},
 						RefID: timeSeriesFilter.RefID,
+						Meta: &data.FrameMeta{
+							ExecutedQueryString: executedQueryString,
```
Comment (fridgepoet) [inline pkg/tsdb/cloudmonitoring/time_series_filter.go:197]: Would you add a test or add to an existing test the use of this field `ExecutedQueryString`?

File: pkg/tsdb/cloudmonitoring/time_series_filter.go [hunk 3]
```diff
@@ -220,13 +223,24 @@ func (timeSeriesFilter *cloudMonitoringTimeSeriesFilter) parseResponse(queryRes
 							timeField,
 							valueField,
 						},
+						Meta: &data.FrameMeta{
+							ExecutedQueryString: executedQueryString,
```
Comment (fridgepoet) [inline pkg/tsdb/cloudmonitoring/time_series_filter.go:227]: Same here. Would you add a test or add to an existing test the use of this field ExecutedQueryString?

**Review by fridgepoet — CHANGES_REQUESTED** [review]

File: pkg/tsdb/cloudmonitoring/time_series_filter.go (hunk 2 above)
Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:197]: I add assert for this field.

File: pkg/tsdb/cloudmonitoring/time_series_filter.go (hunk 3 above)
Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:227]: I add assert for this field.

File: pkg/tsdb/cloudmonitoring/time_series_filter.go [hunk 4]
```diff
@@ -220,13 +223,24 @@ func (timeSeriesFilter *cloudMonitoringTimeSeriesFilter) parseResponse(queryRes
...
 		for i := 0; i < len(buckets); i++ {
+			if buckets[i].Meta != nil {
+				buckets[i].Meta.Custom = customFrameMeta
+			} else {
+				buckets[i].SetMeta(&data.FrameMeta{Custom: customFrameMeta})
+			}
 			frames = append(frames, buckets[i])
 		}
+		if len(buckets) == 0 {
+			frames = append(frames, frame)
```
[the remark this answers is not in the document]
Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:238]: I add test for distribution, with points data, and without points data.

File: pkg/tsdb/cloudmonitoring/time_series_filter_test.go [hunk 5]
```diff
@@ -386,6 +386,41 @@ func TestTimeSeriesFilter(t *testing.T) {
 		require.True(t, ok)
 		assert.Equal(t, "114250375703598695", labels["resource.label.instance_id"])
 	})
+
+	t.Run("Parse labels for distribution", func(t *testing.T) {
```
Comment (fridgepoet) [inline pkg/tsdb/cloudmonitoring/time_series_filter_test.go:390]:
```suggestion
t.Run("parseResponse successfully parses metadata for distribution valueType", func(t *testing.T) {
		data, err := loadTestFile("./test-data/3-series-response-distribution-exponential.json")
		require.NoError(t, err)
		assert.Equal(t, 1, len(data.TimeSeries))

		res := &backend.DataResponse{}
		require.NoError(t, (&cloudMonitoringTimeSeriesFilter{}).parseResponse(res, data, "test_query"))

		assert.Equal(t, data2.FrameMeta{
			ExecutedQueryString: "test_query",
			Custom: map[string]interface{}{
				"groupBys":        []string(nil),
				"alignmentPeriod": "",
				"labels": map[string]string{
					"resource.label.project_id": "grafana-prod",
					"resource.type":             "https_lb_rule",
				},
				"perSeriesAligner": "",
			},
		}, *res.Frames[0].Meta)
	})
```

File: pkg/tsdb/cloudmonitoring/time_series_filter.go (hunk 3 above)
Comment (fridgepoet) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:227]: This field is not directly asserted in these tests (or any other tests here :( ). 
This is probably out of scope for this PR, but what kind of data enters this condition on line 208? It would be great to have a test for it, but that is not blocking for this PR.

File: pkg/tsdb/cloudmonitoring/time_series_filter_test.go (hunk 5 above)
Comment (fridgepoet) [reply pkg/tsdb/cloudmonitoring/time_series_filter_test.go:390]: I am also suggesting some spaces between the setup, function call being tested, and assertions to make the reading easier.

File: pkg/tsdb/cloudmonitoring/time_series_filter_test.go [hunk 6]
```diff
@@ -386,6 +386,41 @@ func TestTimeSeriesFilter(t *testing.T) {
...
+		frames := res.Frames
+		assert.Equal(t, "test_query", frames[0].Meta.ExecutedQueryString)
+		custom, ok := frames[0].Meta.Custom.(map[string]interface{})
+		require.True(t, ok)
+		labels, ok := custom["labels"].(map[string]string)
+		require.True(t, ok)
+		assert.Equal(t, "grafana-prod", labels["resource.label.project_id"])
+	})
+
+	t.Run("Parse labels for distribution without points", func(t *testing.T) {
```
Comment (fridgepoet) [inline pkg/tsdb/cloudmonitoring/time_series_filter_test.go:407]: Again, if I understood correctly and the meta data is being added, would you modify this test so it asserts the entire Meta object?

**Review by fridgepoet — CHANGES_REQUESTED** [review]
Thank you very much for the changes! 
Initially I thought this PR was just to add "getting labels" but now I see it's about setting missing metadata (including the label) for "valueType": DISTRIBUTION.

I would suggest modifying each test so that it makes an assertion on the entire Meta object. I put one suggested change on your test below.

File: pkg/tsdb/cloudmonitoring/time_series_filter.go (hunk 3 above)
Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:227]: Ah, sorry. I only added test which using test data 3, but I should add test which using test data 4 too.

Comment (fridgepoet) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:227]: Thanks!

Comment (fridgepoet) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:227]: Hmm, [your test ](https://github.com/grafana/grafana/pull/45500/files#diff-c8d1bd71f56615fc3c3cc3afb8b40b9c1da7805fdf3c97527ae11d8e66f9a4d9R417) with test data 4 doesn't seem to enter that condition still.

Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:227]: I misunderstand something, I didn't read the code carefully...
I'll try to understand the condition...

Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:227]: The code is added by me...
https://github.com/grafana/grafana/commit/6770f2e9401547863048f58d88a52e3e9dbcb975#diff-19faf88f206b68e7fad5a3f06ee85a43d6d67abe25edcd38343396a09157e431R356-R394
I completely forgot it.

And, now I remember the condition.

When `parseFloat()` is failed at here, the next for clause will be executed.

Sample test data.
 https://gist.github.com/mtanda/e7d33c2d7e742b6e4b0fba2239b52608#file-gistfile1-txt-L101

But I didn't remember that why I ignore `parseFloat()` error.
I'm not sure Cloud Monitoring actually return such broken response.

Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:227]: According to doc, the `bucketCounts` is int64 format string.
I think it is safe the for clause, but it might be out of scope of this PR.

Comment (fridgepoet) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:227]: Really sorry, there is a misunderstanding. I'm asking about the next `for` loop, not related to the `ParseFloat` error. Right [here](https://github.com/grafana/grafana/pull/45500/files#diff-be823fa860127465e4c9518eab333dec6bbac9b158c01a59f62ac302cd825269R207) at line 207 of this PR.

File: pkg/tsdb/cloudmonitoring/time_series_filter_test.go [hunk 7]
```diff
@@ -386,6 +388,77 @@ func TestTimeSeriesFilter(t *testing.T) {
...
+			assert.Equal(t, sdkdata.FrameMeta{
+				ExecutedQueryString: "test_query",
+				Custom: map[string]interface{}{
+					"groupBys":        []string(nil),
+					"alignmentPeriod": "",
+					"labels": map[string]string{
+						"resource.label.project_id": "grafana-prod",
+						"resource.type":             "https_lb_rule",
+					},
+					"perSeriesAligner": "",
```
Comment (fridgepoet) [inline pkg/tsdb/cloudmonitoring/time_series_filter_test.go:411]: I was thinking about adding a separate test (out of scope of this PR, I'm *not* at all asking you to add it) which asserts the values which are empty here (`groupBys`, `alignmentPeriod`, `perSeriesAligner`) in order to ensure the rest of the metadata is successfully parsed for distribution valueType.
Do you think that information is realistic/useful here?

File: pkg/tsdb/cloudmonitoring/time_series_filter.go (hunk 3 above)
Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:227]: Yes, I told about the line 227. The code is not executed if `ParseFloat` doesn't return error.
Sorry, my explanation is might be bad...

File: pkg/tsdb/cloudmonitoring/time_series_filter.go (hunk 1 above)
Comment (fridgepoet) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:239]: Sorry, I just realized I didn't understand what you mean here.

**Review by fridgepoet — APPROVED** [review]
Thanks for addressing all the feedback.
I had some other questions about how some of the code works, but it is not blocking for this PR. 
Thanks so much for your contribution.

File: pkg/tsdb/cloudmonitoring/time_series_filter.go (hunk 1 above)
Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:239]: If Grafana set view parameter to `HEADERS` when calling `timeSeries.list`, the response doesn't contain points data.

https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list#query-parameters
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeSeriesView
> Returns the identity of the metric and the time series resource, but not the time series data.

In that case, the actual response becomes like following.
https://github.com/grafana/grafana/pull/45500/files#diff-5cb10f8670d719b1ecda656d9bb95821632636b8d58803a857b6a1cfa5eb5b9e

If no data points, this for loop is not executed.
https://github.com/grafana/grafana/blob/v8.4.1/pkg/tsdb/cloudmonitoring/time_series_filter.go#L164-L226

The buckets still be empty.
https://github.com/grafana/grafana/blob/v8.4.1/pkg/tsdb/cloudmonitoring/time_series_filter.go#L163

But, Query editor needs label data, Grafana should response label data.

File: pkg/tsdb/cloudmonitoring/time_series_filter.go (hunk 3 above)
Comment (fridgepoet) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:227]: Ok I see. No problem, I might have misunderstood. 
Here's what I believe I see:
* `ParseFloat` returns error
* `continue` sends it back to [line 170](https://github.com/grafana/grafana/pull/45500/files#diff-be823fa860127465e4c9518eab333dec6bbac9b158c01a59f62ac302cd825269R170)
* when line 170's `for` loop finishes, the outer `for` [line 164](https://github.com/grafana/grafana/pull/45500/files#diff-be823fa860127465e4c9518eab333dec6bbac9b158c01a59f62ac302cd825269R164) continues to `for` on [line 207](https://github.com/grafana/grafana/pull/45500/files#diff-be823fa860127465e4c9518eab333dec6bbac9b158c01a59f62ac302cd825269R207)
* I don't know how the `if` condition on [line 208](https://github.com/grafana/grafana/pull/45500/files#diff-be823fa860127465e4c9518eab333dec6bbac9b158c01a59f62ac302cd825269R208) is entered

So what I understand is that the line 207 `for` loop is entered no matter if there is an error returned or not from `ParseFloat`, but not sure what kind of data enters the `if` on line 208.

File: pkg/tsdb/cloudmonitoring/time_series_filter_test.go (hunk 7 above)
Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/time_series_filter_test.go:411]: I added check for `groupBys`.

I'm not sure adding `alignmentPeriod` and `perSeriesAligner` is useful.
https://github.com/grafana/grafana/blob/v8.4.1/pkg/tsdb/cloudmonitoring/time_series_filter.go#L147-L148
These are getting from `Params` field, setting these params is deeply depend on implementation.

File: pkg/tsdb/cloudmonitoring/time_series_filter.go (hunk 3 above)
Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:227]: When I implemented this code, I might hit the data, but I don't remember it...
I'll check Cloud Monitoring API response in my environment.

Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:227]: This prometheus exporter expect bucketCounts is integer.
https://github.com/prometheus-community/stackdriver_exporter/blob/v0.12.0/collectors/monitoring_collector.go#L501


Old Cloud Monitoring document says, bucketCounts is int64 format.
https://web.archive.org/web/20170226132705/https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TypedValue
> string (int64 format)
> If bucketOptions is given, then the sum of the values in bucketCounts must equal the value in count. If bucketOptions is not given, no bucketCounts fields may be given.
> Bucket counts are given in order under the numbering scheme described above (the underflow bucket has number 0; the finite buckets, if any, have numbers 1 through N-2; the overflow bucket has number N-1).
> The size of bucketCounts must be no greater than N as defined in bucketOptions.
> Any suffix of trailing zero bucketCount fields may be omitted.

I might have misunderstood, the code seems to be safe to remove.
