### PR TITLE
DashboardScene: Fixing major row repeat issues

### LINKED ISSUE #87536: Dashboard Scene: major bugs in row repeats feature
Reported [here](https://raintank-corp.slack.com/archives/C03MCTKAJA0/p1715238197667819)

- Moving a panel from a repeater row (The source row) results in a bad end state (hard to describe)
- Adding a new panel to the dashboard with repeated rows results in a broken layout and a panel inside the repeated row moving outside it
- http://localhost:3000/d/Repeating-rows-uid/repeating-rows -- gdev-dashboard  
- Also editing a panel inside a repeating row does not edit with the first scoped value (the same issue for the repeated panel), which means the query gets executed as if the variable had all values.

### PR DESCRIPTION
**Pull request by torkelo**
Noticed several bugs with row repeats. 

See issues here: https://ops.grafana-ops.net/d/ddl5wm680ka2of/repeating-row-t?orgId=1&scenes&var-server=A&var-server=B&var-server=C&tab=queries

**Bugs noticed** (all fixed)
* Adding new viz breaks layout / repeated rows
* Moving panel inside repeated row does not work, panel disappears 
* Removing row repeats does not remove the local value scope (so panels do get the full multi value, only the last repeated scoped value)
* Cannot edit panel inside row after removing repeating from row
* Excessive queries, when changing variable value (say removing a value) all panels first issue new queries (even with the row that is getting removed), then repeat happens and new queries are issued (even for panels inside rows where nothing changed).
* When going into dashboard settings (or panel edit) and back triggers new repeat process and new queries 

**Changes / Fixes**
* [x] Adding a visualization completely messes up the layout. This is caused by the row repeat sources positions are never updated when new panels are added (as the sources are only part of the row repeat behavior). Major change in this PR is to move to something more similar to what we do in old architecture. We treat the first row of children as sources. This should simplify other things.  
* [x] Use deterministic repeat clone keys based on local variable value (Will do the same to panel repeats in a future PR) 
* [x] Fixes moving a panel inside a repeated row (did not work, as the row repeater only repeated it's sources and moving a panel inside a repeated row never updated it's sources) 
* [x] Fixed panel edit issue where the local value scope is lost (So the queries get the full multi var value). Now we use the first repeat scope. 
* [x] When setting row repeat we manually activate the row repeat behavior this causes bugs as the behavior is no longer deactivated / re-activated. Needs fix in scenes lib to activate new behaviors. Fixed in https://github.com/grafana/scenes/pull/731
* [x] When cloning sources the sources can now contain data, so no new queries are issued even though the variable scope for the SceneQueryRunner is different. Fixed in https://github.com/grafana/scenes/pull/727
* [x] When changing variable value the notification was also passed to all SceneQueryRunners inside all the repeated panels trigging new queries (even when their local value did not change). Fixed in https://github.com/grafana/scenes/pull/729. This fix required a big work around to how the RowRepeatBehavior get's notified of the top level variable change as the behavior itself is nested under a local variable value after the first repeat process.    
* [x] Skip repeat process when values are the same as last time 

Unsolved bugs that I do not know how to fix right now, I think we can fix later 
* Doing a full page reload of editing a panel inside a repeated row leads to unscoped state (ie full multi value variable value). That is because we go into panel edit before repeat process 
* Doing a full page reload of the "view panel" view on panels inside the first row results in unscoped full multi value value (same reason as above). 

Both those two bugs are because the first row (The template source) all all referenced by their plain ids / keys.  Not really sure how to fix them yet. But given the bugs this PR fixes that are much more critical I think we can wait to fix them separately. 

Maybe in a future PR (this was what I originally started working on this morning) 
* [ ] Reuse row clone instances when possible 

Fixes: #87536

### CODE REVIEW

File: public/app/features/dashboard-scene/panel-edit/PanelEditor.tsx [hunk 1]
```diff
@@ -113,29 +113,30 @@ export class PanelEditor extends SceneObjectBase<PanelEditorState> {
...
+      return;
     }
+
+    this.commitChangesToSource(gridItem);
   }
 
-  private handleRepeatOptionChanges(panelRepeater: DashboardGridItem) {
-    let width = panelRepeater.state.width ?? 1;
-    let height = panelRepeater.state.height;
+  private commitChangesToSource(gridItem: DashboardGridItem) {
```
Comment (torkelo) [inline public/app/features/dashboard-scene/panel-edit/PanelEditor.tsx:124]: this is unrelated change, and is only here for readability. I have numerous times been very confused trying to find where panel changes are committed (thinking this function only handled repeat options)

**Comment by torkelo** [comment]
Updated this branch so that it contains all the scene fixes via this temp PR https://github.com/grafana/scenes/pull/732 , makes it easier to test and verify the fixes

File: public/app/features/dashboard-scene/scene/row-actions/RowActions.tsx [hunk 2]
```diff
@@ -25,31 +18,6 @@ import { RowOptionsButton } from './RowOptionsButton';
 export interface RowActionsState extends SceneObjectState {}
 
 export class RowActions extends SceneObjectBase<RowActionsState> {
```
Comment (dprokop) [inline public/app/features/dashboard-scene/scene/row-actions/RowActions.tsx:20]: An interesting thing i found when testing is that repeated row has row actions available. This means that the repeated row can be repeated further down. It was possible in the previous arch as well, tho it resulted in no effect. I think we should just disable the repeated row's RowActions, otherwise it's confusing and the results are confusing. WDYT?

**Review by dprokop — COMMENTED** [review]
@torkelo - going through the code it looks good. I've left some nits to consider. 

I see all the mentioned problems are solved, apart from this one:

> When going into dashboard settings (or panel edit) and back triggers new repeat process and new queries

Testing, and the queries are still executed when navigating back from panel edit or dashboard settings.

File: public/app/features/dashboard-scene/scene/row-actions/RowActions.tsx (hunk 2 above)
Comment (torkelo) [reply public/app/features/dashboard-scene/scene/row-actions/RowActions.tsx:20]: yes, your rigtht, it should not have any options action even

**Review by axelavargas — COMMENTED** [review]
👋🏾 Hey @torkelo ,  I did a quick test with one of the `gdev-dashboards` (http://localhost:3000/d/0OmtTCtnk/repeating-a-row-with-a-repeating-horizontal-pane) and found an error of repeating panels disappearing after trying to move them 🤔 


https://github.com/grafana/grafana/assets/239999/99644513-11ec-4a4e-ae8f-61160668f39b

**Comment by torkelo** [comment]
@axelavargas think that might need a fix in scenes lib, to block the movement of panel from the source row to a clone row

File: public/app/features/dashboard-scene/scene/RowRepeaterBehavior.ts [hunk 3]
```diff
@@ -28,25 +29,44 @@ interface RowRepeaterBehaviorState extends SceneObjectState {
 export class RowRepeaterBehavior extends SceneObjectBase<RowRepeaterBehaviorState> {
   protected _variableDependency = new VariableDependencyConfig(this, {
     variableNames: [this.state.variableName],
-    onVariableUpdateCompleted: this._onVariableUpdateCompleted.bind(this),
+    onVariableUpdateCompleted: () => {},
```
[the remark this answers is not in the document]
Comment (torkelo) [reply public/app/features/dashboard-scene/scene/RowRepeaterBehavior.ts:32]: if I do not specify i VariableDependencyConfig will do a forceRender() which is the default action if no callback is specified, so this empty callback is just to spot that

**Comment by torkelo** [comment]
@axelavargas think we can fix that later, looks tricky to fix (and not as bad as the current bugs where panels disappear when you move them into the first repeated row). Moving panel out of the first row and into repeated clone is not really a usecase, more a user mistake. We should fix it but could not find an easy way to block/cancel dropping panel into a row clone, maybe @mdvictor can take a look at it he did something similar a month a go

**Comment by torkelo** [comment]
@dprokop 
> Testing, and the queries are still executed when navigating back from panel edit or dashboard settings.

Could not replicate this (with a row with a normal non repeated panel inside it).

**Review by axelavargas — APPROVED** [review]
Hello 😄 , after more testing I did not find anything else.

P.S The added unit test made the process of discovering/understanding `repeats` code easier🏅

**Comment by dprokop** [comment]
> Could not replicate this (with a row with a normal non repeated panel inside it).

@torkelo - i've tested it in a no rows scenario, see the attached dashboard:


<details>
<summary>dashboard.json</summary>
```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 2504,
  "links": [],
  "panels": [
    {
      "datasource": {
        "type": "grafana-testdata-datasource",
        "uid": "gdev-testdata"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 10,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "11.1.0-pre",
      "repeat": "query0",
      "repeatDirection": "h",
      "targets": [
        {
          "refId": "A"
        }
      ],
      "title": "Panel Title $query0",
      "type": "timeseries"
    }
  ],
  "schemaVersion": 39,
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "text": [
            "a",
            "b",
            "c"
          ],
          "value": [
            "a",
            "b",
            "c"
          ]
        },
        "multi": true,
        "name": "query0",
        "options": [
          {
            "selected": true,
            "text": "a",
            "value": "a"
          },
          {
            "selected": true,
            "text": "b",
            "value": "b"
          },
          {
            "selected": true,
            "text": "c",
            "value": "c"
          },
          {
            "selected": false,
            "text": "d",
            "value": "d"
          }
        ],
        "query": "a,b,c,d",
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "browser",
  "title": "Panel repeats scenes",
  "uid": "cdlnzyhsn435sb",
  "version": 2,
  "weekStart": ""
}
```
</details>

File: public/app/features/dashboard-scene/scene/RowRepeaterBehavior.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (dprokop) [reply public/app/features/dashboard-scene/scene/RowRepeaterBehavior.ts:32]: aha, okey!

File: public/app/features/dashboard-scene/scene/row-actions/RowActions.tsx (hunk 2 above)
Comment (dprokop) [reply public/app/features/dashboard-scene/scene/row-actions/RowActions.tsx:20]: @torkelo - i've just pushed a commit that handles that

**Review by dprokop — APPROVED** [review]
