### PR TITLE
Tempo: Fix Node Graph visualization type in dashboard

### LINKED ISSUE #55906: Tempo: Service graph in dashboards does not work as Prometheus returns different dataFrame structure
Right now there is a difference between how metrics are returned from prometheus depending on whether it is in dashboards or explore. In one it returns a wide dataFrame in other it returns a dataFrame per series. The Tempo service graph assumes and transforms only one from those options (don't remember which now).

The tempo code should be able to transform both options into a node graph as both options are generally supported in Grafana.

### PR DESCRIPTION
**Pull request by CrypticSignal**
Closes #55906 and fixes the issue described in the following customer escalation:
[[skatteetaten] Adding node graph to dashboard from explore doesn't work properly](https://github.com/grafana/support-escalations/issues/3893)

### CODE REVIEW

File: public/app/plugins/datasource/tempo/datasource.ts [hunk 1]
```diff
@@ -427,6 +427,12 @@ function serviceMapQuery(request: DataQueryRequest<TempoQuery>, datasourceUid: s
       }
 
       const { nodes, edges } = mapPromMetricsToServiceMap(responses, request.range);
+
+      // No handling of multiple targets assume just one. NodeGraph does not support it anyway, but still should be
+      // fixed at some point.
+      nodes.refId = request.targets[0].refId;
```
Comment (aocenas) [inline public/app/plugins/datasource/tempo/datasource.ts:433]: This is neede for the dashboard flow to figure out which panel to use so now it correctly creates the dashboard with node graph panel.

**Review by aocenas — APPROVED** [review]
