### PR TITLE
Inspect: Handle JSON tab crash when the provided object is too big to stringify.

### LINKED ISSUE #54188: inspector / json tab crashes if the data is too large
when you use the [inspector] / [json] option, and the data is too large, the whole webpage crashes, because an exception is thrown at https://github.com/grafana/grafana/blob/main/public/app/features/inspector/InspectJSONTab.tsx#L212

the exception is "RangeError: Invalid string length"

from searching on the internet, this error-message happens when the object-to-convert-to-json is simply too large.

how to reproduce it with Loki (but this is not loki specific):
1. make devenv sources=loki ... this will load around 300log-lines into loki automatically
2. node devenv/docker/blocks/loki/data/data.js http://localhost:3100 ... this load 300 more
3. repeat [2] until you have 3000 log-lines in Loki (you can adjust the script to sleep less for this to go faster)
4. run the loki query in grafana explore: {source="data"} , set line-limit to 3000
5. when the data is received open the [inspector], and go to [json]
6. the browser will hang for a while, and then there will be the above-mentioned error

### PR DESCRIPTION
**Pull request by TsotosA**
**Which issue(s) this PR fixes**:
As per [this](https://github.com/grafana/grafana/issues/54188#issue-1350020111), inspector crushes if fed with too much data (needs to manual set line limit to something high ex. 3000). This PR is a proposal for addressing this crash by catching the error and handling it.
More specifically it will try to stringify the data and in case of error it will return an empty string and display an error message.

Fixes #54188
**Special notes for your reviewer**:
Don’t really know if that’s an acceptable error handling/ user experience in Grafana, so I am open to suggestions/ feedback.

### CODE REVIEW

File: public/app/features/inspector/InspectJSONTab.tsx [hunk 1]
```diff
@@ -217,5 +217,18 @@ export class InspectJSONTab extends PureComponent<Props, State> {
 }
 
 function getPrettyJSON(obj: any): string {
-  return JSON.stringify(obj, null, 2);
+  let r = '';
+  try {
+    r = JSON.stringify(obj, null, 2);
+  } catch (e) {
```
Comment (dprokop) [inline public/app/features/inspector/InspectJSONTab.tsx:223]: @TsotosA thanks for your contribution. I've tried this approach but gave up on it as it still crashed the browser tab when stringifying the object. And since the crash, I couldn't recover from it obviously.

Is your experience different? (sorry, haven't tested the PR yet).

Comment (TsotosA) [reply public/app/features/inspector/InspectJSONTab.tsx:223]: https://user-images.githubusercontent.com/22328404/193303661-61f10f88-29d8-4f14-8443-a02f1a51e971.mp4

hey @dprokop, i tried both Firefox and Chrome and got the same results, like the one in the video. It takes a few seconds trying to stringify and then recovers with the error message.

File: public/app/features/inspector/InspectJSONTab.tsx [hunk 2]
```diff
@@ -217,5 +217,18 @@ export class InspectJSONTab extends PureComponent<Props, State> {
...
+    if (
+      e instanceof Error &&
+      (e.toString().includes('RangeError') || e.toString().includes('allocation size overflow'))
+    ) {
+      appEvents.emit(AppEvents.alertError, [e.toString(), 'possibly too much data, try setting a lower line limit']);
```
Comment (dprokop) [inline public/app/features/inspector/InspectJSONTab.tsx:228]: Since this code (`getPrettyJSON`) is used not only in Explore's inspect, I don't think we should provide the error message that indicates a resolution to the problem. Can you make it a little bit more generic, I.e. "Cannot display JSON, the object is too big."

**Review by dprokop — CHANGES_REQUESTED** [review]
I tested this PR and actually my browser was able to recover now, weird. Left one comment regarding the error message, but other than that this should be good to merge soon.

**Review by dprokop — APPROVED** [review]
