### PR TITLE
Auth: change the error HTTP status codes

### LINKED ISSUE #18439: Login with user not present in Grafana orgnization returns error 500 instead of 4xx
**What happened**: When a user not present in organization tries to first time login. Grafana throws 500 (internal server error)

**What you expected to happen**:  Grafana should throw 404 not found error.

**How to reproduce it (as minimally and precisely as possible)**: 
Use separate authentication other than Grafana and try to login with user not present in organization

**Anything else we need to know?**:
We are not using Grafana authentication. we are using our own mechanism such google authentication. When that user tries to access Grafana on 5.4.3 Grafana returns 404 error now 
in Grafana 6.2.5 it is returning 500 error.

**Environment**:
- Grafana version: Grafana 6.25
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Amazon Linux
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by markelog**
* Use 407 HTTP status code for incorrect credentials error

* Improve proxy auth logs

* Remove no longer needed TODO comment

Fixes #18439

### CODE REVIEW

File: pkg/middleware/auth_proxy.go [hunk 1]
```diff
@@ -12,13 +14,18 @@ const (
...
+
 func initContextWithAuthProxy(store *remotecache.RemoteCache, ctx *m.ReqContext, orgID int64) bool {
+	username := ctx.Req.Header.Get(header)
 	auth := authproxy.New(&authproxy.Options{
 		Store: store,
 		Ctx:   ctx,
 		OrgID: orgID,
 	})
 
+	logger := log.New("auth proxy")
```
Comment (torkelo) [inline pkg/middleware/auth_proxy.go]: the logger name should not have white space (otherwise the level filters you specify in grafana.ini wont work) you dots instead to signify hierarchy

**Review by torkelo — APPROVED** [review]
Looks good, one comment about the logger name

File: pkg/middleware/auth_proxy.go [hunk 2]
```diff
@@ -31,24 +38,38 @@ func initContextWithAuthProxy(store *remotecache.RemoteCache, ctx *m.ReqContext,
...
 	if err != nil {
-		ctx.Logger.Error("auth proxy: failed to get signed in user", "message", err.Error(), "error", err.DetailsError)
-		ctx.Handle(500, err.Error(), err.DetailsError)
+		logger.Error(
+			"Failed to get signed user",
+			"username", username,
+			"message", err.Error(),
+			"error", err.DetailsError,
+		)
+		ctx.Handle(407, err.Error(), err.DetailsError)
```
Comment (xlson) [inline pkg/middleware/auth_proxy.go]: Shouldn't this still be a `500`? We were just successful in logging in the user in the previous call (`auth.Login()`), seems to me that failure here is very unexpected.

**Review by xlson — APPROVED** [review]
Good work. Minor comments.

File: pkg/middleware/auth_proxy.go (hunk 1 above)
Comment (markelog) [reply pkg/middleware/auth_proxy.go]: Heh, that's why we don't use the spaces :)

File: pkg/middleware/auth_proxy.go (hunk 2 above)
Comment (markelog) [reply pkg/middleware/auth_proxy.go]: If user is removed from grafana db it will not going to be removed from cache until elapsed time for this entry is reached. Foremost `Login` will get the `id` from the cache then just pass it to this branch of code which will never find it.

I believe this is how issue #18439 came to be
