### PR TITLE
Tempo: Fix trace kvlist and array transformations

### LINKED ISSUE #95998: TraceView: Attribute values containing slices are not displayed
### What happened?

When a span attribute value is a slice or a key-value map it shows as an empty string.

### What did you expect to happen?

The value should be displayed in the UI.

### Did this work before?

Yes, it stopped after https://github.com/grafana/grafana/pull/94267. This change seems to be causing this https://github.com/grafana/grafana/pull/94267/files#diff-0fae7cc1f8c2a5f78b973620a1894c4a8e848581cc65e3ac2fc603b6a37fb64fR214

```diff
- 	case pcommon.ValueTypeMap, pcommon.ValueTypeSlice:
-		return attr.AsString()
+	case *commonv11.AnyValue_KvlistValue, *commonv11.AnyValue_ArrayValue:
+		return attr.GetStringValue()
```

### How do we reproduce it?

Create a span running following snippet:

<details><summary>snippet</summary>

```
curl -X POST -H 'Content-Type: application/json' http://localhost:4318/v1/traces -d '
{
  "resourceSpans": [
    {
      "resource": {
        "attributes": [
          {
            "key": "service.name",
            "value": {
              "stringValue": "foo"
            }
          }
        ]
      },
      "scopeSpans": [
        {
          "scope": {
            "name": "test",
            "version": "1.0.0"
          },
          "spans": [
            {
              "traceId": "1234567890ABCDEF1234567890ABCDEF",
              "spanId": "1234567890ABCDEF",
              "name": "I am a span!",
              "startTimeUnixNano": 1730902619532568832,
              "endTimeUnixNano": 1730902619532588832,
              "kind": 2,
              "attributes": [
                {
                  "key": "attr.kvlistValue",
                  "value": {
                    "kvlistValue": {
                      "values": [
                        {
                          "key": "fooKey",
                          "value": { "stringValue": "fooValue" }
                        },
                        {
                          "key": "barKey",
                          "value": { "stringValue": "barValue" }
                        }
                      ]
                    }
                  }
                },
                {
                  "key": "attr.arrayValue",
                  "value": {
                    "arrayValue": {
                      "values": [
                        {
                          "stringValue": "foo"
                        },
                        {
                          "stringValue": "bar"
                        }
                      ]
                    }
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}'
```
</details>

Load the trace in the UI.

Before ... it would show as:

Image

Now it shows as empty strings:

Image

### Is the bug inside a dashboard panel?

TraceView

### Environment (with versions)?

Grafana: instant, fast, steady, slow
OS: any
Browser: any

### Grafana platform?

None

### Datasource(s)?

Tempo

### PR DESCRIPTION
**Pull request by adrapereira**
**What is this feature?**

Fixes the transformation code for array and kvlist attribute values.

**Which issue(s) does this PR fix?**:

Fixes #95998

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: pkg/tsdb/tempo/trace_transform.go [hunk 1]
```diff
@@ -210,11 +210,41 @@ func getAttributeVal(attr *commonv11.AnyValue) any {
...
+func arrayAsString(list *commonv11.ArrayValue) string {
+	vals := make([]any, len(list.GetValues()))
+
+	for i, val := range list.GetValues() {
+		vals[i] = getAttributeVal(val)
+	}
+
+	res, err := json.Marshal(vals)
+	if err != nil {
+		return ""
```
Comment (joey-grafana) [inline pkg/tsdb/tempo/trace_transform.go:231]: Can we log an error? Just so we know there is an issue, or for people to report when the values do not appear in the UI correctly. Something like we do for [tags](https://github.com/grafana/grafana/blob/main/pkg/tsdb/tempo/trace_transform.go#L144).

Also, if this returns an empty string, does that manifest itself in the UI?

**Review by joey-grafana — APPROVED** [review]
Nice work 👍
