### PR TITLE
Alerting: Choose a previous valid AM configuration in case of error

### LINKED ISSUE #54505: Alerting: users should always be able to edit broken alertmanager configuration.
In Grafana Alerting there are some alertmanager configurations that are invalid or unparseable. In many cases the user is able to edit these broken configurations in the user interface until the config is valid.

However, there are still some cases where the configuration API will return a 500 error, or the backend will refuse to start up, because of broken configuration. Grafana should never crash loop or fail to display broken configuration, because fixing the config in those cases requires direct modification of config in the Grafana database. This is much more error-prone than editing in the user interface.

This requires some research and decisions:
* How should the Grafana Alertmanager operate in the face of invalid alertmanager config? Should it use a previous, valid config? Should it enter a "paused" state?
* How can we effectively warn about broken alertmanager config? If it's broken and the application still runs, we should ensure that users know about this so they don't miss critical alerts when config is broken.
* How can we detect bugs in the write path and validation? Right now start-up refusal and bad UI editing state are loud signals of invalid configuration. We need a way to still find bugs that can lead to invalid config being accepted.

**Design doc** https://docs.google.com/document/d/1m7fWyDMsP4AlSSIk-vMQ0NGQwA5yEemS_cPBinZU3Es/edit

### PR DESCRIPTION
**Pull request by VikaCep**
**What is this feature?**

This PR is based on the backend work from https://github.com/grafana/grafana/pull/65728 and displays a dropdown with valid AM configurations when the current configuration is invalid so that the user can then choose one from the list to start their Alertmanager.

**Why do we need this feature?**

Currently if the Alertmanager fails to start, an error message is displayed and the user is basically locked out of Grafana Alerting. A lot of safeguards were added in order to avoid having bad configs saved in the database, but it's impossible to take into account each and every edge case, so this feature works as a sort of "escape hatch".

**How will this work?**

When there's an invalid configuration, the user is shown an error message and prompted to choose from a list of old, valid configurations 

**IMPORTANT NOTE:** All commits until 1a91808dc03e5fc563bf4f2a602868ddd771fe1d have been cherry-picked from https://github.com/grafana/grafana/pull/59516 which was already approved. The referenced PR was closed because the backend branch it was based off was closed and reimplemented in a new one. 
Last 4 commits are new and they address the following changes that are worth to be mentioned: 
- Upon selecting an old configuration, users won't be able to edit it any longer. For this reason the textarea is disabled. Instead, the current configuration will be replaced with the exact content of the selected option in the list.
- A [new endpoint](jacobsonmt/endpoint_activate_previous_config) (`POST /api/alertmanager/grafana/config/history/<id>/_activate`) has been added for this scenario. When the reset button is clicked it gets called passing the old configuration id. 

Fixes https://github.com/grafana/grafana/issues/54505

image

### CODE REVIEW

**Review by soniaAguilarPeiron — APPROVED** [review]
LGTM! Great job! 🎉

File: public/app/features/alerting/unified/components/admin/AlertmanagerConfigSelector.tsx [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+  const validAmConfigsOptions = useMemo(() => {
+    if (!validAmConfigs?.length) {
+      return [];
+    }
+
+    const configs: ValidAmConfigOption[] = validAmConfigs.map((config) => ({
+      label: config.last_applied ? `Config from ${new Date(config.last_applied).toLocaleString()}` : 'Previous config',
+      value: config,
+    }));
+    onChange(configs[0]);
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/admin/AlertmanagerConfigSelector.tsx:53]: What is the reason for this? What if the `configs` array is empty?

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/admin/AlertmanagerConfigSelector.tsx:53]: It would call onChange with `undefined` and this would set `selectedAmConfig` to `undefined`

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/admin/AlertmanagerConfigSelector.tsx:53]: I would say that this is correct as we set `selectedAmConfig` to undefined in case we don't have `validAmConfigs`

File: public/app/features/alerting/unified/components/admin/AlertmanagerConfig.tsx [hunk 2]
```diff
@@ -84,80 +97,43 @@ export default function AlertmanagerConfig(): JSX.Element {
...
+        <>
+          <Alert
+            severity="error"
+            title="Your Alertmanager configuration is incorrect. These are the details of the error:"
+          >
+            {loadingError.message || 'Unknown error.'}
+          </Alert>
+
+          {alertManagerSourceName === GRAFANA_RULES_SOURCE_NAME && (
+            <AlertmanagerConfigSelector
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/admin/AlertmanagerConfig.tsx:109]: nit: can we move the "Reset to selected configuration" button next to the drop-down so the user doesn't have to scroll down?

**Review by gillesdemey — APPROVED** [review]
Just a few nits / suggestions. 

Code LGTM! 🚀

File: public/app/features/alerting/unified/components/admin/AlertmanagerConfigSelector.tsx (hunk 1 above)
Comment (konrad147) [reply public/app/features/alerting/unified/components/admin/AlertmanagerConfigSelector.tsx:53]: > It would call onChange with undefined

That's my concern, as according to `AlertmanagerConfigSelectorProps` the `onChange` doesn't accept undefined
`onChange: (selectedOption: ValidAmConfigOption) => void;`

File: public/app/features/alerting/unified/components/admin/AlertmanagerConfig.tsx (hunk 2 above)
Comment (VikaCep) [reply public/app/features/alerting/unified/components/admin/AlertmanagerConfig.tsx:109]: Done! 
image

File: public/app/features/alerting/unified/components/admin/AlertmanagerConfigSelector.tsx [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+
+  const [resetAlertManagerConfigToOldVersion] = useResetAlertManagerConfigToOldVersionMutation();
+
+  const validAmConfigsOptions = useMemo(() => {
+    if (!validAmConfigs?.length) {
+      return [];
+    }
+
+    const configs: ValidAmConfigOption[] = validAmConfigs.map((config) => ({
+      label: config.last_applied ? `Config from ${new Date(config.last_applied).toLocaleString()}` : 'Previous config',
```
[the remark this answers is not in the document]
Comment (VikaCep) [reply public/app/features/alerting/unified/components/admin/AlertmanagerConfigSelector.tsx]: Good idea, added it.
image

File: public/app/features/alerting/unified/components/admin/AlertmanagerConfigSelector.tsx (hunk 1 above)
Comment (VikaCep) [reply public/app/features/alerting/unified/components/admin/AlertmanagerConfigSelector.tsx:58]: This code wouldn't execute if `configs` is empty because we don't show the dropdown in that case (see https://github.com/grafana/grafana/pull/65746/files#diff-e1b066e38166296feb3c05add1abf23ab0c47dd362b404c91be28f749c067d9aR73), and this is the onChange handler for when the dropdown option is changed.

**Review by konrad147 — APPROVED** [review]
LGTM!
