### PR TITLE
Azure Monitor: Add Resource Picker to Template Variable Query Editor

### LINKED ISSUE #39444: Azure Monitor query editor for Variables doesn't have Service or Resource picker
**What happened**:
Panel query editor has a resource picker:
image

Variable query editor doesn't:
image

"Upon looking network traces, i see dashboard variable queries being to made to random first available workspace in the default sub specified in the datasource . How do i specify what workspace/resource to be queried for dashboard variable queries?"

**What you expected to happen**:
Be able to pick the right resource in the variables.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Azure Monitor data source
2. Try to add panel and variable

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.2 (103f8fa094)
- Data source type & version: Azure Monitor
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by sarahzinger**
**What this PR does / why we need it**:
In 7.5.x, in the Azure Monitor datasource, users could select a default workspace on the auth configuration page. When users then created template variables they could create 2 types of template variables:
- they could invoke helper functions (ex: Subscriptions) we create that would be matched against regex to get certain resources or groups of resources
- or they could write a KQL logs query that would use their default workspace if selected.

In 8.x, when we introduced the Resource Picker for our logs queries, we removed the option to set a default workspace on the configuration page. This had the unfortunate effect of breaking existing template variables for our users that relied on that default workspace. 

In addition to these broken template variables, it's pretty opaque to users how template variables work, or that we even support KQL in the template variable editor. It would be nice if our query editor and template variable editor functioned more similarly, and it would be nice for users to learn more about the helper functions we implemented. 

One potential solution for these challenges is documented in this discussion: https://github.com/grafana/grafana/discussions/39970

This PR is the first step in that solution which adds the LogsQueryEditor (aka resource picker) to Azure Monitor's template variables editor and will auto select a default workspace from the LogsQueryEditor if one is set, which should hopefully repair any existing broken template variables. It also explicitly calls out that there are 2 potentially ways to create a template variable: with our helper functions which I'm calling Grafana Query Functions (feel free to suggest better names! names are very hard) or with the Logs Query Editor.

**Which issue(s) this PR fixes**:

Fixes: #39444

**Special notes for your reviewer**:

~going to make this a draft for now as I'd like to add tests. But I've been working on this PR for a while now and I figure it's better to share what I have and get some feedback.~

### CODE REVIEW

**Review by joshhunt — COMMENTED** [review]
Great stuff!!!!

It looks like it's only looking at the pseudo-functions defined in azure_monitor_datasource.ts, and does not work for those in azure_log_analytics_datasource.ts

I like your idea for centralising all the regexes, so maybe we might need a new module or class for all the template variable stuff?

**Review by sunker — COMMENTED** [review]
Awesome work on this @sarahzinger!

**Review by sunker — APPROVED** [review]
forgot to approve :)

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/VariableEditor/VariableEditor.tsx [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+  };
+  return (
+    <InlineField label="Grafana template variable function">
+      <Input
+        placeholder={'type a grafana template variable function, ex: Subscriptions()'}
+        value={inputVal}
+        onChange={onChange}
+        onBlur={onBlur}
+      />
+    </InlineField>
```
[the remark this answers is not in the document]
Comment (joshhunt) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/VariableEditor/VariableEditor.tsx:56]: Not sure if I quite follow?

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/types/templateVariables.ts [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+  | 'MetricDefinitionsQuery'
+  | 'ResourceNamesQuery'
+  | 'MetricNamespaceQuery'
+  | 'MetricNamesQuery'
+  | 'WorkspacesQuery'
+  | 'UnknownQuery';
+
+interface BaseGrafanaTemplateVariableQuery {
+  rawQuery?: string;
+  kind: GrafanaTemplateVariableQueryType;
```
Comment (joshhunt) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/types/templateVariables.ts:15]: I don't think this `kind` property here should be needed? The specifically typed `kind` on each of the specific query types should be enough :)

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/variables.ts [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+    }
+
+    if (query.kind === 'WorkspacesQuery') {
+      return this.datasource.azureLogAnalyticsDatasource.getWorkspaces(query.subscription);
+    }
+
+    return null;
+  }
+
+  toVariable(metric: string) {
```
Comment (joshhunt) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/variables.ts:105]: minor nit, but what do you think about like `replaceVariable()` or something? `toVariable` doesn't seem correct to me tbh.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/variables.ts [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+        this.toVariable(query.subscription),
+        this.toVariable(query.resourceGroup),
+        this.toVariable(query.metricDefinition),
+        this.toVariable(query.resourceName),
+        this.toVariable(query.metricNamespace)
+      );
+    }
+
+    if (query.kind === 'WorkspacesQuery') {
+      return this.datasource.azureLogAnalyticsDatasource.getWorkspaces(query.subscription);
```
Comment (joshhunt) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/variables.ts:99]: should `query.subscription` be ran through `toVariable`?

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_log_analytics/azure_log_analytics_datasource.ts [hunk 5]
```diff
@@ -218,60 +212,12 @@ export default class AzureLogAnalyticsDatasource extends DataSourceWithBackend<
...
-
-          throw err;
-        });
-    }) as Promise<MetricFindValue[]>;
+  /*
+    In 7.5.x it used to be possible to set a default workspace id in the config on the auth page.
+    This has been deprecated, however is still used by a few legacy template queries.
+  */
+  getDeprecatedDefaultWorkSpace() {
+    return this.instanceSettings.jsonData.logAnalyticsDefaultWorkspace || '';
```
Comment (joshhunt) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_log_analytics/azure_log_analytics_datasource.ts:220]: Ideally we wouldn't have the `|| ''`  at the end of this - it should either return the value, or undefined.

Is that `||`  there because you saw `logAnalyticsDefaultWorkspace` be an empty string anyway? And to just normalizeall empty values to empty string?

Maybe it might be better to check the length, and return undefined if it's empty string?

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/VariableEditor/VariableEditor.tsx [hunk 6]
```diff
@@ -0,0 +1,144 @@
...
+  datasource: DataSource;
+}) => {
+  const [inputVal, setInputVal] = useState('');
+  useEffect(() => {
+    setInputVal(query.grafanaTemplateVariableFn?.rawQuery || '');
+  }, [query.grafanaTemplateVariableFn?.rawQuery]);
+  const onChange = (event: ChangeEvent<HTMLInputElement>) => {
+    setInputVal(event.target.value);
+  };
+  const onBlur = (event: ChangeEvent<HTMLInputElement>) => {
```
Comment (joshhunt) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/VariableEditor/VariableEditor.tsx:32]: Instead of onBlur, i think this should be debounced/throttled in `onChange`.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/grafanaTemplateVariableFns.ts [hunk 7]
```diff
@@ -0,0 +1,263 @@
...
+  const defaultWorkspaceId = datasource.azureLogAnalyticsDatasource.getDeprecatedDefaultWorkSpace();
+  let resource = '';
+  if (defaultWorkspaceId) {
+    const isWorkspaceGUID = isGUIDish(defaultWorkspaceId);
+    if (isWorkspaceGUID) {
+      resource = await datasource.resourcePickerData.getResourceURIFromWorkspace(defaultWorkspaceId);
+    } else {
+      resource = defaultWorkspaceId;
+    }
+  }
```
Comment (joshhunt) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/grafanaTemplateVariableFns.ts:238]: Otherwise, I think this should be the first LA workspace returned from the API.

**Review by joshhunt — APPROVED** [review]
This is excellent and very thorough!!!

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/VariableEditor/VariableEditor.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (sarahzinger) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/VariableEditor/VariableEditor.tsx:56]: @sunker If you're asking do any of these "GrafanaTemplateVariableFunctions" rely on a defaultWorkspace, I think the answer is no, if that helps?

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/types/templateVariables.ts (hunk 2 above)
Comment (sarahzinger) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/types/templateVariables.ts:15]: yeah I kind of went back and forth on keeping that there. The only thing it gives us really is that if you ever want to make another thing that extends this, it'll force you to add a kind property and encourage you to add to the list of types. But Idk probably more confusing than helpful! Will remove.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/variables.ts (hunk 3 above)
Comment (sarahzinger) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/variables.ts:105]: yeah this was just copy/pasta'd but I agree! Will change.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/variables.ts (hunk 4 above)
Comment (sarahzinger) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/variables.ts:99]: It wasn't before I don't think?? but yeah I feel like it should be? Will fix.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/grafanaTemplateVariableFns.ts (hunk 7 above)
Comment (joshhunt) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/grafanaTemplateVariableFns.ts:238]: (to match the previous behaviour)

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/VariableEditor/VariableEditor.tsx (hunk 6 above)
Comment (joshhunt) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/VariableEditor/VariableEditor.tsx:32]: I'll leave it up to you to decide on what's best. I don't think onBlur is the _worst_,  _personally_ I would prefer onChange, but you can have a different opinion that you go with :)

CodeEditor uses onBlur because it lacks an onChange event, fwiw.

I agree - standardising on this seems like it would be helpful!

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/VariableEditor/VariableEditor.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (sunker) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/VariableEditor/VariableEditor.tsx:56]: Yes! Good, that was my only concern.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/grafanaTemplateVariableFns.ts (hunk 7 above)
Comment (sarahzinger) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/grafanaTemplateVariableFns.ts:238]: Ah interesting... because we have to support old queries that relied on the first workspace yeah? ok will take a look at that.
