### PR TITLE
Variables: shows warning when user tries to save erroneous variables

### LINKED ISSUE #98296: Dashboard Variables: Current value saved even when variable throws an error
### What happened?

After a dependent variable loads with values and something is selected, if I change the value of one of the preceding variables that results in an error in one or more of the child variables, the last known good value is still persisted in the dashboard JSON.

Loaded variables with no errors:

Image

Persisted in JSON as expected:

Image

Switch a parent variable to something that will throw an error (in this case it is an access error):

Image

Notice how even with a different subscription, I still get the same value back for "Resource" when it should have been empty, as that resource does not exist in the selected subscription variable. I expect resources to clear and show None, the same way Resource Group does. Additionally, it is not just the selected value that is persistent, but all the options in the dropdown.

Wrong value persisted in the Dashboard JSON:

Image

With this behavior, it leads to innacuracy when using `Save current variable values as dashboard default` as across Saves and Loads it will continue to persist a wrong value for the variable that should have ideally been empty.

### What did you expect to happen?

Whenever there is an error, or no options are returned for a specific "child" variable, the value of those variables should be set to none, rather than the previous last known good value for that variable.

### Did this work before?

Unable to tell, I was able to repro in 10.4.1 as well

### How do we reproduce it?

1. Create any number of chained variables.
2. change the value to one of the parents to something that will force an error in the dependent chained variables
3. Look at dashboard JSON and search for any "current" selected variable value that should have been empty.
4. Save the dashboards with the current selection for variables and notice that because the variable value was not cleared previously, it is now saved for the next time the dashboard is loaded.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 11.2.2
OS: Windows
Browser: Edge

### Grafana platform?

None

### Datasource(s)?

For this example, Azure Monitor template variables were used.

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What is this feature?**

This pull request introduces a warning alert to the Save Dashboard modal, informing users when variable queries have failed and they attempt to save variable values as defaults. It also adds comprehensive test coverage for this new behavior and updates selectors and localization strings accordingly.

**Save Dashboard Modal - Variable Error Warning:**
- Added a warning alert (`variablesWarningAlert`) to the Save Dashboard modal, which appears when a user tries to save variable values as defaults and some variables have errors. This helps prevent saving failed variable states as defaults. [[1]](diffhunk://#diff-d927cb6763bcc03d8ca119eb6fee1d2e2924542b0166510f267ff573024fce7aR264-R280) [[2]](diffhunk://#diff-ab5399a61ea92f4befbbead3ab764ca814cee6de659ac69a85db91dbb8c9ebc8R417) [[3]](diffhunk://#diff-ab5399a61ea92f4befbbead3ab764ca814cee6de659ac69a85db91dbb8c9ebc8R796-R799) [[4]](diffhunk://#diff-b4ecef94b9b063655a5352ec002d531fadaf54fee60c93f50a769cf41a8d4edcR21)
- Updated localization strings to provide clear messaging for the new warning alert.

**Selectors and Test Improvements:**
- Added a new selector for the warning alert to the E2E selectors (`variablesWarningAlert`).
- Refactored and expanded tests for the Save Dashboard modal to cover scenarios where variables are changed or have errors, verifying the warning alert's presence and behavior. [[1]](diffhunk://#diff-03ba1f5f8599ed35d80653c789268e9ee57a090787bacd1cc7f0e16e9966910eL1-R8) [[2]](diffhunk://#diff-03ba1f5f8599ed35d80653c789268e9ee57a090787bacd1cc7f0e16e9966910eR31-R42) [[3]](diffhunk://#diff-03ba1f5f8599ed35d80653c789268e9ee57a090787bacd1cc7f0e16e9966910eL53-R118) [[4]](diffhunk://#diff-03ba1f5f8599ed35d80653c789268e9ee57a090787bacd1cc7f0e16e9966910eL83-R137) [[5]](diffhunk://#diff-03ba1f5f8599ed35d80653c789268e9ee57a090787bacd1cc7f0e16e9966910eL97-R151) [[6]](diffhunk://#diff-03ba1f5f8599ed35d80653c789268e9ee57a090787bacd1cc7f0e16e9966910eR331-R339)

**UI and State Management:**
- Updated the Save Dashboard form to conditionally render the warning alert based on the new `showVariablesWarning` state, which is set by checking for variable errors in the dashboard scene. [[1]](diffhunk://#diff-d927cb6763bcc03d8ca119eb6fee1d2e2924542b0166510f267ff573024fce7aL206-R211) [[2]](diffhunk://#diff-d927cb6763bcc03d8ca119eb6fee1d2e2924542b0166510f267ff573024fce7aR249)

https://github.com/user-attachments/assets/0d452237-13e7-418d-bd7b-368b0f317a85

**Why do we need this feature?**

These changes improve user awareness when saving dashboards with problematic variable states, reducing the risk of persisting invalid defaults.

**Who is this feature for?**

Grafana users

**Which issue(s) does this PR fix?**:

Fixes #98296

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Looks great!

File: public/app/features/dashboard-scene/scene/DashboardScene.tsx [hunk 1]
```diff
@@ -828,5 +831,11 @@ export class DashboardVariableDependency implements SceneVariableDependencyConfi
         this._dashboard.setState({ panelsPerRow: Number.isInteger(perRow) ? perRow : undefined });
       }
     }
+
+    const variableErrors = Boolean(
+      this._dashboard.state.$variables?.state.variables.find((v) => Boolean(v.state.error))
+    );
+
+    this._dashboard.setState({ variableErrors });
```
Comment (torkelo) [inline public/app/features/dashboard-scene/scene/DashboardScene.tsx]: Missed this, can you move this to the SaveDashboardDrawerState ? 

Or I dont think this needs to be a state property, just a function hasVariableWithErrors

File: public/app/features/dashboard-scene/scene/DashboardScene.tsx [hunk 2]
```diff
@@ -149,6 +149,8 @@ export interface DashboardSceneState extends SceneObjectState {
   editPane: DashboardEditPane;
   /** Manages dragging/dropping of layout items */
   layoutOrchestrator?: DashboardLayoutOrchestrator;
+  /** Whether the dashboard has one or more variable errors */
+  variableErrors?: boolean;
```
Comment (torkelo) [inline public/app/features/dashboard-scene/scene/DashboardScene.tsx]: don think this is needed (and feels wrong to have here)

File: public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx [hunk 3]
```diff
@@ -40,6 +40,7 @@ export const SaveDashboardForm = ({
 }: SaveProps) => {
   const hasTimeChanged = useMemo(() => dashboard.hasTimeChanged(), [dashboard]);
   const hasVariableChanged = useMemo(() => dashboard.hasVariablesChanged(), [dashboard]);
+  const showVariablesWarning = useMemo(() => dashboard.hasVariableErrors(), [dashboard]);
```
Comment (torkelo) [inline public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx]: given this, why is there   variableErrors?: boolean; added to DashboardSceneState ?

File: public/app/features/dashboard-scene/scene/DashboardScene.tsx (hunk 1 above)
Comment (hugohaggmark) [reply public/app/features/dashboard-scene/scene/DashboardScene.tsx]: Great suggestion, fixed 👍

File: public/app/features/dashboard-scene/scene/DashboardScene.tsx (hunk 2 above)
Comment (hugohaggmark) [reply public/app/features/dashboard-scene/scene/DashboardScene.tsx]: Fixed 👍

File: public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx (hunk 3 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx]: Gotcha I've removed the implementation in the "non-scenes" parts 👍
