### PR TITLE
Scenes: Be able to hide dashboard controls in Kiosk mode

### LINKED ISSUE #88906: Scenes: Dashboard toolbar doesn't hide in kiosk mode
**Problem**
When enabling `kiosk=true` for a dashboard, the toolbar containing the variables, time range, links, etc doesn't hide. In the old architecture, it does. 

**Expected behavior**
Hide the toolbar when kiosk mode is enabled

**Screenshots**
|Scenes disabled|Scenes enabled|
|-|-|
Captura de pantalla 2024-06-07 a las 13 01 02|Captura de pantalla 2024-06-07 a las 13 00 41

**Steps to reproduce**
1. Open any dashboard
2. Add to the URL `&kiosk=true`. You see the controls still available
3. Add to the URL `&scenes=false`. You will see the controls are hidden because we disabled Scenes.

### PR DESCRIPTION
**Pull request by ivanortegaalba**
Fixes #88906

TODO: 

- [x] Add more tests
- [x] Confirm design with @Ijin08 

**Solution**
Now, this is the status for old architecture:

- Kiosk:
    - No Nav
    - No time picker
    - No variables
- TV Mode:
    - Nav
    - Time picker
    - No variables

For Scenes, we want to change it and display controls by default:
- Kiosk:
    - No Nav
    - Yes time picker (it hides with &_dash.hideTimePicker=true)
    - Yes variables (it hides with &_dash.hideVariables=true)
    - Yes links (it hides with &_dash.hideLinks=true)
- TV Mode:
    - Nav
    - Yes time picker (it hides with &_dash.hideTimePicker=true)
    - Yes variables (it hides with &_dash.hideVariables=true)
    - Yes links (it hides with &_dash.hideLinks=true)

This PR also adds the possibility to configure the visibility of controls when starting a playlist:
Captura de pantalla 2024-06-14 a las 0 26 53

### CODE REVIEW

**Review by Sergej-Vlasov — DISMISSED** [review]
Works as expected 👍 💯 !

**1 minor bug:**
- when leaving `Kiosk` mode variables and time range do not reappear

My opinions on your questions:
1. Leave with time range visible in `Tv` mode. Kiosk mode hides it if needed.
2. Yes add margin (I think you already did and it looks great)

File: public/app/features/playlist/StartModal.tsx [hunk 1]
```diff
@@ -38,13 +52,37 @@ export const StartModal = ({ playlist, onDismiss }: Props) => {
...
           <RadioButtonGroup value={mode} options={modes} onChange={setMode} />
         </Field>
-        <Checkbox
-          label="Autofit"
-          description="Panel heights will be adjusted to fit screen size"
-          name="autofix"
-          value={autoFit}
-          onChange={(e) => setAutofit(e.currentTarget.checked)}
-        />
+        <Field label="Display dashboard controls" description="Customize dashboard elements visibility">
```
Comment (torkelo) [inline public/app/features/playlist/StartModal.tsx:55]: Only show these if scenes dashboards feature toggle is enabled

File: public/app/features/dashboard-scene/scene/DashboardSceneRenderer.tsx [hunk 2]
```diff
@@ -24,6 +24,7 @@ export function DashboardSceneRenderer({ model }: SceneComponentProps<DashboardS
   const bodyToRender = model.getBodyToRender();
   const navModel = getNavModel(navIndex, 'dashboards/browse');
   const isHomePage = !meta.url && !meta.slug && !meta.isNew && !meta.isSnapshot;
+  const isDashboardControlsHidden = !controls?.hasControls();
```
Comment (torkelo) [inline public/app/features/dashboard-scene/scene/DashboardSceneRenderer.tsx:27]: If you rename this to `hasControls` then there is no need to have three `!` inverts here (and in the markup) as everwhere isDashboardControlsHidden is used it's used with an inverter :)

File: public/app/features/dashboard-scene/scene/DashboardControlsUrlSync.tsx [hunk 3]
```diff
@@ -0,0 +1,39 @@
+import { SceneObjectUrlSyncHandler, SceneObjectUrlValues } from '@grafana/scenes';
+
+import { DashboardControls } from './DashboardControls';
+
+export class DashboardControlsUrlSync implements SceneObjectUrlSyncHandler {
```
Comment (torkelo) [inline public/app/features/dashboard-scene/scene/DashboardControlsUrlSync.tsx:5]: any reason for using a special class here and not just SceneObjectUrlSyncConfig. ?

**Review by torkelo — APPROVED** [review]
I think this looks good, maybe a e2e test for some of it or a react render test on DashboardScenePage level ? (something that can capture the logic full URL => what should be visible logic)

File: public/app/features/dashboard-scene/scene/DashboardControlsUrlSync.tsx (hunk 3 above)
Comment (ivanortegaalba) [reply public/app/features/dashboard-scene/scene/DashboardControlsUrlSync.tsx:5]: Removed! I thought it was cleaner, it is not needed :)

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. Just letting you know I'm updating your PR's milestone to [11.2.x](https://github.com/grafana/grafana/milestone/529). If you need to see your changes in a previous version, please consider adding a backport label.

Thank you!
