### PR TITLE
Alerting: Fix unique violation when updating rule group with title chains/cycles

### LINKED ISSUE #66158: Alerting: Rule diff logic does not take all renames within the same request into account
**What happened**:

There is logic to diff a rule group in requests:
https://github.com/grafana/grafana/blob/8600a8ce2e44f10a67ad98252184901b63dbe135/pkg/services/ngalert/store/deltas.go#L41

This logic also tries to enforce uniqueness of names within a group. However, it does not correctly enforce this, and over-rejects requests.

This is because it strictly processes changes in-order. It does not consider if changes later in the same request actually fix the uniqueness constraint.

There are a lot of ways to manifest this, but the clearest example is swapping names of rules in the same request. Say that rule `A` is renamed to `B`, and `B` is renamed to `A` in the same request. Once the A->B rename is processed by the differ, it will immediately reject the entire request with `rule title under the same organisation and folder should be unique`, around the title `B`. This is because it now sees two rules with name `B` - it has not yet processed the second rule's rename, but it exits out with an error too early.

The same happens with creates - since creates are always processed before updates, if we create a rule A and at the same time rename an existing rule A to B, it fails around a name conflict on A - even though in the resulting group, there is no conflict.

**What you expected to happen**:

I expected internally consistent requests to be processed successfully.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a rule group with two rules.
  a. I did this over the provisioning API, but this also works over the main API as it uses the same diff logic.
2. Swap their names but preserve their UIDs in a single request.
3. 400. "rule title under the same organisation and folder should be unique" even though this is not true.

Another way to do it:

1. Create a rule group with one rule
2. Change its UID (or leave UID blank, asking server to regenerate)
3. 400. "rule title under the same organisation and folder should be unique" really doesn't make sense now, there is only one rule in the group.

**Anything else we need to know?**:

**Environment**:
- Grafana version: main

### PR DESCRIPTION
**Pull request by JacobsonMT**
Fixes: #66158

The uniqueness constraint for titles within an org+folder is enforced on every update within a transaction instead of on commit (deferred constraint). This means that there could be a set of updates that will throw a unique constraint violation in an intermediate step even though the final state is valid. For example, a chain of updates RuleA -> RuleB -> RuleC could fail if not executed in the correct order, or a swap of titles RuleA <-> RuleB cannot be executed in any order without violating the constraint.

The exact solution to this is complex and requires determining directed paths and cycles in the update graph, adding in temporary updates to break cycles, and then executing the updates in reverse topological order (see first commit in PR if curious).

This is not implemented here.

Instead, we choose a simpler solution that works in all cases but might perform more updates than necessary. This simpler solution makes a determination of whether an intermediate collision could occur and if so, adds a temporary title on all updated rules to break any cycles and remove the need for specific ordering.

In addition, we make sure diffs are executed in the following order: DELETES, UPDATES, INSERTS.

The alternatives to this added complexity are:

1) On update delete entire rule group and reinsert. This is simple and straightforward, but requires removing our optimistic locking strategy for pessimistic.
2) Remove the title uniqueness constraint from the table. Then we can either enforce in application code or not enforce it at all. Not enforcing it could cause users to mistakenly group notifications for alerts of the same name.

Note: Deferred constraints are not really a viable option here as SQLite and MySQL do not support them at the moment.

### CODE REVIEW

File: pkg/services/ngalert/store/alert_rule.go [hunk 1]
```diff
@@ -231,6 +238,73 @@ func (st DBstore) UpdateAlertRules(ctx context.Context, rules []ngmodels.UpdateR
...
+	}
+
+	for _, update := range updates {
+		r := update.Existing
+		u := uuid.New().String()
+		uniqueTempTitle := r.Title + u
+		if len(uniqueTempTitle) > AlertRuleMaxTitleLength {
+			uniqueTempTitle = r.Title[:AlertRuleMaxTitleLength-len(u)] + uuid.New().String()
+		}
+		if updated, err := sess.ID(r.ID).Cols("title").Update(&ngmodels.AlertRule{Title: uniqueTempTitle, Version: r.Version}); err != nil || updated == 0 {
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/store/alert_rule.go:269]: I wonder if we can simplify it even more and have an intermediate update of the rule's title to it's UID instead of `Title + uid`, i.e. rule.Title = rule.UID. So, it will guarantee uniqueness (because UID has much stronger constraints) and you will not need to take care of the length limits.

File: pkg/services/ngalert/store/alert_rule.go [hunk 2]
```diff
@@ -231,6 +238,73 @@ func (st DBstore) UpdateAlertRules(ctx context.Context, rules []ngmodels.UpdateR
...
+	// specific ordering.
+
+	// This short circuit detects when no intermediate unique constraint violations are possible.
+	// It may return false positives, but never false negatives.
+	if !newTitlesOverlapExisting(updates) {
+		// No possibility of an intermediate unique constraint violation.
+		return nil
+	}
+
+	for _, update := range updates {
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/store/alert_rule.go:262]: Also, we can ignore updates that do not change the Title, right?

File: pkg/services/ngalert/store/alert_rule.go (hunk 1 above)
Comment (JacobsonMT) [reply pkg/services/ngalert/store/alert_rule.go:269]: For UIDs generated by the system, this sounds good and is unlikely to cause any trouble. However, UIDs can also be defined through provisioning / API. If a user creates a human readable UID that happens to overlap with a title change, this would cause a very strange and hard to understand error.

I could simply set the temporary title to just a new random uid, but figured to code defensively here in case it somehow gets persisted by a future bug. They will at least be able to somewhat identify it by having the old title in there.

File: pkg/services/ngalert/store/alert_rule.go (hunk 2 above)
Comment (JacobsonMT) [reply pkg/services/ngalert/store/alert_rule.go:262]: Correct, nice catch. I'll do some refactoring to collect the title updates early.

File: pkg/services/ngalert/store/alert_rule.go (hunk 1 above)
Comment (yuri-tceretian) [reply pkg/services/ngalert/store/alert_rule.go:278]: ah, that makes sense!

**Review by yuri-tceretian — APPROVED** [review]
LGTM. It would be great to have two things:
1. Log in the case when the logic detected that intermediate updates are needed.
2. API Integration tests that creates several rules in a group and then swap titles of at least two rules.

**Review by grobinson-grafana — APPROVED** [review]

**Comment by JacobsonMT** [comment]
Fixing merge conflicts and will merge
