### PR TITLE
Explore: Fix height on horizontal drawer and query inspector

### LINKED ISSUE #47830: Explore: Query inspector does not scroll as expected
**What happened**:
Improper scroll styling in inspector tray prevents seeing response content

**What you expected to happen**:
The ability to scroll to see tray content.

**How to reproduce it (as minimally and precisely as possible)**:
1. Open Explore
2. Set up something to run a query or run a query
3. Open Inspector and select the query tab
4. Hit the refresh button if needed
5. Note you cannot scroll to see the response

**Anything else we need to know?**:
There is a workaround to expand/collapse all to show all content.

**Environment**:
- Grafana version:  v 9 pre (main)

### PR DESCRIPTION
**Pull request by gelicia**
**What this PR does / why we need it**:
This fixes an issue where the height for the tab container is 100%, which means content falls off the bottom of the page. This is normally accommodated in other ways, but the JSON object in query inspector ends up going past the bottom of the window while not being not tall enough to trigger its own scrolling.

This is fixed by adding the tab height and default horizontal drawer height to the template so those heights can be called to derive proper container heights. TabbedContainer is currently only used by horizontal drawers but that is not guaranteed to always be the case, so it is a passed in variable.

I also added `overflow: scroll` to the inspector content div so we will always be able to get the content. 

Note: RichHistory is passed in a height because it is a class component and cannot use `useTheme2`.

**Which issue(s) this PR fixes**:

Fixes #47830

### CODE REVIEW

File: packages/grafana-ui/src/components/TabbedContainer/TabbedContainer.tsx [hunk 1]
```diff
@@ -27,7 +27,7 @@ const getStyles = stylesFactory((theme: GrafanaTheme2) => {
     tabContent: css`
       padding: ${theme.spacing(2)};
       background-color: ${theme.colors.background.primary};
-      height: 100%;
+      height: calc(100% - ${theme.components.menuTabs.height}px);
```
Comment (gelicia) [inline packages/grafana-ui/src/components/TabbedContainer/TabbedContainer.tsx:30]: Thanks so much @Elfo404 for this excellent tip!

**Review by Elfo404 — APPROVED** [review]
Nice one! 🚀

File: packages/grafana-ui/src/components/TabbedContainer/TabbedContainer.tsx (hunk 1 above)
Comment (torkelo) [reply packages/grafana-ui/src/components/TabbedContainer/TabbedContainer.tsx:30]: never use calc :( flex can handle this much better
