### PR TITLE
Graph: Workaround for DashboardQueryRunner race condition

### LINKED ISSUE #36247: Graph: Time range in x-axis does not update in Graphs
**What happened**:
Graph time range is not updated when I change time range from time picker.

**What you expected to happen**:
Graph time range should be updated.

**How to reproduce it (as minimally and precisely as possible)**:
Reproducible Scripted dashboard.
```
return {
        "panels": [
                {
                        "id": 1,
                        "type": "graph",
                        "title": "panel title",
                        "gridPos": {
                                "h": 8,
                                "w": 24,
                                "x": 0,
                                "y": 1
                        },
                        "datasource": "Prometheus",
                        "lines": true,
                        "linewidth": 1,
                        "targets": [
                                {
                                        "expr": "count(up)",
                                        "refId": "A"
                                }
                        ]
                }
        ],
        "title": "dashboard title",
        "uid": null,
        "editable": true,
        "time": {
                "from": "now-6h",
                "to": "now"
        },
        "style": "dark",
        "schemaVersion": 30,
        "version": 0
};
```

**Anything else we need to know?**:

**Environment**:
- Grafana version:
  - Grafana v8.0.3
- Data source type & version:
  - Prometheus
- OS Grafana is installed on:
  - Linux
- User OS & Browser:
  - Windows & Firefox
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #36247

This is a temporary work around for a race condition with DashboardQueryRunner.

Current process that causes this bug

* Add one old graph panel on an empty dashboard (default time:  range 6h)
* Change time range via time picker (5m)
* RefreshEvent emitted
* DashboardQueryRunner issues query
* MetricsPanelCtrl starts query process, fetches DataSourceAPI instance
* MetricsPanelCtrl calls updateTimeRange and this sets this.range (5m)
* DashboardQueryRunner complete the dashboard annotation query and emits a new result
* mergePanelAndDashData merges new annotation result (empty) with previous query result and emits result, this causes a panelDataObserver.next call in MetricsPanelCtrl which gets the new data result, updates time range (this.range to 6h) from result of the old query and renders graph with old data again. [line](https://github.com/grafana/grafana/blob/main/public/app/features/panel/metrics_panel_ctrl.ts#L159)
* MetricsPanelCtrl calls issueQueries which now uses a this.range (6h) that is for the old query result (so not the new time range)

This PR does not fix the underlying problem that if the annotation query is fast it will complete before any new panel queries have been issued. So we will have two data emits for every refresh, one before any panel queries have been issued and with new annotations/alert states and old data and time range.

If we could unsubscribe to the annotation / dashboard query runner after it is completed maybe that could fix the problem? (so that it does not fire for the previous query/observable).

### CODE REVIEW

**Comment by hugohaggmark** [comment]
I'm trying to repro the original issue on main branch but I'm struggling to reproduce this before testing out this PR. Will try to use slow_proxy and see if the helps. Any more tips?

File: public/app/features/panel/metrics_panel_ctrl.ts [hunk 1]
```diff
@@ -173,7 +173,7 @@ class MetricsPanelCtrl extends PanelCtrl {
 
   updateTimeRange(datasource?: DataSourceApi) {
     this.datasource = datasource || this.datasource;
-    this.range = this.timeSrv.timeRange();
+    this.range = cloneDeep(this.timeSrv.timeRange());
```
Comment (torkelo) [inline public/app/features/panel/metrics_panel_ctrl.ts:176]: note, this clone is not needed it was a test to see if there was some mutable thing causing this but it was not

**Review by hugohaggmark — APPROVED** [review]
Looks good and works as expected 🎉  I'll try to figure out a solution to the root cause.
