### PR TITLE
Alerting: Improve comments on alert table migration immutability

### LINKED ISSUE #60196: Alerting: Migrations run in an unexpected order
Our database migrations are not running in the order that they were written. I'm not aware of any existing issues around this, but I'm shocked this hasn't caused anything yet.

This is because of how the migration code is structured. Migrations are broken up by table, so there is not one linear history.

A contrived example of how it currently looks:
```
AddMigrations() {
    AddTableXMigrations()
    AddTableYMigrations()
}

AddTableXMigrations() {
    MigrationOne()
    MigrationThree()
}

AddTableYMigrations() {
    MigrationTwo()
}
```
In this example, the migrations run in this order: 1->3->2. This is the wrong order.

We've largely been safe so far by pure chance, as most migrations are very simplistic and are scoped to only a single table. The instant we add a migration which touches multiple tables (i.e. needs to run in a specific point in time relative to two tables, not one), this becomes extremely bug-prone and leads to upgrade issues as table schemas drift.

In the example above, assume a migration touches both tables X and Y. **There is no bug-free place to put this migration.**
- If it's put in `AddMigrations()`, it breaks unless it's defined at the very end, after all table-specific migrations. Then, any future migration added to `AddTableXMigrations` or `AddTableYMigrations` then gets incorrectly injected _before_ our new migration, breaking it if it changes the schema.
- If it's put in `AddTableXMigrations()`, table Y won't exist yet, and the migration instantly fails.
- If it's put in `AddTableYMigrations()`, a future migration defined on table X again ends up again incorrectly running too early, breaking the schema out from underneath us.

Solving this is simple. We instead define all migrations in a single, append-only, linear history, regardless of table:

```
AddMigrations() {
    MigrationOne()
    MigrationTwo()
    MigrationThree()
}
```

### PR DESCRIPTION
**Pull request by JacobsonMT**
The current structure of alerting table migrations is presented in a way that encourages modifying existing migrations when changes to alerting table schema occur. This is not a good thing, so efforts are made in the PR to improve comments and messaging to better indicate that new changes should be appended as new migrations. See https://github.com/grafana/grafana/issues/60196 for more in depth discussion.

**Which issue(s) does this PR fix?**:

Fixes #60196

### CODE REVIEW

File: pkg/services/sqlstore/migrations/ualert/tables.go [hunk 1]
```diff
@@ -12,34 +14,45 @@ const DefaultFieldMaxLength = 190
...
 const UIDMaxLength = 40
 
-// AddMigration defines database migrations.
+// AddTablesMigrations defines database migrations that affect Grafana Alerting tables.
 func AddTablesMigrations(mg *migrator.Migrator) {
-	AddAlertDefinitionMigrations(mg, 60)
-	AddAlertDefinitionVersionMigrations(mg)
+	// Migrations are meant to be immutable, any modifications to table structure
+	// should come in the form of a new migration appended to the end of AddTablesMigrations
+	// instead of modifying an existing one. This ensure that tables are modified in a consistent and correct order.
```
Comment (alexweav) [inline pkg/services/sqlstore/migrations/ualert/tables.go:21]: :tada: Nice!

File: pkg/services/sqlstore/migrations/ualert/tables.go [hunk 2]
```diff
@@ -12,34 +14,45 @@ const DefaultFieldMaxLength = 190
...
+	historicalTableMigrations(mg)
+
+	extractAlertmanagerConfigurationHistoryMigration(mg)
```
Comment (alexweav) [inline pkg/services/sqlstore/migrations/ualert/tables.go:24]: Thoughts on just combining this func with `historicalTablesMigrations` and having one big non-frozen func containing everything that we append to?

Alternatively, this one could go in `historicalTablesMigrations` - This one is kind of paired logically with `addAlertmanagerConfigHistoryMigrations(mg)` so IMO they should live next to each other, wherever they go.

File: pkg/services/sqlstore/migrations/ualert/tables.go [hunk 3]
```diff
@@ -433,3 +455,81 @@ func AddAlertImageMigrations(mg *migrator.Migrator) {
 		Postgres("ALTER TABLE alert_image ALTER COLUMN url TYPE VARCHAR(2048);").
 		Mysql("ALTER TABLE alert_image MODIFY url VARCHAR(2048) NOT NULL;"))
 }
+
+func extractAlertmanagerConfigurationHistoryMigration(mg *migrator.Migrator) {
```
Comment (alexweav) [inline pkg/services/sqlstore/migrations/ualert/tables.go:459]: Yeah, good idea, `ualert.go` was not the best place.

Not for this PR, but I'm just curious - WDYT about eventually having one file for each non-trivial migration? The legacy->UA migration could be its own subpackage, etc. Or is that overkill?

**Review by alexweav — APPROVED** [review]
Good change, I had one nitpick with the function at the top but overall LGTM

File: pkg/services/sqlstore/migrations/ualert/tables.go (hunk 2 above)
Comment (JacobsonMT) [reply pkg/services/sqlstore/migrations/ualert/tables.go:24]: The intention was to use the latest one as a sort of example to follow, but I agree it should be alongside `addAlertmanagerConfigHistoryMigrations`. I'll move it into `historicalTablesMigrations`

File: pkg/services/sqlstore/migrations/ualert/tables.go (hunk 3 above)
Comment (JacobsonMT) [reply pkg/services/sqlstore/migrations/ualert/tables.go:459]: I think it still wouldn't solve the underlying issue. IMO, the confusion is mostly caused by the fact that our main legacy -> new alerting migration isn't really a migration:

- It's mutable. It changes quite often.
- It's reversible. This means, it needs to be constantly updated to work with the most recent data model otherwise there can be issues if the the migration is reverted and reapplied.
- It's optional. So, knowing it was applied gives us no information on what their migrated alerts look like now since it depends entirely on the version they did the migration and if they have since modified them.
- Because of the above, it can't be composed in a way to apply step-wise over time; the migration is all or nothing. This means that if someone has previously migrated in, say 8.4, they would have to revert and remigrate to take advantage of any improvements since then.

These migration assumptions more closely resemble an 'upgrade tool/cli' and if I were to recommend making large changes to it now that's probably what I would go for. Basically, extract the legacy migration that actually converts their alerting data as a tool and keep the other migrations (such as table schemas) as ones that are immutable and can be reasoned around like any other migration in Grafana.

This won't change any of the points from above. We'd still have to maintain the tool to upgrade to the current data model. But, it would mean our actual migrations can be reasoned around more clearly.
