### PR TITLE
Alerting: Display correct results when using different filters on alerting panels

### LINKED ISSUE #70383: Dashboards: Only one alerts list panel on dashboard shows alerts even with mutually exclusive filters
### 
# What went wrong?

**What happened**:

I have a dashboard with multiple alerts list panels, each filtering for alerts from a specific layer using label filters. Even when there is at least one alert for each layer, only one panel actually shows alerts. Furthermore this seems to be quite random, on refresh and switching to the panel edit window and back sometimes two panels show alerts and sometimes the panel that shows alerts changes. This issue has been recreated with both using the repeat option and manually creating panels for each layer+severity combination.

The following images are from the same dashboard without any modifications one before and one after switching to the edit panel page and switching back:
alerts_1_blurred
alerts_2_blurred

**What did you expect to happen**:

Each panel should be populated with the appropriate alerts with the desired "layer" label.

### 
# How do we reproduce it?

**Step 1**:

- Create two alert list panels in a dashboard, each filtering for different values of a label:
```
alert 2 : {label1="X"}
alert 1 :  {label1="Y"}
```

**Step 2**:

- Make sure there currently are alert instances firing for both these label values.

**Step 3**:

- Reload dashboard and observer changes.

### 
# What Grafana version are you using?

v10.0.0

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Debian 10

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by VikaCep**
**What is this feature?**

Fixes an issue where showing several alerting panels within a dashboard don't respect each panel's alert state filter settings.

**Why do we need this feature?**

To be able to respect alert state filters within a dashboard with several alerting panels.

**Who is this feature for?**

All users

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/support-escalations/issues/6423

**Special notes for your reviewer:**

When loading several alert list panels where each panel uses a different state filter, the request called to obtain the rules information remains the same. It doesn't trigger a new request if the param changes (in the example `state=pending` and `state=firing` are different filters that should trigger a separate request each). 

After some investigation we concluded the reason behind this is the Redux store keeps the data from the latest loaded panel. This started happening after [the filtering logic was moved to the backend.](https://github.com/grafana/grafana/pull/66267) In order to fix this, a potential solution (that is implemented in this PR) is to fetch the grafana alert rules using RTK query instead of getting it from the store for prom rules, which are the ones that are filtered in the backend.

**We are only getting promrules from RTKQ instead of the Redux Store for grafana managed alerts because so far, are the only ones that the filter is done in the BE.** 

Before - Only one request with `state=firing` when there is one missing with `state=pending`.
Screenshot 2023-06-21 at 19 06 12

Before - Two requests with `state=firing` and `state=pending` after forcing the request calls. The problem here is that the firing panel is not showing all instances due an incorrect result from the redux store.
Screenshot 2023-06-21 at 19 06 39

After - Using RTK Query the panels show the correct instances as we skip reading it from the store.

### CODE REVIEW

File: public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts [hunk 1]
```diff
@@ -67,9 +71,13 @@ export function useCombinedRuleNamespaces(rulesSourceName?: string): CombinedRul
     return rulesSources
       .map((rulesSource): CombinedRuleNamespace[] => {
         const rulesSourceName = isCloudRulesSource(rulesSource) ? rulesSource.name : rulesSource;
-        const promRules = promRulesResponses[rulesSourceName]?.result;
+        let promRules = promRulesResponses[rulesSourceName]?.result;
         const rulerRules = rulerRulesResponses[rulesSourceName]?.result;
 
+        if (rulesSourceName === GRAFANA_RULES_SOURCE_NAME && promRuleNamespaces) {
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts:77]:
```suggestion
        if ( promRuleNamespaces) {
```
So, if `useCombinedRuleNamespaces` we will not use the Redux store and we will use the  `promRuleNamespaces` parameter.

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts:77]: Actually, maybe better:
const promRules = promRuleNamespaces??promRulesResponses[rulesSourceName]?.result :

File: public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts [hunk 2]
```diff
@@ -45,7 +46,10 @@ interface CacheValue {
 
 // this little monster combines prometheus rules and ruler rules to produce a unified data structure
 // can limit to a single rules source
-export function useCombinedRuleNamespaces(rulesSourceName?: string): CombinedRuleNamespace[] {
+export function useCombinedRuleNamespaces(
+  rulesSourceName?: string,
+  promRuleNamespaces?: RuleNamespace[]
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts:51]: maybe we could change this name to `grafanaPromRuleNamespaces`?

File: public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts [hunk 3]
```diff
@@ -67,9 +71,13 @@ export function useCombinedRuleNamespaces(rulesSourceName?: string): CombinedRul
     return rulesSources
       .map((rulesSource): CombinedRuleNamespace[] => {
         const rulesSourceName = isCloudRulesSource(rulesSource) ? rulesSource.name : rulesSource;
-        const promRules = promRulesResponses[rulesSourceName]?.result;
+        let promRules = promRulesResponses[rulesSourceName]?.result;
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts:74]:
```suggestion
        const promRules = grafanaPromRuleNamespaces??promRulesResponses[rulesSourceName]?.result;
```

File: public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts (hunk 2 above)
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts:51]:
```suggestion
  grafanaPromRuleNamespaces?: RuleNamespace[]
```
I think with this name is more clear that we are only optionally passing Grafana promrules

File: public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts (hunk 1 above)
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts:77]:
```suggestion
       
```
if we apply changes above this line is not necessary

File: public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts [hunk 4]
```diff
@@ -67,9 +71,13 @@ export function useCombinedRuleNamespaces(rulesSourceName?: string): CombinedRul
...
         const rulerRules = rulerRulesResponses[rulesSourceName]?.result;
 
+        if (rulesSourceName === GRAFANA_RULES_SOURCE_NAME && promRuleNamespaces) {
+          promRules = promRuleNamespaces;
+        }
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts:79]:
```suggestion
     
```

**Review by soniaAguilarPeiron — APPROVED** [review]
Great job! 🚀
I added some non-blocking comments

File: public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts (hunk 2 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts:51]: I'm a bit confused about this, aren't we also using `useCombinedRuleNamespaces` for prometheus (non-Grafana managed) too?

**Review by gillesdemey — APPROVED** [review]
Code changes LGTM, and I can't repro the bug on this branch – awesome work! 🚀

File: public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts (hunk 2 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts:51]: yes, but this parameter is only used in case of grafana alert data source

File: public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts (hunk 1 above)
Comment (VikaCep) [reply public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts:77]: `rulesSourceName` could be other than `GRAFANA_RULES_SOURCE_NAME` so it's not enough with checking that the `promRuleNamespaces` param is present, we also need to check that we're dealing with `grafana`

File: public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts (hunk 2 above)
Comment (VikaCep) [reply public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts:51]: Yeap, we use it for all other prometheus rules as well. The new parameter contains only grafana-managed though, which are the ones that present the bug as those are filtered by the backend.

**Comment by soniaAguilarPeiron** [comment]
I would add in the PR description that we are only getting promrules from RTKQ instead of the Redux Store for grafana managed alerts because so far, are the only ones that the filter is done in the BE. @VikaCep

File: public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts (hunk 2 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/hooks/useCombinedRuleNamespaces.ts]: Gotcha, that makes sense! 👍
