### PR TITLE
DynamicDashboards: Fix scroll positioning when returning to dashboard

### LINKED ISSUE #99165: Restore scrolling position after panel edit
Restore scrolling position when coming back from panel edit is not working (but adding a timeout to restoreScrollPos seems to make it work).

### PR DESCRIPTION
**Pull request by mdvictor**
**What is this feature?**

Fixes remembering the scroll position when returning to dashboard from panel edit in the new layouts editor.

**Why do we need this feature?**

Fixes a bug

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/99165

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard-scene/edit-pane/DashboardEditPaneSplitter.tsx [hunk 1]
```diff
@@ -68,7 +68,7 @@ export function DashboardEditPaneSplitter({ dashboard, isEditing, body, controls
   }
 
   const onBodyRef = (ref: HTMLDivElement) => {
-    dashboard.onSetScrollRef(ref);
+    dashboard.onSetScrollRef(new DivScrollElement(ref));
```
Comment (mdvictor) [inline public/app/features/dashboard-scene/edit-pane/DashboardEditPaneSplitter.tsx:71]: Setting the scroll element here helps to use the defined `scrollTo` method which also has a retry system, instead of the native scrollTo which will just fail with no retry, thus having the issue.

**Review by torkelo — APPROVED** [review]

**Review by bfmatei — APPROVED** [review]
🚀 🚀 🚀 🚀
