### PR TITLE
Alerting: Allow linking to silence form with `__alert_rule_uid__` value preset

### LINKED ISSUE #45370: Not able to silence alerts in folder with editor permission
**What happened**:
Users with global "viewer" permission and folder "editor" permission can create alerts in that folder, but can't silence them.
**What you expected to happen**:
Users should be able to silence the alerts they created, even they don't have global editor permission.
**How to reproduce it (as minimally and precisely as possible)**:
Create user with global viewer permission and grant editor permission on any folder. 
Create test alert in that folder.
Choose created alert at /alerting/list page and click "Silence" button.
Browser just redirects to grafana home page and silence is not created
**Anything else we need to know?**:
Nope
**Environment**:
- Grafana version: 8.3.6
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by tomratcliffe**
**What is this feature?**

Allows linking to the silence form to work with `matcher=__alert_rule_uid__%3Dsomeuid`, so the alert rule is correctly fetched and used in the form

**Why do we need this feature?**

This allows users to link to the silence form with the alert rule prepopulated, rather than being restricted to having selected the alert via the UI/alert rule list

**Who is this feature for?**

Alerting UI users

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/45370

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/alerting/unified/Silences.tsx [hunk 1]
```diff
@@ -30,9 +31,20 @@ const Silences = () => {
         <Route exact path="/alerting/silence/new">
           {({ location }) => {
             const queryParams = new URLSearchParams(location.search);
+            const potentialRuleUid = queryParams
+              .getAll('matcher')
+              .find((m) => m.startsWith(MATCHER_ALERT_RULE_UID))
```
Comment (konrad147) [inline public/app/features/alerting/unified/Silences.tsx:36]: Should we use `parseMatcher` or any other similar helper here? 
The `alert_rule_uid` shouldn't contain any problematic characters, so the code should work, rather for consistency/readability

**Review by konrad147 — APPROVED** [review]
LGTM! one non-blocking nit
