### PR TITLE
fix extra templating refresh

### LINKED ISSUE #8186: [Bug] deselect panel repeated value cause extra query
Please include this information:
- What Grafana version are you using?
4.2.0
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
Mac
- What did you do?
1. Create dashboard with panel repeat
2. select several value of panel repeat variable
3. deselect some value
- What was the expected result?
Only visible panel cause query.
- What happened instead?
There are extra query.
For example, if each panel has 1 query, and repeat 5 panel.
And then, deselect 1 value, it cause 10 query.
The query count should be 4 query.

Maybe, it is concurrency order problem.
The refresh event is reached to panel, before panel is removed.
https://github.com/grafana/grafana/blob/v4.2.0/public/app/core/directives/value_select_dropdown.js#L254
 
EDIT (2017/04/21 21:15 +0900):
10 query is not correct, 5 query.

### PR DESCRIPTION
**Pull request by mtanda**
Fix https://github.com/grafana/grafana/issues/8186
Skip refresh event once, this may fix the issue.

### CODE REVIEW

File: public/app/features/templating/variable_srv.ts [hunk 1]
```diff
@@ -130,6 +137,7 @@ export class VariableSrv {
     return this.$q.all(promises).then(() => {
       if (emitChangeEvents) {
         this.$rootScope.$emit('template-variable-value-updated');
+        this.ignoreRefresh = true;
         this.$rootScope.$broadcast('refresh');
```
Comment (torkelo) [inline public/app/features/templating/variable_srv.ts]: a better way to solve this without using the instance variable/state ignoreRefresh would be to send an object in the refresh event like:
this.$rootScope.$broadcast('refresh', {fromVariableValueUpdated: true});

Then you can in the onDashboardRefresh function take this argument in (evt, payload)

**Review by torkelo — CHANGES_REQUESTED** [review]

File: public/app/features/templating/variable_srv.ts (hunk 1 above)
Comment (mtanda) [reply public/app/features/templating/variable_srv.ts]: Thanks, feedback!

**Comment by marefr** [comment]
Thank you for contributing to Grafana!
