### PR TITLE
RBAC: Fix permissions on dashboards and folders created by anonymous users

### LINKED ISSUE #51828: Dashboards created by non-logged-in users have incorrect permissions
**What happened**:

Since our update to 9.0.2 we have observed a problematic behaviour after creating new dashboards.

The installation is a Grafana running internally at our company. There are two organisations and the options for authentication are set like this:

auth.anonymous
enabled	true
hide_version	false
org_name	MYORG
org_role	Editor

If a user who is not logged in now creates a dashboard, he gets the message that he is not allowed to see the dashboard and these messages appear in the logs:

`
6.7.2022 17:13:41logger=dashboard-service t=2022-07-06T15:13:41.92554616Z level=error msg="Could not make user admin" dashboard="Test 2 New dashboard" user=0 error="'' built-in role is not valid"
6.7.2022 17:13:42logger=dashboard.permissions t=2022-07-06T15:13:42.204456645Z level=info msg="Access denied to folder or dashboard" userId=0 id=395 permissions="any(dashboards:read dashboards:read)"
6.7.2022 17:13:42logger=context traceID=00000000000000000000000000000000 userId=0 orgId=2 uname= t=2022-07-06T15:13:42.204547314Z level=info msg="Request Completed" method=GET path=/api/dashboards/uid/EgI2wc6nz status=403 remote_addr=172.20.x.x time_ms=26 duration=26.166045ms size=45 referer=https://grafana.my.org/d/EgI2wc6nz/test-2-new-dashboard traceID=00000000000000000000000000000000
`

If I then log in with the user admin, I see the new dashboard and can use it. The permissions look like this:

screenshot 2022-07-06 um 17 43 40

If I look at a dashboard created before the update, the permissions look like this:

screenshot 2022-07-06 um 17 44 10

**What you expected to happen**:

Dashboards created by users who are not logged in should still be accessible to all.

**How to reproduce it (as minimally and precisely as possible)**:

Create a new dashboard as a user who is not logged in

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.2
- Data source type & version: all
- OS Grafana is installed on: Docker image grafana/grafana:9.0.2
- User OS & Browser: all
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by gamab**
**What this PR does / why we need it**:
Dashboards created by non-logged-in users have incorrect permissions because anonymous users having an ID set to `0` they cannot be made admin of the dashboard they created. Hence setting the permissions fails.
This PR adds checks to verify that users are not anonymous before making them admin.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/51828

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/dashboards/service/dashboard_service.go [hunk 1]
```diff
@@ -470,7 +470,7 @@ func (dr *DashboardServiceImpl) setDefaultPermissions(ctx context.Context, dto *
 	inFolder := dash.FolderId > 0
 	if !accesscontrol.IsDisabled(dr.cfg) {
 		var permissions []accesscontrol.SetResourcePermissionCommand
-		if !provisioned {
+		if !provisioned && dto.User.IsRealUser() && !dto.User.IsAnonymous {
```
Comment (gamab) [inline pkg/services/dashboards/service/dashboard_service.go:473]: We could only check for `IsRealUser()` as anonymous users have an ID set to `0` in the context which we consider as non real users. But in case some day we endup changing their ID, I added both checks, just in case.

Comment (IevaVasiljeva) [reply pkg/services/dashboards/service/dashboard_service.go:473]: I think that's a good shout! 👌

**Review by IevaVasiljeva — APPROVED** [review]
Thanks for picking this up and fixing it so fast!
