### PR TITLE
Prometheus: Fix body not being included in resource calls if they are POST

### LINKED ISSUE #50798: Variable - Query issue - After migrating from 8.5.5 to 9.0.0-beta3 with VictoriaMetrics datasource
**What happened?**

Earlier had the version 8.5.5 running with VictoriaMetrics 1.77.2. Was using a bunch of dashboard variables and the queries were working fine. 

After the upgrade to 9.0.0-beta3 the variable query validation keeps failing. Shows "missing match[] query arg"

**What was expected?**
Was expecting the variables will be compatible with the newer version. The variable queries are working fine when I use 8.5.5 version with VictoriaMetrics 1.77.2

**When does it happen?**
This happens when the data source is VictoriaMetrics. Found this error while checking the logs of VictoriaMetrics found this error

> VictoriaMetrics/app/vmselect/main.go:467	error in "/api/v1/series": missing `match[]` query arg

**Environment**
The stack is running on AWS EKS with Amazon Linux
Grafana - 9.0.0-beta3
VictoriaMetrics - 1.77.2

### PR DESCRIPTION
**Pull request by aocenas**
fixes: https://github.com/grafana/grafana/issues/50798

This tries to minimize the transformation of resource request. There is still some and this probably needs more work but for now should make sure that POST requests and their body is sent as it is further downstream.

### CODE REVIEW

File: pkg/tsdb/prometheus/client/client.go [hunk 1]
```diff
@@ -77,36 +78,43 @@ func (c *Client) QueryExemplars(ctx context.Context, q *models.Query) (*http.Res
...
-
-	r, err := http.NewRequestWithContext(ctx, method, u.String(), nil)
+	bodyReader := bytes.NewReader(body)
+	request, err := http.NewRequestWithContext(ctx, method, u.String(), bodyReader)
 	if err != nil {
 		return nil, err
 	}
 
 	if strings.ToUpper(method) == http.MethodPost {
-		r.Body = ioutil.NopCloser(strings.NewReader(qs.Encode()))
```
Comment (toddtreece) [inline pkg/tsdb/prometheus/client/client.go:105]: the `fetch` method was originally meant to be used by the query API methods to handle the switching between GET or POST based on what the user selected in the data source settings, so removing this will break POST bodies for those.

this might be a bad idea, but i attempted to simplify this [on this branch](https://github.com/grafana/grafana/blob/0af51eee721488fce80750735e07215c6ffdd87b/pkg/tsdb/prometheus/client/client.go) by implementing the `http.RoundTripper` interface and building the full resource call proxied `http.Request` in `resource.go`, and calling `RoundTrip` directly instead of mixing the proxy code with prometheus API client methods

Comment (torkelo) [reply pkg/tsdb/prometheus/client/client.go:105]: > so removing this will break POST bodies for those methods. i think it got a bit confusing once resource calls started using fetch since they pull the HTTP method from a different source

This does not remove that, method is still read from datasource settings. From what I can tell this only makes sure we forward the request body in case of POST

Comment (torkelo) [reply pkg/tsdb/prometheus/client/client.go:105]: > so removing this will break POST bodies for those methods. i think it got a bit confusing once resource calls started using fetch since they pull the HTTP method from a different source

This does not remove that, method is still read from datasource settings. From what I can tell this only makes sure we forward the request body in case of POST

Comment (aocenas) [reply pkg/tsdb/prometheus/client/client.go:105]: The decision on what the method is should be on the front end for now IMHO. So this just forwards the request as it is removing as much magic in between as possible. We still strip some headers which I guess makes sense and make sure the URL is correct but otherwise, I don't see any need to alter the request when doing a resource call.

So I assume this was meant as a way to change GET resource request to POST in the grafana server but we don't really do that and I am not sure if that would give us many benefits.

Comment (aocenas) [reply pkg/tsdb/prometheus/client/client.go:105]: Also if you want POST based on config, what would be the benefit doing a GET between browser - grafana and then switch to POST between grafana - prometheus? Seems like that translation is not really necessary and could just lead to problems and confusion.

Comment (toddtreece) [reply pkg/tsdb/prometheus/client/client.go:105]: @torkelo @aocenas ah ok, i think i might be misunderstanding how the POST setting is supposed to be used for `/api/ds/query` calls which use the QueryRange, QueryInstant, and QueryExemplars methods

File: pkg/tsdb/prometheus/client/client.go [hunk 2]
```diff
@@ -42,7 +43,7 @@ func (c *Client) QueryRange(ctx context.Context, q *models.Query) (*http.Respons
 	qs.Set("end", formatTime(tr.End))
 	qs.Set("step", strconv.FormatFloat(tr.Step.Seconds(), 'f', -1, 64))
 
-	return c.fetch(ctx, c.method, u, qs)
+	return c.fetch(ctx, c.method, u, qs, nil)
```
Comment (aocenas) [inline pkg/tsdb/prometheus/client/client.go:46]: All this other uses of fetch are not in use now as they are used only behind streaming feature flag.

@toddtreece not sure though how it was supposed to work with POST request. Seems like it assumed it will just use `qs` and make a POST body out of it but if the request from front end was POST there would be no `qs` and the `body` would be lost, wouldn't it?

File: pkg/tsdb/prometheus/client/client.go [hunk 3]
```diff
@@ -77,36 +78,51 @@ func (c *Client) QueryExemplars(ctx context.Context, q *models.Query) (*http.Res
...
 
-	return c.fetch(ctx, method, u, qs)
+	return c.fetch(ctx, req.Method, baseUrlParsed, nil, req.Body)
 }
 
-func (c *Client) fetch(ctx context.Context, method string, u *url.URL, qs url.Values) (*http.Response, error) {
-	if strings.ToUpper(method) == http.MethodGet {
+func (c *Client) fetch(ctx context.Context, method string, u *url.URL, qs url.Values, body []byte) (*http.Response, error) {
+	// The qs arg seems to be used in some callers of this method, but you can already pass them in the URL object
+	if strings.ToUpper(method) == http.MethodGet && qs != nil {
```
[the remark this answers is not in the document]
Comment (aocenas) [reply pkg/tsdb/prometheus/client/client.go:110]: Don't think so, it's the way it is because it is used for streaming and that probably needs to be refactored a bit and we probably not use it for resource calls right now as we mix different clients. Again something for refactor just didn't want to go into it right now.

**Review by yesoreyeram — APPROVED** [review]

File: pkg/tsdb/prometheus/client/client.go (hunk 2 above)
Comment (toddtreece) [reply pkg/tsdb/prometheus/client/client.go:46]: just adding a note from our call since we discussed it there. this change will break streaming queries, but it can be fixed during a future HTTP client refactor

File: pkg/tsdb/prometheus/client/client_test.go [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+				PluginContext: backend.PluginContext{},
+				Path:          "/api/v1/series",
+				Method:        http.MethodPost,
+				URL:           "/api/v1/series",
+				Headers:       nil,
+				Body:          []byte("match%5B%5D: ALERTS\nstart: 1655271408\nend: 1655293008"),
+			}
+			res, err := client.QueryResource(context.Background(), req)
+			defer func() {
+				if err := res.Body.Close(); err != nil {
```
[the remark this answers is not in the document]
Comment (aocenas) [reply pkg/tsdb/prometheus/client/client_test.go]: Added checks around the closing of the Body I think the nil body should be valid for Gets
