### PR TITLE
Login: Angular to React

### LINKED ISSUE #17928: Rewrite login page to react
Should be pretty straight forward. 

There is a "post login" view as well on the login page that handles changing password if you login with default "admin" password. This should, of course, be broken up into separate React components.

### PR DESCRIPTION
**Pull request by tskarhed**
**Which issue(s) this PR fixes**:
Closes #17928

- Disables login/change password button instead of giving an error message on submit.
- Currently removes the info icon next to "skip", but that will be fixed in another PR

**Notes to reviewer**
Enable different ways of authentication in config.

### CODE REVIEW

**Comment by dehrax** [comment]
- [ ] Check that requests are correct
- [ ] Make the animations work

File: public/app/core/components/Login/LoginCtrl.tsx [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+import config from 'app/core/config';
+
+import { updateLocation } from 'app/core/actions';
+import { connect } from 'react-redux';
+import { StoreState } from 'app/types';
+import { PureComponent } from 'react';
+import { getBackendSrv } from '@grafana/runtime';
+import { hot } from 'react-hot-loader';
+
+let backendSrv;
```
Comment (torkelo) [inline public/app/core/components/Login/LoginCtrl.tsx]: move this to an instance prop instead on the LoginCtrl

File: public/app/core/components/Login/LoginCtrl.tsx [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+    changePassword: boolean;
+    toGrafana: Function;
+    signUp: Function;
+    login: (data: FormModel, valid: boolean) => void;
+  }) => JSX.Element;
+}
+
+interface State {
+  loggingIn: boolean;
+  changePassword: boolean;
```
Comment (torkelo) [inline public/app/core/components/Login/LoginCtrl.tsx]: try to naming booleans like "isChangingPassword" , I know some if the config booleans do not follow this but as general rule this should be followed. changePassword is especially bad as it's named like an action.

File: public/app/core/components/Login/LoginCtrl.tsx [hunk 3]
```diff
@@ -0,0 +1,133 @@
...
+    loggingIn: boolean;
+    changePassword: boolean;
+    toGrafana: Function;
+    signUp: Function;
+    login: (data: FormModel, valid: boolean) => void;
+  }) => JSX.Element;
+}
+
+interface State {
+  loggingIn: boolean;
```
Comment (torkelo) [inline public/app/core/components/Login/LoginCtrl.tsx]: isLogggingIn

File: public/app/core/components/Login/LoginPage.tsx [hunk 4]
```diff
@@ -0,0 +1,99 @@
+import React, { PureComponent } from 'react';
+import config from 'app/core/config';
+import { UserSignup } from './UserSignup';
+import { LoginServiceButtons } from './LoginServiceButtons';
+import LoginCtrl from './LoginCtrl';
+import { LoginForm } from './LoginForm';
+import { ChangePassword } from './ChangePassword';
+
+const oauthEnabled = () => Object.keys(config.oauth).length > 0;
```
Comment (torkelo) [inline public/app/core/components/Login/LoginPage.tsx]: isOAuthEnasbled

File: public/app/core/components/Login/LoginPage.tsx [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+  password: string;
+  email: string;
+  valid: boolean;
+}
+
+export class LoginPage extends PureComponent<Props, State> {
+  submit: Function;
+  constructor(props: Props) {
+    super(props);
+    this.state = {
```
Comment (torkelo) [inline public/app/core/components/Login/LoginPage.tsx]: is this used?

**Review by torkelo — COMMENTED** [review]
I know this is WIP, but added some comments.

**Review by baur — APPROVED** [review]

**Comment by dehrax** [comment]
I am having some issues when rerouting to home - the user isn't actually signed in, even though the request was succesfull.
Screenshot from 2019-08-02 13-40-45

A simple reload does the trick. Is that what is required? In the angular code this was used
https://github.com/grafana/grafana/blob/5e1a3c9ee2f39127def594876affc077a95af03c/public/app/core/controllers/login_ctrl.ts#L132
Is that to force a reload? It doesn't seem to work properly with Redux, so is `window.location.href` a way to go?

**Comment by dehrax** [comment]
Is this currently being used?
https://github.com/grafana/grafana/blob/5e1a3c9ee2f39127def594876affc077a95af03c/public/app/core/controllers/login_ctrl.ts#L89

Can't seem to find a way to change `loginMode`, so it's kinda hard to understand what it's meant to do.

File: public/app/core/components/Login/LoginCtrl.tsx [hunk 6]
```diff
@@ -0,0 +1,141 @@
...
+  user: string;
+  password: string;
+  email: string;
+}
+interface Props {
+  routeParams?: any;
+  updateLocation?: typeof updateLocation;
+  children: (obj: {
+    isLoggingIn: boolean;
+    changePassword: (pw: { newPassword: string; confirmNew: string; oldPassword: string }, valid: boolean) => void;
```
Comment (dprokop) [inline public/app/core/components/Login/LoginCtrl.tsx]: I think changePassword should only accept a string with new password as an argument. The front-end validation should be performed in the form itself (not allowing to call changePassword at all).

File: public/app/core/components/Login/LoginCtrl.tsx [hunk 7]
```diff
@@ -0,0 +1,141 @@
...
+      // });
+    }
+  };
+
+  render() {
+    const { children } = this.props;
+    const { isLoggingIn, isChangingPassword } = this.state;
+    const { login, toGrafana, changePassword } = this;
+
+    return <>{children({ login, isLoggingIn, changePassword, toGrafana, isChangingPassword })}</>;
```
Comment (dprokop) [inline public/app/core/components/Login/LoginCtrl.tsx]: I suggest exposing `toGrafana` via `skipPasswordChange` property. `toGrafana` is an implementation detail that could be (and is, in the LoginCtrl) used id multiple contexts. And the use case that you are supporting by exposing it, is a particular activity, which is skipping the password change.

File: public/app/core/components/Login/LoginCtrl.tsx [hunk 8]
```diff
@@ -0,0 +1,141 @@
...
+      .then(() => {
+        this.toGrafana();
+      })
+      .catch((err: any) => console.log(err));
+  };
+
+  login = (formModel: FormModel, valid: boolean) => {
+    console.log(formModel);
+    console.log(this);
+    if (!valid) {
```
Comment (dprokop) [inline public/app/core/components/Login/LoginCtrl.tsx]: Should be handled in the form itself, `login` should only control the login action. that should not be called at all if the form is not valid

File: public/app/core/components/Login/ChangePassword.tsx [hunk 9]
```diff
@@ -0,0 +1,126 @@
...
+  }
+
+  onSubmit = (e: SyntheticEvent) => {
+    e.preventDefault();
+
+    const { newPassword, confirmNew } = this.state;
+    if (this.state.valid) {
+      this.props.onSubmit({ newPassword, confirmNew, oldPassword: 'admin' }, true);
+    } else {
+      appEvents.on('alert-warning', ['New passwords do not match', '']);
```
Comment (dprokop) [inline public/app/core/components/Login/ChangePassword.tsx]: Don't you want to `emit` the event rather than listening to it?

File: public/app/core/components/Login/ChangePassword.tsx [hunk 10]
```diff
@@ -0,0 +1,126 @@
...
+    }
+  };
+
+  onChange = (e: SyntheticEvent) => {
+    // @ts-ignore
+    this.setState({ [e.target.name]: e.target.value }, () => {
+      this.setState({
```
Comment (dprokop) [inline public/app/core/components/Login/ChangePassword.tsx]: Seems like an antipattern to me to set state as a consequence of setState (will cause double re-render). I think you should validate the data before setting new value.

File: public/app/core/components/Login/LoginForm.tsx [hunk 11]
```diff
@@ -0,0 +1,123 @@
...
+          )}
+
+          {this.props.displayForgotPassword ? (
+            <div className="small login-button-forgot-password">
+              <a href="user/password/send-reset-email">Forgot your password?</a>
+            </div>
+          ) : null}
+        </div>
+      </form>
+    ) : null;
```
Comment (dprokop) [inline public/app/core/components/Login/LoginForm.tsx]: Why are you rendering nothing here? You could decide whether or not to render the LoginForm in the LoginPage component, and keep the visibility information in the LoginCtrl

File: public/app/core/components/Login/LoginPage.tsx [hunk 12]
```diff
@@ -0,0 +1,70 @@
...
+        <div className="login-branding">
+          <img className="logo-icon" src="public/img/grafana_icon.svg" alt="Grafana" />
+          <div className="logo-wordmark" />
+        </div>
+        <LoginCtrl>
+          {({ login, isLoggingIn, changePassword, toGrafana, isChangingPassword }) => (
+            <div className="login-out-box">
+              <div className={`login-inner-box ${isChangingPassword ? 'hidden' : ''}`} id="login-view">
+                <LoginForm
+                  displayLoginFields={!config.disableLoginForm}
```
Comment (dprokop) [inline public/app/core/components/Login/LoginPage.tsx]: Can this be set independently from the `config` object?

Comment (dprokop) [reply public/app/core/components/Login/LoginPage.tsx]: Ah, wait, this, this is actually an app config, so it can not. Ignore ^^

File: public/app/core/components/Login/LoginPage.tsx [hunk 13]
```diff
@@ -0,0 +1,70 @@
...
+                  displayForgotPassword={!(config.ldapEnabled || config.authProxyEnabled)}
```
Comment (dprokop) [inline public/app/core/components/Login/LoginPage.tsx]: Since this is sort of logic i think it belongs to the LoginCtrl, so the dependency on the app config should belong there too.

File: public/app/core/components/Login/UserSignup.tsx [hunk 14]
```diff
@@ -0,0 +1,13 @@
+import React, { FC } from 'react';
+import config from 'app/core/config';
+
+export const UserSignup: FC<any> = ({}) => {
```
Comment (dprokop) [inline public/app/core/components/Login/UserSignup.tsx]: `FC<void>`

File: public/sass/pages/_login.scss [hunk 15]
```diff
@@ -162,18 +162,17 @@ select:-webkit-autofill:focus {
   transform: tranlate(0px, 0px);
   transition: 0.25s ease;
 
-  &.add {
-    transform: translate(0px, -320px);
-    &.hidden {
-      display: none;
-    }
+  &.hidden {
```
Comment (dprokop) [inline public/sass/pages/_login.scss]: Do you feel like migrating _login.scss to Emotion? Or this may be worth another PR

**Comment by dprokop** [comment]
image

Seems like the login button is always disabled

**Comment by dehrax** [comment]
> image
> 
> Seems like the login button is always disabled
No problem for me. Can you check the state?
Screenshot from 2019-08-07 10-18-19

File: public/app/core/components/Login/ChangePassword.tsx (hunk 10 above)
Comment (dehrax) [reply public/app/core/components/Login/ChangePassword.tsx]: Are you thinking that I should only set the values if they are validated? Shouldn't the state reflect whatever is in the text field?

File: public/app/core/components/Login/LoginCtrl.tsx (hunk 6 above)
Comment (dehrax) [reply public/app/core/components/Login/LoginCtrl.tsx]: I thought `LoginCtrl` could be used in another context. Or should it just be for the LoginPage? It feel a bit weird to just set `oldPassword` to `admin` in the `LoginCtrl`.

File: public/app/core/components/Login/ChangePassword.tsx (hunk 9 above)
Comment (dehrax) [reply public/app/core/components/Login/ChangePassword.tsx]: Good point, although  just realized that you really can't reach this piece of code since the button is disabled as long as the passwords don't match.

File: public/sass/pages/_login.scss (hunk 15 above)
Comment (dehrax) [reply public/sass/pages/_login.scss]: Yeah, I could do that after this is merged, just to have some closure I guess :smiley:

File: public/app/core/components/Login/UserSignup.tsx (hunk 14 above)
Comment (dehrax) [reply public/app/core/components/Login/UserSignup.tsx]: Typescript complains about that, so I'm just doing `FC<{}>`

**Comment by dprokop** [comment]
@dehrax it works, seems like some glitch that I had

File: public/app/core/components/Login/LoginCtrl.tsx (hunk 6 above)
Comment (dprokop) [reply public/app/core/components/Login/LoginCtrl.tsx]: It still could be used in another context. It's just a matter of what data you pass into the method. Why would you need the `newPassword` and and `confirmNew` when those are the same (I assume this is already assured by ty the time the change password button is clicked)? So my suggestion here is to change the signature of changePassword to `changePassword(password: string)` and make it front end validation independent.

File: public/app/core/components/Login/ChangePassword.tsx (hunk 10 above)
Comment (dprokop) [reply public/app/core/components/Login/ChangePassword.tsx]: it should, but you have the knowledge what the text gonna be as it's available via the event object, right? sou you could do :

```ts
this.setState((state) => {
  [e.target.name]: e.target.value,
  isValid: /// compare the event value against the state value
});
```

File: public/app/core/components/Login/ChangePassword.tsx [hunk 16]
```diff
@@ -0,0 +1,132 @@
...
+    if (valid) {
+      this.props.onSubmit(newPassword);
+    } else {
+      appEvents.emit('alert-warning', ['New passwords do not match', '']);
+    }
+  };
+
+  onChange = (e: ChangeEvent<HTMLInputElement>) => {
+    // @ts-ignore
+    const { value } = this.state;
```
Comment (dprokop) [inline public/app/core/components/Login/ChangePassword.tsx]: There is no value property in `State` interface. And you also don't use it below

File: public/app/core/components/Login/ChangePassword.tsx [hunk 17]
```diff
@@ -0,0 +1,132 @@
...
+    // @ts-ignore
+    this.setState({
```
Comment (dprokop) [inline public/app/core/components/Login/ChangePassword.tsx]: This ignore is because State has no index signature. I suggest you create two separate methods (onNewPasswordChange, onConfirmPasswordChange) that will call onChange with a partial state update. And then you won't have to rely on `e.target.name`. Relying on event.target.name is flaky as any typo in the name of the input will not be picked up by Typescript and can lead to silent errors.

File: public/app/core/components/Login/LoginPage.tsx [hunk 18]
```diff
@@ -0,0 +1,80 @@
...
+                  </>
+                ) : null}
+                {!disableUserSignUp ? <UserSignup /> : null}
+              </div>
+              <CSSTransition appear={true} in={isChangingPassword} timeout={250} classNames="login-inner-box">
+                <ChangePassword
+                  onSubmit={changePassword}
+                  onSkip={skipPasswordChange}
+                  focus={isChangingPassword}
+                  className={isChangingPassword ? '' : 'hidden'}
```
Comment (dprokop) [inline public/app/core/components/Login/LoginPage.tsx]: I suggest you don't render the ChangePassword at all if it's not necessary. You won't need className at all in ChangePassword then.

Comment (dprokop) [reply public/app/core/components/Login/LoginPage.tsx]:
```tsx
{ isChangingPassword  && (
    <CSSTransition appear={true} in={isChangingPassword} timeout={250} classNames="login-inner-box">
                <ChangePassword...
)}
```

Comment (dehrax) [reply public/app/core/components/Login/LoginPage.tsx]: That's for the animation to work properly. I'll see if it's possible to do it without `className` there.

File: public/app/core/components/Login/LoginCtrl.tsx [hunk 19]
```diff
@@ -0,0 +1,161 @@
...
+    this.state = {
+      isLoggingIn: false,
+      isChangingPassword: false,
+    };
+    if (config.loginError) {
+      appEvents.emit('alert-warning', ['Login Failed', config.loginError]);
+    }
+  }
+
+  changePassword = (pws: string) => {
```
Comment (dprokop) [inline public/app/core/components/Login/LoginCtrl.tsx]: pws -> pswd | password (preferably)

File: public/app/core/components/Login/LoginCtrl.tsx [hunk 20]
```diff
@@ -0,0 +1,161 @@
...
+export class LoginCtrl extends PureComponent<Props, State> {
+  result: any = {};
+  constructor(props: Props) {
+    super(props);
+    this.state = {
+      isLoggingIn: false,
+      isChangingPassword: false,
+    };
+    if (config.loginError) {
+      appEvents.emit('alert-warning', ['Login Failed', config.loginError]);
```
Comment (dprokop) [inline public/app/core/components/Login/LoginCtrl.tsx]: uhm, so what's up with this? Is this needed at all?

Comment (dehrax) [reply public/app/core/components/Login/LoginCtrl.tsx]: Yeah, I have no idea. I'll remove it, can't find anything about `loginError` in the config.

Comment (dprokop) [reply public/app/core/components/Login/LoginCtrl.tsx]: Ok, I see it's set by grafana server and returned via boot data (see pkg/api/login.go). @papagian can u elaborate on that a little bit?

File: public/app/core/components/Login/LoginForm.tsx [hunk 21]
```diff
@@ -0,0 +1,122 @@
...
+
+    const { user, password, email } = this.state;
+    if (this.state.valid) {
+      this.props.onSubmit({ user, password, email });
+    }
+  };
+
+  onChange = (e: SyntheticEvent) => {
+    // @ts-ignore
+    this.setState({ [e.target.name]: e.target.value }, () => {
```
Comment (dprokop) [inline public/app/core/components/Login/LoginForm.tsx]: Same as my previous comment about `@ts-ignore`

File: public/app/core/components/Login/LoginForm.tsx [hunk 22]
```diff
@@ -0,0 +1,122 @@
...
+      this.setState({ valid: this.validate() }, () => {
+        if (this.props.onChange) {
+          this.props.onChange(this.state.valid);
+        }
+      });
+    });
+  };
+
+  validate() {
+    if (this.state.user.length > 0 && this.state.password.length > 0) {
```
Comment (dprokop) [inline public/app/core/components/Login/LoginForm.tsx]:
```suggestion
 return this.state.user.length > 0 && this.state.password.length > 0
```

File: public/app/core/components/Login/LoginForm.tsx [hunk 23]
```diff
@@ -0,0 +1,122 @@
...
+    const { user, password, email } = this.state;
+    if (this.state.valid) {
+      this.props.onSubmit({ user, password, email });
+    }
+  };
+
+  onChange = (e: SyntheticEvent) => {
+    // @ts-ignore
+    this.setState({ [e.target.name]: e.target.value }, () => {
+      this.setState({ valid: this.validate() }, () => {
```
Comment (dprokop) [inline public/app/core/components/Login/LoginForm.tsx]: Same as my previous comment about nested `setState` :)

File: public/app/core/components/Login/LoginForm.tsx [hunk 24]
```diff
@@ -0,0 +1,122 @@
...
+        <div className="login-form">
+          <input
+            ref={input => {
+              this.userInput = input;
+            }}
+            type="text"
+            name="user"
+            className="gf-form-input login-form-input"
+            required
+            // ng-model="formModel.user"
```
Comment (dprokop) [inline public/app/core/components/Login/LoginForm.tsx]:
```suggestion

```

File: public/app/core/components/Login/LoginCtrl.tsx [hunk 25]
```diff
@@ -0,0 +1,161 @@
...
+
+export interface FormModel {
+  user: string;
+  password: string;
+  email: string;
+}
+interface Props {
+  routeParams?: any;
+  updateLocation?: typeof updateLocation;
+  children: (obj: {
```
Comment (dprokop) [inline public/app/core/components/Login/LoginCtrl.tsx]: obj -> props

File: public/app/core/components/Login/LoginCtrl.tsx (hunk 20 above)
Comment (papagian) [reply public/app/core/components/Login/LoginCtrl.tsx]: `loginError` is returned by the view if OAuth login fails for any reason in order to be displayed to the user the cause of the failure like [this](https://user-images.githubusercontent.com/23303904/60657611-3430dd00-9e84-11e9-8c79-929aeb92d1f6.png).

File: public/app/core/components/Login/LoginCtrl.tsx [hunk 26]
```diff
@@ -0,0 +1,162 @@
...
+    });
+  };
+
+  toGrafana = () => {
+    const params = this.props.routeParams;
+    // Use window.location.href to force page reload
+    if (params.redirect && params.redirect[0] === '/') {
+      window.location.href = config.appSubUrl + params.redirect;
+
+      // this.props.updateLocation({
```
Comment (dprokop) [inline public/app/core/components/Login/LoginCtrl.tsx]: Pls remove those commented out lines:)

**Comment by dprokop** [comment]
image


Can u pls align logo and form? Looks slightly off

**Comment by dprokop** [comment]
login

And one more UI thing -> see how logotype position changes when you go from login to change pswd screen. The change pswd form should have the same width as login form has

**Review by dprokop — APPROVED** [review]
Some small UI issues found, apart from that all seems good!

**Comment by dehrax** [comment]
> Can u pls align logo and form? Looks slightly off


They actually are aligned. It's the border on the input element that makes it look misaligned. I could of course add a small margin on the button to compensate for that, but I don't think it is necessary.
