### PR TITLE
MSSQL: Fix connection when password  contains semicolon

### LINKED ISSUE #17665: Semicolon character in MSSQL password won't authenticate
**What happened**:
Authentication to Microsoft SQL server fails when there are special characters in the password. 
(.?;|<)
**What you expected to happen**:
I expected to be able to log in with a password that contains special characters. This password works in Management Studio and Excel. 
**How to reproduce it (as minimally and precisely as possible)**:
Setup a test account on any Microsoft SQL Server that has '(.?;|<)' in the password then try to connect with it from Grafana.
**Anything else we need to know?**:
Microsoft SQL Server 12.0.5207.0
**Environment**:
- Grafana version:
Grafana v6.2.4 (ee01897)
- Data source type & version:
Microsoft SQL Server (NOT SURE WHERE THE VERSION FOR THIS IS)
- OS Grafana is installed on:
Microsoft Windows 10 Pro 1809 Build 17763.557
- User OS & Browser:
Microsoft Windows 10 Pro 1809 Build 17763.557
Chrome Version 74.0.3729.169 (Official Build) (64-bit)
- Grafana plugins:
Just Default, I didn't install any extras. 
- Others:

### PR DESCRIPTION
**Pull request by MdTanwer**
## What

Fix MSSQL datasource authentication failure when the username or password contains ';' or '}' by properly handling special characters in the connection string; other special characters work correctly.

Previously, the connection string was built by concatenating values directly (e.g. `password=StrongPass;123;`). The go-mssqldb driver treats semicolon as the key-value delimiter, so a password like `StrongPass;123` was parsed as `password=StrongPass` and `123` as a separate token, causing authentication to fail.

## Why

Passwords such as `StrongPass;123` are valid in SQL Server but broke the Grafana MSSQL datasource because they were embedded in the connection string without escaping.

## How

- When the password or username contains `;` or `}`, we now use ODBC-style escaping supported by the go-mssqldb driver:
  - Prefix the connection string with `odbc:` so the driver uses the ODBC parser.
  - Wrap values in braces and escape `}` as `}}` (e.g. `password={StrongPass;123};`).
- When the password and username do not contain these characters, behavior is unchanged (no `odbc:` prefix, no braces).

**Which issue(s) does this PR fix?**:

Fixes #17665

### CODE REVIEW

File: pkg/tsdb/mssql/sqleng/connection.go [hunk 1]
```diff
@@ -17,6 +18,20 @@ import (
 	"github.com/microsoft/go-mssqldb/azuread"
 )
 
+// odbcNeedsEscape returns true if the value contains semicolon or closing brace,
+// which would break connection string parsing (semicolon is the key=value delimiter).
+func odbcNeedsEscape(s string) bool {
+	return strings.ContainsAny(s, ";}")
+}
```
Comment (adamyeats) [inline pkg/tsdb/mssql/sqleng/connection.go:25]:
```suggestion
func odbcNeedsEscape(s string) bool {
    return strings.ContainsAny(s, ";}") || s != strings.TrimSpace(s)
}
```

The [docs](https://pkg.go.dev/github.com/denisenkom/go-mssqldb#section-readme) for the driver warns:

> ADO: `key=value` pairs separated by `;`. Values may not contain `;`, leading and trailing whitespace is ignored.

The driver's ADO-style parsing ignores leading/trailing whitespace in values, so passwords like "foo " can fail silently. The above modification should make the function trigger correctly even in the above case. If you accept this change, please update the tests to cover it.

File: pkg/tsdb/mssql/sqleng/connection.go [hunk 2]
```diff
@@ -121,9 +136,25 @@ func generateConnectionString(dsInfo DataSourceInfo, azureCredentials azcredenti
...
+			connStr = kerberos.Krb5ParseAuthCredentials(addr.Host, addr.Port, dsInfo.Database, user, pass, kerberosAuth)
+		}
 	default:
-		connStr += fmt.Sprintf("user id=%s;password=%s;", dsInfo.User, dsInfo.DecryptedSecureJSONData["password"])
+		user := dsInfo.User
+		pass := dsInfo.DecryptedSecureJSONData["password"]
+		if odbcNeedsEscape(pass) || odbcNeedsEscape(user) {
+			user = escapeOdbcValue(user)
+			pass = escapeOdbcValue(pass)
+			connStr = "odbc:" + connStr + fmt.Sprintf("user id=%s;password=%s;", user, pass)
```
Comment (adamyeats) [inline pkg/tsdb/mssql/sqleng/connection.go]: This seems to prepend `odbc:` without guarding against `connStr` already having the prefix (maybe in a future refactor/other auth types). Consider normalising with `strings.TrimPrefix(connStr, "odbc:")` before adding, or (apply the prefix once at the end when `useOdbc` (for example) is `true`.

File: pkg/tsdb/mssql/sqleng/connection.go [hunk 3]
```diff
@@ -121,9 +136,25 @@ func generateConnectionString(dsInfo DataSourceInfo, azureCredentials azcredenti
...
+		if odbcNeedsEscape(pass) || odbcNeedsEscape(user) {
+			user = escapeOdbcValue(user)
+			pass = escapeOdbcValue(pass)
+			connStr = "odbc:" + kerberos.Krb5ParseAuthCredentials(addr.Host, addr.Port, dsInfo.Database, user, pass, kerberosAuth)
+		} else {
+			connStr = kerberos.Krb5ParseAuthCredentials(addr.Host, addr.Port, dsInfo.Database, user, pass, kerberosAuth)
+		}
 	default:
-		connStr += fmt.Sprintf("user id=%s;password=%s;", dsInfo.User, dsInfo.DecryptedSecureJSONData["password"])
+		user := dsInfo.User
```
Comment (adamyeats) [inline pkg/tsdb/mssql/sqleng/connection.go:152]: Minor nit: can we hoist this above the `switch`? We seem to extract these values multiple times in the same `switch`.

File: pkg/tsdb/mssql/sqleng/connection.go [hunk 4]
```diff
@@ -121,9 +136,25 @@ func generateConnectionString(dsInfo DataSourceInfo, azureCredentials azcredenti
...
 	case kerberosRaw, kerberosKeytab, kerberosCredentialCacheFile, kerberosCredentialCache:
-		connStr = kerberos.Krb5ParseAuthCredentials(addr.Host, addr.Port, dsInfo.Database, dsInfo.User, dsInfo.DecryptedSecureJSONData["password"], kerberosAuth)
+		user := dsInfo.User
+		pass := dsInfo.DecryptedSecureJSONData["password"]
+		if odbcNeedsEscape(pass) || odbcNeedsEscape(user) {
+			user = escapeOdbcValue(user)
+			pass = escapeOdbcValue(pass)
+			connStr = "odbc:" + kerberos.Krb5ParseAuthCredentials(addr.Host, addr.Port, dsInfo.Database, user, pass, kerberosAuth)
+		} else {
+			connStr = kerberos.Krb5ParseAuthCredentials(addr.Host, addr.Port, dsInfo.Database, user, pass, kerberosAuth)
```
Comment (adamyeats) [inline pkg/tsdb/mssql/sqleng/connection.go]: Are we sure whether `Krb5ParseAuthCredentials` expects ADO or ODBC DSN parsing here? Suggest computing `useOdbc` (for example) once (based on `user`/`pass`), and applying the `odbc:` prefix exactly once after building the DSN, so the Kerberos path doesn’t depend on helper internals.

**Review by adamyeats — COMMENTED** [review]
Thank you for this @MdTanwer ! This fixes a long standing bug, and we're extremely grateful for that. 🥇 I've left a couple of comments, after those are resolved then we'll be good to go!

File: pkg/tsdb/mssql/sqleng/connection.go (hunk 2 above)
Comment (MdTanwer) [reply pkg/tsdb/mssql/sqleng/connection.go]: Good catch — I'll normalize the prefix using strings.TrimPrefix(connStr, "odbc:") to ensure odbc: is applied only once

File: pkg/tsdb/mssql/sqleng/connection.go (hunk 4 above)
Comment (MdTanwer) [reply pkg/tsdb/mssql/sqleng/connection.go]: Done. I’ve refactored the Kerberos path to compute useOdbc once from user/pass, call Krb5ParseAuthCredentials once (treating it as raw DSN), and apply the odbc: prefix only at the end when useOdbc is true, so we no longer depend on the helper’s format.

**Comment by MdTanwer** [comment]
Hey @adamyeats  Addressed review: guard against double odbc: prefix with TrimPrefix, and in the Kerberos path compute useOdbc once and apply the odbc: prefix in one place so it no longer depends on Krb5ParseAuthCredentials internals—ready for review.

**Comment by adamyeats** [comment]
Thank you @MdTanwer ! Can you try another merge/rebase from `main` here please? Hopefully that'll clear the outstanding pipeline fails. I've checked them and they don't seem to have anything to do with your code.

**Review by adamyeats — APPROVED** [review]
Great stuff @MdTanwer ! Thanks for contributing! 🎉
