### PR TITLE
Cloudwatch: Fix errors while loading queries/datasource on Safari

### LINKED ISSUE #79347: CloudWatch: Errors while loading queries/datasource on Safari
When using the CloudWatch plugin with Safari, CloudWatch errors and isn't able to successfully query. I tried both CloudWatch with Chrome and tried other datasource plugins with Safari and only had this issue with CloudWatch and Safari. Interestingly, the original reporter got the error `Type error: undefined is not an object (evaluating 'Qs')` while I got the error:
Screenshot 2023-12-11 at 11 35 46 AM 
and when I try to open an existing dashboard the console logs a warning: `[Log] failed to load data source – {message: "Datasource: <DatasourceID> was not found"}`

Originally reported in https://github.com/grafana/support-escalations/issues/8693

### PR DESCRIPTION
**Pull request by kevinwcyu**
**Which issue(s) does this PR fix?**:

Fixes #79347

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts [hunk 1]
```diff
@@ -109,9 +105,9 @@ export class CloudWatchMetricsQueryRunner extends CloudWatchRequest {
 
   performTimeSeriesQuery(
     request: DataQueryRequest<CloudWatchQuery>,
-    { from, to }: TimeRange
```
Comment (iwysiu) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts:112]: good catch!

**Review by iwysiu — APPROVED** [review]
Nice! I tried it with safari and chrome (just in case, lol) and it worked
