### PR TITLE
Alerting: Ignore obsolete notification channels referenced by alerts

### LINKED ISSUE #24969: Unable to translate notification id to uid
**What happened**:
When attempting to edit a dashboard (any edit, doesn't have to be alert specific), and then save, we get the following error: 

> Alert validation error: Unable to translate notification id to uid, Alert notification [ id: 46, OrgId:1 ] not found PanelId: 76 DashboardId: 720

image

**What you expected to happen**:
The dashboard to save successfully

**How to reproduce it (as minimally and precisely as possible)**:
We have recently upgraded from Grafana 6.6.2-Ubuntu to 7.0.0-Ubuntu Docker images (Postgres to store dashboard) and trying to edit and then save any dashboard with alerts throws this error

**Anything else we need to know?**:
Let me know if you need any more details around the dashboard or alerts in the DB

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: PostgreSQL 10.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28), 64-bit  
- OS Grafana is installed on: CentOS 7 using Grafana Ubuntu Docker version 7.0.0
- User OS & Browser: Chrome - Mac and Windows
- Grafana plugins: WorldPing
- Others:

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
Do not return an alert validation error if a deleted notification channel is found.

**Which issue(s) this PR fixes**:

Temporary Fixes #24969

**Special notes for your reviewer**:

I have opened another [PR](https://github.com/grafana/grafana/pull/25303) for adding confirmation modals targeting this branch but it's not 100% ready yet.

### CODE REVIEW

File: pkg/services/alerting/rule.go [hunk 1]
```diff
@@ -140,9 +140,10 @@ func NewRuleFromDBAlert(ruleDef *models.Alert) (*Rule, error) {
 		if id, err := jsonModel.Get("id").Int64(); err == nil {
 			uid, err := translateNotificationIDToUID(id, ruleDef.OrgId)
 			if err != nil {
-				return nil, ValidationError{Reason: "Unable to translate notification id to uid, " + err.Error(), DashboardID: model.DashboardID, AlertID: model.ID, PanelID: model.PanelID}
+				logger.Debug("Unable to translate notification id to uid", "error", err.Error(), "DashboardID", model.DashboardID, "AlertID", model.ID, "PanelID", model.PanelID)
```
Comment (marefr) [inline pkg/services/alerting/rule.go:143]: Suggest error level on log message or warning.

```suggestion
				logger.Error("Unable to translate notification id to uid", "error", err.Error(), "dashboardId", model.DashboardID, "alertId", model.ID, "panelId", model.PanelID, "notificationId", id)
```

**Review by marefr — CHANGES_REQUESTED** [review]
Looks good, but suggest change of log message, see suggestion

**Review by marefr — APPROVED** [review]
LGTM

**Review by aknuds1 — APPROVED** [review]
