### PR TITLE
QueryInspector: Show all buttons small screen sizes

### LINKED ISSUE #66585: [Supporting the platform - Server request>Inspect]: Controls present under "Query" tab are not visible after setting the view port at 320*256.
## User Experience: 
Low vision users who depend on zooming the page for better readability will be impacted as they will not be able to see the complete content present in the page if the controls are not visible or truncated which will result in lack of understandability and will fail to access the controls. 

## Pre-requisite:  
Achieve viewport 320 X 256 by adjusting the browser. (Open developer's tool, resize and zoom the browser to achieve viewport 320 X 256).

## Repro Steps:
Open #URL: https://play.grafana.org/. Sign in with valid credentials. "Home" page appears. Navigate the "Server Requests Graphs". Expand the button and select the "Inspect" button. Select "Data" menu item. Navigate all the controls under the "Query" tab pane. Select the "Refresh" button. Select "+Expand all" button. Navigate to "Object " section. Verify the issue.
 Actual Result: Controls present under "Query" tab are not visible after setting the view port at 320*256.

## Expected Result:
 Controls such as "Query" "Refresh" button, "Object", "request: object" and "response: Array [4]" present under "Query " tab should be clearly visible after setting the view port at 320*256.

## Severity
`SEV2`
## Area
`TestRuleResult Component (Alerting Inspect Drawer) `

### PR DESCRIPTION
**Pull request by eledobleefe**
**What is this feature?**
It makes the buttons row wrap when the screen has a small size (320 x 256)

**Why do we need this feature?**
For users to be able to see all buttons no matter the screen size used

**Who is this feature for?**
Everybody

**Which issue(s) does this PR fix?**:

Fixes #66585 

**Special notes for your reviewer:**
| Before | After |
| ------ | ------ |
|The first button is not visible Captura de pantalla 2025-03-17 a las 13 16 32 | Captura de pantalla 2025-03-17 a las 13 16 41|
|Captura de pantalla 2025-03-17 a las 13 18 30| Captura de pantalla 2025-03-17 a las 13 18 39|

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/inspector/QueryInspector.tsx [hunk 1]
```diff
@@ -237,38 +237,34 @@ export class QueryInspector extends PureComponent<Props, State> {
...
-
-          {haveData && allNodesExpanded && (
-            <Button icon="minus" variant="secondary" className={styles.toolbarItem} onClick={this.onToggleExpand}>
-              <Trans i18nKey="inspector.query.collapse-all">Collapse all</Trans>
-            </Button>
-          )}
-          {haveData && !allNodesExpanded && (
-            <Button icon="plus" variant="secondary" className={styles.toolbarItem} onClick={this.onToggleExpand}>
-              <Trans i18nKey="inspector.query.expand-all">Expand all</Trans>
+        <Box marginBottom={1}>
```
[the remark this answers is not in the document]
Comment (eledobleefe) [reply public/app/features/inspector/QueryInspector.tsx:240]: Nop, they don't wrap.
Regarding having another Stack with a column gap, I don't mind. There is also the `Space` component that I can use to add space between the toolbar buttons and the next block. Wdyt?

File: public/app/features/inspector/QueryInspector.tsx [hunk 2]
```diff
@@ -237,38 +237,34 @@ export class QueryInspector extends PureComponent<Props, State> {
...
+          <Stack direction={'row'} gap={2} justifyContent={'flex-start'} wrap>
```
[the remark this answers is not in the document]
Comment (eledobleefe) [reply public/app/features/inspector/QueryInspector.tsx:241]: Captura de pantalla 2025-03-17 a las 16 53 26

The good part about using `Box` and `Stack` is that we can remove the `marginLeft` of the `toolbarItems`, use `gap` to add space between buttons, and, therefore, easily align them.

**Review by ivanortegaalba — APPROVED** [review]
All good from Dashboards side! 💯

File: public/app/features/inspector/QueryInspector.tsx [hunk 3]
```diff
@@ -237,7 +237,7 @@ export class QueryInspector extends PureComponent<Props, State> {
           </p>
         </div>
         {this.renderExecutedQueries(executedQueries)}
-        <div className={styles.toolbar}>
+        <Stack direction={'row'} gap={2} justifyContent={'flex-start'} wrap>
```
Comment (tskarhed) [inline public/app/features/inspector/QueryInspector.tsx:240]:
```suggestion
        <Stack direction={'row'} gap={1} justifyContent={'flex-start'} wrap>
```

Maybe this is a personal preference, but I think it looks better with 1. Any thoughts @EdPoole ?

**Review by tskarhed — APPROVED** [review]
I will approve this, feel free to address my comment if you find it valuable

File: public/app/features/inspector/QueryInspector.tsx (hunk 3 above)
Comment (eledobleefe) [reply public/app/features/inspector/QueryInspector.tsx:240]: I wanted to keep the space we have currently, but @EdPoole, if you also think so I can change it 🤷‍♀️

Comment (tskarhed) [reply public/app/features/inspector/QueryInspector.tsx:240]: You can merge without changing this :)
