### PR TITLE
Explore: updates key and refId reassignment on query row operations in Explore reducer

### LINKED ISSUE #24731: Explore table panel gets Value #A and Value #B the wrong way roung
When running with two queries in explore, I'd expect Value #A to be the first and Value #B to be the second:

image

Version Grafana v7.1.0-91219227pre (bd42407)

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Updates key and refId reassignment on query row operations in Explore reducer - reassigns refIds and updates query row key on query row removal. Adds test coverage. Results in correct columns order when doing multiple queries in Explore, especially after removing and re-adding query rows.

**Which issue(s) this PR fixes**:

Fixes #24731 - continuation of #25131

### CODE REVIEW

**Comment by aocenas** [comment]
Not sure if this is ideal way to solve this. Is it possible to remove query row while the queries are in flight? What will happen in that case if the ref id changes? I think this case may have been problematic even before as we may have reused some refID, but I would expect refIDs to be stable during the query row lifetime.

**Comment by Estrax** [comment]
@aocenas 

> Is it possible to remove query row while the queries are in flight? What will happen in that case if the ref id changes?

Well, it works as same as with turning the queries on and off using the eye button in QueryRowActions - Grafana reruns all the queries then.

> I think this case may have been problematic even before as we may have reused some refID, but I would expect refIDs to be stable during the query row lifetime.

Prometheus and Loki do not get too much of a context from Explore - just enough data to run the query (basically only the query row data), and they use refIds to name columns with values - that's why I went with refId reassignment, because we don't have to pass too much of a data anywhere. refId itself is pretty stable - it gets reassigned only on QueryRow removal to make sure all the QueryRows are in order.

File: public/app/features/explore/state/reducers.ts [hunk 1]
```diff
@@ -367,15 +367,24 @@ export const itemReducer = (state: ExploreItemState = makeExploreItemState(), ac
...
+    const queriesAfterRemoval: DataQuery[] = [...queries.slice(0, index), ...queries.slice(index + 1)].map(query => {
+      return { ...query, refId: '' };
+    });
+    const nextQueries: DataQuery[] = [];
+
+    queriesAfterRemoval.forEach((query, i) => {
+      nextQueries.push(generateNewKeyAndAddRefIdIfMissing(query, nextQueries, i));
+    });
+
+    const nextQueryKeys: string[] = [...nextQueries.map(query => query.key)];
```
Comment (s-h-a-d-o-w) [inline public/app/features/explore/state/reducers.ts:387]: Doing array spread here is redundant, since `map()` already creates a new array.

File: public/app/features/explore/state/reducers.ts [hunk 2]
```diff
@@ -367,15 +367,24 @@ export const itemReducer = (state: ExploreItemState = makeExploreItemState(), ac
...
-    const nextQueryKeys = [...queryKeys.slice(0, index), ...queryKeys.slice(index + 1)];
+    // removes a query under a given index and reassigns query keys and refIds to keep everything in order
+    const queriesAfterRemoval: DataQuery[] = [...queries.slice(0, index), ...queries.slice(index + 1)].map(query => {
+      return { ...query, refId: '' };
+    });
+    const nextQueries: DataQuery[] = [];
+
+    queriesAfterRemoval.forEach((query, i) => {
+      nextQueries.push(generateNewKeyAndAddRefIdIfMissing(query, nextQueries, i));
+    });
```
Comment (s-h-a-d-o-w) [inline public/app/features/explore/state/reducers.ts:385]: You could use `.map()` instead of `forEach()` and `push()` here and skip the empty array initialization.

File: public/app/features/explore/state/reducers.test.ts [hunk 3]
```diff
@@ -231,6 +235,128 @@ describe('Explore item reducer', () => {
...
+          const queriesKeys = resultingState.queries.map(query => query.key);
+          expect(queriesRefIds).toEqual(['A', 'B']);
+          queriesKeys.forEach(queryKey => {
+            expect(queryKey).toMatch(QUERY_KEY_REGEX);
+          });
+          resultingState.queryKeys.forEach(queryKey => {
+            expect(queryKey).toMatch(QUERY_KEY_REGEX);
+          });
+          return true;
+        });
```
Comment (s-h-a-d-o-w) [inline public/app/features/explore/state/reducers.test.ts:357]: For easier maintainability and since I suppose this should focus on testing `removeQueryRowAction()` (you're testing `addQueryRowAction()` in another test already anyway, I'd remove all assertions except the final one.

And something that's in a similar vein but a bit more a matter of taste - also reduce the number of added query rows to 2 instead of 3, since `['B']` turning to `['A']` should be just as safe as `['B', 'C']` turning into `['A', 'B']`.

File: public/app/features/explore/state/reducers.ts (hunk 2 above)
Comment (Estrax) [reply public/app/features/explore/state/reducers.ts:385]: @s-h-a-d-o-w sure, but we'll need to write yet another helper or significantly modify the existing ones not to use partial results (hence the array) to assign refIds properly. No performance difference though - we're talking about queries array and its length usually doesn't exceed 30.

Comment (s-h-a-d-o-w) [reply public/app/features/explore/state/reducers.ts:385]: Sorry, I missed something about how this works when I read it. Forget about my comment. :)

**Review by s-h-a-d-o-w — APPROVED** [review]
