### PR TITLE
PasswordField: Prevent a password from being displayed when you click the Enter button

### LINKED ISSUE #37443: Login: Pressing enter on password field makes it visible
**What happened**:

The password visibility toggles

https://user-images.githubusercontent.com/1438972/127836787-e8ead39d-fa45-429b-815a-0e8bc71c91b2.mov

**What you expected to happen**:
The form to be submitted.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.0-pre (73d36d5521)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: MacOS, Safari
- Grafana plugins:
- Others: I use LastPass, which might be an issue

### PR DESCRIPTION
**Pull request by tskarhed**
**Which issue(s) this PR fixes**:

Fixes #37443 #37302

**Special notes for your reviewer**:

The aria labels are unnecessary here, since screen readers handles password fields in their own way.

### CODE REVIEW

File: public/app/core/components/PasswordField/PasswordField.tsx [hunk 1]
```diff
@@ -25,13 +25,9 @@ export const PasswordField: FC<Props> = React.forwardRef<HTMLInputElement, Props
         aria-label={selectors.pages.Login.password}
         ref={ref}
         suffix={
-          <IconButton
+          <Icon
```
Comment (ashharrison90) [inline public/app/core/components/PasswordField/PasswordField.tsx:28]: can we add `tabIndex={0}` here to allow for tabbing to the show password button?

**Review by ashharrison90 — COMMENTED** [review]
minor nit

File: public/app/core/components/PasswordField/PasswordField.tsx (hunk 1 above)
Comment (ashharrison90) [reply public/app/core/components/PasswordField/PasswordField.tsx:28]: actually a better solution is to keep `IconButton`, but add `type="button"`. that way it won't trigger on enter. see https://stackoverflow.com/a/12914700

**Review by ashharrison90 — APPROVED** [review]
looks good to me 🙌  nice spot tobias!

**Review by jackw — APPROVED** [review]
Awesome stuff! 🚀
