### PR TITLE
Snapshots: Update handling of repeated panels in V2 w/ snapshots

### LINKED ISSUE #117207: Snapshots: Repeated panels w/ All Temp Var Not Working in V2
**Why is this needed**:
To get repeated panels using All template variable working in V2 Snapshots. See https://github.com/grafana/grafana/issues/113524#issuecomment-3825528900

**What would you like to be added**:
A fix.

**Who is this feature for?**
Snapshots users

### PR DESCRIPTION
**Pull request by CollinFingar**
**What is this feature?**
This fixes how snapshots are generated using Schema V2. 

**Why do we need this feature?**
This fix is required because panel repeaters need to be broken down to individual panels for snapshots to work as snapshots won't render repeaters upon loading. It creates a new panel for each of the repeated clones and assigns it to a fixed coordinate.

**Who is this feature for?**
Snapshots users

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/117207

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard-scene/serialization/layoutSerializers/AutoGridLayoutSerializer.ts [hunk 1]
```diff
@@ -20,18 +20,53 @@ import { getGridItemKeyForPanelId } from '../../utils/utils';
...
-export function serializeAutoGridLayout(layoutManager: AutoGridLayoutManager): DashboardV2Spec['layout'] {
+export function serializeAutoGridLayout(
+  layoutManager: AutoGridLayoutManager,
+  isSnapshot?: boolean
+): DashboardV2Spec['layout'] {
   const { maxColumnCount, fillScreen, columnWidth, rowHeight, layout } = layoutManager.state;
   const defaults = defaultAutoGridLayoutSpec();
 
+  const items = isSnapshot
+    ? layout.state.children.flatMap((child) => {
```
Comment (harisrozajac) [inline public/app/features/dashboard-scene/serialization/layoutSerializers/AutoGridLayoutSerializer.ts]: @CollinFingar, your approach is valid if we want to follow the V1 pattern. An alternative to this would be this https://github.com/grafana/grafana/commit/34b6cfe6cb70156d973b12fffe5f0f0d7b12c6d8, and this would work for Custom variables only. 

In v2 dashboards, repeat panels are generated at runtime from variable values. When a custom variable is set to **All**, the repeat expansion depends on the variable options derived from the variable `query`. In snapshots, the snapshot trimming step clears `query` and collapses `options` to only the current selection, which removes the data needed to expand **All**. The result is a single panel in the snapshot instead of one per variable value.

Why this has been working in V1 is that V1 snapshots materialize repeated panels before snapshot rendering. Each repeated panel is persisted with its own `scopedVars` value, so the snapshot does not need to expand **All** during render.

I think we need to decide if there are security/privacy reasons to not include query when creating a snapshot, but currently in v1 `scopedVars` already contain the concrete value per repeated panel, so removing `query` for security does not remove the values from the snapshot payload in V1. 

@axelavargas you might have more context on removing query values from variables when creating a snapshot :)

Comment (axelavargas) [reply public/app/features/dashboard-scene/serialization/layoutSerializers/AutoGridLayoutSerializer.ts]: Hello 👋🏾 , took a look at both proposals. I like Collin's approach of following V1 pattern (materialize repeated panels before snapshot rendering). 

For snapshots, it's better to not include `query`, as @harisrozajac  mentioned, for security reasons, but also because for variables that are not `custom`, keeping that property won't do anything, as panels should contain the snapshot data in the time frame they were snapshotted.

**Review by axelavargas — COMMENTED** [review]
Hey @CollinFingar , took a quick look and added my thoughts. One question, is your current changes fixing the issue creating an snapshot for repeated library panels?

**Comment by CollinFingar** [comment]
@axelavargas it is fixing that issue, yeah. Thanks for taking a look at this!

Here is a recording if it working locally. This uses the variable "All" with panels set to repeat for each of the ten values used in this All context.

https://github.com/user-attachments/assets/eeeecc9a-dcc5-4b21-b008-285e57ed7fb7

File: public/app/features/dashboard-scene/serialization/layoutSerializers/AutoGridLayoutSerializer.ts (hunk 1 above)
Comment (harisrozajac) [inline public/app/features/dashboard-scene/serialization/layoutSerializers/AutoGridLayoutSerializer.ts]: can we extract this snapshot processing logic into a separate function? something like `serializeSnapshotRepaterItems` or `getRepeatedPanelsForSnapshot` like you have below in `transformSceneToSaveModelSchemaV2.ts‎`?

**Review by harisrozajac — APPROVED** [review]
LGMT! Just had a small nit below

File: public/app/features/dashboard-scene/serialization/layoutSerializers/AutoGridLayoutSerializer.ts (hunk 1 above)
Comment (CollinFingar) [reply public/app/features/dashboard-scene/serialization/layoutSerializers/AutoGridLayoutSerializer.ts]: Good idea, moved the logic out!

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/22314462630)
- Version: 13.0.0-22314462630
