### PR TITLE
Azure Monitor: Fixes broken log queries that use workspace

### LINKED ISSUE #45833: Azure Monitor Logs: Queries that have not yet been migrated from workspace to resource don't work
First reported in https://github.com/grafana/support-escalations/issues/1966

**What happened**:

Azure Monitor Logs queries that doesn't have a `resource`, but only a `workspace` in it are not working.

**Environment**:
- Grafana version: 8.4.1
- Data source type & version: Azure Monitor Logs

**How to reproduce it (as minimally and precisely as possible)**:
<details>
  <summary>Use this dashboard</summary>

``` json
{
  "__inputs": [
    {
      "name": "DS_AZURE_MONITOR",
      "label": "Azure Monitor",
      "description": "",
      "type": "datasource",
      "pluginId": "grafana-azure-monitor-datasource",
      "pluginName": "Azure Monitor"
    }
  ],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "7.5.0"
    },
    {
      "type": "datasource",
      "id": "grafana-azure-monitor-datasource",
      "name": "Azure Monitor",
      "version": "0.3.0"
    },
    {
      "type": "panel",
      "id": "stat",
      "name": "Stat",
      "version": ""
    },
    {
      "type": "panel",
      "id": "timeseries",
      "name": "Time series",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "panels": [
    {
      "datasource": "${DS_AZURE_MONITOR}",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 4,
      "options": {
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "/.*/",
          "values": false
        },
        "text": {},
        "textMode": "auto"
      },
      "pluginVersion": "7.5.0",
      "targets": [
        {
          "appInsights": {
            "dimension": [],
            "metricName": "select",
            "timeGrain": "auto"
          },
          "azureLogAnalytics": {
            "query": "Heartbeat | top 1 by TimeGenerated | project strcat(toint((now() - TimeGenerated) / 1s), \" seconds ago\")",
            "resultFormat": "time_series",
            "workspace": "cea42612-bff0-4957-be48-3f9b94ca3263"
          },
          "azureMonitor": {
            "aggOptions": [],
            "dimensionFilter": "*",
            "dimensionFilters": [],
            "metricDefinition": "select",
            "metricName": "select",
            "metricNamespace": "select",
            "resourceGroup": "select",
            "resourceName": "select",
            "timeGrain": "auto",
            "timeGrains": [],
            "top": "10"
          },
          "insightsAnalytics": {
            "query": "",
            "resultFormat": "time_series"
          },
          "queryType": "Azure Log Analytics",
          "refId": "A",
          "subscription": "44693801-6ee6-49de-9b2d-9106972f9572"
        }
      ],
      "title": "Logs - Last heartbeat",
      "type": "stat"
    },
    {
      "datasource": "${DS_AZURE_MONITOR}",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "axisSoftMax": 10,
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 10,
            "gradientMode": "none",
            "hideFrom": {
              "graph": false,
              "legend": false,
              "tooltip": false
            },
            "lineInterpolation": "smooth",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "never",
            "spanNulls": true
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "percent"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 15,
        "x": 0,
        "y": 8
      },
      "id": 2,
      "options": {
        "graph": {},
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltipOptions": {
          "mode": "single"
        }
      },
      "pluginVersion": "7.5.0-pre",
      "targets": [
        {
          "appInsights": {
            "dimension": [],
            "metricName": "select",
            "timeGrain": "auto"
          },
          "azureLogAnalytics": {
            "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
            "resultFormat": "time_series",
            "workspace": "e3fe4fde-ad5e-4d60-9974-e2f3562ffdf2"
          },
          "azureMonitor": {
            "aggOptions": [],
            "aggregation": "Average",
            "allowedTimeGrainsMs": [
              60000,
              300000,
              900000,
              1800000,
              3600000,
              21600000,
              43200000,
              86400000
            ],
            "dimensionFilter": "*",
            "dimensionFilters": [],
            "metricDefinition": "Microsoft.Compute/virtualMachines",
            "metricName": "Percentage CPU",
            "metricNamespace": "Microsoft.Compute/virtualMachines",
            "resourceGroup": "cloud-datasources",
            "resourceName": "GithubTestDataVM",
            "timeGrain": "auto",
            "timeGrains": [],
            "top": "10"
          },
          "insightsAnalytics": {
            "query": "",
            "resultFormat": "time_series"
          },
          "queryType": "Azure Monitor",
          "refId": "A",
          "subscription": "44693801-6ee6-49de-9b2d-9106972f9572"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Metrics - GithubTestDataVM CPU",
      "type": "timeseries"
    },
    {
      "datasource": "${DS_AZURE_MONITOR}",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "axisSoftMax": 10,
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 10,
            "gradientMode": "none",
            "hideFrom": {
              "graph": false,
              "legend": false,
              "tooltip": false
            },
            "lineInterpolation": "smooth",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "never",
            "spanNulls": true
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "percent"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 15,
        "x": 0,
        "y": 17
      },
      "id": 5,
      "options": {
        "graph": {},
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltipOptions": {
          "mode": "single"
        }
      },
      "pluginVersion": "7.5.0-pre",
      "targets": [
        {
          "appInsights": {
            "dimension": [],
            "metricName": "select",
            "timeGrain": "auto"
          },
          "azureLogAnalytics": {
            "query": "Perf\n| where CounterName == \"% Processor Time\"\n| where ObjectName == \"Processor\"\n| summarize avg(CounterValue) by bin(TimeGenerated, 1m), Computer\n| order by TimeGenerated asc",
            "resultFormat": "table",
            "workspace": "cea42612-bff0-4957-be48-3f9b94ca3263"
          },
          "azureMonitor": {
            "aggOptions": [],
            "aggregation": "Average",
            "allowedTimeGrainsMs": [
              60000,
              300000,
              900000,
              1800000,
              3600000,
              21600000,
              43200000,
              86400000
            ],
            "dimensionFilter": "*",
            "dimensionFilters": [],
            "metricDefinition": "Microsoft.Compute/virtualMachines",
            "metricName": "Percentage CPU",
            "metricNamespace": "Microsoft.Compute/virtualMachines",
            "resourceGroup": "cloud-datasources",
            "resourceName": "GithubTestDataVM",
            "timeGrain": "auto",
            "timeGrains": [],
            "top": "10"
          },
          "insightsAnalytics": {
            "query": "",
            "resultFormat": "time_series"
          },
          "queryType": "Azure Log Analytics",
          "refId": "A",
          "subscription": "44693801-6ee6-49de-9b2d-9106972f9572"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Logs - GithubTestDataVM CPU",
      "type": "timeseries"
    }
  ],
  "refresh": false,
  "schemaVersion": 27,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Azure Monitor Josh Test Migration",
  "uid": "L-wXPUlMk",
  "version": 1
}
```json
</details>

### PR DESCRIPTION
**Pull request by sunker**
**What this PR does / why we need it**:
Before the resource picker was introduced in 8.0, scope for Logs queries were defined by a workspace. Since 8.0, Azure Monitor Logs queries that use `workspace` are being migrated to use `resource` instead. This migration takes place once the Logs editor is opened. Immediately after opening a dashboard, the datasource.query method is invoked before the migration takes place. That should be fined because both the resource and the workspace path is being handled correctly in the [backend](https://github.com/grafana/grafana/blob/main/pkg/tsdb/azuremonitor/azure-log-analytics-datasource.go#L82-L86). However, queries that did not have a `resource` prop on the query object would not be executed at all due to a bug in the frontend. This PR makes sure queries that **only** has a workspace are being executed properly. 

See issue for details on how to reproduce. 

**Which issue(s) this PR fixes**:
First reported in https://github.com/grafana/support-escalations/issues/1966
Fixes #45833

### CODE REVIEW

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_log_analytics/azure_log_analytics_datasource.ts [hunk 1]
```diff
@@ -1,26 +1,27 @@
...
+import LogAnalyticsQuerystringBuilder from '../log_analytics/querystring_builder';
+import {
+  AzureDataSourceJsonData,
+  AzureLogsVariable,
+  AzureMonitorQuery,
+  AzureQueryType,
+  DatasourceValidationResult,
+} from '../types';
 import { interpolateVariable, routeNames } from '../utils/common';
+import ResponseParser, { transformMetadataToKustoSchema } from './response_parser';
```
Comment (sunker) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_log_analytics/azure_log_analytics_datasource.ts:24]: clean up order of imports

**Review by andresmgot — APPROVED** [review]
LGTM
