### PR TITLE
Interpolate $__interval in backend for alerting with sql datasources

### LINKED ISSUE #11555: Variable ($__interval_ms) not replaced in Alert Query using SQL DataSource
Running 5.0.4 against MySQL datasource. Errors logged is:
lvl=eror msg="Alert Rule Result Error" logger=alerting.evalHandler ruleId=0 name="Backup alert" error="tsdb.HandleRequest() response error &{Error 1054: Unknown column '$__interval_ms' in 'group statement'  A 0xc4207e9b10 [] []}" changing state to=alerting

Actual query sent to MySQL:
```
SELECT
  UNIX_TIMESTAMP(Updated) as time_sec,
  Avg(Value) as value,
  Name as metric
FROM measurements
INNER JOIN sensors ON sensors.SID = measurements.SID 
WHERE Updated >= FROM_UNIXTIME(1523411324) AND Updated <= FROM_UNIXTIME(1523414924) AND measurements.SID = 190
GROUP BY UNIX_TIMESTAMP(Updated) DIV ($__interval_ms/1000) 
ORDER BY Updated ASC
```

Notice the Grafana $__interval_ms is still in the query causing it to fail.

Expected results was the $__interval_ms would be replaced with a value such that the MySQL is valid.

### PR DESCRIPTION
**Pull request by svenklemm**
Refactor sql datasources to use shared string replace
function and add support for interpolating $__interval
and $__interval_ms in backend to allow using those variables
in alerting queries.

Fixes #11555

### CODE REVIEW

File: pkg/tsdb/sql_engine_test.go [hunk 1]
```diff
@@ -14,6 +14,28 @@ func TestSqlEngine(t *testing.T) {
...
+			query := &Query{}
+
+			Convey("interpolate $__interval", func() {
+				sql, err := Interpolate(query, timeRange, "select $__interval ")
+				So(err, ShouldBeNil)
+
+				So(sql, ShouldEqual, "select 300s ")
+			})
+
+			Convey("interpolate $__interval_ms", func() {
```
Comment (marefr) [inline pkg/tsdb/sql_engine_test.go]: A test where using $__interval in $__timeGroup would be nice since I think that won't work. Think you need to do the global interpolation before the datasource interpolation, but I may be wrong?

**Review by marefr — CHANGES_REQUESTED** [review]
Just took a quick look and I think I found an issue that's need to be fixed, see code comment.

File: pkg/tsdb/sql_engine_test.go (hunk 1 above)
Comment (svenklemm) [reply pkg/tsdb/sql_engine_test.go]: It should work since the regexp matcher for the datasource looks for function calls and should leave $__interval untouched but actual global macros might not work for that reason and the datasource specific macro handling code would need to be adjusted to let those macros through.
But I'm not 100% sure and will add test cases around this.

I did the calls in this order to allow datasource specific implementation of macros to overwrite the global one.

**Comment by svenklemm** [comment]
@marefr Adjusted PR and added tests that verify complete interpolation chain with $__timeGroup

File: pkg/tsdb/sql_engine.go [hunk 2]
```diff
@@ -163,6 +172,26 @@ func (e *sqlQueryEndpoint) Query(ctx context.Context, dsInfo *models.DataSource,
 	return result, nil
 }
 
+// global macros/substitutions for all sql datasources
+func Interpolate(query *Query, timeRange *TimeRange, sql string) (string, error) {
+	rExp, _ := regexp.Compile(`\$__(interval|interval_ms)\b`)
+
+	sql = ReplaceAllStringSubmatchFunc(rExp, sql, func(groups []string) string {
+		switch groups[1] {
+		case "interval":
```
Comment (marefr) [inline pkg/tsdb/sql_engine.go]: There's existing functions and interfaces for calculating intervals that you should use, see influxdb code [here](https://github.com/grafana/grafana/blob/master/pkg/tsdb/influxdb/model_parser.go#L42) and [here](https://github.com/grafana/grafana/blob/master/pkg/tsdb/influxdb/query.go#L37-L38). There should be similar example code for prometheus and elasticsearch.

Sorry, should have spotted this earlier.

**Review by marefr — CHANGES_REQUESTED** [review]

File: pkg/tsdb/sql_engine.go [hunk 3]
```diff
@@ -163,6 +172,33 @@ func (e *sqlQueryEndpoint) Query(ctx context.Context, dsInfo *models.DataSource,
...
 
+// global macros/substitutions for all sql datasources
+func Interpolate(query *Query, timeRange *TimeRange, sql string) (string, error) {
+	rExp, _ := regexp.Compile(`\$__(interval|interval_ms)\b`)
+	var err error
+
+	sql = ReplaceAllStringSubmatchFunc(rExp, sql, func(groups []string) string {
+		switch groups[1] {
+		case "interval":
+			interval, err := GetIntervalFrom(query.DataSource, query.Model, time.Second*60)
```
Comment (marefr) [inline pkg/tsdb/sql_engine.go]: This only returns the minInterval. Same applies for interval_ms.

You'll need to use the [IntervalCalculator](https://github.com/grafana/grafana/blob/master/pkg/tsdb/interval.go#L52) to get the actual interval. See [example usage for influxdb](https://github.com/grafana/grafana/blob/master/pkg/tsdb/influxdb/query.go#L32-L38). 

Optional, but very appreciated, it would be very nice if we could add a Milliseconds() method to [Interval](https://github.com/grafana/grafana/blob/master/pkg/tsdb/interval.go#L19). Then we can use that method here and for [elasticsearch](https://github.com/grafana/grafana/blob/master/pkg/tsdb/elasticsearch/client/client.go#L141) and [influxdb](https://github.com/grafana/grafana/blob/master/pkg/tsdb/influxdb/query.go#L37).

**Review by marefr — CHANGES_REQUESTED** [review]
Looks good, but still needs some changes regarding interval calculation.

**Comment by svenklemm** [comment]
Do we want MillisecondsText() aswell or instead since all the places where it would be used is as string

**Review by marefr — APPROVED** [review]

**Comment by marefr** [comment]
Thank you for contributing to Grafana!
