### PR TITLE
ResourcePicker: Fix selecting icons

### LINKED ISSUE #67941: ResourcePicker: Unable to select icons consistently
There appears to be a bug with resource picker where user is unable to select an icon consistently. This may be related to the recent upgrade to React 18

https://user-images.githubusercontent.com/22381771/236543695-db3a5f17-82a2-4da7-ad48-f70c6ac4f736.mov

Issue appears to be with the virtualized list from React Window library <Grid /> component

If other UI is hovered / or scrolled down so selected icon is not visible you are able to select again but then the entire list is in an infinite rendering cycle. Issue may not be with react-window library itself but in how we are implementing it?

https://github.com/grafana/grafana/assets/22381771/90c9dbe6-f6a3-436e-983f-e2f113bec04a

### PR DESCRIPTION
**Pull request by adela-almasan**
Before

https://github.com/grafana/grafana/assets/88068998/3366054e-b4c7-4382-8ae2-a116f7fa5a58

After

https://github.com/grafana/grafana/assets/88068998/7543a435-cef0-4706-b62f-42edf9a8829b

Fixes #67941

**Special notes for your reviewer:**
- Not sure if also a regression/happens just to me - seems to look different in the original video..

Screenshot

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by nmarrs — APPROVED** [review]
✨✨✨

File: public/app/features/dimensions/editors/ResourceCards.tsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ interface CellProps {
   };
 }
 
-function Cell(props: CellProps) {
+const MemoizedCell = memo(function Cell(props: CellProps) {
```
Comment (nmarrs) [inline public/app/features/dimensions/editors/ResourceCards.tsx:24]: was it clear whether or not this issue was caused by React18 in your troubleshooting? just curious

Comment (adela-almasan) [reply public/app/features/dimensions/editors/ResourceCards.tsx:24]: Not really clear tbh, I was curious too if something is different with `memo()` in React18 but couldn't find anything specific. I've just always used it at component level..
