### PR TITLE
Alerting: Fix flaky integration test

### LINKED ISSUE #49112: Alerting: Flaky test - TestPrometheusRulesPermissions
**What happened**:

TestPrometheusRulesPermissions in `/pkg/tests/api/alerting/api_prometheus_test.go` failed intermittently, causing incorrect build failures.

The build in question: https://drone.grafana.net/grafana/grafana/62058/2/10

The reason is that the test is asserting on a very large JSON object, containing two rule groups. The API decided to return the rule groups in a different order (this endpoint does not guarantee order) so the JSON did not match, even though the correct objects were returned.

Generally, tests shouldn't assert on large JSON blobs like this, because such tests are very brittle.

**What you expected to happen**:

The test should be tolerant of APIs that do not guarantee order in objects.

**How to reproduce it (as minimally and precisely as possible)**:

Run the test a lot? (it is up to the database to pick the order, so it may reproduce on some machines but not others)

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

### PR DESCRIPTION
**Pull request by alexweav**
**What this PR does / why we need it**:

Fixes test flakiness in some authz-related integration tests.

These tests previously asserted on raw JSON strings. However, the API did not guarantee order of returned results, so the test could intermittently fail because the order no longer matched what was in the expected JSON string.

Sort the returned records, to prevent this. Also, avoid asserting on every single field in the JSON, which makes the test much less brittle.

**Which issue(s) this PR fixes**:

Fixes #49112

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/tests/api/alerting/api_prometheus_test.go [hunk 1]
```diff
@@ -671,58 +672,16 @@ func TestPrometheusRulesPermissions(t *testing.T) {
...
-			"lastEvaluation": "0001-01-01T00:00:00Z",
-			"evaluationTime": 0
-		}]
-	}
-}`, string(b))
+		body := asJson(t, b)
+		// Sort, for test consistency.
+		sort.Slice(body.Data.Groups, func(i, j int) bool { return body.Data.Groups[i].File < body.Data.Groups[j].File })
+		require.Equal(t, "success", body.Status)
+		// The request should see both groups, and all rules underneath.
```
Comment (alexweav) [inline pkg/tests/api/alerting/api_prometheus_test.go:679]: The test is just trying to make sure the right records are visible based on the authz settings. Assert only this and nothing more. (otherwise, adding new fields to rule groups would break this test, and that shouldn't matter)

File: pkg/tests/api/alerting/api_prometheus_test.go [hunk 2]
```diff
@@ -671,58 +672,16 @@ func TestPrometheusRulesPermissions(t *testing.T) {
...
-				"lastEvaluation": "0001-01-01T00:00:00Z",
-				"evaluationTime": 0
-			}],
-			"interval": 60,
-			"lastEvaluation": "0001-01-01T00:00:00Z",
-			"evaluationTime": 0
-		}]
-	}
-}`, string(b))
+		body := asJson(t, b)
```
Comment (alexweav) [inline pkg/tests/api/alerting/api_prometheus_test.go:675]: There are a couple other tests in this file which assert in the same way. If we like this, I can propagate it to the other tests too.

**Comment by yuri-tceretian** [comment]
Can we do cmp.Diff for the expected and actual results? Diff can handle different order

**Comment by alexweav** [comment]
IMO this approach fixes a second issue - asserting on the same full response JSON across many tests is brittle, because the test can fail for many reasons. It doesn't add any extra coverage, but still requires update often. Adding a new field to a model shouldn't logically break the authz on a route, but the authz tests end up failing anyway.

**Review by yuri-tceretian — APPROVED** [review]
LGTM
