### PR TITLE
Explore: Fix query editors on mobile

### LINKED ISSUE #24916: Explore: Query field very narrow on mobile
**What happened**:
Loki query field in Explore is very narrow on mobile:
image

**What you expected to happen**:
To be able to see the input in the query field and push elements to the right to new row (responsive).

**Environment**:
- Grafana version: 7.0.0
- User OS & Browser: Chrome for iOS

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
Fixes following Query Editors on mobile/tablet screens:

- **Loki**
- **Prometheus**

I have checked also **Elastic**, **Graphite** and **Influx** and all are usable on mobile devices (influx is broken on Iphone SE-size of screens, but any larger screen works - not sure if we want to do anything about this). 

**Before update:**

**Updated Loki and Prometheus:** 
Kapture 2020-05-27 at 14 47 04
Kapture 2020-05-27 at 14 44 34

**Which issue(s) this PR fixes**:

Fixes  #24916

### CODE REVIEW

File: public/app/plugins/datasource/loki/components/LokiExploreExtraField.tsx [hunk 1]
```diff
@@ -17,12 +17,12 @@ export function LokiExploreExtraField(props: LokiExploreExtraFieldProps) {
   const { label, onChangeFunc, onKeyDownFunc, value, type, min } = props;
 
   return (
-    <div className="gf-form-inline explore-input--ml">
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/loki/components/LokiExploreExtraField.tsx:20]: This class only added a 4px right-margin to LokiExploreExtraField component. I have removed it and instead of that added  4px left-margin to the div wrapping Query field. This keeps all fields aligned at the beginning of the row.

Comment (ivanahuckova) [inline public/app/plugins/datasource/loki/components/LokiExploreExtraField.tsx:20]: This class only added a 4px right-margin to LokiExploreExtraField component. I have removed it and instead of that added 4px left-margin to the div wrapping Query field. This keeps all fields aligned at the beginning of the row.

File: public/app/plugins/datasource/loki/components/LokiExploreExtraField.tsx [hunk 2]
```diff
@@ -17,12 +17,12 @@ export function LokiExploreExtraField(props: LokiExploreExtraFieldProps) {
...
+    <div className="gf-form-inline">
       <div className="gf-form">
-        <InlineFormLabel width={6}>{label}</InlineFormLabel>
+        <InlineFormLabel width={5}>{label}</InlineFormLabel>
         <input
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/loki/components/LokiExploreExtraField.tsx:23]: Same size as Prometheus Step editor.

File: public/app/plugins/datasource/loki/components/LokiQueryFieldForm.tsx [hunk 3]
```diff
@@ -152,7 +152,7 @@ export class LokiQueryFieldForm extends React.PureComponent<LokiQueryFieldFormPr
 
     return (
       <>
-        <div className="gf-form-inline gf-form-inline--nowrap flex-grow-1">
+        <div className="gf-form-inline gf-form-inline--xs-view-flex-column flex-grow-1">
           <div className="gf-form flex-shrink-0">
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/loki/components/LokiQueryFieldForm.tsx:156]: Remove nowrap. Instead of that, add custom class which changes flex-direction to column when we hit 'xs' breaking point.

File: public/app/plugins/datasource/loki/components/LokiQueryFieldForm.tsx [hunk 4]
```diff
@@ -164,7 +164,7 @@ export class LokiQueryFieldForm extends React.PureComponent<LokiQueryFieldFormPr
               {chooserText}
             </ButtonCascader>
           </div>
-          <div className="gf-form gf-form--grow flex-shrink-1">
+          <div className={'gf-form gf-form--grow flex-shrink-1 min-width-15 explore-input-margin'}>
             <QueryField
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/loki/components/LokiQueryFieldForm.tsx:168]: Add min-width so QueryField and doesn't shrink to nothing. `explore-input-margin` adds right margin to query editors that have extra field.

File: public/sass/components/_slate_editor.scss [hunk 5]
```diff
@@ -16,7 +20,7 @@
   color: $text-color;
   background-color: $input-bg;
   background-image: none;
-  border: $panel-border;
+  border: $input-border;
```
Comment (ivanahuckova) [inline public/sass/components/_slate_editor.scss:23]: small not-relevant fix to have query field's border the same color as the rest of the inputs.

File: public/sass/pages/_explore.scss [hunk 6]
```diff
@@ -263,6 +263,9 @@
   display: flex;
   position: relative;
   align-items: flex-start;
+  @include media-breakpoint-down(sm) {
+    flex-wrap: wrap;
+  }
```
Comment (ivanahuckova) [inline public/sass/pages/_explore.scss:269]: class is only used in QueryRow so it doesn't affect anything else. When we hit 'sm' breakpoint, wrap Query Action Buttons if necessary.

File: public/app/plugins/datasource/loki/components/LokiQueryFieldForm.tsx [hunk 7]
```diff
@@ -164,7 +164,7 @@ export class LokiQueryFieldForm extends React.PureComponent<LokiQueryFieldFormPr
               {chooserText}
             </ButtonCascader>
           </div>
-          <div className="gf-form gf-form--grow flex-shrink-1">
+          <div className={'gf-form gf-form--grow flex-shrink-1 min-width-15 explore-input-margin'}>
```
Comment (zoltanbedi) [inline public/app/plugins/datasource/loki/components/LokiQueryFieldForm.tsx:167]: Just a small nitpick. I'd use this prop as a string like this
```suggestion
          <div className="gf-form gf-form--grow flex-shrink-1 min-width-15 explore-input-margin">
```

**Review by zoltanbedi — APPROVED** [review]
good job! 🎡

File: public/app/plugins/datasource/loki/components/LokiQueryFieldForm.tsx (hunk 7 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/components/LokiQueryFieldForm.tsx]: Nice catch!
