### PR TITLE
Folders: Editors should be able to edit name and delete folders

### LINKED ISSUE #25532: Folders: Editors should not be able to create folders with editors_can_admin is set to false
**What happened**:
Users with the "Editor" role are able to create dashboard folders but are unable to edit or delete them. I think this should be possible and is also an usability bug.

See the recording:
Peek 2020-06-11 10-56

**What you expected to happen**:
Editors can rename or delete folders. At least the folders they create on their own should be editable for them to correct e.g. typos in the folder name.

**How to reproduce it (as minimally and precisely as possible)**:
- Authenticate as user with "Editor" role.
- Create folder.
- Try to edit folder.

**Anything else we need to know?**:
I've been using LDAP authentication.

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: no datasource
- OS Grafana is installed on: Offical Alpine Docker container
- User OS & Browser: Windows 7, Google Chrome 80.0.3987.100
- Grafana plugins: no extra plugins
- Others: -

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #25532

Potential fix for this issue. Seems like the UI and backend have long been out of sync (even potentially as far back as v5). Where the backend
allowed editors to create, edit and delete folders (not edit permissions though), but the frontend required Admin permissions to show the settings page (where delete action is).

This updates the UI to to use the canEdit flag to determine if the settings tab should be shown.

### CODE REVIEW

File: public/app/features/search/loaders.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import { backendSrv } from 'app/core/services/backend_srv';
-import { NavModel } from '@grafana/data';
+import { NavModel, NavModelItem } from '@grafana/data';
```
Comment (dsotirakis) [inline public/app/features/search/loaders.ts:2]: This one's not used in case you missed it :)

**Comment by dsotirakis** [comment]
LGTM, seems to have the appropriate behaviour now. Tested with both true/false `editors_can_admin` and I can see the expected behaviour! Now it's a matter of discussion / refining if this fix is closing the issue, or if we should also consider [this one](https://github.com/grafana/grafana/issues/25532#issuecomment-726127167)?

**Comment by torkelo** [comment]
@dsotirakis what do you mean consider #25532 ? you mean not allowing editors to create folders instead?

**Comment by dsotirakis** [comment]
Yes, sorry wasn't clear. Is there something we should look at? Like when the flag is set to false, the editor also shouldn't be able to create a folder? (like having viewer's permissions)

File: public/app/features/search/loaders.ts [hunk 2]
```diff
@@ -39,19 +39,25 @@ export const loadFolderPage = (uid: string, activeChildId: string) => {
...
-      const permTab = navModel.main.children!.find((child: any) => child.id === 'manage-folder-permissions');
-      permTab!.url = folderUrl + '/permissions';
+      navModel.main.children.push(permTab);
+    }
 
-      const settingsTab = navModel.main.children!.find((child: any) => child.id === 'manage-folder-settings');
-      settingsTab!.url = folderUrl + '/settings';
-    } else {
-      navModel.main.children = [dashTab!];
+    if (folder.canEdit) {
```
Comment (marefr) [inline public/app/features/search/loaders.ts:59]: Think this should be `canSave`. Otherwise settings tab would be shown for viewers when viewers_can_edit is enabled. Ref: https://github.com/grafana/grafana/blob/85e186cf10b0d672be5ee17f906f19efb765889b/pkg/services/guardian/guardian.go#L48-L58

```suggestion
    if (folder.canSave) {
```

**Review by marefr — CHANGES_REQUESTED** [review]
Looks good. Added a suggestion. 

Also found some glitch when navigating to folder settings tab with editor org role the permission tab is shown. Clicking on that yields a permission denied message:
image

**Comment by torkelo** [comment]
Had to redo the frontend bit so we share the nav model build, was duplicated with the dashboard list page and settings page. Now it's only one. And changed to canSave

**Review by marefr — APPROVED** [review]
LGTM

**Comment by torkelo** [comment]
@marefr do you know if we have to update docs for this change or is this change in accordance with the current docs?

**Comment by marefr** [comment]
@torkelo at least first section of this page: https://grafana.com/docs/grafana/latest/permissions/dashboard_folder_permissions/#dashboard-and-folder-permissions

@grafana/docs-squad anything to add?

**Review by osg-grafana — APPROVED** [review]
