### PR TITLE
AzureMonitor: Automate location retrieval

### LINKED ISSUE #58990: Azure Monitor datasource is not listing all available metrics in Azure GovCloud
**What happened**:

When using the Azure Monitor datasource some metrics are missing in GovCloud.  Specifically the ones we noticed missing are the kubernetes related metrics because that's really all we use but there may be others.

**What you expected to happen**:

The same metrics to be available between Azure and Azure GovCloud. 

**How to reproduce it (as minimally and precisely as possible)**:

See attached gifs

**Anything else we need to know?**:

I spent a couple of hours with Azure support verifying that this was not an issue on their end and that it was not a permissions problem with the service principal we are using.  We went as far as giving the service principal the Contributor role on the subscription which is then inherited down to the kubernetes service and that did not make a difference.  When using developer tools in the browser you can actually see that the information is returned for the kubernetes services however it is not given as an option in the UI in grafana 8.x.

It is also not given as an option in grafana 9.x but in 9.x you have the Advanced menu where you can manually enter in all the values and if we do that then we do get the kubernetes related metrics that we are looking for, this confirms that the service principal has the proper permissions and that the metrics exist, they are just not being given as an option for some reason.

The other odd thing with 9.x is that the only Types that are being shown are related to DNS so there seems to be some odd scoping or something going on there.  This doesn't happen in 8.x

**Environment**:
- Grafana version: 8.0.6 and 9.2.4
- Data source type & version: Azure Monitor
- OS Grafana is installed on: linux kubernetes pod installed via grafana helm chart
- User OS & Browser: OSX, tested in both Chrome and Safari
- Grafana plugins: N/A
- Others: N/A

* In the GIFs I've removed the tenant, subscription and service principal information from the data source configuration screen but the information is there and works.
 
Working metrics in grafana 8 in Azure:
grafana_8_azure_metrics_commercial

No Kubernetes resource type given as an option in grafana 8 in Azure GovCloud:
grafana_8_azure_metrics_govcloud

Working metrics in grafana 9 in Azure:
grafana_9_azure_metrics_commercial

No kubernetes related metrics in grafana 9 in Azure GovCloud (and only DNS related options being shown):
grafana_9_azure_metrics_govcloud1

Manually entering in the required values in grafana 9 in Azure GovCloud and then getting metrics:
grafana_9_azure_metrics_govcloud2

### PR DESCRIPTION
**Pull request by aangelisc**
Locations in Azure Monitor are currently hardcoded. These locations are used to filter available resources using the resource picker. This PR automates the retrieval of the location information whilst also automating the filtering by identifying which locations have support for the `logs` resource type in the `Microsoft.Insights` resource provider.

This should fix #58990, however testing will need to be conducted. 
 
Fixes #58990

### CODE REVIEW

**Review by asimpson — APPROVED** [review]
:+1: nice work on this. The bits using `unionBy` and `Map` are clever :ok_hand: 

:white_check_mark: tests pass

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts [hunk 1]
```diff
@@ -296,4 +299,29 @@ export default class AzureMonitorDatasource extends DataSourceWithBackend<AzureM
 
     return workingQuery;
   }
+
+  async getProvider(providerName: string) {
+    return await this.getResource<AzureMonitorProvidersResponse>(
+      `${routeNames.azureMonitor}/providers/${providerName}?api-version=2021-04-01`
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts:305]: nit: for keeping the current style it may be good to put all api versions in the same place (line 41)

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts [hunk 2]
```diff
@@ -296,4 +299,29 @@ export default class AzureMonitorDatasource extends DataSourceWithBackend<AzureM
...
+
+  async getLocations(subscriptions: string[]) {
+    let locations: AzureMonitorLocations[] = [];
+    for (const subscription of subscriptions) {
+      const subLocations = ResponseParser.parseLocations(
+        await this.getResource<AzureMonitorLocationsResponse>(
+          `${routeNames.azureMonitor}/subscriptions/${subscription}/locations?api-version=2020-01-01`
+        )
+      );
+      locations = unionBy(locations, subLocations, 'name');
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts:317]: nit: I think you can set the Map here to avoid the second loop in line 321

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts [hunk 3]
```diff
@@ -359,4 +363,37 @@ export default class ResourcePickerData extends DataSourceWithBackend<AzureMonit
     }
     this.supportedMetricNamespaces = uniq(supportedMetricNamespaces).join(',');
   }
+
+  async getValidLocations(subscriptions: ResourceRowGroup): Promise<Map<string, AzureMonitorLocations>> {
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:367]: nit: I would call this `getLogsLocations`

**Review by andresmgot — APPROVED** [review]
Some nits here but LGTM!

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts (hunk 1 above)
Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts:305]: At some point I'll do a broader review of API versions to see if we can find some common ones 😊

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts [hunk 4]
```diff
@@ -225,7 +229,7 @@ export default class ResourcePickerData extends DataSourceWithBackend<AzureMonit
     const { data: response } = await this.makeResourceGraphRequest<RawAzureResourceItem[]>(`
       resources
       | where id hasprefix "${resourceGroupId}"
-      ${await this.filterByType(type)} and location in (${logsSupportedLocationsKusto})
+      ${await this.filterByType(type)} and location in (${this.logLocations})
```
[the remark this answers is not in the document]
Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:232]: Good catch!

**Review by andresmgot — APPROVED** [review]
Great, thanks!
