### PR TITLE
CloudWatch Logs: Limit CloudWatch logs queries to use logGroupIdentifiers only for monitoring accounts

### LINKED ISSUE #111504: CloudWatch: Log queries fail when switching between CW data sources
CloudWatch logs queries fail when switching between CloudWatch data sources if the data sources do not have the same access to the queried log group, even if the log group name exists for both of the configured CloudWatch data sources.

Repro:
1. Create a new dashboard
2. Create a CloudWatch log query
3. Run the query to see that it returns data
4. Change the data source to another CloudWatch data source
5. Run the query and it should error with a message like `failed to execute log action with subtype: StartQuery: operation error CloudWatch Logs: StartQuery, https response error StatusCode: 400, RequestID: 97674759-c793-49ee-ae68-fc0eb16020f1, api error AccessDeniedException: User with accountId: xxxxxxxxxxxx is not authorized to perform StartQuery on resources RDSOSMetrics.`
6. (Optional) if the same log group name exists in the selected data source, then clear the log group selection and reselect the log group with the same name. The query should now work.

This happens because the query JSON for log groups saves the ARN of the log group instead of the log group name, so when the data source is changed, the log group that is saved in the query JSON is used as part of the query, but the newly selected data source might not have access to that log group. Even though the log group name might be the same across different AWS accounts, the ARN is not and will cause the error.

Note, this happens with data source variables as well.

Expected outcome:
CloudWatch logs queries should work when switching between CloudWatch data sources configured for two different AWS accounts, if both of those data sources have access to the same log group name even though the log group ARNs are different.

### PR DESCRIPTION
**Pull request by kevinwcyu**
**What is this feature?**

This PR makes it so CloudWatch logs queries use the [logGroupIdentifiers](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_StartQuery.html#CWL-StartQuery-request-logGroupIdentifiers) parameter only when the data source is configured as a monitoring account for the region of the query.

Otherwise, logs queries will use the [logGroupName](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_StartQuery.html#CWL-StartQuery-request-logGroupNames) parameter.

**Why do we need this feature?**

Previously, we always used the `logGroupName` parameter for logs queries. When Cross-Account Observability was introduced, we switched over to using `logGroupIdentifiers` for all newly created queries when cross account observability was enabled.

However, this caused issues for dashboards that were designed to work across different accounts. For example, a dashboard could be set to query a log group `my-apps-log-group`. This log group could exist in multiple different AWS accounts such as `dev-aws-account` and `prod-aws-account`. Users could create a dashboard using the `my-apps-log-group` with a data source for `dev-aws-account` and switch to using a data source for `prod-aws-accout` and it would work. But it would not work if they had cross account observability enabled on their instance because it would use the `logGroupIdentifiers` to query for logs. This would cause errors because `logGroupIdentifiers` uses the ARN of a log group, which includes the account number and region in it meaning the query can only work for the account the log group belongs to.

This PR makes it so only monitoring account data sources use the `logGroupIdentifiers` parameter for querying logs. That way previously created dashboards can continue using the previous behaviour, without needing to disable cross account observability for the entire instance.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #111504

**Special notes for your reviewer:**

You can test this by have 2 different CloudWatch data sources set up in different accounts. Create a new logs query (the default query is fine) and select the `RDSOSMetrics` log group (this log group was available for external dev and the "AWS CloudWatch" provisioned data source. When you switch between the two data sources, the query should continue to run fine while fetching data for the selected data source. You can either switch the data source from the panel, or use a data source variable to switch the data source.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: pkg/tsdb/cloudwatch/cloudwatch.go [hunk 1]
```diff
@@ -53,9 +54,10 @@ type DataSource struct {
 	ProxyOpts         *proxy.Options
 	AWSConfigProvider awsauth.ConfigProvider
 
-	logger          log.Logger
-	tagValueCache   *cache.Cache
-	resourceHandler backend.CallResourceHandler
+	logger                 log.Logger
+	tagValueCache          *cache.Cache
+	resourceHandler        backend.CallResourceHandler
+	monitoringAccountCache sync.Map
```
Comment (kevinwcyu) [inline pkg/tsdb/cloudwatch/cloudwatch.go:60]: Should I make this a `*cache.Cache` like `tagValueCache` above? That would allow setting a `ttl` for this, although I don't believe this really changes unless the AWS account has cross account observability turned off for it.

File: pkg/tsdb/cloudwatch/log_actions.go [hunk 2]
```diff
@@ -213,17 +213,50 @@ func (ds *DataSource) executeStartQuery(ctx context.Context, logsClient models.C
...
+					ds.logger.FromContext(ctx).Debug("failed to determine monitoring account status", "err", err)
+				} else if isMonitoringAccount {
+					// monitoring accounts require querying by log group identifiers because log group names are not unique across accounts.
+					var logGroupIdentifiers []string
+					for _, lg := range logsQuery.LogGroups {
+						// due to a bug in the startQuery api, we remove * from the arn, otherwise it throws an error
+						arn := strings.TrimSuffix(lg.Arn, "*")
+						logGroupIdentifiers = append(logGroupIdentifiers, arn)
+					}
+					if len(logGroupIdentifiers) > 0 {
```
Comment (idastambuk) [inline pkg/tsdb/cloudwatch/log_actions.go]: won't `logGroupIdentifiers.length` always be >0 in this block if LogGroups.length > 0?

**Review by idastambuk — APPROVED** [review]
Great improvement!

File: pkg/tsdb/cloudwatch/log_actions.go (hunk 2 above)
Comment (kevinwcyu) [reply pkg/tsdb/cloudwatch/log_actions.go]: nice catch!

File: pkg/tsdb/cloudwatch/cloudwatch.go (hunk 1 above)
Comment (njvrzm) [reply pkg/tsdb/cloudwatch/cloudwatch.go:60]: I think sync.Map is fine here for now - it seems unlikely this would change, and we find that it does I think just re-saving the datasource should be a workaround until we can fix it.

File: pkg/tsdb/cloudwatch/log_actions.go [hunk 3]
```diff
@@ -213,17 +213,48 @@ func (ds *DataSource) executeStartQuery(ctx context.Context, logsClient models.C
...
+						logGroupIdentifiers = append(logGroupIdentifiers, arn)
+					}
+					startQueryInput.LogGroupIdentifiers = logGroupIdentifiers
+					useLogGroupIdentifiers = true
+				}
+			}
+		}
+
+		if !useLogGroupIdentifiers {
+			// even though logsQuery.LogGroupNames is deprecated, we still need to support it for backwards compatibility and alert queries
```
Comment (njvrzm) [inline pkg/tsdb/cloudwatch/log_actions.go:242]: It worries me a bit to keep using a deprecated parameter, since that suggests it will be removed at some point. Could we - probably in a later PR - keep a map of log group name and region -> log group identifier, so we can stop using this?

File: pkg/tsdb/cloudwatch/cloudwatch.go [hunk 4]
```diff
@@ -262,6 +264,33 @@ func (ds *DataSource) getRGTAClient(ctx context.Context, region string) (resourc
 	return NewRGTAClient(cfg), nil
 }
 
+func (ds *DataSource) isMonitoringAccount(ctx context.Context, region string) (bool, error) {
```
Comment (njvrzm) [inline pkg/tsdb/cloudwatch/cloudwatch.go:267]: I'm curious - is status as a monitoring account tied to region? I would have thought an account was either a monitoring account or not.

File: pkg/tsdb/cloudwatch/cloudwatch.go (hunk 1 above)
Comment (njvrzm) [reply pkg/tsdb/cloudwatch/cloudwatch.go:60]: I think we're fine leaving this without a TTL for now. It seems unlikely this will change often enough to be an issue, and if we find that it does come up, I think resaving the datasource would be a workaround until we can fix it.

**Review by njvrzm — APPROVED** [review]
Good stuff! no blocking comments, a couple of questions.

File: pkg/tsdb/cloudwatch/cloudwatch.go (hunk 4 above)
Comment (kevinwcyu) [reply pkg/tsdb/cloudwatch/cloudwatch.go:267]: yea, according to https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account.html "With Amazon CloudWatch cross-account observability, you can monitor and troubleshoot applications that span multiple accounts **within a Region**" and also "Each account can have **one sink per Region**." so the sink being the monitoring account is per region, but you can create multiple sinks.

File: pkg/tsdb/cloudwatch/log_actions.go (hunk 3 above)
Comment (kevinwcyu) [reply pkg/tsdb/cloudwatch/log_actions.go:242]: `logsQuery.LogGroupNames` is a parameter we define so we can control when it's removed. as for keeping a map of log group name and region -> log group identifier, i don't think we could do that unless we could update any log queries that are used in alerts, or provisioned dashboards as well. my initial thoughts right now are that we'll probably have to keep `logsQuery.LogGroupNames` to continue supporting those existing queries.

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/19149773613)
- Version: 12.4.0-19149773613
