### PR TITLE
DashboardScene: Fixes issues with relative time range in panel edit

### LINKED ISSUE #86420: DashboardScene: Migration - Relative time range override does not work in panel edit
Dashboard (gdev): [Panel Tests - Relative time zone support](http://localhost:3000/d/d41dbaa2-a39e-4536-ab2b-caca52f1a9c8/panel-tests-relative-time-zone-support)

Possible error location: PanelTimeRange (SceneTimeRange) — object that should be use by scene query runner 

Old arch:
Screenshot 2024-04-12 at 11 30 33

Scenes:
Screenshot 2024-04-12 at 11 31 18

### PR DESCRIPTION
**Pull request by torkelo**
Fixes https://github.com/grafana/grafana/issues/86420 '

This one was very hard to solve, tried so many different ways that all ended up with some dead end. 

The original problem was the "Table view" toggle in panel edit, this switching the rendering of the visualization from the main VizPanel to a temporary table view. But for this temporary table VizPanel to get the data we moved the SceneQueryRunner from VizPanelManager.state.panel to VizPanelManager level (so that it's children all get the data). We could of course clone the main VizPanel SceneQueryRunner to this temporary table VizPanel but this disconnects the queries tab from the table view as the queries tab is subscribing to the main viz scene query runner (and we want changes to queries to reflect in the table view). 

But moving SceneQueryRunner to VizPanelManager level left the time range on the main VizPanel level, so the SceneQueryRunner did not get local panel time range. I tried moving the time range also to VizPanelManager level but then we do not get any rendering of the local time range in the panel chrome header (Which only happens when VizPanel render detects $timeRange on it's local level). 

Ok, lets revert back to SceneQueryRunner living on the main VizPanel level (same as time range), so back to square one. How to switch to Table view and maintain the same SceneQueryRunner between main viz and queries tab? Well, we could break the rule of reusing the same SceneObject instance, when we switch to TableView I use the same instance of the SceneQueryRunner as the main VizPanel. 

One last issue, the SceneQueryRunner is deactivated because it's attached to the main VizPanel and this is not rendered when the table view is rendered, when deactivated it clears all subscriptions so the queries tab which is subscribing to it via `useState()` no longer get's any updates after this. 

To fix this I make sure the queries tab calls the queryRunner activate function (which increments the refCount for main viz SceneQueryRunner so that it does not deactivate during the transition from main VizPane and Table VizPanel). 

I know, messy, complex, don't like it, but best I can come up with for now.

### CODE REVIEW

File: public/app/features/dashboard-scene/panel-edit/VizPanelManager.tsx [hunk 1]
```diff
@@ -379,6 +377,8 @@ export class VizPanelManager extends SceneObjectBase<VizPanelManagerState> {
         .setTitle('')
         .setOption('showTypeIcons', true)
         .setOption('showHeader', true)
+        // this needs to use same instance as the queries tab is subscribing to it
+        .setData(this.queryRunner)
```
Comment (dprokop) [inline public/app/features/dashboard-scene/panel-edit/VizPanelManager.tsx:381]: @torkelo, this will change the parent of the query runner. It should be fine as we are in the panel edit context, so the parent should not really matter.  But maybe it would be worth mentioning it.

But the main problematic part here is that the table view should get the `SceneDataTransformer`, otherwise it shows the non-trasnfromed query results. In the old arch the table view respects transformations.

Comment (torkelo) [reply public/app/features/dashboard-scene/panel-edit/VizPanelManager.tsx]: @dprokop good catch! pushed a fix for that

**Review by mdvictor — APPROVED** [review]
Tested this out and works well!

**Review by dprokop — APPROVED** [review]
