### PR TITLE
TimeRange: Fixes issue when zooming out on a timerange with timespan 0

### LINKED ISSUE #47186: Time picker: zoom out on zero-width range does nothing
**What happened**:
Clicking on the magnifying glass does nothing, if the 'from' and 'to' times are equal.

https://user-images.githubusercontent.com/8125524/161247287-354d77ea-f7a6-4ed1-93d5-8cd5dc881d69.mp4

**What you expected to happen**:
I expected it to zoom out a little, maybe 20 seconds.

**How to reproduce it (as minimally and precisely as possible)**:
Select an absolute time range.
Make the end time the same as the start time.

**Anything else we need to know?**:
I did this because I was trying to select logs from a point in a metric panel, via the 'Data Link' function.

**Environment**:
Grafana version: 8.5.0-a2463818pre
User OS & Browser: MacOS 11.6.1; Chrome Version 99.0.4844.74 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by JoaoSilvaGrafana**
**What this PR does / why we need it**:

On the timerange, if you zoom out from a range that has the same as start/end, it stays withe same range, because if you multiply the timespan of 0 by any factor it will remain 0... So we are forcing a zoom out from a range of 0 to be 30s.

**Which issue(s) this PR fixes**:

Fixes #47186

**Special notes for your reviewer**:

Chose 30s because then as you continue a zoom out it stays logical enough: 1m, 2m, 4m... Open to alternatives though.

### CODE REVIEW

File: public/app/core/utils/timePicker.ts [hunk 1]
```diff
@@ -30,9 +30,11 @@ export const getShiftedTimeRange = (direction: number, origRange: TimeRange): Ab
 export const getZoomedTimeRange = (range: TimeRange, factor: number): AbsoluteTimeRange => {
   const timespan = range.to.valueOf() - range.from.valueOf();
   const center = range.to.valueOf() - timespan / 2;
+  // If the timepsan is 0, zooming out would do nothing, so we force a zoom out to 30s
+  let newTimespan = timespan === 0 ? 30000 : timespan * factor;
```
Comment (ashharrison90) [inline public/app/core/utils/timePicker.ts:34]: minor nit: can this be a `const`?

**Review by ashharrison90 — APPROVED** [review]
looks great 🙌

File: public/app/core/utils/timePicker.ts (hunk 1 above)
Comment (JoaoSilvaGrafana) [reply public/app/core/utils/timePicker.ts:34]: Oh yeah! I played around with different ways of writing this and then forgot to change this to a const when it wasn't changed anymore 🙃
