### PR TITLE
ConditionalRendering: Fix for repeated items

### LINKED ISSUE #108340: Dynamic Dashboards: Show/hide rules for repeating panels not applied individually
### What happened?

Created a new Grafana 12.0.0 instance and enabled the Dynamic Dashboards feature in the grafana.ini config. Created a new dashboard with a variable that contained a list of values. Created a new panel that repeated on that variable that queried a datasource. The first variable panel returns "No data" but the second panel returns time series data. Create a "Show/Hide rule" that hides the panel if "No data" is returned from the Query result. All repeated panels are hidden even if they have data.

### What did you expect to happen?

I expected the show/hide rule to apply individually to each repeated panel since each panel makes it's own query based on the repeat variable. In my example, only the first repeated panel would be hidden and the second panel with data would still show.

### Did this work before?

I do not believe this has worked before since Grafana 12 is what introduced this feature.

### How do we reproduce it?

1. Create a dashboard with a variable that uses a datasource that returns partial "No data" and data
2. Create a repeating panel that uses the variable
3. Create a Show/Hide rule to Hide the panel if "No data" is found
4. All repeated panels will be hidden

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 12.0.0
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by grafakus**
**What is this feature?**

A fix to prevent all repeated items to be hidden/shown when only the first panel should be hidden/shown.

This happens because, before this PR, the conditional rendering was evaluated at the container level (`AutoGridItem`) and its single boolean result was applied to all repeats. So if the source panel hid, all repeated panels hid.

This PR makes sure that the conditional rendering is evaluated for each panel. This is done by cloning the `ConditionalRenderingGroup` and making it target-aware so that each condition evaluates against the specific panel. The group then combines the results per target, and the renderer reads the per‑panel visibility.

The fix is also applied to repeated tabs and rows.

**Why do we need this feature?**

Bugfix

**Who is this feature for?**

All dynamic dashboard users

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/108340

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard-scene/conditional-rendering/hooks/useIsConditionallyHidden.tsx [hunk 1]
```diff
@@ -14,11 +14,29 @@ function getPlaceholderConditionalRendering(): ConditionalRenderingGroup {
...
-      : getPlaceholderConditionalRendering();
+export function useIsConditionallyHidden(
+  scene: SceneObject,
+  itemIdx?: number
+): [boolean, string | undefined, ReactNode | null, boolean] {
+  let conditionalRenderingToRender = getPlaceholderConditionalRendering();
+
+  if (itemIdx !== undefined) {
+    if (
+      'repeatedConditionalRendering' in scene.state &&
```
Comment (idastambuk) [inline public/app/features/dashboard-scene/conditional-rendering/hooks/useIsConditionallyHidden.tsx]: nit: could we extract this condition into a function to make it more readable? something like `isConditionalRenderingGroupItem` (or a better name 😅)

**Review by oscarkilhed — APPROVED** [review]

File: public/app/features/dashboard-scene/conditional-rendering/hooks/useIsConditionallyHidden.tsx (hunk 1 above)
Comment (grafakus) [reply public/app/features/dashboard-scene/conditional-rendering/hooks/useIsConditionallyHidden.tsx]: Fixed in https://github.com/grafana/grafana/pull/114160/commits/f3f018e5fae39126b4f0fbdf7988c65410f9c773 I chose to pass directly the `ConditionalRenderingGroup` (no more type assertion needed)

**Review by idastambuk — APPROVED** [review]

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/19734150546)
- Version: 12.4.0-19734150546
