### PR TITLE
SingleStat: use DataFrame results rather than TimeSeries/TableData

### LINKED ISSUE #18536: SingleStat does not work with DataFrame
If a datasource plugin returns a DataFrame, the "stat" option (avg, min, max) for single stats is missing.

This coding seems related to the issue:
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/module.ts#L130-L138

https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/editor.html#L6-L17

Screenshot 2019-08-13 at 15 28 16

**Environment**:
- Grafana version: docker run --rm --name=grafana -p 3000:3000 grafana/grafana:master
- Data source type & version: TestDatasource streaming client
- OS Grafana is installed on: mac
- User OS & Browser: chrome
- Grafana plugins: singlestat

### PR DESCRIPTION
**Pull request by ryantxu**
fixes #18536

This tries to move as much logic out of the angular panel and use the same calculations as the new react panels.

TODO:
- [x] migrate field mapping calculations
- [x] get tests passing

Changes:
previously, when in table mode I think it assumed showing the first value.  Now it lets you pick a field and the reducer:
image

See also #18581

### CODE REVIEW

File: packages/grafana-ui/src/utils/displayValue.ts [hunk 1]
```diff
@@ -58,6 +58,14 @@ export function getDisplayProcessor(options?: DisplayValueOptions): DisplayProce
...
           const { decimals, scaledDecimals } = getDecimalsForValue(value, field.decimals);
           text = formatFunc(numeric, decimals, scaledDecimals, options.isUtc);
+
+          // Check if the formatted text mapped to a different value
+          if (mappings && mappings.length > 0) {
+            const mappedValue = getMappedValue(mappings, text);
+            if (mappedValue) {
+              text = mappedValue.text;
+            }
+          }
```
Comment (ryantxu) [inline packages/grafana-ui/src/utils/displayValue.ts]: Without this change, this tests fails:
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/specs/singlestat.test.ts#L191

Essentially 9.9 gets changed to 10 in the formatFunc... and we need to map 10 > OK

File: public/app/plugins/panel/singlestat/module.ts [hunk 2]
```diff
@@ -378,19 +310,62 @@ class SingleStatCtrl extends MetricsPanelCtrl {
     this.panel.rangeMaps.push({ from: '', to: '', text: '' });
   }
 
+  /**
```
Comment (ryantxu) [inline public/app/plugins/panel/singlestat/module.ts]: We could move this process to `handleDataFrame(...)`, but would need to update the editor to call `refresh()` on any settings change rather than `render()` -- I made that change for enabling sparklines already

**Review by torkelo — COMMENTED** [review]
Wow this is a pretty comprehensive change! Looks good but will need quite a bit of manual testing I feel.

File: public/app/plugins/panel/singlestat/module.ts [hunk 3]
```diff
@@ -594,25 +561,29 @@ class SingleStatCtrl extends MetricsPanelCtrl {
...
-        getColorFromHexRgbOrName(
-          color,
-          config.bootData.user.lightTheme ? GrafanaThemeType.Light : GrafanaThemeType.Dark
-        )
-      );
+      if (panel.colors) {
+        data.colorMap = panel.colors.map((color: string) =>
+          getColorFromHexRgbOrName(
+            color,
+            config.bootData.user.lightTheme ? GrafanaThemeType.Light : GrafanaThemeType.Dark
```
Comment (torkelo) [inline public/app/plugins/panel/singlestat/module.ts]: = config.theme.type

**Review by torkelo — COMMENTED** [review]
feel pretty good about this, did some more testing and looks good. 

I did find one thing that the auto decimals logic is not great. values like 2.22235 are shown as 2 but it looks like an unrelated problem to this PR but faulty logic in getDecimalsForValue

**Comment by ryantxu** [comment]
> feel pretty good about this

I think it is a good 1/2 step towards migrating this panel for real.

I'll make a different issue for 2.22235 => 2

**Review by torkelo — APPROVED** [review]
