### PR TITLE
(cloudwatch) fix dimension value suggestion

### LINKED ISSUE #3186: query CPUUtilization metric failed for AWS EC2 instance by imageid
failed to add CPU utilization graph for AWS EC2 instances by image id. the dropdown list always show with the instance id. 

below is screenshot.

### PR DESCRIPTION
**Pull request by mtanda**
fix https://github.com/grafana/grafana/issues/3186

### CODE REVIEW

File: public/app/plugins/datasource/cloudwatch/datasource.js [hunk 1]
```diff
@@ -191,7 +185,20 @@ function (angular, _) {
...
 
-        return this.getDimensionValues(region, namespace, metricName, dimensions);
+        return this.getDimensionValues(region, namespace, metricName, dimensions).then(function(result) {
+          return _.map(result, function(dimensions) {
+            var values = _.chain(dimensions)
+            .sortBy(function(dimension) {
+              return dimension.Name;
+            })
+            .map(function(dimension) {
+              return dimension.Name + '=' + dimension.Value;
```
Comment (torkelo) [inline public/app/plugins/datasource/cloudwatch/datasource.js]: this seems very wrong, why return this? getDimensionValues should return values for the current selected dimension, so getDimensionValues should take a dimension key as parameter. And filtering should be here not in query_ctrl

Comment (mtanda) [inline public/app/plugins/datasource/cloudwatch/datasource.js]: @torkelo 
I agree with your opinion for design perspective.
The reason why I change response format is, I want to support flexible templating.
Without returning dimension name, we can't pass dimesion to GetMetricStatistics() correctly.

The dimension name/value pair is likely primary key of database.
For EC2, the primary key is InstanceId.
For ElastiCache, the primary keys are CacheClusterId and CacheNodeId.
(Please see https://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/CacheMetrics.DimensionsAndSets.html)

To get metrics of ElastiCache, we need to specify both key.

I want to generate each cache node graphs in specified cache cluster, by Panel repeat.
If query editor can parse a template value, the format is "dim_key1=dim_value1,dim_key2=dim_value2...", it is possible.

Comment (mtanda) [inline public/app/plugins/datasource/cloudwatch/datasource.js]: If it is not acceptable, how do you think adding another query expression like following.
dimension_pairs(region,namespace,metrics,...).
This query expression returns the response in "dim_key1=dim_value1,dim_key2=dim_value2..." format.

If it is acceptable, I'll add dimension_key parameter for dimension_values() expression.

Comment (torkelo) [inline public/app/plugins/datasource/cloudwatch/datasource.js]: when and how will that be used? the target.dimensions is an object, can only use templating for the key or for the key value, not both at the same time (for a single variable)

Comment (mtanda) [inline public/app/plugins/datasource/cloudwatch/datasource.js]: @torkelo 
One of the idea is,
Storing "dim_key1=dim_value1,dim_key2=dim_value2..." value to "$dimensions", and expand string like "$dimensions[0].name" to each dimension name/value at this function.
https://github.com/grafana/grafana/blob/32f9f8fcceba3bcfd47bc398e524178019ed2faa/public/app/plugins/datasource/cloudwatch/datasource.js#L279-L286

Or, add input field to query editor, the field can take "dim_key1=dim_value1,dim_key2=dim_value2...".
And, parse this format string, then set(overwrite) dimension keys/values at this line.
https://github.com/grafana/grafana/blob/32f9f8fcceba3bcfd47bc398e524178019ed2faa/public/app/plugins/datasource/cloudwatch/datasource.js#L37

Comment (mtanda) [inline public/app/plugins/datasource/cloudwatch/datasource.js]: To help understanding, I add screen capture of current implementation.
templating_editor
dimension_values

For ElastiCache Redis, we get like following values.
CacheClusterId=cluster-001
CacheClusterId=cluster-001,CacheNodeId=0001
CacheClusterId=cluster-002
CacheClusterId=cluster-002,CacheNodeId=0001

Comment (torkelo) [inline public/app/plugins/datasource/cloudwatch/datasource.js]: I think its wrong to hav this in one template variable, you should have two, one for dimension key and one for value

Comment (mtanda) [inline public/app/plugins/datasource/cloudwatch/datasource.js]: If user want to get InstanceId list, fill in regex field like this.
instance_ids

Comment (mtanda) [inline public/app/plugins/datasource/cloudwatch/datasource.js]: Ah yes, I want to separate these if possible...

For example, if dimension name/value pairs like this.
CacheClusterId=cluster-001
CacheClusterId=cluster-001,CacheNodeId=0001
CacheClusterId=cluster-001,CacheNodeId=0002
CacheClusterId=cluster-001,CacheNodeId=0003
CacheClusterId=cluster-002
CacheClusterId=cluster-002,CacheNodeId=0001
CacheClusterId=cluster-002,CacheNodeId=0002

And if separete template variable for CacheClusterId and CacheNodeId.
The CacheClusterId variable has "001", "002".
The CacheNodeId variable has "001", "002", "003". (Because, cluster-001 has 003 node.)

From these templating variable, we can't reproduce original dimension name/value pairs.
If using these templating variable for Panel repeating, the Grafana will make "CacheClusterId=cluster-002,CacheNodeId=0003" graph, it is blank!

**Comment by mtanda** [comment]
@torkelo I don't want to leave this problem longer.
So, I add dimensions() query for templating, and fix current dimension_values() query as you told.
Please check this again.

**Comment by torkelo** [comment]
this PR still contain other stuff than just fixing getDimensionValues :(  can you remove the getDimensions function?

**Comment by mtanda** [comment]
@torkelo remove getDimensions().
I intend to use getDimensions() in Scripted Dashboard.
So, I don't give up to merge this to master, I'll open another PR.
Let's talk about the needs of this feature :-)

**Comment by mtanda** [comment]
@torkelo ping

**Comment by mtanda** [comment]
@torkelo would you check this too?

**Comment by mtanda** [comment]
@torkelo I already remove getDimensions() as you request.
> this PR still contain other stuff than just fixing getDimensionValues :( can you remove the getDimensions function?

If there are any problem in this PR, I'll fix it.
Please check this PR.

**Comment by mtanda** [comment]
@torkelo Any chances of merging this? Please tell me your plan.
This is bug fix of https://github.com/grafana/grafana/issues/3186 .
You tagged it, "P3: Important" and "state: help wanted (PR)", yes I help you :-)

File: public/app/plugins/datasource/cloudwatch/datasource.js [hunk 2]
```diff
@@ -173,25 +195,16 @@ function (angular, _) {
         return this.getDimensionKeys(dimensionKeysQuery[1]);
       }
 
-      var dimensionValuesQuery = query.match(/^dimension_values\(([^,]+?),\s?([^,]+?),\s?([^,]+?)(,\s?([^)]*))?\)/);
+      var dimensionValuesQuery = query.match(/^dimension_values\(([^,]+?),\s?([^,]+?),\s?([^,]+?),\s?([^,]+?)(,\s?([^)]*))?\)/);
```
Comment (torkelo) [inline public/app/plugins/datasource/cloudwatch/datasource.js]: the reason it is not merged it mainly this and the dimensionPart split stuff, seems so hacky.

Comment (mtanda) [inline public/app/plugins/datasource/cloudwatch/datasource.js]: @torkelo removed. please check.

Comment (torkelo) [inline public/app/plugins/datasource/cloudwatch/datasource.js]: great! :heart: 
merged!

**Comment by mtanda** [comment]
thanks.

**Comment by mtanda** [comment]
I agree with you, the code is hacky, but it is required for some case.
The dimensionPart might be useful for filtering some dimension like CacheClusterId of ElastiCache.
https://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/CacheMetrics.DimensionsAndSets.html

To get all CacheNodeId in CacheClusterId cluster, it is required.
