### PR TITLE
Fix: Update badges on PanelEditor tabs when adding a query/transformation/alert

### LINKED ISSUE #25196: Adding a query doesn't update the counter on the Query tab
**How to reproduce it (as minimally and precisely as possible)**:

1. Open the editor on any panel.
2. Click '+ Query'.
3. **The query counter doesn't update**.
4. Go to the Transformations or the Alerts tab.
5. **The query counter is incremented** only when you navigate away from the Query tab.

**Environment**:
- Grafana version: v7.0.1
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by peterholmberg**
**What this PR does / why we need it**:
Fixes an issue where the badges on panel editor tabs were not updated when adding a query/transformation/alert
**Which issue(s) this PR fixes**:

Fixes #25196

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx [hunk 1]
```diff
@@ -16,55 +16,79 @@ interface PanelEditorTabsProps {
...
-          const transformations = panel.getTransformations() ?? [];
-          return transformations.length;
-      }
+  componentWillUnmount() {
+    this.props.panel.off(CoreEvents.queryAdded, this.triggerForceUpdate);
+    this.props.panel.off(CoreEvents.queryRemoved, this.triggerForceUpdate);
+    this.props.panel.off(CoreEvents.alertAdded, this.triggerForceUpdate);
+    this.props.panel.off(CoreEvents.alertRemoved, this.triggerForceUpdate);
+    this.props.panel.off(CoreEvents.transformationAdded, this.triggerForceUpdate);
+    this.props.panel.off(CoreEvents.transformationRemoved, this.triggerForceUpdate);
```
Comment (hugohaggmark) [inline public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx:35]: @peterholmberg noticed that e2e tests were complaining with this:
```
(node:20782) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:20782) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
```

I've checked and this is already on master @peterholmberg so this PR hasn't introduce it.

But when I debug this PR and reach `componentWillUnmount` the events array in the emitter is already empty. Could be because Panel has already been destroyed or the props.panel is a different reference? https://github.com/grafana/grafana/blob/17a1e78754a036b2671437e9b59b0734385c74e4/public/app/features/dashboard/state/PanelModel.ts#L454

Not sure what the best way is to register/unregister emitter this without memory leaks in this case, maybe @torkelo @dprokop has suggestions?

Comment (mckn) [reply public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx]: If this is the case maybe we should store the `unsubscribe` functions for each subscription within this panel and run those on unmount instead of the `off`.

File: public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx [hunk 2]
```diff
@@ -16,55 +16,77 @@ interface PanelEditorTabsProps {
...
-  const styles = getPanelEditorTabsStyles();
-  const activeTab = tabs.find(item => item.active)!;
+export class PanelEditorTabs extends PureComponent<PanelEditorTabsProps> {
+  componentDidMount() {
+    const { panel } = this.props;
+    panel.on(CoreEvents.queryAdded, this.triggerForceUpdate);
+    panel.on(CoreEvents.queryRemoved, this.triggerForceUpdate);
+    panel.on(CoreEvents.transformationAdded, this.triggerForceUpdate);
+    panel.on(CoreEvents.transformationRemoved, this.triggerForceUpdate);
+  }
```
Comment (mckn) [inline public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx:26]: If this still would have been a functional component we could have used a `useEffect` hook to handle the unsubscribe of the events.

But in this case we might be able to do something like:

```suggestion
  componentDidMount() {
      const { panel } = this.props;
      this.subscriptions = [
          panel.on(CoreEvents.queryAdded, this.triggerForceUpdate),
          panel.on(CoreEvents.queryRemoved, this.triggerForceUpdate),
          panel.on(CoreEvents.transformationAdded, this.triggerForceUpdate),
          panel.on(CoreEvents.transformationRemoved, this.triggerForceUpdate),
      ];
  }
```

File: public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx [hunk 3]
```diff
@@ -16,55 +16,77 @@ interface PanelEditorTabsProps {
...
-          const transformations = panel.getTransformations() ?? [];
-          return transformations.length;
-      }
+  componentWillUnmount() {
+    const { panel } = this.props;
+    panel.off(CoreEvents.queryAdded, this.triggerForceUpdate);
+    panel.off(CoreEvents.queryRemoved, this.triggerForceUpdate);
+    panel.off(CoreEvents.transformationAdded, this.triggerForceUpdate);
+    panel.off(CoreEvents.transformationRemoved, this.triggerForceUpdate);
+  }
```
Comment (mckn) [inline public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx:34]: And then run the following code to unsubscribe:

```suggestion
  componentWillUnmount() {
    this.subscriptions.forEach(unsubscribe => unsubscribe());
  }
```

File: public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx (hunk 2 above)
Comment (mckn) [reply public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx:26]: I am assuming that the `panel.on` is returning a function to unsubscribe, but that might not be the case?

File: public/app/features/dashboard/state/PanelModel.ts [hunk 4]
```diff
@@ -488,6 +505,14 @@ export class PanelModel implements DataConfigSource {
   getSavedId(): number {
     return this.editSourceId ?? this.id;
   }
+
+  on<T>(event: AppEvent<T>, callback: (payload?: T) => void) {
+    this.events.on(event, callback);
```
Comment (mckn) [inline public/app/features/dashboard/state/PanelModel.ts:510]: So maybe change so we return the `unsubscribe` function here.

**Review by mckn — CHANGES_REQUESTED** [review]
I added some really small nits but over all I think the code looks great!

File: public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx [hunk 5]
```diff
@@ -16,55 +16,77 @@ interface PanelEditorTabsProps {
...
-export const PanelEditorTabs: React.FC<PanelEditorTabsProps> = ({ panel, dashboard, tabs, onChangeTab }) => {
-  const styles = getPanelEditorTabsStyles();
-  const activeTab = tabs.find(item => item.active)!;
+export class PanelEditorTabs extends PureComponent<PanelEditorTabsProps> {
+  componentDidMount() {
+    const { panel } = this.props;
+    panel.on(CoreEvents.queryAdded, this.triggerForceUpdate);
+    panel.on(CoreEvents.queryRemoved, this.triggerForceUpdate);
+    panel.on(CoreEvents.transformationAdded, this.triggerForceUpdate);
+    panel.on(CoreEvents.transformationRemoved, this.triggerForceUpdate);
```
Comment (dprokop) [inline public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx:25]: Wonder if having `queriesChanged`/`transformationsChanged` events wouldn't be sufficient? I suggest this as we are using these events only in this single case, and limiting the number of events would simplify the logic responsible for actually sending those. You would avoid checking whether or not something was added/removed. I think the less code in this case the better:)

**Review by dprokop — CHANGES_REQUESTED** [review]
I think this looks good, but I suggest limiting the number of introduced events as described in the comment. WDYT @mckn @hugohaggmark ?

File: public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx (hunk 5 above)
Comment (peterholmberg) [reply public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx:25]: Hm, yes that's true. Updating

Comment (dprokop) [reply public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx:25]: thank you!

Comment (hugohaggmark) [reply public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx:25]: Great suggestion @dprokop

File: public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx (hunk 1 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx]: Didn't know it returned an `unsubscribe` function, that would be a better approach indeed!

File: public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx (hunk 5 above)
Comment (peterholmberg) [reply public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx]: It seems like the CI agreed! :smile:

Comment (dprokop) [reply public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx]: hahah, yeah!

**Review by dprokop — APPROVED** [review]
🥳

**Comment by mckn** [comment]
> I think this looks good, but I suggest limiting the number of introduced events as described in the comment. WDYT @mckn @hugohaggmark ?

My suggestion is that we merge this one as it is but open an issue at investigating that we unsubscribe properly after adding an event subscription. Seems like there is some missmatch in panel vs component lifecycle.

**Comment by mckn** [comment]
> > I think this looks good, but I suggest limiting the number of introduced events as described in the comment. WDYT @mckn @hugohaggmark ?
> 
> My suggestion is that we merge this one as it is but open an issue at investigating that we unsubscribe properly after adding an event subscription. Seems like there is some missmatch in panel vs component lifecycle.

Opened this one: https://github.com/grafana/grafana/issues/27800

**Review by mckn — APPROVED** [review]
