### PR TITLE
Alerting: Improve Prometheus Alert Rule error message

### LINKED ISSUE #29100: Alerting module should provide more detailed information in case of an error
**What would you like to be added**:

I would like the alerting UI to be transparent why a certain error has happened when querying the underlying data source. While the same query will show its fully detailed error in the dashboard/explore view it is hidden as part of alerting evaluation.

**Why is this needed**:

Just displaying the status code is often not enough. Most data sources return better error conditions in the response body.

**Steps to reproduce**:

I have created this quick mockup URL which can be setup as Prometheus data source: https://curly-bird-331e.swine-registry.workers.dev/502/

Now when I query it with explore, I get this error:

scrn-2020-11-13-13-53-23

But as part of the alert this information is hidden:

scrn-2020-11-13-14-00-27

### PR DESCRIPTION
**Pull request by wbrowne**
**Which issue(s) this PR fixes**:

Fixes #29100

**Special notes for your reviewer**:
Screenshot 2020-11-25 at 15 32 07

### CODE REVIEW

File: pkg/services/alerting/conditions/query.go [hunk 1]
```diff
@@ -360,3 +358,19 @@ func FrameToSeriesSlice(frame *data.Frame) (tsdb.TimeSeriesSlice, error) {
...
+
+func toCustomError(err error) error {
+	// is context timeout
+	if errors.Is(err, gocontext.DeadlineExceeded) {
+		return fmt.Errorf("alert execution exceeded the timeout")
+	}
+
+	// is Prometheus error
+	var e prometheus.PrometheusError
+	if errors.As(err, &e) {
```
Comment (aknuds1) [inline pkg/services/alerting/conditions/query.go:370]: You're not doing anything with the converted error, so should be `errors.Is`
```suggestion
	if errors.Is(err, prometheus.PrometheusError) {
```

**Review by aknuds1 — APPROVED** [review]
LGTM, but please see my suggestion.

File: pkg/services/alerting/conditions/query.go (hunk 1 above)
Comment (wbrowne) [reply pkg/services/alerting/conditions/query.go:370]: I tried this pattern but it didn't work as I expected. It's not defined with `errors.New`, just given the `error` type so I'm not sure the suggestion applies?

Comment (simonswine) [reply pkg/services/alerting/conditions/query.go:370]: I think you need to create a struct rather than an alias type: https://play.golang.org/p/Ak4SLvQ2APB

Comment (wbrowne) [reply pkg/services/alerting/conditions/query.go]: Thanks for the tip @simonswine - made the wrong assumption that alias represented a distinct type. Have reworked it a different way without introducing an error type

File: pkg/tsdb/prometheus/prometheus.go [hunk 2]
```diff
@@ -220,7 +218,12 @@ func parseResponse(value model.Value, query *PrometheusQuery) (*tsdb.QueryResult
 	return queryRes, nil
 }
 
-func wrapAsPrometheusError(err error) PrometheusError {
+func IsAPIError(err error) bool {
+	var e *apiv1.Error
+	return errors.As(err, &e)
```
Comment (aknuds1) [inline pkg/tsdb/prometheus/prometheus.go:223]: `errors.Is` is the function that should be used to tell if an error is of certain type (or wraps it).
```suggestion
	return errors.Is(err, &apiv1.Error{})
```

File: pkg/tsdb/prometheus/prometheus.go [hunk 3]
```diff
@@ -216,3 +217,16 @@ func parseResponse(value model.Value, query *PrometheusQuery) (*tsdb.QueryResult
...
+
+func IsAPIError(err error) bool {
+	var e *apiv1.Error
+	return errors.As(err, &e)
+}
+
+func WrapAPIError(err error) error {
+	var e *apiv1.Error
+	if errors.As(err, &e) {
+		return fmt.Errorf("%s: %s", e.Msg, e.Detail)
```
Comment (aknuds1) [inline pkg/tsdb/prometheus/prometheus.go:229]: What do you actually gain by this? `apiv1.Error` already implements the `error` interface, and `e.Error()` returns exactly the same string as here.

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Unsure about `WrapAPIError`.

File: pkg/tsdb/prometheus/prometheus.go [hunk 4]
```diff
@@ -216,3 +217,16 @@ func parseResponse(value model.Value, query *PrometheusQuery) (*tsdb.QueryResult
 
 	return queryRes, nil
 }
+
+func IsAPIError(err error) bool {
+	var e *apiv1.Error
+	return errors.As(err, &e)
+}
+
+func WrapAPIError(err error) error {
```
Comment (aknuds1) [inline pkg/tsdb/prometheus/prometheus.go:226]: Better naming since the error isn't wrapped
```suggestion
func ConvertAPIError(err error) error {
```

**Review by aknuds1 — CHANGES_REQUESTED** [review]

**Review by aknuds1 — APPROVED** [review]
LGTM!

File: pkg/services/alerting/conditions/query.go [hunk 5]
```diff
@@ -360,3 +358,18 @@ func FrameToSeriesSlice(frame *data.Frame) (tsdb.TimeSeriesSlice, error) {
...
+
+func toCustomError(err error) error {
+	// is context timeout
+	if errors.Is(err, gocontext.DeadlineExceeded) {
+		return fmt.Errorf("alert execution exceeded the timeout")
+	}
+
+	// is Prometheus error
+	if prometheus.IsAPIError(err) {
+		return prometheus.WrapAPIError(err)
```
Comment (papagian) [inline pkg/services/alerting/conditions/query.go:370]:
```suggestion
		return prometheus.ConvertAPIError(err)
```

**Review by papagian — CHANGES_REQUESTED** [review]
there is a reference to `WrapAPIError` left but otherwise works fine

**Review by papagian — APPROVED** [review]
