### PR TITLE
Dashboard: Fix repeated row panel placement with larger number of rows

### LINKED ISSUE #69833: Dashboards: location of repeated panels are wrong (misalignment)
### 
# What went wrong?

**What happened**:

location of repeated pannels are wrong ( from "last row" to "the nth from the last row". "n" will increase with variable value count)

**What did you expect to happen**:

  - 

image

### 
# How do we reproduce it?

it seems that this issue appeared after upgrading to version 8.x

### 
# What Grafana version are you using?

Grafana v9.5.1 (bc353e4b2d)

### 
### Is the bug inside a Dashboard Panel?
[get-help-data.txt](https://github.com/grafana/grafana/files/11703712/get-help-data.txt)

### Grafana Platform?

Docker

### User's OS?

CentOS 7

### User's Browser?

Google Chrome 114.0.5735.106

### Is this a Regression?

Yes

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by kaydelaney**
Fixes an issue where in certain edge cases with a large number of repeated rows, panels would be incorrectly positioned.

Closes #69833

### CODE REVIEW

File: public/app/features/dashboard/state/DashboardModel.ts [hunk 1]
```diff
@@ -756,59 +760,56 @@ export class DashboardModel implements TimeModel {
...
+        rowClone.panels = [];
+        rowClone.gridPos.y += rowHeight * optionIndex;
+        panelBelowIndex = insertPos + panelsInRow.length;
       }
 
       // Update gridPos for panels below if we inserted more than 1 repeated row panel
       if (selectedOptions.length > 1) {
         for (const panel of this.panels.slice(panelBelowIndex)) {
-          panel.gridPos.y += yPos;
+          panel.gridPos.y += rowHeight;
```
Comment (kaydelaney) [inline public/app/features/dashboard/state/DashboardModel.ts:812]: This was the main cause of the issue. Basically the y-pos of panels following a row was increased much more than needed, and for dashboard's with many rows, this could cause `panel.gridPos.y` to reach the max safe integer value, causing the panels to all sort of bunch up at the end.

File: public/app/features/dashboard/state/DashboardModel.ts [hunk 2]
```diff
@@ -840,12 +841,12 @@ export class DashboardModel implements TimeModel {
   getRowHeight(rowPanel: PanelModel): number {
     if (!rowPanel.panels || rowPanel.panels.length === 0) {
       return 0;
+    } else if (rowPanel.collapsed) {
+      return 1;
```
Comment (polibb) [inline public/app/features/dashboard/state/DashboardModel.ts:845]: Okay, so afaiu the panels that will follow a repeated row which is collapsed will always only increase their y-position with 1. Would you put a comment here as well about this?

**Review by polibb — APPROVED** [review]
Clean fix!
Left a comment for a nit.
Thank you for making the rest of the code easier to read and understand 🙌
