### PR TITLE
Accessibility: Corrected aria-label for Edit Panel

### LINKED ISSUE #66209: ID 256773: [Programmatic Access - Simon - Feature Showcase>Edit]: Incorrect aria-label is defined for "Change Visualization and Close options pane" buttons under 'Edit panel' screen.
### **User Experience:** 
Visually impaired users who depend on screen readers will face difficulty if the incorrect `aria-label` is defined for buttons, which will make it difficult for them to understand the exact purpose of the element they are interacting with.
_Note: Login Credentials must not be provided within the bug._

### **Repro steps:**

1. Open #URL: https://play.grafana.org/. Sign in with valid credentials.  "Home" page appears.  
2. Navigate the Feature Showcase pane heading and select it. 
3. Navigate the expanded Dropdown and select the "Edit" menu item. Navigate the page "Edit" page which appears. 
4. Navigate to the "Change Visualization and Close options pane" buttons and select it. 
5. Verify the issue.

**Actual Result:** 
Issue: Incorrect `aria-label` is defined for "Change Visualization and Close options pane" buttons as "toggle-viz-picker and toggle-viz-options" respectively under 'Edit panel' screen.

**Observation**: 
Screen reader announces as "toggle-viz-picker button and toggle-viz-options button" respectively when focus moves on it.

**Expected Result:** 
`Aria-label `should be defined as "Change Visualization and Close options pane" for 'Change Visualization and Close options pane' buttons respectively under 'Edit panel' screen.
_Note: The same issue exists with "Undefined color" button under 'Annotations>edit' screen. (Home page>Featured showcases dropdown>Edit>Setting>Annotations>New>Annotations>edit). The same issue exists with "Update" button under 'variable> new' screen. Same issue exists with the graph present under 'View rule' screen (Alert rule>Sub menu>View). Same issue exists with Graphana play home link under Home page._

### **Severity:**
`SEV2`

### **Area:**
`Panel Editor` (VisualizationButton & VisualizationSelectPane Components)

### PR DESCRIPTION
**Pull request by khushijain21**
**Which issue(s) does this PR fix?**:
This PR fixes #66209

Corrected aria-label for screen readers

Fixes #

**Special notes for your reviewer:**

### CODE REVIEW

File: public/app/features/dashboard/components/PanelEditor/VisualizationButton.tsx [hunk 1]
```diff
@@ -42,7 +41,7 @@ export const VisualizationButton = ({ panel }: Props) => {
           imgSrc={plugin.meta.info.logos.small}
           isOpen={isVizPickerOpen}
           onClick={onToggleOpen}
-          aria-label={selectors.components.PanelEditor.toggleVizPicker}
```
Comment (polibb) [inline public/app/features/dashboard/components/PanelEditor/VisualizationButton.tsx:45]: e2e tests rely on accessing this button through `components.PanelEditor.toggleVizPicker`, so please add it anywhere it's removed under [`data-testid` instead of `aria-label`](https://github.com/grafana/grafana/blob/main/contribute/style-guides/e2e.md#aria-labels-vs-data-testid) and check if the e2e tests are still failing like they are now 🙏

Comment (khushijain21) [reply public/app/features/dashboard/components/PanelEditor/VisualizationButton.tsx:45]: Hello, thank you for your reply. I've made the changes accordingly. Let me know

Comment (polibb) [reply public/app/features/dashboard/components/PanelEditor/VisualizationButton.tsx:45]: Hi 🙌 thank you for the quick reaction! The [e2e tests are now failing](https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md#run-end-to-end-tests) because they expect aria-label, but they should be expecting data-testid. I'm sorry if this seems unrelated, but it's a part of the task of fixing the usability of aria-labels: removing them from use in e2e tests and [replacing that use](https://github.com/grafana/grafana/blob/main/contribute/style-guides/e2e.md#aria-labels-vs-data-testid) with data-testid.

Comment (khushijain21) [reply public/app/features/dashboard/components/PanelEditor/VisualizationButton.tsx:45]: Can you direct to the file location? I am new to this tests

Comment (khushijain21) [reply public/app/features/dashboard/components/PanelEditor/VisualizationButton.tsx:45]: @polibb I did the changes. Do let me know. Thanks!

Comment (polibb) [reply public/app/features/dashboard/components/PanelEditor/VisualizationButton.tsx:45]: Hi, sorry, it is still failing 😕. Not sure why the betterer precommit hook is not running correctly, but would you run `yarn betterer` on this branch on your side, and commit the resulting files, if there are any? This might fix it.

**Review by polibb — APPROVED** [review]
Super accurate & quick communication, thank you for the contribution @khushijain21!
