### PR TITLE
Auth proxy: Ignore stale cache entries

### LINKED ISSUE #21340: HttpAuth: User auth cache needs to be deleted when user is deleted
**What happened**:

When deleting a user, any corresponding entry in the auth cache isn't also invalidated.

**What you expected to happen**:

For the deleted user's auth cache entry to be invalidated.

**How to reproduce it (as minimally and precisely as possible)**:

## @dpavlos' Account
According to @dpavlos, it's a proxy cache related issue and can be reproduced as follows:

1. start from an empty db
2. create the user
3. set isGrafanaAdmin to true
4. authenticate once using the X-WEBAUTH-USER: <username>. Everything works as expected.
5. delete the user
6. repeat steps 2,3,4

When you delete the user, the proxy key that was generated and saved in cache_data table in step 4 is not invalidated properly. Therefore, when you recreate the user with the same username and then try to authenticate, the Login function checks if there are any proxy keys associated with that username, https://github.com/grafana/grafana/blob/35679d4689fb08ac4d64a857d616bc7ced5cd22f/pkg/middleware/auth_proxy/auth_proxy.go#L201, finds the old one (since it hasn't expired yet) and returns the ID of the already deleted user. Hence, a "User not found" message is returned when you call the /stats endpoint for the second time.

## @sfitts' Outdated Account

Issue the following curl commands:

```
$ curl -X POST -H "X-WEBAUTH-USER: admin" -H "Content-Type: application/json" -d'{"login": "vantiqSystem", "password": "unused"}' http://localhost:3000/api/admin/users
{
  "id": 1480,
  "message": "User created"
}

$ curl -X PUT -H "X-WEBAUTH-USER: admin" -H "Content-Type: application/json" -d'{"isGrafanaAdmin": true}' http://localhost:3000/api/admin/users/1480/permissions
{
  "message": "User permissions updated"
}

$ curl -H "X-WEBAUTH-USER: admin" http://localhost:3000/api/admin/stats
{
  "orgs": 14,
  "dashboards": 97,
  "snapshots": 0,
  "tags": 0,
  "datasources": 13,
  "playlists": 0,
  "stars": 0,
  "alerts": 0,
  "users": 72,
  "admins": 14,
  "editors": 13,
  "viewers": 14,
  "activeUsers": 71,
  "activeAdmins": 14,
  "activeEditors": 13,
  "activeViewers": 13,
  "activeSessions": 0
}

$ curl -vis -H "X-WEBAUTH-USER: vantiqSystem" http://localhost:3000/api/admin/stats

*   Trying ::1:3000...
* TCP_NODELAY set
* Connected to localhost (::1) port 3000 (#0)
> GET /api/admin/stats HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.65.3
> Accept: */*
> X-WEBAUTH-USER: vantiqSystem
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 407 Proxy Authentication Required
HTTP/1.1 407 Proxy Authentication Required
< Cache-Control: no-cache
Cache-Control: no-cache
< Content-Type: text/html; charset=UTF-8
Content-Type: text/html; charset=UTF-8
< Expires: -1
Expires: -1
< Pragma: no-cache
Pragma: no-cache
< X-Frame-Options: deny
X-Frame-Options: deny
< Date: Fri, 03 Jan 2020 21:10:11 GMT
Date: Fri, 03 Jan 2020 21:10:11 GMT
< Content-Length: 1727
Content-Length: 1727

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <meta name="theme-color" content="#000">

    <title>Grafana - Error</title>

    <base href="/grafana/" />

    <link rel="stylesheet" href="public/build/grafana.dark.d9f582b9b538bf193c78.css">

    <link rel="icon" type="image/png" href="public/img/fav32.png">
    <link rel="mask-icon" href="public/img/grafana_mask_icon.svg" color="#F05A28">

  </head>

  <body class="theme-dark">
    <div class="main-view">
      <div class="page-container">
        <div class="page-header">
          <div class="page-header__inner">
            <span class="page-header__logo">
              <i class="page-header__icon fa fa-frown-o"></i>
            </span>
            <div class="page-header__info-block">
              <h1 class="page-header__title">
                <a class="text-link" href="login">Grafana</a><span> / Server Error</span><span></span>
              </h1>
              <div class="page-header__sub-title">Sadly something went wrong</div>
            </div>
          </div>
        </div>
      </div>
      <div class="page-container page-body ng-scope" style="padding: 2rem">
        <div class="alert">
          <div class="alert-icon"><i class="fa fa-exclamation-triangle"></i></div>
          <div class="alert-body">
            <div class="alert-title">User not found</div>
          </div>
        </div>
        <br />

        <div style="padding: 2rem 0 0">
          <p>Check the Grafana server logs for the detailed error message.</p>
        </div>
      </div>
    </div>
  </body>
</html>
```

Contents of log for failed request:

```
t=2020-01-03T21:02:37+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/admin/stats status=200 remote_addr=172.21.0.1 time_ms=4 size=312 referer=
t=2020-01-03T21:02:48+0000 lvl=eror msg="Failed to get signed user" logger=auth.proxy username= message="User not found" error=nil
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.2
- OS Grafana is installed on: tested on both Windows and Linux (both via Docker).
- Others:  Grafana configured as follows:

```
instance_name = vantiq_grafana
app_mode = development

[server]
root_url = /grafana
router_logging = true

[database]
type = mysql
host = vantiq_mysql:3306

[users]
allow_sign_up = false
auto_assign_org = true
allow_org_create = false

[auth]
disable_login_form = true

[auth.basic]
enabled = false

[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = false
enable_login_token = true
```

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
In auth proxy, invalidate and ignore cache entries for which no corresponding user is found.

**NB:**
I didn't implement cache invalidation on user deletion since the cache key can't easily be derived from the user info, it's calculated from auth headers. Maybe this is something we need to do anyway, for e.g. security reasons - I hope to get some feedback around this aspect :)

**Which issue(s) this PR fixes**:

Fixes #21340.

### CODE REVIEW

File: pkg/middleware/auth_proxy.go [hunk 1]
```diff
@@ -41,32 +53,33 @@ func initContextWithAuthProxy(store *remotecache.RemoteCache, ctx *models.ReqCon
...
-		logger.Error(
-			"Failed to get signed user",
-			"username", username,
-			"message", err.Error(),
-			"error", err.DetailsError,
-		)
-		ctx.Handle(407, err.Error(), err.DetailsError)
-		return true
+		logger.Debug("Failed to get user info given ID, retrying without cache", "userID", id)
+		_ = auth.RemoveUserFromCache(logger)
```
Comment (bergquist) [inline pkg/middleware/auth_proxy.go:67]: I think we should handle this error. It would also be nice with some comments about why we remove the cache and try again. This is quite a fragile part of the codebase so some tests would be really nice.

Comment (aknuds1) [reply pkg/middleware/auth_proxy.go:67]: @bergquist OK - do you know if all errors returned here will be hard, or if there can be some we should ignore?

Comment (bergquist) [reply pkg/middleware/auth_proxy.go:67]: https://github.com/grafana/grafana/blob/master/pkg/infra/remotecache/remotecache.go#L18 this is the only known error I think you have to care about. 

If not sure we have to return the error. Perhaps just logging would be enough?

File: Dockerfile [hunk 2]
```diff
@@ -33,7 +16,21 @@ COPY emails emails
 ENV NODE_ENV production
 RUN ./node_modules/.bin/grunt build
 
-# Final container
+FROM golang:1.14.1-alpine AS go-builder
```
Comment (marefr) [inline Dockerfile:19]: These changes seems unrelated to these changes? Can you open a separate PR for this?

Comment (aknuds1) [reply Dockerfile:19]: @marefr I can.

**Review by marefr — CHANGES_REQUESTED** [review]
Still haven't addressed Carl's comment.

**Comment by aknuds1** [comment]
> Still haven't addressed Carl's comment.

@marefr Yes, I didn't get that far yet (re-requested review from Carl by accident).

File: pkg/middleware/auth_proxy.go (hunk 1 above)
Comment (aknuds1) [reply pkg/middleware/auth_proxy.go]: @bergquist Haven't done anything about tests yet, but handling this error now, by logging it if it isn't remotecache.ErrCacheItemNotFound.

**Review by bergquist — APPROVED** [review]
LGTM! 

I'm not if sure we should Cherry-pick this into 7.0. I'm fine either way. your decision :)

**Comment by aknuds1** [comment]
@bergquist I gave it the 7.1 milestone, figure that makes the most sense? :)

**Comment by bergquist** [comment]
Yea I think that's fine

**Comment by bergquist** [comment]
@aknuds1 I think you can merge this now :)

**Comment by aknuds1** [comment]
@bergquist You sure you don't want me to add tests first? :)

**Comment by bergquist** [comment]
@aknuds1 haha. I totally forgot that. I just scrolled thru approved PR's to find things to merged :)
Yes, there should be tests! :)

**Comment by aknuds1** [comment]
@marefr I think all of Carl's concerns are met - corresponding tests are still lacking, but he said in the meantime we can skip them if they take too long to write. I would have to write completely new tests for this functionality, so I'm considering they might just take too long to develop considering how much else needs doing.

**Comment by aknuds1** [comment]
@marefr Ping

File: pkg/middleware/auth_proxy.go [hunk 3]
```diff
@@ -41,32 +55,42 @@ func initContextWithAuthProxy(store *remotecache.RemoteCache, ctx *models.ReqCon
...
+		// because cache keys are computed from request header values and not just the user ID. Meaning that
+		// we can't easily derive cache keys to invalidate when deleting a user. To work around this, we try to
+		// log the user in again without the cache.
+		logger.Debug("Failed to get user info given ID, retrying without cache", "userID", id)
+		if err := auth.RemoveUserFromCache(logger); err != nil {
+			if !errors.Is(err, remotecache.ErrCacheItemNotFound) {
+				logger.Error("Got unexpected error when removing user from auth cache", "error", err)
+			}
+		}
+		id, err := logUserIn(auth, username, logger, true)
```
Comment (papagian) [inline pkg/middleware/auth_proxy.go:79]:
```suggestion
		id, err = logUserIn(auth, username, logger, true)
```

need to override the outside variable `id` so as it will be set correctly [here](https://github.com/grafana/grafana/blob/fd49010775d8576b607e10bca52bd33b528c403e/pkg/middleware/auth_proxy.go#L99).

File: pkg/middleware/auth_proxy_test.go [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+
+	t.Logf("Injecting stale user ID in cache with key %q", key)
+	err = store.Set(key, int64(33), 0)
+	require.NoError(t, err)
+
+	authEnabled := initContextWithAuthProxy(store, ctx, orgID)
+	require.True(t, authEnabled)
+
+	require.Equal(t, userID, ctx.SignedInUser.UserId)
+	require.True(t, ctx.IsSignedIn)
```
Comment (papagian) [inline pkg/middleware/auth_proxy_test.go:84]:
```suggestion
	require.True(t, ctx.IsSignedIn)
	
	i, err := store.Get(key)
	require.NoError(t, err)
	require.Equal(t, i.(int64), userID)
```

**Review by papagian — CHANGES_REQUESTED** [review]
Nice work! Please check my comments for caching correctly the new user id.

File: pkg/middleware/auth_proxy.go (hunk 3 above)
Comment (aknuds1) [reply pkg/middleware/auth_proxy.go:79]: Great catch @papagian, it's such an easy mistake in Go.

File: pkg/middleware/auth_proxy/auth_proxy.go [hunk 5]
```diff
@@ -168,57 +169,62 @@ func (auth *AuthProxy) getKey() string {
...
-		userID, err = auth.store.Get(cacheKey)
-	)
-
+// GetUserViaCache gets user ID from cache.
+func (auth *AuthProxy) GetUserViaCache(logger log.Logger) (int64, error) {
+	cacheKey := auth.getKey()
+	logger.Debug("Getting user ID via auth cache", "cacheKey", cacheKey)
+	userID, err := auth.store.Get(cacheKey)
 	if err != nil {
+		logger.Debug("Failed getting user ID via auth cache", "error", err)
```
[the remark this answers is not in the document]
Comment (aknuds1) [reply pkg/middleware/auth_proxy/auth_proxy.go:208]: @papagian It shouldn't be logged as an error, since it isn't something that needs to be dealt with (i.e., it's only technically an error, not logically). It will just be confusing noise in the logs for anyone looking for errors. See [here](https://github.com/grafana/grafana/pull/23979/files#diff-dc90ed542fb29715788afbc5a913c52cR175).

File: pkg/middleware/auth_proxy_test.go [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+
+	origHeaderName := setting.AuthProxyHeaderName
+	origEnabled := setting.AuthProxyEnabled
+	origHeaderProperty := setting.AuthProxyHeaderProperty
+	t.Cleanup(func() {
+		setting.AuthProxyHeaderName = origHeaderName
+		setting.AuthProxyEnabled = origEnabled
+		setting.AuthProxyHeaderProperty = origHeaderProperty
+		bus.RemoveHandler(upsertHandler)
+		bus.RemoveHandler(getSignedUserHandler)
```
[the remark this answers is not in the document]
Comment (aknuds1) [reply pkg/middleware/auth_proxy_test.go:53]: @papagian I think it's better to not make assumptions. It's a rule of thumb that tests shouldn't affect the state of other tests.

File: pkg/middleware/auth_proxy_test.go (hunk 4 above)
Comment (aknuds1) [reply pkg/middleware/auth_proxy_test.go:84]: @papagian Nice one!

File: pkg/middleware/auth_proxy/auth_proxy.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (papagian) [reply pkg/middleware/auth_proxy/auth_proxy.go:208]: I don't insist :)

File: pkg/middleware/auth_proxy_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (papagian) [reply pkg/middleware/auth_proxy_test.go:53]: ok, but in that case instead of removing completely the handler I think we need to restore its previous behaviour; I believe that tests expecting to find that handler would fail [here](https://github.com/grafana/grafana/blob/53175a41c9e6becc0b493d3cadc8ade2524aba27/pkg/bus/bus.go#L119)

[the remark this answers is not in the document]
Comment (aknuds1) [reply pkg/middleware/auth_proxy_test.go]: @papagian I found a way of restoring any previous handlers (they're currently `nil` AFAICT). Please have another look.

File: pkg/middleware/auth_proxy_test.go [hunk 7]
```diff
@@ -0,0 +1,89 @@
...
+			UserId: userID,
+			OrgId:  orgID,
+		}
+		return nil
+	}
+
+	origHeaderName := setting.AuthProxyHeaderName
+	origEnabled := setting.AuthProxyEnabled
+	origHeaderProperty := setting.AuthProxyHeaderProperty
+	origUpsertHandler := bus.AddHandlerForType(&models.UpsertUserCommand{}, upsertHandler)
```
Comment (marefr) [inline pkg/middleware/auth_proxy_test.go:48]: Is the introduction/usage of `AddHandlerForType` really needed. We haven't really had a problem with this before - what kind of problem did you get?

**Review by marefr — APPROVED** [review]
LGTM. Not sure about the introduction of `bus.AddHandlerForType` though, see comment.

File: pkg/middleware/auth_proxy_test.go (hunk 7 above)
Comment (aknuds1) [reply pkg/middleware/auth_proxy_test.go:48]: @marefr It's necessary for cleaning up handlers after the test finishes. I couldn't see any other way to restore the original handlers. I think the original API is flawed TBH, since it implicitly derives the handler key, and this explicit API is better.

Comment (marefr) [reply pkg/middleware/auth_proxy_test.go:48]: Agree with you, but sure it's the path we want to go. Moving forward the goal should be to remove the usage of the global bus to allow writing tests in separation without having to bother about state.

Comment (aknuds1) [reply pkg/middleware/auth_proxy_test.go:48]: @marefr, I've also seen that we plan to get rid of the global bus. But as it stands I don't see how to write this test differently?

Comment (papagian) [reply pkg/middleware/auth_proxy_test.go:48]: I tend to agree with @marefr 
Moreover because `origUpsertHandler` and `origSignedUserHandler` are `nil` which mean that my original assumption that these handlers were registered was wrong.
Anyway, even though I don't insist, I would prefer to address this everywhere instead of applying to a specific test.

**Review by papagian — APPROVED** [review]
LGTM but I would prefer it without `AddHandlerForType`.

File: pkg/middleware/auth_proxy_test.go (hunk 7 above)
Comment (marefr) [reply pkg/middleware/auth_proxy_test.go:48]: > I don't see how to write this test differently?

If you skip setting back the handlers does the tests fail? If not, you're all set and don't need the `AddHandlerForType`.

Comment (aknuds1) [reply pkg/middleware/auth_proxy_test.go:48]: @marefr As I explained before I think it's a very bad idea to not restore state changed by tests. Although it _might_ not affect anything now, it's an assumption that breaks very easily once you write more tests. Also, I think that objectively the new method is better, since it's explicit about how the key is derived (i.e. from the message type).

@bergquist @kylebrandt what do you think?
