### PR TITLE
grafana/e2e: Update add dashboard flow

### LINKED ISSUE #38683: E2E addDashboard flow should support query variables with custom code editors
**What happened**:
I was writing e2e tests for an external component with uses the same code editor for query template variables as it does for a regular query and I wanted to confirm that adding a template variable worked, but the e2e tests flow for template variables is currently written in such a way that it only checks for the default code editor and not any code editor. 

**What you expected to happen**:
I expect to be able to test my datasource plugin's ability to add and use template variables

**How to reproduce it (as minimally and precisely as possible)**:
To use the same code editor for your template variables extend DataSourceVariableSupport

**Environment**:
- Grafana version: 8.1.2

### PR DESCRIPTION
**Pull request by aangelisc**
**What is this feature?**

This adds support for more complex query variables by allowing the test author to provide a `variableQueryForm` prop (similar to the `queriesForm` prop for the `addPanel` flow). 

In addition, the selector used for selecting the Variable editor in dashboard settings was out of date. This has been updated. The datasource picker selector has also been updated and a selector has been added for the apply button.

Fixes #38683
Fixes a bug blocking grafana/timestream-datasource#199

I will follow this PR up with an update to Azure Montior tests making use of the new flow as an example.

### CODE REVIEW

File: public/app/features/variables/editor/VariableEditorEditor.tsx [hunk 1]
```diff
@@ -204,7 +204,11 @@ export class VariableEditorEditorUnConnected extends PureComponent<Props, State>
                 Run query
                 {loading && <Icon className="spin-clockwise" name="sync" size="sm" style={{ marginLeft: '2px' }} />}
               </Button>
-              <Button variant="primary" onClick={this.onApply}>
+              <Button
+                variant="primary"
+                onClick={this.onApply}
+                aria-label={selectors.pages.Dashboard.Settings.Variables.Edit.General.applyButton}
```
Comment (sarahzinger) [inline public/app/features/variables/editor/VariableEditorEditor.tsx:210]: rather than use an aria label maybe we can use a data test id :) since I think this button should already be well labelled by the text that lives in side it, yeah? https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label

File: packages/grafana-e2e/src/flows/addDashboard.ts [hunk 2]
```diff
@@ -185,7 +186,7 @@ const addVariable = (config: PartialAddVariableConfig, isFirst: boolean): AddVar
     e2e.pages.Dashboard.Settings.Variables.Edit.QueryVariable.queryOptionsDataSourceSelect()
       .should('be.visible')
       .within(() => {
-        e2e.components.Select.input().should('be.visible').type(`${dataSource}{enter}`);
+        e2e.components.DataSourcePicker.inputV2().type(`${dataSource}{enter}`);
```
Comment (sarahzinger) [inline packages/grafana-e2e/src/flows/addDashboard.ts:189]: hii for my own knowledge, do you know what this inputV2 thing is about? I sort of dropped away from e2e testing work and feel out of the loop haha

File: packages/grafana-e2e/src/flows/addDashboard.ts [hunk 3]
```diff
@@ -31,6 +31,7 @@ interface AddVariableOptional {
   label?: string;
   query?: string;
   regex?: string;
+  variableQueryForm?: (config: AddVariableConfig) => void;
```
Comment (sarahzinger) [inline packages/grafana-e2e/src/flows/addDashboard.ts:34]: these changes are very rad. I wonder if it would be possible to document some of these amazing features better so that they are more discoverable.

Like in an ideal world I would love to be able to start typing addDashboard and then it would talk me through what I can pass through it and that if I pass in variableQueryForm I can test template variables or something you know? I feel like this should be possible via comments if they are properly formatted, I think we have something with jsdom style comments maybe? Or maybe I'm making that up.

**Review by sarahzinger — APPROVED** [review]
Very cool thank you! One small comment around aria labels vs data test ids

File: public/app/features/variables/editor/VariableEditorEditor.tsx (hunk 1 above)
Comment (aangelisc) [reply public/app/features/variables/editor/VariableEditorEditor.tsx:210]: Yep I can take a look at moving to `data-testid`. I think that is meant to be the standard anyway 🤔

File: packages/grafana-e2e/src/flows/addDashboard.ts (hunk 2 above)
Comment (aangelisc) [reply packages/grafana-e2e/src/flows/addDashboard.ts:189]: I *think* this may be something to do with moving from `aria-labels` to `data-testid` (just from looking at the selectors). But someone from @grafana/user-essentials would have to confirm 🙃

Comment (aangelisc) [reply packages/grafana-e2e/src/flows/addDashboard.ts:189]: I *think* this may be something to do with moving from `aria-labels` to `data-testid` (just from looking at the selectors). But someone from @grafana/user-essentials would have to confirm 🙃

File: packages/grafana-e2e/src/flows/addDashboard.ts (hunk 3 above)
Comment (aangelisc) [reply packages/grafana-e2e/src/flows/addDashboard.ts:34]: I agree with you here, a JSDOM style doc would be really nice. I'll see what's possible 😊

**Review by ashharrison90 — APPROVED** [review]
+1 on using `data-testid` instead of `aria-label`

lgtm otherwise 👍

File: packages/grafana-e2e/src/flows/addDashboard.ts [hunk 4]
```diff
@@ -40,6 +41,74 @@ interface AddVariableRequired {
...
+ *        type: e2e.flows.VARIABLE_TYPE_CONSTANT,
+ *        constantValue: 'constant',
+ *      }
+ *    ]
+ * })
+ * ```
+ *
+ * @see{@link AddVariableConfig}
+ *
+ * @see{@link https://github.com/grafana/grafana/blob/main/e2e/cloud-plugins-suite/azure-monitor.spec.ts Azure Monitor Tests for full examples}
```
Comment (sarahzinger) [inline packages/grafana-e2e/src/flows/addDashboard.ts:110]: nice thanks so much!

**Review by sarahzinger — APPROVED** [review]
awesome!
