### PR TITLE
Dashboard: Fix issues where unsaved-changes warning is not displayed

### LINKED ISSUE #34768: Dashboard: Not getting any unsaved changes warning after using panel edit then leaving dashboard
Works
* Open dashboard
* Duplicate a panel
* Move to another page , see the unsaved changes warning

Does not work
* Open a dashboard
* Duplicate a panel
* Open panel in edit mode, go back to dashboard
* leave to another page
* No unsaved changes warning

### LINKED ISSUE #34891: LibraryPanels: Go back button triggers save modal even when no changes have been made
**What happened**: Save modal is triggered every time I leave panel edit for a library panel

**What you expected to happen**: Save modal shouldn't appear if I haven't made any changes

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard and a panel. Convert the panel into a library panel.
2. Go into Panel edit and click Save library panel
3. Click on `Go back` or press Esc
4. Should trigger Save modal even though I just saved

image

Test dashboards: 
- https://g80-beta.grafana.net/d/-zopi9qGk/librarypanel-issue?orgId=1
- https://g80-beta.grafana.net/d/JuWZgrqMz/azure-monitor-cross-squad-testing?orgId=1&editPanel=2

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0-beta2
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Ubuntu and Chrome

### PR DESCRIPTION
**Pull request by torkelo**
You can only have one prompt (history block) at a time so this required a big refactoring. 

* [x] Moved ChangeTracker to DashboardPromt so that it uses Prompt component from react-router-dom 
* [x] Rewrite of logic to adapt to this react component structure 
* [x] Integrate Library panels unsaved changes handling into the DashboardPrompt (messy but cannot find another way)
* [x] Solved lots of race conditions between changes triggered via onConfirm and onDismiss both being called
* [x] Listen to save event  
* [x] Move tests from ChangeTracker and delete ChangeTracker 
* [x] Update PanelEditor tests 

Fixes #34768 
Fixes another issue so that if you click a link from within library panel edit and you discard/save library panel you then actually go the link you clicked (currently in main it always block navigation and just returns you to the dashboard). 

This also now supports stacking the unsaved changes warning. First you can get the library panel warning, then you saved/discarded that you can get the dashboard unsaved changes warning. This is a bit confusing. And the library panel modal is also not great as an "unsaved changes" as it's confusing that a "Update library panels" modal shows when you clicked a link. The title should maybe change in this case? Another issue is that when you hit the Save library panel button the Discard button is also there, this is also a bit confusing, what does discarding here do when you come from the Save button?  (currently it discard & and closes panel edit).

### CODE REVIEW

File: public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx [hunk 1]
```diff
@@ -0,0 +1,214 @@
...
+    if (panel.legend) {
+      delete panel.legend.sort;
+      delete panel.legend.sortDesc;
+    }
+
+    return true;
+  });
+
+  // ignore template variable values
+  each(dash.getVariables(), (variable: any) => {
```
Comment (hugohaggmark) [inline public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx:190]: nit: do we need to use each?

File: public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx [hunk 2]
```diff
@@ -0,0 +1,214 @@
...
+  const originalClean = cleanDashboardFromIgnoredChanges(original);
+
+  const currentTimepicker: any = find((currentClean as any).nav, { type: 'timepicker' });
+  const originalTimepicker: any = find((originalClean as any).nav, { type: 'timepicker' });
+
+  if (currentTimepicker && originalTimepicker) {
+    currentTimepicker.now = originalTimepicker.now;
+  }
+
+  const currentJson = angular.toJson(currentClean);
```
Comment (hugohaggmark) [inline public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx:210]: nit: can we use `safeStringifyValue` instead of angular.toJson?

**Review by hugohaggmark — COMMENTED** [review]
Love the DashboardPrompt solution  🧠  💥   But I still have the same issue with Azure Monitor DS when unsaved changes dialog appears without the user changing anything.

Also, now the user gets double Update Library Panels modals when the user clicks `Discard` in the first.

https://user-images.githubusercontent.com/562238/120198926-f4670180-c222-11eb-97b9-f8b16c28af63.mp4

File: public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx (hunk 1 above)
Comment (torkelo) [reply public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx:191]: this is just copied code

File: public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx (hunk 2 above)
Comment (torkelo) [reply public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx:211]: just copied from ChangeTracker

**Comment by torkelo** [comment]
@hugohaggmark 

>  But I still have the same issue with Azure Monitor DS when unsaved changes dialog appears without the user changing anything.

This PR does not address any of the onChange issues with data sources. It only addresses the history.block/Prompt issues where going into Panel edit would remove the dashboard prompt and you would lose all dashboard unsaved changes warnings from then on as well as other issues with the prompt.

**Comment by hugohaggmark** [comment]
> @hugohaggmark
> 
> > But I still have the same issue with Azure Monitor DS when unsaved changes dialog appears without the user changing anything.
> 
> This PR does not address any of the onChange issues with data sources. It only addresses the history.block/Prompt issues where going into Panel edit would remove the dashboard prompt and you would lose all dashboard unsaved changes warnings from then on as well as other issues with the prompt.

Gotcha @torkelo, I just saw that this PR was supposed to fix https://github.com/grafana/grafana/issues/34891 , maybe change the related issue 😉

**Comment by torkelo** [comment]
@hugohaggmark ah! that explains it, linked the wrong issue, meant to link to #34768

File: public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx [hunk 3]
```diff
@@ -164,30 +170,14 @@ export class PanelEditorUnconnected extends PureComponent<Props> {
     ) {
       try {
         await saveAndRefreshLibraryPanel(this.props.panel, this.props.dashboard.meta.folderId!);
-        this.props.updateSourcePanel(this.props.panel);
```
Comment (torkelo) [inline public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:167]: I removed these two calls to updateSourcePanel because I could not see these having any effect, in all the "leave panel edit" flows we never compared changes to updating sourcePanel had no effect that I could see

**Comment by hugohaggmark** [comment]
Is the showing the update library modal again when user presses Discard fixed yet?

File: public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx (hunk 3 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:167]: Maybe @kaydelaney has some insight on this?

**Comment by torkelo** [comment]
Pushed another update that tweaks the modal a bit so they are different as unsaved prompt and when used via "Save library panel" button.

Save button:
Screenshot from 2021-06-01 09-36-12


Unaved Prompt
Screenshot from 2021-06-01 09-36-59

**Comment by torkelo** [comment]
@hugohaggmark 
> Is the showing the update library modal again when user presses Discard fixed yet?

I fixed that just now. frustrating timing issues force some delays between react state updates & location updates

**Comment by hugohaggmark** [comment]
> @hugohaggmark
> 
> > Is the showing the update library modal again when user presses Discard fixed yet?
> 
> I fixed that just now. frustrating timing issues force some delays between react state updates & location updates

I'm going to have another test run, thanks Torkel

**Comment by hugohaggmark** [comment]
Did another test run and the "double" modals on `Discard` are gone! Found this:
- When the user clicks `UpdateAll` (for a changed library panel) when exiting panel edit, the update library panels modal shows up again
- When the user changes a library panel in panel edit and clicks save library panel and then update all, the save dialog isn't closed. Might be something unrelated to this PR though.

File: public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx [hunk 4]
```diff
@@ -0,0 +1,217 @@
...
+      savedEventUnsub.unsubscribe();
+    };
+  }, [dashboard]);
+
+  const onHistoryBlock = (location: H.Location) => {
+    const panelInEdit = dashboard.panelInEdit;
+    const search = new URLSearchParams(location.search);
+
+    // Are we leaving panel edit & library panel?
+    if (panelInEdit && panelInEdit.libraryPanel && panelInEdit.hasChanged && !search.has('editPanel')) {
```
Comment (dprokop) [inline public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx:63]: Why do we have a separate check for the library panel?

File: public/app/features/dashboard/containers/__snapshots__/DashboardPage.test.tsx.snap [hunk 5]
```diff
@@ -119,6 +119,113 @@ exports[`DashboardPage Dashboard init completed  Should render dashboard grid 1`
       title="My dashboard"
     />
   </div>
+  <Memo()
```
Comment (dprokop) [inline public/app/features/dashboard/containers/__snapshots__/DashboardPage.test.tsx.snap:122]: Maybe we can remove this snapshot rather than extending it?

File: public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx (hunk 4 above)
Comment (torkelo) [reply public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx:63]: @dprokop because we have a separate unsaved change modal for unsaved library panel changes when leaving panel edit (the main reason for this PR was that we had a history.block Prompt in panel edit and it overwrote the one in ChangeTracker)

Comment (dprokop) [reply public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx:63]: ok, I see, thanks!

File: public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx [hunk 6]
```diff
@@ -0,0 +1,217 @@
...
+  SaveLibraryPanelModal,
+}
+
+export const DashboardPrompt = React.memo(({ dashboard }: Props) => {
+  const [state, setState] = useState<State>({ original: null, modal: null });
+  const dispatch = useDispatch();
+  const { original, originalPath, blockedLocation, modal } = state;
+
+  useEffect(() => {
+    const timeoutId = setTimeout(() => {
```
Comment (kaydelaney) [inline public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx:39]: I think a comment for why this needs to be in a timeout would be useful

File: public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx [hunk 7]
```diff
@@ -0,0 +1,217 @@
...
+    return false;
+  };
+
+  return (
+    <>
+      <Prompt when={true} message={onHistoryBlock} />
+      {modal === PromptModal.UnsavedChangesModal && (
+        <UnsavedChangesModal
+          dashboard={dashboard}
+          onSaveSuccess={() => {
```
Comment (kaydelaney) [inline public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx:91]: Would `useCallback` make sense here?

File: public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx (hunk 3 above)
Comment (kaydelaney) [reply public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:167]: No insight I'm afraid. :(

File: public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx (hunk 7 above)
Comment (torkelo) [reply public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx:91]: no, DashboardPrompt is only re-rendered when dashboards change or on location change, so caching the callback would have no effect

File: public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx (hunk 6 above)
Comment (torkelo) [reply public/app/features/dashboard/components/DashboardPrompt/DashboardPrompt.tsx:39]: yes, (It's to give panels time to load and migrate schemes)

File: public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx (hunk 3 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx:167]: I can't remember either, so we're all good :)

**Comment by torkelo** [comment]
@hugohaggmark thanks for testing and finding more bugs! Had to do another round of refactoring to fix the remaining race conditions. think all scenarios work now. Added more code comments and the refactoring should help explain the timeouts more.

**Comment by hugohaggmark** [comment]
> @hugohaggmark thanks for testing and finding more bugs! Had to do another round of refactoring to fix the remaining race conditions. think all scenarios work now. Added more code comments and the refactoring should help explain the timeouts more.

Exceptional work as always, Torkel! I will have another look ASAP.

**Review by hugohaggmark — APPROVED** [review]
Beautiful and works as expected! 🎉
