### PR TITLE
Variables: Fixes filtering options with more than 1000 entries

### LINKED ISSUE #24399: Templating: Options picker does not filter correctly
Good afternoon,

Please disregard my terminology if it's incorrect. 

I've updated from 6.7 to Beta1 and Beta2 recently and are seeing in my VM Selector field (which has about 2800 different values to choose from - when i start typing in a name of a VM it does not filter properly.. Some VMs will show up but most will not when i start typing their names.. .When i roll back to 6.7 it works as expected. 

Capture

Thoughts? 

Thank you,

exbane

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
When we created the new variable system we introduced a small issue when filtering for items in a query variable with over 1000 items because we limited the options before doing the filtering. This PR tries to remedy this.

**Which issue(s) this PR fixes**:
Fixes #24399

**Special notes for your reviewer**:
I also added the ability to add variables with TestData so we can simulate a lot of items, hence the change to `metricTree`.
To repro the original issue use this Dashboard JSON https://gist.github.com/hugohaggmark/73097d4450caf63b4f8ad03165bf8ef2.

### CODE REVIEW

File: public/app/features/variables/state/selectors.ts [hunk 1]
```diff
@@ -12,7 +12,7 @@ export const getVariable = <T extends VariableModel = VariableModel>(
     if (throwWhenMissing) {
       throw new Error(`Couldn't find variable with id:${id}`);
     }
-    return undefined;
+    return (undefined as unknown) as T;
```
Comment (dprokop) [inline public/app/features/variables/state/selectors.ts:15]: this is beautiful :)

**Review by dprokop — APPROVED** [review]
LGTM

File: public/app/features/variables/state/selectors.ts (hunk 1 above)
Comment (hugohaggmark) [reply public/app/features/variables/state/selectors.ts:15]: Also, a strict null error unfortunately, the correct way would be to define a better return type. Should be `T | undefined` but that would cause a ripple effect. When we remove the old variable system, a lot of these strict null errors will become a lot clearer.

**Comment by hugohaggmark** [comment]
@mckn any feedback on this?
