### PR TITLE
Loki: Fix explain section about $__interval variable

### LINKED ISSUE #56735: Loki: Explain section for $__interval does not make sense in Explore
**What happened**:

More info: https://raintank-corp.slack.com/archives/C03PMJLVC67/p1665499118771669

In Explore, explain section about $__interval does not make sense as you can't access query options. Moreover, text is duplicated and not very clear. So firstly it shouldn’t be in Explore and  secondly it should be rewritten so it make sense. 

image

The code to change is here: https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/querybuilder/operationUtils.ts#L57

**What you expected to happen**:
Have clear and meaningful explanation of $__interval variable in Loki

**How to reproduce it (as minimally and precisely as possible)**:

1. Choose Loki data source in Explore (`make devenv sources=loki`)
2. Run query such as `rate({place="moon"}[$__interval)`
3. Toggle explain mode and read explanation

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:

This PR updates explain section in Loki query builder explaining interval. It:

- Adds link to interval documentation
- Adds more clear explanation how is interval calculated
- Makes it clear that query options are only in dashboard

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/56735

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/datasource/loki/querybuilder/operationUtils.ts [hunk 1]
```diff
@@ -54,7 +54,7 @@ export function createRangeOperation(name: string, isRangeOperationWithGrouping?
       let opDocs = FUNCTIONS.find((x) => x.insertText === op.id)?.documentation ?? '';
 
       if (op.params[0] === '$__interval') {
-        return `${opDocs} \`$__interval\` is variable that will be replaced with a calculated interval based on **Max data points**,  **Min interval** and query time range. You find these options you find under **Query options** at the right of the data source select dropdown.`;
+        return `${opDocs} \`$__interval\` is variable that will be replaced with a [calculated interval](https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#__interval) based on the time range and width of the graph. In dashboards, you can affect interval variable using **Max data points** and **Min interval**. You find these options you find under **Query options** at the right of the data source select dropdown.`;
```
Comment (matyax) [inline public/app/plugins/datasource/loki/querybuilder/operationUtils.ts:57]: Maybe:

```suggestion
        return `${opDocs} \`$__interval\` is a variable that will be replaced with the [calculated interval](https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#__interval) based on the time range and width of the graph. In Dashboards, you can affect the interval variable using **Max data points** and **Min interval**. You can find these options under **Query options** right of the data source select dropdown.`;
```

**Review by matyax — COMMENTED** [review]
Left a suggestion.

**Review by matyax — APPROVED** [review]
🙇‍♂️
