### PR TITLE
Alerting: Fixed the issue/bug of diff and percent_diff functions *Breaking change*

### LINKED ISSUE #16270: Rename alert rule diff reducer to absDiff or diffAbs
**What happened**: diff calculation in alerts returns absolute values

**What you expected to happen**: negative values when actual values is higher than the compared one

**How to reproduce it (as minimally and precisely as possible)**: create an alert with diff calculation

**Anything else we need to know?**: I think that it was working before 6.0.0 upgrade

**Environment**:
- Grafana version: 6.0.2
- Data source type & version: graphite
- OS Grafana is installed on: Red Hat 7
- User OS & Browser: Windows 10, Chrome
- Grafana plugins:
- Others:

image

### PR DESCRIPTION
**Pull request by vikkyomkar**
What this PR does / why we need it:
This PR fixed the existing **diff and percent_diff** functions to return signed values [+ve / -ve]
and also created 2 new functions, **diff_abs and percent_diff_abs**, to return the absolute values

Which issue(s) this PR fixes:

Fixes #16270  #10129 

Special notes for your reviewer:
None

### CODE REVIEW

**Comment by vikkyomkar** [comment]
Hi @torkelo , Can you please review this PR ?

**Comment by vikkyomkar** [comment]
@aknuds1 @marefr can this PR be merged?

**Comment by aknuds1** [comment]
Awaiting review from other team members.

**Comment by martinbruntsch** [comment]
Hi all, any progress with the PR?

**Comment by aknuds1** [comment]
@martinbruntsch Sorry, we're still waiting on some internal feedback.

File: pkg/services/alerting/conditions/reducer.go [hunk 1]
```diff
@@ -141,8 +145,7 @@ func calculateDiff(series *tsdb.TimeSeries, allNull bool, value float64, fn func
 		for i := 0; i < len(points); i++ {
 			if points[i][0].Valid {
 				allNull = false
-				val := fn(first, points[i][0].Float64)
-				value = math.Abs(val)
+				value = fn(first, points[i][0].Float64)
```
Comment (bergquist) [inline pkg/services/alerting/conditions/reducer.go]: I agree that this makes sense but this will be a breaking change.

File: pkg/services/alerting/conditions/reducer_test.go [hunk 2]
```diff
@@ -128,25 +128,124 @@ func TestSimpleReducer(t *testing.T) {
...
+			So(result, ShouldEqual, float64(70))
+		})
+
+		Convey("diff of three positive points", func() {
 			result := testReducer("diff", 30, 40, 40)
 			So(result, ShouldEqual, float64(10))
 		})
 
+		Convey("diff of three negative points", func() {
+			result := testReducer("diff", -30, -40, -40)
```
Comment (bergquist) [inline pkg/services/alerting/conditions/reducer_test.go]:
```suggestion
			result := testReducer("diff", -30, -40, -50)
```

File: pkg/services/alerting/conditions/reducer_test.go [hunk 3]
```diff
@@ -128,25 +128,124 @@ func TestSimpleReducer(t *testing.T) {
...
+			So(result, ShouldEqual, float64(-10))
```
Comment (bergquist) [inline pkg/services/alerting/conditions/reducer_test.go]:
```suggestion
			So(result, ShouldEqual, float64(-20))
```

File: pkg/services/alerting/conditions/reducer_test.go (hunk 2 above)
Comment (bergquist) [reply pkg/services/alerting/conditions/reducer_test.go]: I think this makes it more clear that we look at the first and last value. It would be great if we could fix this for all tests with more then 2 values.

**Review by bergquist — COMMENTED** [review]
While I agree that this makes sense but I'm worried about the breaking change. Could we solve this without introducing a breaking change?

File: pkg/services/alerting/conditions/reducer.go (hunk 1 above)
Comment (Spengreb) [reply pkg/services/alerting/conditions/reducer.go]: Perhaps something along these lines would make more sense as it doesn't break any existing functionality:

Add additional boolean operator to calculcateDiff function to note if its signed or not
```go
func calculateDiff(series *tsdb.TimeSeries, allNull bool, value float64, fn func(float64, float64) float64, signed bool) (bool, float64) {
```

```go
        case "diff":
		allNull, value = calculateDiff(series, allNull, value, diff, false)
	case "diff_signed":
		allNull, value = calculateDiff(series, allNull, value, diff, true)
	case "percent_diff":
		allNull, value = calculateDiff(series, allNull, value, percentDiff, false)
	case "percent_diff_signed":
		allNull, value = calculateDiff(series, allNull, value, percentDiff, true)
```


```suggestion
				val := fn(first, points[i][0].Float64)
				if !signed {
					value = math.Abs(val)
				} else {
					value = val
				}
```

Comment (vikkyomkar) [reply pkg/services/alerting/conditions/reducer.go]: @bergquist sorry I couldn't understand how this change can break any existing functionality. Here I just moved the Abs function inside "var" and assigning the output result directly to "value" variable.

Can you pls help me understand the breaking point with some example?

Comment (bergquist) [reply pkg/services/alerting/conditions/reducer.go]: Before your change, `diff` and `percent_diff` was always using `math.Abs()`. 
With this change `diff` and `perfect_diff` with return a signed value. 

With @Spengreb suggestion it `diff` will keep returning an absolute number. So all active alert rule won't change behavior. 

I think `diff_abs` is a more common name but if we use `diff_signed` we avoid breaking changes. Perhaps we should have `diff_abs` and `diff_signed` to make it more clear what the diff returns.

Comment (Spengreb) [reply pkg/services/alerting/conditions/reducer.go]: So something like this?

```go
       case "diff_abs":
		allNull, value = calculateDiff(series, allNull, value, diff, false)
	case "diff_signed":
		allNull, value = calculateDiff(series, allNull, value, diff, true)
	case "percent_diff_abs":
		allNull, value = calculateDiff(series, allNull, value, percentDiff, false)
	case "percent_diff_signed":
		allNull, value = calculateDiff(series, allNull, value, percentDiff, true)
```

Comment (vikkyomkar) [reply pkg/services/alerting/conditions/reducer.go]: @bergquist Initially `diff` was not using `math.Abs()` but after a recent commit to [Extract common code for diff calculation](https://github.com/grafana/grafana/commit/28eaac3a9c7082e8c496005c1cb66b4b70a4f82f#diff-b5991af7e3497d6b806a6cb4659fa174) this breaking change was introduced ....

We were using `diff` with signed value in our alerting but after that recent commit we started facing issues....This PR is an attempt to revert the old breaking change along with adding new aggregators like `diff_abs` and `percent_diff_abs`

moreover using `diff_abs` and `diff_signed` will also be a breaking change as we are already using `diff` aggregator in our alerting. However if you suggest, I can rename `diff` and `percent_diff` to `diff_signed` and `percent_diff_signed` respectively

@spengreb As I had earlier mentioned, your logic of deciding `abs` or `signed` won't be true for some corner cases. feel free to run the test cases written by me to uncover the failing cases.

**Comment by marefr** [comment]
FYI found the PR which introduced referenced change (https://github.com/grafana/grafana/commit/28eaac3a9c7082e8c496005c1cb66b4b70a4f82f) and it's #15444

File: pkg/services/alerting/conditions/reducer.go (hunk 1 above)
Comment (bergquist) [reply pkg/services/alerting/conditions/reducer.go]: @vikkyomkar Thank you for finding that commit. 

As much as I dislike breaking changes I think we should introduce this change and break the behavior we introduced with 28eaac3a9c7082e8c496005c1cb66b4b70a4f82f .

Could you please merge the suggestions for the tests?

Comment (vikkyomkar) [reply pkg/services/alerting/conditions/reducer.go]: @bergquist test case values are updated

**Comment by vikkyomkar** [comment]
@bergquist can we merge this PR ?

**Review by bergquist — APPROVED** [review]
Looks good!

@marefr How do we highlight breaking changes in the Changelog?

**Comment by marefr** [comment]
@bergquist see https://github.com/grafana/grafana/blob/master/CHANGELOG.md#breaking-changes. Depending on what kind of change it is we sometime also mention it in the [upgrade docs](https://grafana.com/docs/grafana/latest/installation/upgrading/#upgrading-to-v6-6)

**Comment by marefr** [comment]
Ping @bergquist see my comment ^

**Comment by vikkyomkar** [comment]
@bergquist @marefr when should we expect this change to be merged ?

**Comment by bergquist** [comment]
Thank you for contributing and thank you for for being so patient with me :)
