### PR TITLE
Make Explore panel link work when grafana served from sub url

### LINKED ISSUE #22201: Jump to explore broken in latest master
We are running commit 961cb6b284 with the web-prefix of `/grafana`. When I try to jump to explore from a dashboard panel, it tries to open the url: `/grafana/grafana/explore?.....`, adding an extra `/grafana` thereby 404-ing.

### PR DESCRIPTION
**Pull request by dprokop**
Fixes https://github.com/grafana/grafana/issues/22201

### CODE REVIEW

File: public/app/core/utils/explore.ts [hunk 1]
```diff
@@ -109,7 +109,7 @@ export async function getExploreUrl(args: GetExploreUrlArguments) {
     url = renderUrl('/explore', { left: exploreState });
   }
   const finalUrl = config.appSubUrl + url;
```
Comment (dprokop) [inline public/app/core/utils/explore.ts]:
```suggestion
```

**Review by peterholmberg — APPROVED** [review]
Works! 🎉
