### PR TITLE
Cloud Monitoring: Reduce request size when listing labels

### LINKED ISSUE #44190: Grafana crash due to huge response for Cloud Monitoring `HEADERS` request
**What happened**:
In some GCP project which has too many k8s metrics, Grafana crash before query finished.

**What you expected to happen**:
Query finished without crash.

**How to reproduce it (as minimally and precisely as possible)**:
1. Prepare environment which has too many time series for one metric type
2. Build query for the metric in Explore
image
3. Run Query

**Anything else we need to know?**:
After investigate this issue, I notice that HEADERS response size is too huge, in our env, it is 74.56MB.

We use Grafana Cloud, and I guess the instance memory is limited.
So crash is caused by OOM. If the instance has enough memory, query will finish without error.

Cloud Monitoirng API provide the way to limit response size.
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list
> If view is set to HEADERS, this is the maximum number of TimeSeries returned.

CloudWatch datasource already limit metric suggestion response size.
https://github.com/grafana/grafana/pull/31788

Cloud Monitoring should limit the size at here.
https://github.com/grafana/grafana/blob/v8.3.3/public/app/plugins/datasource/cloud-monitoring/datasource.ts#L140-L158

**Environment**:
- Grafana version: Grafana v8.3.3 (30bb7a93c)
- Data source type & version: Cloud Monitoring
- OS Grafana is installed on: n/a
- User OS & Browser: Firefox & Windows 10
- Grafana plugins:
- Others:
Grafana is running on Grafana Cloud.

### PR DESCRIPTION
**Pull request by mtanda**
**What this PR does / why we need it**:
Cloud Monitoring amplify response size from v8.3.
It cause memory shortage and crash in some environment.

By splitting meta data and relocate it to each frames, the response size could be reduced.
I tested this change locally, and confirm that response size is significantly reduced. (63.06MB -> 3.60MB)

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/44190

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/datasource/cloud-monitoring/datasource.ts [hunk 1]
```diff
@@ -179,7 +179,18 @@ export default class CloudMonitoringDatasource extends DataSourceWithBackend<
           const dataQueryResponse = toDataQueryResponse({
             data: data,
           });
-          return dataQueryResponse?.data[0]?.meta?.custom?.labels ?? {};
+          return _map(dataQueryResponse?.data, 'meta.custom.labels')
+            .filter((p) => !!p)
+            .reduce((acc, labels) => {
+              for (let key in labels) {
+                if (acc[key]) {
```
Comment (andresmgot) [inline public/app/plugins/datasource/cloud-monitoring/datasource.ts:186]: you would need to avoid pushing labels that are already there:

Screenshot from 2022-01-24 12-00-13

**Review by andresmgot — COMMENTED** [review]
Let me know if I understood this properly:

Before, all labels were added to all frames, which caused big response sizes. Now only the labels related to a frame are added and in the fronted we evaluate all the frames (rather than the first) to look for all the different labels.

The approach looks good to me, we should add test to ensure that we are enforcing this behavior. Letting @sunker to also review this in case there is something I am missing.

File: public/app/plugins/datasource/cloud-monitoring/datasource.ts [hunk 2]
```diff
@@ -179,7 +179,18 @@ export default class CloudMonitoringDatasource extends DataSourceWithBackend<
           const dataQueryResponse = toDataQueryResponse({
             data: data,
           });
-          return dataQueryResponse?.data[0]?.meta?.custom?.labels ?? {};
+          return _map(dataQueryResponse?.data, 'meta.custom.labels')
```
Comment (sunker) [inline public/app/plugins/datasource/cloud-monitoring/datasource.ts:182]: No need to import `map` from lodash - just use `dataQueryResponse?.data.map((f) => f.meta.custom.labels)`

File: public/app/plugins/datasource/cloud-monitoring/datasource.ts [hunk 3]
```diff
@@ -179,7 +179,18 @@ export default class CloudMonitoringDatasource extends DataSourceWithBackend<
...
+            .filter((p) => !!p)
+            .reduce((acc, labels) => {
+              for (let key in labels) {
+                if (acc[key]) {
+                  acc[key].push(...labels[key]);
```
Comment (sunker) [inline public/app/plugins/datasource/cloud-monitoring/datasource.ts:187]: You just want to push the key, or am I missing something? 
`acc[key].push(labels[key])`

**Review by sunker — COMMENTED** [review]
Thanks for opening this PR @mtanda! Also think the approach looks good. Just fix the comments that we've added. Would also be great with a test that verifies the merging of labels in the datasource.ts file.

**Comment by mtanda** [comment]
> Let me know if I understood this properly:
> 
> Before, all labels were added to all frames, which caused big response sizes. Now only the labels related to a frame are added and in the fronted we evaluate all the frames (rather than the first) to look for all the different labels.

Yes, I do that. I think it is only way to reduce response size with plugin sdk.

File: pkg/tsdb/cloudmonitoring/time_series_query.go [hunk 4]
```diff
@@ -239,27 +238,25 @@ func (timeSeriesQuery cloudMonitoringTimeSeriesQuery) parseResponse(queryRes *ba
...
 		if frame.Meta != nil {
 			frame.Meta.Custom = customFrameMeta
 		} else {
 			frame.SetMeta(&data.FrameMeta{Custom: customFrameMeta})
 		}
 	}
+	if len(response.TimeSeriesData) > 0 {
+		dl := timeSeriesQuery.buildDeepLink()
+		frames = addConfigData(frames, dl, response.Unit)
+	}
```
[the remark this answers is not in the document]
Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/time_series_query.go:247]: Sorry to confuse you. But, I didn't change it. Moving many code to for loop, git diff recognize this lines changed.

File: public/app/plugins/datasource/cloud-monitoring/datasource.ts (hunk 1 above)
Comment (mtanda) [reply public/app/plugins/datasource/cloud-monitoring/datasource.ts]: That's good point. I didn't check multiple Group bys.
I fixed it in https://github.com/grafana/grafana/pull/44365/commits/1b4ed422719df6e70d3d0e9746fafd8ce08911af .

File: public/app/plugins/datasource/cloud-monitoring/datasource.ts (hunk 3 above)
Comment (mtanda) [reply public/app/plugins/datasource/cloud-monitoring/datasource.ts]: It is wrong code.
And I notice that response format is not appropriate.

The value type of label map should be string, not string list.
I fixed the response format in https://github.com/grafana/grafana/pull/44365/commits/fc7bb7c5dc48ec964b195e4ec7241d423ed96030 .

And, fixed frontend in https://github.com/grafana/grafana/pull/44365/commits/1b4ed422719df6e70d3d0e9746fafd8ce08911af .

File: public/app/plugins/datasource/cloud-monitoring/datasource.ts (hunk 2 above)
Comment (mtanda) [reply public/app/plugins/datasource/cloud-monitoring/datasource.ts]: Thanks for advice, I tend to use lodash...
I fixed it in https://github.com/grafana/grafana/pull/44365/commits/5cf1cdf6a0a28b41ac882d345a67085002b6c6a0 .

File: public/app/plugins/datasource/cloud-monitoring/datasource.ts [hunk 5]
```diff
@@ -179,7 +179,24 @@ export default class CloudMonitoringDatasource extends DataSourceWithBackend<
...
+                acc[key].add(labels[key]);
+              }
+              return acc;
+            }, {});
+          return Object.fromEntries(
+            Object.entries(labels).map((l: any) => {
+              l[1] = Array.from(l[1]);
+              return l;
+            })
+          );
```
Comment (andresmgot) [inline public/app/plugins/datasource/cloud-monitoring/datasource.ts:199]: A slightly simpler solution:

 ```suggestion
          const labels = dataQueryResponse?.data
            .map((f) => f.meta?.custom?.labels)
            .filter((p) => !!p)
            .reduce((acc, labels) => {
              for (let key in labels) {
                if (!acc[key]) {
                  acc[key] = [];
                }
                if (labels[key] && !acc[key].includes(labels[key])) {
                  acc[key].push(labels[key]);
                }
              }
              return acc;
            }, {});
          return labels;
```

Comment (andresmgot) [reply public/app/plugins/datasource/cloud-monitoring/datasource.ts:199]: (I also noticed that some labels were empty, that code removes those)

**Review by andresmgot — COMMENTED** [review]
LGTM, just one minor comment to simplify the frontend code.

File: public/app/plugins/datasource/cloud-monitoring/datasource.ts (hunk 5 above)
Comment (mtanda) [reply public/app/plugins/datasource/cloud-monitoring/datasource.ts:199]: Thanks for advice!
Yes, using includes() is simpler.
But, I don’t want to use O(n) function in loop.
In some env, I guess the number of labels is too big. (I may worry too much)
Using Set is intended.

Comment (mtanda) [reply public/app/plugins/datasource/cloud-monitoring/datasource.ts:199]: In our env, Cloud Monitoring record more than 1000 pod_name labels.
Screenshot 2022-01-26 091158

I think Set is faster than includes() if list is long.
https://www.measurethat.net/Benchmarks/Show/16868/1/includes-vs-has-20220126

Comment (andresmgot) [reply public/app/plugins/datasource/cloud-monitoring/datasource.ts]: I am not sure if the performance benefit goes away with the later loop but anyway it's fine

**Review by andresmgot — APPROVED** [review]
Thanks for the patch!

**Comment by mtanda** [comment]
Thanks for merge!
