### PR TITLE
Fix: Preserve Jaeger base path when constructing search request

### LINKED ISSUE #108651: Bug Jaeger: Grafana v12.1.0 unsupported path requested: "/api/traces"
### What happened?

Hi there,
After upgrading to Grafana v12.1.0, i get this error message in Jaeger.
`unsupported path requested: "/api/traces"`

Image

i don't see this error in Grafana version v12.0.2.

### What did you expect to happen?

Explore without any problems with the Jaeger plugin

### Did this work before?

yes with Grafana v12.0.2

### How do we reproduce it?

Upgrade to Grafana v12.1.0 and use the Jaeger plugin in Explore.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: v12.1.0
OS: Windows 11
Browser:

### Grafana platform?

Docker

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by itsgareth**
this pr fixes https://github.com/grafana/grafana/issues/108651, where jaeger search requests fail if the configured data source url include a subpath.

before this fix:
a url like `http://localhost:1234/abc/` would become `http://localhost:1234/api/traces`, losing the `/abc/` subpath.

this has been fixed by using `url.JoinPath` to correctly append the `/api/traces` segment, preserving any existing path. the url now resolves properly as: `http://localhost:1234/abc/api/traces`

### CODE REVIEW

File: pkg/tsdb/jaeger/client.go [hunk 1]
```diff
@@ -115,11 +115,15 @@ func (j *JaegerClient) Operations(s string) ([]string, error) {
 }
 
 func (j *JaegerClient) Search(query *JaegerQuery, start, end int64) ([]TraceResponse, error) {
-	jaegerURL, err := url.Parse(j.url)
+	u, err := url.JoinPath(j.url, "/api/traces")
+	if err != nil {
+		return []TraceResponse{}, fmt.Errorf("failed to parse Jaeger URL: %w", err)
```
Comment (itsmylife) [inline pkg/tsdb/jaeger/client.go]: Don't we use error source for jaeger?

File: pkg/tsdb/jaeger/client.go [hunk 2]
```diff
@@ -115,11 +115,15 @@ func (j *JaegerClient) Operations(s string) ([]string, error) {
 }
 
 func (j *JaegerClient) Search(query *JaegerQuery, start, end int64) ([]TraceResponse, error) {
-	jaegerURL, err := url.Parse(j.url)
+	u, err := url.JoinPath(j.url, "/api/traces")
```
Comment (itsmylife) [inline pkg/tsdb/jaeger/client.go:118]: Can you cover this in unit tests please?

**Review by itsmylife — APPROVED** [review]
This LGTM. I left some comments. It would be nice if we cover the sub path in unit tests.

File: pkg/tsdb/jaeger/client.go [hunk 3]
```diff
@@ -115,11 +115,15 @@ func (j *JaegerClient) Operations(s string) ([]string, error) {
...
+	if err != nil {
+		return []TraceResponse{}, fmt.Errorf("failed to join url path: %w", err)
```
Comment (ivanahuckova) [inline pkg/tsdb/jaeger/client.go]:
```suggestion
		return []TraceResponse{}, backend.DownstreamError(fmt.Errorf("failed to join url path: %w", err))
```
