### PR TITLE
Correlation: Fix loki dataplane field change

### LINKED ISSUE #94075: Correlations: Handle loki dataplane log lines, even if different field is used
### What happened?

There is a feature to move loki logs to have standardized fields. This is currently behind a feature flag, but is being moved to be GA'd soon.

For correlations, the user explicitly defines what field the correlation is attached to. Commonly, the `Line` field is used, as that is where the log line data is. The `Line` field can then be transformed using `logfmt` or a regular expression to extract out data for the correlation.

In the standardization, the `Line` field is named `body`. The field can actually be named whatever, and with the data plane, there are other settings to indicate the field is the log line.

We would like to support this working, even if the Correlation explicitly defined the Correlation to use `Line`. 

If the feature flag is on, the source data source is Loki, and the results field is specified as `Line`, use the data plane information to find the `body` field and use that as the results field instead for the correlation.

### What did you expect to happen?

Correlations should work as expected, even if the underlying information changes.

### Did this work before?

No, this would have always been broken when the feature flag is enabled.

### How do we reproduce it?

1. Create a correlation for a log line, using the `Line` field, and check it works as expected
2. Enable `lokiLogsDataplane`
3. Try to find the correlation again and see it no longer works.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana main

### Grafana platform?

None

### Datasource(s)?

Loki

### PR DESCRIPTION
**Pull request by gelicia**
**What is this feature?**

This fixes a bug where loki logs using the new dataplane format broke existing correlations. 

Correlations were built using an explicitly defined data frame field name to attach the correlation to. With the data plane, the field name for loki logs changes from `Line` to something else - by default `body`. 

This is a small function that sees if we are in the scenario where the correlation was using the former field name, and will find and use whatever the data plane field is now.

**Why do we need this feature?**

To have previously built correlations work with the loki data plane project.

**Which issue(s) does this PR fix?**:

Fixes #94075 

**Special notes for your reviewer:**

I went with this instead of a data migration to make it less complicated between provisioned and non provisioned correlations. I am willing to change my approach to a migration and a warning for provisioned correlations if that seems more appropriate. We can use this as a stopgap and work on what a longer term solution may look like. 

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/correlations/utils.ts [hunk 1]
```diff
@@ -83,6 +84,27 @@ const decorateDataFrameWithInternalDataLinks = (dataFrame: DataFrame, correlatio
...
+*/
+const fixLokiDataplaneFields = (correlations: CorrelationData[], dataFrame: DataFrame) => {
+  return correlations.map((correlation) => {
+    if (
+      correlation.source.meta?.id === 'loki' &&
+      config.featureToggles.lokiLogsDataplane === true &&
+      correlation.config.field === 'Line'
+    ) {
+      const logsFrame = parseLogsFrame(dataFrame);
+      if (logsFrame != null && logsFrame.bodyField.name !== undefined) {
```
Comment (ifrost) [inline public/app/features/correlations/utils.ts:100]: Would it make sense to skip switching to `body` in case the `Line` field exists? Not sure if it's possible that both would exist at the same time 🤔

File: public/app/features/correlations/utils.ts [hunk 2]
```diff
@@ -43,7 +44,7 @@ export const attachCorrelationsToDataFrames = (
     }
 
     const sourceCorrelations = correlations.filter((correlation) => correlation.source.uid === dataSourceUid);
-    decorateDataFrameWithInternalDataLinks(dataFrame, sourceCorrelations);
+    decorateDataFrameWithInternalDataLinks(dataFrame, fixLokiDataplaneFields(sourceCorrelations, dataFrame));
```
Comment (ifrost) [inline public/app/features/correlations/utils.ts:47]: This would fix it only in runtime. The underlying correlation would still stay the same in the database, wouldn't it? I wonder if in long-run it'd be better to allow data sources to (somehow 🤷 ) migrate correlations 🤔

File: public/app/features/correlations/utils.test.ts [hunk 3]
```diff
@@ -68,10 +70,27 @@ describe('correlations utils', () => {
     // Prometheus value (linked to Elastic)
     expect(testDataFrames[2].fields[0].config.links).toHaveLength(1);
   });
+
+  it('changes the config field if loki dataplane is being used and the correlation is pointing to the legacy body field (Line)', () => {
+    config.featureToggles.lokiLogsDataplane = true;
```
Comment (matyax) [inline public/app/features/correlations/utils.test.ts:75]: You may want to store and reset to the original state after the test.

See https://github.com/grafana/grafana/pull/96226/files#diff-9956354aca04b9ba46fbe2256d14bbf8567f20179b437be2074afd13fc19cf54R452

File: public/app/features/correlations/utils.ts (hunk 1 above)
Comment (matyax) [reply public/app/features/correlations/utils.ts:100]: Oh yes, both should be supported because `lokiLogsDataplane` is not GA https://github.com/grafana/grafana/blob/main/pkg/services/featuremgmt/registry.go#L344

**Review by matyax — COMMENTED** [review]
Besides one small comment about the feature flag in the test, and also supporting Line, looks good to merge!

File: public/app/features/correlations/utils.ts (hunk 1 above)
Comment (matyax) [reply public/app/features/correlations/utils.ts:100]: Taking my comment back as I misread.

**Review by matyax — APPROVED** [review]
Approving, since I misread on my previous comment 👍

**Comment by matyax** [comment]
Hey! I'm unsure if there's anything blocking this PR, but we'd like to reenable dataplane logs after this one is merged.

**Comment by gelicia** [comment]
> Hey! I'm unsure if there's anything blocking this PR, but we'd like to reenable dataplane logs after this one is merged.

@matyax I was looking to merge this one when drone was down, and then I was out for a couple days. I'll get the drone build passing today and then merge it. thank you for your patience!
