### PR TITLE
Alerting: add missing yaml tag to mute time struct

### LINKED ISSUE #53988: mute times: invalid object specification: missing name in mute time interval
**What happened**:
With the newest version of Grafana, version 9.1.0, we tried to provision configurations of the alerting system. But when provisioning a mute timing as described in the [documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/#mute-timings) the following error is raised:

```
logger=provisioning.alerting t=2022-08-20T06:31:55.7978294Z level=debug msg="looking for alerting provisioning files" path=/etc/grafana/provisioning/alerting
logger=provisioning.alerting t=2022-08-20T06:31:55.7978732Z level=debug msg="parsing alerting provisioning file" path=/etc/grafana/provisioning/alerting file.Name=mute-timing.yml
logger=provisioning.alerting t=2022-08-20T06:31:55.7979596Z level=info msg="starting to provision alerting"
logger=provisioning.alerting t=2022-08-20T06:31:55.797983Z level=debug msg="read all alerting files" file_count=1
Failed to start grafana. error: mute times: invalid object specification: missing name in mute time interval
mute times: invalid object specification: missing name in mute time interval
```

This happens when provisioning the template file from the [documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/#mute-timings):

```yaml
# config file version
apiVersion: 1

# List of mute time intervals to import or update
muteTimes:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> name of the mute time interval, must be unique
    name: mti_1
    # <list> time intervals that should trigger the muting
    #        refer to https://prometheus.io/docs/alerting/latest/configuration/#time_interval-0
    time_intervals:
      - times:
          - start_time: '06:00'
            end_time: '23:59'
        weekdays: ['monday:wednesday', 'saturday', 'sunday']
        months: ['1:3', 'may:august', 'december']
        years: ['2020:2022', '2030']
        days_of_month: ['1:5', '-3:-1']
```

**What you expected to happen**:
We expected provisioning of rules, contact points, notificcation policies and mute timings works as described in the documentation and mute timings _can_ be provisioned.

**How to reproduce it (as minimally and precisely as possible)**:
Provision the given yaml as described in the [documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/#provision-grafana).

**Anything else we need to know?**:
We reproduced the behaviour within a docker installation with the `example.ini` as `grafana.ini`. Only the logging was edited, to provide detailed information (`filters = provisioning.alerting:debug`).

The configuration folder from within the docker container was mapped as volume:

```yaml
version: '3'

services:
  grafana:
    image: grafana/grafana:9.1.0
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-config/:/etc/grafana/
```

**Environment**:
- Grafana version: Grafana Version 9.1.0 as Docker image (`REPOSITORY: grafana/grafana, TAG 9.1.0, IMAGE ID: 8a7462f12bfd`)
- OS Grafana is installed on: Docker image OS
- Grafana plugins: _none_

### PR DESCRIPTION
**Pull request by JohnnyQQQQ**
Fixes #53988

### CODE REVIEW

File: pkg/services/ngalert/api/tooling/definitions/provisioning_mute_timings.go [hunk 1]
```diff
@@ -69,8 +69,8 @@ type MuteTimingPayload struct {
 
 // swagger:model
 type MuteTimeInterval struct {
-	config.MuteTimeInterval
-	Provenance models.Provenance `json:"provenance,omitempty"`
+	config.MuteTimeInterval `json:",inline" yaml:",inline"`
```
Comment (alexweav) [inline pkg/services/ngalert/api/tooling/definitions/provisioning_mute_timings.go:72]: I see how this fixes yaml, but does this also change the JSON shape handled by the API? Does JSON somehow default to inline? Since this is an API model, a change to the JSON shape may break clients.

Comment (grobinson-grafana) [reply pkg/services/ngalert/api/tooling/definitions/provisioning_mute_timings.go:72]: @alexweav it defaults to inline, here is a simple example:

```
package main

import (
	"encoding/json"
	"fmt"
)

type Animal struct {
	Species string `json:"species"`
}

type Dog struct {
	Animal
	Breed string `json:"breed"`
}

func main() {
	var d Dog
	json.Unmarshal([]byte(`{"species": "canine", "breed": "labrador"}`), &d)
	fmt.Println(d)
}
```

```
go run main.go
{{canine} labrador}
```

**Review by alexweav — APPROVED** [review]

File: pkg/services/ngalert/api/tooling/definitions/provisioning_mute_timings.go (hunk 1 above)
Comment (alexweav) [reply pkg/services/ngalert/api/tooling/definitions/provisioning_mute_timings.go:72]: Makes sense. Thanks for the example @grobinson-grafana

Comment (JohnnyQQQQ) [reply pkg/services/ngalert/api/tooling/definitions/provisioning_mute_timings.go:72]: Out of convenience, I added both, even if the problem only exists when using the YAML parser. As George mentioned, it won't change the shape as it's just restating the default behavoir.
