### PR TITLE
GrafanaUI: Define tooltip or aria-label as required for IconButton

### LINKED ISSUE #66346: ID 260316: [Programmatic Access - Simon - Value Mapping]: Aria-label is not defined for "Remove" button under "Value mapping" dialog.
### **User Experience:** 
Screen reader dependent users may get misguided while navigating, if the screen reader is not announcing the proper name of the controls present on the page as they will not understand it's purpose.
_Note: User credentials should NOT be included in the bug._

### **Repro Steps:**  

- Open #Url: [play.grafana.org](https://play.grafana.org/)  Sign in with valid credentials. "Home" page appears. 
- Navigate the Feature Showcase pane heading and select it. 
- Navigate the expanded Dropdown and select the "Edit" menu item.  
- Navigate the page "Edit" page which appears.  
- Navigate to the "All" buttons and select it. 
- Navigate to "Value Mapping" button and expand it.  
- Navigate all the controls present under it. 
- Run AI tool. Verify the issue

**Actual Result:** 
Issue: `Aria-label` is not defined for "Remove" button under "Value mapping" dialog. 
Observation: Screen reader is announcing as "Button" when focus moves to it.

**Expected Result:** 
`Aria-label` should be defined for "Remove" button under "Value mapping" dialog.
_Note: Same issue exists with 'Copy" button under "Value mapping" dialog. Same issue appears for Explore->Query patterns. samw issue appears for alerting->alerting group_s

**Issue:** 
Ensures buttons have discernible text (button-name - https://accessibilityinsights.io/info-examples/web/button-name) 

**Target application:**
1 -Time series graphs - Grafana - https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1&editPanel=1&showCategory=Value%20mappings
 
**Element path:**
`button[data-testid="remove-value-mapping"]`

 **Snippet:** 
`<button aria-label=""data-testid="remove-value-mapping" class="css-x1vujn">`

**How to fix:** 
Fix all of the following:

- Element does not have inner text that is visible to screen readers   
- `aria-label` attribute does not exist or is empty 
- `aria-labelledby` attribute does not exist, references elements that do not exist or references elements that are empty   
- Element has no `title` attribute   
- Element's default semantics were not overridden with `role="none"` or `role="presentation"`

**Environment:** 
Microsoft Edge version 105.0.1329.1
This accessibility issue was found using Accessibility Insights for Web 2.32.0 (axe-core 4.4.1), a tool that helps find and fix accessibility issues.

### **Severity:**
`SEV2`

### **Area:**
`Value Mappings Modal` / `IconButton` Component (Saga Design System)

### PR DESCRIPTION
**Pull request by L-M-K-B**
**What is this feature?**
In order to make sure every IconButton provides information about its purpose I now defined the tooltip or aria-label as required.

**Why do we need this feature?**
A11y reason: In case there is no aria-label set the tooltip is used to provide the required information for screen readers.
Consistency in GrafanaUI: Adding IconButton without proper information can be misleading and frustrating for users. This applies to all IconButtons.

**Who is this feature for?**
Everyone

**Which issue(s) does this PR fix?**:
Fixes #66346

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] The docs are updated

# Release notice breaking change

For accessibility reasons `tooltip` or `aria-label` are now required properties for `IconButton`. In order to continue to use `IconButton`, you must ensure all `IconButton` components have  a corresponding tooltip or aria-label text. The tooltip text will also be used as the aria-label if you didn't set one separately. In case you add an aria-label the IconButton will not show a tooltip.

### CODE REVIEW

**Review by mckn — APPROVED** [review]
This is a good change and I like that we are improving a11y! In regards to plugins, I would say it is okay to proceed with this change as long as we don't write any code that relies on the properties being available since the grafana-packages are provided during runtime.

Plugin developers will get an error during build time when upgrading the grafana-packages which feels okay since it is really easy to fix.

Can you also add something in the migration guide from 10.0.x -> 10.1.x about this being a requirement and something that the plugin authors need to provide while upgrading the packages?

https://github.com/grafana/grafana/tree/main/docs/sources/developers/plugins/migration-guide

**Review by ckbedwell — COMMENTED** [review]
In full support of this change!

I'd even be tempted to go one step further and make the visual tooltip always required and it doubles up as the aria-label if one isn't explicitly supplied but that might be too prescriptive...

File: packages/grafana-ui/src/components/IconButton/IconButton.tsx [hunk 1]
```diff
@@ -15,24 +15,38 @@ export type IconButtonVariant = 'primary' | 'secondary' | 'destructive';
...
   /** Type of the icon - mono or default */
   iconType?: IconType;
+  /** Variant to change the color of the Icon */
+  variant?: IconButtonVariant;
+}
+
+interface BasePropsWithTooltip extends BaseProps {
   /** Tooltip content to display on hover */
-  tooltip?: PopoverContent;
+  tooltip: PopoverContent;
```
[the remark this answers is not in the document]
Comment (L-M-K-B) [reply packages/grafana-ui/src/components/IconButton/IconButton.tsx:31]: @ckbedwell I changed the component quite a lot and after discussing what if the tooltip was not a string we decided to keep it as undefined for now. This use case doesn't occur too often so it should be fine.

We also discussed within the Frontend Platform team whether it makes sense to always require a tooltip and we identified some use cases in Grafana where a tooltip is not useful. For instance when IconButtons are used to expand context. They show a chevron and we think the icon is unambiguous in this case.

File: packages/grafana-ui/src/components/IconButton/IconButton.tsx [hunk 2]
```diff
@@ -15,76 +15,92 @@ export type IconButtonVariant = 'primary' | 'secondary' | 'destructive';
...
-    } else {
-      limitedIconSize = size;
-    }
-
-    const styles = getStyles(theme, limitedIconSize, variant);
-    const tooltipString = typeof tooltip === 'string' ? tooltip : '';
-
-    // When using tooltip, ref is forwarded to Tooltip component instead for https://github.com/grafana/grafana/issues/65632
-    const button = (
+export type Props = BasePropsWithTooltip | BasePropsWithAriaLabel;
```
Comment (tskarhed) [inline packages/grafana-ui/src/components/IconButton/IconButton.tsx:43]: I like this. It really explains the `if ('tooltip' in props)` part further down.

**Review by tskarhed — APPROVED** [review]

File: packages/grafana-ui/src/components/IconButton/IconButton.tsx [hunk 3]
```diff
@@ -15,76 +15,92 @@ export type IconButtonVariant = 'primary' | 'secondary' | 'destructive';
...
+    const { name, iconType, className, tooltip, tooltipPlacement, ...restProps } = props;
+    return (
+      <Tooltip ref={ref} content={tooltip} placement={tooltipPlacement}>
+        <button
+          {...restProps}
+          ref={buttonRef}
+          aria-label={ariaLabel}
+          className={cx(styles.button, className)}
+          type="button"
+        >
```
Comment (JoaoSilvaGrafana) [inline packages/grafana-ui/src/components/IconButton/IconButton.tsx:84]: This button seems to be the same as the one in line 92 (unless I'm missing something). What is the reason why we changed it to duplicate the code instead of just declaring the button and using it in the if/else like we had before?

File: packages/grafana-ui/src/components/IconButton/IconButton.story.tsx [hunk 4]
```diff
@@ -30,7 +30,8 @@ const meta: Meta<typeof IconButton> = {
     tooltip: 'sample tooltip message',
     tooltipPlacement: 'top',
     variant: 'secondary',
-    ariaLabel: 'sample aria-label content',
+    ariaLabel: 'this property is deprecated',
```
Comment (JoaoSilvaGrafana) [inline packages/grafana-ui/src/components/IconButton/IconButton.story.tsx:33]: I think if we are telling people not to use this anymore we should remove it from the controls. They should be able to see the deprecation warning on the props list.

Also, I think this `aria-label` will never be used because if we are setting a `tooltip` prop (even if it is an empty string), it always goes through that `if`. Maybe we should have another story for `IconButton` without `tooltip` prop? Otherwise we could have to have a more complex control here that deletes the tooltip prop?

**Review by JoaoSilvaGrafana — COMMENTED** [review]
Looks good otherwise!

File: packages/grafana-ui/src/components/IconButton/IconButton.story.tsx (hunk 4 above)
Comment (L-M-K-B) [reply packages/grafana-ui/src/components/IconButton/IconButton.story.tsx:34]: Done.

File: packages/grafana-ui/src/components/IconButton/IconButton.story.tsx [hunk 5]
```diff
@@ -131,4 +137,16 @@ const RenderBackgroundScenario = ({ background }: ScenarioProps) => {
   );
 };
 
+export const ExamplesWithoutTooltip = () => {
+  const sizes: IconSize[] = ['xs', 'sm', 'md', 'lg', 'xl'];
+
+  return (
+    <HorizontalGroup justify="center">
```
Comment (JoaoSilvaGrafana) [inline packages/grafana-ui/src/components/IconButton/IconButton.story.tsx:144]: Maybe a little text here to explain that in this case we are using the aria-label? Otherwise this is a strange storybook story 😄

File: packages/grafana-ui/src/components/IconButton/IconButton.story.tsx [hunk 6]
```diff
@@ -131,4 +137,16 @@ const RenderBackgroundScenario = ({ background }: ScenarioProps) => {
...
+      {sizes.map((size) => {
+        return <IconButton key={size} name="angle-down" size={size} aria-label="aria-label example" />;
```
Comment (JoaoSilvaGrafana) [inline packages/grafana-ui/src/components/IconButton/IconButton.story.tsx:146]: `aria-label` could be a control here, what do you think?

File: packages/grafana-ui/src/components/IconButton/IconButton.story.tsx (hunk 5 above)
Comment (L-M-K-B) [reply packages/grafana-ui/src/components/IconButton/IconButton.story.tsx:144]: That's true. I assumed that people would read the docs but I know this sounds silly. 😅

File: packages/grafana-ui/src/components/IconButton/IconButton.story.tsx [hunk 7]
```diff
@@ -43,7 +51,7 @@ export const Basic: StoryFn<typeof IconButton> = (args: IconButtonProps) => {
   return <IconButton {...args} />;
 };
 
-export const ExamplesSizes = () => {
+export const ExamplesSizes = (args: BasePropsWithTooltip) => {
```
Comment (JoaoSilvaGrafana) [inline packages/grafana-ui/src/components/IconButton/IconButton.story.tsx:54]: I think we should disable controls for these 'Examples' stories, it is a bit confusing that most of them don't do anything.

File: packages/grafana-ui/src/components/IconButton/IconButton.story.tsx [hunk 8]
```diff
@@ -101,31 +143,30 @@ export const ExamplesBackground = () => {
   );
 };
 
-const RenderBackgroundScenario = ({ background }: ScenarioProps) => {
+export const ExamplesWithoutTooltip = (args: BasePropsWithAriaLabel) => {
```
Comment (JoaoSilvaGrafana) [inline packages/grafana-ui/src/components/IconButton/IconButton.story.tsx:146]: Ok... 👀  I know I was the one who suggested this, but now after seeing this story and how we say we do not recommend using this, maybe it is not necessary? 😅  What do you think?

Comment (L-M-K-B) [reply packages/grafana-ui/src/components/IconButton/IconButton.story.tsx:146]: I find it much more handy for tooltip in comparison to aria-label. For tooltip it helps to see how it would look like when using different descriptions. For aria-label it doesn't make much sense.
So I will remove the control for aria-label but I would like to keep it for tooltip.

File: packages/grafana-ui/src/components/IconButton/IconButton.story.tsx (hunk 7 above)
Comment (L-M-K-B) [reply packages/grafana-ui/src/components/IconButton/IconButton.story.tsx:48]: I'll have a look at which props we can get rid of.

File: packages/grafana-ui/src/components/IconButton/IconButton.story.tsx (hunk 8 above)
Comment (JoaoSilvaGrafana) [reply packages/grafana-ui/src/components/IconButton/IconButton.story.tsx]: Yep I'd say remove the story that doesnt have tooltips completely 🤷

File: packages/grafana-ui/src/components/IconButton/IconButton.story.tsx (hunk 7 above)
Comment (L-M-K-B) [reply packages/grafana-ui/src/components/IconButton/IconButton.story.tsx:48]: Since controls are set for all stories at the same time I removed some props from the controls that don't make sense. I would like to to keep the others as they are used in the basic story.

Comment (JoaoSilvaGrafana) [reply packages/grafana-ui/src/components/IconButton/IconButton.story.tsx:48]: You can exclude controls from particular stories, look at `ConfirmModal` for example. You can do:

```
ExamplesSizes.parameters = {
  controls: {
    exclude: [],
  },
};
```

Comment (L-M-K-B) [reply packages/grafana-ui/src/components/IconButton/IconButton.story.tsx:51]: Thanks a lot! I implemented it as you suggested.
