### PR TITLE
Transformations: Fix clearing of transformation select fields

### LINKED ISSUE #53915: Transforms: Unable to clear select fields for Outer join and Grouping to matrix
**What happened**:
Clicking the `x` to clear the select values for an Outer join or Grouping to matrix transformations does not clear the value.

The selects within the `GroupingToMatrixTransformerEditor` and `SeriesToFieldsTransformerEditor` have isClearable enabled, but when clicking the `x` to clear, seeing the following error in the console:
```
Uncaught TypeError: Cannot read properties of null (reading 'value')
```

**What you expected to happen**:
When clicking the `x`, I expect the field to be cleared.

**How to reproduce it (as minimally and precisely as possible)**:
* Create an Outer join or Grouping to matrix transformation
* Choose values for the appropriate select fields
* Click the `x` to clear the value. You will then see the error above

### PR DESCRIPTION
**Pull request by AlexKaracaoglu**
**What this PR does / why we need it**:
When trying to use the `x` to clear the values in the select fields for the Outer join and Grouping to matrix transformations, the following error occurs and the clearing does not occur successfully:
```
Uncaught TypeError: Cannot read properties of null (reading 'value')
```

Adding optional chaining operators to the erroring fields' `onChange` to allow for proper clearing.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/53915

### CODE REVIEW

File: public/app/features/transformers/editors/SeriesToFieldsTransformerEditor.tsx [hunk 1]
```diff
@@ -23,7 +23,7 @@ export const SeriesToFieldsTransformerEditor: React.FC<TransformerUIProps<Series
     (value: SelectableValue<string>) => {
       onChange({
         ...options,
-        byField: value.value,
+        byField: value?.value,
```
Comment (ryantxu) [inline public/app/features/transformers/editors/SeriesToFieldsTransformerEditor.tsx:26]: 🤣 -- fixed in my PR :)

**Review by ryantxu — APPROVED** [review]
