### PR TITLE
Alerting: recalculate EndsAt

### LINKED ISSUE #35539: New ngalert-based alerts constantly flap from resolved to active to their Contact Points
**What happened**:
We migrated to Grafana 8.0.0 and the new alerting system and since then, any alert that fires (and remains in an alerting condition) will notify its Contact Points of state changes that _Resolve_ and then _Alert_ continuously, every time the alert check runs. This leads to incidents being created/closed every N minutes in OpsGenie, or sequences of Resolved/Firing messages being posted to Slack.

When looking at the logs, it seems that these alerts are being resolved and then ~3 seconds later set to alerting once more.

One example (led to a Resolved message in Slack/OpsGenie)

image

Another example (led to an Alerting message in Slack/OpsGenie, on an alert that had actually been alerting for 6 hours already and had posted many pairs of Resolved/Firing messages):

image

These alerts are new `ngalert` alerts, running off an `InfluxDB` datasource. They are set up as follows:
image

image

Throughout all of these flaps from resolved/active, the state in the Alerting UI is actually accurate and doesn't flap:

image

**What you expected to happen**:

Once an alert is triggered, until it actually resolves, no RESOLVE message is sent to any of the Contact Points. 

**How to reproduce it (as minimally and precisely as possible)**:

We can reproduce this by creating a new alert in the new system and having it trigger and not resolve. Every N minutes it will send a RESOLVE/ACTIVE pair to all contact points.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: InfluxDB (built-in)
- OS Grafana is installed on: Ubuntu 20.04 using Docker
- User OS & Browser: Edge on Mac
- Grafana plugins: none
- Others: `ngalert` enabled

### PR DESCRIPTION
**Pull request by davidmparrott**
**What this PR does / why we need it**:
Changes the calculation of EndsAt to account for conditions that have a For duration that is shorter than IntervalSeconds. 

Added unit tests for new method to set EndsAt correctly

**Which issue(s) this PR fixes**:
Fixes #35539

**Special notes for your reviewer**:
Verified the issues and tested the fix with a Discord notifier running for approximately one hour. The flapping reported was not noticed in that time period.

### CODE REVIEW

**Comment by kylebrandt** [comment]
Maybe 8.0.3 + backport?

File: pkg/services/ngalert/state/state_test.go [hunk 1]
```diff
@@ -73,3 +75,93 @@ func TestNeedsSending(t *testing.T) {
...
+			testState: &State{},
+			testRule: &ngmodels.AlertRule{
+				IntervalSeconds: 10,
+			},
+			testResult: eval.Result{
+				EvaluatedAt: evaluationTime,
+			},
+		},
+		{
+			name:      "For: 0s Interval: 10s",
```
Comment (kylebrandt) [inline pkg/services/ngalert/state/state_test.go:100]: nitpick, not merge blocking.

But might be easier for people to follow tests the names have a "should clause" that describes the behavior. e.g. "EndsAt should be twice the interval if FOR is 0." - so worded a bit more spec-like.

Comment (davidmparrott) [reply pkg/services/ngalert/state/state_test.go]: Easy enough to add

**Review by kylebrandt — APPROVED** [review]
