### PR TITLE
Prometheus: Updates explore query editor to prevent it from throwing error on edit

### LINKED ISSUE #21604: Prometheus step field throws an error on edit - type change from uncontrolled to controlled
**What happened**:

Prometheus step field in Explore throws an error on edit, stating that the type of input field has changed from uncontrolled to controlled.

**What you expected to happen**:

Prometheus step field works properly.

**How to reproduce it (as minimally and precisely as possible)**:

Go to Explore, select Prometheus data source and start typing anything in the step field.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.0-pre (d2b08c8368)
- Data source type & version: Prometheus

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Updates PromExploreQueryEditor to prevent it from throwing an input error on edit. Moves PromExploreExtraField to a separate file. Refactors PromExploreQueryEditor to functional component.

**Which issue(s) this PR fixes**:

Fixes #21604

### CODE REVIEW

**Comment by aocenas** [comment]
Looks good to me, but can we add a basic test for the `PromExploreQueryEditor.tsx`? Just to test what was changed here as we do not have any right now.

Did not run it though so @kaydelaney can you check it too?

**Comment by kaydelaney** [comment]
Still seeing an error thrown the first time the step field is changed from the placeholder "auto" to some other value. Would also be nice if the field had some sort of validation (i.e. red border when the value isn't a valid interval string). Agree with @aocenas that a basic test would be nice as well

**Review by kaydelaney — DISMISSED** [review]
See previous comment

**Comment by Estrax** [comment]
Very basic test added, error fixed (just a very dumb typo). Validation is going to be added in a separate PR alongside additional tests.

File: public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx [hunk 1]
```diff
@@ -1,85 +1,63 @@
...
-    // Query target properties that are fully controlled inputs
-    this.state = {
-      // Fully controlled text inputs
-      interval: query.interval,
-    };
+export const PromExploreQueryEditor = memo(function PromExploreQueryEditor(props: Props) {
+  const { query, data, datasource, history, onChange, onRunQuery } = props;
+  const [step, setStep] = useState(query.interval);
+
+  function onChangeQueryStep(value: string, override?: boolean) {
```
Comment (aocenas) [inline public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx]: `override` does not seem to be ever set to `true`. Seems like `onRunQuery` won't ever be called.

File: public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx [hunk 2]
```diff
@@ -1,85 +1,63 @@
...
+    const { query, onChange, onRunQuery } = props;
+    if (onChange) {
```
Comment (aocenas) [inline public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx]: `onChange` seems to be required in the props. Is there a case where it is not supplied in props?

File: public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx [hunk 3]
```diff
@@ -1,85 +1,63 @@
...
-    this.query.expr = query.expr;
-  };
-
-  onIntervalChange = (e: React.SyntheticEvent<HTMLInputElement>) => {
-    const interval = e.currentTarget.value;
-    this.query.interval = interval;
-    this.setState({ interval });
-  };
-
-  onRunQuery = () => {
```
Comment (aocenas) [inline public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx]: Seems like before we updated query upstream only when query was run. Now it seems to happen only in `onChangeQueryStep`. Is that intentional? Is that changing behaviour?

File: public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx [hunk 4]
```diff
@@ -1,85 +1,63 @@
...
-              />
-            </div>
-          </div>
-        </PromQueryField>
-      </div>
-    );
   }
-}
+
+  useEffect(() => {
```
Comment (aocenas) [inline public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx]: Nitpick: Seems like we could do this inside the `onChangeFunc` handler. So that we call this directly when the value changes, without having to wait for update.

File: public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.test.tsx [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+    expect(wrapper).toMatchSnapshot();
+  });
+
+  it('should render PromQueryField with ExtraFieldElement', () => {
+    const wrapper = setup();
+    const onStepChange = (e: React.SyntheticEvent<HTMLInputElement>) => jest.fn();
+    const onReturnKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => jest.fn();
+
+    // workaround to "Received: serializes to the same string"
+    expect(JSON.stringify(wrapper.prop('ExtraFieldElement'))).toEqual(
```
Comment (aocenas) [inline public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.test.tsx]: We probably do not need to test exactly that it matches, that should handle the `PromExploreExtraField` test. It should probably be enough to just check if the `PromExploreExtraField` was rendered in the `wrapper`.

File: public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx (hunk 1 above)
Comment (Estrax) [reply public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx]: Right; it's a victim of a copypaste from `PromQueryField`. Fixed.

File: public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx (hunk 2 above)
Comment (Estrax) [reply public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx]: Yep, back then there was a weird issue causing errors - onChange was being detected as undefined. It was already fixed so I also fixed that.

File: public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx (hunk 3 above)
Comment (Estrax) [reply public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx]: It doesn't change behavior - we update query upstream using logic in `PromQueryField` when the query was run. There in `PromExploreQueryEditor` we care only about step value changes so we have a slightly simplified implementation there.

File: public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.test.tsx [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+
+describe('PromExploreQueryEditor', () => {
+  it('should render component', () => {
+    const wrapper = setup(shallow);
+    expect(wrapper).toMatchSnapshot();
+  });
+
+  it('should render PromQueryField with ExtraFieldElement', () => {
+    const wrapper = setup(render);
+    expect(wrapper.find('.explore-input--ml')).toHaveLength(1);
```
Comment (aocenas) [inline public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.test.tsx]: I just realised this test is probably at the wrong place. We already check if `PromExploreQueryEditor` is rendered correctly so no need to check it again here. On the other hand we changed `PromQueryField.tsx` so test if it correctly handles the `ExtraFieldElement` should be there.

File: public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx [hunk 7]
```diff
@@ -1,85 +1,55 @@
...
+          onChangeFunc={onStepChange}
+          onKeyDownFunc={onReturnKeyDown}
+          value={query.interval}
+        />
+      }
+    />
+  );
 }
+
+export default memo(PromExploreQueryEditor);
```
Comment (aocenas) [inline public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx]: Is there need to have both memo and non memo exports? If previously something used the `PromExploreQueryEditor` it got the PureComponent version. Now we changed that to non memoized version and add a new export for the memoized one but that seems to be used only in test.

**Review by aocenas — COMMENTED** [review]
Nice, looks better but still have 2 small comments.

File: public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx (hunk 7 above)
Comment (Estrax) [reply public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx]: Well, we use memoization to get some slight performance improvements (so it's going to be used as a default way to use a given component), but the non-memoized version is useful for testing as enzyme still has problems working with memos.

Comment (aocenas) [reply public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx]: But if I see correctly the default memoized version is used only in the test, while the non memoized version is going to be used everywhere else as that is what module.ts uses, or am I seeing that wrong?

Comment (Estrax) [reply public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.tsx]: Memoized export should be used pretty much everywhere, non-memoized one is only for tests. Fixed the import in `module.ts`.

**Comment by Estrax** [comment]
Need to check what's the reason the test fails. Looks like the problem is with slate plugin that doesn't see the `window.getSelector()` method.

File: public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.test.tsx [hunk 8]
```diff
@@ -1,6 +1,7 @@
 import React from 'react';
-import { shallow, render } from 'enzyme';
+import { shallow, mount } from 'enzyme';
 import PromExploreQueryEditor from './PromExploreQueryEditor';
```
Comment (aocenas) [inline public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.test.tsx]: So do we want to use memoized version here? I thought you mentioned the memoization creates issues in the tests.

Comment (Estrax) [reply public/app/plugins/datasource/prometheus/components/PromExploreQueryEditor.test.tsx]: Yes, changed it to non-memoized. Fix coming up in seconds.

**Comment by aocenas** [comment]
As @kaydelaney already mentioned if I enter something totally invalid in the input there is no validation or error so not sure what it actually does. Also there is no indication what should be the value (ie it should be number with time unit string) so this could be confusing. Maybe we could at least add the small tooltip question mark to the label where we would explain the format? I think something like that is already present in dashboard panels settings.

**Comment by Estrax** [comment]
@aocenas added a tooltip on label saying that input needs to be a valid time unit string.

**Review by aocenas — APPROVED** [review]
