### PR TITLE
Variables: Fixes upgrade of legacy Prometheus queries

### LINKED ISSUE #29703: Variables: Query input is empty when you edit a QueryVariable

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
When initializing variables we tried to upgrade legacy queries for Prometheus because Prometheus is now using the Standard Variable Support. 

When I tried to fix this in #29375 I missed the case when a query variable depended on a datasource variable so #29375 upgrades legacy queries to early in the initialization process of variables.

This PR moves the upgrade legacy query action to places later on in the initialization process of variables. I also refactored the actions for datasource variables as they were using the now deprecated function __`getMetricSources`__. 

Enjoy your review

**Which issue(s) this PR fixes**:
Fixes #29703

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/variables/datasource/actions.ts [hunk 1]
```diff
@@ -27,16 +30,21 @@ export const updateDataSourceVariableOptions = (
...
-): ThunkResult<void> => async dispatch => {
-  const dataSources: DataSourceSelectItem[] = await dependencies.getDatasourceSrv().getMetricSources();
-  const filtered = dataSources.filter(ds => !ds.meta.mixed && ds.value !== null);
-  const dataSourceTypes = _(filtered)
+): ThunkResult<void> => dispatch => {
+  const dataSources: DataSourceSelectItem[] = dependencies
+    .getDatasourceSrv()
+    .getList({ metrics: true, variables: true })
+    .filter(setting => {
+      return !setting.meta.mixed && !setting.isDefault;
```
Comment (torkelo) [inline public/app/features/variables/datasource/actions.ts:44]: no need for this, mixed is opt-in, and isDefault is just a property on the option, so should filter out the default data source, as then you only have one data source and that is the default then this dropdown will be empty. (the old getMetricSources returned two entries, one named default with value null, getList does not do this, just returns the data sources, and if it happens to be the default isDefault is true)

**Review by torkelo — APPROVED** [review]
Looks good, just one minor thing with the use of getList

File: public/app/features/variables/datasource/actions.ts (hunk 1 above)
Comment (hugohaggmark) [reply public/app/features/variables/datasource/actions.ts]: Great explanation, I'll remove the filter and update the tests.
