### PR TITLE
fix concurrent map writes

### LINKED ISSUE #13674: service panic because of race conditions
Grafana v5.3.0 (commit: c613a31)
Datasource: Cloudwatch 
OS : linux 

I have upgraded my server to the latest version. The service now panics with a random frequency. I cannot find a pattern yet. In the logs I get the following stack trace: 
```
fatal error: concurrent map writes
goroutine 12697 [running]:
runtime.throw(0x1523ebe, 0x15)
/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0009c7ea0 sp=0xc0009c7e70 pc=0x4353a2
runtime.mapassign_faststr(0x12ec080, 0xc00134c7b0, 0xc00121f0c0, 0x19, 0x0)
/usr/local/go/src/runtime/map_faststr.go:275 +0x3bf fp=0xc0009c7f08 sp=0xc0009c7ea0 pc=0x41b93f
github.com/grafana/grafana/pkg/tsdb/cloudwatch.(*CloudWatchExecutor).executeTimeSeriesQuery.func1(0x8, 0x1590fa0)
/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/cloudwatch.go:138 +0x1a2 fp=0xc0009c7f88 sp=0xc0009c7f08 pc=0xe8c272
github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00134c810, 0xc001356380)
/go/src/github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57 fp=0xc0009c7fd0 sp=0xc0009c7f88 pc=0xb2f347
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0009c7fd8 sp=0xc0009c7fd0 pc=0x465221
created by github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup.(*Group).Go
/go/src/github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

### PR DESCRIPTION
**Pull request by mtanda**
Fix https://github.com/grafana/grafana/issues/13674

### CODE REVIEW

File: pkg/tsdb/cloudwatch/cloudwatch.go [hunk 1]
```diff
@@ -118,10 +119,10 @@ func (e *CloudWatchExecutor) executeTimeSeriesQuery(ctx context.Context, queryCo
 		}
 
 		if query.Id == "" && query.Expression != "" {
-			result.Results[query.RefId] = &tsdb.QueryResult{
+			results.Results[query.RefId] = &tsdb.QueryResult{
```
Comment (marefr) [inline pkg/tsdb/cloudwatch/cloudwatch.go]: Possible to use same solution as sql datasources [here](https://github.com/grafana/grafana/blob/master/pkg/tsdb/sql_engine.go#L131-L132) and then provide needed arguments as in-parameters to go routine? 

Or is that not possible due to use off errgroup?

Comment (mtanda) [reply pkg/tsdb/cloudwatch/cloudwatch.go]: Your approach looks nice, and I want to use it.
But, I consider the code becomes little complicated, because `executeGetMetricDataQuery()` will response multiple `tsdb.QueryResult` in one go routine, and it is called for each regions.
https://github.com/grafana/grafana/blob/v5.3.1/pkg/tsdb/cloudwatch/cloudwatch.go#L147

I need to pass the value typed like `map[string]*tsdb.QueryResult` to `executeGetMetricDataQuery()`.
There are multiple values `map[string]*tsdb.QueryResult` for each regions, so I need to keep it until query finish, and copy to `result.Results`.

If coding policy allows I want to use channel for avoding concurrent map writes.

Comment (mtanda) [reply pkg/tsdb/cloudwatch/cloudwatch.go]: @marefr I success to reproduce the issue.
https://gist.github.com/mtanda/954793aa2ff66b5ffbc782059fde01ac

I add template variable for InstanceId, which include 50+ instance ids, and make EC2 CPUUtilization graph for the variable.

I test my fix doesn't cause the issue. refresh every 5sec, and wait for 10 minutes, the Grafana doesn't crash.

Comment (marefr) [reply pkg/tsdb/cloudwatch/cloudwatch.go]: Okay. I only have one instance id available so hard for me to test. But I'll approve this and merge.

**Review by marefr — APPROVED** [review]

**Comment by marefr** [comment]
Thank you for contributing to Grafana!
