### PR TITLE
Permissions: Show plugins in nav for non admin users but hide plugin configuration

### LINKED ISSUE #17906: Plugins page accessible by viewers/editors even though not included in side menu
**What happened**:
Navigated to `http://localhost:3000/plugins` and got access to the page, but the header says Page not found, 404 error and I can still browse all of the plugins: 

image

**What you expected to happen**:
To not be able to access the page since this page is not included in the side menu.

**How to reproduce it (as minimally and precisely as possible)**:
1. Login as user with viewer or editor org role
2. Navigate to `http://localhost:3000/plugins`

**Anything else we need to know?**:
Tricky part is that we per default have a home dashboard that shows the list of plugins and all authenticated users can access every plugin:
image

You can also add the plugin list panel to any dashboard.

There shouldn't be any problem with any authenticated can access a plugin except for app plugins since they usually have a config and dashboards tab. If the app haven't properly implemented decryption of sensitive settings the users will be able to see these. 

One idea would be to hide the config/dashboards tabs for viewers/editors so that viewers/editors only can browse the plugin readme tab (which all plugin types have). Additionally, making the plugins page available in side menu for authenticated users.

### PR DESCRIPTION
**Pull request by aocenas**
Closes: https://github.com/grafana/grafana/issues/17906

~~Plugins api and routes are constrained to admins. Editors though still can create a dashboard with plugins panel as that is still visible in visualisations selector but it gives permission error as the API is not accessible.~~

~~Also this changes Home dashboard so that only Admins have the Plugins panel there. Others have just the dashboards list.~~

Allow non admins to see plugins list but only with readme. Any config tabs are hidden from the plugin page. Also plugin panel does not show action buttons (like `Enable`) for non admins.

Admin view:
Screenshot 2019-07-25 at 11 41 17

Non admin view:
Screenshot 2019-07-25 at 11 40 49

### CODE REVIEW

File: pkg/api/api.go [hunk 1]
```diff
@@ -252,9 +252,9 @@ func (hs *HTTPServer) registerRoutes() {
 
 		apiRoute.Get("/datasources/id/:name", Wrap(GetDataSourceIdByName), reqSignedIn)
 
-		apiRoute.Get("/plugins", Wrap(hs.GetPluginList))
-		apiRoute.Get("/plugins/:pluginId/settings", Wrap(GetPluginSettingByID))
-		apiRoute.Get("/plugins/:pluginId/markdown/:name", Wrap(GetPluginMarkdown))
+		apiRoute.Get("/plugins", reqOrgAdmin, Wrap(hs.GetPluginList))
+		apiRoute.Get("/plugins/:pluginId/settings", reqOrgAdmin, Wrap(GetPluginSettingByID))
+		apiRoute.Get("/plugins/:pluginId/markdown/:name", reqOrgAdmin, Wrap(GetPluginMarkdown))
```
Comment (torkelo) [inline pkg/api/api.go]: If you move this into the plugins route block below they will get the same route protection.

Think the markdown is used from queries view, and panel visualization settings also has a help button that can request plugin markdown so think that should not require org admin

Comment (aocenas) [reply pkg/api/api.go]: Good point fixed

File: public/app/routes/routes.ts [hunk 2]
```diff
@@ -314,16 +314,19 @@ export function setupAngularRoutes($routeProvider: route.IRouteProvider, $locati
...
     })
     .when('/plugins/:pluginId/', {
       template: '<react-container />',
       reloadOnSearch: false, // tabs from query parameters
       resolve: {
+        roles: () => ['Admin'],
         component: () => PluginPage,
       },
     })
+    // TODO: should also be accessible only by admins but not sure how to do ACL with angular routes.
```
Comment (aocenas) [inline public/app/routes/routes.ts]: @torkelo do you have any pointers for this one?

Comment (torkelo) [reply public/app/routes/routes.ts]: If you check explore route, it should have that

**Review by xlson — COMMENTED** [review]
Looks good, I think it makes sense to solve the whole problem right now considering you've already done 99% of it. The question is what we should do with the Plugin list panel. Having that available as a visualization (to editors) but showing permissions denied does not feel great.

I wonder if we could make it available only to admins without making the code to weird. What do you think @torkelo?

**Comment by torkelo** [comment]
Not sure we want to spend too much time on that. Short term I think we can get rid of the plugin panel, not sure it adds that much value above the plugin list view (which we can improve)

**Comment by torkelo** [comment]
Sorry, accidentally hit close instead of comment :)

**Comment by aocenas** [comment]
> Having that available as a visualization (to editors) but showing permissions denied does not feel great.
@xlson I agree with that but not sure if there is easy way to solve this. It would make sense to me to have some kind of `required_roles` in the `plugin.json` config but that seems like a bigger feature so not sure if makes sense adding something like that here.

**Comment by aocenas** [comment]
I mean we could still hardcode some filter in the panels list I guess and hopefully decide later what to do with it.

**Comment by torkelo** [comment]
So i would like to remove the plugin list panel and replace it with "Useful links" to docs, getting started etc. 

and maybe other improvements to default home dashboard. 

So not sure what to short term with this PR. 

We can easily hide the plugin list panel from viz selection by adding this to plugin.json

  "hideFromList": true,

Used by the getting started panel. Let's go with that for now.

**Comment by marefr** [comment]
Talked to Daniel about this earlier and sounded like it's a good thing that viewers and editors can browse plugins and read the plugin readme. 

Given the stable release is getting really close I would consider thinking about the short term of this PR as Torkel mentions and maybe focusing on closing down the config tab of app plugins for non-admins as a first step?

**Comment by aocenas** [comment]
@marefr Ok seems like I went in an opposite direction. My thinking was that probably nothing that is in `Configuration` section should be visible to users that cannot change it and that all the relevant info is still available in the Visualisation selection tab when creating a panel (even the readme though that is a bit hidden behind a `?` button).

So right now not sure if @torkelo is more aligned with the changes I did here or just rolled with it as it was already done.

If the sentiment is more behind letting users see installed plugins and just not allow them to go to configuration then I am not strongly against or anything and I do not think it will take that much time to change that (though not exactly sure when we want to do the beta2).

Just so we are sync on the @marefr 's proposal:
- show configuration > plugins for both Editor and Viewer users
- Disallow any plugin configuration section for Editor and Viewer users
- Keep the plugins panel as is (though one caveat here is that the panel contains some buttons like enable/update etc these will need to be hidden for Editor and Viewer users I would say).

So the decision options right now:
1. Go with @marefr proposal and implement it for beta2
2. Implement the one change @torkelo mentioned in a comment and merge this for the beta2 (possibly implementing 1. later on for 6.4.0)

**Comment by torkelo** [comment]
This is a bit more problematic, plugins/:pluginId/settings cannot be access restricted as it's used by the app plugin pages (that are potentially accessible to anyone).

See https://github.com/grafana/grafana/blob/master/public/app/features/plugins/PluginPage.tsx#L45

**Comment by torkelo** [comment]
If we can restrict / hide the settings tab somehow, that is probably better option.

**Comment by aocenas** [comment]
@torkelo You are right :(. In that case though this is mostly cosmetics as we cannot __not__ leak the settings data, but at least looking at the code we do not send secureJsonData so only issue could be if somebody set something sensitive in jsonData.

Ok so going to try to quickly implement the proposal 1. tomorrow.

File: pkg/api/index.go [hunk 3]
```diff
@@ -307,6 +307,25 @@ func (hs *HTTPServer) setIndexViewData(c *m.ReqContext) (*dtos.IndexViewData, er
 			}
 		}
 
+		data.NavTree = append(data.NavTree, cfgNode)
+	} else {
```
Comment (aocenas) [inline pkg/api/index.go]: Adds plugins nav for non admins.

File: public/app/features/plugins/PluginPage.tsx [hunk 4]
```diff
@@ -393,6 +316,106 @@ class PluginPage extends PureComponent<Props, State> {
   }
 }
 
+function getPluginTabsNav(
```
Comment (aocenas) [inline public/app/features/plugins/PluginPage.tsx]: This was just move out of the constructor.

File: public/app/features/plugins/PluginPage.tsx [hunk 5]
```diff
@@ -393,6 +316,106 @@ class PluginPage extends PureComponent<Props, State> {
...
+      text: 'Readme',
+      icon: 'fa fa-fw fa-file-text-o',
+      url: `${appSubUrl}${path}?page=${PAGE_ID_README}`,
+      id: PAGE_ID_README,
+    });
+  }
+
+  // We allow non admins to see plugins but only their readme. Config is hidden even though the API needs to be
+  // public for plugins to work properly.
+  if (isAdmin) {
```
Comment (aocenas) [inline public/app/features/plugins/PluginPage.tsx]: Only change here, adds more tabs to navigation only for admins.

File: public/app/plugins/panel/pluginlist/module.html [hunk 6]
```diff
@@ -10,14 +10,16 @@ <h6 class="pluginlist-section-header">
...
         </span>
-        <span class="pluginlist-message pluginlist-message--update" ng-show="plugin.hasUpdate" ng-click="ctrl.updateAvailable(plugin, $event)" bs-tooltip="'New version: ' + plugin.latestVersion">
-          Update available!
-        </span>
-        <span class="pluginlist-message pluginlist-message--enable" ng-show="!plugin.enabled && !plugin.hasUpdate">
-          Enable now
-        </span>
-        <span class="pluginlist-message pluginlist-message--no-update" ng-show="plugin.enabled && !plugin.hasUpdate">
-          Up to date
+        <span ng-if="ctrl.isAdmin">
```
Comment (aocenas) [inline public/app/plugins/panel/pluginlist/module.html]: Do not show those action for non admins. Even though they all takes you to plugins page which for non admins shows only readme it looks weird if you have `Enable` button here.

File: public/dashboards/home.json [hunk 7]
```diff
@@ -77,29 +77,8 @@
   },
   "timepicker": {
     "hidden": true,
-    "refresh_intervals": [
```
Comment (aocenas) [inline public/dashboards/home.json]: Changed by prettier.

File: public/app/features/plugins/PluginPage.tsx [hunk 8]
```diff
@@ -379,7 +302,7 @@ class PluginPage extends PureComponent<Props, State> {
                 {plugin && (
                   <section className="page-sidebar-section">
                     {this.renderVersionInfo(plugin.meta)}
-                    {this.renderSidebarIncludes(plugin.meta.includes)}
+                    {isAdmin && this.renderSidebarIncludes(plugin.meta.includes)}
```
Comment (aocenas) [inline public/app/features/plugins/PluginPage.tsx]: This now does not show includes for non admins. Pages API routes need to work but some of the pages are configuration ones. In here they would all be shown. Non admin user can access available pages through App navigation (which will only show non config pages to him) so this seems sensible to me.

**Comment by aocenas** [comment]
@torkelo @marefr or @xlson can you review the new changes?

**Comment by xlson** [comment]
@aocenas I won't be able to review until tomorrow morning, unfortunately.

**Review by torkelo — APPROVED** [review]
Looks good!
