### PR TITLE
Auth: Do not search for the user twice

### LINKED ISSUE #18329: API access via Basic Auth forbidden before /login request
**What happened**:

Tried using the API via HTTP Basic auth. Which failed even though the credentials were valid.

````bash
$ curl -vk -u "$USERNAME:$PASSWORD" https://grafana/api/datasources
* Server auth using Basic with user 'toomasp'
> GET /api/datasources HTTP/1.1
> Host: grafana
> Authorization: Basic REDACTED
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Cache-Control: no-cache
< Content-Type: application/json; charset=UTF-8
< Expires: -1
< Pragma: no-cache
< X-Frame-Options: deny
< Date: Thu, 01 Aug 2019 06:41:15 GMT
< Content-Length: 31

$ curl -vk -H 'Content-Type: application/json' -X POST -d '{"email": "","password": "REDACTED","user":"toomasp"}' https://grafana/login
> POST /login HTTP/1.1
> Host: grafana
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 66
> 
* upload completely sent off: 66 out of 66 bytes
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Content-Type: application/json
< Expires: -1
< Pragma: no-cache
< Set-Cookie: grafana_session=5df9e5908fc5a46dad1f263f34b7b28e; Path=/; Max-Age=2595600; HttpOnly; SameSite=Lax
< X-Frame-Options: deny
< Date: Thu, 01 Aug 2019 06:45:44 GMT
< Content-Length: 23
< 
{"message":"Logged in"}

$ curl -vk -u "$USERNAME:$PASSWORD" https://grafana/api/datasources
> GET /api/datasources HTTP/1.1
> Host: grafana
> Authorization: Basic REDACTED
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Content-Type: application/json
< Expires: -1
< Pragma: no-cache
< X-Frame-Options: deny
< Date: Thu, 01 Aug 2019 06:52:06 GMT
< Transfer-Encoding: chunked
````

**What you expected to happen**:

I expected the first request to succeed. Instead, I get an authentication failure. Which disappears once I've gone through the /login POST request. Afterwards, basic auth works as expected.

**How to reproduce it (as minimally and precisely as possible)**:

Authenticaton backend is LDAP. Use an existing LDAP user that has *NOT* logged into Grafana.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 6.2.1
- Data source type & version: InfluxDB
- OS Grafana is installed on: CentOS Linux release 7.6.1810 (Core)

### PR DESCRIPTION
**Pull request by markelog**
Previously `initContextWithBasicAuth` did not use `LoginUserQuery`, doing
`GetUserByLoginQuery` only i.e. looking user in DB only, things changed when
this function started to check LDAP provider via `LoginUserQuery` (#6940),
however, this request was placed after `GetUserByLoginQuery`, so we first
looking in DB then in the LDAP - if LDAP user hasn't logged in we will
not find it in DB, so `LoginUserQuery` will never be reached.

`LoginUserQuery` request already performs `GetUserByLoginQuery`
request in correct sequence. So we can just remove redundant request.

* Correct sequence execution during authentification &
  introduce tests for it

* Move basic auth tests to separate test file, since main test file already
  pretty large

* Introduce `testing.go` for the middleware module

* Remove redundant test helper function

* Make handler names more explicit

Ref 5777f65d05a8dc141c34e470ef1d5fe956f8173c
Fixes #18329

### CODE REVIEW

File: pkg/middleware/middleware.go [hunk 1]
```diff
@@ -163,24 +163,11 @@ func initContextWithBasicAuth(ctx *models.ReqContext, orgId int64) bool {
...
-			"username", username,
-		)
-		ctx.JsonApiErr(401, errStringInvalidUsernamePassword, err)
-
-		return true
-	}
-
-	user := loginQuery.Result
-	loginUserQuery := models.LoginUserQuery{
+	AuthQuery := models.LoginUserQuery{
```
Comment (torkelo) [inline pkg/middleware/middleware.go]: A minor naming mistake here :) lowercase the A in the variable name

Comment (markelog) [reply pkg/middleware/middleware.go]: Haha, fixed!

**Review by torkelo — APPROVED** [review]
Looks good!
