### PR TITLE
Cascader: Add enable custom value

### LINKED ISSUE #21798: Cascader: Select search unwanted blurring
**What happened**:
After writing two letters in the cascader search it loses focus.

**What you expected to happen**:
I want to be able to keep writing

**How to reproduce it (as minimally and precisely as possible)**:
Go to Storybook and try it

**Anything else we need to know?**:
This is probably related to react-select version bump https://github.com/grafana/grafana/commit/1ad569c470d1f3a92e2ed5267b09928aea28836f

### PR DESCRIPTION
**Pull request by tskarhed**
Enables the possibility to choose custom values. Also fixes #21798

### CODE REVIEW

File: packages/grafana-ui/src/components/Cascader/Cascader.tsx [hunk 1]
```diff
@@ -62,6 +63,7 @@ export class Cascader extends React.PureComponent<CascaderProps, CascaderState>
       cpy.push(option);
       if (!option.items) {
         selectOptions.push({
+          singleLabel: cpy[cpy.length - 1].label,
```
Comment (dprokop) [inline packages/grafana-ui/src/components/Cascader/Cascader.tsx]: What is the singleLabel?

File: packages/grafana-ui/src/components/Cascader/Cascader.tsx [hunk 2]
```diff
@@ -82,31 +84,45 @@ export class Cascader extends React.PureComponent<CascaderProps, CascaderState>
...
     }
+    if (this.props.allowCustomValue) {
+      return { rcValue: [], activeLabel: initValue };
+    }
     return { rcValue: [], activeLabel: '' };
   }
 
   //For rc-cascader
   onChange = (value: string[], selectedOptions: CascaderOption[]) => {
     this.setState({
```
Comment (dprokop) [inline packages/grafana-ui/src/components/Cascader/Cascader.tsx]: Hmm, I wonder if we need to have the internal state. Can't we derive that from the Cascader's value (maybe prop)? This is a separate PR material

**Review by dprokop — COMMENTED** [review]
I think the code looks ok. Let me test that in storybook before approving

File: packages/grafana-ui/src/components/Cascader/Cascader.tsx (hunk 2 above)
Comment (tskarhed) [reply packages/grafana-ui/src/components/Cascader/Cascader.tsx]: It was needed when both the cascader and the select was controlled, by since I let go of the control of the select in this PR, it should be doable.

File: packages/grafana-ui/src/components/Cascader/Cascader.tsx (hunk 1 above)
Comment (tskarhed) [reply packages/grafana-ui/src/components/Cascader/Cascader.tsx]: It is the label for only the value rather than the path. Should probably be renamed to path and label instead.

Comment (tskarhed) [reply packages/grafana-ui/src/components/Cascader/Cascader.tsx]: Oh, never mind. `label` is required by react-select when searching.

File: packages/grafana-ui/src/components/Cascader/Cascader.tsx [hunk 3]
```diff
@@ -82,31 +84,45 @@ export class Cascader extends React.PureComponent<CascaderProps, CascaderState>
...
-      activeLabel: selectedOptions.map(o => o.label).join(this.props.separator || ' / '),
+      activeLabel: selectedOptions[selectedOptions.length - 1].label,
     });
 
     this.props.onSelect(selectedOptions[selectedOptions.length - 1].value);
   };
 
   //For select
   onSelect = (obj: SelectableValue<string[]>) => {
+    if (obj.__isNew__ && this.props.allowCustomValue) {
```
Comment (dprokop) [inline packages/grafana-ui/src/components/Cascader/Cascader.tsx]: Please update to approach from https://github.com/grafana/grafana/pull/21869

**Review by dprokop — APPROVED** [review]
