### PR TITLE
BarChart: Fix stale values and x axis labels

### LINKED ISSUE #38410: Bar graph does not display correct numerical value
**What happened**:
I am using a bar graph to display Loki metrics (unwrapped values). The dashboard defaults to a 30 minute range, which works normally:

However, when I change the range to 1h, the displayed number is not correct. However it is correct when you hover over the bar:

You can see that none of the displayed values are correct (they don't line up with the axis on the bottom).

If I go into the Edit view for the panel, the numbers are correct again, and then if I leave the Edit view, the numbers stay at the correct value.

**What you expected to happen**:
The numbers displayed next to the bars should be correct

**How to reproduce it (as minimally and precisely as possible)**:
Here is my Loki query:
```
topk(20,sum by (SrcAddr) (sum_over_time({job="netflow",SamplerAddress=~`${sampler:regex}`} | json | SrcAddr=~".*${src_addr}.*" DstAddr=~".*${dst_addr}.*" | unwrap Bytes[$__range])))
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana Cloud, currently at 8.1.2
- Data source type & version: Loki, Grafana Cloud
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: N/A
- Others:

### LINKED ISSUE #38905: Barchart: X axis does not update when data changes
To replicate

* Add 2 queries random walk 
* Add a reduce transform 
* Select bar chart 
* Change alias of one of the queries 
* See no change in x-axis (it should change to reflect the new category value) 

Or replicate here: https://play.grafana.org/d/JUpQTq7nk/1-new-features-in-v8-1?orgId=1 

Change any of the month names in the query CSV content, no change in graph until you also change the field name.

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/grafana/issues/38410
Fixes https://github.com/grafana/grafana/issues/38905

### CODE REVIEW

File: public/app/plugins/panel/barchart/BarChart.tsx [hunk 1]
```diff
@@ -27,6 +27,9 @@ export const BarChart: React.FC<BarChartProps> = (props) => {
   const theme = useTheme2();
   const { eventBus } = usePanelContext();
 
+  const propsRef = useRef(props);
+  propsRef.current = props;
+
```
Comment (leeoniya) [inline public/app/plugins/panel/barchart/BarChart.tsx:32]: surely, this is a dirty, dirty hack.

File: public/app/plugins/panel/barchart/BarChart.tsx [hunk 2]
```diff
@@ -27,6 +27,9 @@ export const BarChart: React.FC<BarChartProps> = (props) => {
   const theme = useTheme2();
   const { eventBus } = usePanelContext();
 
+  const frame0Ref = useRef<DataFrame>();
+  frame0Ref.current = props.frames[0];
```
Comment (leeoniya) [inline public/app/plugins/panel/barchart/BarChart.tsx:31]: surely, this is a hack?. :shrug: 

we need the `rawValue` callback below to always have a fresh `frames[0]` reference.

**Review by ryantxu — APPROVED** [review]

File: public/app/plugins/panel/barchart/BarChart.tsx [hunk 3]
```diff
@@ -27,6 +27,9 @@ export const BarChart: React.FC<BarChartProps> = (props) => {
   const theme = useTheme2();
   const { eventBus } = usePanelContext();
 
+  const frame0Ref = useRef<DataFrame>();
```
Comment (torkelo) [inline public/app/plugins/panel/barchart/BarChart.tsx:30]: useCallback with a dependency arg is the canonically way

Comment (leeoniya) [reply public/app/plugins/panel/barchart/BarChart.tsx:30]: this doesnt work for value updates:

```js
  const { frames } = props;
  const rawValue = useCallback(
    (seriesIdx: number, valueIdx: number) => frames[0].fields[seriesIdx].values.get(valueIdx),
    [frames]
  );
```

probably since the callback passed during config building is stale, and we don't reconfig on every data update.

were you thinking something different?

Comment (torkelo) [reply public/app/plugins/panel/barchart/BarChart.tsx:30]: ah, I see, then useRef is correct I guess.

Comment (leeoniya) [reply public/app/plugins/panel/barchart/BarChart.tsx:30]: ty

**Comment by laurielounge** [comment]
Bug still exists after update to 8.1.4 Community.
