### PR TITLE
FieldOverrides: Fix array merge order so overrides take precedence over defaults

### LINKED ISSUE #116980: State Timeline: Bug with Override Value Mappings
### What happened?

When creating a state timeline, the user may want to use an override to create a different set of value mappings on a specific query. In this case, the value and color mapping does not apply.

Value mappings from the main options do apply.

### What did you expect to happen?

For value mappings done in overrides to work as configured.

### Did this work before?

Yes, according to the customer who originally logged the escalation.

### How do we reproduce it?

1. Create a state timeline panel with two queries
2. Create value mappings for both queries from the options
3. Create an override that applies to only one of the queries, and create different value mappings
4. Note that the value mappings created in 3 do not apply.

### Is the bug inside a dashboard panel?

| Key | Value |
|--|--|
| Panel | state-timeline @ 12.4.0-pre |
| Grafana | Grafana v12.4.0-pre (fda39b0c26) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "id": 2,
      "type": "state-timeline",
      "title": "Reproduced with embedded data",
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "lineWidth": 0,
            "fillOpacity": 70,
            "spanNulls": false,
            "insertNulls": false,
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            },
            "axisPlacement": "auto"
          },
          "color": {
            "mode": "shades"
          },
          "mappings": [
            {
              "type": "value",
              "options": {
                "0": {
                  "color": "red",
                  "index": 1,
                  "text": "DOWN"
                },
                "1": {
                  "color": "green",
                  "index": 0,
                  "text": "UP"
                }
              }
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byFrameRefID",
              "options": "B"
            },
            "properties": [
              {
                "id": "mappings",
                "value": [
                  {
                    "options": {
                      "0": {
                        "color": "orange",
                        "index": 1,
                        "text": "DOWN"
                      },
                      "1": {
                        "color": "green",
                        "index": 0,
                        "text": "UP"
                      }
                    },
                    "type": "value"
                  }
                ]
              }
            ]
          }
        ]
      },
      "transformations": [
        {
          "id": "convertFieldType",
          "options": {
            "conversions": [
              {
                "destinationType": "time",
                "targetField": "time"
              }
            ],
            "fields": {}
          }
        },
        {
          "id": "rowsToFields",
          "options": {
            "mappings": []
          }
        }
      ],
      "pluginVersion": "12.4.0-pre",
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "fields": [
                  {
                    "name": "time",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "A",
                    "type": "number",
                    "typeInfo": {
                      "frame": "int64",
                      "nullable": true
                    },
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    "27/01/2026 13:27:09",
                    "27/01/2026 13:32:09",
                    "27/01/2026 13:37:09",
                    "27/01/2026 13:42:09",
                    "27/01/2026 13:47:09",
                    "27/01/2026 13:52:09",
                    "27/01/2026 13:57:09",
                    "27/01/2026 14:02:09",
                    "27/01/2026 14:07:09"
                  ],
                  [
                    1,
                    1,
                    1,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1
                  ]
                ]
              }
            },
            {
              "schema": {
                "refId": "B",
                "fields": [
                  {
                    "name": "time",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "B",
                    "type": "number",
                    "typeInfo": {
                      "frame": "int64",
                      "nullable": true
                    },
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    "27/01/2026 13:27:09",
                    "27/01/2026 13:32:09",
                    "27/01/2026 13:37:09",
                    "27/01/2026 13:42:09",
                    "27/01/2026 13:47:09",
                    "27/01/2026 13:52:09",
                    "27/01/2026 13:57:09",
                    "27/01/2026 14:02:09",
                    "27/01/2026 14:07:09"
                  ],
                  [
                    1,
                    1,
                    1,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1
                  ]
                ]
              }
            }
          ]
        }
      ],
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "options": {
        "mergeValues": true,
        "showValue": "auto",
        "alignValue": "left",
        "rowHeight": 0.9,
        "legend": {
          "showLegend": true,
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltip": {
          "mode": "single",
          "sort": "none",
          "hideZeros": false
        }
      }
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >state-timeline @ 12.4.0-pre</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[grafana-testdata-datasource], B[grafana-testdata-datasource]</td>\n    </tr>\n    <tr>\n      <th>Transform</th>\n      <td>convertFieldType, rowsToFields</td>\n  </tr>\n    <tr><th>Data</th><td> 2 frames, 4 fields, 18 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>Grafana v12.4.0-pre (fda39b0c26) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"id\": 1,\n  \"type\": \"state-timeline\",\n  \"title\": \"New panel\",\n  \"gridPos\": {\n    \"x\": 0,\n    \"y\": 0,\n    \"h\": 8,\n    \"w\": 12\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"lineWidth\": 0,\n        \"fillOpacity\": 70,\n        \"spanNulls\": false,\n        \"insertNulls\": false,\n        \"hideFrom\": {\n          \"tooltip\": false,\n          \"viz\": false,\n          \"legend\": false\n        },\n        \"axisPlacement\": \"auto\"\n      },\n      \"color\": {\n        \"mode\": \"shades\"\n      },\n      \"mappings\": [\n        {\n          \"type\": \"value\",\n          \"options\": {\n            \"0\": {\n              \"color\": \"red\",\n              \"index\": 1,\n              \"text\": \"DOWN\"\n            },\n            \"1\": {\n              \"color\": \"green\",\n              \"index\": 0,\n              \"text\": \"UP\"\n            }\n          }\n        }\n      ],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"color\": \"green\",\n            \"value\": null\n          }\n        ]\n      }\n    },\n    \"overrides\": [\n      {\n        \"matcher\": {\n          \"id\": \"byFrameRefID\",\n          \"options\": \"B\"\n        },\n        \"properties\": [\n          {\n            \"id\": \"mappings\",\n            \"value\": [\n              {\n                \"options\": {\n                  \"0\": {\n                    \"color\": \"orange\",\n                    \"index\": 1,\n                    \"text\": \"DOWN\"\n                  },\n                  \"1\": {\n                    \"color\": \"green\",\n                    \"index\": 0,\n                    \"text\": \"UP\"\n                  }\n                },\n                \"type\": \"value\"\n              }\n            ]\n          }\n        ]\n      }\n    ]\n  },\n  \"transformations\": [\n    {\n      \"id\": \"convertFieldType\",\n      \"options\": {\n        \"conversions\": [\n          {\n            \"destinationType\": \"time\",\n            \"targetField\": \"time\"\n          }\n        ],\n        \"fields\": {}\n      }\n    },\n    {\n      \"id\": \"rowsToFields\",\n      \"options\": {\n        \"mappings\": []\n      }\n    }\n  ],\n  \"pluginVersion\": \"12.4.0-pre\",\n  \"targets\": [\n    {\n      \"scenarioId\": \"csv_content\",\n      \"refId\": \"A\",\n      \"csvContent\": \"\\\"time\\\",\\\"A\\\"\\n27/01/2026 13:27:09,1\\n27/01/2026 13:32:09,1\\n27/01/2026 13:37:09,1\\n27/01/2026 13:42:09,0\\n27/01/2026 13:47:09,1\\n27/01/2026 13:52:09,1\\n27/01/2026 13:57:09,1\\n27/01/2026 14:02:09,1\\n27/01/2026 14:07:09,1\"\n    },\n    {\n      \"scenarioId\": \"csv_content\",\n      \"refId\": \"B\",\n      \"csvContent\": \"\\\"time\\\",\\\"B\\\"\\n27/01/2026 13:27:09,1\\n27/01/2026 13:32:09,1\\n27/01/2026 13:37:09,1\\n27/01/2026 13:42:09,0\\n27/01/2026 13:47:09,1\\n27/01/2026 13:52:09,0\\n27/01/2026 13:57:09,0\\n27/01/2026 14:02:09,0\\n27/01/2026 14:07:09,1\",\n      \"datasource\": {\n        \"type\": \"grafana-testdata-datasource\",\n        \"uid\": \"PD8C576611E62080A\"\n      }\n    }\n  ],\n  \"datasource\": {\n    \"type\": \"grafana-testdata-datasource\",\n    \"uid\": \"PD8C576611E62080A\"\n  },\n  \"options\": {\n    \"mergeValues\": true,\n    \"showValue\": \"auto\",\n    \"alignValue\": \"left\",\n    \"rowHeight\": 0.9,\n    \"legend\": {\n      \"showLegend\": true,\n      \"displayMode\": \"list\",\n      \"placement\": \"bottom\"\n    },\n    \"tooltip\": {\n      \"mode\": \"single\",\n      \"sort\": \"none\",\n      \"hideZeros\": false\n    }\n  }\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above (after transformations)",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    },
    {
      "id": 100,
      "title": "Data (before transformations)",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 24,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": false,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: New panel // 27/01/2026 20:46:21",
  "tags": [
    "debug",
    "debug-state-timeline"
  ],
  "time": {
    "from": "2026-01-27T19:27:09.649Z",
    "to": "2026-01-27T20:12:52.893Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana: `main`

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by kristinademeshchik**
**What is this feature?**

Fixes the array merge order in setDynamicConfigValue from `[...existingValue, ...val]` to `[...val, ...existingValue]`

**Why do we need this feature?**

Value mappings in overrides were being ignored because defaults came first in the merged array. Since `getValueMappingResult` returns on first match, defaults always won. 

**Which issue(s) does this PR fix?**:

Fixes #116980

### CODE REVIEW

File: packages/grafana-data/src/field/fieldOverrides.ts [hunk 1]
```diff
@@ -353,11 +353,12 @@ export function setDynamicConfigValue(config: FieldConfig, value: DynamicConfigV
     }
   } else {
     // Merge arrays (e.g. mappings) when multiple overrides target the same field
+    // Override values come first so they take precedence (first match wins in getValueMappingResult)
     if (Array.isArray(val)) {
       const existingValue = item.isCustom ? get(config.custom, item.path) : get(config, item.path);
 
       if (Array.isArray(existingValue)) {
-        val = [...existingValue, ...val];
+        val = [...val, ...existingValue];
```
Comment (kristinademeshchik) [inline packages/grafana-data/src/field/fieldOverrides.ts:361]: value mappings work by finding the first match and returning immediately. With the old merge order, defaults came first, so they would match before overrides were ever processed

https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/utils/valueMappings.ts#L22-L26

**Review by gelicia — APPROVED** [review]
perfect!

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/21449530687)
- Version: 12.4.0-21449530687
