### PR TITLE
API: Fix status code when starring already starred dashboard

### LINKED ISSUE #63133: API: Starring already starred dashboard returns 500 internal server error
Using the API to star a dashboard that's already starred returns a 500 internal server, with a SQL-ish looking error in the body:

```json
{
  "error": "UNIQUE constraint failed: star.user_id, star.dashboard_id",
  "message": "Failed to star dashboard",
  "traceID": ""
}
```

While there's not strictly a bug here, it doesn't seem great that the SQL error is bubbled up. If we intend starring an already starred dashboard to be an error, then I think it should return a more appropriate error.

I think it would also be fine to just return 200-OK if the dashboard is already starred. The request might not have altered any state, but the desired effect (the dashboard is starred) is still true. But i don't feel _super_ strongly about this.

### PR DESCRIPTION
**Pull request by MTLChrisLEE**
**What is this feature?**

Returns 200 instead of an internal server error.

**Why do we need this feature?**

The status code and the error message are misleading.

**Who is this feature for?**

For users who call POST /api/user/stars/dashboard/{:id} or /api/user/stars/dashboard/uid/{:dashboardUID} without Grafana UI

Fixes #63133

**Special notes for your reviewer**:
This is my first PR for Grafana.
I tried to find and add tests for this api. I failed to find the relevant tests.
Thanks!

### CODE REVIEW

File: pkg/services/star/model.go [hunk 1]
```diff
@@ -2,7 +2,10 @@ package star
 
 import "errors"
 
-var ErrCommandValidationFailed = errors.New("command missing required fields")
+var (
+	ErrCommandValidationFailed = errors.New("command missing required fields")
+	ErrDashboardAlreadyStarred = errors.New("dashboard was already starred")
```
Comment (papagian) [inline pkg/services/star/model.go:7]: nit
I would suggest declaring this as `github.com/grafana/grafana/pkg/util/errutil.Error` as suggested [here](https://github.com/grafana/grafana/blob/main/contribute/backend/errors.md#declaring-errors)

**Review by papagian — CHANGES_REQUESTED** [review]
Thank you for your contribution!

I still get 500 status code (with a better error message):

```
curl -XPOST -v http://admin:admin@localhost:3000/api/user/stars/dashboard/30
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
* Server auth using Basic with user 'admin'
> POST /api/user/stars/dashboard/30 HTTP/1.1
> Host: localhost:3000
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.87.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Cache-Control: no-store
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Xss-Protection: 1; mode=block
< Date: Wed, 05 Apr 2023 11:38:16 GMT
< Content-Length: 91
< 
* Connection #0 to host localhost left intact
{"error":"dashboard was already starred","message":"Failed to star dashboard","traceID":""
```

I think you still have to handle `star.ErrDashboardAlreadyStarred` and return a different status code here:
https://github.com/grafana/grafana/blob/c9288868f44cf520ef144967ca3674225a8f6a3f/pkg/services/star/api/api.go#L135
and here:
https://github.com/grafana/grafana/blob/c9288868f44cf520ef144967ca3674225a8f6a3f/pkg/services/star/api/api.go#L103


Also, I think that is better instead of `http.StatusOK` response in case of a already starred dashboard to return `http.StatusNotModified`

**Comment by MTLChrisLEE** [comment]
Hi @papagian ,

Thank you for the review.

Actually, I was not sure about which status should be returned. 
When I was fixing the issue, I looked at other services and I found that queryHistory has quite similar request/response.

https://github.com/grafana/grafana/blob/main/pkg/services/queryhistory/api.go#L160
https://github.com/grafana/grafana/blob/main/pkg/services/queryhistory/database.go#L205
https://github.com/grafana/grafana/blob/main/pkg/services/queryhistory/models.go#L12

I think it's better to keep the consistency. But, it's really up to you. I don't mind changing it to other status.

What do you think?

**Comment by papagian** [comment]
> Hi @papagian ,
> 
> Thank you for the review.
> 
> Actually, I was not sure about which status should be returned. When I was fixing the issue, I looked at other services and I found that queryHistory has quite similar request/response.
> 
> https://github.com/grafana/grafana/blob/main/pkg/services/queryhistory/api.go#L160 https://github.com/grafana/grafana/blob/main/pkg/services/queryhistory/database.go#L205 https://github.com/grafana/grafana/blob/main/pkg/services/queryhistory/models.go#L12
> 
> I think it's better to keep the consistency. But, it's really up to you. I don't mind changing it to other status.
> 
> What do you think?

no strong opinions but it seems better to me, since we fix the status to return the more appropriate one rather than trying to conform to whatever the query history returns.

**Comment by MTLChrisLEE** [comment]
Hi @papagian 

Sorry for the late reply. I just updated my PR.
I agree. If the query history behavior/response is not _exemplary_, yes,we should return a different status.
However, if we are returning a http.StatusOK, then I don't think we need another message.

If the message is something like "The dashboard is **already** starred"
I think the message is bit misleading.

What do you think about returning the successful message as like it was the first time that the user was starring the dashboard

**Review by papagian — APPROVED** [review]
thank you for your contribution
