### PR TITLE
Log Context: Add Log Context support to mixed data sources

### LINKED ISSUE #57359: Logs: Log Context does not work with mixed data sources
if you use mixed data sources, the Log Context feature does not work, as the button never appears.

The problem is in this function: https://github.com/grafana/grafana/blob/main/public/app/features/explore/LogsContainer.tsx#L61-L69 It uses the incorrect (in mixed mode) datasource to make a decision.

We should fix this. The problem is: finding the datasource is an async process, But, the method `showContextToggle` is sync. 

(NOTE: technically there is one more place in that file that needs changing, around https://github.com/grafana/grafana/blob/main/public/app/features/explore/LogsContainer.tsx#L49, but that is easy to fix, because it's already `async`)

### PR DESCRIPTION
**Pull request by matyax**
This PR adds support to logs context when using mixed data sources. It has been achieved by using a previously existing data source feature check called `checkFiltersAvailability()` to now additionally maintain a set of data sources that support Logs Context, referenced by the refId. This refId can then be grabbed from the log rows to determine the correct instance to use.

When using "normal" mode, Logs Context behaves as usual, using `datasourceInstance`.

When using mixed data sources, it grabs the resolved data source instance from the aforementioned set.

**Why do we need this feature?**

Enabling a requested feature to work with mixed data sources.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/57359

**Special notes for your reviewer:**

Test logs context with mixed data sources and normal data source mode, it should work as expected.

Set

Demo:

https://github.com/grafana/grafana/assets/1069378/73741d7d-eab9-4ed4-b76c-b6614f086503

### CODE REVIEW

File: public/app/features/explore/Logs/LogsContainer.tsx [hunk 1]
```diff
@@ -59,45 +60,71 @@ interface LogsContainerProps extends PropsFromRedux {
...
+    if (!logsQueries || !datasourceInstance) {
       return;
     }
 
-    if (datasourceInstance?.modifyQuery || hasToggleableQueryFiltersSupport(datasourceInstance)) {
-      this.setState({ logDetailsFilterAvailable: true });
+    let newState: LogsContainerState = { ...this.state, logDetailsFilterAvailable: false };
+
+    // Not in mixed mode.
+    if (datasourceInstance.name !== MIXED_DATASOURCE_NAME) {
```
Comment (svennergr) [inline public/app/features/explore/Logs/LogsContainer.tsx:94]: I think we should do that with `datasourceInstance.type === 'mixed'`. However I also saw this: https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/mixed/MixedDataSource.ts#L30-L32

@ifrost any particular reason to do it based on the DS name rather than the type?

File: public/app/features/explore/Logs/LogsContainer.tsx [hunk 2]
```diff
@@ -59,45 +60,71 @@ interface LogsContainerProps extends PropsFromRedux {
...
     }
 
+    // Mixed mode.
     const promises = [];
+    const refIds: string[] = [];
     for (const query of logsQueries) {
-      if (query.datasource) {
+      if (query.datasource && !newState.logContextSupport[query.refId]) {
         promises.push(getDataSourceSrv().get(query.datasource));
+        refIds.push(query.refId);
```
Comment (svennergr) [inline public/app/features/explore/Logs/LogsContainer.tsx:113]: Hm, I don't like this being handled in two different arrays. What do you think about changing it to something like

```
promises.push(getDataSourceSrv().get(query.datasource).then(ds=>({ds, refId: query.refId}));
```

to just use the `refId` when resolving the promises?

File: public/app/features/explore/Logs/LogsContainer.tsx [hunk 3]
```diff
@@ -59,45 +60,71 @@ interface LogsContainerProps extends PropsFromRedux {
...
+        logsQueries.forEach(({ refId }) => {
+          newState.logContextSupport[refId] = datasourceInstance;
+        });
+      }
+      this.setState(newState);
       return;
     }
 
+    // Mixed mode.
     const promises = [];
```
Comment (svennergr) [inline public/app/features/explore/Logs/LogsContainer.tsx:108]: Just a nit and I know this is not from this PR, but I think having a more descriptive name about the content of the promises, e.g. `datasourcePromises`, would be better.

File: public/app/features/explore/Logs/LogsContainer.tsx [hunk 4]
```diff
@@ -59,45 +60,71 @@ interface LogsContainerProps extends PropsFromRedux {
...
-      const logDetailsFilterAvailable = dataSources.some(
+      newState.logDetailsFilterAvailable = dataSources.some(
         (ds) => ds.modifyQuery || hasToggleableQueryFiltersSupport(ds)
       );
-      this.setState({ logDetailsFilterAvailable });
+      dataSources.forEach((ds, i) => {
+        if (hasLogsContextSupport(ds)) {
+          newState.logContextSupport[refIds[i]] = ds;
+        }
+      });
```
Comment (svennergr) [inline public/app/features/explore/Logs/LogsContainer.tsx:125]: Just a nit, but in the worst case this will loop through all `dataSources` twice. You could just add this to the `forEach` loop:

```
newState.logDetailsFilterAvailable = newState.logDetailsFilterAvailable || ds.modifyQuery || hasToggleableQueryFiltersSupport(ds);
```

**Review by svennergr — COMMENTED** [review]
Nice. Left a few comments.

File: public/app/features/explore/Logs/LogsContainer.tsx (hunk 1 above)
Comment (matyax) [reply public/app/features/explore/Logs/LogsContainer.tsx]: Switched to use `uid` like https://github.com/grafana/grafana/blob/main/public/app/features/explore/state/query.ts#L388C2-L388C2.

File: public/app/features/explore/Logs/LogsContainer.tsx (hunk 3 above)
Comment (matyax) [reply public/app/features/explore/Logs/LogsContainer.tsx]: Changed to `dsPromises`.

File: public/app/features/explore/Logs/LogsContainer.tsx (hunk 2 above)
Comment (matyax) [reply public/app/features/explore/Logs/LogsContainer.tsx:113]: Sure.

File: public/app/features/explore/Logs/LogsContainer.tsx (hunk 1 above)
Comment (ifrost) [reply public/app/features/explore/Logs/LogsContainer.tsx]: I think for mixed data source `datasource.type` is `"datasource"` not `"mixed"`. I think in theory you can check `.meta.mixed` or `.meta.id` here. Checking by name is just the most commonly used across the code base. Probably the reason why the name is used so commonly it's just it was more convenient as it is working the same way regardless of using `DataSourceSettings` (pre-loaded for all data sources) or `DataSourceApi` (needs extra async call).

Comment (svennergr) [reply public/app/features/explore/Logs/LogsContainer.tsx]: Oh, right. I think switching to `uid` makes sense as it makes sure it is unique.

File: public/app/features/explore/Logs/LogsContainer.tsx (hunk 2 above)
Comment (matyax) [reply public/app/features/explore/Logs/LogsContainer.tsx]: Updated.

File: public/app/features/explore/Logs/LogsContainer.tsx (hunk 4 above)
Comment (matyax) [reply public/app/features/explore/Logs/LogsContainer.tsx]: Updated.

**Comment by matyax** [comment]
@svennergr friendly reminder.

File: public/app/features/explore/Logs/LogsContainer.tsx [hunk 5]
```diff
@@ -59,45 +60,75 @@ interface LogsContainerProps extends PropsFromRedux {
 
 interface LogsContainerState {
   logDetailsFilterAvailable: boolean;
+  /**
+   * LogContext support for mixed data sources.
+   * @alpha
```
Comment (svennergr) [inline public/app/features/explore/Logs/LogsContainer.tsx:65]: Just a nit: not sure if this is needed? The interface doesn't seem exported anyways.

File: public/app/features/explore/Logs/LogsContainer.tsx [hunk 6]
```diff
@@ -59,45 +60,75 @@ interface LogsContainerProps extends PropsFromRedux {
...
       }
     }
 
-    Promise.all(promises).then((dataSources) => {
-      const logDetailsFilterAvailable = dataSources.some(
-        (ds) => ds.modifyQuery || hasToggleableQueryFiltersSupport(ds)
-      );
-      this.setState({ logDetailsFilterAvailable });
+    if (!dsPromises.length) {
+      return;
```
Comment (svennergr) [inline public/app/features/explore/Logs/LogsContainer.tsx:120]: I am just wondering if there are ever cases where we need to "reset" the state in cases there are no `dsPromises`? Aka setting every `logContextSupport[refId]` to false here?

**Review by svennergr — APPROVED** [review]
LGTM. I added https://github.com/grafana/grafana/issues/77280 to cover those changes with e2e tests.

File: public/app/features/explore/Logs/LogsContainer.tsx (hunk 5 above)
Comment (matyax) [reply public/app/features/explore/Logs/LogsContainer.tsx]: 100%, I think I did this more as a reflex than with a particupar purpose.

File: public/app/features/explore/Logs/LogsContainer.tsx (hunk 6 above)
Comment (matyax) [reply public/app/features/explore/Logs/LogsContainer.tsx:117]: True. Added to line 126, along with checking the uid on line 106.

File: public/app/features/explore/Logs/LogsContainer.tsx [hunk 7]
```diff
@@ -59,45 +60,81 @@ interface LogsContainerProps extends PropsFromRedux {
...
-      if (query.datasource) {
-        promises.push(getDataSourceSrv().get(query.datasource));
+      const mustCheck =
+        !newState.logContextSupport[query.refId] ||
+        newState.logContextSupport[query.refId].uid !== query.datasource?.uid;
+      if (mustCheck) {
+        dsPromises.push(
+          new Promise((resolve) => {
+            getDataSourceSrv()
+              .get(query.datasource)
```
[the remark this answers is not in the document]
Comment (matyax) [reply public/app/features/explore/Logs/LogsContainer.tsx:113]: Great point @gelicia ! We use `dataSourceSrv.get()` in a few places, so definitely something to keep in mind.

[the remark this answers is not in the document]
Comment (matyax) [reply public/app/features/explore/Logs/LogsContainer.tsx:116]: Now checking if the data source is not null.
