### PR TITLE
LibraryPanels: Don't include ScopedVars with persisted model

### LINKED ISSUE #65518: [Dashboards - Library Panel] A library panel configured to repeat conflicts with dashboard template variables when they share the same name
**What happened**:
Based on escalation: https://github.com/grafana/support-escalations/issues/5382 

If we have `dashboardA` that creates a library panel configured to be repeated on a variable called "variableX", if that library panel is used on  `dashboardB`, the first time we load the library panel on `dashboardB` is always using the harcoded values from `variableX` on `dashboardA` (`scopeVars`)

**What you expected to happen**:

Either the library panel does not carry over the `scopeVars` when is being used outside of the panel that was created, or it should detect that we have a local template variable with the same name and use that variable. 

**How to reproduce it (as minimally and precisely as possible)**:
- Create a dashboard `A` together with a multi-select custom variable called `variableA`
- Create a text panel, use the variable in the content, and configure the panel to be repeated on `variableA`
- Transform the text panel into a "libraryPanel" 
- Create a dashboard `B` together with a multi-select custom variable called `variableA`
- Add the libraryPanel created into dashboard `B`

Observe the panel is displaying the values of `variableA` configured on `dashboardA`

**Context oh why this happens:**
When a panel is configured to repeat on a variable we add `scopedVars` props to the `Panel JSON`, it looks something like this:
```
....
"scopedVars": {
  "VARIABLE_NAME1": {
    "selected": true,
    "text": "Something",
    "value": "Something"
  }
},
```

If we are using this library panel on another dashboard, our `Panel JSON` from the library panel is carrying the `scopeVars`, but then, if on that dashboard we have a variable with the same name (in my example VARIABLE_NAME1) . Whenever we load the panel `scopeVar` takes precedence over the dashboard template variable.  

https://user-images.githubusercontent.com/239999/228510955-e4edab52-1857-44ac-98ff-afce3d7bd147.mp4

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.7
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by kaydelaney**
Removes ScopedVars from library panel before saving.
Unfortunately this highlights another issue in that repeats are processed before library panels are resolved, so if a library panel is repeated by a variable, that variable's value needs to be refreshed or changed for repeats to be processed.
I think it's possible this is a regression introduced during the library panel frontend move, but I'd have to investigate.

Closes #65518

Note: I've marked this as a breaking change since I guess it's possible someone somewhere depended on this behavior.

### CODE REVIEW

**Comment by ivanortegaalba** [comment]
@dprokop suggested adding a release note if we're potentially breaking the behavior of the app. Double checking if this is a real breaking change.

**Comment by polibb** [comment]
I played around with both cases: the bug and the solution. It seems to me that we'd be introducing a bug in place of another bug. Now instead of having this problem: 

https://github.com/grafana/grafana/assets/13227501/f3b3cc9f-b10b-4e6b-ba22-e448d3de2ade

We'd have this problem:

https://github.com/grafana/grafana/assets/13227501/d49b5965-d387-416b-9467-c2535279855d

I don't think it's that much better.

**Comment by kaydelaney** [comment]
@polibb How about with the last commit?

File: public/app/features/library-panels/state/api.ts [hunk 1]
```diff
@@ -64,7 +64,7 @@ export async function getLibraryPanel(uid: string, isHandled = false): Promise<L
     schemaVersion: 35, // should be saved in the library panel
     panels: [result.model],
   });
-  const model = dash.panels[0].getSaveModel(); // migrated panel
+  const { scopedVars, ...model } = dash.panels[0].getSaveModel(); // migrated panel
```
Comment (torkelo) [inline public/app/features/library-panels/state/api.ts:67]: getSaveModel should never include scopedVars, it should be safe to add scopedVars to non persisted props in PanelModel? 

It is cleaned as part of DashboardModel.getPanelSaveModels but maybe it's better to do that in PanelModel ?

**Review by polibb — APPROVED** [review]
works as expected! 😊 🙌
not going over @torkelo's comment, but approving the manual testing and additions on `loadLibraryPanelAndUpdate`
