### PR TITLE
Provisioning: Default to folder sync only and block new instance sync repositories

### LINKED ISSUE #109870: Alerts missing after upgrade from Grafana 11.2.0 → 12.1.1 when GitSync is enabled
### What happened?

Hey team,

I recently upgraded Grafana in our staging environment from 11.2.0 to 12.1.1.
All dashboards, alerts, contact points, and notification policies appeared intact immediately after the upgrade.
Once I enabled GitSync, dashboards remained present, but all alerts disappeared.
When navigating to **Alerting → Active Notifications → [selecting an alert rule],** I encountered the following error:
**/api/ruler/grafana/api/v1/rules/... 403 Access Denied**

I was logged in as an Admin during this process. FYI - we are deploying Grafana with a Bitnami Helm chart.

### What did you expect to happen?

I expected not only dashboards to be visible in the Grafana UI but also Alerts.

### Did this work before?

It is a new feature, so no.

### How do we reproduce it?

1. Bump the Grafana to the latest version
2. Enable GitSync
3. No alerts visible after

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 12.1.1
OS:
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by MissingRoberto**
## Summary

This PR addresses issue #619 by defaulting to folder-only sync and blocking creation of new instance sync repositories, while allowing existing instance sync repositories to continue functioning.

### Backend Configuration
- Changed default `allowed_targets` to `folder` only in:
  - `conf/defaults.ini`
  - `pkg/setting/setting.go`

### Backend Validation
- Modified `ValidateRepository` to only enforce `allowedTargets` on CREATE operations
- This allows existing instance sync repositories to be updated without validation errors
- Updated all callers: `register.go`, `tester.go`, and `validator_test.go`

### Frontend Changes
- Added deprecation warning banner in `RepositoryList.tsx` for repositories using instance sync
- Updated frontend defaults to match backend (folder-only)
- Updated tests to reflect new default behavior

## Testing

- ✅ New repositories can only use folder sync target
- ✅ Existing instance sync repositories continue to function (updates allowed)
- ✅ Warning appears for users with instance sync repositories
- ✅ All tests updated and passing

Fixes https://github.com/grafana/git-ui-sync-project/issues/619
Fixes https://github.com/grafana/grafana/issues/109870

image

### CODE REVIEW

File: apps/provisioning/pkg/repository/validator.go [hunk 1]
```diff
@@ -44,7 +46,7 @@ func (v *RepositoryValidator) ValidateRepository(repo Repository) field.ErrorLis
 		if cfg.Spec.Sync.Target == "" {
 			list = append(list, field.Required(field.NewPath("spec", "sync", "target"),
 				"The target type is required when sync is enabled"))
-		} else if !slices.Contains(v.allowedTargets, cfg.Spec.Sync.Target) {
+		} else if isCreate && !slices.Contains(v.allowedTargets, cfg.Spec.Sync.Target) {
 			list = append(list,
 				field.Invalid(
 					field.NewPath("spec", "target"),
```
Comment (Clarity-89) [inline apps/provisioning/pkg/repository/validator.go:52]: Should this also be `"spec", "sync", "target"`, not sure why it differs from the path above.

**Review by Clarity-89 — APPROVED** [review]

**Review by ferruvich — APPROVED** [review]

File: apps/provisioning/pkg/repository/validator.go (hunk 1 above)
Comment (MissingRoberto) [reply apps/provisioning/pkg/repository/validator.go:52]: yeah, that one is wrong in the original code. Well spotted :)
