### PR TITLE
Auth: Add setting to disable username based brute force login protection

### LINKED ISSUE #109138: Authentication: Cannot use brute force login protection by IP address for same user login attempts
### What happened?

The brute force login protection never blocks IP address when repeated failing login attempts are made from the same IP and using the same username.

### What did you expect to happen?

I expect Grafana to block login for a specific IP address when multiple failing login attempts are made for the same user from the same IP.

### Did this work before?

No

### How do we reproduce it?

1. Configure Grafana to enable IP address login protection

```yaml
disable_ip_address_login_protection: false
disable_brute_force_login_protection: false
brute_force_login_protection_max_attempts: 3
```

2. From host A run 3 times `curl 'https://admin:wrong-password@grafanahost/login'`
3. From host B run `curl http://admin:correct-password@grafanahost/api/orgs`

The last command returns the following 401 error instead of the expected 200.

```json
{"extra":null,"message":"Invalid username or password","messageId":"password-auth.failed","statusCode":401,"traceID":""}
```

Only host A ip should be blocked but here the username is blocked instead of the IP address. This can be seen from Grafana logs as

```
logger=authn.service t=2025-08-04T15:23:33.785747856Z level=info msg="Failed to authenticate request" client=auth.client.basic error="[password-auth.failed] too many consecutive incorrect login attempts for user - login for user temporarily blocked"
```

which should instead say `too many consecutive incorrect login attempts for IP address`

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v12.0.2 (5bda17e7c1)
OS: `Linux 6.6.94-1`
Browser: n/a

### Grafana platform?

Kubernetes

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by TheoBrigitte**
**What is this feature?**

This PR adds a new setting in order to be able to disable the username based brute force login protection, which allow to use IP only brute force login protection.

**Why do we need this feature?**

The issue I am facing currently is due to brute force attacks trying to login in as admin user, which then results in the admin user account being blocked for 5 min. I would rather instead only have the attacker IP address being blocked and not the admin account.

**Who is this feature for?**

For DevOps people running and configuring Grafana.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/109138

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: pkg/services/loginattempt/loginattemptimpl/login_attempt.go [hunk 1]
```diff
@@ -63,7 +63,7 @@ func (s *Service) Reset(ctx context.Context, username string) error {
 }
 
 func (s *Service) Validate(ctx context.Context, username string) (bool, error) {
-	if s.cfg.DisableBruteForceLoginProtection {
+	if s.cfg.DisableUsernameLoginProtection {
```
Comment (cinaglia) [inline pkg/services/loginattempt/loginattemptimpl/login_attempt.go]: We should continue to skip the validation if `s.cfg.DisableBruteForceLoginProtection` is true to avoid unnecessary database calls.

```suggestion
	if s.cfg.DisableBruteForceLoginProtection || s.cfg.DisableUsernameLoginProtection {
```

For completeness, we would probably want to do the same for `Service.ValidateIPAddress()`. 

We could go even a step further and update `Service.Add()` to skip adding in the scenario where `s.cfg.DisableBruteForceLoginProtection || (s.cfg.DisableBruteForceLoginProtection && s.cfg.DisableBruteForceLoginProtection)`. You're welcome to make that change if you wish, otherwise we can probably create a separate PR for it.

**Review by cinaglia — COMMENTED** [review]
Thanks for your contribution, @TheoBrigitte! I just have a minor comment to avoid unnecessary database calls. The PR should be good to go once that is addressed.

File: pkg/services/loginattempt/loginattemptimpl/login_attempt.go (hunk 1 above)
Comment (TheoBrigitte) [reply pkg/services/loginattempt/loginattemptimpl/login_attempt.go]: That's a good point. I think you meant `s.cfg.DisableBruteForceLoginProtection || (s.cfg.DisableUsernameLoginProtection && s.cfg.DisableIPAddressLoginProtection)`

I added that.

Comment (cinaglia) [reply pkg/services/loginattempt/loginattemptimpl/login_attempt.go]: Heh, good catch. I did, indeed.

**Review by cinaglia — DISMISSED** [review]

File: pkg/services/loginattempt/loginattemptimpl/login_attempt.go (hunk 1 above)
Comment (cinaglia) [reply pkg/services/loginattempt/loginattemptimpl/login_attempt.go]: @TheoBrigitte Looks great! I was wondering if you could add a couple of tests to exercise these new checks (for both Validate & ValidateIPAddress)?

I'd approved it before realizing that we needed to update the tests. I've removed my approval but will take another look soon. Thanks again for your contribution!

Comment (TheoBrigitte) [reply pkg/services/loginattempt/loginattemptimpl/login_attempt.go]: I added couple of test cases to test all the settings combinations.

**Review by cinaglia — APPROVED** [review]
