### PR TITLE
Explore: Adds reconnect for failing datasource

### LINKED ISSUE #15096: Explore: no way to retry testDatasource failure
Continuation of the problems found in #14976 

Not sure why Explore does a testDatasource call and why this stops the data source switch process from completing. 

It leaves you in a broken state with no way to retry. You only option is to go another page or select another data source then back again. The failure could have been caused by temporary network glitch or network/wifi issue. 

There is no query editor loaded (due to datasourceError stopping the query editors from rendering so easy to fix). But that fix is not enough,  and a lot of the properties that are set in loadDatasourceSuccess action should I think be set when changing datasource and not be dependant on the "test data source flow".  

2019-01-28_16-46-21_screenshot

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
Before this pull request when a datasource failed to load there was no good way to reconnect. Instead as a user you needed to navigate away from Explore or change datasource back/forward. This pull request adds the ability to reconnect on these failures.

**Before**
image

**After**
image

**Which issue(s) this PR fixes**:
Closes #15096

**Special notes for your reviewer**:
- Checkout the branch and test.
- There has been a whole lot of restructuring of actions and some payloads have moved
- `thunkTester` now supports async dispatch

### CODE REVIEW

**Comment by hugohaggmark** [comment]
These lines have been somewhat refactored into `changeDatasource`don't really understand the whole flow so would appreciate any feedback on the refactor. 
https://github.com/grafana/grafana/blob/2ae63e70c0df3ce2e1cf478d4173be72428c3dd9/public/app/features/explore/state/actions.ts#L211-L230

File: public/app/features/explore/state/actions.ts [hunk 1]
```diff
@@ -185,83 +222,35 @@ export function initializeExplore(
...
         queries,
         range,
         ui,
       })
     );
-
-    if (exploreDatasources.length >= 1) {
-      let instance;
-
-      if (datasourceName) {
```
Comment (hugohaggmark) [inline public/app/features/explore/state/actions.ts]: These lines have been somewhat refactored into `changeDatasource` don't really understand the `!instance` part so would appreciate any feedback on the refactor. 
https://github.com/grafana/grafana/blob/2ae63e70c0df3ce2e1cf478d4173be72428c3dd9/public/app/features/explore/state/actions.ts#L211-L230

File: public/app/features/explore/state/actions.ts [hunk 2]
```diff
@@ -331,8 +350,7 @@ export function loadDatasource(exploreId: ExploreId, instance: DataSourceApi): T
       return;
     }
 
-    dispatch(loadDatasourceSuccess(exploreId, instance));
-    return Promise.resolve();
```
Comment (hugohaggmark) [inline public/app/features/explore/state/actions.ts]: Do we need the Promise.resolve()?

File: public/app/features/explore/state/actions.ts [hunk 3]
```diff
@@ -313,10 +306,36 @@ export function loadDatasource(exploreId: ExploreId, instance: DataSourceApi): T
     }
 
     if (datasourceError) {
-      dispatch(loadDatasourceFailureAction({ exploreId, error: datasourceError }));
-      return Promise.reject(`${datasourceName} loading failed`);
```
Comment (hugohaggmark) [inline public/app/features/explore/state/actions.ts]: Do we need the Promise.reject()?

**Review by daniellee — DISMISSED** [review]
Metrics dropdown (to the left of the query field) does not work after reconnecting for the prometheus datasource in Explore.

**Comment by davkal** [comment]
Blocker: Also noticed the metrics chooser not working. 

Nit: on disconnected datasources, the error reappears after a flicker. would be great to either not have a flicker, or to add a manual delay.

**Comment by hugohaggmark** [comment]
Thanks for finding this issues, would appreciate any feedback on the refactoring too.

**Review by torkelo — COMMENTED** [review]
I like the refactoring, and the thunk tests looks really nice

File: public/app/features/explore/state/actions.ts (hunk 1 above)
Comment (torkelo) [reply public/app/features/explore/state/actions.ts]: can not understand it either

File: public/app/features/explore/state/actions.ts (hunk 2 above)
Comment (torkelo) [reply public/app/features/explore/state/actions.ts]: no should not be needed.

File: public/app/features/explore/state/actions.ts (hunk 3 above)
Comment (torkelo) [reply public/app/features/explore/state/actions.ts]: possibly, as the caller does a try catch, and if error skips execute queries. 
https://github.com/grafana/grafana/blob/3395b7411635774d418ec67e1bb657d66daf9acf/public/app/features/explore/state/actions.ts#L121

Comment (hugohaggmark) [reply public/app/features/explore/state/actions.ts]: Good catch, I'll fix.

File: public/app/features/explore/state/actions.ts (hunk 2 above)
Comment (hugohaggmark) [reply public/app/features/explore/state/actions.ts]: When I added Promise.reject then you get typescript errors if you don't also return Promise.resolve().
```typescript
public/app/features/explore/state/actions.ts:296:10 - error TS7030: Not all code paths return a value.

296   return async dispatch => {
             ~~~~~~~~~~~~~~~~~~~
```

File: public/app/features/explore/state/actions.ts (hunk 1 above)
Comment (davkal) [reply public/app/features/explore/state/actions.ts]: If the requested datasource is not available, it gets the default datasource (by not providing an argument to `get`).

Comment (torkelo) [reply public/app/features/explore/state/actions.ts]: of course, was the comment about it checking if data source was delete that tripped me :)

File: public/app/features/explore/state/actions.ts (hunk 2 above)
Comment (hugohaggmark) [reply public/app/features/explore/state/actions.ts]: Changed to check if state has `datasourceError` before running any queries

File: public/app/features/explore/state/actions.ts (hunk 3 above)
Comment (hugohaggmark) [reply public/app/features/explore/state/actions.ts]: Changed to check if state has `datasourceError` before running any queries

**Comment by hugohaggmark** [comment]
> I like the refactoring, and the thunk tests looks really nice

Had to refactor `thunkTester` as it did not fail tests properly.

**Comment by davkal** [comment]
I still don't get a working Metrics chooser after reconnect under these conditions:
- stop prometheus
- go to Explore and select Prometheus datasource
- start prometheus
- Click connect

Concretely, the DS is reloading rules, but it's not reloading `le` series (histograms) and label values:

Screenshot 2019-03-28 at 11 30 56


The fading works well, but now makes the loading message look a bit unstyled. But that should be addressed in a separate PR.

**Comment by dprokop** [comment]
Minor thing: alert is rendered within `div.explore-container` that has a padding set. It results in additional white space being rendered between the toolbar and query field:

image

**Comment by dprokop** [comment]
> I still don't get a working Metrics chooser after reconnect under these conditions:

Confirming this one

File: public/app/plugins/datasource/loki/components/LokiQueryField.tsx [hunk 4]
```diff
@@ -1,13 +1,20 @@
...
+import { useLokiForceRefresh } from './useLokiForceRefresh';
 
-const LokiQueryField: FunctionComponent<LokiQueryFieldFormProps> = ({ datasource, ...otherProps }) => {
+const LokiQueryField: FunctionComponent<LokiQueryFieldFormProps> = ({
+  datasource,
+  datasourceStatus,
+  ...otherProps
+}) => {
   const { isSyntaxReady, setActiveOption, refreshLabels, ...syntaxProps } = useLokiSyntax(datasource.languageProvider);
+  useLokiForceRefresh(datasourceStatus, refreshLabels);
```
Comment (dprokop) [inline public/app/plugins/datasource/loki/components/LokiQueryField.tsx]: I think this hook should be called on `useLokiSyntax` hook level as this hook is responsible for all things that Loki query field requires. I find `useLokiForceRefresh` hook not returning anything being even more magical than hooks already are ;)

You can easily accomplish that by extending `useLokiSyntax` signature to be 
```ts 
useLokiSyntax(languageProvider: LokiLanguageProvider, dataSourceStatus: DatasourceStatus)
```

File: public/app/plugins/datasource/loki/components/useLokiForceRefresh.ts [hunk 5]
```diff
@@ -0,0 +1,27 @@
+import { useState, useEffect } from 'react';
+import { DatasourceStatus } from '@grafana/ui/src/types/plugin';
+
+export const useLokiForceRefresh = (
+  datasourceStatus: DatasourceStatus,
+  refreshLabels: (forceRefresh?: boolean) => void,
+  initialDatasourceStatus?: DatasourceStatus
+) => {
+  const [prevDatasourceStatus, setPrevDatasourceStatus] = useState(
```
Comment (dprokop) [inline public/app/plugins/datasource/loki/components/useLokiForceRefresh.ts]: Don't think you need that state. Since the effect below is performed on `datasourceStatus` argument change only, then if the status changed to `connected` then you have all the information to perform labels refresh.

File: public/app/plugins/datasource/loki/components/useLokiForceRefresh.ts [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+    initialDatasourceStatus || DatasourceStatus.Connected
+  );
+  const [forceRefresh, setForceRefresh] = useState(false);
+
+  // Effects
+  useEffect(() => {
```
Comment (dprokop) [inline public/app/plugins/datasource/loki/components/useLokiForceRefresh.ts]: You actually don't need that effect at all. The effect below should be sufficient when refactored to:

```ts
useEffect(() => {
    if (datasourceStatus === DatasourceStatus.Connected) {
      refreshLabels(true);
    }
  }, [datasourceStatus]);
```

Since this effect will be perfoemed on `datasourceStatus` change only, then you are secured that the forced refresh will happen when the datasource becomes connected.

File: public/app/plugins/datasource/loki/components/useLokiLabels.ts [hunk 7]
```diff
@@ -66,14 +75,12 @@ export const useLokiLabels = (
   // Since shouldTryRefreshLabels is reset AFTER the labels are refreshed we are secured in case of trying to refresh
   // when previous refresh hasn't finished yet
   useEffect(() => {
-    if (shouldTryRefreshLabels) {
-      tryLabelsRefresh();
-    }
+    tryLabelsRefresh(shouldTryRefreshLabels);
   }, [shouldTryRefreshLabels]);
```
Comment (dprokop) [inline public/app/plugins/datasource/loki/components/useLokiLabels.ts]: Hm, getting rid of `useLokiForceRefresh` hook and moving the datasourceStatus could simplify this hook's logic. If, instead of introducing this:

```ts
const [shouldTryRefreshLabels, setRefreshLabels] = useState({ refresh: false, force: false });
```

you added:
```ts
const [shouldForceRefreshLabels, setForceRefreshLabels] = useState(false)
```

then this effect could be responsive to `dataSourceStatus` argument changes as well setting the `shouldForceRefreshLabels` to true if the status === connected. And then, in `tryLabelsRefresh`, when it's eventually executed on labels selector open event, it would simply pass the `shouldForceRefreshLabels` to languageProvider.refreshLogLabels and set it to `false` when labels are fetched. And the exposed `refreshLabels` wouldn't have to be changed below, I think

**Review by dprokop — CHANGES_REQUESTED** [review]

File: public/app/plugins/datasource/loki/components/LokiQueryField.tsx (hunk 4 above)
Comment (hugohaggmark) [reply public/app/plugins/datasource/loki/components/LokiQueryField.tsx]: I'll fix that

File: public/app/plugins/datasource/loki/components/useLokiForceRefresh.ts (hunk 5 above)
Comment (hugohaggmark) [reply public/app/plugins/datasource/loki/components/useLokiForceRefresh.ts]: Will it not refresh the first time then?

File: public/app/plugins/datasource/loki/components/useLokiForceRefresh.ts (hunk 6 above)
Comment (hugohaggmark) [reply public/app/plugins/datasource/loki/components/useLokiForceRefresh.ts]: It will refresh for the initial state then, right?

File: public/app/plugins/datasource/loki/components/useLokiLabels.ts (hunk 7 above)
Comment (hugohaggmark) [reply public/app/plugins/datasource/loki/components/useLokiLabels.ts]: I see what you mean, but I still think we need the previous state otherwise we'll get a force refresh for the initial state. I'll move the force refresh logic into this instead.

**Comment by hugohaggmark** [comment]
@dprokop updated useLokiLabels according to comments. I think it got better in some ways and worse in other, as we now need to pass `datasourceStatus` in `useLokiSyntax` and `useLokiLabels`.

**Comment by dprokop** [comment]
> I think it got better in some ways and worse in other, as we now need to pass datasourceStatus in useLokiSyntax and useLokiLabels.

I get your point.  I think we can try get rid of the need of passing ds status to `useLokiLabels` by exposing `setForceRefreshLabels` from that hook and moving the logic of setting the force refresh from to `useLokiSyntax` hook. Then the useLokiLabels would be responsible for actually delivering the labels only, why `useLokiSyntax` hook would be a higher order orchestrator. WDYT?

**Comment by dprokop** [comment]
Me and @hugohaggmark decided to skip above comment improvements and focus on that when unifying syntax/labels refresh logic for Prometheus to use the same mechanics as LokiQueryField uses.

**Review by dprokop — APPROVED** [review]

**Comment by hugohaggmark** [comment]
@davkal @daniellee now that I could reproduce the issue in Prometheus I believe the issue is gone.

**Review by davkal — APPROVED** [review]
Works well now. LGTM

Nice refactor, tests, and type additions 😻
