### PR TITLE
Tempo: Fix service graph menu item links

### LINKED ISSUE #74711: 'Explore' context menu items on the Node Graph are not working
### What happened?

In the Traces Node Graph, after clicking on a node to open its context menu, the items under the 'Explore' heading seem to do nothing, although the "Show in grid" is still working.

Possibly related: an error `Uncaught TypeError: m.preventDefault is not a function` is seen in the JS console when clicking one of these menu items.

image

### What did you expect to happen?

The traces Node Graph context menu items should respond to clicks and show request rate / histogram / failed request rate / view traces.

### Did this work before?

Yes - not sure of version.

### How do we reproduce it?

1. https://sedemo.grafana.net/explore?panes=%7B%22KgC%22:%7B%22datasource%22:%22XXcTW9R4z%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22tempo%22,%22uid%22:%22XXcTW9R4z%22%7D,%22queryType%22:%22serviceMap%22,%22limit%22:20%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1
2. Click a node graph item to show the context menu
3. Click one of the Explore items

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: Cloud - v10.2.0-60477
OS: Linux
Browser: Firefox

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Tempo

### LINKED ISSUE #74989: Service map: 'View traces' button takes you to '[Deprecated] Search'
### What happened?

User is taken to a [Deprecated query type] screen in Explore when clicking in the 'View traces' button of the 'Service map' component:

https://github.com/grafana/grafana/assets/7382419/7dc8419a-063c-4f89-b5e2-558c455c7515

### What did you expect to happen?

The user should be taken to the explore page with the proper query filled in

### Did this work before?

Not sure

### How do we reproduce it?

1. Navigate to Service map (e.g. from the [appo11y demo tab](https://sedemo.grafana.net/a/grafana-app-observability-app/services/opentelemetry-demo---adservice/service-map?var-prometheus=grafanacloud-sedemo-prom&var-loki=grafanacloud-sedemo-logs&var-tempo=grafanacloud-sedemo-traces))
2. Click on second node (`adservice`)
3. Get taken to Explore page where the error happens

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Tempo

### PR DESCRIPTION
**Pull request by adrapereira**
**What is this feature?**

This PR fixes an issue where the service graph menu items wouldn't navigate to the link on click. 

It also updates the Tempo link to use the new TraceQL search tab instead of the deprecated search.

**Who is this feature for?**

Users of the Tempo datasource service graph.

**Which issue(s) does this PR fix?**:

Fixes #74989
Fixes #74711

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by mckn — COMMENTED** [review]
LGTM! But waiting for code owners to approve.

File: pkg/tsdb/tempo/trace.go [hunk 1]
```diff
@@ -28,7 +28,11 @@ func (s *Service) getTrace(ctx context.Context, pCtx backend.PluginContext, quer
 		return nil, err
 	}
 
-	request, err := s.createRequest(ctx, dsInfo, model.Query, query.TimeRange.From.Unix(), query.TimeRange.To.Unix())
+	if model.Query == nil || *model.Query == "" {
+		return result, fmt.Errorf("trace id is required")
```
Comment (joey-grafana) [inline pkg/tsdb/tempo/trace.go:32]: This error message should be updated to reflect that this can be a trace id or a traceql query.

File: public/app/plugins/datasource/tempo/datasource.ts [hunk 2]
```diff
@@ -1025,12 +1025,26 @@ export function getFieldConfig(
...
   if (spanName !== '') {
-    query.spanName = spanName;
+    query.filters.push({
+      id: 'span-name',
+      scope: TraceqlSearchScope.Span,
+      tag: 'name',
+      value: spanName,
+      operator: '=',
+      valueType: 'string',
+    });
```
Comment (joey-grafana) [inline public/app/plugins/datasource/tempo/datasource.ts:1047]: This sets the service/span name in the tags, as opposed to the dedicated `Resource Service Name` or `Span Name` fields. Users cannot select service/span name in the tags but when it's injected, if they change the tag they cannot reselect either. Also, what happens if they also select service/span name in the dedicated fields.. would the tags override those values.

**Review by joey-grafana — COMMENTED** [review]
Would also love to close the menu once an item is clicked but that can be in another PR if you like.

File: public/app/plugins/datasource/tempo/datasource.ts (hunk 2 above)
Comment (joey-grafana) [reply public/app/plugins/datasource/tempo/datasource.ts:1047]: So it's more of an edge case but is possible. I select app in the service graph and then also set the service name myself which results in `resource.service.name` being in the query twice. You can't add `resource.service.name` in the query twice from the editor. We can merge as is this is not a big issue.

Screenshot 2023-10-09 at 13 34 02

**Review by joey-grafana — APPROVED** [review]
