### PR TITLE
CloudWatch: Credentials cache invalidation fix

### LINKED ISSUE #22468: cloudwatch credentials cache not invalidated when the datasource config is updated
**What happened**:
If a cloudwatch datasource is configured with valid credentials, then you update the config to use authType=arn , datasource requests will continue to use cached credentials without assuming the specified ARN.

**What you expected to happen**:
When updating a datasource config cached credentials should be invalidated.

**Anything else we need to know?**:
The issue is that cloudwatch credentials are cached for 5minutes: https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/credentials.go#L86
When fetching items from the cache, no consideration is made for whether the DS config has changed since the credentials were cached.

### PR DESCRIPTION
**Pull request by sunker**
See https://github.com/grafana/grafana/issues/22468 for detailed description

fixes #22468

### CODE REVIEW

File: pkg/tsdb/cloudwatch/credentials.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ var awsCredentialCache = make(map[string]cache)
 var credentialCacheLock sync.RWMutex
 
 func GetCredentials(dsInfo *DatasourceInfo) (*credentials.Credentials, error) {
-	cacheKey := dsInfo.AccessKey + ":" + dsInfo.Profile + ":" + dsInfo.AssumeRoleArn
+	cacheKey := fmt.Sprintf("%s:%s:%s:%s", dsInfo.AuthType, dsInfo.AccessKey, dsInfo.Profile, dsInfo.AssumeRoleArn)
```
Comment (marefr) [inline pkg/tsdb/cloudwatch/credentials.go]: I can see that region is used below. What happens if someone changes the default region when the credentials are cached? Not sure if the current caching solution is preferred if multiple cloudwatch data sources using same credentials, but different default regions, and by that are able to reuse the same credentials?

One alternative to this would be to implement [same caching as used for data sources](https://github.com/grafana/grafana/blob/master/pkg/models/datasource_cache.go#L63) using datasource id as key and check if it have been updated and if so invalidate the cache. One advantage of this is that the cache will only be as large as the number of data sources where's the current approach is more dynamic and can in theory create a very large cache.

**Review by marefr — COMMENTED** [review]
Added some comments

**Review by marefr — APPROVED** [review]
LGTM

This should resolve the issue, but there's definitely room for improvements here
