### PR TITLE
ColorPickerInput: Fixed color picker disappearing on input blur

### LINKED ISSUE #97252: UI components: Color Picker Input, color popover not working if open via input
### What happened?

`colorpicker--input` UI component closes color popover if popover open via input, instead button 

https://github.com/user-attachments/assets/cd0f5bd6-74e4-49cc-bdfc-64c3f89c8d21

### What did you expect to happen?

Color popover should not close
Color popover should allow select color

### Did this work before?

Not sure 

### How do we reproduce it?

1. Go to https://developers.grafana.com/ui/latest/index.html?path=/story/pickers-and-editors-colorpicker--input
2. Focus (click) on the input field with color
3. Popover is open
4. Try to change color via Popover
5. Popover immediately closed 

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: Main (11.3.0)
OS: Linux (Ubuntu 22.04.5 LTS)
Browser: Chrome (129.0.6668.89)

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by CollinFingar**
**What is this feature?**

A bug fix for ColorPickerInput blur functionality. It only closes the color popover if it detects no classes w/ "react-colorful" on the blur focus event.

**Why do we need this feature?**

Right now, the color popover panel disappears on click after the user had previously clicked/focused on the Input element itself. This is due to the Input's blur logic blindly closing the popover regardless on if the Input is being blurred due to clicking the panel.

**Who is this feature for?**

Users of this utility.

**Which issue(s) does this PR fix?**:

Fixes #[97252](https://github.com/grafana/grafana/issues/97252)

https://github.com/user-attachments/assets/7388e3c0-00cc-4925-82b9-d7c3fdeeedfc

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/ColorPicker/ColorPickerInput.tsx [hunk 1]
```diff
@@ -48,6 +48,13 @@ export const ColorPickerInput = forwardRef<HTMLInputElement, ColorPickerInputPro
       [currentColor]
     );
 
+    const handleBlur = (evt: FocusEvent<HTMLInputElement>) => {
+      // Unless the user clicked inside the color picker, close it on blur
+      if (!Boolean(evt.relatedTarget?.className?.split(' ').some((c) => /react-colorful/.test(c)))) {
```
Comment (Clarity-89) [inline packages/grafana-ui/src/components/ColorPicker/ColorPickerInput.tsx:53]:
```suggestion
      if (!evt.relatedTarget?.className.includes('react-colorful')) {
```
I think this can be simplified a bit.

File: packages/grafana-ui/src/components/ColorPicker/ColorPickerInput.test.tsx [hunk 2]
```diff
@@ -12,6 +12,24 @@ describe('ColorPickerInput', () => {
...
+  });
+
+  it('should not hide color popover on blur if clicked inside the color picker', async () => {
+    render(<ColorPickerInput onChange={noop} />);
+    expect(screen.queryByTestId('color-popover')).not.toBeInTheDocument();
+    await userEvent.click(screen.getByRole('textbox'));
+    expect(screen.getByTestId('color-popover')).toBeInTheDocument();
+    await userEvent.click(screen.getAllByRole('slider')[0]);
+    expect(screen.queryByTestId('color-popover')).toBeInTheDocument();
+  });
```
Comment (ashharrison90) [inline packages/grafana-ui/src/components/ColorPicker/ColorPickerInput.test.tsx:31]: love these 🚀

File: packages/grafana-ui/src/components/ColorPicker/ColorPickerInput.tsx (hunk 1 above)
Comment (ashharrison90) [reply packages/grafana-ui/src/components/ColorPicker/ColorPickerInput.tsx:53]: we never want to rely on class names since they could change at any moment, e.g. if we update the library. think a more robust solution should rely on something we control:
```tsx
      const isClickInPopover = document.querySelector('[data-testid="color-popover"]')?.contains(evt.relatedTarget);
      if (!isClickInPopover) {
        setIsOpen(false);
      }
```
or maybe we could pass an explicit `id` instead of reusing the `data-testid`. it doesn't really matter 🤷

**Review by ashharrison90 — COMMENTED** [review]
just 1 nit, looks great! 🙌 

one convention we have is if there's an existing issue on the board, we mark the PR as fixing the issue but _don't_ attach the PR to the project board. that's because the issue will show the linked PR anyway, and we avoid having duplicate tickets in the board like this:
image

File: packages/grafana-ui/src/components/ColorPicker/ColorPickerInput.tsx (hunk 1 above)
Comment (joshhunt) [reply packages/grafana-ui/src/components/ColorPicker/ColorPickerInput.tsx:53]: +1 - would rather be passing in an explicit ID/ref than relying on a class name remaining stable.

Comment (CollinFingar) [reply packages/grafana-ui/src/components/ColorPicker/ColorPickerInput.tsx]: Hey folks, thanks for the feedback and good points. I updated to use an `id` for the targeting method. Let me know what you think.

**Review by ashharrison90 — APPROVED** [review]
looks perfect! 🙌

File: packages/grafana-ui/src/components/ColorPicker/ColorPickerInput.tsx [hunk 3]
```diff
@@ -48,11 +50,20 @@ export const ColorPickerInput = forwardRef<HTMLInputElement, ColorPickerInputPro
...
+        setIsOpen(false);
+      }
+    };
+
     return (
       <ClickOutsideWrapper onClick={() => setIsOpen(false)}>
         <div className={styles.wrapper}>
           {isOpen && !inputProps.disabled && (
             <RgbaStringColorPicker
+              id={COLOR_POPOVER_ID}
```
Comment (Clarity-89) [inline packages/grafana-ui/src/components/ColorPicker/ColorPickerInput.tsx:66]: Maybe better to use data-testid, so we avoid the case when multiple pickers used at the same time (unlikely, but possible) and we get two same ids?

Comment (tskarhed) [reply packages/grafana-ui/src/components/ColorPicker/ColorPickerInput.tsx:66]: Would using a `ref` instead make sense here?

Comment (CollinFingar) [reply packages/grafana-ui/src/components/ColorPicker/ColorPickerInput.tsx]: I thought the id issue too, but was unsure on using a test id for this purpose. I updated to use data-testid.

I tried making use of `ref` during my first attempt, but I couldn't find a way for the package to support it (short of wrapping the popover in a div and placing ref on that which didn't seem ideal to me).
