### PR TITLE
AlertNotifications: Translate notifications IDs to UIDs in Rule builder

### LINKED ISSUE #19771: Dashboards saved with numeric IDs for alert notifications are not triggering notifications
**What happened**:
Dashboards created via API that point to alert notification channels via numeric IDs are not triggering these notification channels.
 
These dashboards are saved successfully, notification channels showing up in alert configs but are never triggered.

**What you expected to happen**:  

One of:  

- 
  1. For numeric IDs to be supported and trigger the notification channels
- 
  1. To get an error when saving dashboard with numeric IDs for alert notifications channels
  2. For the alert notification with numeric ID to not show up in the UI after save

**How to reproduce it (as minimally and precisely as possible)**:  
- Create a new webhook alert notification channel (any url that logs requests will do)
- Copy the alert numeric ID from the URL: `grafana.instance/alerting/notification/$NUMERIC_ID/edit`. 
- Create new dashboard and a panel with any metric and add any alert condition
- Open `Dashboard Settings -> JSON Model` and add `{ "id": $NUMERIC_ID }` into `panels[0].alert.notifications` array.
- Save the dashboard
- Edit panel alert and verify that the new notification channel is appearing in the list
- Trigger the alert (e.g. by editing the condition and saving)

**Expected**:
For the alert to be sent to the webhook URL

**Actual**:
The alert is not sent to the webhook URL

**Anything else we need to know?**:
Not sure when this breaking change was introduced

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: irrelevant
- OS Grafana is installed on: Debian 3.16.36
- User OS & Browser: irrelevant 
- Grafana plugins: irrelevant
- Others:

### PR DESCRIPTION
**Pull request by aSapien**
**What this PR does / why we need it**:
Fixes alert notifications for dashboards that were saved with notification IDs

**Which issue(s) this PR fixes**:
Fixes #19771

**Special notes for your reviewer**:
I wasn't sure if `rule.go` is the correct place for this fix, but it seemed the easiest to put there. Please let me know if there's a better approach to fixing this. 

**Bug trace**:  
Currently, IDs are parsed, converted to strings and included in the same slice (of UIDs):
https://github.com/grafana/grafana/blob/c674fa1d794c2b3ef7b9ba51b977c581237f3cc6/pkg/services/alerting/rule.go#L139-L147

In a later stage they are used in https://github.com/grafana/grafana/blob/c674fa1d794c2b3ef7b9ba51b977c581237f3cc6/pkg/services/alerting/notifier.go#L161-L162

Which in turn triggers a query, however, the SQL query expects UIDs and doesn't consider "stringified" IDs:
https://github.com/grafana/grafana/blob/c674fa1d794c2b3ef7b9ba51b977c581237f3cc6/pkg/services/sqlstore/alert_notification.go#L111

This causes notification entities for IDs to not be returned and therefore to not be triggered.

### CODE REVIEW

**Comment by aSapien** [comment]
@torkelo

**Comment by torkelo** [comment]
How are you getting alert rules with notification ids? new rules should use uids. Only legacy rules should still use ids, and we convert those to uids same way we migrated them in the DB

**Comment by aSapien** [comment]
@torkelo We have system that generates dashboards with ID based notification channels

**Comment by aSapien** [comment]
Is there a migration for dashboards that point to notifications by the old IDs? I'm only seeing the migration of the `alerts_notifications` table:

https://github.com/grafana/grafana/blob/7a8f2cd75d1c64cd0d5d5fcfc7ec4473416a800e/pkg/services/sqlstore/migrations/alert_mig.go#L155-L159

**Comment by Tim-Schwalbe** [comment]
any plans to solve this issue on the codebase? I think a lot of people will run into this problem.
I have updated from 6.0.2 and luckily recognize the issue, but it could be a huge trap for others.

File: pkg/services/alerting/rule.go [hunk 1]
```diff
@@ -137,7 +138,8 @@ func NewRuleFromDBAlert(ruleDef *models.Alert) (*Rule, error) {
 	for _, v := range ruleDef.Settings.Get("notifications").MustArray() {
 		jsonModel := simplejson.NewFromAny(v)
 		if id, err := jsonModel.Get("id").Int64(); err == nil {
-			model.Notifications = append(model.Notifications, fmt.Sprintf("%09d", id))
+			maybeUID := translateNotificationIDToUID(id, ruleDef.OrgId)
```
Comment (papagian) [inline pkg/services/alerting/rule.go]: As I suggested in another comment I think that `translateNotificationIDToUID` should return also the error
which it should be checked here and if it's not `null` it should return a `ValidationError` similar to this [one](https://github.com/grafana/grafana/blob/6cd001f09a7c1e7ed1fc10a8302c9fcfed9a0d93/pkg/services/alerting/rule.go#L146).

File: pkg/services/alerting/rule_test.go [hunk 2]
```diff
@@ -60,7 +60,7 @@ func TestAlertRuleModel(t *testing.T) {
 		})
 
 		Convey("can construct alert rule model", func() {
```
Comment (papagian) [inline pkg/services/alerting/rule_test.go]: Can you add a test for trying to create an alert rule with invalid (not-existing) notification id?

File: pkg/services/alerting/rule.go [hunk 3]
```diff
@@ -137,7 +138,8 @@ func NewRuleFromDBAlert(ruleDef *models.Alert) (*Rule, error) {
...
+			model.Notifications = append(model.Notifications, maybeUID...)
```
Comment (papagian) [inline pkg/services/alerting/rule.go]: If `translateNotificationIDToUID `returns `string` instead of `[]string`, following my suggestion, then you won't need `...`.

**Review by papagian — CHANGES_REQUESTED** [review]
Thank you for your contribution!
Please check my comments for some suggested improvements.

**Comment by aSapien** [comment]
@papagian thank you for the comments. I'll try to complete the needed changes soon.

File: pkg/services/alerting/rule.go (hunk 1 above)
Comment (aSapien) [reply pkg/services/alerting/rule.go]: agreed

File: pkg/services/alerting/rule_test.go (hunk 2 above)
Comment (aSapien) [reply pkg/services/alerting/rule_test.go]: with pleasure :)

File: pkg/services/alerting/rule.go (hunk 3 above)
Comment (aSapien) [reply pkg/services/alerting/rule.go]: done

File: pkg/services/alerting/rule.go [hunk 4]
```diff
@@ -136,14 +137,14 @@ func NewRuleFromDBAlert(ruleDef *models.Alert) (*Rule, error) {
...
-				return nil, ValidationError{Reason: "Neither id nor uid is specified in 'notifications' block, " + err.Error(), DashboardID: model.DashboardID, AlertID: model.ID, PanelID: model.PanelID}
-			}
+		if uid, err := getNotificationUidFromIdField(jsonModel, ruleDef); err == nil {
+			model.Notifications = append(model.Notifications, uid)
+		} else if err.Error() != "invalid value type" {
+			return nil, ValidationError{Reason: "Unable to translate notification id to uid, " + err.Error(), DashboardID: model.DashboardID, AlertID: model.ID, PanelID: model.PanelID}
+		} else if uid, err := getNotificationUidFromUidField(jsonModel); err == nil {
 			model.Notifications = append(model.Notifications, uid)
+		} else {
+			return nil, ValidationError{Reason: "Neither id nor uid is specified in 'notifications' block, " + err.Error(), DashboardID: model.DashboardID, AlertID: model.ID, PanelID: model.PanelID}
```
Comment (papagian) [inline pkg/services/alerting/rule.go]: I think that this block was more readable as it was before.
Therefore I would suggest to get rid of `getNotificationUidFromUidField` and `getNotificationUidFromIdField` and change it to:
```
if id, err := jsonModel.Get("id").Int64(); err == nil {
    uid, err := translateNotificationIDToUID(id, ruleDef.OrgId)
    if err != nil {
        return nil, ValidationError{Reason: "Unable to translate notification id to uid, " + err.Error(), DashboardID: model.DashboardID, AlertID: model.ID, PanelID: model.PanelID}
    }
    model.Notifications = append(model.Notifications, uid)
} else {
    uid, err := jsonModel.Get("uid").String()
    if err != nil {
        return nil, ValidationError{Reason: "Neither id nor uid is specified in 'notifications' block, " + err.Error(), DashboardID: model.DashboardID, AlertID: model.ID, PanelID: model.PanelID}
    }
    model.Notifications = append(model.Notifications, uid)
}
```

**Review by papagian — CHANGES_REQUESTED** [review]
Great! Thanks for the modifications.
I have a minor comment.

File: pkg/services/alerting/rule.go (hunk 4 above)
Comment (aSapien) [reply pkg/services/alerting/rule.go]: sure, i inlined it :)

**Review by papagian — CHANGES_REQUESTED** [review]
Great!
I have a minor request before merging, please check my inline comment!

Additionally, it would be nice to do some UID caching.
Therefore I would recommend to change the [`GetAlertNotifications`](https://github.com/grafana/grafana/blob/44e140955ca14583b647251ca3a38e6ab5873c7a/pkg/services/sqlstore/alert_notification.go#L66) to save the result in the cache and check whether it exists in the cache before running the actual query. [Here](https://github.com/grafana/grafana/blob/df1d43167af035c6819923ecce135056f37c79c2/pkg/services/sqlstore/user.go#L329) you can find an example of using the cache.

**Comment by aSapien** [comment]
@papagian are you referring to caching the id->uid translation result? This makes perfect sense.

**Comment by papagian** [comment]
> @papagian are you referring to caching the id->uid translation result? This makes perfect sense.

yes! sorry for not being clear

**Comment by aSapien** [comment]
great! I was concerned about caching values that might change in runtime 😅

**Comment by aSapien** [comment]
@papagian The CacheService example resides within the SqlStore and caches the result of `models.SignedInUser`.  
In our case, we're in fact executing a query that returns the same `AlertNotification` result twice. First by `id` for the sole purpose of obtaining a `uid` and second for the actual `AlertNotification` DTO. Caching the `AlertNotification` DTO only for `id->uid` translation sounds to me like a risky idea, because it contains too much unrelated information that might change in runtime and doesn't convey the purpose. I'm afraid it might open a gate to misuse of these cached items which may have already been updated in the data store. WDYT?

**Comment by aSapien** [comment]
I can think of a few possible ways to go about this:  
1. Use a dedicated DTO containing only `NotificationId` and `NotificationUid` and cache that. Then, within `func GetAlertNotificationByID(c *models.ReqContext)` try to lookup in that cache. If found, execute `GetAlertNotificationByUID` in the implementation. Otherwise, lookup by `id` and create a cache entry.  
2. In-memory map right within `rule.go` to hold the cache

**Comment by papagian** [comment]
> I can think of a few possible ways to go about this:
> 
> 1. Use a dedicated DTO containing only `NotificationId` and `NotificationUid` and cache that. Then, within `func GetAlertNotificationByID(c *models.ReqContext)` try to lookup in that cache. If found, execute `GetAlertNotificationByUID` in the implementation. Otherwise, lookup by `id` and create a cache entry.

You are right that caching the whole query result can have implications and my main intention for using the caching is for minimising the overhead introduced by the addition query for getting the `Uid`. And I like the idea of having a dedicated DTO for it. So, what I think you can do is to define a  new query like:

```
type GetAlertNotificationUidQuery struct {
	Id    int64
	OrgId int64

	Result string
}
```

and a dedicated function (inside [alert_notification.go](https://github.com/grafana/grafana/blob/df1d43167af035c6819923ecce135056f37c79c2/pkg/services/sqlstore/alert_notification.go)) for getting the `Uid` where you can check first the cache and if the key is not there to perform the actual query, with the following signature:
`func (ss *SqlStore)  GetAlertNotificationUidWithId(query *m.GetAlertNotificationUidQuery)`

Does this make sense?

**Comment by aSapien** [comment]
Yep, makes sense :) I'm on it

**Comment by aSapien** [comment]
@papagian I'm not sure why [mysql-integration-test](https://circleci.com/gh/grafana/grafana/265978) failed but it looks like a timeout issue. Is there a way to run it locally? I can't re-run from CircleCI

**Comment by papagian** [comment]
@aSapien 
It seems to be a timeout. I have rerun the CI workflow and hopefully it will be ok.
For your information for running mysql tests you can try:
`./scripts/circle-test-mysql.sh`
which actually sets environmental variable `GRAFANA_TEST_DB=mysql` and on top of this using the `integration` build tag for running integration tests.

**Comment by aSapien** [comment]
@papagian Yep, it's fine now, but failing on [grafana-docker-ubuntu-pr](https://circleci.com/gh/grafana/grafana/269939) which has nothing to do with this PR. Please review :)

**Comment by papagian** [comment]
@aSapien 
FYI there is a fix for `grafana-docker-ubuntu-pr` in the master branch so for overcoming it you need to sync your branch with the master.
But I will review it anyway tomorrow.

**Review by papagian — CHANGES_REQUESTED** [review]
Great work! Thank you for the modifications.
I have some suggestions for improving the tests.
Let me know if you want to work on them or you would prefer me to do it.

**Comment by aSapien** [comment]
@papagian thanks for the comments! I'll do the modifications. They help me learn _idiomatic_ Golang :)

File: pkg/services/sqlstore/alert_notification_test.go [hunk 5]
```diff
@@ -321,5 +321,54 @@ func TestAlertNotificationSQLAccess(t *testing.T) {
 				So(len(query.Result), ShouldEqual, 4)
 			})
 		})
+
+		Convey("Notification Uid by Id Caching", func() {
+			ss.CacheService.Flush()
```
[the remark this answers is not in the document]
Comment (aSapien) [reply pkg/services/sqlstore/alert_notification_test.go]: @papagian I saw that some tests initialize a separate TestDb for isolated test scopes. Perhaps I should use this technique instead? I like it because it's less verbose. https://github.com/grafana/grafana/blob/5aeb367322bbe33d4b95d84c33a05da17676feac/pkg/services/sqlstore/user_test.go#L313-L315

[the remark this answers is not in the document]
Comment (aSapien) [reply pkg/services/sqlstore/alert_notification_test.go]: Then there's not even a need to flush :)

File: pkg/services/sqlstore/alert_notification_test.go [hunk 6]
```diff
@@ -321,5 +321,54 @@ func TestAlertNotificationSQLAccess(t *testing.T) {
...
+
+			notification := &models.CreateAlertNotificationCommand{Uid: "aNotificationUid", OrgId: 1, Name: "aNotificationUid"}
```
[the remark this answers is not in the document]
Comment (aSapien) [reply pkg/services/sqlstore/alert_notification_test.go]: @papagian I'm a bit confused.

In the real implementation, [`getAlertNotificationUidInternal`](https://github.com/grafana/grafana/blob/7fb6d2c1d77d08297ab6ab75e5b5a1688826464d/pkg/services/sqlstore/alert_notification.go#L231) is only called if the key is not found in cache and goes to the DB to search for a corresponding UID. If it's not in the DB it returns an error.  
Therefore, it seems redundant to count the method calls, because the test `Retrieves from cache when exists` creates a scenario where a single call to `getAlertNotificationUidInternal` would yield an error. Thus, verifying that it's not called when the item is in cache. 

The corresponding test `Can cache notification Uid` verifies that `getAlertNotificationUidInternal` has been called because the cache is populated with items from the DB. 

So, don't the two tests together already verify these scenarios? 

* I admit I'm a bit biased towards Chicago school TDD 😇

File: pkg/services/sqlstore/alert_notification_test.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (papagian) [reply pkg/services/sqlstore/alert_notification_test.go]: yes, you can do that instead

File: pkg/services/sqlstore/alert_notification_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (papagian) [reply pkg/services/sqlstore/alert_notification_test.go]: Both `Can cache notification Uid` and `Retrieves from cache when exists` actually test that the key is stored in the cache but this does not necessarily mean that the database is not accessed.
Anyway, I don't insist if you think that these scenarios are too exaggerated.

[the remark this answers is not in the document]
Comment (aSapien) [reply pkg/services/sqlstore/alert_notification_test.go]: I just committed a change that pushes the error down the call path, so that empty query results would return an error and avoid cache population with empty Uid strings.  
So now we can rely on these tests to verify that there really is no DB access when a cached value is found. :)

File: pkg/services/sqlstore/alert_notification_test.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (papagian) [reply pkg/services/sqlstore/alert_notification_test.go]: Not that important but my last impression was that you would use a separate test database for these tests and you would remove flushing.

**Review by papagian — COMMENTED** [review]
The modifications look good to me only check my last comment.

**Comment by aSapien** [comment]
@papagian Thanks for pointing it out! It must've slipped my mind somehow... I made the necessary change

**Review by papagian — APPROVED** [review]

**Comment by papagian** [comment]
Thank you for contributing!

**Comment by papagian** [comment]
@aSapien could you synchronise your branch with master in order to trigger running the new `build-pipeline` workflow and be able to merge it?
I can do it myself if you prefer but I'm wasn't sure since the PR is targeting your repository's master.

**Comment by aSapien** [comment]
@papagian yeah working on a fork's master was poor choice. I synced the branches :)
