### PR TITLE
Prometheus: Fix issues with ad-hoc filters

### LINKED ISSUE #14556: Explore: Prometheus table label click to filter can go wrong
0. Explore enabled, Prometheus data source
1. Issue query like `sum by (status) (label_replace(label_replace(rate(http_requests_total{}[1m]), "status", "${1}xx", "code", "([0-9]).."), "status", "${1}",   "code", "([a-z]+)"))`
2. Then click on a label `4xx` in the table status column

Result: the query ends up being `sum by (status) (label_replace(label_replace(rate(http_requests_total{status="4xx"}{status="4xx"}[1m]), "status", "${status="4xx"}xx", "code", "([0-9]).."), "status", "${status="4xx"}",   "code", "([a{status="4xx"}-z]+)"))` 

Expected: `sum by (status) (label_replace(label_replace(rate(http_requests_total{status="4xx"}[1m]), "status", "${1}xx", "code", "([0-9]).."), "status", "${1}",   "code", "([a-z]+)"))` even though it's wrong since the label of the metric `http_requests_total` is `code`. But at least it would keep the query syntactically correct.

### LINKED ISSUE #14802: Ad-hoc filters with prometheus and joins doesn't work
Started off with this query in a table

```
max by (org_id, org_name, id, name, type) (grafanacloud_instance_info{type=~"prometheus|graphite|graphite-shared"})
  * on(id) group_right(org_id, org_name, type, name)
sum by (id) (grafanacloud_instance_created_date)
  * 1000
```

Selected "filter for value type=prometheus" and Grafana produce the following (incorrect) query:

```
max by (org_id, org_name, id, name, type) (grafanacloud_instance_info{type=~"prometheus|graphite|graphite-shared",type="prometheus"})
  * on(id{type="prometheus"}) group_right(org_id, org_name, type, name{type="prometheus"})
sum by (id) (grafanacloud_instance_created_date{type="prometheus"})
  * 1000
```

### LINKED ISSUE #16486: Ad-hoc filters don't work with logical operators in formulas
**What happened**:
Ad-hoc filtering isn't working if operator OR is used in a formula.

**How to reproduce it (as minimally and precisely as possible)**:
It was tested on next formulas
OK: grafana_info
Screenshot_20190410_130147

Failed: grafana_info or go_info
Screenshot_20190410_130219

**Environment**:
- Grafana version: 6.1.3
- Data source type & version: Prometheus 2.7.1
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Chrome Version 73.0.3683.103 (Official Build) (64-bit)

### LINKED ISSUE #19008: Adhoc filter values incorrectly populate range selector ${__range_s} in addition to instant selectors
We are using ${__range_s}  in SingleStat range selector dashboards to query number of changes in timerange. When Adhoc filters are used to filter the query the resulting query is incorrectly generated. You can check the outcome using Prometheus link or Query inspector.
For example set time range to last 1h.

Original query:
sum(rate(http_server_requests_seconds_count{}[${__range_s}s]))
generates query 
?query=sum(rate(http_server_requests_seconds_count{}[3600s]))

Adding Adhoc filter status="200" generates query
?query= sum(rate(http_server_requests_seconds_count{status="200"}[${status="200"}s]))

Adding Adhoc filter status="200" and method="GET" generates query
?query= sum(rate(http_server_requests_seconds_count{status="200", method="GET"}[${status="200", method="GET"}s]))

Query using [[__range_s]]s is not working at all (without Adhoc):
sum(rate(http_server_requests_seconds_count{}[[[__range_s]]s]))

Expected outcome:
Adding Adhoc filter status="200" generates query
?query= sum(rate(http_server_requests_seconds_count{status="200"}[3600s]))

Adding Adhoc filter status="200" and method="GET" generates query
?query= sum(rate(http_server_requests_seconds_count{status="200", method="GET"}[3600s]))

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Windows, Linux
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

### LINKED ISSUE #26029: Prometheus: Dashboard filters cause query failures when used on dashboards with dashboard variables of type "custom"
**What happened**:

If you add filters to a dashboard (for example through the table 'filter for value' and 'filter out value' feature on rows) and your dashboard has a dashboard variable of type "custom" (to pick one option from a list, for example), Prometheus queries that use that dashboard variable will fail. The queries fail because Grafana is attempting to apply a Prometheus {} label filter to the custom variable value.

The effect of this is to turn a query such as ``count(node_filesystem_avail_bytes{fstype!="rootfs",mountpoint="/"} < (5*1024*1024*1024) or vector(0)) - 1``
into ``count(node_filesystem_avail_bytes{fstype!="rootfs",mountpoint="/",probe!="icmp"} < (5{probe!="icmp"}*1024*1024*1024) or vector(0)) - 1``. Here the 5 in the ``5*1024*1024*1024`` portion is the custom variable, but the substituted string becomes ``5{probe!="icmp"}`` instead of just ``5`` when the filter is added. Prometheus rejects this query with a syntax error:

```
"invalid parameter 'query': 1:104: parse error: unexpected \"{\" in aggregation"
```

**Environment**:
- Grafana version: 7.0.5, but the bug has been present in a number of earlier versions
- Data source type & version: Prometheus 2.19.2
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Firefox on Fedora 31
- Grafana plugins: flant-statusmap-panel, natel-discrete-panel

### LINKED ISSUE #29857: Prometheus ad-hoc filter gets inserted into sum by statement when another variable is used
**What happened**:
In a dashboard with a prometheus datasource an ad-hoc filter and further variables, usage of variables in the by-clause of a sum aggregation gets falsely modified by the ad-hoc filter. Using the deprecated [[variable]] syntax works correctly

**What you expected to happen**:
I expect the ad-hoc filter to behave correctly while using variables in a sums by clause.

**How to reproduce it (as minimally and precisely as possible)**:
We have a dashboard with a prometheus data source and an ad-hoch filter. Now I want to modify a query like this:
`sum(rate({__name__=~"some_metric_names_.*"}[2m])) by (valueName)`

to accept another variable which can be used to modify the by-clause for multiple panels on the board like so:
`sum(rate({__name__=~"some_metric_name_.*"}[2m])) by (valueName $grouping)`

Whether $grouping is empty or contains ",otherLabel" the result is falsely modified by the ad-hoc filter. 
Assuming the ad-hoc-filter is configured to 

> kubernetes_namespace_name = some-namespace
> name = some-name

When opening the query inspector the requested uri is
`api/datasources/proxy/21/api/v1/query_range?query=sum(rate(%7B__name__%3D~%22some_metric_name_.*%22%2Ckubernetes_namespace%3D%22some-namespace%22%2Cname%3D%22some-name%22%7D%5B2m%5D))%20by%20(valueName%20%7Bkubernetes_namespace%3D%22some-namespace%22%2Cname%3D%22some-name%22%7D)&start=1608057540&end=1608061140&step=60`

When using the deprecated variable syntax it works:
`sum(rate({__name__=~"some_metric_name_.*"}[2m])) by (valueName [[grouping]])`
results in
`api/datasources/proxy/21/api/v1/query_range?query=sum(rate(%7B__name__%3D~%22some_metric_name_.*%22%2Ckubernetes_namespace%3D%22some-namespace%22%2Cname%3D%22some-name%22%7D%5B2m%5D))%20by%20(valueName%20)&start=1608058080&end=1608061680&step=60`

It also works with additional Input like ",otherLabel" in $grouping.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.2.1 (72a6c64532)
- Data source type & version: Prometheus
- OS Grafana is installed on: I don't know (if necessary I can try to inquire info)
- User OS & Browser: Windows / Chrome
- Grafana plugins: I don't know (if necessary I can try to inquire info)
- Others:

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
I have added a test scenario for each of this queries. 

**Issues:** 

✅  https://github.com/grafana/grafana/issues/29857 **Problem**: When using template variables, we consider variable to be metric
**Query:** `sum(rate({__name__=~"some_metric_name_.*"}[2m])) by (valueName $grouping)` 
**Correct:** `sum(rate({**name**=~"some*metric_name*.\*",kubernetes_namespace="some-namespace",name="some-name"}[2m])) by (valueName )`
**Incorrect:** `sum(rate({__name__=~"some_metric_name_.*",kubernetes_namespace="some-namespace",name="some-name"}[2m])) by (valueName {kubernetes_namespace="some-namespace",name="some-name"})`

✅ https://github.com/grafana/grafana/issues/16486 **Problem:** Filter is not applied to metrics after **or**
**Query:** `go_info or grafana_info`
**Correct:** `go_info{job="grafana"} or grafana_info{job="grafana"}`
**Incorrect:** `go_info{job="grafana"} or grafana_info`

✅ #14802 **Problem:** Filter added to range vector that is ending with **:**
Query: `avg(rate((my_metric{instance="foo"} > 0)[3h:])) by (device)`
Correct: `avg(rate((my_metric{goversion="go1.13.8",instance="foo"} > 0)[3h:])) by (device)`
Incorrect: `avg(rate((my_metric{goversion="go1.13.8",instance="foo"} > 0)[3h{goversion="go1.13.8"}:])) by (device)`

✅ https://github.com/grafana/grafana/issues/14802 **Problem:** Filter was inserted to the last label, as it considered last label to be metric
**Query:** `max by (org_id, org_name, id, name, type) (grafanacloud_instance_info{type=~"prometheus|graphite|graphite-shared"}) * on(id) group_right(org_id, org_name, type, name) sum by (id) (grafanacloud_instance_created_date) * 1000`
**Correct:** `max by (org_id, org_name, id, name, type) (grafanacloud_instance_info{type=~"prometheus|graphite|graphite-shared", type="prometheus"}) * on(id) group_right(org_id, org_name, type, name) sum by (id) (grafanacloud_instance_created_date{type="prometheus"}) * 1000`
**Incorrect:** `max by (org_id, org_name, id, name, type) (grafanacloud_instance_info{type=~"prometheus|graphite|graphite-shared",type="prometheus"}) * on(id{type="prometheus"}) group_right(org_id, org_name, type, name{type="prometheus"}) sum by (id) (grafanacloud_instance_created_date{type="prometheus"}) * 1000`

✅ https://github.com/grafana/grafana/issues/19008 **Problem:** Filter with broke the simple query with regex
**Query:** `ALERTS{severity=~".*",alertstate=~"firing"}`
**Correct:** `ALERTS{severity=~".*",alertstate=~"firing",alertname!="DeploymentInProgress"}`
**Incorrect:** `ALERTS{severity=~"${alertname!="DeploymentInProgress"}",alertstate=~"${alertname!="DeploymentInProgress"}`

✅ https://github.com/grafana/grafana/issues/19008 **Problem:** Filters get inserted into  **${__range_s}**
**Query:** `sum(rate(http_server_requests_seconds_count{}[${__range_s}s]))`
**Correct:** `query= sum(rate(http_server_requests_seconds_count{status="200", method="GET"}[3600s]))`
**Incorrect:** `query= sum(rate(http_server_requests_seconds_count{status="200", method="GET"}[${status="200", method="GET"}s]))`

✅ https://github.com/grafana/grafana/issues/26029 **Problem:** Filters get inserted into mathematical operations
**Query:** `count(node_filesystem_avail_bytes{fstype!="rootfs",mountpoint="/"} < (5*1024*1024*1024) or vector(0)) - 1`
**Correct:** `count(node_filesystem_avail_bytes{fstype!="rootfs",mountpoint="/",probe!="icmp"} < (5*1024*1024*1024) or vector(0)) - 1`
**Incorrect:** `count(node_filesystem_avail_bytes{fstype!="rootfs",mountpoint="/",probe!="icmp"} < (5{probe!="icmp"}*1024*1024*1024) or vector(0)) - 1`

Fixes #26029
Fixes #19008
Fixes #14802
Fixes #16486
Fixes #29857
Fixes #14556
Fixes #29857

**Special notes for your reviewer**:
In the nest PR, I'll try to tackle these issues, but I need to do some research first on what is desired behaviour:

LABEL_REPLACE: 2. #26526 **Problem:** Filter is inserted to regex
**Query:** `sum by (cluster, nodepool) (label_replace(kube_node_info, "nodepool", "$1", "node", "(.*-.{8})-.*"))`
**Correct:** `sum{cluster="some-12345678-cluster"} by (cluster, nodepool) (label_replace(kube_node_info, "nodepool", "$1", "node", "(.*-.{8})-.*"))`
**Incorrect:** `sum{cluster="some-12345678-cluster"} by (cluster, nodepool) (label_replace(kube_node_info, "nodepool", "$1", "node", "(.*-.{cluster="some-12345678-cluster"})-.*"`

LABEL_REPLACE: 8. #14556 **Problem:** Filters are added to regex and multiple times
**Query:** `sum by (status) (label_replace(label_replace(rate(http_requests_total{}[1m]), "status", "${1}xx", "code", "([0-9]).."), "status", "${1}", "code", "([a-z]+)"))`
**Correct:** `sum by (status) (label_replace(label_replace(rate(http_requests_total{status="4xx"}[1m]), "status", "${1}xx", "code", "([0-9]).."), "status", "${1}", "code", "([a-z]+)"))`
**Incorrect:** `sum by (status) (label_replace(label_replace(rate(http_requests_total{status="4xx"}{status="4xx"}[1m]), "status", "${status="4xx"}xx", "code", "([0-9]).."), "status", "${status="4xx"}", "code", "([a{status="4xx"}-z]+)"))`

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/add_label_to_query.ts [hunk 1]
```diff
@@ -1,10 +1,12 @@
 import _ from 'lodash';
 
-const keywords = 'by|without|on|ignoring|group_left|group_right|bool|or|and|unless';
+const keywords = 'by|without|on|ignoring|group_left|group_right|bool';
+const logicalOperators = 'or|and|unless';
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/prometheus/add_label_to_query.ts:4]: I have split `logicalOperators` from `keywords` as `logicalOperators` are usually between 2 metrics which is different than other keywords.

File: public/app/plugins/datasource/prometheus/add_label_to_query.ts [hunk 2]
```diff
@@ -15,8 +17,12 @@ const builtInWords = [
...
   .split('|');
 
-const metricNameRegexp = /([A-Za-z:][\w:]*)\b(?![\(\]{=!",])/g;
-const selectorRegexp = /{([^{]*)}/g;
+// We want to extract all possible metrics and also keywords
+const metricsAndKeywordsRegexp = /([A-Za-z:][\w:]*)\b(?![\]{=!",])/g;
+// Safari currently doesn't support negative lookbehind. When it does, we should refactor this.
+// We are creating 2 matching groups. (\$) is for the Grafana's variables such as ${__rate_s}. We want to ignore
+// ${__rate_s} and not add variable to it.
+const selectorRegexp = /(\$)?{([^{]*)}/g;
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/prometheus/add_label_to_query.ts:25]: This could be solved with negative lookbehind `(?<!\$){([^{]*)}` and we would receive only selectors that don't start with `$`. Unfortunately Safari doesn't support that https://caniuse.com/?search=lookbehind :( . I have followed this https://stackoverflow.com/questions/35142364/regex-negative-lookbehind-not-valid-in-javascript as a way how you can implement global negative-lookbehind behaviour.

File: public/app/plugins/datasource/prometheus/add_label_to_query.ts [hunk 3]
```diff
@@ -34,29 +40,12 @@ export function addLabelToQuery(
 
   // Add empty selectors to bare metric names
   let previousWord: string;
-  query = query.replace(metricNameRegexp, (match, word, offset) => {
-    const insideSelector = isPositionInsideChars(query, offset, '{', '}');
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/prometheus/add_label_to_query.ts:38]: Moved this to separate function `isWordMetric`.

File: public/app/plugins/datasource/prometheus/add_label_to_query.ts [hunk 4]
```diff
@@ -67,11 +56,19 @@ export function addLabelToQuery(
...
   while (match) {
     const prefix = query.slice(lastIndex, match.index);
-    const selector = match[1];
-    const selectorWithLabel = addLabelToSelector(selector, key, transformedValue, operator);
-    lastIndex = match.index + match[1].length + 2;
+    lastIndex = match.index + match[2].length + 2;
     suffix = query.slice(match.index + match[0].length);
-    parts.push(prefix, selectorWithLabel);
+    // If we matched 1st group, we know it is Grafana's variable and we don't want to add labels
+    if (match[1]) {
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/prometheus/add_label_to_query.ts:62]: This is unfortunately necessary because of negative lookbehind not being supported in safari.

**Review by zoltanbedi — APPROVED** [review]
This is some crazy work right here! 💣

**Comment by davkal** [comment]
Good work, indeed! 🎉
