### PR TITLE
CloudMonitoring: Correctly interpolate multi-valued template variables in PromQL queries

### LINKED ISSUE #78619: Google Cloud Monitoring Multivalue variables not working in PromQL Queries
### What happened?

When I create a variable that allows multiple selections and attempt to include it in a PromQL query such as foo{label~="$values"} it becomes:

foo{label~="{bar,baz}"}

This is not valid PromQL and the query returns empty.

The correct way would be to use foo{label~="bar|baz"} but I have no idea how to instruct the plugin to construct this type of multivalue representation.

### What did you expect to happen?

Multivalue labels to work correctly

### Did this work before?

No

### How do we reproduce it?

1. Create Multivalue Variable based on GCP's Monitoring Label Values equivalent
2. Create Query using multivalue variable
3. Observe blank graph

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Google Cloud Monitoring 1.0.0

### PR DESCRIPTION
**Pull request by aangelisc**
Filters in PromQL should be joined using the `|` operator rather than a `,`. This PR adds support for specifying a function that will be used for formatting for each property in a query. I've only included a custom formatted for the `expr` property in the `promQlQuery` type.

The default now is to join any multi-valued variables using a pipe, otherwise the value will be returned as is.

To test this:

- Create a template variable called `labelValues` (ideally use the label values query variable). Enable the `multi` option.
- Run the following query against the `Compute` service on the default project: `compute_googleapis_com:instance_cpu_utilization{instance_name=~"$labelValues"}`

The query should succeed with these changes when you select multiple values for the variable.

Fixes #78619

### CODE REVIEW

File: public/app/plugins/datasource/cloud-monitoring/datasource.ts [hunk 1]
```diff
@@ -294,11 +295,31 @@ export default class CloudMonitoringDatasource extends DataSourceWithBackend<
...
+  }
+
+  interpolateProps<T extends Record<string, any>>(
+    object: T,
+    scopedVars: ScopedVars = {},
+    formattingFunctions?: { [key: string]: Function | undefined }
+  ): T {
     return Object.entries(object).reduce((acc, [key, value]) => {
+      let interpolatedValue = value;
+      if (interpolatedValue && isString(value)) {
```
Comment (bossinc) [inline public/app/plugins/datasource/cloud-monitoring/datasource.ts:312]:
```suggestion
      if (value && isString(value)) {
```
We should use the same var for clarity. Either `value` or `interpolatedValue`

**Review by bossinc — APPROVED** [review]
It works great!

File: public/app/plugins/datasource/cloud-monitoring/datasource.ts (hunk 1 above)
Comment (aangelisc) [reply public/app/plugins/datasource/cloud-monitoring/datasource.ts:312]: Nice catch 😊
