### PR TITLE
Alerting: Improve Contact Points error handling

### LINKED ISSUE #44238: Specific error message not displayed when testing Slack contact point configuration
**What happened**:

I created a new Slack contact point and did not include the required `recipient` field. After testing the notification, the error toast only showed the base message for a 400 - "Bad Request," but did not tell me the specific error. As there were multiple configuration errors, it was difficult to tell how to troubleshoot the error.

Upon opening the network stack I noticed the specific error message was returned from the backend, under `receivers[0].grafana_managed_receiver_configs[0].error`.

The key difference appears to be here: https://github.com/grafana/grafana/blob/61974383d7ca2a66fd2962375c60046e407d0e71/pkg/services/ngalert/notifier/receivers.go#L153-L155

If an error is produced while building a notifier (as opposed to actually calling Notify), we return an error rather than a failed test result. If instead we return a failed test result, the test errors will be returned and parsed in a consistent way.

**What you expected to happen**:

The error toast tells me that my recipient was missing.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new contact point of Slack type.
2. Configure a token/etc, but leave the Recipient field blank.
3. Test the contact point. -> Bad Request.

### PR DESCRIPTION
**Pull request by konrad147**
**What this PR does / why we need it**:
This PR improves error handling when testing contact points. This gives us the ability to display a specific error message instead of a generic error.

**Which issue(s) this PR fixes**:
Fixes #44238

### CODE REVIEW

File: public/app/features/alerting/unified/api/alertmanager.ts [hunk 1]
```diff
@@ -171,28 +171,52 @@ export async function testReceivers(
...
+        throw new Error(getReceiverResultError(error.data));
+      }
+    }
+
+    throw error;
+  }
+}
+
+function isTestReceiversResult(data: any): data is TestReceiversResult {
+  if (typeof data.receivers === 'object' && Array.isArray(data.receivers)) {
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/api/alertmanager.ts:202]: `Array.isArray(data.receivers)` should be sufficient here, since that implies `typeof object`

File: public/app/features/alerting/unified/api/alertmanager.ts [hunk 2]
```diff
@@ -171,28 +171,52 @@ export async function testReceivers(
...
-    throw new Error(
-      result.data.receivers
-        .flatMap((receiver) =>
-          receiver.grafana_managed_receiver_configs
-            .filter((receiver) => receiver.status === 'failed')
-            .map((receiver) => receiver.error ?? 'Unknown error.')
-        )
-        .join('; ')
+    // api returns 207 if one or more receivers has failed test. Collect errors in this case
+    if (result.status === 207) {
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/api/alertmanager.ts:186]: I think we can simplify a large part of this by checking for any errors in the response regardless of what the status code was.

Something like

```javascript
function receiversResponseContainsErrors(result: TestReceiversResult) {
  return result.receivers.some((receiver) =>
    receiver.grafana_managed_receiver_configs.some((config) => Boolean(config.error))
  );
}
```

should work for both `result.data` and `error.data`

**Review by gillesdemey — APPROVED** [review]
Looks good, comments are not blockers

File: public/app/features/alerting/unified/api/alertmanager.ts (hunk 2 above)
Comment (konrad147) [reply public/app/features/alerting/unified/api/alertmanager.ts]: I adjusted the code. The only concern I have is about the shape of the `error.data` but the `isTestReceiverResult` type guard should be enough to handle that properly

**Comment by gillesdemey** [comment]
LGTM! :shipit:
