### PR TITLE
Azure Monitor: Bug fix for variable interpolations in metrics dropdowns

### LINKED ISSUE #42746: Upgrading to Grafana 8.3 broke variable interpolations with Azure Monitor
After upgrading from Grafana 8.2.5 to 8.3, dashboards using Azure Monitor lost their parameters that have variables in them.

Here is a basic exemple : 
When modifying a panel that uses variables, the fields are empty.

**What you expected to happen**:
It was expected to have the same resource names that were there before, based on the variables that are set.
In our case, we expected to have those values filled in : 

**How to reproduce it (as minimally and precisely as possible)**:
- On Grafana 8.2.5, have a panel using Azure Monitor, with fields based on variables
- Upgrade to Grafana 8.3
- Edit the panel. The fields using variables are empty. They should be filled

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Official docker image
- User OS & Browser: Any
- Grafana plugins: None
- Others:

### PR DESCRIPTION
**Pull request by sarahzinger**
**What this PR does / why we need it**:
In approximately 8.2 we started clearing dropdown fields in Azure Monitor Metrics if the selected value was not a valid option. This was done to make it a smoother UX experience as we felt it was somewhat confusing to edit one field that invalidated the other fields, and yet we kept the old fields. We would request for a list of valid options for the select, and if the selected option was not one of those options on a template variable, then we would clear the selection.

Unfortunately, we mistakenly then broke dashboards for users who had a selection in the dropdown that was not a template variable but used a template variable such as `resource-group-$TEMPLATE_VARIABLE_NAME`. This was easy to miss because it's not really supported by our UI, but it is a feature that is possible to do by importing a json file or manually editing/saving the json directly. 

This pr removes the clear functionality for invalid selections and instead will rely on errored out queries to prompt users to fix their selection.

**Which issue(s) this PR fixes**: 

Fixes #42746

**Special notes for your reviewer**:

Initially I explored doing better validation and keeping the clear functionality, such as verifying that the resource group a user has created with a template variable interpolates correctly, but it occurred to me that if a user mistypes a resource/metric it'll be very difficult to debug if it just automatically clears. I think better to see the failures directly.

An easy way to test this is with the App Insights curated dashboard. In that you'll notice that you can see everything fine until you try to edit a panel, at which point you'll notice the query fails because the dropdowns reset. With this pr you'll notice the data loads properly in edit panels.

### CODE REVIEW

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/dataHooks.ts [hunk 1]
```diff
@@ -297,6 +277,19 @@ export const useMetricMetadata = (query: AzureMonitorQuery, datasource: Datasour
...
 };
 
-function isInvalidOption(value: string | undefined, options: AzureMonitorOption[], templateVariables: string[]) {
-  return value && !templateVariables.includes(value) && !hasOption(options, value);
+function formatOptions(
+  rawResults: Array<{
+    text: string;
+    value: string;
+  }>,
+  selectedValue: string | undefined
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/dataHooks.ts:285]:
```suggestion
  selectedValue?: string
```

**Review by andresmgot — APPROVED** [review]
I agree with not removing custom options. LGTM!

**Comment by andresmgot** [comment]
> This was easy to miss because it's not really supported by our UI, but it is a feature that is possible to do by importing a json file or manually editing/saving the json directly.

I think this is something that was supported before? I don't think people were manually modifying the JSON for that. Maybe we can check that with the user reporting the issue. IMO we can just allow to set custom values in the dropdowns. That will help in case we are missing a metric namespace in our list or for resources that we are not able to retrieve (e.g. china cloud). For example: https://github.com/grafana/grafana/issues/37435 WDYT?

**Review by andresmgot — APPROVED** [review]
:+1:
