### PR TITLE
OrgSwitcher: Fixed issue rendering org switcher even when it's not open

### LINKED ISSUE #21060: Login page incorrectly tries to fetch /api/user/orgs and results in unauthorized message
**What happened**:
Got unauthorized message when browsing the login page.

image

**What you expected to happen**:
No unauthorized message.

**How to reproduce it (as minimally and precisely as possible)**:
Browse the login page unauthorized.

**Anything else we need to know?**:
Unauthorized comes from something trying to fetch /api/user/orgs. 
Seems to be a problem in master only.

**Environment**:
- Grafana version: master

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #21060

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM Works as expected to login and switching orgs

File: public/app/core/components/sidemenu/BottomNavLinks.tsx [hunk 1]
```diff
@@ -67,7 +67,7 @@ class BottomNavLinks extends PureComponent<Props, State> {
             </li>
           )}
 
-          <OrgSwitcher onDismiss={this.toggleSwitcherModal} isOpen={showSwitcherModal} />
+          {showSwitcherModal && <OrgSwitcher onDismiss={this.toggleSwitcherModal} />}
```
Comment (dprokop) [inline public/app/core/components/sidemenu/BottomNavLinks.tsx]: Thanks for this @torkelo ! I consider this a more elegant way of toggling visibility when no animation is required.

**Review by dprokop — APPROVED** [review]
