### PR TITLE
Datasource/Loki: Fixes regression where enhanceDataFrame was not called

### LINKED ISSUE #20642: Loki: Derived fields does not work in master
**What happened**:

Seems like a regression after merging the metrics queries for Loki

**What you expected to happen**:

The [enhanceDataFrame method](https://github.com/grafana/grafana/blob/c6a9a83bf3d69855b4126ac5afc9321398e95ac4/public/app/plugins/datasource/loki/datasource.ts#L613), which adds the derived fields to the dataframe is not called in branch for the new API.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: master
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Fixes a regression introduced when adding metrics support to the Loki datasource where enhanceDataFrame was not called for the new endpoints.

**Which issue(s) this PR fixes**:
Closes #20642

### CODE REVIEW

File: public/app/plugins/datasource/loki/result_transformer.ts [hunk 1]
```diff
@@ -319,28 +327,80 @@ export function lokiLegacyStreamsToDataframes(
...
 
   return series;
 }
 
+/**
+ * Adds new fields and DataLinks to DataFrame based on DataSource instance config.
+ * @param dataFrame
+ */
+export function enhanceDataFrame(dataFrame: DataFrame, config: LokiOptions): void {
+  if (!config) {
```
Comment (aocenas) [inline public/app/plugins/datasource/loki/result_transformer.ts]: Should we make config explicitly optional or `LokiOptions  | null`?

File: public/app/plugins/datasource/loki/result_transformer.ts [hunk 2]
```diff
@@ -301,16 +304,21 @@ export function lokiStreamsToDataframes(
...
-    ...lokiStreamResultToDataFrame(stream, reverse),
-    refId: target.refId,
-    meta: {
-      searchWords: getHighlighterExpressionsFromQuery(formatQuery(target.expr, target.regexp)),
-      limit,
-    },
-  }));
+  const series: DataFrame[] = data.map(stream => {
+    const dataFrame = lokiStreamResultToDataFrame(stream, reverse);
+    enhanceDataFrame(dataFrame, config);
```
Comment (aocenas) [inline public/app/plugins/datasource/loki/result_transformer.ts]: This does not seem the work, though the `dataFrame ` is enhanced with the derived fields it is not actually used afterwards as `lokiStreamResultToDataFrame` creates a new dataFrame.

**Review by aocenas — CHANGES_REQUESTED** [review]

**Comment by aocenas** [comment]
Also this is on me that I forget to create create the tests which could have caught this regression but as we are already, here could you add a test for this in this PR?

File: public/app/plugins/datasource/loki/result_transformer.ts (hunk 2 above)
Comment (kaydelaney) [reply public/app/plugins/datasource/loki/result_transformer.ts]: my mistake, forgot to replace `lokiStreamResultToDataFrame` with `dataFrame` in the next line 😛

File: public/app/plugins/datasource/loki/result_transformer.ts [hunk 3]
```diff
@@ -301,16 +304,21 @@ export function lokiStreamsToDataframes(
...
+    return {
+      ...lokiStreamResultToDataFrame(stream, reverse),
```
Comment (kaydelaney) [inline public/app/plugins/datasource/loki/result_transformer.ts]:
```suggestion
      ...dataFrame(stream, reverse),
```

File: public/app/plugins/datasource/loki/result_transformer.ts [hunk 4]
```diff
@@ -301,16 +304,21 @@ export function lokiStreamsToDataframes(
...
-    meta: {
-      searchWords: getHighlighterExpressionsFromQuery(formatQuery(target.expr, target.regexp)),
-      limit,
-    },
-  }));
+  const series: DataFrame[] = data.map(stream => {
+    const dataFrame = lokiStreamResultToDataFrame(stream, reverse);
+    enhanceDataFrame(dataFrame, config);
+    return {
+      ...dataFrame(stream, reverse),
```
Comment (kaydelaney) [inline public/app/plugins/datasource/loki/result_transformer.ts]:
```suggestion
      ...dataFrame,
```

**Review by aocenas — COMMENTED** [review]
Nice, works fine now.

File: public/app/plugins/datasource/loki/result_transformer.test.ts [hunk 5]
```diff
@@ -23,35 +23,91 @@ const streams: LokiLegacyStreamResult[] = [
...
-
-    appendLegacyResponseToBufferedData({ streams }, data);
-    expect(data.get(0)).toEqual({
-      ts: '1970-01-01T00:00:00Z',
-      line: "foo: [32m'bar'[39m",
-      labels: { foo: 'bar' },
-      id: '1970-01-01T00:00:00Z_{foo="bar"}',
+  describe('lokiLegacyStreamsToDataframes', () => {
+    it('should enhance data frames', () => {
+      jest.spyOn(ResultTransformer, 'enhanceDataFrame');
```
Comment (aocenas) [inline public/app/plugins/datasource/loki/result_transformer.test.ts]: Can we instead of checking if the specific function was called, check if the result of the transformation is correct if the derived fields are part of the config? We can basically reuse the existing tests and just add the config and then check if there is the new column in the dataframe with the datalinks.

Something like:
```
{derivedFields: [
{
  matcherRegex: 'trace=(\w+)',
  name: 'test',
  url: 'example.com'
}
]}
```
Should work for the config and should create new column with the name `test` in the resulting dataframe.

Comment (kaydelaney) [reply public/app/plugins/datasource/loki/result_transformer.test.ts]: Sure, will look at this now

**Review by aocenas — APPROVED** [review]
Nice work 👍
