### PR TITLE
Datasource: Fix allowed cookies to be forwarded as header to backend datasources

### LINKED ISSUE #44250: [grafana 8.3.x][prometheus] Allowed cookies not forwarded to the datasource
**What happened**:
Starting with grafana 8.3.0, the following configuration doesn't work anymore.
Capture d’écran du 2022-01-19 17-18-25
we expose with a public address the grafana server and the prometheus server, both are behind a oauth2-proxy instance which set a `_oauth2_proxy` cookie.
It seems that the cookie specified (`_oauth2_proxy`) in the `Allowed cookies` section is no longer passed to the the prometheus datasource, this mean that the datasource can't be fetched by the grafana server (unauthorized)
With grafana 8.2.7, the cookie was well passed to the datasource and grafana was able to fetch prometheus
To be able to have a functionnal setup, we need to hardcode the cookie header using the `Custom HTTP Headers` section

**What you expected to happen**:
Forwarding the `_oauth2_proxy` cookie to the server to be able to query the datasource

**How to reproduce it (as minimally and precisely as possible)**:
- Set a prometheus server behind a proxy using a cookie header for the authentication
- fix the name of the cookie to `_oauth2_proxy`
- Install a grafana 8.2.7 server using the prometheus datasource
- Add the `_oauth2_proxy`cookie in the `Allowed cookies` section
- Test the connection to the datasource (using the `save and test` button)
- Upgrade the grafana server to 8.3.0 
- Test the connection to the datasource (using the `save and test` button)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.x
- Data source type & version: prometheus
- OS Grafana is installed on: docker image
- User OS & Browser: firefox/chrome
- Grafana plugins: None
- Others:

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Populates `Cookie` header in `QueryDataRequest.Headers` given _Allowed cookies_ (`jsonData.keepCookies`) is configured for a datasource.

**Which issue(s) this PR fixes**:
Fixes #44250 

**Special notes for your reviewer**:
- Seems like it should work out of the box for Prometheus, but need to test/verify

### CODE REVIEW

File: pkg/services/query/query.go [hunk 1]
```diff
@@ -149,6 +151,19 @@ func (s *Service) handleQueryData(ctx context.Context, user *models.SignedInUser
 		req.Headers[k] = v
 	}
 
+	if parsedReq.httpRequest != nil && parsedReq.httpRequest.Header.Get("Cookie") != "" && ds.JsonData != nil {
```
Comment (wbrowne) [inline pkg/services/query/query.go:154]: I wonder is now a good opportunity to refactor so that resource, query and proxy calls both use the same code?

Comment (marefr) [reply pkg/services/query/query.go:154]: Good question. They are different though, not sure how easy that would be. Do you have an idea?

File: pkg/services/query/query.go [hunk 2]
```diff
@@ -149,6 +151,19 @@ func (s *Service) handleQueryData(ctx context.Context, user *models.SignedInUser
...
+		keepCookieNames := []string{}
+
+		if keepCookies := ds.JsonData.Get("keepCookies"); keepCookies != nil {
```
Comment (ryantxu) [inline pkg/services/query/query.go:157]: This seems like a kinda big feature to stick on the untyped jsonData

Where is this used?  Is it something that is really set explicitly from the UI?  It seems more like a setting attached to the whole plugin than something that would selectively apply to some instances

Comment (marefr) [reply pkg/services/query/query.go:157]: It's an oldie part of the datasource HTTP settings for years: https://github.com/grafana/grafana/blob/8fa8c9dc8b6922110d154705b9d822bb5319819d/packages/grafana-ui/src/components/DataSourceSettings/DataSourceHttpSettings.tsx#L172-L186

File: pkg/services/query/query_test.go [hunk 3]
```diff
@@ -61,6 +61,43 @@ func TestQueryData(t *testing.T) {
...
+		json, err := simplejson.NewJson([]byte(`{"keepCookies": [ "foo", "bar" ]}`))
+		require.NoError(t, err)
+		tc.dataSourceCache.ds.JsonData = json
+
+		metricReq := metricRequest()
+		httpReq, err := http.NewRequest(http.MethodGet, "/", nil)
+		require.NoError(t, err)
+		metricReq.HTTPRequest = httpReq
+		_, err = tc.queryService.QueryData(context.Background(), nil, true, metricReq, false)
+		require.Nil(t, err)
```
Comment (wbrowne) [inline pkg/services/query/query_test.go:76]:
```suggestion
		require.NoError(t, err)
```

File: pkg/services/query/query_test.go [hunk 4]
```diff
@@ -61,6 +61,43 @@ func TestQueryData(t *testing.T) {
...
+		httpReq, err := http.NewRequest(http.MethodGet, "/", nil)
+		require.NoError(t, err)
+		httpReq.AddCookie(&http.Cookie{Name: "a"})
+		httpReq.AddCookie(&http.Cookie{Name: "bar", Value: "rab"})
+		httpReq.AddCookie(&http.Cookie{Name: "b"})
+		httpReq.AddCookie(&http.Cookie{Name: "foo", Value: "oof"})
+		httpReq.AddCookie(&http.Cookie{Name: "c"})
+		metricReq.HTTPRequest = httpReq
+		_, err = tc.queryService.QueryData(context.Background(), nil, true, metricReq, false)
+		require.Nil(t, err)
```
Comment (wbrowne) [inline pkg/services/query/query_test.go:97]:
```suggestion
		require.NoError(t, err)
```

**Review by wbrowne — APPROVED** [review]
LGTM
