### PR TITLE
Provisioning: Fix overwrite SecureJSONData on provisioning

### LINKED ISSUE #70035: Provisioning: SecureJSONData in datasource does not null empty fields on update
### 
# What went wrong?

**What happened**:

  - As part of rollout of grafana enterprise, we updated the default datasource to use basicAuth instead of TLS Certificate auth. This involved removing the keys tlsClientCert and tlsClientKey from the secureJSONData field of the datasource in our datasources.yaml.
  - When the TLS certificate expired, the datasource broke, requiring us to delete and recreate it to recover service.

**What did you expect to happen**:

  - We expected the database representation of the datasource to have the tlsClientCert and tlsClientKey fields deleted when they were deleted from the config file.

### 
# How do we reproduce it?

**Step 1**:

- Create a datasource using datasources.yaml. set a key in the secureJsonData field. 

**Step 2**:

- Note in the database that the field is now set - eg `SELECT secure_json_data FROM "data_source" WHERE name='mimir';` will show the key exists.

**Step 3**:

- Delete the key from secureJsonData in datasources.yaml and apply the config file. Note that the secureJsonData continues to contain the affected field.

### 
# What Grafana version are you using?

v9.5.3

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

We can work around by deleting the datasource and allowing recreation for now.

### PR DESCRIPTION
**Pull request by oshirohugo**
**What is this feature?**

Overwrite existing `SecureJSONData` when this is provided on provisioning

**Why do we need this feature?**

This is necessary to avoid that old `SecureJSONData` stays in the database when `SecureJSONData` is provide on provisioning.

**Who is this feature for?**

Data source provisioning users

**Which issue(s) does this PR fix?**:

Fixes #70035

**Special notes for your reviewer:**

This was happening due to this fix https://github.com/grafana/grafana/pull/48557 to solve https://github.com/grafana/grafana/issues/48525.
In this PR we keep the merge behavior for the API and do the overwrite in the provisioning

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by mildwonkey — APPROVED** [review]
👋 I tested this out locally and everything LGTM!

File: pkg/services/datasources/service/datasource_test.go [hunk 1]
```diff
@@ -187,6 +187,93 @@ func TestService_UpdateDataSource(t *testing.T) {
...
+				expectedOgKey: expectedOgValue,
+			},
+		}
+
+		_, err = dsService.UpdateDataSource(context.Background(), cmd)
+
+		assert.Equal(t, cmd.SecureJsonData[expectedDbKey], expectedDbValue)
+		assert.Equal(t, cmd.SecureJsonData[expectedOgKey], expectedOgValue)
+
+		require.NoError(t, err)
```
Comment (andresmgot) [inline pkg/services/datasources/service/datasource_test.go:230]: nit: usually it's better to check the error just after the function call so you don't get weird errors first

File: pkg/services/datasources/models.go [hunk 2]
```diff
@@ -134,6 +134,7 @@ type UpdateDataSourceCommand struct {
 	ReadOnly                bool              `json:"-"`
 	EncryptedSecureJsonData map[string][]byte `json:"-"`
 	UpdateSecretFn          UpdateSecretFn    `json:"-"`
+	SecureJsonOverwrite     bool              `json:"-"`
```
Comment (andresmgot) [inline pkg/services/datasources/models.go:137]: Suggestion: `IgnoreOldSecureJsonData`? If I set `SecureJsonOverwrite: false` it could mean that a new password (for example) wouldn't overwrite the current one, not that it deletes unset params.

Feel free to keep the naming you think is best though :+1:

**Review by andresmgot — APPROVED** [review]
LGTM! only minor comments here

File: pkg/services/datasources/service/datasource_test.go [hunk 3]
```diff
@@ -187,6 +187,92 @@ func TestService_UpdateDataSource(t *testing.T) {
...
+			SecureJsonData: map[string]string{
+				expectedOgKey: expectedOgValue,
+			},
+		}
+
+		_, err = dsService.UpdateDataSource(context.Background(), cmd)
+		require.NoError(t, err)
+
+		assert.Equal(t, cmd.SecureJsonData[expectedDbKey], expectedDbValue)
+		assert.Equal(t, cmd.SecureJsonData[expectedOgKey], expectedOgValue)
```
Comment (xnyo) [inline pkg/services/datasources/service/datasource_test.go:229]: I am confused by those assertions, which are run on `cmd` which is the `UpdateDataSourceCommand` (so the input).

 Shouldn't they be like this:

```suggestion
		ds, err = dsService.UpdateDataSource(context.Background(), cmd)
		require.NoError(t, err)

		secret, err := dsService.DecryptedValues(context.Background(), ds)
		require.NoError(t, err)

		assert.Equal(t, secret[expectedDbKey], expectedDbValue)
		assert.Equal(t, secret[expectedOgKey], expectedOgValue)
```

File: pkg/services/datasources/service/datasource_test.go [hunk 4]
```diff
@@ -187,6 +187,92 @@ func TestService_UpdateDataSource(t *testing.T) {
...
+		}
+
+		_, err = dsService.UpdateDataSource(context.Background(), cmd)
+
+		require.NoError(t, err)
+
+		assert.Equal(t, cmd.SecureJsonData[expectedOgKey], expectedOgValue)
+
+		_, ok := cmd.SecureJsonData[notExpectedDbKey]
+		assert.False(t, ok)
```
Comment (xnyo) [inline pkg/services/datasources/service/datasource_test.go:274]: Same here, shouldn't this be:

```suggestion
		ds, err = dsService.UpdateDataSource(context.Background(), cmd)
		require.NoError(t, err)

		secret, err := dsService.DecryptedValues(context.Background(), ds)
		require.NoError(t, err)

		assert.Equal(t, secret[expectedOgKey], expectedOgValue)

		_, ok := secret[notExpectedDbKey]
		assert.False(t, ok)
```

**Review by xnyo — COMMENTED** [review]
Great job! :+1: 
I have a comment on the tests but apart from that it looks good

File: pkg/services/datasources/service/datasource_test.go (hunk 3 above)
Comment (oshirohugo) [reply pkg/services/datasources/service/datasource_test.go:229]: I wanted to test that `fillWithSecureJSONData` was indeed altering the `cmd` and as the `cmd` is a pointer argument these checks are possible in the caller context.
But you are right, checking the `ds` also shows that everything works indirectly, because this is the return from the db update.
I'll to the changes.

Comment (xnyo) [reply pkg/services/datasources/service/datasource_test.go]: Ah yes, makes sense! Thanks for addressing anyways! :raised_hands:

**Review by xnyo — APPROVED** [review]
LGTM! Great work! :rocket:
