### PR TITLE
Fix restoration of ad-hoc variable value issue

### LINKED ISSUE #8056: [BUG] Restoration of ad-hoc variable from URL does not work correctly
- What Grafana version are you using?
  - 4.2.0
- What datasource are you using?
  - Elasticsearch
- What OS are you running grafana on?
  - CentOS 7.1
- What did you do?
  - Set ad-hoc variable which contains "|" in value. for example, `aaa|bbb`
- What was the expected result?
  - Restoration from URL works correctly.
- What happened instead?
  - Restoration from URL does not work correctly. Ad-hoc variable value is set as  `aaa`.
     https://github.com/grafana/grafana/blob/master/public/app/features/templating/adhoc_variable.ts#L52
    is where the wrong code exists. Key, operator and value are joined and splitted by `|`.
   But when we have value which contains `|`, splitted values count is more than 3, so chars after `|` are ignored.

I'm making PR.

### PR DESCRIPTION
**Pull request by tamayika**
Closes #8056

### CODE REVIEW

File: public/app/features/templating/adhoc_variable.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ export class AdhocVariable implements Variable {
       return {
         key: values[0],
         operator: values[1],
-        value: values[2],
+        value: values.slice(2).join('|'),
```
Comment (torkelo) [inline public/app/features/templating/adhoc_variable.ts]: would it not be better to escape the | if it's used in the value?

Comment (tamayika) [inline public/app/features/templating/adhoc_variable.ts]: How do you escape/unescape delimiter `|` with compatibility?
If we use encode/decodeURIComponent, `|` becomes `%7C`.
But if someone is using ad-hoc variable value=`%7C`, it will be decoded to `|` unexpectedly.
Is this OK?

Comment (torkelo) [inline public/app/features/templating/adhoc_variable.ts]: I was thinking more along the lines of replacing | with a custom sequence, "__gfpipe" or something similar

Comment (tamayika) [inline public/app/features/templating/adhoc_variable.ts]: OK, I will change PR.

**Comment by tamayika** [comment]
Now, we escape/unescape delimiters in all parameters of ad-hoc variable.
