### PR TITLE
TimeSeries: Sort tooltip values based on raw values

### LINKED ISSUE #45292: confused to Tooltip values sort
**What happened**:
when specify tooltip option `Values sort order`, the final display is sort by formatted value, i'm confused
 that why not sort by raw value.

for example this:
8xbmBITuvb

See the implementation code: https://github.dev/grafana/grafana/blob/fed112ef3bd699ece8e6a66c3b012dc6fbb0ee0f/packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx#L246

**What you expected to happen**:
In the example above, **backend_01**'s raw value smaller than **backend_02**'s raw value but look like bigger than **backend_02** in display.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I also found that we use `Intl.Collator` for sort compareFunction, when specify `numeric: true`, it would not get the same result if use native sort compareFunction in comparing decimals. e.g.  
```js
[0.1, 0.21, 0.3].sort((a, b) => new Intl.Collator(undefined, {numeric: true, sensitivity: 'base'}).compare(a, b)) // [0.1, 0.3, 0.21]
```
Intl.Collator issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1312388
Related Conversation: https://github.com/grafana/grafana/pull/43615

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### LINKED ISSUE #46096: Tooltip and sort order
Hello,

Tooltip for timeseries is not sorting correctly if values are as short Unit in thousands - Used descending

image

**Environment**:
- Grafana version: 8.4.2
- Data source type & version: SQL Server
- OS Grafana is installed on: Debian 11
- User OS & Browser: Windows  - Edge
- Grafana plugins: Default - TimeSeries

### LINKED ISSUE #46712: Tooltip : Adding Units can break `Ascending` and `Descending` sorting
**What happened**:

See [this community post](https://community.grafana.com/t/sorting-tooltip/61442/3) for more background.

Adding variable units to values can break[ the new tooltip sort function](https://github.com/grafana/grafana/pull/43615). Here is a sample dashboard:

https://play.grafana.org/d/lWHJxoE7k/tooltip-sorting-test?orgId=1
 
CleanShot 2022-03-17 at 10 48 21@2x

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

[Visit this dashboard](https://play.grafana.org/d/lWHJxoE7k/tooltip-sorting-test?orgId=1) and inspect the the tooltip while changing the tooltip sort value between `Ascending`, `Descending`, and `None`. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.3
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by dprokop**
Fixes https://github.com/grafana/grafana/issues/45292
Fixes https://github.com/grafana/grafana/issues/46712
Fixes https://github.com/grafana/grafana/issues/46096

Bringing back sorting based on raw values rather than display values.

### CODE REVIEW

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx [hunk 1]
```diff
@@ -242,7 +242,14 @@ export const TooltipPlugin: React.FC<TooltipPluginProps> = ({
...
 
       if (sortOrder !== SortOrder.None) {
-        series.sort((a, b) => arrayUtils.sortValues(sortOrder)(a.value, b.value));
+        // create sort reference series array, as Array.sort() mutates the original array
+        const sortRef = [...series];
+        series.sort((a, b) => {
+          // get compared values indices to retrivie raw values from sortIdx
+          const aIdx = sortRef.indexOf(a);
+          const bIdx = sortRef.indexOf(b);
+          return arrayUtils.sortValues(sortOrder)(sortIdx[aIdx], sortIdx[bIdx]);
```
Comment (leeoniya) [inline packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx:251]: can we pull `arrayUtils.sortValues(sortOrder)` up out of this callback?

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx [hunk 2]
```diff
@@ -242,7 +242,14 @@ export const TooltipPlugin: React.FC<TooltipPluginProps> = ({
       }
 
       if (sortOrder !== SortOrder.None) {
-        series.sort((a, b) => arrayUtils.sortValues(sortOrder)(a.value, b.value));
+        // create sort reference series array, as Array.sort() mutates the original array
+        const sortRef = [...series];
+        series.sort((a, b) => {
+          // get compared values indices to retrivie raw values from sortIdx
```
Comment (zoltanbedi) [inline packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx:248]:
```suggestion
          // get compared values indices to retrieve raw values from sortIdx
```

**Review by zoltanbedi — APPROVED** [review]
Works as expected now!

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx (hunk 1 above)
Comment (dprokop) [reply packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx]: sure, that's fixed now
