### PR TITLE
Auth: Fix token refresh when using Entra ID OAuth with workload_identity (federated credentials)

### LINKED ISSUE #3039: Grafana with client assertion doesnt support refresh tokens
Grafana will logg out users after about 1 hour because refreshing the token fails.

Grafana issue: 
https://github.com/grafana/grafana/issues/98919

Golang SDK:
https://github.com/golang/go/issues/73431
https://github.com/golang/oauth2/issues/744 / https://github.com/golang/oauth2/pull/745

Identical issue as ouath2-proxy:
https://github.com/oauth2-proxy/oauth2-proxy/pull/3031

### LINKED ISSUE #98919: OAuth: Token Refresh Fails for Azure AD Managed Identity Authentication in Grafana
### What happened?

When using Azure AD with the managed identity authentication method in Grafana, the [`Exchange`](https://github.com/golang/oauth2/blob/49a531d12a9ad6fa9f5a070d577ac752ada772c9/oauth2.go#L223) method in [golang/oauth2](https://github.com/golang/oauth2) package allows passing additional [`AuthCodeOption`s](https://github.com/grafana/grafana/blob/6883a4b294cccbd9fa8034dc82bb857af7d4aed2/pkg/login/social/connectors/azuread_oauth.go#L194C3-L194C13) to include client assertion parameters required for the managed identity flow. This enables successful authentication during the initial login. However, the [`TokenSource`](https://github.com/golang/oauth2/blob/49a531d12a9ad6fa9f5a070d577ac752ada772c9/oauth2.go#L249C18-L249C29) method, which is responsible for refreshing tokens, does not support passing these additional authorization code options. As a result, token refreshes fail because the necessary client assertion parameters are not included in the refresh request.

This bug disrupts long-running sessions and automated workflows requiring continuous authentication.

**Proposed Solution:**

Update the TokenSource implementation in golang/oauth2 package to accept and utilize additional `AuthCodeOption`s during token refreshes, ensuring consistency with the Exchange method and enabling the managed identity flow for all stages of authentication.

This change will ensure that users leveraging Azure AD managed identity can maintain active sessions without interruption.

This bug is related to the initial addition of a new authentication method for Azure AD in [this](https://github.com/grafana/grafana/pull/95455) PR.

### What did you expect to happen?

The token refresh process should succeed by including the necessary AuthCodeOption(e.g., client_assertion and client_assertion_type) in the token refresh request.

### Did this work before?

No

### How do we reproduce it?

**Steps to Reproduce:**

1. Configure Azure AD in Grafana with the managed identity authentication.
2. Log in to Grafana, triggering the Exchange method to authenticate using client assertion parameters.
3. Allow the token to expire or trigger a token refresh.
4. Observe that the token refresh fails due to missing client assertion parameters.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

N/A

### Grafana platform?

Docker

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by Richard87**
**What is this feature?**

Fixes a bug with the new AzureAD SSO using `workload_identity`. This upgrades Grafana to use `client_assertion` when refreshing the token.

This code should be upgraded in the future if Go adds support

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/98919
Fixes https://github.com/grafana/grafana/issues/112509
Fixes https://github.com/equinor/radix-flux/issues/3039

**Special notes for your reviewer:**

It would be way better with native support from Golang (https://github.com/golang/oauth2/issues/744), this is a hotfix identical to the PR merged in oauth2proxy (https://github.com/oauth2-proxy/oauth2-proxy/pull/3031)

Please check that:
- [x] It works as expected from a user's perspective.
  - [x] Running correct in our dev-environment
  - [x] Running correct in alll our prod-environment
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

This PR/Fork is currently running correctly in all our dev and production clusters

Azure AD config this is run with:
```toml
[auth.azuread]
name = Microsoft
icon = microsoft
enabled = true
allow_sign_up = true
auto_login = false
client_authentication = workload_identity
client_id = f545deb5-f721-4d20-87cd-b046b5119d70
client_secret =
managed_identity_client_id =
federated_credential_audience = api://AzureADTokenExchange
workload_identity_token_file = ./.tmp/grafana.jwt
scopes = openid email profile
auth_url = https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/oauth2/v2.0/token
signout_redirect_url =
allowed_domains =
allowed_groups =
allowed_organizations = 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
role_attribute_strict = false
org_mapping =
allow_assign_grafana_admin = false
force_use_graph_api = false
tls_skip_verify_insecure = false
tls_client_cert =
tls_client_key =
tls_client_ca =
use_pkce = true
skip_org_role_sync = false
use_refresh_token = true
```

### CODE REVIEW

File: pkg/login/social/connectors/azuread_oauth.go [hunk 1]
```diff
@@ -215,30 +218,121 @@ func (s *SocialAzureAD) Exchange(ctx context.Context, code string, authOptions .
...
+	}
+
+	v := url.Values{}
+	v.Set("client_id", s.clientId)
+	v.Set("grant_type", "refresh_token")
+	v.Set("refresh_token", s.token.RefreshToken)
+	v.Set("client_assertion_type", "urn:ietf:params:oauth:client-assertion-type:jwt-bearer")
+	v.Set("client_assertion", strings.TrimSpace(string(federatedToken)))
+
+	return s.fetchToken(v)
```
[the remark this answers is not in the document]
Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth.go]: the callers caller (`TryTokenRefresh` in `oauth_token.go`) seems to use a lock to avoid race conditions:

```
        ...
	lockErr := o.serverLock.LockExecuteAndReleaseWithRetries(ctx, lockKey, lockTimeConfig, func(ctx context.Context) {
            ...
         })
         ...
```

File: pkg/login/social/connectors/azuread_oauth.go [hunk 2]
```diff
@@ -215,30 +218,121 @@ func (s *SocialAzureAD) Exchange(ctx context.Context, code string, authOptions .
...
+	log.Debug("AzureADToken fetchToken completed")
+	return token.WithExtra(rawResponse), nil
+}
+
 // ManagedIdentityCallback retrieves a token using the managed identity credential of the Azure service.
 func (s *SocialAzureAD) managedIdentityCallback(ctx context.Context) (string, error) {
 	// Validate required fields for Managed Identity authentication
 	if s.info.ManagedIdentityClientID == "" {
-		return "", fmt.Errorf("ManagedIdentityClientID is required for Managed Identity authentication")
+		return "", fmt.Errorf("ManagedIdentityClientID is required for Managed Identity or Workoload Identity authentication")
```
[the remark this answers is not in the document]
Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth.go]: fixed

File: pkg/login/social/connectors/azuread_oauth.go [hunk 3]
```diff
@@ -215,30 +218,121 @@ func (s *SocialAzureAD) Exchange(ctx context.Context, code string, authOptions .
...
 	}
 	if s.info.FederatedCredentialAudience == "" {
-		return "", fmt.Errorf("FederatedCredentialAudience is required for Managed Identity authentication")
+		return "", fmt.Errorf("FederatedCredentialAudience is required for Managed Identity or Workoload Identity authentication")
```
[the remark this answers is not in the document]
Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth.go]: Fixed

File: pkg/login/social/connectors/azuread_oauth_test.go [hunk 4]
```diff
@@ -1445,3 +1447,66 @@ func TestSocialAzureAD_Reload_ExtraFields(t *testing.T) {
...
+		// Verify that client_assertion is present in the request
+		if r.FormValue("client_assertion") != "mock-client-assertion" {
+			t.Errorf("expected client_assertion to be 'mock-client-assertion', got '%s'", r.FormValue("client_assertion"))
+		}
+		if r.FormValue("client_assertion_type") != "urn:ietf:params:oauth:client-assertion-type:jwt-bearer" {
+			t.Errorf("expected client_assertion_type to be 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer', got '%s'", r.FormValue("client_assertion_type"))
+		}
+		if r.FormValue("grant_type") != "refresh_token" {
+			t.Errorf("expected grant_type to be 'refresh_token', got '%s'", r.FormValue("grant_type"))
+		}
```
[the remark this answers is not in the document]
Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth_test.go]: fixed

File: pkg/login/social/connectors/azuread_oauth.go [hunk 5]
```diff
@@ -215,30 +218,121 @@ func (s *SocialAzureAD) Exchange(ctx context.Context, code string, authOptions .
...
+			ctx:                       ctx,
+			conf:                      s.Config,
+			token:                     t,
+			clientId:                  s.info.ClientId,
+			workloadIdentityTokenFile: s.info.WorkloadIdentityTokenFile,
+		}
+	}
+
+	return s.Config.TokenSource(ctx, t)
+}
```
[the remark this answers is not in the document]
Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth.go:236]: Agreed, but I am not able to test managedIdentity in dev/production

File: pkg/login/social/connectors/azuread_oauth_test.go [hunk 6]
```diff
@@ -1445,3 +1447,66 @@ func TestSocialAzureAD_Reload_ExtraFields(t *testing.T) {
...
+
+		w.Header().Set("Content-Type", "application/json")
+		json.NewEncoder(w).Encode(map[string]interface{}{
+			"access_token":  "new-access-token",
+			"token_type":    "Bearer",
+			"refresh_token": "new-refresh-token",
+			"expires_in":    time.Now().Add(time.Hour).Unix(),
```
[the remark this answers is not in the document]
Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth_test.go]: fixed

**Comment by Richard87** [comment]
Feedback from copilot has been addressed:

- [x] Typos
- [x] Failure test cases
- [ ] ManagedIdendity support (I dont have the facilities to test this, so I'm ignoreing this)

**Comment by PawOrmstrupMadsen** [comment]
Please do not forget about this, we REALLY need this fix :)

We use ManagedIdentity with Federated credentials - how can i help you test this PR?

**Comment by Richard87** [comment]
@PawOrmstrupMadsen 
We are currently running it in Prod with this image:
```
    image:
      registry: ghcr.io
      repository: equinor/radix/grafana
      tag: 12.3.0.2-test
```
(ref. https://github.com/equinor/radix-flux/blob/master/components/third-party/grafana/chart/helmRelease.yaml#L49-L52)

But maybe @taleena could advice if there is anything I/we can do?

File: pkg/login/social/connectors/azuread_oauth.go [hunk 7]
```diff
@@ -215,30 +218,126 @@ func (s *SocialAzureAD) Exchange(ctx context.Context, code string, authOptions .
...
+		return nil, fmt.Errorf("unable to unmarshal raw response body: %w", err)
+	}
+
+	var token *oauth2.Token
+	if err := json.Unmarshal(body, &token); err != nil {
+		return nil, fmt.Errorf("unable to unmarshal token response body: %w", err)
+	}
+
+	log.Debug("AzureADToken fetchToken completed")
+	return token.WithExtra(rawResponse), nil
```
Comment (volcanonoodle) [inline pkg/login/social/connectors/azuread_oauth.go:322]: Is the token’s `Expiry` field being set? I'm not sure if it might need to be set manually (like in [golang/oauth2 here](https://github.com/golang/oauth2/blob/4d954e69a88d9e1ccb8439f8d5b6cbef230c4ef9/internal/token.go#L300)). 

Otherwise, I would expect it to only be refreshed once because it would always be considered Valid after the first refresh ([see here](https://github.com/golang/oauth2/blob/4d954e69a88d9e1ccb8439f8d5b6cbef230c4ef9/oauth2.go#L311)). Something like:
```go
if token.ExpiresIn > 0 {
    token.Expiry = time.Now().Add(time.Duration(token.ExpiresIn) * time.Second)
}
```
Then maybe test that it is set correctly in the [success test case](https://github.com/grafana/grafana/blob/1979ae3cd60858876d6d530cbba983ad6a9cd6a9/pkg/login/social/connectors/azuread_oauth_test.go#L1516) with:
```go
assert.WithinDuration(t, time.Now().Add(3600*time.Second), newToken.Expiry, 5*time.Second)
```
Have you noticed token refreshment issues after the first successful refresh by any chance?

File: pkg/login/social/connectors/azuread_oauth_test.go [hunk 8]
```diff
@@ -1445,3 +1448,169 @@ func TestSocialAzureAD_Reload_ExtraFields(t *testing.T) {
...
+		}
+		ctx := context.WithValue(context.Background(), oauth2.HTTPClient, server.Client())
+
+		ts := s.TokenSource(ctx, token)
+		_, err = ts.Token()
+		require.Error(t, err)
+		require.Contains(t, err.Error(), "oauth2: cannot fetch token: 500 Internal Server Error")
+	})
+
+	t.Run("error when missing refresh token", func(t *testing.T) {
```
Comment (volcanonoodle) [inline pkg/login/social/connectors/azuread_oauth_test.go:1568]: I think the error message it should check for is `no refresh token available`, rather than a `400 Bad Request`. Without the refresh token the code doesn’t attempt the HTTP request, so we could do without mocking the HTTP server too I think.

File: pkg/login/social/connectors/azuread_oauth.go [hunk 9]
```diff
@@ -215,30 +218,126 @@ func (s *SocialAzureAD) Exchange(ctx context.Context, code string, authOptions .
...
+			token:                     t,
+			clientId:                  s.info.ClientId,
+			workloadIdentityTokenFile: s.info.WorkloadIdentityTokenFile,
+		}
+	}
+
+	return s.Config.TokenSource(ctx, t)
+}
+
+type AzureADTokenSource struct {
```
Comment (volcanonoodle) [inline pkg/login/social/connectors/azuread_oauth.go]: Does this struct need to be exported? Perhaps it could be `azureADTokenSource`

File: pkg/login/social/connectors/azuread_oauth.go [hunk 10]
```diff
@@ -17,6 +19,7 @@ import (
 	"github.com/google/uuid"
 	"golang.org/x/oauth2"
 
+	"github.com/grafana/grafana-app-sdk/logging"
```
Comment (volcanonoodle) [inline pkg/login/social/connectors/azuread_oauth.go]: `AzureADTokenSource` uses `logging.FromContext(s.ctx)` (from grafana-app-sdk), while the rest of this file uses `s.log` from `SocialBase`. We could instead save the `SocialBase` logger in the struct and use it. This would avoid the new `grafana-app-sdk/logging` import. Something like:
```go
import "github.com/grafana/grafana/pkg/infra/log"
...
type AzureADTokenSource struct {
    ...
    log log.Logger
 }
```

File: pkg/login/social/connectors/azuread_oauth.go [hunk 11]
```diff
@@ -215,30 +218,126 @@ func (s *SocialAzureAD) Exchange(ctx context.Context, code string, authOptions .
...
+	}
+	defer resp.Body.Close()
+
+	body, err := io.ReadAll(resp.Body)
+	if err != nil {
+		return nil, fmt.Errorf("oauth2: cannot fetch token: %v", err)
+	}
+
+	if resp.StatusCode < 200 || resp.StatusCode > 299 {
+		return nil, fmt.Errorf("oauth2: cannot fetch token: %v\nResponse: %s", resp.Status, body)
```
Comment (volcanonoodle) [inline pkg/login/social/connectors/azuread_oauth.go]: Returning the body of the response in the error could leak sensitive data if the error is logged later on. Maybe we could log it at the debug level right here and return the error without the body instead, what do you think?

**Review by volcanonoodle — COMMENTED** [review]
@Richard87 thanks a lot for the contribution and for addressing token refresh for Azure OAuth with Workload Identities, we really appreciate it!

At the moment, we don't have an Azure Workload Identity setup on our side to test this flow end-to-end. Have you been running this configuration in your environment, and could you confirm that the custom refresh logic works as expected there?

File: pkg/login/social/connectors/azuread_oauth.go (hunk 9 above)
Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth.go]: Nice, fixed 👍

File: pkg/login/social/connectors/azuread_oauth.go (hunk 11 above)
Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth.go]: agreed, nice catch. Usually its a json with some details about what fails so nice to have when troubleshooting

File: pkg/login/social/connectors/azuread_oauth.go (hunk 10 above)
Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth.go]: Fixed 👍

File: pkg/login/social/connectors/azuread_oauth.go (hunk 7 above)
Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth.go:322]: Interresting, I'll take a look!

Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth.go:322]: And yes :) It has been running in 4 production clusters now (and our dev cluster) since a bit before I opened the PR, and it solved all our problebs regarding signing in again every hour :)

File: pkg/login/social/connectors/azuread_oauth.go (hunk 11 above)
Comment (volcanonoodle) [reply pkg/login/social/connectors/azuread_oauth.go]: Nice, thank you. I just noticed it's now being logged at the `Warn` level, rather than `Debug`. I think `Debug` would be ideal because we wouldn't be logging it by default, as opposed to `Warn`.

File: pkg/login/social/connectors/azuread_oauth_test.go (hunk 8 above)
Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth_test.go:1568]: Nice catch, fixed :)

**Review by Richard87 — COMMENTED** [review]
@volcanonoodle Thanks for the review!

I'm rolling out the new versions with the tweaks to production at our site today, what can I do to help you further?

**Comment by volcanonoodle** [comment]
> @volcanonoodle Thanks for the review!
> 
> I'm rolling out the new versions with the tweaks to production at our site today, what can I do to help you further?

That's great to hear, thank you @Richard87 ! Once all the feedback has been addressed I'll do some testing. If that works and you have it running at your site for a bit without problems, I think we'll be good to go 😄

**Comment by Richard87** [comment]
@volcanonoodle All issues should have been addressed (I have only commented on them, but waiting to click resolve until you are happy :) 

Its been running in production now for a  couple of hours, and refresh tokens works like a charm 👍 

Small summary ;)

- [x] Remove mock http server in one of the tests
- [x] Always set Expires when ExpiresIn is set
- [x] Better log-handling
- [x] Keep the main struct internal
- [ ] Copilot: `managedIdentity` is not tested and not supported by this fix since I'm unable to test it... 
      It also doesn't make any sense since you cannot use managed identities to authorize users, you must use Azure App Registrations. To authenticate the client ypu must use either Client Secret or Workload Identity (aka. federated credentials, aka. Client Assertions)

File: pkg/login/social/connectors/azuread_oauth.go (hunk 11 above)
Comment (volcanonoodle) [reply pkg/login/social/connectors/azuread_oauth.go]: @Richard87 this is still being logged at the `Warn` level. Could you make it `Debug` please? 🙏

**Comment by volcanonoodle** [comment]
> @volcanonoodle All issues should have been addressed (I have only commented on them, but waiting to click resolve until you are happy :)
> 
> Its been running in production now for a couple of hours, and refresh tokens works like a charm 👍

Nice, thank you for the update @Richard87 ! I've added a tiny comment as this still needs to be addressed I think https://github.com/grafana/grafana/pull/114172#discussion_r2831983377

Have you noticed any differences in behaviour since you addressed the `token.Expiry` issue? I'd have expected token-refreshment to stop working after the first refresh without it 🤔  https://github.com/grafana/grafana/pull/114172#discussion_r2815712521

I'll try to do some testing myself soon. Thanks again for all the work on this 🙇

File: pkg/login/social/connectors/azuread_oauth.go (hunk 11 above)
Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth.go]: Wow, absolutley, sorry I missed that :) Fixed now 👍

**Comment by Richard87** [comment]
> Have you noticed any differences in behaviour since you addressed the `token.Expiry` issue? I'd have expected token-refreshment to stop working after the first refresh without it 🤔 [#114172 (comment)](https://github.com/grafana/grafana/pull/114172#discussion_r2815712521)

@volcanonoodle, no, I think its because of the logic in `GetIDTokenExpiry` that checks the "exp" claim in the id_token, instead of looking at the Expires/ExpiresIn fields.
https://github.com/sveinpj/grafana/blob/83e9266bc99455f126f49c942f6d8fb01852841f/pkg/services/oauthtoken/oauth_token.go#L609

While debugging the `id_token.exp` expired in exactly 1 hour, so makes kinda sense ;)

File: pkg/login/social/connectors/azuread_oauth.go [hunk 12]
```diff
@@ -8,16 +8,17 @@ import (
...
 	"strings"
+	"time"
 
 	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
 	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
 	jose "github.com/go-jose/go-jose/v4"
 	"github.com/go-jose/go-jose/v4/jwt"
 	"github.com/google/uuid"
-	"golang.org/x/oauth2"
-
```
Comment (volcanonoodle) [inline pkg/login/social/connectors/azuread_oauth.go:19]: Whoops I missed this earlier, could we keep this import unmodified where it is please?

**Comment by volcanonoodle** [comment]
@Richard87 I'm sharing the output of `golangci-lint` just in case it's not easy to see it. I think these are the only missing things, together with https://github.com/grafana/grafana/pull/114172#discussion_r2836340507. It's looking great, thank you for all the work so far 😄 
```
  Error: pkg/login/social/connectors/azuread_oauth.go:291:23: Error return value of `resp.Body.Close` is not checked (errcheck)
  	defer resp.Body.Close()
  	                     ^
```
and
```
Error: pkg/login/social/connectors/azuread_oauth_test.go:1492:29: Error return value of `(*encoding/json.Encoder).Encode` is not checked (errcheck)
  			json.NewEncoder(w).Encode(map[string]interface{}{
  			                         ^
```

File: pkg/login/social/connectors/azuread_oauth.go (hunk 12 above)
Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth.go:19]: fixed 👍

**Comment by Richard87** [comment]
> @Richard87 I'm sharing the output of `golangci-lint` just in case it's not easy to see it. I think these are the only missing things, together with [#114172 (comment)](https://github.com/grafana/grafana/pull/114172#discussion_r2836340507). It's looking great, thank you for all the work so far 😄
> 
> ```
>   Error: pkg/login/social/connectors/azuread_oauth.go:291:23: Error return value of `resp.Body.Close` is not checked (errcheck)
>   	defer resp.Body.Close()
>   	                     ^
> ```
> 
> and
> 
> ```
> Error: pkg/login/social/connectors/azuread_oauth_test.go:1492:29: Error return value of `(*encoding/json.Encoder).Encode` is not checked (errcheck)
>   			json.NewEncoder(w).Encode(map[string]interface{}{
>   			                         ^
> ```

Awesome, both are fixed :), thanks for quick feedback!

I'm really looking forward to not having to run a fork in prod ;)

File: pkg/login/social/connectors/azuread_oauth.go (hunk 12 above)
Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth.go:19]: golangci-lint keeps moving the line to the bottom, I suggest keeping it where golang wants, to avoid every PR having the same issue 🤔 

If you insist, I will move it in vim or something :)

Comment (Richard87) [reply pkg/login/social/connectors/azuread_oauth.go:19]: I fixed it, not sure if its my vscode formatter, or golangci-lint that moved the line 🤷

**Comment by volcanonoodle** [comment]
@Richard87 turns out that `gofmt` complains about the imports not being properly formatted now. The way you had it before was correct, sorry for misleading you 🤦‍♂️

**Comment by Richard87** [comment]
@volcanonoodle hahaha no problem :D I was unsure which formatter I had that caused it... 

Fixing it now :)

**Review by volcanonoodle — APPROVED** [review]
Awesome job with this @Richard87, thank you very much for the great contribution and for testing it in your own environment!!! 🙇

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/22308523113)
- Version: 13.0.0-22308523113

**Comment by naizerjohn-ms** [comment]
@Richard87 thank you so much for working on closing this long-standing bug! Great to see all of the contributions here
