### PR TITLE
VizLegendTable: fixes column spacing to span to the right side

### LINKED ISSUE #35012: Legend: Table layout spaces out columns equally instead of at the right side
Old Graph:
Screenshot from 2021-06-01 08-37-58

New Time series
Screenshot from 2021-06-01 08-38-10

### PR DESCRIPTION
**Pull request by thisisobate**
**What this PR does / why we need it**:
This PR fixes new timeseries legend table column spacing to span towards the right side.
**Which issue(s) this PR fixes**:

Fixes #35012

### CODE REVIEW

**Review by dprokop — CHANGES_REQUESTED** [review]
The data in the table is wrongly aligned:

image

File: packages/grafana-ui/src/components/VizLegend/VizLegendTable.tsx [hunk 1]
```diff
@@ -65,6 +65,9 @@ export const VizLegendTable = <T extends unknown>({
 
   return (
     <table className={cx(styles.table, className)}>
+      <colgroup>
+        <col style={{ width: '100%' }} />
+      </colgroup>
```
Comment (dprokop) [inline packages/grafana-ui/src/components/VizLegend/VizLegendTable.tsx:70]: This works, but I wonder why? :D

**Review by dprokop — APPROVED** [review]
Now it works good!

**Comment by dprokop** [comment]
@thisisobate can you also fix the `Last (not null)` and possibly other header breaking into new line?

File: packages/grafana-ui/src/components/VizLegend/VizLegendTable.tsx (hunk 1 above)
Comment (thisisobate) [reply packages/grafana-ui/src/components/VizLegend/VizLegendTable.tsx:70]: According to w3schools: 
```
The <colgroup> tag is useful for applying styles to entire columns, instead of repeating the styles for each cell, for each row.
```
But I think I can just explicitly set the width of the first column to 100%. Would push the changes now
