### PR TITLE
Logs: Fix table panel not rendering on initial load in Explore

### LINKED ISSUE #105022: Logs Table: Logs query returns data, but Table is not visible
### What happened?

When initially coming into Explore and writing a logs query, when the default viz is already set to table, the table panel is not loaded until the user refreshes the page, or switches between the logs panel and the table panel.

Image

### What did you expect to happen?

Table panel should load

### Did this work before?

Yes, before 12

### How do we reproduce it?

1. Go to explore
2. Set table as default panel
3. Go to fresh explore url: `/explore`
4. Write log query
5. Notice table doesn't load

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Main

### Grafana platform?

None

### Datasource(s)?

All logs datasources

### PR DESCRIPTION
**Pull request by gtk-grafana**
**What is this fix?**

Fixes issue with table panel not rendering until refresh or switching back and forth between logs panel and table panel in Explore.

**Who is this fix for?**
Users of logs in Explore.

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/grafana/issues/105022

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/logs/components/ControlledLogRows.tsx [hunk 1]
```diff
@@ -86,9 +86,7 @@ export const ControlledLogRows = forwardRef<HTMLDivElement | null, ControlledLog
         {rest.visualisationType === 'logs' && (
           <LogRowsComponent ref={ref} {...rest} deduplicatedRows={deduplicatedRows} />
         )}
-        {rest.visualisationType === 'table' && rest.panelState && rest.updatePanelState && (
-          <ControlledLogsTable {...rest} />
-        )}
+        {rest.visualisationType === 'table' && rest.updatePanelState && <ControlledLogsTable {...rest} />}
```
Comment (L2D2Grafana) [inline public/app/features/logs/components/ControlledLogRows.tsx:89]: Not sure if I'm testing this right, so let me know! Locally I go to `http://localhost:3000/explore` and select the table. Then I type a query `{app="faro-shop-frontend"}` and the table does not show. Line 89 also does not even run if a breakpoint is added. Even if I click the logs (I see logs), but come back to table and it's still empty.
Screenshot 2025-05-06 at 9 13 37 AM

Comment (L2D2Grafana) [reply public/app/features/logs/components/ControlledLogRows.tsx:89]: Apparently my issues was because I had set `newLogsPanel = true` in `newLogsPanel = false` the fix works 👍

**Comment by gtk-grafana** [comment]
Verified that this works with `logsPanelControls` disabled as well. Should be good to go once you can wrap up your review @L2D2Grafana

**Review by matyax — APPROVED** [review]

**Review by L2D2Grafana — APPROVED** [review]
🚀
