### PR TITLE
Variables: Panel no longer crash when using the adhoc variable in data links.

### LINKED ISSUE #39514: Using Adhoc variable in a datalink or panel link breaks the dashboard
**What happened**:
Creating a datalink or a panel link that references an adhoc variable breaks the panel with :  Cannot read properties of undefined (reading 'value')

**What you expected to happen**:
I expected the link to work, to have the variables populated from the adhoc variable, and Grafana to not break. Using the __all_variables works without issues.

**How to reproduce it (as minimally and precisely as possible)**:
Create a datalink in a dashboard that has an adhoc variable (called test) and set the link to http://mywebsite/${test:queryparam}. By clicking on the graph to show the datalink, the panel breaks and shows the following error : Cannot read properties of undefined (reading 'value')

Create a panel link in a dashboard that has an adhoc variable (called test) and set the link to http://mywebsite/${test:queryparam}. By hovering over the panel link the Grafana page breaks and shows an error 
```
An unexpected error happened
DétailsTypeError: Cannot read properties of undefined (reading 'value')

    at l (https://grafana-assets.grafana.net/grafana-pro/8.1.4/public/build/vendors~app.62c612232a976d8836f5.js:2:477447)
    at div
    at d (https://grafana-assets.grafana.net/grafana-pro/8.1.4/public/build/app.62c612232a976d8836f5.js:960:29720)
    at t (https://grafana-assets.grafana.net/grafana-pro/8.1.4/public/build/vendors~app.62c612232a976d8836f5.js:2:1879404)
    at a (https://grafana-assets.grafana.net/grafana- ....
```

**Anything else we need to know?**:
Using the __all_variables works without issues.
 
**Environment**:
- Grafana version: Grafana v8.1.4 (6855cdff7c)
- Data source type & version: Prometheus
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Chrome
- Grafana plugins: NA

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
Not sure about the change in TemplatSrv, it's one of those parts of the code where I haven't understood all the scenarios. But I don't think we've ever supported `adhoc` variables in TemplateSrv so I added some logic to handle that?

Maybe this PR could be simplified so we don't need the `canHandle` function in the formatRegistry? I added a `FormatRegistryID` enum to get rid of some `magic strings` sprinkled throughout the code.

**Which issue(s) this PR fixes**:
Fixes #39514

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/templating/template_srv.ts [hunk 1]
```diff
@@ -270,6 +278,13 @@ export class TemplateSrv implements BaseTemplateSrv {
         return match;
       }
 
+      if (isAdHoc(variable)) {
+        const value = variable.filters;
+        const text = variable.id;
+
+        return this.formatValue(value, fmt, variable, text);
+      }
```
Comment (torkelo) [inline public/app/features/templating/template_srv.ts:286]: Feels like the canHandle function adds some unnecessary complexity/duplication to all formats for just this scenario (at least for now), so instead of having canHandle on all formats can we not just allow it? if we here set value to JSON.stringify(variable.filters) all the other formatters will handkle adhoc fine, and the queryParm will still work the same as it's not use value but inspecting the variable object

**Review by torkelo — COMMENTED** [review]
Looks good but suggested a simpler solution that could get rid of canHandle

File: public/app/features/templating/formatRegistry.ts [hunk 2]
```diff
@@ -13,15 +14,36 @@ export interface FormatOptions {
...
+  html = 'html',
+  json = 'json',
+  percentencode = 'percentencode',
+  singlequote = 'singlequote',
+  doublequote = 'doublequote',
+  sqlstring = 'sqlstring',
+  date = 'date',
+  glob = 'glob',
+  text = 'text',
+  queryparam = 'queryparam',
```
Comment (ashharrison90) [inline public/app/features/templating/formatRegistry.ts:37]: minor nit: think typescript enums are generally PascalCase.

File: public/app/features/templating/template_srv.test.ts [hunk 3]
```diff
@@ -675,27 +716,55 @@ describe('templateSrv', () => {
...
+
+    it(`query variable with adhoc value with queryparam format should return correct ${FormatRegistryID.queryparam}`, () => {
+      const target = _templateSrv.replace(`\${adhoc:${FormatRegistryID.queryparam}}`, {});
+      expect(target).toBe('var-adhoc=alertstate%7C%3D%7Cfiring&var-adhoc=alertname%7C%3D%7CExampleAlertAlwaysFiring');
+    });
+
+    it(`query variable with multi value and queryparam format should return correct ${FormatRegistryID.queryparam}`, () => {
+      const target = _templateSrv.replace('${adhoc}', {}, FormatRegistryID.queryparam);
+      expect(target).toBe('var-adhoc=alertstate%7C%3D%7Cfiring&var-adhoc=alertname%7C%3D%7CExampleAlertAlwaysFiring');
+    });
```
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply public/app/features/templating/template_srv.test.ts:768]: Great feedback, I was thinking the same as I was changing the strings I had to the enum! I'll fix it!

File: public/app/features/templating/template_srv.ts (hunk 1 above)
Comment (hugohaggmark) [reply public/app/features/templating/template_srv.ts:286]: Great suggestion, I'll fix!

File: public/app/features/templating/formatRegistry.ts (hunk 2 above)
Comment (hugohaggmark) [reply public/app/features/templating/formatRegistry.ts:37]: Thank you, I'll fix it!

Comment (hugohaggmark) [reply public/app/features/templating/formatRegistry.ts]: Fixed!

File: public/app/features/templating/template_srv.ts (hunk 1 above)
Comment (hugohaggmark) [reply public/app/features/templating/template_srv.ts]: Fixed!

File: public/app/features/templating/template_srv.test.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply public/app/features/templating/template_srv.test.ts]: Fixed!

File: public/app/features/templating/formatRegistry.ts [hunk 4]
```diff
@@ -16,10 +16,29 @@ export interface FormatRegistryItem extends RegistryItem {
...
+  html = 'html',
+  json = 'json',
+  percentEncode = 'percentencode',
+  singleQuote = 'singlequote',
+  doubleQuote = 'doublequote',
+  sqlString = 'sqlstring',
+  date = 'date',
+  glob = 'glob',
+  text = 'text',
+  queryParam = 'queryparam',
```
Comment (ashharrison90) [inline public/app/features/templating/formatRegistry.ts:35]: i meant like 
```typescript
  Json = 'json',
  PercentEncode = 'percentencode',
  SingleQuote = 'singlequote',
  ...etc
```
but tbh looking at the rest of the codebase we're not super consistent on this 🤷

Comment (hugohaggmark) [reply public/app/features/templating/formatRegistry.ts:35]: Aha ok, I was looking at the IDs in `packages/grafana-data/src/transformations/matchers/ids.ts`

**Review by ashharrison90 — APPROVED** [review]
