### PR TITLE
Explore: Fix log context scroll to bottom

### LINKED ISSUE #50268: Loki 'Show Context' doesn't align to the 'previous' log lines correctly
**Problem**
When I open up the 'Show Context' modal, the log lines that get displayed that are above the line around which I'm showing context aren't centered properly. What I get shown is centered on the oldest possible log line (furthest away from the line around which I want context), rather than the log line that is closest to the line I want context about. 

See [link to gif](https://drive.google.com/file/d/1kQCxYGf1w-MAwGca1UsuweujNMc_psdL/view?usp=sharing)

truncated-lines

**Solution**
Context should be centered around the line I clicked the show context button for. It should be scrolled all the way down to the line nearest the show context line to start. Then I can choose to scroll up and away from that line if I need to see more, older log lines. 

Screen Shot 2022-06-06 at 1 23 30 PM

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
This PR fixes the issue with log context, where top log context window wasn't scrolled downed. You can find more information in why it is wanted in https://github.com/grafana/grafana/issues/50268. 

The main issue was that we didn't add rows into the `useLayoutEffect`  dependency array which meant, that we didn't run when rows changed. And because fetching of rows is async, we firstly passed to context empty array https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Logs/LogRowContextProvider.tsx#L199-L202,  which meant that the `offsetHeight` of that element was 0 as it was empty, and then when actual rows arrived, we didn't re-calculate this. 

Moreover, we want to do this scrolling only when first batch of rows arrive.

https://user-images.githubusercontent.com/30407135/173063423-bba6f9af-699b-4b14-91cc-9bf7a9c881d8.mov

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/50268

**How to test**:
1. run `make devenv sources=loki` in terminal
2. In Explore, open `gdev-loki` data source and run `{place="luna"} |= "error"` query
3. Click on `Show context` in one of the log lines
4. Check if top log context container is scrolled down to the bottom

### CODE REVIEW

File: packages/grafana-ui/src/components/Logs/LogMessageAnsi.tsx [hunk 1]
```diff
@@ -82,6 +82,7 @@ export class UnThemedLogMessageAnsi extends PureComponent<Props, State> {
     return chunks.map((chunk, index) => {
       const chunkText = this.props.highlight?.searchWords ? (
         <Highlighter
+          key={index}
```
Comment (ivanahuckova) [inline packages/grafana-ui/src/components/Logs/LogMessageAnsi.tsx:85]: This is unrelated change, but I noticed it when working on this.  Unfortunately, there is no unique identifier, so I ended up with index.

**Review by gabor — APPROVED** [review]
nice find!
