### PR TITLE
Elasticsearch: Show Size setting for raw_data metric

### LINKED ISSUE #30964: Size field for Raw Data is missing after upgrading to 7.4.0
**What happened**:
After upgrading to grafana 7.4.0, the "Size" field is no longer available for Raw Data. 

**What you expected to happen**:
Field should remain available with at least the same max value as previous version of grafana

**How to reproduce it (as minimally and precisely as possible)**:
Reproducable by upgrading to 7.4.0 and downgrading back to 7.3
Add a panel, choose Raw Data

**Anything else we need to know?**:
Grafana 7.3
image

Grafana 7.4.0:
image

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Docker
- User OS & Browser: Windows / Firefox
- Grafana plugins: grafana-piechart-panel,grafana-azure-monitor-datasource,mtanda-google-calendar-datasource,alexanderzobnin-zabbix-app,jasonlashua-prtg-datasource,snuids-trafficlights-pan
el,ryantxu-ajax-panel,grafana-worldmap-panel,agenty-flowcharting-panel

### PR DESCRIPTION
**Pull request by Elfo404**
**What this PR does / why we need it**:
The React migration introduced a tiny bug for which we are not showing the settings editor when selecting a `raw_data` metric in the ES query editor, this PR brings back the settings editor for that metric type.

**Which issue(s) this PR fixes**:

Fixes #30964

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/datasource/elasticsearch/components/QueryEditor/MetricAggregationsEditor/utils.ts [hunk 1]
```diff
@@ -208,7 +208,7 @@ export const metricAggregationConfig: MetricsConfiguration = {
     isPipelineAgg: false,
     supportsMissing: false,
     supportsMultipleBucketPaths: false,
-    hasSettings: false,
+    hasSettings: true,
```
Comment (Elfo404) [inline public/app/plugins/datasource/elasticsearch/components/QueryEditor/MetricAggregationsEditor/utils.ts:211]: To reviewers: This is the actual fix.

**Review by ivanahuckova — APPROVED** [review]
LGTM! Works nicely. Awesome that you added test for this as well. 🚀
