### PR TITLE
InfluxDB: Fix sending retention policy with InfluxQL queries

### LINKED ISSUE #63672: InfluxDB: Sending retention policy causes empty response when querying fields
Original PR: https://github.com/grafana/grafana/pull/62149

How to reproduce:

- Go to main branch. 
- Apply the changes in the PR above
- Run Grafana and InfluxDB
- Select measurement `cpu`
- Click field() 
- Observe there is no data
- In the network tab we have error
- ` {"results":[{"statement_id":0,"error":"retention policy not found: default"}]}`

This is the query that doesn't return results:
https://play.grafana.org/api/datasources/proxy/uid/000000002/query?db=site&rp=default&epoch=ms

Image

Grafana Version: `v9.4.1`

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

From Original PR https://github.com/grafana/grafana/pull/62149
> In InfluxDB v2, due to technical limitations of the InfluxDB v1 compatibility layer, retention policies in a query (e.g. <retention policy>.<measurement_name>) aren't honored and must be specified in the URL query parameter rp to be applied. Grafana doesn't send this query parameter which results in all queries resolving to the default retention policy when querying InfluxDB v2 servers using InfluxQL.
> 
> This addresses the issue by sending the rp query parameter for queries that have specified a retention policy in the target given to runExploreQuery.
> 
> The outcomes are:
> 
>     InfluxQL queries executed against InfluxDB v2 databases will have the necessary retention policy information for queries like SHOW FIELD KEYS FROM measurement to function correctly.
>     InfluxQL queries executed against InfluxDB v1 databases will be unaffected, because this rp query parameter is unsupported there.
> 
> You can read more about the rentention policy mapping behavior of InfluxDB v2 in our documentation:
> 
>     https://docs.influxdata.com/influxdb/v2.6/reference/api/influxdb-1x/dbrp/#when-querying-data
>     https://docs.influxdata.com/influxdb/v2.6/reference/api/influxdb-1x/query/#query-a-non-default-retention-policy

**What did I add?**
I also changed the default retention policy value from `default` to `autogen`
Because: 
> InfluxDB automatically generated an RP named autogen and set it as the DEFAULT RP for the database.
>https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#retention-policy-rp

Without this we try to query with `default` retention policy and if there is no such policy, the query fails.
See: https://github.com/grafana/support-escalations/issues/5114

**Why do we need this feature?**

This ensures field keys only present in the default retention policy aren't displayed in the query builder for non-default retention policies.

**Who is this feature for?**

Anyone using InfluxQL to query against an InfluxDB v2 API (using v1 compatibility).

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/63672
https://github.com/grafana/support-escalations/issues/5114

### How to test
- Run Grafana
- Run dev env `make devenv sources=influxdb,influxdb1`
- Go to `Explore`
- Select `gdev-influxdb1-influxql`
- See in the `FROM` section, before `select measurement` the retention policies are loaded. 
- The default policy is the first one and selected
- Select a measurement and a field.
- Observe that you can do both
- Select `gdev-influxdb-influxql`
- Go through same steps
- In the network tab you would see your queries are being sent with policy. 
  - `bar` as policy
  - `SELECT mean("value") FROM "bar"."cpu" WHERE time >= now() - 1h and time <= now() GROUP BY time(1s) fill(null)`

### CODE REVIEW

**Comment by gavincabbage** [comment]
Hello 👋 What release can we expect this PR to be merged and included in? Thanks!

File: public/app/plugins/datasource/influxdb/components/VisualInfluxQLEditor/Editor.tsx [hunk 1]
```diff
@@ -76,6 +77,18 @@ export const Editor = (props: Props): JSX.Element => {
...
+    getAllPolicies(datasource).then((result) => {
+      if (!ignore) {
+        setRetentionPolicies(result);
+      }
+    });
+    return () => {
+      ignore = true;
+    };
+  }, [datasource]);
+
```
Comment (gabor) [inline public/app/plugins/datasource/influxdb/components/VisualInfluxQLEditor/Editor.tsx:91]: just a random note. i had good experience with using the `react-use` npm package for these situations, for example this function: https://streamich.github.io/react-use/?path=/story/side-effects-useasyncfn--docs may help you to write simpler code here (but maybe not, just an idea)

(`react-use` is already used in grafana so it does not need to be added)

File: public/app/plugins/datasource/influxdb/response_parser.ts [hunk 2]
```diff
@@ -264,9 +277,9 @@ function incrementName(name: string, nameIncremenet: string, params: string[], i
   return nameIncremenet;
 }
 
-function addUnique(s: Set<string>, value: string | number) {
-  s.add(value.toString());
-}
+// function addUnique(s: Set<string>, value: string | number) {
+//   s.add(value.toString());
+// }
```
Comment (gabor) [inline public/app/plugins/datasource/influxdb/response_parser.ts:282]: do you want to keep this commented-out function?

**Comment by gabor** [comment]
hi @itsmylife , i checked the new commits, they look fine 👍 .(i left a couple small notes, but they are not that important)

File: public/app/plugins/datasource/influxdb/components/VisualInfluxQLEditor/Editor.tsx (hunk 1 above)
Comment (itsmylife) [reply public/app/plugins/datasource/influxdb/components/VisualInfluxQLEditor/Editor.tsx:91]: I will check it. Thanks for the suggestion.

File: public/app/plugins/datasource/influxdb/components/VisualInfluxQLEditor/Editor.tsx [hunk 3]
```diff
@@ -76,6 +78,11 @@ export const Editor = (props: Props): JSX.Element => {
   const { datasource } = props;
   const { measurement, policy } = query;
 
+  useAsync(async () => {
+    const response = await getAllPolicies(datasource);
+    await setRetentionPolicies(response);
+  }, [datasource]);
```
Comment (gabor) [inline public/app/plugins/datasource/influxdb/components/VisualInfluxQLEditor/Editor.tsx:84]: this can be even simpler, without needing `useState`, something like this:
```ts
  const policyData = useAsync(
        () => getAllPolicies(datasource),
        [datasource]
  );
  const retentionPolicies = policyData.error != null ? [] : policyData.value ?? [];
```

**Review by gabor — APPROVED** [review]
LGTM 👍 
(i left a comment below about how `useAsync` can be used in an even simpler)

**Review by gtk-grafana — APPROVED** [review]

**Review by bohandley — APPROVED** [review]
LGTM!
