### PR TITLE
Alerting: Add checks for non supported units - disable defaulting to seconds

### LINKED ISSUE #15866: Avoid second as default unit for alerting interval since it can be confusing when using invalid duration units.
**What happened**: Users have entered several variants of of frequency including but not limited to
* 6hr
* 24hr
screen shot 2019-03-07 at 3 58 33 pm

This then sets these alerts to run at "6" second intervals and "24" second intervals creating havok on your backend. 

**What you expected to happen**:
Grafana rejects invalid time or the admin has the ability to set a default if the time doesn't match a valid one. 

**How to reproduce it (as minimally and precisely as possible)**:
create any alert and fill in "6hr" on the alert frequency

**Anything else we need to know?**:
Even if the UI accepts only correct data a hard setting of maximum query frequency is still valuable. Some users do not understand time series send intervals and often try to alert faster than actual data comes in.

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: any
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

This PR is responsible for preventing `Evaluate every` and `For` fields in **`Alert`** tab to receive unknown units, or numbers without any unit specified.

To date, in the `Evaluate every` (`Frequency`) field, if a _number without any unit_ or a _number with a wrong unit_ appears, it will **default** to seconds. This is something we want to prevent.

About the `For` field, if it receives a number with an unknown unit, then it will fail, throwing `Validation failed` error. 

**Which issue(s) this PR fixes**:

Fixes #15866

**Special notes for your reviewer**:
After you checkout and test with this branch, you can see in the console errors like:

```
{"message":"alert validation error: time unit not supported. supported units: [s m h d]"}
```

Is it something that we should also add on the [frontend side here](https://github.com/grafana/grafana/blob/master/public/app/core/services/backend_srv.ts#L292) and not only in the response?

Maybe something like 
```
if (err.status === 422) {
      message = message + 'Validation failed';
}
```

(cc @torkelo)

### CODE REVIEW

File: pkg/services/alerting/extractor.go [hunk 1]
```diff
@@ -12,6 +13,12 @@ import (
 	"github.com/grafana/grafana/pkg/models"
 )
 
+var (
+	valueFormatRegex = regexp.MustCompile(`^\d+`)
```
Comment (marefr) [inline pkg/services/alerting/extractor.go:17]: Think this one should be in rule.go since it's used there

File: pkg/services/alerting/extractor.go [hunk 2]
```diff
@@ -12,6 +13,12 @@ import (
...
+	unitFormatRegex  = regexp.MustCompile(`[a-z]+`)
+	isDigitRegex     = regexp.MustCompile(`^[0-9]+$`)
```
Comment (marefr) [inline pkg/services/alerting/extractor.go:19]: Think this one should be in rule.go since it's used there

File: pkg/services/alerting/extractor.go [hunk 3]
```diff
@@ -111,6 +118,10 @@ func (e *DashAlertExtractor) getAlertFromPanels(jsonWithPanels *simplejson.Json,
 		rawFor := jsonAlert.Get("for").MustString()
 		var forValue time.Duration
 		if rawFor != "" {
+			unit := unitFormatRegex.FindAllString(rawFor, 1)[0]
```
Comment (marefr) [inline pkg/services/alerting/extractor.go:121]: This field was not part of the referenced issue or was it? Wouldn't time.ParseDuration catch any problem with this?

File: pkg/services/alerting/extractor.go [hunk 4]
```diff
@@ -12,6 +13,12 @@ import (
 	"github.com/grafana/grafana/pkg/models"
 )
 
+var (
+	valueFormatRegex = regexp.MustCompile(`^\d+`)
+	unitFormatRegex  = regexp.MustCompile(`[a-z]+`)
```
Comment (marefr) [inline pkg/services/alerting/extractor.go:18]: Any reason changing this from `unitFormatRegex = regexp.MustCompile(`\w{1}$`)`?

**Review by marefr — CHANGES_REQUESTED** [review]
Think frontend validation is most important as a start. Recommend adding `ng-pattern` in [frontend](https://github.com/grafana/grafana/blob/270a255c08379e23329d9d3feeb6fe186b1bd950/public/app/features/alerting/partials/alert_tab.html#L18-L33) for the input fields. [Example](https://github.com/grafana/grafana/blob/784425c2eeca284a947bb36a62216100d6c21853/public/app/plugins/datasource/postgres/partials/config.html#L166)

I think it should be fine returning validation errors from backend, but might cause issues for users if we're not careful.

I added some comments/questions as well

File: pkg/services/alerting/extractor.go (hunk 4 above)
Comment (dsotirakis) [reply pkg/services/alerting/extractor.go:18]: Yeah, so check this case out:

* _using `\w{1}$`_, when checking with `5hh`, the captured letter is `h`, which can (falsely) be valid, since it takes only the last character.
* _using `[a-z]+`_, when checking with `5hh`, the captured characters are `hh` which is invalid and should throw an error.

File: pkg/services/alerting/extractor.go (hunk 3 above)
Comment (dsotirakis) [reply pkg/services/alerting/extractor.go:121]: I think it is better to distinguish the errors, meaning that if it has happened because of a wrong unit, then throw `ErrWrongUnitFormat.Error`, if something else happens, then throw `"Could not parse for"`. My pov though, feel free to disagree.

File: public/app/features/alerting/partials/alert_tab.html [hunk 5]
```diff
@@ -20,6 +20,7 @@ <h4 class="section-heading">Rule</h4>
           type="text"
           ng-model="ctrl.alert.frequency"
           ng-blur="ctrl.checkFrequency()"
+          ng-pattern="^\d+([dhms])$
```
Comment (marefr) [inline public/app/features/alerting/partials/alert_tab.html:23]:
```suggestion
          ng-pattern="/^\d+([dhms])$/"
```

File: public/app/features/alerting/partials/alert_tab.html [hunk 6]
```diff
@@ -30,6 +31,7 @@ <h4 class="section-heading">Rule</h4>
           ng-model="ctrl.alert.for"
           spellcheck="false"
           placeholder="5m"
+          ng-pattern="^\d+([dhms])$"
```
Comment (marefr) [inline public/app/features/alerting/partials/alert_tab.html:34]: Need to allow an empty value and only zero (0). Zero is stored in database and rendered in UI if For has been saved with an empty value.
image

```suggestion
          ng-pattern="/^\d+([dhms])$/"
```

**Review by marefr — CHANGES_REQUESTED** [review]
Looks good. Added some suggestions/comments

File: pkg/services/alerting/extractor.go (hunk 3 above)
Comment (dsotirakis) [reply pkg/services/alerting/extractor.go:119]: Yeah I agree. Maybe some better error messages to be done in another ticket 👍

Comment (marefr) [reply pkg/services/alerting/extractor.go:119]: Think it's better to address in this PR

File: public/app/features/alerting/partials/alert_tab.html [hunk 7]
```diff
@@ -30,6 +31,7 @@ <h4 class="section-heading">Rule</h4>
           ng-model="ctrl.alert.for"
           spellcheck="false"
           placeholder="5m"
+          ng-pattern="/^\d+([dhms])$/"
```
Comment (marefr) [inline public/app/features/alerting/partials/alert_tab.html:34]: Still think zero and empty should be accepted here.

**Review by marefr — CHANGES_REQUESTED** [review]
Saved an existing dashboard that has alert rules which generated a panic. It has a panel where `For` is zero, attaching panel JSON below. Zero and empty probably should not generate an error and resolve to default 0 (zero).

```
EROR[04-01|16:14:11] Request error                            logger=context userId=1 orgId=1 uname=admin error="runtime error: index out of range [0] with length 0" stack="/usr/local/go/src/runtime/panic.go:88 (0x43e124)\n\tgoPanicIndex: panic(boundsError{x: int64(x), signed: true, y: y, code: boundsIndex})\n/home/marcus/go/src/github.com/grafana/grafana/pkg/services/alerting/extractor.go:119 (0x14a6b32)\n\t(*DashAlertExtractor).getAlertFromPanels: unit := unitFormatRegex.FindAllString(rawFor, 1)[0]\n/home/marcus/go/src/github.com/grafana/grafana/pkg/services/alerting/extractor.go:239 (0x14a700f)\n\t(*DashAlertExtractor).extractAlerts: a, err := e.getAlertFromPanels(dashboardJSON, validateFunc, logTranslationFailures)\n/home/marcus/go/src/github.com/grafana/grafana/pkg/services/alerting/extractor.go:254 (0x14a721b)\n\t(*DashAlertExtractor).ValidateAlerts: _, err := e.extractAlerts(func(alert *models.Alert) bool {\n/home/marcus/go/src/github.com/grafana/grafana/pkg/services/dashboards/dashboard_service.go:174 (0x158ea8b)\n\tglob..func4: return extractor.ValidateAlerts()\n/home/marcus/go/src/github.com/grafana/grafana/pkg/services/dashboards/dashboard_service.go:115 (0x158b1b1)\n\t(*dashboardServiceImpl).buildSaveDashboardCommand: if err := validateAlerts(dash, dto.User); err != nil {\n/home/marcus/go/src/github.com/grafana/grafana/pkg/services/dashboards/dashboard_service.go:280 (0x158c164)\n\t(*dashboardServiceImpl).SaveDashboard: cmd, err := dr.buildSaveDashboardCommand(dto, true, !allowUiUpdate)\n/home/marcus/go/src/github.com/grafana/grafana/pkg/api/dashboard.go:294 (0x1e1ae61)\n\t(*HTTPServer).PostDashboard: dashboard, err := dashSvc.SaveDashboard(dashItem, allowUiUpdate)\n/usr/local/go/src/reflect/value.go:476 (0x4ab186)\n\tValue.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))\n/usr/local/go/src/reflect/value.go:337 (0x4aa658)\n\tValue.Call: return v.call(\"Call\", in)\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x1013f36)\n\t(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x10138b1)\n\t(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())\n/home/marcus/go/src/github.com/grafana/grafana/pkg/api/routing/routing.go:18 (0x14d526d)\n\tWrap.func1: val, err := c.Invoke(action)\n/usr/local/go/src/reflect/value.go:476 (0x4ab186)\n\tValue.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))\n/usr/local/go/src/reflect/value.go:337 (0x4aa658)\n\tValue.Call: return v.call(\"Call\", in)\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x1013f36)\n\t(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x10138b1)\n\t(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x101629c)\n\t(*Context).run: vals, err := ctx.Invoke(ctx.handler())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:115 (0x1535f45)\n\t(*Context).Next: ctx.run()\n/home/marcus/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:54 (0x1535f30)\n\tRequestMetrics.func1.1: c.Next()\n/usr/local/go/src/reflect/value.go:476 (0x4ab186)\n\tValue.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))\n/usr/local/go/src/reflect/value.go:337 (0x4aa658)\n\tValue.Call: return v.call(\"Call\", in)\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x1013f36)\n\t(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x10138b1)\n\t(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x101629c)\n\t(*Context).run: vals, err := ctx.Invoke(ctx.handler())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:115 (0x1536c68)\n\t(*Context).Next: ctx.run()\n/home/marcus/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 (0x1536c5b)\n\tRequestTracing.func1: c.Next()\n/usr/local/go/src/reflect/value.go:476 (0x4ab186)\n\tValue.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))\n/usr/local/go/src/reflect/value.go:337 (0x4aa658)\n\tValue.Call: return v.call(\"Call\", in)\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x1013f36)\n\t(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x10138b1)\n\t(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x101629c)\n\t(*Context).run: vals, err := ctx.Invoke(ctx.handler())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:115 (0x1535dc4)\n\t(*Context).Next: ctx.run()\n/home/marcus/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:166 (0x1535db7)\n\tRecovery.func1: c.Next()\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:81 (0x1016112)\n\tContextInvoker.Invoke: invoke(params[0].(*Context))\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:157 (0x1013c31)\n\t(*injector).fastInvoke: return f.Invoke(in)\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:135 (0x10139a4)\n\t(*injector).Invoke: return inj.fastInvoke(v, t, t.NumIn())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x101629c)\n\t(*Context).run: vals, err := ctx.Invoke(ctx.handler())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:115 (0x1533e71)\n\t(*Context).Next: ctx.run()\n/home/marcus/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:35 (0x1533e45)\n\tLogger.func1: c.Next()\n/usr/local/go/src/reflect/value.go:476 (0x4ab186)\n\tValue.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))\n/usr/local/go/src/reflect/value.go:337 (0x4aa658)\n\tValue.Call: return v.call(\"Call\", in)\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x1013f36)\n\t(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x10138b1)\n\t(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x101629c)\n\t(*Context).run: vals, err := ctx.Invoke(ctx.handler())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/router.go:187 (0x1027cf0)\n\t(*Router).Handle.func1: c.run()\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/router.go:303 (0x1022445)\n\t(*Router).ServeHTTP: h(rw, req, p)\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/macaron.go:220 (0x101b56c)\n\t(*Macaron).ServeHTTP: m.Router.ServeHTTP(rw, req)\n/usr/local/go/src/net/http/server.go:2887 (0x71b7a2)\n\tserverHandler.ServeHTTP: handler.ServeHTTP(rw, req)\n/usr/local/go/src/net/http/server.go:1952 (0x716ccc)\n\t(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)\n/usr/local/go/src/runtime/asm_amd64.s:1371 (0x47b320)\n\tgoexit: BYTE\t$0x90\t// NOP\n"
```

```json
{
  "alert": {
    "alertRuleTags": {
      "key1": "value1"
    },
    "conditions": [
      {
        "evaluator": {
          "params": [
            0
          ],
          "type": "gt"
        },
        "operator": {
          "type": "and"
        },
        "query": {
          "params": [
            "A",
            "5m",
            "now"
          ]
        },
        "reducer": {
          "params": [],
          "type": "avg"
        },
        "type": "query"
      },
      {
        "evaluator": {
          "params": [
            0
          ],
          "type": "gt"
        },
        "operator": {
          "type": "and"
        },
        "query": {
          "params": [
            "C",
            "5m",
            "now"
          ]
        },
        "reducer": {
          "params": [],
          "type": "avg"
        },
        "type": "query"
      }
    ],
    "executionErrorState": "keep_state",
    "for": "0",
    "frequency": "10s",
    "handler": 1,
    "message": "Test",
    "name": "Panel Title alert",
    "noDataState": "ok",
    "notifications": []
  },
  "aliasColors": {},
  "bars": false,
  "dashLength": 10,
  "dashes": false,
  "datasource": "gdev-testdata",
  "fieldConfig": {
    "defaults": {
      "links": []
    },
    "overrides": []
  },
  "fill": 1,
  "fillGradient": 0,
  "gridPos": {
    "h": 9,
    "w": 12,
    "x": 0,
    "y": 8
  },
  "hiddenSeries": false,
  "id": 2,
  "interval": "1m",
  "legend": {
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "show": true,
    "total": false,
    "values": false
  },
  "lines": true,
  "linewidth": 1,
  "maxDataPoints": 100,
  "nullPointMode": "null",
  "options": {
    "alertThreshold": true
  },
  "percentage": false,
  "pluginVersion": "7.5.0-pre",
  "pointradius": 2,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "spaceLength": 10,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "refId": "A",
      "scenarioId": "csv_metric_values",
      "stringInput": "200,445,100,150,200,220,190"
    },
    {
      "refId": "C",
      "scenarioId": "csv_metric_values",
      "stringInput": "200,445,100,150,200,220,190"
    }
  ],
  "thresholds": [
    {
      "value": 0,
      "op": "gt",
      "visible": true,
      "fill": true,
      "line": true,
      "colorMode": "critical"
    }
  ],
  "timeFrom": null,
  "timeRegions": [],
  "timeShift": null,
  "title": "Panel Title",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  }
}
```

File: pkg/services/alerting/extractor.go (hunk 3 above)
Comment (dsotirakis) [reply pkg/services/alerting/extractor.go]: Oh, okay I've misunderstood your comment:

> Sounds good. However, you wouldn't know for what field this error happened which the failure of time.ParseDuration at least includes.

Will add a better message there :) Thanks!

File: public/app/features/alerting/partials/alert_tab.html [hunk 8]
```diff
@@ -20,6 +20,7 @@ <h4 class="section-heading">Rule</h4>
           type="text"
           ng-model="ctrl.alert.frequency"
           ng-blur="ctrl.checkFrequency()"
+          ng-pattern="/(^\d+([dhms])$)|(0)|(^$)/"
```
Comment (marefr) [inline public/app/features/alerting/partials/alert_tab.html:23]: Frequency shouldn't allow an empty or zero input. Sorry if I wasn't clear on that.

File: pkg/services/alerting/rule.go [hunk 9]
```diff
@@ -72,20 +88,22 @@ func (e ValidationError) Error() string {
 	return fmt.Sprintf("alert validation error: %s", extraInfo)
 }
 
-var (
-	valueFormatRegex = regexp.MustCompile(`^\d+`)
-	unitFormatRegex  = regexp.MustCompile(`\w{1}$`)
-)
+func getTimeDurationStringToSeconds(str string) (int64, error) {
+	if str == "0" || str == "" {
```
Comment (marefr) [inline pkg/services/alerting/rule.go:92]: Frequency shouldn't allow an empty or zero input. Sorry if I wasn't clear on that.

File: pkg/services/alerting/rule_test.go [hunk 10]
```diff
@@ -28,11 +27,12 @@ func TestAlertRuleFrequencyParsing(t *testing.T) {
...
 		{input: "1h", result: 3600},
 		{input: "1d", result: 86400},
-		{input: "1o", result: 1},
+		{input: "1o", err: ErrWrongUnitFormat},
 		{input: "0s", err: ErrFrequencyCannotBeZeroOrLess},
 		{input: "0m", err: ErrFrequencyCannotBeZeroOrLess},
 		{input: "0h", err: ErrFrequencyCannotBeZeroOrLess},
-		{input: "0", err: ErrFrequencyCannotBeZeroOrLess},
+		{input: "0", result: 0},
+		{input: "", result: 0},
```
Comment (marefr) [inline pkg/services/alerting/rule_test.go:35]: Frequency shouldn't allow an empty or zero input. Sorry if I wasn't clear on that.

**Review by marefr — CHANGES_REQUESTED** [review]
For-changes looks good, but frequency shouldn't allow an empty or zero input. See comments

**Comment by dsotirakis** [comment]
@marefr No problem, changing :)

**Review by marefr — CHANGES_REQUESTED** [review]
Pushed a fix for frequency. Using ng-pattern did override the ng-blur.

Managed to create a panic by inserting `10` in the for field:
```
EROR[04-12|11:41:29] Request error                            logger=context userId=1 orgId=1 uname=admin error="runtime error: index out of range [0] with length 0" stack="/usr/local/go/src/runtime/panic.go:88 (0x43e124)\n\tgoPanicIndex: panic(boundsError{x: int64(x), signed: true, y: y, code: boundsIndex})\n/home/marcus/go/src/github.com/grafana/grafana/pkg/services/alerting/extractor.go:120 (0x14bb212)\n\t(*DashAlertExtractor).getAlertFromPanels: unit := unitFormatRegex.FindAllString(rawFor, 1)[0]\n/home/marcus/go/src/github.com/grafana/grafana/pkg/services/alerting/extractor.go:241 (0x14bb6ef)\n\t(*DashAlertExtractor).extractAlerts: a, err := e.getAlertFromPanels(dashboardJSON, validateFunc, logTranslationFailures)\n/home/marcus/go/src/github.com/grafana/grafana/pkg/services/alerting/extractor.go:256 (0x14bb8fb)\n\t(*DashAlertExtractor).ValidateAlerts: _, err := e.extractAlerts(func(alert *models.Alert) bool {\n/home/marcus/go/src/github.com/grafana/grafana/pkg/services/dashboards/dashboard_service.go:174 (0x15a5aeb)\n\tglob..func4: return extractor.ValidateAlerts()\n/home/marcus/go/src/github.com/grafana/grafana/pkg/services/dashboards/dashboard_service.go:115 (0x15a2011)\n\t(*dashboardServiceImpl).buildSaveDashboardCommand: if err := validateAlerts(dash, dto.User); err != nil {\n/home/marcus/go/src/github.com/grafana/grafana/pkg/services/dashboards/dashboard_service.go:280 (0x15a2fc4)\n\t(*dashboardServiceImpl).SaveDashboard: cmd, err := dr.buildSaveDashboardCommand(dto, true, !allowUiUpdate)\n/home/marcus/go/src/github.com/grafana/grafana/pkg/api/dashboard.go:294 (0x1e69f21)\n\t(*HTTPServer).PostDashboard: dashboard, err := dashSvc.SaveDashboard(dashItem, allowUiUpdate)\n/usr/local/go/src/reflect/value.go:476 (0x4ab1c6)\n\tValue.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))\n/usr/local/go/src/reflect/value.go:337 (0x4aa698)\n\tValue.Call: return v.call(\"Call\", in)\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x10230b6)\n\t(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x1022a31)\n\t(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())\n/home/marcus/go/src/github.com/grafana/grafana/pkg/api/routing/routing.go:18 (0x14e994d)\n\tWrap.func1: val, err := c.Invoke(action)\n/usr/local/go/src/reflect/value.go:476 (0x4ab1c6)\n\tValue.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))\n/usr/local/go/src/reflect/value.go:337 (0x4aa698)\n\tValue.Call: return v.call(\"Call\", in)\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x10230b6)\n\t(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x1022a31)\n\t(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x102541c)\n\t(*Context).run: vals, err := ctx.Invoke(ctx.handler())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:115 (0x154c965)\n\t(*Context).Next: ctx.run()\n/home/marcus/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:54 (0x154c950)\n\tRequestMetrics.func1.1: c.Next()\n/usr/local/go/src/reflect/value.go:476 (0x4ab1c6)\n\tValue.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))\n/usr/local/go/src/reflect/value.go:337 (0x4aa698)\n\tValue.Call: return v.call(\"Call\", in)\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x10230b6)\n\t(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x1022a31)\n\t(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x102541c)\n\t(*Context).run: vals, err := ctx.Invoke(ctx.handler())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:115 (0x154d688)\n\t(*Context).Next: ctx.run()\n/home/marcus/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 (0x154d67b)\n\tRequestTracing.func1: c.Next()\n/usr/local/go/src/reflect/value.go:476 (0x4ab1c6)\n\tValue.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))\n/usr/local/go/src/reflect/value.go:337 (0x4aa698)\n\tValue.Call: return v.call(\"Call\", in)\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x10230b6)\n\t(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x1022a31)\n\t(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x102541c)\n\t(*Context).run: vals, err := ctx.Invoke(ctx.handler())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:115 (0x154c7e4)\n\t(*Context).Next: ctx.run()\n/home/marcus/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:166 (0x154c7d7)\n\tRecovery.func1: c.Next()\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:81 (0x1025292)\n\tContextInvoker.Invoke: invoke(params[0].(*Context))\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:157 (0x1022db1)\n\t(*injector).fastInvoke: return f.Invoke(in)\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:135 (0x1022b24)\n\t(*injector).Invoke: return inj.fastInvoke(v, t, t.NumIn())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x102541c)\n\t(*Context).run: vals, err := ctx.Invoke(ctx.handler())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:115 (0x154a891)\n\t(*Context).Next: ctx.run()\n/home/marcus/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:35 (0x154a865)\n\tLogger.func1: c.Next()\n/usr/local/go/src/reflect/value.go:476 (0x4ab1c6)\n\tValue.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))\n/usr/local/go/src/reflect/value.go:337 (0x4aa698)\n\tValue.Call: return v.call(\"Call\", in)\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x10230b6)\n\t(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil\n/home/marcus/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x1022a31)\n\t(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x102541c)\n\t(*Context).run: vals, err := ctx.Invoke(ctx.handler())\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/router.go:187 (0x1036e70)\n\t(*Router).Handle.func1: c.run()\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/router.go:303 (0x10315c5)\n\t(*Router).ServeHTTP: h(rw, req, p)\n/home/marcus/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/macaron.go:220 (0x102a6ec)\n\t(*Macaron).ServeHTTP: m.Router.ServeHTTP(rw, req)\n/usr/local/go/src/net/http/server.go:2887 (0x71bb22)\n\tserverHandler.ServeHTTP: handler.ServeHTTP(rw, req)\n/usr/local/go/src/net/http/server.go:1952 (0x71704c)\n\t(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)\n/usr/local/go/src/runtime/asm_amd64.s:1371 (0x47b320)\n\tgoexit: BYTE\t$0x90\t// NOP\n"
```

**Comment by dsotirakis** [comment]
@marefr Fixed, extracted a func to `rule.go` so we can be consistent having tests.

**Review by marefr — APPROVED** [review]
LGTM :tada:
