### PR TITLE
CloudWatch: Fix labels for raw metric search queries

### LINKED ISSUE #86426: Alert rules with CloudWatch metrics seems to evaluate both builder and code conditions
### What happened?

We started to get No Data alerts yesterday on our alert rules using AWS CloudWatch Metrics. Something seems to be up with how these alert rules are evaluated, or that's my best guess after troubleshooting. 

When querying an alert condition like:
`SEARCH('MetricName="ApproximateNumberOfMessagesVisible" AND ("AWS/SQS") AND QueueName=my-queue-prefix NOT QueueName=dlq', 'Sum') ` using the Code editor the result is now no data. If I go to the explorer and query the exact same query, I get data. The datasource is the same, and so is the query period.
Going back to the alert condition and entering Builder editor, choosing any queue name as a dimension I get data. If I now go back to the Code editor (the query is still the same) and run the query, I now get data.

Saving this alert rule and waiting for the next evaluation period, the alert triggers with a no data alert. Going back into the alert again and running the query I do get data.

If I now go into builder mode, enter any queue name as a dimension (or remove all dimensions) go back to code editor mode and save the rule, wait for the next evaluation period, it now transitions into an error stating:
`invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}`
If I enter another metric in builder mode, enter code mode and hit save, and wait for the next evaluation it then transitions into an error state like:
`No error message provided`

Have builder and code mode started to interfere with each other during evaluation maybe?

### What did you expect to happen?

The code edited alert condition to evaluate

### Did this work before?

Yes

### How do we reproduce it?

1. Create an alert rule using AWS CloudWatch source provider and have some queues in active state in AWS (so it produces metrics). Use the search expression `SEARCH('MetricName="ApproximateNumberOfMessagesVisible" AND ("AWS/SQS") AND QueueName=my-queue-prefix NOT QueueName=dlq', 'Sum')` where `my-queue-prefix` partially match some queue names. Hit run queries.
2. Go to builder mode enter the equivalent query. In Dimensions add QueueName and *. Run the query, it should return data.
3. Go back to Code mode and hit run queries -> no data.
4. Go back to builder mode, remove the Dimension, and then go back to Code mode and run queries -> data!
5. Save the rule and wait for it evaluate -> it triggers an error state as described above.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana v11.1.0-69372 (51da96d94e)
OS: Windows 11
Browser: Chrome Version 123.0.6312.122 (Official Build) (64-bit)

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

AWS CloudWatch

### PR DESCRIPTION
**Pull request by iwysiu**
**What is this feature?**
Fixes alerting on metric search queries written with the code editor. We were only adding labels when the query had dimensions, which is only true for builder queries, but this pr adds the cloudwatch label as "series" to it.

For reviewing: You can reproduce the bug using Kevin's reproduction in the original issue, the metric search query: `SEARCH('MetricName="ResourceCount" AND ("AWS/Usage") AND Resource=TargetsPer
  NOT QueueName=TargetsPerNetworkLoadBalancer', 'Average')` and if you can see that it doesn't have labels in the reduce step and errors when evaluated.

**Which issue(s) does this PR fix?**:

Fixes #86426 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/tsdb/cloudwatch/response_parser_test.go [hunk 1]
```diff
@@ -272,11 +274,13 @@ func Test_buildDataFrames_parse_label_to_name_and_labels(t *testing.T) {
 		require.NoError(t, err)
 
 		assert.Equal(t, "some label lb3", frames[0].Name)
+		assert.Equal(t, "some label lb3", frames[0].Fields[1].Labels["Series"])
 		assert.Equal(t, "balancer 1", frames[0].Fields[1].Labels["LoadBalancer"])
 		assert.Equal(t, "inst1", frames[0].Fields[1].Labels["InstanceType"])
 		assert.Equal(t, "tg", frames[0].Fields[1].Labels["TargetGroup"])
 
 		assert.Equal(t, "some label lb4", frames[1].Name)
+		assert.Equal(t, "some label lb4", frames[1].Fields[1].Labels["Series"])
```
Comment (iwysiu) [inline pkg/tsdb/cloudwatch/response_parser_test.go:283]: I decided not to add this for all the parser tests because it felt redundant and it wasn't the thing those tests were checking, but I can add them if we'd prefer

**Review by kevinwcyu — APPROVED** [review]
