### PR TITLE
Unified Alerting, Issue 41156: Clean up expired silences.

### LINKED ISSUE #41156: Expired silences are NOT removed after 5 days
**What happened**:
Expired silences are not removed after 5 days, see screenshot.
The screenshot was taken on Nov 1st, 2021, which is well over 5 days past the expiration of some of these silences, so they should have been removed.

**What you expected to happen**:
I expect the expired silences to be removed after 5 days - just like the message states.

**How to reproduce it (as minimally and precisely as possible)**:
Create any silences, let them expire and wait 5 days to see them NOT being removed.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Official Grafana Docker image 
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by joeblubaugh**
**What this PR does / why we need it**:
Expired silences older than the retention period were not being cleaned
up. The root problem was that AlertManager overrides Prometheus's
silence maintenance function and was not calling Silences.GC() in the
overriden function.

**Which issue(s) this PR fixes**: 

Fixes #41156

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/ngalert/notifier/alertmanager.go [hunk 1]
```diff
@@ -60,6 +58,10 @@ const (
 	memoryAlertsGCInterval = 30 * time.Minute
 )
 
+// How long should we keep silences and notification entries on-disk after they've served their purpose.
```
Comment (joeblubaugh) [inline pkg/services/ngalert/notifier/alertmanager.go:61]: I'm not crazy about doing this, but I need to modify these numbers so that tests can take a reasonable amount of time. See https://github.com/prometheus/alertmanager/issues/2850 for another approach that could make testing faster without changing anything in the source file here.

One way to permit them to be modified for testing purposes would be to make them an argument to one of our functions - perhaps newAlertManager. I need to explore whether that would mess with all the wire magic that I don't yet understand.

File: pkg/services/ngalert/notifier/alertmanager.go [hunk 2]
```diff
@@ -185,7 +187,13 @@ func newAlertmanager(ctx context.Context, orgID int64, cfg *setting.Cfg, store s
 
 	am.wg.Add(1)
 	go func() {
-		am.silences.Maintenance(15*time.Minute, silencesFilePath, am.stopc, func() (int64, error) {
+		am.silences.Maintenance(silenceMaintenanceInterval, silencesFilePath, am.stopc, func() (int64, error) {
+			// Delete silences older than the retention period.
+			if _, err := am.silences.GC(); err != nil {
```
Comment (joeblubaugh) [inline pkg/services/ngalert/notifier/alertmanager.go:192]: This is the bug.

File: pkg/services/ngalert/notifier/silences.go [hunk 3]
```diff
@@ -75,6 +76,14 @@ func (am *Alertmanager) GetSilence(silenceID string) (apimodels.GettableSilence,
 
 // CreateSilence persists the provided silence and returns the silence ID if successful.
 func (am *Alertmanager) CreateSilence(ps *apimodels.PostableSilence) (string, error) {
+	// Validate our silence to avoid segfaults
```
Comment (joeblubaugh) [inline pkg/services/ngalert/notifier/silences.go:79]: I found this problem while writing tests, because I didn't know I had to set all the fields. I was causing segfaults, even. See: https://github.com/prometheus/alertmanager/issues/2851

If we validate somewhere further upstream, we can drop this.

Comment (yuri-tceretian) [reply pkg/services/ngalert/notifier/silences.go:79]: I think this validation needs to be done on the controller level for better separation of API\DTO layers. We can address it later.

**Review by yuri-tceretian — APPROVED** [review]
LGTM! 👍🏻

File: pkg/services/ngalert/notifier/alertmanager.go [hunk 4]
```diff
@@ -185,7 +187,13 @@ func newAlertmanager(ctx context.Context, orgID int64, cfg *setting.Cfg, store s
...
+				return 0, err
```
Comment (gotjosh) [inline pkg/services/ngalert/notifier/alertmanager.go:193]: I'm not sure we should return here. If we do we're losing durability by not persisting the silences. How do you feel about logging and carrying on? Worst-case scenario we would just try again on the next interval and the problem might be fixed by then.

File: pkg/services/ngalert/notifier/alertmanager_test.go [hunk 5]
```diff
@@ -346,3 +348,80 @@ func TestPutAlert(t *testing.T) {
...
+	assert := assert.New(t)
+
+	// TODO: We have to use a real clock because Prometheus doesn't support clock
+	// injection. So modify the retention constant. This isn't great - we should
+	// make this an argument to the alertmanager so we can safely change it.
+	oldRetention := retentionNotificationsAndSilences
+	retentionNotificationsAndSilences = 30 * time.Millisecond
+	oldMaintenance := silenceMaintenanceInterval
+	silenceMaintenanceInterval = 15 * time.Millisecond
+	defer func() {
```
Comment (gotjosh) [inline pkg/services/ngalert/notifier/alertmanager_test.go:367]: nit: perhaps use `t.Cleanup`?

File: pkg/services/ngalert/notifier/alertmanager_test.go [hunk 6]
```diff
@@ -346,3 +348,80 @@ func TestPutAlert(t *testing.T) {
...
+	require.NoError(err)
+	assert.Len(found, 3)
+
+	// Wait again for the expired silence to fall out of retention.
+	<-tick.C
+
+	// So, what silences do we have now?
+	found, err = am.ListSilences(nil)
+	require.NoError(err)
+	require.Len(found, 2)
```
Comment (gotjosh) [inline pkg/services/ngalert/notifier/alertmanager_test.go:426]:
```suggestion
	// So, what silences do we have now?
	require.Eventually(func() bool {
		found, err := am.ListSilences(nil)
		return err == nil && len(found) == 3
	}, 1500*time.Millisecond, 500*time.Millisecond)

	// So, what silences do we have now?
	require.Eventually(func() bool {
		found, err := am.ListSilences(nil)
		return err == nil && len(found) == 2
	}, 4*time.Second, 500*time.Millisecond)
```

The use of `require.Eventually` is technically a nit, but if possible, I would avoid tests that never timeout (L421). If you decide to stick with your approach of using the ticker, then how do you feel about adding a timeout?

File: pkg/services/ngalert/notifier/silences.go (hunk 3 above)
Comment (gotjosh) [reply pkg/services/ngalert/notifier/silences.go:79]: Great catch! I would split this into a separate PR so that we can discuss this individually.

File: pkg/services/ngalert/notifier/alertmanager_test.go [hunk 7]
```diff
@@ -346,3 +348,80 @@ func TestPutAlert(t *testing.T) {
...
+// our alert silencing functionality, so we rely on its tests. However, we
+// implement a custom maintenance function for silences, because we snapshot
+// our data differently, so we test that functionality.
+func TestSilenceCleanup(t *testing.T) {
+	require := require.New(t)
+	assert := assert.New(t)
+
+	// TODO: We have to use a real clock because Prometheus doesn't support clock
+	// injection. So modify the retention constant. This isn't great - we should
+	// make this an argument to the alertmanager so we can safely change it.
```
Comment (gotjosh) [inline pkg/services/ngalert/notifier/alertmanager_test.go:362]: Unsure if this TODO is meant to be for this PR or the next one, but I would advise against leaving the TODO in the code if you don't plan to address this is your immediate next PR.

You already dropped a great issue on the Alertmanager repo, perhaps create one that references that in the Grafana side so that we can follow up?

**Review by gotjosh — COMMENTED** [review]
Fantastic sleuthing @joeblubaugh 👏. Please see my comment re the return which is my main concern.

File: pkg/services/ngalert/notifier/alertmanager_test.go (hunk 6 above)
Comment (joeblubaugh) [reply pkg/services/ngalert/notifier/alertmanager_test.go:426]: I didn't know about require.Eventually. Should definitely have a timeout here.

File: pkg/services/ngalert/notifier/alertmanager.go (hunk 1 above)
Comment (joeblubaugh) [reply pkg/services/ngalert/notifier/alertmanager.go:61]: After submitting this I found that Prometheus does a pretty ugly hack of overriding time.Now in their own tests, but I like that hack better than making these non-const package variables and manipulating them during tests. I'll make a similar change to this PR

File: pkg/services/ngalert/notifier/alertmanager.go (hunk 4 above)
Comment (joeblubaugh) [reply pkg/services/ngalert/notifier/alertmanager.go:193]: The only underlying way Prom fails here is if there's a zero expiration timestamp. I kind of hate that, because once you get invalid data you're doomed to fail forever.

I agree that continuing and snapshotting after this error is what I should be doing.

File: pkg/services/ngalert/notifier/alertmanager_test.go (hunk 7 above)
Comment (joeblubaugh) [reply pkg/services/ngalert/notifier/alertmanager_test.go:362]: https://github.com/grafana/grafana/discussions/46822

**Comment by joeblubaugh** [comment]
@gotjosh could you take one more look? I believe I've addressed all your questions

File: pkg/services/ngalert/notifier/alertmanager.go [hunk 8]
```diff
@@ -185,7 +187,14 @@ func newAlertmanager(ctx context.Context, orgID int64, cfg *setting.Cfg, store s
 
 	am.wg.Add(1)
 	go func() {
-		am.silences.Maintenance(15*time.Minute, silencesFilePath, am.stopc, func() (int64, error) {
+		am.silences.Maintenance(silenceMaintenanceInterval, silencesFilePath, am.stopc, func() (int64, error) {
+			// Delete silences older than the retention period.
+			if _, err := am.silences.GC(); err != nil {
+				am.logger.Error("Silence Garbage Collection Failed at %v: %v", time.Now(), err)
```
[the remark this answers is not in the document]
Comment (joeblubaugh) [reply pkg/services/ngalert/notifier/alertmanager.go:193]: Here's the follow-up : https://github.com/grafana/grafana/pull/46881
