### PR TITLE
Dashboard: Fix changes doesn't reflect after changing panel sizes in inspect JSON and click on apply

### LINKED ISSUE #34483: Panel Resize: Changes doesn't reflect after changing panel sizes in inspect JSON and click on apply
**What happened**: To edit the size of the panel with particular dimensions, I have to select the Inspect > Panel JSON and then adjust the width and height in JSON.  But the changes are not reflected even after clicking on apply. I have to save & reload the page to see the changes.

**What you expected to happen**: After applying size in  Inspect > Panel JSON the changes should reflect without dashboard save and reload.

**How to reproduce it (as minimally and precisely as possible)**: Go to panel JSON and edit the **h** and **w** in the following property of panel JSON:

 `"gridPos": {
   "h": 4,
   "w": 24,
   "x": 0,
   "y": 3
 },`

**Anything else we need to know?**: Able to reproduce in Play Grafana.

**Environment**: Any
- Grafana version:  7.2 and above
- Data source type & version: Any
- OS Grafana is installed on: Any
- User OS & Browser: Any
- Grafana plugins: ANy
- Others:

### PR DESCRIPTION
**Pull request by axelavargas**
**What this PR does / why we need it**:

When editing the size of the panel with particular dimensions through Inspect > Panel JSON, the changes were not reflected even after clicking on `apply`. Resizing only was possible using the mouse.

**Alternative Approach**

After discarding the approach of saving the `layout` in the state, I have found another approach(a simple one) that can work as a temporary fix, this approach will not cover changing the plugin type or the panel id but it will keep the gridPos of each panel updated in the dashboard grid.

From `InspectJSONTab` we will check if the `panel.gridPos` changed and if the dashboard needs to re-render, if yes we will trigger the `DashboardPanelsChangedEvent` that will update the positioning.

panelResizeProgramatically

**Which issue(s) this PR fixes**:

Fixes #34483

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/inspector/InspectJSONTab.tsx [hunk 1]
```diff
@@ -105,8 +105,12 @@ export class InspectJSONTab extends PureComponent<Props, State> {
           appEvents.emit(AppEvents.alertError, ['Unable to apply']);
         } else {
           const updates = JSON.parse(this.state.text);
+          const shouldUpdateGridPositionLayout = JSON.stringify(updates?.gridPos) !== JSON.stringify(panel?.gridPos);
```
Comment (hugohaggmark) [inline public/app/features/inspector/InspectJSONTab.tsx:108]: nit: Probably not an issue here but you can use `safeParseJson` and `safeStringifyValue` to be on the safe side here.
https://github.com/grafana/grafana/blob/36925ef5216e0de7f2c09c4f9540442095e0bf5e/public/app/core/utils/explore.ts#L183
https://github.com/grafana/grafana/blob/36925ef5216e0de7f2c09c4f9540442095e0bf5e/public/app/core/utils/explore.ts#L195

File: public/app/features/inspector/InspectJSONTab.tsx [hunk 2]
```diff
@@ -105,8 +105,12 @@ export class InspectJSONTab extends PureComponent<Props, State> {
...
           panel!.restoreModel(updates);
           panel!.refresh();
+          if (shouldUpdateGridPositionLayout) {
+            panel!.updateGridPositionLayout();
+          }
```
Comment (hugohaggmark) [inline public/app/features/inspector/InspectJSONTab.tsx:113]: Hmm, I wonder if this logic shouldn't belong to PanelModel? I mean maybe PanelModel should decide if it should publish the event or not. WDYT?

File: public/app/features/dashboard/state/PanelModel.ts [hunk 3]
```diff
@@ -315,6 +316,11 @@ export class PanelModel implements DataConfigSource {
     this.events.publish(new RefreshEvent());
   }
 
+  //this is needed when layout is updated programatically (i.e using the inspectJsonTab)
+  updateGridPositionLayout() {
+    this.events.publish(new PanelGridPositionLayoutEvent({ gridPos: this.gridPos, panelId: this.id }));
```
Comment (hugohaggmark) [inline public/app/features/dashboard/state/PanelModel.ts:321]: This is something that burned me last week, when in panelEdit `this.id` is a "random" number. Maybe use this instead:
```suggestion
    this.events.publish(new PanelGridPositionLayoutEvent({ gridPos: this.gridPos, panelId: this.editSourceId ?? this.id }));
```

File: public/app/features/dashboard/dashgrid/DashboardGrid.tsx [hunk 4]
```diff
@@ -140,21 +154,33 @@ export class DashboardGrid extends PureComponent<Props> {
...
 
     this.props.dashboard.sortPanelsByGridPos();
 
-    // Call render() after any changes.  This is called when the layout loads
-    this.forceUpdate();
+    // Call render() after any changes.  This is called when the initial layout loads
+    // After layout is updated via setState
+    if (this.state.shouldForceUpdate) {
+      this.forceUpdate();
+    }
```
Comment (hugohaggmark) [inline public/app/features/dashboard/dashgrid/DashboardGrid.tsx:183]: Out of curiosity, this changes the intent of the previous implementation as it would always force render previously. I'm just asking if this is an intended change and if you can explain the reason?

**Review by hugohaggmark — COMMENTED** [review]
I think this might be a good approach but to be honest this is not my area of expertise so I would await more feedback from @torkelo.

File: public/app/features/dashboard/dashgrid/DashboardGrid.tsx (hunk 4 above)
Comment (axelavargas) [reply public/app/features/dashboard/dashgrid/DashboardGrid.tsx:183]: Indeed 😄 ,  before was needed because the `layout` property was not part of the props or the state, and the component was not being re-render when the user was changing the panel sizes.

On my current implementation when I added the `layout` to the state it was re-rendering twice (First, doing `setState` of layout, and a second time when the `onLayoutChange` was called.

Still, I had to keep this `forceUpdate` for the initial render, when the component is mounted and the layout loads.

File: public/app/features/dashboard/state/PanelModel.ts (hunk 3 above)
Comment (axelavargas) [reply public/app/features/dashboard/state/PanelModel.ts:321]: 🙌🏾 thanks a lot, I will take a look

File: public/app/features/inspector/InspectJSONTab.tsx (hunk 2 above)
Comment (axelavargas) [reply public/app/features/inspector/InspectJSONTab.tsx:113]: That's a good point, so do you mean: to send the `updates` to a function in the `PanelModel`, and there we made the decision? right?

**Comment by axelavargas** [comment]
> I think this might be a good approach but to be honest this is not my area of expertise so I would await more feedback from @torkelo.

Thank you @hugohaggmark for the review,  I will wait for more feedback :)

File: public/app/features/inspector/InspectJSONTab.tsx (hunk 2 above)
Comment (hugohaggmark) [reply public/app/features/inspector/InspectJSONTab.tsx:113]: Yes, exactly

File: public/app/features/dashboard/dashgrid/DashboardGrid.tsx (hunk 4 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/dashgrid/DashboardGrid.tsx:183]: Ok, thanks for a great explanation 👍

File: public/app/features/inspector/InspectJSONTab.tsx (hunk 1 above)
Comment (torkelo) [reply public/app/features/inspector/InspectJSONTab.tsx:108]: is not lodash isEqual a better fit than comparing json strings?

**Review by dprokop — APPROVED** [review]
Tested and works as expected, good stuff @axelavargas!

File: public/app/features/inspector/InspectJSONTab.tsx (hunk 1 above)
Comment (axelavargas) [reply public/app/features/inspector/InspectJSONTab.tsx:108]: @torkelo yes, is a better fit, I  was a bit unsure to use lodash (_I remember the conversation about not using lodash, we still need to define which ones we want to keep using._) I will change it here to `isEqual` :), btw @torkelo do you having any feedback regarding the approach?

**Review by torkelo — COMMENTED** [review]
Seeing crashed when I add panels, or expand rows.

**Comment by axelavargas** [comment]
> I am not sure what the best solution is here, as you can change anything in the JSON and this only addresses a specific case of grid pos. So if you change panel id, or panel type things are not working and to fix that would require a very different solution than this.

that's a very good point! I will think if there is another approach that can take that into account.

**Comment by axelavargas** [comment]
> Seeing crashed when I add panels, or expand rows.

Thank you 🙌🏾 , I will take a look!

**Comment by torkelo** [comment]
But supporting changing panel type & id (ie everything) is not trivial, I have tried and failed, due to complex state & timing issues

**Comment by axelavargas** [comment]
I have updated the approach:

From InspectJSONTab we will check if the panel.gridPos changed and if the dashboard needs to re-render, if yes we will trigger the `DashboardPanelsChangedEvent` that will update the positioning, this can work as a temporary fix, because the approach doesn't cover changing the plugin type or the panel id but it will keep the gridPos of each panel updated in the dashboard grid.

File: public/app/features/inspector/InspectJSONTab.tsx [hunk 5]
```diff
@@ -105,6 +105,7 @@ export class InspectJSONTab extends PureComponent<Props, State> {
           appEvents.emit(AppEvents.alertError, ['Unable to apply']);
         } else {
           const updates = JSON.parse(this.state.text);
+          dashboard!.shouldUpdateDashboardPanelFromJSON(updates, panel!);
```
Comment (hugohaggmark) [inline public/app/features/inspector/InspectJSONTab.tsx:108]: I'm not an expert in this area, but does `panel.refresh()` get invoked twice now that the dashboard grid is force updated?

**Review by hugohaggmark — COMMENTED** [review]
I think this approach looks a lot simpler compared to the last solution, I like it. But again this is all outside of my comfort area of the code base.

**Comment by axelavargas** [comment]
I have created another issue to work in the scenario of changing the `type` #35479

File: public/app/features/inspector/InspectJSONTab.tsx (hunk 5 above)
Comment (axelavargas) [reply public/app/features/inspector/InspectJSONTab.tsx:108]: Hey @hugohaggmark :), that's a good point, I tested and double-checked the code, and it seems working fine(without being invoked twice). I think when we apply changes in the JSON  the `panel.refresh` is only called in `line 110 - InspectJSONTab`  and when we trigger the dashboard event and we force a re-render we are not calling it on the `DashboardGrid` component.

Comment (hugohaggmark) [reply public/app/features/inspector/InspectJSONTab.tsx:108]: 👍

File: public/app/features/dashboard/dashgrid/DashboardGrid.tsx [hunk 6]
```diff
@@ -153,8 +164,11 @@ export class DashboardGrid extends PureComponent<Props> {
 
     this.props.dashboard.sortPanelsByGridPos();
 
-    // Call render() after any changes.  This is called when the layout loads
-    this.forceUpdate();
+    // Call render() after any changes.  This is called when the initial layout loads
+    if (this.state.shouldForceUpdate) {
```
Comment (dprokop) [inline public/app/features/dashboard/dashgrid/DashboardGrid.tsx:168]: Got a bit confused with the name of this state property. Was expecting it to be modified when force update is needed, but apparently it's only to indicate initial forceUpdate. Maybe we could call it `isInitialized` or sth like that?

**Review by dprokop — APPROVED** [review]
I think I like the new approach better compared to the one with events 👍

File: public/app/features/dashboard/dashgrid/DashboardGrid.tsx (hunk 6 above)
Comment (axelavargas) [reply public/app/features/dashboard/dashgrid/DashboardGrid.tsx:168]: That's definitely a better name 🙌🏾

File: public/app/features/dashboard/dashgrid/DashboardGrid.tsx [hunk 7]
```diff
@@ -153,8 +164,11 @@ export class DashboardGrid extends PureComponent<Props> {
 
     this.props.dashboard.sortPanelsByGridPos();
 
-    // Call render() after any changes.  This is called when the layout loads
-    this.forceUpdate();
+    // Call render() after any changes.  This is called when the initial layout loads
+    if (!this.state.isLayoutInitialized) {
+      this.forceUpdate();
+      this.setState({ isLayoutInitialized: true });
+    }
```
Comment (torkelo) [inline public/app/features/dashboard/dashgrid/DashboardGrid.tsx:171]: Can you describe why new condition exists? dont we always need to re-render onLayoutChange ?

Comment (axelavargas) [reply public/app/features/dashboard/dashgrid/DashboardGrid.tsx:171]: Not really, `onLayoutChange` is meant to be a mechanism to save the layout after every drag or resize stop. The library itself should take care of the re-rendering part if we update the `layout` object, I think this condition was here before because of this bug https://github.com/react-grid-layout/react-grid-layout/issues/670  (it was solved in early versions), check this comment https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/dashgrid/DashboardGrid.tsx#L167 , yet we still need to keep forceUpdate when the layout is initially built (I suspect we are doing something with lazy loading or something because when I removed this `forceUpdate` it was rendering an empty dashboard)

Comment (axelavargas) [reply public/app/features/dashboard/dashgrid/DashboardGrid.tsx:171]: Oh, I forgot to mention, removing this condition will re-render the panel twice when we update the `panel.gridPos` via **InspectJSONTab**, the first one because the event triggers a `forceUpdate`, and the second one because of this line on the `onLayoutChange` method

**Comment by hugohaggmark** [comment]
Friendly reminder to add the correct milestone and backport label if this needs to be released in a patch release. Thank you!

**Review by torkelo — APPROVED** [review]
@axelavargas I reviewed this one more time now and think this looks great, not that much complexity added and is a fine solution for now.  
Pushed minor cleanup commit in https://github.com/grafana/grafana/pull/35276/commits/4bf96deb54e89f3701e000f0cd760a7a978a6c50  , removed the now unnecessary call to onLayoutChange from updateGridPos as that is now handled by the react grid layout (the bug referenced is fixed).    Also removed a  this.forceUpdate before the call to setState as changing state will already trigger an update/re-render  

Sorry for holding up this fix for so long, wanted to see if there was a more complete long term solution that will allow changing anything but that looks like it will need quite a big change. So this will do fine!
