### PR TITLE
Prometheus: Fix UI bug where a label with empty string shows as populated with the deleted label filter value

### LINKED ISSUE #78079: Prometheus: query builder label filter delete bug
Deleting a label filter when there is a subsequent label filter without a value populates the value of the second value with the deleted label filter value.

`access_evaluation_duration_bucket{instance="localhost:3005",job="go-app",le="" }`
becomes
`access_evaluation_duration_bucket{instance="localhost:3005",le="go-app"}`

1. Create a query in the code editor with three label filters but leave the last one blank. i.e., access_evaluation_duration_bucket{instance="localhost:3005",job="go-app",le="" }

2. Switch to the query editor and it is parsed correctly.

3. Delete the middle label filter job="go-app"

4. See that the le label now has the value of the deleted label.

### PR DESCRIPTION
**Pull request by bohandley**
Fixes https://github.com/grafana/grafana/issues/78079
fix in esc epic https://github.com/grafana/support-escalations/issues/8272

Bug fix for the following case:

UI bug: Deleting a label filter when there is a subsequent label filter without a value shows in the UI as populated by the value of the second value with the deleted label filter value.

https://github.com/grafana/grafana/assets/25674746/ada0a4de-f0f3-4abe-b27c-a80ff1779097

1. Create a query in the code editor with three label filters but leave the last one blank. i.e., access_evaluation_duration_bucket{instance="localhost:3005",job="go-app",le="" }

2. Switch to the query editor and it is parsed correctly.

3. Delete the middle label filter job="go-app"

4. See that the le label filter UI now shows the value of the deleted label's value.

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilterItem.tsx [hunk 1]
```diff
@@ -65,6 +65,8 @@ export function LabelFilterItem({
     debounceDuration
   );
 
+  const itemValue = item?.value ? item?.value : '';
```
Comment (itsmylife) [inline public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilterItem.tsx:68]: I think this can be 

`const itemValue = item?.value ?? '';`

File: public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.test.tsx [hunk 2]
```diff
@@ -66,10 +66,21 @@ describe('LabelFilters', () => {
...
+    const { onChange } = setup({
+      labelsFilters: [
+        { label: 'foo', op: '=', value: 'bar' },
+        { label: 'le', op: '=', value: '' },
+      ],
+    });
+    await userEvent.click(screen.getByLabelText(/remove-foo/));
+    expect(onChange).toBeCalledWith([{ label: 'le', op: '=', value: '' }]);
+  });
+
```
Comment (itsmylife) [inline public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.test.tsx:83]: I think we need one more unit test that covers the case you described in the issue https://github.com/grafana/grafana/issues/78079

**Review by itsmylife — COMMENTED** [review]
I am still having hard time to see the problem and test the solution. Could you please provide testing steps?

File: public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.test.tsx (hunk 2 above)
Comment (bohandley) [reply public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.test.tsx:83]: There is just the one case, this test covers the case.

1. you have more than one label, here we have two labels, one has a vlaue of `""`, i.e. `{label_one="label_one_value", label_two=""}`
2. Using the query editor click x to delete `label_one`
3. The UI shows that the value from `label_one` has now been placed in `label_two`'s value like this: `{label_two="label_one_value"}`

You can see it in the video from the customer for the escalation
1. The customer has three labels, the last label has an empty string as a value
2. They delete the middle label
3. The value from the deleted label is now shown in the label with the `""` for a value. `""` has been replaced in the UI
https://drive.google.com/file/d/1rsi9Xb1Klra5f13AeOjXlnUdRXDuj3Gk/view

**Review by itsmylife — APPROVED** [review]

File: public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.test.tsx (hunk 2 above)
Comment (bohandley) [reply public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilters.test.tsx:88]: @itsmylife It was just a UI bug where the LabelFilterItem needed to be re-rendered.
