### PR TITLE
Plugins: Parse defaultValues correctly for nested options

### LINKED ISSUE #78362: Nested panel options cannot have default value
### What happened?

As far as I’ve found, nested panel options do not like to have default values. Can someone verify this on their end, and let me know if they obtain the same result, or if I’m putting in the default values incorrectly? Thanks!

Ref:
- [Nested panel options cannot have default value](https://community.grafana.com/t/bug-nested-panel-options-cannot-have-default-value-set/107997)
- [Panel options subcategories](https://community.grafana.com/t/panel-options-subcategories/107812)

Code:

```ts
export const plugin = new PanelPlugin<PsyOptions>(PsyPanel).setPanelOptions((builder, context) => {
  return builder.addTextInput({
      name: 'Not Nested',
      path: 'a',
      defaultValue: 'Hello!'
    })
    .addNestedOptions({
      path: 'nestor',
      build(subbuilder, subcontext) {
        return subbuilder.addTextInput({
            name: 'Nested',
            path: 'b',
            defaultValue: 'World!',
          });
      },
    });
});
```

Result:
a

### What did you expect to happen?

The nested options to have the default values

### Did this work before?

Unsure

### How do we reproduce it?

1. Create a starter panel plugin
2. Add nested panel editor options
3. Assign default values to those options
4. Test the plugin by creating a new dashboard with that panel, and check the panel editor options for any defaults

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: v10.1.1
OS: MacOS 13.6 (22G120)
Browser: Brave v1.60.118

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by oshirohugo**
**What is this feature?**

Change how we are getting `defaultValues` in nested options, using the old way it was necessary to provide an object whose properties would match the nested options path, now only setting the `defaulValues` in nested options should work.

**Why do we need this feature?**

This feature is needed to provided `defaultValues` for nested options in a more natural way.

**Who is this feature for?**

Plugin developers

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/78362

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: packages/grafana-data/src/utils/OptionsUIBuilders.ts [hunk 1]
```diff
@@ -185,7 +187,22 @@ export class NestedPanelOptionsBuilder<TSub = any> implements OptionsEditorItem<
   constructor(public cfg: NestedPanelOptions<TSub>) {
     this.path = cfg.path;
     this.category = cfg.category;
-    this.defaultValue = cfg.defaultValue;
+    this.defaultValue = this.getDefaultValue(cfg);
+  }
+
+  private getDefaultValue(cfg: NestedPanelOptions<TSub>) {
+    let result: any = cfg.defaultValue || {};
```
Comment (academo) [inline packages/grafana-data/src/utils/OptionsUIBuilders.ts:194]: can you figure the correct type here instead of using any?

File: packages/grafana-data/src/utils/OptionsUIBuilders.ts [hunk 2]
```diff
@@ -185,7 +187,22 @@ export class NestedPanelOptionsBuilder<TSub = any> implements OptionsEditorItem<
   constructor(public cfg: NestedPanelOptions<TSub>) {
     this.path = cfg.path;
     this.category = cfg.category;
-    this.defaultValue = cfg.defaultValue;
+    this.defaultValue = this.getDefaultValue(cfg) as TSub;
+  }
+
+  private getDefaultValue(cfg: NestedPanelOptions<TSub>) {
+    let result = cfg.defaultValue || {};
```
Comment (mckn) [inline packages/grafana-data/src/utils/OptionsUIBuilders.ts:194]: Question: is there any risk by mutating the `cfg.defaultValue` with the `set` function at line 201? Would it be better to work against a copy of the defaultValue instead?

```suggestion
    let result = cloneDeep(cfg.defaultValue || {});
```

**Review by mckn — APPROVED** [review]
LGTM!

**Review by academo — APPROVED** [review]
Looks good!

File: packages/grafana-data/src/utils/OptionsUIBuilders.ts [hunk 3]
```diff
@@ -185,7 +187,22 @@ export class NestedPanelOptionsBuilder<TSub = any> implements OptionsEditorItem<
   constructor(public cfg: NestedPanelOptions<TSub>) {
     this.path = cfg.path;
     this.category = cfg.category;
-    this.defaultValue = cfg.defaultValue;
+    this.defaultValue = this.getDefaultValue(cfg) as TSub;
```
Comment (academo) [inline packages/grafana-data/src/utils/OptionsUIBuilders.ts:190]: This type assertion is not a good idea here, is as equivalent as using `any`

**Review by mckn — APPROVED** [review]
LGTM!
