### PR TITLE
Graphite: Limit number of suggestions displayed in Graphite drop downs

### LINKED ISSUE #41556: Typeahead dropdown menu doesn't limit options causing page to crash
**What happened**:

When using the typeahead dropdown to select a metric dimension from a carbon metrics datasource with over 50k items the page becomes unresponsive.

**What you expected to happen**:

The dropdown to limit the amount of options added to the DOM to prevent crashes. Grafana 6 looks like it limits to 10,000

These screenshots are from chrome devtools when the typeahead dropdown is open (js execution is paused)
Grafana 6
Screenshot 2021-11-10 at 15 54 45
Grafana 8
Screenshot 2021-11-10 at 15 55 08

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8
- Data source type & version: Graphite
- OS Grafana is installed on: EC2
- User OS & Browser: Chrome macOS
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by ifrost**
**What this PR does / why we need it**:

Segment component renders all drop down items in DOM and it may cause the browser to slow down. Drop down is rendered by react-select and we could add virtual rendering too it, but it may affect some other components. In case of Graphite the list is being updated every time a character is added to the input so to mitigate the issue we can simply reduce number of items passed to the options list in the drop down.

**Which issue(s) this PR fixes**:

Fixes #41556

**Special notes for your reviewer**:

Options list may contain a mix of metrics and tags (happens when the first segment is opened). In such case half of the limit is used on both to ensure there's always some tags and metrics shown.

The easiest way to test it is probably by changing MAX_SUGGESTIONS value.

### CODE REVIEW

**Comment by Elfo404** [comment]
I still have to test this, but I was wondering if all that logic shouldn't be in the UI.

What I mean is that the underlying implementation of getting tags and metrics maybe shouldn't be concerned about what the UI does with the data. Did you consider moving the "limit" logic into the components themselves?

**Comment by ifrost** [comment]
> I still have to test this, but I was wondering if all that logic shouldn't be in the UI.
> 
> What I mean is that the underlying implementation of getting tags and metrics maybe shouldn't be concerned about what the UI does with the data. Did you consider moving the "limit" logic into the components themselves?

I was thinking about, but at the end of the day these functions in `providers` belong to components anyway, they are just extracted to a separate file and it makes it a bit easier to test.

File: public/app/plugins/datasource/graphite/state/providers.ts [hunk 1]
```diff
@@ -199,6 +215,11 @@ async function addAltTagSegments(
     return segment;
   });
 
+  if (tagSegments.length + altSegments.length >= MAX_SUGGESTIONS) {
+    tagSegments = tagSegments.slice(0, MAX_SUGGESTIONS / 2);
+    altSegments = altSegments.slice(0, MAX_SUGGESTIONS / 2);
+  }
```
Comment (Elfo404) [inline public/app/plugins/datasource/graphite/state/providers.ts:221]: this means that for 9999 tagSegments and 2 altSegments this function returns 5002 items instead of 10000. is it intentional?

File: public/app/plugins/datasource/graphite/specs/store.test.ts [hunk 2]
```diff
@@ -472,4 +477,62 @@ describe('Graphite actions', async () => {
...
+        manyMetrics.push({ text: `metric${i}` });
+        manyTags.push({ text: `tag${i}` });
+        manyTagValues.push({ text: `tagValue${i}` });
+      }
+      ctx.state.datasource.metricFindQuery = jest.fn().mockReturnValue(Promise.resolve(manyMetrics));
+      ctx.state.datasource.getTagsAutoComplete = jest.fn().mockReturnValue(Promise.resolve(manyTags));
+      ctx.state.datasource.getTagValuesAutoComplete = jest.fn().mockReturnValue(Promise.resolve(manyTagValues));
+    });
+
+    it('uses limited metrics and tags list', async () => {
```
Comment (Elfo404) [inline public/app/plugins/datasource/graphite/specs/store.test.ts:498]: can we use `MAX_SUGGESTIONS` in this test instead of testing for `10000` so that we are not forced to change these tests if we want to change the limit?

**Review by Elfo404 — COMMENTED** [review]
I just checked out the code and noticed that the APIs supports limiting the results directly, and there's also there an hardcoded limit of 1000 in `metricFindQuery` (https://github.com/grafana/grafana/blob/7319efe0779d97c8dac5b0e6d9a3749b177c45a0/public/app/plugins/datasource/graphite/datasource.ts#L369), for example: https://github.com/grafana/grafana/blob/7319efe0779d97c8dac5b0e6d9a3749b177c45a0/public/app/plugins/datasource/graphite/datasource.ts#L580

and https://github.com/grafana/grafana/blob/7319efe0779d97c8dac5b0e6d9a3749b177c45a0/public/app/plugins/datasource/graphite/datasource.ts#L607

any reason to not use that instead?

(the other 2 comments are not strictly related related to this)

File: public/app/plugins/datasource/graphite/state/providers.ts (hunk 1 above)
Comment (ifrost) [reply public/app/plugins/datasource/graphite/state/providers.ts:221]: Yep, it's just to ensure 10k is not exceeded. I think 5k is still quite a lot so I didn't want to convolute the code with something more sophisticated that would always get 10k.

File: public/app/plugins/datasource/graphite/specs/store.test.ts (hunk 2 above)
Comment (ifrost) [reply public/app/plugins/datasource/graphite/specs/store.test.ts:498]: I didn't want to expose it just for testing. What's more I think it makes sense that the test should change when implementation changes. When MAX_SUGGESTIONS is changed I'd like to see what tests failed to be double check what scenarios are affected.

**Comment by ifrost** [comment]
> I just checked out the code and noticed that the APIs supports limiting the results directly, and there's also there an hardcoded limit of 1000 in `metricFindQuery` (
> 
> https://github.com/grafana/grafana/blob/7319efe0779d97c8dac5b0e6d9a3749b177c45a0/public/app/plugins/datasource/graphite/datasource.ts#L369
> 
> ), for example:
> https://github.com/grafana/grafana/blob/7319efe0779d97c8dac5b0e6d9a3749b177c45a0/public/app/plugins/datasource/graphite/datasource.ts#L580
> 
> and
> 
> https://github.com/grafana/grafana/blob/7319efe0779d97c8dac5b0e6d9a3749b177c45a0/public/app/plugins/datasource/graphite/datasource.ts#L607
> 
> any reason to not use that instead?
> 
> (the other 2 comments are not strictly related related to this)

That's a very good point! Forgot that it's possible to limit results in API. I think it makes sense as we just discard other results so limiting it at API level should make the call a bit faster

File: public/app/plugins/datasource/graphite/specs/store.test.ts [hunk 3]
```diff
@@ -472,4 +477,68 @@ describe('Graphite actions', async () => {
...
+      const segments = await getAltSegmentsSelectables(ctx.state, 0, '');
+      expect(segments).toHaveLength(5000);
+      expect(segments[0].value!.value).toBe('*'); // * - is a fixed metric name, always added at the top
+      expect(segments[4999].value!.value).toBe('metric4998');
+    });
+
+    it('uses limited tags when editing', async () => {
+      const tags = await getTagsAsSegmentsSelectables(ctx.state, 'any');
+      expect(tags).toHaveLength(5000);
+    });
```
Comment (Elfo404) [inline public/app/plugins/datasource/graphite/specs/store.test.ts:527]: given the limiting is done by the API itself for tags, I feel this is kind of a weak test as we are testing the mock implementation rather than the mock being called with the correct parameters.

shouldn't we test for `getTagsAutoComplete` getting called with the right `limit` option instead?


**EDIT:**
I see it's done in https://github.com/grafana/grafana/pull/42056/files#diff-fb7ccfa6b3057b85136a7d5e64bf0fd40c2b6627acc04a0204f45538e90a35d6R218-R229, so maybe this these is actually superfluous?

File: public/app/plugins/datasource/graphite/specs/store.test.ts [hunk 4]
```diff
@@ -472,4 +477,68 @@ describe('Graphite actions', async () => {
...
+
+    it('uses limited metrics when adding more metrics', async () => {
+      const segments = await getAltSegmentsSelectables(ctx.state, 1, '');
+      expect(segments).toHaveLength(5000);
+    });
+
+    it('uses limited tag values when editing', async () => {
+      const tagValues = await getTagValuesSelectables(
```
Comment (Elfo404) [inline public/app/plugins/datasource/graphite/specs/store.test.ts:535]: same as before, shouldn't we test for getTagsAutoComplete getting called with the right limit option instead?

**EDIT: (same as the other)**
I see it's done in https://github.com/grafana/grafana/pull/42056/files#diff-fb7ccfa6b3057b85136a7d5e64bf0fd40c2b6627acc04a0204f45538e90a35d6R218-R229, so maybe this these is actually superfluous?

File: public/app/plugins/datasource/graphite/specs/store.test.ts (hunk 2 above)
Comment (Elfo404) [reply public/app/plugins/datasource/graphite/specs/store.test.ts:506]: i agree that exposing it just for testing it's not ideal, that's why I was suggesting to move the limiting logic to the UI. For instance, the autocomplete component could accept a `limit` prop and we could pass that limit to the underlying function instead of relying on a that constant. that would also enable us to write tests form the user POV (for example by testing that no matter how many items the API returns, on the screen they will appear on `limit` number of options).

but I'm also ok with this, just wanted to consider a different approach. 👍

**Review by Elfo404 — APPROVED** [review]
Looks good and seems to work as expected (I had to manually set the limit to a lower value to properly test this)

left just a couple of nits regarding testing, but LGTM 🚀

File: public/app/plugins/datasource/graphite/specs/store.test.ts (hunk 2 above)
Comment (Elfo404) [reply public/app/plugins/datasource/graphite/specs/store.test.ts:506]: i agree that exposing it just for testing it's not ideal, that's why I was suggesting moving the limiting logic to the UI. For instance, the autocomplete component could accept a `limit` prop and we could pass that limit to the underlying function instead of relying on a that constant. that would also enable us to write tests from the user POV (for example by testing that no matter how many items the API returns, on the screen they will appear only `limit` number of options).

but I'm also ok with this, just wanted to consider a different approach. 👍

File: public/app/plugins/datasource/graphite/specs/store.test.ts (hunk 4 above)
Comment (ifrost) [reply public/app/plugins/datasource/graphite/specs/store.test.ts]: Agree! Removed in: 63b766be9a0e587c3f681cbdc446544635fd5df5
