### PR TITLE
TimeSrv: Don't modify refresh interval when editing panel

### LINKED ISSUE #51542: Saving a dashboard panel removes the dashboard refresh interval (9.0.x)
**What happened**:

The refresh interval that is being set on a dashboard isn't being kept when editing a panel

**What you expected to happen**:

Saving panel settings would not have an impact on the overall dashboard refresh interval.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new Grafana dashboard
2. Create a new panel (default of a random walk is fine)
3. Save the new panel
4. Go back to the dashboard & set a refresh interval
5. Return to the newly created panel and click `Save`.
6. Review the changes and see that it is removing the refresh interval that you had set.

screenshot 2022-06-29 at 7 02 24 AM

**Anything else we need to know?**:

**Environment**:
- Grafana version: `9.0.2`
- Data source type & version: `InfluxDB v2.2.0` - Alpine Linux (`influxdb:2.2-alpine` Docker image)
- OS Grafana is installed on: `grafana/grafana:9.0.2` Docker image
- User OS & Browser: macOS Monterey 12.4
- Grafana plugins: just the default plugins
- Others: n/a

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Changes some of the logic in `TimeSrv.ts` to flag the dashboard refresh as being "active" or not, rather than directly changing the refresh interval. This prevents the cleared refresh interval from being committed to the dashboard json when saving from the panel edit view.

**Which issue(s) this PR fixes**:
Fixes #51542

### CODE REVIEW

File: public/app/features/dashboard/services/TimeSrv.ts [hunk 1]
```diff
@@ -24,7 +24,7 @@ export class TimeSrv {
   time: any;
   refreshTimer: any;
   refresh: any;
-  previousAutoRefresh: any;
+  refreshActive = true;
```
Comment (dprokop) [inline public/app/features/dashboard/services/TimeSrv.ts:27]: Nit: `refreshActive` wasn't super clear to me when I first went through the change. Maybe an alternative name could be 
- `canAutoRefresh`
- `disableAutoRefresh`

**Review by dprokop — APPROVED** [review]
Looks good, left one nit to consider :)
