### PR TITLE
Auth: Check id token expiry date

### LINKED ISSUE #65380: Grafana sends expired id token in X-Id-Token header to datasource when using "Forward OAuth Identity"
**What happened**:
I'm using Grafana v9.4.7 with auth.azuread & accessTokenExpirationCheck

``` ini
[auth.azuread]
scopes = openid email profile offline_access
enabled = true
auto_login = true
...

[feature_toggles]
enable = accessTokenExpirationCheck
```

When authenticating towards a Promethues datasource with "Forward OAuth Identity" active and using the token in the X-Id-Token header on the prometheus side for auth it works for 1h (token lifetime). Then starts failing due to expired token. The ID Token is not refreshed after sign in to Grafana.

image

I can work around it by setting `auth.login_maximum_lifetime_duration` < 1h and let auth.azuread.auto_login log me in again every hour. This is a bit annoying to get thrown out of Grafana regularly thou, even if the auto_login works.

**What you expected to happen**:
I expect Grafana to not send expired ID tokens to datasources when "Forward OAuth Identity" is used and the accessTokenExpirationCheck feature toggle is active. Instead it should be refreshed and a valid (not expired) ID token should be sent with requests.

**How to reproduce it (as minimally and precisely as possible)**:
Configure [auth.azuread], enable accessTokenExpirationCheck and observe tokens in headers received at datasource after 1h.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.7, don't think it has ever worked, tried on 9.4.1 as well.
- Data source type & version: Prometheus 2.37.x
- OS Grafana is installed on: Running official docker image on amd64 hardware grafana/grafana:9.4.7

### PR DESCRIPTION
**Pull request by akselleirv**
**What is this feature?**

Verify that the ID token has not expired.

**Why do we need this feature?**

When using the feature toggle `accessTokenExpirationCheck` it only checks for the expiry date of the access token and not the ID token. When using AzureAD to authenticate it issues an ID token which expires before the access token and it results in the user experiencing 401. 

**Who is this feature for?**

For users which uses  `accessTokenExpirationCheck`.

**Which issue(s) does this PR fix?**:

Fixes #65380

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by Jguer** [comment]
@mgyongyosi can you take a look?

@akselleirv I think your implementation is missing in the second path `pkg/services/authn/authnimpl/sync/oauth_token_sync.go` 

The context handler path will be removed soon.

```
[feature_toggles]
authnService = true
```

can be used to enable the new path (although it should now be the default in main)

**Comment by akselleirv** [comment]
Hello @Jguer and @mgyongyosi,

I've added the expiry check to the handler you mentioned. 
Let me know if I should it remove it from the original handler path.

File: pkg/services/authn/authnimpl/sync/oauth_token_sync.go [hunk 1]
```diff
@@ -105,3 +114,30 @@ func getOAuthTokenCacheTTL(t time.Time) time.Duration {
...
 	return ttl
 }
+
+// hasIDTokenExpired checks if the exp field in the ID token has expired. It does not validate the ID token.
+func hasIDTokenExpired(token *login.UserAuth) (bool, error) {
+	if token.OAuthIdToken == "" {
+		return false, nil
+	}
+
+	seperatedIDToken := strings.Split(token.OAuthIdToken, ".")
```
Comment (mgyongyosi) [inline pkg/services/authn/authnimpl/sync/oauth_token_sync.go:124]: Could you please refactor this part to use 'jwt.ParseSigned()` and the `UnsafeClaimsWithoutVerification()` function? In this part the signature validation is not mandatory, because previously it was validated.

Example: https://github.com/grafana/grafana/blob/a97a67fd40dfe2055e2602b0576e1591fee37dc5/pkg/login/social/okta_oauth.go#L56-L64

File: pkg/services/contexthandler/contexthandler.go
Comment (mgyongyosi) [inline pkg/services/contexthandler/contexthandler.go:1]: You don't need to change anything in this file, because currently the this functionality is deprecated and will be removed soon in favor of the `AuthBroker` implementation.

File: pkg/services/authn/authnimpl/sync/oauth_token_sync.go [hunk 2]
```diff
@@ -105,3 +114,30 @@ func getOAuthTokenCacheTTL(t time.Time) time.Duration {
 
 	return ttl
 }
+
+// hasIDTokenExpired checks if the exp field in the ID token has expired. It does not validate the ID token.
+func hasIDTokenExpired(token *login.UserAuth) (bool, error) {
```
Comment (mgyongyosi) [inline pkg/services/authn/authnimpl/sync/oauth_token_sync.go:119]: I would suggest to change this function to something like `func getIDTokenExpiry(token *login.UserAuth) (time.Time, error)`, because this function could be reused to calculate the cache TTL properly.

Explanation: The tokens are cached to improve performance and currently the access token's expiry is set as a TTL, considering that the ID token's expiry could be earlier than the AT expiry I think the cache TTL should be calculated with the following formula: `min(access_token expiry, id_token expiry)`.
https://github.com/grafana/grafana/pull/69829/files#diff-ecd19dccd5583801dfd8752e347c08427fa81deba3285c6e7e17ccba016cd382R80

File: pkg/services/authn/authnimpl/sync/oauth_token_sync.go [hunk 3]
```diff
@@ -65,8 +70,12 @@ func (s *OAuthTokenSync) SyncOauthTokenHook(ctx context.Context, identity *authn
...
 	expires := token.OAuthExpiry.Round(0).Add(-oauthtoken.ExpiryDelta)
+	idTokenHasExpired, err := hasIDTokenExpired(token)
+	if err != nil {
+		s.log.FromContext(ctx).Error("Failed to check expiry of ID token", "id", identity.ID, "error", err)
+	}
 	// token has not expired, so we don't have to refresh it
-	if !expires.Before(time.Now()) {
+	if !expires.Before(time.Now()) && !idTokenHasExpired {
 		// cache the token check, so we don't perform it on every request
 		s.cache.Set(identity.ID, struct{}{}, getOAuthTokenCacheTTL(expires))
```
Comment (mgyongyosi) [inline pkg/services/authn/authnimpl/sync/oauth_token_sync.go:80]: To consider both tokens' expiry and to refresh those when needed the [getOAuthTokenCacheTTL](https://github.com/grafana/grafana/pull/69829/files#diff-ecd19dccd5583801dfd8752e347c08427fa81deba3285c6e7e17ccba016cd382R105) function should also consider the expiry of the `id_token` and set the TTL as the `min(AT expiry, IT expiry)`. If IT expiry `IsZero` then only use the AT expiry.

An edge case could be when the AT expiry is Zero (never expiring) and an id_token is provided (`exp` is mandatory for id_tokens), but I don't think it could happen, at least not for the supported OAuth integrations.

**Review by mgyongyosi — CHANGES_REQUESTED** [review]
Hey @akselleirv, 

Thank you for your contribution to Grafana! Currently I'm working on this part, so expect some changes from upstream, but those should be minor. I left some feedback to you, could you please change your implementation based on those suggestions?

File: pkg/services/authn/authnimpl/sync/oauth_token_sync.go [hunk 4]
```diff
@@ -113,15 +125,47 @@ func (s *OAuthTokenSync) SyncOauthTokenHook(ctx context.Context, identity *authn
...
+		idTokenTTL := time.Until(idTokenExpiry)
+		if idTokenTTL > maxOAuthTokenCacheTTL {
+			idTokenTTL = maxOAuthTokenCacheTTL
+		}
+		if idTokenTTL < accessTokenTTL {
+			return idTokenTTL
+		}
+	}
+
+	return accessTokenTTL
```
Comment (linoman) [inline pkg/services/authn/authnimpl/sync/oauth_token_sync.go:148]: This is a small suggestion to improve readability. This is a non-blocking issue.

```suggestion
	if idTokenExpiry.IsZero() {
		return accessTokenTTL
	}

	idTokenTTL := time.Until(idTokenExpiry)
	if idTokenTTL > maxOAuthTokenCacheTTL {
		idTokenTTL = maxOAuthTokenCacheTTL
	}

	if accessTokenTTL <= idTokenTTL {
		return accessTokenTTL
	}
  return idTokenTTL
```

**Review by linoman — COMMENTED** [review]
👋 Hello @akselleirv and thank you for your contribution! As @Jguer and @mgyongyosi have suggested, you don't need to change anything at `pkg/services/contexthandler/contexthandler.go` since it will be removed soon. This is already blocked from being used by the feature flag that @Jguer [mentioned](https://github.com/grafana/grafana/pull/69829#issuecomment-1609896344).

~Please revert it in order to approve and merge this PR.~

Please review @mgyongyosi [comments](https://github.com/grafana/grafana/pull/69829#pullrequestreview-1542134926).

PS I left a small non-blocking code suggestion.

File: pkg/services/authn/authnimpl/sync/oauth_token_sync.go [hunk 5]
```diff
@@ -113,15 +125,47 @@ func (s *OAuthTokenSync) SyncOauthTokenHook(ctx context.Context, identity *authn
 
 const maxOAuthTokenCacheTTL = 10 * time.Minute
 
-func getOAuthTokenCacheTTL(t time.Time) time.Duration {
-	if t.IsZero() {
+func getOAuthTokenCacheTTL(accessTokenExpiry, idTokenExpiry time.Time) time.Duration {
```
Comment (mgyongyosi) [inline pkg/services/authn/authnimpl/sync/oauth_token_sync.go:128]: Thanks for the change, I skimmed through real quck and I think this function doesn't return the correct TTL when the `accessTokenExpiry` is zero (never expires) and there is an ID token provided (when there is an ID Token provided the expiry always set, because it is required by the spec). I quickly added a table of the expected return values from this function based on the inputs. Could you please add tests for the different scenarios and review my table below?

| Access Token Expiration | ID Token Expiration | Result |
| ------------- | ------------- |----|
| 0  | 0  | maxOAuthTokenCacheTTL (this is the case when no ID token provided) |
| 0  | Jul 5  | min(idTokenTTL, maxOAuthTokenCacheTTL) |
| Jul 5 | 0 | min(accessTokenTTL, maxOAuthTokenCacheTTL) (no ID token) |
| Jul 5 | Jul 4 | min(min(accessTokenTTL, idTokenTTL), maxOAuthTokenCacheTTL) |

File: pkg/services/authn/authnimpl/sync/oauth_token_sync.go [hunk 6]
```diff
@@ -67,7 +71,7 @@ func (s *OAuthTokenSync) SyncOauthTokenHook(ctx context.Context, identity *authn
 	// token has no expire time configured, so we don't have to refresh it
 	if token.OAuthExpiry.IsZero() {
 		// cache the token check, so we don't perform it on every request
-		s.cache.Set(identity.ID, struct{}{}, getOAuthTokenCacheTTL(token.OAuthExpiry))
+		s.cache.Set(identity.ID, struct{}{}, getOAuthTokenCacheTTL(token.OAuthExpiry, time.Time{}))
```
Comment (mgyongyosi) [inline pkg/services/authn/authnimpl/sync/oauth_token_sync.go:74]: Based on my [other comment](), I don't think it happens often, but there is a possibility that an ID token is provided in conjunction with an Access token that never expires and just to be safe we should consider the ID token expiry here as well.

File: pkg/services/authn/authnimpl/sync/oauth_token_sync.go (hunk 5 above)
Comment (mgyongyosi) [inline pkg/services/authn/authnimpl/sync/oauth_token_sync.go:128]: Thanks for the change, I skimmed through real quck and I think this function doesn't return the correct TTL when the `accessTokenExpiry` is zero (never expires) and there is an ID token provided (when there is an ID Token provided the expiry always set, because it is required by the spec). I quickly added a table of the expected return values from this function based on the inputs. Could you please add tests for the different scenarios and review my table below?

| Access Token Expiration | ID Token Expiration | Result |
| ------------- | ------------- |----|
| 0  | 0  | maxOAuthTokenCacheTTL (this is the case when no ID token provided) |
| 0  | Jul 5  | min(idTokenTTL, maxOAuthTokenCacheTTL) |
| Jul 5 | 0 | min(accessTokenTTL, maxOAuthTokenCacheTTL) (no ID token) |
| Jul 5 | Jul 4 | min(min(accessTokenTTL, idTokenTTL), maxOAuthTokenCacheTTL) |

**Review by mgyongyosi — CHANGES_REQUESTED** [review]

File: pkg/services/authn/authnimpl/sync/oauth_token_sync.go [hunk 7]
```diff
@@ -113,15 +125,49 @@ func (s *OAuthTokenSync) SyncOauthTokenHook(ctx context.Context, identity *authn
...
+
+	idTokenTTL := time.Until(idTokenExpiry)
+	if idTokenTTL > maxOAuthTokenCacheTTL {
+		idTokenTTL = maxOAuthTokenCacheTTL
+	}
+
+	if accessTokenTTL <= idTokenTTL {
+		return accessTokenTTL
+	}
+  return idTokenTTL
```
Comment (linoman) [inline pkg/services/authn/authnimpl/sync/oauth_token_sync.go:150]: This was my mistake with the suggestion. This change will help you with the linter check.
```suggestion
	return idTokenTTL
```

Comment (akselleirv) [reply pkg/services/authn/authnimpl/sync/oauth_token_sync.go]: Hello @linoman, I refactored this function based on @mgyongyosi's feedback which should have resolved this issue.

**Review by mgyongyosi — APPROVED** [review]

**Comment by mgyongyosi** [comment]
Stellar work on this @akselleirv! ⭐  Thank you again, your PR has been merged!
