### PR TITLE
Loki: Fix type errors in language_provider

### LINKED ISSUE #31586: Loki: TypeError: Cannot read property 'map' of undefined
**What happened**:
From Sentry (7 times):
`TypeError: Cannot read property 'map' of undefined`
`at map (core|webpack:///./public/app/plugins/datasource/loki/language_provider.ts:500:32)`

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
The initial value for **logLabelOptions** wasn't set. So If we didn't fetch any log labels, we were trying to use map in `addLabelValuesToOptions` on undefined value. This fixes it. 
**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/31586

### CODE REVIEW

File: public/app/plugins/datasource/loki/language_provider.ts [hunk 1]
```diff
@@ -87,6 +87,7 @@ export default class LokiLanguageProvider extends LanguageProvider {
 
     this.datasource = datasource;
     this.labelKeys = [];
+    this.logLabelOptions = [];
```
Comment (ifrost) [inline public/app/plugins/datasource/loki/language_provider.ts:90]: Do we still need this property? I think its usage was removed in https://github.com/grafana/grafana/pull/30351

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/language_provider.ts]: Yes you are right. I didn't realize that we are not using it anymore at all. So I have removed it. 

Also, I noticed, that the try-catch block in `fetchLogLabels` and `fetchLabelValues` is catching only "slice" errors, as request errors are console.error in Loki's request method. So I have changed and simplified this, so "slice" errors are not thrown anymore.
image

Comment (ifrost) [reply public/app/plugins/datasource/loki/language_provider.ts]: Nice one!

**Review by ifrost — APPROVED** [review]
