### PR TITLE
Alerting: Automatically remove stale alerting states

### LINKED ISSUE #36179: Alerting: query with comparison operator prevents alert from resolving because query filters out non-alerting results
What happened: Alerts are not updating and they are showing multiple states 

What you expected to happen: Alerts should return what is returned i query when setting up alert

How to reproduce it (as minimally and precisely as possible):

Anything else we need to know?: 
Screen Shot 2021-06-25 at 8 58 06 AM

Environment:

Grafana version: 8.0.3
Data source type & version: Prometheus / Thanos X 2
OS Grafana is installed on: Azure AKS, official Grafana
User OS & Browser: not relevant
Grafana plugins: clean install
Others:

### LINKED ISSUE #36645: Alerting: Remove instances that stop reporting from cache and database
**What happened**:
The _Matching instances_ view does show entries which do not exist, should not be shown (last entry):
wrong

**What you expected to happen**:
After initial setup the listed instances was like this (until some state changes of one of those listed instances):
normal

**How to reproduce it (as minimally and precisely as possible)**:
<details>

1. Attach a postgres database to grafana containing the following table:
``` sql
CREATE TABLE "carmap" (
  "id" int8 NOT NULL DEFAULT nextval('carmap_id_seq'::regclass),
  "captured" timestamp(6) NOT NULL,
  "name" varchar(255) NOT NULL,
  "city" varchar(255) NOT NULL,
  "speed" float8 NOT NULL
);

-- Insert some rows, adjust speed (->50) to trigger alerts
INSERT INTO carmap (captured, name, city, speed) VALUES
  (NOW()-INTERVAL '3 SECOND', 'car1', 'berlin', 150),
  (NOW()-INTERVAL '3 SECOND', 'car2', 'berlin', 130);
```
2. Create a new alert, sql:
``` sql
SELECT t.name, t.city, CASE WHEN t.speed > 100 THEN 0 ELSE 1 END
FROM (
  SELECT RANK()
    OVER(
      PARTITION BY name
      ORDER BY captured DESC
    ) AS rnk,
    id, captured, name, city, speed
  FROM carmap
) t
WHERE
  rnk = 1 AND
  captured >= (NOW() - INTERVAL '5 MIN')
```
2021-07-12 09_11_58-Alerting_ Alert rules - Grafana

4. Alert conditions:
2021-07-12 09_12_20-Alerting_ Alert rules - Grafana
</details>

**Anything else we need to know?**:
- Contact point: autogen-panel-recv-default_route
- Group by: -
- Timings: Group wait: 1s | Group interval: 2s | Repeat interval: 15m

**Environment**:
- Grafana version: v8.0.3 (cae5c5e46b)
- Data source type & version: postgres 13.3
- OS Grafana is installed on: linux
- User OS & Browser: windows, chrome

### PR DESCRIPTION
**Pull request by davidmparrott**
**What this PR does / why we need it**:
If an evaluation result has not been returned from the evaluator for two evaluation intervals then remove it from the cache and alert_instance table. If the result is subsequently returned, a new entry will be created as normal.

**Which issue(s) this PR fixes**:

Fixes #36645

### CODE REVIEW

**Comment by davidmparrott** [comment]
I will fix merge conflicts before adding tests

File: pkg/services/ngalert/store/instance_database.go [hunk 1]
```diff
@@ -142,3 +143,17 @@ func (st DBstore) FetchOrgIds() ([]int64, error) {
...
 	return orgIds, err
 }
+
+func (st DBstore) DeleteAlertInstance(orgID int64, ruleUID string, labels models.InstanceLabels) error {
+	return st.SQLStore.WithTransactionalDbSession(context.Background(), func(sess *sqlstore.DBSession) error {
+		labelTupleJSON, labelsHash, err := labels.StringAndHash()
+		if err != nil {
+			return err
+		}
+		_, err = sess.Exec("DELETE FROM alert_instance WHERE rule_org_id = ? AND rule_uid = ? AND labels = ? AND labels_hash = ?", orgID, ruleUID, labelTupleJSON, labelsHash)
```
Comment (papagian) [inline pkg/services/ngalert/store/instance_database.go:153]: Do we need also the `labels` in the where condition given the `labels_hash` is derived from them and the `labels` column [is not included in the table primary key or an index](https://github.com/grafana/grafana/blob/8a3d7b64469ca4f260b3a712592bfc2a18397876/pkg/services/sqlstore/migrations/ualert/tables.go#L106).

**Review by papagian — COMMENTED** [review]
Generally LGTM; I have a small question.

File: pkg/services/ngalert/state/manager.go [hunk 2]
```diff
@@ -265,3 +267,22 @@ func (st *Manager) createAlertAnnotation(new eval.State, alertRule *ngModels.Ale
 		return
 	}
 }
+
+func (st *Manager) staleResultsHandler(alertRule *ngModels.AlertRule, states map[string]*State) {
+	allStates := st.GetStatesForRuleUID(alertRule.OrgID, alertRule.UID)
+	for _, s := range allStates {
+		_, ok := states[s.CacheId]
+		if !ok && isItStale(s.LastEvaluationTime, time.Duration(alertRule.IntervalSeconds)) {
```
Comment (papagian) [inline pkg/services/ngalert/state/manager.go:275]:
```suggestion
		if !ok && isItStale(s.LastEvaluationTime, alertRule.IntervalSeconds * time.Second) {
```
I think that this would be clearer than having to multiply with `time.Second` [here](https://github.com/grafana/grafana/blob/299f79d6c8fc5efc073cf4026ebbb75918e67827/pkg/services/ngalert/state/manager.go#L287)

File: pkg/services/ngalert/store/instance_database.go (hunk 1 above)
Comment (davidmparrott) [reply pkg/services/ngalert/store/instance_database.go]: You're totally right, thank you!

File: pkg/services/ngalert/state/manager.go (hunk 2 above)
Comment (davidmparrott) [reply pkg/services/ngalert/state/manager.go]: Makes sense. I varied it slightly but I think it preserves the intention of your comment.

File: pkg/services/ngalert/state/manager_test.go [hunk 3]
```diff
@@ -864,3 +867,107 @@ func TestProcessEvalResults(t *testing.T) {
 		})
 	}
 }
+
+func TestStaleResultsHandler(t *testing.T) {
+	evaluationTime, err := time.Parse("2006-01-02", "2021-03-25")
```
Comment (papagian) [inline pkg/services/ngalert/state/manager_test.go:872]: This `evaluationTime` is already far in the past. It could be something closer the double value of the rule interval and even better having a mockable `timeNow()` function for more deterministic tests.

File: pkg/services/ngalert/state/manager.go [hunk 4]
```diff
@@ -265,3 +267,28 @@ func (st *Manager) createAlertAnnotation(new eval.State, alertRule *ngModels.Ale
...
+			err = st.instanceStore.DeleteAlertInstance(s.OrgID, s.AlertRuleUID, labelsHash)
+			if err != nil {
+				st.log.Error("unable to delete stale instance from database", "error", err.Error(), "orgID", s.OrgID, "alertRuleUID", s.AlertRuleUID, "cacheID", s.CacheId)
+			}
+		}
+	}
+}
+
+func isItStale(lastEval time.Time, intervalSeconds int64) bool {
+	return lastEval.Add(2 * time.Duration(intervalSeconds)).Before(time.Now())
```
[the remark this answers is not in the document]
Comment (kylebrandt) [reply pkg/services/ngalert/state/manager.go:293]: Go2 proposal on this to consider upvoting: `https://github.com/golang/go/issues/20757` :-)

File: pkg/services/ngalert/state/manager.go [hunk 5]
```diff
@@ -265,3 +267,28 @@ func (st *Manager) createAlertAnnotation(new eval.State, alertRule *ngModels.Ale
...
+			st.log.Debug("removing stale state entry", "orgID", s.OrgID, "alertRuleUID", s.AlertRuleUID, "cacheID", s.CacheId)
+			st.cache.deleteEntry(s.OrgID, s.AlertRuleUID, s.CacheId)
+			ilbs := ngModels.InstanceLabels(s.Labels)
+			_, labelsHash, err := ilbs.StringAndHash()
+			if err != nil {
+				st.log.Error("unable to get labelsHash", "error", err.Error(), "orgID", s.OrgID, "alertRuleUID", s.AlertRuleUID)
+			}
+
+			err = st.instanceStore.DeleteAlertInstance(s.OrgID, s.AlertRuleUID, labelsHash)
+			if err != nil {
```
Comment (kylebrandt) [inline pkg/services/ngalert/state/manager.go:285]:
```
if err = ...; err != nil {
 ...
}
```

File: pkg/services/ngalert/state/cache.go [hunk 6]
```diff
@@ -261,3 +261,9 @@ func mergeLabels(a, b data.Labels) data.Labels {
 	}
 	return newLbs
 }
+
+func (c *cache) deleteEntry(orgID int64, alertRuleUID, cacheID string) {
+	c.mtxStates.Lock()
+	defer c.mtxStates.Unlock()
```
Comment (kylebrandt) [inline pkg/services/ngalert/state/cache.go:267]: Given that we call this in a loop, I wonder if it might be better to avoid the unlock defer in these when they are short and also don't have any way of returning an error before the unlock. I think it adds a small amount of overhead. No strong feelings on this, but it keeps popping into my head so wanted to get it out :-)

Comment (davidmparrott) [reply pkg/services/ngalert/state/cache.go:267]: I could go for that for as long as the only thing happening in here is a map delete, which is just a noop when the key isn't present (or the nested map is nil/doesn't exist). If we were to start doing anything else in this method then we would need to reconsider that, and having it here makes it less likely we'll forget to add it back and possibly introduce a race condition

Comment (kylebrandt) [reply pkg/services/ngalert/state/cache.go:267]: Since there are multiple candidates (e.g. cache.reset()) , probably best to leave it out of this PR, and if we want to do something like that, do it another PR as a group.

File: pkg/services/ngalert/state/manager_test.go (hunk 3 above)
Comment (davidmparrott) [reply pkg/services/ngalert/state/manager_test.go:872]: The timestamp here shouldn't matter since the expected test cases are all done relative to evaluationTime. I like having the timestamp be known for easier debugging but if you've got an improvement I would be happy to review it. There's probably an opportunity for us to make a couple utilities/helpers along those lines to make our tests easier to write.

Comment (papagian) [reply pkg/services/ngalert/state/manager_test.go:872]: I'm also fine also leaving it as is; I don't insist.

We don't have a library but for such cases we define:
[var timeNow = time.Now](https://github.com/grafana/grafana/blob/7815ed511f6bb0fb86e7274f91d36987ccf648ce/pkg/services/sqlstore/alert.go#L15)
and use this instead so that in test we can mock it to return something deterministic:
https://github.com/grafana/grafana/blob/7815ed511f6bb0fb86e7274f91d36987ccf648ce/pkg/services/sqlstore/alert_test.go#L14-L26

**Review by papagian — APPROVED** [review]
