### PR TITLE
AccessControl: Fix nuid permission deletion when deleting dashboards and folders

### LINKED ISSUE #69277: Dashboards: same UID dashboard permissions removed when one is deleted in any org
### 
# What went wrong?

**What happened**:

  - Dashboards in different Orgs can share the same UID, but when I delete a dashboard in one Org, all the dashboards in the other Orgs with the same UID lose their permissions. That usually happens with popular downloaded dashboards that are added into many Orgs: i.e. - Node Exporter Full. In this case users with Reader/Editor role won't see the dashboards and will assume that someone had deleted them. However re-creating (re-downloading or uploading them) will fail because the dashboards do exist, but cannot be seen and modified.

**What did you expect to happen**:

  - Dashboards with the same UID in different Orgs do not share the same permissions and if one dashboard is removed, the others are not affected.

### 
# How do we reproduce it?

**Step 1**:

- Run a new Grafana from scratch, e.g. as a container on localhost and bind it to localhost:3000
- Open localhost:3000, log in as admin/admin and skip changing the admin password

**Step 2**:

- Go to `Server admin` → `Organizations`
- Click `New org` and create a new Org named `test`
- You are now in this `test` Org

**Step 3**:

- Click `Dashboards` → `New dashboard`
- Add a new panel — random walk example will do
- Click `Save` and save it as `New dashboard`
- Click `Dashboard settings` → `JSON Model` and copy the source code

**Step 4**:

- Go back, click `Profile`→ `Switch organization` and switch to the `Main Org.`
- Click `Dashboards` → `Import`
- Paste the source code from step 3, click `Load` and `Import`
- Now you have 2 dashboards with the same UID in different Orgs.

**Step 5**:

- Click `Dashboard settings` → `General`, scroll down, click the red `Delete Dashboard` button and confirm by clicking `Delete`.
- The dashboard is deleted in the `Main Org.`

**Step 6**:
- Click `Profile`→ `Switch organization` and switch to the `test` Org
- Open the `New dashboard` - it should be available in the recently viewed.
- Click `Dashboard settings` → `Permissions`
- ... and all the permissions but Admin are gone.

### 
# What Grafana version are you using?

9.2.4

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

AlmaLinux 8.7

### User's Browser?

Google Chrome 109.0.5414.119

### Is this a Regression?

No

### Are Datasources involved?

No

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by Jguer**
**What is this feature?**

Fixes https://github.com/grafana/grafana/issues/69277

No tests exist for integration testing this component

Should be superseeded by https://github.com/grafana/grafana/pull/71222 which has the same logic and is tested once dashboard service is ready to handle deletions instead of the dashboard store

### CODE REVIEW

**Review by gamab — APPROVED** [review]

File: pkg/services/dashboards/database/database.go [hunk 1]
```diff
@@ -11,6 +11,7 @@ import (
 	"github.com/grafana/grafana/pkg/infra/db"
 	"github.com/grafana/grafana/pkg/infra/log"
 	"github.com/grafana/grafana/pkg/infra/metrics"
+	"github.com/grafana/grafana/pkg/services/accesscontrol"
```
Comment (gamab) [inline pkg/services/dashboards/database/database.go:14]: Just checked the CI, we need to remove the double import for linting

**Comment by gamab** [comment]
Thinking about edge cases, I have only one concern, I don't think this works for manually created global roles (orgID = 0)
