### PR TITLE
CloudWatch/Logs: Fix panic on multiple aggregations queries

### LINKED ISSUE #24639: Cloudwatch: Panic on query
Not sure what I did. Been clicking around the cheat sheet examples.
grafana-server ended with a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4ef5189]

goroutine 1189 [running]:
github.com/grafana/grafana/pkg/tsdb/cloudwatch.generateGroupKey(0xc001177940, 0x2, 0x2, 0x15, 0xc0011d0188, 0x0)
	/Users/david/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/log_query.go:116 +0x29
github.com/grafana/grafana/pkg/tsdb/cloudwatch.groupResults(0xc0010da980, 0xc000da6180, 0x2, 0x2, 0x2, 0x2, 0x0, 0x0, 0xc0009ec2d0)
	/Users/david/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/log_query.go:95 +0x3f1
github.com/grafana/grafana/pkg/tsdb/cloudwatch.(*CloudWatchExecutor).executeLogActions.func1(0x1, 0x0)
	/Users/david/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/log_actions.go:43 +0x2d7
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000c5c780, 0xc000e37040)
	/Users/david/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/david/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

### PR DESCRIPTION
**Pull request by aocenas**
Query like `stats avg(bytes), min(bytes), max(bytes) by srcAddr, dstAddr` panicked because cloudwatch sent empty row, creating nil pointer in array where it should not be.

Fixes: https://github.com/grafana/grafana/issues/24639

### CODE REVIEW

File: pkg/tsdb/cloudwatch/log_query.go [hunk 1]
```diff
@@ -27,9 +26,9 @@ func logsResultsToDataframes(response *cloudwatchlogs.GetQueryResultsOutput) (*d
 
 				// Check if field is time field
 				if _, err := time.Parse(cloudWatchTSFormat, *resultField.Value); err == nil {
-					fieldValues[*resultField.Field] = make([]*time.Time, rowCount)
+					fieldValues[*resultField.Field] = make([]*time.Time, 0)
```
Comment (aocenas) [inline pkg/tsdb/cloudwatch/log_query.go:29]: not sure if this is going to be less efficient or not, but basically due to empty rows we don't know the length beforehand. Could do one more pass on Results to filter them out but that seems less efficient to me on first glance.

**Review by kaydelaney — APPROVED** [review]

File: pkg/tsdb/cloudwatch/log_query.go (hunk 1 above)
Comment (aknuds1) [reply pkg/tsdb/cloudwatch/log_query.go:29]: @aocenas Actually, to be efficient about memory allocation, you can use array slice capacity instead of length: 

```suggestion
					fieldValues[*resultField.Field] = make([]*time.Time, 0, rowCount)
```

**Review by aknuds1 — APPROVED** [review]
AFAICT this is fine.
