### PR TITLE
Prometheus: Fix ad hoc filters when using explore table column filtering

### LINKED ISSUE #65894: "Filter for value" then "Filter out value" broken on Explore, Table view, Prom DS
**What happened**:

See this video: https://www.loom.com/share/08a228e7a1a44e4daabf4667e38abfbb

On a dashboard everything works fine: When using AdHoc filters on a table view of a Metrics query (PromQL datasource) you can do:
- Hover a table cell, then click the "Filter for value" 🔍➕ icon to filter to only that value. The results update correctly, then
- Hovering the same table cell, click the "Filter out value" 🔍➖ icon to filter **out** that value from the results. The results still update correctly.

BUT
On explore, when you repeat the same and click "Filter out value" 🔍➖ **the results don't update**

**What you expected to happen**:

Explore behaviour should match Dashboard behaviour. (Perhaps the code and implementation should be shared even!)
ie. When I click "Filter out" in Explore, the query-string should update to a `!=` label-match operator.

**How to reproduce it (as minimally and precisely as possible)**:

As above

**Anything else we need to know?**:

No

**Environment**:
- Grafana version: Grafana Enterprise on GrafanaCloud: `9.5.0-54062pre (commit: a18ea77aac, branch: HEAD)`
- Data source type & version: Prometheus `9.5.0-54062pre` plugin version
- OS Grafana is installed on: GrafanaCloud
- User OS & Browser: MacOS 12.6.3 (21G419), Chrome Version 111.0.5563.146 (Official Build) (arm64)
- Grafana plugins: none
- Others: none

### PR DESCRIPTION
**Pull request by jcolladokuri**
**What is this feature?**

Fixes the way we handle ad hoc filtering on tables for Prometheus Datasource when used in Explore. 

**Why do we need this feature?**

When using + / - from table view in Explore, if a label had already been added as a filter, changing the operator on the same label key and value (+ -> - or - -> +) had no effect, essentially making the first filter applied the only one that worked. 

With this change, we keep the logic to only add non duplicate label / value filters, but considering the operator as well on top of label key / value values so that if the operator needs to be changed, we change it instead of ignoring it:

https://github.com/user-attachments/assets/2d5088fb-af28-406f-b0c7-f881c553c92a

**Who is this feature for?**

Prometheus users

**Which issue(s) does this PR fix?**:

Fixes #65894

### CODE REVIEW

**Review by itsgareth — APPROVED** [review]
nice work, lgtm!

File: packages/grafana-prometheus/src/add_label_to_query.ts [hunk 1]
```diff
@@ -98,3 +107,7 @@ function addFilter(
 function labelExists(labels: QueryBuilderLabelFilter[], filter: QueryBuilderLabelFilter) {
   return labels.find((label) => label.label === filter.label && label.value === filter.value);
 }
+
+function labelOperatorMatches(label: QueryBuilderLabelFilter, filter: QueryBuilderLabelFilter) {
+  return label.op === filter.op;
+}
```
Comment (itsmylife) [inline packages/grafana-prometheus/src/add_label_to_query.ts]: Do we really need a separate function for this?

**Review by itsmylife — APPROVED** [review]
just a nit. LGTM!

File: packages/grafana-prometheus/src/add_label_to_query.ts (hunk 1 above)
Comment (jcolladokuri) [reply packages/grafana-prometheus/src/add_label_to_query.ts]: heh, we def don't, I removed the function and kept the check in the if statement :)
