### PR TITLE
CLI: Fix version selection for plugin install

### LINKED ISSUE #19489: grafana-cli: cannot install anymore plugin with specific version
**What happened**:

`grafana-cli plugins install <plugin-id> <version>` is broken (fails with error "Version you want is not supported on your architecture and os").

`grafana-cli plugins install <plugin-id>` (without version) still works.

It seems to be a regression from #17551.

**What you expected to happen**:

I would exepect the plugin to be installed with the version specified.

**How to reproduce it (as minimally and precisely as possible)**:

On latest Grafana (`6.4.0-beta2` or `master`), enter:

    grafana-cli plugins install grafana-clock-panel 1.0.3

You'll have the following error:

```
Error: ✗ Version you want is not supported on your architecture and os. Latest suitable version is 1.0.3

NAME:
   Grafana cli plugins install - install <plugin id> <plugin version (optional)>

USAGE:
   Grafana cli plugins install [arguments...]
```

The same error has been reproduced with other plugins and other versions. The error occurs even if the specified version is the latest suitable version of the plugin.

Everything works when no version is specified:

```
grafana-cli plugins install grafana-clock-panel
installing grafana-clock-panel @ 1.0.3
from: https://grafana.com/api/plugins/grafana-clock-panel/versions/1.0.3/download
into: /var/lib/grafana/plugins

✔ Installed grafana-clock-panel successfully 

Restart grafana after installing plugins . <service grafana-server restart>
```

**Anything else we need to know?**:

It did work in Grafana 6.3.6; the regression seems to be in commit 8c49d27705.

**Environment**:
- Grafana version: `6.4.0-beta2` or `master`
- Data source type & version: SQLite
- OS Grafana is installed on: Alpine (Docker image)
- User OS & Browser: N/A
- Grafana plugins: No plugin
- Others:

### PR DESCRIPTION
**Pull request by aocenas**
Closes: https://github.com/grafana/grafana/issues/19489

Fixes how version is selected which would otherwise prevent plugin installation in some cases.

### CODE REVIEW

File: pkg/cmd/grafana-cli/commands/install_command.go [hunk 1]
```diff
@@ -157,32 +157,35 @@ func latestSupportedVersion(plugin *m.Plugin) *m.Version {
...
+// os and platform. It expects plugin.Versions to be sorted so the newest version is first.
 func SelectVersion(plugin *m.Plugin, version string) (*m.Version, error) {
-	var ver *m.Version
-	if version == "" {
-		ver = &plugin.Versions[0]
-	}
-
-	for _, v := range plugin.Versions {
-		if v.Version == version {
-			ver = &v
```
Comment (aocenas) [inline pkg/cmd/grafana-cli/commands/install_command.go]: One bug was here. As this was taking pointer to looped over variable it ended up with pointer to last (lowest) version after the loop.

File: pkg/cmd/grafana-cli/commands/install_command.go [hunk 2]
```diff
@@ -157,32 +157,35 @@ func latestSupportedVersion(plugin *m.Plugin) *m.Version {
...
-		return nil, xerrors.New("Could not find the version you're looking for")
-	}
+	var ver m.Version
 
 	latestForArch := latestSupportedVersion(plugin)
 	if latestForArch == nil {
 		return nil, xerrors.New("Plugin is not supported on your architecture and os.")
 	}
 
-	if latestForArch.Version == ver.Version {
```
Comment (aocenas) [inline pkg/cmd/grafana-cli/commands/install_command.go]: Here was another bug. We checked if version matches `latestForArch` even in case we actually specified lower version for installation.

File: pkg/cmd/grafana-cli/commands/install_command.go [hunk 3]
```diff
@@ -157,32 +157,35 @@ func latestSupportedVersion(plugin *m.Plugin) *m.Version {
 
 // SelectVersion returns latest version if none is specified or the specified version. If the version string is not
 // matched to existing version it errors out. It also errors out if version that is matched is not available for current
-// os and platform.
+// os and platform. It expects plugin.Versions to be sorted so the newest version is first.
 func SelectVersion(plugin *m.Plugin, version string) (*m.Version, error) {
```
Comment (aocenas) [inline pkg/cmd/grafana-cli/commands/install_command.go]: Refactored the code a bit to fix the bugs and make it clearer. There were some assumptions (mainly that API will filter versions that should not work in current architecture) which made the code work but with the refactor it should work correctly even without those assumptions. Though the assumption that versions are sorted is still required as we do not strictly rely on versioning scheme (and thus meaningful comparison of version strings).

**Review by marefr — APPROVED** [review]
Works as expected for me :+1:
