### PR TITLE
Loki: Fix fetching of values for label if no previous equality operator

### LINKED ISSUE #80308: Explore: Failed to call resource when attempting to change label in Builder mode
### What happened?

After searching logs with Loki and wanting to change a label value (ie: environment) to something else, an error is received "Failed to call resource". The label values are not returned (dropdown just spins). See screenshot as example.
Screenshot 2024-01-10 at 10 38 10 AM

Logs return the following:

```
2024-01-10T16:32:03.123567981Z stdout F logger=context userId=137 orgId=1 uname=xxx t=2024-01-10T16:32:03.123447886Z level=error msg="Failed to call resource" error="parse error : queries require at least one regexp or equality matcher that does not have an empty-compatible value. For instance, app=~\".*\" does not meet this requirement, but app=~\".+\" will" traceID=
```

This results in a broken query that requires a refresh, or removing all other label filters.

### What did you expect to happen?

The error message doesn't provide any clear context as to what happened and why. The label filter dropdown should present the same values that the initial query offered (ie: environment > all values). 

### Did this work before?

Unknown

### How do we reproduce it?

1. In Explore > Builder > choose Loki datasource, add label filters (ie: environment="produs", namespace!~"loki")
2. Run Query
3. Attempt to change first/initial label filter (ie: produs) to something else
4. Note error "Failed to call resource"

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 9.4.3
OS: macOS
Browser: Chrome

### Grafana platform?

Other

### Datasource(s)?

Loki

### PR DESCRIPTION
**Pull request by ivanahuckova**
If user is fetching label value, but there are no label filters with equality operators (`=`, `=~`), then we were using `fetchSeriesLabels` which threw error as it needs at least 1 equality operator. To fix this, in a case when we have none (which should not happen often), we use `fetchLabelValues` in the same way as when we are fetchin label values for the firs label in filter.

I have added test.

Fixes https://github.com/grafana/grafana/issues/80308

Video of broken functionality:

https://github.com/grafana/grafana/assets/30407135/43c9b5ca-ef6f-4515-8fc3-cd45639c533b

Video of fixed behavior in this PR:

https://github.com/grafana/grafana/assets/30407135/371e5285-a8c3-42e4-8dea-20a2bf4c47d0

### CODE REVIEW

File: public/app/plugins/datasource/loki/querybuilder/components/LokiQueryBuilder.tsx [hunk 1]
```diff
@@ -81,7 +81,9 @@ export const LokiQueryBuilder = React.memo<Props>(
 
       let values;
       const labelsToConsider = query.labels.filter((x) => x !== forLabel);
-      if (labelsToConsider.length === 0) {
+      // If we have no equality/regex operation, we can't fetch series as it will throw an error, so we fetch label values
+      const hasEqualityOperation = labelsToConsider.find((filter) => filter.op === '=' || filter.op === '=~');
```
Comment (svennergr) [inline public/app/plugins/datasource/loki/querybuilder/components/LokiQueryBuilder.tsx:85]: Problem with `=~` is that it would still fail with something like `foo=~".*"`, basically every matcher that would match an empty value: https://github.com/grafana/loki/blob/main/pkg/util/matchers.go#L16

I think we would need the same logic, if `=~` is selected, we need to match the "value" against an empty string, if that regex is valid, we should call labelValues instead.

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/querybuilder/components/LokiQueryBuilder.tsx]: Updated and added test in https://github.com/grafana/grafana/pull/82251/commits/35bdc551f38d0518f09ec88b755274e204a2ab9e

File: public/app/plugins/datasource/loki/querybuilder/components/LokiQueryBuilder.tsx [hunk 2]
```diff
@@ -81,7 +81,11 @@ export const LokiQueryBuilder = React.memo<Props>(
 
       let values;
       const labelsToConsider = query.labels.filter((x) => x !== forLabel);
-      if (labelsToConsider.length === 0) {
+      // If we have no equality/regex operation with .*, we can't fetch series as it will throw an error, so we fetch label values
+      const hasEqualityOperation = labelsToConsider.find(
+        (filter) => filter.op === '=' || (filter.op === '=~' && filter.value !== '.*')
```
Comment (svennergr) [inline public/app/plugins/datasource/loki/querybuilder/components/LokiQueryBuilder.tsx:86]: I think what we really need is something like

```suggestion
        (filter) => filter.op === '=' || (filter.op === '=~' && new RegExp(filter.value).test("") === false)
```

to test for all variations of matchers that can match an empty string. That's what Loki also does in https://github.com/grafana/loki/blob/main/pkg/util/matchers.go#L16. The `matcher.Matches("")` is the equivalent of `new RegExp(filter.value).test("")`.

**Review by svennergr — COMMENTED** [review]
I think we need a similar fix for `onGetLabelNames` in public/app/plugins/datasource/loki/querybuilder/components/LokiQueryBuilder.tsx. Do you want to add it in this PR or a separate one?


https://github.com/grafana/grafana/assets/8092184/1adb73c7-973e-4051-ae7d-cebda9777974

**Comment by ivanahuckova** [comment]
>I think we need a similar fix for onGetLabelNames in

Can we tackle that in separate PR?

**Review by svennergr — APPROVED** [review]
Sure, let me go ahead and fix it.
