### PR TITLE
Return correct error for name taken and validation error on add/update datasource

### LINKED ISSUE #65831: Inappropriate HTTP response code - Datasources
Splitting up from the [main issue](https://github.com/grafana/grafana/issues/63543) so that separate squads can take a look at their areas.

|Endpoint| Error | Status code current
-- | -- | --
| **PUT /api/datasources/uid/{UID}**| [Failed to evaluate queries and expressions: failed to execute query D: no handler found for query type ''](pq: duplicate key value violates unique constraint \"UQE_data_source_org_id_name\) | 500 |
| **POST /api/datasources**,  **PUT /api/datasources/uid/{UID}**| [error](pq: value too long for type character varying(255)) | 500 |

Regarding "[error](pq: value too long for type character varying(255))" returning 500 when updating datasource if setting value longer than 255. Referring to Grafana source code, updating datasource is to set new value in PostgreSQL after getting the datatsource by uid. And it uses [XORM](https://xorm.io/) package to operate database,  struct "DataSource" auto mapping to a database’s table, and _string_ type map to _Varchar(255)_ in table. So if user set string value such as "Name", "URL" longer than 255 characters, this error will occur.

  - appropriate status code to be returned, rather than a generic 500 Internal Server
  - Grafana should add check logic for string value when updating SQL database,  avoid _value too long_ error

### PR DESCRIPTION
**Pull request by kousikmitra**
**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #65831

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by kousikmitra** [comment]
> hi @kousikmitra can you create an issue (or link it if there is already one) so we can take a look to the error and how to reproduce it?

It's there #65831

File: pkg/services/datasources/service/datasource.go [hunk 1]
```diff
@@ -243,6 +252,21 @@ func (s *Service) UpdateDataSource(ctx context.Context, cmd *datasources.UpdateD
 			return err
 		}
 
+		if cmd.Name != "" && cmd.Name != dataSource.Name {
+			query := &datasources.GetDataSourceQuery{
+				Name:  cmd.Name,
+				OrgID: cmd.OrgID,
+			}
```
Comment (andresmgot) [inline pkg/services/datasources/service/datasource.go:259]: does this work if the ID is not specified?

File: pkg/services/datasources/service/datasource.go [hunk 2]
```diff
@@ -231,6 +235,11 @@ func (s *Service) DeleteDataSource(ctx context.Context, cmd *datasources.DeleteD
 
 func (s *Service) UpdateDataSource(ctx context.Context, cmd *datasources.UpdateDataSourceCommand) (*datasources.DataSource, error) {
 	var dataSource *datasources.DataSource
+
+	if err := cmd.Validate(); err != nil {
```
Comment (andresmgot) [inline pkg/services/datasources/service/datasource.go:239]: it may be better to implement the validation logic here so we don't need to repeat it twice.

**Review by andresmgot — COMMENTED** [review]
Code mostly looks good to me, thanks! (only a couple of minor comments) But I am not familiar enough with this part of the code to know if it's written in the best place. I'll let @marefr do a more thorough review.

File: pkg/services/datasources/service/datasource.go (hunk 1 above)
Comment (marefr) [reply pkg/services/datasources/service/datasource.go:259]: Yes it does, see https://github.com/grafana/grafana/blob/9ebede1e18dd8c3a2630e05a37d613b1c5f0ab36/pkg/api/datasources.go#L590-L593

**Review by marefr — DISMISSED** [review]
Great work. Some minor things left

File: pkg/services/datasources/service/datasource.go (hunk 2 above)
Comment (marefr) [reply pkg/services/datasources/service/datasource.go:239]: I agree, a function/method can hold the validation logic here and being shared by both save and update.

File: pkg/services/datasources/service/datasource.go (hunk 1 above)
Comment (kousikmitra) [reply pkg/services/datasources/service/datasource.go:264]: OrgID is must to get datasource and the unique constraint is applied on `org_id` + `name`
https://github.com/grafana/grafana/blob/cca9d897339ae2de087bc5b7177849a730d4b38d/pkg/services/sqlstore/migrations/datasource_mig.go#L68

File: pkg/services/datasources/service/datasource.go (hunk 2 above)
Comment (kousikmitra) [reply pkg/services/datasources/service/datasource.go]: check it out, could not figure out a better a way of doing it since both func takes different command struct.

File: pkg/api/datasources.go [hunk 3]
```diff
@@ -393,6 +393,11 @@ func (hs *HTTPServer) AddDataSource(c *contextmodel.ReqContext) response.Respons
 			return response.Error(409, err.Error(), err)
 		}
 
+		var validationErr datasources.ValidationError
+		if errors.As(err, &validationErr) {
+			return response.Error(400, "Failed to add datasource: "+validationErr.Error(), err)
```
[the remark this answers is not in the document]
Comment (kousikmitra) [reply pkg/api/datasources.go]: updated

File: pkg/api/datasources.go [hunk 4]
```diff
@@ -512,10 +517,19 @@ func (hs *HTTPServer) updateDataSourceByID(c *contextmodel.ReqContext, ds *datas
...
+			return response.Error(http.StatusConflict, "Failed to update datasource: "+err.Error(), err)
+		}
+
 		if errors.Is(err, datasources.ErrDataSourceUpdatingOldVersion) {
 			return response.Error(409, "Datasource has already been updated by someone else. Please reload and try again", err)
 		}
 
+		var validationErr datasources.ValidationError
+		if errors.As(err, &validationErr) {
+			return response.Error(400, "Failed to add datasource: "+validationErr.Error(), err)
```
[the remark this answers is not in the document]
Comment (kousikmitra) [reply pkg/api/datasources.go]: updated

File: pkg/api/datasources_test.go [hunk 5]
```diff
@@ -248,6 +249,38 @@ func TestUpdateDataSource_URLWithoutProtocol(t *testing.T) {
...
+			Access: "direct",
+			Type:   "test",
+			Name:   "test",
+		})
+		return hs.UpdateDataSourceByID(c)
+	}))
+
+	sc.fakeReqWithParams("PUT", sc.url, map[string]string{}).exec()
+
+	assert.Equal(t, 409, sc.resp.Code)
```
[the remark this answers is not in the document]
Comment (kousikmitra) [reply pkg/api/datasources_test.go]: updated

File: pkg/services/datasources/models.go [hunk 6]
```diff
@@ -111,6 +111,18 @@ type AddDataSourceCommand struct {
 	UpdateSecretFn          UpdateSecretFn    `json:"-"`
 }
 
+func (cmd AddDataSourceCommand) Validate() error {
+	if len(cmd.Name) > 255 {
+		return ValidationError{Reason: "datasource name is too long, max length is 255"}
+	}
```
[the remark this answers is not in the document]
Comment (kousikmitra) [reply pkg/services/datasources/models.go]: Got it, changed the validation

File: pkg/services/datasources/errors.go [hunk 7]
```diff
@@ -12,3 +12,11 @@ var (
 	ErrDataSourceIdentifierNotSet        = errors.New("unique identifier and org id are needed to be able to get or delete a datasource")
 	ErrDatasourceIsReadOnly              = errors.New("data source is readonly, can only be updated from configuration")
 )
+
+type ValidationError struct {
```
[the remark this answers is not in the document]
Comment (kousikmitra) [reply pkg/services/datasources/errors.go]: Updated, please check if this is the standard way of using the package.

File: pkg/services/datasources/errors.go [hunk 8]
```diff
@@ -11,4 +15,6 @@ var (
 	ErrDataSourceFailedGenerateUniqueUid = errors.New("failed to generate unique datasource ID")
 	ErrDataSourceIdentifierNotSet        = errors.New("unique identifier and org id are needed to be able to get or delete a datasource")
 	ErrDatasourceIsReadOnly              = errors.New("data source is readonly, can only be updated from configuration")
+	ErrDataSourceNameInvalid             = errutil.NewBase(errutil.StatusValidationFailed, "datasource.nameInvalid", errutil.WithPublicMessage("invalid datasource name"))
```
Comment (andresmgot) [inline pkg/services/datasources/errors.go:18]: the public message is what's is printed for the user so it should have proper puntuation:

```suggestion
	ErrDataSourceNameInvalid             = errutil.NewBase(errutil.StatusValidationFailed, "datasource.nameInvalid", errutil.WithPublicMessage("Invalid datasource name."))
```

File: pkg/services/datasources/errors.go [hunk 9]
```diff
@@ -11,4 +15,6 @@ var (
 	ErrDataSourceFailedGenerateUniqueUid = errors.New("failed to generate unique datasource ID")
 	ErrDataSourceIdentifierNotSet        = errors.New("unique identifier and org id are needed to be able to get or delete a datasource")
 	ErrDatasourceIsReadOnly              = errors.New("data source is readonly, can only be updated from configuration")
```
Comment (andresmgot) [inline pkg/services/datasources/errors.go:17]: I am not a fan that now there are two different ways of defining errors but I understand the reasoning so it's okay to keep it like this.

**Review by andresmgot — APPROVED** [review]
Sorry for the slow response, mostly looks good to me, thanks! I only have one minor comment. Giving @grafana/backend-platform also a chance to review this.

File: pkg/services/datasources/errors.go (hunk 8 above)
Comment (kousikmitra) [reply pkg/services/datasources/errors.go]: Got it. Updated both the error message

File: pkg/services/datasources/errors.go (hunk 9 above)
Comment (kousikmitra) [reply pkg/services/datasources/errors.go:17]: ya I agree, but don't wanna club unrelated change in this PR.

**Review by andresmgot — CHANGES_REQUESTED** [review]
After testing this, the update flow is broken if you try to change the name of any data source. It fails with:

image

Can you check the issue @kousikmitra ?

**Comment by kousikmitra** [comment]
> After testing this, the update flow is broken if you try to change the name of any data source. It fails with:
> 
> image
> 
> Can you check the issue @kousikmitra ?

Sorry for the late reply. I was not available. I will look into it.

**Review by andresmgot — APPROVED** [review]
LGTM, thanks for the contribution!
