### PR TITLE
Graphite: Fixes error with annotation metric queries 

### LINKED ISSUE #20737: Annotation query against graphite failes for non empty queries after upgrade from 6.4.5 to  6.5
**What happened**:
After updating from grafana 6.4.5 to 6.5.0, we are encountering failures for deploy annotations using graphite as datasource. The error:

```
Annotation Query Failed
Cannot read property 'length' of undefined
```
The browser console gives:
```
AnnotationSrv.query error TypeError: Cannot read property 'length' of undefined
    at datasource.ts:180
```
If I change the annotation query to something that does not exist (leading to `[]` as response), the error goes away.

**What you expected to happen**:
Seeing the deploy-events recorded in graphite.

**How to reproduce it (as minimally and precisely as possible)**:
* Use an existing graphite/statsd setup
* Issue an inc("test.deploy") against the setup, generating a datapoint
* Create an annotation query on said graphite, querying for "test.deploy"
* Dashboard shows an error popup

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: graphite for the annotation, 1.1.4
- OS Grafana is installed on: debian buster
- User OS & Browser: ubuntu 18.04, chrome
- Grafana plugins: 
```
grafana-piechart-panel @ 1.3.9 
grafana-polystat-panel @ 1.0.16 
vonage-status-panel @ 1.0.9 
```
- Others:

### PR DESCRIPTION
**Pull request by dprokop**
fixes #20737 

The problem described in the issue was caused by the annotation query processing implementation not using `DataFrame` which is a format returned from Graphite's  datasource `query` .

### CODE REVIEW

File: public/app/plugins/datasource/graphite/datasource.ts [hunk 1]
```diff
@@ -177,22 +177,24 @@ export class GraphiteDatasource extends DataSourceApi<GraphiteQuery, GraphiteOpt
         maxDataPoints: 100,
       } as unknown) as DataQueryRequest<GraphiteQuery>;
 
-      return this.query(graphiteQuery).then((result: { data: any[] }) => {
+      return this.query(graphiteQuery).then((result: { data: DataFrame[] }) => {
```
Comment (torkelo) [inline public/app/plugins/datasource/graphite/datasource.ts]: The result typing here can be completely removed :) The query method has a result type of Promise<DataQueryResponse>  so the result type here can be inferred

**Review by torkelo — APPROVED** [review]
Great!

File: public/app/plugins/datasource/graphite/datasource.ts [hunk 2]
```diff
@@ -177,22 +177,24 @@ export class GraphiteDatasource extends DataSourceApi<GraphiteQuery, GraphiteOpt
         maxDataPoints: 100,
       } as unknown) as DataQueryRequest<GraphiteQuery>;
 
-      return this.query(graphiteQuery).then((result: { data: any[] }) => {
+      return this.query(graphiteQuery).then((result: { data }) => {
```
Comment (torkelo) [inline public/app/plugins/datasource/graphite/datasource.ts]: you forgot to remove all typings :)   just do then(result =>
