### PR TITLE
Explore: Fix share link labels

### LINKED ISSUE #86964: Explore: Incorrect copy URL label
Copy Absolute Shortened URL shows up twice (first creates a shortened links, the second creates full URL)

Image

### PR DESCRIPTION
**Pull request by ifrost**
Fixes #86964

| before | after |
|-------|------|
| Screenshot 2024-04-26 at 10 36 52 | Screenshot 2024-04-26 at 10 40 15 |

### CODE REVIEW

File: public/app/features/explore/ShortLinkButtonMenu.tsx [hunk 1]
```diff
@@ -93,7 +93,7 @@ export function ShortLinkButtonMenu() {
         {
           key: 'copy-link-abs-time',
           icon: 'clock-nine',
-          label: t('explore.toolbar.copy-link-abs-time', 'Copy Absolute Shortened URL'),
+          label: t('explore.toolbar.copy-link-abs-time', 'Copy Absolute URL'),
```
Comment (joshhunt) [inline public/app/features/explore/ShortLinkButtonMenu.tsx:96]: While we're nit-picking, absolute probably should have a lowercase A ✌️

**Review by gelicia — APPROVED** [review]

**Review by L-M-K-B — APPROVED** [review]
