### PR TITLE
CloudMonitoring: Fix fastpass issues

### LINKED ISSUE #42709: Accessibility: Fix Google Cloud Monitoring query editor fastpass issues

### LINKED ISSUE #42710: Configuration

### PR DESCRIPTION
**Pull request by andresmgot**
**What this PR does / why we need it**:

Fixes fastpass issues for Cloud Monitoring. Both for the config page and the query editor (Metrics and SLO).

Along the way I found an unused component (`QueryType`) so I deleted it.

**Which issue(s) this PR fixes**:

Fixes #42710
Fixes #42709

**Special notes for your reviewer**:

The cat is happy

Screenshot from 2022-01-20 16-33-51

### CODE REVIEW

File: public/app/plugins/datasource/cloud-monitoring/components/ConfigEditor/ConfigEditor.tsx [hunk 1]
```diff
@@ -22,6 +23,7 @@ export class ConfigEditor extends PureComponent<Props> {
           <InlineField label="Type" labelWidth={20}>
             <Select
               menuShouldPortal
+              aria-label="Type"
```
Comment (kaydelaney) [inline public/app/plugins/datasource/cloud-monitoring/components/ConfigEditor/ConfigEditor.tsx:26]: Here we can use `htmlFor` on `InlineField`, and `inputId` on `Select` so we don't need to repeat the label.
See influxdb's `ConfigEditor.tsx` for an example

File: public/app/plugins/datasource/cloud-monitoring/components/GroupBy.tsx [hunk 2]
```diff
@@ -33,6 +34,7 @@ export const GroupBy: FunctionComponent<Props> = ({
     >
       <MultiSelect
         menuShouldPortal
+        aria-label="group-by"
```
Comment (kaydelaney) [inline public/app/plugins/datasource/cloud-monitoring/components/GroupBy.tsx:37]:
```suggestion
        aria-label="Group by"
```

File: public/app/plugins/datasource/cloud-monitoring/components/LabelFilter.tsx [hunk 3]
```diff
@@ -126,6 +127,7 @@ export const LabelFilter: FunctionComponent<Props> = ({
               />
               <Select
                 menuShouldPortal
+                aria-label="filter-label-value"
```
Comment (kaydelaney) [inline public/app/plugins/datasource/cloud-monitoring/components/LabelFilter.tsx:130]:
```suggestion
                aria-label="Filter label value"
```

File: public/app/plugins/datasource/cloud-monitoring/components/AlignmentFunction.tsx [hunk 4]
```diff
@@ -36,6 +37,7 @@ export const AlignmentFunction: FC<Props> = ({ query, templateVariableOptions, o
         },
       ]}
       placeholder="Select Alignment"
+      aria-label="alignment-function"
```
Comment (joshhunt) [inline public/app/plugins/datasource/cloud-monitoring/components/AlignmentFunction.tsx:40]: Similar to comment as `aria-label="group-by-function"`. This might be mildly trickier to think about as you might have to pass more things in.

File: public/app/plugins/datasource/cloud-monitoring/components/LabelFilter.tsx [hunk 5]
```diff
@@ -20,7 +20,7 @@ const operators = ['=', '!=', '=~', '!=~'];
 
 const FilterButton = React.forwardRef<HTMLButtonElement, CustomControlProps<string>>(
   ({ value, isOpen, invalid, ...rest }, ref) => {
-    return <Button {...rest} ref={ref} variant="secondary" icon="plus"></Button>;
+    return <Button {...rest} ref={ref} variant="secondary" icon="plus" aria-label="add-filter"></Button>;
```
Comment (kaydelaney) [inline public/app/plugins/datasource/cloud-monitoring/components/LabelFilter.tsx:23]:
```suggestion
    return <Button {...rest} ref={ref} variant="secondary" icon="plus" aria-label="Add filter"></Button>;
```

File: public/app/plugins/datasource/cloud-monitoring/components/Metrics.tsx [hunk 6]
```diff
@@ -149,6 +149,7 @@ export function Metrics(props: Props) {
               ...services,
             ]}
             placeholder="Select Services"
+            aria-label="service"
```
Comment (kaydelaney) [inline public/app/plugins/datasource/cloud-monitoring/components/Metrics.tsx:152]:
```suggestion
            aria-label="Service"
```

File: public/app/plugins/datasource/cloud-monitoring/components/Metrics.tsx [hunk 7]
```diff
@@ -165,6 +166,7 @@ export function Metrics(props: Props) {
               ...metrics,
             ]}
             placeholder="Select Metric"
+            aria-label="select-metric"
```
Comment (kaydelaney) [inline public/app/plugins/datasource/cloud-monitoring/components/Metrics.tsx:169]:
```suggestion
            aria-label="Select Metric"
```

File: public/app/plugins/datasource/cloud-monitoring/components/Project.tsx [hunk 8]
```diff
@@ -41,6 +42,7 @@ export function Project({ projectName, datasource, onChange, templateVariableOpt
         options={projectsWithTemplateVariables}
         value={{ value: projectName, label: projectName }}
         placeholder="Select Project"
+        aria-label="project"
```
Comment (kaydelaney) [inline public/app/plugins/datasource/cloud-monitoring/components/Project.tsx:45]:
```suggestion
        aria-label="Project"
```

File: public/app/plugins/datasource/cloud-monitoring/components/QueryEditor.tsx [hunk 9]
```diff
@@ -76,6 +77,7 @@ export class QueryEditor extends PureComponent<Props> {
         >
           <Select
             menuShouldPortal
+            aria-label="query-type"
```
Comment (kaydelaney) [inline public/app/plugins/datasource/cloud-monitoring/components/QueryEditor.tsx:80]:
```suggestion
            aria-label="Query Type"
```

File: public/app/plugins/datasource/cloud-monitoring/components/SLO/SLO.tsx [hunk 10]
```diff
@@ -37,6 +38,7 @@ export const SLO: React.FC<Props> = ({ query, templateVariableOptions, onChange,
     <QueryEditorRow label="SLO">
       <Select
         menuShouldPortal
+        aria-label="slo"
```
Comment (kaydelaney) [inline public/app/plugins/datasource/cloud-monitoring/components/SLO/SLO.tsx:41]: Should this sound similar to "slow", or as the letters "S,L,O"?

File: public/app/plugins/datasource/cloud-monitoring/components/SLO/Selector.tsx [hunk 11]
```diff
@@ -18,6 +19,7 @@ export const Selector: React.FC<Props> = ({ query, templateVariableOptions, onCh
     <QueryEditorRow label="Selector">
       <Select
         menuShouldPortal
+        aria-label="selector"
```
Comment (kaydelaney) [inline public/app/plugins/datasource/cloud-monitoring/components/SLO/Selector.tsx:22]:
```suggestion
        aria-label="Selector"
```

File: public/app/plugins/datasource/cloud-monitoring/components/SLO/Service.tsx [hunk 12]
```diff
@@ -37,6 +38,7 @@ export const Service: React.FC<Props> = ({ query, templateVariableOptions, onCha
     <QueryEditorRow label="Service">
       <Select
         menuShouldPortal
+        aria-label="service"
```
Comment (kaydelaney) [inline public/app/plugins/datasource/cloud-monitoring/components/SLO/Service.tsx:41]:
```suggestion
        aria-label="Service"
```

**Review by kaydelaney — CHANGES_REQUESTED** [review]
Thanks for working on this! Left some suggestions.
In general I think it might be nicer if `QueryEditorRow` and `QueryEditorField` were updated to have an `htmlFor` attribute. That way the label wouldn't have to be repeated and we wouldn't need to use `aria-label` attributes.
But this can be left until later unless you're keen on doing it for this PR.

**Review by joshhunt — COMMENTED** [review]
Excellent stuff - thanks for tackling this!

A few rules of thumb to keep in mind:

 - HTML is accessible by default
 - _As a rule of thumb_, aria-* props should only be used as a last resort, relying on standard html behaviour (`<label /> + <input />`, `<button onClick />` vs `<div onClick />`)
 - aria-label values are read out by screen readers, so they should be plain english, as if were visible on the page. 

For this PR, I think there's two common points here that should be addressed:
 - We already have visible labels for most of these controls on the page. Instead of adding a duplicate label to the markup (through aria-label), we should strive to create the correct link between the existing label and the input control (through IDs + htmlFor) so we get "accessibility for free" by using HTML "correctly".
 - If we _must_ use `aria-label` (because there is not a label already on the page), it should be a plain English label just as if it were visible on the page.

I think these points apply to most of the aria-label usage in this PR, and I didn't want to just copy-paste the same comment all the time, so be sure to check over the diff 😌 

Feel free to reach out to us in #user-essentials if you want more clarification or want to pair up to tackle some of these! I don't mean to dump more on their plate, but maybe @kaydelaney might have some thoughts here??

**Comment by andresmgot** [comment]
Thanks for the review both of you! I have updated it to use IDs (`htmlFor` + `id`) so let me know what you think (or if I missed anything).

File: packages/grafana-ui/src/components/Select/MultiValue.tsx [hunk 13]
```diff
@@ -27,7 +28,7 @@ export const MultiValueRemove: React.FC<MultiValueRemoveProps> = ({ children, in
   const styles = getSelectStyles(theme);
   return (
     <div {...innerProps} className={styles.multiValueRemove}>
-      <Icon name="times" size="sm" />
+      <IconButton name="times" size="sm" aria-label="select multi clear value" />
```
Comment (joshhunt) [inline packages/grafana-ui/src/components/Select/MultiValue.tsx:31]: Actually, it looks like the `<div>` on line 30 is the actual interactable element (which receives the onClick handler), so IT should either be a `<button>`/`<IconButton>`, or have role=button. 

It already has an `aria-label`, so we shouldn't need one on the Icon.

image

I think you should be able to do just:


```tsx
<div {...innerProps} className={styles.multiValueValue} aria-role="button">
  <Icon name="times" size="sm" />
</div>
```

:)

**Review by joshhunt — APPROVED** [review]
Awesome stuff - looks good to me!!! Just check out the MutliValue button, then i think this is good to go in. 👍🏻

File: packages/grafana-ui/src/components/Select/MultiValue.tsx (hunk 13 above)
Comment (andresmgot) [reply packages/grafana-ui/src/components/Select/MultiValue.tsx]: I tried it as you suggested but seems like `aria-role` cannot be used there:

Screenshot from 2022-01-25 12-15-46

I have also tried replacing the `div` with a `button` so the role is implicit but that completely breaks the style:

Screenshot from 2022-01-25 12-22-53

Also, using `IconButton` without an `aria-label` (because as you said, the aria-label is already in the div) won't work either.

The only solution to avoid the duplicity of the aria-label is to set the div with `role=button` (my last commit). Let me know what you think.

Comment (joshhunt) [reply packages/grafana-ui/src/components/Select/MultiValue.tsx]: Sorry yes!!! I meant `role` and not `aria-role`!!!

This looks good 👍🏻 👍🏻

**Comment by andresmgot** [comment]
hey @kaydelaney I need your :+1: here in order to be able to proceed.

File: packages/grafana-ui/src/components/Select/MultiValue.tsx (hunk 13 above)
Comment (kaydelaney) [reply packages/grafana-ui/src/components/Select/MultiValue.tsx]: Just using `role=button` won't make the element keyboard accessible.
Would using the following not work?
```tsx
  return <IconButton {...innerProps} name="times" size="sm" className={styles.multiValueRemove} />;
```

Comment (andresmgot) [reply packages/grafana-ui/src/components/Select/MultiValue.tsx]: Thanks for the suggestion, that works too @kaydelaney :+1: 

One minor change is that now a circle appears around the close icon but that should be fine:

Peek 2022-01-25 16-42

**Review by kaydelaney — APPROVED** [review]
