### PR TITLE
CloudWatch: Add labels for Metric Query type queries

### LINKED ISSUE #69591: Alerting: Alert using Cloudwatch metric query with GROUP BY is not labeling correctly
### 
# What went wrong?

**What happened**:

  - Using a Cloudwatch Metric Query that uses GROUP BY results in the group-by field not being set to the corresponding value. Instead, all results are set to one identical value. The initial query/graph looks fine, but when applying mathematical expressions on the query, the correct label changes.

image

### 
# How do we reproduce it?

**Step 1**:

- Create an alert using CloudWatch Metrics, specifically Metric Query using a Group By clause.

**Step 2**:

- Apply math expression to query result like mean.

**Step 3**:

- Run/preview the query

### 
# What Grafana version are you using?

v9.4.7

### 
### Is the bug inside a Dashboard Panel?

_No response_

### Grafana Platform?

Docker

### User's OS?

_No response_

### User's Browser?

Chrome, Firefox, Opera

### Is this a Regression?

None

### Are Datasources involved?

Cloudwatch

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by kevinwcyu**
**What is this feature?**

Adds the name of the series as a label for `Metric Query` type queries.

**Why do we need this feature?**

The label in expressions in alerts show "Series 1", "Series 2", etc. because the fields in the data frames don't have any labels.

**Who is this feature for?**

**Which issue(s) does this PR fix?**:

Fixes #69591

**Special notes for your reviewer:**

**Example query with multiple group by fields**
query
Screenshot 2024-04-17 at 10 26 32 AM

**Example query without group by clause**
no group by

**Example query with a dimension that doesn't have a value (AWS returns "Other" for any dimensions without a value, see https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-metrics-insights-querylanguage.html)**
query with dimension with no value
Screenshot 2024-04-17 at 10 25 38 AM

Originally, I was trying to use the `GROUP BY` values as keys and the label returned by the GetMetricData API as the value for the labels. However, the label returned by CloudWatch's GetMetricData API returns a single string for the label field, which doesn't work if multiple fields are specified in the `GROUP BY` clause because the values could have spaces in them making it hard to determine how to split the string and associate the values with the `GROUP BY` fields. I tried to using the same method in https://github.com/grafana/grafana/pull/84835 to build a custom well-formed label that would make it easier to parse into separate values, but the `GROUP BY` fields for metric insights queries don't return anything when using the `${PROP('Dim.%s')}` dynamic label.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/tsdb/cloudwatch/response_parser.go [hunk 1]
```diff
@@ -195,7 +195,14 @@ func buildDataFrames(ctx context.Context, startTime time.Time, endTime time.Time
...
 		name := label
 		var labels data.Labels
-		if features.IsEnabled(ctx, features.FlagCloudWatchNewLabelParsing) {
+		if query.GetGetMetricDataAPIMode() == models.GMDApiModeSQLExpression {
+			metricQueryLabel := label
+			if hasStaticLabel {
+				metricQueryLabel = query.Label
+			}
+			labels = data.Labels{}
+			labels["Series"] = metricQueryLabel
```
Comment (iwysiu) [inline pkg/tsdb/cloudwatch/response_parser.go:204]: nit: I think you can do this as one line
```suggestion
			labels = data.Labels{"Series": metricQueryLabel}
```

File: pkg/tsdb/cloudwatch/response_parser_test.go [hunk 2]
```diff
@@ -391,7 +391,7 @@ func Test_buildDataFrames_parse_label_to_name_and_labels(t *testing.T) {
 			},
 			Statistic:        "Average",
 			Period:           60,
-			MetricQueryType:  models.MetricQueryTypeQuery,
+			MetricQueryType:  models.MetricQueryTypeSearch,
```
Comment (iwysiu) [inline pkg/tsdb/cloudwatch/response_parser_test.go:394]: Were these set to the wrong query type before? Otherwise it seems like we're losing tests?

File: pkg/tsdb/cloudwatch/response_parser.go [hunk 3]
```diff
@@ -195,7 +195,14 @@ func buildDataFrames(ctx context.Context, startTime time.Time, endTime time.Time
 
 		name := label
 		var labels data.Labels
-		if features.IsEnabled(ctx, features.FlagCloudWatchNewLabelParsing) {
+		if query.GetGetMetricDataAPIMode() == models.GMDApiModeSQLExpression {
+			metricQueryLabel := label
+			if hasStaticLabel {
```
Comment (iwysiu) [inline pkg/tsdb/cloudwatch/response_parser.go:200]: Do you have to do this? It looks like this query mode returns actually returns the static label as the label (unless I just didn't try the right query)

**Review by iwysiu — COMMENTED** [review]
If you want, you could attempt to do the string matching thing I was trying before https://github.com/grafana/grafana/pull/74847 for this, but that is much more complex and not always right, so I get avoiding it entirely. This should cover most use cases.

Just a couple comments!

File: pkg/tsdb/cloudwatch/response_parser.go (hunk 3 above)
Comment (kevinwcyu) [reply pkg/tsdb/cloudwatch/response_parser.go:200]: Without this I was getting results where the label returned from CW includes the `GROUP BY` field appended to the static label.

Screenshot 2024-04-09 at 8 15 56 AM

File: pkg/tsdb/cloudwatch/response_parser_test.go (hunk 2 above)
Comment (kevinwcyu) [reply pkg/tsdb/cloudwatch/response_parser_test.go:394]: Yea, they were the wrong query type before. `MetricQueryTypeSearch` uses dimensions, whereas `MetricQueryTypeQuery` doesn't use that field from the query object. It uses the `SqlExpression` field which is a SQL string that includes how the metrics are filtered and grouped.

File: pkg/tsdb/cloudwatch/response_parser.go (hunk 3 above)
Comment (kevinwcyu) [reply pkg/tsdb/cloudwatch/response_parser.go]: Removed this change, the static label will only be applied to the field name instead of the labels.

File: pkg/tsdb/cloudwatch/get_dimension_values_for_wildcards_test.go [hunk 4]
```diff
@@ -99,10 +64,135 @@ func TestGetDimensionValuesForWildcards(t *testing.T) {
...
 		api.On("ListMetricsPagesWithContext").Return(nil)
-		queries, err = executor.getDimensionValuesForWildcards(ctx, "us-east-1", api, []*models.CloudWatchQuery{query}, tagValueCache, 50)
+		queries, err = executor.getDimensionValuesForWildcards(ctx, "us-east-1", api, []*models.CloudWatchQuery{query}, tagValueCache, 50, noSkip)
 		assert.Nil(t, err)
 		assert.Len(t, queries, 1)
 		assert.Equal(t, map[string][]string{"Test_DimensionName2": {"Value"}}, queries[0].Dimensions)
 		api.AssertExpectations(t)
 	})
+
+	t.Run("MetricSearch query type", func(t *testing.T) {
```
Comment (iwysiu) [inline pkg/tsdb/cloudwatch/get_dimension_values_for_wildcards_test.go:74]: Is there a reason these moved?

**Review by iwysiu — COMMENTED** [review]
Nice! I left a couple comments

File: pkg/tsdb/cloudwatch/get_dimension_values_for_wildcards_test.go (hunk 4 above)
Comment (kevinwcyu) [reply pkg/tsdb/cloudwatch/get_dimension_values_for_wildcards_test.go:74]: i was grouping these tests by the query type. The tests that were left in their original spots are for caching so i left them ungrouped.

File: pkg/tsdb/cloudwatch/get_dimension_values_for_wildcards.go [hunk 5]
```diff
@@ -58,6 +68,14 @@ func (e *cloudWatchExecutor) getDimensionValuesForWildcards(ctx context.Context,
 				newDimensions = append(newDimensions, resp.Value)
 			}
 
+			// Metric Insights metrics might not have a value for a dimension specified in the `GROUP BY` clause
+			// of the query. When this happens, we use an empty string to indicate in order to keep the
+			// dimension key available in `query.Dimensions` so we can build the labels when we parse the response
+			// See the note under `GROUP BY` in https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-metrics-insights-querylanguage.html
+			if len(newDimensions) == 0 && query.MetricQueryType == models.MetricQueryTypeQuery {
```
[the remark this answers is not in the document]
Comment (kevinwcyu) [reply pkg/tsdb/cloudwatch/get_dimension_values_for_wildcards.go:75]: The empty string was actually for building the label https://github.com/grafana/grafana/pull/85766/files#diff-0b6cabdae8ebaebfdcc947470593cc4640687c733a604b4cc0616b279fdb8c9fR149 checks for an empty string.

I actually just changed it to check for an empty slice instead so I removed the adding of the empty string. But I moved the `query.MetricQueryType == models.MetricQueryTypeQuery` check to the check on line 80 so it should still get cached.

File: pkg/tsdb/cloudwatch/response_parser.go [hunk 6]
```diff
@@ -138,6 +138,30 @@ func getLabels(cloudwatchLabel string, query *models.CloudWatchQuery) data.Label
 	return labels
 }
 
+func getLabelsForMetricQuery(cloudwatchLabel string, query *models.CloudWatchQuery) data.Labels {
+	labels := data.Labels{}
+
+	if len(query.Dimensions) == 0 {
+		labels["Series"] = cloudwatchLabel
```
[the remark this answers is not in the document]
Comment (kevinwcyu) [reply pkg/tsdb/cloudwatch/response_parser.go]: Added the bool flag for `getLabels` to add the original label as `Series` and am just using `getLabels` now. The `Series` will be included for Metric Query types as a fallback.

**Review by iwysiu — APPROVED** [review]
It looks good! Sorry to be annoying about the cache, but I just remembered that I originally wasn't adding empty arrays to the cache due to concern about storing unhelpful infomation/someone potentially malevolently creating a very large number of empty cache values with dimensions that don't exist. What do you think, is that paranoid or a legitimate concern?

**Comment by kevinwcyu** [comment]
> It looks good! Sorry to be annoying about the cache, but I just remembered that I originally wasn't adding empty arrays to the cache due to concern about storing unhelpful infomation/someone potentially malevolently creating a very large number of empty cache values with dimensions that don't exist. What do you think, is that paranoid or a legitimate concern?

@iwysiu, I'd assume most use cases would involve people using the dropdown to select the dimensions in which case i believe the vast majority of the cases will have values any way. I'd also assume that most people who have been given edit access to write queries would not intentionally write non-useful queries where most of the dimensions used are empty.

**Comment by kevinwcyu** [comment]
@iwysiu, just an fyi. i've taken out the caching of dimensions with empty values for now. i think for most queries, people will be using the dimension keys from the drop down anyway so it won't be too big of a deal to not cache those empty values.
