### PR TITLE
Query Editor: Fix viz and data pane layout

### LINKED ISSUE #117744: QueryEditor v2: layout issue when the dashboard has many variables
### What happened?

When you have multiple rows of variables, they are hidden behind the panel when editing.

Image

### What did you expect to happen?

The panel should not overlap with the variables and other elements

### Did this work before?

Yes, I tried disabling our toggle and it was back to normal, so seems related to the v2 changes. 

### How do we reproduce it?

You can see it [here](https://querynext.grafana-dev.net/d/d2e206e1-f72b-448c-83d8-657831c2ea6d/overview?orgId=1&from=now-3h&to=now&timezone=browser&var-DS_PROMETHEUS=grafanacloud-play-prom&var-DS_TEMPO=grafanacloud-play-traces&var-DS_LOKI=grafanacloud-play-logs&refresh=1m&editPanel=9).

### Is the bug inside a dashboard panel?

_No response_

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by alexjonspencer1**
## Description
Resolves #117744

In the new layout component `VizAndDataPaneNext`, we invoke a hook that handles all of the complicated layout logic. This hook had `const CONTROLS_ROW_HEIGHT_PX = 32`, when in fact dashboard controls height is variable based on the number of variables! So, the fix was to initially set this to 'auto' to let the controls dictate their own height. This led to a cascade of downstream layout changes 😅 

Note: I also changed the initial height of the visualization to be taller (this came up recently!)

## Changes
Please refer to code as documentation here.

## Risks
This is low risk

#### Before
image

#### After
image

## Testing Instructions

* If you wouldn't mind pulling it down locally and testing with panels that have various numbers of custom variables 😄 

## Reviewer Checklist

- [ ] Tests are added where applicable
- [ ] Issue is linked to PR
- [ ] Code pulled and tested
- [ ] Code is meaningfully improved if applicable

### CODE REVIEW

File: public/app/features/dashboard-scene/scene/DashboardControls.tsx [hunk 1]
```diff
@@ -322,7 +322,7 @@ function getStyles(theme: GrafanaTheme2, isQueryEditorNext: boolean) {
       flexWrap: 'wrap-reverse',
       ...(isQueryEditorNext && {
         padding: 0,
-        marginBottom: theme.spacing(1),
+        marginBottom: theme.spacing(-1),
```
Comment (Develer) [inline public/app/features/dashboard-scene/scene/DashboardControls.tsx:325]: I'm wondering if there is a way to avoid a negative margin. Could you check this?

**Review by Develer — DISMISSED** [review]
Works as expected to me! Left a small question for improvement.

https://github.com/user-attachments/assets/3d517b39-0ab8-4f21-af6b-1884cb1e4586

File: public/app/features/dashboard-scene/panel-edit/PanelEditNext/hooks.ts [hunk 2]
```diff
@@ -139,10 +139,11 @@ export function usePanelEditorShell(model: PanelEditor) {
 }
 
 export function useVizAndDataPaneLayout(model: PanelEditor, containerHeight: number) {
-  const CONTROLS_ROW_HEIGHT_PX = 32;
+  const CONTROLS_ROW_HEIGHT = 'auto';
   const SIDEBAR_MIN_WIDTH = 285;
   const SIDEBAR_MAX_WIDTH = 380;
-  const VIZ_MIN_HEIGHT = 200;
+  const VIZ_MIN_HEIGHT = 0;
```
Comment (Develer) [inline public/app/features/dashboard-scene/panel-edit/PanelEditNext/hooks.ts:145]: Also noticed that we could completely hide the visualization now. Just wondering if it's intentional and by design.

cc @jotasolano

File: public/app/features/dashboard-scene/scene/DashboardControls.tsx (hunk 1 above)
Comment (alexjonspencer1) [reply public/app/features/dashboard-scene/scene/DashboardControls.tsx:325]: I think we should leave it for now. Basically, there are a lot of "dashboard control" elements that all _individually_ apply a margin bottom. We'd have to go into each of those components, do a check for the feature toggle, and conditionally apply css styles. That would be super messy. This negative margin, while janky, fixes this short term problem in one place, instead of having to make changes in multiple places.

File: public/app/features/dashboard-scene/panel-edit/PanelEditNext/hooks.ts (hunk 2 above)
Comment (alexjonspencer1) [reply public/app/features/dashboard-scene/panel-edit/PanelEditNext/hooks.ts:145]: Yep, that's by design! Today in the legacy experience we allow the visualization to be hidden completely using the drag handler.

**Review by sgriff96 — APPROVED** [review]
Looks good to me!
