### PR TITLE
Stars: Fix starred state not being updated

### LINKED ISSUE #111529: Starring dashboards no longer works in 12.2.0
### What happened?

Both manually starring dashboards or via the API does not work in 12.2.0.

### What did you expect to happen?

That the dashboard is starred.

### Did this work before?

Works in 11.6.6 and previous versions.
Works in 12.1.1 and previous versions.

### How do we reproduce it?

1. Click the star
2. It says the dashboard has been starred
3. Change to another dashboard
4. Go back to the dashboard starred in step 1
5. Error: The dashboard is not starred anymore

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 12.2.0
OS: Windows
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by Clarity-89**
**What is this feature?**

Make sure the starred dashboard's state is properly updated after starring. 

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/111529

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]

File: public/app/features/stars/StarToolbarButton.tsx [hunk 1]
```diff
@@ -63,18 +64,29 @@ export function StarToolbarButtonApiServer({ group, kind, id }: Pick<Props, 'gro
...
 
 function StarToolbarButtonLegacy({ dashboard }: { dashboard: Props['dashboard'] }) {
-  const { meta } = dashboard.useState();
-  const isStarred = Boolean(meta.isStarred);
+  const { meta, uid: uidFromState } = dashboard.useState();
+  // uidFromState is used for legacy dashboards (kubernetesDashboards toggle is off)
+  const uid = meta.uid || meta.k8s?.name || uidFromState;
   const tooltips = getStarTooltips();
 
+  const { value, retry } = useAsyncRetry(async () => {
```
Comment (tdbishop) [inline public/app/features/stars/StarToolbarButton.tsx]: nit: on naming, can `value` be more descriptive? Like `usersStars` or `starredDashboardIds`?

**Review by tomratcliffe — APPROVED** [review]
:+1: I noticed that the navmenu doesn't update the starred items until after refresh - I think we need some tidy up to centralise this starring logic (everywhere should use the `StarToolbarButton` that's in DashList and we should remove the onStarDashboard method

(approving as this still improves things)

**Comment by Clarity-89** [comment]
> 👍 I noticed that the navmenu doesn't update the starred items until after refresh - I think we need some tidy up to centralise this starring logic (everywhere should use the `StarToolbarButton` that's in DashList and we should remove the onStarDashboard method
> 
> (approving as this still improves things)

I'm not sure that ever worked, e.g., DashList has a [special logic](https://github.com/grafana/grafana/blob/b50737a76ceaa301d07deda42b8336e20b6d7953/public/app/plugins/panel/dashlist/DashList.tsx#L155) for that, which I'm not a fan of. It's pretty straightforward to get working with the new star k8s API, but the workaround for the legacy is pretty ugly.

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/18197362368)
- Version: 12.3.0-18197362368

**Comment by ghost** [comment]
The backport to `release-12.2.1` failed:

```
error cherry-picking: error running git cherry-pick: error running command 'git cherry-pick -x 8cb10d45ea07d15d7c93e4ee627fd81ef7d9eb93'
error: exit status 1
stdout: Auto-merging public/app/features/dashboard-scene/scene/DashboardScene.tsx
CONFLICT (modify/delete): public/app/features/stars/StarToolbarButton.tsx deleted in HEAD and modified in 8cb10d45ea0 (Stars: Fix starred state not being updated (#111936)).  Version 8cb10d45ea0 (Stars: Fix starred state not being updated (#111936)) of public/app/features/stars/StarToolbarButton.tsx left in tree.

stderr: error: could not apply 8cb10d45ea0... Stars: Fix starred state not being updated (#111936)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"

```

To backport manually, run these commands in your terminal:

```bash
git fetch
git switch --create backport-111936-to-release-12.2.1 origin/release-12.2.1
git cherry-pick -x 8cb10d45ea07d15d7c93e4ee627fd81ef7d9eb93
```

Resolve the conflicts, then add the changes and run `git cherry-pick --continue`:

```bash
git add . && git cherry-pick --continue
```

If you have the [GitHub CLI](https://cli.github.com/) installed:

```bash
git push --set-upstream origin backport-111936-to-release-12.2.1
PR_BODY=$(gh pr view 111936 --json body --template 'Backport 8cb10d45ea07d15d7c93e4ee627fd81ef7d9eb93 from #111936{{ "\n\n---\n\n" }}{{ index . "body" }}')
echo "${PR_BODY}" | gh pr create --title '[release-12.2.1] Stars: Fix starred state not being updated' --body-file - --label 'backport' --label '' --label 'area/frontend' --label 'add to changelog' --base release-12.2.1 --web
```

Or, if you don't have the GitHub CLI installed ([we recommend you install it!](https://github.com/cli/cli#installation)):

```bash
git push --set-upstream origin backport-111936-to-release-12.2.1
```

And open a pull request where the `base` branch is `release-12.2.1` and the `compare`/`head` branch is `backport-111936-to-release-12.2.1`

**Comment by tomratcliffe** [comment]
Ah yes, that was it - it doesn't work with the new app platform API, because we have it all a bit inconsistently implemented right now. The new component should have that hacky logic in it (or we should sort out the state/store for starred items anyway in general :D )
