### PR TITLE
Datasource: making sure we are having the same data field order when using mixed data sources.

### LINKED ISSUE #20555: Mixed Datasource: Order of results depend on when queries finish (regression in 6.4)
**What happened**:
With grafana update 6.4.4,in table with mixed datasource (different, but all elasticsearch datasource), we cannot reorder columns, in fact between dashboard refreshes the column ordering change. Below a table panel with the problem between three clicks of the refresh:

refresh1

refresh2

refresh3

**What you expected to happen**:
In dashboard refreshes the column ordering not change
**How to reproduce it (as minimally and precisely as possible)**:
With refresh of a table with mixed datasource
**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v 6.4.4
- Data source type & version: Mixed Elasticsearch datasource
- OS Grafana is installed on: Centos 7
- User OS & Browser: Windows 7, Mozilla Firefox & Chrome
- Grafana plugins: Table Panel (Native Plugin)
- Others:

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
When having a panel that uses queries from multiple datasources the order of the data fields will be displayed on the order of how the datasource responses is received. When having datasources that varies in the response times this makes the data fields to change places.

It is really good described in the referenced issue.

**Which issue(s) this PR fixes**:
Fixes #20555 

**Special notes for your reviewer**:
Instead of using merge we are using forkJoin. 

- Is it okay to use the `request.requestId` as the key for the response being returned? Or can this cause any issues?

- Didn't really looked into how we handle errors. But that might also be affected by this change.

### CODE REVIEW

File: public/app/plugins/datasource/mixed/MixedDataSource.ts [hunk 1]
```diff
@@ -105,7 +105,19 @@ export class MixedDatasource extends DataSourceApi<DataQuery> {
       observables.push(observable);
     }
 
-    return merge(...observables);
+    return forkJoin(observables).pipe(
```
Comment (dprokop) [inline public/app/plugins/datasource/mixed/MixedDataSource.ts]: Does forkJoin guarantee order?

Comment (mckn) [reply public/app/plugins/datasource/mixed/MixedDataSource.ts]: Yes, it will return the results in the order of the passed observables.

https://indepth.dev/learn-to-combine-rxjs-sequences-with-super-intuitive-interactive-diagrams/#forkjoin

Comment (dprokop) [reply public/app/plugins/datasource/mixed/MixedDataSource.ts]: woohoo 🍾

**Comment by mckn** [comment]
Looking at the failing tests aws

**Comment by mckn** [comment]
hmm, I was trying to do this instead:

`forkJoin(observables).pipe(mergeAll())`

Which I believe should work but when running it in the app and making the first query slower than the second one it never completes.

**Comment by torkelo** [comment]
think this looks ok, should be safe to use requestId as key as your combining all results into one and only returning a single packet

**Comment by mckn** [comment]
@torkelo yeah, I tried to use the mergeAll to keep the series of data created earlier. But it doesn't  seem to detect the complete of the second one. For some reason.

**Comment by mckn** [comment]
@torkelo @dprokop please have one more look at this one and see what you think.

**Comment by dprokop** [comment]
Code-wise it looks great! Testing it

**Review by dprokop — APPROVED** [review]
OK, this seems to work fine! 🚀
