### PR TITLE
Chore: eslint react hook fix for public folder

### LINKED ISSUE #27391: Chore: Enable and fix eslint-plugin-react-hooks warning and errors in the monorepo
After https://github.com/grafana/grafana/pull/26094 merged the we can start to work on enabling eslint-plugin-react-hooks for the packages and the main app.
As of today (2020.09.04.) there are ✖ 169 problems (86 errors, 83 warnings) in the whole monorepo after enabling the rules.
The plan is to fix these warnings continuously.

- [x] grafana-toolkit 26problems total -  React Hook "useSpinner" cannot be called at the top level. React Hooks must be called in a React function component or a custom React Hook function - This error should be silenced by leaving an override in the root eslintrc
- [x] grafana-ui has 58 problems total (I think this should be separated to storybook errors and component errors) Fixing the component errors we must make sure that we can not create any regressions.
  - [x] storybook errors
  - [x] component errors
  - [x] ~uPlot - 25 warnings.~ added to the eslintignore 
- [x] jaeger-ui-components 4 problems total
- [ ] public folder 81 problems total This is where things can get south real quick so we should focus not to create any regressions here (it is probably a good idea to divy this up to smaller chunks and not to do the whole in one pr)

To see the errors simply remove the overrides property in the eslintrc file and run yarn lint.

### PR DESCRIPTION
**Pull request by zoltanbedi**
**What this PR does / why we need it**:

This is probably the last pr to get rid of the react-hook errors/warnings for the public/app folder. This needs some heavy testing. I tried to always check that I don't break anything but there might be problems that I didn't find.

**Which issue(s) this PR fixes**:

Fixes #27391

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by joshhunt** [comment]
I was just wondering about this line rule yesterday!

**Comment by hugohaggmark** [comment]
Looks like a lot of GraphNG things, I'm adding @dprokop  and @mckn to test/review.

**Review by dprokop — COMMENTED** [review]
@zoltanbedi I suggest not touching BarChart, TimeSeries, Sparkline, XYChart, GraphNG, Plot and other uPlot related components until https://github.com/grafana/grafana/pull/30941 is merged.

**Review by ivanahuckova — COMMENTED** [review]
@zoltanbedi  I have reviewed and tested RichHistory, PromLink, NodeGraph changes and looked at Loki + Elastic changes where we are using `ignore next line`. All changes in these files look 🤩 and work as expected. I have left 1 question below.  For Traces, I would prefer if @aocenas would check them as I don't work with traces much and I am can no 100% test the behaviour, just look at the code.

File: public/app/plugins/panel/nodeGraph/NodeGraphPanel.tsx [hunk 1]
```diff
@@ -5,6 +5,7 @@ import { NodeGraph } from '@grafana/ui';
 import { useLinks } from '../../../features/explore/utils/links';
 
 export const NodeGraphPanel: React.FunctionComponent<PanelProps<Options>> = ({ width, height, data }) => {
+  const getLinks = useLinks(data.timeRange);
   if (!data || !data.series.length) {
```
Comment (ivanahuckova) [inline public/app/plugins/panel/nodeGraph/NodeGraphPanel.tsx:9]: Why this change? Isn't it redundant no run useLinks if we pass no data and we are not going to use the getLinks at the end?

**Comment by dprokop** [comment]
@zoltanbedi #30941 is now on master.

File: public/app/plugins/panel/nodeGraph/NodeGraphPanel.tsx (hunk 1 above)
Comment (zoltanbedi) [reply public/app/plugins/panel/nodeGraph/NodeGraphPanel.tsx:9]: While it makes sense what you are saying it violates the [rules of hooks](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level).

> Don’t call Hooks inside loops, conditions, or nested functions. Instead, always use Hooks at the top level of your React function. By following this rule, you ensure that Hooks are called in the same order each time a component renders. That’s what allows React to correctly preserve the state of Hooks between multiple useState and useEffect calls.

**Review by joshhunt — APPROVED** [review]
gave the Azure stuff a look over and a test - everything seems right!

**Comment by gabor** [comment]
i verified the code-change in the influxdb-data-source-code seems to be correct, also tested the influxdb datasource and it works fine. i also went through the diff and tried to quickly scan it and all the changes seemed to be legitimate on the surface.

File: public/app/features/dashboard/components/PanelEditor/VisualizationTab.tsx [hunk 2]
```diff
@@ -30,17 +30,20 @@ export const VisualizationTabUnconnected = React.forwardRef<HTMLInputElement, Pr
...
+          changePanelPlugin(panel, meta.id);
+        }
+      },
+      [changePanelPlugin, onToggleOptionGroup, panel, plugin.meta.id]
+    );
 
     const onKeyPress = useCallback(
       (e: React.KeyboardEvent<HTMLInputElement>) => {
-        if (e.key === 'Enter') {
+        if (e.key === 'Enter' && plugin) {
```
Comment (mckn) [inline public/app/features/dashboard/components/PanelEditor/VisualizationTab.tsx:46]: Nit: do we have incorrect typings on this component? Looks like plugin always should have a value.

File: public/app/features/dashboard/components/PanelEditor/usePanelLatestData.ts [hunk 3]
```diff
@@ -35,6 +35,7 @@ export const usePanelLatestData = (panel: PanelModel, options: GetDataOptions):
      * Adding separate options to dependencies array to avoid additional hook for comparing previous options with current.
      * Otherwise, passing different references to the same object may cause troubles.
      */
+    // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [panel, options.withFieldConfig, options.withTransforms]);
```
Comment (mckn) [inline public/app/features/dashboard/components/PanelEditor/usePanelLatestData.ts:39]: Nit: should we have a dependency on the `setLatestData` here?

Comment (mckn) [reply public/app/features/dashboard/components/PanelEditor/usePanelLatestData.ts:39]: and maybe destructuring the options object.

Comment (zoltanbedi) [reply public/app/features/dashboard/components/PanelEditor/usePanelLatestData.ts:39]: > Nit: should we have a dependency on the `setLatestData` here?

Nah, the setter from useState is always same so it doesn't need to be added to the dependency array. See https://reactjs.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often

> and maybe destructuring the options object.
Not sure about that. @dprokop do you have any thoughts about it?

File: public/app/features/dashboard/components/PanelEditor/VisualizationTab.tsx (hunk 2 above)
Comment (zoltanbedi) [reply public/app/features/dashboard/components/PanelEditor/VisualizationTab.tsx]: yep, fixed.

File: public/app/features/variables/editor/SelectionOptionsEditor.tsx [hunk 4]
```diff
@@ -19,21 +19,21 @@ export const SelectionOptionsEditor: FunctionComponent<SelectionOptionsEditorPro
     (event: ChangeEvent<HTMLInputElement>) => {
       props.onMultiChanged(toVariableIdentifier(props.variable), event.target.checked);
     },
-    [props.onMultiChanged, props.variable]
+    [props]
```
Comment (mckn) [inline public/app/features/variables/editor/SelectionOptionsEditor.tsx:22]: Nit: could we destruct the props in this component to prevent having dependency on the whole props object?

File: public/app/features/variables/editor/SelectionOptionsEditor.tsx [hunk 5]
```diff
@@ -19,21 +19,21 @@ export const SelectionOptionsEditor: FunctionComponent<SelectionOptionsEditorPro
...
   );
 
   const onIncludeAllChanged = useCallback(
     (event: ChangeEvent<HTMLInputElement>) => {
       props.onPropChange({ propName: 'includeAll', propValue: event.target.checked });
     },
-    [props.onPropChange]
+    [props]
```
Comment (mckn) [inline public/app/features/variables/editor/SelectionOptionsEditor.tsx:29]: Nit: could we destruct the props in this component to prevent having dependency on the whole props object?

File: public/app/features/variables/editor/SelectionOptionsEditor.tsx [hunk 6]
```diff
@@ -19,21 +19,21 @@ export const SelectionOptionsEditor: FunctionComponent<SelectionOptionsEditorPro
...
   );
 
   const onAllValueChanged = useCallback(
     (event: FormEvent<HTMLInputElement>) => {
       props.onPropChange({ propName: 'allValue', propValue: event.currentTarget.value });
     },
-    [props.onPropChange]
+    [props]
```
Comment (mckn) [inline public/app/features/variables/editor/SelectionOptionsEditor.tsx:36]: Nit: could we destruct the props in this component to prevent having dependency on the whole props object?

File: public/app/plugins/datasource/cloud-monitoring/components/Aggregations.tsx [hunk 7]
```diff
@@ -69,7 +69,7 @@ const useAggregationOptionsByMetric = ({ metricDescriptor }: Props): Array<Selec
       ...a,
       label: a.text,
     }));
-  }, [metricDescriptor?.metricKind, metricDescriptor?.valueType]);
+  }, [metricDescriptor]);
```
Comment (mckn) [inline public/app/plugins/datasource/cloud-monitoring/components/Aggregations.tsx:72]: nit: maybe change so we do the following on the top of the function.
```
const useAggregationOptionsByMetric = ({ metricDescriptor }: Props): Array<SelectableValue<string>> => {
  const valueType = metricDescriptor?.valueType;
  const metricKind = metricDescriptor?.metricKind;

  return useMemo(() => {
    if (!valueType || !metricKind) {
      return [];
    }

    return getAggregationOptionsByMetric(valueType, metricKind).map((a) => ({
      ...a,
      label: a.text,
    }));
  }, [valueType, metricKind]);
};

File: public/app/plugins/datasource/cloud-monitoring/components/MetricQueryEditor.tsx [hunk 8]
```diff
@@ -56,9 +56,9 @@ function Editor({
     if (query && query.projectName && query.metricType) {
       datasource
         .getLabels(query.metricType, refId, query.projectName, query.groupBys)
-        .then((labels) => setState({ ...state, labels }));
+        .then((labels) => setState((prevState) => ({ ...prevState, labels })));
     }
-  }, [query.projectName, query.groupBys, query.metricType]);
+  }, [query.projectName, query.groupBys, query.metricType, query, datasource, refId]);
```
[the remark this answers is not in the document]
Comment (mckn) [reply public/app/plugins/datasource/cloud-monitoring/components/MetricQueryEditor.tsx:61]: Nit: maybe do destructoring of the query object.

File: public/app/plugins/datasource/cloudwatch/components/ConfigEditor.tsx [hunk 9]
```diff
@@ -38,7 +38,12 @@ export const ConfigEditor: FC<Props> = (props: Props) => {
              from environment variables or IAM roles'
       );
     }
-  }, []);
+  }, [
+    props.options.jsonData.authType,
```
Comment (mckn) [inline public/app/plugins/datasource/cloudwatch/components/ConfigEditor.tsx:42]: Nit: I think destructing would be nice in this scenario as well.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/MetricsQueryEditor.test.tsx [hunk 10]
```diff
@@ -79,7 +79,7 @@ describe('Azure Monitor QueryEditor', () => {
     const mockDatasource = createMockDatasource();
     const onChange = jest.fn();
     const mockQuery = createMockQuery();
-    mockDatasource.getMetricNames = jest.fn().mockResolvedValueOnce([
+    mockDatasource.getMetricNames = jest.fn().mockResolvedValue([
```
Comment (mckn) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/MetricsQueryEditor.test.tsx:82]: Nit: is this done on purpose?

File: public/app/plugins/panel/dashlist/DashList.tsx [hunk 11]
```diff
@@ -82,17 +82,7 @@ export function DashList(props: PanelProps<DashListOptions>) {
...
-  }, [
-    props.options.showSearch,
-    props.options.showStarred,
-    props.options.showRecentlyViewed,
-    props.options.maxItems,
-    props.options.query,
-    props.options.tags,
-    props.options.folderId,
-    props.replaceVariables,
-    props.renderCounter,
```
Comment (mckn) [inline public/app/plugins/panel/dashlist/DashList.tsx:94]: Nit: I think we might want to keep the `renderCounter` since that is used on the angular side to trigger a re-render. But with that said I have not tested this code so I'm not 100% sure.

File: public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin.tsx [hunk 12]
```diff
@@ -89,7 +89,7 @@ export const AnnotationsPlugin: React.FC<AnnotationsPluginProps> = ({ annotation
     return () => {
       unregister();
     };
-  }, []);
+  }, [plotCtx, theme.palette.red]);
```
Comment (mckn) [inline public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin.tsx:92]: Nit: I think that `useEffect` only should be run once.

File: public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin.tsx [hunk 13]
```diff
@@ -105,7 +105,7 @@ export const AnnotationsPlugin: React.FC<AnnotationsPluginProps> = ({ annotation
         y: plotInstance.bbox.height / window.devicePixelRatio + 4,
       };
     },
-    [plotCtx.getPlotInstance]
+    [plotCtx]
```
Comment (mckn) [inline public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin.tsx:108]: Nit: destructuring of the `getinstance` would be nice here.

File: public/app/plugins/panel/timeseries/plugins/ContextMenuPlugin.tsx [hunk 14]
```diff
@@ -42,7 +42,7 @@ export const ContextMenuPlugin: React.FC<ContextMenuPluginProps> = ({
 
   const onClick = useCallback(() => {
     setIsOpen(!isOpen);
-  }, [setIsOpen]);
+  }, [isOpen]);
```
Comment (mckn) [inline public/app/plugins/panel/timeseries/plugins/ContextMenuPlugin.tsx:45]: Question: what is best practice here? Use a dependency on the `set-function` or the value?

**Review by mckn — APPROVED** [review]
I have added some small nits and questions bot overall I think this is great! I have not tested all the code since this PR is really big but I have done some simple testing and it seems to work as expected.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/MetricsQueryEditor.test.tsx (hunk 10 above)
Comment (zoltanbedi) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/MetricsQueryEditor.test.tsx:82]: yes

File: public/app/plugins/panel/timeseries/plugins/ContextMenuPlugin.tsx (hunk 14 above)
Comment (zoltanbedi) [reply public/app/plugins/panel/timeseries/plugins/ContextMenuPlugin.tsx:45]: value, always. the set function shouldn't be a dependency.
