### PR TITLE
ElasticSearch: Improve ES error handling message

### LINKED ISSUE #61246: Elasticsearch error on fetching a preview does not give details about the error
**What happened**:
Elasticsearch query gave an error, when trying to preview a query on a new alert. No details about the error were provided.
```
Failed to evaluate queries and expressions: failed to execute query A: Unknown elasticsearch error response
```
afbeelding

**What you expected to happen**:
I would expect to see the error message that Elasticsearch gives.

I looked into the browser console on the network tab, and in the server logs, but I could not find additional information about the error message. Only when debugging locally (see section below) I could find additional information.

**How to reproduce it (as minimally and precisely as possible)**:
- Create new alert
- Use elasticsearch query with multiple aggregations and a big(ger) time range, which will result in a 'too many buckets error'
- There is a error popup: "Failed to evaluate queries and expressions: failed to execute query A: Unknown elasticsearch error response"

**Anything else we need to know?**:
When debugging the format of the response I got from Elasticsearch. Elastic
```
(*simplejson.Json)(0x14001fcd8d0)({
 data: (map[string]interface {}) (len=7) {
  (string) (len=9) "caused_by": (map[string]interface {}) (len=3) {
   (string) (len=11) "max_buckets": (float64) 65536,
   (string) (len=4) "type": (string) (len=26) "too_many_buckets_exception",
   (string) (len=6) "reason": (string) (len=196) "Trying to create too many buckets. Must be less than or equal to: [65536] but this number of buckets was exceeded. This limit can be set by changing the [search.max_buckets] cluster level setting."
  },
  (string) (len=10) "root_cause": ([]interface {}) {
  },
  (string) (len=4) "type": (string) (len=32) "search_phase_execution_exception",
  (string) (len=6) "reason": (string) "",
  (string) (len=5) "phase": (string) (len=5) "fetch",
  (string) (len=7) "grouped": (bool) true,
  (string) (len=13) "failed_shards": ([]interface {}) {
  }
 }
})
```
I got this info by adding to `spew.Dump(json)` to [elasticsearch/response_parser.go](https://github.com/grafana/grafana/blob/12c4098bcdb0838691dddcab19d52b7cc80e97f3/pkg/tsdb/elasticsearch/response_parser.go#L709-L712)
```
 func getErrorFromElasticResponse(response *es.SearchResponse) string {
 	var errorString string
 	json := simplejson.NewFromAny(response.Error)
+	spew.Dump(json)
         ...
}
```

**Environment**:
- Grafana version: 5.3.2 (also reproduced on main branch)
- Data source type & version: Elasticsearch 8.0+
- OS Grafana is installed on: Kubernetes 1.25
- User OS & Browser: macOS Monterey (version 12) 
- Grafana plugins: none
- Others: Elasticsearch version 8.5.3
```
> curl -s "localhost:9200/" | jq -r .version.number
8.5.3
```

### PR DESCRIPTION
**Pull request by ruudvanderweijde**
**What is this feature?**

The ElasticSearch response that I got from my query was not supported in the "getErrorFromElasticResponse" method. This method looks for `.reason` or `root_cause[0].reason`, but my error response had `caused_by.reason`. This was not supported.

**Why do we need this feature?**

As reported in the issue, I had an "Unknown elasticsearch error response" error, which didn't help me to figure out what I was doing wrong.

**Who is this feature for?**

Users with ES Datasource who get an error.

**Which issue(s) does this PR fix?**:

Fixes #61246

### CODE REVIEW

File: pkg/tsdb/elasticsearch/response_parser.go [hunk 1]
```diff
@@ -711,14 +712,17 @@ func getErrorFromElasticResponse(response *es.SearchResponse) string {
...
 	switch {
 	case rootCauseReason != "":
 		errorString = rootCauseReason
 	case reason != "":
 		errorString = reason
+	case causedByReason != "":
+		errorString = causedByReason
 	default:
-		errorString = "Unknown elasticsearch error response"
+		errorString = fmt.Sprintf("Unknown elasticsearch error response. Response = [%v]", json)
```
Comment (gabor) [inline pkg/tsdb/elasticsearch/response_parser.go:725]: could you please only do the `case causedByReason` switch, and not change the `default` case?

i understand the motivation (provide more debugging info in an unforeseen situation), but we are very careful with what we return intoto the browser, in case it contains something sensitive. and considering the `case causedByReason` fixes the current problem, i recommend only changing that, it will make the PR merged easier 😄 . thanks!

**Review by gabor — COMMENTED** [review]
nice work, thanks for the PR. there is a small issue i mentioned above, could you please take a look? thanks!

**Comment by gabor** [comment]
NOTE: an easy way to reproduce the situation with test-data:
- run `make devenv sources=elastic`
- connect to `http://localhost:9200`
- go to alerting, make an elastic query:
    -  use the `Count` metric
    - set the date_histogram/interval to `10s`
    - set the time-range to `last 90 days`
    - run the query

**Comment by ruudvanderweijde** [comment]
Thanks for the feedback, I'll update the code when I have some time.

File: pkg/tsdb/elasticsearch/response_parser.go (hunk 1 above)
Comment (ruudvanderweijde) [reply pkg/tsdb/elasticsearch/response_parser.go:725]: Would it be an option to write it to the server logs?

When I had the issue, I checked the browser console on the network tab and server logs, but couldn't find any information about the error.
I also checked elasticsearch errors, but also didn't see any error (this could of course be my configuration).

**Comment by ruudvanderweijde** [comment]
I've dropped the commit with the global error message.

**Review by gabor — APPROVED** [review]
nice work 👍
