### PR TITLE
TimePicker: fixing weird behavior with calendar when switching between months/years 

### LINKED ISSUE #21981: calendar sometimes closes itself when using new timepicker
**What happened**:

When we select dates in Absolute time range new calendar, it sometimes closes itself and does not validate selected start & end dates.

**What you expected to happen**:

After selection, see selected period in blue as expected, and be able to change it if needed before validate.

**How to reproduce it (as minimally and precisely as possible)**:

Just select a first date on calendar, blue circle appears around date, and then select a second date. Randomly, calendar closes itself and we have to start again.

**Anything else we need to know?**: - 

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: postgres
- OS Grafana is installed on: debian 9.11
- User OS & Browser: chrome 79.0.3945.88 on debian
- Grafana plugins: -
- Others: -

### LINKED ISSUE #22110: Time picker closes if a month or year is chosen (rather than a calendar date)
**What happened**: When trying to enter an absolute time range for the time picker
 (located under the clock widget on the home page), I tried to select an earlier date by first looking at all the months and then selecting the one I wanted. After selecting the month, the time picker closes.

**What you expected to happen**: I expected the time picker to show me the all calendar days (1-31) of the month I selected.

**How to reproduce it (as minimally and precisely as possible)**:
1. go to grafana's create dashboard home page
2. open the time picker (clock widget drops down the time picker)
3.  click on 'Absolute time range > from' input box (calendar opens)
4. click the month (February 2020)
* all the months should display in the calendar with February highlighted
5. click January => time picker closes after clicking

**Anything else we need to know?**: this also happens with years.

**Environment**:
- Grafana version: 6.6.1 release
- Data source type & version: n/a
- OS Grafana is installed on: macOS Catalina (v10.15.3)
- User OS & Browser: macOS Catalina (v10.15.3) on Chrome 78.0.3904.108
- Grafana plugins: n/a
- Others:

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
In some scenarios the TimePicker calendar randomly got closed when trying to select a date in another month or year. 

Also when selecting several dates the calendar got a weird "jumpy" behavior because the line height changed. 

All of this is fixed by this PR.

**Which issue(s) this PR fixes**:
Fixes #22110
Fixes #21981

**Special notes for your reviewer**:
The reason why this happen was because react-calendar removes the clicked element from the dom before it got propagated to the top node. Fixed this by not allowing any events from the react-calendar context to propagate outside that context.

### CODE REVIEW

File: packages/grafana-ui/src/components/TimePicker/TimePickerContent/TimePickerCalendar.tsx [hunk 1]
```diff
@@ -129,6 +128,7 @@ const getBodyStyles = stylesFactory((theme: GrafanaTheme) => {
       .react-calendar__tile--now {
         margin-bottom: 4px;
         background-color: inherit;
+        height: 26px;
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/TimePicker/TimePickerContent/TimePickerCalendar.tsx]: Just out of curiosity, are these changes necessary for this fix?

File: packages/grafana-ui/src/components/TimePicker/TimePickerContent/TimePickerCalendar.tsx [hunk 2]
```diff
@@ -248,9 +251,15 @@ const Header = memo<Props>(({ onClose }) => {
 });
 
 const Body = memo<Props>(props => {
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/TimePicker/TimePickerContent/TimePickerCalendar.tsx]: Maybe just destruct this in the func declaration instead of several places below?
```suggestion
const Body = memo<Props>(({from, to, onChange}) => {
```

**Review by hugohaggmark — APPROVED** [review]
LGTM! Couldn't repro behaviour so it should be work as expected.

File: packages/grafana-ui/src/components/TimePicker/TimePickerContent/TimePickerCalendar.tsx (hunk 2 above)
Comment (mckn) [reply packages/grafana-ui/src/components/TimePicker/TimePickerContent/TimePickerCalendar.tsx]: great feedback!

File: packages/grafana-ui/src/components/TimePicker/TimePickerContent/TimePickerCalendar.tsx (hunk 1 above)
Comment (mckn) [reply packages/grafana-ui/src/components/TimePicker/TimePickerContent/TimePickerCalendar.tsx]: Ah - forgot to add that in the description. This fixes some weirdness in when selecting several dates.
