### PR TITLE
Playlists: RBAC Support Precursor - Frontend Safe Checks

### LINKED ISSUE #115712: Playlists: Add RBAC support
After recent changes from the auth team, a user with `None` role should not have access to any API. 
This change [breaks some customers use cases](https://github.com/grafana/support-escalations/issues/19886) and because Playlists does not support RBAC this can't be solved without adding the `Viewer` role to users.
For now, [we have added an exception](https://github.com/grafana/grafana/pull/115713) to continue supporting this behavior. but [this line](https://github.com/grafana/grafana/blob/9c3cdd4814929a29df18b7325eedbdbda0feddc8/pkg/services/apiserver/auth/authorizer/role.go#L19) should be removed once implemented.

We need to add RBAC support to playlists to fix this issue properly.

### PR DESCRIPTION
**Pull request by CollinFingar**
**What is this feature?**
Updates playlist write controls (New/Edit/Delete buttons) to respect RBAC permissions via a new canWritePlaylists() utility, and adds PlaylistsRead/PlaylistsWrite to the AccessControlAction enum.

**Why do we need this feature?**
Playlist UI controls previously used raw org-role checks (isEditor). This update aligns them with RBAC so that users with explicit playlists:write grants (e.g. None-role kiosk accounts) see the correct controls.

**Who is this feature for?**
Grafana admins managing users with non-standard org roles who need explicit playlist write access.

**Which issue(s) does this PR fix?**:

Fixes #115712

**Special notes for your reviewer:**
New changes are feature-toggle dependent
 
With this [OSS Backend PR](https://github.com/grafana/grafana/pull/119975) and this [Enterprise Backend PR](https://github.com/grafana/grafana-enterprise/pull/11228)

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/playlist/utils.ts [hunk 1]
```diff
@@ -1,9 +1,24 @@
...
 import { PlaylistItemUI } from './types';
 
+/**
+ * Returns true if the current user can create, edit, or delete playlists.
+ *
+ * Uses playlists:read as a signal that the backend has registered playlist RBAC.
+ * If the permission is absent (old backend not yet deployed), falls back to the
+ * legacy isEditor check to avoid regressions during a mixed-version rollout.
+ */
+export function canWritePlaylists(): boolean {
```
Comment (baldm0mma) [inline public/app/features/playlist/utils.ts:11]: I don't think i saw a test for this function; is it worth throwing one in?

**Review by baldm0mma — APPROVED** [review]

File: public/app/features/playlist/utils.ts [hunk 2]
```diff
@@ -1,9 +1,24 @@
...
+  return contextSrv.hasPermission(AccessControlAction.PlaylistsRead)
```
Comment (evictorero) [inline public/app/features/playlist/utils.ts]: This is not enough to determine whether the backend supports playlist RBAC or not. How would you differentiate a backend without RBAC deployed by a user that does not have the `PlaylistsRead` permission?
A user with NONE role would return false here if no one add the permission manually so false is a valid case.

Comment (evictorero) [reply public/app/features/playlist/utils.ts]: We should add a feature toggle to manage this. Search for the usage of `savedQueriesRBAC` feature toggle, this is a similar case.

File: public/app/types/accessControl.ts [hunk 3]
```diff
@@ -90,6 +90,9 @@ export enum AccessControlAction {
   FoldersPermissionsRead = 'folders.permissions:read',
   FoldersPermissionsWrite = 'folders.permissions:write',
 
+  PlaylistsRead = 'playlists:read',
```
Comment (evictorero) [inline public/app/types/accessControl.ts:93]: With this new RBAC permission, when not present we should hide the Playlists menu entry in the [routes.tsx](https://github.com/grafana/grafana/blob/58bf5a1ba2115d98feb3c49c95a5c15fc2d16db6/public/app/routes/routes.tsx#L461) file.

Comment (CollinFingar) [reply public/app/types/accessControl.ts:93]: [Updated](https://github.com/grafana/grafana/pull/119974/changes#diff-28aa515cce6c275d3776b64550d509ac87c0c8952bef1b224d37fff4c10d6751R462-R464)

File: public/app/features/playlist/utils.ts (hunk 2 above)
Comment (CollinFingar) [reply public/app/features/playlist/utils.ts]: Everything should be behind a toggle now!

**Review by axelavargas — COMMENTED** [review]
The code looks good to me. A quick question though, a viewer role should see the playlist menu when the feature toggle **playlistsRBAC** is enabled. ? I am not sure if you are fixing this in another PR

Image

**Review by baldm0mma — APPROVED** [review]

**Review by evictorero — APPROVED** [review]
