### PR TITLE
Runtime: Fix handling of short-lived background services

### LINKED ISSUE #26364: Registry: Allow short-lived background services
**What happened**:
When starting a background service by implementing `Run(context.Context) error` and immediately returning `nil` (to avoid running the service) the service will stop other services from starting up.

It is possible to work-around this by idly waiting for `<-ctx.Done()` when Grafana is shutting down, but it'd be reasonable to allow services to shut themselves down without returning an error and not break unrelated services.

These lines are likely responsible:

https://github.com/grafana/grafana/blob/6619cc4b816e6778b68a46ba6c1404f7af845bb4/pkg/cmd/grafana-server/server.go#L129-L132

We should avoid triggering shutdown mode unless we actually get a `<-ctx.Done` signal.

**What you expected to happen**:
The service is cleanly shut down.

**How to reproduce it (as minimally and precisely as possible)**:
Implement a BackgroundService and return `nil` as the first step of the service execution.

(cc @marefr)

### PR DESCRIPTION
**Pull request by ahlaw**
**What this PR does / why we need it**:

Moves shutdown mode flag setting so that shutdown mode is not triggered when services shut down without returning an error.

**Which issue(s) this PR fixes**:

Fixes [#26364](https://github.com/grafana/grafana/issues/26364)

### CODE REVIEW

File: pkg/server/server.go [hunk 1]
```diff
@@ -179,10 +179,10 @@ func (s *Server) Run() (err error) {
 			}
 
 			err := service.Run(s.context)
-			// Mark that we are in shutdown mode
-			// So no more services are started
-			s.shutdownInProgress = true
 			if err != nil {
+				// Mark that we are in shutdown mode
+				// So no more services are started
+				s.shutdownInProgress = true
```
Comment (aknuds1) [inline pkg/server/server.go:185]: @sakjur Isn't there more that needs doing than just this?

**Comment by torkelo** [comment]
Think this should be fine, but not 100% sure

File: pkg/server/server.go (hunk 1 above)
Comment (sakjur) [reply pkg/server/server.go:185]: I just dived into this a little bit and it seems like this should work.
I'll check out the code and play around a little to verify, but I think this change should be mergeable.

Comment (aknuds1) [reply pkg/server/server.go:185]: @sakjur So `s.shutdownInProgress` only needs to be set if an error occurred?

**Review by sakjur — APPROVED** [review]
Tested this locally with both returning `nil` and an error on service initialization. Both were handled correctly (nil continued with the start of the Grafana service and the error aborted it with "A service failed").

LGTM

**Review by aknuds1 — APPROVED** [review]
Think I see the issue solved by this change, and it makes sense.

**Review by marefr — APPROVED** [review]
LGTM

**Comment by aknuds1** [comment]
Thanks for the contribution!
