### PR TITLE
Alerting: Use expected field name for receiver in HCL export

### LINKED ISSUE #87064: Alerting: Simplified Routing HCL export uses incorrect field name
In the model for notification settings we call the receiver field `receiver` in most of Grafana, but the Terraform provider uses `contact_point`.

Currently we export HCL with the incorrect field name, which prevents users from using the feature with rules configured using simplified routing.

### PR DESCRIPTION
**Pull request by rwwiv**
**What is this feature?**

This PR corrects a field name mismatch between Grafana Alerting HCL export and the Terraform provider's accepted model (see [here](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/rule_group#nested-schema-for-rulenotification_settings) for definition).

**Why do we need this feature?**

Fix HCL export of rules using simplified routing.

**Which issue(s) does this PR fix?**:

Fixes #87064

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go [hunk 1]
```diff
@@ -292,7 +292,7 @@ type RelativeTimeRangeExport struct {
 
 // AlertRuleNotificationSettingsExport is the provisioned export of models.NotificationSettings.
 type AlertRuleNotificationSettingsExport struct {
-	Receiver string `yaml:"receiver,omitempty" json:"receiver,omitempty" hcl:"receiver"`
```
Comment (JacobsonMT) [inline pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go:295]: Maybe add a comment to explain the discrepancy for hcl

**Review by JacobsonMT — APPROVED** [review]

**Review by yuri-tceretian — APPROVED** [review]
LGTM
