### PR TITLE
Transformations: Fixes so we match the field based on the proper name.

### LINKED ISSUE #24373: Transforms: CalculateField regex (include options) matches wrong series and problem with byName matcher
The calculate field include option does not work correctly. 

having series named A-series A-series1 A-series2 

And selecting only A-series and A-series1 creates a regex: like `A-series|A-series1` by the calculate field editor. which matches on A-series2 as well. 

We need to update this transform to instead store a list of full fields so we can product a correct regex with start and end tags `^{name}$` . The calculate field editor stores the included fields in a string that it parses to generate the current selection state. This also seems problematic. 

Not sure how we want this to work, in UI & behind the scenes (storing the selected fields object keys, array). But storing the regex as we do now seems like a bad idea (will break if any series name contains a regex character). 

Actually I think series names that include a dot (or other regex characters) wont work in any byName matcher as we do not do any regex escaping. 

And looking how the byName matcher works it tries to convert include option to regex but it's using a function that expect a `/asd/` syntax to be interpreted as a regex directly, so it will get wrapped in this 

/^A-series|A-series1$/

That is the expression that actually gets tested when we use a byName matcher in this case. byName wrapper should just check equality, not regex or if the string does not include `/` prefix and suffix just do normal equality, or regex escape value before constructing a regex the default non regex scenario. 

And if a transform or matcher wants to build a regex it needs to regex escape value and include proper termination characters and it needs to be prefix & suffixed with `/`

### LINKED ISSUE #24518: Fields gone missing after applying filter by name transformation
**What happened**:
Added a filter by name transformation and clicked one series/field and fields/series changed to a single one named value.

First:
image

After clicking on 10.0.100.1:
image

**What you expected to happen**:
The field/series I selected to be selected.

**How to reproduce it (as minimally and precisely as possible)**:
1. `make devenv sources=mysql
2. Open provisioned dashboard: Datasource tests - MySQL
3. Edit "Average logins / $summarize" panel
4. Switch to transformation tab and add "Filter by name" transformation
5. Select on of the series, e.g. 10.0.100.1
6. Fields disappearing 

**Environment**:
- Grafana version: 7.0.0-beta3
- User OS & Browser: Chrome 81

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
The current implementation is broken in a number of ways. Have a look at the referenced issues to get a more detailed explanation.

**Which issue(s) this PR fixes**:
Fixes #24518 
Fixes #24373 

**Todo:**
- [x] check so we have not introduced strict null error.
- [x] add tests for the field name matcher.
- [x] add tests for the field name transformer.

**Testing:**
- [x] field override matcher still working (possibility to add regex should be removed).
- [x] reducer transform with one series
- [x] reducer transform with multiple series
- [x] calculate transform with one series
- [x] calculate transform with multiple series
- [x] filter by name transform with one series
- [x] filter by name transform with multiple series
- [x] organize transform with one series
- [x] check so table panel resize is working as expected

### CODE REVIEW

**Review by ryantxu — COMMENTED** [review]
@mckn quick glance looks good -- anoying how deep this goes, but I think you are on the right path

File: packages/grafana-data/src/transformations/matchers/nameMatcher.ts [hunk 1]
```diff
@@ -4,32 +4,40 @@ import { FieldMatcherInfo, FrameMatcherInfo } from '../../types/transformations'
...
-  getOptionsDisplayText: (pattern: string) => {
-    return `Field name: ${pattern}`;
+  getOptionsDisplayText: (options: FieldNameMatcherOptions) => {
+    return `Field name: ${options.pattern}`;
   },
 };
 
 // General Field matcher
-const frameNameMacher: FrameMatcherInfo<string> = {
+const frameNameMatcher: FrameMatcherInfo<string> = {
```
Comment (ryantxu) [inline packages/grafana-data/src/transformations/matchers/nameMatcher.ts:40]: do we need the same options for this?  `string` will fail in the same way, no?

**Comment by mckn** [comment]
> @mckn quick glance looks good -- anoying how deep this goes, but I think you are on the right path

Yes, so the first issue is fixed. Now I will extend the matcher so support both the possibility to match on exact name of a field and a regexp. So we don't use the same field for both.

**Comment by mckn** [comment]
> > @mckn quick glance looks good -- anoying how deep this goes, but I think you are on the right path
> 
> Yes, so the first issue is fixed. Now I will extend the matcher so support both the possibility to match on exact name of a field and a regexp. So we don't use the same field for both.

This will hopefully fix the issue that @torkelo opened.

File: packages/grafana-data/src/transformations/matchers/nameMatcher.ts (hunk 1 above)
Comment (mckn) [reply packages/grafana-data/src/transformations/matchers/nameMatcher.ts:40]: hmm, not sure. Good feedback! Will have a look at that one once the field matcher is in place.

File: packages/grafana-data/src/transformations/matchers/nameMatcher.ts [hunk 2]
```diff
@@ -4,32 +4,40 @@ import { FieldMatcherInfo, FrameMatcherInfo } from '../../types/transformations'
 import { stringToJsRegex } from '../../text/string';
 import { getFieldDisplayName } from '../../field/fieldState';
 
-// General Field matcher
-const fieldNameMacher: FieldMatcherInfo<string> = {
+export interface FieldNameMatcherOptions {
+  pattern: string;
+  frame?: DataFrame;
+  series?: DataFrame[];
+}
```
Comment (mckn) [inline packages/grafana-data/src/transformations/matchers/nameMatcher.ts:11]: Is this the correct way of naming the different "parts/levels" of the data frame? @dprokop @torkelo @ryantxu

File: public/app/plugins/panel/table/TablePanel.tsx [hunk 3]
```diff
@@ -50,8 +50,14 @@ export class TablePanel extends Component<Props> {
...
     } else {
+      const options = {
+        pattern: fieldDisplayName,
+        frame,
+        series: data.series,
+      };
+
       overrides.push({
-        matcher: { id: matcherId, options: fieldDisplayName },
+        matcher: { id: matcherId, options },
```
Comment (torkelo) [inline public/app/plugins/panel/table/TablePanel.tsx:60]: This won’t work, this is part of a persisted model, we can only store the displayName here , otherwise the whole data frame would be included in the panel
Json that is saved :)

File: packages/grafana-data/src/transformations/matchers/nameMatcher.ts (hunk 2 above)
Comment (torkelo) [reply packages/grafana-data/src/transformations/matchers/nameMatcher.ts:11]: This I think is the wrong level, this is matcher persisted options. frame and all frames should not be part of the matcher persisted options. 

We should change the FieldMatcher function signature: https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/types/transformations.ts#L28 

To include frame & allFrames

**Review by torkelo — COMMENTED** [review]
Great job! I think you're partly on the right path, but think we need to change the matcher interface not the persisted option model :)

File: public/app/plugins/panel/table/TablePanel.tsx (hunk 3 above)
Comment (mckn) [reply public/app/plugins/panel/table/TablePanel.tsx:60]: Ah, good point!

File: packages/grafana-data/src/transformations/matchers/nameMatcher.ts (hunk 2 above)
Comment (mckn) [reply packages/grafana-data/src/transformations/matchers/nameMatcher.ts:11]: hmm, so I totally missed the view of things being persisted. Then it makes sense to move it. The reason why I passed it in the options was that the `FieldMatcher` is being used in other scenarios e.g. `FieldTypeMatcher` and the frame and all frames doesn't make sense in those scenarios.

But I will see if I can introduce a `FieldNameMatcher` that takes the correct signature instead. It will also be more performant since it won't need to create a new option for each iteration which is good.

Comment (mckn) [reply packages/grafana-data/src/transformations/matchers/nameMatcher.ts:11]: hmm - so the pattern in place isn't made to be extended in that way.

File: packages/grafana-data/src/transformations/transformers/filterByName.ts [hunk 4]
```diff
@@ -1,11 +1,13 @@
...
 import { FieldMatcherID } from '../matchers/ids';
+import { FilterOptions, filterFieldsTransformer } from './filter';
 
 export interface FilterFieldsByNameTransformerOptions {
-  include?: string[];
-  exclude?: string[];
+  includeNames?: string[];
+  includePattern?: string;
+  excludeNames?: string[];
+  excludePattern?: string;
```
Comment (mckn) [inline packages/grafana-data/src/transformations/transformers/filterByName.ts:10]: Should I change this one to the following instead?

```
include?: FieldNameMatcherOptions;
exclude?: FieldNameMatcherOptions;
```

File: packages/grafana-data/src/transformations/transformers/filter.ts [hunk 5]
```diff
@@ -24,6 +24,7 @@ export const filterFieldsTransformer: DataTransformerInfo<FilterOptions> = {
       return noopTransformer.transformer({});
     }
 
+    console.log('options', options);
```
Comment (torkelo) [inline packages/grafana-data/src/transformations/transformers/filter.ts:27]: console.log :)

File: packages/grafana-data/src/transformations/matchers/nameMatcher.ts [hunk 6]
```diff
@@ -4,32 +4,66 @@ import { FieldMatcherInfo, FrameMatcherInfo } from '../../types/transformations'
...
-    } catch (e) {
-      console.error(e);
-    }
-    return (field: Field) => {
-      return regex.test(getFieldDisplayName(field) ?? '');
+  get: (options: FieldNameMatcherOptions) => {
+    const regex = patternToRegex(options.pattern);
+    const matchByName = namesToRecord(options.names);
+
+    return (field: Field, frame: DataFrame, allFrames: DataFrame[]) => {
```
Comment (hugohaggmark) [inline packages/grafana-data/src/transformations/matchers/nameMatcher.ts:25]: Ignore this comment for this PR, but I've noticed that this API `field: Field, frame: DataFrame, allFrames: DataFrame[]` is something that is spreading in our codebase.

File: packages/grafana-data/src/transformations/matchers/nameMatcher.ts [hunk 7]
```diff
@@ -4,32 +4,66 @@ import { FieldMatcherInfo, FrameMatcherInfo } from '../../types/transformations'
 import { stringToJsRegex } from '../../text/string';
 import { getFieldDisplayName } from '../../field/fieldState';
 
-// General Field matcher
-const fieldNameMacher: FieldMatcherInfo<string> = {
+export interface FieldNameMatcherOptions {
+  pattern?: string;
+  names?: string[];
```
Comment (torkelo) [inline packages/grafana-data/src/transformations/matchers/nameMatcher.ts:9]: This is sadly used in the FieldNameMatcherEditor as the persisted model, so this change breaks all overrides defined thus far and complicates the override model for the simple one field name match case that we use today. 

Feels like we should split up the matchers a bit, 1 for regex, one for a single name, 1 for multi-names. But question is, is there time for that? What should we do for stable & now?

**Review by torkelo — COMMENTED** [review]
I tested this and it looks great! 

Main problem is that FieldNameMatcherEditor.tsx is using fieldNameMacher & and it's model directly. And so this breaks all existing overrides that just had the name in options (and breaks persisting table column size options set via resizeing columns as it's using the old persisted model). 

If we have time can we create a quick simple simpleFieldNameMatcher? that has `FieldMatcherInfo<string>` and just matches single name and rename FieldNameMatcherEditor to SimpleFieldNameMatcherEditor and have it use this simple one

File: packages/grafana-data/src/transformations/transformers/calculateField.test.ts [hunk 8]
```diff
@@ -96,9 +96,9 @@ describe('calculateField transformer w/ timeseries', () => {
       options: {
         mode: CalculateFieldMode.ReduceRow,
         reduce: {
-          include: 'B',
+          include: ['B'],
           reducer: ReducerID.mean,
-        },
+        } as ReduceOptions,
```
Comment (hugohaggmark) [inline packages/grafana-data/src/transformations/transformers/calculateField.test.ts:101]: nit: if you want to escape the strict null error trap 😉 
```suggestion
        } as unknown as ReduceOptions,
```

File: packages/grafana-ui/src/components/MatchersUI/FieldNameMatcherEditor.tsx [hunk 9]
```diff
@@ -1,37 +1,70 @@
...
+  const selectOptions = useSelectOptions(names);
+
+  const onChange = useCallback(
+    (selection: SelectableValue<string>) => {
+      if (!selection.value || !names.has(selection.value)) {
+        return;
+      }
+      return props.onChange({ names: [selection.value] });
+    },
+    [names]
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/MatchersUI/FieldNameMatcherEditor.tsx:25]: nit
```suggestion
    [names, onChange]
```

**Comment by torkelo** [comment]
Before override rules looked like this: 

```
{
        "matcher": {
          "id": "byName",
          "options": "Max"
        },
        "properties": [
          {
            "id": "custom.align",
            "value": null
          },
          {
            "id": "custom.displayMode",
            "value": "gradient-gauge"
          }
        ]
``´

Question is, can we make byName just be a simple single non-regex string option, and add new matches (that we do need UIs for yet). for the regex & multi cases used in transforms?

The alternative is to add migrations for existing overrides.

File: packages/grafana-ui/src/components/MatchersUI/FieldNameMatcherEditor.tsx [hunk 10]
```diff
@@ -1,37 +1,70 @@
...
+
+const useSelectOptions = (displayNames: Set<string>): Array<SelectableValue<string>> => {
+  return useMemo(() => {
+    return Array.from(displayNames).map(n => ({
       value: n,
       label: n,
     }));
-    const selectedOption = selectOptions.find(v => v.value === options);
+  }, [displayNames]);
+};
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/MatchersUI/FieldNameMatcherEditor.tsx:63]: Nice separation of concerns!

**Review by hugohaggmark — COMMENTED** [review]
Outstanding work 🎉  Will take it for a test run now!

**Comment by dprokop** [comment]
@mckn think we should disable the option creation possibility in the calculate field/binary operation field select:

image

File: packages/grafana-ui/src/components/MatchersUI/FieldNameMatcherEditor.tsx (hunk 9 above)
Comment (mckn) [reply packages/grafana-ui/src/components/MatchersUI/FieldNameMatcherEditor.tsx:25]: ah, awesome finding!

File: packages/grafana-data/src/transformations/matchers/nameMatcher.ts (hunk 6 above)
Comment (mckn) [reply packages/grafana-data/src/transformations/matchers/nameMatcher.ts:82]: Yeah, agree! Feels like there is some structure that we are missing that would solve this.

Comment (torkelo) [reply packages/grafana-data/src/transformations/matchers/nameMatcher.ts:82]: maybe this? https://github.com/grafana/grafana/pull/24199 :)  but for these filtering functions not sure, only alternative would be to have some field display name set in some other more static way, when we build a full data frame list, but that feels also a bit backwards. tricky stuff

Comment (mckn) [reply packages/grafana-data/src/transformations/matchers/nameMatcher.ts:82]: Oh, I need to dig into that one once this release is shipped 👍

**Review by torkelo — APPROVED** [review]
This is looking really good!

**Comment by dprokop** [comment]
@mckn Tested overrides and they seem to work ok, the existing ones and the new ones
