### PR TITLE
Explore: fixes log entries sorting - changes milliseconds to nanoseconds

### LINKED ISSUE #23457: Loki Log entries with Unix Nano Timestamp not sorted correctly
Hello,

**What happened**:
I read logs via promtail and use a Unix Nano Timestamp for the date:

```
- json:
    expressions:
      timestamp_nano: 'TIMESTAMP_NANO'
- timestamp:
    source: "timestamp_nano"
    format: "UnixNs"
```

The logs are sent to loki. 

If I view the Logs via grafana the Logs are only sorted by millisecond precision and not by nanosecond precision.

**How to reproduce it (as minimally and precisely as possible)**:
I created a Repository where you can reproduce this behaviour:

1. Clone Repository https://github.com/denniskniep/GrafanaIssueDemo01
2. docker-compose up
3. Go to http://localhost:3000/ (Credentials are admin:admin)
4. Go to Explore > Choose "loki" > Set loki query to `{app="myApp"}` and change time range to "2020-04-09"
5. Hit "Run Query" Button many times

**What you expected to happen**:

Expected behavoiur is that the log messages are in the order:
C
B
A

But the observed behaviour is that it is after many refreshes as expected, but sometimes it is not sorted correctly. It is like this:
B
A
C

**Anything else we need to know?**:
Used Versions are explicitly defined in docker-compose.yml
https://github.com/denniskniep/GrafanaIssueDemo01/blob/master/docker-compose.yml

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Adds timeEpochNs field to LogRowModel. Fixes log entries sorting - changes sorting from millisecond-level to nanosecond-level to make sure logs are displayed in a correct order. For datasources other than Loki, that output log rows with a millisecond-level timestamps only, adds a padding from the right.

**Which issue(s) this PR fixes**:

Fixes #23457

### CODE REVIEW

File: public/app/core/logs_model.ts [hunk 1]
```diff
@@ -311,6 +314,8 @@ export function logSeriesToLogsModel(logSeries: DataFrame[]): LogsModel | undefi
     for (let j = 0; j < series.length; j++) {
       const ts = timeField.values.get(j);
       const time = dateTime(ts);
+      const tsNs = isLoki ? timeNanosecondField.values.get(j) : undefined;
+      const timeEpochNs = Number(isLoki ? tsNs : time.valueOf() + '000000');
```
Comment (Estrax) [inline public/app/core/logs_model.ts:318]: Well, technically we don't have to add padding from the right there, as on a millisecond precision all the timeEpochNs values are just going to be shorter, but still wanted to make sure all nanosecond-level timestamps have the same structure.

File: public/app/core/logs_model.ts [hunk 2]
```diff
@@ -198,10 +198,11 @@ function isLogsData(series: DataFrame) {
 export function dataFrameToLogsModel(
   dataFrame: DataFrame[],
   intervalMs: number | undefined,
-  timeZone: TimeZone
+  timeZone: TimeZone,
+  isLoki?: boolean
 ): LogsModel {
```
Comment (ivanahuckova) [inline public/app/core/logs_model.ts:203]: What about passing the datasource instead of `isLoki`? It would give us more reusability if there are more specific processing.

File: public/app/core/logs_model.ts [hunk 3]
```diff
@@ -284,6 +286,7 @@ export function logSeriesToLogsModel(logSeries: DataFrame[]): LogsModel | undefi
     return {
       series,
       timeField: fieldCache.getFirstFieldOfType(FieldType.time),
+      timeNanosecondField: isLoki && fieldCache.hasFieldNamed('tsNs') ? fieldCache.getFieldByName('tsNs') : undefined,
```
Comment (ivanahuckova) [inline public/app/core/logs_model.ts:289]: Why does isLoki have to be here? Wouldn't the result be same without it?

File: public/app/core/logs_model.ts (hunk 2 above)
Comment (Estrax) [reply public/app/core/logs_model.ts:203]: Good point, changed.

File: public/app/core/logs_model.ts [hunk 4]
```diff
@@ -311,6 +314,8 @@ export function logSeriesToLogsModel(logSeries: DataFrame[]): LogsModel | undefi
     for (let j = 0; j < series.length; j++) {
       const ts = timeField.values.get(j);
       const time = dateTime(ts);
+      const tsNs = isLoki ? timeNanosecondField.values.get(j) : undefined;
```
Comment (ivanahuckova) [inline public/app/core/logs_model.ts:317]: Isn't `timeNanosecondField` going to be always there as we have created it couple lines above? And therefoore it is going to either give us undefined or value?

File: packages/grafana-data/src/types/logs.ts [hunk 5]
```diff
@@ -60,6 +60,7 @@ export interface LogRowModel {
   searchWords?: string[];
   timeFromNow: string;
   timeEpochMs: number;
+  timeEpochNs: number;
```
Comment (aocenas) [inline packages/grafana-data/src/types/logs.ts:63]: We cannot use number for ns because it overflows safe javascript number

File: public/app/core/logs_model.ts (hunk 3 above)
Comment (Estrax) [reply public/app/core/logs_model.ts]: Aww, right. Forgot to remove this one. Thanks.

File: public/app/core/logs_model.ts (hunk 4 above)
Comment (Estrax) [reply public/app/core/logs_model.ts]: `timeNanosecondField` can either have values or be undefined. Would personally use an optional chaining operator there but got asked to write it in a longer form as it's easier to read.

Comment (ivanahuckova) [reply public/app/core/logs_model.ts]: But shouldn't it be then `const tsNs = timeNanosecondField ? timeNanosecondField.values.get(j) : undefined;` Or in my opinion, this is mor readable `const tsNs = timeNanosecondField?.values.get(j);`

Comment (Estrax) [reply public/app/core/logs_model.ts]: Yep, can be done that way, but there's one downside of this choice: we can never be sure that other datasources are going to have a timestamp-format data under this field. I'll write some additional logic to check that.

File: public/app/core/logs_model.ts [hunk 6]
```diff
@@ -311,6 +314,8 @@ export function logSeriesToLogsModel(logSeries: DataFrame[]): LogsModel | undefi
     for (let j = 0; j < series.length; j++) {
       const ts = timeField.values.get(j);
       const time = dateTime(ts);
+      const tsNs = datasourceId === 'loki' ? timeNanosecondField.values.get(j) : undefined;
+      const timeEpochNs = Number(datasourceId === 'loki' ? tsNs : time.valueOf() + '000000');
```
Comment (aocenas) [inline public/app/core/logs_model.ts:318]: I don't think we need the datasource here at all, we can just check if there is a `tsNs` field and use it otherwise just fallback to miliseconds.

File: packages/grafana-data/src/types/logs.ts (hunk 5 above)
Comment (aocenas) [reply packages/grafana-data/src/types/logs.ts:63]: Also would be nice to add a comment why we need this in addition to timeEpochMs

**Review by aocenas — CHANGES_REQUESTED** [review]

File: packages/grafana-data/src/types/logs.ts (hunk 5 above)
Comment (Estrax) [reply packages/grafana-data/src/types/logs.ts]: @aocenas changed to strings and adjusted sort methods

File: public/app/core/logs_model.ts [hunk 7]
```diff
@@ -265,7 +267,7 @@ interface LogFields {
  * Converts dataFrames into LogsModel. This involves merging them into one list, sorting them and computing metadata
  * like common labels.
  */
-export function logSeriesToLogsModel(logSeries: DataFrame[]): LogsModel | undefined {
+export function logSeriesToLogsModel(logSeries: DataFrame[], datasourceId?: string): LogsModel | undefined {
```
Comment (ivanahuckova) [inline public/app/core/logs_model.ts:270]: datasourceId is not used anymore, so it can be removed:
image

File: public/app/features/explore/utils/ResultProcessor.ts [hunk 8]
```diff
@@ -101,7 +101,8 @@ export class ResultProcessor {
       return null;
     }
 
-    const newResults = dataFrameToLogsModel(this.dataFrames, this.intervalMs, this.timeZone);
+    const datasourceId = this.state.datasourceInstance?.meta?.id;
+    const newResults = dataFrameToLogsModel(this.dataFrames, this.intervalMs, this.timeZone, datasourceId);
```
Comment (ivanahuckova) [inline public/app/features/explore/utils/ResultProcessor.ts:105]: Also here, datasourceId is not used in dataFrameToLogsModel so it can be removed.

**Review by ivanahuckova — CHANGES_REQUESTED** [review]

**Comment by Estrax** [comment]
@ivanahuckova good catch. Done.

File: public/app/features/explore/utils/ResultProcessor.test.ts [hunk 9]
```diff
@@ -176,6 +176,7 @@ describe('ResultProcessor', () => {
               raw: 'third',
               searchWords: [] as string[],
               timeEpochMs: 300,
+              timeEpochNs: '300000000',
```
Comment (aocenas) [inline public/app/features/explore/utils/ResultProcessor.test.ts:179]: Can we add here a case to check the sorting if the difference is sub milisecond to test the new behavior?

**Review by ivanahuckova — APPROVED** [review]
LGTM! 🙂

**Review by aocenas — COMMENTED** [review]
Code looks good just one comment about tests

File: public/app/features/explore/utils/ResultProcessor.test.ts (hunk 9 above)
Comment (Estrax) [reply public/app/features/explore/utils/ResultProcessor.test.ts]: @aocenas done, changed the tests slightly to address nanosecond-level precision.

**Review by aocenas — APPROVED** [review]
