### PR TITLE
Azure Monitor: Limit the log rows to 30000

### LINKED ISSUE #91358: Azure Monitor: Log Panel visualization freezes browser tab
### What happened?

When running an Azure Monitor Logs query that is not well bounded by time or filters, the volume of results returned can freeze the browser tab and cause it to be unresponsive when visualized in the Logs panel.

In example below, the query returns ~230K results which eventually crashes the Browser with Format as Logs and Logs visualization used.

image

However, the same query works as expected when using the Format as Table and Table visualization.

Successful table
image

Query Inspector
image

### What did you expect to happen?

Logs panel to display results just as in the case of the Table panel
OR
Warning message indicating result set is being truncated because of scalability limitations
OR
Error message that the query results contain too many results to be visualized in Logs panel

Note the Log Analytics UI in Azure limits queries to max of 30K in some cases to avoid similar issues.
image

### Did this work before?

No, new limitation found when testing new logs views and filtering capabilities.

### How do we reproduce it?

1. Run Azure Monitor logs query that returns >= 100K rows
2. Change Format as to Logs
3. Change Panel type to Logs

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 11.1 on Azure Managed Grafana, 11.2 on Grafana Cloud
OS: Windows 11
Browser: Edge/Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Azure Monitor

### PR DESCRIPTION
**Pull request by aangelisc**
Due to the logs visualisation not currently being virtualised browser tabs can crash when a substantial amount of data is returned.

To limit the impact of this we are limiting the number of rows returned by a logs query to 30,000 when the result format is set to Logs. This limit will not affect other formats.

A feature toggle has also been added to allow users to disable this behaviour if they wish.

Once #92881 is resolved we should be able to remove this limitation.

Fixes #91358 

# Release notice breaking change

Azure Monitor logs queries that use the result format "Logs" will have their result set truncated to 30,000 rows to prevent unexpected behavior. All other formats are unaffected. If you wish to return more than 30,000 rows you can set the `azureMonitorDisableLogLimit` feature toggle to `true`.

### CODE REVIEW

File: pkg/tsdb/azuremonitor/loganalytics/azure-response-table-frame.go [hunk 1]
```diff
@@ -45,12 +45,12 @@ func apiErrorToNotice(err *AzureLogAnalyticsAPIError) data.Notice {
 }
 
 // ResponseTableToFrame converts an AzureResponseTable to a data.Frame.
-func ResponseTableToFrame(table *types.AzureResponseTable, refID string, executedQuery string, queryType dataquery.AzureQueryType, resultFormat dataquery.ResultFormat) (*data.Frame, error) {
+func ResponseTableToFrame(table *types.AzureResponseTable, refID string, executedQuery string, queryType dataquery.AzureQueryType, resultFormat dataquery.ResultFormat, logLimitDisabled bool) (*data.Frame, error) {
```
Comment (adamyeats) [inline pkg/tsdb/azuremonitor/loganalytics/azure-response-table-frame.go:48]: This is quite a long arguments list, I'd recommend considering if Functional Options would be a good fit here A plus would be that it'd allow you to set defaults for the options before you hit the private function `converterFrameForTable`.

**Review by adamyeats — APPROVED** [review]
LGTM with one nit that isn't blocking 👍

File: pkg/tsdb/azuremonitor/loganalytics/azure-response-table-frame.go [hunk 2]
```diff
@@ -84,6 +84,14 @@ func converterFrameForTable(t *types.AzureResponseTable, queryType dataquery.Azu
 		converters = append(converters, converter)
 	}
 
+	rowLimit := 30000
+	limitExceeded := false
+	if len(t.Rows) > rowLimit && resultFormat == dataquery.ResultFormatLogs && !logLimitDisabled {
+		// We limit the number of rows to 30k to prevent crashing the browser tab as the logs viz is not virtualised.
+		t.Rows = t.Rows[:30000]
```
Comment (adamyeats) [inline pkg/tsdb/azuremonitor/loganalytics/azure-response-table-frame.go:91]:
```suggestion
		t.Rows = t.Rows[:rowLimit]
```
