### PR TITLE
XY Chart: Prevent crash when deleting a series 

### LINKED ISSUE #85036: XYChart2: Removing last / only remaining series in the editor does not clear form
image

### PR DESCRIPTION
**Pull request by adela-almasan**
https://github.com/grafana/grafana/assets/88068998/6a645f14-cc1f-475d-9eb8-fa1b6243cf49

Fixes https://github.com/grafana/grafana/issues/85036

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/panel/xychart/v2/SeriesEditor.tsx [hunk 1]
```diff
@@ -119,174 +120,176 @@ export const SeriesEditor = ({
...
-                delete series.frame;
-              } else {
-                series.frame = {
-                  matcher: {
-                    id: FrameMatcherID.byIndex,
-                    options: Number(opt.value),
-                  },
-                };
-              }
+      {selectedIdx >= 0 && series != null && (
```
Comment (nmarrs) [inline public/app/plugins/panel/xychart/v2/SeriesEditor.tsx:123]: this is the main line preventing the crash right? the rest is just indentation noise? 😬

Comment (adela-almasan) [reply public/app/plugins/panel/xychart/v2/SeriesEditor.tsx:123]: yes, L35 and L123 are fixing the issue. The rest, indentation noise.. 😬

**Review by nmarrs — APPROVED** [review]
🐛🔨
