### PR TITLE
AuthProxy: Optimistic lock pattern for remote cache Set

### LINKED ISSUE #17375: failed to store user in cache" error="pq: duplicate key value violates unique constraint \"cache_data_pkey\""
**What happened**:

Users randomly getting server errors

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Seeing quit a lot of these errors, in the logs:

```
grafana-6b94c79d76-r5c9k grafana t=2019-05-30T14:23:13+0000 lvl=eror msg="auth proxy: failed to store user in cache" logger=context message="failed to store user in cache" error="pq: duplicate key value violates unique constraint \"cache_data_pkey\""
grafana-6b94c79d76-r5c9k grafana t=2019-05-30T14:23:13+0000 lvl=eror msg="failed to store user in cache" logger=context error="pq: duplicate key value violates unique constraint \"cache_data_pkey\""
```

This sounds like get-insert SQL race condition.  We have two replicacas of grafana running in parallel (Kubernetes) writing to the same DB.  This function doesn't look race-free:

```go
// Remember user in cache
func (auth *AuthProxy) Remember(id int64) *Error {
	key := auth.getKey()

	// Check if user already in cache
	userID, _ := auth.store.Get(key)
	if userID != nil {
		return nil
	}

	expiration := time.Duration(-auth.cacheTTL) * time.Minute

	err := auth.store.Set(key, id, expiration)
	if err != nil {
		return newError(err.Error(), nil)
	}

	return nil
}
```

**Environment**:
- Grafana version: 6.2.1 (official docker image)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others: using postgresql 11.2

### PR DESCRIPTION
**Pull request by papagian**
Fixes #17375

The error can be triggered by enabling authentication proxy, setting `ldap_sync_ttl` to something small and running the load tests using MySQL or PostgreSQL as a database.

The error occurs when one request tries to insert the key to the table after having checked that it does not exist but in the meantime another one has already inserted it.

The solution attempts to insert the key without checking if it's already there and in case of an integrity constrain violation tries to update it instead.

The transaction is removed in order to prevent deadlocks after an integrity constrain violation occurs. However, there were still some deadlocks on MySQL therefore in case of a deadlock an update is attempted.

 If the update also fails the error will be propagated (since it's a cache and it does not harm a lot to end up with a key that is not set) unless it is a deadlock. In that case the error is ignored since most probably somebody else is trying to insert or update the key, so one way or another the key will be set.

### CODE REVIEW

File: pkg/services/sqlstore/migrator/dialect.go [hunk 1]
```diff
@@ -48,6 +48,8 @@ type Dialect interface {
 	NoOpSql() string
 
 	IsUniqueConstraintViolation(err error) bool
+	IsDeadlock(err error) bool
+	GetErrorCode(err error) string
```
Comment (bergquist) [inline pkg/services/sqlstore/migrator/dialect.go]: I can't find any usage of this function. Was it added before `IsDeadlock` and not needed anymore?

File: pkg/infra/remotecache/database_storage.go [hunk 2]
```diff
@@ -70,7 +70,10 @@ func (dc *databaseCache) Get(key string) (interface{}, error) {
 	if cacheHit.Expires > 0 {
 		existedButExpired := getTime().Unix()-cacheHit.CreatedAt >= cacheHit.Expires
 		if existedButExpired {
-			_ = dc.Delete(key) //ignore this error since we will return `ErrCacheItemNotFound` anyway
+			err = dc.Delete(key) //ignore this error since we will return `ErrCacheItemNotFound` anyway
+			if err != nil {
+				dc.log.Debug(err.Error())
```
Comment (bergquist) [inline pkg/infra/remotecache/database_storage.go]: We should write a log message here as well. Its gonna be very hard to understand why we log this error :)

**Review by bergquist — COMMENTED** [review]
Great work!

File: pkg/services/sqlstore/migrator/dialect.go (hunk 1 above)
Comment (papagian) [reply pkg/services/sqlstore/migrator/dialect.go]: It is not needed for this specific case, I included it just because I thought it could be useful being there for the investigation of similar future issues.

File: pkg/infra/remotecache/database_storage.go (hunk 2 above)
Comment (papagian) [reply pkg/infra/remotecache/database_storage.go]: I will fix that.

File: pkg/services/sqlstore/migrator/dialect.go (hunk 1 above)
Comment (bergquist) [reply pkg/services/sqlstore/migrator/dialect.go]: Since different datasources have different error codes its not really usable beyond testing one database. So I dont think we need it. The dialect function you added is a better suggestion for how people can solve this in the future :)

Comment (aocenas) [reply pkg/services/sqlstore/migrator/dialect.go]: I would say as `GetErrorCode` and `isThisError` are very similar but `GetErrorCode` is probably easier to understand from the name. So what about we keep `GetErrorCode`, remove the `isThisError` and use:
```
func (db *Mysql) IsUniqueConstraintViolation(err error) bool {
	return db.GetErrorCode(err) == mysqlerr.ER_DUP_ENTRY
}
```

File: pkg/infra/remotecache/database_storage.go [hunk 3]
```diff
@@ -84,35 +87,37 @@ func (dc *databaseCache) Get(key string) (interface{}, error) {
...
+		expiresInSeconds = int64(expire) / int64(time.Second)
+	}
 
-		// insert or update depending on if item already exist
-		if has {
+	// insert or update depending on if item already exist
+	sql := `INSERT INTO cache_data (cache_key,data,created_at,expires) VALUES(?,?,?,?)`
+	_, err = session.Exec(sql, key, data, getTime().Unix(), expiresInSeconds)
+	if err != nil {
+		if dc.SQLStore.Dialect.IsUniqueConstraintViolation(err) || dc.SQLStore.Dialect.IsDeadlock(err) {
```
Comment (aocenas) [inline pkg/infra/remotecache/database_storage.go]: I think it would be nice to leave some comments in this function as it wasn't very straightforward to get to this point. Things I think should be mentioned here or in function doc comment:
- The deadlock check, that it is only because issues on Mysql and that in this context it should be fine
- That we are doing just one insert/update check and that we can end up with value not being set but as this is cache it is ok (but not good to copy to other context probably)

**Comment by aocenas** [comment]
@papagian good work 👍. Please add also a bit of description to the PR. No need to be verbose but for other people checking the PR it is good place to leave a bit of context, like what was done and why especially with PRs like this where quite a few decisions and different approaches were made in the process.

File: pkg/infra/remotecache/database_storage.go [hunk 4]
```diff
@@ -84,35 +87,37 @@ func (dc *databaseCache) Get(key string) (interface{}, error) {
...
-		}
+	session := dc.SQLStore.NewSession()
+	defer session.Close()
 
-		var expiresInSeconds int64
-		if expire != 0 {
-			expiresInSeconds = int64(expire) / int64(time.Second)
-		}
+	var cacheHit CacheData
+	_, err = session.Where("cache_key = ?", key).Get(&cacheHit)
```
[the remark this answers is not in the document]
Comment (bergquist) [reply pkg/infra/remotecache/database_storage.go]: Good point! But I think we should avoid the insert statement if this statement returns something. Should reduce the amounts of locks in the database.

**Comment by bergquist** [comment]
cant respond to this comment for some reason...
> I would say as GetErrorCode and isThisError are very similar but GetErrorCode is probably easier to understand from the name. So what about we keep GetErrorCode, remove the isThisError and use:

I agree that `GetErrorCode` is better but I dont think we need to expose it in the interface.

File: pkg/infra/remotecache/database_storage.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (aocenas) [reply pkg/infra/remotecache/database_storage.go]: I think that would get us back to where we started though, wouldn't it. I mean whatever this returns we cannot count on it when doing the insert/update as other operation could have inserted/deleted the row and we can still get unique error or not update anything.

[the remark this answers is not in the document]
Comment (bergquist) [reply pkg/infra/remotecache/database_storage.go]: Yea I forgot the delete aspect. I think we can improve this but it should be fine for the only use-case we have now.

File: pkg/services/sqlstore/migrator/dialect.go (hunk 1 above)
Comment (papagian) [reply pkg/services/sqlstore/migrator/dialect.go]: Since the errors for each database are of different type the `GetErrorCode ` returns string.
Therefore this condition would need casting but anyway I think it's better to get rid of `GetErrorCode` and maybe find an more appropriate name for `isThisError`.

**Review by aocenas — APPROVED** [review]
