### PR TITLE
Graphite: use POST for /metrics/find requests

### LINKED ISSUE #16707: POST not being used for /metric/find and /tags request
We are seeing an issue in grafanacloud graphite, Grafana v6.1.4 (fef1733)
but TBH we've been seeing it for a long time even with older grafana versions

Upon load of a dashboard that has template variables defined (see "tsdb-gw 0.9" dashboard in our internal ops instance), when the dashboard loads, we immediately get a red error popup that fills up half of the screen (and even that is not enough to fully show the error)

The error looks like:
```
{"err":{"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/datasources/proxy/32/metrics/find","params":{"query":"tsdb-gw.stats.{FOO,BAR,BAZ}.api.request.*","from":1555845978,"until":1555932498},"inspect":{"type":"graphite"},"retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*"}},"statusText":"","xhrStatus":"error"},"cancelled":true}
```
devtools

`{FOO,BAR,BAZ}` is actually a huge list with hundreds of entries. lots of text

Chrome network tab shows that an xhr request to /find failed, without a status code, so it looks like the request was not made or did not return.

When i look for more information, there's no timing information (says the request stalled) (https://developers.google.com/web/tools/chrome-devtools/network/reference#timing-explanation) .
timing

no response or preview is available, and the headers look like this:
(abridged)
```
https://redacted/api/datasources/proxy/32/metrics/find?from=1555845978&query=tsdb-gw.stats.%7BFOO,BAR,BAZ%7D.api.request.*&until=1555932498
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Accept: application/json, text/plain, */*
Referer: https://redacted/d/DSd3POZiz/tsdb-gw-0-9?orgId=1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
X-Grafana-Org-Id: 1
from: 1555845978
query: tsdb-gw.stats.{FOO,BAR,BAZ}.api.request.*
until: 1555932498
icon_explore.svg	icon_alert.svg	icon_cog.svg	icon_question.svg	data:image/png;base…	collect?v=1&_v=j73&aip=1&a=316810956&t=pageview&_s…58328364-6&_gid=1608825132.1555924889&z=576751083	find?from=1555845978&query=tsdb-gw.stats.*&until=1555932498	find?from=1555845978&query=tsdb-gw.stats.%7Bus-wes…ka-test-1-kafkaupgradetest1%7D.*&until=1555932498	find?from=1555845978&query=tsdb-gw.stats.%7Bus-wes…dd967fd68-wzsx6%7D.api.request.*&until=1555932498	icon_add_panel.svg	data:image/svg+xml;…	annotations?dashboardId=488&from=1555846040522&to=1555932440522	
```

My guess is probably the generated URL is too long and it cancels the request? even though it's vague.

I think we should:
1) make sure people cannot shoot themselves in the foot (e.g. fall back to post bodies if url would be too long), to the extent possible
2) provide clearer errors. ellipsize long url's and have clearer error messages

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:

It changes graphite `/metrics/find` requests to POST in order to support long query parameters.

**Which issue(s) this PR fixes**:

Fixes #16707

### CODE REVIEW

File: public/app/plugins/datasource/graphite/datasource.ts [hunk 1]
```diff
@@ -245,10 +245,11 @@ export function GraphiteDatasource(this: any, instanceSettings, $q, backendSrv,
     }
 
     const httpOptions: any = {
-      method: 'GET',
+      method: 'POST',
       url: '/metrics/find',
-      params: {
-        query: interpolatedQuery,
+      data: `query=${query}`,
```
Comment (marefr) [inline public/app/plugins/datasource/graphite/datasource.ts]: You need to use the `interpolatedQuery` here to support /metrics/find queries referencing template variables, like the dashboard here https://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1

File: public/app/plugins/datasource/graphite/specs/datasource.test.ts [hunk 2]
```diff
@@ -303,6 +303,17 @@ describe('graphiteDatasource', () => {
       expect(requestOptions.params.expr).toEqual(['server=~backend*']);
       expect(results).not.toBe(null);
     });
+
+    it('should not be canceled for long queries', () => {
+      const longQuery = 'a'.repeat(40000);
```
Comment (marefr) [inline public/app/plugins/datasource/graphite/specs/datasource.test.ts]: Not sure this is needed since it's more of a browser/server limitation, right? But the rest of the test make sense. If you want to make sure that referencing template variables are interpolated (see other comment) that could also be added to this test.

**Review by marefr — CHANGES_REQUESTED** [review]
Looks good, but added a few comments that needs to be addressed.

**Review by marefr — APPROVED** [review]
Great work :+1:
