### PR TITLE
ShareDrawer: Focus dropdown button back when drawer gets closed

### LINKED ISSUE #117835: A11y: Focus does not consistently return to the "Share" button after closing the Share dialog
## Description

After closing the "Share" dialog, focus does not consistently return to the triggering "Share" button. It works correctly the first time, but on subsequent open/close cycles the focus fails to return, leaving keyboard and screen reader users disoriented.

## Steps to reproduce

1. Open Grafana in Chrome on Windows
2. Enable JAWS screen reader
3. Navigate to the "Share" button and activate it to open the Share dialog
4. Close the dialog using the close button or cancel button
5. Observe that focus returns to the "Share" button (works the first time)
6. Repeat: open and close the "Share" dialog again
7. Observe that focus does **not** return to the "Share" button on subsequent attempts

## Actual behavior

Focus returns to the "Share" button the first time the dialog is closed, but fails to do so on subsequent open/close cycles.

## Expected behavior

Focus should consistently return to the original triggering element (the "Share" button) every time the dialog is closed.

## Suggested fix

Ensure the dialog's close handler always restores focus to the element that triggered the dialog. Store a reference to the trigger element when the dialog opens, and call `.focus()` on it when the dialog closes.

Reference: [WAI-ARIA Dialog Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/dialog/)

## WCAG criteria

- **2.4.3 Focus Order** (Level A)

## Possible duplicates in grafana/grafana

- [#72807](https://github.com/grafana/grafana/issues/72807) — Focus order does not return to "Set color" button after pressing esc key (closed; same pattern — focus not returned to triggering element after closing a dialog)
- [#95721](https://github.com/grafana/grafana/issues/95721) — Dashboard: Keyboard focus is reset when deleting a panel (open; related focus management issue)

## Issue reference

Reference issue 12

### PR DESCRIPTION
**Pull request by juanicabanas**
**What is this feature?**

Due to how the Drawer is rendered, there's an a11y issue where the dropdown button isn't focused when the drawer gets closed.
A generic context provider with a `ref` is added to wrap the content that is rendered in the dashboard scene.
That `ref` is set in the dropdown buttons and used in `Drawer` by `FloatingFocusManager` component, who focuses that ref element.

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/117835

**Special notes for your reviewer:**

https://github.com/user-attachments/assets/156089d3-543e-43e9-8665-b79456be78a2

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard-scene/sharing/FocusReturnContext.tsx [hunk 1]
```diff
@@ -0,0 +1,28 @@
+import { createContext, useContext, useRef, ReactNode } from 'react';
+
+/**
+ * Context for storing a reference to the element that triggered an overlay (drawer, modal, etc.).
+ * Used to restore focus when the overlay closes (WCAG 2.4.3 Focus Order).
+ * See: https://github.com/grafana/grafana/issues/117835
+ */
+interface FocusReturnContextValue {
```
Comment (CollinFingar) [inline public/app/features/dashboard-scene/sharing/FocusReturnContext.tsx]: Looking good! Do you think it might make sense to move this to Grafana-UI as another helpful util/hook there?

**Review by baldm0mma — APPROVED** [review]

File: public/app/features/dashboard-scene/sharing/FocusReturnContext.tsx (hunk 1 above)
Comment (juanicabanas) [reply public/app/features/dashboard-scene/sharing/FocusReturnContext.tsx]: yess, make sense. this is a generic component that could be used in other places

**Review by ashharrison90 — COMMENTED** [review]
ok, `floating-ui` should be able to handle this. and in fact it does for modals. just not for `Drawer`... i guess maybe something to do with `@rc-component/drawer` could be conflicting with it. will investigate and get back to you 👍

**Review by ashharrison90 — CHANGES_REQUESTED** [review]
ok, finally dug into it a bit. believe this can be fixed with 1 line to `Drawer`. set this on the props to `RcDrawer`:
```tsx
      // this is handled by floating-ui
      autoFocus={false}
```

**Comment by juanicabanas** [comment]
> ok, finally dug into it a bit. believe this can be fixed with 1 line to `Drawer`. set this on the props to `RcDrawer`:
> 
> ```tsx
>       // this is handled by floating-ui
>       autoFocus={false}
> ```

awesome @ashharrison90 ! Change applied 🙌🏻

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍 i added a test to the profile button to ensure this behaviour is maintained
