### PR TITLE
Explore: Use new icons for split pane resizing

### LINKED ISSUE #60253: Explore - Split resize widen/narrow uses exact same icon as moving the time window
**What happened**:
In 9.4 we introduced [resizing the split pane](https://github.com/grafana/grafana/pull/58683).

Defining an absolute time in Explore creates arrows that allow you to "nudge" the time window. Those arrows are also introduced in the context of widening/narrowing the explore pane window in split mode. Having redundant icons that do vastly different actions is confusing.

Screen Shot 2022-12-13 at 9 04 00 AM

**What you expected to happen**:
Different icons for the different actions

**How to reproduce it (as minimally and precisely as possible)**:
Set an absolute time in Explore. Go into split mode.

**Environment**:
- Grafana version: main

### PR DESCRIPTION
**Pull request by gelicia**
The icons introduced to the explore toolbar are exactly like other icons the toolbar already has. This brings in new icons designed by @radiorental and uses those instead to be more distinct.

**Which issue(s) does this PR fix?**:
Fixes #60253 

**Note**:
If you toggle the theme via the command palette, you will see some background colors/borders around the buttons here. I'm not sure if this toolbar is doing something strange with styles or not, but I opened up a ticket here https://github.com/grafana/grafana/issues/60397

### CODE REVIEW

**Comment by gelicia** [comment]
Looks bad on dark mode. Fixing..

**Comment by Elfo404** [comment]
is this the actual icon we want to use? i've never seen hand-drawn style icons in grafana, it really clashes with everything else 🤔 
Screenshot 2022-12-15 at 14 07 42

**Comment by academo** [comment]
Just to be sure. did you use `yarn generate-icons-bundle-cache-file` inside `packages/grafana-ui` to generate the cache and bundle files?

**Comment by gelicia** [comment]
> Just to be sure. did you use `yarn generate-icons-bundle-cache-file` inside `packages/grafana-ui` to generate the cache and bundle files?

Yes - I wouldnt have the patience to renumber those imports by hand :)

**Comment by gelicia** [comment]
https://user-images.githubusercontent.com/1533128/207966026-41ead3fa-8c64-45c6-92e1-67d397bdf2cb.mov

After talking about it, we changed the icons to something slightly different and removed the fill to blend into the theme better.

**Comment by gelicia** [comment]
@L-M-K-B @Elfo404 Changed the icons again :D

File: public/app/features/explore/ExploreToolbar.tsx [hunk 1]
```diff
@@ -168,11 +180,9 @@ class UnConnectedExploreToolbar extends PureComponent<Props> {
...
             disabled={isLive}
             onClick={onClickResize}
-            icon={
-              (exploreId === 'left' && isLargerExploreId) || (exploreId === 'right' && !isLargerExploreId)
-                ? 'angle-left'
-                : 'angle-right'
-            }
+            icon={isLargerExploreId ? 'gf-movepane-right' : 'gf-movepane-left'}
+            iconOnly={true}
+            className={styles.rotateIcon}
```
Comment (Elfo404) [inline public/app/features/explore/ExploreToolbar.tsx:185]: as styles would get recreated and inserted at every render, can't we just switch the icon based on `exploreId` instead of rotating it?

Comment (gelicia) [reply public/app/features/explore/ExploreToolbar.tsx:185]: The idea here is to keep the arrow in the pane where it's displayed in the icon. So the left pane always has an arrow on the left side, and the icon itself either has the arrow pointing into or away from the smaller pane depending on if we're making the pane larger or not.

Comment (Elfo404) [reply public/app/features/explore/ExploreToolbar.tsx:185]: Screenshot 2022-12-20 at 13 28 19

that doesn't seem to be the case though 🤔 

also the arrows in the new icons always points internally, if you rotate one of the icons by 180 deg you simply get the other icon

Comment (radiorental) [reply public/app/features/explore/ExploreToolbar.tsx:185]: Apologies @gelicia , I didn't pick up on this detail but I think @Elfo404 is correct.  For reference here are the previous icons (below) and the latest (above).
Screenshot 2022-12-20 at 9 23 43 AM

Comment (radiorental) [reply public/app/features/explore/ExploreToolbar.tsx:185]: I modified it if that helps? 
movepane-rtl(1)

Comment (gelicia) [reply public/app/features/explore/ExploreToolbar.tsx:185]: > Screenshot 2022-12-20 at 13 28 19
> 
> that doesn't seem to be the case though 🤔
> 
> also the arrows in the new icons always points internally, if you rotate one of the icons by 180 deg you simply get the other icon

@radiorental @Elfo404 Ah sorry, I didn't know the assets didn't include both arrows. Fixing.

**Review by Elfo404 — APPROVED** [review]
Nice stuff! 🚀

**Review by radiorental — APPROVED** [review]
ship it
