### PR TITLE
Config: Show user-friendly error message instead of stack trace

### LINKED ISSUE #16283: Crash if `grafana-server` is started with a malformed entry in `/etc/grafana/grafana.ini`
First of all, thank you for your work on Grafana!

**What happened**: The `grafana-server` process crashes with a segmentation fault if it is started with a malformed entry in `grafana.ini`.

**What you expected to happen**: The `grafana-server` process should not crash with a stack trace but show a user-friendly error message instead saying that the entry is malformed.

**How to reproduce it (as minimally and precisely as possible)**:

- Install Grafana 5.4.2 on Debian Jessie (or any other OS since it's not OS-specific).
- Use the default configuration file in `/etc/grafana/grafana.ini` and change the `root_url` line from `;root_url = http://localhost:3000` to `root_url = %(protocol)s://%(domain)s:%(port)s/grafana/`. Using `port` here is invalid.
- Execute `grafana-server -config /etc/grafana/grafana.ini -homepath /usr/share/grafana` and notice the message `panic: runtime error: invalid memory address or nil pointer dereference` with a stack trace.

**Anything else we need to know?**: It looks very similar to #6731, so it's either a different scenario or it regressed in a later version of Grafana.

**Environment**:
- Grafana version: 5.4.2
- Data source type & version: Graphite
- OS Grafana is installed on: Debian Jessie
- User OS & Browser: Ubuntu 18.04 LTS, Firefox 66.0
- Grafana plugins: n/a
- Others: n/a

### PR DESCRIPTION
**Pull request by Hofls**
**What this PR does / why we need it**:
Show user-friendly error message instead of stack trace

**Which issue(s) this PR fixes**:
Fixes #16283

### CODE REVIEW

File: pkg/setting/setting.go [hunk 1]
```diff
@@ -787,26 +787,36 @@ func (cfg *Cfg) Load(args *CommandLineArgs) error {
...
+		ConnStr: valueAsString(cacheServer, "connstr", ""),
 	}
 
 	return nil
 }
 
+func valueAsString(section *ini.Section, keyName string, defaultValue string) string {
+	defer func() {
+		if err := recover(); err != nil {
+			log.Fatal(4, "Invalid value for key '%s' in configuration file", keyName)
```
Comment (bergquist) [inline pkg/setting/setting.go]: I dont want to use `log.Fatal` like this since it calls `os.Exit`. The function should return an error instead. `os.Exit` Should only be called from the `pkg/cmd/grafana-server` package

**Review by bergquist — CHANGES_REQUESTED** [review]
Great that you want to improve the usability for operators. Highly appreciated. 

But I'd like to see some changes in how the error is handled.

File: pkg/setting/setting.go (hunk 1 above)
Comment (Hofls) [reply pkg/setting/setting.go]: Thanks for your feedback, i will replace `log.Fatal` with `error`.
I thought it was ok to use `log.Fatal` in `settings.go`, because it is already being used there.
Maybe we should open an issue to remove all usage of `os.Exit` and `log.Fatal` outside of `pkg/cmd/grafana-server` package?

Comment (Hofls) [reply pkg/setting/setting.go]: > I dont want to use `log.Fatal` like this since it calls `os.Exit`. The function should return an error instead. `os.Exit` Should only be called from the `pkg/cmd/grafana-server` package

I replaced `log.Fatal` with `error` and added a few tests.

**Review by bergquist — APPROVED** [review]

**Comment by bergquist** [comment]
Looks good! Once you solved the conflicts this can be merged.

**Comment by Hofls** [comment]
> Looks good! Once you solved the conflicts this can be merged.

Conflicts have been solved.

**Comment by bergquist** [comment]
Thank you for contributing to Grafana!
