### PR TITLE
Explore: Fix limit in case of Loki logs.

### LINKED ISSUE #19199: v6.4.0-beta1: Loki maximum lines configuration is not working
**What happened**:
I configured the Maximum Lines limit for Loki datasource to 3000. But when I make a query through the explore section, the limit is overridden to 1000 and only 1000 lines are returned.

Screen Shot 2019-09-18 at 09 02 17

Screen Shot 2019-09-18 at 09 01 34

**What you expected to happen**:
I expected to have 3000 lines returned in the query.

**How to reproduce it (as minimally and precisely as possible)**:
- Setup Loki Maximum Lines limit to anything more than 1000.
- Go to the explore section.
- Make a query that should return more than 1000 lines.

**Anything else we need to know?**:
This is working correctly in v6.3.5

**Environment**:
- Grafana version: **v6.4.0-beta1**
- Data source type & version: **Loki**

### PR DESCRIPTION
**Pull request by aocenas**
Closes: https://github.com/grafana/grafana/issues/19199

Do not send explicit limit for logs and just fallback to config of the datasource (for Loki 1000 is the default there.)

### CODE REVIEW

**Comment by torkelo** [comment]
I think there should be a default limit , won’t this change cause issues for other datasources?

**Comment by aocenas** [comment]
@torkelo The only other which supports logs is Elastic as far as I know and that one does not seem to do anything with `maxDataPoints` it seems.

For Loki the default limit is set on the datasource already and Explore just overrode it here without ability to change that.

**Comment by aocenas** [comment]
Could be that the limiting is not implemented in elastic? Would expect some mapping of `maxDataPoints` to `size` or something like that but can't find anything.

**Comment by marefr** [comment]
Elastic uses max 500 documents for logs: https://github.com/grafana/grafana/blob/b20a258b72d3130747118c6f3c535fc5d1b3a15f/public/app/plugins/datasource/elasticsearch/query_builder.ts#L406

**Comment by hugohaggmark** [comment]
FYI Influx also has support for logs in Explore @aocenas

**Comment by torkelo** [comment]
Not sure what is best here. should maxDataPoints be the default that explore sends, that query editors or data source settings can override (internally in the query method)...

**Comment by aocenas** [comment]
> Not sure what is best here. should maxDataPoints be the default that explore sends, that query editors or data source settings can override (internally in the query method)...

In general I agree that this quite a bit inconsistent and will need to be improved on in the future but at this point when we actually have a config on Loki that sets max lines, it is weird to override that in explore without possibility to change that. So I think right now this PR makes sense as an incremental improvement and fix for imho weird behaviour. The elastic and influx seems to be still hardcoded for 500 and [1000](https://github.com/grafana/grafana/blob/2f9c2f3886a6a0e73436c2589caa52faab9766e8/public/app/plugins/datasource/influxdb/components/InfluxLogsQueryField.tsx#L94) lines.

**Comment by torkelo** [comment]
> it is weird to override that in explore without possibility to change that. So I think right now this PR makes sense as an incremental improvement and fix for imho weird behaviour. The elastic and influx seems to be still hardcoded for 500 and 1000 lines.

But it does not explore which is overriding it. Feels more like it's loki that is letting Explore override it by using maxDataPoints over the query or ds setting?

**Comment by aocenas** [comment]
> But it does not explore which is overriding it. Feels more like it's loki that is letting Explore override it by using maxDataPoints over the query or ds setting?

Well yeah I mean the logic is that DS config is hard limit so you cannot go higher what ever you set per query in `maxDataPoints`. But you can use `maxDataPoints` to make it lower that the DS limit. So I mean I do not think this wrong behaviour, just that explore was hardcoded for those 1000 which is not adjustable. So for Loki specifically that means the DS config can only limit it if you set it less than 1000. If you set it higher it has no effect.

If there was some query level setting in explore to set it (with 1000 as default) that would make more sense just not sure whether we want to do it as part of fix here.

File: public/app/features/explore/state/actions.ts [hunk 1]
```diff
@@ -466,8 +466,9 @@ export function runQueries(exploreId: ExploreId): ThunkResult<void> {
 
     const queryOptions = {
       minInterval,
-      // This is used for logs streaming for buffer size.
-      maxDataPoints: mode === ExploreMode.Logs ? 1000 : containerWidth,
+      // This is used for logs streaming for buffer size, with undefined it falls back to datasource config if it
+      // supports that.
+      maxDataPoints: mode === ExploreMode.Logs ? undefined : containerWidth,
```
Comment (hugohaggmark) [inline public/app/features/explore/state/actions.ts]: Is there some way to extract this to be testable?

**Review by torkelo — APPROVED** [review]
Let's go with this for now.

**Comment by aocenas** [comment]
@torkelo created an issue to keep this problem in mind: https://github.com/grafana/grafana/issues/19365

File: public/app/features/explore/state/actions.ts (hunk 1 above)
Comment (aocenas) [reply public/app/features/explore/state/actions.ts]: @hugohaggmark not exactly sure what you mean. The Loki datasource actually have test to check whether the `maxDataPoints` option works correctly (and it also tests whether `undefined` works although that does not conform to the typings).

Or do you mean testing whether we get the correct value for the specified `ExploreMode`?

**Comment by aocenas** [comment]
Going to merge this for now. Created the bigger issue we can tackle this later in more general manner. Also @hugohaggmark let me know your thoughts on [this](https://github.com/grafana/grafana/pull/19235#discussion_r327606253) will add it afterwards to master.

File: public/app/features/explore/state/actions.ts (hunk 1 above)
Comment (hugohaggmark) [reply public/app/features/explore/state/actions.ts]: No biggie, I was thinking something in the line of `cont getMaxDataPoints = (mode) => ` and then have some simple tests for that.
