### PR TITLE
Fix incorrect metric values for scheduler_behind_seconds

### LINKED ISSUE #43031: Clock drift in Grafana managed alerts
**What happened**:

I created a Grafana managed alert. It seems to work fine in all the preview panels, even in "Query results" on the "View rule" page. However, to evaluate the rule in the background, Grafana seems to use a different clock time than the system clock. This is evident in two ways:

- Alerts (like Slack webhooks) trigger delayed by a specific time offset
- The "Created" timestamp if the "Matching instances" in the view rule page is delayed by the same offset, for all states (Normal, Pending, Firing).

Other places where Grafana logs timestamps (e.g. the dashboard history) use the correct clock time. Running the "date" command in the grafana container yields the correct date.

The first time, we noticed this issue on Grafana 8.2.1 (with a delay of ~5h 30min). Then, we updated to 8.3.1, which temporarily fixed the problem. After the weekend, we now again have a drift (delay) of around 15 minutes.

**What you expected to happen**:

The alerts should use the regular system clock and not have a clock drift.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure. For our Grafana instance, just leave Grafana running for a few days and then create an alert.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.3.1 (b9eacd93e9); go1.14
- Data source type & version: happens with elasticsearch and for prometheus
- OS Grafana is installed on: 4.19.0-16-amd64 # 1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: piechart-panel
- Others: podman 3.0.1

### PR DESCRIPTION
**Pull request by grobinson-grafana**
**What this PR does / why we need it**:

This pull request fixes a bug where `scheduler_behind_seconds` had incorrect values due to the tick having current monotonic timestamps.

**Which issue(s) this PR fixes**:

Fixes #43031

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/ngalert/schedule/schedule.go [hunk 1]
```diff
@@ -368,7 +368,11 @@ func (sch *schedule) schedulePeriodic(ctx context.Context) error {
 	for {
 		select {
 		case tick := <-sch.ticker.C:
-			start := time.Now()
+			// We use Round(0) on the start time to remove the monotonic clock.
+			// This is required as late ticks from the ticker have current monotonic
+			// timestamps such that start.Sub(tick) does not return the expected
+			// delta.
```
Comment (gotjosh) [inline pkg/services/ngalert/schedule/schedule.go:374]:
```suggestion
			// This is required as late ticks from the ticker contain a monotonic clock reading
			// and so does `start`, therefore operations such as `start.Sub(tick)` will use the monotonic values
			// and ignore wall time.
```

Comment (gotjosh) [reply pkg/services/ngalert/schedule/schedule.go:374]: The above is my understanding from:

```
The Time returned by time.Now contains a monotonic clock reading. If Time t has a monotonic clock reading, t.Add adds the same duration to both the wall clock and monotonic clock readings to compute the result. Because t.AddDate(y, m, d), t.Round(d), and t.Truncate(d) are wall time computations, they always strip any monotonic clock reading from their results. Because t.In, t.Local, and t.UTC are used for their effect on the interpretation of the wall time, they also strip any monotonic clock reading from their results. The canonical way to strip a monotonic clock reading is to use t = t.Round(0).

If Times t and u both contain monotonic clock readings, the operations t.After(u), t.Before(u), t.Equal(u), and t.Sub(u) are carried out using the monotonic clock readings alone, ignoring the wall clock readings. If either t or u contains no monotonic clock reading, these operations fall back to using the wall clock readings.

On some systems the monotonic clock will stop if the computer goes to sleep. On such a system, t.Sub(u) may not accurately reflect the actual time that passed between t and u.
```

TIL more about monotonic clocks than what I wanted to know.

**Review by gotjosh — APPROVED** [review]
LGTM
