### PR TITLE
middlware: change org when url contains orgid

### LINKED ISSUE #6948: [Bug] Alerting: email alert does not identify or link to the organization
> - What did you do?

Received an Grafana alert email 

> - What was the expected result?

I should be able to identify what organization and dashboard the alert has come from.

Clicking on the "View your alert rule" and "Go to alerts page" links should take me to the correct organization and dashboard.

> - What happened instead?

Email does not specify what organization the dashboard is on.

Clicking the links takes me to whatever organization I am currently logged into, which is most likely the wrong one, as we lean on the multi-organization capability of Grafana quite heavily.

So, clicking on the links just leads to "dashboard not found" and the only other way to find what alerted is to go through each organization by hand.

Alternatively I'd have to annotate each alert with the organization name but this is not a realfix.

### PR DESCRIPTION
**Pull request by bergquist**
closes #6948
ref #1613

### CODE REVIEW

File: pkg/services/alerting/eval_context.go [hunk 1]
```diff
@@ -113,7 +113,7 @@ func (c *EvalContext) GetRuleUrl() (string, error) {
 	if slug, err := c.GetDashboardSlug(); err != nil {
 		return "", err
 	} else {
-		ruleUrl := fmt.Sprintf("%sdashboard/db/%s?fullscreen&edit&tab=alert&panelId=%d", setting.AppUrl, slug, c.Rule.PanelId)
+		ruleUrl := fmt.Sprintf("%sdashboard/db/%s?fullscreen&edit&tab=alert&panelId=%d&org-id=%d", setting.AppUrl, slug, c.Rule.PanelId, c.Rule.OrgId)
```
Comment (torkelo) [inline pkg/services/alerting/eval_context.go]: since we refer to panelId as panelId I think I would prefer ordId for consistency

Comment (torkelo) [inline pkg/services/alerting/eval_context.go]: I mean orgId :)

**Comment by torkelo** [comment]
looks good!
