### PR TITLE
DashboardScene: adjust lib panel as a dashboard datasource refresh logic

### LINKED ISSUE #86988: Dashboard data source: Library panel is incorrectly shown in the query editor

### LINKED ISSUE #87128: Refreshing a panel in edit mode that has library panel as dashboard datasource does not load panel
https://github.com/grafana/grafana/assets/37613182/46b91d6a-73a3-42d5-9b7d-1dd9503067c0

### PR DESCRIPTION
**Pull request by Sergej-Vlasov**
**Not sure if this is not caused by a more global issue.** 
So far seems like two issues were causing the bug:
- ~panel id was not extracted correctly - `panel.state.key` in `LibraryVizPanel` was uuid and `panelKey` was the correct property~ fixed in https://github.com/grafana/grafana/pull/87125
- when refreshing panel B in edit view mode there would be no data because panel parent was not activated before subscribing to state in `dashboard-scene/scene/DashboardDatasourceBehaviour.tsx`

Fixes #87128

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard-scene/utils/PanelModelCompatibilityWrapper.ts [hunk 1]
```diff
@@ -10,10 +10,15 @@ export class PanelModelCompatibilityWrapper implements PanelModel {
   constructor(private _vizPanel: VizPanel) {}
 
   public get id() {
+    // console.log('this._vizPanel.parent', this._vizPanel.parent);
+    // console.log('this._vizPanel', this._vizPanel);
+
     const id = getPanelIdForVizPanel(
```
Comment (mdvictor) [inline public/app/features/dashboard-scene/utils/PanelModelCompatibilityWrapper.ts:16]: I think we should use `getPanelIdForLibraryVizPanel` instead of modifying `getPanelIdForVizPanel` here. So I think we can check if the vizPanel parent is `LibraryVizPanel` or not and call the appropriate function for it.

File: public/app/features/dashboard-scene/scene/DashboardDatasourceBehaviour.tsx [hunk 2]
```diff
@@ -57,6 +57,9 @@ export class DashboardDatasourceBehaviour extends SceneObjectBase<DashboardDatas
       if (!(panel.parent instanceof LibraryVizPanel)) {
         throw new Error('Could not find SceneQueryRunner for panel');
       } else {
+        if (!panel.parent.isActive) {
+          panel.parent.activate();
+        }
```
Comment (torkelo) [inline public/app/features/dashboard-scene/scene/DashboardDatasourceBehaviour.tsx:62]: need to call the deactivation function returned by activate (in the deactivation function for this behavior)

**Review by ivanortegaalba — APPROVED** [review]

**Comment by ivanortegaalba** [comment]
Tested and the problem is solved 💯
