### PR TITLE
Config: Support JSON list syntax

### LINKED ISSUE #57384: Missing documentation about specific behavior in Okta OAuth Configuration
**What happened**: While following [this](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/okta/) documentation, in the `allowed_groups` part. I discovered that if the group names have whitespace in them, the configuration does not work.

**What you expected to happen**: I hoped the spaces in the name worked, or this behavior was at least documented so that people are aware.

**How to reproduce it (as minimally and precisely as possible)**: Add any Okta groups that you are part of which have whitespace separating two words, e.g. `one two`. This will not work

I tried the following ways to see if I could escape the whitespace:
```ini
allowed_groups = one two, three four
allowed_groups = "one two, three four"
allowed_groups = 'one two, three four'
allowed_groups = "one two", "three four"
```

**Anything else we need to know?**: To make this work, I had to rename my Okta groups to have no whitespace. So the following worked:
```ini
allowed_groups = oneTwo, threeFour
```

**Environment**:
- Grafana version: v8.5.14 Enterprise
- Data source type & version:
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS, Chrome / Firefox
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by alexanderzobnin**
**What is this feature?**

This PR changes behavior of configuration options using lists, like `allowed_groups`, `allowed_organizations`, and others. New logic is:
- if list contains `[` as a first symbol, handle string as a JSON list (basically unmarshall it).
- Otherwise, behave as previously.

```
["foo", "bar baz"] => ["foo", "bar baz"]
"foo bar baz"      => ["foo", "bar", "baz"]
```

**Why do we need this feature?**

This allows to specify values containing spaces. For example, if list of allowed groups contains group with spaces in its name.

**Which issue(s) does this PR fix?**:

Fixes #57384

**Special notes for your reviewer**:

This `SplitString()` func is used in many different places, so I want to double check that we do not break anything. Change is small, but consequences might be huge.

### CODE REVIEW

**Review by linoman — APPROVED** [review]

File: pkg/util/strings.go [hunk 1]
```diff
@@ -32,6 +32,14 @@ func SplitString(str string) []string {
...
+	if strings.Contains(str, ",") {
+		// Separate by commas
+		substrs := make([]string, 0)
+		for _, s := range strings.Split(str, ",") {
+			substrs = append(substrs, strings.TrimSpace(s))
+		}
+		return substrs
+	}
 
 	return strings.Fields(strings.ReplaceAll(str, ",", " "))
```
Comment (linoman) [inline pkg/util/strings.go:44]: is this still necessary after parsing per commas in the previous code block?

File: pkg/util/strings.go [hunk 2]
```diff
@@ -32,6 +32,14 @@ func SplitString(str string) []string {
 	if len(str) == 0 {
 		return []string{}
 	}
+	if strings.Contains(str, ",") {
```
Comment (papagian) [inline pkg/util/strings.go:35]: since this function is used in several placed I would suggest making this functionality optional (introduce a flag parameter disabled by default) and enable it only for the specific cases
WDYT?

File: pkg/util/strings.go (hunk 1 above)
Comment (alexanderzobnin) [reply pkg/util/strings.go:44]: Yep, not necessary

File: pkg/util/strings.go (hunk 2 above)
Comment (alexanderzobnin) [reply pkg/util/strings.go:35]: It adds some extra complexity. So I want to make sure we do not use it to handle cases like:
```
"foo, bar baz" => ["foo", "bar", "baz"]
```

If we don't, I prefer to keep it simple.

Comment (papagian) [reply pkg/util/strings.go:35]: ok

Comment (alexanderzobnin) [reply pkg/util/strings.go:35]: Maybe I can add separate method for handling configuration options, like `SplitConfigParams()` to reduce affected area.

**Comment by Jguer** [comment]
@alexanderzobnin haven't had time to take a look at the implementation and may have missed it but will it handle cases where LDAP representations are used for groups in SAML/Oauth. This is common for idPs using LDAP as a provider
 
ex:
`allowed_groups=CN=Dev-India,OU=Distribution Groups,DC=gp,DC=gl,DC=google,DC=com CN=Diana Anton,OU=People,DC=gp,DC=gl,DC=google,DC=com`

File: pkg/util/strings.go (hunk 2 above)
Comment (Jguer) [reply pkg/util/strings.go:35]: this comma separation seems dangerous for LDAP groups, I've added a comment about specific scenarios

**Comment by sakjur** [comment]
We could support JSON lists? Keep current behavior, but if the first non-whitespace character of the setting is `[`, we assume it's a JSON list and will parse the option as such? That'd leave current behavior untouched except for a _very_ specific usecase, and the rules for escaping characters is somewhat well-established for JSON.

**Comment by alexanderzobnin** [comment]
Yes, I think Emil's approach is most safe.

**Review by Jguer — APPROVED** [review]
This will be really good. 

nit: is there some documentation that can be added so this is discoverable by users?

File: docs/sources/setup-grafana/configure-security/configure-authentication/gitlab/index.md [hunk 3]
```diff
@@ -110,6 +110,12 @@ the group `foo`, set
 allowed_groups = example, foo/bar
 ```
 
+In order to put values containing spaces in the list, use JSON syntax:
```
Comment (chri2547) [inline docs/sources/setup-grafana/configure-security/configure-authentication/gitlab/index.md:113]:
```suggestion
To put values containing spaces in the list, use the following JSON syntax:
```

File: docs/sources/setup-grafana/configure-security/configure-authentication/okta/index.md [hunk 4]
```diff
@@ -81,6 +81,12 @@ The `allowed_domains` option limits access to the users belonging to the specifi
 allowed_domains = mycompany.com mycompany.org
 ```
 
+In order to put values containing spaces in the list, use JSON syntax:
```
Comment (chri2547) [inline docs/sources/setup-grafana/configure-security/configure-authentication/okta/index.md:84]:
```suggestion
To put values containing spaces in the list, use the following JSON syntax:
```

File: docs/sources/setup-grafana/configure-security/configure-authentication/saml/index.md [hunk 5]
```diff
@@ -390,6 +390,12 @@ You can use `*` as the Grafana organization in the mapping if you want all users
 
 With the [`allowed_organizations`]({{< relref "../../../configure-grafana/enterprise-configuration/#allowed-organizations" >}}) option you can specify a list of organizations where the user must be a member of at least one of them to be able to log in to Grafana.
 
+In order to put values containing spaces in the list, use JSON syntax:
```
Comment (chri2547) [inline docs/sources/setup-grafana/configure-security/configure-authentication/saml/index.md:393]:
```suggestion
To put values containing spaces in the list, use the following JSON syntax:
```

**Review by chri2547 — APPROVED** [review]
Added a few suggestions. Thank you!
