### PR TITLE
Correlations: Fix incorrect state transitions in transformations editor

### LINKED ISSUE #75223: Correlations: Incorrect form state when editing transformations
There are a few problems with transformations editor:
- going back/next (try more than once) ends up in incorrect state with various results, e.g. showing incorrect type, having disabled state set incorrectly, or validation is applied incorrectly
- changing type of an existing transformation in edit form has no effect in the dropdown

Please check videos below for more details

Steps to reproduce an issue with validation:

1. Add a correlation without transformations
2. Edit the correlation by adding a transformation
3. Save the correlation
4. Click Back button
5. Click Next button
6. Try to save the correlation again

Actual: A validation error shows up "Please select a valid transformation type"
Expected: There are no changes made, correlation should save as normal

Video showing the validation issue:

https://github.com/grafana/grafana/assets/745532/ea05ab59-0f3f-4eb1-890f-f503c6870921

A few more problems related to it in the video below:

https://github.com/grafana/grafana/assets/745532/9bf8e57d-82e8-410b-b8d0-d2418f2c45e8

### PR DESCRIPTION
**Pull request by ifrost**
Fixes a few issues related to transformations editor. Please check #75223 for more details and reproduction steps.

Fixes #75223

- Editing transformation typewas not possible because of `<Select value={fieldVal.type} />`. This will always get the `default` value from the hook-form because `FieldArray` is not controlling the value. 
- To solve the above we could use `<Select value={field.value} ` from the `<Controller/>`. This, however works only after the page is rendered and will revert to defaults from the form after pressing "back" + "next" button (pressing "back" + "next"  causes the form to re-render and re-use defaults again)
- To make it work with "back"/"next" buttons we need to watch form state for changes and apply the value from the state. This is less performant but should be good enough in our case.
- To allow watching state of a values that are in an array I have extracted a row to a separate component to avoid calling `useWatch` inside a callback (that would break deleting rows).

### CODE REVIEW

**Review by gelicia — APPROVED** [review]
LGTM!

File: public/app/features/correlations/Forms/TransformationsEditor.tsx [hunk 1]
```diff
@@ -26,21 +15,14 @@ const getStyles = (theme: GrafanaTheme2) => ({
     font-size: ${theme.typography.h5.fontSize};
```
Comment (harisrozajac) [inline public/app/features/correlations/Forms/TransformationsEditor.tsx:15]: can we put these into an object to avoid adding to the betterer warnings? something like: 
```
const getStyles = (theme: GrafanaTheme2) => {
  return {
    heading: css({
      fontSize: `${theme.typography.h5.fontSize}`,
      fontWeight: `${theme.typography.fontWeightRegular}`,
    }),
  };
};
```

Comment (ifrost) [reply public/app/features/correlations/Forms/TransformationsEditor.tsx:15]: Good point! Updated in c96d238d6f9e5de7d694178c30c3c947d8b3cac1

**Comment by ifrost** [comment]
@gelicia / @harisrozajac I've resolved conflicts, brought back validation rules for type input (I'd removed them by accident 😨 ) and removed css literal strings.

**Review by gelicia — APPROVED** [review]
