### PR TITLE
Loki: Remove unnecessary deduplication

### LINKED ISSUE #26714: Grafana Explorer randomly removes / reorders entries with same timestamp from results returned by Loki API
**What happened**:
If Loki API returns multiple entries with the same internal timestamp (as imported by Promtail), only a "random" subset is shown in the UI and the order may not be preserved either.

**What you expected to happen**:
With deduplication OFF, Grafana Explorer UI shows exactly what Loki API returns.

**How to reproduce it (as minimally and precisely as possible)**:
Here's an example series of entries returned by Loki API that show the bug. There are ~20 entries with `1596023152896762800` timestamp, but Explorer UI only shows 5.

```
          [
            "1596023152897829400",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'MaterialInstance /Game/Twinmotion.Twinmotion:ResourceMaterialGeneric_2147455351.'\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'MaterialInstance /Game/Twinmotion.Twinmotion:ResourceMaterialGeneric_2147455360.'\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896159600",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
```

image

This results in Explorer API saying there are only 522 results out of a query with a limit of 1630, implying we have reached the end of the stream for this time period, which is completely false as Loki actually returned 1630 results.

image

**Anything else we need to know?**:
n/a

**Environment**:
- Grafana version: Grafana 7.1.1
- Data source type & version: Loki 1.5.0
- OS Grafana is installed on: Linux
- User OS & Browser: Mac / Chrome

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
Removes unnecessary deduplication. Read more here https://github.com/grafana/grafana/issues/26714. 
**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/26714

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ivanahuckova** [comment]
This is a tricky one. Please read for more context. 

Based on communication in https://github.com/grafana/grafana/issues/26714 we've learnt, that we are currently deduplicating Loki logs in Grafana that are not supposed to be duplicated. Therefore this PR removed the deduplication. By removing the deduplication, we have a new problem. We are currently creating/setting each log's `uid` which is basically hashed logs nano-timestamp, labels and log message. However, if we don't deduplicate logs, we can have multiple logs with the same uid and uid is not unique anymore. This **is a problem only in live tailing** where we have animation for new logs that relies on unique keys. But because at first, we are showing logs that were received from the regular range query we need to keep in mind that for the each log has to always have the same uid (no matter in which query it arrives).  This means that this uid can't be created randomly trough uid, or by using index. 

See here how the same log lines have different index, until we start to show only logs received from the websocket:
image


**Couple of solutions that I could think of:**
1. Currently, when live-tailing, we firstly show logs that were received from the regular range query. If we removed this and only shown logs received from the websocket, we could simply remove uid and rely just on index. This would solve the problem and wouldn't have too negative impact on users as it takes less than 1 sec for logs to appear. We could add spinner or something else to show users that logs are being fetched. See below example. If we added spinner or message, I think it wouldn't be too bad regression. 

Kapture 2020-12-08 at 17 13 55


2. We would keep the uid and wouldn't do any changes. In an edge case when users receive identical logs (that have the same nano timestamp + log lines + labels), the new logs highlighting would stop to work, but live-tailing and everything would work as before.  Only the animation would be affected. 

@aocenas @davkal thoughts on this?

**Comment by ivanahuckova** [comment]
Based on coversation with @davkal and @aocenas, for now, we are going to go with option 2. This PR is then ready for review.

File: packages/grafana-ui/src/components/Logs/LogRows.tsx [hunk 1]
```diff
@@ -137,7 +137,7 @@ class UnThemedLogRows extends PureComponent<Props, State> {
             {hasData &&
               firstRows.map((row, index) => (
                 <LogRow
-                  key={row.uid}
+                  key={`${row.uid}-${index}`}
```
Comment (ivanahuckova) [inline packages/grafana-ui/src/components/Logs/LogRows.tsx:140]: Uid is created by hashing all provided logs information. However, we might have multiple identical logs.Therefore we need to add index here. This pattern is used at other places in code base as well.

File: public/app/features/explore/Explore.tsx [hunk 2]
```diff
@@ -57,8 +57,8 @@ import { FILTER_FOR_OPERATOR, FILTER_OUT_OPERATOR, FilterItem } from '@grafana/u
 
 const getStyles = stylesFactory((theme: GrafanaTheme) => {
   return {
-    logsMain: css`
-      label: logsMain;
+    exploreMain: css`
```
Comment (ivanahuckova) [inline public/app/features/explore/Explore.tsx:60]: Not related to deduplication, but a little extra fix. 🙂

File: public/app/features/explore/LiveLogs.tsx [hunk 3]
```diff
@@ -14,7 +14,7 @@ const getStyles = (theme: GrafanaTheme) => ({
     font-size: ${theme.typography.size.sm};
     display: flex;
     flex-flow: column nowrap;
-    height: 65vh;
+    height: 60vh;
```
Comment (ivanahuckova) [inline public/app/features/explore/LiveLogs.tsx:17]: We have added second line in Loki query editor. This improves UI a little bit.

File: packages/grafana-ui/src/components/Logs/LogRows.tsx (hunk 1 above)
Comment (aocenas) [reply packages/grafana-ui/src/components/Logs/LogRows.tsx:140]: hmm what I don't like with this is that we have a property uid, which usually means unique identifier and that right away say, this may not be unique. From the meaning of that property, the data source should provide it and if it doesn't we do some fall back to something when processing the logs (I think we already just add an index there or something). So this does not feel right I think we should either abandon creation of uid in the Loki DS because it does not actually provide uids or maybe do an uuid4 or something like that in the datasource.

**Comment by ivanahuckova** [comment]
After conversation and great tip from @aocenas, I have implemented different solution. In Loki, I have added a logic that checks if the uid was already assigned, and if so, it adds the index after it. This way, uids are truly unique and different queries (range/live tailing) is going to provide consistent results. I have added tests as well.

File: public/app/plugins/datasource/loki/result_transformer.ts [hunk 4]
```diff
@@ -127,6 +130,9 @@ export function appendResponseToBufferedData(response: LokiTailResponse, data: M
   const labelsField = data.fields[3];
   const idField = data.fields[4];
 
+  // We need to store and track all used uids to ensure that uids are unique
+  const usedUids: { string?: number } = {};
```
Comment (aocenas) [inline public/app/plugins/datasource/loki/result_transformer.ts:134]: This won't probably work the same way as in `lokiStreamResultToDataFrame` as this is called only on the new lines. We probably have take all the current ids in `data` an use that as a map, otherwise we would be checking here only the few new lines that came later. I mean realistically this could be a problem only if the same line came in 2 separate batches from the websocket not sure how likely that is. What will happen in case we have 2 same ids when livestreaming? If it's only the visual fade highlight maybe I would not just add a comment here that this could happen but would not complicate the code right now.

**Review by aocenas — APPROVED** [review]
Apart from that one comment this looks good
