### PR TITLE
Tempo: Enable native histograms for Tempo service graph 

### LINKED ISSUE #105904: Tempo: Enable native histograms integration with AppO11y under the Tempo service map
### ✨ What is this?

AppO11y uses the Tempo service map. The Tempo service map in Grafana currently has hardcoded links to classic Prometheus histogram queries, but doesn't support native histograms even when Tempo is configured to generate them. We need to update the service map (or update Tempo) to use native histograms instead of using the current hardcoded classic histogram queries.

#### 📸 Service Map Links in AppO11y

Image

#### 📸 Service Map Links In Tempo Explore

Image

#### Current State:

- Tempo service map displays nodes for each service with hover links to Prometheus queries
- These links are hardcoded to use classic histogram metrics
- Links direct users to Grafana's Explore query editor with pre-built Prometheus queries

#### The Problem:

- Tempo can be configured to generate native histograms (newer, more efficient format)
- When native histograms are enabled, the hardcoded classic histogram links become incorrect/irrelevant
- Users lose access to proper histogram data visualization from the service map

#### Technical Requirements:

- configure Tempo to generate native histograms in gdev-tempo data source
- configure Prometheus to ingest native histograms
- Fallback Behavior: Maintain backward compatibility with classic histograms when native histograms aren't configured

#### Tempo code references

- [hardcoded classic histograms](https://github.com/grafana/grafana/blob/71a60e273432f870e400ff28ef556861c73caa35/public/app/plugins/datasource/tempo/graphTransform.ts#L17)
- [Where the classic histogram link in the service map is generated](https://github.com/grafana/grafana/blob/71a60e273432f870e400ff28ef556861c73caa35/public/app/plugins/datasource/tempo/datasource.ts#L1168-L1173)

#### Configuration Reference:

- Native histogram generation is controlled via Tempo's standard overrides configuration
Documentation: https://grafana.com/docs/tempo/latest/configuration/#standard-overrides

#### Impact:
 
- This enhancement will ensure service map users always get relevant, working links to histogram data regardless of their Tempo histogram configuration, improving the overall observability workflow.

### PR DESCRIPTION
**Pull request by bohandley**
Fixes https://github.com/grafana/grafana/issues/105904

Screenshot 2025-05-25 at 11 15 44 PM

Screenshot 2025-05-25 at 11 27 51 PM

**What is this feature?**

This enables native histograms to be used in the Service Graph (service map) in Tempo which is also used in AppO11y. It also updates the Tempo data source in devenv so that both native histograms and classic are generated by Tempo and ingested by Prometheus.

**Why do we need this feature?**

Native histograms in Prometheus will be GA soon in Grafana. This supports that initiative.

**Who is this feature for?**

This is for users of Tempo and users of AppoO11y that have configured Tempo to generate native histograms.

**Which issue(s) does this PR fix?**:
https://github.com/grafana/grafana/issues/105904

**What was changed to make this happen?**:

1. Tempo config page for Service Map configuration now has a select to opt in to this feature, `classic`, `native`, `both`
2. When both or native is selected, this changes the links to Prometheus histogram queries
Screenshot 2025-05-25 at 11 11 15 PM
3. Service Map error and duration queries use native histograms if configured only for `native`. Default is `classic`

**How to Test**:

1. Run gdev-tempo but make sure you delete your docker containers related to Tempo as the Tempo and Prometheus configs have been updated.
2. See that the gdev tempo data source config page shows that 'both' is selected under service map config section.
3. This will create links to both classic and native histograms in the service map Prom links.
4. If you change the option to `native` these two files and rebuild the containers you will see only native histograms used.
  - devenv/datasources.yaml =>  

```
      serviceMap:
        datasourceUid: 'gdev-prometheus'
        histogramType: 'native'
```

  - tempo.yaml =>  `generate_native_histograms: native`

5. This will also use a native histogram for the error and duration query as well as queries generated by the service map metrics.

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/datasource/tempo/configuration/ServiceGraphSettings.tsx [hunk 1]
```diff
@@ -52,6 +88,27 @@ export function ServiceGraphSettings({ options, onOptionsChange }: Props) {
...
+      <InlineFieldRow className={styles.row}>
+        <InlineField
+          tooltip={nativeHistogramDocs}
+          label="Histogram type"
+          labelWidth={26}
+          interactive={true}
+        >
+          <Combobox
+            id="histogram-type-select"
+            value={options.jsonData.serviceMap?.histogramType || 'classic'}
```
[the remark this answers is not in the document]
Comment (bohandley) [reply public/app/plugins/datasource/tempo/configuration/ServiceGraphSettings.tsx:100]: I ensure that classic is the right choice. Resolving conversation.

File: public/app/plugins/datasource/tempo/datasource.ts [hunk 2]
```diff
@@ -512,13 +515,14 @@ export class TempoDatasource extends DataSourceWithBackend<TempoQuery, TempoJson
...
+      const { datasourceUid, histogramType } = this.serviceMap;
       const tempoDsUid = this.uid;
       subQueries.push(
-        serviceMapQuery(options, dsId, tempoDsUid).pipe(
+        serviceMapQuery(options, datasourceUid, tempoDsUid, histogramType).pipe(
           concatMap((result) =>
-            rateQuery(options, result, dsId).pipe(
-              concatMap((result) => errorAndDurationQuery(options, result, dsId, tempoDsUid))
+            rateQuery(options, result, datasourceUid).pipe(
+              // this will need the histogram type too
```
Comment (ifrost) [inline public/app/plugins/datasource/tempo/datasource.ts]: `histogramType` seems to be passed already - is this comment still needed?

**Review by ifrost — APPROVED** [review]
LGTM! Thanks for a great PR description!

File: public/app/plugins/datasource/tempo/datasource.ts (hunk 2 above)
Comment (bohandley) [reply public/app/plugins/datasource/tempo/datasource.ts]: Removed!
