### PR TITLE
Explore: error handling and time fixes

### LINKED ISSUE #13343: Explore: Not showing Prometheus query errors (500)
When a `query_range` request returns with a 500 text/plain response, the error is not shown.

This is hard to repro because it's hard to produce 500 responses. Might need to fake it.

Check additionally:
- does it happen in regular dashboard panels

### LINKED ISSUE #13812: Explore: blank page if Prometheus responds with 503
Prometheus responds with 503 when starting if it needs to replay its WAL.  When loading explore in this situation, just get a blank page.  Would be useful to show the error, and the datasource selector so I can try a different one.

### PR DESCRIPTION
**Pull request by davkal**
- use global range types
- add ErrorBoundary around individual Explore components
- fix table merge on empty results
- fix TimePicker date parsing on ISO dates
- fix TimePicker range string after relative move

Fixes #13343
Fixes #13812

### CODE REVIEW

File: public/app/features/explore/ErrorBoundary.tsx [hunk 1]
```diff
@@ -0,0 +1,34 @@
+import React, { Component } from 'react';
+
+export default class ErrorBoundary extends Component<{}, any> {
```
Comment (torkelo) [inline public/app/features/explore/ErrorBoundary.tsx]: wonder if this could be made it a more generic error handler , maybe as a decorator class or HOC that other components can use.  Question is should it use the alert popups as way to show error or some other way

Comment (davkal) [reply public/app/features/explore/ErrorBoundary.tsx]: I'd keep it as a component for now, since you can make clear which parts are bounded. We can add integration with pop ups later.

**Review by torkelo — APPROVED** [review]

File: public/app/features/explore/ErrorBoundary.tsx (hunk 1 above)
Comment (peterholmberg) [reply public/app/features/explore/ErrorBoundary.tsx]: Is it not possible to use Reacts Error boundry?

Comment (davkal) [reply public/app/features/explore/ErrorBoundary.tsx]: > Is it not possible to use Reacts Error boundry?

 What do you mean?

Comment (torkelo) [reply public/app/features/explore/ErrorBoundary.tsx]: https://reactjs.org/docs/error-boundaries.html
