### PR TITLE
Azure Monitor: Small bug fixes for Resource Picker

### LINKED ISSUE #44039: AzureMonitor: Overlay glitch in Logs resource picker
**What happened**:

When a resource is selected, layers are not behaving properly. The selected item div is on top of the table, which causes some elements in the list to be hidden but this is not working properly when the checkbox is selected:

Peek 2022-01-14 10-49

(only happens when the height of the browser is small enough).

**What you expected to happen**:

The checkbox should not be shown when scrolling.

**How to reproduce it (as minimally and precisely as possible)**:

See the gif above.

**Anything else we need to know?**:

There are two possible solutions:

1. Right now, the header in the resource picker is a standalone table and the footer is a div in a different layer so it's shown on top of the resources table. Ideally, we should be able to have a single table with a sticky header and a footer.
2. Fix the layer for the checkbox when it's selected.

The second option should be easier but new issues may appear so the first solution is desirable. 

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by sarahzinger**
**What this PR does / why we need it**:
While working on our resource picker, I found 2 bugs that I think could be fixed. 

The first is a small css fix, where checkboxes had the wrong z index:
https://recordit.co/pteFqqP42a

The second issue was when trying to select a subscription, it would not create a resource uri (/subscriptions/subId) and instead would try to make the request directly with the subId and always fail 

https://recordit.co/gSCTDX0kig

**Which issue(s) this PR fixes**:

I did not make an issue, I just made the pr 🤷🏻‍♀️ 
UPDATE: Fixes https://github.com/grafana/grafana/issues/44039

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts [hunk 1]
```diff
@@ -68,14 +68,15 @@ export default class ResourcePickerData extends DataSourceWithBackend<AzureMonit
 
     return resources.map((subscription) => ({
       name: subscription.subscriptionName,
-      id: subscription.subscriptionId,
+      id: `/subscriptions/${subscription.subscriptionId}`,
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:71]: this is confusing, some times this code is using `id` as the resource ID (like it was before this change), and some others it's using an URI. Can we change the name of this to `uri` if we are going to use it always as an URI?

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts [hunk 2]
```diff
@@ -68,14 +68,15 @@ export default class ResourcePickerData extends DataSourceWithBackend<AzureMonit
...
       typeLabel: 'Subscription',
       type: ResourceRowType.Subscription,
       children: [],
     }));
   }
 
-  async getResourceGroupsBySubscriptionId(subscriptionId: string) {
+  async getResourceGroupsBySubscriptionId(subscriptionURI: string) {
+    const subscriptionId = subscriptionURI.includes('/subscriptions/') ? subscriptionURI.slice(15) : subscriptionURI;
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:79]: this is also ambiguous because `subscriptionURI` can be an URI or an ID. Can we make this two functions if needed? (`getResourceGroupsBySubscriptionId` and `getResourceGroupsBySubscriptionURI`) or make it so it's always a URI

**Review by andresmgot — COMMENTED** [review]
I wrote an issue for the first thing in the past so this can close that one :)

https://github.com/grafana/grafana/issues/44039

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts (hunk 2 above)
Comment (sarahzinger) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:79]: I am trying to make it so that it's always a URI but users could potentially have broken dashboards where it is not saved as a uri, so this is to try handle that. All new dashboards would have it as a uri. I suppose I could just make the assumption that no one is saving a broken dashboard and expecting it to work and just always assume it's a uri?

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts (hunk 1 above)
Comment (sarahzinger) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:71]: I'll change the name to uri I think? The problem is with resource groups and resources we've been saving the id as a URI, but not for subscriptions. I could attempt to solve this another way by just storing the id and crafting the uri wherever we need it, but it felt like there might be risk of breaking people's dashboards in doing so...but now I'm thinking about it and I'm not entirely sure that's really a risk. 🤔

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts (hunk 2 above)
Comment (andresmgot) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:79]: got it, if that's the case, maybe a comment explaining that should be enough (and a test! so we don't break it unintentionally)

**Review by andresmgot — APPROVED** [review]
I am not seeing any breaking change now so my +1 once you are done with the tests. Thanks! One step closer to untangle things :)

**Comment by sarahzinger** [comment]
@andresmgot thank you for the many reviews! Would you mind checking one more time, I made some bigger updates to the tests and could use some 👀 to make sure the changes seem reasonable

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/ResourcePicker/NestedResourceTable.test.tsx [hunk 3]
```diff
@@ -1,108 +0,0 @@
-import { act, render, screen } from '@testing-library/react';
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/ResourcePicker/NestedResourceTable.test.tsx:1]: what happened to these tests?

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/ResourcePicker/ResourcePicker.test.tsx [hunk 4]
```diff
@@ -10,119 +10,143 @@ import {
...
-      expect(resourePickerDataMock.getResourceGroupsBySubscriptionId).toHaveBeenLastCalledWith(
-        singleSubscriptionSelectionURI
-      );
-      expect(resourePickerDataMock.getResourcesForResourceGroup).toHaveBeenCalledTimes(1);
-      expect(resourePickerDataMock.getResourcesForResourceGroup).toHaveBeenLastCalledWith(
-        singleResourceGroupSelectionURI
-      );
-    });
+    expect(onApply).toBeCalledTimes(1);
+    expect(onApply).toBeCalledWith('$workspace');
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/ResourcePicker/ResourcePicker.test.tsx:150]: nice improvement to these tests!

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts [hunk 5]
```diff
@@ -69,13 +67,14 @@ export default class ResourcePickerData extends DataSourceWithBackend<AzureMonit
     return resources.map((subscription) => ({
       name: subscription.subscriptionName,
       id: subscription.subscriptionId,
+      uri: `/subscriptions/${subscription.subscriptionId}`, // usually the id is the uri, but for subscriptions it's the opposite
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:70]: does this comment still applies? Is the id the uri in any case?

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts [hunk 6]
```diff
@@ -102,32 +101,54 @@ export default class ResourcePickerData extends DataSourceWithBackend<AzureMonit
...
-      id: r.resourceGroupURI,
-      type: ResourceRowType.ResourceGroup,
-      typeLabel: 'Resource Group',
-      children: [],
-    }));
+    return resourceGroups.map((r) => {
+      const parsedUri = parseResourceURI(r.resourceGroupURI);
+      if (!parsedUri || !parsedUri.resourceGroup) {
+        throw new Error('unable to fetch resource groups');
+      }
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:115]: can you cover this new code with some test?

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts [hunk 7]
```diff
@@ -102,32 +101,54 @@ export default class ResourcePickerData extends DataSourceWithBackend<AzureMonit
...
       | where id hasprefix "${resourceGroupId}"
       | where type in (${logsSupportedResourceTypesKusto}) and location in (${logsSupportedLocationsKusto})
     `);
 
-    return formatResourceGroupChildren(response);
+    return response.map((item) => {
+      const parsedUri = parseResourceURI(item.id);
+      if (!parsedUri || !parsedUri.resource) {
+        throw new Error('unable to fetch resource details');
+      }
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:138]: same about covering this, more because we are now using `id` not `uri`

**Review by andresmgot — COMMENTED** [review]
LGTM! I just wonder where the tests for NestedResourceTable have gone

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/ResourcePicker/NestedResourceTable.test.tsx (hunk 3 above)
Comment (sarahzinger) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/ResourcePicker/NestedResourceTable.test.tsx:1]: I removed them because I felt like we're adequately testing them at the Resource Picker level

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts (hunk 5 above)
Comment (sarahzinger) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:70]: lol yeah it's confusing, the id from azure is usually the uri, but this comment is more confusing than helpful so will remove haha

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts (hunk 6 above)
Comment (sarahzinger) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:115]: ooh good point will do!

**Review by andresmgot — APPROVED** [review]
:+1:
