### PR TITLE
LegacyBrowser: fix Safari 13.1 (lacks logical nullish assignent)

### LINKED ISSUE #46110: OS X Safari 13.1.2 no longer loads Grafana after update to 8.4.2
**What happened**:
After updating Grafana to 8.4.2 Safari 13.1.2 (latest of that line of versions), Grafana can longer be accessed. On the same machine Chrome / Firefox load the page. 

**What you expected to happen**:
That it continues to load, like 2h earlier before updating to Grafana 8.4.2. 

**Anything else we need to know?**:
I know this an old version of Mac OS and Safari, but it is still one of the preferred development environments of many in regards to many aspects such as minimal SIP integration, stability, many hardware drivers for older lab / development equipment is no longer being supported on never systems. 
I can live with some UI snags, but getting cut-off on a default browser seems a bit harsh. I won't switch to another browser i rather downgrade Grafana and leave it at that. 

**Environment**:
- Grafana version: 8.4.2
- Data source type & version: 
- OS Grafana is installed on: Linux / Raspberry Pi
- User OS & Browser: OS X High Sierra 10.13.6, Safari 13.1.2

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes #46110

Judging by the feedback in the linked issue, these are the only changes needed to unbork Safari 13.1. Yes it's old, but looks easy to support currently.

The other problem found in that investigation for even older browsers is "Optional catch binding" which we emit as a result of targeting esnext in TypeScript and appears to be supported in Safari 13.1: https://caniuse.com/?search=Optional%20catch%20binding

### CODE REVIEW

File: packages/grafana-data/src/transformations/transformers/labelsToFields.ts [hunk 1]
```diff
@@ -70,7 +70,7 @@ export const labelsToFieldsTransformer: SynchronousDataTransformerInfo<LabelsToF
             continue;
           }
 
-          const uniqueValues = (uniqueLabels[labelName] ||= new Set());
```
Comment (leeoniya) [inline packages/grafana-data/src/transformations/transformers/labelsToFields.ts:73]: by the looks of it, i'm assuming `??=` was actually intended here

File: public/app/plugins/panel/heatmap-new/module.tsx [hunk 2]
```diff
@@ -169,7 +169,7 @@ export const plugin = new PanelPlugin<PanelOptions, GraphFieldConfig>(HeatmapPan
       .addNumberInput({
         path: 'hideThreshold',
         name: 'Hide cell counts <=',
-        defaultValue: 0.000_000_001, // 1e-9
```
Comment (leeoniya) [inline public/app/plugins/panel/heatmap-new/module.tsx:172]: not technically needed for Safari, but reduces the changes needed in custom forks to support some older browsers

**Review by torkelo — APPROVED** [review]

**Review by Clarity-89 — APPROVED** [review]
