### PR TITLE
MultiCombobox: Fix labels disappearing on selected items when filtering

### LINKED ISSUE #100598: MultiCombobox: Selected value labels disappear when they are not in filtered list
### What happened?

https://github.com/user-attachments/assets/a4527079-0934-4934-8468-222a5a7abea8

### What did you expect to happen?

For the label to stick around

### Did this work before?

I think so

### How do we reproduce it?

1. Go to Storybook

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by tskarhed**
**What is this feature?**

https://github.com/user-attachments/assets/3cf5bd3b-bec2-44e9-a96a-012250ae4054

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #100598

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/Combobox/MultiCombobox.tsx [hunk 1]
```diff
@@ -79,8 +79,8 @@ export const MultiCombobox = <T extends string | number>(props: MultiComboboxPro
       return [];
     }
 
-    return getSelectedItemsFromValue<T>(value, baseOptions);
-  }, [value, baseOptions]);
+    return getSelectedItemsFromValue<T>(value, typeof props.options !== 'function' ? props.options : baseOptions);
```
Comment (tskarhed) [inline packages/grafana-ui/src/components/Combobox/MultiCombobox.tsx:82]: I tried exporting `isAsync` from `useOptions`, by Typescript still wasn't a fan

**Review by joshhunt — APPROVED** [review]
