### PR TITLE
Prometheus: Handle non-json errors in a better way

### LINKED ISSUE #92764: Prometheus: parse non-json errors
Sometimes we get errors that are not json and `jsoniter` breaks like this

```
ReadObject: expect { or , or } or n, but found u, error found in #1 byte of ...|unexpected |..., bigger context ...|unexpected error |...
(Trace ID: 0000e63fb664a14cd0fdcc070c6d9b78) 
```

We can check that the response is json before running `jsoniter` and parse the error as what it is.

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

This adds an explicit parsing error when there is a non-json data passed to parser. An example case would be: some prometheus instances behind a proxy and that requires authentication. For some reason this authentication fails and we got a auth page back instead of json response. It looks like this:

```
ReadObject: expect { or , or } or n, but found <, error found in #1 byte of ...|<!DOCTYPE h|..., bigger context ...|<!DOCTYPE html><html lang="en-US"><body><div>Authen|...
```

That error above was happening because we were trying to parse a non-json data. So now we are detecting that responses even before sending the data to parser. 
Instead of above error we will show a bit more understandable error. 
Additionally each error has an `errorSource` too.

**Why do we need this feature?**

A better error handling

**Who is this feature for?**

Prometheus users. 

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/92764

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by aknuds1 — COMMENTED** [review]
Can you fix CI failures?

File: pkg/promlib/converter/prom.go [hunk 1]
```diff
@@ -39,7 +40,7 @@ func ReadPrometheusStyleResult(jIter *jsoniter.Iterator, opt Options) backend.Da
 l1Fields:
 	for l1Field, err := iter.ReadObject(); ; l1Field, err = iter.ReadObject() {
 		if err != nil {
-			return rspErr(err)
+			return rspErr(fmt.Errorf("response from prometheus couldn't parsed. it is non-json: %w", err))
```
Comment (aknuds1) [inline pkg/promlib/converter/prom.go:43]:
```suggestion
			return rspErr(fmt.Errorf("response from prometheus couldn't be parsed. it is non-json: %w", err))
```

File: pkg/promlib/querydata/response_test.go [hunk 2]
```diff
@@ -61,10 +62,47 @@ func TestAddMetadataToMultiFrame(t *testing.T) {
...
-		res := &http.Response{Body: io.NopCloser(bytes.NewBufferString(resBody))}
+		res := &http.Response{Body: io.NopCloser(bytes.NewBufferString(resBody)), StatusCode: 200}
 		result := qd.parseResponse(context.Background(), &models.Query{}, res)
 		assert.Nil(t, result.Error)
 		assert.Len(t, result.Frames, 1)
 		assert.Equal(t, "yMin", result.Frames[0].Fields[1].Name)
 	})
 }
+
+// Helper function to create mock HTTP response
```
Comment (aknuds1) [inline pkg/promlib/querydata/response_test.go:73]: Idiomatically, Go doc comments end with a period.
```suggestion
// Helper function to create mock HTTP response.
```

File: pkg/promlib/querydata/response_test.go [hunk 3]
```diff
@@ -61,10 +62,47 @@ func TestAddMetadataToMultiFrame(t *testing.T) {
...
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			res := createMockResponse(tt.statusCode, tt.body)
+			q := &models.Query{}
+			qd := QueryData{exemplarSampler: exemplar.NewStandardDeviationSampler}
+			qd.log = log.New()
+			resp := qd.parseResponse(ctx, q, res)
+
+			assert.NotNil(t, resp.Error)
```
Comment (aknuds1) [inline pkg/promlib/querydata/response_test.go:102]: `require` is more suitable here, since you don't want to continue the test if `resp.Error` is nil:
```suggestion
			require.Error(t, resp.Error)
```

File: pkg/promlib/querydata/response_test.go [hunk 4]
```diff
@@ -61,10 +62,47 @@ func TestAddMetadataToMultiFrame(t *testing.T) {
...
+			assert.Contains(t, resp.Error.Error(), "unexpected response")
+			assert.Equal(t, 1, len(resp.Frames))
```
Comment (aknuds1) [inline pkg/promlib/querydata/response_test.go:104]:
```suggestion
			assert.Len(t, resp.Frames, 1)
```

**Review by aknuds1 — APPROVED** [review]
LGTM modulo suggestions.
