### PR TITLE
Plugins: Fix plugin alias ID being used in PluginContext.ID

### LINKED ISSUE #76024: Plugins: PluginContext.PluginID can be populated with an alias
`plugincontext.Provider.Get`/`GetWithDataSource` passes the function argument as `PluginID` when constructing `PluginContext`.

https://github.com/grafana/grafana/blob/bd2191c158d8187575feeb9abb6b4d72d59c917f/pkg/services/pluginsintegration/plugincontext/plugincontext.go#L60-L69

Note this part in particular:

```go
	pCtx := backend.PluginContext{
		PluginID:      pluginID, // <---- pluginID is the argument provided to the function!
		PluginVersion: plugin.Info.Version,
	}
```

This can be a problem, because the `InMemory` registry now supports aliases, so a plugin can be referenced by its ID or one of its aliases:

https://github.com/grafana/grafana/blob/374e2a68f61ab1a41bac8cb459f6613187e04b55/pkg/plugins/manager/registry/in_memory.go#L82-L88

For example, the two following function calls will return the same instance of a `Plugin`:

```go
p.pluginStore.Plugin(ctx, "grafana-testdata-datasource")
p.pluginStore.Plugin(ctx, "testdata")
```

(so the values returned by `p.pluginStore.Plugin` will be the same => will have the same `ID` value).

But, when populating the `PluginContext`, one will have the actual plugin id, the other one will have the alias.

<details>

<summary>Code example (failing test)</summary>

```go
package plugincontext

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/grafana/grafana/pkg/infra/localcache"
	"github.com/grafana/grafana/pkg/plugins"
	"github.com/grafana/grafana/pkg/plugins/config"
	pluginFakes "github.com/grafana/grafana/pkg/plugins/manager/fakes"
	"github.com/grafana/grafana/pkg/plugins/manager/registry"
	fakeDatasources "github.com/grafana/grafana/pkg/services/datasources/fakes"
	"github.com/grafana/grafana/pkg/services/pluginsintegration/pluginstore"
	"github.com/grafana/grafana/pkg/setting"
)

func TestPluginContextAlias(t *testing.T) {
	cfg := setting.NewCfg()
	ds := &fakeDatasources.FakeDataSourceService{SimulatePluginFailure: true}
	internalPlugin := &plugins.Plugin{
		JSONData: plugins.JSONData{
			ID:       "grafana-testdata-datasource",
			AliasIDs: []string{"testdata"},
		},
	}
	pluginRegistry := registry.NewInMemory()
	require.NoError(t, pluginRegistry.Add(context.Background(), internalPlugin))
	provider := ProvideService(cfg, localcache.ProvideService(),
		pluginstore.New(pluginRegistry, &pluginFakes.FakeLoader{}),
		ds, nil, pluginFakes.NewFakeLicensingService(), &config.Cfg{},
	)

	for _, tc := range []struct {
		name  string
		query string
	}{
		{"by id", "grafana-testdata-datasource"},
		{"by alias", "testdata"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			p, err := provider.Get(context.Background(), tc.query, nil, 0)
			require.NoError(t, err)
			require.NotNil(t, p)
			require.Equal(t, internalPlugin.ID, p.PluginID)
		})
	}
}

```
</details>

This can cause unwanted behaviour. For example, I noticed one bug when checking plugin instrumentation metrics:

# Reproduction steps
1. Start Grafana backend + frontend with gdev devenv
2. Go to Explore
3. Select `gdev-testdata` and run any query
4. Open http://127.0.0.1:3000/metrics
5. You will see mismatching labels for `grafana_plugin_request_*`. `callResource` uses the plugin ID (`grafana-testdata-datasource`, correct), and `queryData` uses the alias (datasource type, `testdata`, wrong):
<details>

```
# HELP grafana_plugin_request_duration_milliseconds Plugin request duration
# TYPE grafana_plugin_request_duration_milliseconds histogram
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="0.005"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="0.01"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="0.025"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="0.05"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="0.1"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="0.25"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="0.5"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="1"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="2.5"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="5"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="10"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="25"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="50"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="100"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory",le="+Inf"} 1
grafana_plugin_request_duration_milliseconds_sum{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory"} 0
grafana_plugin_request_duration_milliseconds_count{endpoint="callResource",plugin_id="grafana-testdata-datasource",target="in_memory"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="0.005"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="0.01"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="0.025"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="0.05"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="0.1"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="0.25"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="0.5"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="1"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="2.5"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="5"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="10"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="25"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="50"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="100"} 1
grafana_plugin_request_duration_milliseconds_bucket{endpoint="queryData",plugin_id="testdata",target="in_memory",le="+Inf"} 1
grafana_plugin_request_duration_milliseconds_sum{endpoint="queryData",plugin_id="testdata",target="in_memory"} 0
grafana_plugin_request_duration_milliseconds_count{endpoint="queryData",plugin_id="testdata",target="in_memory"} 1
# HELP grafana_plugin_request_duration_seconds Plugin request duration in seconds
# TYPE grafana_plugin_request_duration_seconds histogram
grafana_plugin_request_duration_seconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory",le="0.005"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory",le="0.01"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory",le="0.025"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory",le="0.05"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory",le="0.1"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory",le="0.25"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory",le="0.5"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory",le="1"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory",le="2.5"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory",le="5"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory",le="10"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory",le="25"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory",le="+Inf"} 1
grafana_plugin_request_duration_seconds_sum{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory"} 0.000252932
grafana_plugin_request_duration_seconds_count{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",status="ok",target="in_memory"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory",le="0.005"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory",le="0.01"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory",le="0.025"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory",le="0.05"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory",le="0.1"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory",le="0.25"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory",le="0.5"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory",le="1"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory",le="2.5"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory",le="5"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory",le="10"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory",le="25"} 1
grafana_plugin_request_duration_seconds_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory",le="+Inf"} 1
grafana_plugin_request_duration_seconds_sum{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory"} 0.000286186
grafana_plugin_request_duration_seconds_count{endpoint="queryData",plugin_id="testdata",source="grafana-backend",status="ok",target="in_memory"} 1
# HELP grafana_plugin_request_size_bytes histogram of plugin request sizes returned
# TYPE grafana_plugin_request_size_bytes histogram
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="128"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="256"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="512"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="1024"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="2048"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="4096"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="8192"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="16384"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="32768"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="65536"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="131072"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="262144"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="524288"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="1.048576e+06"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory",le="+Inf"} 1
grafana_plugin_request_size_bytes_sum{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory"} 0
grafana_plugin_request_size_bytes_count{endpoint="callResource",plugin_id="grafana-testdata-datasource",source="grafana-backend",target="in_memory"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="128"} 0
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="256"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="512"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="1024"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="2048"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="4096"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="8192"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="16384"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="32768"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="65536"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="131072"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="262144"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="524288"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="1.048576e+06"} 1
grafana_plugin_request_size_bytes_bucket{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory",le="+Inf"} 1
grafana_plugin_request_size_bytes_sum{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory"} 191
grafana_plugin_request_size_bytes_count{endpoint="queryData",plugin_id="testdata",source="grafana-backend",target="in_memory"} 1
# HELP grafana_plugin_request_total The total amount of plugin requests
# TYPE grafana_plugin_request_total counter
grafana_plugin_request_total{endpoint="callResource",plugin_id="grafana-testdata-datasource",status="ok",target="in_memory"} 1
grafana_plugin_request_total{endpoint="queryData",plugin_id="testdata",status="ok",target="in_memory"} 1
```
</details>

### PR DESCRIPTION
**Pull request by xnyo**
**What is this feature?**

Fixes `ID` field in a `PluginContext` potentially populated with a plugin's alias rather than its actual ID.

More info in the issue: #76024

**Why do we need this feature?**

Bugfix

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #76024

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM

File: pkg/services/pluginsintegration/plugincontext/plugincontext_test.go [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+	"github.com/grafana/grafana/pkg/services/pluginsintegration/plugincontext"
+	"github.com/grafana/grafana/pkg/services/pluginsintegration/pluginsettings"
+	pluginSettings "github.com/grafana/grafana/pkg/services/pluginsintegration/pluginsettings/service"
+	"github.com/grafana/grafana/pkg/services/pluginsintegration/pluginstore"
+	secretstest "github.com/grafana/grafana/pkg/services/secrets/fakes"
+	"github.com/grafana/grafana/pkg/services/user"
+	"github.com/grafana/grafana/pkg/setting"
+)
+
+func TestGetAlias(t *testing.T) {
```
Comment (andresmgot) [inline pkg/services/pluginsintegration/plugincontext/plugincontext_test.go:26]: nit: this looks like the function tested is `GetAlias`, I would rename this to `TestGet` and then have a `t.Run("with alias" , ...`. Same for `GetWithDatasource`

**Review by andresmgot — APPROVED** [review]
Good catch! I just have a suggestion to reorder the tests a bit

File: pkg/services/pluginsintegration/pluginstore/fake.go [hunk 2]
```diff
@@ -12,6 +12,11 @@ type FakePluginStore struct {
 
 func (pr *FakePluginStore) Plugin(_ context.Context, pluginID string) (Plugin, bool) {
 	for _, v := range pr.PluginList {
+		for _, alias := range v.AliasIDs {
```
Comment (wbrowne) [inline pkg/services/pluginsintegration/pluginstore/fake.go:15]: Nit: Rather than duplicating logic here, maybe it makes sense to not mock the store + registry in the test in this case? Since we want to test the actual logic rather than "fake" logic

**Review by wbrowne — APPROVED** [review]
Great stuff!
