### PR TITLE
Alerting: Fix ambiguous handling of equals in labels when bucketing Loki state history streams

### LINKED ISSUE #65012: Alerting: Loki state history doesn't handle entries with equals signs in labels
**What happened**:

`grafana-plugin-sdk`'s `data.Labels` type is the canonical dataframe type for handling labels.

Its `LabelsFromString()` and `String()` methods break on labels containing `=`. The format it uses is ambiguous.

Loki state history relies on this type for label manipulation. The resulting behavior is undefined, and can cause incorrect labels or (more often) a failure to write to Loki. Let's use a different representation as a workaround.

**What you expected to happen**:

Labels containing equals to work.

**How to reproduce it (as minimally and precisely as possible)**:

Enable Loki state history.
Create a rule with a label like `abc: contains=equals`
Observe logs

**Anything else we need to know?**:

n/a

**Environment**:
- Grafana version: main

### PR DESCRIPTION
**Pull request by alexweav**
**What is this feature?**

`grafana-plugin-sdk`'s `data.Labels` type is the canonical dataframe type for handling labels.

Its `LabelsFromString()` and `String()` methods break on labels containing `=`. The format it uses is ambiguous.

We also can't use prometheus Labels format, its repr is also ambiguous around equals. Grafana's labels are a superset of Prometheus labels.

With this PR, we use a stable representation.

**Why do we need this feature?**

Allow equals to be used without issues.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/65012

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/ngalert/state/historian/loki.go [hunk 1]
```diff
@@ -248,7 +248,12 @@ func statesToStreams(rule history_model.RuleMeta, states []state.StateTransition
 		labels[RuleUIDLabel] = fmt.Sprint(rule.UID)
 		labels[GroupLabel] = fmt.Sprint(rule.Group)
 		labels[FolderUIDLabel] = fmt.Sprint(rule.NamespaceUID)
-		repr := labels.String()
+		lblJsn, err := json.Marshal(labels)
```
Comment (alexweav) [inline pkg/services/ngalert/state/historian/loki.go:251]: Choice of JSON as a stable representation was somewhat arbitrary.
- Hash of labels also works and is more compact. But, we're also relying on the labels being parseable later on, so we'd need to store the labels again separately, which undoes any memory savings. 
- `data.LabelsFromString(...)` already [understands JSON](https://github.com/grafana/grafana-plugin-sdk-go/blob/cdc5808e01ce7d8c5db8665207b0035bbb1fd82c/data/labels.go#L91-L96), so no code changes needed on parse side.

**Review by gotjosh — APPROVED** [review]

**Review by JohnnyQQQQ — APPROVED** [review]
LGTM
