### PR TITLE
URLParams: Stringify true values as key=true always

### LINKED ISSUE #97290: Dashboards: Regression with custom variables in Grafana 11.3.0
### What happened?

Since Grafana 11.3.x the custom variable presents a regression where it thinks it has a space or empty value by default. This makes charts that use such variable for queries break as any chart action (like edit) will update the variable to the empty value.
Image

Image

Video of Grafana 11.3.0:

https://github.com/user-attachments/assets/5bfa39e4-4712-4154-abfe-461a96ec29a1

### What did you expect to happen?

I expect the variable/url param to stay to the one that is set between navigation over the dashboard instead of going blank.

Video of Grafana 11.2.0:

https://github.com/user-attachments/assets/90fe314e-04a9-4dc6-aae1-f2d297a4b548

### Did this work before?

Yes, it is working fine on <11.3  and since 8.4 it had kept the same behavior for me.

### How do we reproduce it?

1. Create a dashboard
2. Add Grafana random walk datasource + chart
3. Add a custom variable with custom options `foo : true, bar : false`
5. Save and navigate to your dashboard and then open the chart in edit mode, the variable will be emptied.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Grafana v11.2.0 (2a88694fd3)
OS: Linux
Browser:  
* Chrome Version 109.0.5414.74 (Official Build) (64-bit)
* Firefox 133.0 (64-bit)

### Grafana platform?

Docker

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by yincongcyincong**
Fixes #97290

### CODE REVIEW

**Comment by yincongcyincong** [comment]
@tskarhed bro, could you please take a look this pr? thanks.

**Comment by tskarhed** [comment]
This is either @grafana/plugins-platform-frontend or @grafana/dashboards-squad who should review. I lack enough context to make an informed decision.

**Comment by yincongcyincong** [comment]
@eledobleefe @Ukochka bro. could you please take a look this pr. thanks

**Review by ivanortegaalba — COMMENTED** [review]
Hi, thanks for opening this PR!

This solves the bug of losing the value in the variable, which is the important bug, more than the format of the URL itself.

Please, make sure you update all the unit tests failing in the checks, and I'm ok to get it merged!

**Comment by yincongcyincong** [comment]
> Hi, thanks for opening this PR!
> 
> This solves the bug of losing the value in the variable, which is the important bug, more than the format of the URL itself.
> 
> Please, make sure you update all the unit tests failing in the checks, and I'm ok to get it merged!

@ivanortegaalba bro， i modified all relative unit test, please take a look.

**Comment by Clarity-89** [comment]
@yincongcyincong could you update your branch to the latest main and resolve the conflicts?

**Comment by Clarity-89** [comment]
@ivanortegaalba I assume this is good to merge from your point of view?

**Comment by jwb-coding** [comment]
Is there any update on this issue? The bug is becoming a real pain point for us. We rely heavily on template variables set to true and false, and none of them are working right now—they’re all throwing errors. The review and implementation of this bugfix would be greatly appreciated. Thanks!

**Comment by ivanortegaalba** [comment]
I double checked, and it works as expected. I'd like to merge. @yincongcyincong can you update with main? The checks doesn't pass.

**Review by ivanortegaalba — APPROVED** [review]

**Comment by yincongcyincong** [comment]
@ivanortegaalba thanks for your review. i merge main branch into this branch, please take a look.

**Comment by yincongcyincong** [comment]
@ivanortegaalba bro, could you please take a look this pr, thanks.

**Comment by Clarity-89** [comment]
@yincongcyincong could you update the branch again? The CI needs to be manually triggered after each push, sorry for the trouble!

**Comment by yincongcyincong** [comment]
@Clarity-89 thanks for your replying, i update my branch

**Comment by torkelo** [comment]
reverting this as it's breaking a lot of link functionality that relied on the current behavior

File: public/app/features/variables/utils.ts [hunk 1]
```diff
@@ -30,7 +30,7 @@ import { TransactionStatus, VariableModel } from './types';
  * \[\[(\w+?)(?::(\w+))?\]\]                  [[var2]] or [[var2:fmt2]]
  * \${(\w+)(?:\.([^:^\}]+))?(?::([^\}]+))?}   ${var3} or ${var3.fieldPath} or ${var3:fmt3} (or ${var3.fieldPath:fmt3} but that is not a separate capture group)
  */
-export const variableRegex = /\$(\w+)|\[\[(\w+?)(?::(\w+))?\]\]|\${(\w+)(?:\.([^:^\}]+))?(?::([^\}]+))?}/g;
+export const variableRegex = /\$(\w+)=true|\$(\w+)|\[\[(\w+?)(?::(\w+))?\]\]|\${(\w+)(?:\.([^:^\}]+))?(?::([^\}]+))?}/g;
```
Comment (torkelo) [inline public/app/features/variables/utils.ts:33]: why?
