### PR TITLE
Correlations: Create paginated API

### LINKED ISSUE #64144: Glue: Pagination for Correlations page
### Background

In theory users may have thousands of correlations. If that really happens we may need to add extra filtering/search capabilities but for now we just need to make sure the UI won't crash with too many correlations on the screen.

### Requirements ###

High level: _Implement pagination for correlations table_

#### Technical details

* API should contain `TotalCount`, `PerPage` and `Page` and accept `Page` as GET param (similar to query history and administration pages)
* UI should display paged result using pagination buttons: https://developers.grafana.com/ui/latest/index.html?path=/story/buttons-pagination--with-pages
* Add it to Explore, then review with Design System Squad how to promote it (Please create a follow up ticket about making pagination part of grafana ui)
* If interactive table's client side sorting does not work well with pagination, we should disable sorting and create a separate ticket to deal with sorting and pagination.

### PR DESCRIPTION
**Pull request by gelicia**
**What is this feature?**

Adds pagination to correlations API calls to support only showing a windowed subset of correlations at a time. This is to future proof against a scenario where a user has many, many correlations and showing them all at once would impact performance.

**Why do we need this feature?**

Paginating a list of items is common practice.

**Who is this feature for?**

Correlations users

**Which issue(s) does this PR fix?**:

Fixes #64144

**Special notes for your reviewer:**
This involved some other changes.

- Update to Pagination component: After adding pagination, the Correlations page had two next actions, going next on the wizard to the next step, and going to the next page. I had originally introduced an optional parameter here, but after talking with @JoaoSilvaGrafana , I am going to see what thoughts people have around just statically adding to the aria label
- Correlation fetch changes in Explore: Previously, loading explore would load all the correlations and apply the relevant ones to the dataframe. Introducing pagination meant removing the ability to load all the correlations, so we needed to be a bit smarter on how we fetch relevant correlations. We now attach correlations to the explore pane, not the main explore state, and get the correlations for one or more source UIDs.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.
- [ ] There are no known compatibility issues with older supported versions of Grafana, or plugins.
- [ ] It passes the [Hosted Grafana feature readiness review](https://docs.google.com/document/d/1QL9Ly8KnXzpb6ISbg49pTODRO5mhA5tkkfIZVX6pqQU/edit) for observability, scalability, performance, and security.

### CODE REVIEW

File: pkg/services/correlations/api.go [hunk 1]
```diff
@@ -298,8 +298,20 @@ type GetCorrelationsBySourceUIDResponse struct {
 // 404: notFoundError
 // 500: internalServerError
 func (s *CorrelationsService) getCorrelationsHandler(c *contextmodel.ReqContext) response.Response {
+	perPage := c.QueryInt64("perpage")
```
Comment (ifrost) [inline pkg/services/correlations/api.go:301]: I think it other APIs the param is called "limit", so it'd be good to keep it consistent.

**Review by ifrost — COMMENTED** [review]
Played a bit with API and works nice! The response body structure changes so we will need to adjust the frontend in this branch. Maybe to make it simple and split backend / frontend work we can:
* modify frontend code in this branch to use the new structure but just display the first page only
* make perPage infinite (or huuuge)
* work on fronted changes to support pagination in parallel branch based off this one

**Comment by gelicia** [comment]
I need to check the following
- mixed datasource
- API documentation

**Comment by gelicia** [comment]
After some discussion, we decided to proceed with this as follows

- Do not use a separate endpoint to get correlations with one source datasource UID. 
- Add an optional filter param on the main correlations fetch endpoint that lets you send one or more UIDs
- Have explore fetch a max of 100 correlations for all datasources selected
- Move the fetch function outside a hook so it can be used in the state actions for explore

**Comment by Elfo404** [comment]
we may also want to generate the swagger spec (`make swagger-api-spec`)

File: pkg/services/correlations/database.go [hunk 2]
```diff
@@ -225,17 +225,42 @@ func (s CorrelationsService) getCorrelationsBySourceUID(ctx context.Context, cmd
...
 
 	err := s.SQLStore.WithDbSession(ctx, func(session *db.Session) error {
-		return session.Select("correlation.*").Join("", "data_source AS dss", "correlation.source_uid = dss.uid and dss.org_id = ?", cmd.OrgId).Join("", "data_source AS dst", "correlation.target_uid = dst.uid and dst.org_id = ?", cmd.OrgId).Find(&correlations)
+		offset := cmd.Limit * (cmd.Page - 1)
+
+		q := session.Select("correlation.*").Join("", "data_source AS dss", "correlation.source_uid = dss.uid and dss.org_id = ?", cmd.OrgId).Join("", "data_source AS dst", "correlation.target_uid = dst.uid and dst.org_id = ?", cmd.OrgId)
+
+		if len(cmd.SourceUIDs) > 0 {
+			q.In("dss.uid", cmd.SourceUIDs)
+		}
```
Comment (Elfo404) [inline pkg/services/correlations/database.go:242]: we don't need this (and related changes) until we decide to implement filtering in the settings page, do we?

**Review by Elfo404 — COMMENTED** [review]
something popped up, will finish the review later :D

**Review by ifrost — COMMENTED** [review]
Looks nice (apart issues Gio already pointed out)! Really like that with that user can simply change the data source to get recent correlations, and no full page reload is required.

**Comment by gelicia** [comment]
> we may also want to generate the swagger spec (`make swagger-api-spec`)

@Elfo404 We might need to pair on this, I'm trying to remove the correlations related warnings but not having any success..

File: pkg/services/correlations/database.go (hunk 2 above)
Comment (gelicia) [reply pkg/services/correlations/database.go:242]: We do need it. We added the ability for explore to get correlations filtered by source UID here https://github.com/grafana/grafana/pull/65241/files#diff-41f602993af9972aa8e1fbabbb0cea49eb5c8decaa46646d4ce44afb77840f5eR78 and use that for populating the correlations on the pane state.

Comment (Elfo404) [reply pkg/services/correlations/database.go:242]: why aren't we using this instead? https://grafana.com/docs/grafana/latest/developers/http_api/correlations/#get-all-correlations-originating-from-a-given-data-source

Comment (gelicia) [reply pkg/services/correlations/database.go:242]: From what I remembered with our discussion, for mixed datasources we wanted to make one call and have the 100 limit be per call, not per datasource.

Having a filter on getting all correlations lets us only make one call, even in mixed environments, and enforce a pane-wide limit of only displaying 100 correlations.

Comment (Elfo404) [reply pkg/services/correlations/database.go:242]: aaaah that's true, i forgot about mixed, my bad. 🙇

Comment (gelicia) [reply pkg/services/correlations/database.go:242]: @Elfo404 my fault for having this ticket take approximately 50000 years to complete

File: public/app/features/correlations/CorrelationsPage.tsx [hunk 3]
```diff
@@ -180,19 +182,28 @@ export default function CorrelationsPage() {
...
+                    onUpdated={handleUpdated}
+                    readOnly={isSourceReadOnly({ source: correlation.source }) || !canWriteCorrelations}
+                  />
+                )}
+                columns={columns}
+                data={data.correlations}
+                getRowId={(correlation) => `${correlation.source.uid}-${correlation.uid}`}
+              />
+              <Pagination
+                currentPage={1}
```
[the remark this answers is not in the document]
Comment (gelicia) [reply public/app/features/correlations/CorrelationsPage.tsx]: Sorry, 😅 fixed!

**Comment by gelicia** [comment]
@Elfo404 thanks for your help- we got both the swagger and the openapi docs generated now

File: pkg/services/correlations/api.go [hunk 4]
```diff
@@ -298,8 +298,23 @@ type GetCorrelationsBySourceUIDResponse struct {
...
+	if limit <= 0 {
+		limit = 100
+	}
+
+	page := c.QueryInt64("page")
+	if page <= 0 {
+		page = 1
+	}
+
+	sourceUIDs := c.QueryStrings("sourceuid")
```
Comment (ifrost) [inline pkg/services/correlations/api.go:311]: In Correlations API responses it's called `sourceUID` so maybe we could make it consistent[^1]? 

[^1]: It's not really standardized, though, and all over the place with patterns like `org_id`, `connectionUid` and`dashboardUID` 🤦

**Review by ifrost — APPROVED** [review]
Works great 🙌  Left a few minor comments.

File: pkg/services/correlations/api.go (hunk 4 above)
Comment (Elfo404) [reply pkg/services/correlations/api.go:311]: in https://github.com/grafana/grafana/pull/51801#discussion_r930165948 i got asked to use `UID` as it was being standardized, however it is not really enforced anywhere else, but +1

**Review by Elfo404 — COMMENTED** [review]
there's only one issue i found when deleting the last correlations for a given page: we render the empty state because data contains no correlations.
i think we need to do 2 things here:
- the API should return a 404 when requesting data for a page that does not exist (but still return data such total count, etc...)
- in the FE we shouldn't show that empty state, i think we can be smart and either automatically change page if the user is deleting the last correlation in a given page or if the 404 response states that te total count is > 0, set the page to the "last valid one"

EDIT: thinking about that we can also avoid to be smart and make things easier and just show an empty state different form the current one together with the navigation to allow users to go to a different page

https://github.com/grafana/grafana/assets/1170767/d061a740-28d5-4006-93a5-abd6735e0baa

File: public/app/features/correlations/useCorrelations.ts [hunk 5]
```diff
@@ -9,25 +9,53 @@ import {
...
 export interface CorrelationData extends Omit<Correlation, 'sourceUID' | 'targetUID'> {
   source: DataSourceInstanceSettings;
   target: DataSourceInstanceSettings;
 }
 
+export interface CorrelationsData {
+  correlations: CorrelationData[];
+  page?: number;
+  limit?: number;
+  totalCount?: number;
```
[the remark this answers is not in the document]
Comment (gelicia) [reply public/app/features/correlations/useCorrelations.ts:36]: This is optional because I use this same interface for both paged and non paged correlations data. The only place we had non paged correlations data was getting correlations by sourceUID which wasnt needed anymore, so I removed that along with making these parameters non-optional.

File: public/app/features/correlations/CorrelationsPage.tsx [hunk 6]
```diff
@@ -89,9 +91,13 @@ export default function CorrelationsPage() {
 
   useEffect(() => {
     if (!remove.error && !remove.loading && remove.value) {
-      fetchCorrelations();
+      fetchCorrelations({ page });
     }
-  }, [remove.error, remove.loading, remove.value, fetchCorrelations]);
+  }, [remove.error, remove.loading, remove.value, fetchCorrelations, page]);
```
[the remark this answers is not in the document]
Comment (gelicia) [reply public/app/features/correlations/CorrelationsPage.tsx:96]: It is for the linter, I added a skip for that line

File: pkg/services/correlations/api.go [hunk 7]
```diff
@@ -298,8 +298,23 @@ type GetCorrelationsBySourceUIDResponse struct {
 // 404: notFoundError
 // 500: internalServerError
 func (s *CorrelationsService) getCorrelationsHandler(c *contextmodel.ReqContext) response.Response {
+	limit := c.QueryInt64("limit")
+	if limit <= 0 {
```
[the remark this answers is not in the document]
Comment (gelicia) [reply pkg/services/correlations/api.go:302]: I'm thinking default (for explore) is 100 and max can be 1000 but they'd have to hit the API directly to use it.

[the remark this answers is not in the document]
Comment (Elfo404) [reply pkg/services/correlations/api.go:302]: yup, also 1000 works!

**Comment by gelicia** [comment]
> * the API should return a 404 when requesting data for a page that does not exist (but still return data such total count, etc...)
> * in the FE we shouldn't show that empty state, i think we can be smart and either automatically change page if the user is deleting the last correlation in a given page or if the 404 response states that te total count is > 0, set the page to the "last valid one"

I think in this case, the API is fine - the endpoint is returning correct information which is an empty array for what's being queried. Instead I just did the second thing, where we page back in the correct situation. Let me know what you think - we can change the API too, it just seemed like more a UI issue.

File: public/app/features/correlations/CorrelationsPage.tsx [hunk 8]
```diff
@@ -89,26 +88,38 @@ export default function CorrelationsPage() {
...
     if (!remove.error && !remove.loading && remove.value) {
-      fetchCorrelations();
+      fetchCorrelations({ page });
     }
+    // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [remove.error, remove.loading, remove.value, fetchCorrelations]);
 
+  useEffect(() => {
+    fetchCorrelations({ page });
+  }, [fetchCorrelations, page]);
```
Comment (Elfo404) [inline public/app/features/correlations/CorrelationsPage.tsx:98]: with the latest changes everything looks good, but when deleting the last item of a page, both of these effects will trigger, causing a duplicate fetch 

Screenshot 2023-06-27 at 12 09 15

**Review by Elfo404 — DISMISSED** [review]

File: public/app/features/correlations/CorrelationsPage.tsx (hunk 8 above)
Comment (gelicia) [reply public/app/features/correlations/CorrelationsPage.tsx]: Good catch! try now :D

**Comment by gelicia** [comment]
@ifrost - the last commit were mostly changes provided by @Elfo404 , could you have a look again?

File: docs/sources/developers/http_api/correlations.md [hunk 9]
```diff
@@ -267,6 +267,12 @@ Status codes:
 
 Get all correlations.
 
+Query parameters:
+
+- **page** - Optional. Specify which page number to return. Use the limit parameter to specify the number of queries per page. The default is page 1.
+- **limit** - Optional. Limits the number of returned correlations per page. The default is 100 queries per page.
+- **sourceuid** - Optional. Specify a source datasource UID to filter by. This can be repeated to filter by multiple datasources.
```
Comment (ifrost) [inline docs/sources/developers/http_api/correlations.md:274]:
```suggestion
- **sourceUID** - Optional. Specify a source datasource UID to filter by. This can be repeated to filter by multiple datasources.
```

File: docs/sources/developers/http_api/correlations.md [hunk 10]
```diff
@@ -267,6 +267,12 @@ Status codes:
 
 Get all correlations.
 
+Query parameters:
+
+- **page** - Optional. Specify which page number to return. Use the limit parameter to specify the number of queries per page. The default is page 1.
+- **limit** - Optional. Limits the number of returned correlations per page. The default is 100 queries per page.
```
Comment (ifrost) [inline docs/sources/developers/http_api/correlations.md:273]:
```suggestion
- **limit** - Optional. Limits the number of returned correlations per page. The default is 100 queries per page. The maximum limit is 1000.
```

File: public/app/features/correlations/CorrelationsPage.test.tsx [hunk 11]
```diff
@@ -73,7 +73,14 @@ const renderWithContext = async (
     },
     fetch: (options: BackendSrvRequest) => {
       return new Observable((s) => {
-        s.next(merge(createFetchCorrelationsResponse({ url: options.url, data: correlations })));
+        s.next(
+          merge(
+            createFetchCorrelationsResponse({
+              url: options.url,
+              data: { correlations, page: 0, limit: 5, totalCount: 0 },
```
Comment (ifrost) [inline public/app/features/correlations/CorrelationsPage.test.tsx:80]:
```suggestion
              data: { correlations, page: 1, limit: 5, totalCount: 0 },
```

File: public/app/features/correlations/CorrelationsPage.tsx [hunk 12]
```diff
@@ -54,61 +56,59 @@ export default function CorrelationsPage() {
...
-          closeOnConfirm
-        />
-      ),
+    }: CellProps<CorrelationData, void>) => {
+      return (
+        !readOnly && (
+          <DeleteButton
+            aria-label="delete correlation"
+            onConfirm={() =>
+              handleDelete({ sourceUID, uid }, page.current > 0 && index === 0 && data?.correlations.length === 1)
```
Comment (ifrost) [inline public/app/features/correlations/CorrelationsPage.tsx:104]: Shouldn't this be 1 not 0? The page is always  > 0. At the moment if a very last correlation is removed, and a new one is created, then no page is selected in Pagination component.

```suggestion
              handleDelete({ sourceUID, uid }, page.current > 1 && index === 0 && data?.correlations.length === 1)
```

**Review by ifrost — COMMENTED** [review]
Looks good, just a few more small things left in comments.

File: public/app/features/correlations/CorrelationsPage.tsx (hunk 12 above)
Comment (gelicia) [reply public/app/features/correlations/CorrelationsPage.tsx]: Good catch! Tested by deleting all correlations manually then created one, it works as expected.

Comment (Elfo404) [reply public/app/features/correlations/CorrelationsPage.tsx]: and that's why folks reviews are important <3 thanks for catching this!

**Review by ifrost — APPROVED** [review]
