### PR TITLE
Pyroscope: Fix template variable support

### LINKED ISSUE #83068: Pyroscope: Template variables are broken
### What happened?

When adding Pyroscope template variables to dashboard only Query option that seems to work is  Query type:  Profile type

bug-pyroscope-ds-variables-profile-type

Setting Query type to Label does not create any Preview values

bug-pyroscope-ds-variables-label

Setting Query type to Label value does not create any Preview values and additionally shows an error message

bug-pyroscope-ds-variables-label-value

### What did you expect to happen?

All three options to work same way

### Did this work before?

N/A

### How do we reproduce it?

1. Setting up Pyroscope (monolith)
2. Adding Pyroscope datasource to Grafana

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:  v10.3.1 (00a22ff8b2)
OS: Linux
Browser: Chrome

### Grafana platform?

None

### Datasource(s)?

* pyroscope

### PR DESCRIPTION
**Pull request by aocenas**
Fixes: https://github.com/grafana/grafana/issues/83068

This actually fixes 3 problems:
- The matcher syntax to filter out appropriate labels or values was wrong. Before Pyroscope ignored this but once it started using it, it returned an error.
- If the API returned zero values it returned null instead of an empty array which the code did not expect.
- When changing the variable type, the clearing code sometimes cleared values it should not have, which means it could show that the label is selected but the query sent to the backend wouldn't include that label.

### CODE REVIEW

File: pkg/tsdb/grafana-pyroscope-datasource/pyroscopeClient.go [hunk 1]
```diff
@@ -256,6 +256,10 @@ func (c *PyroscopeClient) LabelNames(ctx context.Context, labelSelector string,
 		return nil, fmt.Errorf("error sending LabelNames request %v", err)
 	}
 
+	if resp.Msg.Names == nil {
```
Comment (aocenas) [inline pkg/tsdb/grafana-pyroscope-datasource/pyroscopeClient.go:259]: Making sure we send empty array instead of null from the backend.

File: public/app/plugins/datasource/grafana-pyroscope-datasource/VariableQueryEditor.tsx [hunk 2]
```diff
@@ -30,23 +30,22 @@ export function VariableQueryEditor(props: QueryEditorProps<PyroscopeDataSource,
...
+                  refId: props.query.refId,
                 });
               }
               if (value.value! === 'label') {
                 props.onChange({
-                  ...props.query,
                   type: value.value!,
-                  profileTypeId: '',
+                  refId: props.query.refId,
+                  profileTypeId: props.query.type !== 'profileType' ? props.query.profileTypeId : '',
```
Comment (aocenas) [inline public/app/plugins/datasource/grafana-pyroscope-datasource/VariableQueryEditor.tsx:41]: Making sure we keep already selected values if they make sense for the variable type

File: public/app/plugins/datasource/grafana-pyroscope-datasource/VariableQueryEditor.tsx [hunk 3]
```diff
@@ -156,3 +161,7 @@ function ProfileTypeRow(props: {
     </InlineFieldRow>
   );
 }
+
+export function getProfileTypeLabel(type: string) {
```
Comment (aocenas) [inline public/app/plugins/datasource/grafana-pyroscope-datasource/VariableQueryEditor.tsx:165]: Using the correct way to send profile type

File: public/app/plugins/datasource/grafana-pyroscope-datasource/VariableQueryEditor.tsx (hunk 2 above)
Comment (fabrizio-grafana) [reply public/app/plugins/datasource/grafana-pyroscope-datasource/VariableQueryEditor.tsx:41]: I'd add this as a code comment.

File: public/app/plugins/datasource/grafana-pyroscope-datasource/VariableQueryEditor.tsx [hunk 4]
```diff
@@ -30,23 +30,22 @@ export function VariableQueryEditor(props: QueryEditorProps<PyroscopeDataSource,
...
               }
               if (value.value! === 'labelValue') {
                 props.onChange({
-                  ...props.query,
                   type: value.value!,
-                  profileTypeId: '',
-                  labelName: '',
+                  refId: props.query.refId,
+                  profileTypeId: props.query.type !== 'profileType' ? props.query.profileTypeId : '',
                 });
```
Comment (fabrizio-grafana) [inline public/app/plugins/datasource/grafana-pyroscope-datasource/VariableQueryEditor.tsx:49]: Is this the same block above—the one for the `value.value! === 'label'` case? What about merging the two then?
```
if (value.value! === 'label' || value.value! === 'labelValue') {
  props.onChange({
    type: value.value!,
    refId: props.query.refId,
    // Make sure we keep already selected values if they make sense for the variable type
    profileTypeId: props.query.type !== 'profileType' ? props.query.profileTypeId : '',
  });
}
```

**Review by fabrizio-grafana — APPROVED** [review]
