### PR TITLE
DashList: Add tooltip for star dashboard icon

### LINKED ISSUE #72834: [Accessibility Visual Requirement] - No tooltips for starred dashboards in Dashlist component (MAS ID: 260681)
**Steps to reproduce**:
Open #Url: https://play.grafana.org/. Sign in with valid credentials. "Home" page appears. Navigate the Feature Showcase pane heading and select it. Navigate the expanded Dropdown and select the view menu item. Navigate the page "General" page which appears. Verify the issue.

**Actual Result**:
Tooltip is not defined for 'Star dashboard 1 time series graph' checkbox under 'General' screen.

**Expected Result**
 Tooltip should be defined for 'Star dashboard 1 time series graph' checkbox under 'General' screen. Tooltip should be defined as 'Star dashboard 1'. 
 
**Relevant WCAG Criteria:**
Could possibly make an argument for [3.3.2 Labels or Instructions](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.1#labels-or-instructions)?

image

**Component**
`<DashList />`

### PR DESCRIPTION
**Pull request by JoaoSilvaGrafana**
**What is this feature?**

This feature adds a tooltip to the star icon in the dashboard list so the user knows the action that will be happening.
Screenshot 2023-08-18 at 15 06 35

**Why do we need this feature?**

All icon buttons should have a tooltip describing the action.

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #72834

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/panel/dashlist/DashList.tsx [hunk 1]
```diff
@@ -240,7 +240,7 @@ function IconToggle({
   const iconPropsOverride = checked ? enabled : disabled;
   const iconProps = { ...otherProps, ...iconPropsOverride };
   const styles = useStyles2(getCheckboxStyles);
-  return (
+  const toggle = (
     <label className={styles.wrapper}>
```
Comment (ckbedwell) [inline public/app/plugins/panel/dashlist/DashList.tsx:244]: Because of the interaction of the tooltip cloning its immediate child (...and adding `tabIndex=0`) I'm finding this label is causing issues when I'm navigating with my keyboard. You stop once on the label with the tooltip, which you think is the interactive element (but doesn't do anything), then tab again to get to the checkbox.

I think if we change the implementation to a button (potentially utilizing `aria-pressed`... but maybe not - see other comment) that will address this issue. I don't think I can see any adverse affects from going input/type=checkbox to button/aria-pressed.

What do you think?

File: public/app/plugins/panel/dashlist/DashList.tsx [hunk 2]
```diff
@@ -183,7 +183,7 @@ export function DashList(props: PanelProps<Options>) {
                 {dash.folderTitle && <div className={css.dashlistFolder}>{dash.folderTitle}</div>}
               </div>
               <IconToggle
-                aria-label={`Star dashboard "${dash.title}".`}
+                aria-label={`${dash.isStarred ? 'Unstar' : 'Star'} dashboard "${dash.title}"`}
```
Comment (ckbedwell) [inline public/app/plugins/panel/dashlist/DashList.tsx:186]: So, this is a really interesting time where we want the tooltip and the aria-label to differ because the experience changes depending on if you are using assistive technology or not.

If you think for a sighted user looking at the tooltip they can clearly read what action they are about to perform and the cognitive overhead is pretty simple:
- "Star dashboard"
- "Unstar dashboard"

However, for a screen reader user it becomes more complicated when the element has state. In this case they would get presented with:

- "Unstar dashboard, ticked"
- "Star dashboard, unticked"

So it becomes more difficult to reason what will happen and for them to decipher state. MDN has a section on this  under [aria-pressed](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-pressed).

**Review by ckbedwell — CHANGES_REQUESTED** [review]
Left a few comments, got a few options of which way to go with this! I think changing the input to button is the cleanest and most consistent, what do you think? 😃

**Comment by JoaoSilvaGrafana** [comment]
Ah thanks for all the feedback @ckbedwell ! 🎉  Looking around the rest of Grafana there is another place that uses this "star" behaviour and it uses an `IconButton` with tooltip:
Screenshot 2023-08-23 at 11 04 32

That does not make use of the `aria-pressed` though and simply has the same tooltip and aria-label but with no extra information for screen readers (checked/unchecked). Do you think if we just change it to work in a similar way it would be enough or should I make the changes to just use a `button` with `aria-pressed` in the `DashList`?

**Comment by ckbedwell** [comment]
Always a pleasure to provide feedback! 😄

> Do you think if we just change it to work in a similar way it would be enough or should I make the changes to just use a button with aria-pressed in the DashList?

Yeah, I think that implementation works great as it is. They do the same thing where the label changes depending on state so in that case we don't want to use `aria-pressed`. One day we can look up if users prefer consistent text and let the state be described or they prefer having the label changed to reflect state instead. At the moment it's guesswork 😅

They do use the language 'favorite' over 'star', so worth looking at making that consistent, too.

**Comment by JoaoSilvaGrafana** [comment]
Hurray! This led to a lot of code deletion 🥳 

I have a question though, to make it consistent I changed the tooltip/aria label to say "Mark as favorite" or "Unmark as favorite", but this now no longer has the name of the dashboard that we are marking, would it be helpful to have that in the ariaLabel?

**Comment by ckbedwell** [comment]
> I have a question though, to make it consistent I changed the tooltip/aria label to say "Mark as favorite" or "Unmark as favorite", but this now no longer has the name of the dashboard that we are marking, would it be helpful to have that in the ariaLabel?

I think it is always worth trying to differentiate repeated controls like these with additional information; I've attached a screenshot at the bottom of this comment to highlight how navigating the form controls could be confusing. Without the additional information someone who is navigating via their screen reader rotor (or equivalent) can not identify which favorite button is associated with which dashboard.

It may also not be clear to a screen reader user in this case if the favorite control is to the right or left of the dashboard group. The only way they would identify it is if they remembered what the interactions were at the start and end of the list, which there is no guarantee that is how they would enter the dashlist in the first place.

Screenshot of a Grafana dashboard with a Dashlist with the Voiceover overlay rotor set on form controls. In the list of form controls there is a lot of repeated 'Unmark as favorite' options.
*Notice the repeated 'Unmark as favorite button's in the image above.*

**Comment by JoaoSilvaGrafana** [comment]
Alright I have added that, _however_, the `IconButton` doesn't allow for a different `tooltip` and `aria-label`, so they both have to include the dashboard name. Wdyt?

**Review by ckbedwell — APPROVED** [review]
> Alright I have added that, however, the IconButton doesn't allow for a different tooltip and aria-label, so they both have to include the dashboard name. Wdyt?

I think this is the best approach for now, let's go with this! 🎉 🚀 

I think it's an oversight to not allow a different aria-label and tooltip in the `IconButton` component but we can address that in a separate PR 😄
