### PR TITLE
Expressions: Fixes the issue showing expressions editor

### LINKED ISSUE #62259: SSE: Adding Expression adds empty row instead of expression
**What happened**:
Expression is missing contents when adding an expression to a dashboard:

image

**What you expected to happen**:

Expression operation dropdown (as seen in previous commit):

image

**How to reproduce it (as minimally and precisely as possible)**:

New Dashboard, Add Panel, Add expression 

**Anything else we need to know?**:

Seems to have been introduced in https://github.com/grafana/grafana/pull/61927 based on my bisect -- 9f7ddf1f0b5234a1fd82e1f92d1444f81a794e45

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

Fixes the issue showing expressions editor.

**Why do we need this feature?**

With the latest release of Grafana, we cannot create new expressions as it adds only an empty section.

**Who is this feature for?**

Anybody who uses expressions

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/62259

**Special notes for your reviewer**:
Replacing all `-100`s with `__expr__` was quite a challenge. That's why we have too many files changed. Please review thoroughly.

### CODE REVIEW

File: public/app/features/expressions/ExpressionDatasource.ts [hunk 1]
```diff
@@ -61,10 +61,9 @@ export class ExpressionDatasourceApi extends DataSourceWithBackend<ExpressionQue
 }
 
 /**
- * MATCHES a constant in DataSourceWithBackend, this should be '__expr__'
- * @deprecated
+ * MATCHES a constant in DataSourceWithBackend
  */
-export const ExpressionDatasourceUID = '-100';
+export const ExpressionDatasourceUID = '__expr__';
```
Comment (itsmylife) [inline public/app/features/expressions/ExpressionDatasource.ts:66]: I am not sure if that is the ultimate solution to the problem but that definitely solves it. Please advise if there is something better or wiser we can do.

**Review by ryantxu — APPROVED** [review]
This seems reasonable -- does the backend work if the UID is "-100" or "__expr__"?

**Comment by itsmylife** [comment]
> This seems reasonable -- does the backend work if the UID is "-100" or "**expr**"?

There are this lines https://github.com/grafana/grafana/blob/main/pkg/expr/service.go#L15-L31
That part is quite confusing

File: devenv/dev-dashboards/panel-timeseries/timeseries-stacking2.json [hunk 2]
```diff
@@ -424,7 +424,7 @@
           "stringInput": "-50,-50,-50,-50,-50,-50,-50,-50"
         },
         {
-          "alias": "-100",
+          "alias": "__expr__",
```
Comment (joshhunt) [inline devenv/dev-dashboards/panel-timeseries/timeseries-stacking2.json:427]: These changes don't look right  - cauality of find-and-replace?

Comment (itsmylife) [reply devenv/dev-dashboards/panel-timeseries/timeseries-stacking2.json:427]: I wanted to change it because of this https://github.com/grafana/grafana/blob/main/public/app/features/expressions/ExpressionDatasource.ts#L63-L67
Then failing tests led me to change all of them.

Comment (itsmylife) [reply devenv/dev-dashboards/panel-timeseries/timeseries-stacking2.json:427]: But I think this is not necessary. Since it is not related to the expressions at all.

Comment (joshhunt) [reply devenv/dev-dashboards/panel-timeseries/timeseries-stacking2.json:427]: I think in _this_ file, this is just an alias describing the metric values of `[-100,-100,-100,-100]` and not the magic value for expressions.

Comment (itsmylife) [reply devenv/dev-dashboards/panel-timeseries/timeseries-stacking2.json]: you are right. Nice catch. Reverted that part.

File: pkg/services/sqlstore/migrations/ualert/cond_trans.go [hunk 3]
```diff
@@ -187,7 +187,7 @@ func transConditions(set dashAlertSettings, orgID int64, dsUIDMap dsUIDLookup) (
 	ccAlertQuery := alertQuery{
 		RefID:         ccRefID,
 		Model:         exprModelJSON,
-		DatasourceUID: "-100",
+		DatasourceUID: "__expr__",
```
Comment (ryantxu) [inline pkg/services/sqlstore/migrations/ualert/cond_trans.go:190]: rather than using the magic string "__expr__" can we import the go constant?

This whole mess was caused by using the magic string "-100" as a uid... so we still need to make sure that continues to work when it is saved in the raw JSON models

File: public/api-merged.json [hunk 4]
```diff
@@ -15940,7 +15940,7 @@
           },
           "example": [
             {
-              "datasourceUid": "-100",
+              "datasourceUid": "__expr__",
```
Comment (ryantxu) [inline public/api-merged.json:15943]: is this file generated?

**Review by mckn — COMMENTED** [review]
I think this looks good but we should probably define the value once in a constant and reference that where it is possible.

Also - I'm missing migrations to make sure that we migrate persisted panels with the -100 value.

File: pkg/services/sqlstore/migrations/ualert/cond_trans.go (hunk 3 above)
Comment (itsmylife) [reply pkg/services/sqlstore/migrations/ualert/cond_trans.go:190]: Yes, we can and should. I will handle that part.

File: packages/grafana-runtime/src/utils/DataSourceWithBackend.ts [hunk 5]
```diff
@@ -47,7 +47,7 @@ export function isExpressionReference(ref?: DataSourceRef | string | null): bool
     return false;
   }
   const v = typeof ref === 'string' ? ref : ref.type;
-  return v === ExpressionDatasourceRef.type || v === '-100'; // -100 was a legacy accident that should be removed
```
Comment (itsmylife) [inline packages/grafana-runtime/src/utils/DataSourceWithBackend.ts:50]: I'll put this line back since we might need this.

File: pkg/expr/service.go [hunk 6]
```diff
@@ -27,8 +27,8 @@ const DatasourceID = -100
 // OldDatasourceUID is the datasource uid used in requests to identify it as an
 // expression command. It goes with the query root level datasourceUID property. It was accidentally
 // set to the Id and is now kept for backwards compatibility. The newer Datasource.UID property
-// should be used instead and should be set to "__expr__".
-const OldDatasourceUID = "-100"
```
Comment (itsmylife) [inline pkg/expr/service.go:31]: I will put this back too. And will use `DatasourceUID` where it is possible.

File: public/api-merged.json (hunk 4 above)
Comment (itsmylife) [reply public/api-merged.json:15889]: Yes it was and I regenerated it in my latest commit

**Comment by itsmylife** [comment]
> I think this looks good but we should probably define the value once in a constant and reference that where it is possible.
> 
> Also - I'm missing migrations to make sure that we migrate persisted panels with the -100 value.

Please see https://github.com/grafana/grafana/pull/62510/commits/26817f29618c4977c3f7c6dc270fccebff06523b

**Comment by gillesdemey** [comment]
I believe this one also needs to be backported to `v9.4.x`?

**Comment by itsmylife** [comment]
> I believe this one also needs to be backported to `v9.4.x`?

Yes, it should. We missed the release cut. I'll add that label too.

**Comment by itsmylife** [comment]
`v9.1.x` and `v9.0.x` do not have this bug. So I won't backport it.

**Comment by torkelo** [comment]
@itsmylife this needs manual backports for v9.0.x and 9.1.x   (Just did opened manual backports for my PR that introduced this, https://github.com/grafana/grafana/pull/62657, https://github.com/grafana/grafana/pull/62657 )

**Comment by jiaojialin** [comment]
Hello, I wonder when this fix will be released ? This bug has prevented us to upgrade to v.9.3.6 to use some other newer features. Thanks

**Comment by gtk-grafana** [comment]
@jiaojialin This PR will be released in the 9.3.7 release
