### PR TITLE
fix only users that can edit a dashboard should be able to update panel json

### LINKED ISSUE #15667: Editor downgraded to viewer should not be able to Update JSON on a panel.
Found this old issue while googling for a solution: #3874 

### What Grafana version are you using?
Version 5.4.3 (commit # 6539180 ) & 5.2.4 have been tested.

Tested in Version 6.0.0 (commit: 34a9a62). Still an issue.

### What datasource are you using?
MySQL

### What OS are you running grafana on?
Linux Kernel 3.10.0-957.1.3.el7.x86_64

### What did you do?
0. Start with Fresh Grafana Installation.
1. Create Dashboard.
2. Create Test User.
3. Giver Test User Viewer permissions on Dashboard.
4. Create Panel on Dashboard using MySQL datasource.
5. View Dashboard as Test User.
6. Open the Test Panel's Panel JSON.
7. Edit the SQL Query.
8. Click Update.

### What was the expected result?
Update on the Panel JSON should not be there and should not apply changes even if shown.

### What happened instead?
Update on the Panel JSON window was visible and updated the JSON. This allows running SQL Queries as a User with Viewer permissions.  For example, say if I would normally see my own statistics and wished to see my Supervisor's while knowing his ID in the database.

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

The attached .TXT file is a .HAR that covers the following actions:
1. Opening the Dashboard as the Test User.
2. Opening the Test Panel JSON as the Test User.
3. Updating the JSON by clicking Update after editing it, as the Test User.

It was created on version 5.4.3 in an Incognito Chrome Window. I verified that commit 14952de 's change exists within 5.2.4 and 5.4.3 in `json_editor_ctrl.ts`.

`viewers_can_edit` is set to `false` during my testing.
 
[grafana.domain.com.txt](https://github.com/grafana/grafana/files/2906709/grafana.domain.com.txt)

### PR DESCRIPTION
**Pull request by marefr**
Fixes #15667

### CODE REVIEW

File: public/app/core/controllers/json_editor_ctrl.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@ export class JsonEditorCtrl {
   /** @ngInject */
   constructor($scope) {
     $scope.json = angular.toJson($scope.model.object, true);
-    $scope.canUpdate = $scope.model.updateHandler !== void 0 && $scope.contextSrv.isEditor;
+    $scope.canUpdate = $scope.model.updateHandler !== void 0 && ($scope.model.canUpdate || false) === true;
```
Comment (xlson) [inline public/app/core/controllers/json_editor_ctrl.ts]: Probably something typescript-specific I'm missing here, but, wouldn't `$scope.model.canUpdate` be enough? Instead of the whole or false === true, I mean.

**Review by xlson — APPROVED** [review]
Looks good. Curious about the if statement.

File: public/app/core/controllers/json_editor_ctrl.ts (hunk 1 above)
Comment (torkelo) [reply public/app/core/controllers/json_editor_ctrl.ts]: yes, agree, looks a bit strange

Comment (marefr) [reply public/app/core/controllers/json_editor_ctrl.ts]: Will fix :+1:
