### PR TITLE
Fix rotation bug

### LINKED ISSUE #73021: CanCAD: Bug - height width change on rotate
When rotating an element, height and width is growing. Likely just needs to be recalculated relative to the rotation.

Image

### PR DESCRIPTION
**Pull request by drew08t**
For rotated elements, elements would grow and shift when selected. This addresses that issue for elements constrained by top, bottom, left, or right.

Known limitations: does not address center, scale, top + bottom, left + right constraints.

Aug-09-2023 21-58-31

Closes #73021, #73069

### CODE REVIEW

**Comment by drew08t** [comment]
This code breaks this fix:
`style.transformOrigin = `bottom left`;`

... in https://github.com/grafana/grafana/pull/73132

File: public/app/features/canvas/runtime/element.tsx [hunk 1]
```diff
@@ -214,21 +214,63 @@ export class ElementState implements LayerElement {
...
+          break;
+        case rotationDegrees >= 270:
+          const sinNegRad = Math.sin(-rotationRad);
+          const cosNegRad = Math.cos(-rotationRad);
+          deltaTop =
+            (this.options.placement?.width / 2) * sinNegRad + (this.options.placement.height / 2) * (cosNegRad - 1);
+          deltaLeft =
+            (this.options.placement?.height / 2) * sinNegRad + (this.options.placement.width / 2) * (cosNegRad - 1);
+          break;
+      }
```
Comment (rwwiv) [inline public/app/features/canvas/runtime/element.tsx:256]: This is awesome, what a wild fix! This should make the code a little easier to read:

```suggestion
      let radOffset = rotationRad;

      switch (true) {
        case rotationDegrees >= 0 && rotationDegrees < 90:
          // no-op
          break;
        case rotationDegrees >= 90 && rotationDegrees < 180:
          radOffset = Math.PI - rotationRad;
          break;
        case rotationDegrees >= 180 && rotationDegrees < 270:
          radOffset = Math.PI + rotationRad;
          break;
        case rotationDegrees >= 270:
          radOffset = -rotationRad;
          break;
      }
      const sinRadOffset = Math.sin(radOffset);
      const cosRadOffset = Math.cos(radOffset);

      const calcDelta = (n: number, m: number) => (n / 2) * sinRadOffset + (m / 2) * (cosRadOffset - 1);

      deltaTop = calcDelta(this.options.placement?.width, this.options.placement.height);
      deltaLeft = calcDelta(this.options.placement?.height, this.options.placement.width);
```

**Review by rwwiv — APPROVED** [review]
LGTM 🚀
