### PR TITLE
CloudMonitoring: Fix crash when inspecting data for MQL queries

### LINKED ISSUE #63744: CloudMonitoring: UI Error when Inspecting Data
**What happened**:
Inspecting data for a MQL query that contains an aggregation function causes a crash
image

**How to reproduce it (as minimally and precisely as possible)**:
1. Write a MQL query that uses an aggregation function, e.g. `fetch gce_instance::compute.googleapis.com/instance/cpu/utilization | sum`
2. Inspect data
3. Crash

**Anything else we need to know?**:
Similar to #35999

### PR DESCRIPTION
**Pull request by asimpson**
This happened for MQL queries that used an [aggregate function][1], e.g. `sum`.

[1]: https://cloud.google.com/monitoring/mql/reference#aggr-function-group

**Which issue(s) does this PR fix?**:

Fixes #63744

### CODE REVIEW

File: pkg/tsdb/cloudmonitoring/cloudmonitoring.go [hunk 1]
```diff
@@ -481,7 +481,11 @@ func calculateAlignmentPeriod(alignmentPeriod string, intervalMs int64, duration
 func formatLegendKeys(metricType string, defaultMetricName string, labels map[string]string,
 	additionalLabels map[string]string, query cloudMonitoringQueryExecutor) string {
 	if query.getAliasBy() == "" {
-		return defaultMetricName
+		if defaultMetricName != "" {
+			return defaultMetricName
+		}
+
+		return metricType
```
Comment (asimpson) [inline pkg/tsdb/cloudmonitoring/cloudmonitoring.go:488]: I'm not sure what else we could use as the label.

Comment (aangelisc) [reply pkg/tsdb/cloudmonitoring/cloudmonitoring.go:488]: This is a fine choice 😊

**Review by aangelisc — APPROVED** [review]
Great stuff @asimpson, and thanks for the test case too!
