### PR TITLE
Logs Panel: Add support for keyboard interactions with log lines

### LINKED ISSUE #46478: A11y : Cannot interact with log lines via keyboard
**Steps to reproduce**:

Can’t Focus / Interact with log lines using keyboard-only navigation

**Actual Result**:

Degraded experience - log lines cannot be expanded to check log labels and detected fields

**Expected Result**

Elements should be more accessible to users who rely on keyboard navigation

**Relevant WCAG Criteria:**

[2.1.1 Keyboard - Level A](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=335%2C332#keyboard)

**Environment**:
- Grafana version: 8.4.3
- Data source type & version:
- User OS & Browser:
- Others:

### LINKED ISSUE #46485: A11y : Cannot select Log lines via keyboard
**Steps to reproduce**:

Attempt to navigate the labels / values inside the Log Browser using keyboard-only navigation

**Actual Result**:

Log browser not usable - workaround would be to take note of labels and value and then use the text editor input

**Expected Result**

Better accessibility for keyboard-only navigators

**Relevant WCAG Criteria:**

[2.1.1 Keyboard - Level A](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=335%2C332#keyboard)

**Environment**:
- Grafana version: 8.4.3
- Data source type & version:
- User OS & Browser:
- Others:

### LINKED ISSUE #59047: A11y: Fix keyboard accessibility in `public/app/features/logs/components/LogRowMessage.tsx`
- ⏱️ temporarily enable the eslint rules `jsx-a11y/click-events-have-key-events` and `jsx-a11y/no-static-element-interactions`
  - this can be done by changing them from `"off"` to `"error"` in your `.eslintrc`
- 🔍 open the file to see where the error is (or run `yarn lint` if your editor isn't set up to show eslint errors)
- 🔧 fix the error
  - this will be heavily dependant on context
    - should you be able to interact with this element via the keyboard?
    - is there another element that already handles the same behaviour via the keyboard?
  - in some cases, the best fix is to **use the correct semantic element** for the job. if something behaves like a button but we want it to look different, we can still use the `<button type="button">` element and style it appropriately. this will handle all our keyboard accessibility needs for us. there's even a handy [`clearButtonStyles`](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Button/Button.tsx#L306) util to undo the basic button styling.
  - if using a `<button>` or other similar interactive element is not appropriate, refer to the documentation [here](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/click-events-have-key-events.md) and [here](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-static-element-interactions.md). this will likely involve setting a `role` and implementing a custom `onKeyPress`
- 🧪 test it! can you interact with this element using the keyboard now?
- 🥳 turn the rules back off and deliver a PR with the fix! 

See https://github.com/grafana/grafana/issues/58924

### PR DESCRIPTION
**Pull request by matyax**
This PR adds support to interact with log lines using the keyboard, so a user can toggle them open/closed.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/46485
Fixes https://github.com/grafana/grafana/issues/46478
Fixes https://github.com/grafana/grafana/issues/59047

**Special notes for your reviewer**:

Styles should be unchanged:

https://user-images.githubusercontent.com/1069378/208653757-8cb95a5c-dac4-41e1-8a76-52c75f6e8448.mov

Interaction demo:

https://user-images.githubusercontent.com/1069378/208653781-da18074e-c078-4fea-819d-5e75ebee23d0.mov

### CODE REVIEW

File: public/app/features/logs/components/LogRowMessage.tsx [hunk 1]
```diff
@@ -77,6 +77,15 @@ const getStyles = (theme: GrafanaTheme2, showContextButton: boolean, isInDashboa
       right: ${isInDashboard ? '40px' : `calc(75px + ${theme.spacing()} + ${showContextButton ? '80px' : '40px'})`};
       margin-top: -${theme.spacing(0.125)};
     `,
+    logLine: css`
+      background-color: transparent;
+      border: none;
+      diplay: inline;
+      font-family: ${theme.typography.fontFamilyMonospace};
+      font-size: ${theme.typography.bodySmall.fontSize};
+      letter-spacing: ${theme.typography.bodySmall.letterSpacing};
```
Comment (svennergr) [inline public/app/features/logs/components/LogRowMessage.tsx:86]: As soon as log lines are wrapping, they seem to be centered:
image

Could be fixed with:

```suggestion
      letter-spacing: ${theme.typography.bodySmall.letterSpacing};
      text-align: left;
```

**Review by svennergr — CHANGES_REQUESTED** [review]

File: public/app/features/logs/components/LogRowMessage.tsx (hunk 1 above)
Comment (matyax) [reply public/app/features/logs/components/LogRowMessage.tsx:86]: Oh, good catch!

**Review by svennergr — APPROVED** [review]
LGTM 👍
