### PR TITLE
Tempo: Represent OTLP Span Intrinsics correctly

### LINKED ISSUE #59607: TraceView: Represent OTLP Span Intrinsics correctly
**What happened**:
Currently when rendering traces from Tempo, Grafana pushes certain "intrinsic" properties on a span into attributes (or ignores them entirely). There are quite a few intrinsic properties to a span that should be considered when rendering OTLP spans, but this issue will only specifically call out two of them. Please review the [data model](https://github.com/open-telemetry/opentelemetry-proto/tree/main/opentelemetry/proto/trace/v1) for full details.

[**Status**](https://github.com/open-telemetry/opentelemetry-proto/blob/d8729d40f629dba12694b44c4c32c1eab109b00a/opentelemetry/proto/trace/v1/trace.proto#L255)

Currently when rendering a span with a status of error Grafana creates an "error" attribute with the value `true`. This should instead be displayed somehow as part of the span.
image

[**Kind**](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto#L156)

Currently when rendering a span with the kind set Grafana creates a "span.kind" attribute with a string value. This should also be displayed as an intrinsic element of the span instead of as an attribute.

image

**What you expected to happen**:
These properties are intrinsic to the span should not be rendered as attributes.

**How to reproduce it (as minimally and precisely as possible)**:
Render a trace with any of the above properties.

**Additional Context**:
Tempo uses the OTLP object model natively and currently the Grafana UI doesn't display represent that faithfully. This will be increasingly important as TraceQL rolls out. The language distinguishes between dynamic attributes and intrinsic properties of the span and we would like the Grafana view to be consistent with the object model and query language.

### PR DESCRIPTION
**Pull request by joey-grafana**
**What is this feature?**

Adds a span intrinsics section and moves all intrinsic tags to that section.

**Why do we need this feature?**

To represent OTLP Span Intrinsics correctly.

**Who is this feature for?**

Tempo users.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/59607

This also fixes a few issues not reported;
- span kind internal not in downloaded trace file
- status.code of unset is ignored in uploaded file but exists in original trace
- tagsToAttributes(span.tags) throws if span.tags is undefined and export breaks

**Special notes for your reviewer:**

Screenshot 2023-06-13 at 09 08 15

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/datasource/tempo/resultTransformer.ts [hunk 1]
```diff
@@ -161,51 +161,57 @@ function resourceToProcess(resource: collectorTypes.opentelemetryProto.resource.
...
-    if (span.status.code && (span.status.code as any) !== SpanStatusCode.UNSET) {
-      spanTags.push({
+    if (span.status.code !== undefined) {
+      intrinsics.push({
         key: 'otel.status_code',
         value: SpanStatusCode[span.status.code],
       });
       if (span.status.message) {
-        spanTags.push({ key: 'otel.status_description', value: span.status.message });
+        intrinsics.push({ key: 'otel.status_description', value: span.status.message });
```
Comment (joey-grafana) [inline public/app/plugins/datasource/tempo/resultTransformer.ts:198]: So we call these `status.code` & `status.message` in the backend but when transforming here we rename to `otel.status_code` and `otel.status_description` - not fully happy with that approach

**Review by adrapereira — DISMISSED** [review]
In order to represent the OTLP intrinsics correctly we have to make a few more changes to this PR:
1. `error = true` shouldn't be displayed in the intrinsics section because it's not a valid intrinsic attribute. It may be a part of other sections if the system has a tag called `error` but in our case I think we're adding it "manually" to denote an error, which is wrong under OTLP. 
2. `span.kind` is not a valid intrinsic. `kind` is an intrinsic though so we can show it instead
3. same for `status.code`. However `status` is a valid intrinsic
4. Please review all the comments of https://github.com/grafana/grafana/issues/59607 to make sure we're making all the necessary and accurate changes.

**Comment by aocenas** [comment]
I don't think it makes sense to hide the intrinsics as another table section. I think this comment with the image makes more sense: https://github.com/grafana/grafana/issues/59607#issuecomment-1416429862. Basically, intrinsics are well-known parts of the span that are always there while attributes is a variable length list of key-value pairs. This should be apparent from the UI and needs a different representation imho.

**Comment by joey-grafana** [comment]
Thanks for the reviews :) 

I believe we had discussed in stand up that we were first going to move the intrinsics to their own section and then modify/rename them accordingly after some more discussion. In any case, I've updated this PR and removed the intrinsics section and instead display the values in the span details along with service, duration etc. 

I've removed `error` & `span.kind` has also been updated. `status` on the other hand needs to be handled differently. We assume that `status` is either `ok`, `error` or `unset` but [OTEL specifies](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status) (+ [source](https://github.com/open-telemetry/opentelemetry-proto/blob/d8729d40f629dba12694b44c4c32c1eab109b00a/opentelemetry/proto/trace/v1/trace.proto#L260)) that `status` contains a `message` and a `code` and we also add each of these [as intrinsics](https://github.com/grafana/grafana/blob/main/pkg/tsdb/tempo/trace_transform.go#L284) on the span. The [values are represented](https://opentelemetry.io/docs/specs/otel/common/mapping-to-non-otlp/) as `otel.status_description` & `otel.status_code` (+ [source](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-go+otel.status_description&type=code)). This distinction is especially important when downloading/uploading traces.

File: public/app/plugins/datasource/tempo/resultTransformer.ts [hunk 2]
```diff
@@ -282,7 +289,8 @@ export function transformFromOTLP(
             serviceTags,
             startTime: span.startTimeUnixNano! / 1000000,
             duration: (span.endTimeUnixNano! - span.startTimeUnixNano!) / 1000000,
-            tags: getSpanTags(span, librarySpan.instrumentationLibrary),
+            tags: getSpanTags(span),
+            intrinsics: getIntrinsics(span, librarySpan.instrumentationLibrary),
```
Comment (aocenas) [inline public/app/plugins/datasource/tempo/resultTransformer.ts:293]: I feel like this is a part I am having a different view of what intrinsics are so want to align or that. What I thought intrinsic means is just intrinsic attributes of the trace or span, not a different set of tags. So for example here `duration` is also intrinsic attribute because is it part of the span type. So this to me right now feel a bit odd in the same sense as if `startTime` and `duration` were part of some `intrinsics` map with `duration` key and value instead of just part of the actual type. Then when presenting and we have to have a separate list of keys, that we have to pull out of here first and then display it feels weird but at the same time reason I suggested to put it here because I thought they are just part of the type.

Comment (joey-grafana) [reply public/app/plugins/datasource/tempo/resultTransformer.ts:293]: When you describe `duration` & `startTime` like that they do sound to be something that could go in the `intrinsics` map, however `duration` & `startTime` always exist on the span whereas not every span has the library intrinsics. Feels a bit tidier to put them in their own map in this sense. I wanted to keep them out of the tags map so we didn't have to filter when adding the tags to the UI however we could just put all of these on the span type and check if they exist before rendering in span details where they are now (next to duration, child count etc)

So to be super clear we would add the following to the span type;
```
kind: enum,
status: {
   code: number,
   message: string
},
instrumentationLibrary: {
   name: string,
   version: string 
}
```
btw have you ever seen the [trace state](https://github.com/grafana/grafana/pull/69394/files#diff-0fae7cc1f8c2a5f78b973620a1894c4a8e848581cc65e3ac2fc603b6a37fb64fL213) in a span?

Comment (aocenas) [reply public/app/plugins/datasource/tempo/resultTransformer.ts:293]: > duration & startTime always exist on the span whereas not every span has the library intrinsics.

Ah ok yeah this is probably what I wasn't clear about. But in what cases we don't have them? I would assume the library and lib-version may be only from OTEL spans but kind and status are sort of universal, aren't they?

Also it's not like we show anything as intrinsic right? Like we have a hardcoded list of things that go there so it's not dynamic like somebody could send a span with some other intrinsics right?

Comment (joey-grafana) [reply public/app/plugins/datasource/tempo/resultTransformer.ts:293]: Yes, they are so if they are set on the span they will be rendered.

That's it yeah, we have a hardcoded list of intrinsics that may vary in length depending on which exist on the span.

File: public/app/plugins/datasource/tempo/resultTransformer.ts [hunk 3]
```diff
@@ -161,51 +161,75 @@ function resourceToProcess(resource: collectorTypes.opentelemetryProto.resource.
...
+  if (span.kind) {
+    const split = span.kind.toString().toLowerCase().split('_');
+    kind = split.length ? split[split.length - 1] : span.kind.toString();
+  }
+  return kind;
+}
+
+function getStatusCode(span: collectorTypes.opentelemetryProto.trace.v1.Span) {
+  let statusCode = undefined;
+  if (span.status) {
```
Comment (aocenas) [inline public/app/plugins/datasource/tempo/resultTransformer.ts:187]: Do we need these accessors here? Seems like they could be replaced by just using `?` operator like here `span.status?.code`?

**Review by aocenas — APPROVED** [review]
Small comment about the accessor functions but otherwise look good.

**Review by aocenas — APPROVED** [review]
