### PR TITLE
Graphite: Use TimeRange with applied fiscalYearStartMonth

### LINKED ISSUE #50153: fiscal year selection does not update legend data
**What happened**:
when defining a custom fiscal year range and selecting a fiscal year timeframe, the legend values are still shown for the year and not fiscal year

**What you expected to happen**:
the legend values should update for the specified time range, in our case a custom fiscal year data definition.

**How to reproduce it (as minimally and precisely as possible)**:
go to
https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&from=now%2Ffy&to=now%2Ffy&editPanel=3
define the fiscal year starting april
add total for the legend values
image

select "this fiscal year" (01.04.2022 to 31.03.2023) to view the desired time range for that specific graph, the total numbers in the legend is 51k

try another selection for the current year(01.01.2022 to 31.12.2023), the total value on the legend is still 51k although the timeframe is completely different.
image

### PR DESCRIPTION
**Pull request by mdvictor**
**What this PR does / why we need it**:
Fixes an issue where the Graphite DS does not take into account the set fiscal year start month and returns erroneous data.

**Which issue(s) this PR fixes**:

Fixes #50153

### CODE REVIEW

File: public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx [hunk 1]
```diff
@@ -52,6 +52,8 @@ export const TimeSeriesPanel: React.FC<TimeSeriesPanelProps> = ({
 
   const enableAnnotationCreation = Boolean(canAddAnnotations && canAddAnnotations());
 
+  console.log(options.legend);
+
```
Comment (dprokop) [inline public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx:56]:
```suggestion
```

image

File: public/app/features/query/state/PanelQueryRunner.ts [hunk 2]
```diff
@@ -225,6 +227,7 @@ export class PanelQueryRunner {
       dashboardId,
       publicDashboardAccessToken,
       range: timeRange,
+      fiscalYearStartMonth,
```
Comment (dprokop) [inline public/app/features/query/state/PanelQueryRunner.ts:230]: Not sure about the changes in the PanelQueryRunner. There's a lot of fiscalYearStartMonth option drilling. Maybe instead we can make sure that the time range passed to PanelQueryRunner.run method has already a time range with the fiscal year applied? This way we wouldn't really need to wory about this kind of bugs in other datasources.

Comment (mdvictor) [reply public/app/features/query/state/PanelQueryRunner.ts:230]: The time ranges themselves seem to be calculated before and passed correctly to graphite, but when the query is ran it uses the `raw` values instead of the precalculated dates here: https://github.com/grafana/grafana/pull/51623/files#diff-c27e82d1dbdf51beeab4bc60a1546fce8a7ffec7a7905f78f4fee06375ab05cbR182

I'm not sure why exactly this is done and why we don't just use `options.range.from`

**Comment by mdvictor** [comment]
I think that the modification should be applied everywhere where the `translateTime` function is called in the datasource. I'm going to test it out and see.

File: public/app/features/query/state/PanelQueryRunner.ts (hunk 2 above)
Comment (dprokop) [reply public/app/features/query/state/PanelQueryRunner.ts]: I guess this is some old code that we are looking at here. I would ping @grafana/observability-metrics for some help with landing this PR.

**Review by bohandley — APPROVED** [review]
Looks good to me, I tested it locally wasn't able to find any issues. Thank you!
