### PR TITLE
JWT: Find login and email claims with JMESPATH

### LINKED ISSUE #69451: [Auth - JWT]: `username/email_claim` don't support array values
### 
# What went wrong?

I'm trying to use [JWT authentication](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/jwt/#configure-jwt-authentication) for an embedded iframe. The JWT token in question is provided by Azure AD B2C, which unfortunately isn't entirely standard compliant (surprise) and instead of containing an `email` claim, holds a string array `emails`.

For generic OAuth you support [`email_attribute_path`](https://github.com/grafana/grafana/blob/e789c2bf03f33569dab4be3b9882f3d5b11f87c9/pkg/login/social/generic_oauth.go#L323-L330C3), which allows for selecting the first element of the array by using: `emails[0]`. Would it be possible to extend `email/username_claim` to support such paths as well?

Either by keeping the same set of properties, but accepting more kinds of input, or by adding explicit properties `email/username_claim_path`.

I'm thinking something along the lines of replacing:

```go
if key := h.Cfg.JWTAuthUsernameClaim; key != "" {
    query.Login, _ = claims[key].(string)
    extUser.Login, _ = claims[key].(string)
}
```

with

```go
if key := h.Cfg.JWTAuthEmailClaim; key != "" {
    email := s.searchJSONForStringAttr(key, json.Marshal(claims)).(string)
    query.Email, _ = email
    extUser.Email, _ = email
}
```

and the same for `JWTAuthUsernameClaim`. With added error handling, of course. I realize [`searchJSONForStringAttr()`](https://github.com/grafana/grafana/blob/e789c2bf03f33569dab4be3b9882f3d5b11f87c9/pkg/login/social/common.go#L96) isn't available in the given scope, but you get the gist of it, I hope.

Thoughts?

### 
# How do we reproduce it?

There's really not much to test/reproduce here, I think you can quite easily verify the behavior by just looking at the relevant code.

### 
# What Grafana version are you using?

v9.5.1

### 
### Is the bug inside a Dashboard Panel?

No

### Grafana Platform?

Docker

### User's OS?

macOS Ventura 13.3.1

### User's Browser?

N/A

### Is this a Regression?

No

### Are Datasources involved?

No

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by linoman**
**What is this feature?**

This feature will resolve login/username and email claims using JMESPath. This will allow us to use `rootClaim.subClaim.listOfEmails[0]`.

**Why do we need this feature?**

This has been requested in the [past](https://github.com/grafana/grafana/issues/69451). However, this won't solve the issue for Google's JWT subclaim `gcip` since that needs to be parsed again.

https://github.com/grafana/grafana/issues/75856

**Who is this feature for?**

IAM

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/69451

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/services/auth/jwt/auth.go [hunk 1]
```diff
@@ -118,3 +120,17 @@ func HasSubClaim(jwtToken string) bool {
 
 	return claims.Subject != ""
 }
+
+func FindSubClaims(subclaim string, jsonMap any) (string, error) {
```
Comment (mgyongyosi) [inline pkg/services/auth/jwt/auth.go:124]: I think it's better to use the same function that is used by the other providers: https://github.com/grafana/grafana/blob/c6a489cfd891387a65210a903e8cd652ac56974d/pkg/util/json.go#L59.

File: pkg/services/authn/clients/jwt.go [hunk 2]
```diff
@@ -75,13 +76,24 @@ func (s *JWT) Authenticate(ctx context.Context, r *authn.Request) (*authn.Identi
...
 		}}
 
+	serializedClaims, _ := json.Marshal(&claims)
+	var data map[string]interface{}
+	_ = json.Unmarshal(serializedClaims, &data)
+
 	if key := s.cfg.JWTAuth.UsernameClaim; key != "" {
 		id.Login, _ = claims[key].(string)
 		id.ClientParams.LookUpParams.Login = &id.Login
+	} else if key := s.cfg.JWTAuth.NameAttributePath; key != "" {
```
Comment (mgyongyosi) [inline pkg/services/authn/clients/jwt.go:86]: Please rename `NameAttributePath` to `UsernameAttributePath` to match with the naming of the `UsernameClaim`.

File: pkg/services/auth/jwt/auth.go (hunk 1 above)
Comment (linoman) [reply pkg/services/auth/jwt/auth.go]: I removed this function and replaced its uses with `SearchJSONForStringAttr`.

File: pkg/services/authn/clients/jwt.go (hunk 2 above)
Comment (linoman) [reply pkg/services/authn/clients/jwt.go]: No problem. I was using these [names](https://github.com/grafana/grafana/issues/75856#issuecomment-1992244516) as a reference.

File: pkg/services/authn/clients/jwt.go [hunk 3]
```diff
@@ -75,13 +76,24 @@ func (s *JWT) Authenticate(ctx context.Context, r *authn.Request) (*authn.Identi
 			SyncTeams:       s.cfg.JWTAuth.GroupsAttributePath != "",
 		}}
 
+	serializedClaims, _ := json.Marshal(&claims)
```
Comment (mgyongyosi) [inline pkg/services/authn/clients/jwt.go:79]: Instead of marshaling/unmarshaling you can use `map[string]any(claims)` in the code. 
Example:
```
id.Email, _ = util.SearchJSONForStringAttr(s.cfg.JWTAuth.EmailAttributePath, map[string]any(claims))
```
Because `claims`'s type is `JWTClaims` which is a "redefinition of `DynMap` -> `map[string]any`, so because of this the underlying jmespath lib cannot work without the type conversion to `map[string]any`, because it checks for `map[string]any`, but it receives `JWTClaims`.

I don't think the custom type definitions (without any functions attached to those) provides any benefit here. So we could remove `JWTClaims` and use `map[string]any` instead to make the code simpler. @kalleep wdyt?

Comment (kalleep) [reply pkg/services/authn/clients/jwt.go:79]: Yeah I think it makes sense, either solution would work but I think I would prefer to remove the custom definition `JwtClaims` and just return map[string]any for the reasons @mgyongyosi stated

Comment (linoman) [reply pkg/services/authn/clients/jwt.go]: As suggested, I have replaced `JWTClaims` with `map[string]any` and removed the conversation of claims to map. Looks much cleaner!

File: pkg/services/authn/clients/jwt.go [hunk 4]
```diff
@@ -78,10 +78,17 @@ func (s *JWT) Authenticate(ctx context.Context, r *authn.Request) (*authn.Identi
 	if key := s.cfg.JWTAuth.UsernameClaim; key != "" {
 		id.Login, _ = claims[key].(string)
 		id.ClientParams.LookUpParams.Login = &id.Login
+	} else if key := s.cfg.JWTAuth.UsernameAttributePath; key != "" {
+		id.Login, _ = util.SearchJSONForStringAttr(s.cfg.JWTAuth.UsernameAttributePath, claims)
```
Comment (kalleep) [inline pkg/services/authn/clients/jwt.go:82]: We need to handle potential errors for both of these

Comment (linoman) [reply pkg/services/authn/clients/jwt.go:82]: I intentionally didn't handle the errors similar to what was already being done 3 lines before.
```
id.Login, _ = claims[key].(string)
```

They don't handle the errors because the identity validation expects username and email to be set.


If we handle errors for these 2, we might as well handle the errors for the other 2. WDYT @kalleep ?

Comment (mgyongyosi) [reply pkg/services/authn/clients/jwt.go:82]: @linoman The emptiness of `id.Login` and `id.Email` is checked at the end of this function: 
https://github.com/grafana/grafana/blob/29c76b98d4901a7979edab3b9267c870109b6c34/pkg/services/authn/clients/jwt.go#L120-L123

However, I think we should still check/log and return the errors here (for example when the JMESPath is incorrect) as Kalle said.

**Review by kalleep — APPROVED** [review]

**Review by mgyongyosi — APPROVED** [review]
