### PR TITLE
Variables: Fix so queryparam option works for scoped variables

### LINKED ISSUE #42694: Data links from panels in repeated rows don't populate the row variable correctly
**What you expected to happen**:

We have a fairly common drill-down use case: a summary dashboard has a multi-valued template variable `cluster` and a single row of panels, where that row repeats for each value of the variable. A separate details dashboard accepts a single value for `cluster` and has many detailed panels based on that template variable.

On the panels of the summary dashboard, we'd like to embed a link to the details dashboard:

```https://grafana/d/some_id/details_dash?${cluster:queryparam}```

That way, a user inspecting the summary dashboard for all clusters could click through a particular cluster's summary panel directly to the details dashboard for that cluster. For an instance of the repeated row where `cluster` has value `my-cluster-1`, we'd expect the panel link on that row to be populated like:

```https://grafana/d/some_id/details_dash?var-cluster=my-cluster-1```

**What happened**:

- When we select `cluster: All` on the summary dash, all values for `cluster` are selected and we get a row for each value, but the panel link is populated as `https://grafana/d/some_id/details_dash?var-cluster=All`.
- When we select multiple individual values for `cluster` on the summary dash, we get the correct behavior of a row for each value, but the panel link is populated as `https://grafana/d/some_id/details_dash?var-cluster=my-cluster-1&var-cluster=my-cluster-2&var-cluster=my-cluster-3&...`

**Anything else we need to know?**:

It looks like this may be a recurrence of a previous bug:

#22286 and #25881 fixed in #26147 and flagged for cherry-pick in #26238
#29942 fixed in #29757
#32904 incorrectly flagged as a help question
https://community.grafana.com/t/current-value-of-a-repeat-variable-in-a-repeating-panel/10080
https://community.grafana.com/t/getting-single-variable-from-repeated-row/12920
https://community.grafana.com/t/templated-panels-and-linking-to-dashboard/14197
https://community.grafana.com/t/link-on-table-plugin-within-repeatable-row/37343

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a "details" dashboard that takes a `cluster` template variable, only allowing one value to be selected. The details dash doesn't need any panels. Copy its URL.
2. Create a "summary" dashboard with a single multi-value variable also named `cluster` (e.g. different Prometheus data sources). Check "Multi-Value" and "Include All option" on the dashboard settings Variable screen.
3. Add a row with a single panel to the "summary" dash. Under the panel settings, add a panel link pointing to the "details" dash with `?${cluster:queryparam}` on the end.
4. Under row settings choose "Repeat for: `cluster`".
5. Select `cluster` All, click the panel link, and see that it passes `?var-cluster=All`.
6. Select two or more explicit values for `cluster`, click the panel link, and see that it passes all values.

**Environment**:
- Grafana version: v8.2.5 (b57a137acd)
- Data source type & version: Prometheus 2.28.1
- OS Grafana is installed on: Alpine Linux
- User OS & Browser: MacOS 11.6.1, Firefox 95.0b12
- Grafana plugins: n/a, core only

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR fixes so the `${var:queryparam}` works in a scoped setting. Not sure this is a good approach, feels a bit hacky. Is there a better way @torkelo?

**Which issue(s) this PR fixes**:
Fixes #42694

**Special notes for your reviewer**:

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
@hugohaggmark not sure I understand, why does the formatters and formatValue function care about if the value is scoped or not?

**Comment by hugohaggmark** [comment]
> @hugohaggmark not sure I understand, why does the formatters and formatValue function care about if the value is scoped or not?

That is the hack I came up with. Because for `queryparam` option it means different things depending if it's used in a scoped setting or not. Is there another way to solve this?

File: public/app/features/templating/formatRegistry.ts [hunk 1]
```diff
@@ -244,7 +245,13 @@ export const formatRegistry = new Registry<FormatRegistryItem>(() => {
       description:
         'Format variables as URL parameters. Example in multi-variable scenario A + B + C => var-foo=A&var-foo=B&var-foo=C.',
       formatter: (options, variable) => {
+        const { isScoped, value } = options;
         const { name, type } = variable;
+
+        if (isScoped) {
+          return formatQueryParameter(name, value);
+        }
+
```
Comment (torkelo) [inline public/app/features/templating/formatRegistry.ts:254]: This is confusing, why would we care about if the value is scoped or not here? I do not understand this formatter, the formatter options parameter has a value property, why is this formatter not using that?

Comment (hugohaggmark) [reply public/app/features/templating/formatRegistry.ts:254]: I understand its confusing, this is a special formatter because when it's not used outside a scope setting then you want it to resolve all the values (for a multivalued variable), i.e. var1=value1&var1=value2 but in a scoped setting you want it to resolve to var1=value1.

Comment (hugohaggmark) [reply public/app/features/templating/formatRegistry.ts:254]: An alternative would be to make sure to set the "correct" value for non scoped vars for this specific formatter here https://github.com/grafana/grafana/blob/8722c19cc396e49ab2da8142594d9bdbb8bd10af/public/app/features/templating/template_srv.ts#L297. Maybe that is a better approach?

Comment (torkelo) [reply public/app/features/templating/formatRegistry.ts:254]: > Itss is a special formatter because when it's not used outside a scope setting then you want it to resolve all the values 

But that is true for all formatters, so not sure how that makes this special. The only thing special with this formatter is that it needs to know the name of the variable not just the value

The multi value is passed via options.value, so as long as this formatter always takes the value from there it should work for both scoped and non scoped uses

Comment (hugohaggmark) [reply public/app/features/templating/formatRegistry.ts]: Thanks for the feedback, I've updated the code.

**Review by torkelo — APPROVED** [review]

**Review by kaydelaney — APPROVED** [review]
