### PR TITLE
GraphPanel: Panel Description box does not expand to fit markdown table

### LINKED ISSUE #53725: Panel Description box does not expand to fit markdown table
**What happened**:
Panel Descriptions support Markdown formatting. Making a table that is too wide for the panel does not adjust it's size to fit the content.
The Table section spreads outside the tooltip and can be difficult to read.

**What you expected to happen**:

- a) The panel should expand in width to contain its content if there is enough space.

- b) If there is not enough space (Browser Windows size or whatever) or a reasonable max width is reached, switch to having a scroll bar (or otherwise handle the large table).

**How to reproduce it (as minimally and precisely as possible)**:

- Edit any panel, e.g. https://play.grafana.org/d/3SWXxreWk/grafana-dashboard?orgId=1&editPanel=4

- Add Description text containing table markdown code, e.g.:
```
| Correct | Horse | Staple | Butter | Mint | Bus | Bread | Elephant| Extremity| Problematic | Incomplete|
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| |
|Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |
```

- Result
image
Here the table escapes the description box. (Firefox)

image
Here a panel on the right side of the dashboard has the description cut off. (Firefox)

image
Here is the same issue duplicated in Chrome.

**Anything else we need to know?**:
This issue is similar to [Issue #29239](https://github.com/grafana/grafana/issues/29239) which has been fixed.

**Environment**:
- Grafana version: `Grafana v9.0.7 (eed942a50)`
- Data source type & version: 
- OS Grafana is installed on: 
- User OS & Browser: Windows 10 21H1, Firefox 103.0.2 (64-bit), Chrome Version 104.0.5112.81 (Official Build) (64-bit)

- Grafana plugins: 
- Others:

### PR DESCRIPTION
**Pull request by gitstart**
**What this PR does / why we need it**:
Add X scroll bar to solve extrapolate problem

**Which issue(s) this PR fixes**:

Fixes #53725 

Demo
https://www.loom.com/share/d6c7500ee2784120abedd08f1e0b833b

**Special notes for your reviewer**:

### CODE REVIEW

File: packages/grafana-ui/src/components/Tooltip/Tooltip.tsx [hunk 1]
```diff
@@ -78,6 +78,10 @@ function getStyles(theme: GrafanaTheme2) {
         pointer-events: none;
       }
 
+      &[data-popper-interactive='true'] {
+        overflow-x: scroll;
```
Comment (axelavargas) [inline packages/grafana-ui/src/components/Tooltip/Tooltip.tsx:82]:
```suggestion
        overflow: auto;
```

Great work 👏🏾 , I think we could prevent showing the scroll when we don't need it :)

File: packages/grafana-ui/src/components/Tooltip/Tooltip.tsx [hunk 2]
```diff
@@ -78,6 +78,10 @@ function getStyles(theme: GrafanaTheme2) {
         pointer-events: none;
       }
 
+      &[data-popper-interactive='true'] {
```
Comment (ivanortegaalba) [inline packages/grafana-ui/src/components/Tooltip/Tooltip.tsx:81]: If we target the tooltip, this will affect every tooltip in Grafana. The tooltip by default doesn't have any width constraint, so I'd suggest adding this property where the constraint is. In this case [in the panel description component](https://github.com/grafana/grafana/blob/32a26d87a47c1b6fe408310297d272ca3ad67e1b/public/sass/components/_panel_header.scss#L120-L121).

**Review by ivanortegaalba — CHANGES_REQUESTED** [review]
Thank you so much for the PR 🙏  

I added a suggestion, please let me know if you need any clarification 😄

**Comment by gitstart** [comment]
@ivanortegaalba Requested changes added. Please take a look

**Review by ivanortegaalba — APPROVED** [review]
Thanks for applying the changes. Everything looks good to me now. Thank you so much! 🙏 

|Y overflow| X overflow|
|-|-|
|Captura de Pantalla 2022-09-05 a las 17 32 57||
