### PR TITLE
DataSourceProxy: Fix url validation error handling

### LINKED ISSUE #73032: Inappropriate HTTP response code-Failed creating data source proxy
### What happened?

Inappropriate 500 status code for Failed creating data source proxy
| path      | msg | error| current status|
| ----------- | ----------- | ----------- | ----------- |
| /api/alertmanager/OIb2JuqVk/api/v2/     /api/alertmanager/OIb2JuqVk/config/api/v1/alerts | Failed creating data source proxy       | validation of data source URL "" failed: empty URL string| 500  |

### What did you expect to happen?

Based on the error messages, it appears that all the failed requests were caused by uer errors. Therefore, we should anticipate the appropriate status code to be returned, rather than a generic 500 Internal Server.

### Did this work before?

no

### How do we reproduce it?

see above.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 9.5.6

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by ricci2511**
**What is this feature?**

Fixes error handling during url validation in data source proxy service.

**Why do we need this feature?**

Without this fix even if url validation fails it will fall into the else case and return a generic 500 status code, even though a 400 status code is expected.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #73032

**Special notes for your reviewer:**

Another way of fixing this would be by adding the `Is` method in `pkg/api/datasource/validation.go`.
Also let me know if I should add any tests. I'm not sure if I should add any to `datasourceproxy.go` or create a test file for `validation.go`.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by wbrowne — COMMENTED** [review]
Hey @ricci2511 - thanks your contribution to Grafana!

I think this is fine in its current state - would only suggest to add a test if possible. [This test](https://github.com/grafana/grafana/blob/main/pkg/api/pluginproxy/ds_proxy_test.go#L874) should provide some groundwork for stubbing out what you need. Let us know if you need any support 😄

**Comment by ricci2511** [comment]
@wbrowne Sure thing! 

Thanks for the linked unit test, so I guess adding `assert.ErrorAs(t, err, &datasource.URLValidationError{})` in the else block of `tc.err == nil` check should be enough?

**Comment by wbrowne** [comment]
> @wbrowne Sure thing!
> 
> Thanks for the linked unit test, so I guess adding `assert.ErrorAs(t, err, &datasource.URLValidationError{})` in the else block of `tc.err == nil` check should be enough?

I think it would be good to test the actual logic of where the error check is done. I was thinking of something like so (as part of `datasourceproxy_test.go`):

```go
func TestDataSourceProxyService_proxyDatasourceRequest(t *testing.T) {
	responseRecorder := httptest.NewRecorder()
	c := &contextmodel.ReqContext{
		Context: &web.Context{
			Req:  &http.Request{URL: &url.URL{}},
			Resp: web.NewResponseWriter("GET", responseRecorder),
		},
		Logger: log.NewNopLogger(),
	}

	tcs := []struct {
		name  string
		dsURL string
	}{
		{
			name:  "Empty datasource URL will return a HTTP 400",
			dsURL: "",
		},
	}
	for _, tc := range tcs {
		t.Run(tc.name, func(t *testing.T) {
			pluginID := datasources.DS_PROMETHEUS

			pluginStore := &fakes.FakePluginStore{PluginList: []plugins.PluginDTO{
				{JSONData: plugins.JSONData{ID: pluginID}},
			}}

			p := DataSourceProxyService{
				PluginRequestValidator: &fakePluginRequestValidator{},
				pluginStore:            pluginStore,
			}

			p.proxyDatasourceRequest(c, &datasources.DataSource{
				Type: pluginID,
				URL:  tc.dsURL,
			})

			resp := responseRecorder.Result()
			body := resp.Body
			defer func() {
				require.NoError(t, body.Close())
			}()

			b, err := io.ReadAll(body)
			require.NoError(t, err)

			var jsonBody = make(map[string]interface{})
			err = json.Unmarshal(b, &jsonBody)
			require.NoError(t, err)

			require.Equal(t, http.StatusBadRequest, resp.StatusCode)
			require.Equal(t, "Failed creating data source proxy", jsonBody["message"])
			require.Equal(t, "validation of data source URL \"\" failed: empty URL string", jsonBody["error"])
		})
	}
}

type fakePluginRequestValidator struct{}

func (rv *fakePluginRequestValidator) Validate(_ string, _ *http.Request) error {
	return nil
}
```

WDYT?

**Comment by ricci2511** [comment]
Alright, I understand. I'll take a better look later today, or tomorrow once I have time and add a test.

Thanks for the clarification!

**Comment by ricci2511** [comment]
Your suggested test LGTM, should I add another test case for an invalid `dsURL`? Some test code would need to be adjusted, for example:

```go
func TestDatasourceProxy_proxyDatasourceRequest(t *testing.T) {
	tcs := []struct {
		name  string
		dsURL string
	}{
		{
			name:  "Empty datasource URL will return a 400 HTTP status code",
			dsURL: "",
		},
		{
			name:  "Invalid datasource URL will return a 400 HTTP status code",
			dsURL: "://host/path", // missing protocol scheme
		},
	}
	for _, tc := range tcs {
		t.Run(tc.name, func(t *testing.T) {
			pluginID := datasources.DS_PROMETHEUS

			pluginStore := &fakes.FakePluginStore{PluginList: []plugins.PluginDTO{
				{JSONData: plugins.JSONData{ID: pluginID}},
			}}

			p := DataSourceProxyService{
				PluginRequestValidator: &fakePluginRequestValidator{},
				pluginStore:            pluginStore,
			}

			responseRecorder := httptest.NewRecorder()
			c := &contextmodel.ReqContext{
				Context: &web.Context{
					Req:  &http.Request{URL: &url.URL{}},
					Resp: web.NewResponseWriter("GET", responseRecorder),
				},
				Logger: log.NewNopLogger(),
			}

			p.proxyDatasourceRequest(c, &datasources.DataSource{
				Type: pluginID,
				URL:  tc.dsURL,
			})

			resp := responseRecorder.Result()
			body := resp.Body
			defer func() {
				require.NoError(t, body.Close())
			}()

			b, err := io.ReadAll(body)
			require.NoError(t, err)

			jsonBody := make(map[string]string)
			err = json.Unmarshal(b, &jsonBody)
			require.NoError(t, err)

			require.Equal(t, http.StatusBadRequest, resp.StatusCode)
			require.Equal(t, fmt.Sprintf("Invalid data source URL: %q", tc.dsURL), jsonBody["message"])

			switch dsURL := tc.dsURL; {
			case dsURL == "":
				require.Equal(t, "validation of data source URL \"\" failed: empty URL string", jsonBody["error"])
			case dsURL == "://host/path":
				require.Equal(t, fmt.Sprintf("validation of data source URL %q failed: parse \"%s\": missing protocol scheme", dsURL, dsURL), jsonBody["error"])
			}
		})
	}
}
```

I guess the test set up could be abstracted to its own helper if you prefer it that way and plan to reuse it on some other unit tests.

**Comment by wbrowne** [comment]
> Your suggested test LGTM, should I add another test case for an invalid `dsURL`? Some test code would need to be adjusted, for example:
> 
> ```go
> func TestDatasourceProxy_proxyDatasourceRequest(t *testing.T) {
> 	tcs := []struct {
> 		name  string
> 		dsURL string
> 	}{
> 		{
> 			name:  "Empty datasource URL will return a 400 HTTP status code",
> 			dsURL: "",
> 		},
> 		{
> 			name:  "Invalid datasource URL will return a 400 HTTP status code",
> 			dsURL: "://host/path", // missing protocol scheme
> 		},
> 	}
> 	for _, tc := range tcs {
> 		t.Run(tc.name, func(t *testing.T) {
> 			pluginID := datasources.DS_PROMETHEUS
> 
> 			pluginStore := &fakes.FakePluginStore{PluginList: []plugins.PluginDTO{
> 				{JSONData: plugins.JSONData{ID: pluginID}},
> 			}}
> 
> 			p := DataSourceProxyService{
> 				PluginRequestValidator: &fakePluginRequestValidator{},
> 				pluginStore:            pluginStore,
> 			}
> 
> 			responseRecorder := httptest.NewRecorder()
> 			c := &contextmodel.ReqContext{
> 				Context: &web.Context{
> 					Req:  &http.Request{URL: &url.URL{}},
> 					Resp: web.NewResponseWriter("GET", responseRecorder),
> 				},
> 				Logger: log.NewNopLogger(),
> 			}
> 
> 			p.proxyDatasourceRequest(c, &datasources.DataSource{
> 				Type: pluginID,
> 				URL:  tc.dsURL,
> 			})
> 
> 			resp := responseRecorder.Result()
> 			body := resp.Body
> 			defer func() {
> 				require.NoError(t, body.Close())
> 			}()
> 
> 			b, err := io.ReadAll(body)
> 			require.NoError(t, err)
> 
> 			jsonBody := make(map[string]string)
> 			err = json.Unmarshal(b, &jsonBody)
> 			require.NoError(t, err)
> 
> 			require.Equal(t, http.StatusBadRequest, resp.StatusCode)
> 			require.Equal(t, fmt.Sprintf("Invalid data source URL: %q", tc.dsURL), jsonBody["message"])
> 
> 			switch dsURL := tc.dsURL; {
> 			case dsURL == "":
> 				require.Equal(t, "validation of data source URL \"\" failed: empty URL string", jsonBody["error"])
> 			case dsURL == "://host/path":
> 				require.Equal(t, fmt.Sprintf("validation of data source URL %q failed: parse \"%s\": missing protocol scheme", dsURL, dsURL), jsonBody["error"])
> 			}
> 		})
> 	}
> }
> ```
> 
> I guess the test set up could be abstracted to its own helper if you prefer it that way and plan to reuse it on some other unit tests.

You should add a field for the expected `error` field in the JSON response so that you don't have to add the switch statement. Something that will allow you to do:

```go
require.Equal(t, tc.expectedRespErrorField, jsonBody["error"])
```

That way it should be trivial to add a new case. LMK if that makes sense!

**Comment by ricci2511** [comment]
Just saw that there seems to be a lint error which says "response body must be closed". I guess it might be a false positive since it's actually being closed:

```go
defer func() {
    require.NoError(t, body.Close())
}() 
```

Maybe by removing the `body` variable and directly using `resp.Body` it would go away?

File: pkg/services/datasourceproxy/datasourceproxy_test.go [hunk 1]
```diff
@@ -52,3 +65,74 @@ func TestDataProxy(t *testing.T) {
...
+
+			p.proxyDatasourceRequest(c, &datasources.DataSource{
+				Type: pluginID,
+				URL:  tc.dsURL,
+			})
+
+			resp := responseRecorder.Result()
+			body := resp.Body
+			defer func() {
+				require.NoError(t, body.Close())
```
Comment (wbrowne) [inline pkg/services/datasourceproxy/datasourceproxy_test.go:117]: To fix the lint error you could do:

```go
resp := responseRecorder.Result()
body := resp.Body

b, err := io.ReadAll(body)
require.NoError(t, err)
require.NoError(t, body.Close())
```

**Comment by taleena** [comment]
Hello! I saw this had the no-backport tag - given that this was found on 9, is there something preventing this from being backported to last-latest?

**Comment by wbrowne** [comment]
> Hello! I saw this had the no-backport tag - given that this was found on 9, is there something preventing this from being backported to last-latest?

Nope - we can backport to 10.1.x @taleena in that case!

**Comment by taleena** [comment]
Thank you so much, I've removed the no-backport tag. 🎉

**Review by wbrowne — APPROVED** [review]

**Review by marefr — APPROVED** [review]
LGTM

**Comment by taleena** [comment]
And whoops, sorry, since it was found in 9, I also meant backport to 9.5.x - have added that label - please let me know if there is a problem with that one. 😎

**Comment by wbrowne** [comment]
Thanks a lot for your contribution @ricci2511! 🎉
