### PR TITLE
Command Palette: don't register dashboards as actions in the command palette

### LINKED ISSUE #61093: Bug: Long dashboard names cause the command palette to crash

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- stops registering searched dashboards as actions in the command palette, instead just concats them to the other actions + passes them to `KBarResults`

**Why do we need this feature?**

- there's no need for kbar to look at the returned dashboard search terms... we've already searched+matched+ranked in our backend

**Who is this feature for?**

- everyone!

**Which issue(s) does this PR fix?**:

For #61093 

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/commandPalette/CommandPalette.tsx [hunk 1]
```diff
@@ -66,14 +77,20 @@ export const CommandPalette = () => {
...
-const RenderResults = () => {
+interface RenderResultsProps {
+  dashboardResults: ActionImpl[];
+}
+
+const RenderResults = ({ dashboardResults }: RenderResultsProps) => {
   const { results, rootActionId } = useMatches();
   const styles = useStyles2(getSearchStyles);
+  const dashboardsSectionTitle = t('command-palette.section.dashboard-search-results', 'Dashboards');
+  const dashboards = dashboardResults.length > 0 ? [dashboardsSectionTitle, ...dashboardResults] : [];
```
Comment (joshhunt) [inline public/app/features/commandPalette/CommandPalette.tsx:88]: useMemo this

File: public/app/features/commandPalette/CommandPalette.tsx [hunk 2]
```diff
@@ -66,14 +77,20 @@ export const CommandPalette = () => {
...
 
   return (
     <div className={styles.resultsContainer}>
       <KBarResults
-        items={results}
+        items={[...results, ...dashboards]}
```
Comment (joshhunt) [inline public/app/features/commandPalette/CommandPalette.tsx:93]: useMemo, can probably happen in the same as the above

File: public/app/features/commandPalette/actions/dashboardActions.ts [hunk 3]
```diff
@@ -42,7 +44,7 @@ export async function getRecentDashboardActions(): Promise<CommandPaletteAction[
   return recentDashboardActions;
 }
 
-export async function getDashboardSearchResultActions(searchQuery: string): Promise<CommandPaletteAction[]> {
+export async function getDashboardSearchResultActions(searchQuery: string): Promise<ActionImpl[]> {
```
Comment (joshhunt) [inline public/app/features/commandPalette/actions/dashboardActions.ts:47]: I think this should still continue to return `CommandPaletteAction`, and we can map it to `ActionImpl` inside of `RenderResults`

**Review by joshhunt — COMMENTED** [review]
just a few nits, but i haven't tested this yet

File: public/app/features/commandPalette/CommandPalette.tsx (hunk 2 above)
Comment (joshhunt) [reply public/app/features/commandPalette/CommandPalette.tsx:93]: I don't know whether it's definitely happening here, but changing the identity of an array that's rendered using a virtualised list can cause it to reset scroll position on every render, which is less than ideal!

File: public/app/features/commandPalette/actions/useDashboardResults.ts [hunk 4]
```diff
@@ -0,0 +1,23 @@
+import debounce from 'debounce-promise';
+import { useEffect, useState } from 'react';
+
+import { CommandPaletteAction } from '../types';
+
+import { getDashboardSearchResultActions } from './dashboardActions';
+
+const debouncedDashboardSearch = debounce(getDashboardSearchResultActions, 200);
+
+export const useDashboardResults = (searchQuery: string, isShowing: boolean) => {
```
Comment (joshhunt) [inline public/app/features/commandPalette/actions/useDashboardResults.ts:10]: nitpicky, but i think it's fine for this to just go in the dashboardActions file.

**Review by joshhunt — APPROVED** [review]
