### PR TITLE
Prometheus: Fixes default step value for annotation query

### LINKED ISSUE #21914: Annotations fail validation when step field is removed
**What happened**:
When upgrading from 6.3.0 to 6.6.0, in an annotation using a Prometheus datasource type, removing an existing value for the query step result in a broken annotation with the following error:
```
Annotation Query Failed
Invalid interval string, expecting a number followed by one of "Mwdhmsy"
```

**What you expected to happen**:
The annotation step should just use the default value of 60s

**How to reproduce it (as minimally and precisely as possible)**:
On an empty dashboard, create an annotation with Prometheus type datasource.
Set the query to anything really (`up` works)
Set the step value to 5m and save
Re-edit the annotation, remove the step value, leaving the field empty (which should default to 60s) and save
Create a panel -> error

**Anything else we need to know?**:
The error seems to stem from the json model: a step field is added when filling in `5m` and then set to `""` when the value is removed, which is then indeed invalid because not a timeframe.
Removing said field from the json and saving fixes the annotation

**Environment**:
- Grafana version: Grafana v6.6.0 (5c11bbdfb4)
- Data source type & version: Prometheus v2.15.2
- OS Grafana is installed on: Docker in RHEL
- User OS & Browser: Firefox 73.0b6 on MacOS
- Grafana plugins: -
- Others:

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
Introduced during a refactor here #20536. 
When the step is removed in the Annotation Editor the `annotation.step` is an empty string `''`. The original code `annotation.step || '60s'` handled this but in the refactor we use destructuring with a default value `, step = '60s' } = annotation` which only applies if `step` is `null` or `undefined`.

This PR adds a method to handle this case and make it easier to test. PR also adds a constant used in both Angular view code and in datasource.
 
**Which issue(s) this PR fixes**:
Closes #21914

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/datasource.ts [hunk 1]
```diff
@@ -520,20 +522,29 @@ export class PrometheusDatasource extends DataSourceApi<PromQuery, PromOptions>
     };
   }
 
+  createAnnotationQueryOptions = (options: any): DataQueryRequest<PromQuery> => {
+    const annotation = options.annotation;
+    const interval =
```
Comment (torkelo) [inline public/app/plugins/datasource/prometheus/datasource.ts]: Think we should use this.adjustInterval here so that the interval adjusts to time range (so the default 60s won't end up returning too many data points for a long time range).

Comment (hugohaggmark) [reply public/app/plugins/datasource/prometheus/datasource.ts]: Not sure about that, isn't that covered in createQuery?

Comment (hugohaggmark) [reply public/app/plugins/datasource/prometheus/datasource.ts]: Updated PR description so it's more clear what this fix does.

**Review by tskarhed — APPROVED** [review]
Looks good to me! :smiley:
