### PR TITLE
Fix: do not remove whitespace in PanelLink url

### LINKED ISSUE #21936: Spaces deleted from generated panel links
Since panel links (drilldown links) ui change on 6.3, it's impossible to use spaces inside the link (they removed). CHECK OUT EXAMPLES BELOW
In our migration process, all spaces appear on our defined drilldown links get deleted (when opening the link, not in the defined input).
Asking customers to use `%20` instead of spaces is ugly yet acceptable, but it still doesn't solve the migration issue.

Before version 6.3 (this is version 6.2.5):
Screen Shot 2020-02-05 at 12 26 19
the generated link is: `www.google.com?query=some%20query`

From 6.3 (this is version 6.5):
Screen Shot 2020-02-05 at 12 24 54
the generated link is: `www.google.com?query=somequery` the space is deleted!

**Environment**:
- Grafana version: 6.3 and up (Since changing panel links ui)

### PR DESCRIPTION
**Pull request by peterholmberg**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #21936

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hugohaggmark — APPROVED** [review]
LGTM!

**Review by dprokop — APPROVED** [review]

File: public/app/features/panel/panellinks/link_srv.ts [hunk 1]
```diff
@@ -268,7 +268,7 @@ export class LinkSrv implements LinkService {
     }
 
     const info: LinkModel<T> = {
-      href: locationUtil.assureBaseUrl(href.replace(/\s|\n/g, '')),
```
Comment (torkelo) [inline public/app/features/panel/panellinks/link_srv.ts]: think the newlines we want to remove

**Review by torkelo — COMMENTED** [review]
think the newline removal we want to keep
