### PR TITLE
Alerting: use duration model for alert rule provisioning api

### LINKED ISSUE #53183: Alerting: Unified Alerting REST API: Field `For` is always set to `0`
**What happened**:
I´m trying to create a Grafana-Managed rule via the unified alerting API. The value for the field `for` seems to be ignored. My JSON i send to `/api/v1/provisioning/alert-rules`:
```
 "annotations": {
            "summary": "trunc"
        },
        "labels": {
            "sn": "_changeme_"
        },
        "condition": "B",
        "title": "SN000092 - Letztes Statusupdate",
        "data": [
            {
                "refId": "A",
                "queryType": "",
                "relativeTimeRange": {
                    "from": 600,
                    "to": 0
                },
                "datasourceUid": "_changeme_",
                "model": {
                    "expr": "(time() - (push_time_seconds{job=\"caterva_collector_SNxxx\"})) / 3600",
                    "hide": false,
                    "intervalMs": 1000,
                    "maxDataPoints": 43200,
                    "refId": "A"
                }
            },
            {
                "refId": "B",
                "queryType": "",
                "relativeTimeRange": {
                    "from": 0,
                    "to": 0
                },
                "datasourceUid": "-100",
                "model": {
                    "conditions": [
                        {
                            "evaluator": {
                                "params": [
                                    6
                                ],
                                "type": "gt"
                            },
                            "operator": {
                                "type": "and"
                            },
                            "query": {
                                "params": [
                                    "A"
                                ]
                            },
                            "reducer": {
                                "params": [],
                                "type": "last"
                            },
                            "type": "query"
                        }
                    ],
                    "datasource": {
                        "type": "__expr__",
                        "uid": "-100"
                    },
                    "hide": false,
                    "intervalMs": 1000,
                    "maxDataPoints": 43200,
                    "refId": "B",
                    "type": "classic_conditions"
                }
            }
        ],
        "ruleGroup": "_changeme_",
        "noDataState": "OK",
        "execErrState": "OK",
        "for": 1200,
        "orgId": 1
```

Look at the value for the field `for` which is set to 1200. The result should be 20mins. But when I check the result (`/api/ruler/grafana/api/v1/rules?subtype=cortex`) I get the value zero:
```
{
    "expr": "",
    "for": "0s",
    "labels": {
        "sn": "000092"
    },
    "annotations": {
        "summary": "Deine Caterva-Anlage hat seit über 6 Stunden keine Werte mehr an das Reporting übermittelt."
    },
    "grafana_alert": {
        "id": 12,
        "orgId": 1,
        "title": "SN000092 - Letztes Statusupdate",
        "condition": "B",
        "data": [
            {
                "refId": "A",
                "queryType": "",
                "relativeTimeRange": {
                    "from": 600,
                    "to": 0
                },
                "datasourceUid": "vXgO9xzVz",
                "model": {
                    "expr": "(time() - (push_time_seconds{job=\"caterva_collector_SN000092\"})) / 3600",
                    "hide": false,
                    "intervalMs": 1000,
                    "maxDataPoints": 43200,
                    "refId": "A"
                }
            },
            {
                "refId": "B",
                "queryType": "",
                "relativeTimeRange": {
                    "from": 0,
                    "to": 0
                },
                "datasourceUid": "-100",
                "model": {
                    "conditions": [
                        {
                            "evaluator": {
                                "params": [
                                    6
                                ],
                                "type": "gt"
                            },
                            "operator": {
                                "type": "and"
                            },
                            "query": {
                                "params": [
                                    "A"
                                ]
                            },
                            "reducer": {
                                "params": [],
                                "type": "last"
                            },
                            "type": "query"
                        }
                    ],
                    "datasource": {
                        "type": "__expr__",
                        "uid": "-100"
                    },
                    "hide": false,
                    "intervalMs": 1000,
                    "maxDataPoints": 43200,
                    "refId": "B",
                    "type": "classic_conditions"
                }
            }
        ],
        "updated": "2022-08-02T20:31:17Z",
        "intervalSeconds": 600,
        "version": 3,
        "uid": "oADDrbk4k",
        "namespace_uid": "5ODvrxzVz",
        "namespace_id": 5,
        "rule_group": "SN000092",
        "no_data_state": "OK",
        "exec_err_state": "OK",
        "provenance": "api"
    }
}
```

now the value is set to zero seconds. The value I send has no effect.

**What you expected to happen**:
I can controll the value of the field `for` over the api

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Maybe this is related to https://github.com/grafana/grafana/pull/50992

**Environment**:
- Grafana version: 9.0.6 and 9.1.0-beta1
- Data source type & version: prometheus
- OS Grafana is installed on: docker
- User OS & Browser: Windows 11/ Edge
- Grafana plugins: none

### PR DESCRIPTION
**Pull request by JohnnyQQQQ**
Before this PR we did use the native golang type `time.Duration` which does not include any JSON support. In this PR we change to our internal type, supporting JSON.

Fixes https://github.com/grafana/grafana/issues/53183

### CODE REVIEW

File: pkg/services/ngalert/api/api_provisioning.go [hunk 1]
```diff
@@ -274,9 +278,12 @@ func (srv *ProvisioningSrv) RoutePostAlertRule(c *models.ReqContext, ar definiti
...
 
 func (srv *ProvisioningSrv) RoutePutAlertRule(c *models.ReqContext, ar definitions.ProvisionedAlertRule, UID string) response.Response {
-	updated := ar.UpstreamModel()
+	updated, err := ar.UpstreamModel()
+	if err != nil {
+		ErrResp(http.StatusBadRequest, err, "")
+	}
 	updated.UID = UID
-	updatedAlertRule, err := srv.alertRules.UpdateAlertRule(c.Req.Context(), ar.UpstreamModel(), alerting_models.ProvenanceAPI)
+	updatedAlertRule, err := srv.alertRules.UpdateAlertRule(c.Req.Context(), updated, alerting_models.ProvenanceAPI)
```
Comment (JohnnyQQQQ) [inline pkg/services/ngalert/api/api_provisioning.go:286]: This is a side-effect of this PR, we used the UID from the payload, but now we use it from the path. `updated` was never used before, just the UID was set and then nothing would happen with it.

Comment (alexweav) [reply pkg/services/ngalert/api/api_provisioning.go:286]: Lol, good catch. I feel like a linter should be able to catch this sort of thing since Go does not support overriding field setters?

For example, If I do this, the compiler complains:
```
unusedVar := doSomethingThatReturnsStructNotPtr()
<never touch unusedVar again>
```
but then nothing catches if I do this:
```
unusedVar := doSomethingThatReturnsStructNotPtr()
unusedVar.Foo = Bar
<never touch unusedVar again>
```
but we still clearly didn't do anything with `unusedVar`. The assignment will never have a side effect for sure because Go doesn't support overriding setters and it's not a ptr type. So, in pretty much all cases the above could theoretically be flagged, right? :thinking:

Comment (alexweav) [reply pkg/services/ngalert/api/api_provisioning.go:286]: Cool, i'm not the only one: https://github.com/golang/go/issues/449

File: pkg/services/ngalert/api/api_provisioning_test.go [hunk 2]
```diff
@@ -242,11 +243,13 @@ func TestProvisioningApi(t *testing.T) {
...
-				rule := createInvalidAlertRule()
-
-				response := sut.RoutePutAlertRule(&rc, rule, "rule")
+				uid := "123123"
+				rule := createTestAlertRule("rule", 1)
+				rule.UID = uid
+				insertRule(t, sut, rule)
 
+				rule = createInvalidAlertRule()
+				response := sut.RoutePutAlertRule(&rc, rule, uid)
```
Comment (alexweav) [inline pkg/services/ngalert/api/api_provisioning_test.go:252]: This is such a tiny nitpick it's unreal, but the original test had careful newlines to separate setup/act/assert stages and make the test a little more readable as to "what" it's testing. Could we readjust the spacing:
```
insertRule()
rule = createInvalidAlertRule()

response := sut.RoutePutAlertRule(...

require.Equal(...

File: pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go [hunk 3]
```diff
@@ -87,7 +88,7 @@ type ProvisionedAlertRule struct {
 	// required: true
 	ExecErrState models.ExecutionErrorState `json:"execErrState"`
 	// required: true
-	For time.Duration `json:"for"`
+	For model.Duration `json:"for"`
```
Comment (alexweav) [inline pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go:91]: Hate to be that person, but since this now serializes as a string instead of a number in JSON, does this count as a compatibility break?

Luckily there is no TF provider calling this yet. If there was, we'd have some issues (version N-1 only supports grafana 9.0 - 9.1, version N only supports grafana 9.0+) and we'd need to sync releases.

Comment (JohnnyQQQQ) [reply pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go:91]: It never worked before, so I wouldn't tag this as a breaking change. If anybody would had used it -- they wouldn't be able to.

File: pkg/services/ngalert/api/api_provisioning_test.go (hunk 2 above)
Comment (JohnnyQQQQ) [reply pkg/services/ngalert/api/api_provisioning_test.go]: Done

**Review by alexweav — APPROVED** [review]

File: pkg/services/ngalert/api/api_provisioning.go [hunk 4]
```diff
@@ -254,7 +254,11 @@ func (srv *ProvisioningSrv) RouteRouteGetAlertRule(c *models.ReqContext, UID str
 }
 
 func (srv *ProvisioningSrv) RoutePostAlertRule(c *models.ReqContext, ar definitions.ProvisionedAlertRule) response.Response {
-	createdAlertRule, err := srv.alertRules.CreateAlertRule(c.Req.Context(), ar.UpstreamModel(), alerting_models.ProvenanceAPI, c.UserID)
+	upstreamModel, err := ar.UpstreamModel()
+	if err != nil {
+		ErrResp(http.StatusBadRequest, err, "")
+	}
+	createdAlertRule, err := srv.alertRules.CreateAlertRule(c.Req.Context(), upstreamModel, alerting_models.ProvenanceAPI, c.UserId)
```
Comment (JohnnyQQQQ) [inline pkg/services/ngalert/api/api_provisioning.go:261]:
```suggestion
	createdAlertRule, err := srv.alertRules.CreateAlertRule(c.Req.Context(), upstreamModel, alerting_models.ProvenanceAPI, c.UserID)
```
