### PR TITLE
Alerting: Improve UI for making more clear that evaluation interval belongs to the group

### LINKED ISSUE #50290: Unified Alerting: All alarms are reset when saving one alarm
Hello Grafana,

When you edit an alert rule and save it ALL alerts rules are reset to resolved.
This creates confusion and unnecessary checking and communication of various teams. 

Before when you edited an alert rule, only that alert rule was reset. 

To reproduce it create two rules.
One rule (rule1) that goes in alert and one rule (rule2) where the status does not matter.
When you get the alert notification edit the second rule and save it.
Now rule one is gets the resolved status.

- Grafana version: 8.5.3
- Data source type & version: Prometheus 2.35.0
- OS Grafana is installed on: Debian 11
- User OS & Browser: Windows with Firefox

### PR DESCRIPTION
**Pull request by soniaAguilarPeiron**
**What this PR does / why we need it**:
This PR improves the alert rule form (only for grafana-managed alert rules)regarding evaluation interval concept. It makes more clear that the evaluation interval does not belong to the alert rule but to the group.

This PR adds the following changes: 

- Folder, group and evaluation interval has been moved to the same section (as they have to be handled as a block)
- Group becomes a drop-down list with the list of groups belonging to the current selected folder in the form.
- Evaluation interval by default it's not an editable field (as it belongs to the group, not to the alert). 
- But it can be updated by clicking on the 'Edit group' button. This button will open the `EditRuleGroupModal`, and in this case, user only can update the evaluation field.
- New groups, created from this form, have to be saved before being able to edit this evaluation interval.
- As we need to fetch ruler rules for these validations and for populating the groups drop-down, in case this response takes too much time, we will show this loading spinner without blocking the rest of the UI: 

Fixes #50290 
Fixes https://github.com/grafana/alerting-squad/issues/375

**Special notes for your reviewer**:

https://user-images.githubusercontent.com/33540275/200881209-4febeabb-65b7-4ac5-bfd5-c2f7c704fe44.mp4

@brendamuir changes have been done in these sections: 

Screenshot 2022-11-09 at 16 55 24

Screenshot 2022-11-09 at 16 55 31

Screenshot 2022-11-09 at 16 55 42

Screenshot 2022-11-09 at 16 55 47

Screenshot 2022-11-09 at 16 55 52

### CODE REVIEW

**Comment by VikaCep** [comment]
I have to admit it took me a few tries for me to understand that the input would become editable once the button was clicked. It wasn't immediately obvious to me. I think the confusion comes from the wording of the button which states "Edit group behavior" assuming users already know that the "Evaluate every" field belongs to the group, but inferring form the source issue, I think that fact is not very clear for users.  That said, I don't think this is a blocker and it's just my impression which could be wrong. Also it aligns with the Figma created by UX. 

What did call my attention is that if you repeatedly click on it, the visibility of the button/message toggles. I think once the button is clicked the first time then the message should just stay visible without allowing for it to toggle back to a disabled state.

**Comment by soniaAguilarPeiron** [comment]
> I have to admit it took me a few tries for me to understand that the input would become editable once the button was clicked. It wasn't immediately obvious to me. I think the confusion comes from the wording of the button which states "Edit group behavior" assuming users already know that the "Evaluate every" field belongs to the group, but inferring form the source issue, I think that fact is not very clear for users. Once the yellow message showed up then things were more clear. That said, I don't think this is a blocker and it's just my impression which could be wrong. Also it aligns with the Figma created by UX.
> 
> What did call my attention is that if you repeatedly click on it, the visibility of the button/message toggles. I think once the button is clicked the first time then the message should just stay visible without allowing for it to toggle back to a disabled state.
> 
>  [  ](https://user-images.githubusercontent.com/6271380/194370467-5b2f2d39-18cb-446f-aa94-59a41b08843d.gif) [ ](https://user-images.githubusercontent.com/6271380/194370467-5b2f2d39-18cb-446f-aa94-59a41b08843d.gif)

Thank you, @VikaCep 👌, I will take a look on the weird behaviour when clicking the button, and I will think a way to make more clear all the confusion that you mentioned.

**Comment by gillesdemey** [comment]
I think there's a few things we should add to the PR;

* Having a simple dropdown list of all of the existing groups in the selected folder, should be doable since we have all of the alert rules fetched at once – and of course allowing custom values
* Fetching the interval of the group you've selected, a rule author may not necessarily have created that group and thus might not know about what interval is already applied to that group.

File: public/app/features/alerting/unified/components/rule-editor/SelectWIthAdd.tsx [hunk 1]
```diff
@@ -29,13 +30,15 @@ export const SelectWithAdd: FC<Props> = ({
...
   'aria-label': ariaLabel,
+  getOptionLabel,
 }) => {
   const [isCustom, setIsCustom] = useState(custom);
 
   useEffect(() => {
-    if (custom) {
-      setIsCustom(custom);
-    }
+    //not sure why do we need this if
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/components/rule-editor/SelectWIthAdd.tsx:38]: I need to be able to hide the group input once user selects another folder (group drop-down should be reset)

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 2]
```diff
@@ -75,65 +102,193 @@ export const evaluateEveryValidationOptions: RegisterOptions = {
...
+            It can overwrite the interval of an existing alert rule. 
+            Click on 'Edit group behaviour' button to edit this group value.`}
+        </Card.Meta>
+        <Card.Actions>
+          {intervalHasChanged &&
+          !editInterval &&
+          someRulesBelongToThisGroup(initialRuleName, groupfoldersForGrafana?.result, group, folder?.title ?? '') ? (
+            <>
+              <div className={styles.intervalChangedLabel}>
+                <Icon name="exclamation-triangle" size="xs" className={cx('text-warning', styles.warningIcon)} />
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:173]: Can we replace the instances of `text-warning` to a custom CSS rule with 

```css
color: ${theme.colors.warning.text};
```

it appears that class has some weird `:hover` states I don't think we need :)

**Review by gillesdemey — CHANGES_REQUESTED** [review]
This is amazing! Couple of things I've questions about but we can address later in a follow-up PR;

1. It appears the group selection isn't cleared when another folder is selected – I'm thinking that's something we want to do?

2. The warning text about double checking the `For` duration seems to also show if the interval is the same as the existing one – a bug or should we just hide that?

image

File: public/app/features/alerting/unified/components/rule-editor/FolderAndGroup.tsx [hunk 3]
```diff
@@ -0,0 +1,236 @@
...
+    [groupOptions]
+  );
+  const folderTilte = folder?.title ?? '';
+
+  useEffect(() => {
+    if (folderTilte && groupOptions && !groupIsInGroupOptions(selectedGroup)) {
+      setIsAddingGroup(false);
+      resetGroup();
+    }
+    // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (VikaCep) [inline public/app/features/alerting/unified/components/rule-editor/FolderAndGroup.tsx:134]: can you add all the dependencies to the array instead of this line disabling it?

File: public/app/features/alerting/unified/state/actions.ts [hunk 4]
```diff
@@ -385,17 +388,49 @@ export function deleteRuleAction(
   };
 }
 
+export const isRulerGrafanaRuleDTO = (rule: RulerRuleDTO): rule is RulerGrafanaRuleDTO => 'grafana_alert' in rule;
+
+// This method was introduced for making betterer happy (it was complaining about using as StoreState)
+const isStoreState = (something: unknown): something is StoreState => {
+  if (typeof something === 'object') {
+    return something ? 'unifiedAlerting' in something : false;
```
Comment (VikaCep) [inline public/app/features/alerting/unified/state/actions.ts:396]: I'm confused by this ternary operator condition. You're evaluating whether `something` is truthy or not, but it will always be truthy as you already know it's of type `object` at that point. I think you could simply `return 'unifiedAlerting' in something`.

File: public/app/features/alerting/unified/state/actions.ts [hunk 5]
```diff
@@ -385,17 +388,49 @@ export function deleteRuleAction(
...
+  } else {
+    return false;
+  }
+};
```
Comment (VikaCep) [inline public/app/features/alerting/unified/state/actions.ts:400]: Or simpler yet:

```suggestion
const isStoreState = (something: unknown): something is StoreState => typeof something === 'object' && 'unifiedAlerting' in something;
```

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/state/actions.ts:400]: it needs to be checked if it's null

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/state/actions.ts:400]: maybe this could work though:
```
const isStoreState = 
(something: unknown): something is StoreState  => typeof something === 'object' && something ? 'unifiedAlerting' in something : false;
```

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/state/actions.ts:400]: But I think that maybe this 'one line expression' it's more confusing? WDT? @VikaCep @gillesdemey

File: public/app/features/alerting/unified/state/actions.ts (hunk 4 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/state/actions.ts:396]: I'm checking that something it's not null

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx (hunk 2 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:173]: > It appears the group selection isn't cleared when another folder is selected – I'm thinking that's something we want to do?
I've just pushed a commit for fixing this 😊

File: public/app/features/alerting/unified/state/actions.ts (hunk 5 above)
Comment (VikaCep) [reply public/app/features/alerting/unified/state/actions.ts:400]: Oh right, `null` is of type object 😮‍💨 Well don't worry then. It was just a nitpick.

File: public/app/features/alerting/unified/components/rule-editor/FolderAndGroup.tsx (hunk 3 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/FolderAndGroup.tsx:134]: good idea! @VikaCep

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx (hunk 2 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:173]: > The warning text about double checking the For duration seems to also show if the interval is the same as the existing one – a bug or should we just hide that?
Actually, I think we should remove this warning, as now we have a new validation in case this evaluation interval produces invalid For on another rules in the same group.

**Review by brendamuir — APPROVED** [review]

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 6]
```diff
@@ -51,90 +68,141 @@ export const forValidationOptions = (evaluateEvery: string): RegisterOptions =>
...
+            <div className={styles.evaluateLabelEnd}>
+              {`Evaluation interval applies to every rule within a group. 
+          It can overwrite the interval of an existing alert rule.`}
+            </div>
+            <br />
+          </div>
+        </Card.Meta>
+        <Card.Actions>
+          <div className={styles.editGroup}>
+            {`Click on Edit group button to edit this value `}
```
Comment (brendamuir) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:136]: I don't think you need to add this text since the button says Edit group

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 7]
```diff
@@ -51,90 +68,141 @@ export const forValidationOptions = (evaluateEvery: string): RegisterOptions =>
...
   const evaluateForId = 'eval-for-input';
 
   return (
-    // TODO remove "and alert condition" for recording rules
-    <RuleEditorSection stepNo={2} title="Alert evaluation behavior">
+    <div className={styles.flexRow}>
+      <InlineLabel
+        htmlFor={evaluateForId}
+        width={7}
+        tooltip='Once condition is breached, alert will go into pending state. If it is pending for longer than the "for" value, it will become a firing alert.'
```
Comment (brendamuir) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:167]:
```suggestion
        tooltip='Once the condition is breached, the alert goes into pending state. If the alert is pending longer than the "for" value, it becomes a firing alert.'
```

File: public/app/features/alerting/unified/components/rule-editor/FolderAndGroup.tsx [hunk 8]
```diff
@@ -0,0 +1,226 @@
...
+  return (
+    <div className={styles.container}>
+      <Field
+        label={
+          <Label htmlFor="folder" description={'Select a folder to store your rule.'}>
+            <Stack gap={0.5}>
+              Folder
+              <InfoIcon
+                text={
+                  'Each folder has unique folder permission. When you store multiple rules in a folder, the folder access permissions get assigned to the rules.'
```
Comment (brendamuir) [inline public/app/features/alerting/unified/components/rule-editor/FolderAndGroup.tsx:132]:
```suggestion
                  'Each folder has unique folder permission. When you store multiple rules in a folder, the folder access permissions are assigned to the rules.'
```

File: public/app/features/alerting/unified/components/rule-editor/FolderAndGroup.tsx [hunk 9]
```diff
@@ -0,0 +1,226 @@
...
+                if (!groupIsInGroupOptions(selectedGroup)) {
+                  setIsAddingGroup(false);
+                  resetGroup();
+                }
+              }}
+            />
+          )}
+          name="folder"
+          rules={{
+            required: { value: true, message: 'Please select a folder' },
```
Comment (brendamuir) [inline public/app/features/alerting/unified/components/rule-editor/FolderAndGroup.tsx:163]:
```suggestion
            required: { value: true, message: 'Select a folder' },
```

**Comment by VikaCep** [comment]
I think we should disable the Edit group button when we're creating a new group, otherwise saving its changes throws an error:

**Comment by soniaAguilarPeiron** [comment]
> I think we should disable the Edit group button when we're creating a new group, otherwise saving its changes throws an error:
> 
>  [  ](https://user-images.githubusercontent.com/6271380/200666841-8e7defe6-e0d0-4f3c-ae20-6fd1b737580b.gif) [ ](https://user-images.githubusercontent.com/6271380/200666841-8e7defe6-e0d0-4f3c-ae20-6fd1b737580b.gif)
💯! @VikaCep I've just pushed a commit with this

**Review by brendamuir — APPROVED** [review]

**Review by VikaCep — APPROVED** [review]
Great work!! 💯

**Comment by gillesdemey** [comment]
I get some overlapping text artifacts in the UI that I think are related to the `evaluateLabelEnd` styles having a negative margin – why do we need that?

image

**Review by gillesdemey — APPROVED** [review]

**Review by gillesdemey — CHANGES_REQUESTED** [review]
Identified some browser-specific issues on Firefox

**Comment by soniaAguilarPeiron** [comment]
> Identified some browser-specific issues on Firefox

@gillesdemey good find! I've just pushed the fix 👀

**Review by gillesdemey — APPROVED** [review]
Amazing improvement, great work 🚀 :shipit:
