### PR TITLE
Loki, Prometheus: Fix PromQL and LogQL syntax highlighting

### LINKED ISSUE #20758: PromQL syntax highlighting is broken when string literal contains a pound sign (#)
**What happened**:
When a pound sign appears anywhere inside a string literal, it seems to be interpreted as a comment, and so the syntax highlighting is broken for the whole selector.
firefox_37Covn5Fj0

**What you expected to happen**:
bilde

**How to reproduce it (as minimally and precisely as possible)**:
Run a query like `{label="#"}`.

**Anything else we need to know?**:
No, that's pretty much it.

**Environment**:
- Grafana version: v6.4.4 (092e514)
- Data source type & version: Prometheus, not sure about the version
- OS Grafana is installed on: N/A
- User OS & Browser: Windows 10, Firefox 70
- Grafana plugins: Loki, Prometheus
- Others:

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
This PR fixes highlighting of comments for LogQL and PromQL. Currently **#** anywhere in query (besides new line) is considered and highlighted as a comment. Therefore if **#** is used as a label, highlighting is broken. 

This PR fixes this by changing the comment's regex and **#** at the beginning, at the end, or within the word is not highlighted as a comment. 

**Regex currently in master**:
image
image
image
image
image
image
image

**Fixed regex:**
image
image
image
image
image
image

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/20758

### CODE REVIEW

File: public/app/plugins/datasource/loki/syntax.ts [hunk 1]
```diff
@@ -69,7 +69,7 @@ export const FUNCTIONS = [...AGGREGATION_OPERATORS, ...RANGE_VEC_FUNCTIONS];
 
 const tokenizer: Grammar = {
   comment: {
-    pattern: /(^|[^\n])#.*/,
+    pattern: /(^|[^\n"a-zA-Z])#.*/,
```
Comment (aocenas) [inline public/app/plugins/datasource/loki/syntax.ts]: So I do not think we can solve it by single regex here. This still does not match comment on a new line and if you do `##` inside the label value it still matches as comment.

What we can do is set this to simple `/#.*/` pattern, then make `context-labels` `greedy: true`. This will make it so that `context-labels` will be matched first and so no comment will be matched inside that group. But then we can add the same `comment: /#.*/,` to be in the `inside` key and because `label-value` is also greedy it will now allow comment inside the `label-value`.

Probably need to be tested though is there is no edge case.

**Comment by ivanahuckova** [comment]
@aocenas thanks for the tips, I have also added the test coverage for loki and promql syntax (tests are identical).

**Review by aocenas — APPROVED** [review]
