### PR TITLE
Panel: Fix text aliasing bug when panel is loading

### LINKED ISSUE #88104: Viz: The loading bar causes text to shift
### What happened?

A loading bar is shown for slow queries for the panel, which causes text to shift.
blur-bug-1

Only happens when there is no title for the panel.
blur-bug-panel-title-1

This issue is similar to #82214 but was only fixed for panels with a title.

It only happens on Chromium-based browsers like Chrome, Edge, Brave, Etc.
It doesn't happen on Firefox.

### What did you expect to happen?

The text to not shift when retrieving data.

### Did this work before?

It worked in v9.4 and broke in v9.5.
It was partially fixed in v11, but only for panels with a title.

### How do we reproduce it?

blur-bug-reproducable-1

1. Create a new stat panel with the `TestData` data source
2. Change the query scenario to be `Slow Query`
3. Change `Show` under `Value options` to `All values`
4. Change `Fields` under `Value options` to `time`
5. Remove the panel title
6. Refresh the panel (the text shifts)

### Is the bug inside a dashboard panel?

Removed some of the data points since I got `There was an error creating your Issue: body is too long (maximum is 65536 characters).`

| Key | Value |
|--|--|
| Panel | stat @ 11.0.0 |
| Grafana | Grafana v11.0.0 (277ef258d4) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "type": "stat",
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "id": 2,
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "typeVersion": [
                    0,
                    0
                  ],
                  "custom": {
                    "customStat": 10
                  }
                },
                "fields": [
                  {
                    "name": "time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time",
                      "nullable": true
                    },
                    "config": {
                      "interval": 15000
                    }
                  },
                  {
                    "name": "A-series",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64",
                      "nullable": true
                    },
                    "labels": {},
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1716210855578,
                    1716210870578,
                    1716210885578,
                    1716210900578,
                    1716210915578,
                    1716210930578,
                    1716210945578,
                    1716210960578,
                  ],
                  [
                    31.494190733870685,
                    31.4360624052497,
                    31.41956566114027,
                    31.1754770651706,
                    31.12398544924021,
                    31.23567247094241,
                    31.212607552630143,
                    31.429187433477672
                  ]
                ]
              }
            }
          ]
        }
      ],
      "options": {
        "reduceOptions": {
          "values": true,
          "calcs": [
            "lastNotNull"
          ],
          "fields": "/^time$/"
        },
        "orientation": "auto",
        "textMode": "auto",
        "wideLayout": true,
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "showPercentChange": false
      },
      "fieldConfig": {
        "defaults": {
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "value": null,
                "color": "green"
              },
              {
                "value": 80,
                "color": "red"
              }
            ]
          },
          "color": {
            "mode": "thresholds"
          }
        },
        "overrides": []
      },
      "pluginVersion": "11.0.0",
      "title": "Reproduced with embedded data"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >stat @ 11.0.0</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[grafana-testdata-datasource]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 1 frames, 2 fields, 1440 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>Grafana v11.0.0 (277ef258d4) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"type\": \"stat\",\n  \"gridPos\": {\n    \"x\": 0,\n    \"y\": 0,\n    \"w\": 12,\n    \"h\": 8\n  },\n  \"datasource\": {\n    \"uid\": \"cdc7hj45r7474f\",\n    \"type\": \"grafana-testdata-datasource\"\n  },\n  \"id\": 1,\n  \"targets\": [\n    {\n      \"scenarioId\": \"slow_query\",\n      \"refId\": \"A\",\n      \"datasource\": {\n        \"type\": \"grafana-testdata-datasource\",\n        \"uid\": \"cdc7hj45r7474f\"\n      },\n      \"stringInput\": \"1s\"\n    }\n  ],\n  \"options\": {\n    \"reduceOptions\": {\n      \"values\": true,\n      \"calcs\": [\n        \"lastNotNull\"\n      ],\n      \"fields\": \"/^time$/\"\n    },\n    \"orientation\": \"auto\",\n    \"textMode\": \"auto\",\n    \"wideLayout\": true,\n    \"colorMode\": \"value\",\n    \"graphMode\": \"area\",\n    \"justifyMode\": \"auto\",\n    \"showPercentChange\": false\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"value\": null,\n            \"color\": \"green\"\n          },\n          {\n            \"value\": 80,\n            \"color\": \"red\"\n          }\n        ]\n      },\n      \"color\": {\n        \"mode\": \"thresholds\"\n      }\n    },\n    \"overrides\": []\n  },\n  \"pluginVersion\": \"11.0.0\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: undefined // 2024-05-20 21:38:34",
  "tags": [
    "debug",
    "debug-stat"
  ],
  "time": {
    "from": "2024-05-20T13:38:34.177Z",
    "to": "2024-05-20T19:38:34.178Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana: 11.0.0 (277ef258d4)
OS: Windows 11
Browser: Brave Version 1.66.110 Chromium: 125.0.6422.60 (Official Build)  (64-bit)

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- sets `zIndex: 1` on the loading bar container to force it to create its own stacking context and prevent it from interfering with the panel content

**Why do we need this feature?**

- so the text doesn't flicker when the loading bar appears
  - note: this bug only happened in webkit browsers on windows/linux from what i can tell. it's impossible to recreate on mac

**Who is this feature for?**

- anyone on webkit based browsers on windows/linux

**Which issue(s) does this PR fix?**:

Fixes #88104 
Supersedes #88105 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/PanelChrome/PanelChrome.tsx [hunk 1]
```diff
@@ -423,6 +423,10 @@ const getStyles = (theme: GrafanaTheme2) => {
       position: 'absolute',
       top: 0,
       width: '100%',
+      // this is to force the loading bar container to create a new stacking context
+      // otherwise, in webkit browsers on windows/linux, the aliasing of panel text changes when the loading bar is shown
+      // see https://github.com/grafana/grafana/issues/88104
+      zIndex: 1,
```
Comment (joshhunt) [inline packages/grafana-ui/src/components/PanelChrome/PanelChrome.tsx:429]: did you also consider https://developer.mozilla.org/en-US/docs/Web/CSS/will-change ?

Comment (ashharrison90) [reply packages/grafana-ui/src/components/PanelChrome/PanelChrome.tsx:429]: `LoadingBar` already sets `will-change` on the element that transforms

**Review by joshhunt — APPROVED** [review]
