### PR TITLE
AzureAD OAuth: Add support for fetching user groups

### LINKED ISSUE #43356: Azure AD OAuth: Grafana does not fetch user groups when #groups > 200 (Does not support distributed claims)
**What happened**:
For users who are member of more than 200 azure AD groups, the groups are not being parsed and the Team Sync feature is broken

**What you expected to happen**:
The groups are correctly parsed upon login for all users.
Grafana should support distributed claims as per the official OIDC spec

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an app registration in Azure, configure auth.azuread in grafana.ini to use this app registration (URLs, client secret).
2. Add a user to this app registration/enterprise application who is a member of 200+ groups
3. Attempt to login with this user
4. Note the following line in the logs:
t=2021-12-09T14:34:58+0000 lvl=dbug msg="AzureAD OAuth: extracted groups" logger=social email=xxx@yyy.com groups=[]

**Anything else we need to know?**:
In Azure, if a user is indirectly a member of more than 200 groups, Azure will send _claim_names and _claim_sources instead of the groups, per OIDC Core 1.0, section 5.6.2:
https://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims

Example:
```
{
  "_claim_names": {
    "groups": "src1"
  },
  "_claim_sources": {
    "src1": {
      "endpoint": "https://graph.windows.net/{orgId}/users/{userId}/getMemberObjects"
    }
  }
}
```
The groups then have to be fetched in a separate request

longform explanation in someones blog post: http://www.mattruma.com/adventures-with-azure-ad-group-overage-claim/

**Environment**:
- Grafana version: 8.3.3 enterprise
- Data source type & version:
- OS Grafana is installed on: Default official container (Alpine)
- User OS & Browser: Windows 10, chrome
- Grafana plugins: -
- Others:

### PR DESCRIPTION
**Pull request by kalleep**
**What this PR does / why we need it**:
When a user is member of 200 or more groups they will not be part of the ID Token. Instead the claims will include two additional properties (_claim_names and _claim_sources). To get groups for the user we have to fetch them from provided endpoint.

Group overage doc: https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#groups-overage-claim
Docs getGroups endpoint endpoint: https://docs.microsoft.com/en-us/graph/api/directoryobject-getmemberobjects

The provided endpoint in _claims_sources points to the deprecated graph.windows.net. So wee need to hard code the url to the graph.microsoft.com api.

To manually test this a user need to be configured with 200+ groups and token needs permissions for User.Read and GroupMember.Read.All

**Which issue(s) this PR fixes**:
Fixes #43356

### CODE REVIEW

File: pkg/login/social/azuread_oauth.go [hunk 1]
```diff
@@ -20,19 +22,33 @@ type SocialAzureAD struct {
...
+	Roles             []string               `json:"roles"`
+	Groups            []string               `json:"groups"`
+	Name              string                 `json:"name"`
+	ID                string                 `json:"oid"`
+	ClaimNames        claimNames             `json:"_claim_names,omitempty"`
+	ClaimSources      map[string]claimSource `json:"_claim_sources,omitempty"`
+}
+
+type claimNames struct {
+	Groups string `json:"groups"`
```
Comment (sakjur) [inline pkg/login/social/azuread_oauth.go:36]: Will we need this for Roles as well? 🤔

File: pkg/login/social/azuread_oauth.go [hunk 2]
```diff
@@ -56,7 +72,12 @@ func (s *SocialAzureAD) UserInfo(_ *http.Client, token *oauth2.Token) (*BasicUse
 	role := extractRole(claims, s.autoAssignOrgRole)
 	logger.Debug("AzureAD OAuth: extracted role", "email", email, "role", role)
 
-	groups := extractGroups(claims)
+	groups, err := extractGroups(client, claims, token)
+	if err != nil {
+		logger.Error("AzureAD OAuth: failed to extract groups", "error", err)
+		return nil, err
```
Comment (sakjur) [inline pkg/login/social/azuread_oauth.go:78]: No need to log the error here, pass it up to the caller and let the caller handle it.

```suggestion
		return nil, fmt.Errorf("failed to extract groups: %w", err)
```

File: pkg/login/social/azuread_oauth.go [hunk 3]
```diff
@@ -127,8 +148,64 @@ func hasRole(roles []string, role models.RoleType) bool {
...
+		}
+
+		var accessClaims azureAccessClaims
+		if err := parsedToken.UnsafeClaimsWithoutVerification(&accessClaims); err != nil {
+			return nil, errutil.Wrapf(err, "error getting claims from access token")
+		}
+
+		// Sadly the endpoints provided in _claim_source is pointed to the deprecated "graph.windows.net" api
+		// See https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-overview
+		// So instead we do the group lookup to microsoft graph api
```
Comment (sakjur) [inline pkg/login/social/azuread_oauth.go:177]: I would still use the endpoints in `_claim_source` if that still works. That's more resilient toward them deciding to drop this endpoint too, since that's following some kind of standard.

File: pkg/login/social/azuread_oauth.go [hunk 4]
```diff
@@ -127,8 +148,64 @@ func hasRole(roles []string, role models.RoleType) bool {
...
+}
+
+type getAzureGroupResponse struct {
+	Value []string `json:"value"`
+}
+
+func extractGroups(client *http.Client, claims azureClaims, token *oauth2.Token) ([]string, error) {
+	if len(claims.Groups) > 0 {
+		return claims.Groups, nil
+	} else if claims.ClaimNames.Groups != "" {
```
Comment (sakjur) [inline pkg/login/social/azuread_oauth.go:162]: If you re-arrange this a little, you'll be able to shift the big block to the left 🤔

```suggestion
	}

	if claims.ClaimNames.Groups == "" {
		return nil, nil
	}
```

**Review by sakjur — APPROVED** [review]
I think it'd be good to add tests, but even without them this looks like an improvement and it doesn't look like it should be able to break anything so I'm going to eagerly approve it :+1:

File: pkg/login/social/azuread_oauth.go (hunk 3 above)
Comment (kalleep) [reply pkg/login/social/azuread_oauth.go:176]: Yeah, i just need to figure out what permissions is required to access that endpoint then. Got access denied error when trying to use it

File: pkg/login/social/azuread_oauth.go (hunk 4 above)
Comment (kalleep) [reply pkg/login/social/azuread_oauth.go:161]: true

File: pkg/login/social/azuread_oauth.go (hunk 1 above)
Comment (kalleep) [reply pkg/login/social/azuread_oauth.go:36]: There is nothing in the docs about roles overage. Seem like this only applies to groups

File: pkg/login/social/azuread_oauth_test.go [hunk 5]
```diff
@@ -249,6 +254,54 @@ func TestSocialAzureAD_UserInfo(t *testing.T) {
...
+			fields: fields{
+				SocialBase: newSocialBase("azuread", &oauth2.Config{}, &OAuthInfo{}),
+			},
+			claims: &azureClaims{
+				ID:                "1",
+				Name:              "test",
+				PreferredUsername: "test",
+				Email:             "test@test.com",
+				Roles:             []string{"Viewer"},
+				ClaimNames:        claimNames{Groups: "src1"},
```
Comment (sakjur) [inline pkg/login/social/azuread_oauth_test.go:268]:
```suggestion
				ClaimNames:        claimNames{Groups: "src1"},
				ClaimSources:      nil, // set by the test
```

Maybe this is silly, wdyt?

File: pkg/login/social/azuread_oauth_test.go [hunk 6]
```diff
@@ -249,6 +254,54 @@ func TestSocialAzureAD_UserInfo(t *testing.T) {
...
+				Name:   "test",
+				Email:  "test@test.com",
+				Login:  "test@test.com",
+				Role:   "Viewer",
+				Groups: []string{"from_server"},
+			},
+			wantErr: false,
+		},
+		{
+			name: "Fetch groups when ClaimsNames and ClaimsSources is set",
```
Comment (sakjur) [inline pkg/login/social/azuread_oauth_test.go:282]: Is this the same test repeated? 🤔

**Review by sakjur — APPROVED** [review]
