### PR TITLE
TimeSeries: Implement auto decimals for y axes

### LINKED ISSUE #46570: Grafana time series duplicated values in left axis
**What happened**:
Time series graph displays duplicate values
**What you expected to happen**:
no duplicate values
**How to reproduce it (as minimally and precisely as possible)**:
I have a series of time buckets from SQL that counts an event every 15 minutes. The count can only be a whole number. I have set decimals to 0 in  grafana believing that it would give me a simple graph with the left axis count from 0,1,2,3,4 but actually it shows 0,1,2,2,3,3.
**Anything else we need to know?**:

**Environment**:
- Grafana version: latest
- Data source type & version:
- OS Grafana is installed on: Server 2019
- User OS & Browser:Windows 10, edge
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes [#3383](https://github.com/grafana/support-escalations/issues/3383)
Fixes https://github.com/grafana/grafana/issues/46570

there has been a steady stream of issues where it appears like the Y axis has duplicate ticks. the cause for this is simply insufficient decimal precision set on the field (since we typically use the field's configured `decimals` and the resulting `.display()` displayProcessor). the issue resolution for this has been to ask users to increase the `decimals` setting, but this is not ideal, since zooming and dynamic data ranges can easily change the needed precision.

this implements a second `decimals` argument for `displayProcessor(value, decimals)` so it can be called with a dynamic value, which is asserted from the generated y axis tick increments.

an alternative approach would be to not rely on `field.display()` for y axis tick formatting.

### CODE REVIEW

File: public/app/features/transformers/calculateHeatmap/utils.ts [hunk 1]
```diff
@@ -1,7 +1,11 @@
 const { abs, round, pow } = Math;
 
-export function roundDec(val: number, dec: number) {
-  return round(val * (dec = 10 ** dec)) / dec;
+// https://stackoverflow.com/a/48764436
+// rounds half away from zero
+export function roundDec(val: number, dec = 0) {
+  let p = 10 ** dec;
+  let n = val * p * (1 + Number.EPSILON);
+  return round(n) / p;
```
Comment (leeoniya) [inline public/app/features/transformers/calculateHeatmap/utils.ts:8]: @ryantxu we should pull this out into a generic util fn and re-use, where shall it go?

Comment (ryantxu) [reply public/app/features/transformers/calculateHeatmap/utils.ts:8]: somethign in: https://github.com/grafana/grafana/tree/main/packages/grafana-data/src/utils

File: packages/grafana-data/src/field/displayProcessor.ts [hunk 2]
```diff
@@ -75,7 +75,7 @@ export function getDisplayProcessor(options?: DisplayProcessorOptions): DisplayP
   const formatFunc = getValueFormat(unit || 'none');
   const scaleFunc = getScaleCalculator(field, options.theme);
 
-  return (value: any) => {
+  return (value: any, decimals?: number | null) => {
```
Comment (ryantxu) [inline packages/grafana-data/src/field/displayProcessor.ts:78]: do we need the | null?
```suggestion
  return (value: any, decimals?: number) => {
```

File: packages/grafana-data/src/types/displayValue.ts [hunk 3]
```diff
@@ -1,6 +1,6 @@
 import { FormattedValue } from '../valueFormats';
 
-export type DisplayProcessor = (value: any) => DisplayValue;
+export type DisplayProcessor = (value: any, decimals?: number | null) => DisplayValue;
```
Comment (ryantxu) [inline packages/grafana-data/src/types/displayValue.ts:3]:
```suggestion
export type DisplayProcessor = (value: any, decimals?: number) => DisplayValue;
```

File: packages/grafana-data/src/field/displayProcessor.ts (hunk 2 above)
Comment (leeoniya) [reply packages/grafana-data/src/field/displayProcessor.ts:78]: i think we need to stay in line with https://github.com/grafana/grafana/blob/277a83215c1e20ff8c93768f93edf92d60deee5f/packages/grafana-data/src/types/displayValue.ts#L38

File: public/app/features/transformers/calculateHeatmap/utils.ts [hunk 4]
```diff
@@ -1,15 +1,9 @@
-const { abs, round, pow } = Math;
+import { guessDec, roundDec } from '@grafana/data';
```
Comment (ryantxu) [inline public/app/features/transformers/calculateHeatmap/utils.ts:1]: given that it is in global scope, can we be more explicit on what "Dec" is?
```suggestion
import { guessDecimals, roundDecimals } from '@grafana/data';
```
maybe?

File: packages/grafana-data/src/utils/numbers.ts [hunk 5]
```diff
@@ -0,0 +1,11 @@
+// https://stackoverflow.com/a/48764436
+// rounds half away from zero
+export function roundDec(val: number, dec = 0) {
+  let p = 10 ** dec;
+  let n = val * p * (1 + Number.EPSILON);
+  return Math.round(n) / p;
+}
+
+export function guessDec(num: number) {
```
Comment (ryantxu) [inline packages/grafana-data/src/utils/numbers.ts:9]:
```suggestion
/**
 * guess an appropriate 🤷 
 */
export function guessDecimals(num: number) {
```

**Review by ryantxu — APPROVED** [review]

File: packages/grafana-data/src/utils/numbers.ts [hunk 6]
```diff
@@ -0,0 +1,29 @@
...
+ *
+ * used for determining minimum decimals required to uniformly
+ * format a numric sequence, e.g. 10, 10.125, 10.25, 10.5
+ *
+ * good for precisce increments:  0.125            -> 3
+ * bad  for arbitrary floats:     371.499999999999 -> 12
+ */
+export function guessDecimals(num: number) {
+  return (('' + num).split('.')[1] || '').length;
+}
```
Comment (leventebalogh) [inline packages/grafana-data/src/utils/numbers.ts:29]: **Suggestion:** I think we should add some tests for these utility functions, especially as they are used in a lot of places.

Although I like the comments here (they are making the "why" easier to understand), tests could also help making it easier to understand what these are doing (apart from being a safety net).
