### PR TITLE
Fix home breadcrumbs

### LINKED ISSUE #83888: DashboardScene: Homepage dashboard loaded differently if access via ?orgId=1 in URL
I'm noticing inconsistent behaviour when loading the OSS homepage dashboard. I have the `dashboardSceneForViewers` feature enabled

 - When i navigate to http://localhost:3000/ my breadcrumbs read Home > Dashboards > Home, and there's an extra gap at the top of the page that clips the dashboard as it scrolls. (bug!)
 - When I navigate directly to http://localhost:3000/?orgId=1 , I get correct breadcrumbs and no extra gap at the top of the page

| Incorrect | Correct |
| --- | --- |
| image | image |

### PR DESCRIPTION
**Pull request by mdvictor**
Fixes the dashboard breadcrumbs on the homepage when navigating to `http://localhost:3000/`. It would default to a wrong url in that component and rendered `Home > Dashboard > Home` instead of simply `Home`.

Also fixes the gap reported in the issue.

Fixes https://github.com/grafana/grafana/issues/83888

### CODE REVIEW

File: public/app/features/dashboard-scene/utils/urlBuilders.ts [hunk 1]
```diff
@@ -54,6 +56,10 @@ export function getDashboardUrl(options: DashboardUrlOptions) {
     };
   }
 
+  if (options.isHomeDashboard) {
```
Comment (mdvictor) [inline public/app/features/dashboard-scene/utils/urlBuilders.ts:59]: Why do we build the paths like this instead of using `location.pathname`? I must be missing something here

Comment (torkelo) [reply public/app/features/dashboard-scene/utils/urlBuilders.ts:59]: @mdvictor what do you mean? this is used for many different scenarios (like generating URLs to solo panels which has different pathname)

Also a new dashboard has no uid so also has a unique pathname. What would your alternative be?

**Review by axelavargas — COMMENTED** [review]
Great work @mdvictor 🥳 , locally works as expected, can we test using an ephemeral instance? I would like to check when the home is `cloud-home-app`

File: public/app/features/dashboard-scene/utils/urlBuilders.ts (hunk 1 above)
Comment (mdvictor) [reply public/app/features/dashboard-scene/utils/urlBuilders.ts:59]: Indeed, for the scenarios where we need to build the url it makes sense, like the share tab. But for dashboardScene [here](https://github.com/grafana/grafana/blob/13a81ea929d4fe719fdc1502430a1c5ccaf309c1/public/app/features/dashboard-scene/scene/DashboardScene.tsx#L394) couldn't we just pass the pathname and build the query params on top of that?

Why are we deducing the path based on `uid` and `meta` info instead of just getting the base `location.pathname` and adding query params?

**Review by axelavargas — APPROVED** [review]
