### PR TITLE
Tempo: Fix Otel span kind mapping in trace upload resultTransformer

### LINKED ISSUE #43060: Cannot import a trace that was exported from Grafana
**What happened**:
I exported a trace from the Tempo explore view (using Inspector -> Data -> Download traces) but I am unable to import it using the JSON File option in the Tempo explore view. 

This seems to be due to the value contained in the `kind` field, where values different than `SPAN_KIND_SERVER` are supported when loading from Tempo directly but not when importing as json. If I replace the `kind` field with `SPAN_KIND_SERVER `, I can now upload the JSON fine.

The same thing happens when getting the contents from the Tempo API directly using curl, I am unable to import the JSON except if I replace `kind` with `SPAN_KIND_SERVER`.

**What you expected to happen**:
I would be able to import the JSON file I had downloaded

**How to reproduce it (as minimally and precisely as possible)**:
* Download example JSON from https://grafana.com/docs/grafana/latest/datasources/tempo/#upload-json-trace-file
* Replace `kind` field with `SPAN_KIND_CONSUMER`
* Try to upload the json file in the Tempo explore view

**Environment**:
- Grafana version: 8.4.0-pre (641eef15b7)
- Data source type & version: Tempo data source

Error when uploading:
Screen Shot 2021-12-13 at 1 59 58 PM

### PR DESCRIPTION
**Pull request by connorlindsey**
**What this PR does / why we need it**:
Fixes the span kind mapping when uploading traces from json

**Which issue(s) this PR fixes**:
Fixes #43060

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/datasource/tempo/resultTransformer.ts [hunk 1]
```diff
@@ -220,9 +220,11 @@ function getSpanTags(
     span.kind !== undefined &&
     span.kind !== collectorTypes.opentelemetryProto.trace.v1.Span.SpanKind.SPAN_KIND_INTERNAL
   ) {
+    // collectorTypes...SpanKind includes "SPAN_KIND_UNSPECIFIED" at 0 so we need to subtract 1 from
+    // the index to map to the correct value in the SpanKind enum
     spanTags.push({
       key: 'span.kind',
-      value: SpanKind[collectorTypes.opentelemetryProto.trace.v1.Span.SpanKind[span.kind] as any].toLowerCase(),
+      value: SpanKind[(collectorTypes.opentelemetryProto.trace.v1.Span.SpanKind[span.kind] as any) - 1].toLowerCase(),
```
Comment (aocenas) [inline public/app/plugins/datasource/tempo/resultTransformer.ts:227]: Bit unsure why this code looks like this. It seems to me we could just do
```
spanTags.push({
      key: 'span.kind',
      value: span.kind.toString().toLowerCase().split('_').last()
})
```
or something like that as it seems like we just need to convert the enum string values so they are a bit more readable. Also not sure why SPAN_KIND_INTERNAL isn't added? If we are processing the span why not add its kind here? @zoltanbedi do you maybe remember why we do it like this?

Comment (connorlindsey) [reply public/app/plugins/datasource/tempo/resultTransformer.ts:227]: I think we lose a bit of safety by just converting the string although since it's a tag, it's probably not a big deal to have any string as the value. That would simplify the code a bit.

INTERNAL is the default span kind so maybe that's why we don't add the tag? Seems like we should still just add it.

Comment (aocenas) [reply public/app/plugins/datasource/tempo/resultTransformer.ts:227]: >I think we lose a bit of safety by just converting the string 

What do you mean? That the enum value name could change? I mean yeah probably should fallback to not split() or something just in case to still get something meaningful but don't see many other issues. If the definitions change the current approach could probably fail even more because we are not really doing type-checked access to those enums anyway.

We can still filter out the `internal` tag if needed, not sure if it is important or not.

Comment (connorlindsey) [reply public/app/plugins/datasource/tempo/resultTransformer.ts:227]: I was thinking that by using the enum, we're restricting it to a set of valid values. Without the enum, we're allowing any value which I guess is fine. True that if the definitions change, it'd break. 

I'll switch to just going off of the string value and add some more error handling. I'll also remove the INTERNAL condition unless Zoltan confirms we need it.

Comment (aocenas) [reply public/app/plugins/datasource/tempo/resultTransformer.ts]: > I was thinking that by using the enum, we're restricting it to a set of valid values.

Just to clarify, aren't both `SpanKind` and `collectorTypes.opentelemetryProto.trace.v1.Span.SpanKind` coming from OpenTelemetry types? Do they have different meanings? It seems to me like a definitions bug that they have different values tbh.

Comment (connorlindsey) [reply public/app/plugins/datasource/tempo/resultTransformer.ts]: Yeah, they do differ because one is from the js-api and the other from the collector. It does seem like a bug that they differ - that difference is what caused this bug in the first place

Comment (zoltanbedi) [reply public/app/plugins/datasource/tempo/resultTransformer.ts]: > Also not sure why SPAN_KIND_INTERNAL isn't added? If we are processing the span why not add its kind here? @zoltanbedi do you maybe remember why we do it like this?

I think I just missed it.

**Review by aocenas — APPROVED** [review]

File: public/app/plugins/datasource/tempo/resultTransformer.ts (hunk 1 above)
Comment (aocenas) [reply public/app/plugins/datasource/tempo/resultTransformer.ts]: thanks, in that case, let's merge this PR, I don't think having that additional tag there would make anything worse and seem more consistent this way.
