### PR TITLE
Transformations: break add field from calculation transformation UI into sub components

### LINKED ISSUE #77186: Transformations: Refactor add field from calculation UI component
**What is the chore?**:
The add field from calculation transformation has grown to a state where it's rather bloated. It should be converted to a functional component, and the different UI for the different modes should be broken into their own components.

### PR DESCRIPTION
**Pull request by oscarkilhed**
**What is this feature?**
This continues the refactoring of the UI part of the add field from calculation transformation.

**Which issue(s) does this PR fix?**:
Fixes #77186

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.

### CODE REVIEW

File: public/app/features/transformers/standardTransformers.ts [hunk 1]
```diff
@@ -4,7 +4,7 @@ import { config } from '@grafana/runtime';
 import { filterByValueTransformRegistryItem } from './FilterByValueTransformer/FilterByValueTransformerEditor';
 import { heatmapTransformRegistryItem } from './calculateHeatmap/HeatmapTransformerEditor';
 import { configFromQueryTransformRegistryItem } from './configFromQuery/ConfigFromQueryTransformerEditor';
-import { calculateFieldTransformRegistryItem } from './editors/CalculateFieldTransformerEditor';
+import { calculateFieldTransformRegistryItem } from './editors/CalculateFieldTransformerEditor/CalculateFieldTransformerEditor';
```
Comment (mdvictor) [inline public/app/features/transformers/standardTransformers.ts:7]: This is more of a naming nit: Maybe we can leave the dir as `CalculateFieldTransformer`, similar to how other transformer editors who have multiple components are named, so the path would be `'./editors/CalculateFieldTransformer/CalculateFieldTransformerEditor'`

**Review by mdvictor — APPROVED** [review]
Tested out, works and looks great!
