### PR TITLE
Search: Fix some minor UI issues

### LINKED ISSUE #35328: Search: Some minor UX issues
Feedback from @lukasztyrala 

* [ ] B) No spacing between cards sometimes? when in folder view for example I see no spacing between cards
* [ ] C) Folder icon alignment issue 

image

@Clarity-89 if you have time, the B) and C) should be easy?

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
 - Fix the missing margin between search list items
 - Align folder icon 
 - Fix search items height overflow
 - Fix regression for https://github.com/grafana/grafana/issues/31652 where custom class name wasn't passed to the Card
  
**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/35328

**Special notes for your reviewer**:

Before:
Screenshot 2021-06-07 at 17 01 48

After:
Screenshot 2021-06-08 at 15 13 16

### CODE REVIEW

File: public/app/features/search/components/ManageDashboards.tsx [hunk 1]
```diff
@@ -153,7 +153,9 @@ const getStyles = stylesFactory((theme: GrafanaTheme) => {
       display: flex;
       flex-direction: column;
       flex: 1;
-      margin-top: ${theme.spacing.xl};
+      height: 100%;
+      padding-top: ${theme.spacing.lg};
+      margin-top: -${theme.spacing.md};
```
Comment (Clarity-89) [inline public/app/features/search/components/ManageDashboards.tsx:158]: It seemed the easiest to use padding instead of margin and compensate for the margin from `.page-action-bar`, which was pushing the search items down. Couldn't find a working combination using just height and we need `height: 100%;` rule to render the virtualised lists.

Comment (thisisobate) [reply public/app/features/search/components/ManageDashboards.tsx:158]: ok...makes more sense. 👍

Comment (thisisobate) [inline public/app/features/search/components/ManageDashboards.tsx:158]: It seems the overflow behaviour still exists when you view it on a smaller screen. I would suggest you add more margin below...`margin-top: -${theme.spacing.xl}` .

**Review by thisisobate — CHANGES_REQUESTED** [review]
If you're going for the 8.0.1 milestone, I would suggest you don't add backport labels since we're in a code freeze for tomorrow's release.

Milestone 8.1.0 seems to be alot more safer given the current circumstance. 😀

File: public/app/features/search/components/ManageDashboards.tsx (hunk 1 above)
Comment (thisisobate) [reply public/app/features/search/components/ManageDashboards.tsx:158]: yeah...

**Comment by thisisobate** [comment]
It seems the overflow still shows...but a tiny amount. Is it necessary for us to look out for this tiny amount of detail? 😅
Screenshot 2021-06-07 at 16 15 20

File: public/app/features/search/components/ManageDashboards.tsx [hunk 2]
```diff
@@ -153,7 +153,9 @@ const getStyles = stylesFactory((theme: GrafanaTheme) => {
       display: flex;
       flex-direction: column;
       flex: 1;
-      margin-top: ${theme.spacing.xl};
+      height: 100%;
+      padding-top: ${theme.spacing.lg};
+      margin-top: -${theme.spacing.lg};
     `,
```
Comment (torkelo) [inline public/app/features/search/components/ManageDashboards.tsx:159]: this should not be needed, just set the parent wrapper to be:

display: flex
flex-direction: column;
height: 100%;

And then the child you want to take the remaining space (left after toolbar):
flex: 1 1 0;
min-height: 0;

This should

Comment (Clarity-89) [reply public/app/features/search/components/ManageDashboards.tsx]: Thanks, that worked, except `min-height: 0;` was breaking the layout, so removing it fixed the issue.

**Comment by Clarity-89** [comment]
> If you're going for the 8.0.1 milestone, I would suggest you don't add backport labels since we're in a code freeze for tomorrow's release.
> 
> Milestone 8.1.0 seems to be alot more safer given the current circumstance. 😀

There are no backport labels for this PR? Bug fixes generally go into patch releases, like 8.0.1.

**Review by thisisobate — APPROVED** [review]
LGTM!

**Comment by thisisobate** [comment]
> There are no backport labels for this PR? Bug fixes generally go into patch releases, like 8.0.1.
We can add backport labels but I think that should be done after the 8.0 release inorder to avoid breaking the release process.

**Review by torkelo — APPROVED** [review]
