### PR TITLE
Explore: Open new window when exploring panel metrics

### LINKED ISSUE #18308: Open new window when exploring pane metrics
**Steps to reproduce**:

Go to any pane and use the `explore` option.

**Actual Result**:

Grafana will switch the to the explore view with the current values in the current tab and it'll make back navigation a very difficult to do.

**Expected Result**

Allow to set (optionally?) this behavior to open the explore view in a new window.

**Environment**:
- Grafana version: Grafana v6.2.0 (5d16da7)
- Data source type & version: Prometheus
- User OS & Browser: Chrome 
- Others:

If this is something that It can be done, it's believed to be useful and doesn't present any primary problems I can give it a try to craft a PR.

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
This PR adds option to optionally open the explore view in a new window (cmd + click), as switching to the explore view was available only in the same window. This was done by adding href to additional menu items. As async function `getExploreUrl()` was used, we had to then propagate async in this PR. 

**Which issue(s) this PR fixes**:
Fixes #18308 

**Special notes for your reviewer**:
I would like to ask/discuss couple of options that I discovered during working on this.
The code in the current PR fixes the issue, however, I have one question regarding using just href and in that case, we wouldn't need explore function and just use:
```
async getAdditionalMenuItems() {
    const items = [];
    if (this.contextSrv.hasAccessToExplore() && this.datasource) {
      items.push({
        text: 'Explore',
        icon: 'gicon gicon-explore',
        shortcut: 'x',
        href: await getExploreUrl(this.panel.targets, this.datasource, this.datasourceSrv, this.timeSrv),
      });
    }
    return items;
  }
```

According to docs/experience of other developers href should always reload the page. But when I tested it in the network tab, href didn't reloaded the page. So I am not sure why is that and if we can rely on that (and therefore we wouldn't need explore function).

Network tab using href: 
image

Network tab using ng-onclick:
image

Can you please give me more insight on this? Thank you! 🙂

### CODE REVIEW

**Comment by torkelo** [comment]
> According to docs/experience of other developers href should always reload the page.  

This is almost never true in a single page application like a React or Angular app where the javascript router intercepts the link click and navigates to the new view without a full page reload. This is the primary benefit of single-page applications that they allow you to have pages & views that you can switch between without a full page reload. 

Switching to async call to getAddittionalMenuItems is a bit problematic as it's used by plugins and could break some of them. Need to figure out a backward-compatible way here.

File: public/app/features/panel/metrics_panel_ctrl.ts [hunk 1]
```diff
@@ -248,23 +248,27 @@ class MetricsPanelCtrl extends PanelCtrl {
...
         icon: 'gicon gicon-explore',
         shortcut: 'x',
+        href: await getExploreUrl(this.panel.targets, this.datasource, this.datasourceSrv, this.timeSrv),
       });
     }
     return items;
   }
 
-  async explore() {
+  async explore(e: any) {
```
Comment (torkelo) [inline public/app/features/panel/metrics_panel_ctrl.ts]: this action should not be needed if you have the href?

File: public/app/features/panel/metrics_panel_ctrl.ts [hunk 2]
```diff
@@ -248,23 +248,27 @@ class MetricsPanelCtrl extends PanelCtrl {
...
   }
 
-  getAdditionalMenuItems() {
+  async getAdditionalMenuItems() {
     const items = [];
     if (this.contextSrv.hasAccessToExplore() && this.datasource) {
       items.push({
         text: 'Explore',
-        click: 'ctrl.explore();',
+        click: 'ctrl.explore($event);',
```
Comment (torkelo) [inline public/app/features/panel/metrics_panel_ctrl.ts]: as mentioned below you do not need the click if you have a href

File: public/app/features/panel/metrics_panel_ctrl.ts (hunk 1 above)
Comment (ivanahuckova) [reply public/app/features/panel/metrics_panel_ctrl.ts]: Exactly! 🙂 Based on your message above regarding reloading, we don't need explore function at all, as href will be used.

**Comment by aocenas** [comment]
@torkelo 
> This is almost never true in a single page application like a React or Angular app where the javascript router intercepts the link click and navigates to the new view without a full page reload.

So is this standard angular behaviour when using `<a href="link">`? I thought that only happens when using `<a ng-href="link">`.

File: public/app/features/panel/metrics_panel_ctrl.ts (hunk 2 above)
Comment (ivanahuckova) [reply public/app/features/panel/metrics_panel_ctrl.ts]: 👍

**Comment by aocenas** [comment]
> Switching to async call to getAddittionalMenuItems is a bit problematic as it's used by plugins and could break some of them. Need to figure out a backward-compatible way here.

Not sure this is a problem, if plugin extends PanelCtrl and overrides the `getMenu` method with it's own non async method I think we can still await on it. Should just wrap the simple return value in promise. So basically [here](https://github.com/grafana/grafana/blob/c8498461a5ddb33e7862cc3c63bf2e454cd6559b/public/app/features/panel/panel_header.ts#L61) we can await for the `getMenu()` whether it is async or not.

**Comment by aocenas** [comment]
> Switching to async call to getAddittionalMenuItems is a bit problematic as it's used by plugins and could break some of them. Need to figure out a backward-compatible way here.

I think @ivanahuckova mentioned a version where we do not have to get rid of the explore() function but do something like:
```
async explore(e: any) {
    const url = await getExploreUrl(this.panel, this.panel.targets, this.datasource, this.datasourceSrv, this.timeSrv);
    if (url) {
      if (e.shiftKey || e.ctrlKey || e.metaKey) {
        window.open(url);
      } else {
        e.preventDefault();
        this.$timeout(() => this.$location.url(url));
      }
    }
  }
```
This would allow cmd-click to open a new window but you could not do right-click > open in new tab/window.

Other possibility would be to change the access to the datasource (which is the reason the url creation is async) to already have that somewhere beforehand but not sure right now where the change would need to be done.

**Comment by torkelo** [comment]
> This would allow cmd-click to open a new tab but you could not do right-click > open in new tab/window.

This is the default browser behavior for all links with hrefs, so no need to have a javascript function that does what the browser does already :) 

When I remove the click handler for this link I can CMD/CTRL+click to open in a new window (like I can with any link)

**Comment by torkelo** [comment]
> Not sure this is a problem, if plugin extends PanelCtrl and overrides the getMenu method with it's own non async method I think we can still await on it. Should just wrap the simple return value in promise. So basically here we can await for the getMenu() whether it is async or not.

Plugins that extend PanelCtrl do not override getMenu they override getAdditionalMenuItems. So we might have make this function return an optional promise.

 getAdditionalMenuItems(): AngularPanelLink[] | Promise<AngularPanelLink>

and check when we call it. Or create a getAdditionalMenuItemsAsync

**Comment by aocenas** [comment]
> This is the default browser behavior for all links with hrefs, so no need to have a javascript function that does what the browser does already :)

Yes but the href creation is async which is problematic as you mention. So if we use only the explore() onClick handler instead of the href then we could get at least the behaviour that I mentioned there.

> When I remove the click handler for this link I can CMD/CTRL+click to open in a new window (like I can with any link)

Yes but that is because the async is propagated in this PR but as you mention that may break some plugins.

**Comment by aocenas** [comment]
> and check when we call it. Or create a getAdditionalMenuItemsAsync

Well in that case we do not even need to check it actually. `await getAdditionalMenuItems` should work whether it returns promise or not.

**Comment by torkelo** [comment]
> Yes but that is because the async is propagated in this PR but as you mention that may break some plugins.

Think we can find a backward-compatible way to support async here, feels more elegant than having to replicate native browser click behavior

**Comment by ivanahuckova** [comment]
Thank you Torkel and Andrej! I have removed explore() function, as we are not going to use it anymore. And we are going to use href and native browser click behaviour. All tests are passing, functionality works.

> Well in that case we do not even need to check it actually. `await getAdditionalMenuItems` should work whether it returns promise or not.

Does it mean that there are no more changes necessary, as it should work with plugins as well?

**Review by torkelo — APPROVED** [review]
This look good, confirmed that this does not break existing plugins that have override and create a non async getAdditionalMenuItems function.

**Review by aocenas — APPROVED** [review]
