### PR TITLE
Alerting: Fix image embed in email template.

### LINKED ISSUE #50315: Unified alerting screenshot rendering not works
Hey guys,

I tried to use the image rendering for unified alerting. I read that you built in the rendering for unified alerting in the v9 beta version from grafana. 

I enabled the screenshot rendering with the environment variable GF_UNIFIED_ALERTING_SCREENSHOTS_ENABLED. Logfile confirm this action:
`level=info msg="Config overridden from Environment variable" var="GF_UNIFIED_ALERTING_SCREENSHOTS_ENABLED=true" `

No idea, why rendering not works. I can see the call in grafana log, but there is no image in the alerting message:
`level=debug msg="calling remote rendering service" url=http://renderer:8081/render/version`

Any idea?

**Environment**:
- Grafana version: docker grafana/grafana:9.0.0-beta2
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Docker Container
- Grafana plugins: Default
- Contact Point: Mail
- Image Store: No external image store
- Others: External Rendering Service

### PR DESCRIPTION
**Pull request by joeblubaugh**
The ng_alert_notification email template did not include templating for
linked or embedded images. This change updates that.

Additionally, this change supports embedding an image for each alert in
an email batch.

Fixes #50315

### CODE REVIEW

File: pkg/services/ngalert/notifier/channels/email.go [hunk 1]
```diff
@@ -108,6 +106,25 @@ func (en *EmailNotifier) Notify(ctx context.Context, as ...*types.Alert) (bool,
 		en.log.Debug("failed to parse external URL", "url", en.tmpl.ExternalURL.String(), "err", err.Error())
 	}
 
+	// Extend alerts data with images, if available.
+	var embeddedFiles []string
```
Comment (joeblubaugh) [inline pkg/services/ngalert/notifier/channels/email.go:110]: This change links or attaches an image for each alert that has an image.

File: public/emails/ng_alert_notification.html [hunk 2]
```diff
@@ -210,6 +210,21 @@
 {{Subject .Subject "{{.Title}}"}}
 
 {{ define "alert" }}
+
+  {{if ne .ImageURL "" }}
```
Comment (joeblubaugh) [inline public/emails/ng_alert_notification.html:214]: This adds a row just after the subject, before the value string. See included image in this comment.
Screenshot 2022-06-08 at 12 21 38 PM

File: public/emails/ng_alert_notification.html [hunk 3]
```diff
@@ -210,6 +210,21 @@
...
+       <img src="{{.ImageURL}}" class="fluid-centered" alt="Alerting Panel" style="outline: none !important; text-decoration: none !important; -ms-interpolation-mode: bicubic; width: auto; clear: both; display: block; border: 0;" align="left" />
+		</td>
+	</tr>
+  {{end}}
+  {{if ne .EmbeddedImage "" }}
+  <tr style="vertical-align: top; padding: 0;" align="left">
+    <td colspan="2" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; color: #222222; font-family: 'Open Sans', 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-weight: normal; line-height: 19px; font-size: 14px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; margin: 0; padding: 24px 0 0;" align="left" valign="top">
+       <img src="cid:{{.EmbeddedImage}}" alt="Alerting Chart Attached Below" style="outline: none !important; text-decoration: none !important; -ms-interpolation-mode: bicubic; width: auto; clear: both; display: block; border: 0;" align="left" />
```
Comment (joeblubaugh) [inline public/emails/ng_alert_notification.html:224]: Most webmail clients don't directly display `cid` image sources, hence the alt text "Alerting Chart Attached Below"

File: pkg/services/ngalert/notifier/channels/email.go [hunk 4]
```diff
@@ -123,34 +140,13 @@ func (en *EmailNotifier) Notify(ctx context.Context, as ...*types.Alert) (bool,
...
-	_ = withStoredImage(ctx, en.log, en.images,
-		func(index int, image *ngmodels.Image) error {
-			if image == nil {
-				return nil
-			}
-
-			if len(image.URL) != 0 {
-				cmd.Data["ImageLink"] = image.URL
-			} else if len(image.Path) != 0 {
-				file, err := os.Stat(image.Path)
```
Comment (joeblubaugh) [inline pkg/services/ngalert/notifier/channels/email.go:143]: I should go back to doing the os.Stat thing here instead of splitting the path and waiting for the email code to fail to open the file.

File: public/emails/ng_alert_notification.html (hunk 3 above)
Comment (gillesdemey) [reply public/emails/ng_alert_notification.html:224]: TIL about `cid:` image links :D

**Review by gotjosh — APPROVED** [review]
LGTM

File: public/emails/ng_alert_notification.html (hunk 3 above)
Comment (grobinson-grafana) [inline public/emails/ng_alert_notification.html:224]: Is this the original path of the file on disk?

Comment (grobinson-grafana) [reply public/emails/ng_alert_notification.html:224]: Does that include the path on disk? What I meant with the original comment is that do we want to make the full path visible in the HTML email, or is this now just the filename?

Comment (joeblubaugh) [reply public/emails/ng_alert_notification.html:224]: Our email sending code requires a "full path" to order to find attachment files, and that becomes the ID for the attachment, so I don't think I can get around including the full path name in the template variable.
