### PR TITLE
Fix: Change getExistingDashboardByTitleAndFolder to get dashboard by title, not slug

### LINKED ISSUE #69301: API: dashbaords db overwrite: saving dashboard failed: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title
### 
# What went wrong?

I had existing dashboard from previous versions. They were generated using Python, then uploaded via API to grafana.

Recently our Grafana was updated to newer version, and script stopped working.

I am getting error 500, with body: `{"message":"Failed to save dashboard","traceID":""}`

Looking at grafana logs I see:

```
logger=context userId=9 orgId=1 uname=sa-autogen-1-wb-dashboard-generator t=2023-05-31T09:59:19.536952278Z
  level=error msg="Failed to save dashboard"
  error="saving dashboard failed: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title"
  remote_addr=10.1.1.1 traceID=
logger=context userId=9 orgId=1 uname=sa-autogen-1-wb-dashboard-generator t=2023-05-31T09:59:19.536996697Z
  level=error msg="Request Completed"
  method=POST path=/api/dashboards/db status=500
  remote_addr=10.1.1.1 time_ms=29 duration=29.083281ms size=51 referer= handler=/api/dashboards/db
```
****

### 
# How do we reproduce it?

```
$ cat >request.json <<-EOF
{"overwrite":true,"dashboard":
{
  "__inputs": [],
  "annotations": {
    "list": []
  },
  "description": "Autogenerated",
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "hideControls": false,
  "id": null,
  "links": [],
  "panels": [
  ],
  "refresh": "5m",
  "rows": [],
  "schemaVersion": 12,
  "sharedCrosshair": true,
  "style": "dark",
  "tags": [
    "ixc"
  ],
  "templating": {
    "list": [
    ]
  },
  "time": {
    "from": "now-3h",
    "to": "now"
  },
  "timepicker": {
    "hidden": false,
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "utc",
  "title": "my_dashboard3",
  "uid": null,
  "version": 0
}
}
EOF
$
```

```
$ curl \
              --request POST \
              --header "Accept: application/json" \
              --header "Content-Type: application/json" \
              --header "Authorization: Bearer ${MY_GRAFANA_API_KEY}" \
              --data "@request.json" \
              --write-out '\nHTTP status: %{http_code}\n' \
              "https://grafana.my.example.com/api/dashboards/db"
```

Note, this only fails, if the dashboard existed before in pre-v9.5.2

Step to reproduce would be to run v9.4.x, run above snippet. Upgrade to v9.5.2, then run above again.

### 
# What Grafana version are you using?

v9.5.2 (cfcea75916)

### 
### Grafana Platform?

Kubernetes, OpenShift on bare metal

### Is this a Regression?

Yes. It was working in 9.4.x

### Workaround

Deleting dashboard via UI, and reuploading solves the problem. Only issue with that is that URL is now new and existing links and bookmarks are broken.

### PR DESCRIPTION
**Pull request by yangkb09**
**What is this feature?**

Change `getExistingDashboardByTitleAndFolder` to get dashboard by title, not slug.

**Why do we need this feature?**

There is an issue where provisioned dashboards with underscores fail to update via the /api/dashboards/db endpoint. This bug affecting dashboards whose slugs were created with underscores.

**Which issue(s) does this PR fix?**:
Fixes [#6068](https://github.com/grafana/support-escalations/issues/6068)
Fixes #69301

### CODE REVIEW

**Review by papagian — APPROVED** [review]

**Comment by tolzhabayev** [comment]
Wdyt about adding a test to https://github.com/grafana/grafana/blob/main/pkg/services/dashboards/database/database_test.go to cover this scenario?

File: pkg/services/dashboards/database/database.go [hunk 1]
```diff
@@ -388,12 +390,12 @@ func getExistingDashboardByIDOrUIDForUpdate(sess *db.Session, dash *dashboards.D
...
 	isParentFolderChanged bool) (bool, error) {
 	var existing dashboards.Dashboard
-	exists, err := sess.Where("org_id=? AND slug=? AND (is_folder=? OR folder_id=?)", dash.OrgID, dash.Slug,
+	exists, err := sess.Where("org_id=? AND title=? AND (is_folder=? OR folder_id=?)", dash.OrgID, dash.Title,
 		dialect.BooleanStr(true), dash.FolderID).Get(&existing)
 	if err != nil {
 		return isParentFolderChanged, fmt.Errorf("SQL query for existing dashboard by org ID or folder ID failed: %w", err)
 	}
-
+	fmt.Printf("dashboard title exists? %+v %v", dash, exists)
```
Comment (papagian) [inline pkg/services/dashboards/database/database.go:398]: nit, remove this print

File: pkg/services/dashboards/database/database_test.go [hunk 2]
```diff
@@ -639,6 +639,41 @@ func TestIntegrationDashboard_Filter(t *testing.T) {
...
+	quotaService := quotatest.New(false, nil)
+	dashboardStore, err := ProvideDashboardStore(sqlStore, cfg, testFeatureToggles, tagimpl.ProvideService(sqlStore, cfg), quotaService)
+	require.NoError(t, err)
+	insertTestDashboard(t, dashboardStore, "Apple", 1, 0, false)
+	t.Run("Should be able to get dashboard with existing name", func(t *testing.T) {
+		err = sqlStore.WithDbSession(context.Background(), func(sess *sqlstore.DBSession) error {
+			_, err = getExistingDashboardByTitleAndFolder(sess, &dashboards.Dashboard{Title: "Apple", OrgID: 1}, sqlStore.GetDialect(), false, false)
+			return err
+		})
+		require.Error(t, err)
```
Comment (papagian) [inline pkg/services/dashboards/database/database_test.go:655]: we want to test [this](https://github.com/grafana/grafana/blob/b80c20f80ba0d0de223d81e912c9fe57224c72c9/pkg/services/dashboards/database/database.go#L417) specific case (successfully retrieving an existing dashboard by title and org):
so you can better check for the specific `dashboards.ErrDashboardWithSameNameInFolderExists` error.

File: pkg/services/dashboards/database/database_test.go [hunk 3]
```diff
@@ -639,6 +639,41 @@ func TestIntegrationDashboard_Filter(t *testing.T) {
...
+	})
+
+	t.Run("Should not be able to get dashboard with non-existing name", func(t *testing.T) {
+		err = sqlStore.WithDbSession(context.Background(), func(sess *sqlstore.DBSession) error {
+			_, err = getExistingDashboardByTitleAndFolder(sess, &dashboards.Dashboard{Title: "Beta"}, sqlStore.GetDialect(), false, false)
```
Comment (papagian) [inline pkg/services/dashboards/database/database_test.go:660]:
```suggestion
			_, err = getExistingDashboardByTitleAndFolder(sess, &dashboards.Dashboard{Title: "Beta", OrgID: 1}, sqlStore.GetDialect(), false, false)
```
we want to test [this](https://github.com/grafana/grafana/blob/b80c20f80ba0d0de223d81e912c9fe57224c72c9/pkg/services/dashboards/database/database.go#L421) specific case (no error if no dashboard with this title exists) but we have to set the org as well otherwise the [query](https://github.com/grafana/grafana/blob/b80c20f80ba0d0de223d81e912c9fe57224c72c9/pkg/services/dashboards/database/database.go#L393) will not return any results regardless of the title we pass.

File: pkg/services/dashboards/database/database_test.go [hunk 4]
```diff
@@ -639,6 +639,41 @@ func TestIntegrationDashboard_Filter(t *testing.T) {
...
+			return err
+		})
+		require.NoError(t, err)
+	})
+
+	t.Run("Should be able to get dashboard with existing name in a folder", func(t *testing.T) {
+		savedFolder := insertTestDashboard(t, dashboardStore, "test dash folder", 1, 0, true, "prod", "webapp")
+		savedDash := insertTestDashboard(t, dashboardStore, "test dash", 1, savedFolder.ID, false, "prod", "webapp")
+		err = sqlStore.WithDbSession(context.Background(), func(sess *sqlstore.DBSession) error {
+			_, err = getExistingDashboardByTitleAndFolder(sess, savedDash, sqlStore.GetDialect(), false, false)
```
Comment (papagian) [inline pkg/services/dashboards/database/database_test.go:670]:
```suggestion
			_, err = getExistingDashboardByTitleAndFolder(sess, &dashboards.Dashboard{Title: savedDash.Title, FolderID: savedFolder.ID, OrgID: 1}, sqlStore.GetDialect(), false, false)
```
same as the 1st test, we want to test [this](https://github.com/grafana/grafana/blob/b80c20f80ba0d0de223d81e912c9fe57224c72c9/pkg/services/dashboards/database/database.go#L417) specific case (successfully retrieving an existing dashboard under a folder by title and folder identifier):
so you can better pass a `*dashboards.Dashboard` where only the org, title and folder identifier are set: `savedDash` has other fields set (eg slug)
also, same as above better to check for the specific `dashboards.ErrDashboardWithSameNameInFolderExists` error.

File: pkg/services/dashboards/database/database.go [hunk 5]
```diff
@@ -299,6 +300,7 @@ func (d *dashboardStore) Count(ctx context.Context, scopeParams *quota.ScopePara
 }
 
 func getExistingDashboardByIDOrUIDForUpdate(sess *db.Session, dash *dashboards.Dashboard, dialect migrator.Dialect, overwrite bool) (bool, error) {
+	spew.Dump("HELLO!")
```
Comment (papagian) [inline pkg/services/dashboards/database/database.go:303]: nit: remove this

File: pkg/services/dashboards/database/database_test.go [hunk 6]
```diff
@@ -639,6 +639,41 @@ func TestIntegrationDashboard_Filter(t *testing.T) {
...
 
+func TestGetExistingDashboardByTitleAndFolder(t *testing.T) {
+	sqlStore := db.InitTestDB(t)
+	cfg := setting.NewCfg()
+	cfg.IsFeatureToggleEnabled = func(key string) bool { return false }
+	quotaService := quotatest.New(false, nil)
+	dashboardStore, err := ProvideDashboardStore(sqlStore, cfg, testFeatureToggles, tagimpl.ProvideService(sqlStore, cfg), quotaService)
+	require.NoError(t, err)
+	insertTestDashboard(t, dashboardStore, "Apple", 1, 0, false)
+	t.Run("Should be able to get dashboard with existing name in root directory", func(t *testing.T) {
```
Comment (danielthedm) [inline pkg/services/dashboards/database/database_test.go:650]: Can we rename this test to "Finds a dashboard with existing name in root directory and throws DashboardWithSameNameInFolderExists error"

File: pkg/services/dashboards/database/database_test.go [hunk 7]
```diff
@@ -639,6 +639,41 @@ func TestIntegrationDashboard_Filter(t *testing.T) {
...
+
+	t.Run("Should not be able to get dashboard with non-existing name in root directory", func(t *testing.T) {
+		err = sqlStore.WithDbSession(context.Background(), func(sess *sqlstore.DBSession) error {
+			_, err = getExistingDashboardByTitleAndFolder(sess, &dashboards.Dashboard{Title: "Beta"}, sqlStore.GetDialect(), false, false)
+			return err
+		})
+		require.NoError(t, err)
+	})
+
+	t.Run("Should be able to get dashboard with existing name in a folder", func(t *testing.T) {
```
Comment (danielthedm) [inline pkg/services/dashboards/database/database_test.go:666]: Title could be "Returns no error when dashboard does not exist in folder"

File: pkg/services/dashboards/database/database_test.go (hunk 3 above)
Comment (danielthedm) [reply pkg/services/dashboards/database/database_test.go:660]: "Returns no error when dashboard does not exist in root directory"

File: pkg/services/dashboards/database/database.go [hunk 8]
```diff
@@ -385,15 +385,15 @@ func getExistingDashboardByIDOrUIDForUpdate(sess *db.Session, dash *dashboards.D
 	return isParentFolderChanged, nil
 }
 
+// Returns boolean on whether the parent folder changed. Error is if the dashboard already exists.
```
Comment (yangkb09) [inline pkg/services/dashboards/database/database.go:388]: thoughts on this documentation comment?

File: pkg/services/dashboards/database/database_test.go [hunk 9]
```diff
@@ -639,6 +639,41 @@ func TestIntegrationDashboard_Filter(t *testing.T) {
...
+	})
+
+	t.Run("Finds a dashboard with existing name in specific folder and throws DashboardWithSameNameInFolderExists error", func(t *testing.T) {
+		savedFolder := insertTestDashboard(t, dashboardStore, "test dash folder", 1, 0, true, "prod", "webapp")
+		savedDash := insertTestDashboard(t, dashboardStore, "test dash", 1, savedFolder.ID, false, "prod", "webapp")
+		err = sqlStore.WithDbSession(context.Background(), func(sess *sqlstore.DBSession) error {
+			_, err = getExistingDashboardByTitleAndFolder(sess, &dashboards.Dashboard{Title: savedDash.Title, FolderID: savedFolder.ID, OrgID: 1}, sqlStore.GetDialect(), false, false)
+			return err
+		})
+		require.ErrorIs(t, err, dashboards.ErrDashboardWithSameNameInFolderExists)
```
Comment (yangkb09) [inline pkg/services/dashboards/database/database_test.go:673]: i believe this test is also expecting `dashboards.ErrDashboardWithSameNameInFolderExists`, correct? since we expect to find the dash we saved

File: pkg/services/dashboards/database/database.go (hunk 8 above)
Comment (danielthedm) [reply pkg/services/dashboards/database/database.go:388]: Linting may fail on this in CI.  If not don't want to block shipping this but usually it's best practice to document functions like this:
`// getExistingDashboardByTitleAndFolder returns a boolean (on whether the parent folder changed) and an error for if the dashboard already exists.`

Comment (yangkb09) [reply pkg/services/dashboards/database/database.go:388]: ahhh, noted - thank you. will implement the comment like that

File: pkg/services/dashboards/database/database_test.go (hunk 9 above)
Comment (danielthedm) [reply pkg/services/dashboards/database/database_test.go:673]: The variable naming `savedDash` here is confusing it's not actually saved to the dashboardStore.  This shouldn't return an error.

File: pkg/services/dashboards/database/database_test.go [hunk 10]
```diff
@@ -639,6 +639,41 @@ func TestIntegrationDashboard_Filter(t *testing.T) {
...
+	insertTestDashboard(t, dashboardStore, "Apple", 1, 0, false)
+	t.Run("Finds a dashboard with existing name in root directory and throws DashboardWithSameNameInFolderExists error", func(t *testing.T) {
+		err = sqlStore.WithDbSession(context.Background(), func(sess *sqlstore.DBSession) error {
+			_, err = getExistingDashboardByTitleAndFolder(sess, &dashboards.Dashboard{Title: "Apple", OrgID: 1}, sqlStore.GetDialect(), false, false)
+			return err
+		})
+		require.ErrorIs(t, err, dashboards.ErrDashboardWithSameNameInFolderExists)
+	})
+
+	t.Run("Returns no error when dashboard does not exist in a specific folder", func(t *testing.T) {
```
Comment (danielthedm) [inline pkg/services/dashboards/database/database_test.go:658]: We aren't specifying a folder here, this will default to the root folder.

Comment (yangkb09) [reply pkg/services/dashboards/database/database_test.go:658]: oops my mistake, fixing now

File: pkg/services/dashboards/database/database_test.go (hunk 9 above)
Comment (danielthedm) [reply pkg/services/dashboards/database/database_test.go:673]: That's correct.

**Review by danielthedm — APPROVED** [review]
LGTM.  Nit: we could add a test to expect no error when a dashboard doesn't exist in a specific folder but not blocking.
