### PR TITLE
Dashboard Scene:  Fix snapshots not displaying variables values 

### LINKED ISSUE #85654: Snapshots: Variables not/wrongly displayed when rendered with Scenes
### What happened?

When generating and rendering a snapshot with Scenes feature toggles, the variables are either not displayed at all or wrongly displayed (multi variables show "All" even if this is not what was selected in the dashboard).

### What did you expect to happen?

The snapshot variables to be rendered correctly. 

### Did this work before?

Yes, it's working without Scenes feature toggles.

### How do we reproduce it?

1. Create a dashboard with variables. For example, this one using the devenv postgres data source:
<details>
<summary>dashboard.json</summary>

```
{
  "__inputs": [
    {
      "name": "DS_GDEV-POSTGRES",
      "label": "gdev-postgres",
      "description": "",
      "type": "datasource",
      "pluginId": "grafana-postgresql-datasource",
      "pluginName": "PostgreSQL"
    },
    {
      "name": "DS_TESTDATA",
      "label": "TestData",
      "description": "",
      "type": "datasource",
      "pluginId": "grafana-testdata-datasource",
      "pluginName": "TestData"
    }
  ],
  "__elements": {},
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "11.1.0-pre"
    },
    {
      "type": "datasource",
      "id": "grafana-postgresql-datasource",
      "name": "PostgreSQL",
      "version": "1.0.0"
    },
    {
      "type": "datasource",
      "id": "grafana-testdata-datasource",
      "name": "TestData",
      "version": "11.1.0-pre"
    },
    {
      "type": "panel",
      "id": "table",
      "name": "Table",
      "version": ""
    },
    {
      "type": "panel",
      "id": "timeseries",
      "name": "Time series",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "panels": [
    {
      "datasource": {
        "type": "grafana-postgresql-datasource",
        "uid": "${DS_GDEV-POSTGRES}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "align": "auto",
            "cellOptions": {
              "type": "auto"
            },
            "inspect": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "cellHeight": "sm",
        "footer": {
          "countRows": false,
          "fields": "",
          "reducer": [
            "sum"
          ],
          "show": false
        },
        "showHeader": true
      },
      "pluginVersion": "11.1.0-pre",
      "targets": [
        {
          "datasource": {
            "type": "grafana-postgresql-datasource",
            "uid": "${DS_GDEV-POSTGRES}"
          },
          "editorMode": "builder",
          "format": "table",
          "rawSql": "SELECT hostname FROM grafana_metric WHERE datacenter = '${datacenter}' LIMIT 50 ",
          "refId": "A",
          "sql": {
            "columns": [
              {
                "parameters": [
                  {
                    "name": "hostname",
                    "type": "functionParameter"
                  }
                ],
                "type": "function"
              }
            ],
            "groupBy": [
              {
                "property": {
                  "type": "string"
                },
                "type": "groupBy"
              }
            ],
            "limit": 50,
            "whereJsonTree": {
              "children1": [
                {
                  "id": "99abab88-4567-489a-bcde-f18e7b389577",
                  "properties": {
                    "field": "datacenter",
                    "fieldSrc": "field",
                    "operator": "equal",
                    "value": [
                      "${datacenter}"
                    ],
                    "valueSrc": [
                      "value"
                    ],
                    "valueType": [
                      "text"
                    ]
                  },
                  "type": "rule"
                }
              ],
              "id": "ba8aab8a-0123-4456-b89a-b18e7b34f2dc",
              "type": "group"
            },
            "whereString": "datacenter = '${datacenter}'"
          },
          "table": "grafana_metric"
        }
      ],
      "title": "Datacenter ${datacenter}",
      "type": "table"
    },
    {
      "datasource": {
        "type": "grafana-testdata-datasource",
        "uid": "${DS_TESTDATA}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 24,
        "x": 0,
        "y": 8
      },
      "id": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "maxHeight": 600,
          "mode": "single",
          "sort": "none"
        }
      },
      "repeat": "query",
      "repeatDirection": "h",
      "targets": [
        {
          "datasource": {
            "type": "grafana-testdata-datasource",
            "uid": "${DS_TESTDATA}"
          },
          "refId": "A",
          "scenarioId": "random_walk",
          "seriesCount": 1
        }
      ],
      "title": "Panel $hostname",
      "type": "timeseries"
    }
  ],
  "schemaVersion": 39,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timeRangeUpdatedDuringEditOrView": false,
  "timepicker": {},
  "timezone": "",
  "title": "Variables Test",
  "uid": "d4492fa5-634b-4933-b682-dab733e45d90",
  "version": 21,
  "weekStart": ""
}
```

</details>

2. Create a snapshot
3. Access the snapshot on an anonymous browser. This is what you should see: 
image

This was reproduced using only the test DS as well. 

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: main
OS: Windows
Browser: Chrome

### Grafana platform?

Other

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by axelavargas**
**What is this PR doing ?**
It fixes an issue for snapshots with template variables.  The variables were either not displayed at all or wrongly displayed.

**The issue** In snapshots, we only store the current variable value, and don't store `options` for variables such as `queries, datasources, ...` . The problem was that the Scenes implementation does validate `options` against the `current` variable value, if the `current` value did not exist, it cleared up that value. 

I created a new `SnapshotVariable`  and made some adjustments in the scenes repository ([PR](https://github.com/grafana/scenes/pull/781)) to support read-only for variables.
However, for `adhoc` variable types, I didn't use the snapshotVariable, as it was complex to add the same behavior to the custom snapshot variable, and the filters were not available.

SnapshotVariables

**How to test this PR?**
Create a snapshot with variables from different types and double-check check everything is working.

**Which issue(s) does this PR fix?**:

Fixes #85654

- [x] Add new `snapshot` type to Variable Type 
- [x] Remove console.logs
- [x] Add unit test for extra case 
- [x]  Extract variable logic outside of transformSaveModelToScene it was getting very confusing

### CODE REVIEW

File: public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts [hunk 1]
```diff
@@ -297,6 +321,25 @@ export function createDashboardSceneFromDashboardModel(oldModel: DashboardModel)
   return dashboardScene;
 }
 
+export function createVariableForSnapshots(variable: TypedVariableModel): SceneVariable {
+  const snapshotVariable = new SnapshotVariable({
```
Comment (torkelo) [inline public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts:325]: @axelavargas think you missed adding this file :)

Comment (axelavargas) [reply public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts:325]: oh yes, before I was implemeting this on the Scenes repository. I moved the implementation here :)

Comment (dprokop) [reply public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts:325]: @axelavargas - I've just pushed import fix, otherwise this was not working :)

Anyways - seems like most of the variables are working now in snapshots, but not the ad hoc filters, the read only variable is empty even tho I have snapshoted a dashboard with filters applied.

Comment (axelavargas) [reply public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts:325]: Thanks @dprokop 😄 , yes, I am working on adding support for ad-hoc filters, intervals and textBox variables :)

Comment (axelavargas) [reply public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts]: @dprokop I have made a refactor to support `ad-hoc, intervals, groupBy, and textBox` variables. Displaying the variables works as expected, however, I see an issue with the URL and ad-hoc variables, the URL does not contain the value of filters 🤔.

image

I am unsure if this is related to my changes, will investigate. But for now, can you check the approach of this PR 😄.

Comment (dprokop) [reply public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts]: @axelavargas - i think it's because filters have a custom sync handler: https://github.com/grafana/scenes/blob/main/packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx#L116

Comment (axelavargas) [reply public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts]: @dprokop I managed to fix the issue with ad-hoc filters. I took the approach of using the `AdHocFiltersVariable` from scenes and adding the `read-only` prop to make it work.

File: public/app/features/dashboard-scene/utils/utils.ts [hunk 2]
```diff
@@ -261,3 +263,43 @@ export function getLibraryPanel(vizPanel: VizPanel): LibraryVizPanel | undefined
   }
   return;
 }
+
+export function createVariableForSnapshots(variable: TypedVariableModel): SceneVariable {
```
Comment (ivanortegaalba) [inline public/app/features/dashboard-scene/utils/utils.ts:267]: I'd add some tests for this one. WDYT?

File: packages/grafana-schema/src/raw/dashboard/x/dashboard_types.gen.ts [hunk 3]
```diff
@@ -349,7 +349,7 @@ export type DashboardLinkType = ('link' | 'dashboards');
  * `custom`: Define the variable options manually using a comma-separated list.
  * `system`: Variables defined by Grafana. See: https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#global-variables
  */
-export type VariableType = ('query' | 'adhoc' | 'groupby' | 'constant' | 'datasource' | 'interval' | 'textbox' | 'custom' | 'system');
+export type VariableType = ('query' | 'adhoc' | 'groupby' | 'constant' | 'datasource' | 'interval' | 'textbox' | 'custom' | 'system' | 'snapshot');
```
Comment (ivanortegaalba) [inline packages/grafana-schema/src/raw/dashboard/x/dashboard_types.gen.ts:352]: Do we have any way to skip this variable from here? 

The goal for the schema is to represent a shareable save model, and the `snapshot` variable is just a runtime variable used to represent read-only variable data. Same for the `system` var.

Do we have any way to skip it from here?

**Review by ivanortegaalba — COMMENTED** [review]
It looks good to me @axelavargas! I added some comments 😄

File: yarn.lock
[the remark this answers is not in the document]
Comment (axelavargas) [reply yarn.lock:1]: oh yes! probably during a merge,good cath ❤️

File: packages/grafana-schema/src/raw/dashboard/x/dashboard_types.gen.ts (hunk 3 above)
Comment (axelavargas) [reply packages/grafana-schema/src/raw/dashboard/x/dashboard_types.gen.ts:352]: 🤔 I didn't find a way to skip it from here

File: public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts [hunk 4]
```diff
@@ -196,22 +197,59 @@ export function createDashboardSceneFromDashboardModel(oldModel: DashboardModel,
...
+          }
+        })
+        // TODO: Remove filter
+        // Added temporarily to allow skipping non-compatible variables
+        .filter((v): v is SceneVariable => Boolean(v));
+
+      variables = new SceneVariableSet({
+        variables: variableObjects,
+      });
+    }
```
[the remark this answers is not in the document]
Comment (axelavargas) [reply public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts]: @ivanortegaalba I did a small refactor on this part, it was becoming quite big and confusing 😄.

**Review by evictorero — APPROVED** [review]
I've tested it, and it works as expected. I plan to use these variables to render inside a report. 
I don't want to block this PR since Scenes Snapshots are broken at this moment. 
Is it worth changing the naming to something related to the nature of these variables, like "read-only" mode, instead of using the Snapshots prefix?
In the end, these changes attempt to render template variables in read-only mode they shouldn't be dependent of Snapshots.
