### PR TITLE
TableNG: Filter and sort sub tables

### LINKED ISSUE #104012: TableNG: Sub table filtering/sorting
We need to correctly filter the sub tables at the parent level. Sub table level sorting will come in a future PR.

### LINKED ISSUE #104295: TableNG: Sub table filtering crashes the panel

### PR DESCRIPTION
**Pull request by alexjonspencer1**
## What does this PR do? 📓 

This PR is a primary fix for sorting/filtering for sub tables in TableNG. Sorting at the header parent level sorts the parent rows correctly and also correctly nests its sub table. Filtering at the header parent level sorts at the parent row level, and correctly nests its sub table.

This **does not** fix the actual sorting of the sub table rows themselves. That will be a follow-up PR.

Fixes #104012
Fixes #104295

Can test with: [Debug_ Panel Title __ 2025-01-28 17_52_52-1745344727814.json](https://github.com/user-attachments/files/19854832/Debug_.Panel.Title.__.2025-01-28.17_52_52-1745344727814.json)

#### Before

https://github.com/user-attachments/assets/91595582-3c94-4dd6-bb9b-a3debd0bbc8f

#### After

https://github.com/user-attachments/assets/eb07777c-3b18-4728-b290-4618055ee19e

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/TableNG/TableNG.tsx [hunk 1]
```diff
@@ -285,6 +278,13 @@ export function TableNG(props: TableNGProps) {
       return rows;
     }
 
+    // Helper function to get displayed value
+    const getDisplayedValue = (row: TableRow, key: string) => {
+      const field = props.data.fields.find((field) => field.name === key)!;
+      const displayedValue = formattedValueToString(field.display!(row[key]));
+      return displayedValue;
+    };
+
```
Comment (alexjonspencer1) [inline packages/grafana-ui/src/components/Table/TableNG/TableNG.tsx:287]: Scoping this to `filteredRows` as it's the only place it's used.

**Review by adela-almasan — APPROVED** [review]
