### PR TITLE
Search: Safari UI fixes

### LINKED ISSUE #24516: Search: Dashboard results not visible in list view on Safari
**What happened**:
When switching from Folder to List view in manage dashboards, on Safari, the results are not shown:

Screenshot 2020-05-11 at 14 42 54

**What you expected to happen**:
The dashboard results should be visible in the List view. 

**How to reproduce it (as minimally and precisely as possible)**:
- Go to `/dashboards`
- Switch to List view
- No dashboards are shown

**Environment**:
- Grafana version: 7.0.0-beta3
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: MacOS Catalina, Safari Version 13.1 (15609.1.20.111.8)
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
Fix UI issues on Safari, mainly the issues with `AutoSizer`:
- Fix search results not displayed in manage dashboards List view
- Fix Data not displayed in Drawer
- Fix options layout for Select
- Fix folder edit permissions

**Which issue(s) this PR fixes**:

Fixes #24516, #24513

**Special notes for your reviewer**:

### CODE REVIEW

File: packages/grafana-ui/src/components/Select/getSelectStyles.ts [hunk 1]
```diff
@@ -22,6 +22,7 @@ export const getSelectStyles = stylesFactory((theme: GrafanaTheme) => {
       display: flex;
       align-items: center;
       flex-direction: row;
+      flex-shrink: 0;
```
Comment (torkelo) [inline packages/grafana-ui/src/components/Select/getSelectStyles.ts:25]: What does this do? does select still support smaller width than the value? (for example, select a data source with really long name in data source picker)

**Review by torkelo — APPROVED** [review]
LGTM, but not 100% sure on the Select shrink option, have you tested Select on different views?

File: packages/grafana-ui/src/components/Select/getSelectStyles.ts (hunk 1 above)
Comment (Clarity-89) [reply packages/grafana-ui/src/components/Select/getSelectStyles.ts:25]: It prevents the Select options from being squished vertically. Another option is to remove `display: flex` and default to `block`, but I guess it's there for a reason.

Tested with a few Selects and didn't notice any issues. 


Before:
Screenshot 2020-05-12 at 11 22 11
After:
Screenshot 2020-05-12 at 11 25 38
