### PR TITLE
Calculations: Update First * and Last * reducers to exclude NaNs

### LINKED ISSUE #59862: Corrected NaN behaviour on histogram_quantile causes "last non-null value" to not work as expected
In Grafana < 9.3 we see the following behaviour:

histogram_quantile on a metric which buckets do not containing any data, returns null values

image

This is actually wrong as per Prometheus standard

If `b` has 0 observations, `NaN` is returned. For `φ < 0`, `-Inf` is returned. For `φ > 1`, `+Inf` is returned. For `φ = NaN`, `NaN` is returned.

Which seems to be fixed or at least changed in 9.3**?**  As we see the following behaviour in **Grafana 9.3**

image

Which is by all means "good" yet it breaks the functionally of  "last *" - filtering out the last non-null value.

image

---

My suggestion or expectation is that "last *" _also_ ignores NaN and show the last non-null/nan value. At the moment (Grafana 9.3) it shows NaN in the Stat panel:
image

while < 9.3 would actually show the last non null/nan value

### PR DESCRIPTION
**Pull request by nmarrs**
**What is this feature?**

Exclude NaN values as part of `Last *` and `First *` reducers.

https://github.com/grafana/grafana/assets/22381771/170e65cb-736c-4b8a-a71a-cb2a2c98feda

[NaN_-1698445566753.json.txt](https://github.com/grafana/grafana/files/13193737/NaN_-1698445566753.json.txt)

**Why do we need this feature?**

`NaN` is not typically considered a "valid" value and so excluding it makes sense through these reducers as they are designed to return either the first or last "valid" value.

**Who is this feature for?**

Users that want to receive the first or last "valid" value in their data.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/59862

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: packages/grafana-data/src/transformations/fieldReducer.ts [hunk 1]
```diff
@@ -418,7 +418,7 @@ function calculateFirstNotNull(field: Field, ignoreNulls: boolean, nullAsZero: b
   const data = field.values;
   for (let idx = 0; idx < data.length; idx++) {
     const v = data[idx];
-    if (v != null && v !== undefined) {
+    if (v != null && v !== undefined && !isNaN(v)) {
```
Comment (leeoniya) [inline packages/grafana-data/src/transformations/fieldReducer.ts:421]: probably `if (v != null && !Number.isNaN(v))`

File: packages/grafana-data/src/transformations/fieldReducer.ts [hunk 2]
```diff
@@ -435,7 +435,7 @@ function calculateLastNotNull(field: Field, ignoreNulls: boolean, nullAsZero: bo
   let idx = data.length - 1;
   while (idx >= 0) {
     const v = data[idx--];
-    if (v != null && v !== undefined) {
+    if (v != null && v !== undefined && !isNaN(v)) {
```
Comment (leeoniya) [inline packages/grafana-data/src/transformations/fieldReducer.ts:438]: same as above

File: packages/grafana-data/src/transformations/fieldReducer.ts (hunk 1 above)
Comment (nmarrs) [reply packages/grafana-data/src/transformations/fieldReducer.ts:421]: ah good catch - `Number.isNaN` doesn't infer that value is `number` and instead is `unknown`

Currently working on adding a test and the [`reduceFields` function](https://github.com/grafana/grafana/blob/2ec3d3902186f3117e9796510cc303f194d0b615/packages/grafana-data/src/transformations/fieldReducer.ts#L57-L58) isn't playing nicely and still is returning `NaN` instead of the expected valid value in the test suite 🙃

File: packages/grafana-data/src/transformations/fieldReducer.test.ts [hunk 3]
```diff
@@ -172,6 +172,58 @@ describe('Stats Calculators', () => {
...
+        data: [NaN, NaN, NaN], // All NaN
+        result: null,
+      },
+      {
+        data: [undefined, undefined, undefined], // Empty row
+        result: null,
+      },
+    ];
+
+    const stats = reduceField({
```
Comment (nmarrs) [inline packages/grafana-data/src/transformations/fieldReducer.test.ts:191]: Stats returns:

```
{
        sum: 200,
        max: 200,
        min: 200,
        logmin: 200,
        mean: 200,
        last: NaN,
        first: NaN,
        lastNotNull: 200,
        firstNotNull: 200,
        count: 3,
        nonNullCount: 1,
        allIsNull: false,
        allIsZero: false,
        range: 0,
        diff: 0,
        delta: 0,
        step: null,
        diffperc: 0,
        previousDeltaUp: true
}
```

File: packages/grafana-data/src/transformations/fieldReducer.ts [hunk 4]
```diff
@@ -320,8 +320,8 @@ export function doStandardCalcs(field: Field, ignoreNulls: boolean, nullAsZero:
 
     calcs.count++;
 
-    if (currentValue != null) {
-      // null || undefined
+    if (currentValue != null && !Number.isNaN(currentValue)) {
```
Comment (nmarrs) [inline packages/grafana-data/src/transformations/fieldReducer.ts:323]: I'm a little scared of modifying the `doStandardCalcs` function but this seems reasonable 🤷

File: packages/grafana-data/src/transformations/fieldReducer.test.ts [hunk 5]
```diff
@@ -172,6 +172,58 @@ describe('Stats Calculators', () => {
...
 
+  it('consistent results for first/last value with NaN', () => {
+    const info = [
+      {
+        data: [NaN, 200, NaN], // first/last value is NaN
+        result: 200,
+      },
+      {
+        data: [NaN, NaN, NaN], // All NaN
+        result: null,
```
Comment (nmarrs) [inline packages/grafana-data/src/transformations/fieldReducer.test.ts:183]: Not sure if we want special handling in this case (i.e. if all NaN return NaN vs null)

**Review by ryantxu — APPROVED** [review]

File: packages/grafana-data/src/transformations/fieldReducer.ts [hunk 6]
```diff
@@ -418,7 +418,7 @@ function calculateFirstNotNull(field: Field, ignoreNulls: boolean, nullAsZero: b
   const data = field.values;
   for (let idx = 0; idx < data.length; idx++) {
     const v = data[idx];
-    if (v != null && v !== undefined) {
+    if (v != null && v !== undefined && !isNaN(v)) {
       return { firstNotNull: v };
```
[the remark this answers is not in the document]
Comment (nmarrs) [reply packages/grafana-data/src/transformations/fieldReducer.ts]: `foo != null` will check if `foo` is either `null` or `undefined` so we should be good with this simplification 👍

File: packages/grafana-data/src/transformations/fieldReducer.ts (hunk 4 above)
Comment (nmarrs) [reply packages/grafana-data/src/transformations/fieldReducer.ts:323]: @ryantxu this is a change I'm a little worried about in this PR (modifying `doStandardCalcs` function) - does this seem reasonable?

**Comment by leeoniya** [comment]
we could go one step further and also omit Infinity and -Infinity by switching to `Number.isFinite()` for the whole condition. 🤔 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite

**Comment by ryantxu** [comment]
> go one step further

I think that may be one step too far, but I do not feel too strongly

**Review by ryantxu — APPROVED** [review]

**Comment by nmarrs** [comment]
> we could go one step further and also omit Infinity and -Infinity by switching to `Number.isFinite()` for the whole condition. 🤔

I don't feel super strongly on this either way - though I am not informed on use cases where seeing +/- inf makes sense. Maybe for now we could move forward with just avoiding NaN and see what user sentiment / feedback is for that initial change? What do you think @leeoniya?
