### PR TITLE
NavBar: app chrome state wrongly overwritten when ds modal is opened

### LINKED ISSUE #67805: Navbar resets to dashboard state when opening the advanced DS modal picker
https://user-images.githubusercontent.com/5699976/236148536-a09f825d-dc18-4a6b-bfbb-3e7c4f7bb992.mov

Notes from Torkel
> we had the same issue with the drawer, I think it's triggering a render of DashNav somehow which resets the nav toolbar content

### PR DESCRIPTION
**Pull request by juanicabanas**
**What is this feature?**

The DashNav was using the ModalsContext. That's because from the public dashboard list table (/dashboard/public), there's a button that redirects the user to the specific public dashboard configuration (which is a modal).
Since the ds picker updates that context, the DashNav component was being rerendered and, therefore, updating the toolbar buttons.  

**Why do we need this feature?**

The toolbar was showing the dashboard buttons instead of the panel edit buttons

**Which issue(s) does this PR fix?**:

Fixes [#67805](https://github.com/grafana/grafana/issues/67805)

**Special notes for your reviewer:**

- I modified where the ModalsContext is used. I think it's responsibility of the ShareButton to open or not the ShareModal component. With this, an update on the ModalsContext doesn't rerender the DashNav.
- I created a function to get the public dashboard configuration url

https://user-images.githubusercontent.com/11707172/236598307-53739eb0-4c08-409a-b8ca-df846b917cd3.mov

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard/components/ShareModal/ShareModal.tsx [hunk 1]
```diff
@@ -86,6 +86,8 @@ function getInitialState(props: Props): State {
 }
 
 export class ShareModal extends React.Component<Props, State> {
+  static contextType = ModalsContext;
```
Comment (torkelo) [inline public/app/features/dashboard/components/ShareModal/ShareModal.tsx:89]: could not see context used anywhere in this modal

**Review by torkelo — APPROVED** [review]

**Review by torkelo — APPROVED** [review]

**Review by torkelo — APPROVED** [review]

**Review by ivanortegaalba — APPROVED** [review]
The bug is not there anymore. Happy with the new approach 💯

**Review by ivanortegaalba — DISMISSED** [review]
Ups, I found a bug now, the modal doesn't close when going to "Add new DS"

File: public/app/features/dashboard/components/DashNav/DashNav.tsx [hunk 2]
```diff
@@ -165,23 +162,6 @@ export const DashNav = React.memo<Props>((props) => {
   };
 
   // Open/Close
```
Comment (evictorero) [inline public/app/features/dashboard/components/DashNav/DashNav.tsx:164]: nit: this comment does not have sense anymore

**Review by evictorero — APPROVED** [review]
Tested and works as expected, it fixes the existent bug and the opening of the public dashboard settings from the list still works as expected. Great refactor! Left one nit comment.
