### PR TITLE
GraphNG: uPlot 1.6.10

### LINKED ISSUE #31724: Resizing panels during refresh causes page to hang
**What happened**:
Resizing panels, or the page will cause Grafana to hang.

https://user-images.githubusercontent.com/9749173/110117203-74123b00-7db0-11eb-8114-9099e81fad11.mp4

**What you expected to happen**:
Grafana not to hang.

**How to reproduce it (as minimally and precisely as possible)**:
I tried to create a "test" dashboard to reproduce, but couldn't figure out what the underlying issue was. I can upload the JSON for the shown dashboard if it helps.

**Anything else we need to know?**:
Seems to be okay for smaller time ranges, seems to be okay if there are less panels.

**Environment**:
- Grafana version: 7.4.2
- Data source type & version: Thanos v0.18.0 (Prometheus 2.22.1), Loki 2.0.0
- OS Grafana is installed on: Linux (Kubernetes)
- User OS & Browser: Windows 10, Chrome 88.0.4324.190
- Grafana plugins: Default
- Others:

### LINKED ISSUE #34604: Grafana UI locks sometimes when creating a new dashboard and panel
**What happened**:
The flow of new dashboard -> new panel on main will _sometimes_ lock my browser.

**What you expected to happen**:
Not to lock

**How to reproduce it (as minimally and precisely as possible)**:
Keep creating dashboards, and click add new panel. If it doesn't lock, keep doing that until it does - no saving needed.

**Anything else we need to know?**:
This might only trigger with inspector open? Or perhaps more like to trigger with inspector open. When happens, a line isn't drawn on the plot before it locks.

**Environment**:
- Grafana version: 888683a8ad 
- Data source type & version: test-datasource
- User OS & Browser: Linux, Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes #31724
Fixes #34604

Also partial fix for #34693, though it's likely there's also an issue on Grafana's side which triggers that error (attempting to plot 0 series).

Unblocks

#34584
#34531

https://github.com/leeoniya/uPlot/releases/tag/1.6.10

image

### CODE REVIEW

**Review by torkelo — APPROVED** [review]

**Review by ryantxu — APPROVED** [review]
works :tada:

File: packages/grafana-ui/src/components/uPlot/utils.ts [hunk 1]
```diff
@@ -119,16 +119,16 @@ export function findMidPointYPosition(u: uPlot, idx: number) {
   for (let i = 1; i < u.data.length; i++) {
     const sData = u.data[i];
     const sVal = sData[idx];
-    if (sVal !== null) {
-      if (max === null) {
+    if (sVal != null) {
+      if (max == null) {
```
Comment (ryantxu) [inline packages/grafana-ui/src/components/uPlot/utils.ts:123]: can you add comments on why (and if) it is important that this is `==` not `===` many folks looking at it (including me a few weeks ago) have learned to just use `===` for some who knows what javascript reason

Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/utils.ts:123]: this will (and already does) exist in many places. adding a comment here specifically seems odd. if TS does not complain then not sure it's worth also adding comments everywhere instead of expecting folks to know how JS works :)

Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/utils.ts:123]: in fact, making this strict induces TS errors, so i dont think it's necessary.
