### PR TITLE
AzureMonitor: Support decimal (as float64) type in analytics/logs

### LINKED ISSUE #28278: Azure Insights Analytics, unsupported analytics column type decimal
**What happened**:
When  using the `todecimal()` function in Insights Analytics queries, you get this error: 
`unsupported analytics column type decimal` 
image

**What you expected to happen**:
Getting a result to the query. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a new query using Azure Monitor data source, and Insights Analytics service. 
The query should return a number, use `todecimal()` on that number

**Anything else we need to know?**:
Replacing `todecimal()` by `toreal()` works. 

**Environment**:
- Grafana version: 7.2.1
- Data source type & version: Azure Monitor
- OS Grafana is installed on: 
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by kylebrandt**
**What this PR does / why we need it**:
Converters the kusto 128-bit decimal type into a 64-bit float64 instead of returning an error.

**Which issue(s) this PR fixes**:

Fixes #28278

**Special notes for your reviewer**:
Following work already done in ADX plugin, which is very similar https://github.com/grafana/azure-data-explorer-datasource/blob/a710e2d67fd40fc79db4c1dc5f087168e19eaf07/pkg/azuredx/table.go#L245

### CODE REVIEW

File: pkg/tsdb/azuremonitor/azure-log-analytics-table-frame.go [hunk 1]
```diff
@@ -194,3 +195,41 @@ var longConverter = data.FieldConverter{
...
+		if sOk {
+			out, err := strconv.ParseFloat(jS, 64)
+			if err != nil {
+				return nil, err
+			}
+			return &out, err
+		}
+
+		// As far as I can tell this always comes in a string, but this was in the
+		// ADX code, so leaving it in case does sometimes become a number somehow.
```
Comment (kylebrandt) [inline pkg/tsdb/azuremonitor/azure-log-analytics-table-frame.go:224]:
```suggestion
		// As far as I can tell this always comes in a string, but this is in the
		// ADX code, so leaving this in case values do sometimes become a number somehow.
```

File: pkg/tsdb/azuremonitor/testdata/loganalytics/7-log-analytics-all-types-table.json [hunk 2]
```diff
@@ -38,7 +38,10 @@
           {
             "name": "XTimeSpan",
             "type": "timespan"
-          }
+          },
+          {
+            "name":"XDecimal",
+            "type":"decimal"}
```
Comment (aknuds1) [inline pkg/tsdb/azuremonitor/testdata/loganalytics/7-log-analytics-all-types-table.json:44]:
```suggestion
            "type":"decimal"
          }
```

**Review by aknuds1 — APPROVED** [review]
Sorry for the slow review, but LGTM. Just left a suggestion for some JSON cleanup.
