### PR TITLE
FieldConfig: set min/max automatically for gauge

### LINKED ISSUE #19527: BarGauge: Auto min / max based on data
**What would you like to be added**: Bar Gauges should dynamically decide the maximum if not set (curretnly 100 is default)

**Why is this needed**:
The scenario is using bar gauges to show the most common error in an error log (mysql). As 1h or 1y could be selected setting a static maximum does not work for this scenario.

### LINKED ISSUE #20581: Bar Guage: support for automatic max. value
**What would you like to be added**:
Max. value of the bar guage is automatically set to the maximum value of the query results.

**Why is this needed**:
I am using a bar guage to display TopN query with interval filter. In some cases, the guage is not usable, because the max. value of the bar guage can be set a single value.

with long interval:
A ============ 10000
B ============ 5000
C ============ 1000
D ============ 500

with short interval:
A = 11
B = 10
C = 9
D = 8

I think it is very useful that the max. value is set automatically to the maximum value (10000 or 11 above).

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes #20581, Fixes #19527

This auto picks the min/max based on the results in the series:

image

The thresholds are still absolute

### CODE REVIEW

File: packages/grafana-data/src/field/fieldOverrides.ts [hunk 1]
```diff
@@ -50,15 +42,13 @@ export function findNumericFieldMinMax(data: DataFrame[]): GlobalMinMax {
...
  * Return a copy of the DataFrame with all rules applied
  */
-export function applyFieldOverrides(
-  data: DataFrame[],
-  source: FieldConfigSource,
-  replaceVariables: InterpolateFunction,
-  theme: GrafanaTheme,
-  isUtc?: boolean
-): DataFrame[] {
+export function applyFieldOverrides(options: GetFieldDisplayValuesOptions): DataFrame[] {
```
Comment (ryantxu) [inline packages/grafana-data/src/field/fieldOverrides.ts]: I am a bit torn changing this signature because the "source" value becomes `FieldDisplayOptions` rather than the more limited version...

But passing the other values is pretty messy when the rest is all the same.

Lets keep an eye on this and aim to clean it up as we apply more patterns to it

File: packages/grafana-data/src/field/fieldDisplay.ts [hunk 2]
```diff
@@ -79,6 +79,7 @@ export interface GetFieldDisplayValuesOptions {
   replaceVariables: InterpolateFunction;
   sparkline?: boolean; // Calculate the sparkline
   theme: GrafanaTheme;
+  calculatePercent?: boolean;
```
Comment (ryantxu) [inline packages/grafana-data/src/field/fieldDisplay.ts]: this is a flag to avoid calculating min/max when not necessary.  It will also be required when we add a 'relative' threshold mode in #20783

Comment (torkelo) [reply packages/grafana-data/src/field/fieldDisplay.ts]: Is there a reason you named this calculatePercent and not calculateMinMax or autoMinMax ?

**Review by torkelo — APPROVED** [review]
Looks good to me, only thing that looks strange is the naming of calculatePercent :)
