### PR TITLE
Loki: Uppercase autocomplete

### LINKED ISSUE #42573: Granana/Loki : Autocomplete not working for labels starting with upper case letter
**What happened**:

When searching in Loki labels container upper case characters renders with a white first letter and auto-complete of the labels values doesn't appear.

image

**What you expected to happen**:

Label name to not have a white first character, and for values for the label to appear.

**How to reproduce it (as minimally and precisely as possible)**:

Create two labels, one starting with UpperCase and one lower case and perform a search.

**Environment**:

- Grafana version: 8.2.5
- Data source type & version: Loki
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Google Chrome

### PR DESCRIPTION
**Pull request by joey-grafana**
**What this PR does / why we need it**:
To allow Loki queries with labels that have an uppercase char for the first letter. 
To also allow syntax highlighting for the above.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/42573

**Special notes for your reviewer**:
Before
Before
After
After

### CODE REVIEW

File: public/app/plugins/datasource/loki/syntax.ts [hunk 1]
```diff
@@ -192,7 +192,7 @@ export const lokiGrammar: Grammar = {
         pattern: /#.*/,
       },
       'label-key': {
-        pattern: /[a-z_]\w*(?=\s*(=|!=|=~|!~))/,
+        pattern: /[a-z_,A-Z_]\w*(?=\s*(=|!=|=~|!~))/,
```
Comment (connorlindsey) [inline public/app/plugins/datasource/loki/syntax.ts:195]: I think the comma should be removed as well as the redundant second underscore. Including the comma makes it a valid option in the regex and I think you have have been using it like an 'or' which the brackets already do. 

Here's the Prometheus label data model which includes a regex for valid labels as reference: https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

**Review by connorlindsey — APPROVED** [review]
