### PR TITLE
SigV4: fix AWS auth settings not getting forwarded to data proxy HTTP client

### LINKED ISSUE #120766: Alertmanager: regression breaking sigv4 in alertmanager plugin
### What happened?

After upgrading from v10.4.1 to v12.4.3, pressing `Save & Test` with the alertmanager plugin no longer works. The prometheus plugin with the exact same sigv4 settings works.

Image

In our logs we see `trying to use non-allowed auth method ec2_iam_role`. This tells me either `allowed_auth_providers` is not being passed to the plugin or the plugin is no longer respecting it

My suspicion is after https://github.com/grafana/grafana/pull/107522, we no longer pass in these configs via `SigV4MiddlewareWithAuthSettings` for frontend plugins

### What did you expect to happen?

The plugin should work

### Did this work before?

Yes. Last tested on v10.4.1

### How do we reproduce it?

1. Set up alertmanager plugin with sigv4 and test successful connection in v10.4.1
2. Upgrade to v12.4.3
3. The alertmanager plugin stops working

Alternatively set it up directly on v12.4.3. It never works

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 12.4.1
OS: Mac
Browser: Firefox

### Grafana platform?

Other

### Datasource(s)?

alertmanager

### PR DESCRIPTION
**Pull request by chriscerie**
**What is this feature?**

After https://github.com/grafana/grafana/pull/107522 we no longer pass in aws auth settings as the middleware would read the auth settings from ctx. But for frontend-only datasources using the data proxy (like `alertmanager`), GrafanaConfig is never injected into the request context. This causes them to no longer respect the aws auth settings

The fix here is to pass the grafana cfg as a fallback when the context's auth settings are not found

**Why do we need this feature?**

Fixes regression

**Which issue(s) does this PR fix?**:

Fixes #120766

**Special notes for your reviewer:**

Previously

1. Set ini `allowed_auth_providers = ec2_iam_role,keys,default`
2. Set up prometheus data source with sigv4 + AWS IAM auth. Confirmed it works
3. Set up alertmanager data source with same setup. Confirmed it fails health check

image

Now

1. Set ini `allowed_auth_providers = ec2_iam_role,keys,default`
2. Set up prometheus data source with sigv4 + AWS IAM auth. Confirmed it works
3. Set up alertmanager data source with same setup. Confirmed it works

image

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: pkg/infra/httpclient/httpclientprovider/http_client_provider.go [hunk 1]
```diff
@@ -44,7 +44,26 @@ func New(cfg *setting.Cfg, validator validations.DataSourceRequestURLValidator,
 
 	// SigV4 signing should be performed after all headers are added
 	if cfg.SigV4AuthEnabled {
-		middlewares = append(middlewares, awsauth.NewSigV4Middleware())
+		awsCfg := backend.NewGrafanaCfg(map[string]string{
+			awsds.AllowedAuthProvidersEnvVarKeyName:  strings.Join(cfg.AWSAllowedAuthProviders, ","),
```
Comment (iwysiu) [inline pkg/infra/httpclient/httpclientprovider/http_client_provider.go]: I realize that sigv4 might not use it, but would it make sense to include [PerDatasourceHTTPProxyEnabledEnvVarKeyName](https://github.com/grafana/grafana-aws-sdk/blob/72e2ed1e90df88aab3adea9988cdad26c128594a/pkg/awsds/authSettings.go#L23) just in case?

**Review by iwysiu — COMMENTED** [review]
Overall it makes sense! one note

File: pkg/infra/httpclient/httpclientprovider/http_client_provider.go (hunk 1 above)
Comment (chriscerie) [reply pkg/infra/httpclient/httpclientprovider/http_client_provider.go]: Added!

**Review by iwysiu — APPROVED** [review]

**Comment by taleena** [comment]
Hey team - because this is a regression, is this possible to get a backport into v12?

**Comment by zoltanbedi** [comment]
Hey @taleena going to push a backport for this.
