### PR TITLE
PanelEdit: Fix 'Actual' size by passing the correct panel size to Das…

### LINKED ISSUE #37812: PanelEdit: actual size is busted
When working on a panel with a specific aspect ratio, it is nice to see it in the shape it will be in the dashboard.  We have the "Fill" and "Actual" for this reason... but it is currently not behaving properly.

image

Edit mode:
image

I would expect to see something similar to what we had in 7x and 8.0

### PR DESCRIPTION
**Pull request by ashharrison90**
…hboardPanel

**What this PR does / why we need it**:

- passes the correct panel size in to `DashboardPanel`
- stops absolutely positioning `PanelChrome`/`PanelChromeAngular` so it's restricted by it's parent correctly

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/37812

**Special notes for your reviewer**:

- this feels like one of those simple changes that could easily break something i haven't thought about, if anyone has some good suggestions of what to test it would be really appreciated!

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]
:taco: 

image

File: public/app/features/dashboard/dashgrid/PanelChrome.tsx [hunk 1]
```diff
@@ -428,7 +428,6 @@ export class PanelChrome extends Component<Props, State> {
 
     const containerClassNames = classNames({
       'panel-container': true,
-      'panel-container--absolute': true,
```
Comment (ryantxu) [inline public/app/features/dashboard/dashgrid/PanelChrome.tsx:431]: I agree this feels dangerous since it it changes the *view* settings not just the edit settings... but I have not found a dashboard that looked wrong yet.

My guess is that we have so many redundant position elements around panels that the absolute position is not needed anymore

Comment (ashharrison90) [reply public/app/features/dashboard/dashgrid/PanelChrome.tsx:431]: i also can't see any issues from my testing, so i'll merge and be on the lookout 👀
