### PR TITLE
Azure Monitor: Add trap focus for modals in grafana/ui and other small a11y fixes for Azure Monitor

### LINKED ISSUE #41902: Fastpass Fixes for Azure
(just making a separate ticket for https://github.com/grafana/grafana/issues/41206 for easier tracking of this work on our board)

### PR DESCRIPTION
**Pull request by sarahzinger**
**What this PR does / why we need it**:
I went through [Fastpass](https://accessibilityinsights.io/docs/en/web/getstarted/fastpass/) and tried to resolve any issues I saw there for Azure Monitor

The main problem I noticed was that we do not properly trap focus for modals, and we use a modal in Azure for the resource picker. So if a user tabs to open a modal, their focus stays beneath the modal rather than within it. By using trap-focus-react it'll keep the user's focus on the focus-able elements of the modal until the modal is closed. 

Other than that the only issues I saw were things getting flagged for not having a label

**Which issue(s) this PR fixes**:
relates to https://github.com/grafana/grafana/issues/41206

**Special notes for your reviewer**:
I don't recall if I've ever made a change to grafana/ui before, so let me know if I'm doing it right! I found when I installed the npm package for trap-focus-react I had to install it in 2 package.jsons to get it to work, does that sound right or am I misunderstanding something?

### CODE REVIEW

File: packages/grafana-ui/src/components/Modal/Modal.tsx [hunk 1]
```diff
@@ -7,6 +7,7 @@ import { getModalStyles } from './getModalStyles';
 import { ModalHeader } from './ModalHeader';
 import { IconButton } from '../IconButton/IconButton';
 import { HorizontalGroup } from '../Layout/Layout';
+import FocusTrap from 'focus-trap-react';
```
Comment (jackw) [inline packages/grafana-ui/src/components/Modal/Modal.tsx:10]: This is a thin wrapper around `focus-trap`. Looking at open issues for that library two caught my eye that might cause us problems:

https://github.com/focus-trap/focus-trap/issues/375 (focus stuck on elements with positive tabIndex)
https://github.com/focus-trap/focus-trap/issues/383 (can break `clipboard.js`. Unless I'm mistaken we use it in [ClipboardButton.tsx](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.tsx#L2))

Might be wise to confirm if these issues affect us before merging.

**Review by jackw — COMMENTED** [review]
> I don't recall if I've ever made a change to grafana/ui before, so let me know if I'm doing it right!

Yep, you are making changes to grafana/ui correctly! 🙂 
One thing that's always worth considering is if your changes are going to affect any stories.

> I found when I installed the npm package for trap-focus-react I had to install it in 2 package.jsons to get it to work, does that sound right or am I misunderstanding something?

I've seen similar strangeness and I think it's related to how Yarn PnP works. I've yet to figure out how to avoid this duplication of dependency references in multiple package.json files.

File: packages/grafana-ui/src/components/Modal/Modal.tsx (hunk 1 above)
Comment (sarahzinger) [reply packages/grafana-ui/src/components/Modal/Modal.tsx:10]: @jackw good catches! I believe for Azure neither of these issues should affect us, but it seems a bit aggressive to force all modals to use this when we haven't really done thorough testing yet. What would you think about making this opt-in for now.

File: packages/grafana-ui/src/components/Modal/Modal.tsx [hunk 2]
```diff
@@ -25,6 +26,9 @@ export interface Props {
 
   /** If not set will call onDismiss if that is set. */
   onClickBackdrop?: () => void;
+
+  /** prevents users from tabbing away from items outside of the modal. You probably want this set to true, but making this opt-in for now as we test out this implementation */
+  shouldFocusTrap?: boolean;
```
Comment (Elfo404) [inline packages/grafana-ui/src/components/Modal/Modal.tsx:31]: i am a bit reluctant in having this extra prop controlling the trap. if modals should always trap then i think it would make more sense to invest a little more into testing it now rather than introducing this extra prop. wdyt?

File: package.json [hunk 3]
```diff
@@ -284,6 +284,7 @@
     "fast-json-patch": "3.1.0",
     "fast-text-encoding": "^1.0.0",
     "file-saver": "2.0.2",
+    "focus-trap-react": "^8.8.2",
```
Comment (thisisobate) [inline package.json:287]: We already use `react-aria` for all things focus trapping in Grafana.
React-aria provides you with a set of hooks that helps you do things like focus trapping, keyboard navigation, `esc` closing, etc.
As for focus trapping, you can use the [FocusLock]( https://react-spectrum.adobe.com/react-aria/FocusScope.html) provided by react-aria to achieve similar result.

You can take a look at the [TimeRangePicker](https://github.com/grafana/grafana/blob/1aac13e5d0e703c9bc403c157e8af8e3025cf7ec/packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker.tsx#L120) component for some inspiration.

File: packages/grafana-ui/src/components/Modal/Modal.tsx (hunk 2 above)
Comment (sarahzinger) [reply packages/grafana-ui/src/components/Modal/Modal.tsx]: @Elfo404 removed it! I had added it because I was originally using a different dependency for the focus traps and I think there was some concern that perhaps it wasn't stable enough to use everywhere. But now that I switched to FocusScope from react-aria I think it's no longer necessary. Removed!

File: package.json (hunk 3 above)
Comment (sarahzinger) [reply package.json]: @thisisobate thanks so much didn't notice this! Looks cool.

File: packages/grafana-ui/src/components/Modal/Modal.tsx (hunk 2 above)
Comment (Elfo404) [reply packages/grafana-ui/src/components/Modal/Modal.tsx]: awesome!

**Comment by kaydelaney** [comment]
Seems like these changes affect prometheus' azure auth settings rather than the azure datasource config itself?

**Comment by sarahzinger** [comment]
> Seems like these changes affect prometheus' azure auth settings rather than the azure datasource config itself?

Sorry, I don't understand @kaydelaney what makes you say that? I haven't looked at prometheus, just the azure monitor plugin. Here's a screenshot of fastpass showing no errors on the config page:
Screen Shot 2021-11-18 at 3 47 46 PM


Here's some from the query editor. There's some errors still but none seem to be directly related to the datasource, so I'm assuming efforts for that are being tracked/worked on elsewhere:
Screen Shot 2021-11-18 at 3 51 25 PM
Screen Shot 2021-11-18 at 3 53 38 PM
Screen Shot 2021-11-18 at 3 56 05 PM

**Review by Elfo404 — APPROVED** [review]
went through some of the modals and everything seems to work as expected 🚀 

note: do we want to add a milestone and backport this to 8.3?
