### PR TITLE
PanelEdit: Display the VisualizationPicker that was not displayed if a panel has an unknown panel plugin

### LINKED ISSUE #35733: PanelEdit: VisulizationPicker doesn't show if panel has an unknown panel plugin
**What happened**:
I created a dashboard with the clock plugin. I then uninstalled the clock plugin but I cannot select a different visualisation for the panel as the VisualizationPicker doesn't appear.

**What you expected to happen**:

To have the option to select a different visualization from the picker.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.1.0-pre (898c314946)
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser:
- Grafana plugins: Clock plugin but could be any panel plugin
- Others:

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
If you have a panel with a plugin that is no longer available the VisualisationPicker won't render a button which makes it rather tricky to change the panel visualisation. This PR addresses this by returning an "unknown" plugin to the visualisation picker so the picker appears.

https://user-images.githubusercontent.com/73201/122248269-4321c600-cec8-11eb-9c98-9597cd800721.mp4

https://user-images.githubusercontent.com/73201/122248301-474de380-cec8-11eb-99bc-cc649c7f0410.mp4

**Which issue(s) this PR fixes**:

Fixes #35733

**Special notes for your reviewer**:
This PR also refactors the `<VisualisationButton />` component to use redux hooks over `map<State|Dispatch>ToConnect`.

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Looks fantastic! 

Wonder if this can solve https://github.com/grafana/grafana/issues/35835 ?

File: public/app/features/dashboard/components/PanelEditor/VisualizationButton.tsx [hunk 1]
```diff
@@ -1,45 +1,31 @@
...
-  plugin,
-  toggleVizPicker,
-  isPanelOptionsVisible,
-  isVizPickerOpen,
-  setPanelEditorUIState,
-}) => {
+export const VisualizationButton: FC<Props> = ({ panel }) => {
   const styles = useStyles(getStyles);
+  const dispatch = useDispatch();
+  const plugin = useSelector(getPanelPluginWithFallback(panel.type));
```
Comment (hugohaggmark) [inline public/app/features/dashboard/components/PanelEditor/VisualizationButton.tsx:19]: nit: I think that React recommends using useDispatch|Selector over connected components. But when I use it I found it a bit more complicated to test those components because I need to either wrap the component in a Provider or mock useDispatch|Selector. What are everyone's thoughts on this, is there another trick for testing these components? Is there a performance penalty using connected components?

**Review by hugohaggmark — APPROVED** [review]
Looks great!

File: public/app/features/dashboard/components/PanelEditor/VisualizationButton.tsx (hunk 1 above)
Comment (jackw) [reply public/app/features/dashboard/components/PanelEditor/VisualizationButton.tsx:19]: I think they recommend the hooks mostly for reducing boilerplate, making it easier to follow the flow of data, and easier typing. I was in two minds about it but felt that for the size of this component it felt neater to remove all the boilerplate. For testing I don't think there's a trick you've missed in your approaches I'm afraid. I've never really considered mocking useDispatch/useSelector. I've always gone the wrong of using a wrapper to handle the mocks. Maybe this refactor shouldn't be part of this PR? I can always revert the commit and we can have this discussion with a wider audience. WDYT @hugohaggmark?

Comment (hugohaggmark) [reply public/app/features/dashboard/components/PanelEditor/VisualizationButton.tsx:19]: Yes, I totally agree with you Jack that this should be with a wider audience and not for this PR. I was just being curious if I missed a trick out there. Again great work 🎉

Comment (dprokop) [reply public/app/features/dashboard/components/PanelEditor/VisualizationButton.tsx:19]: @hugohaggmark could this be part of your useDispatch|Selector topic on next FE Weekly?

Comment (hugohaggmark) [reply public/app/features/dashboard/components/PanelEditor/VisualizationButton.tsx:19]: Hmm not really, that session was more about using useReducer and Redux Toolkit
