### PR TITLE
Sandbox: Add support for webpack dynamic imports

### LINKED ISSUE #71713: Fix webpack dynamic imports not working inside the sandbox.

### PR DESCRIPTION
**Pull request by academo**
**What is this feature?**
Adds compatibility for webpack dynamic imports to the frontend plugin sandbox.

**Why do we need this feature?**

Some big plugins distribute their code in splitted chunks and load them dynamically or using react's suspense. These dynamic imports don't work in the sandbox because of the restriction impossed in scripts loading.

**Who is this feature for?**

plugins loading dynamic chunks
plugins loading dynamic chunks

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/71713

**Special notes for your reviewer:**

#### The webpack way

Webpack loads dynamic chunks in its "loadScript" function. This function when invoked does this:

- Returns a new promise, waits for:
- Check if the chunk is already loaded. if not:
- Check if the chunk is being loaded. if not:
- Check if there's a `script` tag with the chunk url. if not:
- Injects a new `script` tag with the url as src. Subscribes to `onLoad` and `onError` for this tag
- The chunk loading promise is resolved or rejected based on the `onLoad` or `onError`.

After this wait, webpack checks again if the chunk is now available and if not it throws an error.

#### The Sandbox way

- Intercept when a `script` tag is injected
- If the src is not from an accepted source (same hostname or cdn hostname): execute `onError`
- If the src is an accepted source:
- window.fetch the `url`, then:
- process the content for sourcemaps and cdns, then:
- evaluate the code inside the same sandboxed environment, then:
- call `onLoad` of the script.

### CODE REVIEW

File: public/app/features/plugins/sandbox/code_loader.ts [hunk 1]
```diff
@@ -0,0 +1,88 @@
+import { PluginMeta } from '@grafana/data';
```
Comment (academo) [inline public/app/features/plugins/sandbox/code_loader.ts:1]: moving some functions from the sandbox loader to here.

File: public/app/features/plugins/sandbox/distortion_map.ts [hunk 2]
```diff
@@ -356,6 +371,19 @@ function distortAppend(distortions: DistortionMap) {
           return document.createDocumentFragment();
         }
       }
+      // if the node is a script, load it into the sandbox
+      // this allows webpack chunks to be loaded into the sandbox
+      // loadScriptIntoSandbox has restrictions on what scripts can be loaded
+      if (sandboxEnv && arg && nodeType === 'script' && arg instanceof HTMLScriptElement) {
```
Comment (academo) [inline public/app/features/plugins/sandbox/distortion_map.ts:377]: even though these checks look redundant they are necessary for typescript.

Comment (jackw) [reply public/app/features/plugins/sandbox/distortion_map.ts:377]: I'd stuff this logic in a var like `isScriptTag` to make it easier to scan the code.

**Review by jackw — APPROVED** [review]
LGTM! 🚀
