### PR TITLE
Prometheus: fix Heatmap y buckets when legendFormat: auto

### LINKED ISSUE #55535: Prometheus histogram heatmap y-axis out-of-order with auto legend
**What happened**:

I created a Heatmap panel of some Prometheus histogram metrics, with the legend set to `auto` and the `+Inf` entry on the y-axis appeared between `0` and the next positive y-axis value. The corresponding data was also incorrectly plotted.

**What you expected to happen**:

The `+Inf` label should appear at the topmost position on the y-axis and its cumulative value correctly interpreted, the same way was when the legend is explicitly specified as `{{le}}`.

image

**How to reproduce it (as minimally and precisely as possible)**:

image

**Anything else we need to know?**:

I was only able to get this working when I stumbled upon this comment on an indirectly related issue:
https://github.com/grafana/grafana/issues/24343#issuecomment-1250728216

**Environment**:
- Grafana version: v9.1.4 from [Docker Hub](https://hub.docker.com/layers/grafana/grafana/9.1.4/images/sha256-f776b98f6bc3115d04f76f9b52b8172ac0cd81a8a78933d7e48bf2b76ce13d95?context=explore)
- Data source type & version: Prometheus 5.0.0 (core)
- OS Grafana is installed on: Docker host is Ubuntu 18.04
- User OS & Browser: Windows 11 and Chrome v105
- Grafana plugins: Heatmap 5.0.0 (core)
- Others:

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/grafana/issues/55535

this works around the fact that we only get back frame.name with le buckets when legendFormat == {{le}}...which is not the default.

more thorough explanation here: https://github.com/grafana/grafana/issues/55535#issuecomment-1321330816

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/result_transformer.ts [hunk 1]
```diff
@@ -102,6 +102,17 @@ export function transformV2(
     (df) => isHeatmapResult(df, request)
   );
 
+  // this works around the fact that we only get back frame.name with le buckets when legendFormat == {{le}}...which is not the default
+  heatmapResults.forEach((df) => {
+    if (df.name == null) {
+      let le = df.fields.find((f) => f.name === 'Value')?.labels?.le;
+
+      if (le != null) {
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/prometheus/result_transformer.ts:110]: Could we simplify this to `if(le)` instead of `le != null`?

File: public/app/plugins/datasource/prometheus/result_transformer.ts [hunk 2]
```diff
@@ -102,6 +102,17 @@ export function transformV2(
     (df) => isHeatmapResult(df, request)
   );
 
+  // this works around the fact that we only get back frame.name with le buckets when legendFormat == {{le}}...which is not the default
+  heatmapResults.forEach((df) => {
+    if (df.name == null) {
+      let le = df.fields.find((f) => f.name === 'Value')?.labels?.le;
```
Comment (toddtreece) [inline public/app/plugins/datasource/prometheus/result_transformer.ts:108]: should this loop through each field in the frame and set the field name to the value of `le` if that label exists? setting the frame name seems like it wouldn't work with wide frames

Comment (toddtreece) [reply public/app/plugins/datasource/prometheus/result_transformer.ts:108]: scratch that. i see what's going on now in `sortSeriesByLabel`. it looks like this will be updated if/when the plugin backend outputs wide frames

**Review by toddtreece — APPROVED** [review]

File: public/app/plugins/datasource/prometheus/result_transformer.ts (hunk 1 above)
Comment (toddtreece) [reply public/app/plugins/datasource/prometheus/result_transformer.ts:110]: i think this would have unintended consequences if `le` was `0`

File: public/app/plugins/datasource/prometheus/result_transformer.ts (hunk 2 above)
Comment (leeoniya) [reply public/app/plugins/datasource/prometheus/result_transformer.ts:108]: that would require more changes since sorting has always relied on frame names.

https://github.com/grafana/grafana/blob/bdfa127ee5c11948568d83579e60351792e65f4f/public/app/plugins/datasource/prometheus/result_transformer.ts#L637-L638

and we actually rename the Value fields based on frame names later:

https://github.com/grafana/grafana/blob/bdfa127ee5c11948568d83579e60351792e65f4f/public/app/plugins/datasource/prometheus/result_transformer.ts#L593

File: public/app/plugins/datasource/prometheus/result_transformer.ts (hunk 1 above)
Comment (toddtreece) [reply public/app/plugins/datasource/prometheus/result_transformer.ts:110]: trying this comment again, cause i confused myself for a second :smile: 

i think `if(le)` would miss setting the frame name if `le` was `0`

Comment (leeoniya) [reply public/app/plugins/datasource/prometheus/result_transformer.ts]: the label values are all strings, so we'll never actually have `0`...and `'0'` will still be okay.

but yeah, i generally hate coalescing to truthy/falsey, even in `if ()`. `== null` is more chars but covers only null and undefined, without having to think through what else might fail.

i changed it for you, though, @gtk-grafana; anything for you :heart:

**Review by gtk-grafana — COMMENTED** [review]
This doesn't look good to me, it looks great! 

✅ Tested locally was able to verify bug and the fix working as expected.
✅ Unit tests fail when this logic is removed/adjusted.
Thank you Leon!
