### PR TITLE
AzureMonitor: Add support for not equals and startsWith operators when creating Azure Metrics dimension filters

### LINKED ISSUE #47427: Dimension Operator not supporting ne and startsWith for Azure Monitor
## Issue:
When adding a new dimension, we can't select the `ne` operator on the UI as shown below:

image

But we can add it in the json model like below (work around)

image

## Expectation:
What we expect is to be able to select at least the `ne` operator in the UI, optimally to select the `startsWith` operator too.

## To reproduce:
Use Azure Monitor with any metric and try to select another operator for the dimension as explained before.

**Environment**:
- Grafana version: 8.2.5
- Data source type & version: Azure Monitor (Core)
- OS Grafana is installed on: AWS
- User OS & Browser: macOS, Chrome
- Grafana plugins: Azure Monitor

### PR DESCRIPTION
**Pull request by aangelisc**
**What this PR does / why we need it**:

Adds support for the not equals and startsWith operators in the Azure Monitor data source when selecting dimensions for a metric (where supported).

**Which issue(s) this PR fixes**:

Fixes #47427 

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource.go [hunk 1]
```diff
@@ -120,11 +120,16 @@ func (e *AzureMonitorDatasource) buildQueries(queries []backend.DataQuery, dsInf
...
 		} else {
 			for i, filter := range azJSONModel.DimensionFilters {
-				dimSB.WriteString(filter.String())
-				if i != len(azJSONModel.DimensionFilters)-1 {
-					dimSB.WriteString(" and ")
+				if filter.Operator != "eq" && filter.Filter == "*" {
+					dimSB.WriteString(fmt.Sprintf("%s eq '*'", filter.Dimension))
+				} else {
+					dimSB.WriteString(filter.String())
+					if i != len(azJSONModel.DimensionFilters)-1 {
```
Comment (iwysiu) [inline pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource.go:127]: should the code that adds `" and "` be outside this else?

File: pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource_test.go [hunk 2]
```diff
@@ -127,6 +127,39 @@ func TestAzureMonitorBuildQueries(t *testing.T) {
...
+		{
+			name: "correctly sets dimension operator to eq (irrespective of operator) when filter value is unspecified or \"*\"",
+			azureMonitorVariedProperties: map[string]interface{}{
+				"timeGrain":        "PT1M",
+				"dimensionFilters": []types.AzureMonitorDimensionFilter{{Dimension: "blob", Operator: "sw", Filter: "*"}, {Dimension: "tier", Operator: "ne", Filter: "*"}},
+				"top":              "30",
+			},
+			queryInterval:           duration,
+			expectedInterval:        "PT1M",
+			azureMonitorQueryTarget: "%24filter=blob+eq+%27%2A%27tier+eq+%27%2A%27&aggregation=Average&api-version=2018-01-01&interval=PT1M&metricnames=Percentage+CPU&metricnamespace=Microsoft.Compute-virtualMachines&timespan=2018-03-15T13%3A00%3A00Z%2F2018-03-15T13%3A34%3A00Z&top=30",
```
Comment (iwysiu) [inline pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource_test.go:161]: See azuremonitor-datasource.go, but should this be:
`%24filter=blob+eq+%27%2A%27+and+tier+eq+%27%2A%27&a...` ?

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx [hunk 3]
```diff
@@ -15,6 +16,21 @@ const DimensionFields: React.FC<DimensionFieldsProps> = ({ query, dimensionOptio
...
+    { label: '==', value: 'eq' },
+    { label: '!=', value: 'ne' },
+    { label: 'starts with', value: 'sw' },
+  ];
+
+  const validDimensionOptions = useMemo(() => {
+    let t = dimensionOptions;
+    let dimensionFilters = query.azureMonitor?.dimensionFilters;
+    if (dimensionFilters !== undefined && dimensionFilters.length > 0) {
+      t = dimensionOptions.filter((val) => !dimensionFilters?.find((dimension) => dimension.dimension === val.value));
```
Comment (iwysiu) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:29]: Maybe add a comment? This bit of logic is a little complex

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx [hunk 4]
```diff
@@ -46,11 +62,17 @@ const DimensionFields: React.FC<DimensionFieldsProps> = ({ query, dimensionOptio
               menuShouldPortal
               placeholder="Field"
               value={filter.dimension}
-              options={dimensionOptions}
+              options={validDimensionOptions}
               onChange={(v) => onFieldChange(index, 'dimension', v.value ?? '')}
               width={38}
             />
-            <InlineLabel aria-label="equals">==</InlineLabel>
+            <Select
```
Comment (iwysiu) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:69]: optional, but it might be nice to set `==` as the default value

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx (hunk 3 above)
Comment (sunker) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:29]: A few nits: 
An undefined dimensionFilters and an empty array both evaluates to false, so you should be able to replace the if condition to `if (query.azureMonitor?.dimensionFilters?.length) {`. 

Think you can also remove the not-null assertion operator from the filter condition. Using the `dimensionFilters?.find` is fine, but using `dimensionFilters?.some` would be a bit more expressive in this case. 

 Maybe a unit test can be added for this?

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx [hunk 5]
```diff
@@ -46,11 +62,17 @@ const DimensionFields: React.FC<DimensionFieldsProps> = ({ query, dimensionOptio
...
+              menuShouldPortal
+              placeholder="Operation"
+              value={filter.operator}
+              options={dimensionOperators}
+              onChange={(v) => onFieldChange(index, 'operator', v.value ?? '')}
+            />
```
Comment (sunker) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:75]: If you want to, you can take a look at how operators are rendered in the CloudMonitoring filter component. There the input control is replaced by a button. I think it looks pretty good in the scenarios where predefined non text values such as operators are listed. I think it would be nice if we could do the same here.

Screenshot from 2022-04-22 09-23-04

https://github.com/grafana/grafana/blob/47427-additional-dimension-operations/public/app/plugins/datasource/cloud-monitoring/components/LabelFilter.tsx#L126

**Review by sunker — COMMENTED** [review]
This looks really promising @aangelisc, great work! 

A question: React select has the option to `allowCustomValue` which gives the user the freedom to add whatever value the want. Could that be an option here so that we provide a workaround in case Azure decides to add support for new operators? Or would that still require manual changes in the backend?

File: pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource.go (hunk 1 above)
Comment (aangelisc) [reply pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource.go:127]: Great catch, missed this 😊 Explains why the below test was passing when it shouldn't of!

File: pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource_test.go (hunk 2 above)
Comment (aangelisc) [reply pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource_test.go:161]: Fixed as per above

File: pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource.go [hunk 6]
```diff
@@ -120,11 +120,16 @@ func (e *AzureMonitorDatasource) buildQueries(queries []backend.DataQuery, dsInf
...
+						dimSB.WriteString(" and ")
+					}
 				}
 			}
+
```
[the remark this answers is not in the document]
Comment (aangelisc) [reply pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource.go:132]: 👍

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx (hunk 4 above)
Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:69]: This makes sense given that in the backend we default to `==` as well.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx (hunk 5 above)
Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:75]: This makes sense for consistency, will take a look at implementing this 😊

Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:75]: On the question of creating a custom operator value if Azure adds a new operator - I don't believe this would work as the display name of the operator doesn't directly match up with the actual value (e.g. `==` in the frontend is translated to `eq`). We could alternatively use the actual API representation however this may not be as appealing. It wouldn't require a change in the backend as we set the appropriate API value in the frontend here: 
image

Comment (sunker) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:116]: Maybe for optional values, it could be fine that the label name and value are the same? `{ label: 'ew', 'value: 'ew }` Thoughts?

Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:116]: I think that'd be a happy medium as, if the user is specifying the operator, the correct value should be passed to the backend.

**Review by dprokop — COMMENTED** [review]
Think this PR would use a rebase: 
image

File: pkg/tsdb/azuremonitor/types/types.go [hunk 7]
```diff
@@ -139,15 +140,27 @@ type AzureMonitorJSONQuery struct {
 // AzureMonitorDimensionFilter is the model for the frontend sent for azureMonitor metric
 // queries like "BlobType", "eq", "*"
 type AzureMonitorDimensionFilter struct {
-	Dimension string `json:"dimension"`
-	Operator  string `json:"operator"`
-	Filter    string `json:"filter"`
+	Dimension string   `json:"dimension"`
+	Operator  string   `json:"operator"`
+	Filter    []string `json:"filter"`
```
Comment (fridgepoet) [inline pkg/tsdb/azuremonitor/types/types.go:145]: From our conversation: suggested moving this change to a separate PR

File: pkg/tsdb/azuremonitor/types/types.go [hunk 8]
```diff
@@ -139,15 +140,27 @@ type AzureMonitorJSONQuery struct {
...
+			var filterStrings []string
+			for _, filter := range a.Filter {
+				filterStrings = append(filterStrings, fmt.Sprintf("%v %v '%v'", a.Dimension, a.Operator, filter))
+			}
+			if a.Operator == "eq" {
+				return strings.Join(filterStrings, " or ")
+			} else {
+				return strings.Join(filterStrings, " and ")
+			}
+		}
```
Comment (fridgepoet) [inline pkg/tsdb/azuremonitor/types/types.go:163]: from our conversation: suggest moving this to a different function more focused on filter construction, will be able to unit test it closer to its declaration

File: pkg/tsdb/azuremonitor/types/types.go (hunk 7 above)
Comment (sunker) [reply pkg/tsdb/azuremonitor/types/types.go:145]: Yeah I'm not sure I follow. Why is this needed? Unless migrated properly in frontend and backend, it will break any existing queries passing `Filter` as a string. Would be good with a new issue that provides context on why this change is necessary.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts [hunk 9]
```diff
@@ -105,11 +105,11 @@ export default class AzureMonitorDatasource extends DataSourceWithBackend<AzureM
     const dimensionFilters = (item.dimensionFilters ?? [])
       .filter((f) => f.dimension && f.dimension !== 'None')
       .map((f) => {
-        const filter = templateSrv.replace(f.filter ?? '', scopedVars);
+        const filter = f.filter?.map((filter) => templateSrv.replace(filter ?? '', scopedVars)).filter((item) => item!);
```
Comment (sunker) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts:108]: Can this last filter be moved to the already existing filter on line 106 so that we don't iterate over all items another time?

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts [hunk 10]
```diff
@@ -105,11 +105,11 @@ export default class AzureMonitorDatasource extends DataSourceWithBackend<AzureM
...
         return {
           dimension: templateSrv.replace(f.dimension, scopedVars),
           operator: f.operator || 'eq',
-          filter: filter || '*', // send * when empty
+          filter: filter, // send * when empty
```
Comment (sunker) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts:112]: comment not useful anymore so can be removed?

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx [hunk 11]
```diff
@@ -11,12 +12,60 @@ interface DimensionFieldsProps extends AzureQueryEditorFieldProps {
...
+            if (labelsObj[dimension]) {
+              labelsObj[dimension].add(value);
+            } else {
+              labelsObj[dimension] = new Set([value]);
+            }
+          }
+        }
+      }
+    }
+    setDimensionLabels((prevLabels) => ({ ...labelsObj, ...prevLabels }));
```
Comment (sunker) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:48]: If I understand correctly, it extracts the labels from all the returned series and put them in a multi select filter? I'm not sure this is correct. data.series returns labels for all queries in a panel - not only for the current query row. To be sure you use labels for the current query, you need to check the frame's refId against the row that is currently being rendered in the editor. 

I think this hook is a bit complicated. Would be nice if you could add some comments on what it does. Also, make sure all args in the arrow functions are properly named. For example `fields.map((item) => item.labels)` could be `fields.map((field) => field.labels)` to make it easier to read the code. 

You can also consider 1) moving this to a custom hook or 2) moving the multi-select filter to a separate component that would also contain this hook.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx [hunk 12]
```diff
@@ -33,12 +82,22 @@ const DimensionFields: React.FC<DimensionFieldsProps> = ({ query, dimensionOptio
     onQueryChange(setDimensionFilterValue(query, filterIndex, fieldName, value));
   };
 
-  const onFilterInputChange = (index: number, ev: React.FormEvent) => {
-    if (ev.target instanceof HTMLInputElement) {
-      onFieldChange(index, 'filter', ev.target.value);
+  const onFilterInputChange = (index: number, v: SelectableValue<string>) => {
+    if (v) {
+      onFieldChange(index, 'filter', [v.value!]);
```
Comment (sunker) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:87]: We should avoid using the non-null assertion operator. If the value is nullable, we should check that this is not the case.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx [hunk 13]
```diff
@@ -33,12 +82,22 @@ const DimensionFields: React.FC<DimensionFieldsProps> = ({ query, dimensionOptio
...
+    } else {
+      onFieldChange(index, 'filter', []);
     }
   };
 
+  const onMultiSelectFilterChange = (index: number, v: Array<SelectableValue<string>>) => {
+    onFieldChange(
+      index,
+      'filter',
+      v.map((item) => item.value!)
```
Comment (sunker) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:97]: same here

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/types/query.ts [hunk 14]
```diff
@@ -87,5 +87,5 @@ export interface AzureResourceGraphQuery {
 export interface AzureMetricDimension {
   dimension: string;
   operator: string;
-  filter?: string;
+  filter?: string[];
```
Comment (sunker) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/types/query.ts:90]: This is problematic. If we don't migrate existing queries, they will still send strings to the backend. If we for some reason don't want to migrate queries in the frontend but rely on backend to handle both, we should at least change typings here to `string | string[]`.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx [hunk 15]
```diff
@@ -48,12 +107,44 @@ const DimensionFields: React.FC<DimensionFieldsProps> = ({ query, dimensionOptio
...
+            <Select
+              menuShouldPortal
+              placeholder="Operation"
+              value={filter.operator}
+              options={dimensionOperators}
+              onChange={(v) => onFieldChange(index, 'operator', v.value ?? '')}
+              allowCustomValue
+            />
+            {filter.operator === 'eq' || filter.operator === 'ne' ? (
+              <MultiSelect
```
Comment (sunker) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:123]: Can you add unit tests for the conditional rendering?

**Review by sunker — COMMENTED** [review]
Added a few more comments. Agree with @fridgepoet - the latest changes to the query model should go in a separate PR.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx (hunk 11 above)
Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:48]: Great catch on needing to check the refId, will update this.

File: pkg/tsdb/azuremonitor/types/types.go (hunk 8 above)
Comment (aangelisc) [reply pkg/tsdb/azuremonitor/types/types.go:163]: Will move this to a separate PR

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx (hunk 12 above)
Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:87]: Corrected, thanks 😊

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx (hunk 15 above)
Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:123]: Will be moved to a separate PR

File: pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource_test.go [hunk 16]
```diff
@@ -130,6 +130,39 @@ func TestAzureMonitorBuildQueries(t *testing.T) {
...
+		{
+			name: "has dimensionFilter*s* property with not equals operator",
+			azureMonitorVariedProperties: map[string]interface{}{
+				"timeGrain":        "PT1M",
+				"dimensionFilters": []types.AzureMonitorDimensionFilter{{Dimension: "blob", Operator: "ne", Filter: "test"}},
+				"top":              "30",
+			},
+			queryInterval:           duration,
+			expectedInterval:        "PT1M",
+			azureMonitorQueryTarget: "%24filter=blob+ne+%27test%27&aggregation=Average&api-version=2018-01-01&interval=PT1M&metricnames=Percentage+CPU&metricnamespace=Microsoft.Compute-virtualMachines&timespan=2018-03-15T13%3A00%3A00Z%2F2018-03-15T13%3A34%3A00Z&top=30",
```
Comment (fridgepoet) [inline pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource_test.go:142]: I was testing it manually (pulled in latest changes from main) and after I clicked on View in Azure Portal, I didn't see the dimension filters I applied there. Just wondering if these expected `azureMonitorQueryTarget` implied I was supposed to see them passed through there.

Comment (aangelisc) [reply pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource_test.go:142]: Great spot here @fridgepoet, I think this is actually a separate issue in how we build the deep link URL for the query. The URL built above is the URL that is used for data retrieval (the query URL). The URL that is built to link back to the Azure portal does not include filters at the moment, maybe something we can look into implementing.

**Review by iwysiu — COMMENTED** [review]
nice! It looks a lot nicer.
Is `eq` supposed to be an option? I opened a fresh panel and go this as the operator options:
Screen Shot 2022-04-27 at 5 40 15 PM

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx [hunk 17]
```diff
@@ -33,12 +89,40 @@ const DimensionFields: React.FC<DimensionFieldsProps> = ({ query, dimensionOptio
...
   };
 
-  const onFilterInputChange = (index: number, ev: React.FormEvent) => {
-    if (ev.target instanceof HTMLInputElement) {
-      onFieldChange(index, 'filter', ev.target.value);
+  const onFilterInputChange = (index: number, v: SelectableValue<string>) => {
+    if (v) {
+      onFieldChange(index, 'filter', v.value);
+    } else {
+      onFieldChange(index, 'filter', '');
```
Comment (sunker) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:96]: Is this necessary? I think the if else condition can be replaced with `v && onFieldChange(index, 'filter', v.value);`

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx [hunk 18]
```diff
@@ -48,12 +132,28 @@ const DimensionFields: React.FC<DimensionFieldsProps> = ({ query, dimensionOptio
...
+              allowCustomValue
+            />
+            <Select
+              menuShouldPortal
+              placeholder="Select value"
+              value={filter.filter ? filter.filter : ''}
+              allowCustomValue
+              options={getValidFilterOptions(filter.filter, filter.dimension)}
+              onChange={(v) => onFilterInputChange(index, v)}
+              isClearable
```
Comment (sunker) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:154]: Should `isClearable` allow you to completely clear the select? It wasn't working for me. Probably doing something wrong, but if not this is an issue in grafana ui so nothing to care about in this pr.,

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx [hunk 19]
```diff
@@ -48,12 +132,28 @@ const DimensionFields: React.FC<DimensionFieldsProps> = ({ query, dimensionOptio
...
+              placeholder="Operation"
+              value={filter.operator}
+              options={getValidOperators(filter.operator)}
+              onChange={(v) => onFieldChange(index, 'operator', v.value ?? '')}
+              allowCustomValue
+            />
+            <Select
+              menuShouldPortal
+              placeholder="Select value"
+              value={filter.filter ? filter.filter : ''}
```
Comment (sunker) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:150]:
```suggestion
              value={filter.filter ?? ''}
```

**Review by sunker — COMMENTED** [review]
Looks good, great stuff @aangelisc! Wasn't able to find a metric that has dimension labels attached to it so couldn't test filter values properly. Let's discuss this offline.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.test.tsx [hunk 20]
```diff
@@ -0,0 +1,137 @@
...
+      />
+    );
+    const addDimension = await screen.findByText('Add new dimension');
+    await user.click(addDimension);
+    mockQuery = appendDimensionFilter(mockQuery);
+    expect(onQueryChange).toHaveBeenCalledWith({
+      ...mockQuery,
+      azureMonitor: { ...mockQuery.azureMonitor, dimensionFilters: [{ dimension: '', operator: 'eq', filter: '*' }] },
+    });
+    render(
```
[the remark this answers is not in the document]
Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.test.tsx:50]: This should rerender otherwise we'd be testing against the original component.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.test.tsx [hunk 21]
```diff
@@ -0,0 +1,137 @@
...
+        variableOptionGroup={variableOptionGroup}
+        setError={() => {}}
+        dimensionOptions={dimensionOptions}
+      />
+    );
+    const dimensionSelect = await screen.findByText('Field');
+    await selectOptionInTest(dimensionSelect, 'Test Dimension 1');
+    expect(screen.queryByText('Test Dimension 1')).toBeInTheDocument();
+    expect(screen.queryByText('==')).toBeInTheDocument();
+  });
```
[the remark this answers is not in the document]
Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.test.tsx:66]: Yep! Good shout, have added this in.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx (hunk 17 above)
Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/DimensionFields.tsx:96]: Have replaced this with ```  const onFilterInputChange = (index: number, v: SelectableValue<string> | null) => {
    onFieldChange(index, 'filter', v?.value ?? '');
  };```

It's necessary as a null value is passed if the filters are cleared so we handle that accordingly.

**Comment by sunker** [comment]
Might be missing something here but I'm still not able to get any filter value options when using the dashboard you shared with me? 

azuredimension

**Comment by aangelisc** [comment]
> Might be missing something here but I'm still not able to get any filter value options when using the dashboard you shared with me?
> 
> azuredimension

Ah thank you for this! It's because of the new ResourcePicker, will push a commit to rectify this now.

**Review by sunker — APPROVED** [review]
Tested and it works really well! Fantastic work on this @aangelisc! Don't forget to add the `add-to-changelog` label. Also, would it be possible to make the PR title a little more informative? This is the text that will end up in the [changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md) eventually.

**Comment by sunker** [comment]
@aangelisc the automatic backport job failed, probably due to a merge conflict, so it needs to be done manually. See instructions on how to do it manually in comment above. Let me know if you need help!
