### PR TITLE
CodeEditor: Ensure suggestions only apply to the instance of the editor that registered them

### LINKED ISSUE #69262: GrafanaUI: CodeEditor shows duplicate suggestions
### 
# What went wrong?

**What happened**:

  - The `CodeEditor` component is showing duplicated suggestions:
image (2)
  - Originally raised in [Slack](https://raintank-corp.slack.com/archives/CT7S455SP/p1685451142475929), possible reason: "The autocomplete list I'm passing does not have any duplicates whatsoever, but based on what I read this is due to not disposing the editor/suggestions, although I see the suggestions are being disposed, but the editor instance seems not"

**What did you expect to happen**:

  - `CodeEditor` to only show a suggestion once

### 
# How do we reproduce it?

**Step 1**:

- Go to any integrations page (example https://ops.grafana-ops.net/a/grafana-oncall-app/integrations_2/CZ6894HY84ULC?p=8)

**Step 2**:

- Open the edit icon on the Templates block

**Step 3**:

- Click on any template from the Drawer to edit (click edit icon)

**Step 4**:

- Try suggestions in the template editor (Ctrl + Space)

### 
# What Grafana version are you using?

v10.1.0-pre

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- passes the `modelId` when registering suggestions
  - this ensures that future calls to `provideCompletionItems` can check the `modelId` against the registered `modelId`
    - if they match -> great, show suggestions
    - if they don't -> don't show these suggestions

**Why do we need this feature?**

- so suggestions don't bleed between editor instances/are duplicated

**Who is this feature for?**

- anyone using `CodeEditor` 

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/69262

**Special notes for your reviewer:**

i tried to look for a way to write a test that would prevent regressions to this... but i don't think it's possible in react-testing-library 😬 

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/Monaco/CodeEditor.tsx [hunk 1]
```diff
@@ -85,20 +86,21 @@ class UnthemedCodeEditor extends PureComponent<Props> {
 
   handleBeforeMount = (monaco: Monaco) => {
     this.monaco = monaco;
-    const { language, getSuggestions, onBeforeEditorMount } = this.props;
 
-    if (getSuggestions) {
-      this.completionCancel = registerSuggestions(monaco, language, getSuggestions);
-    }
```
Comment (tskarhed) [inline packages/grafana-ui/src/components/Monaco/CodeEditor.tsx:92]: What is the logical difference ebtween doing this onMount instead of beforeMount?

File: packages/grafana-ui/src/components/Monaco/CodeEditor.tsx [hunk 2]
```diff
@@ -85,20 +86,21 @@ class UnthemedCodeEditor extends PureComponent<Props> {
...
+    const { onBeforeEditorMount } = this.props;
 
     onBeforeEditorMount?.(monaco);
   };
 
   handleOnMount = (editor: MonacoEditorType, monaco: Monaco) => {
-    const { onChange, onEditorDidMount } = this.props;
+    const { getSuggestions, language, onChange, onEditorDidMount } = this.props;
 
+    this.modelId = editor.getModel()?.id;
```
Comment (tskarhed) [inline packages/grafana-ui/src/components/Monaco/CodeEditor.tsx:98]: This doesn't require a URI? :open_mouth:

**Review by tskarhed — COMMENTED** [review]
Edit: No tests for this one then :cry:

File: packages/grafana-ui/src/components/Monaco/CodeEditor.tsx (hunk 2 above)
Comment (ashharrison90) [reply packages/grafana-ui/src/components/Monaco/CodeEditor.tsx:98]: nope, i think because the model is associated with this editor (as opposed to getting it from the global monaco namespace)

File: packages/grafana-ui/src/components/Monaco/CodeEditor.tsx (hunk 1 above)
Comment (ashharrison90) [reply packages/grafana-ui/src/components/Monaco/CodeEditor.tsx:92]: i guess it will happen slightly later, but by doing it `onMount` we get access to the editor instance, whereas before mount we only have access to the global monaco instance

**Review by tskarhed — APPROVED** [review]
