### PR TITLE
Make sure big lists of suggestions don't expand outside of the viewport

### LINKED ISSUE #31192: Data link variable suggestions extend beyond window boundaries in Chrome
**What happened**:

When I type `$` in a data-link entry window, the list of suggested variables extends past the top of the browser window:

image

(Note that the light gray area at the top of the screenshot is the bottom of my bookmarks bar, i.e., the top of the rendering area for the page)

I cannot see all of the suggestions, and I cannot scroll the list. I _can_ use the arrow keys to navigate the selection highlight past the top of the visible area and select invisible options, but it does not scroll them into view.

**What you expected to happen**:

I expect to be able to either see all of the suggestions, or at least have a scrollable list.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard
2. Create a fair number of dashboard variables.
3. Create and edit a panel, giving it a query that returns multiple series.
4. Create a data link.
5. In the data link entry window, type a `$`.

**Environment**:
- Grafana version: 7.4.1
- Data source type & version: InfluxDB 2.0, Flux
- OS Grafana is installed on: Alpine Linux (official docker image `grafana/grafana:7.4.1`)
- User OS & Browser: Windows 10, Chrome 88.0.4324.150
- Grafana plugins: None other than the defaults that ship with the base docker image.
- Others:

### PR DESCRIPTION
**Pull request by oscarkilhed**
**What this PR does / why we need it:**
Sets a max size for the suggestions list and adds a scrollbar.

Sets the z-index of the scrollbars as they ended up underneath the data links modal.

Moves the scrollbar when the user uses keyboard to select suggestions.

**Which issue(s) this PR fixes:**
Fixes #31192

**Special notes for your reviewer:**
Not entirely sure this use of refs is kosher. Not completely confident in my use of react yet :)

Might have to pass the z-index of the scrollbars to the CustomScrollbar. Not sure if setting this for every use of CustomScrollbar is ok.

### CODE REVIEW

File: packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx [hunk 1]
```diff
@@ -146,13 +146,15 @@ const getStyles = (theme: GrafanaThemeV2) => {
         right: 0px;
         bottom: ${theme.spacing(0.25)};
         top: ${theme.spacing(0.25)};
+        z-index: 1;
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx:149]: nit: I think we have z-indexes in the theme, maybe it needs a new addition?

File: packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx [hunk 2]
```diff
@@ -81,6 +82,12 @@ export const DataLinkInput: React.FC<DataLinkInputProps> = memo(
     const stateRef = useRef({ showingSuggestions, suggestions, suggestionsIndex, linkUrl, onChange });
     stateRef.current = { showingSuggestions, suggestions, suggestionsIndex, linkUrl, onChange };
 
+    // Used to get the height of the suggestion elements in order to scroll to them.
+    const selectedRef = useRef<HTMLDivElement>(null);
+    function getScrollTop() {
+      return (selectedRef.current?.clientHeight ?? 0) * suggestionsIndex;
+    }
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx:89]: Maybe use `useMemo` here instead and use the `scrollTop` value in CustomScrollbar? I mention this because it seems like everything in this component is optimized.

```suggestion
    const scrollTop = useMemo(() => (selectedRef.current?.clientHeight ?? 0) * suggestionsIndex, [
      selectedRef,
      suggestionsIndex,
    ]);
```

**Review by hugohaggmark — APPROVED** [review]
Magnificent work on this and it works as expected! 🎉  Not an expert if this is an ok usage of useRef or not though.

File: packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx (hunk 2 above)
Comment (dprokop) [reply packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx:89]: Using ref as a hook dependency is an antipattern (read more here https://medium.com/@teh_builder/ref-objects-inside-useeffect-hooks-eb7c15198780).

What you can do instead, to avoid this function creation is to declare it outside of the component scope and make it accept a dom element as an argument;

```
function getScrollTop(el, suggestionsIndex) {
  return (el.clientHeight ?? 0) * suggestionsIndex;
  }
```

Then the scrollTop will invalidate only on index change (which I think is sufficient):

```
const scrollTop = useMemo(() => getScrollTop(selectedRef.current, suggestionsIndex), [
	      suggestionsIndex,
	    ]);

File: packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx [hunk 3]
```diff
@@ -172,12 +179,15 @@ export const DataLinkInput: React.FC<DataLinkInputProps> = memo(
...
-                          onClose={() => setShowingSuggestions(false)}
-                          activeIndex={suggestionsIndex}
-                        />
+                        <CustomScrollbar scrollTop={getScrollTop()} autoHeightMax="190px">
+                          <DataLinkSuggestions
+                            selectedRef={selectedRef}
+                            suggestions={stateRef.current.suggestions}
+                            onSuggestionSelect={onVariableSelect}
+                            onClose={() => setShowingSuggestions(false)}
+                            activeIndex={suggestionsIndex}
```
Comment (dprokop) [inline packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx:188]: Nit, naming: we have activeIndex and selectedRef - let's unify those:

```suggestion
                            activeItemRef={selectedRef}
                            suggestions={stateRef.current.suggestions}
                            onSuggestionSelect={onVariableSelect}
                            onClose={() => setShowingSuggestions(false)}
                            activeIndex={suggestionsIndex}
```

File: packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx [hunk 4]
```diff
@@ -172,12 +179,15 @@ export const DataLinkInput: React.FC<DataLinkInputProps> = memo(
                   {({ ref, style, placement }) => {
                     return (
                       <div ref={ref} style={style} data-placement={placement}>
-                        <DataLinkSuggestions
-                          suggestions={stateRef.current.suggestions}
-                          onSuggestionSelect={onVariableSelect}
-                          onClose={() => setShowingSuggestions(false)}
-                          activeIndex={suggestionsIndex}
-                        />
+                        <CustomScrollbar scrollTop={getScrollTop()} autoHeightMax="190px">
```
Comment (dprokop) [inline packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx:182]: @oscarkilhed can you make the popover bigger? 190px feels and looks super tiny when interacting with the suggestions; 300px looks better IMO

File: packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx (hunk 2 above)
Comment (hugohaggmark) [reply packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx:89]: Aha, outstanding catch @dprokop 🎉

File: packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx (hunk 4 above)
Comment (oscarkilhed) [reply packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx:182]: Good point, 190px was very good in terms of not going outside of the viewport even with a very small viewport. But it does make the "normal" use case a bit worse. The popper doesn't compress, so with a very small viewport there will be some suggestions hidden. Unless we shrink the CustomScrollbar when the viewport is tiny.

File: packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx (hunk 1 above)
Comment (oscarkilhed) [reply packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx:149]: I just realized the only reason we need this is because the datalink suggestions has a wrapper with z-index: 1. Not sure that's needed. Can possibly remove that and this.

File: packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx (hunk 2 above)
Comment (oscarkilhed) [reply packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx]: implemented, also improved naming a bit (subjective)

File: packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx (hunk 1 above)
Comment (oscarkilhed) [reply packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx]: Tested removing the z-index, works on all places the the DataLinkSuggestions is used in both chrome and ff
