### PR TITLE
Handle scalar and string resultType separately

### LINKED ISSUE #51313: Prometheus datasource: query_result([prometheus scalar]) is broken
**What happened**:
Tried to use `query_result()` on a PromQL scalar within a dashboard variable:
image (5)
Specifically `query_result(scalar(grafanacloud_instance_active_series{id="47882"}))` on the `grafanacloud-usage` datasource

**What you expected to happen**:
The "Preview of values" to contain the same integer as I get when I send the query to the `/query` Prometheus API endpoint.

**How to reproduce it (as minimally and precisely as possible)**:
You can reproduce the error by adding a variable with Query `query_result(1+1)`. If you can fix that, I'm pretty sure the whole issue will be fixed.

**Anything else we need to know?**:
There is a workaround, for anyone else looking for this:
https://stackoverflow.com/a/54247340/1358187

> Your Query should be: `query_result(passed_tests_total{job="MyJob"})a
> 
> And the Regex to extract just the value of metric should be `/.* ([^\ ]*) .*/`.

### PR DESCRIPTION
**Pull request by itsmylife**
Fixes https://github.com/grafana/grafana/issues/51313

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/metric_find_query.ts [hunk 1]
```diff
@@ -141,22 +141,35 @@ export default class PrometheusMetricFindQuery {
...
-            }).join(',') +
-            '}';
-          text += ' ' + metricData.value[1] + ' ' + metricData.value[0] * 1000;
-
-          return {
-            text: text,
-            expandable: true,
-          };
-        });
+        switch (result.data.data.resultType) {
```
Comment (itsmylife) [inline public/app/plugins/datasource/prometheus/metric_find_query.ts:144]: https://prometheus.io/docs/prometheus/latest/querying/api/#expression-query-result-formats

File: public/app/plugins/datasource/prometheus/metric_find_query.ts [hunk 2]
```diff
@@ -141,22 +141,35 @@ export default class PrometheusMetricFindQuery {
...
+                '}';
+              text += ' ' + metricData.value[1] + ' ' + metricData.value[0] * 1000;
+
+              return {
+                text: text,
+                expandable: true,
+              };
+            });
+          default:
+            throw Error(`Unknown/Unhandled result type: [${result.data.data.resultType}]`);
```
Comment (itsmylife) [inline public/app/plugins/datasource/prometheus/metric_find_query.ts:171]: I throw error since those are being handled and showed with a red notification. But not sure it is the best way to do it here.

Comment (srclosson) [reply public/app/plugins/datasource/prometheus/metric_find_query.ts:171]: Just my opinion, but it's always best to throw an error when it does not make sense to handle it. So, this looks fine to me. With that said, what about instant vectors? Are they handled somewhere else?

File: .betterer.results [hunk 3]
```diff
@@ -10336,13 +10336,13 @@ exports[`better eslint`] = {
       [216, 21, 3, "Unexpected any. Specify a different type.", "193409811"],
       [240, 21, 3, "Unexpected any. Specify a different type.", "193409811"]
     ],
-    "public/app/plugins/datasource/prometheus/metric_find_query.ts:3246701167": [
+    "public/app/plugins/datasource/prometheus/metric_find_query.ts:1417569751": [
```
Comment (srclosson) [inline .betterer.results:10339]: Not sure what this is? Would you mind explaining the intent here?

Comment (itsmylife) [reply .betterer.results:10339]: betterer is a tool to track code quality. the idea is to have fewer `any` types in typescript code. So we would have even stronger typed code. Since my changes interacted with a code that has type `any` it warns me to fix it. But in my case, I cannot focus on that in this PR. So with running `yarn bettered -u` I add those lines to results so it can be ignored for now.
https://github.com/grafana/grafana/blob/main/contribute/create-pull-request.md#betterer

File: public/app/plugins/datasource/prometheus/metric_find_query.ts (hunk 1 above)
Comment (aocenas) [reply public/app/plugins/datasource/prometheus/metric_find_query.ts:144]: Looks good but could we add a test case for this?

File: .betterer.results [hunk 4]
```diff
@@ -10336,13 +10336,13 @@ exports[`better eslint`] = {
...
       [62, 70, 3, "Unexpected any. Specify a different type.", "193409811"],
       [83, 72, 3, "Unexpected any. Specify a different type.", "193409811"],
       [96, 72, 3, "Unexpected any. Specify a different type.", "193409811"],
       [122, 70, 3, "Unexpected any. Specify a different type.", "193409811"],
       [140, 43, 35, "Do not use any type assertions.", "2712117061"],
-      [175, 70, 3, "Unexpected any. Specify a different type.", "193409811"]
+      [188, 70, 3, "Unexpected any. Specify a different type.", "193409811"]
```
Comment (aocenas) [inline .betterer.results:10345]: Hmm feels weird that this small change made such a difference. I thought you had a problem in some test code.

File: public/app/plugins/datasource/prometheus/metric_find_query.ts (hunk 1 above)
Comment (itsmylife) [reply public/app/plugins/datasource/prometheus/metric_find_query.ts:144]: @aocenas Please check https://github.com/grafana/grafana/pull/51411/commits/6bcf1e4fb437cd1ddf9fab511b35b20979f937e3

**Review by aocenas — APPROVED** [review]
Looks good but tbh don't understand the need for betterer changes. Seems like a big difference in numbers when only a few lines have changed.

**Comment by itsmylife** [comment]
> Looks good but tbh don't understand the need for betterer changes. Seems like a big difference in numbers when only a few lines have changed.

After adding the test case, to the test file I saw there are some `any`s so I decided to handle them. In the new case, we have less `any`. So that's why we have a big difference.
