### PR TITLE
XYChart: Fix variable interpolation in datalinks/toggletip

### LINKED ISSUE #64464: XY Chart: Data link interpolation not working
**What happened**:
The functionality I'm trying to replicate is that the Bubble chart drives my dashboard - if a user clicks a bubble, the rest of the charts show a specific view of that particular country.

**What you expected to happen**:
Reload the dashboard with a new template variable based on the circle I clicked

**How to reproduce it (as minimally and precisely as possible)**:
https://play.grafana.org/d/_KUTfkjnk/gapminder-ish-hans-rosling?orgId=1&viewPanel=20

**Anything else we need to know?**:
image

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/grafana/issues/64464

mostly aped from the code below (this is copy-pasted in more than a few places in the codebase already):

https://github.com/grafana/grafana/blob/b963defa44ef264a88e3dd862b9e91d026102e5c/public/app/features/visualization/data-hover/DataHoverView.tsx#L63-L80

i pulled the bit of logic for falling back to domain link text from the explore datalink generator, as it was working before.

### CODE REVIEW

File: public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx [hunk 1]
```diff
@@ -79,9 +79,7 @@ export const TimeSeriesPanel = ({
       options={options}
     >
       {(config, alignedDataFrame) => {
-        if (
-          alignedDataFrame.fields.filter((f) => f.config.links !== undefined && f.config.links.length > 0).length > 0
-        ) {
+        if (alignedDataFrame.fields.some((f) => Boolean(f.config.links?.length))) {
```
Comment (leeoniya) [inline public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx:82]: drive-by optimization / simplification. (logic should be same)

**Review by nmarrs — APPROVED** [review]
