### PR TITLE
Pyroscope: Fix stale value for query in query editor

### LINKED ISSUE #80502: Pyroscope: Sub-group selection profiling resets on query change
### What happened?

In a system where two separate processes are being profiled, it appears that that the sub-path for a profile is being consistently reset to the first item in the list.

For example, in a situation where the main profling group is `process_cpu` and there are four sub-groups, two of which associated with each process:
* cpu - Process 1
* samples - Process 1
* samples - Process 2 (unsure why this shows up as a separate sub-group, given that it already exists for Process 1 as well)
* wall - Process 2

Selecting `process_cpu.wall` and then adding the query `{service_name="Process 1"}` yields results on a `Run query`, event though the Process 1 service does not include data in the `process_cpu.wall` group. Re-selecting `process_cpu.wall` and then running the query correctly shows no results.

Conversely, selecting the `process_cpu.wall` group and then changing the query to `{service_name="Process 2"}` shows no results, where it should. Re-selecting `process_cpu.wall` and then running a query then correctly shows the expected results.

It appears that the sub-group for the group is being reset to the first item/index in the sub-group when a query is entered. This should not change.

Additionally, only one process is showing up for autocompletion in the `service_name` tag, instead of all processes.

### What did you expect to happen?

The query should return all valid results for the group selected, when a new query is entered and not require the re-selecting of the specific group before running that query.

### Did this work before?

This worked correctly in Grafana 10.2.1.

### How do we reproduce it?

1. Use the [Intro to MLTP repo branch with updated components](https://github.com/grafana/intro-to-mltp/tree/hedss-update-component-versions)
2. `docker compose up`
3. Navigate to the Explorer, select `Pryoscope`
4. Select the `process_cpu.wall` subgroup.
5. Follow the examples in the attached video.
PyroscopeIssues

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: v10.2.3
OS: MacOS/Docker Compose
Browser: https://www.whatsmybrowser.org/b/OIAO0

### Grafana platform?

Docker

### Datasource(s)?

Pyroscope

### LINKED ISSUE #80765: Profiling: Explore query resets when typging
### What happened?

https://github.com/grafana/grafana/assets/23323466/ab87fed2-454b-4119-a4da-109221449e09

When typing the type in the profile type dropdown resets back to a different item

### What did you expect to happen?

I expect it to not reset and stay as what I selected 

### Did this work before?

Yes

### How do we reproduce it?

1. Go to the explore page
2. change the profile type to something else 
3. start typing

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

sedemo environment

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by joey-grafana**
**What is this feature?**

Fixes issue with stale query value in Pyroscope query editor.

**Why do we need this feature?**

We need to reference the query as otherwise when it's passed into useLabels, only the initial value of the query is passed into the LabelsEditor (onChange) which renders the CodeEditor for Monaco. The above needs to have a ref to the query so it can get the latest value.

**Who is this feature for?**

Tempo users/

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/80502
Fixes https://github.com/grafana/grafana/issues/80765

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/datasource/grafana-pyroscope-datasource/QueryEditor/QueryEditor.tsx [hunk 1]
```diff
@@ -142,28 +148,28 @@ function useLabels(
...
 
   // Create a function with range and query already baked in, so we don't have to send those everywhere
   const getLabelValues = useCallback(
     (label: string) => {
-      let labelSelector = createSelector(query.labelSelector, query.profileTypeId, label);
+      const labelSelector = createSelector(queryRef.current.labelSelector, queryRef.current.profileTypeId, label);
       return datasource.getLabelValues(labelSelector, label, unpreciseRange.from, unpreciseRange.to);
     },
-    [datasource, query.labelSelector, query.profileTypeId, unpreciseRange.to, unpreciseRange.from]
+    [queryRef, datasource, unpreciseRange.from, unpreciseRange.to]
```
Comment (aocenas) [inline public/app/plugins/datasource/grafana-pyroscope-datasource/QueryEditor/QueryEditor.tsx:167]: I don't think we need to change these callbacks. When the query changes the callback should be recreated with the newest query and there should not be an issue here.

File: public/app/plugins/datasource/grafana-pyroscope-datasource/QueryEditor/QueryEditor.tsx [hunk 2]
```diff
@@ -142,28 +148,28 @@ function useLabels(
...
   );
 
   const onChangeDebounced = debounce((value: string) => {
     if (onChange) {
-      onChange({ ...query, labelSelector: value });
+      onChange({ ...queryRef.current, labelSelector: value });
```
Comment (aocenas) [inline public/app/plugins/datasource/grafana-pyroscope-datasource/QueryEditor/QueryEditor.tsx:172]: I think this is the root cause, because we don't update the query in here. So we can either minimize the code change and only use a ref for this without needing it in other places while keeping the the hook signature bit cleaner or we can change the usage a to pass the query to the debounce function when used.

Also it's not clear to me why these `onChangeDebounced` and `onLabelSelectorChange` are lumped together in this single hook if they don't need anything from the other code.

Would probably opt to separate them to their own hook and use the queryRef just inside of it that way I think it would be much clearer why the ref is needed.

Comment (joey-grafana) [reply public/app/plugins/datasource/grafana-pyroscope-datasource/QueryEditor/QueryEditor.tsx:172]: Ahh yes this is much cleaner to use a separate hook. I appreciate your detailed comment. Not 100% sure I addressed it all but at least the purpose of the ref is a lot more clear now without providing a ref in places it is unnecessary.

File: public/app/plugins/datasource/grafana-pyroscope-datasource/QueryEditor/QueryEditor.tsx [hunk 3]
```diff
@@ -27,8 +27,15 @@ export function QueryEditor(props: Props) {
     onRunQuery();
   }
 
+  // Need to reference the query as otherwise when the label selector is changed, only the initial value
+  // of the query is passed into the LabelsEditor (onChange) which renders the CodeEditor for monaco.
+  // The above needs to have a ref to the query so it can get the latest value.
+  const queryRef = useRef(query);
+  queryRef.current = query;
```
Comment (aocenas) [inline public/app/plugins/datasource/grafana-pyroscope-datasource/QueryEditor/QueryEditor.tsx:34]: Nice yeah this is what I had in mind but I also think we can move the definition of the ref inside the `useLabelSelector`. That way the whole thing is encapsulated and a single "unit" so to say. It shouldn't change the functionality as the variable capturing happens inside `useLabelSelector` and the queryRef now isn't needed anywhere else anyway.

Comment (joey-grafana) [reply public/app/plugins/datasource/grafana-pyroscope-datasource/QueryEditor/QueryEditor.tsx]: Awh my God, yeah makes sense, thanks for the re-review!

**Review by aocenas — APPROVED** [review]
Nice looks great
