### PR TITLE
Alerting: Prevents creating alerts from unsupported queries

### LINKED ISSUE #19087: Alerting: When adding alert for query that uses variable there's no validation
**What happened**:
Given a query using variables and switching to the alert tab I was presented with the Create Alert CTA, clicked on Create Alert, added a condition and tested the alert rule and the result is that query returned no series.

**What you expected to happen**:
I had expected to get a validation error instead of the Create Alert CTA. If that's not possible I would have expected the validation error to be shown at least when testing the alert rule.

**How to reproduce it (as minimally and precisely as possible)**:
1. Import below dashboard json and select `gdev-elasticsearch-v7-metrics` as datasource and make sure to start elastic7 from devenv.
2. Go into panel and select Alert tab, Create Alert, set condition and test alert rule.

<details><summary>Dashboard json</summary>

```json
{
  "__inputs": [
    {
      "name": "DS_GDEV-ELASTICSEARCH-V7-METRICS",
      "label": "gdev-elasticsearch-v7-metrics",
      "description": "",
      "type": "datasource",
      "pluginId": "elasticsearch",
      "pluginName": "Elasticsearch"
    }
  ],
  "__requires": [
    {
      "type": "datasource",
      "id": "elasticsearch",
      "name": "Elasticsearch",
      "version": "1.0.0"
    },
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "6.4.0-pre"
    },
    {
      "type": "panel",
      "id": "graph",
      "name": "Graph",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "iteration": 1568366463502,
  "links": [],
  "panels": [
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "${DS_GDEV-ELASTICSEARCH-V7-METRICS}",
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 10,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "options": {
        "dataLinks": []
      },
      "percentage": false,
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "bucketAggs": [
            {
              "fake": true,
              "field": "@hostname",
              "id": "3",
              "settings": {
                "min_doc_count": 1,
                "order": "desc",
                "orderBy": "_term",
                "size": "10"
              },
              "type": "terms"
            },
            {
              "field": "@timestamp",
              "id": "2",
              "settings": {
                "interval": "1m",
                "min_doc_count": 0,
                "trimEdges": 0
              },
              "type": "date_histogram"
            }
          ],
          "metrics": [
            {
              "field": "select field",
              "id": "1",
              "type": "count"
            }
          ],
          "query": "@hostname:$hostname",
          "refId": "A",
          "timeField": "@timestamp"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Panel Title",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "schemaVersion": 19,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {},
        "datasource": "${DS_GDEV-ELASTICSEARCH-V7-METRICS}",
        "definition": "{\"find\": \"terms\", \"field\": \"@hostname\"}",
        "hide": 0,
        "includeAll": true,
        "label": null,
        "multi": true,
        "name": "hostname",
        "options": [],
        "query": "{\"find\": \"terms\", \"field\": \"@hostname\"}",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "",
  "title": "Elasticsearch 7 alert test with variable",
  "uid": "0p_vPscZz",
  "version": 1
}
```
</details>

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest master (81ec76bdef03e3706bd7502703a58f6195c5e70f)
- Datasource: Datasources supported validating if queries contains template variables, e.g. Elasticsearch, Prometheus, Graphite etc

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR validates the queries when the Alerting tab is chosen and displays a validation message if the query/queries are unsupported. This forces the creation of alerts to query/queries that are supported.
image

**Which issue(s) this PR fixes**:
Fixes #19087

**Special notes for your reviewer**:
Haven't been able to test transformations because I don't know how to use them 😄

### CODE REVIEW

File: public/app/features/alerting/AlertTab.tsx [hunk 1]
```diff
@@ -1,34 +1,47 @@
...
 import StateHistory from './StateHistory';
 import 'app/features/alerting/AlertTabCtrl';
-
 // Types
 import { DashboardModel } from '../dashboard/state/DashboardModel';
 import { PanelModel } from '../dashboard/state/PanelModel';
 import { TestRuleResult } from './TestRuleResult';
 import { AlertBox } from 'app/core/components/AlertBox/AlertBox';
-import { AppNotificationSeverity } from 'app/types';
+import { AppNotificationSeverity, StoreState } from 'app/types';
```
Comment (hugohaggmark) [inline public/app/features/alerting/AlertTab.tsx]: Seems WebStorm has reordered my imports, will fix.

**Review by torkelo — COMMENTED** [review]
Will try to review in more detail later.

**Comment by torkelo** [comment]
Screen Shot 2019-09-20 at 09 58 31

there is this 0 :)

**Comment by hugohaggmark** [comment]
> Screen Shot 2019-09-20 at 09 58 31
> 
> there is this 0 :)

How did you managed to get this?

File: public/app/features/alerting/AlertTab.tsx [hunk 2]
```diff
@@ -1,34 +1,46 @@
...
+import { PanelEditorTabIds, getPanelEditorTab } from '../dashboard/panel_editor/state/reducers';
+import { changePanelEditorTab } from '../dashboard/panel_editor/state/actions';
 
 interface Props {
   angularPanel?: AngularComponent;
   dashboard: DashboardModel;
   panel: PanelModel;
+  changePanelEditorTab?: typeof changePanelEditorTab;
```
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply public/app/features/alerting/AlertTab.tsx]: Good catch, I'll fix those.

File: public/app/features/dashboard/panel_editor/state/reducers.ts [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+        tabs,
+      };
+    },
+  })
+  .addMapper({
+    filter: panelEditorCleanUp,
+    mapper: (): PanelEditorState => initialState,
+  })
+  .addMapper({
+    filter: panelEditorChangeTab,
```
Comment (torkelo) [inline public/app/features/dashboard/panel_editor/state/reducers.ts]: Having to keep two separate states in sync now (activeTab from url and the new redux state) is that ideal?  Before it was only the location query param, and now we have two states that that need to be kept in sync. Seeing a bug where if we update query tab via browser back button it does not change tab in Grafana (this seems to be a bug in master as well).

**Comment by torkelo** [comment]
To get the zero in the AlertTab
 
* first create a transformation
* go to alert tab view warning
* remove transformation
* Go back to alert tab and create alert

File: public/app/features/dashboard/panel_editor/state/reducers.ts (hunk 3 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/panel_editor/state/reducers.ts]: Good points I will look into this closer

**Comment by hugohaggmark** [comment]
> To get the zero in the AlertTab
> 
> * first create a transformation
> * go to alert tab view warning
> * remove transformation
> * Go back to alert tab and create alert

How do I create a transformation? 😄

**Review by marefr — CHANGES_REQUESTED** [review]
Functionality wise it's a huge improvement :star2: and my use cases except one I tried with variables and transformation works as expected. 

Not working:
From alert list (http://localhost:3000/alerting/list) clicking on an alert rule doesn't take me to the alert tab, instead queries tab.

 This is interesting - can we update style of the bottom one?
image

File: public/app/features/dashboard/panel_editor/state/reducers.ts (hunk 3 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/panel_editor/state/reducers.ts]: Using only the prop from `location` now so that we can navigate to a tab from outside PanelEditor, again good catch!

Comment (torkelo) [reply public/app/features/dashboard/panel_editor/state/reducers.ts]: great!

**Review by marefr — APPROVED** [review]
From alert list (http://localhost:3000/alerting/list) clicking on an alert rule does now take me to the alert tab. Anything else you want tested?

**Comment by hugohaggmark** [comment]
> From alert list (http://localhost:3000/alerting/list) clicking on an alert rule does now take me to the alert tab. Anything else you want tested?

Thanks, that will do I think!

**Review by torkelo — APPROVED** [review]
Looks good! Great job & nice refactoring!
