### PR TITLE
Navigation: Don't round app plugin icon images

### LINKED ISSUE #44446: Grafana 8.3.3 application plugin small logo is clipped by border-radius of 50%
**What happened**:
In an application plugin the small logo is clipped by border-radius of 50%. 

In plugin.json
```
{
//...
 "info": {
    "keywords": ["plugins"],
    "logos": {
      "small": "img/small-light.svg", // <<<----- clipped
      "large": "img/large.svg"
    },
   /...
  },
//...
}
```

Example of the issue:
Screen Shot 2022-01-25 at 9 42 41 AM

**What you expected to happen**:
Expectation is that the side menu icon button logo would not be clipped by a border radius. It would be nice if I could match the behavior of the built in svg icons. 

**How to reproduce it (as minimally and precisely as possible)**:
1. create an application plugin
2. declare a logo of 24px by 24px, a square logo
3. Load the grafana web site, and ensure that plugin is enabled
4. On the left sidemenu, the icon will be clipped

**Anything else we need to know?**: Below...

**Environment**: any
- Grafana version: 8.3.3
- Data source type & version: N/A
- OS Grafana is installed on: osx
- User OS & Browser: chrome
- Grafana plugins: Custom application plugin
- Others: N/A

## Cause:
The SASS definition will add a border radius when dom elements in side menu are an image. This same case is used for the profile avatar. The default svg side menu icons are native svg and not rendered with img tag. 

This looks like it may be the SASS definition for adding border radius in _sidemenu.scss.
Screen Shot 2022-01-25 at 9 40 56 AM

### PR DESCRIPTION
**Pull request by joshhunt**
**What this PR does / why we need it**:

Stops the `border-radius: 50%` on all images in the side nav, which was clipping App plugin icons (including Grafana's!)

 - Made a new `<NavBarItemIcon />` component to contain the logic (and styling) for rendering the icon or image
 - Made a utility function in grafana-ui to convert a string to an `IconName`

| Before | After |
| -- | -- |
| before | after |

**Which issue(s) this PR fixes**:

Fixes #44446

**Special notes for your reviewer**:

~~At the moment the Profile gravatar image is no longer rounded, i need to figure out how to add that back in.~~ ~~going to leave profile image square for now and see how it feels~~ made just the profile icon round

### CODE REVIEW

File: packages/grafana-ui/src/types/icon.ts [hunk 1]
```diff
@@ -214,3 +224,18 @@ export function getFieldTypeIcon(field?: Field): IconName {
...
 }
+
+function isValidIconName(iconName: string): iconName is IconName {
+  const namedIcons: string[] = availableIcons;
+  const brandIcons: string[] = avaibleBrandIcons;
+
+  return namedIcons.includes(iconName) || brandIcons.includes(iconName);
+}
+
+export function toIconName(iconName: string): IconName | undefined {
```
Comment (ashharrison90) [inline packages/grafana-ui/src/types/icon.ts:235]: love this - so many `as IconName`s can be removed

**Review by ashharrison90 — APPROVED** [review]
great job! 🙌 

my pref would be to just slightly round every icon and not provide this as a configurable property in the `navModel`. but it's not really a hill i wanna die on, and this is **significantly** better than existing behaviour 🥳

File: packages/grafana-ui/src/types/icon.ts (hunk 1 above)
Comment (academo) [reply packages/grafana-ui/src/types/icon.ts:235]: @joshhunt this would be better if we can validate that the string is indeed an icon Name. Any random string as icon can be problematic as we don't know if those icons actually exists.

Comment (joshhunt) [reply packages/grafana-ui/src/types/icon.ts:235]: Is this not what this does?

Comment (academo) [reply packages/grafana-ui/src/types/icon.ts:235]: @joshhunt Yes please ignore my confusion I had my  mind set in something else.
