### PR TITLE
Restore dashboards: Improve bulk restore

### LINKED ISSUE #110809: Restore dashboards: Improve bulk operations
Currently there's no feedback if a dashboard is not found when restoring or if restoring some of the dashboards fails. Moreover, if restoring some of the dashboards fails, the whole restore operation is aborted.

### PR DESCRIPTION
**Pull request by Clarity-89**
**What is this feature?**

- Improve bulk restore by allowing partial failures
- Use the same cache when restoring dashboards to prevent restore failures
- Improve restore result notifications

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/110809

### CODE REVIEW

File: public/app/features/browse-dashboards/components/RecentlyDeletedActions.tsx [hunk 1]
```diff
@@ -21,17 +22,54 @@ export function RecentlyDeletedActions() {
...
+    let alertType = AppEvents.alertSuccess.name;
+    let message = t('browse-dashboards.restore.success', 'Dashboards restored successfully');
+
+    if (failedCount > 0) {
+      if (successCount > 0) {
+        // Partial success
+        alertType = AppEvents.alertWarning.name;
+        message = t(
+          'browse-dashboards.restore.partial-success',
+          '{{successCount}} of {{totalCount}} dashboards restored successfully. {{failedCount}} failed.',
```
Comment (tomratcliffe) [inline public/app/features/browse-dashboards/components/RecentlyDeletedActions.tsx]: Can we name one of the variables `count`, so that the translations know to generate the different plural versions? 🙏 

(TBH, I'm not sure how it works with all the different numbers and pluralised versions)

Comment (Clarity-89) [reply public/app/features/browse-dashboards/components/RecentlyDeletedActions.tsx]: > (TBH, I'm not sure how it works with all the different numbers and pluralised versions)

Apparently we need to use [nesting](https://www.i18next.com/translation-function/nesting#passing-options-to-nestings) or have a separate translated string for each count :(

**Review by ywzheng1 — APPROVED** [review]
Tested in ephemeral instance, looks good!  One small nit is that "Restore" button is still clickable after first click 
image
