### PR TITLE
PanelEditor: fixes save/apply for undefined props in restoreModel

### LINKED ISSUE #23916: PanelEditor: Changing some panel option to undefined does not save/apply changes
But I did discover one bug and that save and apply does not work from new panel edit if your change sets something to undefined. Like Delete Alert sets panel.alert to undefined. 

Problem is PanelModel.restoreModel is not correct, it does not clear all props on this before setting properties.
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/state/PanelModel.ts#L162

_Originally posted by @torkelo in https://github.com/grafana/grafana/issues/23910#issuecomment-619617896_

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
Not sure this is a good implementation.

**Which issue(s) this PR fixes**:
Closes #23916

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/dashboard/state/PanelModel.ts [hunk 1]
```diff
@@ -162,6 +162,44 @@ export class PanelModel implements DataConfigSource {
...
+          continue;
+        }
+
+        if (typeof (this as any)[property] === 'symbol') {
+          continue;
+        }
+
+        (this as any)[property] = undefined;
+      }
+    }
```
Comment (hugohaggmark) [inline public/app/features/dashboard/state/PanelModel.ts:201]: I'm not at all sure this is a good way to handle this case, please leave feedback!

File: public/app/features/dashboard/state/PanelModel.ts [hunk 2]
```diff
@@ -162,6 +162,44 @@ export class PanelModel implements DataConfigSource {
       (this as any)[property] = model[property];
     }
 
+    const notPersistedPropertiesKeys = Object.keys(notPersistedProperties);
+    const mustKeepPropsKeys = Object.keys(mustKeepProps);
+    const defaultsKeys = Object.keys(defaults);
+    const properties = Object.keys(this);
+    for (const property of properties) {
+      if (notPersistedPropertiesKeys.find(prop => property === prop)) {
```
Comment (torkelo) [inline public/app/features/dashboard/state/PanelModel.ts:170]: any reason for not using index lookup?  notPersistedProperties, mustKeepProps & defaults are objects for a reason to be able to do index-based lookup 

if (notPersistedProperties[property])

Comment (hugohaggmark) [reply public/app/features/dashboard/state/PanelModel.ts:170]: Of course, great catch 🙈

File: public/app/features/dashboard/state/PanelModel.ts [hunk 3]
```diff
@@ -162,6 +162,44 @@ export class PanelModel implements DataConfigSource {
...
+      if (defaultsKeys.find(prop => property === prop)) {
+        continue;
+      }
+
+      if (model[property]) {
+        continue;
+      }
+
+      if (!this.hasOwnProperty(property)) {
+        (this as any)[property] = undefined;
```
Comment (torkelo) [inline public/app/features/dashboard/state/PanelModel.ts:187]: think 
delete  (this as any)[property] 

is better but no sure :)

File: public/app/features/dashboard/components/PanelEditor/state/actions.ts [hunk 4]
```diff
@@ -58,6 +58,7 @@ export function panelEditorCleanUp(): ThunkResult<void> {
         if (lastResult) {
           sourcePanel.getQueryRunner().pipeDataToSubject(lastResult);
         }
+        sourcePanel.refresh();
```
Comment (torkelo) [inline public/app/features/dashboard/components/PanelEditor/state/actions.ts:61]: We should not tigger a refresh here, the code above will make sure the panel get's latest data again. 

This could be needed to clear alert state, but think that is an edge case.

Comment (hugohaggmark) [reply public/app/features/dashboard/components/PanelEditor/state/actions.ts:61]: Without the refresh the sourcePanel will look like it still has an alert rule with the hear icon for instance.

File: public/app/features/dashboard/state/PanelModel.ts (hunk 2 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/state/PanelModel.ts]: Done

File: public/app/features/dashboard/state/PanelModel.ts (hunk 3 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/state/PanelModel.ts]: Done!

**Comment by dprokop** [comment]
@hugohaggmark I've tested it and I am not sure it actually works. 

1. Create graph panel
2. Add an alerte 
3. Save, apply, go back and save -> whatever to save the changes
4. Refresh dashboard -> no changes are there

But I guess this is a different bug probably?

**Comment by hugohaggmark** [comment]
> @hugohaggmark I've tested it and I am not sure it actually works.
> 
> 1. Create graph panel
> 2. Add an alerte
> 3. Save, apply, go back and save -> whatever to save the changes
> 4. Refresh dashboard -> no changes are there
> 
> But I guess this is a different bug probably?

Hmm I can't repro this on my branch

**Comment by dprokop** [comment]
OH GOD DAMN IT! (sorry) `hub pr checkout` failed and I haven't noticed. Sorry!

**Comment by hugohaggmark** [comment]
> OH GOD DAMN IT! (sorry) `hub pr checkout` failed and I haven't noticed. Sorry!

no worries :)

File: public/app/features/dashboard/components/PanelEditor/state/actions.ts (hunk 4 above)
Comment (hugohaggmark) [reply public/app/features/dashboard/components/PanelEditor/state/actions.ts:61]: Any suggestions on how to force update the source panel @torkelo ?

Comment (torkelo) [reply public/app/features/dashboard/components/PanelEditor/state/actions.ts:61]: In graph render maybe we can check if we have alertState on the data but no alert rule defined, and if that is the case ignore ore remove alert state from data

Comment (torkelo) [reply public/app/features/dashboard/components/PanelEditor/state/actions.ts:61]: https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx#L98 

If we there can check if panel.alert is stiill defined

**Comment by torkelo** [comment]
Fixed a related issue: https://github.com/grafana/grafana/pull/23949 

where we lost editSourceId when switching panel type, that is used to merge panel in the edit with dashboard model when saving from within the edit model  (I know this state logic is very messy due to the mix of redux and mutable state, need to improve this in over time )

**Comment by torkelo** [comment]
have some changes coming

**Comment by torkelo** [comment]
Did some refactoring (moved the cleanup step first, then setting properties from model) and added a couple of unit tests for restoreModel. 

This solves a big issue that I have seen where if you start with a graph panel and switch to an react panel, then go back to dashboard and save the panel model saved is still a mix of angular graph panel options and new the react panel option. With this change we now clean-up all the panel specific angular panel options. Before in angular panel all the panel options lived directly on the root PanelModel level (hence all the mustKeep etc options as the plugin specific options angular panels live in the same namespace/tree). For react panels all plugin specific options live in PanelModel.options :) (I learn from my mistakes)

**Review by torkelo — APPROVED** [review]

File: public/app/features/dashboard/state/PanelModel.test.ts [hunk 5]
```diff
@@ -285,5 +285,51 @@ describe('PanelModel', () => {
...
+          title: 'New title',
+          options: {},
+        });
+
+        expect(model.id).toBe(10);
+        expect(model.gridPos.h).toBe(10);
+      });
+
+      it('Should remove old angular panel specfic props', () => {
+        model.axes = [{ prpo: 1 }];
```
Comment (dprokop) [inline public/app/features/dashboard/state/PanelModel.test.ts:322]:
```suggestion
        model.axes = [{ prop: 1 }];
```

**Review by dprokop — APPROVED** [review]
Nice and clean!
