### PR TITLE
Prometheus: Add metadata for summary metrics

### LINKED ISSUE #22337: Match HELP and TYPE for complex metrics
**What happened**:

No HELP and TYPE displayed for a sub metric of a complex metric. 

**What you expected to happen**:

HElP and TYPE are displayed for the given metric.

**How to reproduce it (as minimally and precisely as possible)**:

Create a summary, define a HELP. Only the base metric will have the information but the `sum` and `count` won't.

Base metric

Screenshot 2020-02-20 at 12 40 16

Sub metric

Screenshot 2020-02-20 at 12 40 20

**Anything else we need to know?**:
I believe this happens because we only match on the exact metric name:

https://github.com/grafana/grafana/blob/4f9b6c55c03462277a62be5084865723ba2e743c/public/app/plugins/datasource/prometheus/language_provider.ts#L45-L52

We would also need to match even if it includes the following suffices: 
- `_bucket`
- `_sum`
- `_count`
- `_total`

**Environment**:
- Grafana version: Lastest
- Data source type & version: Prometheus / Latest

### PR DESCRIPTION
**Pull request by davkal**
- summary metrics don't have metadata available from the metadata API,
so Grafana can help and just add it
- given a summary metric `foo`, we add metadata info for `foo_sum` and
`foo_count`
- with tests

Example using the prometheus instance at http://demo.robustperception.io:9090/

Screenshot 2020-05-03 at 22 16 30

Fixes #22337

CC @gotjosh

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/language_utils.ts [hunk 1]
```diff
@@ -111,3 +113,34 @@ export function expandRecordingRules(query: string, mapping: { [name: string]: s
   const rulesRegex = new RegExp(`(\\s|^)(${ruleNames.join('|')})(\\s|$|\\(|\\[|\\{)`, 'ig');
   return query.replace(rulesRegex, (match, pre, name, post) => `${pre}${mapping[name]}${post}`);
 }
+
+/**
+ * Adds metadata for synthetic summary metrics for which the API does not provide metadata.
```
Comment (gotjosh) [inline public/app/plugins/datasource/prometheus/language_utils.ts:118]:
```suggestion
 * Adds metadata for synthetic metrics for which the API does not provide metadata.
```

Comment (gotjosh) [reply public/app/plugins/datasource/prometheus/language_utils.ts:118]: Histograms also suffer from this problem

File: public/app/plugins/datasource/prometheus/language_utils.ts [hunk 2]
```diff
@@ -111,3 +113,34 @@ export function expandRecordingRules(query: string, mapping: { [name: string]: s
...
+ * @param metadata HELP and TYPE metadata from /api/v1/metadata
+ */
+export function fixSummariesMetadata(metadata: PromMetricsMetadata): PromMetricsMetadata {
+  if (!metadata) {
+    return metadata;
+  }
+  const summaryMetadata: PromMetricsMetadata = {};
+  for (const metric in metadata) {
+    const item = metadata[metric][0];
+    if (item.type === 'summary') {
```
Comment (gotjosh) [inline public/app/plugins/datasource/prometheus/language_utils.ts:130]: Do we want to add the other cases as part of this PR as well? I think we should be taking `_bucket`, `_sum`, `_count`, and `_total` into account as well.

In principle, I think I like modifying the metadata for these metrics with a clear explanation of what they actually are. However, it's one more level of indirection for people trying to look at what the base metrics does/is. 

To be clear, I'm not opposed to this I just think it's worth a discussion.

Comment (davkal) [reply public/app/plugins/datasource/prometheus/language_utils.ts:130]: Yes, lets do histograms as well. They seem so consist of `_bucket`, `_sum`, and `_count`. 

Can you explain what mechanism exists around `_total`?

Comment (davkal) [reply public/app/plugins/datasource/prometheus/language_utils.ts:130]: How do I find the metadata for the histogram base metric? I don't think `foo` is part of the metadata API result if a metric `foo_bucket` exists.

Comment (gotjosh) [reply public/app/plugins/datasource/prometheus/language_utils.ts:130]: > Can you explain what mechanism exists around _total?

My bad, we don't need to do anything for `_total` only the other three. 

> How do I find the metadata for the histogram base metric? I don't think foo is part of the metadata API result if a metric foo_bucket exists.

It's already there if I understand the question correctly. The metadata API won't expose the `_bucket` metric, the only thing that'll show up is the `foo` metric with the type of histogram.

File: public/app/plugins/datasource/prometheus/language_utils.ts [hunk 3]
```diff
@@ -111,3 +113,34 @@ export function expandRecordingRules(query: string, mapping: { [name: string]: s
...
+ * Adds metadata for synthetic metrics for which the API does not provide metadata.
+ * See https://github.com/grafana/grafana/issues/22337 for details.
+ *
+ * @param metadata HELP and TYPE metadata from /api/v1/metadata
+ */
+export function fixSummariesMetadata(metadata: PromMetricsMetadata): PromMetricsMetadata {
+  if (!metadata) {
+    return metadata;
+  }
+  const summaryMetadata: PromMetricsMetadata = {};
```
Comment (gotjosh) [inline public/app/plugins/datasource/prometheus/language_utils.ts:127]: nit: a very minor and optional nit is to move all the suffices and types to constants.

**Review by ivanahuckova — APPROVED** [review]
Looks good David! Not sure if we want to add metadata for histogram in this PR, but if not (and you will create a separate PR), then LGTM. However, if it is going to be part of this PR, @davkal, could you then re-request the review and. I'll look at that then. 🙂
