### PR TITLE
Table: Support date unit formats on string values 

### LINKED ISSUE #25884: Grafana 7.x cannot change the format date by setting the unit in
**What happened**:
image
image
I try to change the format like the captures, but it doesn't work.
**What you expected to happen**:
work as the described in the release note.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.4
- Data source type & version: Postgresql 10
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chrome
- Grafana plugins: table
- Others:

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #25884 

So many ways to address this. 

I think the display processor should be smarter here and identify that a date unit has been selected and try to parse strings to dates.

### CODE REVIEW

**Review by dprokop — APPROVED** [review]
looks good

File: packages/grafana-data/src/field/displayProcessor.ts [hunk 1]
```diff
@@ -30,25 +30,27 @@ export function getDisplayProcessor(options?: DisplayProcessorOptions): DisplayP
...
+  let unit = config.unit;
+  let hasDateUnit = unit && (timeFormats[unit] || unit.startsWith('time:'));
 
-  if (field.type === FieldType.time) {
-    if (config.unit && timeFormats[config.unit]) {
-      // Currently selected unit is valid for time fields
-    } else if (config.unit && config.unit.startsWith('time:')) {
-      // Also OK
-    } else {
-      config.unit = `time:${DEFAULT_DATE_TIME_FORMAT}`;
```
Comment (torkelo) [inline packages/grafana-data/src/field/displayProcessor.ts:42]: this is the modify the config object bug

**Review by ryantxu — APPROVED** [review]
LGTM -- good that we do not mutate anymore
