### PR TITLE
Plugins: display plugin id and url when it fails to install

### LINKED ISSUE #67335: Identify which plugin is failing to install before exiting
## What happened:

When installing a plugin that has a mismatched SHA256 or one that doesn't exist, Grafana will exit with an error but not tell you which plugin failed.

## What you expected to happen:

Error should display which plugin failed to install before exiting.  In K8 this leads to a loop.

## How to reproduce it (as minimally and precisely as possible):

Install Grafana 8.4.0 (and newer if version specified), and the `grafana-azuredevops-datasource` version 0.2.0

The plugin will fail to install, but Grafana doesn't tell you which plugin.  When there is a large list of plugins, this becomes difficult to diagnose.

```bash
grafana-1  | Error: ✗ failed to download plugin archive: expected SHA256 checksum does not match the downloaded archive - please contact security@grafana.com
grafana-1 exited with code 1
```

## Environment:
- Grafana version:

8.4+

- Data source type & version:

`grafana-azuredevops-datasource` version `0.2.0`

- OS Grafana is installed on:

docker image on macos

- User OS & Browser:

macos and chrome

- Grafana plugins:

`grafana-azuredevops-datasource`

- Others:

### PR DESCRIPTION
**Pull request by briangann**
**What is this feature?**

When a plugin fails to install, the error message will include the plugin-id and when possible the URL to the zip file used.

**Why do we need this feature?**

This makes it easier to identify the plugin that is failing and remove it from a long list, or escalate to the team responsible.

**Who is this feature for?**

Administrators of Grafana

**Which issue(s) does this PR fix?**:

Fixes #67335

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/plugins/repo/client.go [hunk 1]
```diff
@@ -53,7 +53,7 @@ func (c *Client) download(_ context.Context, pluginZipURL, checksum string, comp
 		if err := tmpFile.Close(); err != nil {
 			c.log.Warn("Failed to close file", "err", err)
 		}
-		return nil, fmt.Errorf("%v: %w", "failed to download plugin archive", err)
+		return nil, fmt.Errorf("%v: failed to download plugin archive (%s)", err, pluginZipURL)
```
Comment (xnyo) [inline pkg/plugins/repo/client.go:56]: Nit: I think this should be:

```suggestion
		return nil, fmt.Errorf("%w: failed to download plugin archive (%s)", err, pluginZipURL)
```

to make sure the original error is wrapped in the new one, like with the previous code

**Review by xnyo — COMMENTED** [review]
Awesome! :rocket: :rocket: 
Just one small comment:

**Review by marefr — APPROVED** [review]
LGTM with earlier suggestions. 

Definitely confusing having two API clients. Are both of these clients still in use @wbrowne? Related to removal of unused code in the cli perhaps? We should make sure to clean this up if possible.

File: pkg/cmd/grafana-cli/services/api_client.go [hunk 2]
```diff
@@ -108,7 +108,7 @@ func (client *GrafanaComClient) DownloadFile(pluginName string, tmpFile *os.File
 		return fmt.Errorf("failed to write to %q: %w", tmpFile.Name(), err)
 	}
 	if len(checksum) > 0 && checksum != fmt.Sprintf("%x", h.Sum(nil)) {
-		return fmt.Errorf("expected SHA256 checksum does not match the downloaded archive - please contact security@grafana.com")
+		return fmt.Errorf("expected SHA256 checksum does not match the downloaded archive (%s: %s) - please contact security@grafana.com", pluginName, url)
```
Comment (wbrowne) [inline pkg/cmd/grafana-cli/services/api_client.go:111]: Yeah as @marefr highlighted, this isn't used. No harm in changing it but it serves as a reminder to us to finally clean all this up!

**Review by wbrowne — COMMENTED** [review]
If you are able to reproduce easily, it would be interesting to know if `--debug` happens to already give you some information that you need. This is probably overkill to change by default as you'll get a bunch of output for every install, successful or not

**Comment by briangann** [comment]
> If you are able to reproduce easily, it would be interesting to know if `--debug` happens to already give you some information that you need. This is probably overkill to change by default as you'll get a bunch of output for every install, successful or not

With `GF_LOG_LEVEL` set to debug there isn't any additional output during startup of the container. Is there another env setting that should be used?

Running the command `grafana cli --debug plugins install grafana-azuredevops-datasource 0.2.0`  does show which plugin is failing, 

```
Fetching metadata for plugin "grafana-azuredevops-datasource" from repo https://grafana.com/api/plugins

Installing plugin from https://grafana.com/api/plugins/grafana-azuredevops-datasource/versions/0.2.0/download
```

File: pkg/cmd/grafana-cli/services/api_client.go (hunk 2 above)
Comment (briangann) [reply pkg/cmd/grafana-cli/services/api_client.go]: have reverted this since it's been cleaned up already!
