### PR TITLE
Dashboards: Remove Explore option from panel menu when panel's datasource uid is "-- Dashboard --"

### LINKED ISSUE #61620: Clicking 'explore' on a panel with '-- Dashboard --' datasource is broken
**What happened**:
I went to explore a panel, to find out what query is powering it & modify it slightly to my needs. As it was a provisioned dashboard which is not editable I could not use the 'edit' view to see the query, so I opted for 'explore'

I didn't know this panel was targeting another panel, and got the error (see attached gif). 

**What you expected to happen**:
To see the query generating the data. In this case it would be the query that is powering the _other dashboard panel_ that is the target of this panel.

**How to reproduce it (as minimally and precisely as possible)**:
The issue is visible in the automatically provisioned "Usage Insights - 3 - Query Errors" dashboard in Grafana cloud
Peek 2023-01-17 14-26

**Anything else we need to know?**:
I've run into this both with loki and prometheus based 'source panels', though I'm not sure if that is relevant.

As a workaround I tried to inspect the json, it only mentions a the following for a target:
```
  "targets": [
    {
      "panelId": 2,
      "refId": "A"
    }
```
This did not help me to find the panel that I could explore.

**Environment**:
- Grafana version: v9.3.2-67a213dc85 (67a213dc85)
- Data source type & version: "dashboard"
- User OS & Browser: Firefox

### PR DESCRIPTION
**Pull request by harisrozajac**
**What is this feature?**

Since Explore doesn't support the dashboard datasource, I've disabled the Explore option in panel menu. 

In future, we should support all the source queries used by the dashboard data source and generate a link to Explore using them instead. I've created a follow-up ticket that will address that: https://github.com/grafana/grafana/issues/69167

**Example**

Panel with `-- Dashboard --` uid:
Screenshot 2023-05-24 at 1 44 15 PM

All other panels:
Screenshot 2023-05-24 at 1 45 23 PM

Fixes https://github.com/grafana/grafana/issues/61620

**Please check that:**
- [ ] It works as expected from a user's perspective.

### CODE REVIEW

File: public/app/features/dashboard/utils/getPanelMenu.ts [hunk 1]
```diff
@@ -141,7 +141,11 @@ export function getPanelMenu(
     shortcut: 'p s',
   });
 
-  if (contextSrv.hasAccessToExplore() && !(panel.plugin && panel.plugin.meta.skipDataQuery)) {
+  if (
+    contextSrv.hasAccessToExplore() &&
+    !(panel.plugin && panel.plugin.meta.skipDataQuery) &&
+    panel.datasource?.uid !== '-- Dashboard --'
```
Comment (ryantxu) [inline public/app/features/dashboard/utils/getPanelMenu.ts:147]: can you use the constant `SHARED_DASHBOARD_QUERY`?

Comment (harisrozajac) [reply public/app/features/dashboard/utils/getPanelMenu.ts]: Sure, I've made the update. Thanks for the feedback

**Comment by Elfo404** [comment]
i think you want to set add the `backport v10.0.x` and remove the `backport` label.
`backport v10.0.x` will tell grot to backport the PR to `v10.0.x` once merged, while `backport` should only be used for backport PRs (not PRs to be backported).

Other than this looks good! 👍 we may want to create a followup issue to - instead of removing the link to explore - build a link with all the queries referenced in the panel

**Review by Elfo404 — APPROVED** [review]
