### PR TITLE
Fix dashboard snapshot deletion

### LINKED ISSUE #11994: Snapshot deletion
In #4412 & #10996 there was a change made to the way that the snapshot delete system works to only allow users to delete snapshots for dashboards they have edit access to.  The problem with that change is that it breaks the ability to delete snapshots via the "Did you make a mistake? delete snapshot. " link if the user doesn't have edit access (including when using a remote snapshot server).

I propose resolving this problem by adding support for `DELETE /api/snapshots/:key` where `:key` is the public key and the user permissions are checked, this would be used by the UI and respect the permissions.

The `GET /api/snapshots-delete/:key` route would be clarified as `GET /api/snapshots-delete/:deleteKey` and only be used for unauthenticated request as it was previously.  The `deleteKey` would only be exposed in the snapshot creation response, so that only the user who created the snapshot would have that key, and anyone else would need to use the new endpoint and be subject to the standard authorization checks.

### PR DESCRIPTION
**Pull request by DanCech**
This PR fixes #11994 by restoring the original behavior of the `GET /api/snapshots-delete/:deleteKey` endpoint and adding a new `DELETE /api/snapshots/:key` endpoint to be used by authenticated users.

It also updates the snapshot documentation to include the `GET /api/dashboard/snapshots` functionality for listing snapshots.

### CODE REVIEW

File: pkg/api/dashboard_snapshot_test.go [hunk 1]
```diff
@@ -47,13 +47,26 @@ func TestDashboardSnapshotApiEndpoint(t *testing.T) {
...
 					sc.handlerFunc = DeleteDashboardSnapshot
-					sc.fakeReqWithParams("GET", sc.url, map[string]string{"key": "12345"}).exec()
+					sc.fakeReqWithParams("DELETE", sc.url, map[string]string{"key": "12345"}).exec()
 
 					So(sc.resp.Code, ShouldEqual, 403)
 				})
 			})
+
+			Convey("Should be able to delete snapshot by deleteKey", func() {
+				loggedInUserScenarioWithRole("When calling GET on", "GET", "/api/snapshots-delete/12345", "/api/snapshots-delete/:deleteKey", m.ROLE_EDITOR, func(sc *scenarioContext) {
```
Comment (bergquist) [inline pkg/api/dashboard_snapshot_test.go]: since this does not require editor I think we should change the test to use `m.ROLE_VIEWER`

Comment (DanCech) [reply pkg/api/dashboard_snapshot_test.go]: The new DELETE endpoint requires exactly the same permissions as the GET endpoint does in 5.1.3, is there something I'm missing here?

File: pkg/api/api.go [hunk 2]
```diff
@@ -107,7 +107,8 @@ func (hs *HTTPServer) registerRoutes() {
 	r.Post("/api/snapshots/", bind(m.CreateDashboardSnapshotCommand{}), CreateDashboardSnapshot)
 	r.Get("/api/snapshot/shared-options/", GetSharingOptions)
 	r.Get("/api/snapshots/:key", GetDashboardSnapshot)
-	r.Get("/api/snapshots-delete/:key", reqEditorRole, wrap(DeleteDashboardSnapshot))
+	r.Get("/api/snapshots-delete/:deleteKey", DeleteDashboardSnapshotByDeleteKey)
```
[the remark this answers is not in the document]
Comment (DanCech) [reply pkg/api/api.go]: done

File: pkg/api/dashboard_snapshot_test.go (hunk 1 above)
Comment (bergquist) [reply pkg/api/dashboard_snapshot_test.go]: Then we need to add `reqEditorRole` as a middleware to that route. https://github.com/grafana/grafana/pull/12025/files#diff-13d216b12482e706601d65bcc87deb38R110

as in 5.1.3 https://github.com/grafana/grafana/blob/v5.1.x/pkg/api/api.go#L110

Comment (DanCech) [reply pkg/api/dashboard_snapshot_test.go]: updated it to use a scenario with no user or role info

**Comment by bergquist** [comment]
:+1:

**Comment by DanCech** [comment]
I'd really like to at least get it onto the public snapshot server so folks can delete their snapshot if they click accidentally, we can make a custom build for that if necessary but it would be easier to be able to just upgrade it to 5.1.4

**Comment by bergquist** [comment]
Perhaps we could deploy a master build on the snapshoot server?

**Comment by RichiH** [comment]
Having a working master on play.g.o would be nice, but please also keep the current release around.

I just tested a FR on play.g.o as our own versions are still at 5.0.3 and having a known-good-and-current state to test against was quite useful.

**Comment by DanCech** [comment]
We could definitely run a master build on the snapshot server for now.

**Comment by bergquist** [comment]
Agree.

Merging this to master so we can run master no the snapshoot server but I'll tag this 5.1.4 in case we make a 5.1.4 release.
