### PR TITLE
Prometheus: Fix incremental querying logic for public dashboards

### LINKED ISSUE #109871: Prometheus: public dashboards fail when incremental querying is enabled
when the data source setting `incremental querying (beta)` is enabled, public dashboards no longer work.

**steps to reproduce:**
- enable `incremental querying (beta)` on a data source
- create a public dashboard that queries from this data source
- attempt to load the public dashboard, queries are no longer successful.

```
PanelQueryRunner Error TypeError: Cannot read properties of undefined (reading 'includes')

this.hasIncrementalQuery && !request.targets.some((target) => target.instant || target.expr.includes('$__range'));
```

### PR DESCRIPTION
**Pull request by jcolladokuri**
**What is this feature?**

Fixes query failure for prometheus when public dashboards + incremental querying is enabled.

Also disables incremental querying if public dashboards are being used altogether.

**Why do we need this feature?**

Because of the way public dashboards are handled, using incremental querying on the datasource, was causing queries to fail. This ensures that incremental querying is always disabled if public dashboards are being used.

**Who is this feature for?**

Prometheus users.

**Which issue(s) does this PR fix?**:

Fixes #109871 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-prometheus/src/datasource.ts [hunk 1]
```diff
@@ -471,7 +471,9 @@ export class PrometheusDatasource
 
     // Use incremental query only if enabled and no instant queries or no $__range variables
     const shouldUseIncrementalQuery =
-      this.hasIncrementalQuery && !request.targets.some((target) => target.instant || target.expr.includes('$__range'));
+      this.hasIncrementalQuery &&
+      !request.targets.some((target) => target.instant || target.expr?.includes('$__range')) &&
+      !config.publicDashboardAccessToken;
```
Comment (itsmylife) [inline packages/grafana-prometheus/src/datasource.ts]: I'd move this one line up to fail the check quickly. If there is a token it's going to fail anyways. No need to wait for `some` loop.

Comment (jcolladokuri) [reply packages/grafana-prometheus/src/datasource.ts]: moved the check earlier :)

**Review by itsmylife — APPROVED** [review]

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/18106767738)
- Version: 12.3.0-18106767738
