### PR TITLE
Transformations: Fix true inner join in `joinByField` transformation

### LINKED ISSUE #87361: Transformations: Outer Join (tabular) is not joining consistent with SQL-style Outer Join
### What happened?

As title suggests, Outer Join (tabular) - `Join by field` Transformation - is not joining consistent with SQL-style Outer Join.

[Escalation.](https://github.com/grafana/support-escalations/issues/10351)

[PR that introduced the behavior](https://github.com/grafana/grafana/pull/72176).

Consider the following tables...
Table 1:
```
[
{
"Name": "Mithil",
"Value": "iPhone"
},
{
"Name": "Mithil",
"Value": "Android"
}
]
```

Table2:
```
[
{
"Name": "Mithil",
"Val": "Phone1"
},
{
"Name": "Mithil",
"Val": "Phone2"
},
{
"Name": "Mithil",
"Val": "Phone3"
},
{
"Name": "Mithil",
"Val": "Phone4"
},
{
"Name": "Mithil",
"Val": "Phone5"
}
]
```

With a "traditional" SQL-style Full Outer Join which joins on the `Name` field, which this functionality is attempting to mimic. We should see the following output:
```
Name  Value    Val
Mithil  Iphone  Phone1
Mithil  Android Phone1
Mithil  Iphone  Phone2
Mithil  Android Phone2
Mithil  Iphone  Phone3
Mithil  Android Phone3
Mithil  Iphone  Phone4
Mithil  Android Phone4
Mithil  Iphone  Phone5
Mithil  Android Phone5
```

However, this is the output instead:
```
Name   Value   Val
Mithil  Iphone  Phone1
Mithil  Android Phone1
Mithil  Iphone  Phone2
Mithil  Iphone  Phone3
Mithil  Iphone  Phone4
Mithil  Iphone  Phone5
```

Import this Dash to verify:
[debug-Transformation.join.by.fields-2024-05-02.02_11_05.json.txt](https://github.com/grafana/grafana/files/15205623/debug-Transformation.join.by.fields-2024-05-02.02_11_05.json.txt)

### What did you expect to happen?

For the Transform to behave like a SQL-style Full Outer Join.

### Did this work before?

This fiunctionality didn't exist before.

### How do we reproduce it?

1. Download debug dash
2. See issue
3. ...
4. Profit

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

ENVIRONMENT DETAILS
On-Prem or HG: On-Prem
(On-prem) Platform (Linux, Windows, K8s, AMG, etc):
(Cloud) Instance Slug: N/A
(HG) Permission to access instance (Y/N): N/A
(HG) Link to affected page: N/A

Grafana Version: 10.4
License: Grafana Enterprise

Product: Grafana
Component: Panel (Transformation)

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by baldm0mma**
**What is this feature?**

This fixes the joinByField's "inner" join option to perform like an actual SQL-like inner join.

Example:

**Students**

| StudentID | Name     | Major            |
| --------- | -------- | ---------------- |
| 1         | John     | Computer Science |
| 2         | Emily    | Mathematics      |
| 3         | Michael  | Physics          |
| 4         | Jennifer | Chemistry        |

**Enrollments**

| StudentID | CourseID | Grade |
| --------- | -------- | ----- |
| 1         | CS101    | A     |
| 1         | CS102    | B     |
| 2         | MATH201  | A     |
| 3         | PHYS101  | B     |
| 5         | HIST101  | B     |

The result after applying the inner join transformation looks like the following:

| StudentID | Name    | Major            | CourseID | Grade |
| --------- | ------- | ---------------- | -------- | ----- |
| 1         | John    | Computer Science | CS101    | A     |
| 1         | John    | Computer Science | CS102    | B     |
| 2         | Emily   | Mathematics      | MATH201  | A     |
| 3         | Michael | Physics          | PHYS101  | B     |

The inner join only includes rows where there is a match between the "StudentID" in both tables. In this case, the result does not include "Jennifer" from the "Students" table because there are no matching enrollments for her in the "Enrollments" table.

**Why do we need this feature?**

It is used by users, but has not been working as expected. Also, an [escalation](https://github.com/grafana/grafana/issues/87361) was created for it.

**Who is this feature for?**

All users.

**Which issue(s) does this PR fix?**:

Fixes #87361 

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: packages/grafana-data/src/transformations/transformers/joinDataFrames.ts [hunk 1]
```diff
@@ -362,6 +362,77 @@ function joinOuterTabular(
...
+ *
+ * @param {AlignedData[]} tables - The tables to join.
+ *
+ * @returns {Array<Array<string | number | null | undefined>>} The joined tables as an array of arrays, where each array represents a row in the joined table.
+ */
+function joinInner(tables: AlignedData[]): Array<Array<string | number | null | undefined>> {
+  const joinedTables: Array<Array<string | number | null | undefined>> = [];
+
+  // Helper function to get the value at a specific index from an array or typed array
+  const getValue = (arr: number[] | TypedArray | Array<number | null | undefined>, index: number) => arr[index];
```
Comment (leeoniya) [inline packages/grafana-data/src/transformations/transformers/joinDataFrames.ts:386]: dont need this

Comment (baldm0mma) [reply packages/grafana-data/src/transformations/transformers/joinDataFrames.ts:386]: Don't need what?

Comment (baldm0mma) [reply packages/grafana-data/src/transformations/transformers/joinDataFrames.ts:386]: You mean I could remove it now that I'm not accessing via the `at` method? Yeah, that's probably a good idea.

Comment (baldm0mma) [reply packages/grafana-data/src/transformations/transformers/joinDataFrames.ts]: Removed.

File: packages/grafana-data/src/transformations/transformers/joinByField.test.ts [hunk 2]
```diff
@@ -761,93 +761,6 @@ describe('JOIN Transformer', () => {
       });
     });
 
-    it('inner joins by time field in reverse order', async () => {
```
Comment (baldm0mma) [inline packages/grafana-data/src/transformations/transformers/joinByField.test.ts:764]: Not relevant with the new behavior. `seriesToColumns` has been deprecated.

File: packages/grafana-data/src/transformations/transformers/joinDataFrames.test.ts [hunk 3]
```diff
@@ -204,11 +208,72 @@ describe('align frames', () => {
...
+              201,
+              201,
               95,
+            ],
+          },
+        ]
+      `);
+    });
+
+    it('should perform an inner join with duplicated values to join on', () => {
```
Comment (nmarrs) [inline packages/grafana-data/src/transformations/transformers/joinDataFrames.test.ts:223]:
```suggestion
    it('should perform an inner join with duplicated values to join on - as expected for tabular data', () => {
```

File: packages/grafana-data/src/transformations/transformers/joinDataFrames.test.ts [hunk 4]
```diff
@@ -150,8 +154,8 @@ describe('align frames', () => {
     });
     const tableData2 = toDataFrame({
       fields: [
-        { name: 'gender', type: FieldType.string, values: ['MALE', 'FEMALE'] },
-        { name: 'count', type: FieldType.number, values: [103, 95] },
+        { name: 'gender', type: FieldType.string, values: ['MALE', 'NON-BINARY', 'FEMALE'] },
+        { name: 'count', type: FieldType.number, values: [103, 95, 201] },
       ],
     });
```
Comment (nmarrs) [inline packages/grafana-data/src/transformations/transformers/joinDataFrames.test.ts:161]: maybe update outer join test description to specify tabular data as well

File: packages/grafana-data/src/transformations/transformers/joinDataFrames.ts [hunk 5]
```diff
@@ -362,6 +362,74 @@ function joinOuterTabular(
...
+ * Then, when processing the tables, the function iterates over the values in the `xValues`
+ * (the joining keys) array and checks if the current row `currentRow` already includes the value.
+ * If a matching value is found, it joins the corresponding values from the remaining arrays `yValues`
+ * (all other non-joining key arrays) to create a new row in the joined table.
+ *
+ * @param {AlignedData[]} tables - The tables to join.
+ *
+ * @returns {Array<Array<string | number | null | undefined>>} The joined tables as an array of arrays, where each array represents a row in the joined table.
+ */
+function joinInner(tables: AlignedData[]): Array<Array<string | number | null | undefined>> {
```
Comment (nmarrs) [inline packages/grafana-data/src/transformations/transformers/joinDataFrames.ts:382]:
```suggestion
function joinInnerTabular(tables: AlignedData[]): Array<Array<string | number | null | undefined>> {
```
Should we keep naming convention the same as the outer join for tabular data? 🤔

File: packages/grafana-data/src/transformations/transformers/joinDataFrames.ts [hunk 6]
```diff
@@ -362,6 +362,74 @@ function joinOuterTabular(
...
+  const joinedTables: Array<Array<string | number | null | undefined>> = [];
+
+  // Recursive function to perform the inner join.
+  const joinTables = (
+    currentTables: AlignedData[],
+    currentIndex: number,
+    currentRow: Array<string | number | null | undefined>
+  ) => {
+    if (currentIndex === currentTables.length) {
+      // Base case: all tables have been joined, add the current row to the final result.
```
Comment (nmarrs) [inline packages/grafana-data/src/transformations/transformers/joinDataFrames.ts:392]: data-structures and algorithms!! next challenge will be centering a div

File: docs/sources/panels-visualizations/query-transform-data/transform-data/index.md [hunk 7]
```diff
@@ -761,13 +761,13 @@ Use this transformation to merge multiple results into a single table, enabling
 
 This is especially useful for converting multiple time series results into a single wide table with a shared time field.
 
-#### Inner join
+#### Inner join (for Time Series or SQL-like data)
```
Comment (nmarrs) [inline docs/sources/panels-visualizations/query-transform-data/transform-data/index.md:764]: i'm wondering why we have two outer join options and only one inner join 🤔 maybe the outer join should also be consolidated to reduce option overload / need for user to care about the shape of their data?
Screenshot 2024-05-08 at 4 35 25 PM

**Review by nmarrs — APPROVED** [review]
Looks great overall!

Test dashboard
[Tabular Inner and Outer Join Test-1715211190626.json](https://github.com/grafana/grafana/files/15255928/Tabular.Inner.and.Outer.Join.Test-1715211190626.json)

File: packages/grafana-data/src/transformations/transformers/joinDataFrames.ts (hunk 5 above)
Comment (nmarrs) [reply packages/grafana-data/src/transformations/transformers/joinDataFrames.ts:382]: update: it seems that for inner we can do both series + tabular data while for some reason outer is differentiated and split out 🤔

File: docs/sources/panels-visualizations/query-transform-data/transform-data/index.md (hunk 7 above)
Comment (leeoniya) [reply docs/sources/panels-visualizations/query-transform-data/transform-data/index.md:764]: the timeseries outer join algorithm sorts the values, and does not handle duplicate timestamps in the same series. this makes it really fast but not a true sql outer join. i dont think we can make a sql outer join work as fast, but would love to be wrong here.

File: packages/grafana-data/src/transformations/transformers/joinDataFrames.ts (hunk 5 above)
Comment (baldm0mma) [reply packages/grafana-data/src/transformations/transformers/joinDataFrames.ts:382]: Correct. I was originally going to add an `INNER (TABULAR)` option, but the previous `INNER` wasn't actually behaving like an `INNER` anyway, so instead of adding yet another option, @leeoniya suggested we just correct the original `INNER`'s behavior, which I think was the right move. The reason we split the 2 `OUTER` joins - I believe - is because they behave significantly differently then the other, depending on the data (time series or SQL-like). The `INNER`, however, due to the nature of an `INNER` join itself, will behave very similarly for both data types - sans a few edge cases.

File: packages/grafana-data/src/transformations/transformers/joinDataFrames.ts (hunk 6 above)
Comment (baldm0mma) [reply packages/grafana-data/src/transformations/transformers/joinDataFrames.ts:392]: Using only floats!!!

File: packages/grafana-data/src/transformations/transformers/joinDataFrames.ts [hunk 8]
```diff
@@ -362,6 +362,74 @@ function joinOuterTabular(
   return data;
 }
 
+/**
+ * This function performs a sql-style inner join on tabular data;
```
Comment (codeincarnate) [inline packages/grafana-data/src/transformations/transformers/joinDataFrames.ts:366]: Love the comments ❤️

**Review by codeincarnate — APPROVED** [review]
Gave it a spin and looks good! 🚀
