### PR TITLE
TimeSeries: Fix plugins memory leak

### LINKED ISSUE #117401: Azure Monitor: Memory leak and browser crashing
### What happened?

Chrome Browser crashed after extended period of auto refreshing a dashboard with panels that used the Azure Monitor Data Source. 

We used Chrome's Performance recorder to see if there were any memory leaks:

Image

As can be seen, the heap memory and event listeners continue to grow in time. We believe the issue is due to the **Format as: Table** configuration of the query. When using **Format as: Logs** we no longer see the rise in heap memory and event listeners:

Image

### What did you expect to happen?

Continued auto refresh without issues

### Did this work before?

We're currently using Grafana v11.6.9 and it currently only works whenever auto refresh is off. If auto refresh is on, eventually the browser will crash

### How do we reproduce it?

1. Create a Time series panel
2. Select Azure Monitor as the Data Source
3. Configure it to use Service: Logs > Select a Resource and fill in a query
4. Ensure you set Format as: Table
5. Leave auto-refresh option to the lowest setting (we used 5s auto refresh)

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: v11.6.9
OS: Windows 11
Browser: Chrome

### Grafana platform?

Other

### Datasource(s)?

Azure Monitor

### PR DESCRIPTION
**Pull request by gtk-grafana**
**What is this fix?**
Fix for long standing memory leak in TooltipPlugin2 and AnnotationsPlugin.
Storing a uPlot reference in react state across uPlot re-inits was preventing garbage collection from cleaning up old uPlot references. This resulted in uPlotConfigBuilder, uPlotSeriesBuilder, and detached uPlot DOM nodes from getting collected which caused the leak. 

**Why do we need this feature?**
Reduce memory consumption, increase performance on dashboards with many panels and/or many series.

**Who is this feature for?**
Timeseries panel users

Could potentially fix https://github.com/grafana/grafana/issues/117401

**Special notes for your reviewer:**
To test: to create a panel with many series (1000+) and trigger uplot to re-init by changing the panel options (toggling series visibility in the legend is the fastest way to repro).

How the browser collects garbage is variable but you should typically see a gradual increase eventually plateauing. Resizing the panel tends to force garbage collection, so keep that in mind when profiling.

The annotation changes are behind the `annotationsClustering` feature flag to prevent accidental regression due to the slightly larger impact radius of the annotation changes. Since the leak in annotations has been present since ~2024 this shouldn't be high enough impact to warrant pushing a potential regression.

Many many thanks to @leeoniya for helping track this down & fix

Firefox running on 5s refresh for ~25m:
image

Chrome running on 5s refresh for ~25m:
image

Safari: 
No heapshot tool but was able to run 1000 series at 5 second auto refresh all night without crashing.

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin2.tsx [hunk 1]
```diff
@@ -707,6 +706,7 @@ export const TooltipPlugin2 = ({
 
   useLayoutEffect(() => {
     const size = sizeRef.current!;
+    const _plot = plotRef.current!;
```
Comment (gtk-grafana) [inline packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin2.tsx]: I would rather avoid silencing the compiler and adding a few more optional accessors in to prevent these assumptions from introducing a runtime error in the future if this code is changed

```
#709 const _plot = plotRef.current;
#721 let event = _plot?.cursor.event;
#746 !isStaleEvent && _plot?.over.dispatchEvent(event);
#748 _plot?.setCursor(
```

**Review by leeoniya — APPROVED** [review]
nice work. this was a doozy!

**Review by fastfrwrd — APPROVED** [review]
