### PR TITLE
Table: Improve a11y

### LINKED ISSUE #117843: A11y: Screen reader announces extra "separator" content when navigating table cells
## Description

When navigating table cells using arrow keys, the screen reader announces extra content such as "dash dash dash separator" after each column value. This extraneous announcement clutters the reading experience and makes it harder for screen reader users to focus on the actual data.

## Steps to reproduce

1. Open Grafana in Chrome on Windows
2. Enable JAWS screen reader
3. Navigate to the Example Dashboard page containing a data table
4. Use arrow keys to navigate through the table cells
5. Listen to the screen reader announcements for each cell

## Actual behavior

The screen reader announces extra content, such as "dash dash dash separator," after each column value.

## Expected behavior

The screen reader should only announce the column value without any extra or irrelevant content.

## Suggested fix

Inspect the table's HTML structure to identify the source of the extra content (e.g., hidden separator elements or column resize handles). If these elements are purely decorative or structural, hide them from assistive technologies using `aria-hidden="true"`:

```html
<div role="separator" aria-hidden="true" class="resizeHandle" ...></div>
```

## WCAG criteria

- **1.3.1 Info and Relationships** (Level A)

## Possible duplicates in grafana/grafana

- [#84096](https://github.com/grafana/grafana/issues/84096) — Tables can't be read properly by JAWS (open; related — JAWS cannot navigate table cells properly, reads entire rows as single lines)

## Issue reference

Reference issue 24

### PR DESCRIPTION
**Pull request by fastfrwrd**
Fixes #117843, #117828, #84096

I've verified using Lighthouse, and in an upcoming PR I'll add a11y checks via Playwright to keep this working.

- added `treegrid` role when nesting is present, and added some other related `aria` props to help in the nested table scenario.
- adds `aria-hidden` to a number of non-interactive or non-relevant-to-screenreader elements in our react-data-grid fork.
  - need to open a PR to upstream that.
- removed an unnecessary tabIndex={-1}
- improve aria tags on tooltip trigger for Tooltip from Field
- improves aria tags on row collapsing element for nested tables

### CODE REVIEW

**Comment by fastfrwrd** [comment]
Screenshot 2026-02-13 at 6 50 41 PM
Screenshot 2026-02-13 at 6 50 30 PM

File: packages/grafana-ui/src/components/Table/TableNG/TableNG.tsx [hunk 1]
```diff
@@ -943,14 +975,18 @@ const renderRowFactory =
     const rowIdx = row.__index;
     const isExpanded = expandedRows.has(rowIdx);
 
+    const a11yProps: HTMLAttributes<HTMLDivElement> = {};
```
Comment (ywzheng1) [inline packages/grafana-ui/src/components/Table/TableNG/TableNG.tsx]: curious why its not `React.AriaAttributes` or `React.AriaAttributes & React.HTMLAttributes<HTMLDivElement>`?

File: packages/grafana-ui/src/components/Table/TableNG/TableNG.tsx [hunk 2]
```diff
@@ -943,14 +975,18 @@ const renderRowFactory =
...
+
     // Don't render non expanded child rows
     if (row.__depth === 1 && !isExpanded) {
       return null;
     }
 
     // Add aria-expanded to parent rows that have nested data
     if (row.data) {
-      return <Row key={key} {...props} aria-expanded={isExpanded} />;
+      a11yProps['aria-level'] = 1;
```
Comment (ywzheng1) [inline packages/grafana-ui/src/components/Table/TableNG/TableNG.tsx]: should we use the depth we already have and for nested we add 1? ex: `row.__depth + 1`

**Review by gtk-grafana — APPROVED** [review]
LGTM and works well locally, although we might want to also add an active aria state for the column filter buttons

File: packages/grafana-ui/src/components/Table/TableNG/TableNG.tsx (hunk 2 above)
Comment (fastfrwrd) [reply packages/grafana-ui/src/components/Table/TableNG/TableNG.tsx]: thanks for these comments, I'm able to clean this whole thing up a little bit after some of the changes I was planning didn't pan out the way I expected.

**Comment by fastfrwrd** [comment]
I've confirmed these changes resolve the a11y issues via Axe - there will be automated enforcement once we have the Playwright-based test utilities in place (#118140)

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/22117372342)
- Version: 12.4.0-22117372342
