### PR TITLE
Plugins: Fix outline for elements inside a plugin page

### LINKED ISSUE #70820: Plugin Details Page: overflow: auto causes fields' outline to be cut off
in https://github.com/grafana/grafana/pull/58741 an `overflow: auto` rule is added to the plugin details page, which causes outlines on fields to be cut out when focused

Screenshot 2023-06-28 at 12 29 23

removing the rule in `public/app/features/plugins/admin/components/PluginDetailsPage.tsx` fixes the issue, however i'm not sure if it ha any unwanted side effect

### PR DESCRIPTION
**Pull request by academo**
**What is this feature?**

Adds a small left-padding to the app details page to prevent fields outlines not showing correctly

Before:
image

After:
image

**Why do we need this feature?**

To fix a visual bug in the app details page introduced in https://github.com/grafana/grafana/pull/58741

**Who is this feature for?**

All users visiting an app details page

**Which issue(s) does this PR fix?**:

fixes https://github.com/grafana/grafana/issues/70820

Fixes #

**Special notes for your reviewer:**

Please check that:

- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/plugins/admin/components/PluginDetailsPage.tsx [hunk 1]
```diff
@@ -111,6 +111,7 @@ export const getStyles = (theme: GrafanaTheme2) => {
     tabContent: css`
       overflow: auto;
```
Comment (jackw) [inline public/app/features/plugins/admin/components/PluginDetailsPage.tsx:112]: Is this `overflow:auto` needed? We have a custom scrollbar for the page-inner which should be all that's required for scrolling the page. 🤔

Comment (academo) [reply public/app/features/plugins/admin/components/PluginDetailsPage.tsx:112]: @leventebalogh added it in his previous commit. I am not sure what is the use case for it. If we can remove it would be the best. @leventebalogh do you remember why ?

Comment (leventebalogh) [reply public/app/features/plugins/admin/components/PluginDetailsPage.tsx:112]: Phew, good question. I added this comment above it `// Needed due to block formatting context`, but unfortunately I don't remember what was the actual reason. Probably it's not needed anymore?

**Review by leventebalogh — APPROVED** [review]
Apart from the `overflow: auto` discussion - LGTM 👍
