### PR TITLE
Supplementary Query Error: Align buttons to the right / Update timeout message

### LINKED ISSUE #64627: Loki Logs Volume: Users should be able to reload then the request times out
It seems to be a recurring theme that the logs volume request times out. When it happens, two things happen:

Image

1. The message we display is not easy to understand / potentially confusing.
2. The users have no direct workaround for it, for example, requesting it again.

We need to explore the possibility of improving the displayed message, and also adding the alternative to repeat the request.

### PR DESCRIPTION
**Pull request by matyax**
As agreed with @radiorental , the request was to:

- Update the timeout message to this shorter version.
- Align the buttons within the alert to the right.

An additional change included in these changes is to decrease the width of the alert and center it, because otherwise it would have 100% width, looking like:

100% width

**Who is this feature for?**

Users who use explore with the logs volume panel open and experience errors and timeouts. The main goal for all these changes has been to do a better job, clearly communicating to the user what failed. It was reported that the warning and the cryptic message was confusing for users, thinking that the actual logs query failed.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/64627

**Special notes for your reviewer:**

How it looks after these changes:

Other errors:

Alert

Other errors expanded:

Expanded alert

Timeout in a small screen:

Small screen

Timeout in a bigger screen:

Bigger screen

** How to test **
Tthe easiest way is to harcode a true here:

https://github.com/grafana/grafana/blob/dc8827a10df28bc647cae0328b50707197c8edd5/public/app/features/explore/LogsVolumePanelList.tsx#L65

```javascript
const timeoutError = isTimeoutErrorResponse(logsVolumeData) || true;
```

A more real-world scenario would be to have a Loki instance with old data, request logs from a long time interval (last 30 days) and have the logs volume panel timeout on you.

### CODE REVIEW

File: public/app/features/explore/SupplementaryResultError.tsx [hunk 1]
```diff
@@ -19,27 +20,52 @@ export function SupplementaryResultError(props: Props) {
...
+            </div>
+          )}
+        </div>
+      </Alert>
+    </div>
   );
 }
+
+const getStyles = (theme: GrafanaTheme2) => {
+  return {
```
Comment (matyax) [inline public/app/features/explore/SupplementaryResultError.tsx:57]: These styles are necessary because the `Alert` component has `overflow: auto` set for the content. https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Alert/Alert.tsx#L168

Overflow

**Review by ivanahuckova — COMMENTED** [review]
Wouldn't we want to align to the left rather than middle. Is there already a pattern where we would do this with alert?

**Comment by radiorental** [comment]
> Wouldn't we want to align to the left rather than middle. Is there already a pattern where we would do this with alert?
I discussed with the design system folks, we agreed...

- We need a better component for this type of interaction (something has happened, do you want to proceed or dismiss)
- The current notification component wasn't design for this transient inline interaction
- Left, center & right justification all look weird in their own way.  Go with Center for now.

With that in mind, this is a SHIP IT from UX.  Thanks @matyax

**Review by radiorental — APPROVED** [review]
SHIP IT

**Comment by matyax** [comment]
The split view is a good catch. I'll adjust that, thanks @svennergr !

**Comment by matyax** [comment]
Updated widths to play more nicely with smaller screens, and above all, split view.

Min width

For smaller viewports, Grafana starts hiding things (independent of the error message).

Eating contents

Demo:



What do you think?

**Comment by gelicia** [comment]
@matyax How is best to replicate a log query timeout? Throttle internet? something else?

**Comment by matyax** [comment]
@gelicia the easiest way would be to harcode a true here:

https://github.com/grafana/grafana/blob/dc8827a10df28bc647cae0328b50707197c8edd5/public/app/features/explore/LogsVolumePanelList.tsx#L65

```javascript
const timeoutError = isTimeoutErrorResponse(logsVolumeData) || true;
```

A more real-world scenario would be to have a Loki instance with old data, request logs from a long time interval (last 30 days) and have the logs volume panel timeout on you.

**Comment by Pauric** [comment]
DO NOT THROTTLE INTERNET FFS!

Only joking.

I don’t know why I’m getting these emails, but they’re entertaining. Probably best to remove me from the email list.

Thanks.

**Comment by gelicia** [comment]
@radiorental to stop getting notifications from this ticket, please click the unsubscribe button on the right side. We cannot do that for you.
Screenshot 2023-04-03 at 4 05 21 PM

**Comment by matyax** [comment]
Oops, my bad. Thank you for correcting it @gelicia . Apologies @ pauric 😅

**Comment by Pauric** [comment]
No problem Matias,

For what it’s worth, I think the button should be aligned to the right on all screens except portrait tablet & phone, where it aligns to the left under the text.  

You have not been charged for this information.

Good luck with your project.

Pauric

**Review by gelicia — APPROVED** [review]

**Review by ivanahuckova — APPROVED** [review]

**Comment by matyax** [comment]
Thanks everyone!
