### PR TITLE
BarChart: add negY transform to fieldConfig overrides

### LINKED ISSUE #55348: Stacking in bar and timeseries plots when negative values are present is incorrect
Tested with Grafana 9.1.2 and 9.1.5

The data is (data columns correspond to green, yellow, red colors in the graphs below)
2022-09-18_22-25-16_3290x603
This is what I get with stacked bar plot (changing to stacked timeseries plot shows the same issue)
2022-09-18_22-49-49_3018x783
An example of the issue is for 11:00 and 12:00 - both yellow values should have exactly the same height (their values are 1100).

If I hide the green (negative values), then the yellow and red values are OK

2022-09-18_22-24-29_3465x1702

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes #55348

makes negative y transform field override available in BarChart panel; adjusts label positions accordingly.

<details><summary>neg-y-bars.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 349,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "fillOpacity": 30,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1,
            "scaleDistribution": {
              "type": "linear"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "b"
            },
            "properties": [
              {
                "id": "custom.transform",
                "value": "negative-Y"
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 14,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 6,
      "options": {
        "barRadius": 0,
        "barWidth": 0.97,
        "groupWidth": 0.7,
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "orientation": "vertical",
        "showValue": "auto",
        "stacking": "none",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "xField": "time",
        "xTickLabelRotation": 0,
        "xTickLabelSpacing": 0
      },
      "targets": [
        {
          "alias": "a",
          "csvContent": "time,metric,value\n2022-09-01T19:00:00Z, a, 100\n2022-09-01T19:00:00Z, c, 150\n2022-09-01T20:00:00Z, a, 200\n2022-09-01T20:00:00Z, b, 300\n2022-09-01T20:00:00Z, c, 150\n2022-09-01T21:00:00Z, a, 250\n2022-09-01T21:00:00Z, b, 350\n2022-09-01T21:00:00Z, c, 150",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "transformations": [
        {
          "id": "prepareTimeSeries",
          "options": {
            "format": "many"
          }
        },
        {
          "id": "prepareTimeSeries",
          "options": {
            "format": "wide"
          }
        },
        {
          "id": "organize",
          "options": {
            "excludeByName": {
              "time": false
            },
            "indexByName": {
              "time": 0,
              "value {metric=\"a\", name=\"a\"}": 1,
              "value {metric=\"b\", name=\"a\"}": 2,
              "value {metric=\"c\", name=\"a\"}": 3
            },
            "renameByName": {
              "value {metric=\"a\", name=\"a\"}": "a",
              "value {metric=\"b\", name=\"a\"}": "b",
              "value {metric=\"c\", name=\"a\"}": "c"
            }
          }
        }
      ],
      "type": "barchart"
    },
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "fillOpacity": 30,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1,
            "scaleDistribution": {
              "type": "linear"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "b"
            },
            "properties": [
              {
                "id": "custom.transform",
                "value": "negative-Y"
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 15,
        "w": 12,
        "x": 12,
        "y": 0
      },
      "id": 3,
      "options": {
        "barRadius": 0,
        "barWidth": 0.97,
        "groupWidth": 0.7,
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "orientation": "auto",
        "showValue": "auto",
        "stacking": "normal",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "xField": "time",
        "xTickLabelRotation": 0,
        "xTickLabelSpacing": 0
      },
      "targets": [
        {
          "alias": "a",
          "csvContent": "time,metric,value\n2022-09-01T19:00:00Z, a, 100\n2022-09-01T19:00:00Z, c, 150\n2022-09-01T20:00:00Z, a, 200\n2022-09-01T20:00:00Z, b, 300\n2022-09-01T20:00:00Z, c, 150\n2022-09-01T21:00:00Z, a, 250\n2022-09-01T21:00:00Z, b, 350\n2022-09-01T21:00:00Z, c, 150",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "transformations": [
        {
          "id": "prepareTimeSeries",
          "options": {
            "format": "many"
          }
        },
        {
          "id": "prepareTimeSeries",
          "options": {
            "format": "wide"
          }
        },
        {
          "id": "organize",
          "options": {
            "excludeByName": {
              "time": false
            },
            "indexByName": {
              "time": 0,
              "value {metric=\"a\", name=\"a\"}": 1,
              "value {metric=\"b\", name=\"a\"}": 2,
              "value {metric=\"c\", name=\"a\"}": 3
            },
            "renameByName": {
              "value {metric=\"a\", name=\"a\"}": "a",
              "value {metric=\"b\", name=\"a\"}": "b",
              "value {metric=\"c\", name=\"a\"}": "c"
            }
          }
        }
      ],
      "type": "barchart"
    },
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "fillOpacity": 30,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1,
            "scaleDistribution": {
              "type": "linear"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "b"
            },
            "properties": [
              {
                "id": "custom.transform",
                "value": "negative-Y"
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 15,
        "w": 12,
        "x": 0,
        "y": 14
      },
      "id": 5,
      "options": {
        "barRadius": 0,
        "barWidth": 0.97,
        "groupWidth": 0.7,
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "orientation": "horizontal",
        "showValue": "auto",
        "stacking": "none",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "xField": "time",
        "xTickLabelRotation": 0,
        "xTickLabelSpacing": 0
      },
      "targets": [
        {
          "alias": "a",
          "csvContent": "time,metric,value\n2022-09-01T19:00:00Z, a, 100\n2022-09-01T19:00:00Z, c, 150\n2022-09-01T20:00:00Z, a, 200\n2022-09-01T20:00:00Z, b, 300\n2022-09-01T20:00:00Z, c, 150\n2022-09-01T21:00:00Z, a, 250\n2022-09-01T21:00:00Z, b, 350\n2022-09-01T21:00:00Z, c, 150",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "transformations": [
        {
          "id": "prepareTimeSeries",
          "options": {
            "format": "many"
          }
        },
        {
          "id": "prepareTimeSeries",
          "options": {
            "format": "wide"
          }
        },
        {
          "id": "organize",
          "options": {
            "excludeByName": {
              "time": false
            },
            "indexByName": {
              "time": 0,
              "value {metric=\"a\", name=\"a\"}": 1,
              "value {metric=\"b\", name=\"a\"}": 2,
              "value {metric=\"c\", name=\"a\"}": 3
            },
            "renameByName": {
              "value {metric=\"a\", name=\"a\"}": "a",
              "value {metric=\"b\", name=\"a\"}": "b",
              "value {metric=\"c\", name=\"a\"}": "c"
            }
          }
        }
      ],
      "type": "barchart"
    },
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "fillOpacity": 30,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1,
            "scaleDistribution": {
              "type": "linear"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "b"
            },
            "properties": [
              {
                "id": "custom.transform",
                "value": "negative-Y"
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 14,
        "w": 12,
        "x": 12,
        "y": 15
      },
      "id": 4,
      "options": {
        "barRadius": 0,
        "barWidth": 0.97,
        "groupWidth": 0.7,
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "orientation": "horizontal",
        "showValue": "auto",
        "stacking": "normal",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "xField": "time",
        "xTickLabelRotation": 0,
        "xTickLabelSpacing": 0
      },
      "targets": [
        {
          "alias": "a",
          "csvContent": "time,metric,value\n2022-09-01T19:00:00Z, a, 100\n2022-09-01T19:00:00Z, c, 150\n2022-09-01T20:00:00Z, a, 200\n2022-09-01T20:00:00Z, b, 300\n2022-09-01T20:00:00Z, c, 150\n2022-09-01T21:00:00Z, a, 250\n2022-09-01T21:00:00Z, b, 350\n2022-09-01T21:00:00Z, c, 150",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "transformations": [
        {
          "id": "prepareTimeSeries",
          "options": {
            "format": "many"
          }
        },
        {
          "id": "prepareTimeSeries",
          "options": {
            "format": "wide"
          }
        },
        {
          "id": "organize",
          "options": {
            "excludeByName": {
              "time": false
            },
            "indexByName": {
              "time": 0,
              "value {metric=\"a\", name=\"a\"}": 1,
              "value {metric=\"b\", name=\"a\"}": 2,
              "value {metric=\"c\", name=\"a\"}": 3
            },
            "renameByName": {
              "value {metric=\"a\", name=\"a\"}": "a",
              "value {metric=\"b\", name=\"a\"}": "b",
              "value {metric=\"c\", name=\"a\"}": "c"
            }
          }
        }
      ],
      "type": "barchart"
    }
  ],
  "refresh": false,
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "2022-09-01T18:13:18.658Z",
    "to": "2022-09-01T22:07:45.586Z"
  },
  "timepicker": {},
  "timezone": "",
  "title": "test-stack",
  "uid": "piJUyWV4z",
  "version": 11,
  "weekStart": ""
}
```
</details>

image

### CODE REVIEW

File: public/app/plugins/panel/barchart/bars.ts [hunk 1]
```diff
@@ -352,13 +353,24 @@ export function getConfig(opts: BarsOptions, theme: GrafanaTheme2) {
...
+            u.bbox.left +
+            (isXHorizontal ? lft + wid / 2 : xFormedValue < 0 ? lft - labelOffset : lft + wid + labelOffset);
           const y =
             u.bbox.top +
-            (isXHorizontal ? (value < 0 ? top + hgt + labelOffset : top - labelOffset) : top + hgt / 2 - middleShift);
+            (isXHorizontal
+              ? xFormedValue < 0
+                ? top + hgt + labelOffset
+                : top - labelOffset
+              : top + hgt / 2 - middleShift);
```
Comment (leeoniya) [inline public/app/plugins/panel/barchart/bars.ts:373]: i hate this Prettier auto-formatting in a pre-commit hook. the only change here is renaming `value` -> `xFormedValue`.

same story for the diff below.

File: public/app/plugins/panel/barchart/module.tsx [hunk 2]
```diff
@@ -63,6 +63,28 @@ export const plugin = new PanelPlugin<PanelOptions, PanelFieldConfig>(BarChartPa
...
+              label: 'Negative Y',
+              value: GraphTransform.NegativeY,
+              description: 'Flip the results to negative values on the y axis',
+            },
+          ],
+          isClearable: true,
+        },
+        hideFromDefaults: true,
+      });
+
```
Comment (leeoniya) [inline public/app/plugins/panel/barchart/module.tsx:87]: copy-paste from TimeSeries:

https://github.com/grafana/grafana/blob/6aef353b59836941456cc25573858d9081f94f38/public/app/plugins/panel/timeseries/config.ts#L186-L206

**Review by codeincarnate — APPROVED** [review]
LGTM
