### PR TITLE
Provisioning: Move OSS provisioning to Run step

### LINKED ISSUE #105397: Provisioning: Removing `alertingSimplifiedRouting` breaks app plugin provisioning
In the plugins-platform team we have these integration tests that check that the plugin platform at a daily interval. Yesterday we got a notification that one of our e2e tests [were failing](https://github.com/grafana/plugin-tools/actions/runs/14998912653/job/42186772711?pr=1789).

Investigation lead us to this PR: https://github.com/grafana/grafana/pull/104980 or this PR : https://github.com/grafana/grafana/pull/105080

Before these PRs the provisioning works flawless but after the PR it fails.

Steps to reproduce:
1. git clone https://github.com/grafana/plugin-tools.git
2. run `cd plugin-tools`
3. run `npm ci`
4. run `npm run build --w @grafana/plugin-e2e`
5. run `npx playwright install --with-deps chromium`
6. run `cd ./packages/plugin-e2e`
7. run `ANONYMOUS_AUTH_ENABLED=false GRAFANA_IMAGE=grafana-dev GRAFANA_VERSION=12.1.0-242641 docker compose up`
8. look at the logs it gets stuck on

```logs
grafana-1  | logger=plugindashboards t=2025-05-14T09:04:39.003014172Z level=info msg="Plugin state changed" pluginId=redis-app enabled=true
grafana-1  | logger=plugindashboards t=2025-05-14T09:04:39.003028005Z level=info msg="Syncing plugin dashboards to DB" pluginId=redis-app
grafana-1  | logger=plugindashboards t=2025-05-14T09:04:39.004118755Z level=info msg="Auto updating App dashboard" dashboard="Redis Overview" newRev=1 oldRev=0
```

9. stop docker compose
10. run `docker compose down`
11. run `ANONYMOUS_AUTH_ENABLED=false GRAFANA_IMAGE=grafana-dev GRAFANA_VERSION=12.1.0-242630 docker compose up` -- this is the commit before
12.  look at the logs and it doesn't get stuck

```logs
grafana-1  | logger=plugindashboards t=2025-05-14T08:35:58.768928875Z level=info msg="Syncing plugin dashboards to DB" pluginId=redis-app
grafana-1  | logger=plugindashboards t=2025-05-14T08:35:58.770140792Z level=info msg="Auto updating App dashboard" dashboard="Redis Overview" newRev=1 oldRev=0
grafana-1  | logger=plugindashboards t=2025-05-14T08:35:58.776873459Z level=info msg="Auto updating App dashboard" dashboard="Redis CLI" newRev=1 oldRev=0
grafana-1  | logger=plugindashboards t=2025-05-14T08:35:58.782294292Z level=info msg="Auto updating App dashboard" dashboard=RedisGears newRev=1 oldRev=0
```

### PR DESCRIPTION
**Pull request by filewalkwithme**
**What is this feature?**

Move back all OSS provisioning initializers to Run() method. 

We had to do that because OSS provisioning initializers depends on `/apis/*` to be ready and listening, so we can retrieve folders and dashboards. This only happen after the Server is initialized and running. Otherwise, the provisioning initializers will be stuck, waiting for the `/apis/*` to answer, creating a "deadlock".

**Why do we need this feature?**

Currently, the provisioning of plugins is causing e2e tests to fail.

**Who is this feature for?**

@grafana/grafana-search-and-storage 

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/105397

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by wbrowne** [comment]
Thanks for taking care of this @filewalkwithme. It would be great if possible to add a test for this, because this could very easily have gone out unnoticed! I tried already to write an integration test, but can't seem to get the right test setup - but will keep noodling on it.

Aside (for anyone else who feels this pain): It also feels like it would be good to have a more reliable runtime dependency mechanism within the backend now that we are moving towards a more service oriented approach (IE service A relies on Service X,Y and Z and can only start once all are healthy)

File: pkg/services/provisioning/provisioning.go [hunk 1]
```diff
@@ -171,30 +171,36 @@ type ProvisioningServiceImpl struct {
 }
 
 func (ps *ProvisioningServiceImpl) RunInitProvisioners(ctx context.Context) error {
```
Comment (toddtreece) [inline pkg/services/provisioning/provisioning.go:173]: does this function need to exist if it's empty? i think previously it was being called from `Run()`

Comment (filewalkwithme) [reply pkg/services/provisioning/provisioning.go:173]: this is defined by the `ProvisioningService` interface. I checked and saw that the enterprise implementation is not empty, so I thought it would be safer to just keep this method as part of the interface definition.

Comment (toddtreece) [reply pkg/services/provisioning/provisioning.go:173]: @filewalkwithme is there a chance that enterprise could hit this issue? i'm wondering if moving the `RunInitProvisioners()` back to inside `Run()` would help avoid that

**Review by toddtreece — APPROVED** [review]

File: pkg/services/provisioning/provisioning.go (hunk 1 above)
Comment (filewalkwithme) [reply pkg/services/provisioning/provisioning.go:173]: This will occur whenever an init provisioner needs to use a Service that goes through k8s apis (currently Folders and Dashboards), regardless of OSS or Enterprise code
