### PR TITLE
TimeseriesPanel: Preserve string fields for data link interpolation

### LINKED ISSUE #58307: Timeseries datalinks don't replace string field variable
**What happened**:
Creating a data link in the timeseries panel which references a string field variable (e.g: `${__data.fields.stringField}` does not correctly replace the variable with the desired value.

**What you expected to happen**:
Replace the variable with it's correct value.

**How to reproduce it (as minimally and precisely as possible)**:
Easily reproducible on the TestData DS using `CSV Content`:
```
time, numberField, stringField
1667809287000,2,test1
1667812887000,3,test2
1667816487000,4,test3
```

Create a datalink and add title and URL : `fields ${__data.fields.numberField} ${__data.fields.stringField}`

It is noticeable that the numberField gets replaced with the correct value but the stringField does not.

**Anything else we need to know?**:
Caused by https://github.com/grafana/grafana/pull/56729

**Environment**:
- Grafana version: >9.2.0

### PR DESCRIPTION
**Pull request by mdvictor**
**What is this feature?**
Fixes an issue where string field variables (e.g: `${__data.fields.stringField}` would not be replaced with a value in datalinks.

**Why do we need this feature?**
To have support for string fields in timeseries panel

**Who is this feature for?**
Timeseries users that also use data links.

**Which issue(s) does this PR fix?**:

Fixes #58307

### CODE REVIEW

File: public/app/plugins/panel/timeseries/utils.ts [hunk 1]
```diff
@@ -123,3 +136,41 @@ export function getTimezones(timezones: string[] | undefined, defaultTimezone: s
...
+          clonedFrameField.values = new SortedVector(frameField.values, field.values.getOrderArray());
+          tempFrame.fields.push(clonedFrameField);
+        } else {
+          tempFrame.fields.push(frameField);
+        }
+      }
+    }
+
+    field.getLinks = getLinksSupplier(tempFrame, field, field.state!.scopedVars!, replaceVariables, timeZone);
+  });
```
Comment (oscarkilhed) [inline public/app/plugins/panel/timeseries/utils.ts:173]: This looks a bit scary from a performance standpoint. Does this run when data updates or when the user tries to view the datalinks?

Comment (leeoniya) [reply public/app/plugins/panel/timeseries/utils.ts:173]: agreed. i cannot review for a few days (out of office)

File: public/app/plugins/panel/timeseries/utils.ts [hunk 2]
```diff
@@ -123,3 +136,41 @@ export function getTimezones(timezones: string[] | undefined, defaultTimezone: s
...
+): DataFrame {
+  alignedDataFrame.fields.forEach((field) => {
+    const frameIndex = field.state?.origin?.frameIndex;
+
+    if (frameIndex === undefined) {
+      return;
+    }
+
+    const frame = frames[frameIndex];
+    const tempFrame = cloneDeep(alignedDataFrame);
```
Comment (leeoniya) [inline public/app/plugins/panel/timeseries/utils.ts:154]: 😬

File: public/app/plugins/panel/timeseries/utils.ts [hunk 3]
```diff
@@ -123,3 +136,41 @@ export function getTimezones(timezones: string[] | undefined, defaultTimezone: s
...
+
+    /* check if field has sortedVector values
+      if it does, sort all string fields in the original frame by the order array already used for the field
+      otherwise just attach the fields to the temporary frame used to get the links
+    */
+    for (const frameField of frame.fields) {
+      if (frameField.type === FieldType.string) {
+        if (field.values instanceof SortedVector) {
+          const clonedFrameField = cloneDeep(frameField);
```
Comment (leeoniya) [inline public/app/plugins/panel/timeseries/utils.ts:163]: 😬

File: public/app/plugins/panel/timeseries/utils.ts (hunk 1 above)
Comment (mdvictor) [reply public/app/plugins/panel/timeseries/utils.ts]: This runs every time the data updates. I took out the `cloneDeep` calls

**Review by zoltanbedi — COMMENTED** [review]
I've tried this out and works as expected now but I let others review the code performance wise.

File: public/app/plugins/panel/timeseries/utils.ts [hunk 4]
```diff
@@ -123,3 +134,46 @@ export function getTimezones(timezones: string[] | undefined, defaultTimezone: s
...
+    const frameIndex = field.state?.origin?.frameIndex;
+
+    if (frameIndex === undefined) {
+      return;
+    }
+
+    const frame = frames[frameIndex];
+    const tempFields: Field[] = [];
+
+    /* check if field has sortedVector values
```
Comment (codeincarnate) [inline public/app/plugins/panel/timeseries/utils.ts:154]: A nitpick, but I think inline comments are usually better for cases like this. Like:

```js
// Line 1
// Line 2
// Line 3
```

File: public/app/plugins/panel/timeseries/utils.ts [hunk 5]
```diff
@@ -123,3 +134,46 @@ export function getTimezones(timezones: string[] | undefined, defaultTimezone: s
...
+      if it does, sort all string fields in the original frame by the order array already used for the field
+      otherwise just attach the fields to the temporary frame used to get the links
+    */
+    for (const frameField of frame.fields) {
+      if (frameField.type === FieldType.string) {
```
Comment (codeincarnate) [inline public/app/plugins/panel/timeseries/utils.ts:159]: Seems like having a single `if` here would make more sense rather than nesting them as in this case it's basically an `&&` of two condition together.

Comment (mdvictor) [reply public/app/plugins/panel/timeseries/utils.ts:159]: I think I would still need two `if` statements, since the second statement is an `if/else`, both executed in the case the field type is string. I could avoid nesting by checking for `field.type !== string` and `continue`ing.

File: public/app/plugins/panel/timeseries/utils.ts [hunk 6]
```diff
@@ -123,3 +134,46 @@ export function getTimezones(timezones: string[] | undefined, defaultTimezone: s
...
+          tempFields.push(copiedField);
+        } else {
+          tempFields.push(frameField);
+        }
+      }
+    }
+
+    const tempFrame: DataFrame = {
+      fields: [...alignedDataFrame.fields, ...tempFields],
+      length: alignedDataFrame.length + tempFields.length,
```
Comment (torkelo) [inline public/app/plugins/panel/timeseries/utils.ts:172]: is length not the number of rows (the length of each field values array).  how can it be set to the addition of both lenghs here?

Comment (mdvictor) [reply public/app/plugins/panel/timeseries/utils.ts:172]: you are right, that's a mistake :S Should be the addition of the number of fields in the Dataframe/array

File: public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx [hunk 7]
```diff
@@ -65,15 +65,7 @@ export const TimeSeriesPanel: React.FC<TimeSeriesPanelProps> = ({
...
-        alignedDataFrame.fields.forEach((field) => {
-          field.getLinks = getLinksSupplier(
-            alignedDataFrame,
-            field,
-            field.state!.scopedVars!,
-            replaceVariables,
-            timeZone
-          );
-        });
+        alignedDataFrame = regenerateLinksSupplier(alignedDataFrame, frames, replaceVariables, timeZone);
```
Comment (torkelo) [inline public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx:68]: Is there a way to skip this step when there are no data links or the aligned frame is the same as source frame?

**Review by torkelo — APPROVED** [review]

File: public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx (hunk 7 above)
Comment (mdvictor) [reply public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx]: I just added a check to skip if no data links are present in the aligned df. the latter comparison gets tricky since the source frame is actually an array of dataframes.

**Comment by Lroy** [comment]
mdvictor, I have been watching for this enhancement to surface in the latest Grafana builds.

During testing of this enhancement today, I notice that the panel data links work as expected, and my string field values can be passed along as variables to another dashboard, just like I had hoped.

I also noticed that this enhancement does not work for field overrides.  Is that by design? Is there some underlying problem with getting the data link concept to work when using a field override for a string field?

**Comment by mdvictor** [comment]
Hey @Lroy,

I think this should work just as well. Can you share the example where you had problem with string fields in data link overrides? I've looked into a scenario where I tried to build an overriden data link with a string field and managed to do so fine. Thank you!

**Comment by Lroy** [comment]
Sure! I have attached two screen shots.  

First one works (Data links section of Panel Config).  "Display Image" appears on the context menu when clicking on a data point on the chart.

Second one doesn't work (Field override from Overrides in Panel Config). "Field Override - Show Image" does not appear on the context menu when clicking on a data point on the chart.

Works
Doesnt Work

**Comment by mdvictor** [comment]
Hey @Lroy. I believe the reason this happens is because you override the string field itself. If you want your overriden data link to appear, you need to change `Fields with name` with the value field used for the timeseries (e.g: `DataMaxValue` in your scenario). Then the overriden data link should appear in the tooltip and the link itself should contain the interpolated string.

**Comment by Lroy** [comment]
You are correct, sir! I have been trying to get this field override to work for quite some time, and did not realize the problem. Thank you very much for responding!
