### PR TITLE
Fix setting oauthPassThru flag

### LINKED ISSUE #72469: Bug: Setting oauthPassThru flag causes crash while setting AlertManager datasource
Related PR: https://github.com/grafana/grafana/pull/71640

Image

Image

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

UI broken after setting an alert manager data source to receive Grafana alerts. This Pr is addressing that issue by setting the `oauthPassThru` flag more robust way. 

Fixes https://github.com/grafana/grafana/issues/72469

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/DataSourceSettings/DataSourceHttpSettings.tsx [hunk 1]
```diff
@@ -78,9 +78,31 @@ export const DataSourceHttpSettings = (props: HttpSettingsProps) => {
   } = props;
 
   const [isAccessHelpVisible, setIsAccessHelpVisible] = useState(false);
+  const [azureAuthEnabled, setAzureAuthEnabled] = useState(false);
   const theme = useTheme2();
   let urlTooltip;
 
+  useEffect(() => {
```
Comment (joshhunt) [inline packages/grafana-ui/src/components/DataSourceSettings/DataSourceHttpSettings.tsx:85]: Rather than an effect, can you do this in `onSettingsChange` ?

Comment (itsmylife) [reply packages/grafana-ui/src/components/DataSourceSettings/DataSourceHttpSettings.tsx:85]: @joshhunt I'll make the change. Not sure if that's going to be the one you asked for.

Comment (itsmylife) [reply packages/grafana-ui/src/components/DataSourceSettings/DataSourceHttpSettings.tsx]: @joshhunt Please see https://github.com/grafana/grafana/pull/72472/commits/3695109a4453bc4d5c2d7d02cf32d6ad79178c61

**Review by joshhunt — APPROVED** [review]
