### PR TITLE
Prometheus: Fix enabling of disabled queries when editing in dashboard

### LINKED ISSUE #31048: Prometheus: When editing disabled query in dashboard, it becomes enabled
**What happened**:

In dashboard, when query is disabled and you edit it, it becomes enabled. I was able to recreate this only for Prometheus, [Influx and Flux (separate issue)](https://github.com/grafana/grafana/issues/31054). I wasn't able to recreate this bug for Loki, Graphite, Elastic. 

**What you expected to happen**:
If query is disabled and I edit it, I still want it to be disabled.

**How to reproduce it (as minimally and precisely as possible)**:
Kapture 2021-02-09 at 15 50 58

**Environment**:
- Grafana version: 7.4.0

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
See https://github.com/grafana/grafana/issues/31048 for more information on how to recreate & observe the issue. The problem was that we are setting `query.hide` outside of PromQueryEditor, therefore when we are running query, we need to make sure that it has the current up-to-date hide info, but also any other query param that can be set outside of PromQueryEditor. 

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/31048

### CODE REVIEW

**Comment by zoltanbedi** [comment]
hmm I can still reproduce this bug in your branch.

**Comment by ivanahuckova** [comment]
@zoltanbedi sorry I linked the wrong issue - this fixes the disabling-enabiling bug for prometheus, not for influx. I tested it again and it seems to be working.

File: public/app/plugins/datasource/prometheus/components/PromQueryEditor.tsx [hunk 1]
```diff
@@ -92,7 +92,9 @@ export class PromQueryEditor extends PureComponent<Props, State> {
 
   onRunQuery = () => {
     const { query } = this;
-    this.props.onChange(query);
+    // Change of query.hide happes outside of this component and is just passed as prop. We have to update it when running queries.
```
Comment (zoltanbedi) [inline public/app/plugins/datasource/prometheus/components/PromQueryEditor.tsx:95]:
```suggestion
    // Change of query.hide happens outside of this component and is just passed as prop. We have to update it when running queries.
```

**Review by zoltanbedi — APPROVED** [review]
works for me now. good job 🪲
