### PR TITLE
A11y : Fix option panes not accessible when collapsed

### LINKED ISSUE #46488: A11y : Cannot access edit-mode/collapsible section via keyboard
**Steps to reproduce**:

In edit mode > panel options tab skips whole section when collapsed (but it is accessible if expanded) 

**Actual Result**:

[see video](https://drive.google.com/file/d/17tBLmtfBGgVqRWqCN4JeS1POaYGi-sQU/view?usp=sharing)

**Expected Result**

use can expand collapsible sections via keyboard

**Relevant WCAG Criteria:**

[2.1.1 Keyboard - Level A](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=335%2C332#keyboard)

**Environment**:
- Grafana version: 8.4.3
- Data source type & version:
- User OS & Browser:
- Others:

### PR DESCRIPTION
**Pull request by yaelleC**
## What this PR does / why we need it

To improve A11y:

Currently when editing a dashboard, option pans that are collapsed are not accessible by keyboard - and some are collapsed by default meaning a keyboard-only user would not be able to expand and use them.

This PR fixes that by turning the caret icon (angle-down or angle-right) into a button. 
It also adds the prop `aria-expanded` and `aria-controls` to it.

### Screenshots

| - | Before | After |
|--------|--------|-------|
| Not focussed |   Screenshot 2022-03-10 at 13 05 03   | Screenshot 2022-03-10 at 16 10 28 |
| Focussed |  N/A  |  Screenshot 2022-03-10 at 16 10 42  |

## Which issue(s) this PR fixes

See the list of issues the a11y Hackathon team focuses on here: https://docs.google.com/spreadsheets/d/1e3sjrB3wjgQfttK5ANNkac5wmDwLszhgW0fO1kWT2LI/edit#gid=0 

## Special notes for your reviewer
1. This PR does change the UI a bit (see screenshots each optionPane is slightly bigger in this PR's version) I don't think it does in a bad way but I'm open to comments / requests to change it 🙂 

2. I have tried a solution that would make the whole row focussable but I've ran into issues with the `override` pane as it also has a delete button and buttons cannot be embedded into each others. I find that using the caret icon is the best compromise at it fixes a high priority a11y issue all the while not disturbing the existing solution too much. Happy for it to be iterated upon in the future 🙂

### CODE REVIEW

File: public/app/features/dashboard/components/PanelEditor/OptionsPaneCategory.tsx [hunk 1]
```diff
@@ -101,12 +101,23 @@ export const OptionsPaneCategory: FC<OptionsPaneCategoryProps> = React.memo(
         ref={ref}
       >
         <div className={headerStyles} onClick={onToggle} aria-label={selectors.components.OptionsGroup.toggle(id)}>
-          <div className={cx(styles.toggle, 'editor-options-group-toggle')}>
+          <Button
+            size="sm"
```
Comment (yaelleC) [inline public/app/features/dashboard/components/PanelEditor/OptionsPaneCategory.tsx:105]: Storybook tells me a `Button` has a `xs` option for this prop that might make the rows closer to what we currently have but when I changed it , it defaulted to `md` : looks like `xs` is not a valid `size` 🤷‍♀️

**Comment by kaydelaney** [comment]
There's a component in grafana-ui `CollapsableSection`, that you might consider using for this

**Comment by yaelleC** [comment]
> There's a component in grafana-ui `CollapsableSection`, that you might consider using for this

Hi @kaydelaney , I had a go at using `CollapsibleSection` however styling it for this use case is a challenge and I ran into some UX/a11y issue with the `overrides` section where we have a delete button inside, it does not look very best practice and I actually deleted an override by mistake by while testing the component.

Screenshot 2022-03-11 at 12 51 51

I think we could go with the solution in this PR for now (to fix the fact that collapsed optionPanes are not accessible to keyboard users) and raise a GH issue to look into more detail how to modify `CollapsableSection` or create another component that would work for this use case. 
I see unified alerting also went with a caret button for accessibility; https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/components/CollapseToggle.tsx . 
My last commit modifies that element and reuses it for optionPanes.

WDYT?

**Comment by kaydelaney** [comment]
Sounds good to me 👍

**Review by kaydelaney — APPROVED** [review]

**Comment by yaelleC** [comment]
> Sounds good to me 👍

Thanks @kaydelaney , do you think I should wait for someone in @grafana/alerting-squad-frontend to 👀  and ✅  before merging?

**Review by gillesdemey — APPROVED** [review]
Changes to `CollapseToggle` look great! 👏
