### PR TITLE
fix: Extra forward slash added when org redirect middleware is called (#10263)

### LINKED ISSUE #10263: Extra forward slash added when org redirect middleware is called.
The preceding forward slash should be removed from `c.Req.URL.Path` to prevent the Location header from getting set to `Location: http://localhost:3000//dashboard/db/testdata-graph-panel-last-1h?orgId=2`

https://github.com/grafana/grafana/blob/dd2192cccc43e4d8aacc0871e96f206a915eafdd/pkg/middleware/org_redirect.go#L44

All other instances  of `setting.ToAbsUrl` use paths without a preceding forward slash.

The following code should resolve this
```go
relURL := c.Req.URL.Path
if strings.HasPrefix(relURL, "/") {
	relURL = relURL[1:]
}

newURL := setting.ToAbsUrl(fmt.Sprintf("%s?%s", relURL, c.Req.URL.Query().Encode()))
c.Redirect(newURL, 302)
```

### PR DESCRIPTION
**Pull request by SteelPhase**
Closes #10263

### CODE REVIEW

File: pkg/middleware/org_redirect.go [hunk 1]
```diff
@@ -41,7 +42,12 @@ func OrgRedirect() macaron.Handler {
 			return
 		}
 
-		newUrl := setting.ToAbsUrl(fmt.Sprintf("%s?%s", c.Req.URL.Path, c.Req.URL.Query().Encode()))
-		c.Redirect(newUrl, 302)
+		relURL := c.Req.URL.Path
+		if strings.HasPrefix(relURL, "/") {
+			relURL = relURL[1:]
```
Comment (bergquist) [inline pkg/middleware/org_redirect.go]: Thank you for taking the time to report and fix this issue.

I think this can be replaced with 
`relUrl = strings.TrimPrefix(relUlr, "/")`

Makes it more obvious what the code does. 
https://golang.org/pkg/strings/#TrimPrefix

Otherwise it looks ready to merge.

**Comment by SteelPhase** [comment]
Updated with your suggestion.

**Comment by bergquist** [comment]
Thank you for contributing!
