### PR TITLE
TablePanel: Prevents crash when data contains mixed data formats

### LINKED ISSUE #20075: grafana version 6.4.2 Table panel - unable to find application file
**What happened**:
After adding the table panel and writing more than 2 queries
(After selecting both measurement and value)
Changing the format as (when two or more queries have different format as)
grafana error :::: unable to fine application file

image

 In the situation as picture, A Query or B Query change Format as 'Table'

**Environment**:
- Grafana version: 6.4.2
- Data source type & version:  influxDB 1.7.8
- OS Grafana is installed on: Ubunto 18.04.3-desktop-amd64
- User OS & Browser: Ubunto / firefox, window/ chrom,
- Grafana plugins: Table Panel - Native Plugin
- Others: 

image

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
In the reported issue #20075 there are 2 issues, the first one is that the `SafeDynamicImport` component catched all errors so the user received an unrelated error message. The fix for this was merged with #20170. This PR handles the error thrown in the Table Panel transformers. 

Just to clarify the Table Panel doesn't support having different data formats in the queries so the results could potentially be misleading. It would be nice if we could show somehow in the UI that the data has mixed data formats. This is out of scope for this PR.

**Which issue(s) this PR fixes**:
Fixes #20075

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/core/table_model.ts [hunk 1]
```diff
@@ -99,11 +99,14 @@ export function mergeTablesIntoModel(dst?: TableModel, ...tables: TableModel[]):
     return model;
   }
 
+  // Filter out any tables that are not of TableData format
+  const tableDataTables = tables.filter(table => !!table.columns);
```
Comment (hugohaggmark) [inline public/app/core/table_model.ts]: Does this mean that this code can go away?
https://github.com/grafana/grafana/blob/46a4118461a02f7f7146696ee00715975eddcbca/public/app/features/explore/utils/ResultProcessor.ts#L39

File: public/app/plugins/panel/table/transformers.ts [hunk 2]
```diff
@@ -6,6 +6,33 @@ import { TableTransform } from './types';
 import { Column, TableData } from '@grafana/data';
 
 const transformers: { [key: string]: TableTransform } = {};
+const timeSeriesReducer = (data: any): any[] => {
```
Comment (torkelo) [inline public/app/plugins/panel/table/transformers.ts]: is it really a reducer? Feels more like a filter of sorts? a reducer I would expect to take in an array of stuff and return a single value (I guess redux reducers to something else).

File: public/app/plugins/panel/table/transformers.ts [hunk 3]
```diff
@@ -254,7 +285,8 @@ function transformDataToTable(data: any, panel: any) {
     throw { message: 'Transformer ' + panel.transform + ' not found' };
   }
 
-  transformer.transform(data, panel, model);
+  const reducedData = transformer.dataFormatReducer ? transformer.dataFormatReducer(data) : data;
```
Comment (torkelo) [inline public/app/plugins/panel/table/transformers.ts]: does this step need to be done outside the transform? maybe cleaner if this is done inside the transform function instead.

**Review by torkelo — APPROVED** [review]
looks good! just some minor nitpicks that you can ignore if you do not agree with them :)

File: public/app/plugins/panel/table/transformers.ts (hunk 2 above)
Comment (hugohaggmark) [reply public/app/plugins/panel/table/transformers.ts]: Yeah, `dataFormatFilterer`, `timeSeriesFilterer` and `tableFilterer` might be better naming.

File: public/app/core/table_model.ts (hunk 1 above)
Comment (torkelo) [reply public/app/core/table_model.ts]: don't think so that is something else, without that Prometheus results will show time series in graph and table (where we only want table (instant) query result in table).

File: public/app/plugins/panel/table/transformers.ts (hunk 3 above)
Comment (hugohaggmark) [reply public/app/plugins/panel/table/transformers.ts]: Ok I can see why that could potentially become a problem if transform is called without the filtering. Will change!

**Review by davkal — APPROVED** [review]
Nicely done. Code looks good, and I tested all combinations, even timeseries+timeseries still works.
