### PR TITLE
Prometheus: fixes regex ad-hoc filters variables with wildcards

### LINKED ISSUE #14615: Regex ad-hoc filters with wildcards return no data with Prometheus
### What Grafana version are you using?

Grafana 5.4.2

### What datasource are you using?

Prometheus 2.5.0

### What OS are you running grafana on?

Linux

### What did you do?

I'm looking at adhoc filters. While automatic discovery of labels isn't there, they work if I enter labels manually.

### What was the expected result?

I'd expect regex queries work with wildcards as well.

### What happened instead?

instance = HOST.DOMAIN.COM – works
instance =~ HOST.DOMAIN.COM – works
instance =~ HOST.DOMAIN.* – doesn't work

Queries using adhoc filters with regexes and wildcards return always no data at all.

### PR DESCRIPTION
**Pull request by daniellee**
Fixes #14615 

Removes extra escaping for regex filter values when using ad hoc filters for Prometheus. The extra escaping causes queries with regex characters to be invalid.

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/datasource.ts [hunk 1]
```diff
@@ -1,22 +1,20 @@
...
+import PrometheusLanguageProvider from './language_provider';
 import { expandRecordingRules } from './language_utils';
-
+import PrometheusMetricFindQuery from './metric_find_query';
+import { getQueryHints } from './query_hints';
+import { ResultTransformer } from './result_transformer';
 // Types
 import { PromQuery } from './types';
-import { DataQueryOptions, DataSourceApi, AnnotationEvent } from '@grafana/ui/src/types';
-import { ExploreUrlState } from 'app/types/explore';
```
Comment (torkelo) [inline public/app/plugins/datasource/prometheus/datasource.ts]: These types seems to have move up in the import and is no longer under // Types, deliberate?

**Review by torkelo — APPROVED** [review]

**Review by torkelo — APPROVED** [review]
looks good, can't find reason for the special escape, only the commit 2.5 years ago, https://github.com/grafana/grafana/commit/46ebae73043d731bf166abb7b1a929270fa8d174 but no explanation

File: public/app/plugins/datasource/prometheus/datasource.ts (hunk 1 above)
Comment (daniellee) [reply public/app/plugins/datasource/prometheus/datasource.ts]: No, that is prettier doing that I think and sorting them alphabetically. Have I got an incorrect setting?

Comment (torkelo) [reply public/app/plugins/datasource/prometheus/datasource.ts]: yes, prettier has no such sorting

Comment (torkelo) [reply public/app/plugins/datasource/prometheus/datasource.ts]: maybe a vs code setting?

Comment (torkelo) [reply public/app/plugins/datasource/prometheus/datasource.ts]: or plugin

Comment (daniellee) [reply public/app/plugins/datasource/prometheus/datasource.ts]: My TSLint plugin was doing it - have fixed it now.
