### PR TITLE
Heatmap: Use displayName to test if numeric bucket fields

### LINKED ISSUE #71152: Precalculated prometheus heatmap buckets are ordered alphabetically even they are numbers
### 
# What went wrong?

**What happened**:

  - I created an prometheus query and created y axis values that are numbers (=days of the month). The numbers are sorted alphabetically in the heatmap.

image

**What did you expect to happen**:

  - numerical sorted y axis

### 
# How do we reproduce it?

Use the debug panel information provided.

### 
# What Grafana version are you using?

10.0.1 (5a30620b85) // Open Source

### 
### Is the bug inside a Dashboard Panel?

[Panel debug snapshot dashboard.txt](https://github.com/grafana/grafana/files/11970734/Panel.debug.snapshot.dashboard.txt)

### Grafana Platform?

None

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

Related:
- https://github.com/grafana/grafana/issues/60545
- https://github.com/grafana/grafana/issues/69877

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/grafana/issues/71152

the time series format of the prometheus response there returns numeric `displayNameFromDS`

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/result_transformer.ts [hunk 1]
```diff
@@ -674,8 +674,8 @@ export function sortSeriesByLabel(s1: DataFrame, s2: DataFrame): number {
 
   try {
     // fail if not integer. might happen with bad queries
-    le1 = parseSampleValue(s1.name ?? s1.fields[1].name);
-    le2 = parseSampleValue(s2.name ?? s2.fields[1].name);
+    le1 = parseSampleValue(s1.name ?? s1.fields[1].state?.displayName ?? s1.fields[1].name);
+    le2 = parseSampleValue(s2.name ?? s2.fields[1].state?.displayName ?? s2.fields[1].name);
```
Comment (leeoniya) [inline public/app/plugins/datasource/prometheus/result_transformer.ts:678]: i don't like this.

not sure if we can use `getFieldDisplayName(s1.fields[1], s1)`, since we don't have all frames here for third arg and both Transforms and Field overrides can change the display name after these frames are returned :(

File: public/app/plugins/panel/heatmap/fields.ts [hunk 2]
```diff
@@ -65,6 +66,13 @@ export function prepareHeatmapData(
     return {};
   }
 
+  // cache field.state.displayName
+  frames.forEach((fr) => {
+    fr.fields.forEach((fl) => {
+      getFieldDisplayName(fl, fr, frames);
```
Comment (ryantxu) [inline public/app/plugins/panel/heatmap/fields.ts:72]: did you add a utility for this recently?

Comment (leeoniya) [reply public/app/plugins/panel/heatmap/fields.ts:72]: :facepalm: you don't actually expect me to remember what happened [a week ago](https://github.com/grafana/grafana/pull/71161), do you?

**Review by gtk-grafana — DISMISSED** [review]
I can verify that this fixes the bug, and doesn't seem to break anything. But can we add a unit test for `sortSeriesByLabel` that covers sorting numerically and alphabetically? I could see this functionality being inadvertently broken in the future

**Review by nmarrs — APPROVED** [review]
image

File: public/app/plugins/panel/heatmap/fields.ts [hunk 3]
```diff
@@ -109,7 +112,7 @@ export function prepareHeatmapData(
   if (!rowsHeatmap) {
     if (frames.length > 1) {
       let allNamesNumeric = frames.every(
-        (frame) => !Number.isNaN(parseSampleValue(frame.name ?? frame.fields[1].name))
+        (frame) => !Number.isNaN(parseSampleValue(frame.fields[1].state?.displayName!))
```
Comment (leeoniya) [inline public/app/plugins/panel/heatmap/fields.ts:115]: verified that removal of `frame.name` here does not regress the issues fixed by https://github.com/grafana/grafana/pull/65322
