### PR TITLE
Dashboards: Show copy menu item to editors (regardless of dashboard edit state)

### LINKED ISSUE #58548: Dashboards: `Copy` button should still be visible/usable on non-editable dashboards
**What happened**:
I tried to copy a panel from a non-editable dashboard onto an editable one.
Specifically the "Current Billable Metrics Series" panel, from the GrafanaCloud Billing/Usage dashboard:
image
https://play.grafana.org/d/vXjDa4IVk/billing-usage

I need this on my own custom dashboard which I use to manage my own spend, and share with my colleagues.

But it's impossible to copy that panel, because it's on a non-editable (ie. Provisioned) dashboard. In order to copy it I first have to click the gear ⚙️ symbol, click **Edit Dashboard**, and then I can copy it. Even this I can only do on Grafana Instances where I am an admin I think - I can't edit that dashboard on play.grafana.com, so it's impossible for me to copy that panel on that instance.

**What you expected to happen**:
Any panel that I can view I should also be able to copy, so that I can then paste that panel on a new dashboard that I am building/editing.

Ie. the **More > Copy** option should _always_ show:

image

**How to reproduce it (as minimally and precisely as possible)**:

As described above

**Anything else we need to know?**:

I think there are other options that should also always be available but aren't yet on provisioned dashboards- just take a visual diff of the screenshots I shared above. The ones I can see are:

- Copy
- Create Library Panel
- Get Help

**Environment**:
- Grafana version: v9.2.3-997144b7 (997144b79f)
- OS Grafana is installed on: GrafanaCloud
- User OS & Browser: MacOS 12.6.1 (21G217), Chrome 107.0.5304.87 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by ryantxu**
**What is this feature?**

Users in the edit role will see the copy menu item regardless of the dashboard edit status

**Why do we need this feature?**

So editors can easily copy panels

**Who is this feature for?**

Editors...

**Which issue(s) does this PR fix?**:

Fixes: https://github.com/grafana/grafana/issues/58548

### CODE REVIEW

File: public/app/features/dashboard/utils/getPanelMenu.ts [hunk 1]
```diff
@@ -206,28 +206,35 @@ export function getPanelMenu(
...
+        subMenu.push({
+          text: t('panel.header-menu.unlink-library-panel', `Unlink library panel`),
+          onClick: onUnlinkLibraryPanel,
+        });
+      } else {
+        subMenu.push({
+          text: t('panel.header-menu.create-library-panel', `Create library panel`),
+          onClick: onAddLibraryPanel,
+        });
+      }
```
Comment (ryantxu) [inline public/app/features/dashboard/utils/getPanelMenu.ts:232]: The changes above are just indentation, below is the new clause

**Review by axelavargas — APPROVED** [review]
Nice, code and adding the 'copy' option looks good to me  🥳

**Comment by samjewell** [comment]
Ah fantastic! Thanks so much for this, great change 🎉
