### PR TITLE
DashboardSettings: fixes vertical scrolling

### LINKED ISSUE #30593: Cannot scroll vertically in dashboard Settings pages (7.4.0-beta1)
**What happened**:
When viewing any of the dashboard Settings pages (including General, Variables, etc) and the extent of the content is greater than the vertical size of the window, vertical scrolling does not work properly. Tested in Chrome and Safari, with slightly different behavior:
- In Safari, the page does not scroll at all
- In Chrome, the page scrolls most of the way, but the bottom of the page cannot be brought into view. E.g. the "Delete Dashboard" button in the "General" page, or the "Update" button when editing a template variable

**What you expected to happen**:
To be able to scroll and see all the content

**How to reproduce it (as minimally and precisely as possible)**:
1. In Chrome or Safari, open a dashboard and go to the Settings page
2. Shrink the window vertically, so the content extends beyond the bottom of the window (this can also be step 1)
3. Try scrolling down

**Environment**:
- Grafana version: 7.4.0-beta1
- Data source type & version: N/A
- OS Grafana is installed on: Linux or macOS
- User OS & Browser: macOS 11.1; Chrome 88.0.4324.96 or Safari 14.0.2
- Grafana plugins: N/A

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
The 7.4.0-beta release introduced a bug which prevents users from scrolling the dashboard settings view vertically. This PR fixes the bug by putting back missing css / html elements.

https://user-images.githubusercontent.com/73201/105849510-c8bbdc80-5fe0-11eb-9611-909fc05c0091.mp4

**Which issue(s) this PR fixes**:

Fixes #30593

**Special notes for your reviewer**:
I chose to add the missing css back using emotion. A follow up PR will migrate all the dashboard settings css to use emotion. 💅

### CODE REVIEW

File: public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx [hunk 1]
```diff
@@ -142,6 +151,7 @@ export class DashboardSettings extends PureComponent<Props> {
     const currentPage = pages.find((page) => page.id === editview) ?? pages[0];
     const canSaveAs = contextSrv.hasEditPermissionInFolders;
     const canSave = dashboard.meta.canSave;
+    const styles = getStyles(config.theme);
```
Comment (dprokop) [inline public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx:154]: Not 100% but i think using the config.theme is maybe not the best idea. Since the theme in the react tree is provided via context it should be retrieved in a such way making the component independent from global variables.

As this component is a class onne, you can use [withTheme](https://github.com/grafana/grafana/blob/master/contribute/style-guides/themes.md#using-withtheme-higher-order-component-hoc) HOC or make it function componet and use [useStyles](https://github.com/grafana/grafana/blob/master/contribute/style-guides/themes.md#usestyles-hook).

**Review by dprokop — COMMENTED** [review]
@jackw left one nit that I think we should change as a matter of consistency with the majority of the theme dependencies we have.

File: public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx (hunk 1 above)
Comment (torkelo) [reply public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx:154]: think this is fine here, we use config.theme a lot in the main app components, we should move away from it but to fix this bug here I thbnk itä's fine, and we do not have to use withTheme which is messy

File: public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx [hunk 2]
```diff
@@ -154,40 +164,46 @@ export class DashboardSettings extends PureComponent<Props> {
...
-  icon: IconName;
-  render: () => React.ReactNode;
-}
+const getStyles = stylesFactory((theme: GrafanaTheme) => ({
+  scrollInner: css`
+    min-width: 100%;
+    min-height: 100%;
+  `,
+  settingsWrapper: css`
+    background: ${theme.palette.gray10};
```
Comment (torkelo) [inline public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx:204]: this cannot be right, (feels like it will break in dark or light theme depending on what you tested). Use theme.colors.bg1 or bg2),  the palette colors should almost never be used from components

**Review by torkelo — APPROVED** [review]
Looks good except for a theme variable issue that looked strange

File: public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx (hunk 1 above)
Comment (jackw) [reply public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx:154]: Thanks for the feedback Dominik. When I rip out all the dashboard settings sass in favour of emotion I'll definitely introduce `withTheme` or `useStyles`.

Comment (dprokop) [reply public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx:154]: Thanks @jackw . In case of this PR it does not really matter.

File: public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx (hunk 2 above)
Comment (jackw) [reply public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx]: Thanks @torkelo. Have swapped it out for `theme.colors.bg1`. 👍

**Review by dprokop — APPROVED** [review]
Tested and it works great.

One thing to think about in the future @lukasztyrala  when designing Grafana navigation revamp is the behavior of the dashboard settings(not sure we will redesign for 8.0) is whether or not the dashboard settings tabs should scroll with the content or not. Currently they do:

https://user-images.githubusercontent.com/2376619/105858873-1ee24d00-5fec-11eb-8a96-18751f8c30d7.mp4
