### PR TITLE
Table: Fix cell border visibility

### LINKED ISSUE #101759: Table: Colored Background Cells Overlap Row Dividers in Table Panel broken a table view (Since 11.1.0)
### What happened?

Starting from Grafana version 11.1.0, the appearance of table cells with the Colored Background type has been broken. The background color now overlaps the horizontal row dividers, causing cells to visually merge into a single vertical block. However, vertical column dividers remain visible. As a result, the table becomes difficult to read and visually unappealing.

Image

This issue appeared after Text Wrapping was introduced (#86895, @codeincarnate).
Initial investigation suggests that a calculated height parameter was added to the CSS style of each cell. 

Image

However, this calculation does not account for the 1px row divider thickness.

For example:

    If the inner cell area is 35px, the height is set to 36px, causing the overlap a row divider.
    Reducing the height by 1px resolves the issue and restores correct rendering.

Image

### What did you expect to happen?

The table should look as follows

Image

### Did this work before?

It worked in grafana 11.0.10 and has been broken in 11.1.0 since Text Wrapping was introduced (#86895, @codeincarnate)

### How do we reproduce it?

1. Create the panel with grafana-testdata-datasource, with any csv test data with 2 or more rows.
2.  Set cell type to Colored Background

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: > 11.1.0
OS: 
Browser: Chrome & Firefox last versions

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by Develer**
**What is this feature?**

This PR fixes table cell bottom border visibility in Colored background cell type situation.

Before:

Image

After:

Image

Fixes [#101759](https://github.com/grafana/grafana/issues/101759)

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by alexjonspencer1 — APPROVED** [review]
Nice, this totally works! 🏆 

Another, maybe _slightly_ less hacky, approach would be to add the style `overflow: hidden` on the row. 

In `packages/grafana-ui/src/components/Table/styles.ts`, you could do this.

```
row: css({
  label: 'row',
  borderBottom: `1px solid ${borderColor}`,
  overflow: 'hidden', ⬅️ This one here!

  '&:hover': {
    backgroundColor: theme.components.table.rowHoverBackground,
  },

  '&:last-child': {
    borderBottom: 0,
  },
}),
```

File: packages/grafana-ui/src/components/Table/RowsList.tsx [hunk 1]
```diff
@@ -351,7 +351,9 @@ export const RowsList = (props: RowsListProps) => {
               rowStyled={rowBg !== undefined}
               rowExpanded={rowExpanded}
               textWrapped={textWrapFinal !== undefined}
-              height={Number(style.height)}
+              // VariableSizeList overrides calculated in buildCellContainerStyle height of the cell,
+              // so we need to subtract 1 to respect the row border
+              height={Number(style.height) - 1}
```
Comment (alexjonspencer1) [inline packages/grafana-ui/src/components/Table/RowsList.tsx:356]: Since we're coercing `style.height` to a number here, it _might_ be a safer approach to use `parseInt` in case the string ever comes through with extra characters like "px". Not necessary, but maybe thing to think about!

` parseInt(style.height, 10)`

**Review by drew08t — APPROVED** [review]

File: packages/grafana-ui/src/components/Table/RowsList.tsx (hunk 1 above)
Comment (Develer) [reply packages/grafana-ui/src/components/Table/RowsList.tsx:356]: yeah, `parseInt` feels safer, but looks like those styles calculate based on `getItemSize`, which returns a number, and the style returns an object with numbers, so I think we are safe here. But it does not feel robust, I agree.

**Comment by sknaumov** [comment]
Could it be backported to v11.x versions? This issue is caused by commit 04c4b0d004c48d1ccbbc5424f8215809462ca4fb from #86895.
