### PR TITLE
Prometheus: Introduce failsafe PromQueryFormat unmarshalling

### LINKED ISSUE #112002: Prometheus: Type mismatch and utf8 metrics and labels
### What happened?

In Prometheus data source, there are high errors. There are two major error logs that are

```
json: cannot unmarshal number into Go struct field internalQueryModel.PrometheusQueryProperties.format of type models.PromQueryFormat 
```
I think this is related to [this line](https://github.com/grafana/grafana/blob/7f805d8e1a14666b392039aadf9a64a37e7ac679/pkg/promlib/models/query.go#L23) in Grafana. Unmarshaling number to string in that struct throws errors.

```
[plugin.requestFailureError] client: failed to query data: Failed to query data: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
```
Similar to above but utf8 for metrics and labels.

### What did you expect to happen?

Unmarshalling should not fail for those structs that threw errors. It should convert type as expected.

### Did this work before?

N/A

### How do we reproduce it?

Error logs

### Is the bug inside a dashboard panel?

You can check error logs in [this dashboard](https://ops.grafana-ops.net/d/cdsqp9biempdsca/6b3ce21?from=now-1h&to=now&var-metrics_datasource=grafanacloud-prom&var-datasource=prometheus&timezone=utc&orgId=1&var-squad=Big%20Tent&var-cluster=$__all&var-remoteAppName=prometheus-datasource-grafana-app)

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

We observed high error rates in Prometheus data source with given log:

```
json: cannot unmarshal number into Go struct field internalQueryModel.PrometheusQueryProperties.format of type models.PromQueryFormat 
```                                                                                                                                                                                                           
This occurs when clients incorrectly send numeric values (e.g., "format": 0) instead of strings (e.g., "format": "time_series") for the format field.

So with this PR we introduced a custom UnmarshalJSON method to the PromQueryFormat type that provides failsafe handling.

**Why do we need this feature?**

To prevent accidental unmarshalling issues 

Fixes: https://github.com/grafana/grafana/issues/112002

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: pkg/promlib/models/query.go [hunk 1]
```diff
@@ -33,6 +33,40 @@ const (
 	PromQueryFormatHeatmap    PromQueryFormat = "heatmap"
 )
 
+// UnmarshalJSON implements custom unmarshaling to handle both string and numeric format values.
+// This provides a failsafe to prevent unmarshaling errors when clients incorrectly send
+// numeric values instead of strings for the format field.
+func (f *PromQueryFormat) UnmarshalJSON(data []byte) error {
+	// Try to unmarshal as string first (the expected type)
```
Comment (yesoreyeram) [inline pkg/promlib/models/query.go:40]: I would go with numeric values first and then string. Also seems there is no strict validation for string format. ( potentially `timeseries` / `TIME_SERIES` might fail / panic here.

similar implementation for sql ds https://github.com/grafana/grafana-plugin-sdk-go/pull/1462/changes

Comment (itsmylife) [reply pkg/promlib/models/query.go:40]: But the default value of that field is always string. Numeric value shouldn't even be there. So checking numeric first seems waste of resource, right?

File: pkg/promlib/models/query.go [hunk 2]
```diff
@@ -33,6 +33,47 @@ const (
...
+		default:
+			// Invalid string value, fall back to default
+			*f = PromQueryFormatTimeSeries
+		}
+		return nil
+	}
+
+	// If that fails, try as number and convert to the default format
+	// This handles cases where clients incorrectly send numeric values
+	var n float64
```
Comment (yesoreyeram) [inline pkg/promlib/models/query.go]: nit. we can go with uint32 instead float64.

**Review by yesoreyeram — APPROVED** [review]

File: pkg/promlib/models/query.go (hunk 2 above)
Comment (itsmylife) [reply pkg/promlib/models/query.go]: That's correct :) I'll change it.

Comment (itsmylife) [inline pkg/promlib/models/query.go]:
```suggestion
	var n uint32
```

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/21367068514)
- Version: 12.4.0-21367068514
