### PR TITLE
Grafana-ui: Fix RadioButtonList component

### LINKED ISSUE #72729: Grafana UI: RadioButtonList component does not work as expected
### What happened?

During some work on RolePicker component (https://github.com/grafana/grafana/pull/72561) we've found that new `<RadioButtonList>` component does not work the same way as `<RadioButtonGroup>`. We use it inside a drop down menu and when you select a value, menu is closing immediately. However, correct option is passed to the onChange handler. The root cause of this behaviour is event propagation, so if I put this code to the `RadioButtonDot` component, it works correctly:

```ts
export const RadioButtonDot = ({ id, name, label, checked, disabled, description, onChange }: RadioButtonDotProps) => {
  const styles = useStyles2(getStyles);

  const handleOnChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    // This solves the issue
    e.stopPropagation();
    onChange && onChange(id);
  };

  return (
    <label title={description} className={styles.label}>
      <input
        id={id}
        name={name}
        type="radio"
        checked={checked}
        disabled={disabled}
        className={styles.input}
        onChange={handleOnChange}
      />
      {label}
    </label>
  );
};
```

I'm not 100% sure why RadioButtonList behaves differently from RadioButtonGroup since it does not have (at least I haven't found) any code that stops event propagation. So here are few questions:
1. Is it a bug and event should not be propagated?
2. If yes, why RadioButtonGroup works correctly in out case (in drop down menu)?
3. Is suggested fix correct or issue can be solved in a different way?

### What did you expect to happen?

`<RadioButtonList>` works correctly inside drop down

### Did this work before?

N/A, seems we're the first users of this component.

### How do we reproduce it?

1.
2.
3.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by alexanderzobnin**
**What is this feature?**

This PR fixes `RadioButtonList` component issue related to wrong behavior within `ClickOutsideWrapper`.

**Which issue(s) does this PR fix?**:

Fixes #72729

**Special notes for your reviewer:**

According to rules of using key in React, it should not change on rendering

> Keys must not change or that defeats their purpose! Don’t generate them while rendering.

https://react.dev/learn/rendering-lists#rules-of-keys

### CODE REVIEW

File: packages/grafana-ui/src/components/Forms/RadioButtonList/RadioButtonList.tsx [hunk 1]
```diff
@@ -48,7 +48,7 @@ export function RadioButtonList<T>({
 
         return (
           <RadioButtonDot
-            key={itemId}
+            key={`${option.label}-${index}`}
```
Comment (Clarity-89) [inline packages/grafana-ui/src/components/Forms/RadioButtonList/RadioButtonList.tsx:51]: Does the old code create some issues? We use `uniqueId` in a few other places as well.

Comment (joshhunt) [inline packages/grafana-ui/src/components/Forms/RadioButtonList/RadioButtonList.tsx:51]: I think, if we're going to include `index`, then it that's all the key should be. Including `index` _at all_ in the key is the thing that kind of breaks it, so `option.label` doesn't really do anything for us here.

Comment (Clarity-89) [reply packages/grafana-ui/src/components/Forms/RadioButtonList/RadioButtonList.tsx:51]: Was thinking the same, it doesn't look like the components in the list will be dynamically removed or added and the key should be unique only in the scope of the parent component, so `index` would probably work here.

Comment (alexanderzobnin) [reply packages/grafana-ui/src/components/Forms/RadioButtonList/RadioButtonList.tsx:51]: Yes, see my comment in the corresponding issue https://github.com/grafana/grafana/issues/72729#issuecomment-1663582705
In general, it causes list element re-render and detaches it from DOM. So ClickOutsideWrapper cannot find it anymore and calls onClick() handler (which usually used to close menu, modal, etc).

Comment (alexanderzobnin) [reply packages/grafana-ui/src/components/Forms/RadioButtonList/RadioButtonList.tsx:51]: yes, agreed, that does not change anything actually

**Review by Clarity-89 — APPROVED** [review]
