### PR TITLE
Table: Adds adhoc filtering

### LINKED ISSUE #25072: Table: Add ad-hoc filters support to new table panel
**What happened**:
Can't use the filter feature in table panel

**What you expected to happen**:
image

**How to reproduce it (as minimally and precisely as possible)**:
Create a table with elasticsearch datasource.

**Anything else we need to know?**:
Feature work if I import old dashboards. I can see panel json config : "type": "table-old"

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: elasticsearch
- OS Grafana is installed on: docker ubuntu official image

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR adds ad hoc filtering to the new React Table component.

**Which issue(s) this PR fixes**:
Fixes #25072

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/panel/table/TablePanel.tsx [hunk 1]
```diff
@@ -62,6 +65,20 @@ export class TablePanel extends Component<Props> {
...
+    const panelModel = getDashboardSrv()
+      .getCurrent()
+      .getPanelById(this.props.id);
+    const datasource = panelModel?.datasource;
+
+    if (!datasource) {
+      return;
+    }
+
+    dispatch(applyFilterFromTable({ datasource, key, operator, value }));
```
Comment (hugohaggmark) [inline public/app/plugins/panel/table/TablePanel.tsx:79]: Not super happy with this, maybe we should introduce a prop on PanelProps that allows plugins to dispatch actions/events?

File: packages/grafana-ui/src/components/Table/TableCell.tsx [hunk 2]
```diff
@@ -1,38 +1,59 @@
...
+  if (filterable && onFilterAdded) {
+    return (
+      <FilterableTableCell
+        cell={cell}
+        field={field}
+        tableStyles={tableStyles}
+        onFilterAdded={onFilterAdded}
+        cellProps={cellProps}
+      />
+    );
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/Table/TableCell.tsx:48]: Would love to get feedback on this refactor 🙏

Comment (dprokop) [reply packages/grafana-ui/src/components/Table/TableCell.tsx:48]: This sort of relates to my previous comment on how we enable the filtering callback. Since we want to inject domain-specific props to the table cell I think we would have to introduce a render prop for the cell. Then not sure we have/will have a case for filterable prop in near time feature, hence introducing this additional prop feels like introducing unnecessary complexity. WDYT?

File: packages/grafana-ui/src/components/Table/Table.tsx [hunk 3]
```diff
@@ -36,9 +37,10 @@ export interface Props {
   noHeader?: boolean;
   resizable?: boolean;
   initialSortBy?: TableSortByFieldState[];
-  onCellClick?: TableFilterActionCallback;
+  onCellClick?: TableCellClickActionCallback;
   onColumnResize?: TableColumnResizeActionCallback;
   onSortByChange?: TableSortByActionCallback;
+  onFilterAdded?: TableFilterActionCallback;
```
Comment (dprokop) [inline packages/grafana-ui/src/components/Table/Table.tsx:43]: This feels a bit too domain-specific as for a generic table component

Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Table/Table.tsx:43]: Not sure what the solution would be otherwise? Maybe we could sync on this or maybe you could elaborate further?

File: packages/grafana-ui/src/components/Table/TableCell.tsx [hunk 4]
```diff
@@ -1,38 +1,59 @@
...
-    onClick = () => onCellClick(cell.column.Header as string, cell.value);
+    return (
+      <ClickableTableCell
+        cell={cell}
+        field={field}
+        tableStyles={tableStyles}
+        onCellClick={onCellClick}
+        cellProps={cellProps}
+      />
+    );
```
Comment (torkelo) [inline packages/grafana-ui/src/components/Table/TableCell.tsx:36]: I do not think we need this clickable cell and callback anymore, this was just done as simple version of ad-hoc filters, Explore table should use the onFilterAdded callback instead

File: packages/grafana-ui/src/components/Table/TableCell.tsx (hunk 2 above)
Comment (torkelo) [reply packages/grafana-ui/src/components/Table/TableCell.tsx:48]: not sure what the best solution is, we need this in Explore as well. filterable is a field.config property. think a prop for this on Table is ok. wonder if we should name the callback a bit differently, like onCellFilterAdded , as I think we will add filters on columns as well in the future (think filters in excel on the headers), to filter values in a table in the table component it'self.

File: packages/grafana-ui/src/components/Table/TableCell.tsx (hunk 4 above)
Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Table/TableCell.tsx:36]: Gotcha, but this means that Explore also would need to implement both `filter for` and `filter out` functionality.

File: public/app/plugins/panel/table/TablePanel.tsx (hunk 1 above)
Comment (torkelo) [reply public/app/plugins/panel/table/TablePanel.tsx:79]: question is what kind of actions/events? My thinking was to have an event bus on panel props, so panels can subscribe to and listen to events, ala https://github.com/grafana/grafana/pull/21010 
need to pick that PR up again. Got stuck on the event bus design and how to migrate or make it compatible with the panel events & app events (so we do not have two event systems).

Comment (hugohaggmark) [reply public/app/plugins/panel/table/TablePanel.tsx:79]: Ah yes, I remembered that one. Then I will just leave this as is for now.

File: packages/grafana-ui/src/components/Table/TableCell.tsx (hunk 2 above)
Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Table/TableCell.tsx:48]: I like this suggestion; it makes the api clearer.

**Comment by hugohaggmark** [comment]
@dprokop @torkelo renamed prop to `onCellFilterAdded` and removed the clickable cell. Also, I added the changes to Explore.

File: packages/grafana-ui/src/components/Table/TableCell.tsx (hunk 4 above)
Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Table/TableCell.tsx]: Made changes to Explore to accommodate this new api. Please have a look at changes @kaydelaney @aocenas 🙏

File: packages/grafana-ui/src/components/Table/TableCell.tsx (hunk 2 above)
Comment (dprokop) [reply packages/grafana-ui/src/components/Table/TableCell.tsx]: Yeah, I like the suggestion as well. Think as long as the props are all optional this makes sense.

**Review by aocenas — COMMENTED** [review]
Code looks good but did not test. Let me know if you need some testing for this.

**Comment by torkelo** [comment]
took this for a spin, works great! awesome!  I changed tooltip position to top so that the first icon (filter for value) tooltip did no cover the right (filter out) icon

**Review by torkelo — APPROVED** [review]

**Comment by hugohaggmark** [comment]
> took this for a spin, works great! awesome! I changed tooltip position to top so that the first icon (filter for value) tooltip did no cover the right (filter out) icon

Great catch!
