### PR TITLE
Dashboard: Fix multi-value variables in share links (#33216)

### LINKED ISSUE #33216: Render and share link contains only one item of a multiselect variable
Hi everyone,

we have the issue, that not all selected variable items are in the share and render link. Only one item seems to be added.

**How to reproduce it (as minimally and precisely as possible)**:
- create a variable with multiselect
- create a graph with a query that contains this variable
- select 2 or more items in the variable
- click share on that graph
Then we only have one variable item is in this links

Link to dashboard is:
https://grafana.domain.de/d/cLUhzjXGz/1043046?orgId=22&var-query0=it-es-data07&var-query0=it-es-data09
Render Link on the graph is:
https://grafana.domain.de/render/d-solo/cLUhzjXGz/1043046?orgId=22&var-query0=it-es-data09&from=1618990114371&to=1619011714371&panelId=2&width=1000&height=500&tz=Europe%2FBerlin

**Environment**:
- Grafana version: 7.5.2
- Data source type & version: Influx and Graphite
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Ubuntu 20.04 & Firefox 85
- Grafana plugins: -

Best regards,
Patrick

### PR DESCRIPTION
**Pull request by MrSummat**
**What this PR does / why we need it**:
Currently, the share-link generation only takes into account one value of a multi-value variable if several are selected. The source of the problem is that, since all of the values belong to the same variable, they share the same key in the variable dictionary and override each other.

This PR changes the variable dictionary so it contains lists of values to solve that issue.

**Which issue(s) this PR fixes**:

Fixes #33216

**Special notes for your reviewer**:

A working deployment of this version may be found in this [link](https://monit-grafana-open.cern.ch/d/000000759/fts-transfers?orgId=16).

### CODE REVIEW

File: packages/grafana-data/src/utils/url.ts [hunk 1]
```diff
@@ -116,7 +116,11 @@ function getUrlSearchParams() {
       // key-value param
       const key = decodeURIComponent(keyValuePair[0]);
       const value = decodeURIComponent(keyValuePair[1]);
-      params[key] = value;
+      if (key in params) {
+        params[key].push(value);
+      } else {
+        params[key] = [value];
+      }
```
Comment (hugohaggmark) [inline packages/grafana-data/src/utils/url.ts:123]: Looks, good can we add tests for this? Thank you.

Comment (hugohaggmark) [reply packages/grafana-data/src/utils/url.ts:123]: It would be great if we could specify the return value for this function, should be `UrlQueryMap`. Also, the line 112 should be:
`const params: UrlQueryMap = {};` instead of `any`.

**Review by hugohaggmark — COMMENTED** [review]
Looks good and works as expected 🎉  There should be a unit test for this before merging though.

File: packages/grafana-data/src/utils/url.ts (hunk 1 above)
Comment (MrSummat) [reply packages/grafana-data/src/utils/url.ts:123]: Hi, thanks for reviewing! The tests are on their way, but I have a couple of concerns:

- I totally agree with specifying that the method returns a UrlQueryMap, but do we want params to be one too? Effectively it is going to comply with the type, but since here it is always going to be an array (as long as it is not a boolean), we avoid having to cast. If you'd rather have it as a UrlQueryMap then we would need to change line 120 to something like `params[key] = [...params[key] as any[], value];`. Whichever you prefer :)

- How much do we care about manually modified URLs? I believe the ones generated by Grafana are always going to work with the above code, but I can think of some manually written ones that could break it, like:
  - Defining a key-value parameter as a boolean parameter before it would cause it to break since true is not iterable.
  - Defining a key-value parameter as a boolean parameter after it would override all the previous values with true.

- A "solution" for the two problems above could be to change line 122 to `params[key] = [true];`. That would avoid any exceptions but, honestly, since the input is invalid I would rather throw one or validate the input in some other way if this issue is a concern.

Comment (hugohaggmark) [reply packages/grafana-data/src/utils/url.ts:123]: > Hi, thanks for reviewing! The tests are on their way, but I have a couple of concerns:
> 
> * I totally agree with specifying that the method returns a UrlQueryMap, but do we want params to be one too? Effectively it is going to comply with the type, but since here it is always going to be an array (as long as it is not a boolean), we avoid having to cast. If you'd rather have it as a UrlQueryMap then we would need to change line 120 to something like `params[key] = [...params[key] as any[], value];`. Whichever you prefer :)

Good points, I think we're avoiding `any` as much as possible because it leads to unclear types and code so I rather have the `unnecessary` casting and make baby steps into something clearer.

> * How much do we care about manually modified URLs? I believe the ones generated by Grafana are always going to work with the above code, but I can think of some manually written ones that could break it, like:
>   
>   * Defining a key-value parameter as a boolean parameter before it would cause it to break since true is not iterable.
>   * Defining a key-value parameter as a boolean parameter after it would override all the previous values with true.
> * A "solution" for the two problems above could be to change line 122 to `params[key] = [true];`. That would avoid any exceptions but, honestly, since the input is invalid I would rather throw one or validate the input in some other way if this issue is a concern.

I agree, let's keep the boolean as is for now and we can change that moving forward.

**Comment by hugohaggmark** [comment]
Hi again @MrSummat, we're almost ready to release Grafana v8-beta3 and it would be outstanding to include this fix. If you need any help fixing the last comments I'd be glad to help out. Thank you!

**Comment by MrSummat** [comment]
Hi @hugohaggmark, sorry for the lateness, it's been quite a hectic week. I will wrap up the tests now and let you know if I have any doubt, but you can expect them today for sure.

**Review by hugohaggmark — APPROVED** [review]
Thank you for contributing, looks good and works as expected 🎉
