### PR TITLE
Tempo: Fix instant query streaming

### LINKED ISSUE #108783: Product Area: Short description of bug TraceQL metrics instant query with streaming shows range-query results
### What happened?

When using Tempo TraceQL metrics queries in Explore, the results shows a range rather than instant query result.

Image

### What did you expect to happen?

Without streaming enabled on the data source, the same query shows an instant value. Not that Tempo instant queries always return a single instant value.

Image

### Did this work before?

No/Unknown

### How do we reproduce it?

1. Enable streaming for TraceQL metrics in the Tempo data source.
2. Perform a TraceQL metrics query for the data source in Explore, such as `{} | count_over_time()`.
3. In the Search options, select the type: Instant.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Grafana Cloud instant (12.2.0-16545419697)
OS: macOS
Browser: Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Tempo

### PR DESCRIPTION
**Pull request by adrapereira**
**What is this feature?**

When streaming is enabled on the Tempo datasource and we attempt to run an instant metrics query, the datasource will always run a range metrics query instead. This PR fixes that bug by adding support for streaming instant metric queries in the Tempo datasource backend. 

Additionally it disables streaming when the query is performed by alerting, to avoid partial results from being interpreted as full results. 

**Who is this feature for?**

Users of the Tempo datasource.

**Which issue(s) does this PR fix?**:

Fixes #108783 
Fixes #106368 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/datasource/tempo/datasource.ts [hunk 1]
```diff
@@ -393,14 +394,19 @@ export class TempoDatasource extends DataSourceWithBackend<TempoQuery, TempoJson
           subQueries.push(this.handleTraceIdQuery(options, targets.traceql, queryValue));
         } else {
           if (this.isTraceQlMetricsQuery(queryValue)) {
+            const useStreaming =
```
Comment (ifrost) [inline public/app/plugins/datasource/tempo/datasource.ts:397]: Should we also do it in backend to cover the actual alerting queries execute in the background.

We could check for "FromAlert" header like in https://github.com/grafana/grafana/blob/main/pkg/tsdb/azuremonitor/azuremonitor.go#L206

**Review by ifrost — APPROVED** [review]

File: public/app/plugins/datasource/tempo/datasource.ts (hunk 1 above)
Comment (ifrost) [reply public/app/plugins/datasource/tempo/datasource.ts:397]: nvm, Alerting never uses streaming anyway
