### PR TITLE
SQLStore: Fix PostgreSQL failure to create organisation for first time

### LINKED ISSUE #18628: First attempt of creating an organization fails with PostgreSQL database
**What happened**:
First attempt of creating an organization fails with PostgreSQL database. Once it fails, the next requests succeed. This Bug happens in both GUI and HTTP API.
**What you expected to happen**:
Create an organization on first attempt.
**How to reproduce it (as minimally and precisely as possible)**:
* Run `docker-compose up` with the following configuration:
```yml
version: "2.1"

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=grafana
      - POSTGRES_PASSWORD=grafana
      - POSTGRES_DB=grafana
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grafana"]
      interval: 10s
      timeout: 5s
      retries: 5
  grafana:
    image: grafana/grafana:6.3.3
    environment:
      - GF_SERVER_HTTP_PORT=4000
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgres
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=grafana
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_SSL_MODE=disable
    ports:
      - 4000:4000
    depends_on:
      postgres:
        condition: service_healthy
```
* Try to create a new organization: 
  * First attempt will fail but the second will succeed
  * GUI: http://localhost:4000/org/new
  * HTTP API: 
    ```sh
    curl --user admin:admin -X POST -v -H "Content-Type: application/json" -H "Accept: application/json" -d '{"name": "test-org"}' http://localhost:3000/api/orgs
    ```

**Anything else we need to know?**:
Without database or using MySQL works as expected.
**Environment**: 
- Grafana version: 6.3.3
- Data source type & version: PostgreSQL 9.6, 12
- OS Grafana is installed on: [Docker container](https://hub.docker.com/r/grafana/grafana/)
- User OS & Browser:Ubuntu 18.04, Firefox 68.0.2
- Grafana plugins: No
- Others: No

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
Grafana [explicitly sets](https://github.com/grafana/grafana/blob/421e83f7c45de0baf0c470bbb001fdfb1c10eacb/pkg/services/sqlstore/org.go#L236) the org id when creates the main organisation.  However, this does not work nicely with PostgresSQL because it seems that the primary key sequence is only evaluated when the id field is not set. This fix adds a hook for syncing the sequence for the org table after inserts. 

**Which issue(s) this PR fixes**:

Fixes #18628

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/sqlstore/migrator/postgres_dialect.go [hunk 1]
```diff
@@ -155,3 +155,15 @@ func (db *Postgres) IsUniqueConstraintViolation(err error) bool {
...
 }
+
+func (db *Postgres) PostInsertId(table string, sess *xorm.Session) error {
+	if table != "org" {
+		return nil
+	}
+
+	// sync primary key sequence of org table
+	if _, err := sess.Exec("SELECT setval('org_id_seq', (SELECT max(id)+1 FROM org));"); err != nil {
+		return fmt.Errorf("Failed to sync primary key for org table")
```
Comment (kylebrandt) [inline pkg/services/sqlstore/migrator/postgres_dialect.go]: This seems to follow the error pattern in the file, but I wonder:
 1. Why not return the error if an error?
 2. Regardless of what is done with the error, should the contents of sess.Exec's err be wrapped into the message so the reason is logged?

Comment (papagian) [reply pkg/services/sqlstore/migrator/postgres_dialect.go]: good points, I will fix it!

Comment (aknuds1) [reply pkg/services/sqlstore/migrator/postgres_dialect.go]: Yeah, wrapping the error sounds like the thing to do for me as well :)

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Looks good AFAICT, apart from the error that should get wrapped.

File: pkg/services/sqlstore/migrator/postgres_dialect.go [hunk 2]
```diff
@@ -162,8 +162,8 @@ func (db *Postgres) PostInsertId(table string, sess *xorm.Session) error {
 	}
 
 	// sync primary key sequence of org table
-	if _, err := sess.Exec("SELECT setval('org_id_seq', (SELECT max(id)+1 FROM org));"); err != nil {
-		return fmt.Errorf("Failed to sync primary key for org table")
+	if _, err := sess.Exec("SELECT setval('org_id_seq', (SELECT max(id) FROM org));"); err != nil {
+		return fmt.Errorf("Failed to sync primary key for org table: %v", err)
```
Comment (aknuds1) [inline pkg/services/sqlstore/migrator/postgres_dialect.go]: I should've mentioned this before, but we use an error wrapping utility in Grafana:

```suggestion
		return errutil.Wrapf(err, "failed to sync primary key for org table")
```

I think the norm in Go (and Grafana?) is also to start errors with lowercase first letter, since they are often combined and don't form the whole message if you see what I mean.

**Review by aknuds1 — CHANGES_REQUESTED** [review]

**Review by aknuds1 — APPROVED** [review]
LGTM!
