### PR TITLE
TimeSeriesPanel: Fix overlapping time axis ticks

### LINKED ISSUE #30906: Time Series panel: Time labels overlap
**What happened**:
In certain circumstances time labels in time series panel overlap. It is caused by "too frequent labeling"
Time range is set to last 7 days. Here is how Time Series panel looks:
image
This is how old Graph panel looks:
image

As you can see, in this example, on time series panel time is labelled every 6 hours, whereas on graph panel time is labelled every 8 hours.

**What you expected to happen**:
It should be labelled the same as on graph panel (once every 8 hours in this example)

**How to reproduce it (as minimally and precisely as possible)**:
Create panel which takes full width of the page and then select last 7 days range. I was testing in on FullHD (1920 x 1080) monitor.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: Influxdb 1.8.2
- OS Grafana is installed on: Debian 4.9
- User OS & Browser: Windows 10 Opera Gx
- Grafana plugins: -
- Others: -

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #30906

* [x] Adds measuring a sample tick to know how wide a time tick could be 
* [x] Improves formatting logic 
* [x] Adds improved formatting when time ticks round to even years 
* [x] Adds test dashboard for time axis

### CODE REVIEW

File: packages/grafana-ui/src/components/uPlot/config/UPlotAxisBuilder.ts [hunk 1]
```diff
@@ -129,29 +140,38 @@ function calculateAxisSize(self: uPlot, values: string[], axisIdx: number) {
   return measureText(maxLength, 12).width + 18;
 }
 
+const timeUnitSize = {
+  second: 1000,
+  minute: 60 * 1000,
+  hour: 60 * 60 * 1000,
+  day: 24 * 60 * 60 * 1000,
+  month: 30 * 24 * 60 * 60 * 1000,
+  year: 365.2425 * 24 * 60 * 60 * 1000,
```
Comment (leeoniya) [inline packages/grafana-ui/src/components/uPlot/config/UPlotAxisBuilder.ts:149]: i think a unix timestamp year is exactly 365.

```js
new Date("1971-01-01")/1000/3600/24 === 365
```

File: packages/grafana-ui/src/components/uPlot/config/UPlotAxisBuilder.ts [hunk 2]
```diff
@@ -129,29 +140,38 @@ function calculateAxisSize(self: uPlot, values: string[], axisIdx: number) {
   return measureText(maxLength, 12).width + 18;
 }
 
+const timeUnitSize = {
+  second: 1000,
+  minute: 60 * 1000,
+  hour: 60 * 60 * 1000,
+  day: 24 * 60 * 60 * 1000,
+  month: 30 * 24 * 60 * 60 * 1000,
```
Comment (leeoniya) [inline packages/grafana-ui/src/components/uPlot/config/UPlotAxisBuilder.ts:148]: i typically use 28 days to account for Feb and leap years

**Review by leeoniya — APPROVED** [review]
