### PR TITLE
Rich history: Fix create url and run query for various datasources

### LINKED ISSUE #23022: Rich History: Data source select width bug
Not sure if the width should have a limit here, and that what causes it. Can someone else reproduce this?
Screenshot from 2020-03-24 12-13-47

### LINKED ISSUE #23863: Tracing and Query history UI overlap
**What happened**:

image

I had the query history open and I jump to a trace and got this.

**What you expected to happen**:

Close the query history or give it a higher z-index ? not sure you tell me :)

**How to reproduce it (as minimally and precisely as possible)**:

Open query history than go to a trace.

**Environment**:
- Grafana version: Grafana v7.0.0-2f89b534pre (1955c3911b)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

/cc @aocenas

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
1. Store DataQuery in LocalStorage instead of string
2. Fix create url & run query for all datasources (except Loki and Prometheus where there was no problem)
3. CSS updates - remove theme.palette and replace with theme.colors (where possible)
4. Update Legacy Select component to the new one (fixes #23022)

**Which issue(s) this PR fixes**:
Fixes #23022 
Fixes https://github.com/grafana/grafana/issues/23863

### CODE REVIEW

File: packages/grafana-data/src/types/datasource.ts [hunk 1]
```diff
@@ -218,6 +218,11 @@ export abstract class DataSourceApi<
    */
   getQueryDisplayText?(query: TQuery): string;
 
+  /**
+   * Convert a simple text string to query
+   */
+  getQueryFromDisplayText?(query: string): any;
+
   /**
```
Comment (ivanahuckova) [inline packages/grafana-data/src/types/datasource.ts:226]: Datasources, that implement `getQueryDisplayText` method should implement `getQueryFromDisplayText` as well. This way we can translate query text to query.

File: public/app/core/utils/richHistory.test.ts [hunk 2]
```diff
@@ -179,6 +179,7 @@ describe('createQueryHeading', () => {
 describe('createDataQuery', () => {
   it('should correctly create data query from rich history query', () => {
     const dataQuery = createDataQuery(mock.history[0], mock.queries[0], 0);
+    console.log(dataQuery);
```
Comment (ivanahuckova) [inline public/app/core/utils/richHistory.test.ts:182]:
```suggestion
```

File: public/app/core/utils/richHistory.ts [hunk 3]
```diff
@@ -153,15 +152,27 @@ export const copyStringToClipboard = (string: string) => {
   document.body.removeChild(el);
 };
 
-export const createUrlFromRichHistory = (query: RichHistoryQuery) => {
-  const queries = query.queries.map(query => ({ expr: query }));
+export const createUrlFromRichHistory = (query: RichHistoryQuery, getQueryFromDisplayText?: (q: string) => {}) => {
```
Comment (ivanahuckova) [inline public/app/core/utils/richHistory.ts:155]: If `getQueryFromDisplayText` passed, use it to create url. Otherwise just parse queryString.

File: public/app/core/utils/richHistory.ts [hunk 4]
```diff
@@ -238,14 +250,21 @@ export function isParsable(string: string) {
   return true;
 }
 
-export function createDataQuery(query: RichHistoryQuery, queryString: string, index: number) {
+export function createDataQuery(
```
Comment (ivanahuckova) [inline public/app/core/utils/richHistory.ts:253]: Same as with createUrl, if getQueryFromDisplayText passed, use it to create url. Otherwise just parse queryString.

File: public/app/features/explore/RichHistory/RichHistory.tsx [hunk 5]
```diff
@@ -24,8 +24,8 @@ export enum Tabs {
 }
 
 export const sortOrderOptions = [
-  { label: 'Time ascending', value: SortOrder.Ascending },
```
Comment (ivanahuckova) [inline public/app/features/explore/RichHistory/RichHistory.tsx:27]: Based on suggestion at UX feedback session, using Newest first and Oldest first is more clear.

File: public/app/features/explore/RichHistory/RichHistoryQueriesTab.tsx [hunk 6]
```diff
@@ -141,9 +140,10 @@ export function RichHistoryQueriesTab(props: Props) {
   const listOfDatasources = createDatasourcesList(datasourcesRetrievedFromQueryHistory);
 
   const listOfDatasourceFilters = datasourceFilters?.map(d => d.value);
-  const filteredQueriesByDatasource = datasourceFilters
-    ? queries?.filter(q => listOfDatasourceFilters?.includes(q.datasourceName))
-    : queries;
```
Comment (ivanahuckova) [inline public/app/features/explore/RichHistory/RichHistoryQueriesTab.tsx:146]: Updated as new Select for empty selected list uses [] instead of null (which was used by LegacySelect)

File: public/app/features/explore/RichHistory/RichHistoryStarredTab.tsx [hunk 7]
```diff
@@ -87,9 +86,10 @@ export function RichHistoryStarredTab(props: Props) {
   const listOfDatasourceFilters = datasourceFilters?.map(d => d.value);
 
   const starredQueries = queries.filter(q => q.starred === true);
-  const starredQueriesFilteredByDatasource = datasourceFilters
-    ? starredQueries?.filter(q => listOfDatasourceFilters?.includes(q.datasourceName))
-    : starredQueries;
```
Comment (ivanahuckova) [inline public/app/features/explore/RichHistory/RichHistoryStarredTab.tsx:92]: Updated as new Select for empty selected list uses [] instead of null (which was used by LegacySelect)

**Review by Estrax — APPROVED** [review]

**Comment by ivanahuckova** [comment]
@aocenas As we have spoken, I have updated richHistory so full queries are saved and display text is used for visualisation purposes.

File: public/app/features/explore/RichHistory/RichHistoryCard.tsx [hunk 8]
```diff
@@ -147,28 +151,37 @@ export function RichHistoryCard(props: Props) {
   } = props;
   const [activeUpdateComment, setActiveUpdateComment] = useState(false);
   const [comment, setComment] = useState<string | undefined>(query.comment);
+  const [queryDsInstance, setQueryDsInstance] = useState<DataSourceApi | undefined>(undefined);
+
+  useEffect(() => {
+    getQueryDsInstance();
+  });
```
Comment (aocenas) [inline public/app/features/explore/RichHistory/RichHistoryCard.tsx:158]: This feels a bit wrong. Do we really want to run this on every render? Seems like this should actually create a infinite render loop. Maybe we should just run it if `query.datasourceName` changes.

File: public/app/features/explore/RichHistory/RichHistoryCard.tsx [hunk 9]
```diff
@@ -243,9 +258,10 @@ export function RichHistoryCard(props: Props) {
       <div className={cx(styles.cardRow)}>
         <div className={styles.queryContainer}>
           {query.queries.map((q, i) => {
+            const queryText = createQueryText(q, queryDsInstance);
             return (
               <div aria-label="Query text" key={`${q}-${i}`} className={styles.queryRow}>
-                {q}
+                {queryText.length > 0 && queryText}
```
Comment (aocenas) [inline public/app/features/explore/RichHistory/RichHistoryCard.tsx:264]: If `queryText` is empty string we render false here which ends up as nothing right? is that different from just rendering empty text?

File: public/app/features/explore/RichHistory/RichHistoryCard.tsx [hunk 10]
```diff
@@ -147,28 +151,37 @@ export function RichHistoryCard(props: Props) {
...
   const onCopyQuery = () => {
-    const queries = query.queries.join('\n\n');
-    copyStringToClipboard(queries);
+    const queriesToCopy = query.queries.map(q => createQueryText(q, queryDsInstance)).join('\n');
+    copyStringToClipboard(queriesToCopy);
     appEvents.emit(AppEvents.alertSuccess, ['Query copied to clipboard']);
   };
 
-  const onCreateLink = () => {
+  const onCreateLink = async () => {
```
Comment (aocenas) [inline public/app/features/explore/RichHistory/RichHistoryCard.tsx:184]: Does this need to be async? Or is this missing `await` somewhere?

File: public/app/core/utils/richHistory.ts [hunk 11]
```diff
@@ -252,16 +269,29 @@ export function isParsable(string: string) {
...
 
-export function createDataQuery(query: RichHistoryQuery, queryString: string, index: number) {
-  let dataQuery;
+export function createDataQuery(query: RichHistoryQuery, individualQuery: DataQuery, index: number) {
   const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
-  isParsable(queryString)
-    ? (dataQuery = JSON.parse(queryString))
-    : (dataQuery = { expr: queryString, refId: letters[index], datasource: query.datasourceName });
+  let dataQuery;
+  typeof individualQuery === 'object'
```
[the remark this answers is not in the document]
Comment (aocenas) [reply public/app/core/utils/richHistory.ts:275]: Also btw the usage of `?:` is a bit weird here could be simplified to:
```
return typeof individualQuery === 'object' ? individualQuery : { expr: individualQuery, refId: letters[index] }
```

File: public/app/types/explore.ts [hunk 12]
```diff
@@ -241,7 +241,7 @@ export type RichHistoryQuery = {
   datasourceId: string;
   starred: boolean;
   comment: string;
-  queries: string[];
+  queries: DataQuery[];
```
Comment (aocenas) [inline public/app/types/explore.ts:244]: Also here it is probably more correct to say this is `(DataQuery | string)[]` I assume that may ripple out a bit and we will need to check what it really is but we already need to do that.

File: public/app/core/utils/richHistory.ts [hunk 13]
```diff
@@ -304,3 +334,17 @@ export function createDatasourcesList(queriesDatasources: string[]) {
   });
   return datasources;
 }
+
+export function notEmptyQuery(query: DataQuery) {
```
Comment (aocenas) [inline public/app/core/utils/richHistory.ts:338]: I think in the same way we will need to handle the case query is still a string.

**Review by aocenas — COMMENTED** [review]
Considering the issue with DataQuery vs string due to old versions of the RichHistory in memory I think it may be easier to just run some conversion at the application start. Something that would take the RichHistory, go through all queries, convert to object and then all the code does not have to handle the legacy version. I know I am bit late with the feedback so I will leave that to you what seems to make the most sense at the moment.

File: public/app/features/explore/RichHistory/RichHistoryCard.tsx (hunk 8 above)
Comment (ivanahuckova) [reply public/app/features/explore/RichHistory/RichHistoryCard.tsx:158]: Yeah, good catch! It should run only on first render, as `query.datasourceName` never changes. I'll add `,[]`.

File: public/app/core/utils/richHistory.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (ivanahuckova) [reply public/app/core/utils/richHistory.ts]: ✅ removed as after update, we only receive DataQuery. So it is not necessary anymore.

File: public/app/core/utils/richHistory.ts [hunk 14]
```diff
@@ -252,16 +269,29 @@ export function isParsable(string: string) {
...
+    : (dataQuery = { expr: individualQuery, refId: letters[index] });
 
   return dataQuery;
 }
 
+export function createQueryText(query: DataQuery, queryDsInstance: DataSourceApi) {
+  /* query DatasourceInstance is necessary because we use its getQueryDisplayText method
+   * to format query text
+   */
+  if (typeof query === 'object') {
```
[the remark this answers is not in the document]
Comment (ivanahuckova) [reply public/app/core/utils/richHistory.ts]: ✅ removed as after update, we only receive DataQuery. So it is not necessary anymore.

File: public/app/features/explore/RichHistory/RichHistoryCard.tsx (hunk 9 above)
Comment (ivanahuckova) [reply public/app/features/explore/RichHistory/RichHistoryCard.tsx]: true, removed.

File: public/app/features/explore/RichHistory/RichHistoryCard.tsx (hunk 10 above)
Comment (ivanahuckova) [reply public/app/features/explore/RichHistory/RichHistoryCard.tsx]: Yeah, async is redundant, I accidentally left it there. Good catch.

File: public/app/types/explore.ts (hunk 12 above)
Comment (ivanahuckova) [reply public/app/types/explore.ts:244]: ✅ it is correct, as we now only receive DataQuery, no strings.

**Comment by ivanahuckova** [comment]
@aocenas based on your feedback and our talk, I have created a function that transforms all string queries to DataQueries. It is in `getRichHistory()` which is run in `initializeExplore`. When new query is run, this transformed history is saved and we don't need to deal with strings anymore.

File: public/app/features/explore/RichHistory/RichHistoryCard.tsx [hunk 15]
```diff
@@ -147,24 +146,33 @@ export function RichHistoryCard(props: Props) {
   } = props;
   const [activeUpdateComment, setActiveUpdateComment] = useState(false);
   const [comment, setComment] = useState<string | undefined>(query.comment);
+  const [queryDsInstance, setQueryDsInstance] = useState<DataSourceApi | undefined>(undefined);
+
+  useEffect(() => {
+    getQueryDsInstance();
+  }, []);
```
Comment (aocenas) [inline public/app/features/explore/RichHistory/RichHistoryCard.tsx:153]: I think the deps should be `[query.datasourceName]` to run if query and datasource changes. If we do add keys to the cards in the list then changing the queries will just update the props and not unmount/mount new card.

File: public/app/core/utils/richHistory.ts [hunk 16]
```diff
@@ -304,3 +312,46 @@ export function createDatasourcesList(queriesDatasources: string[]) {
...
+
+  if (queryKeys.length > 0) {
+    return true;
+  }
+
+  return false;
+}
+
+/* These functions are created to migrate string queries (from 6.7 release) to DataQueries. They can be removed after 7.1 release. */
+function createDataQueriesRichHistory(richHistory: RichHistoryQuery[]) {
```
Comment (aocenas) [inline public/app/core/utils/richHistory.ts:331]: I would probably call this `migrateRichHistory` or something in that lines to be clear what is going on.

**Review by aocenas — APPROVED** [review]
2 small comments, after addressing that this can be merged.

File: public/app/features/explore/RichHistory/RichHistoryCard.tsx (hunk 15 above)
Comment (ivanahuckova) [reply public/app/features/explore/RichHistory/RichHistoryCard.tsx]: updated in https://github.com/grafana/grafana/pull/23627/commits/597b0a497c8a475ae9e872ea397f7dd8314bfdef

File: public/app/core/utils/richHistory.ts (hunk 16 above)
Comment (ivanahuckova) [reply public/app/core/utils/richHistory.ts]: updated in https://github.com/grafana/grafana/pull/23627/commits/597b0a497c8a475ae9e872ea397f7dd8314bfdef
