### PR TITLE
XY Chart: share legend config with timeseries

### LINKED ISSUE #30551: XY Chart: Error "outerJoinValues lost a field?"
**What happened**:
Error trying to use XY chart.

**How to reproduce it (as minimally and precisely as possible)**:

image

or easier:

```
QVJST1cxAAD/////8AEAABAAAAAAAAoADgAMAAsABAAKAAAAFAAAAAAAAAEDAAoADAAAAAgABAAKAAAACAAAAOwAAAADAAAATAAAACgAAAAEAAAAmP7//wgAAAAMAAAAAQAAAEEAAAAFAAAAcmVmSWQAAAC4/v//CAAAAAwAAAAAAAAAAAAAAAQAAABuYW1lAAAAANj+//8IAAAAhAAAAHsAAAB7ImN1c3RvbSI6eyJDb2x1bW5UeXBlcyI6WyJyZWFsIiwicmVhbCJdfSwiZXhlY3V0ZWRRdWVyeVN0cmluZyI6ImRhdGF0YWJsZSAoYTpyZWFsLCBiOnJlYWwpIFtcbiAgICAxLCAxMDQwLFxuICAgIDIsIDIsXG5dIn0ABAAAAG1ldGEAAAAAAgAAAGwAAAAEAAAArv///xQAAAA4AAAAOAAAAAAAAwE4AAAAAQAAAAQAAACc////CAAAAAwAAAABAAAAYgAAAAQAAABuYW1lAAAAAAAAAACS////AAACAAEAAABiABIAGAAUABMAEgAMAAAACAAEABIAAAAUAAAAQAAAAEgAAAAAAAMBSAAAAAEAAAAMAAAACAAMAAgABAAIAAAACAAAAAwAAAABAAAAYQAAAAQAAABuYW1lAAAAAAAAAAAAAAYACAAGAAYAAAAAAAIAAQAAAGEAAAD/////uAAAABQAAAAAAAAADAAWABQAEwAMAAQADAAAACAAAAAAAAAAFAAAAAAAAAMDAAoAGAAMAAgABAAKAAAAFAAAAFgAAAACAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAACAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAABAAAAAAABAkEAAAAAAAAAAQBAAAAAMABQAEgAMAAgABAAMAAAAEAAAACwAAAA8AAAAAAADAAEAAAAAAgAAAAAAAMAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoADAAAAAgABAAKAAAACAAAAOwAAAADAAAATAAAACgAAAAEAAAAmP7//wgAAAAMAAAAAQAAAEEAAAAFAAAAcmVmSWQAAAC4/v//CAAAAAwAAAAAAAAAAAAAAAQAAABuYW1lAAAAANj+//8IAAAAhAAAAHsAAAB7ImN1c3RvbSI6eyJDb2x1bW5UeXBlcyI6WyJyZWFsIiwicmVhbCJdfSwiZXhlY3V0ZWRRdWVyeVN0cmluZyI6ImRhdGF0YWJsZSAoYTpyZWFsLCBiOnJlYWwpIFtcbiAgICAxLCAxMDQwLFxuICAgIDIsIDIsXG5dIn0ABAAAAG1ldGEAAAAAAgAAAGwAAAAEAAAArv///xQAAAA4AAAAOAAAAAAAAwE4AAAAAQAAAAQAAACc////CAAAAAwAAAABAAAAYgAAAAQAAABuYW1lAAAAAAAAAACS////AAACAAEAAABiABIAGAAUABMAEgAMAAAACAAEABIAAAAUAAAAQAAAAEgAAAAAAAMBSAAAAAEAAAAMAAAACAAMAAgABAAIAAAACAAAAAwAAAABAAAAYQAAAAQAAABuYW1lAAAAAAAAAAAAAAYACAAGAAYAAAAAAAIAAQAAAGEAAAAgAgAAQVJST1cx
```

In 

image

As a table it appears as:

image

JS Console says:

```
GraphNG.tsx:271 Uncaught TypeError: Cannot read property 'map' of undefined
    at Object.getDisplayValues (GraphNG.tsx:271)
    at VizLegendListItem (VizLegendListItem.tsx:42)
    at VizLegendListItem (react-hot-loader.development.js:757)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
getDisplayValues @ GraphNG.tsx:271
VizLegendListItem @ VizLegendListItem.tsx:42
VizLegendListItem @ react-hot-loader.development.js:757
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22779
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
react-dom.development.js:20085 The above error occurred in the <VizLegendListItem> component:

    at VizLegendListItem (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:278323:20)
    at span
    at li
    at ul
    at AbstractList (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at InlineList (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at div
    at div
    at VizLegendList (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:278323:20)
    at Legend (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:278323:20)
    at VizLayoutLegend (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:278323:20)
    at div
    at div
    at Scrollbars (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at CustomScrollbar (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at div
    at div
    at VizLayout (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:278323:20)
    at GraphNG (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:278323:20)
    at XYChartPanel (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:278323:20)
    at div
    at ErrorBoundary (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at div
    at PanelChrome (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at div
    at AutoSizer (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at div
    at DashboardPanelUnconnected (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at Connect(DashboardPanelUnconnected) (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:282087:75)
    at div
    at div
    at div
    at AutoSizer (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at div
    at div
    at div
    at Pane (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at div
    at SplitPane (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at div
    at Pane (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at div
    at SplitPane (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at SplitPaneWrapper (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at div
    at div
    at PanelEditorUnconnected (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at Connect(PanelEditorUnconnected) (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:282087:75)
    at div
    at DashboardPage (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at Connect(DashboardPage) (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:278323:20)
    at AppContainer (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at HotExportedConnect(DashboardPage) (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at LoadableComponent (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at Component
    at ModalsProvider (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at Component
    at ThemeProvider (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:278323:20)
    at Component
    at ConfigProvider
    at ErrorBoundary (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at ErrorBoundaryAlert (eval at ES6ProxyComponentFactory (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:277836:10), <anonymous>:5:7)
    at Provider (http://localhost:3000/public/build/vendors~app.0b367466150cf79963ef.js:278323:20)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

image

**Environment**:
- Grafana version: 6bdc9fac45
- Data source type & version: ADX (or test, a dataframe with two number columns)

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes #30551

the timeseries legend now allows adding stats to the display, but broke if they were not defined.  This PR:

1. supports legend without any stats defined
2. reuses the legend config from timeseries in XY Chart

### CODE REVIEW

File: packages/grafana-ui/src/components/GraphNG/GraphNG.tsx [hunk 1]
```diff
@@ -259,6 +259,10 @@ export const GraphNG: React.FC<GraphNGProps> = ({
         label: seriesConfig.fieldName,
         yAxis: axisPlacement === AxisPlacement.Left ? 1 : 2,
         getDisplayValues: () => {
+          if (!legend.calcs?.length) {
```
Comment (ryantxu) [inline packages/grafana-ui/src/components/GraphNG/GraphNG.tsx:262]: this was causing the failure

**Review by leeoniya — APPROVED** [review]
