### PR TITLE
CloudMonitoring: Fix annotation queries

### LINKED ISSUE #41526: CloudMonitoring: Annotation queries are broken
**What happened**:
Annotation queries are broken. Problem likely introduced in [this PR](https://github.com/grafana/grafana/pull/40740). 

**How to reproduce it (as minimally and precisely as possible)**:
Create an annotation query and refresh panel to trigger it

### PR DESCRIPTION
**Pull request by sunker**
**What this PR does / why we need it**:
Currently, CloudMonitoring annotation queries always return an error because the tags prop in the annotation query model passed from the frontend is an array meanwhile the backend [expects a string](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudmonitoring/annotation_query.go#L33). 

I don't know why the [tags prop](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloud-monitoring/datasource.ts#L65) is passed to the backend in the first place, because it's not part of the annotation query model and it's not possible to specify tags in the annotation query editor. Also, the returned tags were completely [ignored](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloud-monitoring/datasource.ts#L94) in the frontend, so it could never have worked anyway. So for now, I'm just removing tags from the query to fix this bug.  

In the future, we should return something meaningful, like labels, in the annotation tag field. 

**Which issue(s) this PR fixes**:
Fixes #41526

### CODE REVIEW

File: pkg/tsdb/cloudmonitoring/time_series_filter.go [hunk 1]
```diff
@@ -309,7 +309,7 @@ func (timeSeriesFilter *cloudMonitoringTimeSeriesFilter) parseToAnnotations(dr *
 			annotation["time"] = append(annotation["time"], point.Interval.EndTime.UTC().Format(time.RFC3339))
 			annotation["title"] = append(annotation["title"], formatAnnotationText(title, value, series.Metric.Type,
 				series.Metric.Labels, series.Resource.Labels))
-			annotation["tags"] = append(annotation["tags"], tags)
+			annotation["tags"] = append(annotation["tags"], "")
```
Comment (andresmgot) [inline pkg/tsdb/cloudmonitoring/time_series_filter.go:312]: are the `tags` required here? what happens if you remove this line?

File: pkg/tsdb/cloudmonitoring/time_series_query.go [hunk 2]
```diff
@@ -313,7 +313,7 @@ func (timeSeriesQuery cloudMonitoringTimeSeriesQuery) parseToAnnotations(queryRe
 				annotation := make(map[string]string)
 				annotation["time"] = point.TimeInterval.EndTime.UTC().Format(time.RFC3339)
 				annotation["title"] = formatAnnotationText(title, value, d.MetricKind, metricLabels, resourceLabels)
-				annotation["tags"] = tags
+				annotation["tags"] = ""
```
Comment (andresmgot) [inline pkg/tsdb/cloudmonitoring/time_series_query.go:316]: same

**Review by andresmgot — APPROVED** [review]

File: pkg/tsdb/cloudmonitoring/time_series_filter.go (hunk 1 above)
Comment (sunker) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:312]: I believe they are. The framework expects tags to be returned, even though they are empty

**Comment by sunker** [comment]
I believe this bug was introduced in https://github.com/grafana/grafana/pull/38650, so no need to backport this one to 8.2.x
