### PR TITLE
Elasticsearch: Fix legend for alerting, expressions and previously frontend queries

### LINKED ISSUE #83968: Elastic Datasource: query groups are no longer converted to labels
### What happened?

After the last Grafana update, Elasticsearch query groups are no longer converted to labels.

The absence of “*service” label causes Slack alerts to come ungrouped and without identification which services have issues. Also this partially breaks templated Slack alert messages.
image

### What did you expect to happen?

That the labels shown up correctly

### Did this work before?

Yes it was working before. See attached image

### How do we reproduce it?

We could reproduce it with following steps  
1. new alert
2. select elastic as datasource
3. add query
4. add reduce and threshold
5. click on preview

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 10.3.3
OS: Windows Server 2022 
Browser: Chrome

### Grafana platform?

A downloaded binary

### Datasource(s)?

Elastic (should be the native one)

### LINKED ISSUE #84054: Dashboards: Elasticsearch legends not shown with 10.4.0
### What happened?

I have a visualization that used to show the ratio between two sets of data. The queries are set up like this:

image

The visualization is a heatmap with no custom settings.

The heatmap shows some seemingly random numbers as y-axis labels:

image

Note that I only want to display the last query (the calculated ratio). When I only keep the first query for debugging purposes, I get the correct labels:

image

### What did you expect to happen?

I am expecting the heatmap to show the actual distinct values of `study.subject.keyword` in the y axis as labels, because I only want to show the calculated ratio grouped by those values.

### Did this work before?

Yes! This used to be the case with Grafana < 10.4. It now no longer works after updating. Something broke here.

### How do we reproduce it?

See the screenshots for the queries.

### Is the bug inside a dashboard panel?

Too long for this field. See https://gist.github.com/slhck/929757d91275c85186dfd1d5614f6c99

### Environment (with versions)?

Grafana: 10.4.0
OS: Docker/Linux
Browser: Chrome 122

### Grafana platform?

None

### Datasource(s)?

Elasticsearch 8

### PR DESCRIPTION
**Pull request by ivanahuckova**
The detailed investigation and decision on why are we producing different names for regular queries and for alerting/expression queries can be found in https://docs.google.com/document/d/1tW0E2Ol5E90KwFvK-FMgfLNs6ChRlSouw-PwyjVNh60/edit

Summary: 
We will have to use different naming for responses produced by regular queries vs produced by alerting and expression queries, which can be identified through headers - `FromAlert` and  `X-Grafana-From-Exp`. 

For regular queries, we are going to use the same naming as was in frontend, which 100% produces the same experience through frontend and new backend - using `frame.Name` and deleting labels `valueField.Labels = nil`.

For alerting and expression queries, we are going to use the same naming convention as was done initially `field.SetConfig(&data.FieldConfig{DisplayNameFromDS: fieldName})`.

Testing:

1. Create alert with `gdev-elastic` and the preview should look like this - graph legend shouldn't have duplicated name and labels `{hostname=hostname1}...` should be visible

image

2. Import following dashboard that tests for 3 issues - correct functioning of transformations, fields overrides and server side expressions. 

https://github.com/grafana/grafana/assets/30407135/1aa605a9-1136-405a-b295-28d3c29e85f8

```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 880,
  "links": [],
  "panels": [
    {
      "datasource": {
        "type": "elasticsearch",
        "uid": "gdev-elasticsearch"
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "scaleDistribution": {
              "type": "linear"
            }
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 4,
      "options": {
        "calculate": false,
        "cellGap": 1,
        "color": {
          "exponent": 0.5,
          "fill": "dark-orange",
          "mode": "scheme",
          "reverse": false,
          "scale": "exponential",
          "scheme": "Oranges",
          "steps": 64
        },
        "exemplars": {
          "color": "rgba(255,0,255,0.7)"
        },
        "filterValues": {
          "le": 1e-9
        },
        "legend": {
          "show": true
        },
        "rowsFrame": {
          "layout": "unknown"
        },
        "tooltip": {
          "maxHeight": 600,
          "mode": "single",
          "showColorScale": false,
          "yHistogram": false
        },
        "yAxis": {
          "axisPlacement": "left",
          "reverse": false
        }
      },
      "pluginVersion": "11.0.0-pre",
      "targets": [
        {
          "alias": "",
          "bucketAggs": [
            {
              "field": "label",
              "id": "3",
              "settings": {
                "min_doc_count": "1",
                "order": "desc",
                "orderBy": "_term",
                "size": "10"
              },
              "type": "terms"
            },
            {
              "field": "@timestamp",
              "id": "2",
              "settings": {
                "interval": "auto"
              },
              "type": "date_histogram"
            }
          ],
          "datasource": {
            "type": "elasticsearch",
            "uid": "gdev-elasticsearch"
          },
          "hide": true,
          "metrics": [
            {
              "id": "1",
              "type": "count"
            }
          ],
          "query": "hostname: hostname1",
          "refId": "hostname1",
          "timeField": "@timestamp"
        },
        {
          "alias": "",
          "bucketAggs": [
            {
              "field": "label",
              "id": "3",
              "settings": {
                "min_doc_count": "1",
                "order": "desc",
                "orderBy": "_term",
                "size": "10"
              },
              "type": "terms"
            },
            {
              "field": "@timestamp",
              "id": "2",
              "settings": {
                "interval": "auto"
              },
              "type": "date_histogram"
            }
          ],
          "datasource": {
            "type": "elasticsearch",
            "uid": "gdev-elasticsearch"
          },
          "hide": true,
          "metrics": [
            {
              "id": "1",
              "type": "count"
            }
          ],
          "query": "",
          "refId": "all",
          "timeField": "@timestamp"
        },
        {
          "datasource": {
            "name": "Expression",
            "type": "__expr__",
            "uid": "__expr__"
          },
          "expression": "$hostname1/$all",
          "hide": false,
          "refId": "ratio",
          "type": "math"
        }
      ],
      "title": "Panel Title",
      "type": "heatmap"
    },
    {
      "datasource": {
        "type": "elasticsearch",
        "uid": "gdev-elasticsearch"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "hostname5"
            },
            "properties": [
              {
                "id": "custom.axisLabel",
                "value": "this needs to be shown"
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 12,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "maxHeight": 600,
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "11.0.0-pre",
      "targets": [
        {
          "alias": "",
          "bucketAggs": [
            {
              "field": "hostname",
              "id": "3",
              "settings": {
                "min_doc_count": "1",
                "order": "desc",
                "orderBy": "_term",
                "size": "10"
              },
              "type": "terms"
            },
            {
              "field": "@timestamp",
              "id": "2",
              "settings": {
                "interval": "6h"
              },
              "type": "date_histogram"
            }
          ],
          "datasource": {
            "type": "elasticsearch",
            "uid": "gdev-elasticsearch"
          },
          "metrics": [
            {
              "id": "1",
              "type": "count"
            }
          ],
          "query": "",
          "refId": "A",
          "timeField": "@timestamp"
        }
      ],
      "title": "overrides name ",
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "elasticsearch",
        "uid": "gdev-elasticsearch"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 8
      },
      "id": 3,
      "options": {
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "showPercentChange": false,
        "textMode": "auto",
        "wideLayout": true
      },
      "pluginVersion": "11.0.0-pre",
      "targets": [
        {
          "alias": "",
          "bucketAggs": [
            {
              "field": "@timestamp",
              "id": "2",
              "settings": {
                "interval": "6h"
              },
              "type": "date_histogram"
            }
          ],
          "datasource": {
            "type": "elasticsearch",
            "uid": "gdev-elasticsearch"
          },
          "metrics": [
            {
              "id": "1",
              "type": "count"
            }
          ],
          "query": "",
          "refId": "A",
          "timeField": "@timestamp"
        }
      ],
      "title": "transform + name",
      "transformations": [
        {
          "id": "reduce",
          "options": {
            "includeTimeField": false,
            "mode": "reduceFields",
            "reducers": [
              "last",
              "min"
            ]
          }
        },
        {
          "id": "filterFieldsByName",
          "options": {}
        }
      ],
      "type": "stat"
    }
  ],
  "schemaVersion": 39,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timeRangeUpdatedDuringEditOrView": false,
  "timepicker": {},
  "timezone": "browser",
  "title": "test es",
  "uid": "edfmgdz48dqm8b",
  "version": 11,
  "weekStart": ""
}
```

image

Also sanity check - that in our test dashboard, names are the same as frontend produced frames (this shouldn't change as we are not changing this logic)

image

image

Fixes: https://github.com/grafana/grafana/issues/84054
Fixes: https://github.com/grafana/grafana/issues/83968

### CODE REVIEW

File: pkg/tsdb/elasticsearch/data_query.go [hunk 1]
```diff
@@ -23,20 +23,25 @@ const (
...
-		dataQueries: dataQuery,
-		logger:      logger,
-		ctx:         ctx,
-		tracer:      tracer,
+		client:               client,
+		dataQueries:          req.Queries,
+		logger:               logger,
+		ctx:                  ctx,
+		tracer:               tracer,
+		keepLabelsInResponse: fromAlert || fromExpression,
```
Comment (svennergr) [inline pkg/tsdb/elasticsearch/data_query.go:44]: hm, maybe a small comment why we need that?

**Review by svennergr — APPROVED** [review]
🚀

File: pkg/tsdb/elasticsearch/data_query.go (hunk 1 above)
Comment (ivanahuckova) [reply pkg/tsdb/elasticsearch/data_query.go:46]: 👍
