### PR TITLE
PublicDashboards: Query collapsed panels inside rows

### LINKED ISSUE #58702: Public Dashboards: Impossible to unfold a folded row in the public dashboard.
**What happened**:
If a row is saved as folded on the real dashboard, the anonymous user will not be able to unfold it on the public dashboard.

**What you expected to happen**:
The row should properly unfold and its contained panels should work.

**How to reproduce it (as minimally and precisely as possible)**:
Simply collapse a row and save your dashboard. The public one will be able to unfold but will get an error with the panels.  
See the following three screenshots below:

<hr>

**The row is folded**
image

<hr>

**I get an error when I unfold the row**
image

<hr>

**Here is the error**
image

<hr>

**Anything else we need to know?**:
I also get an error if I try to close the tab after unfolding the row. It apparently thinks I've make changes to the dashboard.

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome on Windows 10

### PR DESCRIPTION
**Pull request by evictorero**
**What is this feature?**
Load panel queries inside collapsed rows.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/58702

**Special notes for your reviewer**:
When a public dashboard loads queries from the dashboard model it ignores those panels inside a panel of `type=row` and collapsed rows. 
Added a recursive call to load all panels inside collapsed rows so when a user wants to unfold the row, the panel it's found and the query request returns the data.

### CODE REVIEW

File: pkg/services/publicdashboards/service/query.go [hunk 1]
```diff
@@ -239,9 +239,22 @@ func getUniqueDashboardDatasourceUids(dashboard *simplejson.Json) []string {
...
+
+	return result
+}
+
+func extractQueriesFromPanels(panels []interface{}, result map[int64][]*simplejson.Json) {
+	for _, panelObj := range panels {
 		panel := simplejson.NewFromAny(panelObj)
 
+		// if the panel is a row and it is collapsed, get the queries from the panels inside the row
+		if panel.Get("type").MustString() == "row" && panel.Get("collapsed").MustBool() == true {
```
Comment (juanicabanas) [inline pkg/services/publicdashboards/service/query.go:252]: isn't there a way to start the view with a panel row expanded? I mean, not collapsed, so this condition won't work.
Based on pubdash page component, I don't think so.
Has the dashboard that behavior? Should we add it?

**Review by juanicabanas — APPROVED** [review]

File: pkg/services/publicdashboards/service/query.go (hunk 1 above)
Comment (evictorero) [reply pkg/services/publicdashboards/service/query.go:252]: What do you mean? You can save a dashboard with rows collapsed or expanded. Then, the public dashboard will reflect that behavior, so yes, it is possible.

Comment (juanicabanas) [reply pkg/services/publicdashboards/service/query.go]: I mean, is it possible to pass a query param and start with the dashboard not collapsed, so `panel.Get("collapsed").MustBool() == true` will be false?
I just checked and it seems that's not possible
