### PR TITLE
Explore: Pass the dataframes along with the time range of the data

### LINKED ISSUE #89039: Explore: TimeSeriesPanel crashes after switching the time range
### What happened?

TimeSeriesPanel crashes with the error below after switching from an absolute range (5 second wide) to relative "last 3 hours":

```
RangeError: Invalid array length
    at Array.push (<anonymous>)
    at i (nullInsertThreshold.ts:156:20)
    at r (nullInsertThreshold.ts:72:31)
    at h (utils.ts:132:9)
    at TimeSeriesPanel.tsx:47:32
```

The issue doesn't seem to be happening in Dashboards.

Possibly related issues:
- https://github.com/grafana/grafana/pull/79725

For more details please check: https://raintank-corp.slack.com/archives/C02TXB92G6T/p1717626732900599 

### What did you expect to happen?

The panel should display the data.

### Did this work before?

Not sure.

### How do we reproduce it?

See above

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Grafana v11.1.0-71799 (3a8b59f5e8)
OS: MacOS
Browser: Chrome Version 125.0.6422.142 (Official Build) (arm64)

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Loki

### PR DESCRIPTION
**Pull request by ifrost**
Fixes https://github.com/grafana/grafana/issues/89039

Another attempt after reverting https://github.com/grafana/grafana/pull/90259. Main difference is that [the range is memoized](https://github.com/grafana/grafana/pull/90594/commits/f5c1596bb4373a93d2ebd499689d857a20098a8c) to avoid infinite loop caused by onHiddenSeriesChanged callbacked called from ExploreGraph, triggering another render with the same range values but newly created time range from/to objects.

The fix is to ensure onHiddenSeriesChanged is called only when hidden frames actually change.

### CODE REVIEW

**Comment by ifrost** [comment]
@grafana/observability-logs sorry for not waiting for your review last time and thanks for reporting the bug 👍

**Review by harisrozajac — APPROVED** [review]
Tested it with the logs volume panel and no flickering or infinitely calling `onHiddenSeriesChanged` 
🚀

**Review by gelicia — APPROVED** [review]
Looks good - tested with a flame graph and trace view as well.

**Comment by matyax** [comment]
Looking! Sorry for the delay.

File: public/app/features/explore/Graph/ExploreGraph.tsx [hunk 1]
```diff
@@ -166,7 +153,13 @@ export function ExploreGraph({
           hiddenFrames.push(getFrameDisplayName(frame));
         }
       });
-      onHiddenSeriesChangedRef.current(hiddenFrames);
+      if (
+        previousHiddenFrames.current === undefined ||
+        !isEqual(sortBy(hiddenFrames), sortBy(previousHiddenFrames.current))
```
Comment (matyax) [inline public/app/features/explore/Graph/ExploreGraph.tsx:158]: Is there any possibility for a performance impact of this conditional with sorting and comparison?

**Review by matyax — APPROVED** [review]
Made a few tests with the usual log happy paths in explore and looked good 👌

File: public/app/features/explore/Graph/ExploreGraph.tsx (hunk 1 above)
Comment (ifrost) [reply public/app/features/explore/Graph/ExploreGraph.tsx:158]: It's a one-off operation when data / config changes. Non-scientific benchmark on my laptop shows that it may increase from 0.1ms to 0.2ms. I didn't see any issues while a Loki query response was being split. This list contains names of hidden frames so by default it's empty and it may add some impact only with filtering. Lodash it quite fast at sorting strings so it should be quick even with thousands of data frames.

Comment (ifrost) [reply public/app/features/explore/Graph/ExploreGraph.tsx:158]: I'll merge it after syncing with main but let us know if you spot anything suspicious 😉

Comment (matyax) [reply public/app/features/explore/Graph/ExploreGraph.tsx:158]: For sure. Thank you!
