### PR TITLE
Postgres: Fix time group macro when TimescaleDB is enabled and interval is less than a second

### LINKED ISSUE #33124: PostgreSQL+TimescaleDB: no data retrieved for intervals below 1s when using $__timeGroup macro in Grafana 7.4.2+
**What happened**:
I use Grafana with PostgreSQL data source with TimescaleDB installed. 
In a query using $__timeGroup macro, when the interval determined by the UI is less than 1s (e.g. 200ms), the macro no longer gets translated to the correct time_bucket function. Instead, the interval passed to time_bucket function in these cases is "0s", which causes an error: "pq: period must be greater then 0". As a result, no data is returned from the database. See screenshot from the Query Inspector below.
This behavior is observed for all Grafana releases from 7.4.2 to 7.5.4. 
incorrect_blur

**What you expected to happen**:
The interval is translated correctly between $__timeGroup and time_bucket, for example $__timeGroup(time, '200ms', 0) should be time_bucket('0.2s', time). The behavior was correct in previous Grafana releases. 
See attached screenshot from Grafana 7.4.1 for the exact same query: 
correct_blur

**How to reproduce it (as minimally and precisely as possible)**:
Zoom in close enough on a time trace pulled in from TimescaleDB. 

**Environment**:
- Grafana version: 7.4.2+ 
- Data source type & version: PostgreSQL 12.5 + TimescaleDB 12 
- OS Grafana is installed on: Windows 
- User OS & Browser: Chrome 
- Grafana plugins: PostgreSQL

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Fixing a special case with time group macro when using TimescaleDB and interval is lower than a second.

**Which issue(s) this PR fixes**:
Fixes #33124

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/tsdb/postgres/macros.go [hunk 1]
```diff
@@ -109,6 +109,9 @@ func (m *postgresMacroEngine) evaluateMacro(name string, args []string) (string,
 		}
 
 		if m.timescaledb {
+			if interval.Seconds() < 1.0 {
```
Comment (ying-jeanne) [inline pkg/tsdb/postgres/macros.go:112]: instead of checking it is < 1.0 could we check float(int64(interval.Seconds())) == interval.Seconds(), or something similar, because in this case, we could keep the possibility to have an interval like 1.2 seconds. (in reality it might be less but i think 1.5 is still something that users might use.)

Comment (marefr) [reply pkg/tsdb/postgres/macros.go]: Changed so that always a precision of 1 is used.

**Review by ying-jeanne — APPROVED** [review]

File: pkg/tsdb/postgres/macros_test.go [hunk 2]
```diff
@@ -7,217 +7,210 @@ import (
 	"time"
 
 	"github.com/grafana/grafana/pkg/plugins"
-	. "github.com/smartystreets/goconvey/convey"
+	"github.com/stretchr/testify/require"
 )
 
 func TestMacroEngine(t *testing.T) {
-	Convey("MacroEngine", t, func() {
```
Comment (ying-jeanne) [inline pkg/tsdb/postgres/macros_test.go:14]: thanks for the chore 🧹

**Comment by paniterka** [comment]
Hello, I'm the original poster of #33124 - thank you for tackling this. I tested the feature and it is not working fully correctly yet, basically the bug is the same, only now for values below 50ms - I left my comment in the original issue. Thanks for your efforts!
