### PR TITLE
Fix #10555 #6888 Backslash in Prometheus variables

### LINKED ISSUE #10555: backslash in prometheus label in not escaped properly
When I use a variable to choose between multiple label/value that have a backslash, the regexes in the graphes are not working.

grafana5

### PR DESCRIPTION
**Pull request by roidelapluie**
Prior this commit, `C:\bar` was escaped `C:\\\bar`. Should be `C:\\\\bar`.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by bergquist** [comment]
This should have tests.

**Comment by roidelapluie** [comment]
Tests added

**Comment by bergquist** [comment]
Perhaps Im blind... But are there any docs for this at prometheus.io ?

**Comment by roidelapluie** [comment]
I am just testing what was present before my change and fixed `\` escaping

**Comment by roidelapluie** [comment]
https://prometheus.io/docs/prometheus/latest/querying/examples/

All regular expressions in Prometheus use RE2 syntax.

https://github.com/google/re2/wiki/Syntax

**Comment by roidelapluie** [comment]
@bergquist Now updated to escape {}[]

File: public/app/plugins/datasource/prometheus/specs/datasource_specs.ts [hunk 1]
```diff
@@ -606,6 +606,43 @@ describe('PrometheusDatasource', function() {
   });
 });
 
+describe('Prometheus regular escaping', function() {
```
Comment (bergquist) [inline public/app/plugins/datasource/prometheus/specs/datasource_specs.ts]: These tests should be moved to `datasource.jest.ts` 

we want to move as many tests as possible to jest instead

Comment (roidelapluie) [reply public/app/plugins/datasource/prometheus/specs/datasource_specs.ts]: done! :)

**Review by bergquist — APPROVED** [review]

**Comment by bergquist** [comment]
:+1:
