### PR TITLE
PublicDashboards: fix collapsed rows queries

### LINKED ISSUE #66012: Bug: Panels with rows collapsed not working in Cloud
This is failing only in Enterprise or Cloud because the cache service is [checking for additional permissions](https://github.com/grafana/grafana-enterprise/blob/main/src/pkg/extensions/dspermissions/cache/cache.go#L97) for data sources and the datasourcesUids array contains empty value because of collapsed rows contains panels.  
Creating an array with the correct data source uid values will fix this issue.

### PR DESCRIPTION
**Pull request by evictorero**
**What is this feature?**
We generate an array of unique uids of data sources to check for permissions. 
Nested panels in collapsed rows where failing to return the correct data source uid and they were returning an empty value.
When checking permissions, the empty value fails because there is no data source with that uid.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/66012

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/services/publicdashboards/service/query.go [hunk 1]
```diff
@@ -213,7 +213,10 @@ func getUniqueDashboardDatasourceUids(dashboard *simplejson.Json) []string {
 	var datasourceUids []string
 	exists := map[string]bool{}
 
-	for _, panelObj := range dashboard.Get("panels").MustArray() {
+	// collapsed rows contain panels in a nested structure, so we need to flatten them before calculate unique uids
+	flatPanels := getFlattenPanels(dashboard)
```
Comment (juanicabanas) [inline pkg/services/publicdashboards/service/query.go:217]:
```suggestion
	flatPanels := getFlattenedPanels(dashboard)
```

**Review by juanicabanas — APPROVED** [review]
