### PR TITLE
Prometheus: Use default POST method if no httpMethod provided

### LINKED ISSUE #37976: Prometheus Data source with SSE Errors: "failed to query data: no http method provided"
**What happened**:

Works: 
image

Does not work (Error):

image

**What you expected to happen**:
Used to work for me, so guess something changed and needs to be updated, not sure what I missed yet though.

**Anything else we need to know?**:
Once an SSE operation is added, the query is routed through the backend.

**Environment**:
- Grafana version: d93d989a5a (origin/main)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:

Prometheus was missing default httpMethod (POST) on backend. httpMethod is not required field therefore if it is not provided, we want to use default method. 
**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/37976

### CODE REVIEW

File: pkg/tsdb/prometheus/prometheus.go [hunk 1]
```diff
@@ -70,6 +70,7 @@ func (s *Service) Init() error {
 
 func newInstanceSettings() datasource.InstanceFactoryFunc {
 	return func(settings backend.DataSourceInstanceSettings) (instancemgmt.Instance, error) {
+		defaultHttpMethod := "POST"
```
Comment (marefr) [inline pkg/tsdb/prometheus/prometheus.go:73]: Probably need to import the "http" package with this change as well.

```suggestion
		defaultHttpMethod := http.MethodPost
```

**Review by marefr — APPROVED** [review]
LGTM, but see suggestion

File: pkg/tsdb/prometheus/prometheus.go (hunk 1 above)
Comment (ivanahuckova) [reply pkg/tsdb/prometheus/prometheus.go]: Changed in https://github.com/grafana/grafana/pull/38446/commits/18caa5b1fe25318a3c9e388a4e0d878ca189e055

**Review by kylebrandt — APPROVED** [review]
Fixes the issue for me, thanks all!

**Review by kminehart — APPROVED** [review]
