### PR TITLE
Move panel plugin change logic into scenes

### LINKED ISSUE #89836: Scenes: Thresholds doesn't work after creating a gauge panel
**Problem**
> it feels like scenes has broken creating / editing a gauge panel, trying to get a video of some of the issues i ran across, but it wasn't consistently rendering as i made updates, and there were weird issues with changing thresholds, colors, etc. - anyone else reported same? 

When changing between panel types, the color strategy is always set as classic palette.

**Investigation**
This is caused because, when changing between plugin types, the options are not properly calculated.

When computing options for the new plugin, VizPanelManager creates a `new VizPanel`, which behind the scenes calls [getPanelOptionsWithDefaults](https://github.com/grafana/grafana/blob/0285278cfc5cf8e9780f7a0624a5f1c8c6e75590/packages/grafana-data/src/panel/getPanelOptionsWithDefaults.ts#L34) that generates the options for the VizPanel plugin. If `isAfterPluginChange` is not set to true, the `adaptFieldColorMode` won't set the plugin color mode, and it will default to classic instead.

**Solution**
Make `VizPanel` to always set `isAfterPluginChange` when loading the plugin after activation.

### PR DESCRIPTION
**Pull request by mdvictor**
Moves panel plugin change logic into scenes, in the VizPanel. This is needed because when changing plugin, the VizPanelManager does not have access to the new plugin (since it is being pulled async) and thus cannot merge default options/fieldConfig into the existing ones.

Depends on https://github.com/grafana/scenes/pull/836. Need to update packages after it gets merged.

Fixes https://github.com/grafana/grafana/issues/89836

### CODE REVIEW

**Comment by torkelo** [comment]
what do you mean by 

> VizPanelManager is not aware of the new plugin

in what way is it not aware of it?

File: public/app/features/dashboard-scene/panel-edit/VizPanelManager.tsx [hunk 1]
```diff
@@ -222,13 +214,6 @@ export class VizPanelManager extends SceneObjectBase<VizPanelManagerState> {
       newFieldConfig = restoreCustomOverrideRules(newFieldConfig, cachedFieldConfig);
```
Comment (torkelo) [inline public/app/features/dashboard-scene/panel-edit/VizPanelManager.tsx:214]: just test/verify that standard field config is preserved when changing plugins (unit, decimals, min/max etc)

**Comment by mdvictor** [comment]
> what do you mean by
> 
> > VizPanelManager is not aware of the new plugin
> 
> in what way is it not aware of it?

I worded that a bit wrongly. The VizPanelManager is aware of the plugin and it called `panel.getPlugin()`, but when changing the plugin type, it would create a new vizPanel and call `getPlugin` on it before it activated, which returned undefined. This meant that we did not have the new plugin loaded, since that is done async, so the logic never worked.

**Review by ivanortegaalba — APPROVED** [review]
Great work Victor on this!!! It works like a charm! LGTM!

**Comment by mdvictor** [comment]
There were a couple extra problems that appeared with this around table view in panel edit, or because of other getPlugin calls. I pushed another commit to fix it

File: public/app/features/dashboard-scene/panel-edit/PanelDataPane/PanelDataPane.tsx [hunk 2]
```diff
@@ -59,16 +60,13 @@ export class PanelDataPane extends SceneObjectBase<PanelDataPaneState> {
   }
 
   private onActivate() {
-    const panel = this.panelManager.state.panel;
-    this.setupPanelSubscription(panel);
```
Comment (mdvictor) [inline public/app/features/dashboard-scene/panel-edit/PanelDataPane/PanelDataPane.tsx:63]: we no longer need a panel sub as we hold everything we need on the panelVizManager. panel sub would also become pointless when switching to table view, thus deactivating the vizPanel and removing it's subs.

File: public/app/features/dashboard-scene/panel-edit/VizPanelManager.tsx [hunk 3]
```diff
@@ -103,6 +102,8 @@ export class VizPanelManager extends SceneObjectBase<VizPanelManagerState> {
       $variables: variables,
       panel: sourcePanel.clone(),
       sourcePanel: sourcePanel.getRef(),
+      pluginId: sourcePanel.state.pluginId,
+      skipDataQuery: config.panels[sourcePanel.state.pluginId].skipDataQuery,
```
Comment (mdvictor) [inline public/app/features/dashboard-scene/panel-edit/VizPanelManager.tsx:106]: We need these properties in state to avoid relying on `getPlugin` around panelEdit.

**Review by dprokop — APPROVED** [review]
I've tested this a bit and didn't find any regressions.

File: public/app/features/dashboard-scene/panel-edit/PanelDataPane/PanelDataPane.tsx [hunk 4]
```diff
@@ -103,13 +87,7 @@ export class PanelDataPane extends SceneObjectBase<PanelDataPaneState> {
...
 
     if (panel) {
-      const plugin = panel.getPlugin();
-
-      if (!plugin) {
-        return;
-      }
-
-      if (plugin.meta.skipDataQuery) {
+      if (panelManager.state.skipDataQuery) {
```
[the remark this answers is not in the document]
Comment (mdvictor) [reply public/app/features/dashboard-scene/panel-edit/PanelDataPane/PanelDataPane.tsx:90]: aah, you are right! We most probably do not need that in state indeed! Will update

**Review by axelavargas — COMMENTED** [review]
Hey @mdvictor 👋🏾, I gave it a quick test and found a couple of things (I used the canary scenes version from the other pr)

1. #### Issue with threshold options: It seems that changing the threshold options is not triggering a refresh in the visualization


https://github.com/user-attachments/assets/e7aa5d32-7d65-4626-a326-788601d2dbf6



2.  ####  Text panels changing the `gridPos`? 
This one was strange, I compared the same dashboard in the old architecture, and I noticed TextPanels are now taking 24 of width.  I am not sure this is related to your changes, though


WeirdRenderizationForTextPanels

File: yarn.lock
[the remark this answers is not in the document]
Comment (mdvictor) [reply yarn.lock:1]: hmm, the yarn.lock does look a bit suspicious, will review

**Comment by mdvictor** [comment]
@axelavargas For 1, I think you found a different bug! This is currently reproducible on ops as well, seems like some options rerender the panel and some don't. 

For the second one I couldn't reproduce, can you help me with that? It doesn't look like it is related to this either, tho. 

I would first try closing and fixing this issue and then I can open followup issues for the rest, if they are unrelated to this PR

**Comment by axelavargas** [comment]
> @axelavargas For 1, I think you found a different bug! This is currently reproducible on ops as well, seems like some options rerender the panel and some don't.
> 
> For the second one I couldn't reproduce, can you help me with that? It doesn't look like it is related to this either, tho.
> 
> I would first try closing and fixing this issue and then I can open followup issues for the rest, if they are unrelated to this PR

Sure thing, let's merge this one then. 

P.S. I am sharing the dashboard for the second one. 

[Variables resolving multiple times-1721657010989.txt](https://github.com/user-attachments/files/16334770/Variables.resolving.multiple.times-1721657010989.txt)

**Review by axelavargas — APPROVED** [review]

**Comment by mdvictor** [comment]
@axelavargas I've looked through that dashboard, it looks very weird, not sure what's happening there but the same happens on main with it so I think it's unrelated to this. Still, I wonder what caused this to happen, I cannot reproduce it anywhere else other that on that db
