### PR TITLE
TimeSeries: don't auto-disable fill of fillBelowTo targets

### LINKED ISSUE #41092: Setting B Fill below to <A> disables fill in A
**What happened**:

On a Time Series panel, when I set an override for field `two` to `Fill below to` field `one`, the fill for `one` is disabled, leaving its background empty.

##### With `Fill below to` set:

image

##### Without it:

image

**What you expected to happen**:

I expect to be able to still have field `one` with its own fill settings working.

**How to reproduce it (as minimally and precisely as possible)**:

Add the panel below (it works with a Prometheus data source as the queries use `vector()`):

```
{
  "id": 23763571993,
  "gridPos": {
    "x": 0,
    "y": 0,
    "w": 12,
    "h": 9
  },
  "type": "timeseries",
  "title": "Panel Title",
  "targets": [
    {
      "expr": "vector(1)",
      "legendFormat": "one",
      "interval": "",
      "exemplar": true,
      "refId": "A"
    },
    {
      "expr": "vector(2)",
      "legendFormat": "two",
      "interval": "",
      "exemplar": true,
      "refId": "B",
      "hide": false
    }
  ],
  "options": {
    "tooltip": {
      "mode": "single"
    },
    "legend": {
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    }
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "linear",
        "barAlignment": 0,
        "lineWidth": 1,
        "fillOpacity": 30,
        "gradientMode": "opacity",
        "spanNulls": false,
        "showPoints": "auto",
        "pointSize": 5,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "value": null,
            "color": "green"
          },
          {
            "value": 80,
            "color": "red"
          }
        ]
      },
      "mappings": [],
      "min": 0
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "two"
        },
        "properties": [
          {
            "id": "custom.fillBelowTo",
            "value": "one"
          },
          {
            "id": "custom.gradientMode",
            "value": "none"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "one"
        },
        "properties": [
          {
            "id": "custom.fillOpacity",
            "value": 100
          }
        ]
      }
    ]
  },
  "datasource": null
}
```

**Anything else we need to know?**:

Disabling `Fill below to` reenables all the fills, but then the color filling `one` is the sum of both `one` and `two`, which is not as I desire.

**Environment**:
- Grafana version: `v8.2.2 (6232fe07c0)`
- Data source type & version: N/A
- OS Grafana is installed on: Linux
- User OS & Browser: macOS Monterey, Firefox 93.0 and Safari 15.1
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes #41092

(follow-up to https://github.com/grafana/grafana/pull/41998)

specifically this addresses a situation where we were removing fills of series that had their own explicit `fillBelowTo` overrides https://github.com/grafana/grafana/issues/41092#issuecomment-994488943.

the purpose of auto-removing the fills in the first place was to:

1. make it less config for the user. without us doing this automagically, the user has to disable the fills manually on all the "low" series.
2. make it less easily confused with stacked mode, which would look identical.

an alternative to this would be to simply leave everything explicit and let the user disable all fills themselves when configuring `fillBelowTo`. thoughts? cc @dprokop @torkelo.

before:

image

after:

image

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 496,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "C-series"
            },
            "properties": [
              {
                "id": "custom.fillBelowTo",
                "value": "B-series"
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "B-series"
            },
            "properties": [
              {
                "id": "custom.fillBelowTo",
                "value": "A-series"
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 11,
        "w": 10,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltip": {
          "mode": "single"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "1,20,90,30,5,0"
        },
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "B",
          "scenarioId": "csv_metric_values",
          "stringInput": "10,41,111,41,30,10"
        },
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "C",
          "scenarioId": "csv_metric_values",
          "stringInput": "20,50,130,50,45,20"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "refresh": "",
  "schemaVersion": 34,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "fillBelowTo-bug2",
  "uid": "Ds_1kiTnk",
  "version": 5,
  "weekStart": ""
}
```

### CODE REVIEW

File: packages/grafana-ui/src/components/uPlot/config/UPlotConfigBuilder.ts [hunk 1]
```diff
@@ -232,10 +232,16 @@ export class UPlotConfigBuilder {
...
         const killFill = new Set<number>();
+
         for (const b of config.bands) {
           killFill.add(b.series[1]);
         }
 
+        // don't remove fills of series that have their own fillBelowTo defined (pseudo-stacking case)
+        for (const b of config.bands) {
+          killFill.delete(b.series[0]);
+        }
```
Comment (torkelo) [inline packages/grafana-ui/src/components/uPlot/config/UPlotConfigBuilder.ts:243]: Is there a way to add a unit test for this condition / scenario?

Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/config/UPlotConfigBuilder.ts:243]: i wanted to see first if we wanted to instead remove all the magic and just leave it up to users to explicitly disable fills when they set fillBelowTo. in that case this would just go away.

**Comment by torkelo** [comment]
I am confused, not sure I understand why we remove the fills

> the purpose of auto-removing the fills in the first place was to:
> make it less config for the user. without us doing this automagically, the user has to disable the fills manually on all the "low" series.

Why does the user have to disable the fill on the low series? I mean if there is a global fill then yes, but not sure understand it if there is only a "fillBelowTo" in an override between high and low

**Comment by dprokop** [comment]
Haven't looked at this for a while, but I also find it confusing now. I mean - I see the point of removing the lower bound fill yet it can lead to this weird scenarios some fills are missing and impossible to bring back. Take a look a the attached dashboard[1]. By default there is a fillOpacity set to 40% on all series, but series A for the auto-removal reason has no fill below it:

image

I think I would rather make the user set it by hand. Maybe to make it easier for the user (so that he/she doesn't have to create an additional override fo fillOpacity) we could have the lower bound fill setting with the fillBelowTo override? Sth like this:

image

<details>
<summary>[1] dashboard.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 636,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 40,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "C-series"
            },
            "properties": [
              {
                "id": "custom.fillBelowTo",
                "value": "B-series"
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "B-series"
            },
            "properties": [
              {
                "id": "custom.fillBelowTo",
                "value": "A-series"
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 11,
        "w": 10,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltip": {
          "mode": "single"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "1,20,90,30,5,0"
        },
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "B",
          "scenarioId": "csv_metric_values",
          "stringInput": "10,41,111,41,30,10"
        },
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "C",
          "scenarioId": "csv_metric_values",
          "stringInput": "20,50,130,50,45,20"
        },
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "hide": false,
          "refId": "D",
          "scenarioId": "csv_metric_values",
          "stringInput": "0,5,13,5,4,2"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "refresh": "",
  "schemaVersion": 34,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "fillBelowTo-bug2",
  "uid": "Ds_1kiTnk",
  "version": 2,
  "weekStart": ""
}
```
</details>

**Comment by leeoniya** [comment]
i've removed all the magic and did tweaked two dev dashboards to set global opacity = 0.

**Review by torkelo — APPROVED** [review]

**Comment by nicolaerosia** [comment]
This causes a regression in one situation and a fix in another in our usecase, I tried to detail it here: https://github.com/grafana/grafana/issues/44466
