### PR TITLE
Alerting: Accurately set value for prom-compatible APIs

### LINKED ISSUE #46095: Alerting: `value` field is empty for alerts in `/api/prometheus/grafana/api/v1/alerts` and `/api/prometheus/grafana/api/v1/rules`
**What happened**:

_This is for Prometheus alert-generator compliance, read more [here](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md). Using Grafana managed alert on a Prometheus datasource._

`value` field is empty for alerts in `/api/prometheus/grafana/api/v1/alerts` and `/api/prometheus/grafana/api/v1/rules`.

**What you expected to happen**:

`value` having the value of the query result from the alerting rule query.

**How to reproduce it (as minimally and precisely as possible)**:

Set a simple alerting rule with `up == 0` query (only one query, no expressions) and have a series satisfying that condition. The alert produced should have `"value": "0"`, but it has `"value": ""`

**Anything else we need to know?**:

Tested using Prometheus data source

**Environment**:
- Grafana version: Latest at the time of opening this PR

### PR DESCRIPTION
**Pull request by gotjosh**
Sets the value fields for the Prometheus compatible API based on a combination of condition `refID` and the values extracted from the different frames.

This is a follow up from #46971, where now that we can extract the correct values for classic conditions we can define a semantic to pick the value we alerted on.

This is a bit nuanced so I'll attempt to explain what's going on:

1. There's a simple change to also expose the values when the alerting state is `pending`.
2. In the first scenario, we have no value in case we weren't able to extract anything so we default back to the previous behaviour of showing the evaluation string. I think this is a bug - alerting alerts should always have a value, so I've filed a separate issue https://github.com/grafana/grafana/issues/47215 to investigate a bit more.
3. If there's only a single value in the condition, we show that without any additional formatting.
4. If we have more than one value then we structure it in a way that shows which condition + position has which value.

The condition is a `refID` needs to be taken into account because this is what an user selects as part of an alerting rule. Even if an alerting rule has multiple `refIDs` that produce multiple values only one of the `refIDs` can be chosen.

Fixes #46095

### CODE REVIEW

**Review by yuri-tceretian — APPROVED** [review]
LGTM 👍🏻

File: pkg/services/ngalert/api/api_prometheus.go [hunk 1]
```diff
@@ -63,6 +65,38 @@ func (srv PrometheusSrv) RouteGetAlertStatuses(c *models.ReqContext) response.Re
...
 
+func formatValues(alertState *state.State) string {
+	var fv string
+	values := alertState.GetLastEvaluationValuesForCondition()
+
+	switch len(values) {
+	case 0:
+		fv = alertState.LastEvaluationString
+	case 1:
+		vs := make([]string, 0, len(values))
```
Comment (grobinson-grafana) [inline pkg/services/ngalert/api/api_prometheus.go:76]: Do we need `vs`, can't we just set `fv` on the first iteration and the break?

File: pkg/services/ngalert/api/api_prometheus.go [hunk 2]
```diff
@@ -63,6 +65,38 @@ func (srv PrometheusSrv) RouteGetAlertStatuses(c *models.ReqContext) response.Re
...
+		fv = vs[0]
+	default:
+		vs := make([]string, 0, len(values))
+
+		for k, v := range values {
+			vs = append(vs, fmt.Sprintf("%s: %s", k, strconv.FormatFloat(v, 'e', -1, 64)))
+		}
+
+		// Ensure we have a consistent ordering after formatting e.g. A0, A1, A3, etc.
+		sort.Slice(vs, func(i, j int) bool {
```
Comment (grobinson-grafana) [inline pkg/services/ngalert/api/api_prometheus.go:90]: The sort here is not a natural sort. I.e. the order of `["A2", "A1", "A10"]` will be `["A1", "A10", "A2"]`.

**Review by grobinson-grafana — APPROVED** [review]

File: pkg/services/ngalert/api/api_prometheus.go (hunk 2 above)
Comment (gotjosh) [reply pkg/services/ngalert/api/api_prometheus.go:89]: I chose to do `strconv.Atoi(vs[i])` as it's the simplest thing I can do without going down a rabbithole and the position is being added by me. The bad thing here is that refIDs can be literally anything IIRC.

Comment (gotjosh) [reply pkg/services/ngalert/api/api_prometheus.go]: After going down a rabbit hole here, I ended up accepting the fact that it'll not be a natural sort. 

If somehow this becomes a problem down the line - we can easily spend some time providing a logical order similar to what the UI gives us. For now, the use of `sort.Strings` will have to do.

**Comment by daverstam** [comment]
Will this possible fix #45982 ?
