### PR TITLE
DataSourceList: expands the clickable area of the DataSource card to be the entire container.

### LINKED ISSUE #32552: DataSource list: Clicking above the data source name doesn't open the card
**What happened**:
Clicking on the padding are of data source card doesn't open the data source settings. It focuses the card, but you have to click at the correct spot again to open it. 

**How to reproduce it (as minimally and precisely as possible)**:
 See video:
 https://user-images.githubusercontent.com/30407135/113149510-62974400-9233-11eb-936f-032e65c1930c.mov

**Anything else we need to know?**:

**Environment**: 
- Grafana version: Grafana 7.5.2 (and master)

### PR DESCRIPTION
**Pull request by thisisobate**
**What this PR does / why we need it**:
This PR expands the clickable area of the DataSource card to be the entire container.
**Which issue(s) this PR fixes**:

Fixes #32552

### CODE REVIEW

**Review by dprokop — APPROVED** [review]
Works good

**Comment by torkelo** [comment]
@thisisobate can you test the search results so that this did not impact that card , it has custom padding I think

File: packages/grafana-ui/src/components/Card/Card.tsx [hunk 1]
```diff
@@ -263,6 +262,7 @@ export const getCardStyles = stylesFactory((theme: GrafanaTheme) => {
     innerLink: css`
       display: flex;
       width: 100%;
+      padding: ${theme.spacing.md};
```
Comment (Clarity-89) [inline packages/grafana-ui/src/components/Card/Card.tsx:265]: Inner link is an optional component, so the Card won't have any padding now if it's not present: 
Screenshot 2021-04-06 at 9 40 48

Comment (thisisobate) [reply packages/grafana-ui/src/components/Card/Card.tsx:265]: hmm...good point.
That means we need to somehow add back the padding to the Card component.

Any ideas on the best possible solution for this? @Clarity-89

**Comment by thisisobate** [comment]
Thanks @Clarity-89 for helping out with the search results card.

File: packages/grafana-ui/src/components/Card/Card.tsx (hunk 1 above)
Comment (Clarity-89) [reply packages/grafana-ui/src/components/Card/Card.tsx:265]: I've made a fix for this here: https://github.com/grafana/grafana/pull/32702

Comment (thisisobate) [reply packages/grafana-ui/src/components/Card/Card.tsx:265]: oh wow...Thanks alot! @Clarity-89 
Your solution is quite simple and elegant; love it!
