### PR TITLE
fix(DashListItem): Improve click targets for dashboard list/card items

### LINKED ISSUE #114289: Dashboard List Panel: Row shows link hover state but clicking only works on text
### What happened?

When viewing dashboards in the list, the entire row shows a hand cursor, the link gets underlined, and turns blue on hover — but the link is only actually clickable when clicking directly on the text.
Clicking anywhere else in the row (even though it shows the link hover styling) does not open the dashboard.
This did work in previous Grafana versions.

### What did you expect to happen?

If the entire row displays link hover styling (hand icon, underline, blue text), clicking anywhere within the row should open the dashboard — as it did before.

### Did this work before?

Yes, in previous Grafana versions.

### How do we reproduce it?

/

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 12.3.0
OS: Windows 11
Browser: Chrome

### Grafana platform?

A downloaded binary

### Datasource(s)?

_No response_

### LINKED ISSUE #115929: Dashlist panel: hover area link too big
### What happened?

https://youtu.be/uofrOelEu_c?si=f6kOXRDk1XJ81xfn

### What did you expect to happen?

The `<a>` element is wrapped in a div, not sure what's the intention here, but it looks like it should redirect to a page via highlighting and cursor type, but it doesn't. I think previously the behavior was that you could click outside of the text itself (either way will probably do, but the behavior now is inconsistent)

### Did this work before?

I think it did, but I don't have time to downgrade to older grafana. Noticed this the day I upgraded it from 12.1 to Grafana v12.3.1 (0d1a5b4420)

### How do we reproduce it?

1. Create a dashboard
2. Use it
3. It should pop up in recently used list

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: Grafana v12.3.1 (0d1a5b4420) 
OS: win 11 
Browser: Chrome Version 143.0.7499.170 (Official Build) (64-bit)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by MattIPv4**
**What is this feature?**

This changes the `DashListItem` component to have a larger `a` click target, while also ensuring the hover styling only provides visual feedback when the user is actually hovering on the click target.

| Before | After |
|-|-|
| image | image |
| image | image |

**Why do we need this feature?**

`DashListItem` applied hover styling to the outer container, while the actual `a` click target was a much smaller portion of the component, leading to visual feedback that the user could click when they couldn't. As an example, you could hover over the folder name in both views, which would show styling for the component as if you were hovering over the link, but clicking did nothing -- this now works with this PR.

**Who is this feature for?**

All users.

**Which issue(s) does this PR fix?**:

Fixes #115929

Fixes #114289

Closes #116257

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/panel/dashlist/styles.ts [hunk 1]
```diff
@@ -11,39 +11,55 @@ export const getStyles = (theme: GrafanaTheme2) => {
...
       flexDirection: 'column',
-      '&:hover a': {
-        color: theme.colors.text.link,
-        textDecoration: 'underline',
-      },
       height: '100%',
       paddingTop: theme.spacing(1.5),
 
-      '&:hover': {
+      '&:has(a:hover)': {
```
Comment (MattIPv4) [inline public/app/plugins/panel/dashlist/styles.ts:37]: `:has()` is baseline now. If loaded on an older browser, the card just won't get the background on hover, so doesn't seem like this introduces a compatibility issue.

File: public/app/plugins/panel/dashlist/DashListItem.tsx [hunk 2]
```diff
@@ -62,34 +62,26 @@ export function DashListItem({
...
-            {showFolderNames && locationInfo && (
-              <Stack alignItems="start" direction="row" gap={0.5} height="25%">
-                <Icon name="folder" size="sm" className={css.dashlistCardIcon} aria-hidden="true" />
-                <Text color="secondary" variant="bodySmall" element="p">
-                  {locationInfo?.name}
-                </Text>
-              </Stack>
-            )}
+              {showFolderNames && locationInfo && (
+                <Stack alignItems="start" direction="row" gap={0.5} height="25%">
```
Comment (MattIPv4) [inline public/app/plugins/panel/dashlist/DashListItem.tsx]: Fwiw, I'm not sure what the intent is behind this `height="25%"`, it seems to result in the folder information clipping beyond its container, but it was here before so I've left it as-is for now.

Comment (ywzheng1) [reply public/app/plugins/panel/dashlist/DashListItem.tsx]: i have [another PR](https://github.com/grafana/grafana/pull/116450/changes#diff-5f2280019c5dc32076c98df25f022b2b96e2558d89246559735f20e66b6264ddR80-R90) here to change this `25%`

Comment (MattIPv4) [reply public/app/plugins/panel/dashlist/DashListItem.tsx]: Ah, nice! I'm happy to let you land that first if you want, and can then rebase this.

Comment (ywzheng1) [reply public/app/plugins/panel/dashlist/DashListItem.tsx]: That would be great, my PR should merge very soon. Hope I won’t block you for long!

**Comment by ywzheng1** [comment]
For reference purpose, we have an OSS ticket asking for something similar: https://github.com/grafana/grafana/issues/115929

File: public/app/plugins/panel/dashlist/DashListItem.tsx (hunk 2 above)
Comment (ywzheng1) [reply public/app/plugins/panel/dashlist/DashListItem.tsx]: its merged! 😅 and caused some conflicts

**Review by ywzheng1 — APPROVED** [review]
🚀
