### PR TITLE
Alerting: Remove url based external alertmanagers config

### LINKED ISSUE #57724: Alerting: Remove URL-based configuration in External Alertmanagers
**What happened:**

We added a new, better, and more complete way to manage the alert sending to external alertmangers and deprecated the old URL-base way.

Before

**What you expected to happen:**

- Not to be able to add URL-based external alertmanagers anymore. Code removal.
- Old URL-based imported alertmanagers to be available as new data sources. Requires data migration.

After

**How to reproduce it (as minimally and precisely as possible):**

Go to Alerting -> Admin tab -> Scroll all the way down.

**Anything else we need to know?:**

**Environment:**
- Grafana version: 9.2.2

### PR DESCRIPTION
**Pull request by alexmobo**
**What is this feature?**

Removes old URL-based configuration in external alertmanagers admin configuration page.
It also migrates old configurations to alertmanager `DataSource`s with the `Receive Grafana Alerts` toggle toggled.

**Why do we need this feature?**

To force customers to start using alertmanager data sources as they are more configurable.

**Who is this feature for?**

All users.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/57724

### CODE REVIEW

**Comment by grobinson-grafana** [comment]
Hi! :wave: Should I wait before reviewing this? I built Grafana from this PR but still see the old UI, should I assume this is still work-in-progress?
 
Screenshot 2022-11-03 at 09 39 54

**Comment by alexmobo** [comment]
> Hi! 👋 Should I wait before reviewing this? I built Grafana from this PR but still see the old UI, should I assume this is still work-in-progress?
> 
> Screenshot 2022-11-03 at 09 39 54

I don't see the old UI. Maybe the browser cache?

**Comment by grobinson-grafana** [comment]
I think I had checked out an older commit :( Thanks!

File: pkg/services/sqlstore/migrations/ualert/ualert.go [hunk 1]
```diff
@@ -876,3 +879,104 @@ func (c updateRulesOrderInGroup) Exec(sess *xorm.Session, migrator *migrator.Mig
...
+		}
+	}
+
+	return nil
+}
+func generateNewDatasourceUid(sess *xorm.Session, orgId int64) (string, error) {
+	for i := 0; i < 3; i++ {
+		uid := util.GenerateShortUID()
+
+		exists, err := sess.Table("ngalert_configuration").Where("org_id = ?", uid, orgId).Exist()
```
Comment (grobinson-grafana) [inline pkg/services/sqlstore/migrations/ualert/ualert.go:971]: I think this the `Where("org_id = ?", uid, orgId).Exist()` is invalid, I get the following error:

```
error: migration failed (id = migrate external alertmanagers to datsourcse): pq: got 2 parameters but the statement requires 1
```

**Review by grobinson-grafana — CHANGES_REQUESTED** [review]

File: pkg/services/sqlstore/migrations/ualert/ualert.go (hunk 1 above)
Comment (alexmobo) [reply pkg/services/sqlstore/migrations/ualert/ualert.go:971]: oh, I thought that was fixed. Let me fix it. Sorry about the mess

Comment (alexmobo) [reply pkg/services/sqlstore/migrations/ualert/ualert.go]: It should be fixed

File: pkg/services/ngalert/api/tooling/definitions/admin.go [hunk 2]
```diff
@@ -76,13 +76,11 @@ const (
 
 // swagger:model
```
Comment (alexweav) [inline pkg/services/ngalert/api/tooling/definitions/admin.go:77]: Since we touched some of the Swagger models, we'll need to regenerate the OpenAPI docs to uptake these changes. Check the README and makefile in this directory: https://github.com/grafana/grafana/tree/main/pkg/services/ngalert/api/tooling

File: pkg/services/ngalert/models/admin_configuration_test.go [hunk 3]
```diff
@@ -2,62 +2,11 @@ package models
 
 import (
 	"errors"
-	"fmt"
 	"testing"
 
 	"github.com/stretchr/testify/require"
 )
 
-func TestAdminConfiguration_AsSHA256(t *testing.T) {
```
Comment (alexweav) [inline pkg/services/ngalert/models/admin_configuration_test.go:11]: It seems we moved some of the redaction code to `router.go`, but only deleted the tests. Even though it's only used for logs now, could we still add a corresponding test on `buildRedactedAMs` in `router_test.go`? That way we at least have some extra protection around accidentally logging sensitive info in URLs there.

File: pkg/services/sqlstore/migrations/ualert/ualert.go [hunk 4]
```diff
@@ -876,3 +879,104 @@ func (c updateRulesOrderInGroup) Exec(sess *xorm.Session, migrator *migrator.Mig
 	}
 	return nil
 }
+
+func AddExternalAlertmanagerToDatasourceMigration(mg *migrator.Migrator) {
```
Comment (alexweav) [inline pkg/services/sqlstore/migrations/ualert/ualert.go:883]: Could we implement this migration in a separate file or package, rather than appending it to the `ualert.go` migration file?

The vast majority of the code in `ualert.go` is around the Legacy Alerting -> Unified Alerting migration. It's not meant to be an umbrella package for all alerting-related migrations, rather most of this code is one very big migration that already happened and should be "frozen" unless we are fixing a bug in that area.

File: pkg/services/sqlstore/migrations/ualert/ualert.go [hunk 5]
```diff
@@ -876,3 +879,104 @@ func (c updateRulesOrderInGroup) Exec(sess *xorm.Session, migrator *migrator.Mig
...
+
+func (e externalAlertmanagerToDatasources) Exec(sess *xorm.Session, mg *migrator.Migrator) error {
+	var results []AdminConfiguration
+	err := sess.SQL("SELECT org_id, alertmanagers FROM ngalert_configuration").Find(&results)
+	if err != nil {
+		return err
+	}
+
+	for _, result := range results {
+		for _, am := range result.Alertmanagers {
```
Comment (alexweav) [inline pkg/services/sqlstore/migrations/ualert/ualert.go:917]: Should we do some kind of deduplication on the URL? If a system has two configured alertmanagers with exactly the same URL/credentials, should we collapse them into one datasource?

I ask because we've had duplication bugs with alertmanagers in the past. There are definitely still instances floating around with many duplicated URLs in this list.

**Review by alexweav — COMMENTED** [review]
Looking good, few nits/questions. I did not review the frontend code.

File: pkg/services/ngalert/api/tooling/definitions/admin.go (hunk 2 above)
Comment (alexmobo) [reply pkg/services/ngalert/api/tooling/definitions/admin.go:77]: Thanks

File: pkg/services/sqlstore/migrations/ualert/ualert.go [hunk 6]
```diff
@@ -876,3 +879,104 @@ func (c updateRulesOrderInGroup) Exec(sess *xorm.Session, migrator *migrator.Mig
...
+
+func AddExternalAlertmanagerToDatasourceMigration(mg *migrator.Migrator) {
+	mg.AddMigration("migrate external alertmanagers to datsourcse", &externalAlertmanagerToDatasources{})
+}
+
+type externalAlertmanagerToDatasources struct {
+	migrator.MigrationBase
+}
+
+// Just copy old struct code to use Alertmanagers as new one is not getting it.
```
Comment (grobinson-grafana) [inline pkg/services/sqlstore/migrations/ualert/ualert.go:891]: What does this mean? 😄

File: pkg/services/sqlstore/migrations/ualert/ualert.go (hunk 5 above)
Comment (grobinson-grafana) [reply pkg/services/sqlstore/migrations/ualert/ualert.go:917]: I agree, and think we should deduplicate on the URL. I just checked and neither the UI or API deduplicated external Alertmanagers.

File: pkg/services/sqlstore/migrations/ualert/ualert.go [hunk 7]
```diff
@@ -876,3 +879,104 @@ func (c updateRulesOrderInGroup) Exec(sess *xorm.Session, migrator *migrator.Mig
...
+		return err
+	}
+
+	for _, result := range results {
+		for _, am := range result.Alertmanagers {
+			u, err := url.Parse(am)
+			if err != nil {
+				return err
+			}
+			uri := fmt.Sprintf("%s://%s", u.Scheme, u.Host)
```
Comment (grobinson-grafana) [inline pkg/services/sqlstore/migrations/ualert/ualert.go:922]: What about the port and path?

File: pkg/services/sqlstore/migrations/ualert/ualert.go [hunk 8]
```diff
@@ -876,3 +879,104 @@ func (c updateRulesOrderInGroup) Exec(sess *xorm.Session, migrator *migrator.Mig
...
+		}
+	}
+
+	return nil
+}
+func generateNewDatasourceUid(sess *xorm.Session, orgId int64) (string, error) {
+	for i := 0; i < 3; i++ {
+		uid := util.GenerateShortUID()
+
+		exists, err := sess.Table("data_source").Where("uid = ? AND org_id = ?", uid, orgId).Exist()
```
Comment (grobinson-grafana) [inline pkg/services/sqlstore/migrations/ualert/ualert.go:971]: If `exists` is false after three attempts won't this return `"", nil`?

**Review by grobinson-grafana — CHANGES_REQUESTED** [review]

File: pkg/services/ngalert/models/admin_configuration_test.go (hunk 3 above)
Comment (alexmobo) [reply pkg/services/ngalert/models/admin_configuration_test.go:11]: Of course

File: pkg/services/sqlstore/migrations/ualert/ualert.go (hunk 5 above)
Comment (alexmobo) [reply pkg/services/sqlstore/migrations/ualert/ualert.go]: Yes! Your point is correct

File: pkg/services/sqlstore/migrations/ualert/ualert.go (hunk 6 above)
Comment (alexmobo) [reply pkg/services/sqlstore/migrations/ualert/ualert.go]: I needed to copy the old AdminConficuration struct as the new one has not the attribute `Alertmanagers []string` defined in it anymore.

File: pkg/services/sqlstore/migrations/ualert/ualert.go (hunk 7 above)
Comment (alexmobo) [reply pkg/services/sqlstore/migrations/ualert/ualert.go]: `u.Host` already includes the port but you are right about the path. Someone could have a reverse proxy pointing to an AM url.

File: pkg/services/sqlstore/migrations/ualert/ualert.go (hunk 8 above)
Comment (alexmobo) [reply pkg/services/sqlstore/migrations/ualert/ualert.go]: If it is `false`, it will return a valid uid on the first attempt, right? Am I missing something?

File: public/app/features/alerting/unified/components/admin/ExternalAlertmanagerDataSources.tsx [hunk 9]
```diff
@@ -18,7 +18,7 @@ export function ExternalAlertmanagerDataSources({ alertmanagers, inactive }: Ext
 
   return (
     <>
-      <h5>Alertmanagers data sources</h5>
+      <h5>Alertmanagers Receiving Grafana-managed alerts</h5>
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/admin/ExternalAlertmanagerDataSources.tsx:21]:
```suggestion
      <h5>Alertmanagers receiving Grafana-managed alerts</h5>
```

**Review by gillesdemey — CHANGES_REQUESTED** [review]
Before merging I think we'll need some assistance from @brendamuir to make sure the documentation is up-to-date and contains the right information to help users configure external AlertManagers for Grafana managed rules.

File: pkg/services/sqlstore/migrations/ualert/ualert.go (hunk 8 above)
Comment (grobinson-grafana) [reply pkg/services/sqlstore/migrations/ualert/ualert.go]: Apologies, I mean if `exists` is `true` after three attempts

Comment (alexmobo) [reply pkg/services/sqlstore/migrations/ualert/ualert.go]: If `exists` is `true` after 3 attempts it will `return "", datasources.ErrDataSourceFailedGenerateUniqueUid`.

I am failing to see your point. The only thing we can do here, AFAIK, is to raise the number of attempts. right?

Comment (grobinson-grafana) [reply pkg/services/sqlstore/migrations/ualert/ualert.go]: Ah apologies, I somehow misread the return at the end of the function.

File: pkg/services/sqlstore/migrations/external_alertmanagers.go [hunk 10]
```diff
@@ -0,0 +1,132 @@
...
+	UpdatedAt int64 `xorm:"updated"`
+}
+
+func (e externalAlertmanagerToDatasources) SQL(dialect migrator.Dialect) string {
+	return "migrate external alertmanagers to datasource"
+}
+
+func (e externalAlertmanagerToDatasources) Exec(sess *xorm.Session, mg *migrator.Migrator) error {
+	var results []AdminConfiguration
+	err := sess.SQL("SELECT org_id, alertmanagers FROM ngalert_configuration").Find(&results)
```
Comment (grobinson-grafana) [inline pkg/services/sqlstore/migrations/external_alertmanagers.go:46]: It might be nice to keep the timestamps of the original, what do we think?

**Review by grobinson-grafana — COMMENTED** [review]
Looks good to me, @alexweav?

File: pkg/services/sqlstore/migrations/external_alertmanagers.go (hunk 10 above)
Comment (alexmobo) [reply pkg/services/sqlstore/migrations/external_alertmanagers.go:46]: Great catch

**Comment by grobinson-grafana** [comment]
Looks good to me! I want to test it this afternoon before I approve! 🙂

**Review by grobinson-grafana — APPROVED** [review]

**Comment by alexweav** [comment]
Looking good to me as well. I'll defer to @gillesdemey on the frontend code, backend looks good!

**Review by gillesdemey — APPROVED** [review]
Amazing work, LGTM – no blockers! 🚀
