### PR TITLE
Geomap: Improve tooltip UX and fix data links

### LINKED ISSUE #43937: Geomap data links don't work
Grafana 8.3.0, self hosted, open source

When setting a data-link in the Geomap panel, I expect map markers to become clickable as per the data link. However, the map markers are not clickable and there is no link.

### PR DESCRIPTION
**Pull request by nmarrs**
**What this PR does / why we need it**:
Improve geomap tooltip UX to allow user to select / view multiple layers of data. Fix data link functionality as part of this revamp of geomap tooltip.

Before

https://user-images.githubusercontent.com/22381771/152064017-b658a0f5-b6ae-4cc8-9bc4-04cfb9db23a9.mov

After

https://user-images.githubusercontent.com/22381771/152062729-3f57ca45-a964-43a1-9463-40e2a8358678.mov

**Which issue(s) this PR fixes**:

Fixes #43937

### CODE REVIEW

File: public/app/plugins/panel/geomap/components/ComplexDataHoverView.tsx [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+export interface Props {
+  layers?: GeomapLayerHover[];
+  isOpen: boolean;
+  onClose: () => void;
+}
+
+export const ComplexDataHoverView = ({ layers, onClose, isOpen }: Props) => {
+  const [activeTabIndex, setActiveTabIndex] = useState<number>(0);
+
```
Comment (ryantxu) [inline public/app/plugins/panel/geomap/components/ComplexDataHoverView.tsx:16]:
```suggestion
if (!layers) {
  return null
}
```
we can avoid some nesting below

File: public/app/plugins/panel/geomap/components/DataHoverRows.tsx [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+                    <DataHoverRow key={key} feature={feature} />
+                  );
+                })}
+              </div>
+            </div>
+          )
+      )) ??
+    null;
+
+  return <TabContent>{rows}</TabContent>;
```
Comment (ryantxu) [inline public/app/plugins/panel/geomap/components/DataHoverRows.tsx:58]: maybe inline?  we already check that layers exists
```suggestion
  return <TabContent>{layers.map( ...) }</TabContent>;
```

File: public/app/plugins/panel/geomap/components/DataHoverTabs.tsx [hunk 3]
```diff
@@ -0,0 +1,29 @@
+import React, { Dispatch, SetStateAction } from 'react';
+import { Tab, TabsBar } from '@grafana/ui';
+
+import { GeomapLayerHover } from '../event';
+
+type Props = {
+  layers?: GeomapLayerHover[];
```
Comment (ryantxu) [inline public/app/plugins/panel/geomap/components/DataHoverTabs.tsx:7]:
```suggestion
  layers: GeomapLayerHover[];
```
and avoid null check?

File: public/app/plugins/panel/geomap/components/DataHoverView.tsx [hunk 4]
```diff
@@ -1,85 +1,100 @@
...
-import { config } from 'app/core/config';
-import { FeatureLike } from 'ol/Feature';
 import { SortOrder } from '@grafana/schema';
 
+import { GeomapLayerHover } from '../event';
+
 export interface Props {
   data?: DataFrame; // source data
-  feature?: FeatureLike;
+  layers?: GeomapLayerHover[];
```
Comment (ryantxu) [inline public/app/plugins/panel/geomap/components/DataHoverView.tsx:19]:
```suggestion

```

can we remove this?  I think we now force everything to frame before passing it in

**Review by ryantxu — APPROVED** [review]
looks good!  a bit more cleanup then :ship:
