### PR TITLE
Analytics: Instrument Azure Application Insights

### LINKED ISSUE #38552: Analytics: Instrument Azure Application Insights
### Discussed in https://github.com/grafana/grafana/discussions/38545

<div type='discussions-op-text'>

<sup>Originally posted by **sunker** August 25, 2021</sup>
**What I'd like to do**
Add support for instrumenting Application Insights with events coming from the Grafana frontend. This should be an opt-in feature that can be configured in grafana.ini. 

**What is Application Insights?**
Azure Application Insights an Application Performance Management system that can be used to monitor live applications. By installing an instrumentation script on the web client, it allows you to ingest application / analytics data into the Application Insights data base. 

**How?**
We should use the [EchoSrv](https://github.com/grafana/grafana/blob/main/packages/grafana-runtime/src/services/EchoSrv.ts) to collect frontend events and create a new backend implementation for Application Insights, similar to how this is already done for Google Analytics and Rudderstack. 

An instrumentation key is required to initialize the Application Insights instrumentation script. This should be a configured in [grafana.ini](https://grafana.com/docs/grafana/latest/administration/configuration/#analytics). 

The Application Insights api has the following actions:
```javascript
appInsights.trackEvent({name: 'some event'});
appInsights.trackPageView({name: 'some page'});
appInsights.trackPageViewPerformance({name : 'some page', url: 'some url'});
appInsights.trackException({exception: new Error('some error')});
appInsights.trackTrace({message: 'some trace'});
appInsights.trackMetric({name: 'some metric', average: 42});
appInsights.trackDependencyData({absoluteUrl: 'some url', responseCode: 200, method: 'GET', id: 'some id'});
appInsights.startTrackPage("pageName");
appInsights.stopTrackPage("pageName", null, {customProp1: "some value"});
appInsights.startTrackEvent("event");
appInsights.stopTrackEvent("event", null, {customProp1: "some value"});
```

Currently, the EchoSrv collects page view events (would map to  `appInsights.trackPageView({name: 'some page'});`) and interaction events (would map to `appInsights.trackEvent({name: 'some event'});`). I doubt Application Insights would need to track other types of events than that, but if so we'll have to add new mechanisms for that. Tracking exceptions for example, shouldn't be so hard to do. 

Feedback appreciated. cc @daniellee @dprokop </div>

### PR DESCRIPTION
**Pull request by sunker**
**What this PR does / why we need it**:
This PR makes it possible to pass tracking events from the Grafana frontend to Azure Application Insights. This feature is not enabled by default. To start ingesting data to Application Insights, an instrumentation key must first be added to the Grafana configuration file. 

**Which issue(s) this PR fixes**:
Fixes #38552

### CODE REVIEW

File: pkg/setting/setting.go [hunk 1]
```diff
@@ -367,6 +367,7 @@ type Cfg struct {
 	CheckForUpdates      bool
 	ReportingDistributor string
 	ReportingEnabled     bool
+	ApplicationInsightsInstrumentationKey string
```
Comment (dprokop) [inline pkg/setting/setting.go:370]: Uber nit: can we place it together with other tracking services keys? Meaning line 146 :)

**Review by dprokop — APPROVED** [review]
Looks good to me @sunker 👍

File: public/app/core/services/echo/backends/analytics/ApplicationInsightsBackend.ts [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+
+  constructor(public options: ApplicationInsightsBackendOptions) {
+    $.ajax({
+      url: 'https://js.monitor.azure.com/scripts/b/ai.2.min.js',
+      dataType: 'script',
+      cache: true,
+    }).done(function () {
+      var applicationInsightsOpts = {
+        config: {
+          instrumentationKey: options.instrumentationKey,
```
Comment (yuwaMSFT2) [inline public/app/core/services/echo/backends/analytics/ApplicationInsightsBackend.ts:19]: It seems there is recommendation to use connectionString instead of instrumentationKey. 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript#adding-the-javascript-sdk

File: pkg/setting/setting.go (hunk 1 above)
Comment (sunker) [reply pkg/setting/setting.go:370]: Thanks for feedback! In theory I agree, but I think all the variables above are global, and the idea is that we're suppose to use the `Cfg` struct instead.

File: public/app/core/services/echo/backends/analytics/ApplicationInsightsBackend.ts (hunk 2 above)
Comment (sunker) [reply public/app/core/services/echo/backends/analytics/ApplicationInsightsBackend.ts:19]: I'll fix!

File: public/app/core/services/echo/backends/analytics/ApplicationInsightsBackend.ts [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+
+  constructor(public options: ApplicationInsightsBackendOptions) {
+    $.ajax({
+      url: 'https://js.monitor.azure.com/scripts/b/ai.2.min.js',
+      dataType: 'script',
+      cache: true,
+    }).done(function () {
+      var applicationInsightsOpts = {
+        config: {
+          connectionString: options.connectionString,
```
Comment (avidhanju) [inline public/app/core/services/echo/backends/analytics/ApplicationInsightsBackend.ts:19]: Is it possible to add another config option for endpointUrl to be set from the Grafana config? Different Azure clouds need to be configured with different data collection endpoints. More info here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-endpoints?tabs=js

Comment (sunker) [reply public/app/core/services/echo/backends/analytics/ApplicationInsightsBackend.ts:20]: Sure, I just pushed some changes. Please take another look

**Review by achatterjee-grafana — COMMENTED** [review]
Added doc review.

**Comment by sunker** [comment]
> Added doc review.

For some reason I'm not able to see your comments @achatterjee-grafana. Might be because I force pushed. Would you mind re-doing the review? Sorry :(

File: docs/sources/administration/configuration.md [hunk 4]
```diff
@@ -460,6 +460,14 @@ Analytics ID here. By default this feature is disabled.
 
 Google Tag Manager ID, only enabled if you enter an ID here.
 
+### application_insights_connection_string
+
+If you want to track Grafana usage via Azure Application Insights, specify _your_ Application Insights connection string here. Since the connection string contains semicolons, you need to wrap it in backticks (`). By default this feature is disabled.
+
+### application_insights_endpoint_url
+
+Optionally, you can override the default endpoint address for Application Insights data collecting. For details, please refer to the [official documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-endpoints?tabs=js) in Azure.
```
Comment (achatterjee-grafana) [inline docs/sources/administration/configuration.md:469]:
```suggestion
If you want to track Grafana usage via Azure Application Insights, then specify _your_ Application Insights connection string. Since the connection string contains semicolons, you need to wrap it in backticks (`). By default, tracking usage is disabled.
		
### application_insights_endpoint_url
		Optionally, use this option to override the default endpoint address for Application Insights data collecting. For details,  refer to the [Azure documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-endpoints?tabs=js).
```

File: conf/defaults.ini [hunk 5]
```diff
@@ -202,6 +202,12 @@ rudderstack_write_key =
 # Rudderstack data plane url, enabled only if rudderstack_write_key is also set
 rudderstack_data_plane_url =
 
+# Application Insights connection string, only enabled if you specify a string here
+application_insights_connection_string =
+
+# Optionally specify an Application Insights endpoint url. If an endpoint is specified, the string must we wrapped in backticks ``.
```
Comment (achatterjee-grafana) [inline conf/defaults.ini:208]:
```suggestion
# Optional. Specifies an Application Insights endpoint URL where the endpoint string is wrapped in backticks ``. 
```

File: conf/defaults.ini [hunk 6]
```diff
@@ -202,6 +202,12 @@ rudderstack_write_key =
 # Rudderstack data plane url, enabled only if rudderstack_write_key is also set
 rudderstack_data_plane_url =
 
+# Application Insights connection string, only enabled if you specify a string here
```
Comment (achatterjee-grafana) [inline conf/defaults.ini:205]:
```suggestion
# Application Insights connection string. Specify an URL string to enable this feature.
```

**Review by achatterjee-grafana — COMMENTED** [review]
Added doc review.
