### PR TITLE
Annotations: Fix annotation autocomplete causing panels to crash

### LINKED ISSUE #50928: Grafana 9.0.0: autocomplete annotation tags
**What happened**:
When I try to create a new annotation in a metric and type (autocomplete) for the proper tag, the interface launch an error.
Screenshot from 2022-06-16 10-47-46

**What you expected to happen**:
In version 8.5.2 the annotation tag is autocomplete 

**How to reproduce it (as minimally and precisely as possible)**:
In a dashboard annotated with tags, try to create a new annotation and when the tag is searched may raise the error, in my case always the error is raised

**Anything else we need to know?**:
Error raised in file https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/utils/tags.ts Line:70
Maybe one value undefined is passed to this function?

**Environment**:
- Grafana version: OSS 9.0.0
- Data source type & version: Prometheus 2.36.0
- OS Grafana is installed on: Amazon Linux 2, binary .tar.gz
- User OS & Browser: Chrome Linux
- Grafana plugins: Default
- Others: Grafana configuration database, postgres

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- https://github.com/grafana/grafana/pull/47796 updated our default `formatCreateLabel` to return a `React.ReactNode` instead of a string.
- this causes [`name.toLowerCase()`](https://github.com/grafana/grafana/blob/ash/50928/packages/grafana-ui/src/utils/tags.ts#L70) to blow up because the `TagFilter` used in `AnnotationEditorForm` doesn't set a `formatCreateLabel`: https://github.com/grafana/grafana/blob/ash/50928/public/app/plugins/panel/timeseries/plugins/annotations/AnnotationEditorForm.tsx#L100
- set a default (simpler) `formatCreateLabel` in `TagFilter` which returns a string to make sure the util functions work correctly.

fyi @torkelo i'm not sure of the best solution here... somewhere the types from `react-select` are incorrect, because it says this should only ever be a string, but it can definitely be a `React.ReactNode`. this fixes the immediate crash at least. 

**Which issue(s) this PR fixes**:

Fixes #50928 

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/core/components/TagFilter/TagFilter.tsx [hunk 1]
```diff
@@ -40,7 +40,7 @@ const filterOption = (option: any, searchQuery: string) => {
 
 export const TagFilter: FC<Props> = ({
   allowCustomValue = false,
-  formatCreateLabel,
+  formatCreateLabel = (input: string) => `Use custom value: ${input}`,
```
Comment (torkelo) [inline public/app/core/components/TagFilter/TagFilter.tsx:43]:
```suggestion
  formatCreateLabel = (input: string) => (<span>Add tag</span> <TagBadge label={label} removeIcon={false} />),
```

Maybe something like that is better? but then it wont solve the bug. 

Maybe in the TagOption component we check if label is not string we just return label (instead of the markup )

Comment (ashharrison90) [reply public/app/core/components/TagFilter/TagFilter.tsx:43]: > Maybe in the TagOption component we check if label is not string we just return label (instead of the markup )

@torkelo that would look like:
| before | after |
| --- | --- |
| image | image |

we lose the tag colour on the creatable option... i don't mind too much tbh, think it looks fairly clean still and the code is nicer that way. @grafana/user-essentials any thoughts? 🤔

Comment (torkelo) [reply public/app/core/components/TagFilter/TagFilter.tsx:43]: yea, that works pretty well (after)

Comment (axelavargas) [reply public/app/core/components/TagFilter/TagFilter.tsx]: 🤔 just to double-check,  we had this "use custom value" because we support the usage of template variables, as the documentation explains:

> In Grafana v5.3+ it’s possible to use template variables in the tag query. So if you have a dashboard showing stats for different services and a template variable that dictates which services to show, you can now use the same template variable in your annotation query to only show annotations for those services.

Does this mean we are removing that?

https://user-images.githubusercontent.com/239999/175044605-73398f77-b690-472f-a089-75a293ad77a7.mp4

Comment (ashharrison90) [reply public/app/core/components/TagFilter/TagFilter.tsx]: @axelavargas yes, we support custom values so you can use template variables

> Does this mean we are removing that?

no - this PR means the styling has changed (see the `Hit enter to add` bit). the bug you're seeing where it doesn't actually get added is https://github.com/grafana/grafana/issues/51171, which was caused by refactoring the `TagFilter` component 😞

**Review by axelavargas — APPROVED** [review]
🚀 ready to go! great job Mr. Harrison 😎
