### PR TITLE
Sandbox: Fix monaco editor custom languages not working correctly inside the sandbox

### LINKED ISSUE #72669: Fix regexes behaving differently inside the sandbox. Relevant for custom languages in monaco editor.

### PR DESCRIPTION
**Pull request by academo**
**What is this feature?**

Patches MonacoEditor inside the sandbox to fix custom languages syntax highlight not working inside the sandbox

**Why do we need this feature?**

If this monaco editor function is not patched the syntax highlighting inside plugins that have their own custom language definition won't work

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/72669

**Special notes for your reviewer:**

# Performance?

The patched function is rarely used inside plugins and if used it is strictly used once per custom language definition. Most plugins don't define a custom language and if they do they define a single one thus a performance impact is not expected with this additional distortion

### CODE REVIEW

File: public/app/features/plugins/sandbox/distortion_map.ts [hunk 1]
```diff
@@ -456,3 +460,48 @@ function distortDocument(distortions: DistortionMap) {
...
 }
+
+async function distortMonacoEditor(distortions: DistortionMap) {
+  // We rely on `monaco` being instanciated inside `window.monaco`.
+  // this is the same object passed down to plugins using monaco editor for their editors
+  // this `window.monaco` is an instance of monaco but not the same as if we
+  // import `monaco-editor` directly in this file.
+  // Short of abusing the `window.monaco` object we would have to modify grafana-ui to export
+  // the monaco instance directly in the ReactMonacoEditor component
+  const monacoEditor: Monaco = Reflect.get(window, 'monaco');
```
Comment (jackw) [inline public/app/features/plugins/sandbox/distortion_map.ts:471]: Something for the future... I believe that if we move monaco editor to load via ESM no globals are created which would make this undefined. I don't think it should block us from merging this but certainly something we need to consider. @aangelisc looping you in so you're aware.

**Review by jackw — APPROVED** [review]
LGTM! 🚀

File: public/app/features/plugins/sandbox/distortion_map.ts (hunk 1 above)
Comment (aangelisc) [reply public/app/features/plugins/sandbox/distortion_map.ts:471]: I think once we're ready to move Monaco to ESM we can move the `monaco-kusto` package to also load via ESM which should *hopefully* make our problems go away.
