### PR TITLE
Frontend o11y: Load SharedWorkers for crash detection

### LINKED ISSUE #96672: Frontend o11y: Load SharedWorkers for crash detection
Follow-up after https://github.com/grafana/grafana/issues/94678. SharedWorkers need to be loaded via `blob` (like regular web workers) so we can load them from an external domain. We should also check if they are available in browser (some mobile browsers don't support it)

### PR DESCRIPTION
**Pull request by ifrost**
Fixes [#96672](https://github.com/grafana/grafana/issues/96672). 

This is a follow-up after https://github.com/grafana/grafana/issues/94678. SharedWorkers need to be loaded via blob (like regular web workers) so we can load them from an external domain. We should also check if they are available in browser (some mobile browsers don't support it)

### CODE REVIEW

File: public/app/core/utils/CorsSharedWorker.ts [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+
+/**
+ * The base class is created dynamically here to allow later on syntax like:
+ * import { CorsSharedWorker as SharedWorker } from '../utils/CorsSharedWorker';
+ * And also take into account cases where SharedWorked is not available in the browser (mainly mobile browsers)
+ *
+ * It's important to use: new SharedWorker(...) syntax instead of new CorsSharedWorker(...) due to how web-workers
+ * are processing workers syntax (more details https://webpack.js.org/guides/web-workers/)
+ */
+const BaseSharedWorkerClass = sharedWorkersSupported() ? window.SharedWorker : SharedWorkerNotSupported;
```
Comment (joey-grafana) [inline public/app/core/utils/CorsSharedWorker.ts:26]: Not sure why we need to return a class with stub like values. How is it going to be used if the shared worker is not supported? Perhaps we can just return null because I'm really not sure how this is going to be handled in the `crashme` repo and it could change in the future leading to unexpected behaviour.

File: public/app/core/utils/CorsSharedWorker.ts [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+    const scriptsBasePathUrl = `${urlParts.join('/')}/`;
+
+    const importScripts = `importScripts('${scriptUrl}');`;
+    const objectURL = URL.createObjectURL(
+      new Blob([`__webpack_worker_public_path__ = '${scriptsBasePathUrl}'; ${importScripts}`], {
+        type: 'application/javascript',
+      })
+    );
+    super(objectURL, options);
+    URL.revokeObjectURL(objectURL);
```
Comment (joey-grafana) [inline public/app/core/utils/CorsSharedWorker.ts:50]: Could the revoke happen before the script has fully initialised?

File: public/app/core/utils/CorsSharedWorker.ts [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+    //    resulting public path: http://host.com/cdn/scripts
+
+    const scriptUrl = url.toString();
+    const urlParts = scriptUrl.split('/');
+    urlParts.pop();
+    const scriptsBasePathUrl = `${urlParts.join('/')}/`;
+
+    const importScripts = `importScripts('${scriptUrl}');`;
+    const objectURL = URL.createObjectURL(
+      new Blob([`__webpack_worker_public_path__ = '${scriptsBasePathUrl}'; ${importScripts}`], {
```
Comment (joey-grafana) [inline public/app/core/utils/CorsSharedWorker.ts:45]: This could break in environments not using Webpack or with different build configurations. I'm not 100% sure how reliable it is to depend on __webpack_worker_public_path__ being available?

File: public/app/core/utils/CorsSharedWorker.ts [hunk 4]
```diff
@@ -0,0 +1,52 @@
+// Almost identical to CorsWorker.ts. Main difference being it allows loading a SharedWorker if browser supports it
+
+export function sharedWorkersSupported() {
+  return typeof window.SharedWorker !== 'undefined';
+}
+
+class SharedWorkerNotSupported implements SharedWorker {
+  onerror() {}
+  // @ts-ignore
```
Comment (joey-grafana) [inline public/app/core/utils/CorsSharedWorker.ts:9]: Might lead to runtime issue as it does not have value

File: public/app/core/utils/CorsSharedWorker.ts [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+    //    initial worker chunk: http://host.com/cdn/scripts/worker-123.js
+    //    resulting public path: http://host.com/cdn/scripts
+
+    const scriptUrl = url.toString();
+    const urlParts = scriptUrl.split('/');
+    urlParts.pop();
+    const scriptsBasePathUrl = `${urlParts.join('/')}/`;
+
+    const importScripts = `importScripts('${scriptUrl}');`;
+    const objectURL = URL.createObjectURL(
```
Comment (joey-grafana) [inline public/app/core/utils/CorsSharedWorker.ts:44]: Hmm this is a little concerning. Generating a blob and `objectURL` of type `application/javascript` from what looks like arbitrary urls seems like a risk. Do we have full control of the input urls and are sure they are sanitised? Where is the `objectURL` going to be executed?

**Review by joey-grafana — COMMENTED** [review]
I left a few comments but this is a fairly far-reaching change added into core Grafana so I would like someone from the frontend team (or someone with the experience in this area of the codebase) to take a look.

File: public/app/core/utils/CorsSharedWorker.ts (hunk 2 above)
Comment (ifrost) [reply public/app/core/utils/CorsSharedWorker.ts:50]: Shouldn't happen as importScripts [load scripts synchronously](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts). It just revokes the URL so at this point the content should be loaded. It works exactly the same way in `CorsWorker`

File: public/app/core/utils/CorsSharedWorker.ts (hunk 1 above)
Comment (ifrost) [reply public/app/core/utils/CorsSharedWorker.ts:26]: Thanks! Yes, I think we can do `class extends null` here instead 👍

File: public/app/core/utils/CorsSharedWorker.ts (hunk 5 above)
Comment (ifrost) [reply public/app/core/utils/CorsSharedWorker.ts:44]: This is exactly what we already do in `CorsWorker` class and is a workaround to load web workers from external domains. When calling `new Worker(...)` the browser [uses same-origin mode](https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-classic-worker-script). We create proxy/shell script (a blob) that loads the actual worker code via `importScripts()` which [uses CORS/CSP like a regular fetch](https://html.spec.whatwg.org/multipage/workers.html#worker-processing-model:fetching-scripts-perform-fetch)

File: public/app/core/utils/CorsSharedWorker.ts (hunk 4 above)
Comment (ifrost) [reply public/app/core/utils/CorsSharedWorker.ts:9]: As mentioned above, will try with `class extends null` when worker is not supported

File: public/app/core/crash/index.ts [hunk 6]
```diff
@@ -39,6 +45,10 @@ export function initializeCrashDetection() {
       return new Worker(new URL('./client.worker', import.meta.url));
     },
 
+    // Ignore that SharedWorker possibly does not implement window.SharedWorker
+    // It will be the case only if SharedWorker is not supported by the browser and
+    // in such case the code below won't run because we check sharedWorkersSupported above
+    // @ts-ignore
     createDetectorWorker(): SharedWorker {
       return new SharedWorker(new URL('./detector.worker', import.meta.url));
```
[the remark this answers is not in the document]
Comment (joshhunt) [reply public/app/core/crash/index.ts:53]: ranking for ignoring the type system, which we should really avoid doing, is `as` type assertion > `// @ts-expect-error` > `// @ts-ignore`

File: public/app/core/utils/CorsSharedWorker.ts [hunk 7]
```diff
@@ -0,0 +1,39 @@
...
+  constructor(url: URL, options?: WorkerOptions) {
+    // by default, worker inherits HTML document's location and pathname which leads to wrong public path value
+    // the CorsWorkerPlugin will override it with the value based on the initial worker chunk, ie.
+    //    initial worker chunk: http://host.com/cdn/scripts/worker-123.js
+    //    resulting public path: http://host.com/cdn/scripts
+
+    const scriptUrl = url.toString();
+    const urlParts = scriptUrl.split('/');
+    urlParts.pop();
+    const scriptsBasePathUrl = `${urlParts.join('/')}/`;
```
[the remark this answers is not in the document]
Comment (ifrost) [reply public/app/core/utils/CorsSharedWorker.ts:28]: I think it is! I wanted to keep it exactly the same as CorsWorker though to isolate what's being changed and avoid any edge cases being handled in a different way  🙈

File: public/app/core/utils/CorsSharedWorker.ts [hunk 8]
```diff
@@ -0,0 +1,39 @@
...
+ * import { CorsSharedWorker as SharedWorker } from '../utils/CorsSharedWorker';
+ * And also take into account cases where SharedWorked is not available in the browser (mainly mobile browsers)
+ *
+ * It's important to use: new SharedWorker(...) syntax instead of new CorsSharedWorker(...) due to how web-workers
+ * are processing workers syntax (more details https://webpack.js.org/guides/web-workers/)
+ */
+const BaseSharedWorkerClass = sharedWorkersSupported() ? window.SharedWorker : null;
+
+// @ts-ignore
+export class CorsSharedWorker extends BaseSharedWorkerClass {
```
Comment (joshhunt) [inline public/app/core/utils/CorsSharedWorker.ts:18]: `null` is not a valid constructor, and typescript is telling you this. This PR needs to not have `ts-ignore` in it.

File: public/app/core/crash/index.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (ifrost) [reply public/app/core/crash/index.ts]: `// @ts-ignore` removed

File: public/app/core/utils/CorsSharedWorker.ts (hunk 8 above)
Comment (ifrost) [reply public/app/core/utils/CorsSharedWorker.ts]: 👍  removed `// @ts-ignore` by implementing what @svennergr suggested above

**Review by jackw — COMMENTED** [review]
FYI - I've enabled the featureflag on the ephemeral instance for testing. Clicking around I can see it loads via chrome://inspect/#workers. 

image


I'm not particularly well versed in sharedworkers but the code LGTM.

**Comment by ifrost** [comment]
@joshhunt / @svennergr I've made changes based on your suggestions.

File: .betterer.results [hunk 9]
```diff
@@ -833,6 +833,9 @@ exports[`better eslint`] = {
       [0, 0, 0, "Do not re-export imported variable (\`TimeSeries\`)", "6"],
       [0, 0, 0, "Do not re-export imported variable (\`updateLegendValues\`)", "7"]
     ],
+    "public/app/core/crash/index.ts:5381": [
+      [0, 0, 0, "Do not use any type assertions.", "0"]
+    ],
```
Comment (joshhunt) [inline .betterer.results:838]: if we don't have a plan to remove this, instead using an eslint-ignore comment.

**Review by joshhunt — COMMENTED** [review]
I'm not enthusiastic that we're using `as` here, but I can see your reasoning for it.

Otherwise no objections from me 👍 . I'll leave final approval for @svennergr or someone else from your team 😌

File: public/app/core/crash/index.ts [hunk 10]
```diff
@@ -39,8 +45,17 @@ export function initializeCrashDetection() {
       return new Worker(new URL('./client.worker', import.meta.url));
     },
 
-    createDetectorWorker(): SharedWorker {
-      return new SharedWorker(new URL('./detector.worker', import.meta.url));
+    /**
+     *  There are limitations that require us to manually assert the type here.
+     *  1) Webpack uses static code analysis to create a new entry point for a SharedWorker.
+     *     It requies constructing an object with exact syntax new SharedWorker(...) (https://webpack.js.org/guides/web-workers/)
+     *  2) Some browsers may not support SharedWorkers hence we cannot extends CorsSharedWorker like CorsWorker and
```
Comment (svennergr) [inline public/app/core/crash/index.ts:52]:
```suggestion
     *  2) Some browsers may not support SharedWorkers hence we cannot extend CorsSharedWorker like CorsWorker and
```

File: public/app/core/crash/index.ts [hunk 11]
```diff
@@ -39,8 +45,17 @@ export function initializeCrashDetection() {
...
+     *     window.SharedWorker needs to be referenced during runtime only if it supported (https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker)
```
Comment (svennergr) [inline public/app/core/crash/index.ts:53]:
```suggestion
     *     window.SharedWorker needs to be referenced during runtime only if it is supported (https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker)
```

File: public/app/core/utils/CorsSharedWorker.ts [hunk 12]
```diff
@@ -0,0 +1,32 @@
...
+export function sharedWorkersSupported() {
+  return typeof window.SharedWorker !== 'undefined';
+}
+
+/**
+ * Creating CorsSharedWorker should be called only if sharedWorkersSupported() is truthy
+ */
+export class CorsSharedWorker {
+  constructor(url: URL, options?: WorkerOptions) {
+    // by default, worker inherits HTML document's location and pathname which leads to wrong public path value
```
Comment (svennergr) [inline public/app/core/utils/CorsSharedWorker.ts:12]:
```suggestion
    if (!sharedWorkersSupported()) {
      throw new Error('SharedWorker is not supported');
    }
    // by default, worker inherits HTML document's location and pathname which leads to wrong public path value
```

File: public/app/core/utils/CorsSharedWorker.ts [hunk 13]
```diff
@@ -0,0 +1,32 @@
...
+    // the CorsWorkerPlugin will override it with the value based on the initial worker chunk, ie.
```
Comment (svennergr) [inline public/app/core/utils/CorsSharedWorker.ts:13]:
```suggestion
    // the CorsSharedWorker will override it with the value based on the initial worker chunk, ie.
```

File: public/app/core/crash/index.ts [hunk 14]
```diff
@@ -39,8 +45,17 @@ export function initializeCrashDetection() {
...
+     *
+     *  We guarantee the type assertion is correct by returning a SharedWorker in CorsSharedWorker constructor.
+     */
+    createDetectorWorker() {
+      return new SharedWorker(new URL('./detector.worker', import.meta.url)) as globalThis.SharedWorker;
```
Comment (svennergr) [inline public/app/core/crash/index.ts:58]: Btw, is there any reason we rename the import `CorsSharedWorker as SharedWorker`?

Instead of doing

```suggestion
      return new CorsSharedWorker(new URL('./detector.worker', import.meta.url)) as SharedWorker;
```

I think that might be a bit more readable. Otherwise it might be unclear why we need to assert a `SharedWorker` as `SharedWorker`.

**Review by svennergr — COMMENTED** [review]
Left a few comments, mostly for readability/maintainability.

File: public/app/core/utils/CorsSharedWorker.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (ifrost) [reply public/app/core/utils/CorsSharedWorker.ts:20]: Okay, I'll update CorsWorker as well for consistency

File: public/app/core/crash/index.ts (hunk 14 above)
Comment (ifrost) [reply public/app/core/crash/index.ts:58]: The only reason is that webpack uses static code analysis to create entry points for workers. So it requires that exact class name to be used. We do the same thing with CorsWorker (WebWorker).

Comment (svennergr) [reply public/app/core/crash/index.ts:58]: Ah, okay, that's wild.

File: public/app/core/utils/CorsSharedWorker.ts (hunk 13 above)
Comment (ifrost) [reply public/app/core/utils/CorsSharedWorker.ts:16]: This one is actually correct. There's a single plugin for Web and SharedWorkers

File: public/app/core/utils/CorsSharedWorker.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (ifrost) [reply public/app/core/utils/CorsSharedWorker.ts]: CorsWorker updated in 972793817ff116b7f7b322d173297514e6e88132

**Review by svennergr — APPROVED** [review]
LGTM, thanks for iterating on this!

**Review by tskarhed — APPROVED** [review]
This would be highly valuable to present on a frontend weekly!
