### PR TITLE
Tempo: Use pipe in TraceQL by default for multi-value variables

### LINKED ISSUE #69841: Multi-value variables do not work in TraceQL
Multi-value variables do not work in TraceQL by default. They default to the [Graphite format](https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/#glob---graphite) which does not work and causes the TraceQL queries to return no data. 
 
Manually updating the query to use the [Pipe format](https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/#pipe) works, but this should be the default behavior for TraceQL.

### PR DESCRIPTION
**Pull request by joey-grafana**
**What is this feature?**

Updates Tempo TraceQL queries to use pipe by default for multi-value variables.

**Why do we need this feature?**

Fixes issue where TraceQL queries with multi-value variables were not being replaced correctly for the TraceQL query.

**Who is this feature for?**

Tempo users.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/69841

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/datasource/tempo/datasource.ts [hunk 1]
```diff
@@ -353,7 +353,7 @@ export class TempoDatasource extends DataSourceWithBackend<TempoQuery, TempoJson
 
     return {
       ...expandedQuery,
-      query: this.templateSrv.replace(query.query ?? '', scopedVars),
+      query: this.templateSrv.replace(query.query ?? '', scopedVars, 'pipe'),
```
Comment (aocenas) [inline public/app/plugins/datasource/tempo/datasource.ts:356]: I think it would make sense to use VariableFormatID.Pipe enum here instead of the raw string.

**Review by aocenas — APPROVED** [review]
Apart from one comment looks good
