### PR TITLE
Fix dense y-axis labels in heatmap using tsbuckets

### LINKED ISSUE #11342: Too many Y axis labels on heatmap in Time series bucket mode
When datasource returns too many buckets it's may be hard to read resulted heatmap. A simple solution is just to remove excess ticks or labels.

screenshot from 2018-03-22 15-29-17

### PR DESCRIPTION
**Pull request by postwait**
This change emulates the non-tsbuckets Y-axis tick count by making
the y-axis label formatter treat a dense set as a sparse set.

fixes #11342

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by postwait** [comment]
This should be a draft PR, it isn't quite right

**Comment by postwait** [comment]
Reverted to the correct version, but the tsbucket implementation is a hot mess. It assumes all buckets are the same height (or that users would want to see them as the same height)

**Comment by alexanderzobnin** [comment]
Hi, @postwait ! I'll take a look at this shortly.

File: public/app/plugins/panel/heatmap/rendering.ts [hunk 1]
```diff
@@ -366,11 +367,18 @@ export class HeatmapRenderer {
...
       .axisLeft(this.yScale)
-      .tickValues(tickValues)
       .tickFormat(tickFormatter)
       .tickSizeInner(0 - this.width)
       .tickSizeOuter(0)
       .tickPadding(Y_AXIS_TICK_PADDING);
+    if (
+      (tickValues && tickValues.length <= ticks) ||
+      (this.panel.yBucketBound === 'middle' && tickValues && tickValues.length)
+    ) {
```
Comment (alexanderzobnin) [inline public/app/plugins/panel/heatmap/rendering.ts:377]: Why do we need to leave `middle` ticks as is? From my POV there's no difference in terms of how to display it.

```suggestion
    if (tickValues && tickValues.length <= ticks) {
```

**Review by alexanderzobnin — CHANGES_REQUESTED** [review]
Looks good except one detail related to "middle" ticks mode.

File: public/app/plugins/panel/heatmap/rendering.ts (hunk 1 above)
Comment (postwait) [reply public/app/plugins/panel/heatmap/rendering.ts:377]: I was simply trying to preserve pre-existing functionality. I have no objection to this change.

**Review by alexanderzobnin — APPROVED** [review]
Looks good now!

**Comment by alexanderzobnin** [comment]
@postwait For some reason PR checks are not running on latest commit. Could you rebase/merge against master branch and push it to trigger checks again?

**Comment by postwait** [comment]
@alexanderzobnin I have rebased on master and force pushed my branch

**Comment by epvuc** [comment]
this makes labeled tsbuckets look bad since it skips names, and these graphs don't really make sense without names, unlike with numbered buckets. 

grafana704
