### PR TITLE
Prometheus: Fix aggregating by labels with dots

### LINKED ISSUE #114806: Prometheus: Aggregating by a label with dots doesn't work
### What happened?

I tried to use the query builder for the Prometheus data source to aggregate a metric by a label which contains a dot and got the following error: 

Image

### What did you expect to happen?

The issue is that the generated query is `sum by(item.name) (MyCounter_total{"color.name"="black"})` when it should be `sum by("item.name") (MyCounter_total{"color.name"="black"})`.

### Did this work before?

Not as far as I know.

### How do we reproduce it?

See the picture above. You don't even need any data, just input the label manually.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: latest
OS: Windows 11
Browser: Google Chrome 

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

### PR DESCRIPTION
**Pull request by juliuskoval**
Fixes https://github.com/grafana/grafana/issues/114806.

### CODE REVIEW

**Review by ooye-sanket — COMMENTED** [review]
Hey @juliuskoval! The logic looks good, but I think there might be a syntax issue.

**Line 251:**
```typescript
model.params.map(x => isString(x) && isValidLegacyName(x) ? x : `"${x}`)
```

This appears to be missing the closing quote in the template literal. Should it be:
```typescript
model.params.map(x => isString(x) && isValidLegacyName(x) ? x : `"${x}"`)
```

Same issue on line 256 in `getAggregationWithoutRenderer`.

Could you verify this compiles correctly? If it's working in your testing, I might be misreading the diff.

**Comment by juliuskoval** [comment]
Hi @ooye-sanket, it works when I test it. And here is the source code https://github.com/juliuskoval/grafana/blob/0ffc29ce812b3c4bc1019b4a6244a4f0b47d8f4d/packages/grafana-prometheus/src/querybuilder/operationUtils.ts#L251

**Comment by itsmylife** [comment]
@juliuskoval Thanks for the contribution! 
Could you please provide unit tests specific to this use case?
Thank you!

**Comment by juliuskoval** [comment]
Sure, I should have it done ~~tomorrow~~ on Wednesday.

**Comment by juliuskoval** [comment]
I added the unit tests. I also previously missed a scenario and changed the code from 
``model.params.map(x => isString(x) && isValidLegacyName(x) ? x : `"${x}"`)`` to 
``model.params.map(x => isString(x) && !isValidLegacyName(x) ? `"${x}"` : x)`` which is more restrictive.

**Comment by juliuskoval** [comment]
Hi @ooye-sanket, @itsmylife. Would you mind taking a look?

File: packages/grafana-prometheus/src/querybuilder/operationUtils.ts [hunk 1]
```diff
@@ -246,13 +248,13 @@ export function createAggregationOperationWithParam(
 
 export function getAggregationByRenderer(aggregation: string) {
   return function aggregationRenderer(model: QueryBuilderOperation, def: QueryBuilderOperationDef, innerExpr: string) {
-    return `${aggregation} by(${model.params.join(', ')}) (${innerExpr})`;
+    return `${aggregation} by(${model.params.map((x) => (isString(x) && !isValidLegacyName(x) ? `"${x}"` : x)).join(', ')}) (${innerExpr})`;
```
Comment (itsmylife) [inline packages/grafana-prometheus/src/querybuilder/operationUtils.ts]: I'd prefer doing it without lodash and using existing utf8Support function:

```
return `${aggregation} by(${model.params.map((x) => (typeof x === 'string' ? utf8Support(x) : x)).join(', ')}) (${innerExpr})`;
```

Do you mind replacing all three usages with this way?

**Review by itsmylife — CHANGES_REQUESTED** [review]
Thanks for fixing this issue. The PR looks good. I just asked a small change. After that we can merge this.

**Comment by itsmylife** [comment]
@juliuskoval Also do you mind merging latest `main` branch into your branch? This is for keeping the branch in sync.

And I'm sorry for such a delayed response. I should have reviewed this sooner. Next time I'll review it in time.

**Comment by juliuskoval** [comment]
Hi @itsmylife I made the changes you asked for and rebased my branch onto the main branch.

**Comment by juliuskoval** [comment]
Fixed unit tests.

**Review by ooye-sanket — COMMENTED** [review]
LGTM

**Comment by juliuskoval** [comment]
Hi @itsmylife, I rebased my branch onto main. Would you mind taking a look again?

**Review by itsmylife — APPROVED** [review]
LGTM
Thanks for the contribution and huge thanks for your patience.

**Comment by itsmylife** [comment]
@juliuskoval I know you've already gone through cla signing but the check is not passing. Could you please do it again by simply clicking this link https://cla-assistant.io/grafana/grafana?redirect=true&pullRequest=114807
It's a `required` check so without it's passing I cannot merge the PR. 

Also if you can, it'd be the best if you merge the latest `main` into your branch once more. It looks like e2e tests are failing for no reason. I think merging `main` would help.

**Comment by juliuskoval** [comment]
Done and done
