### PR TITLE
Dashboard import: Bug fixes

### LINKED ISSUE #23563: ImportDashboard: State is not cleaned when moving away from page
1) Import any dashboard
2) Go back to import page and see the old state remain.

### LINKED ISSUE #23564: ImportDashboard: error when trying to import into other folder than general
**What happened**:
When trying to import dashboard into other folder than general the following error is thrown by the backend (probably due to frontend not sending proper id for the folder).

`{ classification: "DeserializationError", message: "json: cannot unmarshal object into Go struct field ImportDashboardCommand.folderId of type int64" }`

**What you expected to happen**:
It should work without any errors

**How to reproduce it (as minimally and precisely as possible)**:
1. Copy a dashboard json
2. Go to import dashboard
3. Paste the json in the "import panel json".
4. Press load
5. In the next page select other folder than general
6. booom

### LINKED ISSUE #23565: ImportDashboard: input for dashboard identifier is rendered on top of select
**What happened**:
When trying to import a dashboard to a folder other than general the dropdown with all the options is rendered behind the identifier input.

Skärmavbild 2020-04-14 kl  15 26 13

### PR DESCRIPTION
**Pull request by peterholmberg**
**What this PR does / why we need it**:
Solves some issues discovered after merge to master.

**Which issue(s) this PR fixes**:
Fixes #23565
Fixes #23564
Fixes #23563

**Special notes for your reviewer**:

### CODE REVIEW

**Review by tskarhed — CHANGES_REQUESTED** [review]
Still can't import into other folder than general. No error, just regardless of what folder I select it ends up in General.

File: public/app/features/manage-dashboards/DashboardImportPage.tsx [hunk 1]
```diff
@@ -22,11 +22,16 @@ interface ConnectedProps {
...
   fetchGcomDashboard: typeof fetchGcomDashboard;
   importDashboardJson: typeof importDashboardJson;
+  resetDashboard: typeof resetDashboard;
 }
 
 type Props = OwnProps & ConnectedProps & DispatchProps;
 
 class DashboardImportUnConnected extends PureComponent<Props> {
+  componentWillUnmount() {
+    this.props.resetDashboard();
```
Comment (tskarhed) [inline public/app/features/manage-dashboards/DashboardImportPage.tsx:32]: What does this do on non-dashboard pages?

Comment (peterholmberg) [reply public/app/features/manage-dashboards/DashboardImportPage.tsx:32]: What do you mean? :thinking:

File: public/app/features/manage-dashboards/components/ImportDashboardOverview.tsx [hunk 2]
```diff
@@ -14,7 +14,7 @@ interface ConnectedProps {
   inputs: DashboardInputs;
   source: DashboardSource;
   meta?: any;
-  folderId: number;
+  folderId: { id: number; title?: string };
```
Comment (hugohaggmark) [inline public/app/features/manage-dashboards/components/ImportDashboardOverview.tsx:17]: Consider splitting this into 2 different props or change name to folder/folderConfig/folderSettings

Comment (hugohaggmark) [reply public/app/features/manage-dashboards/components/ImportDashboardOverview.tsx:17]: Or where is title used?

**Review by hugohaggmark — APPROVED** [review]
LGTM and works as expected! Left a minor comment for you to consider.

File: packages/grafana-ui/src/components/Select/SelectBase.tsx [hunk 3]
```diff
@@ -275,6 +275,8 @@ export function SelectBase<T>({
           container: () => ({
             position: 'relative',
             width: inputSizesPixels(size),
+            // This puts the menu above Inputs (z-index: 1)
+            zIndex: 10,
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/Select/SelectBase.tsx:279]: Can we use a zIndex from GrafanaTheme instead of hard coding this?

File: public/app/features/manage-dashboards/components/ImportDashboardOverview.tsx (hunk 2 above)
Comment (peterholmberg) [reply public/app/features/manage-dashboards/components/ImportDashboardOverview.tsx:17]: I wanted to match the type that the FolderPicker returns

Comment (peterholmberg) [reply public/app/features/manage-dashboards/components/ImportDashboardOverview.tsx:17]: ...and the FolderPicker should return a `SelectableValue<number>` in the future in my opinion. But that's a bit out of scope for this PR imo.

Comment (hugohaggmark) [reply public/app/features/manage-dashboards/components/ImportDashboardOverview.tsx:17]: Gotcha, then we should just rename it folder for now?

File: public/app/features/manage-dashboards/DashboardImportPage.tsx (hunk 1 above)
Comment (tskarhed) [reply public/app/features/manage-dashboards/DashboardImportPage.tsx:32]: Was just wondering what `resetDashboard` does. How does it update the state?

**Review by tskarhed — CHANGES_REQUESTED** [review]
The "unique identifier" error should disappear when you change folder. Otherwise it's confusing what "Overwrite" means. Will my old dashboard disappear?
Screenshot from 2020-04-17 11-34-41

**Comment by peterholmberg** [comment]
@tskarhed we can not have two dashboards with the same uid regardless of which folder they're in.

**Review by tskarhed — APPROVED** [review]

File: public/app/features/manage-dashboards/DashboardImportPage.tsx (hunk 1 above)
Comment (torkelo) [reply public/app/features/manage-dashboards/DashboardImportPage.tsx:32]: Find the resetDashboard action could be better named, maybe initImportDashboardPage? And I think it's better to have a cleanUp/reset on unmount rather than reset on mount. doing it on mount will cause it to render one time with old state before state resets. 

For clean up, we have this pattern that can fire a cleanup action on unmount that hugo created
We have a redux pattern for this already in the connectWithCleanUp, https://github.com/grafana/grafana/blob/e4c33e0be8418ae5fc99f4c94ee9bf62f9c1e511/public/app/core/components/connectWithCleanUp.tsx

**Comment by dprokop** [comment]
@peterholmberg seems like some snapshot tests are failing

File: public/app/features/manage-dashboards/DashboardImportPage.tsx (hunk 1 above)
Comment (torkelo) [reply public/app/features/manage-dashboards/DashboardImportPage.tsx:32]: Would still rename this action before merge.  As it does not reset any dashboard

**Review by torkelo — APPROVED** [review]
