### PR TITLE
PieChart: Display "No data" when there is no data

### LINKED ISSUE #38693: Pie Chart Legend Shows invalid labels when there is no data
**What happened**:
grafana 8.1 Pie chart shows incorrect legend when there is no data to show. see attached image

**What you expected to happen**:
When there is no data, there should be no legend and the "no data" (or equivalent) message should be displayed in place of any graph and legend in the panel.

**How to reproduce it (as minimally and precisely as possible)**:
an SQL query that includes time_sec, value and metric with 0 rows returned.

**Anything else we need to know?**:
The object returned from the query shows the following...
```
{
  ...
  "response": {
    "results": {
      "A": {
        "frames": [
          {
            "schema": {
              ...
              "fields": [
                {
                  "name": "time_sec",
                  "type": "number",
                  "typeInfo": {
                    "frame": "int64",
                    "nullable": true
                  }
                },
                {
                  "name": "value",
                  "type": "number",
                  "typeInfo": {
                    "frame": "int64",
                    "nullable": true
                  }
                },
                {
                  "name": "metric",
                  "type": "string",
                  "typeInfo": {
                    "frame": "string",
                    "nullable": true
                  }
                }
              ]
            },
            "data": {
              "values": [
                [],
                [],
                []
              ]
            }
          }
        ],
        "refId": "A"
      },
    }
  }
}
```

Also: the field override to hide columns from the legend displays them as disabled and does not hide them entirely. see attached image

**Environment**:
- Grafana version: v8.1.1 (90c87a52f7)
- Data source type & version: mysql 5.7
- OS Grafana is installed on: official docker image
- User OS & Browser: any browser, Mac OS
- Grafana plugins: none
- Others: n/a

Screenshot 2021-08-30 at 12 40 51

### PR DESCRIPTION
**Pull request by oscarkilhed**
**What this PR does / why we need it**:
When there is no data to display the piechart looks a bit weird.
Before:
image

After:
image

**Which issue(s) this PR fixes**:
Fixes #38693

### CODE REVIEW

File: public/app/plugins/panel/piechart/PieChartPanel.tsx [hunk 1]
```diff
@@ -127,6 +135,15 @@ function getLegend(props: Props, displayValues: FieldDisplay[]) {
   );
 }
 
+function hasFrames(fieldDisplayValues: FieldDisplay[]) {
+  for (let fd of fieldDisplayValues) {
+    if (fd.view && fd.view.dataFrame.length > 0) {
```
Comment (Clarity-89) [inline public/app/plugins/panel/piechart/PieChartPanel.tsx:140]:
```suggestion
    if (fd.view?.dataFrame.length) {
```
I think this. can be simplified a bit, altho I'd probably go with smth like 
```
function hasFrames(fieldDisplayValues: FieldDisplay[]) {
  return fieldDisplayValues.some((fd) => fd.view?.dataFrame.length);
}
```

**Review by Clarity-89 — APPROVED** [review]

File: public/app/plugins/panel/piechart/PieChartPanel.tsx [hunk 2]
```diff
@@ -127,6 +135,15 @@ function getLegend(props: Props, displayValues: FieldDisplay[]) {
...
+      return true;
+    }
+  }
+  return false;
+}
+
```
Comment (dprokop) [inline public/app/plugins/panel/piechart/PieChartPanel.tsx:146]: Do we need this function? Can't we simply rely on either data frames existence or fields compatibility with the vis? Something similar to what we do in the Bar chart: https://github.com/grafana/grafana/blob/8b80d2256dabbb29bb2beb3e97773789af61b22f/public/app/plugins/panel/barchart/BarChartPanel.tsx#L16

Comment (oscarkilhed) [reply public/app/plugins/panel/piechart/PieChartPanel.tsx:146]: Time series relies on data.series being > 0. In this case we actually get series ( DataFrame[] ) but the array is empty. It's fine to display this in the time series as it will just be a graph with no points in it, and that is probably the expected behavior. But for the PieChart that's more like the Gauge plugin it looks odd when we don't get any values, that's why I wanna check that there's some data to display.

File: public/app/plugins/panel/piechart/PieChartPanel.tsx (hunk 1 above)
Comment (oscarkilhed) [reply public/app/plugins/panel/piechart/PieChartPanel.tsx:140]: Yeah that would clean it up a bit, thanks.

**Review by dprokop — APPROVED** [review]
LGTM

**Comment by dprokop** [comment]
@oscarkilhed addeed this to 8.1.3 milestone (releasing tomorrow)
