### PR TITLE
Admin: Fixes so whole org drop down is visible when adding users to org

### LINKED ISSUE #22749: Grafana add to org dropdown is not showing all elements in json
**What happened**:
In grafana admin page while adding a user to an organization the dropdown it's not showing all list returned in the JSON.
**What you expected to happen**:
It has to show all elements returned in the JSON.
**How to reproduce it (as minimally and precisely as possible)**:
grafana admin -> users -> select user -> add organization, scroll bar actually going out of div
**Anything else we need to know?**:
Screenshot 2020-03-12 at 4 33 23 PM

**Environment**:
- Grafana version: 6.6.2
- Data source type & version:
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: 
- Others:

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR refactors `Modal` into a Functional Component and adds a render property so consumers can customize modal content part of `Modal`. I made `render` optional so we don't break existing usage of `Modal`. 

Would love some feedback on this change, maybe we should refactor all existing Modals to use render pattern instead? Or should we introduce a CustomModal or a third option?

We're probably doing a lot of work for this in v8 #24607, so I didn't want to do too much in this PR.

Enjoy the review 🎉 

**Which issue(s) this PR fixes**:
Fixes #22749

**Special notes for your reviewer**:

### CODE REVIEW

File: packages/grafana-ui/src/components/Modal/Modal.tsx [hunk 1]
```diff
@@ -19,48 +19,51 @@ export interface Props extends Themeable {
...
+          <div className={styles.modalHeaderClose}>
+            <IconButton surface="header" name="times" size="lg" onClick={onDismiss} />
           </div>
-          <div className={styles.modalContent}>{this.props.children}</div>
         </div>
-        <div className={styles.modalBackdrop} onClick={this.props.onClickBackdrop || this.onClickBackdrop} />
-      </Portal>
-    );
-  }
+        {render && render({ styles })}
```
Comment (Clarity-89) [inline packages/grafana-ui/src/components/Modal/Modal.tsx:53]: Is there a specific reason we'd need `render` in addition to `children` prop? Seems like they both are used to render content. If we need to customize content container styling maybe introducing `contentClassName` prop would work instead?

File: packages/grafana-ui/src/components/Modal/Modal.tsx [hunk 2]
```diff
@@ -19,48 +19,51 @@ export interface Props extends Themeable {
...
+        {!render && <div className={styles.modalContent}>{children}</div>}
```
Comment (Clarity-89) [inline packages/grafana-ui/src/components/Modal/Modal.tsx:54]: I think this might get a bit confusing when users provide both render and children prop. Maybe adding a warning, if both props are present, that says that the render prop is used, would be a good idea here?

**Review by Clarity-89 — COMMENTED** [review]
Great job! Left a few comments.

Correct me if I'm wrong, but it seems that render prop is introduced here to be able to override the content styling. Maybe it would be simpler to introduce a prop to customise container styles instead, same as `className`, but for content?

File: packages/grafana-ui/src/components/Modal/Modal.test.tsx [hunk 3]
```diff
@@ -9,10 +9,10 @@ describe('Modal', () => {
 
   it('renders nothing by default or when isOpen is false', () => {
     const wrapper = mount(<Modal title={'Some Title'} />);
-    expect(wrapper.html()).toBe('');
+    expect(wrapper.html()).toBe(null);
```
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Modal/Modal.test.tsx:12]: Good idea, but something for #24607 I think.

File: packages/grafana-ui/src/components/Modal/Modal.tsx [hunk 4]
```diff
@@ -19,48 +19,51 @@ export interface Props extends Themeable {
...
-  onClickBackdrop = () => {
-    this.onDismiss();
-  };
+interface RenderApi {
+  styles: ReturnType<typeof getModalStyles>;
+}
 
-  renderDefaultHeader(title: string) {
-    const { icon, iconTooltip } = this.props;
+export function Modal(props: PropsWithChildren<Props>): JSX.Element | null {
```
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Modal/Modal.tsx:29]: I'm using `function` not `const` here so I can't use FC? Any suggestions?

File: packages/grafana-ui/src/components/Modal/Modal.tsx (hunk 1 above)
Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Modal/Modal.tsx:53]: The reason for this is that I didn't want to break any existing Modals.

File: packages/grafana-ui/src/components/Modal/Modal.tsx (hunk 2 above)
Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Modal/Modal.tsx:54]: Great suggestion, but this depends on if I'll go ahead and refactor all existing Modals or not. But I guess that based on your feedback we should either refactor all Modal or introduce yet another className prop. The latter one is something that we should avoid IMHO.

Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Modal/Modal.tsx:54]: @dprokop would love your feedback on this before I take my next steps

File: packages/grafana-ui/src/components/Modal/Modal.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Modal/Modal.tsx]: I updated the return type to `ReturnType<FC<Props>>` instead.

[the remark this answers is not in the document]
Comment (Clarity-89) [reply packages/grafana-ui/src/components/Modal/Modal.tsx]: Any particular reason we'd want to use `function` here? I think in this case const + FC make code a bit cleaner. Not sure there's a way to use FC with `function` keyword.

[the remark this answers is not in the document]
Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Modal/Modal.tsx]: We should have a Frontend Weekly discussion about this. Seems like we don't really have a clear guideline regarding this (yet). Until we have I'll keep using `function` 😉

File: packages/grafana-ui/src/components/Modal/Modal.tsx (hunk 2 above)
Comment (torkelo) [reply packages/grafana-ui/src/components/Modal/Modal.tsx:54]: Agree with Alex that this solution adds some unnecessary complexity to the Moda. the fundamental problem is really that the Select does not support portal for the dropdown.

I would add an optional property on the Modal component to disable the overflow: auto property in the modal content, or add a contentClassName, not sure which is best out of those two :)

**Comment by hugohaggmark** [comment]
I reverted to using a simple prop called `contentClassName`.

File: public/app/features/admin/UserOrgs.tsx [hunk 5]
```diff
@@ -224,9 +225,21 @@ export class AddToOrgModal extends PureComponent<AddToOrgModalProps, AddToOrgMod
     const { isOpen } = this.props;
     const { role } = this.state;
     const styles = getAddToOrgModalStyles();
-
+    const modalStyles = getModalStyles(this.props.theme);
+    const contentClassName = cx(
+      modalStyles.modalContent,
```
Comment (torkelo) [inline public/app/features/admin/UserOrgs.tsx:230]: This this is a left over from the previous solution, this is already applied in the Modal component

**Review by torkelo — APPROVED** [review]
Look good :)  found one thing you left from the first solution

File: public/app/features/admin/UserOrgs.tsx [hunk 6]
```diff
@@ -224,9 +225,21 @@ export class AddToOrgModal extends PureComponent<AddToOrgModalProps, AddToOrgMod
...
+      css`
+        overflow: visible;
+      `
+    );
```
Comment (Clarity-89) [inline public/app/features/admin/UserOrgs.tsx:234]:
```suggestion
     const contentClassName = css`
      overflow: visible;
    `;
```

The modal content already has content styles applied, so this shouldn't be necessary here.

**Review by Clarity-89 — APPROVED** [review]
Looks good! 🎉  Just one minor comment.

File: public/app/features/admin/UserOrgs.tsx (hunk 6 above)
Comment (hugohaggmark) [reply public/app/features/admin/UserOrgs.tsx:234]: Yes, I realized that when I saw Torkel's comment. Will fix ASAP.

File: public/app/features/admin/UserOrgs.tsx (hunk 5 above)
Comment (hugohaggmark) [reply public/app/features/admin/UserOrgs.tsx]: Awesome catch, thank you!

File: packages/grafana-ui/src/components/Modal/Modal.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (dprokop) [reply packages/grafana-ui/src/components/Modal/Modal.tsx]: My two cents about this. For a matter of readability, I would opt for:

- `function` - when a function actually is a utility
- `const` - in case of _function component_. It's easier to type with `:FC<..>` than `ReturnType<FC<...>>` and I guess I've  never seen typing function components this way. Guess event React guide uses const all over the place rather than functions.

[the remark this answers is not in the document]
Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Modal/Modal.tsx]: Hahaha, I love being the first one using that instead of `ReactElement | null`. We should really have a Frontend discussion about the `function` vs `const` usage. I know that @torkelo has some opinions about this too.

[the remark this answers is not in the document]
Comment (torkelo) [reply packages/grafana-ui/src/components/Modal/Modal.tsx]: yes, I prefer function over a const variable, except for react components, where the typing is easier / more readable with a const variable.

[the remark this answers is not in the document]
Comment (hugohaggmark) [reply packages/grafana-ui/src/components/Modal/Modal.tsx]: Ok, I didn't realize you preferred const for ReactComponents. Good to know.
