### PR TITLE
Security: Fix invite link still accessible after completion or revocation

### LINKED ISSUE #20835: Invite link still accessible after completion or revocation
**What happened**:
Completed an invite I received for a Grafana organization and noticed that I still could access the invite link after completion.

**What you expected to happen**:
No access to invite link.

**How to reproduce it (as minimally and precisely as possible)**:
1. Invite user to org through Configuration -> Users -> Invite 
2. Copy invite link and complete it
3. Open a new tab with invite link and you see you can still access it.

**Anything else we need to know?**:
Seems like the existing validation [here](https://github.com/grafana/grafana/blob/master/pkg/api/org_invite.go#L166-L168) when completing invite could be added here [here](https://github.com/grafana/grafana/blob/master/pkg/api/org_invite.go#L145) to make sure that only pending invites are accessible. 

**Environment**: 
- Grafana version: master (74ac737)

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Currently, already accepted invites can be accessed again. This PR fixes this by making the API return 404 for non-pending invites.

**Which issue(s) this PR fixes**:
Fixes #20835.

**Special notes for your reviewer**:
I picked 404 as the HTTP status code, but feedback is welcome on this choice. Also, should we add a test for this?

### CODE REVIEW

File: pkg/api/org_invite.go [hunk 1]
```diff
@@ -132,9 +132,11 @@ func RevokeInvite(c *m.ReqContext) Response {
 	return Success("Invite revoked")
 }
 
+// GetInviteInfoByCode gets a user invite corresponding to a certain code.
+// A response containing an InviteInfo object is returned if the invite is found.
+// If the invite is not found, 404 is returned.
```
Comment (papagian) [inline pkg/api/org_invite.go]: This comment is a bit misleading; actually, 404 is returned if the invite status is un-expected.

File: pkg/api/org_invite.go [hunk 2]
```diff
@@ -143,6 +145,9 @@ func GetInviteInfoByCode(c *m.ReqContext) Response {
 	}
 
 	invite := query.Result
+	if invite.Status != m.TmpUserInvitePending {
+		return Error(404, "Invite not found", nil)
```
Comment (papagian) [inline pkg/api/org_invite.go]: Maybe better use `412` status to conform with [this](https://github.com/grafana/grafana/blob/master/pkg/api/org_invite.go#L167).

File: pkg/services/auth/auth_token.go [hunk 3]
```diff
@@ -121,7 +121,6 @@ func (s *UserAuthTokenService) LookupToken(ctx context.Context, unhashedToken st
 		return err
 
 	})
-
```
Comment (papagian) [inline pkg/services/auth/auth_token.go]: Maybe this is not necessary since it's the only modification in this file.

File: pkg/api/org_invite.go (hunk 1 above)
Comment (aknuds1) [reply pkg/api/org_invite.go]: @papagian Yeah, it's a question of semantics. I defined it (implicitly) as if a pending invite is not found, since that's all the client should care about (as I defined it).

File: pkg/api/org_invite.go (hunk 2 above)
Comment (aknuds1) [reply pkg/api/org_invite.go]: I don't really know how [CompleteInvite](https://github.com/grafana/grafana/blob/master/pkg/api/org_invite.go#L155) is invoked in a user flow, so it's difficult for me to evaluate how these two API endpoints should correlate with each other.

In isolation, 404 seems more useful to me for this particular endpoint, since I don't think it should matter to the user which state the invite is in on the back-end if it shouldn't be accessed.

Comment (marefr) [reply pkg/api/org_invite.go]: I agree 404 is more logical than 412. When submitting invite-form rendered at invite url the CompleteInvite is the handler of that action.

Comment (papagian) [reply pkg/api/org_invite.go]: I think that the CompleteInvite is [called](https://github.com/grafana/grafana/blob/master/public/app/core/controllers/invited_ctrl.ts#L36) by the frontend when one submits the signup (after invitation form) but I don't have a strong opinion about this either.

File: pkg/api/org_invite.go (hunk 1 above)
Comment (aknuds1) [reply pkg/api/org_invite.go]: @papagian I reworded the documentation here a bit, to make it clearer.

**Review by papagian — APPROVED** [review]
LGTM

**Review by marefr — APPROVED** [review]
LGTM
