### PR TITLE
Prometheus: Provide label values match parameter API when supported prometheus instance is configured

### LINKED ISSUE #33487: Prometheus: Try to use labels API instead of series API as it newly supports match
**What happened**:
On metric with high cardinality (a lots of prometheus series) we can't get label values.
This is because label_values use /api/v1/series instead of /api/1v/label when there is a metric defined.

It comes from here :
https://github.com/grafana/grafana/blob/b5190ee547340aa8f9e4d9e32d4ff05e3687d449/public/app/plugins/datasource/prometheus/metric_find_query.ts#L73-L109

It uses /api/v1/series endpoint when there is a serie selector (metric) to match

**What you expected to happen**:

The documentation of prometheus HTTP API indicates that it supports "match" field on label value endpoint
https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values

This endpoint is well optimized to retrieve label values.

**How to reproduce it (as minimally and precisely as possible)**:

Fill a prometheus/victoria metrics server with a high cardinality metrics (3 tag/label with 500 different values), getting values from one label/tag will return 250000 of series using series endpoint, but only 500 label values using label endpoint.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.5
- Data source type & version: prometheus 2.26/victoriametrics 1.58.0
- OS Grafana is installed on: dockerofficial image
- User OS & Browser: chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by gtk-grafana**
**What this PR does / why we need it**:
Right now we're using the /series API in prometheus to pull metric names with regex, for example in the label_values function. This endpoint is terribly inefficient for this need as it sends a bunch of additional data that we wind up throwing away in this context. 

Now that users can detect/configure their prometheus type/version (introduced in https://github.com/grafana/grafana/pull/56496), we can use these configured values to provide support for the new (introduced in [v2.24](https://github.com/prometheus/prometheus/releases/tag/v2.24.0)) prometheus API features.

For this initial alpha release, we're defaulting to use the old APIs so as not to introduce a breaking change, and only users that configure their datasource will get the new API feature, however I expect this functionality to change in a future Grafana release to default to using new API features.

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/33487

**Special notes for your reviewer**:
Thanks to @alanprot for https://github.com/grafana/grafana/pull/54263, which was very helpful in implementing this

### CODE REVIEW

**Comment by alanprot** [comment]
Hi @gtk-grafana 

Thanks for working into this! This is a very good improvement.

So if i understood correctly, now the customer will be able to define the backend datasource version when configuring the prometheus datasource on grafana. Is my understanding correct?

If this is the case, does makes more sense to default to `get labels` and if the customer is using a old backend use `get series`?

**Comment by gtk-grafana** [comment]
@alanprot yup! After we release the parent PR: https://github.com/grafana/grafana/pull/56496, users can start configuring their datasource configuration, and we're aiming to quickly follow up with this PR.

As to your other question I think we're going to default to not use the new API, and if users configure their version then supported versions will get new features, as to prevent introducing a breaking change before we know how many users are running datasources versions that don't support this API feature. 

We're also planning on introducing UI notifying users when they haven't configured these values, and they could be using the new API if they did.

File: public/app/plugins/datasource/prometheus/datasource.tsx [hunk 1]
```diff
@@ -146,6 +147,33 @@ export class PrometheusDatasource
     return query.expr;
   }
 
+  doesDatasourceSupportLabelsMatchAPI(): boolean {
```
Comment (obetomuniz) [inline public/app/plugins/datasource/prometheus/datasource.tsx:150]: What do you think about renaming it to `hasLabelsMatchAPISupport`? I think makes sense since it will be used publicly as `ds.hasLabelsMatchAPISupport()`.

**Review by obetomuniz — APPROVED** [review]
LGTM 👏👏👏  Just left a few nits to consider as code improvement suggestions.

File: public/app/plugins/datasource/prometheus/metric_find_query.ts [hunk 2]
```diff
@@ -71,28 +71,27 @@ export default class PrometheusMetricFindQuery {
...
+    const params = metric
+      ? {
+          'match[]': metric,
+          start: start.toString(),
+          end: end.toString(),
+        }
+      : {
+          start: start.toString(),
+          end: end.toString(),
+        };
```
[the remark this answers is not in the document]
Comment (gtk-grafana) [reply public/app/plugins/datasource/prometheus/metric_find_query.ts]: Oh whoa yeah I like this! Fixed!!

**Review by itsmylife — APPROVED** [review]

File: docs/sources/whatsnew/whats-new-in-v9-2.md [hunk 3]
```diff
@@ -219,3 +219,17 @@ For more information, see the [SAML configuration documentation](https://grafana
 You can now map OAuth groups and roles to Server Admin for the GitLab, GitHub, AzureAD, Okta, and Generic OAuth integrations.
 To enable this functionality, set the `allow_assign_grafana_admin` configuration option to `true` in the desired OAuth integration section.
 For more information, see the [authentication configuration documentation](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/) for each OAuth client.
+
+## Match parameter support in prometheus labels API
+
+Prometheus users running Prometheus 2.24 or higher can now elect to use the
```
Comment (gtk-grafana) [inline docs/sources/whatsnew/whats-new-in-v9-2.md:225]: @gguillotte-grafana Can you take a look at this and let me know if you have any questions about how we can clean up this language?

File: docs/sources/whatsnew/whats-new-in-v9-2.md [hunk 4]
```diff
@@ -219,3 +219,17 @@ For more information, see the [SAML configuration documentation](https://grafana
...
+[labels](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values) endpoint instead of the
+[series](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers) endpoint for the
+`label_values` [function](https://grafana.com/docs/grafana/latest/datasources/prometheus/#query-variable).
+This has no impact on dashboard functionality, but can decrease load times for templated high cardinality
+prometheus instances.
+
+In order to prevent breaking changes for prometheus versions before 2.24, users must first configure their prometheus
+type and version in the prometheus
+[configuration](https://grafana.com/docs/grafana/latest/administration/data-source-management),
+or in the [provisioning](https://grafana.com/docs/grafana/latest/administration/provisioning/) file.
```
Comment (gguillotte-grafana) [inline docs/sources/whatsnew/whats-new-in-v9-2.md:235]: When should Prometheus <v2.24 users "first configure their prometheus type and version"? Before upgrading to v9.2? Immediately after? What breaks if they don't?

cf. my comment in #56496 - Prometheus-specific settings, including provisioning, should also be in the [data source's docs](https://github.com/grafana/grafana/blob/main/docs/sources/datasources/prometheus.md), which should also make it a more specific link target for configuration docs.

```suggestion
Prometheus users running Prometheus v2.24 and higher can use the [labels endpoint](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values) instead of the [series endpoint](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers) for the [`label_values` function]({{< relref "../datasources/prometheus/#query-variable" >}}).
This decreases load times for templated high-cardinality Prometheus instances.

To prevent breaking changes if you're running Prometheus versions before v2.24, you must first configure the Prometheus type and version in any Prometheus data sources' [configuration]({{< relref "../datasources/prometheus/" >}}).
```

**Review by gguillotte-grafana — COMMENTED** [review]
Provided revised wording; see also the comment in #56496 about adding the new settings to the data source docs. This text could be repurposed there for context.

File: docs/sources/whatsnew/whats-new-in-v9-2.md (hunk 4 above)
Comment (gtk-grafana) [reply docs/sources/whatsnew/whats-new-in-v9-2.md]: > When should Prometheus <v2.24 users "first configure their prometheus type and version"? Before upgrading to v9.2? Immediately after? What breaks if they don't?

If you're running prometheus <2.24, the new API endpoint we're exposing in this PR doesn't exist, so they'll continue calling the existing series API that we call today, nothing breaks, they just can't use these new optimizations we're releasing.

If you're running prometheus <2.24 you don't need to set your configuration at all, as you don't apply for the new functionality.

Only users that are running prometheus >2.24 benefit from setting their configuration, as then they will be able to use new API endpoints that will increase performance.

Comment (gguillotte-grafana) [reply docs/sources/whatsnew/whats-new-in-v9-2.md]: I'm confused by "In order to prevent breaking changes for prometheus versions before 2.24" then - it doesn't sound like there are any breaking changes or necessary configuration changes regardless of version?

If there's not a change that will break things when upgrading to Grafana v9.2 then we need to avoid the term "breaking change".

Comment (gguillotte-grafana) [reply docs/sources/whatsnew/whats-new-in-v9-2.md]: If you want to merge this I'm OK to iterate on the docs end. But I really want to avoid suggesting this might be a breaking change if there's not one.

Comment (gtk-grafana) [reply docs/sources/whatsnew/whats-new-in-v9-2.md]: Oh yeah, that is unnecessarily confusing, I was trying to explain why we're releasing this functionality as opt-in, because if we otherwise assume that everyone supports the new API unless they configure an older version, then folks running older versions could see dashboards break. I'll rewrite this, I don't think it's super relevant anyway

Comment (gtk-grafana) [reply docs/sources/whatsnew/whats-new-in-v9-2.md]: I changed it to:
`If you want to benefit from this endpoint you must first configure the Prometheus type and version in any Prometheus data sources' [configuration]({{< relref "../datasources/prometheus/" >}}).`

**Review by gguillotte-grafana — APPROVED** [review]
