### PR TITLE
Graphite: Display an error message when finding metrics fails

### LINKED ISSUE #28336: graphite query editor: find request failure invisible in UI
Grafana v7.2.1 (72a6c64532)

**What happened**:

When using graphite, and using the query editor, which triggers find requests in the background, if the find request fails, nothing is visible in the UI.
the only tell is this in the grafana logs:
```
grafana_1        | t=2020-10-16T18:38:08+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/3/metrics/find status=400 remote_addr=172.25.0.1 time_ms=2 size=40 referer="http://localhost:3000/dashboard/new?editPanel=2&orgId=1"
```
but as the user in the UI nothing is visible (or more precisely, the panel doesn't update, it shows whatever the last drawn panel was)

**What you expected to happen**:

I expect to see an error in the UI

**How to reproduce it (as minimally and precisely as possible)**:

it's hard to deliberately generate a find error, but it can be done e.g. with https://github.com/grafana/metrictank/pull/1926 to autocomplete on a number of series that exceeds the limit

### PR DESCRIPTION
**Pull request by ifrost**
**What this PR does / why we need it**:

This is similar to https://github.com/grafana/grafana/pull/31680. When listing metric names fails it's not clear why the list of metrics is empty. This PR adds an error message:

find-error

**Which issue(s) this PR fixes**:

Fixes #28336

**Special notes for your reviewer**: -

### CODE REVIEW

File: public/app/plugins/datasource/graphite/query_ctrl.ts [hunk 1]
```diff
@@ -437,6 +439,14 @@ export class GraphiteQueryCtrl extends QueryCtrl {
       dispatch(notifyApp(createErrorNotification(`Fetching tags failed: ${error.message}.`)));
     }
   }
+
+  private handleMetricsAutoCompleteError(error: Error): void {
+    console.log(error);
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/graphite/query_ctrl.ts:444]:
```suggestion
    console.error(error);
```

Comment (ivanahuckova) [reply public/app/plugins/datasource/graphite/query_ctrl.ts:444]: I have noticed that we are using `console.log` in `private handleTagsAutoCompleteError`. I think it would make sense to change it to `console.error` as well.

**Review by ivanahuckova — APPROVED** [review]
LGTM! Left 1 comment, but definitely non-blocking. Good job!

File: public/app/plugins/datasource/graphite/query_ctrl.ts (hunk 1 above)
Comment (ifrost) [reply public/app/plugins/datasource/graphite/query_ctrl.ts:444]: Coolio, I'll do the same for `handleTagsAutoCompleteError` :)

**Comment by Dieterbe** [comment]
Thanks @ifrost !
