### PR TITLE
Data source: Fixes saving a data source without failure when URL doesn't specify a protocol

### LINKED ISSUE #24387: Validation error, invalid URL on PostgreSQL Data Source creation specifying a port
**What happened**:
I get this "Validation error, invalid URL" message while trying to specify a different port on PostgreSQL datasource. The inserted value was `192.168.0.1:5433` on `Host` config. 

**What you expected to happen**:
This should be a valid `Host` setting, as it was on `grafana:latest`. I'm trying out 7.0 release. 

**How to reproduce it (as minimally and precisely as possible)**:
Specify an IP (i.e., 127.0.0.1 instead of localhost) and any port for `Host` setting, on PostgreSQL Data Source creation.

**Anything else we need to know?**:

**Environment**:
- Grafana version: `v7.1.0-f3f34ac0pre (d891cc5949)`, reproducible on `7.0 beta1`. It works well on stable `grafana:latest` on docker
- Data source type & version: PostgreSQL

- OS Grafana is installed on: Alpine on docker
- User OS & Browser: Debian
- Grafana plugins: None, fresh install
- Others:

Captura de tela de 2020-05-07 09-07-14

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Modify data source URL validation to handle URLs that don't specify the protocol, f.ex. "127.0.0.1:5432". 

I've tested this change with Loki and Postgres data sources, and both work fine (I could verify that the bug in #24387, with specifying e.g. "127.0.0.1:5433" is fixed).

**Which issue(s) this PR fixes**:

Fixes #24387.

**Special notes for your reviewer**:
I don't feel as if it's the cleanest fix, but I'm not sure how else we might solve this, since a URL is inherently ambiguous without the protocol part (f.ex. "http://").

### CODE REVIEW

File: pkg/api/pluginproxy/ds_proxy.go [hunk 1]
```diff
@@ -83,10 +84,19 @@ func (lw *logWrapper) Write(p []byte) (n int, err error) {
...
+var reURL = regexp.MustCompile("^[^:]*://")
+
 // NewDataSourceProxy creates a new Datasource proxy
 func NewDataSourceProxy(ds *models.DataSource, plugin *plugins.DataSourcePlugin, ctx *models.ReqContext,
 	proxyPath string, cfg *setting.Cfg) (*DataSourceProxy, error) {
-	targetURL, err := url.Parse(ds.Url)
+	u := ds.Url
+	// Make sure the URL starts with a protocol specifier, so parsing is unambiguous
+	if !reURL.MatchString(u) {
+		u = fmt.Sprintf("http://%s", u)
```
Comment (aknuds1) [inline pkg/api/pluginproxy/ds_proxy.go:97]: Could it cause problems anywhere that the URL's protocol is set to HTTP as a fallback?

File: pkg/api/datasources.go [hunk 2]
```diff
@@ -129,8 +130,16 @@ func DeleteDataSourceByName(c *models.ReqContext) Response {
...
 }
 
+// reURL is a regexp to detect if a URL specifies the protocol. We match also strings where the actual protocol is missing
+// (i.e., "://"), in order to catch these as invalid when parsing.
+var reURL = regexp.MustCompile("^[^:]*://")
+
 func validateURL(u string) Response {
 	if u != "" {
+		// Make sure the URL starts with a protocol specifier, so parsing is unambiguous
+		if !reURL.MatchString(u) {
```
Comment (bergquist) [inline pkg/api/datasources.go:140]: It would be nice with some tests for this. I always find it easier to understand regexp patterns if I can read tests :)

File: pkg/api/pluginproxy/ds_proxy.go (hunk 1 above)
Comment (bergquist) [reply pkg/api/pluginproxy/ds_proxy.go:97]: I _think_ it should be fine as long as the regexp works as expected.

Comment (papagian) [reply pkg/api/pluginproxy/ds_proxy.go:97]: I was wondering almost the same; is there any case that the fallback protocol should be `https` instead of `http`?
At least there could be a debug message that the silent implied protocol is `http`?

File: pkg/api/datasources.go (hunk 2 above)
Comment (aknuds1) [reply pkg/api/datasources.go:140]: @bergquist Gotcha, I will add a test or two.

File: pkg/api/pluginproxy/ds_proxy.go (hunk 1 above)
Comment (aknuds1) [reply pkg/api/pluginproxy/ds_proxy.go:99]: @papagian Would it help in any case to specify https? I am actually hoping that the protocol part of the URL won't be applied anywhere, since chances are it's incorrect. For example, I tested with Postgres, and it doesn't apply the protocol part of the URL (which would fail if it did).

Regarding https, I think it's less safe, since many servers might not support it and if you use http they will typically redirect you to https.

Comment (aknuds1) [reply pkg/api/pluginproxy/ds_proxy.go:99]: I've added debug logging BTW @papagian, please have a look.

Comment (papagian) [reply pkg/api/pluginproxy/ds_proxy.go:99]: Honestly I can't tell for sure because I'm not aware of all the possible cases.
I think that the debug message should be enough for now.

I would ideally prefer also a unified `validateUrl` to be used by both the `api` and the `pluginproxy`. What do you think?

Comment (aknuds1) [reply pkg/api/pluginproxy/ds_proxy.go:99]: @papagian I can't share `validateURL` as is, but I can try to extract a common one.

Comment (papagian) [reply pkg/api/pluginproxy/ds_proxy.go:99]: not a blocker anyway

**Comment by aknuds1** [comment]
@bergquist @papagian I added a collection of tests for adding and updating data sources, plus I refactored the URL validation into a shared function. Please have a look.

File: pkg/api/datasources_test.go [hunk 3]
```diff
@@ -56,3 +57,107 @@ func TestDataSourcesProxy(t *testing.T) {
...
+
+	assert.Equal(t, 200, sc.resp.Code)
+}
+
+// Updating data sources with invalid URLs should lead to an error.
+func TestUpdateDataSource_InvalidURL(t *testing.T) {
+	defer bus.ClearBusHandlers()
+
+	sc := setupScenarioContext("/api/datasources/1234")
+	// TODO: Make this an argument to setupScenarioContext
```
Comment (bergquist) [inline pkg/api/datasources_test.go:118]: I guess your goal is to solve these TODO's in another PR?

**Review by bergquist — APPROVED** [review]
LGTM

File: pkg/api/datasources_test.go (hunk 3 above)
Comment (aknuds1) [reply pkg/api/datasources_test.go:118]: @bergquist Yes, it's a larger operation (as part of dropping goconvey), and I think best done separately.
