### PR TITLE
Trend: Fix x field matching logic

### LINKED ISSUE #72861: Trend: Fix field name handling regression
The trend field handling was modified as part of adding disconnect values support. As a result this has broken a few dashboards in our BI instance as well as could impact other current usages of the trend panel.

Broken BI panels
- https://bi.grafana-ops.net/d/f1c51f68-f2ef-4600-83ae-67e8b26669ec/pipeline-monitor?orgId=1&refresh=15m&viewPanel=275
- https://bi.grafana-ops.net/d/f1c51f68-f2ef-4600-83ae-67e8b26669ec/pipeline-monitor?orgId=1&refresh=15m&viewPanel=323

The regression occurred in [the following PR / lines changed](https://github.com/grafana/grafana/pull/70616/files#diff-0328eaa656b27fcf995773d206433d4b5b1e0e2b922d6285d1caa8987585d1bfR57)

See [this slack thread](https://raintank-corp.slack.com/archives/C04J73AAQ87/p1690995864173559) for additional context

### PR DESCRIPTION
**Pull request by nmarrs**
Fixes regression with trend panel where we were matching incorrectly to the field's display name vs. name which caused a few trend panels in BI to break

Before
Screenshot 2023-08-03 at 5 32 48 PM

After
Screenshot 2023-08-03 at 5 32 56 PM

Fixes https://github.com/grafana/grafana/issues/72861

Debug panel dashboard to test things out locally with
[debug-Pipeline Build by Days Before Quarter Begin-2023-08-03 23_13_01.json.txt](https://github.com/grafana/grafana/files/12255705/debug-Pipeline.Build.by.Days.Before.Quarter.Begin-2023-08-03.23_13_01.json.txt)

### CODE REVIEW

File: public/app/plugins/panel/trend/TrendPanel.tsx [hunk 1]
```diff
@@ -39,7 +39,7 @@ export const TrendPanel = ({
     dimFields = {
       ...dimFields,
       x: (field, frame, frames) => {
-        return getFieldDisplayName(field, frame, frames) === trendXFieldName;
+        return field.name === trendXFieldName;
```
Comment (ryantxu) [inline public/app/plugins/panel/trend/TrendPanel.tsx:42]: rather than trying to do the calculation ourselves, should we just use a matcher?

I think this could be:
```suggestion
        x: fieldMatchers.get(FieldMatcherID.byName).get(trendXFieldName),
```

**Review by ryantxu — APPROVED** [review]
🔥
