### PR TITLE
CloudWatch: Fixes query order not affecting series ordering & color

### LINKED ISSUE #16161: CloudWatch: Reordering queries does not affect graph order or color
**What happened**:
Given two CloudWatch queries A and B, if the order in the edit panel is [B, A], the graph still shows query A first (green) and query B second (yellow). It seems to still use the alphabetical order of the query identifiers [A, B].

**What you expected to happen**:
Query B should be first (green) and query A should be second (yellow)

**How to reproduce it (as minimally and precisely as possible)**:
Create a graph panel with two CloudWatch queries. Reorder them, and observe no change in the graph ordering.

**Anything else we need to know?**:
Moving these queries up and down only affect their ordering in the query editor.

This does work as expected with other datasources, so it seems that the Cloudwatch datasource doesn't honor the order specified in Grafana.

**Environment**:
- Grafana version: 5.3.4
- Data source type & version: CloudWatch
- OS Grafana is installed on: Docker/Linux
- User OS & Browser: Chrome MacOS X
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by mtanda**
Fix https://github.com/grafana/grafana/issues/16161

### CODE REVIEW

File: public/app/plugins/datasource/cloudwatch/datasource.ts [hunk 1]
```diff
@@ -138,7 +138,8 @@ export default class CloudWatchDatasource {
       const data = [];
 
       if (res.results) {
-        _.forEach(res.results, queryRes => {
+        request.queries.forEach(q => {
```
Comment (torkelo) [inline public/app/plugins/datasource/cloudwatch/datasource.ts]: replace with for (const query of request.queries)

File: public/app/plugins/datasource/cloudwatch/datasource.ts [hunk 2]
```diff
@@ -138,15 +138,16 @@ export default class CloudWatchDatasource {
       const data = [];
 
       if (res.results) {
-        _.forEach(res.results, queryRes => {
+        for (const query of request.queries) {
+          const queryRes = res.results[query.refId];
           _.forEach(queryRes.series, series => {
```
Comment (torkelo) [inline public/app/plugins/datasource/cloudwatch/datasource.ts]: for (const series of queryRes.series)

Comment (mtanda) [reply public/app/plugins/datasource/cloudwatch/datasource.ts]: sorry, I need lint rule for `for-of`...
