### PR TITLE
Alerting: Show evaluation interval global limit warning

### LINKED ISSUE #52475: Warning about minimum evaluation interval is not present in Grafana Managed Alerts
**What happened**:

Old alerting would show a warning if the evaluation interval for an alert rule was lower than the minimum evaluation interval for the installation.

image

**What you expected to happen**:

We should show the same warning in Grafana Managed Alerts.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by konrad147**
**What this PR does / why we need it**:
This PR adds a warning when the global evaluation interval limit is bigger than the interval set on an alert rule group

**Which issue(s) this PR fixes**:
Fixes #52475 

**Special notes for your reviewer**:
The PR also contains a fix for https://github.com/grafana/grafana/issues/52491 and bypasses the `for` option validation for `0` and `0s` values because they are valid options

**Alerts list**
image

**Alert edit page**
image

### CODE REVIEW

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 1]
```diff
@@ -52,6 +55,16 @@ const evaluateEveryValidationOptions: RegisterOptions = {
   },
 };
 
+// TODO Move to more generic place
+export function useEvaluationIntervalGlobalLimit(alertGroupEvaluateEvery: string) {
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:59]: Maybe better `getEvaluationIntervalGlobalLimit` instead of `useEvaluationIntervalGlobalLimit` as this is not a hook?

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 2]
```diff
@@ -101,6 +124,14 @@ export const GrafanaEvaluationBehavior: FC = () => {
           </Field>
         </div>
       </Field>
+      {exceedsGlobalEvaluationLimit && (
+        <Alert severity="warning" title="Global evalutation interval limit exceeded">
+          A minimum evaluation interval of{' '}
+          <span className={styles.globalLimitValue}>{config.unifiedAlerting.minInterval}</span> have been configured in
```
Comment (grobinson-grafana) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:130]:
```suggestion
          <span className={styles.globalLimitValue}>{config.unifiedAlerting.minInterval}</span> has been configured in
```

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 3]
```diff
@@ -52,6 +55,16 @@ const evaluateEveryValidationOptions: RegisterOptions = {
   },
 };
 
+// TODO Move to more generic place
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:58]: If we want to use this method as a generic method, maybe it's a good idea to inject `minInterval` as a parameter, so we have a pure function?

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 4]
```diff
@@ -101,6 +124,14 @@ export const GrafanaEvaluationBehavior: FC = () => {
           </Field>
         </div>
       </Field>
+      {exceedsGlobalEvaluationLimit && (
+        <Alert severity="warning" title="Global evalutation interval limit exceeded">
+          A minimum evaluation interval of{' '}
+          <span className={styles.globalLimitValue}>{config.unifiedAlerting.minInterval}</span> have been configured in
+          Grafana and will be used for this alert rule. <br />
```
Comment (grobinson-grafana) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:131]:
```suggestion
          Grafana. <br />
```

I think this is OK as this warning is shown when configuring the `For` interval.

File: public/app/features/alerting/unified/components/rules/RuleConfigStatus.tsx [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+    return null;
+  }
+
+  return (
+    <Tooltip
+      theme="error"
+      content={
+        <div>
+          A minimum evaluation interval of{' '}
+          <span className={styles.globalLimitValue}>{config.unifiedAlerting.minInterval}</span> have been configured in
```
Comment (grobinson-grafana) [inline public/app/features/alerting/unified/components/rules/RuleConfigStatus.tsx:29]:
```suggestion
          <span className={styles.globalLimitValue}>{config.unifiedAlerting.minInterval}</span> has been configured in
```

File: public/app/features/alerting/unified/components/rules/RuleConfigStatus.tsx [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+          Grafana and will be used for this alert rule instead of {rule.group.interval} configured for the alert group.
```
Comment (grobinson-grafana) [inline public/app/features/alerting/unified/components/rules/RuleConfigStatus.tsx:30]:
```suggestion
          Grafana and will be used instead of the {rule.group.interval} interval configured for the Rule Group.
```

**Review by grobinson-grafana — CHANGES_REQUESTED** [review]
I haven't reviewed the code, however I have a number of suggestions on how we could improve the message shown to the user.

**Review by soniaAguilarPeiron — APPROVED** [review]

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 7]
```diff
@@ -15,17 +16,19 @@ import { RuleEditorSection } from './RuleEditorSection';
 
 const MIN_TIME_RANGE_STEP_S = 10; // 10 seconds
 
+function parseDurationToMiliseconds(duration: string) {
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:19]: 🙌

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx (hunk 1 above)
Comment (konrad147) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:59]: Yes, of course!

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx [hunk 8]
```diff
@@ -15,17 +16,24 @@ import { RuleEditorSection } from './RuleEditorSection';
...
     message: 'Required.',
   },
   pattern: durationValidationPattern,
   validate: (value) => {
-    const evaluateEveryDuration = parseDuration(evaluateEvery);
-    const forDuration = parseDuration(value);
-    const millisFor = durationToMilliseconds(forDuration);
-    const millisEvery = durationToMilliseconds(evaluateEveryDuration);
+    // 0 is a special value meaning for equals evaluation interval
+    if (value === '0' || value === '0s') {
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:31]: I'm wondering if `0m` etc. are also accepted options.

Comment (konrad147) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:31]: They should be https://github.com/grafana/grafana/issues/52491

Comment (gillesdemey) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:31]: Should we use a regular expression instead like `0([mnuµ]?s)|m|h`?

**Review by gillesdemey — APPROVED** [review]
LGTM, just one concern about the special meaning for `0` and other time formats

File: public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx (hunk 8 above)
Comment (konrad147) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:31]: Ah, sorry I misread your first comment. I'm checking the other zeros :)

Comment (konrad147) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:31]: The backend accepts `0m` and `0h` but it always sets `0s` in that case (same as just for plain 0). Should we allow them?

Comment (konrad147) [reply public/app/features/alerting/unified/components/rule-editor/GrafanaEvaluationBehavior.tsx:31]: I'll allow them. If it's something we can parse as a `0` then it's ok (there is an additional pattern validation already)

**Review by grobinson-grafana — APPROVED** [review]

File: public/app/features/alerting/unified/RuleEditor.test.tsx [hunk 9]
```diff
@@ -35,7 +35,7 @@ jest.mock('./components/rule-editor/ExpressionEditor', () => ({
 
 jest.mock('./api/buildInfo');
 jest.mock('./api/ruler');
-jest.mock('./utils/config');
+// jest.mock('./utils/config');
```
Comment (peterholmberg) [inline public/app/features/alerting/unified/RuleEditor.test.tsx:38]: should we remove this line?

**Review by peterholmberg — COMMENTED** [review]
Nit :)

**Review by gillesdemey — APPROVED** [review]
