### PR TITLE
Library Panels: Fix refresh when changing to angular library panel

### LINKED ISSUE #34874: Library panels loose fidelity in certain workflows.
### What happened

The library panel only displays 1 series of data (a different metric) when two are expected. 

Screen Shot 2021-05-27 at 9 13 13 AM

## What I expected to happen

The library panel would show 2 series of data:

Screen Shot 2021-05-27 at 3 32 32 PM

### How to reproduce it

1. Create a library panel from a (legacy) Graph Panel:
Screen Shot 2021-05-27 at 3 32 39 PM

2. Add an empty panel:
Screen Shot 2021-05-27 at 3 33 36 PM

3. Change the panel type to a library panel and pick the library panel in question:
Screen Shot 2021-05-27 at 3 15 22 PM

4. Panel appears with no data and the wrong query:
Screen Shot 2021-05-27 at 3 15 40 PM

5. There's no way to proceed without saving the panel and breaking it everywhere:
Screen Shot 2021-05-27 at 3 35 21 PM

_Originally posted by @pkolyvas in https://github.com/grafana/grafana/issues/34624#issuecomment-849857559_

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Fixes an issues where the panel would not refresh when changing from a React panel to an Angular library panel, caused by the refresh event listener not being set up by the time it is published.

**Which issue(s) this PR fixes**:
Closes #34874

### CODE REVIEW

File: public/app/features/library-panels/components/PanelLibraryOptionsGroup/PanelLibraryOptionsGroup.tsx [hunk 1]
```diff
@@ -55,8 +55,12 @@ export const PanelLibraryOptionsGroup: FC<Props> = ({ panel, searchQuery }) => {
 
     panel.configRev = 0;
     panel.refresh();
-    panel.events.publish(new PanelQueriesChangedEvent());
-    panel.events.publish(new PanelOptionsChangedEvent());
+    const unsubscribeEvent = panel.events.subscribe(PanelDirectiveReadyEvent, () => {
+      panel.refresh();
```
Comment (hugohaggmark) [inline public/app/features/library-panels/components/PanelLibraryOptionsGroup/PanelLibraryOptionsGroup.tsx:59]: Maybe we should remove `panel.refresh();` on line 57?

**Review by hugohaggmark — APPROVED** [review]
Elegant solution and works as expected 🎉

File: public/app/features/library-panels/components/PanelLibraryOptionsGroup/PanelLibraryOptionsGroup.tsx (hunk 1 above)
Comment (hugohaggmark) [reply public/app/features/library-panels/components/PanelLibraryOptionsGroup/PanelLibraryOptionsGroup.tsx:59]: Aha, ok I understand thank you for clarifying it. Maybe we should add a comment about this or add it to React panels too as you already suggested 👍

**Comment by hugohaggmark** [comment]
@kaydelaney friendly reminder to add backport, approve the backport and merge it. Thank you!
