### PR TITLE
Dashboards: Fix getVariablesCompability

### LINKED ISSUE #121796: Section level variables: fix getVariablesCompatibility
When `getVariablesCompatibility` is called with the top level scene object (`DashboardScene`) it should only return dashboard level variables not all variables in all sections, this will break existing stuff that relies only on getting dashboard level variables.

Ref https://github.com/grafana/grafana/pull/119572#discussion_r3029651207

### PR DESCRIPTION
**Pull request by harisrozajac**
Alternative to https://github.com/grafana/grafana/pull/121788

It removes `collectAllVariables` and defaults to returning only dashboard-level variables. This is so we don't introduce any breaking behavior for the panel plugins that rely on `templateSrv.getVariables` where only global variables are expected. 

Fixes a bug with editing a query variable where the same variable was referenced in its own query editor. 

Fixes #121796

### CODE REVIEW

File: public/app/features/dashboard-scene/utils/getVariablesCompatibility.ts [hunk 1]
```diff
@@ -19,23 +19,22 @@ export function getVariablesCompatibility(sceneObject: SceneObject): TypedVariab
   // the same section + dashboard globals.
   if (sceneObject instanceof DashboardScene) {
     const selectedObject = sceneObject.state.editPane.getSelectedObject();
-    if (selectedObject && selectedObject !== sceneObject) {
+    const isQueryVariable = selectedObject instanceof QueryVariable;
```
Comment (torkelo) [inline public/app/features/dashboard-scene/utils/getVariablesCompatibility.ts]: It feels hacky to have get selected object here. getVariablesCompatibility already has a sceneObject argument that could act as the context. Any way we can pass the context to DataSourecPicker (then to useDataSources, then `templateSrv.getVariables` so that sceneObject here is the correct context 

I guess it would mean updating useDataSources , dataSourceSrv.getList and TemplateSrv.getVariables. Hm... a bit messy maybe. I guess we could do it via ScopedVars arg. I'm not sure, but let's keep it like this for now.

the other thing that feels hacky here is the instanceof QueryVariable. 

that also feels unnecessary/irrelevant. Either you use the selectedObject as the context/starting point or not. And then in collectAncestorVariables you can just ignore variables that are equal to that starting point obj ref

Comment (harisrozajac) [reply public/app/features/dashboard-scene/utils/getVariablesCompatibility.ts]: @torkelo agree with you that this is hacky, but yeah let's keep it like this for now 

i've removed the logic for instanceof QueryVariable

**Review by torkelo — APPROVED** [review]
