### PR TITLE
DashboardScene: Fix dashboard clear when row repeating with non-existing variable

### LINKED ISSUE #89089: Dashboard scenes: Changing a variable to a non existing custom value causes the dashboard to clear.
The dashboard: https://ops.grafana-ops.net/d/gKxo0tnVk/right-sizing?var-datasource=000000134&var-cluster=ops-eu-south-0&var-namespace=agent-logs&var-container=$__all

Reproduce by typing into the cluster variable dropdown and hitting enter, setting the variable to a custom value.

Slack thread (contains screen recording of the problem): https://raintank-corp.slack.com/archives/C03KVDHTWAH/p1718126876754899

### PR DESCRIPTION
**Pull request by axelavargas**
**What is this feature?**
We added an empty variable placeholder when the row was repeating and the variable was returning empty values.

https://github.com/grafana/grafana/assets/239999/b8b0893f-f79c-4e11-b867-702b3712541a

**Which issue(s) does this PR fix?**:

Fixes #89089

### CODE REVIEW

**Review by ivanortegaalba — APPROVED** [review]
Thank you so much for the quick fix!! It looks great!

File: public/app/features/dashboard-scene/scene/RowRepeaterBehavior.ts [hunk 1]
```diff
@@ -99,10 +99,18 @@ export class RowRepeaterBehavior extends SceneObjectBase<RowRepeaterBehaviorStat
 
     let maxYOfRows = 0;
 
+    const emptyVariablePlaceholderOption = {
+      values: ['placeholder'],
```
Comment (torkelo) [inline public/app/features/dashboard-scene/scene/RowRepeaterBehavior.ts:103]: @axelavargas 
not sure "placeholder" is a good emtpy value, maybe an empty string is better?
