### PR TITLE
Alerting: Fix escaping of silence matchers in utf8 mode

### LINKED ISSUE #94320: Silences: Unable to preview matched alerts when creating a new silence on AMP Alertmanager
### What happened?

Since upgrading from 11.2.0 to either 11.2.1 or 11.2.2 we are unable to ~~add~~  preview a silence in Grafana. We use an alertmanager datasource for this which is hosted in Amazon Managed Prometheus.

This is an on-prem deployment of OSS Grafana.

When adding a matcher such as alertname = a

We get an error: 
Error: maxFailure (quorum) on a given error family, addr=<IP> state=ACTIVE zone=eu-west-2b, rpc error: code = Code(400) desc = "bad matcher format: \"alertname\"=\"a\""

Rolling back to 11.2.0 this works fine.

Image

### What did you expect to happen?

I expected Grafana to find any firing alerts and show them as items that would be silenced by matcher query, it willl allow me to save that silence but i don't see what alerts i'll be silencing (no preview)

### Did this work before?

Worked in Grafana 11.2.0 and earlier.

### How do we reproduce it?

1. Alertmanager instance added to Grafana using Prometheues or Cortex, where the backend is Amazon Managed Prometheus.
2 Add any alert silence matchers
3. Watch it fail on 'Bad Matchers'

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.2.1 or later
OS: macOS 15
Browser: Chrome 129.0.6668.90 

### Grafana platform?

Kubernetes

### Datasource(s)?

Alertmanager

### LINKED ISSUE #94580: create Silence alert rule: bad matcher format: \"alertname\"=\
### What happened?

Image

### What did you expect to happen?

create Silence alert rule successfully

### Did this work before?

no

### How do we reproduce it?

1. add alter rule and trigger it
2. silence the alert as gif show
(the alertmanager is from mimir build in)

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: Grafana v11.2.2 (dbf571744d)
OS: macos15 docker desktop Docker Engine v27.2.0
Browser: edge
Mimir: 2.14.0

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by tomratcliffe**
**What is this feature?**

This PR prevents the "silences preview" feature from not showing any results on older versions of Prometheus or Mimir with `utf8_strict_mode` disabled.

**Which issue(s) does this PR fix?**:

Fixes #94320
Fixes #94580

### CODE REVIEW

File: public/app/features/alerting/unified/api/alertmanagerApi.ts [hunk 1]
```diff
@@ -72,9 +73,13 @@ export const alertmanagerApi = alertingApi.injectEndpoints({
         // TODO Add support for active, silenced, inhibited, unprocessed filters
         const filterMatchers = filter?.matchers
           ?.filter((matcher) => matcher.name && matcher.value)
-          .map(
-            (matcher) => `${wrapWithQuotes(matcher.name)}${matcherToOperator(matcher)}${wrapWithQuotes(matcher.value)}`
-          );
+          .map((matcher) => {
+            return encodeMatcher({
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/api/alertmanagerApi.ts]: nit: we can use `matcherToMatcherField()` here to avoid some code duplication – I've appended that to the PR

**Review by gillesdemey — APPROVED** [review]
