### PR TITLE
Alerting: Fix image rendering and uploading timeout preventing to send alert notifications

### LINKED ISSUE #21018: Alert is not sent if render hangs
**What happened**:
I have some problem with image rendering. I tried PhantomJS and external renderer and still have similar result. 
But what is really bad that when render is broken Grafana do not send any alert notification. 

So I disable images in alert notifications.

**What you expected to happen**:
Grafana send alert notification even if it can't render image.

**How to reproduce it (as minimally and precisely as possible)**:
* Break your image rendering
* Trigger alert
* Got nothing in your notification channels

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: Any
- OS Grafana is installed on: Docker

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Continuation of #17688 and will make  #18011 obsolete/not needed.

**Which issue(s) this PR fixes**:
Fixes #21018 

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/alerting/notifier_test.go [hunk 1]
```diff
@@ -38,21 +39,81 @@ func TestNotificationService(t *testing.T) {
 		require.Truef(t, evalCtx.Ctx.Value("notificationSent").(bool), "expected notification to be sent, but wasn't")
 	})
 
-	notificationServiceScenario(t, "SendIfNeeded should not render and upload image, but send notification", evalCtx, false, func(scenarioCtx *scenarioContext) {
+	notificationServiceScenario(t, "Given alert rule with upload image disabled should not render and upload image, but send notification", evalCtx, false, func(scenarioCtx *scenarioContext) {
 		err := scenarioCtx.notificationService.SendIfNeeded(evalCtx)
 		require.NoError(t, err)
 
 		require.Equalf(t, 0, scenarioCtx.renderCount, "expected render to be called, but wasn't")
 		require.Equalf(t, 0, scenarioCtx.imageUploadCount, "expected image to be uploaded, but wasn't")
```
Comment (aknuds1) [inline pkg/services/alerting/notifier_test.go]: Is the error message misleading? Isn't the expectation rather that the image was _not_ uploaded?

File: pkg/services/alerting/notifier_test.go [hunk 2]
```diff
@@ -38,21 +39,81 @@ func TestNotificationService(t *testing.T) {
...
+				break
+			case <-wait:
+			}
+
+			return nil, nil
+		}
+		err := scenarioCtx.notificationService.SendIfNeeded(evalCtx)
+		require.NoError(t, err)
+
+		require.Equalf(t, 0, scenarioCtx.renderCount, "expected render to be called, but wasn't")
```
Comment (aknuds1) [inline pkg/services/alerting/notifier_test.go]: Isn't the error message misleading here, since the expected render count is 0?

File: pkg/services/alerting/notifier_test.go [hunk 3]
```diff
@@ -38,21 +39,81 @@ func TestNotificationService(t *testing.T) {
...
+		require.Equalf(t, 0, scenarioCtx.imageUploadCount, "expected image to be uploaded, but wasn't")
```
Comment (aknuds1) [inline pkg/services/alerting/notifier_test.go]: Isn't the error message misleading here, since no image should be uploaded?

File: pkg/services/alerting/notifier_test.go [hunk 4]
```diff
@@ -38,21 +39,81 @@ func TestNotificationService(t *testing.T) {
...
+			case <-wait:
+			}
+
+			return "", nil
+		}
+		err := scenarioCtx.notificationService.SendIfNeeded(evalCtx)
+		require.NoError(t, err)
+
+		require.Equalf(t, 1, scenarioCtx.renderCount, "expected render to be called, but wasn't")
+		require.Equalf(t, 0, scenarioCtx.imageUploadCount, "expected image to be uploaded, but wasn't")
```
Comment (aknuds1) [inline pkg/services/alerting/notifier_test.go]: Isn't the error message misleading here, since the expectation is for the image not to be uploaded?

File: pkg/services/rendering/plugin_mode.go [hunk 5]
```diff
@@ -22,7 +23,7 @@ func (rs *RenderingService) renderViaPlugin(ctx context.Context, opts Opts) (*Re
 		return nil, err
 	}
 
-	ctx, cancel := context.WithTimeout(ctx, opts.Timeout)
+	ctx, cancel := context.WithTimeout(ctx, opts.Timeout+time.Second*2)
```
Comment (aknuds1) [inline pkg/services/rendering/plugin_mode.go]: Would it make sense to explain the reason for doubling the timeout with a comment here?

**Review by aknuds1 — CHANGES_REQUESTED** [review]
I think error messages in tests are misleading, unless I'm missing something.

File: pkg/services/rendering/plugin_mode.go (hunk 5 above)
Comment (marefr) [reply pkg/services/rendering/plugin_mode.go]: I noticed [http mode](https://github.com/grafana/grafana/blob/master/pkg/services/rendering/http_mode.go#L63) and [phantomjs](https://github.com/grafana/grafana/blob/master/pkg/services/rendering/phantomjs.go#L66) used that, but not the plugin mode. I guess the reasoning is that the image renderer service, plugin and phantomjs receives the timeout and times out after that time. By adding 2 additional seconds Grafana gives the image renderer service, plugin and phantomjs to timeout and return possible error message.

Comment (aknuds1) [reply pkg/services/rendering/plugin_mode.go]: @marefr Sorry, I meant a comment in the code, as a hint to future readers :D

Comment (aknuds1) [reply pkg/services/rendering/plugin_mode.go]: Ugh, I realize now I even misread the code, I thought that was a multiplication by 2 :man_facepalming:

Comment (marefr) [reply pkg/services/rendering/plugin_mode.go]: I added comments

**Review by aknuds1 — APPROVED** [review]
LGTM!

**Comment by marefr** [comment]
@hekmon thanks for your initial work and contributing to Grafana
