### PR TITLE
Dashboard: Fix for folder picker menu not being visible outside modal when saving dashboard

### LINKED ISSUE #24228: Select is cropped by the modal window
As seen in the dashboard save modal:

image

### PR DESCRIPTION
**Pull request by tskarhed**
Fixes #24228

Tested with
- Dashboard import
- Save as modal

Please test this in places where this has been a known problem before.

Screenshot from 2020-05-05 17-29-41
Screenshot from 2020-05-05 17-29-54

### CODE REVIEW

File: packages/grafana-ui/src/components/Select/SelectBase.tsx [hunk 1]
```diff
@@ -312,9 +312,6 @@ export function SelectBase<T>({
         }}
         styles={{
           ...resetSelectStyles(),
-          menuPortal: () => ({
-            zIndex: theme.zIndex.dropdown,
-          }),
```
Comment (torkelo) [inline packages/grafana-ui/src/components/Select/SelectBase.tsx:317]: I think this will break other stuff, without this the menu portal will use the wrong zIndex. 

What z-index will menuPortal use by default? If not set here?

Comment (torkelo) [reply packages/grafana-ui/src/components/Select/SelectBase.tsx:317]: https://github.com/grafana/grafana/pull/23786

Comment (tskarhed) [reply packages/grafana-ui/src/components/Select/SelectBase.tsx:317]: 1, but I think I have a better solution incoming.

**Review by torkelo — APPROVED** [review]
