### PR TITLE
Playlists: Added RBAC backend support - DO NOT MERGE UNTIL FRONTEND MERGES

### LINKED ISSUE #115712: Playlists: Add RBAC support
After recent changes from the auth team, a user with `None` role should not have access to any API. 
This change [breaks some customers use cases](https://github.com/grafana/support-escalations/issues/19886) and because Playlists does not support RBAC this can't be solved without adding the `Viewer` role to users.
For now, [we have added an exception](https://github.com/grafana/grafana/pull/115713) to continue supporting this behavior. but [this line](https://github.com/grafana/grafana/blob/9c3cdd4814929a29df18b7325eedbdbda0feddc8/pkg/services/apiserver/auth/authorizer/role.go#L19) should be removed once implemented.

We need to add RBAC support to playlists to fix this issue properly.

### PR DESCRIPTION
**Pull request by CollinFingar**
**What is this feature?**
Adds proper RBAC support for playlists: declares playlists:read and playlists:write fixed roles, replaces the k8s API org-role authorizer with an RBAC evaluator, and removes the temporary None-role hotfix.

**Why do we need this feature?**
There was no way for admins to grant playlist access to None-role users (e.g. kiosk/display accounts) without elevating their org role. A temporary hotfix was granting all None-role users viewer-level access to the playlist API, which was overly permissive.

**Who is this feature for?**
Grafana admins who need to grant playlist access to service accounts or kiosk users without changing their org role.

**Which issue(s) does this PR fix?**:

Fixes #115712

**Special notes for your reviewer:**
The frontend PR (collinfingar/playlists-rbac-support-fe) should be merged first. Requires the companion enterprise PR on collinfingar/playlists-rbac-support-be. The nav item uses playlists:read with a HasRole(Viewer) fallback for MT safety. 

Dashboards note: a None-role user with only playlists:read will see a blank screen during playback — the playlist player requires a separate dashboards:read grant. Admins enabling kiosk accounts should grant both.

With this [Frontend Precursor PR](https://github.com/grafana/grafana/pull/119974) and [this Enterprise Backend PR](https://github.com/grafana/grafana-enterprise/pull/11228)

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

Testing instructions!
- Use `collinfingar/playlists-rbac-support` for both OSS and Enterprise as these have all changes together.

Testing results:
- Viewer/Editor/Admin — nav shows, write buttons appear for Editor+, no regressions
- None (no grant) — nav hidden, all API calls denied
- None + playlists:read — nav shows, list/get works, write buttons hidden, playback blank (expected — needs separate dashboards:read)
- None + playlists:write — nav shows, write buttons visible
- None + playlists:read + dashboards:read — full kiosk playback works

### CODE REVIEW

**Review by baldm0mma — APPROVED** [review]

**Comment by baldm0mma** [comment]
From Claude: "This is a clean, well-reasoned change that properly fixes a security hole (overpermissive None-role access) without regressing normal users." I agree! 😎

File: pkg/registry/apps/playlist/register.go [hunk 1]
```diff
@@ -68,8 +81,39 @@ func RegisterAppInstaller(
 }
 
 func (p *AppInstaller) GetAuthorizer() authorizer.Authorizer {
-	//nolint:staticcheck // not yet migrated to Resource Authorizer
-	return roleauthorizer.NewRoleAuthorizer()
+	return authorizer.AuthorizerFunc(
```
Comment (ArturWierzbicki) [inline pkg/registry/apps/playlist/register.go:68]: cc @charandas can you ptal?

File: pkg/services/navtree/navtreeimpl/navtree.go [hunk 2]
```diff
@@ -369,7 +370,11 @@ func (s *ServiceImpl) buildDashboardNavLinks(c *contextmodel.ReqContext) []*navt
 	dashboardChildNavs := []*navtree.NavLink{}
 
 	if c.IsSignedIn {
-		if c.HasRole(org.RoleViewer) {
+		// Show Playlists nav if the user has the RBAC playlists:read permission.
+		// If playlists:read is not present (old backend not yet deployed), fall back to
+		// the legacy org-role check so Viewers don't lose the nav item during a
+		// mixed-version rollout.
+		if hasAccess(ac.EvalPermission(playlistregistry.ActionPlaylistsRead)) || c.HasRole(org.RoleViewer) {
```
Comment (evictorero) [inline pkg/services/navtree/navtreeimpl/navtree.go]: We should gate this behind a feature flag.

File: pkg/registry/apps/playlist/accesscontrol.go [hunk 3]
```diff
@@ -0,0 +1,48 @@
+package playlist
+
+import (
+	"github.com/grafana/grafana/pkg/services/accesscontrol"
+	"github.com/grafana/grafana/pkg/services/org"
+)
+
+const (
+	ActionPlaylistsRead  = "playlists:read"
+	ActionPlaylistsWrite = "playlists:write"
```
Comment (evictorero) [inline pkg/registry/apps/playlist/accesscontrol.go:10]: Add these new permissions to the file https://github.com/grafana/grafana/blob/8329b345a6f8062e129606232d73e181bc0c69b4/docs/sources/administration/roles-and-permissions/access-control/rbac-fixed-basic-role-definitions/index.md

File: pkg/services/apiserver/auth/authorizer/role.go [hunk 4]
```diff
@@ -15,8 +15,6 @@ var _ authorizer.Authorizer = &roleAuthorizer{}
 
 var orgRoleNoneAsViewerAPIGroups = []string{
 	"productactivation.ext.grafana.com",
-	// playlist can be removed after this issue is resolved: https://github.com/grafana/grafana/issues/115712
-	"playlist.grafana.app",
```
Comment (evictorero) [inline pkg/services/apiserver/auth/authorizer/role.go:19]: We should keep this until this change is fully turned on. We could gate this behind the same feature flag.

File: pkg/registry/apps/playlist/accesscontrol.go [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+)
+
+var (
+	ScopeProviderPlaylists = accesscontrol.NewScopeProvider("playlists")
+	ScopeAllPlaylists      = ScopeProviderPlaylists.GetResourceAllScope()
```
Comment (evictorero) [inline pkg/registry/apps/playlist/accesscontrol.go]: I don't think we want to implement permissions using Scopes, at least, this PR is not using it and I don't think we would like to use it in the future.

File: pkg/services/accesscontrol/permreg/permreg.go [hunk 6]
```diff
@@ -101,6 +101,7 @@ func newPermissionRegistry() *permissionRegistry {
 		"inhibition-rules":    "inhibition-rules:uid:",
 		"secret.securevalues": "secret.securevalues:uid:",
 		"secret.keepers":      "secret.keepers:uid:",
+		"playlists":           "playlists:uid:",
```
Comment (evictorero) [inline pkg/services/accesscontrol/permreg/permreg.go]: Not needed if we don't use Scopes.

**Review by evictorero — COMMENTED** [review]
We need to gate all these changes behind a feature flag so we can turn the feature on, targeting a minimum version. With this approach, we would also remove the dependency mentioned in the Title of this PR.

File: pkg/services/navtree/navtreeimpl/navtree.go (hunk 2 above)
Comment (CollinFingar) [reply pkg/services/navtree/navtreeimpl/navtree.go]: Done

File: pkg/registry/apps/playlist/accesscontrol.go (hunk 3 above)
Comment (CollinFingar) [reply pkg/registry/apps/playlist/accesscontrol.go:10]: [Here they are](https://github.com/grafana/grafana/pull/119975/changes#diff-e66bc6b6e08450ddd01991ad48dfeb53b33076ecfa3ae8c479cbc70b1a42bbccR141-R142)

File: pkg/services/apiserver/auth/authorizer/role.go (hunk 4 above)
Comment (CollinFingar) [reply pkg/services/apiserver/auth/authorizer/role.go:19]: [I moved this to the playlists repo and behind a toggle](https://github.com/grafana/grafana/pull/119975/changes#diff-b068db21c0960d1431567ca10bd356826caf7a7399a7637ba60224d428c4e8f1R74-R87). What do you think?

File: pkg/registry/apps/playlist/accesscontrol.go (hunk 5 above)
Comment (CollinFingar) [reply pkg/registry/apps/playlist/accesscontrol.go]: Removed

File: pkg/services/accesscontrol/permreg/permreg.go (hunk 6 above)
Comment (CollinFingar) [reply pkg/services/accesscontrol/permreg/permreg.go]: Removed

**Review by baldm0mma — APPROVED** [review]

File: pkg/registry/apps/playlist/register.go [hunk 7]
```diff
@@ -46,6 +65,53 @@ func RegisterAppInstaller(
...
+			if !attr.IsResourceRequest() {
+				return authorizer.DecisionNoOpinion, "", nil
+			}
+
+			//nolint:staticcheck // not yet migrated to OpenFeature
+			if !p.features.IsEnabledGlobally(featuremgmt.FlagPlaylistsRBAC) {
+				// Hotfix: grant None-role users viewer-level access until the toggle is enabled.
+				// All other roles are handled by the default role authorizer.
+				user, err := identity.GetRequester(ctx)
+				if err != nil || user.GetOrgRole() != org.RoleNone {
```
Comment (evictorero) [inline pkg/registry/apps/playlist/register.go]: I think in case of `err != nil` we should return `authorizer.DecisionDeny` like below.
We can call `user, err := identity.GetRequester(ctx)` outside this if and use that user.
Basically moving up the below code block:
```
			user, err := identity.GetRequester(ctx)
			if err != nil {
				return authorizer.DecisionDeny, "valid user is required", err
			}
```

File: pkg/services/apiserver/auth/authorizer/role.go (hunk 4 above)
Comment (evictorero) [reply pkg/services/apiserver/auth/authorizer/role.go:19]: Looks good, please create an issue to track this removal.

**Review by evictorero — APPROVED** [review]
LGTM, tested and works as expected. Please read my last comment before merge.

File: pkg/services/apiserver/auth/authorizer/role.go (hunk 4 above)
Comment (CollinFingar) [reply pkg/services/apiserver/auth/authorizer/role.go:19]: Created! https://github.com/grafana/grafana/issues/122124

File: pkg/registry/apps/playlist/register.go (hunk 7 above)
Comment (CollinFingar) [reply pkg/registry/apps/playlist/register.go]: Nice point, updated
