### PR TITLE
InfluxDB: Improve legend labels for InfluxDB query results

### LINKED ISSUE #36534: Legend displays "_value" before series label for InfluxDB Flux query results.
In previous versions of Grafana (version 7.20 was tested), FLUX queries for InfluxDB resulted in visualizations where series labels (in the legend) were based on the remaining tags on the data.  So, for example, if your data includes the _time, _value, and a "loc" tag, the legend automatically would show the value of the "loc" tag if it was the sole remaining tag.

Migrating to release 8.4.0 (v8.0.4 (81fef5b4b4)), the legend for each of the data series is now prefaced with "_value".  A workaround is to modify the Standard Options -> Display Name field on the visualization to "${__field.labels.__values}".

The problem with this approach is that while the legend displays the value without embellishment, if you click on a value in the legend to filter the result, the chart blanks instead of only showing the selected series.

Reproducing the issue: In order to reproduce, simply run a Flux query that returns only a _time, _value, and one extra tag in version 8.4.  The problem occurs with most of the visualizations, but start with the time series visualization and enable the legend.  Note that each of the values are prefaced with the word "_value ".  In the attached images, the names of air handling units (e.g. AHU31) are prefaces with "_value".  Please note that when using the exact same queries in version 7.2, this problem did not occur.

**Environment**:
- Grafana version: v8.0.4 (81fef5b4b4)
- Data source type & version: Data Source = Influxdb set to FLUX option
- OS Grafana is installed on: Running on Docker
- User OS & Browser: Firefox 89.0.2 (64-bit)
Screen Shot 2021-07-07 at 3 22 18 PM
Screen Shot 2021-07-07 at 3 25 09 PM

### PR DESCRIPTION
**Pull request by gabor**
when parsing flux database responses we try to detect certain patterns (as simple queries) and make the result easier to visualize in grafana (this means adjusting field-names and label-names).

this pull-request does some of this, making the behavior closer to what it was in grafana7:

when there is a single timestamp-column named "_time" and a single non-timestamp-column named "_value":
- we rename "_time" to "Time"
- we choose a new name for "_value": the old behavior was that we try to use the value from the "_field" tag, otherwise we keep "_value". the new behavior also tries the "_field", but if not found, it uses the name "Value".

these changes should make using the grafana visualizations easier, because those prefer timestamp columns named "Time" and value-columns named "Value".

fixes https://github.com/grafana/grafana/issues/36534

to test the use-case mentioned in the github issue:

- `make devenv sources=influxdb`
- go to explore in grafana, choose the `gdev-influxdb-flux` data source
- use this query:
```
from(bucket: "mybucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_idle")
  |> map(fn: (r) => ({
    _time: r._time, _value: r._value, cpu: r.cpu
  }))
  ```
- (the `map` part makes sure we only have 3 fields in the csv-result: `_time`, `_value` and `cpu` (the label))
- run the query in explore, verify that the graph-legend says this: `cpu_total`, `cpu0`, `cpu1`, `cpu2`, `cpu3` (for comparison, on `main-branch` the legend would be: `_value cpu-total`, `_value cpu0` and so on)

### CODE REVIEW

File: pkg/tsdb/influxdb/flux/builder.go [hunk 1]
```diff
@@ -207,7 +209,11 @@ func (fb *frameBuilder) Init(metadata *query.FluxTableMetadata) error {
 	if hasSimpleTimeCol && (len(nonTimestampCols) == 1) && (nonTimestampCols[0].name == "_value") {
 		// there is a simple timestamp column, and there is a single non-timestamp value column
 		// named "_value". we decide that this is "the" value-column.
-		nonTimestampCols[0].isTheSingleValue = true
+		nonTimestampCols[0].isTheSimpleValue = true
+
+		// now that we know that there is both a single correctly named timestamp column
```
Comment (aocenas) [inline pkg/tsdb/influxdb/flux/builder.go:214]: I wonder if it wouldn't make more sense to have these comments where the field is defined in the struct to explain what the field and true/false values mean in a single place.

**Review by aocenas — APPROVED** [review]
left one nitpick otherwise works well

File: pkg/tsdb/influxdb/flux/builder.go (hunk 1 above)
Comment (gabor) [reply pkg/tsdb/influxdb/flux/builder.go:232]: thanks, i added a comment to that place for now, later maybe some comment-refactoring will be needed :)
