### PR TITLE
Alerting: Fix NoData & Error alerts not resolving when rule is reset

### LINKED ISSUE #80182: Alerting: NoData & Error alerts are not resolved when rule is reset
### What happened?

Resetting (deleting, updating, pausing) an alert rule that is set to map no data to `DatasourceNoData` or datasource errors to `DatasourceError` will not send an alert to the configured alertmanager(s) (GMA or otherwise) to resolve any active `DatasourceNoData` or `DatasourceError` alerts.

Peek 2024-01-08 23-50

### What did you expect to happen?

When resetting (deleting, updating, pausing) an alert rule that is set to map no data to `DatasourceNoData` or datasource errors to `DatasourceError` any active `DatasourceNoData` or `DatasourceError` should be resolved in the configured alertmanager(s).

### Did this work before?

Likely not for a while. Bug exists in v9.4+ at least.

### How do we reproduce it?

1. Create an alert that will evaluate as no data and ensure that the no data is mapped to create a `DatasourceNoData` alert.
2. Wait until the `DatasourceNoData` alert instance begins firing. Verify there is an entry in the alertmanager (http://localhost:3000/api/alertmanager/grafana/api/v2/alerts)
3. Reset the rule (pausing or deleting it is easiest, but you can also update the rule so that it will resolve) and wait until you see log lines for `Rules state was reset` and `Sending alerts to local notifier`.
4. Verify that the active alert in the alertmanager has not been resolved/expired. (http://localhost:3000/api/alertmanager/grafana/api/v2/alerts)

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: v9.4+ and likely earlier.

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by JacobsonMT**
**What is this feature?**

On rule reset, when creating the PostableAlerts StateToPostableAlert did not attach the correct NoData/Error alertname and rulename labels to expire/resolve the active alerts when the previous cached state was NoData/Error.

**Why do we need this feature?**

Fixes `DatasourceNoData` & `DatasourceError` alerts not resolving when the rule is reset.

**Who is this feature for?**

Alerting users.

**Which issue(s) does this PR fix?**:

Fixes #80182

**Special notes for your reviewer:**

Before:
Peek 2024-01-08 23-50

After:
Peek 2024-01-08 23-46

### CODE REVIEW

File: pkg/services/ngalert/state/compat.go [hunk 1]
```diff
@@ -71,11 +72,19 @@ func StateToPostableAlert(alertState *State, appURL *url.URL) *models.PostableAl
 		urlStr = ""
 	}
 
-	if alertState.State == eval.NoData {
+	state := alertState.State
+	if alertState.Resolved && state == eval.Normal {
```
Comment (grobinson-grafana) [inline pkg/services/ngalert/state/compat.go:76]:
```suggestion
	if alertState.Resolved {
```

What would happen if we just checked `alertState.Resolved`? It should be an invariant that this cannot be true while state is something other than `eval.Normal`, right?

**Review by grobinson-grafana — COMMENTED** [review]
I think this is fine, I'll wait for a second review from @yuri-tceretian.

File: pkg/services/ngalert/state/compat.go (hunk 1 above)
Comment (yuri-tceretian) [reply pkg/services/ngalert/state/compat.go:76]: I agree with George, this change https://github.com/grafana/grafana/pull/80184/files#diff-6420fa5148996efbf754b18838902601c17b758ab7da6279dc019b5b143fd5c2R220  guarantees that the states will have Resolved=true, and this additional check does not seem to be needed.

Comment (JacobsonMT) [reply pkg/services/ngalert/state/compat.go]: Fixed: https://github.com/grafana/grafana/pull/80184/commits/e52412da8d2c5cc130f7f7acb49fd810650cfb9b

**Review by yuri-tceretian — APPROVED** [review]
LGTM
