### PR TITLE
Table Panel: Add ability to use text color for value or hide value in gauge cell

### LINKED ISSUE #45442: Table: Bar gauge cell display mode with varying value lengths in a narrow column creates miss-alignment
**What happened**: The LCD gauge display mode div is incorrect if, for example, a 3-digit number is displayed after 1000. The last LED is one more than the 4-digit higher value.

See value: "978"
image

Setting of this column:
image

**Environment**:
- Grafana version: v8.3.3 (30bb7a93ca)
- User OS & Browser: Chrome 98.0.4758.102 Windows 64 bit

### PR DESCRIPTION
**Pull request by torkelo**
So now that we have cell options we can add more options to specific cell modes. 

This option is something I have been wanting to add for ages (and @ryantxu as well) 

* [x] Add new value display mode: Color text (old default) | Text color | Hidden
* [x] Fix typings for TableCellOptions, the current typing could not take advantage of typescript union typing/discriminator as the TableAutoCellOptions supported all TableCellDisplayMode for it's type property. This break the union type benefits (of being able to check type and get the other props part of that type automatically). But was not able to type this in cue efficiently, had to create a specific type for each enum value. Due to cuetsy not supporting multiple enum values for a property.
* [x] Fixed sentence casing for some property names
* [x] Fixed double button margin in the editor
* [x] Update react table gdev test dashboard
* [x] Updated the logic in BarGaugeCell for supporting the old displayMode, could need extra review, I did not understand the existing code 

Open question
* Should we default to text color? ok breaking change or migrate current options to "color" and then make default text color 

Todo: 
* [x] Update bar gauge panel with options
* [x] Try to add some tests for BarGauge 
* [x] Docs 

Another value mode option we can explore in the future would be "inside" where the value is shown inside the bar 

Screenshot 2023-01-13 at 11 25 41

Screenshot 2023-01-13 at 12 20 51

Fixes #45442, #40925

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/BarGaugeCell.tsx [hunk 1]
```diff
@@ -35,32 +35,25 @@ export const BarGaugeCell: FC<TableCellProps> = (props) => {
...
-  // Support deprecated settings
-  const usingDeprecatedSettings = field.config.custom.displayMode !== undefined;
-
-  // If we're using the old settings format we read the displayMode directly from
-  // the cell options
-  if (usingDeprecatedSettings) {
-    if (
-      (field.config.custom && field.config.custom.cellOptions.displayMode === TableCellDisplayMode.Gauge) ||
-      (field.config.custom && field.config.custom.cellOptions.displayMode === BarGaugeDisplayMode.Lcd)
-    ) {
```
Comment (torkelo) [inline packages/grafana-ui/src/components/Table/BarGaugeCell.tsx:51]: I could not really understand this, why are we checking `cellOptions.displayMode` here? we have never had such a custom option

Comment (codeincarnate) [reply packages/grafana-ui/src/components/Table/BarGaugeCell.tsx:51]: Might be a mistake on my part there 😬

**Comment by codeincarnate** [comment]
Going to be taking a look at this later today 😄

**Comment by codeincarnate** [comment]
Going to try and get the changes from main merged since this duplicates some of the changes in https://github.com/grafana/grafana/pull/61582

**Comment by codeincarnate** [comment]
I have `main` merged locally but I think it might be messing up something as it seems like values aren't changing correctly when they're being edited. Looking into it further.

**Comment by codeincarnate** [comment]
Alright, looks like the value mode wasn't updating correctly. It had gotten lost in the merge somehow but was able to fix that. I _think_ I have everything merged together nicely. 

Would definitely appreciate your eyes on this again @torkelo if you have the chance

Otherwise I can cover the doc changes for this 😄

**Comment by torkelo** [comment]
@codeincarnate awesome! will take a look either later today or monday

**Comment by codeincarnate** [comment]
Going to take one more pass at this to merge and clean everything up so this can hopefully get merged before row based formatting

**Comment by codeincarnate** [comment]
Whoa, something went really off with this 😢. Not sure why there are so many pending changes now. Going to try to get this resolved

**Comment by codeincarnate** [comment]
Ok, another merge of main seemed to do the trick. Going to try to get this wrapped up today

File: packages/grafana-schema/src/common/common.gen.ts [hunk 2]
```diff
@@ -640,6 +649,7 @@ export interface TableImageCellOptions {
 export interface TableBarGaugeCellOptions {
   mode?: BarGaugeDisplayMode;
   type: TableCellDisplayMode.Gauge;
+  valueMode?: BarGaugeValueMode;
```
Comment (mdvictor) [inline packages/grafana-schema/src/common/common.gen.ts:652]: More of a naming nit: I think it would be more consistent to have `mode` renamed to `displayMode` alongside `valueMode`, or maybe rename `valueMode` to `valueDisplay`? Not entirely sure, but I feel it's a bit confusing right now.

File: packages/grafana-ui/src/components/BarGauge/BarGauge.tsx [hunk 3]
```diff
@@ -111,25 +112,37 @@ export class BarGauge extends PureComponent<Props> {
   }
 
   renderBasicAndGradientBars(): ReactNode {
-    const { value, showUnfilled } = this.props;
+    const { value, showUnfilled, valueMode: valueDisplayMode } = this.props;
```
Comment (mdvictor) [inline packages/grafana-ui/src/components/BarGauge/BarGauge.tsx:115]: Why are we renaming the `valueMode` here? It seems to be renamed only in a couple places.

File: packages/grafana-ui/src/components/BarGauge/BarGauge.tsx [hunk 4]
```diff
@@ -111,25 +112,37 @@ export class BarGauge extends PureComponent<Props> {
...
     const styles = getBasicAndGradientStyles(this.props);
 
     return (
       <div style={styles.wrapper}>
-        <FormattedValueDisplay
-          data-testid={selectors.components.Panels.Visualization.BarGauge.valueV2}
-          value={value}
-          style={styles.value}
-        />
+        {valueDisplayMode !== 'hidden' && (
```
Comment (mdvictor) [inline packages/grafana-ui/src/components/BarGauge/BarGauge.tsx:121]: Think we could use the enum here

File: packages/grafana-ui/src/components/BarGauge/BarGauge.tsx [hunk 5]
```diff
@@ -192,11 +205,13 @@ export class BarGauge extends PureComponent<Props> {
     return (
       <div style={containerStyles}>
         {cells}
-        <FormattedValueDisplay
-          data-testid={selectors.components.Panels.Visualization.BarGauge.valueV2}
-          value={value}
-          style={valueStyles}
-        />
+        {valueDisplayMode !== 'hidden' && (
```
Comment (mdvictor) [inline packages/grafana-ui/src/components/BarGauge/BarGauge.tsx:208]: Switch to enum value

File: packages/grafana-ui/src/components/BarGauge/BarGauge.tsx [hunk 6]
```diff
@@ -371,6 +392,11 @@ export function calculateBarAndValueDimensions(props: Props): BarAndValueDimensi
     valueHeight = height - titleDim.height;
     valueWidth = Math.max(Math.min(width * 0.2, MAX_VALUE_WIDTH), realValueWidth);
```
Comment (mdvictor) [inline packages/grafana-ui/src/components/BarGauge/BarGauge.tsx:393]: This could be an if...else so we don't do these calculations if `valueMode` is hidden

File: packages/grafana-ui/src/components/BarGauge/BarGauge.tsx [hunk 7]
```diff
@@ -363,6 +378,12 @@ export function calculateBarAndValueDimensions(props: Props): BarAndValueDimensi
     }
 
     valueWidth = width;
+
+    if (valueMode === BarGaugeValueMode.Hidden) {
```
Comment (mdvictor) [inline packages/grafana-ui/src/components/BarGauge/BarGauge.tsx:382]: This could be an if...else so we don't do the above calculations if valueMode is hidden

File: pkg/tests/api/alerting/api_alertmanager_test.go [hunk 8]
```diff
@@ -12,6 +12,7 @@ import (
 	"testing"
 	"time"
 
+	"github.com/grafana/grafana/pkg/expr"
```
Comment (mdvictor) [inline pkg/tests/api/alerting/api_alertmanager_test.go:15]: This import seems to be redeclared here

**Review by mdvictor — CHANGES_REQUESTED** [review]
Works great! I left some comments regarding code changes / nits.

File: packages/grafana-schema/src/common/common.gen.ts (hunk 2 above)
Comment (codeincarnate) [reply packages/grafana-schema/src/common/common.gen.ts:652]: I think you're right about this, probably best to call it `valueDisplayMode` or something similar.

Comment (mdvictor) [reply packages/grafana-schema/src/common/common.gen.ts:652]: Yes, or that!

File: pkg/tests/api/alerting/api_alertmanager_test.go (hunk 8 above)
Comment (codeincarnate) [reply pkg/tests/api/alerting/api_alertmanager_test.go:15]: Not sure where that snuck in 😓

**Comment by codeincarnate** [comment]
@mdvictor think I got all of the above resolved. Would appreciate another look! 🙏

**Review by mdvictor — APPROVED** [review]
LGTM

File: devenv/dev-dashboards/panel-table/table_tests_new.json [hunk 9]
```diff
@@ -451,7 +442,7 @@
         "y": 18
       },
       "id": 3,
-      "maxDataPoints": "10",
```
Comment (sdboyer) [inline devenv/dev-dashboards/panel-table/table_tests_new.json:478]: Manually changed this. i don't know how it's possible that we produce a string here, but either the schema should be updated (eww, ick, please no) or TS updated to ensure this is never allowed to be a string. tbqh, i'm not sure how this got allowed in the first place, given that we're using the generated type here...

**Comment by sdboyer** [comment]
OK, i've fixed the validation errors on devenv. Here's what i found.

For `devenv/dev-dashboards/panel-table/table_tests_new.json`, there were two issues, fixed in [this commit](https://github.com/grafana/grafana/pull/61477/commits/7f44520d9db882767015d520821df52e2773ce21). For `devenv/dev-dashboards/panel-bargauge/panel_tests_bar_gauge.json`, some fixes in [this commit](https://github.com/grafana/grafana/pull/61477/commits/8c143ffaeb16e7d5a4cd6f606dfb0345d8e55d67). I've made inline comments discussing each change. Pretty much all of them merit follow-ups.

File: devenv/dev-dashboards/panel-bargauge/panel_tests_bar_gauge.json [hunk 10]
```diff
@@ -143,8 +142,7 @@
             "steps": [
               {
                 "color": "blue",
-                "index": 0,
-                "value": null
```
Comment (sdboyer) [inline devenv/dev-dashboards/panel-bargauge/panel_tests_bar_gauge.json]: We needed to run `scripts/stripnulls.sh` (uugggghhhhhhhhh how is this still a thing)

File: kinds/dashboard/dashboard_kind.cue [hunk 11]
```diff
@@ -221,6 +221,8 @@ lineage: seqs: [
 					// TODO docs
 					color: string @grafanamaturity(NeedsExpertReview)
 					// TODO docs
+					index?: int32 @grafanamaturity(NeedsExpertReview)
```
Comment (sdboyer) [inline kinds/dashboard/dashboard_kind.cue:224]: Apparently this is an expected field here, but we just never had it? Either that, or the thresholds logic needs to be updated in order to remove what is ephemeral runtime state.

**Review by sdboyer — COMMENTED** [review]
OK, i've fixed the validation errors on devenv. Here's what i found.

For `devenv/dev-dashboards/panel-table/table_tests_new.json`, there were two issues, fixed in [this commit](https://github.com/grafana/grafana/pull/61477/commits/7f44520d9db882767015d520821df52e2773ce21). For `devenv/dev-dashboards/panel-bargauge/panel_tests_bar_gauge.json`, some fixes in [this commit](https://github.com/grafana/grafana/pull/61477/commits/8c143ffaeb16e7d5a4cd6f606dfb0345d8e55d67). I've made inline comments discussing each change. Pretty much all of them merit follow-ups.

**Comment by codeincarnate** [comment]
Thanks @sdboyer and @torkelo. Very nice to have this merged in and have the corresponding (long requested) issues closed out 🎉

**Comment by torkelo** [comment]
@codeincarnate great!
