### PR TITLE
TooltipPlugin2: Various fixes for different panel types

### LINKED ISSUE #77939: Status history tooltip: Incorrect tooltip values after refresh the panel
### What happened?

Tooltip has wrong values after refreshing data of the panel.

### What did you expect to happen?

Correct values inside tooltip.

### Did this work before?

Yes

### How do we reproduce it?

1. Open any Status history page
2. Refresh data of the panel
3. Hover on any status history panel's rectangle and check if there is a correct values

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/grafana/issues/77939

also fixes some hover logic with different tooltip modes and panels that may or may not have proximity-based hover via setSeries

### CODE REVIEW

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin2.tsx [hunk 1]
```diff
@@ -68,6 +79,12 @@ export const TooltipPlugin2 = ({ config, render }: TooltipPlugin2Props) => {
 
   const styles = useStyles2(getStyles);
 
+  const renderRef = useRef(render);
+  renderRef.current = render;
```
Comment (leeoniya) [inline packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin2.tsx:83]: this was the reason the data was not updated in the tooltip. (stale closure)

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin2.tsx [hunk 2]
```diff
@@ -190,7 +205,15 @@ export const TooltipPlugin2 = ({ config, render }: TooltipPlugin2Props) => {
...
     config.addHook('setLegend', (u) => {
-      let _isHoveringNow = _plot!.cursor.idxs!.some((v) => v != null);
+      let hoveredSeriesIdx = _plot!.cursor.idxs!.findIndex((v, i) => i > 0 && v != null);
+      let _isHoveringNow = hoveredSeriesIdx !== -1;
+
+      // in mode: 2 uPlot won't fire the proximity-based setSeries (below)
+      // so we set closestSeriesIdx here instead
+      // TODO: setSeries only fires for TimeSeries & Trend...not state timeline or statsus history
+      if (hoverMode === TooltipHoverMode.xyOne) {
+        closestSeriesIdx = hoveredSeriesIdx;
```
Comment (leeoniya) [inline packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin2.tsx:215]: this _should_ remove the need to do this downstream in the downstream components for StatusHistory and XYChart and Heatmap.

**Review by adela-almasan — APPROVED** [review]
