### PR TITLE
Secrets: Improve error handling for secrets manager plugin

### LINKED ISSUE #54653: Fatal crash in secrets migration when LockExecuteAndRelease fails to release
Will Browne reported this error:
```
Failed to start grafana. error: there is already a lock for this actionName: secret migration task 
there is already a lock for this actionName: secret migration task 
Exiting.
```

Most likely setup for this was pausing (with the debugger) in the middle of migration, then killing the process before the LockExecuteAndRelease function did the release. The next run, this happened.

Throwing an error is good, but it should not be fatal since the migrator runs regardless of if there are secrets. Maybe a big ugly warn instead.

### PR DESCRIPTION
**Pull request by guicaulada**
**What this PR does / why we need it**:

This PR improves error handling during secrets migration and plugin errors.

Previously plugin errors would result in an "Unrecognized message from plugin" error log which could be confusing, this solves this issue giving clear error messages and delegating any additional error log to the plugin itself where the errors can be detailed properly.

**Which issue(s) this PR fixes**:

Fixes #54653

**Special notes for your reviewer**:

This PR complements https://github.com/grafana/grafana-aws-secrets-manager/pull/31 but they are not dependent.

### CODE REVIEW

File: pkg/services/secrets/kvstore/migrations/migrator.go [hunk 1]
```diff
@@ -78,6 +78,10 @@ func (s *SecretMigrationProviderImpl) Migrate(ctx context.Context) error {
 			logger.Debug("Finished secret migration service", "service", serviceName)
 		}
 	})
+	if err != nil {
+		logger.Warn("Server lock for secret migration already exists")
```
Comment (mmandrus) [inline pkg/services/secrets/kvstore/migrations/migrator.go:82]: I think this should still be a logger.Error

File: pkg/services/secrets/kvstore/plugin.go [hunk 2]
```diff
@@ -255,7 +256,7 @@ func SetPluginStartupErrorFatal(ctx context.Context, kvstore *kvstore.Namespaced
 	return kvstore.Set(ctx, QuitOnPluginStartupFailureKey, "true")
 }
 
-func EvaluateRemoteSecretsPlugin(ctx context.Context, mg plugins.SecretsPluginManager, cfg *setting.Cfg) error {
+func EvaluateRemoteSecretsPlugin(ctx context.Context, mg plugins.SecretsPluginManager, cfg *setting.Cfg, hasStarted bool) error {
```
Comment (mmandrus) [inline pkg/services/secrets/kvstore/plugin.go:259]: This seems like a bit too much burden on people calling this function to know if the plugin should have started or not.

My thought is that we update the SecretsManagerPlugin interface to have a HasStarted func. Maybe whenever `mg.SecretsManager(ctx)` is called, that function should check if `self.SecretsManager != nil` and if so set an internal bool to true. HasStarted() can just return that bool and we can easily track if the plugin has started and then exited.

**Review by mmandrus — CHANGES_REQUESTED** [review]

File: pkg/services/secrets/kvstore/kvstore.go [hunk 3]
```diff
@@ -40,7 +40,7 @@ func ProvideService(
 		secretsPlugin, err = StartAndReturnPlugin(pluginsManager, ctx)
 		namespacedKVStore := GetNamespacedKVStore(kvstore)
 		if err != nil || secretsPlugin == nil {
-			logger.Error("failed to start remote secrets management plugin", "msg", err.Error())
```
[the remark this answers is not in the document]
Comment (guicaulada) [reply pkg/services/secrets/kvstore/kvstore.go:43]: This was removed because the "msg" returned was "unrecognized message from plugin" it's better to delagate error logging to the plugin which can properly detail the error.

File: pkg/services/secrets/kvstore/migrations/from_plugin_mig.go [hunk 4]
```diff
@@ -44,8 +47,7 @@ func (s *MigrateFromPluginService) Migrate(ctx context.Context) error {
 	// access the plugin directly
 	plugin, err := secretskvs.StartAndReturnPlugin(s.manager, context.Background())
 	if err != nil {
-		logger.Error("Error retrieiving plugin", "error", err.Error())
-		return err
+		return errPluginUnavailable
```
[the remark this answers is not in the document]
Comment (guicaulada) [reply pkg/services/secrets/kvstore/migrations/from_plugin_mig.go:50]: This log is dropped due to the same reason as above, it resulted in multiple logging, one of them being "unrecognized message from plugin" when the message is recognized and we already had logged the correct error.

File: pkg/services/secrets/kvstore/migrations/migrator.go (hunk 1 above)
Comment (guicaulada) [reply pkg/services/secrets/kvstore/migrations/migrator.go:82]: Sounds good! Will do!

File: pkg/services/secrets/kvstore/plugin.go (hunk 2 above)
Comment (guicaulada) [reply pkg/services/secrets/kvstore/plugin.go:259]: Sounds good! Will do!

File: pkg/services/secrets/kvstore/migrations/migrator.go (hunk 1 above)
Comment (guicaulada) [reply pkg/services/secrets/kvstore/migrations/migrator.go]: Done on 526bc81318

File: pkg/services/secrets/kvstore/plugin.go (hunk 2 above)
Comment (guicaulada) [reply pkg/services/secrets/kvstore/plugin.go]: I moved the check to a separate function on 08c16e4afa but `mg.SecretsManager(ctx)` returns a `*plugins.Plugin`, I'm not sure if we should add the `HasStarted` function to `plugins.Plugin` since many plugins already depend on it, so I added the HasPluginStarted function to the `kvstore` package on `plugin.go` instead, in the end it has the same effect, removing the burden when calling `EvaluateRemoteSecretsPlugin`.

File: pkg/services/secrets/kvstore/kvstore.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (mmandrus) [reply pkg/services/secrets/kvstore/kvstore.go:43]: gotcha, I missed that this was done in conjunction with the plugin changes, sounds good.

File: pkg/services/secrets/kvstore/migrations/from_plugin_mig.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (mmandrus) [reply pkg/services/secrets/kvstore/migrations/from_plugin_mig.go:50]: Got it, cool!

**Review by mmandrus — APPROVED** [review]
LGTM
