### PR TITLE
PlayList: add delete functionality to remove playlist

### LINKED ISSUE #37284: How to remove the playlist?
**What happened**:
I don't know how to remove an exist playlist. [Doc](https://grafana.com/docs/grafana/latest/dashboards/playlist/#delete-a-playlist)

**What you expected to happen**:
Have a remove button.

**How to reproduce it (as minimally and precisely as possible)**:
Run a Grafana container on Docker.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.6 (68fe9e3431)
- User OS & Browser: MacOS 11.2.1 & Chrome 92.0.4515.107
- Docker: Docker Engine - Community v20.10.7

### PR DESCRIPTION
**Pull request by thisisobate**
**What this PR does / why we need it**:
This PR adds delete functionality to remove playlist.
**Which issue(s) this PR fixes**:

Fixes #37284

### CODE REVIEW

**Review by dprokop — COMMENTED** [review]
Looks and works good - left one comment to consider about (maybe) unnecessary fetch after the deletion.

File: public/app/features/playlist/PlaylistPage.tsx [hunk 1]
```diff
@@ -22,10 +33,12 @@ interface Props extends ConnectedProps, GrafanaRouteComponentProps {}
 export const PlaylistPage: FC<Props> = ({ navModel }) => {
   const [searchQuery, setSearchQuery] = useState('');
   const [startPlaylist, setStartPlaylist] = useState<PlaylistDTO | undefined>();
+  const [playlistToDelete, setPlaylistToDelete] = useState<PlaylistDTO | undefined>();
+  const [forcePlaylistsFetch, setforcePlaylistsFetch] = useState(0);
 
   const { value: playlists, loading } = useAsync(async () => {
     return getBackendSrv().get('/api/playlists', { query: searchQuery }) as Promise<PlaylistDTO[]>;
-  });
+  }, [forcePlaylistsFetch]);
```
[the remark this answers is not in the document]
Comment (dprokop) [reply public/app/features/playlist/PlaylistPage.tsx:32]: Yes - you download the list of playlists, and after that you only update local state of the component.

**Comment by dprokop** [comment]
> Also, noticed the alert message I get when I delete a playlist doesn't correspond with the action I performed. Any ideas on how I can change it to have the correct message? @dprokop @hugohaggmark

What's the alert message? I would look for it first to see where it comes from. 

Showing alert messages is as simple as publishing new event through appEvents event bus:
`appEvents.publish(new Your Event())`.

File: public/app/features/playlist/PlaylistPage.tsx [hunk 2]
```diff
@@ -51,16 +64,27 @@ export const PlaylistPage: FC<Props> = ({ navModel }) => {
...
+                  <LinkButton key="edit" variant="secondary" href={`/playlists/edit/${playlist.id}`} icon="cog">
+                    Edit playlist
+                  </LinkButton>
+                  <Button
+                    disabled={false}
+                    onClick={() => setPlaylistToDelete(playlist.id)}
+                    icon="trash-alt"
+                    variant="destructive"
+                  >
+                    Delete playlist
```
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply public/app/features/playlist/PlaylistPage.tsx:69]: How was it done in the original Angular page?

File: public/app/features/playlist/PlaylistPage.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply public/app/features/playlist/PlaylistPage.tsx:32]: Couldn't another user have deleted playlists and we want to reflect that too?

[the remark this answers is not in the document]
Comment (dprokop) [reply public/app/features/playlist/PlaylistPage.tsx:32]: Probably tru @hugohaggmark. Question how often the playlists are deleted and whether or not this will be an issue. Dunno to be honest. My gut feeling is that this ain't the mostly used list in Grafana.

[the remark this answers is not in the document]
Comment (hugohaggmark) [reply public/app/features/playlist/PlaylistPage.tsx:32]: I agree with you Domink, but I think we should avoid having a disconnected frontend state.

[the remark this answers is not in the document]
Comment (dprokop) [reply public/app/features/playlist/PlaylistPage.tsx:32]: That's totally fine with me @hugohaggmark . Let's keep it as it is implemented atm - since this endpoint ain't used too much probably, re-fetching list should still be fine.

**Comment by thisisobate** [comment]
> What's the alert message? 

The message is "playlist saved"

**Comment by thisisobate** [comment]
> I would look for it first to see where it comes from

Tried looking but couldn't locate where it's coming from.

**Comment by hugohaggmark** [comment]
> > I would look for it first to see where it comes from
> 
> Tried looking but couldn't locate where it's coming from.

Probably coming from the backend? I think you can pass an option that you will handle the alerts/errors. But why not use the message from the backend?

**Comment by thisisobate** [comment]
> why not use the message from the backend?

I think the "playlist saved" message I get from the backend doesn't represent the delete action I performed. I think the message should be "playlist deleted".

File: public/app/features/playlist/PlaylistPage.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (thisisobate) [reply public/app/features/playlist/PlaylistPage.tsx:69]: Just confirmed: editors have permissions to delete a playlist. Great catch! @hugohaggmark

[the remark this answers is not in the document]
Comment (hugohaggmark) [reply public/app/features/playlist/PlaylistPage.tsx:69]: Also, the backend api should always prevent deletion even if the frontend doesn't, right?

**Comment by hugohaggmark** [comment]
> > why not use the message from the backend?
> 
> I think the "playlist saved" message I get from the backend doesn't represent the delete action I performed. I think the message should be "playlist deleted".

Ok, I understand I should have read all the comments 🙈  . 
I think instead of using the `delete` function on backendSrv here https://github.com/grafana/grafana/blob/2b54b9277ada4a31c4584a863cbdc8ef6623d369/public/app/features/playlist/api.ts#L17

you can use the `request` function and like this:
```ts
getBackendSrv().request({
  method: 'DELETE',
  url:`/api/playlists/${id}`,
  showSuccessAlert: false,
})
```

File: public/app/features/playlist/api.ts [hunk 3]
```diff
@@ -13,6 +13,10 @@ export async function updatePlaylist(id: number, playlist: Playlist) {
   await withErrorHandling(async () => await getBackendSrv().put(`/api/playlists/${id}`, playlist));
 }
 
+export async function deletePlaylist(id: number) {
+  await withErrorHandling(async () => await getBackendSrv().delete(`/api/playlists/${id}`));
+}
+
```
Comment (hugohaggmark) [inline public/app/features/playlist/api.ts:19]: Maybe use this suggestion:
```suggestion
export async function deletePlaylist(id: number) {
  await withErrorHandling(async () => await getBackendSrv().request({
  method: 'DELETE',
  url:`/api/playlists/${id}`,
  showSuccessAlert: false,
})
);
}

```

File: public/app/features/playlist/PlaylistPage.tsx [hunk 4]
```diff
@@ -84,52 +115,3 @@ const mapStateToProps: MapStateToProps<ConnectedProps, {}, StoreState> = (state:
 });
 
 export default connect(mapStateToProps)(PlaylistPage);
-
```
Comment (hugohaggmark) [inline public/app/features/playlist/PlaylistPage.tsx:87]: Nice refactor 🎉

File: public/app/features/playlist/PlaylistPage.tsx [hunk 5]
```diff
@@ -73,6 +87,23 @@ export const PlaylistPage: FC<Props> = ({ navModel }) => {
...
+            onConfirm={() => {
+              deletePlaylist(playlistItemToDelete.id).finally(() => {
+                setForcePlaylistsFetch(forcePlaylistsFetch + 1);
+                setPlaylistToDelete(undefined);
+              });
+            }}
+            isOpen={Boolean(playlistToDelete)}
+            onDismiss={() => {
+              setPlaylistToDelete(undefined);
+            }}
```
Comment (hugohaggmark) [inline public/app/features/playlist/PlaylistPage.tsx:104]: nitpick: we should try to avoid anonymous functions (arrow functions =>) as props because they will be recreated on each render.

File: public/app/features/playlist/PlaylistPage.tsx [hunk 6]
```diff
@@ -1,32 +1,37 @@
...
   const [startPlaylist, setStartPlaylist] = useState<PlaylistDTO | undefined>();
+  const [playlistToDelete, setPlaylistToDelete] = useState<number | undefined>();
+  const [forcePlaylistsFetch, setForcePlaylistsFetch] = useState(0);
 
   const { value: playlists, loading } = useAsync(async () => {
     return getBackendSrv().get('/api/playlists', { query: searchQuery }) as Promise<PlaylistDTO[]>;
-  });
+  }, [forcePlaylistsFetch]);
   const hasPlaylists = playlists && playlists.length > 0;
+  const playlistItemToDelete = playlists?.find(({ id }) => id === playlistToDelete);
```
Comment (hugohaggmark) [inline public/app/features/playlist/PlaylistPage.tsx:34]: Why this lookup? If we store the `playlistItemToDelete` in state or something like `{id: number; name:string}` we don't need to do this lookup on each render, right?

File: public/app/features/playlist/PlaylistPage.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply public/app/features/playlist/PlaylistPage.tsx:32]: @thisisobate can we expose the `getBackendSrv().get(` from the api file public/app/features/playlist/api.ts instead? Much like you did with the delete function?

**Review by hugohaggmark — COMMENTED** [review]
Almost there, I did a high level code review and I have some questions/comments.

File: public/app/features/playlist/api.ts (hunk 3 above)
Comment (thisisobate) [reply public/app/features/playlist/api.ts:19]: Seems like the `request` function is deprecated?

Comment (thisisobate) [reply public/app/features/playlist/api.ts:19]: Maybe it's worth using `fetch` instead? @hugohaggmark

Comment (hugohaggmark) [reply public/app/features/playlist/api.ts:19]: Sure, go ahead. That uses Observables though, so you need to figure that out. 🤔

Comment (thisisobate) [reply public/app/features/playlist/api.ts:19]: Getting some errors with types
`Type 'Promise<FetchResponse<unknown>>' is not assignable to type 'Promise<void>'.`

maybe I'm doing this the wrong way?
```ts
await lastValueFrom(
    getBackendSrv().fetch({
      method: 'DELETE',
      url: `/api/playlists/${id}`,
      showSuccessAlert: false,
    })
  )
```

Comment (hugohaggmark) [reply public/app/features/playlist/api.ts:19]: > Sure, go ahead. That uses Observables though, so you need to figure that out. 

That's what I was trying to say you need to figure this out if you're using `fetch` instead of `request` 😉

Comment (thisisobate) [reply public/app/features/playlist/api.ts:19]: I guess we need to create a duplicate of the `withErrorHandling` function that has a type compatible with observables and return the correct alert message? @hugohaggmark 
```ts
async function withErrorHandling2(apiCall: () => Promise<FetchResponse<unknown>>) {
  try {
    await apiCall();
    dispatch(notifyApp(createSuccessNotification('Playlist deleted')));
  } catch (e) {
    dispatch(notifyApp(createErrorNotification('Unable to delete playlist', e)));
  }
}
```

Comment (hugohaggmark) [reply public/app/features/playlist/api.ts:19]: Nope, read the deprecation notice for `request` carefully again.

Comment (thisisobate) [reply public/app/features/playlist/api.ts:19]: oh...just found where the alert message is coming from!
We could as well use the `getBackendSrv().delete()` but wrap it up in `withErrorHandling2` function? I think I prefer this approach 😝

File: public/app/features/playlist/PlaylistPage.tsx [hunk 7]
```diff
@@ -1,32 +1,43 @@
...
+  const [playlistToDelete, setPlaylistToDelete] = useState<PlaylistDTO | undefined>();
+  const [forcePlaylistsFetch, setForcePlaylistsFetch] = useState(0);
 
   const { value: playlists, loading } = useAsync(async () => {
-    return getBackendSrv().get('/api/playlists', { query: searchQuery }) as Promise<PlaylistDTO[]>;
-  });
+    return getAllPlaylist(searchQuery) as Promise<PlaylistDTO[]>;
+  }, [forcePlaylistsFetch]);
   const hasPlaylists = playlists && playlists.length > 0;
+  const setPlaylistItemToDelete = () => setPlaylistToDelete(undefined);
```
Comment (hugohaggmark) [inline public/app/features/playlist/PlaylistPage.tsx:33]: nit: Maybe rename?
```suggestion
  const onDismissDelete = () => setPlaylistToDelete(undefined);
```

File: public/app/features/playlist/PlaylistPage.tsx [hunk 8]
```diff
@@ -51,17 +62,26 @@ export const PlaylistPage: FC<Props> = ({ navModel }) => {
...
-                <LinkButton key="edit" variant="secondary" href={`/playlists/edit/${playlist.id}`} icon="cog">
-                  Edit playlist
-                </LinkButton>
+                <>
+                  <LinkButton key="edit" variant="secondary" href={`/playlists/edit/${playlist.id}`} icon="cog">
+                    Edit playlist
+                  </LinkButton>
+                  <Button
+                    disabled={false}
+                    onClick={() => setPlaylistToDelete({ id: playlist.id, name: playlist.name })}
```
Comment (hugohaggmark) [inline public/app/features/playlist/PlaylistPage.tsx:71]: nit: anonymous function

File: public/app/features/playlist/PlaylistPage.tsx [hunk 9]
```diff
@@ -1,32 +1,43 @@
...
+  const [forcePlaylistsFetch, setForcePlaylistsFetch] = useState(0);
 
   const { value: playlists, loading } = useAsync(async () => {
-    return getBackendSrv().get('/api/playlists', { query: searchQuery }) as Promise<PlaylistDTO[]>;
-  });
+    return getAllPlaylist(searchQuery) as Promise<PlaylistDTO[]>;
+  }, [forcePlaylistsFetch]);
   const hasPlaylists = playlists && playlists.length > 0;
+  const setPlaylistItemToDelete = () => setPlaylistToDelete(undefined);
+  const canDeletePlaylist = () => {
```
Comment (hugohaggmark) [inline public/app/features/playlist/PlaylistPage.tsx:34]: nit: maybe rename?
```suggestion
  const onDeletePlaylist = () => {
```

File: public/app/features/playlist/api.ts [hunk 10]
```diff
@@ -13,15 +13,24 @@ export async function updatePlaylist(id: number, playlist: Playlist) {
   await withErrorHandling(async () => await getBackendSrv().put(`/api/playlists/${id}`, playlist));
 }
 
+export async function deletePlaylist(id: number) {
+  await withErrorHandling(async () => await getBackendSrv().delete(`/api/playlists/${id}`), 'Playlist deleted');
```
Comment (hugohaggmark) [inline public/app/features/playlist/api.ts:17]: I think we can replace all usages of `async () => await getBackendSrv()` with `() => getBackendSrv()`

**Review by hugohaggmark — COMMENTED** [review]
Much better, almost there. Found some minor things

File: public/app/features/playlist/PlaylistPage.tsx (hunk 8 above)
Comment (thisisobate) [reply public/app/features/playlist/PlaylistPage.tsx:71]: But we need to pass in an argument available only in the context. How can achieve this without the anonymous function?

File: public/app/features/playlist/api.ts (hunk 10 above)
Comment (hugohaggmark) [reply public/app/features/playlist/api.ts:17]: yes, thank you!

File: public/app/features/playlist/PlaylistPage.tsx (hunk 8 above)
Comment (hugohaggmark) [reply public/app/features/playlist/PlaylistPage.tsx:71]: Good catch, I didn't pay attention to the arguments. You can ignore my comment.

File: public/app/features/playlist/api.ts [hunk 11]
```diff
@@ -1,27 +1,36 @@
...
 }
 
 export async function getPlaylist(id: number): Promise<Playlist> {
   const result: Playlist = await getBackendSrv().get(`/api/playlists/${id}`);
   return result;
 }
 
-async function withErrorHandling(apiCall: () => Promise<void>) {
+export async function getAllPlaylist(query: string): Promise<PlaylistDTO[]> {
+  const result: PlaylistDTO[] = await getBackendSrv().get('/api/playlists/', query);
```
Comment (hugohaggmark) [inline public/app/features/playlist/api.ts:26]: I think the call to the api used to be. Not sure if passing just a string would work.
```suggestion
  const result: PlaylistDTO[] = await getBackendSrv().get('/api/playlists/', { query });
```

File: public/app/features/playlist/PlaylistPage.tsx [hunk 12]
```diff
@@ -1,32 +1,43 @@
...
   const [searchQuery, setSearchQuery] = useState('');
   const [startPlaylist, setStartPlaylist] = useState<PlaylistDTO | undefined>();
+  const [playlistToDelete, setPlaylistToDelete] = useState<PlaylistDTO | undefined>();
+  const [forcePlaylistsFetch, setForcePlaylistsFetch] = useState(0);
 
   const { value: playlists, loading } = useAsync(async () => {
-    return getBackendSrv().get('/api/playlists', { query: searchQuery }) as Promise<PlaylistDTO[]>;
-  });
+    return getAllPlaylist(searchQuery) as Promise<PlaylistDTO[]>;
+  }, [forcePlaylistsFetch]);
```
Comment (hugohaggmark) [inline public/app/features/playlist/PlaylistPage.tsx:31]: I found an issue, the search for playlists is broken (might be broken on main already). But I think `searchQuery` should be part of the dependencies and the typing should be debounced. Not sure you should tackle this in this PR or open a new issue, up to you.

File: public/app/features/playlist/PlaylistPage.tsx [hunk 13]
```diff
@@ -1,32 +1,43 @@
...
   const hasPlaylists = playlists && playlists.length > 0;
+  const onDismissDelete = () => setPlaylistToDelete(undefined);
+  const onDeletePlaylist = () => {
+    playlistToDelete &&
+      deletePlaylist(playlistToDelete?.id).finally(() => {
+        setForcePlaylistsFetch(forcePlaylistsFetch + 1);
+        setPlaylistToDelete(undefined);
+      });
+  };
```
Comment (hugohaggmark) [inline public/app/features/playlist/PlaylistPage.tsx:40]: Maybe rewrite this as 
```suggestion
  const onDeletePlaylist = () => {
    if(!playlistToDelete) {
     return;
    }
      deletePlaylist(playlistToDelete.id).finally(() => {
        setForcePlaylistsFetch(forcePlaylistsFetch + 1);
        setPlaylistToDelete(undefined);
      });
  };
```

**Review by hugohaggmark — APPROVED** [review]
Looks good and the delete works as expected 🎉  I found another issue when testing the PR and left a comment about it.

File: public/app/features/playlist/api.ts (hunk 11 above)
Comment (thisisobate) [reply public/app/features/playlist/api.ts:26]: The `getBackendSrv().get()` function accepts 3 args that are of type `string` and `any`. So I think passing just a string would work. @hugohaggmark

File: public/app/features/playlist/PlaylistPage.tsx (hunk 12 above)
Comment (thisisobate) [reply public/app/features/playlist/PlaylistPage.tsx:31]: Would open a separate PR for this...great catch

File: public/app/features/playlist/api.ts (hunk 11 above)
Comment (hugohaggmark) [reply public/app/features/playlist/api.ts:26]: Not sure if this makes sense but the backend api needs a param called `query` and they way we provide it from the frontend is to pass an object with the property needed for the backend api call, in this case a property named `query`.
https://github.com/grafana/grafana/blob/6cfb640a0b6ba59a512f05f4fe5fb0e7865da322/pkg/api/playlist.go#L31

Let me know if something is unclear.

Comment (thisisobate) [reply public/app/features/playlist/api.ts:26]: oh...ok.
Now it makes sense. Thanks for the clarification
