### PR TITLE
Singlestat: Fix no data / null value mapping 

### LINKED ISSUE #19645: Singlestat: Treat no data data as null so it can be mapped to text (regression in v6.4)
**What happened**:
After update to version 6.4.1, when there is no data in database in selected time range, singlestat panel shows "No Data" instead of applying value mappings settings

**What you expected to happen**:
It should use value mapping. It should convert "null" to "-" text.

**Environment**:
- Grafana version: 6.4.1
- Data source type & version: Influxdb 1.6.4
- OS Grafana is installed on: Debian 4.9
- User OS & Browser: Windows 10, Google Chrome
- Grafana plugins: -
- Others: -

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes #19645

### CODE REVIEW

File: public/app/plugins/panel/singlestat/module.ts [hunk 1]
```diff
@@ -186,13 +186,17 @@ class SingleStatCtrl extends MetricsPanelCtrl {
     }
 
     if (!fieldInfo) {
+      const processor = getDisplayProcessor({
+        config: {
+          mappings: convertOldAngulrValueMapping(this.panel),
```
Comment (torkelo) [inline public/app/plugins/panel/singlestat/module.ts]: Angulr? :)

Comment (ryantxu) [reply public/app/plugins/panel/singlestat/module.ts]: dooh -- fixed

**Review by torkelo — APPROVED** [review]
