### PR TITLE
SQL: Fix code editor for SQL datasources

### LINKED ISSUE #57745: MS/MYSQL: Autocomplete not working
**What happened**:

After upgrading @grafana/experimental to 1.0.1 the autocomplete doesn't work anymore in the sql datasources.

This is a regression caused by https://github.com/grafana/grafana/pull/57436

### PR DESCRIPTION
**Pull request by zoltanbedi**
This PR fixes the code editor for the sql datasources after bumping the grafana/experimental package to 1.0.1 in https://github.com/grafana/grafana/pull/57436

**Which issue(s) does this PR fix?**:

Fixes #57745

**Special notes for your reviewer**:

This is far from perfect but it works. Things to consider.

- [ ] Use proper [monaco languages](https://github.com/microsoft/monaco-editor/tree/main/src/basic-languages) for postgres and mysql
- [ ] Support schemas for postgresql
- [ ] Use functions from monaco language in the visual query editor (maybe the everyday user doesn't need all the functions)
- [x] https://github.com/grafana/plugin-ui/issues/118

Autocomplete doesn't work well inside SELECT.
- [ ] ~After adding a column with an aggregate function there aren't more suggestions for columns~ Taking another look this is only an issue when you select `value` field which for me is an edge case.
- [x] https://github.com/grafana/plugin-ui/issues/117

### CODE REVIEW

File: public/app/features/plugins/sql/components/query-editor-raw/QueryEditorRaw.tsx [hunk 1]
```diff
@@ -39,7 +38,7 @@ export function QueryEditorRaw({ children, onChange, query, width, height, compl
       height={height}
       query={query.rawSql!}
       onChange={onRawQueryChange}
-      language={{ id: 'sql', completionProvider, formatter: formatSQL }}
```
Comment (zoltanbedi) [inline public/app/features/plugins/sql/components/query-editor-raw/QueryEditorRaw.tsx:42]: This change was not necessary for this PR but it can help in the future to be able to get language definition for mysql and postgres in the future.

**Comment by codeincarnate** [comment]
Tested with Postgres and looking good there. I'm testing with MySql as well now.

File: public/app/plugins/datasource/mysql/sqlCompletionProvider.ts [hunk 2]
```diff
@@ -1,267 +1,32 @@
...
-    {
-      id: `MYSQL${StatementPosition.WhereKeyword}`,
-      applyTo: [StatementPosition.WhereKeyword],
-      suggestionsResolver: async (ctx) => {
-        const path = getPath(ctx.currentToken, Direction.Previous);
-        const t = await fetchMeta.current(path);
-        return t.map((meta) => {
-          const completion = meta.kind === CompletionItemKind.Class ? `${meta.completion}.` : meta.completion;
-          return suggestion(meta.name, completion!, meta.kind, ctx);
-        });
```
Comment (sunker) [inline public/app/plugins/datasource/mysql/sqlCompletionProvider.ts:150]: Did this custom handling work? If so, is the support dropped now?

**Review by sunker — COMMENTED** [review]
Not tested but looks good! For these plugin, you may want to consider adding support for resolving schemas. See [example](https://github.com/grafana/redshift-datasource/pull/173/commits/0599b17a03cf4771b28fe09589925d2ead634b6c) in the redshift plugin.

**Comment by codeincarnate** [comment]
I think I may be having trouble with MySql 🤔. Not getting table names although I am with the visual query editor.

**Comment by codeincarnate** [comment]
OK, so with MySql there does seem to be one issue with completion suggestions. I have a database configured in the data source however this isn't getting used and will always default to the database name first rather than providing table names. Not sure if this is the desired behavior but certainly seems a bit awkward.

File: public/app/plugins/datasource/mysql/sqlCompletionProvider.ts (hunk 2 above)
Comment (zoltanbedi) [reply public/app/plugins/datasource/mysql/sqlCompletionProvider.ts:150]: it did but I think it did the same as what we have in place. showing the columns after WHERE.

**Comment by zoltanbedi** [comment]
> OK, so with MySql there does seem to be one issue with completion suggestions. I have a database configured in the data source however this isn't getting used and will always default to the database name first rather than providing table names. Not sure if this is the desired behavior but certainly seems a bit awkward.

@codeincarnate Can you help me how to reproduce this? I tried to add another database  but it still worked for me.

**Comment by zoltanbedi** [comment]
> Also having issues with MySql when selecting more than one column name. Past the first selected column no suggestions are returned. I imagine this one just may be tricky or is something that can be implemented at a later date potentially.

This is something that I also found. Going to open an issue for this in the experimental repo.

**Comment by zoltanbedi** [comment]
> Not tested but looks good! For these plugin, you may want to consider adding support for resolving schemas. See [example](https://github.com/grafana/redshift-datasource/pull/173/commits/0599b17a03cf4771b28fe09589925d2ead634b6c) in the redshift plugin.

Thanks @sunker. This is something that I'd like to do some time later.

**Comment by codeincarnate** [comment]
@zoltanbedi from my end using MySql 8 from homebrew and using `root` with no password. Here's my datasource configuration page. If you can't reproduce it may very well be my setup. If you think that's the case let me know and I'm fine with approving 😄 

Screenshot 2022-11-09 at 6 01 29 PM

**Comment by zoltanbedi** [comment]
> OK, so with MySql there does seem to be one issue with completion suggestions. I have a database configured in the data source however this isn't getting used and will always default to the database name first rather than providing table names. Not sure if this is the desired behavior but certainly seems a bit awkward.

Ok this should be fixed now but in order to have database in jsonData we need this pr https://github.com/grafana/grafana/pull/58649 which targets 9.3 so it will only be available after that.

**Review by oscarkilhed — APPROVED** [review]
This works, and is better than not having any completion at all as is the case right now. But in the testing I've found a lot of wonky issues that we should address sooner rather than later.
