### PR TITLE
Stat: Fix data links that refer to fields

### LINKED ISSUE #60297: Data links in Stat panel with __data.fields not working
Copied from [here](https://community.grafana.com/t/data-links-in-stat-panel-with-data-fields/66604)

We have also this problem in v8.5.15. Thanks!

Grafana v8.5.2 in Docker Container

What are you trying to achieve?
I want to have a Data link on the Stat Panel, with some data from the query

How are you trying to achieve it?
https://example.com?foo=${__data.fields.foo} .

What happened?
I was able to select the data field in the Data Link dialog, but later it does not get substituted in the URL when I click or hover on the stat panel.

What did you expect to happen?
The variable gets substituted like in the table panel.

image (17)

### PR DESCRIPTION
**Pull request by ajwerner**
**What is this feature?**

Fixes a bug whereby data links in Stat panels (and probably other "reduced" data panels) could not refer to the `${__data.fields}` macros available in other panels.

For these panels, data links which referred to fields did not end up rendering because the rowIndex ended up being undefined. When the row index is undefined, the data macro expansion for fields does not trigger (see [0]).

**Why do we need this feature?**

It's often very nice to link to data that you are not displaying. See the chatter in #60297.

**Who is this feature for?**

Grafana users who like data links.

**Which issue(s) does this PR fix?**:

Fixes #60297

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
    - I tested it manually; I don't have the context on how to write the appropriate test. All the tests passed.
    
[0]: https://github.com/grafana/grafana/blob/878ba96a/public/app/features/templating/dataMacros.ts#L99-L101

### CODE REVIEW

**Comment by baldm0mma** [comment]
Thanks @ajwerner . The fix looks good to me, but I would love a few others on the @grafana/dataviz-squad to take a look too make sure this doesn't adversely/unexpectedly touch anything and have unintended interactions elsewhere.

**Review by codeincarnate — APPROVED** [review]
Thanks for the contribution! This appears to be working and it makes sense that the value field for a reduction would be the first field (i.e. index 0). I'm not sure if this has broader impact however and it would be good to get someone to chime in on that. 

Going by file history maybe @drew08t or @ryantxu might know?

File: packages/grafana-data/src/field/fieldDisplay.ts [hunk 1]
```diff
@@ -215,6 +215,7 @@ export const getFieldDisplayValues = (options: GetFieldDisplayValuesOptions): Fi
               ? () =>
                   fieldLinksSupplier({
                     calculatedValue: displayValue,
+                    valueRowIndex: 0,
```
Comment (nmarrs) [inline packages/grafana-data/src/field/fieldDisplay.ts:218]: I'm not sure of the implications of hard coding the value row index here, @leeoniya do you have any insights on this?

Comment (ajwerner) [reply packages/grafana-data/src/field/fieldDisplay.ts]: I've narrowed the change and added more commentary. The change is now more minimal.

On some level, choosing `valueRowIndex: 0` can be wrong. If you have more than one row in the data frame then the calc that was run may not be totally meaningful. Indeed this is referring to the entire data frame here when we talk about the `${__data}` macros and then scoped to the relevant row through this mechanism here.

The more minimal and correct thing I've now done to limit this change to apply only to data frames with a single row. Then there's no doubt that it's the right choice for the row index (it's the only reasonable choice :p).

**Comment by ajwerner** [comment]
I think the failure on that CI step was some sort of infra misconfiguration or flake or something.

**Review by nmarrs — APPROVED** [review]
I think this is reasonable, thanks for diving deeper into this - I think this solution is "good enough" for the time being 👍

**Comment by nmarrs** [comment]
@ajwerner we made some build changes recently so to get this merged you will need to merge this branch onto latest main

1) Pull latest main
2) Checkout to this branch
3) run `git merge origin main`
4) push up result

thanks!

**Comment by ajwerner** [comment]
@nmarrs I rebased main
