### PR TITLE
SSE: Reduce to apply Mode to instant vector (mathexp.Number)

### LINKED ISSUE #74645: Drop/Replace Non-Numeric Values in Grafana Alerting does not work.
### What happened?

Hello, I'm setting up alerting on my cluster and noticed that these 2 functions do not work as expected.
I have a selection that contains “NaN”, and accordingly I don’t want to rate them, then Grafana does not react in any way if I select Reduce and Drop/Replace Non-Numeric Values.
I am attaching a screenshot.

### What did you expect to happen?

Drop/Replace Non-Numeric Values will works as expected

### Did this work before?

I do not know.

### How do we reproduce it?

```
rate(node_network_receive_errs_total{job="node-exporter"}[2m]) / rate(node_network_receive_packets_total{job="node-exporter"}[2m])
```

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 10.1.1
OS: Windows 10
Browser: Vivaldi | 6.2.3105.47

### Grafana platform?

Kubernetes

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What is this feature?**
Updates reduce command expression to apply modes `Drop` and `Replace` to mathexp.Number. 
Also, it changes when the warning is returned. If mapping mode is not Strict, the warning will not be added.

**Why do we need this feature?**
Initially, the expression applied this mode to mathexp.Series (i.e. time-series). However, from user's perspective, the format of data may not be clear and the expression behavior looks different. 

**Who is this feature for?**
Alerting users that query data sources that return vectors and want to drop\map non-numeric values.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/74645

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/expr/commands.go [hunk 1]
```diff
@@ -175,12 +175,21 @@ func (gr *ReduceCommand) Execute(ctx context.Context, _ time.Time, vars mathexp.
...
+				}
+			}
 			copyV := mathexp.NewNumber(gr.refID, v.GetLabels())
-			copyV.SetValue(v.GetFloat64Value())
-			copyV.AddNotice(data.Notice{
-				Severity: data.NoticeSeverityWarning,
-				Text:     fmt.Sprintf("Reduce operation is not needed. Input query or expression %s is already reduced data.", gr.VarToReduce),
-			})
+			copyV.SetValue(value)
+			if gr.seriesMapper == nil {
```
Comment (yuri-tceretian) [inline pkg/expr/commands.go:187]: I think this is semantically correct because in this case reduce is not a noop anymore.

File: pkg/expr/commands_test.go [hunk 2]
```diff
@@ -100,42 +101,83 @@ func Test_UnmarshalReduceCommand_Settings(t *testing.T) {
...
+				expected := numbers[i]
+				require.Equal(t, expected.Type(), value.Type())
+				require.Equal(t, expected.GetLabels(), value.GetLabels())
+
+				expectedValue := expected.Value().(*mathexp.Number).GetFloat64Value()
+				actualValue := value.Value().(*mathexp.Number).GetFloat64Value()
+				require.Equal(t, expectedValue, actualValue)
+			}
+
+			t.Run("should add warn notices to every frame", func(t *testing.T) {
```
Comment (kylebrandt) [inline pkg/expr/commands_test.go:136]: We should see if works with only the first frame, and if it does only put it there. Else were could be repeating this string a lot if there are many items in the response.

Comment (yuri-tceretian) [reply pkg/expr/commands_test.go:136]: I can address it in a follow-up PR.

**Review by kylebrandt — APPROVED** [review]
