### PR TITLE
ShareModal: delete shareView query param from url 

### LINKED ISSUE #92242: ShareModal: delete shareView query param from url
### What happened?

https://github.com/grafana/grafana/pull/92020 adds shareView to the url. However, when building the url to share, it still has the param and needs to be removed so that when copied and pasted in another window, the share modal will not appear

### What did you expect to happen?

When sharing the link via the share modal, the link, will not contain the shareView param. When copy and pasted into a new window, the sharemodal will not be opened

### Did this work before?

Yes before https://github.com/grafana/grafana/pull/92020

### How do we reproduce it?

1. Navigate to a dashboard: https://ops.grafana-ops.net/d/2OQseaNMz/billing-usage-internal
2. Click the Share button in the top right; 
3. Copy the Link URL on the popup (e.g. [https://ops.grafana-ops.net/d/2OQseaNMz/billing-usage-internal?var-org_slug=dapperlabs[…]00Z&to=2024-08-21T18:33:44.619Z&timezone=utc&shareView=link](https://ops.grafana-ops.net/d/2OQseaNMz/billing-usage-internal?var-org_slug=dapperlabs&var-is_customer_of_grafana=1&var-is_customer_of_partner=0&var-org_id=216416&var-metrics_id=$__all&var-logs_id=$__all&var-traces_id=$__all&var-grafana_id=$__all&var-profiles_id=$__all&from=2024-08-01T00:00:00.000Z&to=2024-08-21T18:33:44.619Z&timezone=utc&shareView=link))
4. Paste & load copied link in new browser window and the Share popup is shown again :point_left: this seems unexpected, i would expect to see the dashboard i intended to share

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by lucychen-grafana**
**What is this feature?**

Delete 'shareView' param from the link url when url is created to be shared

**Why do we need this feature?**

To prevent the share modal from popping up when share link url is pasted into another window

**Who is this feature for?**

Customers

**Which issue(s) does this PR fix?**:

Fixes #https://github.com/grafana/grafana/issues/92242

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard-scene/utils/urlBuilders.ts [hunk 1]
```diff
@@ -62,6 +62,8 @@ export function getDashboardUrl(options: DashboardUrlOptions) {
 
   const params = options.currentQueryParams ? locationSearchToObject(options.currentQueryParams) : {};
 
+  delete params['shareView'];
```
Comment (evictorero) [inline public/app/features/dashboard-scene/utils/urlBuilders.ts:65]: Can we add also a simple test in `urlBuilders.test.ts`?
Are we sure this `getDashboardurl` function will never need to return a `shareView` param? I think the answer is yes but I want to double check just in case.

Comment (lucychen-grafana) [reply public/app/features/dashboard-scene/utils/urlBuilders.ts:65]: Test added!

Seems like shareView is used to open the different tabs in the share modal. When copying link to share, we don't need that info

**Review by evictorero — APPROVED** [review]
LGTM!

**Review by juanicabanas — APPROVED** [review]
LGTM!
