### PR TITLE
Annotations: Adds DashboardQueryRunner

### LINKED ISSUE #30229: Annotation disappearing on edit mode and when open option menu
**What happened**:
Annotation disappeared when I go to "edit" menu or when I open  "Show option" sidebar. After "refresh dashboard" it appears.

**What you expected to happen**:
As it works on an older version (for example 6.6.2), annotation always showed on a graph.

**How to reproduce it (as minimally and precisely as possible)**:
Just go to edit mode on graph with annotation.

**Anything else we need to know?**:
annotation
invisible_annotations

**Environment**:
- Grafana version: 7.3.6
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker
- User OS & Browser:
- Grafana plugins:
- Others:

### LINKED ISSUE #32772: Dashboard Query Runner
- [x] Create the DashboardQueryRunner
   - [x]  Tests
   - [ ] Cancellation
   - [x] Clean up all console.logs
- [x] Find good starting points for the run in DashboardQueryRunner   
- [x] Subscribe to DashboardQueryRunner from PanelQueryRunner
   - [ ] How to decide which panels that should subscribe, add abilities to plugin json?
   - [ ] What should we do with AlertStates? Hold until next gen Alerting has more progress?

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:

### Open questions
- [x] Right now in the PR we run both AnnotationSrv and DashboardQueryRunner. Should we get rid of AnnotationSrv in this PR? One consequence right now is that requests are cancelled due to duplicate requestIds. If we decide to remvoe AnnotationSrv what are the consequences?
- [x] How do we decide which panel plugins PanelQueryRunner should subscribe to DashboardQueryRunner results? Should we try to solve this in this PR? Fixed in #33253
- [x] Add cancellation logic to DashboardQueryRunner

**Which issue(s) this PR fixes**:
Fixes #32772
Fixes #30229

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/query/state/DashboardQueryRunner/DashboardQueryRunner.ts [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+          acc.alertStates = acc.alertStates.concat(value.alertStates);
+          return acc;
+        })
+      )
+      .subscribe((x) => {
+        this.results.next(x);
+      });
+  }
+
+  getResult(panelId?: number): Observable<DashboardQueryRunnerResult> {
```
Comment (hugohaggmark) [inline public/app/features/query/state/DashboardQueryRunner/DashboardQueryRunner.ts:48]: What should the result be here? For now I'm keeping the same interface as AnnotationSrv. But I guess that this should be Observable<PanelData> instead?

File: public/app/features/query/state/PanelQueryRunner.ts [hunk 2]
```diff
@@ -189,12 +191,12 @@ export class PanelQueryRunner {
...
   }
 
-  private pipeToSubject(observable: Observable<PanelData>) {
+  private pipeToSubject(observable: Observable<PanelData>, panelId?: number) {
     if (this.subscription) {
       this.subscription.unsubscribe();
     }
 
-    this.subscription = observable.subscribe({
+    this.subscription = mergePanelAndDashData(observable, getDashboardQueryRunner().getResult(panelId)).subscribe({
```
Comment (hugohaggmark) [inline public/app/features/query/state/PanelQueryRunner.ts:199]: Here we need to figure out which panel plugins that should subscribe to DashboardQueryRunner results, for now all PanelRunners subscribe.

**Review by torkelo — COMMENTED** [review]
Amazing work, the mergePanelAndDashData & tests are just a beauty. 

Is there a way to rewrite annotationSrv so that it is using DashboardQueryRunner internally? Because with this if you have an angular graph & time series panel on the same dashboard the annotation query will fire twice. If it's super complicated / risky, the double queries is fine, just need to inform users that they should migrate all panels.

File: public/app/features/dashboard/state/DashboardModel.ts [hunk 3]
```diff
@@ -305,6 +307,7 @@ export class DashboardModel {
 
   startRefresh() {
     this.events.publish(new RefreshEvent());
+    getDashboardQueryRunner().run({ dashboard: this, range: getTimeSrv().timeRange() }); // how can we avoid calling getTimeSrv().timeRange()
```
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply public/app/features/dashboard/state/DashboardModel.ts:310]: I think this is a great idea!

File: public/app/features/query/state/DashboardQueryRunner/DashboardQueryRunner.ts [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+  }
+}
+
+export function getDashboardQueryRunnerWorkers(): DashboardQueryRunnerWorker[] {
+  return [new AlertStatesWorker(), new SnapshotWorker(), new AnnotationsWorker()];
+}
+
+export function getAnnotationQueryRunners() {
+  return [new LegacyAnnotationQueryRunner(), new AnnotationsQueryRunner()];
+}
```
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply public/app/features/query/state/DashboardQueryRunner/DashboardQueryRunner.ts:80]: I agree, I think your suggestion is great!

File: public/app/features/query/state/mergePanelAndDashData.ts [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+      const [panelData, dashData] = combined;
+
+      if (Boolean(dashData.annotations?.length)) {
+        if (!panelData.annotations) {
+          panelData.annotations = [];
+        }
+
+        return of({
+          ...panelData,
+          annotations: panelData.annotations.concat(toDataFrame(dashData.annotations)),
```
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply public/app/features/query/state/mergePanelAndDashData.ts:27]: Hmm, not sure I follow but wouldn't this just transform the dashboard result part to DataFrame. My concern is if we can use concat with data frames?

File: public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+import { cloneDeep } from 'lodash';
+import { AnnotationEvent } from '@grafana/data';
+
+import { DashboardQueryRunnerOptions, DashboardQueryRunnerWorker, DashboardQueryRunnerWorkerResult } from './types';
+import { emptyResult } from './utils';
+
+export class SnapshotWorker implements DashboardQueryRunnerWorker {
+  canWork({ dashboard }: DashboardQueryRunnerOptions): boolean {
+    const snapshots = dashboard.annotations.list.find((a) => a.enable && Boolean(a.snapshotData));
+    return Boolean(snapshots);
```
Comment (kaydelaney) [inline public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts:11]: Could do the following to avoid `Boolean(snapshots)`, if you wanted:
```suggestion
    return dashboard.annotations.list.some((a) => a.enable && Boolean(a.snapshotData));
```

File: public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts [hunk 7]
```diff
@@ -0,0 +1,42 @@
...
+  }
+
+  work(options: DashboardQueryRunnerOptions): Observable<DashboardQueryRunnerWorkerResult> {
+    if (!this.canWork(options)) {
+      return emptyResult();
+    }
```
Comment (kaydelaney) [inline public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts:17]: Do we need this guard, since the rest of the function will effectively return `emptyResult` even if `dashAnnotations` and `snapshots` are empty?

File: public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts [hunk 8]
```diff
@@ -0,0 +1,42 @@
...
+    const dashAnnotations = dashboard.annotations.list.filter((a) => a.enable);
+    const snapshots = dashAnnotations.filter((a) => Boolean(a.snapshotData));
+    const annotations = snapshots.reduce((acc, curr) => {
+      return acc.concat(SnapshotWorker.translateQueryResult(curr, curr.snapshotData));
+    }, [] as AnnotationEvent[]);
+
+    return of({ annotations, alertStates: [] });
+  }
+
+  private static translateQueryResult(annotation: any, results: AnnotationEvent[]): AnnotationEvent[] {
```
Comment (kaydelaney) [inline public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts:29]: Can we type `annotation` with `AnnotationQuery<DataQuery>`?

File: public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts (hunk 7 above)
Comment (hugohaggmark) [reply public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts:17]: Not sure I follow you now, can you elaborate? This will return snapshotted annotations as far as I can see.

File: public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts (hunk 8 above)
Comment (hugohaggmark) [reply public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts:29]: Will fix!

File: public/app/features/query/state/DashboardQueryRunner/DashboardQueryRunner.ts [hunk 9]
```diff
@@ -0,0 +1,94 @@
...
+      .subscribe((x) => {
+        this.results.next(x);
+      });
+  }
+
+  getResult(panelId?: number): Observable<DashboardQueryRunnerResult> {
+    return this.results.asObservable().pipe(
+      map((result) => {
+        const annotations = result.annotations.filter((item) => {
+          if (Boolean(panelId) && item.panelId && item.source?.type === 'dashboard') {
```
Comment (kaydelaney) [inline public/app/features/query/state/DashboardQueryRunner/DashboardQueryRunner.ts:53]: Should this be
```suggestion
          if (panelId !== undefined && item.panelId && item.source?.type === 'dashboard') {
```
since for example if `panelId` were 0, `Boolean(panelId)` would return false?

Comment (hugohaggmark) [reply public/app/features/query/state/DashboardQueryRunner/DashboardQueryRunner.ts:53]: Great catch!! Will fix!

File: public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts (hunk 6 above)
Comment (hugohaggmark) [reply public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts:11]: Excellent suggestion, out of curiosity, which is the most performant `some` or `find`.

File: public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts (hunk 8 above)
Comment (hugohaggmark) [reply public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts]: Fixed

File: public/app/features/query/state/DashboardQueryRunner/DashboardQueryRunner.ts (hunk 9 above)
Comment (hugohaggmark) [reply public/app/features/query/state/DashboardQueryRunner/DashboardQueryRunner.ts]: Fixed

File: public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts (hunk 6 above)
Comment (kaydelaney) [reply public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts:11]: Did some very unscientific benchmarks and it seems like they're basically the same in terms of performance

Comment (hugohaggmark) [reply public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts:11]: Thank you, and I think `some` adds better readability.

File: public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts (hunk 7 above)
Comment (kaydelaney) [reply public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts:17]: So, if I understand correctly, `this.canWork` checks if `dashboard.annotations.list` has some value `a` such that `a.enable` is true, and that it has some snapshotData, and if this isn't the case, it returns `emptyResult()`, which is `of({ annotations: [], alertStates: [] })`.
But if we remove the guard
```ts
    if (!this.canWork(options)) {
      return emptyResult();
    }
```
then `getAnnotationsFromSnapshot` gets called regardless. Like in `canWork`, we check if `dashboard.annotations.list` has a value `a` such that `a.enable` is true, and that it has some snapshotData.
But even if it doesn't (i.e. `snapshots === []`), when it's reduced, `annotations` should just equal `[]`, and `getAnnotationsFromSnapshot` will return [], and so `work` will return `of({ annotations: [], alertStates: []})`, the same as `emptyResult()`.
It doesn't really matter, just removing the guard would mean there's only one path through the code which might be a little easier to read, but it's not a big deal at all.

File: public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts (hunk 6 above)
Comment (hugohaggmark) [reply public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts]: Fixed

File: public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts (hunk 7 above)
Comment (hugohaggmark) [reply public/app/features/query/state/DashboardQueryRunner/SnapshotWorker.ts:16]: Hmm, maybe in the future the `canWork`will have other logic so I think I'll keep it for now

File: public/app/features/query/state/DashboardQueryRunner/DashboardQueryRunner.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply public/app/features/query/state/DashboardQueryRunner/DashboardQueryRunner.ts]: Fixed

File: public/app/features/query/state/PanelQueryRunner.ts (hunk 2 above)
Comment (hugohaggmark) [reply public/app/features/query/state/PanelQueryRunner.ts:246]: Fixed by #33253

File: public/app/features/dashboard/state/DashboardModel.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (hugohaggmark) [reply public/app/features/dashboard/state/DashboardModel.ts]: Fixed

**Comment by torkelo** [comment]
Tested this with some angular & time series panels and slow annotation queries, and works super! 

One potential follow-up if it's not too complex would be to investigate (only investigate/estimate) if adding a loading spinner to the annotation switch label would be possible without a major effort. As it would be really awesome if you could see that an annotation query is loading/executing

**Comment by hugohaggmark** [comment]
> Tested this with some angular & time series panels and slow annotation queries, and works super!
> 
> One potential follow-up if it's not too complex would be to investigate (only investigate/estimate) if adding a loading spinner to the annotation switch label would be possible without a major effort. As it would be really awesome if you could see that an annotation query is loading/executing

I was thinking about that too, but let's add that as an follow up PR.

**Review by torkelo — APPROVED** [review]
Awesome job! using the new plugin option that kay introduced, is that going to come in follow-up PR?

**Comment by hugohaggmark** [comment]
> Awesome job! using the new plugin option that kay introduced, is that going to come in follow-up PR?

Yes, @kaydelaney is working on a branch to this branch!

**Comment by hugohaggmark** [comment]
Will merge this on Monday as it's getting late on a Friday.
