### PR TITLE
Secrets: Convert secret migration to a background service

### LINKED ISSUE #52563: Migrate secrets to plugin in the background instead of blocking

### LINKED ISSUE #54653: Fatal crash in secrets migration when LockExecuteAndRelease fails to release
Will Browne reported this error:
```
Failed to start grafana. error: there is already a lock for this actionName: secret migration task 
there is already a lock for this actionName: secret migration task 
Exiting.
```

Most likely setup for this was pausing (with the debugger) in the middle of migration, then killing the process before the LockExecuteAndRelease function did the release. The next run, this happened.

Throwing an error is good, but it should not be fatal since the migrator runs regardless of if there are secrets. Maybe a big ugly warn instead.

### PR DESCRIPTION
**Pull request by guicaulada**
**What this PR does / why we need it**:

This converts secret migration to Unified Secrets or a secret store plugin to a background service, speeding up startup time.

**Which issue(s) this PR fixes**:

Fixes #52563 
Fixes #54653 

**Special notes for your reviewer**:
This also fixes some wire conflicts with grafana-cli which caused some duplication.

### CODE REVIEW

File: pkg/server/wire.go [hunk 1]
```diff
@@ -334,8 +334,7 @@ var wireBasicSet = wire.NewSet(
 	secretsMigrations.ProvideDataSourceMigrationService,
 	secretsMigrations.ProvideMigrateToPluginService,
 	secretsMigrations.ProvideMigrateFromPluginService,
-	secretsMigrations.ProvideSecretMigrationService,
-	wire.Bind(new(secretsMigrations.SecretMigrationService), new(*secretsMigrations.SecretMigrationServiceImpl)),
```
Comment (mmandrus) [inline pkg/server/wire.go:338]: I might be confused about wire, but don't we still need the bind here?

From the docs:

```Wire matches inputs to outputs via [type identity](https://golang.org/ref/spec#Type_identity), so the inclination might be to create a provider that returns an interface type. However, this would not be idiomatic, since the Go best practice is to [return concrete types](https://github.com/golang/go/wiki/CodeReviewComments#interfaces). Instead, you can declare an interface binding in a provider set:```

**Review by mmandrus — CHANGES_REQUESTED** [review]
LMGTM (Looks Mostly Goot To Me) but one question

File: pkg/server/wire.go (hunk 1 above)
Comment (guicaulada) [reply pkg/server/wire.go:338]: Oh! Will sitck to concrete types from now on, changed the return type to interface, will revert it back and add the wire.Bind.

Comment (guicaulada) [reply pkg/server/wire.go:338]: Done on https://github.com/grafana/grafana/pull/54676/commits/4af903d7a4676ca432a342d703cb5d19b6f4153f

**Review by mmandrus — APPROVED** [review]
