### PR TITLE
Histogram: Fix panel hide when clicking on legend

### LINKED ISSUE #52671: Histogram Panel Hide in area wont work
**What happened**: Histogram panel Hide series functionality not working.

**What you expected to happen**: it should hide/unhide when selecting a series from legend like it does for time series panel

**How to reproduce it (as minimally and precisely as possible)**:  any time series panel when switched to histogram panel looses the ability to hide the series.

**Anything else we need to know?**:

**Environment**: Grafana running on k8s
- Grafana version: v8.5.5 (d32ae1890)
- Data source type & version: MySQL ( not the issue)
- OS Grafana is installed on: K8s
- User OS & Browser: safari
- Grafana plugins: NA
- Others:

### PR DESCRIPTION
**Pull request by mdvictor**
**What this PR does / why we need it**:
Small fix that allow histogram panel to hide/show series when series clicked from legend.

**Which issue(s) this PR fixes**:

Fixes #52671

### CODE REVIEW

File: public/app/plugins/panel/histogram/Histogram.tsx [hunk 1]
```diff
@@ -199,7 +199,7 @@ const prepConfig = (frame: DataFrame, theme: GrafanaTheme2) => {
       colorMode,
       pathBuilder,
       //pointsBuilder: config.drawPoints,
-      show: !customConfig.hideFrom?.vis,
```
Comment (zoltanbedi) [inline public/app/plugins/panel/histogram/Histogram.tsx:202]: No way! Where is typescript when you need it the most?

**Review by zoltanbedi — APPROVED** [review]
We need to make sure to type this properly in the future. ~Also to include it in the schema generation.~ We do include this in the schema generation `HideableFieldConfig`

**Comment by mdvictor** [comment]
> We need to make sure to type this properly in the future. Also to include it in the schema generation.

You're right. I'll look into it and try to do it in this PR
