### PR TITLE
CloudWatch: Add AWS/EFS StorageBytes metric

### LINKED ISSUE #31836: StorageBytes missing from AWS/EFS
**What happened**:
The [AWS/EFS StorageBytes metric](https://aws.amazon.com/about-aws/whats-new/2021/01/monitor-your-amazon-efs-storage-usage-with-amazon-cloudwatch/) is [missing](https://github.com/grafana/grafana/blob/b79e61656ab4f5144d727d50df781f53d71fccf8/pkg/tsdb/cloudwatch/metric_find_query.go#L75).

**What you expected to happen**:
Should be able to see/graph the AWS/EFS StorageBytes metric.

**How to reproduce it (as minimally and precisely as possible)**:
It's not there. 
image

**Anything else we need to know?**:
[The StorageBytes metric has three dimensions: Total, Standard, IA.](https://docs.aws.amazon.com/efs/latest/ug/efs-metrics.html)

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: AWS
- OS Grafana is installed on: Ubuntu
- User OS & Browser: MacOS 10.15.7, Chrome 88.0.4324.192
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by freshleafmedia**
**What this PR does / why we need it**:

This adds the `StorageBytes` metric and `StorageClass` dimension for AWS EFS 

**Which issue(s) this PR fixes**:

Fixes #31836

**Special notes for your reviewer**:

*none*

### CODE REVIEW

**Review by joshhunt — APPROVED** [review]

File: pkg/tsdb/cloudwatch/metric_find_query.go [hunk 1]
```diff
@@ -172,7 +172,7 @@ var dimensionsMap = map[string][]string{
 	"AWS/EC2CapacityReservations": {"CapacityReservationId"},
 	"AWS/EC2Spot":                 {"AvailabilityZone", "FleetRequestId", "InstanceType"},
 	"AWS/ECS":                     {"ClusterName", "ServiceName"},
-	"AWS/EFS":                     {"FileSystemId"},
+	"AWS/EFS":                     {"FileSystemId", "StorageClass"},
```
Comment (andresmgot) [inline pkg/tsdb/cloudwatch/metric_find_query.go:175]: Why is `StorageClass` required as a dimension? From https://docs.aws.amazon.com/efs/latest/ug/efs-metrics.html:

> Amazon EFS metrics use the EFS namespace and provide metrics for a single dimension, FileSystemId.

Comment (andresmgot) [reply pkg/tsdb/cloudwatch/metric_find_query.go:175]: Had some time to verify this today. Indeed, `StorageClass` is a possible dimension when using the `StorageBytes` metric.

Screenshot from 2021-05-18 13-33-44

The problem is that this dimension is not available for any of the other metrics so displaying it for the whole namespace can be confusing. IMO I would not add it because people can still manually write the dimension in this case (and won't hurt the rest of metrics). WDYT @sunker?

Ideally, I would create a separate map for metrics dimensions (I don't know if there are more cases like this) but that would require changes in the frontend as well since the metric is not part of the query when resolving these dimensions. I'd be happy to do so in a separate PR if you think so.

Comment (freshleafmedia) [reply pkg/tsdb/cloudwatch/metric_find_query.go:175]: I agree that it's kinda confusing having a dimension that only applies to specific metrics and that the UI would need to change to make that clear.

I also didn't realise that dimensions and metrics could be typed directly in

Comment (andresmgot) [reply pkg/tsdb/cloudwatch/metric_find_query.go:175]: I checked with @sunker and we are okay merging this as it is and create a follow-up feature request to be able to have dimensions per metric. Thanks again @freshleafmedia!

**Review by andresmgot — APPROVED** [review]
