### PR TITLE
MySQL: add error source to QueryData

### LINKED ISSUE #92751: MySQL: Improve error source in query data
Implement error source (downstream/plugin) for errors generated by mysql data source.

After completed we should remove exception for mysql plugin in slos. More in: https://github.com/grafana/deployment_tools/pull/192778

### PR DESCRIPTION
**Pull request by itsgareth**
**What is this feature?**
adds error source to the mysql data source

**Why do we need this feature?**
better observability :)

**Who is this feature for?**
...

**Which issue(s) does this PR fix?**:
Fixes #92751

**Special notes for your reviewer:**
this follows the same pattern as the mssql ds for consistency.

### CODE REVIEW

File: pkg/tsdb/mysql/sqleng/sql_engine.go [hunk 1]
```diff
@@ -222,10 +222,13 @@ func (e *DataSourceHandler) executeQuery(query backend.DataQuery, wg *sync.WaitG
 			logger.Error("ExecuteQuery panic", "error", r, "stack", string(debug.Stack()))
 			if theErr, ok := r.(error); ok {
 				queryResult.dataResponse.Error = theErr
+				queryResult.dataResponse.ErrorSource = backend.ErrorSourcePlugin
```
Comment (zoltanbedi) [inline pkg/tsdb/mysql/sqleng/sql_engine.go:225]: Are you sure these errors are not from downstream?

File: pkg/tsdb/mysql/sqleng/sql_engine.go [hunk 2]
```diff
@@ -300,14 +304,14 @@ func (e *DataSourceHandler) executeQuery(query backend.DataQuery, wg *sync.WaitG
...
-		errAppendDebug("converting time columns failed", err, interpolatedQuery)
+		errAppendDebug("converting time columns failed", err, interpolatedQuery, backend.ErrorSourcePlugin)
 		return
 	}
 
 	if qm.Format == dataQueryFormatSeries {
 		// time series has to have time column
 		if qm.timeIndex == -1 {
-			errAppendDebug("db has no time column", errors.New("no time column found"), interpolatedQuery)
+			errAppendDebug("db has no time column", errors.New("no time column found"), interpolatedQuery, backend.ErrorSourceDownstream)
```
Comment (zoltanbedi) [inline pkg/tsdb/mysql/sqleng/sql_engine.go:314]: I'm not sure if it is a downstream error. This is something that the plugin throws because of no time column found.

Comment (ivanahuckova) [inline pkg/tsdb/mysql/sqleng/sql_engine.go:314]: @zoltanbedi Yes, this is user error when they select time series format and their query does not include time column.
image

@gwdawson could we also improve the error message to make it more actionable and understandable. Something like:

```suggestion
			errAppendDebug("db has no time column", errors.New("time column is missing; make sure your data includes a time column for time series format or switch to a table format that doesn't require it"), interpolatedQuery, backend.ErrorSourceDownstream)
```

**Review by ivanahuckova — COMMENTED** [review]
Left some comments bellow, but in general LGTM! :)

**Comment by zoltanbedi** [comment]
Sorry I thought that user errors are not downstream, my bad.

**Comment by ivanahuckova** [comment]
Also, we could go ahead and after merging this implement all of these also in postgres, as it seems that have exactly the same errors.

**Review by ivanahuckova — APPROVED** [review]
