### PR TITLE
BarGauge: Improved handling of  streaming data.

### LINKED ISSUE #37952: Bar gauge Retro LCD style incorrect max
Since our upgrade from 7.5.x to 8.1.y we are having an issue with the Bar Gauge panel, using only the LCD style flavour.
We're using the Riemann streaming datasource to display values. As the first few streamed dataframes come in, the panel seems fine, but very quickly after that, all bars are extended the same amount and fill the horizontal space:

grafana-issue-37952

This happens regardless of the maximum value, be it automatically selected or manually entered.

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- `BarGauge` doesn't really work when streaming data at the moment unless you set an explicit minimum and maximum because we don't have a default min/max value when the `field.min`/`field.max` values aren't set
- compare this to `Gauge` where we do: https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Gauge/Gauge.tsx#L119
- this PR matches `Gauge`'s behaviour

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/37952

**Special notes for your reviewer**:

### CODE REVIEW

File: packages/grafana-ui/src/components/BarGauge/BarGauge.tsx [hunk 1]
```diff
@@ -132,8 +132,8 @@ export class BarGauge extends PureComponent<Props> {
       wrapperWidth,
       wrapperHeight,
     } = calculateBarAndValueDimensions(this.props);
-    const minValue = field.min!;
-    const maxValue = field.max!;
+    const minValue = field.min ?? 0;
+    const maxValue = field.max ?? 100;
```
Comment (hugohaggmark) [inline packages/grafana-ui/src/components/BarGauge/BarGauge.tsx:136]: Maybe we should introduce constants for the defaults?

**Review by hugohaggmark — APPROVED** [review]
Looks great and works as expected 🎉
