### PR TITLE
Transformations: Allow queries without dataframe results to be selectable as filters

### LINKED ISSUE #107148: Transformations: Filters disappear with datasource error
### What happened?

In Grafana, two things are possible

1. You can set up transformations to be filtered to work on a specific query
2. Datasources can occasionally fail

The datasource filter should not care if the datasource has failed or not. There is a dataframe preview on the dropdown that may not populate, but it should show a list of refIds, even if the refId is for a failing datasource. Having them disappear is confusing for users, even if the filter returns when the datasource access is restored.

### What did you expect to happen?

For the transformation filter to still show even though the datasource has returned an error.

### Did this work before?

No.

### How do we reproduce it?

Running Grafana locally to show a datasource error...

1. Run `make devenv sources=loki` to bring up a docker container with a loki datasource.
2. Create a dashboard panel using `gdev-loki` and create a filter that points to that query
3. Shut down the docker container running loki
4. Refresh the query. The filter no longer shows.

It's worth noting that once the docker container is restarted, the filters shows again as expected.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: main
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by gelicia**
**What is this feature?**

Transformation filters are based on returned data frames, which means in the event of a datasource failure, the filter disappears and is not selectable. We would like to have the list populate based off all refIDs, regardless if they return a data frame.

**Which issue(s) does this PR fix?**:

Fixes #107148
Assists https://github.com/grafana/support-escalations/issues/16603

**Special notes for your reviewer:**

Please see issue for replication steps. I attempted to replicate this with the test datasource and shutting down the grafana server, but found that the filter still persisted - this was different than loki. I'd recommend testing with a devenv datasource as described.

Sorry about the couple bad commits in here, I accidentally pushed the commit to an old branch and starting a new branch from the commit meant the prior commits came with it.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard/components/TransformationsEditor/TransformationOperationRow.tsx [hunk 1]
```diff
@@ -138,7 +138,17 @@ export const TransformationOperationRow = ({
       .subscribe(setOutput);
     const prevOutputSubscription = transformDataFrame(prevInputTransforms, data.series, ctx)
       .pipe(mergeMap((before) => transformDataFrame(prevOutputTransforms, before, ctx)))
-      .subscribe(setPrevOutput);
+      .subscribe((result) => {
+        let mergedResult = result;
```
Comment (alexjonspencer1) [inline public/app/features/dashboard/components/TransformationsEditor/TransformationOperationRow.tsx]: Nit (non-blocking): I'm not sure exactly where result is used elsewhere, if it is, etc. Just in case, should we create a shallow copy as to not mutate result directly?

```let mergedResult = [...result]```

Also another non-blocking question: How big can the results array get? Should we consider making it a `Set` for performance improvements?

**Review by alexjonspencer1 — APPROVED** [review]
Just a few non-blocking questions, but LGTM!! 🏆

File: public/app/features/dashboard/components/TransformationsEditor/TransformationOperationRow.tsx (hunk 1 above)
Comment (gelicia) [reply public/app/features/dashboard/components/TransformationsEditor/TransformationOperationRow.tsx]: The use of the spread operator is a good call. As for changing it to set, having the result be an array of dataframes is used all over this component so I'd rather leave it as is for now, and we can change them to sets for performance reasons if needed.
