### PR TITLE
Cloud Monitoring: MQL support

### LINKED ISSUE #24490: GCP Cloud Monitoring - New Query Language
**What would you like to be added**:

GCP has just released a new language for querying metrics called MQL. The existing stackdriver (aka Cloud Monitoring) datasource obviously doesn’t support this yet, but it would be great if it could :-)

https://cloud.google.com/monitoring/mql

**Why is this needed**:

MQL provides a much more powerful query language than the current filtering options. Having the ability to use it in Grafana, would be very useful since the charting capabilities of stackdriver aren’t so great.

### LINKED ISSUE #29667: Cloud monitoring: request sent to the backend with undefined queryType
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. create new dashboard
2. add new panel
3. select a cloud monitoring (stackdriver) datasource
4. select a service (eg `Compute`) without selecting anything else eg project, metric
5. request fails because `queryType` is undefined
6. in the query editor select `Metrics` as `QueryType` (now the request has a valid queryType and succeeds)

**Anything else we need to know?**:

**Environment**:
- Grafana version: master (commit 874f2fafb2fa4c56423773902af419335390f140)
- Data source type & version: Google cloud monitoring
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by mtanda**
**What this PR does / why we need it**:
Add new query language support to Cloud Monitoring.

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/24490
Fixes #29667

### CODE REVIEW

**Comment by mtanda** [comment]
unset stale

**Comment by mtanda** [comment]
Some part of change will be conflicted with https://github.com/grafana/grafana/pull/26400 .
I stop my work until https://github.com/grafana/grafana/pull/26400 is merged (or rejected).

**Comment by mtanda** [comment]
Ready to review.
Sample query is here. Please test and review.
https://cloud.google.com/monitoring/mql/qn-from-api#ql-timeseries-query

**Comment by aknuds1** [comment]
Thank you so much for the PR! We have to discuss internally how to proceed wrt. this feature.

**Comment by mtanda** [comment]
I hope this feature is included in 7.3 beta release...

**Comment by mtanda** [comment]
@aknuds1 Would you tell me the status? What is the blocker?

**Comment by aknuds1** [comment]
@daniellee Are you supposed to provide feedback on this one?

**Comment by daniellee** [comment]
@mtanda @aknuds1 We would really like to have MQL support for CM in Grafana. I can make time this week to sit down with @aknuds1 or @papagian to review this.

**Comment by aknuds1** [comment]
Thanks @daniellee - I can look at this when time permits. Maybe I can get back to you when I'm done reviewing? I find it easier to review async first.

**Comment by daniellee** [comment]
@aknuds1 sure. I can book time on Friday for myself to review this properly.

File: pkg/tsdb/cloudmonitoring/types.go [hunk 1]
```diff
@@ -46,6 +68,7 @@ type (
 		QueryType    string
 		MetricQuery  metricQuery
 		SloQuery     sloQuery
+		MqlQuery     cloudMonitoringMqlQuery
```
Comment (aknuds1) [inline pkg/tsdb/cloudmonitoring/types.go:71]: [Words in names that are initialisms or acronyms (e.g. "URL" or "NATO") have a consistent case](https://github.com/golang/go/wiki/CodeReviewComments#initialisms):
```suggestion
		MQLQuery     cloudMonitoringMqlQuery
```

File: pkg/tsdb/cloudmonitoring/types.go [hunk 2]
```diff
@@ -65,10 +88,60 @@ type (
...
+		TimeSeriesDescriptor timeSeriesDescriptor `json:"timeSeriesDescriptor"`
+		TimeSeriesData       timeSeriesData       `json:"timeSeriesData"`
 	}
 )
 
+type timeSeriesDescriptor struct {
+	LabelDescriptors []struct {
+		Key        string `json:"key"`
+		ValueType  string `json:"valueType"`
+		Descrition string `json:"description"`
```
Comment (aknuds1) [inline pkg/tsdb/cloudmonitoring/types.go:101]:
```suggestion
		Description string `json:"description"`
```

File: pkg/tsdb/cloudmonitoring/mql_query.go [hunk 3]
```diff
@@ -0,0 +1,351 @@
...
+	query.Query += fmt.Sprintf(" | graph_period %s | within d'%s', d'%s'", interval.Text, from.UTC().Format(timeFormat), to.UTC().Format(timeFormat))
+
+	buf, err := json.Marshal(map[string]interface{}{
+		"query": query.Query,
+	})
+	if err != nil {
+		queryResult.Error = err
+		return queryResult, cloudMonitoringResponse{}, nil
+	}
+	req, err := e.createRequest(ctx, e.dsInfo, fmt.Sprintf("cloudmonitoring%s", "v3/projects/"+projectName+"/timeSeries:query"), bytes.NewBuffer(buf))
```
Comment (aknuds1) [inline pkg/tsdb/cloudmonitoring/mql_query.go:58]: The following should be a lot cleaner:
```suggestion
	req, err := e.createRequest(ctx, e.dsInfo, path.Join("cloudmonitoringv3/projects", projectName, "timeSeries:query"), bytes.NewBuffer(buf))
```

File: pkg/tsdb/cloudmonitoring/cloudmonitoring.go [hunk 4]
```diff
@@ -431,7 +452,7 @@ func (e *CloudMonitoringExecutor) executeQuery(ctx context.Context, query *cloud
 		slog.Info("No project name set on query, using project name from datasource", "projectName", projectName)
 	}
 
-	req, err := e.createRequest(ctx, e.dsInfo, query, fmt.Sprintf("cloudmonitoring%s", "v3/projects/"+projectName+"/timeSeries"))
+	req, err := e.createRequest(ctx, e.dsInfo, fmt.Sprintf("cloudmonitoring%s", "v3/projects/"+projectName+"/timeSeries"), nil)
```
Comment (aknuds1) [inline pkg/tsdb/cloudmonitoring/cloudmonitoring.go:455]:
```suggestion
	req, err := e.createRequest(ctx, e.dsInfo, path.Joinf("cloudmonitoringv3/projects", projectName, "timeSeries"), nil)
```

File: pkg/tsdb/cloudmonitoring/mql_query.go [hunk 5]
```diff
@@ -0,0 +1,351 @@
...
+					value := point.Values[n].DoubleValue
+
+					if d.ValueType == "INT64" {
+						parsedValue, err := strconv.ParseFloat(point.Values[n].Int64Value, 64)
+						if err == nil {
+							value = parsedValue
+						}
+					}
+
+					if d.ValueType == "BOOL" {
```
Comment (aknuds1) [inline pkg/tsdb/cloudmonitoring/mql_query.go:164]: An `else` makes the relation between the `ifs` clearer:
```suggestion
					} else if d.ValueType == "BOOL" {
```

File: pkg/tsdb/cloudmonitoring/mql_query.go [hunk 6]
```diff
@@ -0,0 +1,351 @@
...
+						if point.Values[n].BoolValue {
+							value = 1
+						} else {
+							value = 0
+						}
+					}
+
+					points = append(points, tsdb.NewTimePoint(null.FloatFrom(value), float64((point.TimeInterval.EndTime).Unix())*1000))
```
Comment (aknuds1) [inline pkg/tsdb/cloudmonitoring/mql_query.go:172]:
```suggestion
					points = append(points, tsdb.NewTimePoint(null.FloatFrom(value), float64(point.TimeInterval.EndTime.Unix())*1000))
```

File: pkg/tsdb/cloudmonitoring/mql_query.go [hunk 7]
```diff
@@ -0,0 +1,351 @@
...
+							additionalLabels := map[string]string{"bucket": bucketBound}
+							buckets[i] = &tsdb.TimeSeries{
+								Name:   formatLegendKeys(d.MetricKind, defaultMetricName, nil, additionalLabels, &cloudMonitoringQuery{ProjectName: query.ProjectName, AliasBy: query.AliasBy}),
+								Points: make([]tsdb.TimePoint, 0),
+							}
+							if maxKey < i {
+								maxKey = i
+							}
+						}
+						buckets[i].Points = append(buckets[i].Points, tsdb.NewTimePoint(null.FloatFrom(value), float64((point.TimeInterval.EndTime).Unix())*1000))
```
Comment (aknuds1) [inline pkg/tsdb/cloudmonitoring/mql_query.go:208]:
```suggestion
						buckets[i].Points = append(buckets[i].Points, tsdb.NewTimePoint(null.FloatFrom(value), float64(point.TimeInterval.EndTime.Unix())*1000))
```

File: pkg/tsdb/cloudmonitoring/types.go [hunk 8]
```diff
@@ -65,10 +88,60 @@ type (
...
+	} `json:"labelDescriptors"`
+	PointDescriptors []struct {
+		Key        string `json:"key"`
+		ValueType  string `json:"valueType"`
+		MetricKind string `json:"metricKind"`
+	} `json:"pointDescriptors"`
+}
+type timeSeriesData []struct {
```
Comment (aknuds1) [inline pkg/tsdb/cloudmonitoring/types.go:109]:
```suggestion
}

type timeSeriesData []struct {
```

File: pkg/tsdb/cloudmonitoring/types.go [hunk 9]
```diff
@@ -18,6 +31,15 @@ type (
 		Slo         string
 	}
 
+	cloudMonitoringMqlQuery struct {
+		RefID       string
+		ProjectName string
+		Query       string
+		IntervalMs  int64
```
Comment (aknuds1) [inline pkg/tsdb/cloudmonitoring/types.go:38]:
```suggestion
		IntervalMS  int64
```

File: pkg/tsdb/cloudmonitoring/cloudmonitoring.go [hunk 10]
```diff
@@ -480,7 +501,7 @@ func (e *CloudMonitoringExecutor) executeQuery(ctx context.Context, query *cloud
 	return queryResult, data, nil
 }
 
-func (e *CloudMonitoringExecutor) unmarshalResponse(res *http.Response) (cloudMonitoringResponse, error) {
+func (e *cloudMonitoringQuery) unmarshalResponse(res *http.Response) (cloudMonitoringResponse, error) {
```
Comment (aknuds1) [inline pkg/tsdb/cloudmonitoring/cloudmonitoring.go:504]:
```suggestion
func (q *cloudMonitoringQuery) unmarshalResponse(res *http.Response) (cloudMonitoringResponse, error) {
```

File: pkg/tsdb/cloudmonitoring/cloudmonitoring.go [hunk 11]
```diff
@@ -535,7 +556,7 @@ func handleDistributionSeries(series timeSeries, defaultMetricName string, serie
 	})
 }
 
-func (e *CloudMonitoringExecutor) parseResponse(queryRes *tsdb.QueryResult, data cloudMonitoringResponse, query *cloudMonitoringQuery) error {
+func (query *cloudMonitoringQuery) parseResponse(queryRes *tsdb.QueryResult, data cloudMonitoringResponse) error {
```
Comment (aknuds1) [inline pkg/tsdb/cloudmonitoring/cloudmonitoring.go:559]: [The name of a method's receiver should be a reflection of its identity; often a one or two letter abbreviation of its type suffices (such as "c" or "cl" for "Client")](https://github.com/golang/go/wiki/CodeReviewComments#receiver-names):
```suggestion
func (q *cloudMonitoringQuery) parseResponse(queryRes *tsdb.QueryResult, data cloudMonitoringResponse) error {
```

**Review by aknuds1 — COMMENTED** [review]
Generally looks good to me, but made some suggestions for nits that should be cleaned up. I haven't tested yet, which I figure I should do before approving.

**Comment by aknuds1** [comment]
@mtanda Do you want me to fix up the compilation failures after applying the suggestions, and push to your branch?

**Comment by mtanda** [comment]
@aknuds1 Thanks for suggestion. I fixed it.

**Comment by mtanda** [comment]
If you want to refactor my code, feel free to edit my code :-)

**Comment by aknuds1** [comment]
@mtanda Thanks, I will try to fix the build failure.

**Comment by aknuds1** [comment]
@mtanda Your PR description still says you're not finished with all of the implementation. Is that comment out of date, or is something still missing?

**Comment by mtanda** [comment]
@aknuds1 The comment is out of date. I finished the implementation.

**Comment by aknuds1** [comment]
Thanks for the update!

**Review by daniellee — CHANGES_REQUESTED** [review]
Here is my review.

## Alias by

The alias by field does not work in the same way as the visual metrics mode. The docs for the alias by field have patterns for the aliases that are divided into metric type patterns and label patterns: https://grafana.com/docs/grafana/latest/datasources/cloudmonitoring/#metric-queries
In MQL mode, the metadata is not formatted into the same categories.

For example, this pattern does not work `{{metric.label.instance_name}}` but `{{metric.instance_name}}` does. The logic for creating the metric type and label grouping for the metric mode can be [found here](https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudmonitoring/cloudmonitoring.go#L541-L597). The pattern `metric.label.xxx` is hardcoded here. This PR takes the label fields and puts them in a map and breaks that convention.

## Query Editor

The query field is a simple input field rather using something like Monaco which means the experience is not as good as the query editor in the Google console. But I think that is fine as a first step. Erik or someone else with frontend skills could add that at a later stage.

But can you switch to use a text area instead? The input field is very small when writing a query:

image

## Documentation

There is no documentation. As this is a very simple editor, it can be quite short. The biggest thing to cover is how to interact with the selected timerange and how to group by time using built in variables like $__interval or $__interval_ms.

**Comment by mtanda** [comment]
> This PR takes the label fields and puts them in a map and breaks that convention.
MQL doesn't response labels separately.

https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/query#TimeSeriesDescriptor
https://github.com/grafana/grafana/pull/26551/files#diff-232a8a4ec5dc81f22c3aa3fcc551e0045b44bdcb5fc1f4a21afb081654f542d0R128-R148

There is no way to know where the label come from.
Due to incompatibility between past query feature and MQL, breaking changes is not avoidable...

**Comment by mtanda** [comment]
> But can you switch to use a text area instead? The input field is very small when writing a query:

I switched to use a text area.

**Comment by aknuds1** [comment]
I'll try to test soon :)

File: docs/sources/datasources/cloudmonitoring.md [hunk 12]
```diff
@@ -226,6 +226,24 @@ The Alias By field allows you to control the format of the legend keys for SLO q
...
+
+The MQL query builder in the Google Cloud Monitoring data source allows you to display MQL result in time series format. To get an understanding of the basic concepts in MQL, please refer to Google Cloud Monitoring's [official docs](https://cloud.google.com/monitoring/mql).
+
+#### How to create an MQL query
+
+To create an MQL query, follow these steps:
+
+1. Choose the option **Monitoring Query Language (MQL)** in the **Query Type** dropdown.
+1. Choose a project from the **Project** dropdown.
+1. Specify [MQL](https://cloud.google.com/monitoring/mql/query-language) to query field.
```
Comment (aknuds1) [inline docs/sources/datasources/cloudmonitoring.md:241]: The following wording seems more correct/understandable to me:
```suggestion
1. Specify [MQL](https://cloud.google.com/monitoring/mql/query-language) in the query field.
```

File: docs/sources/datasources/cloudmonitoring.md [hunk 13]
```diff
@@ -226,6 +226,24 @@ The Alias By field allows you to control the format of the legend keys for SLO q
 
 SLO queries use the same [alignment period functionality as metric queries]({{< relref "#metric-queries" >}}).
 
+### MQL (Monitoring Query Language) queries
+
+> Only available in Grafana v7.x+
```
Comment (oddlittlebird) [inline docs/sources/datasources/cloudmonitoring.md:231]:
```suggestion
> **Note:** Only available in Grafana v7.4+.
```

File: docs/sources/datasources/cloudmonitoring.md [hunk 14]
```diff
@@ -226,6 +226,24 @@ The Alias By field allows you to control the format of the legend keys for SLO q
...
+
+The MQL query builder in the Google Cloud Monitoring data source allows you to display MQL result in time series format. To get an understanding of the basic concepts in MQL, please refer to Google Cloud Monitoring's [official docs](https://cloud.google.com/monitoring/mql).
```
Comment (oddlittlebird) [inline docs/sources/datasources/cloudmonitoring.md:233]:
```suggestion
The MQL query builder in the Google Cloud Monitoring data source allows you to display MQL result in time series format. To get an understanding of the basic concepts in MQL, refer to [Google Cloud Monitoring documentation](https://cloud.google.com/monitoring/mql).
```

File: docs/sources/datasources/cloudmonitoring.md [hunk 15]
```diff
@@ -226,6 +226,24 @@ The Alias By field allows you to control the format of the legend keys for SLO q
...
+
+#### How to create an MQL query
```
Comment (oddlittlebird) [inline docs/sources/datasources/cloudmonitoring.md:235]:
```suggestion
#### Create an MQL query
```

File: docs/sources/datasources/cloudmonitoring.md [hunk 16]
```diff
@@ -226,6 +226,24 @@ The Alias By field allows you to control the format of the legend keys for SLO q
...
+
+To create an MQL query, follow these steps:
+
+1. Choose the option **Monitoring Query Language (MQL)** in the **Query Type** dropdown.
+1. Choose a project from the **Project** dropdown.
```
Comment (oddlittlebird) [inline docs/sources/datasources/cloudmonitoring.md:240]:
```suggestion
1. Choose a project from the **Project** list.
```

File: docs/sources/datasources/cloudmonitoring.md [hunk 17]
```diff
@@ -226,6 +226,24 @@ The Alias By field allows you to control the format of the legend keys for SLO q
...
+
+> Only available in Grafana v7.x+
+
+The MQL query builder in the Google Cloud Monitoring data source allows you to display MQL result in time series format. To get an understanding of the basic concepts in MQL, please refer to Google Cloud Monitoring's [official docs](https://cloud.google.com/monitoring/mql).
+
+#### How to create an MQL query
+
+To create an MQL query, follow these steps:
+
+1. Choose the option **Monitoring Query Language (MQL)** in the **Query Type** dropdown.
```
Comment (oddlittlebird) [inline docs/sources/datasources/cloudmonitoring.md:239]:
```suggestion
1. In the **Query Type** list, click **Monitoring Query Language (MQL)**.
```

Comment (oddlittlebird) [reply docs/sources/datasources/cloudmonitoring.md:239]: When writing instructions, it is a good idea to tell people where to do the thing before you tell them what to do.

File: docs/sources/datasources/cloudmonitoring.md (hunk 12 above)
Comment (oddlittlebird) [inline docs/sources/datasources/cloudmonitoring.md:241]: Unclear. Am I selecting MQL from a list? Am I typing the entry somewhere? If so, where? 

Also, the link here is confusing. Why are you sending me to another website?

File: docs/sources/datasources/cloudmonitoring.md [hunk 18]
```diff
@@ -226,6 +226,24 @@ The Alias By field allows you to control the format of the legend keys for SLO q
...
+1. Choose a project from the **Project** dropdown.
+1. Specify [MQL](https://cloud.google.com/monitoring/mql/query-language) to query field.
+
+#### Alias Patterns for MQL queries
```
Comment (oddlittlebird) [inline docs/sources/datasources/cloudmonitoring.md:243]:
```suggestion
#### Alias patterns for MQL queries
```

File: docs/sources/datasources/cloudmonitoring.md [hunk 19]
```diff
@@ -226,6 +226,24 @@ The Alias By field allows you to control the format of the legend keys for SLO q
...
+
+MQL queries use the same [alias patterns as metric queries]({{< relref "#metric-queries" >}}).
```
Comment (oddlittlebird) [inline docs/sources/datasources/cloudmonitoring.md:245]:
```suggestion
MQL queries use the same alias patterns as [metric queries]({{< relref "#metric-queries" >}}).
```

File: docs/sources/datasources/cloudmonitoring.md (hunk 12 above)
Comment (mtanda) [reply docs/sources/datasources/cloudmonitoring.md:241]: User edit MQL in text area.
image

I follow the convention to include related link in step guide.

**Review by papagian — CHANGES_REQUESTED** [review]
Thank you for your contribution; It looks promising!
I have a suggestion for fixing deep linking for MQL queries.
In addition to this, I have noticed that there is no way to define an MQL query for annotations but probably this can be addressed in a separate PR:

Screenshot 2020-10-28 at 19 55 57

File: pkg/tsdb/cloudmonitoring/cloudmonitoring_test.go [hunk 20]
```diff
@@ -997,6 +1061,16 @@ func loadTestFile(path string) (cloudMonitoringResponse, error) {
 	return data, err
 }
 
+func getQueriesFromInterface(qis []cloudMonitoringQueryInterface) []*cloudMonitoringQuery {
```
Comment (papagian) [inline pkg/tsdb/cloudmonitoring/cloudmonitoring_test.go:1064]: Since it returns an array of `*cloudMonitoringQuery` I would suggest renaming it:
```suggestion
func getCloudMonitoringQueriesFromInterface(qis []cloudMonitoringQueryInterface) []*cloudMonitoringQuery {
```

File: pkg/tsdb/cloudmonitoring/cloudmonitoring.go [hunk 21]
```diff
@@ -203,24 +209,26 @@ func (e *CloudMonitoringExecutor) executeTimeSeriesQuery(ctx context.Context, ts
...
+			for _, s := range resp.TimeSeries {
+				resourceType = s.Resource.Type
+				// set the first resource type found
+				break
+			}
+			cmq.Params.Set("resourceType", resourceType)
 		}
-		query.Params.Set("resourceType", resourceType)
 		dl := ""
 		if len(resp.TimeSeries) > 0 {
```
[the remark this answers is not in the document]
Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/cloudmonitoring.go]: Thanks for suggestion.
I tested the code https://github.com/grafana/grafana/pull/26551/commits/02421d713512415818405d48e2760a3c8e3f376e and confirm it works!

**Review by daniellee — CHANGES_REQUESTED** [review]
The label alias patterns are working now but the Metric Type patterns are not for me:
image

- `{{metric.name}}` doesn't return anything
- `{{metric.type}}` returns `GAUGE`
- `{{metric.service}} doesn't return anything

A  nit-pick that can be fixed in the future - if I don't type anything in the MQL query field, then get a long bad request error. Could ignore empty queries instead.

**Comment by aknuds1** [comment]
Sorry, haven't had the time to review this yet. I should be able to now at least.

**Comment by mtanda** [comment]
@daniellee MQL allow to fetch multiple time series at once.

https://cloud.google.com/monitoring/mql/reference#fetching-group
```
  { fetch gce_instance :: compute.googleapis.com/instance/cpu/utilization ;
    fetch gce_instance :: compute.googleapis.com/instance/cpu/reserved_cores
  } | filter zone = 'asia-east1-a' | join | div
```

It is technically possible in some simple case if parsing MQL..., but supporting `{{metric.name}}`, `{{metric.type}}` and `{{metric.service}}` is difficult.

I add notice about the limitation.
And show time series key if `{{metric.name}}` or `{{metric.type}}` is used.

**Review by papagian — CHANGES_REQUESTED** [review]
Deep linking works fine now!
Something else I've noticed: if I have one metric query and one MQL query in the same panel and both return data (several time series) only the MQL appears in the graph (I have to disable it for seeing the other).
I'll be back with more details if I find out why.

**Comment by mtanda** [comment]
@papagian Thanks for testing!
I can't replicate the issue locally. Would you share the dashboard JSON?

**Comment by papagian** [comment]
> @papagian Thanks for testing!
> I can't replicate the issue locally. Would you share the dashboard JSON?

my mistake; I thought that I couldn't see all the legends from both queries but they were just too many and I had to scroll down, sorry.

**Review by papagian — APPROVED** [review]
LGTM, thanks you for this feature!

**Comment by mtanda** [comment]
@papagian no problem, thanks for check again!

File: pkg/tsdb/cloudmonitoring/mql_query.go [hunk 22]
```diff
@@ -0,0 +1,357 @@
...
+		queryResult.Error = err
+		return queryResult, cloudMonitoringResponse{}, nil
+	}
+
+	return queryResult, data, nil
+}
+
+func (query cloudMonitoringMQLQuery) unmarshalResponse(res *http.Response) (cloudMonitoringResponse, error) {
+	body, err := ioutil.ReadAll(res.Body)
+	defer res.Body.Close()
```
[the remark this answers is not in the document]
Comment (mtanda) [reply pkg/tsdb/cloudmonitoring/mql_query.go:101]: The code is come from https://github.com/grafana/grafana/blob/v7.3.2/pkg/tsdb/cloudmonitoring/cloudmonitoring.go#L485 .
Anyway, I'm willing to move it!

**Comment by mtanda** [comment]
I hope to merge this before conflicting change...
https://github.com/grafana/grafana/commit/112a755e188b451921fda87cf5938b88363cf07e#diff-71862e079d75143b30ed8b1ed31035e4c988a541e201d9d72cdba5e4af478037

**Comment by mtanda** [comment]
If I need to fix anything, please notify me.

**Review by sunker — CHANGES_REQUESTED** [review]
Great work @mtanda! This is some feedback that I have after testing your new feature. Haven't looked into the code yet. 

I don't like the fact that a new query is issued every time the onchange event is triggered in the textarea. It's annoying, and also it's not very cost-efficient since the users pay per request. I suggest a new query should only be issued onBlur or when SHIFT+Enter is pressed (same as for example Cloudwatch logs). In order for this to work, some refactoring needs to be done. 
[These](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/cloud-monitoring/components/QueryEditor.tsx#L59-L62) lines of codes assumes that when a query model change occurs, the query should be ran. That was the case for metric queries and SLO queries, but obviously not for MQL queries. See if you can refactor this, and if not I'll help you. 

Also I'm not a great fan of having a text area for query input. Ideally, we would have something like we have for cloudwatch logs, but I don't expect you to do that in this PR. However, for now it would be nice if you could add a placeholder to the text area and also use the class slate-query-field to get some styling from logs query fields. This would be a temporary fix that me or someone from the frontend platform team could improve at some point in the future. 
`<TextArea
        className="slate-query-field"
        placeholder="Enter a Cloud Monitoring MQL query (run with Shift+Enter)"
        ...
      />`

**Comment by mtanda** [comment]
@sunker Welcome Back and thanks feedback!
Improving frontend is not easy for me, I fix query editor little, but it still doesn't support `shift-enter` .

**Comment by sunker** [comment]
> @sunker Welcome Back and thanks feedback!
> Improving frontend is not easy for me, I fix query editor little, but it still doesn't support `shift-enter` .

Know I've added Shift+Enter shortcut to run the query.

**Comment by sunker** [comment]
I'm not completely sure adding a new Query type for MQL makes sense. Adding a new query type for MQL would suggest is a new type of query, but really it's not - it's just a different way of querying metrics right? Maybe we should have a different metric query modes instead - Query editor and Basic text? What do you think @daniellee? 

See here how they do it in GCP
MQL

**Comment by mtanda** [comment]
remove stale

**Comment by sunker** [comment]
@mtanda sorry I had to force push to this branch

I've made some refactoring. Instead of having MQL as a new query type, I've added two different editor modes for query type metric - a visual query builder and a raw query builder (MQL). There are a few minor issues that I haven't had the time to fix yet, but I'll do that within the next couple of days. 

Question to you @mtanda: At the moment we always use the Grafana dashboard timerange. What happens if the user specifies a custom time range in the query using the `within` keyword? At the moment that doesn't work, but I wonder if we should allow that to happen? In case a custom time range is specified we could ignore the dashboard time range.

**Comment by mtanda** [comment]
@sunker I think, Grafana doesn't need to support `within` for specifying custom time range.
It will confuse user.
If query editor doesn't parse MQL, it is difficult to check whether `within` is included or not.
First step is notice about the limitation in document.
If user want to use `within`, they will create a feature request, wait for feedback.

File: docs/sources/datasources/cloudmonitoring.md [hunk 23]
```diff
@@ -222,6 +222,27 @@ The Alias By field allows you to control the format of the legend keys for SLO q
 
 SLO queries use the same [alignment period functionality as metric queries]({{< relref "#metric-queries" >}}).
 
+### MQL (Monitoring Query Language) queries
+
+> **Note:** Only available in Grafana v7.4+.
+
+The MQL query builder in the Google Cloud Monitoring data source allows you to display MQL results in time series format. To get an understanding of the basic concepts in MQL, refer to [Google Cloud Monitoring documentation](https://cloud.google.com/monitoring/mql).
```
Comment (osg-grafana) [inline docs/sources/datasources/cloudmonitoring.md:229]: Please change that link text as follows so that it is WYSIWYG:

[Introduction to Monitoring Query Language](https://cloud.google.com/monitoring/mql)

Comment (sunker) [reply docs/sources/datasources/cloudmonitoring.md]: fixed! thanks for feedback @osg-grafana

**Comment by sunker** [comment]
> @sunker I think, Grafana doesn't need to support `within` for specifying custom time range.
> It will confuse user.
> If query editor doesn't parse MQL, it is difficult to check whether `within` is included or not.
> First step is notice about the limitation in document.
> If user want to use `within`, they will create a feature request, wait for feedback.

I agree @mtanda, thanks for feedback!  

Eventually I think we should add support for mql autocomplete, but that could wait. From my perspective this is good enough for merging. Would you mind reviewing my latest changes @mtanda?

**Comment by mtanda** [comment]
@sunker Thanks for improving query editor, and refactor backend code. Looks good to me!

**Comment by sunker** [comment]
Got massive conflicts with master since cloud monitoring has been converted to use data frames meanwhile this pr has been developed, so I ended up squashing all commits in this branch and rebase on top of master.

**Comment by sunker** [comment]
When creating deep link, we added a resource type if resource type wasn't defined in the Grafana query editor. I ended up removing that for two reasons. One being it does work without it, and another being I think it's misleading that the Grafana query editor is not exactly the same as the query that the deep link refers to. 

Instead a created an [issue](#30344) to auto set resource type in the grafana query editor.

**Review by sunker — APPROVED** [review]

**Review by ying-jeanne — CHANGES_REQUESTED** [review]

**Review by ying-jeanne — APPROVED** [review]

**Review by papagian — APPROVED** [review]
I have tested and everything works fine expects of some issues with deep linking and selecting resource type for template variable which already existed and are not introduced by these modifications.

I have noticed also some limitations (not able using MQL in template variable and annotation queries) which could be introduced in the future.

**Review by daniellee — APPROVED** [review]

**Comment by sunker** [comment]
> I have tested and everything works fine expects of some issues with deep linking and selecting resource type for template variable which already existed and are not introduced by these modifications.
> 
> I have noticed also some limitations (not able using MQL in template variable and annotation queries) which could be introduced in the future.

Yes we can add support for that later on.

**Comment by mtanda** [comment]
Thanks for @sunker and all of reviewers!

**Comment by sunker** [comment]
Thank YOU @mtanda for contributing!
