### PR TITLE
Cloudwatch: Fix duplicated time series

### LINKED ISSUE #35388: CloudWatch: issue #28301 is back after updating to grafana 8.0.0
Issue #28301 is back after updating to grafana 8.0.0

### PR DESCRIPTION
**Pull request by sunker**
**What this PR does / why we need it**:
This PR fixes a bug that could duplicate time series in case a panel has more than one query row. The bug was introduced when [migrating cloudwatch to new SDK contracts](https://github.com/grafana/grafana/pull/31149).

The SDK migration introduced an extra loop in order to be able to connect a query ref id with a response ref id. This extra loop ran each query one extra time in case the request contained more than one query. The reason it worked in some cases and it didn't work in other cases was due to raise conditions - the query that first wrote to the response channel won. 
 
**Which issue(s) this PR fixes**:

Fixes #35388

**Special notes for your reviewer**:

When an error occurred in any of the child methods of `executeTimeSeriesQuery`, all queries were looped through and a corresponding frame was created with and error (see example below). These errors were not being handled individually in the [frontend](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloudwatch/datasource.ts#L555-L572), so therefore the user would only see a `Bad request` error on the top left of the panel. This PR changes that and instead returns the big error. That way, the real error is propagated to the panel and shown to the user. 

```go
for _, query := range requestQueries {
  resultChan <- &backend.DataResponse{
	  Frames: data.Frames{data.NewFrame(query.RefId)},
	  Error:  err,
  }
}
```
errormessage

### CODE REVIEW

File: pkg/tsdb/cloudwatch/time_series_query.go [hunk 1]
```diff
@@ -5,120 +5,105 @@ import (
...
+		region := r
+		eg.Go(func() error {
+			defer func() {
+				if err := recover(); err != nil {
+					plog.Error("Execute Get Metric Data Query Panic", "error", err, "stack", log.Stack(1))
+					if theErr, ok := err.(error); ok {
+						resultChan <- &responseWrapper{
+							DataResponse: &backend.DataResponse{
+								Error: theErr,
+							},
```
Comment (andresmgot) [inline pkg/tsdb/cloudwatch/time_series_query.go:54]: is it okay to have `refID: 0` here?

**Review by andresmgot — APPROVED** [review]
LGTM. Great catch! Tested locally and worked as expected :+1:

File: pkg/tsdb/cloudwatch/time_series_query.go (hunk 1 above)
Comment (sunker) [reply pkg/tsdb/cloudwatch/time_series_query.go:54]: Yeah I think it's okay. Or, I mean the real error that caused the panic, is not passed all the way to the panel since the error is not attached to a certain ref id. The panel just receives a general error. But I think that's fine.
