### PR TITLE
Modals: Fix closing of modals with escape key

### LINKED ISSUE #30592: Modal: Esc key no longer closes modals
I noticed I can no longer close modals with the Esc key.

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
This PR adds a listener to the grafana ui modal to handle closing by pressing the Esc key. 
**Which issue(s) this PR fixes**:

Fixes #30592

**Special notes for your reviewer**:
Initial testing suggests this works but I'm not sure if this is the right direction or if we should be making use of the `KeybindingSrv` class to handle this within the Grafana app.

### CODE REVIEW

File: packages/grafana-ui/src/components/Modal/Modal.tsx [hunk 1]
```diff
@@ -40,6 +40,23 @@ export function Modal(props: PropsWithChildren<Props>): ReturnType<FC<Props>> {
     }
   }, [propsOnDismiss]);
 
+  const onEscKey = (ev: KeyboardEvent): void => {
```
Comment (Clarity-89) [inline packages/grafana-ui/src/components/Modal/Modal.tsx:43]:
```suggestion
  const onEscKey = (ev: KeyboardEvent) => {
```
I think it's better to infer as much as possible, so it's less type maintenance.

**Review by Clarity-89 — APPROVED** [review]
Looks good! I think `KeybindingSrv` is used for global events, whereas here `Esc` key should work per specific Modal component.

**Review by dprokop — APPROVED** [review]
Looks good. One thing to consider is if this behaviour should not be controlled via property, i.e. `closeOnEscape` or sth similar.
