### PR TITLE
Prometheus: Fix handling errors in streaming client

### LINKED ISSUE #61507: Prometheus: Streaming client gives different errors than the buffered client
The Prometheus streaming client was made the default client in Grafana v9.3 to replace the old buffered client. Since then there have been reports that the streaming client returns different errors than the buffered client.

For example, when there is an issue with the prometheus instance itself, the error is returned as `downstreamError`. This happened in a [customer issue](https://github.com/grafana/support-escalations/issues/4629) where a prometheus instance had a timeout and returned the `plugin.downstreamError`.

Another example from a customer is shown below
Streaming client
Screen Shot 2023-01-13 at 2 36 31 PM

Buffered client
Screen Shot 2023-01-13 at 2 37 26 PM

Currently, the feature toggle for using the buffered client can be set so that users get errors from Prometheus. 
[feature_toggles]
prometheusBufferedClient = true

Since we intend to remove the buffered client, we will investigate the difference in error handling between the streaming and buffered client.

**Environment**:
- Grafana version: v9.3
- Data source type & version: Prometheus

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

Since we are returning the result directly from json parser, we failed to handle errors properly. 
See the issue: https://github.com/grafana/grafana/issues/52430

This was a bug that was introduced in the PR https://github.com/grafana/grafana/pull/57209 which was reviewed by me and failed to catch. So this PR is fixing it.

**Why do we need this feature?**

To handle errors properly in the new Prometheus client.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/61507

**Special notes for your reviewer**:
To Reproduce:
- Checkout `main` branch
- In the explore while a Prometheus datasource selected run `asd{` as query
- Observe that no meaningful error message is being displayed

After this fix:
image

### CODE REVIEW

**Review by bohandley — APPROVED** [review]
LGTM! Good fix!

Without the fix we get a generic plugin error
Screen Shot 2023-01-17 at 5 12 04 PM

With the fix we get more details
Screen Shot 2023-01-17 at 5 13 35 PM

File: pkg/tsdb/prometheus/querydata/response.go [hunk 1]
```diff
@@ -29,6 +29,11 @@ func (s *QueryData) parseResponse(ctx context.Context, q *models.Query, res *htt
 		MatrixWideSeries: s.enableWideSeries,
 		VectorWideSeries: s.enableWideSeries,
 	})
+
+	if r.Error != nil {
+		return r, r.Error
+	}
+
```
Comment (kylebrandt) [inline pkg/tsdb/prometheus/querydata/response.go:36]: I believe we should add a frame with no fields (if there isn't one already), and return after adding the metadata to the frame (So interpolated queries are still returned). See para 2 of https://github.com/grafana/grafana-plugin-sdk-go/tree/main/data/contract_docs#error-responses : 

> When an error is returned with the DataResponse, a single frame with no fields may be included as well. If the error is present, this will not be considered "No Data". This frame is included so that metadata, in particular a Frame's ExecutedQueryString, can be returned to the caller with an error.

Comment (itsmylife) [reply pkg/tsdb/prometheus/querydata/response.go:36]: I think we always have a frame in it. See https://github.com/grafana/grafana/pull/57209/files#r999603684

**Review by kylebrandt — APPROVED** [review]

**Comment by samjewell** [comment]
@itsmylife you said:
> which was reviewed by me and failed to catch

But rather than considering this a human error, or at least considering how we could prevent this in future, I'm wondering - are we missing a software test here (or maybe some other kind of code-restructuring which would prevent this bug from recurring in the future)? Maybe an integration test or something?
