### PR TITLE
OpenTSDB: Fix showing error on query

### LINKED ISSUE #27618: Explore OpenTSDB: React error when populating metric name from auto-complete
**What happened**:
Explore gets a React error when I click on a metric from an OpenTSDB datasource `An unexpected error happened`
```Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bcode%2C%20message%2C%20details%2C%20trace%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.```

grafana-opentsdb-explore-bug

**What you expected to happen**:
Clicking auto-complete metric populates metric name field with metric and executes query.  

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to /explore 
1. Pick an OpenTSDB data source from the data source drop-down
1. Put cursor in the “metric name” field
1. Start typing metric and with metric name partially complete pick one of the entries from auto-complete
1. Get a React error

**Anything else we need to know?**:
It executes an OpenTSDB query without filling in the value of the metric from the auto-complete, resulting in a HTTP 400.  It seems like it maybe failing to map that to the UI properly.  

**Environment**:
- Grafana version: Tested in 7.2.0-beta1 and 6.7.4
- Data source type & version: OpenTSDB 2.4
- OS Grafana is installed on: Alpine docker images
- User OS & Browser: Mac OS Catalina & Firefox 
- Grafana plugins: None
- Others:

### PR DESCRIPTION
**Pull request by zoltanbedi**
**Which issue(s) this PR fixes**:

Fixes #27618

Opened issue https://github.com/grafana/grafana/issues/32783 for error handling improvements in general.

### CODE REVIEW

File: public/app/plugins/datasource/opentsdb/datasource.ts [hunk 1]
```diff
@@ -84,6 +84,10 @@ export default class OpenTsDatasource extends DataSourceApi<OpenTsdbQuery, OpenT
     });
 
     return this.performTimeSeriesQuery(queries, start, end).pipe(
+      catchError((err) => {
+        // Throw the error message here instead of the whole object to workaround the error parsing error.
+        throw err?.data?.error?.message || 'Error performing time series query.';
```
Comment (aocenas) [inline public/app/plugins/datasource/opentsdb/datasource.ts:89]: Where is the error parsing code? Shouldn't it handle errors there in more robust way?

Comment (zoltanbedi) [reply public/app/plugins/datasource/opentsdb/datasource.ts:89]: So the error comes back in this format
```json
{
  "error": {
    "code": 400,
    "message": "No such name for 'metrics': 'a'",
    "details": "No such name for 'metrics': 'a'",
    "trace": "net.opentsdb.tsd.BadRequestException: No such name for 'metrics': 'a'\n\tat net.opentsdb.tsd.QueryRpc$1ErrorCB.call(QueryRpc.java:216) [tsdb-2.4.0.jar:]\n\tat"
  }
}
```

And the code error parsing code is here: https://github.com/grafana/grafana/blob/master/packages/grafana-runtime/src/utils/queryResponse.ts#L150

Should we make changes here instead?

Comment (aocenas) [reply public/app/plugins/datasource/opentsdb/datasource.ts:89]: Hmm no I think it makes sense that we massage the opentsdb error a bit so it is normalized for the query pipeline. What seems of to me is that in the original issue, before this fix, it resulted in a react error that would remove the whole page. From the code in https://github.com/grafana/grafana/blob/master/packages/grafana-runtime/src/utils/queryResponse.ts#L150 I would just assume we show some non helpful message or no message at all but not that the whole explore would crash. So That what I mean whether we don't have some weird code somewhere in react that just crashes any time the error from the query is a bit different than expected.

**Review by aocenas — APPROVED** [review]
