### PR TITLE
Fix accessibility issues in traces query editor

### LINKED ISSUE #70985: A11y: Fix keyboard accessibility in `public/app/plugins/datasource/azuremonitor/components/TracesQueryEditor/Filter.tsx`
# How to make progress on this issue

- 🔍 open the file and search for `TODO: fix keyboard a11y`
- ❌ remove the `eslint-disable` comment
- 🔧 fix the lint error(s) that should now be showing
  - this will be heavily dependant on context
  - should you be able to interact with this element via the keyboard or is there another element that already handles the same behaviour via the keyboard?
  - in some cases, the best fix is to **use the correct semantic element** for the job. if something behaves like a button but we want it to look different, we can still use the `<button type="button">` element and style it appropriately. this will handle all our keyboard accessibility needs for us. there's even a handy [`clearButtonStyles`](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Button/Button.tsx#L306) util to undo the basic button styling.
  - if using a `<button>` or other similar interactive element is not appropriate, refer to the documentation [here](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/click-events-have-key-events.md) and [here](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-static-element-interactions.md). this will likely involve setting a `role` and implementing a custom `onKeyPress`
- 🧪 test it!
  - can you interact with this element using the keyboard now?
- 🥳 celebrate for making grafana a better product!

### PR DESCRIPTION
**Pull request by aangelisc**
- Ensure key events exist and role is appropriately set
- Ensure that when the filter field is cleared the query is updated

Fixes #70985

### CODE REVIEW

File: public/app/plugins/datasource/azuremonitor/components/TracesQueryEditor/Filter.tsx [hunk 1]
```diff
@@ -169,6 +167,10 @@ const Option = (props: React.PropsWithChildren<OptionProps>) => {
       aria-label="Select option"
       title={data.title}
       onClick={onClickMultiOption}
+      onKeyDown={onClickMultiOption}
+      role={'checkbox'}
```
Comment (adamyeats) [inline public/app/plugins/datasource/azuremonitor/components/TracesQueryEditor/Filter.tsx:171]:
```suggestion
      role="checkbox"
```

**Review by adamyeats — APPROVED** [review]
One very minor thing, otherwise LGTM! 👍
