### PR TITLE
Alerting: Allow specifying uid for new rules added to groups

### LINKED ISSUE #98283: Alerting: Provisioning API fails with 500 response when trying to batch-create rules in a group with client-provided rule UIDs
### What happened?

PUT `http://0.0.0.0:3000/api/v1/provisioning/folder/{folderUID}/rule-groups/{ruleGroupName}` returns HTTP status 500 when the request payload includes rule UIDs that don't already exist in Grafana

Response Body:
`{"message":"Internal Server Error","traceID":""}`

I can create rules by using this API and omitting the `uid` field for each rule, but my use case requires that I use client-provided rule UIDs

### What did you expect to happen?

I expected the rules to be created with the specified rule UID. I'm able to create a rule with client-provided UID by POSTing to `/api/v1/provisioning/alert-rules` so I'd expect to be able to do the same with the `api/v1/provisioning/folder/{FolderUID}/rule-groups/{ruleGroupName}` api.

Unlike the `/api/v1/provisioning/alert-rules` where I must use the POST verb to create rules, and can only use PUT to update existing rules, the `api/v1/provisioning/folder/{FolderUID}/rule-groups/{ruleGroupName}` doesn't support a POST verb, but does allow me to create new rules via PUT. It just doesn't support client-provided rule UIDs.

If this was intentionally not a supported operation, I'd have expected some kind of 4XX error code.

My workaround is to pre-create all my rules with POST `/api/v1/provisioning/alert-rules` and once they're all created I can use the rule-groups API to bulk-update them.

### Did this work before?

No, I believe the API has always worked this way

### How do we reproduce it?

1. Launch Grafana (here using Docker as an example)
```sh
docker run -e GF_AUTH_ANONYMOUS_ENABLED=true -e GF_AUTH_ANONYMOUS_ORG_ROLE=Admin -p 3000:3000 --name=grafana grafana/grafana:11.2.0
```
2. Create folder and get its UID (here using `jq`, can also be extracted manually from the response)
```
FOLDER_UID=$(curl -X POST -H 'Content-Type: application/json' -d '{"title": "test_folder"}' http://localhost:3000/api/folders | jq '.uid')
```
3. Attempt to create a rule in a rule group with client-provided rule UID
```sh
curl -X PUT -H 'Content-Type: application/json' -d '
{
  "title": "hello world",
  "folderUid": "de790ko9eje2od",
  "interval": 1200,
  "rules": [
    {
      "title": "TEST-API_3",
      "folderUID": '$FOLDER_UID',
      "noDataState": "OK",
      "execErrState": "OK",
      "for": "5m",
      "orgId": 1,
      "uid": "ce7cc4i4iu0hse",
      "condition": "A",
      "data": [
        {
          "refId": "A",
          "queryType": "",
          "relativeTimeRange": {
            "from": 600,
            "to": 0
          },
          "datasourceUid": "XXXXXXXXX-XXXXXXXXX-XXXXXXXXXX",
          "model": {
            "expr": "up",
            "hide": false,
            "intervalMs": 1000,
            "maxDataPoints": 43200,
            "refId": "A"
          }
        }
      ]
    }
  ]
}
' http://0.0.0.0:3000/api/v1/provisioning/folder/$FOLDER_UID/rule-groups/hello
```

### Is the bug inside a dashboard panel?

this issue isn't related to dashboard panels

### Environment (with versions)?

Grafana: 11.2
OS: docker
Browser: curl

### Grafana platform?

Docker

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by moustafab**
When modifying rule groups the `uid` can be specified but only if the rule already existed in the DB. If the rule is new the update would be rejected.

This updates the RuleGroup provisioning apis to allow specifying the `uid` when creating/updating rule groups. 

Additionally, the RuleGroupIdx was not being updated when rules were reordered in the group.

Context: https://github.com/grafana/terraform-provider-grafana/pull/1971#issuecomment-2599223897
Relates to: https://github.com/grafana/terraform-provider-grafana/issues/1928

Fixes: #98283

### CODE REVIEW

File: pkg/tests/api/alerting/api_ruler_test.go [hunk 1]
```diff
@@ -3201,79 +3201,6 @@ func TestIntegrationAlertRuleCRUD(t *testing.T) {
 		assert.JSONEq(t, expectedGetNamespaceResponseBody, body)
 	}
 
-	// try to update by pass an invalid UID
-	{
-		interval, err := model.ParseDuration("30s")
```
Comment (JacobsonMT) [inline pkg/tests/api/alerting/api_ruler_test.go:3206]: Instead of removing this test, let's update it to show what is expected.

File: pkg/services/ngalert/store/deltas_test.go [hunk 2]
```diff
@@ -240,14 +240,14 @@ func TestCalculateChanges(t *testing.T) {
 		require.Len(t, changes.AffectedGroups[sourceGroupKey], len(inDatabase))
 	})
 
-	t.Run("should fail when submitted rule has UID that does not exist in db", func(t *testing.T) {
```
Comment (JacobsonMT) [inline pkg/services/ngalert/store/deltas_test.go:243]: Let's add some tests here covering the new expected behaviour of `CalculateChanges`

File: pkg/tests/api/alerting/api_ruler_test.go [hunk 3]
```diff
@@ -3201,79 +3201,6 @@ func TestIntegrationAlertRuleCRUD(t *testing.T) {
...
-		require.NoError(t, err)
-
-		assert.Equal(t, resp.StatusCode, 202)
-
-		body, m := rulesNamespaceWithoutVariableValues(t, b)
-		returnedUIDs, ok := m["default,arulegroup"]
-		assert.True(t, ok)
-		assert.Equal(t, 2, len(returnedUIDs))
-		assert.JSONEq(t, expectedGetNamespaceResponseBody, body)
-	}
```
Comment (yuri-tceretian) [inline pkg/tests/api/alerting/api_ruler_test.go:3275]: I think this test could be rewritten to assert creation of a rule with this UID.

**Review by JacobsonMT — CHANGES_REQUESTED** [review]
Looking good so far, I've tested the following risk cases and they appear to be working as expected:

- Swapping rule positions.
- Insert rules in middle of group.
- Delete rules in middle of group.

One blocker is that validation is missing on user-defined UIDs, probably best done at the store level to be sure.

Regression test coverage could be improved as well.

File: pkg/services/ngalert/provisioning/alert_rules.go [hunk 4]
```diff
@@ -368,6 +368,16 @@ func (service *AlertRuleService) ReplaceRuleGroup(ctx context.Context, user iden
 		return err
 	}
 
+	for _, rule := range group.Rules {
```
Comment (JacobsonMT) [inline pkg/services/ngalert/provisioning/alert_rules.go:371]: NIT: Validating early has some performance benefits, but I wonder if we shouldn't just call `ValidateUID` during `DBstore.InsertAlertRules(...)` in the alternative to generating the UID. Central and guaranteed to prevent inserting invalid UIDs regardless of the path taken to insertion.

**Review by JacobsonMT — APPROVED** [review]
LGTM :rocket: Great work, couple of optional nits but will approve as-is and leave it to you whether you want to address them or not.
