### PR TITLE
OAuth: Make generic teams URL and JMES path configurable

### LINKED ISSUE #17390: 'team_ids' not working with Bitbucket
**What happened**: Getting the error `"User not a member of one of the required teams"` when providing a value to `team_ids` in the `grafana.ini` in the `auth.generic_oauth` section.

**What you expected to happen**: Be able to sign in.

**How to reproduce it (as minimally and precisely as possible)**: Just configure the global OAuth config in Grafana using the documentation

**Anything else we need to know?**: Bitbucket is not returning the list of teams and Grafana's code is expecting an `int`

**Environment**:
- Grafana version: 6.2.1
- Data source type & version: N/A
- OS Grafana is installed on: Official Docker Hub image
- User OS & Browser: macOS & Chrome
- Grafana plugins: None
- Others:

### PR DESCRIPTION
**Pull request by djairhogeuens**
**What this PR does / why we need it**:
This PR makes the teams URL and the JMES path that is used for getting the correct attribute values in the generic OAuth login provider configurable. This is needed because currently, this functionality is not working for Bitbucket OAuth because the URL and JSON structure is not compliant with the Bitbucket API.

**Which issue(s) this PR fixes**:
Fixes #17390

**Special notes for your reviewer**:
The change as I have it implemented here is breaking on configuration level (for other OAuth providers for which the current teams setup does work). I suppose we want to make this backwards compatible but I'm not sure on what the best approach would be. Maybe we can default the teams URL to the API URL and the JMES path for the team id to "id"? Feel free to make suggestions.

### CODE REVIEW

**Review by dsotirakis — CHANGES_REQUESTED** [review]
Will need some more specific entries on [generic-oauth.md](https://github.com/grafana/grafana/blob/main/docs/sources/auth/generic-oauth.md), on what each new introduced config var does :) Looks good otherwise.

**Comment by achatterjee-grafana** [comment]
> Will need some more specific entries on [generic-oauth.md](https://github.com/grafana/grafana/blob/main/docs/sources/auth/generic-oauth.md), on what each new introduced config var does :) Looks good otherwise.

Agree

**Comment by djairhogeuens** [comment]
> Will need some more specific entries on [generic-oauth.md](https://github.com/grafana/grafana/blob/main/docs/sources/auth/generic-oauth.md), on what each new introduced config var does :) Looks good otherwise.

I extended the docs. No comments on the fact that this change is breaking on configuration level (see my "special note for reviewer" at the top)?

File: pkg/login/social/generic_oauth.go [hunk 1]
```diff
@@ -412,28 +414,21 @@ func (s *SocialGenericOAuth) FetchPrivateEmail(client *http.Client) (string, err
...
 }
 
-func (s *SocialGenericOAuth) FetchTeamMemberships(client *http.Client) ([]int, bool) {
-	type Record struct {
-		Id int `json:"id"`
-	}
-
-	response, err := s.httpGet(client, fmt.Sprintf(s.apiUrl+"/teams"))
+func (s *SocialGenericOAuth) FetchTeamMemberships(client *http.Client) ([]string, bool) {
+	response, err := s.httpGet(client, fmt.Sprintf(s.teamsUrl))
```
Comment (dsotirakis) [inline pkg/login/social/generic_oauth.go:418]: Maybe we can add a check here that checks if the `teamsUrl` is set, otherwise we'll continue using `response, err := s.httpGet(client, fmt.Sprintf(s.apiUrl+"/teams"))`?

File: pkg/login/social/generic_oauth.go [hunk 2]
```diff
@@ -412,28 +414,21 @@ func (s *SocialGenericOAuth) FetchPrivateEmail(client *http.Client) (string, err
...
-		s.log.Error("Error decoding team memberships response", "raw_json", string(response.Body), "error", err)
-		return nil, false
+	if s.teamIdAttributePath == "" {
+		return []string{}, true
 	}
 
-	var ids = make([]int, len(records))
-	for i, record := range records {
-		ids[i] = record.Id
+	ids, err := s.searchJSONForStringArrayAttr(s.teamIdAttributePath, response.Body)
```
Comment (dsotirakis) [inline pkg/login/social/generic_oauth.go:428]: And then do something similar here.

**Review by dsotirakis — COMMENTED** [review]
@djairhogeuens, I'd say that 8.1 would be a good candidate for breaking changes, but this may affect lots of users, so what I'd suggest is to have a look into the comments, and then maybe for cases that your new config vars are not set, we can have a `log.Warn([Deprecated])`, or sth similar that says that new config vars now exist.

File: pkg/login/social/generic_oauth.go (hunk 1 above)
Comment (djairhogeuens) [reply pkg/login/social/generic_oauth.go]: Done

**Comment by djairhogeuens** [comment]
@dsotirakis I saw that the 8.1 release has passed by in the meanwhile, can you update me on the plan for this PR please?

**Comment by osg-grafana** [comment]
@pkolyvas could give more insight into timing of breaking changes.

**Comment by dsotirakis** [comment]
Hello @djairhogeuens, major releases (vX.X.0) are the main candidates for breaking changes. Unfortunately I was off on vacation and needed to have another look before we merge. I will make sure to communicate with my team and let you know which version (before the next major) could be appropriate for your changes to take effect. Thanks for following up!

**Comment by djairhogeuens** [comment]
@dsotirakis note that I processed your suggestions and that the change is therefore not breaking anymore. The actual breaking change (removing the deprecated stuff) can be done in a next major release.

**Comment by djairhogeuens** [comment]
@dsotirakis any update?

**Comment by dsotirakis** [comment]
@djairhogeuens Sorry for the late response, looks good to me! Can try that now and introduce the breaking change on `8.2`. @marefr agree?

**Review by dsotirakis — APPROVED** [review]

**Comment by djairhogeuens** [comment]
@dsotirakis @pkolyvas @marefr 

**gentle reminder**

**Comment by pkolyvas** [comment]
Looking at it now - now sure how I missed it for so long but I have concerns about any breaking change to Oauth in a minor release. Will sync with the team to understand the impact. Again, appologies for the delay.

**Review by kminehart — CHANGES_REQUESTED** [review]
I'm hoping to look at this one by the end of the day today. From what i can tell the change makes sense I just want to make sure :D

In the meantime, here are some small changes that I'd like to request. More will follow when I've had a chance to look a little closer. Have a doctor appointment within the hour so I'll certainly take a look after that.

**Comment by kminehart** [comment]
@djairhogeuens Upon looking more closely at this, I do not think that the logic is consistent with other "attribute_path" config items in grafana.ini.

Here's an example:

This is an example token I had generated from my local instance of github.com/ory/hydra. Something very similar is going to be given to Grafana when it is used as a generic oauth provider:

```json
{
	"active": true,
	"aud": [],
	"client_id": "grafana-code-client",
	"exp": 1630537218,
	"iat": 1630533617,
	"iss": "http://localhost:4444/",
	"nbf": 1630533617,
	"scope": "user:email",
	"sub": "foo@bar.com",
	"token_type": "Bearer",
	"token_use": "access_token"
}
```


And assume I have this setting in `grafana.ini`:

```
email_attribute_path = sub
```

This means that, before any HTTP requests are made, the `email_attribute_path` will be attempted to find the user's email address, using the `sub` key in the object.

The code that I'm reading here doesn't seem to follow that behavior for `teams`. It looks like it sort of follows this logic:

*  If teams_url is not set (true for current installs of Grafana):
    * warn the user that they should be using "teams_urL" 
    * get team ID from apiUrl+"/teams"
    * return team ID from response
* If teams_url is set:
    * fetch data from teams_url
    * use attribute path to get key from response
    * if attribute path is not set, return an empty list.
    * return team ID that matches attribute path (if set). 

Is that accurate?

To follow the behavior of some of our other attribute paths, it should attempt to retrieve the team ID from the JWT claims using the attribute path first before attempting to fetch data from the teams_url (or the api_url + "/teams" path).

**Comment by djairhogeuens** [comment]
@kminehart you're observation is correct. I strongly doubt that the teams will normally be included in the JWT claims or the /userinfo response but it's always a possibility though. I'll make the changes you suggested (first checking this before continuing the fetch from the configured teamsUrl). Since you're located in the US and I'm in Europe, you'll probably see this change done once you wake up ;)

File: pkg/login/social/generic_oauth.go [hunk 3]
```diff
@@ -412,28 +415,52 @@ func (s *SocialGenericOAuth) FetchPrivateEmail(client *http.Client) (string, err
 	return email, nil
 }
 
-func (s *SocialGenericOAuth) FetchTeamMemberships(client *http.Client) ([]int, bool) {
-	type Record struct {
-		Id int `json:"id"`
-	}
+func (s *SocialGenericOAuth) FetchTeamMemberships(client *http.Client) ([]string, bool) {
```
[the remark this answers is not in the document]
Comment (djairhogeuens) [reply pkg/login/social/generic_oauth.go:418]: Splitting it up = fine. Could you give an example of the comment you'd like to see added? Not sure what you're looking for.

**Comment by kminehart** [comment]
Probably true but the first thing I tried when I cloned this was adding `teams` to my JWT claims :joy:

File: pkg/login/social/generic_oauth.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (kminehart) [reply pkg/login/social/generic_oauth.go:418]:
```
// FetchTeamMemberships will attempt to get the team's integer ID from the JWT claims using the 'teams_attribute_path' setting.
// If the attribute path does not find anything, then the same attribute path is used to attempt to retrieve the team ID from the OIDC '/userinfo' endpoint.
```

Something like that. Feel free to correct the information if it's not accurate.

File: pkg/login/social/generic_oauth.go [hunk 4]
```diff
@@ -412,28 +415,52 @@ func (s *SocialGenericOAuth) FetchPrivateEmail(client *http.Client) (string, err
...
-	var records []Record
+		type Record struct {
+			Id int `json:"id"`
+		}
 
-	err = json.Unmarshal(response.Body, &records)
-	if err != nil {
-		s.log.Error("Error decoding team memberships response", "raw_json", string(response.Body), "error", err)
-		return nil, false
+		response, err = s.httpGet(client, fmt.Sprintf(s.apiUrl+"/teams"))
```
[the remark this answers is not in the document]
Comment (djairhogeuens) [reply pkg/login/social/generic_oauth.go:430]: This won't be possible (see: https://stackoverflow.com/questions/34668012/combine-url-paths-with-path-join/34668130)

[the remark this answers is not in the document]
Comment (kminehart) [reply pkg/login/social/generic_oauth.go:430]: Fair enough.

I was trying to find a decent middleground because string concatenation on a URL path is shaky at best, but I didn't want you to have to do a bunch of refactoring to get this to be a url.URL.

Good callout, it's totally fine to leave it as-is and we'll have to refactor this to use a url.URL in the future.

**Comment by kminehart** [comment]
Thanks for the contributions, by the way!

I'll take a look at the new changes today.

File: pkg/login/social/generic_oauth.go [hunk 5]
```diff
@@ -412,33 +434,82 @@ func (s *SocialGenericOAuth) FetchPrivateEmail(client *http.Client) (string, err
...
+	}
+
+	ids, err = s.searchJSONForStringArrayAttr(s.teamIdAttributePath, response.Body)
+
+	if err != nil {
+		return nil, nil
+	}
 
-	return ids, true
+	return ids, nil
```
Comment (kminehart) [inline pkg/login/social/generic_oauth.go:512]: Could this just be:

```go
return s.searchJSONForStringArrayAttr(s.teamIdAttributePath, response.Body)
```
?

It's a bit of a smell to receive an error and return `nil, nil`. If we need to do something specific if `s.searchJSONForStringArrayAttr` returns an error, we can create a new error in this file and use 


```go
// at the top of the file...
var AttributeError = errors.New("failed to find json attribute")

fmt.Errorf("%s: %w", err.Error(), AttributeError)

// Check for attribute error
if err := fetchTeamMembershipsFromTeamsUrl(...); err != nil {
    if errors.Is(err, AttributeError) {
        // error is an AttributeError
    }
}
```

File: pkg/login/social/social.go [hunk 6]
```diff
@@ -206,6 +212,7 @@ type BasicUserInfo struct {
 	Company string
 	Role    string
 	Groups  []string
+	Teams   []string
```
Comment (kminehart) [inline pkg/login/social/social.go:215]: Should this be

```go
Teams []int
```

since that's what is expected in the JSON?

**Review by kminehart — CHANGES_REQUESTED** [review]
Couple questions / requests. Getting there though!

File: pkg/login/social/social.go (hunk 6 above)
Comment (djairhogeuens) [reply pkg/login/social/social.go:215]: No, an array of strings is expected. Not sure where you get the int from. It used to be ints but that is insufficiently generic.

File: pkg/login/social/generic_oauth.go [hunk 7]
```diff
@@ -160,6 +166,14 @@ func (s *SocialGenericOAuth) UserInfo(client *http.Client, token *oauth2.Token)
 			s.log.Debug("Setting user info groups from extracted groups")
 			userInfo.Groups = groups
 		}
+
+		teams, err := s.extractTeams(data)
+		if err != nil {
+			s.log.Error("Failed to extract teams", "error", err)
+		} else if len(teams) > 0 {
+			s.log.Debug("Setting user info teams from extracted teams")
+			userInfo.Teams = teams
```
Comment (marefr) [inline pkg/login/social/generic_oauth.go:175]: Suggested moving this to a separate PR in another comment, but to me it seems like you can use a variable for teams rather than putting it into `BasicUserInfo`.

File: pkg/login/social/generic_oauth.go [hunk 8]
```diff
@@ -412,33 +434,75 @@ func (s *SocialGenericOAuth) FetchPrivateEmail(client *http.Client) (string, err
...
+
+	if err == nil {
+		s.log.Debug("Received team memberships", "ids", ids)
+	}
+
+	return ids, err
+}
+
+func (s *SocialGenericOAuth) fetchTeamMembershipsFromDeprecatedTeamsUrl(client *http.Client) ([]string, error) {
+	s.log.Warn("[Deprecated] Switch to the use of the teams_url and team_id_attribute_path configuration options for filtering on team membership")
```
Comment (marefr) [inline pkg/login/social/generic_oauth.go:459]: I don't think we should treat this as deprecated because basically every configured Generic OAuth provider would get this notice logged. I think we should still provide the same experience as before to provide a good backward compatibility story when teams_url is not configured and basically fallback to the old behavior.

File: pkg/login/social/generic_oauth.go [hunk 9]
```diff
@@ -412,33 +434,75 @@ func (s *SocialGenericOAuth) FetchPrivateEmail(client *http.Client) (string, err
...
+// FetchTeamMemberships will attempt to get the user's team string IDs from the JWT claims using the 'team_id_attribute_path' setting.
+// If the attribute path does not find anything in the JWT claims, then the same attribute path is used to attempt to retrieve the team IDs from the OIDC '/userinfo' endpoint.
+// If the attribute path still does not find anything in the '/userinfo' response, then the same attribute path is used to attempt to retrieve the team IDs from the 'teams_url'
+// If team IDs are found, they are returned. Otherwise, an error is returned.
+func (s *SocialGenericOAuth) FetchTeamMemberships(client *http.Client) ([]string, error) {
+	var err error
+	var ids []string
+
+	if s.teamsUrl == "" {
+		ids, err = s.fetchTeamMembershipsFromDeprecatedTeamsUrl(client)
```
Comment (marefr) [inline pkg/login/social/generic_oauth.go:446]: It adds some complexity having two branches for fetching team memberships. Have you considered just fallback the `teamsUrl` to the behavior before these changes and setting the `teamIdAttributePath` to a default value and then only use the `fetchTeamMembershipsFromTeamsUrl`? 

I'm not sure it would work, but I tested the following on jmespath.org:
```json
[
 { "id": 1 },
 { "id": 2 }
]
```
The expression `[*].to_string(id)` produces the following result which seems like it can be used with `fetchTeamMembershipsFromTeamsUrl`:
```json
[
  "1",
  "2"
]
```

This would allow us to reuse the same code for extracting team ids and it would be completely backward compatible for everyone. WDYT?

**Review by marefr — CHANGES_REQUESTED** [review]
Looks good in general and something we definitely could accept/merge. However, I think some of the changes should be extracted to a separate PR, see comment. I've also suggested a possible way to simplify the code with backward compatibility in mind. Let us  know what you think.

**Comment by djairhogeuens** [comment]
@marefr I agree with you on separating the changes but I actually only did these because @kminehart requested them. So for me it's a bit hard to decide what to do now... Can you guys figure this out please and let me know what you've decided?

Regarding the fallback to the old flow instead of deprecating it, I understand why you're suggesting that. Although, I think that the old setup is very limited and hardly usable by anyone instead of very specific providers. So that's why I favored deprecating this at once. If you really insist on removing the deprecation warning, I'll do it so let me know in that case.

Regarding the refactoring of the logic, I'll look into it tonight.

**Comment by marefr** [comment]
@djairhogeuens sorry for that. Me and @kminehart will sync up on this and let you know shortly.

File: pkg/login/social/generic_oauth.go [hunk 10]
```diff
@@ -29,21 +31,25 @@ type SocialGenericOAuth struct {
...
 
-	teamMemberships, ok := s.FetchTeamMemberships(client)
-	if !ok {
-		return false
+	if teamMemberships == nil {
+		var err error
+		teamMemberships, err = s.FetchTeamMemberships(client)
+		if err != nil {
+			return false
+		}
```
Comment (kminehart) [inline pkg/login/social/generic_oauth.go:52]:
```suggestion
```

**Review by kminehart — CHANGES_REQUESTED** [review]
Hi @djairhogeuens

@marefr and I discussed this PR this morning.

We've agreed that we should leave the token checking out of this PR as it could have some unintended consequences. That was my mistake, I was looking at another PR recently that changed up some of that and I must have got some wires crossed. I've added the suggestion so you can just click to remove it. And of course make sure to update the documentation. Again, my apologies for the unclear back and forth.

The only other thing we'd like to see is the removal of the deprecation warning, and maybe a comment in it's place that just says, `fall back to the old behavior of assuming the teams URL is on '/teams'`. We don't think we'll be comfortable removing the check on `/teams` any time soon, even though like you said it's probably not being used.

Once those 3 changes are made we will be happy to merge this in and hopefully get it into the 8.1.3 release.

File: pkg/login/social/generic_oauth.go (hunk 9 above)
Comment (kminehart) [reply pkg/login/social/generic_oauth.go:446]: @marefr discussed this and we are comfortable with the current logic and making it clear that one path is the "old" path.

File: pkg/login/social/generic_oauth.go (hunk 10 above)
Comment (kminehart) [reply pkg/login/social/generic_oauth.go]: :upside_down_face: i forgot to include the rest of that if statement.

**Comment by djairhogeuens** [comment]
@kminehart @marefr Done :)

**Review by kminehart — APPROVED** [review]
Looks good to me. As soon as the tests pass I'll get this merged in.

**Review by marefr — APPROVED** [review]
LGTM, but added two minor suggestions. Milestone/release will probably be v8.2.0 since this is a new feature/enhancement.

**Comment by djairhogeuens** [comment]
@marefr could you give me a little bit more info on how the releases are created? I always assumed that everything that's merged into master gets into the next release so in this case that would be 8.1.4. Or are you cherry-picking commits into a separate release branch? Or how should I see this?
