### PR TITLE
DataSourceProxy: Handle URL parsing error

### LINKED ISSUE #23723: Panic when save and test an data source
**What happened**:
An error throwed when i make `save & test` for create data source.

The error :
- (Loki) `Loki: Internal Server Error. 500. Internal Server Error - Check the Grafana server logs for the detailed error message.`
- (Prometheus) `HTTP Error Internal Server Error`

The server log :
```
runtime error: invalid memory address or nil pointer dereference
  /usr/local/go/src/runtime/panic.go:199 (0x44c7eb)
  /usr/local/go/src/runtime/signal_unix.go:394 (0x44c628)
  /root/project/pkg/api/pluginproxy/ds_proxy.go:215 (0xfcce7d)
  /root/project/pkg/api/pluginproxy/ds_proxy.go:94 (0xfcbe12)
  /root/project/pkg/api/dataproxy.go:36 (0x14485c8)
  /usr/local/go/src/reflect/value.go:460 (0x497b65)
  /usr/local/go/src/reflect/value.go:321 (0x497323)
  /root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x9743b9)
  /root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x973d69)
  /root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:121 (0x975358)
  /root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:112 (0x13d89d5)
  /root/project/pkg/middleware/request_tracing.go:25 (0x13d89c8)
  /usr/local/go/src/reflect/value.go:460 (0x497b65)
  /usr/local/go/src/reflect/value.go:321 (0x497323)
  /root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x9743b9)
  /root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x973d69)
  /root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:121 (0x975358)
  /root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:112 (0x13d81a9)
  /root/project/pkg/middleware/request_metrics.go:36 (0x13d8194)
  /usr/local/go/src/reflect/value.go:460 (0x497b65)
  /usr/local/go/src/reflect/value.go:321 (0x497323)
  /root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x9743b9)
  /root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x973d69)
  /root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:121 (0x975358)
  /root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:112 (0x13d805f)
  /root/project/pkg/middleware/recovery.go:160 (0x13d804d)
  /root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:79 (0x975200)
  /root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:157 (0x9740c9)
  /root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:135 (0x973e58)
  /root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:121 (0x975358)
  /root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:112 (0x13d53cb)
  /root/project/pkg/middleware/logger.go:34 (0x13d53b6)
  /usr/local/go/src/reflect/value.go:460 (0x497b65)
  /usr/local/go/src/reflect/value.go:321 (0x497323)
  /root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x9743b9)
  /root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x973d69)
  /root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:121 (0x975358)
  /root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/router.go:187 (0x9864b6)
  /root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/router.go:303 (0x980d85)
  /root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/macaron.go:220 (0x97a24a)
  /usr/local/go/src/net/http/server.go:2802 (0x706d53)
  /usr/local/go/src/net/http/server.go:1890 (0x7026f4)
  /usr/local/go/src/runtime/asm_amd64.s:1357 (0x466f40)
```

**What you expected to happen**:
Save and test without error

**How to reproduce it (as minimally and precisely as possible)**:
1) Login to grafana
2) go to Configuration -> Data Sources
3) Click on `Add data source` and select `Loki` or `Prometheus`
4) Fill the data (in my case, the url is : `analytics_loki:3100`)

**Anything else we need to know?**:
No

**Environment**:
- Grafana version:   v6.7.2 (423a25fc32)
- Data source type & version: Loki latest (k14-45f424b), Prometheus latest (v2.17.2)
- OS Grafana is installed on: Linux (official docker image `grafana/grafana:latest`)
- User OS & Browser: Windows 10 with Firefox 75.0
- Grafana plugins: `grafana-piechart-panel` and `vonage-status-panel`
- Others:

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Handle error when parsing a URL parameter in DataSourceProxy.

Fixes #23723.

### CODE REVIEW

**Review by bergquist — APPROVED** [review]
Oh great! LGTM

I know you made lots of improvements for unhandled errors. Did we add linting for that?

**Comment by aknuds1** [comment]
> Oh great! LGTM
> 
> I know you made lots of improvements for unhandled errors. Did we add linting for that?

@bergquist Yeah, enabling linting of missing error checks was part of the work I did. However, this case is trickier since the error is explicitly ignored (`targetURL, _ := url.Parse(ds.Url)`).

I'm not sure if we can ever catch this case through linting, since there might be valid reasons to ignore an error.

**Comment by bergquist** [comment]
Ah ok. I guess we need to catch these during PR review.

**Comment by aknuds1** [comment]
I could reproduce #23723, and with this PR we get a 500 instead of panic.

**Comment by aknuds1** [comment]
I updated this PR now to respond with 400 instead of 500 if the URL is invalid.

File: pkg/api/datasources.go [hunk 1]
```diff
@@ -147,6 +155,12 @@ func AddDataSource(c *models.ReqContext, cmd models.AddDataSourceCommand) Respon
 func UpdateDataSource(c *models.ReqContext, cmd models.UpdateDataSourceCommand) Response {
 	cmd.OrgId = c.OrgId
 	cmd.Id = c.ParamsInt64(":id")
+	if cmd.Url != "" {
+		_, err := url.Parse(cmd.Url)
+		if err != nil {
+			return Error(400, "Validation error", errutil.Wrapf(err, "invalid data source URL %q", cmd.Url))
```
Comment (marefr) [inline pkg/api/datasources.go:161]: Would be nice to extract validation to function.

File: pkg/api/datasources.go [hunk 2]
```diff
@@ -126,6 +128,12 @@ func DeleteDataSourceByName(c *models.ReqContext) Response {
 
 func AddDataSource(c *models.ReqContext, cmd models.AddDataSourceCommand) Response {
 	cmd.OrgId = c.OrgId
+	if cmd.Url != "" {
+		_, err := url.Parse(cmd.Url)
+		if err != nil {
+			return Error(400, "Validation error", errutil.Wrapf(err, "invalid data source URL %q", cmd.Url))
```
Comment (marefr) [inline pkg/api/datasources.go:134]: Message in UI is not super friendly
image

Should say something along the lines "Invalid URL".

**Review by marefr — CHANGES_REQUESTED** [review]
Looks good. Some minor changes requested

File: pkg/api/datasources.go (hunk 2 above)
Comment (aknuds1) [reply pkg/api/datasources.go:134]: @marefr I think this must be fixed in the UI, because that's not the message sent from the API (I checked in the browser). Shall we fix it in another PR?

Comment (aknuds1) [reply pkg/api/datasources.go:134]: @marefr I think I see how to fix it.

File: pkg/api/datasources.go [hunk 3]
```diff
@@ -124,8 +127,24 @@ func DeleteDataSourceByName(c *models.ReqContext) Response {
 	return Success("Data source deleted")
 }
 
+func validateParams(params models.DataSourceParams) Response {
```
Comment (marefr) [inline pkg/api/datasources.go:130]: Maybe a bit overkill for now. Why not just send in string argument?

Comment (aknuds1) [reply pkg/api/datasources.go:130]: @marefr I also thought about about sending only the string, but then I figured we logically want to validate the parameters, and quite possibly more than just the URL, so we might as well prepare for it. I don't see any downside to let the validation function receive all parameters?

Comment (aknuds1) [reply pkg/api/datasources.go:130]: Thinking it over a second time though, maybe it can be better solved through a shared embedded struct instead of an interface though?

Comment (aknuds1) [reply pkg/api/datasources.go]: @marefr I discussed with @bergquist and he also thought it would be better to leave the embedded struct refactoring out of this PR, so I switched to a validation function only receiving the URL, as you suggested.

**Review by marefr — APPROVED** [review]
LGTM :+1:
