### PR TITLE
TablePanel: Fix ad-hoc variabes not working on default datasources

### LINKED ISSUE #43975: Broken inline ad-hoc filtering using Elasticsearch with Table Panels
**What happened**:
Updating existing and creating new table panels breaks the inline ad-hoc filtering functionality in Elasticsearch. After looking through the panel JSON, it seems like the datasource type and uid are not updated correctly.
I was unable to replicate this issue with datasources that were not the default.

**What you expected to happen**:
In-line filtering still works after updating the panel.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a table panel
2. Group by Terms
3. Try to filter for/our value

**Anything else we need to know?**:

Old, functioning panel:
```
      "query": "redacted",
      "refId": "A",
      "timeField": "created_at"
    }
  ],
  "datasource": {
    "type": "elasticsearch",
    "uid": "000000002"
  }
}
```

New, broken panel:
```
      "query": "redacted",
      "refId": "A",
      "timeField": "created_at",
      "datasource": {
        "type": "elasticsearch",
        "uid": "000000002"
      }
    }
  ],
  "datasource": null
```

**Environment**:
- Grafana version: 8.3.2 OSS
- Data source: Elasticsearch

### PR DESCRIPTION
**Pull request by joshhunt**
**What this PR does / why we need it**:

Fixes TablePanel so ad-hoc filters work when the panel is configured with a default datasource.

**Which issue(s) this PR fixes**:

Fixes #43975

### CODE REVIEW

File: public/app/plugins/panel/table/TablePanel.tsx [hunk 1]
```diff
@@ -68,13 +76,17 @@ export class TablePanel extends Component<Props> {
   onCellFilterAdded = (filter: FilterItem) => {
     const { key, value, operator } = filter;
     const panelModel = getDashboardSrv().getCurrent()?.getPanelById(this.props.id);
-    const datasource = panelModel?.datasource;
 
-    if (!datasource) {
+    // The datasource ref from the panel model can be null/undefined if a panel uses a default datasource
+    // so we need to resolve it to the real final datasource.
```
Comment (ashharrison90) [inline public/app/plugins/panel/table/TablePanel.tsx:81]: i think it's worth clarifying that `getInstanceSettings` will return the default datasource instance settings if the argument (in this case `panelModel?.datasource`) is undefined

**Review by ashharrison90 — APPROVED** [review]
looks great! 🚀 

added a minor suggestion for the comment just to make it clearer what's happening
