### PR TITLE
Dashboard Import: fix multiple import issues

### LINKED ISSUE #119494: Dashboards: Unable to import dashboards with libraries as classic or V1 resource
### What happened?

_See also https://community.grafana.com/t/12-4-0-cannot-import-dashboards-with-library-panels-anymore/161940_

Trying to import a dashboard that references library panels like this one: [EVCC: Today | Grafana Labs](https://grafana.com/grafana/dashboards/22028-evcc-today/)

Tried the following methods:

- Import dashboard through Grafana.com using the dashboard ID '22028'.
- Upload dashboard from file system from classic JSON exported under 12.3.1: https://github.com/ha-puzzles/evcc-grafana-dashboards/blob/main/dashboards/dashboards/EVCC_%20Today.json
- Export dashboard from a migrated 12.4.0 system, where the dashboards were imported before the upgrade to 12.4.0 and tried the import to another fresh 12.4.0 installation using either 
  - Classic JSON or 
  - V1 JSON resources.

Neither of these methods works. After import all library panels are broken:

Image

Besides the broken library panels, see the broken variable name on the top of the dashboard:

Image

The only workaround that worked was:

Export as V2 resource under 12.4.0 and import to other 12.4.0 instance - this however eliminates all library panels and I ended up with the message “The Dynamic Dashboard feature is temporarily disabled”. See [New warning about dynamic dashboards being unavailable](https://community.grafana.com/t/new-warning-about-dynamic-dashboards-being-unavailable/161936)

Image

### What did you expect to happen?

Successful import including library panels from classic JSON file as it was possible with previous Grafana versions.

### Did this work before?

Up to Grafana 12.3.2 this works without any problem. 

Downgrade to 12.3.2. and import the dashboard above and it will work.

### How do we reproduce it?

1. Create an influx data source. It does not need the correct data (which would be data from [EVCC](https://evcc.io/))
1. Import this dashboard: https://grafana.com/grafana/dashboards/22028-evcc-today/
2. See the errors on all library panels
3. Examine the list of Library panels. You see several panels starting with the name "EVCC:", which got imported as part of the dashboard.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 12.4.0
OS: Linux, ARM64 (Raspian)
Browser: Brave, Chrome

### Grafana platform?

None

### Datasource(s)?

Influx 1.8, filled through EVCC.io

### PR DESCRIPTION
**Pull request by kristinademeshchik**
**What is this feature?**

1. **Constant template variables not resolved:** `__inputs` of type constant (e.g. ${VAR_INVERTERPORTALTITLE}) were passed through as literal placeholders instead of being substituted with user-provided values. 

2. **Mixed datasource panels losing target datasources:** Panels with -- Mixed -- as the top-level datasource had their per-target datasource placeholders (e.g. ${DS_BIGQUERY}) skipped because target processing was gated behind the panel-level uid.startsWith('$') check. 

3. **Built-in datasources detected as user inputs (v2)**: extractV2Inputs did not filter built-in datasources, causing them to appear as configurable inputs during v2 import. 

Fixes: #119494

### CODE REVIEW

File: public/app/features/manage-dashboards/import/utils/inputs.ts [hunk 1]
```diff
@@ -231,6 +232,15 @@ export function extractV2Inputs(dashboard: unknown): DashboardInputs {
   }
 
   for (const [label, dsType] of Object.entries(dsTypes)) {
+    try {
```
Comment (kristinademeshchik) [inline public/app/features/manage-dashboards/import/utils/inputs.ts:235]: mimics old approach of checking built-in datasources

https://github.com/grafana/grafana/blob/main/public/app/features/manage-dashboards/import/legacy/actions.ts#L268-L270

(added try/catch)

File: public/app/features/manage-dashboards/import/utils/inputs.ts [hunk 2]
```diff
@@ -522,46 +532,67 @@ function processAnnotation(
...
-        if (userInput) {
-          return {
-            ...target,
-            datasource: {
-              ...target.datasource,
-              uid: userInput.uid,
-            },
-          };
-        }
+  const queries = panel.targets?.map((target) => {
```
Comment (kristinademeshchik) [inline public/app/features/manage-dashboards/import/utils/inputs.ts:535]: same approach but handles panel level datasource and targets separately

File: public/app/features/manage-dashboards/import/utils/inputs.ts [hunk 3]
```diff
@@ -522,46 +532,67 @@ function processAnnotation(
...
 
 function processVariable(
   variable: VariableModel,
-  inputs: { dataSources: DataSourceInput[] },
+  inputs: { dataSources: DataSourceInput[]; constants?: DashboardInput[] },
   form: ImportDashboardDTO
 ) {
   const variableType = variable.type;
+
+  if (variableType === 'constant' && 'query' in variable && typeof variable.query === 'string' && inputs.constants) {
```
Comment (kristinademeshchik) [inline public/app/features/manage-dashboards/import/utils/inputs.ts:575]: I see a potential problem with this new import approach introduced in https://github.com/grafana/grafana/pull/116482

Looking at the backend code that handled this before, it recursively walked every key/value in the entire dashboard JSON tree and performed a regex replace of ${...} placeholders on every string value, skipping  `__inputs`. This meant placeholders were resolved regardless of where they appeared 

With the new frontend approach, we're targeting specific parts of the dashboard (panel datasources, variable queries, annotations). My fix here adds constant variable processing, but there may still be placeholders in other parts of the dashboard that the frontend code doesn't reach

WDYT @ivanortegaalba

File: public/app/features/manage-dashboards/import/utils/inputs.ts [hunk 4]
```diff
@@ -262,7 +272,7 @@ function getDataSourceDescription(input: Record<string, unknown>): string {
  */
 export function applyV1Inputs(
   dashboard: Dashboard,
-  inputs: { dataSources: DataSourceInput[] },
+  inputs: { dataSources: DataSourceInput[]; constants?: DashboardInput[] },
```
Comment (ivanortegaalba) [inline public/app/features/manage-dashboards/import/utils/inputs.ts:275]: In the K8s path, `applyV1Inputs` spreads the entire dashboard ({ ...dashboard, ... }), which preserves __inputs, __elements, and __requires in the output. Then ImportOverviewV1.onSubmit passes this directly to getDashboardAPI('v1').saveDashboard(). The K8s save API doesn't strip unknown fields; these export-only keys would be persisted in the dashboard JSON. Have you noticed that? I might be wrong here but just to double check

File: public/app/features/manage-dashboards/import/utils/inputs.ts (hunk 3 above)
Comment (ivanortegaalba) [reply public/app/features/manage-dashboards/import/utils/inputs.ts:575]: After investigating how constant variables are handled during export/import, I wanted to share some context.

In the classic (non-k8s) path, `__inputs` entries are rendered in the import form: datasource pickers for DS inputs and text fields for constant variables. This allows the user to customize constant values (e.g., environment name, URL prefix) when importing a dashboard into a different Grafana instance.

**Regarding this PR:** The constant input is being parsed correctly, but we need to make sure the import overview also renders text fields for constant variables — not just datasource pickers.

**Separate issue — V2 export doesn't support constant variables as placeholders.** We've lost the ability to customize constant variable values when importing a V2-format dashboard. Similar work was done for datasources in #117212, but we missed constant variables. That said, unlike datasources (which needed the `ExportLabel` mechanism to distinguish multiple instances of the same type), constants are straightforward to detect — each `ConstantVariable` in the spec can be surfaced directly as a text input during import without any label/placeholder mechanism.

**Review by ivanortegaalba — APPROVED** [review]
Great work @kristinademeshchik ! 

Just adding as a note:

#119494 likely requires two fixes:

- Constant variable handling — addressed by this branch (v1 only)
- Library panel import during V1 K8s path — not addressed, needs separate investigation

I'd not mark the issue as resolved when merging this PR, but it already solves a lot! Great work! 💯

**Comment by ivanortegaalba** [comment]
@kristinademeshchik I opened a PR on these changes, fixing the small stuff I have found: 
https://github.com/grafana/grafana/pull/119969

I had everything mostly ready in my Cursor sessions; the changes are trivial 🙌

File: public/app/features/manage-dashboards/import/utils/inputs.ts (hunk 4 above)
Comment (kristinademeshchik) [reply public/app/features/manage-dashboards/import/utils/inputs.ts:275]: It does not happen
backend strips it out - [https://github.com/grafana/grafana/blob/main/apps/dashboard/pkg/migration/migrate.go#L119-L121](https://github.com/grafana/grafana/blob/main/apps/dashboard/pkg/migration/migrate.go#L119-L121)

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/22913850422)
- Version: 13.0.0-22913850422
