### PR TITLE
Dashboard: New Datasource picker link is keyboard accessible

### LINKED ISSUE #69109: Dashboard: New Datasource picker link not keyboard accessible
### 
# What went wrong?

https://github.com/grafana/grafana/pull/66566 introduced a new component
image with an "Open advanced data source picker" link which is not accessible via the keyboard.

### 
# How do we reproduce it?

- Open Grafana dashboard, select datasource picker dropdown, navigate through options with the up/down arrows on the keyboard. Notice that the link on the bottom is not selectable unless you could "tab" to the next link, which closes the dropdown and unmounts the component housing the link.

### 
# What Grafana version are you using?

v10.0.x

### 
### Is the bug inside a Dashboard Panel?

Nope

### Grafana Platform?

None

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

No

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by polibb**
**What is this feature?**

This should allow the user to tab their way from the input of the Datasource picker to the buttons underneath the list of available datasources in its dropdown.

**Why do we need this feature?**

Keyboard accessibility for the dropdown of the datasource picker.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/69109

**Special notes for your reviewer:**

### CODE REVIEW

File: public/app/features/datasources/components/picker/DataSourceDropdown.tsx [hunk 1]
```diff
@@ -359,3 +350,84 @@ function getStylesPickerContent(theme: GrafanaTheme2) {
     `,
   };
 }
+
+export interface FooterProps extends PickerContentProps {}
+
+function Footer({ onClose, onChange, onClickAddCSV, ...props }: FooterProps) {
```
Comment (ivanortegaalba) [inline public/app/features/datasources/components/picker/DataSourceDropdown.tsx:356]: This was extracted for simplicity. Since now we're capturing the tab navigation and bringing back the focus to the input

File: public/app/features/datasources/components/picker/DataSourceDropdown.tsx [hunk 2]
```diff
@@ -119,6 +125,17 @@ export function DataSourceDropdown(props: DataSourceDropdownProps) {
     onChange(grafanaDS, [defaultFileUploadQuery]);
   };
 
+  function onKeyDownInput(keyEvent: React.KeyboardEvent<HTMLInputElement>) {
+    if (keyEvent.key === 'Tab' && !keyEvent.shiftKey && isOpen) {
```
Comment (polibb) [inline public/app/features/datasources/components/picker/DataSourceDropdown.tsx:129]: good attention to detail!

File: public/app/features/datasources/components/picker/DataSourceDropdown.tsx [hunk 3]
```diff
@@ -136,7 +153,8 @@ export function DataSourceDropdown(props: DataSourceDropdownProps) {
   const onClose = useCallback(() => {
     setFilterTerm('');
     setOpen(false);
-  }, [setOpen]);
+    markerElement?.focus();
```
Comment (polibb) [inline public/app/features/datasources/components/picker/DataSourceDropdown.tsx:156]: that's a better place than in Escape! Because now we are never concerned with the problem of the content living inside a Portal!!

File: public/app/features/datasources/components/picker/DataSourceDropdown.tsx [hunk 4]
```diff
@@ -359,3 +350,84 @@ function getStylesPickerContent(theme: GrafanaTheme2) {
...
   };
 }
+
+export interface FooterProps extends PickerContentProps {}
+
+function Footer({ onClose, onChange, onClickAddCSV, ...props }: FooterProps) {
+  const styles = useStyles2(getStylesFooter);
+  const isUploadFileEnabled = props.uploadFile && config.featureToggles.editPanelCSVDragAndDrop;
+
+  const onKeyDownLastButton = (e: React.KeyboardEvent<HTMLButtonElement>) => {
```
Comment (polibb) [inline public/app/features/datasources/components/picker/DataSourceDropdown.tsx:360]: Even though we tried to avoid that handling of "onkeydown" manually for each button, this is a clean way to do it since we have to right now.

**Review by ivanortegaalba — APPROVED** [review]
