### PR TITLE
Cascader: Fix icon not showing

### LINKED ISSUE #97158: Frontend: ButtonCascader: Expandable entries don't show any arrow icon
### What happened?

If you use the ButtonCascader with several levels, an angle-right icon should be displayed for an element with children, which serves as an indicator for child elements.

This icon is currently not displayed because the path to the svg is incorrectly specified in the CSS and therefore cannot be loaded.

- Current: `../img/icons/unicons/angle-right.svg`
- Working: `public/img/icons/unicons/angle-right.svg`

### What did you expect to happen?

The icon should be displayed correctly.

### Did this work before?

Yes

### How do we reproduce it?

Reproducible at: https://developers.grafana.com/ui/latest/index.html?path=/docs/forms-cascader-buttoncascader--docs

Image
Image

**With fixed path:**
Image

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 11.1.x, 11.2.x, 11.3.x
OS: Windows, Mac
Browser: Chrome, Edge, Firefox, Safari

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- updates the icon path to point to the correct place

|  | before | after |
| --- | --- | --- |
| grafana | image | image |
| cascader story | image | image |
| buttoncascader story | image | image |

**Why do we need this feature?**

- so the icon shows up!

**Who is this feature for?**

- everyone

**Which issue(s) does this PR fix?**:

Fixes #97158 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/Icon/utils.ts [hunk 1]
```diff
@@ -60,3 +60,9 @@ export function getIconRoot(): string {
 
   return iconRoot;
 }
+
+export function getIconPath(name: IconName, type: IconType = 'default'): string {
```
Comment (joshhunt) [inline packages/grafana-ui/src/components/Icon/utils.ts:64]: nice

**Review by joshhunt — APPROVED** [review]
Eggcellent 🥇 

Thanks for tightening the path up to use the CDN!
