### PR TITLE
API: Support folder UID in dashboards API

### LINKED ISSUE #12491: [Feat] Expose folder uid in dashboard meta for GET dashboard
In a attempt to move copy dashboards from a development environment to a production environment we have come up with our own script to export / import via the HTTP endpoints.

There seems to be a issue with getting the Dashboards into the right folders, if the folder exists (and is the same id) it will work fine. But that is not the case if the folder does not exist, even if you specify a id & uid that is not already taken.

How to reproduce:

1. Create folder
2. Create Dashboard (Place it in the previous folder).
3. Export dashboard.
4. Export folder through HTTP endpoint
5. Remove folder.
6. Using HTTP endpoint, create new folder with previous export.
7. (Folder id has now changed, even when stating no override & giving a id / uid).
8. Try to import dashboard with it in folder, the dashboard will be placed in 'general'

This makes it difficult to make sure that dashboards being imported go in the correct folder. There is a uid field on the folder, why not link it like that?

### LINKED ISSUE #26678: I would like to be able to POST a new dashboard while providing the folderUid (seems only the folderId is present in the API)
Hello everyone !

**What would you like to be added**:
Possibility to POST a new dashboard on the API using folderUid.
Seems like only folderId is available right now.

**Why is this needed**:
In infrastructure as code, I keep trace of all my dashboards as json inside the project. I want to hardcode the folderUid name in the json, but I don't know for sure what will be the folders ID. Calling the GET method on folders to get their ID before posting, and replace the folderId in the JSON file at runtime is just painful.

Thanks ! 
If there is already a way to make this happen, i'm all ears !

### PR DESCRIPTION
**Pull request by zserge**
Closes #12491 
Closes #26678 

Ref #32853

### CODE REVIEW

File: pkg/api/dashboard.go [hunk 1]
```diff
@@ -295,8 +296,16 @@ func (hs *HTTPServer) PostDashboard(c *models.ReqContext, cmd models.SaveDashboa
 			return response.Error(500, "Error while applying default value to the dashboard json", err)
 		}
 	}
+	if cmd.FolderUid != "" {
+		folders := dashboards.NewFolderService(c.OrgId, c.SignedInUser, hs.SQLStore)
+		folder, err := folders.GetFolderByUID(cmd.FolderUid)
+		if err != nil {
+			return response.Error(500, "Error while checking folder ID", err)
```
Comment (marefr) [inline pkg/api/dashboard.go:303]: Should handle `models.ErrFolderNotFound` and return 400 error

File: pkg/api/dashboard.go [hunk 2]
```diff
@@ -295,8 +296,16 @@ func (hs *HTTPServer) PostDashboard(c *models.ReqContext, cmd models.SaveDashboa
 			return response.Error(500, "Error while applying default value to the dashboard json", err)
 		}
 	}
+	if cmd.FolderUid != "" {
```
Comment (marefr) [inline pkg/api/dashboard.go:299]: Do we need to validate if both folderId and folderUid is set? Or is the idea that if folderUid is set it will override folderId?

**Review by marefr — COMMENTED** [review]
Just a few minor comments. Seems like you're on the right track

File: pkg/api/dashboard.go (hunk 2 above)
Comment (zserge) [reply pkg/api/dashboard.go:299]: FolderUID and FolderID both present - is a confusing combination. We could either a) treat it as an error or b) make one of the values override the other. In case of b) I would prefer UID to override ID, assuming that IDs are to be gone in the future.

Comment (marefr) [reply pkg/api/dashboard.go:302]: I agree with your suggestion of b)

File: pkg/api/dashboard.go [hunk 3]
```diff
@@ -138,8 +138,12 @@ func (hs *HTTPServer) GetDashboard(c *models.ReqContext) response.Response {
 	if dash.FolderId > 0 {
 		query := models.GetDashboardQuery{Id: dash.FolderId, OrgId: c.OrgId}
 		if err := bus.Dispatch(&query); err != nil {
+			if errors.Is(err, models.ErrFolderNotFound) {
+				return response.Error(400, models.ErrFolderNotFound.Error(), err)
```
Comment (marefr) [inline pkg/api/dashboard.go:142]:
```suggestion
				return response.Error(404, "Folder not found", err)
```

**Comment by marefr** [comment]
Given Ida's commit, can this PR description close/fix Ida's issue? Or is that the same as already referenced in the PR description?

**Review by dsotirakis — APPROVED** [review]
LGTM! 🚀

**Review by marefr — CHANGES_REQUESTED** [review]
Looks great :+1:  Just some documentation updates left: https://github.com/grafana/grafana/blob/main/docs/sources/http_api/dashboard.md

File: pkg/api/dashboard.go [hunk 4]
```diff
@@ -138,8 +138,12 @@ func (hs *HTTPServer) GetDashboard(c *models.ReqContext) response.Response {
 	if dash.FolderId > 0 {
 		query := models.GetDashboardQuery{Id: dash.FolderId, OrgId: c.OrgId}
 		if err := bus.Dispatch(&query); err != nil {
+			if errors.Is(err, models.ErrFolderNotFound) {
+				return response.Error(404, "Folder not found", err)
```
Comment (zserge) [inline pkg/api/dashboard.go:142]: The statuses will be changed to constants in a separate automatic PR

File: docs/sources/http_api/dashboard.md [hunk 5]
```diff
@@ -55,6 +56,7 @@ JSON Body schema:
 - **dashboard.id** – id = null to create a new dashboard.
 - **dashboard.uid** – Optional unique identifier when creating a dashboard. uid = null will generate a new uid.
 - **folderId** – The id of the folder to save the dashboard in.
+- **folderUid** – The uid of the folder to save the dashboard in.
```
Comment (marefr) [inline docs/sources/http_api/dashboard.md:59]: Does this make sense or do you have a better suggestion?

```suggestion
- **folderUid** – The uid of the folder to save the dashboard in. Overrides the `folderId`, if that's specified.
```

**Review by marefr — CHANGES_REQUESTED** [review]
Added a suggestion. Missing documentation of `folderUid` property in dashboard meta responses in the documentation, for example for Get dashboard by UID.

File: docs/sources/http_api/dashboard.md [hunk 6]
```diff
@@ -55,6 +56,7 @@ JSON Body schema:
 - **dashboard.id** – id = null to create a new dashboard.
 - **dashboard.uid** – Optional unique identifier when creating a dashboard. uid = null will generate a new uid.
 - **folderId** – The id of the folder to save the dashboard in.
+- **folderUid** – The uid of the folder to save the dashboard in. Overrides the `folderId`, if that's specified.
```
Comment (achatterjee-grafana) [inline docs/sources/http_api/dashboard.md:59]:
```suggestion
- **folderUid** – The UID of the folder to save the dashboard in. Overrides the `folderId`.
```

**Review by achatterjee-grafana — CHANGES_REQUESTED** [review]
Added copy-edit change.

**Review by marefr — APPROVED** [review]
LGTM great

**Review by achatterjee-grafana — APPROVED** [review]
LGTM
