### PR TITLE
Node Graph Panel: Add options to configure units and arc colors

### LINKED ISSUE #49773: nodegraph with mysql not rendering colors on nodes
hello

**What happened**:
When using nodeGraph with mysql the arc_* values are not being properly rendered on the nodes

**What you expected to happen**:
To properly render on the nodes per size of arc_*

**How to reproduce it (as minimally and precisely as possible)**:
using mysql as data source
nodegraph as visualisation
2 queries

```
Query #1
select 1 as id, 'node1' as title, 'seattle' as subtitle, 23 mainstat, 2 secondarystat, 0.25 arc__cpu, 0.75 arc__disk  union
select 2 as id, 'node2' as title, 'renton' as subtitle,12 mainstat, 6 secondarystat, 0.15 arc__cpu, 0.85 arc__disk 

Query #2
select 'a' as id,1 source,2 target, 32 mainStat, 'mb/s' secondaryStat
```
**Anything else we need to know?**:
 The same identical data renders properly when the data source is inline csv and with the Infinity plugin

**Environment**:
- Grafana version: 8.5.2
- Data source type & version: mysql
- OS Grafana is installed on: Locally
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: nodegraph
- Others:

Thanks

### PR DESCRIPTION
**Pull request by connorlindsey**
**What this PR does / why we need it**:
It's currently impossible to configure the units and colors for the node graph panel, so this adds options to do so.

**Which issue(s) this PR fixes**:
Fixes #49773

**Special notes for your reviewer**:
How to test:
- Add a Node Graph panel to a dashboard
- Add the following queries in a MySQL datasource (or other SQL ds):
    - Ref: Nodes     
```sql
select 1 as id, 'node1' as title, 'seattle' as subtitle, 23 mainstat, 2 secondarystat, 0.25 arc__cpu, 0.75 arc__disk  union
select 2 as id, 'node2' as title, 'renton' as subtitle,12 mainstat, 6 secondarystat, 0.15 arc__cpu, 0.85 arc__disk
```

    - Ref: Edges
    
```sql
select 'a' as id,1 source,2 target, 32 mainStat, 'mb/s' secondaryStat
```
- Test the units and color options. Re-run the query/refresh the panel to view changes.

Screen Shot 2022-06-17 at 11 38 18 AM

### CODE REVIEW

File: public/app/plugins/panel/nodeGraph/module.tsx [hunk 1]
```diff
@@ -1,6 +1,42 @@
 import { PanelPlugin } from '@grafana/data';
 
 import { NodeGraphPanel } from './NodeGraphPanel';
-import { Options } from './types';
+import { ArcOptionsEditor } from './editor/ArcOptionsEditor';
+import { NodeGraphOptions } from './types';
 
-export const plugin = new PanelPlugin<Options>(NodeGraphPanel);
+export const plugin = new PanelPlugin<NodeGraphOptions>(NodeGraphPanel).setPanelOptions((builder, context) => {
```
Comment (joey-grafana) [inline public/app/plugins/panel/nodeGraph/module.tsx:7]: context not used

**Review by joey-grafana — APPROVED** [review]
LGTM 👍
