### PR TITLE
Table: Keep expanded rows persistent when data changes if it has unique ID

### LINKED ISSUE #74140: [TraceQL] Streaming results repeatedly collapse
When using the TraceQL streaming option and you click to expand results, they immediately collapse.

To reproduce:
1) Run a streaming query
2) While the query is still running click a trace id so it drops down to reveal the spans
image
3) Observe it immediately collapse
image

I believe that everytime Grafana gets a new message from Tempo and it refreshes it results it collapses all rows in the table.

### PR DESCRIPTION
**Pull request by aocenas**
Fixes: https://github.com/grafana/grafana/issues/74140

Specifically for streaming responses, collapsed/expanded state would reset on every new part of the data, which for long queries with multiple parts could be pretty disrupting.

This PR contains few distinct changes:
1. Use rowID for the expanded state of a row. This is probably the proper way to do it anyway and even if there isn't a proper row ID react-table will just use the row index as before.
2. If we have a proper unique column in the data, use it as rowID and set the expanded state to be persistent between data changes.
3. Set TraceID column in Tempo response to have unique attribute.
4. Fixes the sizing reset code in the Table to properly reset sizing for collapsed/expanded rows.
5. Adds test case in the testdata source > streaming client > traces to test this functionality.

https://github.com/grafana/grafana/assets/1014802/2a778317-1af8-47da-ac1b-64bbf125c804

**Note:** This persists the state only if also the table is kept in the render tree. So for example when doing new query in Explore the visualization still gets unmounted and mounted again and the state is lost (not sure if good thing tbh, maybe we should persist the data from the previous query until we have new data)

**TODO:** Not sure about the `unique` attribute on the DataFrame.Field config. Have to see if that makes sense or there is a better place for it.

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/types.ts [hunk 1]
```diff
@@ -67,8 +67,10 @@ export interface TableFooterCalc {
 }
 
 export interface GrafanaTableState extends TableState {
-  lastExpandedIndex?: number;
-  toggleRowExpandedCounter: number;
```
Comment (aocenas) [inline packages/grafana-ui/src/components/Table/types.ts:71]: Wasn't used anywhere.

File: packages/grafana-ui/src/components/Table/hooks.ts [hunk 2]
```diff
@@ -36,41 +36,47 @@ export function useFixScrollbarContainer(
...
-          resetIndex = Math.min(resetIndex, lowestExpandedIndex);
-        }
+    // By default, reset all rows
+    let resetIndex = 0;
+
+    // If we have unique field, extendedState.expanded keys are not row indexes but IDs so instead of trying to search
+    // for correct index we just reset the whole table.
+    if (!uniqueField) {
+      // If we don't have we reset from the last changed index.
+      if (Number.isFinite(extendedState.lastExpandedOrCollapsedIndex)) {
```
Comment (aocenas) [inline packages/grafana-ui/src/components/Table/hooks.ts:60]: This is simplified from previous version. Previously it reset always the minimal index whether it was `lastExpandedOrCollapsedIndex` or from `state.expanded`. This right now only expands from last changed index in `lastExpandedOrCollapsedIndex` down.

**Review by adrapereira — DISMISSED** [review]
Amazing change that will cleanup this annoying issue from the tables with streaming rows! 
Code looks great to me, and the addition of comments helps understand what's going on, thank you!
One small issue I see is that the `unique` config isn't easily discoverable, do you mind adding something to `Table.mdx` and/or `Table.story.tsx`?

**Comment by aocenas** [comment]
@adrapereira thanks. Yeah still waiting a bit for some feedback from relevant team about that, whether it makes sense to have it in field.custom or put somewhere else and will update afterwards.

**Review by joey-grafana — COMMENTED** [review]
Looks good, thanks for simplifying the logic!

Row alignment in dash seems to be broken.
Screenshot 2024-01-12 at 14 17 39


nit: `req.panelId` undefined
Screenshot 2024-01-12 at 14 16 12

We should also add docs for the nestedFrames but honestly not really part of this PR.

File: packages/grafana-data/src/dataframe/utils.test.ts [hunk 3]
```diff
@@ -77,3 +77,30 @@ describe('anySeriesWithTimeField', () => {
     });
   });
 });
+
+describe('addRow', () => {
```
Comment (baldm0mma) [inline packages/grafana-data/src/dataframe/utils.test.ts:81]: Yay tests!

File: packages/grafana-data/src/dataframe/utils.ts [hunk 4]
```diff
@@ -98,3 +98,28 @@ export function getRowUniqueId(dataFrame: DataFrame, rowIndex: number) {
   }
   return dataFrame.meta.uniqueRowIdFields.map((fieldIndex) => dataFrame.fields[fieldIndex].values[rowIndex]).join('-');
 }
+
+/**
```
Comment (baldm0mma) [inline packages/grafana-data/src/dataframe/utils.ts:102]: Thanks for the docs!

File: packages/grafana-data/src/dataframe/utils.ts [hunk 5]
```diff
@@ -98,3 +98,28 @@ export function getRowUniqueId(dataFrame: DataFrame, rowIndex: number) {
...
+  } else {
+    for (const field of dataFrame.fields) {
+      field.values.push(row[field.name]);
+    }
+  }
+  try {
+    dataFrame.length++;
+  } catch (e) {
+    // Unfortunate but even though DataFrame as interface defines length some implementation of DataFrame only have
+    // length getter. In that case it will throw and so we just skip and assume they define getter for length that
```
Comment (baldm0mma) [inline packages/grafana-data/src/dataframe/utils.ts:122]:
```suggestion
    // length getter. In that case it will throw and so we just skip and assume they defined a `getter` for length that
```

File: packages/grafana-ui/src/components/Table/Table.mdx [hunk 6]
```diff
@@ -13,6 +13,12 @@ This nested fields values can contain an array of one or more dataframes. Each o
 
 For each dataframe and index in the nested field, the dataframe will be rendered as one or more sub-tables below the main dataframe row at that index.
 
+### Unique rowId
+
+In some cases it makes sense to persist the state of opened/closed state of the sub-tables, for example with streaming queries where user may manipulate the state while additional data is still loading. In such cases use `dataframe.meta.uniqueRowIdFields` property to specify which fields create unique row id and table will use it to persist the state across data changes.
```
Comment (baldm0mma) [inline packages/grafana-ui/src/components/Table/Table.mdx:18]:
```suggestion
In some cases it makes sense to persist the opened/closed state of the sub-tables. For example: with streaming queries where a user may manipulate the state while additional data is still loading. In such cases use `dataframe.meta.uniqueRowIdFields` property to specify which fields create unique row id and table will use it to persist the state across data changes.
```

File: packages/grafana-ui/src/components/Table/hooks.ts [hunk 7]
```diff
@@ -36,41 +36,47 @@ export function useFixScrollbarContainer(
 }
 
 /**
-  react-table caches the height of cells so we need to reset them when expanding/collapsing rows
-   We need to take the minimum of the current expanded indexes and the previous expandedIndexes array to account
-  for collapsed rows, since they disappear from expandedIndexes but still keep their expanded height
+  react-table caches the height of cells, so we need to reset them when expanding/collapsing rows.
+  We use lastExpandedOrCollapsedIndex since collapsed rows disappear from expandedIndexes but still keep their expanded
```
Comment (baldm0mma) [inline packages/grafana-ui/src/components/Table/hooks.ts:40]:
```suggestion
  We use `lastExpandedOrCollapsedIndex` since collapsed rows disappear from `expandedIndexes` but still keep their expanded
```

File: public/app/plugins/datasource/grafana-testdata-datasource/components/StreamingClientEditor.tsx [hunk 8]
```diff
@@ -29,29 +30,41 @@ export const StreamingClientEditor = ({ onChange, query }: EditorProps) => {
     onChange({ target: { name, value: Number(value) } });
   };
 
+  const fields =
+    query?.stream?.type === 'signal'
```
Comment (baldm0mma) [inline public/app/plugins/datasource/grafana-testdata-datasource/components/StreamingClientEditor.tsx:34]: Readability of this logic might increase if it's broken out into a couple functions?

File: public/app/plugins/datasource/grafana-testdata-datasource/runStreams.ts [hunk 9]
```diff
@@ -27,14 +32,15 @@ export const defaultStreamQuery: StreamingQuery = {
...
   const query = defaults(target.stream, defaultStreamQuery);
-  if ('signal' === query.type) {
-    return runSignalStream(target, query, req);
-  }
-  if ('logs' === query.type) {
-    return runLogsStream(target, query, req);
-  }
-  if ('fetch' === query.type) {
-    return runFetchStream(target, query, req);
+  switch (query.type) {
```
Comment (baldm0mma) [inline public/app/plugins/datasource/grafana-testdata-datasource/runStreams.ts:35]: Nice. Switch was a good choice!

File: public/app/plugins/datasource/tempo/resultTransformer.ts [hunk 10]
```diff
@@ -995,6 +1001,7 @@ const traceSubFrame = (
     },
   });
 
+  // TODO: this should be done in applyFieldOverrides instead recursively for the nested DataFrames
```
Comment (baldm0mma) [inline public/app/plugins/datasource/tempo/resultTransformer.ts:1004]:
```suggestion
  // TODO: this should be done in `applyFieldOverrides` instead recursively for the nested `DataFrames`
```

**Review by baldm0mma — APPROVED** [review]
Not too much to add. Just a few comments. But from a DataViz squad perspective, it looks good to me!

File: public/app/plugins/datasource/grafana-testdata-datasource/components/StreamingClientEditor.tsx (hunk 8 above)
Comment (codeincarnate) [reply public/app/plugins/datasource/grafana-testdata-datasource/components/StreamingClientEditor.tsx:34]: I'd agree here, doing a guard to check that query and stream exist would make this a lot more readable.

**Review by codeincarnate — CHANGES_REQUESTED** [review]
Looks good overall!

I noticed in testing that some of the sub-table data seems to be changing on scroll. See below:


https://github.com/grafana/grafana/assets/199847/2cc614d3-79d6-477b-aca5-faea0c6c8f2e

Is this intentional?

File: public/app/plugins/datasource/grafana-testdata-datasource/components/StreamingClientEditor.tsx (hunk 8 above)
Comment (aocenas) [reply public/app/plugins/datasource/grafana-testdata-datasource/components/StreamingClientEditor.tsx]: Changed it a bit but the problem here is typing. Typing the dynamic UI creation based on the query type and associated fields is a bit harder without adding some explicit casts and need lots of additional typing which I don't want to go into right now.

For example even changing this into `if else` would mean TS complains about assigning different types to `fields` variable, because the `streamingClientFields` is `as const` type which is needed for the field mapping to `query.stream.[field]` later on to work.

**Review by codeincarnate — APPROVED** [review]
Looking good now, great PR!
