### PR TITLE
State Timeline/Status History: Fixes panels so that the rendered visualisation has correct color

### LINKED ISSUE #44648: State timeline: Visualization value colors won't update when base value changes
https://user-images.githubusercontent.com/36818606/151785509-c5517df3-0c85-4e5b-8a44-658223387439.mov

**What happened**: Changing base value of `State timeline` component while using a Color Scheme (e.g: `Red-Yellow-Green (by value)`) does not update colors correctly on the visualization itself, only on the tooltips

**What you expected to happen**:  Update the colors of the visualisation also

**How to reproduce it (as minimally and precisely as possible)**:
- Add TestDataDB datasource and set it to `CSV Content`
- Add this CSV: 
```
time,value
2022-01-27 16:45:02,
2022-01-27 16:45:03,16
```
- Convert the time field to `Time` using `Transform`
- Select `State timeline`
- Set color scheme to `Red-Yellow-Green (by value)`
- Add a value to the first row in the CSV ( there is no value in the above example), for example `0`
- The colors should update, but they don't. Only the tooltip updates.

**Anything else we need to know?**:
A workaround for this is to toggle/untoggle `Table view`

**Environment**:
- Grafana version: 8.3

### PR DESCRIPTION
**Pull request by dprokop**
Fixes https://github.com/grafana/grafana/issues/44648

Alternative to https://github.com/grafana/grafana/pull/45652

### CODE REVIEW

File: public/app/plugins/panel/state-timeline/TimelineChart.tsx [hunk 1]
```diff
@@ -34,6 +34,19 @@ export class TimelineChart extends React.Component<TimelineProps> {
   static contextType = PanelContextRoot;
   panelContext: PanelContext = {} as PanelContext;
 
+  getValueColor = (frameIdx: number, fieldIdx: number, value: any) => {
+    const field = this.props.frames[frameIdx].fields[fieldIdx];
+
+    if (field.display) {
+      const disp = field.display(value); // will apply color modes
```
Comment (torkelo) [inline public/app/plugins/panel/state-timeline/TimelineChart.tsx:41]: everytime I see this I cry a bit inside wishing we had a Field class with a default display processor

**Review by torkelo — APPROVED** [review]

**Comment by ramesh-singh-20** [comment]
How to use this property to set the color for the values, I am still confused.
