### PR TITLE
Alerting: Allow created by to be manually set when there's no creator for silences

### LINKED ISSUE #55948: Can't save silence for Grafana with disabled auth
#### What

When trying to save silence in Grafana with disabled auth (and "anonymous" Mimir tenant only) - the following error pops up:

```
Error: createdBy in body is required
```

alertmanager_mimir_bug

As `createdBy` cannot be added in the menu - I'd expect there should be a possibility to skip the validation for such setup.

#### Setup

- Grafana 9.0.9
- Mimir 2.1.0

both installed via helm charts

#### To reproduce

1. Disable auth in Grafana.
2. Add Mimir Alertmanager datasource.
3. Configure and save silence.

### PR DESCRIPTION
**Pull request by gotjosh**
Grafana has a mode that allows unauthenticated interaction, typically the created by field of a silence is inferred from the current logged user. When this is not present, the field is left black and thus the silence creation fails.

This allows us to set the created by when it is not possible to infer it from the current user.

- [x] Ideally, I would like the form to only show when `createdBy` is undefined. However, my javascript foo is way to rusty to even begin to attempt doing that - could I get some help?

fixes https://github.com/grafana/grafana/issues/55948

### CODE REVIEW

File: public/app/features/alerting/unified/components/silences/SilencesEditor.tsx [hunk 1]
```diff
@@ -164,6 +164,7 @@ export const SilencesEditor: FC<Props> = ({ silence, alertManagerSourceName }) =
     700,
     [clearErrors, duration, endsAt, prevDuration, setValue, startsAt]
   );
+  const userLogged = Boolean(config.bootData.user.isSignedIn && config.bootData.user.name);
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/silences/SilencesEditor.tsx:167]: It should work only for anonymous users, I think
```suggestion
  const userLogged = Boolean(config.bootData.user.isSignedIn && config.bootData.user.name);
```

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/silences/SilencesEditor.tsx:167]: opsssss, trueee

Comment (konrad147) [reply public/app/features/alerting/unified/components/silences/SilencesEditor.tsx:167]: My bad, I haven't noticed `!` 🤦

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/silences/SilencesEditor.tsx:167]: we use the userLogged exactly for this: 
`         {!userLogged && (
            <Field
              className={cx(styles.field, styles.createdBy)}
              label="Created By"
              required`

**Review by konrad147 — APPROVED** [review]
LGTM!
