### PR TITLE
Loki: Fix Loki with repeated panels and interpolation for Explore

### LINKED ISSUE #21419: Loki does not work with repeated panels
Need to pass scopedVars to replace function: 

https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/loki/datasource.ts#L134 

example:
expr: this.templateSrv(target.expr, options.scopedVars, this.interpolateQueryExpr)

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
This PR focuses on 2 issues: 
1. It passes *scopedVars* to `replace` function in `query` function in Loki Datasource, which fixes the problem with Loki not working with repeated panels. 
2. It adds additional *scopedVars* parameter to `interpolateVariablesInQueries` that is used to correctly interpolated variables in repeated panels. It also fixes the implementation for all datasources that currently have `interpolateVariablesInQueries` function. 

**Which issue(s) this PR fixes**:
Fixes #21419

### CODE REVIEW

File: public/app/plugins/datasource/influxdb/datasource.ts [hunk 1]
```diff
@@ -178,11 +178,11 @@ export default class InfluxDatasource extends DataSourceApi<InfluxQuery, InfluxO
         const expandedQuery = {
           ...query,
           datasource: this.name,
-          measurement: this.templateSrv.replace(query.measurement, null, 'regex'),
+          measurement: this.templateSrv.replace(query.measurement, scopedVars, 'regex'),
         };
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/influxdb/datasource.ts]: I wasn't able to test influx solution as I can not make devenv influx work for me. if reviewer could test it out, it would be amazing! 🧡In the meantime, I will try to make influx work for me.

File: public/app/plugins/datasource/mssql/datasource.ts [hunk 2]
```diff
@@ -43,14 +44,17 @@ export class MssqlDatasource {
...
+  ): MssqlQueryForInterpolation[] {
     let expandedQueries = queries;
     if (queries && queries.length > 0) {
       expandedQueries = queries.map(query => {
         const expandedQuery = {
           ...query,
           datasource: this.name,
-          rawSql: this.templateSrv.replace(query.rawSql, {}, this.interpolateVariable),
+          rawSql: this.templateSrv.replace(query.rawSql, scopedVars, this.interpolateVariable),
         };
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/mssql/datasource.ts]: I am going to create a new issue for all sql databases as all of them have following bug. When we want to get to Explore from panel, `interpolateVariablesInQueries` is used and it correctly interpolates variable. You can see correct variables in SQL Editor, but the UI/graphical editor is incorrectly displaying un-interpolated version. When you open Editor and run query, correct results are displayed.
image
image

**Review by torkelo — APPROVED** [review]
Great job @ivanahuckova looks great!
