### PR TITLE
Prometheus: Don't show errors from unsuccessful API checks like rules or exemplar checks

### LINKED ISSUE #52240: Explore page for Prometheus data source without Rules api shows "Unexpected error"
**What happened**:
When loading the explore page for a Prometheus data source without the rules API enabled a popup message shows on the UI. In our instance we are using a cortex as the backend without -experimental.ruler.enable-api.  

When running the Grafana binary included in the Docker image there is a parsing error. 
Screenshot from 2022-07-14 08-34-42
Screenshot from 2022-07-14 08-38-21

When running in debug mode from an IDE the 404 error message is show. 
Screenshot from 2022-07-14 08-45-22
Screenshot from 2022-07-14 08-45-47

**What you expected to happen**:
In previous major Grafana version, 8.5, the error was logged to the console with the message "Rules API is experimental. Ignore next error." and there was no error message visible on the UI.

Regardless of the response error it should not be show on the UI since the Rules API is experimental.

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure Cortex or Prometheus without rules enabled. 
2. Create a Prometheus data source
3. Navigate to the explore page for that datasource
4. Error is received when page is loaded or data source is change.

**Anything else we need to know?**:
**Changes noticed from version 8.5 to 9.0**
There rules metadata call was migrated to resource calls. [https://github.com/grafana/grafana/commit/53ee72d15daeede62988cbcf9339057edf5a464b#diff-338f087d1745b2d11debdbbe6b3a1ec487fb1cc966b542a8fc592b4036acbcd3R106 ](https://github.com/grafana/grafana/commit/53ee72d15daeede62988cbcf9339057edf5a464b#diff-338f087d1745b2d11debdbbe6b3a1ec487fb1cc966b542a8fc592b4036acbcd3R106). This new endpoint is hard coded to set the header content-type=application/json. Even though the 404 response has a body of text, "404 page not found." This resulting in the error "SyntaxError: Unexpected token p in JSON at position 4. In previous version content-type for the 404 response was set to text/plain.

**Environment**:
- Grafana version: v9.0.2
- Data source type & version: Prometheus data source with Cortex v1.11.1 backend   
- OS Grafana is installed on: Docker image
- User OS & Browser: Linux/Windows, Chrome/Firefox/Edge

### PR DESCRIPTION
**Pull request by darrenjaneczek**
**What this PR does / why we need it**:

The query inspector was experiencing some error pop-ups due to errors encountered on metrics datasources configured with multiple tenants.

e.g., team-a|team-b

Some of the backend implementations of these metadata endpoints aren't yet well-defined for multi-tenant queries, so they often result in error messages.

This fix suppresses those errors..

In the event of a multi-tenant datasource, these endpoints were contributing to the pop-up errors. 

`/api/v1/query_exemplars` - in a check to see if query examplars can be accessed.

`/api/v1/rules` as a metadata request
`/api/v1/metadata` as a metadata request (see: https://github.com/grafana/mimir/issues/2410)

These error messages newly became visible in version 9. Some of the underlying request errors were still present in 8.5, but they were not visible.

image

### CODE REVIEW

File: packages/grafana-runtime/src/utils/DataSourceWithBackend.ts [hunk 1]
```diff
@@ -219,14 +219,21 @@ class DataSourceWithBackend<
...
-    return getBackendSrv().post(`/api/datasources/${this.id}/resources/${path}`, { ...body });
+    return getBackendSrv().post(this.getResourcePath(path), { ...body });
+  }
+
+  /**
+   * Get the datasource resource path for the given path
+   */
+  getResourcePath(path: string): string {
+    return `/api/datasources/${this.id}/resources/${path}`;
   }
```
Comment (darrenjaneczek) [inline packages/grafana-runtime/src/utils/DataSourceWithBackend.ts:237]: The `getResourcePath` method was separated out so that it could be used by `areExamplarsAvailable`, instead of `getResource`. It uses the path to make a `fetch`, using error suppressing options.

File: public/app/plugins/datasource/prometheus/datasource.tsx [hunk 2]
```diff
@@ -237,6 +237,7 @@ export class PrometheusDatasource
       this._request<T>(`/api/datasources/${this.id}/resources${url}`, params, {
         method: 'GET',
         hideFromInspector: true,
+        showErrorAlert: false,
```
Comment (darrenjaneczek) [inline public/app/plugins/datasource/prometheus/datasource.tsx:240]: This is set to showErrorAlert: false, matching the same call in the if clause above.

This suppresses the errors from the following paths:
`/api/v1/rules`
`/api/v1/metadata`

File: public/app/plugins/datasource/prometheus/datasource.tsx [hunk 3]
```diff
@@ -1016,11 +1017,18 @@ export class PrometheusDatasource
...
+      };
+      // Avoid alerting the user if this test fails
+      const testRequest = {
+        showErrorAlert: false,
+        hideFromInspector: true,
+      };
+      const res = await lastValueFrom(getBackendSrv().fetch({ url, params, ...testRequest }));
       if (res.data.status === 'success') {
         return true;
       }
```
Comment (darrenjaneczek) [inline public/app/plugins/datasource/prometheus/datasource.tsx:1034]: This reimplementation of "areExemplarsAvaialble" uses fetch to suppress the error associated with:
`/api/v1/query_exemplars`

File: public/app/plugins/datasource/prometheus/datasource.tsx [hunk 4]
```diff
@@ -1016,11 +1017,20 @@ export class PrometheusDatasource
...
+        end: dateTime().valueOf().toString(),
+      };
+      const res = await lastValueFrom(
+        this._request<PromDataSuccessResponse<PromExemplarData>>(url, params, {
+          method: 'GET',
+          // Avoid alerting the user if this test fails
+          hideFromInspector: true,
+          showErrorAlert: false,
+        })
+      );
```
Comment (darrenjaneczek) [inline public/app/plugins/datasource/prometheus/datasource.tsx:1033]: This use of this._request helps us to suppress the error associated with:
/api/v1/query_exemplars

**Review by yesoreyeram — APPROVED** [review]
LGTM

**Comment by bboreham** [comment]
Does this suppress the messages described, or all error messages?
Are errors suppressed just when multiple tenants are defined?

**Comment by darrenjaneczek** [comment]
@bboreham 
> Does this suppress the messages described, or all error messages? Are errors suppressed just when multiple tenants are defined?

This currently suppresses all errors made through that "metadataRequest" method.

The recent PR https://github.com/grafana/grafana/pull/52249 gives finer control over this, so I will rebase and make use the parameter.

**Comment by darrenjaneczek** [comment]
@bboreham , more specifically:

This change to `metadataRequest` will be exclusive to the `PrometheusDatasource` class.

Here are the usages:

`this.metadataRequest('/api/v1/rules');`

For `getTagKeys`
this.metadataRequest('/api/v1/labels'); 

For `getTagLabels`
this.metadataRequest(`/api/v1/label/${options.key}/values`)

Not all types of datasources (classes other than PrometheusDatasource) share the pattern of setting the following options for their `metadataRequest` methods:
```
            hideFromInspector: true,
            showErrorAlert: false,
```
Some only have `hideFromInspector: true`, and others have neither.

**Comment by bboreham** [comment]
OK, I don't know what `metadataRequest` is.  I don't really need to know; the point is: are you confident this doesn't break anything else, or the ability to diagnose issues causing different errors?

**Comment by bboreham** [comment]
Also I usually recommend making the PR title match what it does.
Something like "suppress all errors for metadataRequest from prometheus datasource"?

**Comment by darrenjaneczek** [comment]
@bboreham 
> are you confident this doesn't break anything else, or the ability to diagnose issues causing different errors?

Yes, I am confident.
If there are different errors that don't just affect metadata-related calls, we will definitely see those when we start trying to make queries.

File: public/app/plugins/datasource/prometheus/datasource.tsx (hunk 2 above)
Comment (aocenas) [reply public/app/plugins/datasource/prometheus/datasource.tsx:240]: So I am just unsure here because it means that if there is any issue with labels/values API calls this will also be suppressed and user will end up with queryEditor that is failing without any indication. If we need it only for /rules and /metadata can we lift it up? Or can we just handle the error manually and look if it is a problem with multiple tenants and only hide it then?

File: public/app/plugins/datasource/prometheus/datasource.tsx (hunk 4 above)
Comment (aocenas) [reply public/app/plugins/datasource/prometheus/datasource.tsx:1033]: @leventebalogh how close is this PR https://github.com/grafana/grafana/pull/51316? Would probably help us here.

File: public/app/plugins/datasource/prometheus/datasource.tsx (hunk 2 above)
Comment (darrenjaneczek) [reply public/app/plugins/datasource/prometheus/datasource.tsx:240]: Hmmm... true. And if we can't fetch the labels/values, it won't be immediately clear that there is a problem unless they manually write queries and execute them?

Checking for the multi-tenants case would require some backend insight. Also, is it possible to suppress the error when catching it, or is it too late?

This closed PR suggests adding a parameter (see: https://github.com/grafana/grafana/pull/52249) -- then we ensure that we only suppress on `/metadata` and `/rules`. Except, I think I'd prefer something similar to @leventebalogh's and add a parameter for `options?: Partial<BackendSrvRequest>`.

Comment (darrenjaneczek) [reply public/app/plugins/datasource/prometheus/datasource.tsx:240]: @aocenas , what is your thought on the previous "IF" block, which sets `showErrorAlert` to false already:

(See line 223 above)
```typescript
  async metadataRequest<T = any>(url: string, params = {}) {
    // If URL includes endpoint that supports POST and GET method, try to use configured method. This might fail as POST is supported only in v2.10+.
    if (GET_AND_POST_METADATA_ENDPOINTS.some((endpoint) => url.includes(endpoint))) {
      try {
        return await lastValueFrom(
          this._request<T>(`/api/datasources/${this.id}/resources${url}`, params, {
            method: this.httpMethod,
            hideFromInspector: true,
            showErrorAlert: false, // <-- this is line 223
          })
        );
      } catch (err) {
        // If status code of error is Method Not Allowed (405) and HTTP method is POST, retry with GET
        if (this.httpMethod === 'POST' && isFetchError(err) && (err.status === 405 || err.status === 400)) {
          console.warn(`Couldn't use configured POST HTTP method for this request. Trying to use GET method instead.`);
        } else {
          throw err;
        }
      }
    }
    return await lastValueFrom(
      this._request<T>(`/api/datasources/${this.id}/resources${url}`, params, {
        method: 'GET',
        hideFromInspector: true,
        showErrorAlert: false, // <-- Current line we are discussing
...        
```

Comment (aocenas) [reply public/app/plugins/datasource/prometheus/datasource.tsx:240]: > And if we can't fetch the labels/values, it won't be immediately clear that there is a problem unless they manually write queries and execute them?

Well, I think the user just won't get any autocomplete in the code editor or no options in any dropdowns in the editor. They will be just empty and if we suppress the error there is not much other indication. So it's probably rare situation but still not great not to have any message there.

So I sort of like
> This closed PR suggests adding a parameter (see: #52249) -- then we ensure that we only suppress on /metadata and /rules. Except, I think I'd prefer something similar to @leventebalogh's #51316 and add a parameter for options?: Partial<BackendSrvRequest> to metadataRequest.

for this reason, as it seems like a smaller change/less of a regression at this point.

> what is your thought on the previous "IF" block, which sets showErrorAlert to false already:

So this might need a better comment in code but the reason it is there is that at first, we do a POST request, which may fail on older Prom instances because POST is supported only from a specific version. So we try the POST and if it fails in a specific way we retry with GET. So that is why we want to handle any error from the first request manually because we can potentially recover from it, and if the second fails we just show the default message because we have nothing else to do.

**Comment by darrenjaneczek** [comment]
@bboreham To ensure that label value metadata fetches return an error as early as possible, I've changed the PR to only suppress errors for these three checks:

/api/v1/query_exemplars - in a check to see if query examplars can be accessed.
/api/v1/rules as a metadata request
/api/v1/metadata as a metadata request (see: https://github.com/grafana/mimir/issues/2410)

I've changed the issue title accordingly.

File: public/app/plugins/datasource/prometheus/datasource.tsx (hunk 4 above)
Comment (56quarters) [reply public/app/plugins/datasource/prometheus/datasource.tsx]: > This use of this._request helps us to suppress the error associated with: `/api/v1/query_exemplars`

FWIW, the `/api/v1/query_exemplars` endpoint in Mimir and GEM supports multiple tenants if enabled by configuration (since 2.0).

**Review by aocenas — APPROVED** [review]

**Comment by aocenas** [comment]
@darrenjaneczek merging this and adding to 9.0.5 so this also needs a backport
