### PR TITLE
Loki: Run query when pressing Enter on line-filters

### LINKED ISSUE #49408: Loki: Hitting enter key does no longer execute query when loki line filters have focus
Not sure where this got lost, maybe in some refactoring. 

But in the new loki query builder hitting enter (or shift or ctrl+enter) does not work anymore. I think both should work.

### PR DESCRIPTION
**Pull request by svennergr**
**What this PR does / why we need it**:
Pressing the Enter-Key on the line-filters in the Loki QueryBuilder is currently doing nothing. This PR adds the missing call to `onRunQuery` in the `LokiQueryEditorSelector.onChangeInternal` method. 

After doing that this would run queries also when the line-filters are blurred. To overcome this I added an `onBlur` method, which does not call `onRunQuery` if the QueryBuilder is used in Explore.

**Which issue(s) this PR fixes**:

Fixes #49408

**Special notes for your reviewer**:
Video of the fix:

https://user-images.githubusercontent.com/8092184/171174744-8ecd715f-6512-4863-a51b-6f91938df0d1.mov

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
This is changing things in a way that I am not sure is good. We specifically don't auto run the query on changes in this new builder, instead highlight the run query button when there is a change and the query has not run. 

But when pressing enter key in the line filters (and in some other inputs) I think it should run. So only when pressing enter (or shift enter). For this I think we need a new option on the OperationParamDef  ("runOnEnter" or something close to that). Then we can check that in the onCommitChange callback

File: public/app/plugins/datasource/loki/querybuilder/components/LokiQueryEditorSelector.tsx [hunk 1]
```diff
@@ -49,6 +49,13 @@ export const LokiQueryEditorSelector = React.memo<LokiQueryEditorProps>((props)
   const onChangeInternal = (query: LokiQuery) => {
     setDataIsStale(true);
     onChange(query);
+    onRunQuery();
+  };
+
+  const onBlur = () => {
+    if (app !== CoreApp.Explore) {
+      onRunQuery();
+    }
```
Comment (torkelo) [inline public/app/plugins/datasource/loki/querybuilder/components/LokiQueryEditorSelector.tsx:58]: I would like to keep the behavior the same in Explore & elsewhere

File: public/app/plugins/datasource/loki/querybuilder/components/LokiQueryEditorSelector.tsx [hunk 2]
```diff
@@ -49,6 +49,13 @@ export const LokiQueryEditorSelector = React.memo<LokiQueryEditorProps>((props)
   const onChangeInternal = (query: LokiQuery) => {
     setDataIsStale(true);
     onChange(query);
+    onRunQuery();
```
Comment (torkelo) [inline public/app/plugins/datasource/loki/querybuilder/components/LokiQueryEditorSelector.tsx:52]:
```suggestion
```

File: public/app/plugins/datasource/loki/querybuilder/components/LokiQueryEditorSelector.tsx (hunk 1 above)
Comment (svennergr) [reply public/app/plugins/datasource/loki/querybuilder/components/LokiQueryEditorSelector.tsx:58]: I see. Just to be sure about the behaviour in the line-filters input components: 
- onBlur should highlight the `Run Query` button
- onKeyDown with `Enter` will run the query depending on a property from `QueryBuilderOperationParamDef`.

**Comment by svennergr** [comment]
Hi @torkelo,

I now added a `runQueryOnEnter` flag to the `QueryBuilderOperationParamDef` and added that flag to all those line-filters:
- Line contains
- Line does not contain
- Line contains regex match
- Line does not match regex

Are there any more operation types which should run on enter-press?

In the [`onCommitChange` of `AutoSizeInput`](https://github.com/grafana/grafana/pull/49913/files#diff-0be9584796826c55c8c8cedabfcaaecb327cd90202db28e81b23b7996aa22170R41-R43) I needed to check for the event type, to no run queries on blur.

Just one last thing I would like to highlight: 
With that change the behaviour differs a bit between the "Operations" and the "Options", which might be confusing for some users:
image

File: public/app/plugins/datasource/prometheus/querybuilder/shared/OperationParamEditor.tsx [hunk 3]
```diff
@@ -38,6 +38,9 @@ function SimpleInputParamEditor(props: QueryBuilderOperationParamEditorProps) {
       title={props.paramDef.description}
       onCommitChange={(evt) => {
         props.onChange(props.index, evt.currentTarget.value);
+        if (props.paramDef.runQueryOnEnter && evt.type !== 'blur') {
```
[the remark this answers is not in the document]
Comment (svennergr) [reply public/app/plugins/datasource/prometheus/querybuilder/shared/OperationParamEditor.tsx:41]: But maybe it's better to directly check for `evt.type === 'keydown'` instead of the negative check.

**Review by torkelo — APPROVED** [review]
