### PR TITLE
Alerting: Improve rule validation to check if rule uses backend datasources

### LINKED ISSUE #51583: Alerting: Improve validation for evaluating incompatible data source
This applies only to Grafana managed rules.

Currently when the alerting engine evaluates an alert rule that uses a non-compatible data source a rather generic exception is returned stating: 

`Failed to evaluate queries and expressions: failed to execute conditions: plugin unavailable`.

We can probably;

1. Make the exception a bit clearer by checking if the plugin is compatible
2. Add additional validation to prevent alert rules being created that are using incompatible data sources

This is technically not possible using the UI but when using the Provisioning API it's perfectly possible to provision alert rules with data source UIDs that end up not being compatible.

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What is this feature?**
Grafana supports frontend-only data sources. Although UI filters out those data sources from the list of available data sources on the rule editor page, API accepts rules that use those data sources, and the error 
```
Failed to evaluate queries and expressions: failed to execute conditions: plugin unavailable.
```
occurs in either the query preview phase or during the execution phase. 

This PR improves rule query validation to check whether the datasource(s) mentioned in the alert query have a backend query component. This will make API reject requests that mentioned frontend-only datasources with error 

```
failed to validate condition of alert rule TEST: datasource refID A is not a backend datasource
```

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/grafana/issues/51583

**Special notes for your reviewer**:

### CODE REVIEW

**Review by alexmobo — APPROVED** [review]
LGTM

File: pkg/services/ngalert/eval/eval.go [hunk 1]
```diff
@@ -23,6 +24,7 @@ import (
 	"github.com/grafana/grafana-plugin-sdk-go/data"
 )
 
+var ErrNotABackendDatasource = errors.New("")
```
Comment (grobinson-grafana) [inline pkg/services/ngalert/eval/eval.go:27]: Should this have an error message?

**Review by grobinson-grafana — CHANGES_REQUESTED** [review]

**Review by grobinson-grafana — APPROVED** [review]

**Comment by grobinson-grafana** [comment]
Looks good to me!
