### PR TITLE
Graphite: Show graphite functions descriptions

### LINKED ISSUE #26174: Query panel disappear after switching from one graphite datasource to another
**What happened**:
Query panel disappear after switching from one graphite datasource to another

Please, take a look on the attached screenshots. 
Before 
Screenshot_20200708_194947
and after
Screenshot_20200708_183703
 switching datasources. 
Panel have disappeared.

Browser debug console shows

```
    XHR POST https://grafana.xxx.xxx/api/datasources/proxy/14/render
    [HTTP/1.1 200 OK 219ms]

error parsing target: Method not found reduceSeries graphite_query.ts:57:14
```

Switching back to previous datasource does not fix problem. Browser debug console shows up next error

```
    Uncaught (in promise) TypeError: t is undefined
        r promiseToDigest.ts:3
        value query_ctrl.ts:64
        t query_ctrl.ts:41
```

**What you expected to happen**:
I expect normal switch to new datasource
**How to reproduce it (as minimally and precisely as possible)**:
* Setup dashboard with reduceSeries function in query. 
* Switch to graphite datasource with carbonapi>=0.12.6 as backend

**Anything else we need to know?**:
Switching graphite api version in datasource settings from 1.1.x to 1.0.x fix the problem

**Environment**:
- Grafana version: 6.7.2, 6.7.3, 6.7.4
- Data source type & version: graphite datasource native plugin
- OS Grafana is installed on: ubuntu 14.04
- User OS & Browser: Firefox 78.0.1
- Graphite backend - carbonapi 0.12.6/0.13.0

### PR DESCRIPTION
**Pull request by ifrost**
**What this PR does / why we need it**:

This PR fixes broken function descriptions tooltips for Graphite. List of descriptions is received from `/functions` endpoint. Graphite 1.1.7, however, has a [bug](https://github.com/graphite-project/graphite-web/issues/2609) and returns an invalid JSON. This PR attempts to fix the JSON structure on the fly. For versions 1.1.0 - 1.1.6 the endpoint returns a valid JSON. 

Unfortunately, the tooltip showing the descriptions is broken too. It disappears immediately after clicking on the question mark icon:

tooltip

This is caused by a Popover being immediately closed by `ClickOutsideWrapper` (this was added on purpose [here](https://github.com/grafana/grafana/pull/26923)). Instead of showing the description on click I thought we could simply display it with a `Tooltip` on hover to keep it consistent with the rest of UI:

word-breaks

Note that CSS wrapping has been changed to avoid overflowing long code examples, like:

no-breaks

It also adds support for "Infinity" (in Graphite query defined as "inf"):

sparse

**Which issue(s) this PR fixes**:

Related to #26174

**Special notes for your reviewer**:

This change can also help with #26174 - it will allow to verify if a function is available in currently used Graphite version when switching datasources to give use better feedback about what's wrong with the query (at the moment it simply locks in the raw editor mode).

### CODE REVIEW

File: public/app/plugins/datasource/graphite/FunctionEditorControls.tsx [hunk 1]
```diff
@@ -20,9 +20,30 @@ export interface FunctionEditorControlsProps {
   onRemove: (func: FunctionDescriptor) => void;
 }
 
-const FunctionHelpButton = (props: { description?: string; name: string; onDescriptionShow: () => void }) => {
+const FunctionDescription = React.lazy(async () => {
+  // @ts-ignore
+  const { default: rst2html } = await import(/* webpackChunkName: "rst2html" */ 'rst2html');
+  return {
+    default(props: { description?: string }) {
+      console.log(rst2html(props.description ?? ''));
```
Comment (zoltanbedi) [inline public/app/plugins/datasource/graphite/FunctionEditorControls.tsx:28]:
```suggestion
```

**Review by zoltanbedi — APPROVED** [review]
lgtm 🪴
