### PR TITLE
AzureMonitor: Add error indicating potential configuration issue on Resource Picker

### LINKED ISSUE #59688: Azure Monitor: Bad request when trying to query subscription for metrics
image

**What happened**:
The query editor for `Service: Metrics` throws an error when trying to select a resource. The following POST request fails due to an invalid query:

```
POST | https://mbo-stage.westeurope.cloudapp.azure.com/grafana/api/datasources/2/resources/resourcegraph/providers/Microsoft.ResourceGraph/resources?api-version=2021-03-01

{
  "query": "\n    resources\n     | join kind=inner (\n       ResourceContainers\n       | where type == 'microsoft.resources/subscriptions/resourcegroups'\n       | project resourceGroupURI=id, resourceGroupName=name, resourceGroup, subscriptionId\n     ) on resourceGroup, subscriptionId\n\n     | where type in ()\n     | where subscriptionId == '38bcf4c7-3cf6-42ed-9cc1-5cac61324889'\n     | summarize count() by resourceGroupName, resourceGroupURI\n     | order by resourceGroupURI asc",
  "options": {
    "resultFormat": "objectArray"
  }
}

```

The 400 Bad Request response contains the following error details:
```
{
        "code": "InvalidQuery",
        "message": "Query is invalid. Please refer to the documentation for the Azure Resource Graph service and fix the error before retrying."
      },
      {
        "code": "ParserFailure",
        "message": "ParserFailure",
        "line": 8,
        "characterPositionInLine": 22,
        "token": ")"
      }
``` 

I've extracted the resource graph query and tried to run it via the `Service: Azure Resource Graph` option. Looks like the `where`-clause with an empty `type` is the problem (see image below). It runs if I remove that clause. 
**I don't know where I could configure that type for the `Service: Metrics`queries.**

image

**What you expected to happen**:
I can select a resource in the subscription.

**How to reproduce it (as minimally and precisely as possible)**:
- add a valid Azure Monitor datasource 
- click `Explore`
- click `select a resource` for `Service: Metrics`
- select a subscription in the popup

**Anything else we need to know?**:
The test of the data source configuration of the Azure Monitor shows 'green' (no errors).

**Environment**:
- Grafana version: 9.2.7
- Data source type & version: Azure Monitor
- OS Grafana is installed on:
- User OS & Browser: Ubuntu & Firefox
- Grafana plugins: none
- Others:

### PR DESCRIPTION
**Pull request by aangelisc**
As demonstrated in #59688, there is a lack of information around potential failures when retrieving metric namespaces. This can lead to a user being unable to diagnose why they're unable to select resources using the Azure Monitor resource picker.

This PR adds an error that will highlight when the returned metric namespaces value is empty, providing some indication as to why a request has failed.

Closes #59688

### CODE REVIEW

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts [hunk 1]
```diff
@@ -364,6 +364,12 @@ export default class ResourcePickerData extends DataSourceWithBackend<AzureMonit
         supportedMetricNamespaces = supportedMetricNamespaces.concat(namespaceVals);
       }
     }
+
+    if (supportedMetricNamespaces.length === 0) {
+      throw new Error(
+        'No namespaces returned. Validate the datasource configuration is correct and required permissions have been granted.'
```
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:370]: I would give a bit more of info (for example, people may not now what a "namespace" is). Something like:

```
Unable to resolve a list of valid metric namespaces. Validate that the current data source have permissions to retrieve [metric namespaces?] for the desired subscriptions.
```

(not sure what's the right permissions that needs to be set)

**Review by andresmgot — APPROVED** [review]
LGTM, only some thoughts about how to make the error message as useful as possible.

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts (hunk 1 above)
Comment (aangelisc) [reply public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:370]: I think we need to be consistent with the documentation and suggest that the user has the `Reader` role on the subscriptions they're querying
