### PR TITLE
Border radius: Improve rule and fix remaining violations

### LINKED ISSUE #64385: Border Radius: Check and fix deviations from standard
We introduced a standard for the Grafana wide use of border radii and agreed to use 2px unless it's required differently for styling purposes (e.g. to create a certain shape).

[Here](https://internal-ops-us-east-0.grafana.net/design-system/Styling/border-radius/) you can find the documentation in Saga.
[Here](https://docs.google.com/spreadsheets/d/1gFij3aFnyMMVnNESiQbLk33e7dgAnSpMuU4WGXaKjoU/edit#gid=0) you can find the whole list of deviations.

```[tasklist]
- [ ] https://github.com/grafana/grafana/issues/64414
- [ ] https://github.com/grafana/grafana/issues/64408
- [ ] https://github.com/grafana/grafana/issues/64290
- [ ] https://github.com/grafana/grafana/issues/64421
- [ ] https://github.com/grafana/grafana/issues/64423
- [ ] https://github.com/grafana/grafana/issues/64419
- [ ] https://github.com/grafana/grafana/issues/64488
- [ ] https://github.com/grafana/grafana/issues/64490
- [ ] https://github.com/grafana/grafana/issues/65089
- [ ] https://github.com/grafana/grafana/issues/70502
```

### LINKED ISSUE #64421: Check and remove deviations from standard border radius in dashboard components
## How to make progress on this issue
- assign yourself to the task
- check the cases listed below and replace the border radius if it makes sense 
- please use `GrafanaTheme2` and set the border radius as follows: `theme.shape.radius.default` or `theme.shape.radius.pill` or `theme.shape.radius.circle`
- please leave a comment in the list mentioned below in case the border radius needs to be kept as is

Please check the use of border radius in the following files. For more information and details refer to [this list](https://docs.google.com/spreadsheets/d/1gFij3aFnyMMVnNESiQbLk33e7dgAnSpMuU4WGXaKjoU/edit#gid=441982249):
--
- [ ] public/app/core/components/OptionsUI/fieldColor.tsx
- [ ] public/app/features/dashboard/components/PanelEditor/OptionsPaneOptions.tsx
- [ ] public/app/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx
- [ ] public/app/features/dashboard/components/TransformationsEditor/TransformationEditor.tsx
- [ ] public/app/features/panel/components/VizTypePicker/VisualizationSuggestionCard.tsx
- [ ] public/app/features/query/components/QueryEditorRowHeader.tsx

**In case there are files another team is responsible for please let me know.**

### LINKED ISSUE #64488: Check and remove deviations from standard border radius in tracing&profiling
## How to make progress on this issue
- assign yourself to the task
- check the cases listed below and replace the border radius if it makes sense 
- please use `GrafanaTheme2` and set the border radius as follows: `theme.shape.radius.default` or `theme.shape.radius.pill` or `theme.shape.radius.circle`
- please leave a comment in the list mentioned below in case the border radius needs to be kept as is

Please check the use of border radius in the following files. For more information and details refer to [this list](https://docs.google.com/spreadsheets/d/1gFij3aFnyMMVnNESiQbLk33e7dgAnSpMuU4WGXaKjoU/edit#gid=608301790):
--

- [ ] public/app/plugins/datasource/parca/QueryEditor/LabelsEditor.tsx
- [ ] public/app/plugins/datasource/phlare/QueryEditor/LabelsEditor.tsx

**In case there are files another team is responsible for please let me know.**

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- improves rule to catch more edge cases
- fixes majority, adds ignore comments for some others

**Why do we need this feature?**

- consistency

**Who is this feature for?**

- grafana devs

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/64385
Fixes https://github.com/grafana/grafana/issues/64488
Fixes https://github.com/grafana/grafana/issues/64421

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/themes/GlobalStyles/elements.ts [hunk 1]
```diff
@@ -276,6 +276,7 @@ export function getElementStyles(theme: GrafanaTheme2, isExtensionSidebarOpen?:
     // 2. Correct font properties not being inherited.
     // 3. Address margins set differently in Firefox 4+, Safari, and Chrome.
     'button, input, optgroup, select, textarea': {
+      // eslint-disable-next-line @grafana/no-border-radius-literal
```
[the remark this answers is not in the document]
Comment (ashharrison90) [reply packages/grafana-ui/src/themes/GlobalStyles/elements.ts:279]: i think if we want to support it, we should add an explicit token for it. e.g. `theme.shape.radius.none` or something

but tbh i can't think of a good use case for it. this is a pretty special global case, makes sense to just ignore the rule here. can you think of a more general case where you'd need to unset the border radius of something? 🤔

File: public/app/plugins/panel/canvas/globalStyles.ts [hunk 2]
```diff
@@ -157,7 +157,7 @@ export function getGlobalStyles(theme: GrafanaTheme2) {
             '&.rc-tree-checkbox-indeterminate.rc-tree-checkbox-disabled': {
               position: 'relative',
               background: '#ccc',
-              borderRadius: '3px',
+              borderRadius: theme.shape.radius.default,
```
Comment (CollinFingar) [inline public/app/plugins/panel/canvas/globalStyles.ts:160]: Just checking on the few different values being converted to `theme.shape.radius.default` (`2px`, `3px`, `4px`). I'm guessing this is intentional to make them all uniformed as they're close enough at the moment?

File: packages/grafana-eslint-rules/tests/no-border-radius-literal.test.js [hunk 3]
```diff
@@ -32,27 +36,27 @@ ruleTester.run('eslint no-border-radius-literal', noBorderRadiusLiteral, {
...
       code: `css([{ lineHeight: 1 }, { borderRadius: '2px' }])`,
-      errors: [
-        {
-          message: 'Prefer using theme.shape.radius tokens instead of literal values.',
-        },
-      ],
+      errors: [expectedError],
+    },
+    {
+      name: 'nested classes',
```
Comment (tomratcliffe) [inline packages/grafana-eslint-rules/tests/no-border-radius-literal.test.js:50]: FYI @ashharrison90 I pushed a test for the nested classes case that the rule now catches

**Review by tomratcliffe — APPROVED** [review]
LGTM!
