### PR TITLE
Loki: Fix wrongly escaped label values when using LabelFilter

### LINKED ISSUE #59333: Explore Loki query builder uses escape on backtick strings
**What happened**: If you click on the magnifier in the Explore page the value of the label gets escaped and put inside backticks.

image

result query 

```
{app !="", level=~"error|warning", machineName="server"} | json | user=`DOMAINNAME\\USERNAME` | line_format "{{.app}}@{{.machineName}} : {{.t}} IP:{{.remoteAddr}}\n{{.user}}"
```

**What you expected to happen**: either use quotes or disable escaping.

**How to reproduce it (as minimally and precisely as possible)**: make a loki query and click on magnifier next to log lable with special characters 

**Environment**:
- Grafana version: 9.2.6
- OS Grafana is installed on: Windows Server 2019
- Others: loki, version HEAD-1b627d8 (branch: HEAD, revision: 1b627d880)
  build user:       root@079d888186e6
  build date:       2022-11-10T23:52:44Z
  go version:       go1.19.2
  platform:         windows/amd64

### PR DESCRIPTION
**Pull request by svennergr**
**What is this feature?**

As reported in #59333 using the filter-in and out buttons in Loki is currently broken when the label value contains special characters. This PR fixes that by not using backticks but quotes as identifier for a value.

**Which issue(s) does this PR fix?**:

Fixes #59333

**Special notes for your reviewer**:
1. With a Loki devenv open Explore
2. Run a `{place="luna"} | logfmt ` query
3. Click the Filter-In button on an `instance` label containing `server\2` or a `job` label containing `"grafana/data"`.
4. Without the fix notice the bug.

### CODE REVIEW

**Review by matyax — APPROVED** [review]

File: public/app/plugins/datasource/loki/querybuilder/parsing.ts [hunk 1]
```diff
@@ -212,7 +212,9 @@ function getLabel(expr: string, node: SyntaxNode): QueryBuilderLabelFilter {
   const labelNode = node.getChild(Identifier);
   const label = getString(expr, labelNode);
   const op = getString(expr, labelNode!.nextSibling);
-  const value = getString(expr, node.getChild(String)).replace(/"/g, '');
+  let value = getString(expr, node.getChild(String));
+  // `value` is wrapped in double quotes, so we need to remove them. As a value can contain double quotes, we can't use RegEx here.
+  value = value.substring(1, value.length - 1);
```
Comment (svennergr) [inline public/app/plugins/datasource/loki/querybuilder/parsing.ts:217]: @matyax @ivanahuckova that was the issue which caused wrong visuals in the query builder when switching from code. Since it also messed up my testing I fixed it here directly.

File: public/app/plugins/datasource/loki/modifyQuery.ts [hunk 2]
```diff
@@ -329,7 +329,7 @@ function addFilterAsLabelFilter(
     const start = query.substring(prev, match.to);
     const end = isLast ? query.substring(match.to) : '';
 
-    const labelFilter = ` | ${filter.label}${filter.op}\`${filter.value}\``;
+    const labelFilter = ` | ${filter.label}${filter.op}"${filter.value}"`;
```
[the remark this answers is not in the document]
Comment (svennergr) [reply public/app/plugins/datasource/loki/modifyQuery.ts]: Behavior changed and backed by those tests: https://github.com/grafana/grafana/pull/59812/files#diff-cf79bb71c8c429239aa2cbadd4e1dc3dad57c253e93f6cf864f6862a60e8ede9R48-R54

File: public/app/plugins/datasource/loki/languageUtils.ts [hunk 3]
```diff
@@ -35,6 +35,10 @@ export function escapeLabelValueInExactSelector(labelValue: string): string {
   return labelValue.replace(/\\/g, '\\\\').replace(/\n/g, '\\n').replace(/"/g, '\\"');
 }
 
+export function unescapeLabelValue(labelValue: string): string {
+  return labelValue.replace(/\\n/g, '\n').replace(/\\"/g, '"').replace(/\\\\/g, '\\');
```
Comment (matyax) [inline public/app/plugins/datasource/loki/languageUtils.ts:39]: Why do we care about `\n` here?

**Review by matyax — APPROVED** [review]
Verified that it fixes the bug 👍

File: public/app/plugins/datasource/loki/languageUtils.ts (hunk 3 above)
Comment (svennergr) [reply public/app/plugins/datasource/loki/languageUtils.ts:39]: Basically I am just blindly doing the opposite as https://github.com/grafana/grafana/pull/59812/files/18b24952aeceef89f0589ed205bec904bc5d2ad2#diff-5ed6a834fd2847e0c6660d68d3ac7e583c188b5940bb1b1ecfd0f8087c8014dfR34, which  is escaping newlines. 

I am also unsure if a label value will ever contain newlines. Guess that's a good question which can be answered in https://github.com/grafana/grafana/issues/59824.
