### PR TITLE
panel: defensive coding that fixes #15563

### LINKED ISSUE #15563: Query editor crashes if has-text-edit-mode set to true but not implemented in plugin
If a query editor partial uses the query-editor-row directive and sets the `has-text-edit-mode` to true:

```html
<query-editor-row query-ctrl="ctrl" has-text-edit-mode="true">
```

But does not implement the toggleEditorMode function then the [query-editor-row](https://github.com/grafana/grafana/blob/master/public/app/features/panel/query_editor_row.ts#L19) will throw an exception which causes the query editor to not be loaded properly.

There are several plugins that have done so and this used to not crash in previous versions of Grafana.

### PR DESCRIPTION
**Pull request by daniellee**
If a plugin incorrectly sets toggle text mode to true in the query-editor-row directive, it should not throw an exception. While it is incorrect for the plugin to do so, this used to work in Grafana 5.x.

### CODE REVIEW

File: public/app/features/panel/query_editor_row.ts [hunk 1]
```diff
@@ -14,12 +14,12 @@ export class QueryRowCtrl {
...
     this.panel = this.panelCtrl.panel;
 
-    if (this.hasTextEditMode) {
+    if (this.hasTextEditMode && this.queryCtrl.toggleEditorMode) {
       // expose this function to react parent component
       this.panelCtrl.toggleEditorMode = this.queryCtrl.toggleEditorMode.bind(this.queryCtrl);
     }
 
-    if (this.queryCtrl.getCollapsedText) {
+    if (this.queryCtrl.getCollapsedText && this.queryCtrl.getCollapsedText) {
```
Comment (torkelo) [inline public/app/features/panel/query_editor_row.ts]: this checks the same function twice :)
