### PR TITLE
Settings: Fix data race when dynamically overriding settings with environment variables

### LINKED ISSUE #44509: Grafana server crashes with concurrent map writes
**What happened**:
Grafana server crashes with:

> fatal error: concurrent map writes 

**What you expected to happen**:
No panic

**How to reproduce it (as minimally and precisely as possible)**:
I saw this subside when we turned off `unified alerting (ngalert)` in previous versions of Grafana, but I could be wrong.

**Anything else we need to know?**:

Stacktrace:

    t=2022-01-26T17:58:44-0500 lvl=info msg="Initialized channel handler" logger=live channel=grafana/dashboard/uid/jReK7Vo7k address=grafana/dashboard/uid/jReK7Vo7k
    t=2022-01-26T17:59:49-0500 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=11 orgId=1 uname=rajat path=/api/datasources/proxy/57/_msearch remote_addr=xx.xx.xx.xxx referer="https://grafana/d/i3X3JXFnz/time-series?orgId=1&refresh=1s&from=now-6h&to=now" error="http: proxy error: context canceled"
    t=2022-01-26T17:59:49-0500 lvl=eror msg="Request Completed" logger=context userId=11 orgId=1 uname=rajat method=POST path=/api/datasources/proxy/57/_msearch status=502 remote_addr=xx.xx.xx.xxx time_ms=10 size=0 referer="https://grafana/d/i3X3JXFnz/time-series?orgId=1&refresh=1s&from=now-6h&to=now"
    fatal error: concurrent map writes
    
    goroutine 69077 [running]:
    runtime.throw({0x2de6a77, 0xc0014d9790})
            /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc0014223b8 sp=0xc001422388 pc=0x43f5d1
    runtime.mapassign_faststr(0x28cebc0, 0x7, {0x2db8336, 0x7})
            /usr/local/go/src/runtime/map_faststr.go:211 +0x39c fp=0xc001422420 sp=0xc0014223b8 pc=0x41cadc
    gopkg.in/ini%2ev1.(*Section).NewKey(0xc0019f8cb0, {0x2db8336, 0xc0014224f8}, {0x0, 0xc0023493a0})
            /root/go/pkg/mod/gopkg.in/ini.v1@v1.62.0/section.go:85 +0x26b fp=0xc0014224c8 sp=0xc001422420 pc=0x7836cb
    gopkg.in/ini%2ev1.(*Section).Key(0xc0023493a0, {0x2db8336, 0x7})
            /root/go/pkg/mod/gopkg.in/ini.v1@v1.62.0/section.go:171 +0x45 fp=0xc001422508 sp=0xc0014224c8 pc=0x784165
    github.com/grafana/grafana/pkg/setting.(*DynamicSection).Key(0xc0014226f0, {0x2db8336, 0x7})
            /drone/src/pkg/setting/setting.go:1153 +0x96 fp=0xc0014225a8 sp=0xc001422508 pc=0xdb50d6
    github.com/grafana/grafana/pkg/api.(*HTTPServer).getFrontendSettingsMap(0xc0002e3080, 0xc0025ef740)
            /drone/src/pkg/api/frontendsettings.go:288 +0x2a3b fp=0xc001422d20 sp=0xc0014225a8 pc=0x2122e9b
    github.com/grafana/grafana/pkg/api.(*HTTPServer).setIndexViewData(0xc0002e3080, 0xc0025ef740)
            /drone/src/pkg/api/index.go:523 +0xee fp=0xc001422f80 sp=0xc001422d20 pc=0x212de4e
    github.com/grafana/grafana/pkg/api.(*HTTPServer).Index(0xc0002e3080, 0xc0025ef740)
            /drone/src/pkg/api/index.go:638 +0x27 fp=0xc001422fc8 sp=0xc001422f80 pc=0x212eb27
    github.com/grafana/grafana/pkg/api.(*HTTPServer).Index-fm(0x0)
            /drone/src/pkg/api/index.go:637 +0x2c fp=0xc001422fe8 sp=0xc001422fc8 pc=0x215244c
    runtime.call16(0xc0017de180, 0xc0017ed2b0, 0x0, 0x0, 0x0, 0x8, 0xc001423518)
            /usr/local/go/src/runtime/asm_amd64.s:625 +0x49 fp=0xc001423008 sp=0xc001422fe8 pc=0x471129
    runtime.reflectcall(0x2d4e700, 0xc0025ef740, 0x1, 0x2ddc120, 0x0, 0x12, 0x2d4e700)
            <autogenerated>:1 +0x3c fp=0xc001423048 sp=0xc001423008 pc=0x47551c
    reflect.Value.call({0x2741b60, 0xc0017ed2b0, 0x7f92a5c72a68}, {0x2db0e7c, 0x4}, {0xc001690ca8, 0x1, 0xc0007ef878})
            /usr/local/go/src/reflect/value.go:543 +0x814 fp=0xc001423638 sp=0xc001423048 pc=0x4e6334
    reflect.Value.Call({0x2741b60, 0xc0017ed2b0, 0x2d4e700}, {0xc001690ca8, 0x1, 0x1})
            /usr/local/go/src/reflect/value.go:339 +0xc5 fp=0xc0014236b0 sp=0xc001423638 pc=0x4e58e5
    gopkg.in/macaron%2ev1.(*injector).callInvoke(0xc000a9cfa0, {0x2741b60, 0xc0017ed2b0}, {0x346eb50, 0x2741b60}, 0x1)
            /drone/src/pkg/macaron/inject.go:159 +0x127 fp=0xc001423740 sp=0xc0014236b0 pc=0xdbe007
    gopkg.in/macaron%2ev1.(*injector).Invoke(0x2282aaa4670197, {0x2741b60, 0xc0017ed2b0})
            /drone/src/pkg/macaron/inject.go:119 +0xb5 fp=0xc0014237c0 sp=0xc001423740 pc=0xdbdc55
    gopkg.in/macaron%2ev1.(*Context).run(0xc001ea2540)
            /drone/src/pkg/macaron/context.go:67 +0x6c fp=0xc0014237e8 sp=0xc0014237c0 pc=0xdbceec
    gopkg.in/macaron%2ev1.(*Context).Next(...)
            /drone/src/pkg/macaron/context.go:62
    github.com/grafana/grafana/pkg/middleware.RequestMetrics.func1.1({0x33dc8d0, 0xc001764c60}, 0xc002590500, 0xc001ea2540)
            /drone/src/pkg/middleware/request_metrics.go:55 +0x134 fp=0xc0014241d8 sp=0xc0014237e8 pc=0x163e234
    runtime.call32(0xc00168f200, 0xc0018ba3c0, 0x0, 0x0, 0x0, 0x20, 0xc001424718)
            /usr/local/go/src/runtime/asm_amd64.s:626 +0x49 fp=0xc001424208 sp=0xc0014241d8 pc=0x4711c9
    runtime.reflectcall(0x2d32500, 0xc001ea2540, 0x4, 0x2ddc120, 0x0, 0x12, 0x2d32500)
            <autogenerated>:1 +0x3c fp=0xc001424248 sp=0xc001424208 pc=0x47551c
    reflect.Value.call({0x286e660, 0xc0018ba3c0, 0x7f92a5c72a68}, {0x2db0e7c, 0x4}, {0xc001212190, 0x3, 0xc0021aa580})
            /usr/local/go/src/reflect/value.go:543 +0x814 fp=0xc001424838 sp=0xc001424248 pc=0x4e6334
    reflect.Value.Call({0x286e660, 0xc0018ba3c0, 0x2d32500}, {0xc001212190, 0x3, 0x3})
            /usr/local/go/src/reflect/value.go:339 +0xc5 fp=0xc0014248b0 sp=0xc001424838 pc=0x4e58e5
    gopkg.in/macaron%2ev1.(*injector).callInvoke(0xc0008cec78, {0x286e660, 0xc0018ba3c0}, {0x346eb50, 0x286e660}, 0x3)
            /drone/src/pkg/macaron/inject.go:159 +0x127 fp=0xc001424940 sp=0xc0014248b0 pc=0xdbe007
    gopkg.in/macaron%2ev1.(*injector).Invoke(0xc001764c60, {0x286e660, 0xc0018ba3c0})
            /drone/src/pkg/macaron/inject.go:119 +0xb5 fp=0xc0014249c0 sp=0xc001424940 pc=0xdbdc55
    gopkg.in/macaron%2ev1.(*Context).run(0xc001ea2540)
            /drone/src/pkg/macaron/context.go:67 +0x6c fp=0xc0014249e8 sp=0xc0014249c0 pc=0xdbceec
    gopkg.in/macaron%2ev1.(*Context).Next(...)
            /drone/src/pkg/macaron/context.go:62
    gopkg.in/macaron%2ev1.(*Macaron).UseMiddleware.func1({0x33dc8d0, 0xc001764c60}, 0xc002590500)
            /drone/src/pkg/macaron/macaron.go:155 +0x1fb fp=0xc001424a40 sp=0xc0014249e8 pc=0xdc4fdb
    net/http.HandlerFunc.ServeHTTP(0xc0007f0b28, {0x33dc8d0, 0xc001764c60}, 0xc0007f0b00)
            /usr/local/go/src/net/http/server.go:2046 +0x2f fp=0xc001424a68 sp=0xc001424a40 pc=0x6d990f
    github.com/grafana/grafana/pkg/middleware.AddCSPHeader.func1.1({0x33dc8d0, 0xc001764c60}, 0x0)
            /drone/src/pkg/middleware/csp.go:22 +0x653 fp=0xc001424b68 sp=0xc001424a68 pc=0x163aa33
    runtime.call32(0xc00168f2c0, 0xc00113e330, 0x0, 0x0, 0x0, 0x18, 0xc0014250a8)
            /usr/local/go/src/runtime/asm_amd64.s:626 +0x49 fp=0xc001424b98 sp=0xc001424b68 pc=0x4711c9
    runtime.reflectcall(0x2d1e860, 0xc002590500, 0x4, 0x2ddc120, 0x0, 0x12, 0x2d1e860)
            <autogenerated>:1 +0x3c fp=0xc001424bd8 sp=0xc001424b98 pc=0x47551c
    reflect.Value.call({0x295cf60, 0xc00113e330, 0x7f92a5c72a68}, {0x2db0e7c, 0x4}, {0xc001e71950, 0x2, 0xc0007f0f48})
            /usr/local/go/src/reflect/value.go:543 +0x814 fp=0xc0014251c8 sp=0xc001424bd8 pc=0x4e6334
    reflect.Value.Call({0x295cf60, 0xc00113e330, 0x2d1e860}, {0xc001e71950, 0x2, 0x2})
            /usr/local/go/src/reflect/value.go:339 +0xc5 fp=0xc001425240 sp=0xc0014251c8 pc=0x4e58e5
    gopkg.in/macaron%2ev1.(*injector).callInvoke(0xc0008cec78, {0x295cf60, 0xc00113e330}, {0x346eb50, 0x295cf60}, 0x2)
            /drone/src/pkg/macaron/inject.go:159 +0x127 fp=0xc0014252d0 sp=0xc001425240 pc=0xdbe007
    gopkg.in/macaron%2ev1.(*injector).Invoke(0xc001764c60, {0x295cf60, 0xc00113e330})
            /drone/src/pkg/macaron/inject.go:119 +0xb5 fp=0xc001425350 sp=0xc0014252d0 pc=0xdbdc55
    gopkg.in/macaron%2ev1.(*Context).run(0xc001ea2540)
            /drone/src/pkg/macaron/context.go:67 +0x6c fp=0xc001425378 sp=0xc001425350 pc=0xdbceec
    gopkg.in/macaron%2ev1.(*Context).Next(...)
            /drone/src/pkg/macaron/context.go:62
    gopkg.in/macaron%2ev1.(*Macaron).UseMiddleware.func1({0x33dc8d0, 0xc001764c60}, 0xc00122d300)
            /drone/src/pkg/macaron/macaron.go:155 +0x1fb fp=0xc0014253d0 sp=0xc001425378 pc=0xdc4fdb
    net/http.HandlerFunc.ServeHTTP(0x33c1400, {0x33dc8d0, 0xc001764c60}, 0x2)
            /usr/local/go/src/net/http/server.go:2046 +0x2f fp=0xc0014253f8 sp=0xc0014253d0 pc=0x6d990f
    gopkg.in/macaron%2ev1.Renderer.func1.1({0x33dc8d0, 0xc001764c60}, 0xc00122d300)
            /drone/src/pkg/macaron/render.go:44 +0x1e7 fp=0xc001425490 sp=0xc0014253f8 pc=0xdbfcc7
    runtime.call32(0xc00168f2c0, 0xc0019002a0, 0x0, 0x0, 0x0, 0x18, 0xc0014259d0)
            /usr/local/go/src/runtime/asm_amd64.s:626 +0x49 fp=0xc0014254c0 sp=0xc001425490 pc=0x4711c9
    runtime.reflectcall(0x2d1e860, 0xc00122d300, 0x4, 0x2ddc120, 0x0, 0x12, 0x2d1e860)
            <autogenerated>:1 +0x3c fp=0xc001425500 sp=0xc0014254c0 pc=0x47551c
    reflect.Value.call({0x295cf60, 0xc0019002a0, 0x7f92a5c72108}, {0x2db0e7c, 0x4}, {0xc00116f020, 0x2, 0xc00263fb50})
            /usr/local/go/src/reflect/value.go:543 +0x814 fp=0xc001425af0 sp=0xc001425500 pc=0x4e6334
    reflect.Value.Call({0x295cf60, 0xc0019002a0, 0x2d1e860}, {0xc00116f020, 0x2, 0x2})
            /usr/local/go/src/reflect/value.go:339 +0xc5 fp=0xc001425b68 sp=0xc001425af0 pc=0x4e58e5
    gopkg.in/macaron%2ev1.(*injector).callInvoke(0x417f8c, {0x295cf60, 0xc0019002a0}, {0x346eb50, 0x295cf60}, 0x2)
            /drone/src/pkg/macaron/inject.go:159 +0x127 fp=0xc001425bf8 sp=0xc001425b68 pc=0xdbe007
    gopkg.in/macaron%2ev1.(*injector).Invoke(0x40bfe9, {0x295cf60, 0xc0019002a0})
            /drone/src/pkg/macaron/inject.go:119 +0xb5 fp=0xc001425c78 sp=0xc001425bf8 pc=0xdbdc55
    gopkg.in/macaron%2ev1.(*Context).run(0xc001ea2540)
            /drone/src/pkg/macaron/context.go:67 +0x6c fp=0xc001425ca0 sp=0xc001425c78 pc=0xdbceec
    gopkg.in/macaron%2ev1.(*Context).Next(...)
            /drone/src/pkg/macaron/context.go:62
    github.com/grafana/grafana/pkg/middleware.Recovery.func1(0x10)
            /drone/src/pkg/middleware/recovery.go:167 +0x6b fp=0xc001425ce0 sp=0xc001425ca0 pc=0x163d58b
    gopkg.in/macaron%2ev1.ContextInvoker.Invoke(0x2d32500, {0xc0027c3030, 0x2d32500, 0xc00263fda0})
            /drone/src/pkg/macaron/context.go:32 +0x3c fp=0xc001425d08 sp=0xc001425ce0 pc=0xdbcddc
    gopkg.in/macaron%2ev1.(*injector).fastInvoke(0xc0008cec78, {0x7f927475b878, 0xc0018c89b0}, {0x346eb50, 0x290fe20}, 0x1)
            /drone/src/pkg/macaron/inject.go:139 +0x95 fp=0xc001425d78 sp=0xc001425d08 pc=0xdbdd75
    gopkg.in/macaron%2ev1.(*injector).Invoke(0xc001764c60, {0x290fe20, 0xc0018c89b0})
            /drone/src/pkg/macaron/inject.go:117 +0xfd fp=0xc001425df8 sp=0xc001425d78 pc=0xdbdc9d
    gopkg.in/macaron%2ev1.(*Context).run(0xc001ea2540)
            /drone/src/pkg/macaron/context.go:67 +0x6c fp=0xc001425e20 sp=0xc001425df8 pc=0xdbceec
    gopkg.in/macaron%2ev1.(*Context).Next(...)
            /drone/src/pkg/macaron/context.go:62
    gopkg.in/macaron%2ev1.(*Macaron).UseMiddleware.func1({0x33dc8d0, 0xc001764c60}, 0xc00122d300)
            /drone/src/pkg/macaron/macaron.go:155 +0x1fb fp=0xc001425e78 sp=0xc001425e20 pc=0xdc4fdb
    net/http.HandlerFunc.ServeHTTP(0x2b475e0, {0x33dc8d0, 0xc001764c60}, 0x4)
            /usr/local/go/src/net/http/server.go:2046 +0x2f fp=0xc001425ea0 sp=0xc001425e78 pc=0x6d990f
    github.com/grafana/grafana/pkg/middleware.Gziper.func1.1({0x33df600, 0xc0016747d0}, 0xc00122d300)
            /drone/src/pkg/middleware/gziper.go:75 +0x359 fp=0xc001425f40 sp=0xc001425ea0 pc=0x163f839
    runtime.call32(0xc00168f2c0, 0xc0017654d0, 0x0, 0x0, 0x0, 0x18, 0xc001426480)
            /usr/local/go/src/runtime/asm_amd64.s:626 +0x49 fp=0xc001425f70 sp=0xc001425f40 pc=0x4711c9
    runtime.reflectcall(0x2d1e860, 0xc00122d300, 0x4, 0x2ddc120, 0x0, 0x12, 0x2d1e860)
            <autogenerated>:1 +0x3c fp=0xc001425fb0 sp=0xc001425f70 pc=0x47551c
    reflect.Value.call({0x295cf60, 0xc0017654d0, 0x13}, {0x2db0e7c, 0x4}, {0xc00116eff0, 0x2, 0x2})
            /usr/local/go/src/reflect/value.go:543 +0x814 fp=0xc0014265a0 sp=0xc001425fb0 pc=0x4e6334
    reflect.Value.Call({0x295cf60, 0xc0017654d0, 0x2d1e860}, {0xc00116eff0, 0x2, 0x2})
            /usr/local/go/src/reflect/value.go:339 +0xc5 fp=0xc001426618 sp=0xc0014265a0 pc=0x4e58e5
    gopkg.in/macaron%2ev1.(*injector).callInvoke(0x4682a5, {0x295cf60, 0xc0017654d0}, {0x346eb50, 0x295cf60}, 0x2)
            /drone/src/pkg/macaron/inject.go:159 +0x127 fp=0xc0014266a8 sp=0xc001426618 pc=0xdbe007
    gopkg.in/macaron%2ev1.(*injector).Invoke(0x2aa1fe0, {0x295cf60, 0xc0017654d0})
            /drone/src/pkg/macaron/inject.go:119 +0xb5 fp=0xc001426728 sp=0xc0014266a8 pc=0xdbdc55
    gopkg.in/macaron%2ev1.(*Context).run(0xc001ea2540)
            /drone/src/pkg/macaron/context.go:67 +0x6c fp=0xc001426750 sp=0xc001426728 pc=0xdbceec
    gopkg.in/macaron%2ev1.(*Context).Next(...)
            /drone/src/pkg/macaron/context.go:62
    github.com/grafana/grafana/pkg/middleware.Logger.func1({0x33df600, 0xc0016747d0}, 0xc00122d300, 0xc001ea2540)
            /drone/src/pkg/middleware/logger.go:33 +0xa5 fp=0xc001426818 sp=0xc001426750 pc=0x163b445
    runtime.call32(0xc00168f200, 0xc0018c89a0, 0x0, 0x0, 0x0, 0x20, 0xc001426d58)
            /usr/local/go/src/runtime/asm_amd64.s:626 +0x49 fp=0xc001426848 sp=0xc001426818 pc=0x4711c9
    runtime.reflectcall(0x2d32500, 0xc001ea2540, 0x4, 0x2ddc120, 0x0, 0x12, 0x2d32500)
            <autogenerated>:1 +0x3c fp=0xc001426888 sp=0xc001426848 pc=0x47551c
    reflect.Value.call({0x286e660, 0xc0018c89a0, 0x7f92a5c72108}, {0x2db0e7c, 0x4}, {0xc0016748c0, 0x3, 0x203000})
            /usr/local/go/src/reflect/value.go:543 +0x814 fp=0xc001426e78 sp=0xc001426888 pc=0x4e6334
    reflect.Value.Call({0x286e660, 0xc0018c89a0, 0x2d32500}, {0xc0016748c0, 0x3, 0x3})
            /usr/local/go/src/reflect/value.go:339 +0xc5 fp=0xc001426ef0 sp=0xc001426e78 pc=0x4e58e5
    gopkg.in/macaron%2ev1.(*injector).callInvoke(0x0, {0x286e660, 0xc0018c89a0}, {0x346eb50, 0x286e660}, 0x3)
            /drone/src/pkg/macaron/inject.go:159 +0x127 fp=0xc001426f80 sp=0xc001426ef0 pc=0xdbe007
    gopkg.in/macaron%2ev1.(*injector).Invoke(0xc00122d300, {0x286e660, 0xc0018c89a0})
            /drone/src/pkg/macaron/inject.go:119 +0xb5 fp=0xc001427000 sp=0xc001426f80 pc=0xdbdc55
    gopkg.in/macaron%2ev1.(*Context).run(0xc001ea2540)
            /drone/src/pkg/macaron/context.go:67 +0x6c fp=0xc001427028 sp=0xc001427000 pc=0xdbceec
    gopkg.in/macaron%2ev1.(*Context).Next(...)
            /drone/src/pkg/macaron/context.go:62
    github.com/grafana/grafana/pkg/middleware.RequestTracing.func1({0x33df600, 0xc0016747d0}, 0xc00122d200, 0xc001ea2540)
            /drone/src/pkg/middleware/request_tracing.go:57 +0x55a fp=0xc001427178 sp=0xc001427028 pc=0x163fe1a
    runtime.call32(0xc00168f200, 0x2fa58e0, 0x0, 0x0, 0x0, 0x20, 0xc0014276b8)
            /usr/local/go/src/runtime/asm_amd64.s:626 +0x49 fp=0xc0014271a8 sp=0xc001427178 pc=0x4711c9
    runtime.reflectcall(0x2d32500, 0xc001ea2540, 0x4, 0x2ddc120, 0x0, 0x12, 0x2d32500)
            <autogenerated>:1 +0x3c fp=0xc0014271e8 sp=0xc0014271a8 pc=0x47551c
    reflect.Value.call({0x286e660, 0x2fa58e0, 0x13}, {0x2db0e7c, 0x4}, {0xc001674870, 0x3, 0x3})
            /usr/local/go/src/reflect/value.go:543 +0x814 fp=0xc0014277d8 sp=0xc0014271e8 pc=0x4e6334
    reflect.Value.Call({0x286e660, 0x2fa58e0, 0x2d32500}, {0xc001674870, 0x3, 0x3})
            /usr/local/go/src/reflect/value.go:339 +0xc5 fp=0xc001427850 sp=0xc0014277d8 pc=0x4e58e5
    gopkg.in/macaron%2ev1.(*injector).callInvoke(0xdbf483, {0x286e660, 0x2fa58e0}, {0x346eb50, 0x286e660}, 0x3)
            /drone/src/pkg/macaron/inject.go:159 +0x127 fp=0xc0014278e0 sp=0xc001427850 pc=0xdbe007
    gopkg.in/macaron%2ev1.(*injector).Invoke(0x150, {0x286e660, 0x2fa58e0})
            /drone/src/pkg/macaron/inject.go:119 +0xb5 fp=0xc001427960 sp=0xc0014278e0 pc=0xdbdc55
    gopkg.in/macaron%2ev1.(*Context).run(0xc001ea2540)
            /drone/src/pkg/macaron/context.go:67 +0x6c fp=0xc001427988 sp=0xc001427960 pc=0xdbceec
    gopkg.in/macaron%2ev1.(*Router).Handle.func1({0x33dfae0, 0xc0017d20e0}, 0x2daf174, 0x2)
            /drone/src/pkg/macaron/router.go:156 +0x25e fp=0xc001427a18 sp=0xc001427988 pc=0xdc15fe
    gopkg.in/macaron%2ev1.(*Router).ServeHTTP(0xc0017f3000, {0x33dfae0, 0xc0017d20e0}, 0xc00122c600)
            /drone/src/pkg/macaron/router.go:223 +0x192 fp=0xc001427a78 sp=0xc001427a18 pc=0xdc2292
    gopkg.in/macaron%2ev1.(*Macaron).ServeHTTP(0xc0017fcd80, {0x33dfae0, 0xc0017d20e0}, 0xc00122c600)
            /drone/src/pkg/macaron/macaron.go:189 +0xf1 fp=0xc001427ac0 sp=0xc001427a78 pc=0xdbf611
    net/http.serverHandler.ServeHTTP({0xc00116edb0}, {0x33dfae0, 0xc0017d20e0}, 0xc00122c600)
            /usr/local/go/src/net/http/server.go:2878 +0x43b fp=0xc001427b80 sp=0xc001427ac0 pc=0x6dce7b
    net/http.(*conn).serve(0xc0024dc140, {0x3404bb0, 0xc00168ef30})
            /usr/local/go/src/net/http/server.go:1929 +0xb08 fp=0xc001427fb8 sp=0xc001427b80 pc=0x6d89e8
    net/http.(*Server).Serve·dwrap·82()
            /usr/local/go/src/net/http/server.go:3033 +0x2e fp=0xc001427fe0 sp=0xc001427fb8 pc=0x6dd7ce
    runtime.goexit()
            /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc001427fe8 sp=0xc001427fe0 pc=0x472e01
    created by net/http.(*Server).Serve
            /usr/local/go/src/net/http/server.go:3033 +0x4e8
    
    goroutine 1 [semacquire, 44 minutes]:
    sync.runtime_Semacquire(0x2dea182)
            /usr/local/go/src/runtime/sema.go:56 +0x25
    sync.(*WaitGroup).Wait(0x0)
            /usr/local/go/src/sync/waitgroup.go:130 +0x71
    golang.org/x/sync/errgroup.(*Group).Wait(0xc001907a40)
            /root/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x27
    github.com/grafana/grafana/pkg/server.(*Server).Run(0xc000f141c0)
            /drone/src/pkg/server/server.go:172 +0x138
    github.com/grafana/grafana/pkg/cmd/grafana-server/commands.executeServer({0x0, 0x0}, {0x7ffcf31a2688, 0x38}, {0x0, 0x0}, {0x2db936d, 0x7}, 0x0, {{0x333f51c, ...}, ...})
            /drone/src/pkg/cmd/grafana-server/commands/cli.go:184 +0x7dc
    github.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x333f51c, 0x5}, {0x3340e50, 0xa}, {0x333f514, 0x4}, {0x3340e40, 0xa}})
            /drone/src/pkg/cmd/grafana-server/commands/cli.go:107 +0x785
    main.main()
            /drone/src/pkg/cmd/grafana-server/main.go:16 +0xc5
    
    goroutine 168 [chan receive]:
    github.com/golang/glog.(*loggingT).flushDaemon(0xc000122480)
            /root/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x6a
    created by github.com/golang/glog.init.0
            /root/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x1c5
    
    goroutine 146 [select]:
    go.opencensus.io/stats/view.(*worker).start(0xc000410180)
            /root/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xb9
    created by go.opencensus.io/stats/view.init.0
            /root/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x92
    
    goroutine 245 [select, 4 minutes]:
    github.com/patrickmn/go-cache.(*janitor).Run(0xc000567ff0, 0xc0000f0ba0)
            /root/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0x89
    created by github.com/patrickmn/go-cache.runJanitor
            /root/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0xf2
    
    goroutine 246 [select, 44 minutes]:
    database/sql.(*DB).connectionOpener(0xc000f0d380, {0x3404b08, 0xc000c2c9c0})
            /usr/local/go/src/database/sql/sql.go:1196 +0x93
    created by database/sql.OpenDB
            /usr/local/go/src/database/sql/sql.go:794 +0x188
    
    goroutine 247 [select, 44 minutes]:
    database/sql.(*DB).connectionCleaner(0xc000f0d380, 0x0)
            /usr/local/go/src/database/sql/sql.go:1068 +0xbd
    created by database/sql.(*DB).startCleanerLocked
            /usr/local/go/src/database/sql/sql.go:1055 +0x105
    
    goroutine 410 [select, 14 minutes]:
    github.com/prometheus/alertmanager/nflog.(*Log).run(0xc001b56e80)
            /root/go/pkg/mod/github.com/prometheus/alertmanager@v0.23.1-0.20211116083607-e2a10119aaf7/nflog/nflog.go:373 +0x197
    created by github.com/prometheus/alertmanager/nflog.New
            /root/go/pkg/mod/github.com/prometheus/alertmanager@v0.23.1-0.20211116083607-e2a10119aaf7/nflog/nflog.go:322 +0x274
    
    goroutine 148 [semacquire, 44 minutes]:
    sync.runtime_Semacquire(0x0)
            /usr/local/go/src/runtime/sema.go:56 +0x25
    sync.(*WaitGroup).Wait(0xc000587798)
            /usr/local/go/src/sync/waitgroup.go:130 +0x71
    github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).Run(0xc0017367e0, {0x3404b08, 0xc000f34000})
            /drone/src/pkg/services/ngalert/schedule/schedule.go:177 +0x15d
    github.com/grafana/grafana/pkg/services/ngalert.(*AlertNG).Run.func1()
            /drone/src/pkg/services/ngalert/ngalert.go:175 +0x34
    golang.org/x/sync/errgroup.(*Group).Go.func1()
            /root/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
    created by golang.org/x/sync/errgroup.(*Group).Go
            /root/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
    
    goroutine 250 [chan send, 44 minutes]:
    github.com/grafana/grafana/pkg/services/alerting.(*Ticker).run(0xc000632370)
            /drone/src/pkg/services/alerting/ticker.go:49 +0xf3
    created by github.com/grafana/grafana/pkg/services/alerting.NewTicker
            /drone/src/pkg/services/alerting/ticker.go:39 +0x185
    
    goroutine 266 [sleep]:
    time.Sleep(0x3b9aca00)
            /usr/local/go/src/runtime/time.go:193 +0x12e
    github.com/centrifugal/centrifuge.(*historyHub).expireStreams(0xc00043e400)
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/broker_memory.go:208 +0x38
    created by github.com/centrifugal/centrifuge.(*historyHub).runCleanups
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/broker_memory.go:164 +0x5f
    
    goroutine 267 [select]:
    github.com/FZambia/eagle.(*Eagle).aggregate(0xc000455500)
            /root/go/pkg/mod/github.com/!f!zambia/eagle@v0.0.1/eagle.go:210 +0x85
    created by github.com/FZambia/eagle.New
            /root/go/pkg/mod/github.com/!f!zambia/eagle@v0.0.1/eagle.go:66 +0x18f
    
    goroutine 172 [chan receive, 44 minutes]:
    github.com/oklog/run.(*Group).Run(0xc001b75760)
            /root/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:43 +0x7c
    github.com/prometheus/alertmanager/inhibit.(*Inhibitor).Run(0xc0006ac070)
            /root/go/pkg/mod/github.com/prometheus/alertmanager@v0.23.1-0.20211116083607-e2a10119aaf7/inhibit/inhibit.go:108 +0x332
    github.com/grafana/grafana/pkg/services/ngalert/notifier.(*Alertmanager).applyConfig.func2()
            /drone/src/pkg/services/ngalert/notifier/alertmanager.go:428 +0x68
    created by github.com/grafana/grafana/pkg/services/ngalert/notifier.(*Alertmanager).applyConfig
            /drone/src/pkg/services/ngalert/notifier/alertmanager.go:426 +0xbd3
    
    goroutine 171 [select]:
    github.com/prometheus/alertmanager/dispatch.(*Dispatcher).run(0xc00057dad0, {0x33dd680, 0xc001bab8c0})
            /root/go/pkg/mod/github.com/prometheus/alertmanager@v0.23.1-0.20211116083607-e2a10119aaf7/dispatch/dispatch.go:155 +0x1e5
    github.com/prometheus/alertmanager/dispatch.(*Dispatcher).Run(0xc00057dad0)
            /root/go/pkg/mod/github.com/prometheus/alertmanager@v0.23.1-0.20211116083607-e2a10119aaf7/dispatch/dispatch.go:144 +0x125
    github.com/grafana/grafana/pkg/services/ngalert/notifier.(*Alertmanager).applyConfig.func1()
            /drone/src/pkg/services/ngalert/notifier/alertmanager.go:422 +0x68
    created by github.com/grafana/grafana/pkg/services/ngalert/notifier.(*Alertmanager).applyConfig
            /drone/src/pkg/services/ngalert/notifier/alertmanager.go:420 +0xb79
    
    goroutine 272 [select]:
    github.com/centrifugal/centrifuge.(*Node).initMetrics.func1()
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/node.go:308 +0x9f
    created by github.com/centrifugal/centrifuge.(*Node).initMetrics
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/node.go:306 +0x21d
    
    goroutine 69 [syscall, 44 minutes]:
    os/signal.signal_recv()
            /usr/local/go/src/runtime/sigqueue.go:169 +0x98
    os/signal.loop()
            /usr/local/go/src/os/signal/signal_unix.go:24 +0x19
    created by os/signal.Notify.func1.1
            /usr/local/go/src/os/signal/signal.go:151 +0x2c
    
    goroutine 273 [select]:
    github.com/centrifugal/centrifuge.(*Node).sendNodePing(0xc000782000)
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/node.go:323 +0x90
    created by github.com/centrifugal/centrifuge.(*Node).Run
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/node.go:203 +0x250
    
    goroutine 274 [select]:
    github.com/centrifugal/centrifuge.(*Node).cleanNodeInfo(0xc000782000)
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/node.go:337 +0x9a
    created by github.com/centrifugal/centrifuge.(*Node).Run
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/node.go:204 +0x292
    
    goroutine 275 [select]:
    github.com/centrifugal/centrifuge.(*Node).updateMetrics(0xc000782000)
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/node.go:278 +0x93
    created by github.com/centrifugal/centrifuge.(*Node).Run
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/node.go:205 +0x2d4
    
    goroutine 276 [sync.Cond.Wait, 41 minutes]:
    sync.runtime_notifyListWait(0xc000b96850, 0x41)
            /usr/local/go/src/runtime/sema.go:513 +0x13d
    sync.(*Cond).Wait(0xc000588778)
            /usr/local/go/src/sync/cond.go:56 +0x8c
    github.com/centrifugal/centrifuge/internal/dissolve.(*queueImpl).Wait(0xc000454bd0)
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/internal/dissolve/queue.go:139 +0x5c
    github.com/centrifugal/centrifuge/internal/dissolve.(*Dissolver).runWorker(0xc000110498)
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/internal/dissolve/dissolve.go:52 +0x34
    created by github.com/centrifugal/centrifuge/internal/dissolve.(*Dissolver).Run
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/internal/dissolve/dissolve.go:31 +0x2c
    
    goroutine 277 [sync.Cond.Wait, 41 minutes]:
    sync.runtime_notifyListWait(0xc000b96850, 0x40)
            /usr/local/go/src/runtime/sema.go:513 +0x13d
    sync.(*Cond).Wait(0xc000583f78)
            /usr/local/go/src/sync/cond.go:56 +0x8c
    github.com/centrifugal/centrifuge/internal/dissolve.(*queueImpl).Wait(0xc000454bd0)
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/internal/dissolve/queue.go:139 +0x5c
    github.com/centrifugal/centrifuge/internal/dissolve.(*Dissolver).runWorker(0xc000110498)
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/internal/dissolve/dissolve.go:52 +0x34
    created by github.com/centrifugal/centrifuge/internal/dissolve.(*Dissolver).Run
            /root/go/pkg/mod/github.com/centrifugal/centrifuge@v0.18.8/internal/dissolve/dissolve.go:31 +0x2c

    <ad infinitum>

**Environment**:
- Grafana version: 8.3.2
- Data source type & version: Elasticsearch 7.16.1
- OS Grafana is installed on: CentOS7
- User OS & Browser: Windows/Chrome
- Grafana plugins: N/A
- Others:

### PR DESCRIPTION
**Pull request by diegommm**
**What is this feature?**

A fix for a data race described in #44509. This is due to accessing `*ini.File` with `BlockMode` set to `false`. A suggested approach would be adding a mutex to `DynamicSection`, but that would not be enough since that depends on the internals of `*ini.File` not racing while accessing keys of different sections.

**Who is this feature for?**

Everyone.

**Which issue(s) does this PR fix?**:

Fixes #44509

**Special notes for your reviewer:**

Checks:
- [x] It works as expected from a user's perspective (tested locally).
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/setting/setting.go [hunk 1]
```diff
@@ -819,6 +820,9 @@ func (cfg *Cfg) loadSpecifiedConfigFile(configFile string, masterFile *ini.File)
 		return fmt.Errorf("failed to parse %q: %w", configFile, err)
 	}
 
+	// micro-optimization since we don't need to share this ini file. In
+	// general, prefer to leave this flag as true as it is by default to prevent
+	// data races
```
Comment (papagian) [inline pkg/setting/setting.go:825]: what preventing us from setting it `true`?

Comment (diegommm) [reply pkg/setting/setting.go:825]: Nothing at all, I can remove it and move the comment to another place if you think that would be better or more consistent. It's just that I noticed with git blame that it was several folks who set the flag to false, so I thought it would be good to leave this one and explain why it's ok here and not in general. That with the hope that if some of them come back and want to set another instance to false then they would probably look up what was the name of the frobb name to be changed in the code, see the comment and reconsider.

**Review by zserge — APPROVED** [review]

File: pkg/setting/setting.go (hunk 1 above)
Comment (diegommm) [reply pkg/setting/setting.go:825]: Merging the PR. If you think it would be better to remove this line as well, let me know and I can open a followup PR.
