### PR TITLE
CloudWatch: Fix - make sure dimensions are propagated to alert query editor

### LINKED ISSUE #58280: unified alerting: Cloudwatch queries do not propogate dimensions
**What happened**: I go to create an alert from a panel using Cloudwatch queries.

**What you expected to happen**: The dimensions from the query to be propagated to the alerting screen.

**How to reproduce it (as minimally and precisely as possible)**: Run latest version of Grafana locally or in Docker. Create a dashboard with a panel that queries a Cloudwatch data source. Save it and then try to create an alert from it.

https://user-images.githubusercontent.com/43791257/200081611-8a8567ea-b893-4f19-bf78-f48a1ea30d4b.mov

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.3
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: -
- Others: -

### PR DESCRIPTION
**Pull request by conorevans**
Signed-off-by: Conor Evans <coevans@tcd.ie>

**Which issue(s) does this PR fix?**: 

Fixes #58280 

**Special notes for your reviewer**:

I'm not sure if Cloudwatch can return `string`s as the value for Dimensions. From what I can see, they're always arrays with a single string. However, I've kept the existing code in place and just modified it to account for that latter case.

Before: 

https://user-images.githubusercontent.com/43791257/200082057-1c3fea53-6aae-4167-80b4-76e40b24bd48.mov

After:

https://user-images.githubusercontent.com/43791257/200082074-3fb3bf89-76e3-40f2-b6b3-702ddce16433.mov

### CODE REVIEW

**Comment by sunker** [comment]
Thanks a lot for reporting this issue and proposing a solution @conorevans!

I wonder if the problem can be solved with a different approach though. The alerting engine doesn't support template variables, so before the alerting UI is loaded, it calls [`interpolateVariablesInQuery`](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloudwatch/datasource.ts#L118) in the data source file. It looks like through a pretty complicated chain of calls, `expandVariableToArray` is being called to interpolate any template variables in the dimension values prop. This method should not convert the dimension value to an array in case the value itself was not a template variable. Would you like to try and come up with a fix using that approach? 

Thanks again!

**Comment by conorevans** [comment]
Hi @sunker thanks for the review and pointing me in a helpful direction! Yeah there's quite the chaining happening here, makes for some gnarly debugging 😅 (esp as I'm no TS whiz).

I've implemented your feedback and it looks cleaner + set properly closer to source than my original tack. Please feel free to suggest any changes or apply them yourself. Cheers

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchRequest.ts [hunk 1]
```diff
@@ -50,13 +50,18 @@ export abstract class CloudWatchRequest {
...
 
-      const newValues = this.expandVariableToArray(value, scopedVars);
+      const newValues = this.expandVariableToArrayIfTemplated(value, scopedVars);
       return { ...result, [key]: newValues };
     }, {});
   }
 
   // get the value for a given template variable
-  expandVariableToArray(value: string, scopedVars: ScopedVars): string[] {
+  expandVariableToArrayIfTemplated(value: string, scopedVars: ScopedVars): string | string[] {
```
Comment (sunker) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchRequest.ts:59]: You don't need to change the name of this method - if it's a variable it's always templated.

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchRequest.ts [hunk 2]
```diff
@@ -50,13 +50,18 @@ export abstract class CloudWatchRequest {
...
+    // If no template variables, simply return the value.
+    if (!this.templateSrv.getVariables.length) {
```
Comment (sunker) [inline public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchRequest.ts:61]: `getVariables` will return variables also for other data sources in the current dashboard, so think you can remove this if statement. What you can instead is to simply return the string on line 73 rather than putting it in an array. If we reach line 73, we know it's not a variable.

File: public/app/plugins/datasource/cloudwatch/utils/datalinks.ts [hunk 3]
```diff
@@ -16,7 +16,7 @@ export async function addDataLinksToLogsResponse(
   request: DataQueryRequest<CloudWatchQuery>,
   range: TimeRange,
   replaceFn: ReplaceFn,
-  getVariableValueFn: (value: string, scopedVars: ScopedVars) => string[],
+  getVariableValueFn: (value: string, scopedVars: ScopedVars) => string | string[],
```
Comment (sunker) [inline public/app/plugins/datasource/cloudwatch/utils/datalinks.ts:19]: Don't think you need to make any changes in this file.

**Review by sunker — COMMENTED** [review]
Thanks! Added a few comments. Also, would you be able to add a test for the `interpolateVariablesInQueries` method? There's already a pattern for testing this method [here](https://github.com/grafana/grafana/blob/b1bfae035022d6cedd89014744073e89741e4738/public/app/plugins/datasource/cloudwatch/datasource.test.ts#L251) in the datasource test file. If you could add a scenario with something like `should not change structure of dimension prop if its not a template variable`, that would be great!

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchRequest.ts (hunk 1 above)
Comment (conorevans) [reply public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchRequest.ts:59]: I added the `IfTemplated` because I figured changing the method signature to return `string | string[]` means that there should be some indication that it won't always strictly be an Array (`string[]`), but then again I guess the typing already says that.

File: public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchRequest.ts (hunk 2 above)
Comment (conorevans) [reply public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchRequest.ts:61]: Yeah I had that originally but wasn't sure if it could reach that case otherwise. Will amend 👍

File: public/app/plugins/datasource/cloudwatch/utils/datalinks.ts (hunk 3 above)
Comment (conorevans) [reply public/app/plugins/datasource/cloudwatch/utils/datalinks.ts:19]: This `addDataLinksToLogsResponse` is called [here](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts#L153) using `expandVariableToArray` as its `getVariableValueFn`. So changing the return signature of `expandVariableToArray` means we need to change it here too

Comment (sunker) [reply public/app/plugins/datasource/cloudwatch/utils/datalinks.ts:19]: Okay I see!

**Comment by conorevans** [comment]
@sunker implemented that batch of feedback! I tried to add a test via a few different permutations but I could not find a satisfactory way of accessing the dimensions of the interpolated queries. Do you mind taking a look? I'm happy for you to push to my PR

**Comment by sunker** [comment]
> @sunker implemented that batch of feedback! I tried to add a test via a few different permutations but I could not find a satisfactory way of accessing the dimensions of the interpolated queries. Do you mind taking a look? I'm happy for you to push to my PR

Test added!

**Comment by conorevans** [comment]
> > @sunker implemented that batch of feedback! I tried to add a test via a few different permutations but I could not find a satisfactory way of accessing the dimensions of the interpolated queries. Do you mind taking a look? I'm happy for you to push to my PR
> 
> Test added!

Thank you 😄

**Comment by sunker** [comment]
@conorevans I'll look into the failing tests as soon as I can!

**Comment by sunker** [comment]
Sorry @conorevans, dropped the ball on this for PR for a while. 

The path that I suggested in this PR, making changes to datasource.interpolateVariablesInQuery, had side effects that there are not easy fixes for. I rebased and removed all commits except for the first one, which includes you initial fix. Also added a unit test. 

Thanks a lot for contributing and again sorry for the delay!

**Review by sunker — APPROVED** [review]

**Comment by conorevans** [comment]
All okay @sunker ! Thanks for your efforts
