### PR TITLE
Explore: Add t * keybindings to change time range

### LINKED ISSUE #32404: Time range keyboard shortcuts do not work in explore
**What happened**:

When using Explore, moving the time range via keyboard shortcuts does not work for me.
Non of the following three shorcuts work in Explore, they do in dashboards:

grafik

**What you expected to happen**:

The keyboard shortcuts should also work in explore.

**How to reproduce it (as minimally and precisely as possible)**:

- Go to <https://play.grafana.org/explore>
- Get some data or not
- Try any of the keyboard shortcuts mentioned above
- [Direct Link](https://play.grafana.org/explore?orgId=1&left=%5B%221616997652986%22,%221617004852986%22,%22demo.robustperception.io%22,%7B%22exemplar%22:false,%22expr%22:%221%22,%22requestId%22:%22Q-5183b2ac-63f1-4e8e-948b-98fab09c6039-0A%22,%22instant%22:false,%22range%22:true%7D%5D)

**Anything else we need to know?**:

Additionally, the Zoom Out Button tooltip incorrectly (?) shows `Ctrl+Z` as hotkey:

grafik

**Environment**:
- Grafana version: `Grafana v7.5.1 (4dffb875cf)`
- Data source type & version: prometheus
- OS Grafana is installed on: <https://play.grafana.org>
- User OS & Browser: Windows 10 2020H2, Firefox 86.0.1
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by gelicia**
**What this PR does / why we need it**:
The dashboard has several keybindings to change the time range. This adds the same keybindings into the explore page. In the event the explore page is in split view, the keybindings will affect the right side. If the time ranges are synced, it will affect both.

**Which issue(s) this PR fixes**:
Fixes #32404 

**Special notes for your reviewer**:
My goal for this PR was to stay as close to what exists for Dashboard as possible. To this end, I wanted to re-use the existing events and subscribers for the explore keybindings. The event subscribers for it are all in [TimeSrv](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/services/TimeSrv.ts#L36) which is a Dashboard service but Explore already uses `TimeSrv`. To help indicate that TimeSrv is used by more than just Dashboards, we opted to change the dashboard model to a more generically named TimeModel since we use relatively few things inside TimeSrv (Thanks to @ifrost for the assistance on that). 

One thing that came up is we needed to skip the URL changes since dashboard has the from and to URL params in a different location, so I broke out the events to clarify if a URL edit would be needed or not, so we could specify to not edit the URL from `TimeSrv` if the event was coming from the Explore page - the explore function updates the URL in the way you'd expect.

In building out the e2e test for this, I wanted an easy to use way to parse the URL to ensure that only explores URL was being altered and not including the params that dashboard uses. ~~I found the utility function in @grafana/data that worked perfectly but found it tricky to set up a link that our e2e directory could use. In the end I think it makes sense for that e2e directory to function independently, so I added the utility function to the @grafana/e2e package and expose it via the `e2e` object.~~ I used [URLSearchParams.get](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get) for this

It's also worth noting that the keybindings are reset with every route change so there is no need to clean this up explicitly.
https://github.com/grafana/grafana/blob/main/public/app/core/navigation/GrafanaRoute.tsx#L15
https://github.com/grafana/grafana/blob/main/public/app/core/services/keybindingSrv.ts#L27

### CODE REVIEW

File: public/app/features/explore/state/time.ts [hunk 1]
```diff
@@ -96,13 +97,18 @@ export const updateTime = (config: {
...
-        timeZone,
-      })
-    );
+    const dashboardModel = new DashboardModel({
+      time: range.raw,
+      refresh: false,
+      timeZone,
+    });
+
+    dashboardModel.events.subscribe(TimeRangeUpdatedEvent, (event) => {
```
Comment (gelicia) [inline public/app/features/explore/state/time.ts:106]: I'm not sure if adding this subscription to a new instantiation with every time update will cause issues at some point. I assume if creating a new dashboardModel.events event bus every update caused us problems they would have shown themselves by now. There is a destroy() method in the dashboard model but I think we have to call it explicitly. 

Another alternative was allowing us to override the dashboard model's update time function with the `updateTimeRange` function but we would rather keep changes as contained as possible.

File: e2e/various-suite/explore.spec.ts [hunk 2]
```diff
@@ -1,4 +1,5 @@
 import { e2e } from '@grafana/e2e';
+import { urlUtil } from '../../packages/grafana-data/src/utils/url';
```
Comment (ifrost) [inline e2e/various-suite/explore.spec.ts:2]:
```suggestion
import { urlUtil } from '@grafana/data';
```

File: public/app/features/explore/state/time.ts [hunk 3]
```diff
@@ -17,6 +17,7 @@ import { getTimeSrv } from '../../dashboard/services/TimeSrv';
 import { DashboardModel } from 'app/features/dashboard/state';
 import { runQueries } from './query';
 import { syncTimesAction, stateSave } from './main';
+import { TimeRangeUpdatedEvent } from '@grafana/runtime/src/services/appEvents';
```
Comment (ifrost) [inline public/app/features/explore/state/time.ts:20]:
```suggestion
import { TimeRangeUpdatedEvent } from '@grafana/runtime';
```

File: public/app/features/explore/state/time.ts (hunk 1 above)
Comment (ifrost) [reply public/app/features/explore/state/time.ts:106]: This should be cleaned by garbage collector, but I agree it might be error prone.

Maybe we could do something similar you did with overrides and decouple `TimeSrv` from `DashboardModel`? At the moment we hack it to use in Explore. `TimeSrv` does not require full `DashboardModel`, just a subset of time-related properties so we could have:

```diff
export class TimeSrv {
  ...
- dashboard?: DashboardModel;
+  timeModel?: TimeModel;
}

interface TimeModel {
  fiscalYearStartMonth?: number;
  refresh: any;
  timepicker: any;
  getTimezone(): TimeZone;
  timeRangeUpdated(timeRange: TimeRange): void;
}
```

That would allow us to pass custom object, e.g. `ExploreTimeModel`, not `DashboardModel`. (it would just need to implement `getTimezone` as `timeRangeUpdated` has to be custom anyway).

In future the logic to update the URL could be decoupled as well. At the moment is dashboards-specific, but could be moved to `DashboardModel` and `ExploreTimeModel`.

File: e2e/various-suite/explore.spec.ts (hunk 2 above)
Comment (gelicia) [reply e2e/various-suite/explore.spec.ts:2]: @ifrost I tried this and webpack has an issue on a seemingly unrelated file. Have you ever ran into this before? 

`Webpack Compilation Error
Module not found: Error: Can't resolve './FieldConfigOptionsRegistry' in '/Users/kristinadurivage/development/grafana/packages/grafana-data/src/field'`

Comment (gelicia) [reply e2e/various-suite/explore.spec.ts]: I ended up thinking that it didnt make a lot of sense to bring in that whole library for one utility function. Instead, anticipating we may want to test on URL changes more with cypress, I moved the utility function over and exposed it so it can be used by cypress tests from our e2e package.

File: packages/grafana-e2e/src/support/url.ts [hunk 4]
```diff
@@ -12,3 +12,60 @@ export const getDashboardUid = (url: string): string => {
     return matches[1];
   }
 };
+
+/**
+ * Parses an escaped url query string into key-value pairs.
+ * Attribution: Code dervived from https://github.com/angular/angular.js/master/src/Angular.js#L1396
+ * @returns {Object.<string,boolean|Array>}
+ */
+export function parseKeyValue(keyValue: string) {
```
Comment (gelicia) [inline packages/grafana-e2e/src/support/url.ts:21]: I ended up just copying this utility over from grafana-data - for one, cypress really didn't like us refering to that package (and it honestly didn't make sense to refer to other packages in our test definitions) and for two, it didn't seem to make sense to add in links to the entire grafana-data package for one utility function. This does make some redundant code, but it keeps everything separated more which will probably be good. I can see us continuing to want to test that actions in the UI affect the URL as expected as well.

Comment (ifrost) [reply packages/grafana-e2e/src/support/url.ts:21]: Makes sense 👍 I wonder if we could avoid duplication by using URLSearchParams, see comment here https://github.com/grafana/grafana/pull/45020#discussion_r804598362. Though this might be a recurring problem if there are utilities that are not Grafana specific but still useful in testing.

File: e2e/various-suite/explore.spec.ts (hunk 2 above)
Comment (gelicia) [reply e2e/various-suite/explore.spec.ts]: This works perfectly - I didn't know about that one! Thanks!

File: public/app/features/dashboard/services/TimeSrv.ts [hunk 5]
```diff
@@ -7,38 +7,47 @@ import {
...
 import { getShiftedTimeRange, getZoomedTimeRange } from 'app/core/utils/timePicker';
 import { config } from 'app/core/config';
 import { getRefreshFromUrl } from '../utils/getRefreshFromUrl';
 import { locationService } from '@grafana/runtime';
-import { AbsoluteTimeEvent, ShiftTimeEvent, ShiftTimeEventPayload, ZoomOutEvent } from '../../../types/events';
+import { AbsoluteTimeEvent, ShiftTimeEvent, ShiftTimeEventDirection, ZoomOutEvent } from '../../../types/events';
 import { contextSrv, ContextSrv } from 'app/core/services/context_srv';
 import appEvents from 'app/core/app_events';
 
+interface TimeModel {
```
Comment (ifrost) [inline public/app/features/dashboard/services/TimeSrv.ts:21]: One more thing - we need to add `DasboardModel implements TimeModel` to DashboardModel

**Review by ifrost — CHANGES_REQUESTED** [review]

**Review by ifrost — APPROVED** [review]
Looks awesome! 🚀

**Comment by ifrost** [comment]
@grafana/user-essentials are you okay with the proposed changes?

File: public/app/core/services/keybindingSrv.ts [hunk 6]
```diff
@@ -171,6 +171,24 @@ export class KeybindingSrv {
     this.bind(keyArg, withFocusedPanel(fn));
   }
 
+  setupTimeRangeBindings(updateUrl = true) {
+    this.bind('t z', () => {
+      appEvents.publish(new ZoomOutEvent({ scale: 2, updateUrl: updateUrl }));
```
Comment (kaydelaney) [inline public/app/core/services/keybindingSrv.ts:176]: Nit: Can use property shorthand syntax
```suggestion
      appEvents.publish(new ZoomOutEvent({ scale: 2, updateUrl }));
```

**Review by kaydelaney — APPROVED** [review]
Looks great! Just a small nitpick.

File: public/app/core/services/keybindingSrv.ts (hunk 6 above)
Comment (gelicia) [reply public/app/core/services/keybindingSrv.ts]: Sounds good!

**Comment by hugohaggmark** [comment]
>In building out the e2e test for this, I wanted an easy to use way to parse the URL to ensure that only explores URL was being altered and not including the params that dashboard uses. I found the utility function in @grafana/data that worked perfectly but found it tricky to set up a link that our e2e directory could use. In the end I think it makes sense for that e2e directory to function independently, so I added the utility function to the @grafana/e2e package and expose it via the e2e object.

I can't see the change mentioned above in this PR? 
But you're absolutely right the `e2e` packages should not have dependencies on other Grafana packages. The only exception is that e2e has a dependency on e2e-selectors, which is ok 👍

**Comment by gelicia** [comment]
> > In building out the e2e test for this, I wanted an easy to use way to parse the URL to ensure that only explores URL was being altered and not including the params that dashboard uses. I found the utility function in @grafana/data that worked perfectly but found it tricky to set up a link that our e2e directory could use. In the end I think it makes sense for that e2e directory to function independently, so I added the utility function to the @grafana/e2e package and expose it via the e2e object.
> 
> I can't see the change mentioned above in this PR? But you're absolutely right the `e2e` packages should not have dependencies on other Grafana packages. The only exception is that e2e has a dependency on e2e-selectors, which is ok 👍

Yep sorry, That changed and I forgot to update the description. I ended up using a utility function already in javascript based on @ifrost 's feedback.

File: public/app/features/dashboard/services/TimeSrv.ts [hunk 7]
```diff
@@ -276,20 +276,19 @@ export class TimeSrv {
     this.setAutoRefresh(this.previousAutoRefresh);
   }
 
-  setTime(time: RawTimeRange, fromRouteUpdate?: boolean) {
+  setTime(time: RawTimeRange, updateUrl = true) {
```
Comment (torkelo) [inline public/app/features/dashboard/services/TimeSrv.ts:279]: this inverts the logic here, which means all callers needs to pass false, when they previously passed true

File: public/app/features/dashboard/services/TimeSrv.ts [hunk 8]
```diff
@@ -276,20 +276,19 @@ export class TimeSrv {
...
       this.setAutoRefresh(false);
-    } else if (this.oldRefresh && this.oldRefresh !== this.dashboard?.refresh) {
+    } else if (this.oldRefresh && this.oldRefresh !== this.timeModel?.refresh) {
       this.setAutoRefresh(this.oldRefresh);
       this.oldRefresh = null;
     }
 
-    // update url
-    if (fromRouteUpdate !== true) {
+    if (updateUrl === true) {
```
Comment (gelicia) [inline public/app/features/dashboard/services/TimeSrv.ts:291]: @torkelo I changed the logic in the function to be inverted as well. Is there a bug with this I can look at?

Comment (torkelo) [reply public/app/features/dashboard/services/TimeSrv.ts:291]: @gelicia yea, https://github.com/grafana/grafana/pull/48657 

But no worries will be fixed in the next patch release. Wish we had better unit tests for this part (TimeSrv is very messy, should be refactored to redux actions)

Comment (gelicia) [reply public/app/features/dashboard/services/TimeSrv.ts:291]: Thank you for fixing my bug 😅
