### PR TITLE
Histogram: Fix Tooltip placement issue

### LINKED ISSUE #103686: Histogram: Tooltip for wrong bucket shown in some cases
Noticed that when hovering mouse on the _right half_ of a bucket column, tooltip is shown for the next bucket not the one being hovered.

https://github.com/user-attachments/assets/25a23a85-ae07-4fe9-9093-d71c699caecd

### PR DESCRIPTION
**Pull request by wassafshahzad**
**What is this feature?**
This PR resolves a bug with the tooltip on the histogram graph. Before this fix the tooltip would either stop rendering when the cursor moves across a bar or render the wrong value. This is caused by an inaccurate calculation of the nearest datapoint used as a reference for the tool tip. This PR fixes the bug in the calculation by using the center of the bar (on the x-axis) as a reference point and not the start

**Why do we need this feature?**

This bug is in the UI of the histogram and can be jarring to the user.

**Who is this feature for?**

Any user of the histogram feature.

**Which issue(s) does this PR fix?**:

Fixes #103686

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

**Screenshots and Gifs**

Before the fix:

https://github.com/user-attachments/assets/c14181ce-73e0-420b-bed6-65f96ec4bcb7

After the fix:

https://github.com/user-attachments/assets/6dee96da-108f-47fc-b1b1-e72c51720078

### CODE REVIEW

File: public/app/plugins/panel/histogram/Histogram.tsx [hunk 1]
```diff
@@ -204,6 +204,13 @@ const prepConfig = (frame: DataFrame, theme: GrafanaTheme2) => {
       y: false,
       setScale: true,
     },
+    dataIdx: (u, _, closestIdx, xValue) => {
+      let xTiker = u.data[0][closestIdx];
+      if (xValue < xTiker) {
```
Comment (leeoniya) [inline public/app/plugins/panel/histogram/Histogram.tsx]: variable name is a bit odd, let's just inline the condition?

```suggestion
      if (xValue < u.data[0][closestIdx]) {
```

**Comment by leeoniya** [comment]
looks good, thanks!

left one comment to address.

File: public/app/plugins/panel/histogram/Histogram.tsx (hunk 1 above)
Comment (wassafshahzad) [reply public/app/plugins/panel/histogram/Histogram.tsx]: Sure, I will inline the condition. The logic behind the  variable names are x-axis Value at current positions and x axis Tick value at current position.

Comment (leeoniya) [reply public/app/plugins/panel/histogram/Histogram.tsx]: > and x axis Tick value at current position.

in high density histograms you won't have a tick for every bar even though you can hover every bar :)

Comment (wassafshahzad) [reply public/app/plugins/panel/histogram/Histogram.tsx]: > > and x axis Tick value at current position.
> 
> in high density histograms you won't have a tick for every bar even though you can hover every bar :)

My bad, This isnt the tick value as in the rendered tick shown under the histogram. This is the value from the u.data list based on the closetIdx which would be the starting point of every bar, I hope. Even in high density histogram the values in u.data should be available right ? 

The reason this works is because when the closestIdx overshoots (_because the reference point is the start not the center of the bar)_ and the reference value becomes the start of the next bar and we can detect and correct the overshoot by checking if the current value < reference value. Since the current value should always be <= to the reference value of the corresponding  bar

Comment (leeoniya) [reply public/app/plugins/panel/histogram/Histogram.tsx]: heh, i get it (i wrote uPlot). the code makes sense.

i was just commenting on the variable name since you said the name was derived from "tick" :)

Comment (wassafshahzad) [reply public/app/plugins/panel/histogram/Histogram.tsx]: > heh, i get it (i wrote uPlot). the code makes sense.
> 
> i was just commenting on the variable name since you said the name was derived from "tick" :)

Yeah that was my bad and I wrote the explanation just to keep a history of sorts.

**Comment by wassafshahzad** [comment]
> looks good, thanks!
> 
> left one comment to address.

@leeoniya The pre-commit hooks don't like the inline condition

**Review by leeoniya — DISMISSED** [review]

**Review by leeoniya — APPROVED** [review]
