### PR TITLE
Cloud Monitoring: Fix missing data when result is paginated

### LINKED ISSUE #51395: Cloud Monitoring: Missing data for large responses
Hello,

So recently i've noticed an issue when whenever time range is exceeded to 6 hours or more - Grafana is missing Data -  It works perfectly fine when we reduce the time range to 1 hour or 2 hour, not sure if this has anything to do with the data being captured by the Log Based Metric in Stackdriver.

Recording of Missing Record comparison between Stackdriver Log Based metric and Grafana using the same metric
Missing Records in 6Hour Range

- Questions should be posted to: https://community.grafana.com/t/grafana-dashboard-is-missing-fields-when-compared-with-stackdriver/67708

**What happened**: Grafana Dashboard is missing fields when compared with Stackdriver using same log based metric

**What you expected to happen**: Display same number of records as it does on Stackdriver since the source of Data is same log based metric

**How to reproduce it (as minimally and precisely as possible)**: Have a Log Based metric in Google Cloud Monitoring - with Huge amount of data on daily basis let's say atleast 2000 records on daily basis and then you'd see the data displayed through Stackdriver vs Grafana will have difference in number of records.

**Anything else we need to know?**: Haven't gotten any far to share further details

**Environment**:
- Grafana version: v8.5.1
- Data source type & version: Google Cloud Monitoring 
- OS Grafana is installed on: Linux
- User OS & Browser:  Windows & Chrome
- Grafana plugins: Stackdriver/Google Cloud Monitoring
- Others: N/A

### PR DESCRIPTION
**Pull request by yaelleC**
**What this PR does / why we need it**:
If a Cloud Monitoring returns paginated results the existing code only returns the first page of data.

This PR adds a loop to keep querying until the `nextPageToken` is empty : 
- in `time_series_queries` (code editor)
- in `time_series_filter` (builder)

**Which issue(s) this PR fixes**:

Fixes #51395

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/tsdb/cloudmonitoring/time_series_filter.go [hunk 1]
```diff
@@ -30,54 +30,69 @@ func (timeSeriesFilter *cloudMonitoringTimeSeriesFilter) run(ctx context.Context
...
-				dr.Frames = append(dr.Frames, data.NewFrame(""))
-			}
-			firstFrame := dr.Frames[0]
-			if firstFrame.Meta == nil {
-				firstFrame.SetMeta(&data.FrameMeta{
-					Custom: map[string]interface{}{
-						"alignmentPeriod": seconds,
-					},
-				})
+	for first || d.NextPageToken != "" {
```
Comment (andresmgot) [inline pkg/tsdb/cloudmonitoring/time_series_filter.go:42]: nit: a bit of a style change, you can move all the logic to do a request to a function so this code is cleaner (I'm not including params or errors):

```go
d := doRequest(...)
nextPageToken := d.NextPageToken
for nextPageToken != "" {
  nextPage := doRequest(..., nextPageToken)
  nextPageToken := nextPage.NextPageToken
  d.TimeSeries = append(d.TimeSeries, nextPage.TimeSeries...)
}

**Review by andresmgot — APPROVED** [review]
LGTM! Just a minor style suggestion

File: pkg/tsdb/cloudmonitoring/time_series_filter.go (hunk 1 above)
Comment (asimpson) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:42]: I was going to add the same comment! :joy:

I know you didn't necessarily author this entire block but this section could be cleaned up to left-align "the happy path" as explained [here][mat] and [here][go wiki].

[go wiki]: https://github.com/golang/go/wiki/CodeReviewComments#indent-error-flow
[mat]: https://medium.com/@matryer/line-of-sight-in-code-186dd7cdea88

**Review by asimpson — APPROVED** [review]
LGTM! :trophy:

File: pkg/tsdb/cloudmonitoring/time_series_filter.go (hunk 1 above)
Comment (yaelleC) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go:42]: Neat! Thanks both, I'll make the changes

Comment (yaelleC) [reply pkg/tsdb/cloudmonitoring/time_series_filter.go]: I've extracted the function , however I have issues with left aligning the happy path @asimpson : I don't see how to do it since there is no possible return in `if` and no `else`. Any idea? 🤔

File: pkg/tsdb/cloudmonitoring/time_series_query.go [hunk 2]
```diff
@@ -35,6 +35,44 @@ func (timeSeriesQuery cloudMonitoringTimeSeriesQuery) appendGraphPeriod(req *bac
...
+	}
+
+	buf, err := json.Marshal(requestBody)
+	if err != nil {
+		return cloudMonitoringResponse{}, err
+	}
+	r, err := s.createRequest(ctx, &dsInfo, path, bytes.NewBuffer(buf))
+	if err != nil {
+		return cloudMonitoringResponse{}, err
+	}
```
Comment (andresmgot) [inline pkg/tsdb/cloudmonitoring/time_series_query.go:53]: you could evaluate creating the request outside of this function and simply modify the `Body` for each page:

```go
	req.Body = io.NopCloser(bytes.NewBuffer(buf))
```

Also (nit), since you don't need to do the nextPageToken management for the first query, you can do that within the `for` loop, not here.

That may save you a bunch of parameters and complexity here but it's just moving things around for style so up to you what you prefer :)

**Review by andresmgot — COMMENTED** [review]
more small suggestions here!

File: pkg/tsdb/cloudmonitoring/time_series_query.go [hunk 3]
```diff
@@ -55,40 +74,43 @@ func (timeSeriesQuery cloudMonitoringTimeSeriesQuery) run(ctx context.Context, r
...
 	span.SetAttributes("from", req.Queries[0].TimeRange.From, attribute.Key("from").String(req.Queries[0].TimeRange.From.String()))
 	span.SetAttributes("until", req.Queries[0].TimeRange.To, attribute.Key("until").String(req.Queries[0].TimeRange.To.String()))
-
 	defer span.End()
-	tracer.Inject(ctx, r.Header, span)
 
-	r = r.WithContext(ctx)
-	res, err := dsInfo.services[cloudMonitor].client.Do(r)
+	requestBody := map[string]interface{}{
+		"query":    timeSeriesQuery.Query,
```
Comment (andresmgot) [inline pkg/tsdb/cloudmonitoring/time_series_query.go:86]: I think there is too much space here and that's what the linter is complaining about

**Review by andresmgot — APPROVED** [review]
:+1:

File: pkg/tsdb/cloudmonitoring/time_series_query.go (hunk 3 above)
Comment (yaelleC) [reply pkg/tsdb/cloudmonitoring/time_series_query.go:86]: oh yes, I just removed the `pageSize` prop, and I forgot to format again 🤦‍♀️

**Comment by yaelleC** [comment]
It took a while to merge as I could not get it to work locally I kept getting an error about an invalid prop when hard coding a `pageSize` property in first request to force pagination.

For future reference: if you do multiple requests with `pageToken` you must have the same `pageSize` property in first and subsequent requests 🤷‍♀️ 

All working well now 👍
