### PR TITLE
Loki: fix timestamp field

### LINKED ISSUE #14599: Explore: Logging throw React key error
0. Explore enabled, local Loki datasource
1. Select a file stream
2. Open JS console

React key errors: `EKundefined{__filename__="/var/log/system.log", job="varlogs"}undefined`

### LINKED ISSUE #14635: Explore: In Logging all timestamps are the same
All timestamps shown in Loki seem to be the same.

I believe the API changed from `timestamp` to `ts`.

### PR DESCRIPTION
**Pull request by davkal**
- timestamp was renamed to `ts` in grafana/loki#152
- renamed here in result transformer and tests

Fixes #14635 
Fixes #14599

### CODE REVIEW

File: public/app/core/logs_model.ts [hunk 1]
```diff
@@ -81,7 +81,9 @@ export interface LogsStream {
 
 export interface LogsStreamEntry {
   line: string;
-  timestamp: string;
+  ts: string;
```
Comment (DanCech) [inline public/app/core/logs_model.ts]: @davkal does this need to be declared optional also?
