### PR TITLE
Search API: Search by folder UID

### LINKED ISSUE #64756: Browse Dashboards: Folders after the first 999 show dashboards from General
**What happened**:

With Search v1, if your Grafana org has more than 999 folders, the folder view will show folders from the default General folder instead of the selected folder.

This is because the search API uses folder _IDs_, whereas the frontend almost exclusively deals with UIDs. To convert the folder UID to ID, it only looks in the first 999 folders. If your folder is not within those 999 folders, the frontend will default to searching the General folder instead.

https://github.com/grafana/grafana/blob/664721720809e85e10c08b3befef111d69713775/public/app/features/search/service/sql.ts#L56-L62

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by joshhunt**
**What is this feature?**

Enhances the Search v1 API to support filtering by folder UID (instead of folder ID)

Fixes https://github.com/grafana/grafana/issues/64756  where folders after the first 999 could show incorrect children

### CODE REVIEW

File: pkg/services/sqlstore/searchstore/filters.go [hunk 1]
```diff
@@ -85,6 +85,14 @@ func (f FolderFilter) Where() (string, []interface{}) {
 	return sqlIDin("dashboard.folder_id", f.IDs)
 }
 
+type FolderUIDFilter struct {
+	UIDs []string
+}
+
+func (f FolderUIDFilter) Where() (string, []interface{}) {
+	return sqlUIDin("folder_uid", f.UIDs)
+}
```
Comment (joshhunt) [inline pkg/services/sqlstore/searchstore/filters.go:94]: I'm struggling with generating the correct SQL filter here. Currently this is making:


```sql
SELECT 
  dashboard.id, 
  dashboard.uid, 
  dashboard.title, 
  dashboard.slug, 
  dashboard_tag.term, 
  dashboard.is_folder, 
  dashboard.folder_id, 
  folder.uid AS folder_uid, 
  folder.slug AS folder_slug, 
  folder.title AS folder_title 
FROM 
  (
    SELECT 
      dashboard.id 
    FROM 
      dashboard 
    WHERE 
      (
        NOT dashboard.is_folder 
        OR dashboard.is_folder
      ) 
      AND dashboard.org_id = ? 
      AND folder_uid IN (?)  -- This is my additional folder UID filter
    ORDER BY 
      dashboard.title ASC 
    LIMIT 
      1000 OFFSET 0
  ) AS ids 
  INNER JOIN dashboard ON ids.id = dashboard.id 
  LEFT OUTER JOIN dashboard AS folder ON folder.id = dashboard.folder_id 
  LEFT OUTER JOIN dashboard_tag ON dashboard.id = dashboard_tag.dashboard_id 
ORDER BY 
  dashboard.title ASC
```

But after trying various things (`dashboard.folder_uid`, `folder_uid`, `folder.uid`), I think I've realised that the folder UID just isn't available in this subquery.

**Comment by joshhunt** [comment]
Will hold off on this until https://github.com/grafana/grafana/pull/63275 is merged

File: pkg/services/sqlstore/searchstore/filters.go (hunk 1 above)
Comment (papagian) [reply pkg/services/sqlstore/searchstore/filters.go]: I pushed a fix

<details>
<summary>Execution plan for example query searching by UID:</summary>

```
 mysql> EXPLAIN 
    -> SELECT
    ->                         dashboard.id,
    ->                         dashboard.uid,
    ->                         dashboard.title,
    ->                         dashboard.slug,
    ->                         dashboard_tag.term,
    ->                         dashboard.is_folder,
    ->                         dashboard.folder_id,
    ->                         folder.uid AS folder_uid,
    ->                         folder.slug AS folder_slug,
    ->                         folder.title AS folder_title  FROM ( SELECT dashboard.id FROM dashboard WHERE (NOT dashboard.is_folder OR dashboard.is_folder) AND dashboard.org_id=1 AND dashboard.folder_id IN (SELECT id FROM dashboard WHERE is_folder = 1 AND org_id = 1 AND uid IN ("bb138916-d6d1-4732-b15b-be462cd85ac0")) ORDER BY dashboard.title ASC LIMIT 1000 OFFSET 0) AS ids
    ->                 INNER JOIN dashboard ON ids.id = dashboard.id
    -> LEFT OUTER JOIN dashboard AS folder ON folder.id = dashboard.folder_id
    ->                 LEFT OUTER JOIN dashboard_tag ON dashboard.id = dashboard_tag.dashboard_id
    ->  ORDER BY dashboard.title ASC;
+----+-------------+---------------+------------+--------+---------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------+-----------------------------+------+----------+------------------------------------+
| id | select_type | table         | partitions | type   | possible_keys                                                                                                                                     | key                                  | key_len | ref                         | rows | filtered | Extra                              |
+----+-------------+---------------+------------+--------+---------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------+-----------------------------+------+----------+------------------------------------+
|  1 | PRIMARY     | <derived2>    | NULL       | ALL    | NULL                                                                                                                                              | NULL                                 | NULL    | NULL                        |  100 |   100.00 | Using temporary; Using filesort    |
|  1 | PRIMARY     | dashboard     | NULL       | eq_ref | PRIMARY                                                                                                                                           | PRIMARY                              | 8       | ids.id                      |    1 |   100.00 | NULL                               |
|  1 | PRIMARY     | folder        | NULL       | eq_ref | PRIMARY                                                                                                                                           | PRIMARY                              | 8       | grafana.dashboard.folder_id |    1 |   100.00 | NULL                               |
|  1 | PRIMARY     | dashboard_tag | NULL       | ref    | IDX_dashboard_tag_dashboard_id                                                                                                                    | IDX_dashboard_tag_dashboard_id       | 8       | ids.id                      |    2 |   100.00 | NULL                               |
|  2 | DERIVED     | dashboard     | NULL       | const  | PRIMARY,UQE_dashboard_org_id_folder_id_title,UQE_dashboard_org_id_uid,IDX_dashboard_org_id,IDX_dashboard_org_id_plugin_id,IDX_dashboard_is_folder | UQE_dashboard_org_id_uid             | 171     | const,const                 |    1 |   100.00 | Using filesort                     |
|  2 | DERIVED     | dashboard     | NULL       | ref    | UQE_dashboard_org_id_folder_id_title,UQE_dashboard_org_id_uid,IDX_dashboard_org_id,IDX_dashboard_org_id_plugin_id                                 | UQE_dashboard_org_id_folder_id_title | 16      | const,const                 |  110 |    91.00 | Using index condition; Using where |
+----+-------------+---------------+------------+--------+---------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------+-----------------------------+------+----------+------------------------------------+
6 rows in set, 1 warning (0.01 sec)
```
</details>

For comparison I provide the respective execution plan for the existing query (searching by ID)
<details>
<summary>Execution plan for example query searching by ID :</summary>

```
mysql> EXPLAIN SELECT
    ->                         dashboard.id,
    ->                         dashboard.uid,
    ->                         dashboard.title,
    ->                         dashboard.slug,
    ->                         dashboard_tag.term,
    ->                         dashboard.is_folder,
    ->                         dashboard.folder_id,
    ->                         folder.uid AS folder_uid,
    ->                         folder.slug AS folder_slug,
    ->                         folder.title AS folder_title  FROM ( SELECT dashboard.id FROM dashboard WHERE (NOT dashboard.is_folder OR dashboard.is_folder) AND dashboard.org_id=1 AND dashboard.folder_id IN (1) ORDER BY dashboard.title ASC LIMIT 1000 OFFSET 0) AS ids
    ->                 INNER JOIN dashboard ON ids.id = dashboard.id
    -> LEFT OUTER JOIN dashboard AS folder ON folder.id = dashboard.folder_id
    ->                 LEFT OUTER JOIN dashboard_tag ON dashboard.id = dashboard_tag.dashboard_id
    ->  ORDER BY dashboard.title ASC
    -> ;
+----+-------------+---------------+------------+--------+-------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------+-----------------------------+------+----------+------------------------------------+
| id | select_type | table         | partitions | type   | possible_keys                                                                                                     | key                                  | key_len | ref                         | rows | filtered | Extra                              |
+----+-------------+---------------+------------+--------+-------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------+-----------------------------+------+----------+------------------------------------+
|  1 | PRIMARY     | <derived2>    | NULL       | ALL    | NULL                                                                                                              | NULL                                 | NULL    | NULL                        |  100 |   100.00 | Using temporary; Using filesort    |
|  1 | PRIMARY     | dashboard     | NULL       | eq_ref | PRIMARY                                                                                                           | PRIMARY                              | 8       | ids.id                      |    1 |   100.00 | NULL                               |
|  1 | PRIMARY     | folder        | NULL       | eq_ref | PRIMARY                                                                                                           | PRIMARY                              | 8       | grafana.dashboard.folder_id |    1 |   100.00 | NULL                               |
|  1 | PRIMARY     | dashboard_tag | NULL       | ref    | IDX_dashboard_tag_dashboard_id                                                                                    | IDX_dashboard_tag_dashboard_id       | 8       | ids.id                      |    2 |   100.00 | NULL                               |
|  2 | DERIVED     | dashboard     | NULL       | ref    | UQE_dashboard_org_id_folder_id_title,UQE_dashboard_org_id_uid,IDX_dashboard_org_id,IDX_dashboard_org_id_plugin_id | UQE_dashboard_org_id_folder_id_title | 16      | const,const                 |  110 |    91.00 | Using index condition; Using where |
+----+-------------+---------------+------------+--------+-------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------+-----------------------------+------+----------+------------------------------------+
5 rows in set, 1 warning (0.02 sec)
```
</details>

**Comment by joshhunt** [comment]
@papagian E2E tests is failing because search is no longer listing dashboards in General "folder".

**Comment by joshhunt** [comment]
Hmm. Bluge search supports sending a folderUID of 'general' to search the General folder. I'm indifferent to what the solution is (as long as it's still possible!), but if we're adding folderUID search, it might make sense to align it with bluge? idk.

**Comment by papagian** [comment]
> @papagian ~E2E tests is failing because search is no longer listing dashboards in General "folder".~ When trying to list folders in General folder, frontend tries to list dashboards in the folder with UID "general" - `/api/search?type=dash-db&folderUIDs=general`. I guess to list folders in General folder, this should still use `?folderIds=0`?

ideally we would like to deprecate at some point `folderIds` query parameter, so I think that we need to find a solution for `folderUIDs` but we could address that in a follow-up PR

**Comment by papagian** [comment]
based on the following:
https://github.com/grafana/grafana/blob/dd86693998e1baacb0f0fd3a9d82c6d64b6f9543/pkg/services/dashboards/database/database.go#L993-L999

I think that `folderIds=0` is equivalent to not passing anything to the query parameter (same for the `folderUIDs`), no?

**Comment by joshhunt** [comment]
@papagian how do you search in all folders?

**Comment by papagian** [comment]
> @papagian how do you search in all folders?

If you do not set `folderIDs` (or it's zero); tested in main

but my above assumption:
> I think that folderIds=0 is equivalent to not passing anything to the query parameter (same for the folderUIDs), no?

 is wrong because in that case `len(query.FolderIds)` is `[0]` which is greater than zero (satisfies the condition)

**Comment by papagian** [comment]
@joshhunt I have pushed a change for fetching the top level folders when passing `folderUIDs=` (empty string)

File: pkg/api/search.go [hunk 2]
```diff
@@ -136,17 +142,27 @@ type SearchParams struct {
...
 	DashboardUIDs []string `json:"dashboardUIDs"`
 	// List of folder id’s to search in for dashboards
+	// If it's `0` then it will query for the top level folders
+	// This is deprecated: users should use the `folderUIDs` query parameter instead
 	// in:query
 	// required: false
+	// deprecated: true
 	FolderIds []int64 `json:"folderIds"`
+	// List of folder UID’s to search in for dashboards
+	// If it's an empty string then it will query for the top level folders
```
Comment (joshhunt) [inline pkg/api/search.go:162]: needs updating. specify special string 'general' to query in the root level

**Review by suntala — COMMENTED** [review]
LGTM overall but there's a file I would like to take a closer look at tomorrow.

File: pkg/services/sqlstore/searchstore/filters.go [hunk 3]
```diff
@@ -91,6 +92,21 @@ func (f FolderFilter) Where() (string, []interface{}) {
...
 }
 
+type FolderUIDFilter struct {
+	Dialect migrator.Dialect
+	OrgID   int64
+	UIDs    []string
+}
+
+func (f FolderUIDFilter) Where() (string, []interface{}) {
+	if len(f.UIDs) == 1 && f.UIDs[0] == folder.GeneralFolderUID {
```
Comment (suntala) [inline pkg/services/sqlstore/searchstore/filters.go:102]: I assume it would be possible for the "General" folder to be just one of the many included in `f.UIDs`. If so, I don't know if I understand exactly why we need this special bit of logic for handling the case when it's the only folder but not when it's included in `innerSelect`. Could you please go into this?

File: pkg/services/sqlstore/searchstore/filters_test.go [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+			expectedSql:    "dashboard.folder_id = 0",
+			expectedParams: nil,
+		},
+
+		{
+			description:    "searching a specific folder",
+			uids:           []string{"abc-123"},
+			expectedSql:    "dashboard.folder_id IN (SELECT id FROM dashboard WHERE org_id = ? AND uid IN (?))",
+			expectedParams: []interface{}{int64(1), "abc-123"},
+		},
```
Comment (suntala) [inline pkg/services/sqlstore/searchstore/filters_test.go:29]: Would it be worth adding the following test cases? 
(1) Including multiple UIDs in the array
(2) Including multiple UIDs in the array and one of them is the "general" folder. 

This is somewhat related to my previous comment so not sure if (2) is actually relevant.

**Review by zserge — APPROVED** [review]
