### PR TITLE
BarChart: Value label sizing

### LINKED ISSUE #34335: Light theme does not show values on top of the bart in the (beta) bar chart (Grafana v8.0.0-beta1)
This concerns the new [bar chart](https://github.com/grafana/grafana/issues/30741) (#30741)

**What happened**:
When using the new (beta) bar chart plugin in Grafana v8.0.0-beta1 (84203aaff8), it will not show the values on the top of the bars when the light theme is in use. However, when using the dark theme, it shows the values on top of the bars.

With the dark theme:
image

With the light theme: 
image

I have set the "Show values" to "Always":
image

**What you expected to happen**:
I expected the values shown in a colour which can actually be seen when using the light theme.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a bar chart 
2. set "Show values" to "Always"
3. switch to the light theme, if you haven't already.

**Anything else we need to know?**:
No.

**Environment**:
- Grafana version: Grafana v8.0.0-beta1 (84203aaff8)
- Data source type & version: PostgreSQL data source plugin supplied with Grafana v8.0.0-beta1 (84203aaff8)
- OS Grafana is installed on: Mac OS Big Sur
- User OS & Browser: Mac OS + Google Chrome
- Grafana plugins: Only default plugins.
- Others:

### PR DESCRIPTION
**Pull request by dprokop**
This PR adds support for automatically & fixed-sized labels for bar chart values. It introduces a new, common panel option that may be used by other visualizations to control the value text formatting. Currently it has two options:

- Mode: Fixed | Auto
- Font size - when Fixed mode enabled 
I'm not a big fan of Value formatting option name.- maybe Value test style would work better? Happy to hear some suggestions
image
image

Since the auto sizing is calculated per bar, the label sizes may differ in a single vis:
image

Ideally, in this scenario, I would love to pick a single value for the size - name it min from all of the calculated- and use it for every bar. Hence the "Sync..." option in the screenshot above. But, the font size is calculated in a closure that's executed per point, and I have no idea how to make the collected font sizes available outside of this closure to render the labels. Any suggestions @leeoniya??

The barchart code config is super messy, next step here is to make it more digestable.

Test CSV data for dev dashboard:
```csv
"lib_name"," lib_size"," render_time","peak_heap"," final_heap","interact","toggl"
uPlot,39,109,19.9,3,415,75
ECharts5,987,136,55,4.6,2352,138
Chart.js3,233,161,34.4,11.3,2279,126
Flot,494,176,45.9,16.4,,
LightningChart,1000,222,61.1,22,5579,88
dygraphs,125,237,99,43.8,1528,
HighCharts,391,334,108,33.4,1428,481
CanvasJS,482,340,51.7,25.6,1488,
dvxCharts,369,380,60.4,23.5,1409,1200
Plotly,3500,485,199,46,1312,656
Chart.js2,245,602,103,53.6,9566,2745
ECharts4,785,1082,224,77.9,9897,
ApexCharts478,1701,332,70,9510,3533,
ZingCharts,857,2144,191,100,,
amCharts,1200,5016,695,237,2279,7603
```

Dev dashboard: http://localhost:3000/d/WFlOM-jM1/barchart-label-tex-sizing?orgId=1

TODO:
- [ ] cleanup bar chart code (especially variable naming and structure)
- [ ] tests

Fixes https://github.com/grafana/grafana/issues/34335

### CODE REVIEW

**Comment by dprokop** [comment]
@torkelo do you think we should support coloring the value given a threshold is hit?

**Comment by dprokop** [comment]
Ah, and the Auto sizing can result in some labels being shown while others not:

image

Not sure this is the best. Think auto should either scale all the values to the same font size, or hide them alltogether if at leas one cannot be rendered. Thoughts? :)

Thiss is again an issue with labels being rendered with drawPoint hook making the measurements not available outside of the closure.

**Comment by leeoniya** [comment]
> But, the font size is calculated in a closure that's executed per point, and I have no idea how to make the collected font sizes available outside of this closure to render the labels. Any suggestions @leeoniya??

we should use the same strategy here as in timeline by taking advantage of the fact `drawBars` executes before `drawPoints`. we can accumulate and cache a uniform font size during `drawBars()`, and then use that value in `drawPoints()`.

see the `boxRectsBySeries` cache here: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/timeline/timeline.ts#L89

**Comment by ryantxu** [comment]
Do we really need "sync" as an option?  Having different size text within the graph is pretty weird.

This seems very similar to the existing stat panel size options -- should we use the same settings model there?

image

**Comment by torkelo** [comment]
If syncing across all is tricky, let's just have a fixe size option for now.

**Comment by dprokop** [comment]
> This seems very similar to the existing stat panel size options -- should we use the same settings model there?

yes, gonna try to fix this together

**Comment by dprokop** [comment]
> Do we really need "sync" as an option

**Comment by dprokop** [comment]
> If syncing across all is tricky, let's just have a fixe size option for now.

It now works :) But no test god damn, how to test this?

File: packages/grafana-ui/src/options/builder/valueFormatting.tsx [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+            value: VizValueFormattingMode.Auto,
+            label: 'Auto',
+          },
+          {
+            value: VizValueFormattingMode.Fixed,
+            label: 'Fixed',
+          },
+        ],
+      },
+    })
```
Comment (torkelo) [inline packages/grafana-ui/src/options/builder/valueFormatting.tsx:33]: do we need this option? for the stat/bargauge/gauge we have a font size option, if you leave it empty it means Grafana will automatically handle it 

The option name (path), shoudl we align it with the naming for stat/bar gauge/ https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/stat/types.ts#L138   (text.valueSize)

**Comment by leeoniya** [comment]
this appears to fix https://github.com/grafana/grafana/issues/34335, too :+1:

File: packages/grafana-ui/src/options/builder/valueFormatting.tsx (hunk 1 above)
Comment (dprokop) [reply packages/grafana-ui/src/options/builder/valueFormatting.tsx]: @torkelo this is now unified between all visualizations using text size. Added to common options builders

File: public/app/plugins/panel/stat/types.ts [hunk 2]
```diff
@@ -120,19 +120,24 @@ export function addOrientationOption<T extends SingleStatBaseOptions>(
...
-    name: 'Title',
-    settings: {
-      placeholder: 'Auto',
-      integer: false,
-      min: 1,
-      max: 200,
-    },
-    defaultValue: undefined,
-  });
+export function addTextSizeOptions<T extends SingleStatBaseOptions>(
```
Comment (torkelo) [inline public/app/plugins/panel/stat/types.ts:123]: is this still used? (it looks the same from commonOptionsBuilder)

**Review by torkelo — APPROVED** [review]
Looks good, only looks like there is a left over addTextSizeOptions in stat/types.ts

File: public/app/plugins/panel/stat/types.ts (hunk 2 above)
Comment (dprokop) [reply public/app/plugins/panel/stat/types.ts:123]: nope, left by mistake

File: public/app/plugins/panel/barchart/bars.ts [hunk 3]
```diff
@@ -73,30 +70,119 @@ export function getConfig(opts: BarsOptions) {
         const _dir = dir * (ori === 0 ? 1 : -1);
 
         walkTwo(groupWidth, barWidth, sidx - 1, numGroups, barsPerGroup, xDim, null, (ix, x0, wid) => {
-          let lft = Math.round(xOff + (_dir === 1 ? x0 : xDim - x0 - wid));
+          let left = Math.round(xOff + (_dir === 1 ? x0 : xDim - x0 - wid));
           let barWid = Math.round(wid);
+          const canvas = u.root.querySelector<HTMLDivElement>('.u-over');
+          const bbox = canvas?.getBoundingClientRect();
```
Comment (leeoniya) [inline public/app/plugins/panel/barchart/bars.ts:76]: why is this being done for each bar?

File: public/app/plugins/panel/barchart/bars.ts [hunk 4]
```diff
@@ -73,30 +70,119 @@ export function getConfig(opts: BarsOptions) {
...
 
             if (strokeWidth) {
-              rect(stroke, lft + strokeWidth / 2, top + strokeWidth / 2, barWid - strokeWidth, barHgt - strokeWidth);
+              rect(stroke, left + strokeWidth / 2, top + strokeWidth / 2, barWid - strokeWidth, barHgt - strokeWidth);
             }
 
-            rect(fill, lft, top, barWid, barHgt);
+            rect(fill, left, top, barWid, barHgt);
+
+            let x = ori === ScaleOrientation.Horizontal ? Math.round(left - xOff) : Math.round(top - yOff);
```
Comment (leeoniya) [inline public/app/plugins/panel/barchart/bars.ts:91]: `ori === ScaleOrientation.Horizontal` changes everything simple comparisons against integers to comparisons against strings pulled from an enum object. :(

can't we just alias 0 and 1 to `HZ` and `VT` constants?

also renaming of variables below throws off a bunch of code alignment. was x/y/w/h really that unclear?

File: public/app/plugins/panel/barchart/bars.ts [hunk 5]
```diff
@@ -108,53 +194,83 @@ export function getConfig(opts: BarsOptions) {
...
   };
 
-  const drawPoints: Series.Points.Show =
-    formatValue == null
-      ? false
-      : (u, sidx) => {
-          u.ctx.font = font;
-          u.ctx.fillStyle = 'white';
+  // uPlot hook to draw the labels on the bar chart
+  const draw = (u: uPlot) => {
```
Comment (leeoniya) [inline public/app/plugins/panel/barchart/bars.ts:198]: hmm, i guess this needs to be in this later hook so we can capture label sizes across all series, since `series.paths` and `points.show` fire in alternating sequence. using a `draw` hook is a bit brute force, but probably the simplest changeset for this PR :+1: .

i'll see if i can come up with something a bit more elegant in a follow-up.

Comment (dprokop) [reply public/app/plugins/panel/barchart/bars.ts:198]: what's brute force about it?

File: public/app/plugins/panel/barchart/bars.ts (hunk 4 above)
Comment (dprokop) [reply public/app/plugins/panel/barchart/bars.ts:91]: ScaleOrientation enum ain't string, it's 0/1

Comment (dprokop) [reply public/app/plugins/panel/barchart/bars.ts:91]: > also renaming of variables below throws off a bunch of code alignment. was x/y/w/h really that unclear?


I'm not done with the renames yet ;)

File: public/app/plugins/panel/barchart/bars.ts (hunk 3 above)
Comment (dprokop) [reply public/app/plugins/panel/barchart/bars.ts:76]: yups, good catch!
