### PR TITLE
Alerting: Fix changing datasource and creating new query not  using defaults.

### LINKED ISSUE #63585: Alerting: Use default queries when clearing/adding queries
**What happened**:

We are not  applying the default values provided by the data source when clearing/adding queries.

**What you expected to happen**:

Datasources may provide a default value for queries. We should use these default valuesin alerting when:

- creating new alert (default values for form)
- adding new query
- changing the data source 

This issue is related to this one: https://github.com/grafana/grafana/issues/61280

Grafana: 10.2.3

### PR DESCRIPTION
**Pull request by soniaAguilarPeiron**
**What is this feature?**

This PR sets default query from the data source when creating new alert rule, changing data source or adding a new query in the alert rule form.

- When creating a new alert rule => uses default query in case of existing.
- When changing data source => in case of different type => uses default query in case of existing, otherwise, clears the query .
- When creating a new query => uses default query in case of existing

 **Why do we need this feature?**

Data sources can include a default value for query that should be used in the cases described before.

**Who is this feature for?**

All users

**Which issue(s) does this PR fix?**:

Fixes [#61280](https://github.com/grafana/grafana/issues/63585)

### CODE REVIEW

File: public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx [hunk 1]
```diff
@@ -35,17 +35,27 @@ import {
...
+  prefill,
+}) => {
   const runner = useRef(new AlertingQueryRunner());
   const {
     setValue,
     getValues,
     watch,
     formState: { errors },
     control,
+    formState: { isDirty },
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx:58]: Could it be combined with line 56?

File: public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx [hunk 2]
```diff
@@ -98,21 +126,36 @@ export const AlertRuleForm: FC<Props> = ({ existing, prefill }) => {
...
     defaultValues,
     shouldFocusError: true,
   });
 
-  const { handleSubmit, watch } = formAPI;
+  const { handleSubmit, watch, reset } = formAPI;
+
+  // only reset once we get some value in defaultDsAndQueries.queries, adding this value.
+  useEffect(() => {
+    !existing &&
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx:147]: `if` condition could improve readability here

File: public/app/features/alerting/unified/components/rule-editor/ExpressionEditor.tsx [hunk 3]
```diff
@@ -17,18 +19,37 @@ export interface ExpressionEditorProps {
...
+  const defaultModel = lazyDefaultQuery?.model;
+  const previousDataSource = usePrevious(dataSourceName);
+
+  // New alert: update with default query once we have the lazy default
+  useEffect(() => {
+    !preservePreviousValue && defaultModel && setDataQuery((dataQuery) => ({ ...dataQuery, ...{ ...defaultModel } }));
+  }, [defaultModel, preservePreviousValue]);
+  // when data source is changed
+  useEffect(() => {
+    !!previousDataSource &&
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rule-editor/ExpressionEditor.tsx:47]: How about extracting this condition into a variable?

File: public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx [hunk 4]
```diff
@@ -176,6 +191,12 @@ export const QueryAndExpressionsStep: FC<Props> = ({ editingExistingRule, onData
     }
   }, [condition, queries, handleSetCondition]);
 
+  const onAddNewQuery = () => {
+    lazyDataSource &&
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx:195]: nit: `if` condition?

File: public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx [hunk 5]
```diff
@@ -191,6 +212,8 @@ export const QueryAndExpressionsStep: FC<Props> = ({ editingExistingRule, onData
                   {...field}
                   dataSourceName={dataSourceName}
                   showPreviewAlertsButton={!isRecordingRuleType}
+                  lazyDefaultQuery={lazyDefaultQueries?.[0]}
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx:215]: How do we know that we always want to pass the first query?

File: public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx [hunk 6]
```diff
@@ -247,7 +290,13 @@ export const AlertRuleForm: FC<Props> = ({ existing, prefill }) => {
           <CustomScrollbar autoHeightMin="100%" hideHorizontalTrack={true}>
             <div className={styles.contentInner}>
               <AlertRuleNameInput />
-              <QueryAndExpressionsStep editingExistingRule={!!existing} onDataChange={checkAlertCondition} />
+              <QueryAndExpressionsStep
+                editingExistingRule={!!existing}
+                prefill={!!prefill}
+                onDataChange={checkAlertCondition}
+                lazyDefaultQueries={defaultDsAndQueries.queries}
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx:297]: The prop is named `lazy`, but we render it only if there are some `queries` in the `defaultDsAndQueries` object. So what does `lazy` means in this context?

File: public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx (hunk 1 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx:58]: 💯

File: public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx (hunk 5 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx:215]: the first query is the one that contains the data query (not expressions) as we do in `getDefaultQueriesAsync`

File: public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx (hunk 6 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx:297]: Maybe we could rename it to asycDefaultQueries => this queries array is an async value. Once we have a value in here means we can render.

File: public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx [hunk 7]
```diff
@@ -218,13 +227,18 @@ function copyModel(item: AlertQuery, settings: DataSourceInstanceSettings): Omit
   };
 }
 
-function newModel(item: AlertQuery, settings: DataSourceInstanceSettings): Omit<AlertQuery, 'datasource'> {
+async function newModel(
+  item: AlertQuery,
+  settings: DataSourceInstanceSettings
+): Promise<Omit<AlertQuery, 'datasource'>> {
+  const ds = await getDataSourceSrv().get(item.datasourceUid);
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx]: Maybe we could move this line to `onDataSourceChange` function, and instead of passing `settings` we could pass the data source object. Thanks to that this function would be still simple and wouldn't require async calls

File: public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx [hunk 8]
```diff
@@ -176,6 +176,15 @@ export const QueryAndExpressionsStep: FC<Props> = ({ editingExistingRule, onData
     }
   }, [condition, queries, handleSetCondition]);
 
+  const onAddNewQuery = async () => {
+    const datasource = getDefaultOrFirstCompatibleDataSource();
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx]: Should we keep this code here or move it to the `addNewDataQuery` reducer?

File: public/app/features/alerting/unified/utils/rule-form.ts [hunk 9]
```diff
@@ -199,9 +202,47 @@ export function recordingRulerRuleToRuleForm(
...
+
+  let ds;
+  try {
+    ds = await getDataSourceSrv().get(dataSource.uid);
+  } catch (error) {
+    console.log(error);
+    return { queries: [...getDefaultExpressions('A', 'B')] };
+  }
+
+  return {
```
Comment (konrad147) [inline public/app/features/alerting/unified/utils/rule-form.ts:223]: Could we reuse `newModel` function here?

File: public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx [hunk 10]
```diff
@@ -84,6 +110,8 @@ export const AlertRuleForm: FC<Props> = ({ existing, prefill }) => {
   const returnTo: string = (queryParams['returnTo'] as string | undefined) ?? '/alerting/list';
   const [showDeleteModal, setShowDeleteModal] = useState<boolean>(false);
 
+  const { defaultDsAndQueries, defaultsInQueryParamsObject } = useGetDefaults(queryParams, existing);
```
[the remark this answers is not in the document]
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx:113]: I don't think that's the case where we expect a slow response as this is about getting the default queries for one datasource.

File: public/app/features/alerting/unified/utils/rule-form.ts (hunk 9 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/utils/rule-form.ts:223]: I don't think it's a good idea in this case, as this would make the newModel less understandable, as so far, newModel is for creating a new model based on an existing AlertQuery and a particular data source.
In here, it's something different, we create a new model for default data source and we are not relaying on an existing AlertQuery

File: public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx (hunk 7 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx]: Yes we can do it 👌
We still need to pass settings, though.

**Review by konrad147 — APPROVED** [review]
LGTM!

File: public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx [hunk 11]
```diff
@@ -247,7 +300,13 @@ export const AlertRuleForm: FC<Props> = ({ existing, prefill }) => {
           <CustomScrollbar autoHeightMin="100%" hideHorizontalTrack={true}>
             <div className={styles.contentInner}>
               <AlertRuleNameInput />
-              <QueryAndExpressionsStep editingExistingRule={!!existing} onDataChange={checkAlertCondition} />
+              <QueryAndExpressionsStep
+                editingExistingRule={!!existing}
+                prefill={!!prefill}
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx:305]: I'm not sure if I understand why these props have to be passed all the way down in to the `QueryAndExpressionsStep`, it looks like we're using them to make some assertions on when to dispatch `setDataQueries`?

**Review by gillesdemey — COMMENTED** [review]
Is there a way we can split this PR in to two distinct problems:
1. clearing the model when switching DS
2. applying `getDefaultQuery`

I feel like the former is more important than the latter and I think there might be some opportunities to improve on the latter while not blocking a bug fix for 1.

File: public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx (hunk 11 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx:305]: We need to pass all the way down because:
- we need default queries for initialising the form with the default values. (when creating a new alert rule)
- we need also these default queries as you said in the `QueryAndExpressionsStep` to set queries once this async value is set, and also for the `onAddNewQuery` (to set the default)
- at the same time we need to keep updated this async default value in the `ExpressionEditor` when we are creating a new alert.

File: public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx [hunk 12]
```diff
@@ -247,7 +300,13 @@ export const AlertRuleForm: FC<Props> = ({ existing, prefill }) => {
...
+                onDataChange={checkAlertCondition}
+                asyncDefaultQueries={defaultDsAndQueries.queries}
+                asyncDataSource={defaultDsAndQueries.ds}
```
[the remark this answers is not in the document]
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx:308]: this `defaultDsAndQueries.queries` is not the same as we get from `DataSourceApi`.`getDefaultQuery`. This `defaultDsAndQueries.queries` is: 
`queries: [
      {
        refId: 'A',
        datasourceUid: dataSource.uid,
        queryType: '',
        relativeTimeRange,
        model: {
          refId: 'A',
          hide: false,
          ...ds?.getDefaultQuery?.(CoreApp.UnifiedAlerting),
        },
      },
      ...getDefaultExpressions('B', 'C'),
    ],`

File: public/app/features/alerting/unified/utils/rule-form.ts [hunk 13]
```diff
@@ -199,9 +202,46 @@ export function recordingRulerRuleToRuleForm(
   };
 }
 
-export const getDefaultQueries = (): AlertQuery[] => {
+export const getDefaultQueriesAsync = async (): Promise<{
+  queries: AlertQuery[] | null;
```
[the remark this answers is not in the document]
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/utils/rule-form.ts:206]: we use null to differentiate between the resolved value that can be an empty string or the null that indicates in some parts of the code that we don't have the value yet.

File: public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/__snapshots__/reducer.test.tsx.snap [hunk 14]
```diff
@@ -66,14 +66,24 @@ exports[`Query and expressions reducer should add query 1`] = `
...
-      "datasourceUid": "c8eceabb-0275-4108-8f03-8f74faf4bf6d",
+      "datasourceUid": "some uid",
       "model": {
         "datasource": {
-          "type": "prometheus",
-          "uid": "c8eceabb-0275-4108-8f03-8f74faf4bf6d",
+          "type": undefined,
+          "uid": "some uid",
         },
+        "datasourceUid": "",
```
[the remark this answers is not in the document]
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/__snapshots__/reducer.test.tsx.snap:75]: in the test we are using this default query:
```
 const defaultQuery: AlertQuery = {
      refId: 'A',
      queryType: '', =>>>>>>>>>>
      datasourceUid: '',=>>>>>>>>>>
      model: { refId: 'A', expression: 'THIS IS THE DEFAULT EXPRESSION' },
      relativeTimeRange: getDefaultRelativeTimeRange(),
    };
```
where the queryType is empty and also the datasource. That's why we get this snapshot.

File: public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx [hunk 15]
```diff
@@ -73,6 +89,26 @@ type Props = {
   prefill?: Partial<RuleFormValues>; // Existing implies we modify existing rule. Prefill only provides default form values
 };
 
+export const useGetDefaults = (queryParams: UrlQueryMap, existing: RuleWithLocation<RulerRuleDTO> | undefined) => {
+  const [defaultDsAndQueries, setDefaultDsAndQueries] = useState<{
+    queries: AlertQuery[] | null;
```
[the remark this answers is not in the document]
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx:95]: same as before

File: public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx [hunk 16]
```diff
@@ -73,6 +89,26 @@ type Props = {
...
+    ds?: DataSourceApi<DataQuery, DataSourceJsonData, {}>;
+  }>({ queries: null });
+
+  useEffect(() => {
+    const getDefaultQueries_ = async () => {
```
[the remark this answers is not in the document]
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx]: done!

**Comment by soniaAguilarPeiron** [comment]
@gillesdemey I updated the description of the PR, because this PR is actually setting the defaults. What I see is that the problem of not clearing the model is not happening. I was testing it and I didn't find any issues on that. @konrad147 mentioned the same. Maybe something related to data source plugins changed and this error is gone?

File: public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx (hunk 11 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx:304]: Gotcha, that makes sense!

**Review by gillesdemey — APPROVED** [review]
Everything looks good, let's ship it! :shipit:
