### PR TITLE
QueryBuilder: Preserve queries when switching from Mixed

### LINKED ISSUE #50831: Switching from mixed to Azure monitor loses query data
**What happened**:
azure monitor

**What you expected to happen**:
Switching between mixed and Azure monitor should keep the query data
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
In grafana/public/app/features/query/state/updateQueries.ts, as Azure monitor Datasource does not have `importQueries`, the query data are lost in the method.
**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by aangelisc**
Paraphrasing from grafana/grafana#66968:

This PR preserves all relevant queries when switching from mixed to another data source. If there are no relevant queries, then the default query will be set.

NOTE: The original issue indicated that this was an issue with Azure Monitor but it actually applies to all data sources because of how the data source picker worked.

This should improve UX as queries will be maintained leading to less effort from users. A follow-up would be to determine if Expression queries should be migrated or cleared (they are cleared for now).

Fixes #50831

### CODE REVIEW

**Comment by alyssabull** [comment]
@oscarkilhed - when implementing this PR we noticed that switching from mixed to a new datasource doesn't re-run the query. We noticed that you recently [implemented this code ](https://github.com/grafana/grafana/blob/2075dc4f2b8f32457d6de1fa6ed61a4d93557b74/public/app/features/query/components/QueryGroup.tsx#L164) and were wondering if you could provide some context. Thanks!

File: public/app/features/query/state/updateQueries.ts [hunk 1]
```diff
@@ -26,8 +27,23 @@ export async function updateQueries(
     else if (currentDS && nextDS.importQueries) {
       nextQueries = await nextDS.importQueries(queries, currentDS);
     }
-    // Otherwise clear queries
+    // Otherwise clear queries that do not match the next datasource UID
     else {
+      if (currentDS) {
+        const reducedQueries: DataQuery[] = [];
+        const nextDsQueries = queries.reduce((reduced, currentQuery) => {
```
Comment (axelavargas) [inline public/app/features/query/state/updateQueries.ts:34]: Nit: I think it would be great to add a comment on what is the criteria to preserve the relevant comments 😄

**Review by axelavargas — COMMENTED** [review]
Hey @aangelisc 👋🏾, I think the PR is excellent 🙌🏾 . It indeed improves user experience by preserving the queries. However, I've found an issue concerning template variables and mixed data sources. It seems that when I switch to Mixed, some of the queries associated with the variable are cleared.


https://github.com/grafana/grafana/assets/239999/de1ec5ed-6d3b-489c-8b60-f1a500e2387b

File: public/app/features/query/state/updateQueries.ts (hunk 1 above)
Comment (aangelisc) [reply public/app/features/query/state/updateQueries.ts:39]: Added a comment 😊

**Comment by aangelisc** [comment]
@axelavargas thank you for catching that! I've updated this to work as expected when template variables are used. Wdyt of @alyssabull's comment above?

**Review by axelavargas — COMMENTED** [review]
Hey @aangelisc 👋🏾 , I gave it a second test and I found something else (Variables are really tricky 😢 ). Sometimes the variable inside the query became stale, I am attaching the video with the repro steps.


https://github.com/grafana/grafana/assets/239999/f09e4917-3bd4-42e5-87cf-5d5896e50b94

P.S Regarding this comment:

> @oscarkilhed - when implementing this PR we noticed that switching from mixed to a new datasource doesn't re-run the query. We noticed that you recently [implemented this code ](https://github.com/grafana/grafana/blob/2075dc4f2b8f32457d6de1fa6ed61a4d93557b74/public/app/features/query/components/QueryGroup.tsx#L164)and were wondering if you could provide some context. Thanks!


Unfortunately, I don't have the context of why this changed was made, maybe @ivanortegaalba knows?  (Oscar is on vacation 🌴 )

**Review by axelavargas — APPROVED** [review]
@aangelisc great job 🥳 , I gave it a last quick test and everything works as expected. 

Also 👍🏾 for the unit test!
