### PR TITLE
Prometheus: Grafana global variables in PromQL should not raise errors

### LINKED ISSUE #60314: Switching to builder mode with a valid PromQL query shows a "Query Parsing Error" modal
**What happened**:
When switching to builder mode with a valid PromQL query a confirmation modal is being displayed. Since I have a valid PromQL query it should not happen. 
The Query:
```
sort_desc(sum without(job, instance) (rate(grafana_http_request_duration_seconds_count[$__rate_interval])))
```

The problem is `$__rate_interval`. I think the parser cannot handle `$` properly. Here is the function handling that https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/querybuilder/parsing.ts#L105

image
image

**What you expected to happen**:
No modal should be displayed.

**How to reproduce it (as minimally and precisely as possible)**:
- Go to Explore with the Prometheus datasource selected
- In the `Code Mode` write the following query `sort_desc(sum without(job, instance) (rate(grafana_http_request_duration_seconds_count[$__rate_interval])))`
- Click `Builder` to switch to `Builder Mode`
- Observe there is a confirmation modal
- Even though it says there are errors it will parse the query properly in `Builder Mode`

**Anything else we need to know?**:
The problem is `$__rate_interval`. I think the parser cannot handle `$` properly. Here is the function handling that https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/querybuilder/parsing.ts#L105

**Environment**:
- Grafana version: `v9.4.0-pre`

### PR DESCRIPTION
**Pull request by LudoVio**
**What is this feature?**

Grafana global variables in PromQL should not raise errors

**Why do we need this feature?**

When a PromQL query has Grafana global variables, it is considered invalid by the parser and an error popup shows up

**Who is this feature for?**

Everyone using Prometheus query editor

**Which issue(s) does this PR fix?**:

Fixes #60314

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/querybuilder/parsing.ts [hunk 1]
```diff
@@ -95,6 +101,30 @@ interface Context {
...
+    query: {
+      metric: '',
+      labels: [],
+      operations: [],
+    },
+    errors: [],
+  };
+
+  expr = expr.replace(/\$__interval/g, '1m');
+  expr = expr.replace(/\$__rate_interval/g, '1m');
```
Comment (itsmylife) [inline public/app/plugins/datasource/prometheus/querybuilder/parsing.ts:115]: We also have the `$__range`. I do not know where exactly we use it but we have.
See: https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/components/monaco-query-field/monaco-completion-provider/completions.ts#L61

Comment (itsmylife) [reply public/app/plugins/datasource/prometheus/querybuilder/parsing.ts:115]: It works but I do not feel safe with this. What if we have more variables in the future? What if we have variables that are not handled here? We must find a better approach I believe.

**Review by ivanahuckova — COMMENTED** [review]
Just an idea - for Loki we have implemented full query validation in monaco editor and we had to "take care" of the similar issue. Here is the PR https://github.com/grafana/grafana/pull/59427

File: public/app/plugins/datasource/prometheus/querybuilder/parsing.ts (hunk 1 above)
Comment (LudoVio) [reply public/app/plugins/datasource/prometheus/querybuilder/parsing.ts:115]: Before sending the query to Prometheus, Grafana  is extrapolating the custom variables. There is probably the code somewhere in the backend. This backend probably hold the list of Global variables. We need  a way for the frontend to access this list of variables identifier, alongside a dummy value compatible with the type of that variable. So people adding global variables later will not have to update the frontend.

Do you think it is worth investigating?

Comment (LudoVio) [reply public/app/plugins/datasource/prometheus/querybuilder/parsing.ts]: Added all variables I could find, with default values. 

Reading Loki and Prometheus plugins code, I can see that those variables are hard coded in multiples places. It does not seem to exist a single source of truth for what global variables Grafana provides and what default values should be used for syntax validation purpose.

**Comment by aocenas** [comment]
Looking at the code here https://github.com/grafana/grafana/blob/46f0672215011e6c233b9df4ccef5e5c5af6e271/public/app/plugins/datasource/prometheus/querybuilder/parsing.ts#L204 I would assume we are swallowing any error as part of the function node don't we? Or did the error move to be a sibling node instead of child node of the function?

**Comment by LudoVio** [comment]
> Looking at the code here
> 
> https://github.com/grafana/grafana/blob/46f0672215011e6c233b9df4ccef5e5c5af6e271/public/app/plugins/datasource/prometheus/querybuilder/parsing.ts#L204
> 
> I would assume we are swallowing any error as part of the function node don't we? Or did the error move to be a sibling node instead of child node of the function?

As I understand it., this code is taking what is inside the `[]` and add it as a parameter to the function. For example `$__rate_interval`. But that is still invalid as per PromQL grammer and will create an error node.

**Review by itsmylife — APPROVED** [review]
