### PR TITLE
Auth: Fix signup workflow and UI when verify email is enabled

### LINKED ISSUE #26262: Workflow for signup with verify email enabled is erroneous
**What happened**:
* On enabling verify email and enable signup, signup screen asks for verification code without an option to send it
* The user interface is not consisent with login

**How to reproduce it (as minimally and precisely as possible)**:
1. Enable signup and verify_email in configuration
2. Setup smtp
3. Try to sign up

**Environment**:
- Grafana version: 7.2.0-pre
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Ubuntu 16.04, Chrome

### LINKED ISSUE #27167: User sign up doesn't work when verify email enabled
**What happened**:
Clicked on Sign Up button on login page and was redirected to sign up page. Had to fill in email verification code, name, email and password. Filling in name, email and password and clicking on Submit results in `Invalid email verification code`.

image
image

**What you expected to happen**:
Backtracked to v4.6.5 which seem to be latest version where this works as expected; I would expect to be filling in email in a first step after clicking on the Sign Up button on the login page. Then an email sent with a verification code and/or link to sign up where I can complete the sign up flow.

image
image

**How to reproduce it (as minimally and precisely as possible)**:
1. Enable the following settings:
```ini
allow_sign_up = true
verify_email_enabled = true
```
2. If authenticated, logout
3. Navigate to the login page
4. Click on Sign Up button

**Anything else we need to know?**:
I'm guessing that maybe the same form are used for both sign up and invite flows. 

**Environment**:
- Grafana version: latest (4a6268014a), 7.1.3, 6.7.3, 5.0.4

### PR DESCRIPTION
**Pull request by KamalGalrani**
**What this PR does / why we need it**:
* Fixes signup workflow
* Makes Signup UI consistent with Login
* Fixes login and forgot password links (they did not respect appsuburl)

**Which issue(s) this PR fixes**:
Fixes #26262
Fixes #27167

**Special notes for your reviewer**:
Setup SMTP before testing this PR

### CODE REVIEW

**Comment by torkelo** [comment]
This is looking great, frontend squad is a bit short-staffed during summer so might take some time to get this reviewed

File: public/app/core/components/ForgottenPassword/ForgottenPassword.tsx [hunk 1]
```diff
@@ -32,7 +33,7 @@ export const ForgottenPassword: FC = () => {
       <div>
         <p>An email with a reset link has been sent to the email address. You should receive it shortly.</p>
         <Container margin="md" />
-        <LinkButton variant="primary" href="/login">
+        <LinkButton variant="primary" href={getConfig().appSubUrl + '/login'}>
```
Comment (hugohaggmark) [inline public/app/core/components/ForgottenPassword/ForgottenPassword.tsx:36]: May I suggest creating/using a variable `loginHref` with the value `getConfig().appSubUrl + '/login'` so future changes can be done in one place, wdyt @KamalGalrani ?

File: public/app/core/components/Login/UserSignup.tsx [hunk 2]
```diff
@@ -1,8 +1,12 @@
 import React, { FC } from 'react';
 import { LinkButton, VerticalGroup } from '@grafana/ui';
 import { css } from 'emotion';
+import { getConfig } from 'app/core/config';
 
 export const UserSignup: FC<{}> = () => {
+  let href = getConfig().verifyEmailEnabled ? '/verify' : '/signup';
+  href = getConfig().appSubUrl + href;
+
```
Comment (hugohaggmark) [inline public/app/core/components/Login/UserSignup.tsx:9]: Nitpick: avoid using `let` when you can use `const` instead.
```suggestion
  const href = getConfig().verifyEmailEnabled ? `${getConfig().appSubUrl}/verify` : `${getConfig().appSubUrl}/signup`;
```

File: public/app/core/components/Signup/VerifyEmail.tsx [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+import { AppEvents } from '@grafana/data';
+
+interface EmailDTO {
+  email: string;
+}
+
+export const VerifyEmail: FC = () => {
+  const [emailSent, setEmailSent] = useState(false);
+
+  const sendEmail = (formModel: EmailDTO) => {
```
Comment (hugohaggmark) [inline public/app/core/components/Signup/VerifyEmail.tsx:15]: nitpick
```suggestion
  const onSubmit = (formModel: EmailDTO) => {
```

**Comment by KamalGalrani** [comment]
Thanks @hugohaggmark 
I have applied the changes

**Review by hugohaggmark — COMMENTED** [review]
Looks good to me, but I'm not able to test this today. Will try to test it tomorrow.

**Comment by hugohaggmark** [comment]
@KamalGalrani I'm going to merge latest changes from master so we can push this PR forward

**Comment by hugohaggmark** [comment]
> @KamalGalrani I'm going to merge latest changes from master so we can push this PR forward

Sorry, I can't do that on your fork. Maybe you can merge your branch with master @KamalGalrani?

**Review by hugohaggmark — APPROVED** [review]
Looks great, thank you @KamalGalrani for this contribution. I took this for a test spin and it worked wonderfully AFAIK. Needs to merge with master :)

Someone needs to review the backend code too. @grafana/backend-platform

**Review by hugohaggmark — CHANGES_REQUESTED** [review]
Hmm, testing to log in as an existing user doesn't work. I'll add repro soon

**Review by hugohaggmark — APPROVED** [review]
Hmm, I couldn't repro the previous erroneous behavior. When I tried to login as admin I got redirected to verify email page for some reason. But I might have forgotten to refresh the browser after doing changes in config.ini. Sorry for this interruption.

We still need some review from our backend squad before merging this to `master` @KamalGalrani.

File: public/app/core/components/ForgottenPassword/ForgottenPassword.tsx [hunk 4]
```diff
@@ -21,6 +20,7 @@ const paragraphStyles = (theme: GrafanaTheme) => css`
 export const ForgottenPassword: FC = () => {
   const [emailSent, setEmailSent] = useState(false);
   const styles = useStyles(paragraphStyles);
+  const loginHref = `${config.appSubUrl}/login`;
```
Comment (hugohaggmark) [inline public/app/core/components/ForgottenPassword/ForgottenPassword.tsx:23]: Hmm, you should use `getConfig()` instead

Comment (KamalGalrani) [reply public/app/core/components/ForgottenPassword/ForgottenPassword.tsx:23]: Commit on 4th Sept used config instead of get config. https://github.com/grafana/grafana/commit/a54df0c3cd37f79655a70d16a66a8a631d6e5304#diff-8ed33df727294c29ebfba45e47faba53

Let me know if you want me to change back to getConfig

Comment (hugohaggmark) [reply public/app/core/components/ForgottenPassword/ForgottenPassword.tsx:23]: Yeah, I saw that change. If you can change it, but not super important. It much more important to get a backend specific code review.

**Review by aknuds1 — APPROVED** [review]
Haven't tested it myself, but assuming that the back-end component is correct (render the index page for /verify route).

**Review by papagian — APPROVED** [review]
I have tested it w/o email verification enabled, using invalid verification code and using valid verification code that does not match with the email and all work as expected. Thank you for your contribution!
