### PR TITLE
AzureMonitor: Filter list of resources by resourceType

### LINKED ISSUE #43514: Azure Monitor: Missing resources for huge resource groups
**What happened**:
When working with the Azure Monitor data source and selecting a resource group with more than 1000 resources in the query editor, you won't have all the resources available for selection. The reason appears to be a request behind the scenes made to `/api/datasources/2/resources/azuremonitor/subscriptions/#SUBSCRIPTION_ID#/resourceGroups/#RESOURCE_GROUP_NAME#/resources?api-version=2018-01-01` which returns a JSON with a values array of 1000 elements only and a nextLink which apparently isn't followed by Grafana. Even if I select a specific resource type in my query, Grafana still makes a request for all the resources in the resource group instead of using a resourceType filter.

**What you expected to happen**:
Whenever I'm working with resource groups with over 1000 elements I should be able to select any element which is present in that resource group. Grafana should either:
- follow the `nextLink` value and fetch another batch of resources
- use a resourcetype filter when requesting resources 

**How to reproduce it (as minimally and precisely as possible)**:
1. You will need a resource group with over 1000 resources.
2. Go into query editor and select your subscription, resource group with over 1000 elements and one of the resource types.
3. Look at the network tab of your browser, Grafana will make a request without filtering for the specific resource type. You will get only 1000 resources in the response and only those resource will be available for selection.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.3.3
- Data source type & version: Azure Monitor data source - native plugin | Grafana Labs | 0.3.0 | Core
- OS Grafana is installed on: Docker - grafana/grafana:8.3.3
- User OS & Browser: Manjaro Linux - Firefox 95.0
- Grafana plugins: No extra than what is shipped with grafana
- Others:

### PR DESCRIPTION
**Pull request by andresmgot**
**What this PR does / why we need it**:

Uses the `resourceType` when requesting resources, to scope down the amount of results obtained.

**Which issue(s) this PR fixes**:

Fixes #43514

**Special notes for your reviewer**:

I have also updated the apiVersion to match the documentation: https://docs.microsoft.com/en-us/rest/api/resources/resources/list-by-resource-group#uri-parameters

### CODE REVIEW

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/grafanaTemplateVariableFns.ts [hunk 1]
```diff
@@ -121,6 +121,7 @@ const createGrafanaTemplateVariableQuery = (rawQuery: string, datasource: DataSo
         resourceGroup: matchesForQuery.resourceNamesWithSub[2],
         metricDefinition: matchesForQuery.resourceNamesWithSub[3],
       };
+      console.log('Subscription_? ', queryDetails.subscription);
```
Comment (sunker) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/grafanaTemplateVariableFns.ts:124]: remove this?

**Review by sunker — APPROVED** [review]
LGTM

File: public/app/plugins/datasource/grafana-azure-monitor-datasource/grafanaTemplateVariableFns.ts (hunk 1 above)
Comment (andresmgot) [inline public/app/plugins/datasource/grafana-azure-monitor-datasource/grafanaTemplateVariableFns.ts:124]:
```suggestion
```
