### PR TITLE
Canvas: Fix inconsistent element placement when changing element type

### LINKED ISSUE #74222: Canvas: Placement gets reset when switching to button
When switching to button type, the placement gets reset to top left of panel.

https://github.com/grafana/grafana/assets/22381771/d635dd72-118c-4956-9546-3052a02665b0

### LINKED ISSUE #74941: Canvas: From any element type to Text, the placement will reset to 100,100
### What happened?

From any element type to Text, the placement will reset to 100,100

https://github.com/grafana/grafana/assets/56526981/790302b2-79eb-4a33-b631-f33e7307c5b2

### What did you expect to happen?

the element changed will stay in the original placement, not reset to  position 100,100.

### Did this work before?

Since these elements added

### How do we reproduce it?

1. from element type change to another type('button', 'metric value', 'text')

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: latest dev, and  v10.2.0-59882 (3ee26df4)in play.grafana.com
OS: MacOS
Browser: Chrome 116

### Grafana platform?

Other

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by linghaoSu**
**Which issue(s) does this PR fix?**:

fix placement reset when change element type

Fixes https://github.com/grafana/grafana/issues/74941
Fixes #74222

result: 

https://github.com/grafana/grafana/assets/56526981/2f389f5a-5227-4147-961f-840c6fec6676

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/canvas/elements/icon.tsx [hunk 1]
```diff
@@ -91,6 +85,12 @@ export const iconItem: CanvasElementItem<IconConfig, IconData> = {
         fixed: 'transparent',
       },
     },
+    placement: {
+      width: options?.placement?.width ?? 100,
+      height: options?.placement?.height ?? 100,
+      top: options?.placement?.top ?? 0,
+      left: options?.placement?.left ?? 0,
```
Comment (nmarrs) [inline public/app/features/canvas/elements/icon.tsx:92]:
```suggestion
      top: options?.placement?.top ?? 100,
      left: options?.placement?.left ?? 100,
```

**Review by nmarrs — APPROVED** [review]
LGTM - one nit on fallback top / left of icon. Thanks for your contribution!

**Comment by nmarrs** [comment]
Hi @linghaoSu - to fix the build I believe we need to rebase your PR branch onto latest main. As I do not have write permissions to your branch you will need to first pull latest main branch, switch to your PR branch and run `git merge origin main` and push. 

Thanks!
