### PR TITLE
Elasticsearch: Fix auto interval for date histogram in explore logs mode

### LINKED ISSUE #21285: Elasticsearch: Wrong auto interval for date histogram in explore logs mode
On the Explore page in Metrics mode you can produce any date histogram of document counts you want and the default interval value set to "auto" will adjust the "interval" parameter's value to a sane value based on the time range when the underlying code makes the request to grafana-instance.com/api/datasources/proxy/x/_msearch?max_concurrent_shard_requests=xx.

_However_ when on the Explore page in Logs mode, if you have enough data(in order to not create null buckets) changing the date range before modifying the query to something like last 30 days(typical workflow in Kibana Discover) will  produce a _msearch request with this payload:
```
[
  { "search_type": "query_then_fetch", "ignore_unavailable": true, "index": "my-index-*" },
  {
    "size": 500,
    "query": {
      "bool": {
        "filter": [
          {
            "range": { "@timestamp": { "gte": "epoch_min", "lte": "epoch_max", "format": "epoch_millis" } }
          }
        ]
      }
    },
    "sort": { "@timestamp": { "order": "desc", "unmapped_type": "boolean" } },
    "script_fields": { },
    "docvalue_fields": ["@timestamp"],
    "aggs": {
      "2": {
        "date_histogram": {
          "interval": "1s",
          "field": "@timestamp",
          "min_doc_count": 0,
          "extended_bounds": { "min": "1577481456296", "max": "1577503056296" },
          "format": "epoch_millis"
        },
        "aggs": { }
      }
    }
  }
]

```
Grafana is properly setting the size constraint(500) to only return the log data that the user is interested in but the date histogram of the document counts at the top of the page is using the aggregation with a 1 second interval and no way to change it to anything higher.  The usecase for that histogram isn't detailed graphing(thus not needing a modifiable interval like panels) but to give the user an easy way to eyeball out rough time ranges to focus on when reading the logs or narrowing the query time range down to.

I believe this issue could be closed(as fixed) by changing the Explore:Logs page to use the same auto interval logic as Explore:Metrics since it looks to be the only case where this error is being produced without the user specifically asking for the condition which triggered it.  If the user sets a value that causes the error then the ElasticSearch guidance that you pointed out of "manually raise the level if you actually did it on purpose" is correct response and there is nothing Grafana can do about it.  Kibana will give you the same bucket error when you do something like this on the Visualization page and modifying the query without the user's knowledge for graph panels via backend magic would be dangerous to do(changing the meaning of the returned aggregate, causing load problems for your cluster, etc).

_Originally posted by @redNixon in https://github.com/grafana/grafana/issues/17327#issuecomment-569384893_

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
Limit the number of datapoints for the counts query to container width.

**Which issue(s) this PR fixes**:
Fixes #21285

### CODE REVIEW

File: public/app/features/explore/state/actions.ts [hunk 1]
```diff
@@ -428,9 +428,11 @@ export const runQueries = (exploreId: ExploreId): ThunkResult<void> => {
 
     const queryOptions: QueryOptions = {
       minInterval,
-      // This is used for logs streaming for buffer size, with undefined it falls back to datasource config if it
-      // supports that.
-      maxDataPoints: mode === ExploreMode.Logs ? undefined : containerWidth,
+      // maxDataPoints is used in:
+      // Loki - used for logs streaming for buffer size, with undefined it falls back to datasource config if it supports that.
+      // Elastic - limits the number of datapoints for the counts query and for logs it has hardcoded limit.
+      // Influx - used to correctly display logs ingraph
```
Comment (aocenas) [inline public/app/features/explore/state/actions.ts]:
```suggestion
      // Influx - used to correctly display logs in graph
```

**Review by aocenas — APPROVED** [review]

**Comment by marefr** [comment]
@ivanahuckova cherry-pick needed label is needed if this going into 6.6.2

**Comment by ivanahuckova** [comment]
@marefr Yes, sorry, cherry pick was removed as it wasn't part of 6.6.1 and I have forgotten to add it again. Added.
