### PR TITLE
Alerting: Fix labels suggestions Grafana-managed rules

### LINKED ISSUE #73890: Invalid Grafana-managed alert rule labels suggestions
Custom labels editor provides incorrect suggestions for Grafana-managed alert rules

Image

The suggestions are based on the `/api/ruler` response from the selected data source. While this behavior is correct for Mimir/Loki rules it's wrong for Grafana-managed rules

Grafana-managed rules should use the `/api/ruler/grafana` response to populate suggestions no matter what data sources are selected in the queries section

### PR DESCRIPTION
**Pull request by konrad147**
**What is this feature?**
This PR fixes labels' suggestions for Grafana-managed alert rules

Fixes #73890 

**Special notes for your reviewer:**
The issue was caused by using the `dataSourceName` form field for Grafana-managed rules. The value of this field was then passed as a data source name to the labels autosuggestion instead of the `grafana` data source
The field is only valid for Mimir/Loki rules
The PR removes the code that changes the value of `dataSourceName` input when working with GMA

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx [hunk 1]
```diff
@@ -312,6 +312,11 @@ export const QueryAndExpressionsStep = ({ editingExistingRule, onDataChange }: P
       prevCondition && setValue('condition', prevCondition);
     } else {
       setValue('type', RuleFormType.cloudAlerting);
+      const newDsName = getDataSourceSrv().getInstanceSettings(queries[0].datasourceUid)?.name;
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx:315]: i would add a comment in here to understand why we are only setting the data source in case of cloud

File: public/app/features/alerting/unified/CloneRuleEditor.test.tsx [hunk 2]
```diff
@@ -164,7 +164,7 @@ describe('CloneRuleEditor', function () {
       });
 
       await waitForElementToBeRemoved(ui.loadingIndicator.query());
-      await waitForElementToBeRemoved(within(ui.inputs.group.get()).getByTestId('Spinner'));
+      await waitForElementToBeRemoved(within(ui.inputs.group.get()).queryByTestId('Spinner'));
```
Comment (soniaAguilarPeiron) [inline public/app/features/alerting/unified/CloneRuleEditor.test.tsx:167]: why do we need this change?

Comment (gillesdemey) [reply public/app/features/alerting/unified/CloneRuleEditor.test.tsx:167]: I've also seen this one being flakey on some PRs 👍

**Review by soniaAguilarPeiron — APPROVED** [review]
Tested locally and it works good!🚀
I added a couple of non-blocking comments.

File: public/app/features/alerting/unified/CloneRuleEditor.test.tsx (hunk 2 above)
Comment (konrad147) [reply public/app/features/alerting/unified/CloneRuleEditor.test.tsx]: Fixed by https://github.com/grafana/grafana/pull/73997

**Comment by konrad147** [comment]
After discussion, we decided to skip the backport
