### PR TITLE
Alerting: Add support for Sensu Go notification channel

### LINKED ISSUE #19908: Notifications no longer work against latest version of Sensu Go
Since moving to Sensu Go and repointing Grafana, the alerting mechanism to Sensu no longer works. 

Looking into it a little more, it seems that some of the fields that Sensu is expecting have changed slightly, causing it to (I think) ignore the API call due to it being malformed.

**What happened**:

Alert did not get recognised by Sensu

**What you expected to happen**:

Sensu should handle the alert

**How to reproduce it (as minimally and precisely as possible)**:

Point Grafana at Sensu Go backend.
Configure the notification config and click Send Test

**Anything else we need to know?**:

Ideally there should be 2 notification channels for Sensu. One for Sensu Core (the no longer maintained version), and another for Sensu Go (which is the new platform).

At a minimum I think these following values are required in the JSON:

```
check.proxy_entity_name
check.metadata.name
check.output
check.interval
check.issued
check.executed
check.status
check.handlers
```

**Environment**:
- Grafana version: Latest
- Data source type & version: N/A
- OS Grafana is installed on: RHEL 7
- User OS & Browser: MacOS & Chrome
- Grafana plugins: N/A

### PR DESCRIPTION
**Pull request by nixwiz**
**What this PR does / why we need it**:
Similar to current support for the older "Core" version of
Sensu, this commit add support for the newer version.

**Which issue(s) this PR fixes**:

Fixes #19908

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hugohaggmark — COMMENTED** [review]
Frontend changes look ok a bit confusing with 2 versions of sensu but I hope there is a description somewhere that helps the users?

**Comment by aknuds1** [comment]
Thanks, we'll review it this week.

**Review by mckn — COMMENTED** [review]
I agree with what @hugohaggmark said. What is the difference? Can it be expressed in a better way?

File: public/app/types/alerting.ts [hunk 1]
```diff
@@ -40,6 +40,7 @@ export type NotifierType =
   | 'hipchat'
   | 'email'
   | 'sensu'
+  | 'sensugo'
```
Comment (mckn) [inline public/app/types/alerting.ts:43]: I am referring to this change.

Comment (nixwiz) [reply public/app/types/alerting.ts:43]: What is referred to simply as 'sensu' in this context is the older version of the Sensu product.  It is also commonly referred to as Sensu Core.  It went EOL in 2019 December but still has a significant number of users.

'sensugo' refers to Sensu Go which is the next generation replacement product that went GA in 2018 December and is in active development.

Comment (mckn) [reply public/app/types/alerting.ts:43]: aha, got it! Then it makes sense to name it that way. Sorry for not getting this earlier 🙈

File: pkg/services/alerting/notifiers/sensugo.go [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+		"ruleURL":  ruleURL,
+	}
+
+	if sn.NeedsImage() && evalContext.ImagePublicURL != "" {
+		labels["imageUrl"] = evalContext.ImagePublicURL
+	}
+
+	bodyJSON.SetPath([]string{"check", "metadata", "labels"}, labels)
+
+	body, _ := bodyJSON.MarshalJSON()
```
Comment (aknuds1) [inline pkg/services/alerting/notifiers/sensugo.go:175]:
```suggestion
	body, err := bodyJSON.MarshalJSON()
	if err != nil {
		return err
	}
```

File: pkg/services/alerting/notifiers/sensugo_test.go [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+
+import (
+	"testing"
+
+	"github.com/grafana/grafana/pkg/components/simplejson"
+	"github.com/grafana/grafana/pkg/models"
+	. "github.com/smartystreets/goconvey/convey"
+)
+
+func TestSensuGoNotifier(t *testing.T) {
```
Comment (aknuds1) [inline pkg/services/alerting/notifiers/sensugo_test.go:11]: Please rewrite tests using the standard Go library + testify.

File: pkg/services/alerting/notifiers/sensugo_test.go [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+	Convey("Sensu Go notifier tests", t, func() {
+		Convey("Parsing alert notification from settings", func() {
+			Convey("empty settings should return error", func() {
+				json := `{ }`
+
+				settingsJSON, _ := simplejson.NewJson([]byte(json))
```
Comment (aknuds1) [inline pkg/services/alerting/notifiers/sensugo_test.go:17]:
```suggestion
				settingsJSON, err := simplejson.NewJson([]byte(json))
				So(err, ShouldBeNil)
```

File: pkg/services/alerting/notifiers/sensugo_test.go [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+				}`
+
+				settingsJSON, _ := simplejson.NewJson([]byte(json))
+				model := &models.AlertNotification{
+					Name:     "Sensu Go",
+					Type:     "sensugo",
+					Settings: settingsJSON,
+				}
+
+				not, err := NewSensuGoNotifier(model)
```
Comment (aknuds1) [inline pkg/services/alerting/notifiers/sensugo_test.go:46]:
```suggestion
				not, err := NewSensuGoNotifier(model)
				So(err, ShouldBeNil)
```

File: pkg/services/alerting/notifiers/sensugo_test.go [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+				sensuGoNotifier := not.(*SensuGoNotifier)
+
+				So(err, ShouldBeNil)
```
Comment (aknuds1) [inline pkg/services/alerting/notifiers/sensugo_test.go:49]:
```suggestion
```

**Review by aknuds1 — CHANGES_REQUESTED** [review]
I saw some issues that should be fixed, but bear in mind that we need to decide first if we want to include this new channel.

File: public/app/types/alerting.ts (hunk 1 above)
Comment (nixwiz) [reply public/app/types/alerting.ts:43]: I'm wondering if changing [this line](https://github.com/grafana/grafana/blob/3b27c8476aaebe78117ccc0a9aebf2c85b7a7d2e/pkg/services/alerting/notifiers/sensu.go#L17) (and the subsequent one) for the old/original version to "Sensu Core" or "Sensu Core (EOL)" would help in the differentiation.

File: pkg/services/alerting/notifiers/sensugo_test.go (hunk 3 above)
Comment (nixwiz) [reply pkg/services/alerting/notifiers/sensugo_test.go:12]: The tests were changed from convey to testify.

**Comment by aknuds1** [comment]
We're still discussing potential inclusion of Sensu Go support.

File: pkg/services/alerting/notifiers/sensugo.go [hunk 7]
```diff
@@ -0,0 +1,195 @@
...
+	})
+}
+
+// NewSensuGoNotifier is the constructor for the Sensu Go Notifier.
+func NewSensuGoNotifier(model *models.AlertNotification) (alerting.Notifier, error) {
+	url := model.Settings.Get("url").MustString()
+	apikey := model.Settings.Get("apikey").MustString()
+
+	if url == "" {
+		return nil, alerting.ValidationError{Reason: "Could not find url property in settings"}
```
Comment (achatterjee-grafana) [inline pkg/services/alerting/notifiers/sensugo.go:76]: Change to "Could not find URL property in settings."

File: pkg/services/alerting/notifiers/sensugo.go [hunk 8]
```diff
@@ -0,0 +1,195 @@
...
+	}
+	if apikey == "" {
+		return nil, alerting.ValidationError{Reason: "Could not find API Key property in settings"}
```
Comment (achatterjee-grafana) [inline pkg/services/alerting/notifiers/sensugo.go:79]: Change to: "Could not find the API Key property in settings."

**Review by achatterjee-grafana — COMMENTED** [review]
Added two copy-edit suggestions.

**Review by aknuds1 — COMMENTED** [review]
We have thought about this a bit, and are leaning towards accepting the PR.

However, we need facilities to make it maintainable. Could you also add a Sensu Go block to devenv/docker/blocks, so we can easily bring up a Docker Compose environment when we need to maintain/test it?

**Comment by nixwiz** [comment]
> We have thought about this a bit, and are leaning towards accepting the PR.
> 
> However, we need facilities to make it maintainable. Could you also add a Sensu Go block to devenv/docker/blocks, so we can easily bring up a Docker Compose environment when we need to maintain/test it?

I added that block.  Upon pushing my updates the build is now failing the `build-docs-website` step.  In reviewing the log, I'm not seeing where my changes from a7702ae would have affected that test.

**Comment by kylebrandt** [comment]
> > We have thought about this a bit, and are leaning towards accepting the PR.
> > However, we need facilities to make it maintainable. Could you also add a Sensu Go block to devenv/docker/blocks, so we can easily bring up a Docker Compose environment when we need to maintain/test it?
> 
> I added that block. Upon pushing my updates the build is now failing the `build-docs-website` step. In reviewing the log, I'm not seeing where my changes from [a7702ae](https://github.com/grafana/grafana/commit/a7702ae091287edf9646358ac93ebcb1ee61573a) would have affected that test.

Can you try merging master to resolve the build?

**Comment by nixwiz** [comment]
> Can you try merging master to resolve the build?

Yes, that resolved it.  Thank you!

**Comment by kylebrandt** [comment]
While this seems to work from the directory:

```
# kbrandt @ kbrandt-ws in ~/go/github.com/grafana/grafana/devenv/docker/blocks/sensugo on git:add-sensu-go o [11:00:42] 
$ docker-compose up
Creating network "sensugo_default" with the default driver
Creating volume "sensugo_sensu-backend-data" with default driver
Pulling sensu-backend (sensu/sensu:latest)...
latest: Pulling from sensu/sensu
```

There seems to be something wrong when wrong it with our devenv:

```
$ make devenv sources=sensugo
ERROR: In file './docker-compose.yaml', service must be a mapping, not a NoneType.
Deleting docker-compose.yaml
Adding Compose header to docker-compose.yaml
ERROR: In file './docker-compose.yaml', service must be a mapping, not a NoneType.
Makefile:131: recipe for target 'devenv' failed
make: *** [devenv] Error 1
```

**Comment by nixwiz** [comment]
> There seems to be something wrong when wrong it with our devenv:

This should be fixed now.

File: devenv/docker/blocks/sensugo/docker-compose.yaml [hunk 9]
```diff
@@ -0,0 +1,18 @@
+  sensu-backend:
+    image: sensu/sensu:latest
+    container_name: sensu-backend
+    ports:
+      - "3000:3000"
```
Comment (kylebrandt) [inline devenv/docker/blocks/sensugo/docker-compose.yaml:5]: Can the binding be changed here? 3000 is the default dev port for Grafana, so will conflict with a locally running dev instance.

Comment (nixwiz) [reply devenv/docker/blocks/sensugo/docker-compose.yaml:5]: Yes, port 3000 is the Web UI.  Which I doubt you would need/use.  I will change to 3080.

**Review by kylebrandt — APPROVED** [review]
Works with devenv for me

image

File: pkg/services/alerting/notifiers/sensugo.go [hunk 10]
```diff
@@ -0,0 +1,195 @@
...
+				PropertyName: "namespace",
+			},
+		},
+	})
+}
+
+// NewSensuGoNotifier is the constructor for the Sensu Go Notifier.
+func NewSensuGoNotifier(model *models.AlertNotification) (alerting.Notifier, error) {
+	url := model.Settings.Get("url").MustString()
+	apikey := model.Settings.Get("apikey").MustString()
```
Comment (papagian) [inline pkg/services/alerting/notifiers/sensugo.go:73]:
```suggestion
	apikey := model.DecryptedValue("apikey", model.Settings.Get("apikey").MustString())
```
`model.DecryptedValue()` searches for the field in the SecureSettings and only if it's not there assigns the fallback string

This is required otherwise the following check:
https://github.com/grafana/grafana/blob/54f886e9118dffa23d5c34f4ab4ce4ee304c51f3/pkg/services/alerting/notifiers/sensugo.go#L78-L81
prevents from having a provisioning configuration where the api key is defined under secure_settings like:
```
notifiers:
  - name: provisioned-sensugo
    type: sensugo
    org_id: 1
    org_name: Main Org.
    uid: abcde
    is_default: false
    settings:
      url: "http://localhost:8080"
    secure_settings:
      apikey: "somekey"
```

**Review by papagian — CHANGES_REQUESTED** [review]
Generally works fine!
I have requested some changes regarding securely storing the API key.

File: devenv/docker/blocks/sensugo/notes.md [hunk 11]
```diff
@@ -0,0 +1,39 @@
...
+```
+
+The output should look similar to this:
+
+```
+Created: /api/core/v2/apikeys/0a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d
+```
+
+
+## Configuring the notification channel
```
[the remark this answers is not in the document]
Comment (nixwiz) [reply devenv/docker/blocks/sensugo/notes.md:28]: Added a section to the notification docs via 7ec9271

File: pkg/services/alerting/notifiers/sensugo.go [hunk 12]
```diff
@@ -0,0 +1,196 @@
...
+	}
+
+	return &SensuGoNotifier{
+		NotifierBase: NewNotifierBase(model),
+		URL:          url,
+		Entity:       model.Settings.Get("entity").MustString(),
+		Check:        model.Settings.Get("check").MustString(),
+		Namespace:    model.Settings.Get("namespace").MustString(),
+		Handler:      model.Settings.Get("handler").MustString(),
+		APIKey:       model.DecryptedValue("apikey", model.Settings.Get("apikey").MustString()),
```
Comment (papagian) [inline pkg/services/alerting/notifiers/sensugo.go:90]:
```suggestion
		APIKey:       apikey,
```

**Review by papagian — CHANGES_REQUESTED** [review]
Thank you for your contribution and the delayed response.
It works fine but I have a small suggestion.

**Review by papagian — APPROVED** [review]
Great! one last thing: you have to synchronise your branch with master once again for the CI built to succeed in order to get it merged!

**Comment by nixwiz** [comment]
@papagian branch merged with master and pushed again, CI builds successful.  Thanks for your assistance!

File: pkg/services/alerting/notifiers/sensugo_test.go [hunk 13]
```diff
@@ -0,0 +1,56 @@
...
+
+	"github.com/grafana/grafana/pkg/components/simplejson"
+	"github.com/grafana/grafana/pkg/models"
+)
+
+func TestSensuGoNotifier(t *testing.T) {
+	json := `{ }`
+
+	settingsJSON, err := simplejson.NewJson([]byte(json))
+	assert.NoError(t, err)
```
Comment (aknuds1) [inline pkg/services/alerting/notifiers/sensugo_test.go:16]:
```suggestion
	require.NoError(t, err)
```

File: pkg/services/alerting/notifiers/sensugo_test.go [hunk 14]
```diff
@@ -0,0 +1,56 @@
...
+	model := &models.AlertNotification{
+		Name:     "Sensu Go",
+		Type:     "sensugo",
+		Settings: settingsJSON,
+	}
+
+	_, err = NewSensuGoNotifier(model)
+	assert.Error(t, err)
```
Comment (aknuds1) [inline pkg/services/alerting/notifiers/sensugo_test.go:24]:
```suggestion
	require.Error(t, err)
```

File: pkg/services/alerting/notifiers/sensugo_test.go [hunk 15]
```diff
@@ -0,0 +1,56 @@
...
+		"url": "http://sensu-api.example.com:8080",
+		"entity": "grafana_instance_01",
+		"check": "grafana_rule_0",
+		"namespace": "default",
+		"handler": "myhandler",
+		"apikey": "abcdef0123456789abcdef"
+	}`
+
+	settingsJSON, err = simplejson.NewJson([]byte(json))
+	assert.NoError(t, err)
```
Comment (aknuds1) [inline pkg/services/alerting/notifiers/sensugo_test.go:37]:
```suggestion
	require.NoError(t, err)
```

File: pkg/services/alerting/notifiers/sensugo_test.go [hunk 16]
```diff
@@ -0,0 +1,56 @@
...
+	model = &models.AlertNotification{
+		Name:     "Sensu Go",
+		Type:     "sensugo",
+		Settings: settingsJSON,
+	}
+
+	not, err := NewSensuGoNotifier(model)
+	assert.NoError(t, err)
```
Comment (aknuds1) [inline pkg/services/alerting/notifiers/sensugo_test.go:45]:
```suggestion
	require.NoError(t, err)
```

**Review by aknuds1 — APPROVED** [review]
Generally looks good to me, but left suggestions for some improvements to the tests. Basically, you should use `require.NoError` and `require.Error` instead of their `assert` equivalents, since you want to abort the tests if these tests fail, to avoid chaos/undefined behaviour in the following code.

File: pkg/services/alerting/notifiers/sensugo_test.go (hunk 16 above)
Comment (nixwiz) [reply pkg/services/alerting/notifiers/sensugo_test.go]: Changes made.
