### PR TITLE
Loki: Base maxDataPoints limits on query type

### LINKED ISSUE #26688: Default line limit set on Loki data source is not actually used in Grafana explorer
**What happened**:
Set default line limit in data source to 2500.

**What you expected to happen**:
Actual line limit used in Grafana Explorer is 1612.

**How to reproduce it (as minimally and precisely as possible)**:
- Have the Loki data source line limit default set to 2500 (from JSON provisioning)
- Visit https://{redacted}/explore and make sure Loki data source is selected
- Enter a query
- Line limit shown in in the UI is set to 1612 instead of 2500

image

**Anything else we need to know?**:
If you set the line limit override field in the query to 5000, it will now show "Limit: 5000 (502 returned)". Then empty the field and execute the query again: it now shows "Limit: 2500 (502 returned)".

(No matter what, this doesn't impact the query results but that's because of #26687)

**Environment**:
- Grafana version: Grafana 7.1.1
- Data source type & version: Loki 1.5.0
- OS Grafana is installed on: Linux
- User OS & Browser: Mac / Chrome

### PR DESCRIPTION
**Pull request by aocenas**
Fixes: https://github.com/grafana/grafana/issues/26688

In Explore right now we do not know what kind of query we are running before we get the response so we cannot pass different limit for log vs metric queries in Loki. So right now we always pass maxDataPoints limit based on the pixel width of the screen and then Loki data source decides whether to use that or use line limit defined in the query itself or from data source config.

### CODE REVIEW

File: public/app/plugins/datasource/loki/datasource.ts [hunk 1]
```diff
@@ -554,4 +545,16 @@ export function lokiSpecialRegexEscape(value: any) {
   return value;
 }
 
+/**
+ * Checks if the query expression uses function and so should return a time series instead of logs.
+ * Sometimes important to know that before we actually do the query.
+ */
+function isMetricsQuery(query: string): boolean {
```
Comment (aocenas) [inline public/app/plugins/datasource/loki/datasource.ts:552]: @ivanahuckova I think we can use this to check if we should run the instant query right? Cause right now we run the instant query also for logs query which I assume does not make much sense.

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/datasource.ts:552]: Yes! That makes sense to use it also there.

File: public/app/plugins/datasource/loki/datasource.ts [hunk 2]
```diff
@@ -186,31 +188,20 @@ export class LokiDatasource extends DataSourceApi<LokiQuery, LokiOptions> {
...
-    }
+    // For metric query we use maxDataPoints from the request options which should be something like width of the
+    // visualisation in pixels. In case of logs request we either use lines limit defined in the query target or
+    // global limit defined for the data source which ever is lower.
+    let maxDataPoints = isMetricsQuery(target.expr)
+      ? // We fallback to maxLines here because maxDataPoints is defined as possibly undefined. Not sure that can
+        // actually happen both Dashboards and Explore should send some value here. If not maxLines does not make that
+        // much sense but nor any other arbitrary value.
+        (options as DataQueryRequest<LokiQuery>).maxDataPoints || this.maxLines
+      : Math.min(target.maxLines || Infinity, this.maxLines);
```
Comment (aocenas) [inline public/app/plugins/datasource/loki/datasource.ts:199]: So this mimicks the current behaviour but I wonder if it makes sense. Shouldn't user be able to override the global limit from the query editor in both directions? Ie rise the limit for a particular query if needed? @davkal

File: public/app/plugins/datasource/loki/datasource.ts (hunk 1 above)
Comment (aocenas) [reply public/app/plugins/datasource/loki/datasource.ts:552]: Cool will add a PR after this is merged.

Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/datasource.ts:552]: 👍 awesome

File: public/app/plugins/datasource/loki/datasource.ts (hunk 2 above)
Comment (ivanahuckova) [reply public/app/plugins/datasource/loki/datasource.ts:199]: No, I don't think it makes sense. Because with logs query, we want to either use the `this.maxLines` if users didn't fill the query row Line limit, or if they filled it, then use that value.  So I think it should be something like `target.maxLines || this.maxLines;`. Not sure what should be the behaviour when user selects 0 in query row's Line limit - if showing 0 logs or showing default number of logs.

Comment (aocenas) [reply public/app/plugins/datasource/loki/datasource.ts:199]: I agree it looks weird at the moment. Will change it.

**Review by ivanahuckova — APPROVED** [review]
LGTM! Thanks for adding a comment regarding edge case. Good job. 🚀

**Comment by kylebrandt** [comment]
Removed cp label because it is in beta2, and see this in the v7.3.x branch already
