### PR TITLE
Dashboard: Fix Regression detected in time range variables under the refactorVariablesTimeRange feature flag

### LINKED ISSUE #71060: Dashboards: Possible regression detected in time range variables under the `refactorVariablesTimeRange` feature flag.
After trying out the new algorithm for resolving time range variables behind the `refactorVariablesTimeRange` feature flag, we've received feedback indicating a potential regression: 

When template variable is configured to be reloaded on time range change, and QueryType is Labelvalues with metrics is used, the time range change does not trigger template variable reload.
> 
> This result that on every time range change outdated template variable are used. This does not happen with old template variable loading as all one or more times.
> 
> How to repro:
> I created simple dashboards with some dependencies on template variables like below, and using promsource, label x!=”value” is just for debugging to see which query is which.
> 
> Template variable using Query Type label values with metrics, and all configured to be reloaded on time range change
> ```
> job                                                   label_values(http_server_requests_seconds_count{x!="job"},job)
> teamname                                    label_values(http_server_requests_seconds_count{x!="teamname", job=~"$job"},teamname)
> country                                          label_values(http_server_requests_seconds_count{x!="country", job=~"$job"},country)
> severity                                          label_values(http_server_requests_seconds_count{x!="severity", job=~"$job"},severity)
> dnsname                                       label_values(http_server_requests_seconds_count{x!="dnsname", job=~"$job", teamname=~"$teamname", country=~"$country", severity=~"$severity"},dnsname)
> dnsname_single                         http_server_requests_seconds_count{x!="dnsname_single", job=~"$job", teamname=~"$teamname", country=~"$country", severity=~"$severity", dnsname=~"$dnsname"}
> ```
> 
> Template variables using query Type Query Results with regexp /.*dnsname="(.*?)".*/ works
> ```
> 5xx:                                                  query_result( increase(http_server_requests_seconds_count{job=~"$job", dnsname=~"$appall", status=~"5..|None"}[$__range]  ) > 0)
> alerts                                               query_result (max_over_time(ALERTS{x!="alerts", job=~"$job", dnsname=~"$dnsname", alertstate="active"}[$__range:$range]  ) > 0)
> ```
> 
> Then just change time range and you notice that only template variables using Query results are reloaded, most template variables are not reloaded and contains wrong data.
> 
> What works as expected:
> Changing data source (no time range change) result reload of all template variables.
> Changing template variable like country value (no time range change) values result correctly reload of dependent variable only. All were not reloaded.
> 
> I also notice that reloading panels is not optimal, but this happen also with legacy templating.
> - Normal panels are refreshed correctly after timerange change when all template queries competed after “annotation query”.
> - If panel use “repeat by variables”, then visible repeated panels are refreshed when template variable are loaded, and again after “annotation query” al are reloaded. Cannot repro on small test dashboards. The parent panel which is repeated by variable is correctly loaded after “annotation”, but all repeated one are loaded twice.

### PR DESCRIPTION
**Pull request by axelavargas**
**What is this feature?**
The original algorithm did not account for situations where a variable set to refresh based on time range had a dependency on another variable that was not configured to refresh on time range.

##### The original dashboard from the customer:
A query variable with dependent variables relied on a DataSource variable. However, currently, we don't allow DataSource variables to be configured to refresh based on time range. In such cases, we need to add that original query variable to the list of variables to be refreshed.

variables system_9~2

**How to test this PR?**

- Enable locally `refactorVariablesTimeRange` feature flag
- Configure Prometheus datasource (use [robust perception](http://demo.robustperception.io:9090/))
- Import this dashboard: [Slow Template Variable Basic Exampless-1693929458840.txt](https://github.com/grafana/grafana/files/12525781/Slow.Template.Variable.Basic.Exampless-1693929458840.txt)
- Modify the time range of the dashboard
- Check the network and verify that 3 calls are being made 

**Why do we need this feature?**

Will fix slow template variable issue

**Who is this feature for?**

users with the feature flag enabled for now and later everyone 

**Which issue(s) does this PR fix?**:

Fixes #71060

**Special notes for your reviewer:**

- [x] Missing unit test of edge case
- [x] Fix betterer
- [x] Add better description and example to the PR

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/variables/state/helpers.ts [hunk 1]
```diff
@@ -161,3 +162,19 @@ export function getPreloadedState(
...
+  });
+  return variableNode;
+}
+
+// Some variable types have a refresh options, and it might be configured to refresh on time range change
+export function isVariableOnTimeRangeConfigured(variable: TypedVariableModel) {
+  return (
+    (variable.type === 'query' || variable.type === 'datasource' || variable.type === 'interval') &&
+    variable.refresh === VariableRefresh.onTimeRangeChanged
+  );
```
Comment (dprokop) [inline public/app/features/variables/state/helpers.ts:179]: This function looks funky. For datasource and interval there is no time range refresh configuration, why handling those types here?

File: public/app/features/variables/state/onTimeRangeUpdated.test.ts [hunk 2]
```diff
@@ -449,8 +469,97 @@ describe('when onTimeRangeUpdated is dispatched', () => {
...
+        .whenAsyncActionIsDispatched(onTimeRangeUpdated(key, range, dependencies), true);
+
+      // Defining the variables that are expected to be refreshed
+      // Based on the algorithm of getVariablesThatNeedRefreshNew, we have the following variables:
+      // - queryA, queryD and interval: These are variables with no dependents. According to the algorithm, should be refreshed.
+      // - queryE: This is a query variable with a dependent node (queryF) but also has a dependency on DsVar datasource variable.
+      //   because DSVar is not configured to refresh on time range,this means that queryE is the
+      //   variable that is expected to be refreshed
+      // Note: Variables 'b' and 'c', f are not expected to be in the refreshed variables list even though they're set to
+      // refresh on time range change. This is because they have dependencies ('b' and 'c' depend on 'a').
```
Comment (dprokop) [inline public/app/features/variables/state/onTimeRangeUpdated.test.ts:532]: You are describing queryA and queryD variables, but these are not defined in this test. Are those shared across multiple tests?

**Review by dprokop — COMMENTED** [review]
I get the idea, of this fix I think. But leaving some comments with questions.

File: public/app/features/variables/state/helpers.ts (hunk 1 above)
Comment (axelavargas) [reply public/app/features/variables/state/helpers.ts:179]: Yes, I was also surprised. Currently, we don't offer a UI configuration for time range refresh for either interval or datasource variables. However, when inspecting the Dashboard JSON, I noticed that interval variables had the default configuration set to "time range," and datasource variables had the property assigned to their model. With the datasource variable, I wasn't sure if we might receive provisioned dashboards with this default setting for time range. 

So, I decided to create this function, especially because in the original function, we were checking for the `refresh` prop and were using the `as QueryVariable` cast. 🙈

File: public/app/features/variables/state/onTimeRangeUpdated.test.ts (hunk 2 above)
Comment (axelavargas) [reply public/app/features/variables/state/onTimeRangeUpdated.test.ts:532]: indeed, I have the function `getTestContextVariables` that sets some base variables, and in this PR I added an extra variable D (with no dependents) to account for the edge case I missed last time :)

File: public/app/features/variables/state/helpers.ts (hunk 1 above)
Comment (dprokop) [reply public/app/features/variables/state/helpers.ts:179]: > I wasn't sure if we might receive provisioned dashboards with this default setting for time range.

Well, think this is a valid assumption, not sure if real case, but worth having this extra security. I suggest adding a comment about this to the function so that it won't get lost.

**Review by dprokop — APPROVED** [review]
