### PR TITLE
Security: Add disabled option for cookie samesite attribute

### LINKED ISSUE #19847: Chrome warning on SameSite attribute
**What happened**:
We embed grafana UI in our own app and configure grafana instance with oauth authentication.
To enable such embedding, we configure the grafana instance with:
########
[security]
cookie_samesite = none
##########

While doing so, chrome issues a warning:
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Furthermore, when enabling the flag 'SameSite by default cookies' in chrome the oauth login fails.

From my understanding because of a bug in safari (see issue #18332) when configuring same_site = none the attribute SameSite is dropped from the cookie, but this will cause an issue on future chrome version 80, when this flag will be enabled by default.

**What you expected to happen**:
Login with oauth would succeed when flag 'SameSite by default cookies' in chrome is enabled.

**How to reproduce it (as minimally and precisely as possible)**:
- Configure grafana to use oauth mechanism.
- Embed grafana UI in another app.
- Enable chrome 'SameSite by default cookies' flag.
- Try to login into grafana from the embedded iframe.

**Environment**:
- Grafana version: v6.3.6
- Data source type & version:
- OS Grafana is installed on: GrafanaLabs
- User OS & Browser: MacOS. Chrome 77.0.3865.120
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Breaking change: If disabled the cookie samesite cookie attribute
will not be set, but if none the attribute will be set and is a
breaking change compared to before where none did not render the
attribute. This was due to a known issue in Safari.

Needs to add docs and breaking change notice before merge.

**Which issue(s) this PR fixes**:
Fixes #19847 

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/middleware/middleware_test.go [hunk 1]
```diff
@@ -287,6 +285,21 @@ func TestMiddlewareContext(t *testing.T) {
 					So(sc.resp.Header().Get("Set-Cookie"), ShouldEqual, expectedCookie.String())
 				})
 			}
+
+			Convey("Should not set cookie with setting.SameSite", func() {
```
Comment (aknuds1) [inline pkg/middleware/middleware_test.go]: Do you mean "with setting.CookieSameSiteDisabled"?

File: pkg/setting/setting.go [hunk 2]
```diff
@@ -718,18 +720,24 @@ func (cfg *Cfg) Load(args *CommandLineArgs) error {
...
-		"lax":    http.SameSiteLaxMode,
-		"strict": http.SameSiteStrictMode,
-		"none":   http.SameSiteDefaultMode,
-	}
 
-	if samesite, ok := validSameSiteValues[samesiteString]; ok {
-		CookieSameSite = samesite
-		cfg.CookieSameSite = CookieSameSite
+	if samesiteString == "disabled" {
+		CookieSameSiteDisabled = false
```
Comment (aknuds1) [inline pkg/setting/setting.go]: Should it be `true` here?

**Review by aknuds1 — COMMENTED** [review]
Saw a couple of things I'm unsure about.

File: pkg/middleware/middleware_test.go [hunk 3]
```diff
@@ -287,6 +285,21 @@ func TestMiddlewareContext(t *testing.T) {
...
+				setting.CookieSameSiteDisabled = true
```
Comment (papagian) [inline pkg/middleware/middleware_test.go]: In order to test this behaviour you need to set also `setting.CookieSameSiteMode` to some valid `SameSite` (e.g. http.SameSiteDefaultMode) value otherwise the default is 0 and in that case `SameSite` is not written anyway because none of [these](https://github.com/golang/go/blob/go1.13.1/src/net/http/cookie.go#L220) `case` statements are true.

**Review by papagian — CHANGES_REQUESTED** [review]
Generally LGTM! Only some minor fixes and maybe we need to update also [this](https://grafana.com/docs/grafana/latest/reference/share_panel/#embed-panel) in the docs in addition to the breaking change notice.

File: pkg/middleware/middleware_test.go (hunk 3 above)
Comment (marefr) [reply pkg/middleware/middleware_test.go]: Not sure I follow. We check if same site is not disabled [here](https://github.com/grafana/grafana/pull/21472/files/4a52840071461d5e40fcac94278d7d8f41b6ef05#diff-8664c49bf50694ac622b7cb861b8dd1fR41-R42) and only then we set the same site attribute on the cookie. Or are you just referring to setting same site mode for the completeness of the test?

File: docs/sources/installation/configuration.md [hunk 4]
```diff
@@ -361,7 +361,8 @@ Set to `true` if you host Grafana behind HTTPS. Default is `false`.
 
 ### cookie_samesite
 
-Sets the `SameSite` cookie attribute and prevents the browser from sending this cookie along with cross-site requests. The main goal is mitigate the risk of cross-origin information leakage. It also provides some protection against cross-site request forgery attacks (CSRF),  [read more here](https://www.owasp.org/index.php/SameSite). Valid values are `lax`, `strict` and `none`. Default is `lax`.
+Sets the `SameSite` cookie attribute and prevents the browser from sending this cookie along with cross-site requests. The main goal is mitigate the risk of cross-origin information leakage. It also provides some protection against cross-site request forgery attacks (CSRF),  [read more here](https://www.owasp.org/index.php/SameSite). Valid values are `lax`, `strict`, `none` and `disabled`. Default is `lax`. Using value `disabled` will not
+add any `SameSite` attribute to cookies.
```
Comment (aknuds1) [inline docs/sources/installation/configuration.md]: Nit, but why is there a line break here? Considering the line before is so long.

File: docs/sources/reference/share_panel.md [hunk 5]
```diff
@@ -32,7 +32,7 @@ https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&from=156871968017
 
 You can embed a panel using an iframe on another web site. This tab will show you the html that you need to use.
 
-> *Notice* This sharing require either anonymous access or setting [cookie_samesite]({{< relref "../installation/configuration.md#cookie-samesite" >}}) to none
+> *Note* This sharing require [allow_embedding]({{< relref "../installation/configuration.md#allow-embedding" >}}) enabled and anonymous access or proper configuration of the [cookie_samesite]({{< relref "../installation/configuration.md#cookie-samesite" >}}) setting.
```
Comment (aknuds1) [inline docs/sources/reference/share_panel.md]:
```suggestion
> *Note* This sharing requires [allow_embedding]({{< relref "../installation/configuration.md#allow-embedding" >}}) enabled and anonymous access or proper configuration of the [cookie_samesite]({{< relref "../installation/configuration.md#cookie-samesite" >}}) setting.
```

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Couple of nits.

**Review by aknuds1 — APPROVED** [review]
LGTM!

File: CHANGELOG.md [hunk 6]
```diff
@@ -6,6 +6,7 @@
 
 ## Breaking changes
 * **PagerDuty**: Change `payload.custom_details` field in PagerDuty notification to be a JSON object instead of a string.
+* **Security**: The `[security]` setting `cookie_samesite` configured to `none` now renders cookies with `SameSite=None` attribute compared to before where no `SameSite` attribute was added to cookies. To get the old behavior use value `disabled` instead of `none`. Read [upgrading](https://grafana.com/docs/grafana/latest/installation/upgrading/#upgrading-to-v6-6) for more information.
```
Comment (oddlittlebird) [inline CHANGELOG.md]:
```suggestion
* **Security**: The `[security]` setting `cookie_samesite` configured to `none` now renders cookies with `SameSite=None` attribute compared to before where no `SameSite` attribute was added to cookies. To get the old behavior, use value `disabled` instead of `none`. Refer to [Upgrade Grafana](https://grafana.com/docs/grafana/latest/installation/upgrading/#upgrading-to-v6-6) for more information.
```

File: docs/sources/installation/configuration.md [hunk 7]
```diff
@@ -361,7 +361,7 @@ Set to `true` if you host Grafana behind HTTPS. Default is `false`.
 
 ### cookie_samesite
 
-Sets the `SameSite` cookie attribute and prevents the browser from sending this cookie along with cross-site requests. The main goal is mitigate the risk of cross-origin information leakage. It also provides some protection against cross-site request forgery attacks (CSRF),  [read more here](https://www.owasp.org/index.php/SameSite). Valid values are `lax`, `strict` and `none`. Default is `lax`.
+Sets the `SameSite` cookie attribute and prevents the browser from sending this cookie along with cross-site requests. The main goal is mitigate the risk of cross-origin information leakage. It also provides some protection against cross-site request forgery attacks (CSRF),  [read more here](https://www.owasp.org/index.php/SameSite). Valid values are `lax`, `strict`, `none` and `disabled`. Default is `lax`. Using value `disabled` will not add any `SameSite` attribute to cookies.
```
Comment (oddlittlebird) [inline docs/sources/installation/configuration.md]:
```suggestion
Sets the `SameSite` cookie attribute and prevents the browser from sending this cookie along with cross-site requests. The main goal is to mitigate the risk of cross-origin information leakage. This setting also provides some protection against cross-site request forgery attacks (CSRF),  [read more about SameSite here](https://www.owasp.org/index.php/SameSite). Valid values are `lax`, `strict`, `none`, and `disabled`. Default is `lax`. Using value `disabled` does not add any `SameSite` attribute to cookies.
```

File: docs/sources/installation/upgrading.md [hunk 8]
```diff
@@ -226,3 +226,14 @@ The handling of multi-valued template variables in dimension values has been cha
 ## Upgrading to v6.6
 
 The Generic OAuth setting `send_client_credentials_via_post`, used for supporting non-compliant providers, has been removed. From now on, Grafana will automatically detect if credentials should be sent as part of the URL or request body for a specific provider. The result will be remembered and used for additional OAuth requests for that provider.
+
+### Important changes regarding SameSite cookie attribute
+
+The Stable version of Chrome 80 will treat cookies as `SameSite=Lax` by default if no `SameSite` attribute is specified, see https://www.chromestatus.com/feature/5088147346030592.
+
+Due to this change in Chrome the `[security]` setting `cookie_samesite` configured to `none` now renders cookies with `SameSite=None` attribute compared to before where no `SameSite` attribute was added to cookies. To get the old behavior use value `disabled` instead of `none`, see [cookie_samesite]({{< relref "configuration/#cookie-samesite" >}}) for more information.
```
Comment (oddlittlebird) [inline docs/sources/installation/upgrading.md]:
```suggestion
Due to this change in Chrome, the `[security]` setting `cookie_samesite` configured to `none` now renders cookies with `SameSite=None` attribute compared to before where no `SameSite` attribute was added to cookies. To get the old behavior, use value `disabled` instead of `none`, see [cookie_samesite in Configuration]({{< relref "configuration/#cookie-samesite" >}}) for more information.
```

File: docs/sources/installation/upgrading.md [hunk 9]
```diff
@@ -226,3 +226,14 @@ The handling of multi-valued template variables in dimension values has been cha
 ## Upgrading to v6.6
 
 The Generic OAuth setting `send_client_credentials_via_post`, used for supporting non-compliant providers, has been removed. From now on, Grafana will automatically detect if credentials should be sent as part of the URL or request body for a specific provider. The result will be remembered and used for additional OAuth requests for that provider.
+
+### Important changes regarding SameSite cookie attribute
+
+The Stable version of Chrome 80 will treat cookies as `SameSite=Lax` by default if no `SameSite` attribute is specified, see https://www.chromestatus.com/feature/5088147346030592.
```
Comment (oddlittlebird) [inline docs/sources/installation/upgrading.md]:
```suggestion
Chrome 80 treats cookies as `SameSite=Lax` by default if no `SameSite` attribute is specified, see https://www.chromestatus.com/feature/5088147346030592.
```

File: docs/sources/installation/upgrading.md [hunk 10]
```diff
@@ -226,3 +226,14 @@ The handling of multi-valued template variables in dimension values has been cha
...
+
+Due to this change in Chrome the `[security]` setting `cookie_samesite` configured to `none` now renders cookies with `SameSite=None` attribute compared to before where no `SameSite` attribute was added to cookies. To get the old behavior use value `disabled` instead of `none`, see [cookie_samesite]({{< relref "configuration/#cookie-samesite" >}}) for more information.
+
+*Note:* There is currently a bug affecting Mac OSX and iOS which causes `SameSite=None` cookies to be inadvertently treated as `SameSite=Strict` and therefore not sent with cross-site requests, see https://bugs.webkit.org/show_bug.cgi?id=198181. Until this is fixed, `SameSite=None` may not work properly on Safari.
```
Comment (oddlittlebird) [inline docs/sources/installation/upgrading.md]:
```suggestion
**Note:** There is currently a bug affecting Mac OSX and iOS that causes `SameSite=None` cookies to be treated as `SameSite=Strict` and therefore not sent with cross-site requests. (See https://bugs.webkit.org/show_bug.cgi?id=198181.) Until this is fixed, `SameSite=None` might not work properly on Safari.
```

File: docs/sources/installation/upgrading.md [hunk 11]
```diff
@@ -226,3 +226,14 @@ The handling of multi-valued template variables in dimension values has been cha
...
+
+This version of Chrome will also reject insecure `SameSite=None` cookies, see https://www.chromestatus.com/feature/5633521622188032 for more information. Make sure that you
```
Comment (oddlittlebird) [inline docs/sources/installation/upgrading.md]:
```suggestion
This version of Chrome also rejects insecure `SameSite=None` cookies. See https://www.chromestatus.com/feature/5633521622188032 for more information. Make sure that you
```

File: docs/sources/reference/share_panel.md [hunk 12]
```diff
@@ -32,7 +32,7 @@ https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&from=156871968017
 
 You can embed a panel using an iframe on another web site. This tab will show you the html that you need to use.
 
-> *Notice* This sharing require either anonymous access or setting [cookie_samesite]({{< relref "../installation/configuration.md#cookie-samesite" >}}) to none
+> *Note* This sharing requires [allow_embedding]({{< relref "../installation/configuration.md#allow-embedding" >}}) enabled and anonymous access or proper configuration of the [cookie_samesite]({{< relref "../installation/configuration.md#cookie-samesite" >}}) setting.
```
Comment (oddlittlebird) [inline docs/sources/reference/share_panel.md]:
```suggestion
> **Note:** This sharing requires [allow_embedding]({{< relref "../installation/configuration.md#allow-embedding" >}}) enabled and anonymous access, or proper configuration of the [cookie_samesite]({{< relref "../installation/configuration.md#cookie-samesite" >}}) setting.
```

**Review by oddlittlebird — APPROVED** [review]

File: pkg/middleware/middleware_test.go (hunk 3 above)
Comment (papagian) [reply pkg/middleware/middleware_test.go]: The latter

**Review by papagian — APPROVED** [review]
LGTM
