### PR TITLE
CustomScrollbar: Invoke setScrollTop callback only after scrolling finishes

### LINKED ISSUE #33815: PromQL Query Editor: scrolling through queries with mouse is not usable
**What happened**:
1. Open a PromQL Query Editor (data from prometheus) with more than one query.
2. Try to scroll up / down through queries with the mouse over the editor panel.
3. Queries are just "shaking" without any significant movement.

**What you expected to happen**:
Queries moving up / down according to the mouse.

**How to reproduce it (as minimally and precisely as possible)**:
See **What happened** above.
 
**Anything else we need to know?**:
Regarding the issues I've been experiencing with the editor so far I would really beg for a possibility to switch off all those editor's "[smart functionalities](https://github.com/grafana/grafana/issues/30997)"... 

**Environment**:
- Grafana version: Grafana v7.5.5
- Data source type & version: prometheus v2.26.0
- OS Grafana is installed on: Linux / Ubuntu 20.04.2 LTS
- User OS & Browser: Firefox 88.0 (64-bit)
- Grafana plugins: ...
- Others:

### LINKED ISSUE #34165: Cannot fast-scroll query section of graph
**What happened**:
I tried scrolling fast the query section of a graph, but instead of actually going faster it got stuck pretty often (it's just a 2-queries graph)

**What you expected to happen**:
It should've gotten to the end quickly

**How to reproduce it (as minimally and precisely as possible)**:
Open a graph query settings, put your mouse cursor on the queries and try to scroll fast

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0 beta 1
- Data source type & version: InfluxDB
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows 10 - Firefox

### PR DESCRIPTION
**Pull request by ifrost**
**What this PR does / why we need it**:

*Problem*

Firefox (Gecko) supports smooth scrolling meaning that when it's enabled...

> (...) then the view doesn't scroll immediately but schedules a series of small-step scroll events to be processed over time. 

Gecko docs: https://wiki.mozilla.org/Gecko:How_Scrolling_Works

QueryGroup listens to scroll events and updates the scroll back to the dispatched value ([here](https://github.com/grafana/grafana/blob/main/public/app/features/query/components/QueryGroup.tsx#L278)). However, the scrollTop value is set in [CustomScrollbar with useEffect()](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx#L49) meaning it's set only after the render. At that point the scroll might haven already been moved farther by the next small-step event. This causes the scroll to be reset to a lower value and stop after the first small-step event. 

Example:
- native scroll event is dispatched { scrollTop: 101 }
- QueryGroup passes scrollTop=101 to CustomScrollbar 
- CustomScrollbar schedules setting the scrollTop with useEffect
- another native scroll event is dispatched { scrollTop: 102 }
- useEffect is triggered setting the scroll back to 101

*Fix*

The PR changes that `setScrollTop` callback is triggered only on the scroll end. This is a breaking change in API. Should I instead introduce a new method `onScrollStop`?

Note that DashboardPage is not affected by this bug because the scrollTop value is not being passed back to CustomScrollbar. It could also be a solution for QueryGroup but feels clunky as it's not really needed. I also tried disabling smooth scrolling with `scroll-behavior` CSS but it didn't work.

*How to test it?*

I was able to test it on a Mac using a mouse. A single roll triggers multiple scroll events. Not sure if there's a way to reproduce it with a trackpad.

UX wise it feels like the scroll is extremely slow:

https://user-images.githubusercontent.com/745532/118611612-55bbb900-b7bd-11eb-9880-462ac307aed9.mov

Here's how it looks in Chrome (but Chrome dispatches only single scroll event with bigger delta):

https://user-images.githubusercontent.com/745532/118610958-9c5ce380-b7bc-11eb-81f8-219d19742d25.mov

**Which issue(s) this PR fixes**:

Fixes #34165 
Fixes #33815

**Special notes for your reviewer**: N/A

### CODE REVIEW

File: packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx [hunk 1]
```diff
@@ -105,7 +107,9 @@ export const CustomScrollbar: FC<Props> = ({
     <Scrollbars
       ref={ref}
       className={classNames(styles.customScrollbar, className)}
-      onScroll={setScrollTop}
+      onScrollStop={() => {
+        ref.current && setScrollTop && setScrollTop(ref.current.getValues());
+      }}
```
Comment (torkelo) [inline packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx:112]: this will create a new callback every render, even when setScrollTop is not passed from parent, could we memoize this callback with useCallback?

Comment (ifrost) [reply packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx]: Updated

**Review by torkelo — APPROVED** [review]
