### PR TITLE
A11y: Fixed keyboard accessibility in Tooltip Component

### LINKED ISSUE #70964: A11y: Fix keyboard accessibility in `packages/grafana-ui/src/components/Tooltip/Popover.tsx`
# How to make progress on this issue

- 🔍 open the file and search for `TODO: fix keyboard a11y`
- ❌ remove the `eslint-disable` comment
- 🔧 fix the lint error(s) that should now be showing
  - this will be heavily dependant on context
  - should you be able to interact with this element via the keyboard or is there another element that already handles the same behaviour via the keyboard?
  - in some cases, the best fix is to **use the correct semantic element** for the job. if something behaves like a button but we want it to look different, we can still use the `<button type="button">` element and style it appropriately. this will handle all our keyboard accessibility needs for us. there's even a handy [`clearButtonStyles`](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Button/Button.tsx#L306) util to undo the basic button styling.
  - if using a `<button>` or other similar interactive element is not appropriate, refer to the documentation [here](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/click-events-have-key-events.md) and [here](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-static-element-interactions.md). this will likely involve setting a `role` and implementing a custom `onKeyPress`
- 🧪 test it!
  - can you interact with this element using the keyboard now?
- 🥳 celebrate for making grafana a better product!

### PR DESCRIPTION
**Pull request by RoxanaAnamariaTurc**
**What is this feature?**

Fixed keyboard accessibility in Tooltip component.

**Why do we need this feature?**

To ensure the components are accessible.

**Who is this feature for?**

Everyone.

**Which issue(s) does this PR fix?**:

Fixes #70964

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/Tooltip/Popover.tsx [hunk 1]
```diff
@@ -66,9 +66,8 @@ class Popover extends PureComponent<Props> {
                 >
                   {({ ref, style, placement, arrowProps, update }) => {
                     return (
-                      // TODO: fix keyboard a11y
-                      // eslint-disable-next-line jsx-a11y/no-static-element-interactions
-                      <div
+                      <button
```
Comment (ashharrison90) [inline packages/grafana-ui/src/components/Tooltip/Popover.tsx:69]: haven't had time to properly look at this (can look after lunch), but don't think this should be a `button`

**Review by ashharrison90 — CHANGES_REQUESTED** [review]

**Review by ashharrison90 — APPROVED** [review]
i think this makes sense:
- it actually fixes a bug where we weren't passing all the props we say are allowed to the popover 👍 
- i don't think the lint rule is exposing a real problem here
