### PR TITLE
LibraryPanels: Fixes connections after dashboard import

### LINKED ISSUE #34454: Library Panels: Exporting and then importing it to the same Grafana instance should work
1. Create a dashboard with at least one library panel
2. Share and export it (doesn't matter if it is for sharing externally or not)
3. Copy the shared Dashboard json
4. Import the shared Dashboard json
5. Expect the imported dsahboard to load [OK]
5. Expect to see the same library panels appear in the imported dashboard [Not OK]
image

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR fixes so we add appropriate connections to the imported dashboard. 

**Which issue(s) this PR fixes**:
Fixes #34454

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/services/librarypanels/librarypanels.go [hunk 1]
```diff
@@ -179,8 +180,24 @@ func (lps *LibraryPanelService) ConnectLibraryPanelsForDashboard(c *models.ReqCo
...
-		libraryPanels = append(libraryPanels, uid)
+		_, exists := libraryPanels[uid]
+		if !exists {
+			libraryPanels[uid] = uid
+		}
+	}
+
+	elementUIDs := make([]string, 0, len(libraryPanels))
+	for libraryPanel := range libraryPanels {
+		elementUIDs = append(elementUIDs, libraryPanel)
```
Comment (hugohaggmark) [inline pkg/services/librarypanels/librarypanels.go:191]: While fixing the issue, I realized that we were potentially calling connect several times for the same UID because we weren't using a map. I added this little snippet to handle that.

**Review by dprokop — APPROVED** [review]
My golang mojo is low, but reading this code I cannot see anything suspicious :)

**Review by aknuds1 — APPROVED** [review]
