### PR TITLE
Explore: Prevent panes from disappearing when resizing window in split view

### LINKED ISSUE #55693: Explore: Resizing split view when coming out of full screen moves panes
**What happened**: With the resizable panes now available in explore, the pane width seems to react with the window size coming out of full screen view, meaning one pane will be all the way over. Buttons can also be messed up in this instance.

**What you expected to happen**: 
Panes to stay roughly the same ratio when going into or out of full screen view.

**How to reproduce it (as minimally and precisely as possible)**:
1. Start with maximized browser window (green button on osx)
1. drag pane over to be more to one side
1. Make the window normal size (green button on osx)
1. Notice one side is completely minimized, the resize bar is right up against the side nav. 

**Anything else we need to know?**: Thanks to @hairyhenderson for the QA :) 

**Environment**:
- Grafana version: main
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by gelicia**
**What this PR does / why we need it**:
Resizing the browser window can push window panes to be more narrow than what is allowed. This PR looks for window resize events so it can ensure the ratio of panes is kept and neither pane goes under the minimum width.

The pane resizing is easier to see when you manually resize by dragging a window corner, but entering and exiting fullscreen can move panes around in ways that are not obvious.

**Which issue(s) this PR fixes**:
Fixes #55693

### CODE REVIEW

File: public/app/features/explore/Wrapper.tsx [hunk 1]
```diff
@@ -118,6 +124,25 @@ class WrapperUnconnected extends PureComponent<Props, WrapperState> {
...
+    let newRightPaneWidth = Math.floor(windowWidth * rightPaneRatio);
+    if (newRightPaneWidth < this.minWidth) {
+      // if right pane is too narrow, make min width
+      newRightPaneWidth = this.minWidth;
+    } else if (windowWidth - newRightPaneWidth < this.minWidth) {
+      // if left pane is too narrow, make right pane = window - minWidth
+      newRightPaneWidth = windowWidth - this.minWidth;
+    }
+
+    this.setState({ windowWidth, rightPaneWidth: newRightPaneWidth });
```
Comment (ifrost) [inline public/app/features/explore/Wrapper.tsx:143]: Works fine but I wonder if it'd be simpler to keep the ratio in the state instead of width, what do you think? This way we would not need to recalculate it here to adjust widths. What is more at the moment resizing feels a bit odd with only one pane being squeezed and not keeping the ratio.

**Review by ifrost — CHANGES_REQUESTED** [review]
Works fine, though it'd be nice to have it covered with tests 🎉 Also I'm just thinking if there's maybe a simpler way to tackle this problem. Let me know what you think

**Review by ifrost — APPROVED** [review]
We've discussed in the standup and we agreed we can merge it but as we have similar hacks in other places (e.g. in Dashboards) we should create a work item to come up with a better solution that doesn't require such workarounds.
