### PR TITLE
Alerting: Store alertmanager configuration history in a separate table in the database

### LINKED ISSUE #59845: Alerting: Alertmanager configuration truncation in MySQL 8
**What happened**:

Many of the Alertmanager resources are stored in a single JSON blob in the database, as a single string field.

When running against MySQL 8.0.28, the JSON blob will be truncated once it reaches a certain size (roughly 60-100KB). This completely breaks the alerting config.

This bug does not reproduce against MySQL 5.7.40 with the same configuration, in the same environment.

The specific size is not clear. We've seen it truncate at different points on different deployments at the same MySQL version. One case truncated at 65KB, another truncated at 108KB.

The field in question is of type `MEDIUMTEXT`, which according to MySQL docs [should not truncate until 16MB](https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html#data-types-storage-reqs-strings). In practice it truncates far earlier, only on MySQL 8.

**What you expected to happen**:

I expected the alerting configuration to not be truncated.

**How to reproduce it (as minimally and precisely as possible)**:

1. Set up Grafana against MySQL 8.0.28. I used AWS RDS to do this quickly.
2. Create a lot of alerting objects. In my case, tried to create 1000 contact points.
3. The alertmanager config becomes broken after the first 300 or so, with an error like `unexpected end of JSON value`

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version: n/a
- OS Grafana is installed on: Linux
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: MySQL 8.0.28

### PR DESCRIPTION
**Pull request by alexweav**
**What is this feature?**

Instead of storing all (both active and historical) configurations in the same table, we now store the active configurations in a separate table from the historical ones.

**Why do we need this feature?**

This drastically simplifies the SQL required to manage configurations. This fixes a couple existing bugs, and would have prevented others from happening.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/59845
Contributes https://github.com/grafana/grafana/issues/60053

**Special notes for your reviewer**:

I decided to revert the original attempt at this. The migration ran into a known issue in MySQL where if a certain query optimization was applied, the query would fail, so it failed on a subset of mysql environments.

https://github.com/grafana/grafana/pull/60197

This PR is exactly the same, except for the migration. The migration logic has been re-implemented in Golang instead of SQL, and now uses only extremely trivial SQL commands, issued through the ORM where possible.

I'm performing the same test suite as before, on it. So far, everything is working well. Posting now

### CODE REVIEW

File: pkg/services/ngalert/store/alertmanager.go [hunk 1]
```diff
@@ -103,109 +113,25 @@ func (st *DBstore) UpdateAlertmanagerConfiguration(ctx context.Context, cmd *mod
...
-			WHERE 
-				org_id = ? 
-			AND 
-				id = (SELECT MAX(id) FROM alert_configuration WHERE org_id = ?) 
-			AND 
-				configuration_hash = ?
-		)`
-	}
-}
-
```
Comment (JohnnyQQQQ) [inline pkg/services/ngalert/store/alertmanager.go:208]: Gald we could remove that 👍

**Review by JohnnyQQQQ — APPROVED** [review]
LGTM
