### PR TITLE
Navigation: Fix bookmarks when Grafana is running under subpath

### LINKED ISSUE #102678: Navigation: Bookmarks are not working correctly under subpath
### What happened?

When using a Grafana instance under a subpath, bookmarks are not showing up after reload.

### What did you expect to happen?

Bookmarks to be visible when grafana is run under subpath (Bookmarks list is empty).

### Did this work before?

Not likely, since the feature is under public preview.

### How do we reproduce it?

1.Deploy grafana under subpath - `docker run --rm --name grafana -p 3000:3000 -e GF_SERVER_ROOT_URL=/grafana -e GF_SERVER_SERVE_FROM_SUB_PATH=true grafana/grafana:11.5.2`
2.Login
3.Bookmark some pages
4.Reload the browser tab

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 11.5.2
OS: Docker
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by matejkubinec**
**What is this feature?**

Appends application subpath when searching for the bookmarks menu item.

Bookmarks should now be visible after page reload.

**Which issue(s) does this PR fix?**:

Fixes #102678

### CODE REVIEW

File: public/app/core/components/AppChrome/MegaMenu/MegaMenu.tsx [hunk 1]
```diff
@@ -43,7 +43,7 @@ export const MegaMenu = memo(
       .map((item) => enrichWithInteractionTracking(item, state.megaMenuDocked));
 
     if (config.featureToggles.pinNavItems) {
-      const bookmarksItem = findByUrl(navItems, '/bookmarks');
+      const bookmarksItem = findByUrl(navItems, config.appSubUrl + '/bookmarks');
```
Comment (ashharrison90) [inline public/app/core/components/AppChrome/MegaMenu/MegaMenu.tsx:46]: i think finding by id might be safer instead 👍 
```suggestion
      const bookmarksItem = navItems.find((item) => item.id === 'bookmarks');
```

**Review by ashharrison90 — COMMENTED** [review]
hey @matejkubinec 👋 

thanks for raising this! minor suggestion to use `id` instead, otherwise looks great 🙌

File: public/app/core/components/AppChrome/MegaMenu/MegaMenu.tsx (hunk 1 above)
Comment (matejkubinec) [reply public/app/core/components/AppChrome/MegaMenu/MegaMenu.tsx]: Makes sense, updated.

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍 the fix will go out in grafana 12

thanks for your contribution! 🙇
