### PR TITLE
TimeSeries/Barchart: Only show default label for y axis

### LINKED ISSUE #42966: Label is set on both Axis instead of only Y axis
**What happened**: I set "test" Label in a default time series => I can see this label for both Y and X axis

**What you expected to happen**: To see this label only on Y axis like in the doc

**How to reproduce it (as minimally and precisely as possible)**: just set a label on a time series

**Anything else we need to know?**: Maybe a 2nd Label field for X axis could be a good idea

**Environment**: using last grafana docker oss image
- Grafana version: v8.3.1 (b9eacd93e9)
- Data source type & version: PostgreSQL 12+
- OS Grafana is installed on: docker Alpine image
grafana-screen

- User OS & Browser: Windows and Firefox
- Grafana plugins: None (only default)
- Others:

### PR DESCRIPTION
**Pull request by oscarkilhed**
**What this PR does / why we need it**:
Only shows the label for the Y axis as it was before the change to allow X axis labels. X axis labels can still be set with overrides. XY chart is still a bit messy.

**Which issue(s) this PR fixes**:

Fixes #42966

### CODE REVIEW

File: packages/grafana-ui/src/options/builder/axis.tsx [hunk 1]
```diff
@@ -38,7 +38,7 @@ export function addAxisConfig(
       },
       showIf: (c) => c.axisPlacement !== AxisPlacement.Hidden,
       // no matter what the field type is
```
Comment (dprokop) [inline packages/grafana-ui/src/options/builder/axis.tsx:40]: This comment ain't relevant anymore :)
```suggestion
      // Do not apply default settings to time and string fields which are used as x-axis fields in Time series and Bar chart panels
```

**Review by dprokop — APPROVED** [review]
Clever solution I must say:)
