### PR TITLE
Alerting: Ensure Discord notification is sent when metric name is absent

### LINKED ISSUE #30875: Discord alert does not send when `"name"` field is empty
**What happened**: Discord alerts do not send when legend is set to `{{hostname}}`.

**What you expected to happen**: Discord alerts should send with the alert's `"name"` field populated with the hostname of the device.

**How to reproduce it (as minimally and precisely as possible)**:
- Create an alert channel for Discord and configure/test it.
- Create a panel, and set the legend to `{{hostname}}`
- Create an alert on that panel. The alert will not trigger, but *will* send an OK message when the issue resolves.

**Anything else we need to know?**:
When sending the alert, the Grafana logs read:

```sh
t=2021-02-03T02:39:02+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.discord webhook_url=[my discord webhook]
t=2021-02-03T02:39:02+0000 lvl=eror msg="Failed to send notification to Discord" logger=alerting.notifier.discord error="Webhook response status 400 Bad Request"
t=2021-02-03T02:39:02+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=4UFaaLLGz error="Webhook response status 400 Bad Request"
t=2021-02-03T02:39:02+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=4UFaaLLGz error="Webhook response status 400 Bad Request"
```

Using webhook.site to inspect the payloads, and `curl` to test payloads, I isolated the issue: Discord does not like it when the `"name"` field is blank. Consider the following payload:

```json
{
    "content": "@everyone",
    "embeds": [
      {
        "color": 14037554,
        "description": "",
        "fields": [
          {
            "inline": true,
            "name": "",
            "value": "41.752048"
          },
          {
            "inline": true,
            "name": "",
            "value": "51.155786"
          }
        ],
        "footer": {
          "icon_url": "https://grafana.com/assets/img/fav32.png",
          "text": "Grafana v7.3.7"
        },
        "title": "[Alerting] temp",
        "type": "rich",
        "url": "[my grafana url]"
      }
    ],
    "username": "Grafana"
  }
```
Discord rejects this. If you fill in the `"name"` fields, however, the alert posts correctly.

Eventually, I discovered the root problme: I used the `{{hostname}}` pattern in the panel's legend. For whatever reason, this left the `"name"` field empty.

My suggestion is twofold:
(1) The name field should never be blank in Discord, as that causes notifications to fail in a difficult-to-detect way.
(2)  `{{hostname}}` should populate the `"name"` field with the actual hostname on alert.

**Environment**:
- Grafana version:  7.3.7
- Data source type & version: PromQL (Prometheus 2.24.1)
- OS Grafana is installed on: Ubuntu 20.04.2 LTS
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by LeviHarrison**
**What this PR does / why we need it**:

When the Metric field is empty in a notification, like when the legend is set to `{{hostname}}`, Discord won't deliver the notification. This PR adds a function that checks if this field is empty, and if it is, replaces it with `Empty metric`, uniquely for Discord.

**Which issue(s) this PR fixes**:

Fixes #30875

**Special notes for your reviewer**:

I didn't change the actual variable because it's a pointer, and that would mean that any other notification channels that come after Discord would also receive the `Empty metric` message, even though they don't require that field to be filled.

### CODE REVIEW

**Comment by dsotirakis** [comment]
Hey @LeviHarrison, I think what you did is good and thanks for spotting, I just left a comment which is more or less a matter of preference but I think something we'd like to see. However, I'd like to see some messages in error handling on Discord API to be honest, since if you send a request an miss the name, you get a 
```
"embeds": [
      "0"
]
```

response, which isn't really self-explanatory. Good catch!

File: pkg/services/alerting/notifiers/discord.go [hunk 1]
```diff
@@ -213,3 +215,11 @@ func (dn *DiscordNotifier) embedImage(cmd *models.SendWebhookSync, imagePath str
 
 	return nil
 }
+
+func notEmpty(metric string) string {
+	if metric == "" {
+		return "Empty metric"
```
Comment (dsotirakis) [inline pkg/services/alerting/notifiers/discord.go:221]: I think we should change the message to something like `<NO_METRIC_NAME>` or `<INVALID_METRIC_NAME>` rather than anything else, since the way you have it right now, appears like:

image

which basically feels like there's a metric called empty!

**Review by dsotirakis — CHANGES_REQUESTED** [review]

File: pkg/services/alerting/notifiers/discord.go (hunk 1 above)
Comment (LeviHarrison) [reply pkg/services/alerting/notifiers/discord.go:221]: Totally get that. `<NO_METRIC_NAME>` it is, because technically `{{hostname}}` is valid, it just doesn't show up on the server.

**Comment by LeviHarrison** [comment]
@dsotirakis I'm not exactly sure what you mean. The only error I see when the name isn't passed is `Webhook response status 400 Bad Request`.

**Review by dsotirakis — APPROVED** [review]
Looks good to me! Also make sure you pull the latest master :)
