### PR TITLE
InfluxDB: Fix Unable to use self-signed CA for adding influxdb data source

### LINKED ISSUE #105585: When adding an influxdb data source to Grafana, select SQL query language and cannot use self-signed CA for verification
### What happened?

When adding an influxdb data source to Grafana, select SQL query language and fail to use self-signed CA for verification.
When I click the Save & Test button, I get the following error:
```
ERROR: flightsql: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"
```

### What did you expect to happen?

When adding an influxdb data source and selecting the SQL query language, you can successfully connect using a self-signed CA and Token

### Did this work before?

There isn't a specific Grafana version confirmed to have worked correctly before in this context.

### How do we reproduce it?

1. Use openssl to generate CA and server certificates
2. Use docker to run influxdb:3.0.3-core and configure the server certificate
3. Open grafana to add influxdb data source, select SQL query language, fill in the URL as https://, select With CA Cert and fill in the CA certificate just generated, click Save & Test button

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: grafana/grafana:12.0.0
OS: Docker
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

influxdb3-core

### PR DESCRIPTION
**Pull request by geekeryy**
**Which issue(s) does this PR fix?**:

Fixes #105585

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by bossinc — APPROVED** [review]
@geekeryy sorry for the long delay!
I see we are handling this correctly in our default client [here](https://github.com/grafana/grafana-plugin-sdk-go/blob/3c35e405973c6626a612753fc4e5f56f38e18350/backend/httpclient/http_client.go#L141) but missed it when recreating the dial options in fsql :disappointed: 
Thank you for catching this!

**Comment by bossinc** [comment]
Will you rebase main so we can merge this :smile: thank you again!

File: pkg/tsdb/influxdb/fsql/fsql.go [hunk 1]
```diff
@@ -143,7 +143,7 @@ func runnerFromDataSource(dsInfo *models.DatasourceInfo) (*runner, error) {
 		md.Set("Authorization", fmt.Sprintf("Bearer %s", dsInfo.Token))
 	}
 
-	fsqlClient, err := newFlightSQLClient(u, md, !dsInfo.InsecureGrpc, dsInfo.ProxyClient)
+	fsqlClient, err := newFlightSQLClient(u, md, !dsInfo.InsecureGrpc,dsInfo.TLSConfig, dsInfo.ProxyClient)
```
Comment (bossinc) [inline pkg/tsdb/influxdb/fsql/fsql.go]:
```suggestion
	fsqlClient, err := newFlightSQLClient(u, md, !dsInfo.InsecureGrpc, dsInfo.TLSConfig, dsInfo.ProxyClient)
```
