### PR TITLE
Geomap: Fix Share View

### LINKED ISSUE #57497: Geomap - Share View not working at all
**What happened**:

The Share View toggle, to sync multiple map panels to always be on the same zoom/view, does not work anymore. I tested with already created dashboards, as well as deploying a fresh newest grafana and just a simple dashboard with two geomap panels with Share View on. Does not work even after reloading the page.

**What you expected to happen**:

That multiple geomap panels keep the view/zoom in sync.

**How to reproduce it (as minimally and precisely as possible)**:

Simply create a geomap panel, no data necessary, toggle Share View on, duplicate panel, save dashboard, and refresh website.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.1
- Data source type & version: InfluxDB 2.4
- OS Grafana is installed on: RPI 64bit
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: None
- Others:

### PR DESCRIPTION
**Pull request by drew08t**
For geomap panel, share view was not working. This fixes that.

Before:
Oct-18-2023 21-25-39

After:
Oct-18-2023 21-23-29

Fixes #57497

### CODE REVIEW

File: public/app/plugins/panel/geomap/GeomapPanel.tsx [hunk 1]
```diff
@@ -250,7 +250,7 @@ export class GeomapPanel extends Component<Props, State> {
     pointerMoveListener(evt, this);
   };
 
-  initMapView = (config: MapViewConfig, sharedView?: View | undefined): Array<View | undefined> => {
+  initMapView = (config: MapViewConfig): Array<View | undefined> => {
     let view = new View({
       center: [0, 0],
       zoom: 1,
```
Comment (nmarrs) [inline public/app/plugins/panel/geomap/GeomapPanel.tsx:256]: On https://github.com/grafana/grafana/blob/1a58a99f37ffcef59b8618c57efb7440e0dd13a9/public/app/plugins/panel/geomap/GeomapPanel.tsx#L270 is it still needed to return both sharedView + view here?

**Review by nmarrs — COMMENTED** [review]
Ihor and I pair reviewed this and encountered an issue where the shared view toggled is turned off and not taking effect (still acting as a shared view)

https://github.com/grafana/grafana/assets/22381771/422c47ed-25cc-438e-9d99-542e61b758dd

[Panel Tests - Geomap Copy-1697734374148.json.txt](https://github.com/grafana/grafana/files/13046214/Panel.Tests.-.Geomap.Copy-1697734374148.json.txt)

**Comment by drew08t** [comment]
> Ihor and I pair reviewed this and encountered an issue where the shared view toggled is turned off and not taking effect (still acting as a shared view)
> 
>  share.view.setting.not.being.disabled.mov 
> [Panel Tests - Geomap Copy-1697734374148.json.txt](https://github.com/grafana/grafana/files/13046214/Panel.Tests.-.Geomap.Copy-1697734374148.json.txt)

I'll take a look. Did a full page refresh help?

**Comment by nmarrs** [comment]
Page refresh did not impact it

**Comment by drew08t** [comment]
> Page refresh did not impact it
So, what appears to be happening is that when not all panels have "share view" on, but one or some do, the order that the panels load impacts the logic in initMapView().

I was able to observe both scenarios below, although scenario 2 is more rare:
Panel 1, 'share view': true; Panel 2, 'share view': false
1. Panel 1 loads first => Share View is active
2. Panel 2 loads first => Share view not active

File: public/app/plugins/panel/geomap/GeomapPanel.tsx [hunk 2]
```diff
@@ -250,24 +249,26 @@ export class GeomapPanel extends Component<Props, State> {
...
+        return sharedView;
       }
+    } else {
+      this.initViewExtent(view, config);
+      return view;
     }
-    this.initViewExtent(view, config);
-
-    return [sharedView, view];
   };
```
Comment (nmarrs) [inline public/app/plugins/panel/geomap/GeomapPanel.tsx:272]: hm I think we can still keep the end of this function the same (pretty much) i.e.

```
this.initViewExtent(view, config);

return view;
```

and just define `view` as a let var and assign it accordingly? unless that doesn't work for some reason?

**Review by nmarrs — APPROVED** [review]
💥

**Comment by drew08t** [comment]
@Develer please try to break this when you get a chance, then we'll move forward with the merge.

**Review by Develer — APPROVED** [review]
