### PR TITLE
DashboardScene: Restrict dashboard in read only state

### LINKED ISSUE #87169: Dashboard Scene: Read-Only dashboards don't work as expected
Dashboard "Read Only" is not working as expected since it allows users to change Permissions and General Tab. 

https://github.com/grafana/grafana/assets/239999/89a2e678-140d-4302-8c30-a954d782456b

In the old architecture, when a dashboard was read-only, a screen was shown to inform the user about the dashboard situation and it offered the option to make the dashboard editable. 

image

### PR DESCRIPTION
**Pull request by Sergej-Vlasov**
In order to fix this for G11 a temporary solution of `Make Editable` button was introduced and few safeguards around that.

Fixes #87169

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard-scene/scene/NavToolbarActions.tsx [hunk 1]
```diff
@@ -344,6 +345,27 @@ export function ToolbarActions({ dashboard }: Props) {
...
+          dashboard.setState({ editable: true, meta: { ...meta, canEdit: true } });
+        }}
+        tooltip="This dashboard was marked as read only"
+        key="edit"
+        className={styles.buttonWithExtraMargin}
+        variant="secondary"
+        size="sm"
+        data-testid={selectors.components.NavToolbar.editDashboard.editButton}
+      >
+        Make Editable
```
Comment (ivanortegaalba) [inline public/app/features/dashboard-scene/scene/NavToolbarActions.tsx:364]:
```suggestion
        Make editable
```

**Review by ivanortegaalba — APPROVED** [review]
It works as expected! Better than the current approach. Good job Sergej! Once we get feedback from the team we can iterate over it

File: public/app/features/dashboard-scene/scene/PanelMenuBehavior.tsx [hunk 2]
```diff
@@ -66,7 +66,7 @@ export function panelMenuBehavior(menu: VizPanelMenu, isRepeat = false) {
       });
     }
 
-    if (dashboard.canEditDashboard() && !isRepeat && !isEditingPanel) {
+    if (dashboard.state.editable && !isRepeat && !isEditingPanel) {
```
Comment (Sergej-Vlasov) [inline public/app/features/dashboard-scene/scene/PanelMenuBehavior.tsx:69]: @ivanortegaalba maybe this should be like this?
```typescript
if (dashboard.canEditDashboard() && dashboard.state.editable && !isRepeat && !isEditingPanel) {
```
