### PR TITLE
Hide datalink button when datasource for exemplar is undefined

### LINKED ISSUE #50358: Exemplar links on Prometheus graph show "undefined"
**What happened**:
User without permission to Tempo data sources will see "Query with Undefined" button on Prometheus graph exemplar details.

**What you expected to happen**:
 Button should be hidden when user does not have access.

**How to reproduce it (as minimally and precisely as possible)**:
Set up
1. Set up a Tempo data source.
2. Add permissions to the Tempo data source that denies access to a test user.
3. Set up a Prometheus data source. Prometheus must have exemplars to query.
4. In the Prometheus data source add Exemplars setting with internal link to the Tempo data source.

Reproduce
1. Log into Grafana as test user without access to Tempo data source.
2. In Grafana, go to explore.
3. Select the Prometheus data source.
4. Run a query that shows exemplars.
5. Hover over the exemplar marker to bring up exemplar details.
6. Find related "Query with undefined"

image

**Anything else we need to know?**:

In the file: https://github.com/grafana/grafana/blob/6de77283c682e8baba133250f67453a03fdbf5bf/public/app/plugins/datasource/prometheus/result_transformer.ts#L289-L305

The function getDataLinks needs to check if dsSettings has a type of undefined before adding it to the dataLinks.

**Environment**:
- Grafana version: 8.5.2 
- Data source type & version: Prometheus and Tempo

- OS Grafana is installed on: Ubuntu 
- User OS & Browser: Ubuntu & Chrome

### PR DESCRIPTION
**Pull request by itsmylife**
**What this PR does / why we need it**:
After setting up the exemplars you might see the exemplar Datasource is undefined. This might happen because of permissions or deleting/breaking the configuration of the data source. In order to show undefined in the UI we show an error message to inform the user there is something wrong. 

image

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/50358

**Special notes for your reviewer**:
I couldn't cover those in unit tests since setting up an environment with exemplars is a bit tricky. Let me know if you have any suggestions on better tests to run or even unit tests in this case.

### CODE REVIEW

File: packages/grafana-ui/src/components/DataLinks/FieldLinkList.tsx [hunk 1]
```diff
@@ -28,25 +33,48 @@ export function FieldLinkList({ links }: Props) {
...
+  link: LinkModel<Field>;
+};
+
+/**
+ * @internal
+ */
+const MaybeErrorBadge: React.FC<MaybeErrorBadgeProps> = (props) => {
+  const { link, children } = props;
+  return link.origin.config.links && link.origin.config.links[0].error ? (
+    <Badge text={link.title} tooltip={link.error} color="red" icon="external-link-alt" />
```
Comment (itsmylife) [inline packages/grafana-ui/src/components/DataLinks/FieldLinkList.tsx:67]: Although we have a tooltip here, we cannot show it. Because the exemplar popup is in the tooltip container already. I couldn't find a way to show it.

**Review by aocenas — COMMENTED** [review]
Looks good but maybe we can add a small unit test for the getDataLinks function. Not sure if it makes sense to export it just to test it (I usually don't like that as it makes something that can be private public) but maybe we can add a case for the transform functions and check the datalinks in the resulting dataframe

**Comment by KirbySSmith** [comment]
The preferred behavior for us would be to hide the button. This is similar behavior to the datasource drop down on the explore page. We are expecting a list of data links and some users will only have access to some of the linked datasources.

**Comment by itsmylife** [comment]
> The preferred behavior for us would be to hide the button. This is similar behavior to the datasource drop down on the explore page. We are expecting a list of data links and some users will only have access to some of the linked datasources.

I would implement this way for consistency. WDYT @aocenas

**Comment by aocenas** [comment]
@itsmylife @KirbySSmith ok thinking about it more it probably makes sense. For not having permission not showing the link makes sense and is expected. In case this is due to the data source being deleted or something misconfigured it would be better to have some message but we don't know which case it is and I think the permission reason will be much more common that the misconfiguration.

So yeah let's just hide it instead. Sorry for my earlier suggestion @itsmylife.

**Comment by itsmylife** [comment]
> @itsmylife @KirbySSmith ok thinking about it more it probably makes sense. For not having permission not showing the link makes sense and is expected. In case this is due to the data source being deleted or something misconfigured it would be better to have some message but we don't know which case it is and I think the permission reason will be much more common that the misconfiguration.
> 
> So yeah let's just hide it instead. Sorry for my earlier suggestion @itsmylife.

No worries. Thanks for the input. I will make the changes.

File: public/app/plugins/datasource/prometheus/result_transformer.ts [hunk 2]
```diff
@@ -293,15 +293,17 @@ function getDataLinks(options: ExemplarTraceIdDestination): DataLink[] {
...
-    dataLinks.push({
-      title: options.urlDisplayLabel || `Query with ${dsSettings?.name}`,
-      url: '',
-      internal: {
-        query: { query: '${__value.raw}', queryType: 'traceId' },
-        datasourceUid: options.datasourceUid,
-        datasourceName: dsSettings?.name ?? 'Data source not found',
-      },
-    });
+    if (dsSettings) {
```
Comment (aocenas) [inline public/app/plugins/datasource/prometheus/result_transformer.ts:296]: Lets just add a comment what are the cases when this is undefined ie:
- permissions
- deleted datasource
- misconfiguration
And that permission is probably most likely and in that case it makes sense to just not show the link

**Review by aocenas — APPROVED** [review]
