### PR TITLE
API: Fix redirect issue when configured to use a subpath

### LINKED ISSUE #21651: subpath evaluates as invalid in redirects
**What happened**:

Following a link to a dashboard with Grafana configured to use a subpath:
```
http://localhost:3000/grafana/d/5xrG2HyWz/sample?orgId=1
```
When the user needs to login, they are redirected to the login. Once that succeeds, they should be redirected back to the original url intended.

The new cookie validation code has an extra forward slash and always returns false, sending the user to their default page.

This is related to PR #21057

**What you expected to happen**:
login should complete, then should be redirected to intended dashboard

**How to reproduce it (as minimally and precisely as possible)**:

add a subpath to grafana config and startup

grafana.ini:
```
[server]
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
serve_from_sub_path = true
```
**Anything else we need to know?**:

**Environment**:
- Grafana version:
6.3.2
- Data source type & version:
any - testdata
- OS Grafana is installed on:
linux
- User OS & Browser:
macos/chrome
- Grafana plugins:
none
- Others:

### PR DESCRIPTION
**Pull request by briangann**
**What this PR does / why we need it**:

redirect_to cookie handling needs to account for subpath already inside request during login.

**Which issue(s) this PR fixes**:
Fixes #21651 

**Special notes for your reviewer**:

This fix works, but one change has not been tested with OAuth (see login_oauth.go)

### CODE REVIEW

File: pkg/api/login.go [hunk 1]
```diff
@@ -35,8 +35,10 @@ func (hs *HTTPServer) validateRedirectTo(redirectTo string) error {
 	if to.IsAbs() {
 		return login.ErrAbsoluteRedirectTo
 	}
-	if hs.Cfg.AppSubUrl != "" && !strings.HasPrefix(to.Path, "/"+hs.Cfg.AppSubUrl) {
-		return login.ErrInvalidRedirectTo
+	if hs.Cfg.AppSubUrl != "" {
```
Comment (aknuds1) [inline pkg/api/login.go]: Is there a reason for dividing it into two if statements, instead of and-ing the conditions as before? Personally I'd prefer keeping the one if statement, since it makes it clear that there's no possibility of further branches nested within.

**Comment by aknuds1** [comment]
Are you going to test OAuth before marking the PR as ready for review?

**Comment by marefr** [comment]
@briangann thanks a lot. Would be nice to include this in 6.6 stable planned for Monday. Possible to mark this as ready for review and get it merged for tomorrow? Please let us know if you want us to help or take it over in case you don't have time.

File: pkg/api/login.go (hunk 1 above)
Comment (briangann) [reply pkg/api/login.go]: this can be combined back into one statement, that was just an artifact of debugging

**Comment by briangann** [comment]
> Are you going to test OAuth before marking the PR as ready for review?

i'll setup and test with oauth today, thanks!

**Comment by briangann** [comment]
there's a bug with oauth2, the sub_url is being removed, will update with a fix

**Comment by briangann** [comment]
verified with gihub oauth2 config, the redirect is working correctly now

File: pkg/api/login.go [hunk 2]
```diff
@@ -35,7 +35,7 @@ func (hs *HTTPServer) validateRedirectTo(redirectTo string) error {
 	if to.IsAbs() {
 		return login.ErrAbsoluteRedirectTo
 	}
-	if hs.Cfg.AppSubUrl != "" && !strings.HasPrefix(to.Path, "/"+hs.Cfg.AppSubUrl) {
+	if hs.Cfg.AppSubUrl != "" && !strings.HasPrefix(to.Path, hs.Cfg.AppSubUrl) && !strings.HasPrefix(to.Path, "/"+hs.Cfg.AppSubUrl) {
```
Comment (kylebrandt) [inline pkg/api/login.go]: Comment explaining the logic here might help future us.

**Comment by kylebrandt** [comment]
Should there be an additional test case in `redirectCases := []redirectCase{` that illustrates this change? Or is it somehow covered?

**Review by aknuds1 — APPROVED** [review]
LGTM

**Comment by briangann** [comment]
> Should there be an additional test case in `redirectCases := []redirectCase{` in `login_test.go` that illustrates this change? Or is it somehow covered?

i'll add additional cases to cover these different values for regular logins.
the oauth-based redirect doesn't have complete coverage like this, will see how to implement similar tests.

File: pkg/api/login_oauth.go [hunk 3]
```diff
@@ -218,6 +218,10 @@ func (hs *HTTPServer) OAuthLogin(ctx *m.ReqContext) {
 
 	if redirectTo, _ := url.QueryUnescape(ctx.GetCookie("redirect_to")); len(redirectTo) > 0 {
 		middleware.DeleteCookie(ctx.Resp, "redirect_to", hs.cookieOptionsFromCfg)
+		// if there is a sub_url, prepend it
+		if setting.AppSubUrl != "" {
+			redirectTo = setting.AppSubUrl + redirectTo
+		}
```
Comment (marefr) [inline pkg/api/login_oauth.go]: This change doesn't work for me since redirect cookie already contains subpath so resulting redirect is `http://localhost:3000/grafana/grafana/d/5SdHCadmz/panel-tests-graph?orgId=1`. Removing this code makes it work for as expected for me.

**Review by marefr — CHANGES_REQUESTED** [review]
Using subpath doesn't redirect correctly using oauth, see comment. Without subpath login/oauth and with subpath login works as expected.

File: pkg/api/login_oauth.go (hunk 3 above)
Comment (briangann) [reply pkg/api/login_oauth.go]: will investigate, i was testing this on a "real" site behind SSL and nginx, but not testing locally.

nginx block looks like this, the rewrite is probably "fixing" that for me
```
  upstream internal {
    server 0.0.0.0:9098;
    keepalive 32;
  }
  location /grafana/ {
      proxy_pass http://internal;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $http_host;
      rewrite ^/grafana/(.*) /$1 break;
  }
```

File: pkg/api/login.go [hunk 4]
```diff
@@ -94,6 +96,8 @@ func (hs *HTTPServer) LoginView(c *models.ReqContext) {
 				return
 			}
 			middleware.DeleteCookie(c.Resp, "redirect_to", hs.cookieOptionsFromCfg)
+			// remove subpath if it exists
+			redirectTo = strings.Replace(redirectTo, setting.AppSubUrl, "", 1)
```
Comment (consideRatio) [inline pkg/api/login.go]: What if the subUrl is just `-` or `grafana` and this occur in the redirectTo path? We could do something to replace it only in the beginning of the string, or only once from left to right perhaps.

File: pkg/api/login_oauth.go (hunk 3 above)
Comment (briangann) [reply pkg/api/login_oauth.go]: have removed this change, and verified it is working.  the redirect_to subpath is handled in login.go

File: pkg/api/login.go (hunk 4 above)
Comment (briangann) [reply pkg/api/login.go]: that is true, there's a chance of replacing a match in the wrong location.  currently it removes 1 occurrence but it is not positionally constrained

Comment (consideRatio) [reply pkg/api/login.go]: Ah that was the `, 1` part I understand now. I think it may always be the first position, from left to right, as it worked that way in [this playground test](https://play.golang.org/p/L0Djy9kFa07) i did.

If we can safely assume redirectTo will contain settings.AppSubUrl, then I think this is fine as it is.

Comment (briangann) [reply pkg/api/login.go]: removing this change, debug/test shows it is not needed.  this code path is not easy to hit either :)

**Comment by briangann** [comment]
Here's the logic behind this PR:

For a Grafana server running in a subpath (nginx + ssl being typical)

When using a local login, the request url is stored in the cookie and it includes the subpath.

When local login succeeds, the redirect_to in the cookie is stored in result json "redirectUrl" and sent to the frontend, which prepends it with the subpath, ending up with a duplicate.

The change is to remove the subpath that will be return to "redirectUrl", and let the frontend prepend it.

(oauth takes a different code path and is not affected by this issue since the cookie is ok to use in that codepath)

**Comment by papagian** [comment]
I have tested the modifications with:
- base auth without subpath
- base auth with subpath
- github oauth without subpath
- github oauth with subpath

and it works as expected.

**Review by marefr — APPROVED** [review]
Great! LGTM

**Comment by consideRatio** [comment]
The fix is an improvement, but leads to another issue if i visit https://example.local/grafana instead of https://example.local/grafana/. I end up with a redirect_to cookie of `%2Fgrafana` or `%2Fgrafana%2F` respectively.

If i have a redirect_to cookie with /grafana/ (%2Fgrafana%2F) then everything is fine. But, if I have a redirect_to cookie of /grafana, what follow login is a redirect loop between /grafana and /grafana/login bouncing back and forth with 302 web redirects to each other.

**Comment by aknuds1** [comment]
@consideRatio could you post an issue about the bug you're experiencing?

**Comment by consideRatio** [comment]
@aknuds1 - issue created at https://github.com/grafana/grafana/issues/22227
