### PR TITLE
api/ds/query: simplify data sources lookup for queries and expressions

### LINKED ISSUE #41341: Dashboard: Expression "All queries must use the same datasource"
A couple of releases ago, the Mixed datasource + math Expression was broken in the Dashboard page. As I checked in version 8.2.3, we are not able to query dato from different datasources and the do some math expressions.

We setup Mixed datasource, then make the queries and finally try to do some math operation with Expression. We expect a result, but it said: All queries must use the same datasource.

If we remove the math Expression query, it works and dashboard shows some data of different datasources. Only affect after adding one math expression.

image

image

**Environment**:
- Grafana version: 8.2.3
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian 10
- User OS & Browser: Windows, Google Chrome
- Grafana plugins: None
- Others: None

### PR DESCRIPTION
**Pull request by ryantxu**
This expands the work in #41169 so that we:
1. move all funky simplejson/type/uid/datasourceid logic to a single function
2. use the *same* query parsing logic for normal vs expression query parsing
3. stop sending `datasourceId` from the frontend (but still supported in the backend)

With this PR, the following request structure is preferred:
```
{
  "queries": [
    {
      "datasource": { "type": "testdata", "uid": "7w0eseKGz" },
      "refId": "A",
      ....
    },
```
The following structures continue to be supported, but we should move to using the above structure (and in general prefer uid over id)
```
{
  "queries": [
    {
      "datasourceId": 1234,
      ....
    },
    {
      "datasource": "__expr__", // this was type, not instance ¯\_(ツ)_/¯ 
      ....
    },
```

NOTE:
* ~~this now looks up a datasource for each query -- is that OK/fast?~~  Update: it now looks things up once for each uid.  When `datasourceId` is sent, it will have to look up each time -- but we can update the frontend so that should be a rare case.
* Weirdly the existing code checks that everything is the same *type*, not the same instance -- so you currently send all queries to the first instance found.  

NEXT: (not this PR, but soon)
1. update SQL data sources that send `datasourceId` directly -- this touches many instances so lets do it independently
2. @kylebrandt -- it looks like there are lots of different places and ways that datasources are loaded from expressions, can we remove all that and just pass in the now loaded models.DataSource instance?   

Fixes #41341 #41151

### CODE REVIEW

File: pkg/api/metrics.go [hunk 1]
```diff
@@ -97,6 +111,46 @@ func (hs *HTTPServer) QueryMetricsV2(c *models.ReqContext, reqDTO dtos.MetricReq
 	return toMacronResponse(resp)
 }
 
+type queryDSInfo struct {
+	isExpr bool
+	ds     *models.DataSource
+	err    error
+	uid    string
+	id     int64
```
Comment (ryantxu) [inline pkg/api/metrics.go:119]: :vomiting_face:  -- I don't like this, and it is only required so we can have the info for:
```
return hs.handleGetDataSourceUIDError(q.err, q.uid)
```

An alternate approach would be to have the body of `getDataSourceFromQuery` inside the loop and return errors directly.  Since it is only used once, that could be fine

File: pkg/expr/graph.go [hunk 2]
```diff
@@ -143,17 +143,30 @@ func (s *Service) buildGraph(req *Request) (*simple.DirectedGraph, error) {
...
 			QueryType:     query.QueryType,
-			DatasourceUID: query.DatasourceUID,
+			DatasourceUID: query.GetDatasourceUID(),
 		}
 
-		isExpr, err := rn.IsExpressionQuery()
-		if err != nil {
-			return nil, err
+		numericDSID := float64(0) // legacy
+		if rn.DatasourceUID == "" {
```
Comment (ryantxu) [inline pkg/expr/graph.go:150]: @kylebrandt -- is this path still possible?  is the graph called from anywhere besides `/api/ds/query`?

File: pkg/expr/transform.go [hunk 3]
```diff
@@ -72,13 +79,30 @@ type Request struct {
 type Query struct {
 	RefID         string
 	TimeRange     TimeRange
-	DatasourceUID string
+	DatasourceUID string        // deprecated, value -100 when expressions
+	Datasource    DataSourceRef `json:"datasource"`
```
Comment (ryantxu) [inline pkg/expr/transform.go:83]: @kylebrandt do we need a special object here?  can it be the same DataSource object that already exists on q?

File: pkg/api/metrics.go [hunk 4]
```diff
@@ -97,67 +97,63 @@ func (hs *HTTPServer) QueryMetricsV2(c *models.ReqContext, reqDTO dtos.MetricReq
...
+			statusCode = http.StatusBadRequest
+		}
+	}
+
+	return response.JSONStreaming(statusCode, qdr)
 }
 
-func (hs *HTTPServer) handleGetDataSourceError(err error, datasourceID int64) *response.NormalResponse {
-	hs.log.Debug("Encountered error getting data source", "err", err, "id", datasourceID)
+func (hs *HTTPServer) handleGetDataSourceError(err error, datasourceRef interface{}) *response.NormalResponse {
```
Comment (ryantxu) [inline pkg/api/metrics.go:155]: changed this to interface so the same signature could take int64 or string

File: pkg/expr/transform.go [hunk 5]
```diff
@@ -72,13 +79,30 @@ type Request struct {
...
 	JSON          json.RawMessage
 	Interval      time.Duration
 	QueryType     string
 	MaxDataPoints int64
 }
 
+type DataSourceRef struct {
```
Comment (ryantxu) [inline pkg/expr/transform.go:90]: This class is temporary until we can just pass in models.DataSource

File: pkg/expr/transform.go (hunk 3 above)
Comment (kylebrandt) [reply pkg/expr/transform.go:83]: I believe new alerting use this, so that would have to change.

File: pkg/expr/graph.go (hunk 2 above)
Comment (kylebrandt) [reply pkg/expr/graph.go:150]: I don't think so, was defaulting to being cautious.

Comment (ryantxu) [reply pkg/expr/graph.go:150]: Should we remove it now or in a different PR?  I am a bit nervous with the multiple ways to identify a datasource in graph/node but also not clear on where this is called and referenced.

File: pkg/api/metrics.go [hunk 6]
```diff
@@ -97,67 +97,63 @@ func (hs *HTTPServer) QueryMetricsV2(c *models.ReqContext, reqDTO dtos.MetricReq
...
+	if ok {
+		return ds, nil
+	}
 
-		datasourceID, err := query.Get("datasourceId").Int64()
+	switch uid {
+	case expr.OldDatasourceUID: // "-100" :(
+		fallthrough
+	case expr.DatasourceUID:
+		return expr.DataSourceModel(), nil
```
Comment (marefr) [inline pkg/api/metrics.go:119]: Could maybe hide the details in expr package by exposing a function, e.g. `expr.IsDatasource(<uid>)`?

```suggestion
	if expr.IsDataSource(uid) {
		return expr.DataSourceModel(), nil
	}
	
	switch uid {
```

File: pkg/api/metrics.go [hunk 7]
```diff
@@ -31,42 +32,23 @@ func (hs *HTTPServer) QueryMetricsV2(c *models.ReqContext, reqDTO dtos.MetricReq
...
-			if dsID == grafanads.DatasourceID {
-				ds = grafanads.DataSourceModel(c.OrgId)
-			} else {
-				ds, err = hs.DataSourceCache.GetDatasource(dsID, c.SignedInUser, c.SkipCache)
-				if err != nil {
-					return hs.handleGetDataSourceError(err, dsID)
-				}
-			}
+		datasources[ds.Uid] = ds
+		if ds.Uid == expr.DatasourceUID {
```
Comment (marefr) [inline pkg/api/metrics.go:48]: Based on earlier suggestion in `getDataSourceFromQuery`.

```suggestion
		if expr.IsDataSource(ds.Uid) {
```

File: pkg/api/metrics.go [hunk 8]
```diff
@@ -97,67 +97,63 @@ func (hs *HTTPServer) QueryMetricsV2(c *models.ReqContext, reqDTO dtos.MetricReq
...
-func (hs *HTTPServer) handleExpressions(c *models.ReqContext, reqDTO dtos.MetricRequest) response.Response {
-	timeRange := plugins.NewDataTimeRange(reqDTO.From, reqDTO.To)
-	request := plugins.DataQuery{
-		TimeRange: &timeRange,
-		Debug:     reqDTO.Debug,
-		User:      c.SignedInUser,
-		Queries:   make([]plugins.DataSubQuery, 0, len(reqDTO.Queries)),
+	// before 8.3 special types could be sent as datasource (expr)
+	if uid == "" {
+		uid = query.Get("datasource").MustString()
```
Comment (marefr) [inline pkg/api/metrics.go:106]: Isn't this the data source name rather than uid?

File: pkg/services/ngalert/models/alert_query.go [hunk 9]
```diff
@@ -89,7 +89,7 @@ func (aq *AlertQuery) setModelProps() error {
 
 // IsExpression returns true if the alert query is an expression.
 func (aq *AlertQuery) IsExpression() (bool, error) {
-	return aq.DatasourceUID == expr.DatasourceUID, nil
+	return aq.DatasourceUID == expr.OldDatasourceUID, nil
```
Comment (marefr) [inline pkg/services/ngalert/models/alert_query.go:92]: Can we perhaps use `expr.IsDataSource(<uid>)` here as well?

File: pkg/expr/translate/translate.go [hunk 10]
```diff
@@ -259,7 +259,7 @@ func (dc *dashConditionsJSON) GetNew(orgID int64) (*ngmodels.Condition, error) {
 	ccAlertQuery := ngmodels.AlertQuery{
 		RefID:         ccRefID,
 		Model:         exprModelJSON,
-		DatasourceUID: expr.DatasourceUID,
+		DatasourceUID: expr.OldDatasourceUID,
```
Comment (marefr) [inline pkg/expr/translate/translate.go:262]: Sorry probably too tired right now. Why `expr.OldDatasourceUID` and not `expr.DatasourceUID`

File: pkg/expr/service.go [hunk 11]
```diff
@@ -4,21 +4,29 @@ import (
...
 const DatasourceID = -100
 
-// DatasourceUID is the fake datasource uid used in requests to identify it as an
-// expression command.
-const DatasourceUID = "-100"
+// OldDatasourceUID is the datasource uid used in requests to identify it as an
+// expression command. It goes with the query root level datasourceUID property. It was accidentally
+// set to the Id and is now kept for backwards compatibility. The newer Datasource.UID property
+// should be used instead and should be set to "__expr__".
+const OldDatasourceUID = "-100"
```
Comment (marefr) [inline pkg/expr/service.go:29]: Related to other suggestions.

```suggestion
const OldDatasourceUID = "-100"

func IsDataSource(uid stirng) bool {
	return uid == DatasourceUID || uid == OldDatasourceUID
}
```

**Review by marefr — COMMENTED** [review]
I think this looks good, definitely easier to follow than how it looks like in main :+1: It took some time to wrap my head around things since I'm not that familiar with SSE. Added some comments/suggestions.

File: pkg/api/metrics.go (hunk 6 above)
Comment (ryantxu) [reply pkg/api/metrics.go:119]: I am torn on how to approach this -- my sense is we should fix/migrate everything so that `expr.DatasourceUID` is the real value!

However, fixing that along with everything else in this PR seems like a big lift.

File: pkg/api/metrics.go (hunk 8 above)
Comment (ryantxu) [reply pkg/api/metrics.go:106]: :thinking: true in dashboards, but for the metrics request it was weirdly set to `__expr__`

This endpoint was never sent name, rather it primarily worked with `datasourceId: int64`

File: pkg/api/metrics.go (hunk 6 above)
Comment (ryantxu) [reply pkg/api/metrics.go:119]: After this is merged, I think we should audit expressions to make sure:
1. "-100" is handled by migrations and not with every check at runtime
2. datasource loading does not fall back to looking in the `map[string]interface{}`

If adding the function now is helpful, then :+1:

File: pkg/expr/translate/translate.go (hunk 10 above)
Comment (ryantxu) [reply pkg/expr/translate/translate.go:262]: @kylebrandt

File: pkg/api/metrics.go (hunk 8 above)
Comment (marefr) [reply pkg/api/metrics.go:106]: Understood. And now you'll send `__expr__` in both `uid` and `type` of `DataSourceRef`?

File: pkg/api/metrics.go (hunk 6 above)
Comment (marefr) [reply pkg/api/metrics.go:119]: > However, fixing that along with everything else in this PR seems like a big lift.

Agree. Guess my point was moving the checks of these different constant behind a function would allow us to just remove usage of `OldDatasourceUID` in that function when we've migrated to use only `DatasourceUID`. Guess it could wait

File: pkg/expr/translate/translate.go (hunk 10 above)
Comment (kylebrandt) [reply pkg/expr/translate/translate.go:262]: Alerting would need to change, and there would need to be a migration to change the saved type.

Translate isn't actually used, dead code, but is similar to the ualert migration that migrations legacy 8 alerting conditions to new unified alerts with condition. Unified alerts saved model uses the "old" UID. So not sure we want to get into changing that now since it may require another migraiton.

**Review by kylebrandt — APPROVED** [review]
Looks okay and works for me, like @marefr suggestions, might want to wait for final approval from him.

File: pkg/api/metrics.go (hunk 8 above)
Comment (ryantxu) [reply pkg/api/metrics.go:106]: yup -- *should* be just `type`, but right now enough things only look at uid that I don't want to muck with that just yet.  Ideally we can have defaults scoped to type rather than global.  ie "give me my default loki instance" -- but we are not there yet!

**Review by marefr — APPROVED** [review]
LGTM
