### PR TITLE
CloudWatch: Add multi-value template variable support for log group names in logs query builder

### LINKED ISSUE #49540: Multi-value template variables are not supported for logGroupNames by Cloudwatch datasource
**What happened**:
We want to run a Cloudwatch log insights query on multiple Log groups. Log Groups vary depending on the `region` template variable. Ex: 
- If `region = us-east-1`, Log groups are `ServiceName/us-east-1-a/logfile`, `ServiceName/us-east-1-b/logfile`
- If `region = us-west-2`, Log groups are `ServiceName/us-west-2-c/logfile`, `ServiceName/us-west-2-d/logfile`

I have managed to get the log group names dynamically into a template variable, say `log_groups`. But, when I use the variable `$log_groups` in the panel, Grafana shows an error : 
```
Multi template variables are not supported for logGroupNames
```

I looked at Query on developer tool -> Network Tab. This is the query in the request out by Grafana: 

```
{
    "from": "1653379352443",
    "to": "1653422552443",
    "queries": [{
        "refId": "A",
        "intervalMs": 1,
        "maxDataPoints": 1,
        "datasource": {
            "type": "cloudwatch",
            "uid": "ServiceName-Prod-cloudwatch-us-east-1"
        },
        "type": "logAction",
        "subtype": "StartQuery",
        "queryString": "fields X, Y, Z\n| filter Status not like /200/\n| filter Operation like /XXXX/\n| stats count(*) by X",
        "logGroupNames": ["{ServiceName/us-east-1/us-east-1-a/service_log,ServiceName/us-east-1/us-east-1-b/service_log,ServiceName/us-east-1/us-east-1-c/service_log}"],
        "region": "us-east-1"
    }]
}
```

**What you expected to happen**:
Multiple Log Groups are sent in the request to Cloudwatch

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Cloudwatch datasource
2. Create a multi-value template variable with valid log group names
3. Create a panel -> Use Cloudwatch datasource -> Select Cloudwatch Logs -> Use variable created in step (2)
4. Write a valid Log Insights query
5. Execute the query

**Anything else we need to know?**:
Have tried Advanced Template variable options like `:json`, no success. 

**Environment**:
- Grafana version: 8.4.4
- Data source type & version: Cloudwatch
- OS Grafana is installed on: RHEL
- User OS & Browser: MacOS, Firefox
- Grafana plugins: AWS Cloudwatch Datasource plugin, Timeseries panel.
- Others:

### PR DESCRIPTION
**Pull request by kevinwcyu**
**What this PR does / why we need it**:
Adds support in the frontend for multi-value template variables. The backend already supports it.

Currently on the frontend, the `logGroupNames` field in the query is an array of strings. Each value in the array is a log group name. When using a multi-value template variable, all of the selected values are joined in a single string. E.g. if you had the values `log-group-name-1` and `log-group-name-2`, it would be:

```js
logGroupNames: ["log-group-name-1,log-group-name-2"],
```

This PR uses `getVariableValue` to get the variable values and splits them so each individual log group name correctly passed in the query to the backend.

```js
logGroupNames: ["log-group-name-1", "log-group-name-2"],
```

**Which issue(s) this PR fixes**:

Fixes #49540

**Special notes for your reviewer**:
If you want to test this, you'll have to manually enter the variable into the Log groups field.

Screen Shot 2022-05-26 at 12 33 30 PM

### CODE REVIEW

File: public/app/plugins/datasource/cloudwatch/utils/datalinks.ts [hunk 1]
```diff
@@ -65,10 +67,11 @@ function createAwsConsoleLink(
   target: CloudWatchLogsQuery,
   range: TimeRange,
   region: string,
-  replace: (target: string, fieldName?: string) => string
+  replace: (target: string, fieldName?: string) => string,
+  getVariableValue: (value: string) => string[]
 ) {
   const interpolatedExpression = target.expression ? replace(target.expression) : '';
-  const interpolatedGroups = target.logGroupNames?.map((logGroup: string) => replace(logGroup, 'log groups')) ?? [];
+  const interpolatedGroups = target.logGroupNames?.flatMap(getVariableValue) ?? [];
```
Comment (iwysiu) [inline public/app/plugins/datasource/cloudwatch/utils/datalinks.ts:74]: Neat, I hadn't seen `flatmap` before.

**Review by iwysiu — APPROVED** [review]
lgtm with a test

**Review by sunker — COMMENTED** [review]
Nice! Can you also append template variables to the list of options in the multi select? We do that for all other fields that support variables, see [here](https://github.com/grafana/grafana/blob/kevinwcyu/49540-multi-value-template-var-log-group-names/public/app/plugins/datasource/cloudwatch/hooks.ts#L35) for example.

I think for this to be really useful, we should provide a template variable query function for listing log groups so that the user doesn't have to add them manually using a custom variable. Should be simple since we already have code in place for describing log groups. Anyway, that should be done in a separate PR.

**Comment by kevinwcyu** [comment]
> I think for this to be really useful, we should provide a template variable query function for listing log groups so that the user doesn't have to add them manually using a custom variable. Should be simple since we already have code in place for describing log groups. Anyway, that should be done in a separate PR.

@sunker good shout, I've added this issue https://github.com/grafana/grafana/issues/49844 and also marked as `mob-friendly`. Let me know if it's simple, but not `mob-friendly`-simple and I can update the label.

**Comment by sunker** [comment]
> Let me know if it's simple, but not `mob-friendly`-simple and I can update the label.

Think this is very mob-friendly! Thanks for creating the issue.

File: .betterer.results [hunk 2]
```diff
@@ -179,8 +179,8 @@ exports[`no enzyme tests`] = {
     "public/app/plugins/datasource/cloudwatch/components/ConfigEditor.test.tsx:1224072551": [
       [0, 19, 13, "RegExp match", "2409514259"]
     ],
-    "public/app/plugins/datasource/cloudwatch/components/LogsQueryField.test.tsx:2097436158": [
-      [1, 19, 13, "RegExp match", "2409514259"]
+    "public/app/plugins/datasource/cloudwatch/components/LogsQueryField.test.tsx:1501504663": [
+      [2, 19, 13, "RegExp match", "2409514259"]
```
Comment (kevinwcyu) [inline .betterer.results:183]: I edited two of the existing tests to make them pass. They are being refactored in this other PR https://github.com/grafana/grafana/pull/49286/files.

**Review by sunker — APPROVED** [review]
Nice work on this! Think you need add a milestone and a `no-backport` label for the CI to pass.
