### PR TITLE
Storage: Take `migration_locking` setting into account

### LINKED ISSUE #100256: Grafana 11.5 does not (fully) honor `database.migration_locking = false`
### What happened?

Upgraded to grafana 11.5, with `database.migration_locking = false`, but startup failed because some migrations still tried to use `GET_LOCK`, which is not supported on our Percona-XtraDB-Cluster. Issue is present on both 11.5.0 and 11.5.1, not on 11.4.1 and older.

Logging shows the "normal" `migrator` successfully doing migrations, and then the `resource-migrator`/`resource-server` trying to get a lock, and failing. (Normal `migrator` also fails on locking when `database.migration_locking` is not set, as expected)

Logs:
```
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=settings t=2025-02-07T10:09:46.8862728Z level=info msg="Starting Grafana" version=11.5.0 commit=f7a938db9ad71c1558e93d8e29e69f42c8a5f50b branch=HEAD compiled=2025-02-07T10:09:46Z
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=settings t=2025-02-07T10:09:46.88674538Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=settings t=2025-02-07T10:09:46.88676175Z level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=settings t=2025-02-07T10:09:46.88677023Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=settings t=2025-02-07T10:09:46.88678289Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=settings t=2025-02-07T10:09:46.88679071Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=settings t=2025-02-07T10:09:46.88679689Z level=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=settings t=2025-02-07T10:09:46.8868037Z level=info msg=Target target=[all]
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=settings t=2025-02-07T10:09:46.88681542Z level=info msg="Path Home" path=/usr/share/grafana
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=settings t=2025-02-07T10:09:46.8868223Z level=info msg="Path Data" path=/var/lib/grafana
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=settings t=2025-02-07T10:09:46.88682956Z level=info msg="Path Logs" path=/var/log/grafana
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=settings t=2025-02-07T10:09:46.88683652Z level=info msg="Path Plugins" path=/var/lib/grafana/plugins
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=settings t=2025-02-07T10:09:46.88684348Z level=info msg="Path Provisioning" path=/etc/grafana/provisioning
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=settings t=2025-02-07T10:09:46.88685072Z level=info msg="App mode production"
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=featuremgmt t=2025-02-07T10:09:46.8873399Z level=info msg=FeatureToggles userStorageAPI=true dashboardSceneSolo=true alertingApiServer=true dashboardSceneForViewers=true recoveryThreshold=true reportingUseRawTimeRange=true unifiedRequestLog=true promQLScope=true dataplaneFrontendFallback=true nestedFolders=true groupToNestedTableTransformation=true logRowsPopoverMenu=true lokiQuerySplitting=true prometheusAzureOverrideAudience=true alertingNoDataErrorExecution=true logsExploreTableVisualisation=true newFiltersUI=true accessControlOnCall=true lokiLabelNamesQueryApi=true awsAsyncQueryCaching=true lokiQueryHints=true alertingInsights=true cloudWatchCrossAccountQuerying=true alertingUIOptimizeReducer=true addFieldFromCalculationStatFunctions=true dashboardScene=true onPremToCloudMigrations=true ssoSettingsApi=true annotationPermissionUpdate=true azureMonitorEnableUserAuth=true alertingSimplifiedRouting=true newDashboardSharingComponent=true transformationsVariableSupport=true recordedQueriesMulti=true formatString=true angularDeprecationUI=true newPDFRendering=true correlations=true kubernetesPlaylists=true preinstallAutoUpdate=true tlsMemcached=true influxdbBackendMigration=true panelMonitoring=true exploreMetrics=true zipkinBackendMigration=true logsContextDatasourceUi=true lokiStructuredMetadata=true managedPluginsInstall=true dashgpt=true accessActionSets=true openSearchBackendFlowEnabled=true publicDashboardsScene=true logsInfiniteScrolling=true cloudWatchRoundUpEndTime=true cloudWatchNewLabelParsing=true transformationsRedesign=true useSessionStorageForRedirection=true pinNavItems=true
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=sqlstore t=2025-02-07T10:09:46.88741434Z level=info msg="Connecting to DB" dbtype=mysql
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=migrator t=2025-02-07T10:09:46.889721269Z level=info msg="Starting DB migrations"
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=migrator t=2025-02-07T10:09:46.914845557Z level=info msg="migrations completed" performed=0 skipped=629 duration=603.959µs
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=secrets t=2025-02-07T10:09:46.919051305Z level=info msg="Envelope encryption state" enabled=true currentprovider=secretKey.v1
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=local.finder t=2025-02-07T10:09:46.99586198Z level=warn msg="Skipping finding plugins as an error occurred" path=/var/lib/grafana/plugins/performancecopilot-pcp-app error="stat /var/lib/grafana/plugins/performancecopilot-pcp-app: permission denied"
Feb 07 10:09:46 grafana.example.com grafana[127957]: logger=plugin.angulardetectorsprovider.dynamic t=2025-02-07T10:09:46.99732468Z level=info msg="Restored cache from database" duration=1.360079ms
Feb 07 10:09:47 grafana.example.com grafana[127957]: logger=plugin.store t=2025-02-07T10:09:47.001824798Z level=info msg="Loading plugins..."
Feb 07 10:09:47 grafana.example.com grafana[127957]: logger=plugins.registration t=2025-02-07T10:09:47.088722958Z level=info msg="Plugin registered" pluginId=grafana-lokiexplore-app
Feb 07 10:09:47 grafana.example.com grafana[127957]: logger=plugins.registration t=2025-02-07T10:09:47.121092163Z level=info msg="Plugin registered" pluginId=grafana-pyroscope-app
Feb 07 10:09:47 grafana.example.com grafana[127957]: logger=local.finder t=2025-02-07T10:09:47.121223573Z level=warn msg="Skipping finding plugins as an error occurred" path=/var/lib/grafana/plugins/performancecopilot-pcp-app error="stat /var/lib/grafana/plugins/performancecopilot-pcp-app: permission denied"
Feb 07 10:09:47 grafana.example.com grafana[127957]: logger=plugin.store t=2025-02-07T10:09:47.121250763Z level=info msg="Plugins loaded" count=56 duration=119.428405ms
Feb 07 10:09:47 grafana.example.com grafana[127957]: logger=resource-migrator t=2025-02-07T10:09:47.125772531Z level=info msg="Locking database"
Feb 07 10:09:47 grafana.example.com grafana[127957]: logger=resource-migrator t=2025-02-07T10:09:47.126779081Z level=error msg="Failed to lock database" error="Error 1105 (HY000): Percona-XtraDB-Cluster prohibits use of GET_LOCK with pxc_strict_mode = ENFORCING"
Feb 07 10:09:47 grafana.example.com grafana[127957]: logger=resource-server t=2025-02-07T10:09:47.127252081Z level=error msg="error initializing resource server" error="initialize Resource Server: initialize resource DB: run migrations: Error 1105 (HY000): Percona-XtraDB-Cluster prohibits use of GET_LOCK with pxc_strict_mode = ENFORCING"
Feb 07 10:09:47 grafana.example.com grafana[127957]: logger=resource-server t=2025-02-07T10:09:47.127299701Z level=error msg="error initializing resource server" error="initialize Resource Server: initialize resource DB: run migrations: Error 1105 (HY000): Percona-XtraDB-Cluster prohibits use of GET_LOCK with pxc_strict_mode = ENFORCING"
Feb 07 10:09:47 grafana.example.com grafana[127957]: Error: ✗ initialize Resource Server: initialize resource DB: run migrations: Error 1105 (HY000): Percona-XtraDB-Cluster prohibits use of GET_LOCK with pxc_strict_mode = ENFORCING
```

### What did you expect to happen?

For Grafana to fully honor the `database.migration_locking` setting and not try to lock the database for it's migrations.

### Did this work before?

Worked as expected in 11.4.1 and before.

### How do we reproduce it?

1. Install grafana 11.5.0 or 11.5.1 from rpm repository
2. Configure it to use a mysql database that does not support locking (e.g Percona-XtraDB-Cluster)
3. Set `database.migration_locking = false`.
4. Start it and see it fail.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 11.5.0
OS: AlmaLinux 9.5
Browser: Firefox

Installed from https://rpm.grafana.com

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by JohnnyQQQQ**
Fixes #100256 

We no longer ignore `migration_locking` in unified storage, so users running database systems that don't support it can still run Grafana at their own risk, especially when running in HA.

This can be tested by running Grafana against percona. I used the following file to run it in docker compose locally:

```docker
version: '3.8'

services:
  percona:
    image: percona/percona-xtradb-cluster:8.0
    container_name: percona-xtradb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      CLUSTER_NAME: pxc-cluster
      XTRABACKUP_PASSWORD: xtrabackuppass
      MYSQL_DATABASE: grafana
      MYSQL_USER: grafana
      MYSQL_PASSWORD: grafana
    ports:
      - "3306:3306"
    volumes:
      - percona_data:/var/lib/mysql
    # Bootstrap the cluster and set pxc_strict_mode to ENFORCING
    command: >
      --wsrep-new-cluster
      --pxc_strict_mode=ENFORCING
      --log-error-verbosity=3
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  percona_data: 
```

And the following grafana.ini to make it fail
```toml 
[database]
type = mysql
host = 127.0.0.1:3306
name = grafana
user = grafana
password = grafana
```

And the following grafana.ini to fix it
```toml
[database]
type = mysql
host = 127.0.0.1:3306
name = grafana
user = grafana
password = grafana
migration_locking = false
```

### CODE REVIEW

**Review by pstibrany — APPROVED** [review]

File: pkg/storage/unified/sql/db/migrations/migrator.go [hunk 1]
```diff
@@ -17,6 +17,9 @@ func MigrateResourceStore(_ context.Context, engine *xorm.Engine, cfg *setting.C
 
 	initResourceTables(mg)
 
-	// since it's a new feature enable migration locking by default
-	return mg.Start(true, 0)
+	sec := cfg.Raw.Section("database")
+	return mg.Start(
```
Comment (mustafasencer) [inline pkg/storage/unified/sql/db/migrations/migrator.go:21]: Optional: What about using the `RunMigrations` directly as it says `soft-deprecated` for [this one](https://github.com/grafana/grafana/blob/c91b37d8307dce3c4ae13eab5e24882714e396d9/pkg/services/sqlstore/migrator/migrator.go#L187)? This way we can also handle the TODO above?

**Review by mustafasencer — COMMENTED** [review]
LGTM - just a non blocker 🙂

**Review by mustafasencer — APPROVED** [review]

File: pkg/storage/unified/sql/db/migrations/migrator.go (hunk 1 above)
Comment (JohnnyQQQQ) [reply pkg/storage/unified/sql/db/migrations/migrator.go]: Good shout, changed it!

Comment (JohnnyQQQQ) [reply pkg/storage/unified/sql/db/migrations/migrator.go]: Tested it locally with the change, still working, going to merge 👍
