### PR TITLE
graph: fixes click after scroll in series override menu

### LINKED ISSUE #15621: v6.0.0-beta1: Cannot assign axis in series override
In Grafana v6.0.0-beta1 (d7f81c4) it is not possible to assign a series to a different axis. After selecting the series from the respective dropdown menu, it is not displayed in the editor:

screenshot 2019-02-24 at 10 17 32

### PR DESCRIPTION
**Pull request by daniellee**
Johannes fixed the issue but only in the dropdown-typehead2 directive so any component that uses dropdown-typeahead has the problem described in the linked issue.

This makes changes to dropdown-typeahead2 so that a css class for the button can be passed in. Means it can be used instead of dropdown-typeahead.

Switches to using dropdown-typeahead2 for series_overrides directive and for the influxdb, mysql and postgres datasources. dropdown-typeahead is not being used anywhere in Grafana so can maybe be removed but it might be used by external plugins.

This commit also fixes the index property which was set using an incorrectly spelled length property in the series_overrides directive.

Closes #15621

### CODE REVIEW

File: public/app/core/directives/dropdown_typeahead.ts [hunk 1]
```diff
@@ -137,9 +137,15 @@ export function dropdownTypeahead2($compile) {
...
       dropdownTypeaheadOnSelect: '&dropdownTypeaheadOnSelect',
       model: '=ngModel',
+      buttonTemplateClass: '@',
     },
     link: ($scope, elem, attrs) => {
       const $input = $(inputTemplate);
+
+      if (!$scope.buttonTemplateClass) {
+        $scope.buttonTemplateClass = 'gf-form-input';
+      }
```
Comment (jschill) [inline public/app/core/directives/dropdown_typeahead.ts]: This will make it impossible (well..) for us to remove the default class since it will match both undefined and if we pass an empty string.

**Comment by jschill** [comment]
Think it looks good and I've verified the influx/postgres/mysql works over here.
