### PR TITLE
Data sources: Hide the datasource redirection banner for users who can't interact with data sources

### LINKED ISSUE #92421: Anonymous/Viewer can access datasources page
### What happened?

When Grafana has “anonymous” access configured with a “Viewer” role, anonymous users have access to the datasource list and the datasource edit page (but cannot save).

### What did you expect to happen?

A redirection or error message.

### Did this work before?

I switched from 10.3.1 to 11.1.4, but I don't think 10.3.1 had this problem (I could be wrong).

### How do we reproduce it?

1. Enable anonymous access.
2. You should see the “Administration” button in the sidebar, click on it.
3. The information message “Data sources have a new home! You can discover new data sources or manage existing ones on the Connections page, accessible from the main menu” should appear, along with a "Go to connections" button.
4. You now have access to a list of all datasources.
5. Bonus: the "Build a dashboard" button doesn't work and redirects to the default dashboard. But if you manually modify the link of this button to "/connections/datasources/edit/<datasource_uid>", the anonymous user will have access to the datasource modification page in readonly.

If we try to access these pages by specifying the URL directly, we'll be redirected correctly.

Shouldn't the “Administration” button be visible at all as a “Viewer” anyway?

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 11.1.4
OS: Any
Browser: Any

### Grafana platform?

Docker

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by IevaVasiljeva**
**What is this feature?**

Hiding the DS redirection banner from `/admin` page (see the image below) from users who can't create/edit data sources and are therefore not supposed to see the DS list.

Screenshot 2024-09-03 at 17 40 33

**Why do we need this feature?**

This allowed Viewer users to reach data source list and data source edit pages (users could still not create new DSs or edit the existing DSs). Viewers are not able to create/edit data sources, therefore we hide the DS pages from them.

In general, users who can't create/edit data sources don't benefit from a banner telling them where data sources are.

**Who is this feature for?**

Any users

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/92421

**Special notes for your reviewer:**

It is not ideal that we show the `Administration` page to Viewers. We do this, because we want Viewers to be able to see `Correlations`, which live under `Administration` -> `Plugins and data`. I think we should rethink the nav section structure. But that's a larger piece of work which we should tackle separately.

### CODE REVIEW

File: pkg/services/datasources/accesscontrol.go [hunk 1]
```diff
@@ -25,7 +25,6 @@ var (
 var (
 	// ConfigurationPageAccess is used to protect the "Configure > Data sources" tab access
 	ConfigurationPageAccess = accesscontrol.EvalAny(
-		accesscontrol.EvalPermission(accesscontrol.ActionDatasourcesExplore),
```
Comment (IevaVasiljeva) [inline pkg/services/datasources/accesscontrol.go:28]: Note: unrelated change, but I noticed that `Explore` is not located under data sources anymore, so we don't need to account for it here.

**Review by academo — APPROVED** [review]

**Review by academo — APPROVED** [review]
Could you add some tests for this case?

**Review by xnyo — APPROVED** [review]
