### PR TITLE
TablePanel: Footer now updates values on column filtering

### LINKED ISSUE #55716: Table footer is not updating by columns filters
**What happened**:

When column filter is applied table footer with rows count is not updating.

**What you expected to happen**:

Rows count in table footer has been updated.

**How to reproduce it (as minimally and precisely as possible)**:

1. Prepare database

```sql
DROP TABLE IF EXISTS users;
CREATE TABLE users
(
    `id` UInt32,
    `type` char(155),
    `name` char(155)
)
ENGINE = MergeTree
PRIMARY KEY id
SETTINGS index_granularity = 8192;
INSERT INTO users VALUES (1, 'approved', 'Bob'), (2, 'not_approved', 'Martin'), (3, 'not_approved', 'Alex');
```

2. Create panel with name **Users** and query `SELECT * FROM users`

3. [Activate columns](https://tinyurl.com/2fcsa49x) filters in table

4. [Apply filter](https://tinyurl.com/2nxanaa2) in table

**Environment**:
- Grafana version: v9.0.5
- Data source type & version: ClickHouse 22.7.2.15
- OS Grafana is installed on: Linux 5.15.0-43-generic 46-Ubuntu SMP
- User OS & Browser: macOS Monterey, Google Chrome 105.0.5195.125 (Official Build) (arm64)
- Grafana plugins: just built-in plugins

### PR DESCRIPTION
**Pull request by mdvictor**
**What this PR does / why we need it**:
Table footer does not update when data changes through column filtering. This PR adds support for this but not necessarily in a trivial way.  

**Which issue(s) this PR fixes**:

Fixes #55716

**Special notes for your reviewer**:
This fixes the issue but I'm wondering if there is a better way, I feel like this implementation could be improved.

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/Table.tsx [hunk 1]
```diff
@@ -47,8 +48,7 @@ export interface Props {
   onColumnResize?: TableColumnResizeActionCallback;
   onSortByChange?: TableSortByActionCallback;
   onCellFilterAdded?: TableFilterActionCallback;
-  footerValues?: FooterItem[];
```
Comment (mckn) [inline packages/grafana-ui/src/components/Table/Table.tsx:50]: Would it be possible to introduce this change in a non-breaking way?

**Review by oscarkilhed — APPROVED** [review]
LGTM!
