### PR TITLE
Fix: Make the JSON in JSONCell Tooltip more visible

### LINKED ISSUE #25897: Table: JSONTooltip not following theme
**What happened**:
I hovered over a tags cell in a table. A tooltip opened, but the background was in dark mode while my Grafana is in light mode.

Screenshot from 2020-06-29 14-11-15

**What you expected to happen**:
The tooltip to follow Grafanas theme.

**How to reproduce it (as minimally and precisely as possible)**:
Create a table panel, choose TestDB as datasource and Grafana API as scenario. Hover over the  tags.
**Anything else we need to know?**:

**Environment**:
- Grafana version: Current master
- Data source type & version: TestDB
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Ubuntu 20.04 / Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by peterholmberg**
**What this PR does / why we need it**:
https://github.com/grafana/grafana/pull/23174 introduced some styling updates to tooltip. When this is being used in the JSONCell Tooltip, the text is barely visible since the JSONFormatter thinks the background is white. This is a "quick" workaround to have the JSON more visible in the tooltip. This should probably be revised to a more elegant solution in the future.

**Which issue(s) this PR fixes**:
Fixes #25897

**Special notes for your reviewer**:
Before: 

Screenshot from 2020-07-02 15-58-27

After: 

Screenshot from 2020-07-03 12-07-50

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
This did not really work well, (and not at all for dark theme). 

Better to add Tooltip theme that is dark in dark theme and light gray in light theme

**Comment by peterholmberg** [comment]
There was some leftover style on one of the divs @torkelo

**Comment by torkelo** [comment]
This still looks bad I think in light theme  (dark theme also a bit since the inner color)

**Comment by torkelo** [comment]
But not sure what the best solution is, think we need a new theme for the tooltip that is dark in dark theme and light gray in light theme

**Comment by peterholmberg** [comment]
Yeah, it's not optimal but it was the short term solution we discussed at stand up iirc.

**Comment by torkelo** [comment]
In dark theme it should use normal tooltip bg & shadow so that it stands out more. 

In light theme the shadow is a bit much I feel 
Screenshot from 2020-07-07 15-51-34

File: packages/grafana-ui/src/components/Table/JSONViewCell.tsx [hunk 1]
```diff
@@ -41,12 +42,15 @@ interface PopupProps {
 }
 
 const JSONTooltip: FC<PopupProps> = props => {
-  const clazz = css`
-    padding: 10px;
+  const theme = useTheme();
+  const className = css`
+    padding: ${theme.spacing.xs};
   `;
```
Comment (dprokop) [inline packages/grafana-ui/src/components/Table/JSONViewCell.tsx:48]: `useStyles` maybe?

File: packages/grafana-ui/src/components/Tooltip/Tooltip.tsx [hunk 2]
```diff
@@ -4,7 +4,7 @@ import { Popover } from './Popover';
 import { PopoverController, UsingPopperProps } from './PopoverController';
 
 export interface TooltipProps extends UsingPopperProps {
-  theme?: 'info' | 'error';
+  theme?: 'info' | 'error' | 'code';
```
Comment (dprokop) [inline packages/grafana-ui/src/components/Tooltip/Tooltip.tsx:7]: I woke up with a thought today, that maybe instead of being very explicit with `code` name, we could have `info-alt`?

**Review by dprokop — APPROVED** [review]
This looks good implementation wise, left few nits to consider. Also, I agree with @torkelo about the bg and box-shadows. In dark theme, it should use dark theme's tooltip default box-shadow, and the light theme should have some more subtle shadow:)

File: packages/grafana-ui/src/components/Tooltip/Tooltip.tsx (hunk 2 above)
Comment (peterholmberg) [reply packages/grafana-ui/src/components/Tooltip/Tooltip.tsx:7]: Hm, yeah maybe. Just need to add some documentation about that

Comment (dprokop) [reply packages/grafana-ui/src/components/Tooltip/Tooltip.tsx:7]: There is one already: https://github.com/grafana/grafana/blob/master/contribute/style-guides/styling.md#styling-with-theme

**Review by dprokop — APPROVED** [review]
