### PR TITLE
ValueMappings: Improve singlestat value mappings migration

### LINKED ISSUE #35537: [Grafana 8.0.1] Single stat widget and probably other widgets value mappings disappear when upgrading to 8.0.x
**What happened**:
After upgrading from 6.7.3 to 8.0.1 all Value mappings I had setup vanished and didn't find anything related to migration. It is very inconvenient to recreate all the mappings I have on around 300 dashboards and many of them have the value mappings set.

**What you expected to happen**:
When running grafana 8.0.1, I expected migrations to migrate the value mappings as they were in the older version

**How to reproduce it (as minimally and precisely as possible)**:
- Start a grafana instance with docker image version grafana/grafana:6.7.3

```
sudo docker run  -d --name grafana -p 3000:3000  -v $(PWD)/data:/var/lib/grafana -e "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,doitintl-bigquery-datasource,grafana-worldmap-panel,blackmirror1-singlestat-math-panel" grafana/grafana:6.7.3
```
- The log in to the new created grafana instance on localhost:3000 
- Create a dashboard and add value mapping like the following pictures (using grafana test data)

Screen Shot 2021-06-10 at 18 45 27

- select single stat visualization
Screen Shot 2021-06-10 at 18 45 38

- Add value mappings
Screen Shot 2021-06-10 at 18 46 13

- Save dashboard
Screen Shot 2021-06-10 at 18 46 31

On grafana 6.7.3 it looks something like this
Screen Shot 2021-06-10 at 18 51 54

Upgrade to grafana 8.0.1

```
sudo docker stop grafana && sudo docker rm grafana

sudo docker run  -d --name grafana -p 3000:3000  -v $(PWD)/data:/var/lib/grafana -e "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,doitintl-bigquery-datasource,grafana-worldmap-panel,blackmirror1-singlestat-math-panel" grafana/grafana:8.0.1


sudo docker logs -f grafana                  
✔ Downloaded grafana-clock-panel v1.1.2 zip successfully

Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.

✔ Downloaded grafana-simple-json-datasource v1.4.2 zip successfully

Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.

✔ Downloaded grafana-piechart-panel v1.6.2 zip successfully

Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.

✔ Downloaded doitintl-bigquery-datasource v1.0.8 zip successfully

Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.

✔ Downloaded grafana-worldmap-panel v0.3.3 zip successfully

Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.

✔ Downloaded blackmirror1-singlestat-math-panel v1.1.8 zip successfully

Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.

t=2021-06-10T21:54:57+0000 lvl=info msg="Starting Grafana" logger=server version=8.0.1 commit=8849243d27 branch=HEAD compiled=2021-06-10T11:31:37+0000
t=2021-06-10T21:54:57+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2021-06-10T21:54:57+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2021-06-10T21:54:57+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2021-06-10T21:54:57+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2021-06-10T21:54:57+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2021-06-10T21:54:57+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2021-06-10T21:54:57+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
t=2021-06-10T21:54:57+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
t=2021-06-10T21:54:57+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
t=2021-06-10T21:54:57+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
t=2021-06-10T21:54:57+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
t=2021-06-10T21:54:57+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2021-06-10T21:54:57+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2021-06-10T21:54:57+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2021-06-10T21:54:57+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2021-06-10T21:54:57+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2021-06-10T21:54:57+0000 lvl=info msg="App mode production" logger=settings
t=2021-06-10T21:54:57+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2021-06-10T21:54:57+0000 lvl=warn msg="SQLite database file has broader permissions than it should" logger=sqlstore path=/var/lib/grafana/grafana.db mode=-rw-r--r-- expected=-rw-r-----
t=2021-06-10T21:54:57+0000 lvl=info msg="Starting DB migrations" logger=migrator
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="Add index user.login/user.email"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="drop index IDX_temp_user_email - v1"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="drop index IDX_temp_user_org_id - v1"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="drop index IDX_temp_user_code - v1"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="drop index IDX_temp_user_status - v1"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table temp_user to temp_user_tmp_qwerty - v1"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="create temp_user v2"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_email - v2"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_org_id - v2"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_code - v2"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_status - v2"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="copy temp_user v1 to v2"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="drop temp_user_tmp_qwerty"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="Set created for temp users that will otherwise prematurely expire"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for dashboard_title"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="delete tags for deleted dashboards"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="delete stars for deleted dashboards"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="Add uid column"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="Update uid value"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="Add unique index datasource_org_id_uid"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index datasource_org_id_is_default"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="Add encrypted dashboard json column"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="Change dashboard_encrypted column to MEDIUMBLOB"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_alert_rule_tag_alert_id_tag_id - v1"
t=2021-06-10T21:54:57+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table alert_rule_tag to alert_rule_tag_v1 - v1"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="Create alert_rule_tag table v2"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_alert_rule_tag_alert_id_tag_id - Add unique index alert_rule_tag.alert_id_tag_id V2"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="copy alert_rule_tag v1 to v2"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="drop table alert_rule_tag_v1"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="Add column secure_settings in alert_notification"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="alter alert.settings to mediumtext"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="Add non-unique index alert_notification_state_alert_id"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="Add non-unique index alert_rule_tag_alert_id"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_annotation_tag_annotation_id_tag_id - v2"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table annotation_tag to annotation_tag_v2 - v2"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="Create annotation_tag table v3"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_annotation_tag_annotation_id_tag_id - Add unique index annotation_tag.annotation_id_tag_id V3"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="copy annotation_tag v2 to v3"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="drop table annotation_tag_v2"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="add index team_member.team_id"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="delete acl rules for deleted dashboards and folders"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="add index user_auth_token.user_id"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="Add revoked_at to the user auth token"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="create short_url table v1"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="add index short_url.org_id-uid"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="delete alert_definition table"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="recreate alert_definition table"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="add index in alert_definition on org_id and title columns"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="add index in alert_definition on org_id and uid columns"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="alter alert_definition table data column to mediumtext in mysql"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="drop index in alert_definition on org_id and title columns"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="drop index in alert_definition on org_id and uid columns"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index in alert_definition on org_id and title columns"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index in alert_definition on org_id and uid columns"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="Add column paused in alert_definition"
t=2021-06-10T21:54:58+0000 lvl=info msg="Executing migration" logger=migrator id="drop alert_definition table"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="delete alert_definition_version table"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="recreate alert_definition_version table"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add index in alert_definition_version table on alert_definition_id and version columns"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add index in alert_definition_version table on alert_definition_uid and version columns"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="alter alert_definition_version table data column to mediumtext in mysql"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="drop alert_definition_version table"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="create alert_instance table"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add index in alert_instance table on def_org_id, def_uid and current_state columns"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add index in alert_instance table on def_org_id, current_state columns"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add column current_state_end to alert_instance"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="remove index def_org_id, def_uid, current_state on alert_instance"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="remove index def_org_id, current_state on alert_instance"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="rename def_org_id to rule_org_id in alert_instance"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="rename def_uid to rule_uid in alert_instance"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add index rule_org_id, rule_uid, current_state on alert_instance"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add index rule_org_id, current_state on alert_instance"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="create alert_rule table"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add index in alert_rule on org_id and title columns"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add index in alert_rule on org_id and uid columns"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add index in alert_rule on org_id, namespace_uid, group_uid columns"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="alter alert_rule table data column to mediumtext in mysql"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add column for to alert_rule"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add column annotations to alert_rule"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add column labels to alert_rule"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="remove unique index from alert_rule on org_id, title columns"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add index in alert_rule on org_id, namespase_uid and title columns"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="create alert_rule_version table"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add index in alert_rule_version table on rule_org_id, rule_uid and version columns"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add index in alert_rule_version table on rule_org_id, rule_namespace_uid and rule_group columns"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="alter alert_rule_version table data column to mediumtext in mysql"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add column for to alert_rule_version"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add column annotations to alert_rule_version"
t=2021-06-10T21:54:59+0000 lvl=info msg="Executing migration" logger=migrator id="add column labels to alert_rule_version"
t=2021-06-10T21:55:00+0000 lvl=info msg="Executing migration" logger=migrator id=create_alert_configuration_table
t=2021-06-10T21:55:00+0000 lvl=info msg="Executing migration" logger=migrator id="Add column default in alert_configuration"
t=2021-06-10T21:55:00+0000 lvl=info msg="Executing migration" logger=migrator id="create library_element table v1"
t=2021-06-10T21:55:00+0000 lvl=info msg="Executing migration" logger=migrator id="add index library_element org_id-folder_id-name-kind"
t=2021-06-10T21:55:00+0000 lvl=info msg="Executing migration" logger=migrator id="create library_element_connection table v1"
t=2021-06-10T21:55:00+0000 lvl=info msg="Executing migration" logger=migrator id="add index library_element_connection element_id-kind-connection_id"
t=2021-06-10T21:55:00+0000 lvl=info msg="migrations completed" logger=migrator performed=95 skipped=234 duration=3.072267252s
t=2021-06-10T21:55:00+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2021-06-10T21:55:00+0000 lvl=info msg="Registering plugin" logger=plugins id=input
t=2021-06-10T21:55:00+0000 lvl=info msg="Registering plugin" logger=plugins id=grafana-plugin-admin-app
t=2021-06-10T21:55:02+0000 lvl=info msg="Registering plugin" logger=plugins id=blackmirror1-singlestat-math-panel
t=2021-06-10T21:55:02+0000 lvl=info msg="Registering plugin" logger=plugins id=grafana-clock-panel
t=2021-06-10T21:55:02+0000 lvl=info msg="Registering plugin" logger=plugins id=grafana-piechart-panel
t=2021-06-10T21:55:02+0000 lvl=info msg="Registering plugin" logger=plugins id=grafana-simple-json-datasource
t=2021-06-10T21:55:02+0000 lvl=info msg="Registering plugin" logger=plugins id=grafana-worldmap-panel
t=2021-06-10T21:55:02+0000 lvl=warn msg="Some plugin scanning errors were found" logger=plugins errors="plugin 'doitintl-bigquery-datasource' is unsigned"
t=2021-06-10T21:55:02+0000 lvl=info msg="Live Push Gateway initialization" logger=live.push_http
t=2021-06-10T21:55:02+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
```

- Log in to grafana again in the 8.0.1 version in localhost:3000 and go to the dashboard created in previous steps

- widget not doesn't have mapping just the value

Screen Shot 2021-06-10 at 18 57 40
- Edit the widget
Screen Shot 2021-06-10 at 18 59 29

- On the editing page of the widget scroll down to the bottom and there is no value mappings there
Screen Shot 2021-06-10 at 18 59 40

- If i look at the JSON definition of the dashboard the value mappings are there but are not shown or applied to the visualisation
```json
{
  "annotations": {
    "list": [
      {
        "$$hashKey": "object:31",
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 1,
  "links": [],
  "panels": [
    {
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "mappings": [
            {
              "from": "0",
              "id": 1,
              "operator": "",
              "text": "low",
              "to": "50",
              "type": 2,
              "value": ""
            },
            {
              "from": "51",
              "id": 2,
              "operator": "",
              "text": "high",
              "to": "1000",
              "type": 2,
              "value": ""
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "mean"
          ],
          "fields": "",
          "values": false
        },
        "text": {},
        "textMode": "auto"
      },
      "pluginVersion": "8.0.1",
      "targets": [
        {
          "queryType": "randomWalk",
          "refId": "A"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Panel Title",
      "type": "stat"
    }
  ],
  "schemaVersion": 30,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "New dashboard Copy",
  "uid": "lXA0P3eGz",
  "version": 1
}
```

**Anything else we need to know?**:

- I tried this steps upgrading from 6.7.3 -> 8.0.1 with the results shown above.

- I also tried this but upgrading to intermediate versions like the following  6.7.3 -> 7.0.6 -> 7.1.5 -> 7.2.2 -> 7.3.10 ->  7.4.5 -> 7.5.7 -> 8.0.1, and I have the same results as upgrading straight to 8.0.1; however the visualization and mappings were still showing OK in 7.5.7, It broke in the last step upgrading to 8.0.1

- Another step I tried perform the same dashboard creation  starting on 7.5.7 and upgrading to 8.0.1, but this time visualization and mappings showed OK in both versions. Based on this I think at some point the json schema for value mappings changed in some 7.x.x version and 8.0.1 is able to recognize the new version only and not older versions of the value mappings.

- I checked upgrade docs, changelogs, searched google if this was an issue or if there were some migration steps I needed to take but haven't found anything yet
  

**Environment**:
- Grafana version: 8.0.1 upgrading from version 7.5.7
- Data source type & version: Prometheus 2.25.0
- OS Grafana is installed on: Linux Ubuntu 20.04 Running offcial Grafana docker images
- User OS & Browser: Mac M1 Chrome
- Grafana plugins: grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,doitintl-bigquery-datasource,grafana-worldmap-panel,blackmirror1-singlestat-math-panel
- Others:

### PR DESCRIPTION
**Pull request by dprokop**
This was tricky, as in case of single stat value mappings get migrated first by the panel migration, and then by the dashboard migration of the value mappings (when dashboard schema version is quite outdated). Added some defensivenes towards that.

Fixes https://github.com/grafana/grafana/issues/35537

### CODE REVIEW

File: public/app/features/dashboard/state/DashboardMigrator.ts [hunk 1]
```diff
@@ -977,6 +977,11 @@ function upgradeValueMappings(oldMappings: any, thresholds?: ThresholdsConfig):
   const newMappings: ValueMapping[] = [];
 
   for (const old of oldMappings) {
+    // when migrating singlestat to stat/gauge, mappings are already handled by angular-> react migration
```
Comment (dprokop) [inline public/app/features/dashboard/state/DashboardMigrator.ts:980]:
```suggestion
    // when migrating singlestat to stat/gauge, mappings are already handled by panel type change handler used in that migration
```

File: public/app/features/dashboard/state/DashboardMigrator.test.ts [hunk 2]
```diff
@@ -1242,6 +1242,156 @@ describe('DashboardModel', () => {
...
+            "options": Object {
+              "30": Object {
+                "color": "orange",
+                "text": "50",
+              },
+            },
+            "type": "value",
+          },
+        ]
+      `);
```
Comment (torkelo) [inline public/app/features/dashboard/state/DashboardMigrator.test.ts:1315]: this does not look correct, value mappings should be all in one object map

Comment (torkelo) [reply public/app/features/dashboard/state/DashboardMigrator.test.ts:1315]: maybe that migration happens after this?

Comment (dprokop) [reply public/app/features/dashboard/state/DashboardMigrator.test.ts:1315]: You are right. Trying to migrate this dashboard:

```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 465,
  "links": [],
  "panels": [
    {
      "cacheTimeout": null,
      "colorBackground": false,
      "colorValue": false,
      "colors": [
        "#299c46",
        "rgba(237, 129, 40, 0.89)",
        "#d44a3a"
      ],
      "datasource": null,
      "format": "none",
      "gauge": {
        "maxValue": 100,
        "minValue": 0,
        "show": false,
        "thresholdLabels": false,
        "thresholdMarkers": true
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "interval": null,
      "links": [],
      "mappingType": 1,
      "mappingTypes": [
        {
          "name": "value to text",
          "value": 1
        },
        {
          "name": "range to text",
          "value": 2
        }
      ],
      "maxDataPoints": 100,
      "nullPointMode": "connected",
      "nullText": null,
      "postfix": "",
      "postfixFontSize": "50%",
      "prefix": "",
      "prefixFontSize": "50%",
      "rangeMaps": [
        {
          "from": "null",
          "text": "N/A",
          "to": "null"
        }
      ],
      "sparkline": {
        "fillColor": "rgba(31, 118, 189, 0.18)",
        "full": false,
        "lineColor": "rgb(31, 120, 193)",
        "show": false,
        "ymax": null,
        "ymin": null
      },
      "tableColumn": "",
      "targets": [
        {
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "90"
        }
      ],
      "thresholds": "",
      "timeFrom": null,
      "timeShift": null,
      "title": "Panel Title",
      "type": "singlestat",
      "valueFontSize": "80%",
      "valueMaps": [
        {
          "op": "=",
          "text": "test",
          "value": "24.3"
        },
        {
          "op": "=",
          "text": "91",
          "value": "190"
        },
        {
          "op": "=",
          "text": "test",
          "value": "90"
        }
      ],
      "valueName": "avg"
    }
  ],
  "schemaVersion": 22,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "test legacy stat",
  "uid": "QYrYmggnz",
  "variables": {
    "list": []
  },
  "version": 1
}
```

results in panel having this field config for mappings:

```
"mappings": [
        {
          "type": "value",
          "options": {
            "24.3": {
              "text": "test"
            }
          }
        },
        {
          "type": "value",
          "options": {
            "190": {
              "text": "91"
            }
          }
        },
        {
          "type": "value",
          "options": {
            "90": {
              "text": "test"
            }
          }
        }
      ],
```

Yet, it seems to be working fine 🤔

Comment (dprokop) [reply public/app/features/dashboard/state/DashboardMigrator.test.ts]: @torkelo the migration is now updated and collects val->text mappings in a single object. I've added it in the value mappings migration instead of base single stat migration to avoid code duplication.

**Review by torkelo — APPROVED** [review]
