### PR TITLE
Alerting: Paginate result previews

### LINKED ISSUE #64830: Alerting: large amount of instances crashes browser
**What happened**:

Tried to preview an alert rule with about 50k instances in the alert rule creation flow

**What you expected to happen**:

The UI not to crash, perhaps a "show x more instances" that progressively shows more instances?

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new Alert rule
2. Choose `Random Data` data source
3. Set "Series count" to a ridiculous high amount (~50k)

**Anything else we need to know?**:

Crashes on Chrome but not Firefox, it completely blocks the main thread for a good 10 seconds or so though

### PR DESCRIPTION
**Pull request by gillesdemey**
**What is this feature?**

Adds a pagination to the bottom of expression results when previewing alerts from a data query with more than 20 series (multi-dimensional alert rule).

image

**Why do we need this feature?**

Large query results could crash the browser (10k+)

**Which issue(s) does this PR fix?**:

Fixes #64830

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.
- [ ] There are no known compatibility issues with older supported versions of Grafana, or plugins.
- [ ] It passes the [Hosted Grafana feature readiness review](https://docs.google.com/document/d/1QL9Ly8KnXzpb6ISbg49pTODRO5mhA5tkkfIZVX6pqQU/edit) for observability, scalability, performance, and security.

### CODE REVIEW

File: public/app/features/alerting/unified/components/expressions/Expression.tsx [hunk 1]
```diff
@@ -131,30 +132,82 @@ interface ExpressionResultProps {
...
 
+  // reset the page index whenever the series changes
+  useEffect(() => {
+    setPageIndex(0);
+  }, [series, setPageIndex]);
+
   // sometimes we receive results where every value is just "null" when noData occurs
   const emptyResults = isEmptySeries(series);
   const isTimeSeriesResults = !emptyResults && isTimeSeriesFrames(series);
+  const resultPages = chunk(series, PAGE_SIZE);
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/expressions/Expression.tsx:148]: You can try to use `usePagination` hook (from (`public/app/features/alerting/unified/hooks/usePagination.ts`) to remove some of the pagination handling code.

**Review by konrad147 — APPROVED** [review]
Nice! one nit

File: public/app/features/alerting/unified/components/expressions/Expression.tsx (hunk 1 above)
Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/expressions/Expression.tsx:148]: We thought that for this particular case it would be more simple and clear to use `chunk` from `lodash` (we only go forward and backward, we don't go directly to the page)

Comment (konrad147) [reply public/app/features/alerting/unified/components/expressions/Expression.tsx:148]: Hmm, but you had to implement pagination logic once again (pageStart, pageEnd, clamp, chunk)

Comment (gillesdemey) [reply public/app/features/alerting/unified/components/expressions/Expression.tsx:148]: Yea I think we can re-use that one, I forgot we had that :D It doesn't seem to expose the `start` and `end` of the current page but that's easy to add to the hook 👍

Comment (konrad147) [reply public/app/features/alerting/unified/components/expressions/Expression.tsx:148]: It exposes `numberOfPages` which should be enough :)

Comment (soniaAguilarPeiron) [reply public/app/features/alerting/unified/components/expressions/Expression.tsx:148]: ahh ok! nice!

**Comment by gillesdemey** [comment]
Updated PR with the following changes:

Using `usePagination()` for the preview results.

Made the following changes to the `usePagination()` hook:

* Use clamping in the hook to prevent out-of-bounds access
* Added `nextPage` and `previousPage` which just call `onPageChange()`
* `pageStart` and `pageEnd` exposed
