### PR TITLE
Preferences: Fix updating of preferences for Navbar and Query History

### LINKED ISSUE #49322: Query History: Home tab option is not saved when using PUT
**What happened**:

As a part of #47506 query history preferences are saved using PATCH method. However using PUT method to override all settings it doesn't seem to pick up query history settings at all. This causes a bug where query history home tab settings are removed if a user saves any preferences using User Preferences panel.

**What you expected to happen**:

All provided settings are saved in the database.

**How to reproduce it (as minimally and precisely as possible)**:

* Use branch #49320 
* Change Query History tab settings
* Go to User -> Preferences
* Change any preferences e.g. timezone (`queryHistory` is passed in the payload)
* When the page is reloaded `/preferences/` endpoint contains empty (default) `queryHistory` entry

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.0-pre (dda716dc4a)
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
In https://github.com/grafana/grafana/pull/47506 we have added updating of query history preferences using PATCH method. However, when user if in their user preferences, we are using PUT method to override all settings and it was missing handling for preferences of query history (and navbar). This causes a bug where query history home tab settings are removed if a user saves any preferences using User Preferences panel.

I was fixing Query history part, but noticed that the same probably happens for navbar settings, so I updated that as well. @ashharrison90 could you please have a look if it make sense.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/49322

**Special notes for your reviewer**:

How to reproduce:
1. Got to Explore ->  Query History 
2. Change Query history tab settings
3. Go to User -> Preferences
4. Change any preferences e.g. timezone (queryHistory is passed in the payload)
5. When the page is reloaded /preferences/ endpoint contains empty (default) queryHistory entry

### CODE REVIEW

**Comment by ashharrison90** [comment]
@ivanahuckova thanks for spotting this!
being completely honest i've kinda forgotten how this works now, so apologies if this is a stupid question... 😅 

how does adding `QueryHistory`/`Navbar` to the `SavePreferenceCommand` prevent it from clearing the values? does it stop it from initialising with a default or something? 🤔

File: pkg/api/dtos/prefs.go [hunk 1]
```diff
@@ -26,8 +25,8 @@ type UpdatePrefsCmd struct {
 	// Enum: utc,browser
 	Timezone     string                         `json:"timezone"`
 	WeekStart    string                         `json:"weekStart"`
-	Navbar       *models.NavbarPreference       `json:"navbar,omitempty"`
-	QueryHistory *models.QueryHistoryPreference `json:"queryHistory,omitempty"`
+	Navbar       *pref.NavbarPreference         `json:"navbar,omitempty"`
+	QueryHistory *pref.QueryHistoryPreference   `json:"queryHistory,omitempty"`
```
Comment (papagian) [inline pkg/api/dtos/prefs.go:29]: I would suggest getting rid of `models.NavbarPreference` and `models.QueryHistoryPreference` and use everywhere the models defined under the `preference` package, if possible

**Review by papagian — APPROVED** [review]
LGTM; I have tested and it fixes the issue.

File: pkg/api/dtos/prefs.go (hunk 1 above)
Comment (ivanahuckova) [reply pkg/api/dtos/prefs.go]: I got rid of them in https://github.com/grafana/grafana/pull/49677/commits/6f7aa9f8d35a7aad505fa3bad7e2ddeaddb4c527

Comment (papagian) [reply pkg/api/dtos/prefs.go]: it seems that it's not possible after all due to cycle dependencies; sorry!

**Review by ifrost — APPROVED** [review]
Splendid ❤️

**Comment by ivanahuckova** [comment]
@ashharrison90 

>how does adding QueryHistory/Navbar to the SavePreferenceCommand prevent it from clearing the values? does it stop it from initialising with a default or something? 🤔

So unfortunately for Query history and Navbar, when we change the settings in User preferences, we first GET the current preferences, and then we use PUT and send the whole new preferences object (old preferences + changed new item) to the backend. But because in backend, we didn't pass Query history and Navbar preferences for PUT requests, they became undefined.

**Comment by ivanahuckova** [comment]
@ashharrison90 

>how does adding QueryHistory/Navbar to the SavePreferenceCommand prevent it from clearing the values? does it stop it from initialising with a default or something? 🤔

So unfortunately for Query history and Navbar, when we change the settings in User preferences, we first GET the current preferences, and then we use PUT and send the whole new preferences object (old preferences + changed new item) to the backend. But because in backend, we didn't pass Query history and Navbar preferences for PUT requests, they became undefined. 

@grafana/user-essentials for the future, would it make sense to change this PUT request to PATCH as we are are usually changing just couple of preferences, and not all?
