### PR TITLE
Traces: Fix missing CopyButton on KeyValueTables and overlapping of panels

### LINKED ISSUE #46032: Trace View: Detail panel overlaps other spans
**What happened**:
Screen Shot 2022-03-01 at 7 44 08 AM

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by svennergr**
**What this PR does / why we need it**:
As described in #46032 the traces panel is overlapping other panels when the inner KeyValue tables (Tags, Process) are opened. This PR introduces a fix for that by simply adding a fixed height of `30px` to the rows of KeyValue tables.

While working on a fix for the overlapping issue, I noticed that the buttons to copy values from the table disappeared somewhen in the past. I fixed that as well by rewriting the `CopyIcon` component to a functional component and to also use RTL.

**Which issue(s) this PR fixes**:

Fixes #46032 

**Special notes for your reviewer**:

KeyValueTable with overlapping and missing CopyIcon issue before:
image

Fixed KeyValueTable now:
image

### CODE REVIEW

File: packages/jaeger-ui-components/src/TraceTimelineViewer/SpanDetail/KeyValuesTable.tsx [hunk 1]
```diff
@@ -44,6 +44,7 @@ export const getStyles = (theme: GrafanaTheme2) => {
     `,
     row: css`
       label: row;
+      height: 30px;
```
Comment (connorlindsey) [inline packages/jaeger-ui-components/src/TraceTimelineViewer/SpanDetail/KeyValuesTable.tsx:47]: Fix looks great, but the cells don't seem to be vertically aligned. One potential fix is to move the height declaration to the `td`. 

Screen Shot 2022-05-20 at 9 42 32 AM

**Review by connorlindsey — CHANGES_REQUESTED** [review]

File: packages/jaeger-ui-components/src/TraceTimelineViewer/SpanDetail/KeyValuesTable.tsx (hunk 1 above)
Comment (svennergr) [reply packages/jaeger-ui-components/src/TraceTimelineViewer/SpanDetail/KeyValuesTable.tsx]: Good catch - didn't see that! I did so and moved it to the `td`.

**Review by connorlindsey — APPROVED** [review]
