### PR TITLE
Provisioning: Add validation for missing organisations in datasource, dashboard, and notifier configurations

### LINKED ISSUE #20502: Provisioning: Validation of valid org id is missing for datasources, dashboards, and notifiers
**What happened**:
Data sources provided in datasource.yml file getting inserted into the database even though the org ID doesn't exist in the DB.
**What you expected to happen**:
Data sources should not be inserted into the db if org ID doesn't exist
**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce
1) In the datasource.yml file change the org ID to one that doesn't exist in org table
2) Trigger the reload API /api/admin/provisioning/dashboards/reload
3) check datasource table you will be seeing record with this datasource 

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version: Postgres 11
- OS Grafana is installed on: Linux
- User OS & Browser: Windows and Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by nabokihms**
**What this PR does / why we need it**:
This PR adds validation that organization IDs specified in configs exist.

**Which issue(s) this PR fixes**:
Fixes #20502

**Special notes for your reviewer**:
* I'm not sure about notifiers, because org_name in configs looks tricky, but everything should be ok :)
* It looks like a breaking change for people, who have provisioning configs with invalid org IDs.

### CODE REVIEW

File: pkg/services/provisioning/dashboards/config_reader.go [hunk 1]
```diff
@@ -88,6 +89,10 @@ func (cr *configReader) readConfig() ([]*config, error) {
 			dashboard.OrgID = 1
 		}
 
+		if err := utils.CheckOrgExists(dashboard.OrgID); err != nil {
+			return nil, fmt.Errorf("failed to provision dashboards with %s reader: %w", dashboard.Name, err)
```
Comment (aknuds1) [inline pkg/services/provisioning/dashboards/config_reader.go:93]: I think it's better to quote the dashboard name, in case it contains whitespace.
```suggestion
			return nil, fmt.Errorf("failed to provision dashboards with %q reader: %w", dashboard.Name, err)
```

File: pkg/services/provisioning/dashboards/config_reader_test.go [hunk 2]
```diff
@@ -20,6 +23,14 @@ func TestDashboardsAsConfig(t *testing.T) {
 	t.Run("Dashboards as configuration", func(t *testing.T) {
 		logger := log.New("test-logger")
 
+		sqlstore.InitTestDB(t)
+		for _, index := range []int{1, 2} {
+			orgCommand := models.CreateOrgCommand{Name: fmt.Sprintf("Main Org. %v", index)}
+			if err := sqlstore.CreateOrg(&orgCommand); err != nil {
+				t.Fatal(err)
+			}
```
Comment (aknuds1) [inline pkg/services/provisioning/dashboards/config_reader_test.go:31]: We use `require.NoError` to verify an error didn't occur.
```suggestion
			err := sqlstore.CreateOrg(&orgCommand)
			require.NoError(t, err)
```

File: pkg/services/provisioning/datasources/config_reader.go [hunk 3]
```diff
@@ -95,13 +97,8 @@ func (cr *configReader) validateDefaultUniqueness(datasources []*configs) error
...
 
-			if ds.Access == "" {
-				ds.Access = models.DS_ACCESS_PROXY
-			}
-
-			if ds.Access != models.DS_ACCESS_DIRECT && ds.Access != models.DS_ACCESS_PROXY {
-				cr.log.Warn("invalid access value, will use 'proxy' instead", "value", ds.Access)
-				ds.Access = models.DS_ACCESS_PROXY
+			if err := cr.validateAccessAndOrgID(ds); err != nil {
+				return fmt.Errorf("failed to provision %s datasource: %w", ds.Name, err)
```
Comment (aknuds1) [inline pkg/services/provisioning/datasources/config_reader.go:101]: I suggest quoting data source names, in case they contain whitespace.
```suggestion
				return fmt.Errorf("failed to provision %q data source: %w", ds.Name, err)
```

File: pkg/services/provisioning/notifiers/config_reader.go [hunk 4]
```diff
@@ -82,6 +84,10 @@ func checkOrgIDAndOrgName(notifications []*notificationsAsConfig) {
 				} else {
 					notification.OrgID = 0
 				}
+			} else {
+				if err := utils.CheckOrgExists(notification.OrgID); err != nil {
+					return fmt.Errorf("failed to provision %s notification: %w", notification.Name, err)
```
Comment (aknuds1) [inline pkg/services/provisioning/notifiers/config_reader.go:89]:
```suggestion
					return fmt.Errorf("failed to provision %q notification: %w", notification.Name, err)
```

File: pkg/services/provisioning/notifiers/config_reader_test.go [hunk 5]
```diff
@@ -31,6 +32,12 @@ func TestNotificationAsConfig(t *testing.T) {
 	Convey("Testing notification as configuration", t, func() {
 		sqlstore.InitTestDB(t)
 
+		for _, index := range []int{1, 2, 3, 4} {
```
Comment (aknuds1) [inline pkg/services/provisioning/notifiers/config_reader_test.go:35]: I think the following is more concise and less prone to mistakes:
```suggestion
		for i := 1; i < 5; i++ {
```

**Review by aknuds1 — COMMENTED** [review]
AFAICT it looks generally good! Left some suggestions though, for things that I think could be improved.

**Review by aknuds1 — APPROVED** [review]
Haven't tested it yet, but looks good code wise!

**Comment by aknuds1** [comment]
There's a Go lint failure in CI, can you please fix it?

**Review by kylebrandt — APPROVED** [review]

**Comment by aknuds1** [comment]
@papagian You wanted to see another test case?

**Comment by papagian** [comment]
> @papagian You wanted to see another test case?

Yes it would be great to have an additional test before organisations are created [here](https://github.com/grafana/grafana/blob/aedca0ddbc023af8a88535ef7aa7e00d33e08c7d/pkg/services/provisioning/dashboards/config_reader_test.go#L27) to verify that reading the configuration fails if there is the dashboard organisation does not exist.

**Comment by nabokihms** [comment]
@papagian I have added the negative test case for the feature. Could you please take a look at it one more time?

**Review by papagian — APPROVED** [review]
Thank you for your contribution!
