### PR TITLE
Table: Fixes issue with field config applied to wrong fields when hiding columns

### LINKED ISSUE #43191: TablePanel: hidden fields does not work
**What happened**:

Since release 8.2.x, we can now use a feature to be able to HIDE fields and still use in datalinks ( #24092 - https://github.com/grafana/grafana/issues/24092 )

But when you use at least 2 hidden fields, the field options seems to be applied on another (further right). It seems to be the same issue with all "field Options"

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Here is an example using the CSV example, the "seconds" Unit should be applied to "Count" columns and NOT on "Price" column.

grafana-hidden-fields

**Anything else we need to know?**:

So the feature is not usable, too bad after so long to wait for this feature to move to Grafana 8.x

**Environment**:
- Grafana version: 8.3.2
- Data source type & version: 
- OS Grafana is installed on: Linux
- User OS & Browser: CHrome
- Grafana plugins: Table panel
- Others:

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #43191

Hidden fields made it so we passed the wrong field to the TableCell

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/utils.ts [hunk 1]
```diff
@@ -79,20 +79,21 @@ export function getColumns(
...
-      minWidth: fieldTableOptions.minWidth || columnMinWidth,
+      minWidth: fieldTableOptions.minWidth ?? columnMinWidth,
       filter: memoizeOne(filterByValue(field)),
       justifyContent: getTextAlign(field),
       Footer: getFooterValue(fieldIndex, footerValues),
     });
   }
 
-  // set columns that are at minimum width
+  // set columns that are at minimum widthya
```
Comment (pbaumard) [inline packages/grafana-ui/src/components/Table/utils.ts:96]: A typo to be reverted.

File: packages/grafana-ui/src/components/Table/types.ts [hunk 2]
```diff
@@ -33,3 +34,11 @@ export interface TableCellProps extends CellProps<any> {
 export type CellComponent = FC<TableCellProps>;
 
 export type FooterItem = Array<KeyValue<string>> | string | undefined;
+
+export type GrafanaTableColumn = Column & {
+  grafanaField: Field;
```
Comment (dprokop) [inline packages/grafana-ui/src/components/Table/types.ts:39]: Can we ust name it `field` if this doesn't conflict with properties from `Column` interface?

**Review by dprokop — APPROVED** [review]
Works like a charm! Left one nit to consider

File: packages/grafana-ui/src/components/Table/types.ts (hunk 2 above)
Comment (torkelo) [reply packages/grafana-ui/src/components/Table/types.ts:39]: @dprokop yes, but this type is really owned by react-table,  It could used in a a future release of react-table, but maybe unlikely

**Review by simPod — APPROVED** [review]

**Comment by Donal-Goggin** [comment]
The column filter still seems to be affected by this bug in 8.5.2. If you hide the first column in a table the filter icon jumps to the column on the right but it still filters the original column just to the left of it.
