### PR TITLE
Explore: Fixes incorrect handling of utc in timeEpic

### LINKED ISSUE #18385: Explore: wrong output when calculating utc values in timeEpic
When timeZone prop was made into a string this line was forgotten during that process https://github.com/grafana/grafana/blob/c8b195147e1293f41b23e4df7d378eebc7b6235a/public/app/features/explore/state/epics/timeEpic.ts#L24

This means that we'll never evaluate isUtc to true because it's not defined.

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
During a refactoring a while ago the timeZone prop was converted from object to string and because of missing typings this was not caught in timeEpic. This PR should fix both typings and the bug.

**Which issue(s) this PR fixes**:
Fixes #18385

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by torkelo** [comment]
Is this something we need to cherry pick to 6.3 for the stable release tomorrow?

**Comment by hugohaggmark** [comment]
I don't know, all the absolutranges are wrong for utc calculations in Explore. By `AbsolutRanges` I mean when the user zooms the Graph or when the user scans.

File: packages/grafana-data/src/utils/moment_wrapper.ts [hunk 1]
```diff
@@ -96,3 +97,15 @@ export const toDuration = (input?: DurationInput, unit?: DurationUnit): DateTime
 export const dateTime = (input?: DateTimeInput, formatInput?: FormatInput): DateTime => {
   return moment(input as MomentInput, formatInput) as DateTime;
 };
+
+export const dateTimeFromTimeZone = (
```
Comment (aocenas) [inline packages/grafana-data/src/utils/moment_wrapper.ts]: Just a nitpicking regarding the naming. Probably `dateTimeWithTimeZone` or `dateTimeInTimeZone` would make more sense to me.

**Review by aocenas — APPROVED** [review]

File: packages/grafana-data/src/utils/moment_wrapper.ts (hunk 1 above)
Comment (hugohaggmark) [reply packages/grafana-data/src/utils/moment_wrapper.ts]: How about `dateTimeForTimeZone`?

Comment (aocenas) [reply packages/grafana-data/src/utils/moment_wrapper.ts]: Yeah that works too. Btw what will happen if you call `dateTimeFromTimeZone` without parameters?

Comment (hugohaggmark) [reply packages/grafana-data/src/utils/moment_wrapper.ts]: It will call dateTime without parameters resulting in `moment()` I believe or do you see any catch?

Comment (aocenas) [reply packages/grafana-data/src/utils/moment_wrapper.ts]: No you are right, I thought maybe there was something special going on but yeah it will just be like calling `moment()`
