### PR TITLE
Graphite: Fixed issue with functions with multiple required params and no defaults caused params that could not be edited (groupByNodes groupByTags)

### LINKED ISSUE #16961: Grafana v6: second parameter in new groupByTags() function not selectable
**What happened**: In Grafana v6, after adding a new groupByTags() function, the second parameter is not selectable. (if there is value at second parameter already, then it's selectable)

**What you expected to happen**: Able to fill in second parameter in new groupByTags() function

**How to reproduce it (as minimally and precisely as possible)**: as above

**Anything else we need to know?**: No

**Environment**:
- Grafana version: v6.1.6
- Data source type & version: Metrictank
- OS Grafana is installed on: RHEL 7.x
- User OS & Browser: Chrome or Safari
- Grafana plugins:  N/A
- Others:

### LINKED ISSUE #20345: groupByNodes query editor issues (extra comma results in broken query, fires off query before done editing)
Grafana v6.4.4 (092e514)

See https://youtu.be/o6XfP4w8Qno

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #20345
Fixes #16961 

This is touching the oldest part of Grafana, a messy angular directive with no tests :(  

The UX could be better for multiple required fields but think this is good enough for a bug fix

### CODE REVIEW

**Review by dprokop — APPROVED** [review]
Tested it and it seems to be working fine

File: public/app/plugins/datasource/graphite/func_editor.ts [hunk 1]
```diff
@@ -184,24 +184,28 @@ export function graphiteFuncEditor($compile: any, templateSrv: TemplateSrv) {
...
           }
 
-          const $paramLink = $(
-            '<a ng-click="" class="graphite-func-param-link' +
-              (last ? ' query-part__last' : '') +
-              '">' +
-              (hasValue ? paramValue : '&nbsp;') +
-              '</a>'
-          );
+          console.log(linkClass);
```
Comment (dprokop) [inline public/app/plugins/datasource/graphite/func_editor.ts]:
```suggestion
```
