### PR TITLE
Prometheus: Fix parsing logic of prometheus expressions to honor the order of binary operations

### LINKED ISSUE #103464: Prometheus: clamp function cannot be parsed properly into the visual query editor
We can create a query with `clamp` function in visual query editor with no problem. We can use that function in code editor too. But whenever we want to switch from code editor to visual editor we got the warning

> Operations are presented in the order they are executed, not in the inverted order they are written in the text query

And the query we wrote in code editor becomes badly formed in visual query editor:
```
// In code editor
clamp(sum(rate(loki_distributor_bytes_received_total{cluster="loki", tenant="kubernetes"}[5m])) / 1024 / 1024, 5, 30)

// After switching to visual editor
clamp(sum(rate(loki_distributor_bytes_received_total{cluster="loki", tenant="kubernetes"}[5m])), 5, 30) / 1024 / 1024
```

This should be parsed without a problem as it can be built in visual query editor without an issue. 

Try it on [play.grafana.org](https://play.grafana.org/explore?schemaVersion=1&panes=%7B%227fb%22%3A%7B%22datasource%22%3A%22--+Mixed+--%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22datasource%22%3A%7B%22type%22%3A%22graphite%22%2C%22uid%22%3A%22000000001%22%7D%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-1h%22%2C%22to%22%3A%22now%22%7D%7D%7D&orgId=1)

When we remove the binary operations from the query it parses it properly. So we should focus how we handle/parse binary operators.

### PR DESCRIPTION
**Pull request by jcolladokuri**
**What is this feature?**

This is a minor fix to the way we parse expressions for Prometheus. Specifically with binary operations, we were always adding them to the end. For the cases where the binary operations exist within a function argument (i.e `clamp(sum(rate(loki_distributor_bytes_received_total{cluster="loki", tenant="kubernetes"}[5m])) / 1024 / 1024, 5, 30)`)  adding operations to the end, ignored the place where they should be added:

https://github.com/user-attachments/assets/2572defb-80f7-4613-865a-ea53c62ad2ad

**Why do we need this feature?**

This fixes a small part of our logic for binary operations so that the order in which they appear in the expression is respected.

**Who is this feature for?**

Prometheus users.

**Which issue(s) does this PR fix?**:

Fixes #103464

### CODE REVIEW

File: packages/grafana-prometheus/src/querybuilder/parsing.ts [hunk 1]
```diff
@@ -407,6 +390,16 @@ function handleBinary(expr: string, node: SyntaxNode, context: Context) {
 
   const rightBinary = right.type.id === BinaryExpr;
 
+  // binary operations that are part of a function arguument do not get processed and added to the query until the end, this index helps keep track
```
Comment (itsmylife) [inline packages/grafana-prometheus/src/querybuilder/parsing.ts]:
```suggestion
  // binary operations that are part of a function argument do not get processed and added to the query until the end, this index helps keep track
```

**Review by itsmylife — APPROVED** [review]
LGTM 🚀 
Nicely done.

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/18467674239)
- Version: 12.3.0-18467674239
