### PR TITLE
Alerting: Add support for linking external images securely - Azure Blob (#1)

### LINKED ISSUE #56597: Alerting: Linking external images securely - Azure Blob
**What happened**:
Hi, we would like to send Images to MS Teams using External image storage - Azure Storage Account.

However only public Containers are supported right. See https://grafana.com/docs/grafana/latest/alerting/images-in-notifications/#supported-notifiers

Information from the images like IP addresses, ports or just the endpoint names are exposed to public internet..

**What you expected to happen**:

Store images in non-public storage

**How to reproduce it (as minimally and precisely as possible)**:

It's documented as per the official link above.

**Anything else we need to know?**:

My proposal is to add into `[external_image_storage.azure_blob]` section `sas_token`
This variable will be attached to the notification image URL as parameter like on the screenshot below.

image
https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview#sas-token

Below is proposed Azure Blob config:

```
#################################### External image storage ##########################
[external_image_storage]
provider = azure_blob

[external_image_storage.azure_blob]
account_name =
account_key =
container_name =
sas_token =
```

The idea is to change the Blob Container to Private and generate SAS token for the Container and supply SAS token as Grafana ENV variable.

It will be not super secure, however it is possibile to set expiration of the SAS token and create rotation automation if that will help. So i guess this small change can be big improvement in term of data privacy.

### PR DESCRIPTION
**Pull request by petrsx**
**What this PR does / why we need it**:

Enable option to store/share external images securely in private Azure Container
(if `sas_token` variable value is not specified, public container required as is right now)

**Which issue(s) this PR fixes**:

Fixes #56597

**Special notes for your reviewer**:

`add to changelog` :innocent:

### CODE REVIEW

**Comment by brendamuir** [comment]
@chri2547 @gguillotte-grafana can you take a look - it's a configure grafana file. Thanks!

**Comment by sakjur** [comment]
I don't think pre-generating a long-lived token is the correct approach here? It seems to me like the [SAS overview documentation](https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview#signing-a-sas-token-with-an-account-key) suggests that we should use the account key to generate an account SAS token or service SAS token.

**Comment by petr-stupka** [comment]
Hi @sakjur, i think it's correct, depend on the usage. In my case the `sas_token` variable is SAS token created manually using the `account_key` as simple solution.

In advanced scenario the `pkg/components/imguploader/azureblobuploader.go` can generate SAS token for each image created, however SAS token generated would need to be long lived as well, otherwise the URL link to the image will be invalid. As example the SAS token validity can be specified by `sas_token_validity = 30` (valid for 30 days)

**Comment by sakjur** [comment]
> Hi @sakjur, i think it's correct, depend on the usage. In my case the `sas_token` variable is SAS token created manually using the `account_key` as simple solution.
> 
> In advanced scenario the `pkg/components/imguploader/azureblobuploader.go` can generate SAS token for each image created, however SAS token generated would need to be long lived as well, otherwise the URL link to the image will be invalid. As example the SAS token validity can be specified by `sas_token_validity = 30` (valid for 30 days)
> 
> I may try to put the advanced scenario in the code if that make sense?

Ah, I see. I believe that would make more sense, as if nothing else we'd be able to generate a per-image SAS token which would make the 30 days rolling?

**Review by chri2547 — APPROVED** [review]

**Review by gguillotte-grafana — APPROVED** [review]

**Comment by petr-stupka** [comment]
Hi @sakjur can you please review it? parameter `sas_token_expiration` means how many days the SAS token will be valid after image upload. Many thanks!

File: pkg/components/imguploader/imguploader.go [hunk 1]
```diff
@@ -110,8 +110,10 @@ func NewImageUploader() (ImageUploader, error) {
 		account_name := azureBlobSec.Key("account_name").MustString("")
 		account_key := azureBlobSec.Key("account_key").MustString("")
 		container_name := azureBlobSec.Key("container_name").MustString("")
+		sas_token_expiration := azureBlobSec.Key("sas_token_expiration").MustString("")
```
Comment (sakjur) [inline pkg/components/imguploader/imguploader.go:113]: I'd suggest either making this a `Duration` or `int`, so that we do the conversion in the same location as other variables.

If you don't want to do that, please add `_days` as the unit to the argument, since that'll be unclear otherwise.

```suggestion
		sas_token_expiration := azureBlobSec.Key("sas_token_expiration").MustDuration(0)
```

```suggestion
		sas_token_expiration := azureBlobSec.Key("sas_token_expiration_days").MustInt(-1)
```

Comment (petr-stupka) [reply pkg/components/imguploader/imguploader.go]: Added this:

```golang
sas_token_expiration := azureBlobSec.Key("sas_token_expiration_days").MustInt(-1)
```

**Comment by petr-stupka** [comment]
Hi @sakjur, should be completed. I'm not sure about the `continuous-integration/drone/pr` check

It is failing at something unrelated to the changes

image

where imguploader passed the test

image

**Comment by sakjur** [comment]
Thank you, we have a flaky test problem right now, so I’ll see if I can get that passing 👍

**Review by sakjur — APPROVED** [review]
LGTM, thank you :+1:
