### PR TITLE
Elasticsearch: Fix empty query (via template variable) should be sent as wildcard

### LINKED ISSUE #17442: Incorrect blank query sent to Elasticsearch when using Text box
**What happened**:
An empty Query is set via the Text Box field variable (via {Textbox:raw} in the Query field). Grafana sends an empty string to Elasticsearch, which will always respond with no matches.

**What you expected to happen**:
An empty query should always send an "*" to Elasticsearch.  This can be observed working properly when using the Query field directly.  When the Query field is empty, Grafana sends an "*" for the Elasticsearch Query_String/Query setting, which results in all documents being returned (no filter).  If a Textbox variable is being used to set the Query field, and it is also empty, the same behavior should occur.

**How to reproduce it (as minimally and precisely as possible)**:
Add a Text Box variable to a Dashboard (name it 'Lucene'), with a Table, using an Elasticsearch 6+ Datasource that has valid documents that will match your current Time Range.

With a refresh, documents will be returned.  Note that the Query field is empty, and the Query Inspector shows an "*" is sent for the Elasticsearch query.

Now set the Query field to ${Lucene:raw}.  With the Text Box empty, refresh your dashboard.  Instead of receiving the same results, no results will be received.  The Query Inspector shows that a "" is sent for the Elasticsearch query.

**Anything else we need to know?**:
Attached screenshots showing the difference in behaviors.

**Environment**:
- Grafana version:  6+ (valid since Text Box was added in 5.x?)
- Data source type & version: Elasticsearch 6+
- OS Grafana is installed on: CentOS 7
- User OS & Browser: NA
- Grafana plugins: NA
- Others:
ESQuerySuccess
ESQueryFailed

### PR DESCRIPTION
**Pull request by davewat**
… issue that appears when passing raw data from variables.

**What this PR does / why we need it**:
Elasticsearch requires an * when an empty query is requested (default to all).  Grafana captures this requirement in several places.  However, when submitted via a raw variable (ie: ${Variable:raw}), the templateSrv converts this to an empty string.  Elasticsearch will therefore return no results.  Since this is Elasticsearch specific, this PR provides a simple sanity check after templateSrv processes the query.  If the result is '', it is replaced with a '*'.

**Which issue(s) this PR fixes**:

Fixes #17442 

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/plugins/datasource/elasticsearch/datasource.ts [hunk 1]
```diff
@@ -257,7 +257,11 @@ export class ElasticDatasource {
         target.alias = this.templateSrv.replace(target.alias, options.scopedVars, 'lucene');
       }
 
-      const queryString = this.templateSrv.replace(target.query || '*', options.scopedVars, 'lucene');
+      let queryString = this.templateSrv.replace(target.query || '*', options.scopedVars, 'lucene');
```
Comment (torkelo) [inline public/app/plugins/datasource/elasticsearch/datasource.ts]: can you remove the `|| '*'` logic

Comment (davewat) [reply public/app/plugins/datasource/elasticsearch/datasource.ts]: I initially thought that check was redundant too, but removing it can cause errors if target.query is undefined.  templateSrv.replace will return an undefined queryString if target.query is also undefined, which the queryBuilder won't like.  I only found this issue in one place, with a new installation, on the Home Dashboard, after completing the second step of 'Create your first data source', with an Elasticsearch Data Source, the built query will not have the required Elasticsearch "query" field.

However, a small modification to my PR accounts for both scenarios, and the || '*' logic can then be removed.  Will update the PR with the fix.

Excuse the long response, just wanted to document the resulting change.

**Review by torkelo — APPROVED** [review]
