### PR TITLE
Dynamic dashboards: Paste v1 panel clipboard into dynamic dashboard layouts

### LINKED ISSUE #120078: Copying a V1 panel does not allow it to be pasted in V2
Steps to reproduce:
1. Disable Dynamic Dashboards
2. Open a dashboard
3. Copy a panel
4. Enable Dynamic Dashboards
5. Try to paste the panel in a dashboard

### PR DESCRIPTION
**Pull request by oscarkilhed**
**What is this feature?**

Allows pasting panels in the v1 format into dynamic dashboards using v2 format.

Fixes #120078

### CODE REVIEW

File: public/app/features/dashboard-scene/scene/layouts-shared/paste.ts [hunk 1]
```diff
@@ -42,6 +44,23 @@ export interface PanelStore {
   gridItem: GridLayoutItemKind | AutoGridLayoutItemKind;
 }
 
+/** Dynamic Dashboards copy format: element map + layout item kind (dashboard schema v2). */
+function isV2DynamicDashboardsPanelClipboard(obj: unknown): obj is PanelStore {
+  if (typeof obj !== 'object' || obj === null) {
+    return false;
+  }
+  const elements = Reflect.get(obj, 'elements');
```
Comment (ifrost) [inline public/app/features/dashboard-scene/scene/layouts-shared/paste.ts:52]: Why do we need `Reflect.get`? 🤔

File: public/app/features/dashboard-scene/scene/layouts-shared/paste.ts [hunk 2]
```diff
@@ -42,6 +44,23 @@ export interface PanelStore {
...
+  if (elements === null || typeof elements !== 'object') {
+    return false;
+  }
+  const gridItem = Reflect.get(obj, 'gridItem');
+  if (gridItem === null || typeof gridItem !== 'object') {
+    return false;
+  }
+  const kind = Reflect.get(gridItem, 'kind');
+  return kind === 'GridLayoutItem' || kind === 'AutoGridLayoutItem';
```
Comment (ifrost) [inline public/app/features/dashboard-scene/scene/layouts-shared/paste.ts:61]: Are there real life cases where this can be false?

**Review by ifrost — APPROVED** [review]

File: public/app/features/dashboard-scene/scene/layouts-shared/paste.ts [hunk 3]
```diff
@@ -79,15 +98,20 @@ export function getTabFromClipboard(scene: DashboardScene): TabItem {
 
 function getGridItemFromClipboard(scene: DashboardScene) {
   const jsonData = store.get(LS_PANEL_COPY_KEY);
-  // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
-  const { elements, gridItem }: PanelStore = JSON.parse(jsonData) as PanelStore;
+  const parsed: unknown = JSON.parse(jsonData);
```
Comment (grafakus) [inline public/app/features/dashboard-scene/scene/layouts-shared/paste.ts:101]: I'm wondering why `parse` is not within the try/catch?

**Review by grafakus — COMMENTED** [review]
In my tests, the pasted panel does not retain its original position on the custom grid.

File: public/app/features/dashboard-scene/scene/layouts-shared/paste.ts (hunk 1 above)
Comment (oscarkilhed) [reply public/app/features/dashboard-scene/scene/layouts-shared/paste.ts:52]: To avoid casting it using `as`, triggering lint issues and having to add an exception.

File: public/app/features/dashboard-scene/scene/layouts-shared/paste.ts (hunk 2 above)
Comment (oscarkilhed) [reply public/app/features/dashboard-scene/scene/layouts-shared/paste.ts:61]: hmm, not really

File: public/app/features/dashboard-scene/scene/layouts-shared/paste.ts (hunk 3 above)
Comment (oscarkilhed) [reply public/app/features/dashboard-scene/scene/layouts-shared/paste.ts:101]: That's a good point. I'll move it

**Comment by oscarkilhed** [comment]
> In my tests, the pasted panel does not retain its original position on the custom grid.

I don't think that's desirable. It's likely it will lead to very weird positioning if it works like that. I think that problem will be smaller once we can drag the paste item from the sidebar.
