### PR TITLE
Alerting: update rules POST API to validate query and condition only for rules that changed.

### LINKED ISSUE #53357: Can't edit/delete alert rules when data source deleted
**What happened**:
I removed a data source (InfluxDB 2) from Grafana then tried to edit/delete some alert rules with queries that used this data source. I found that the alert rules could not be edited or deleted, instead an error message appears: `Error: invalid rule specification at index [0]: failed to validate condition of alert rule System Load: invalid query C: data source not found: 000000001`. Query C does not exist in the GUI.

**What you expected to happen**:
I expected the alert rules to be able to be deleted regardless of data source availability.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a couple of alert rules with queries that use a specific data source.
2. Remove the data source from Grafana.
3. Try to edit or delete one of the alert rules. It will fail with the above error message.

**Anything else we need to know?**:
No.

**Environment**:
- Grafana version: 9.0.6
- Data source type & version: InfluxDB 2 and Prometheus
- OS Grafana is installed on: Alpine Linux 3.16
- User OS & Browser: macOS Monterey 12.5
- Grafana plugins: Renderer
- Others: Grafana running in a Docker container on Docker Engine 20.10.16

### LINKED ISSUE #64593: can't delete/modify alerts when datasource is deleted
**What happened**:

We set up a new Loki instance and wanted to delete the old datasource in Grafana and update the alerts. Deleting the datasource was successful, but we can't modify/delete and alerts as there's an error "datasource not found"

**What you expected to happen**:

Be able to modify the alerts with a new datasource or delete them

**How to reproduce it (as minimally and precisely as possible)**:

- start a grafana instance
  - e.g. in a docker container without persistence
    ```
    docker run -p 3000:3000 grafana/grafana
    ```
- log in and go into datasources
- Create a test data datasource
- Go into alerts
- Create an alert rule with test data datasource
- **Create another alert rule**
  - the bug only happens when you have more than 1 alert rule accessing the data source
- Go back into datasources
- Delete test datasource
- Create new test datasource (gets a new ID)
- Go back into alerts
- Try to modify or delete the alert
  - alert not found

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.3
- Data source type & version:
- OS Grafana is installed on: Kubernetes & locally on Docker
- User OS & Browser: Windows 10/Firefox
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What is this feature?**
This PR updates rule update API to validate queries of only rules in the group that are either created or updated and do not validate those that were not touched.

- In API model validations condition validation that uses expression service to validate queries is replaced by simpler validation that just makes sure that query refID is specified, and unique, and the rule condition refers to one of the queries.
- API request handler is updated to apply condition validation to only new and updated rules.

**Why do we need this feature?*
Currently, UI allows to update of only one alert rule but submits the entire group to the API. When the data source that is used by all of the alert rules in that group gets deleted, the user cannot update a single rule via UI because other rules in that group do not pass condition validation (because datasource UID is missing). This PR lets users fix rules one by one.

**Who is this feature for?**
For users that happened to delete a data source that is used by many alert rules.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/53357
Fixes https://github.com/grafana/grafana/issues/64593

**Special notes for your reviewer:**
There is still an edge case that is not covered. In Grafana Enterprise each user has granular permissions for data sources (i.e. permissions `datasources.query` in scope `datasources:uid:b36c3a8e-208d-4517-aea8-f1adf3193b84` whereas in OSS users (Editor role) have wildcard permissions (`datasources.query` in scope `datasources:uid:*`). 
In the case of granular permissions, the request will be rejected by access control because when data source is deleted all explicit permissions are deleted too. 
This edge case will be covered in follow up PR.

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by JacobsonMT — APPROVED** [review]
LGTM :rocket: 
Tested locally and working as expected :heavy_check_mark:

File: pkg/services/ngalert/api/api_ruler_validation.go [hunk 1]
```diff
@@ -117,6 +113,33 @@ func validateRuleNode(
...
+	if condition == "" {
+		return errors.New("condition cannot be empty")
+	}
+	if len(queries) == 0 {
+		return errors.New("no query\\expressions specified")
+	}
+	refIDs := make(map[string]int, len(queries))
+	for idx, query := range queries {
+		if query.RefID == "" {
+			return fmt.Errorf("refID is not specified for data query\\expression at index %d", idx)
```
Comment (grobinson-grafana) [inline pkg/services/ngalert/api/api_ruler_validation.go:126]:
```suggestion
			return fmt.Errorf("refID is not specified for data query/expression at index %d", idx)
```

File: pkg/services/ngalert/api/api_ruler_validation.go [hunk 2]
```diff
@@ -117,6 +113,33 @@ func validateRuleNode(
...
+		}
+		if usedIdx, ok := refIDs[query.RefID]; ok {
+			return fmt.Errorf("refID '%s' is already used by query\\expression at index %d", query.RefID, usedIdx)
```
Comment (grobinson-grafana) [inline pkg/services/ngalert/api/api_ruler_validation.go:129]:
```suggestion
			return fmt.Errorf("refID '%s' is already used by query/expression at index %d", query.RefID, usedIdx)
```

**Review by grobinson-grafana — APPROVED** [review]
