### PR TITLE
Alerting: Make folder filter clearable in Alert list panel

### LINKED ISSUE #49483: Alerting: alert list panel cannot clear selected folder filter
**What happened**:

I was trying to clear the folder filter selection but there is no way to clear it.

image

**What you expected to happen**:

The field should be clearable.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new Alert List panel
2. Add a folder filter
3. You can't clear it :(

### PR DESCRIPTION
**Pull request by peterholmberg**
**What this PR does / why we need it**:
The filter for folders in the Alert list panel was not clearable and once you set it there was no way of getting rid of it. 

**Which issue(s) this PR fixes**:

Fixes #49483

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/core/components/Select/FolderPicker.tsx [hunk 1]
```diff
@@ -130,13 +136,17 @@ export class FolderPicker extends PureComponent<Props, State> {
...
     if (newFolder.id > -1) {
       appEvents.emit(AppEvents.alertSuccess, ['Folder Created', 'OK']);
       folder = { value: newFolder.id, label: newFolder.title };
-      await this.onFolderChange(folder);
+      this.setState(
+        {
+          folder: newFolder,
+        },
+        () => this.props.onChange({ id: newFolder.value!, title: newFolder.label! })
+      );
```
Comment (peterholmberg) [inline public/app/core/components/Select/FolderPicker.tsx:149]: had to duplicate this so I wouldn't call `onFolderChange`. Could potentially be extracted to its own function to reduce the duplication.

**Review by gillesdemey — APPROVED** [review]
LGTM! 🚢
