### PR TITLE
SubMenu: Fix expanding sub menu items on touch devices

### LINKED ISSUE #93151: PanelChrome: Sub menu items not expanding on mobile devices
> There is no way for me to reach the "Get Help" buton on an Android phone. I
> 
> select the respective view but when I tap on "More..." the view resets and
> 
> there is nothing else to do.
> 
> 
> 
> The UI is no designed to handle viewpoints from mobile devices.

 _Originally posted by @r0ckarong in [#91857](https://github.com/grafana/grafana/issues/91857#issuecomment-2339054854)_

Using in browser device simulation:

https://github.com/user-attachments/assets/c060cfba-2fd2-4fe0-ad5a-d8ae46f8de08

### PR DESCRIPTION
**Pull request by yincongcyincong**
Fixes #93151
actually, i add mobile click event `onTouchStart`, and use event delegation to avoid menu is closed
please take a look @tskarhed @torkelo 
https://github.com/user-attachments/assets/4ce7541c-7c5d-4d35-93bd-18ff6e960829

### CODE REVIEW

File: packages/grafana-ui/src/components/Dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -73,7 +73,14 @@ export const Dropdown = React.memo(({ children, overlay, placement, offset, onVi
...
 
-  const onOverlayClicked = () => {
+  const onOverlayClicked = (event: React.MouseEvent<HTMLDivElement, MouseEvent>) => {
+    if (event.target instanceof HTMLDivElement || event.target instanceof HTMLSpanElement) {
+      const innerText = event.target.innerText
+      if (innerText.includes("More...")) {
+        return
+      }
+    }
+
```
Comment (ashharrison90) [inline packages/grafana-ui/src/components/Dropdown/Dropdown.tsx:83]: this is definitely too brittle i'm afraid 😬

**Review by ashharrison90 — CHANGES_REQUESTED** [review]
thanks for raising the issue and looking at this! 🙌 

think maybe a better approach would be to change the `onClick` in `MenuItem` to be something like:
```tsx
        onClick={(event) => {
          if (hasSubMenu) {
            event.preventDefault();
            event.stopPropagation();
          }
          onClick?.(event);
        }}
```
that should stop the click event propagating up to the overlay and closing the menu.


note: this isn't perfect, if the new submenu overflows the bounds of the mobile view it will resize the whole window. but it at least unblocks people from using these submenus. i think the changes needed to properly support mobile behaviour for the `Menu` and `MenuItem` elements are bigger than can be delivered in a community PR 😅

File: packages/grafana-ui/src/components/Dropdown/Dropdown.tsx (hunk 1 above)
Comment (yincongcyincong) [reply packages/grafana-ui/src/components/Dropdown/Dropdown.tsx:83]: thanks for your review, bro. i will modify it.

**Review by tskarhed — CHANGES_REQUESTED** [review]
This doesn't seem to quite work. We want all the use cases for the menu to support touch for submenu, so it is better if the stopPropagation is used in `MenuItem`. Try the approach that @ashharrison90 suggested!

**Comment by yincongcyincong** [comment]
> This doesn't seem to quite work. We want all the use cases for the menu to support touch for submenu, so it is better if the stopPropagation is used in `MenuItem`. Try the approach that @ashharrison90 suggested!

thanks for review. i have add `stopPropagation` at `MenuItem`. please take a look at lastest pr.

**Comment by yincongcyincong** [comment]
> > thanks for review. i have add `stopPropagation` at `MenuItem`. please take a look at lastest pr. https://github.com/grafana/grafana/pull/93208/files#diff-6274d9463d0536b679c48ba4551dbc84354b1a742e5d385f01d61fa494f27d75R78
> 
> The issue is still there: https://github.com/user-attachments/assets/158db928-5672-42db-b590-d61e2bdda399
> 
> You have added stopPropagation only for `onMore`, which doesn't account for `inspect` or any other use case.
> 
> Try adding the ash's requested changes here:
> 
> https://github.com/grafana/grafana/blob/5459d49bc09a3c5f181672beceab7a066f0b7101/packages/grafana-ui/src/components/Menu/MenuItem.tsx#L155

yep. actually this pr don't work on `inspect`. because `inspect` is very special. itself has a click event. if i modify the `click` event. it will result some other bug. like this.
image

**Comment by tskarhed** [comment]
> yep. actually this pr don't work on `inspect`. because `inspect` is very special. itself has a click event. if i modify the `click` event. it will result some other bug. like this. image


You're right. This functionality doesn't make sense. Not calling onClick when there is a submenu is more consistent behavior. Can you add those changes too?

**Comment by yincongcyincong** [comment]
> > yep. actually this pr don't work on `inspect`. because `inspect` is very special. itself has a click event. if i modify the `click` event. it will result some other bug. like this. image
> 
> You're right. This functionality doesn't make sense. Not calling onClick when there is a submenu is more consistent behavior. Can you add those changes too?

i'm pleasure contribute to grafana. i will give a new pr!

**Comment by tskarhed** [comment]
> i'm pleasure contribute to grafana. i will give a new pr!

It is okay if you do it in this PR, as it will make it easier to fix the other issue :)

**Comment by yincongcyincong** [comment]
> > i'm pleasure contribute to grafana. i will give a new pr!
> 
> It is okay if you do it in this PR, as it will make it easier to fix the other issue :)

ok, i will change this pr. thanks for your review.

**Comment by yincongcyincong** [comment]
@tskarhed bro, i delete `inspect` click function and add stopPropagation at menu that have submenu. please take a look again. thanks

https://github.com/user-attachments/assets/560ad305-84a0-41ad-a335-08a2c46a3d21

File: packages/grafana-ui/src/components/Menu/MenuItem.tsx [hunk 2]
```diff
@@ -108,7 +108,8 @@ export const MenuItem = React.memo(
         [styles.disabled]: disabled,
         [styles.destructive]: destructive && !disabled,
       },
-      className
+      className,
+      hasSubMenu ? 'hasSubmenu' : 'noSubmenu'
```
Comment (tskarhed) [inline packages/grafana-ui/src/components/Menu/MenuItem.tsx:112]: Instead of using a class as a selector, you could add `aria-haspopup="menu"` to the item that has a submenu and use that when selecting closest.

File: packages/grafana-ui/src/components/Menu/MenuItem.tsx [hunk 3]
```diff
@@ -152,10 +153,17 @@ export const MenuItem = React.memo(
...
+          if (hasSubMenu && !(event.target as HTMLElement).closest('.noSubmenu')) {
+            event.preventDefault();
+            event.stopPropagation();
+          }
+          onClick?.(event);
+        }}
         onMouseEnter={onMouseEnter}
         onMouseLeave={onMouseLeave}
         onKeyDown={handleKeys}
+        onTouchStart={onMouseEnter}
```
Comment (ashharrison90) [inline packages/grafana-ui/src/components/Menu/MenuItem.tsx:166]:
```suggestion
```

File: packages/grafana-ui/src/components/Menu/MenuItem.tsx (hunk 2 above)
Comment (ashharrison90) [inline packages/grafana-ui/src/components/Menu/MenuItem.tsx:112]:
```suggestion
```

File: packages/grafana-ui/src/components/Menu/MenuItem.tsx [hunk 4]
```diff
@@ -152,10 +153,17 @@ export const MenuItem = React.memo(
...
         rel={target === '_blank' ? 'noopener noreferrer' : undefined}
         href={url}
-        onClick={onClick}
+        onClick={(event) => {
+          if (hasSubMenu && !(event.target as HTMLElement).closest('.noSubmenu')) {
+            event.preventDefault();
+            event.stopPropagation();
+          }
+          onClick?.(event);
+        }}
```
Comment (ashharrison90) [inline packages/grafana-ui/src/components/Menu/MenuItem.tsx:162]:
```suggestion
        onClick={(event) => {
          if (hasSubMenu && !isSubMenuOpen) {
            event.preventDefault();
            event.stopPropagation();
          }
          onClick?.(event);
        }}
```

**Review by ashharrison90 — CHANGES_REQUESTED** [review]
think the changes in `Menu/MenuItem` can simplify down into just modifying the `onClick` - see suggestions. i _think_ this handles all cases 🙏 thanks again for tackling this 🙇

**Comment by yincongcyincong** [comment]
@tskarhed @ashharrison90 bros, thanks for your review. i gived a new pr.

**Review by ashharrison90 — APPROVED** [review]
think this looks great 👍 thanks for the contribution! 🙌

**Review by tskarhed — APPROVED** [review]
