### PR TITLE
Query Library: Fix Change DS during replace query loses query library context

### LINKED ISSUE #9265: adding kg (kilogramm) as unit
Hello,

I've realized a monitoring for my heating infrastructure with influxdb and grafana. Thank you for that.

However i miss the unig kg (kilogramms) for messuring weight.

is it possible to add that? i think it shouldn't be a big deal.

regards

### PR DESCRIPTION
**Pull request by axelavargas**
**What is this feature?**

When replacing a query using the Query Library, if the datasource differed from the current one and the user selected the query, we were incorrectly resetting the query state to empty. This happened because we dispatch `importQueries` in the `changeQueries` reducer, which includes specific logic for importing queries between datasources. When datasources were different,  we would fall back to empty queries. However, for Query Library replacements, we should skip this mechanism because we want to preserve the query exactly as it is stored in the library.

https://github.com/user-attachments/assets/3af45388-4458-49f9-88ae-5140b5d9bd37

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana-enterprise/issues/9265

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/query/components/QueryEditorRows.tsx [hunk 1]
```diff
@@ -66,14 +66,14 @@ export class QueryEditorRows extends PureComponent<Props> {
   onReplaceQuery(query: DataQuery, index: number) {
     const { queries, onQueriesChange, onUpdateDatasources, dsSettings } = this.props;
 
-    // Replace old query with new query
+    // Replace old query with new query, preserving the original refId
```
Comment (axelavargas) [inline public/app/features/query/components/QueryEditorRows.tsx:71]: This fix is required, if we don't preserve the `refId` the new query could have the same `refId` as an existing query and refIds should be unique

**Review by CollinFingar — APPROVED** [review]
LGTM! 🎉
