### PR TITLE
Transformations: Add documentation around new behavior of Calculate field

### LINKED ISSUE #103826: Transformations: Add field from calculation default alias being interpolated
### What happened?

The transformation "Add field from calculation" will let you create a field in the dataset from a variable and some sort of math function. The alias placeholder for this defaults to "[variable name] [math equation]", IE a variable called var1 that had 1 subtracted from it would be "var1 - 1" 

In 11.6, the variable name is interpolated, so the alias ends up being whatever the value of the variable is with the math equation. So for the above example, if var1 is 10, the alias is "10 - 1" 

When you build variable overrides on these fields, the field name breaks whenever the value changes from what it was when the override is created.

11.6 (https://play.grafana.org/d/behnv563zm7swa/variable-field-name-interpolation-bug?orgId=1&from=2025-04-01T08:07:25.849Z&to=2025-04-02T08:07:25.849Z&timezone=browser&var-number1=7&var-number2=10&tab=transformations)
Image

11.4
Image

### What did you expect to happen?

For the alias to remain what it was in 11.4, with the variable name instead of the variable value.

### Did this work before?

Yes, confirmed working as expected in 11.4 and broken in 11.6

### How do we reproduce it?

1. Create a variable with the textbox type, and have a default value
2. Use any dataset, like random walk
3. Use the "create field from calculation" transformation to subtract 1 from the variable set in 1. 
4. Note the name of the data starts with the default value, and changes when you change the value.

### Is the bug inside a dashboard panel?
<details><summary>Example dashboard</summary>

```json

{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 3330,
  "links": [],
  "panels": [
    {
      "datasource": {
        "type": "grafana-testdata-datasource",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green"
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "6 - 1"
            },
            "properties": []
          }
        ]
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "minVizHeight": 75,
        "minVizWidth": 75,
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "showThresholdLabels": false,
        "showThresholdMarkers": true,
        "sizing": "auto"
      },
      "pluginVersion": "12.0.0-85820.patch2-86140",
      "targets": [
        {
          "datasource": {
            "type": "grafana-testdata-datasource",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A"
        }
      ],
      "title": "New panel",
      "transformations": [
        {
          "id": "calculateField",
          "options": {
            "alias": "",
            "binary": {
              "left": {
                "matcher": {
                  "id": "byName",
                  "options": "$number1"
                }
              },
              "operator": "-",
              "right": {
                "fixed": "1"
              }
            },
            "mode": "binary",
            "reduce": {
              "reducer": "sum"
            }
          }
        },
        {
          "id": "calculateField",
          "options": {
            "binary": {
              "left": {
                "matcher": {
                  "id": "byName",
                  "options": "$number2"
                }
              },
              "operator": "-",
              "right": {
                "fixed": "1"
              }
            },
            "mode": "binary",
            "reduce": {
              "reducer": "sum"
            }
          }
        }
      ],
      "type": "gauge"
    }
  ],
  "preload": false,
  "schemaVersion": 41,
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "text": "7",
          "value": "7"
        },
        "name": "number1",
        "options": [
          {
            "selected": true,
            "text": "7",
            "value": "7"
          }
        ],
        "query": "7",
        "type": "textbox"
      },
      {
        "current": {
          "text": "10",
          "value": "10"
        },
        "name": "number2",
        "options": [
          {
            "selected": true,
            "text": "10",
            "value": "10"
          }
        ],
        "query": "10",
        "type": "textbox"
      }
    ]
  },
  "time": {
    "from": "2025-04-01T08:07:25.849Z",
    "to": "2025-04-02T08:07:25.849Z"
  },
  "timepicker": {},
  "timezone": "browser",
  "title": "Variable Field Name interpolation bug",
  "uid": "behnv563zm7swa",
  "version": 2
}

```
</details>

Related: https://github.com/grafana/support-escalations/issues/15675
Related: https://github.com/grafana/grafana/pull/100225

### Environment (with versions)?

Grafana: main
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by gelicia**
**What is this feature?**

In https://github.com/grafana/grafana/pull/100225 , we added the ability for all transformations to have variables interpolated before the visualization displays data. This had an unintentional side effect for the Add Field from Calculation transformation - the default alias when doing a binary calculation is to concatenate the two numbers and the operator to make the field name. If either or both of the numbers being calculated is a variable, the alias will include that variable. This then gets interpolated to the variable value and displayed with the variable value instead of the variable name. We end up with a field name that contains the value of the variable, which changes whenever the variable is changed.

Other features like field overrides that use a static field name will break with this.

We will require users needing this feature to not use the default alias for Add field from calculation and instead define it themselves. To make this more clear, I remove the default placeholder when this scenario exists. Although ideally it would be best to have the placeholder match the value in the visualization, we need the original value with the variable for saving, and the function to generate the placeholder does not have access to the template service. I don't really think it is worth to put a lot of code in for this edge case, but we can move forward with other solutions based on user feedback.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/support-escalations/issues/15675 
Fixes https://github.com/grafana/grafana/issues/103826

**Special notes for your reviewer:**

If we ever would like to fix this more comprehensively, the following two PRs will do so
- https://github.com/grafana/scenes/pull/1102
- https://github.com/grafana/grafana/pull/104016 

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/transformers/docs/content.ts [hunk 1]
```diff
@@ -67,6 +67,7 @@ Use this transformation to add a new field calculated from two other fields. Eac
   - **All number fields** - Set the left side of a **Binary operation** to apply the calculation to all number fields.
 - **As percentile** - If you select **Row index** mode, then the **As percentile** switch appears. This switch allows you to transform the row index as a percentage of the total number of rows.
 - **Alias** - (Optional) Enter the name of your new field. If you leave this blank, then the field will be named to match the calculation.
+> **Note:** If a variable will be used in this transformation, the default alias will be interpolated with the value of the variable. Please explicitly define an alias if you would like the alias to not be affected by variable changes.
```
Comment (imatwawana) [inline public/app/features/transformers/docs/content.ts:70]:
```suggestion
> **Note:** If a variable is used in this transformation, the default alias will be interpolated with the value of the variable. Explicitly define an alias if you want the alias to be unaffected by variable changes.
```

**Review by imatwawana — COMMENTED** [review]
Made some wording suggestions

File: public/app/features/transformers/docs/content.ts [hunk 2]
```diff
@@ -67,6 +67,7 @@ Use this transformation to add a new field calculated from two other fields. Eac
   - **All number fields** - Set the left side of a **Binary operation** to apply the calculation to all number fields.
 - **As percentile** - If you select **Row index** mode, then the **As percentile** switch appears. This switch allows you to transform the row index as a percentage of the total number of rows.
 - **Alias** - (Optional) Enter the name of your new field. If you leave this blank, then the field will be named to match the calculation.
+> **Note:** If a variable is used in this transformation, the default alias will be interpolated with the value of the variable. Explicitly define an alias if you want the alias to be unaffected by variable changes.
```
Comment (imatwawana) [inline public/app/features/transformers/docs/content.ts:70]:
```suggestion
> **Note:** If a variable is used in this transformation, the default alias will be interpolated with the value of the variable. If you want an alias to be unaffected by variable changes, explicitly define the alias.
```

**Review by imatwawana — APPROVED** [review]
Just a small nit for flow
