### PR TITLE
Explore/Loki: Fix handling of legacy log row context request

### LINKED ISSUE #21695: Loki: On loading context it does requests for both old and new API
**What happened**:
Seems like the RX.js switch does not work properly and it does both old and new API call https://github.com/grafana/grafana/blob/cf2cc713933599e7646416a56a665282c9d9e3bb/public/app/plugins/datasource/loki/datasource.ts#L491

Screenshot 2020-01-23 at 16 55 53

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Fixes a bug where getting a log row's context would make requests to both new and legacy endpoints.

**Which issue(s) this PR fixes**:
Closes #21695

### CODE REVIEW

File: public/app/plugins/datasource/loki/datasource.ts [hunk 1]
```diff
@@ -491,22 +491,26 @@ export class LokiDatasource extends DataSourceApi<LokiQuery, LokiOptions> {
...
-                  message: 'Error during context query. Please check JS console logs.',
-                  status: err.status,
-                  statusText: err.statusText,
-                };
-                throw error;
-              }),
-              map((res: { data: LokiLegacyStreamResponse }) => ({
-                data: res.data ? res.data.streams.map(stream => legacyLogStreamToDataFrame(stream, reverse)) : [],
-              }))
+            defer(() =>
```
Comment (aocenas) [inline public/app/plugins/datasource/loki/datasource.ts]: If I understand this correctly this is needed because the `_request` method creates a stream that is already hot (subscribed) and so request was already sent, right? So this will change it to cold one that will wait for actual subscription?

**Review by aocenas — APPROVED** [review]
lgtm
