### PR TITLE
TimeRange: Fixes updating time range from url and browser history

### LINKED ISSUE #48652: Dashboard: Time range is not updating from url properly
Changing time range and using browser back to change to previous time range is only working the first time (not really figured out when it's working and when it stops)

This means that data links that set time range on current dashboard is also not working.

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #48652

PR #45020 inverted the boolean parameter fromRouteUpdate in call to setTime but did not invert the place
where it was called.

Also included some code simplification as I was struggling understanding why we built a object with all
url params when the function getUrlRefresh only needed a single url property.

### CODE REVIEW

File: public/app/features/dashboard/services/TimeSrv.ts [hunk 1]
```diff
@@ -203,7 +198,7 @@ export class TimeSrv {
       if (from !== urlRange.from || to !== urlRange.to) {
         // issue update
         this.initTimeFromUrl();
-        this.setTime(this.time, true);
+        this.setTime(this.time, false);
```
Comment (torkelo) [inline public/app/features/dashboard/services/TimeSrv.ts:201]: this is the actual bugfix

**Review by joshhunt — APPROVED** [review]
Thanks!
