### PR TITLE
Alerting: fix response popover prompt when add notification channels

### LINKED ISSUE #18820: PageDuty test not working correctly
**What happened**: PagerDuty "send test" button is not working as expected

**What you expected to happen**: When i type wrong key, i expect to see some error message

**How to reproduce it (as minimally and precisely as possible)**:
create a new pagerduty channel
type wrong key
click on "send test"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.5
- Data source type & version:
- OS Grafana is installed on: docker image grafana/grafana:6.2.5
- User OS & Browser:
- Grafana plugins:
- Others:

image

### PR DESCRIPTION
**Pull request by lzdw**
**What this PR does / why we need it**:
 It returns success popover prompt  while input type wrong key  when add notification channels. 
**Which issue(s) this PR fixes**:
  PageDuty test not working correctly

Fixes #18820 

**Special notes for your reviewer**:

### CODE REVIEW

File: public/app/features/alerting/NotificationsEditCtrl.ts [hunk 1]
```diff
@@ -121,9 +121,7 @@ export class AlertNotificationEditCtrl {
       settings: this.model.settings,
     };
 
-    this.backendSrv.post(`/api/alert-notifications/test`, payload).then((res: any) => {
-      appEvents.emit('alert-success', ['Test notification sent', '']);
-    });
+    this.backendSrv.post(`/api/alert-notifications/test`, payload).then();
```
Comment (torkelo) [inline public/app/features/alerting/NotificationsEditCtrl.ts]: remove then()

**Review by torkelo — APPROVED** [review]
thanks for contributing!
