### PR TITLE
Variables: Fix so panels in expanded rows have correct variable values

### LINKED ISSUE #41127: Panel not refreshed when collapsed and variable value has changed
Grafana v7.5.11
Prometheus data source
Mozilla Firefox 93.0 (64-bit)

Using chained variables with "AlarmID" being the last variable in the chain. The "AlarmID" variable supports multi-choice and "All". Depending on the user's selection, zero, one or multiple "AlarmID" values can be selected. "All" is automatically selected if there is no "AlarmID" found for the user's selection. An alarm record panel repeats on the "AlarmID" variable and displays alarm details. Each alarm record panel can be collapsed.

The error is observed as follows:
- make a selection that results in at least 1 Alarm ID found and the alarm record panel being populated with the alarm details
image

- collapse the alarm record panel showing the alarm details
image

- change the selection such as no Alarm ID is found, i.e. "All" is automatically selected.
image

**- expand the alarm record "All" panel that still contains the values of the previous alarm record panel while "No data" would be expected.**
image

The error does not occur if the alarm record panel is kept expanded during the reselection, i.e. the alarm panel "All" is updated with "NoData":
- make a selection that results in at least 1 Alarm ID found and the alarm panel being populated with the alarm details
image

- change the selection such as no Alarm ID is found, i.e. "All" is automatically selected.
image

BTW is there a way to hide the alarm record panel "All" showing NoData if no "AlarmID" object is found based on the selection?

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
When we clean up all the repeats we forgot to clean up any collapsed panels. This PR fixes this.

**Which issue(s) this PR fixes**:
Fixes #41127

**Special notes for your reviewer**:
You need to read the issue carefully and I used the attached dashboard.json to repro and fix the issue (you'll need a prometheus data source like 
image

```json
{
  "__inputs": [
    {
      "name": "DS_PROMETHEUS_DEMO",
      "label": "Prometheus Demo",
      "description": "",
      "type": "datasource",
      "pluginId": "prometheus",
      "pluginName": "Prometheus"
    }
  ],
  "__elements": [],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "8.3.0-pre"
    },
    {
      "type": "datasource",
      "id": "prometheus",
      "name": "Prometheus",
      "version": "1.0.0"
    },
    {
      "type": "panel",
      "id": "stat",
      "name": "Stat",
      "version": ""
    },
    {
      "type": "panel",
      "id": "timeseries",
      "name": "Time series",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "iteration": 1637046364182,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "collapsed": false,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 4,
      "panels": [],
      "repeat": "job",
      "title": "Job $job",
      "type": "row"
    },
    {
      "datasource": "${DS_PROMETHEUS_DEMO}",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 1
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltip": {
          "mode": "single"
        }
      },
      "targets": [
        {
          "exemplar": true,
          "expr": "go_gc_duration_seconds{instance=~\"demo.robustperception.io:(${port:pipe})\", job=~\"(${job:pipe})\", quantile=\"1\"}",
          "interval": "",
          "legendFormat": "",
          "refId": "A"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    },
    {
      "datasource": "${DS_PROMETHEUS_DEMO}",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 12,
        "y": 1
      },
      "id": 5,
      "options": {
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "text": {},
        "textMode": "auto"
      },
      "pluginVersion": "8.3.0-pre",
      "targets": [
        {
          "exemplar": true,
          "expr": "go_gc_duration_seconds{job=~\"(${job:pipe})\", quantile=\"1\"}",
          "interval": "",
          "legendFormat": "",
          "refId": "A"
        }
      ],
      "title": "Panel Title",
      "type": "stat"
    }
  ],
  "schemaVersion": 33,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": true,
          "text": [
            "1337"
          ],
          "value": [
            "1337"
          ]
        },
        "hide": 0,
        "includeAll": true,
        "multi": true,
        "name": "port",
        "options": [
          {
            "selected": false,
            "text": "All",
            "value": "$__all"
          },
          {
            "selected": false,
            "text": "9090",
            "value": "9090"
          },
          {
            "selected": false,
            "text": "9091",
            "value": "9091"
          },
          {
            "selected": false,
            "text": "9093",
            "value": "9093"
          },
          {
            "selected": false,
            "text": "9100",
            "value": "9100"
          },
          {
            "selected": true,
            "text": "1337",
            "value": "1337"
          }
        ],
        "query": "9090,9091, 9093,9100,1337",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      },
      {
        "current": {},
        "datasource": "${DS_PROMETHEUS_DEMO}",
        "definition": "label_values(go_memstats_gc_cpu_fraction{instance=~\"demo.robustperception.io:(${port:pipe})\"}, job)",
        "hide": 0,
        "includeAll": true,
        "multi": true,
        "name": "job",
        "options": [],
        "query": {
          "query": "label_values(go_memstats_gc_cpu_fraction{instance=~\"demo.robustperception.io:(${port:pipe})\"}, job)",
          "refId": "StandardVariableQuery"
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Panel not refreshed when collapsed and variable value has changed #41127 Copy",
  "uid": "efKvXz5nkasd",
  "version": 1,
  "weekStart": ""
}
```

### CODE REVIEW

File: public/app/features/variables/inspect/utils.ts [hunk 1]
```diff
@@ -375,3 +379,16 @@ export const getVariableUsages = (variableId: string, usages: VariableUsageTree[
...
+
+  for (const panel of panels) {
+    result.push(panel);
+    if (panel.panels?.length) {
+      result.push(...flattenPanels(panel.panels.map((p: PanelModel) => new PanelModel(p))));
+    }
+  }
+
+  return result;
+}
```
Comment (hugohaggmark) [inline public/app/features/variables/inspect/utils.ts:394]: While debugging and fixing the issue I realised that the new panels impacted by variable logic was incorrect and didn't consider collapsed panels. This function will remedy this.

**Review by ashharrison90 — APPROVED** [review]
code looks great and works as expected 🙌
