### PR TITLE
Alerting: Fix synchronisation of group interval with form values

### LINKED ISSUE #95937: Alerting: changing evaluation group for alert rule is broken (v11.1+) - groups modified instead of rules
### What happened?

Hi guys!
I'm reanimating #93337 - sadly, could solidly reproduce only after issue being closed :(

So, the setup:
- you have an Alert Rule with evaluation group "5m", interval "5m"
- you have another group, say "1m", interval "1m"
- you want to assign a rule a new group, 1m instead of 5m

**The problem**:
When you pick the "1m" group and hit Save rule, "1m" group changes its interval to 5m.

**Repro notes**:
- go to alert rule edit page, by pasting direct link in browser address bar
- OR navigate from alert rule link in messenger (slack, telegram etc)
- OR navigate from "Alert Rules" Grafana page and make sure to refresh the page
In those conditions issue reproduces.

When you navigate from Alert Rules page without refreshing, all works as expected.

@tonypowa @tomratcliffe sorry for mentioning directly, please look into this 🙏 
Consider this a critical one, since my users almost always come to rules from alerts in messengers and face this problem.

### What did you expect to happen?

Choosing a new group in Alert rule & Save rule:

- SHOULD change this particular Alert rule's evaluation group
- SHOULD NOT modify chosen evaluation group (or any other group)

### Did this work before?

I reckon it was broken in 11.1+

### How do we reproduce it?

See repro notes above

### Is the bug inside a dashboard panel?

NO

### Environment (with versions)?

Grafana: 11.1+
OS: Any
Browser: Any

### Grafana platform?

I don't know

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by gillesdemey**
It looks like the group interval isn't always synchronized with the alert rule definition of the group when we are editing a alert rule directly without passing through the alert rule list view first.

The primary reason for this is because we are grabbing rule group information from the redux store but implicitly trusting that a corresponding redux actions has already been dispatched so we can grab the rule group information.

This assumption is false when we are directly editing a rule group.

This PR attempts to:

1. use the RTKQ endpoints to fetch rule group information.
2. refactors the prop drilling for the evaluation interval
3. synchronizes the evaluation interval selected in the dropdown with the value in the form.

Fixes https://github.com/grafana/grafana/issues/95937.

## Notes to reviewers

This code is very error-prone; I would welcome any (manual) testing or insights into what I may have overlooked.

### CODE REVIEW

File: public/app/features/alerting/unified/api/alertRuleApi.ts [hunk 1]
```diff
@@ -242,6 +242,7 @@ export const alertRuleApi = alertingApi.injectEndpoints({
         const { path, params } = rulerUrlBuilder(rulerConfig).namespace(namespace);
         return { url: path, params };
       },
+      providesTags: (_result, _error, { namespace }) => [{ type: 'RuleNamespace', id: namespace }],
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/api/alertRuleApi.ts:245]: This one is important; prior to this change any calls to `upsertRuleGroup` would not invalidate the `rulerNamespace` endpoints
