### PR TITLE
CI: Fix broken nightly builds

### LINKED ISSUE #67246: No 9.5.x branch "nightly" builds on dockerhub anymore?
I was expecting to find nightly" builds of 9.5.x branch on dockerhub here: https://hub.docker.com/r/grafana/grafana-oss-dev/tags?page=2 but they end 22 days ago (probably when the builds for 10.0.0 started).  What would be the way to get images for 9.5.0 to preview compatibility?

### PR DESCRIPTION
**Pull request by dsotirakis**
**What is this feature?**

Nightly builds are broken and stuck to the last `9.5.0` release.

This PR sorts the objects in a GCS bucket based on the `"generation"` field, which gives us back the timestamp based on which the artifacts were built. 

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/67246

**Special notes for your reviewer**:

Works as expected here: https://grafana.com/grafana/download/10.1.0-114444pre?edition=oss&platform=linux

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/build/gcloud/storage/gsutil.go [hunk 1]
```diff
@@ -366,11 +366,17 @@ func GetLatestMainBuild(ctx context.Context, bucket *storage.BucketHandle, path
 		return "", ErrorNilBucket
 	}
 
-	it := bucket.Objects(ctx, &storage.Query{
+	query := &storage.Query{
 		Prefix: path,
-	})
+	}
+	err := query.SetAttrSelection([]string{"Name", "Generation"})
```
Comment (zerok) [inline pkg/build/gcloud/storage/gsutil.go:372]: I think it would be better to use the `Updated` attribute here, then do filtering of the name in the first loop and fill everything into a slice to sort. This way IMO the code starting at line 388 would become much more readable 🙂

**Review by zerok — CHANGES_REQUESTED** [review]

File: pkg/build/gcloud/storage/gsutil.go (hunk 1 above)
Comment (dsotirakis) [reply pkg/build/gcloud/storage/gsutil.go:372]: Hm, why `Updated` is better than `Generation`? 🤔 
Grafana uploaded packages should be immutable I think? 

Also, about 
> filtering of the name in the first loop and fill everything into a slice to sort

I am doing the sort while I am constructing the slice so we won't have to go and run a sort on a slice afterwards. It's more performant IMO and that's why I wanted to go with it this way. I can always add some comments if it makes it easier for people to read and understand it.
Feel free to object though 😄

Comment (zerok) [reply pkg/build/gcloud/storage/gsutil.go:372]: `Updated` for unchanged items is the same as `Created` :)

But yes, manual sorting is also fine for me :)

**Review by zerok — APPROVED** [review]
