### PR TITLE
EmbedPanel: Add url sync and fix refresh

### LINKED ISSUE #98388: EmbedPanel: Fix refresh
Url sync is not working with scenes in `SoloPanelPage` and, therefore, refresh query param is not taken into account. 

Issue: https://github.com/grafana/grafana/issues/95315

### PR DESCRIPTION
**Pull request by juanicabanas**
**What is this feature?**

The embedded panel time picker refresh is not working with scenes. This activates the refresh picker and adds the URL sync for the component.
[Related issue](https://github.com/grafana/grafana/issues/95315)

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/98388

**Special notes for your reviewer:**

How can I add tests? I would like to mock the request call and, after N refresh seconds, assert `toHaveBeenCalledTimes(2)` but I'm struggling with many mocks 😅

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard-scene/solo/SoloPanelPage.tsx [hunk 1]
```diff
@@ -39,15 +40,26 @@ export function SoloPanelPage({ queryParams }: Props) {
...
+    </UrlSyncContextProvider>
+  );
 }
 
 export default SoloPanelPage;
 
 export function SoloPanelRenderer({ dashboard, panelId }: { dashboard: DashboardScene; panelId: string }) {
   const [panel, error] = useSoloPanel(dashboard, panelId);
+  const { controls } = dashboard.useState();
+  const { refreshPicker } = controls!.useState();
```
Comment (nmarrs) [inline public/app/features/dashboard-scene/solo/SoloPanelPage.tsx:55]: is there a way to avoid the need to use `!` here? This could result in a runtime error if `controls` is undefined for some reason 🤔

Comment (torkelo) [reply public/app/features/dashboard-scene/solo/SoloPanelPage.tsx:55]: why does the solo page need a refresh picker? I don't recall it ever having one, it's just the panel

Comment (ivanortegaalba) [reply public/app/features/dashboard-scene/solo/SoloPanelPage.tsx:55]: @torkelo It seems we need the scene object because the refresh picker is responsible for triggering the refresh and managing the interval for the next refresh. If the object isn't activated, the subsequent refresh won’t occur once the interval passes, and the URL parameter meant to set the refresh interval won’t function either.

Comment (juanicabanas) [reply public/app/features/dashboard-scene/solo/SoloPanelPage.tsx]: correct @ivanortegaalba . I don't know if there's any other way of activating the refresh, but I couldn't find anything in the panel context

Comment (torkelo) [reply public/app/features/dashboard-scene/solo/SoloPanelPage.tsx]: Ah, good reason to move the auto refresh logic out of the refresh picker.

**Review by nmarrs — APPROVED** [review]
LGTM
