### PR TITLE
Annotations: Fix rendering

### LINKED ISSUE #66625: Timeseries: Annotations not rendering properly
Findings from testing/debugging:

- Happens after annotations updates -> edit, add, delete
- Preview doesn't really previews unless you're refreshing the dashboard
- `AnnotationsPlugin` `useLayoutEffect` seem to have a stale list of current annotations as it gets called before `useEffect`?
- refresh is partially working

https://user-images.githubusercontent.com/88068998/232181448-62a29ecb-465f-4b3b-9466-cbbadf1f0bd5.mov

Consoles:

https://user-images.githubusercontent.com/88068998/234397206-9e35ef3a-5ad3-4f95-bde0-6325df4c7a59.mov

### PR DESCRIPTION
**Pull request by adela-almasan**
Before

https://user-images.githubusercontent.com/88068998/236911654-b4acfba8-2876-4109-993e-ed734fce7daf.mov

After

https://user-images.githubusercontent.com/88068998/236911691-25f56fbd-4f2f-4c4a-aa7a-aaff85a0f53f.mov

Fixes #66625 

**Special notes for your reviewer:**
Applies to Time Series, State Timeline and Candlestick.

**Testing steps:**

1. Create a dashboard and add visualizations: Time series, Candlestick, State timeline
2. Create 1-2 annotations 
2a. Check enabling/disabling annotations
2b. Check deleting an annotation
3. The annotations should correctly appear in panels (also in preview)

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin.tsx [hunk 1]
```diff
@@ -28,9 +29,16 @@ export const AnnotationsPlugin = ({ annotations, timeZone, config }: Annotations
...
     annotationsRef.current = views;
+
+    return () => {
+      // clear on unmount
+      annotationsRef.current = [];
+    };
   }, [annotations]);
 
   useLayoutEffect(() => {
+    getTimeSrv().refreshTimeModel();
```
Comment (ryantxu) [inline public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin.tsx:40]: We need to find a path that does not require this hack within the panel.

Comment (nmarrs) [inline public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin.tsx:40]: I tried testing this without this line and it seems to work as expected 🤔 Is this change necessary?


https://user-images.githubusercontent.com/22381771/236925439-7756e8a5-2ab0-4fc8-b22e-e3c0d0b376d5.mov

Comment (adela-almasan) [reply public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin.tsx:40]: This auto-refreshes the dashboard after adding/deleting a new annotation - otherwise you'd have to manually refresh from the button. Not sure if there were any complaints or if it's a requirement, seeing @ryantxu comment might be a good idea to address it separately..

Comment (ryantxu) [reply public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin.tsx]: yes -- that should be addressed at the dashboard level, not within the panel

**Review by ryantxu — APPROVED** [review]

**Review by nmarrs — APPROVED** [review]
✨
