### PR TITLE
Alerting: Convert 'Both' type Prometheus queries to 'Range' in migration

### LINKED ISSUE #70768: Alerting: Migration of Prometheus queries with both response types to Unified Alerting causes rule to start failing
### 
# What went wrong?

**What happened**:

In legacy alerting the query is taken from the panel query. In the panel query user can configure a request to Prometheus and select "both" for setting `type` (i.e. return instant and range results at the same time)

image

This setting is not supported in Unified Alerting 

image

However, this setting could come to unified alerting via migration and the rule will start failing with the following error:
```
frame has wrong type, expected NumericMulti but got \"timeseries-multi\"
```

Also, this happens when the panel's query contains expressions, then the query is executed by the server-side expression engine.

image

**What did you expect to happen**:
Migration should either fail or rule should be migrated correctly.

### 
# How do we reproduce it?

**Step 1**:

- Start Grafana with legacy alerting. Create a panel with Prometheus query and value "both" for setting `type`. Create a rule for that panel.

**Step 2**:

- Migrate to Unified Alerting

### 
# What Grafana version are you using?

Main

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by JacobsonMT**
**What is this feature?**

This feature updates the legacy migration to convert Prometheus queries of type `Both` to type `Range` and log a warning during migration.

**Why do we need this feature?**

Legacy supports alerting on Prometheus queries of type `Both`. This returns a mixed response with two dataframes (`TimeSeriesWide` & `NumericWide`), however Server Side Expressions and UA does not currently support this type of mixed response.

**Who is this feature for?**

Users of legacy alerting who will be migrating to UA.

**Which issue(s) does this PR fix?**:

Fixes #70768

**Special notes for your reviewer:**

There is the possibility to better support migrating this functionality by:
- Splitting the query into two: one for instant and one for range.
- Splitting the condition into two: one for each query, separated by OR.

However, relying on a `Both` query instead of multiple conditions to do this in legacy is likely
to be unintentional. In addition, this would require more robust operator precedence in classic conditions.
Given these reasons, we opt to convert them to `Range` queries and log a warning.

Please check that:
- [x] It works as expected from a user's perspective.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/services/sqlstore/migrations/ualert/alert_rule.go [hunk 1]
```diff
@@ -206,6 +207,56 @@ func fixGraphiteReferencedSubQueries(queryData map[string]json.RawMessage) map[s
...
+		if err := json.Unmarshal(instantRaw, &instant); err != nil {
+			// Nothing to do here, we can't parse the instant field.
+			return queryData
+		}
+	}
+	var rng bool
+	if rangeRaw, ok := queryData["range"]; ok {
+		if err := json.Unmarshal(rangeRaw, &rng); err != nil {
+			// Nothing to do here, we can't parse the instant field.
+			return queryData
```
Comment (yuri-tceretian) [inline pkg/services/sqlstore/migrations/ualert/alert_rule.go:248]: What do you think about leaving a debug\info message when we fail to parse the payload? I think it would help track down "unsuccessful" migrations. I would do Info level.

Comment (JacobsonMT) [reply pkg/services/sqlstore/migrations/ualert/alert_rule.go:248]: Makes sense, I can add a log to the unsuccessful unmarshalling of `datasource`, `instant` and `range`.

File: pkg/services/sqlstore/migrations/ualert/alert_rule.go [hunk 2]
```diff
@@ -206,6 +207,56 @@ func fixGraphiteReferencedSubQueries(queryData map[string]json.RawMessage) map[s
...
+	//	- Splitting the query into two: one for instant and one for range.
+	//  - Splitting the condition into two: one for each query, separated by OR.
+	// However, relying on a 'Both' query instead of multiple conditions to do this in legacy is likely
+	// to be unintentional. In addition, this would require more robust operator precedence in classic conditions.
+	// Given these reasons, we opt to convert them to range queries and log a warning.
+
+	// Check if the query is for Prometheus.
+	ds, ok := queryData["datasource"]
+	if !ok {
+		return queryData
```
Comment (yuri-tceretian) [inline pkg/services/sqlstore/migrations/ualert/alert_rule.go:222]: Let's leave a debug message if datasource field is not found. IIRC, this is an optional field on the SSE backend (and probably anywhere else) and it does not rely on it.

Comment (JacobsonMT) [reply pkg/services/sqlstore/migrations/ualert/alert_rule.go:222]: What information would the debug message show? If the `datasource` is not required, the only thing we know is that the rule could be prometheus, and could be `Both` and if it is, it won't convert correctly.

Comment (JacobsonMT) [reply pkg/services/sqlstore/migrations/ualert/alert_rule.go:222]: I could change up the order, try to find `instant` and `range` first. Then if they are both true and the `datasource` is missing, I can log a more informative message. WDYT?

**Review by yuri-tceretian — APPROVED** [review]
LGTM. Just suggestions about adding log messages. Tested. Works as expected.

File: pkg/services/sqlstore/migrations/ualert/alert_rule.go (hunk 2 above)
Comment (yuri-tceretian) [reply pkg/services/sqlstore/migrations/ualert/alert_rule.go:222]: > I could change up the order, try to find `instant` and `range` first. Then if they are both true and the `datasource` is missing, I can log a more informative message. WDYT?

I like the idea.

Comment (JacobsonMT) [reply pkg/services/sqlstore/migrations/ualert/alert_rule.go]: Fixed: b3bc9aadf91d9b7b6548728beaa8e1ab8fe1f143

**Review by yuri-tceretian — APPROVED** [review]
Nice 👍🏻

**Review by brendamuir — APPROVED** [review]

**Comment by brendamuir** [comment]
LGTM!

**Review by rwwiv — APPROVED** [review]
LGTM!
