### PR TITLE
Dashboards: Hide playlist edit functionality from viewers and snapshots link from unauthenticated users

### LINKED ISSUE #24987: Create new playlist button shouldn't be visible for user with viewer role on playlists page
**What happened**:
We have our **unauthenticated** user set to "Viewer" permission level. Within Grafana, the user is able to navigate into the left-side menu items. Relevant here are the routes `playlists` and `dashboard/snapshots`, where the user may view their respective contents. The issue is that the calls to the server either prevent them from creating a new / manipulating old playlists (for `playlists` route), or present them with an empty list of snapshots (for `dashboards/snapshots` route, even when existing snapshots are purely local snapshots). The `playlists` case is met with a "403 Forbidden" with response data `{message: "Permission denied"}`.
**What you expected to happen**:
Given that the **unauthenticated** user can view these areas, we expected them to be able to see the list of existing snapshots and/or be able to create/manipulate playlists.
**How to reproduce it (as minimally and precisely as possible)**:
Set **unauthenticated** user in custom.ini or default.ini to have the "Viewer" permission level by setting `org_role = Viewer`. Attempt to create a playlist or view existing snapshots from existing dashboards.
**Anything else we need to know?**:
n/a
**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Prometheus 2.13.1
- OS Grafana is installed on: Windows Server 2012
- User OS & Browser: Windows Server 2012 & Google Chrome 81.0.4404.122
- Grafana plugins:
- Others:

EDIT: Used the word "unauthorized" rather than "unauthenticated".

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
Viewing snapshots and creating playlists should not be available for users with "viewer" permissions. This PR:
- hides the snapshot nav link from unauthenticated viewers as the snapshot table is always blank.
- fixes a bug which caused snapshot to multiply in the UI if backend error'd.
- hides the playlists create / edit functionality from viewers
- if no playlists exist shows an info box stating the user doesn't have permission to create playlists

#### Viewer

| Without Playlists | With Playlists |
| --- | --- |
| Screenshot 2020-11-11 at 11 38 33 | Screenshot 2020-11-11 at 11 39 39 |

#### Admin / Editor

| Without Playlists | With Playlists |
| --- | --- |
| Screenshot 2020-11-11 at 11 38 13 | Screenshot 2020-11-11 at 11 39 22 |

**Which issue(s) this PR fixes**:

Fixes #24987

**Special notes for your reviewer**:

This is my first attempt at writing Go and I'm not overly familiar with the permissions levels or auth settings so input there would be really helpful. Should there be some sort of authorisation on the snapshots route as well as hiding it in the FE from "viewers"?

I'd also appreciate any feedback on the info message displayed for viewers when no playlists exist.

### CODE REVIEW

**Review by dprokop — APPROVED** [review]
I think this looks good code wise. I would like to confirm with @torkelo or maybe @marefr as they have more knowledge about permissions than I do.

File: pkg/api/index.go [hunk 1]
```diff
@@ -159,7 +159,15 @@ func (hs *HTTPServer) getNavTree(c *models.ReqContext, hasEditPerm bool) ([]*dto
 		{Text: "Divider", Divider: true, Id: "divider", HideFromTabs: true},
 		{Text: "Manage", Id: "manage-dashboards", Url: setting.AppSubUrl + "/dashboards", Icon: "sitemap"},
 		{Text: "Playlists", Id: "playlists", Url: setting.AppSubUrl + "/playlists", Icon: "presentation-play"},
-		{Text: "Snapshots", Id: "snapshots", Url: setting.AppSubUrl + "/dashboard/snapshots", Icon: "camera"},
+	}
+
+	if c.OrgRole != models.ROLE_VIEWER {
```
Comment (torkelo) [inline pkg/api/index.go:164]: this is better types has if c.HasRole(models.ROLE_EDITOR)   (will be true for admins as well)

**Review by torkelo — APPROVED** [review]
Looks good just one small issue

File: pkg/api/index.go (hunk 1 above)
Comment (marefr) [reply pkg/api/index.go:164]: I think this check need to consider admin/editor permission in folders/dashboards and should use `hasEditPerm` argument instead. But, needs to be verified.

Comment (torkelo) [reply pkg/api/index.go:164]: @marefr since viewers cannot create playlist today, I think we can wait with this until we make it possible to create playlists inside a folder

Comment (marefr) [reply pkg/api/index.go:164]: @torkelo yes that's true but this check is specifically for snapshots and not playlists, right? Platlist navitem is above.

Comment (torkelo) [reply pkg/api/index.go:164]: Ah , Sam your right . Mistook this item for playlists

Comment (marefr) [reply pkg/api/index.go:164]: @torkelo @jackw need some changes to move this PR forward I suppose?

**Review by marefr — DISMISSED** [review]
See comment regarding snapshots

File: pkg/api/index.go [hunk 2]
```diff
@@ -159,7 +159,15 @@ func (hs *HTTPServer) getNavTree(c *models.ReqContext, hasEditPerm bool) ([]*dto
 		{Text: "Divider", Divider: true, Id: "divider", HideFromTabs: true},
 		{Text: "Manage", Id: "manage-dashboards", Url: setting.AppSubUrl + "/dashboards", Icon: "sitemap"},
 		{Text: "Playlists", Id: "playlists", Url: setting.AppSubUrl + "/playlists", Icon: "presentation-play"},
-		{Text: "Snapshots", Id: "snapshots", Url: setting.AppSubUrl + "/dashboard/snapshots", Icon: "camera"},
+	}
+
+	if hasEditPerm {
```
Comment (marefr) [inline pkg/api/index.go:164]: I just tried with viewer role and I can actually create snapshots so don't think this. Sorry, but think snapshots shouldn't have any permission check here. WDYT?

Comment (marefr) [reply pkg/api/index.go:164]: When created a snapshot as viewer I can (in master) see the snapshots I've created:
image

Comment (jackw) [reply pkg/api/index.go:164]: Thanks for highlighting this Marcus. Turns out I misread the original issue which states the snapshot table is always empty for an unauthenticated user.

Based on this I'm guessing we either change the logic here to remove the snapshots menu item if there isn't a logged in user or revert this backend change and place a note in the frontend stating something like "you need to be logged in to see snapshots". What do you think?

Comment (marefr) [reply pkg/api/index.go:164]: Not authenticated - no snapshot menu item should work I think

**Review by wbrowne — COMMENTED** [review]
Go code looks good @jackw. Tested it out locally and works AFAICT. One thing I wanted to confirm was that with this change, it's still possible for a viewer to create and view their own snapshots (just not anyone else's)?

**Comment by jackw** [comment]
@wbrowne that's correct. I've not changed any logic around what a viewer can do with snapshots only that an unauthenticated user won't be presented with a nav link that leads to an empty table. The PR is a little misleading - I've updated the title and description so it hopefully makes more sense.

**Review by wbrowne — APPROVED** [review]
👍
