### PR TITLE
Auth Proxy: Resolve database is locked errors

### LINKED ISSUE #17247: Some panels not loading after updating to 6.2.0
**What happened**:
I updated our Grafana+Prometheus setup from 6.1.6 to 6.2.0. After the update, random panels on all dashboards are failing to load. Maybe 10% or so are affected and after reloading the dashboard or refreshing the browser tab other panels won't load.

The browser console is logging

```
Panel data error: 
Object { data: {…}, status: 500, headers: zn(), config: {…}, statusText: "Internal Server Error", xhrStatus: "complete" }
```

and the pod logs (we're running our stack in Kubernetes):

```
t=2019-05-23T08:35:24+0000 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=xrstf method=GET path=/api/datasources/proxy/1/api/v1/query_range status=500 remote_addr=10.156.0.68 time_ms=1 size=1723 referer="https://gibson.initech/d/mafnVWWZk/etcd-objects?orgId=1&refresh=30s"
```

It does not make a difference how complex the Prometheus queries are, even simple ones like `etcd_object_counts{resource=~"$resource"}` are failing. Prometheus is configured to be proxied through Grafana with no special authentication and Grafana and Prometheus talk via plain HTTP.

**What you expected to happen**:
I expected no particular changes, all of our dashboards should continue to work as before.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy Grafana 6.2.0 and Prometheus 2.9.2.
2. Create any kind of dashboard.
3. Observe random panels failing.

**Environment**:
- Grafana version: 6.2.0
- Data source type & version: Prometheus 2.9.2, proxy mode
- OS Grafana is installed on: GKE node
- User OS & Browser: Ubuntu, Firefox 67.0
- Grafana plugins: none
- Others: none

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
The change was originally made in #16950, but that change
was too big to cherry pick. That's why this PR needs to be merged into v6.2.x branch. 
This change adds a major database
performance improvement since the number of selects to fetch
a cached item is drastically decreased and by that removes
sqlite database is locked errors.

**After these changes:**
```
> ./run.sh -d 15m -v 20 -c auth_proxy_test -u http://127.0.0.1:10080/grafana

          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     output: -
     script: src/auth_proxy_test.js

    duration: 15m0s, iterations: -
         vus: 20,    max: 20

    done [==========================================================] 15m0s / 15m0s

    █ auth proxy test

      █ batch proxy requests

        ✓ response status is 200

    checks.....................: 100.00% ✓ 209400 ✗ 0
    data_received..............: 5.9 GB  6.6 MB/s
    data_sent..................: 65 MB   72 kB/s
    group_duration.............: avg=20.63s   min=1.64s  med=20.83s max=30.65s  p(90)=24.73s  p(95)=27.02s
    http_req_blocked...........: avg=542.55µs min=890ns  med=2.97µs max=1s      p(90)=4.36µs  p(95)=389.18µs
    http_req_connecting........: avg=506.42µs min=0s     med=0s     max=1s      p(90)=0s      p(95)=277.16µs
    http_req_duration..........: avg=1.32s    min=1.46ms med=1.36s  max=4.69s   p(90)=1.77s   p(95)=1.96s
    http_req_receiving.........: avg=53.28µs  min=9.69µs med=42µs   max=25.18ms p(90)=58.31µs p(95)=67.34µs
    http_req_sending...........: avg=56.55µs  min=6.55µs med=22.7µs max=55.69ms p(90)=35.69µs p(95)=67.24µs
    http_req_tls_handshaking...: avg=0s       min=0s     med=0s     max=0s      p(90)=0s      p(95)=0s
    http_req_waiting...........: avg=1.32s    min=1.4ms  med=1.36s  max=4.69s   p(90)=1.77s   p(95)=1.96s
    http_reqs..................: 212036  235.595539/s
    iteration_duration.........: avg=25.57s   min=5.64µs med=25.85s max=35.65s  p(90)=29.75s  p(95)=32.02s
    iterations.................: 690     0.766667/s
    vus........................: 20      min=20   max=20
    vus_max....................: 20      min=20   max=20
```

**Before these changes:**
```
> ./run.sh -d 15m -v 20 -c auth_proxy_test -u http://127.0.0.1:10080/grafana

          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     output: -
     script: src/auth_proxy_test.js

    duration: 15m0s, iterations: -
         vus: 20,    max: 20

    done [==========================================================] 1m49.1s / 15m0s

    █ auth proxy test

      █ batch proxy requests

        ✗ response status is 200
         ↳  45% — ✓ 5730 / ✗ 6870

    checks.....................: 45.47% ✓ 5730 ✗ 6870
    data_received..............: 177 MB 1.6 MB/s
    data_sent..................: 4.0 MB 36 kB/s
    group_duration.............: avg=40.84s   min=3.11s  med=39.27s  max=47.36s  p(90)=47.27s  p(95)=47.34s
    http_req_blocked...........: avg=6.15ms   min=850ns  med=3.01µs  max=1.06s   p(90)=5.63µs  p(95)=3.1ms
    http_req_connecting........: avg=6.12ms   min=0s     med=0s      max=1.01s   p(90)=0s      p(95)=2.85ms
    http_req_duration..........: avg=2.47s    min=2.68ms med=2.19s   max=11.37s  p(90)=5.09s   p(95)=6s
    http_req_receiving.........: avg=49.68µs  min=7.56µs med=39.66µs max=26.82ms p(90)=56.6µs  p(95)=64.96µs
    http_req_sending...........: avg=168.36µs min=6.01µs med=23.11µs max=30.52ms p(90)=39.18µs p(95)=108.77µs
    http_req_tls_handshaking...: avg=0s       min=0s     med=0s      max=0s      p(90)=0s      p(95)=0s
    http_req_waiting...........: avg=2.47s    min=2.58ms med=2.19s   max=11.37s  p(90)=5.09s   p(95)=6s
    http_reqs..................: 15142  138.748067/s
    iteration_duration.........: avg=44.78s   min=49ms   med=44.17s  max=52.38s  p(90)=52.26s  p(95)=52.34s
    iterations.................: 42     0.384851/s
    vus........................: 20     min=20 max=20
    vus_max....................: 20     min=20 max=20
```

**Which issue(s) this PR fixes**:
Fixes #17247

### CODE REVIEW

File: pkg/middleware/auth_proxy/auth_proxy.go [hunk 1]
```diff
@@ -298,21 +298,18 @@ func (auth *AuthProxy) GetSignedUser(userID int64) (*models.SignedInUser, *Error
...
 
 // Remember user in cache
-func (auth *AuthProxy) Remember() *Error {
+func (auth *AuthProxy) Remember(id int64) *Error {
+	key := auth.getKey()
 
-	// Make sure we do not rewrite the expiration time
-	if auth.InCache() {
+	// Check if user already in cache
+	userID, _ := auth.store.Get(key)
```
Comment (bergquist) [inline pkg/middleware/auth_proxy/auth_proxy.go]: I think we should handle this error. 
if its `err` and not `ErrItemNotFound` then we want to know about it.

**Comment by torkelo** [comment]
Looks great, nice use of k6.io again !

File: pkg/middleware/auth_proxy/auth_proxy.go (hunk 1 above)
Comment (marefr) [reply pkg/middleware/auth_proxy/auth_proxy.go]: Good point. Will fix

**Review by bergquist — APPROVED** [review]
