### PR TITLE
Dashboards: Fix autogrid selection / drag and drop

### LINKED ISSUE #113491: Fix: Bug with conditional rendering
Stuggling selecting a panel with conditional rendering (if I click panel header), [https://dynamicdashboards.grafana.net/d/togh2p6/simple-dash?orgId=1&from=now%2Fw&to=now%2Fw[…]r-Service=AB&var-Pod=AAA&showCategory=dash-grid-layout](https://dynamicdashboards.grafana.net/d/togh2p6/simple-dash?orgId=1&from=now%2Fw&to=now%2Fw&timezone=browser&var-Env=prod&var-Namespace=eu-west-us1&var-Service=AA&var-Service=AB&var-Pod=AAA&showCategory=dash-grid-layout)

Slack thread: https://raintank-corp.slack.com/archives/C081AF3S814/p1762348472106319

### PR DESCRIPTION
**Pull request by bfmatei**
**What is this feature?**

This PR brings two changes to drag and drop in the autogrid:
1. Fix selecting a panel that contains the conditional rendering overlay. This was caused by the `position: relative` CSS property brought by the conditional rendering CSS class.
2. Prevent re-calculating the order of the children when dragging a panel over the same panel.

**Why do we need this feature?**

Prepare for private preview.

**Who is this feature for?**

-

**Which issue(s) does this PR fix?**:

Fixes #113491 

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/dashboard-scene/scene/layout-auto-grid/AutoGridItemRenderer.tsx [hunk 1]
```diff
@@ -123,7 +123,10 @@ export function AutoGridItemRenderer({ model }: SceneComponentProps<AutoGridItem
 const getStyles = (theme: GrafanaTheme2) => ({
   wrapper: css({ width: '100%', height: '100%', position: 'relative' }),
   draggedWrapper: css({
-    position: 'absolute',
+    // Unfortunately, we need to enforce position absolute here. Otherwise, the position will be overwritten with
+    //  a relative position by .dashboard-visible-hidden-element
+    // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
+    position: 'absolute !important' as 'absolute',
```
Comment (grafakus) [inline public/app/features/dashboard-scene/scene/layout-auto-grid/AutoGridItemRenderer.tsx]: Instead of `!important`:

```css
'&.dashboard-visible-hidden-element': {
  position: 'absolute',
}
```

Would this be a good alternative?

File: public/app/features/dashboard-scene/scene/layout-auto-grid/AutoGridLayout.tsx [hunk 2]
```diff
@@ -196,7 +199,7 @@ export class AutoGridLayout extends SceneObjectBase<AutoGridLayoutState> impleme
       })
       ?.getAttribute('data-auto-grid-item-drop-target');
 
-    if (dropTargetGridItemKey) {
+    if (dropTargetGridItemKey && dropTargetGridItemKey !== this._lastDropTargetGridItemKey) {
```
Comment (grafakus) [inline public/app/features/dashboard-scene/scene/layout-auto-grid/AutoGridLayout.tsx:202]: While testing, I could not see under which conditions `dropTargetGridItemKey === this._lastDropTargetGridItemKey`. You mentioned dragging a panel over the same panel?

**Review by grafakus — APPROVED** [review]
Tested and it works well! I just left some questions and also noticed that, when clicking on the "Element is hidden..." tooltip, the whole parent is selected:

Image

But was not introduced in this PR. Is it intended?

File: public/app/features/dashboard-scene/scene/layout-auto-grid/AutoGridItemRenderer.tsx (hunk 1 above)
Comment (bfmatei) [reply public/app/features/dashboard-scene/scene/layout-auto-grid/AutoGridItemRenderer.tsx]: Thanks! Just tested and it seems to be working fine. Nice one dodging the !important workaround.

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/20035878385)
- Version: 12.4.0-20035878385
