### PR TITLE
release_publisher: Fix Debian/RPM naming

### LINKED ISSUE #25236: Last 7 nightly downloads for Linux not downloadable - 404 errors.
**What happened**:
If I go to the [Grafana downloads](https://grafana.com/grafana/download/7.1.0-1d66e55cpre?edition=oss&platform=linux) page and choose `Linux` The last (top) 7 nightly builds don't seem to be downloadable. At least for some platforms. For example:
`wget https://dl.grafana.com/oss/master/grafana_7.1.0-1d66e55cpre_amd64.deb`
`--2020-05-30 16:07:06--  https://dl.grafana.com/oss/master/grafana_7.1.0-1d66e55cpre_amd64.deb`
`Resolving dl.grafana.com (dl.grafana.com)... 151.101.18.217, 2a04:4e42:4::729`
`Connecting to dl.grafana.com (dl.grafana.com)|151.101.18.217|:443... connected.`
`HTTP request sent, awaiting response... 404 Not Found`
`2020-05-30 16:07:06 ERROR 404: Not Found.`

And on the download page where it should show the SHA key it says:
`Ubuntu and Debian(64 Bit)SHA256: <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: grafana-downloads/oss/master/grafana_7.1.0-1d6`

If I choose the 8th nightly (or lower) from the list all seems well. It's just the most recent 7 as of time of writing.

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Fix the scripts/build/release_publisher tool so naming of Debian and RPM packages is correct on publishing to grafana.com.

The reason the fix is needed is that the build pipeline tool fixed naming of pre-release Debian/RPM packages, so the pre-release component gets prefixed with `~` instead of `-`, f.ex. _grafana_7.1.0~aed17029pre_amd64.deb_. The scripts/build/release_publisher tool was out of sync with this.

**Which issue(s) this PR fixes**:
Fixes #25236.

### CODE REVIEW

File: scripts/build/release_publisher/publisher_test.go [hunk 1]
```diff
@@ -72,10 +75,12 @@ func TestPreparingReleaseFromRemote(t *testing.T) {
 			expectedBeta:    false,
 			expectedStable:  false,
 			expectedArch:    "armv6",
-			expectedOs:      "linux",
-			expectedURL:     "https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-rpi-5.4.0-pre1asdf_armhf.deb",
+			expectedOs:      "deb",
```
Comment (marefr) [inline scripts/build/release_publisher/publisher_test.go:78]: Don't understand this change. Was it a "test mistake" using linux earlier?

**Review by marefr — APPROVED** [review]
LGTM, but see comment

File: scripts/build/release_publisher/publisher_test.go (hunk 1 above)
Comment (aknuds1) [reply scripts/build/release_publisher/publisher_test.go:78]: @marefr Well noticed, but yeah I do think it must've been a mistake in the test before. If you look at the corresponding [production configuration](https://github.com/grafana/grafana/blob/master/scripts/build/release_publisher/publisher.go#L132), the OS is "deb" (which in this codebase corresponds to the package type).
