### PR TITLE
CloudWatch: Add macro for resolving period in SEARCH expressions

### LINKED ISSUE #60434: CloudWatch: Add support for period auto macro
**What happened**:

In a CloudWatch search expression, one needs to define a period for each expression.
``` SEARCH('{"AWS/EC2","InstanceId"} MetricName="CPUUtilization"', 'Average', 60)```

The period is similar to Grafana's `interval` variable, but it's also different in the sense that it needs to be a multiple of 60. For that reason, the interval variable cannot be used directly.

It's very limiting that there's no way of automatically adjusting the period to the selected time range. Only way now is to define a template variable for period, but that does not automatically adjust to the current resolution in the Graph. I therefore propose we introduce a `$__period_auto` macro that adjust the CloudWatch period to the time range, using the same algorithm as we currently use for the period field when it's set to `auto`. 

For reference, see [this](https://github.com/grafana/grafana/issues/20262) issue. 

cc @taleena

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by sunker**
**What is this feature?**

This PR adds a `$__period_auto` macro for resolving a suitable CloudWatch period based on the current time range in Grafana. The macro is using the same algorithm for resolving CloudWatch period as we currently use when the _Period_ field is set to `auto`.   

period-auto-macro

**Why do we need this feature?**

For user's of the CloudWatch plugin, it's very limiting that there's no way of automatically adjusting the period to the selected time range. Only way now is to define a template variable for period, but that does not automatically adjust to the current resolution in the Graph. I therefore propose we introduce a `$__period_auto` macro that adjust the CloudWatch period to the time range, using the same algorithm as we currently use for the period field when it's set to `auto`. 

**Who is this feature for?**

Users of the plugins

**Which issue(s) does this PR fix?**:

Fixes #60434
Related to https://github.com/grafana/grafana/issues/20262

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/tsdb/cloudwatch/models/cloudwatch_query.go [hunk 1]
```diff
@@ -264,6 +266,8 @@ func ParseMetricDataQueries(dataQueries []backend.DataQuery, startTime time.Time
 			return nil, &QueryError{Err: err, RefID: refId}
 		}
 
+		cwQuery.applyMacros(startTime, endTime)
+
 		cwQuery.migrateLegacyQuery(mdq, dynamicLabelsEnabled)
```
Comment (sunker) [inline pkg/tsdb/cloudwatch/models/cloudwatch_query.go:271]: Intuitively feels wrong that migrations are applied after `validateAndSetDefaults` and `applyMacros`, but that's something to look into another time.

**Comment by onitake** [comment]
I think this would be very helpful and cover what's asked for in #20262 .

Two formal questions:
1. Does it make sense to call this `$__period__auto`? Isn't this the same as `$__interval` (or `$interval`), as used elsewhere in Grafana?
2. Will this also work with the query builder (not only custom queries)?

**Comment by sunker** [comment]
> * Does it make sense to call this `$__period__auto`? Isn't this the same as `$__interval` (or `$interval`), as used elsewhere in Grafana?

They are similar in a way, but not the same. The grafana interval is calculated based on the current time range and number of pixels available in the panel. The `$__period__auto` macro also takes the time range into consideration, but the CloudWatch period needs to be a multiple of 60 so it will adjust for that. Also, it makes an attempt to take CloudWatch metric [retentions](https://aws.amazon.com/about-aws/whats-new/2016/11/cloudwatch-extends-metrics-retention-and-new-user-interface/) into consideration when calculating the period. 

_In this example, the $interval is 2 seconds, and that is not a valid CloudWatch period._ 
Screenshot from 2022-12-16 14-03-24

> * Will this also work with the query builder (not only custom queries)?

The exact same period calculation as the one used for the `$__period__auto` macro is already applied when you leave the _Period_ field in the editor empty (or specify `auto`), so the same behavior already exists there.

**Comment by onitake** [comment]
> The exact same period calculation as the one used for the `$__period__auto` macro is already applied when you leave the _Period_ field in the editor empty (or specify `auto`), so the same behavior already exists there.

Sorry, what I actually meant, was: Is this also available in metric math?

Since I'm having trouble with the `PERIOD()` function, I'd like to have the period provided by Grafana instead, so I can use it as a simple scalar value.

File: pkg/tsdb/cloudwatch/models/cloudwatch_query.go [hunk 2]
```diff
@@ -227,7 +228,7 @@ type metricsDataQuery struct {
 
 // ParseMetricDataQueries decodes the metric data queries json, validates, sets default values and returns an array of CloudWatchQueries.
 // The CloudWatchQuery has a 1 to 1 mapping to a query editor row
-func ParseMetricDataQueries(dataQueries []backend.DataQuery, startTime time.Time, endTime time.Time, dynamicLabelsEnabled,
+func ParseMetricDataQueries(dataQueries []backend.DataQuery, startTime time.Time, endTime time.Time, logger log.Logger, dynamicLabelsEnabled,
```
Comment (iwysiu) [inline pkg/tsdb/cloudwatch/models/cloudwatch_query.go:231]: is there a reason for the logger changes?

File: pkg/tsdb/cloudwatch/models/cloudwatch_query_test.go [hunk 3]
```diff
@@ -11,10 +11,12 @@ import (
 	"github.com/stretchr/testify/assert"
 	"github.com/stretchr/testify/require"
 
-	"github.com/grafana/grafana/pkg/infra/log/logtest"
+	log "github.com/grafana/grafana/pkg/infra/log"
 	"github.com/grafana/grafana/pkg/tsdb/cloudwatch/utils"
 )
 
+var logger = log.New("testCloudWatchLogger")
```
Comment (iwysiu) [inline pkg/tsdb/cloudwatch/models/cloudwatch_query_test.go:18]: Is there a reason that we're using an actual logger instead of `&logtest.Fake{}`? Does this logger print out to anywhere?

File: pkg/tsdb/cloudwatch/models/cloudwatch_query_test.go [hunk 4]
```diff
@@ -1187,11 +1189,82 @@ func Test_ParseMetricDataQueries_account_Id(t *testing.T) {
...
 }
+
+func Test_ParseMetricDataQueries_ApplyMacros(t *testing.T) {
+	t.Run("should expand $__period_auto macro when a metric search code query is used", func(t *testing.T) {
+		testCases := []struct {
+			startTime      time.Time
+			expectedPeriod string
+		}{
+			{
+				startTime:      time.Now().Add(-2 * time.Hour),
```
Comment (iwysiu) [inline pkg/tsdb/cloudwatch/models/cloudwatch_query_test.go:1208]: I don't think it's going to matter that much in this case, but it may be better practice in general to get `time.Now()` once, so the difference between the starttime and endtime is more consistent.

**Review by iwysiu — APPROVED** [review]
Overall, looks good with a couple questions!

File: docs/sources/datasources/aws-cloudwatch/query-editor/index.md [hunk 5]
```diff
@@ -92,6 +92,10 @@ For example, to apply arithmetic operations to a metric, apply a unique string i
 
 > **Note:** If you use the expression field to reference another query, like `queryA * 2`, you can't create an alert rule based on that query.
 
+##### Period macro
+
+If you're using a CloudWatch [`SEARCH`](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/search-expression-syntax.html) expression, you may want to use the `$__period_auto` macro rather than specifying a period explicitly. The `$__period_auto` macro will resolve to a [CloudWatch period](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html) that is suitable for the choosen time range. It will use the same algorithm for calculating period as is used when the **Period** field is set to `auto`. Read more about that [here](#period).
```
Comment (sarahzinger) [inline docs/sources/datasources/aws-cloudwatch/query-editor/index.md:97]: Sorry I'm not sure I follow this bit: `It will use the same algorithm for calculating period as is used when the **Period** field is set to "auto"`

What is the difference between the Period field described in the read more section and this one? This one is used in search expressions and the other one is used in other queries?

File: pkg/tsdb/cloudwatch/models/cloudwatch_query.go [hunk 6]
```diff
@@ -63,7 +64,7 @@ type CloudWatchQuery struct {
 	AccountId         *string
 }
 
-func (q *CloudWatchQuery) GetGMDAPIMode(logger log.Logger) GMDApiMode {
+func (q *CloudWatchQuery) GetGMDAPIMode() GMDApiMode {
```
Comment (sarahzinger) [inline pkg/tsdb/cloudwatch/models/cloudwatch_query.go:67]: A bit unrelated to this pr but can we document what gmd stands for here?

File: pkg/tsdb/cloudwatch/models/cloudwatch_query.go [hunk 7]
```diff
@@ -390,21 +400,27 @@ func getLabel(query metricsDataQuery, dynamicLabelsEnabled bool) string {
 	return result
 }
 
+func calculatePeriodBasedOnTimeRange(startTime, endTime time.Time) int {
+	deltaInSeconds := endTime.Sub(startTime).Seconds()
+	periods := getRetainedPeriods(time.Since(startTime))
+	datapoints := int(math.Ceil(deltaInSeconds / 2000))
```
Comment (sarahzinger) [inline pkg/tsdb/cloudwatch/models/cloudwatch_query.go:406]: what does 2000 represent here? maybe it can be a named variable or done in some kind of math to indicate what's happening (example 7 * 24 for hours in a week)

File: public/app/plugins/datasource/cloudwatch/metric-math/completion/CompletionItemProvider.ts [hunk 8]
```diff
@@ -99,6 +99,11 @@ export class MetricMathCompletionItemProvider extends CompletionItemProvider {
           break;
 
         case SuggestionKind.Period:
+          addSuggestion('$__period_auto', {
+            kind: monaco.languages.CompletionItemKind.Variable,
+            sortText: 'a',
+            detail: 'Will be expanded to period in seconds matching the time range.',
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/metric-math/completion/CompletionItemProvider.ts:105]: .maybe "sets period dynamically to adjust to selected time range" not sure

File: public/app/plugins/datasource/cloudwatch/metric-math/language.ts [hunk 9]
```diff
@@ -92,6 +93,7 @@ export const language: monacoType.languages.IMonarchLanguage = {
     variables: [
       [/\$[a-zA-Z0-9-_]+/, 'variable'], // $ followed by any letter/number we assume could be grafana template variable
     ],
+    macros: [[/\$__[a-zA-Z0-9-_]+/, 'type']],
```
Comment (sarahzinger) [inline public/app/plugins/datasource/cloudwatch/metric-math/language.ts:96]: maybe  a comment, my brain was like "oh this is exactly the same as above and then I realized no there are underscores lol

**Review by sarahzinger — APPROVED** [review]
Looks good, couple of suggestions/questions on my end

File: docs/sources/datasources/aws-cloudwatch/query-editor/index.md (hunk 5 above)
Comment (onitake) [reply docs/sources/datasources/aws-cloudwatch/query-editor/index.md:97]: I believe this relates to the way that CloudWatch calculates the period, when you don't specify it explicitly, or specify it as "auto".

File: pkg/tsdb/cloudwatch/models/cloudwatch_query.go (hunk 2 above)
Comment (sunker) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go:231]: Just think it makes more sense for it to be attached to the instance rather than a specific method.

File: pkg/tsdb/cloudwatch/models/cloudwatch_query_test.go (hunk 3 above)
Comment (sunker) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query_test.go:18]: No reason, just copied from another test file. I'll use `&logtest.Fake{}` instead.

File: pkg/tsdb/cloudwatch/models/cloudwatch_query.go (hunk 6 above)
Comment (sunker) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go:67]: I'm renaming this method to `GetGetMetricDataAPIMode`

File: pkg/tsdb/cloudwatch/models/cloudwatch_query.go (hunk 7 above)
Comment (sunker) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go:406]: I would if I could, but I have no idea what it represents. Would guess it's just a random quotient that seemed suitable at the time this was implemented..?

**Comment by sunker** [comment]
@grafana/docs-squad can you take a look at the docs changes in this PR?

File: pkg/tsdb/cloudwatch/models/cloudwatch_query.go (hunk 2 above)
Comment (onitake) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go]: TBH, I'd generally refrain from binding loggers to any kind of program logic.
Loggers should either be centrally managed, or local to a module. Definitely not local to an object or function.
Is this a pattern that's used in other places in the Grafana source code?

Comment (onitake) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go]: Here's an example for a package-local logger: https://github.com/grafana/grafana/blob/main/pkg/services/secrets/migrator/migrator.go#L152
But I've also found object-local loggers elsewhere, so there's probably no general guideline on what should be used in Grafana.

File: pkg/tsdb/cloudwatch/models/cloudwatch_query.go (hunk 7 above)
Comment (onitake) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go:412]: So this number comes from CloudWatch?
I would at least add a link to a reference in this case.

File: pkg/tsdb/cloudwatch/models/cloudwatch_query.go (hunk 2 above)
Comment (sunker) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go]: Yeah I agree with you on this, but for tracing reasons this logger is attached to the [query data execution flow](https://github.com/grafana/grafana/blob/90185bea007086ada4bddb70bc934d10579241c2/pkg/tsdb/cloudwatch/cloudwatch.go#L151), so it cannot be package or module specific. 

Making it object specific is not ideal, but I also don't want it to be passed to a utility function like it would have an affect on the output. Anyway, I think this will become better soon very soon when we've refactored the [query data execution flow](https://github.com/grafana/grafana/issues/57146). Then, we can call the `RequestContextFactoryFunc` from anywhere within the package to retrieve the logger rather than injecting it like this.

File: pkg/tsdb/cloudwatch/models/cloudwatch_query.go (hunk 7 above)
Comment (sunker) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go:412]: No I did not say it comes from CloudWatch.

Comment (onitake) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go:412]: Ah sorry... I misunderstood. I thought "seemed suitable at the time it was implemented" referred to a decision made by an AWS engineer during CloudWatch development.
So, where does the logic behind this line of code come from?

**Review by kevinwcyu — APPROVED** [review]

File: pkg/tsdb/cloudwatch/models/cloudwatch_query.go (hunk 7 above)
Comment (sunker) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go:412]: Don't know actually.

**Comment by onitake** [comment]
Somewhat unrelated, but still relevant:
https://github.com/grafana/grafana/blob/10e7e82c74e2ddbac37c2c2d7eb87bd13300b509/pkg/tsdb/cloudwatch/models/cloudwatch_query.go#L444 -> I think it would be better to link to the API docs and not an AWS news article here: https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html

File: pkg/tsdb/cloudwatch/models/cloudwatch_query.go (hunk 7 above)
Comment (onitake) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go:412]: Let's try to trace it, then.
1. https://github.com/grafana/grafana/pull/57624/files#diff-870ca91de9ab6432ae4482009df9ce24421b3a4aeb334e94a61bb13285a865baR384
2. https://github.com/grafana/grafana/pull/21659/files#diff-85dc934cbe9964e970a0c2745dffcf54bec2f1e61d505534fcb7f437207d900dR72
3. https://github.com/grafana/grafana/commit/d40b66f1c170d0927382854f9b36351937c05757#diff-85dc934cbe9964e970a0c2745dffcf54bec2f1e61d505534fcb7f437207d900dR72
So, this was introduced by https://github.com/grafana/grafana/pull/21471 .

Comment (onitake) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go:412]: The documentation says:
> * Data points with a period of less than 60 seconds are available for 3 hours. These data points are high-resolution metrics and are available only for custom metrics that have been defined with a StorageResolution of 1.
> * Data points with a period of 60 seconds (1-minute) are available for 15 days.
> * Data points with a period of 300 seconds (5-minute) are available for 63 days.
> * Data points with a period of 3600 seconds (1 hour) are available for 455 days (15 months).

The original code was (abbreviated):
```go
func closest(array []int, num int) int {
	if num <= array[0] -> return array[0]
	if num >= array[len(array)-1]  -> return array[len(array)-1]
	minDiff := array[len(array)-1]
	var closest int
	for _, value := range array {
		var m = int(math.Abs(float64(num - value)))
		if m <= minDiff  -> minDiff = m; closest = value
	}
	return closest
}
periods := []int{60, 300, 900, 3600, 21600}
period = closest(periods, int(math.Ceil(deltaInSeconds/2000)))
```

I deduced that "closeness" to two consecutive numbers in the periods table (i.e. `min|dTs/2000-p[i]|`) means a break at each midpoint. So, this would result in the following numbers:
```
dTs <= 2000*(60+300)/2=36,000=10h -> p=60
10h < dTs <= 2000*(300+900)/2=1,200,000=13.89d -> p=300
13.89d < dTs <= 2000*(900+3600)/2=52.08d -> p=900
52.08d < dTs <= 2000*(3600+21600)/2=25,200,000=291.67d -> p=3600
291.67d < dTs <= 2000*21600=43,200,000=500d -> p=21600
```

That still doesn't explain where this magic number comes from, though. I can only guess that it is some sort of hard-coded number of data points.

But the only "magic" number that is really relevant, is 10,800: That's the maximum number of data points a GetMetricData query will return. The only relation to this number I can find is `2000*21,600=10,800,000=10,800/2`, but that could be a red herring.

Comment (sunker) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go:412]: Thanks for the thorough investigation! 

Interesting that this was initially introduced in a PR made by me - I have no memory of this whatsoever. My guess is that the number `2000` is used in the CloudWatch console, so we were recommended to use the same in Grafana. But I'm not sure. 

There's no point in asking the GetMetricData api for more data points than the graph has pixels for. My guess is that the number `2000` is an assumption made for available pixels in the graph. However, the query data api already provides a `MaxDataPoints` field for each query, so we should probably use that instead of `2000`. That would be a breaking change though as it may change result set for potentially many user, so that's something that we need to save for a major release in that case.

Comment (piequi) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go:412]: > what does 2000 represent here?

image

https://docs.aws.amazon.com/grafana/latest/userguide/CloudWatch-using-the-metric-search.html#cloudwatch-period

My 2 cent...

Comment (sunker) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go:412]: @piequi that paragraph is copied from the cloudwatch data source documentation at grafana.com. 

The question here was why ‘2000’ was added to the equation.

Comment (onitake) [reply pkg/tsdb/cloudwatch/models/cloudwatch_query.go:412]: Sorry for bringing this up and making your past catch up with you. :smile: 
I suppose it's ok to leave this as it is for now, as it's unrelated to the PR. The current algorithm looks better than the original version, in that it no longer breaks at the midpoints instead of the boundaries (given that my interpretation was correct).
But it may not be a bad idea to revisit this at some point.
