### PR TITLE
Flamegraph: Add nice empty state for dashboard panel

### LINKED ISSUE #66803: FlameGraph: Panel crashes on initialization
## What happened:
When adding a new panel type and selecting the Flame Graph, the panel crashes.

## What you expected to happen:
The panel not to crash and instead show a more useful message in the panel body potentially?

## How to reproduce it (as minimally and precisely as possible):
1) Add a new panel
2) Set panel type to Flame Graph

Screenshot 2023-04-18 at 10 46 43 AM

### PR DESCRIPTION
**Pull request by aocenas**
Fixes: https://github.com/grafana/grafana/issues/66803

Screenshot 2023-07-31 at 10 58 00

Shows also a nice-ish message saying what fields are missing or have the wrong type.

### CODE REVIEW

File: public/app/plugins/panel/flamegraph/components/FlameGraph/dataTransform.ts [hunk 1]
```diff
@@ -85,15 +130,17 @@ export class FlameGraphDataContainer {
 
   constructor(data: DataFrame, theme: GrafanaTheme2 = createTheme()) {
     this.data = data;
+
+    const wrongFields = checkFields(data);
+    if (wrongFields) {
+      throw new Error('Malformed dataFrame: value, level and label and self fields of correct type are required.');
```
Comment (fabrizio-grafana) [inline public/app/plugins/panel/flamegraph/components/FlameGraph/dataTransform.ts:136]: What about using `getMessageFromWrongFields` here?

**Review by fabrizio-grafana — APPROVED** [review]
GTM 🚀
