### PR TITLE
Auth: Resolve isGrafanaAdmin for debug logging

### LINKED ISSUE #70840: Authentication: ldap mapping of grafana_admin fails since v10
### 
# What went wrong?

**What happened**:
When logging in via ldap account, all groups are mapped to orgs as expected except grafana_admin.
log output with activated ldap.debug shows:
..... OrgRoles:map[1:Viewer 2:Admin 3:Admin 4:Admin 6:Admin 7:Admin 8:Admin 9:Admin 10:Admin] **IsGrafanaAdmin:0xc003766a69** IsDisabled:false SkipTeamSync:false}]

**What did you expect to happen**:

**IsGrafanaAdmin:true**

**Additional info**:
the same group is mapped several times in the same toml file. It also results in Org Admin for 2, 3, 4, 6, 7, 8, 9, 10 - which works.

### 
# How do we reproduce it?

**Step 1**:

- Setup grafana openLDAP mapping

**Step 2**:

- define a grafana_admin group in ldap and map it in ldap.toml

**Step 3**:

- try to login

### 
# What Grafana version are you using?

10.0.1

### 
### Is the bug inside a Dashboard Panel?

no

### Grafana Platform?

Docker

### User's OS?

RHEL7

### User's Browser?

Firefox 102.12.0esr (64-Bit)

### Is this a Regression?

Yes

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by Jguer**
**What is this feature?**

- Show isGrafanaAdmin value in debug logs instead of pointer address 

**Why do we need this feature?**

Fixes https://github.com/grafana/grafana/issues/70840

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/services/login/model.go [hunk 1]
```diff
@@ -67,7 +67,12 @@ type ExternalUserInfo struct {
 }
 
 func (e *ExternalUserInfo) String() string {
-	return fmt.Sprintf("%+v", *e)
+	isGrafanaAdmin := "nil"
+	if e.IsGrafanaAdmin != nil {
+		isGrafanaAdmin = fmt.Sprintf("%v", *e.IsGrafanaAdmin)
+	}
+	return fmt.Sprintf("OAuthToken: %+v, AuthModule: %v, AuthId: %v, UserId: %v, Email: %v, Login: %v, Name: %v, Groups: %v, OrgRoles: %v, IsGrafanaAdmin: %v, IsDisabled: %v, SkipTeamSync: %v",
```
Comment (linoman) [inline pkg/services/login/model.go:74]: This might be kinda hard to read. I don't have a better solution but I'd prefer a line per value, rather than a really long string.

**Review by linoman — APPROVED** [review]
Great job!

File: pkg/services/login/model.go (hunk 1 above)
Comment (Jguer) [reply pkg/services/login/model.go:74]: This is for the logs, where new lines are discouraged, is that what you meant?

Comment (linoman) [reply pkg/services/login/model.go:74]: Yes! I'm aware it's used for a log. I stand by my comment. Keep in mind I don't have a better solution, so feel free to merge as is.

**Review by IevaVasiljeva — APPROVED** [review]
