### PR TITLE
Explore metrics: Use state for variables to fix labels loading bug

### LINKED ISSUE #89911: bug: overview label list is misleadingly empty
It seems the use of the `getLabelOptions` function does not always ensure an up-to-date list of label options as used and rendered by the `MetricOverviewScene`.

[Brendan] exploring the bug where metadata is loading slowly and the browser gets stuck on messages saying it is not available. The metadata is present and the messages will switch from “none” or general missing data if you click around in a random fashion. These are async calls to the data source using Scenes. When the calls return, the browser should be updated. It is not. This seems to be because the components are static and treat the calls as synchronous. Changing the calls to async and waiting breaks Explore Metrics. Not sure of a solution without refactoring Scenes. Maybe an event driven re-render

**Matt Stewart**:
> any idea why we would be seeing "unable to fetch labels" here? It is like this for most metrics it seems with the metrics explorer. Not enough data?
> actually, looks like if I jump around with data trails and stuff, eventually they appear. but if I start with a fresh metric exploration the labels dont show

Image

Image

See:
- https://raintank-corp.slack.com/archives/C0630AYC4SY/p1717772199344919
- https://raintank-corp.slack.com/archives/C0630AYC4SY/p1717772319312599
- https://github.com/grafana/grafana/pull/89352

### PR DESCRIPTION
**Pull request by bohandley**
**What is this feature?**
Bug fix for labels not loading correctly due to state issues 

**Why do we need this feature?**

Labels can be slow to load for customers with a significant amount of labels. Using `variable.useState()` to access labels through the scenes queryVariable is a fix for this. 

**Who is this feature for?**

Explore metrics users with lots of labels 

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/89911

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/trails/ActionTabs/MetricOverviewScene.tsx [hunk 1]
```diff
@@ -67,26 +64,27 @@ export class MetricOverviewScene extends SceneObjectBase<MetricOverviewSceneStat
   public static Component = ({ model }: SceneComponentProps<MetricOverviewScene>) => {
     const { metadata, metadataLoading } = model.useState();
     const variable = model.getVariable();
-    const { loading: labelsLoading } = variable.useState();
-    const labelOptions = getLabelOptions(model, variable).filter((l) => l.value !== ALL_VARIABLE_VALUE);
+    const { loading: labelsLoading, options: labelOptions } = variable.useState();
+
+    const help = metadata?.help;
+    const type = metadata?.type;
+    const unit = metadata?.unit;
```
Comment (itsmylife) [inline public/app/features/trails/ActionTabs/MetricOverviewScene.tsx:71]: Since the metadata is an optional value, we might end up having those as `undefined`

Comment (bohandley) [reply public/app/features/trails/ActionTabs/MetricOverviewScene.tsx]: Not changing the metadata part in this PR, but good point

**Review by itsmylife — APPROVED** [review]

File: public/app/features/trails/ActionTabs/MetricOverviewScene.tsx [hunk 2]
```diff
@@ -67,29 +65,54 @@ export class MetricOverviewScene extends SceneObjectBase<MetricOverviewSceneStat
   public static Component = ({ model }: SceneComponentProps<MetricOverviewScene>) => {
     const { metadata, metadataLoading } = model.useState();
     const variable = model.getVariable();
-    const { loading: labelsLoading } = variable.useState();
-    const labelOptions = getLabelOptions(model, variable).filter((l) => l.value !== ALL_VARIABLE_VALUE);
+    const { loading: labelsLoading, options: labelOptions } = variable.useState();
```
Comment (darrenjaneczek) [inline public/app/features/trails/ActionTabs/MetricOverviewScene.tsx:68]: Ah nice. It was right there and ready for us to use!

**Review by darrenjaneczek — APPROVED** [review]

File: .betterer.results [hunk 3]
```diff
@@ -5499,15 +5499,6 @@ exports[`better eslint`] = {
...
     ],
-    "public/app/features/trails/ActionTabs/MetricOverviewScene.tsx:5381": [
-      [0, 0, 0, "No untranslated strings. Wrap text with <Trans />", "0"],
-      [0, 0, 0, "No untranslated strings. Wrap text with <Trans />", "1"],
-      [0, 0, 0, "No untranslated strings. Wrap text with <Trans />", "2"],
-      [0, 0, 0, "No untranslated strings. Wrap text with <Trans />", "3"],
-      [0, 0, 0, "No untranslated strings. Wrap text with <Trans />", "4"],
-      [0, 0, 0, "No untranslated strings. Wrap text with <Trans />", "5"],
-      [0, 0, 0, "No untranslated strings. Wrap text with <Trans />", "6"]
-    ],
```
Comment (darrenjaneczek) [inline .betterer.results:5510]: Thanks for cleaning this.

Comment (bohandley) [reply .betterer.results:5479]: It is now an enforced check for linting, haha, I had to! But good to know and then there was another drone check that required me to run `make i18n-extract` to update the files for translations.
