### PR TITLE
Auth: Show invite button if disable login form is set to false

### LINKED ISSUE #69878: Invite button is not visible in Grafana Cloud
### 
# What went wrong?

**What happened**:

 With Grafana >10 the Invite button in Grafana instance (e.g. `mygrafana.grafana.net`) is not visible anymore, despite `disable_login_form` is set to `false`. 

This makes it not possible to invite users to the grafana.net instance outside of the Grafana Cloud portal. A typical scenario for this use case is when Grafana administrators don't want for invited users to have any visibility in the stack level, and they want users just to be able to view dashboards with given Grafana instance.

**What did you expect to happen**:

 The Invite button should be visible when `disable_login_form` is set to `false` and upon invitation the invited users should be able to register and log in to my grafana.net instance.

### 
# How do we reproduce it?

**Step 1**:

- Create a Grafana Cloud account/stack with any of the plans (e.g. `mygrafana.grafana.net`)

**Step 2**:

- Set `disable_login_form` to `false` for the Grafana instance to enable login form for external users.

**Step 3**:

- Navigate to mygrafana.grafana.net/admin/users and you won't be able to see the Invite button

### 
# What Grafana version are you using?

Grafana v10.0.1-cloud.1.d4a15e66 (33f806237f)

### 
### Is the bug inside a Dashboard Panel?

_No response_

### Grafana Platform?

I use Grafana Cloud

### User's OS?

_No response_

### User's Browser?

Google Chrome

### Is this a Regression?

Yes

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by IevaVasiljeva**
**What is this feature?**

https://github.com/grafana/grafana/pull/67031 and https://github.com/grafana/grafana/pull/68991 change the logic of when the `invite` button is shown, which lead the button from being hidden from cloud instances where it was actually used. This PR extends the logic again to show the `invite` button if:
1) the instance is not a cloud instance;
2) the instance has `disable_login_form` set to false (so new basic auth users can be added).

**Why do we need this feature?**

To reenable the `invite` button for cloud instances where it was being used.

**Who is this feature for?**

Cloud users.

**Which issue(s) does this PR fix?**:

Fixes #69878

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by Jguer — APPROVED** [review]

File: public/app/features/users/UsersActionBar.tsx [hunk 1]
```diff
@@ -49,8 +49,10 @@ export const UsersActionBarUnconnected = ({
     { label: `Pending Invites (${pendingInvitesCount})`, value: 'invites' },
   ];
   const canAddToOrg: boolean = contextSrv.hasAccess(AccessControlAction.OrgUsersAdd, canInvite);
-  // Hide Invite button in case users are managed externally
-  const showInviteButton: boolean = canAddToOrg && !config.externalUserMngInfo;
+  // Show invite button in the following cases:
+  // 1) the instance is not a hosted Grafana instance (!config.externalUserMngInfo)
+  // 2) new basic auth users can be created for this instance (!config.disableLoginForm).
+  const showInviteButton: boolean = canAddToOrg && (!config.disableLoginForm || !config.externalUserMngInfo);
```
Comment (mgyongyosi) [inline public/app/features/users/UsersActionBar.tsx:55]: Nit: 
```suggestion
  const showInviteButton: boolean = canAddToOrg && !(config.disableLoginForm && config.externalUserMngInfo);
```

**Review by mgyongyosi — APPROVED** [review]

**Comment by IevaVasiljeva** [comment]
> @IevaVasiljeva I'm not sure, but I think this should be backported to 10.0.x as well and the milestone should be 10.1.x.

You're very right @mgyongyosi, thanks for pointing it out!
