### PR TITLE
Auth: Write the redirect cookie if denied - do not write a blank redirect

### LINKED ISSUE #56827: Redirect after login doesn't work for Explore
**What happened**:

Kapture 2022-10-12 at 15 12 53

Navigating to the Explore view after a login takes you to the homepage.

**What you expected to happen**:

After logging in, you should be redirected to the correct path.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open Explore view and build any query.
2. Copy the URL.
3. Log out of Grafana.
4. Navigate to the copied URL

**Anything else we need to know?**: n/a

**Environment**:
- Grafana version: 9.1.7
- Data source type & version: n/a
- OS Grafana is installed on: MacOS
- User OS & Browser: MacOS & Safari/Chrome
- Grafana plugins: n/a
- Others: n/a

### PR DESCRIPTION
**Pull request by gelicia**
**What this PR does / why we need it**:
As written, no routes that had used the access control authorize function would redirect properly after login. This was caused by the cookie not being written in the first place, and then, after being redirected to '/', it was overwritten when the normal auth middleware kicked in and overwritten to be '/'.

This writes the redirect even if access was denied, and then does not save a redirect cookie if it is only the root directory. 

**Which issue(s) this PR fixes**:
Fixes #56827

**Special notes for your reviewer**:
This is not my normal area of expertise so feel free to make any recommendations or modifications necessary.

Any paths using the authorize function here will run into the bug https://github.com/grafana/grafana/blob/main/pkg/api/api.go#L83

### CODE REVIEW

File: pkg/services/accesscontrol/middleware.go [hunk 1]
```diff
@@ -84,6 +84,7 @@ func deny(c *models.ReqContext, evaluator Evaluator, err error) {
 
 	if !c.IsApiRequest() {
 		// TODO(emil): I'd like to show a message after this redirect, not sure how that can be done?
+		writeRedirectCookie(c)
```
Comment (sakjur) [inline pkg/services/accesscontrol/middleware.go:87]: This is not the same function, since this lies in a different package, is that intentional?

Comment (gelicia) [reply pkg/services/accesscontrol/middleware.go:87]: @sakjur sorry if this is a misunderstanding, but would calling this not call the function here https://github.com/grafana/grafana/blob/main/pkg/services/accesscontrol/middleware.go#L130 ?

Comment (sakjur) [reply pkg/services/accesscontrol/middleware.go:87]: It would, but you've modified the function that was copied from in `pkg/middleware/auth.go` rather than that function? It's possible that's what you want, but I'm asking about it since you're modifying `pkg/middleware.writeRedirectCookie` and adding a dependency on `pkg/services/accesscontrol.writeRedirectCookie` in the same PR and I want to double-check so that that's right.

Comment (gelicia) [reply pkg/services/accesscontrol/middleware.go:87]: Yes, for this bug both the access control middeware and normal Auth middleware kick in. The AC middleware is what   gets accessed for authorization, but then redirects to the root directory. The normal auth middleware then kicks in to that route, and sets the cookie to just the /

Comment (sakjur) [reply pkg/services/accesscontrol/middleware.go:87]: Ah, I think I understand.

Looks good then, let me just take a quick look and approve :+1:

File: pkg/middleware/auth.go [hunk 2]
```diff
@@ -64,10 +64,15 @@ func writeRedirectCookie(c *models.ReqContext) {
 		redirectTo = setting.AppSubUrl + c.Req.RequestURI
 	}
 
-	// remove any forceLogin=true params
-	redirectTo = removeForceLoginParams(redirectTo)
+	if redirectTo != "/" {
```
Comment (sakjur) [inline pkg/middleware/auth.go:67]: Nit: If you invert this clause to a guard clause with something like

```suggestion
	if redirectTo == "/" {
		return
	}
```

(not directly applicable, GitHub didn't let me propose the suggestion on the whole block)
we'd keep the main flow left-aligned.

File: pkg/middleware/auth.go [hunk 3]
```diff
@@ -64,10 +64,15 @@ func writeRedirectCookie(c *models.ReqContext) {
...
+		if setting.AppSubUrl != "" && !strings.HasPrefix(redirectTo, setting.AppSubUrl) {
+			redirectTo = setting.AppSubUrl + c.Req.RequestURI
+		}
```
Comment (sakjur) [inline pkg/middleware/auth.go:70]: Address this before merging: This looks like a repeat of lines 63-65, I don't think you need these lines?

```suggestion
```

**Review by sakjur — APPROVED** [review]
:+1:

Could be merged as-is, though I have a nit-pick about preferring guard clauses and a question about some code appearing to appear twice in comments that'd be nice if you could take a look at.

File: pkg/middleware/auth.go (hunk 3 above)
Comment (gelicia) [reply pkg/middleware/auth.go]: Oops! I missed this, thank you!

File: pkg/middleware/auth.go (hunk 2 above)
Comment (gelicia) [reply pkg/middleware/auth.go]: Sounds good!

**Review by sakjur — APPROVED** [review]
