### PR TITLE
MixedDatasource: don't filter hidden queries before sending to datasources

### LINKED ISSUE #18801: MixedDatasource: Handle hidden queries internally
**What happened**: Following upgrade from v6.1.6 to 6.3.3 a query that sums disabled queries has stopped working on mixed datasource graphs.

**What you expected to happen**: The sum should be visible as Query C even when Query A/B are disabled.

**How to reproduce it (as minimally and precisely as possible)**:
Mixed Datasource graph:
Query A - Data from Graphite (Disabled)
Query B - Data from Graphite (Disabled)
Query C - sumSeries(#A, #B)
Query D - Data from Prometheus

In v6.1.6 this would give a graph which displays the values of Query C and Query D, in v6.3.3 this graph only displays Query D, unless Query A/B are enabled, which would then give Query C the sum of the enabled queries.

When this is performed on a single Datasource graph on v6.3.3 the functionality still exists and the value of Query C will be displayed even when Query A/B are disabled.

**Anything else we need to know?**: Possibly related to https://github.com/grafana/grafana/pull/16409 ?

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: Mixed Graphite/Prometheus
- OS Grafana is installed on: CentOS7
- User OS & Browser: macOS Mojave, Vivaldi
- Grafana plugins: Graph, Graphite, Prometheus
- Others: n/a

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes: #18801

let the underlying datasources handle mixed

### CODE REVIEW

File: public/app/plugins/datasource/mixed/datasource.ts [hunk 1]
```diff
@@ -17,17 +17,13 @@ class MixedDatasource extends DataSourceApi<DataQuery> {
...
-      });
-
-      if (filtered.length === 0) {
+      if (targets.length === 0) {
         return { data: [] };
       }
 
       return this.datasourceSrv.get(dsName).then(ds => {
         const opt = _.cloneDeep(options);
-        opt.targets = filtered;
```
Comment (torkelo) [inline public/app/plugins/datasource/mixed/datasource.ts]: Should this not filter if hiddenQueries is false?

**Review by torkelo — APPROVED** [review]
Think internally it needs to check the meta hiddenQueries flag and filter accordingly , but not sure

File: public/app/plugins/datasource/mixed/datasource.ts (hunk 1 above)
Comment (ryantxu) [reply public/app/plugins/datasource/mixed/datasource.ts]: yup -- updated
