### PR TITLE
CloudWatch: Improve metric label parsing

### LINKED ISSUE #79809: Cloudwatch: Dimension Labels Inconsistencies Bug with wildcard selected, Match Exact turned off, and an expression used
To Reproduce:

- Create a Cloudwatch Metrics query with 3 dimensions selected, and the third one is *
- Add an expression (I think any expression)
- Ensure match exact is turned off. 
- Notice that the label for the third wildcard dimension is inaccurate. I believe it is taking it from a different dimension possibility (so in the case below AutoScaling is the first Service option when the resource dimension is removed)

Screenshot 2023-12-21 at 12 40 57 PM

Another example:
Screenshot 2023-12-21 at 1 01 46 PM

It's not much better when match exact is turned off:
Screenshot 2023-12-21 at 12 46 35 PM
seems to create some sort of uid? 

Confusingly this only happens sometimes. So far we've had reports of this happening with Kafka Metrics when the dimensions of Cluster Name, Consumer Group, and Topic is selected, and I've been able to reproduce it those in the screenshot above as well, but many times I can not reproduce it. Sometimes I'll select 3 and one of the labels is missing?

Screenshot 2023-12-21 at 12 59 52 PM

Other times it seems to work just fine?
Screenshot 2023-12-21 at 1 04 59 PM

I'm not entirely clear what's going on, but I see we've had [challenges](https://github.com/grafana/grafana/issues/72172) with this in the past, so perhaps there's one more edge case here we've missed? 

Grafana Version: main (I was on commit 315dd757678282d9a621301ebb341d1943df57b4)

### PR DESCRIPTION
**Pull request by iwysiu**
**What is this feature?**
Updates parsing labels from queries. Instead of checking for dimension values in the default returned label, make AWS format it for us in a way where we can consistently parse the label values out without searching for substrings.

**Why do we need this feature?**
We have some issues with incorrectly returned labels from Cloudwatch, because we were just searching for known dimension values as substrings in the returned label from AWS, which just takes all of the dimensions with multiple values and concatenates them with spaces. This becomes an issue if any of the dimension values are substrings of the other dimension values, as it may set a label to one value when it means another.

**Who is this feature for?**
This feature is for anyone who uses CloudWatch query labels for expressions or alerting.

**Which issue(s) does this PR fix?**:

Fixes #79809

**Special notes for your reviewer:**
I wasn't sure if it was necessary, but I added it behind a feature flag because its sort of a big logic change.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/tsdb/cloudwatch/metric_data_query_builder.go [hunk 1]
```diff
@@ -9,10 +10,13 @@ import (
 	"github.com/aws/aws-sdk-go/aws"
 	"github.com/aws/aws-sdk-go/service/cloudwatch"
 
+	"github.com/grafana/grafana/pkg/tsdb/cloudwatch/features"
 	"github.com/grafana/grafana/pkg/tsdb/cloudwatch/models"
 )
 
-func (e *cloudWatchExecutor) buildMetricDataQuery(query *models.CloudWatchQuery) (*cloudwatch.MetricDataQuery, error) {
+const keySeparator = "|&|"
```
Comment (iwysiu) [inline pkg/tsdb/cloudwatch/metric_data_query_builder.go:17]: Do we think this is a distinct enough separator? I didn't add spaces because it makes the parsing simpler for when there are no results and ${LABEL} is "" (AWS removes the leading space)

File: pkg/tsdb/cloudwatch/response_parser.go [hunk 2]
```diff
@@ -87,6 +89,30 @@ func aggregateResponse(getMetricDataOutputs []*cloudwatch.GetMetricDataOutput) m
...
 
+func parseLabels(cloudwatchLabel string, query *models.CloudWatchQuery) (string, data.Labels) {
+	dims := make([]string, 0, len(query.Dimensions))
+	for k := range query.Dimensions {
+		dims = append(dims, k)
+	}
+	sort.Strings(dims)
+
+	splitLabels := strings.Split(cloudwatchLabel, keySeparator)
+	labelsIndex := 1
```
Comment (kevinwcyu) [inline pkg/tsdb/cloudwatch/response_parser.go:100]: nit: could you add a note here for why `labelsIndex` starts at 1. It wasn't clear to me at first until I traced it back to `buildSearchExpressionLabel`.

**Review by kevinwcyu — APPROVED** [review]

File: pkg/tsdb/cloudwatch/response_parser_test.go [hunk 3]
```diff
@@ -266,7 +279,7 @@ func Test_buildDataFrames_uses_response_label_as_frame_name(t *testing.T) {
 			Metrics: []*cloudwatch.MetricDataResult{
 				{
 					Id:    aws.String("lb3"),
-					Label: aws.String("some label"),
+					Label: aws.String("some label|&|--"),
```
[the remark this answers is not in the document]
Comment (iwysiu) [reply pkg/tsdb/cloudwatch/response_parser_test.go:283]: Added a comment. That's what cloudwatch uses for a value in a label when there are no results.

File: pkg/tsdb/cloudwatch/response_parser.go (hunk 2 above)
Comment (iwysiu) [reply pkg/tsdb/cloudwatch/response_parser.go:101]: done!

**Comment by iwysiu** [comment]
(Sorry about the force push, one of the files on the main was interfering with doing a merge commit)
