### PR TITLE
BarChart: fix gradient fill orientation when horizontal

### LINKED ISSUE #43137: Gradient should apply horizontally for horizontal bar charts
**What happened**:
I had a bar chart in vertical mode, with gradient set to "Hue" - each bar tapered through the palette correctly.  When set to horizontal however, the gradient still applies vertically, so now the top of the top bar is red, fading to green at the bottom of the bottom bar.

**What you expected to happen**:
Gradient would be applied in the same direction as the bar

**How to reproduce it (as minimally and precisely as possible)**:
Create a bar chart, set direction to horizontal, and apply a gradient

**Anything else we need to know?**:
Screenshots below.
1 grafana-good-gradient
2 grafana-bad-gradient

**Environment**:
- Grafana version: 8.3.2
- Data source type & version: Elasticsearch 7.15.2
- OS Grafana is installed on: Docker / linux
- User OS & Browser: Linux / Firefox
- Grafana plugins: None
- Others:

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/grafana/issues/43137

this makes all fill and stroke gradients perpendicular to the plot's x axis.

image

### CODE REVIEW

**Review by torkelo — APPROVED** [review]

File: packages/grafana-ui/src/components/uPlot/config/gradientFills.ts [hunk 1]
```diff
@@ -10,28 +10,61 @@ import tinycolor from 'tinycolor2';
...
 export function getHueGradientFn(
   color: string,
   opacity: number,
   theme: GrafanaTheme2
 ): (self: uPlot, seriesIdx: number) => CanvasGradient {
   return (plot: uPlot, seriesIdx: number) => {
     const ctx = getCanvasContext();
-    const gradient = ctx.createLinearGradient(0, plot.bbox.top, 0, plot.bbox.top + plot.bbox.height);
+    const gradient = makeDirectionalGradient(
+      plot.scales.x!.ori === 0 ? GradientDirection.Down : GradientDirection.Left,
```
Comment (dprokop) [inline packages/grafana-ui/src/components/uPlot/config/gradientFills.ts:63]: Can you use `ScaleOrientation` enum please?

**Review by dprokop — COMMENTED** [review]
Works as expected - one comment to address before merging this please :)

File: packages/grafana-ui/src/components/uPlot/config/gradientFills.ts (hunk 1 above)
Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/config/gradientFills.ts]: done
