### PR TITLE
Table: Support custom date formats via custom unit

### LINKED ISSUE #24655: v7.0.0-beta3 Date/Time Formatting Override in Table not working on date fields
**What happened**:
Applying Date/Time format to a table column as an override does not format the Date/Time. 

**What you expected to happen**:
The specified date/time format specification should be applied to the cell 

**How to reproduce it (as minimally and precisely as possible)**:
Create new table from query, add override to a datetime field 

**Anything else we need to know?**:
I believe this works if the data is a timestamp but not if it's a pre-formatted date/time. My datasource is  Microsoft Log Analytics with a custom query 

**Environment**:
- Grafana version: Grafana v7.0.0-beta3 (2169fc1a3f)
- Data source type & version: Azure Log Analytics (built-in datasource)
- OS Grafana is installed on: Windows server 2016 (core)
- User OS & Browser: Mac OS running latest Chrome Version 81.0.4044.138  (64-bit)
 - Grafana plugins: None (just core bundled)
- Others:

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #24655 

Currently in 7.0 units where only applied to number fields, which made the custom time formatting via the custom unit support not possible anymore. 

This used to work via units like `time:YYYY` , but the standard field config unit only applied to number fields. Changed so that unit can be applied to all fields. Not sure if that is correct. Maybe it should be number or time?

### CODE REVIEW

**Comment by ryantxu** [comment]
hymmm -- the issue is in the default field tab, the units people put in tend to just be for numbers.  When there is an override, we should always apply it.

File: packages/grafana-ui/src/utils/standardEditors.tsx [hunk 1]
```diff
@@ -63,7 +63,7 @@ export const getStandardFieldConfigs = () => {
       placeholder: 'none',
     },
 
-    shouldApply: field => field.type === FieldType.number,
+    shouldApply: () => true,
```
Comment (ryantxu) [inline packages/grafana-ui/src/utils/standardEditors.tsx:66]: is `shouldApply` called when an override is added?

maybe we should rename it to `shouldDefaultApply` and only call this on the defaults

Comment (torkelo) [reply packages/grafana-ui/src/utils/standardEditors.tsx:66]: ah, that is probably a better approach. Will maybe be a problem for new broad override matchers, but sounds like a good idea

File: packages/grafana-data/src/field/fieldOverrides.test.ts [hunk 2]
```diff
@@ -46,8 +46,16 @@ const property3 = {
   shouldApply: () => true,
 } as any;
 
+const shouldApplyFalse = {
+  id: 'custom.shouldApplyFalse', // Match field properties
+  path: 'shouldApplyFalse', // Match field properties
+  isCustom: true,
+  process: (value: any) => value,
+  shouldApply: () => false,
+} as any;
```
Comment (hugohaggmark) [inline packages/grafana-data/src/field/fieldOverrides.test.ts:55]: nit: to avoid the strict null error but would be better if we use the actual type instead of `any`.
```suggestion
const shouldApplyFalse: any = {
  id: 'custom.shouldApplyFalse', // Match field properties
  path: 'shouldApplyFalse', // Match field properties
  isCustom: true,
  process: (value: any) => value,
  shouldApply: () => false,
};
```

**Review by hugohaggmark — APPROVED** [review]
LGTM, I'm don't grasp the impact of the change here so I only left a tiny nit :)

File: packages/grafana-data/src/field/fieldOverrides.test.ts [hunk 3]
```diff
@@ -353,6 +362,27 @@ describe('setDynamicConfigValue', () => {
     expect(config.custom.property1).toEqual('applied');
   });
 
+  it('applies overrides even when shouldApply returns false', () => {
```
Comment (mckn) [inline packages/grafana-data/src/field/fieldOverrides.test.ts:365]: I see what we are doing but it feels like we probably should rename the `shouldApply` to something else or change so it can make the decision and return `true` in this scenario.

Comment (mckn) [reply packages/grafana-data/src/field/fieldOverrides.test.ts:365]: Will give it some thought and see if I can give some better feedback.

**Review by mckn — CHANGES_REQUESTED** [review]

**Comment by therealcodlord** [comment]
Should this be fixed in the latest nightly build? Or is this still incoming? I just downloaded and installed `grafana_7.1.0~e836f2dfpre_amd64.deb`

With a MySQL datasource there still does not seem to be any change to a date/time display by choosing a Unit override

With a Prometheus datasource and a query of `probe_success` although I can now see **some** change happening to values when I select a Date/Time Unit override it does not seem to be working correctly. 

For example: the field without any format shows `2020-06-17 22:44:20`

There are only 2 pre-defined date/time format values in the unit override dropdown. 
If I select `YYYY-MM-DD HH:mm:ss` the value is displayed as `22:44:20` (no date).
If I select `MM/DD/YYYY h:mm:ss a` the value is displayed as `10:44:20 pm` (no date).
If I enter a manual format such as `DD/MM/YYYY` it accepts that custom format but the displayed value goes back to being shown as `2020-06-17 22:44:20`.
If I enter a manual format such as `HH:mm` it does NOT seem to accept that custom format, so the `Unit` value reverts back to `YYYY-MM-DD HH:mm:ss` and the displayed value is shown as  `22:44:20`.

**Comment by hugohaggmark** [comment]
Thank you @therealcodlord for mentioning that. Can I bother you with creating an issue for that?
