### PR TITLE
Alerting: Fix RelativeTimeRangePicker

### LINKED ISSUE #60014: Alerting: Relative time picker not working
**What happened**
The relative time picker is not working
https://user-images.githubusercontent.com/6293563/206429474-a09151c6-f53e-4411-8cc6-b4f8564f6d97.mov

### PR DESCRIPTION
**Pull request by konrad147**
**What is this feature?**
Fix for the query relative time range selector

**Which issue(s) does this PR fix?**:
Fixes #60014

**Special notes for your reviewer**:
The problem was caused by the recent changes in Query Editor https://github.com/grafana/grafana/pull/58840
I used Portal to display the content of the selector to escape the `overflow: hidden` style on the parent container

### CODE REVIEW

File: packages/grafana-ui/src/components/DateTimePickers/RelativeTimeRangePicker/RelativeTimeRangePicker.tsx [hunk 1]
```diff
@@ -94,7 +102,7 @@ export function RelativeTimeRangePicker(props: RelativeTimeRangePickerProps) {
   };
 
   return (
-    <div className={styles.container}>
+    <div className={styles.container} ref={setMarkerElement}>
```
Comment (gillesdemey) [inline packages/grafana-ui/src/components/DateTimePickers/RelativeTimeRangePicker/RelativeTimeRangePicker.tsx:105]: I'm not entirely sure why we're passing a `useState` value in to a ref, shouldn't this be a `useRef` value?

File: packages/grafana-ui/src/components/DateTimePickers/RelativeTimeRangePicker/RelativeTimeRangePicker.tsx [hunk 2]
```diff
@@ -107,52 +115,59 @@ export function RelativeTimeRangePicker(props: RelativeTimeRangePickerProps) {
...
-                  <Input
-                    onClick={(event) => event.stopPropagation()}
-                    onBlur={() => setFrom({ ...from, validation: isRangeValid(from.value) })}
-                    onChange={(event) => setFrom({ ...from, value: event.currentTarget.value })}
-                    value={from.value}
+        <Portal>
+          <ClickOutsideWrapper includeButtonPress={false} onClick={onClose}>
+            <div
+              className={styles.content}
+              ref={setSelectorElement}
```
Comment (gillesdemey) [inline packages/grafana-ui/src/components/DateTimePickers/RelativeTimeRangePicker/RelativeTimeRangePicker.tsx:122]: Dito question as the one above :)

File: packages/grafana-ui/src/components/DateTimePickers/RelativeTimeRangePicker/RelativeTimeRangePicker.tsx (hunk 1 above)
Comment (konrad147) [reply packages/grafana-ui/src/components/DateTimePickers/RelativeTimeRangePicker/RelativeTimeRangePicker.tsx:105]: I was quite surprised too but this is what the [docs](https://popper.js.org/react-popper/v2/) says:
> Note: the usePopper hook intentionally takes the DOM node, not refs, in order to be able to update when the nodes change. A [callback ref](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs) is used here to permit this behaviour, and useState is an appropriate way to implement this.

**Review by gillesdemey — APPROVED** [review]
