### PR TITLE
Explore: Fix context view in logs, where some rows may have been filtered out.

### LINKED ISSUE #21440: Explore: show context not showing top values
**What happened**:

I was trying to find the cause of a panic and when using the `show context` on the line found, it didn't show anything at the top. However it seems that the data is being returned correctly.

image

**What you expected to happen**:

Show me the top and bottom part of the show context 

**How to reproduce it (as minimally and precisely as possible)**:

Use a filter query, then use show context.

**Environment**:
- Grafana version: Grafana v6.6.0-pre (0bf9e9bc28)
- Data source type & version: Loki
- User OS & Browser: Chrome

/cc @davkal

### PR DESCRIPTION
**Pull request by aocenas**
Closes: https://github.com/grafana/grafana/issues/21440

- We used timestamp to filter out current row which had smaller precision and could filter out more rows than just the one.
- In general it wasn't very clear what kind of timestamp we will get from the datasource as there difference between old loki, new loki and elastic. This changes it so that we expect a ISO timestamp with ms precision from datasource.
- In loki we add `tsNs` field with epoch ns string. This is used to get correct from and to ranges for the context queries, which before also lost precision and so could include or exclude some rows.
- The dataframe was not correctly reversed for one of the context windows as `id` field was kept out of reversing.
- The UID creation was not stable as it depended on the ordering of labels, which as far as I know there are no guarantees.

### CODE REVIEW

File: packages/grafana-data/src/types/logs.ts [hunk 1]
```diff
@@ -56,7 +56,6 @@ export interface LogRowModel {
   logLevel: LogLevel;
   raw: string;
   searchWords?: string[];
-  timestamp: string; // ISO with nanosec precision
```
Comment (aocenas) [inline packages/grafana-data/src/types/logs.ts]: I removed this as it was either unclear what this will be and as right now it is expect that we get iso string with ms precision from datasource having it here does not seem important as we mostly use  `timeEpochMs ` anyway

File: public/app/core/utils/explore.ts [hunk 2]
```diff
@@ -474,23 +474,23 @@ export const getRefIds = (value: any): string[] => {
 };
 
 export const sortInAscendingOrder = (a: LogRowModel, b: LogRowModel) => {
-  if (a.timestamp < b.timestamp) {
+  if (a.timeEpochMs < b.timeEpochMs) {
```
Comment (aocenas) [inline public/app/core/utils/explore.ts]: This was comparing strings before, which works but is kinda weird. One thing though is that this is ms precision right now (was also before) so not sure if it can mess up some ordering for loki where ns precision is default. It is an issue in case of merging multiple streams so there super exact ordering probably isn't important.

Comment (dprokop) [reply public/app/core/utils/explore.ts]: > One thing though is that this is ms precision right now (was also before)

Was it really? IIRC the string comparison here was done because it was in ns.

File: public/app/plugins/datasource/loki/datasource.ts [hunk 3]
```diff
@@ -518,27 +518,35 @@ export class LokiDatasource extends DataSourceApi<LokiQuery, LokiOptions> {
...
+    const nsField = fieldCache.getFieldByName('tsNs')!;
+    const nsTimestamp = nsField.values.get(row.rowIndex);
+
     if (direction === 'BACKWARD') {
       return {
         ...commonTargetOptions,
-        start: timeEpochNs - contextTimeBuffer,
-        end: timeEpochNs, // using RFC3339Nano format to avoid precision loss
+        // convert to ns, we loose some precision here but it is not that important at the far points of the context
+        start: row.timeEpochMs - contextTimeBuffer + '000000',
```
Comment (aocenas) [inline public/app/plugins/datasource/loki/datasource.ts]: `* 1e6` would work, but as other operations with ns precision integers may not work as it is over SAFE_INTEGER limit, it seems clearer to just append this as a string.

File: packages/grafana-ui/src/components/Logs/LogRowContextProvider.tsx [hunk 4]
```diff
@@ -62,16 +63,33 @@ export const getRowContexts = async (
       const data: any[] = [];
       for (let index = 0; index < dataResult.data.length; index++) {
         const dataFrame = toDataFrame(dataResult.data[index]);
-        const timestampField: Field<string> = dataFrame.fields.filter(field => field.name === 'ts')[0];
+        const fieldCache = new FieldCache(dataFrame);
+        const timestampField: Field<string> = fieldCache.getFieldByName('ts')!;
+        const idField: Field<string> | undefined = fieldCache.getFieldByName('id');
```
Comment (ivanahuckova) [inline packages/grafana-ui/src/components/Logs/LogRowContextProvider.tsx]: nice, clean and super readable!

File: packages/grafana-ui/src/components/Logs/LogRowContextProvider.tsx [hunk 5]
```diff
@@ -62,16 +63,33 @@ export const getRowContexts = async (
...
-
-          // We need to filter out the row we're basing our search from because of how start/end params work in Loki API
-          // see https://github.com/grafana/loki/issues/597#issuecomment-506408980
-          // the alternative to create our own add 1 nanosecond method to the a timestamp string would be quite complex
-          if (timestamp === row.timestamp) {
-            continue;
+          // TODO: this filtering is datasource dependant so it will make sense to move it there so the API is
+          //  to return correct list of lines handling inclusive ranges or how to filter the correct line on the
+          //  datasource.
+
```
Comment (ivanahuckova) [inline packages/grafana-ui/src/components/Logs/LogRowContextProvider.tsx]: We should probably create an issue for this, so we won't forget about moving it to datasource.

File: public/app/plugins/datasource/loki/result_transformer.ts [hunk 6]
```diff
@@ -48,67 +48,80 @@ export function legacyLogStreamToDataFrame(
...
-    refId,
-    fields: [
-      { name: 'ts', type: FieldType.time, config: { title: 'Time' }, values: times }, // Time
-      { name: 'line', type: FieldType.string, config: {}, values: lines, labels }, // Line
-      { name: 'id', type: FieldType.string, config: {}, values: uids },
-    ],
-    length: times.length,
-  };
+  return constructDataFrame(times, timesNs, lines, uids, labels, reverse, refId);
 }
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/loki/result_transformer.ts]: Nice touch with moving this to separate function.

File: public/app/plugins/datasource/loki/result_transformer.ts [hunk 7]
```diff
@@ -48,67 +48,80 @@ export function legacyLogStreamToDataFrame(
...
 
+/**
+ * Transforms LokiStreamResult structure into a dataFrame. Used when doing standard queries and newer version of Loki.
+ */
 export function lokiStreamResultToDataFrame(stream: LokiStreamResult, reverse?: boolean, refId?: string): DataFrame {
   const labels: Labels = stream.stream;
+  const labelsString = Object.entries(labels)
+    .map(([key, val]) => `${key}="${val}"`)
+    .sort()
+    .join('');
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/loki/result_transformer.ts]: 👍 for sorting!

**Review by ivanahuckova — APPROVED** [review]
Code looks very good. It has a lot of lot of nice touches! I have also tested it locally and everything works as it is supposed to. Really good job!

File: public/app/core/utils/explore.ts (hunk 2 above)
Comment (aocenas) [reply public/app/core/utils/explore.ts]: At some point this was changed https://github.com/grafana/grafana/blob/9ebd99d595bb35cadad5c545878d1165d5cbd712/public/app/plugins/datasource/loki/result_transformer.ts#L89. I assume because of new loki version sends the tiemstamp as string epoch ns which isn't parseable by dateTime (while ns precision ISO string is just throws away the precision).

Comment (aocenas) [reply public/app/core/utils/explore.ts]: So right now this is kind of least common denominator approach. This way we do not have to assume the format and parse-ability in explore code. At the same time we still pass on the full dataframe so datasources can keep the raw timestamp and use it later if they get passed a row (like in the case of the context)

Comment (aocenas) [reply public/app/core/utils/explore.ts]: > This was comparing strings before, which works but is kinda weird

this was mainly comment for recent code where you could get ISO string with either ns or ms precision (depending on datasource) which again works but it wasn't that clear imho what is going.

**Review by Estrax — APPROVED** [review]
LGTM.
