### PR TITLE
RefreshPicker: Update aria labels to match visible labels

### LINKED ISSUE #116511: [SEV2] Visual label and aria label are different for the 'Auto' menu item under 'Choose refresh time interval' button
**Pre-Requisite**:

Achieve viewport 320 X 256 by adjusting the browser. (Open developer's tool, resize and zoom the browser to achieve viewport 320 X 256).

**Steps to reproduce**:
1. Create a new dashboard
2. add a new visualization
3. Navigate to 'Change refresh time interval' and expand it.
4. Verified whether visual label and aria label are different for the 'Auto' menu item or not.

**Actual Result**:
Visual label and aria label are different for the 'Auto' menu item under 'Change refresh time interval' present under 'New dashboard' screen.

**Expected Result**
Visual label and aria label should be same for the 'Auto' menu item under 'Change refresh time interval' present under 'New dashboard' screen.

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

WCAG: [2.5.3 Label in Name](https://liquid.microsoft.com/Web/Object/Read/ms.accessibility/Requirements/2.5.3)
EN 301 549: [PDF of EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf), which applies WCAG principles for Label in Name to 9.2.5.3 web, 10.2.5.3 non-web documents, and 11.2.5.3.1 software.

**Environment**:
- Grafana version: 12.2.0
- Data source type & version: n/a
- User OS & Browser: any
- Others:

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- updates `aria-label`s to match visible labels

**Why do we need this feature?**

- so people using a screenreader have the same experience

**Who is this feature for?**

- anyone using a screenreader

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/116511

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by joshhunt — APPROVED** [review]

File: packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx [hunk 1]
```diff
@@ -32,17 +32,17 @@ export interface Props {
 const offOption = {
   label: 'Off',
   value: '',
-  ariaLabel: 'Turn off auto refresh',
+  ariaLabel: 'Off',
```
Comment (joshhunt) [inline packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx:35]: actually - are these aria labels even needed? Can they just be removed completely?

Comment (ashharrison90) [reply packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx:35]: sort of. there's other options where the aria-labels are different (e.g. 5s -> "5 seconds"). but for these i guess strictly speaking they're not required. i've removed them, updated the tests and updated the code to do `const durationAriaLabel = selectedValue.ariaLabel ?? selectedValue.label;`

**Review by joshhunt — APPROVED** [review]

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/22222968017)
- Version: 13.0.0-22222968017
