### PR TITLE
Instrumentation: Fix HTTP request instrumentation of authentication failures

### LINKED ISSUE #39590: Prometheus metrics for HTTP 401 are not reported.
**What happened**:
Prometheus metrics for HTTP 401 are not reported.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ docker run -d -p 3000:3000 grafana/grafana
$ curl --user name:password http://localhost:3000 -I
HTTP/1.1 401 Unauthorized
$ curl -s http://localhost:3000/metrics | grep grafana_http_request_duration_seconds_count
# empty
# missing grafana_http_request_duration_seconds_count{handler="/",method="GET",status_code="401"} 1
...

```
**Environment**:
- Grafana version: v8.1.5 (c725a4259a)

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Moves the request tracing middleware earlier in the chain, just after the tracing middleware and before the log middleware. With these changes we'll be able to track authentication/authorization status failures that currently exits early and don't execute the request tracing middleware. In addition, there might be some other routes now being tracked with this that we didn't do before.

**Which issue(s) this PR fixes**:
Fixes #39590 

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/middleware/request_metrics.go [hunk 1]
```diff
@@ -45,50 +45,60 @@ func init() {
...
+		c.Next()
 
-			switch {
-			case strings.HasPrefix(req.RequestURI, "/api/datasources/proxy"):
-				countProxyRequests(status)
-			case strings.HasPrefix(req.RequestURI, "/api/"):
-				countApiRequests(status)
-			default:
-				countPageRequests(status)
+		handler := req.URL.Path
```
Comment (marefr) [inline pkg/middleware/request_metrics.go:62]: We might not want to do this because it will create a handler label value for every route not registered, for example any 404 page will be put in this label value. So yeah probably going to remove this.

Comment (bergquist) [reply pkg/middleware/request_metrics.go:62]: We want the use the route used to register the handler. Ex https://github.com/grafana/grafana/blob/main/pkg/api/api.go#L173 so that we don't instrument every id differently. That would create an carnality explosion. 

@zserge I think you said during one of the backend arc meetings that it would be possible to get the route from macaron some way. But I might have missunderstod you.

**Review by bergquist — CHANGES_REQUESTED** [review]

File: pkg/middleware/request_metrics.go [hunk 2]
```diff
@@ -45,50 +45,60 @@ func init() {
...
+
+		if routeOperation, exists := RouteOperationNameFromContext(c.Req.Context()); exists {
+			handler = routeOperation
```
Comment (marefr) [inline pkg/middleware/request_metrics.go:65]: @bergquist this is using the route used to register the handler

Comment (bergquist) [reply pkg/middleware/request_metrics.go:65]: Ah. I guess I just didn't grok the code :+1: 

Can we default to '"unknown"' instead of using the `req.URL.Path`?

Comment (marefr) [reply pkg/middleware/request_metrics.go:65]: Yeah good idea :+1:

**Review by bergquist — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Waiting for a couple of additional eyes from @pianohacker and @guicaulada before merging

**Review by guicaulada — APPROVED** [review]
