### PR TITLE
Prometheus: Fix adding of multiple values for regex operator

### LINKED ISSUE #51628: Query Builder throws away values when switching from `=~` to `!~`.
When using the new Grafana 9 (9.0.2) query builder to adjust queries to go from `match regex =~` to `not match regex !~` the values disappear except the first one when I expect to be able to still have the same values available:

Before:
Screenshot from 2022-06-30 13-00-01
After: 
Screenshot from 2022-06-30 13-04-31

See how `grpc_code!~"Aborted"` instead of the many previous values.

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
This PR fixes choosing multiple values for `!~` regex opreator in Loki and Prometheus query builder. 

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/51628

**Special notes for your reviewer**:

To test this, select Loki/Prometheus data source, choose query builder mode and in label selector, choose `~!` operator and try to add multiple values.

### CODE REVIEW

**Review by gabor — APPROVED** [review]
LGTM! (tested with Loki only)

File: public/app/plugins/datasource/prometheus/querybuilder/shared/LabelFilterItem.tsx [hunk 1]
```diff
@@ -25,7 +25,7 @@ export function LabelFilterItem({ item, defaultOp, onChange, onDelete, onGetLabe
   }>({});
 
   const isMultiSelect = () => {
-    return item.op === operators[0].label;
+    return item.op === operators[0].label || item.op === operators[3].label;
```
Comment (gabor) [inline public/app/plugins/datasource/prometheus/querybuilder/shared/LabelFilterItem.tsx:28]: nitpick: this is a little hard to read (which are the zero-element and the three-element?).. maybe we could modify the `operators` structure, to be like:

```ts
const operators = [
  { label: '=~', value: '=~' , isMultiselect: true},
.
.
.
];
```

?

Comment (ivanahuckova) [reply public/app/plugins/datasource/prometheus/querybuilder/shared/LabelFilterItem.tsx:28]: Yeah, I was actually thinking about this as well. Good call. I'll change it.

Comment (ivanahuckova) [reply public/app/plugins/datasource/prometheus/querybuilder/shared/LabelFilterItem.tsx]: Updated in https://github.com/grafana/grafana/pull/52978/commits/d7191be3492a3b90a69ab7d3f09356202fad1136

**Review by gabor — APPROVED** [review]
LGTM!

**Review by obetomuniz — APPROVED** [review]
LGTM 👏
