### PR TITLE
Annotations: Avoid crash when listing panels (that are rows)

### LINKED ISSUE #66862: Annotations: Page crashing
Link to page: [https://admin-dev-us-central-0.grafana.net/grafana/d/84ee45b3ad1a2dd0766509a1055f9460/agent-ma[…]orgId=1&refresh=1m&editview=annotations&editIndex=0](https://admin-dev-us-central-0.grafana.net/grafana/d/84ee45b3ad1a2dd0766509a1055f9460/agent-management-overview?orgId=1&refresh=1m&editview=annotations&editIndex=0)

**Steps to reproduce**
1. In a new/existing dashboard add some rows
2. Go to Dashboard Settings
3. Click on Annotations tab
4. Click on one of the existing annotations
5. => The page is crashing

### PR DESCRIPTION
**Pull request by adela-almasan**
Before
The panels list was including rows, which was causing the page to crash.

rows

After
no_rows

Fixes #66862 

**Testing steps:**

1. In a new/existing dashboard and add some rows
2. Go to dashboard Settings
3. Click on Annotations tab
4. Go to "Show In" section
5. Choose "Selected panels"

Expected results:

- You should only see a list of panels (no rows)
- The page should not crash

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by drew08t — APPROVED** [review]
Tested locally successfully and LGTM!

File: public/app/features/dashboard/components/AnnotationSettings/AnnotationSettingsEdit.tsx [hunk 1]
```diff
@@ -142,6 +142,7 @@ export const AnnotationSettingsEdit = ({ editIdx, dashboard }: Props) => {
   const panels: Array<SelectableValue<number>> = useMemo(
     () =>
       dashboard?.panels
+        .filter((panel) => config.panels[panel.type])
```
Comment (torkelo) [inline public/app/features/dashboard/components/AnnotationSettings/AnnotationSettingsEdit.tsx:145]:
```suggestion
        .filter((panel) => panel.plugin?.dataSupport?.annotations)
```

@ryantxu @adela-almasan that should do it

Comment (torkelo) [reply public/app/features/dashboard/components/AnnotationSettings/AnnotationSettingsEdit.tsx:145]: hm.,. the only problem with that is that it won't work for lazy loaded panels that have yet to to render (and load it's plugin), and this code does not take rows into account.

To get all panels including those in collapsed rows it's best to use dashboard.panelIterator,  but to look up if the visualization actually supports annotations is impossible without loading the PanelPlugin

[the remark this answers is not in the document]
Comment (nmarrs) [reply public/app/features/dashboard/components/AnnotationSettings/AnnotationSettingsEdit.tsx:145]: This might a good e2e test case to include (that rows / only panels that support annotations are included in list)

**Review by ryantxu — APPROVED** [review]
this fixes a crash, so lets merge now -- and revist how to iterate and filter soon
