### PR TITLE
Canvas: Fix inconsistent element resizing UX

### LINKED ISSUE #49449: Canvas: Inconsistent element resize UX
Currently for some constraint options (center / scale) the resize functionality is not working as expected
(i.e. center resizes both sides at the same time vs. just the one side you are trying to resize)

### PR DESCRIPTION
**Pull request by nmarrs**
**What this PR does / why we need it**:
Address inconsistent element resize behavior when using `center` and `scale` constraint options.

https://user-images.githubusercontent.com/22381771/169919579-35ed2d36-19ce-43cb-b460-f76ea3e805f3.mov

**Which issue(s) this PR fixes**:

Fixes #49449

### CODE REVIEW

File: public/app/features/canvas/runtime/element.tsx [hunk 1]
```diff
@@ -29,6 +29,11 @@ export class ElementState implements LayerElement {
   // Determine whether or not element is in motion or not (via moveable)
   isMoving = false;
 
+  // Determine whether or not to use temp stored constraint for visualization purposes
+  // (switch to top / left constraint to simplify some functionality)
+  shouldUseTempConstraint = false;
+  tempConstraint: Constraint = {};
```
Comment (nmarrs) [inline public/app/features/canvas/runtime/element.tsx:35]: Don't love this pattern, but without it is harder to match Figma's UX (keep showing constraint visualizations on re-size, as well as keeping the layout options in sync (i.e. not flashing / changing to top / left and then back to original))

Comment (ryantxu) [inline public/app/features/canvas/runtime/element.tsx:35]: Maybe rather than boolean and constraint, we could just use:
```suggestion
  tempConstraint: Constraint | undefined;
```
if set, we use it

**Review by ryantxu — APPROVED** [review]
:shipit:
