### PR TITLE
A11y: Add aria-expanded to expand/collapse buttons

### LINKED ISSUE #117828: A11y: Expand/collapse buttons do not announce their expanded or collapsed state
## Description

Several expand/collapse buttons update their `aria-label` to reflect the current state, but the updated state is not announced by screen readers upon activation. The screen reader does not inform users whether the section is now expanded or collapsed.

**Affected areas:**
- "Section Bookmark" arrow icon button
- "Toggle Top Search Bar" button
- "Help" and "Profile" buttons
- "Open" and "Close Menu" buttons
- Expand/collapse row buttons in data tables

## Steps to reproduce

1. Open Grafana in Chrome on Windows
2. Enable JAWS screen reader
3. Navigate to a section containing an expand/collapse button (e.g., the "Section Bookmark" arrow icon)
4. Use Tab to reach the button
5. Press Enter or Space to toggle its state
6. Observe that the screen reader does not announce the updated state (e.g., "expanded" or "collapsed")

## Actual behavior

The button's `aria-label` updates to reflect the state (e.g., "Collapse section Bookmarks"), but the screen reader does not announce the updated expand/collapse state after activation.

## Expected behavior

The button should dynamically announce its updated expand/collapse state every time it is activated.

## Suggested fix

Use `aria-expanded` on the button element to programmatically communicate the expanded/collapsed state, rather than relying solely on `aria-label` changes:

```html
<button aria-expanded="true" aria-label="Section Bookmarks" ...>
```

Reference: [WAI-ARIA Disclosure Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/)

## WCAG criteria

- **4.1.2 Name, Role, Value** (Level A)

## Possible duplicates in grafana/grafana

- [#86649](https://github.com/grafana/grafana/issues/86649) — Change time settings: No state property is defined for the 'Change time settings' button (closed; same pattern — button doesn't announce expanded/collapsed state)
- [#66350](https://github.com/grafana/grafana/issues/66350) — Aria label is not defined for "expand/collapse" button present for "Data source: AWS IoT Site wise" (open; expand/collapse button missing accessible name)
- [#53924](https://github.com/grafana/grafana/issues/53924) — A11y: Implement aria-expanded for query rows (closed; same aria-expanded pattern)

## Issue reference

Reference issue 04

### PR DESCRIPTION
**Pull request by Clarity-89**
**What is this feature?**

Adds `aria-expanded` attribute to expand/collapse buttons across the Grafana UI to announce state changes to screen readers, per WAI-ARIA disclosure pattern.

**Why do we need this feature?**

Screen readers were not announcing expanded/collapsed state changes when users activated expand/collapse buttons. The `aria-expanded` attribute programmatically communicates state to assistive technologies, meeting WCAG 4.1.2 (Name, Role, Value) requirements.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/117828

**Special notes for your reviewer:**

- Dropdown component now automatically sets `aria-expanded` on all dropdown triggers (Help, Profile buttons)

### CODE REVIEW

File: public/app/core/components/AppChrome/TopBar/SingleTopBar.tsx [hunk 1]
```diff
@@ -71,7 +71,8 @@ export const SingleTopBar = memo(function SingleTopBar({
               narrow
               id={MEGA_MENU_TOGGLE_ID}
               onClick={onToggleMegaMenu}
-              tooltip={t('navigation.megamenu.open', 'Open menu')}
+              tooltip={t('navigation.megamenu.open', 'Main menu')}
```
Comment (Clarity-89) [inline public/app/core/components/AppChrome/TopBar/SingleTopBar.tsx:74]: This change is needed so screen readers properly announce the menu, otherwise they would announce it as "Open menu, expanded", which can be confusing.

**Review by eledobleefe — APPROVED** [review]
LGTM

**Review by ywzheng1 — APPROVED** [review]

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/22754586795)
- Version: 13.0.0-22754586795
