### PR TITLE
CloudWatch: Calculate period based on time range

### LINKED ISSUE #18493: CloudWatch: Move min period implementation to backend
I am using backend plugin API of cloudwatch to qury data from AWS in my application. 

But it seems if "min period" is "Auto" then logic to determine Period for query is in frontend. 

Screenshot 2019-08-11 at 2 02 15 PM

here is code block from dtatasourece.ts :
`getPeriod(target: any, options: any, now?: number) {
    const start = this.convertToCloudWatchTime(options.range.from, false);
    const end = this.convertToCloudWatchTime(options.range.to, true);
    now = Math.round((now || Date.now()) / 1000);

    let period;
    const range = end - start;

    const hourSec = 60 * 60;
    const daySec = hourSec * 24;
    let periodUnit = 60;
    if (!target.period) {
      if (now - start <= daySec * 15) {
        // until 15 days ago
        if (target.namespace === 'AWS/EC2') {
          periodUnit = period = 300;
        } else {
          periodUnit = period = 60;
        }
      } else if (now - start <= daySec * 63) {
        // until 63 days ago
        periodUnit = period = 60 * 5;
      } else if (now - start <= daySec * 455) {
        // until 455 days ago
        periodUnit = period = 60 * 60;
      } else {
        // over 455 days, should return error, but try to long period
        periodUnit = period = 60 * 60;
      }
    } else {
      if (/^\d+$/.test(target.period)) {
        period = parseInt(target.period, 10);
      } else {
        period = kbn.interval_to_seconds(this.templateSrv.replace(target.period, options.scopedVars));
      }
    }
    if (period < 1) {
      period = 1;
    }
    if (!target.highResolution && range / period >= 1440) {
      period = Math.ceil(range / 1440 / periodUnit) * periodUnit;
    }

    return period;
  }`

If we have this logic in backend plugin somewhere in get_metric_data.go or  cloudwatch.go i can use direct backend api to get cloudwatch data. 

Request is to add getPeriod logic in backend if its mentioned Auto in panel configuration so that i can use backend API directly to query data from my application

### LINKED ISSUE #20652: Cloudwatch query to GetMetricData fails when requesting too many datapoints
**What happened**:
Upgraded from 6.4 to 6.5 and cloudwatch queries that span more then three hours in the past and return more than 90k metrics are failing with the error : "too many datapoints requested in query A. Please try to reduce the time range"

**What you expected to happen**:
Grafana should detect if a query is going to possibly return more than the GetMetricData limits and either split the query into multiple requests or increase the minimum interval to get under the limits. The limits are :
 - 180,000 Datapoints Per Second (DPS) if the StartTime used in the API request is less than or equal to three hours from current time. 
 - 90,000 DPS if the StartTime is more than three hours from current time. 
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html
These limits cannot be changed and seem to not just be a per second threshold but a hard limit on the size of a singe query response.

**How to reproduce it (as minimally and precisely as possible)**:
query cloudwatch with a single query that will return more than 90k datapoints over a three hour period. For me this happens when i request the cpu average of all of the ECS services (96 of them) in a cluster for 24 hours. This gives 138240 datapoints.

I know I can manually specify a larger interval but as I widen my time range it will eventually fail again.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: Cloudwatch
- OS Grafana is installed on: grafana provided docker container
- User OS & Browser: macos + chrome 79
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by sunker**
This PR will add logic that will set a period interval based on the time range in case the period field in the query editor is left blank or has the value `auto`. If the period is actively defined by the user in the query editor, that value will be passed to the GMD api unconditionally. Previously the auto period calculations were made in the frontend, and therefore it didn't work for alerting. This PR moves the period calculation to the backend.  

If the period field is not defined by the user, the period will be calculated the following way:
`periods = [60, 300, 900, 3600, 21600]`
`x = timeRangeDeltaInSeconds / 2000`
x will then snap to the closest number in the periods array

This is an example with a time range of 30 days
`2,592,000 / 2000 = 1296` --> `900 is the closest number`

fixes #20652
fixes #18493

### CODE REVIEW

**Comment by sunker** [comment]
@mtanda could you review this, please?

File: pkg/tsdb/cloudwatch/request_parser_test.go [hunk 1]
```diff
@@ -78,6 +82,99 @@ func TestRequestParser(t *testing.T) {
...
+
+					res, err := parseRequestQuery(query, "ref1", from, to)
+					So(err, ShouldBeNil)
+					So(res.Period, ShouldEqual, 21600)
+				})
+			})
+
+			Convey("closest works as expected", func() {
+				periods := []int{60, 300, 900, 3600, 21600}
+				Convey("and input is lower than 60", func() {
```
Comment (mtanda) [inline pkg/tsdb/cloudwatch/request_parser_test.go]: @sunker Would you add test which confirm the period isn't shorter than CloudWatch retension?

https://aws.amazon.com/about-aws/whats-new/2016/11/cloudwatch-extends-metrics-retention-and-new-user-interface/

Sample test case.
```
So(closest(periods, (60 * 60 * 24 * 15) + 1), ShouldEqual, 300)
So(closest(periods, (60 * 60 * 24 * 63) + 1), ShouldEqual, 3600)
```

**Review by mtanda — DISMISSED** [review]

**Review by marefr — APPROVED** [review]
LGTM

**Comment by mtanda** [comment]
@sunker When I tested https://github.com/grafana/grafana/commit/8616f1beac7f31d28ef819f1e2ed93882dcd3b84, cloudwatch query is randomly failed.

I get error in my console. Would you test in your environment?
```
EROR[01-17|22:54:13] Metric request error                     logger=context userId=1 orgId=1 uname=admin error="Error parsing query A, time: invalid duration undefined"
```

**Comment by mtanda** [comment]
image
When I get query error, period is `undefined`.

image
When success, the period is empty string.

**Comment by mtanda** [comment]
I guess it can be reproduced, by creating new panel which use CloudWatch datasource.

**Comment by sunker** [comment]
Oh, must have been a merge problem. Fix coming right up @mtanda..

**Comment by sunker** [comment]
@mtanda see https://github.com/grafana/grafana/pull/21574

**Comment by crxpandion** [comment]
I think this commit introduced a behavior where when you zoom in (to say start-end < 15 days) on an event that occurred more than 15 or 63 days prior and `period` is set to `auto` the query will use `period` as `60` resulting in Cloudwatch returning no data.

To fix we will need to have a concept of `now` in this function to understand which `period` Cloudwatch has retained.
