### PR TITLE
Alerting: Do not include button in googlechat notification if URL invalid

### LINKED ISSUE #47305: Google Chat Alert empty if root_url not absolute
**What happened**:
Starting this weekend (Weekend of April first, funnily enough), Google Chat alerts started disappearing for us. Alerts would still be triggered, however, they would be completely empty:

After a bunch of debugging, including recompiling Grafana with additional logging to get the webhook body, I discovered that this happens, if a button URL in a card is invalid. This can be reproduced by using the following JSON payload (notice the relative URL `/grafana/alerting/list` in `cards.0.sections.1.buttons.0.textButton.onClick.openLink.url`):

<details>
<summary>Invalid Google Chat Webhook Payload</summary>
<pre><code>
{
  "previewText": "[FIRING:1]  (TestAlert Grafana)",
  "fallbackText": "[FIRING:1]  (TestAlert Grafana)",
  "cards": [
    {
      "header": {
        "title": "[FIRING:1]  (TestAlert Grafana)"
      },
      "sections": [
        {
          "widgets": [
            {
              "textParagraph": {
                "text": "**Firing**\n\nValue: [ metric='foo' labels={instance=bar} value=10 ]\nLabels:\n - alertname = TestAlert\n - instance = Grafana\nAnnotations:\n - summary = Notification test\nSilence: /grafana/alerting/silence/new?alertmanager=grafana&matcher=alertname%3DTestAlert&matcher=instance%3DGrafana\n"
              }
            },
            {
              "buttons": [
                {
                  "textButton": {
                    "text": "OPEN IN GRAFANA",
                    "onClick": {
                      "openLink": {
                        "url": "/grafana/alerting/list"
                      }
                    }
                  }
                }
              ]
            },
            {
              "textParagraph": {
                "text": "Grafana v8.4.4 | 05 Apr 22 11:16 CEST"
              }
            }
          ]
        }
      ]
    }
  ]
}
</pre></code>
</details>

This invalid relative URL was caused by using a relative URL `/grafana` in `root_url`. Prior to this weekend we did not notice this since Google would display `fallbackText` in this case - but it seems like Google changed something over the weekend (?). Using an absolute URL `https://monitoring.mycompany.com/grafana` fixed the issue.

**What you expected to happen**:
Google Chat Alerts should be displayed as cards. If `root_url` is relative, then the button could be omitted and a warning logged.

In general, the `notifications.Webhook.sendWebRequestSync` could log the request and response bodies when debug logging is active in order to make this kind of debugging easier.

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure Grafana with a relative `root_url` (e.g. `/` or `/foo`)
2. Set up a Google Chat / Hangouts Contact Point with a webhook URL pointing to your Google Chat Channel
3. Send a Test alert to that contact point
4. Observe an empty message in Google Chat

**Anything else we need to know?**:
I'll open 2 PRs for this Issue, one with a fix  for 

**Environment**:
- Grafana version: 8.4.4
- Data source type & version: n/a
- OS Grafana is installed on: Could be reproduced using the `8.4.4` and `8.4.4-ubuntu` docker images running on Kubernetes using the `grafana/helm-charts` chart as well as directly on my Ubuntu 21.04 machine 
- User OS & Browser: n/a
- Grafana plugins: none
- Others: n/a

### PR DESCRIPTION
**Pull request by j6s**
**What this PR does / why we need it**:
This prevents the "Open in Grafana" button from being added to googlechat notifications if the URL for it is not absolute. This is done to prevent empty-messages that google adds in that case.

**Which issue(s) this PR fixes**:

Fixes #47305

**Special notes for your reviewer**:
I am not really familiar with this codebase and how code is usually structured - I did not know where best to put the `isUrlAbsolute` utility method. Therefor, I added it to the `GoogleChatNotifier` structs themselves.

### CODE REVIEW

**Comment by joeblubaugh** [comment]
Can you say a little bit more about what the user experience is when the URL is not absolute? Is it that the button links to a relative path within the Google Chat app? Does it lead to a 404 page? Something else?

The code looks OK to me, but it's also possible we should move this check further up the stack and/or eliminate cases where the URL is not absolute. I can't think of a reason the URL shouldn't have a host component, but maybe one of my coworkers knows of a few.

**Comment by j6s** [comment]
I have outlined the user experience with a non-relative URL in #47305 : Unfortunately having a non-absolute URL leads to the message not being shown at all (empty message) in google chat:

image

 That's where the idea of simply hiding the button came from: In that case there will at least be a message being rendered (Without the 'open in grafana' button, however): 

image

File: pkg/services/alerting/notifiers/googlechat.go [hunk 1]
```diff
@@ -171,21 +172,25 @@ func (gcn *GoogleChatNotifier) Notify(evalContext *alerting.EvalContext) error {
...
+							},
 						},
 					},
 				},
 			},
-		},
-	})
+		})
+	} else {
+		gcn.log.Warn("Alerting Rule URL is not absolute, not adding 'open in grafana' button to prevent google from displaying empty alerts. This is most likely due to using a non-absolute root_url", "ruleURL", ruleURL)
```
Comment (alexweav) [inline pkg/services/alerting/notifiers/googlechat.go:192]:
```suggestion
		gcn.log.Warn("Grafana External URL setting is missing or invalid. Skipping 'open in grafana' button to prevent google from displaying empty alerts.", "ruleURL", ruleURL)
```
Simplify, and point users in the right direction to fix

File: pkg/services/ngalert/notifier/channels/googlechat.go [hunk 2]
```diff
@@ -98,21 +99,25 @@ func (gcn *GoogleChatNotifier) Notify(ctx context.Context, as ...*types.Alert) (
...
-	// Add a button widget (link to Grafana).
-	widgets = append(widgets, buttonWidget{
-		Buttons: []button{
-			{
-				TextButton: textButton{
-					Text: "OPEN IN GRAFANA",
-					OnClick: onClick{
-						OpenLink: openLink{
-							URL: ruleURL,
+	if gcn.isUrlAbsolute(ruleURL) {
```
Comment (alexweav) [inline pkg/services/ngalert/notifier/channels/googlechat.go:102]: Thank you for adding it to both legacy and ng :)

File: pkg/services/ngalert/notifier/channels/googlechat.go [hunk 3]
```diff
@@ -98,21 +99,25 @@ func (gcn *GoogleChatNotifier) Notify(ctx context.Context, as ...*types.Alert) (
...
+							},
 						},
 					},
 				},
 			},
-		},
-	})
+		})
+	} else {
+		gcn.log.Warn("Alerting Rule URL is not absolute, not adding 'open in grafana' button to prevent google from displaying empty alerts. This is most likely due to using a non-absolute root_url", "ruleURL", ruleURL)
```
Comment (alexweav) [inline pkg/services/ngalert/notifier/channels/googlechat.go:119]:
```suggestion
		gcn.log.Warn("Grafana External URL setting is missing or invalid. Skipping 'open in grafana' button to prevent google from displaying empty alerts.", "ruleURL", ruleURL)
```
same as above

File: pkg/services/ngalert/notifier/channels/googlechat.go [hunk 4]
```diff
@@ -98,21 +99,25 @@ func (gcn *GoogleChatNotifier) Notify(ctx context.Context, as ...*types.Alert) (
 	}
 
 	ruleURL := joinUrlPath(gcn.tmpl.ExternalURL.String(), "/alerting/list", gcn.log)
```
Comment (alexweav) [inline pkg/services/ngalert/notifier/channels/googlechat.go:101]: I suppose this right here might be the underlying issue. Presumably `gcn.tmpl.ExternalURL` is `""` if the template doesn't have any way to know the instance's external URL (missing from the config file, etc.)

I still like this approach of handling it, though - since we have no idea what was actually entered in the config file, we are covering all bases. It doesn't seem sufficient to only check for emptiness here.

I commented suggestions to the log message, to point users toward the config file as a likely culprit.

Nothing to do here, just thought I'd point this out.

File: pkg/services/ngalert/notifier/channels/googlechat.go (hunk 2 above)
Comment (alexweav) [inline pkg/services/ngalert/notifier/channels/googlechat.go:102]: Could we add a test case for this to the `googlechat_test.go` file next to this one?

All the existing cases provide a valid base URL in the settings (`http://localhost`). So, they never run into this problem.

https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/notifier/channels/googlechat_test.go#L37-L91

It'd be nice to have another case that does not have this in settings, and then asserts that the `expMsg` does not have the `buttonWidget`.

**Review by alexweav — COMMENTED** [review]
Thank you for this contribution!

It's looking good - just a couple minor comments.

File: pkg/services/ngalert/notifier/channels/googlechat.go (hunk 2 above)
Comment (j6s) [reply pkg/services/ngalert/notifier/channels/googlechat.go:102]: I added 2 Testcases to the ngvariant of the channel: one for an empty URL, one for a relative URL. I did not add a testcase for the old alerting

**Review by armandgrillet — APPROVED** [review]
LGTM, existing reviews raise good questions but the changes and added tests are enough for me to believe this is a net positive.

**Comment by armandgrillet** [comment]
I believe `continuous-integration/drone/pr` CI is failing for unrelated reasons, rebasing this PR should make it pass.

**Review by alexweav — APPROVED** [review]
LGTM

**Comment by alexweav** [comment]
The enterprise check that's failing simply fails on all PRs from forks due to how GH propagates secrets, it's not the fault of this PR specifically.

Ran it past some of the enterprise engineers and we decided it's probably best to ignore the failing check.

Thank you @j6s for this contribution! It hit right at a busy time so it took longer than normal to get through, apologies for that.
