### PR TITLE
Alerting: Return proper status code when trying to create alert notification channel with duplicate name or uid

### LINKED ISSUE #20089: When creating notification channel with non-unique uid or name should not return HTTP status 500
**What happened**:
We have a service that creates programmatic dashboards and alerts in Grafana. One step is to check if a notification channel with a certain uid (same as the email address) exists. If it does not exist, the service will try to create it. 
A handful of times, we have run into the service returning a 500 despite the unique uid and the notification channel not existing if you try to look it up with that uid. 
If you then check for a notification channel with the same name (different uid) and delete that, then try making the channel again with the email address as the uid it will work. Then the service we have can find the notification channel as expected.

**What you expected to happen**:
If a notification channel has the same name but a unique UID, the api should be able to create the new notification channel. 

**How to reproduce it (as minimally and precisely as possible)**:
Have an email notification channel that exists with the name you're going to use.

First check if a notification channel exists with the uid you want:
curl -H "Authorization: Bearer" http://grafana/api/alert-notifications/uid/team+alerts@company.com
{"message":"Alert notification not found"}%

Run an API call to create a new notification channel with the same name but a unique uid (uid is the email address in this case):
curl -H "Content-Type: application/json" -H "Authorization: Bearer" -d @alert.json -X POST http://grafana/api/alert-notifications
{"message":"Failed to create alert notification"}%

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.3.5
- Data source type & version:
- OS Grafana is installed on: linux, ubuntu
- User OS & Browser: mac & chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by jgulick48**
…tification where the name or UID already exists.

**What this PR does / why we need it**:
When trying to create an Alert Notification where the uid or name are already in use grafana currently returns a 500 status code.  This adds two new errors that are returned from the sqlstore and the api will now return a 409 (conflict) status code. 

**Which issue(s) this PR fixes**:

Fixes #20089

### CODE REVIEW

File: pkg/api/alerting.go [hunk 1]
```diff
@@ -273,6 +273,9 @@ func CreateAlertNotification(c *models.ReqContext, cmd models.CreateAlertNotific
 	cmd.OrgId = c.OrgId
 
 	if err := bus.Dispatch(&cmd); err != nil {
+		if err == models.ErrAlertNotificationWithSameNameExists || err == models.ErrAlertNotificationWithSameUIDExists {
```
Comment (aknuds1) [inline pkg/api/alerting.go:276]: It's better to use `errors.Is` than comparing errors directly, since otherwise you'll miss wrapped errors:
```suggestion
		if errors.Is(err, models.ErrAlertNotificationWithSameNameExists) || errors.Is(err, models.ErrAlertNotificationWithSameUIDExists) {
```

**Review by aknuds1 — CHANGES_REQUESTED** [review]

**Review by aknuds1 — APPROVED** [review]
LGTM, but looks as if you need to fix a compilation error.

**Comment by marefr** [comment]
I think errors package is missing an import in api/alerting.go. @aknuds1 maybe you could help out here getting this merged?

**Comment by aknuds1** [comment]
I've fixed the build, do you mind if I push my commit to your branch @jgulick48?

**Comment by jgulick48** [comment]
> I've fixed the build, do you mind if I push my commit to your branch @jgulick48?

Go ahead. Sorry I haven't had time to circle back on this one.

**Comment by aknuds1** [comment]
> > I've fixed the build, do you mind if I push my commit to your branch @jgulick48?
> 
> Go ahead. Sorry I haven't had time to circle back on this one.

Done.

**Comment by aknuds1** [comment]
Thanks for contributing!
