### PR TITLE
Fix kiosk bug

### LINKED ISSUE #43150: Entering kiosk mode in a different org locks UI
**What happened**:

The search params kiosk not work in url when the org to be accessed is not the current org.

example:

when the current org is 2, but I visit org 3 with kiosk in url:

https://xxx.com/?orgId=3&kiosk

The kiosk will be discarded:
https://xxx.com/?kiosk=&orgId=3

and no full screen

**What you expected to happen**:

kiosk can work

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: OpenTSDB,prome,Mysql and so on
- OS Grafana is installed on: Linux
- User OS & Browser: macOS, Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by dessen-xu**
**What this PR does / why we need it**:

Fix: The search params kiosk not work in url when the org to be accessed is not the current org

**Which issue(s) this PR fixes**:

Fixes #43150

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by dessen-xu** [comment]
@sdboyer Hi, what does it mean? I can not fond the pull request in my repo

image

**Comment by papagian** [comment]
> @sdboyer Hi, what does it mean? I can not fond the pull request in my repo
> 
> image

It means that the PR should be assigned to a milestone. I have added a milestone and now it's fixed.

File: pkg/middleware/org_redirect.go [hunk 1]
```diff
@@ -44,7 +44,13 @@ func OrgRedirect(cfg *setting.Cfg) web.Handler {
 			return
 		}
 
-		newURL := fmt.Sprintf("%s%s?%s", cfg.AppURL, strings.TrimPrefix(c.Req.URL.Path, "/"), c.Req.URL.Query().Encode())
+		var queryString string = c.Req.URL.Query().Encode()
+		if strings.Contains(queryString, "kiosk=") && !strings.Contains(queryString, "kiosk=tv") {
```
Comment (papagian) [inline pkg/middleware/org_redirect.go:48]: I would suggest to better use [Values.Has()](https://pkg.go.dev/net/url#Values.Has) for checking if. `kiosk` query parameter exists.
Also I would copy `c.Req.URL.Query()` to a variable, delete the `kiosk` parameter (using [Values.Del()](https://pkg.go.dev/net/url#Values.Del), encode it and then append the `kiosk`.

**Comment by dessen-xu** [comment]
@papagian Thanks

**Review by papagian — CHANGES_REQUESTED** [review]
Thank you for your contribution! I have some suggestions. Also could you please update the [test](https://github.com/grafana/grafana/blob/e993f0c62e301695e3538bd84f8ed00bd418ab02/pkg/middleware/org_redirect_test.go#L14) to cover these cases and if check the `Location` header is the expected.

File: pkg/middleware/org_redirect_test.go [hunk 2]
```diff
@@ -30,7 +30,7 @@ func TestOrgRedirectMiddleware(t *testing.T) {
 		}
 
 		sc.m.Get("/", sc.defaultHandler)
-		sc.fakeReq("GET", "/?orgId=3").exec()
+		sc.fakeReq("GET", "/?orgId=3&kiosk").exec()
```
Comment (papagian) [inline pkg/middleware/org_redirect_test.go:33]: I would test all the following inputs:
- `/?orgId=3`
- `/?orgId=3&kiosk`
- `/?kiosk=&orgId=3`
- `/?kiosk=tv&orgId=3`

File: pkg/middleware/org_redirect_test.go [hunk 3]
```diff
@@ -30,7 +30,7 @@ func TestOrgRedirectMiddleware(t *testing.T) {
...
 
 		assert.Equal(t, 302, sc.resp.Code)
```
Comment (papagian) [inline pkg/middleware/org_redirect_test.go:35]: you need to check also that the `sc.resp.Header()["Location"]` is the expected (it contains `&kiosk` instead of `&kiosk=`

File: pkg/middleware/org_redirect.go [hunk 4]
```diff
@@ -44,12 +44,13 @@ func OrgRedirect(cfg *setting.Cfg) web.Handler {
 			return
 		}
 
-		var queryString string = c.Req.URL.Query().Encode()
-		if strings.Contains(queryString, "kiosk=") && !strings.Contains(queryString, "kiosk=tv") {
-			queryString = strings.Replace(queryString, "kiosk=", "kiosk", -1)
+		urlParams := c.Req.URL.Query()
+
+		if urlParams.Has("kiosk") && urlParams.Get("kiosk") == "" {
+			urlParams.Set("kiosk", "true")
```
Comment (papagian) [inline pkg/middleware/org_redirect.go:50]: If you keep `kiosk` parameter it will still be encoded as `kiosk=`.
Instead you can do something like:
```suggestion
		qs := urlParams.Encode()
		if c.Req.URL.Query().Has("kiosk") {
			urlParams.Del("kiosk")
			qs = fmt.Sprintf("%s&kiosk", urlParams.Encode())
		}
```

File: pkg/middleware/org_redirect.go [hunk 5]
```diff
@@ -44,12 +44,13 @@ func OrgRedirect(cfg *setting.Cfg) web.Handler {
...
 		}
 
-		newURL := fmt.Sprintf("%s%s?%s", cfg.AppURL, strings.TrimPrefix(c.Req.URL.Path, "/"), queryString)
+		newURL := fmt.Sprintf("%s%s?%s", cfg.AppURL, strings.TrimPrefix(c.Req.URL.Path, "/"), urlParams.Encode())
```
Comment (papagian) [inline pkg/middleware/org_redirect.go:53]:
```suggestion
		newURL := fmt.Sprintf("%s%s?%s", cfg.AppURL, strings.TrimPrefix(c.Req.URL.Path, "/"), qs)
```

**Review by papagian — CHANGES_REQUESTED** [review]

File: pkg/middleware/org_redirect_test.go (hunk 3 above)
Comment (dessen-xu) [reply pkg/middleware/org_redirect_test.go:35]: sorry, I can not understand it, can you help me please.

Comment (marefr) [reply pkg/middleware/org_redirect_test.go]: I pushed some changes to resolve this.

**Review by papagian — APPROVED** [review]
Thank you for your contribution!

**Review by marefr — APPROVED** [review]
LGTM
