### PR TITLE
Variables: Fix url util converting `false` into `true`

### LINKED ISSUE #37403: Cannot pass a `false` value into a Variable through url query
# What happened:

Accessed `http://x.y/?var-booleanvar=false` and var-'s value was converted into `true` for `booleanvar` Variable.

# What you expected to happen:

Value of boolean`false` should have been passed into a Variable

# How to reproduce it (as minimally and precisely as possible):

Create Constant type Variable `a`.

Access http://x.y/?var-a=false

# Environment:

Grafana version: 8.1.beta-1

### PR DESCRIPTION
**Pull request by simPod**
**What this PR does / why we need it**:

A value of key-value pair is stripped for boolean values. While this is ok for `true`, it kind of inverts `false`

**Which issue(s) this PR fixes**:

Fixes #37403

### CODE REVIEW

File: packages/grafana-data/src/utils/url.ts [hunk 1]
```diff
@@ -45,7 +45,7 @@ function toUrlParams(a: any) {
 
   const add = (k: string, v: any) => {
     v = typeof v === 'function' ? v() : v === null ? '' : v === undefined ? '' : v;
-    if (typeof v !== 'boolean') {
+    if (typeof v !== 'boolean' || !v) {
```
Comment (hugohaggmark) [inline packages/grafana-data/src/utils/url.ts:48]: Sorry for the late response, but I just got back from summer vacation. Can we keep the existing logic and create an inclusive/explicit boolean logic instead of the else on line 50?

**Review by hugohaggmark — COMMENTED** [review]
Looks good but I added a suggestion

File: packages/grafana-data/src/utils/url.ts [hunk 2]
```diff
@@ -48,7 +48,8 @@ function toUrlParams(a: any) {
     if (typeof v !== 'boolean') {
       s[s.length] = encodeURIComponentAsAngularJS(k, true) + '=' + encodeURIComponentAsAngularJS(v, true);
     } else {
-      s[s.length] = encodeURIComponentAsAngularJS(k, true);
+      s[s.length] =
+        encodeURIComponentAsAngularJS(k, true) + (v ? '' : '=' + encodeURIComponentAsAngularJS('false', true));
```
Comment (hugohaggmark) [inline packages/grafana-data/src/utils/url.ts:52]: nitpick: I still think this code can be made more readable, maybe extract the value on a separate line?

**Review by hugohaggmark — APPROVED** [review]
The code looks ok; but I think it could be made more readable.

File: packages/grafana-data/src/utils/url.ts (hunk 2 above)
Comment (simPod) [reply packages/grafana-data/src/utils/url.ts]: aight, done

Comment (hugohaggmark) [reply packages/grafana-data/src/utils/url.ts]: Love it ❤️ , thank you for contributing to Grafana

**Comment by hugohaggmark** [comment]
@simPod seems the build is stuck, can you try to merge with master and push that? Let me know if you need any help.

**Comment by simPod** [comment]
@hugohaggmark I've rebased on master rn

**Comment by hugohaggmark** [comment]
> @hugohaggmark I've rebased on master rn

Awesome, build is building as expected now. Thank you 🙏

**Comment by hugohaggmark** [comment]
Thank you for contributing @simPod 🎉
