### PR TITLE
Live: do not show connection warning when on the login page

### LINKED ISSUE #33860: Live: Disconnect banner shown on login page
**What happened**:
Logout from Grafana and saw the disconnected banner. 
image
 
**What you expected to happen**:
To not see the disconnected banner. 

**How to reproduce it (as minimally and precisely as possible)**:
Visit the login page unauthenticated.

**Anything else we need to know?**:

**Environment**:
- Grafana version: main (1b36656455ee3c79cb5f219479197ac508eddbb8)
- User OS & Browser: Chrome and Firefox

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes https://github.com/grafana/grafana/issues/33860

this will now show a warning indicator when you are on the login page

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
Is there a better solution for this than relying on route path? Same problem shows when visiting the Forgot your password page and probably a few other.

File: public/app/features/live/LiveConnectionWarning.tsx [hunk 1]
```diff
@@ -44,24 +44,36 @@ export class LiveConnectionCorner extends PureComponent<Props, State> {
   render() {
     const { show } = this.state;
     if (show) {
-      return <div className={this.styles.corner} title="The server is disconnected" />;
+      if (!(window as any).grafanaBootData?.user?.isSignedIn) {
```
Comment (marefr) [inline public/app/features/live/LiveConnectionWarning.tsx:47]: Might want to use contextSrv.isSignedIn? 
https://github.com/grafana/grafana/blob/0d044285a9c646d4317f9f9da8694b70e7f9fc73/public/app/core/components/sidemenu/BottomSection.tsx#L12

**Review by marefr — APPROVED** [review]
LGTM, but see suggested improvement in comment
