### PR TITLE
Explore metrics: Fix long metrics and labels in landing page

### LINKED ISSUE #92411: Explore metrics: Bookmarks is still overflowing on homepage
When a metric name is too long, the bookmarks flow off the homepage (and the user requires horizontal scroll)

Image

### PR DESCRIPTION
**Pull request by bohandley**
Fixes https://github.com/grafana/grafana/issues/92411

What is this?

This is a bug fix for long metric names and labels in the landing page for Explore metrics.

Why?

Long metric names and labels break the Card components and for the UI to extend off the page, which allows the user to scroll outside the landing page window. This is a bad experience.

Previously

https://github.com/user-attachments/assets/984aaf7b-9a74-4436-bc9d-30f3b3fe9b9d

Now we word wrap long metrics and hide longer labels to prevent flowing beyond the page.

Screenshot 2024-09-04 at 9 01 48 AM

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/features/trails/DataTrailCard.tsx [hunk 1]
```diff
@@ -110,5 +110,18 @@ function getStyles(theme: GrafanaTheme2) {
...
 }
+
+function truncateLongLabels(filter: { key: string; value: string }, maxlength?: number, suffix?: string) {
+  suffix = suffix ?? '...';
+  maxlength = maxlength ?? 80;
+
+  const label = `${filter.key}: ${filter.value}`;
+
+  return label.slice(0, maxlength) + suffix;
+}
```
Comment (itsmylife) [inline public/app/features/trails/DataTrailCard.tsx:127]: Instead of this function if you'd add following into the `description` CSS class, it will do the same job.
Could you please try it out?

```
overflow: 'hidden',
textOverflow: 'ellipsis',
whiteSpace: 'nowrap',
```

Comment (bohandley) [reply public/app/features/trails/DataTrailCard.tsx]: Looks good!

**Review by itsmylife — APPROVED** [review]
