### PR TITLE
Jaeger: support running queries with keyboard shortcut

### LINKED ISSUE #36694: Make Trace ID query work from the keyboard only
**Steps to reproduce**:
Bring up Explore window; select trace data source; select Query Type: TraceID.
Enter something in Trace ID text field.
Try to initiate search using keyboard.
image

**Actual Result**:
Nothing happened on <kbd>Shift</kbd>+<kbd>Enter</kbd>

**Expected Result**
Shift-Enter should trigger a search for consistency with other queries I've used.
image
(Note <kbd>Ctrl</kbd>+<kbd>Enter</kbd> works there too, and seems more natural for me)

**Relevant WCAG Criteria:**
[2.1.1](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#keyboard)

**Environment**:
- Grafana version: Grafana v8.1.0-28167pre (b1d576c5da)
- Data source type & version: Tempo; not obvious how to get the version
- User OS & Browser: Windows 10; Chrome
- Others:

### PR DESCRIPTION
**Pull request by olbo98**
**What this PR does / why we need it**:
This PR adds support for running queries with <kbd>Shift</kbd>+<kbd>Enter</kbd> in Explore when using Jaeger.

**Which issue(s) this PR fixes**:

Fixes #36694

**Special notes for your reviewer**:
A plugin for running queries with <kbd>Shift</kbd>+<kbd>Enter</kbd> already exists in the `QueryField` component which is why it's been added to Jaeger

### CODE REVIEW

File: public/app/plugins/datasource/jaeger/components/QueryEditor.tsx [hunk 1]
```diff
@@ -32,16 +36,12 @@ export function QueryEditor({ datasource, query, onChange, onRunQuery }: Props)
         return (
           <InlineFieldRow>
             <InlineField label="Trace ID" labelWidth={21} grow>
-              <Input
-                aria-label={selectors.components.DataSource.Jaeger.traceIDInput}
```
Comment (ifrost) [inline public/app/plugins/datasource/jaeger/components/QueryEditor.tsx:36]: I think this aria-label is used by [a e2e test](https://github.com/grafana/grafana/blob/main/e2e/suite1/specs/trace-view-scrolling.spec.ts). You can try changing the test to something like we have in Prometheus (I haven't tested it though):

```diff
- e2e.components.DataSource.Jaeger.traceIDInput().should('be.visible').type('long-trace');
+ e2e.components.QueryField.container().should('be.visible').type('long-trace');
```

**Review by ifrost — CHANGES_REQUESTED** [review]

File: e2e/suite1/specs/trace-view-scrolling.spec.ts [hunk 2]
```diff
@@ -19,13 +19,14 @@ describe('Trace view', () => {
 
     e2e().contains('gdev-jaeger').scrollIntoView().should('be.visible').click();
 
-    e2e.components.DataSource.Jaeger.traceIDInput().should('be.visible').type('long-trace');
+    //e2e.components.DataSource.Jaeger.traceIDInput().should('be.visible').type('long-trace');
```
Comment (ifrost) [inline e2e/suite1/specs/trace-view-scrolling.spec.ts:22]: Seems to work fine. Can we remove the commented out code?

**Review by ifrost — CHANGES_REQUESTED** [review]

**Review by ifrost — APPROVED** [review]
