### PR TITLE
Loki: LogsTable fix - ad hoc filters getting added as wrong type on sparse fields

### LINKED ISSUE #116564: Explore: Loki Logs Table adding invalid ad-hoc filter with sparse fields.
### What happened?

When filtering a sparse field in Loki with the the Logs Table in Explore, we are currently only checking the label types for the first row in the data frame. This causes ad-hoc filters to get added incorrectly as indexed labels or as parsed fields, which can break queries which would otherwise be correct if given the correct label type.

### What did you expect to happen?

Adding an ad-hoc filter in the logs table in explore would not break the query.

### Did this work before?

No.

### How do we reproduce it?

Find a sparse field and add an ad-hoc filter to it:
1. Go to example on [play](https://play.grafana.org/goto/bfarnr28kqo00b?orgId=stacks-35611)
2. Click on the ad-hoc filter for `apache-bnhpr`

Image

3. See the filter get added as an indexed label instead of metadata

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

N/A

### Grafana platform?

None

### Datasource(s)?

Loki

### PR DESCRIPTION
**Pull request by gtk-grafana**
**What is this feature?**
Fixes unexpected behavior in ad-hoc filters in table in Explore which cause fields to get added as the wrong type.

**Why do we need this feature?**
To stop breaking queries when adding ad hoc filters on a sparse field.

**Who is this feature for?**
Loki users of the Table in Explore.

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/grafana/issues/116564

**Special notes for your reviewer:**
Ideally the `ToggleFilterAction` would contain the data frame value index so we don't need to iterate through the entire frame to find a value, but I only updated the instances of this method that are called on ad-hoc action, so any performance impact should be negligible.
This _shouldn't_ cause problems in explore since the table requires picking a single data frame and there isn't the ability to merge/transform frames by the user, but it's theoretically possible that a data frame defines multiple types for a single field and us grabbing the first label type for a particular label results in the wrong one getting grabbed, but since that still wouldn't work in the prior implementation either I think this PR is safe for merge as this PR will only decrease the likelihood of getting an invalid label type.

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/datasource/loki/languageUtils.ts [hunk 1]
```diff
@@ -93,16 +93,36 @@ export function isBytesString(string: string) {
...
+  }
+
+  if (index === null) {
+    index = typeField.values.findIndex((typeFieldValue) => typeFieldValue[labelKey]);
+  }
+
+  const valueTypes = typeField?.values[index];
   if (!typeField) {
     return null;
   }
```
Comment (L2D2Grafana) [inline public/app/plugins/datasource/loki/languageUtils.ts]: This code is duplicated above on line 113
```
if (!typeField) {
    return null;
  }
```

**Review by L2D2Grafana — APPROVED** [review]
LGTM. 
Not sure I found the right spare local data set to test this properly, but the tests are good and all the normal functionality is there.

File: public/app/plugins/datasource/loki/languageUtils.ts (hunk 1 above)
Comment (gtk-grafana) [reply public/app/plugins/datasource/loki/languageUtils.ts]: Good catch, fixed in https://github.com/grafana/grafana/pull/116566/commits/78c1d68ddbeb97f6704a6b3f02a10a438940f067

**Review by matyax — APPROVED** [review]
