### PR TITLE
Table: Fix units showing in footer after reductions without units

### LINKED ISSUE #81670: Table footer -> Count formats integer-counts as the units of the fields above (dollars etc)
This illustrates well the issue:

image

When configured with this:
image

The correct formatting in the footer would just say `4`, `4`, `2`, but instead it says `4 GiB` and `$4` for the first two value columns.

### PR DESCRIPTION
**Pull request by codeincarnate**
This PR fixes an issue in which table footer items will display units even in cases where the reduction will not preserve units. i.e. in cases where counts are applied of percentages are calculated.

This does so by adding a `preservesUnits` property to reducer registry items so that it's possible to determine if unit formatting should be applied after reduction.

Fixes #81670

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by nmarrs — APPROVED** [review]
Overall LGTM - not sure on edge case you're encountering with rounded percents (do you have a dashboard you can share to replicate that?)

In testing each reducer type the units are preserved / ignored as I would expect 👍 
[debug-Panel Title-2024-02-08 12_20_29.json.txt](https://github.com/grafana/grafana/files/14214319/debug-Panel.Title-2024-02-08.12_20_29.json.txt)

**Comment by nmarrs** [comment]
This [is the approach we've taken before](https://github.com/grafana/grafana/blob/ce57166c9a5047ae7898fdbe794b61fc89476a78/public/app/plugins/panel/xychart/XYChartPanel.tsx#L148) to address this (at least in XY Chart)

**Comment by codeincarnate** [comment]
Thanks for the review Nathan! Interesting that another go was taken at this. I'll follow up so that we can unify approaches. I believe we should go with the option presented here so that it can be handled in a uniform way regardless of usage.

File: packages/grafana-ui/src/components/Table/utils.ts [hunk 1]
```diff
@@ -385,10 +385,19 @@ export function getFooterItems(
...
   const calc = reducer[0];
-  const v = reduceField({ field, reducers: reducer })[calc];
-  return formattedValueToString(fmt(v));
+  const reducerInfo = fieldReducers.get(calc);
+  const format = field.display ?? getDisplayProcessor({ field, theme });
+  const fieldCalcValue = reduceField({ field, reducers: reducer })[calc];
+
+  // If the reducer preserves units then format the
+  // end value with the field display processor
+  if (reducerInfo.preservesUnits) {
```
Comment (codeincarnate) [inline packages/grafana-ui/src/components/Table/utils.ts:395]: Just wanted to leave a comment here that this would be the area to refactor and pull out into a separate function in this part so we can use in other places (i.e. XY chart, etc.)

**Comment by codeincarnate** [comment]
Oof, did run into one issue. Panel crashes when the reducer is undefined 😢. Fixing that now.

**Comment by codeincarnate** [comment]
Here's what I was seeing the the `Difference Percent"`option

Old: 
Screenshot 2024-02-12 at 2 10 55 PM

New:
Screenshot 2024-02-12 at 2 14 35 PM

Basically we've been applying at least some rounding to these numbers. This is a change in behavior, that being said this may be better suited as an option (like amount of precision). I can see arguments for rounding and for not rounding depending on use case. Would definitely be interested to thoughts on that 🙂

**Comment by codeincarnate** [comment]
Fix the issue when there's an undefined value for the footer 🥳

File: packages/grafana-data/src/transformations/fieldReducer.ts [hunk 2]
```diff
@@ -41,6 +41,7 @@ export interface FieldReducerInfo extends RegistryItem {
   // Internal details
   emptyInputResult?: unknown; // typically null, but some things like 'count' & 'sum' should be zero
   standard: boolean; // The most common stats can all be calculated in a single pass
+  preservesUnits: boolean; // Whether this reducer preserves units, certain ones don't e.g. count, distinct count, etc,
```
Comment (baldm0mma) [inline packages/grafana-data/src/transformations/fieldReducer.ts:44]: Thanks for the comment here.

**Review by baldm0mma — APPROVED** [review]
lgtm

**Comment by nmarrs** [comment]
Re: percent issue is there a way for us to set the resulting value's unit to percent? This reminds me of some work that we've done / issues that we ran into previously with an issue with [bar chart percent stacking](https://github.com/grafana/grafana/pull/79903/files) 😬

**Comment by codeincarnate** [comment]
@nmarrs cool, sounds good there. I'll go ahead and get this merged up :smile:
