### PR TITLE
Alerting: Fix label escaping in rule export

### LINKED ISSUE #71006: Alerting: File provisioning rule export endpoints should escape $variables
Context: https://github.com/grafana/grafana/issues/70484

Alerting file provisioning supports interpolation of environment variables using the `$variable` syntax in most fields. The file provisioning export endpoints should escape all instances of `$variable` to `$$variable` when found in a field that is interpolated. Raw un-interpolated strings are not saved in any fashion, so no need to worry about accidentally escaping a `$variable` that should be an environment variable.

### Example:

A rule with the following config:
```yaml
          annotations:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$3" $labels.name }}'
          labels:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$3" $labels.name }}'
```

should export to:
```yaml
          annotations:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$3" $labels.name }}'
          labels:
            instance: '{{ reReplaceAll "^(([^.]+\\.){3})([^.]+).+" "$$3" $$labels.name }}'
```

Since, annotations are not interpolated but labels are.

### PR DESCRIPTION
**Pull request by moustafab**
Labels are interpolated by file provisioning so any usage of `$` at the beginning of a word must be escaped.

The export api was not returning the labels with the escape characters, which caused the file provisioning to fail if you directly use the export from the api.

Fixes #71006, which is probably the root of #70484 and #95759

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: pkg/services/ngalert/api/compat.go [hunk 1]
```diff
@@ -223,11 +224,31 @@ func AlertRuleExportFromAlertRule(rule models.AlertRule) (definitions.AlertRuleE
 		result.Annotations = &rule.Annotations
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/api/compat.go:224]: The same must be done for annotations because they can contain templates too

File: pkg/services/ngalert/api/compat.go [hunk 2]
```diff
@@ -223,11 +224,31 @@ func AlertRuleExportFromAlertRule(rule models.AlertRule) (definitions.AlertRuleE
...
 	if rule.Labels != nil {
-		result.Labels = &rule.Labels
+		result.Labels = escapeLabelsForFileProvisioning(rule.Labels)
 	}
 	return result, nil
 }
 
+// this is to prevent the string from being interpreted as a variable in the provisioning engine
+func escapeLabelsForFileProvisioning(labels map[string]string) *map[string]string {
+	escapedLabels := make(map[string]string)
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/api/compat.go:234]: we know the size of the escaped labels, perhaps pre-allocate the map?

File: pkg/services/ngalert/api/compat.go [hunk 3]
```diff
@@ -223,11 +224,31 @@ func AlertRuleExportFromAlertRule(rule models.AlertRule) (definitions.AlertRuleE
...
+func addEscapeCharactersToString(s string) string {
+	// loop over words in the string and add escape characters to any word that starts with $
+	words := strings.Split(s, " ")
+	for i, word := range words {
+		if strings.HasPrefix(word, "$") {
+			words[i] = "$" + word
+		}
+	}
+	return strings.Join(words, " ")
+}
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/api/compat.go:250]: this logic skips strings like `test$A` as well as `$$$ABC`. I think the logic should be more straightforward and just replace every `$` with `$$`.

File: pkg/services/ngalert/api/compat.go [hunk 4]
```diff
@@ -223,11 +224,31 @@ func AlertRuleExportFromAlertRule(rule models.AlertRule) (definitions.AlertRuleE
...
+		result.Labels = escapeLabelsForFileProvisioning(rule.Labels)
 	}
 	return result, nil
 }
 
+// this is to prevent the string from being interpreted as a variable in the provisioning engine
+func escapeLabelsForFileProvisioning(labels map[string]string) *map[string]string {
+	escapedLabels := make(map[string]string)
+	for k, v := range labels {
+		escapedLabels[k] = addEscapeCharactersToString(v)
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/api/compat.go:236]: Keys should also be escaped.

File: pkg/services/ngalert/api/compat.go (hunk 1 above)
Comment (yuri-tceretian) [reply pkg/services/ngalert/api/compat.go:224]: Nevermind. Apparently, I am wrong here.

File: pkg/services/ngalert/api/compat.go (hunk 3 above)
Comment (moustafab) [reply pkg/services/ngalert/api/compat.go:250]: I think the environment templating on the file provisioning side doesn't replace those kinds of strings but I will double check the behavior. My goal was to get the same output that would when provided as input to file provisioning would result in a consistent result. Export -> import -> export should remain consistent. I think if I replace every `$` then we'd get an addition of `$` with every export.

File: pkg/services/ngalert/api/compat.go (hunk 4 above)
Comment (moustafab) [reply pkg/services/ngalert/api/compat.go]: After I tested the existing behavior, it looks like the label keys aren't interpolated. Apparently it's just the values https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/values/values.go#L177

File: pkg/services/ngalert/api/api_provisioning.go [hunk 5]
```diff
@@ -587,6 +588,77 @@ func exportResponse(c *contextmodel.ReqContext, body definitions.AlertingFileExp
...
+		ns.GroupWait = &escapedGroupWait
+	}
+	if ns.GroupInterval != nil {
+		escapedGroupInterval := addEscapeCharactersToString(*ns.GroupInterval)
+		ns.GroupInterval = &escapedGroupInterval
+	}
+	if ns.RepeatInterval != nil {
+		escapedRepeatInterval := addEscapeCharactersToString(*ns.RepeatInterval)
+		ns.RepeatInterval = &escapedRepeatInterval
+	}
```
Comment (yuri-tceretian) [inline pkg/services/ngalert/api/api_provisioning.go:643]: We can omit these lines because, if I am not mistaken, `$` is not a valid character in these fields.

File: pkg/tests/api/alerting/api_provisioning_test.go [hunk 6]
```diff
@@ -809,3 +813,70 @@ func createTestRequest(method string, url string, user string, body string) *htt
...
+		var expected definitions.AlertingFileExport
+		require.NoError(t, yaml.Unmarshal(fileProvisionedAlertRules, &expected))
+		expectedYaml, err := yaml.Marshal(expected)
+		require.NoError(t, err)
+
+		// create folder
+		folderUID := "my_first_folder_uid"
+		apiClient.CreateFolder(t, folderUID, "my_first_folder_with_$escaped_symbols")
+
+		err = os.WriteFile(filepath.Join(alertingDir, "provisioning-rules.yaml"), fileProvisionedAlertRules, 0750)
```
Comment (yuri-tceretian) [inline pkg/tests/api/alerting/api_provisioning_test.go:857]: I wonder if we should clean up after this test, so it won't affect other tests

File: pkg/tests/api/alerting/api_provisioning_test.go [hunk 7]
```diff
@@ -809,3 +813,70 @@ func createTestRequest(method string, url string, user string, body string) *htt
 	}
 	return req
 }
+
+func TestIntegrationExportFileProvision(t *testing.T) {
+	testinfra.SQLiteIntegrationTest(t)
```
Comment (yuri-tceretian) [inline pkg/tests/api/alerting/api_provisioning_test.go:818]: Why do we need to stick only to Sqlite tests?

**Review by yuri-tceretian — COMMENTED** [review]
Love the new test that covers the full cycle of file provisioning and export! Great job! 

Overall LGTM. Couple of questions, though.

File: pkg/tests/api/alerting/api_provisioning_test.go (hunk 6 above)
Comment (moustafab) [reply pkg/tests/api/alerting/api_provisioning_test.go:857]: I figured it didn't matter really for these rn, but I can add that to my follow up PR

File: pkg/tests/api/alerting/api_provisioning_test.go (hunk 7 above)
Comment (moustafab) [reply pkg/tests/api/alerting/api_provisioning_test.go:818]: Not sure, will double check that's necessary

**Review by yuri-tceretian — APPROVED** [review]
Tested and it works as expected. LGTM.
