### PR TITLE
Datasources: Improve error handling for error messages

### LINKED ISSUE #34013: Graphite: Authentication failure results in misleading error
Grafana master.
when you add a graphite datasource, but the auth is wrong, the UI says "HTTP error Bad Request"
web developer tools network inspector reveals the request to POST
	http://localhost:3000/api/datasources/proxy/1/render resulted ina response saying "Authentication to data source failed" (and it uses http code 400 which is not appropriate). see screenshot
screenshot-auth-error

### PR DESCRIPTION
**Pull request by ifrost**
**What this PR does / why we need it**:

This PR improves the way we handle errors when testing a data source results in failure (when clicking on "Test & Save" button).

So far the logic was to return `error.statusText` and fall back to `error.message` if no `statusText` is defined. In practice `error.statusText` is a more generic message and `error.message` should provide more detailed information. What is more the error might be returned in the response body in `error.data.message`. This PR changes that the error message is extracted from the first non-empty property in the following order:

- `error.message`
- `error.data.message`
- `error.statusText`

This should give more precise information about what happened.

**Which issue(s) this PR fixes**:

Fixes #34013

Backend changed the logic so in case of authentication errors  HTTP 401 is no longer returned but more appropriate in this case HTTP 400 with a message in the response body (see the issue for the explanation). This, however, means that the logic described above is picking up the status code for 400 (Bad Request) without additional info. By changing the way the error message is extracted we will get a more meaningful error.

**How to test it?**

Run `make devenv sources=graphite`. Create a Graphite data source. For given URLs you should get the following errors:

| URL | Error message |
|-----|----------------|
| https://graphite-us-central1.grafana.net/graphite | Authentication to data source failed |
| http://bad-gateway | Bad Gateway | 
| http://localhost:8180 | Data source is working |

for example:

Screenshot 2021-06-02 at 17 21 54

**Special notes for your reviewer**:

N/A

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Works great for Graphite, but not for other data sources. Would have been nice to include this in v8, but seems like too less time for that?

For example just trying to connect to Microsoft SQL Server data source without having it running I get this message:
image

Response payload looks like this:
```json
{
  "results": {
    "A": {
      "error": "db query error: failed to connect to server - please inspect Grafana server log for details",
      "frames": [
        {
          "schema": {
            "meta": { "executedQueryString": "SELECT 1" },
            "fields": []
          },
          "data": { "values": [] }
        }
      ]
    }
  }
}

```

And the MSSQL datasource then converting that response here:
https://github.com/grafana/grafana/blob/1c49986b2f2e36179159258517696353a5ea01c8/public/app/plugins/datasource/mssql/datasource.ts#L170-L177

This probably applies to any SQL data source and would guess basically any backend data source. For example all backend data sources basically using this code:
https://github.com/grafana/grafana/blob/1c49986b2f2e36179159258517696353a5ea01c8/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L209-L217

**Comment by ifrost** [comment]
Thanks @marefr! For Microsoft SQL Server I'm getting "Metric request error" (which is also not super helpful). MySQL is indeed returning just "400" though it's not related to changes in this PR but returned but the datasource API ([testDatasource()](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/mysql/datasource.ts#L191)). I just changed how exceptions thrown by `testDatasource` are handled.

It seems like the only way to fix all data sources is to check every data source one by one (probably also enterprise plugins). Might be also useful to update docs on how errors should be handled by data sources.

This PR still should improve the API in general and at least fix it for Graphite. Do you think it's worth merging it and then work on all data sources separately?

**Review by hugohaggmark — COMMENTED** [review]
I agree with @marefr and maybe we should use or create a similar function to `toDataQueryError` if that can't handle this scenario.
https://github.com/grafana/grafana/blob/43d3d9756285caec2621707471f7e08a86f6771e/packages/grafana-runtime/src/utils/queryResponse.ts#L136

**Comment by ifrost** [comment]
With 86cfd40 I added error handling for SQL datasources (mysql, mssql, postgres) and CloudWatch - all use `api/ds/query` to test the data source. Other errors (including HTTP errors) are re-thrown to be handled in `public/app/features/datasources/state/actions.ts`.

`toTestingStatus()` handles 2 types of errors returned by `api/ds/query`. Both can be tested with Microsoft Server SQL:
- create a new data source and click save (`api/ds/query` will return an object with `{ message, error }`)
- add database name and click save (`api/ds/query` will return empty query results with an error in `results.A.error`)

Out of curiosity - in ideal world, should all DataSourcesWithBackend implement health check endpoint and use it instead?

File: public/app/plugins/datasource/cloudwatch/datasource.ts [hunk 1]
```diff
@@ -881,10 +882,14 @@ export class CloudWatchDatasource extends DataSourceWithBackend<CloudWatchQuery,
...
-      message: 'Data source is working',
-    }));
+    return this.getDimensionValues(region, namespace, metricName, 'ServiceName', dimensions)
+      .then(() => ({
+        status: 'success',
+        message: 'Data source is working',
+      }))
+      .catch((error) => {
+        return toTestingStatus(error);
+      });
```
Comment (hugohaggmark) [inline public/app/plugins/datasource/cloudwatch/datasource.ts:892]: nit: can we use async/await instead?

**Review by hugohaggmark — APPROVED** [review]
Such splendid work on this, love that you added tests and comments. I haven't got the time to test it locally yet so I'll approve this for frontend platform. Maybe the individual data sources need to approve this works as expected.

File: public/app/plugins/datasource/cloudwatch/datasource.ts (hunk 1 above)
Comment (ifrost) [reply public/app/plugins/datasource/cloudwatch/datasource.ts]: Good point! Updated with 6b5efd6

**Comment by ifrost** [comment]
I had to remove returned value for `TestingStatus` in 1bd4266. `TestingStatus` lives in [`app/types/datasources`](https://github.com/grafana/grafana/blob/main/public/app/types/datasources.ts#L19) so cannot be imported directly to packages. Should it be moved somewhere else? `@grafana/data` or `@grafana/runtime` packages? On one hand it's returned by [`@grafana/data: DataSourceApi`](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/datasource.ts#L233) but on the other hand requires [`@grafana/runtime: HealthCheckResultDetails`](https://github.com/grafana/grafana/blob/main/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L62).

Any guidelines on where types for data sources should be defined?

**Comment by ifrost** [comment]
> Works great for Graphite, but not for other data sources. Would have been nice to include this in v8, but seems like too less time for that?

@marefr I've changed the implementation to cover SQL data sources, I hope it's better now 👍

**Comment by ifrost** [comment]
@sunker could you have a quick look if changes for CloudWatch make sense?

File: packages/grafana-data/src/types/datasource.ts [hunk 2]
```diff
@@ -472,7 +476,13 @@ export enum DataQueryErrorType {
 
 export interface DataQueryError {
   data?: {
+    /**
+     * Short information about the error
+     */
     message?: string;
+    /**
+     * Detailed information about the error
```
Comment (marefr) [inline packages/grafana-data/src/types/datasource.ts:484]:
```suggestion
     * Detailed information about the error. Only returned when app_mode is development.
```

File: packages/grafana-runtime/src/utils/queryResponse.ts [hunk 3]
```diff
@@ -127,6 +127,36 @@ export function toDataQueryResponse(
...
+ *
+ * If possible, this should be avoided in favor of implementing /health endpoint
+ * and testing data source with DataSourceWithBackend.testDataSource()
+ *
+ * @returns {TestingStatus}
+ */
+export function toTestingStatus(err: FetchError): any {
+  const queryResponse = toDataQueryResponse(err);
+  // POST api/ds/query errors returned as { message: string, error: string } objects
+  if (queryResponse.error?.data?.message && queryResponse.error?.data?.error) {
```
Comment (marefr) [inline packages/grafana-runtime/src/utils/queryResponse.ts:142]: I think this logic is wrong since error is only included when [app_mode](https://grafana.com/docs/grafana/latest/administration/configuration/#app_mode) is development. But I might be wrong since not sure if `toDataQueryResponse` somehow handles this case and always populates the `data.error`?

```suggestion
  if (queryResponse.error?.data?.message) {
```

File: packages/grafana-runtime/src/utils/queryResponse.ts [hunk 4]
```diff
@@ -127,6 +127,36 @@ export function toDataQueryResponse(
...
+    return {
+      status: 'error',
+      message: queryResponse.error.data.message,
+      details: { message: queryResponse.error.data.error },
```
Comment (marefr) [inline packages/grafana-runtime/src/utils/queryResponse.ts:146]: Based on earlier suggestion the details might not be included if `queryResponse.error.data.error` is undefined?

**Review by marefr — APPROVED** [review]
I think this looks good :+1: I've tested to connect to almost all core data sources without having their backend services running and seems to work as expected. Still a bit unsure if we're missing something for external plugins, but given they're returning `status` and `message` already it should be fine. Only possible case would be an unhandled exception, but guess it should fallback to `statusText`. I'll request a review from Ryan/Torkel just in case I've missed something.

Added some suggestions.

File: packages/grafana-data/src/types/datasource.ts [hunk 5]
```diff
@@ -228,7 +228,11 @@ abstract class DataSourceApi<
   abstract query(request: DataQueryRequest<TQuery>): Promise<DataQueryResponse> | Observable<DataQueryResponse>;
 
   /**
-   * Test & verify datasource settings & connection details
+   * Test & verify datasource settings & connection details (returning TestingStatus)
+   *
+   * When verification fails - errors specific to the data source should handled here and converted to
```
Comment (sunker) [inline packages/grafana-data/src/types/datasource.ts:233]:
```suggestion
   * When verification fails - errors specific to the data source should be handled here and converted to
```

**Review by sunker — APPROVED** [review]
Nice! Tested CloudWatch, Cloud Monitoring and Azure Monitor and it works as expected.

File: packages/grafana-data/src/types/datasource.ts (hunk 2 above)
Comment (ifrost) [reply packages/grafana-data/src/types/datasource.ts]: @marefr 👍 Added. Though I was getting it also when running in production mode, so maybe *sometimes* it's returned?

File: packages/grafana-runtime/src/utils/queryResponse.ts (hunk 4 above)
Comment (ifrost) [reply packages/grafana-runtime/src/utils/queryResponse.ts]: @marefr Good catch. Though, I think the end result would be the same because when `data.error` is not defined then `toTestingStatus` re-throws the error and the message is extracted from the error in `public/app/features/datasources/state/actions.ts`:

```typescript
const message = errMessage || data?.message || 'HTTP error ' + statusText;
```

I have changed it so when `data.error` is missing it's handled earlier, in `toTestingStatus`, it's probably more readable this way.

**Comment by ifrost** [comment]
> (...). I'll request a review from Ryan/Torkel just in case I've missed something.

@torkelo  / @ryantxu - could you have a quick look if these changes make sense?

File: packages/grafana-data/src/types/datasource.ts (hunk 2 above)
Comment (marefr) [reply packages/grafana-data/src/types/datasource.ts]: Hmm are you sure? I had this code in mind https://github.com/grafana/grafana/blob/4632b070e4a4c736698df61c18494902a9f7d209/pkg/api/response/response.go#L194. Possible that this is not used for all responses I suppose?

Comment (ifrost) [reply packages/grafana-data/src/types/datasource.ts]: Lemme check again 🔎

Comment (ifrost) [reply packages/grafana-data/src/types/datasource.ts]: Oh sorry, my bad! You're totally right - `data.error` is not returned in production mode 🤦 As discussed [below](https://github.com/grafana/grafana/pull/35120#discussion_r663755749) I have changed the logic to cover this case. Thanks!

**Review by ryantxu — APPROVED** [review]
LGTM

**Comment by Dieterbe** [comment]
thanks @ifrost :heart_eyes:
