### PR TITLE
Fix button "Run query" width (#32655)

### LINKED ISSUE #32655: Explore: Use fixed width for button "Run query"
**What would you like to be added**:

Please consider changing the width of the "Run query" / "Cancel" button to fixed instead of text-length depended, so it is always the same size.

**Why is this needed**:
When the query is executing, the elements to the left site are "wobbling" around, which is at least unpleasant to look at 😄 
If the query takes a second or if you click fast enough, you might actually misclick a wrong button, 

e.g. "Copy shortened link" instead of "time range backward", please see gif

G2PJ5PWgY1

### PR DESCRIPTION
**Pull request by glintik**
**What this PR does / why we need it**:

Fixes annoying UI bug with flutter of button width.

**Which issue(s) this PR fixes**:

Fixes #32655

### CODE REVIEW

File: packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx [hunk 1]
```diff
@@ -72,6 +76,7 @@ export class RefreshPicker extends PureComponent<Props> {
           variant={variant}
           icon={isLoading ? 'fa fa-spinner' : 'sync'}
           aria-label={selectors.components.RefreshPicker.runButton}
+          style={style}
```
Comment (mckn) [inline packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx:79]:
```suggestion
          fullWidth={true}
```

If we make the `ToolbarButton` to grow and take all of the unused space and set the constraint (width) on the `ButtonGroup` using `cx` and classNames. I think that would be a more elegant way of doing this and less prone to cause problems else where.

File: public/app/features/explore/RunButton.tsx [hunk 2]
```diff
@@ -36,6 +38,7 @@ export function RunButton(props: Props) {
       onRefresh={() => onRun(loading)}
       noIntervalPicker={!showDropdown}
       primary={true}
+      minWidth={minWidth}
```
Comment (mckn) [inline public/app/features/explore/RunButton.tsx:41]:
```suggestion
      width={!isSmall && '108px'}
```

Maybe reuse the already existing width property but only set it when it isn't small. Also, when I inspect the size of the button it should take `107.25px` instead so let's set `108px`.

File: packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx [hunk 3]
```diff
@@ -52,13 +53,16 @@ export class RefreshPicker extends PureComponent<Props> {
   }
 
   render() {
-    const { onRefresh, intervals, tooltip, value, text, isLoading, noIntervalPicker } = this.props;
+    const { onRefresh, intervals, tooltip, value, text, isLoading, noIntervalPicker, minWidth } = this.props;
```
Comment (mckn) [inline packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx:56]:
```suggestion
    const { onRefresh, intervals, tooltip, value, text, isLoading, noIntervalPicker, width } = this.props;
```

File: packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx [hunk 4]
```diff
@@ -52,13 +53,16 @@ export class RefreshPicker extends PureComponent<Props> {
...
 
     const currentValue = value || '';
     const variant = this.getVariant();
     const options = intervalsToOptions({ intervals });
     const option = options.find(({ value }) => value === currentValue);
     let selectedValue = option || RefreshPicker.offOption;
+    let style = {
+      minWidth: minWidth,
+    };
```
Comment (mckn) [inline packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx:65]:
```suggestion
const refreshPickerWidth = css`width: ${width}`;
```

File: packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx (hunk 1 above)
Comment (mckn) [reply packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx:79]: So in the `ButtonGroup` you should be able to pass a className lite below and it will only be applied when `width` has a truthy value.

```ts
      <ButtonGroup
        className={cx('refresh-picker', {
          refreshPickerWidth: !!width,
        })}
      >
```

**Review by mckn — COMMENTED** [review]
Left some comments on how to improve this. Thanks to @jackw for throwing some ideas around on how to solve this.

**Comment by jackw** [comment]
Thanks so much for making this contribution @glintik ! 🚀 

> One more css prop for this seldom used component is a fair price and it doesn't create any mess.

I believe the aim of @mckn approach was to minimise changes to the APIs by reusing already existing props and isolate where the width is set without needing to push it down to the `ToolbarButton`. We have to always keep in mind that with public APIs we are not able to change them easily. The result is pretty much the same but moves where the `min-width` is set higher up the tree.

> Mixing of min-width with width creates a mess for any developer and can result in various bugs.

Maybe I'm misunderstanding this statement but setting a `min-width` on a button element as you already highlighted is a more flexible solution to setting the `width`. Right now the `width` prop already exists in the component API but isn't being used. We're now proposing using it to set the `min-width` of the element. I'm not sure what bugs this would introduce.

**Comment by glintik** [comment]
@jackw ToolbarButton class is not touched at all. No API is changed while some props just were added.
I think, we spend too much time discussing about so little changes for this bug fix and this thread becomes a perfect example of how to kill any developer motivation.

File: packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx (hunk 4 above)
Comment (torkelo) [reply packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx:65]: not sure this is better, only slower

**Comment by torkelo** [comment]
ah, this is a great PR, I have been annoyed by this jumping button for ages and was about to try to fix this yesterday! 
I would use the already existing (not used) width property on RefreshPicker, 
https://gist.github.com/torkelo/bcf1e5d2ad466bd77602dfdf41dfe648 

It's a bit of a hack and not the most elegant but it's simple and think this is a bit of an edge case. And it does not introduce any new complexity to ToolbarButton or ButtonGroup.

**Review by torkelo — APPROVED** [review]

**Review by torkelo — APPROVED** [review]

**Review by mckn — APPROVED** [review]
LGTM!
