### PR TITLE
Routing: Replace Angular routing with react-router

### LINKED ISSUE #31548: Epic: routing migration
Ref #31463

### `AppWrapper` component
This component is the main wrapper of the entire Grafana app. 

Responsibilities:
- Providers rendering
- App shell & overlay layers(notifications, search) rendering 
- Routes rendering
- Angular app bootstrap - we can't get rid of this yet as we still have plenty of services to migrate, as well as loads of plugins are still implemented in Angular

#### Routes rendering
Routes are rendered as react-router-dom Route components. Under the hood react-router-dom routes are rendering a Grafana route abstraction, `GrafanaRoute`, which is the de-facto page renderer. This allows us to sync Redux `location` slice with the current location of the history. It's also a chance for us to intercept any location changes with side effects i.e. force login, or redirects when a user does not have a role allowing him/her to access the current route. *While the redirect is there to live, I consider moving the side effect to `updateLocation` action instead*

##### `GrafanaRoute`
This component manages the lifecycle of a given page route as well as renders the page itself.

Interface:
```ts
export interface GrafanaRouteProps<T, Q = any> extends RouteComponentProps<T> {
  component: () => React.ComponentType<GrafanaRouteComponentProps<T>>;
  route: RouteDescriptor;
  $injector: any; // TODO[Router]: annotate correctly
}
```

Each GrafanaRoute gets all react-router Route props as well as page component, the route model (`RouteDescriptor`) and Angular's injector(some pages, i.e. DashboardPage..., rely on the injector to retrieve Angular services). It's also responsible for body page class modification as well as DOM cleanups (previously implemented in the GrafanaCtrl via angular route events, $routeChangeSuccess).

### Routes definition
All routes definition are now represented by `RouteDescriptor` interface and as previously defined in the `routes.tsx` file:
```
export interface RouteDescriptor {
  path: string;
  component: () => React.ComponentType<GrafanaRouteComponentProps<any>>;
  reloadOnSearch?: boolean;
  roles?: () => string[];
  pageClass?: string;
  routeInfo?: string;
}
```

This interface builds on top the Angular's model and alters it to React needs. 
- `reloadOnSearch` - leaving this as it is now, as we heavily depend on the query parameters in the navigation and this helps us manage the unnecessary re-render of the pages in the `GrafanaRoute`(see `shouldComponentUpdaye` implementation)
- `roles`, `routeInfo`, `pageClass` - behavior is not changing

**TODO**

### Navigating in the app
**Think this is the most important thing to decide on currently**, as it will affect migration a lot.

#### Current ways to navigate
- `updateLocation` Redux action that is bridged to Angular router(and vice versa)
- `locationSrv` - runtime service that under the hood dispatches the `updateLocation`action

#### Proposal
The current way, driven by the need for Angular-Redux sync, introduces quite a complexity in the shape of the `BridgeSrv`.

With react-router we are fortunate to be able to use custom history object and get access to its API via service. Hence I'm introducing a secondary `LocationService` in this PR, which under the hood wraps the history API. The service is responsible for history initialization, which is then used by react-router `Router` component. Also, it exposes a (WIP) API for imperative navigation:

```ts
// Backwards compatibility for Angulars's $location service, picked methods are the ones we actually use
interface AngularLocationProviderAPI extends Pick<ILocationService, 'path' | 'hash' | 'url' | 'search'> {}

export interface LocationService extends AngularLocationProviderAPI {
  partial: (query: Record<string, any>, replace?: boolean) => void;
  push: (location: H.Path | H.LocationDescriptor<any>) => void;
  replace: (location: H.Path) => void;
  getCurrentLocation: () => H.Location;
  getHistory: () => H.History;
}
```

As you can see this service is to implement parts of Angular's `ILocationService` that will enable backward compatibility for the plugins that use Angular's `$location` service. See [Bridging Angular-React gap](#bridging-angular-react-gap) for some more details.

For anchor navigation, since it's wildly used all over the place, the quick way would be to replace all `<a ...` with react-route `Link` components, but this would take a lot of time and would be super error-prone. Additionaly, all Angular plugins   would stop working. To mitigate this I'm intercepting all link clicks with a custom handler, that under the hood uses the `LocationService` described above:

```ts
export function interceptLinkClicks(e: MouseEvent) {
  const target = e.target as HTMLElement;
  if (target && target.tagName === 'A') {
    const href = target.getAttribute('href');

    if (href) {
      navigationLogger('utils', false, 'intercepting link click', e);
      e.preventDefault();
      getLocationService().push(href);
    }
  }
}

```

### Bridging Angular-React gap
Grafana, and most probably the plugins, extensively use Angular's `$location`, `$route` and `$routeParams` services. We could replace all of the usages of these usages with the `LocationService` counterparts, yet we would most probably end up with unforeseen bugs. To mitigate the risk I'm proposing patching above Angular's services to bridge its calls to `LocationService`(hence it implements part of the Angular's `$location` API):

```ts
// Intercepting $location service with implementation based on history
const interceptAngularLocation = () => {
  // debugger;
  coreModule.config([
    '$provide',
    ($provide: any) => {
      $provide.decorator('$location', [
        '$delegate',
        ($delegate: any) => {
          $delegate = getLocationService();
          return $delegate;
        },
      ]);
    },
  ]);
  coreModule.provider('$route', RouteProvider);
  coreModule.provider('$routeParams', RouteParamsProvider);
};
```

### ~Syncing history with Redux `location` slice for backward compatibility~

~Redux `location` slice is used extensively across Grafana's react code to retrieve the current location. While there is nothing wrong with this, I strongly want to rely on the history state as much as possible in the future instead of the Redux state to reduce the complexity and unnecessary duplication. While Redux location state makes sense to core Grafana, it's useless for plugins. I believe the history of the `LocationService` should be the only source of truth.

The same goes about the `updateLocation` Redux action. Instead of relying on dispatching a Redux action, I suggest using the `LocationService` API directly. `GrafanaRoute` component will make sure that the Redux location state is in sync with the history, and all current page components that rely on `state.location` mapping will continue working. 

*Mind that in this PR dispatching `updateLocation` action will not result in the navigation, but state update only!!!*

The proposed (I consider it a temporary) data flow is:
1. react-router Route is hit
2. `updateLocation` action is dispatched to keep the state in sync
3. Page component can read from store and retrieve the location state, and render~

The *desired* data flow in the future:
1. React-router Route is hit
2. Page component retrieves the entire location state via props.  All page components already receive the entire set of route props(see `GrafanaRouteProps`). We just need to be more strict about page props typings so that the props interface extends the `GrafanaRouteProps` type.

### PR DESCRIPTION
**Pull request by dprokop**
# Migration to react-router

**See https://github.com/grafana/grafana/issues/31548 for proposal description**

This PR introduces POC for long waiting migration of Grafana's routing from Angular to react-router.

References:
- https://reactrouter.com/web/guides/philosophy
- https://github.com/ReactTraining/history/tree/v4.10.1
- Test list of all Grafana routes is available under http://localhost:3000/router-debug

## TODOs
- [x] Link click intercepting: handle link `target` attribute
- [x] Migrate $routeXXX (`$routeChangeSuccess`, `$routeChange`) events 🏃 @dprokop 
  - [x] Get rid of `$routeChangeSuccess`:  Used in `KeybindingSrv` and `BridgeSrv`
  - [x] Get rid of `$routeChange`:  Used in `TimeSrv`
- [ ] implement `RouteParamsProvider`
- [ ] implement `RouteProvider`
- [ ] implement Angular $location compat API methods in the `LocationService` https://github.com/grafana/grafana/pull/31773
	- [x] `path`
	- [x] ~`hash`~
	- [x] `search`
	- [x] `url`
	- [ ] make sure all of the above implementations are marked as deprecated and have deprecation warnings
	- [ ] remove usages or injected $location provider
- [x] replace `updateLocation` usage with `LocationService` API
- [x] Make it work when under sub path (serve_from_sub_path) 🏃 @torkelo
- [x] Figure out how to open search (and where)
- [x] How to hide sidemenu in kiosk (SideMenu is direct child of Router and not re-rendering when query param change, the  Route is but not Router children) 
- [ ] POC API for AppPlugins
- [ ] List popular Angular plugins using `$route`, `$routeParams` and `$location` services
https://github.com/ReactTraining/history/blob/v4.10.1/docs/Blocking.md
- [ ] Bring back services:
	- [x] `TimeSrv` - still dependant on `$location`
	- [x] `KeybindingSrv`
	- [x] `ChangeTracker`
	- [x] `BridgeSrv` - is it going to be still needed?
	- [x] `DashboardLoaderSrv` https://github.com/grafana/grafana/pull/31863
	- [ ] And more to come:)
- [x] Bring back `checkBrowserCompatibility`
- [x] Bring back `monkeyPatchInjectorWithPreAssignedBindings`
- [ ] Migrate playlist routes
	- [ ] Migrate playlist views to React (ref https://github.com/grafana/grafana/issues/21484)
- [x] Remove ReactContainer
- [x] Use AppNotificationsList instead of angular directive in  AppWrapper
- [x] Use DashboardSearch instead of the Angular directive in  AppWrapper
- [x] Make sure `?orgId` is persisted in the URL when navigating
- [x] Fix warning: `react-dom.development.js:67 Warning: Cannot update a component (`Connect(SignIn)`) while rendering a different component (`Router.Consumer`). To locate the bad setState() call inside `Router.Consumer`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render` when signing out
- [x] Migrate enterprise routes
- [ ] Verify all routes migrated
- [x] `createMemoryHistory` import sows a warnign both in tests and in the runtime: image

Pages
- [x] Dashboad
   - [x] Restoring dashboard version throws an error: `TypeError: $route.reload is not a function at RevertDashboardModal` 🏃 #31683
   - [x] undefined scope for initDahboard cannot be rootScope 
   - [x] Kiosk mode in DashNav
   - [x] Navigating back from Dashboard Settings does not close the settings
   - [x] Investigate blocking navigation, i.e. for the Dashboard change tracker 
   - [x] DashboardWatcher (websocket events) is using $route.reload 🏃 #31683
- [x] SoloPanel 
- [x] Manage dashboards
- [x] Import dashboard page
- [x] New folder page 
- [x] Manage folder
- [x] Folder settings
- [x] Folder permissions 
- [x] Explore 
- [x] Snapshot list (Strange double url in the list) 
- [x] Playlist list (needs angular to react migration) 
- [ ] Playlist list edit (needs angular to react migration) 
- [x] DatasourceSettingsPage 
- [x] DataSourceSettings Tabs (Dashboards) 
- [x] Org Users
- [x] Alert Rules List
- [x] Alert Notification Channel List
- [x] Alert Notification Channel Edit/New
- [x] Teams List
- [x] New Team 
- [x] Team settings
- [x] Server admin > Edit user
- [x] Server admin > Edit org
- [x] Server admin > Ldap
- [x] Plugins page (Readme & Config etc)  
- [x] Not found page
- [x] Reset Password
- [x] Invite page

Enterprise
* [x] Report list
* [x] Edit/new report
* [x] Data source permissions
* [x] Team group mappings 

## Backlog:
* [ ]  Route reload in dashboard page - think about "cleaner" way of handling forced reloads, ref https://github.com/grafana/grafana/pull/31683
uploadDashboardDirective - refactor to React (used in cloud-monitoring ds)
- [ ]  Singlestat - remove the panel (using $location, i't to be depracated in v8)
- [ ] HistoryListCtrl - to be removed in @jackw DashboardSettings migration work (using $location)

### CODE REVIEW

**Comment by hugohaggmark** [comment]
This is so huge, impressive description and hypothesis, I need to spend some quality time reading it through again. 
Initial thought just by reading through the description once: 
- Is the added complexity on level with the upsides React Router gives us? 
- One thing that surfaces in your excellent problem statement/description is the urgency to deprecate Angular plugins first.

**Review by hugohaggmark — COMMENTED** [review]
This is so huge, impressive description and hypothesis, I need to spend some quality time reading it through again.
Initial thought just by reading through the description once:

- Is the added complexity on level with the upsides React Router gives us?
- One thing that surfaces in your excellent problem statement/description is the urgency to deprecate Angular plugins first.

File: public/app/core/AppWrapper.tsx [hunk 1]
```diff
@@ -0,0 +1,161 @@
...
+            return null;
+          }
+
+          store.dispatch(
+            updateLocation({
+              path: props.location.pathname,
+              routeParams: props.match.params,
+              query: queryStringToJSON(props.location.search),
+            })
+          );
```
Comment (torkelo) [inline public/app/core/AppWrapper.tsx:96]: Calling a redux action during rendering seems bad. Is there a callback on Route that we can hook into instead?

Comment (dprokop) [reply public/app/core/AppWrapper.tsx:96]: Indeed, that's gonna land in the `GrafanaRoute` component lifecycle.

Comment (dprokop) [reply public/app/core/AppWrapper.tsx]: @torkelo thought about this a bit and my conclusion is to keep it in the render cycle. I've moved it to `SyncLocationWithRedux` intermediate component to make sure the dispatch happens before the component is rendered. I know it feels a weird pattern but the render is predictable here as it should happen only on route changes/matches. See the test and implementatin in 5eb4c5f.

Alternatively, we could hack something around the history.listen and use react-routers matchPath (https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L38). But again the problem is we don't have the path to match the location against in that listener.

File: public/app/core/AppWrapper.tsx [hunk 2]
```diff
@@ -0,0 +1,141 @@
...
+          }
+
+          return (
+            <SyncLocationWithRedux {...props}>
+              <GrafanaRoute
+                {...props}
+                component={route.component}
+                route={route}
+                $injector={this.state.ngInjector}
+                $contextSrv={contextSrv}
```
Comment (torkelo) [inline public/app/core/AppWrapper.tsx:90]: we do not need this, it's a public singleton and not an angular service (it is but that is only for old angular components)

Comment (dprokop) [reply public/app/core/AppWrapper.tsx:90]: yes, it's on TODOs to remove

File: public/app/core/AppWrapper.tsx (hunk 1 above)
Comment (torkelo) [reply public/app/core/AppWrapper.tsx]: ok, looks good. As long as we do not get warnings that we are updating state during rendering, but should not as this is redux state not react component state

Comment (dprokop) [reply public/app/core/AppWrapper.tsx]: The more I explore this the more I think I'll just remove the location from redux altogether. The above introduces loads of react warnings(same as the previous approach) and looking at flips implemented in https://github.com/supasate/connected-react-router it only makes me more confident this complexity does not bring us much.

Comment (torkelo) [reply public/app/core/AppWrapper.tsx]: flips?

Comment (dprokop) [reply public/app/core/AppWrapper.tsx]: Flips, tricks, you name it:)

File: public/app/app.ts [hunk 3]
```diff
@@ -89,11 +104,12 @@ export class GrafanaApp {
 
   init() {
     const app = angular.module('grafana', []);
-
     addClassIfNoOverlayScrollbar();
+    setViewModeBodyClass(queryStringToJSON(getLocationService().getCurrentLocation().search).kiosk as KioskUrlValue);
```
Comment (torkelo) [inline public/app/app.ts:104]: would be nice to build queryStringToJSON into LocationService, so we can just do locationService.getQueryParms() or something

File: packages/grafana-runtime/src/services/LocationService.ts [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+import * as H from 'history';
+
+// Backwards compatibility for Angulars's $location service, picked methods are the ones we actually use
+interface AngularLocationProviderAPI extends Pick<ILocationService, 'path' | 'hash' | 'url' | 'search'> {}
+
+export interface LocationService extends AngularLocationProviderAPI {
+  partial: (query: Record<string, any>, replace?: boolean) => void;
+  push: (location: H.Path | H.LocationDescriptor<any>) => void;
+  replace: (location: H.Path) => void;
+  getCurrentLocation: () => H.Location;
```
Comment (torkelo) [inline packages/grafana-runtime/src/services/LocationService.ts:11]:
```suggestion
  getLocation: () => H.Location;
```

Nitpick: Just expect us to write this a lot, and the current word seems surperflous

**Comment by torkelo** [comment]
Been making some progress
* Been updating some updateLocation redux actions to LocationService calls.  
* initDashboard now handles redirects using LocationService , need to update tests, but waiting with that as I have an idea for how to improve LocationHistory + unit testing
* Fixing some typescript errors 
* Fixed issues after merge with master (Due to library panel PR merge)
* Moved the angular location wrapper out of the main LocationService into a separate class so the LocationService interface can be cleaner

**Comment by torkelo** [comment]
Did two more changes
*  Moved LocationService to runtime as it had no dependency other than history, and makes it easier to use in tests (now automatically uses in memory history in tests), and it is exported as a const package singleton instead of a getXX function as I think that just hearts readability without any gains. https://github.com/grafana/grafana/pull/31523
* Started moving angular stuff out of main app into it's own folder, just a start, need to move much more https://github.com/grafana/grafana/pull/31525

**Comment by torkelo** [comment]
Fixed issue with the anchor click document listener, did not capture (prevent default) clicks inside anchors (when you clicked on svg, or inner div)

**Comment by torkelo** [comment]
Moved AppWrapper to root, want to limit circular dependencies where we have things under app/core that depend on things outside app/core, think app/core should be only services and components and not have any dependencies outside app/core. 

Also moved the angular to react bridge (the fake angular services) to the new app/angular folder, the thinking is to move all angular stuff (directives and panel/plugin info to this folder, but think we can wait with that until after this is merged so limit the potential for merge conflicts).

**Comment by torkelo** [comment]
Another update: 

* Tried to update AlertRuleList to use location (search) provided GrafanaRouteComponentProps, discovered its not getting a new location object as GrafanaRoute is not re-rendering the route due to reloadOnSearch 
* Removed all the reloadOnSearch properties as this should no longer be needed, React will by default not unmount the component if it stays the same
* After removing reloadOnSearch I discovered that the way GrafanaRoute renders components they get unmounted and mounted for every url or query update no matter if it's the same path and component 
* The problem with unmount on every update is due to SafeDynamicImport it's causing React to detect a new component every render, tried to remove it and replace it with just AlertRuleList and no more unmounts on every url update (state  query parameter is in url for this page). 

Tried to memoize the component(), tried to cache the result but still when re-rendering a SafeDynamicImport component it always causes the underlying component to unmount & mount

**Comment by torkelo** [comment]
Figured out why GrafanaRoute caused unmounts for every URL update even when the path/component was the same. 

The signature for SafeDynamicImport was so that it always created a new LoadableComponent  which caused all route re-renders to unmount the component. But if we change the signature to:

```ts
export const SafeDynamicImport = (loader: () => Promise<any>): GrafanaRouteComponent =>
  Loadable({
    loader: loader,
    loading: loadComponentHandler,
  });
```
That means this function will be called ONCE when we define the route descriptor and we will just have defined one Loadable per route (before the way this function was defined it was called for every render and hence creating a new Loadable every route render). Had to update ever route to move the arrow function. This means that the RouteDescriptor can now look like this:

```ts
export interface RouteDescriptor {
  path: string;
  component: GrafanaRouteComponent<any>;
  roles?: () => string[];
  pageClass?: string;
  routeName?: string;
}
```

That is the component prop is no longer a function just a component (That gets assigned a Loadable to handle the dynamic load)

**Comment by torkelo** [comment]
Updated DashboardPage & DataSourceSettingsPage to use router match params and location.search instead of redux location

**Comment by hugohaggmark** [comment]
> Figured out why GrafanaRoute caused unmounts for every URL update even when the path/component was the same.
> 
> The signature for SafeDynamicImport was so that it always created a new Loadable Component which caused all route re-renders to unmount the component. But if we change the signature to:
> 
> ```ts
> export const SafeDynamicImport = (loader: () => Promise<any>): GrafanaRouteComponent =>
>   Loadable({
>     loader: loader,
>     loading: loadComponentHandler,
>   });
> ```
> 
> That means this function will be called ONCE when we define the route descriptor and we will just have defined one Loadable per route (before the way this function was defined it was called for every render and hence creating a new Loadable every route render). Had to update ever route to move the arrow function. This means that the RouteDescriptor can now look like this:
> 
> ```ts
> export interface RouteDescriptor {
>   path: string;
>   component: GrafanaRouteComponent<any>;
>   roles?: () => string[];
>   pageClass?: string;
>   routeName?: string;
> }
> ```
> 
> That is the component prop is no longer a function just a component (That gets assigned a Loadable to handle the dynamic load)

Brilliant catch! 🎉

**Comment by dprokop** [comment]
@torkelo great progress, thanks for the help !

**Comment by dprokop** [comment]
Moved proposal description to https://github.com/grafana/grafana/issues/31548

**Comment by hugohaggmark** [comment]
Impressed with the progress you're making here 💥

**Comment by dprokop** [comment]
@hugohaggmark thanks!

File: public/app/core/services/keybindingSrv.ts [hunk 5]
```diff
@@ -171,8 +163,10 @@ export class KeybindingSrv {
   }
 
   showDashEditView() {
-    // const search = _.extend(this.$location.search(), { editview: 'settings' });
-    // this.$location.search(search);
+    locationService.partial({
+      ...locationService.getSearchObject(),
```
Comment (torkelo) [inline public/app/core/services/keybindingSrv.ts:167]: why? the partial does this already

**Comment by torkelo** [comment]
@dprokop I wrote a test for GrafanaRoute passing it location, history, match etc, wanted test that it parsed the location search into queryParams but the test did not pass due to GrafanaRoute not using props.location.search but calling locationService and it checking it's internal history.location.search.

So broke out the code in getSearchObject into a package level util function, locationSearchToObject so now GrafanaRoute can do:

```tsx
  return <RouteComponent {...props} queryParams={locationSearchToObject(props.location.search)} />;
```

this way it does not use any global state (which makes the test a bit cleaner)

File: public/app/core/navigation/parseKeyValue.ts [hunk 6]
```diff
@@ -0,0 +1,165 @@
+// tslint:disable
```
Comment (torkelo) [inline public/app/core/navigation/parseKeyValue.ts:1]: @dprokop can't see this file used anywhere, do you remember where this was used? maybe something I accidentially removed?

**Comment by dprokop** [comment]
> @dprokop I wrote a test for GrafanaRoute passing it location, history, match etc, wanted test that it parsed the location search into queryParams but the test did not pass due to GrafanaRoute not using props.location.search but calling locationService and it checking it's internal history.location.search.
> 
> So broke out the code in getSearchObject into a package level util function, locationSearchToObject so now GrafanaRoute can do:
> 
> ```tsx
>   return <RouteComponent {...props} queryParams={locationSearchToObject(props.location.search)} />;
> ```
> 
> this way it does not use any global state (which makes the test a bit cleaner) 
> 
> 

Of course, super stupid of me 🙈

File: public/app/core/navigation/parseKeyValue.ts (hunk 6 above)
Comment (dprokop) [reply public/app/core/navigation/parseKeyValue.ts:1]: Nope, this can be removed. I haves moved the function to utils file and forgot to delete the file

**Comment by dprokop** [comment]
@torkelo fixed Kiosk modes and aded tests

**Comment by torkelo** [comment]
nice

**Comment by dprokop** [comment]
And fixed some more type check issues.

**Comment by torkelo** [comment]
@dprokop had forgotten to submit my PR review of https://github.com/grafana/grafana/pull/31683 

Not that important but do not think we need to complicate LocationService.replace method like that for and edge case (especially add boolean function param feels like it will make that function hard to extend in the future). And feels unnecessary as the state can already be sent in in

**Comment by dprokop** [comment]
> Not that important but do not think we need to complicate LocationService.replace method like that for and edge case (especially add boolean function param feels like it will make that function hard to extend in the future). And feels unnecessary as the state can already be sent in in

@torkelo that's on purpose. My thinking was that it will be easier to refactor out from this reload logic when we figure out another way(preferably react-first) by just removing this property in the replace fn signature rather than looking for al usages of state that may come.

**Comment by torkelo** [comment]
> . My thinking was that it will be easier to refactor out from this reload logic when we figure out another way(preferably react-first)

How so? This is only used in DashboardPage, why should LocationService & GrafanaRoute be involved?

**Comment by dprokop** [comment]
> by just removing this property in the replace fn signature

And ts will show us all usages. And we have a stable state key thanks to that, so that GrafanaRoute can do the removal ((this.props.history.location.state as any)?.forceRouteReload;) 

But I may be wrong. My thinking is that `locationService.replace({pathname: newUrl, state: { reload: true })` is cryptic when readding the code compared to a verbose `forceRouteReload` param suggestion when using the replace fn.

**Comment by torkelo** [comment]
From my research, there does not exist a more React first solution to reloading the same route, other than switching route path and then back. Or update location state to trigger a route re-render and then handle the reload in the route component like you did.

**Comment by dprokop** [comment]
@torkelo I wasn't clear. When I said `when we figure out another way(preferably react-first)` I had differently constructed routes that maybe do not use query params for navigation. I believe we could do that with nested Route component's in the dashbaord page, but I have not looked into this yet. This would we could create backwards compatibility routes map but this wouldn't work if you used link in a lower version in grafana. Not sur ehow popular this is, but still there's a risk.

**Comment by torkelo** [comment]
Some good progress
* Admin > user edit page
* Admin > org edit page
* Admin > Ldap page
* Import dashboard page
* New folder page 
* Data source settings > dashboards tab

**Comment by torkelo** [comment]
I moved check browser compatability from app init and to index html file (javascript) and from using app notification to using native alert. This way it will actually work for old browsers, many old browsers will simply fail to load the app and so our old browser compatibility alert did not work that well, only for modern browsers that could boot the app but maybe missed some css features. Now if the app fails to boot they will still see this alert that their browser is too old.

**Comment by torkelo** [comment]
Fixed 
* Not found page (default wildcard route)
* Reset password page
* Signup invite page

**Comment by torkelo** [comment]
No usages of updateLocation now in oss, so made a start for enterprise routes https://github.com/grafana/grafana-enterprise/pull/1129

**Comment by torkelo** [comment]
Started work on the playlist list view & start route, but not sure how much time I can spend on that today

**Comment by mckn** [comment]
I have done some testing and can't find anything that doesn't work as I expected, great work on this! For me, the navigation feels snappier.

**Review by Clarity-89 — COMMENTED** [review]
Impressive work! Tested most of the routes and only found two issues:
1. The annotations page is missing in dashboard settings
2.  Pressing `New API key` from `Configuration > API Keys` redirects to the home page instead of opening the SlideDown.

Also left a bunch of minor comments, not sure if all of them are relevant to this PR as it seems some changes are not directly related to the new routing.

File: packages/grafana-runtime/src/services/LocationService.ts [hunk 7]
```diff
@@ -0,0 +1,155 @@
...
+      } else {
+        debugGlobal = {
+          location: this,
+        };
+      }
+      // @ts-ignore
+      window['_debug'] = debugGlobal;
+    }
+
+    this.partial = this.partial.bind(this);
```
[the remark this answers is not in the document]
Comment (torkelo) [reply packages/grafana-runtime/src/services/LocationService.ts:56]: This seems likes the most optimal way to bind class functions, using arrow functions create 100% new functions in constructor, But mainly it's because I hate mixing arrow functions and norma prototypee functions, I find it just makes the code a lot messier when I see a class with some prototype functions and some arrow instance functions. So moved this to using this method to keep all functions looking the same. But I actually think we can remove these binds, don't think they are needed

File: public/app/AppWrapper.tsx [hunk 8]
```diff
@@ -0,0 +1,112 @@
...
+    }
+  }
+
+  bootstrapNgApp() {
+    const injector = this.props.app.angularApp.bootstrap();
+    this.setState({ ngInjector: injector });
+  }
+
+  renderRoute = (route: RouteDescriptor) => {
+    const roles = route.roles ? route.roles() : [];
```
[the remark this answers is not in the document]
Comment (torkelo) [reply public/app/AppWrapper.tsx:50]: think roles does not need to be function, this is executed once anyway

**Comment by dprokop** [comment]
Thanks @Clarity-89 for testing!

File: packages/grafana-runtime/src/services/LocationService.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (Clarity-89) [reply packages/grafana-runtime/src/services/LocationService.ts:56]: I think performance-wise it's almost the same since `bind` also creates new functions. But my main concern is that if there's a lot of the methods bound like this, it will make code messier and harder to maintain (e.g. if method name changes, it now needs to be updated here as well). Another benefit of arrow methods is proper `this` scoping.

**Review by torkelo — APPROVED** [review]

**Review by thisisobate — COMMENTED** [review]
This looks exciting I must confess!

Tested on local and everything seems to be working fine.

Amazing work! 🎉🎉🎉 @torkelo @dprokop
