### PR TITLE
Prometheus: Fix disappearing multi values in metric label values

### LINKED ISSUE #48123: Grafana/ui: Select in multiselect mode sometimes does not show values
Seems like multiselect when the values are both custom (so not in the options prop), for some render it does not show any value at all:

https://user-images.githubusercontent.com/1014802/164727153-bad9d7d5-5060-4912-8b06-0849a7ef92be.mp4

The values seem to be lost somewhere in the SelectBase but wasn't able to find where (the console log is just before the return in the BaseSelect component). Also, the values are shown if there is another rerender with the same state.

### PR DESCRIPTION
**Pull request by aocenas**
Fixes: https://github.com/grafana/grafana/issues/48123

### CODE REVIEW

File: public/app/plugins/datasource/prometheus/querybuilder/shared/LabelFilterItem.tsx [hunk 1]
```diff
@@ -27,22 +27,18 @@ export function LabelFilterItem({ item, defaultOp, onChange, onDelete, onGetLabe
...
   };
 
-  const getOptions = () => {
-    if (!state.labelValues && item && item.value && item.value.indexOf('|') > 0) {
-      return getValue(item);
-    }
-
-    return state.labelValues;
+  const getOptions = (): SelectableValue[] => {
+    return [...getSelectOptionsFromString(item?.value).map(toOption), ...(state.labelValues ?? [])];
```
Comment (aocenas) [inline public/app/plugins/datasource/prometheus/querybuilder/shared/LabelFilterItem.tsx:41]: Main fix is just to include the created options in the select options array.

**Review by torkelo — APPROVED** [review]
