### PR TITLE
InfluxDB SQL: Provide raw query preview for query history

### LINKED ISSUE #74987: InfluxDB SQL Bug: Query history is not working correctly

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

Support `getQueryDisplayText` for InfluxDB SQL variant. 

image

**Why do we need this feature?**

To be able to show the query in the query history panel

**Who is this feature for?**

InfluxDB SQL query language users

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/74987

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/plugins/datasource/influxdb/fsql/sqlUtil.ts [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+
+  if (dataset && table) {
+    rawQuery += `FROM ${dataset}.${table} `;
+  }
+
+  if (sql.whereString) {
+    rawQuery += `WHERE ${sql.whereString} `;
+  }
+
+  if (sql.groupBy?.[0]?.property.name) {
```
Comment (gtk-grafana) [inline public/app/plugins/datasource/influxdb/fsql/sqlUtil.ts:24]: do we want to iterate through the groupBy or are we fine selecting the first one?

**Review by gtk-grafana — APPROVED** [review]

File: public/app/plugins/datasource/influxdb/fsql/sqlUtil.ts (hunk 1 above)
Comment (itsmylife) [reply public/app/plugins/datasource/influxdb/fsql/sqlUtil.ts:24]: This code was taken from mysql and postgresql datasources. For now it is ok but it needs some refactoring to fit with InfluxDB SQL requirements. Code generation is a bit problematic and I will address that in another PR. And I will definitely check that part too.
