### PR TITLE
Exemplars: always query exemplars

### LINKED ISSUE #30916: Opportunistically query for exemplars
**What would you like to be added**:

With 7.4, we have an option to query for exemplars in explore.  Current behaviour:
- If you turn it on with a version of Prometheus that doesn't support exemplars, the whole query fails
- If you turn it on with one that does, you sometimes see exemplars (when the query has some).

I'm suggesting we _always_ query for exemplars, and then have a toggle to show/hide exemplars when the query succeeds, and grey out the button (with an error message in the tooltip saying the request failed).

We should also persist the state of the toggle in the link.

**Why is this needed**:

So exemplars are move discoverable.

/cc @zoltanbedi @cstyan

### PR DESCRIPTION
**Pull request by zoltanbedi**
**What this PR does / why we need it**:

This pr changes Prometheus query editor to always query exemplars.
If exemplars endpoint is not there yet then we show an icon with a tooltip next to the Show exemplars button. Also it shows the query without exemplars and doesn't crash.
Screenshot 2021-03-04 at 12 52 24

**Which issue(s) this PR fixes**:

Fixes #30916

### CODE REVIEW

**Review by ivanahuckova — COMMENTED** [review]
The code looks really good, clean and readable.🤩

Regarding UI - if we know that Prometheus is not supporting exemplars, can't we just not show it. Or visually turn it off and disable it? Because it might be confusing the have the toggle ON, but the tooltip says that your Prometheus is not supporting exemplars, but you can't turn it OFF. Maybe you can check in UX what they think.

File: public/app/plugins/datasource/prometheus/components/PromExemplarField.tsx [hunk 1]
```diff
@@ -1,21 +1,67 @@
...
   return (
-    <InlineField label="Exemplars" labelWidth="auto">
-      <InlineSwitch label="Exemplars" value={!!props.query.exemplar} onChange={onExemplarsChange(props)} />
-    </InlineField>
+    <InlineLabel width="auto">
+      <Tooltip content={!!error ? 'Exemplars are not supported in this version of prometheus.' : ''}>
+        <div className={styles.iconWrapper}>
+          Exemplars
+          <IconButton
+            name="eye"
```
Comment (ivanahuckova) [inline public/app/plugins/datasource/prometheus/components/PromExemplarField.tsx:41]: I would do here also `tooltip={!!props.query.exemplar ?  'Disable query with exemplars' : 'Enable query with exemplars'}`. Not sure about exact copy, but I would add tooltip for this as well.

**Review by ivanahuckova — APPROVED** [review]
LGTM! 🙂 Nice job. Left a nit comment, but It is definitely not a blocker.
