### PR TITLE
Explore: Use root datasource if not mixed and adding first query

### LINKED ISSUE #56900: Explore: Deleting all queries and adding one creates query with default DS
**What happened**:
1. Go to explore. Choose a non default datasource
2. Delete the query
3. Add a query
4. Query added is for the default datasource.

**What you expected to happen**:
Query added should be for the selected datasource. If selected datasource is mixed, it should be for the default datasource.

**Anything else we need to know?**:
This is a regression from the mixed datasources changed, but occurs when mixed datasource flag is off

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by gelicia**
**What this PR does / why we need it**:
The refactoring needed to add the mixed datasources feature added the datasource ref to every query. This missed some logic in the scenario where there were no queries, but we needed to create one and only had the root datasource to go off of. This fixes that error by passing the root datasource in from state as an override if needed.

**Which issue(s) this PR fixes**:
Fixes #56900

### CODE REVIEW

File: public/app/features/explore/state/query.ts [hunk 1]
```diff
@@ -222,7 +222,18 @@ export const clearCacheAction = createAction<ClearCachePayload>('explore/clearCa
...
   return async (dispatch, getState) => {
     const queries = getState().explore[exploreId]!.queries;
-    const query = await generateEmptyQuery(queries, index);
+    let datasourceOverride = undefined;
+
+    // if this is the first query being added, check for a root datasource
+    // if it's not mixed, send it as an override. generateEmptyQuery doesn't have access to state
+    if (queries.length === 0) {
+      const rootDatasource = getState().explore[exploreId]!.datasourceInstance;
+      if (!config.featureToggles.exploreMixedDatasource || !rootDatasource?.meta.mixed) {
```
Comment (ifrost) [inline public/app/features/explore/state/query.ts:231]: Nit: Maybe just a personal preference but I think the other way around reads a bit better:

```suggestion
      if (!(config.featureToggles.exploreMixedDatasource && rootDatasource?.meta.mixed)) {
```

also data source can be `mixed` only if the toggle is enabled so maybe we also just use:

```suggestion
      if (!rootDatasource?.meta.mixed) {
```

**Review by ifrost — APPROVED** [review]
Nice catch! Works as expected 🎉

**Comment by L-M-K-B** [comment]
+1 
Works very well! 😃
