### PR TITLE
Access Control: Clean up permissions for deprovisioned data sources

### LINKED ISSUE #88482: Data source provisioning/creation failures
**What**

Data source provisioning and creation sometimes fails with the following message:

```
ERROR[05-30|12:38:36] Failed to provision data sources         logger=provisioning error="Datasource provisioning error: UNIQUE constraint failed: permission.action, permission.scope, permission.role_id"
```

We should investigate why we try to insert duplicate permissions and fix the issue.

### PR DESCRIPTION
**Pull request by IevaVasiljeva**
**What is this feature?**

Make sure that data source permissions get correctly cleaned up if a data source is deleted through provisioning.

Context: previously we were passing an empty UID to the permission cleanup function, so the permissions were not deleted. 

Other work:
* make it explicit that DS service not DS store is used in provisioning code;
* remove a dangerous (and wrong) permission deletion query that didn't check for org ID

**Why do we need this feature?**

To correctly clean up DS permissions. Otherwise DS creation fails afterwards, as we try to reinsert already existing permissions.

**Who is this feature for?**

Anyone who uses data source provisioning.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/88482

### CODE REVIEW

File: pkg/services/datasources/service/store.go [hunk 1]
```diff
@@ -162,12 +161,6 @@ func (ss *SqlStore) DeleteDataSource(ctx context.Context, cmd *datasources.Delet
 			}
 
 			cmd.DeletedDatasourcesCount, _ = result.RowsAffected()
-
-			// Remove associated AccessControl permissions
-			if _, errDeletingPerms := sess.Exec("DELETE FROM permission WHERE scope=?",
-				ac.Scope(datasources.ScopeProvider.GetResourceScope(ds.UID))); errDeletingPerms != nil {
-				return errDeletingPerms
-			}
```
Comment (IevaVasiljeva) [inline pkg/services/datasources/service/store.go:170]: Note: removing this, as it's not safe - if data sources with the same UID exists in multiple orgs, we'd be deleting the permissions for all of these data sources. `DeleteDataSource` from DS store is only called from DS service which also calls access control function to clean up data source permissions, so this is safe.

File: pkg/services/provisioning/datasources/datasources.go [hunk 2]
```diff
@@ -12,14 +12,6 @@ import (
 	jsoniter "github.com/json-iterator/go"
 )
 
-type Store interface {
```
Comment (IevaVasiljeva) [inline pkg/services/provisioning/datasources/datasources.go:15]: Note: I could leave it in, but I think it's cleaner when you can see that DS service is used (previously it looked like it was DS store that was called, although it wasn't the case).

File: pkg/services/provisioning/datasources/datasources.go [hunk 3]
```diff
@@ -238,17 +230,21 @@ func makeCreateCorrelationCommand(correlation map[string]any, SourceUID string,
...
+				return err
+			}
 		}
 
 		// Skip publishing the event as the data source is not really deleted, it will be re-created during provisioning
 		// This is to avoid cleaning up any resources related to the data source (e.g. correlations)
 		skipPublish := willExistAfterProvisioning[DataSourceMapKey{Name: ds.Name, OrgId: ds.OrgID}]
-		cmd := &datasources.DeleteDataSourceCommand{OrgID: ds.OrgID, Name: ds.Name, SkipPublish: skipPublish}
-		if err := dc.store.DeleteDataSource(ctx, cmd); err != nil {
+		cmd := &datasources.DeleteDataSourceCommand{OrgID: ds.OrgID, Name: ds.Name, UID: existingDs.UID, SkipPublish: skipPublish}
```
Comment (IevaVasiljeva) [inline pkg/services/provisioning/datasources/datasources.go:246]: Note: the main change is here - passing in the UID of the data source (it is used for cleaning up DS permissions).

File: pkg/services/datasources/service/datasource_test.go [hunk 4]
```diff
@@ -542,6 +542,71 @@ func TestService_UpdateDataSource(t *testing.T) {
...
 }
 
+func TestService_DeleteDataSource(t *testing.T) {
+	t.Run("should not return an error if data source doesn't exist", func(t *testing.T) {
+		sqlStore := db.InitTestDB(t)
+		secretsService := secretsmng.SetupTestService(t, fakes.NewFakeSecretsStore())
+		secretsStore := secretskvs.NewSQLSecretsKVStore(sqlStore, secretsService, log.New("test.logger"))
+		quotaService := quotatest.New(false, nil)
+		permissionSvc := acmock.NewMockedPermissionsService()
+		permissionSvc.On("DeleteResourcePermissions", mock.Anything, mock.Anything, mock.Anything).Return(nil).Maybe()
```
Comment (drclau) [inline pkg/services/datasources/service/datasource_test.go:552]: Seems like this would be slightly better.

```suggestion
		permissionSvc.On("DeleteResourcePermissions", mock.Anything, mock.Anything, mock.Anything).Return(nil).Once()
```

**Review by drclau — APPROVED** [review]
lgtm

**Review by gamab — APPROVED** [review]
LGTM!

**Review by andresmgot — CHANGES_REQUESTED** [review]
Just one small request here

File: pkg/services/provisioning/datasources/datasources.go (hunk 2 above)
Comment (IevaVasiljeva) [reply pkg/services/provisioning/datasources/datasources.go:15]: I've renamed `DataSourceService` in DS provisioning to `BaseDataSourceService`, I think that's what you meant, right? I initially removed the interface altogether and used the DS service interface directly, but it required pretty big test updates, so I decided to leave the interface in.

**Review by andresmgot — APPROVED** [review]
LGTM
