### PR TITLE
Permissions: Fix team and role permissions on folders/dashboards not displayed for non Grafana Admin users

### LINKED ISSUE #31134: Team/role permissions on dashboards/folders are not displayed to non Grafana Admin users
**What happened**:
Team permissions are not displayed for non Grafana Admin users. 

Grafana Admin view:
image

Admin user without Grafana Admin rights view:
image

**What you expected to happen**:
The two screen above should show the same things.

**How to reproduce it (as minimally and precisely as possible)**:
Set one team permission and one role permission on a dashboard with a Grafana Admin user. Then, log in with a non Grafana Admin user and look at the dashboard permissions.

**Environment**:
- Grafana version: 7.4

### PR DESCRIPTION
**Pull request by AgnesToulet**
**What this PR does / why we need it**:
Fix team and role permissions not displayed for folder and dashboard permissions. 

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/31134

**Special notes for your reviewer**:
There are two fixes in this PR:
- The first one is to initialize the `cfg.HiddenUsers` field as empty when the config field is empty.
- The second one is to not even use this config field if the `userLogin` field is empty which is the case for team and role permissions. This isn't necessary but it was my first fix and I think it makes senses anyway.

Also, this issue wasn't catched in the dashboard permissions tests because settings are not initialized in the same way than for a real Grafana instance. E2E tests for dashboard permissions would be great but I don't have the knowledge to include them in this PR.

### CODE REVIEW

File: pkg/api/dtos/models.go [hunk 1]
```diff
@@ -77,7 +77,7 @@ func GetGravatarUrlWithDefault(text string, defaultText string) string {
 }
 
 func IsHiddenUser(userLogin string, signedInUser *models.SignedInUser, cfg *setting.Cfg) bool {
-	if signedInUser.IsGrafanaAdmin || userLogin == signedInUser.Login {
+	if userLogin == "" || signedInUser.IsGrafanaAdmin || userLogin == signedInUser.Login {
```
Comment (marefr) [inline pkg/api/dtos/models.go:80]: Would be good having a test of this method. 

In addition it feels a bit fragile/awkward that this method would be called for any permission, should only be called for user permissions. WDYT?

**Review by marefr — CHANGES_REQUESTED** [review]
Looks good I think. But requested some changes, see comment

File: pkg/api/dtos/models.go (hunk 1 above)
Comment (AgnesToulet) [reply pkg/api/dtos/models.go:80]: Yes you're right, I added the test in the dashboard permissions file. Now, I'm not sure if we should keep this line or remove it.

Comment (xlson) [reply pkg/api/dtos/models.go:80]: I agree, we should def call this only when we need to.

Comment (AgnesToulet) [reply pkg/api/dtos/models.go:80]: Yes, I added a check for dashboard / folder permissions in [this commit](https://github.com/grafana/grafana/pull/31132/commits/bdb6542ec620803c61e1309e0bb3f77eb941609c) and I made a PR for Enterprise too.

**Review by marefr — CHANGES_REQUESTED** [review]
Great. Almost there

dashboard_permissions.go should be updated as well: https://github.com/grafana/grafana/blob/a18e4d8d6437a0cf57e8ddebe61d36d5ce081e25/pkg/api/dashboard_permission.go#L35

File: pkg/api/dtos/models.go (hunk 1 above)
Comment (marefr) [reply pkg/api/dtos/models.go:80]: > I'm not sure if we should keep this line or remove it.

If someone uses the API with an API key the `signedInUser.Login` would be empty. But doesn't really matter because permissions shouldn't have an empty `userLogin` is it's a user permissions. This extra check wouldn't hurt I would say :)

**Review by marefr — APPROVED** [review]
LGTM great
