### PR TITLE
stackdriver: fix for float64 bounds for distribution metrics

### LINKED ISSUE #14509: Stackdriver data source expects distributions' lower bounds to be int64
Please include this information:
### What Grafana version are you using?
5.3.4 (But, version doesn't really matter, I see the problematic code even now.)

### What datasource are you using?
Stackdriver with GCE.

Adding a stackdriver distribution metric that has float lower-bounds results in an error:
"json: cannot unmarshal number 0.01 into Go struct field .bounds of type int64"

Here is the code that's causing this problem:
https://github.com/grafana/grafana/blob/9773a2d41959385b338e97eb2f9b3b61c1b7f8c3/pkg/tsdb/stackdriver/types.go#L29

I can attempt fixing it. Please let me know.

### PR DESCRIPTION
**Pull request by daniellee**
Adds support for explicit distribution metrics and float64 bounds  (for example, 0.01, 0.05 etc). Might need to follow up with a fix for linear and exponential distribution metrics but have to create some test data for those cases first.

Fixes #14509

### CODE REVIEW

File: pkg/tsdb/stackdriver/stackdriver.go [hunk 1]
```diff
@@ -559,7 +561,7 @@ func calcBucketBound(bucketOptions StackdriverBucketOptions, n int) string {
 	} else if bucketOptions.ExponentialBuckets != nil {
 		bucketBound = strconv.FormatInt(int64(bucketOptions.ExponentialBuckets.Scale*math.Pow(bucketOptions.ExponentialBuckets.GrowthFactor, float64(n-1))), 10)
 	} else if bucketOptions.ExplicitBuckets != nil {
-		bucketBound = strconv.FormatInt(bucketOptions.ExplicitBuckets.Bounds[(n-1)], 10)
+		bucketBound = fmt.Sprintf("%g", bucketOptions.ExplicitBuckets.Bounds[n])
```
Comment (marefr) [inline pkg/tsdb/stackdriver/stackdriver.go]: What's with the `n-1` used earlier vs only `n` now?

**Review by marefr — COMMENTED** [review]
LGTM, but have a question, see comment

File: pkg/tsdb/stackdriver/stackdriver.go (hunk 1 above)
Comment (daniellee) [reply pkg/tsdb/stackdriver/stackdriver.go]: It was incorrect before - noticed that in the UI and added a test for distribution metrics with explicit bounds to test this.
