### PR TITLE
Alerting: Fix redirect after saving a notification template

### LINKED ISSUE #83471: Saving a Template redirects to Contact Points

### PR DESCRIPTION
**Pull request by tomratcliffe**
**What is this feature?**

Redirects to the correct UI after saving a notification template

**Why do we need this feature?**

Adds query param handling for the tabs within the contact points page, so saving a notification template would send you back to the Contact Points tab. This fixes it

**Which issue(s) does this PR fix?**:
Fixes #83471

### CODE REVIEW

**Comment by tomratcliffe** [comment]
(The tests are acting strange - there's something stateful in `ContactPoints.test` for me, where if I focus the failing tests then they start passing. Need to investigate this)

File: public/app/features/alerting/unified/components/contact-points/ContactPoints.tsx [hunk 1]
```diff
@@ -62,17 +62,19 @@ import {
...
+  NotificationTemplates = 'templates',
 }
 
 const DEFAULT_PAGE_SIZE = 10;
 
 const ContactPoints = () => {
   const { selectedAlertmanager } = useAlertmanager();
-  // TODO hook up to query params
-  const [activeTab, setActiveTab] = useState<ActiveTab>(ActiveTab.ContactPoints);
+  const [queryParams, setQueryParams] = useQueryParams();
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/contact-points/ContactPoints.tsx:74]: `useURLSearchParams` gives you a native `URLSearchParam` interface to work with. I think it could simplify the code if used

File: public/app/features/alerting/unified/components/contact-points/ContactPoints.tsx [hunk 2]
```diff
@@ -88,12 +90,15 @@ const ContactPoints = () => {
   const [DeleteModal, showDeleteModal] = useDeleteContactPointModal(deleteTrigger, updateAlertmanagerState.isLoading);
   const [ExportDrawer, showExportDrawer] = useExportContactPoint();
 
-  const [searchParams] = useURLSearchParams();
-  const { search } = getContactPointsFilters(searchParams);
+  const search = String(queryParams.search || '');
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/contact-points/ContactPoints.tsx:93]: If you use `useURLSearchParam` type casting here would be no longer needed

File: public/app/features/alerting/unified/components/contact-points/ContactPoints.tsx [hunk 3]
```diff
@@ -62,17 +62,19 @@ import {
...
 
 const DEFAULT_PAGE_SIZE = 10;
 
 const ContactPoints = () => {
   const { selectedAlertmanager } = useAlertmanager();
-  // TODO hook up to query params
-  const [activeTab, setActiveTab] = useState<ActiveTab>(ActiveTab.ContactPoints);
+  const [queryParams, setQueryParams] = useQueryParams();
+  // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
+  const initialActiveTab = queryParams.tab as ActiveTab;
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/contact-points/ContactPoints.tsx:76]: If the user changes the param in the URL the value will be incorrect
Perhaps a custom typeguard returning `ActiveTab` would be better?

File: public/app/features/alerting/unified/components/contact-points/ContactPoints.tsx [hunk 4]
```diff
@@ -62,17 +62,19 @@ import {
...
 }
 
 const DEFAULT_PAGE_SIZE = 10;
 
 const ContactPoints = () => {
   const { selectedAlertmanager } = useAlertmanager();
-  // TODO hook up to query params
-  const [activeTab, setActiveTab] = useState<ActiveTab>(ActiveTab.ContactPoints);
+  const [queryParams, setQueryParams] = useQueryParams();
+  // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/contact-points/ContactPoints.tsx:75]: I think we are able to get rid of this

File: public/app/features/alerting/unified/components/contact-points/ContactPoints.test.tsx [hunk 5]
```diff
@@ -40,6 +41,13 @@ import setupVanillaAlertmanagerFlavoredServer, {
 const server = setupMswServer();
 
 describe('contact points', () => {
+  beforeEach(() => {
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/contact-points/ContactPoints.test.tsx:44]: 👍

**Comment by tomratcliffe** [comment]
@konrad147 I've refactored the logic into a small hook - let me know what you think

File: public/app/features/alerting/unified/components/contact-points/ContactPoints.tsx [hunk 6]
```diff
@@ -62,17 +62,32 @@ import {
...
+    return queryParam || ActiveTab.ContactPoints;
+  }, [queryParams]);
+};
+
 const ContactPoints = () => {
   const { selectedAlertmanager } = useAlertmanager();
-  // TODO hook up to query params
-  const [activeTab, setActiveTab] = useState<ActiveTab>(ActiveTab.ContactPoints);
+  const [queryParams, setQueryParams] = useURLSearchParams();
+  const activeTabVal = useTabQueryParam();
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/contact-points/ContactPoints.tsx:88]: How about keeping the active tab state only in url and changing this hook like for example
```
const [activeTab, setActiveTab] = useTabQuery()
```
Then, we could remove the line below, and make the query parameter our only source of truth. 
It should also allow us to remove the `useEffect` below

File: public/app/features/alerting/unified/components/contact-points/ContactPoints.tsx [hunk 7]
```diff
@@ -62,17 +62,35 @@ import {
...
+    const queryParam = queryParams.get('tab');
+
+    if (!queryParam || !Object.values(ActiveTab).map(String).includes(queryParam)) {
+      return ActiveTab.ContactPoints;
+    }
+
+    return queryParam || ActiveTab.ContactPoints;
+  }, [queryParams]);
+
+  const setParam = (tab: string) => setQueryParams({ tab });
```
Comment (konrad147) [inline public/app/features/alerting/unified/components/contact-points/ContactPoints.tsx:84]: one nit: 
```suggestion
  const setParam = (tab: ActiveTab) => setQueryParams({ tab });
```

**Review by konrad147 — APPROVED** [review]
LGMT! one nit

File: public/app/features/alerting/unified/components/contact-points/ContactPoints.tsx (hunk 7 above)
Comment (tomratcliffe) [reply public/app/features/alerting/unified/components/contact-points/ContactPoints.tsx]: Thanks, good point - done!
