### PR TITLE
Plugins: Fix support for adhoc filters with raw queries in InfluxDB 

### LINKED ISSUE #101635: InfluxDB: adhoc filters not handled for raw queries
### What happened?

adhoc filters were created for a raw query.

### What did you expect to happen?

adhoc filters would be applied to a raw query.

### Did this work before?

this never worked for raw queries.

### How do we reproduce it?

1. create an influxdb dashboard with a raw query panel
2. add an adhoc filter
3. observe that the adhoc filter values are not applied to raw queries.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

InfluxDB

### PR DESCRIPTION
**Pull request by beejeebus**
Fixes #101635.

### CODE REVIEW

**Comment by bossinc** [comment]
This works well, but I think adhoc queries should be processed on the frontend. Building queries should happen in the frontend so users can easily see how their queries are manipulated with the query inspector. Adhoc filters are also only used for dashboards, so it makes sense to keep adhoc query logic with other dashboard logic like template vars. Lastly, (probably the weakest point) all data sources that I'm familiar with process adhoc filters in the `applyTemplateVariables` function. What do you think?

**Comment by beejeebus** [comment]
> This works well, but I think adhoc queries should be processed on the frontend. Building queries should happen in the frontend so users can easily see how their queries are manipulated with the query inspector. Adhoc filters are also only used for dashboards, so it makes sense to keep adhoc query logic with other dashboard logic like template vars. Lastly, (probably the weakest point) all data sources that I'm familiar with process adhoc filters in the `applyTemplateVariables` function. What do you think?

I don't agree, I think we should do this on the backend. Not sure how to proceed, but probably best to close this PR and get more feedback from the team.

File: pkg/tsdb/influxdb/models/query.go [hunk 1]
```diff
@@ -44,6 +95,96 @@ func (query *Query) Build(queryContext *backend.QueryDataRequest) (string, error
...
+				tag.Operator = "=~"
+			} else {
+				tag.Operator = "="
+			}
+		}
+
+		isOperatorTypeHandler := func(tag *Tag) (string, string) {
+			// Attempt to identify the type of the supplied value
+			var lowerValue = strings.ToLower(tag.Value)
+			var r = regexp.MustCompile(`^(-?)[0-9\.]+$`)
```
Comment (bossinc) [inline pkg/tsdb/influxdb/models/query.go:124]: idk if this is worth calling out. feel free to ignore
```suggestion
			lowerValue := strings.ToLower(tag.Value)
			r := regexp.MustCompile(`^(-?)[0-9\.]+$`)
```

File: pkg/tsdb/influxdb/models/query.go [hunk 2]
```diff
@@ -44,6 +95,96 @@ func (query *Query) Build(queryContext *backend.QueryDataRequest) (string, error
...
+
+			// Perform operator replacements
+			switch tag.Operator {
+			case "Is":
+				operator = "="
+			case "Is Not":
+				operator = "!="
+			default:
+				// This should never happen
+				operator = "="
```
Comment (bossinc) [inline pkg/tsdb/influxdb/models/query.go:136]: If this should never, should we return an error?

File: pkg/tsdb/influxdb/models/query.go [hunk 3]
```diff
@@ -15,12 +16,62 @@ var (
 	regexpOperatorPattern           = regexp.MustCompile(`^\/.*\/$`)
 	regexpMeasurementPattern        = regexp.MustCompile(`^\/.*\/$`)
 	regexMatcherWithStartEndPattern = regexp.MustCompile(`^/\^(.*)\$/$`)
+	regexpRawQueryWhere             = regexp.MustCompile(`(?i)WHERE`)
 )
 
+func (query *Query) getRawQueryWithAdhocFilters() string {
```
Comment (bossinc) [inline pkg/tsdb/influxdb/models/query.go:22]: `renderTags` seems to be almost the same function. Can we make `renderTags` generic and just use that?

**Review by bossinc — CHANGES_REQUESTED** [review]

File: pkg/tsdb/influxdb/models/query.go (hunk 3 above)
Comment (bossinc) [reply pkg/tsdb/influxdb/models/query.go:22]: This is the only comment preventing me from approving

Comment (beejeebus) [reply pkg/tsdb/influxdb/models/query.go:22]: I'll refactor the signatures to reuse code from that function.

I like all the rest of your comments, but I don't want to resolve them in this PR, because that's all just existing code.

**Review by bossinc — APPROVED** [review]

**Comment by beejeebus** [comment]
more failures that don't seem at all related to this PR. will get a rerun going and see if I get lucky next time.
