### PR TITLE
Dashboards: Evaluate provisioned dashboard titles in a backwards compatible way

### LINKED ISSUE #64525: alert rules: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title
**What happened**:
Upgrading from version 9.1.2 we tried to upgrade to the newest version of 9.4.3. This lead to the following error:

```
Error: ✗ alert rules: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title
```

This happens during startup and terminates the process. It seems to happen while parsing the provisioned files (see below).

**What you expected to happen**:
Provisioned alert rules can be read without errors after upgrading,

**How to reproduce it (as minimally and precisely as possible)**:
We've used a minimal Grafana `docker-compose.yml` setup:

```yaml
version: '3'

services:
  grafana:
    image: grafana/grafana:9.1.2
    ports:
      - "3000:3000"
    volumes:
      - /srv/docker/grafana/:/var/lib/grafana
      - ./grafana-config/:/etc/grafana/
```

We provisioned a minimal `grafana-config/provisioning/alerting/rules.yml`:

```yaml
apiVersion: 1
groups:
  - orgId: 1
    name: my_rule_group
    folder: my_first_folder
    interval: 60s
    rules:
      - uid: my_id_1
        title: my_first_rule
        condition: A
        data:
          - refId: A
            datasourceUid: '__expr__'
            model:
              conditions:
                - evaluator:
                    params:
                      - 3
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: '__expr__'
              expression: 1==0
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
              type: math
        noDataState: Alerting
        for: 60s
```
This provisioned file is derived from the [documentations](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-alert-rules).

Starting this instance leads to _no_ errors, as this works in Grafana 9.1.2 ✔️ .

After stopping the container and upgrading the version from 9.1.2 to version 9.4.3 within the `docker-compose.yml` the following error occurred on `docker logs` (some debug logging was applied via `grafana.ini`) :x: :

```
logger=provisioning.alerting t=2023-03-09T13:46:12.552109646Z level=debug msg="looking for alerting provisioning files" path=/etc/grafana/provisioning/alerting
logger=provisioning.alerting t=2023-03-09T13:46:12.552183446Z level=debug msg="parsing alerting provisioning file" path=/etc/grafana/provisioning/alerting file.Name=rules.yml
logger=provisioning.alerting t=2023-03-09T13:46:12.552635744Z level=info msg="starting to provision alerting"
logger=provisioning.alerting t=2023-03-09T13:46:12.552660944Z level=debug msg="read all alerting files" file_count=1
Error: ✗ alert rules: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title
```

It seems only to happen when the provisioned alert rule existed prior to the upgrade, and only when the folder (`my_first_folder` from above) contains an alert rule.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana Version 9.1.0 as Docker image (REPOSITORY: grafana/grafana, TAG 9.4.3, IMAGE ID: 944e84f25bc7)
- OS Grafana is installed on: Docker image OS
- Grafana plugins: none

### LINKED ISSUE #64595: Grafana 9.4 dashboard provisioning not working
After upgrade on Grafana 9.4.x   provisioning of dashboards doesn't working.

I get this error

`logger=provisioning t=2023-03-10T11:44:26.104835139+01:00 level=error msg="Failed to provision dashboard" error="Failed to provision dashboards: failed to provision config bare_metal_servers_2: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title"
logger=server t=2023-03-10T11:44:26.104947224+01:00 level=error msg="Stopped background service" service=*provisioning.ProvisioningServiceImpl reason="Failed to provision dashboards: failed to provision config bare_metal_servers_2: UNIQUE constraint failed: dashboard.org_id, dashboard.folder_id, dashboard.title"
logger=ticker t=2023-03-10T11:44:26.105017023+01:00 level=info msg=stopped last_tick=2023-03-10T11:44:20+01:00
logger=tracing t=2023-03-10T11:44:26.105187299+01:00 level=info msg="Closing tracing"
`

I have lot of provisoning dashboards. For example, configuration of two of them:

```
cat /etc/grafana/provisioning/dashboards/bare_metal_servers_2.yaml 
apiVersion: 1

providers:
 - name: 'bare_metal_servers_2'
   orgId: 2
   folder: 'bare_metal_servers'
   type: 'file'
   updateIntervalSeconds: 30
   options:
     path: /var/lib/grafana/dashboards/bare_metal_servers_2/

```

```
cat /etc/grafana/provisioning/dashboards/bare_metal_servers_3.yaml 

apiVersion: 1

providers:
 - name: 'bare_metal_servers_3'
   orgId: 3
   folder: 'bare_metal_servers'
   type: 'file'
   updateIntervalSeconds: 30
   options:
     path: /var/lib/grafana/dashboards/bare_metal_servers_3/

```

On the version 9.3.8 the provisioning works. I didn't find that the provisioning of dashboards changed in version 9.4.x. It's feature or bug?

### PR DESCRIPTION
**Pull request by sakjur**
**What is this feature?**

- Adds support for querying a dashboard by its folder ID and title (folder ID is required to satisfy the `UQE_org_id_folder_id_title` index).
- Removes support for querying a dashboard by slug (the slug index has been removed and it was only used by the two methods below).

**Why do we need this feature?**

#59517 changed some corner cases for slug generation and previously alerting and dashboards were using slugs to determine whether a folder already existed or not.

https://github.com/grafana/grafana/blob/b54b80f473ce010a3377d1907b449f382db0bb8f/pkg/services/provisioning/dashboards/file_reader.go#L302
https://github.com/grafana/grafana/blob/c006df375a3a6056f9cbeeaf2f28f87ce86823a2/pkg/services/provisioning/alerting/rules_provisioner.go#L99-L102

**Who is this feature for?**

Bug fix for provisioning for users upgrading to Grafana 9.4 from an earlier version.

**Which issue(s) does this PR fix?**:

Fixes #64525
Fixes #64595

**Special notes for your reviewer:**

The steps to reproduce that I was successful in following were provided in #64525 by @ThomasFOC (🙏 thank you for the very good step-by-step instructions for reproduction), here's a tarball containing a docker-compose environment that should show the issue. Use the commented out line to alternate between the earlier version of Grafana and a later version of Grafana should trigger the issue:
- [grafana-issue-64525.tar.gz](https://github.com/grafana/grafana/files/11040825/grafana-issue-64525.tar.gz)

For manually testing the patch, I'd recommend copying over the 1.yml provisioning file to the provisioning directory in your development environment and checking out the `v9.3.8` and then a later version (I started out by testing it against 6a1d736f037c5d1c2c82d353e8cd2878348715d0 which was the current head of the v9.4.x branch). Validate that this is broken, and then check out this branch to validate its function.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.
- [ ] There are no known compatibility issues with older supported versions of Grafana, or plugins.
- [ ] It passes the [Hosted Grafana feature readiness review](https://docs.google.com/document/d/1QL9Ly8KnXzpb6ISbg49pTODRO5mhA5tkkfIZVX6pqQU/edit) for observability, scalability, performance, and security.

### CODE REVIEW

File: pkg/services/provisioning/alerting/rules_provisioner.go [hunk 1]
```diff
@@ -97,8 +96,9 @@ func (prov *defaultAlertRuleProvisioner) provisionRule(
 func (prov *defaultAlertRuleProvisioner) getOrCreateFolderUID(
 	ctx context.Context, folderName string, orgID int64) (string, error) {
 	cmd := &dashboards.GetDashboardQuery{
-		Slug:  slugify.Slugify(folderName),
-		OrgID: orgID,
+		Title:    &folderName,
+		FolderID: util.Pointer(int64(0)),
```
Comment (papagian) [inline pkg/services/provisioning/alerting/rules_provisioner.go:100]: that's can be fine for now but if nested folders are enabled then we need also the parent folder information

File: pkg/services/provisioning/dashboards/file_reader.go [hunk 2]
```diff
@@ -299,7 +298,11 @@ func (fr *FileReader) getOrCreateFolderID(ctx context.Context, cfg *config, serv
 		return 0, ErrFolderNameMissing
 	}
 
-	cmd := &dashboards.GetDashboardQuery{Slug: slugify.Slugify(folderName), OrgID: cfg.OrgID}
+	cmd := &dashboards.GetDashboardQuery{
+		Title:    &folderName,
+		FolderID: util.Pointer(int64(0)),
```
Comment (papagian) [inline pkg/services/provisioning/dashboards/file_reader.go:303]: same concern as above

File: pkg/services/dashboards/database/database_test.go [hunk 3]
```diff
@@ -81,11 +82,12 @@ func TestIntegrationDashboardDataAccess(t *testing.T) {
 		require.False(t, queryResult.IsFolder)
 	})
 
-	t.Run("Should be able to get dashboard by slug", func(t *testing.T) {
+	t.Run("Should be able to get dashboard by title and folderID", func(t *testing.T) {
```
Comment (suntala) [inline pkg/services/dashboards/database/database_test.go:85]: It might make sense to also add a test case for when just the title or the folder ID is set. 

Let's consider the new condition, `query.ID == 0 && len(query.UID) == 0 && (query.Title == nil || query.FolderID == nil)`. We could remove the check for the title or for folder ID and all the test cases in `TestIntegrationDashboardDataAccess` still pass.

File: pkg/services/dashboards/database/database.go [hunk 4]
```diff
@@ -847,11 +847,18 @@ func (d *dashboardStore) deleteAlertDefinition(dashboardId int64, sess *db.Sessi
 func (d *dashboardStore) GetDashboard(ctx context.Context, query *dashboards.GetDashboardQuery) (*dashboards.Dashboard, error) {
 	var queryResult *dashboards.Dashboard
 	err := d.store.WithDbSession(ctx, func(sess *db.Session) error {
-		if query.ID == 0 && len(query.Slug) == 0 && len(query.UID) == 0 {
+		if query.ID == 0 && len(query.UID) == 0 && (query.Title == nil || query.FolderID == nil) {
```
[the remark this answers is not in the document]
Comment (sakjur) [reply pkg/services/dashboards/database/database.go:850]: Maybe, I don't have sufficient understanding of any of this to make changes larger than this.

File: pkg/services/dashboards/database/database.go [hunk 5]
```diff
@@ -847,12 +847,22 @@ func (d *dashboardStore) deleteAlertDefinition(dashboardId int64, sess *db.Sessi
...
+		dashboard := dashboards.Dashboard{OrgID: query.OrgID, ID: query.ID, UID: query.UID}
+		mustCols := []string{}
+		if query.Title != nil {
+			dashboard.Title = *query.Title
+			mustCols = append(mustCols, "title")
+		}
+		if query.FolderID != nil {
+			dashboard.FolderID = *query.FolderID
+			mustCols = append(mustCols, "folder_id")
+		}
```
Comment (papagian) [inline pkg/services/dashboards/database/database.go:863]: if it's empty then the `UQE_dashboard_org_id_folder_id_title` index won't be used
maybe it's not a big problem given that another index (`IDX_dashboard_title`) is used, but still has to filter out rows using where (for the `org_id`)

```
mysql> EXPLAIN SELECT * FROM dashboard WHERE org_id = 1 AND title = 'gdev dashboards';
+----+-------------+-----------+------------+------+---------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------+-------+------+----------+-------------+
| id | select_type | table     | partitions | type | possible_keys                                                                                                                         | key                 | key_len | ref   | rows | filtered | Extra       |
+----+-------------+-----------+------------+------+---------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------+-------+------+----------+-------------+
|  1 | SIMPLE      | dashboard | NULL       | ref  | UQE_dashboard_org_id_folder_id_title,UQE_dashboard_org_id_uid,IDX_dashboard_org_id,IDX_dashboard_org_id_plugin_id,IDX_dashboard_title | IDX_dashboard_title | 758     | const |    1 |   100.00 | Using where |
+----+-------------+-----------+------------+------+---------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------+-------+------+----------+-------------+
1 row in set, 1 warning (0.01 sec)

mysql> EXPLAIN SELECT * FROM dashboard WHERE org_id = 1 AND title = 'gdev dashboards' AND folder_id = 0;
+----+-------------+-----------+------------+-------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------+-------------------+------+----------+-------+
| id | select_type | table     | partitions | type  | possible_keys                                                                                                                         | key                                  | key_len | ref               | rows | filtered | Extra |
+----+-------------+-----------+------------+-------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------+-------------------+------+----------+-------+
|  1 | SIMPLE      | dashboard | NULL       | const | UQE_dashboard_org_id_folder_id_title,UQE_dashboard_org_id_uid,IDX_dashboard_org_id,IDX_dashboard_org_id_plugin_id,IDX_dashboard_title | UQE_dashboard_org_id_folder_id_title | 774     | const,const,const |    1 |   100.00 | NULL  |
+----+-------------+-----------+------------+-------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------+-------------------+------+----------+-------+
1 row in set, 1 warning (0.01 sec)
```

File: pkg/services/dashboards/database/database.go [hunk 6]
```diff
@@ -852,14 +852,17 @@ func (d *dashboardStore) GetDashboard(ctx context.Context, query *dashboards.Get
 		}
 
 		dashboard := dashboards.Dashboard{OrgID: query.OrgID, ID: query.ID, UID: query.UID}
+		mustCols := []string{}
 		if query.Title != nil {
 			dashboard.Title = *query.Title
+			mustCols = append(mustCols, "title")
```
Comment (suntala) [inline pkg/services/dashboards/database/database.go:858]: Not completely familiar with MustCols yet but seems to me it would make sense to require that both `title` and `folder_id` be set if `query.Title != nil`. Same comment for if `query.FolderID != nil`

Comment (suntala) [reply pkg/services/dashboards/database/database.go:858]: Actually I suppose we can rely on the check on line 850 to ensure that we do include both "title" and "folder_id" in case either of them is non-nil.

**Review by suntala — APPROVED** [review]
LGTM 👍 

One question, does the API documentation for this need to get updated separately or is the doc comment you added going to be included somehow?

**Review by papagian — COMMENTED** [review]
I have tested and it solves the problem (thank you for the database and the provisioning file to reproduce it)
maybe we could improve the query performance by always using the `UQE_dashboard_org_id_folder_id_title` index

File: pkg/services/dashboards/database/database.go (hunk 6 above)
Comment (papagian) [reply pkg/services/dashboards/database/database.go:858]: I would love to have this query re-written without the `xorm` magic

File: pkg/services/dashboards/database/database.go (hunk 5 above)
Comment (sakjur) [reply pkg/services/dashboards/database/database.go:863]: If it’s nil, then either UID or ID is set and those have indices?

Comment (papagian) [reply pkg/services/dashboards/database/database.go:863]: not sure: the following condition:
https://github.com/grafana/grafana/blob/882b0f608ac0ebf38d0727050a3e980a19763d34/pkg/services/dashboards/database/database.go#L850
allows only the Title to be set, no?

I think that it has to become: `query.Title == nil && query.FolderID == nil)` instead

File: pkg/services/dashboards/database/database.go (hunk 6 above)
Comment (sakjur) [reply pkg/services/dashboards/database/database.go:858]: Rn, you can say “give me a dashboard with this ID and this title”, which has the same uniqueness as title + folder. We don’t need to do it like that, but that’s why those are separated. Note that as long as orgID is properly set (…out of scope for this fix) at least one unique index will be hit, but there’s nothing preventing you from adding further constraints (give me dashboard 5 but only if it’s in folder 10)

File: pkg/services/dashboards/database/database.go (hunk 5 above)
Comment (papagian) [reply pkg/services/dashboards/database/database.go:863]: my mistake, I think that you are right

**Review by papagian — APPROVED** [review]

**Comment by sakjur** [comment]
@suntala That API documentation is just internal in the codebase, so it won’t show up anywhere. If Grafana had been compatible with pkg.go.dev you might’ve been able to see it there, but we wouldn’t have to do anything for that.
