### PR TITLE
Plugins: Fail plugins installation on wrong args provided

### LINKED ISSUE #70056: Plugins: Make grafana CLI flexible in working with command arguments
Grafana CLI is currently limited in how it accepts command arguments

For example, this works:

`grafana cli --debug --pluginsDir=../data/plugins plugins install opennms-helm-app 8.0.2`

But this does not:

`grafana cli --debug plugins install opennms-helm-app 8.0.2 --pluginsDir=../data/plugins`

It would be nice for this arguments to be accepted after the command, or at the very least, warn the user about the fact that it is ignored.

### PR DESCRIPTION
**Pull request by oshirohugo**
**What is this feature?**

Fail plugin installation when more args than needed are provided

**Why do we need this feature?**

This is needed because we use hierarchical flags and arguments and we need to feedback the user if an argument is being ignored. 

**Who is this feature for?**

Fixes #70056

**Special notes for your reviewer:**

The command line package that we use to parse our flags and arguments is based on hierarchical flags. `--pluginsDir` is defined in the upper command (`cli`) to be availabel to all `plugins` subcommands. The library doesn't seem to support a global flag being passed after a subcommand. This is confirmed by this maintainer [comment](https://github.com/urfave/cli/issues/325#issuecomment-184520124) and by this [comment](https://github.com/urfave/cli/issues/734#issuecomment-996185107) on an open isse

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: pkg/cmd/grafana-cli/commands/install_command.go [hunk 1]
```diff
@@ -20,6 +20,11 @@ import (
 )
 
 func validateInput(c utils.CommandLine, pluginFolder string) error {
```
Comment (oshirohugo) [inline pkg/cmd/grafana-cli/commands/install_command.go:22]: `pluginFolder` argument isn't used inside this function and could be removed as well

File: pkg/cmd/grafana-cli/commands/install_command.go [hunk 2]
```diff
@@ -20,6 +20,11 @@ import (
...
+	if c.Args().Len() > 1 {
+		logger.Info("Install only supports one local argument\n")
+		showIgnoredArguments(c.Args().Slice()[1:])
+	}
```
[the remark this answers is not in the document]
Comment (andresmgot) [reply pkg/cmd/grafana-cli/commands/install_command.go:26]: Also, the length to check should be 2, not 1 (it's possible to specify the version, apart from the name). This has the caveat that if you specify `... install foo --pluginsDir=bar`, the number of arguments is correct but it will fail anyway when trying to use the flag as a version.

**Review by andresmgot — COMMENTED** [review]
The lack of this functionality is surprising :sweat_smile: I checked it and if you copy the flag to the sub command (so you have the flag `--pluginsDir` in the `install` command), it no longer works if you specify it at the root level (so `grafana cli --pluginsDir foo install bar` would stop working).

Anyway, thanks for the investigation! I have some comments.

File: pkg/cmd/grafana-cli/commands/install_command.go (hunk 1 above)
Comment (andresmgot) [reply pkg/cmd/grafana-cli/commands/install_command.go:22]: you can remove it then :)

**Review by andresmgot — APPROVED** [review]
LGTM

**Comment by oshirohugo** [comment]
@wbrowne could you please take a look. There was a change on the first proposal after @andresmgot suggestions and now we are failing the command.

File: pkg/cmd/grafana-cli/commands/install_command.go [hunk 3]
```diff
@@ -19,7 +19,13 @@ import (
 	"github.com/grafana/grafana/pkg/plugins/storage"
 )
 
-func validateInput(c utils.CommandLine, pluginFolder string) error {
+const installArgsSize = 2
+
+func validateInput(c utils.CommandLine) error {
+	if c.Args().Len() > installArgsSize {
+		return errors.New("install only supports 2 arguments: plugin and version")
```
Comment (wbrowne) [inline pkg/cmd/grafana-cli/commands/install_command.go:26]: Maybe before we return the error here, we should add a log with something more descriptive to hopefully help the user form the right command.

For example:

```
./bin/darwin-amd64/grafana cli plugins install autohome-comparequeries-datasource --debug --pluginUrl /Users/wbrowne/Downloads/autohome-comparequeries-datasource.zip                                           
Please specify the correct format. For example ./grafana cli (<command arguments>) plugins install <plugin ID> (<plugin version>)

Error: ✗ install only supports 2 arguments: plugin and version
```

```suggestion
		logger.Info(color.RedString("Please specify the correct format. For example ./grafana cli (<command arguments>) plugins install <plugin ID> (<plugin version>)\n\n"))
		return errors.New("install only supports 2 arguments: plugin and version")
```


Maybe @sympatheticmoose/@josmperez can weigh in here on best lingo

**Review by wbrowne — COMMENTED** [review]
A shame about the CLI package limitations, but definitely an improvement. Had an idea about potentially adding a log statement.

Think it would be good to follow this PR up with version field validation to avoid the possibility of using an "incorrect" single argument where version should be (like what @andresmgot mentioned in a comment).

Great work!

File: pkg/cmd/grafana-cli/commands/install_command.go (hunk 3 above)
Comment (wbrowne) [reply pkg/cmd/grafana-cli/commands/install_command.go:26]: For reference, this would look like:
image

**Review by wbrowne — APPROVED** [review]
LGTM
