### PR TITLE
Prometheus: Fuzzy search for metric names in Code Mode

### LINKED ISSUE #66402: Bug: Prometheus Query Field block user input unnecessarily
**What happened**:
Prometheus query field is blocked by autocomplete suggestions. Below is a gif recording what happened when I tried to type multiple character quickly in the query field.

type-err

**What you expected to happen**:
Prometheus query field to not blocked by autocomplete suggestions

**How to reproduce it (as minimally and precisely as possible)**:
I have a branch that can simulate the issue: https://github.com/qingwei91/grafana/commit/0705288316fb7577d82e92e16d89ba5a79c7019e
To reproduce, you can
1. Pull my branch
2. Setup prometheus locally by running `docker run -p 9090:9090 prom/prometheus`
3. Run grafana locally using `yarn start`
4. Open grafana from browser, install prometheus datasource to `http://localhost:9090`
5. Go to `explore` view, type something like `rrrr` consecutively.

**Anything else we need to know?**:
This is mainly a problem with large number of metric names, the same problem might exists for other datasource too, but I havent tested that out.

**Environment**:
- Grafana version: 9.4.3 to 9.4.7
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: Prometheus
- Others:

----------------
**Discussion**:

I am keen to help fix this assuming we agree this is not desired, I wish to get your thoughts on what's the best way on fixing this.

Ideally, I think we should avoid blocking user input. I am not a frontend expert, I can think of a few naive way:

1. Move the compute to web worker
2. Chunk the computation into smaller pieces so that we can queue them separately to the event loop
3. Make use of the CancelationToken from Monaco editor, similarly we need to chunk the computation to give chance to cancel computation, but Monaco editor isnt very well documented on this front, so I am not entirely what triggers a cancelation.

I don't fully understand the Monaco code, its not easy to track because apparently it comes from vscode directly, so I am not sure how the suggestions produced by our `completionProvider` is used. One easier fix might be to limit the no of suggestion produced upstream, in my case, our deployed prometheus has 30 millions metric name, maybe auto-complete can be imperfect and just make use of top N results.

Kind regards

### LINKED ISSUE #84612: Prometheus: Improve Code Mode autocomplete performance for large numbers of metric names
**Why is this needed**:

When a Prometheus instance has an enormous number of unique metric names (on the order of many hundreds of thousands, or millions), it takes a long time (single to double-digit seconds) to load metric names to power the autocomplete experience in [Code Mode][code-mode]. Rendering such a large volume of label names in the Monaco editor can freeze the UI.

**What would you like to be added**:

When the number of metric names exceeds threshold value _n_ (10k by default, but configurable by the user), use fuzzy search to provide only the _n_ best metric name matches to the Monaco editor's pool of autocomplete values.

**Who is this feature for?**

Prometheus data source users, especially those with hundreds of thousands to millions of unique metric names.

[code-mode]: https://grafana.com/docs/grafana/latest/datasources/prometheus/query-editor/#code-mode

**Tasks**

- [x] Use fuzzy search to restrict results to the 10k-most relevant metric names
  - [x] Associated tests
- [x] Configure the Monaco editor to update suggestions as input changes, but only when fuzzy search is active
  - [x] Associated tests
- [x] Allow threshold value _n_ to be configurable by the user
- [x] Add tooltip-esque disclaimer when fuzzy search is active
- [x] Put new functionality behind a feature flag

### PR DESCRIPTION
**Pull request by NWRichmond**
## What is this feature?

A performance boost for the Prometheus data source's [Code Mode][code-mode], when a Prometheus instance has hundreds of thousands or millions of metric names.

### How it works

In Code Mode, if there are more than _n_ metric names (where `n=10000` by default, configurable by the user), we no longer attempt to provide the Monaco Editor with all metric names as possible autocomplete suggestions. Instead, we use fuzzy search (powered by [`@leeoniya/ufuzzy`](https://github.com/leeoniya/uFuzzy)) to provide only the _n_-most relevant metric names to the Monaco editor as possible autocomplete suggestions.

#### Performance

The resulting performance boost is very noticeable as the number of metric names gets into the hundreds of thousands. With a casual, unscientific test with 750,000 metric names, I observed an ~89% decrease in the longest-running [tasks](https://web.dev/articles/optimize-long-tasks) while typing in the code editor:

<details>
  <summary>Performance test: the "before" state</summary>

  When typing, [tasks](https://web.dev/articles/optimize-long-tasks#what_is_a_task_what-is-tasks) took between 1080-2070ms.

suggestions perf before fix
</details>

<details>
  <summary>Performance test: with fuzzy search</summary>

  When typing, [tasks](https://web.dev/articles/optimize-long-tasks#what_is_a_task_what-is-tasks) took between 130-203ms.

suggestions perf after fix
</details>

#### UI changes

The metric names fuzzy search is configured to prioritize rendering performance and single typos. Consequently, when search is active, the autocomplete will not include some suggestions that Monaco would normally display. For that reason, this PR introduces a disclaimer about the autocomplete results when metric names fuzzy search is active. The disclaimer UI only appears when metric names are in excess of the configured threshold:

https://github.com/grafana/grafana/assets/5732000/5efa88c1-bd13-4ce3-9eff-ba2c52fe3102

This PR also adds a new configuration parameter in the **Performance** section. It allows users to configure the number of metric names suggestions in Code Mode if the 10,000 default doesn't suit their needs:

https://github.com/grafana/grafana/assets/5732000/1a7882a5-b713-46e4-af0c-fa58cab9856f

## Why do we need this feature?

As described in #84612, when a Prometheus instance has an enormous number of unique metric names (on the order of many hundreds of thousands, or millions), it takes a long time (single to double-digit seconds) to load metric names to power the autocomplete experience in [Code Mode][code-mode]. Rendering such a large volume of label names in the Monaco editor can freeze the UI.

## Who is this feature for?

Prometheus data source users whose Prometheus instances have hundreds of thousands (or more) of metric names.

## Which issue(s) does this PR fix?

Fixes #84612 

## Special notes for your reviewer

- This is my first experience with creating a new feature toggle. I'd appreciate extra focus on the implementation of the `prometheusCodeModeMetricNamesSearch`.
- To simplify the review process, I've only made Prometheus data source changes in  `packages/grafana-prometheus`. These changes will also need to be copied over to `public/app/plugins/datasource/prometheus`. I'll do that after we're aligned on the changes.
- If running this locally, you'll need to enable two feature toggles in `custom.ini`: 
  - `usePrometheusFrontendPackage`
  - `prometheusCodeModeMetricNamesSearch`

## To-do before merging

- [x] Copy updates from `packages/grafana-prometheus` to `public/app/plugins/datasource/prometheus`

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

[code-mode]: https://grafana.com/docs/grafana/latest/datasources/prometheus/query-editor/#code-mode

### CODE REVIEW

File: packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts
Comment (NWRichmond) [inline packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts:1]: This is a refactor of the `dataProvider` that was in `components/monaco-query-field/MonacoQueryField.tsx`

File: pkg/services/store/testdata/public_testdata.golden.jsonc
Comment (NWRichmond) [inline pkg/services/store/testdata/public_testdata.golden.jsonc:1]: I'm not sure why this differs from `main`

File: packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/completions.ts [hunk 1]
```diff
@@ -16,25 +22,45 @@ type Completion = {
...
-  getSeriesLabels: (selector: string, otherLabels: Label[]) => Promise<string[]>;
-};
+export function fuzzySearchMetrics(haystack: Metric[], needle: string): Metric[] {
+  const filteredMetrics: Metric[] = [];
+  const metricNames = haystack.map((metric) => metric.name);
+  const [idxs] = metricNamesSearchClient.search(metricNames, needle);
 
-// we order items like: history, functions, metrics
+  for (const idx of idxs ?? []) {
+    const metric = haystack.at(idx);
```
[the remark this answers is not in the document]
Comment (NWRichmond) [reply packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/completions.ts]: For curious minds: array access is ~11% faster than `Array.prototype.at`:

jsperf-array-access-vs-array-prototype-at

[the remark this answers is not in the document]
Comment (leeoniya) [reply packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/completions.ts]: what does this look like with 10k values and with a `for` loop instead of forEach callback?

[the remark this answers is not in the document]
Comment (leeoniya) [reply packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/completions.ts]: thanks!

good to know. last time i checked .at() was like 50% slower. maybe it's catching up :)

generally when iterating possibly thousands of values, i try to stick with for loops and direct access since they're the most optimized in js VMs.

File: packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/completions.ts [hunk 2]
```diff
@@ -16,25 +22,45 @@ type Completion = {
...
 };
 
-type Metric = {
-  name: string;
-  help: string;
-  type: string;
-};
+const metricNamesSearchClient = new UFuzzy({
+  intraMode: 1,
+  intraChars: '[a-z0-9_:]', // characters allowed in metric names, according to the Prometheus data model
```
[the remark this answers is not in the document]
Comment (NWRichmond) [reply packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/completions.ts:27]: I just did some local testing...looks like using the default `intraChars` setting changes the results.

I created an array of metric names containing valid Prometheus characters like `_` and `:`, e.g.:
```js
["metric_0_tes:ting_delimiters","metric_1_tes:ting_delimiters",...]
```

When I use the default `intraChars`, I'm getting no matches on needles `gdeli` or `sting`. But those needles return matches when using `intraChars: '[a-z0-9_:]'`.

Here are the findings (note the `filteredMetricNames.length`):

### With default `intraChars` (`[a-z\d']`)

Needle: `gdeli`

default-intrachars-input-gdeli-filteredMetricNames-length-0

Needle: `sting`

default-intrachars-input-sting-filteredMetricNames-length-0

### With `intraChars: '[a-z0-9_:]'

Needle: `gdeli`

prom-data-model-intrachars-input-gdeli-filteredMetricNames-length-10k

Needle: `sting`

prom-data-model-intrachars-input-sting-filteredMetricNames-length-10k

[the remark this answers is not in the document]
Comment (NWRichmond) [reply packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/completions.ts:27]: Per external discussion, it seems that in order to optimize the user experience (by having minimal changes to autocomplete results when metric name search is active), the key is to operate in [`intraMode: 0`, with `intraIns: Infinity` and `intraChars: '.'`](https://github.com/leeoniya/uFuzzy?tab=readme-ov-file#options).

Many thanks, @leeoniya!

[the remark this answers is not in the document]
Comment (NWRichmond) [reply packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/completions.ts]: In https://github.com/grafana/grafana/pull/85396/commits/5428287c8891045814ba5c6e704f7265f04d9b81, I updated the settings to match option 2 above after comparing the performance between the two options. While option 1 did a great job at not changing the autocomplete results when search is active, it's almost twice as slow with large metric name arrays (tested 50k up to 2M). So until users demand closer matches, let's err on the side of performance and a fluid user experience.

File: packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+  }
+
+  private enableAutocompleteSuggestionsUpdate(): void {
+    this.suggestionsIncomplete = true;
+    dispatchEvent(
+      new CustomEvent(CODE_MODE_SUGGESTIONS_INCOMPLETE_EVENT, {
+        detail: { limit: this.metricNamesSuggestionLimit, datasourceUid: this.languageProvider.datasource.uid },
+      })
+    );
+  }
```
Comment (bohandley) [inline packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts:95]: Running locally, I'm having trouble seeing the listener catch this event in the component `PromQueryCodeEditorAutocompleteInfo.tsx` that shows the warning. I might be missing something, but having trouble following the logic to get the warning to show up

**Comment by catherineymgui** [comment]
From a UX perspective:
- Would shorten the tooltip after "autocomplete suggestions limited" to

> The number of metric names exceeds the autocomplete limit. Only the n-most relevant metrics are displayed. You can adjust the threshold in the data source settings.

- Would put the info icon after the text

- In the configuration page - update tooltip to
> The maximum number of metric names that may appear as autocomplete suggestions in the query editor's Code mode.

File: packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts (hunk 3 above)
Comment (NWRichmond) [reply packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts:95]: Sorry about that, @bohandley! There was a regression. Fixed now, by https://github.com/grafana/grafana/pull/85396/commits/49f8ce5bcfd4aef528a8c490c32e06b5b8373ce7:

https://github.com/grafana/grafana/assets/5732000/97a52405-c9ff-442c-ab61-7958801bea3d

**Review by catherineymgui — APPROVED** [review]

File: packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts (hunk 3 above)
Comment (bohandley) [reply packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts:95]: Beautiful! Works like a charm. Fantastic work on this!!!

**Review by bohandley — APPROVED** [review]
Excellent work! 🚀🚀🚀

File: packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/completions.ts [hunk 4]
```diff
@@ -176,19 +187,19 @@ async function getLabelValuesForMetricCompletions(
...
     case 'AT_ROOT': {
       return getAllFunctionsAndMetricNamesCompletions(dataProvider);
     }
     case 'EMPTY': {
-      const metricNames = await getAllMetricNamesCompletions(dataProvider);
-      const historyCompletions = await getAllHistoryCompletions(dataProvider);
-      return [...historyCompletions, ...FUNCTION_COMPLETIONS, ...metricNames];
+      const metricNames = getAllMetricNamesCompletions(dataProvider);
+      const historyCompletions = getAllHistoryCompletions(dataProvider);
+      return Promise.resolve([...historyCompletions, ...FUNCTION_COMPLETIONS, ...metricNames]);
```
Comment (itsmylife) [inline packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/completions.ts:202]: Do you think we should use `Promise.all()` here?

File: packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts [hunk 5]
```diff
@@ -0,0 +1,117 @@
+import { HistoryItem } from '@grafana/data';
+// @ts-ignore
+import type { Monaco } from '@grafana/ui';
```
Comment (itsmylife) [inline packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts:3]: Do we need this? What happens when we remove this import?

File: packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts [hunk 6]
```diff
@@ -0,0 +1,117 @@
...
+    this.metricNamesSuggestionLimit = this.languageProvider.datasource.metricNamesAutocompleteSuggestionLimit;
+    this.suggestionsIncomplete = false;
+    this.getSeriesLabels = this.languageProvider.getSeriesLabels.bind(this.languageProvider);
+    this.getSeriesValues = this.languageProvider.getSeriesValues.bind(this.languageProvider);
+    this.getAllLabelNames = this.languageProvider.getLabelKeys.bind(this.languageProvider);
+    this.getLabelValues = this.languageProvider.getLabelValues.bind(this.languageProvider);
+  }
+
+  getHistory(): string[] {
+    return this.historyProvider.map((h) => h.query.expr).filter((expr) => expr !== undefined);
```
Comment (itsmylife) [inline packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts:67]: We don't check against `null`. Do you think we should use `filter(Boolean)`?

Additionally, can't we do filtering without mapping?: 
```
return this.historyProvider.filter((h) => h.query.expr !== undefined);
```

File: packages/grafana-prometheus/src/querybuilder/components/PromQueryCodeEditorAutocompleteInfo.tsx [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+        setAutocompleteLimitExceeded(true);
+        setAutocompleteLimit(e.detail.limit.toString());
+      }
+    };
+
+    addEventListener(CODE_MODE_SUGGESTIONS_INCOMPLETE_EVENT, handleSuggestionsIncompleteEvent);
+
+    return () => {
+      removeEventListener(CODE_MODE_SUGGESTIONS_INCOMPLETE_EVENT, handleSuggestionsIncompleteEvent);
+    };
```
Comment (itsmylife) [inline packages/grafana-prometheus/src/querybuilder/components/PromQueryCodeEditorAutocompleteInfo.tsx:39]: ❤️

File: packages/grafana-prometheus/src/querybuilder/components/PromQueryCodeEditorAutocompleteInfo.tsx [hunk 8]
```diff
@@ -0,0 +1,67 @@
...
+        return;
+      }
+
+      if (e.detail.datasourceUid === props.datasourceUid) {
+        setAutocompleteLimitExceeded(true);
+        setAutocompleteLimit(e.detail.limit.toString());
+      }
+    };
+
+    addEventListener(CODE_MODE_SUGGESTIONS_INCOMPLETE_EVENT, handleSuggestionsIncompleteEvent);
```
Comment (itsmylife) [inline packages/grafana-prometheus/src/querybuilder/components/PromQueryCodeEditorAutocompleteInfo.tsx:35]: I know the datasourceUid is not gonna change and if it changes, we will be in a new datasource. But is that a safe practice to have the event handler in `useEffect`? The feature is working well and not saying we should change this but just want to question if that's safe :)

**Review by itsmylife — APPROVED** [review]
Looks fantastic 🚀 
I just added a couple of questions. This is good to go!

File: packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts (hunk 5 above)
Comment (NWRichmond) [reply packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts:3]: If we remove this, it breaks the TSDoc [`@link`](https://tsdoc.org/pages/tags/link) below.

With Monaco type import:
tsdoc link Monaco Range

Without:
broken tsdoc link Monaco Range

If you feel the `@link` is of questionable value, I'm happy to remove it.

File: packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/completions.ts (hunk 4 above)
Comment (NWRichmond) [reply packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/completions.ts:202]: `getAllMetricNamesCompletions` and `getAllHistoryCompletions` used to be `async`, but aren't `async` anymore and do not return promises.

File: packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts (hunk 6 above)
Comment (NWRichmond) [reply packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts]: > Do you think we should use filter(Boolean)?

Totally! Updated in 91c272c3fd0e025af3904c2a13ba38e9afe439b1.

> Additionally, can't we do filtering without mapping?
> ```
> return this.historyProvider.filter((h) => h.query.expr !== undefined);
> ```

We still need to map to get the `query.expr` from each history item (return type should be `string[]` and not `HistoryItem<PromQuery>[]`).

File: packages/grafana-prometheus/src/querybuilder/components/PromQueryCodeEditorAutocompleteInfo.tsx (hunk 8 above)
Comment (NWRichmond) [reply packages/grafana-prometheus/src/querybuilder/components/PromQueryCodeEditorAutocompleteInfo.tsx:37]: Probably best to have it in a `useCallback`, since it's relying on a prop.

Updated in 065f2bd097c3db55a09a8ede82088ffd0a2973d3 :)

File: packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts (hunk 5 above)
Comment (itsmylife) [reply packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts]: Do you mind commenting on this over there? It will help us in the future I believe.

Comment (NWRichmond) [reply packages/grafana-prometheus/src/components/monaco-query-field/monaco-completion-provider/data-provider.ts]: Certainly! Updated in https://github.com/grafana/grafana/pull/85396/commits/7b9510c29586c8402cd87872b99f5d580d66e44e.
