### PR TITLE
Logs panel: Make it possible to copy first and last line

### LINKED ISSUE #24862: Log panel can't copy first line
**What happened**:
When using the log panel, and I want to copy a traceID from the first log line I can't because of the top header bar that shows up.

See those screenshots:
image
image

**What you expected to happen**:

Being able to copy the first log line.

**How to reproduce it (as minimally and precisely as possible)**:

Try to copy the first line of a log panel.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.1.0-ac486de9pre (26964b383f)
- Data source type & version: Loki

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
We are adding a padding to bottom so the last log line can be copied and also padding to the top so the first log line can be copied if no Panel title is set.

Before top: 
image

After top: 
image

Before bottom: 
Screenshot 2021-06-09 at 12 16 20

After bottom:
image

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/24862#event-4863580672

### CODE REVIEW

File: public/app/plugins/panel/logs/LogsPanel.tsx [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import React from 'react';
-import { LogRows, CustomScrollbar } from '@grafana/ui';
+import { css } from 'emotion';
```
Comment (Elfo404) [inline public/app/plugins/panel/logs/LogsPanel.tsx:2]: as per https://emotion.sh/docs/emotion-11#package-renaming
```suggestion
import { css } from '@emotion/css';
```

we don't directly depend on `emotion`, it's installed as a transient dependency of `react-diff-viewer`

**Review by Elfo404 — CHANGES_REQUESTED** [review]
Nice thought checking the title to conditionally apply the styles 👍 

just a comment about importing `css` from `emotion`, but otherwise looks good!

**Comment by ivanahuckova** [comment]
@Elfo404 good catch, I have commited your suggestions.

**Review by Elfo404 — APPROVED** [review]
