### PR TITLE
TimeSeries: Improve keyboard focus and fix spacebar override

### LINKED ISSUE #86832: TimeSeries panel: Label button not clickable with space
**Steps to reproduce**:

Sub task of #79627

Create a panel with at least two labels. Focus them with the keyboard. Try to press space. Using Enter works, and that's the behaviour we want.

It seems that space can be used when zooming in, similar to just clicking, which I think overrides this behaviour. It makes sense to have that on the actual graph area, but if a label is focus that should not be the case.

**Actual Result**:

https://github.com/grafana/grafana/assets/1438972/c87b46d1-d646-4339-9da3-0905770e4638

**Expected Result**

https://github.com/grafana/grafana/assets/1438972/ce4118fe-1ff7-46a4-90a0-fdf229dfcf13

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)
2.11
**Environment**:
- Grafana version:
- Data source type & version:
- User OS & Browser:
- Others:

### PR DESCRIPTION
**Pull request by tskarhed**
**What is this feature?**

Makes the graph focusable and removes bug with labels and spacebar

https://github.com/grafana/grafana/assets/1438972/9db36377-c070-47b5-abc1-6436056eef2b

Some ideas may be found in #42244

KeyboardPlugin looks for the closest parent with tabindex, hence overrides when space is being used on the label, because they have the same tabindex parent. This is now fixed by setting it dynamically to the uPlot root.

**Why do we need this feature?**

Improves keyboard interaction.

**Who is this feature for?**

Keyboard users
**Which issue(s) does this PR fix?**:

Fixes #86832

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/VizLayout/VizLayout.tsx [hunk 1]
```diff
@@ -95,7 +95,10 @@ export const VizLayout: VizLayoutComponentType = ({ width, height, legend, child
 
   return (
     <div style={containerStyle}>
-      <div className={styles.viz}>{size && children(size.width, size.height)}</div>
+      {/* eslint-disable-next-line jsx-a11y/no-noninteractive-tabindex -- Interactivity set by KeyboardPlugin*/}
+      <div aria-label="Graph" tabIndex={0} className={styles.viz}>
```
[the remark this answers is not in the document]
Comment (tskarhed) [reply packages/grafana-ui/src/components/VizLayout/VizLayout.tsx:99]: Also, zooming with spacebar behaves weirdly sometimes.

**Comment by tskarhed** [comment]
ToolTipPlugin2 interferes with the keyboard interactions. It seem like a MouseEvent is created when rendering the tooltip, which causes the timeseries cursor to disappear.

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin2.tsx [hunk 2]
```diff
@@ -543,8 +543,8 @@ export const TooltipPlugin2 = ({
 
       const event = plot!.cursor.event;
 
-      // if not viaSync, re-dispatch real event
-      if (event != null) {
+      // if not viaSync, re-dispatch real event and prevent unattached MouseEvent from being dispatched
+      if (event != null && event.currentTarget != null) {
```
Comment (tskarhed) [inline packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin2.tsx:547]: @leeoniya I have no idea if this breaks some case. When the tooltip was rendering, the event appearing here was a MouseEvent, which was then dispatched and caused the crosshair disappearing.

Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin2.tsx:547]: sounds good, i'll check today

File: public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx
Comment (leeoniya) [inline public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx:1]: maybe let's leave out unreleated cleanups for now?

File: packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin2.tsx (hunk 2 above)
Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin2.tsx:547]: doesnt seem to affect the behavior this code was added to fix, so LGTM.

i appreciate that you found a clean solution here :trophy:. this plugin's code is not the easiest to follow, but it needs to be really high perf, so there's a lot of React-ism stuff being juggled.

Comment (leeoniya) [reply packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin2.tsx]: upon further testing, it looks like `currentTarget` is always null, because it's only available during the event bubbling phase, but here we're dispatching the event after the fact. the reason it still worked is because setCursor below it still worked _almost_ the same way, but not quite.

i pushed a different fix with a comment explaining what was going on.

**Review by leeoniya — APPROVED** [review]
