### PR TITLE
fix #103209: fix access for tables with nullable data

### LINKED ISSUE #103209: Table Panel: Text wrapping causes error when fields are missing
### What happened?

When using a Table panel with "Wrap text" enabled, combined with the Extract fields and Organize fields by name transformations, the panel throws the following JavaScript error:

Image

This happens when the data contains missing fields — if one record has a field and another doesn't.

The error originates from the [guessLongestField](https://github.com/grafana/grafana/blob/f85866f8690d28986392f93ba941c792e152121e/packages/grafana-ui/src/components/Table/utils.ts#L735) function, where `field.values[0].length` is accessed without checking if `field.values[0]` is defined.

Related issue: #91168 was closed due to being unreproducible, but this report includes clear reproduction steps.

https://github.com/user-attachments/assets/33d770e7-05ff-4856-85a3-1c9039ef3f1a

### What did you expect to happen?

The table should render normally, even when some fields are missing from parts of the dataset. No error should be thrown.

### Did this work before?

Unknown

### How do we reproduce it?

1. Create a Table panel.
2. Use this data:
    ```javascript
    [
      { "id": "12345678901234567890123456789012" },
      { "id": "12345678901234567890123456789012", "port": "3000" }
    ]
    ```
3. Enable `Wrap text` in the table display options.
4. Apply the following transformations:
    - Extract fields
    - Organize fields by name

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: v11.5.2 and v11.6.0

### Grafana platform?

A downloaded binary

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by fastfrwrd**
**What is this feature?**

fixes an error in a Table util.

**Who is this feature for?**

Users of table who enable auto-wrap cells, and who have data which is nullable in at least one of their string columns.

**Which issue(s) does this PR fix?**:

Fixes #103209

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-ui/src/components/Table/utils.ts [hunk 1]
```diff
@@ -729,12 +729,11 @@ export function guessLongestField(fieldConfig: FieldConfigSource, data: DataFram
...
 
-      // If we have less than 30 values we assume
-      // that the first record is representative
-      // of the overall data
+      // If we have less than 30 values we assume that the first
+      // non-null record is representative of the overall data
       if (numValues <= 30) {
         for (const field of stringFields) {
-          const fieldLength = field.values[0].length;
+          const fieldLength = field.values.find((v) => v != null)?.length ?? 0;
```
Comment (fastfrwrd) [inline packages/grafana-ui/src/components/Table/utils.ts:736]: smoking gun for me: revert this line and watch the test fail, then watch it pass once you re-apply it.

**Review by jesdavpet — APPROVED** [review]
🕵️ Nice sleuthing!
