### PR TITLE
Correlations: Account for restricted datasource

### LINKED ISSUE #70714: Explore: All queries fail when Correlations are in use and Datasource Permissions are used to restrict a Correlations datasource.
### 
# What went wrong?

**What happened**:

  -  I had an environment where Grafana Correlations was in use with a couple of correlations configured
  - Datasource Permissions (Enterprise feature) was also in use and had been configured to remove access to one of the datasources involved in a correlation
  - Sending any query to any data source via Explore (or jumping from a panel to Explore with the context menu) resulted in this error:
image
image
```
TypeError: Cannot read properties of undefined (reading ‘uid’)
    at utils.ts:25:88
    at Array.filter (<anonymous>)
    at utils.ts:25:45
    at Array.forEach (<anonymous>)
    at z (utils.ts:19:14)
    at decorators.ts:98:7
    at map.js:7:37
    at E._next (OperatorSubscriber.js:15:21)
    at M.next (Subscriber.js:34:18)
    at map.js:7:24
```

- Diving further into the developer console revealed that the above error was coming from Correlations, as it seems to do some sort of check against every correlation data source every time an Explore query is run
- Removing the restricted permission on the correlation datasource resolved the issue (after refreshing Grafana)
- Re-adding a restricted permission on a correlation datasource caused the issue to come back (after refreshing Grafana)

**What did you expect to happen**:

  - I expected Explore queries to succeed as normal

### 
# How do we reproduce it?

**Step 1**:

- Configure any Correlation using Grafana Correlations

**Step 2**:

- Remove the ability to Query one of the datasources from the Correlation using [Datasource Permissions](https://grafana.com/docs/grafana/latest/administration/data-source-management/#data-source-permissions)
- This actually makes the datasource invisible to restricted users

**Step 3**:

- Now go to Explore as a restricted user from your permissions (e.g. an Editor) and try to query any data source
- You should see the error `Cannot read properties of undefined (reading ‘uid’)`

### 
# What Grafana version are you using?

Grafana Enterprise v10.0.1 (5a30620b85)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

Pop!_OS latest

### User's Browser?

Latest Firefox and Chrome both see it.

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

Note: While this requires an Enterprise feature to occur, datasource permissions have always functioned this way where removing the "Query" permission makes the datasource invisible. 

So, I've filed this bug against Grafana rather than Grafana Enterprise but feel free to move if appropriate.

cc @gelicia - I have this in an internal environment for easy debugging if needed

### PR DESCRIPTION
**Pull request by gelicia**
**What is this feature?**

Fix a bug where restricting an individual datasource broke all other queries due to correlation lookup.

When we get the list of correlations, we query the datasources the user has access to to get more information about the datasource off of the datasource UID. If the user doesn't have access to that datasource, that query returns undefined. 

This changes how we retrieve that information to filter out correlations that have a datasource the user doesn't have access to. 

This also adds some error handling if a user attempts to create or edit a correlation on a UID they dont have access to from the front end.

Note: the root cause of this is the initial correlations fetch retrieves every correlation that exists. In #65241 we change this query to only retrieve correlations the user has selected in their queries. Since a user cannot select a datasource they do not have access to, this scenario thus becomes impossible. 

**Why do we need this feature?**

Enterprise users who do not have access to a datasource with a correlation cannot run queries

**Which issue(s) does this PR fix?**:

Fixes #70714

**Special notes for your reviewer:**
Replication steps
1. Run enterprise
2. From your admin user, create a new user with the editor role and save
3. From that same admin user, find a datasource that's used for a source of a datasource
4. Remove the permission that editors can view that datasource and save
5. From an incognito window, log in with the user created in step 2
6. Go to explore and attempt to run a query from any datasource you have access to
7. Previously, would error. Now, does not.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

File: public/app/features/correlations/utils.ts [hunk 1]
```diff
@@ -31,7 +31,9 @@ export const attachCorrelationsToDataFrames = (
       dataSourceUid = dataFrameRefIdToDataSourceUid[formattedRefID];
     }
 
-    const sourceCorrelations = correlations.filter((correlation) => correlation.source.uid === dataSourceUid);
+    const sourceCorrelations = correlations.filter((correlation) => {
+      return correlation.source ? correlation.source.uid === dataSourceUid : false;
+    });
```
Comment (Elfo404) [inline public/app/features/correlations/utils.ts:36]: should we change the `CorrelationData` type accordingly?

Comment (gelicia) [reply public/app/features/correlations/utils.ts:36]: @Elfo404 actually, we can be smarter about this and filter out correlations that don't have sources when we fetch them. I'll do that instead.

**Review by harisrozajac — APPROVED** [review]
Looks good!

**Review by ifrost — APPROVED** [review]
Nice one! Do you think we should remove the code in 10.1.x once pagination is merged in? Or maybe we could add some comments (or a test) explaining why it was added?

**Comment by gelicia** [comment]
> Nice one! Do you think we should remove the code in 10.1.x once pagination is merged in? Or maybe we could add some comments (or a test) explaining why it was added?

The code is still a worthwhile safeguard and I’ll follow up with a test for this
