### PR TITLE
Bugfix: Prevent previous query editor to set default values when changing data source

### LINKED ISSUE #60005: Plugins Platform: onChange - previously selected data source can update the query of the newly selected data source
**What happened**:
When a user changes data source in panel edit mode, the previously selected data source can update the query of the newly selected data source. This happens when the data source calls `onChange`  immediately during the first render of the editor to set query default values.

**What you expected to happen**:
Guard against this being possible. 

**Possible mitigation**:
When changing the data source, and the data source does not implement importQueries or doesn't support abstract queries, then all queries should be just cleared completely.

**Mitigation in the plugin**:
https://github.com/grafana/grafana/issues/58205

**How to reproduce it (as minimally and precisely as possible)**:
- Some more details (only accessible internally): https://github.com/grafana/support-escalations/issues/4491#issuecomment-1338996560
- https://github.com/grafana/support-escalations/issues/4577#issuecomment-1341064127

### PR DESCRIPTION
**Pull request by mckn**
**What is this feature?**
Bug fix to prevent the previous query editor from setting default values to the query passed to next query editor of the newly selected data source.

**Why do we need this feature?**
We have a bug in the current flow when changing data sources. It only occur for data source plugins that sets default values to the query on the initial render of the query editor.

**Who is this feature for?**
Everyone

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/support-escalations/issues/4577
Fixes https://github.com/grafana/grafana/issues/60005
Fixes https://github.com/grafana/support-escalations/issues/4491

**Special notes for your reviewer**:
The rendering flow is something like this when changing the data source:

- Data source id changed
- Query will be cleared
- Start loading new ds into state
- Render query editor for the ds in state with empty query.
- Query editor for ds in state will set default values to the empty query.
- Finished loading new ds into state.
- Render query editor for the ds in state with query containing default values from previous ds.
- New query editor might not be able to handle the default values from the previous editor (things break).

### CODE REVIEW

**Comment by aangelisc** [comment]
I can also confirm that the original issue is fixed and I can change datasources correctly. However, this fix seems to have introduced another bug where updating the datasource properties doesn't trigger the query to be run immediately. 

To reproduce:

- Select the Azure Monitor datasource.
- Choose any resource to query.
- Select any metric name, the data will not be loaded.
- Change the metric name to an alternative one. The data for the previous metric will be loaded. 

The same can also be seen for the Cloudwatch datasource. You can see from the network tab that the `eval` request does not get called until the query parameters are updated a second time.

File: public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx [hunk 1]
```diff
@@ -278,6 +285,19 @@ function copyModel(item: AlertQuery, uid: string): Omit<AlertQuery, 'datasource'
...
 }
 
+function emptyModel(item: AlertQuery, uid: string): Omit<AlertQuery, 'datasource'> {
+  return {
+    refId: item.refId,
+    relativeTimeRange: item.relativeTimeRange,
+    queryType: '',
+    datasourceUid: uid,
+    model: {
+      refId: item.refId,
```
Comment (sunker) [inline public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx:295]: While working on adding support for defining a default query, I wasn't aware unified alerting had it's own query rows renderer. That means default queries defined by the data source will be ignored in the alerting ui. 

If you want to, you spread the default query to the alert query model here.
```typescript
function emptyModel(
  item: AlertQuery,
  ds: DataSourceApi<DataQuery, DataSourceJsonData, {}>
): Omit<AlertQuery, 'datasource'> {
  return {
    refId: item.refId,
    relativeTimeRange: item.relativeTimeRange,
    queryType: '',
    datasourceUid: ds.uid,
    model: {
      ...ds?.getDefaultQuery?.(CoreApp.UnifiedAlerting),
      refId: item.refId,
      hide: false,
    },
  };
}
```

Maybe then this function should be called `newModel` rather than `emptyModel`. 

But let me know if you want me to do this in a separate PR.

**Review by sunker — COMMENTED** [review]
Tested and seems like this is solving the problem mentioned in [this](https://github.com/grafana/support-escalations/issues/4491#issuecomment-1338996560) escalation. 

I was not able to repro the issue you described @aangelisc.

File: public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx (hunk 1 above)
Comment (mckn) [reply public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx:295]: Ah, this is great! i will apply your suggestion. Thanks 🙏🏻

**Comment by mckn** [comment]
> this

Thank you, I can reproduce that locally however it works the same way in `main`. So I don't think this behavior is something introduced by my PR.

**Comment by mckn** [comment]
> @sunker have a look at this GIF and let me know if you can reproduce it this way. Otherwise it'll be something weird with my local.
> 
> AlertingExample mov [ AlertingExample mov ](https://user-images.githubusercontent.com/15019026/207614441-259d58b9-c796-45de-86d5-8cd333261ea3.gif) [ ](https://user-images.githubusercontent.com/15019026/207614441-259d58b9-c796-45de-86d5-8cd333261ea3.gif)

I have tested this a bit more in Alerting, Explore and Panel Edit. Seems like there is something odd happening in Explore and Alerting where it doesn't work as expected.

Will continue to investigate what the difference is to make sure we have the same behavior everywhere.

**Comment by sunker** [comment]
> @sunker have a look at this GIF and let me know if you can reproduce it this way. Otherwise it'll be something weird with my local.

I see! I only tested in dashboard edit, not in unified alerting.

**Comment by mckn** [comment]
@aangelisc do you have the same behavior in the `main` branch?

**Comment by aangelisc** [comment]
@mckn you're right! I can also replicate on main so it's a separate bug.

**Review by aangelisc — APPROVED** [review]
Great work, thanks for this 👍

File: public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx [hunk 2]
```diff
@@ -278,6 +288,20 @@ function copyModel(item: AlertQuery, uid: string): Omit<AlertQuery, 'datasource'
...
+function newModel(item: AlertQuery, ds: DataSourceApi): Omit<AlertQuery, 'datasource'> {
+  return {
+    refId: item.refId,
+    relativeTimeRange: item.relativeTimeRange,
+    queryType: '',
+    datasourceUid: ds.uid,
+    model: {
+      ...ds.getDefaultQuery?.(CoreApp.UnifiedAlerting),
+      refId: item.refId,
+      hide: false,
```
Comment (sunker) [inline public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx:300]: Not too familiar with alerting, but you may also want to set data source ref in the model. See how it's done in [panel edit](https://github.com/grafana/grafana/blob/main/public/app/features/query/components/QueryGroup.tsx#L236) for example.

**Review by sunker — APPROVED** [review]
Looks good!

File: public/app/features/query/components/QueryEditorRow.tsx [hunk 3]
```diff
@@ -239,10 +238,20 @@ export class QueryEditorRow<TQuery extends DataQuery> extends PureComponent<Prop
...
+  };
+
   renderPluginEditor = () => {
     const { query, onChange, queries, onRunQuery, onAddQuery, app = CoreApp.PanelEditor, history } = this.props;
     const { datasource, data } = this.state;
 
+    if (this.waitingForDatasourceToLoad()) {
+      return null;
+    }
+
```
Comment (leventebalogh) [inline public/app/features/query/components/QueryEditorRow.tsx:254]: Should we add a quick test-case for this in [QueryEditorRow.test.ts](https://github.com/grafana/grafana/blob/b3087cfcd1d1e2e08538e0c8414daaac3470286e/public/app/features/query/components/QueryEditorRow.test.ts#L0-L1)?

**Review by leventebalogh — APPROVED** [review]
LGTM 👏

File: public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx [hunk 4]
```diff
@@ -96,16 +98,24 @@ export class QueryRows extends PureComponent<Props> {
     );
   };
 
-  onChangeDataSource = (settings: DataSourceInstanceSettings, index: number) => {
+  onChangeDataSource = async (settings: DataSourceInstanceSettings, index: number) => {
     const { queries, onQueriesChange } = this.props;
+    const dataSource = await getDataSourceSrv().get(settings.uid);
```
Comment (gillesdemey) [inline public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx:103]: I'm not quite sure what will happen if this request fails, but I think it might halt script execution. Best to wrap this in a `try...catch` block?

File: public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx (hunk 2 above)
Comment (gillesdemey) [reply public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx:300]: iirc we grab the datasource settings from the `datasourceUid` property from the root (not from the model) and pass that in to the query editor, so no need to have it in the model.

File: public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx (hunk 4 above)
Comment (mckn) [reply public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx:103]: Agree, but I think I will revert the `ds.getDefaultQuery?.` functionality and open an issue for it because I saw that the logic for adding a new query is located in a reducer. So we probably need to this this there as well and it is probably better to do that in both places in a separate PR.

File: public/app/features/query/components/QueryEditorRow.tsx (hunk 3 above)
Comment (mckn) [reply public/app/features/query/components/QueryEditorRow.tsx:254]: I gave it a go but that class is a mess so decided to continue without adding a test. Sorry about this 😢

File: public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx (hunk 4 above)
Comment (mckn) [reply public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx]: I opened this issue: https://github.com/grafana/grafana/issues/61280

Comment (mckn) [reply public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx]: Do you want to give it a go or should I @gillesdemey?

**Comment by torkelo** [comment]
> Query editor for ds in state will set default values to the empty query.

Query editors should never do this

**Comment by torkelo** [comment]
> New query editor might not be able to handle the default values from the previous editor (things break).

The query model was cleared when changing datasource , so how can this be ?

**Comment by mckn** [comment]
> @mckn Just wondering why was this backported to so many old versions?
> 
> Anyway, this breaks data source variable usage (The props.dataSource.uid is just the `${myDS` string) Fix: #61927
> 
> It now needs to be backported to all the same branches, do we know if this patch was released in releases?

Ah, sorry for not answering this one. Totally missed this notification. 

I backported it to all 9.x versions to include the bug fix if we ship any patch versions of 9.x. The issue exists in earlier versions as well but thought it would be good if at a minimum got fixed in Grafana 9.
