### PR TITLE
PublicDashboards: Delete on folder deletion

### LINKED ISSUE #79423: Public Dashboards: Delete public dashboards inside dashboard deletion service
The public dashboard deletion is at the API level, it should be part of the dashboard service delete method.
Also there are other places where the deletion of resources happen (like folders and orgs) and we are not deleting public dashboard with them.
Review the entire code base searching for this issue that is producing orphan public dashboards.

### LINKED ISSUE #98739: Public Dashboards: Data is not deleted alongside folder deletions
### What happened?

If you delete a folder with public dashboards inside, the public dashboard data is not deleted. 

### What did you expect to happen?

The public dashboard data [should be removed](https://github.com/grafana/grafana/blob/main/pkg/services/publicdashboards/service/service.go#L465) when a folder is deleted with public dashboards inside.

I started looking into solutions and originally thought it we could just add the deletion logic [to the dashboard store](https://github.com/grafana/grafana/blob/main/pkg/services/dashboards/database/database.go#L606), but then that will miss the [enterprise deletes](https://github.com/grafana/grafana-enterprise/blob/main/src/pkg/extensions/enterprisepublicdashboards/service/service_wrapper.go#L49), and we can't add the public dashboard service into the dashboard service due to circular dependencies. Also looked into adding it to the folders registry to delete children, but that means it'll be returned in the children count api, which already returns dashboards, which are the same object to the user. So that may not be great. One note, though, the solution needs to not query the dashboard or folders table directly as both as being migrated now to app platform.

### Did this work before?

Yes, it worked up until about a year ago in the api until [this check](https://github.com/grafana/grafana/blob/69adb3d25b485e803f1f830ae5399934e29ca052/pkg/api/dashboard.go#L467) was added. It may have been broken for longer in the frontend, depending on when it switched over to using the folder deletion endpoint. 

### How do we reproduce it?

1. Create a public dashboard inside of a folder
2. Delete the folder
3. Check the database and the data still exists on the public dashboard.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Main

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by evictorero**
**What is this feature?**

Because of a dependency cicle, the public dashboard main service can't be called from the dashboard service.
I moved all the public dashboard deletion code to a service wrapper so that it can be called from the dashboard service.
Now, when a dashboard is deleted this service will be called to take care of public dashboard resources.

In the case of folders, this won't work because the folder service is calling directly the dashboard store layer (instead of the service) so the public dashboard service deletion is also called on folder deletion.

[Enterprise PR](https://github.com/grafana/grafana-enterprise/pull/7766)

Fixes https://github.com/grafana/grafana/issues/98739
Fixes https://github.com/grafana/grafana/issues/79423

**Special notes for your reviewer:**
Whenever a dashboard is deleted the public dashboard service should be called to take care of public dashboards resources.
We can't just add SQL statements to delete table like some Services are doing at this moment.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: pkg/services/dashboards/database/database.go [hunk 1]
```diff
@@ -1043,6 +1043,40 @@ func (d *dashboardStore) CountDashboardsInFolders(
 	return count, err
 }
 
+// GetAllDashboardsUIDsInFolders returns all dashboards associated with the given folder list and orgID.
+// this will return soft deleted dashboards too (deleted IS NOT NULL)
+func (d *dashboardStore) GetAllDashboardsUIDsInFolders(
```
Comment (evictorero) [inline pkg/services/dashboards/database/database.go:1048]: This is a new function in the Dashboard Service since we need a list of dashboards UIDs by folder UID to delete associated public dashboards.

File: pkg/services/dashboards/service/dashboard_service.go [hunk 2]
```diff
@@ -1404,6 +1407,17 @@ func (dr *DashboardServiceImpl) DeleteInFolders(ctx context.Context, orgID int64
...
+	// We need a list of dashboard uids inside the folder to delete related public dashboards
+	dashboardUIDs, err := dr.dashboardStore.GetAllDashboardsUIDsInFolders(ctx, &dashboards.GetAllDashboardsInFolderRequest{FolderUIDs: folderUIDs, OrgID: orgID})
+	if err != nil {
+		return err
+	}
+
+	err = dr.publicDashboardService.DeleteByDashboardUIDs(ctx, orgID, dashboardUIDs)
+	if err != nil {
+		return err
+	}
```
Comment (evictorero) [inline pkg/services/dashboards/service/dashboard_service.go:1419]: Adding public dashboards deletion on `DeleteInFolders` dashboard function.

File: pkg/services/publicdashboards/database/database.go [hunk 3]
```diff
@@ -270,6 +272,30 @@ func (d *PublicDashboardStoreImpl) Delete(ctx context.Context, uid string) (int6
 	return affectedRows, err
 }
 
+// DeleteByDashboardUIDs deletes public dashboards by dashboard uids
+func (d *PublicDashboardStoreImpl) DeleteByDashboardUIDs(ctx context.Context, orgId int64, dashboardUIDs []string) error {
```
Comment (evictorero) [inline pkg/services/publicdashboards/database/database.go:276]: New function

File: pkg/services/dashboards/database/database.go (hunk 1 above)
Comment (stephaniehingtgen) [reply pkg/services/dashboards/database/database.go:1048]: Would it be possible instead to use `SearchDashboards` and pass in the list of folder uids & the org id?

File: pkg/services/folder/folderimpl/folder.go [hunk 4]
```diff
@@ -1006,6 +1010,17 @@ func (s *Service) deleteChildrenInFolder(ctx context.Context, orgID int64, folde
...
+		dashboardUIDs, err := s.dashboardStore.GetAllDashboardsUIDsInFolders(ctx, &dashboards.GetAllDashboardsInFolderRequest{FolderUIDs: folderUIDs, OrgID: cmd.OrgID})
+		if err != nil {
+			return folder.ErrInternal.Errorf("failed to fetch dashboards: %w", err)
+		}
+
+		err = s.publicDashboardService.DeleteByDashboardUIDs(ctx, cmd.OrgID, dashboardUIDs)
+		if err != nil {
+			return folder.ErrInternal.Errorf("failed to delete public dashboards: %w", err)
+		}
+
```
[the remark this answers is not in the document]
Comment (stephaniehingtgen) [reply pkg/services/folder/folderimpl/folder.go:1023]: I'm probably missing a flow here, but what's the reasoning behind having it in this function and also in the `DeleteInFolders` function in dashboards?

[the remark this answers is not in the document]
Comment (evictorero) [reply pkg/services/folder/folderimpl/folder.go:1023]: This is because when the `forceDeleteRules` is false (this is the value our frontend is sending), the `DeleteInFolders` is not executed.

File: pkg/api/dashboard.go [hunk 5]
```diff
@@ -500,12 +500,6 @@ func (hs *HTTPServer) deleteDashboard(c *contextmodel.ReqContext) response.Respo
 			"error", err)
 	}
 
-	// deletes all related public dashboard entities
-	err = hs.PublicDashboardsApi.PublicDashboardService.DeleteByDashboard(c.Req.Context(), dash)
-	if err != nil {
-		hs.log.Error("Failed to delete public dashboard")
-	}
-
```
Comment (evictorero) [inline pkg/api/dashboard.go:508]: Not needed anymore at api level, it will be called inside the service `hs.DashboardService.DeleteDashboard` below.

File: pkg/services/publicdashboards/service/service.go [hunk 6]
```diff
@@ -459,37 +459,6 @@ func (pd *PublicDashboardServiceImpl) Delete(ctx context.Context, uid string, da
 	return pd.serviceWrapper.Delete(ctx, uid)
 }
 
-func (pd *PublicDashboardServiceImpl) DeleteByDashboard(ctx context.Context, dashboard *dashboards.Dashboard) error {
```
Comment (evictorero) [inline pkg/services/publicdashboards/service/service.go:462]: I moved all deletions to the public dashboard service wrapper to avoid dependency issues.
Now, the dashboard service is responsible for calling the public dashboard deletion.

Comment (juanicabanas) [reply pkg/services/publicdashboards/service/service.go:462]: I agree with the decision but I think it breaks enterprise, since the enterprise service wrapper should implement this new `DeleteByDashboardUIDs` method that will just call the oss wrapper service. Am I correct?

**Comment by juanicabanas** [comment]
What about running a migration for unlinked public dashboards?

File: pkg/services/dashboards/database/database.go (hunk 1 above)
Comment (evictorero) [reply pkg/services/dashboards/database/database.go]: `SearchDashboards` is part of the `DashbaordService` and can't be imported on the folderService because of a circular dependency. I've used the `store.FindDashboards` instead which is what the `SearchDashboards` use under the hood.

**Comment by evictorero** [comment]
> What about running a migration for unlinked public dashboards?

You mean to delete orphan public dashboards right? I think it's a good idea. I will create a new issue to track this.

File: pkg/services/dashboards/service/dashboard_service.go [hunk 7]
```diff
@@ -870,6 +873,12 @@ func (dr *DashboardServiceImpl) deleteDashboard(ctx context.Context, dashboardId
 		}
 	}
 
+	// deletes all related public dashboard entities
```
[the remark this answers is not in the document]
Comment (evictorero) [reply pkg/services/dashboards/service/dashboard_service.go:881]: Good catch!! I've added the public dashboard deletion in the k8s flow.

File: pkg/services/folder/folderimpl/folder.go [hunk 8]
```diff
@@ -1004,14 +1008,36 @@ func (s *Service) deleteChildrenInFolder(ctx context.Context, orgID int64, folde
 }
 
 func (s *Service) legacyDelete(ctx context.Context, cmd *folder.DeleteFolderCommand, folderUIDs []string) error {
+	// if dashboard restore is on we don't delete public dashboards, the hard delete will take care of it later
+	if !s.features.IsEnabledGlobally(featuremgmt.FlagDashboardRestore) {
```
Comment (stephaniehingtgen) [inline pkg/services/folder/folderimpl/folder.go:1012]: You'll also need to add this to `deleteFromApiServer` in `folder_unifiedstorage.go` for this to work in k8s

File: pkg/services/folder/folderimpl/folder_unifiedstorage.go [hunk 9]
```diff
@@ -520,6 +520,26 @@ func (s *Service) deleteFromApiServer(ctx context.Context, cmd *folder.DeleteFol
 		if alertRulesInFolder > 0 {
 			return folder.ErrFolderNotEmpty.Errorf("folder contains %d alert rules", alertRulesInFolder)
 		}
+
+		// if dashboard restore is on we don't delete public dashboards, the hard delete will take care of it later
```
Comment (evictorero) [inline pkg/services/folder/folderimpl/folder_unifiedstorage.go:524]: Adding public dashboard deletion to the k8s flow

**Review by stephaniehingtgen — APPROVED** [review]
LGTM! Tested this out on the normal flow & the k8s flow and everything is looking good. Thanks for fixing this :)

**Review by juanicabanas — APPROVED** [review]
