### PR TITLE
CloudWatch: Prevent log groups from being removed on query change

### LINKED ISSUE #33626: Cloudwatch Logs: Log group required error when I've already selected a log group
**What happened**:
In Explore mode, I chose a log group, tried to run a query, and got a "Log Group required" error

**What you expected to happen**:
I expected no error, because I had already selected a Log Group.

**How to reproduce it (as minimally and precisely as possible)**:
See this 30s video: https://drive.google.com/file/d/1j-xYvT2oza2c0-rLRkavM27IhsgIuY8f/view?usp=sharing

**Anything else we need to know?**:
This is not extremely urgent because I can just select a log group after receiving the error, but it was a little confusing.

**Environment**:
- Grafana version: 7.5.0-beta2
- Data source type & version: Cloudwatch built-in
- OS Grafana is installed on: Docker
- User OS & Browser: Mac, Chrome
- Grafana plugins: 
- Others:

### PR DESCRIPTION
**Pull request by asimpson**
**What this PR does / why we need it**:
Previously when a query was changed the existing log groups for that query were "dropped". The fix is to combine the
new query with the existing query object in memory to preserve the log groups.

**Which issue(s) this PR fixes**:
Fixes #33626

**Special notes for your reviewer**:
1. Have Cloudwatch configured as a datasource
2. Head to explore, `/explore`
3. Add a cloudwatch query
4. Change from metrics to logs if metrics is per-selected
5. Select a log group
6. Insert a query either from the help menu
7. Click `Run Query` and note there is no longer an error message requiring a Log Group

### CODE REVIEW

**Review by fridgepoet — APPROVED** [review]
Nice, just tested it out manually. 

(For the original problem I don't think a metrics query needed to be added first, not sure if that was an intentional extra step on the Special Notes for reviewer)

Edit: oops just saw this was a Draft PR..

**Comment by asimpson** [comment]
@fridgepoet I refactored how this works if you want to take another look?

**Review by sunker — COMMENTED** [review]
Really nice work on this @asimpson! Just a few nits. 

This is a small change to the plugin api, so we should probably let @grafana/plugins-platform-frontend review this before we merge.

File: packages/grafana-data/src/types/datasource.ts [hunk 1]
```diff
@@ -413,6 +413,8 @@ export type ExploreQueryFieldProps<
 
 export interface QueryEditorHelpProps<TQuery extends DataQuery = DataQuery> {
   datasource: DataSourceApi<TQuery>;
+  queries: TQuery[];
+  refId: string;
```
Comment (andresmgot) [inline packages/grafana-data/src/types/datasource.ts:417]: it sounds to me that you can pass only the `query` rather than the list of queries and the refId so you always need to look for it, isn't it?

Also, to make this change backwards compatible, you can make the `query` property optional.

File: public/app/plugins/datasource/cloudwatch/components/LogsCheatSheet.tsx [hunk 2]
```diff
@@ -223,12 +223,21 @@ export default class LogsCheatSheet extends PureComponent<
   }
 
   renderExpression(expr: string, keyPrefix: string) {
+    const existingQuery = this.props.queries.filter((x) => x.refId === this.props.refId)[0] as CloudWatchLogsQuery;
```
[the remark this answers is not in the document]
Comment (andresmgot) [reply public/app/plugins/datasource/cloudwatch/components/LogsCheatSheet.tsx:226]: yeah, I would avoid the type casting so it's safer. You can do something like:

```ts
    const logGroupNames = ('logGroupNames' in existingQuery) ? existingQuery.logGroupNames : [];
```

[the remark this answers is not in the document]
Comment (asimpson) [reply public/app/plugins/datasource/cloudwatch/components/LogsCheatSheet.tsx:226]: Great call out, thanks!

File: public/app/plugins/datasource/cloudwatch/components/LogsCheatSheet.tsx [hunk 3]
```diff
@@ -223,12 +223,21 @@ export default class LogsCheatSheet extends PureComponent<
...
         className="cheat-sheet-item__example"
         key={expr}
-        onClick={(e) =>
-          this.onClickExample({ refId: 'A', expression: expr, queryMode: 'Logs', region: 'default', id: 'A' })
+        onClick={() =>
+          this.onClickExample({
+            refId: this.props.refId,
+            expression: expr,
+            queryMode: 'Logs',
+            region: 'default',
```
[the remark this answers is not in the document]
Comment (asimpson) [reply public/app/plugins/datasource/cloudwatch/components/LogsCheatSheet.tsx:237]: Yep, good idea!

File: packages/grafana-data/src/types/datasource.ts (hunk 1 above)
Comment (asimpson) [reply packages/grafana-data/src/types/datasource.ts:417]: You're absolutely right! I was tracing the queries and forgot we also have query available. This cleans up things quite nicely, thank you.

File: packages/grafana-data/src/types/datasource.ts [hunk 4]
```diff
@@ -416,6 +416,8 @@ export type ExploreQueryFieldProps<
 
 export interface QueryEditorHelpProps<TQuery extends DataQuery = DataQuery> {
   datasource: DataSourceApi<TQuery>;
+  query: TQuery;
+  refId: string;
```
Comment (andresmgot) [inline packages/grafana-data/src/types/datasource.ts:420]: you can also remove the refId from here (it can be accessed with `query.refId`)

File: public/app/plugins/datasource/cloudwatch/components/LogsCheatSheet.tsx [hunk 5]
```diff
@@ -229,8 +229,15 @@ export default class LogsCheatSheet extends PureComponent<
       <div
         className="cheat-sheet-item__example"
         key={expr}
-        onClick={(e) =>
-          this.onClickExample({ refId: 'A', expression: expr, queryMode: 'Logs', region: 'default', id: 'A' })
+        onClick={() =>
+          this.onClickExample({
+            refId: this.props.refId,
```
Comment (andresmgot) [inline public/app/plugins/datasource/cloudwatch/components/LogsCheatSheet.tsx:234]: here you could do `this.props.query.refId ?? 'A'`

**Review by andresmgot — COMMENTED** [review]
LGTM, just one minor comment.

File: public/app/plugins/datasource/cloudwatch/components/LogsCheatSheet.tsx (hunk 5 above)
Comment (asimpson) [reply public/app/plugins/datasource/cloudwatch/components/LogsCheatSheet.tsx:234]: Perfect, fixed.

File: packages/grafana-data/src/types/datasource.ts (hunk 4 above)
Comment (asimpson) [reply packages/grafana-data/src/types/datasource.ts]: Perfect, thanks!

**Review by andresmgot — APPROVED** [review]
LGTM :+1:
