### PR TITLE
Dashboard: Fix plugin dashboard save as button

### LINKED ISSUE #54735: Plugin Dashboard Save As button not working for versioning
https://user-images.githubusercontent.com/16856582/188524933-9914d19b-8163-4196-8278-3ebb4b2fac10.mov

**What happened**: When trying to save a copy of a dashboard using the TestDB, the `Save As...` button doesn't seem to do anything. I looked at the network traffic in developer tools and it doesn't look like this button is triggering any request. The `Overwrite` button works though.

**What you expected to happen**: I expected the plugin dashboard to save a new version `Test`.

**How to reproduce it (as minimally and precisely as possible)**:
- Installed v9.1.2 on an Ubuntu 22 machine
- Add a TestDB datasource
- Made sure the `Simple Streaming Example` dashboard is present in the datasource's dashboards tab. 
- Go to the `Simple Streaming Example` dashboard and make a simple change (change "Angular Graph" panel name to "Angular Graph Test")
- Save dashboard -> Save -> Save As... (this is where the button does not work

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.2
- Data source type & version: TestDB
- OS Grafana is installed on: Ubuntu 22
- User OS & Browser: Mac OS & Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by lpskdl**
**What this PR does / why we need it**:
Render the SaveDashboardErrorProxy component only when error is not yet handled.

https://user-images.githubusercontent.com/108552997/190253529-67e7bc81-2369-4893-840b-782871224833.mov

**Which issue(s) this PR fixes**:

Fixes #54735

### CODE REVIEW

File: public/app/features/dashboard/components/SaveDashboard/SaveDashboardDrawer.tsx [hunk 1]
```diff
@@ -126,7 +126,7 @@ export const SaveDashboardDrawer = ({ dashboard, onDismiss, onSaveSuccess, isCop
     );
   };
 
-  if (state.error && isFetchError(state.error)) {
+  if (state.error && isFetchError(state.error) && !state.error.isHandled) {
```
Comment (polibb) [inline public/app/features/dashboard/components/SaveDashboard/SaveDashboardDrawer.tsx:129]: That's neat 🧉

File: public/app/features/dashboard/components/SaveDashboard/SaveDashboardDrawer.test.tsx [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+
+  const { rerender } = await waitFor(() =>
+    render(
+      <Provider store={store}>
+        <SaveDashboardDrawer dashboard={mockDashboard} onDismiss={mockOnDismiss} />{' '}
+      </Provider>
+    )
+  );
+
+  return { rerender, mockDashboard, store };
```
Comment (polibb) [inline public/app/features/dashboard/components/SaveDashboard/SaveDashboardDrawer.test.tsx:47]: `setup()` is doing too many things: creating a dashboard mock and returning it, configuring store and returning it, and rendering a component and returning it. I think it would be better to have `mockDashboard` as a part of a single `describe()` or even inside a single test whenever it's needed.
The configuration of the store can also just happen as a separate thing once for the whole test module.

File: public/app/features/dashboard/components/SaveDashboard/SaveDashboardDrawer.test.tsx [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+
+    const { rerender, store, mockDashboard } = await setup();
+
+    await userEvent.click(screen.getByRole('button', { name: /save/i }));
+
+    expect(screen.getByRole('button', { name: /cancel/i })).toBeInTheDocument();
+    expect(screen.getByRole('button', { name: /save as/i })).toBeInTheDocument();
+    expect(screen.getByRole('button', { name: /overwrite/i })).toBeInTheDocument();
+
+    rerender(
```
Comment (polibb) [inline public/app/features/dashboard/components/SaveDashboard/SaveDashboardDrawer.test.tsx:73]: From here down it's confusing what is happening, as it seems to be a different test: "renders a corresponding Save new modal if there's an error that has already been handled".

**Review by polibb — APPROVED** [review]
Great initiative with the test 🥳
