### PR TITLE
Fix mentioning Slack users/groups

### LINKED ISSUE #19938: Slack alert message mentions not highlighting or being detected
**What happened**:
Adding a Slack username in the mentions box only includes the raw text in the Slack message, and doesn't act as a proper mention (Username is not highlighted, no notification is sent by Slack)

**What you expected to happen**:
Usernames are treated as proper mentions which highlight them and trigger Slack notifications to those users

**How to reproduce it (as minimally and precisely as possible)**:
Add a username to the Mention field in a Slack notification channel, send a test alert, observe the lack of highlighting in Slack

**Anything else we need to know?**:
Screenshot 2019-10-21 at 16 55 30
Screenshot 2019-10-21 at 16 58 24

Mentioned on the Grafana community too. https://community.grafana.com/t/slack-mentions-not-working/22030

Might be related to https://github.com/grafana/grafana/issues/10450 but thats pretty old..

**Environment**:
- Grafana version: Grafana v6.4.3 (commit: 3a2bfb7)
- Data source type & version: Graphite 
- OS Grafana is installed on: grafana/grafana:6.4.3 Docker image 
- User OS & Browser: MacOS 10.14.6   Safari 13.0.2 
- Grafana plugins: None
- Others:

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Fix mentioning users and groups in Slack notifications. The current mentioning doesn't work, as you need special Markdown syntax in order to mention users and groups with the current Slack API. You also [need to refer to IDs](https://api.slack.com/changelog/2017-09-the-one-about-usernames) instead of user/group handles.

TODO: Check what happens when Json has an old Mention field

**Which issue(s) this PR fixes**:
Fixes #19938.

### CODE REVIEW

File: pkg/services/alerting/notifiers/slack.go [hunk 1]
```diff
@@ -73,25 +75,36 @@ func init() {
...
+        <span class="gf-form-label width-8">Mention User</span>
         <input type="text"
           class="gf-form-input max-width-30"
-          ng-model="ctrl.model.settings.mention"
+          ng-model="ctrl.model.settings.mentionUser"
           data-placement="right">
         </input>
         <info-popover mode="right-absolute">
-          Mention a user or a group using @ when notifying in a channel
+          Mention a user when notifying in a channel
```
Comment (marefr) [inline pkg/services/alerting/notifiers/slack.go]: Need to extend this I think to include that you must reference user id's and how to include multiple

File: pkg/services/alerting/notifiers/slack.go [hunk 2]
```diff
@@ -73,25 +75,36 @@ func init() {
...
       <div class="gf-form max-width-30">
-        <span class="gf-form-label width-6">Token</span>
+        <span class="gf-form-label width-8">Mention Group</span>
+        <input type="text"
+          class="gf-form-input max-width-30"
+          ng-model="ctrl.model.settings.mentionGroup"
+          data-placement="right">
+        </input>
+        <info-popover mode="right-absolute">
+          Mention a group when notifying in a channel
```
Comment (marefr) [inline pkg/services/alerting/notifiers/slack.go]: Need to extend this I think to include that you must reference user id's and how to include multiple

File: pkg/services/alerting/notifiers/slack_test.go [hunk 3]
```diff
@@ -51,19 +51,21 @@ func TestSlackNotifier(t *testing.T) {
...
 				json := `
 				{
           "url": "http://google.com",
           "recipient": "#ds-opentsdb",
           "username": "Grafana Alerts",
           "icon_emoji": ":smile:",
           "icon_url": "https://grafana.com/img/fav32.png",
-          "mention": "@carl",
+          "mentionUser": "user",
+          "mentionGroup": "group",
```
Comment (marefr) [inline pkg/services/alerting/notifiers/slack_test.go]: Would make sense with a test showing multiple user/group mentions

**Review by marefr — CHANGES_REQUESTED** [review]
Looks good. Some minor things, see comments.

Needs to update docs:
- https://grafana.com/docs/grafana/latest/alerting/notifications/#slack
- https://grafana.com/docs/grafana/latest/administration/provisioning/#alert-notification-slack

File: pkg/services/alerting/notifiers/slack.go (hunk 1 above)
Comment (aknuds1) [reply pkg/services/alerting/notifiers/slack.go]: @marefr Oh yeah thanks, slipped my mind.

Comment (aknuds1) [reply pkg/services/alerting/notifiers/slack.go]: @marefr I didn't think of supporting multiple user IDs, what should we use for separator? Space, comma?

File: pkg/services/alerting/notifiers/slack.go (hunk 2 above)
Comment (aknuds1) [reply pkg/services/alerting/notifiers/slack.go]: @marefr Thanks, slipped my mind.

File: pkg/services/alerting/notifiers/slack.go [hunk 4]
```diff
@@ -174,9 +190,20 @@ func (sn *SlackNotifier) Notify(evalContext *alerting.EvalContext) error {
...
 
-	message := sn.Mention
+	message := ""
+	mentionGroup := strings.TrimSpace(sn.MentionGroup)
+	if mentionGroup != "" {
+		message += fmt.Sprintf("<!subteam^%s>", mentionGroup)
+	}
+	mentionUser := strings.TrimSpace(sn.MentionUser)
+	if mentionUser != "" {
+		message += fmt.Sprintf("<@%s>", mentionUser)
```
Comment (papagian) [inline pkg/services/alerting/notifiers/slack.go]: Previously we [assumed](https://grafana.com/docs/grafana/latest/alerting/notifications/#slack) that `@` was included in the user input. I think that it will be confusing and prone to errors if we make the users change usernames to IDs and at the same time remove the `@` character from their existing notifiers.

In any case the existing documentation should be updated too and probably we need to add a note to the next release for letting the users fix their notifiers.

**Review by papagian — CHANGES_REQUESTED** [review]
We need to update the documentation.

File: pkg/services/alerting/notifiers/slack.go (hunk 4 above)
Comment (aknuds1) [reply pkg/services/alerting/notifiers/slack.go]: @papagian My thinking at least is that this is such a radical change, splitting user and group mentions (whereas they used to be one). Also, the `@` sign only works for user mentions now, since the character technically happens to be part of the notification syntax. It doesn't work for group mentions, due to its different syntax, so isn't it just more confusing if you have to use `@` for user mentions and not for group mentions?

Comment (aknuds1) [reply pkg/services/alerting/notifiers/slack.go]: I haven't thought about other types of mentions though, than user or group, since the old tooltip just describes those types of mentions. Not sure how many types of mention targets we should support.

Comment (papagian) [reply pkg/services/alerting/notifiers/slack.go]: probably yes! so just make sure we communicate this properly to the users.

File: docs/sources/alerting/notifications.md [hunk 5]
```diff
@@ -75,20 +75,22 @@ able to access the image.
...
-Url | Slack incoming webhook url.
+Url | Slack incoming webhook URL.
 Username | Set the username for the bot's message.
 Recipient | Allows you to override the Slack recipient.
 Icon emoji | Provide an emoji to use as the icon for the bot's message. Ex :smile:
 Icon URL | Provide a url to an image to use as the icon for the bot's message.
-Mention | make it possible to include a mention in the Slack notification sent by Grafana. Ex @here or @channel
+Mention Users | Mention one or more comma separated users in the Slack notification sent by Grafana. You have to refer to users via their Slack IDs (you can get a user's ID from their Slack profile).
+Mention Groups | Mention one or more comma separated groups in the Slack notification sent by Grafana. You have to refer to groups via their Slack IDs (you can get a group's ID from its Slack profile URL).
+Mention Channel | Mention either all channel members (_@channel_) or just active ones (_@here_).
```
Comment (marefr) [inline docs/sources/alerting/notifications.md]: Maybe better UX to have a drop down with options `Disabled`, `Everyone`, `Every online member`.

File: docs/sources/alerting/notifications.md [hunk 6]
```diff
@@ -75,20 +75,22 @@ able to access the image.
...
 Setting | Description
 ---------- | -----------
-Url | Slack incoming webhook url.
+Url | Slack incoming webhook URL.
 Username | Set the username for the bot's message.
 Recipient | Allows you to override the Slack recipient.
 Icon emoji | Provide an emoji to use as the icon for the bot's message. Ex :smile:
 Icon URL | Provide a url to an image to use as the icon for the bot's message.
-Mention | make it possible to include a mention in the Slack notification sent by Grafana. Ex @here or @channel
+Mention Users | Mention one or more comma separated users in the Slack notification sent by Grafana. You have to refer to users via their Slack IDs (you can get a user's ID from their Slack profile).
```
Comment (marefr) [inline docs/sources/alerting/notifications.md]: Could you maybe include an example url, I'm looking in the slack app but cannot find any id. Do you have to go to website/administration of slack workspace? Same in a few different places that makes me confused.

File: pkg/services/alerting/notifiers/slack.go [hunk 7]
```diff
@@ -110,37 +137,61 @@ func NewSlackNotifier(model *models.AlertNotification) (alerting.Notifier, error
...
 // SlackNotifier is responsible for sending
 // alert notification to Slack.
 type SlackNotifier struct {
 	NotifierBase
-	URL       string
-	Recipient string
-	Username  string
-	IconEmoji string
-	IconURL   string
-	Mention   string
```
Comment (marefr) [inline pkg/services/alerting/notifiers/slack.go]: Think we need to document this as a breaking change as well.

**Review by marefr — CHANGES_REQUESTED** [review]
Some minor things left. See comments. 

Found some proper documentation of the mentioning formatting: https://api.slack.com/reference/surfaces/formatting#advanced

File: docs/sources/alerting/notifications.md (hunk 6 above)
Comment (aknuds1) [reply docs/sources/alerting/notifications.md]: @marefr I'm not sure what you mean by example URL. It's sort of difficult to explain more I think, without going really into detail with screenshots and all. Basically you have to f.ex. right click a username in chat and click their name to visit their profile, from where you can click the "More" button and then "Copy member ID".

I don't think it makes sense to be too detailed here about how to navigate Slack's UI, since it could change and then our documentation is stale.

File: pkg/services/alerting/notifiers/slack.go (hunk 7 above)
Comment (aknuds1) [reply pkg/services/alerting/notifiers/slack.go]: @marefr Is there anything I need to do in this regard?

Comment (bergquist) [reply pkg/services/alerting/notifiers/slack.go]: The breaking change is in Slacks API but our users is still affected so I think it might be a good idea to add a note about this in the changelog.

Comment (aknuds1) [reply pkg/services/alerting/notifiers/slack.go]: @bergquist OK, adding an item to the changelog.

Comment (aknuds1) [reply pkg/services/alerting/notifiers/slack.go]: @marefr @bergquist Added an item to 6.7.0 breaking changes in changelog. Please let me know if I should do it differently.

File: pkg/services/alerting/notifiers/slack.go [hunk 8]
```diff
@@ -73,25 +75,50 @@ func init() {
...
+      </div>
+      <div class="gf-form max-width-30">
+        <span class="gf-form-label width-8">Mention Channel</span>
+        <select
+          class="gf-form-input max-width-30"
+          ng-model="ctrl.model.settings.mentionChannel"
+          data-placement="right">
+		  <option value="">Disabled</option>
+		  <option value="here">Every active channel member</option>
+		  <option value="channel">Every channel member</option>
```
Comment (papagian) [inline pkg/services/alerting/notifiers/slack.go]: there is an additional `everyone` [option](https://api.slack.com/reference/surfaces/formatting#special-mentions) that notifies every person in the #general channel (ie. every non-guest member of a workspace).

Comment (aknuds1) [reply pkg/services/alerting/notifiers/slack.go]: @papagian Yeah, but I didn't really think supporting `@everyone` really made sense since this notification is for a channel. My reasoning was that if you are notifying a channel, why would you also want to notify `#general`? I could be convinced I'm wrong though, maybe there are valid use cases?

**Comment by papagian** [comment]
I suspect that the `Recipient` field also [expects](https://github.com/grafana/grafana/blob/f613214ac5633bf5aefb585bea3e39276b25e9d6/pkg/services/alerting/notifiers/slack.go#L41) group IDs or user IDs.

File: pkg/services/alerting/notifiers/slack.go (hunk 8 above)
Comment (papagian) [reply pkg/services/alerting/notifiers/slack.go]: ok, you have convinced me :)

**Comment by aknuds1** [comment]
> I suspect that the `Recipient` field also [expects](https://github.com/grafana/grafana/blob/f613214ac5633bf5aefb585bea3e39276b25e9d6/pkg/services/alerting/notifiers/slack.go#L41) group IDs or user IDs.

Topic for another PR?

**Comment by papagian** [comment]
> > I suspect that the `Recipient` field also [expects](https://github.com/grafana/grafana/blob/f613214ac5633bf5aefb585bea3e39276b25e9d6/pkg/services/alerting/notifiers/slack.go#L41) group IDs or user IDs.
> 
> Topic for another PR?

It could be, but in that case we need to notify the users to update their rules once again.

**Comment by aknuds1** [comment]
> > > I suspect that the `Recipient` field also [expects](https://github.com/grafana/grafana/blob/f613214ac5633bf5aefb585bea3e39276b25e9d6/pkg/services/alerting/notifiers/slack.go#L41) group IDs or user IDs.
> > 
> > 
> > Topic for another PR?
> 
> It could be, but in that case we need to notify the users to update their rules once again.

Only if the change happens in a different release?

File: CHANGELOG.md [hunk 9]
```diff
@@ -1,6 +1,7 @@
 # 6.7.0 (unreleased)
 
 ## Breaking changes
+* **Slack**: Remove Mention setting and instead introduce _Mention Users_, _Mention Groups_, and _Mention Channel_. The first two settings require user and group IDs respectively. This change was necessary due to the fact that the way of mentioning via the Slack API changed, and mentions in Slack notifications no longer worked.
```
Comment (papagian) [inline CHANGELOG.md]: You could add a link mentioning the modification in the Slack API.

Comment (aknuds1) [reply CHANGELOG.md]: @papagian Done.

File: CHANGELOG.md [hunk 10]
```diff
@@ -1,6 +1,7 @@
 # 6.7.0 (unreleased)
 
 ## Breaking changes
+* **Slack**: Remove Mention setting and instead introduce _Mention Users_, _Mention Groups_, and _Mention Channel_. The first two settings require user and group IDs respectively. This change was necessary due to the fact that the way of mentioning via the Slack API [changed](https://api.slack.com/changelog/2017-09-the-one-about-usernames) and mentions in Slack notifications no longer worked.
```
Comment (oddlittlebird) [inline CHANGELOG.md]:
```suggestion
* **Slack**: Removed _Mention_ setting and instead introduce _Mention Users_, _Mention Groups_, and _Mention Channel_. The first two settings require user and group IDs, respectively. This change was necessary because the way of mentioning via the Slack API [changed](https://api.slack.com/changelog/2017-09-the-one-about-usernames) and mentions in Slack notifications no longer worked.
```

File: docs/sources/alerting/notifications.md [hunk 11]
```diff
@@ -75,20 +75,22 @@ able to access the image.
 
 {{< imgbox max-width="40%" img="/img/docs/v4/slack_notification.png" caption="Alerting Slack Notification" >}}
 
-To set up slack you need to configure an incoming webhook url at slack. You can follow their guide on how
+To set up Slack, you need to configure an incoming Slack webhook URL. You can follow their guide on how
```
Comment (oddlittlebird) [inline docs/sources/alerting/notifications.md]:
```suggestion
To set up Slack, you need to configure an incoming Slack webhook URL. You can follow the Slack guide on how
```

File: docs/sources/alerting/notifications.md [hunk 12]
```diff
@@ -75,20 +75,22 @@ able to access the image.
...
 to do that [here](https://api.slack.com/incoming-webhooks). If you want to include screenshots of the firing alerts
```
Comment (oddlittlebird) [inline docs/sources/alerting/notifications.md]: Please rewrite this so that it removes "here" as the link text. Per the Documentation Style Guide, we want to use descriptive linking text, such as the title of the page being linked to, rather than uninformative verbiage such as "here."

File: docs/sources/alerting/notifications.md [hunk 13]
```diff
@@ -75,20 +75,22 @@ able to access the image.
...
 Setting | Description
 ---------- | -----------
-Url | Slack incoming webhook url.
+Url | Slack incoming webhook URL.
 Username | Set the username for the bot's message.
 Recipient | Allows you to override the Slack recipient.
 Icon emoji | Provide an emoji to use as the icon for the bot's message. Ex :smile:
 Icon URL | Provide a url to an image to use as the icon for the bot's message.
-Mention | make it possible to include a mention in the Slack notification sent by Grafana. Ex @here or @channel
+Mention Users | Optionally mention one or more comma separated users in the Slack notification sent by Grafana. You have to refer to users via their Slack IDs (you can get a user's ID from their Slack profile).
```
Comment (oddlittlebird) [inline docs/sources/alerting/notifications.md]:
```suggestion
Mention Users | Optionally mention one or more comma-separated Slack IDs in the Slack notification sent by Grafana. You can get a user's ID from their Slack profile.
```

File: docs/sources/alerting/notifications.md [hunk 14]
```diff
@@ -75,20 +75,22 @@ able to access the image.
...
+Mention Groups | Optionally mention one or more comma separated groups in the Slack notification sent by Grafana. You have to refer to groups via their Slack IDs (you can get a group's ID from its Slack profile URL).
```
Comment (oddlittlebird) [inline docs/sources/alerting/notifications.md]:
```suggestion
Mention Groups | Optionally mention one or more comma-separated group Slack IDs in the Slack notification sent by Grafana. You can get a group's ID from its Slack profile URL.
```

File: docs/sources/alerting/notifications.md [hunk 15]
```diff
@@ -75,20 +75,22 @@ able to access the image.
...
+Mention Channel | Optionally mention either all channel members or just active ones.
```
Comment (oddlittlebird) [inline docs/sources/alerting/notifications.md]: How do I choose if it will mention all channel members or just active ones?

**Review by oddlittlebird — DISMISSED** [review]

File: docs/sources/alerting/notifications.md (hunk 11 above)
Comment (aknuds1) [reply docs/sources/alerting/notifications.md]: To be honest, I think the older wording is better, since the new wording sounds overly repetitive to my ears (3x Slack in the same sentence). Besides, wording wasn't introduced by my PR, so if you want to change it around I think it's better to make a new PR.

File: docs/sources/alerting/notifications.md (hunk 12 above)
Comment (aknuds1) [reply docs/sources/alerting/notifications.md]: @oddlittlebird The text in question isn't touched by my PR so I think it's out of scope for the review, but since it's such an uncontroversial change, sure.

File: docs/sources/alerting/notifications.md (hunk 13 above)
Comment (aknuds1) [reply docs/sources/alerting/notifications.md]: @oddlittlebird Based on my knowledge of the Slack API specs and my practical usage of it, I think the suggested wording is less technically precise. If I were to read this documentation in order to understand the semantics of the setting, I would definitely find the original wording the most helpful. The reason being that the resulting message mentions users and not IDs; the IDs (and not any kind of Slack IDs, but _user_ IDs in particular) just happen to be how users are referenced when communicating with the Slack API.

File: docs/sources/alerting/notifications.md (hunk 14 above)
Comment (aknuds1) [reply docs/sources/alerting/notifications.md]: See my explanation above.

File: docs/sources/alerting/notifications.md (hunk 15 above)
Comment (aknuds1) [reply docs/sources/alerting/notifications.md]: @oddlittlebird It's self explanatory through the UI options (you can choose "Every active channel member" or "Every channel member").

File: docs/sources/alerting/notifications.md (hunk 13 above)
Comment (oddlittlebird) [reply docs/sources/alerting/notifications.md]: I was mostly trying to combine the two sentences, since they seemed kind of choppy. What about Slack user IDs? If that does not work for you, then just make sure the hyphen in "comma-separated" is added and I shall be happy.

Comment (aknuds1) [reply docs/sources/alerting/notifications.md]: @oddlittlebird I changed to "comma-separated already". I think I see how I can improve the sentence. The basic structure of the sentence is necessary, since while the goal is to mention Slack users, for this setting you have to provide user IDs, so you can't just refer to the latter.

Comment (aknuds1) [reply docs/sources/alerting/notifications.md]: @oddlittlebird I rewrote the sentences a bit, to make it clear that the IDs of the setting must be comma-separated, and that it doesn't apply to the resulting mentions in Slack.

Comment (oddlittlebird) [reply docs/sources/alerting/notifications.md]: Much better, thank you!

File: pkg/services/alerting/notifiers/slack.go [hunk 16]
```diff
@@ -174,9 +225,32 @@ func (sn *SlackNotifier) Notify(evalContext *alerting.EvalContext) error {
 		})
 	}
 
-	message := sn.Mention
+	message := ""
```
Comment (kylebrandt) [inline pkg/services/alerting/notifiers/slack.go]: Should probably be a string builder? Also maybe maybe something like:

```
	foo := ""
	msgAddSpace := func() {
		if foo != "" {
			foo += " "
		}
		return
	}
	msgAddSpace()
``` 

to reduce repetition,  bit with stringbuilder.

Comment (aknuds1) [reply pkg/services/alerting/notifiers/slack.go]: Thanks @kylebrandt - will look into it.

**Review by kylebrandt — APPROVED** [review]

File: pkg/services/alerting/notifiers/slack.go [hunk 17]
```diff
@@ -185,13 +258,21 @@ func (sn *SlackNotifier) Notify(evalContext *alerting.EvalContext) error {
 	}
 
 	body := map[string]interface{}{
+		"blocks": []map[string]interface{}{
```
Comment (marefr) [inline pkg/services/alerting/notifiers/slack.go]: What's the reason for moving message into a block which seem to use `mrkdwn` format? Seems like notifications cannot show preview of message any longer:
image
image

Comment (marefr) [reply pkg/services/alerting/notifiers/slack.go]: Need to verify that it showed preview before

Comment (marefr) [reply pkg/services/alerting/notifiers/slack.go]: On master I see 
image

Comment (aknuds1) [reply pkg/services/alerting/notifiers/slack.go]: @marefr It's because, based on my understanding of Slack's API specs, you need to use an attachment with Markdown in order to mention users/groups/channels. I'll read more closely though, to see if you should e.g. have a fallback message.

Comment (aknuds1) [reply pkg/services/alerting/notifiers/slack.go]: @marefr I fixed the issue. The API specs are really weak on explaining this (I couldn't find the behaviour documented), but it looks as if you need to include a top-level `text` field in your message object, with just plain text (no markup) as a fallback for Web and mobile notifications. You also need the block object in order to deliver mention markup, since that doesn't work in the `text` field.

File: pkg/services/alerting/notifiers/slack_test.go [hunk 18]
```diff
@@ -51,19 +51,23 @@ func TestSlackNotifier(t *testing.T) {
...
 				{
           "url": "http://google.com",
           "recipient": "#ds-opentsdb",
           "username": "Grafana Alerts",
           "icon_emoji": ":smile:",
           "icon_url": "https://grafana.com/img/fav32.png",
-          "mention": "@carl",
+          "mentionUsers": "user1, user2",
+          "mentionGroups": "group1, group2",
+		  "mentionChannel": "here",
```
Comment (papagian) [inline pkg/services/alerting/notifiers/slack_test.go]: Can you fix indentation here?

File: pkg/services/alerting/notifiers/slack.go [hunk 19]
```diff
@@ -185,13 +258,22 @@ func (sn *SlackNotifier) Notify(evalContext *alerting.EvalContext) error {
 	}
 
 	body := map[string]interface{}{
+		"text": evalContext.Rule.Message,
```
Comment (marefr) [inline pkg/services/alerting/notifiers/slack.go]: I think you want to use `evalContext.GetNotificationTitle()` here instead to make it backward compatible.

**Review by marefr — CHANGES_REQUESTED** [review]
Use rule title instead of message, see comment.

**Comment by aknuds1** [comment]
@marefr I put the message back in attachments, only appending a block if there are mentions. Please have another look.

**Review by marefr — APPROVED** [review]
Works as expected. Great!

LGTM

**Review by papagian — APPROVED** [review]
LGTM
