### PR TITLE
Flame Graph: Anchor exact match when clicking a table symbol in search

### LINKED ISSUE #110680: Pyroscope/flamegraph: TOP table "Search for symbol" matches substrings.
#### Describe the bug

The "Search for symbol" function should use properly anchored matching to find exact symbol names.

#### To Reproduce

1. Use the "Search for Symbol" on a symbol that is fully part of another symbol.

#### Example

Example: Clicked "Search for symbol" on "runtime.futex", it machtes 3 longer functions:
 
Image

#### Expected behaviour

The regex after clicking should be anchored on both ends:

Image

#### Additional Context

Most likely related to [#106347](https://github.com/grafana/grafana/pull/106347)

### PR DESCRIPTION
**Pull request by SamarthBagga**
**Which issue(s) does this PR fix?**:

Fixes #110680

### CODE REVIEW

File: packages/grafana-flamegraph/src/TopTable/FlameGraphTopTableContainer.tsx [hunk 1]
```diff
@@ -11,6 +11,7 @@ import {
   GrafanaTheme2,
   MappingType,
 } from '@grafana/data';
+import { escapeStringForRegex } from '@grafana/data';
```
Comment (subhramit) [inline packages/grafana-flamegraph/src/TopTable/FlameGraphTopTableContainer.tsx]: You can add it to the existing `@grafana/data` imports

**Review by subhramit — COMMENTED** [review]
Hey :)

File: packages/grafana-flamegraph/src/TopTable/FlameGraphTopTableContainer.tsx (hunk 1 above)
Comment (SamarthBagga) [reply packages/grafana-flamegraph/src/TopTable/FlameGraphTopTableContainer.tsx]: done ! thanks :)

**Comment by SamarthBagga** [comment]
Hi @ifrost, I have signed the CLA but for some reason it is not reflecting here. What can I do about this ?

**Comment by subhramit** [comment]
> Hi @ifrost, I have signed the CLA but for some reason it is not reflecting here. What can I do about this ?

Your commits are from a different github account wrt the account that raised the PR, which might not have CLA signed.
That could be the issue.

**Comment by samarthbagga-meesho** [comment]
> [CLA assistant check](https://cla-assistant.io/grafana/grafana?pullRequest=111101) All committers have signed the CLA.

Thank you ! Done.

**Comment by ifrost** [comment]
Thanks for submitting it! 🙌  Code wise looks good, I'll try to test it later this week. Also it looks like `packages/grafana-flamegraph/src/FlameGraphContainer.test.tsx` needs fixing

**Comment by SamarthBagga** [comment]
I'll raise a PR to fix the test as well.

**Review by ifrost — APPROVED** [review]

**Comment by ghost** [comment]
:rocket: Your submission is now being built and packaged.

- [GitHub Actions Build](https://github.com/grafana/grafana/actions/runs/18841892819)
- Version: 12.3.0-18841892819
