### PR TITLE
Alerting: Fix evaluation metrics to not count retries

### LINKED ISSUE #85847: Alerting: Evaluation failures metric incremented even if retry succeeds
### What happened?

Retry attempts for rule evaluations are enabled:
```
max_attempts = 3
```

When an alert rule query fails, the `grafana_alerting_rule_evaluation_failures_total` is incremented, even if the query is retried and the evaluation ultimately succeeds.

### What did you expect to happen?

What _should_ happen is perhaps debatable.

Arguably, `grafana_alerting_rule_evaluation_failures_total` should only be incremented if all retries fail for an evaluation cycle.

However there is value in seeing the number of queries fail too. I think my preferred solution, off the top of my head, is to only increment the existing metric when evaluation for that tick fails, and add another metric for e.g. "failed attempts".

### Did this work before?

No

### How do we reproduce it?

1. Create an alert rule
2. Configure `max_attempts = 3` (>1)
3. Have the datasource fail queries
4. Observe the metric increment too often

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.0.0
OS: N/A
Browser: N/A

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by stevesg**
Changes the following metrics to scope multiple retry attempts as a single occurrence:

- `grafana_alerting_rule_evaluation_duration_seconds`
- `grafana_alerting_rule_evaluations_total`
- `grafana_alerting_rule_evaluation_failures_total`

The benefits are:
- To have a consistent count of evaluations, irrespective of the number of retries required.
- To have a count of failures that might need attention. i.e. a successfully retried evaluation is usually not a cause for concern.

The change also adds the following new metrics, which inherit the behavior of the previous metrics.
- `grafana_alerting_rule_evaluation_attempts_total`
- `grafana_alerting_rule_evaluation_attempt_failures_total`

I've opted not to add a duration for individual attempts, I don't think it's worth the additional cardinality, and the information is available through debug log lines if needed.

Fixes #85847

### CODE REVIEW

File: pkg/services/ngalert/schedule/alert_rule.go [hunk 1]
```diff
@@ -233,28 +233,37 @@ func (a *alertRule) Run(key ngmodels.AlertRuleKey) error {
 					a.evalApplied(key, ctx.scheduledAt)
 				}()
 
-				for attempt := int64(1); attempt <= a.maxAttempts; attempt++ {
```
Comment (JacobsonMT) [inline pkg/services/ngalert/schedule/alert_rule.go:236]: So, moving the start of the loop means that rule changes (updates, pauses, moving to new folder, ...) would not affect remaining retry attempts. I imagine the functional impact of this is fairly low / non-existent but just want to confirm that the intent.

Comment (stevesg) [reply pkg/services/ngalert/schedule/alert_rule.go:236]: I did _pause_ a minute to think about this, I think it's reasonable that the state of the rule at the start of the evaluation is used for each attempt. If they're only seconds apart, then I don't know the benefit of having the rule pause/unpause only  seconds earlier, instead of waiting for the next tick.

Comment (stevesg) [reply pkg/services/ngalert/schedule/alert_rule.go:236]: I've reverted the moving of the pause code out of paranoia, and to get this PR merged quicker, we can do it as a cleanup in a subsequent commit.

File: pkg/services/ngalert/schedule/alert_rule.go [hunk 2]
```diff
@@ -227,10 +227,16 @@ func (a *alertRule) Run(key ngmodels.AlertRuleKey) error {
 			}
 
 			func() {
+				orgID := fmt.Sprint(key.OrgID)
```
Comment (grobinson-grafana) [inline pkg/services/ngalert/schedule/alert_rule.go:230]: This is a small nit, but I prefer to use `strconv.Itoa`. It's on average twice as fast as `fmt.Sprint`, and is almost allocation-free for small numbers as it uses a lookup table https://cs.opensource.google/go/go/+/refs/tags/go1.22.2:src/strconv/itoa.go;l=58-81.

**Review by grobinson-grafana — APPROVED** [review]

File: pkg/services/ngalert/schedule/alert_rule.go (hunk 2 above)
Comment (stevesg) [reply pkg/services/ngalert/schedule/alert_rule.go:230]: Fair point - TBH I just moved the code from [lower down the file](https://github.com/grafana/grafana/pull/85873/files#diff-4b931e3d763eee3b0d2027bfcd27ecc38478541f333322a25d59225cd3c80152R324-L316)
