### PR TITLE
QueryVariable: Default to first option when none is set

### LINKED ISSUE #35471: Template Variable Defaults Blanked When Using Data Links Back to Same Dashboard
**What happened**:

When creating a data link to essentially "reset" any change in drop-down variables back to the dashboard defaults (On Dashboard Load) - the dashboard loads correctly (with defaults) - and then immediately blanks out all variables defaults.

**What you expected to happen**:

Not sure why there's an additional refresh of the variables after load that blanks out any defaults. It should not blank out the defaults (on dashboard load).

**How to reproduce it (as minimally and precisely as possible)**:

Dashboard with data link:

That pushes new variables back into the same dashboard:

`/d/${__dashboard.uid}﻿﻿/?var-forecast_day_num=﻿${__data.fields["day_num"]}﻿&var-display_date=${__data.fields.day_start_local}&from=now%2B${__data.fields.day_relative}d%2Fd&to=now%2B${__data.fields.day_relative}d%2Fd&var-interval=1h&${station_name:queryparam}&${tz:queryparam}`

Dashboard presented with new parameters correctly.

Click on the panel link to "reset" back to the dashboard URL without any pushed variables (top Left panel has a panel link):

`URL: /d/${__dashboard.uid}`

Takes me back to the same dashboard as expected and proper... And then a split second later, removes all "on dashboard load" variables to:

Them all being blank. (The variables are in the dropdowns - just the default selection has been wiped out...)

**Anything else we need to know?**:

Rolled back to testing on 7.5.7 and this works as expected.

**Environment**: Linux Docker x64
- Grafana version: 8.0.0 Release - but also tested nightly Grafana v8.1.0-25681pre (f4e9dcd40b)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: MacOS - Version 91.0.4472.77 (Official Build) (x86_64) and Safari Version 14.1.1 (16611.2.7.1.4)
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by tskarhed**
**What this PR does / why we need it**:
To make sure that query variables do not break when the current dashboard is navigated to via an anchor tag.

**Which issue(s) this PR fixes**:
Fixes #35471

**Special notes for your reviewer**:

1. Create query variable with onDashboardLoad
2. Create a panel link that leads to `/d/${__dashboard.uid}`
3. Select a non default value for the query variable
4. Click the panel link
5. The query variables should now be set to default values as opposed to nothing

### CODE REVIEW

File: public/app/features/variables/state/sharedReducer.ts [hunk 1]
```diff
@@ -121,6 +121,15 @@ const sharedReducerSlice = createSlice({
       const { option } = action.payload.data;
       const current = { ...option, text: ensureStringValues(option?.text), value: ensureStringValues(option?.value) };
 
+      // If no value is set, default to the first avilable
+      if (!current.value) {
+        instanceState.current = { ...instanceState.options[0], selected: true };
+        instanceState.options = instanceState.options.map((option, index) =>
+          index === 0 ? instanceState.current : { ...option, selected: false }
+        );
+        return;
```
Comment (torkelo) [inline public/app/features/variables/state/sharedReducer.ts:130]: what happens if options are an empty array? will this crash?  

Since this handler can be written mutably and immer will make it immutable. I think you first can just set all options to selected false except first and set instance.current = instance.options[0] ?

**Review by torkelo — APPROVED** [review]

File: public/app/features/variables/state/sharedReducer.ts (hunk 1 above)
Comment (mckn) [reply public/app/features/variables/state/sharedReducer.ts:130]: Yeah, we need to add a check to make sure we have options.

**Review by mckn — COMMENTED** [review]
Looks good! Just need to add the check that @torkelo mentioned in his comment.

File: public/app/features/variables/state/sharedReducer.ts [hunk 2]
```diff
@@ -121,6 +121,15 @@ const sharedReducerSlice = createSlice({
       const { option } = action.payload.data;
       const current = { ...option, text: ensureStringValues(option?.text), value: ensureStringValues(option?.value) };
 
+      // If no value is set, default to the first avilable
+      if (!current.value && instanceState.options.length) {
+        instanceState.options.forEach((option, index) => {
+          option.selected = !Boolean(index);
```
Comment (tskarhed) [inline public/app/features/variables/state/sharedReducer.ts:127]: Quite enjoyed this fancy little trick :sunglasses:

**Review by torkelo — APPROVED** [review]
