### PR TITLE
Graphite: Fix autocomplete when tags are not available

### LINKED ISSUE #17429: Graphite query auto-complete breaks when using Graphite without tags
**What happened**:
We have a Graphite datasource with tags feature disabled. This breaks the auto-complete feature in the query editor. Note that this only affects the first part of the metric name. If that's filled out manually, the remaining parts auto-complete as expected. It appears that this is happening because the call to `/tags` endpoint fails.

image

**What you expected to happen**:
I expected the auto-complete to show all the top-level metric names in graphite even if the graphite tags are disabled.

**How to reproduce it (as minimally and precisely as possible)**:
Use Graphite DS  that has tag feature disabled. Create a graph in Explore window or in a regular dashboard and click on the metric auto-complete dropdown. The auto-complete will not populate.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.1
- Data source type & version: Graphite, 1.1.x
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Chrome/Windows
- Grafana plugins: -
- Others: -

### PR DESCRIPTION
**Pull request by ifrost**
**What this PR does / why we need it**:

This is to fix #17429. Long story short the query builder's autocomplete input makes 2 requests to graphite-web: one to get a list of metrics and one to get a list of tags and merges both lists together:

dropdown

The problem is when one of the requests fails, nothing is returned in the suggests list.

The request to get the list of tags may fail in two scenarios:

1) Graphite is upgraded to 1.1 (supporting tags) but tags are disabled in the config and the database is not been migrated. No tables for tags are created causing the endpoint to get the list of tags to return HTTP 500.

To mitigate this problem the errors for tags request are caught to return an empty list and the error is displayed in the console.

2) The version of the datasource in the configuration is set to 1.1 (supporting tags) while the actual version of Graphite is lower (without tags support). In this case autocomplete makes a request to non-existing tags endpoint causing the break.

This may however happen unintentionally in some edge cases. When creating a new Graphite data source the version input is initially populated:

graphite-version-dropdown

But this value is not being saved if it's not changed explicitly. In Explore section the query component falls back to `1.1` when the version is not defined, but this fall back was changed in `7.4.0` (from 0.9 to 1.1) meaning that all data sources created before 7.4.0 (intentionally created for 0.9 with the default value in the input) are now treated as 1.1 and make an attempt to get tags, hence breaking autocomplete.

To avoid similar problems in future the initial version is saved when a new data source is created.

We could also automatically detect the version of Graphite by calling `/version` endpoint (https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/version/views.py)

**Which issue(s) this PR fixes**:

Fixes #17429.

### CODE REVIEW

File: public/app/plugins/datasource/graphite/configuration/ConfigEditor.tsx [hunk 1]
```diff
@@ -13,6 +14,7 @@ const graphiteVersions = [
   { label: '1.0.x', value: '1.0' },
   { label: '1.1.x', value: '1.1' },
 ];
+const DEFAULT_GRAPHITE_VERSION = graphiteVersions[2];
```
Comment (aocenas) [inline public/app/plugins/datasource/graphite/configuration/ConfigEditor.tsx:17]: Nitpick: probably makes sense to have `last(graphiteVersions)` so that when new version is added it's automatically the latest version

File: public/app/plugins/datasource/graphite/datasource.ts [hunk 2]
```diff
@@ -473,23 +481,30 @@ export class GraphiteDatasource extends DataSourceApi<GraphiteQuery, GraphiteOpt
...
+          return _.map(results.data, (tag) => {
+            return { text: tag };
+          });
+        } else {
+          return [];
+        }
+      })
+      .catch((error) => {
+        console.error(error);
+        this.displayTagsAutocompleteAlert(error, url);
```
Comment (aocenas) [inline public/app/plugins/datasource/graphite/datasource.ts:496]: I don't think this is a good place to show the error. Error handling should be in general pushed as high in stack as possible to the place where it is clear what to do about it. Datasource code could be possible used from multiple contexts like alerting or other datasources (none of it is true right now but could be in the future) so it can't really know if showing an user error is appropriate. Best way to handle this would be to throw this error and let the caller handle it. In this case I assume it would be the queryEditor component where it is clear that user is interacting with the autocomplete and so makes sense to show him an alert notification.

File: public/app/plugins/datasource/graphite/configuration/ConfigEditor.tsx (hunk 1 above)
Comment (ifrost) [reply public/app/plugins/datasource/graphite/configuration/ConfigEditor.tsx]: I've extracted the list to `graphite_versions.ts` to use the default (now last from the list) in `datasource.ts` and `ConfigEditor.tsx`

File: public/app/plugins/datasource/graphite/datasource.ts (hunk 2 above)
Comment (ifrost) [reply public/app/plugins/datasource/graphite/datasource.ts]: Good point! I've moved error handling to `query_ctrl.ts`. I've also converted `appEvents.emit` to `notifyApp` in `checkOtherSegments()`.

**Comment by ifrost** [comment]
It should also resolve #24287

File: public/app/plugins/datasource/graphite/query_ctrl.ts [hunk 3]
```diff
@@ -415,6 +429,16 @@ export class GraphiteQueryCtrl extends QueryCtrl {
   getCollapsedText() {
     return this.target.target;
   }
+
+  private handleTagsAutoCompleteError(error: Error): void {
+    console.log(error);
+    if (!this._tagsAutoCompleteErrorShown) {
+      this._tagsAutoCompleteErrorShown = true;
+      dispatch(
+        notifyApp(createErrorNotification(`Fetching tags failed: ${error.message}. Check console for more details.`))
```
Comment (aocenas) [inline public/app/plugins/datasource/graphite/query_ctrl.ts:438]: Is there any details for the user that could be interesting in the console log? I would assume only stack trace which would point to our code where we created the error but that's not going to be cause of the problem anyway. So we can keep the console.log for debugging, pointing it out for the user does not seem like it will give them any more useful information.

**Review by aocenas — APPROVED** [review]
One small additional comment but otherwise this look nice, good work.

File: public/app/plugins/datasource/graphite/query_ctrl.ts (hunk 3 above)
Comment (ifrost) [reply public/app/plugins/datasource/graphite/query_ctrl.ts]: Yep, the most useful info is in the network tab and I guess users would check it anyway. I'm removing "Check console..." thing 👍
